### PR TITLE
Circshift no longer throws error for empty array

### LINKED ISSUE #41402: circshift throws DivideError with empty array
I would expect returning the original empty array.

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> circshift([], 1)
ERROR: DivideError: integer division error
Stacktrace:
 [1] div
   @ ./int.jl:261 [inlined]
 [2] div
   @ ./div.jl:217 [inlined]
 [3] div
   @ ./div.jl:262 [inlined]
 [4] fld
   @ ./div.jl:228 [inlined]
 [5] mod
   @ ./int.jl:253 [inlined]
 [6] _circshift!
   @ ./multidimensional.jl:1139 [inlined]
 [7] circshift!(dest::Vector{Any}, src::Vector{Any}, shiftamt::Tuple{Int64})
   @ Base ./multidimensional.jl:1113
 [8] circshift(a::Vector{Any}, shiftamt::Int64)
   @ Base ./abstractarraymath.jl:131
 [9] top-level scope
   @ REPL[1]:1

```

### PR DESCRIPTION
**Pull request by getzze**
Closes JuliaLang#41402

Return the `dest` array if any dimension of `src` is 0. Because of the 0-dimension, no value is stored in the array and `dest==src`.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Terminological nit: these arrays are empty, not zero-dimensional. Zero-dimensional arrays are non-empty and have a single element. Arrays where at least one dimension has size zero are empty. Zero-dimensional arrays cannot be empty because there is no dimension to have size zero.

File: base/multidimensional.jl [hunk 1]
```diff
@@ -1147,6 +1147,7 @@ See also [`circshift`](@ref).
     dest === src && throw(ArgumentError("dest and src must be separate arrays"))
     inds = axes(src)
     axes(dest) == inds || throw(ArgumentError("indices of src and dest must match (got $inds and $(axes(dest)))"))
+    any(size(src) .== 0) && return dest
```
Comment (stevengj) [inline base/multidimensional.jl:1150]:
```suggestion
    isempty(src) && return dest
```

**Review by stevengj — APPROVED** [review]
