### PR TITLE
Fix #11109. Fix sparse matrix-matrix multiplication.

### LINKED ISSUE #11109: At_mul_B! missing for multiplication of sparse and dense matrix in Julia 0.4
In Julia 0.3 following works:
```julia
julia> At_mul_B(sprand(10, 3, 0.5), rand(10, 2))
3x2 Array{Float64,2}:
 1.70632  1.77156
 2.00262  1.86686
 2.76919  2.08001
```
In latest 0.4 I get an error
```julia
julia> At_mul_B(sprand(10, 3, 0.5), rand(10, 2))
ERROR: MethodError: `At_mul_B!` has no method matching At_mul_B!(::Array{Float64,2}, ::Base.SparseMatrix.SparseMatrixCSC{Float64,Int64}, ::Array{Float64,2})
Closest candidates are:
  At_mul_B!{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32)}(::Union(DenseArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),2},SubArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),2,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}), ::Union(DenseArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),2},SubArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),2,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD},DenseArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),1},SubArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),1,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}), ::Union(DenseArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),2},SubArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),2,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD},DenseArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),1},SubArray{T<:Union(Float64,Complex{Float64},Complex{Float32},Float32),1,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}))
  At_mul_B!(::Union(SubArray{T,2,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD},DenseArray{T,2}), ::Union(DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD},SubArray{T,2,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}), ::Union(DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD},SubArray{T,2,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}))
  At_mul_B!(::Base.LinAlg.Diagonal{T}, ::AbstractArray{T,2})
  ...
 in At_mul_B at linalg/matmul.jl:136
```

### PR DESCRIPTION
**Pull request by andreasnoack**
This implements all the sparse-dense matrix-matrix in-place multiplication methods. Also removes `*(AbstractVector, SparseMatrixCSC)` because it is different from the semantics of dense multiplication.

### CODE REVIEW

**Comment by kshyatt** [comment]
:+1: :100: :clap: :tada:

File: test/sparsedir/umfpack.jl [hunk 1]
```diff
@@ -55,4 +55,4 @@ end
 
 #4523 - complex sparse \
 x = speye(2) + im * speye(2)
-@test_approx_eq ((lufact(x) \ ones(2)) * x) (complex(ones(2)))
+@test_approx_eq (x*(lufact(x) \ ones(2))) ones(2)
```
Comment (tkelman) [inline test/sparsedir/umfpack.jl]: needs more tests of various combinations of `[.][']*` - why not add a bunch, plus leave the ones that are already there?

File: base/sparse/cholmod.jl [hunk 2]
```diff
@@ -1325,4 +1325,7 @@ function ishermitian(A::Sparse{Complex{Float64}})
     end
 end
 
+(*){Ti}(A::Symmetric{Float64,SparseMatrixCSC{Float64,Ti}}, B::SparseMatrixCSC{Float64,Ti}) = sparse(Sparse(A)*Sparse(B))
```
Comment (ViralBShah) [inline base/sparse/cholmod.jl]: The `sparse` and `Sparse` are confusing. I wonder if we can do better names. In any case this should not prevent this from getting merged - but thought I'd bring it up right here.

Comment (tkelman) [inline base/sparse/cholmod.jl]: Might be clearer to qualify all calls to this as `CHOLMOD.Sparse` even inside the module, as long as that doesn't slow anything down

File: test/sparsedir/umfpack.jl (hunk 1 above)
Comment (andreasnoack) [inline test/sparsedir/umfpack.jl]: Yes indeed. I've now added all the `.'` variants which should hopefully prevent the issue from reappearing.

File: base/sparse/cholmod.jl (hunk 2 above)
Comment (andreasnoack) [inline base/sparse/cholmod.jl]: I'm open for a discussion about this, but the reasoning is that the namespace takes care of the potential confusion because `Sparse` is not exported.

Comment (ViralBShah) [inline base/sparse/cholmod.jl]: Yes, the namespace definitely makes this not much of an issue.

Comment (tkelman) [inline base/sparse/cholmod.jl]: depends whether people looking at this file are always going to remember that they're inside a module here

Comment (andreasnoack) [inline base/sparse/cholmod.jl]: I don't this will be a huge problem. If you want to do work in this file you'd have to figure out what `Sparse` and `Factor` mean inside the module. Furthermore, this method definition should go away as soon as we provide the functionality in pure Julia which will provide efficiency and element type generality.

Comment (tkelman) [inline base/sparse/cholmod.jl]: last time I compared things, cholmod was quite a bit faster than pure-julia spmm, but this method is easy enough to recreate manually if you know what you're doing

Comment (andreasnoack) [inline base/sparse/cholmod.jl]: I don't think our algorithm will be faster as such, but to use the CHOLMOD version we have to translate the matrices back and forth to `CHOLMOD.Sparse` matrices which adds a little overhead.
