### PR TITLE
while loop -> for loop in _simplify_include_frames (fixes #41566)

### LINKED ISSUE #41566: _simplify_include_frames throws bounds error
Original issue: https://github.com/JuliaLang/PackageCompiler.jl/issues/517

When using a sysimage, `_simplify_include_frames` throws a bounds error at line 804 because `i` is 0. 

https://github.com/JuliaLang/julia/blob/d7329038feb207997b9a6d969c5c8f11d37680d5/base/errorshow.jl#L804

The immediate fix is to move the decrement to the top of the loop and start at `i = length(trace) + 1`. I can make a pull request for this.

This still gives really verbose stack traces when using a sysimage. I'd like to take a shot at improving that as well, but perhaps this should be done in a separate issue/pull request since it might require further discussion.

Thanks to @KristofferC for identifying the problem.

### PR DESCRIPTION
**Pull request by fredcallaway**
prevents the possibility of a bounds error when i = 0

### CODE REVIEW

File: base/errorshow.jl [hunk 1]
```diff
@@ -801,7 +800,7 @@ function _simplify_include_frames(trace)
         i -= 1
```
Comment (thchr) [inline base/errorshow.jl:800]: Seems like this could be removed:
```suggestion
```

Comment (fredcallaway) [reply base/errorshow.jl]: Oops! Thanks for catching that!
