### PR TITLE
[JuliaLowering] Use Expr structure in macro expansion

### LINKED ISSUE #126: "AssertionError: op isa Symbol" when converting `:comparison`
```julia
julia> JuliaLowering.include_string(Main, raw"""
       if version() > v"1.8.3"
           @doc "hello" @enum Apple Fruit Banana
       else
           1
       end
       """)
ERROR: AssertionError: op isa Symbol
Stacktrace:
  [1] _insert_convert_expr(e::Any, graph::JuliaLowering.SyntaxGraph{Dict{Symbol, Any}}, src::LineNumberNode)
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/compat.jl:256
```

### LINKED ISSUE #136: Leaf kinds we don't expect
```
julia> jlower("&")
ERROR: LoweringError:
&
╙ ── invalid syntax

julia> jlower("function (&)(::Int); 1; end")
ERROR: LoweringError:
function (&)(::Int); 1; end
#         ╙ ── Invalid function name
```

`&`, unless it's being called, is `K"&"` instead of `K"Identifier"`. `|` and `:` behave the same.  Are there others?  How do I find out?

I think I'll fix this by converting any unknown leaf kind with a `name_val` to a `K"Identifier"` in EST so they're more consistent with Expr and easier to handle.  Opening an issue to remember, and to consider changing the text->RawGreenNode behaviour instead since this could be called a parser bug.

### LINKED ISSUE #138: Fails to lower short form `@main` function
```julia-repl
julia> using JuliaLowering

julia> JuliaLowering.include_string(Main, "@main(args::Vector{String}) = println(args)")
ERROR: LoweringError:
#= string:1 =# - invalid assignment location

Detailed provenance:
(call main (:: args (curly Vector String)))
└─ (call (escape main) (escape (:: args (curly Vector String))))
   ├─ (call (escape main) (escape (:: args (curly Vector String))))
   │  └─ @ string:1
   └─ (macrocall-p @main (::-i args (curly Vector String)))
      └─ (macrocall-p (macro_name ✘ main) ✘ (::-i args :: (curly Vector ✘ String ✘)) ✘)
         └─ @ string:1

Stacktrace:
  [1] expand_assignment(ctx::JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}}, is_const::Bool)
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/desugaring.jl:1394
  [2] expand_assignment(ctx::JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/desugaring.jl:1267
  [3] expand_forms_2(ctx::JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}}, docs::Nothing)
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/desugaring.jl:4474
  [4] expand_forms_2
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/desugaring.jl:4430 [inlined]
  [5] expand_forms_2
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/desugaring.jl:4684 [inlined]
  [6] lower_step(iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module, world::UInt64)
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:95
  [7] lower_step(iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module)
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:46
  [8] lower_step(iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module, world::UInt64)
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:71
  [9] lower_step
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:46 [inlined]
 [10] _eval(mod::Module, iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}})
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:478
 [11] #eval#135
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:466 [inlined]
 [12] eval
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:462 [inlined]
 [13] #include_string#137
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:535 [inlined]
 [14] include_string
    @ ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:533 [inlined]
 [15] include_string(mod::Module, code::String)
    @ JuliaLowering ~/.julia/packages/JuliaLowering/Lqzhw/src/eval.jl:533
 [16] top-level scope
    @ REPL[4]:1

julia> @main(args::Vector{String}) = println(args)
main (generic function with 1 method)

julia> main(["a"])
["a"]
```

### PR DESCRIPTION
**Pull request by mlechu**
Step 4 in the the plan at https://github.com/JuliaLang/julia/pull/60373.  

Main changes:
- Delete old `expr_to_syntaxtree` (hooray)

- Introduce `est_to_dst`, which does a similar conversion as the above, but can assume all macros have expanded.  (I've chosen "dst" for to mean "desugarable syntax tree" instead of the "current syntax tree" naming I've been using thus far)

- Update macro expansion to be a function EST->EST

- Add the AST validator from https://github.com/JuliaLang/JuliaLowering.jl/pull/93, which I've changed to work on Expr structure.  It's included in this PR so that `est_to_dst` doesn't need to do all the same checking (since nothing can be assumed about the output of macro expansion).  Most of the long write-up there still applies, and using the same assumptions in desugaring could make it much less messy in the future.
  - This also means we're now able to return multiple AST-related syntax errors per top-level thunk, which may be of interest to @aviatesk.  I haven't implemented pretty-printing for this beyond a `for` loop, though.

- We now go though the `Core.@doc`system instead of the `K"doc"`system, which should be a temporary solution before we (1) get JuliaLowering working, then (2) handle docstrings in lowering in both implementations.

- Many tests have been updated with the changes in behaviour.  I've deleted a few where the point of the test is no longer relevant, but otherwise tried to maintain the spirit of each test.

- Changes in syntax_macros.jl to produce the new old AST.  The largest change is to our version of `@ccall`.  Desugaring has also been tweaked so that it can tolerate `@ccall` expanded by flisp.  

stdlib status: There shouldn't be any regressions, and TOML and LibGit2 now precompile.

Atop https://github.com/JuliaLang/julia/pull/60710

### CODE REVIEW

File: test/JuliaLowering_stdlibs.jl [hunk 1]
```diff
@@ -2,12 +2,11 @@ import Libdl
 
 # known precompilation failures under JL
 const INCOMPATIBLE_STDLIBS = String[
-    "LibGit2", # op isa Symbol (JuliaLang/JuliaLowering.jl#126)
+    "LibGit2", # could not evaluate cfunction return type (it might depend on a local variable)
```
Comment (topolarity) [inline test/JuliaLowering_stdlibs.jl]: It looks like this might be related to the `@doc` change:
```julia
julia> JuliaLowering.include_string(Main, raw"""
              "docstring"
              foo() = @cfunction(+, Cint, (Cint, Cint))
              """; expr_compat_mode=true)
```

Fails only if the docstring is included (and does not fail on `master`)

File: JuliaLowering/src/compat.jl [hunk 2]
```diff
@@ -750,3 +143,323 @@ function est_to_expr(st::SyntaxTree)
...
+         when=(get(s, :name_val, "") in ("nospecialize", "specialize"))) -> let
+            if length(vs) === 0
+                @ast g st [K"meta" s=>K"Symbol"]
+            elseif length(vs) === 1
+                out = est_to_dst(vs[1])
+                setmeta(out, Symbol(s), true)
+            else
+                # Kick the can down the road (should only be simple atoms?)
+                out_cs = SyntaxList(g)
+                for v in vars
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl]: undefined var / dead code?

File: JuliaLowering/src/compat.jl [hunk 3]
```diff
@@ -750,3 +143,323 @@ function est_to_expr(st::SyntaxTree)
...
+            mknode(st, out_cs)
+        end
+
+        #-----------------------------------------------------------------------
+        # Heads are not emitted from parsing
+        ([K"meta" [K"unknown_head" ps...]], when=st[1].name_val === "purity") ->
+            @ast g st [K"meta" "purity"::K"Symbol"
+                Base.EffectsOverride([x.value for x in ps]...)::K"Value"]
+        ([K"meta" s vs...],
+         when=(get(s, :name_val, "") in ("nospecialize", "specialize"))) -> let
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl:403]: Why do these two meta forms need special handling?

File: JuliaLowering/src/compat.jl [hunk 4]
```diff
@@ -750,3 +143,323 @@ function est_to_expr(st::SyntaxTree)
...
+            if s in ("ccall", "cglobal")
+                setattr!(newleaf(g, st, K"core"), :name_val, st.name_val)
+            elseif all(==('_'), s)
+                setattr!(mkleaf(st), :kind, K"Placeholder")
+            else
+                st
+            end
+        end
+        (_, when=is_leaf(st)) -> st
+        ([K"unknown_head" l r],
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl:250]: late question for me to ask (since this comes from the existing Expr <-> EST transform), but why do we use `K"unknown_head"`?

I'm assuming it's because we support a pre-determined set of forms in SyntaxTree (in contrast to Expr)? Should we consider moving the 'recognized' ones to first-class forms?

**Review by topolarity — COMMENTED** [review]
Looking good so far

I'll review the validator in more detail in the next review pass

File: JuliaLowering/src/compat.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/src/compat.jl]: Meant to handle the form produced by
```
function f()
    @nospecialize x y z
end
```

File: JuliaLowering/src/compat.jl (hunk 4 above)
Comment (mlechu) [reply JuliaLowering/src/compat.jl:250]: We should consider that for e.g. `symbolicgoto`/`symbolic_goto`, but maybe not for this case, since every `op=` and `.op=` has a different expr head.

File: JuliaLowering/src/compat.jl (hunk 3 above)
Comment (mlechu) [reply JuliaLowering/src/compat.jl:403]: Just what JL desugaring expects at the moment.  I assume we'll make it more consistent at some point.

File: test/JuliaLowering_stdlibs.jl (hunk 1 above)
Comment (mlechu) [reply test/JuliaLowering_stdlibs.jl]: Probably calling the standard `@cfunction` instead of the JL one, since `@doc` calls `macroexpand`.  I haven't done this yet, but we should be compatible with that and standard `@ccall`.  I suppose `macroexpand` should also point to JL.

File: JuliaLowering/src/compat.jl (hunk 2 above)
Comment (topolarity) [reply JuliaLowering/src/compat.jl]: Right, but `vars` seems to be undefined

File: test/JuliaLowering_stdlibs.jl (hunk 1 above)
Comment (topolarity) [reply test/JuliaLowering_stdlibs.jl]: Ah that would explain it!

It would be nice to fix that up before merging, if you agree that's reasonable

File: JuliaLowering/src/compat.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/src/compat.jl]: Oops, thanks.  I thought you were talking about the JL `@nospecialize` not working on this form and never hitting this path, which should also be fixed.

File: test/JuliaLowering_stdlibs.jl (hunk 1 above)
Comment (mlechu) [reply test/JuliaLowering_stdlibs.jl]: Made the SyntaxTree `@cfunction` and `@ccall` behave like the Expr ones.

File: JuliaLowering/src/validation.jl [hunk 5]
```diff
@@ -0,0 +1,972 @@
+struct ValidationDiagnostic <: Exception
+    sts::SyntaxList
+    msg::String
+    loc::LineNumberNode
+end
+ValidationDiagnostic1(st::SyntaxTree, msg, loc) =
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl]: Would it be better just to treat this as a constructor and call this `ValidationDiagnostic`?

File: JuliaLowering/src/validation.jl [hunk 6]
```diff
@@ -0,0 +1,972 @@
...
+        @fail(st, string("unknown expr head: ", st.name_val))
+    [K"$" x] -> @fail(st, raw"`$` expression outside string or quote")
+    _ -> let top_vr = vst1_toplevel_only(vcx, st)
+        if vcx.toplevel
+            top_vr
+        else
+            !top_vr.ok ? unknown() :
+                @fail(st, "this syntax is only allowed at top level")
+        end
+    end | @fail(st, string(
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl:348]: nit: The boolean operators on these are cool, but `|` is maybe hard to intuit IMO

Might be simpler as:
```julia
vr = ...
if !vr.ok && isempty(vr.errors)
    push!(vr.errors, ...) # add fallback error message if there was no reason provided
end
```

I think the `&` operator is more natural since the semantics are a better fit. I'd expect a true "OR" would want to pick the result with fewer errors, since that means it's a more succinct explanation for what went wrong

File: JuliaLowering/src/validation.jl [hunk 7]
```diff
@@ -0,0 +1,972 @@
...
+"""
+The type returned by all `vst` functions.  There are three answers this can
+represent:
+  - valid `(true, [])`
+  - known-invalid `(false, [errors...])`
+  - don't know/not my job `(false, [])`.
+"""
+struct ValidationResult
+    ok::Bool
+    errors::Vector{ValidationDiagnostic}
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl]: It'd be nice if this didn't have to allocate for a "good" result

File: JuliaLowering/src/validation.jl [hunk 8]
```diff
@@ -0,0 +1,972 @@
...
+    ValidationResult(vr1.ok & vr2.ok, union(vr1.errors, vr2.errors))
+end
+
+function Base.var"|"(vr1::ValidationResult, vr2::ValidationResult)
+    vr1.ok && return vr1
+    vr2.ok && return vr2
+    ValidationResult(false, !isempty(vr1.errors) ? vr1.errors : vr2.errors)
+end
+
+function allv(f, vcx, itr; kws...)
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl]: Matter of taste, but it'd be nice to spell this out as `allvalid` or try to re-use `all` with standard semantics

File: JuliaLowering/src/validation.jl [hunk 9]
```diff
@@ -0,0 +1,972 @@
...
+#   lhss as const (ref and .)
+vst1_assign_lhs(
+    vcx, st; in_const=false, in_tuple=false, disallow_type=false
+) = @stm st begin
+    [K"tuple" [K"parameters" xs...]] -> allv(vst1_symdecl, vcx, xs)
+    [K"tuple" xs...] ->
+        allv(vst1_assign_lhs, vcx, xs; in_const, in_tuple=true) &
+        (count(kind(x)===K"..." for x in xs) <= 1 ? pass() :
+        @fail(st, "multiple `...` in destructuring assignment are ambiguous"))
+    # type-annotated tuple segfaults, haha
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl:871]: Oops!

Do you have an MWE for that?

File: JuliaLowering/test/misc.jl [hunk 10]
```diff
@@ -229,16 +260,16 @@ end
     jeval(test_mod, "\"docstr11\" f11(x::T_exists, y::U, z::T) where {T, U<:Number}")
     d = jeval(test_mod, "@doc f11")
     @test d |> string === "docstr11\n"
-    @test d.meta[:results][1].data[:typesig] === Tuple{test_mod.T_exists, U, T} where {T, U<:Number}
+    @test_broken d.meta[:results][1].data[:typesig] === Tuple{test_mod.T_exists, U, T} where {T, U<:Number}
```
Comment (topolarity) [inline JuliaLowering/test/misc.jl]: Can you add a quick comment about why these tests are broken?

File: JuliaLowering/test/misc_ir.jl [hunk 11]
```diff
@@ -34,7 +34,7 @@ x."b"
 @ast_ [K"." "x"::K"Identifier" "a"::K"Identifier" 3::K"Integer"]
 #---------------------
 LoweringError:
-#= line 1 =# - `.` form requires either one or two children
+#= line 1 =# - invalid syntax: unknown form `.` or number of arguments 3
```
Comment (topolarity) [inline JuliaLowering/test/misc_ir.jl:37]: Is it possible to distinguish the "unknown" case from the "wrong # of arguments" case, so that the phrasing is a bit less awkward? I know this is the fallback anyway, so hopefully that doesn't mean a ton of extra error cases, but it'd be worth it for error clarity IMO

File: JuliaLowering/test/misc_ir.jl [hunk 12]
```diff
@@ -148,23 +148,24 @@ LoweringError:
...
+splatting can only be done into a `call`, `tuple`, `curly`, or array-like expression
 
 ########################################
 # Error: Named tuple field invalid lhs
 (; a[]=1)
 #---------------------
 LoweringError:
 (; a[]=1)
-#  └─┘ ── invalid named tuple field name
+#  └───┘ ── invalid syntax: unknown form `kw` or number of arguments 2
```
Comment (topolarity) [inline JuliaLowering/test/misc_ir.jl]: this error message feels like it was better before

File: JuliaLowering/test/misc_ir.jl [hunk 13]
```diff
@@ -235,23 +236,23 @@ LoweringError:
...
+└────┘ ── `braces` outside of `where` is reserved for future use
 
 ########################################
 # Error: braces matrix syntax
 {x y; y z}
 #---------------------
 LoweringError:
 {x y; y z}
-└────────┘ ── { } syntax is reserved for future use
+└────────┘ ── `bracescat` is reserved for future use
```
Comment (topolarity) [inline JuliaLowering/test/misc_ir.jl]: Is it possible for us to change this back? `bracescat` isn't really a user-facing notion

File: JuliaLowering/test/misc_ir.jl [hunk 14]
```diff
@@ -485,55 +474,56 @@ MacroExpansionError while expanding @ccall in module Main.TestMod:
 #---------------------
 MacroExpansionError while expanding @ccall in module Main.TestMod:
 @ccall foo(; x::Int; y::Float64)::Int
-#                  └──────────┘ ── Multiple parameter blocks not allowed
+#          └──────┘ ── C ABI prohibits varargs without one required argument
```
Comment (topolarity) [inline JuliaLowering/test/misc_ir.jl:477]: This error message seems strange. I don't see any varargs here

File: test/JuliaLowering_stdlibs.jl (hunk 1 above)
Comment (topolarity) [reply test/JuliaLowering_stdlibs.jl]: That looked quite non-trivial! thanks for getting it done

File: test/JuliaLowering_stdlibs.jl [hunk 15]
```diff
@@ -2,12 +2,10 @@ import Libdl
 
 # known precompilation failures under JL
 const INCOMPATIBLE_STDLIBS = String[
-    "LibGit2", # op isa Symbol (JuliaLang/JuliaLowering.jl#126)
     "SparseArrays", # type-alias bug (JuliaLang/JuliaLowering.jl#123)
-    "TOML", # @invokelatest / QuoteNode bug
     "Test", # nested + destructured args splat (JuliaLang/JuliaLowering.jl#133)
     "REPL", # infinite softscope (in REPL code)
-    "Pkg", # depends on TOML
+    "Pkg", # depends on LibGit2
```
Comment (topolarity) [inline test/JuliaLowering_stdlibs.jl]:
```suggestion
    "Pkg", # closure w/ kwarg bug (JuliaLang/JuliaLowering.jl#139)
```

Very exciting to be tackling bugs in Pkg now!

File: test/JuliaLowering_stdlibs.jl [hunk 16]
```diff
@@ -2,12 +2,10 @@ import Libdl
 
 # known precompilation failures under JL
 const INCOMPATIBLE_STDLIBS = String[
-    "LibGit2", # op isa Symbol (JuliaLang/JuliaLowering.jl#126)
     "SparseArrays", # type-alias bug (JuliaLang/JuliaLowering.jl#123)
```
Comment (topolarity) [inline test/JuliaLowering_stdlibs.jl]:
```suggestion
    "SparseArrays", # closure static parameter bug (JuliaLang/JuliaLowering.jl#134)
```

just to make you update this since I let it get out-of-date 😅

**Review by topolarity — APPROVED** [review]
This is great. I feel much better about our Expr compat story with this in place.

I'm a particular fan of the validator.

Minor quibbles about error messages and other things, but no major issues. I think this is ready to merge whenever you feel it's ready @mlechu

File: JuliaLowering/src/validation.jl (hunk 9 above)
Comment (mlechu) [reply JuliaLowering/src/validation.jl:871]: Simple cases appear to work, but further destructuring produces IR that attempts to read future ssavalues
```
julia> (q,r,s)=1,1,1
(1, 1, 1)

julia> (q,r,s)::Tuple = (1,2,3)
(1, 2, 3)

julia> ((q,r),s)::Tuple = ((1,2),3)
[65584] signal 11 (2): Segmentation fault: 11
```

This replicates on many versions of julia including 1.0, and the slightly less minimal example `((q,r)::Tuple,s)::Tuple = ((1,2),3)` replicates on all versions that I tried.  Hence I wasn't sure if this is intended to work (validator should pass it) or we should be guarding lowering from this case.

File: JuliaLowering/test/misc.jl (hunk 10 above)
Comment (mlechu) [reply JuliaLowering/test/misc.jl]: When these were written, we weren't producing the same result as `@doc` (which produces something I don't understand):

```
julia> Base.include_string(test_mod, "\"docstr12\" f12(x::Int, y::U, z::T=1) where {T, U<:Number}")
Main.anonymous.f12

julia> d = Base.include_string(test_mod, "@doc f12")
  docstr12

julia> d.meta[:results][1].data[:typesig]
Union{Tuple{U}, Tuple{T}, Tuple{Int64, U}, Tuple{Int64, U, T}} where {T, U<:Number}
```

Now we match `@doc`, which is due for updating soon.  I think I'll delete the tests for now, as they're not great tests anyway.

File: JuliaLowering/src/validation.jl (hunk 6 above)
Comment (mlechu) [reply JuliaLowering/src/validation.jl:348]: Indeed I didn't know what was best in the case of `errors1 | errors2` here.  `&` is the intersection of `ok` and the union of `errors`; `|` would be perfect if we could do the intersection of errors but that doesn't make much sense.

> pick the result with fewer errors

Interesting idea.  We would still need to pick a side if both have the same number, though, and I think the writer of a `|` should know what side produces a more specific error.  

I also wanted to allow  `specific_thing | general_thing | fail`.  Maybe I should use a different operator that doesn't suggest commutativity?  Maybe @StefanKarpinski would like to be informed about this sort of puzzle?

File: JuliaLowering/test/misc_ir.jl (hunk 11 above)
Comment (mlechu) [reply JuliaLowering/test/misc_ir.jl:37]: It would unfortunately wouldn't come for free, since we would either need a ton of extra match cases, or a map that the fallback case looks into (which loses context and needs maintaining).  I'm OK with just having a specific error if the error is particularly reachable or confusing (e.g. a wrong-number-of-children error reachable without macros) and otherwise use the fallback case as an invitation to look at the specification.

It could also be helpful to show the malformed s-expression in a case like this where we don't have source text (we currently show them in errors, but not in the IR tests, and we currently don't print the bad expression, just the provenance of it).

File: JuliaLowering/test/misc_ir.jl (hunk 14 above)
Comment (mlechu) [reply JuliaLowering/test/misc_ir.jl:477]: Just matching the existing `@ccall` error message.  There aren't any julia varargs involved, but `;` is used for C varargs:

```
"""
...
Varargs are supported with the following convention:

    @ccall printf("%s = %d"::Cstring ; "foo"::Cstring, foo::Cint)::Cint

The semicolon is used to separate required arguments (of which there
must be at least one) from variadic arguments.
...
"""
```

File: JuliaLowering/src/validation.jl (hunk 8 above)
Comment (mlechu) [reply JuliaLowering/src/validation.jl]: Good idea, done

**Comment by mlechu** [comment]
@Keno Just FYI changed your new `K"symbolic_block"` to `K"symbolicblock"` since I was also changing its siblings `K"symbolic_goto"` and `K"symbolic_label"` for easier conversion

File: JuliaLowering/test/misc_ir.jl (hunk 14 above)
Comment (topolarity) [reply JuliaLowering/test/misc_ir.jl:477]: TIL! Sorry for the noise

File: JuliaLowering/src/validation.jl (hunk 9 above)
Comment (topolarity) [reply JuliaLowering/src/validation.jl:871]: Great, I mostly wanted to make sure we don't drop the bug. Thanks for filing the issue

File: JuliaLowering/test/misc.jl (hunk 10 above)
Comment (topolarity) [reply JuliaLowering/test/misc.jl]: Sounds reasonable to me 👍

File: JuliaLowering/test/misc_ir.jl (hunk 11 above)
Comment (topolarity) [reply JuliaLowering/test/misc_ir.jl:37]: Yeah, even if it doesn't come for free I think any of these that are reachable from parse-able syntax really ought to be improved.

It's a bit more understandable for macro-crafted syntax, so anything not parser-reachable is probably OK.

File: JuliaLowering/test/misc.jl [hunk 17]
```diff
@@ -222,23 +253,18 @@ end
...
     @test d |> string === "docstr12\n"
-    @test d.meta[:results][1].data[:typesig] === Union{Tuple{Int, U, T}, Tuple{Int, U}} where {T, U<:Number}
 
     # doc-strings on macrocalls (punned on quoted macrocall)
     # TODO: implement and test `doc!` support for this
-    @test jeval(test_mod, """
+    @test_broken jeval(test_mod, """
         "doc string"
         :@test
     """) isa Expr
```
Comment (topolarity) [inline JuliaLowering/test/misc.jl:270]:
```suggestion
    @test jeval(test_mod, """
        "doc string"
        :@test
    """) isa Base.Docs.Binding
```

I think this test might just be out-of-date (but working) w.r.t. the new `@doc` usage:
```julia
julia> "doc string"
       :@test
@test

julia> typeof(ans)
Base.Docs.Binding

julia> JuliaLowering.include_string(Main, raw"""
       "doc string"
       :@test
       """; expr_compat_mode=true)
@test

julia> typeof(ans)
Base.Docs.Binding
```

File: JuliaLowering/src/validation.jl (hunk 6 above)
Comment (topolarity) [reply JuliaLowering/src/validation.jl:348]: Just my $.02 but I think `|` may not be very "natural" for this data structure, esp. since it's only used once (I think) and probably better just to "spell out"

It's pretty common for data structures to have a natural intersection but awkward union or vice-versa. As you mention, it would be great to just intersect the errors but that's not really the correct semantics either. A precise `|` operator seems like it would have to accumulate the error sets, not reduce (similar to how `Float64 | Int` accumulates but `(Float64 | String) & (Int | String)` can faithfully reduce to `String`).

Comment (topolarity) [reply JuliaLowering/src/validation.jl:348]: Reading your response again though, an "ordered choice" operator would make more sense. The truncation of the errors feels a bit like short-circuiting. Maybe `||` would be reasonable for that? I don't think that's overridable though.

`firsterror(...)` or another english spelling might be another way to go?

File: test/JuliaLowering_stdlibs.jl [hunk 18]
```diff
@@ -2,12 +2,10 @@ import Libdl
 
 # known precompilation failures under JL
 const INCOMPATIBLE_STDLIBS = String[
-    "LibGit2", # op isa Symbol (JuliaLang/JuliaLowering.jl#126)
-    "SparseArrays", # type-alias bug (JuliaLang/JuliaLowering.jl#123)
-    "TOML", # @invokelatest / QuoteNode bug
+    "SparseArrays", # closure static parameter bug (JuliaLang/JuliaLowering.jl#134)
     "Test", # nested + destructured args splat (JuliaLang/JuliaLowering.jl#133)
     "REPL", # infinite softscope (in REPL code)
```
Comment (topolarity) [inline test/JuliaLowering_stdlibs.jl]:
```suggestion
```

File: JuliaLowering/src/validation.jl (hunk 6 above)
Comment (mlechu) [reply JuliaLowering/src/validation.jl:348]: It's used in a handful of places, e.g.

```jl
# vst1_struct_special_form allows extra stuff like `const x`
vst1_struct_arg(vcx, st) = vst1_struct_special_form(vcx, st) | vst1(vcx, st)
```

Properly spelling it out would be something like `any_valid_or_first_error`.  Maybe a `Base.any` method would be nicer?  Using the last error may also be worth a try.

File: JuliaLowering/test/misc.jl (hunk 17 above)
Comment (mlechu) [reply JuliaLowering/test/misc.jl:270]: The eventual goal is for top-level docstrings to not change the value of the expression unless it could access an undefined variable or call something where it didn't before.  (`@doc` might still return Base.Docs.Binding though).

File: JuliaLowering/src/validation.jl (hunk 6 above)
Comment (topolarity) [reply JuliaLowering/src/validation.jl:348]: Ah that's fair - I defer to your judgment in that case

Even the original operator might be OK if you want, although best to leave a comment it's not a "faithful" OR operation

**Comment by mlechu** [comment]
I think this is ready to go.  Still feel free to leave comments @c42f
