### PR TITLE
incorporate upstream fixes to crc32c.c

### LINKED ISSUE #52325: incorporate upstream fixes to crc32c code
Our [CRC32c implementation](https://github.com/JuliaLang/julia/blob/5b2fcb68800875e570d7bb8c78ed00d360b6cfd5/src/crc32c.c) was adapted from @madler's (BSD-licensed) code in [this stackoverflow question](https://stackoverflow.com/questions/17645167).   However, I just noticed that he posted a [2021 comment](https://stackoverflow.com/questions/17645167/implementing-sse-4-2s-crc32c-in-software#comment119798529_17646775) that the code has been updated from the version we used:

> SGJ I have updated the code in this answer. The register constraints in the assembly code, which was inherited in your code, had a problem which is now fixed. As well as some other improvements.

I don't know if there is an easy way to get the diff, but we should probably go through it and incorporate any improvements as needed.

For reference, [this](https://github.com/JuliaLang/julia/blob/155437a4b2aa7f31988e4007ced5f5abe22812ad/src/support/crc32c.c) is the version of `crc32c.c` from my initial import, which should be closest to Mark's original code.

*Update*: the `diff` is available on stackoverflow here: https://stackoverflow.com/posts/17646775/revisions … note that there were 3 updates in 2021.

### PR DESCRIPTION
**Pull request by stevengj**
Closes #52325.

I have ~~no~~ only a [vague](https://gcc.gnu.org/onlinedocs/gcc/Simple-Constraints.html) [idea](https://stackoverflow.com/questions/40638326/inline-assembly-clarification-of-constraint-modifiers) what these changes to the `__asm__` register arguments actually do; I just copied them from @madler [upstream](https://stackoverflow.com/questions/17645167/implementing-sse-4-2s-crc32c-in-software/17646775#17646775).  It would be good if @yuyichao or @vtjnash or someone else who knows `__asm__` syntax would take a look.   It looks like they are a response to [this comment](https://stackoverflow.com/questions/17645167/implementing-sse-4-2s-crc32c-in-software/17646775#comment88832559_17646775) on StackOverflow:

> Your asm constraints aren't strictly safe. A pointer in a `"r"` constraint does not imply that the pointed-to memory is also an input. You could just use memory operands (or the `_mm_crc32_u64` intrinsic), but if you want to force the addressing mode you can use a dummy memory operand like `asm("crc32 (%1),%0 " : "+r"(crc0) : "r"(next),  "m" (*(const char (*)[24]) pStr) )`;. Inlining or LTO could break this. See [at&t asm inline c++ problem](https://stackoverflow.com/posts/comments/81680441) (which needs an update: pointer-to-array is cleaner than a struct with a flexible array member).

~~There should be test coverage of this PR via https://github.com/JuliaLang/julia/blob/master/stdlib/CRC32c/test/runtests.jl~~ The existing test coverage wasn't enough to fully exercise Adler's code, so I added another test.

### CODE REVIEW

File: src/crc32c.c [hunk 1]
```diff
@@ -98,16 +101,14 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
        to an eight-byte boundary */
     while (len && ((uintptr_t)buf & 7) != 0) {
         __asm__("crc32b\t" "(%1), %0"
-                : "=r"(crc0)
-                : "r"(buf), "0"(crc0));
+                : "+r"(crc0)
+                : "r"(buf), "m"(*buf));
```
Comment (vtjnash) [inline src/crc32c.c:105]: If I understand my asm constraint parsing correctly at https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Input-Operands, you have changed this from a constraint that it must pick a single register for output (`=r`) that is also chosen as an input register (`r`) with the output assigned to the variable crc0 and the input assigned from the variable crc0 to a constraint that is must pick a single register for input and output (`+r`) for the variable crc0 (this change should not affect code generation)

Secondly, you have added a constraint that the `asm` block will read one byte as represented by the memory expression `*buf` (other C expressions are valid here, such as `buf[0]` to show it is an array read or `((uint64_t*)buf)[0]` to show it is an aligned 64-bit read or `(*(const char (*)[10]) buf)` to show it reads the 10 bytes from `buf[0]` to `buf[9]`

Comment (vtjnash) [reply src/crc32c.c:105]: Note that the readable/alignment constraints are subtractive, not additive. They prevent the compiler from making optimizations that would eliminate those properties, but they do not create constraints that the compiler needs to meet those properties (for TBAA, alignment, etc). Required constraints must already be met during declaration/allocation, with the right type and alignment, for example.

Comment (stevengj) [reply src/crc32c.c:105]: > Secondly, you have added a constraint that the asm block will read one byte as represented by the memory expression `*buf`

Based on the SO comment above, this is a dummy argument that implicitly fixes the safety of the preceding `"r"(buf)` argument somehow.

Comment (vtjnash) [reply src/crc32c.c:105]: Right, the `"r"(buf)` constraint (unchanged) says that the variable `buf` is assigned to the expression `%0` which must be an input register, but says nothing about it being a pointer. The `"m"(*buf)` says that the value `*buf` must be computed by the expression `%3` (which is unused in the actual assembly) and must be valid as input

Comment (vtjnash) [reply src/crc32c.c:105]: Another comment on SO also noted similarly, for that reason, that these could be combined as something like
```
__asm__ ("crc32b\t" "%1, %0"
                : "=r"(crc0)
                : "rm"(*buf) : )
```

which instead says that `%1` must be either the value `*buf` in a register or as a memory load expression that computes  `*buf`

Comment (stevengj) [reply src/crc32c.c:105]: Thanks!

I guess I'll leave it as-is, since in either case it sounds like code generation is unchanged, and in the current form it is easier to compare to the upstream version.  But `"rm"(*buf)` does look a bit cleaner.

File: src/crc32c.c [hunk 2]
```diff
@@ -116,8 +117,8 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
             __asm__(CRC32_PTR "\t" "(%3), %0\n\t"
                     CRC32_PTR "\t" LONGx1 "(%3), %1\n\t"
                     CRC32_PTR "\t" LONGx2 "(%3), %2"
-                    : "=r"(crc0), "=r"(crc1), "=r"(crc2)
-                    : "r"(buf), "0"(crc0), "1"(crc1), "2"(crc2));
+                    : "+r"(crc0), "+r"(crc1), "+r"(crc2)
+                    : "r"(buf), "m"(* (const char (*)[LONG*3]) buf));
```
Comment (stevengj) [inline src/crc32c.c:121]: I merged this suggestion by @vtjnash, but upon reflection it seems incorrect.  The `buf` pointer is incremented during the loop, so it is wrong to say that `LONG*3` bytes from the *current* value of `buf` are being accessed.
```suggestion
                    : "r"(buf), "m"(*buf));
```

File: src/crc32c.c [hunk 3]
```diff
@@ -116,8 +117,8 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
             __asm__(CRC32_PTR "\t" "(%3), %0\n\t"
                     CRC32_PTR "\t" LONGx1 "(%3), %1\n\t"
                     CRC32_PTR "\t" LONGx2 "(%3), %2"
-                    : "=r"(crc0), "=r"(crc1), "=r"(crc2)
-                    : "r"(buf), "0"(crc0), "1"(crc1), "2"(crc2));
+                    : "+r"(crc0), "+r"(crc1), "+r"(crc2)
+                    : "r"(buf), "m"(*buf));
```
[the remark this answers is not in the document]
Comment (stevengj) [reply src/crc32c.c:121]: I merged this, but reverted it.  Because the `buf` pointer is incremented throughout the loop, it is not necessarily a pointer to at least `LONG*3` bytes.

(Besides, in each iteration aren't only 4 bytes being read/written?)

File: src/crc32c.c (hunk 1 above)
Comment (stevengj) [reply src/crc32c.c:105]: the actual number of bytes being accessed by `CRC32_PTR` is `sizeof(void*)`, no?

File: src/crc32c.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply src/crc32c.c:121]: `*buf` only reads 1 byte, so it would be incorrect for the assembly to read more than that. This assembly reads `LONG*3` bytes starting at pointer however

[the remark this answers is not in the document]
Comment (vtjnash) [reply src/crc32c.c:121]: Oh, I see, they are not sequential reads though, but rather `LONG` bytes apart, so we need to write out the indexing call for each of those:
```suggestion
                    : "r"(buf),
                    "m"(* (const char (*)[sizeof(void*)]) &buf[0]),
                    "m"(* (const char (*)[sizeof(void*)]) &buf[LONG]),
                    "m"(* (const char (*)[sizeof(void*)]) &buf[LONG*2]));
```

File: src/crc32c.c [hunk 4]
```diff
@@ -136,8 +140,8 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
             __asm__(CRC32_PTR "\t" "(%3), %0\n\t"
                     CRC32_PTR "\t" SHORTx1 "(%3), %1\n\t"
                     CRC32_PTR "\t" SHORTx2 "(%3), %2"
-                    : "=r"(crc0), "=r"(crc1), "=r"(crc2)
-                    : "r"(buf), "0"(crc0), "1"(crc1), "2"(crc2));
+                    : "+r"(crc0), "+r"(crc1), "+r"(crc2)
+                    : "r"(buf), "m"(*buf));
```
Comment (stevengj) [inline src/crc32c.c:144]: Needs a similar change to the `"m"(...)` directive, no?

Comment (stevengj) [inline src/crc32c.c:144]: Something like:
```suggestion
                    : "r"(buf),
                      "m"(* (const char (*)[sizeof(void*)]) &buf[0]),
                      "m"(* (const char (*)[sizeof(void*)]) &buf[SHORT]),
                      "m"(* (const char (*)[sizeof(void*)]) &buf[SHORT*2]));
```

File: src/crc32c.c [hunk 5]
```diff
@@ -116,8 +117,11 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
             __asm__(CRC32_PTR "\t" "(%3), %0\n\t"
                     CRC32_PTR "\t" LONGx1 "(%3), %1\n\t"
                     CRC32_PTR "\t" LONGx2 "(%3), %2"
-                    : "=r"(crc0), "=r"(crc1), "=r"(crc2)
-                    : "r"(buf), "0"(crc0), "1"(crc1), "2"(crc2));
+                    : "+r"(crc0), "+r"(crc1), "+r"(crc2)
+                    : "r"(buf),
+                    "m"(* (const char (*)[sizeof(void*)]) &buf[0]),
+                    "m"(* (const char (*)[sizeof(void*)]) &buf[LONG]),
+                    "m"(* (const char (*)[sizeof(void*)]) &buf[LONG*2]));
```
Comment (stevengj) [inline src/crc32c.c:124]: indenting:
```suggestion
                      "m"(* (const char (*)[sizeof(void*)]) &buf[0]),
                      "m"(* (const char (*)[sizeof(void*)]) &buf[LONG]),
                      "m"(* (const char (*)[sizeof(void*)]) &buf[LONG*2]));
```

File: src/crc32c.c (hunk 4 above)
Comment (stevengj) [inline src/crc32c.c:144]:
```suggestion
                    : "r"(buf), "m"(* (const char (*)[sizeof(void*)]) buf));
```

File: src/crc32c.c [hunk 6]
```diff
@@ -151,17 +155,17 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
     const char *end = buf + (len - (len & 7));
     while (buf < end) {
         __asm__(CRC32_PTR "\t" "(%1), %0"
-                : "=r"(crc0)
-                : "r"(buf), "0"(crc0));
+                : "+r"(crc0)
+                : "r"(buf), "m"(*buf));
```
Comment (stevengj) [inline src/crc32c.c:159]:
```suggestion
                : "r"(buf), "m"(* (const char (*)[sizeof(void*)]) buf));
```

File: src/crc32c.c [hunk 7]
```diff
@@ -151,17 +155,17 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
...
     }
     len &= 7;
 
     /* compute the crc for up to seven trailing bytes */
     while (len) {
         __asm__("crc32b\t" "(%1), %0"
-                : "=r"(crc0)
-                : "r"(buf), "0"(crc0));
+                : "+r"(crc0)
+                : "r"(buf), "m"(*buf));
```
Comment (stevengj) [inline src/crc32c.c:168]:
```suggestion
                : "r"(buf), "m"(* (const char (*)[sizeof(void*)]) buf));
```

Comment (stevengj) [reply src/crc32c.c:168]: whoops, no, this is a single-byte read

File: src/crc32c.c [hunk 8]
```diff
@@ -151,17 +158,17 @@ static uint32_t crc32c_sse42(uint32_t crc, const char *buf, size_t len)
     const char *end = buf + (len - (len & 7));
     while (buf < end) {
         __asm__(CRC32_PTR "\t" "(%1), %0"
-                : "=r"(crc0)
-                : "r"(buf), "0"(crc0));
+                : "+r"(crc0)
+                : "r"(buf), "m"(*buf));
```
Comment (stevengj) [inline src/crc32c.c:162]:
```suggestion
                : "r"(buf), "m"(* (const char (*)[sizeof(void*)]) buf));
```

**Comment by stevengj** [comment]
@vtjnash, I updated the other constraints following your example.  Looks good?

**Review by vtjnash — APPROVED** [review]

**Comment by stevengj** [comment]
Are the constraints actually impossible or is this a compiler bug?

**Comment by stevengj** [comment]
See https://github.com/JuliaLang/julia/pull/52437 for updated constraints to fix the 32-bit debug build.

**Comment by madler** [comment]
You don't need the `r` in `"rm"`. The `r` was a mistake on my part, and leaving it out permits more compiler optmization on addressing modes and unrolling loops. gcc doesn't do much with it, but clang really goes to town.

If you have different input constraints for the three instructions in one `__asm__`, then they need to be numbered appropriately in each instruction, `%3`, `%4`, and `%5` respectively for the three constraints. Or you can just make it three different `__asm__`s as suggested.

**Comment by stevengj** [comment]
@madler, the reason we use `sizeof(void*)` is that the instruction we are using is `crc32q` on a 64-bit machine and `crc32l` on a 32-bit machine.  (Patch by @yuyichao in #22385.)

**Comment by madler** [comment]
Ah, ok.

**Comment by vtjnash** [comment]
> The r was a mistake on my part, and leaving it out permits more compiler optmization in addressing modes and unrolling loops

What gives that more options, when "rm" seems to mean "select either a register or a memory expression", which is stricly more optimization permission, and the crc32 instruction permits either form? They seem to generate identical code for me (at optimization levels at or above -Og anyways)

**Comment by madler** [comment]
These examples are with clang 15, using `-O3`.

The `r` appears to force the use of a pre-computed pointer:

```
.LBB0_14:                               #   Parent Loop BB0_13 Depth=1
                                        # =>  This Inner Loop Header: Depth=2
	movq	%rbx, %rbp
	movq	8(%rsi,%rdi), %rbx
	movq	8200(%rsi,%rdi), %rcx
	movq	16392(%rsi,%rdi), %rax
	movq	%rcx, -24(%rsp)
	movq	%rbx, -16(%rsp)
	movq	%rbp, %rbx
	movq	%rax, -32(%rsp)
	#APP
	crc32q	-16(%rsp), %rbx
	crc32q	-24(%rsp), %rdx
	crc32q	-32(%rsp), %r10
	#NO_APP
	addq	$8, %rdi
	cmpq	$8184, %rdi                     # imm = 0x1FF8
	jb	.LBB0_14
```

Whereas without the `r`, more creative addressing modes are used:

```
.LBB0_21:                               #   Parent Loop BB0_20 Depth=1
                                        # =>  This Inner Loop Header: Depth=2
	#APP
	crc32q	(%rsi,%rdi), %rcx
	crc32q	(%rdx,%rdi), %rbx
	crc32q	(%r10,%rdi), %rax
	#NO_APP
	leaq	8(%rdi), %rbp
	cmpq	$8184, %rdi                     # imm = 0x1FF8
	movq	%rbp, %rdi
	jb	.LBB0_21
```

The subsequent shorter loop with three `crc32q`'s results in a simple loop like above. Without the `r`, the loop is unrolled, since it can apply offsets in the memory address:

```
.LBB0_11:                               # =>This Inner Loop Header: Depth=1
	xorl	%ebx, %ebx
	xorl	%edx, %edx
	#APP
	crc32q	(%rsi), %rax
	crc32q	256(%rsi), %rbx
	crc32q	512(%rsi), %rdx
	#NO_APP
	#APP
	crc32q	8(%rsi), %rax
	crc32q	264(%rsi), %rbx
	crc32q	520(%rsi), %rdx
	#NO_APP
```
...
```
	#APP
	crc32q	248(%rsi), %rax
	crc32q	504(%rsi), %rbx
	crc32q	760(%rsi), %rdx
```
