### PR TITLE
Include world age in thread work

### LINKED ISSUE #19876: Multi-threading doesn't work on master
I reported on [discourse](https://discourse.julialang.org/t/wrong-results-with-multi-threading-in-julia-master/1298?u=giordano) a problem, but didn't get any feedback, so I don't know if anyone else can reproduce it.

Currently, multi-threading doesn't seem to work on master branch (at least on my system).  Using the [example](http://docs.julialang.org/en/latest/manual/parallel-computing.html#Multi-Threading-%28Experimental%29-1) proposed in the manual:

```julia
julia> versioninfo()
Julia Version 0.6.0-dev.1928
Commit cbc6670 (2017-01-05 11:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> Threads.nthreads()
4

julia> a = zeros(10);

julia> Threads.@threads for i = 1:10
           a[i] = Threads.threadid()
       end

julia> a
10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```

As show in the discourse message, the same example works on my system with Julia 0.5.

I could not find any reference to this problem in the bug tracker, I assume it's a new issue.

### PR DESCRIPTION
**Pull request by yuyichao**
Similar to how we deal with `current_module`.

Fix #19876

### CODE REVIEW

**Comment by yuyichao** [comment]
I triggered two threading buildbot build at https://build.julialang.org/builders/nightly_threading-x64
and https://build.julialang.org/builders/nightly_threading-x86. There are other known failures though so they might still hang in the threading tests.

File: src/threading.h [hunk 1]
```diff
@@ -43,6 +43,7 @@ typedef struct {
     jl_svec_t     *args;
     jl_value_t    *ret;
     jl_module_t   *current_module;
+    size_t world_age;
```
Comment (tkelman) [inline src/threading.h]: may as well align it with the other fields?

**Review by vtjnash — APPROVED** [review]

**Comment by yuyichao** [comment]
The [32bit one](https://build.julialang.org/builders/nightly_threading-x86/builds/576/steps/make%20testall/logs/stdio) shows the expected intermittent hang. The [64bit one](https://build.julialang.org/builders/nightly_threading-x64/builds/601) seems to have built the wrong version....

> Revision	770898e984e0f676a759946405983ee3b307eca1
> Got Revision	84d9eac66a4ab72bb56b94975c93abf3892167a2

@staticfloat

**Comment by staticfloat** [comment]
Huh, weird, when it tried to check it out, `git` said `fatal: Could not parse object '770898e984e0f676a759946405983ee3b307eca1'.`  I've asked it to do another one, to see if it works any better this time around.

**Comment by kshyatt** [comment]
@staticfloat what was the outcome?

**Comment by staticfloat** [comment]
Oh, I see what happened.  You force-pushed to this branch, so the commit 770898e984e0f676a759946405983ee3b307eca1 disappeared and the buildbot got confused.  I've started up a new build against gitsha 673e6f0fdb852c462ea67069c560b5c722b4aa69 now.
