### PR TITLE
Fix type instability of closures capturing types (2)

### LINKED ISSUE #23618: type inference problem with captured type in closures
```julia
function foo(a::AbstractVector)
    T = eltype(a)
    b = Vector{T}()
    c = [Set{T}() for x in a]
    return length(c)
end

a = rand(1:10, 200);
```
`@code_warntype` shows an inference failure in `b` and `c`.

Changing to `c = Set{T}[Set{T}() for x in a]` fixes `c`'s inference issue.

### PR DESCRIPTION
**Pull request by simeonschaub**
Instead of closures lowering to `typeof` for the types of captured fields, this introduces a new function `_typeof_captured_variable` that returns `Type{T}` if `T` is a type (w/o free typevars). Also adds special inference support for that function to make it a no-op in most cases.

replaces/closes #35970
fixes #23618

### CODE REVIEW

File: base/compiler/compiler.jl [hunk 1]
```diff
@@ -19,6 +19,8 @@ eval(m, x) = Core.eval(m, x)
 include(x) = Core.include(Compiler, x)
 include(mod, x) = Core.include(mod, x)
 
+const _typeof_prefer_singleton = Core.typeof
```
Comment (tkf) [inline base/compiler/compiler.jl:22]: nitpick: maybe the name is a bit confusing now? how about something like `_typeof_captured_variable`?

File: base/Base.jl [hunk 2]
```diff
@@ -34,6 +34,16 @@ getproperty(x, f::Symbol) = getfield(x, f)
 dotgetproperty(x, f) = getproperty(x, f)
 setproperty!(x, f::Symbol, v) = setfield!(x, f, convert(fieldtype(typeof(x), f), v))
 
+# for closures
+function _typeof_prefer_singleton(Core.@nospecialize x)
+    if x isa DataType
+        if x.layout === Ptr{Nothing}(0)  # we don't have C_NULL yet
```
Comment (tkf) [inline base/Base.jl:40]: I think this works inside `Base`?

```suggestion
        if x.layout === C_NULL
```

Comment (tkf) [reply base/Base.jl]: Let the CI figure out...

File: base/compiler/compiler.jl (hunk 1 above)
Comment (simeonschaub) [reply base/compiler/compiler.jl:22]: Yeah, I think that would make more sense.

**Comment by tkf** [comment]
I just run `]test ChainRules`. Just eyeballing the test result, I don't see a major regression. Though maybe `rulesets/LinearAlgebra/symmetric.jl` is slower? (307 in this PR to 251 on master)

### This PR

```
Testing ChainRules.jl
Testing rulesets/Base/base.jl:
...
113.387431 seconds (194.65 M allocations: 11.406 GiB, 4.15% gc time, 0.18% compilation time)
Testing rulesets/Base/fastmath_able.jl:
135.469393 seconds (201.52 M allocations: 11.869 GiB, 3.89% gc time, 0.03% compilation time)
Testing rulesets/Base/evalpoly.jl:
 35.726451 seconds (64.08 M allocations: 3.702 GiB, 3.45% gc time, 76.07% compilation time)
Testing rulesets/Base/array.jl:
 10.367831 seconds (17.88 M allocations: 1.074 GiB, 3.64% gc time, 21.27% compilation time)
Testing rulesets/Base/arraymath.jl:
...
188.849576 seconds (341.39 M allocations: 19.978 GiB, 3.86% gc time, 92.38% compilation time)
Testing rulesets/Base/indexing.jl:
 17.777968 seconds (26.13 M allocations: 1.505 GiB, 3.51% gc time, 98.34% compilation time)
Testing rulesets/Base/mapreduce.jl:
113.682090 seconds (221.61 M allocations: 12.675 GiB, 5.68% gc time, 0.00% compilation time)
Testing rulesets/Base/sort.jl:
  9.309037 seconds (14.99 M allocations: 894.253 MiB, 4.40% gc time, 10.71% compilation time)

Testing rulesets/Statistics/statistics.jl:
  3.154018 seconds (5.54 M allocations: 337.662 MiB, 6.72% gc time, 18.29% compilation time)

Testing rulesets/LinearAlgebra/dense.jl:
 90.476702 seconds (144.34 M allocations: 8.792 GiB, 4.83% gc time, 20.87% compilation time)
Testing rulesets/LinearAlgebra/norm.jl:
153.307127 seconds (241.14 M allocations: 14.354 GiB, 4.56% gc time, 0.00% compilation time)
Testing rulesets/LinearAlgebra/matfun.jl:
 16.050503 seconds (27.39 M allocations: 2.706 GiB, 8.82% gc time, 0.37% compilation time)
Testing rulesets/LinearAlgebra/structured.jl:
 81.032083 seconds (112.20 M allocations: 6.698 GiB, 3.87% gc time, 21.03% compilation time)
Testing rulesets/LinearAlgebra/symmetric.jl:
307.083321 seconds (385.80 M allocations: 45.909 GiB, 6.67% gc time, 0.46% compilation time)
...
Testing rulesets/LinearAlgebra/blas.jl:
 57.792782 seconds (93.93 M allocations: 7.993 GiB, 5.22% gc time, 0.00% compilation time)
Testing rulesets/LinearAlgebra/lapack.jl:
 18.828087 seconds (29.57 M allocations: 1.831 GiB, 4.03% gc time, 17.00% compilation time)

Testing rulesets/Random/random.jl:
  0.783869 seconds (821.83 k allocations: 50.719 MiB, 90.65% compilation time)

Testing rulesets/packages/NaNMath.jl:
  0.000138 seconds (56 allocations: 4.266 KiB)

...

julia> Base.GIT_VERSION_INFO
Base.GitVersionInfo("75086967ef7e5385b54369cb0f99b8eb9cc7480b", "75086967ef", "sds/tkf/type-capturing", 1189, "2021-05-28 18:48 UTC", false, 3, 1.622195605e9)
```

### master

```
Testing ChainRules.jl
Testing rulesets/Base/base.jl:
...
110.912486 seconds (191.40 M allocations: 11.192 GiB, 3.72% gc time, 0.18% compilation time)
Testing rulesets/Base/fastmath_able.jl:
133.547750 seconds (199.73 M allocations: 11.757 GiB, 3.86% gc time, 0.03% compilation time)
Testing rulesets/Base/evalpoly.jl:
 34.510045 seconds (63.45 M allocations: 3.660 GiB, 3.54% gc time, 75.96% compilation time)
Testing rulesets/Base/array.jl:
 10.106647 seconds (17.67 M allocations: 1.061 GiB, 3.55% gc time, 20.78% compilation time)
Testing rulesets/Base/arraymath.jl:
...
185.997513 seconds (339.63 M allocations: 19.862 GiB, 4.00% gc time, 92.22% compilation time)
Testing rulesets/Base/indexing.jl:
 17.365063 seconds (25.89 M allocations: 1.489 GiB, 3.21% gc time, 98.30% compilation time)
Testing rulesets/Base/mapreduce.jl:
110.458438 seconds (220.21 M allocations: 12.584 GiB, 4.98% gc time, 0.00% compilation time)
Testing rulesets/Base/sort.jl:
  9.054407 seconds (14.83 M allocations: 882.215 MiB, 4.29% gc time, 11.54% compilation time)

Testing rulesets/Statistics/statistics.jl:
  3.022534 seconds (5.51 M allocations: 335.324 MiB, 4.24% gc time, 16.47% compilation time)

Testing rulesets/LinearAlgebra/dense.jl:
 88.285892 seconds (143.68 M allocations: 8.751 GiB, 4.53% gc time, 20.88% compilation time)
Testing rulesets/LinearAlgebra/norm.jl:
150.491677 seconds (239.33 M allocations: 14.238 GiB, 4.41% gc time, 0.00% compilation time)
Testing rulesets/LinearAlgebra/matfun.jl:
 16.358479 seconds (27.57 M allocations: 2.718 GiB, 9.26% gc time, 0.36% compilation time)
Testing rulesets/LinearAlgebra/structured.jl:
 76.466074 seconds (108.54 M allocations: 6.501 GiB, 4.32% gc time, 22.90% compilation time)
Testing rulesets/LinearAlgebra/symmetric.jl:
251.823712 seconds (348.90 M allocations: 44.452 GiB, 7.87% gc time, 0.61% compilation time)
...
Testing rulesets/LinearAlgebra/blas.jl:
 56.097692 seconds (93.35 M allocations: 7.957 GiB, 5.91% gc time, 0.00% compilation time)
Testing rulesets/LinearAlgebra/lapack.jl:
 18.680355 seconds (29.96 M allocations: 1.859 GiB, 4.90% gc time, 17.17% compilation time)

Testing rulesets/Random/random.jl:
  0.771533 seconds (817.91 k allocations: 50.452 MiB, 90.70% compilation time)

Testing rulesets/packages/NaNMath.jl:
  0.000109 seconds (56 allocations: 4.266 KiB)

...

julia> Base.GIT_VERSION_INFO
Base.GitVersionInfo("61701d7a84be62beaf129b2178ede42882a7a46a", "61701d7a84", "master", 1186, "2021-05-28 09:53 UTC", false, 0, 1.622195605e9)
```

**Comment by KristofferC** [comment]
@oscardssmith Why is this added to the 1.7 milestone?

**Comment by vtjnash** [comment]
This is not going into v1.7, but is something to review and consider for a next release

**Comment by simeonschaub** [comment]
Triage echoed worries about significantly increased latency in some cases. We should at least run all Base benchmarks on this and we also talked about potentially doing a PkgEval run and analyzing whether there are any outliers in terms of run times.

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40985#issuecomment-872599675) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/3bcccc9_vs_1810952/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40985#issuecomment-872599675) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/03de024_vs_1810952/report.md). cc @christopher-dG

**Comment by simeonschaub** [comment]
Sorry it took me so long to get back to this! Overall, I couldn't measure any significant mean increase in run time for the PkgEval jobs. Just to be safe, I'll rerun PkgEval for all packages whose tests took more than 20% longer.

@nanosoldier `runtests(["HealthBase", "P4est", "Pitaya", "Geophysics", "Synthesizer", "LatinHypercubeSampling", "SequentialMonteCarlo", "Batsrus", "InterProcessCommunication", "MixedModels", "RandomizedNMF", "EasyConfig", "Crayons", "CooperativeGames", "DashBootstrapComponents", "Word2Vec", "PatModules", "IntervalTrees", "IncrementalInference", "VT100", "TraitWrappers", "URIParser", "KeywordCalls", "ProgrammableAPI", "LikelihoodProfiler", "DataFitting", "FeatureDescriptors", "StatsDiscretizations", "LittleEndianBase128", "ConventionalApp", "RealContinuedFractions", "PredictMD", "Avalon", "FromDigits", "H3", "SLEEFInline", "DashTable", "MultivariateOrthogonalPolynomials", "Vinyl", "CIAOAlgorithms", "Zabbix", "RenoiseOSC", "UnitTestDesign", "Remark", "Scalpels", "MixedModelsExtras", "RegularizationTools", "ChainLadder", "Morton", "CPLEX", "LCMGL", "LibDeflate", "SuperLU", "QuadraticToBinary", "AbstractIndices", "Gloria", "GLNS", "ArgParse", "TriangleMesh", "BlockBootstrap", "ForecastEval", "SalesForceBulkApi", "MLDataUtils", "SuiteSparseGraphBLAS", "ARFFFiles", "FeatherLib", "StippleLatex", "GtkMarkdownTextView", "ProgressMeter", "LinearFractionalTransformations", "SimpleLife", "Plots", "Glob", "BDF", "CurrenciesBase", "Skyler", "TrackingTimers", "BioServices", "BoltzmannMachines", "ClassicalOrthogonalPolynomials", "Taro", "TensorKit", "ReusePatterns", "SymArrays", "RiskAdjustedLinearizations", "YahooFinance", "JuliaPetra", "PooledArrays", "StaticNumbers", "ExponentialUtilities", "LogCompose", "GitCommand", "Pilot", "FastRounding", "TSAnalysis", "ConstantArrays", "Intervals", "NeuroCore", "Parameters", "AMRVW", "HighFrequencyCovariance", "ComputabilityTheory", "GenFlux", "Shoco", "KiteConnect", "EditionBuilders", "FastFloat16s", "ImGuiOpenGLBackend", "Yao", "ConstructiveGeometry", "CircoCore", "Vortice", "AbaqusReader", "RelocatableFolders", "BayesianNonparametrics", "NearestNeighbors", "ElementaryChemistry", "NLPModelsJuMP", "IPNets", "Tectonic", "JacobiDavidson", "Multisets", "PropertyUtils", "BitInformation", "TensArrays", "ValidatedNumerics", "EffectiveWaves", "MitosisStochasticDiffEq", "Chron", "ApproxFunFourier", "Quadrature", "StateSpaceReconstruction", "HOODESolver", "EcoSISTEM", "MPIMapReduce"], vs = ":master")`

**Comment by simeonschaub** [comment]
@nanosoldier `runtests(["JacobiDavidson"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40985#issuecomment-950018298) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/4a91389_vs_59aa3ed/report.md).

**Comment by simeonschaub** [comment]
I used the following quick Pluto notebook based on Kristoffer's PkgEval analysis script to filter out all tests which took > 20% longer: https://gist.github.com/simeonschaub/098ed76dcee0ba8cd542e2cb22176d38. Doesn't seem like there are any notable outliers remaining.

**Comment by tkf** [comment]
@nanosoldier runbenchmarks(!"scalar", vs=":master")

**Comment by oscardssmith** [comment]
What does this need before merging?

**Comment by simeonschaub** [comment]
@JeffBezanson I'd argue that's a bug with `Core.Typeof`, no?

```julia
julia> T = Rational{Core.TypeVar(:T)}
Rational{T}

julia> Core.Typeof(ans)
Type{Rational{T}}

julia> T isa ans
false
```

`Typeof` should probably have a `hasfreetypevars` check.

**Comment by simeonschaub** [comment]
Unfortunately, we can't fix this in `Core.Typeof`, since this is actually used in method definitions like `Foo{T}() where {T} = ...`. Instead, I have fixed this just for `_typeof_captured_variables` here. I wonder whether we should make `has_free_typevars` a builtin though, so that we can add some inference support to make `_typeof_captured_variable` type stable. Otherwise, it's possible this change could lead to regressions in some cases.

File: test/core.jl [hunk 3]
```diff
@@ -704,6 +704,27 @@ end
...
+    @test fieldtype(typeof(f(Rational{Core.TypeVar(:T)})), 1) === DataType
+end
+let f() = (T = Rational{Core.TypeVar(:T)}; () -> T)
+    t = f()()
+    @test t isa DataType
+    @test t.name.wrapper == Rational
+    @test length(t.parameters) == 1
+    @test t.parameters[1] isa Core.TypeVar
+
+    @test_broken @inferred(f()) isa Function
```
Comment (simeonschaub) [inline test/core.jl:723]: Any ideas what's going on here?
```julia
julia> g() = (T = Rational{Core.TypeVar(:T)}; () -> T)
g (generic function with 1 method)

julia> ir = @code_typed g()
CodeInfo(
1 ─ %1  = Core._typevar(:T, Union{}, Any)::TypeVar
│   %2  = Core.apply_type(Main.Rational, %1)::Type{Rational{T}}
│   %3  = Main.:(var"#3#4")::Type{var"#3#4"}
│   %4  = Core.has_free_typevars::typeof(Core.has_free_typevars)
│   %5  = (%4)(%2)::Bool
└──       goto #3 if not %5
2 ─ %7  = Base.typeof(%2)::DataType
└──       goto #4
3 ─ %9  = Core.apply_type(Core.Type, %2)::Type{Type{_A}} where _A
└──       goto #4
4 ┄ %11 = φ (#2 => %7, #3 => %9)::DataType
│   %12 = Core.apply_type(%3, %11)::Type{var"#3#4"{_A}} where _A
│   %13 = %new(%12, %2)::var"#3#4"
└──       return %13
) => var"#3#4"

julia> Core.Compiler.has_free_typevars_tfunc(ir[1].ssavaluetypes[2])
Core.Const(true)
```
Why is `%5` inferred as `Bool` instead of `Core.Const(true)`?

Comment (aviatesk) [reply test/core.jl:723]: You need to inspect unoptimized frame to see how abstract interpretation goes. Essentially when inference enters the frame of `_typeof_captured_variable` we intentionally widen anything including free typevars (as free typevars are very annoying): https://github.com/JuliaLang/julia/blob/2ba3a22858938ecaf41bbe3e780df507556825c5/base/compiler/inferenceresult.jl#L168

I think the easiest direction here would be to have a special case in `abstract_known_call` rather than having a new builtin.

Comment (aviatesk) [reply test/core.jl:723]: #43965

Comment (tkf) [reply test/core.jl]: > we intentionally widen anything including free typevars

So, I guess this is why we can't just mark `has_free_typevars` as pure and expect to get a similar result?

File: base/reflection.jl [hunk 4]
```diff
@@ -588,7 +588,7 @@ isdispatchtuple(@nospecialize(t)) = (@_pure_meta; isa(t, DataType) && (t.flags &
 
 iskindtype(@nospecialize t) = (t === DataType || t === UnionAll || t === Union || t === typeof(Bottom))
 isconcretedispatch(@nospecialize t) = isconcretetype(t) && !iskindtype(t)
-has_free_typevars(@nospecialize(t)) = ccall(:jl_has_free_typevars, Cint, (Any,), t) != 0
+import Core: has_free_typevars
```
Comment (aviatesk) [inline base/reflection.jl:591]:
```suggestion
using Core: has_free_typevars
```

File: test/core.jl (hunk 3 above)
Comment (aviatesk) [reply test/core.jl]: If we need to forward it to `_typeof_captured_variable`, yes. If the frontend inserts (inlines) the entire body of `_typeof_captured_variable`, then we don't need to forward it and it would probably work to just mark `has_free_typevars` as pure.

Comment (tkf) [reply test/core.jl]: Marking `_typeof_captured_variable` as pure is also not enough?

Comment (aviatesk) [reply test/core.jl]: Well, pure function call can be folded only when all the inputs are `Const`. But we want to infer `_typeof_captured_variable(::Int)` as `Type{Int}` for example and it requires some special casing anyway.

Comment (tkf) [reply test/core.jl]: What about

```julia
_typeof_captured_variable(::T) where {T} = T
@pure _typeof_captured_variable(::Type{T}) where {T} = has_free_typevars(T) ? typeof(T) : Typeof(T)
```

? i.e., Can we extract out special casing from the compiler?

Comment (simeonschaub) [reply test/core.jl]: I believe that would run into the same issues I was having above that free type vars are widened automatically.

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/40985#issuecomment-1030399161):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.

**Comment by timholy** [comment]
Will this fix
```julia
julia> function outer(list)
           function inner(x)
               x isa Vector{Int} && return map(inner, x)
               return 2x
           end
           map(inner, list)
       end
                   
outer (generic function with 1 method)

julia> @code_warntype outer([1, 2, [3, 4]])
MethodInstance for outer(::Vector{Any})
  from outer(list) in Main at REPL[1]:1
Arguments
  #self#::Core.Const(outer)
  list::Vector{Any}
Locals
  inner@_3::Core.Box
  inner@_4::Union{}
  inner@_5::Union{}
Body::Vector
1 ─       (inner@_3 = Core.Box())
│   %2  = %new(Main.:(var"#inner#1"), inner@_3)::var"#inner#1"
│         Core.setfield!(inner@_3, :contents, %2)
│   %4  = Core.isdefined(inner@_3, :contents)::Bool
└──       goto #3 if not %4
2 ─       goto #4
3 ─       Core.NewvarNode(:(inner@_5))
└──       inner@_5
4 ┄ %9  = Core.getfield(inner@_3, :contents)::Any
│   %10 = Main.map(%9, list)::Vector
└──       return %10
```
That's the main category of `Core.Box` left in Base after #44029

**Comment by simeonschaub** [comment]
No, unfortunately that's an orthogonal issue. It's tracked in #40990.

**Comment by vtjnash** [comment]
I think we may need to support fixed declared types on closure variables (e.g. `@nospecialize x::T`) before we can make this drastic of a change to the ecosystem.

https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4d026b5_vs_46032c5/report.md

**Comment by simeonschaub** [comment]
Could you clarify what you mean by this? Are you talking about arguments of the closure being annotated as `@nospecialize`? That should mostly be orthogonal to this, no?

**Comment by vtjnash** [comment]
I mean the closed over environment itself: `f() = (@nospecialize x; x = y; g() = x)`

**Comment by oscardssmith** [comment]
bumping this since I ran into an example today: `f(T) = [T[] for _ in 1:2]`

**Comment by KristofferC** [comment]
Yeah, it doesn't look like anything was actively blocking this so let's try get it in imo.

**Comment by vtjnash** [comment]
I thought it was sort of breaking?

**Comment by KristofferC** [comment]
PkgEval looked fine.

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks()`

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks(ALL, vs="master")`

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40985#issuecomment-2335370834) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/8757b16_vs_61be4de/report.md).

**Comment by simeonschaub** [comment]
Benchmarks look good as far as I can tell. Tagging for triage to give the final green light considering some of the concerns voiced above. I do belive we've sufficiently demonstrated that this would be a net win and otherwise this is ready to merge.

**Comment by oscardssmith** [comment]
triage assigned a build time and sysimage size check to Jeff, but merge after that.

**Comment by KristofferC** [comment]
> triage assigned a build time and sysimage size check to Jeff


Just checking, but presumably, Jeff was there and agreed to it? :smile:

File: base/reflection.jl [hunk 5]
```diff
@@ -851,7 +851,8 @@ end
 
 iskindtype(@nospecialize t) = (t === DataType || t === UnionAll || t === Union || t === typeof(Bottom))
 isconcretedispatch(@nospecialize t) = isconcretetype(t) && !iskindtype(t)
-has_free_typevars(@nospecialize(t)) = (@_total_meta; ccall(:jl_has_free_typevars, Cint, (Any,), t) != 0)
```
Comment (JeffBezanson) [inline base/reflection.jl:854]: Maybe we still need this, to preserve the `_total_meta`?

**Comment by JeffBezanson** [comment]
I don't see any meaningful changes in the numbers there, so probably good.

File: base/reflection.jl (hunk 5 above)
Comment (simeonschaub) [reply base/reflection.jl:854]: Good catch! I believe when this PR was created it didn't have the `@_total_meta`. I now added `@_total_meta` to the definition in `base/boot.jl

File: base/compiler/abstractinterpretation.jl [hunk 6]
```diff
@@ -2316,6 +2316,20 @@ function abstract_call_known(interp::AbstractInterpreter, @nospecialize(f),
...
         call = abstract_call_gf_by_type(interp, f, ArgInfo(nothing, Any[Const(UnionAll), Any, Any]), si, Tuple{Type{UnionAll}, Any, Any}, sv, max_methods)
         return abstract_call_unionall(interp, argtypes, call)
+    elseif f === _typeof_captured_variable && la == 2
+        t = argtypes[2]
+        if t isa Const
+            tv = t.val
+            rt = Const(has_free_typevars(tv) ? typeof(tv) : Core.Typeof(tv))
+        elseif isType(t)
+            tv = t.parameters[1]
+            rt = Const(has_free_typevars(tv) ? typeof(tv) : Core.Typeof(tv))
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:2326]: This seems mostly likely incorrect changing an uncertain value to a guaranteed one

Comment (simeonschaub) [reply base/compiler/abstractinterpretation.jl:2326]: You mean just the `isType` branch? Or is there an issue with this optimization as a whole?

Comment (simeonschaub) [reply base/compiler/abstractinterpretation.jl:2327]: Bump. @vtjnash What would a correct version of this look like?

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:2327]: Can you just delete it?

**Comment by simeonschaub** [comment]
Ok, this seemed to work, all tests still pass and I've confirmed locally that the call is still eliminated in all cases I care about. Good to merge?

File: base/compiler/abstractinterpretation.jl [hunk 7]
```diff
@@ -2321,6 +2321,20 @@ function abstract_call_known(interp::AbstractInterpreter, @nospecialize(f),
     elseif f === UnionAll
         call = abstract_call_gf_by_type(interp, f, ArgInfo(nothing, Any[Const(UnionAll), Any, Any]), si, Tuple{Type{UnionAll}, Any, Any}, sv, max_methods)
         return abstract_call_unionall(interp, argtypes, call)
+    elseif f === _typeof_captured_variable && la == 2
+        t = argtypes[2]
+        if t isa Const
+            tv = t.val
+            rt = Const(has_free_typevars(tv) ? typeof(tv) : Core.Typeof(tv))
+        elseif isType(t)
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:2329]:
```suggestion
        elseif isconstType(t)
```
It would be probably fine if we use `isconstType` here?

File: test/core.jl [hunk 8]
```diff
@@ -796,6 +796,27 @@ end
...
+    t = f()()
+    @test t isa DataType
+    @test t.name.wrapper == Rational
+    @test length(t.parameters) == 1
+    @test t.parameters[1] isa Core.TypeVar
+
+    @test @inferred(f()) isa Function
+    @test Base.return_types(f()) == Any[DataType]
+    @test fieldtype(typeof(f()), 1) === DataType
+end
```
Comment (aviatesk) [inline test/core.jl:818]:
```suggestion
end
function issue23618(a::AbstractVector)
    T = eltype(a)
    b = Vector{T}()
    return [Set{T}() for x in a]
end
@test Base.infer_return_type(issue23618, (Vector{Int},)) == Vector{Set{Int}}
```
Would be useful as a high-level test.

**Review by aviatesk — APPROVED** [review]

File: base/compiler/abstractinterpretation.jl (hunk 7 above)
Comment (simeonschaub) [reply base/compiler/abstractinterpretation.jl]: Sorry, I've been a bit busy this week, so didn't get to this yet. I don't really know why I thought I addressed Jameson's comment about `isType` in b64b1b3, thanks for fixing this up!

File: base/compiler/ssair/inlining.jl [hunk 9]
```diff
@@ -1768,6 +1768,13 @@ function late_inline_special_case!(ir::IRCode, idx::Int, stmt::Expr, flag::UInt3
         unionall_call = Expr(:foreigncall, QuoteNode(:jl_type_unionall), Any, svec(Any, Any),
             0, QuoteNode(:ccall), stmt.args[2], stmt.args[3])
         return SomeCase(unionall_call)
+    elseif f === _typeof_captured_variable
+        if isa(type, Const)
+            return SomeCase(quoted(type.val))
+        elseif isconstType(type)
+            return SomeCase(quoted(type.parameters[1]))
+        end
+        # TODO we may still want to inline the body of `_typeof_captured_variable` here
```
Comment (aviatesk) [inline base/compiler/ssair/inlining.jl:1777]: Why is this special case necessary? The cases being optimized here should be handled by the handling for `MethodPureResult`.

**Comment by aviatesk** [comment]
I tweaked the implementation of `_typeof_captured_variable` a bit to remove the special case in inference. I think this PR is fine now, so I'll go ahead and merge it as is.
