### PR TITLE
Relax `StridedArray` signatures wherever possible

### LINKED ISSUE #587: `lu!` does not support `SubArray` indexed by `Vector` rather `UnitRange`
`lu!` works for `A[ii,jj]` when `ii` and `jj` are `UnitRange{Int64}`:
```julia
julia> VERSION
v"0.7.1-pre.0"

julia> A = rand(3,3)
3×3 Array{Float64,2}:
 0.433089  0.964333  0.921431
 0.736251  0.108516  0.147767
 0.435144  0.707014  0.36105

julia> Asub1 = @view(A[2:3,2:3])
2×2 view(::Array{Float64,2}, 2:3, 2:3) with eltype Float64:
 0.108516  0.147767
 0.707014  0.36105

julia> lu!(Asub1)
LU{Float64,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}
L factor:
2×2 Array{Float64,2}:
 1.0       0.0
 0.153484  1.0
U factor:
2×2 Array{Float64,2}:
 0.707014  0.36105
 0.0       0.092351
```

However, `lu!` does not work for `A[ii,jj]` if `ii` and `jj` are `Vector{Int64}`:
```julia
julia> Asub2 = @view(A[[1,3],[1,3]])
2×2 view(::Array{Float64,2}, [1, 3], [1, 3]) with eltype Float64:
 0.433089  0.921431
 0.435144  0.092351

julia> lu!(Asub2)
ERROR: MethodError: no method matching lu!(::SubArray{Float64,2,Array{Float64,2},Tuple{Array{Int64,1},Array{Int64,1}},false})
Closest candidates are:
  lu!(::Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /Users/wsshin/packages/julia/julia-0.7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:37
  lu!(::Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}, ::Union{Val{false}, Val{true}}; check) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /Users/wsshin/packages/julia/julia-0.7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:37
  lu!(::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) at /Users/wsshin/packages/julia/julia-0.7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:45
  ...
Stacktrace:
 [1] top-level scope at none:0
```

Still, `lu` (instead of `lu!`) works even in that case:
```julia
julia> lu(Asub2)
LU{Float64,Array{Float64,2}}
L factor:
2×2 Array{Float64,2}:
 1.0       0.0
 0.995276  1.0
U factor:
2×2 Array{Float64,2}:
 0.435144  0.092351
 0.0       0.829516
```

### LINKED ISSUE #620: Remove StridedArray restrictions on factorization objects.
I'm going through the QR, Cholesky, etc. factorization codes as I re-write the factorizations in BandedMatrices.jl (and elsewhere) to be consistent with Base, and there are a large amount of unnecessary restrictions to `StridedArray`s. This is particularly silly as many of the factorizations have generic Julia fallbacks which do not use strided-ness at all.

I can do a PR when I get some time.

### LINKED ISSUE #713: Overly restrictive type constraints in LinearAlgebra
Many functions in `LinearAlgebra`  have the `::StridedVecOrMat` constraint. In many cases, it seems unnecessary. Just to list a few:

https://github.com/JuliaLang/julia/blob/8a5b3233a1fad479ed417345fc2b9de0a5d23c1d/stdlib/LinearAlgebra/src/lu.jl#L394-L397
https://github.com/JuliaLang/julia/blob/8a5b3233a1fad479ed417345fc2b9de0a5d23c1d/stdlib/LinearAlgebra/src/lu.jl#L339-L389

This causes problems like
```julia
julia> using LinearAlgebra
julia> A = rand(3, 3); x = rand(3)';
julia> ldiv!(lu(A), vec(x))
ERROR: MethodError: no method matching ldiv!(::LU{Float64,Array{Float64,2}}, ::Base.ReshapedArray{Float64,1,Adjoint{Float64,Array{Float64,1}},Tuple{}})
```

### LINKED ISSUE #30097: `lu!` does not support `SubArray` indexed by `Vector` rather `UnitRange`
`lu!` works for `A[ii,jj]` when `ii` and `jj` are `UnitRange{Int64}`:
```julia
julia> VERSION
v"0.7.1-pre.0"

julia> A = rand(3,3)
3×3 Array{Float64,2}:
 0.433089  0.964333  0.921431
 0.736251  0.108516  0.147767
 0.435144  0.707014  0.36105

julia> Asub1 = @view(A[2:3,2:3])
2×2 view(::Array{Float64,2}, 2:3, 2:3) with eltype Float64:
 0.108516  0.147767
 0.707014  0.36105

julia> lu!(Asub1)
LU{Float64,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}
L factor:
2×2 Array{Float64,2}:
 1.0       0.0
 0.153484  1.0
U factor:
2×2 Array{Float64,2}:
 0.707014  0.36105
 0.0       0.092351
```

However, `lu!` does not work for `A[ii,jj]` if `ii` and `jj` are `Vector{Int64}`:
```julia
julia> Asub2 = @view(A[[1,3],[1,3]])
2×2 view(::Array{Float64,2}, [1, 3], [1, 3]) with eltype Float64:
 0.433089  0.921431
 0.435144  0.092351

julia> lu!(Asub2)
ERROR: MethodError: no method matching lu!(::SubArray{Float64,2,Array{Float64,2},Tuple{Array{Int64,1},Array{Int64,1}},false})
Closest candidates are:
  lu!(::Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /Users/wsshin/packages/julia/julia-0.7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:37
  lu!(::Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}, ::Union{Val{false}, Val{true}}; check) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /Users/wsshin/packages/julia/julia-0.7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:37
  lu!(::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) at /Users/wsshin/packages/julia/julia-0.7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:45
  ...
Stacktrace:
 [1] top-level scope at none:0
```

Still, `lu` (instead of `lu!`) works even in that case:
```julia
julia> lu(Asub2)
LU{Float64,Array{Float64,2}}
L factor:
2×2 Array{Float64,2}:
 1.0       0.0
 0.995276  1.0
U factor:
2×2 Array{Float64,2}:
 0.435144  0.092351
 0.0       0.829516
```

### LINKED ISSUE #31389: Remove StridedArray restrictions on factorization objects.
I'm going through the QR, Cholesky, etc. factorization codes as I re-write the factorizations in BandedMatrices.jl (and elsewhere) to be consistent with Base, and there are a large amount of unnecessary restrictions to `StridedArray`s. This is particularly silly as many of the factorizations have generic Julia fallbacks which do not use strided-ness at all.

I can do a PR when I get some time.

### LINKED ISSUE #35419: Overly restrictive type constraints in LinearAlgebra
Many functions in `LinearAlgebra`  have the `::StridedVecOrMat` constraint. In many cases, it seems unnecessary. Just to list a few:

https://github.com/JuliaLang/julia/blob/8a5b3233a1fad479ed417345fc2b9de0a5d23c1d/stdlib/LinearAlgebra/src/lu.jl#L394-L397
https://github.com/JuliaLang/julia/blob/8a5b3233a1fad479ed417345fc2b9de0a5d23c1d/stdlib/LinearAlgebra/src/lu.jl#L339-L389

This causes problems like
```julia
julia> using LinearAlgebra
julia> A = rand(3, 3); x = rand(3)';
julia> ldiv!(lu(A), vec(x))
ERROR: MethodError: no method matching ldiv!(::LU{Float64,Array{Float64,2}}, ::Base.ReshapedArray{Float64,1,Adjoint{Float64,Array{Float64,1}},Tuple{}})
```

### PR DESCRIPTION
**Pull request by dkarrasch**
This is a careful manual rebase of JuliaLang/julia#35420. I'd say half of it was already done in other PRs, so here is what remained to be done. There was one concern by @andreasnoack that some implementations may now be open to array types that (i) are invariant under 3-arg `similar` and (ii) have slow elementwise indexing. If that is still a concern, then this PR should be reviewed in light of that. This needs a pkgeval run to see if it creates many ambiguities, but, as you can see, there was not that much to be resolved. I wonder if this [c/sh]ould be made a v1.9 milestone, so packages could iron out ambiguities in the beta phase?

Closes JuliaLang/julia#35420. Fixes JuliaLang/LinearAlgebra.jl#713. Fixes JuliaLang/LinearAlgebra.jl#620. Fixes JuliaLang/LinearAlgebra.jl#587.

### CODE REVIEW

File: stdlib/LinearAlgebra/src/bunchkaufman.jl [hunk 1]
```diff
@@ -348,11 +348,6 @@ function ldiv!(B::BunchKaufman{T}, R::StridedVecOrMat{T}) where T<:BlasComplex
         end
     end
 end
-# There is no fallback solver for Bunch-Kaufman so we'll have to promote to same element type
-function ldiv!(B::BunchKaufman{T}, R::StridedVecOrMat{S}) where {T,S}
-    TS = promote_type(T,S)
-    return ldiv!(convert(BunchKaufman{TS}, B), convert(AbstractArray{TS}, R))
-end
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/bunchkaufman.jl:355]: This is an untested method that doesn't even follow the `ldiv!` contract: when the types `TS` and `S` are different, then `R` gets copied. Usually, we don't promote `eltypes` in in-place functions.

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 2]
```diff
@@ -960,93 +960,14 @@ function lmul!(A::UnitLowerTriangular, B::StridedVecOrMat)
...
-            m, n = size(B, 1), size(B, 2)
-            if m != size(A, 1)
-                throw(DimensionMismatch("right hand side B needs first dimension of size $(size(A,1)), has size $m"))
-            end
-            pA = parent(A)
-            for j = 1:n
-                for i = 1:m
-                    Bij = $tfun(pA[i,i])*B[i,j]
-                    for k = i + 1:m
-                        Bij += $tfun(pA[k,i])*B[k,j]
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/triangular.jl:976]: I have removed all of these methods because all they do is to spell out the "unpacking" in `getindex`: w.r.t. the original argument `xA` above, `$tfun(pA[k,i])` is nothing but `xA[i,k]`, which is what is written in the generic code above. I wonder if we should force inlining at the call site to make sure that `adjoint(xA.data.parent[k,i]` is inserted in the generic code above. OTOH, even for a rather big benchmark case I was hardly seeing any benefit.

Comment (N5N3) [reply stdlib/LinearAlgebra/src/triangular.jl:976]: The `getindex` for `Adjoint`/`Transpose` has been marked with `@propagate_inbounds`. The generic code above would inline thes `getindex`s and generate the same IR. So I think these methods are safe to remove?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/triangular.jl:976]: I would very much hope so!

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47107#issuecomment-1272373698) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/5ac0681_vs_2590712/report.html).

**Comment by dkarrasch** [comment]
Wow, what a clean nanosoldier run! `ArrayLayouts.jl` "fails" due to unexpected passes. 🤣  `BlockArrays.jl` fails due to

```julia
MethodError: ldiv!(::LU{Float64, Matrix{Float64}, Vector{Int64}}, ::PseudoBlockMatrix{Float64, Matrix{Float64}, Tuple{BlockedUnitRange{RangeCumsum{Int64, UnitRange{Int64}}}, BlockedUnitRange{Vector{Int64}}}}) is ambiguous.
  
  Candidates:
    ldiv!(A::Factorization, x::LayoutMatrix)
      @ ArrayLayouts ~/.julia/packages/ArrayLayouts/DYIpy/src/ldiv.jl:135
    ldiv!(A::LU, B::AbstractVecOrMat)
      @ LinearAlgebra /opt/julia/share/julia/stdlib/v1.9/LinearAlgebra/src/lu.jl:426
  
  Possible fix, define
    ldiv!(::LU, ::LayoutMatrix)
```

which points to a general pattern for all `Factorization`s that admit a generic `ldiv!` solver (in which we relaxed the `StridedVecOrMat` restriction). `ExtendableSparse.jl` can be easily fixed by splitting `\(symm_ext::Symmetric{Tm, ExtendableSparseMatrix{Tm, Ti}}, B::AbstractVecOrMat) where {Tm, Ti}` into two methods, one for matrices and one for vectors; and same for `Hermitian`. `InfiniteLinearAlgebra` fails due to the same reason as `ArrayLayouts.jl` (actually it's the same `ArrayLayouts.jl` issue with `Cholesky`. So, it seems to be all about the `ldiv!(::Factorization, ::LayoutMatrix)` in `ArrayLayouts.jl`. Finally, I'm not sure what to do with `OptimKit.jl`. The computation doesn't seem to converge, so perhaps @Jutho could take a look at this PR if there is something relevant?

**Comment by Jutho** [comment]
I don't think the OptimKit.jl failure is relevant. I run some optimisation tests using quadratic problems with random matrices, and do not even set the seed appropriately. So I guess it can happen that a matrix happens to have bad convergence properties for GD, and convergence is thus terribly slow. I should probably make the tests of OptimKit a bit more robust.

**Comment by dkarrasch** [comment]
@dlfivefifty I think this can be merged once we find a solution for the ambiguity in `ArrayLayouts.jl`, see https://github.com/JuliaLang/julia/pull/47107#issuecomment-1272524606. Do you have any idea how to fix it? A suboptimal fix would be to introduce specific methods for all factorizations from `LinearAlgebra`, but that wouldn't extend to other factorizations from the general ecosystem.

OTOH, I noticed that `ArrayLayouts.jl` has about 1k method ambiguities (counted by `Aqua.jl`), so I wonder how it can be working at all. 😅

**Comment by dkarrasch** [comment]
Hm:

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.2 (2022-09-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using LinearAlgebra

julia> methods(ldiv!, (Factorization, AbstractMatrix), LinearAlgebra)
# 19 methods for generic function "ldiv!":
[1] ldiv!(A::LinearAlgebra.QRCompactWY{T, M, C} where {M<:AbstractMatrix{T}, C<:AbstractMatrix{T}}, B::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/qr.jl:876
[2] ldiv!(A::QRPivoted{T, S, C} where {S<:AbstractMatrix{T}, C<:AbstractVector{T}}, B::StridedVecOrMat{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/qr.jl:920
[3] ldiv!(A::QRPivoted, B::StridedMatrix{T} where T) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/qr.jl:989
[4] ldiv!(A::LU{T, <:StridedMatrix{T} where T}, B::StridedVecOrMat{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/lu.jl:404
[5] ldiv!(A::LU{<:Any, <:StridedMatrix{T} where T}, B::StridedVecOrMat) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/lu.jl:407
[6] ldiv!(A::LU{T, Tridiagonal{T, V}}, B::AbstractVecOrMat) where {T, V} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/lu.jl:598
[7] ldiv!(C::CholeskyPivoted{T}, B::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/cholesky.jl:592
[8] ldiv!(C::CholeskyPivoted, B::AbstractMatrix) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/cholesky.jl:615
[9] ldiv!(A::QR{T, S, C} where {S<:AbstractMatrix{T}, C<:AbstractVector{T}}, B::StridedMatrix{T}) where T in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/qr.jl:970
[10] ldiv!(A::SVD{T, Tr, M} where {Tr, M<:(AbstractArray{T})}, B::StridedVecOrMat) where T in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:251
[11] ldiv!(C::Cholesky{T, <:StridedMatrix{T} where T}, B::StridedVecOrMat{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/cholesky.jl:578
[12] ldiv!(C::Cholesky, B::StridedVecOrMat) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/cholesky.jl:581
[13] ldiv!(A::LQ, B::StridedVecOrMat) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/lq.jl:337
[14] ldiv!(S::LDLt{<:Any, <:SymTridiagonal}, B::AbstractVecOrMat) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/ldlt.jl:174
[15] ldiv!(F::Hessenberg{<:Complex, <:Any, <:AbstractMatrix{<:Real}}, B::AbstractVecOrMat{<:Complex}) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/hessenberg.jl:662
[16] ldiv!(F::Hessenberg, B::AbstractVecOrMat) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/hessenberg.jl:646
[17] ldiv!(B::BunchKaufman{T}, R::StridedVecOrMat{T}) where T<:Union{Float32, Float64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/bunchkaufman.jl:329
[18] ldiv!(B::BunchKaufman{T}, R::StridedVecOrMat{T}) where T<:Union{ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/bunchkaufman.jl:336
[19] ldiv!(B::BunchKaufman{T}, R::StridedVecOrMat{S}) where {T, S} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/bunchkaufman.jl:352
```

So in v1.8 we have

```julia
[6] ldiv!(A::LU{T, Tridiagonal{T, V}}, B::AbstractVecOrMat)
[8] ldiv!(C::CholeskyPivoted, B::AbstractMatrix)
[14] ldiv!(S::LDLt{<:Any, <:SymTridiagonal}, B::AbstractVecOrMat)
[16] ldiv!(F::Hessenberg, B::AbstractVecOrMat)
```

that are already causing ambiguities with `ArrayLayouts.jl`. Apparently, they are not called anywhere with a `LayoutMatrix` in the registered ecosystem, otherwise that would throw or tests would fail. I guess we only have two options: restrict to `StridedArrays` here or introduce a few disambiguating `ldiv!` methods in `ArrayLayouts.jl`.

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["ArrayLayouts", "BlockArrays", "ExtendableSparse", "InfiniteLinearAlgebra", "NeXLCore", "OptimKit", "Singular"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47107#issuecomment-1304786014) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f136a18_vs_4e2d13f/report.html).

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["ArrayLayouts", "BlockArrays", "ExtendableSparse", "InfiniteLinearAlgebra"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47107#issuecomment-1304790826) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f136a18_vs_4e2d13f/report.html).

**Comment by dkarrasch** [comment]
Alright, this seems to fix broken tests instead of creating new issues, so this looks promising. I'll put PRs together to adjust the tests in `ArrayLayouts.jl` and `BandedMatrices.jl`.

**Comment by dkarrasch** [comment]
CI failures seem unrelated.
