### PR TITLE
Manually implement tempname on non-windows

### LINKED ISSUE #35785: tmpname(parent) does not respect parent
Hello! I'm packaging julia 1.4.1 for guix, and this test is failing

https://github.com/JuliaLang/julia/blob/381693d3dfc9b7072707f6d544f82f6637fc5e7c/test/file.jl#L70

I can reproduce it with:

```jl
using Test
using Random

function run()
    @testset "tempname with parent" begin
        t = tempname()
        @test dirname(t) == tempdir()
        mktempdir() do d
            t = tempname(d)
            @test dirname(t) == d
        end
        @test_throws ArgumentError tempname(randstring())
    end
end
# tempdir() uses the first environment variable found in the ordered list TMPDIR, TMP, TEMP, and TEMPDIR. If none of these are found, the path "/tmp" is used.
# Let's check all those variables are currently empty
all_empty() = @test all(isnothing.(get.(Ref(ENV), ["TMPDIR", "TMP", "TEMP", "TEMPDIR"], nothing)))
all_empty()

# Check the test passes when no "TEMP" variable is set
@info "No env var"
run()

@info "TMPDIR var"
withenv("TMPDIR" => mktempdir()) do
    run()
end
all_empty()
```

Can anybody confirm the same happens with the official build?

Thanks, Nicolò

### LINKED ISSUE #38873: `tempname` ignores `parent` argument  when environment variable `TMPDIR` is set
```
compiler/validation                (31) |        started at 2020-12-14T10:40:17.674           
compiler/validation                (31) |     2.18 |   0.09 |  4.2 |      56.87 |   303.75
file                               (31) |        started at 2020-12-14T10:40:20.769                                                                                                                                  
file                               (31) |         failed at 2020-12-14T10:40:42.395
Test Failed at /nobackup/users/vchuravy/dev/julia/test/file.jl:72
  Expression: dirname(t) == d
   Evaluated: "/tmp" == "/tmp/jl_b8KtOh"
```

I tried isolating it, but I have not yet reproduced it outside the tests themselves. Running `file` tests on it's own succeeds as well, but running `make testall` this is always reproducible.

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes https://github.com/JuliaLang/julia/issues/35785

### CODE REVIEW

File: base/file.jl [hunk 1]
```diff
@@ -578,10 +578,14 @@ else # !windows
 # Obtain a temporary filename.
 function tempname(parent::AbstractString=tempdir(); cleanup::Bool=true)
     isdir(parent) || throw(ArgumentError("$(repr(parent)) is not a directory"))
-    p = ccall(:tempnam, Cstring, (Cstring, Cstring), parent, temp_prefix)
-    systemerror(:tempnam, p == C_NULL)
-    s = unsafe_string(p)
-    Libc.free(p)
+    # If TEMPDIR is set tempname will ignore `parent` as an argument (#38873)
```
Comment (musm) [inline base/file.jl:581]:
```suggestion
    # If TMPDIR is set tempname will ignore `parent` as an argument (#38873)
```

File: base/file.jl [hunk 2]
```diff
@@ -578,10 +578,14 @@ else # !windows
...
+    s = withenv("TMPDIR" => nothing) do
```
Comment (musm) [inline base/file.jl:582]: shouldn't this be conditional on `parent != tempdir()` ?

**Comment by StefanKarpinski** [comment]
Shouldn't this do the opposite? If `parent` is passed, `TMPDIR` is ignored? If someone has explicitly asked for a temporary path to be in a certain directory, then we should respect that. They might do this, for example, if they need to ensure that it is on the same file system as a final location that they need to be able to move it to without copying. With this change, setting `TMPDIR` would wreck all attempts to do that.

**Comment by vchuravy** [comment]
> Shouldn't this do the opposite? If `parent` is passed, `TMPDIR` is ignored? If someone has explicitly asked for a temporary path to be in a certain directory, then we should respect that. They might do this, for example, if they need to ensure that it is on the same file system as a final location that they need to be able to move it to without copying. With this change, setting `TMPDIR` would wreck all attempts to do that.

I am not sure I understand. This is doing exactly what you are describing. 

If the user passes `parent` we will use that as the directory to prefix the name with, we ensure that `libc` honors the passed `parent` directory by unsetting `TMPDIR` since otherwise it would ignore `parent` and use `TMPDIR` instead. Since we use `parent=tempdir()` in the case that `parent` is not passed we still honor `TMPDIR` as an environment variable. 

We could also achieve the same by setting `TMPDIR` to `parent`, and could then pass an empty string to libc.

File: base/file.jl (hunk 2 above)
Comment (vchuravy) [reply base/file.jl:582]: See https://github.com/JuliaLang/julia/pull/38879#issuecomment-744735667

IMO it is fine to do this unconditional. We unset `TMPDIR` here after checking it with `tempdir`, so that the libc implementation will not override `parent` with the value of `TMPDIR`

**Comment by StefanKarpinski** [comment]
The comment says:

> If TMPDIR is set tempname will ignore `parent` as an argument (#38873)

That's the opposite of what it should do: if `parent` is passed, ignore `TMPDIR`.

**Comment by vchuravy** [comment]
Currently:

```
vchuravy@odin ~> TMPDIR=~ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> tempname()
"/home/vchuravy/jl_Z9se0A"

julia> tempname("/opt")
"/home/vchuravy/jl_hI1x9x"
```

With this PR:
```
vchuravy@odin ~/s/julia (vc/tempname)> TMPDIR=~ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @eval Base.Filesystem function tempname(parent::AbstractString=tempdir(); cleanup::Bool=true)
                  isdir(parent) || throw(ArgumentError("$(repr(parent)) is not a directory"))
                  # If TEMPDIR is set tempname will ignore `parent` as an argument (#38873)
                  s = withenv("TMPDIR" => nothing) do
                      p = ccall(:tempnam, Cstring, (Cstring, Cstring), parent, temp_prefix)
                      systemerror(:tempnam, p == C_NULL)
                      s = unsafe_string(p)
                      Libc.free(p)
                      return s
                  end
                  cleanup && temp_cleanup_later(s)
                  return s
              end
tempname (generic function with 2 methods)

julia> tempname()
"/home/vchuravy/jl_u70Ddi"

julia> tempname("/opt")
"/opt/jl_WNbezj"

```

**Comment by vchuravy** [comment]
> The comment says:
> 
> > If TMPDIR is set tempname will ignore `parent` as an argument (#38873)
> 
> That's the opposite of what it should do: if `parent` is passed, ignore `TMPDIR`.

Ah! I see where the confusion comes from. I was documenting the behavior of `:tempnam` and not the behavior of the Julia function `tempname`.

**Comment by StefanKarpinski** [comment]
Ah, I understand the confusion: the comment is explaining why we need to unset `TMPDIR` whereas I read it as explaining how the function behaves. Perhaps there's some clearer way of wording that? Something like this:

> Unless we unset `TMPDIR` here, it will cause `tempnam` to give a directory in that location, which would contradict the `parent` argument passed in here.

I worry about the thread safety of messing with `TMPDIR` like this. What if, for example, two different threads do this at the same time?

**Comment by vchuravy** [comment]
> I worry about the thread safety of messing with TMPDIR like this. What if, for example, two different threads do this at the same time?

Yeah... `setenv` is not thread-safe at all.

**Comment by StefanKarpinski** [comment]
We could at least put a lock around this so that multiple calls to this function from different threads don't end up concurrently modifying the same environment variable.

**Comment by DilumAluthge** [comment]
Instead of `setenv`, would `withenv` work? Would that be thread-safe?

**Comment by vchuravy** [comment]
> Instead of `setenv`, would `withenv` work? Would that be thread-safe?

I am using `withenv` here, but that uses `setenv` internally.

**Comment by DilumAluthge** [comment]
> > Instead of `setenv`, would `withenv` work? Would that be thread-safe?
> 
> I am using `withenv` here, but that uses `setenv` internally.

Ah fair enough

File: base/file.jl (hunk 2 above)
Comment (staticfloat) [reply base/file.jl:584]: I have a mortal fear of messing with environment variables now.  I'm pretty sure that with this change, we can crash Julia on glibc if we call `tempanme()` in parallel.

I think the only way we can avoid threading issues here is to un-set `TMPDIR` at startup and emulate it. :(

Comment (vchuravy) [reply base/file.jl:584]: At this point I am almost thinking it would be better to avoid the libc implementation of tempname altogether.

Comment (stevengj) [reply base/file.jl:584]: Should `withenv` have a mutex lock?

Comment (StefanKarpinski) [reply base/file.jl:584]: Avoiding `libc` is probably better. Anything that requires modifying the environment is going to be broken.

**Comment by staticfloat** [comment]
The issue is not just Julia code; if any C library (such as, for instance, `tempname()`) tries to read an environment variable while another C library (or some Julia task) modifies the environment block, we can segfault.  We don't run into this very often because we tend to set environment variables at the beginning of program execution and leave them from then on, but the more we use `withenv()` the more likely we are to create this problem.  To be explicit, a Julia mutex won't do anything but ensure that Julia can't interfere with other Julia operations.  That's not even as helpful as you might think however, because since `tempnam()` uses `getenv()` to read the contents of `$TMPDIR`, if you have two Julia tasks that each wait for a mutex to call `setenv()` or `getenv()`, you can still have Julia acquire the (julia) mutex before calling `setenv()` and have that occur at a bad point in time for some other Julia task which is calling `tempnam()`.

Possible solutions:
* We could surround all `ccall()`'s with acquiring a mutex and not release it until the `ccall()` returns.  Ha ha, right.  This at least avoids crashes being Julia's fault; C code could still start a thread that calls `setenv()` within it at some point and causes a segfault.

* We can hijack `getenv()` and `setenv()` somehow and force these functions to become threadsafe.  A custom-build libc, symbol injection, etc...  This is the only truly foolproof method that I know of, and will impose a performance penalty on environment actions, but IMO that's totally acceptable.

* We can avoid modification of environment variables at unsafe points (where "unsafe" means after any thread has been started by anything).  Realistically, this means you should set environment variables in things like `__init__()` and leave it at that.  I will note that I am guilty as anyone in that JLL wrappers set environment variables when launching external processes, but I've been working to eliminate that by passing an environment block to `open(::Cmd)` rather than using `withenv`, and in so doing avoiding `setenv()` on the parent process altogether.

File: base/file.jl (hunk 2 above)
Comment (stevengj) [reply base/file.jl:584]: The [musl implementation](https://git.musl-libc.org/cgit/musl/tree/src/temp) seems pretty straightforward, and is MIT-licensed if we want to copy it.

**Review by Keno — DISMISSED** [review]
Per discussion, should avoid using libc, since messing with the environment is inherently problematic.

File: base/file.jl [hunk 3]
```diff
@@ -578,21 +578,40 @@ end
 
 else # !windows
 
+# Based of musl __randname
+function _rand_string()
+    r = Base.rand(UInt) # FIXME: https://git.musl-libc.org/cgit/musl/tree/src/temp/__randname.c
```
Comment (vchuravy) [inline base/file.jl:583]: Any good ideas on how to get a random number here? Musl use `time_ns`, but then mixes in two pointers as sources of randomness.

File: base/file.jl [hunk 4]
```diff
@@ -578,15 +578,40 @@ end
...
+    buf = Vector{Char}(undef, 6)
+    for i in 1:6
+        buf[i] = 'A'+(r&15)+(r&16)*2;
+        r >>= 5
+    end
+    String(buf)
+end
+
 # Obtain a temporary filename.
 function tempname(parent::AbstractString=tempdir(); cleanup::Bool=true)
```
Comment (musm) [inline base/file.jl:593]: We should use this implementation on Windows as well

File: base/file.jl (hunk 3 above)
Comment (musm) [reply base/file.jl:583]: Is there a particular reason we are avoiding `Base.rand` ?

**Comment by musm** [comment]
I find it a bit odd we are trying to implement `tempnam`  since  the first sentence of the description section in http://man7.org/linux/man-pages/man3/tempnam.3.html says "Never use this function." ... use `mkstemp` instead.

File: base/file.jl (hunk 3 above)
Comment (stevengj) [reply base/file.jl:583]: Even if we use `Base.rand`, we might want to initialize our own seed since we don't want the caller to be able to override this, no?

Comment (vchuravy) [reply base/file.jl:583]: >  since we don't want the caller to be able to override this, no?

I don't think we care about the state of the rng. IIUC we just want a random seed that is not likely to be used by another process. This is why musl mixes in the two pointers to get some randomness in the higher bits, but we don't need to high quality randomness. 

> Is there a particular reason we are avoiding `Base.rand` ?

`Base.rand` is implemented through the stdlib `Random` and thus we would add a hard-dependency edge. Otherwise I would just use `Random.randstring`.

**Comment by vchuravy** [comment]
> I find it a bit odd we are trying to implement `tempnam` since the first sentence of the description section in http://man7.org/linux/man-pages/man3/tempnam.3.html says "Never use this function." ... use `mkstemp` instead.

:shrug: I read that as well and found it entertaining, I assume they want to discourage usage since there is the risk of running into collisions and `mkstemp` will lock the file immediatly.

File: base/file.jl (hunk 3 above)
Comment (vtjnash) [reply base/file.jl:583]: I believe `Libc.rand()` should provide suitable quality for this. It appears we can also use the same code everywhere now, rather than using separate, identical implementation for windows.

**Comment by StefanKarpinski** [comment]
OMG, can we finish this?

**Comment by vchuravy** [comment]
> OMG, can we finish this?

xD If anyone want to pick this up, please go ahead.

**Comment by staticfloat** [comment]
Rebased and unified a bit, as requested by reviewers.

File: base/file.jl [hunk 5]
```diff
@@ -554,8 +554,41 @@ end
 
 const temp_prefix = "jl_"
 
-if Sys.iswindows()
+# Use `Libc.rand()` to generate random strings
+function _rand_filename(len = 10)
+    slug = Base.StringVector(len)
+    chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
```
Comment (stevengj) [inline base/file.jl:560]:
```suggestion
    chars = b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
```
You really want an array of bytes here, I think.

If `chars` is a string, then `chars[i]` converts the byte to a `Char` and then it gets converted back for assignment to `slug[i]`, and `length(chars)` is slow.

Comment (staticfloat) [reply base/file.jl]: Thanks @stevengj!

Comment (staticfloat) [reply base/file.jl]: This is a pretty decent speedup.  The old version:

```
julia> @btime _rand_filename(10)
  320.220 ns (2 allocations: 96 bytes)
```

The new version:
```
julia> @btime _rand_filename(10)
  66.308 ns (2 allocations: 96 bytes)
```

**Comment by musm** [comment]
Any reason not to use this also on Windows?

**Comment by staticfloat** [comment]
> Any reason not to use this also on Windows?

Despite the PR title, this does unify much of the windows/posix divide.

**Comment by staticfloat** [comment]
This is green, and I believe all reviewer concerns have been addressed.  I'm going to add the `merge me` label.

**Comment by vchuravy** [comment]
Thanks Elliot for picking this up!

**Comment by DilumAluthge** [comment]
Thank you Valentin and Elliot!

**Comment by Keno** [comment]
CI failures might be related:
https://build.julialang.org/#/builders/44/builds/856
https://build.julialang.org/#/builders/72/builds/866

**Comment by Keno** [comment]
I will note that the file name is the same in both of these failures, so I'm assuming the RNG doesn't get seeded during precompile generation and since we're using tempname here, we probably end up clashing somewhere.

**Comment by Keno** [comment]
We may want to revert this until #43597 is merged. This is likely quite destabilizing to CI.
