### PR TITLE
Support non-1 indices and fix type problems in DFT (fixes #17896)

### LINKED ISSUE #17896: Some DFT issues
I'm working on a PR to fix these (which will also generalize FFT to non-1 indices), but I may get interrupted for a couple of days so I thought I'd at least document some problems I noticed just from browsing the current code.

First, at least `rfft` fails for anything other than `StridedArray`s:
```jl
julia> a = randn(10)
10-element Array{Float64,1}:
  0.0243352
 -1.70058  
  2.23913  
 -0.0130746
 -1.10423  
 -0.259103 
  0.871204 
 -0.799567 
 -0.0846184
 -0.676859 

julia> b = view(a, 1:8)
8-element SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}:
  0.0243352
 -1.70058  
  2.23913  
 -0.0130746
 -1.10423  
 -0.259103 
  0.871204 
 -0.799567 

julia> rfft(b)
5-element Array{Complex{Float64},1}:
 -0.741877+0.0im     
 -0.446848-0.904787im
  -4.19023+1.14704im 
   2.70397+1.83107im 
   4.80277+0.0im     

julia> b = view(a, [1:8;])
8-element SubArray{Float64,1,Array{Float64,1},Tuple{Array{Int64,1}},false}:
  0.0243352
 -1.70058  
  2.23913  
 -0.0130746
 -1.10423  
 -0.259103 
  0.871204 
 -0.799567 

julia> rfft(b)
ERROR: MethodError: no method matching plan_rfft(::SubArray{Float64,1,Array{Float64,1},Tuple{Array{Int64,1}},false}, ::UnitRange{Int64})
Closest candidates are:
  plan_rfft{N}(::Union{Base.ReshapedArray{Float32,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{Float32,N},SubArray{Float32,N,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Any; flags, timelimit) at fft/FFTW.jl:636
  plan_rfft{N}(::Union{Base.ReshapedArray{Float64,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{Float64,N},SubArray{Float64,N,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Any; flags, timelimit) at fft/FFTW.jl:636
  plan_rfft{T<:Union{Integer,Rational{T<:Integer}}}(::AbstractArray{T<:Union{Integer,Rational},N}, ::Any; kws...) at dft.jl:191
  ...
 in #plan_rfft#7(::Array{Any,1}, ::Function, ::SubArray{Float64,1,Array{Float64,1},Tuple{Array{Int64,1}},false}) at ./dft.jl:38
 in rfft(::SubArray{Float64,1,Array{Float64,1},Tuple{Array{Int64,1}},false}) at ./dft.jl:36
```

Second, `Float16` is an `AbstractFloat` but is not supported by FFTW, so:
```jl
julia> a = randn(Float16, 8)
8-element Array{Float16,1}:
 -1.7412  
  0.38818 
  0.066711
 -0.64893 
  1.3623  
 -0.48633 
 -1.1904  
 -0.023666

julia> fft(a)
ERROR: MethodError: no method matching plan_fft(::Array{Complex{Float16},1}, ::UnitRange{Int64})
Closest candidates are:
  plan_fft{T<:Union{Complex{Float32},Complex{Float64}},N}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64}},N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64}},N},SubArray{T<:Union{Complex{Float32},Complex{Float64}},N,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Any; flags, timelimit) at fft/FFTW.jl:585
  plan_fft{T<:Real}(::AbstractArray{T<:Real,N}, ::Any; kws...) at dft.jl:185
  plan_fft{T<:Union{Integer,Rational{T<:Integer}}}(::AbstractArray{Complex{T<:Union{Integer,Rational}},N}, ::Any; kws...) at dft.jl:187
  ...
 in fft(::Array{Float16,1}, ::UnitRange{Int64}) at ./dft.jl:184 (repeats 2 times)
```
even though
```jl
julia> a = round(Int, 10*randn(8))
8-element Array{Int64,1}:
  -8
  -3
   1
 -20
  -2
  15
  -5
   2

julia> fft(a)
8-element Array{Complex{Float64},1}:
    -20.0+0.0im    
 -3.17157+22.2843im
     -6.0-30.0im   
 -8.82843+34.2843im
     -8.0+0.0im    
 -8.82843-34.2843im
     -6.0+30.0im   
 -3.17157-22.2843im
```
works fine.

### PR DESCRIPTION
**Pull request by timholy**
This supports FFT on non-1 arrays, by introducing `circcopy!`:

``` jl
julia> using OffsetArrays

julia> a = OffsetArray(1:7, -1:5)
OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}} with indices -1:5:
 1
 2
 3
 4
 5
 6
 7

julia> a1 = Array{Int}(7);

julia> circcopy!(a1, a)
7-element Array{Int64,1}:
 3
 4
 5
 6
 7
 1
 2

julia> a[1:5] == a1[1:5]
true
```

As a consequence, index information gets preserved in the phase of the FFT. I tried an alternative implementation, multiplying by phases _post hoc_, but in my hands that was slower.

I also took the opportunity to fix (and test for) #17896.

CC @stevengj.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I'm glad you're pushing this forward, @timholy! Any change that shouldn't break code and isn't too risky should probably be marked for backporting to release-0.5. Does this qualify?

**Comment by StefanKarpinski** [comment]
Minus the export, I should add.

**Comment by timholy** [comment]
Yes, it qualifies. Thanks for the reminder re the label.

> I'm glad you're pushing this forward

Nothing like having a new real-world application to put it through its paces...the application I used while developing non-1 indices in the first place was based on old code where I faked unconventional indices, but perforce that couldn't stretch the limits like it's possible to do now. Once some stuff works, you quickly discover how much more you want to get working.

File: base/multidimensional.jl [hunk 1]
```diff
@@ -662,6 +662,66 @@ function _circshift!(dest, rdest, src, rsrc, inds, shiftamt)
     copy!(dest, CartesianRange(rdest), src, CartesianRange(rsrc))
 end
 
+# circcopy!
+"""
+    circcopy!(dest, src)
```
Comment (tkelman) [inline base/multidimensional.jl]: for 0.6 this should go in the rst manual if exported

File: base/multidimensional.jl [hunk 2]
```diff
@@ -662,6 +662,66 @@ function _circshift!(dest, rdest, src, rsrc, inds, shiftamt)
...
+    indd1, inds1 = indsdest[1], indssrc[1]
+    l = length(indd1)
+    s = mod(first(inds1)-first(indd1), l)
+    sdf = first(indd1)+s
+    rd1, rd2 = first(indd1):sdf-1, sdf:last(indd1)
+    ssf = last(inds1)-s
+    rs1, rs2 = first(inds1):ssf, ssf+1:last(inds1)
+    tindsd, tindss = tail(indsdest), tail(indssrc)
+    _circcopy!(dest, (rdest..., rd1), tindsd, src, (rsrc..., rs2), tindss)
+    _circcopy!(dest, (rdest..., rd2), tindsd, src, (rsrc..., rs1), tindss)
```
Comment (tkelman) [inline base/multidimensional.jl]: this could use some comments

**Comment by timholy** [comment]
I split the `export` and RST manual addition into a separate commit, so that when backporting to release-0.5 you can just use the first commit.

I also added comments as requested.

File: doc/stdlib/arrays.rst [hunk 3]
```diff
@@ -616,6 +616,33 @@ Indexing, Assignment, and Concatenation
...
+   .. doctest::
+
+       julia> src = reshape(collect(1:16), (4,4))
+       4×4 Array{Int64,2}:
+        1  5   9  13
+        2  6  10  14
+        3  7  11  15
+        4  8  12  16
+
+       julia> dest = OffsetArray(Int, (-1,1));
```
Comment (tkelman) [inline doc/stdlib/arrays.rst]: this doctest won't pass without some setup code to load the OffsetArray type definition from `test/`, will it?

File: base/dft.jl [hunk 4]
```diff
@@ -20,22 +20,41 @@ export fft, ifft, bfft, fft!, ifft!, bfft!,
...
-complexfloat{T<:Complex}(x::AbstractArray{T}) = copy!(Array{typeof(float(one(T)))}(size(x)), x)
-complexfloat{T<:AbstractFloat}(x::AbstractArray{T}) = copy!(Array{typeof(complex(one(T)))}(size(x)), x)
-complexfloat{T<:Real}(x::AbstractArray{T}) = copy!(Array{typeof(complex(float(one(T))))}(size(x)), x)
+complexfloat{T<:Complex}(x::AbstractArray{T}) = copy1(typeof(fftwfloat(one(T))), x)
+complexfloat{T<:Real}(x::AbstractArray{T}) = copy1(typeof(complex(fftwfloat(one(T)))), x)
+
+realfloat{T<:Real}(x::AbstractArray{T}) = copy1(typeof(fftwfloat(one(T))), x)
+
+# copy to a 1-based array, using circular permutation
+function copy1{T}(::Type{T}, x)
```
Comment (stevengj) [inline base/dft.jl]: I don't understand why it would be necessary to make a copy.  FFTW doesn't care how Julia indexes the array, as long as the data is strided.  It should be possible to make it work with any `DenseArray` (i.e. supporting `pointer` and `strides`) without copying.

File: doc/stdlib/arrays.rst (hunk 3 above)
Comment (timholy) [inline doc/stdlib/arrays.rst]: Good catch. I'm guessing we can't just say `using OffsetArrays`, for reasons previously discussed. Is there some kind of "hidden" setup possible? Or should I just remove the doctest and make sure this runs in the main tests?

File: base/dft.jl (hunk 4 above)
Comment (timholy) [inline base/dft.jl]: Mathematical consistency. As you know better than almost anyone, here's the formula:
```latex
FFT(x)[k] = \sum_{n=1}^N x[n] exp(-2\pi (n-1)(k-1)/N)
```
`x[n]` is to be interpreted with periodic boundary conditions.


That summation range actually means something, and 1 is **not** synonymous with "the first value." If my array is defined over `-1:5`, it's equivalent to it being defined over `1:7` but you need to circularly-permute the values. Nothing else makes any sense.

Incidentally, this makes array-padding---extending the indices in either direction---an absolute dream. No more index gymnastics necessary.

Comment (timholy) [inline base/dft.jl]: BTW, I do think we are a bit confused about `DenseArray` vs `StridedArray`: if `DenseArray` means it supports `pointer` and `strides`, what exactly does `StridedArray` mean?

Comment (stevengj) [inline base/dft.jl]: You're right, I meant `StridedArray`.

I see your point, you want the indexing to define the "origin" (the phase offset) of the DFT.

File: doc/stdlib/arrays.rst (hunk 3 above)
Comment (tkelman) [inline doc/stdlib/arrays.rst]: I believe there is a way to do a few lines of test setup that don't appear in the rendered docs. It might be worth moving the definition of the type and methods from `test/offsetarray.jl` to `test/TestHelpers.jl`, if the rest of the correctness tests take a little too long to run as part of the doctest setup.

File: base/dft.jl (hunk 4 above)
Comment (stevengj) [inline base/dft.jl]: Note that you could still do it without making a copy by multiplying the output by an appropriate phase.  It's probably more expensive than a copy, though.

Comment (timholy) [inline base/dft.jl]: In my tests, it was.

**Comment by timholy** [comment]
I think this can be merged once CI passes.

File: doc/stdlib/arrays.rst (hunk 3 above)
Comment (timholy) [inline doc/stdlib/arrays.rst]: I just got rid of it, as (1) I was not successful in figuring out hiding, and (2) the printing of the typename just didn't seem to benefit from having TestHelpers in it. I did move the OAs module to TestHelpers.jl, however.
