### PR TITLE
fix `nextpow`, `prevpow` for types without `typemax`

### LINKED ISSUE #57906: prevpow errors on some BigInt/BigFloat input combinations
Here is a pretty self explanatory MWE:
```
julia> prevpow(2, 5.1)
4

julia> prevpow(2, BigFloat(5.1))
ERROR: MethodError: no method matching typemax(::Type{BigInt})
The function `typemax` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  typemax(::Type{LibGit2.Consts.GIT_SUBMODULE_IGNORE})
   @ LibGit2 Enums.jl:217
  typemax(::Type{LibGit2.Consts.GIT_MERGE_FILE_FAVOR})
   @ LibGit2 Enums.jl:217
  typemax(::Type{Int128})
   @ Base int.jl:823
  ...

Stacktrace:
 [1] typemax(x::BigInt)
   @ Base ./float.jl:1039
 [2] prevpow(a::Int64, x::BigFloat)
   @ Base ./intfuncs.jl:570
 [3] top-level scope
   @ REPL[12]:1

julia> prevpow(BigFloat(2), 5.1)
4.0

julia> prevpow(BigInt(2), 5.1)
ERROR: MethodError: no method matching typemax(::Type{BigInt})
The function `typemax` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  typemax(::Type{LibGit2.Consts.GIT_SUBMODULE_IGNORE})
   @ LibGit2 Enums.jl:217
  typemax(::Type{LibGit2.Consts.GIT_MERGE_FILE_FAVOR})
   @ LibGit2 Enums.jl:217
  typemax(::Type{Int128})
   @ Base int.jl:823
  ...

Stacktrace:
 [1] typemax(x::BigInt)
   @ Base ./float.jl:1039
 [2] prevpow(a::BigInt, x::Float64)
   @ Base ./intfuncs.jl:570
 [3] top-level scope
   @ REPL[14]:1

julia> versioninfo()
Julia Version 1.11.4
Commit 8561cc3d68d (2025-03-10 11:36 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

The error is coming from a `typemax` call in the [prevpow code](https://github.com/JuliaLang/julia/blob/d63adeda50d5b8c440a7c29c9a65357a98fe927f/base/intfuncs.jl#L570C5-L570C19). 

As far as fixing it goes, adding `(x isa BigInt) || ...` pushes the problem downstream, where `mul_with_overflow` isn't defined for a mixture of `Int` and `BigInt`, this approach would require changing that line to `mul_with_overflow(promote(a,p)...)`  I do not know if this fits the style, or if it is performant.

First and foremost I think there needs to be more test cases to catch things like this, here is the summary of combinations I have right now, with coverage of the special case `a == 2`
```
@testset "prevpow input types" begin
    @test prevpow(3,7) == 3
    @test prevpow(3, BigInt(7)) == 3                broken = true
    @test prevpow(3, BigFloat(7)) == 3              broken = true
    @test prevpow(BigInt(3), 7) ==3                 broken = true
    @test prevpow(BigInt(3), BigInt(7)) == 3        broken = true
    @test prevpow(BigInt(3), BigFloat(7)) == 3      broken = true
    @test prevpow(BigFloat(3), 7) == 3
    @test prevpow(BigFloat(3), BigInt(7)) == 3
    @test prevpow(BigFloat(3), BigFloat(7)) == 3

    @test prevpow(BigInt(2), 7) == 4 
    @test prevpow(BigInt(2), BigInt(7)) == 4
    @test prevpow(BigFloat(2), 7) == 4
    @test prevpow(2, BigInt(7)) == 4
    @test prevpow(2, BigFloat(7)) == 4              broken = true
end
```

### PR DESCRIPTION
**Pull request by nsajko**
Without this change `prevpow` and `nextpow` fail for, e.g., `BigInt`; incorrectly throwing a `MethodError`. For example, calls like `prevpow(3, big"10")` or `nextpow(3, big"10")` fail.

The issue is that the code incorrectly assumes the existence of a `typemax` method.

Another issue was a missing promote for the arguments of a `mul_with_overflow` call.

Fixes #57906

### CODE REVIEW

**Comment by Seelengrab** [comment]
`applicable` requires a dynamic lookup, which means this implementation cannot be constant folded anymore, if I'm not mistaken:

```
julia> Base.infer_effects(prevpow, (Int, Int))
(+c,+e,!n,+t,+s,+m,+i)

julia> Base.infer_effects(prevpow_new, (Int, Int))
(!c,!e,!n,!t,!s,!m,+i)′
```

I think it'll be better to write a specialized method for `BigInt` (or use the corresponding GMP function, if that exists) in `base/gmp.jl` if we want to support `BigInt` in these functions.

**Comment by nsajko** [comment]
Oof, OK. I guess this means that `digits!` and `invmod` also need fixing. They use `hastypemax`, which uses `applicable`.

**Comment by Seelengrab** [comment]
No, `hastypemax` works on the type, which is known for the important constant foldable cases - it compiles away for e.g. `Int`,  which is specialized to just return `true` (check `@edit Base.hastypemax(Int)`). Since pretty much every operation with `BigInt` needs the runtime for allocations anyway, I guess that's why it's used there as a fallback? You could try to use that here as well, good catch.

**Comment by nsajko** [comment]
Ping. The failures are system-dependent and surely unrelated.

**Comment by oscardssmith** [comment]
@Seelengrab are your concerns resolved?

File: base/intfuncs.jl [hunk 1]
```diff
@@ -488,7 +488,8 @@ function nextpow(a::Real, x::Real)
     n = ceil(Integer,log(a, x))
     # round-off error of log can go either direction, so need some checks
     p = a^(n-1)
-    x > typemax(p) && throw(DomainError(x,"argument is beyond the range of type of the base"))
+    hastypemax(typeof(p)) && x > typemax(p) &&
+        throw(DomainError(x,"argument is beyond the range of type of the base"))
```
Comment (Seelengrab) [inline base/intfuncs.jl:492]: If we guarantee the error (having automatic type widening in Base is a non-starter, as far as I'm aware) this throwing behavior should be documented & tested.

**Comment by Seelengrab** [comment]
If `BigInt` performance is not a concern, yes, this version seems good. I'll maintain though that explicit `BigInt` with promotion at the start & in-place operations would be better, but it's not blocking the PR.

File: base/intfuncs.jl (hunk 1 above)
Comment (nsajko) [reply base/intfuncs.jl:492]: Isn't that a concern that's completely separate from this PR? It's not like this commit adds the `throw`, or makes it happen where it didn't before. I just added the `hastypemax(typeof(p))` check (with the goal of preventing spurious errors), so I don't really see how does the `throw` come into the picture here.

Comment (Seelengrab) [reply base/intfuncs.jl:492]: If we're already going to merge a change for this code, why not take the opportunity to improve its documentation as well?

Comment (nsajko) [reply base/intfuncs.jl:492]: OK.

Regarding the documentation change (guaranteeing the exception), that seems to depend on other changes (#49670 is related), because currently base two is a special case regarding output width:
```julia-repl
julia> prevpow(Int8(2), 800)
512

julia> typeof(ans)
Int64

julia> prevpow(Int8(3), 800)
ERROR: DomainError with 800:
argument is beyond the range of type of the base
```

I'll add some tests for base three, though.

Comment (nsajko) [reply base/intfuncs.jl:492]: > If the `2` case is expected to stay special cased

Ideally it wouldn't be special-cased, at least not to the degree that we mention that in the docs, IMO.

Comment (Seelengrab) [reply base/intfuncs.jl:492]: Agreed, but I was talking about the behavior that `nextpow`/`prevpow` etc. throw if the result is not representable in the input type :) With #49672, the special casing in terms of output size goes aways, if I understood correctly.

Comment (nsajko) [reply base/intfuncs.jl:492]: This is what I meant: https://github.com/JuliaLang/julia/pull/49672#issuecomment-1671160754

File: base/intfuncs.jl [hunk 2]
```diff
@@ -611,9 +612,10 @@ function prevpow(a::T, x::Real) where T <: Real
     n = floor(Integer,log(a, x))
     # round-off error of log can go either direction, so need some checks
     p = a^n
-    x > typemax(p) && throw(DomainError(x,"argument is beyond the range of type of the base"))
+    hastypemax(typeof(p)) && x > typemax(p) &&
+        throw(DomainError(x,"argument is beyond the range of type of the base"))
     if a isa Integer
-        wp, overflow = mul_with_overflow(a, p)
+        wp, overflow = mul_with_overflow(promote(a, p)...)
```
Comment (nsajko) [inline base/intfuncs.jl:618]: Try to revert unrelated change

```suggestion
        wp, overflow = mul_with_overflow(a, p)
```

File: base/intfuncs.jl [hunk 3]
```diff
@@ -615,7 +615,7 @@ function prevpow(a::T, x::Real) where T <: Real
     hastypemax(typeof(p)) && x > typemax(p) &&
         throw(DomainError(x,"argument is beyond the range of type of the base"))
     if a isa Integer
-        wp, overflow = mul_with_overflow(promote(a, p)...)
+        wp, overflow = mul_with_overflow(a, p)
```
Comment (nsajko) [inline base/intfuncs.jl:618]:
```suggestion
        wp, overflow = mul_with_overflow(promote(a, p)...)
```

**Comment by nsajko** [comment]
> If `BigInt` performance is not a concern, yes, this version seems good. I'll maintain though that explicit `BigInt` support with promotion at the start & in-place operations would be better, but it's not blocking the PR.

`BigInt` is a red herring here, this PR is a bugfix to (more or less) generic code, where `BigInt` just happens to be an example where the code is currently broken. A separate method for `BigInt`, as a performance optimization, is clearly completey off-topic here.

File: test/intfuncs.jl [hunk 4]
```diff
@@ -326,6 +326,18 @@ end
...
+                                       P ∈ (Int8, Int16, Int32, Int64, Int128),
+                                       R ∈ (Int8, Int16, Int32, Int64, Int128),
+                                       p ∈ 1:64,
+                                       r ∈ 2:5
+        q = P(p)
+        n = R(r)
+        for a ∈ (n, unsigned(n)), b ∈ (q, unsigned(q))
+            @test f(a, b) == f(a, big(b))
+        end
+    end
```
Comment (nsajko) [inline test/intfuncs.jl:339]:
```suggestion
    fs = (prevpow, nextpow)
    types = (Int8, BigInt, BigFloat)
    for f ∈ fs, P ∈ types, R ∈ types, p ∈ 1:20, r ∈ 2:5
        q = P(p)
        n = R(r)
        @test f(r, p) == f(n, q)
    end
```

**Comment by nsajko** [comment]
bump

**Review by oscardssmith — APPROVED** [review]
