### PR TITLE
Use Matrix for similar(SpecialMatrix, shape) instead of throwing

### LINKED ISSUE #15193: Triangular matrix indexing bug
Index ranges seem to fail with triangular matrices:

```julia
julia> s=randn(6,6); s = s*s'
6x6 Array{Float64,2}:
 12.6695    4.37903    3.78534   -1.82609   9.07167   1.5337  
  4.37903   4.03807    2.3878    -3.87199   2.81139  -0.362388
  3.78534   2.3878     3.7409    -2.44415   2.95657   0.558897
 -1.82609  -3.87199   -2.44415    8.43938  -2.7138    1.60016
  9.07167   2.81139    2.95657   -2.7138    7.78165   0.22353
  1.5337   -0.362388   0.558897   1.60016   0.22353   2.67511

julia> u=chol(s)
6x6 UpperTriangular{Float64,Array{Float64,2}}:
 3.55943  1.23026  1.06347   -0.513029   2.54863    0.430883
 0.0      1.58887  0.679383  -2.0397    -0.20398   -0.561711
 0.0      0.0      1.46573   -0.349872   0.262503   0.329038
 0.0      0.0      0.0        1.97317   -0.87701    0.400681
 0.0      0.0      0.0        0.0        0.637546  -1.13589
 0.0      0.0      0.0        0.0        0.0        0.784136

julia> u[3:5,6]
ERROR: ArgumentError: Triangular matrix must have two dimensions
 in similar at linalg/triangular.jl:27
 in _unsafe_getindex at multidimensional.jl:193
 in getindex at abstractarray.jl:488
```

This was in version 0.4, but the same error occurs in today's 0.5.

### PR DESCRIPTION
**Pull request by andreasnoack**
and try to be consistent across the special matrices. Fixes JuliaLang/julia#15193.

This has been extensively discussed in https://github.com/JuliaLang/LinearAlgebra.jl/issues/271. @tkelman I think this was somewhat in line with your suggestion and I believe it will make the interaction with special matrices smoother (i.e. less throwing).

However, this doesn't have to be the last word on `similar` for special matrices. We can still consider splitting up the functionality in more functions later if necessary.

### CODE REVIEW

**Comment by tkelman** [comment]
Will review more completely, but the quick tldr is this is doing option 1 from #13731? It's not perfect but I think it's a decent short term stopgap.

**Comment by andreasnoack** [comment]
Yes. It's option 1.

File: base/linalg/symmetric.jl [hunk 1]
```diff
@@ -33,6 +33,18 @@ end
...
     r
 end
+
+similar{T}(A::Symmetric, ::Type{T}) = Symmetric(similar(A.data, T))
+# Hermitian version can be simplified when check for imaginary part of
+# diagonal in Hermitian has been removed
+function similar{T}(A::Hermitian, ::Type{T})
+    B = similar(A.data, T)
+    for i = 1:size(A,1)
+        B[i,i] = 0
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: `real(B[i,i])` ?

**Comment by tkelman** [comment]
Can you add tests that check that the structural zeros or symmetries are respected in the "similar with specified output size" case? That's now going to some fallbacks that I can't quite trace in my head without building and introspecting on this branch.

**Comment by andreasnoack** [comment]
> Can you add tests that check that the structural zeros or symmetries are respected in the "similar with specified output size" case?

I don't understand this. When you specify the output size, you get an array of the "parent type". Most often that is a `Matrix` and therefore it won't have any structural zeros.

File: base/linalg/symmetric.jl (hunk 1 above)
Comment (andreasnoack) [inline base/linalg/symmetric.jl]: The value shouldn't really matter here.

**Comment by tkelman** [comment]
The question is whether the result of similar should be preset with the structural data from the input matrix in the case where you're losing information by returning Matrix instead of a more specialized type, ot if it should always be the user's responsibility to manually iterate through even uninteresting elements to set them.

**Comment by andreasnoack** [comment]
The structure doesn't generally have a meaning when asking for a specific shape. E.g. triangularity and symmetry can't be imposed on the rectangular matrices. In practice, I think the cases where you ask for a specific shape will be cases where you'll visit all elements.

Instead of falling back to the `similar` method in `abstractarray.jl`, we could add `similar` methods to each of the special matrices that initialize the elements with the structure whenever `m=n`, but it seems a bit arbitrary and adds quite a few extra methods so I'd like to see if there is really a need for this first.

**Comment by tkelman** [comment]
Relying on "visit all elements" use case assumptions doesn't sit well, but this does depend on what similar is really supposed to be used for and increasingly points IMO that it should be split into better specified uses going forward. I guess we should try this out for now though.

You can do triangular (trapezoidal) rectangular matrices, I think symmetry is the main structural property that imposes actual size constraints mathematically as opposed to just as current implementation limitations.

**Comment by mbauman** [comment]
This seems like the right direction given our definition and use of similar.

The next question, then, is if that definition is actually *useful* for generic programming… and in what cases.  Is it worth keeping `similar` for the new-shape case?  We've been using similar in this manner for the non-scalar fallbacks, and almost all array types have needed to change to returning an `Array` in order to use those fallbacks.  Those that haven't end up implementing their own specializations of the algorithm anyways (e.g., sparse).

As far as I'm aware, the only array types that return a non-`Array` when requesting a new shape from similar and still do something reasonable in the non-scalar indexing fallbacks are StructsOfArrays/NullableArrays.  I suppose this makes sense… because instead of adding or exploiting structural storage information, those array types do something special to the element type itself.  So they can still do something useful in the different-shape case.

File: test/linalg/triangular.jl [hunk 2]
```diff
@@ -38,14 +38,18 @@ for elty1 in (Float32, Float64, BigFloat, Complex64, Complex128, Complex{BigFloa
...
+        @test eltype(similar(A1, Int)) == Int
+        @test isa(similar(A1, (3,2)), Matrix{elty1})
+        @test isa(similar(A1, Int, (3,2)), Matrix{Int})
 
         # getindex
         ## Linear indexing
         for i = 1:length(A1)
             @test A1[i] == full(A1)[i]
         end
+        @test isa(A1[2:4,1], Matrix)
```
Comment (tkelman) [inline test/linalg/triangular.jl]: `Vector` ?
