### PR TITLE
Correct rounding mode after calling fma

### LINKED ISSUE #9847: test/numbers.jl fails on 32-bit platform
```
$ make test-numbers
    JULIA test/numbers
     * numbers             exception on 1: ERROR: LoadError: test failed: ("0.3" != "0.3")
 in expression: repr(0.1 + 0.2) != "0.3"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in runtests at /usr/local/src/julia/julia/test/testdefs.jl:66
 in anonymous at multi.jl:642
 in run_work_thunk at multi.jl:603
 in remotecall_fetch at multi.jl:676
 in remotecall_fetch at multi.jl:691
 in anonymous at task.jl:1614
while loading numbers.jl, in expression starting on line 318
ERROR: LoadError: LoadError: test failed: ("0.3" != "0.3")
 in expression: repr(0.1 + 0.2) != "0.3"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in runtests at /usr/local/src/julia/julia/test/testdefs.jl:66
 in anonymous at multi.jl:642
 in run_work_thunk at multi.jl:603
 in remotecall_fetch at multi.jl:676
 in remotecall_fetch at multi.jl:691
 in anonymous at task.jl:1614
while loading numbers.jl, in expression starting on line 318
while loading /usr/local/src/julia/julia/test/runtests.jl, in expression starting on line 42

make[1]: *** [numbers] Error 1
make: *** [test-numbers] Error 2
[Rick@steelers julia]$ ./julia -e 'versioninfo()'
Julia Version 0.4.0-dev+2824
Commit 6bc53e6* (2015-01-19 20:14 UTC)
Platform Info:
  System: Linux (i686-redhat-linux)
  CPU: Genuine Intel(R) CPU           T2250  @ 1.73GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Banias)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Interestingly ...
```
$ ../julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2824 (2015-01-19 20:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6bc53e6* (0 days old master)
|__/                   |  i686-redhat-linux

julia> repr(0.1 + 0.2)
"0.30000000000000004"

julia> include("testdefs.jl")
2-element Array{Union(UTF8String,ASCIIString),1}:
 "/usr/local/src/julia/julia/usr/local/share/julia/site/v0.4"
 "/usr/local/src/julia/julia/usr/share/julia/site/v0.4"      

julia> repr(0.1 + 0.2)
"0.30000000000000004"

julia> include("numbers.jl")
ERROR: LoadError: test failed: ("0.3" != "0.3")
 in expression: repr(0.1 + 0.2) != "0.3"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
while loading /usr/local/src/julia/julia/test/numbers.jl, in expression starting on line 318

julia> repr(0.1 + 0.2)
"0.3"

```

### PR DESCRIPTION
**Pull request by eschnett**
This seems to be necessary on 32-bit Intel Linux systems to fix #9847 and the issues mentioned in the comments of #9898.

This needs to be tested on 32-bit Intel Linux systems before applying.

### CODE REVIEW

**Comment by nalimilan** [comment]
Shouldn't you call `get_rounding_raw()`, save the result, and restore it on exit?

File: base/float.jl [hunk 1]
```diff
@@ -386,10 +386,35 @@ end
...
-fma_libm(x::Float32, y::Float32, z::Float32) =
-    ccall(("fmaf", libm_name), Float32, (Float32,Float32,Float32), x, y, z)
-fma_libm(x::Float64, y::Float64, z::Float64) =
-    ccall(("fma", libm_name), Float64, (Float64,Float64,Float64), x, y, z)
+function fma_libm(x::Float32, y::Float32, z::Float32)
+    r = ccall(("fmaf", libm_name), Float32, (Float32,Float32,Float32), x, y, z)
+    # This is necessary on 32-bit Intel Linux, probably on OS X, and
+    # maybe on Windows
+    # TODO: Disable this for non-Intel systems
+    if is(Int, Int32)
```
Comment (nalimilan) [inline base/float.jl]: Maybe better written as `WORD_SIZE == 32`?

Comment (eschnett) [inline base/float.jl]: `const WORD_SIZE = int(Int.size)*8`

I think I should actually be looking at `Base.ARCH` instead. Do you know what value it has for a 32-bit Intel system? `:i686`?

Comment (nalimilan) [inline base/float.jl]: > const WORD_SIZE = int(Int.size)*8

Yeah, that's the same, I was just making a stylistic point.

> I think I should actually be looking at Base.ARCH instead. Do you know what value it has for a 32-bit Intel system? :i686?

`ARCH` is passed to gcc/clang, so it may be set to any value that -march/mtune support. For 32-bit Intel, this is a very long list which evolves over time: https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html So it's not possible to future-proof detection if somebody sets `ARCH = some_new_cpu` later in a build.

So it looks like we'd better use compiler macros instead: http://sourceforge.net/p/predef/wiki/Architectures/ or http://nadeausoftware.com/articles/2012/02/c_c_tip_how_detect_processor_type_using_compiler_predefined_macros Adding a global variable containing an enum to `base.build_h.jl` looks like the best solution, so that it could be used to detect e.g. ARM if needed.

Comment (eschnett) [inline base/float.jl]: Are you sure that `Base.ARCH` is this complicated? For me it's just `:x86_64` -- the actual CPU is not encoded.

Are you using a 32-bit Linux system? What is the value of `Base.ARCH` for you?

Comment (nalimilan) [inline base/float.jl]: I don't have a direct access to a 32-bit machine, only via Fedora builders. AFAICS in Make.inc, `ARCH` is extracted from `$(CC) -dumpmachine`, so my statement that we may get any option accepted by `-mtune` looks exaggerated as long as the user doesn't override this variable. Still, there are quite a few different cases handled in the Makefiles: https://github.com/JuliaLang/julia/blob/master/Make.inc#L476-496 But since all unknown values currently lead to a failure, it should be fine not to handle them.

If I were you, I'd create a new variable at these lines, and write it to `base/build_h.jl`. That way, it will evolve naturally with the Makefiles if something changes in the future.

Comment (eschnett) [inline base/float.jl]: I'm tempted to simply ask LLVM instead. It must know the truth about what is going on.

Comment (tkelman) [inline base/float.jl]: It's going to depend where Julia gets built. Some distributions use `i386-linux-gnu`, others `i486-linux-gnu` (https://github.com/JuliaLang/julia/issues/3421) or `i586-linux-gnu` (https://github.com/JuliaLang/julia/issues/6029) or `i686-linux-gnu`.

Comment (nalimilan) [inline base/float.jl]: Looks like this is what we need: http://llvm.org/docs/doxygen/html/classllvm_1_1Triple.html#a547abd13f7a3c063aa72c8192a868154

The Triple is already used here: https://github.com/JuliaLang/julia/blob/master/src/codegen.cpp#L410

**Comment by simonbyrne** [comment]
From what I understand, isn't the problem just with old versions of the glibc libm? i.e. openlibm and newer glibcs are unaffected? If so, this fix seems like overkill.

**Comment by nalimilan** [comment]
@simonbyrne Yet we want Julia to work on older distributions, and even Fedora 20 (6 months old) seems to be affected. Or maybe we can forbid using the system's libm instead of openlibm on those OSes?

**Comment by simonbyrne** [comment]
I think the default should be to use openlibm when no hardware support exists. As this seems to be a bit complicated (I don't know enough about LLVM to understand how it links to libraries), then the current behaviour seems like the next best option: I would just add the second part of this PR that resets the rounding mode during build.

I don't think the first part (adding the `set_rounding` calls to the `fma` function) is useful: for one thing, it is going to clobber performance even more, and will also cause problems if people *were* using a different rounding mode. I don't think we can be in the business of monkey-patching potentially broken system libraries.

**Comment by eschnett** [comment]
Regarding always using openlibm: That's not an option if we want performance. To get performance, we need to use LLVM's `fma` intrinsic that can be translated to a single machine instruction if that exists. And if that doesn't exist, LLVM will fall back to libm. At this point, there is no way to tell LLVM to use openlibm instead. Note that we implement `fma` via an LLVM intrinsic, not via a libcall as we do for `sin`, `cos`, etc.

If we don't want to forego a fast `fma`, then we have to test at build time whether `fma` is broken. At build time, we know the rounding mode, so we can reset it after calling the (broken) `fma. Later, the broken `fma` will be disabled and never used.

So we're not really "monkeying". We're detecting whether the system has a bug, and circumvent it. If there's a better way of doing so, I'd be all for it. But the following ideas won't work, as discussed previously:
- use openlibm -- that's significantly slower if `fma` is supported in hardware
- restore previous rounding mode -- see previous discussion, that's probably exactly the feature that is broken and over which the `fma' implementation trips
- wait for glibc to correct this problem -- we really can't expect people to update their libc; that's a fundamental piece of system software that, in practice, cannot be "replaced" in an existing install
- testing without correcting the rounding mode afterwards -- experiments show that a broken `fma` does change the rounding mode, so we do need to reset it to a correct value afterwards

**Comment by eschnett** [comment]
I simplified the implementation. Instead of trying to correct libc's `fma` implementation, it is now left as it is.

Also, after testing, the rounding mode is set unconditionally, since there's little point in creating new infrastructure just to find out whether the current system is a 32-bit Intel Linux system.

**Comment by eschnett** [comment]
Regarding submitting a PR for glibc: I currently think that even recent glibc implementations may be broken. I cannot test, because I don't have a 32-bit Intel Linux system at hand, and many of the failure reports I've seen were somewhat unclear on the details. So, if you have such a system -- could you write a small C program that demonstrates the failure, including the rounding mode problems, and open such a PR for glibc? We owe it to them.

**Comment by eschnett** [comment]
Is this new version of the patch good to apply?

**Comment by simonbyrne** [comment]
@staticfloat @rickhg12hs Any chance you could try this out?

**Comment by staticfloat** [comment]
As stated in [this comment](https://github.com/JuliaLang/julia/pull/9898#issuecomment-71391543), this doesn't fix it because after your tests the numbers are correct, but the floating-point registers are clobbered, so we still use `libm` instead of `openlibm`, and every `fma()` call forever after clobbers the registers.

**Comment by simonbyrne** [comment]
what if we did something like:
```
fma_llvm(1.0,2.0,3.0)
if 0.1+0.2==0.3
   # fma = fma_libm
   # set_rounding
else
   # fma = fma_llvm
end
```

**Comment by staticfloat** [comment]
We could do that. I would rather directly probe the floating point
registers though, since we already have the code to do that.

**Comment by simonbyrne** [comment]
> I would rather directly probe the floating point
registers though, since we already have the code to do that.

I thought the problem was that we didn't?

**Comment by eschnett** [comment]
@staticfloat Can you point me to the code that tests the floating-point registers? I know where to find them in Julia -- but as I don't have access to a system where this fails, I need a screen shot from an interactive session (or a function written in Julia) that I can use to write this code. Currently, the best test I have is `0.1 + 0.2 == 0.3`. I recall other reports that indicate that `get_rounding` is not working correctly.

Even better -- could you write the failure-detecting code instead of me, since you can actually test it? I've been flying blind for the past days, and that's not sustainable.

**Comment by tkelman** [comment]
@eschett if you have a 64-bit Linux system with multiarch gcc, you should be able to compile a 32-bit version of Julia. On Ubuntu 14.04, I can do so with the following in Make.user:
```
override ARCH = i686
override MARCH = i686
override JULIA_CPU_TARGET = pentium4
```

Best to do this in a separate clone due to dependencies. Because of some cmake messiness this currently will build libgit2 with the wrong arch so that test will fail right now, but everything up to there should be representative. I can reproduce the failure to bootstrap without commenting out the asserts, and the repr test failure.

**Comment by staticfloat** [comment]
I'm working on it, but its difficult for me to get the test (which involves
llvmcall) to run in the bootstrap phase properly.

**Comment by staticfloat** [comment]
Okay, I'm having trouble with this because the fact that using an `llvmcall()` intrinsic causes an error the first time keeps on breaking my bootstrap, even if I wrap it in a `try/catch` and put it at the end of the bootstrap right before calling `precompile.jl`.  Specifically, this is the code I'm moving around:

```
# fused multiply-add
fma_libm(x::Float32, y::Float32, z::Float32) =
    ccall(("fmaf", libm_name), Float32, (Float32,Float32,Float32), x, y, z)
fma_libm(x::Float64, y::Float64, z::Float64) =
    ccall(("fma", libm_name), Float64, (Float64,Float64,Float64), x, y, z)
fma_llvm(x::Float32, y::Float32, z::Float32) =
    box(Float32,fma_float(unbox(Float32,x),unbox(Float32,y),unbox(Float32,z)))
fma_llvm(x::Float64, y::Float64, z::Float64) =
    box(Float64,fma_float(unbox(Float64,x),unbox(Float64,y),unbox(Float64,z)))
# Disable LLVM's fma if it is incorrect, e.g. because LLVM falls back
# onto a broken system libm; if so, use openlibm's fma instead. Also
# fallback to opeblibm if it messes with the floating point rounding
# 1.0000305f0 = 1 + 1/2^15
# 1.0000000009313226 = 1 + 1/2^30

function get_mxcsr_rounding()
    mxcsr = llvmcall( """%ptr = alloca i32
              call void @llvm.x86.sse.stmxcsr(i32 * %ptr)
              %curval = load i32 * %ptr
              ret i32 %curval""", UInt32, () )
    bits(mxcsr)[18:19]
end

# Need to warmup llvmcall due to https://github.com/JuliaLang/julia/pull/8740
try
    get_mxcsr_rounding()
end
initial_rounding = get_mxcsr_rounding()

if (fma_llvm(1.0000305f0, 1.0000305f0, -1.0f0) == 6.103609f-5 &&
    (fma_llvm(1.0000000009313226, 1.0000000009313226, -1.0) ==
     1.8626451500983188e-9) && initial_rounding == get_mxcsr_rounding() )
    fma(x::Float32, y::Float32, z::Float32) = fma_llvm(x,y,z)
    fma(x::Float64, y::Float64, z::Float64) = fma_llvm(x,y,z)
else
    fma(x::Float32, y::Float32, z::Float32) = fma_libm(x,y,z)
    fma(x::Float64, y::Float64, z::Float64) = fma_libm(x,y,z)
end
# This is necessary at least on 32-bit Intel Linux, since fma_llvm may
# have called glibc, and some broken glibc fma implementations don't
# properly restore the rounding mode
Rounding.set_rounding_raw(Float32, Rounding.JL_FE_TONEAREST)
Rounding.set_rounding_raw(Float64, Rounding.JL_FE_TONEAREST)
```

After bootstrapping, I can run this code no problem and I get the desired result, but in the middle of bootstrapping, I invariably get an error like the following:
```
llvmintrinsics.jl
error during bootstrap: LoadError(at "sysimg.jl" line 297: LoadError(at "llvmintrinsics.jl" line 33: ErrorException("error compiling anonymous: Failed to parse LLVM Assembly:
julia: <string>:4:11: error: use of undefined value '@llvm.x86.sse.stmxcsr'
call void @llvm.x86.sse.stmxcsr(i32 * %ptr)
          ^
")))
Basic Block in function 'julia_anonymous_17814' does not have terminator!
label %try
LLVM ERROR: Broken module, no Basic Block terminator!
make[1]: *** [/home/vagrant/buildbot/slave/build_ubuntu14_04-x86/build/usr/lib/julia/sys0.o] Error 1
make: *** [release] Error 2
```

Where `llvmintrinsics.jl` is a file I added to the system image generation process at the end to avoid any issues with not having things like `@mstr` defined.  The backtrace here is for running the slightly modified code:
```
try
    llvmcall( """%ptr = alloca i32
              call void @llvm.x86.sse.stmxcsr(i32 * %ptr)
              %curval = load i32 * %ptr
              ret i32 %curval""", UInt32, () )
end
```
as my warm-up step.  Any ideas?

**Comment by eschnett** [comment]
It's probably not worthwhile to call `get_mxcsr_rounding` to determine whether the rounding mode is off. `0.1+0.2` should be fine for double precision, and we can cook up a similar expression for single precision.

**Comment by simonbyrne** [comment]
I agree the `0.1+0.2` check is probably fine, as long as it's accompanied by a comment explaining why. You don't need a single precision check, as both are always the same (the reason for the type argument in `set_rounding` is for `BigFloat`s).

**Comment by staticfloat** [comment]
PR submitted to @eschnett's PR branch

**Comment by simonbyrne** [comment]
I can recreate the issue in Julia on a 32bit VM running glibc 2.19. However I'm having trouble reproducing the same problem in pure C, even with liberal use of volatile. [Here's my code](https://gist.github.com/simonbyrne/d2c84417dd831dfea8fb): any suggestions?

**Comment by simonbyrne** [comment]
Quick update: I can replicate it with clang but not gcc: see [here](https://gist.github.com/simonbyrne/c59282e9c4f4eac35ca4). That's about the extent of my C knowledge, any ideas would be appreciated.

**Comment by simonbyrne** [comment]
Ah, okay: the issue is that gcc is using x87 instructions (and so is unaffected), whereas clang is using the sse instructions. Need to use both `-msse2 -mfpmath=sse` options.

**Comment by simonbyrne** [comment]
See [glibc #17907](https://sourceware.org/bugzilla/show_bug.cgi?id=17907).

**Comment by simonbyrne** [comment]
Apparently this is fixed in 2.20 ([glibc #16064](https://sourceware.org/bugzilla/show_bug.cgi?id=16064)).

**Comment by simonbyrne** [comment]
It's not pretty, but I think it's a sensible compromise. If I understand correctly, this should only break if a user is running a broken system libm, and manually enables `USE_SYSTEM_LIBM` in their build. If that's the case, then I don't think there's much we can do.

**Comment by ViralBShah** [comment]
I think that is reasonable.

**Comment by eschnett** [comment]
I squashed all commits. I think this is now ready to merge.

**Comment by eschnett** [comment]
@simonbyrne Unfortunately, this is independent of `USE_SYSTEM_LIBM`; see the discussion above.

**Comment by simonbyrne** [comment]
Thanks.

@eschnett What I mean was, if `USE_SYSTEM_LIBM` is enabled, then `fma_libm` will still point to the system libm, and so won't solve the problem. But there's not much we can really do about that.

**Comment by nalimilan** [comment]
I confirm this appears to fix the build on 32-bit Fedora.
