### PR TITLE
[JuliaLowering] Fix and test quoting in getproperty

### LINKED ISSUE #168: "invalid `.` syntax" when lowering `Expr(:., Module, Expr(:quote, :f))`
```julia
julia> module Foo
           bar = 1
       end
Main.Foo

julia> println(eval(Expr(:., Foo, QuoteNode(:bar))))
1

julia> println(eval(Expr(:., Foo, Expr(:quote, :bar))))
┌ Info: JuliaLowering threw given input:
│   code = :((Main.Foo).bar)
...
ERROR: LoweringError:
#= none:1 =# - invalid `.` syntax
Expression:
  (call Base.JuliaLowering.interpolate_ast Expr (inert bar))
Containing expressions:
  (. Main.Foo (call Base.JuliaLowering.interpolate_ast Expr (inert bar)))
... 
Stacktrace:
 [1] expand_forms_2(ctx::Base.JuliaLowering.MacroExpansionContext{Dict{…}}, ex::Base.JuliaSyntax.SyntaxTree{Dict{…}})
   @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:4482
```

Seems to be related to `interpolate_ast`.

As a mostly-unrelated side note, it might be time to put in the flisp optimization for "simple" expression quoting / interpolation? I expect more `macro` shenanigans around expecting this to reduce "canonically" in the simple cases.

### PR DESCRIPTION
**Pull request by mlechu**
Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/168.  Note that quoting still needs more thought, but this change takes the conservative approach where `(inert K"Identifier")` == `(inert_syntaxtree K"Identifier")` == `K"Symbol"`.

### CODE REVIEW

File: JuliaLowering/src/validation.jl [hunk 1]
```diff
@@ -486,26 +484,32 @@ vst1_const_assign(vcx, st) = @stm st begin
     _ -> @fail(st, "expected assignment after `const`")
 end
 
+# syntax TODO: all-underscore variables may be read from with dot syntax
+vst1_dot_getproperty_rhs(vcx, st) = @stm st begin
+    [K"inert" x] -> pass()
+    [K"inert_syntaxtree" x] -> pass()
+    [K"Identifier"] -> pass()
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl:491]: maybe worth checking the `mod` attribute?

**Review by topolarity — APPROVED** [review]
Looks like we've got some more kinks to work out here, but this is a good improvement thanks!

File: JuliaLowering/src/validation.jl (hunk 1 above)
Comment (mlechu) [reply JuliaLowering/src/validation.jl:491]: This case just lowers to a getproperty call with an unquoted second arg, so a globalref there should behave similar to a global variable.  I'm fine allowing this even if flisp probably doesn't.

Comment (topolarity) [reply JuliaLowering/src/validation.jl:491]: Doesn't the `:inert` mean that it would act like a `GlobalRef(...)` not an access to the corresponding global variable?

Comment (mlechu) [reply JuliaLowering/src/validation.jl:491]: Correct, but `(. x (inert anything))` is accepted by flisp, so I've replicated that here (inert globalref generally produces `MethodError: no method matching getproperty(::typeof(x), ::GlobalRef)`.  In my previous comment, I assumed you meant an unquoted globalref.

Comment (topolarity) [reply JuliaLowering/src/validation.jl:491]: Ah OK, makes sense to me. I agree with you 👍
