### PR TITLE
Fix typo: " is is "

### LINKED ISSUE #51373: Typo in `Random.default_rng` doc
There is a typo in [ `Random.default_rng`](https://docs.julialang.org/en/v1/stdlib/Random/#Random.default_rng) doc.

Search for " is is"

### PR DESCRIPTION
**Pull request by prbzrg**
Closes #51373

### CODE REVIEW

File: stdlib/Random/src/RNGs.jl [hunk 1]
```diff
@@ -336,7 +336,7 @@ typeof_rng(::_GLOBAL_RNG) = TaskLocalRNG
 Return the default global random number generator (RNG).
 
 !!! note
-    What the default RNG is is an implementation detail.  Across different versions of
+    The default RNG is an implementation detail. Across different versions of
```
Comment (rfourquet) [inline stdlib/Random/src/RNGs.jl:339]: I find this wording unclear: is the existence of the default RNG an implementation detail? no, it's documented to exist and be returned by `default_rng()`. What is an implementation detail is the implementation of this default RNG, i.e. its type.  See #52385 for a rewording.
