### PR TITLE
finish implementation of upgradable stdlibs

### LINKED ISSUE #53983: 1.11.0-alpha2: precompilation fails if `JULIA_DEPOT_PATH` is set
This is a duplicate of #53831. I'm creating a new issue because I now have a reproducible MWE and because the old issue was apparently not noticed.

Setup: There is no `~/.julia`, and `JULIA_DEPOT_PATH` is set to the empty directory `/tmp/julia-depot`. Then I try to install and use a package as follows:
```
~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-alpha2 (2024-03-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.11.0-alpha2
Commit 9dfd28ab751 (2024-03-18 20:35 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_DEPOT_PATH = /tmp/julia-depot

(@v1.11) pkg> st
  Installing known registries into `/tmp/julia-depot`
Status `/tmp/julia-depot/environments/v1.11/Project.toml` (empty project)

(@v1.11) pkg> add Chairmarks
    Updating registry at `/tmp/julia-depot/registries/General.toml`
   Resolving package versions...
   Installed Chairmarks ─ v1.2.1
    Updating `/tmp/julia-depot/environments/v1.11/Project.toml`
  [0ca39b1e] + Chairmarks v1.2.1
    Updating `/tmp/julia-depot/environments/v1.11/Manifest.toml`
  [0ca39b1e] + Chairmarks v1.2.1
  [de0858da] + Printf v1.11.0
  [4ec0a83e] + Unicode v1.11.0
Precompiling project...
  ✓ Unicode
  ✓ Printf
  3 dependencies successfully precompiled in 3 seconds
  2 dependencies precompiled but different versions are currently loaded. Restart julia to access the new versions

julia> using Chairmarks
[ Info: Precompiling Chairmarks [0ca39b1e-fe0b-4e98-acfc-b1656634c4de] (cache misses: wrong dep version loaded (2))
┌ Warning: Module Printf with build ID fafbfcfd-be51-2905-0028-424d602318e3 is missing from the cache.
│ This may mean Printf [de0858da-6303-5e67-8744-51eddeeeb8d7] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:2319
┌ Info: Skipping precompilation due to precompilable error. Importing Chairmarks [0ca39b1e-fe0b-4e98-acfc-b1656634c4de].
└   exception = nothing

julia>
```
The check marks (✓) in front of `Unicode` and `Printf` are actually red and not green.

Restarting:
```
~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-alpha2 (2024-03-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.11) pkg> st
Status `/tmp/julia-depot/environments/v1.11/Project.toml`
  [0ca39b1e] Chairmarks v1.2.1

julia> using Chairmarks
[ Info: Precompiling Chairmarks [0ca39b1e-fe0b-4e98-acfc-b1656634c4de] (cache misses: wrong dep version loaded (2))
┌ Warning: Module Printf with build ID fafbfcfd-be51-2905-0028-424d602318e3 is missing from the cache.
│ This may mean Printf [de0858da-6303-5e67-8744-51eddeeeb8d7] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:2319
┌ Info: Skipping precompilation due to precompilable error. Importing Chairmarks [0ca39b1e-fe0b-4e98-acfc-b1656634c4de].
└   exception = nothing

julia>
```
If `JULIA_DEPOT_PATH` is not set, then the problem disappears.

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #53983

~~Unfortunately, TOML has a design problem with the way it is used by Pkg (because of the way they use Dates without depending on it correctly, they want to assume things that are false now), so this does not yet work correctly for Pkg. But maybe if we change some of the uses of loaded_packages to explicit_loaded_modules in loading, we can try to make the way those three packages interact to still kind of mostly work.~~ (Fixed in Pkg now and removed from TOML in https://github.com/JuliaLang/julia/pull/54755)

~~Also currently one test is broken, as we need some more code rearrangement to make it legal again for an `__init__` method to import code.~~

### CODE REVIEW

File: base/loading.jl [hunk 1]
```diff
@@ -2289,14 +2300,19 @@ end
 PkgOrigin() = PkgOrigin(nothing, nothing, nothing)
 const pkgorigins = Dict{PkgId,PkgOrigin}()
 
-const loaded_modules = Dict{PkgId,Module}()
-# Emptied on Julia start
-const explicit_loaded_modules = Dict{PkgId,Module}()
+const explicit_loaded_modules = Dict{PkgId,Module}() # Emptied on Julia start
+const loaded_modules = Dict{PkgId,Module}() # available to be explicitly loaded
+const loaded_precompiles = Dict{Pair{PkgId,UInt128},Module}() # extended (complete) list of modules, available to be loaded
```
Comment (JeffBezanson) [inline base/loading.jl:2305]: Can we be clearer about the differences between these three dicts? Is the first one modules loaded during this session? Is the second one currently visible modules, and the third one all modules? I'm not sure.

**Comment by matthias314** [comment]
I'm sorry, but this doesn't fully fix #53983. There are still problems when using `startup.jl`. The setting is as follows: no `~/.julia` directory, `JULIA_DEPOT_PATH=/tmp/julia-depot` containing the file `/tmp/julia-depot/config/startup.jl` with contents
```
using InteractiveUtils
```
Then:
```
/usr/local/git/julia$ ./julia
[ Info: Precompiling InteractiveUtils [b77e0a4c-d291-57a0-90e8-8db25a27a240] 
[ Info: Precompiling REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.766 (2024-06-21)
 _/ |\__'_|_|_|\__'_|  |  Commit 9d8ecaa899 (0 days old master)
|__/                   |

julia>

[ now I press the key "]" ]

(@v1.12) pkg> Unhandled Task ERROR: ArgumentError: Package REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```
Starting Julia with `--startup-file=no` works fine. Unsetting `JULIA_DEPOT_PATH` and moving `startup.jl` to `~/.julia/config` instead also works fine.
```
Julia Version 1.12.0-DEV.766
Commit 9d8ecaa899 (2024-06-21 17:00 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_DEPOT_PATH = /tmp/julia-depot
```

**Comment by vtjnash** [comment]
Much appreciated. I had fixed this earlier in the PR history, then forgot why I had the code to handle this and removed it again. Now it is clear again why I needed to handle this case with that example.

**Comment by Keno** [comment]
I haven't fully bisected, but it seems like this is causing the following:
```
ERROR: InitError: KeyError: key Base.PkgId(Base.UUID("872c559c-99b0-510c-b3b7-b6c96a88d5cd"), "NNlib") not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:477 [inlined]
  [2] macro expansion
    @ ./lock.jl:273 [inlined]
  [3] root_module(key::Base.PkgId)
    @ Base ./loading.jl:2358
  [4] parse_pkg_files(id::Base.PkgId)
    @ Revise ~/.julia/dev/Revise/src/loading.jl:38
  [5] watch_package(id::Base.PkgId)
    @ Revise ~/.julia/dev/Revise/src/pkgs.jl:349
  [6] add_require(sourcefile::String, modcaller::Module, idmod::String, modname::String, expr::Expr)
    @ Revise ~/.julia/dev/Revise/src/pkgs.jl:188
  [7] top-level scope
    @ ~/.julia/packages/Requires/Z8rfN/src/require.jl:70
  [8] (::NNlib.var"#599#603")()
    @ NNlib ~/.julia/packages/Requires/Z8rfN/src/require.jl:106
  [9] top-level scope
    @ ~/.julia/packages/Requires/Z8rfN/src/require.jl:20
 [10] macro expansion
    @ ~/.julia/packages/Requires/Z8rfN/src/require.jl:98 [inlined]
 [11] (::NNlib.var"#598#602")()
    @ NNlib ~/.julia/packages/Requires/Z8rfN/src/init.jl:11
 [12] __init__()
    @ NNlib ~/.julia/packages/Requires/Z8rfN/src/init.jl:18
 [13] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1305
 [14] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1293
```

**Comment by KristofferC** [comment]
Should we use https://github.com/JuliaLang/julia/pull/53849 for this then?

**Comment by Keno** [comment]
> Should we use #53849 for this then?

That helps for pre-merge versioning. Now this can just use a regular VERSION check if intended or a fix if not.

**Comment by KristofferC** [comment]
So this PR should have added an entry?

**Comment by Keno** [comment]
If the break here was intentional, then what should have happened would be:
1. This PR adds an entry
2. We make the package work both ways by querying the entry
3. We merge/tag the package
4. We merge the PR here

**Comment by KristofferC** [comment]
Any change to an internal is possibly breaking. And so far it seems no new entry has been added so I guess no internals have been broken? But Revise doesn't work now. So what should be changed in the workflow to make this thing actually do something?

**Comment by KristofferC** [comment]
I am worried backporting this will cause https://github.com/JuliaLang/julia/issues/54940 on 1.11 but will have to check.
