### PR TITLE
replace some occurrences of iteration over 1:length with more idiomatic structures (mostly eachindex)

### LINKED ISSUE #55136: `permute_dims` fails in edge case because of use if `1:length`
```julia
struct OffsetArray{T, N, P} <: AbstractArray{T, N}
    parent::P
    offset::NTuple{N, Int}
end
OffsetArray(array::AbstractArray{T, N}, offset::NTuple{N, Int}) where {T, N} =
    OffsetArray{T, N, typeof(array)}(array, offset)
Base.getindex(oa::OffsetArray, inds...) = getindex(oa.parent, map(.-, inds, oa.offset)...)
Base.setindex!(oa::OffsetArray, v, inds...) = setindex!(oa.parent, v, map(.-, inds. oa.offset)...)
Base.size(oa::OffsetArray) = size(oa.parent)
Base.axes(oa::OffsetArray) = map(.+, axes(oa.parent), oa.offset)

struct DefaultArray{T, N, P} <: AbstractArray{T, N}
    parent::P
    default::T
end
DefaultArray(array::AbstractArray{T, N}, default::T) where {T, N} =
    DefaultArray{T, N, typeof(array)}(array, default)
Base.getindex(da::DefaultArray, inds...) = checkbounds(Bool, da.parent, inds...) ? getindex(da.parent, inds...) : da.default
Base.setindex!(da::DefaultArray, v, inds...) = setindex!(da.parent, v, inds...)
Base.size(da::DefaultArray) = size(da.parent)
Base.axes(da::DefaultArray) = axes(da.parent)

doa = DefaultArray(OffsetArray([2,3,1], (1,)), 2)
permutedims!(rand(2,2,3), rand(0,2,3), doa) # should throw, but reads undef instead
```

### PR DESCRIPTION
**Pull request by LilithHafner**
Base should be a model for the ecosystem, and `eachindex(x)` is better than `1:length(x)` in almost all cases. I've updated many, but certainly not all examples. This is mostly a NFC, but also fixes #55136.

### CODE REVIEW

**Comment by jishnub** [comment]
Should probably be backported?

**Review by tecosaur — APPROVED** [review]
This looks like a pretty straightforward improvement, CI failures appear unrelated

File: base/intfuncs.jl [hunk 1]
```diff
@@ -978,7 +978,7 @@ end
 
 Return an array with element type `T` (default `Int`) of the digits of `n` in the given
 base, optionally padded with zeros to a specified size. More significant digits are at
-higher indices, such that `n == sum(digits[k]*base^(k-1) for k=1:length(digits))`.
+higher indices, such that `n == sum(digits[k]*base^(k-1) for k in eachindex(digits))`.
```
Comment (KristofferC) [inline base/intfuncs.jl:981]: I think this was clearer before since one is taking an exponential of `k`. The genericness of iterating indices just takes away from the point being made.

Comment (LilithHafner) [reply base/intfuncs.jl:981]: That's a reasonable position. OTOH, with 1:length, you have to worry about bounds errors which also distracts from the point. Personally, I think it's similar either way.

**Comment by IanButterworth** [comment]
Not clear why this was removed from backport. Adding it back to 1.11 at least as it makes other things easier to backport.
