### PR TITLE
fix some new-edges issues

### LINKED ISSUE #56577: edge creation mistake
Looking at why some code wasn't loading correctly, I found this edge list isn't being generated correctly for `nteltype(::Type)` with 3 entries present for it where there should only be at most one of a different kind (method table rather than call and widened invoke given the resulting code), though preferable this would be zero edges:

```julia
julia> code_typed(eltype, (Type{A} where A<:(NamedTuple{names, T} where T<:Tuple{Vararg{Any, N}} where names where N),))[2][1].edges
7-element Vector{Any}:
 2
  Tuple{typeof(Base.nteltype), Type{A} where A<:(NamedTuple{names, T} where {N, names, T<:NTuple{N, Any}})}
  CodeInstance for MethodInstance for Base.nteltype(::Type{NamedTuple{names, T}} where names) where {N, T<:NTuple{N, Any}}
  nteltype(::Type) @ Base namedtuple.jl:230
  MethodInstance for Base.nteltype(::Type{A} where A<:(NamedTuple{names, T} where {N, names, T<:NTuple{N, Any}}))
  Tuple{typeof(Base.nteltype), Type}
  MethodInstance for Base.nteltype(::Type)

julia> code_typed(eltype, (Type{A} where A<:(NamedTuple{names, T} where T<:Tuple{Vararg{Any, N}} where names where N),))[2][1]
CodeInfo(
    @ namedtuple.jl:229 within `eltype`
1 ─ %1 = $(Expr(:static_parameter, 1))::Type{A} where A<:(NamedTuple{names, T} where {N, names, T<:NTuple{N, Any}})
│   %2 =   dynamic Base.nteltype(%1)::Any
└──      return %2
)
```

### PR DESCRIPTION
**Pull request by vtjnash**
- incorrect edge types were being added from inlining: there is minimal dispatch info available, so best not to add that (which was already added earlier) as it results in failures to validate later
- MethodTable/sig order in edges could confuse the iterator: always put the type before the edge now as that is more consistent
- edges wasn't converted to a SimpleVector, so they might get ignored later from being in the wrong format
- edges were not populated for optimize=false, which made debugging them more inconvenient

Fixes #56577

### CODE REVIEW

File: Compiler/src/typeinfer.jl [hunk 1]
```diff
@@ -488,14 +493,40 @@ function finishinfer!(me::InferenceState, interp::AbstractInterpreter)
...
+            if isa(callee, Method)
+                i += 2
+                continue
+            elseif isa(callee, MethodTable) # abstract dispatch (legacy style edges)
+                ccall(:jl_method_table_add_backedge, Cvoid, (Any, Any, Any), callee, item, caller)
+                i += 2
+                continue
+            elseif isa(callee, CodeInstance)
+                callee = callee.def
+            end
```
Comment (aviatesk) [inline Compiler/src/typeinfer.jl:527]:
```suggestion
        else
            callee = edges[i+1]
            if isa(callee, MethodTable) # abstract dispatch (legacy style edges)
                ccall(:jl_method_table_add_backedge, Cvoid, (Any, Any, Any), callee, item, caller)
                i += 2
                continue
            end
            # `invoke` edge
            if isa(callee, Method)
                # ignore `Method`-edges (from e.g. failed `abstract_call_method`)
                i += 2
                continue
            elseif isa(callee, CodeInstance)
                callee = callee.def
            end
```

**Review by aviatesk — APPROVED** [review]
