### PR TITLE
Fix dot(::Adjoint, ::Adjoint) for numbers that don't commute under multiplication

### LINKED ISSUE #908: dot(::Adjoint, ::Adjoint) incorrect for numbers that are not multiplicatively commutative
The overload `dot(x::Adjoint, y::Adjoint)` assumes that the number eltypes of the inputs commute under multiplication, so that `dot(x', y') == sum(x .* y') == conj(sum(x' .* y)) == conj(dot(x, y))`
https://github.com/JuliaLang/julia/blob/1aac07efe44c229abf41b9c50031783f46bed4bf/stdlib/LinearAlgebra/src/generic.jl#L889

For numbers that don't commute under multiplication (like Quaternions), this definition is incorrect. A short demo:

```julia
julia> using Quaternions, LinearAlgebra

julia> mydot(x, y) = mapreduce(mydot, +, x, y);  # define our own recursive dot function

julia> mydot(x::Number, y::Number) = dot(x, y)

julia> x = [quatrand() for _ in 1:2, _ in 1:2];

julia> y = [quatrand() for _ in 1:2, _ in 1:2];

julia> dot(x, y) ≈ mydot(x, y)  # fine
true

julia> dot(transpose(x), transpose(y)) ≈ mydot(transpose(x), transpose(y))   # fine
true

julia> dot(x', y') ≈ mydot(x', y')   # uh-oh
false

julia> method = @which dot(x', y')
dot(x::Adjoint, y::Adjoint) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:922

julia> Base.delete_method(method)

julia> dot(x', y') ≈ mydot(x', y')   # all good
true
```

This could be handled by restricting the types to `Union{Real,Complex}`, e.g.

```julia
 dot(x::Adjoint{Union{Real,Complex}}, y::Adjoint{Union{Real,Complex}}) = conj(dot(parent(x), parent(y))) 
```

### LINKED ISSUE #44152: dot(::Adjoint, ::Adjoint) incorrect for numbers that are not multiplicatively commutative
The overload `dot(x::Adjoint, y::Adjoint)` assumes that the number eltypes of the inputs commute under multiplication, so that `dot(x', y') == sum(x .* y') == conj(sum(x' .* y)) == conj(dot(x, y))`
https://github.com/JuliaLang/julia/blob/1aac07efe44c229abf41b9c50031783f46bed4bf/stdlib/LinearAlgebra/src/generic.jl#L889

For numbers that don't commute under multiplication (like Quaternions), this definition is incorrect. A short demo:

```julia
julia> using Quaternions, LinearAlgebra

julia> mydot(x, y) = mapreduce(mydot, +, x, y);  # define our own recursive dot function

julia> mydot(x::Number, y::Number) = dot(x, y)

julia> x = [quatrand() for _ in 1:2, _ in 1:2];

julia> y = [quatrand() for _ in 1:2, _ in 1:2];

julia> dot(x, y) ≈ mydot(x, y)  # fine
true

julia> dot(transpose(x), transpose(y)) ≈ mydot(transpose(x), transpose(y))   # fine
true

julia> dot(x', y') ≈ mydot(x', y')   # uh-oh
false

julia> method = @which dot(x', y')
dot(x::Adjoint, y::Adjoint) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:922

julia> Base.delete_method(method)

julia> dot(x', y') ≈ mydot(x', y')   # all good
true
```

This could be handled by restricting the types to `Union{Real,Complex}`, e.g.

```julia
 dot(x::Adjoint{Union{Real,Complex}}, y::Adjoint{Union{Real,Complex}}) = conj(dot(parent(x), parent(y))) 
```

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes JuliaLang/LinearAlgebra.jl#908

### CODE REVIEW

File: stdlib/LinearAlgebra/src/generic.jl [hunk 1]
```diff
@@ -886,7 +886,9 @@ function dot(x::AbstractArray, y::AbstractArray)
     s
 end
 
-dot(x::Adjoint, y::Adjoint) = conj(dot(parent(x), parent(y)))
+function dot(x::Adjoint{Union{Real,Complex}}, y::Adjoint{Union{Real,Complex}})
```
Comment (fredrikekre) [inline stdlib/LinearAlgebra/src/generic.jl:889]:
```suggestion
function dot(x::Adjoint{<:Union{Real,Complex}}, y::Adjoint{<:Union{Real,Complex}})
```

**Review by andreasnoack — APPROVED** [review]

**Comment by sethaxen** [comment]
Should this be backported to 1.6? It would be annoying to have to work around this bug until the next LTS.

File: stdlib/LinearAlgebra/src/generic.jl [hunk 2]
```diff
@@ -886,7 +886,9 @@ function dot(x::AbstractArray, y::AbstractArray)
     s
 end
 
-dot(x::Adjoint, y::Adjoint) = conj(dot(parent(x), parent(y)))
+function dot(x::Adjoint{<:Union{Real,Complex}}, y::Adjoint{<:Union{Real,Complex}})
+    return conj(dot(parent(x), parent(y)))
+end
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/generic.jl:891]: You could add another method for the generic `Number` case to extend the performance optimization to `Quaternion`s.
```suggestion
function dot(x::Adjoint{<:Union{Real,Complex}}, y::Adjoint{<:Union{Real,Complex}})
    return conj(dot(parent(x), parent(y)))
end
function dot(x::Adjoint{<:Number}, y::Adjoint{<:Number})
    return conj(dot(parent(y), parent(x)))
end
```

Comment (oscardssmith) [reply stdlib/LinearAlgebra/src/generic.jl:891]: Doesn't this definition work as the general fallback?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/generic.jl:891]: 🤦  Of course. I noticed that we need to restrict to `Numbers`, because for arrays of arrays the `conj`s seem to annihilate each other and the result becomes wrong.

Comment (sethaxen) [reply stdlib/LinearAlgebra/src/generic.jl:891]: This overload is also not correct:
```julia
julia> using LinearAlgebra, Quaternions

julia> function LinearAlgebra.dot(x::Adjoint{<:Number}, y::Adjoint{<:Number})
           return conj(dot(parent(y), parent(x)))
       end

julia> x = [quatrand() for _ in 1:2, _ in 1:2];

julia> y = [quatrand() for _ in 1:2, _ in 1:2];

julia> dot(Matrix(x'), Matrix(y'))
Quaternion{Float64}(11.624166294288848, 5.2859863153466815, -2.9677753842907677, -4.862662050905291, false)

julia> dot(x', y')
Quaternion{Float64}(11.624166294288848, 4.145847727927628, -2.535886196576731, -3.489570292291287, false)
```

This is because we want to compute
`⟨xᴴ, yᴴ⟩ = ∑ᵢ (xᵀ)ᵢ (yᵀ)ᵢ^* = ∑ᵢ xᵢ yᵢ^*`
But the overload is actually computing
`⟨y, x⟩^* = (∑ᵢ yᵢ^* xᵢ)^* = ∑ᵢ xᵢ^* yᵢ`

We could compute what we want to by conjugating both input arguments:
`⟨x^*, y^*⟩ = ∑ᵢ xᵢ yᵢ^*`
But then we end up allocating 2 arrays.

**Comment by KristofferC** [comment]
Does this really have to go into 1.6. The `dot(x::Adjoint, y::Adjoint)` was added in https://github.com/JuliaLang/julia/pull/39004 which is not in 1.6. Am I missing something?

**Comment by dkarrasch** [comment]
> Should this be backported to 1.6? It would be annoying to have to work around this bug until the next LTS.

We don't need to backport to v1.6. IIRC, then #39004 was just for performance, so there is no (should not be) bug in the LTS regarding `dot` of `Adjoint`s.
