### PR TITLE
trailing dimensions in eachslice

### LINKED ISSUE #51692: `eachslice(ones(3),dims=2)`
fails on Julia 1.09 and 1.10-beta3, but `eachcol(ones(3))` produces a  `ColumnSlices`. In fact, `test.arrayops.jl` has a test for the latter on line 2275. Also, `selectdim(ones(3),2,1) ` and `view(ones(3),:,1)` work.

This difference (inconsistency?) is inconvenient.

### PR DESCRIPTION
**Pull request by adienes**
fixes https://github.com/JuliaLang/julia/issues/51692

### CODE REVIEW

File: base/slicearray.jl [hunk 1]
```diff
@@ -40,33 +40,36 @@ unitaxis(::AbstractArray) = Base.OneTo(1)
 
 function Slices(A::P, slicemap::SM, ax::AX) where {P,SM,AX}
     N = length(ax)
-    argT = map((a,l) -> l === (:) ? Colon : eltype(a), axes(A), slicemap)
+    parent_axes = ntuple(d -> axes(A, d), length(slicemap))
```
Comment (mbauman) [inline base/slicearray.jl:45]: I think it'd probably be good to explicitly error if this new invariant (that `slicemap` must be at least `ndims(A)` long) is broken.  I know you're changing the only call-site (and the docs tell you not to use the constructor), but I'd rather get an error than a weird truncation or something.  And I think this should be statically known/removable:

```suggestion
    length(slicemap) >= ndims(A) || throw(AssertionError("the second argument to the Slices constructor must not have fewer elements than there are dimensions"))
    parent_axes = ntuple(d -> axes(A, d), length(slicemap))
```

Comment (adienes) [reply base/slicearray.jl:45]: of course I'm down to add such a check, but I don't yet understand how that would be a new problem after this PR (vs existing). on master, if `slicemap` is shorter than `ndims` than the `map` call will truncate to `length(slicemap)` already, right?

Comment (mbauman) [reply base/slicearray.jl:45]: Ah, you're right. That's great. I always forget that the 2-arg `map` doesn't demand/assert equal lengths.  I was worried this change might introduce a fun new failure mode but you're right this behaves exactly the same way.  So, yeah, take it or leave it :)

Comment (adienes) [reply base/slicearray.jl:45]: seems like a decent idea anyway, and master already infers `!n` (which this doesn't change)

**Review by mbauman — APPROVED** [review]

**Comment by adienes** [comment]
` @test_throws DimensionMismatch eachslice(M, dims = 4)`

I mean, yeah that test is a "real" failure (in that it should be removed)

but how on earth is it failing only on Apple?

**Comment by mbauman** [comment]
> but how on earth is it failing only on Apple?

The only ones that passed are the Linux network-only tests; there are other Linux workers that run the tests that fail.  I think they're subsetted like that due to network flakiness or disk size or some such.
