### PR TITLE
don't assume homogenous axes types in `dropdims`

### LINKED ISSUE #40462: Incorrect type assert triggers when calling `dropdims` with a StaticArray
Minimal example:

```julia
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

julia> using StaticArrays
julia> arr = @MMatrix rand(Int64,4,1)
4×1 MMatrix{4, 1, Int64, 4} with indices SOneTo(4)×SOneTo(1):
 -1142656121258989149
   636254653156898121
 -4641314833637010406
  -842100514524024656
julia> dropdims(arr, dims=2)
ERROR: TypeError: in typeassert, expected Tuple{SOneTo{1}}, got a value of type Tuple{SOneTo{4}}
Stacktrace:
 [1] _dropdims(A::MMatrix{4, 1, Int64, 4}, dims::Tuple{Int64})
   @ Base ./abstractarraymath.jl:85
 [2] _dropdims(A::MMatrix{4, 1, Int64, 4}, dim::Int64)
   @ Base ./abstractarraymath.jl:87
 [3] dropdims(A::MMatrix{4, 1, Int64, 4}; dims::Int64)
   @ Base ./abstractarraymath.jl:70
 [4] top-level scope
   @ REPL[3]:1
```

@jakobnissen on Slack:

> It looks to me like Base's function is wrong - please make an issue!
> Specifically, what happens is that the typeassert in reshape(A, d::typeof(_sub(axes(A), dims))) is not right - it picks up the wrong axes. It works by accident for Base arrays since all axes of Base arrays have the same type

### PR DESCRIPTION
**Pull request by adienes**
fixes https://github.com/JuliaLang/julia/issues/40462

test written by claude

### CODE REVIEW

File: base/abstractarraymath.jl [hunk 1]
```diff
@@ -88,12 +88,18 @@ function _dropdims(A::AbstractArray, dims::Dims)
             dims[j] == dims[i] && throw(ArgumentError("dropped dims must be unique"))
         end
     end
+    ox = axes(A)
     ax = _foldoneto((ds, d) -> d in dims ? ds : (ds..., axes(A,d)), (), Val(ndims(A)))
-    reshape(A, ax::typeof(_sub(axes(A), dims)))
+    if isconcretetype(eltype(typeof(ox)))
```
Comment (nsajko) [inline base/abstractarraymath.jl]: slightly simpler:

```suggestion
    if isconcretetype(eltype(ox))
```

Comment (adienes) [reply base/abstractarraymath.jl]: ty

File: base/abstractarraymath.jl [hunk 2]
```diff
@@ -88,12 +88,18 @@ function _dropdims(A::AbstractArray, dims::Dims)
             dims[j] == dims[i] && throw(ArgumentError("dropped dims must be unique"))
         end
     end
+    ox = axes(A)
     ax = _foldoneto((ds, d) -> d in dims ? ds : (ds..., axes(A,d)), (), Val(ndims(A)))
-    reshape(A, ax::typeof(_sub(axes(A), dims)))
+    if isconcretetype(eltype(ox))
+        # if all the axes are the same type, we can ue the tail as the
```
Comment (adienes) [inline base/abstractarraymath.jl]:
```suggestion
        # if all the axes are the same type, we can use the tail as the
```

**Comment by adienes** [comment]
bump

**Comment by adienes** [comment]
I waffled on a one-line diff more times than I'd like to admit, but here's what I'm currently thinking...

tl;dr
`dropdims` calls `reshape(A, remaining_dimensions)`, which gets turned into (`Int`) sizes via (paraphrased) `map(to_shape, remaining_dimensions)`

the original version of this PR put the else branch of `isconcretetype(eltype(ox))` as `reshape(A, map(length, ax))` and the current now does `reshape(A, ax)`. while the `map(length)` version does:

* return a correct answer
* make some cases "just work" even if they don't implement a `reshape`

I think it would complicate the ability to add specialization as arrays with heterogenous axis types would then have to specialize `dropdims` directly *as well as `reshape`* in order to participate in any fast paths, whereas if this is left as just `reshape(A, ax)`, then specializing `reshape` will imply `dropdims` specialization without further work.

since this PR is now very close to NFC, only removing a typeassert that existed for performance benefit (not semantics), I feel comfortable calling it mergeable

**Comment by nsajko** [comment]
Currently this PR introduces a branch and then only applies the `typeassert` on one side of the branch, where it was previously applied unconditionally. Would it make sense to just delete the `typeassert` unconditionally? Why was the `typeassert` introduced in the first place?

File: base/abstractarraymath.jl [hunk 3]
```diff
@@ -88,12 +88,18 @@ function _dropdims(A::AbstractArray, dims::Dims)
...
+    ox = axes(A)
     ax = _foldoneto((ds, d) -> d in dims ? ds : (ds..., axes(A,d)), (), Val(ndims(A)))
-    reshape(A, ax::typeof(_sub(axes(A), dims)))
+    if isconcretetype(eltype(ox))
+        # if all the axes are the same type, we can use the tail as the
+        # axes of the result rather than extracting one at each index
+        return reshape(A, ax::typeof(_sub(ox, dims)))
+    else
+        return reshape(A, ax)
+    end
```
Comment (nsajko) [inline base/abstractarraymath.jl:99]: I'd deduplicate this by moving the `reshape` call out of the branch (assuming the `typeassert` is necessary in the first place):

```suggestion
    if isconcretetype(eltype(ox))
        # if all the axes are the same type, we can use the tail as the
        # axes of the result rather than extracting one at each index
        ax = ax::typeof(_sub(ox, dims))
    end
    return reshape(A, ax)
```

Comment (adienes) [reply base/abstractarraymath.jl:99]: I actually do prefer to have the return values on the same indentation. I suppose we could golf one word by making it a `return if`, but I don't know if that's really worth the CI churn

**Comment by adienes** [comment]
it helps for performance sometimes apparently, so may as well keep it

```
julia> P = Base.PermutedDimsArray(rand(5,1,3,1), (2,4,1,3));

julia> @btime dropdims($P; dims=(1,2)); # with typeassert
  179.126 ns (5 allocations: 96 bytes)

julia> @btime dropdims($P; dims=(1,2)); # without
  204.671 ns (7 allocations: 224 bytes)
```
