### PR TITLE
bug grabbag

### LINKED ISSUE #17520: Typod @code_llvm can segfault
```jl
julia> @code_llvm (2.0, 3.0)
ERROR: UndefRefError: access to undefined reference
 in typeinf_ext(::LambdaInfo) at ./inference.jl:1546
 in _dump_function(::Function, ::Any, ::Bool, ::Bool, ::Bool, ::Bool) at ./reflection.jl:333
 in code_llvm at ./reflection.jl:350 [inlined] (repeats 2 times)
 in code_llvm(::Any, ::Any) at ./reflection.jl:352
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

julia> @code_llvm (2.0, 3.0)

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
emit_function at /home/kricarl/juliamaster/src/codegen.cpp:3983
```

### PR DESCRIPTION
**Pull request by vtjnash**
closing issues with the "bug" tag

github: fixes #17520

(travis build @ https://travis-ci.org/JuliaLang/julia/builds/146264046, in case it never posts status below)

### CODE REVIEW

File: base/REPL.jl [hunk 1]
```diff
@@ -37,31 +37,32 @@ abstract AbstractREPL
...
             else
-                ans = backend.ans
-                # note: value wrapped in a non-syntax value to avoid evaluating
-                # possibly-invalid syntax (issue #6763).
-                eval(Main, :(ans = $(getindex)($(Any[ans]), 1)))
                 backend.in_eval = true
                 value = eval(Main, ast)
                 backend.in_eval = false
-                backend.ans = value
+                # note: value wrapped in a closure to ensure it doesn't passing through expand
```
Comment (tkelman) [inline base/REPL.jl]: doesn't pass through

**Comment by JeffBezanson** [comment]
This leads to the following behavior:

```
julia> @code_typed 1+2
1-element Array{Any,1}:
 LambdaInfo for +(::Int64, ::Int64)
```

(the code is no longer shown). At least for the macro forms, maybe we should return the LambdaInfo when there is only one, instead of wrapping it in an array?

**Comment by vtjnash** [comment]
that sounds logical to me. since the arguments are leaftypes, it should always return 0 or 1 LambdaInfo (assuming we don't try to return ambiguous matches)
