### PR TITLE
More robust non-integer conversions for %d Printf specifier

### LINKED ISSUE #37552: `@printf` aborts with `InexactError`
I am using the current master of Julia. I see this error:

```Julia
julia> using Printf
julia> @printf("%d", 1.0e100)
ERROR: InexactError: Int64(1.0e100)
Stacktrace:
 [1] Int64
   @ ./float.jl:710 [inlined]
 [2] Integer
   @ ./boot.jl:771 [inlined]
 [3] plength
   @ ~/src/julia-master/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:678 [inlined]
 [4] computelen
   @ ~/src/julia-master/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:692 [inlined]
 [5] format(io::Base.TTY, f::Printf.Format{Base.CodeUnits{UInt8, String}, Tuple{Printf.Spec{Val{'d'}}}}, args::Float64)
   @ Printf ~/src/julia-master/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:718
 [6] top-level scope
   @ REPL[7]:1
```

I think that `@sprintf` should not abort with an error when outputting large values.

The problem is that the format `%d` expect an integer, but the argument `1.0e100` is too large to be converted to an integer when counting digits.

This works:
```Julia
julia> @printf("%d", big(1.0e100))
10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104
```

### PR DESCRIPTION
**Pull request by quinnj**
Fixes #37552. As pointed out by Jameson, the non-integer conversion code
for the `%d` specifier handling code wasn't super robust; I wasn't sure
how robust it really needed to be, since it seems a bit sketchy to me
for users to be relying on Printf conversion behavior of non-integers
with `%d` anyway; C even throws a really scary warning if you pass
non-integer for `%d`. But anyways, this isn't that much more machinery
and puts back support for printf formatting of `Rational` with `%d`
anyway. But a note to users, I'd strongly suggest doing your own
conversion, `trunc`, `round`, whatever yourself to ensure you fully
understand what's going on if you really need to use the `%d` with
non-integer arguments.

As for the issue reported, it's note quite as severe a use-case since
they're just trying to represent a _huge_ integer via `Float64`, which
seems decently reasonable.

### CODE REVIEW

File: stdlib/Printf/src/Printf.jl [hunk 1]
```diff
@@ -262,11 +262,17 @@ end
 end
 
 # integers
+toint(x) = x
+toint(x::Rational) = Integer(x)
```
Comment (fredrikekre) [inline stdlib/Printf/src/Printf.jl:266]: Doesn't this need `round` too?

Comment (quinnj) [reply stdlib/Printf/src/Printf.jl:266]: I was just matching old printf behavior here:
```julia
julia> @sprintf("%d", 3//2)
ERROR: InexactError: Integer(3//2)
Stacktrace:
 [1] Integer at ./rational.jl:109 [inlined]
 [2] decode_dec at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Printf/src/Printf.jl:855 [inlined]
 [3] decode_dec(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Rational{Int64}, ::String, ::Int64, ::Int64, ::Char, ::Array{UInt8,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Printf/src/Printf.jl:841
 [4] top-level scope at REPL[4]:1

julia> @sprintf("%d", 3//1)
"3"
```
But I could see the case that we should call `round` first

Comment (fredrikekre) [reply stdlib/Printf/src/Printf.jl:266]: Right, it just seemed like the direction we have taken is to integerify any number (admittedly a bit weird -- would be simpler to force the user to do it for `%d`). Perhaps the fallback should just be `round(Int, x)` instead of a no-op?

File: stdlib/Printf/src/Printf.jl [hunk 2]
```diff
@@ -262,11 +262,17 @@ end
...
+toint(x::AbstractFloat) = x > typemax(Int128) ?
+                            BigInt(round(x)) : x > typemax(Int64) ?
+                            Int128(round(x)) : Int64(round(x))
```
Comment (vtjnash) [inline stdlib/Printf/src/Printf.jl:269]: Making this so type-unstable seems bad for both the compiler and runtime performance, as well as making it more complex. What did we do before that this wasn't a problem?

Comment (quinnj) [reply stdlib/Printf/src/Printf.jl:269]: It looks like we just called the grisu equivalent of `Ryu.writefixed` with precision `0`. Let me play around and see if we can do that as well.

Comment (quinnj) [reply stdlib/Printf/src/Printf.jl:269]: Ok, much faster to do that approach: https://github.com/JuliaLang/julia/pull/37601
