### PR TITLE
fix #28159, better field reflection functions for NamedTuple

### LINKED ISSUE #28159: show() does not work for Array of NamedTuple
Hello, this happens in REPL on `julia 0.7.0-beta2`:

```julia
julia> A = [(a=1, b=2), (a=3,c=4)]
2-element Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}:
Error showing value of type Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}:
ERROR: BoundsError: attempt to access NamedTuple{names,Tuple{Int64,Int64}}
  at index [1]
Stacktrace:
 [1] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::NamedTuple{(:a, :b),Tuple{Int64,Int64}}) at ./namedtuple.jl:144
 [2] #sprint#335(::IOContext{REPL.Terminals.TTYTerminal}, ::Int64, ::Function, ::Function, ::NamedTuple{(:a, :b),Tuple{Int64,Int64}}) at ./strings/io.jl:99
 [3] #sprint at ./none:0 [inlined]
 [4] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::NamedTuple{(:a, :b),Tuple{Int64,Int64}}) at ./show.jl:1732
 [5] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::Int64, ::Int64, ::Int64) at ./arrayshow.jl:68
 [6] print_matrix(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./arrayshow.jl:186
 [7] print_matrix at ./arrayshow.jl:159 [inlined]
 [8] print_array at ./arrayshow.jl:308 [inlined]
 [9] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}) at ./arrayshow.jl:344
 [10] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:130
 [11] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:133
 [12] display(::Array{NamedTuple{names,Tuple{Int64,Int64}} where names,1}) at ./multimedia.jl:287
 [13] #invokelatest#1 at ./essentials.jl:660 [inlined]
 [14] invokelatest at ./essentials.jl:659 [inlined]
 [15] print_response(::REPL.Terminals.TTYTerminal, ::Any, ::Nothing, ::Bool, ::Bool, ::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:151
 [16] print_response(::REPL.LineEditREPL, ::Any, ::Nothing, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:137
 [17] (::getfield(REPL, Symbol("#do_respond#42")){Bool,getfield(REPL, Symbol("##52#61")){REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:706
 [18] (::getfield(REPL, Symbol("##57#66")))(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:969
 [19] #invokelatest#1 at ./essentials.jl:660 [inlined]
 [20] invokelatest at ./essentials.jl:659 [inlined]
 [21] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(REPL, Symbol("##57#66")),String})(::REPL.LineEdit.MIState, ::REPL.LineEditREPL) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1302
 [22] prompt!(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2311
 [23] run_interface(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2212
 [24] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:1026
 [25] run_repl(::REPL.LineEditREPL, ::getfield(Base, Symbol("##824#826"))) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:187
 [26] macro expansion at ./logging.jl:299 [inlined]
 [27] (::getfield(Base, Symbol("##823#825")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:347
 [28] #invokelatest#1 at ./essentials.jl:660 [inlined]
 [29] invokelatest at ./essentials.jl:659 [inlined]
 [30] macro expansion at ./logging.jl:296 [inlined]
 [31] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:335
 [32] exec_options(::Base.JLOptions) at ./client.jl:247
 [33] _start() at ./client.jl:427
```
I don't think, it is a huge bug, but still kind of important in every-day usage. Because this happens already at definition (after hitting `Enter`).

### PR DESCRIPTION
**Pull request by JeffBezanson**
This allows `typeinfo` to work when printing NamedTuples.

### CODE REVIEW

File: base/reflection.jl [hunk 1]
```diff
@@ -132,6 +143,9 @@ julia> fieldname(Rational, 2)
 ```
 """
 function fieldname(t::DataType, i::Integer)
+    if t.abstract
+        error("type does not have definite field names")
```
Comment (ararslan) [inline base/reflection.jl]: Perhaps use `throw(ArgumentError("..."))`?

Comment (JeffBezanson) [reply base/reflection.jl]: `fieldcount` uses `error` for a similar case. Meanwhile, this function also uses `ArgumentError` for what is arguably a `BoundsError`. I guess I can change it though.

Comment (ararslan) [reply base/reflection.jl]: Up to you, just figured I'd suggest it since typed errors can be handy and informative.

**Review by ararslan — APPROVED** [review]
