### PR TITLE
[JuliaLowering] Recognize `(tryfinally _ _ scope)` form

### LINKED ISSUE #79: `@testset` not working as of ScopedValue change
MWE:
```
using Test
using JuliaLowering

returns_true() = (println("test ran"); true)

macro testset2(tests)
    quote
        ts = Test.DefaultTestSet("foo")
        Test.@with_testset ts begin
            $(esc(tests))
        end
        Test.finish(ts)
    end
end

ts = @testset2 begin
    @test returns_true()
end

ts_jl = JuliaLowering.include_string(Main, """
@testset2 begin
    @test returns_true()
end
"""; expr_compat_mode=true)


@info ts.n_passed    # 1
@info ts_jl.n_passed # 0
```

(also works with normal `@testset`, though with a lot more IR)

### PR DESCRIPTION
**Pull request by mlechu**
Fix `@testset` https://github.com/JuliaLang/JuliaLowering.jl/issues/79; we just weren't handling the secret third arg to the tryfinally form.  This argument appears to be used exclusively by Base.ScopedValues.

### CODE REVIEW

File: JuliaLowering/src/linear_ir.jl [hunk 1]
```diff
@@ -472,27 +472,27 @@ end
...
+        args = SyntaxList(ctx)
+        push!(args, scope)
+        enter_scope_arg = compile_args(ctx, args)
+    end
     # Exception handler block prefix
     handler_token = ssavar(ctx, ex, "handler_token")
     emit(ctx, @ast ctx ex [K"="
         handler_token
-        [K"enter" catch_label]  # TODO: dynscope
+        [K"enter" catch_label enter_scope_arg...]
```
Comment (topolarity) [inline JuliaLowering/src/linear_ir.jl:495]:
```suggestion
        [K"enter" catch_label only(enter_scope_arg)]
```

IIUC there should be exactly one

File: JuliaLowering/test/macros.jl [hunk 2]
```diff
@@ -389,6 +389,18 @@ end
     """; expr_compat_mode=true)
     @test test_mod.SOME_ENUM <: Enum
     @test test_mod.X1 isa Enum
+
+    # @testset produces :tryfinally with secret third arg
+    @eval test_mod :(using Test)
+    @test JuliaLowering.include_string(test_mod, "@test true") isa Test.Pass
+    @testset let jltestset = JuliaLowering.include_string(test_mod, """
+    @testset begin
```
Comment (topolarity) [inline JuliaLowering/test/macros.jl:397]: It's annoying, but can you add an explicit `:tryfinally` test as well?

Feels a bit indirect to only have coverage via Test.jl

**Review by topolarity — APPROVED** [review]
Thanks! Nice find.

This was indeed introduced with the relatively new `Expr(:enter, ...)` scope support. Maybe a forward-port we were missing?

File: JuliaLowering/src/linear_ir.jl (hunk 1 above)
Comment (mlechu) [reply JuliaLowering/src/linear_ir.jl:495]: Zero or one; should already be guaranteed by the checking on the way in
