### PR TITLE
inlining: bail out unless `match.spec_types <: match.method.sig`

### LINKED ISSUE #52644: Wrong call of `DataType` method with `UnionAll` argument causes segfault
Currently on the latest Julia release: 1.10.0

I observed this difference with 1.9:
```julia
struct TupleHolder
    tuple::Type{<:Tuple}
end

do_thing(t::DataType) = println("DataType")
do_thing(t::UnionAll) = println("UnionAll")

call_thing(t::TupleHolder) = do_thing(t.tuple)

call_thing(TupleHolder(Tuple{}))
```

Outputs `"UnionAll"`, which is unexpected since `Tuple{} isa DataType`. In 1.9, it outputs `"DataType"`.

By changing `call_thing` to `call_thing(t::TupleHolder) = (println(@which do_thing(t.tuple)); do_thing(t.tuple))` we get:
```
do_thing(t::DataType) @ Main REPL[2]:1
UnionAll
```
Meaning that there is a discrepancy between `@which` and the method Julia chooses to call.
Adding `println(typeof(t))` to `do_thing(t::UnionAll)` outputs `DataType`, which makes me think this is definitly a bug.

Interestingly, removing the `::Type{<:Tuple}` from the `TupleHolder` declaration fixes the issue.

### PR DESCRIPTION
**Pull request by aviatesk**
As Jameson pointed out in the link below, while the union-split handles cases when there are uncovered matches, sometimes the expected condition `spec_types <: method.sig` that the union-split algorithm relies on isn't met in such cases, which caused issues like #52644. This commit fixes the problem by adding explicit checks for such cases. Note that this is based on #52092. The extra handling for single method match unmatched static parameters based on `only_method` that was removed in JuliaLang/#52092 has been ineffective and would otherwise cause problematic inlining on this PR. We'll likely need to come back to this later and figure out a safe and effective way to deal with such cases in the future when the handling for either case turns out to be necessary.

- closes #52644
- xref: <https://github.com/JuliaLang/julia/pull/53600#pullrequestreview-1917272781>

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/53720#issuecomment-1993839347) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/75f5a2b_vs_9ae7eab/report.md).

File: base/compiler/ssair/inlining.jl [hunk 1]
```diff
@@ -1355,16 +1356,18 @@ function compute_inlining_cases(@nospecialize(info::CallInfo), flag::UInt32, sig
...
+                    end
                 else
                     handled_all_cases = false
-                    revisit_idx = nothing
                 end
+            elseif !(match.spec_types <: match.method.sig) # the requirement for correct union-split
+                handled_all_cases = false
             else
                 handled_all_cases &= handle_any_const_result!(cases,
                     result, match, argtypes, info, flag, state; allow_abstract=true, allow_typevars=false)
```
Comment (vtjnash) [inline base/compiler/ssair/inlining.jl:1373]:
```suggestion
                    result, match, argtypes, info, flag, state; allow_abstract=handled_all_cases, allow_typevars=false)
```
This can only permit later abstract calls if we proved that all previous calls were disjoint from this. One conservative way to express that requirement is to only allow isdispatchtuple here.

Comment (aviatesk) [reply base/compiler/ssair/inlining.jl:1373]: Isn't this filtering enough for this?
https://github.com/JuliaLang/julia/blob/63e75e899997d41058ef70ca687b4e57732d72c3/base/compiler/ssair/inlining.jl#L1391-L1393

Comment (vtjnash) [reply base/compiler/ssair/inlining.jl:1373]: Additionally, if `nunion != 1`, then the list of matches cannot be assumed to be sorted, so we can only allow the abstract calls that we can prove are disjoint from the other union elements, since we do not attempt to merge-sort them to combine them (the merge sort might fail) but we simply concat the lists.
```suggestion
                    result, match, argtypes, info, flag, state; allow_abstract=handled_all_cases && nunion == 1, allow_typevars=false)
```

Comment (vtjnash) [reply base/compiler/ssair/inlining.jl:1373]: Ah, okay, I wasn't expecting we would over-estimate this then filter it later. That late filter is actually a bit more strict than necessary then, since it doesn't consider the ordering. But that does at least seem valid.

**Review by vtjnash — APPROVED** [review]
