### PR TITLE
fix map! undefined value exposure

### LINKED ISSUE #36235: `map!` resulting in undefined values
```julia
julia> VERSION
v"1.5.0-beta1.0"

julia> map!(+, [0,0,0], [1,2], [10,20,30], [100])
3-element Array{Int64,1}:
 111
  31
   0

julia> map!(+, [0,0,0], [1,2], [10,20,30], [100])
3-element Array{Int64,1}:
        111
 4616658790
          0
```

This also happened on `v1.4.1`

Pretty sure this commit removed the necessary bounds check: https://github.com/JuliaLang/julia/commit/f9645ff3938bf2bb00186564484c5a179a14fa5a

Probably, if `@boundscheck LinearIndices(dest) == idxs1 && all(x -> LinearIndices(x) == idxs1, As)` evaluates to false, then `BoundsError` should be thrown.

If I understand the intent correct, `map!(+, [0,0,0], [1,2], [10,20,30], [100])` is supposed to error because the trailing arguments don't match the `axes` of the second argument. Or at the very least because the last argument is smaller than the second argument.

### PR DESCRIPTION
**Pull request by adienes**
hopefully more targeted / less disruptive than #50647 , would (at least partially) fix #36235 

may need extra documentation explaining that with this implementation, `@inbounds map!(dest, As)`  will always iterate through the indices of `As[1]` regardless of the other sizes

tbh, the existing implementation is pretty fundamentally incorrect and does not match the behavior explicitly described in the docstring, so I think that this PR (or #50647 , or something else similar) should merge _regardless_ of benchmarks impact. however, I would appreciate if someone could trigger a benchmark run just so we can see the impact :)

### CODE REVIEW

**Comment by adienes** [comment]
pretty sure build failures are unrelated

**Comment by LilithHafner** [comment]
This looks like a simple typo:

https://github.com/JuliaLang/julia/blob/a17db2b138b0e042329d2a3fb2efd53c68e2563f/base/abstractarray.jl#L3466

That's not how `@boundscheck` works. That won't throw even if the indices don't line up. Would it work to simply fix that typo or would that be too strict because the typo has been present for so long?

**Comment by adienes** [comment]
typo aside, it's checking the wrong thing. that's checking that literally all the indices are equal.

`map` is supposed to stop when any of the constituent arguments are exhausted --- this should be honored even in the presence of `@inbounds` ! I only made it skip this check in the presence of `@inbounds` in the PR because I figured there would be complaints if the added indices intersection impacted performance


but for a correct implementation to match the docstring, I think `intersect(map(eachindex ∘ LinearIndices, As)...)` --- or something else to that effect _must_ be computed, `@inbounds` or no

this is one of those cases where Julia skipped directly to "make it fast" before "make it right" ☹️

File: base/abstractarray.jl [hunk 1]
```diff
@@ -3462,8 +3462,11 @@ function ith_all(i, as)
...
 
 function map_n!(f::F, dest::AbstractArray, As) where F
-    idxs1 = LinearIndices(As[1])
-    @boundscheck LinearIndices(dest) == idxs1 && all(x -> LinearIndices(x) == idxs1, As)
+    idxs1 = eachindex(LinearIndices(As[1]))
+    @boundscheck begin
+        idxs1 = intersect(map(eachindex ∘ LinearIndices, As)...)
+        checkbounds(dest, idxs1)
+    end
     for i = idxs1
```
Comment (LilithHafner) [inline base/abstractarray.jl:3470]:
```suggestion
    idxs = mapreduce(LinearIndices, intersect, As)
    checkbounds(dest, inds)
    for i = idxs
```

- I don't see why we need `eachindex` is here
- We should only include bounds-check elision if benchmarks reveal that it makes a difference. In this case, we would also need to add `@propagate_inbounds` to `map!` to make it take effect.
- I think that `mapreduce(LinearIndices, intersect, As)` is more elegant than `intersect(map(LinearIndices, As)...)`, unless there is some performance reason to use the latter.
- If always compute the intersection of indices then `inds` is a better name than `inds1`

File: test/abstractarray.jl [hunk 2]
```diff
@@ -910,6 +910,9 @@ include("generic_map_tests.jl")
 generic_map_tests(map, map!)
 @test_throws ArgumentError map!(-, [1])
 
+# Issue #30624
+@test map!(+, [0,0,0], [1,2], [10,20,30], [100]) == [111,0,0]
```
Comment (LilithHafner) [inline test/abstractarray.jl:914]: Would you also add a test for https://github.com/JuliaLang/julia/issues/36235#issuecomment-2503895662, please?

**Review by LilithHafner — COMMENTED** [review]
Thanks for addressing this significant issue. Much appreciated. A related issue that you might want to be aware of, but don't need to fix in this PR is #56696.

I agree that it is acceptable to take some performance regressions in exchange for fixing this bug. I have some refactoring suggestions to make it a bit simpler.

I'm planning to run benchmarks once we agree on an implementation, but if you want me to run them right away instead I'd be happy to do that.

File: base/abstractarray.jl (hunk 1 above)
Comment (LilithHafner) [reply base/abstractarray.jl:3470]: > the `eachindex` I added for the following reason

Good reason.

> I suppose we should decide if in the first place `@inbounds` should allow skipping the check and iterate through the indices of the first argument? 

`@inbounds` should never expose documented semantics that are otherwise not present. This is because you can't count on bounds checks being removed. For exmaple, Julia could be run with `-check-bound=yes` or the boundschecking might not be inlined into the callsite where `@inbounds` is present. In either case, the bounds checks will remain. Consequently I think the answer to that question is no: `@inbounds` should not change the semantics other than to skip bounds checks.

**Comment by adienes** [comment]
* added a bunch more tests
* removed all `@inbounds` until it's clear that these are needed for performance, we can re-add
* I would like to abdicate responsibility for fixing `OffsetArrays` interactions :)

File: test/abstractarray.jl [hunk 3]
```diff
@@ -910,6 +910,26 @@ include("generic_map_tests.jl")
 generic_map_tests(map, map!)
 @test_throws ArgumentError map!(-, [1])
 
+function test_30624()
```
Comment (LilithHafner) [inline test/abstractarray.jl:913]: Why not a testset?

**Review by LilithHafner — COMMENTED** [review]
Previously, `map!(+, ones(1), ones(2, 2))` and `map!(+, ones(1), ones(2, 2), ones(2, 2))` worked and this makes them throw (as the docstring indicates they should).

Performance is, at a glance, sometimes slightly better and sometimes slightly worse than it was on master. Correctness first, performance optimization second so I'm not too concerned.

I like that the implementation for `map_n!` is a bit simpler now and that it clearly aligns with the implementations of 1-arg and 2-arg map.

**Comment by LilithHafner** [comment]
> - I would like to abdicate responsibility for fixing `OffsetArrays` interactions :)

Unfortunately we have to deal with them before merging because otherwise existing, valid, code that uses OffsetArrays will break. For example,

```julia
julia> R = fill(0, -4:-1);

julia> B = OffsetArray(reshape(1:12, 4, 3), -5, 6);

julia> minimum!(R, B)
4-element OffsetArray(::Vector{Int64}, -4:-1) with eltype Int64 with indices -4:-1:
 1
 2
 3
 4
```

This is a test failure from CI which fails because the implementation of `minimum!` (which lives in Base) for arrays with unconventional indexing relies on a bug that this PR fixes:

```julia
julia> x = fill(0, 1:3);

julia> y = fill(1, 2:4);

julia> map!(identity, x, y)
3-element OffsetArray(::Vector{Int64}, 1:3) with eltype Int64 with indices 1:3:
 1
 1
 1
```

@nanosoldier `runtests()`

**Comment by adienes** [comment]
I guess we'll have to iterate through destination idxs separately?

```
function map!(f::F, dest::AbstractArray, A::AbstractArray, B::AbstractArray) where F
    inds = intersect(eachindex(LinearIndices(A)), eachindex(LinearIndices(B)))
    @boundscheck length(dest) >= length(inds)
    dest_idx = firstindex(dest)
    for i = inds
        dest[dest_idx] = f(A[i], B[i])
        dest_idx = nextind(dest, dest_idx)
    end
    return dest
end
```

I could be wrong but this seems more likely to hurt performance.

Would there be a meaningful difference here between iterating through `firstindex`, `nextindex` of `dest` directly vs through `LinearIndices(dest)` ?

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56673#issuecomment-2511734560) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/592d233_vs_4280731/report.html) is available.

**Comment by LilithHafner** [comment]
Oh, wow! Nanosoldier looks clean. Rerunning failures to be sure:

@nanosoldier `runtests(["ApproxLogFunction", "TestSetExtensions", "FunctionOperators", "RemoteFiles", "ChebyshevFiltering", "EinExprs", "Andes", "OpenTelemetryExporterPrometheus", "RegressionTables", "GLPK", "CDDLib", "OrdinaryDiffEqSSPRK", "MPIMeasurements", "ManifoldDiffEq", "OceanRobots", "DynamicMovementPrimitives", "ActiveInference", "Yunir", "ImmersedLayers", "FrequencySweep", "LowRankIntegrators", "NetworkJumpProcesses", "BoxCox"])`

**Comment by LilithHafner** [comment]
> I guess we'll have to iterate through destination idxs separately to fix the `OffsetArrays` issue?

Given how nice PkgEval is looking, another option would be to fix the `minimum!` implementation to not rely on the `map!` bug.

> Would there be a meaningful difference here between iterating through firstindex, nextindex of dest directly vs through LinearIndices(dest) ?

I doubt it, but hopefully that won't be necessary. If we can implement it in a way that isn't practically breaking, I'd love to make `map!` take offset indices into account (like `map`) rather than iterating separately.

**Comment by adienes** [comment]
I'm finding all the indirection in `reducedim.jl` pretty inscrutable 😓

but I guess the "real" issue is in `mapfirst!` ?
```
function mapfirst!(f::F, R::AbstractArray, A::AbstractArray{<:Any,N}) where {N, F}
    lsiz = check_reducedims(R, A)
    t = _firstreducedslice(axes(R), axes(A))
    map!(f, R, view(A, t...))
end
```

in your example, we have
```
julia> t
(IdOffsetRange(values=-4:-1, indices=-4:-1), 7:7)
```

so then
```
julia> LinearIndices(view(B, t...)) |> collect
4×1 Matrix{Int64}:
 1
 2
 3
 4
```

on `main`,  that final `map!` call will happily map indices `[1 2 3 4]` into `[-4, -3, -2, -1]` whereas this PR makes it (correctly?) throw a `BoundsError`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56673#issuecomment-2514674149) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/592d233_vs_4280731/report.html) is available.

**Comment by adienes** [comment]
actually, @mbauman 's tour de force #55318 with this PR rebased on top seems to solve the offset arrays case. so maybe the solution is rebase & wait to get more help on that one?

**Comment by adienes** [comment]
at the very least, this PR would swap "bad" bugs (segfaults, undefined behavior) for "regular" bugs (something throwing a `BoundsError` when it should not)

**Comment by adienes** [comment]
updates https://github.com/JuliaLang/julia/pull/30389

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56673#issuecomment-2809999224) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4ddaf5d_vs_caa97c9/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

6 packages crashed on the previous version too.

## ✖ Packages that failed

**23 packages failed only on the current version.**

 - Illegal method overwrites during precompilation: 1 packages
 - Package has test failures: 3 packages
 - Package tests unexpectedly errored: 1 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 17 packages

1536 packages failed on the previous version too.

## ✔ Packages that passed tests

**27 packages passed tests only on the current version.**

 - Other: 27 packages

5121 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**8 packages successfully loaded only on the current version.**

 - Other: 8 packages

2855 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

905 packages were skipped on the previous version too.



</details>

**Comment by adienes** [comment]
@nanosoldier `runtests(["Uncertain", "CopEnt", "GraphViz", "QuadraticKalman", "KalmanFilters", "RegressionTables", "DMRGenie", "SteadyStateDiffEq", "DrugInteractions", "BOSS", "UnitDiskMapping", "TestParticle", "NonconvexBayesian", "JumpProblemLibrary", "ProbabilisticEchoInversion", "Yunir", "PlantGeomTurtle", "ClimaCalibrate", "ReactionDiffusion", "SignalTablesInterface_WGLMakie", "BoxCox", "UnfoldDecode", "EarthSciData"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56673#issuecomment-2812945216) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4ddaf5d_vs_caa97c9/report.html) is available.

<details><summary>Report summary</summary>

## ✖ Packages that failed

**1 packages failed only on the current version.**

 - Test log exceeded the size limit: 1 packages

2 packages failed on the previous version too.

## ✔ Packages that passed tests

**1 packages passed tests only on the current version.**

 - Other: 1 packages

16 packages passed tests on the previous version too.

## ~ Packages that at least loaded

3 packages successfully loaded on the previous version too.



</details>

**Comment by adienes** [comment]
I think this is clean actually. the single remaining failure has `Warning: detected a stack overflow; program state may be corrupted, so further execution might be unreliable.` in the logs, so I don't think that test should be trusted anyway.

File: base/reducedim.jl [hunk 4]
```diff
@@ -238,7 +238,7 @@ copyfirst!(R::AbstractArray, A::AbstractArray) = mapfirst!(identity, R, A)
 function mapfirst!(f::F, R::AbstractArray, A::AbstractArray{<:Any,N}) where {N, F}
     lsiz = check_reducedims(R, A)
     t = _firstreducedslice(axes(R), axes(A))
-    map!(f, R, view(A, t...))
+    map!(f, view(R, firstindex(R):lastindex(R)), view(A, t...))
```
Comment (mbauman) [inline base/reducedim.jl:241]: Why did this need to change?

```suggestion
    map!(f, R, view(A, t...))
```

File: base/abstractarray.jl [hunk 5]
```diff
@@ -3400,10 +3400,11 @@ map(f, ::AbstractSet) = error("map is not defined on sets")
...
 function map!(f::F, dest::AbstractArray, A::AbstractArray, B::AbstractArray) where F
-    for (i, j, k) in zip(eachindex(dest), eachindex(A), eachindex(B))
-        @inbounds a, b = A[j], B[k]
-        val = f(a, b)
-        @inbounds dest[i] = val
+    IL = IndexLinear()
+    inds = intersect(eachindex(IL, A), eachindex(IL, B))
+    @boundscheck checkbounds(dest, inds)
+    for i = inds
+        dest[i] = f(A[i], B[i])
```
Comment (mbauman) [inline base/abstractarray.jl:3407]: Similarly:

```suggestion
    length(dest) < min(length(A), length(B)) && throw(ArgumentError("destination is smaller than the smallest mapped argument"))
    for (i, j, k) in zip(eachindex(dest), eachindex(A), eachindex(B))
        @inbounds a, b = A[j], B[k]
        val = f(a, b)
        @inbounds dest[i] = val
        dest[i] = f(A[i], B[i])
```

File: base/abstractarray.jl [hunk 6]
```diff
@@ -3417,12 +3418,10 @@ function ith_all(i, as)
...
-    idxs1 = LinearIndices(As[1])
-    @boundscheck LinearIndices(dest) == idxs1 && all(x -> LinearIndices(x) == idxs1, As)
-    for i = idxs1
-        @inbounds I = ith_all(i, As)
-        val = f(I...)
-        @inbounds dest[i] = val
+    inds = mapreduce(Fix1(eachindex, IndexLinear()), intersect, As)
+    @boundscheck checkbounds(dest, inds)
+    for i = inds
+        dest[i] = f(ith_all(i, As)...)
```
Comment (mbauman) [inline base/abstractarray.jl:3424]:
```suggestion
    length(dest) < minimum(length, As) && throw(ArgumentError("destination is smaller than the smallest mapped argument"))
    idxs1 = LinearIndices(As[1])
    if LinearIndices(dest) == idxs1 && all(x -> LinearIndices(x) == idxs1, As)
        for i in idxs1
            @inbounds as = ith_all(i, As)
            val = f(as...)
            @inbounds dest[i] = val
        end
    else
       for (i, Is...) in zip(eachindex(dest), map(eachindex, As)...)
           as = ntuple(j->getindex(As[j], Is[j]), length(As))
           val = f(as...)
           dest[i] = val
        end
```

**Review by mbauman — CHANGES_REQUESTED** [review]

**Comment by mbauman** [comment]
(It took me a bit to understand what was happening here... my incremental review snowballed and became much more than a small comment; my apologies for the harsh appearance.)

File: base/reducedim.jl (hunk 4 above)
Comment (adienes) [reply base/reducedim.jl:241]: otherwise it will cause `maximum!` and `minimum!` on `OffsetArrays` to fail via some interaction with `mapfirst!` since `view(R::OffsetArray, :)` has offset indices but `view(R::OffsetArray, firstindex(R):lastindex(R))` has 1-based indices.

**Comment by adienes** [comment]
no worries; feedback is good!

File: base/abstractarray.jl [hunk 7]
```diff
@@ -3355,9 +3355,9 @@ concatenate_setindex!(R, X::AbstractArray, I...) = (R[I...] = X)
 ## 1 argument
 
 function map!(f::F, dest::AbstractArray, A::AbstractArray) where F
-    for (i,j) in zip(eachindex(dest),eachindex(A))
-        val = f(@inbounds A[j])
-        @inbounds dest[i] = val
+    inds = LinearIndices(A)
+    for i = inds
+        dest[i] = f(A[i])
```
[the remark this answers is not in the document]
Comment (mbauman) [reply base/abstractarray.jl:3360]: Oh I see, sure.  But again, I'd just encode that as a precondition:

```
all(A->ndims(A)==ndims(dest), As) && assert(all(A->axes(A) == axes(dest)), As)
```

[the remark this answers is not in the document]
Comment (adienes) [reply base/abstractarray.jl:3360]: that seems super reasonable to me, but it's also more breaking. `map!` , unlike `map`, currently allows for forms like this
```
julia> x, y, z = rand(1, 12), rand(3,4), rand(2,6);

julia> map!(*, x, y, z);
```

so despite my protest in the previous comment, this PR currently only fixes the interaction with `OffsetArrays` and does not change the general case of multidimensional arrays --- maybe it should? lmk if that's not too disruptive a change

**Comment by mbauman** [comment]
Let's detangle all of this.  At the core, there are **three** intended behavior changes here, which is precisely how I got all tangled up in knots upon reviewing it.

* The 3+ arg version has a buggy no-op `@boundscheck`.  Let's change that to be the branch between the shared linear index (if we can) or the `zip`ped cartesian thing.  That's obviously a clear and necessary bugfix.
* None of the methods enforce `map!`'s documented requirement that `dest` be at least as large as the smallest array.  That could be added as a precondition to all three methods.
* None of the methods enforce `map`'s documented requirement that — if the arrays have the same dimensionality — they must also have the same axes.  This isn't documented for `map!`, but perhaps could and should be.

**Comment by adienes** [comment]
ok, I narrowed the scope. only `map_n!` is changed now with the implementation you suggested.

as you note, this would leave open the question of input validation when the docstring is violated, but at least it fixes the segfaults and uninitialized value exposure (which was my main goal)

**Review by mbauman — APPROVED** [review]
