### PR TITLE
Fix several issues with `Pkg.pin()`

### LINKED ISSUE #17176: `Pkg.pin` broken, test ineffective
Not sure if this is known, but I couldn't find any open issue about it:
`Pkg.pin` creates a pinned branch, but does not switch to it:

```
julia> Pkg.pin("Example", v"0.4.0")
INFO: Creating Example branch pinned.b1990792.tmp

julia> Pkg.installed("Example")
v"0.4.1"
```

Inside the `Example` directory, this is the situation:

```
~/.julia/v0.5/Example$ git status
Not currently on any branch.
nothing to commit, working directory clean

~/.julia/v0.5/Example$ git branch
* (no branch)
  master
  pinned.b1990792.tmp
```

Also, the part of the tests which should catch this bug is missing a `@test` macro, see [the last line of these three](https://github.com/JuliaLang/julia/blob/cfc10f07431f5c762d4531333864b245a038480d/test/pkg.jl#L185-L187), which is doing nothing with its return value.

This is on latest master, `0.5.0-dev+4990`. It works fine in 0.4.

cc @jakebolewski

### PR DESCRIPTION
**Pull request by carlobaldassi**
- Actually check out the branch after creation (fix #17176)
- Activate test in test/pkg.jl
- Avoid trying to update a pinned package (and emit info message)
- Allow to pin a package several times without producing errors
- Fix the cases in which `resolve()` is called after a `pin()`

~~More tests should be added. I'm working on it, but in the meanwhile~~ this could already be merged, if everything seems in order to people who actually know LibGit2 well.

cc @wildart

### CODE REVIEW

File: base/pkg/entry.jl [hunk 1]
```diff
@@ -295,18 +295,42 @@ function pin(pkg::AbstractString, head::AbstractString)
     should_resolve = true
     with(GitRepo, pkg) do repo
         id = if isempty(head) # get HEAD commit
-            LibGit2.head_oid(repo)
-        else
             # no need to resolve, branch will be from HEAD
             should_resolve = false
+            LibGit2.head_oid(repo)
```
Comment (tkelman) [inline base/pkg/entry.jl]: what was the logic error here?

File: test/pkg.jl [hunk 2]
```diff
@@ -184,7 +184,7 @@ temp_pkg_dir() do
 
         Pkg.pin("Example", v"0.4.0")
         @test Pkg.update() == nothing
-        Pkg.installed()["Example"] == v"0.4.0"
+        @test Pkg.installed()["Example"] == v"0.4.0"
```
Comment (tkelman) [inline test/pkg.jl]: is this alone sufficient to test what was broken, or should there be a few more?

File: base/pkg/entry.jl (hunk 1 above)
Comment (carlobaldassi) [inline base/pkg/entry.jl]: `resolve` was being called when keeping the head fixed and not called when changing it, rather than the other way around.

The behaviour after the fix is the following (notice the info messages which tell you whether `resolve` was invoked or not):

```
julia> Pkg.pin("Example") # stay on head, resolve not invoked 
INFO: Creating Example branch pinned.526e34fd.tmp

julia> Pkg.pin("Example", v"0.4.0") # resolve invoked
INFO: Creating Example branch pinned.b1990792.tmp
INFO: No packages to install, update or remove

julia> Pkg.pin("Example", v"0.4.0") # no changes, resolve not invoked
INFO: Package Example is already pinned to the selected commit

julia> Pkg.pin("Example", v"0.4.1") # change commit, resolve invoked
INFO: Package Example: checking out existing branch pinned.526e34fd.tmp
INFO: No packages to install, update or remove

julia> Pkg.pin("Example") # no changes, resolve not invoked
INFO: Package Example is already pinned

julia> Pkg.free("Example") # free always calls resolve (may be changed, but it's not in this PR)
INFO: Freeing Example
INFO: No packages to install, update or remove
```

**Comment by carlobaldassi** [comment]
Tests added. Should be ready to merge after review.

Note: I wrote an ugly macro in the test file in order to grab the package manager outputs and check them. Is there a better way to achieve that?

**Comment by tkelman** [comment]
> I wrote an ugly macro in the test file in order to grab the package manager outputs and check them

I think it might be doable without writing to a temp file, but I like what it achieves of making this test file less noisy - probably applicable for the rest of the file too. Maybe generically useful enough to put it somewhere more official later.

**Comment by carlobaldassi** [comment]
Yes, I also thought about applying it to the rest of the file. It's quite some work though, and can be left to another PR. Avoiding temp files would certainly be an improvement.
I will also certainly use this functionality in the tests for #17132.

**Comment by wildart** [comment]
LGTM

**Comment by carlobaldassi** [comment]
Thanks for the reviews!
