### PR TITLE
fix #40258: nested string interpolation

### LINKED ISSUE #40258: 1.6 bug: nested string interpolation is broken
Hello. :) I believe we have encountered a bug in the 1.6 release: nested string interpolation appears to be broken.

Consider this simple example:
```julia
julia> VERSION
v"1.6.0"

julia> v = "a $("b $("c")")"
"a b "

julia> length(v)
4
```

Where the inner nested string is dropped. Compare this with the prior release which produces the correct answer:
```julia
julia> VERSION
v"1.5.4"

julia> v = "a $("b $("c")")"
"a b c"

julia> length(v)
5
```

I am running on macOS:
```julia
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

------------------------------------

In case this is relevant, we came across this when a macro that includes string interpolation broke. As a very simple example, consider something like this:
```julia
macro pstring(str)
    @info str
    return quote
        println("str1:", $(str))
        println("str2: $($(str))")
    end
end
```
Interestingly, the `@macroexpand` is different between 1.5 and 1.6, but as far as I can tell, both are equally valid expansions, so I don't think anything is _wrong_ with the new expansion in 1.6. However, the 1.6 expansion creates nested string interpolation, which doesn't work in 1.6, even though it did work in 1.5:

```julia
julia> VERSION
v"1.6.0"

julia> @pstring "hello $("nathan")"
[ Info: "hello $("nathan")"
str1:hello nathan
str2: hello 

julia> @macroexpand @pstring "hello $("nathan")"
[ Info: "hello $("nathan")"
quote
    #= /Users/nathandaly/work/Delve/test/compilation_times/lib.jl:7 =#
    Main.println("str1:", "hello $("nathan")")
    #= /Users/nathandaly/work/Delve/test/compilation_times/lib.jl:8 =#
    Main.println("str2: $("hello $("nathan")")")
end
```
```julia
julia> VERSION
v"1.5.4"

julia> @pstring "hello $("nathan")"
[ Info: "hello nathan"
str1:hello nathan
str2: hello nathan

julia> @macroexpand @pstring "hello $("nathan")"
[ Info: "hello nathan"
quote
    #= /Users/nathandaly/work/Delve/test/compilation_times/lib.jl:7 =#
    Main.println("str1:", "hello nathan")
    #= /Users/nathandaly/work/Delve/test/compilation_times/lib.jl:8 =#
    Main.println("str2: $("hello nathan")")
end
```

### PR DESCRIPTION
**Pull request by simeonschaub**
fixes #40258

### CODE REVIEW

**Review by NHDaly — COMMENTED** [review]
Awesome, thank you for picking this up! :)

File: test/syntax.jl [hunk 1]
```diff
@@ -2751,3 +2751,8 @@ end
 @test eval(:(x = $(QuoteNode(Core.SlotNumber(1))))) == Core.SlotNumber(1)
 @test_throws ErrorException("syntax: SSAValue objects should not occur in an AST") eval(:(x = $(Core.SSAValue(1))))
 @test_throws ErrorException("syntax: Slot objects should not occur in an AST") eval(:(x = $(Core.SlotNumber(1))))
+
+# issue 40258
+@test "a $("b $("c")")" == "a b c"
+
+@test "$(([[:a, :b], [:c, :d]]...)...)" == "abcd"
```
Comment (NHDaly) [inline test/syntax.jl:2758]: It might be worth also testing that we still support both forms of the AST, in case anyone was manually constructing ASTs in the old form?:

```julia
julia> VERSION
v"1.5.4"

julia> eval(Expr(:string, "a", Expr(:string, "b", Expr(:string, "c"))))
"abc"

julia> eval(Expr(:string, "a", Expr(:string, "b", "c")))
"abc"
```

```julia
julia> VERSION
v"1.6.0"

julia> eval(Expr(:string, "a", Expr(:string, "b", Expr(:string, "c"))))
"ab"

julia> eval(Expr(:string, "a", Expr(:string, "b", "c")))
"ab"
```

Comment (NHDaly) [reply test/syntax.jl:2758]: So something like
```suggestion
@test "$(([[:a, :b], [:c, :d]]...)...)" == "abcd"

@test eval(Expr(:string, "a", Expr(:string, "b", "c"))) == "abc"
@test eval(Expr(:string, "a", Expr(:string, "b", Expr(:string, "c")))) == "abc"
```

**Review by NHDaly — COMMENTED** [review]
Awesome, thank you for picking this up! :)

File: test/syntax.jl (hunk 1 above)
Comment (simeonschaub) [reply test/syntax.jl:2758]: Thanks! Always good to have more test cases.

File: src/julia-syntax.scm [hunk 2]
```diff
@@ -2383,12 +2383,13 @@
 
    'string
    (lambda (e)
+     (define (expand-args s)
+       (if (and (pair? s) (eq? (car s) 'string))
+           (apply append (map expand-args (cdr s)))
+           (list s)))
      (expand-forms
-      `(call (top string) ,@(map (lambda (s)
-                                   (if (and (pair? s) (eq? (car s) 'string))
```
Comment (JeffBezanson) [inline src/julia-syntax.scm:2388]: I think we should instead change this to `(and (length= s 2) (eq? (car s) 'string) (string? (cadr s)))` to avoid too many changes to which `string` calls happen.

**Review by JeffBezanson — APPROVED** [review]
