### PR TITLE
Fix: lastindex for Numbers

### LINKED ISSUE #36311: 1[end, end] errors: no multiarg lastindex for Numbers
while silly, we should be constistent
```julia
julia> 1[1,1]
1

julia> 1[end]
1

julia> [1][end, end]
1

julia> 1[end, end]
ERROR: MethodError: no method matching lastindex(::Int64, ::Int64)
```

### PR DESCRIPTION
**Pull request by mgautam98**
Fixes: #36311 
Added a method to `lastindex` to handel 1[end,end] for consistency.
Also added similar function to `firstindex`

### CODE REVIEW

File: base/number.jl [hunk 1]
```diff
@@ -68,7 +68,9 @@ ndims(x::Number) = 0
 ndims(::Type{<:Number}) = 0
 length(x::Number) = 1
 firstindex(x::Number) = 1
+firstindex(x::Number, ::Int) = 1
```
Comment (simeonschaub) [inline base/number.jl:71]: Since `size` and `axes` do this check as well, this should probably be:
```suggestion
firstindex(x::Number, d::Int) = d < 1 ? throw(BoundsError()) : 1
```

File: base/number.jl [hunk 2]
```diff
@@ -68,7 +68,9 @@ ndims(x::Number) = 0
...
 lastindex(x::Number) = 1
+lastindex(x::Number, ::Int) = 1
```
Comment (simeonschaub) [inline base/number.jl:73]: Here as well.

Comment (mgautam98) [reply base/number.jl:73]: Okay

Comment (mgautam98) [reply base/number.jl:73]: I made the changes. When I was testing it was throwing `BoundsError` so I didn't thought of it

**Comment by simeonschaub** [comment]
This still needs tests, probably somewhere here: https://github.com/JuliaLang/julia/blob/6cdfcf9b48c0c4d4cd4022539ec7e5083df9e8e3/test/numbers.jl#L2403

**Comment by mgautam98** [comment]
@simeonschaub Okay I will include test

**Review by simeonschaub — APPROVED** [review]
If you want, you could also include @oxinabox's `1[end, end]
` example in the tests, but it's not that important.

**Review by mbauman — APPROVED** [review]
Thanks!

**Review by oxinabox — APPROVED** [review]

**Comment by mgautam98** [comment]
@mbauman will it me merged?

**Comment by mbauman** [comment]
Yes, closing and re-opening is a little trick to easily re-run CI.  A website we hit to test HTTP connectivity went down, which meant that all the tests here failed.  I'm quite certain that this will pass tests, but it's better to confidently merge with 18 ✅s from CI.
