### PR TITLE
Mark ccall to git_libgit2_opts as variadic

### LINKED ISSUE #38638: [PPC] double free or corruption in libgit
```
      From worker 81:   *** Error in `/nobackup/users/vchuravy/builds/julia-nodbg/usr/bin/julia': double free or corruption (out): 0x00002000ad470070 ***
      From worker 81:
      From worker 81:   signal (11): Segmentation fault
      From worker 81:   in expression starting at /nobackup/users/vchuravy/builds/julia-nodbg/usr/share/julia/stdlib/v1.6/LibGit2/test/libgit2.jl:210
      From worker 81:   backtrace at /lib64/libc.so.6 (unknown line)
      From worker 81:   __libc_message at /lib64/libc.so.6 (unknown line)
      From worker 81:   cfree at /lib64/libc.so.6 (unknown line)
      From worker 81:   stdalloc__free at /nobackup/users/vchuravy/builds/julia-nodbg/usr/bin/../lib/libgit2.so (unknown line)
      From worker 81:   git_buf_dispose at /nobackup/users/vchuravy/builds/julia-nodbg/usr/bin/../lib/libgit2.so (unknown line)
      From worker 81:   git_buf_free at /nobackup/users/vchuravy/builds/julia-nodbg/usr/bin/../lib/libgit2.so (unknown line)
      From worker 81:   free at /nobackup/users/vchuravy/builds/julia-nodbg/usr/share/julia/stdlib/v1.6/LibGit2/src/types.jl:129 [inlined]
      From worker 81:   get_global_dir at /nobackup/users/vchuravy/builds/julia-nodbg/usr/share/julia/stdlib/v1.6/LibGit2/test/libgit2.jl:131
      From worker 81:   #12 at /nobackup/users/vchuravy/builds/julia-nodbg/usr/share/julia/stdlib/v1.6/LibGit2/test/libgit2.jl:144
      From worker 81:   #mktempdir#21 at ./file.jl:729
      From worker 81:   mktempdir at ./file.jl:727 [inlined]
      From worker 81:   mktempdir at ./file.jl:727 [inlined]
      From worker 81:   with_libgit2_temp_home at /nobackup/users/vchuravy/builds/julia-nodbg/usr/share/julia/stdlib/v1.6/LibGit2/test/libgit2.jl:143
      From worker 81:   unknown function (ip: 0x2000194a382f)
      From worker 81:   _jl_invoke at /nobackup/users/vchuravy/dev/julia/src/gf.c:2228 [inlined]
      From worker 81:   jl_apply_generic at /nobackup/users/vchuravy/dev/julia/src/gf.c:2410
      From worker 81:   Allocations: 14914739 (Pool: 14910064; Big: 4675); GC: 19
```

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #38638, as usual PPC is sensitive to variadic functions. Correctly done in `LibGit2.set_ssl_cert_locations`.

### CODE REVIEW

File: stdlib/LibGit2/test/libgit2.jl [hunk 1]
```diff
@@ -125,7 +125,7 @@ end
 function get_global_dir()
     buf = Ref(LibGit2.Buffer())
     LibGit2.@check ccall((:git_libgit2_opts, :libgit2), Cint,
-                         (Cint, Cint, Ptr{LibGit2.Buffer}),
```
Comment (Keno) [inline stdlib/LibGit2/test/libgit2.jl:128]: This signature is `git_libgit2_opts(int option, ...);`, which doesn't quite match this. It may not make a difference here, but it would be better to be consistent.

Comment (vchuravy) [reply stdlib/LibGit2/test/libgit2.jl:128]: Yeah..., the general `...` is hard to express using `ccall`. Especially since we want to have the types to do argument conversion. I suspect that the correct signature is `(Cint, Clong...)` and then manually do the conversion to `Ptr{LibGit2.Buffer}` + reinterpret to `Clong`.  

Any better ideas? For PPC it's only important that the callsite is marked `va`.

**Comment by vtjnash** [comment]
`@ccall` supports more features (including varargs) that `ccall` doesn't support
