### PR TITLE
Nospecialize close(c::Channel, excp::Exception) on excp.

### LINKED ISSUE #49507: stackoverflow in type inference caused by handling a StackOverflow exception
We saw this rather comical exception pop up in our production cloud deployment:
```julia
Internal error: stack overflow in type inference of close(Base.Channel{Bool}, StackOverflowError).
```
As described above, this comes from a place in our code that performs a generic operation like this:
```julia
function http_handler()
    result = Channel()
    do_stuff()
    return_result_or_report_error(result)
end

# ... much later, after much processing on the server  ...
function do_stuff_inner_function(result_channel)
    try
        put!(result_channel, user_func())
    catch e
        close(result_channel, e)
    end
end
```
In this case, the try block happened to execute when the stack was _very nearly full,_ so the `user_func()` threw a `StackOverflowException`. This is perfectly fine -- the code is set up to handle exceptions, and so the result should now contain the StackOverflowException, which, once everything unwinds, could be reported at the top level http handler.

However, what actually happens is the `close(::Channel, ::StackOverflowExeption)` triggers type inference, which causes _another_ stack overflow! 😅 

------

Looking at that function, i'm pretty sure that it the exception argument should be marked `@nospecialize`, since the generated code is going to be identical no matter what: `c.excp` is type `Union{Exception, Nothing}`, and all the other functions it calls with `excp` are already `@nospecialize`:

https://github.com/JuliaLang/julia/blob/2d14390077d422b642ce80fe1404f0b6d6392332/base/channels.jl#L186-L198

### PR DESCRIPTION
**Pull request by NHDaly**
Fixes https://github.com/JuliaLang/julia/issues/49507.

~Avoids dynamic dispatch when closing a Channel with an Exception, and~ should avoid a call into the runtime for julia compilation when attempting to report an exception.

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

File: base/channels.jl [hunk 1]
```diff
@@ -183,7 +183,7 @@ Close a channel. An exception (optionally given by `excp`), is thrown by:
 * [`put!`](@ref) on a closed channel.
 * [`take!`](@ref) and [`fetch`](@ref) on an empty, closed channel.
 """
-function close(c::Channel, excp::Exception=closed_exception())
+function close(c::Channel, @nospecialize(excp::Exception=closed_exception()))
```
Comment (NHDaly) [inline base/channels.jl:186]: > ~Avoids dynamic dispatch when closing a Channel with an Exception~

Oh, jk i forgot that `Channel` is also a parametric type, so this will still have a dispatch to do.

... is there any reason to specialize on the Channel type? None of the Channel fields accessed in this function depend on the type of the parameter.. Would julia be able to tell that, and still be able to produce concrete code for a type without its type parameter if none of the accessed fields depend on the parameter? My guess is the answer is **no**, but it would be a neat feature.

@vchuravy or @pchintalapudi you are probably the best people I could get to answer that question - do you know?

Comment (NHDaly) [reply base/channels.jl:186]: @quinnj and @vtjnash: Without the above, i guess this will still trigger compilation, due to the dispatch on the Channel type.

Can I mark that as nospecialize too?

Comment (vtjnash) [reply base/channels.jl:186]: You may incur internal dispatch (for lock and unlock), but it can potentially still figure out memory layout and dispatch specializations

Comment (vtjnash) [reply base/channels.jl:186]: It looks like inference should know the type of Channel. Only the exception argument is type Any

Comment (NHDaly) [reply base/channels.jl:186]: > You may incur internal dispatch (for lock and unlock), but it can potentially still figure out memory layout and dispatch specializations

Oh right. Good points..

.... Is there any reason I can't mark these as `@nospecialize(c::Channel)` as well???:
https://github.com/JuliaLang/julia/blob/36ace5430d5b54ec3f7045b980002fe2f600e508/base/channels.jl#L525-L528

Comment (NHDaly) [reply base/channels.jl:186]: ...assuming that julia can still produce good code since `cond_take` doesn't depend on `{T}`?

Comment (NHDaly) [reply base/channels.jl:186]: ...I'm finding that I can't rely on Cthulhu to answer this question, since it seems to disregard the `@nospecialize`, and shows me a function that's been inferred specifically for the type i'm calling with, even though codegen will ultimately produce a single generic native function, right?

> It looks like inference should know the type of Channel. Only the exception argument is type Any

@vtjnash: I'm not sure what you meant by this message. Can you expand on it? How does it apply to the situation where I mark both arguments nospecialize in close?

Comment (NHDaly) [reply base/channels.jl:186]: Ohhhhhh you're saying I don't _need_ to mark it nospecialize in order to avoid a dispatch, since inference already knows the channel type, so i could still avoid the dispatch even if the exception type is unknown! 💡 great point. So it could still be an invoke, or even inlined 👍 

Neat!

Oh, so then maybe Cthulhu was right after all, because it was devirtualizing my call!  Aha, yes that was it. Neat!! :)
Julia is pretty cool you guys.

So then: the only fear would be that if this is the **first exception** we've ever called `close()` on for this channel type, we might still stackoverflow. But if we've done it for some other exceptions first, we'll be okay.
... that's probably still an improvement, and so we can probably do without marking it `@nospecialize`. (Unless we think it would still produce good code even in that case.)

Comment (NHDaly) [reply base/channels.jl:186]: Wow, incredible! Maybe it actually _can_ produce good code, even if the Channel is nospecialize!
```julia
julia> struct Foo{T}
           a::Int
           b::T
       end

julia> function foo(@nospecialize(x::Foo))
           bar(x.a)
       end
foo (generic function with 1 method)

julia> bar(v) = v + 1
bar (generic function with 1 method)

julia> function run(v::Vector{Any})
           return foo(v[1])
       end
run (generic function with 1 method)

julia> using Cthulhu

julia> @descend run(Any[Foo(1, "hi")])
run(v::Vector{Any}) in Main at REPL[4]:1
1 function run(v::Vector{Any}::Vector{Any})::Int64
2     return foo(v::Vector{Any}[1]::Any)::Int64
3 end
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
Toggles: [w]arn, [h]ide type-stable statements, [t]ype annotations, [s]yntax highlight for Source/LLVM/Native.
Show: [S]ource code, [A]ST, [T]yped code, [L]LVM IR, [N]ative code
Actions: [E]dit source code, [R]evise and redisplay
   2 v::Vector{Any}[1]
 • 2 foo(v::Vector{Any}[1]::Any)
   ↩
foo(x::Foo) in Main at REPL[2]:1
1 function foo(@nospecialize(x::Foo::Foo))::Int64
2     bar(x::Foo.a::Int64)::Int64
3 end
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
Toggles: [w]arn, [h]ide type-stable statements, [t]ype annotations, [s]yntax highlight for Source/LLVM/Native.
Show: [S]ource code, [A]ST, [T]yped code, [L]LVM IR, [N]ative code
Actions: [E]dit source code, [R]evise and redisplay
   2 x::Foo.a
 • 2 bar(x::Foo.a::Int64)
   ↩
bar(v) in Main at REPL[3]:1
1 bar(v::Int64)::Int64 = v::Int64 + 1
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
Toggles: [w]arn, [h]ide type-stable statements, [t]ype annotations, [s]yntax highlight for Source/LLVM/Native.
Show: [S]ource code, [A]ST, [T]yped code, [L]LVM IR, [N]ative code
Actions: [E]dit source code, [R]evise and redisplay
   1  v::Int64 + 1
 • ↩

julia>
```

Thanks Cthulhu: you're an amazing tool. (And thanks @vchuravy ❤️)

So I'm down to nospeicalize everything! Thoughts? I'll send up a commit like that too.

Comment (NHDaly) [reply base/channels.jl:186]: K, i put that into a separate PR, here, since I kind of went crazy and added a bunch of them everywhere it seemed to not depend on `T`:
https://github.com/JuliaLang/julia/pull/49509

I'll merge this one now, since we're happy with it, and we can discuss what to do next on https://github.com/JuliaLang/julia/pull/49509.

Comment (NHDaly) [reply base/channels.jl]: > So then: the only fear would be that if this is the **first exception** we've ever called `close()` on for this channel type, we might still stackoverflow. But if we've done it for some other exceptions first, we'll be okay.

Oh, even this isn't a concern, since when it's devirtualized, it'll be inferred during its caller's inference! Wow, julia is pretty rad. 😎

**Comment by NHDaly** [comment]
BTW, yep, this does indeed resolve the issue by preventing dispatch+compilation when reporting the error, since it could already be compiled when compiling its caller.

Here's evidence: the reproducer from the original issue now succeeds:
```julia
julia> ch = let result = Channel()

       foo() = try
           foo()
       catch e;
           close(result, e)
       end

       foo()

       result
       end
Channel{Any}(0) (closed)

julia> take!(ch)
ERROR: StackOverflowError:
Stacktrace:
 [1] check_channel_state
   @ ./channels.jl:174 [inlined]
 [2] take_unbuffered(c::Channel{Any})
   @ Base ./channels.jl:472
 [3] take!(c::Channel{Any})
   @ Base ./channels.jl:451
 [4] top-level scope
   @ REPL[2]:1
```

**Comment by NHDaly** [comment]
Since this is a bug-fix, could it be a backport candidate?

File: test/channels.jl [hunk 2]
```diff
@@ -626,3 +626,20 @@ end
         @test n_avail(c) == 0
     end
 end
+
+# Issue #49507: stackoverflow in type inference caused by close(::Channel, ::Exception)
+@testset "close(::Channel, ::StackOverflowError)" begin
```
Comment (vtjnash) [inline test/channels.jl:631]: I forgot I meant to say this should go into the `stack_overflow.jl` file, since the handling of this error is quite bad and sometimes ends up breaking the process (as I found out today trying to debug something completely unrelated). Do you mind making a PR to move it?

Comment (NHDaly) [reply test/channels.jl:631]: Oh, interesting. Yeah, i'm happy to move it! 👍 PR incoming

Comment (NHDaly) [reply test/channels.jl:631]: PR here: https://github.com/JuliaLang/julia/pull/49702
