### PR TITLE
Fix a few cases of REPL completion crash

### LINKED ISSUE #19310: REPL tab completion exception
Under Windows opening a new terminal and writing `"C` and then pressing *tab* key raises an exception:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> "CWARNING: Caught an exception in the keymap:
ERROR: stat: operation not permitted (EPERM)
ERROR: syntax: incomplete: invalid string syntax

julia> pwd()
"D:\\"

julia>
```

This happens only if current directory is drive root, e.g. `C:\\`, `D:\\`. It might be related to #8693.

### LINKED ISSUE #32797: keymap error in stat
```Julia
julia> stat("C:\\S<tab>
┌ Error: Error in the keymap
│   exception =
│    IOError: stat: permission denied (EACCES) for file "C:\\\\System Volume Information"
│    Stacktrace:
│     [1] stat(::String) at .\stat.jl:69
│     [2] isdir at .\stat.jl:311 [inlined]
│     [3] completions(::String, ::Int64, ::Module) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\REPLCompletions.jl:597
│     [4] completions(::String, ::Int64) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\REPLCompletions.jl:575
│     [5] complete_line(::REPL.REPLCompletionProvider, ::Any) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:362
│     [6] complete_line(::REPL.LineEdit.PromptState, ::Any) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:324
│     [7] complete_line(::REPL.LineEdit.MIState) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:315
│     [8] edit_tab(::REPL.LineEdit.MIState, ::Any, ::Any) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:1987 (repeats 2 times)
│     [9] (::getfield(REPL.LineEdit, Symbol("##108#160")))(::Any, ::Any, ::Vararg{Any,N} where N) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:2028
│     [10] #invokelatest#1 at .\essentials.jl:708 [inlined]
│     [11] invokelatest at .\essentials.jl:707 [inlined]
│     [12] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(REPL.LineEdit, Symbol("##108#160")),String})(::Any, ::Any) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:1356
│     [13] prompt!(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:2398
│     [14] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:2301
│     [15] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:1039
│     [16] run_repl(::REPL.AbstractREPL, ::Any) at C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:201
│     [17] (::getfield(Base, Symbol("##767#769")){Bool,Bool,Bool,Bool})(::Module) at .\client.jl:390
│     [18] #invokelatest#1 at .\essentials.jl:708 [inlined]
│     [19] invokelatest at .\essentials.jl:707 [inlined]
│     [20] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:374
│     [21] exec_options(::Base.JLOptions) at .\client.jl:312
│     [22] _start() at .\client.jl:468
└ @ REPL.LineEdit C:\cygwin64\home\jameson\julia\julia-win64\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:2400
```

### LINKED ISSUE #36855: REPLCompletions crash on isdir
```julia
julia> symlink("foo", "foo")

julia> "f<tab>
┌ Error: Error in the keymap
│   exception =
│    IOError: stat: too many symbolic links encountered (ELOOP) for file "foo"
```

### PR DESCRIPTION
**Pull request by Liozou**
Fix #36855, fix #32797 and close #19310. Those three were the same bug, fixed by adding a `try`-`catch` block around an `isdir` call (lines 626-631).

Also complete #40621 (in a separate commit) to avoid having an `Error in the keymap` for
```julia
julia> macro mymacro(arg, whatever...)
           arg
       end;

julia> @mymacro.#TAB
```
PR #40621 only fixed the case brought up by issue #27184 where `mymacro` was non-existent, but the underlying issue is that `Meta.@lower @mymacro` throws an error if `@mymacro` is not a valid macro call, which can be either because the macro does not exist, or because it requires at least one argument.
The fix consists in putting the `Meta.lower` call in a `try`-`catch` block as well.

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -749,8 +757,9 @@ function completions(string::String, pos::Int, context_module::Module=Main)
 
         if inc_tag === :string &&
            length(paths) == 1 &&  # Only close if there's a single choice,
-           !isdir(expanduser(replace(string[startpos:prevind(string, first(r))] * paths[1].path,
-                                     r"\\ " => " "))) &&  # except if it's a directory
+           try !isdir(expanduser(replace(string[startpos:prevind(string, first(r))] * paths[1].path,
```
Comment (KristofferC) [inline stdlib/REPL/src/REPLCompletions.jl:760]: Maybe this should be pulled out in a function (perhaps local to the function). It's starting to become hard to read.

Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl:760]: Sure, the accumulation of things is a bit too much indeed

Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: Moved to the new `close_path_completion` function

**Comment by Liozou** [comment]
Actually #19310 might have been solved already, I just added a few tests

**Comment by Liozou** [comment]
Looks like the current fix leads to some unwanted completions, I'll look into that.

**Comment by Liozou** [comment]
And CI is now green! Please let me know if there is anything else to be done.

File: stdlib/REPL/src/REPLCompletions.jl [hunk 2]
```diff
@@ -466,11 +466,19 @@ function get_type(sym::Expr, fn::Module)
...
-    if isexpr(sym, :macrocall)
+    newsym = if isexpr(sym, :macrocall)
         _, found = get_type(first(sym.args), fn)
         found || return Any, false
+        try
+            Meta.lower(fn, sym)
+        catch e
+            e isa LoadError && e.error isa MethodError && return Any, false
+            rethrow()
+        end
```
Comment (aviatesk) [inline stdlib/REPL/src/REPLCompletions.jl:477]:
```suggestion
        try
            Meta.lower(fn, sym)
        catch # macro expansion can throw an arbitrary error, just ignore it
            return Any, false
        end
```

Would be also nice if you add test cases that demonstrate it:
```julia
# @unsafemacro.[TAB]
macro unsafemacro()
    throw(ArgumentError("zero argument"))
end
# @unsafemacro("foo").[TAB]
macro unsafemacro(a)
    if isa(a, Number)
        return a
    end
    throw(ArgumentError(a))
end
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 3]
```diff
@@ -611,6 +619,21 @@ function afterusing(string::String, startpos::Int)
     return occursin(r"^\b(using|import)\s*((\w+[.])*\w+\s*,\s*)*$", str[fr:end])
 end
 
+function close_path_completion(string, startpos, r, paths, pos)
+    length(paths) == 1 || return false  # Only close if there's a single choice...
+    _path = string[startpos:prevind(string, first(r))] * paths[1].path
```
Comment (aviatesk) [inline stdlib/REPL/src/REPLCompletions.jl:624]:
```suggestion
    _path = string[startpos:prevind(string, first(r))] * (paths[1]::PathCompletion).path
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 4]
```diff
@@ -611,6 +619,21 @@ function afterusing(string::String, startpos::Int)
     return occursin(r"^\b(using|import)\s*((\w+[.])*\w+\s*,\s*)*$", str[fr:end])
 end
 
+function close_path_completion(string, startpos, r, paths, pos)
```
Comment (aviatesk) [inline stdlib/REPL/src/REPLCompletions.jl:622]: `string` is a bit confusing since there is `Base.string` global function. Maybe better to rename it to `s`?

File: stdlib/REPL/src/REPLCompletions.jl (hunk 2 above)
Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl:477]: Thank you for the thorough review, I'll amend the PR accordingly! However, may I suggest to keep the `e isa LoadError` condition (barring the `&& e.error isa MethodError` part), since this `try`-`catch` block is only supposed to catch lowering errors, be they caused by invalid macro calls or macro calls expanding into errors.
I think any other error should leak because they are not supposed to happen, so they should be reported. But please let me know if I am misunderstanding something.

File: stdlib/REPL/src/REPLCompletions.jl (hunk 4 above)
Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: I incorporated the two last review comments in the last commit, thanks!

File: stdlib/REPL/src/REPLCompletions.jl (hunk 2 above)
Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: You can see the fixed commit here: https://github.com/JuliaLang/julia/pull/43541/commits/6d9ae078efaa654b56692c02b67feaf284eefdbd

Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl]: My view is that REPL completion is just one application, and it should be implemented "safely". For example, Pluto and Juno use this module for its code completion feature, but they assume this module never throws.
So from this point of view, REPL completion ideally shouldn't involve any kind of actual code execution and potential side effect (including macroexansion, dictionary indexing, etc.). Nevertheless we're doing some of such "dangerous" operations in REPL completions since they can provide useful information, but potential errors from such inspections should be caught since it is not users but us (REPL completion implementers) who execute user code here.

Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl]: Ops, I think I missed your point. Yeah, it sounds reasonable to keep the `LoadError` condition.

Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: Yes, whatever code the user may write, I agree that REPL completion should definitely not crash on it. But if I understand correctly, `Meta.lower` always wraps whatever error may be caused by macro expansion in a `LoadError`, so if another kind of error is thrown, then something wrong is happening with julia itself, independently of the user's code. And as such, it would be best if it was reported, even if REPL completion may not be the best place to do so.
But I won't object further if you still feel like REPL completion is not the place for this, I can see your point as well so please let me know!

Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: Ah, it seems we crossed answers :)

Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl]: yep, sorry for the confusion :P
It would be appreciated if you could leave some comment here so that why we want to have this `rethrow` here.

**Review by aviatesk — APPROVED** [review]

File: stdlib/REPL/src/REPLCompletions.jl (hunk 2 above)
Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: Comment added, see https://github.com/JuliaLang/julia/pull/43541/commits/af9f78abe94fbdd1b48fe20934dd484284b66e97
