### PR TITLE
Fix conversion in getindex

### LINKED ISSUE #26608: Improving indexing operations of ranges of bit integers
Currently, computations in `getindex(::UnitRange, ::Integer)` can overflow during the bounds check. If so, it throws an InexactError; not a BoundsError. Compare:

```julia
> (-100:100)[400] # ok
ERROR: BoundsError: attempt to access 201-element UnitRange{Int64} at index [400]
> (Int8(-100):Int8(100))[400] # :(
ERROR: InexactError: trunc(Int8, 299)
> (-100:100)[typemax(UInt)] # :(
ERROR: InexactError: check_top_bit(UInt64, 18446744073709551514)
```

I think I have fixed this for all bit integer types (both the range type and index type) with this hack:

```julia
using Base: BitInteger

function getindex(r::UnitRange{Tr}, i::Integer) where {Tr<:BitInteger}
    @_inline_meta
    # if i ≥ 1 we can safely do i - 1 without ending up at typemax(i)
    # if r.start ≤ r.stop we could compute r.stop - r.start, but this number may not be representable in signed integers, so switch to unsigned integers with a hack.
    @boundscheck i ≥ 1 && r.start ≤ r.stop && i - 1 ≤ unsigned(r.stop) - unsigned(r.start) || throw_boundserror(r, i)

    return (r.start + (i - 1)) % Tr
end
```

But I'm not 100% sure this is the way to go and if I'm covering everything. At least it fixes the problems listed above:

```julia
> (Int8(-100):Int8(100))[400]
ERROR: BoundsError: attempt to access 201-element UnitRange{Int8} at index [400]
> (-100:100)[typemax(UInt)]
ERROR: BoundsError: attempt to access 201-element UnitRange{Int64} at index [18446744073709551615]
```

### PR DESCRIPTION
**Pull request by haampie**
Fixes #26608 (all edge cases of it) and improves performance for the `@inbounds` case a lot.

Note that using `@inbounds` will now return garbage results when going out of bounds, whereas it previously would throw a conversion error. Should be fine.

### CODE REVIEW

**Comment by haampie** [comment]
Right, didn't think about ranges of rationals.

File: base/range.jl [hunk 1]
```diff
@@ -473,11 +473,23 @@ end
...
-    ret
+    val = convert(T, v.start + i - 1)
+    @boundscheck _in_unit_range(v, val, i) || throw_boundserror(v, i)
+    val
+end
+
+const OverflowSafe = Union{Bool,Int8,Int16,Int32,Int64,Int128,
+                           UInt8,UInt16,UInt32,UInt64,UInt128}
+
+function getindex(v::UnitRange{T}, i::Integer) where {T<:OverflowSafe}
```
Comment (mbauman) [inline base/range.jl]: You could just use `Union{Bool, Base.BitInteger}` for this.

File: base/range.jl [hunk 2]
```diff
@@ -473,11 +473,23 @@ end
 
 ## indexing
 
+_in_unit_range(v::UnitRange, val, i::Integer) = i > 0 && val <= v.stop && val >= v.start
```
Comment (mbauman) [inline base/range.jl]: Ah, yes, I totally believe that this is faster — bounds checks are very friendly to branch prediction and when they miss, well, we really don't care about performance anymore.

**Comment by mbauman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

I'm not sure if we have any tests that index into `UnitRange`s without bounds checks, but I'm curious.  If Nanosoldier fails this isn't terribly crucial.  Maybe you could share your spot-perf checks?

File: base/range.jl (hunk 1 above)
Comment (haampie) [reply base/range.jl]: Yeah, I was trying that, but it turns out `BitInteger` is defined a couple includes away in `int.jl`, and when I tried moving the constants to a separate file `int_types.jl`, I broke stuff without very useful feedback from `make`. It's worth defining these types a bit earlier, because other places redefine them as well!

**Comment by haampie** [comment]
Same tricks with `value % T` and changing `&` -> `&&` makes indexing of `StepRange` and `Base.OneTo` faster as well :). So I'll expand and tidy this PR a bit.

Fixing #26623 would make bounds checking for ranges slower unfortunately.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26615#issuecomment-400017914) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1d285935bc36c6b0abd1609d436a930015294691/9a44594_vs_d7bf89f/report.md). cc @ararslan

**Comment by haampie** [comment]
I think yes
