### PR TITLE
Test if selfmem can write to RX page

### LINKED ISSUE #22082: Julia hangs on launch when using Linux kernel v4.12-rc1
Julia simply hangs on launch when using Linux kernel v4.12-rc1 (on Ubuntu 17.04). There is no stdout or stderr output and Ctrl-C does not work. Workaround is just to go back to v4.11.

Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

### PR DESCRIPTION
**Pull request by yuyichao**
Also open only one `/proc/self/mem`.
There are apparently two instances of `RTDyldMemoryManagerJL` created.

Fix #22082 

@Keno for testing.

### CODE REVIEW

**Comment by yuyichao** [comment]
Added backport label. Not sure how cleanly this can be backported to 0.5.

**Review by Keno — APPROVED** [review]

**Comment by yuyichao** [comment]
A local cherry-pick attempt shows no conflict so this should be backportable to 0.5.

File: src/cgmemmgr.cpp [hunk 1]
```diff
@@ -264,9 +264,9 @@ static void *alloc_shared_page(size_t size, size_t *id, bool exec)
 #ifdef _OS_LINUX_
 // Using `/proc/self/mem`, A.K.A. Keno's remote memory manager.
 
-static int self_mem_fd = -1;
-
-static int init_self_mem()
+// Do not call this direction.
```
Comment (alyst) [inline src/cgmemmgr.cpp]: directly

**Comment by yuyichao** [comment]
I take the approve as tested on 4.12-rc* kernel?

**Comment by Keno** [comment]
yes
