### PR TITLE
Fix printing of InetAddr

### LINKED ISSUE #29402: show(::InetAddr) prints port in hex
```julia
julia> Sockets.InetAddr(ip"127.0.0.1", 8080)
Sockets.InetAddr{IPv4}(ip"127.0.0.1", 0x1f90)
```

should be

```julia
julia> Sockets.InetAddr(ip"127.0.0.1", 8080)
Sockets.InetAddr{IPv4}(ip"127.0.0.1", 8080)
```

### PR DESCRIPTION
**Pull request by adamslc**
Port should be printed in decimal.

Closes #29402.

### CODE REVIEW

File: stdlib/Sockets/src/IPAddr.jl [hunk 1]
```diff
@@ -251,3 +251,6 @@ struct InetAddr{T<:IPAddr}
 end
 
 InetAddr(ip::IPAddr, port) = InetAddr{typeof(ip)}(ip, port)
+function show(io::IO, addr::InetAddr{T}) where T
+    print(io, "InetAddr{", T, "}(", addr.host, ", ", Int(addr.port), ")")
+end
```
Comment (JeffBezanson) [inline stdlib/Sockets/src/IPAddr.jl]: This would be better:
```
function show(io::IO, addr::InetAddr)
    show(io, typeof(addr))
    print(io, "(")
    show(io, addr.host)
    print(io, ", ", Int(addr.port), ")")
end
```
We don't want to re-implement how types are printed, and `addr.host` should probably be printed with `show`.

File: stdlib/Sockets/test/runtests.jl [hunk 2]
```diff
@@ -64,6 +64,9 @@ end
     inet = Sockets.InetAddr(IPv4(127,0,0,1), 1024)
     @test inet.host == ip"127.0.0.1"
     @test inet.port == 1024
+    io = IOBuffer()
+    show(io, inet)
+    @test String(take!(io)) == "Sockets.InetAddr{IPv4}(ip\"127.0.0.1\", 1024)"
```
Comment (JeffBezanson) [inline stdlib/Sockets/test/runtests.jl]:
```suggestion
    @test String(take!(io)) == "Sockets.InetAddr{Sockets.IPv4}(ip\"127.0.0.1\", 1024)"
```

**Review by JeffBezanson — APPROVED** [review]
