### PR TITLE
typeintersect: convert union of tuples to tuple of unions

### LINKED ISSUE #26827: Inference failure for known static parameters matched with unknown type
Reduced from a test failure in FFTW.jl:
```julia
julia> struct Foo{inplace,N}; end

julia> Foo{inplace,N}(X::StridedArray{Float32,N},Y) where {inplace,N} = Foo{inplace,N}()

julia> code_warntype(Foo{false,1}, Tuple{Any,Any})
Variables:
  X<optimized out>
  Y<optimized out>

Body:
  begin
      Core.SSAValue(0) = (Core.apply_type)(Main.Foo, $(Expr(:static_parameter, 1)), $(Expr(:static_parameter, 2)))::Type{Foo{_1,_2}} where _2 where _1
      Core.SSAValue(1) = (Core.SSAValue(0))()::Foo{_1,_2} where _2 where _1
      return Core.SSAValue(1)
  end::Foo{_1,_2} where _2 where _1
```
Compare with 0.6:
```julia
Variables:
  #self# <optimized out>
  X <optimized out>
  Y <optimized out>

Body:
  begin 
      return $(QuoteNode(Foo{false,1}()))
  end::Foo{false,1}
```
Remarks:
* Works if the type of `X` is known.
* Works if using a simpler type instead of `StridedArray`, e.g. `AbstractArray{Float32,N}`.
* Second parameter `Y` is irrelevant, but avoids cluttering the output from the `convert`/constructor deprecation method.
* Also fails without the `inplace` parameter, but I find it particularly puzzling that it is also affected.

### PR DESCRIPTION
**Pull request by martinholters**
On master, if type intersection gives a `Union`, it is simply replaced by the second argument in a post-processing step. This is because some code, handling the method tables, cannot deal with `Union`s. This PR drastically reduces the number of cases where this is happening: First, it only prevents a `Union` from being returned if the inputs are `Tuple`s (or `UnionAll`s of `Tuple`s), i.e. could be method signatures. Second, it tries to do a "point-wise" `Union` of the `Tuple` parameters, i.e. `Union{Tuple{A,B},Tuple{C,D}}` is transformed to `Tuple{Union{A,C},{B,D}}`. Note that the latter is wider than the former, but I'm not sure such a case can actually happen when intersecting two `Tuple`s, and anyway, it shouldn't be worse than just returning the second argument to `typeintersect`.

This also uncovered three ambiguities which where previously hidden by wrong intersection results. I hope I've chosen the correct resolution for them.

Fixes #26827.

### CODE REVIEW

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
Server issue, had to restart. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27573#issuecomment-397504188) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4088a677a856def1486b1b59825f379351b3f71a/389953d_vs_5ba7f20/report.md). cc @ararslan

**Comment by martinholters** [comment]
@JeffBezanson, does this look good to you?

File: test/subtype.jl [hunk 1]
```diff
@@ -1307,3 +1307,10 @@ f26453(x::T,y::T) where {S,T>:S} = 0
 g26453(x::T,y::T) where {S,T>:S} = T
 @test_throws UndefVarError(:T) g26453(1,1)
 @test issub_strict((Tuple{T,T} where T), (Tuple{T,T} where {S,T>:S}))
+
+# issue #26827
+@testintersect(Union{Int8,Int16,Int32}, Union{Int8,Int16,Int64}, Union{Int8, Int16})
```
Comment (JeffBezanson) [inline test/subtype.jl]: This test would have passed before; `@testintersect` uses the internal, more accurate function. Should also test `typeintersect` directly.

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
Probably introduced a gc-root or gc-wb bug? https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.27871/job/y5x7f5ce00i0di95#L2513

File: src/subtype.c [hunk 2]
```diff
@@ -2213,6 +2213,66 @@ jl_svec_t *jl_outer_unionall_vars(jl_value_t *u)
...
+        return ans;
+    }
+    if (!jl_is_tuple_type(a) || !jl_is_tuple_type(b)) {
+        return NULL;
+    }
+    if (jl_nparams(a) != jl_nparams(b) || jl_is_va_tuple((jl_datatype_t *)a) ||
+        jl_is_va_tuple((jl_datatype_t *) b)) {
+        return NULL;
+    }
+    jl_svec_t *vec = jl_alloc_svec_uninit(jl_nparams(a));
```
Comment (vtjnash) [inline src/subtype.c]: It's not permissible to call `JL_GC_PUSH1` on an uninit svec. This must use the `jl_alloc_svec` constructor to avoid gc-corruption

**Comment by martinholters** [comment]
Sorry!
