### PR TITLE
CHOLMOD cleanup

### LINKED ISSUE #568: cholesky on SparseMatrix{Float64, Int32} stackoverflows
```jl
julia> using SparseArrays, LinearAlgebra

julia> a = sparse(rand(10,10));

julia> aa = convert(SparseMatrixCSC{Float64, Int32}, a);

julia> cholesky(aa)
ERROR: StackOverflowError:
Stacktrace:
 [1] copy at ./array.jl:299 [inlined]
 [2] copy at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsematrix.jl:271 [inlined]
 [3] Type at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsematrix.jl:361 [inlined]
 [4] Type at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsematrix.jl:360 [inlined]
 [5] SuiteSparse.CHOLMOD.Sparse(::SparseMatrixCSC{Float64,Int32}, ::Int64) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:973 (repeats 52399 times)
 [6] SuiteSparse.CHOLMOD.Sparse(::SparseMatrixCSC{Float64,Int32}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:924
 [7] #cholesky#9(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::SparseMatrixCSC{Float64,Int32}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:1465
 [8] cholesky(::SparseMatrixCSC{Float64,Int32}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:1465
 [9] top-level scope at none:0
```

### LINKED ISSUE #29367: cholesky on SparseMatrix{Float64, Int32} stackoverflows
```jl
julia> using SparseArrays, LinearAlgebra

julia> a = sparse(rand(10,10));

julia> aa = convert(SparseMatrixCSC{Float64, Int32}, a);

julia> cholesky(aa)
ERROR: StackOverflowError:
Stacktrace:
 [1] copy at ./array.jl:299 [inlined]
 [2] copy at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsematrix.jl:271 [inlined]
 [3] Type at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsematrix.jl:361 [inlined]
 [4] Type at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsematrix.jl:360 [inlined]
 [5] SuiteSparse.CHOLMOD.Sparse(::SparseMatrixCSC{Float64,Int32}, ::Int64) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:973 (repeats 52399 times)
 [6] SuiteSparse.CHOLMOD.Sparse(::SparseMatrixCSC{Float64,Int32}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:924
 [7] #cholesky#9(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::SparseMatrixCSC{Float64,Int32}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:1465
 [8] cholesky(::SparseMatrixCSC{Float64,Int32}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/SuiteSparse/src/cholmod.jl:1465
 [9] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes JuliaLang/LinearAlgebra.jl#568, and cleans up by removing a lot of unneeded code.

### CODE REVIEW

**Comment by KristofferC** [comment]
I wonder if throwing instead of silently converting is better here. If someone used Int32 it is likely intentional and to save space and to silently blow it up to an Int64 seems unlikely what was intended.

**Comment by simonbyrne** [comment]
Not sure. We do silently convert values from `Float32` to `Float64`.

**Comment by ViralBShah** [comment]
@KristofferC My counterargument to your point is that 32-bit Ints going to 64-bit Ints is basically about 33% more memory usage as a fraction of the data structure and most sparse direct solvers have fill in that is significantly larger and will dwarf concerns with memory blow up here.

So perhaps merge this PR, and revisit the issue of whether we should do silent conversion or not in a separate issue/PR, and also document this.

**Comment by KristofferC** [comment]
Throwing an error would leave future choices open while implicitly converting means we are stuck with it, but I don't feel that strongly about it. Also, the question is what to do for `choleksy!`. Does this just fail for `Int32` or do you make a converted copy and then copy back to the original matrix. This seems to kinda break the `!` "contract".

And it is not just 33% more memory usage, it is ~133% more memory use because (AFAIU) we creating a fully converted copy of the sparse matrix.

Anyway, just some opinions, no need to spend too much attention to them :)

**Comment by andreasnoack** [comment]
We face this tradeoff all the time. When you can afford it and don't care about full control, automatic conversion is often convenient but if you run out of memory or try to avoid promotions then it can be a pain. Hence, you can find arguments that favor one or the other case depending on your focus. It can be considered a decision between being friendly to casual programmers versus friendly to expert programmers.

**Comment by KristofferC** [comment]
> It can be considered a decision between being friendly to casual programmers versus friendly to expert programmers.

In this case, someone explicitly asked for an Int32 sparse matrix though, which arguably already excludes the casual programming crowd.

**Comment by andreasnoack** [comment]
Although it might happen frequently, I think users will encounter sparse `Int32` matrices occasionally that they haven't explicitly constructed. This could happen when interacting with external libraries or when loading data from a binary format. I think I've seen such examples a couple of times when people have asked why this didn't work with the sparse solvers.

**Comment by oscardssmith** [comment]
If we convert to 64bit now, would it be breaking to later switch to using the 32 bit provided?

**Comment by simonbyrne** [comment]
I guess so? Though I don't imagine that will happen any time soon.

**Comment by oscardssmith** [comment]
Sure, but at that point why not just make it work if we can optimize later?

**Comment by simonbyrne** [comment]
I'm not sure I understand: what are you suggesting should be done?

**Comment by oscardssmith** [comment]
convert for now, later make cholmod work for int/float32

**Comment by simonbyrne** [comment]
Well, it would give technically different behaviour, since it would give different return types, e.g.
```julia
julia> using SparseArrays, LinearAlgebra

julia> x = sprand(Float32, 10,10,0.2); a = I + x'*x;

julia> C = cholesky(a);

julia> C \ ones(Float32,10) |> typeof
Array{Float64,1}
```

**Comment by ViralBShah** [comment]
I think it would be ok if the return type changed in the future.

**Comment by StefanKarpinski** [comment]
> I think it would be ok if the return type changed in the future.

That's definitely a breaking change. If we can show that there's reason to believe it will not break people's code and it doesn't actually break any package code in practice, perhaps, but that's a fairly high bar for changing a return type.

**Comment by simonbyrne** [comment]
Okay, this seems to be working now. Test for  #29367 here: https://github.com/JuliaLang/julia/pull/29462/files#diff-29b17f2b5404b9c57ecc798f9c78aad2R645

**Comment by KristofferC** [comment]
I think keeping things conservative first is better, adding a conversion can always be done, removing one is much more involved.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 1]
```diff
@@ -1,5 +1,13 @@
 # This file is a part of Julia. License is MIT: https://julialang.org/license
 
+# Theoretically CHOLMOD supports both Int32 and Int64 indices on 64-bit.
```
Comment (andreasnoack) [inline stdlib/SuiteSparse/src/cholmod.jl]: Why delete the comment? These limitations can sometimes to tricky to realize (at least it took me a while) so having them mentioned here might save future developers a bit of frustration.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 2]
```diff
@@ -228,116 +246,98 @@ struct C_Sparse{Tv<:VTypes} <: SuiteSparseStruct
...
 Base.unsafe_convert(::Type{Ptr{Tv}}, A::Sparse{Tv}) where {Tv} = getfield(A, :ptr)
 
 # Factor
+# Cvoid is used for pattern-only factors
+struct C_Factor{Tv<:VTypes} <: SuiteSparseStruct
+    n::Csize_t
+    minor::Csize_t
+    Perm::Ptr{SuiteSparse_long}
+    ColCount::Ptr{SuiteSparse_long}
+    @static if build_version >= v"2.1.0"
```
Comment (andreasnoack) [inline stdlib/SuiteSparse/src/cholmod.jl]: Nice. I didn't realize you could do this.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 3]
```diff
@@ -397,56 +397,51 @@ Factor(FC::FactorComponent) = Factor(FC.F)
...
 end
 
-free_dense!(p::Ptr{C_Dense{T}}) where {T} = ccall((:cholmod_l_free_dense, :libcholmod),
-    Cint, (Ref{Ptr{C_Dense{T}}}, Ptr{Cvoid}), p, common_struct)
-
-function zeros(m::Integer, n::Integer, ::Type{T}) where T<:VTypes
-    Dense(ccall((:cholmod_l_zeros, :libcholmod), Ptr{C_Dense{T}},
-        (Csize_t, Csize_t, Cint, Ptr{UInt8}),
-         m, n, xtyp(T), common_struct))
+function free!(p::Ptr{C_Dense{Tv}}) where {Tv<:VTypes}
```
Comment (andreasnoack) [inline stdlib/SuiteSparse/src/cholmod.jl]: The idea was to use the CHOLMOD name of the function for the wrappers to make it easy to use map between the C API and the wrappers. Then alongside to have a "julia API" based on the wrapper functions. Not necessarily saying that is the better way to do it, but just wanted to mention the motivation.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 4]
```diff
@@ -397,56 +397,51 @@ Factor(FC::FactorComponent) = Factor(FC.F)
...
+                m, n, xtyp(Tv), common_struct))
 end
 eye(m::Integer, n::Integer) = eye(m, n, Float64)
 eye(n::Integer) = eye(n, n, Float64)
 
-function copy_dense(A::Dense{Tv}) where Tv<:VTypes
-    Dense(ccall((:cholmod_l_copy_dense, :libcholmod), Ptr{C_Dense{Tv}},
-        (Ptr{C_Dense{Tv}}, Ptr{UInt8}),
-         A, common_struct))
+function copy(A::Dense{Tv}) where Tv<:VTypes
```
Comment (andreasnoack) [inline stdlib/SuiteSparse/src/cholmod.jl]: Same here

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 5]
```diff
@@ -460,157 +455,132 @@ function norm_dense(D::Dense{Tv}, p::Integer) where Tv<:VTypes
...
-end
-
-function change_factor!(::Type{Complex{Float64}}, to_ll::Bool,
-        to_super::Bool, to_packed::Bool, to_monotonic::Bool, F::Factor{Tv}) where Tv<:VTypes
-    @isok ccall((@cholmod_name("change_factor", SuiteSparse_long),:libcholmod), Cint,
-            (Cint, Cint, Cint, Cint, Cint, Ptr{C_Factor{Tv}}, Ptr{UInt8}),
-                COMPLEX, to_ll, to_super, to_packed, to_monotonic, F, common_struct)
-    # don't register finalizer since we reuse object
-    Factor{Complex{Float64}}(pointer(F), false)
+                xtyp(Tv), to_ll, to_super, to_packed, to_monotonic, F, common_struct)
```
Comment (andreasnoack) [inline stdlib/SuiteSparse/src/cholmod.jl]: Is it on purpose that you don't return the `Factor` anymore?

**Review by andreasnoack — COMMENTED** [review]
Nice cleanup. I've a few minor comments inline.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 1 above)
Comment (simonbyrne) [reply stdlib/SuiteSparse/src/cholmod.jl]: Delete what comment? I've added these.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 2 above)
Comment (simonbyrne) [reply stdlib/SuiteSparse/src/cholmod.jl]: yeah, we do the same thing in LibGit2

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 3 above)
Comment (simonbyrne) [reply stdlib/SuiteSparse/src/cholmod.jl]: ah, fair enough. This just simplified a bit of later code, but we can change it back if you would prefer.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 5 above)
Comment (simonbyrne) [reply stdlib/SuiteSparse/src/cholmod.jl]: Yes. (1) The return value wasn't used in any code, and (2) if it was used it was likely to cause a segfault, since there was nothing to stop the original object from being GC'ed.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 1 above)
Comment (andreasnoack) [reply stdlib/SuiteSparse/src/cholmod.jl]: Ha, sorry. That makes more sense. Then I think this is a very good addition to the source.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 3 above)
Comment (simonbyrne) [reply stdlib/SuiteSparse/src/cholmod.jl]: Keep it as it is in the PR? or as it is in the current code? (I don't mind either way)

**Comment by simonbyrne** [comment]
Just so it's clear, there are actually two decisions:
1) whether we should convert `Int32` indices to `Int64`. Currently
 - `lu` promotes.
 - `cholesky`/`ldlt` stack overflow (#29367).
 - `factorize` promotes only if the matrix is _not_ symmetric (fails with a `MethodError` on `bunchkaufman!` otherwise, which is only defined for dense matrices)).
2) whether we should convert `Float32` (or other) values to `Float64`. Currently
 - `lu` promotes to `Float64`
 - `cholesky`/`ldlt` promotes to `Float64`
 - `factorize` promotes only if the matrix is _not_ symmetric (otherwise fails as above).

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 3 above)
Comment (andreasnoack) [reply stdlib/SuiteSparse/src/cholmod.jl]: As it is in the PR.

**Comment by StefanKarpinski** [comment]
I think this should just print a very clear message explaining the situation and telling people to either:
1. Convert their indices to `Int64` manually; or
2. Complain to the CHOLMOD maintainers that their shit is broken; or
3. Both.

**Comment by JeffBezanson** [comment]
I think the first priority is for each function to have the desired type behavior, i.e. they all preserve both element type and index type. That's slightly breaking in the case of `lu` since it currently returns a widened result. In each case, we can either give an error (hoping to add an efficient implementation at some point), or slowly convert for cholmod and convert back to give the right result. I don't have a strong opinion on which of those we should do.

**Comment by ViralBShah** [comment]
I believe that if we can't support all the int/float types, it should be the Int32/Float64 combination. There really is no reason to have Int64 indices and waste memory and time for square matrices.

**Comment by simonbyrne** [comment]
From the top of my changes to cholmod.jl:

> Theoretically CHOLMOD supports both Int32 and Int64 indices on 64-bit.
> However experience suggests that using both in the same session causes memory
> leaks, so we restrict indices to be SuiteSparse_long (see cholmod_h.jl).
> Ref: https://github.com/JuliaLang/julia/issues/12664
> 
> Additionally, only Float64/ComplexF64 are supported in practice.
> Ref: https://github.com/JuliaLang/julia/issues/25986

**Comment by StefanKarpinski** [comment]
> I believe that if we can't support all the int/float types, it should be the Int32/Float64 combination.

Having an arbitrary index cap of 2 billion just for this one array type when we don't have it anywhere else is pretty weird and unfortunate. Especially for a type that is specifically designed to support sparsity.

This argument is also completely at odds with the conclusion that the triage discussion came to last time, which has blocked any progress on this issue.

**Comment by KristofferC** [comment]
So, if possible, could we not enable any new promotions with this PR so that the things that used to stackoverflow are now MethodErrors instead? Is that enough for you @simonbyrne to go ahead and merge this or are there other things that need to be decided?

**Comment by simonbyrne** [comment]
What if we were to allow both types by lazily activating CHOLMOD for which ever was used first? We could even add reference counting to allow switching if there are no active objects of the other type?

**Comment by StefanKarpinski** [comment]
> What if we were to allow both types by lazily activating CHOLMOD for which ever was used first? We could even add reference counting to allow switching if there are no active objects of the other type?

That sounds... very fancy. I think it might be better to have an option that let's you switch which is supported as long as you haven't used either yet which picks a reasonable default.

**Comment by ViralBShah** [comment]
I would much rather much something here right away that fixes the immediate issue, and do the fancy thing in a separate PR.

**Comment by StefanKarpinski** [comment]
The fancy thing of allowing whatever is used first is actually the least breaking change. Any code that currently works and doesn't hit this issue would continue working. Code that is currently hitting the bug would get a clear error message about the problem. If the upstream issue gets fixed then we could just relax the restriction and again, nothing would break. It's possibly the right way to go now that I think about it...

**Comment by simonbyrne** [comment]
So this now throws a `MethodError` for non-`Int` indices, and promotes `Float32` to `Float64`. This should be non-breaking, so can be merged and in future we can figure out how to initialise different indices, and make SPQR (for `qr`)and UMFPACK (for `lu`) consistent as well.

**Comment by StefanKarpinski** [comment]
Does this need a NEWS entry?

**Comment by simonbyrne** [comment]
See #30293.
