### PR TITLE
Workaround upstream FreeBSD issue #272992

### LINKED ISSUE #50846: `dllist()` returns no items on FreeBSD
With Julia 1.9.2 on FreeBSD 13.2, `dllist()` returns 42 entries. With 1.10.0-beta1 and `master`, it incorrectly returns 0 entries. The `libdl` and `binaryplatform` tests are failing for this reason. This is a regression introduced by https://github.com/JuliaLang/julia/pull/50162. Specifically, reordering the sources for symbol lookup to put the exe last caused this; the sanitizer parts of that PR are unrelated.

### PR DESCRIPTION
**Pull request by topolarity**
ELF doesn't handle WEAK symbols dynamically the way it handles them statically.

Looking up overloaded WEAK symbols via a library-specific handle will often give you the empty stub (in `libc.so.7` in this case) instead of the strong implementation elsewhere (`ld-elf.so.1` here).

Even after the [upstream fix](https://cgit.freebsd.org/src/commit/?id=21a52f99440c9bec7679f3b0c5c9d888901c3694), `dlsym`, `dladdr` and a ton of other symbols still have stubs with no trampoline in FreeBSD's libc:
https://cgit.freebsd.org/src/tree/lib/libc/gen/dlfcn.c?id=21a52f99440c9bec7679f3b0c5c9d888901c3694 Thankfully `dl_iterate_phdr` appears to be the only function that we directly `ccall` from Julia's Libdl so we can leave this fix incomplete for now.

Resolves #50846.

### CODE REVIEW

File: src/dlload.c [hunk 1]
```diff
@@ -435,6 +435,13 @@ JL_DLLEXPORT int jl_dlsym(void *handle, const char *symbol, void ** value, int t
 // Look for symbols in internal libraries
 JL_DLLEXPORT const char *jl_dlfind(const char *f_name)
 {
+#ifdef _OS_FREEBSD_
+    // This is a workaround for FreeBSD <= 13.2 which do not have
+    // https://cgit.freebsd.org/src/commit/?id=21a52f99440c9bec7679f3b0c5c9d888901c3694
+    // (See https://github.com/JuliaLang/julia/issues/50846)
+    if (strcmp(f_name, "dl_iterate_phdr") == 0)
```
Comment (ararslan) [inline src/dlload.c:442]: This seems reasonable to me as a stopgap solution but I wonder if there's a way we can more directly query whether `dl_iterate_phdr` resolved to libc does the right thing so that we don't have to perform this check on every call.

Comment (topolarity) [reply src/dlload.c:442]: I expect this check is generally a lot cheaper than the `dlsym`s below, but thankfully the standard function/library pointer caching for `ccall` should mean we only do this once per call-site

**Comment by ararslan** [comment]
Screenshot 2023-08-30 at 10 03 58 AM

💖

**Review by staticfloat — APPROVED** [review]

**Comment by ararslan** [comment]
The x86_64-linux-gnuassertrr failure is unrelated
