### PR TITLE
avoid hang when only threads are starting IO

### LINKED ISSUE #48430: sleep causes Julia to hang in multi-threaded context
Reported and discussed in https://julialang.slack.com/archives/C688QKS7Q/p1674678148290409 (but probably it will be quickly lost so I am re-reporting it here as the issue persists and causes DataFrames.jl GitHub Actions CI to constantly fail).

On some systems (not all) when you start Julia with multiple threads and run the following code:

```
julia> for i in 1:10
           println("ping $i")
           @sync Threads.@spawn sleep(0.01)
           println("pong $i")
       end
ping 1
pong 1
ping 2
pong 2
ping 3
pong 3
ping 4
pong 4
ping 5
pong 5
ping 6
pong 6
ping 7
pong 7
ping 8
pong 8
ping 9
pong 9
ping 10
pong 10

julia> for i in 1:10
           @sync Threads.@spawn sleep(0.01)
       end
```
It freezes Julia. Note in particular, that doing some IO within the loop ensures that no freezing happens. (the same freezing happens if loop is replaced by multiple invocations of `@sync Threads.@spawn sleep(0.01)` in top level scope or if the loop is wrapped in a function and a function is called)

This problem is observed on Julia nightly on the following example configurations:

```
Julia Version 1.10.0-DEV.430
Commit 9b1ffbbe1b (2023-01-25 12:52 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 12 virtual cores
```
and
```
Julia Version 1.10.0-DEV.427
Commit dfab7be1f8b (2023-01-24 19:07 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 2 × Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, icelake-server)
```
and
```
Julia Version 1.10.0-DEV.430
Commit 9b1ffbbe1b (2023-01-25 12:52 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-1260P
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 4 on 16 virtual cores
```
and
```
Julia Version 1.10.0-DEV.430
Commit 9b1ffbbe1bc (2023-01-25 12:52 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
```

### PR DESCRIPTION
**Pull request by vtjnash**
When not in threaded region, only thread 0 will manage IO events, but it may go to sleep if there are none started for it to watch.

Fix #48430

### CODE REVIEW

File: src/partr.c [hunk 1]
```diff
@@ -424,6 +424,11 @@ JL_DLLEXPORT jl_task_t *jl_task_get_next(jl_value_t *trypoptask, jl_value_t *q,
                     continue;
                 }
             }
+            else if (ptls->tid != 0 && !jl_atomic_load_relaxed(&_threadedregion)) {
+                // Since we might have started some IO work, we might need to ensure
+                // tid = 0 will go watch that new event source for us.
+                (void)wake_thread(0);
```
Comment (vtjnash) [inline src/partr.c:430]: This does not wake thread 0 quite properly enough to merge this yet. I need to work more to figure out if we need another sleep_check_state (to distinguish sleeping in uv_run vs entirely stopped), or whether to take some other approach towards checking here such as:
```diff
diff --git a/src/partr.c b/src/partr.c
index 4faff409c7..3ab2cebe0d 100644
--- a/src/partr.c
+++ b/src/partr.c
@@ -425,6 +425,14 @@ JL_DLLEXPORT jl_task_t *jl_task_get_next(jl_value_t *trypoptask, jl_value_t *q,
                 }
             }
 
+            if (ptls->tid != 0 && !jl_atomic_load_relaxed(&_threadedregion)) {
+                // Since we might have started some IO work, we might need to ensure
+                // tid = 0 will go watch that new event source for us.
+                jl_task_t *uvlock = jl_atomic_load_relaxed(&jl_uv_mutex.owner);
+                if (uvlook == NULL)
+                    jl_wakeup_thread(0);
+            }
+
             // the other threads will just wait for an individual wake signal to resume
             JULIA_DEBUG_SLEEPWAKE( ptls->sleep_enter = cycleclock() );
             int8_t gc_state = jl_gc_safe_enter(ptls);
```

**Comment by bkamins** [comment]
Build of this branch using Cygwin-to-MinGW on Windows works and does not hang.
```
Julia Version 1.10.0-DEV.445
Commit d7693f1a19 (2023-01-28 05:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 12 virtual cores
```

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
The tests fail with several `EOFError: read end of file` problems, but you probably understand better than me if this is related or not.

**Review by JeffBezanson — APPROVED** [review]
