### PR TITLE
Fix regression in `map` and `collect`

### LINKED ISSUE #43112: `map` throws type assertion error
Hi,

(I'm opening this as a separate issue for easy tracking and to make sure people see this.)

I just noticed that the type inference related changes newly introduced in #42046 breaks my existing code. A minimal example:
```julia
map(1:4) do i
    a = (x=i, y=(i==1 ? 1 : "a"))
    b = 3
    (a, b)
end
```
throws the following error
```
ERROR: LoadError: TypeError: in typeassert, expected AbstractVector{<:Tuple{NamedTuple{(:x, :y), _A} where _A<:Tuple{Int64, Union{Int64, String}}, Int64}}, got a value of type Vector{Tuple{NamedTuple{(:x, :y)}, Int64}}
Stacktrace:
 [1] _collect(c::UnitRange{Int64}, itr::Base.Generator{UnitRange{Int64}, Main.SEDL.var"#636#637"}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
   @ Base ./array.jl:754
 [2] collect_similar(cont::UnitRange{Int64}, itr::Base.Generator{UnitRange{Int64}, Main.SEDL.var"#636#637"})
   @ Base ./array.jl:653
 [3] map(f::Function, A::UnitRange{Int64})
   @ Base ./abstractarray.jl:2849
 [4] top-level scope
   @ ~/.julia/dev/SEDL/scripts/hovercraft_example.jl:63
```

I just upgraded to 1.7.0-rc3 from rc1 this morning and immediately ran into this. Looks like the computed type annotation is more precise but is not compatible with the actual returned collection type.

### PR DESCRIPTION
**Pull request by nalimilan**
`promote_typejoin_tuple` returned a type which was more precise than the one which `map` and `collect` actually use via `promote_type`, triggering an assertion error in corner cases.

This is an attempt at fixing #43112.

### CODE REVIEW

File: base/promotion.jl [hunk 1]
```diff
@@ -195,7 +195,7 @@ function typejoin_union_tuple(T::Type)
         elseif U isa Union
             ci = typejoin(U.a, U.b)
         else
-            ci = U
+            ci = promote_typejoin_union(U)
```
Comment (nalimilan) [inline base/promotion.jl:198]: @vtjnash According to what you noted at https://github.com/JuliaLang/julia/pull/30485#discussion_r251042912, it's not correct to call `promote_typejoin_union` from here given that the function is marked as `@pure`. But I don't know how to fix this otherwise, as without `@pure` the result isn't inferred, which defeats the point of all this code.

**Review by vtjnash — CHANGES_REQUESTED** [review]
This seems like the wrong fix, but I think it has put me on the path of the correct one

File: base/promotion.jl (hunk 1 above)
Comment (vtjnash) [reply base/promotion.jl:198]: Yes, exactly as your edit says. Note that `promote_typejoin_union(U)` here is already defined to be `ci = Any`, so that is the identical change too. And we could perhaps simplify the structure a bit:
```
diff --git a/base/promotion.jl b/base/promotion.jl
index 21245f0e05..70bb4c3b53 100644
--- a/base/promotion.jl
+++ b/base/promotion.jl
@@ -168,19 +168,17 @@ function promote_typejoin_union(::Type{T}) where T
         return Any # TODO: compute more precise bounds
     elseif T isa Union
         return promote_typejoin(promote_typejoin_union(T.a), promote_typejoin_union(T.b))
-    elseif T <: Tuple
-        return typejoin_union_tuple(T)
-    else
+    elseif T isa DataType
+        T <: Tuple && return typejoin_union_tuple(T)
         return T
+    else
+        error("unreachable") # not a type??
     end
 end
 
-function typejoin_union_tuple(T::Type)
+function typejoin_union_tuple(T::DataType)
     @_pure_meta
     u = Base.unwrap_unionall(T)
-    u isa Union && return typejoin(
-            typejoin_union_tuple(Base.rewrap_unionall(u.a, T)),
-            typejoin_union_tuple(Base.rewrap_unionall(u.b, T)))
     p = (u::DataType).parameters
     lr = length(p)::Int
     if lr == 0
@@ -192,6 +190,8 @@ function typejoin_union_tuple(T::Type)
         U = Core.Compiler.unwrapva(pi)
         if U === Union{}
             ci = Union{}
+        elseif U isa UnionAll
+            return Any # TODO: compute more precise bounds
         elseif U isa Union
             ci = typejoin(U.a, U.b)
         else
```

**Comment by nalimilan** [comment]
> This seems like the wrong fix, but I think it has put me on the path of the correct one

That was exactly the plan. :-p

I've pushed your fix. Let's hope we haven't missed yet another corner case that will be caught only later!

**Review by vtjnash — APPROVED** [review]

**Comment by nalimilan** [comment]
Thanks!
