### PR TITLE
[JuliaLowering] Several small bugfixes found in stdlib testing

### LINKED ISSUE #142: `LineNumberNode` conversion error when macro-expanding `@testset` with multi-`for` iteration
```julia
julia> JuliaLowering.include_string(Main, raw"""
           @testset "multi-for" for a = (NaN, Inf), b = (1, 2), c = (true, false); end
       """; expr_compat_mode=true)
ERROR: MacroExpansionError while expanding @testset in module Main:
    @testset "multi-for" for a = (NaN, Inf), b = (1, 2), c = (true, false); end
#   └─────────────────────────────────────────────────────────────────────────┘ ── Error expanding macro
Caused by:
MethodError: Cannot `convert` an object of type LineNumberNode to an object of type Expr
```

### LINKED ISSUE #143: 'Invalid syntax; K"curly"' when expanding macro with global binding type
```julia
julia> macro foo()
           return :(global val::Union{Float64,Int})
       end
@foo (macro with 1 method)

julia> JuliaLowering.include_string(Main, "@foo"; expr_compat_mode=true)
ERROR: LoweringError:
#= string:1 =# - Invalid syntax; K"curly"

Detailed provenance:
(curly #₂/Union #₃/Float64 #₄/Int)
└─ (curly Union Float64 Int)
   └─ (curly Union Float64 Int)
      └─ (curly Union Float64 Int)
         ├─ (curly Union Float64 Int)
         │  └─ @ string:1
         └─ (macrocall @foo :(#= string:1 =#))
            └─ (macrocall (macro_name ✘ foo))
               └─ @ string:1
```

### LINKED ISSUE #146: "expected `numchildren(binding) == 2`" when lowering `global x += 1`
```julia
julia> JuliaLowering.include_string(Main, raw"""
       function foo()
           global bar += 1
       end
       """; expr_compat_mode=true)
ERROR: LoweringError:
function foo()
    global bar += 1
#         └───────┘ ── expected `numchildren(binding) == 2`
end

Detailed provenance:
(op= bar + 1)
└─ (unknown_head bar 1)
   └─ (unknown_head bar 1)
      └─ (op= ✘ bar ✘ + = ✘ 1)
         └─ @ string:2

Stacktrace:
    [1] macro expansion
      @ ~/repos/julia/JuliaLowering/src/ast.jl:43 [inlined]
    [2] expand_decls(ctx::JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
      @ JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:2223
    [3] expand_forms_2(ctx::JuliaLowering.DesugaringContext{Dict{…}}, ex::JuliaSyntax.SyntaxTree{Dict{…}}, docs::Nothing)
      @ JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:4519
```

needed for `FileWatching` tests

### PR DESCRIPTION
**Pull request by mlechu**
- Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/143, simple missing
  desugaring on the rhs of a global type decl
- Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/142, producing
  LineNumberNodes in the first argument to `for` when it is a block.  flisp and
  JuliaSyntax make an exception for this block (and the one in `let`, which I've
  also changed).  I wrote down what linenodes I expect macro authors to tolerate
  for future reference.
- Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/146, which was just
  desugaring not knowing it had to handle `op=` (or `.op=`).
  - Fix the validator in the `global x .= y` case.  I missed this case expecting
    it to be part of `vst1_op_assign`.
  - Remove handling of non-top-level global type decls in the validator.  I 
    thought flisp was checking in desugaring, but it actually waits until scope 
    resolution.
- Remove checking for duplicate type decls on globals.  flisp only does this for
  locals (which only exist in one top-level expression, so the checking can be
  complete).
- Fix desugaring of `(string (... _))` form

All the changes above should be tested.  Suggestions for more are welcome!

### CODE REVIEW

File: JuliaLowering/src/compat.jl [hunk 1]
```diff
@@ -97,7 +97,7 @@ function _expr_to_est(graph::SyntaxGraph, @nospecialize(e), src::LineNumberNode)
     return st._id, src
 end
 
-function est_to_expr(st::SyntaxTree)
+function est_to_expr(st::SyntaxTree, suppress_linenodes=false)
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl:103]:
```suggestion
function est_to_expr(st::SyntaxTree; suppress_linenodes=false)
```
just a suggestion, for clarity

File: JuliaLowering/src/compat.jl [hunk 2]
```diff
@@ -116,22 +116,45 @@ function est_to_expr(st::SyntaxTree)
...
+        # Macro authors are responsible for handling any linenodes that follow
+        # the rules above (but the presence of optional linenodes can't be
+        # counted upon).
+        need_lnns = head in (:block, :toplevel) && !suppress_linenodes
+        for (i, c) in enumerate(children(st))
             need_lnns && push!(out.args, source_location(LineNumberNode, c))
-            push!(out.args, est_to_expr(c))
+            let suppress_c = i == 1 && (k == K"for" || k == K"let")
+                push!(out.args, est_to_expr(c, suppress_c))
+            end
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl:142]:
```suggestion
            let suppress_linenodes = i == 1 && (k == K"for" || k == K"let")
                push!(out.args, est_to_expr(c; suppress_linenodes))
            end
```

File: JuliaLowering/src/compat.jl [hunk 3]
```diff
@@ -116,22 +116,45 @@ function est_to_expr(st::SyntaxTree)
...
+                push!(out.args, source_location(LineNumberNode, st))
+            [K"module" _... [K"block" _...]] ->
+                pushfirst!(out.args[end].args, source_location(LineNumberNode, st))
+            [K"function" _ [K"block" _...]] ->
+                pushfirst!(out.args[end].args, source_location(LineNumberNode, st))
+            [K"macro" _ [K"block" _...]] ->
+                pushfirst!(out.args[end].args, source_location(LineNumberNode, st))
+            [K"for" _ [K"block" _...]] ->
+                push!(out.args[end].args, source_location(
+                    LineNumberNode, sourcefile(st), last_byte(st)))
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl:156]: Is it possible for this to add the `LineNumberNode` we're trying to suppress?

File: JuliaLowering/src/desugaring.jl [hunk 4]
```diff
@@ -2215,23 +2216,20 @@ end
...
+        simple = kind(c) in KSet"Identifier :: Value Placeholder"
+        lhs = @stm c begin
+            (_, when=simple) -> c
+            [K"=" x _] -> x
+            [K".=" x _] -> x
+            [K"op=" x _ _] -> x
+            [K".op=" x _ _] -> x
+            [K"function" x _] -> x
+        end
+        # type decls are handled elsewhere unless simple
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl:2230]: just a question, but does this mean elsewhere in desugaring or in a separate pass entirely?

File: JuliaLowering/src/scope_analysis.jl [hunk 5]
```diff
@@ -378,7 +378,7 @@ function _resolve_scopes(ctx, ex::SyntaxTree,
         id = ex_out[1]
         if kind(id) != K"Placeholder"
             binfo = get_binding(ctx, id)
-            if !isnothing(binfo.type)
+            if !isnothing(binfo.type) && binfo.kind !== :global
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl:381]: I assume this is OK because this will still eventually error?

**Review by topolarity — APPROVED** [review]
Looks like I need to file a new set of bugs! 😄 I'm happy about that

File: JuliaLowering/src/compat.jl (hunk 3 above)
Comment (topolarity) [reply JuliaLowering/src/compat.jl:156]: Ah this is not an issue, because this is the second child. Looks good, but might be worth a quick comment.

File: JuliaLowering/src/compat.jl [hunk 6]
```diff
@@ -116,22 +116,45 @@ function est_to_expr(st::SyntaxTree)
...
-        # extra linenodes
-        n = length(out.args)
-        if (k === K"module" && 3 <= n <= 4 && kind(st[end]) === K"block") ||
-            (k in KSet"function macro" && n === 2 && kind(st[end]) === K"block")
-            pushfirst!(out.args[end].args, source_location(LineNumberNode, st))
+        # Add extra linenodes to some blocks for better provenance
+        @stm st begin
+            ([K"block"], when=!suppress_linenodes) ->
+                push!(out.args, source_location(LineNumberNode, st))
+            [K"module" _... [K"block" _...]] ->
```
Comment (topolarity) [inline JuliaLowering/src/compat.jl:148]:
```suggestion
            # all following cases ignore `suppress_linenodes`
            # (it only applies to the immediate expression, not transitively to children)
            [K"module" _... [K"block" _...]] ->
```

File: JuliaLowering/src/scope_analysis.jl (hunk 5 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:381]: Yes, the error (if the type is different from before) should be caught after lowering

File: JuliaLowering/src/desugaring.jl (hunk 4 above)
Comment (mlechu) [reply JuliaLowering/src/desugaring.jl:2230]: Elsewhere in desugaring

File: JuliaLowering/src/compat.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/src/compat.jl:142]: Clearer to keep the inner tree `c`'s setting named differently from the outer tree's setting IMO

Comment (topolarity) [reply JuliaLowering/src/compat.jl:142]: OK that's fair, but `suppress_c` is more cryptic than necessary IMO

seems to expand to "suppress_child" but it doesn't actually suppress the child
