### PR TITLE
eliminate intrinsics

### LINKED ISSUE #18687: Inconsistent parsing of `ccall`
`ccall` appears to be parsed different with a normal call when it's part of another expression.

``` jl
julia> :(ccall(ptr, A, ()).v)
ERROR: syntax: missing comma or ) in argument list

julia> :(ccall(ptr, A, ())[1])
:(ccall(ptr,A,()) * [1])

julia> :(f(ptr, A, ())[1])
:((f(ptr,A,()))[1])

julia> :(f(ptr, A, ()).v)
:(f(ptr,A,()).v)
```

Ideally they should be parsed the same way.

### PR DESCRIPTION
**Pull request by vtjnash**
After this, only 1 intrinsics (llvmcall ~~and some ccall fixes~~) remain to go to be fully interpretable and statically compilable!
- removes special parsing rules for `ccall` (and thus removes `Expr(:ccall)`), fixes #18687
- makes `Expr(:call, :ccall)` special in lowering (effectively, reserving `ccall` – as the keyword it already is) and which expands to `Expr(:foreigncall)` representing the lowered ffi call (instead of expanding to `Expr(:call, Core.Intrinsics.ccall)`, even though this couldn't really be a first-class function)
- adds error checking to all Core.Intrinsic functions
- adds support to `ccall` for calling llvm intrinsics directly (via "llvmcall" calling convention)
- the `unbox` intrinsic is now just a deprecated alias for the `box` intrinsic (aka `reinterpret`)

The ccall intrinsic now evaluates its global arguments during method definition time, eliminating the call back into the runtime from inside codegen (yay!), and making its semantics independent of runtime values (so that its behavior is statically compilable).

edit: see https://github.com/vtjnash/julep/wiki/0001:-Enhanced-static-compilation-and-C-interface

### CODE REVIEW

File: base/floatfuncs.jl [hunk 1]
```diff
@@ -2,40 +2,40 @@
 
 ## floating-point functions ##
 
-copysign(x::Float64, y::Float64) = box(Float64,copysign_float(unbox(Float64,x),unbox(Float64,y)))
-copysign(x::Float32, y::Float32) = box(Float32,copysign_float(unbox(Float32,x),unbox(Float32,y)))
+copysign(x::Float64,  y::Float64) = box(Float64, copysign_float(x, y))
+copysign(x::Float32,  y::Float32) = box(Float32, copysign_float(x, y))
```
Comment (Sacha0) [inline base/floatfuncs.jl]: Extra space preceding `y` in the method signature?

File: base/floatfuncs.jl [hunk 2]
```diff
@@ -2,40 +2,40 @@
...
 copysign(x::Float32, y::Real) = copysign(x, Float32(y))
 copysign(x::Float64, y::Real) = copysign(x, Float64(y))
 
-flipsign(x::Float64, y::Float64) = box(Float64,xor_int(unbox(Float64,x),and_int(unbox(Float64,y),0x8000000000000000)))
-flipsign(x::Float32, y::Float32) = box(Float32,xor_int(unbox(Float32,x),and_int(unbox(Float32,y),0x80000000)))
+flipsign(x::Float64,  y::Float64) = box(Float64, xor_int(box(UInt64, x), and_int(box(UInt64, y), 0x8000000000000000)))
+flipsign(x::Float32,  y::Float32) = box(Float32, xor_int(box(UInt32, x), and_int(box(UInt32, y), 0x80000000)))
```
Comment (Sacha0) [inline base/floatfuncs.jl]: Extra space preceding `y` in the method signature here as well?

**Comment by maleadt** [comment]
Cool, the `llvmcall` calling convention will make some of our `llvmcall(...)` usage in CUDAnative redundant. What about function attributes though? Most NVPTX intrinsics are `readnone nounwind`.

For PTX we also need to call into `libdevice`, an IR blob providing implementations of common math functions. This blob is linked in during JIT, so regular `ccall` doesn't work (disregarding the fact that there's no `dlopen`, etc). Bottom line, it would be handy if the new `llvmcall` cc wouldn't check for isIntrinsic, even though it makes sense to require that for every other sane use case...

File: doc/manual/calling-c-and-fortran-code.rst [hunk 3]
```diff
@@ -1003,6 +1003,20 @@ For more information, please see the `LLVM Language Reference`_.
...
+There is one additional special calling convention ``llvmcall``,
+which allows inserting calls to LLVM intrinsics directly.
+This can be especially useful when targeting unusual platforms such as GPGPUs.
+For example, for `CUDA`_, we need to be able to read the thread index::
+
+    ccall("llvm.nvvm.read.ptx.sreg.tid.x", llvmcall, Int32, ())
+
+.. _CUDA: http://llvm.org/docs/NVPTXUsage.html
+
+As with any ccall, it is essential to get the argument signature exactly correct.
```
Comment (tkelman) [inline doc/manual/calling-c-and-fortran-code.rst]: code highlight `ccall`

File: src/ccall.cpp [hunk 4]
```diff
@@ -1289,35 +1306,108 @@ static std::string generate_func_sig(
...
+                                          size_t &nargt, bool &isVa)
+{
+    if (jl_is_svec(rt)) {
+        std::string msg = "in ";
+        msg += funcName;
+        msg += ": ccall: missing return type";
+        jl_error(msg.c_str()); // TODO: this leaks memory
+    }
+    if (jl_is_cpointer_type(rt) && jl_is_typevar(jl_tparam0(rt)))
+        jl_error("ccall: return type Ptr should have an element type, not Ptr{_<:T}");
```
Comment (tkelman) [inline src/ccall.cpp]: this `Ptr{_<:T}` will be pretty confusing

File: src/intrinsics.cpp [hunk 5]
```diff
@@ -70,85 +106,80 @@ extern "C" JL_DLLEXPORT int8_t jl_is_memdebug() {
     where the box is needed.
 */
 
-static Type *FTnbits(size_t nb)
+// convert an llvm type to same-size float type
+static Type *FLOATT(Type *t)
 {
+    if (t->isFloatingPointTy())
+        return t;
+    unsigned nb = (t->isPointerTy() ? t->getPrimitiveSizeInBits() : sizeof(void*));
```
Comment (tkelman) [inline src/intrinsics.cpp]: is this backwards?

File: src/intrinsics.cpp [hunk 6]
```diff
@@ -70,85 +106,80 @@ extern "C" JL_DLLEXPORT int8_t jl_is_memdebug() {
...
-    assert(t == T_void);
-    return T_void;
+    if (t == T_float64)
+        return T_int64;
+    if (t == T_float32)
+        return T_int32;
+    if (t == T_float16)
+        return T_int16;
+    //if (t == T_float128)
+    //    return T_int128;
```
Comment (tkelman) [inline src/intrinsics.cpp]: leave a comment or a cross-reference about why this is commented out (same below in `JL_JL_UINTT`)

File: src/intrinsics.cpp [hunk 7]
```diff
@@ -516,191 +516,141 @@ static jl_cgval_t generic_box(jl_value_t *targ, jl_value_t *x, jl_codectx_t *ctx
...
 {
-    jl_cgval_t parg = emit_expr(e, ctx);
-    Value *iarg = boxed(emit_expr(i, ctx), ctx);
-    Value *alignarg = boxed(emit_expr(align, ctx), ctx);
-#if JL_LLVM_VERSION >= 30700
-    Value *ret = builder.CreateCall(prepare_call(jlpref_func), { boxed(parg, ctx), iarg, alignarg });
-#else
-    Value *ret = builder.CreateCall3(prepare_call(jlpref_func), boxed(parg, ctx), iarg, alignarg);
+#ifdef JL_NEED_FLOATTEMP_VAR
+        // Target platform might carry extra precision.
```
Comment (tkelman) [inline src/intrinsics.cpp]: excess indent

**Comment by tkelman** [comment]
needs a test for #18687

File: src/ccall.cpp (hunk 4 above)
Comment (vtjnash) [inline src/ccall.cpp]: this isn't a new change

File: src/intrinsics.cpp (hunk 6 above)
Comment (vtjnash) [inline src/intrinsics.cpp]: this isn't a new change

**Comment by vtjnash** [comment]
this isn't that kind of fix. this "fixes" the issue by deleting the special parsing code and the tests for it (of which apparently there were none).

File: src/intrinsics.cpp (hunk 6 above)
Comment (tkelman) [inline src/intrinsics.cpp]: that's not a reason to leave unexplained things or lousy error messages in the code. while it's being rearranged is the right time to make these little improvements

**Comment by tkelman** [comment]
doesn't matter how it's being fixed. add a test.

**Comment by vtjnash** [comment]
It's not fixed, it's deleted, along with all tests for it.

**Comment by tkelman** [comment]
That issue is about the fact that it works differently on master. To close that issue, and just in general, should add tests that it no longer works differently in this pr. Not asking for much here, tests and comments. Why are you fighting that?

**Comment by vtjnash** [comment]
I'm not fixing that issue, I'm deleting the feature that the referenced issue complained about.

**Review by tkelman — DISMISSED** [review]
So what? You're replacing it with a new implementation that **needs to be tested** that it no longer has the undesirable behavior.

**Comment by vtjnash** [comment]
> So what? You're replacing it with a new implementation that needs to be tested that it no longer has the undesirable behavior.

No, it's completely gone. The parser no longer has any knowledge of `ccall`.

**Comment by tkelman** [comment]
The implementation now happening in lowering instead of parsing doesn't change the fact that the parser behavior change for ccall should be tested and verified.

**Comment by vtjnash** [comment]
How does the parser not implementing ccall not eliminate the need to test how the parser implements ccall? The parser no longer has *any* special behavior related to the symbol `ccall`, it is handled by exactly the same code as handles all `Expr(:call)` form expressions.

**Comment by tkelman** [comment]
Because the parser used to implement ccall. If it hadn't had a custom implementation before, it would be fine. This is a change in behavior specifically for ccall, and that's the part that should now be tested.

File: src/intrinsics.cpp (hunk 5 above)
Comment (tkelman) [inline src/intrinsics.cpp]: needs-test then if it was passing with a mistake here

**Comment by tkelman** [comment]
why is llvmcall2 a separate file here? would the "nonsensical valid conversions and errors" tests have caught the mistake from https://github.com/JuliaLang/julia/pull/18754#discussion_r81501204 ?

**Comment by vtjnash** [comment]
It tests v2 of llvmcall. Yes, it includes coverage of that case.

**Comment by JeffBezanson** [comment]
It occurs to me that after this change we should add t-functions for all intrinsics (previously we relied on their results always being passed to `box`).

**Comment by vtjnash** [comment]
Yes, that's also on my list of eventually fixes for here (along with completely removing unbox and removing most calls to box)

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`. This is also a good candidate for PkgEval before merging (since it changes the behavior of ccall)

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/18754#issuecomment-253839513):
```
NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]")
```Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b4315662641f569288b090a8c7d6fa8247a05841/92bd0e0_vs_4ba21aa/report.md)
cc @jrevels

**Comment by vtjnash** [comment]
Let's try that again, with the deprecation in place. @nanosoldier `runbenchmarks(ALL, vs=":master")`.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18754#issuecomment-253862276) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/61182cf6c2ff31b8db4258acf548dabccd2794bb/43cc839_vs_51e9247/report.md). cc @jrevels

File: doc/manual/calling-c-and-fortran-code.rst [hunk 8]
```diff
@@ -51,24 +51,28 @@ function, all inputs must be passed by reference.
 Finally, you can use :func:`ccall` to actually generate a call to the
 library function. Arguments to :func:`ccall` are as follows:
 
-1. (:function, "library") pair (must be a constant, but see below).
+1. A ``(:function, "library")`` pair, which must be written as a literal constant,
+
+   OR
+
+   a function pointer (for example, from :func:``dlsym``).
```
Comment (tkelman) [inline doc/manual/calling-c-and-fortran-code.rst]: `:func` references use single backticks, I believe

File: doc/manual/calling-c-and-fortran-code.rst [hunk 9]
```diff
@@ -533,30 +539,40 @@ the field that will have the greatest size (potentially including padding).
...
+
+Type Parameters
+~~~~~~~~~~~~~~~
+
+The static parameters of the function may be used as type parameters in the ``ccall`` signature,
+as long as they don't affect the layout of the type.
+For example, ``f{T}(x::T) = ccall(:valid, Ptr{T}, (Ptr{T},), x)``
+is valid, since ``Ptr`` is always a word-size bitstype.
+But, ``g{T}(x::T) = ccall(:notvalid, T, (T,), x)``
+is not valid, since the type layout of T is not known statically.
```
Comment (tkelman) [inline doc/manual/calling-c-and-fortran-code.rst]: code highlight T

File: doc/manual/calling-c-and-fortran-code.rst (hunk 8 above)
Comment (vtjnash) [inline doc/manual/calling-c-and-fortran-code.rst]: it seemed like `make doc` didn't care when I tested both ways

Comment (tkelman) [inline doc/manual/calling-c-and-fortran-code.rst]: did it render correctly? there are zero instances of ```git grep -n 'func:``'``` currently

File: src/codegen.cpp [hunk 10]
```diff
@@ -292,8 +291,15 @@ int32_t jl_jlcall_api(const void *function)
     // give the function an index in the constant lookup table
     if (function == NULL)
         return 0;
-    const Function *F = (const Function*)function;
-    return (F->getFunctionType() == jl_func_sig ? 1 : 3);
+    const Function *F = cast<const Function>((const Value*)function);
+    StringRef Name = F->getName();
+    if (Name.startswith("japi3_"))
+       return 3;
```
Comment (tkelman) [inline src/codegen.cpp]: indent not quite right

File: doc/manual/calling-c-and-fortran-code.rst (hunk 8 above)
Comment (vtjnash) [inline doc/manual/calling-c-and-fortran-code.rst]: upon rechecking, no it doesn't

File: src/intrinsics.cpp [hunk 11]
```diff
@@ -38,9 +39,43 @@ static void jl_init_intrinsic_functions_codegen(Module *m)
...
+    float_func[lt_float] = true;
+    float_func[le_float] = true;
+    float_func[eq_float_fast] = true;
+    float_func[ne_float_fast] = true;
+    float_func[lt_float_fast] = true;
+    float_func[le_float_fast] = true;
+    float_func[fpiseq] = true;
+    float_func[fpislt] = true;
+    float_func[abs_float] = true;
+    //float_func[copysign_float] = false;
```
Comment (vtjnash) [inline src/intrinsics.cpp]: so that you can see it wasn't forgotten in the list

**Comment by tkelman** [comment]
`Ptr{_<:T}` is still really confusing in one of the `ccall` error messages, and the commented-out Float128 lines could use cross-references or explanations about why they're disabled

File: src/intrinsics.cpp (hunk 11 above)
Comment (tkelman) [inline src/intrinsics.cpp]: why is it false then?

**Comment by tkelman** [comment]
> This is also a good candidate for PkgEval before merging (since it changes the behavior of ccall)

I can do this, but it'll be best if the master baseline has fixed the ssl certificate issues that are currently causing problems.

**Comment by vtjnash** [comment]
> Ptr{_<:T} is still really confusing in one of the ccall error messages, and the commented-out Float128 lines could use cross-references or explanations about why they're disabled

These are left alone because I'm trying not to change everything in one PR. Sure this changes a lot of related content. But that still doesn't mean it needs to change everything in sight.

File: src/intrinsics.cpp (hunk 11 above)
Comment (tkelman) [inline src/intrinsics.cpp]: could you say that in a comment then?

**Comment by vtjnash** [comment]
I did a PkgEval run. There's lots of unrelated failures (due to the mbedtls bug and the cache uuid bug in my build). And a lot more failures being picked up due to inadequate test coverage in those packages (this moves a compile error earlier). The set that might merit further research are below, although from a quick glance through, the failures there looked like the ones I expected should happen and will be easy for those authors to resolve.
https://gist.github.com/vtjnash/3a05a54fe793bb52734e2a74a9265682
Documenter
FLAC
GMT
HTTPClient
FactCheck (correctly detects that ccall parsing is no longer special)
LibCURL
LibExpat
NLopt
ParameterizedFunctions
RequestsCache
SFML

**Comment by tkelman** [comment]
> due to the mbedtls bug and the cache uuid bug in my build

rebase the branch and those won't happen

**Comment by vtjnash** [comment]
I reran PkgEval; it produced no interesting new results. The updated results are in the same gist above.

Merge?

File: doc/manual/calling-c-and-fortran-code.rst [hunk 12]
```diff
@@ -533,30 +539,40 @@ the field that will have the greatest size (potentially including padding).
...
-    end
     type B
-        A::B_A
+        A::NTuple{3, A}
     end
-    b_a_2 = B.A.(2)
+    b_a_2 = B.A[2]
 
-Arrays of unknown size are not supported.
+Arrays of unknown size (C99-complaint variable length structs specified by ``[]`` or ``[0]``) are not supported.
```
Comment (tkelman) [inline doc/manual/calling-c-and-fortran-code.rst]: compliant

File: src/ccall.cpp [hunk 13]
```diff
@@ -1667,163 +1721,235 @@ static jl_cgval_t emit_ccall(jl_value_t **args, size_t nargs, jl_codectx_t *ctx)
...
 
+    Instruction *stacksave = NULL;
+    if (needStackRestore) {
+        stacksave = CallInst::Create(Intrinsic::getDeclaration(jl_Module,
+                                                               Intrinsic::stacksave));
+        if (savespot) {
+#if JL_LLVM_VERSION >= 30800
+                instList.insertAfter(savespot->getIterator(), stacksave);
+#else
+                instList.insertAfter(savespot, stacksave);
```
Comment (tkelman) [inline src/ccall.cpp]: wrong indent on these 2 lines?

File: src/intrinsics.cpp [hunk 14]
```diff
@@ -355,104 +392,48 @@ static Value *emit_unbox(Type *to, const jl_cgval_t &x, jl_value_t *jt, Value *d
...
-// figure out how many bits a bitstype has at compile time
-static int get_bitstype_nbits(jl_value_t *bt)
-{
-    assert(jl_is_bitstype(bt));
-    return jl_datatype_nbits(bt);
+    Value *r = builder.CreateCall(func, makeArrayRef(argvalues, nargs));
+    return mark_julia_type(r, true, (jl_value_t*)jl_any_type, ctx);
 }
 
 // put a bits type tag on some value (despite the name, this doesn't necessarily actually "box" the value however)
```
Comment (tkelman) [inline src/intrinsics.cpp]: parenthetical no longer relevant?

File: src/debuginfo.cpp [hunk 15]
```diff
@@ -822,7 +830,10 @@ static int lookup_pointer(DIContext *context, jl_frame_t **frames,
         else
             jl_copy_str(&frame->file_name, file_name.c_str());
 
-        if (!frame->func_name || !func_name.compare(0, 7, "jlcall_") || !func_name.compare(0, 7, "jlcapi_")) {
+        if (!frame->func_name ||
+                func_name.compare(0, 6, "jlsysw_") == 0 ||
+                func_name.compare(0, 6, "jlcall_") == 0 ||
+                func_name.compare(0, 7, "jlcapi_") == 0) {
```
Comment (tkelman) [inline src/debuginfo.cpp]: why are `jlsysw_` and `jlcall_` comparing 6, but `jlcapi_` is comparing 7?

File: src/alloc.c [hunk 16]
```diff
@@ -267,8 +267,31 @@ JL_DLLEXPORT jl_value_t *jl_new_struct_uninit(jl_datatype_t *type)
 }
 
 
+// type constructor -----------------------------------------------------------
+
+JL_DLLEXPORT jl_value_t *jl_new_type_constructor(jl_svec_t *p, jl_value_t *body)
```
Comment (JeffBezanson) [inline src/alloc.c]: Could you move this back? It will conflict with my branch.

File: base/inference.jl [hunk 17]
```diff
@@ -1201,19 +1186,19 @@ function abstract_eval_call(e::Expr, vtypes::VarTable, sv::InferenceState)
 end
 
 function abstract_eval(e::ANY, vtypes::VarTable, sv::InferenceState)
-    if isa(e,QuoteNode)
+    if isa(e, QuoteNode)
```
Comment (JeffBezanson) [inline base/inference.jl]: Would be nice to take out these small whitespace changes.

**Review by JeffBezanson — DISMISSED** [review]

**Comment by JeffBezanson** [comment]
Also discussed: `box` is not a very accurate term; should probably be renamed `bitcast`.

File: src/julia.h [hunk 18]
```diff
@@ -255,10 +255,6 @@ typedef struct _jl_method_t {
     int32_t called;  // bit flags: whether each of the first 8 arguments is called
     uint8_t isva;
     uint8_t isstaged;
-    // if there are intrinsic calls, sparams are probably required to compile successfully,
-    // and so unspecialized will be created for each linfo instead of using linfo->def->template
-    // 0 = no, 1 = yes, 2 = not yet known
-    uint8_t needs_sparam_vals_ducttape;
```
Comment (JeffBezanson) [inline src/julia.h]: :tada: :100:

File: src/codegen.cpp [hunk 19]
```diff
@@ -299,8 +298,15 @@ int32_t jl_jlcall_api(const void *function)
     // give the function an index in the constant lookup table
     if (function == NULL)
         return 0;
-    const Function *F = (const Function*)function;
-    return (F->getFunctionType() == jl_func_sig ? 1 : 3);
+    const Function *F = cast<const Function>((const Value*)function);
+    StringRef Name = F->getName();
+    if (Name.startswith("japi3_"))
+        return 3;
+    assert(Name.startswith("japi1_") ||
```
Comment (StefanKarpinski) [inline src/codegen.cpp]: We should also probably call these jlapiN, no? Although I guess old ones might be an issue if we want to maintain C API compatibility.

Comment (vtjnash) [inline src/codegen.cpp]: Julia ABI N would perhaps be the most accurate. But these are not externally visible names.

**Comment by vtjnash** [comment]
just to double-check that removing box/unbox didn't impact perf, @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18754#issuecomment-262691383) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1f4ef86dbcc5d6ce375b5920d325be8e4af1c926/b9a8c42_vs_3daa183/report.md). cc @jrevels

File: base/deprecated.jl [hunk 20]
```diff
@@ -1763,4 +1763,6 @@ export @test_approx_eq
 @deprecate(SharedArray{T}(filename::AbstractString, ::Type{T}, dims::NTuple, offset; kwargs...),
            SharedArray{T,length(dims)}(filename, dims, offset; kwargs...))
 
+is_intrinsic_expr(x::ANY) = false
```
Comment (tkelman) [inline base/deprecated.jl]: missing `depwarn`

**Comment by vtjnash** [comment]
@JeffBezanson now that jb/subtypes is merged, I think this should be ready to merge also

**Comment by tkelman** [comment]
Not without a nanosoldier run, considering how long it's been since the last one.

File: test/ccall.jl [hunk 21]
```diff
@@ -123,7 +126,11 @@ function test_struct1{Struct}(::Type{Struct})
     b = Float32(123.456)
 
     a2 = copy(a)
-    x = ccall((:test_1, libccalltest), Struct, (Struct, Float32), a2, b)
+    if Struct === Struct1
```
Comment (tkelman) [inline test/ccall.jl]: what's the reason for these splits now?

Comment (vtjnash) [inline test/ccall.jl]: The old version was taking advantage of the fact that we would usually compile a new version of the method for every input type. This PR removes that constraint from codegen so we can make it more robust.

**Comment by vtjnash** [comment]
You do realize that you could just trigger @nanosoldier `runbenchmarks(ALL, vs=":master")` yourself?

**Comment by tkelman** [comment]
right, though if this fails CI, re-running nanosoldier on an updated version takes longer

File: test/ccall.jl (hunk 21 above)
Comment (yuyichao) [inline test/ccall.jl]: Are you saying that this will be error after the pr? That'll be a big regression.

Comment (vtjnash) [inline test/ccall.jl]: In practice, it's not an issue. When I ran PkgEval, and there weren't any packages that failed due to needing this.

**Comment by vtjnash** [comment]
Usually, but with the current backlog queue on CI, I think nanosoldier might finish first 😛

File: test/ccall.jl (hunk 21 above)
Comment (yuyichao) [inline test/ccall.jl]: Is there an explicit rule about the use of type parameters in ccall?

Comment (vtjnash) [inline test/ccall.jl]: Yes. You can have them anywhere they don't affect the ABI

File: src/ccall.cpp [hunk 22]
```diff
@@ -1133,49 +1179,90 @@ static jl_cgval_t emit_llvmcall(jl_value_t **args, size_t nargs, jl_codectx_t *c
...
-        std::vector<bool> &byRefList, // vector of "byref" parameters (vararg is the last item, if applicable)
-        AttributeSet &attributes, // vector of function call site attributes (vararg is the last item, if applicable)
-        jl_value_t *rt, // julia return type
-        jl_svec_t *tt, // tuple of julia argument types
-        size_t nargs) // number of actual arguments (can be different from the size of tt when varargs)
+class function_sig_t {
+public:
+    std::vector<Type*> fargt; // vector of llvm output types (julia_struct_to_llvm) for arguments (vararg is the last item, if applicable)
+    std::vector<Type*> fargt_sig; // vector of ABI coercion types for call signature
+    std::vector<bool> fargt_isboxed; // vector of whether the llvm output types is boxed for each argument (vararg is the last item, if applicable)
```
Comment (tkelman) [inline src/ccall.cpp]: "output type is boxed" or "output types are boxed"

File: src/ccall.cpp [hunk 23]
```diff
@@ -1648,166 +1728,242 @@ static jl_cgval_t emit_ccall(jl_value_t **args, size_t nargs, jl_codectx_t *ctx)
...
+        else if (symarg.fptr != NULL) {
+            jl_error("llvmcall doesn't support static pointers");
+        }
+        else if (symarg.f_lib != NULL) {
+            jl_error("llvmcall doesn't support dynamic libraries");
+        }
+        else {
+            assert(symarg.f_name != NULL);
+            llvmf = jl_Module->getOrInsertFunction(symarg.f_name, functype);
+            if (!isa<Function>(llvmf) || cast<Function>(llvmf)->getIntrinsicID() == Intrinsic::not_intrinsic)
```
Comment (vchuravy) [inline src/ccall.cpp]: As mention by Tim in https://github.com/JuliaLang/julia/pull/18754#issuecomment-250977056 it would be nice if we could turn off the second check. Maybe a second calling convention `llvmcall_unsafe`?

File: src/ccall.cpp [hunk 24]
```diff
@@ -1648,166 +1728,242 @@ static jl_cgval_t emit_ccall(jl_value_t **args, size_t nargs, jl_codectx_t *ctx)
...
-    if (jl_ptr != NULL) {
-        null_pointer_check(jl_ptr,ctx);
-        Type *funcptype = PointerType::get(functype,0);
-        llvmf = builder.CreateIntToPtr(jl_ptr, funcptype);
+    if (llvmcall) {
+        if (symarg.jl_ptr != NULL) {
+            jl_error("llvmcall doesn't support dynamic pointers");
+        }
+        else if (symarg.fptr != NULL) {
+            jl_error("llvmcall doesn't support static pointers");
```
Comment (vchuravy) [inline src/ccall.cpp]: Currently `llvmcall` has a second form that @Keno is using for `Cxx.jl` that takes a pointer to a `llvmf`. Not something that this needs to cover, but we should keep it in mind.

**Review by vchuravy — COMMENTED** [review]
Nice! I found it easier to understand then before (especially intrinsics.cpp). Looks to me like an overall simplification and would be great to have for v0.6

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 25]
```diff
@@ -822,6 +822,20 @@ err = ccall(:gethostname, stdcall, Int32, (Ptr{UInt8}, UInt32), hn, length(hn))
 
 For more information, please see the [LLVM Language Reference](http://llvm.org/docs/LangRef.html#calling-conventions).
 
+There is one additional special calling convention `llvmcall`,
+which allows inserting calls to LLVM intrinsics directly.
+This can be especially useful when targeting unusual platforms such as GPGPUs.
+For example, for [CUDA](http://llvm.org/docs/NVPTXUsage.html), we need to be able to read the thread index::
```
Comment (tkelman) [inline doc/src/manual/calling-c-and-fortran-code.md]: the double-colon might be a leftover rst-ism?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18754#issuecomment-272979848) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/033ed8d16c5c23a442545e8ae68773f66f9f37af/02f17c8_vs_a1f232e/report.md). cc @jrevels

**Comment by tkelman** [comment]
I was just about to say I got the same assertion `jl_typeis(a, jl_array_any_type), file c:/projects/julia/src/array.c, line 1042` to fail, same as on mac travis (while running bootstrap instead of a test, but different build configurations).

File: src/ccall.cpp (hunk 24 above)
Comment (vtjnash) [inline src/ccall.cpp]: yeah, I know. It's also seems to be fundamentally incompatible with the way we manage the rest of the code pipeline, so it's low on my priority lists of things that need to work. I've written up a replacement plan at https://github.com/vtjnash/julep/wiki/0002:-Enhanced-llvmcall (which I believe should also cover Tim's case below), but waiting for someone to actually care about the implementation. Maybe that person could be you :) :) ;) :)

Comment (vchuravy) [inline src/ccall.cpp]: Right, I remember that.

 Are we planning on deprecating the current version of `llvmcall` for 1.0?
I have one example that I think still requires the current form and SIMD.jl might have issues as well.
Especially problematic is if you need to work with LLVM types that are not represented in Julia currently (e.g. `i1` and `i2`).

A long term alternative might be LLVM.jl allowing us to programmatically build up IR instead of relying on string representations.

File: src/intrinsics.cpp [hunk 26]
```diff
@@ -1040,156 +901,190 @@ static jl_cgval_t emit_intrinsic(intrinsic f, jl_value_t **args, size_t nargs,
...
+    case sub_float_fast: return math_builder(ctx, true)().CreateFSub(x, y);
+    case mul_float_fast: return math_builder(ctx, true)().CreateFMul(x, y);
+    case div_float_fast: return math_builder(ctx, true)().CreateFDiv(x, y);
+    case rem_float_fast: return math_builder(ctx, true)().CreateFRem(x, y);
     case fma_float: {
-        assert(y->getType() == x->getType());
-        assert(z->getType() == y->getType());
-        Value *fmaintr = Intrinsic::getDeclaration(jl_Module, Intrinsic::fma,
-                                   ArrayRef<Type*>(x->getType()));
+          assert(y->getType() == x->getType());
```
Comment (tkelman) [inline src/intrinsics.cpp]: indentation is off

File: src/ccall.cpp (hunk 24 above)
Comment (vtjnash) [inline src/ccall.cpp]: The above proposal should support a superset of the current implementation.

**Comment by vtjnash** [comment]
@vchuravy thanks! That's been my goal :) I think that it's much easier to express code-generation as a set of optimizations over a static implementation, rather than hoping that you can express all dynamic code-generation paths (even in the presence of a inference algorithm that can't always give you those sorts of guarantees). I know this caused you a bit of pain, since I wouldn't let you layer more optimizations on top that didn't have a static implementation.

It looks like I was missing a `jl_gc_wb` on that line.

**Comment by tkelman** [comment]
If this is at all breaking, it should have a news mention and possibly doc updates

File: test/ccall.jl (hunk 21 above)
Comment (yuyichao) [inline test/ccall.jl]: It sounds ok for now as long as it doesn't break FunctionWrappers.jl **BEFORE** the alternative is implemented.

In the long term, I think we shouldn't have such restriction as long as it's possible to do efficiently **with** codegen and possible to implement without codegen (with libffi for example). As long as it is expressible, whether or not the construct requires compiler or not shouldn't be visible functionally (i.e. it can of course affect performance). Changing the ccall API to not allow this syntactically is of course different.

Comment (vtjnash) [inline test/ccall.jl]: FunctionWrappers.jl already doesn't like the current situation (https://github.com/yuyichao/FunctionWrappers.jl/blob/master/src/FunctionWrappers.jl#L77), so it won't be affected at all. The only change this makes is that now the argument type tuple ABI must be actually statically computable from the signature of the containing function (using `@generated` qualifies for this), instead of being required to be statically computable from "whatever we could constant propagate during codegen + some semi-arbitrary heuristics".

Don't worry, this is quite non-breaking in practice. Really it's just a simplification of the rule that the argument type tuple must be a constant literal. In the future, it might even allow us to relax that constraint (changing from literal -> evaluated at the toplevel during method definition).

File: base/serialize.jl [hunk 27]
```diff
@@ -39,7 +39,7 @@ const TAGS = Any[
     :a, :b, :c, :d, :e, :f, :g, :h, :i, :j, :k, :l, :m, :n, :o,
     :p, :q, :r, :s, :t, :u, :v, :w, :x, :y, :z,
     :add_int, :sub_int, :mul_int, :add_float, :sub_float,
-    :mul_float, :unbox, :box,
+    :mul_float, :bitcast, :box,
```
Comment (JeffBezanson) [inline base/serialize.jl]: rm `box`?

Comment (vtjnash) [inline base/serialize.jl]: I'm assuming someone will change it to `reservedN` at some point or reuse it, but that keeping it in place keeps the indexing the same for `ser_version`.

File: base/inference.jl [hunk 28]
```diff
@@ -340,7 +342,95 @@ function instanceof_tfunc(t::ANY)
     end
     return Any
 end
-add_tfunc(box, 2, 2, (t,v)->instanceof_tfunc(t))
+box_tfunc(t::ANY, x::ANY) = instanceof_tfunc(t)
```
Comment (JeffBezanson) [inline base/inference.jl]: `bitcast_tfunc`?

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 29]
```diff
@@ -260,29 +269,37 @@ same:
...
-    Exactly corresponds to the `signed` type annotation in C (or any `INTEGER` type in Fortran). Any
-    Julia type that is not a subtype of `Signed` is assumed to be unsigned.
+    Exactly corresponds to the `signed` type annotation in C (or any `INTEGER` type in Fortran).
+    Any Julia type that is not a subtype of `Signed` is assumed to be unsigned.
+
+
   * `Ref{T}`
 
-    Behaves like a `Ptr{T}` that owns its memory.
+    Behaves like a ``Ptr{T}`` that can manage its memory via the Julia GC.
```
Comment (tkelman) [inline doc/src/manual/calling-c-and-fortran-code.md]: single backticks for markdown

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 30]
```diff
@@ -420,20 +437,48 @@ struct B {
...
-end
 type B
-    A::B_A
+    A::NTuple{3, CInt}
 end
-b_a_2 = B.A.(2)
+b_a_2 = B.A[2]
+```
+
+Arrays of unknown size (C99-compliant variable length structs specified by ``[]`` or ``[0]``) are not directly supported.
```
Comment (tkelman) [inline doc/src/manual/calling-c-and-fortran-code.md]: single backticks for markdown

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 31]
```diff
@@ -420,20 +437,48 @@ struct B {
...
+Often the best way to deal with these is to deal with the bytes offsets directly.
```
Comment (tkelman) [inline doc/src/manual/calling-c-and-fortran-code.md]: "byte offsets" ?

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 32]
```diff
@@ -420,20 +437,48 @@ struct B {
...
+struct String {
+    int strlen;
+    char data[];
+};
+```
+
+In Julia, we can access the parts independently to make a copy of that string:
+
 ```
+str = from-c::Ptr{Void}
```
Comment (tkelman) [inline doc/src/manual/calling-c-and-fortran-code.md]: `from_c` ? this is slightly confusing

File: base/inference.jl [hunk 33]
```diff
@@ -1431,17 +1511,47 @@ function abstract_eval(e::ANY, vtypes::VarTable, sv::InferenceState)
...
     elseif e.head === :&
         abstract_eval(e.args[1], vtypes, sv)
         t = Any
+    elseif e.head === :foreigncall
+        rt = e.args[2]
+        if isdefined(sv.linfo, :def)
+            spsig = sv.linfo.def.sig
+            if isa(spsig, UnionAll)
+                env = data_pointer_from_objref(sv.linfo.sparam_vals) + sizeof(Ptr{Void})
+                rt = ccall(:jl_instantiate_type_in_env, Any, (Any, Any, Ptr{Any}), e.args[2], spsig, env)
```
Comment (JeffBezanson) [inline base/inference.jl]: Is it worth checking for free type vars before doing this?

File: base/inference.jl [hunk 34]
```diff
@@ -2650,16 +2760,30 @@ function substitute!(e::ANY, na, argexprs, spvals, offset)
...
     end
     if isa(e, Expr)
         e = e::Expr
         head = e.head
         if head === :static_parameter
             return spvals[e.args[1]]
+        elseif head === :foreigncall
+            for i = 1:length(e.args)
+                if i == 2
+                    e.args[2] = ccall(:jl_instantiate_type_in_env, Any, (Any, Any, Ptr{Any}), e.args[2], spsig, spvals)
```
Comment (JeffBezanson) [inline base/inference.jl]: Does this mean these types only get instantiated when the code is inlined somewhere?

File: base/int.jl [hunk 35]
```diff
@@ -427,12 +423,12 @@ widen(::Type{UInt64}) = UInt128
...
-widemul(x::Unsigned,y::Signed) = signed(widen(x))*widen(y)
+widemul(x::Signed,y::Unsigned) = widen(x) * signed(widen(y))
+widemul(x::Unsigned,y::Signed) = signed(widen(x)) * widen(y)
 # multplication by Bool doesn't require widening
-widemul(x::Bool,y::Bool) = x*y
-widemul(x::Bool,y::Number) = x*y
-widemul(x::Number,y::Bool) = x*y
+widemul(x::Bool,y::Bool) = x * y
+widemul(x::Bool,y::Number) = x * y
+widemul(x::Number,y::Bool) = x * y
```
Comment (JeffBezanson) [inline base/int.jl]: I don't know if it's worth changing at this point, but the large number of whitespace-only changes in here is annoying.

File: base/serialize.jl (hunk 27 above)
Comment (JeffBezanson) [inline base/serialize.jl]: Doesn't changing `unbox` to `bitcast` also break the serialization format though?

**Review by JeffBezanson — APPROVED** [review]

File: base/serialize.jl (hunk 27 above)
Comment (vtjnash) [inline base/serialize.jl]: no idea

File: base/inference.jl (hunk 33 above)
Comment (vtjnash) [inline base/inference.jl]: Is it? I assumed that apply_type was efficient at handling that case.

File: base/inference.jl (hunk 34 above)
Comment (vtjnash) [inline base/inference.jl]: Yes
