### PR TITLE
Use safepoint to deliver SIGINT

### LINKED ISSUE #1468: Segfault when aborting matrix multiplication
I get this systematically
```
julia> mA=randn(5000,5000);mB=randn(5000,5000);

julia> mA*mB
^CSegmentation fault: 11
```
when I try to abort the computation. Julia runs in the terminal on a MacBook Pro with Mountain Lion. Shouldn't it be okay to abort a matrix multiplication like this or are crashes expected when aborting?

### LINKED ISSUE #2622: make ccall sigatomic (defer SIGINT handling)
Currently, a ctrl-c in the REPL can interrupt a `ccall` to an external library, leaving that library in an inconsistent state and producing crashes or other problems later (see e.g. [PyCall issue #15](https://github.com/stevengj/PyCall.jl/issues/15)).

Julia's C API (`julia.h`) has `SIGATOMIC` macros to protect critical code regions from being interrupted by ctrl-c (`SIGINT`), but these are not easily accessible from Julia.   

Arguably, *every* `ccall` should be made sigatomic by default, on the theory that C code in general is not interrupt-safe (with a separate `interruptable_ccall` for cases that are known to be re-entrant and interrupt-safe). Note that [Python does the same thing](http://docs.python.org/2/library/signal.html).  As noted below, the performance penalty for this is almost certainly negligible under ordinary circumstances.

### LINKED ISSUE #12309: at-atomic macro as alternative to disable_sigint()
While working on VideoIO, I was unaware of `disable_sigint`, and created a macro which disables interrupts around sections of code:

```julia
macro atomic(code)
    quote
        Base.sigatomic_begin()
        ret = ($code)
        Base.sigatomic_end()
        ret
    end
end
```

Even after discovering `disable_sigint`, I like this a little better, especially for single ccalls (or in the case of VideoIO, wrapped ccalls):

```julia
@atomic av_freep(c)  # function which wraps ccall((:av_freep,libavutil),Void,(Ptr{Void},),ptr)
```

Is there interest in having this in Base?  If so, I'll submit a PR.

Cc: @stevengj

### PR DESCRIPTION
**Pull request by yuyichao**
This implements @vtjnash 's [idea](https://github.com/JuliaLang/julia/issues/14675#issuecomment-171810732) of delivering sigint in a safer way, without having to add sigatomic to everywhere. This also solves a few performance issues along the way. A brief summary of the differences,
- Make GC safepoint thread local
  
  And create 3 signal pages. See the comment in `safepoint.c` for detail.
  This have a very minor performance hit for accessing safepoint. However, I think we can avoid the safepoint and GC transition around gcframe setup and gcframe pop on x86 so this shouldn't be a big issue. (On ARM, the atomic release store is more expensive than two GC safepoint so we may use a normal store with two safepoint instead, the performance hit of making the safepoint thread local is still very minor in this case though (~5-10% for empty GC frame push/pop, cheaper than the tls getter call....)).
- Use the GC safepoint mechanism (i.e. SegFault) to deliver InterruptException at known points
  
  This automatically makes `ccall` of external library `sigatomic`. (Fix #1468, Fix #2622). In order to avoid waiting too long before the exception is delivered when running unmanaged code, this also implement waking up libuv, abort syscall and abort libsupport io (this use a hack but can be generalized if needed) when sigint arrives. This also implement force throwing of exception if SIGINT arrives too frequently so that one can use `Ctrl-C` to force abort some dead loop. A warning will be printed in such case since it bypass the safe path and even sigatomic.
  
  The most important consequence IMHO is that pressing `Ctrl-C` during sysimg compilation should no longer segfault =)
  
  This should also make it easier to implement #14675.
- Make parser and type inference calls sigatomic
  
  sigatomic is much cheaper (see below) now so it is now used to protect important runtime code to not be interrupted by `Ctrl-C`.
- Clean up safepoint and sigatomic, optimize try-catch and `sigatomic`
  - Split out `safepoint.c`, make `defer_signal` thread local and avoid the expensive atomic ops
  - Make `defer_signal` task local and automatically restore on expection. This eliminate the try-catch needed before in `disable_sigint`.
    
    This is technically breaking but `sigatomic_begin` and `sigatomic_end` aren't exported.
  - Inline `jl_sigatomic_begin` and `jl_sigatomic_end` in codegen.
  
  Benchmarking try-catch and `disable_sigint`
  
  ``` jl
  julia> @inline f1() = try end
  f1 (generic function with 1 method)
  
  julia> @inline f2() = disable_sigint(()->nothing)
  f2 (generic function with 1 method)
  
  julia> g1(n) = for i in 1:n
             f1()
         end
  g1 (generic function with 1 method)
  
  julia> g2(n) = for i in 1:n
             f2()
         end
  g2 (generic function with 1 method)
  
  julia> function k(n)
             @time g1(n)
             @time g2(n)
         end
  k (generic function with 1 method)
  ```
  
  Timing before
  
  ``` jl
  julia> k(10_000_000)
    0.264041 seconds
    0.401437 seconds
  ```
  
  Timing after
  
  ``` jl
  julia> k(10_000_000)
    0.122592 seconds                                                                
    0.012506 seconds
  ```

Close https://github.com/JuliaLang/julia/pull/12333
Close #12309

### CODE REVIEW

File: src/julia.h [hunk 1]
```diff
@@ -1494,7 +1494,13 @@ STATIC_INLINE void jl_eh_restore_state(jl_handler_t *eh)
         locks->len = eh->locks_len;
     }
 #endif
-    JL_SIGATOMIC_END();
+    jl_get_ptls_states()->defer_signal = eh->defer_signal;
+    // This should be the last since this can trigger a safepoint
+    // that throws a SIGINT.
+    jl_gc_state_save_and_set(eh->gc_state);
+    if (eh->defer_signal == 0) {
+        jl_sigint_safepoint();
```
Comment (vtjnash) [inline src/julia.h]: i'm fairly certain we don't actually want `catch` to be a safepoint (now that it's avoidable)

Comment (yuyichao) [inline src/julia.h]: The sigint safepoint is kind of avoidable (by reenable the gc safepoint) I don't think it's valid to avoid the GC safepoint in the gc state restore though.

File: src/julia_internal.h [hunk 2]
```diff
@@ -264,10 +265,63 @@ void jl_set_base_ctx(char *__stk);
 void jl_init_threading(void);
 void jl_start_threads(void);
 void jl_shutdown_threading(void);
+
+// Whether the GC is running
+extern char *jl_safepoint_pages;
+static inline int jl_addr_is_safepoint(uintptr_t addr)
```
Comment (tkelman) [inline src/julia_internal.h]: `STATIC_INLINE`

Comment (yuyichao) [inline src/julia_internal.h]: What configuration doesn't support `static inline`? It seems that MSVC should be fine with it in c++ mode?

File: src/julia.h (hunk 1 above)
Comment (vtjnash) [inline src/julia.h]: that's fine. i just don't think we want to throw an InterruptException before the catch block has a chance to install a try/catch of its own.

File: src/julia_internal.h (hunk 2 above)
Comment (tkelman) [inline src/julia_internal.h]: we won't always need to compile in c++ mode

File: src/signals-unix.c [hunk 3]
```diff
@@ -131,72 +140,80 @@ static void allocate_segv_handler(void)
...
 #endif
 
         pthread_mutex_lock(&in_signal_lock);
-        wait_barrier();
+        pthread_cond_broadcast(&signal_caught_cond);
         pthread_cond_wait(&exit_signal_cond, &in_signal_lock);
-        wait_barrier();
+        request = jl_atomic_exchange(&ptls->signal_request, 0);
+        assert(request == 1);
+        if (request)
```
Comment (vtjnash) [inline src/signals-unix.c]: assert & conditional seems like an odd pair?

File: src/julia.h (hunk 1 above)
Comment (yuyichao) [inline src/julia.h]: We can't really provide the grantee that an async signal will not be thrown between a `catch` and a `try` though, unless we garentee it can only be compiled and not interpreted. The GC safepoint can also throw the exception even when there's not a sigint safepoint.

File: src/signals-unix.c [hunk 4]
```diff
@@ -131,72 +140,80 @@ static void allocate_segv_handler(void)
...
+    else if (request == 2) {
+        jl_unblock_signal(sig);
+        int force = jl_check_force_sigint();
+        if (force || (!ptls->defer_signal && ptls->io_wait)) {
+            jl_safepoint_consume_sigint();
+            if (force)
+                jl_safe_printf("WARNING: Force throwing a SIGINT\n");
+            // Force a throw
+            jl_clear_force_sigint();
+            jl_throw(jl_interrupt_exception);
```
Comment (vtjnash) [inline src/signals-unix.c]: maybe add a TODO to replace this with `jl_throw_in_ctx` (after writing said function)

File: src/task.c [hunk 5]
```diff
@@ -318,6 +318,8 @@ static void ctx_switch(jl_task_t *t, jl_jmp_buf *where)
             arraylist_new(locks, 0);
         }
 #endif
```
Comment (vtjnash) [inline src/task.c]: i think FIXME comment at the top of this function can be removed now?

**Comment by stevengj** [comment]
Suppose I have a `ccall` with a Julia callback function, e.g. `ccall(:my_numeric_integration, Cdouble, (Ptr{Void},), cfunction(my_julia_integrand, ...))`.    If I send a SIGINT while this is executing, does this mean that it will not interrupt the C code, but an `InterruptException` will still occur during the `my_julia_integrand` execution?

Also, if you have multiple `Task`s running, is there any way to indicate which `Task` you want to catch the exception?

**Comment by yuyichao** [comment]
A callback can still throw exception so sigatomic_begin/end are still useful. I made it fast because of this...

The sigint is always delivered to current task on the master thread if it doesn't block sigint (I realized that I might have missed a pending sigint check there, similar to the one in en_restore_state). However, you can block the sigint on the task you don't want it to be delivered by calling sigatomic_begin, is this good enough?

**Comment by stevengj** [comment]
I'm still confused by the callback situation in this PR.  If I *want* `InterruptExceptions` to be thrown during my callback (e.g. I have a `try-catch` block that handles them correctly), do I need to call `sigatomic_end/begin` in my callback?

**Comment by yuyichao** [comment]
For julia callback from C, I think a much faster sigatomic is as far as what this approach can provide.

For the task issue, I'm wondering if we can make non-root tasks sigatomic by default? This way any frontend will need to explicitly reenable sigint on tasks that want to handle sigint.

**Comment by yuyichao** [comment]
> (e.g. I have a try-catch block that handles them correctly), do I need to call sigatomic_end/begin in my callback?

A sigint can be delivered in the callback if the C caller wasn't called in sigatomic region. It is a little unreliably though since in principle a sigint can be delivered before the try block starts so I think to do this reliably you need to call the C function with sigatomic and reenable sigatomic in the callback after you started the try block.

**Comment by stevengj** [comment]
I'm not sure if non-root tasks should be sigatomic by default.  But it would be nice to have an option to make the task sigatomic when it is created.  e.g. `@async_nosigint`

I'm not sure how calling `sigatomic_begin/end` will help in Tasks, right now.  The problem is that `sigatomic_end` is still called within the Task, and as soon as it is called any deferred SIGINT will be thrown as an exception in that Task.  What if I don't want that Task to get `InterruptExceptions` at all?

**Comment by stevengj** [comment]
> you need to call the C function with sigatomic and reenable sigatomic in the callback after you started the try block.

Yes, that's what I'm doing now.

**Comment by yuyichao** [comment]
You can call sigatomic_begin without calling end to permanently block sigint on a task. Doing that at initialization time is also possible since I accidentally made defer_signal a property of the task (instead of just save it on the stack on task switch....)

File: src/julia_internal.h (hunk 2 above)
Comment (yuyichao) [inline src/julia_internal.h]: I fixed this one. However, there are a lot of threading utils that relies on c++ when compiled with MSVC. Alternative would be using C11 generic macro, which I think is even less likely going to be supported by MSVC....

File: src/signals-unix.c (hunk 3 above)
Comment (yuyichao) [inline src/signals-unix.c]: Fixed. I think the two was added at different point and I didn't remove them in rebase/squash...

File: src/signals-unix.c (hunk 4 above)
Comment (yuyichao) [inline src/signals-unix.c]: TODO with `Jameson` attached added =)

File: src/task.c (hunk 5 above)
Comment (yuyichao) [inline src/task.c]: Done.

**Comment by vtjnash** [comment]
What is the sigatomic state of a new Task? e.g.
```julia
sigatomic_begin()
@async println("am I sigatomic?")
sigatomic_end()
yield()
```

**Comment by stevengj** [comment]
@yuyichao, `sigatomic_begin()` will only block SIGINT on the current task?  I thought it increments `jl_defer_signal`, which is global to all tasks?

**Comment by yuyichao** [comment]
sigatomic is now thread and task local. New task currently (on this branch) inherit the state from when it's started... since I haven't set fix start_task for this yet...

**Comment by yuyichao** [comment]
Travis linux32 failure is https://github.com/JuliaLang/julia/issues/15920

File: src/gc.c [hunk 6]
```diff
@@ -354,95 +355,26 @@ NOINLINE static uintptr_t gc_get_stack_ptr(void)
...
-}
-
 static void jl_gc_wait_for_the_world(void)
 {
     for (int i = 0;i < jl_n_threads;i++) {
         jl_tls_states_t *ptls = jl_all_task_states[i].ptls;
-        while (!ptls->gc_state) {
+        // FIXME: The acquire load pairs with the release store
+        // in the signal handler of safepoint so we are sure that
+        // all the memory write on those threads are visible. However,
```
Comment (tkelman) [inline src/gc.c]: memory writes? memory written ... is?

Comment (yuyichao) [inline src/gc.c]: Maybe `store` is the right word?

File: test/core.jl [hunk 7]
```diff
@@ -2142,13 +2142,24 @@ end
...
-        Libc.systemsleep(0.2) # wait for SIGINT to arrive
+        for i in 1:10
+            Libc.systemsleep(0.1)
+            ccall(:jl_gc_safepoint, Void, ()) # wait for SIGINT to arrive
+        end
     end
     ccall(:jl_exit_on_sigint, Void, (Cint,), 1)
 end
+let
+    # Exception frame automatically restore sigatomic counter.
```
Comment (tkelman) [inline test/core.jl]: restores?

**Comment by yuyichao** [comment]
Spelling mistakes fixed. Threading CI passed [AppVeyor](https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.1224), [travis](https://travis-ci.org/JuliaLang/julia/builds/128043719). This should be ready for final review now.

**Comment by stevengj** [comment]
It seems like the documentation of the `sigatomic` functions should be revisited.  (I'd also like to see documentation of how to catch ctrl-c in callback functions, disable ctrl-c in certain tasks, etcetera.)

File: src/signal-handling.c [hunk 8]
```diff
@@ -23,11 +23,35 @@ static const    uint64_t GIGA = 1000000000ULL;
...
+    static double accum_weight = 0;
+    uint64_t cur_time = uv_hrtime();
+    uint64_t dt = cur_time - jl_last_sigint_trigger;
+    uint64_t last_t = jl_last_sigint_trigger;
+    jl_last_sigint_trigger = cur_time;
+    if (last_t == 0) {
+        accum_weight = 0;
+        return 0;
+    }
+    double new_weight = accum_weight * exp(-(dt / 1e9)) + 0.3;
```
Comment (JeffBezanson) [inline src/signal-handling.c]: Clearly written by a physicist :)

**Comment by yuyichao** [comment]
I've also noticed one case where `Ctrl-C` can still segfault. It is when we throw the error without any handler, and the execution of `on_exit` overflows the signal handler stack..... (at least on linux where we throw directly from the signal handler frame). A easy fix would be setting up a top level try catch frame at initialization time. The alternative would be to return to a call to `jl_throw` from the signal handler instead. However, it seems that `setcontext` or `makecontext` using a signal context might be undefined....

File: src/ast.c [hunk 9]
```diff
@@ -267,6 +268,7 @@ static jl_ast_context_t *jl_ast_ctx_enter(void)
 
 static void jl_ast_ctx_leave(jl_ast_context_t *ctx)
 {
+    JL_SIGATOMIC_END();
```
Comment (JeffBezanson) [inline src/ast.c]: This breaks `--lisp`; segfaults.

Comment (yuyichao) [inline src/ast.c]: Ah... ok.... will fix later today....

Comment (yuyichao) [inline src/ast.c]: And in case you need it now, I think making jl_sigint_safepoint noop should work around it for now

Comment (yuyichao) [inline src/ast.c]: Fixed in https://github.com/JuliaLang/julia/commit/417e49aae87222d96df6125b188686da39a9bc80

Comment (tkelman) [inline src/ast.c]: should be tested if breaking it matters

Comment (yuyichao) [inline src/ast.c]: `` run(pipeline(DevNull, `$(Base.julia_cmd()) --lisp`, DevNull)) `` ?

Comment (tkelman) [inline src/ast.c]: something like that. might need to be unix only, would need to run it through CI first

**Comment by tkelman** [comment]
This PR broke the Windows buildbots: https://build.julialang.org/builders/package_win6.2-x64/builds/247/steps/make/logs/stdio

Similar to #11727, but now bootstrap freezes when output is redirected instead of just being unable to run tests. @vtjnash @yuyichao please advise, we'll have to revert this if no solution can be found.

**Comment by yuyichao** [comment]
The only commit that touches libuv is the last one and reverting it seems to get rid of the problem for me locally (tested by piping it through `tee`) I'm checking now if what is the minimum change that triggers this now...

**Comment by yuyichao** [comment]
Something is fishy here. The buildbot seems to have been printing `jl_uv_writecb` warnings forever during compilation http://buildbot.e.ip.saba.us:8010/builders/package_win6.2-x64/builds/245/steps/make/logs/stdio The freezing happens on current master after printing the first warning. However, either with or without the commit reverted, the build passes without printing any warnings if `inference.ji` exists before I run make. (i.e. if I run make again after it freezes, the build passes without any warning).

**Comment by vtjnash** [comment]
If you follow that issue, you'll discover it's an upstream bug where libuv forgot to initialize the synchronization object. I think it then corrupts its internal state and tries to report an error that didn't happen by forgetting about a write req that did happen.

**Comment by yuyichao** [comment]
> If you follow that issue

Which issue? I didn't see any mentioning of synchronization object in #11727?

**Comment by vtjnash** [comment]
you have to follow it somewhat far. there's a more concise explanation at https://github.com/libuv/libuv/issues/629, in which I demonstrate how it would make nodejs to hang (for the same reason) in a one-liner.

**Comment by yuyichao** [comment]
Ah, that one, I somehow think you are talking about `uv_async_t` since apparently simply initializing (not even using it) one is causing the trouble on windows......

**Comment by tkelman** [comment]
I think this broke the arm build too: https://build.julialang.org/builders/package_tarballarm/builds/227/steps/make%20binary-dist/logs/stdio

**Comment by yuyichao** [comment]
I believe it's caused by a llvm bug (probably similar to https://llvm.org/bugs/show_bug.cgi?id=27545) easy to workaround by removing an optimization, need to first check if it's fixed on llvm svn...
