### PR TITLE
[REPLCompletions] fix #52099 by adjusting effects of `HAMT` methods

### LINKED ISSUE #52099: `UndefRefError` due to line completion in REPL
```julia
julia> versioninfo()
Julia Version 1.11.0-DEV.851
Commit fae6b7859b (2023-11-06 15:34 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i7-1255U
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, alderlake)
  Threads: 1 on 12 virtual cores
```

To trigger, type:
```julia
julia> x = []

julia> Base.PersistentDict(x => 3.0)[
```

You will be presented with a large stacktrace:
```julia
│   exception =
│    UndefRefError: access to undefined reference
│    Stacktrace:
│      [1] getindex
│        @ Base ./essentials.jl:791 [inlined]
│      [2] (::Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}})(i::Int64)
│        @ Base.HashArrayMappedTries ./none:0
│      [3] (::Base.MappingRF{Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}}, Base.BottomRF{typeof(Base.add_sum)}})(acc::Int64, x::Int64)
│        @ Base ./reduce.jl:100
│      [4] _foldl_impl(op::Base.MappingRF{Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}}, Base.BottomRF{typeof(Base.add_sum)}}, init::Int64, itr::Base.OneTo{Int64})
│        @ Base ./reduce.jl:58
│      [5] foldl_impl(op::Base.MappingRF{Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}}, Base.BottomRF{typeof(Base.add_sum)}}, nt::Int64, itr::Base.OneTo{Int64})
│        @ Base ./reduce.jl:48
│      [6] mapfoldl_impl(f::typeof(identity), op::typeof(Base.add_sum), nt::Int64, itr::Base.Generator{Base.OneTo{Int64}, Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}}})
│        @ Base ./reduce.jl:44
│      [7] mapfoldl(f::Function, op::Function, itr::Base.Generator{Base.OneTo{Int64}, Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}}}; init::Int64)
│        @ Base ./reduce.jl:175
│      [8] mapfoldl
│        @ Base ./reduce.jl:175 [inlined]
│      [9] mapreduce
│        @ Base ./reduce.jl:307 [inlined]
│     [10] #sum#322
│        @ Base ./reduce.jl:535 [inlined]
│     [11] sum(a::Base.Generator{Base.OneTo{Int64}, Base.HashArrayMappedTries.var"#1#2"{Base.HashArrayMappedTries.HAMT{Vector{Any}, Float64}}}; kw::@Kwargs{init::Int64})
│        @ Base ./reduce.jl:564
│     [12] length
│        @ Base.HashArrayMappedTries ./hamt.jl:225 [inlined]
│     [13] length(dict::Base.PersistentDict{Vector{Any}, Float64})
│        @ Base ./dict.jl:1031
│     [14] dict_identifier_key(str::String, tag::Symbol, context_module::Module)
│        @ REPL.REPLCompletions ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:903
│     [15] completions(string::String, pos::Int64, context_module::Module, shift::Bool)
│        @ REPL.REPLCompletions ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:1114
│     [16] complete_line(c::REPL.REPLCompletionProvider, s::REPL.LineEdit.PromptState, mod::Module)
│        @ REPL ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:560
│     [17] check_for_hint(s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:384
│     [18] (::REPL.LineEdit.var"#139#195")(s::REPL.LineEdit.MIState, data::Any, c::Union{Char, SubString{String}, String})
│        @ REPL.LineEdit ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2494
│     [19] #invokelatest#2
│        @ Base ./essentials.jl:929 [inlined]
│     [20] invokelatest
│        @ Base ./essentials.jl:926 [inlined]
│     [21] (::REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#139#195", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:1678
│     [22] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2815
│     [23] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2717
│     [24] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1352
│     [25] (::REPL.var"#64#70"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:401
└ @ REPL.LineEdit ~/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2817
```

### PR DESCRIPTION
**Pull request by aviatesk**
After looking into #52099, I discovered that it has the same root cause as #51548. Essentially, when a method that's not `!effect_free` is applied to a `Const` value concretized by the `REPLInterpreter`'s aggressive inference, since the `!effect_free` method will not be concretized, it will eventually lead to the `Const` representing unexpected object being returned.

This commit tries to fix the specific problem reported in #52099 by enhancing the effects of `Base.HAMT` methods, so they're concrete-evaled.

Admittedly, this is more of a quick fix than a complete solution, and not the best one, but it was the simplest. A better solution might involve implementing EA's handling of `Memory`-objects that allows the compiler to automatically prove `:effect_free` in more scenarios. But this would need a bigger overhaul, so I plan to tackle it in another PR.

### CODE REVIEW

**Comment by Keno** [comment]
Ok, but the REPL should really not be running concrete code on speculatively obtained values.

**Comment by oscardssmith** [comment]
@Keno isn't this fine as long as the code is effect free and no-ub?

File: base/hamt.jl [hunk 1]
```diff
@@ -66,14 +66,14 @@ mutable struct HAMT{K, V}
...
+    # For a single element we can't have a 'hash-collision
     trie = HAMT{K,V}(Vector{Union{Leaf{K, V}, HAMT{K, V}}}(undef, 1), zero(BITMAP))
     trie.data[1] = Leaf{K,V}(k,v)
     return trie
 end
 
-function HAMT{K,V}((k,v)::Pair) where {K, V}
+Base.@assume_effects :effect_free function HAMT{K,V}((k,v)::Pair) where {K, V}
     k = convert(K, k)
     v = convert(V, v)
```
Comment (vtjnash) [inline base/hamt.jl:78]: Seems fairly sketchy to assert that these convert calls are effect_free

**Comment by aviatesk** [comment]
> Ok, but the REPL should really not be running concrete code on speculatively obtained values.

That could be true. More specifically, we need to avoid unsafe concrete evaluations if there's a risk of `!effect_free` operations being applied to speculatively-concretized objects. This would require some kind of escape/taint analysis, but considering the persistence of these issues, it might be time to seriously tackle this problem.

File: base/hamt.jl (hunk 1 above)
Comment (aviatesk) [reply base/hamt.jl]: Addressed by isolating unsafe cases into a separate function.
