### PR TITLE
inference: propagate variable changes to all exception frames

### LINKED ISSUE #42022: Variable update not reflected outside nested `try` blocks
Minimal example:

```julia
assertstring(::AbstractString) = nothing

function test_trytry()
    x = nothing
    try
        try
            x = "/"
            assertstring(x)
            error("err")
        catch
            rethrow()
        end
    catch
    end
    assertstring(x)
end

test_trytry()
```

throws

```
ERROR: LoadError: MethodError: no method matching assertstring(::Nothing)
```

As a sanity check, using `Ref` instead of a slot works:

```julia
function test_trytry_ref()
    x = Ref{Any}(nothing)
    try
        try
            x[] = "/"
            assertstring(x[])
            error("err")
        catch
            rethrow()
        end
    catch
    end
    assertstring(x[])
end

test_trytry_ref()  # no error
```

Looking at `@code_typed optimize=false test_trytry()`:

```
CodeInfo(
1 ─      (x = Main.nothing)::Core.Const(nothing)
2 ─ %2 = $(Expr(:enter, #7))
3 ─      $(Expr(:enter, #5))
4 ─      (x = "/")::Core.Const("/")
│        Main.assertstring(x::Core.Const("/"))::Any
│        Main.error("err")::Union{}
│        Core.Const(:($(Expr(:leave, 1))))::Union{}
└──      Core.Const(:(goto %12))::Union{}
5 ┄      $(Expr(:leave, 1))
6 ─      Main.rethrow()::Union{}
│        Core.Const(:($(Expr(:pop_exception, :(%3)))))::Union{}
│        Core.Const(:($(Expr(:leave, 1))))::Union{}
└──      Core.Const(:(goto %16))::Union{}
7 ┄      $(Expr(:leave, 1))
8 ─      $(Expr(:pop_exception, :(%2)))::Any
│        Main.assertstring(x::Core.Const(nothing))::Union{}
└──      Core.Const(:(return %16))::Union{}
) => Union{}
```

Note `Main.assertstring(x::Core.Const(nothing))::Union{}` in BB 8. Does this indicate that there are some problems in the inference?

### PR DESCRIPTION
**Pull request by vtjnash**
Switch to precomputing the handler_at for each statement, instead of copying around a linked list for more efficiency, and chain backwards on that linked list to update all places the exception might get thrown to.

Fix #42022

### CODE REVIEW

File: test/compiler/inference.jl [hunk 1]
```diff
@@ -3428,3 +3428,48 @@ end
...
+                x = '3'
+                y ? (return 1) : throw()
+            catch ex1
+                rethrow()
+            end
+        catch ex2
+            nothing
+        end
+        return x
+    end) === Union{Int64, Float64, Char}
```
Comment (vtjnash) [inline test/compiler/inference.jl:3475]:
```suggestion
    end) === Union{Int, Float64, Char}
```

File: test/compiler/inference.jl [hunk 2]
```diff
@@ -3428,3 +3428,48 @@ end
...
+        Core.GotoNode(22)
+        Expr(:leave, 1)
+        Expr(:(=), Core.SlotNumber(5), Expr(:the_exception))
+        nothing
+        Expr(:pop_exception, Core.SSAValue(2))
+        Core.ReturnNode(Core.SlotNumber(3))
+    ]
+    handler_at = Core.Compiler.compute_trycatch(x, Core.Compiler.BitSet())
+    @test handler_at == [0, 0, 2, 2, 4, 4, 4, 0, 4, 4, 2, 4, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0]
+end
```
Comment (aviatesk) [inline test/compiler/inference.jl:3459]:
```suggestion
let x = Tuple{Int,Any}[
        #= 1=# (0, Expr(:(=), Core.SlotNumber(3), 1))
        #= 2=# (0, Expr(:enter, 18))
        #= 3=# (2, Expr(:(=), Core.SlotNumber(3), 2.0))
        #= 4=# (2, Expr(:enter, 12))
        #= 5=# (4, Expr(:(=), Core.SlotNumber(3), '3'))
        #= 6=# (4, Core.GotoIfNot(Core.SlotNumber(2), 9))
        #= 7=# (4, Expr(:leave, 2))
        #= 8=# (0, Core.ReturnNode(1))
        #= 9=# (4, Expr(:call, GlobalRef(Main, :throw)))
        #=10=# (4, Expr(:leave, 1))
        #=11=# (2, Core.GotoNode(16))
        #=12=# (4, Expr(:leave, 1))
        #=13=# (2, Expr(:(=), Core.SlotNumber(4), Expr(:the_exception)))
        #=14=# (2, Expr(:call, GlobalRef(Main, :rethrow)))
        #=15=# (2, Expr(:pop_exception, Core.SSAValue(4)))
        #=16=# (2, Expr(:leave, 1))
        #=17=# (0, Core.GotoNode(22))
        #=18=# (2, Expr(:leave, 1))
        #=19=# (0, Expr(:(=), Core.SlotNumber(5), Expr(:the_exception)))
        #=20=# (0, nothing)
        #=21=# (0, Expr(:pop_exception, Core.SSAValue(2)))
        #=22=# (0, Core.ReturnNode(Core.SlotNumber(3)))
    ]
    handler_at = Core.Compiler.compute_trycatch(last.(x), Core.Compiler.BitSet())
    @test handler_at == first.(x)
end
```

File: base/compiler/abstractinterpretation.jl [hunk 3]
```diff
@@ -1925,16 +1916,21 @@ function typeinf_local(interp::AbstractInterpreter, frame::InferenceState)
...
-                    if stupdate1!(states[l]::VarTable, changes::StateUpdate) !== false
-                        if l < frame.pc´´
-                            frame.pc´´ = l
+                cur_hand = frame.handler_at[pc]
+                if isa(changes, StateUpdate)
+                    while cur_hand != 0
+                        let l = frame.handler_at[cur_hand + 1]
+                            # propagate new type info to exception handler
+                            # the handling for Expr(:enter) propagates all changes from before the try/catch
+                            # so this only needs to propagate any changes
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:1925]:
```suggestion
                            # propagate new type info to exception handler by stacking changes on Expr(:enter)
                            # the handling for Expr(:enter) will then propagate all changes from the try/catch
                            # so this only needs to propagate any changes here
```

File: base/compiler/inferencestate.jl [hunk 4]
```diff
@@ -28,9 +28,7 @@ mutable struct InferenceState
     pc´´::LineNum
     nstmts::Int
     # current exception handler info
-    cur_hand #::Union{Nothing, Pair{LineNum, prev_handler}}
-    handler_at::Vector{Any}
-    n_handlers::Int
+    handler_at::Vector{LineNum}
```
Comment (aviatesk) [inline base/compiler/inferencestate.jl:31]: I think "handler_at" naming is actually a bit confusing ? To me "entered_at" sounds more reasonable ("handler" usually mean `catch` clause ... ?).

File: base/compiler/abstractinterpretation.jl [hunk 5]
```diff
@@ -1925,16 +1916,21 @@ function typeinf_local(interp::AbstractInterpreter, frame::InferenceState)
...
+                            if stupdate1!(states[l]::VarTable, changes::StateUpdate) !== false
+                                if l < frame.pc´´
+                                    frame.pc´´ = l
+                                end
+                                push!(W, l)
+                            end
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:1931]: Well, why do we want to propagate changes via `:enter` ? Can't we propagate changes directly to `:leave` statements here ?

**Review by aviatesk — COMMENTED** [review]
I like this changes. The code looks much cleaner and easier to reason about.

File: base/compiler/abstractinterpretation.jl (hunk 5 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1931]: The `l` value here is short for `:leave` (strictly speaking, it doesn't have to be a :leave, but it normally will be)

File: base/compiler/inferencestate.jl (hunk 4 above)
Comment (vtjnash) [reply base/compiler/inferencestate.jl:31]: I think it is the same to say it is handled by the `try` statement. The `catch` / `leave` is where we stop handling errors (which is why it is simpler to point to the `try` statement also, since we have more information there)

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1925]: no, this doesn't describe the algorithm

File: base/compiler/abstractinterpretation.jl (hunk 5 above)
Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:1931]: `frame.src.code[l]` is supposed to be `:enter` expression always, no ?
My understanding is that the algorithm accumulates all changes within `try/catch` clauses to `:enter` expression's states, and then `:enter` will propagate the changes to `:leave`.

So I wonder why we don't want to do:
```julia
if isa(changes, StateUpdate)
    while cur_hand != 0
        let l = frame.handler_at[cur_hand + 1]
            # propagate new type info to exception handler
            enter = frame.src.code[l]
            @assert isexpr(enter, :enter)
            leavestate = states[enter.args[1]::Int]::VarTable
            stupdate1!(leavestate, changes::StateUpdate) !== false
        end
        cur_hand = frame.handler_at[cur_hand]
    end
end
```

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1931]: Because `l` is almost always a `:leave` expr there

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1931]: oh, or was supposed to be, until I rearranged the code, and then it wasn't anymore

**Review by aviatesk — APPROVED** [review]

**Comment by KristofferC** [comment]
This has quite a few merge conflicts with 1.6 so would need a rebase somewhere that can be cherry picked

**Comment by aviatesk** [comment]
Directly cherry-picking this PR on the backport branch is an option ? I think I can take it.

**Comment by KristofferC** [comment]
> Directly cherry-picking this PR on the backport branch is an option ?

Yes.

**Comment by vtjnash** [comment]
@aviatesk when merging, please check that the commit message is also correct. Fixup should never appear, for example.

**Comment by aviatesk** [comment]
So the commit message of this merge commit should be like:
```
inference: propagate variable changes to all exception frames (#42081)

Fix #42022

Co-authored-by: Shuhei Kadowaki <40514306+aviatesk@users.noreply.github.com>
```

?

**Comment by vtjnash** [comment]
Yes, though I am not sure you want to claim co-authorship, since you are already claiming the reviewer, and it would imply you are claiming ownership of the content also.
