### PR TITLE
Fix reuse of client port on Linux. Implement for OSX.

### LINKED ISSUE #19893: Enable SO_REUSEPORT for OSX.
Creating an issue so that this work is tracked.

We can now enable SO_REUSEPORT on OSX. This required us to get early access to the socket in libuv which has now become available in our fork.

Ref : https://github.com/JuliaLang/julia/pull/12158

### PR DESCRIPTION
**Pull request by amitmurthy**
Closes https://github.com/JuliaLang/julia/issues/19893 .

`ci skip` till https://github.com/JuliaLang/julia/pull/21799 is merged.

This commit should backport cleanly. Will add another commit that uses `getsockname` everywhere once https://github.com/JuliaLang/julia/issues/21801 is closed.

### CODE REVIEW

File: base/socket.jl [hunk 1]
```diff
@@ -282,10 +282,17 @@ mutable struct TCPSocket <: LibuvStream
         return tcp
     end
 end
-function TCPSocket()
+function TCPSocket(; delay=true)  # kw arg "delay": if true, libuv delays creation of the socket
+                                  # fd till the first bind call
+
```
Comment (tkelman) [inline base/socket.jl]: could we avoid starting the function with an empty line? it's not the usual formatting style

File: base/distributed/cluster.jl [hunk 2]
```diff
@@ -153,8 +153,16 @@ function start_worker(out::IO, cookie::AbstractString)
     init_worker(cookie)
     interface = IPv4(LPROC.bind_addr)
     if LPROC.bind_port == 0
-        (actual_port,sock) = listenany(interface, UInt16(9009))
-        LPROC.bind_port = actual_port
+#        (actual_port,sock) = listenany(interface, UInt16(9009))
```
Comment (amitmurthy) [inline base/distributed/cluster.jl]: When testing this PR, i.e., reusing client port numbers, our current strategy for workers to start listening for a free port starting from 9009 caused a major slowdown in `addprocs` when it was part of a repeated `addprocs(x); run tests....; rmprocs(workers)` cycle - as the test script indeed does.  I suspect it was because the new workers listened on the same ports (starting from 9009), but setup of new connections with the same client port were being delayed, as TCP connections to previous workers (now in a TIME_WAIT state) still existed. And new connections with the same (clienthostport,serverhostport) tuple had to wait till the system cleaned them up (OSX in my case).

I changed the worker listening port selection logic to select a free ephemeral port and the slowdown disappeared. While that works, I am uncomfortable using ephemeral ports for workers to listen on as firewalling policies may disallow incoming connections to the ephemeral port range.

However, the current strategy of listening on a free port starting from 9009 is also not ideal when we have many workers on a node. For example, the 100th worker in an `addprocs(100)` will try and fail in listening on every port between 9009 and 9108 before succeeding to listen on 9109.

Looking for suggestions to work around this issue.

File: base/distributed/managers.jl [hunk 3]
```diff
@@ -455,31 +455,36 @@ end
...
             if rc > 0  # SO_REUSEPORT is unsupported, just return the ephemerally bound socket
                 return s
             elseif rc < 0
                 throw(SystemError("setsockopt() SO_REUSEPORT : "))
             end
-            getsockname(s)
+            is_apple() && bind_client_port(s)
         catch e
             # This is an issue only on systems with lots of client connections, hence delay the warning
             nworkers() > 128 && warn_once("Error trying to reuse client port number, falling back to plain socket : ", e)
```
Comment (vtjnash) [inline base/distributed/managers.jl]: why is this done as a try/catch rather than printing this message where we through it 6 lines above and then returning from there

File: base/socket.jl [hunk 4]
```diff
@@ -282,10 +282,17 @@ mutable struct TCPSocket <: LibuvStream
...
     tcp = TCPSocket(Libc.malloc(_sizeof_uv_tcp), StatusUninit)
-    err = ccall(:uv_tcp_init, Cint, (Ptr{Void}, Ptr{Void}),
-                eventloop(), tcp.handle)
+    if delay
+        err = ccall(:uv_tcp_init, Cint, (Ptr{Void}, Ptr{Void}),
+                    eventloop(), tcp.handle)
+    else
+        err = ccall(:uv_tcp_init_ex, Cint, (Ptr{Void}, Ptr{Void}, Cuint),
+                    eventloop(), tcp.handle, 2) # AF_INET is 2
+    end
```
Comment (vtjnash) [inline base/socket.jl]: I think you can call the `_ex` version unconditionally, and just select between `AF_INET = 2` and `AF_UNSPEC = 0` (that's what libuv will do internally anyways)

**Review by vtjnash — APPROVED** [review]

File: base/distributed/cluster.jl (hunk 2 above)
Comment (vtjnash) [inline base/distributed/cluster.jl]: Maybe we can suggest that someone who needs that will write a UPnP package that automates the firewall configuration step? Although I think that the typical usage of this cluster code is intended to be in a closed environment where all of the devices are on the same side of the firewall (whether virtually or physically).

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
Looks like this will be a bit better after https://github.com/JuliaLang/julia/issues/21801 is merged too.

File: base/distributed/cluster.jl [hunk 5]
```diff
@@ -153,8 +153,15 @@ function start_worker(out::IO, cookie::AbstractString)
...
-        (actual_port,sock) = listenany(interface, UInt16(9009))
-        LPROC.bind_port = actual_port
+        addr = Base.InetAddr(interface, 0)
+        sock = Base.TCPServer()
+        if bind(sock, addr) && Base.trylisten(sock) == 0
+            _addr, port = Base._sockname(sock, true)
+            LPROC.bind_port = port
+        else
+            close(sock)
+            error("no ports available")
```
Comment (tkelman) [inline base/distributed/cluster.jl]: should throw a more specific exception type if possible

**Comment by amitmurthy** [comment]
Added a NEWS entry. Will this fix make 0.6? Should it be in the 0.6 section?

**Comment by amitmurthy** [comment]
AV failure is unrelated.

**Comment by amitmurthy** [comment]
Will merge this in a day.

**Comment by tkelman** [comment]
This is failing tests on the buildbots. https://build.julialang.org/builders/build_ubuntu14.04-x64/builds/366/steps/shell_2/logs/stdio
