### PR TITLE
Fix layout of REPL completions with newlines

### LINKED ISSUE #45836: [REPL] broken tab completion layout for methods
```
julia> include(<tab>
include(mapexpr::Function, fname::AbstractString)
     @ Base.MainInclude client.jl:469                                                    include(fname::AbstractString)
     @ Base.MainInclude client.jl:470
```

expected (from v1.8):
```
julia> include(<tab>
include(mapexpr::Function, fname::AbstractString) in Base.MainInclude at client.jl:473  include(fname::AbstractString) in Base.MainInclude at client.jl:474
```

### PR DESCRIPTION
**Pull request by Liozou**
Fix #45836 by forcing REPL completions that include a newline to print on a single column.

The behaviour on this PR is like for a small terminal:
```julia
julia> include(<tab>
include(mapexpr::Function, fname::AbstractString)
     @ Base.MainInclude client.jl:469
include(fname::AbstractString)
     @ Base.MainInclude client.jl:470
```

I didn't know how to test this so feel free to comment if you think the test can be improved.

### CODE REVIEW

File: stdlib/REPL/src/LineEdit.jl [hunk 1]
```diff
@@ -322,7 +322,7 @@ end
 
 # Show available completions
 function show_completions(s::PromptState, completions::Vector{String})
-    colmax = maximum(map(length, completions))
+    colmax = occursin('\n', first(completions)) ? width(terminal(s))-2 : maximum(map(length, completions))
     num_cols = max(div(width(terminal(s)), colmax+2), 1)
```
Comment (vtjnash) [inline stdlib/REPL/src/LineEdit.jl:326]:
```suggestion
    if any(occursin('\n'), completions)
        foreach(println, completions)
        return
    end
    colmax = maximum(length, completions) # n.b. length >= textwidth
    num_cols = max(div(width(terminal(s)), colmax+2), 1)
```

Comment (vtjnash) [reply stdlib/REPL/src/LineEdit.jl:326]: I think it might be more reliable to check all input lines, and then entirely bypass the extra logic

Comment (Liozou) [reply stdlib/REPL/src/LineEdit.jl]: Sure! Thanks for the snippet, I took your idea with did minor edits.

**Comment by Liozou** [comment]
CI failure looks like https://github.com/JuliaLang/julia/issues/45310 and https://github.com/JuliaLang/julia/issues/45981, which should be unrelated.

**Comment by vtjnash** [comment]
I think this is still merge-worthy. Not specifically needed for that case any more, but any other random user might come along and use the REPLCompletions code and expect this case to work.
