### PR TITLE
Fix \ for underdetermined systems of integers

### LINKED ISSUE #224: A\b DimensionMismatch for underdetermined system with A::Matrix{Int64}
I just encountered the following oddity when A is 2x3 and b is 2x1 - I get a DimensionMismatch error which is dependent on the input _numerical values_, not only the shape of A and b:

``` julia
julia> [1 0 0; 0 1 0] \ [1;1]
ERROR: DimensionMismatch("matrix is not square")
 in chksquare at ./linalg.jl:176
 in call at linalg/triangular.jl:14
 in A_ldiv_B! at linalg/qr.jl:317
 in \ at linalg/qr.jl:421
 in \ at linalg/dense.jl:402

julia> [1 0 0.1; 0 1 0] \ [1;1]
3-element Array{Float64,1}:
 0.990099 
 1.0      
 0.0990099
```

According to the docs, "For rectangular "A" the result is the minimum-norm least squares solution computed by a pivoted QR factorization of "A" and a rank estimate of A based on the R factor."  The correct solution for the first problem should be `[1,1,0]` in that case.

### LINKED ISSUE #11949: A\b DimensionMismatch for underdetermined system with A::Matrix{Int64}
I just encountered the following oddity when A is 2x3 and b is 2x1 - I get a DimensionMismatch error which is dependent on the input *numerical values*, not only the shape of A and b:

```julia
julia> [1 0 0; 0 1 0] \ [1;1]
ERROR: DimensionMismatch("matrix is not square")
 in chksquare at ./linalg.jl:176
 in call at linalg/triangular.jl:14
 in A_ldiv_B! at linalg/qr.jl:317
 in \ at linalg/qr.jl:421
 in \ at linalg/dense.jl:402

julia> [1 0 0.1; 0 1 0] \ [1;1]
3-element Array{Float64,1}:
 0.990099 
 1.0      
 0.0990099
```

According to the docs, "For rectangular "A" the result is the minimum-norm least squares solution computed by a pivoted QR factorization of "A" and a rank estimate of A based on the R factor."  The correct solution for the first problem should be `[1,1,0]` in that case.

### PR DESCRIPTION
**Pull request by andreasnoack**
This fixes JuliaLang/LinearAlgebra.jl#224.

### CODE REVIEW

File: test/linalg/dense.jl [hunk 1]
```diff
@@ -0,0 +1,4 @@
+using Base.Test
+
+# Check that non-floats are correctly promoted
+@test_approx_eq [1 0 0; 0 1 0]\[1,1] [1;1;0]
```
Comment (tkelman) [inline test/linalg/dense.jl]: couldn't adding the new file wait until there's more than one line to add to it?

Comment (andreasnoack) [inline test/linalg/dense.jl]: There is more in `linalg1-4.jl` but it is for another commit to more that.
