### PR TITLE
hide kwcall methods from the backtrace

### LINKED ISSUE #47319: kwcall appearing in stacktraces
I have been seeing kwcall in stacktraces, and need to figure out how to reproduce it. It seems my mistake is here:
```diff
diff --git a/base/errorshow.jl b/base/errorshow.jl
index 16190d64e0..65d761aefe 100644
--- a/base/errorshow.jl
+++ b/base/errorshow.jl
@@ -850,10 +850,8 @@ function process_backtrace(t::Vector, limit::Int=typemax(Int); skipC = true)
             code = lkup.linfo
             if code isa MethodInstance
                 def = code.def
-                if def isa Method
-                    if def.name === :kwcall && def.module === Core
-                        continue
-                    end
+                if def isa Method && def.sig <: Tuple{typeof(Core.kwcall),Vararg}
+                    continue
                 end
             elseif !lkup.from_c
                 lkup.func === :kwcall && continue
```

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/issues/47157#issuecomment-1287596176_

### PR DESCRIPTION
**Pull request by vtjnash**
They are not strictly internal, but also not strictly external, so just assume they should be hidden.

Perhaps, in the future, we should figure out a way to signal directly in the line number value that this line can be hidden, so only exactly the inner call gets hidden, but not errors that happen in the kwsorter itself (for example, for computing default values). Then all of these could print comparable backtraces (rather than just hiding the kwcall, as this PR does):

```
julia> f(; a, b) = error()
f (generic function with 1 method)

julia> f()
ERROR: UndefKeywordError: keyword argument `a` not assigned
Stacktrace:
 [1] f()
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[2]:1

julia> f(b=1)
ERROR: UndefKeywordError: keyword argument `a` not assigned
Stacktrace:
 [1] kwcall(::NamedTuple{(:b,), Tuple{Int64}}, ::typeof(f))
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[3]:1

julia> f(a=1)
ERROR: UndefKeywordError: keyword argument `b` not assigned
Stacktrace:
 [1] kwcall(::NamedTuple{(:a,), Tuple{Int64}}, ::typeof(f))
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[4]:1

julia> f(a=1, b=2)
ERROR:
Stacktrace:
 [1] error()
   @ Base ./error.jl:44
 [2] f(; a::Int64, b::Int64)
   @ Main ./REPL[1]:1
 [3] kwcall(::NamedTuple{(:a, :b), Tuple{Int64, Int64}}, ::typeof(f))
   @ Main ./REPL[1]:1
 [4] top-level scope
   @ REPL[5]:1
```

Fix #47319

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

File: base/errorshow.jl [hunk 1]
```diff
@@ -850,10 +850,11 @@ function process_backtrace(t::Vector, limit::Int=typemax(Int); skipC = true)
             code = lkup.linfo
             if code isa MethodInstance
                 def = code.def
-                if def isa Method
-                    if def.name === :kwcall && def.module === Core
-                        continue
-                    end
+                if def isa Method && def.name !== :kwcall && def.sig <: Tuple{typeof(Core.kwcall),Any,Any,Vararg}
```
Comment (vchuravy) [inline base/errorshow.jl:853]: Maybe add a comment why `def.name !== :kwcall`? That's a bit confusing.

Comment (vtjnash) [reply base/errorshow.jl:853]: In theory, it means that we chose a different name for the Method when defining this because it was the kwsorter for something else, but in practice, it is unclear if that is really what it means or not.
