### PR TITLE
Bugfix for getindex(x::AbstractSparseVector, I::Abstract<Vector,Array>)

### LINKED ISSUE #24534: getindex(x::AbstractSparseVector, I::AbstractVector) fails when sparse vector indices are not default integer type
The bug described in the title shows up on release 0.6.1 and on master that was current as of last night:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.2462
Commit 193c5b9789 (2017-11-08 01:51 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
Here is a MWE
```
julia> a = sparsevec(Int32[1;4;7],Int32[2;2;2],10)
10-element SparseVector{Int32,Int32} with 3 stored entries:
  [1 ]  =  2
  [4 ]  =  2
  [7 ]  =  2

julia> i = [1;4]
2-element Array{Int64,1}:
 1
 4

julia> a[i]
ERROR: MethodError: no method matching SparseMatrixCSC{Int32,Int64}(::Int64, ::Int64, ::Array{Int64,1}, ::Array{Int32,1}, ::Array{Int32,1})
Stacktrace:
 [1] getindex(::SparseVector{Int32,Int32}, ::Array{Int64,1}) at ./sparse/sparsevector.jl:730
```
This gets dispatched to the following method in base/sparse/sparsevector.jl
```
@inline function getindex(x::AbstractSparseVector, I::AbstractVector)
    # SparseMatrixCSC has a nicely optimized routine for this; punt
    S = SparseMatrixCSC(x.n, 1, [1,length(x.nzind)+1], x.nzind, x.nzval)
    S[I, 1]
end
```
The error arises because `eltype(x.nzind) == Int32 != eltype([1,length(x.nzind)+1]) == Int64`. Those two arrays need to have the same element type.

A simple fix is to change that method to the following
```
@inline function getindex(x::AbstractSparseVector, I::AbstractVector)
    # SparseMatrixCSC has a nicely optimized routine for this; punt
    Ti = eltype(x.nzind)
    S = SparseMatrixCSC(x.n, 1, Ti[1,length(x.nzind)+1], x.nzind, x.nzval)
    S[I, 1]
end
```
I've made that change locally (and the same change in the method `getindex(x::AbstractSparseVector, I::AbstractArray)`) and it seems to work well. Is there a problem with that fix I'm not seeing? If it seems acceptable I'll make a PR.

Thanks, Patrick

### PR DESCRIPTION
**Pull request by Pbellive**
This fixes #24534. See full description of the problem in the issue. The `getindex` methods in question create n X 1 `SparseMatrixCSC`s and then call the appropriate `SparseMatrixCSC` `getindex` method. However, the way the `SparseMatrixCSC`s were being created only worked for non-zero indexing arrays stored as vectors of `Int`s. This PR simply checks the type of the non-zero indexing array and constructs the n X 1 sparse matrix appropriately. 

I also added a test that calls `getindex` on a sparse vector with `UInt32` indices. Please let me know if this PR needs to have anything added or if there's any problem with the approach. It's quite a small fix but it's my first PR to fix something in base so I want to make sure I'm following the right procedure to get it merged. I have read the contribution guidelines and looked at other PRs.

### CODE REVIEW

**Review by ararslan — COMMENTED** [review]
Welcome! This is a very nice first contribution! The changes here look good to me but I'll request a second set of eyes from someone who's more familiar with this code.

File: base/sparse/sparsevector.jl [hunk 1]
```diff
@@ -786,13 +786,15 @@ getindex(x::AbstractSparseVector, I::AbstractVector{Bool}) = x[find(I)]
...
+    Ti = eltype(x.nzind)
+    S = SparseMatrixCSC(x.n, 1, Ti[1,length(x.nzind)+1], x.nzind, x.nzval)
     S[I, 1]
 end
 
 function getindex(x::AbstractSparseVector, I::AbstractArray)
     # punt to SparseMatrixCSC
-    S = SparseMatrixCSC(x.n, 1, [1,length(x.nzind)+1], x.nzind, x.nzval)
+    Ti = eltype(x.nzind)
+    S = SparseMatrixCSC(x.n, 1, Ti[1,length(x.nzind)+1], x.nzind, x.nzval)
```
Comment (fredrikekre) [inline base/sparse/sparsevector.jl]: Would be good with a test case for this change too.

Comment (Pbellive) [reply base/sparse/sparsevector.jl]: Definitely a good idea to have another test there. I added one and found another bug. Here's an example
```
julia> a = sparsevec(Int32[1;4;7],Int32[2;2;2],10)
10-element SparseVector{Int32,Int32} with 3 stored entries:
  [1 ]  =  2
  [4 ]  =  2
  [7 ]  =  2

julia> I = rand(1:10,3,1)
3×1 Array{Int64,2}:
 1
 4
 5

julia> r = a[I]
3×1 SparseMatrixCSC{Int32,Int64} with 2 stored entries:
  [1, 1]  =  2
  [2, 1]  =  2
```
In that example `r` should be a 3 X 1 `SparseMatrixCSC{Int32,Int32}`. In general, calling `A[I]` with `A` a sparse matrix and `I<:AbstractArray` (or A a sparse vector and `I` an abstract array with `ndims(I)>1`) always returns a `SparseMatrixCSC{Tv,Int}` regardless of the indexing integer type of `A`. This arises due to a bug in the sparse matrix getindex method at https://github.com/JuliaLang/julia/blob/caa7f04da63bb13fb56560843ad84b09b33d6280/base/sparse/sparsematrix.jl#L2302.

At least I assume it's a bug. I don't understand why it would be desirable to change the type of the indexing arrays of a slice by default.
 In any event, it's simple to fix this. Is it ok to add that fix to this PR or should I create a another one since the change affects sparse matrices as well as sparse vectors?

Comment (fredrikekre) [reply base/sparse/sparsevector.jl]: You can add it to the same PR if you want. Perhaps @Sacha0 can answer the other questions regarding why we always return with `Int`?

File: test/sparse/sparsevector.jl [hunk 2]
```diff
@@ -179,6 +179,14 @@ end
             @test all(nonzeros(r) .!= 0.0)
             @test Array(r) == Array(x)[I]
         end
+
+        let x = convert(SparseVector{Float64,UInt32},sprandn(100,0.5))
+            I = rand(1:length(x), 20)
+            r = x[I]
+            @test isa(r, SparseVector{Float64,UInt32})
+            @test all(nonzeros(r) .!= 0.0)
```
Comment (Sacha0) [inline test/sparse/sparsevector.jl]: Perhaps `all(!iszero, nonzeros(r))`, avoiding the temporary? :)

File: base/sparse/sparsevector.jl (hunk 1 above)
Comment (Sacha0) [reply base/sparse/sparsevector.jl]: The index-type non-preservation in the linked methods looks like an oversight on this end as well :).

**Comment by Sacha0** [comment]
A wonderful first contribution indeed! Welcome and thanks much @Pbellive! :)

File: test/sparse/sparsevector.jl (hunk 2 above)
Comment (Pbellive) [reply test/sparse/sparsevector.jl]: Oh I like that syntax. Will change.

**Comment by Pbellive** [comment]
Thanks very much for the feedback all. I'll update the sparse matrix `getindex` method discussed above + relevant tests and push tomorrow.

**Comment by Pbellive** [comment]
I think this is ready to go now. Not sure why the appveyor tests are failing but it doesn't seem to have anything to do with this PR. Build seems to be failing on master as well.

**Review by mbauman — APPROVED** [review]
LGTM! Great first PR, thanks!

File: base/sparse/sparsematrix.jl [hunk 3]
```diff
@@ -2305,13 +2305,14 @@ function getindex(A::SparseMatrixCSC{Tv}, I::AbstractArray) where Tv
     colptrA = A.colptr
     rowvalA = A.rowval
     nzvalA = A.nzval
+    Ti = eltype(colptrA)
```
Comment (fredrikekre) [inline base/sparse/sparsematrix.jl]: Could perhaps be cleaner to change the function signature to:
```julia
function getindex(A::SparseMatrixCSC{Tv,Ti}, I::AbstractArray) where {Tv,Ti}
    # ...
```

File: base/sparse/sparsematrix.jl [hunk 4]
```diff
@@ -2325,7 +2326,7 @@ function getindex(A::SparseMatrixCSC{Tv}, I::AbstractArray) where Tv
         for r in colptrA[col]:(colptrA[col+1]-1)
             @inbounds if rowvalA[r] == row
                 rowB,colB = ind2sub(szB, i)
-                colptrB[colB+1] += 1
+                colptrB[colB+1] += one(Ti)
```
Comment (fredrikekre) [inline base/sparse/sparsematrix.jl]: This should not be necessary; the `1` will be converted to the correct type when entered into the vector.

File: base/sparse/sparsevector.jl [hunk 5]
```diff
@@ -646,10 +646,11 @@ function getindex(A::SparseMatrixCSC{Tv}, I::AbstractVector) where Tv
     colptrA = A.colptr
     rowvalA = A.rowval
     nzvalA = A.nzval
+    Ti = eltype(colptrA)
```
Comment (fredrikekre) [inline base/sparse/sparsevector.jl]: Same as above; I suggest we update the function signature instead;
```julia
function getindex(A::SparseMatrixCSC{Tv,Ti}, I::AbstractVector) where {Tv,Ti}
    # ...
```

File: base/sparse/sparsevector.jl [hunk 6]
```diff
@@ -786,13 +787,15 @@ getindex(x::AbstractSparseVector, I::AbstractVector{Bool}) = x[find(I)]
...
-    S = SparseMatrixCSC(x.n, 1, [1,length(x.nzind)+1], x.nzind, x.nzval)
+    Ti = eltype(x.nzind)
+    S = SparseMatrixCSC(x.n, 1, Ti[1,length(x.nzind)+1], x.nzind, x.nzval)
     S[I, 1]
 end
 
 function getindex(x::AbstractSparseVector, I::AbstractArray)
     # punt to SparseMatrixCSC
-    S = SparseMatrixCSC(x.n, 1, [1,length(x.nzind)+1], x.nzind, x.nzval)
+    Ti = eltype(x.nzind)
```
Comment (fredrikekre) [inline base/sparse/sparsevector.jl]: Same here, perhaps instead add this to the signature as:
```julia
function getindex(x::AbstractSparseVector{Tv,Ti}, I::AbstractArray) where {Tv,Ti}
    # ...
```

File: test/sparse/sparse.jl [hunk 7]
```diff
@@ -716,6 +716,13 @@ end
         @test S1290[end] == (S1290[1] + S1290[2,2])
         @test 6 == sum(diag(S1290))
         @test Array(S1290)[[3,1],1] == Array(S1290[[3,1],1])
+
+        # check that indexing with an abstract array returns matrix
+        # with same colptr and rowval eltypes as input
```
Comment (fredrikekre) [inline test/sparse/sparse.jl]: Could be worthwhile adding a breadcrumb to this PR and/or the issue.

File: test/sparse/sparsevector.jl [hunk 8]
```diff
@@ -176,7 +176,23 @@ end
             I = rand(1:length(x), 20)
             r = x[I]
             @test isa(r, SparseVector{Float64,Int})
-            @test all(nonzeros(r) .!= 0.0)
+            @test all(!iszero, nonzeros(r))
+            @test Array(r) == Array(x)[I]
+        end
+
+        let x = convert(SparseVector{Float64,UInt32},sprandn(100,0.5))
```
Comment (fredrikekre) [inline test/sparse/sparsevector.jl]: Same for the tests here, I think it would be nice with a comment what the test is for, and perhaps a reference to the PR/issue.

**Review by fredrikekre — APPROVED** [review]
Some small suggestions

File: base/sparse/sparsematrix.jl (hunk 3 above)
Comment (Pbellive) [reply base/sparse/sparsematrix.jl]: Agreed. Made the change.

File: base/sparse/sparsematrix.jl (hunk 4 above)
Comment (Pbellive) [reply base/sparse/sparsematrix.jl]: Changed.

File: test/sparse/sparse.jl (hunk 7 above)
Comment (Pbellive) [reply test/sparse/sparse.jl]: Added breadcrumbs on all the tests

File: base/sparse/sparsevector.jl (hunk 5 above)
Comment (Pbellive) [reply base/sparse/sparsevector.jl]: Changed.

File: base/sparse/sparsevector.jl (hunk 6 above)
Comment (Pbellive) [reply base/sparse/sparsevector.jl]: Changed

**Comment by Pbellive** [comment]
@fredrikekre, thanks for the feedback. I've incorporated all your suggestions. I agree that including the integer type as a parameter in the functions signatures looks cleaner.

**Review by fredrikekre — APPROVED** [review]
Thanks!

**Comment by KristofferC** [comment]
Thanks for the contribution!
