### PR TITLE
Threading without using patched LLVM

### LINKED ISSUE #13975: Windows build with JULIA_THREADS = 1 segfaults
`Make.user` has the required `XC_HOST = x86_64-w64-mingw32`.
I added `JULIA_THREADS = 1` as I wanted to test threads. MSYS2 isn't working still from my understanding of #13206 so I used Cygwin. The deps built successfully but when building Julia it failes with:
```
Copying in usr/share/doc/julia/examples
    JULIA usr/lib/julia/inference0.ji
/bin/sh: line 1: 16180 Segmentation fault      /cygdrive/d/julia/usr/bin/julia.exe -C native --output-ji `cygpath -w /cygdrive/d/julia/usr/lib/julia/inference0.ji` -f coreimg.jl
Makefile:211: recipe for target '/cygdrive/d/julia/usr/lib/julia/inference0.ji' failed
make[1]: *** [/cygdrive/d/julia/usr/lib/julia/inference0.ji] Error 139
Makefile:93: recipe for target 'julia-inference' failed
make: *** [julia-inference] Error 2
```

### PR DESCRIPTION
**Pull request by yuyichao**
This tries to implement what @vtjnash suggested for making threading working without LLVM patch. This should also make it possible to support threading on windows since (I was told that) the LLVM tls patch doesn't support emitting TLS on windows.

A few notes ~~and TODOs~~ (all done):
1. ~~The first few commits in this PR are not directly related to TLS, they are either slightly related
   clean-up's or fix of the bug discovered when testing this PR.~~
   (merged as https://github.com/JuliaLang/julia/pull/14084)
2. ~~This is currently GCC/Clang only due to the `__attribute__((const))` but it is only for performance
   and not for correctness so can easily be disabled for other compilers (MSVC) or replaced with
   equivalent attributes.~~ (fixed, [MSVC doesn't/won't support it](http://stackoverflow.com/a/2798511/904262), use `__declspec(noalias)` on MSVC)
3. This placed all TLS variables in a big struct. Mainly because it's easier to do... There's no `#ifdef`'s
   in the struct in order to keep it clean and to make the threading and non-threading versions ABI
   compatible (to certain degree anyway...). This also effectively export all the TLS variables but we
   could easily fix this using a nested struct (and only exposing the pointer to the inner, exported
   struct) if it is a concern. (FWIW, this is C and there's way more things you can do to break stuff
   other than accessing a non-exported TLS variable....)
4. Compilation passes, REPL works and all tests passes for both threading and non-threading on
   LLVM37. ~~(The compilation of `inference0.ji` with threading on had one SegFault that I couldn't
   reproduce).~~ (reported as #14091)
5. ~~Codegen is always accessing the TLS variables through a (const) function call. I get a freeze
   before enterning the REPL if I let it use the global variable directly for non-threading version.
   (probably because I didn't declare the struct correctly for LLVM).~~ (fixed). OTOH, with the
   function attributes set (copied from Clang), llvm is able to emit only on call to `jl_get_ptls_states()`
   per function.
6. ~~TLS model is still `global-dynamic`.~~ Using a dynamic model by default. Override to a static model in repl. The override has to be done at initialization time and can be done for embedding as well if needed.

c.c @tkelman @Keno

edit: closes #13975

### CODE REVIEW

**Comment by tkelman** [comment]
Lovely, thank you for this. This will close #13975. I wonder whether this would allow us to turn threading on by default before we move to newer LLVM? First time I tried that on win64 it segfaulted in bootstrap, though will try another few times to see if it's the same problem as #14091.

**Comment by yuyichao** [comment]
> This will close #13975

I suspect #13975 is the same with #14091 (since it segfault before the LLVM error)

**Comment by yuyichao** [comment]
Squashed and all the TODO's in this PR are done now! Remove `WIP` from the title and this PR is ready for review.

This essentially implements a runtime weak symbol. It would be nice if the dynamic linker can do this for us (I tried `__attribute__((weak))` but couldn't get it working).

Getting the address of the TLS variable is not as fast as (~30-60% slower) the optimal case (a single function returning a static TLS address) but is also much faster (2x-3x) than using the global dynamic model. Note that this is also only relavant for code in the `sys.so`, JIT code use the actually getter function address directly. The impact on the overall performance will also be much smaller since we only emit TLS variables in expensive functions (gcframe, catch exceptions).

The advantage of this approach is that it should be able to support all platforms (non-linux have a lot of issues with unresolved symbols in a shared library) and doesn't require another shim for embedding.

File: src/codegen.cpp [hunk 1]
```diff
@@ -5640,6 +5625,25 @@ static void init_julia_llvm_env(Module *m)
                                      "jl_float_temp"));
 #endif
 
+#ifndef JULIA_ENABLE_THREADING
+    jltls_states_var =
+        new GlobalVariable(*m, ArrayType::get(T_int8, sizeof(jl_tls_states_t)),
```
Comment (vtjnash) [inline src/codegen.cpp]: I think this can be declared as an ArrayType of `T_pint8` so that alignment is correct and to avoid the BitCastOp on most usages

Comment (yuyichao) [inline src/codegen.cpp]: I actually had that at first but was a little bit paranoid about the size I should supply since `jl_tls_states_t` has a `int16_t` and is not exactly multiple of pointer size.

Comment (vtjnash) [inline src/codegen.cpp]: true, although although sizeof must be a multiple of __alignof in C, so the over-allocation is guaranteed

**Comment by vtjnash** [comment]
lgtm. thanks, :santa: :penguin:

File: src/codegen.cpp (hunk 1 above)
Comment (yuyichao) [inline src/codegen.cpp]: Agree, I'll rearange the members a little and declare it as a pointer array to LLVM.

Comment (yuyichao) [inline src/codegen.cpp]: Done. You are right that `sizeof(jl_tls_states_t) % sizeof(void*) == 0`. The bitcast was actually not necessary anyway since it's always casted to `T_ppjlvalue` by `emit_nthptr_addr` anyway....

**Comment by yuyichao** [comment]
So I've just run some micro-benchmarks to compare the performance of creating a useless gc frame. The functions I used to benchmark this is (they are the `gcframe` and `no gcframe` respectively in the table below).

```jl
@noinline function tls_test(a)
    1 > 2 && "a$a"
    a
end

@noinline function non_tls_test(a)
    a
end
```

The first function generates a useless gcframe for the branch eliminated by llvm.

I've also put this in the sysimg and verified in GDB that for this PR with threading, the sysimg version has one more level of indirection through `jl_get_ptls_states` while the JIT version calls `jl_get_ptls_states_static` directly.

Numbers below (time in ns)

||master|this pr|master threading|this pr threading|
|gcframe (sysimg)|1.74|1.74|5.22|3.07|
|no gcframe (sysimg)|1.09|1.09|1.09|1.09|
|gcframe|1.53|1.72|5.22|2.93|
|no gcframe|1.09|1.09|1.09|1.09|

The only possible regression is the non-threading GC frame is slower by 1-2 cycles (0.217ns). The extra level of indirection isn't as bad as what Ithought for tls access in sysimg.

Overall, I'm pretty happy with the current performance. Maybe we can do better for the tls access (trick the linker or emitting static TLS access if we can recognize that?)

Will merge tomorrow if there's no other issues.

**Comment by tkelman** [comment]
Let's merge now?

**Comment by yuyichao** [comment]
Sure.....

**Comment by ViralBShah** [comment]
Does this mean we can turn on travis

**Comment by yuyichao** [comment]
The build should work, but I'm pretty sure there's still bugs (not sure if we can hit those bugs without actually running many threads though). Maybe at least have a buildbot for it? @tkelman @staticfloat

**Comment by tkelman** [comment]
It is dev master. I say let's turn threads on by default, everywhere except MSVC.

**Comment by yuyichao** [comment]
I'd prefer to leave it off until we have a stop-the-world GC (rather than a wait-for-the-world GC as @vtjnash phrased it....)

**Comment by ViralBShah** [comment]
I thought there was a buildbot for threading.

**Comment by staticfloat** [comment]
@yuyichao What build configuration would you want?  Just tacking `JULIA_ENABLE_THREADING` onto the makevars?

**Comment by yuyichao** [comment]
> I thought there was a buildbot for threading.

I thought there wasn't since I've heard there's issues getting newer LLVM to build.

> What build configuration would you want

Normal build and test with `JULIA_THREADS=1` make var.

**Comment by staticfloat** [comment]
What is the minimum version of LLVM we can build against?  We have `Cxx` nightlies that actually finish building every now and then, but if there is a specific version we can build against that'd be great.

**Comment by tkelman** [comment]
Cxx nightlies are broken on gcc 5 because they are based off a broken point in upstream's history, see https://github.com/Keno/Cxx.jl/issues/73#issuecomment-152918572.

Threading with LLVM 3.3 should now work, which was the purpose of this PR.

**Comment by ViralBShah** [comment]
Perhaps I was thinking of the cxx buildbot. Sorry for the noise.

**Comment by staticfloat** [comment]
Alright, I've got a nightly builder that will attempt this stuff, and have [a test build](http://buildbot.e.ip.saba.us:8010/builders/nightly_threading64/builds/0) forcing its way through right now.

**Comment by yuyichao** [comment]
Seems like [it was broken](http://buildbot.e.ip.saba.us:8010/builders/nightly_threading64/builds/0/steps/make%20binary-dist/logs/stdio) by https://github.com/JuliaLang/julia/pull/14103#issuecomment-159304606
