### PR TITLE
Fix bug in SubstitutionString replace

### LINKED ISSUE #27125: SubstitutionString can't contain escape sequences \n, \t, etc. during replace
While trying to create documentation for SubstitutionString (#26497), I found that `replace` using `SubstitutionString`s doesn't work if the substition string has a newline or other escape sequence in it. 

```
julia> msg = "#Hello# from Julia";

julia> re = r"#(.+)# from (?<name>\w+)";

julia> subst = s"FROM: \g<name>\n MESSAGE: \1"
s"FROM: \\g<name>\\n MESSAGE: \\1"

julia> replace(msg, re => subst)
ERROR: Bad replacement string: FROM: \g<name>\n MESSAGE: \1
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] replace_err at .\regex.jl:241 [inlined]
 [3] _replace(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Base.SubstitutionString{String}, ::String, ::UnitRange{Int64}, ::Regex) at .\regex.jl:302
 [4] #replace#350(::Int64, ::Function, ::String, ::Pair{Regex,Base.SubstitutionString{String}}) at .\strings\util.jl:427
 [5] replace(::String, ::Pair{Regex,Base.SubstitutionString{String}}) at .\strings\util.jl:415
 [6] top-level scope

julia> subst = s"FROM: \g<name>; MESSAGE: \1"
s"FROM: \\g<name>; MESSAGE: \\1"

julia> replace(msg, re => subst) #works fine when \n is removed
"FROM: Julia; MESSAGE: Hello"
```

Looking at the code, when the `_replace` function (in regex.jl) sees a backslash, it expects another backslash, a digit or a 'g', and throws an error with `replace_err` if it doesn't see one of those. Another consequence of this is that the replacement string can't contain things like Unicode codepoint sequences (`\u0B85`).

### PR DESCRIPTION
**Pull request by sam0410**
fixes #27125

### CODE REVIEW

File: base/regex.jl [hunk 1]
```diff
@@ -309,6 +309,8 @@ function _replace(io, repl_s::SubstitutionString, str, r, re)
     LBRACKET = '<'
     RBRACKET = '>'
     repl = repl_s.string
+    keep_esc = [SUB_CHAR, GROUP_CHAR, collect('0':'9')...]
```
Comment (nalimilan) [inline base/regex.jl]: Define this as a literal tuple, or outside of the function with `const`, to avoid allocating on each call.

File: base/strings/io.jl [hunk 2]
```diff
@@ -382,12 +382,14 @@ julia> unescape_string("\\\\101") # octal
 ## See also
 [`escape_string`](@ref).
 """
-function unescape_string(io, s::AbstractString)
+function unescape_string(io, s::AbstractString, keep_esc::AbstractArray{<:AbstractChar}=Char[])
```
Comment (nalimilan) [inline base/strings/io.jl]: This adds an argument to an exported function, so it should be documented. Also I'd simply call this `keep`.

Finally, it could be worth using `nothing` or `()` as a default value to avoid introducing an overhead when that argument is omitted. Not sure whether it makes a significant difference, though.

**Review by nalimilan — COMMENTED** [review]
Thanks. I think the following comment by @digital-carver at #27125 needs to be taken into account, though: 
> There's a change in behaviour due to this though: invalid single letter sequences like `\m`, `\j`, etc. are silently replaced by their corresponding character (`m`, `j`, ...) by `unescape_string`, whereas currently `_replace` emits the "Bad replacement string" error for those. Perhaps `unescape_string` needs another optional argument to enable a `strict` mode, or... is there a reason `unescape_string` is currently _not_ strict about invalid C sequences, while it errors out on invalid Unicode sequences?

**Comment by sam0410** [comment]
Thanks for your review @nalimilan. I thought the following comment has already been merged in pull request #27238 ?

`    There's a change in behaviour due to this though: invalid single letter sequences like \m, \j, etc. are  silently replaced by their corresponding character (m, j, ...) by unescape_string, whereas currently _replace emits the "Bad replacement string" error for those. Perhaps unescape_string needs another optional argument to enable a strict mode, or... is there a reason unescape_string is currently not strict about invalid C sequences, while it errors out on invalid Unicode sequences?`

File: base/strings/io.jl (hunk 2 above)
Comment (sam0410) [reply base/strings/io.jl]: Did you mean `unescape_string(io, s::AbstractString, keep = nothing)` ? I don't think that should be used otherwise it will throw `MethodError` in place of `ArgumentError`.

File: base/regex.jl (hunk 1 above)
Comment (sam0410) [reply base/regex.jl]: Yes you are right. I fixed that.

File: base/strings/io.jl [hunk 3]
```diff
@@ -354,10 +354,11 @@ end
 # TODO: handle unescaping invalid UTF-8 sequences
 """
     unescape_string(str::AbstractString)::AbstractString
-    unescape_string(io, str::AbstractString)::Nothing
+    unescape_string(io, str::AbstractString, keep::AbstractArray{<:AbstractChar} = nothing)::Nothing
```
Comment (nalimilan) [inline base/strings/io.jl]: The signature should match the actual one. So either `keep = nothing` (and the text should say "a collection of characters"), or use `::Union{AbstractArray{<:AbstractChar} , Nothing}` in both places.

BTW, below, not only the characters are kept as they are: the whole sequence including the backlash is (also  "as it is" should be "as they are").

File: base/regex.jl [hunk 4]
```diff
@@ -303,12 +303,14 @@ function _write_capture(io, re, group)
     io.size = max(io.size, io.ptr - 1)
 end
 
+const SUB_CHAR = '\\'
```
Comment (nalimilan) [inline base/regex.jl]: Why does this need to be allowed? That's not covered by tests AFAICT.

File: base/strings/io.jl [hunk 5]
```diff
@@ -382,12 +383,14 @@ julia> unescape_string("\\\\101") # octal
 ## See also
 [`escape_string`](@ref).
 """
-function unescape_string(io, s::AbstractString)
+function unescape_string(io, s::AbstractString, keep = ())
```
Comment (nalimilan) [inline base/strings/io.jl]: Add `io::IO` to fix the ambiguity error which caused CI failure (and adjust docstring).

File: NEWS.md [hunk 6]
```diff
@@ -22,6 +22,7 @@ New library functions
 Standard library changes
 ------------------------
 
+* Added argument `keep` to `unescape_string` ([#27125]).
```
[the remark this answers is not in the document]
Comment (sam0410) [reply NEWS.md]: I added the `unescape_string` change under `new language functions` of `NEWS.md`
But I think the improvement to the substitution string is a bugfix. Does it needs to be added to `NEWS.md` too?

File: base/regex.jl (hunk 4 above)
Comment (sam0410) [reply base/regex.jl]: I added tests for this @nalimilan.

File: NEWS.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (nalimilan) [reply NEWS.md]: Looks like we don't mention bug fixes in NEWS.md, so should be OK.

File: base/regex.jl (hunk 4 above)
Comment (nalimilan) [reply base/regex.jl]: Thanks, but I still don't get why backslashes need to be in the list of accepted chars.

File: base/strings/io.jl [hunk 7]
```diff
@@ -377,17 +379,22 @@ julia> unescape_string("\\\\u03c0") # unicode
 
 julia> unescape_string("\\\\101") # octal
 "A"
+
+julia> unescape_string("aaa \\g \\n", ['g']) # using `keep` argument
+"aaa \\g \n"
```
Comment (nalimilan) [inline base/strings/io.jl]: The CI failure is due to this. Not sure exactly why. Maybe it needs to be `\\n`. You can check this locally by running `make -C doc doctest=true`.

File: base/regex.jl (hunk 4 above)
Comment (sam0410) [reply base/regex.jl]: When the ` _replace function` (in `regex.jl`) sees a backslash, it expects another backslash, a digit or a 'g', and throws an error with `replace_err` if it doesn't see one of those.

File: base/strings/io.jl (hunk 7 above)
Comment (sam0410) [reply base/strings/io.jl]: ``` unescape_string("aaa \\g \\n", ['g'])``` 
results in
```"aaa \\g \n"```
I think there is a problem with docstrings here. I am not sure on how to fix that.

Comment (sam0410) [reply base/strings/io.jl]: This is the error.
```
julia> unescape_string("aaa \n \g", ['g']) # using `keep` argument
"aaa 
 \g"

> Subexpression:

    unescape_string("aaa \n \g", ['g']) # using `keep` argument

> Output Diff:

"aaa 
 \g"
```

I don't know why ```unescape_string("aaa \\g \\n", ['g'])``` interpreted as ```unescape_string("aaa \g \n", ['g'])``` . I think there is some issue with docstrings. I am not sure how to fix this.

Comment (nalimilan) [reply base/strings/io.jl]: Have you tried writing `\\\\g` and so on?

Comment (sam0410) [reply base/strings/io.jl]: Thanks for the suggestion @nalimilan . I added the change.

**Review by nalimilan — APPROVED** [review]
Thanks!

I realize that if performance really matters it could be more efficient to pass a function instead of an array of characters: `c -> c == '\\' || c == 'g' || '0' <= c <= '9'` would need fewer operations. But that probably doesn't matter a lot.

**Comment by sam0410** [comment]
Hi @StefanKarpinski @nalimilan , just came in to see if this could be merged.

**Comment by JeffBezanson** [comment]
Bump. @StefanKarpinski ok to merge? (needs rebase tho)

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Can be squash-merged if CI passes.
