### PR TITLE
Fix segment violation with negative size argument to NTuple{N,T}

### LINKED ISSUE #11967: NTuple does not like unsigned integers
This was the cause of a rather frustrating bug I had today:
```
Ref{NTuple{0x0000000000000004,UInt8}}()
Base.RefValue{NTuple{0x0000000000000004,UInt8}}(#undef)
```

### PR DESCRIPTION
**Pull request by ScottPJones**
This fixes one of the problems I discovered with the way values are handled in the type system.

~~This is a different fix for the issue in #11967.
Instead of making using an `Unsigned` value (or anything not strictly of `Int` type)
be an error, this allows any `Integer` or `Unsigned` type that is <= `size_t` to be used,
which conceptually seems to be what you'd want.~~

~~Note: the code is more verbose than I would have liked, I couldn't find any way of simply asking if
a parameter was an `Integer` type, as opposed to checking each specific concrete type.~~

### CODE REVIEW

File: src/jltypes.c [hunk 1]
```diff
@@ -1687,17 +1687,43 @@ jl_value_t *jl_apply_type_(jl_value_t *tc, jl_value_t **params, size_t n)
...
+            else if (jl_is_uint8(params[0])) {
+                nt = jl_unbox_uint8(params[0]);
+            }
+            else if (jl_is_int16(params[0])) {
+                nt = jl_unbox_int16(params[0]);
+            }
+            else if (jl_is_int8(params[0])) {
+                nt = jl_unbox_int8(params[0]);
+            }
+            else if (!jl_is_typevar(params[0])) {
```
Comment (yuyichao) [inline src/jltypes.c]: Duplicated logic.

File: src/jltypes.c [hunk 2]
```diff
@@ -1687,17 +1687,43 @@ jl_value_t *jl_apply_type_(jl_value_t *tc, jl_value_t **params, size_t n)
...
+                // Only allow integer, unsigned or TypeVar as the first parameter to
+                // NTuple. issue #9233
+                jl_type_error_rt("apply_type", "first parameter of NTuple",
+                                 (jl_value_t*)jl_long_type, params[0]);
```
Comment (yuyichao) [inline src/jltypes.c]: Wrong parameter

**Comment by yuyichao** [comment]
Not sure we'll gain anything except complexity in c code by doing this.

File: src/jltypes.c [hunk 3]
```diff
@@ -1687,17 +1687,43 @@ jl_value_t *jl_apply_type_(jl_value_t *tc, jl_value_t **params, size_t n)
...
     if (tc == (jl_value_t*)jl_ntuple_type && (n == 1 || n == 2)) {
-        if (jl_is_long(params[0])) {
-            size_t nt = jl_unbox_long(params[0]);
+        if (!jl_is_typevar(params[0])) {
+            size_t nt;
+            if (jl_is_long(params[0])) {
+                nt = jl_unbox_long(params[0]);
+            }
+#ifdef _P64
+            else if (jl_is_uint64(params[0])) {
```
Comment (yuyichao) [inline src/jltypes.c]: Duplicated

File: src/jltypes.c (hunk 1 above)
Comment (ScottPJones) [inline src/jltypes.c]: What is duplicated?  Unfortunately, I didn't find any call that give you whether something is one of the many primitive Int or UInt types, as I clearly stated in the opening comment.

File: src/jltypes.c (hunk 2 above)
Comment (ScottPJones) [inline src/jltypes.c]: What's the wrong parameter? The only thing I didn't see how do to, is to have the error say "Integer" instead of "Int64" (or "Int32" on a 32-bit machine).

File: src/jltypes.c (hunk 3 above)
Comment (ScottPJones) [inline src/jltypes.c]: There is no duplication there.  long is either int64 or int32.  the _P64 case catches uint64 and int32, which would otherwise be missed.

**Comment by ScottPJones** [comment]
What you gain is having it make more sense to people using it.  Even @keno got bit by this only accepting `Int` type, instead of any integer (including unsigned) that would fit in a `size_t`.

**Comment by JeffBezanson** [comment]
The main issue is that the type system only uses === to compare non-types, so allowing many integer types in theory creates tuples that differ only in the type of integer used to represent the length. Of course this code effectively converts these to a common type, but we don't do that for type parameters in any other case. I think this is just spurious complexity. Why allow a fixed, but relatively large set of integer types here? The reason one could get bit before is that there was no clear error.

**Comment by ScottPJones** [comment]
Why should it matter what type is used, as long as `NTuple{}` is provided with a unsigned integer value that represents a length?  That seems a needless restriction.
If I read a length out of a `UInt8` (say, from something coming across from ZMQ or a file), and want to use that to create an `NTuple{}` (which seems like the case that @Keno ran into), why should that be an error?  I thought it was more Julian to define things with the abstract type (in this case, Integer), and not a particular concrete type.  If there is not a simpler way of coding this, then I'd add a general function that returned the value from any Integer type (which includes Unsigned, of course), so that it can be used not just here, but anywhere else where it makes sense.

**Comment by ScottPJones** [comment]
Here are some related bugs I found (there are a lot of places that call jl_is_long, that look incorrect):
I'm working on some changes that will also fix these bugs:
```julia
julia> bitstype -4294967280 t

julia> bitstype 68719476753 y
ERROR: invalid number of bits in type y

julia> bitstype 68719476752 y

julia> bitstype 68719476751 y
ERROR: invalid number of bits in type y

julia> bitstype -4294967279 t
ERROR: invalid number of bits in type t

julia> bitstype -4294967281 t
ERROR: invalid number of bits in type t
```

**Comment by JeffBezanson** [comment]
+1 to fixing those.

Type systems are difficult enough as it is. You really don't want to wedge in extra behaviors like this.

For example, there might be other places in the compiler (or in Lint.jl) that assume this is an Int. Someone might want to modify type inference to return `Bottom` for invalid parameters to `NTuple`, and this logic would have to be replicated there.

Currently, we "expand" NTuple to a normal tuple type when you pass an integer, but we won't always. If we keep the integer in place, should we have `NTuple{0x2} == NTuple{2}`? If so, then the system now contains another kind of equality that's mostly like `===` but works differently for 8 specific integer types. Or, we might no longer have `T{x}.parameters[1]===x`. Code that looks at type parameters needs to be aware of this.

If we merged this, I can see the next issue title: "NTuple accepts all integer types except BigInt".
Today, the run time system happens to know about these 8 integer types, but maybe it won't always. Why introduce more coupling just for this one case? The type system cannot call `==`, since then you'd have to run arbitrary user code just to compare types.

I hope this illustrates some of my thinking. I believe we really need to keep type system internals like this as simple as possible.

**Comment by ScottPJones** [comment]
To me, the problem is taking something that is conceptually a unsigned size_t type (which is what the long is usually placed in, leading to potential bugs), and trying to limit things to a particular concrete type that doesn't even match that.
I don't see BigInt as being a problem either.  It isn't the *type* that matters, but rather will the value given fit into a size_t.  If the value of a BigInt is small enough to fit, then it should be valid.
It isn't just this one case, either, I think this is true anywhere you have a dimension or size,
instead of a type, as a type parameter.
I think the type system needs to be *conceptually* simple, which I don't feel that allowing only a specific concrete type for size/dimension parameters is (@Keno is super smart, well versed in all of Julia, so if even he can stumble over this, anybody can).

**Comment by ScottPJones** [comment]
>Or, we might no longer have T{x}.parameters[1]===x. Code that looks at type parameters needs to be aware of this.

I would say that all size/dimensions become internally size_t, (and treated as Int for display in Julia, i.e. no 0x...), and you have a comparison for those parameters that knows about that, instead of using the overly restrictive `=== x`.

**Comment by tkelman** [comment]
So now you have a special kind of type parameter with a unique set of behaviors only for size or dimension parameters? How would Julia type definitions communicate "this parameter is a dimension"? I don't see the advantage of this, since the simpler behavior can just be documented and error messages added.

**Comment by JeffBezanson** [comment]
> If the value of a BigInt is small enough to fit, then it should be valid.

But there is no way to realize this. The type system cannot depend on arbitrary user-level definitions. There is not even a reasonable way to "eventually" allow this.

You are conflating *simple* and *easy* (with thanks to Rich Hickey). Being able to use 8 integer types instead of 1 might be easier in some cases, but it's *not* simpler.

Put differently: this is not just some random piece of code that can be adjusted any way we feel like. It's the f***ing type system.

**Comment by JeffBezanson** [comment]
> if even he can stumble over this, anybody can

Do you really think he still would have stumbled having seen the error "first parameter to NTuple must be an Int"? That would have caught the problem early.

**Comment by ScottPJones** [comment]
>So now you have a special kind of type parameter with a unique set of behaviors only for size or dimension parameters?

@tkelman There already is a special kind of type parameter in the code for size and dimension parameters, and it is handled currently by position, i.e. `NTuple{N,T}` or `Array{T,dims...}`.
@JeffBezanson I understand quite well that this is the type system. I also understand that you are still working on changes/improvements to the type system (which I am looking forward to).

Conceptually, I would think that (pardon the pseudo-code), NTuple would act as follows:
```julia
NTuple{N::Integer, T} = NTuple{Int(N), T}
NTuple{N::Int, T} = NTuple{N, T}
NTuple{N} = NTuple{N, Any}
```
That would handle any Integer type (including Unsigned or BigInt types), as long as the value fit
into an Int (you'd get an Inexact error otherwise).
Would doing that really mess up the type system at all?
Having the rules written as above seems more general than having it determined by the C code.

**Comment by JeffBezanson** [comment]
Yes, if we had the ability to define things like that then it would probably be ok. We tend to implement flexibility only at higher abstraction levels. For example, arrays require that assigned values match the element type, but `getindex` calls `convert` on top of that.

The problem is that generic functions depend on the type system to find a matching method, so the type system should not in turn depend on generic functions. If we all decided to construct tuple types via a new generic function `ntupletype(n::Integer, t::Type) = NTuple{...}` then allowing any integer would be fine. However, this would "hide" the integer behind a lambda (or two), making it harder for the compiler to determine the exact type being constructed. We would have to special-case this function.

So yes, this does mess up the type system. Not an enormous amount, but an unwelcome amount. I'm all for generality, but the type system is effectively the base case behind all the generality.

**Comment by ScottPJones** [comment]
If you look, I had removed already the handling of unsigned and other concrete integer types, so this is strictly a fix of a segment violation, so I don't see any reason not to merge this.

**Comment by ScottPJones** [comment]
>The problem is that generic functions depend on the type system to find a matching method, so the type system should not in turn depend on generic functions.

I think you are misunderstanding me here.  I am not saying that one should use functions at all
(although that might actually work today, but with the problems you mentioned about lambdas),
but rather have new syntax for types that would treat type definitions similar to method definitions,
as I did in my pseudo-code above.
That way, you could have a lot of generality with the type, and not need to implement any of that generality in the low level code, as is done now for NTuples.  In fact, for the current NTuple implementation, where it simply makes a Tuple type with N types, you might be able to do it completely
in higher level code, and not have had to add anything at all to the type system. I think it would also allow checking certain invariants of the type  earlier on, instead of buried in the C code (which is where I found several bugs already, one of which this PR fixes)

**Comment by timholy** [comment]
Having looked at this, I agree 100% with Jeff that sizes should use just one integer type throughout julia. I would rather see this fixed by making it impossible to construct an `NTuple` with `N<0` or anything other than an `Int`. (Except for the probably-necessary `UInt8`, I also think the introduction of unsigned numbers in C was a mistake---the problems they cause are not justified by having that extra bit. It's a strength that julia is not following C's lead here.)

This issue is not fixed by #11242, so whatever you do here would be independent.

**Comment by ScottPJones** [comment]
@timholy I disagree totally about unsigned integers in C, remember, C is meant to be able to express what you would otherwise have to code in assembly language, and a lot of the arithmetic you need to do is unsigned, not signed there.  `char` was signed on most implementation originally, because you only had to worry about 7-bit ASCII back then, except for IBM with EBCDIC.  That "extra bit" is critical in most of the programming that I do (I probably use unsigned types much more than signed types).

Since this does fix a nasty segmentation violation, and is not covered by #11242, do you think somebody might merge it?

**Comment by ScottPJones** [comment]
@timholy This change does exactly that, it makes it impossible to construct an `NTuple` with `N<0` and only allows `Int`.

**Comment by timholy** [comment]
Sorry, I misread it (was going too fast).
