### PR TITLE
simplify interpreter-stacktraces code

### LINKED ISSUE #33877: backtrace test issue
Been seeing a lot of this start happening recently: https://build.julialang.org/#/builders/65/builds/5828
```
Error in testset backtrace:
Test Failed at D:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\backtrace.jl:239
  Expression: read(#= D:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\backtrace.jl:239 =# Core.@cmd("\$(Base.julia_cmd()) --startup-file=no --compile=min -e \$code"), String) == "1000 1000"
   Evaluated: "998 1000" == "1000 1000"
```

### PR DESCRIPTION
**Pull request by vtjnash**
The unwinder and debuggers thought that our assembly code here was not
quite correct. Rather than attempt to fix that, let the compiler
generate it so we don't need to maintain it anymore.

This was previously also not particularly optimal for an interpreter to
need a couple extra function calls (by indirect pointer too) to setup
the call frame, so now we avoid that.

This simplifies the design by adding a new flag bit to the existing
pgcstack frames. In the future, we may end up generalizing this support
to handle stack allocation of arbitrary objects, but for now we
implement just enough support for our current needs.

It's unclear why dbghelp StackWalk glitches here a couple times (it is
reporting the stack pointer instead of the instruction pointer as the
return address), but this design is robust against that now (even though
I've manually verified that that particular glitch still happens with
this patch).

fix #33877

### CODE REVIEW

File: src/julia.h [hunk 1]
```diff
@@ -709,41 +709,41 @@ extern void _JL_GC_PUSHARGS(jl_value_t **, size_t) JL_NOTSAFEPOINT;
...
+  memset(rts_var, 0, sizeof(void*) * (n)); \
+  _JL_GC_PUSHARGS(rts_var, (n));
 
 extern void JL_GC_POP() JL_NOTSAFEPOINT;
 
 #else
 
 #define JL_GC_PUSH1(arg1)                                                 \
-  void *__gc_stkf[] = {(void*)3, jl_pgcstack, arg1};                      \
+  void *__gc_stkf[] = {(void*)5, jl_pgcstack, arg1};                      \
```
Comment (Keno) [inline src/julia.h]: Rather than use magic numbers here have a macro that does the bitshift and marking?

File: src/stackwalk.c [hunk 2]
```diff
@@ -27,6 +27,26 @@ extern "C" {
...
+{
+    jl_gcframe_t *pgcstack = *ppgcstack;
+    while (pgcstack != NULL) {
+        jl_gcframe_t *prev = pgcstack->prev;
+        if (pgcstack->nroots & 2) { // tagged frame
+            uintptr_t frame_fp = ((uintptr_t*)pgcstack)[-1];
+            if (frame_fp == 0)
+                continue; // frame wasn't fully initialized yet
+            if (frame_fp >= sp)
+                break; // stack grows up, so frame pointer is monotonically increasing
```
Comment (JeffBezanson) [inline src/stackwalk.c]:
```suggestion
                break; // stack grows down, so frame pointer is monotonically increasing
```

**Review by JeffBezanson — APPROVED** [review]

File: src/stackwalk.c [hunk 3]
```diff
@@ -37,7 +57,7 @@ static int jl_unw_step(bt_cursor_t *cursor, uintptr_t *ip, uintptr_t *sp, uintpt
 // entries.  If `sp != NULL`, the stack pointer corresponding `bt_data[i]` is
 // stored in `sp[i]`.
 //
-// Flag `add_interp_frames==1` should be set to record an extended backtrace
+// `pgcstack` should be given if you want to record extended backtrace
```
Comment (c42f) [inline src/stackwalk.c]:
```suggestion
// `ppgcstack` should be given if you want to record extended backtrace
```

File: src/interpreter.c [hunk 4]
```diff
@@ -23,9 +23,38 @@ typedef struct {
...
+#define JL_GC_PUSHFRAME(frame, n)     \
+  frame = (interpreter_state*)alloca(sizeof(*frame) + sizeof(void*) * (n)); \
+  memset(&frame[1], 0, sizeof(void*) * n); \
+  _JL_GC_PUSHARGS((jl_value_t**)&frame[1], n);
+
+#else
+
+#define JL_GC_PUSHFRAME(frame,n)                                                    \
+  frame = (interpreter_state*)alloca(sizeof(*frame)+((n)*sizeof(jl_value_t*)));     \
+  ((void**)&frame[1])[-3] = NULL;                                                   \
```
Comment (c42f) [inline src/interpreter.c]: These negative indices are rather confusing. I can see this makes the gcframe layout manifestly compatible with the other places gc frames are created (rather than setting `frame->associated_frame_pointer` etc directly). Took me a bit of squinting to see that though.

File: src/interpreter.c [hunk 5]
```diff
@@ -23,9 +23,38 @@ typedef struct {
...
+// This is necessary, because otherwise the analyzer considers this undefined
+// behavior and terminates the exploration
+#define JL_GC_PUSHFRAME(frame, n)     \
+  frame = (interpreter_state*)alloca(sizeof(*frame) + sizeof(void*) * (n)); \
+  memset(&frame[1], 0, sizeof(void*) * n); \
+  _JL_GC_PUSHARGS((jl_value_t**)&frame[1], n);
+
+#else
+
+#define JL_GC_PUSHFRAME(frame,n)                                                    \
```
Comment (c42f) [inline src/interpreter.c]: This name makes me think the macro mainly to do with GC. But it's also very much to do with the interpreter. I don't have a great suggestion for a better name though... `JL_GC_PUSH_INTERPFRAME`?

**Review by c42f — COMMENTED** [review]
This is an ingenious solution to interpreter frame detection.

:100: to getting rid of interpreter-backtrace.c

File: src/julia.h (hunk 1 above)
Comment (vtjnash) [reply src/julia.h]: I had thought about that, but then wasn't sure this would really help much with code maintenance. It used to be that way with `JL_GC_PUSH()` until 9582f99671f.
```suggestion
#define JL_GC_ENCODE_PUSHARGS(n)   ((n)<<2)
#define JL_GC_ENCODE_PUSH(n)       (((n)<<2)|1)
#define JL_GC_ENCODE_PUSHFRAME(n)  (((n)<<2)|2)

  void *__gc_stkf[] = {(void*)JL_GC_ENCODE_PUSH(1), jl_pgcstack, arg1};                      \
```

File: src/interpreter.c (hunk 4 above)
Comment (vtjnash) [reply src/interpreter.c]: Right, it's not dealing with an interpreter_state, it's dealing with pushing a general gc-frame just like any other. I just happened to only implement `interpreter_state` support.

File: src/interpreter.c (hunk 5 above)
Comment (vtjnash) [reply src/interpreter.c]: The macro only does things with `gc`. It doesn't care what else `frame` happens to be or to do.

File: src/stackwalk.c (hunk 3 above)
Comment (vtjnash) [reply src/stackwalk.c]: It's `pgcstack` that must be given, but I guess it make more sense to encode this as:
```suggestion
// `*ppgcstack` should be given if you want to record extended backtrace
```

Comment (c42f) [reply src/stackwalk.c]: Yes that's much better.

File: src/interpreter.c (hunk 5 above)
Comment (c42f) [reply src/interpreter.c]: Well it sets aside the space and names the type `(interpreter_state*)`. A normal JL_GC_PUSH doesn't do those things.

File: src/interpreter.c [hunk 6]
```diff
@@ -25,7 +25,48 @@ typedef struct {
...
+
+#define JL_GC_ENCODE_PUSHFRAME(n)  ((((size_t)(n))<<2)|2)
+
+#define JL_GC_PUSHFRAME(frame,n)                                                    \
+  JL_CPPALLOCA(frame, sizeof(*frame)+(((n)+3)*sizeof(jl_value_t*)));                \
+  ((void**)&frame[1])[0] = NULL;                                                    \
+  ((void**)&frame[1])[1] = (void*)JL_GC_ENCODE_PUSHFRAME(n);                        \
+  ((void**)&frame[1])[2] = jl_pgcstack;                                             \
+  memset(&((void**)&frame[1])[3], 0, (n)*sizeof(jl_value_t*));                      \
+  jl_pgcstack = (jl_gcframe_t*)&(((void**)&frame[1])[1])
```
Comment (c42f) [inline src/interpreter.c]: Nice resolution.

I do think this makes a lot more sense than putting the space for the frame inside `interpreter_state` :+1:

File: src/llvm-final-gc-lowering.cpp [hunk 7]
```diff
@@ -119,7 +119,7 @@ void FinalLowerGC::lowerPushGCFrame(CallInst *target, Function &F)
     builder.SetInsertPoint(&*(++BasicBlock::iterator(target)));
     Instruction *inst =
         builder.CreateStore(
-            ConstantInt::get(T_size, nRoots << 1),
+            ConstantInt::get(T_size, nRoots << 2),
```
Comment (c42f) [inline src/llvm-final-gc-lowering.cpp]: Should this be `JL_GC_ENCODE_PUSHARGS` as well or is there a subtle difference here?

File: src/stackwalk.c [hunk 8]
```diff
@@ -122,15 +142,25 @@ int jl_unw_stepn(bt_cursor_t *cursor, jl_bt_element_t *bt_data, size_t *bt_size,
...
+                    // now, so just ignore this possibility. If we want this,
+                    // we can work on adding support for it later.
+                }
             }
+            bt_entry->uintptr = call_ip;
+            n++;
         }
+        // TODO: if we have some pgcstack entries remaining (because the
+        // unwinder failed and returned !have_more_frames early), we could
+        // still append those frames here
```
Comment (c42f) [inline src/stackwalk.c]: Am I correct in thinking that this would, however, lead to missing all compiled frames which interleave with the frames which happen to be interpreted? That sounds like it would be more confusing than helpful for the average user.

File: src/stackwalk.c [hunk 9]
```diff
@@ -517,27 +547,19 @@ static int jl_unw_step(bt_cursor_t *cursor, uintptr_t *ip, uintptr_t *sp, uintpt
...
-#ifdef UNW_REG_FP
-    if (unw_get_reg(cursor, UNW_REG_FP, &reg) < 0)
-        return 0;
-    if (fp)
-        *fp = reg;
-#else
-    if (fp)
-        *fp = 0;
-#endif
+    *fp = 0;
```
Comment (c42f) [inline src/stackwalk.c]: So it looks like we don't need `fp` at all anymore? In that case would it be better just to remove this parameter from `jl_unw_step`?

**Review by c42f — APPROVED** [review]
I really like these changes, they're going to greatly improve the ease of working with the interpreter backtrace machinery. A few months ago I was tweaking the `interpreter-stacktrace.c` assembly but it was quite difficult to have confidence that it would work on all platforms. I don't think my changes made it off my branch yet, but I'm going to happily delete those parts after this is merged!

File: src/stackwalk.c (hunk 8 above)
Comment (vtjnash) [reply src/stackwalk.c]: Yeah, it'd just jump to the frames it could still find. Happens sometimes anyways if the unwinder fails.
