### PR TITLE
fix #15723, `findfirst` on strings

### LINKED ISSUE #15723: invalid character index in findfirst
``` jl
julia> findfirst("⨳(",'(')
ERROR: UnicodeError: invalid character index
 in next(::UTF8String, ::Int64) at ./version.jl:106
 [inlined code] from ./strings/basic.jl:37
 in findnext(::UTF8String, ::Char, ::Int64) at ./array.jl:664
 in findfirst(::UTF8String, ::Char) at ./array.jl:670
 in eval(::Module, ::Any) at ./docs/bootstrap.jl:69
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Makes findfirst, findlast, findnext, and findprev more generic by using endof, nextind, and prevind. Also adds a `nextind` method for arrays and `CartesianIndex`.

These functions are scheduled for a refactoring, but in the meantime might as well make them work better.

### CODE REVIEW

File: test/strings/search.jl [hunk 1]
```diff
@@ -379,3 +379,9 @@ end
 @test rsearchindex("\U1f596\U1f596", "\U1f596\U1f596", endof("\U1f596\U1f596\U1f596")) == 1
 
 @test_throws ErrorException "ab" ∈ "abc"
+
+# issue #15723
```
Comment (nalimilan) [inline test/strings/search.jl]: Could be worth testing other cases for each function, e.g. with the searched character is in the middle of the string (with non-ASCII chars around it).

**Review by nalimilan — APPROVED** [review]
That doesn't fix the issue of general iterables, but it's great to get support for strings with so minimal changes.

Since it took me some time to find it, the PR about supporting any iterable is https://github.com/JuliaLang/julia/pull/18668.
