### PR TITLE
Fix rounding when converting Rational to BigFloat

### LINKED ISSUE #718: invalid interval constructed
This is because of this issue in julia: https://github.com/JuliaLang/julia/issues/58432

TL;DR: converting a rational to BigFloat, especially when rounding up or down, has some correctness issues, see code snippet and problem diagnostic in the linked issue

Because of that, sometimes invalid intervals can be constructed

```julia
julia> a = 1 // (big(2)^300 + 1)
1//2037035976334486086268445688409378161051468393665936250636140449354381299763336706183397377

julia> aa = interval(BigFloat, a, a)
[4.90909e-91, 4.9091e-91]₂₅₆_com

julia> inf(aa) > sup(aa)
true

julia> interval(inf(aa), sup(aa))
┌ Warning: ill-formed interval [a, b] with a = 4.909093465297726553095771954986275642975215512499449565111549117187105254721716e-91, b = 4.909093465297726553095771954986275642975215512499449565111549117187105254721673e-91 and decoration d = com. NaI is returned
└ @ IntervalArithmetic ~/.julia/packages/IntervalArithmetic/uYe1Q/src/intervals/construction.jl:443
∅₂₅₆_ill
```

I was expecting the `aa` construction to return `NaI` because of the issue in Julia, but it actually silently returns an invalid interval

### LINKED ISSUE #58432: Incorrect rounding when converting rational to bigfloat
```julia
julia> versioninfo()
Julia Version 1.12.0-beta1
Commit c175ace780d (2025-04-02 11:19 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i7-1255U
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, alderlake)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_EDITOR = hx

julia> a = 1 // (big(2)^300 + 1)
1//2037035976334486086268445688409378161051468393665936250636140449354381299763336706183397377

julia> a_up = BigFloat(a, RoundUp)
4.909093465297726553095771954986275642975215512499449565111549117187105254721673e-91

julia> a_down = BigFloat(a, RoundDown)
4.909093465297726553095771954986275642975215512499449565111549117187105254721716e-91

julia> a_down > a_up
true
```

here the rounded down version is strictly bigger than the rounded up version. Implementation seems to be

```julia
function BigFloat(x::Rational, r::MPFRRoundingMode=rounding_raw(BigFloat); precision::Integer=_precision_with_base_2(BigFloat))
    setprecision(BigFloat, precision) do
        setrounding_raw(BigFloat, r) do
            BigFloat(numerator(x))::BigFloat / BigFloat(denominator(x))::BigFloat
        end
    end
end
```

I think the problem is that here `BigFloat(denominator(x))` is not exact (with default 256 bits precision) and it's rounded up when computing `a_up`, but to correctly round up the ratio, the denominator should be rounded down.

### PR DESCRIPTION
**Pull request by OlivierHnt**
This PR implements @lucaferranti's suggestion.

cc @oscardssmith since you had been assigned at some point.

I believe this PR should be back ported to 1.10, 1.11 since it is a bug.

Closes https://github.com/JuliaLang/julia/issues/58432
Closes https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/718

### CODE REVIEW

File: base/mpfr.jl [hunk 1]
```diff
@@ -391,13 +391,19 @@ BigFloat(x::Union{UInt8,UInt16,UInt32}, r::MPFRRoundingMode=rounding_raw(BigFloa
 BigFloat(x::Union{Float16,Float32}, r::MPFRRoundingMode=rounding_raw(BigFloat); precision::Integer=_precision_with_base_2(BigFloat)) =
     BigFloat(Float64(x), r; precision=precision)
 
-function BigFloat(x::Rational, r::MPFRRoundingMode=rounding_raw(BigFloat); precision::Integer=_precision_with_base_2(BigFloat))
+function BigFloat(x::Rational, r::Base.MPFR.MPFRRoundingMode=Base.MPFR.MPFRRoundNearest; precision::Integer=_precision_with_base_2(BigFloat))
```
Comment (adienes) [inline base/mpfr.jl]: why does the default rounding mode change?

Comment (OlivierHnt) [reply base/mpfr.jl]: I think that's a mistake.

**Comment by adienes** [comment]
a test or two for the "new" (fixed) behavior would be good

**Comment by OlivierHnt** [comment]
I added tests, using the discussion in the issue https://github.com/JuliaLang/julia/issues/58432.

**Comment by OlivierHnt** [comment]
Can we see this PR backported to 1.11.8 (#59521) and 1.12 (#59556)? The changes made here are important, and fairly minor.

Not sure how the process goes usually for this.

cc @KristofferC
