### PR TITLE
optimizer: Handle path-excluded `Core.ifelse` arguments

### LINKED ISSUE #50276: Method error during optimization
MWE:

```julia
df = (A = [missing], B = 1)
map(&, df.A , df.A , df.B > 1)
```

```
Internal error: encountered unexpected error in runtime:
MethodError(f=Base.string, args=(Expr(:&&, Expr(:call, :!==, :then_result, :SKIP_TOKEN), Expr(:call, :!==, :then_result, :UNDEF_TOKEN)),), world=0x00000000000015b0)
jl_method_error_bare at /source/src/gf.c:2204
jl_method_error at /source/src/gf.c:2222
jl_lookup_generic_ at /source/src/gf.c:3053 [inlined]
ijl_apply_generic at /source/src/gf.c:3068
macro expansion at ./error.jl:231 [inlined]
perform_lifting! at ./compiler/ssair/passes.jl:768
lift_comparison_leaves! at ./compiler/ssair/passes.jl:601
lift_comparison! at ./compiler/ssair/passes.jl:553 [inlined]
sroa_pass! at ./compiler/ssair/passes.jl:1011
run_passes at ./compiler/optimize.jl:489
run_passes at ./compiler/optimize.jl:504 [inlined]
optimize at ./compiler/optimize.jl:453 [inlined]
_typeinf at ./compiler/typeinfer.jl:272
typeinf at ./compiler/typeinfer.jl:216
```

As seen on PkgEval during testing of DataFramesMeta.jl.

Bisected to #49882, cc @topolarity.

### PR DESCRIPTION
**Pull request by topolarity**
There are cases where a relevant PiNode implies that `Core.ifelse(%cond, %a, %b)` never yields `%b`.

~~I opted to take the basic path here and just lower to `Core.ifelse(%cond, %a, %a)`. An improved solution would probably replace with `%a` directly, but I haven't convinced myself of the legality conditions for that.~~

Resolves #50276.

### CODE REVIEW

**Comment by Keno** [comment]
> An improved solution would probably replace with `%a` directly

I think that should be always legal.

**Comment by topolarity** [comment]
> I think that should be always legal.

My main concern was about accidentally erasing an exception throw.

What ensures that we preserve that effect? Is it that the original `Core.ifelse` call is guaranteed to be preserved?

**Comment by Keno** [comment]
Ah, I guess make it conditional on `IR_FLAG_NOTHROW`. I supposed it's possible that someone is passing something other than a boolean as the first argument. Though even then you could still take the `ifelse` out of the def-use chain and just make it a separate statement. That can help some downstream passes that walk def-use chains.

**Comment by oscardssmith** [comment]
`Core.ifelse` evals both branches so replacing it's result with an assignment doesn't change anything. It might make the other branch "dead code" but that will only be deleted if the effects pan out.

**Review by Keno — APPROVED** [review]

File: test/compiler/irpasses.jl [hunk 1]
```diff
@@ -742,6 +742,58 @@ let m = Meta.@lower 1 + 1
...
+        Bool,
+        Any,
+        Any
+    ]
+    nstmts = length(src.code)
+    src.codelocs = fill(one(Int32), nstmts)
+    src.ssaflags = fill(one(Int32), nstmts)
+    src.slotflags = fill(zero(UInt8), 3)
+    ir = Core.Compiler.inflate_ir(src)
+    Main.Base.IRShow.show_ir(stdout, ir)
```
Comment (aviatesk) [inline test/compiler/irpasses.jl:791]:
```suggestion
```
or comment out?

Comment (topolarity) [reply test/compiler/irpasses.jl:791]: Yikes, good catch - thank you

File: base/compiler/ssair/passes.jl [hunk 2]
```diff
@@ -767,6 +767,21 @@ function perform_lifting!(compact::IncrementalCompact,
             else_result = lifted_value(compact, old_node_ssa, else_result,
                                        lifted_philikes, lifted_leaves, reverse_mapping)
 
+            # In cases where the Core.ifelse condition is statically-known, e.g., thanks
+            # to a PiNode from a guarding conditional, replace with the remaining branch.
+            if then_result === SKIP_TOKEN || else_result === SKIP_TOKEN
+                only_result = (then_result === SKIP_TOKEN) ? else_result : then_result
+
+                # Replace Core.ifelse(%cond, %a, %b) with %a
+                compact[lf.ssa][:inst] = only_result
```
Comment (Keno) [inline base/compiler/ssair/passes.jl:776]: On second look, this bypasses the count removal of the cond. This probably needs to be:
```
compact[lf.ssa] = nothing
compact[lf.ssa][:inst] = only_result
```

Possibly also consider turning on the oracle check for the tests, which would have caught this.
