### PR TITLE
Fix `--project=@script` when outside script directory

### LINKED ISSUE #55069: `--project=@script` does not activate script project if outside of the Project Directory
Launching a script with `julia --project=@script foo.jl` does not activate the script project if ran outside the containing folder. 

In `test_at_script.jL`
```julia
#!/usr/bin/env -S julia --project=@script
@info "Check Active Env" Base.active_project() PROGRAM_FILE LOAD_PATH Base.load_path_expand("@script")

# Check that ../Project.toml got activated
active_project = realpath(Base.active_project())
expected = realpath(joinpath(@__DIR__, "..", "Project.toml"))
@assert active_project == expected  "$active_project != $expected"
```

Expected Directory Structure:
```
Documents/
    julia_at_script_issue/
        Project.toml
        bin/
            test_at_script.jl
```

> Alternatively, run `script.sh` in the attached achieve: [julia_at_script_issue.zip](https://github.com/user-attachments/files/16130231/julia_at_script_issue.zip)

Running from `Documents/julia_at_script_issue/` with `julia --startup-file=no --project=@script bin/test_at_script.jl` or `./bin/test_at_script.jl` gives the following (expected) output:

```shell
❯ julia --startup-file=no --project=@script bin/test_at_script.jl
┌ Info: Check Active Env
│   Base.active_project() = "/Users/alexwadell/Documents/julia_at_script_issue/Project.toml"
│   PROGRAM_FILE = "bin/test_at_script.jl"
│   LOAD_PATH =
│    3-element Vector{String}:
│     "@"
│     "@v#.#"
│     "@stdlib"
└   Base.load_path_expand("@script") = "Project.toml"
```
However, running from outside of `Documents/julia_at_script_issue` activates the default environment instead:

```shell
❯ julia --project=@script --startup-file=no julia_at_script_issue/bin/test_at_script.jl
┌ Info: Check Active Env
│   Base.active_project() = "/Users/alexwadell/.julia/environments/v1.11/Project.toml"
│   PROGRAM_FILE = "julia_at_script_issue/bin/test_at_script.jl"
│   LOAD_PATH =
│    3-element Vector{String}:
│     "@"
│     "@v#.#"
│     "@stdlib"
└   Base.load_path_expand("@script") = "julia_at_script_issue/Project.toml"
ERROR: LoadError: AssertionError: /Users/alexwadell/.julia/environments/v1.11/Project.tom
l != /Users/alexwadell/Documents/julia_at_script_issue/Project.toml
Stacktrace:
 [1] top-level scope
   @ ~/Documents/julia_at_script_issue/bin/test_at_script.jl:5
in expression starting at /Users/alexwadell/Documents/julia_at_script_issue/bin/test_at_scr
ipt.jl:5
```

Oddly, enough `Base.load_path_expand("@cript")` resolves the correct project file.

Setting `JULIA_LOAD_PATH` directly does result in the expect behavior outside the project directory:

```shell
❯ JULIA_LOAD_PATH=@script julia --startup-file=no julia_at_script_issue/bin/test_at_script.jl
┌ Info: Check Active Env
│   Base.active_project() = "julia_at_script_issue/Project.toml"
│   PROGRAM_FILE = "julia_at_script_issue/bin/test_at_script.jl"
│   LOAD_PATH =
│    1-element Vector{String}:
│     "@script"
└   Base.load_path_expand("@script") = "julia_at_script_issue/Project.toml"
```

## Julia Info

```
Julia Version 1.11.0-rc1
Commit 3a35aec36d1 (2024-06-25 10:23 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_PKG_USE_CLI_GIT = true
```

## Related PRs
#50864 
#53356

### PR DESCRIPTION
**Pull request by awadell1**
Should close #55069 and #55606

As discussed in #55069, this PR adds a `program_file` field to `JLOptions`, allowing the program file to be defined during `Base.__init__()` when `load_path_expand` is first called. The PR is broken into four commits:

- 4c7f4dd: Add tests to replicate the above issues
- 575cd1e: Implements the above fix
- 2828fad: Adds `--project=@script` help text to the cli

### CODE REVIEW

**Comment by awadell1** [comment]
As best I can tell, the test failure appears unrelated to this PR. Should be good for review

cc @tecosaur @Keno @oxinabox @StevenWhitaker

File: test/cmdlineargs.jl [hunk 1]
```diff
@@ -257,6 +257,16 @@ let exename = `$(Base.julia_cmd()) --startup-file=no --color=no`
         @test expanded == readchomp(addenv(`$exename -e 'println(Base.active_project())'`, "JULIA_PROJECT" => "@foo", "HOME" => homedir()))
     end
 
+    # --project=@script handling
+    let expanded = abspath(joinpath(@__DIR__, "project", "ScriptProject"))
+        script = joinpath(expanded, "bin", "script.jl")
+        # Check running julia with --project=@script both within and outside the script directory
+        @testset "--@script from $name" for (name, dir) in [("project", expanded, ("outside", pwd()))]
```
Comment (StevenWhitaker) [inline test/cmdlineargs.jl:264]: It looks like this `for` loop has a misplaced closing parenthesis:
```julia
[("project", expanded, ("outside", pwd()))]
                                         ^
```
I'm guessing should be
```julia
[("project", expanded), ("outside", pwd())]
                     ^
```
Otherwise this loop has only one iteration and ignores `"outside"` and `pwd()`.

Comment (awadell1) [reply test/cmdlineargs.jl]: Good catch, thank you!

**Review by tecosaur — APPROVED** [review]
Looking through the code, this looks sensible to me, though ideally somebody involved in the original PR would give this a stamp of approval and merge.

**Comment by tecosaur** [comment]
Friendly bump @Keno / @oxinabox

**Review by oxinabox — APPROVED** [review]
