### PR TITLE
Try to fix `fma` on windows

### LINKED ISSUE #43386: FMA regression on windows on master (CPU:9600KF)
The detection seems incorrect? (I think 9600KF has native FMA support?)
On 1.7.0
```julia
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CUDA_VERSION = 11.4.0

julia> @code_native fma(1.0,1.0,1.0)
        .text
; ┌ @ floatfuncs.jl:347 within `fma`
        pushq   %rbp
        movq    %rsp, %rbp
; │┌ @ floatfuncs.jl:336 within `fma_llvm`
        vfmadd213sd     %xmm2, %xmm1, %xmm0     # xmm0 = (xmm1 * xmm0) + xmm2
; │└
        popq    %rbp
        retq
        nopl    (%rax,%rax)
```
on master 
```julia
julia> versioninfo()
Julia Version 1.8.0-DEV.1090
Commit d16f4806e9 (2021-12-01 10:54 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CUDA_VERSION = 11.4.0

julia> @code_native fma(1.0,1.0,1.0)
        .text
        .file   "fma"
        .globl  julia_fma_552                   # -- Begin function julia_fma_552
        .p2align        4, 0x90
        .type   julia_fma_552,@function
julia_fma_552:                          # @julia_fma_552
; ┌ @ floatfuncs.jl:416 within `fma`
        .cfi_startproc
# %bb.0:                                # %L5
        pushq   %rbp
        .cfi_def_cfa_offset 16
        .cfi_offset %rbp, -16
        movq    %rsp, %rbp
        .cfi_def_cfa_register %rbp
        subq    $32, %rsp
        movabsq $j_fma_emulated_554, %rax
        callq   *%rax
        addq    $32, %rsp
        popq    %rbp
        retq
.Lfunc_end0:
        .size   julia_fma_552, .Lfunc_end0-julia_fma_552
        .cfi_endproc
; └
                                        # -- End function
        .section        ".note.GNU-stack","",@progbits
```

### PR DESCRIPTION
**Pull request by N5N3**
This PR aims to fix runtime `fma` on windows by adding `julia_fma(f)` using `Base.fma_emulated` as the reference.
On other systems, ~`julia_fma(f)` call~ use `fma(f)` directly.
I use `Base.fma_float` to test `julia_fma(f)`'s precison. And it passed locally.
Since it only affects const propagation, I believe perfomance is not important.
We can remove this code if `fma` on windows get fixed in the future.
Close #43386.

### CODE REVIEW

**Comment by oscardssmith** [comment]
having written the Julia version of this, congrats on having the fortitude it takes to rewrite this! This looks like the best solution to windows being bad for now.

File: src/runtime_intrinsics.c [hunk 1]
```diff
@@ -1174,9 +1174,123 @@ bi_fintrinsic(mul,mul_float)
...
+  ieee_double temp;				\
+  temp.vf64 = (d);				\
+  (ix) = temp.vu64;				\
+} while (0)
+// reinterpret(Float64, ix::UInt64)
+#define BITCAST_U64_F64(d,ix)	\
+do {							\
+    ieee_double temp;			\
+    temp.vu64 = (ix);			\
+    (d) = temp.vf64;			\
```
Comment (oscardssmith) [inline src/runtime_intrinsics.c:1195]: I believe this is UB. I think the correct way to do this is with a `memcpy` (see https://stackoverflow.com/a/3267062/5141328)

Comment (N5N3) [reply src/runtime_intrinsics.c:1195]: I borrowed this pattern from openlibm: https://github.com/JuliaMath/openlibm/blob/master/src/math_private.h#L66-L91.
I‘ll replace it with `memcpy` if that's prefered. 
BTW, thanks again for the julia version!

Comment (oscardssmith) [reply src/runtime_intrinsics.c:1195]: @vtjnash you know this stuff better than me. Is `openlibm` doing a bad here?

Comment (yuyichao) [reply src/runtime_intrinsics.c:1195]: Using a union isn't UB.

**Comment by N5N3** [comment]
@oscardssmith Linux32's run time `fma` seems also broken.
Is it OK to skip the test on Linux32 in this PR? (I have no linux machine.)

**Comment by oscardssmith** [comment]
32 bit linux is passing those tests on master, so they should continue to be tested and pass.

**Comment by N5N3** [comment]
`master` doesn't test runtime fma (call `Base.fma_float(a, b, c)` directly).
I mean keep test `fma` and `Base.fma_emulated`, and skip `Base.fma_float` only.

**Comment by oscardssmith** [comment]
that should be OK.

**Comment by N5N3** [comment]
Well, `math` test passed on `linux32` after skiping `Base.fma_float`.
The failure in `core` shows:
```julia
Error in testset core:
Error During Test at /buildworker/worker/tester_linux32/build/share/julia/test/testdefs.jl:21
  Got exception outside of a @test
  LoadError: OutOfMemoryError()
```
Should be unrelated with this PR.

**Comment by N5N3** [comment]
`core` passed this time. but a new error arised in `threads`:
```julia
Error in testset threads:
Error During Test at /buildworker/worker/tester_linux32/build/share/julia/test/testdefs.jl:21
  Got exception outside of a @test
  LoadError: failed process: Process(setenv(`/buildworker/worker/tester_linux32/build/bin/julia -Cnative -J/buildworker/worker/tester_linux32/build/lib/julia/sys.so -g1 --depwarn=error --rr-detach --startup-file=no threads_exec.jl`,["HOSTNAME=c9184fb58f3f", "PWD=/buildworker/worker/tester_linux32/build", "SHLVL=1", "JULIA_CPU_THREADS=6", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "OLDPWD=/buildworker", "_=/usr/bin/linux32", "JULIA_NUM_THREADS=4", "OPENBLAS_NUM_THREADS=8", "TERM=screen", "HOME=/home/buildworker", "CI=true", "JULIA_TEST_NUM_CORES=6", "JULIA_DEPOT_PATH=/tmp/jl_SW89dW"]), ProcessExited(143)) [143]
  
  Stacktrace:
    [1] pipeline_error
      @ ./process.jl:529 [inlined]
    [2] run(::Base.CmdRedirect; wait::Bool)
      @ Base ./process.jl:444
    [3] run(::Base.CmdRedirect)
      @ Base ./process.jl:442
```
Should also be unrelated with this PR.

**Review by vtjnash — APPROVED** [review]
LGTM. What is wrong with linux32?

**Comment by N5N3** [comment]
I'm not sure, runtime fma test passed locally using official 32bit 1.7.1 on wsl2.
But CI test keeps failing.
Maybe machine dependent?

**Comment by N5N3** [comment]
All test passed after rebasing @vtjnash
