### PR TITLE
fix #30499, document behavior of `return` at top level

### LINKED ISSUE #30499: disallow `return` outside function?
On v1.0.2 I used a return statement from within a let block that got assigned to a variable.  This didn't work as I expected, but it also didn't cause any errors.  The surprising side effect was that the variable assigned to was never actually created.

```julia
julia> x = let
           # some ugly calc
           42
       end
42

julia> x
42

julia> y = let
           # some ugly calc
           return 42
       end
42

julia> y
ERROR: UndefVarError: y not defined
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Also add some missing doc strings for exported names, and improve some other doc strings.

### CODE REVIEW

File: base/Enums.jl [hunk 1]
```diff
@@ -7,6 +7,11 @@ export Enum, @enum
 
 function basetype end
 
+"""
+    Enum
```
Comment (fredrikekre) [inline base/Enums.jl]: Maybe useful to show that it is parametric, e.g.
```suggestion
    Enum{T<:Integer}
```

**Review by ararslan — APPROVED** [review]
