### PR TITLE
Profile: fix indent computation BoundsError

### LINKED ISSUE #34723: div-by-zero in Profie.print indent computation
```
ERROR: BoundsError: attempt to access 50-element Array{Int64,1} at index [0]
Stacktrace:
 [1] getindex at ./array.jl:786 [inlined]
 [2] indent(::Int64) at /Users/jameson/julia/usr/share/julia/stdlib/v1.5/Profile/src/Profile.jl:546
```

### PR DESCRIPTION
**Pull request by vtjnash**
fixes #34723

### CODE REVIEW

File: stdlib/Profile/src/Profile.jl [hunk 1]
```diff
@@ -543,7 +543,9 @@ function indent(depth::Int)
     depth < 1 && return ""
     depth <= length(indent_z) && return indent_s[1:indent_z[depth]]
     div, rem = divrem(depth, length(indent_z))
-    return (indent_s^div) * SubString(indent_s, 1, indent_z[rem])
+    indent = indent_s^div;
```
Comment (JeffBezanson) [inline stdlib/Profile/src/Profile.jl]:
```suggestion
    indent = indent_s^div
```
