### PR TITLE
tfuncs: Be more robust in the face of uninhabited types

### LINKED ISSUE #37943: Tfuncs error on invalid types
Reported by @YingboMa.
Various of our tfuncs assume that types they get will be valid datatypes. However, it
is possible to construct invalid ones. This prints ugly errors:
```
julia> f(x::Any, i::Int) = getfield((x::Pair{false, Int}), i)
f (generic function with 1 method)

julia> code_typed(f, Tuple{Any, Int})[1][2]
ERROR: MethodError: no method matching widenconst(::Bool)
Closest candidates are:
  widenconst(::Core.Compiler.Conditional) at compiler/typelattice.jl:207
  widenconst(::Core.Const) at compiler/typelattice.jl:208
  widenconst(::Core.Compiler.MaybeUndef) at compiler/typelattice.jl:218
  ...
Stacktrace:
  [1] tmerge(typea::Any, typeb::Any)
    @ Core.Compiler ./compiler/typelimits.jl:354
  [2] getfield_tfunc(s00::Any, name::Any)
    @ Core.Compiler ./compiler/tfuncs.jl:866
  [3] builtin_tfunction(interp::Core.Compiler.Ab
```

### PR DESCRIPTION
**Pull request by Keno**
Fixes #37943

### CODE REVIEW

File: test/compiler/inference.jl [hunk 1]
```diff
@@ -2841,3 +2841,11 @@ f37532(T, x) = (Core.bitcast(Ptr{T}, x); x)
 
 # issue #37638
 @test !(Core.Compiler.return_type(() -> (nothing, Any[]...)[2], Tuple{}) <: Vararg)
+
+# Issue #37943
+f37943(x::Any, i::Int) = getfield((x::Pair{false, Int}), i)
+g37943(i::Int) = fieldtype(Pair{false, T} where T, i)
+@test code_typed(f37943, Tuple{Any, Int})[1][2] === Union{}
+@test code_typed(g37943, Tuple{Int})[1][2] === Any
```
Comment (vtjnash) [inline test/compiler/inference.jl:2849]:
```suggestion
@test only(Base.return_types(f37943, Tuple{Any, Int})) === Union{}
@test only(Base.return_types(g37943, Tuple{Int})) === Any
```

**Review by vtjnash — APPROVED** [review]

File: base/compiler/tfuncs.jl [hunk 2]
```diff
@@ -853,6 +853,14 @@ function getfield_tfunc(@nospecialize(s00), @nospecialize(name))
     if isa(name, Conditional)
         return Bottom # can't index fields with Bool
     end
+    for _ft in ftypes
+        if (!isa(_ft, Type) && !isa(_ft, TypeVar)) || _ft === Bottom
```
Comment (JeffBezanson) [inline base/compiler/tfuncs.jl:857]: What about a type like this:
```
struct Foo
    x
    y::Union{}
    Foo(x) = new(x)
end
```

Comment (JeffBezanson) [reply base/compiler/tfuncs.jl:857]: Or similarly this, but this case should possibly be disallowed on construction:
```
struct Bar{T}
    x
    y::T
    Bar{T}(x) where {T} = new(x)
end
Bar{false}(1)
```

Comment (Keno) [reply base/compiler/tfuncs.jl:857]: Is that legal? I guess there's nothing technically wrong with it, but boy. I guess I'll add a check to only bail if it's one of the initialized fields.

Comment (JeffBezanson) [reply base/compiler/tfuncs.jl:857]: The first one is definitely legal. The second one probably shouldn't be, since a constructable type needs a layout, and if a field type is a non-type it's impossible to say what its layout is.

Comment (vtjnash) [reply base/compiler/tfuncs.jl:857]: There's also `s.has_concrete_subtype` which has already checked for conditions such as that?

It's not impossible to describe the layout, but impossible for that field to have a value. We could also treat it similar to apply_type failures, which returns the uninhabited type for the fieldtype and expand the check there (in `inst_ftypes`) instead of here:
```
julia> struct Bar{T}
           x
           y::Complex{T}
           Bar{T}(x) where {T} = new(x)
       end

julia> fieldtypes(Bar{false})
(Any, Union{})
```

Comment (vtjnash) [reply base/compiler/tfuncs.jl:857]: Yeah, there's no particular necessity in saying the field has type "false", when it's not even valid as a type

**Comment by Keno** [comment]
Updated as discussed.

**Review by vtjnash — APPROVED** [review]
