### PR TITLE
A trick to fix continue/break/return handling in for loop testset.

### LINKED ISSUE #17908: Base.Test does not support continue statement
Using `Base.Test` on master, 

```
@testset "Testing 1..3" for i=1:3
           @test 1 == 1
       end
```

results in 

```
Test Summary: | Pass  Total
  Testing 1..3 |    1      1
Test Summary: | Pass  Total
  Testing 1..3 |    1      1
Test Summary: | Pass  Total
  Testing 1..3 |    1      1
```

as expected. However, adding a continue statement set to trigger on `i=2`, causes the whole `testset` to stop on `i=2` and not continue to `i=3`. 

```
@testset "Testing 1..3" for i=1:3
           if i%2 == 0
               continue
           end
           @test 1 == 1
       end
```

results in 
```
Test Summary: | Pass  Total
  Testing 1..3 |    1      1
```

Furthermore, once I have run one `testset` in a REPL that contained a call to `continue`, any regular (non-continued) testset now returns `Nothing`. i.e. 

```
@testset "Testing 1..3" for i=1:3
           @test 1 == 1
       end
``` 

returns 

```
3-element Array{Union{Base.Test.DefaultTestSet,Base.Test.FallbackTestSet,Void},1}:
 nothing
 nothing
 nothing
```

and does not print any test results to the terminal. 

I can confirm that this also happens on `release-0.5`

Maybe having the continue statement not interact with a `testset` is by design, but having one `testset` with a continue make all future REPL `testset`'s not correct is definitely a bug.

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #17908

I realized that the test for #17462 could have been swallowing test errors for all tests running on the same worker.....

### CODE REVIEW

File: test/test.jl [hunk 1]
```diff
@@ -183,6 +183,50 @@ end
 @test typeof(tss[1]) == Base.Test.DefaultTestSet
 @test typeof(tss[1].results[1]) == Base.Test.Pass
 
+# Issue #17908 (return)
+testset_depth17908 = Test.get_testset_depth()
+@testset for i in 1:3
+    i > 1 && return
+    @test i == 1
+end
+# The return abort the control flow so the expression above doesn't return a
```
Comment (tkelman) [inline test/test.jl]: aborts
