### PR TITLE
Fix FileMonitor test case on FreeBSD

### LINKED ISSUE #8078: file test failure on freebsd10
```
$ gmake test-file
    JULIA test/file
exception on 1: ERROR: test failed: fname == basename(file)
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in test_monitor_wait at file.jl:149
 in runtests at /usr/home/nolta/julia/test/testdefs.jl:5
 in anonymous at multi.jl:660
 in run_work_thunk at multi.jl:621
 in remotecall_fetch at multi.jl:694
 in remotecall_fetch at multi.jl:709
 in anonymous at task.jl:1365
while loading file.jl, in expression starting on line 161
ERROR: test failed: fname == basename(file)
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in test_monitor_wait at file.jl:149
 in runtests at /usr/home/nolta/julia/test/testdefs.jl:5
 in anonymous at multi.jl:660
 in run_work_thunk at multi.jl:621
 in remotecall_fetch at multi.jl:694
 in remotecall_fetch at multi.jl:709
 in anonymous at task.jl:1365
while loading file.jl, in expression starting on line 161
while loading /usr/home/nolta/julia/test/runtests.jl, in expression starting on line 35
     * file

gmake[1]: *** [file] Error 1
gmake: *** [test-file] Error 2
```

### PR DESCRIPTION
**Pull request by iblislin**
close #8078

On FreeBSD, the F_GETPATH is not available in fcntl.
The path returned by libuv will be NULL.

Ref:
https://github.com/libuv/libuv/blob/309d603382159eacdf52cbf0fa936deb60552d32/src/unix/kqueue.c#L353-L361

And the test case in libuv:
https://github.com/libuv/libuv/blob/309d603382159eacdf52cbf0fa936deb60552d32/test/test-fs-event.c#L315-L318

### CODE REVIEW

File: test/file.jl [hunk 1]
```diff
@@ -236,7 +236,11 @@ function test_monitor_wait(tval)
     end
     fname, events = wait(fm)
     close(fm)
-    @test fname == basename(file)
+    if is_linux() || is_windows() || is_apple()
+        @test fname == basename(file)
+    else
+        @test fname == ""  # the platform which F_GETPATH is not available
```
Comment (tkelman) [inline test/file.jl]: I'd word this as "platforms where F_GETPATH is not available"

Comment (iblis17) [inline test/file.jl]: 👌

**Comment by ararslan** [comment]
Have you confirmed that this actually fixes the linked issue, which specifically mentions FreeBSD 10? (Can Julia even build on FreeBSD 10? I haven't tried.)

**Comment by iblis17** [comment]
@ararslan 
Let me explain more details: the test cases mentioned in #8078 will set a function written in Julia and pass it as libuv's `fs_event` callback function. One of parameter is the file path related to the event; our test case will check this path.
But the value of path on FreeBSD is always `NULL`, due to libuv requires F_GETPATH method(https://github.com/libuv/libuv/blob/309d603382159eacdf52cbf0fa936deb60552d32/src/unix/kqueue.c#L353-L361), but FreeBSD do not (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198570).

> Have you confirmed that this actually fixes the linked issue, which specifically mentions FreeBSD 10? 

I think all version of FreeBSD will get the same result on this test case.

>(Can Julia even build on FreeBSD 10? I haven't tried.)

Yes, Julia in ports tree (0.5) also supports 10.3-REALEASE.
