### PR TITLE
Fix length calculation of broadcast over tuples

### LINKED ISSUE #23647: Inconsistency in tuple 1 and 0 broadcast
```julia
julia> [1] .+ [1, 2, 3]
3-element Array{Int64,1}:
 2
 3
 4

julia> [1] .+ []
0-element Array{Any,1}

julia> (1,) .+ (1, 2, 3)
(2,)  # should be (2, 3, 4)

julia> (1,) .+ ()
ERROR: BoundsError: attempt to access ()
  at index [1]
Stacktrace:
 [1] (::getfield(Base.Broadcast, Symbol("##3#4")){typeof(+),Tuple{Tuple{Int64},Tuple{}}})(::Int64) at ./broadcast.jl:338
 [2] broadcast(::Function, ::Tuple{Int64}, ::Tuple{}) at ./broadcast.jl:434
```

The expected result would have been `()` to be consistent with the array case, and with the other tuple broadcast case.

### PR DESCRIPTION
**Pull request by p-zubieta**
Fixes #23647

### CODE REVIEW

**Comment by Sacha0** [comment]
Was #23647 introduced by #21331? The length determination logic that existed prior to #21331 seems a bit simpler than that in this pull request?

File: base/broadcast.jl [hunk 1]
```diff
@@ -127,6 +127,7 @@ end
 end
 
 Base.@propagate_inbounds _broadcast_getindex(A, I) = _broadcast_getindex(containertype(A), A, I)
+Base.@propagate_inbounds _broadcast_getindex(::Type{Tuple}, A::Tuple{Any}, I) = A[1]
```
Comment (Sacha0) [inline base/broadcast.jl]: Should `A[1]` not be `A[I]`?

**Comment by pabloferz** [comment]
> The length determination logic that existed prior to #21331 seems a bit simpler than that in this pull request?

The problem with the previous approach is that it was hard to get a type stable result, that was the reason for #21331 but that solution wasn't good enough.

File: base/broadcast.jl (hunk 1 above)
Comment (pabloferz) [reply base/broadcast.jl]: No, you can see that there is a `::Tuple{Any}` in the signature, we need this for handling cases like `(1,2,3) .+ (1,)`. This shouldn't be a problem as we want `(x,)` where `x` is a scalar to behave the same as `[x]` or `x`.

Comment (Sacha0) [reply base/broadcast.jl]: Yes, I missed the `Any` last night :). To make this method's purpose clearer, perhaps add a comment or an adjacent general method
```julia
Base.@propagate_inbounds _broadcast_getindex(::Type{Tuple}, A::Tuple, I) = A[I]
```
though it would be redundant with
```julia
Base.@propagate_inbounds _broadcast_getindex(::Any, A, I) = A[I]
```
below?

**Comment by Sacha0** [comment]
> The problem with the previous approach is that it was hard to get a type stable result, that was the reason for #21331 but that solution wasn't good enough.

Yes, rather I was wondering whether the simpler former logic could be improved while remaining simpler than that in this pull request. A few comments describing the logic in this pull request would do the trick as well :). Best!

File: base/broadcast.jl (hunk 1 above)
Comment (pabloferz) [reply base/broadcast.jl]: I have added a comment.

**Comment by pabloferz** [comment]
> Yes, rather I was wondering whether the simpler former logic could be improved while remaining simpler than that in this pull request.

I couldn't come up with a simpler approach, but I have added comments as you suggested. The wording could probably be improved, so if you have any suggestions about it, I'm all ears.

File: base/broadcast.jl [hunk 2]
```diff
@@ -333,13 +336,35 @@ end
...
 @inline tuplebroadcast(f, ::NTuple{N,Any}, As...) where {N} =
     ntuple(k -> f(tuplebroadcast_getargs(As, k)...), Val(N))
 @inline tuplebroadcast(f, ::NTuple{N,Any}, ::Type{T}, As...) where {N,T} =
     ntuple(k -> f(T, tuplebroadcast_getargs(As, k)...), Val(N))
-first_tuple(A::Tuple, Bs...) = A
-@inline first_tuple(A, Bs...) = first_tuple(Bs...)
+# When the result of broadcast is a tuple it can only come from mixing n-tuples
+# of the same length with scalars and 1-tuples. So, in order to have a
+# type-stable broadcast we need to find a tuple of maximum length (except when
+# there are only scalars empty tuples and empty tuples, in which case the
```
Comment (Sacha0) [inline base/broadcast.jl]: One too many "empty tuples?"

**Comment by Sacha0** [comment]
:100: for the comments! :)

**Comment by pabloferz** [comment]
Because of a possible mess with ambiguities, I decided to use the `containertype` trait to disambiguate methods. I believe this makes also the implementation much clearer (in addition to the presence of some comments)

**Comment by pabloferz** [comment]
Has anyone have more comments/objections? If not I'd like to merge this in a day or two.

**Review by mbauman — APPROVED** [review]

File: base/broadcast.jl [hunk 3]
```diff
@@ -333,13 +335,32 @@ end
...
+# type-stable broadcast, we need to find a tuple of maximum length (except when
+# there are only scalars, empty tuples and 1-tuples, in which case the
+# returned value will be an empty tuple).
+# The following methods compare broadcast arguments pairwise to determine the
+# length of the final tuple.
+tuplebroadcast_maxtuple(A, B) =
+    _tuplebroadcast_maxtuple(containertype(A), containertype(B), A, B)
+@inline tuplebroadcast_maxtuple(A, Bs...) =
+    tuplebroadcast_maxtuple(A, tuplebroadcast_maxtuple(Bs...))
+tuplebroadcast_maxtuple(A::NTuple{N,Any}, ::NTuple{N,Any}...) where {N} = A
```
Comment (TotalVerb) [inline base/broadcast.jl]: I think this needs to be a `_tuplebroadcast_maxtuple` method, for example with the testcase `broadcast(+, (1, 2), (3, 4), 5)`.

Comment (pabloferz) [reply base/broadcast.jl]: That example works with this PR as is. I had it like this to reduce the compiler/inference work in cases where you have a bunch of tuples of the same length and a scalar element (which I imagined would be common), e.g. `(1,2) .+ (2,3) .+ (3,4) .+ (4,5) .+ 1`. But I can make it a `_tuplebroadcast_maxtuple` for conciseness if preferred.

**Comment by TotalVerb** [comment]
Wouldn't a method for two tuples of the same length be necessary anyway? This method can be kept as a specialization, right?

**Comment by timholy** [comment]
In case it's of interest, #23939 has a `longest` method.

**Comment by pabloferz** [comment]
> Wouldn't a method for two tuples of the same length be necessary anyway? This method can be kept as a specialization, right?

Yes a method for tuples of the same length is necessary. And the current one could be changed into `_tuplebroadcast_maxtuple` specialization, but I wrote it like this as an optimization for inference/compilation (as opposed to a runtime optimization). This could not be all that important (someone like @vtjnash could check if it's worth it), in which case I can change it.

> In case it's of interest, #23939 has a longest method.

Thanks Tim, I don't think both behave the same (but that PR is really nice, I'm going to take a closer look into it).

**Comment by Sacha0** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23887#issuecomment-333997562) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/327a12d7d40c67b791ef9e0a8a8f5b9c181e0ccd/97cd701_vs_f2b4ff5/report.md). cc @ararslan

**Comment by Sacha0** [comment]
@nanosoldier `runbenchmarks("tuple" || "scalar", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23887#issuecomment-334036937) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/981461be86243ec3d6478d7deaa05b2fddc1a237/97cd701_vs_f2b4ff5/report.md). cc @ararslan

**Comment by ararslan** [comment]
Good to go?

File: base/broadcast.jl (hunk 3 above)
Comment (TotalVerb) [reply base/broadcast.jl]: Sorry, I screwed up the order of my example. It should be `broadcast(+, 5, (1, 2), (3, 4))` which I believe would not currently work.

**Comment by TotalVerb** [comment]
@pabloferz Please confirm the behavior of `broadcast(+, 5, (1, 2), (3, 4))`; while I have not tested the code I still believe the mentioned `_tuplebroadcast_maxtuple` method to be necessary.

File: base/broadcast.jl (hunk 3 above)
Comment (pabloferz) [reply base/broadcast.jl]: I can confirm that example (or `broadcast(+, 5, (1, 2), (3, 4))`) works fine.

`tuplebroadcast_maxtuple` will call `_tuplebroadcast_maxtuple` only when the number or arguments to `tuplebroadcast_maxtuple` is two and both are not tuples of the same lengths (if the they are dispatch would select `tuplebroadcast_maxtuple(A::NTuple{N,Any}, ::NTuple{N,Any}...) where {N}` instead).

**Comment by pabloferz** [comment]
@TotalVerb the behaviour of broadcast for the examples you have mentioned seems to be the expected with this PR.

File: base/broadcast.jl (hunk 3 above)
Comment (TotalVerb) [reply base/broadcast.jl]: Oh, I understand. Thanks for the correction.
