### PR TITLE
precompilation: fix show_progress crash when bar.current goes negative

### LINKED ISSUE #61333: precompilation: `show_progress` throws: `can't repeat a string -1 times`
```julia-repl
julia> using BenchmarkTools: @btime
[ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
Precompiling BenchmarkTools finished.
  9 dependencies successfully precompiled in 23 seconds. 8 already precompiled.

julia> using ProfileView: @profview
[ Info: Precompiling ProfileView [c46f51b8-102a-5cf2-8d2c-8597cb0e0da7]
ERROR: TaskFailedException━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/88
Stacktrace:t
  [1] #wait#581ays
    @ ./task.jl:363 [inlined]
  [2] wait
    @ ./task.jl:360 [inlined]
  [3] _precompilepkgs(pkgs::Vector{Base.PkgId}, internal_call::Bool, strict::Bool, warn_loaded::Bool, timing::Bool, _from_loading::Bool, configs::Vector{Pair{…}}, io::IOContext{IO}, fancyprint′::Bool, manifest::Bool, ignore_loaded::Bool)
    @ Base.Precompilation ./precompilation.jl:1258
  [4] precompilepkgs(pkgs::Vector{Base.PkgId}; internal_call::Bool, strict::Bool, warn_loaded::Bool, timing::Bool, _from_loading::Bool, configs::Pair{Cmd, Base.CacheFlags}, io::Base.TTY, fancyprint::Bool, manifest::Bool, ignore_loaded::Bool)
    @ Base.Precompilation ./precompilation.jl:590
  [5] kwcall(::@NamedTuple{_from_loading::Bool, ignore_loaded::Bool}, ::typeof(Base.Precompilation.precompilepkgs), pkgs::Vector{Base.PkgId})
    @ Base.Precompilation ./precompilation.jl:576
  [6] #invokelatest_gr#222
    @ ./reflection.jl:1374 [inlined]
  [7] invokelatest_gr
    @ ./reflection.jl:1366 [inlined]
  [8] (::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, Base.PkgLoadSpec, Dict{String, Int64}, Base.RefValue{Bool}})()
    @ Base ./loading.jl:2876
  [9] mkpidlock(f::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, Base.PkgLoadSpec, Dict{String, Int64}, Base.RefValue{Bool}}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-b4aba01002/share/julia/stdlib/v1.14/FileWatching/src/pidfile.jl:97
 [10] #mkpidlock#7
    @ ~/tmp/jl/jl/julia-b4aba01002/share/julia/stdlib/v1.14/FileWatching/src/pidfile.jl:92 [inlined]
 [11] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile ~/tmp/jl/jl/julia-b4aba01002/share/julia/stdlib/v1.14/FileWatching/src/pidfile.jl:118
 [12] #invokelatest_gr#222
    @ ./reflection.jl:1374 [inlined]
 [13] invokelatest_gr
    @ ./reflection.jl:1366 [inlined]
 [14] maybe_cachefile_lock(f::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, Base.PkgLoadSpec, Dict{String, Int64}, Base.RefValue{Bool}}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base ./loading.jl:4144
 [15] maybe_cachefile_lock
    @ ./loading.jl:4141 [inlined]
 [16] __require_prelocked(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2861
 [17] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2695
 [18] macro expansion
    @ ./loading.jl:2622 [inlined]
 [19] macro expansion
    @ ./lock.jl:376 [inlined]
 [20] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2586
 [21] require
    @ ./loading.jl:2562 [inlined]
 [22] eval_import_path
    @ ./module.jl:36 [inlined]
 [23] eval_import_path_all(at::Module, path::Expr, keyword::String)
    @ Base ./module.jl:60
 [24] _eval_import(::Bool, ::Module, ::Expr, ::Expr, ::Vararg{Expr})
    @ Base ./module.jl:101
 [25] top-level scope
    @ REPL[1]:1

    nested task error: ArgumentError: can't repeat a string -1 times
    Stacktrace:
      [1] repeat(s::String, r::Int64)
        @ Base ./strings/substring.jl:272
      [2] repeat
        @ ./strings/substring.jl:269 [inlined]
      [3] ^
        @ ./strings/basic.jl:771 [inlined]
      [4] (::Base.Precompilation.var"#4#5"{…})(io::IOContext{…})
        @ Base.Precompilation ./precompilation.jl:362
      [5] #sprint#421
        @ ./strings/io.jl:107 [inlined]
      [6] sprint
        @ ./strings/io.jl:102 [inlined]
      [7] show_progress(io::IOContext{IOBuffer}, p::Base.Precompilation.MiniProgressBar; termwidth::Int64, carriagereturn::Bool)
        @ Base.Precompilation ./precompilation.jl:357
      [8] show_progress
        @ ./precompilation.jl:325 [inlined]
      [9] #_precompilepkgs##21
        @ ./precompilation.jl:1007 [inlined]
     [10] #sprint#421
        @ ./strings/io.jl:107 [inlined]
     [11] sprint
        @ ./strings/io.jl:102 [inlined]
     [12] (::Base.Precompilation.var"#_precompilepkgs##19#_precompilepkgs##20"{…})(iostr::IOBuffer)
        @ Base.Precompilation ./precompilation.jl:1007
     [13] #sprint#421
        @ ./strings/io.jl:109 [inlined]
     [14] sprint
        @ ./strings/io.jl:102 [inlined]
     [15] macro expansion
        @ ./precompilation.jl:997 [inlined]
     [16] macro expansion
        @ ./lock.jl:376 [inlined]
     [17] (::Base.Precompilation.var"#_precompilepkgs##17#_precompilepkgs##18"{…})()
        @ Base.Precompilation ./precompilation.jl:987
Some type information was truncated. Use `show(err)` to see complete types.

julia> versioninfo()
Julia Version 1.14.0-DEV.1893
Commit b4aba01002b (2026-03-15 04:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-20.1.8 (ORCJIT, znver2)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 2
  JULIA_PKG_PRECOMPILE_AUTO = 0
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #61333

There's likely a better fix for locking around incrementing these counters together, but I'd handle that after https://github.com/JuliaLang/julia/pull/60943

So just protect for now.

### CODE REVIEW

**Comment by KristofferC** [comment]
It might be worth making the actual printing code more robust as well, like clamping these values:

https://github.com/JuliaLang/julia/blob/a03bd9e921a1d845c7af5f715d6afb0bdbf6f026/base/precompilation.jl#L353-L355

File: base/precompilation.jl [hunk 1]
```diff
@@ -350,8 +350,9 @@ function show_progress(io::IO, p::MiniProgressBar; termwidth=nothing, carriagere
     end
     termwidth = @something termwidth (displaysize(io)::Tuple{Int,Int})[2]
     max_progress_width = max(0, min(termwidth - textwidth(p.header) - textwidth(progress_text) - 10 , p.width))
-    n_filled = floor(Int, max_progress_width * perc / 100)
-    partial_filled = (max_progress_width * perc / 100) - n_filled
+    perc_clamped = clamp(perc, 0.0, 100.0)
+    n_filled = floor(Int, max_progress_width * perc_clamped / 100)
```
Comment (topolarity) [inline base/precompilation.jl]:
```suggestion
    n_filled = floor(Int, max_progress_width * clamp(perc / 100, 0.0, 1.0))
```

just to make the clamping more obviously correct, rather than having to reason about whether `* 100 / 100` might round.

File: base/precompilation.jl [hunk 2]
```diff
@@ -350,8 +350,8 @@ function show_progress(io::IO, p::MiniProgressBar; termwidth=nothing, carriagere
     end
     termwidth = @something termwidth (displaysize(io)::Tuple{Int,Int})[2]
     max_progress_width = max(0, min(termwidth - textwidth(p.header) - textwidth(progress_text) - 10 , p.width))
-    n_filled = floor(Int, max_progress_width * perc / 100)
-    partial_filled = (max_progress_width * perc / 100) - n_filled
+    n_filled = floor(Int, max_progress_width * clamp(perc / 100, 0.0, 1.0))
+    partial_filled = (max_progress_width * perc_clamped / 100) - n_filled
```
Comment (topolarity) [inline base/precompilation.jl]:
```suggestion
    filled = max_progress_width * clamp(perc / 100, 0.0, 1.0)
    (partial_filled, n_filled::Int64) = modf(filled) # get fractional / integer part
```

Sorry my suggestion left it out, but this should be done in both spots. Try this

**Review by topolarity — APPROVED** [review]
