### PR TITLE
[JuliaLowering] Separate type parameter scope from inner constructor scope

### LINKED ISSUE #508: Boxed capture false positive with inner constructors and type parameters
Inner constructors seem to be misinterpreted as closures that may capture type parameters from the struct scope, leading to incorrect diagnostics like in the following screenshot:

Image

MWE as text for your copy-pasting convenience:

```julia
struct Foo{T}
    x::T
    function Foo(x)
        T = typeof(x)
        return new{T}(x)
    end
end
```

### PR DESCRIPTION
**Pull request by aviatesk**
User-defined inner constructors are now placed in a separate scope_block outside the type parameter scope, matching flisp behavior. This ensures that local variables in inner constructors are distinct bindings from type parameters of the same name.

~~Note: For full flisp compatibility, default constructors should also be placed outside the type parameter scope. However, JuliaLowering currently generates default constructor code at compile time (unlike flisp which calls `_defaultctors` at runtime), and this code references field_types directly in function signatures, requiring access to type parameter bindings. Therefore, default constructors remain inside the type parameter scope for now.~~

EDIT: Now this PR aligns JuliaLowering with flisp behavior by using `Core._defaultctors` to generate default constructors at runtime instead of generating constructor code at compile time.

Additionally, inner constructors now use `GlobalRef` directly to reference the struct type, eliminating the need for a global declaration in their `scope_block`. This removes the duplicate `declare_global` that
was previously emitted for structs with user-defined inner constructors.

The `scope_block` for inner constructors is retained to prevent helper functions defined in the struct body from leaking to the module's global scope.

Fixes aviatesk/JETLS.jl#508

### CODE REVIEW

**Comment by vtjnash** [comment]
> unlike flisp which calls _defaultctors at runtime

It sounds like this was modeled on the old buggy version of ctor lowering from flisp, since the switch to `_defaultctors` is a newer bugfix

**Comment by aviatesk** [comment]
Yes, I agree a proper fix would be to update JuliaLowering to use `_defaultctors`.
I think it would be a large change, so it might be better to do it in a separate PR.

**Comment by aviatesk** [comment]
I've switched to using `Core._defaultctors`, since it makes the generated IR much simpler so is probably better done in this PR. As a bonus, this also let us clean up the duplicate `declare_global` that was being emitted for structs with inner constructors.

File: JuliaLowering/src/desugaring.jl [hunk 1]
```diff
@@ -4067,6 +4067,19 @@ function expand_struct_def(ctx, ex, docs)
         end
     end
 
+    # GlobalRef for use outside scope_block (for _defaultctors and inner constructors)
+    struct_globalref = GlobalRef(ctx.mod, Symbol(struct_name.name_val))
```
Comment (mlechu) [inline JuliaLowering/src/desugaring.jl]: I'm not sure I understand why we need a new GlobalRef here; can't we just use `global_struct_name`?  It should be in-scope for anything in the struct's scope block.

**Comment by mlechu** [comment]
Change sounds good conceptually.  I'm fine with calling out to flisp in `_defaultctors` for now.  We should eventually implement that too, but it's not like we're getting great provenance for mostly-generated code anyway.

File: JuliaLowering/src/desugaring.jl (hunk 1 above)
Comment (aviatesk) [reply JuliaLowering/src/desugaring.jl]: I don't think there's any strong reason for it. I wasn't sure if I could freely access variables from the parent struct definition scope within the inner constructor scope. Since it turned out that `global_struct_name` can be used from the inner constructor scope thanks to the scope analysis on the entire struct definition thunk, I think your idea would work fine (allowing simpler implementation). `global_struct_name` should be lowered to a `GlobalRef` anyway, so there shouldn't be any problem.

Comment (mlechu) [reply JuliaLowering/src/desugaring.jl]: Sounds reasonable, I mainly commented since the rest of desugaring and lowering assume identifiers are `K"Identifier"` or `K"BindingId"`

**Review by mlechu — APPROVED** [review]
