### PR TITLE
exact `BigFloat` to IEEE FP conversion in pure Julia

### LINKED ISSUE #50642: `BigFloat` incorrectly rounded to `Float16` (subnormals)
`julia_rounding_experiment.jl`
```julia
distance(x, y) = abs(x - y)

function rounding_experiment(bf::BigFloat, r::AbstractFloat)
  p = prevfloat(r)
  n = nextfloat(r)

  r_dist = distance(bf, r)
  p_dist = distance(bf, p)
  n_dist = distance(bf, n)

  if !((r_dist ≤ p_dist) & (r_dist ≤ n_dist))
    print("rounding $r not correct: ")
    if p_dist ≤ n_dist
      println("$p is the correct rounding")
    else
      println("$n is the correct rounding")
    end
  end

  nothing
end

f16_rounding_experiment(bf::BigFloat) = rounding_experiment(bf, Float16(bf))

setprecision(BigFloat, 500)

f16_rounding_experiment(big"1.4901162082026128889687591176485489397376143775948511e-07")
```

```julia-repl
julia> include("/home/nsajko/julia_rounding_experiment.jl")
rounding 1.0e-7 not correct: 2.0e-7 is the correct rounding

julia> versioninfo()
Julia Version 1.11.0-DEV.139
Commit bf00ff4a110 (2023-07-21 19:34 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 1 on 8 virtual cores
```

### PR DESCRIPTION
**Pull request by nsajko**
There's lots of code, but most of it seems like it will be useful in general. For example, I think I'll use the changes in float.jl and rounding.jl to improve the #49749 PR. The changes in float.jl could also be used to refactor float.jl to remove many magic constants.

Benchmarking script:
```julia
using BenchmarkTools
f(::Type{T} = BigFloat, n::Int = 2000) where {T} = rand(T, n)
g!(u, v) = map!(eltype(u), u, v)
@btime g!(u, v) setup=(u = f(Float16); v = f();)
@btime g!(u, v) setup=(u = f(Float32); v = f();)
@btime g!(u, v) setup=(u = f(Float64); v = f();)
```

On master (dc064683087d017927381e):
```
  46.116 μs (0 allocations: 0 bytes)
  38.842 μs (0 allocations: 0 bytes)
  37.039 μs (0 allocations: 0 bytes)
```

With both this commit and #50674 applied:
```
  42.310 μs (0 allocations: 0 bytes)
  42.661 μs (0 allocations: 0 bytes)
  41.608 μs (0 allocations: 0 bytes)
```

So, with this benchmark at least, on an AMD Zen 2 laptop, conversion to `Float16` is faster, but there's a slowdown for `Float32` and `Float64`.

Fixes #50642 (exact conversion to `Float16`)

### CODE REVIEW

File: base/float.jl [hunk 1]
```diff
@@ -137,6 +137,68 @@ i.e. the maximum integer value representable by [`exponent_bits(T)`](@ref) bits.
 """
 function exponent_raw_max end
 
+"""
+IEEE 754 definition of the minimum exponent.
+"""
+ieee754_exponent_min(::Type{T}) where {T<:IEEEFloat} = Int(1 - exponent_max(T))::Int
+
+exponent_min(::Type{Float16}) = ieee754_exponent_min(Float16)
```
Comment (oscardssmith) [inline base/float.jl:145]: Do these functions need to exist?

File: base/float.jl [hunk 2]
```diff
@@ -137,6 +137,68 @@ i.e. the maximum integer value representable by [`exponent_bits(T)`](@ref) bits.
...
+    T = uinttype(F)
+    ret::T = sign_bit
+    ret <<= exponent_bits(F)
+    ret |= exponent_field
+    ret <<= significand_bits(F)
+    ret |= significand_field
+end
+
+# ±floatmax(T)
+function ieee754_representation(
```
Comment (oscardssmith) [inline base/float.jl:161]: Do any of these functions need to exist? Why are they better than `floatmax`/ `Inf` etc?

**Comment by oscardssmith** [comment]
Thank you so much for writing this! I have a few minor style nits, but overall it looks really good.

File: base/float.jl (hunk 2 above)
Comment (nsajko) [reply base/float.jl:161]: The difference is they give the representation of a floating-point number as an unsigned integer. In mpfr.jl, in `to_ieee754`, the representation is what I need at that point, so it leads to simpler, and, I suppose, slightly faster code.

Apart from that, these additions to float.jl could actually be used (in a future PR) for refactoring float.jl so as to remove almost all "magic constants" from the file. So, taking `floatmax` for example: `floatmax` is currently defined with a magic constant for each method, when it would be prettier to define it via `ieee754_representation`.

File: base/float.jl (hunk 1 above)
Comment (nsajko) [reply base/float.jl:145]: You mean why is `exponent_min` necessary in addition to `ieee754_exponent_min`?

The idea was to have `exponent_min` be consistent with functions like `exponent_max`, in that it only has methods that are strictly required. To be honest, I don't really understand the significance of that, I was just trying to follow the discussion in #50654, the "incorrectly switches the position / ordering of `Union` and `Type`" part, in particular.

Apart from that the formula in the definition of `ieee754_exponent_min` is defined in the IEEE 754 standard, and it's only known to be valid for IEEE 754 floating-point. So theoretically we could have some non-IEEE floating-point types with different definitions of `exponent_min`.

**Comment by nsajko** [comment]
Note to myself: more tests would be good. An idea that comes to mind is to compare against `mpfr_get_flt` for all `Float32` values, varying through all rounding modes (both `RoundingMode` and `MPFR.MPFRRoundingMode`) and varying the `BigFloat` precision.

**Comment by nsajko** [comment]
Added more tests.

**Comment by nsajko** [comment]
Tweaked the new test in `test/rounding.jl`.

**Comment by nsajko** [comment]
Ping?

**Comment by nsajko** [comment]
Added another test set.

**Comment by oscardssmith** [comment]
I think this is good to go.

**Comment by nsajko** [comment]
ping

**Comment by DilumAluthge** [comment]
CI is green on this.

@oscardssmith Is this good to merge? I don't see any "approval" reviews on this.

**Review by oscardssmith — APPROVED** [review]
