### PR TITLE
Handle infix operators in REPL completion

### LINKED ISSUE #51194: Tab expansion of NamedTuple fails on 1.10.0-beta2
This worked on 1.9, does not on 1.10.0-beta2.

`A = (; foo=2, bar=3)`, and then type `A.foo + A.b<TAB>`.  `bar` does not get expanded.

### PR DESCRIPTION
**Pull request by Liozou**
Fix https://github.com/JuliaLang/julia/issues/51194

This PR fixes a regression introduced in https://github.com/JuliaLang/julia/pull/49294, so I believe it should be backported to v1.10.
In the current code, completion of `qux(foo, bar.` is detected by parsing `foo(qux, bar` as an incomplete expression, and then looking for the sub-expression to complete (here, `bar.`). This approach fails however for infix calls, since completing `foo + bar.` starts by parsing `foo + bar`, which is a complete call expression, and so the code behaves as if completing `(foo + bar).` instead of `bar.`. This leads to the current problematic behaviour:
```julia
julia> Complex(1, 3) + (4//5).#TAB
im
re
```
which would be correct for `(Complex(1, 3) + (4//5)).#TAB`, but here we expect
```julia
julia> Complex(1, 3) + (4//5).#TAB
den
num
```

This PR fixes that by trying to detect infix calls. In the long term, all this ad-hoc and probably somewhat wrong string processing should be replaced by proper use of `JuliaSyntax` (as mentioned in https://github.com/JuliaLang/julia/pull/49294#issue-1659443492, https://github.com/JuliaLang/julia/issues/50817#issuecomment-1668773346 and probably other places), but for now at least this fixes the regression.

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -1014,6 +1014,17 @@ function complete_identifiers!(suggestions::Vector{Completion}, @nospecialize(ff
                 ex = Meta.parse(lookup_name, raise=false, depwarn=false)
             end
             isexpr(ex, :incomplete) && (ex = nothing)
+        elseif isexpr(ex, :call) && length(ex.args) > 1
+            isinfix = s[end] != ')'
+            # A complete call expression that does not finish with ')' is an infix call.
+            if !isinfix
+                # Handle infix call argument completion of the form bar + foo(qux).
+                frange, end_of_identifier = find_start_brace(@view s[1:end-1])
```
Comment (oscardssmith) [inline stdlib/REPL/src/REPLCompletions.jl:1022]: should this use `prevind` rather than `end-1`?

Comment (oscardssmith) [reply stdlib/REPL/src/REPLCompletions.jl:1022]: If so, please add a test where the last character is more than 1 byte.

Comment (Liozou) [reply stdlib/REPL/src/REPLCompletions.jl]: Absolutely, thanks for the review!
Done in https://github.com/JuliaLang/julia/pull/51366/commits/5c5b61d8401a22160b81b2ff3b8e40f995d531b9

Comment (oscardssmith) [reply stdlib/REPL/src/REPLCompletions.jl]: I only caught it because we just fixed the same problem literally 2 days ago https://github.com/JuliaLang/julia/pull/51541
