### PR TITLE
🐝 Fix escaping in `Base.show(::IO, ::DateFormat)`

### LINKED ISSUE #45032: ISODateTimeFormat parsing odd behaviour
The following errors (which is unexpected):
```julia
julia> using Dates

julia> DateTime("2022-01-29T15:34:49.000000", ISODateTimeFormat)
ERROR: ArgumentError: Invalid DateTime string
Stacktrace:
 [1] parse(#unused#::Type{DateTime}, s::String, df::DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"), Tuple{Dates.DatePart{'y'}, Dates.Delim{Char, 1}, Dates.DatePart{'m'}, Dates.Delim{Char, 1}, Dates.DatePart{'d'}, Dates.Delim{Char, 1}, Dates.DatePart{'H'}, Dates.Delim{Char, 1}, Dates.DatePart{'M'}, Dates.Delim{Char, 1}, Dates.DatePart{'S'}, Dates.Delim{Char, 1}, Dates.DatePart{'s'}}})
   @ Dates /Applications/Julia-1.7 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Dates/src/parse.jl:277
 [2] DateTime(dt::String, df::DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"), Tuple{Dates.DatePart{'y'}, Dates.Delim{Char, 1}, Dates.DatePart{'m'}, Dates.Delim{Char, 1}, Dates.DatePart{'d'}, Dates.Delim{Char, 1}, Dates.DatePart{'H'}, Dates.Delim{Char, 1}, Dates.DatePart{'M'}, Dates.Delim{Char, 1}, Dates.DatePart{'S'}, Dates.Delim{Char, 1}, Dates.DatePart{'s'}}})
   @ Dates /Applications/Julia-1.7 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Dates/src/io.jl:547
 [3] top-level scope
   @ REPL[8]:1
```

But if I print `ISODateTimeFormat` and copy-paste the definition, it suddenly works:

```julia
julia> ISODateTimeFormat
dateformat"yyyy-mm-ddTHH:MM:SS.s"

julia> DateTime("2022-01-29T15:34:49.000000", dateformat"yyyy-mm-ddTHH:MM:SS.s")
2022-01-29T15:34:49
```

Julia 1.7.0

### PR DESCRIPTION
**Pull request by fonsp**
See https://github.com/JuliaLang/julia/issues/45032#issuecomment-1102775136

Fix #45032

### CODE REVIEW

File: stdlib/Dates/test/io.jl [hunk 1]
```diff
@@ -60,7 +60,9 @@ end
 end
 
 @testset "DateFormat printing" begin
-    @test sprint(show, DateFormat("yyyzzxmmdd\\MHH:MM:SS\\P")) == "dateformat\"yyyzzxmmdd\\MHH:MM:SSP\""
+    @test sprint(show, DateFormat("yyyzzxmmdd\\MHH:MM:SS\\P")) == "dateformat\"yyyzzxmmdd\\MHH:MM:SS\\P\""
```
Comment (fonsp) [inline stdlib/Dates/test/io.jl:63]: The change to this test actually corresponds to a fix: running the old output does not produce the input `DateFormat`.

```julia
julia> DateFormat("yyyzzxmmdd\\MHH:MM:SS\\P") == dateformat"yyyzzxmmdd\MHH:MM:SSP"
false

# new output includes the backslash:

julia> DateFormat("yyyzzxmmdd\\MHH:MM:SS\\P") == dateformat"yyyzzxmmdd\MHH:MM:SS\P"
true
```

This mismatch is what caused #45032

**Comment by fonsp** [comment]
Looks like the windows test failures are unrelated.
