### PR TITLE
Fix `typeintersect` bug reported in #36443

### LINKED ISSUE #36443: Unreachable reached (1.5.0-beta1 & 1.4.0)
I have reached the unreachable using the following `bugscript.jl:`:
```
using InteractiveUtils

struct Joe{N}
    tup::NTuple{N}
    sym::Symbol
    Joe{N}(tup::NTuple{N}, sym::Symbol) where {N} = new(tup, sym)
end

Joe{N}(tup::NTuple{N}) where {N} = Joe{N}(tup, :a)

function bugfunc(::Type{T}) where {T}
    tup1 = (:a, :b)
    tup2 = (:a, :b)
    tup1, tup2 = zip(zip(tup1, tup2)...)
    T(tup1)
end

versioninfo()
bugfunc(Joe{2})
```
```
julia --startup-file=no -e 'include("bugscript.jl")'
```
```
Julia Version 1.5.0-beta1.0
Commit 6443f6c95a (2020-05-28 17:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Unreachable reached at 0x7f343cc9ddfb

signal (4): Illegal instruction
in expression starting at /home/markus/Työ/julia/unreachable_MERA/bugscript.jl:19
bugfunc at /home/markus/Työ/julia/unreachable_MERA/bugscript.jl:15
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1689 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:566
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:913
jl_load_rewrite at /buildworker/worker/package_linux64/build/src/toplevel.c:914
include at ./client.jl:457
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1689 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:566
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:790
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:883
eval at ./boot.jl:331
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
exec_options at ./client.jl:272
_start at ./client.jl:506
jfptr__start_35292.clone_1 at /home/markus/Downloads/julia-1.5.0-beta1/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1689 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:106
main at /buildworker/worker/package_linux64/build/ui/repl.c:227
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/markus/Downloads/julia-1.5.0-beta1/bin/julia (unknown line)
Allocations: 3466189 (Pool: 3464834; Big: 1355); GC: 4
Illegal instruction (core dumped)
```

As mentioned in the title, this happens on at least 1.4.0 and 1.5.0-beta1.

The above is pretty much the smallest example I could reduce this down to, but let me know if I can do something else to help track this down further.

### LINKED ISSUE #37257: Wrong `Vararg` expansion in type intersection
```julia
julia> T = Tuple{Val{N}, Any, Any, Vararg{Any,N}} where N
Tuple{Val{N},Any,Any,Vararg{Any,N}} where N

julia> typeintersect(T, Tuple{Val{1}, Vararg{Any}})
Tuple{Val{1},Any,Any,Any,Any,Any}

julia> typeintersect(T, Tuple{Val{1}, Any, Vararg{Any}})
Tuple{Val{1},Any,Any,Any,Any}

julia> typeintersect(T, Tuple{Val{1}, Any, Any, Vararg{Any}})
Tuple{Val{1},Any,Any,Any}
```
Clearly, the result should be `Tuple{Val{1},Any,Any,Any}` in all three cases.

Of course, this can have an impact on inference, e.g.
```julia
julia> foo(::Val{N}, unused, args::Vararg{Any,N}) where {N} = (Val(N), args)
foo (generic function with 1 method)

julia> code_warntype(foo, Tuple{Val{1}, Any, Vararg}) # good
Variables
  #self#::Core.Const(foo, false)
  #unused#::Core.Const(Val{1}(), false)
  unused::Any
  args::Tuple{Any}

Body::Tuple{Val{1},Tuple{Any}}
1 ─ %1 = Main.Val($(Expr(:static_parameter, 1)))::Core.Const(Val{1}(), false)
│   %2 = Core.tuple(%1, args)::Core.PartialStruct(Tuple{Val{1},Tuple{Any}}, Any[Core.Const(Val{1}(), false), Tuple{Any}])
└──      return %2

julia> code_warntype(foo, Tuple{Val{1}, Vararg}) # bad
Variables
  #self#::Core.Const(foo, false)
  #unused#::Core.Const(Val{1}(), false)
  unused::Any
  args::Tuple{Any,Any}

Body::Tuple{Val{_A} where _A,Tuple{Any,Any}}
1 ─ %1 = Main.Val($(Expr(:static_parameter, 1)))::Val{_A} where _A
│   %2 = Core.tuple(%1, args)::Tuple{Val{_A} where _A,Tuple{Any,Any}}
└──      return %2
```
Note that in the bad case, not only is inference of the first return value needlessly imprecise (because `N` wasn't fixed), but the type of the second return value is plain wrong.

I've stumbled upon this when looking at suboptimal inference of this constructor:
https://github.com/JuliaLang/julia/blob/4b42f1400a33d656ae9e61822b0a47b5cad7a777/base/bitarray.jl#L28
So this is not a purely theoretical issue.

### PR DESCRIPTION
**Pull request by N5N3**
1. On master, we use a `offset` field to recode the valid length difference between 2 `Vararg`s.
It is set outside `intersect_varargs`, so when we check the `Vararg`'s eltype, the intersection result would be influenced when we have e.g. `Vararg{Val{N},N}`.
The first commit move the `offset` setting into `intersect_varargs` to fix the problem.
2. On master, `set_var_to_const` will ignore the `offset` if the `typevar` has been settled, thus gives many false `Union{}`. 
The second commit fix it.
3. At present, when we intersect 2 `Vararg`s length, we always return the length on the right. Which cause many order dependent error. In fact we should always return the shorter `Vararg`'s length, as the extra elements has been consumed within `intersect_tuple`.
4. At present, when we intersect 2 unbounded `Vararg`s length, we always set them equal, which is not correct if `offset != 0`. The 4th commit fix it (Not all, as some Vararg has `Null` length, which causes #39088)

close #36443, close #37257. Test added.

### CODE REVIEW

**Comment by N5N3** [comment]
@Keno 9e1e4ed should be enough to fix https://github.com/JuliaLang/julia/issues/39088, which doesn't introduce the following regression:
> by I tried rebasing, but noted it currently has this particularly egregious error (both before and after rebasing):
`typeintersect(NTuple, Tuple{Any,Vararg}) === NTuple{T,Vararg{T}} where T` (gives `Tuple{Any}`)

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/issues/39098#issuecomment-1211116701_

But the fix itself is some how too complex.
It would be much simpler if we force all `Vararg` to have a length var. With that, ca3c90b should enough to make sure the intersect result is not wrong.
(Some re-`intersect_union_` might still be needed to fix #39088, but that would be much simpler.)

Is it OK to do such change?

File: src/subtype.c [hunk 1]
```diff
@@ -2170,7 +2170,7 @@ static jl_value_t *set_var_to_const(jl_varbinding_t *bb, jl_value_t *v JL_MAYBE_
         bb->lb = bb->ub = v;
     }
     else if (jl_is_long(v) && jl_is_long(bb->lb)) {
-        if (jl_unbox_long(v) != jl_unbox_long(bb->lb))
+        if (jl_unbox_long(v) + offset != jl_unbox_long(bb->lb))
```
Comment (vtjnash) [inline src/subtype.c:2185]: Can you expand this commit message to say a little bit more about this offset (and include the relevant test changes, if possible)?

e.g. `subtype: add tuple length offset to Vararg length when matching up typevars in intersection`

File: src/subtype.c [hunk 2]
```diff
@@ -2165,13 +2165,21 @@ static jl_value_t *set_var_to_const(jl_varbinding_t *bb, jl_value_t *v JL_MAYBE_
...
     if (bb->lb == jl_bottom_type && bb->ub == (jl_value_t*)jl_any_type) {
-        if (jl_is_long(v))
-            v = jl_box_long(jl_unbox_long(v) + offset);
-        bb->lb = bb->ub = v;
+        if (jl_is_long(v)) {
+            size_t iv = jl_unbox_long(v);
+            v = jl_box_long(iv + offset);
+            bb->lb = bb->ub = v;
+            // Here we always return the shorter `Vararg`'s length.
+            if (offset > 0) return jl_box_long(iv);
```
Comment (vtjnash) [inline src/subtype.c:2179]:
```suggestion
            bb->lb = bb->ub = jl_box_long(iv + offset);
            // Here we always return the shorter `Vararg`'s length.
            if (offset > 0) return v;
```

File: src/subtype.c [hunk 3]
```diff
@@ -2165,13 +2165,21 @@ static jl_value_t *set_var_to_const(jl_varbinding_t *bb, jl_value_t *v JL_MAYBE_
         offset = -othervar->offset;
     assert(!othervar || othervar->offset == -offset);
     if (bb->lb == jl_bottom_type && bb->ub == (jl_value_t*)jl_any_type) {
-        if (jl_is_long(v))
-            v = jl_box_long(jl_unbox_long(v) + offset);
-        bb->lb = bb->ub = v;
+        if (jl_is_long(v)) {
```
Comment (vtjnash) [inline src/subtype.c]:
```
        if (jl_is_long(v) && offset) {
```

File: src/subtype.c [hunk 4]
```diff
@@ -74,7 +74,11 @@ typedef struct jl_varbinding_t {
     // 1 - var.ub = ub; return var
     // 2 - either (var.ub = ub; return var), or return ub
     int8_t constraintkind;
-    int8_t intvalued;      // must be integer-valued; i.e. occurs as N in Vararg{_,N}
+    // intvalued: must be integer-valued; i.e. occurs as N in Vararg{_,N}
```
Comment (vtjnash) [inline src/subtype.c:77]: can you fix the commit message to remove the `...\n` characters?

File: src/subtype.c [hunk 5]
```diff
@@ -2346,6 +2366,10 @@ static jl_value_t *intersect_var(jl_tvar_t *b, jl_value_t *a, jl_stenv_t *e, int
                 ub = (jl_value_t*)b;
             }
         }
+        if (has_free_vararg_length(ub, e) && !has_free_vararg_length(a, e)) {
+            bb->ub = ub;
+            ub = (jl_value_t*)b;
+        }
```
Comment (vtjnash) [inline src/subtype.c:2372]: should this be moved several lines further (just guarding the assignment to lb)? Right now, it seems that it may try to set `bb->ub = b` (which would be invalid) and then `return b` (which would be less accurate) and skips the `check_unsat_bound` on this Tuple

File: test/subtype.jl [hunk 6]
```diff
@@ -2080,3 +2085,53 @@ let A = Tuple{NTuple{N,Any},Val{N}} where {N},
...
+
+    Bs = (Tuple{Tuple{Int, Vararg{Any}}, Tuple{Int, Int, Vararg{Any}}},
+          Tuple{Tuple{Int, Vararg{Any,N1}}, Tuple{Int, Int, Vararg{Any,N2}}} where {N1,N2},
+          Tuple{Tuple{Int, Vararg{Any,N}} where {N}, Tuple{Int, Int, Vararg{Any,N}} where {N}})
+    Cerr = Tuple{Tuple{Int, Vararg{Int, N}}, Tuple{Int, Int, Vararg{Int, N}}} where {N}
+    for B in Bs
+        C = typeintersect(A, B)
+        @test C == typeintersect(B, A) != Union{}
+        @test C != Cerr
+        # TODO: The idea result is Tuple{Tuple{Int, Int, Vararg{Int, N}}, Tuple{Int, Int, Vararg{Int, N}}} where {N}
```
Comment (vtjnash) [inline test/subtype.jl:2112]: ideal (sp)

File: test/subtype.jl [hunk 7]
```diff
@@ -2080,3 +2085,53 @@ let A = Tuple{NTuple{N,Any},Val{N}} where {N},
...
+        @test_broken C != Tuple{Tuple{Int, Vararg{Int}}, Tuple{Int, Int, Vararg{Int}}}
+    end
+end
+
+struct __Vals{A,B} end
```
Comment (vtjnash) [inline test/subtype.jl:2117]: I think this can use `Pair`, to avoid needing a new type

File: src/subtype.c (hunk 3 above)
Comment (vtjnash) [reply src/subtype.c]: I see you fixed this in a later commit

**Comment by vtjnash** [comment]
Great work! I had a few minor nits that I commented about, but otherwise looks good. Let's see how it does:

@nanosoldier `runtests(ALL, vs=":master")`

File: test/subtype.jl (hunk 7 above)
Comment (N5N3) [reply test/subtype.jl:2117]: Oh didn't notice this.

File: src/subtype.c [hunk 8]
```diff
@@ -2877,7 +2877,7 @@ static jl_value_t *intersect_invariant(jl_value_t *x, jl_value_t *y, jl_stenv_t
     jl_value_t *ii = intersect(x, y, e, 2);
     e->invdepth--;
     e->Rinvdepth--;
-    if (jl_is_typevar(x) && jl_is_typevar(y) && (jl_is_typevar(ii) || !jl_is_type(ii)))
+    if ((jl_is_typevar(x) || jl_is_typevar(y)) && (jl_is_typevar(ii) || !jl_is_type(ii)))
```
[the remark this answers is not in the document]
Comment (N5N3) [reply src/subtype.c:2928]: IIRC, this was added as the subtype check below would ignore the `offset` with `var_gt`.
Some tests added in this PR need this change to pass. (I gave up to change `var_gt`.)

But yes, maybe we should not widen this branch that much. I'll try to tighten it and split this change into a seperate commit.

File: src/subtype.c (hunk 5 above)
Comment (N5N3) [reply src/subtype.c]: Not sure I get it. `has_free_vararg_length` wont return true if `ub` is a typevar, so we' never perform `bb->ub = b` here.
But yes, `check_unsat_bound` should not be skipped.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46446#issuecomment-1233100201) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/245f3c4_vs_8fa066b/report.html).

**Comment by vtjnash** [comment]
Good to see there are no failures. Should be good to merge once you make the clang-sagc-subtype test happy

File: src/subtype.c (hunk 2 above)
Comment (N5N3) [reply src/subtype.c]: looks like gc test dislike this change. Revert for now.
