### PR TITLE
Fix a precision issue in `abstract_iteration`

### LINKED ISSUE #41022: Possible inference improvement in iterated assignment where the RHS uses splatting
```julia
julia> function f(r)
       a, b, c = r..., nothing
       end
f (generic function with 1 method)

julia> @code_warntype f(1:2)
MethodInstance for f(::UnitRange{Int64})
  from f(r) in Main at REPL[1]:1
Arguments
  #self#::Core.Const(f)
  r::UnitRange{Int64}
Locals
  @_3::Int64
  c::Any
  b::Any
  a::Any
Body::Tuple
1 ─ %1 = Core.tuple(Main.nothing)::Core.Const((nothing,))
│   %2 = Core._apply_iterate(Base.iterate, Core.tuple, r, %1)::Tuple
│   %3 = Base.indexed_iterate(%2, 1)::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(2)])
│        (a = Core.getfield(%3, 1))
│        (@_3 = Core.getfield(%3, 2))
│   %6 = Base.indexed_iterate(%2, 2, @_3::Core.Const(2))::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(3)])
│        (b = Core.getfield(%6, 1))
│        (@_3 = Core.getfield(%6, 2))
│   %9 = Base.indexed_iterate(%2, 3, @_3::Core.Const(3))::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(4)])
│        (c = Core.getfield(%9, 1))
└──      return %2
```

The RHS is inferred as a `Tuple`, although it's really a `Tuple{Vararg{Union{Int, Nothing}}}`

In this case the variables may at least be inferred as `Union{Int, Nothing}`. Ideally `a` and `b` may be inferred as `Int`s as the function will error if there are less than three elements on the right hand side.

```julia
julia> f(1:1)
ERROR: BoundsError: attempt to access Tuple{Int64, Nothing} at index [3]
```

Edit: A simpler example:

```julia
julia> function f(r)
       a, b, c = r..., 1
       end
f (generic function with 1 method)

julia> @code_warntype f(1:2)
Variables
  #self#::Core.Const(f)
  r::UnitRange{Int64}
  @_3::Int64
  c::Any
  b::Any
  a::Any

Body::Tuple
1 ─ %1 = Core.tuple(1)::Core.Const((1,))
│   %2 = Core._apply_iterate(Base.iterate, Core.tuple, r, %1)::Tuple
│   %3 = Base.indexed_iterate(%2, 1)::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(2)])
│        (a = Core.getfield(%3, 1))
│        (@_3 = Core.getfield(%3, 2))
│   %6 = Base.indexed_iterate(%2, 2, @_3::Core.Const(2))::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(3)])
│        (b = Core.getfield(%6, 1))
│        (@_3 = Core.getfield(%6, 2))
│   %9 = Base.indexed_iterate(%2, 3, @_3::Core.Const(3))::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(4)])
│        (c = Core.getfield(%9, 1))
└──      return %2
```

In this case the variables must all be `Int`s

### PR DESCRIPTION
**Pull request by martinholters**
The first loop is left before `valtype` and `statetype` are updated from the current `stateordonet`, so the second loop should first process it before obtaining a new one instead of vice versa.

Fixes #41022.

### CODE REVIEW

**Comment by martinholters** [comment]
Ah, no, this isn't it. We need to compute a new `stateordonet` based on the const-widened `statetype` first. We just need to be careful in case the first loop never sets a `statetype` to not use `Union{}` as the argument type then.

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -862,8 +862,12 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
     # the precise (potentially const) state type
     statetype = widenconst(statetype)
     valtype = widenconst(valtype)
-    while valtype !== Any
+    if statetype === Bottom
```
Comment (Keno) [inline base/compiler/abstractinterpretation.jl:865]: Is the issue here when skipping the loop above? Maybe we should directly widen stateordonet then? Otherwise we're redoing this call here which duplicates work that was already done above.

Comment (martinholters) [reply base/compiler/abstractinterpretation.jl:865]: Widening `stateordonet` may not be sufficient, we need to compute it from the widened `statetype` as input to `iterate`. However, I also dislike the duplicaton of work here. (Which, btw, we also did before as the loop started with computing a new `stateordonet`.) However, I think I have found an alternative that avoids the duplication at the cost of replacing a `<:` with `⊑`. Will push momentarily; let me know what you think.

**Comment by martinholters** [comment]
Bump. @Keno, mind taking another look?

**Comment by martinholters** [comment]
Bump. Any objections against merging this?

File: base/compiler/abstractinterpretation.jl [hunk 2]
```diff
@@ -860,17 +860,15 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
     end
     # From here on, we start asking for results on the widened types, rather than
     # the precise (potentially const) state type
-    statetype = widenconst(statetype)
     valtype = widenconst(valtype)
     while valtype !== Any
-        stateordonet = abstract_call_known(interp, iteratef, nothing, Any[Const(iteratef), itertype, statetype], sv).rt
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:866]: This is the only line that should be moved, though I think we can rearrange some others a bit to sometimes skip work that is unnecessary.
```diff
diff --git a/base/compiler/abstractinterpretation.jl b/base/compiler/abstractinterpretation.jl
index 296a30cdb2..0da2ce68b3 100644
--- a/base/compiler/abstractinterpretation.jl
+++ b/base/compiler/abstractinterpretation.jl
@@ -860,25 +860,28 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
     end
     # From here on, we start asking for results on the widened types, rather than
     # the precise (potentially const) state type
-    statetype = widenconst(statetype)
     valtype = widenconst(valtype)
-    while valtype !== Any
-        stateordonet = abstract_call_known(interp, iteratef, nothing, Any[Const(iteratef), itertype, statetype], sv).rt
-        stateordonet = widenconst(stateordonet)
-        nounion = typesubtract(stateordonet, Nothing, 0)
-        if !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
-            valtype = Any
-            break
-        end
-        if nounion.parameters[1] <: valtype && nounion.parameters[2] <: statetype
-            if typeintersect(stateordonet, Nothing) === Union{}
-                # Reached a fixpoint, but Nothing is not possible => iterator is infinite or failing
-                return Any[Bottom], nothing
+    statetype = widenconst(statetype)
+    if valtype !== Any
+        while true
+            stateordonet = widenconst(stateordonet)
+            nounion = typesubtract(stateordonet, Nothing, 0)
+            if !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
+                valtype = Any
+                break
             end
-            break
+            if nounion.parameters[1] <: valtype && nounion.parameters[2] <: statetype
+                if typeintersect(stateordonet, Nothing) === Union{}
+                    # Reached a fixpoint, but Nothing is not possible => iterator is infinite or failing
+                    return Any[Bottom], nothing
+                end
+                break
+            end
+            valtype = tmerge(valtype, nounion.parameters[1])
+            valtype === Any && break
+            statetype = tmerge(statetype, nounion.parameters[2])
+            stateordonet = abstract_call_known(interp, iteratef, nothing, Any[Const(iteratef), itertype, statetype], sv).rt
         end
-        valtype = tmerge(valtype, nounion.parameters[1])
-        statetype = tmerge(statetype, nounion.parameters[2])
     end
     push!(ret, Vararg{valtype})
     return ret, nothing
```

**Comment by vtjnash** [comment]
Thanks for solving this. It looks like it is actually a bugfix so we should backport it, but that only the iterate function needs to be moved.

File: base/compiler/abstractinterpretation.jl (hunk 2 above)
Comment (martinholters) [reply base/compiler/abstractinterpretation.jl:866]: No, that leads to the following unsoundness:
```julia
julia> f() = (1:40...,)
f (generic function with 1 method)

julia> @code_typed f()
CodeInfo(
1 ─     Core._apply_iterate(Base.iterate, Core.tuple, $(QuoteNode(1:40)))::Union{}
└──     unreachable
) => Union{}
```
In this case, the first loop is terminates because `MAX_TUPLE_SPLAT` is exceeded. Then `statetype`, `valtype` and `stateordonet` all are `Const`s. Next we widen them to `Int`, `Int`, and `Tuple{Int,Int}`, respectively. So `nounion == Tuple{Int,Int}` also thus `nounion.parameters[1] <: valtype && nounion.parameters[2] <: statetype`. But at the same time, `typeintersect(stateordonet, Nothing) === Union{}`, so a `nothing`-free fixpoint is declared erroneously. That's why in my version, I don't `widenconst` the `statetype` and use `⊑`, so that in the first iteration `nounion.parameters[2] ⊑ statetype == Int ⊑ Const(n) == false`. In successive iterations, `statetype` will always be a proper type, so we could use `<:` then, but the overhead of `⊑` in the both-arguments-are-types case seems negligible here so I chose not to worry about it.

I think somewhere in the `abstractarray` tests we do a splat of a looong range which would have caught this, but I'll add a more direct test while at it.

**Comment by martinholters** [comment]
I don't think this is a bugfix in the sense that inference was unsound before. At least I could not come up with a case, although that may not be too strong an indicator... On the other hand, the fact that you proposed an alternative which did end up being unsound is a strong indicator that this is quite tricky to get right, so I'm not sure backporting is a good idea.

**Comment by martinholters** [comment]
> but that only the iterate function needs to be moved (the other changes just make it slower / less accurate)

If you mean that we should not do the removal of `statetype = widenconst(statetype)` and use of `⊑` instead of `<:`, then no, these changes are needed for soundness (see explanation in response to your inline comment above).

File: base/compiler/abstractinterpretation.jl [hunk 3]
```diff
@@ -860,17 +860,15 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
     end
     # From here on, we start asking for results on the widened types, rather than
     # the precise (potentially const) state type
-    statetype = widenconst(statetype)
     valtype = widenconst(valtype)
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:863]:
```suggestion
    valtype = Bottom
```

File: base/compiler/abstractinterpretation.jl (hunk 2 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:866]: Ah, that is true. I marked it as a bugfix, since it appeared to me that we might end up skipping including the first `valtype` (from `iterate(foo)`) into the final result, as we begin this loop with discarding that result and computing `iterate(foo, state)`

Comment (martinholters) [reply base/compiler/abstractinterpretation.jl:866]: > I marked it as a bugfix, since it appeared to me that we might end up skipping including the first valtype (from iterate(foo)) into the final result

...but we basically repeated that `iterate` (with widened, but not updated state), so this was indeed not a correctness issue ... right?

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (martinholters) [reply base/compiler/abstractinterpretation.jl:863]: True; I was basically `tmerge`ing this with itself after the first iteration, so could indeed just start with `Bottom` here to maybe save a bit. But more importantly, that will ensure we don't declare a fixpoint in the first iteration, so we could go back to widening the state here and using `<:` in the loops break condition. Let me play with that locally and see whether I missed anything in that reasoning.

**Comment by martinholters** [comment]
Prodding at this, I've found another case where we could consider improving precision:
```julia
julia> struct NoneOrFailOnSecond{T}
           itr::T
       end

julia> Base.iterate(itr::NoneOrFailOnSecond) = iterate(itr.itr)

julia> f_splat(x) = (x...,)
f_splat (generic function with 1 method)

julia> f_splat(NoneOrFailOnSecond([]))
()

julia> f_splat(NoneOrFailOnSecond([1]))
ERROR: MethodError: no method matching iterate(::NoneOrFailOnSecond{Vector{Int64}}, ::Int64)
[...]

julia> @code_typed f_splat(NoneOrFailOnSecond([1]))
CodeInfo(
1 ─ %1 = Core._apply_iterate(Base.iterate, Core.tuple, x)::Tuple
└──      return %1
) => Tuple
```
(Same for master and this PR in its current form.) Conceivably, this could be inferred as `Tuple{}`. It should also be possible to construct a case where it would be possible to infer that either a fixed (non-zero) number of elements is produced or the iteration fails. We would need to check `nounion == Bottom` and then act accordingly. But I doubt it's worth it. Such iterators look rather pathological and defensively producing too wide a result seems better than getting something wrong and returning too narrow a result, even if only for bizarre edge cases.

So I'd say leave that as is (for now, at least). Opinions?

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl]: `valtype` is the type of the previous element, not the type of the current element. It was incorrect (though conservative) to include it

File: base/compiler/abstractinterpretation.jl (hunk 2 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:866]: yeah, mostly we do repeat the same, but it appears to get specifically confused by that particular case, but perhaps it doesn't get this wrong. Since we start with statetype===Bottom, it will conclude that the result is Bottom, and then luckily we will replace that with Any, but it is not great.

```
iterate(::Foo) = rand(Bool) ? nothing : (nothing, 1)
iterate(::Foo, i) = i < 16 ? (i, i + 1) : nothing
```

**Comment by vtjnash** [comment]
I think we can easily handle that, by choosing not to widen valtype, and avoiding adding Vararg{Bottom} to the array

Another case we can improve is to model the implicit typeassert call, by adding a `tmeet(nounion, Tuple{Any, Any})` call before the checks for whether we have an Tuple of 2 fields

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (martinholters) [reply base/compiler/abstractinterpretation.jl]: Ah, true.

File: test/compiler/inference.jl [hunk 4]
```diff
@@ -2872,9 +2872,24 @@ partial_return_2(x) = Val{partial_return_1(x)[2]}
...
+# Soundness and precision of abstract_iteration
+f41839() = (1:100...,)
+@test NTuple{100,Int} <: only(Base.return_types(f41839, ())) <: Tuple{Vararg{Int}}
 f_splat(x) = (x...,)
 @test Base.return_types(f_splat, (Pair{Int,Int},)) == Any[Tuple{Int, Int}]
+@test Base.return_types(f_splat, (UnitRange{Int},)) == Any[Tuple{Vararg{Int}}]
+struct Itr41839_1 end # empty or infinite
+Base.iterate(::Itr41839_1) = rand(Bool) ? (nothing, nothing) : nothing
+Base.iterate(::Itr41839_1, ::Nothing) = (nothing, nothing)
+@test Base.return_types(f_splat, (Itr41839_1,)) == Any[Tuple{}]
```
Comment (martinholters) [inline test/compiler/inference.jl:2884]: And we finally have a bugfix! This gives `Union{}` on master.

File: base/compiler/abstractinterpretation.jl [hunk 5]
```diff
@@ -860,27 +862,43 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
...
+    # (widened) stateordonet, which has not yet been fully analyzed in the loop above
+    statetype = Bottom
+    valtype = Bottom
+    may_have_terminated = Nothing <: stateordonet
     while valtype !== Any
-        stateordonet = abstract_call_known(interp, iteratef, nothing, Any[Const(iteratef), itertype, statetype], sv).rt
-        stateordonet = widenconst(stateordonet)
-        nounion = typesubtract(stateordonet, Nothing, 0)
-        if !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
+        nounion = typeintersect(typesubtract(stateordonet, Nothing, 0), Tuple{Any,Any})
```
Comment (martinholters) [inline base/compiler/abstractinterpretation.jl:871]:
```suggestion
        nounion = typeintersect(stateordonet, Tuple{Any,Any})
```
This should work just as well, right?

File: base/compiler/abstractinterpretation.jl [hunk 6]
```diff
@@ -860,27 +862,43 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
...
+            # handle iterator failing or giving an invalid answer below
+            nounion = Tuple{Union{}, Union{}}
+        elseif !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
+            # nounion is of a type we cannot handle
             valtype = Any
             break
         end
         if nounion.parameters[1] <: valtype && nounion.parameters[2] <: statetype
+            # reached a fixpoint or iterator failed/gave invalid answer
             if typeintersect(stateordonet, Nothing) === Union{}
```
Comment (martinholters) [inline base/compiler/abstractinterpretation.jl:882]:
```suggestion
            if !(Nothing <: stateordonet)
```
As `Nothing` is a leaf type, this should be equal but more efficient?

File: base/compiler/abstractinterpretation.jl [hunk 7]
```diff
@@ -860,27 +862,43 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
...
     while valtype !== Any
-        stateordonet = abstract_call_known(interp, iteratef, nothing, Any[Const(iteratef), itertype, statetype], sv).rt
-        stateordonet = widenconst(stateordonet)
-        nounion = typesubtract(stateordonet, Nothing, 0)
-        if !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
+        nounion = typeintersect(typesubtract(stateordonet, Nothing, 0), Tuple{Any,Any})
+        if nounion === Union{}
+            # handle iterator failing or giving an invalid answer below
+            nounion = Tuple{Union{}, Union{}}
+        elseif !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
```
Comment (martinholters) [inline base/compiler/abstractinterpretation.jl:875]:
```suggestion
        elseif !isa(nounion, DataType)
```
Should be sufficient with the `typeintersect` above, but in corner cases it might give funnily too wide types which then might make these extra checks necessary?

File: base/compiler/abstractinterpretation.jl (hunk 6 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:882]: It should be essential identical (since typeintersect can check that property too), so not worth worrying about the difference too much

File: base/compiler/abstractinterpretation.jl (hunk 5 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:871]: LGTM

File: test/compiler/inference.jl (hunk 4 above)
Comment (vtjnash) [reply test/compiler/inference.jl:2884]: yay! that is quite the iteration space

File: base/compiler/abstractinterpretation.jl [hunk 8]
```diff
@@ -860,27 +862,43 @@ function abstract_iteration(interp::AbstractInterpreter, @nospecialize(itft), @n
...
+    may_have_terminated = Nothing <: stateordonet
     while valtype !== Any
-        stateordonet = abstract_call_known(interp, iteratef, nothing, Any[Const(iteratef), itertype, statetype], sv).rt
-        stateordonet = widenconst(stateordonet)
-        nounion = typesubtract(stateordonet, Nothing, 0)
-        if !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
+        nounion = typeintersect(typesubtract(stateordonet, Nothing, 0), Tuple{Any,Any})
+        if nounion === Union{}
+            # handle iterator failing or giving an invalid answer below
+            nounion = Tuple{Union{}, Union{}}
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:874]: subtyping may have some difficulty with this type. it is generally best to normalize away from it, not towards it

Comment (martinholters) [reply base/compiler/abstractinterpretation.jl:874]: Good point. That was an attempt to avoid repeating the code for handling infinite iterators below. I'll structure this differently to avoid this "denormalization".

**Comment by martinholters** [comment]
@vtjnash anything left I should address or good to go?
