### PR TITLE
handle round(x; base=...)

### LINKED ISSUE #28160: `round(pi, base=10)` broken
```julia

julia> round(pi)
3.0

julia> round(pi, digits=0)
3.0

julia> round(pi, digits=0, base=10)
3.0

julia> round(pi, base=10)
ERROR: MethodError: no method matching round(::Irrational{:π}, ::RoundingMode{:Nearest})
Closest candidates are:
  round(::Irrational, ::RoundingMode) at irrationals.jl:137
  round(::Real, ::RoundingMode; digits, sigdigits, base) at floatfuncs.jl:127
  round(::Number, ::Any) at deprecated.jl:53
  ...
Stacktrace:
 [1] _round(::Irrational{:π}, ::RoundingMode{:Nearest}, ::Nothing, ::Nothing, ::Int64) at ./floatfuncs.jl:137
#...
```
The error is a straight lie:
```julia
julia> round(pi, RoundingMode{:Nearest}())
3.0
```
Explicitly thrown here:
https://github.com/JuliaLang/julia/blob/b6a60dd6601a6947e00a0a77decd283248ba8a7f/base/floatfuncs.jl#L136-L137

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #28160.

### CODE REVIEW

File: base/floatfuncs.jl [hunk 1]
```diff
@@ -123,19 +123,35 @@ round(::Type{T}, x::AbstractFloat, r::RoundingMode) where {T<:Integer} = trunc(T
...
     isfinite(x) || return x
-    _round(x,r,digits,sigdigits,base)
+    if digits === nothing
+        if sigdigits === nothing
+            if base === nothing
+                # avoid recursive calls
+                throw(MethodError(round, (x,r)))
+            else
+                round(x,r)
+                # or throw(ArgumentError("`round` cannot use `base` argument without `digits` or `sigdigits` arguments."))
```
Comment (simonbyrne) [inline base/floatfuncs.jl]: decision needed here.

Comment (martinholters) [reply base/floatfuncs.jl]: Although specifying `base` without `digits` or `sigdigits` does not make much sense, I don't see any reason for disallowing it. The desired result is pretty unambiguous, after all.

**Comment by JeffBezanson** [comment]
If it doesn't break anything let's just merge this now.
