### PR TITLE
fix #37671, bug in `isa` Union check

### LINKED ISSUE #37671: Segmentation fault during LLVM Instcombine
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/ProximalAlgorithms/1.6.0-DEV-e476b33821.log

### PR DESCRIPTION
**Pull request by JeffBezanson**
The problem was that the initial and final blocks of an `emit_isa` test might be different.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: src/cgutils.cpp [hunk 1]
```diff
@@ -1122,14 +1122,18 @@ static std::pair<Value*, bool> emit_isa(jl_codectx_t &ctx, const jl_cgval_t &x,
...
         emit_isa_union(ctx, x, ((jl_uniontype_t*)type)->a, bbs);
         emit_isa_union(ctx, x, ((jl_uniontype_t*)type)->b, bbs);
         return;
     }
-    bbs.emplace_back(ctx.builder.GetInsertBlock(), emit_isa(ctx, x, type, nullptr).first);
+    BasicBlock *enter = ctx.builder.GetInsertBlock();
+    Value *v = emit_isa(ctx, x, type, nullptr).first;
+    BasicBlock *exit = ctx.builder.GetInsertBlock();
+    std::pair<BasicBlock*,BasicBlock*> blocks(enter, exit);
+    bbs.emplace_back(blocks, v);
```
Comment (yuyichao) [inline src/cgutils.cpp:1136]: `bbs.emplace_back(std::make_pair(enter, exit), v);`

**Review by yuyichao — APPROVED** [review]
