### PR TITLE
abstractarray: fix `append!(::AbstractVector, ...)` interface

### LINKED ISSUE #49748: Changes to `append!` inconpatible with TypedTables.jl
It seems that this commit https://github.com/JuliaLang/julia/commit/a20a3d09ec47a4a39bbafd6241a66dc75c21d41a (cc @aviatesk) makes `append!` no longer work with TypedTables.jl
```julia
julia> VERSION
v"1.10.0-DEV.1247"

julia> using TypedTables

julia> tints = Table(a = [1], b = [2])
Table with 2 columns and 1 row:
     a  b
   ┌─────
 1 │ 1  2

julia> supertype(typeof(tints))
AbstractVector{@NamedTuple{a::Int64, b::Int64}} (alias for AbstractArray{@NamedTuple{a::Int64, b::Int64}, 1})

julia> append!(tints, [(a=3, b=4)])
ERROR: MethodError: no method matching __inbounds_setindex!(::Table{@NamedTuple{a::Int64, b::Int64}, 1, @NamedTuple{a::Vector{Int64}, b::Vector{Int64}}}, ::@NamedTuple{a::Int64, b::Int64}, ::Int64)

Closest candidates are:
  __inbounds_setindex!(::Array{T}, ::Any, ::Int64) where T
   @ Base array.jl:1019
  __inbounds_setindex!(::Array{T}, ::Any, ::Int64, ::Int64, ::Int64...) where T
   @ Base array.jl:1021

Stacktrace:
 [1] _append!(a::Table{@NamedTuple{a::Int64, b::Int64}, 1, @NamedTuple{a::Vector{Int64}, b::Vector{Int64}}}, ::Base.HasShape{1}, iter::Vector{@NamedTuple{a::Int64, b::Int64}})
   @ Base ./array.jl:1189
 [2] append!(a::Table{@NamedTuple{a::Int64, b::Int64}, 1, @NamedTuple{a::Vector{Int64}, b::Vector{Int64}}}, iter::Vector{@NamedTuple{a::Int64, b::Int64}})
   @ Base ./array.jl:1178
 [3] top-level scope
   @ REPL[24]:1
```
whereas on earlier versions that worked:
```julia
julia> append!(tints, [(a=3, b=4)])
Table with 2 columns and 2 rows:
     a  b
   ┌─────
 1 │ 1  2
 2 │ 3  4

julia> VERSION
v"1.9.0-rc3"
```

### PR DESCRIPTION
**Pull request by aviatesk**
JuliaLang/julia#47154 mistakenly added `@_safeindex` macro on the `_append!(a::AbstractVector, ::Union{HasLength,HasShape}, iter)` method, although `@_safeindex` is only valid for builtin vectors i.e. `Vector`.

This commit adds `isa` check so that `@_safeindex` is only applied to builtin vectors. The `isa` check should be removed at compile time, so it should not affect the runtime performance.

closes #49748

### CODE REVIEW

File: base/array.jl [hunk 1]
```diff
@@ -1180,18 +1182,21 @@ push!(a::AbstractVector, iter...) = append!(a, iter)
 
 append!(a::AbstractVector, iter...) = foldl(append!, iter, init=a)
 
-function _append!(a, ::Union{HasLength,HasShape}, iter)
+function _append!(a::AbstractVector, ::Union{HasLength,HasShape}, iter)
```
Comment (aviatesk) [inline base/array.jl:1185]: I wonder if we should move these generic definitions into `base/abstractarray.jl` and define simple definition of `append!` for `Vector`-inputs here (same for `prepend!`). Any thoughts?

Comment (Seelengrab) [reply base/array.jl:1185]: Special casing a concrete implementation should IMO always be preferrable over assuming more of a generic version. It's philosophically the same reason why `@inbounds` in a function accepting `AbstractArray` is bad - there's no guarantee that the concrete type isn't doing any funny business in indexing; the local information cannot be enough to ensure the use is safe.

Comment (aviatesk) [reply base/array.jl:1185]: A potential drawback on the design is that there will be multiple potential method matches in type-unstable code for those functions, that may lead to worse inlining and optimization.

Well, we may want to accept that since the type unstable code will be slow anyway.

Comment (Seelengrab) [reply base/array.jl:1185]: I think prioritizing correctness over potentially broken fallbacks is a better bet any day of the week.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("array" || "sparse", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/49754#issuecomment-1545011092) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/5f05832_vs_8d0282c/report.md).

**Comment by aviatesk** [comment]
Going to merge this. I will refactor the code as suggested [above](https://github.com/JuliaLang/julia/pull/49754#discussion_r1190714161) in a separate PR.

**Comment by Seelengrab** [comment]
Since I looked at this code again for a different reason and noticed this, how did the `@_safeindex` come up in the first place? This branch should be completely dead, since the specialized `append!` just above doesn't use `_append!`, right?

https://github.com/JuliaLang/julia/pull/49754/files#diff-b3ce72015a28ab518a31d9914189e2a17e1d32eb988a0af985a621e023279382R1172-R1178

So just removing the branch entirely ought to be correct!

**Comment by aviatesk** [comment]
No, the specialized `append!(::Vector, items::AbstractVector)` is dispatched only when `items` isa `AbstractVector`.

**Comment by Seelengrab** [comment]
Ah, of course :facepalm:
