### PR TITLE
Use @loader_path instead of @executable_path when searching for shared libraries.

### LINKED ISSUE #15670: Master process linking wrong libraries, but workers don't
This one breaks `eigs` and `svds` because the homebrew version is built with 32 bit integers. The tricky part is that we don't detect this because the tests are run as workers where the linking is correct.
```jl
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5-pre+7 (2016-03-17 05:23 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a5d90d8* (12 days old release-0.4)
|__/                   |  x86_64-apple-darwin15.3.0

julia> addprocs(2)
@ev2-element Array{Int64,1}:
 2
 3

julia> @everywhere println(Libdl.dlpath(:libarpack))
/Users/andreasnoack/Library/homebrew/Cellar/arpack/3.2.0/libexec/lib/libarpack.2.dylib
	From worker 3:	/Users/andreasnoack/julia/usr/lib/libarpack.2.dylib
	From worker 2:	/Users/andreasnoack/julia/usr/lib/libarpack.2.dylib
```

UPDATE:

Same thing with `libgit2`
```jl
julia> @everywhere println(Libdl.dlpath(:libgit2))
/Users/andreasnoack/Library/homebrew/Cellar/libgit2/0.23.4/lib/libgit2.0.23.4.dylib
	From worker 2:	/Users/andreasnoack/julia-dev/usr/lib/libgit2.dylib
	From worker 3:	/Users/andreasnoack/julia-dev/usr/lib/libgit2.dylib
```
which is probably causing https://github.com/JuliaLang/julia/issues/15681

### PR DESCRIPTION
**Pull request by andreasnoack**
See https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html. As I read the link I think this change is right. It fixes #15670 for me.

### CODE REVIEW

File: base/libdl.jl [hunk 1]
```diff
@@ -7,8 +7,8 @@ export DL_LOAD_PATH, RTLD_DEEPBIND, RTLD_FIRST, RTLD_GLOBAL, RTLD_LAZY, RTLD_LOC
     dlpath, find_library, dlext, dllist
 
 const DL_LOAD_PATH = ByteString[]
-@osx_only push!(DL_LOAD_PATH, "@executable_path/../lib/julia")
-@osx_only push!(DL_LOAD_PATH, "@executable_path/../lib")
+@osx_only push!(DL_LOAD_PATH, "@loader_path/../lib/julia")
+@osx_only push!(DL_LOAD_PATH, "@loader_path/../lib")
```
Comment (vtjnash) [inline base/libdl.jl]: since `libjulia.dylib` is performing the `dlopen` call (and thus defines the base path), the `../lib` is redundant. just `"@loader_path"` and `"@loader_path/julia` should work even better.

Comment (andreasnoack) [inline base/libdl.jl]: Makes sense. I've changed that and it works as expected locally.

**Comment by vtjnash** [comment]
yep, lgtm now. merge when CI finishes

**Comment by tkelman** [comment]
This appears to have broken building the mac .app binaries. https://build.julialang.org/builders/package_osx10.9-x64/builds/133/steps/make%20.app/logs/stdio

ping @staticfloat if he has any ideas

**Comment by vtjnash** [comment]
since the buildbot failed to launch Python prior to building Julia src, I fail to see how a change to the Julia system image could be the cause. I suspect rather a buildbot configuration changed coincidentally and needs to have its cached cleared so that `deps/build/julia-env` can pick up the new system python

**Comment by tkelman** [comment]
Yeah I misread, you're probably right. Will see if cleaning it out helps.
