### PR TITLE
Fix union!(s::BitSet, r::AbstractUnitRange{<:Integer}) when two ranges do not overlap.

### LINKED ISSUE #45574: inconsistent results from repeated calls to `union!(s::BitSet, r::UnitRange{Int})`
As part of a larger task I need to count the number of elements in the union of a set of intervals. A sample set of intervals from genomic sequences and a function to evaluate the overlap size is in
[bugreport.txt](https://github.com/JuliaLang/julia/files/8835946/bugreport.txt)

I get inconsistent results
```jl
ulia> overlapsz(rngs)
8833

julia> overlapsz(rngs)
10413

julia> overlapsz(rngs)
8663

julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc656 (2022-05-27 18:33 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 8 on 8 virtual cores
```

I suspect that somewhere in the `union!(s::BitSet, r::AbstractUnitRange{<:Integer})` method starting at line 126 of bitset.jl the `bits` vector of `s` is being extended without zeroing the extending part.

### PR DESCRIPTION
**Pull request by metab0t**
Fix https://github.com/JuliaLang/julia/issues/45574

### CODE REVIEW

**Comment by dmbates** [comment]
Thanks to both @metab0t and @giordano for the fast response to #45574.

**Comment by giordano** [comment]
I did nothing! 😅

**Comment by dmbates** [comment]
> I did nothing! sweat_smile

You added the backport labels which will be important to me.  I hope the bug fix makes it into 1.8.0-rc2 as we are teaching a workshop in mid-July and it would be good if our code gave correct answers.

File: test/bitset.jl [hunk 1]
```diff
@@ -351,3 +351,12 @@ end
     # union! with an empty range doesn't modify the BitSet
     @test union!(x, b:a) == y
 end
+
+@testset "union!(::BitSet, ::AbstractUnitRange) when two ranges do not overlap" begin
```
Comment (KristofferC) [inline test/bitset.jl:355]: These tests seem to pass on e.g. 1.8-rc1 so it seems they do not cover the fixed behavior?

Comment (metab0t) [reply test/bitset.jl:355]: @KristofferC
I find that the failure of original code can only be triggered occasionally. (Maybe `Base._growbeg!/_growend!` allocates uninitialized memory that can be zero by accident)
I will change the code so that it can trigger failure consistently.

Comment (metab0t) [reply test/bitset.jl:355]: I test the new code in 1.8-rc1 (Win and Linux), and it triggers failure immediately.

**Comment by metab0t** [comment]
@KristofferC Is there any issues or blockers to merge this?

**Comment by KristofferC** [comment]
Sorry no, this just slipped through the cracks. Let's get it in!
