### PR TITLE
Relax eltype condition in `rdiv!` with `Diagonal`

### LINKED ISSUE #849: rdiv!(randn(4,4), I(4)) fails
```julia
julia> rdiv!(randn(4,4), I(4))
ERROR: MethodError: no method matching rdiv!(::Matrix{Float64}, ::Diagonal{Bool, Vector{Bool}})
```

There is an `rdiv!` method but it requires the arguments to have the same `eltype`, i.e.,
`rdiv!(randn(4,4), 1.0I(4))` works

~~I also noticed that there are two `ldiv!` methods for `Diagonal` and `Matrix`. `ldiv!(D::Diagonal, B::StridedVecOrMat)` and 
`ldiv!(D::Diagonal{T}, V::AbstractMatrix{T})`. This seems redundant?~~

### LINKED ISSUE #40887: rdiv!(randn(4,4), I(4)) fails
```julia
julia> rdiv!(randn(4,4), I(4))
ERROR: MethodError: no method matching rdiv!(::Matrix{Float64}, ::Diagonal{Bool, Vector{Bool}})
```

There is an `rdiv!` method but it requires the arguments to have the same `eltype`, i.e.,
`rdiv!(randn(4,4), 1.0I(4))` works

~~I also noticed that there are two `ldiv!` methods for `Diagonal` and `Matrix`. `ldiv!(D::Diagonal, B::StridedVecOrMat)` and 
`ldiv!(D::Diagonal{T}, V::AbstractMatrix{T})`. This seems redundant?~~

### PR DESCRIPTION
**Pull request by ArunS-tack**
Closes JuliaLang/LinearAlgebra.jl#849.  

**Before**
`julia> rdiv!(ones(2,2), 3I(2))
ERROR: MethodError: no method matching rdiv!(::Matrix{Float64}, ::Diagonal{Int64, Vector{Int64}})`

**After**
`julia> rdiv!(ones(2,2), 3I(2))
2×2 Matrix{Float64}:
 0.333333  0.333333
 0.333333  0.333333`

### CODE REVIEW

File: stdlib/LinearAlgebra/test/diagonal.jl [hunk 1]
```diff
@@ -141,6 +141,9 @@ Random.seed!(1)
                 @test rdiv!(Uc, D) ≈ target atol=atol_three
                 @test_throws DimensionMismatch rdiv!(Matrix{elty}(I, n-1, n-1), D)
                 @test_throws SingularException rdiv!(Uc, Diagonal(fill!(similar(D.diag), 0)))
+                @test rdiv!(Diagonal([2.0,3.0]), Diagonal(2:3)) == Diagonal([1.0,1.0])
+                @test rdiv!(Diagonal([2,3]), Diagonal(2.0:3.0)) == Diagonal([1.0,1.0])
+                @test rdiv!(Diagonal([2,3]), Diagonal(2:3)) == Diagonal([1,1])
```
Comment (mcabbott) [inline stdlib/LinearAlgebra/test/diagonal.jl:146]: Should the tests all be Diagonal Diagonal? 

Also, they are inside a loop `for (v, U) in ((vv, UU), (view(vv, 1:n), view(UU, 1:n, 1:2)))` but don't use that. Which is itself inside a loop `for relty in (Float32, Float64, BigFloat), elty in (relty, Complex{relty})`. I'm not too sure what all these loops are doing, but perhaps worth understanding right way to test the objects/types the loop is concerned with, or why not to be concerned.

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 2]
```diff
@@ -456,8 +456,7 @@ function ldiv!(D::Diagonal, A::Union{LowerTriangular,UpperTriangular})
     A
 end
 
-function rdiv!(A::AbstractMatrix{T}, D::Diagonal{T}) where {T}
-    require_one_based_indexing(A)
+function rdiv!(A::AbstractMatrix, D::Diagonal)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/diagonal.jl:459]: We need to require one-based indexing, because we are indexing into `A` with one-based ranges.
```suggestion
function rdiv!(A::AbstractMatrix, D::Diagonal)
    require_one_based_indexing(A)
```

File: stdlib/LinearAlgebra/test/diagonal.jl [hunk 3]
```diff
@@ -403,6 +403,13 @@ Random.seed!(1)
 
 end
 
+@testset "rdiv! (#40887)" begin
+    @test rdiv!(Diagonal([2.0,3.0]), Diagonal(2:3)) == Diagonal([1.0,1.0])
+    @test rdiv!(ones(3,3), 3I(3)) == 0.333333ones(3,3)
+    A=[[2 2];  [2 2];]
+    @test rdiv!(A, 2.0I(2)) == ones(2,2)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/diagonal.jl:410]: The last test is pretty much the same as the second test.
```suggestion
    @test rdiv!(Matrix(Diagonal([2.0, 3.0])), Diagonal(2:3)) == Diagonal([1.0, 1.0])
    @test rdiv!(fill(3.0, 3, 3), 3.0I(3)) == ones(3,3)
```

**Review by dkarrasch — APPROVED** [review]

**Comment by dkarrasch** [comment]
Maybe this is an opportunity to remove even more of the same-eltype conditions related to `Diagonal`s? The same pattern can be seen in a few `ldiv!` and `rdiv!` methods below and above the current changes. I think it's safe to remove them. The functions will complain anyway if the target eltype cannot store the result type of the division.

**Comment by ArunSanganal** [comment]
I deleted the main repository for this PR since you had reviewed and approved the changes (mainly because it was made from master and not a sub-branch). I can open another PR to implement what you suggested.

**Comment by dkarrasch** [comment]
> I deleted the main repository for this PR since you had reviewed and approved the changes (mainly because it was made from master and not a sub-branch). I can open another PR to implement what you suggested.

Sounds good.
