### PR TITLE
Don't let setglobal! implicitly create bindings

### LINKED ISSUE #54607: It is now possible to create globals in a different module
```julia
x@fedora:~$ julia +1.8 -q
julia> module M; end
Main.M

julia> M.x = 6
ERROR: cannot assign variables in other modules
Stacktrace:
 [1] setproperty!(x::Module, f::Symbol, v::Int64)
   @ Base ./Base.jl:32
 [2] top-level scope
   @ REPL[2]:1

julia> 
x@fedora:~$ julia +1.9 -q
julia> module M; end
Main.M

julia> M.x = 6
6
```

From the discussion at https://github.com/JuliaLang/julia/pull/44231, this seems unintentional.

### PR DESCRIPTION
**Pull request by Keno**
PR #44231 (part of Julia 1.9) introduced the ability to modify globals with `Mod.sym = val` syntax. However, the intention of this syntax was always to modify *existing* globals in other modules. Unfortunately, as implemented, it also implicitly creates new bindings in the other module, even if the binding was not previously declared. This was not intended, but it's a bit of a syntax corner case, so nobody caught it at the time.

After some extensive discussions and taking into account the near future direction we want to go with bindings (#54654 for both), the consensus was reached that we should try to undo the implicit creation of bindings (but not the ability to assign the *value* of globals in other modules). Note that this was always an error until Julia 1.9, so hopefully it hasn't crept into too many packages yet. We'll see what pkgeval says. If use is extensive, we may want to consider a softer removal strategy.

Across base and stdlib, there's two cases affected by this change:
1. A left over debug statement in `precompile` that wanted to assign a new variable in Base for debugging. Removed in this PR.
2. Distributed wanting to create new bindings. This is a legimitate use case for wanting to create bindings in other modules. This is fixed in https://github.com/JuliaLang/Distributed.jl/pull/102.

As noted in that PR, the recommended replacement where implicit binding creation is desired is:
```
Core.eval(mod, Expr(:global, sym))
invokelatest(setglobal!, mod, sym, val)
```

The `invokelatest` is not presently required, but may be needed by #54654, so it's included in the recommendation now.

Fixes #54607

### CODE REVIEW

File: test/syntax.jl [hunk 1]
```diff
@@ -3683,3 +3683,40 @@ end
...
+    # Syntactic, not dynamic
+    try_to_create_binding1() = (Foreign54607.foo = 2)
+    @eval try_to_create_binding2() = ($(GlobalRef(Foreign54607, :foo)) = 2)
+    function global_create_binding()
+        global bar
+        bar = 3
+    end
+    baz = 4
+    begin;
+        for i = 1:10; end
```
Comment (vtjnash) [inline test/syntax.jl:3698]:
```suggestion
        Base.Experimental.@force_compile
```

**Review by vtjnash — COMMENTED** [review]
LGTM

File: test/syntax.jl (hunk 1 above)
Comment (Keno) [reply test/syntax.jl:3698]: Ah, I thought we had this one, I just forgot what it was called.

**Comment by Keno** [comment]
@nanosoldier `runtests()`

**Review by JeffBezanson — APPROVED** [review]

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54678#issuecomment-2150666336) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/5c770d1_vs_06a90c5/report.html) is available.

**Comment by Keno** [comment]
I've submitted PRs to Toolips, RTableTools and ACSets which should cover all the PkgEval failures, except the one in AlgebraicRelations, which appears to be a lowering bug that I have yet to investigate.

**Comment by Keno** [comment]
> AlgebraicRelations, which appears to be a lowering bug that I have yet to investigate

#54701

**Comment by Keno** [comment]
From my perspective this is ready to go once https://github.com/JuliaLang/julia/issues/54701 is merged.
