### PR TITLE
Remove mention of Rational in convert

### LINKED ISSUE #40226: Improve docstring for convert
The current docstring for `convert` states:
> If `T` is a `AbstractFloat` or `Rational` type, then it will return the closest value to x representable by `T`.

This statement is not true, as conversion `AbstractFloat` float to to `Rational` requires the conversion back to be exact, as the following check is performed:
```
x == convert(typeof(x), r)
```
so you have that the following throws an error:
```
julia> convert(Rational{Int64}, nextfloat(big(1.0)))
ERROR: InexactError: Rational(1.000000000000000000000000000000000000000000000000000000000000000000000000000017)

julia> convert(Rational{Int32}, nextfloat(1.0))
ERROR: InexactError: Rational(1.0000000000000002)
```
so either:
1. the check should be removed

or

2. the docstring should be updated to reflect the behavior for `Rational` exactly. This issue is relevant as currently the user gets a false feeling that the conversion will be always successful, while a normal code like `Rational{Int32}[rand() for i in 1:1000]` errors almost all the time.

### PR DESCRIPTION
**Pull request by bkamins**
Fixes https://github.com/JuliaLang/julia/issues/40226.

I recommend to just remove the mention of `Rational` in the docstring. The reason is that explaining when conversion fails and when it works seems complex to me (as it depends on several factors). Therefore I think, given `Rational` is not so commonly used in conversion, that just avoiding mentioning it is OK.

### CODE REVIEW

File: base/essentials.jl [hunk 1]
```diff
@@ -181,7 +181,7 @@ Stacktrace:
 [...]
 ```
 
-If `T` is a [`AbstractFloat`](@ref) or [`Rational`](@ref) type,
+If `T` is a [`AbstractFloat`](@ref) type,
```
Comment (fredrikekre) [inline base/essentials.jl:184]: Remove the two examples also?

Comment (bkamins) [reply base/essentials.jl:184]: ah - right
