### PR TITLE
Fix `sum()` and `prod()` for tuples

### LINKED ISSUE #39182: sum for tuples uses +
sum for tuples uses `+` which has the following two consequences:

1. when a 1-element collection is passed `+` errors, while standard `sum` silently accepts the value:
```
julia> sum(["a"])
"a"
julia> sum(("a",))
ERROR: MethodError: no method matching +(::String)
```
2. no promotion happens (as standard `sum` uses `add_sum`):
```
julia> sum([0xe1, 0x1f])
0x0000000000000100
julia> sum((0xe1, 0x1f))
0x00
```

### LINKED ISSUE #39183: prod for tuples uses *
```julia
julia> prod([Int8(100), Int8(100)])
10000

julia> prod((Int8(100), Int8(100)))
16

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

Ref. https://github.com/JuliaLang/julia/issues/39182, which is the same issue but for `sum` and `+`

The is a todo in the code that says this function definition is inconsistent with regular `prod`:
https://github.com/JuliaLang/julia/blob/788b2c77c10c2160f4794a4d4b6b81a95a90940c/base/tuple.jl#L399-L400

### PR DESCRIPTION
**Pull request by petvana**
This PR aims to fix #39182 and #39183 by using the universal implementation of `prod` and `sum` from https://github.com/JuliaLang/julia/blob/97f817a379b0c3c5f9bb803427fe88a018ebfe18/base/reduce.jl#L588

However, the file `abstractarray.jl` is included way sooner, and it is crucial to have already a simplified version of `prod` function. ~~To distinguish the problematic locations (and not redefine the functions), I renamed these occurrences of the function to `_prod_simple` (not exported from Base).~~

The TODO was left in #22825 (@TotalVerb).

**EDIT:** The separate function `_prod_simple` is not necessary because we can specify a simplified version or `prod` only for a system-wide `Int` type that is sufficient to compile `Base`.
``` julia
prod(x::Tuple{}) = 1
# This is consistent with the regular prod because there is no need for size promotion
# if all elements in the tuple are of system size.
prod(x::Tuple{Int, Vararg{Int}}) = *(x...)
```

Although the implementations are different, they lead to the same binary code for tuples containing ~~`UInt` and~~ `Int`.

``` julia
julia> a = (1,2,3)
(1, 2, 3)

# Simplified version for tuples containing Int only
julia> prod_simplified(x::Tuple{Int, Vararg{Int}}) = *(x...)

julia> @code_native prod_simplified(a)
	.text
; ┌ @ REPL[1]:1 within `prod_simplified'
; │┌ @ operators.jl:560 within `*' @ int.jl:88
	movq	8(%rdi), %rax
	imulq	(%rdi), %rax
	imulq	16(%rdi), %rax
; │└
	retq
	nop
; └
```
``` julia
# Regular prod without the simplification
julia> @code_native prod(a)
        .text
; ┌ @ reduce.jl:588 within `prod`
; │┌ @ reduce.jl:588 within `#prod#247`
; ││┌ @ reduce.jl:289 within `mapreduce`
; │││┌ @ reduce.jl:289 within `#mapreduce#240`
; ││││┌ @ reduce.jl:162 within `mapfoldl`
; │││││┌ @ reduce.jl:162 within `#mapfoldl#236`
; ││││││┌ @ reduce.jl:44 within `mapfoldl_impl`
; │││││││┌ @ reduce.jl:48 within `foldl_impl`
; ││││││││┌ @ tuple.jl:276 within `_foldl_impl`
; │││││││││┌ @ operators.jl:613 within `afoldl`
; ││││││││││┌ @ reduce.jl:81 within `BottomRF`
; │││││││││││┌ @ reduce.jl:38 within `mul_prod`
; ││││││││││││┌ @ int.jl:88 within `*`
        movq    8(%rdi), %rax
        imulq   (%rdi), %rax
; │││││││││└└└└
; │││││││││┌ @ operators.jl:614 within `afoldl`
; ││││││││││┌ @ reduce.jl:81 within `BottomRF`
; │││││││││││┌ @ reduce.jl:38 within `mul_prod`
; ││││││││││││┌ @ int.jl:88 within `*`
        imulq   16(%rdi), %rax
; │└└└└└└└└└└└└
        retq
        nop
; └
```

### CODE REVIEW

File: base/tuple.jl [hunk 1]
```diff
@@ -488,17 +488,14 @@ reverse(t::Tuple) = revargs(t...)
...
-# require size promotion to system size.
-sum(x::Tuple{Any, Vararg{Any}}) = +(x...)
+prod(x::Tuple{}) = 1
 
 # NOTE: should remove, but often used on array sizes
 # TODO: this is inconsistent with the regular prod in cases where the arguments
 # require size promotion to system size.
-prod(x::Tuple{}) = 1
-prod(x::Tuple{Any, Vararg{Any}}) = *(x...)
+_prod_simple(x) = prod(x)
```
Comment (JeffBezanson) [inline base/tuple.jl:496]: Is this method really needed? It seems to me in any case this is used, the caller could just call `prod` instead?

**Comment by JeffBezanson** [comment]
Welcome, and thanks! Very nice first PR!

File: base/tuple.jl (hunk 1 above)
Comment (petvana) [reply base/tuple.jl:496]: These two functions are not equal, and the idea was to remove incorrect code from `prod` and clearly state that `_prod_simple` is not correct at edge cases for `Tuple`. 

First, I have tried it without this alias, but `_prod_simple` is sometimes called for an array as an argument in `abstractarray.jl`. Therefore `_prod_simple` just calls `prod` for any type except for `Tuple`. The new function seems necessary because `prod` is not yet included from `reduce.jl`, and bootstrap fails if removed.

**Comment by petvana** [comment]
The CI error in `tester_macos64` seems unrelated, or should I bother? I cannot re-run myself.
```bash
nested task error: Couldn't connect to server while requesting https://httpbingo.julialang.org/delay/2?id=75
```

File: base/tuple.jl (hunk 1 above)
Comment (petvana) [reply base/tuple.jl]: @JeffBezanson Thanks for the comment. I've found a way not to define a separate method and updated the PR accordingly. Now, it seems much cleaner, and both TODOs are fully resolved.

**Comment by petvana** [comment]
@NHDaly Would you mind checking this bugfix since you've already commented on both issues?

**Review by NHDaly — APPROVED** [review]
Yeah, LGTM! Thanks for the ping. 👍

**Comment by petvana** [comment]
@NHDaly Should I ping someone to consider merging?

**Review by NHDaly — APPROVED** [review]
Thanks @petvana LGTM, sorry for the delay. Agreed that CI looks good. :)

I'll go ahead and merge this now!

**Comment by NHDaly** [comment]
> backporting to v1.7 (not v1.6) as bugfix

Is there any particular reason why _not_ to backport to 1.6? Since this is a bugfix, and 1.6 is going to be the next LTS, i believe we are meant to backport all bugfixes to 1.6 as well.

I'll mark it `backport-1.6` for now until you comment! 😊 Thanks :)

**Comment by petvana** [comment]
First, usage of `prod` was changed in #41201, and thus I'm not sure if it is 1.6 compatible fix (can be checked by CI easily). Secondly, I don't like the idea of breaking anyone's code because it changes return types significantly, and tuple is a fundamental data type. On the other hand, I guess you run pkgeval on every release. So, I'm ok with backporting to v1.6.

**Comment by KristofferC** [comment]
Looking at PkgEval, I don't think this should go into 1.6. It changes things a bit too much and causes some test errors. Also, https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4651333_vs_7c45ff0/ApproxFunBase.1.6.3-pre-7c1cb9f5343.log seems to have been caused by this (inference regression).

**Comment by petvana** [comment]
> Looking at PkgEval, I don't think this should go into 1.6. It changes things a bit too much and causes some test errors.

That is exactly what my concerns were about. Also, the bugfix is not as critical.

**Comment by KristofferC** [comment]
While this is a bugfix, the effect it had on some packages also makes me a bit hesitant to backport this to 1.7 which is so late in the release cycle. I think it is better if this gets to live on master for a while before we commit it to a release.

**Comment by NHDaly** [comment]
Thanks both, makes sense to me 👍
