### PR TITLE
Fix #36531 - Error in abstract_iteration

### LINKED ISSUE #36531: Internal error in abstract_iteration
Happens on master and at least back to 1.4:
```
julia> f(args...) = Core._apply_iterate(Base.iterate, identity, args...)
f (generic function with 1 method)

julia> f(1,2,3)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="non-final parameter", expected=Type, got=Vararg{Int64, N} where N)
jl_type_error_rt at /home/keno/julia/src/rtutils.c:118
jl_f_apply_type at /home/keno/julia/src/builtins.c:959
jl_apply at /home/keno/julia/src/julia.h:1711 [inlined]
do_apply at /home/keno/julia/src/builtins.c:655
argtypes_to_type at ./compiler/typeutils.jl:46 [inlined]
abstract_call_known at ./compiler/abstractinterpretation.jl:908
abstract_call_known at ./compiler/abstractinterpretation.jl:698
abstract_iteration at ./compiler/abstractinterpretation.jl:589
precise_container_type at ./compiler/abstractinterpretation.jl:536
```

### PR DESCRIPTION
**Pull request by Keno**
The issue here is passing a `Vargarg` to `precise_container_type`, which
doesn't really make sense. Instead, we need to have the caller unwrap
the vararg, request the precise container type of the inner type and
then re-wrap the answer in a vararg.

### CODE REVIEW

File: test/compiler/inference.jl [hunk 1]
```diff
@@ -2660,3 +2660,8 @@ function symcmp36230(vec)
     return false
 end
 @test Base.return_types(symcmp36230, (Vector{Any},)) == Any[Bool]
+
+# Issue #36531, double varargs in abstract_iteration
+splat36531(args...) = args
+f36531(args...) = Core._apply_iterate(Base.iterate, splat36531, args...)
```
Comment (martinholters) [inline test/compiler/inference.jl:2666]:
```suggestion
f36531(args...) = Core._apply_iterate(Base.iterate, tuple, args...)
```
or
```suggestion
f36531(args...) = tuple((args...)...)
```

**Review by martinholters — APPROVED** [review]
Good catch! Fix LGTM.

File: test/compiler/inference.jl [hunk 2]
```diff
@@ -2660,3 +2660,8 @@ function symcmp36230(vec)
...
+@test @inferred(f36531(1,2,3)) == (1,2,3)
```
Comment (martinholters) [inline test/compiler/inference.jl:2667]: This tests seems to pass after printer the error message, which might go unnoticed if it regresses.
Maybe something like
```suggestion
@test code_typed(f36531, Tuple{Vararg{Int}}) isa Vector
```

Comment (Keno) [reply test/compiler/inference.jl:2667]: I'll do both, run it with `@inferred` and the code typed to test correctness as well as absence of error.
