### PR TITLE
Make DomainError more informative

### LINKED ISSUE #12152: Should DomainErrors accept arguments?
Re: #12121's discussion for @tkelman. 

Right now, `DomainError` doesn't take any arguments and will throw a `MethodError` if you try to pass an informative string. This is important because it's used in many performance critical math functions like `sqrt`, cf. @andreasnoack. @simonster chimed in to point out that

> We could have DomainError{T<:Union(None,ByteString)} where DomainError() would be a DomainError{None}. I don't think that would be any more expensive when there's no string to be thrown. Would need some changes on the codegen side, though...

and @yuyichao mentioned the performance regression discussed at https://github.com/JuliaLang/julia/pull/11508. @simonster pointed out that

> I'm not sure removing the GC frame would be enough. It would eliminate the additional cost for a DomainError with a string parameter in code that doesn't throw a DomainError, but you'd still have additional overhead if you actually throw a DomainError, which might matter.

What do we want to do going forward? Should we fix codegen, use https://github.com/JuliaLang/julia/pull/11508, or something else?

### PR DESCRIPTION
**Pull request by timholy**
Fixes #12152.

### CODE REVIEW

**Comment by timholy** [comment]
The travis errors look weird. A consequence of the switch to trusty?

Perhaps this will fail too, but worth a try: @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by fredrikekre** [comment]
> A consequence of the switch to trusty?

Perhaps, same error in #22750

**Comment by tkelman** [comment]
Complete coincidence, was happening before changing .travis.yml too. The unicode consortium might be rate-limiting Travis' IP's like they were doing for appveyor at one point. It looks like we maybe missed this download from our caching server whitelist, which should be added in https://github.com/staticfloat/cache.julialang.org/pull/16. I'm not clear on the details of how that gets deployed though, at least since the caching server was redone and moved a couple months back.

File: base/intfuncs.jl [hunk 1]
```diff
@@ -159,6 +160,10 @@ invmod(n::Integer, m::Integer) = invmod(promote(n,m)...)
 # ^ for any x supporting *
 to_power_type(x::Number) = oftype(x*x, x)
 to_power_type(x) = x
+@noinline throw_depbs(p) = throw(DomainError(p,
```
Comment (tkelman) [inline base/intfuncs.jl]: this only occurs twice, may as well spell out the name a little more

File: base/linalg/eigen.jl [hunk 2]
```diff
@@ -436,6 +438,14 @@ julia> eigvecs(A, B)
 """
 eigvecs(A::AbstractMatrix, B::AbstractMatrix) = eigvecs(eigfact(A, B))
 
+function throw_de_complex(A)
+    if length(A) < 10
```
Comment (tkelman) [inline base/linalg/eigen.jl]: bit arbitrary, maybe the showerror should be looking at the iocontext limits?

File: base/math.jl [hunk 3]
```diff
@@ -27,6 +27,16 @@ using Core.Intrinsics: sqrt_llvm
 
 const IEEEFloat = Union{Float16, Float32, Float64}
 
+@noinline function throw_complex_domainerror(x, f)
```
Comment (tkelman) [inline base/math.jl]: maybe `x` and `f` should be the other way around to match `nan_dom_err` ?

File: base/special/trig.jl [hunk 4]
```diff
@@ -169,7 +169,7 @@ Compute ``\\cos(\\pi x)`` more accurately than `cos(pi*x)`, especially for large
 function cospi(x::T) where T<:AbstractFloat
     if !isfinite(x)
         isnan(x) && return x
-        throw(DomainError())
+        throw(DomainError(x, "`x` must be finite."))
```
Comment (tkelman) [inline base/special/trig.jl]: this and `sinpi(x::T) where T<:AbstractFloat` should probably be consistent

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22751#issuecomment-314400807) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/86b27556e8d6cd2c4cff02f693726a9655ccb526/470aba9_vs_782460f/report.md). cc @jrevels

**Comment by timholy** [comment]
We should cancel all remaining builds until https://github.com/JuliaLang/julia/pull/22133#issuecomment-314475721 is resolved, otherwise we're just clogging the queue.

File: base/boot.jl [hunk 5]
```diff
@@ -216,6 +215,12 @@ struct UndefVarError      <: Exception
     var::Symbol
 end
 struct InterruptException <: Exception end
+struct DomainError <: Exception
+    val
+    msg
+    DomainError(val::ANY) = (@_noinline_meta; new(val))
```
Comment (tkelman) [inline base/boot.jl]: keep an eye on whether `@nospecialize` gets merged before this

**Comment by timholy** [comment]
The AppVeyor failures in the old buildlogs looked fine---the failure seemed pretty clearly unrelated. OK to merge now?

File: base/replutil.jl [hunk 6]
```diff
@@ -232,31 +232,16 @@ end
...
-                    (code.file === Symbol("math.jl") || code.file === Symbol(joinpath(".", "math.jl")))
-                print(io, "\nExponentiation yielding a complex result requires a complex ",
-                    "argument.\nReplace x^y with (x+0im)^y, Complex(x)^y, or similar.")
-            end
-            @goto showbacktrace
-        end
+    if isa(ex.val, AbstractArray)
+        compact = get(io, :compact, true)
+        limit = get(io, :limit, true)
+        print(IOContext(io, compact=compact, limit=limit), "DomainError with ", ex.val)
```
Comment (tkelman) [inline base/replutil.jl]: the compact code path doesn't look like it's tested anywhere

File: base/intfuncs.jl [hunk 7]
```diff
@@ -147,7 +147,8 @@ julia> invmod(5,6)
 """
 function invmod(n::T, m::T) where T<:Integer
     g, x, y = gcdx(n, m)
-    (g != 1 || m == 0) && throw(DomainError())
+    g != 1 && throw(DomainError((n, m), "Greatest common divisor is 1."))
```
Comment (Sacha0) [inline base/intfuncs.jl]: I am confused: Is `g` not the gcd?

File: base/math.jl [hunk 8]
```diff
@@ -27,6 +27,16 @@ using Core.Intrinsics: sqrt_llvm
...
 const IEEEFloat = Union{Float16, Float32, Float64}
 
+@noinline function throw_complex_domainerror(f, x)
+    throw(DomainError(x, string("$f will only return a complex result if called with a ",
+                                "complex argument. Try $f(complex(x)).")))
+end
+@noinline function throw_exp_domainerror(x)
+    throw(DomainError(x, string("Exponentiation yielding a complex result requires a ",
+                                "complex argument.\nReplace x^y with (x+0im)^y, ",
+                                "Complex(x)^y, or similar.")))
```
Comment (Sacha0) [inline base/math.jl]: The first method recommends calling `complex`, whereas the second recommends calling `Complex`; should these methods consistently recommend one or the other?

File: base/special/trig.jl [hunk 9]
```diff
@@ -106,7 +106,7 @@ Compute ``\\sin(\\pi x)`` more accurately than `sin(pi*x)`, especially for large
 function sinpi(x::T) where T<:AbstractFloat
     if !isfinite(x)
         isnan(x) && return x
-        throw(DomainError())
+        throw(DomainError(x, "`x` cannot be infinite."))
```
Comment (Sacha0) [inline base/special/trig.jl]: Slight inconsistency between errors in this file? ("`x` cannot be infinite" versus "`x` must be finite"?)

**Review by Sacha0 — APPROVED** [review]
Fantastic! :)

File: base/special/trig.jl (hunk 9 above)
Comment (tkelman) [inline base/special/trig.jl]: I believe that's intentional, as some of the methods check for `isnan` and return the input, others don't
