### PR TITLE
Fix "Issue 9160" tests in cholmod.jl by removing empty loop

### LINKED ISSUE #19583: empty loop in cholmod test
In `test/sparse/cholmod.jl`:

```
let # Issue 9160

    for Ti in CHOLMOD.ITypes.types
        for elty in CHOLMOD.VRealTypes.types
 ```

`VRealTypes.types` is intended to be the list of types in a union. By bad luck, both union types and DataTypes have a `.types` field, and `VRealTypes` is actually just the `Float64` type. Therefore `VRealTypes.types` is empty, and the loop doesn't execute. Fixing that reveals some failures that go beyond my knowledge of the cholmod code.

Noticed on my branch, where union types don't have a `.types` field any more (which, happily, will prevent this issue in the future).

### PR DESCRIPTION
**Pull request by andreasnoack**
Update tests to changes in `CHOLMOD` module, i.e. only support `SuiteSparse_long`.

Fixes #19583

Sort sparse matrices before constructing `SparseMatrixCSC` from `CHOLMOD.Sparse`.
This issue was revealed by the fix of the "Issue 9160" tests.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I think there is a bug here but I haven't been able to trigger it yet. Trying to come up with a test that will. Meanwhile, please don't merge.

**Comment by andreasnoack** [comment]
Ok. Should be ready now.

File: test/sparse/cholmod.jl [hunk 1]
```diff
@@ -687,3 +683,15 @@ let Apre = sprandn(10, 10, 0.2) - I
     end
 end
 
+# Check that Symmtric{SparseMatrixCSC} can be constructed from CHOLMOD.Sparse
```
Comment (tkelman) [inline test/sparse/cholmod.jl]: Symmetric

File: base/sparse/cholmod.jl [hunk 2]
```diff
@@ -1571,21 +1611,28 @@ function isposdef{Tv<:VTypes}(A::SparseMatrixCSC{Tv,SuiteSparse_long})
...
 
-function issymmetric(A::Sparse)
-    s = unsafe_load(A.p)
-    if s.stype != 0
-        return isreal(A)
-    end
-    i = symmetry(A, 1)[1]
-    return i == MM_SYMMETRIC || i == MM_SYMMETRIC_POSDIAG
-end
+# function issymmetric(A::Sparse)
```
Comment (tkelman) [inline base/sparse/cholmod.jl]: why commented out instead of deleted?

File: base/sparse/cholmod.jl [hunk 3]
```diff
@@ -418,6 +418,13 @@ function copy_dense{Tv<:VTypes}(A::Dense{Tv})
     d
 end
 
+function sort!{Tv<:VTypes}(S::Sparse{Tv})
```
Comment (tkelman) [inline base/sparse/cholmod.jl]: use a more descriptive name for this? confusing to locally shadow generic functions but with different meanings

Comment (andreasnoack) [inline base/sparse/cholmod.jl]: To elaborate. I think this works and isn't confusing since inside `CHOLMOD` the names match the behavior of CHOLMOD. If it is important/necessary to change this it should be a separate issue but I don't think it is.

Comment (tkelman) [inline base/sparse/cholmod.jl]: I have repeatedly had a really hard time debugging code in this file because of the name shadowing. I don't think it's a good convention. At least prefix `cholmod_` or something.

Comment (tkelman) [inline base/sparse/cholmod.jl]: this doesn't do the same thing as julia `sort!` it shouldn't be called that in julia code. you're strictly confusing people by matching the C names of a library with a horribly messy APi
