### PR TITLE
Documentation changes for isreal for 'Inf' and 'Nan'

### LINKED ISSUE #24870: Documentation of `isreal` is incorrect for Inf and NaN
```
help?> isreal

  isreal(x) -> Bool

  Test whether x or all its elements are numerically equal to some real
  number.
```
But
```
julia> isreal(Inf)
true

julia> isreal(NaN)
true
```
Neither `Inf` nor `NaN` is "numerically equal to a real number".

### PR DESCRIPTION
**Pull request by Subhash-Saurabh**
Made changes in documentation for isreal for 'Inf' and 'Nan'
Fix #24870

### CODE REVIEW

File: base/complex.jl [hunk 1]
```diff
@@ -114,6 +114,7 @@ real(::Type{Complex{T}}) where {T<:Real} = T
     isreal(x) -> Bool
 
 Test whether `x` or all its elements are numerically equal to some real number.
```
Comment (KristofferC) [inline base/complex.jl]: Perhaps this could be written shorter as:

```
Test whether `x` or all its elements are numerically equal to some real number, `Inf` or `NaN`.
```

**Review by KristofferC — APPROVED** [review]

File: base/complex.jl [hunk 2]
```diff
@@ -114,13 +114,16 @@ real(::Type{Complex{T}}) where {T<:Real} = T
     isreal(x) -> Bool
 
 Test whether `x` or all its elements are numerically equal to some real number,
-`Inf` or `NaN`.
+including infinities and NaNs.
```
Comment (StefanKarpinski) [inline base/complex.jl]: I think the more correct technical definition would be that `isreal(x)` is true if `isequal(x, real(x))` is true. In other words, the real component of `x` is numerically identical to `x` itself, comparing `NaN`s as equal. You could just add that after your explanation as a more technical clarification.

File: base/complex.jl [hunk 3]
```diff
@@ -114,7 +114,7 @@ real(::Type{Complex{T}}) where {T<:Real} = T
     isreal(x) -> Bool
 
 Test whether `x` or all its elements are numerically equal to some real number
-including infinities and NaNs.`isreal(x)` is true if `isequal(x, real(x))` 
+including infinities and NaNs.`isreal(x)` is true if `isequal(x, real(x))`
```
Comment (StefanKarpinski) [inline base/complex.jl]: You're missing a space after the first sentence.

**Review by fredrikekre — APPROVED** [review]

**Review by StefanKarpinski — APPROVED** [review]

**Comment by nalimilan** [comment]
I've taken the liberty to cancel to AppVeyor and CircleCI builds, Travis is enough for pure documentation edits.

**Comment by Subhash-Saurabh** [comment]
@nalimilan I had a look on my travis build log but couldn't understand why it is failing. Can you please take a look and suggest what changes are needed to be done.

**Comment by nalimilan** [comment]
Don't worry, that's unrelated and two builds passed.
