### PR TITLE
Update dtypes.h to fix C4146 in Visual C++

### LINKED ISSUE #14422: LLT_ALIGN makes Microsoft VC++ unhappy
this macro

```
#define LLT_ALIGN(x, sz) (((x) + (sz-1)) & (-sz))
```

in [support/dtypes.h](https://github.com/JuliaLang/julia/blob/79b241872d55d556189ce2fb4e91157164b2b1a6/src/support/dtypes.h#L160) causes Visual C++ to complain with [the following warning](https://msdn.microsoft.com/en-us/library/4kh09110.aspx)

```
julia.h(750) warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

The macro may likely be right but it unnerves the compiler and because it's in julia.h, it's all over the place littering the output with this warning -- which can be suppressed.  It would be nice to have it not do that by default is there's another way to construct the effect.

[pao: insert pinned SHA link to `dtypes.h`]

### PR DESCRIPTION
**Pull request by taoyouh**
Fixes #14422

### CODE REVIEW

**Review by Keno — APPROVED** [review]

File: src/support/dtypes.h [hunk 1]
```diff
@@ -227,7 +227,7 @@ STATIC_INLINE unsigned int next_power_of_two(unsigned int val) JL_NOTSAFEPOINT
     return val;
 }
 
-#define LLT_ALIGN(x, sz) (((x) + (sz)-1) & -(sz))
+#define LLT_ALIGN(x, sz) (((x) + (sz)-1) & ~(sz-1))
```
Comment (JeffBezanson) [inline src/support/dtypes.h]:
```suggestion
#define LLT_ALIGN(x, sz) (((x) + (sz)-1) & ~((sz)-1))
```
