### PR TITLE
fix #39804, ABI handling of structs with String references

### LINKED ISSUE #39804: Segfault in Catlab tests on v1.6.0-rc1 but pass on 1.7.0-DEV.599
When testing 1.6.0-rc1 with the Catlab library, we get a segfault in one test case and an undefined reference error in another (see https://github.com/AlgebraicJulia/Catlab.jl/issues/385). Both tests pass on Julia Version 1.7.0-DEV.599 (2021-02-23)

### PR DESCRIPTION
**Pull request by JeffBezanson**
It looks to me like the other ABIs don't need this, but somebody else should check to be sure.

Unfortunately does not help #28669.

fix #39804

### CODE REVIEW

File: src/abi_x86_64.cpp [hunk 1]
```diff
@@ -151,7 +151,7 @@ void classifyType(Classification& accum, jl_datatype_t *dt, uint64_t offset) con
         size_t i;
         for (i = 0; i < jl_datatype_nfields(dt); ++i) {
             jl_value_t *ty = jl_field_type(dt, i);
-            if (!jl_is_datatype(ty) || ((jl_datatype_t*)ty)->layout == NULL || jl_is_array_type(ty))
+            if (jl_field_isptr(dt, i))
```
Comment (vtjnash) [inline src/abi_x86_64.cpp:154]: I don't think `->layout` is necessarily defined. I'm unsure the best way to match `_julia_struct_to_llvm` here, as it seems many other abi files might similarly be trying to access it.

**Review by vtjnash — APPROVED** [review]

File: src/abi_x86_64.cpp (hunk 1 above)
Comment (JeffBezanson) [reply src/abi_x86_64.cpp:154]: I updated a couple other cases; see what you think.
