### PR TITLE
make sure `make_seed()` work on 32bits systems

### LINKED ISSUE #38206: possible error pass in `make_seed` on 32bits system
I would like to point out that the current implementation of `make_seed` might be "errorneous" on 32bits system because `hash(::UInt64, ::UInt64)` wouldn't be not defined.

> [`make_seed()`](https://github.com/JuliaLang/julia/blob/29a6e66e4944c6d79e1f672ae4648a76599b2f21/stdlib/Random/src/RNGs.jl#L317-L333)
```julia
function make_seed()
    try
        return rand(RandomDevice(), UInt32, 4)
    catch
        println(stderr,
                "Entropy pool not available to seed RNG; using ad-hoc entropy sources.")
        seed = reinterpret(UInt64, time())
        seed = hash(seed, UInt64(getpid())) # <= (possible) no method error.
        try
            seed = hash(seed, parse(UInt64,
                                    read(pipeline(`ifconfig`, `sha1sum`), String)[1:40],
                                    base = 16))
        catch
        end
        return make_seed(seed)
    end
end
```

... Well, I have not encountered this error (in other word, I'm even not sure if this control flow pass can actually occur on that system).
Why I found this possible problem was that I ran `rand(Bool)` on type level by using [JET.jl](https://github.com/aviatesk/JET.jl) (an experimental type checker for Julia) and I found it yielded the following errorneous trace only on 32 bits systems (if interested, please see [this CI trace](https://github.com/aviatesk/JET.jl/pull/60/checks?check_run_id=1319809936) and [this script](https://github.com/aviatesk/JET.jl/blob/751e9c72d3c85a9344c0d1e59dfe08e2b6f1807a/test/debug.jl)):

```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1352
Commit 8f71ea7f35 (2020-10-28 02:10 UTC)
Platform Info:
  OS: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_LOAD_PATH = @:/tmp/jl_Cud35Q

julia> using JET; @profile_call rand(Bool)
═════ 1 possible error found ═════
┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/Random.jl:259 Random.default_rng()
│┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:370 Random.default_rng(Base.getproperty(Random.Threads, :threadid)())
││┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:376 Random.MersenneTwister()
│││┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:147 #self#(Random.nothing)
││││┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:147 Random.seed!(Random.MersenneTwister(Core.apply_type(Random.Vector, Random.UInt32)(), Random.DSFMT_state()), seed)
│││││┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/Random.jl:426 Random.seed!(rng)
││││││┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:362 Random.make_seed()
│││││││┌ @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:324 Random.hash(seed, Random.UInt64(Random.getpid()))
││││││││ no matching method found for call signature: Random.hash(seed::UInt64, Random.UInt64(Random.getpid()::Int32)::UInt64)
│││││││└────────────────────────────────────────────────────────────────────────────────────────────────
```

So in other word, this errorneous control flow may never happen in actual execution and this error report might be just a false positive one. Then of course I will close this issue.

/cc @rfourquet could you tell me if this error report is wrong, or the control flow can happen in actual execution and it's better to be fixed ?

### PR DESCRIPTION
**Pull request by aviatesk**
fixes #38206 

/cc @rfourquet

### CODE REVIEW

**Review by rfourquet — APPROVED** [review]

File: stdlib/Random/src/RNGs.jl [hunk 1]
```diff
@@ -321,7 +321,7 @@ function make_seed()
         println(stderr,
                 "Entropy pool not available to seed RNG; using ad-hoc entropy sources.")
         seed = reinterpret(UInt64, time())
-        seed = hash(seed, UInt64(getpid()))
+        seed = hash(seed, UInt(getpid()))
```
Comment (rfourquet) [inline stdlib/Random/src/RNGs.jl:324]: Actually, while you are at it, there is another `hash` call below... the result of `parse` is `UInt64`, I suggest to just take it modulo `UInt`, i.e. `hash(seed, parse(UInt64, ...) % UInt)`, to be on the safe side. This path is guarded by a `try-catch` block, so it's less crucial, but let's clean it up too!

Comment (aviatesk) [reply stdlib/Random/src/RNGs.jl]: ops, thanks for pointing this out !
I decided to use modulo in both places for (local) consistency.

**Comment by rfourquet** [comment]
Thanks!
