### PR TITLE
Revised Range Documentation

### LINKED ISSUE #33798: Possible documentation error: range function docstring at julia/base/range.jl
The second paragraph states

> If `length` and `stop` are provided and `step` is not, the step size will be computed
automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).

but in this setting I get the following
```
julia> typeof(range(1, length=10,stop=100))
StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}
```
A `StepRangeLen` instead of a `LinRange`.

### PR DESCRIPTION
**Pull request by kamalojasv181**
Closes #33798

### CODE REVIEW

File: base/range.jl [hunk 1]
```diff
@@ -53,11 +53,20 @@ Given a starting value, construct a range either by length or from `start` to `s
 optionally with a given step (defaults to 1, a [`UnitRange`](@ref)).
 One of `length` or `stop` is required.  If `length`, `stop`, and `step` are all specified, they must agree.
 
-If `length` and `stop` are provided and `step` is not, the step size will be computed
-automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).
```
Comment (timholy) [inline base/range.jl]: To me it would be clearer to keep the

> the step size will be computed automatically such that there are `length` linearly spaced elements in the range

part because it's important and applies to everything. Then say something like

```julia
"""
...in a range. The returned type depends on the inputs, a [`StepRangeLen`](@ref) for floating-point inputs and [`LinRange`](@ref) otherwise.
"""
``` 

because that's effectively a detail that most people won't need to worry about. (Since the docs for `StepRangeLen` mention error-free arithmetic, I think we're covered as far as "purpose" goes.)

**Comment by timholy** [comment]
Yes, deleting the info about return type seems like an OK solution to the problem too. Any other thoughts?

**Comment by kamalojasv181** [comment]
Oh I thought you meant doing that in the first place. Anyways I think it would be great to do so for now.

**Comment by timholy** [comment]
Well, there don't seem to be any objections to just deleting the info about the return type. If you can clean up this branch with the extraneous stuff then I think we could merge it.

**Comment by kamalojasv181** [comment]
Sorry for the trouble. Now we are back at where you want. It is ready to be merged.

File: base/range.jl [hunk 2]
```diff
@@ -54,10 +54,7 @@ optionally with a given step (defaults to 1, a [`UnitRange`](@ref)).
 One of `length` or `stop` is required.  If `length`, `stop`, and `step` are all specified, they must agree.
 
 If `length` and `stop` are provided and `step` is not, the step size will be computed
-automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).
-
-If `step` and `stop` are provided and `length` is not, the overall range length will be computed
```
Comment (timholy) [inline base/range.jl]: Hmm, maybe I didn't notice this before or maybe it changed, but now you've deleted explanation of what happens if you don't provide `length`. This does need to be explained...

Comment (kamalojasv181) [reply base/range.jl]: Yes, It was me who did not add it earlier as well. Edited it now. Thanks

**Comment by timholy** [comment]
Thanks @kamalojasv181!
