### PR TITLE
inference: fix stupdate for Conditional after slot re-assignment

### LINKED ISSUE #25579: bug in `Conditional` inference design
```julia
julia> function f(g)
         h = g[]
         t = (h === nothing)
         h = nothing
         println(t ? typeof(h) : typeof(h))
       end
f (generic function with 1 method)

julia> f(Ref{Union{Int, Nothing}}( nothing ))
Nothing

julia> f(Ref{Union{Int, Nothing}}( 1 ))
Int64
```
um, yeah, variable reuse: I guess just don't do that.

### PR DESCRIPTION
**Pull request by vtjnash**
We were neglecting to clear Conditional objects upon assignment to their attached slot
(which invalidates their knowledge of the contents of that slot)

fixes #25579

### CODE REVIEW

File: base/compiler/typelattice.jl [hunk 1]
```diff
@@ -28,11 +28,11 @@ end
 # end
 # ```
 mutable struct Conditional
-    var::Union{Slot,SSAValue}
+    var::Slot
```
Comment (JeffBezanson) [inline base/compiler/typelattice.jl]: Why can't this apply to SSAValues?

Comment (vtjnash) [reply base/compiler/typelattice.jl]: Not worth the compile-time performance cost, since it'll never generate better results (on our current syntax).

File: base/compiler/typelattice.jl [hunk 2]
```diff
@@ -208,24 +208,42 @@ end
...
-        newst[slot_id(changes.var::Slot)] = changes.vtype
+        changeid = slot_id(changes.var::Slot)
+        newst[changeid] = changes.vtype
+        # remove any Conditional for this Slot from the vtable
+        for i = 1:length(newst)
+            newtype = newst[i]
+            if isa(newtype, VarState)
+                newtypetyp = newtype.typ
+                if isa(newtypetyp, Conditional) && slot_id(newtypetyp.var) == changeid
+                    newst[i] = VarState(Bool, newtype.undef)
```
Comment (Keno) [inline base/compiler/typelattice.jl]: Update to `Const(...)` if it's a conditional of the matching form?

**Review by Keno — APPROVED** [review]

File: test/compiler/compiler.jl [hunk 3]
```diff
@@ -1417,4 +1417,31 @@ for expr25261 in opt25261[i:end]
...
+    h = g[]
+    t = (h === nothing)
+    try
+        h = -1.25
+        error("continue at catch block")
+    end
+    return t ? typeof(h) : typeof(h)
+end
+@test Base.return_types(h25579, (Base.RefValue{Union{Nothing, Int}},)) ==
+        Any[Union{Type{Float64}, Type{Int64}, Type{Nothing}}]
```
Comment (JeffBezanson) [inline test/compiler/compiler.jl]: Needs to be adjusted for 32-bit platforms. If I had a dime for every time I've done that...
