### PR TITLE
Fix constructors of Symmetric and Hermitian

### LINKED ISSUE #423: Symmetric(A::Symmetric) should be a no-op?
I find it surprising that this is the case for `Symmetric` (and `Hermitian`):
```julia
julia> typeof(Symmetric(Symmetric(rand(2, 2))))
Symmetric{Float64,Symmetric{Float64,Array{Float64,2}}}
```
instead of just `Symmetric{Float64,Array{Float64,2}}`. Is this behaviour ever useful?

The simplest solution would be to define these:

```julia
Symmetric(A::Symmetric, uplo::Symbol=:U) = A
Hermitian(A::Hermitian, uplo::Symbol=:U) = A
```
and just ignore the `uplo`. A more general fix would be the following, but that will sometimes create a new `Symmetric`/`Hermitian` instance, depending on the input `uplo`:

```julia
function Symmetric(A::Symmetric{T,S}, uplo::Symbol=:U) where {T,S}
    if A.uplo == char_uplo(uplo)
        return A
    else
        transpose!(A.data, copy(A.data)) # to keep correct aliasing
        return Symmetric{T,S}(A.data, char_uplo(uplo))
    end
end
```

### LINKED ISSUE #21616: Symmetric(A::Symmetric) should be a no-op?
I find it surprising that this is the case for `Symmetric` (and `Hermitian`):
```julia
julia> typeof(Symmetric(Symmetric(rand(2, 2))))
Symmetric{Float64,Symmetric{Float64,Array{Float64,2}}}
```
instead of just `Symmetric{Float64,Array{Float64,2}}`. Is this behaviour ever useful?

The simplest solution would be to define these:

```julia
Symmetric(A::Symmetric, uplo::Symbol=:U) = A
Hermitian(A::Hermitian, uplo::Symbol=:U) = A
```
and just ignore the `uplo`. A more general fix would be the following, but that will sometimes create a new `Symmetric`/`Hermitian` instance, depending on the input `uplo`:

```julia
function Symmetric(A::Symmetric{T,S}, uplo::Symbol=:U) where {T,S}
    if A.uplo == char_uplo(uplo)
        return A
    else
        transpose!(A.data, copy(A.data)) # to keep correct aliasing
        return Symmetric{T,S}(A.data, char_uplo(uplo))
    end
end
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix JuliaLang/LinearAlgebra.jl#423

### CODE REVIEW

File: base/linalg/symmetric.jl [hunk 1]
```diff
@@ -41,6 +41,15 @@ julia> Slower = Symmetric(A, :L)
 Note that `Supper` will not be equal to `Slower` unless `A` is itself symmetric (e.g. if `A == A.'`).
 """
 Symmetric(A::AbstractMatrix, uplo::Symbol=:U) = (checksquare(A); Symmetric{eltype(A),typeof(A)}(A, char_uplo(uplo)))
+Symmetric(A::Symmetric) = A
+function Symmetric(A::Symmetric, uplo::Symbol)
+    if A.uplo == char_uplo(uplo)
+        return A
+    else
+        throw(ArgumentError("Cannot construct Symmetric; uplo doesn't match"))
```
Comment (fredrikekre) [inline base/linalg/symmetric.jl]: Suggestions for better messages here? :)

Comment (jebej) [inline base/linalg/symmetric.jl]: why not just ignore the uplo argument? Presumably, if you're building a symmetric matrxx from an already symmetric matrix, taking the lower or upper triangle should not matter since they are the same.

Comment (ararslan) [inline base/linalg/symmetric.jl]: @jebej See https://github.com/JuliaLang/julia/issues/21616#issuecomment-298059168

Comment (andreasnoack) [inline base/linalg/symmetric.jl]: I think it is unlikely that people will hit this exception on purpose, i.e. where they want to flip the storage. We can revisit if it is really an issue.

**Review by andreasnoack — APPROVED** [review]

**Review by Sacha0 — APPROVED** [review]
Thanks @fredrikekre! :)

File: base/linalg/symmetric.jl [hunk 2]
```diff
@@ -41,6 +41,15 @@ julia> Slower = Symmetric(A, :L)
 Note that `Supper` will not be equal to `Slower` unless `A` is itself symmetric (e.g. if `A == A.'`).
 """
 Symmetric(A::AbstractMatrix, uplo::Symbol=:U) = (checksquare(A); Symmetric{eltype(A),typeof(A)}(A, char_uplo(uplo)))
+Symmetric(A::Symmetric) = A
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: tiny bit inconsistent that here the default uplo matches that of the input, whereas on all other types it defaults to upper
