### PR TITLE
Fix late gc lowering pass for vector intrinsics

### LINKED ISSUE #55844: LateLowerGCFrame infinite loops in presence of `@llvm.vector.insert` in IR
On master this IR hangs in LateLowerGCFrame
```llvm
; ModuleID = 'reduced.bc'
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128-ni:10:11:12:13"
target triple = "x86_64-unknown-linux-gnu"

declare ptr @julia.get_pgcstack()

define swiftcc void @julia_abstract_modifyopNOT._36663(<4 x ptr addrspace(10)> %0, <2 x ptr addrspace(10)> %1) {
top:
  %pgcstack = call ptr @julia.get_pgcstack()
  %2 = call <4 x ptr addrspace(10)> @llvm.vector.insert.v4p10.v2p10(<4 x ptr addrspace(10)> %0, <2 x ptr addrspace(10)> %1, i64 2)
  ret void
}
```

The hang is in the `FindBaseValue` function as this code doesn't seem to handle this intrinsic https://github.com/JuliaLang/julia/blob/9136bddb6c36050e03529e2db456e6ea2e380557/src/llvm-late-gc-lowering.cpp#L174-L179

### PR DESCRIPTION
**Pull request by gbaraldi**

### CODE REVIEW

File: src/llvm-late-gc-lowering.cpp [hunk 1]
```diff
@@ -204,7 +205,17 @@ static std::pair<Value*,int> FindBaseValue(const State &S, Value *V, bool UseCac
                 }
                 // In general a load terminates a walk
                 break;
-            }
+            } else if (II->getIntrinsicID() == Intrinsic::vector_extract) {
+                if (auto VTy = dyn_cast<VectorType>(II->getType())) {
+                    if (hasLoadedTy(VTy->getElementType())) {
+                        // TODO: For now, only support constant index.
+                        auto IdxOp = cast<ConstantInt>(II->getOperand(1));
```
[the remark this answers is not in the document]
Comment (gbaraldi) [reply src/llvm-late-gc-lowering.cpp:212]: This is an assertion. This argument is a immarg argument in llvm

**Comment by Zentrik** [comment]
`JULIA_CPU_TARGET="sandybridge,-xsaveopt,clone_all;x86-64-v4,-rdrnd"` is a more minimal reproducer for the build failure. 

Looking at the coredump I get locally, I see its indexing out of bounds at https://github.com/JuliaLang/julia/blob/4843847315f9f6e6df1843b7eb14f6f17156f3db/src/llvm-late-gc-lowering.cpp#L567 but https://github.com/JuliaLang/julia/blob/4843847315f9f6e6df1843b7eb14f6f17156f3db/src/llvm-late-gc-lowering.cpp#L560 should make sure that can't happen so I don't understand what's going on. I added a if statement to check if `i >= BaseNumbers.size()` and it never got hit either.

```
#12 0x0000730004148a26 in llvm::SmallVectorTemplateCommon<int, void>::operator[] (idx=<optimised out>, this=<optimised out>) at /home/rag/Documents/Code/julia/usr/include/llvm/ADT/SmallVector.h:291
#13 LateLowerGCFrame::NumberAllBase (this=this@entry=0x72ffe3ffd500, S=..., CurrentV=<optimised out>, CurrentV@entry=0x72ffad005810) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:567
#14 0x000073000414cc17 in LateLowerGCFrame::NumberAll (this=this@entry=0x72ffe3ffd500, S=..., V=<optimised out>, V@entry=0x72ffad005810) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:630
#15 0x000073000414d381 in LateLowerGCFrame::NoteUse (this=this@entry=0x72ffe3ffd500, S=..., V=0x72ffad005810, Uses=..., F=..., BBS=...) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:739

#16 0x000073000414d524 in LateLowerGCFrame::NoteUse (BBS=..., F=..., Uses=..., V=<optimised out>, S=..., this=0x72ffe3ffd500) at /home/rag/Documents/Code/julia/usr/include/llvm/IR/Value.h:533
#17 LateLowerGCFrame::NoteUse (F=..., V=<optimised out>, BBS=..., S=..., this=0x72ffe3ffd500) at /home/rag/Documents/Code/julia/src/llvm-gc-interface-passes.h:336
#18 LateLowerGCFrame::NoteOperandUses (this=this@entry=0x72ffe3ffd500, S=..., BBS=..., UI=...) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:751
#19 0x000073000414f611 in LateLowerGCFrame::LocalScan (this=this@entry=0x72ffe3ffd500, F=...) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:1419
#20 0x000073000414fc2d in LateLowerGCFrame::runOnFunction (this=0x72ffe3ffd500, F=..., CFGModified=0x72ffe3ffd4ef) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:2490
#21 0x000073000415015e in LateLowerGCPass::run (this=<optimised out>, F=..., AM=...) at /home/rag/Documents/Code/julia/src/llvm-late-gc-lowering.cpp:2506
```

**Comment by giordano** [comment]
Note that this is necessary to upgrade to LLVM 20: #57352.

File: src/llvm-late-gc-lowering.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (vchuravy) [reply src/llvm-late-gc-lowering.cpp:212]: Then I don't understand the todo?

File: src/llvm-late-gc-lowering.cpp [hunk 2]
```diff
@@ -171,39 +173,54 @@ static std::pair<Value*,int> FindBaseValue(const State &S, Value *V, bool UseCac
             (void)LI;
             break;
         }
-        else if (auto II = dyn_cast<IntrinsicInst>(CurrentV)) {
+        else if (dyn_cast<IntrinsicInst>(CurrentV) != nullptr &&
+                (cast<IntrinsicInst>(CurrentV)->getIntrinsicID() == Intrinsic::masked_load ||
+                cast<IntrinsicInst>(CurrentV)->getIntrinsicID() == Intrinsic::masked_gather)) {
```
Comment (vchuravy) [inline src/llvm-late-gc-lowering.cpp:178]: This code pattern is annoying since you are doing three casts.  

Can we restore the previous code pattern?

File: src/llvm-late-gc-lowering.cpp [hunk 3]
```diff
@@ -171,39 +173,54 @@ static std::pair<Value*,int> FindBaseValue(const State &S, Value *V, bool UseCac
...
-                        continue;
                     }
+                    continue;
+                }
+            }
+            // In general a load terminates a walk
+            break;
+        }
+        else if (dyn_cast<IntrinsicInst>(CurrentV) != nullptr && cast<IntrinsicInst>(CurrentV)->getIntrinsicID() == Intrinsic::vector_extract) {
+            auto II = dyn_cast<IntrinsicInst>(CurrentV);
```
Comment (vchuravy) [inline src/llvm-late-gc-lowering.cpp:212]: Same here, I think LLVM style generally preferes doing one `dyn_cast` `if(auto II = dyn_cast)`

File: src/llvm-late-gc-lowering.cpp (hunk 2 above)
Comment (gbaraldi) [reply src/llvm-late-gc-lowering.cpp:178]: The old pattern was wrong, it was catching every intrinsic and infinite looping, we should only enter the branch if we are going to handle it. Maybe this is a use for a goto

File: src/llvm-late-gc-lowering.cpp [hunk 4]
```diff
@@ -205,6 +207,24 @@ static std::pair<Value*,int> FindBaseValue(const State &S, Value *V, bool UseCac
...
+                        if (!isa<ConstantInt>(Idx)) {
+                            assert(isa<UndefValue>(Idx) && "unimplemented");
+                            (void)Idx;
+                        }
+                        CurrentV = II->getOperand(0);
+                        fld_idx = -1;
+                        continue;
+                    }
+                }
+                break;
```
Comment (vchuravy) [inline src/llvm-late-gc-lowering.cpp:223]: This break was missing previously.

**Review by oscardssmith — APPROVED** [review]
