### PR TITLE
[JuliaLowering] Fix closure-conversion of keyword functions

### LINKED ISSUE #139: Closures with kwargs de-sugar incorrectly
```julia
julia> JuliaLowering.include_string(Main, raw"""
       function destructure()
           return (; kwarg) -> nothing
       end
       """; expr_compat_mode=true)
destructure (generic function with 2 methods)

julia> destructure()
Internal error: encountered unexpected error during compilation of destructure:
ErrorException("unsupported or misplaced expression \"latestworld\" in function destructure")
```

### PR DESCRIPTION
**Pull request by mlechu**
The `Core.kwcall` `method` expression from desugaring is expected to be as local or global (according to closure conversion) as the other methods produced.  We were (1) always considering it global, and so (2) not lifting the `method` form for it, which just meant invalid IR.  This PR makes a few tweaks:
1. Allow that method to be local
2. Lift `method` expressions to top-level regardless of whether they're local or global.  Debatable, but I think it's simpler to expect closure conversion always do the simple mechanical thing, and not have it depend on the scope resolution of the first argument of `K"method_defs"`.  This form doesn't exist in flisp, and I don't think we've written down or decided on the full purpose of the first argument yet.
3. Throw an internal error if `method` is found not at top level (commented out before).  The user-facing "global function should go at top level" is thrown from the validator.
4. A small hack to get the closure argument passed to `Core.kwcall` in the third position instead of the first (don't think there's a good way around this; flisp does `(contains (lambda (x) (eq? x 'kwftype)) sig)`)

Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/139. Pkg and LazyArtifacts should now precompile, meaning all stdlibs precompile under JuliaLowering now!

### CODE REVIEW

File: JuliaLowering/src/desugaring.jl [hunk 1]
```diff
@@ -2614,13 +2614,15 @@ function keyword_function_defs(ctx, srcref, callex_srcref, name_str, typevar_nam
     end
     # TODO: Is the layer correct here? Which module should be the parent module
     # of this body function?
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl]: Does this comment still apply?

File: JuliaLowering/src/desugaring.jl [hunk 2]
```diff
@@ -2860,7 +2862,9 @@ function keyword_function_defs(ctx, srcref, callex_srcref, name_str, typevar_nam
             ]
         ]
         [K"method_defs"
-            "nothing"::K"core"
+            # We want this method to be local or global at the same time as the
+            # body func, but it's really a method on Core.kwcall
+            body_func_name
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl]:
```suggestion
            # This should inherit the local / global status of the body func, 
            # so provide that here for closure conversion, even though this is
            # really a method on Core.kwcall
            body_func_name
```

I assume this is done for closure conversion, but the comment seems to leave that out. Also, is there any issue that this will look up the `ClosureInfo` for the body func when converting the wrapper?

That doesn't lead to https://github.com/JuliaLang/JuliaLowering.jl/issues/141, does it? (shot in the dark)

Comment (mlechu) [reply JuliaLowering/src/desugaring.jl]: Yes, for closure conversion.  The name lookup should do the right thing, as the closure should(?) be the same for both methods.

(discussed in meeting) I'm guessing https://github.com/JuliaLang/JuliaLowering.jl/issues/141 is something specific to constructors

**Review by topolarity — APPROVED** [review]
I can't say no to all stdlibs pre-compiling!

Thanks @mlechu 👍
