### PR TITLE
LinearAlgebra: Don't assume AbstractVector supports deleteat!

### LINKED ISSUE #46654: `kron` of `Diagonal` and `Bidiagonal` calls missing method
This fails:
```Julia
julia> using LinearAlgebra
julia> using SparseArrays
julia> kron(Diagonal(sparsevec([1])), Bidiagonal([2], Int[], :U))
ERROR: MethodError: no method matching deleteat!(::SparseVector{Int64, Int64}, ::Int64)
```

The problem is that this `kron` method calls `deleteat!`, which does not exist for sparse vectors.

Since sparse vectors are immutable, `deleteat!` cannot be implemented. (A `deleteat` could be implemented, though.)

I think the solution is to call `deleteat!` only when the respective vector type holding the diagonal elements is mutable, or (to be safe) when it is `Vector`.

This error was introduced by https://github.com/JuliaLang/julia/pull/46463.

### PR DESCRIPTION
**Pull request by eschnett**
Closes https://github.com/JuliaLang/julia/issues/46654.

### CODE REVIEW

File: stdlib/LinearAlgebra/src/bidiag.jl [hunk 1]
```diff
@@ -205,11 +205,13 @@ convert(T::Type{<:Bidiagonal}, m::AbstractMatrix) = m isa T ? m : T(m)
 similar(B::Bidiagonal, ::Type{T}) where {T} = Bidiagonal(similar(B.dv, T), similar(B.ev, T), B.uplo)
 similar(B::Bidiagonal, ::Type{T}, dims::Union{Dims{1},Dims{2}}) where {T} = zeros(T, dims...)
 
-function kron(A::Diagonal, B::Bidiagonal)
+# We can only handle Vector representations, otherwise _droplast! might not be defined
+function kron(A::Diagonal{<:Any,<:Vector}, B::Bidiagonal{<:Any,<:Vector})
     kdv = kron(diag(A), B.dv)
     kev = _droplast!(kron(diag(A), _pushzero(B.ev)))
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/bidiag.jl:211]: With your `_makevec` above, can't you just have

```suggestion
    kev = _droplast!(_makevec(kron(diag(A), _pushzero(B.ev))))
```

and avoid the extra method?

Comment (eschnett) [reply stdlib/LinearAlgebra/src/bidiag.jl:211]: That's a nice idea. I'll have to call `_makevec` for both `kdv` and `kev` because they need to have the same type, but I like it anyway.

Comment (eschnett) [reply stdlib/LinearAlgebra/src/bidiag.jl]: Done.

**Comment by eschnett** [comment]
The CI errors appear unrelated.

File: stdlib/LinearAlgebra/src/bidiag.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/bidiag.jl]: I think the "homogenization" of the two vectors to same type will be done within the constructor anyway, so it wouldn't be strictly necessary. OTOH, this performs the same amount of work and allocations, so should be fine.

**Comment by dkarrasch** [comment]
Can we have a simple test to guard against regression? I think ranges should make up for good diagonal types that don't support `deleteat!`, though they will likely be turned into `Vector`s upon calling `_pushzero`... not sure.

**Comment by Tokazama** [comment]
This sort of thing is the motivation for https://github.com/JuliaLang/julia/pull/46500

File: stdlib/LinearAlgebra/src/bidiag.jl (hunk 1 above)
Comment (eschnett) [reply stdlib/LinearAlgebra/src/bidiag.jl]: No, this does not happen:
```Julia
julia> Bidiagonal([1,2], sparsevec([3]), :U)
ERROR: MethodError: no method matching Bidiagonal(::Vector{Int64}, ::SparseVector{Int64, Int64}, ::Symbol)
```
(although maybe it should happen...)
