### PR TITLE
pmap docstring update, hook exception input changes.

### LINKED ISSUE #19652: `pmap(f, c; distributed=false` is not equivalent to `asyncmap(f, c)`
In the docs the following calls are described as equivalent.

> `pmap(f,c; distributed=false)` and `asyncmap(f,c)`

However, the `pmap` call will only run an `asyncmap` with `ntasks` equal to `nworkers(p)` (as shown [here](https://github.com/JuliaLang/julia/blob/master/base/pmap.jl#L120)) while the `asyncmap` call will run a `Task` for each element of `c`. If this is the intended behaviour it would help to mention it in the docs to avoid confusion.

### PR DESCRIPTION
**Pull request by amitmurthy**
This PR

- Updates docstring for pmap
- Cleans up exception input in the hooks. Previously hooks were input the wrapped `RemoteException`, now they are input the actual root exception.
- deprecated keyword args have been removed

Please provide feedback on the updated docstring.
Also a good time to bikeshed keyword arg names.

Closes #19652

### CODE REVIEW

File: base/pmap.jl [hunk 1]
```diff
@@ -158,15 +170,24 @@ function wrap_on_error(f, on_error; capture_data=false)
...
-wrap_retry(f, retry_delays, retry_check) = retry(f, delays=retry_delays, check=retry_check)
+function wrap_retry(f, retry_delays, retry_check)
+    f2 = x -> begin
+        try
+            f(x)
+        catch e
+            rethrow(extract_exception(e))
+        end
+    end
+    retry(f2, delays=retry_delays, check=retry_check)
```
Comment (ararslan) [inline base/pmap.jl]: Not a big deal, but this could perhaps be written more succinctly using a `do` block, e.g.
```julia
retry(delays=retry_delays, check=retry_check) do x
    try
        f(x)
    catch e
        rethrow(extract_exception(e))
    end
end
```

File: base/pmap.jl [hunk 2]
```diff
@@ -38,61 +38,66 @@ workers and tasks.
...
 
-Any error stops pmap from processing the remainder of the collection. To override this behavior
+Any error stops `pmap` from processing the remainder of the collection. To override this behavior
 you can specify an error handling function via argument `on_error` which takes in a single argument, i.e.,
 the exception. The function can stop the processing by rethrowing the error, or, to continue, return any value
 which is then returned inline with the results to the caller.
 
-Failed computation can also be retried via `retry_delays`, `retry_check`, which
-are passed through to `retry` as keyword arguments `delays` and `check`,
+Consider the following two examples. The first one returns the exception object itself inline,
```
Comment (tkelman) [inline base/pmap.jl]: "itself" is redundant

File: test/parallel_exec.jl [hunk 3]
```diff
@@ -663,28 +663,14 @@ end
...
 # Test all combinations of pmap keyword args.
 pmap_args = [
                 (:distributed, [:default, false]),
                 (:batch_size, [:default,2]),
-                (:on_error, [:default, e -> unmangle_exception(e).msg == "foobar"]),
-                (:retry_delays, [:default, fill(0.01, 1000)]),
-                (:retry_check, [:default, (s,e) -> (s,unmangle_exception(e).msg == "foobar")]),
+                (:on_error, [:default, e -> (e.msg == "foobar" ? true : rethrow(e))]),
+                (:retry_delays, [:default, fill(0.001, 1000)]),
+                (:retry_check, [:default, (s,e) -> (s,endswith(e.msg,"foobar"))]),
```
Comment (tkelman) [inline test/parallel_exec.jl]: what else ends up in it?

Comment (amitmurthy) [inline test/parallel_exec.jl]: Helps differentiate between `on_error` and `retry_check` callbacks. One of the test functions below throws "notfoobar".

**Comment by amitmurthy** [comment]
Will merge this tomorrow.
