### PR TITLE
fix #28297, deserializing structs with compact Union-typed fields

### LINKED ISSUE #28297: precompile-related assertion error
```julia
__precompile__(true)
module Parsers

mutable struct Result{T}
    result::Union{T, Missing}
    code::UInt8
    b::UInt8
end

Result(::Type{T}, r::UInt8=0x00, b::UInt8=0x00) where {T} = Result{T}(missing, r, b)

const INT_RESULT = Result(Int)

end
```

results in:
```
julia> using Parsers
[ Info: Precompiling module Parsers
Assertion failed: (loc != NULL && loc != HT_NOTFOUND), function jl_deserialize_value_singleton, file /Users/jacobquinn/julia/src/dump.c, line 1821.

signal (6): Abort trap: 6
in expression starting at no file:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 4628168 (Pool: 4627419; Big: 749); GC: 9
Abort trap: 6
jq-mbp:julia jacobquinn$
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
I believe this was just an assumption that needed to be updated for the new Union representation.

fix #28297

### CODE REVIEW

File: src/dump.c [hunk 1]
```diff
@@ -1818,9 +1818,14 @@ static jl_value_t *jl_deserialize_value_singleton(jl_serializer_state *s, jl_val
     if (s->mode == MODE_MODULE) {
         // TODO: optimize the case where the value can easily be obtained
         // from an external module (tag == 6) as dt->instance
-        assert(loc != NULL && loc != HT_NOTFOUND);
-        arraylist_push(&flagref_list, loc);
-        arraylist_push(&flagref_list, (void*)pos);
+        assert(loc != HT_NOTFOUND);
+        // if loc == NULL, then the caller doesn't need the address of the instance.
```
Comment (vtjnash) [inline src/dump.c]: Would be more accurate to say "is unable to provide the address where the instance will be stored". The assertion seems like it may be correct in detecting that we can't currently compute the tindex for the field store that we'll attempt just after this.

Comment (JeffBezanson) [reply src/dump.c]: What do you mean by tindex?

Comment (vtjnash) [reply src/dump.c]: Oh, right. `tindex` is the codegen name for it. In jl_get_nth_field, it's called the type selector byte.

Comment (JeffBezanson) [reply src/dump.c]: The type selector is serialized separately though; we don't need to compute it.

Comment (vtjnash) [reply src/dump.c]: Oh, that's valid? Ok then, should be all set

**Comment by quinnj** [comment]
Hmmmm, upon further inspection, it seems I'm still hitting an issue here w/ Parsers.jl:
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-beta2.132 (2018-07-26 22:48 UTC)
 _/ |\__'_|_|_|\__'_|  |  jb/fix28297/97cc1cfc7c* (fork: 1 commits, 0 days)
|__/                   |  x86_64-apple-darwin16.7.0

julia> using Parsers
Assertion failed: (loc != NULL), function jl_deserialize_value, file /Users/jacobquinn/julia/src/dump.c, line 1965.

signal (6): Abort trap: 6
in expression starting at no file:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2576180 (Pool: 2575641; Big: 539); GC: 4
Abort trap: 6
jq-mbp:julia jacobquinn$
```

**Comment by JeffBezanson** [comment]
Yeah, there might be another occurrence of a case like this. Can you get more of the stacktrace from gdb? I just need a couple more frames.

**Comment by JeffBezanson** [comment]
Ok, should work now.
