### PR TITLE
Fix eltype of flatten of tuple with non-2 length

### LINKED ISSUE #56783: Regression in `collect(Iterators.flatten((some_values..., )))` on the main branch
The following code fails on the e0656ac017a427f739f985809017a33c269b3af1

```julia
julia> collect(Iterators.flatten((1, )))
ERROR: MethodError: no method matching promote_typejoin(::Type{Int64})
The function `promote_typejoin` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  promote_typejoin(::Any, ::Any)
   @ Base promotion.jl:174

Stacktrace:
 [1] eltype(::Type{Base.Iterators.Flatten{Tuple{Int64}}})
   @ Base.Iterators ./iterators.jl:1205
 [2] eltype(x::Base.Iterators.Flatten{Tuple{Int64}})
   @ Base ./abstractarray.jl:241
 [3] _collect(cont::UnitRange{Int64}, itr::Base.Iterators.Flatten{Tuple{Int64}}, ::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:733
 [4] collect(itr::Base.Iterators.Flatten{Tuple{Int64}})
   @ Base ./array.jl:727
 [5] top-level scope
   @ REPL[2]:1

julia> versioninfo()
Julia Version 1.12.0-DEV.1734
Commit e0656ac017 (2024-12-08 21:48 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin24.1.0)
  CPU: 11 × Apple M3 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m3)
Threads: 1 default, 0 interactive, 1 GC (on 5 virtual cores)
```

Works fine in `1.10.7` and `1.11.2`

```julia
julia> collect(Iterators.flatten((1, ))) 
1-element Vector{Int64}:
 1

julia> versioninfo() # also works on 1.10.7
Julia Version 1.11.2
Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 11 × Apple M3 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m2)
Threads: 1 default, 0 interactive, 1 GC (on 5 virtual cores)
```

Interestingly enough, this works fine
```julia
julia> collect(Iterators.flatten((1, (1, ))))
2-element Vector{Int64}:
 1
 1
```
and also this
```julia
julia> collect(Iterators.flatten((1, (1, ), 1)))
3-element Vector{Int64}:
 1
 1
 1
```
but not this
```julia
julia> collect(Iterators.flatten((1, 1, 1)))
ERROR: MethodError: no method matching promote_typejoin(::Type{Int64}, ::Type{Int64}, ::Type{Int64})
The function `promote_typejoin` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  promote_typejoin(::Any, ::Any)
```

So yeah the idea in the original code that the arguments might or might just number or other collections, previously it was possible to mix those. 

More examples of seemingly broken behaviour
```julia
julia> a = 1
1

julia> collect(Iterators.flatten((a, )))
ERROR: MethodError: no method matching promote_typejoin(::Type{Int64})
The function `promote_typejoin` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  promote_typejoin(::Any, ::Any)
   @ Base promotion.jl:174

Stacktrace:
 [1] eltype(::Type{Base.Iterators.Flatten{Tuple{Int64}}})
   @ Base.Iterators ./iterators.jl:1205
 [2] eltype(x::Base.Iterators.Flatten{Tuple{Int64}})
   @ Base ./abstractarray.jl:241
 [3] _collect(cont::UnitRange{Int64}, itr::Base.Iterators.Flatten{Tuple{Int64}}, ::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:733
 [4] collect(itr::Base.Iterators.Flatten{Tuple{Int64}})
   @ Base ./array.jl:727
 [5] top-level scope
   @ REPL[11]:1

julia> collect(Iterators.flatten((a, a)))
2-element Vector{Int64}:
 1
 1

julia> collect(Iterators.flatten((a, a, a)))
ERROR: MethodError: no method matching promote_typejoin(::Type{Int64}, ::Type{Int64}, ::Type{Int64})
The function `promote_typejoin` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  promote_typejoin(::Any, ::Any)
   @ Base promotion.jl:174

Stacktrace:
 [1] eltype(::Type{Base.Iterators.Flatten{Tuple{Int64, Int64, Int64}}})
   @ Base.Iterators ./iterators.jl:1205
 [2] eltype(x::Base.Iterators.Flatten{Tuple{Int64, Int64, Int64}})
   @ Base ./abstractarray.jl:241
 [3] _collect(cont::UnitRange{Int64}, itr::Base.Iterators.Flatten{Tuple{…}}, ::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:733
 [4] collect(itr::Base.Iterators.Flatten{Tuple{Int64, Int64, Int64}})
   @ Base ./array.jl:727
 [5] top-level scope
   @ REPL[13]:1
Some type information was truncated. Use `show(err)` to see complete types.
```
All of the above works fine in `1.11.2`.

Initially caught [here](https://github.com/ReactiveBayes/GraphPPL.jl/actions/runs/12234711294/job/34124468216?pr=251) with the following stacktrace 

```julia
MethodError: no method matching promote_typejoin(::Type{Symbol}, ::Type{Symbol}, ::Type{Symbol}, ::Type{Symbol})
  The function `promote_typejoin` exists, but no method is defined for this combination of argument types.
  
  Closest candidates are:
    promote_typejoin(::Any, ::Any)
     @ Base promotion.jl:174
  
  Stacktrace:
    [1] eltype(::Type{Base.Iterators.Flatten{NTuple{4, Tuple{Symbol}}}})
      @ Base.Iterators ./iterators.jl:1205
    [2] eltype(x::Base.Iterators.Flatten{NTuple{4, Tuple{Symbol}}})
      @ Base ./abstractarray.jl:241
    [3] _collect(cont::UnitRange{Int64}, itr::Base.Iterators.Flatten{NTuple{4, Tuple{Symbol}}}, ::Base.HasEltype, isz::Base.HasLength)
      @ Base ./array.jl:733
    [4] collect(itr::Base.Iterators.Flatten{NTuple{4, Tuple{Symbol}}})
```

Steps to reproduce are 
```julia
julia> collect(Iterators.flatten((:a, :b, :c, :d)))
ERROR: MethodError: no method matching promote_typejoin(::Type{Any}, ::Type{Any}, ::Type{Any}, ::Type{Any})
The function `promote_typejoin` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  promote_typejoin(::Any, ::Any)
   @ Base promotion.jl:174

Stacktrace:
 [1] eltype(::Type{Base.Iterators.Flatten{NTuple{4, Symbol}}})
   @ Base.Iterators ./iterators.jl:1205
 [2] eltype(x::Base.Iterators.Flatten{NTuple{4, Symbol}})
   @ Base ./abstractarray.jl:241
 [3] _collect(cont::UnitRange{Int64}, itr::Base.Iterators.Flatten{NTuple{…}}, ::Base.HasEltype, isz::Base.SizeUnknown)
   @ Base ./array.jl:737
 [4] collect(itr::Base.Iterators.Flatten{NTuple{4, Symbol}})
```

### PR DESCRIPTION
**Pull request by jakobnissen**
In 4c076c80af, eltype of flatten of tuple was improved by computing a refined eltype at compile time. However, this implementation only worked for length-2 tuples, and errored for all others.
Generalize this to all tuples.

Closes #56783

### CODE REVIEW

File: base/iterators.jl [hunk 1]
```diff
@@ -1202,7 +1203,19 @@ julia> [(x,y) for x in 0:1 for y in 'a':'c']  # collects generators involving It
...
-eltype(::Type{Flatten{I}}) where {I<:Union{Tuple,NamedTuple}} = promote_typejoin(map(eltype, fieldtypes(I))...)
+
+# For tuples, we statically know the element type of each index, so we can compute
+# this at compile time.
+function eltype(::Type{Flatten{I}}) where {I<:Union{Tuple,NamedTuple}}
+    @_foldable_meta
+    T = Union{}
+    for i in fieldtypes(I)
+        T = Base.promote_typejoin(T, eltype(i))
+        T === Any && return Any
```
Comment (nsajko) [inline base/iterators.jl:1214]:
```suggestion
```

This line is unnecessary, right?

File: base/iterators.jl [hunk 2]
```diff
@@ -1202,7 +1203,19 @@ julia> [(x,y) for x in 0:1 for y in 'a':'c']  # collects generators involving It
 flatten(itr) = Flatten(itr)
 
 eltype(::Type{Flatten{I}}) where {I} = eltype(eltype(I))
-eltype(::Type{Flatten{I}}) where {I<:Union{Tuple,NamedTuple}} = promote_typejoin(map(eltype, fieldtypes(I))...)
+
+# For tuples, we statically know the element type of each index, so we can compute
+# this at compile time.
+function eltype(::Type{Flatten{I}}) where {I<:Union{Tuple,NamedTuple}}
+    @_foldable_meta
```
Comment (nsajko) [inline base/iterators.jl:1210]:
```suggestion
```

I think it's not permissible to assume :foldable, because the loop body calls `eltype` on user types, so it calls arbitrary user-defined code.

Comment (martinholters) [reply base/iterators.jl:1210]: How about
```julia
eltype(::Type{Flatten{I}}) where {I<:Union{Tuple,NamedTuple}} = 
    afoldl((T, i) -> Base.promote_typejoin(T, Base.eltype(i)), Union{}, fieldtypes(I)...)
```

File: base/iterators.jl (hunk 1 above)
Comment (jakobnissen) [reply base/iterators.jl]: Yes, but we might as well have Julia do less work at compile time where possible. This fast-path will probably be hit often.

File: base/iterators.jl [hunk 3]
```diff
@@ -1202,7 +1203,23 @@ julia> [(x,y) for x in 0:1 for y in 'a':'c']  # collects generators involving It
...
+    _flatten_eltype(Union{}, T)
+end
+
+function _flatten_eltype(T::Type, I::Type{<:Tuple})
+    T2 = promote_typejoin(T, eltype(tuple_type_head(I)))
+    T2 === Any && return Any
+    _flatten_eltype(T2, tuple_type_tail(I))
+end
+
+_flatten_eltype(T::Type, I::Type{Tuple{}}) = T
```
Comment (martinholters) [inline base/iterators.jl:1221]: If we're willing to give up on the `T2 === Any` short-circuiting, I think we can reduce this to
```suggestion
eltype(::Type{Flatten{I}}) where {I<:Union{Tuple,NamedTuple}} =
    mapreduce(eltype, promote_typejoin, fieldtypes(I))
```

Comment (jakobnissen) [reply base/iterators.jl]: Good idea - that also constant folds for me. I'm fine with not doing the early return trick.
I'm used your implementation in the latest commit (except added `init=Union{}` to handle the empty named tuple case)

**Comment by jakobnissen** [comment]
Turns out we need to think about bootstrapping - `iterators.jl` is defined before a lot of Base (and the compiler), so several functions like `mapreduce` and `tuple_type_tail` are not defined at the time the module is defined (and used to compile the compiler).
I'm giving it a go now with the recursive - somewhat less elegant - implementation. If that still doesn't work, or is too complex for this small accuracy increase, we can just revert to before https://github.com/JuliaLang/julia/pull/55946

**Comment by nsajko** [comment]
> Turns out we need to think about bootstrapping

I second @martinholters suggestion for using `afoldl` above. The `afoldl` function is defined in operators.jl, which is included before iterators.jl.

**Comment by jakobnissen** [comment]
That requires splatting the tuple, which might not be a good idea.

**Comment by nsajko** [comment]
Splatting is only an issue for large tuples, in any case pretty sure splatting directly is preferable to calling `tuple_type_tail`, which seems like a monstrosity, and starts with a warning for incorrectness:

https://github.com/JuliaLang/julia/blob/ece1c70184022341439a774eb27915daf377b02c/base/tuple.jl#L430-L445

**Comment by nsajko** [comment]
> Splatting is only an issue for large tuples

Actually, it doesn't seem to be an issue at all. Here are two variants on @martinholters' suggestion:

```julia
function f(::Type{Iterators.Flatten{I}}) where {I<:Union{Tuple,NamedTuple}}
    Base.afoldl((T, i) -> Base.promote_typejoin(T, eltype(i)), Union{}, fieldtypes(I)...)
end

function g(::Type{Iterators.Flatten{I}}) where {I<:Union{Tuple,NamedTuple}}
    function reducer(t::Type, i::Int)
        Base.promote_typejoin(t, eltype(fieldtype(I, i)))
    end
    Base.afoldl(reducer, Union{}, 1:fieldcount(I)...)
end
```

Both are foldable independently of tuple length:

```julia-repl
julia> Base.infer_effects(f, Tuple{Type{Iterators.Flatten{<:Tuple}}})
(+c,+e,!n,+t,+s,+m,+u,+o,+r)

julia> Base.infer_effects(g, Tuple{Type{Iterators.Flatten{<:Tuple}}})
(+c,+e,!n,+t,+s,+m,+u,+o,+r)

julia> Base.infer_effects(f, Tuple{Type{Iterators.Flatten{<:NamedTuple}}})
(+c,+e,!n,+t,+s,+m,+u,+o,+r)

julia> Base.infer_effects(g, Tuple{Type{Iterators.Flatten{<:NamedTuple}}})
(+c,+e,!n,+t,+s,+m,+u,+o,+r)
```

File: test/iterators.jl [hunk 4]
```diff
@@ -515,6 +515,9 @@ end
 @test eltype(flatten(UnitRange{Int8}[1:2, 3:4])) == Int8
 @test eltype(flatten(([1, 2], [3.0, 4.0]))) == Real
 @test eltype(flatten((a = [1, 2], b = Int8[3, 4]))) == Signed
+@test eltype(flatten((Int[], Nothing[], Int[]))) == Union{Int, Nothing}
+@test eltype(flatten((String[],))) == String
+@test eltype(flatten((Int[], UInt[], Int8[],))) == Integer
```
Comment (nsajko) [inline test/iterators.jl:520]: Test empty tuples, named tuples:

```suggestion
@test eltype(flatten((Int[], UInt[], Int8[],))) == Integer
@test eltype(flatten((; a = Int[], b = Nothing[], c = Int[]))) == Union{Int, Nothing}
@test eltype(flatten((; a = String[],))) == String
@test eltype(flatten((; a = Int[], b = UInt[], c = Int8[],))) == Integer
@test eltype(flatten(())) == Union{}
@test eltype(flatten((;))) == Union{}
```

**Review by nsajko — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Ah, I did not mean to merge this PR without getting @martinholters's approval first.

@martinholters Could you do a post-merge review of this PR? If there are any changes you suggest, we can either make those changes in a follow-up PR, or revert this PR if there are major changes needed.

**Comment by nsajko** [comment]
FWIW the implementation that was merged is what @martinholters suggested: https://github.com/JuliaLang/julia/pull/56802#discussion_r1881965312

**Comment by nsajko** [comment]
Just made a PR to test foldability inference of `eltype` and other basic iteration interface functions for various iterator types: #56838

**Comment by martinholters** [comment]
Right, I'm ok with the implementation, given it's my suggestion. Some `@inferred`s in the tests might have been worth considering.

**Comment by DilumAluthge** [comment]
Thanks Martin!

**Comment by DilumAluthge** [comment]
> Some `@inferred`s in the tests might have been worth considering.

@jakobnissen or @nsajko Would you be able to make a follow-up PR that addresses this?

**Comment by nsajko** [comment]
> Would you be able to make a follow-up PR that addresses this?

See #56838 and #56885
