### PR TITLE
Fix rdiv of complex lhs by real factorizations

### LINKED ISSUE #1019: Missing method in `/(::Adjoint{ComplexF64}, Hessenberg{Float64})`
```julia
julia> A = rand(5,5);

julia> b = rand(5);

julia> H = hessenberg(A);

julia> b' / H # adjoint of real vector is ok
1×5 Matrix{Float64}:
 -7.66339  3.09448  7.69176  0.771431  -0.683927

julia> Matrix(complex(b)') / H # complex single-row matrix is ok
1×5 Matrix{ComplexF64}:
 -7.66339+0.0im  3.09448+0.0im  7.69176-0.0im  0.771431+0.0im  -0.683927+0.0im

julia> complex(b)' / H # adjoint of complex vector fails
ERROR: MethodError: no method matching rmul!(::Matrix{ComplexF64}, ::LinearAlgebra.HessenbergQ{Float64, Matrix{Float64}, Vector{Float64}, false})
```
Is there a good reason why the last call shouldn't give the same result as the one before? (Or maybe even better, an adjoint vector rather than a single-row matrix, also in the real case.)

Noticed while working on JuliaLang/LinearAlgebra.jl#1015 and as a by-product making `complex.(b')` return an `Adjoint` (just as `broadcast(complex, b')` does already) and thus breaking
https://github.com/JuliaLang/julia/blob/958f647d8e2d7d93b9d158f283e0891e8e9cf0b0/stdlib/LinearAlgebra/test/hessenberg.jl#L181

### LINKED ISSUE #50617: Missing method in `/(::Adjoint{ComplexF64}, Hessenberg{Float64})`
```julia
julia> A = rand(5,5);

julia> b = rand(5);

julia> H = hessenberg(A);

julia> b' / H # adjoint of real vector is ok
1×5 Matrix{Float64}:
 -7.66339  3.09448  7.69176  0.771431  -0.683927

julia> Matrix(complex(b)') / H # complex single-row matrix is ok
1×5 Matrix{ComplexF64}:
 -7.66339+0.0im  3.09448+0.0im  7.69176-0.0im  0.771431+0.0im  -0.683927+0.0im

julia> complex(b)' / H # adjoint of complex vector fails
ERROR: MethodError: no method matching rmul!(::Matrix{ComplexF64}, ::LinearAlgebra.HessenbergQ{Float64, Matrix{Float64}, Vector{Float64}, false})
```
Is there a good reason why the last call shouldn't give the same result as the one before? (Or maybe even better, an adjoint vector rather than a single-row matrix, also in the real case.)

Noticed while working on #50548 and as a by-product making `complex.(b')` return an `Adjoint` (just as `broadcast(complex, b')` does already) and thus breaking
https://github.com/JuliaLang/julia/blob/958f647d8e2d7d93b9d158f283e0891e8e9cf0b0/stdlib/LinearAlgebra/test/hessenberg.jl#L181

### PR DESCRIPTION
**Pull request by dkarrasch**
This fixes overseen typos, contained in untested methods, and fixes JuliaLang/LinearAlgebra.jl#1019. The faulty methods were introduced in JuliaLang/julia#46874 and need to be backported to v1.10.

@martinholters

### CODE REVIEW

File: stdlib/LinearAlgebra/src/factorization.jl [hunk 1]
```diff
@@ -200,3 +180,25 @@ function ldiv!(Y::AbstractMatrix, A::Factorization, B::AbstractMatrix)
...
     end
 end
+
+function (/)(B::AbstractMatrix, F::Factorization)
+    require_one_based_indexing(B)
+    TFB = typeof(oneunit(eltype(B)) / oneunit(eltype(F)))
+    rdiv!(copy_similar(B, TFB), F)
+end
+# reinterpretation trick for complex lhs and real factorization
+function (/)(B::Union{Matrix{Complex{T}},Adjoint{Complex{T},Vector{Complex{T}}}}, F::Factorization{T}) where {T<:BlasReal}
```
Comment (martinholters) [inline stdlib/LinearAlgebra/src/factorization.jl:190]: I think this should also work for `Transpose`, i.e.
```suggestion
function (/)(B::Union{Matrix{Complex{T}},Adjoint{Complex{T},Vector{Complex{T}}},Transpose{Complex{T},Vector{Complex{T}}}}, F::Factorization{T}) where {T<:BlasReal}
```
(with corresponding changes in the following).

File: stdlib/LinearAlgebra/src/factorization.jl [hunk 2]
```diff
@@ -200,3 +180,25 @@ function ldiv!(Y::AbstractMatrix, A::Factorization, B::AbstractMatrix)
...
+    require_one_based_indexing(B)
+    x = rdiv!(copy(reinterpret(T, B)), F)
+    return copy(reinterpret(Complex{T}, x))
+end
+# don't do the reinterpretation for [Adjoint/Transpose]Factorization
+(/)(B::Union{Matrix{Complex{T}},Adjoint{Complex{T},Vector{Complex{T}}}}, F::TransposeFactorization{T}) where {T<:BlasReal} =
```
Comment (martinholters) [inline stdlib/LinearAlgebra/src/factorization.jl:196]:
```suggestion
(/)(B::Union{Matrix{Complex{T}},Adjoint{Complex{T},Vector{Complex{T}}},Transpose{Complex{T},Vector{Complex{T}}}}, F::TransposeFactorization{T}) where {T<:BlasReal} =
```

File: stdlib/LinearAlgebra/src/factorization.jl [hunk 3]
```diff
@@ -200,3 +180,25 @@ function ldiv!(Y::AbstractMatrix, A::Factorization, B::AbstractMatrix)
...
+    @invoke /(B::AbstractMatrix, F::Factorization)
+(/)(B::Matrix{Complex{T}}, F::AdjointFactorization{T}) where {T<:BlasReal} =
+    @invoke /(B::AbstractMatrix, F::Factorization)
+(/)(B::Adjoint{Complex{T},Vector{Complex{T}}}, F::AdjointFactorization{T}) where {T<:BlasReal} =
+    (F' \ B')'
```
Comment (martinholters) [inline stdlib/LinearAlgebra/src/factorization.jl:201]:
```suggestion
(/)(B::Adjoint{Complex{T},Vector{Complex{T}}}, F::AdjointFactorization{T}) where {T<:BlasReal} =
    (F' \ B')'
(/)(B::Transpose{Complex{T},Vector{Complex{T}}}, F::TransposeFactorization{T}) where {T<:BlasReal} =
    transpose(transpose(F) \ transpose(B))
```

File: stdlib/LinearAlgebra/test/hessenberg.jl [hunk 4]
```diff
@@ -178,8 +178,9 @@ let n = 10
         @test H \ B ≈ A \ B ≈ H \ complex(B)
         @test (H - I) \ B ≈ (A - I) \ B
         @test (H - (3+4im)I) \ B ≈ (A - (3+4im)I) \ B
-        @test b' / H ≈ b' / A ≈ complex.(b') / H
+        @test b' / H ≈ b' / A ≈ complex(b') / H
```
Comment (martinholters) [inline stdlib/LinearAlgebra/test/hessenberg.jl:181]:
```suggestion
        @test b' / H ≈ b' / A ≈ complex(b') / H
        @test transpose(b) / H ≈ transpose(b) / A ≈ transpose(complex(b)) / H
```

**Review by martinholters — COMMENTED** [review]
The new methods all look good to me, but I haven't checked whether the removed ones leave any holes.

I think we should be able to extent this to `Transpose`, but I'm not totally sure. Try?

**Comment by dkarrasch** [comment]
The "removed" `rdiv!`s have just moved. Instead of specializing on the factorization, I turned them into generic fallbacks. Transpose complex looks a bit weird, but I'll give it a try after CI finishes on the current status.

**Comment by martinholters** [comment]
> Transpose complex looks a bit weird

True, but transpose real is simply unnecessary given that it's equivalent to adjoint real.

Anyway, test failures look unrelated (though some of them are a bit scary), so this seems to be on a good track.

**Comment by martinholters** [comment]
All green CI!

I'm not 100% sold this qualifies as a bugfix. Is there anything that gives a wrong result without this PR or gives an error while it used to work in an earlier version? But even if it does not, I'm still in favor of backporting, as 1.10 is not yet released and this indeed is cleanup to #46874 worth including in the release. (It also adds a feature, so I'd be reluctant to backport it to 1.10.1).

File: stdlib/LinearAlgebra/src/factorization.jl [hunk 5]
```diff
@@ -200,3 +180,27 @@ function ldiv!(Y::AbstractMatrix, A::Factorization, B::AbstractMatrix)
...
     end
 end
+
+function (/)(B::AbstractMatrix, F::Factorization)
+    require_one_based_indexing(B)
+    TFB = typeof(oneunit(eltype(B)) / oneunit(eltype(F)))
+    rdiv!(copy_similar(B, TFB), F)
+end
+# reinterpretation trick for complex lhs and real factorization
+function (/)(B::Union{Matrix{Complex{T}},Adjoint{Complex{T},Vector{Complex{T}}},Transpose{Complex{T},Vector{Complex{T}}}}, F::Factorization{T}) where {T<:BlasReal}
```
Comment (martinholters) [inline stdlib/LinearAlgebra/src/factorization.jl:190]: Uh, this line is quite long. I'm not sure how best to wrap it though. The extreme other end would be
```suggestion
function (/)(
    B::Union{
        Matrix{Complex{T}},
        Adjoint{Complex{T},Vector{Complex{T}}},
        Transpose{Complex{T},Vector{Complex{T}}}
    },
    F::Factorization{T}
) where {T<:BlasReal}
```
Maybe there is some reasonable middle-ground?

File: stdlib/LinearAlgebra/src/factorization.jl [hunk 6]
```diff
@@ -200,3 +180,27 @@ function ldiv!(Y::AbstractMatrix, A::Factorization, B::AbstractMatrix)
...
+    require_one_based_indexing(B)
+    x = rdiv!(copy(reinterpret(T, B)), F)
+    return copy(reinterpret(Complex{T}, x))
+end
+# don't do the reinterpretation for [Adjoint/Transpose]Factorization
+(/)(B::Union{Matrix{Complex{T}},Adjoint{Complex{T},Vector{Complex{T}}},Transpose{Complex{T},Vector{Complex{T}}}}, F::TransposeFactorization{T}) where {T<:BlasReal} =
```
Comment (martinholters) [inline stdlib/LinearAlgebra/src/factorization.jl:196]: Here too.

**Comment by dkarrasch** [comment]
Yeah, "bugfix" might be a bit misleading, but there were typos in the `/` methods (I must have copied from `\` above and changed the signature line, but not the code line) which are corrected here. Whatever that is called if not bugfix. As such, this should definitely be backported.

**Comment by martinholters** [comment]
There's
```
Expression: #= /cache/build/default-amdci5-5/julialang/julia-master/julia-6c4b22f3d1/share/julia/test/abstractarray.jl:762 =# @inferred(cat3v(As)) == zeros(2, 2, 2)
--
  | return type Array{Float64, 3} does not match inferred return type Array{_A, 3} where _A
```
for more than one CI job. Can that possibly be related? I couldn't explain how.

**Review by martinholters — APPROVED** [review]
LGTM, but given that this was a bit of collaboration between the two us, another pair of eyes would be welcome.

**Comment by martinholters** [comment]
Ah, the CI failures I worried about are https://github.com/JuliaLang/julia/issues/50550, so unrelated (as expected).
