### PR TITLE
Visit :cfunction during slot renaming

### LINKED ISSUE #27215: @cfunction macro does not work with locally defined functions
In 0.7 `@cfunction(f, ...)` complains about `f` not being defined if `f` is not in global scope.

Specifically, if we wrap the example from the manual in another function call:

```julia
function once_removed()
    function mycompare(a, b)::Cint
        return (a < b) ? -1 : ((a > b) ? +1 : 0)
    end
    mycompare_c = @cfunction(mycompare, Cint, (Ref{Cdouble}, Ref{Cdouble}))
end
```
it results in:
```
ERROR: UndefVarError: mycompare not defined
```
A workaround would seem to be to `$`-interpolate the name into the macro call, i.e.
```julia
function once_removed()
    function mycompare(a, b)::Cint
        return (a < b) ? -1 : ((a > b) ? +1 : 0)
    end
    mycompare_c = @cfunction($mycompare, Cint, (Ref{Cdouble}, Ref{Cdouble}))
end
```
but if we call once_removed as in  `a = once_removed()`, it results in 
```
Internal error: encountered unexpected error in runtime:
BoundsError(a=Array{Any, (1,)}[typeof(Main.once_removed)], i=(2,))
rec_backtrace at /home/macd/julia/src/stackwalk.c:94
record_backtrace at /home/macd/julia/src/task.c:246
jl_throw at /home/macd/julia/src/task.c:577
jl_bounds_error_ints at /home/macd/julia/src/rtutils.c:187
getindex at ./array.jl:681
_widen_all_consts! at ./compiler/optimize.jl:666
_widen_all_consts! at ./compiler/optimize.jl:662
widen_all_consts! at ./compiler/optimize.jl:695
optimize at ./compiler/optimize.jl:331
typeinf at ./compiler/typeinfer.jl:436
typeinf_frame at ./compiler/typeinfer.jl:96 [inlined]
typeinf_code at ./compiler/typeinfer.jl:191
...
```
However, it seems that `a` is still a good function pointer for C or Fortran (at least my Fortran wrappers still seem to work OK)
```
julia> versioninfo()
Julia Version 0.7.0-DEV.5175
Commit 9f2f712* (2018-05-23 01:11 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by Keno**
Fixes #27215

### CODE REVIEW

File: test/ccall.jl [hunk 1]
```diff
@@ -1443,3 +1443,12 @@ callback27178(cb::CTF) where CTF<:CallThisFunc27178 = nothing
...
 @test isa(get_c_func(sin), Ptr)
+
+# issue #27215
+function once_removed()
+    function mycompare(a, b)::Cint
+        return (a < b) ? -1 : ((a > b) ? +1 : 0)
+    end
+    mycompare_c = @cfunction($mycompare, Cint, (Ref{Cdouble}, Ref{Cdouble}))
+end
+@test isa(once_removed(), Ptr)
```
Comment (vtjnash) [inline test/ccall.jl]: This method is not supposed to return a Ptr

**Review by vtjnash — CHANGES_REQUESTED** [review]
