### PR TITLE
fix #32678, error due to Ptr constant in `_reformat_bt`

### LINKED ISSUE #32678: Problem with `_reformat_bt`?
test failure appears on https://build.julialang.org/#/builders/76/builds/449/steps/8/logs/stdio, inhibiting fixing the buildbot CI since we can't see the real error:
```
fatal: error thrown and no exception handler available.
BoundsError(a=Array{Any, (0,)}[], i=(1,))
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:94
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:217 [inlined]
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:454
jl_bounds_error_ints at /buildworker/worker/package_linux64/build/src/rtutils.c:183
getindex at ./array.jl:742 [inlined]
_reformat_bt at ./error.jl:67
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2049 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2213
catch_backtrace at ./error.jl:91
task_done_hook at ./task.jl:318
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2049 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2213
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1630 [inlined]
jl_finish_task at /buildworker/worker/package_linux64/build/src/task.c:174
start_task at /buildworker/worker/package_linux64/build/src/task.c:614
unknown function (ip: 0xffffffffffffffff)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Also change `jl_get_backtrace` to return a pair of values instead of mutating. This seems to have been missing a write barrier, plus `jl_backtrace_from_here` is very similar and already returns a pair, so might as well make them match.

fix #32678

### CODE REVIEW

File: base/error.jl [hunk 1]
```diff
@@ -70,7 +70,7 @@ function _reformat_bt(bt, bt2)
     i, j = 1, 1
     while i <= length(bt)
         ip = bt[i]::Ptr{Cvoid}
-        if ip == Ptr{Cvoid}(-1%UInt)
+        if UInt(ip) == (-1 % UInt)
```
Comment (Keno) [inline base/error.jl]: So the issue is that we make this `-1` Ptr into a literal and then don't serialize it properly. That seems ... bad?

Comment (JeffBezanson) [reply base/error.jl]: Yes, we save all pointers as NULL so that we can detect that an object is uninitialized at run time, and re-create the needed native objects. Interestingly dump.c has this:
```
                if (t->name == jl_pointer_typename && jl_unbox_voidpointer(v) != (void*)-1) {
                    // normalize most pointers to NULL, to help catch memory errors
                    // but permit MAP_FAILED / INVALID_HANDLE to be stored unchanged
```
but staticdata.c doesn't have the special case for -1. @vtjnash & I discussed limiting this somehow, e.g. only nulling mutable object fields.

Comment (Keno) [reply base/error.jl]: This one is particularly bad because the user didn't write `@eval :($(Ptr{Cvoid}(-1%UInt)))`, but just the code `Ptr{Cvoid}(-1%UInt)`. The fact that we construct and inline that pointer in the IR is just something the compiler does. Perhaps we need to prevent inference from creating `Const` `Ptr`s?

Comment (vtjnash) [reply base/error.jl]: yeah, stopping inference from embedding pointers would probably be a better plan

File: src/stackwalk.c [hunk 2]
```diff
@@ -240,18 +240,17 @@ JL_DLLEXPORT jl_value_t *jl_backtrace_from_here(int returnsp, int skip)
     return bt;
 }
 
+// note: btout and bt2out must be GC roots
```
Comment (c42f) [inline src/stackwalk.c]: I'm a little surprised the static analyzer is ok with this; I believe these should be marked with `JL_REQUIRE_ROOTED_SLOT`? I can add that tweak in #33277 where I'm touching the same code anyway.

**Comment by KristofferC** [comment]
Can this be backported? It happens all the time when dealing with package compilation stuff.

**Comment by c42f** [comment]
Yes I think it would be sufficient to backport only the single line with the `if UInt(ip) == (-1 % UInt)`. The rest is just cleanup.
