### PR TITLE
REPLCompletions: PATH caching tweaks

### LINKED ISSUE #52890: `ConcurrencyViolationError("lock must be held")` during repl shell completions
Looks like an issue from https://github.com/JuliaLang/julia/pull/52833 (cc @IanButterworth)

If I go into the shell mode and mash the keyboard (incl. backspace), I get:
```julia
./julia --startup-file=no -q
shell> eiaorsntoaUnhandled Task ERROR: ConcurrencyViolationError("lock must be held")
Stacktrace:
 [1] concurrency_violation()
   @ Base ./condition.jl:8
 [2] assert_havelock
   @ Base ./condition.jl:25 [inlined]
 [3] assert_havelock
   @ Base ./condition.jl:48 [inlined]
 [4] assert_havelock
   @ Base ./condition.jl:72 [inlined]
 [5] notify(c::Condition, arg::Any, all::Bool, error::Bool)
   @ Base ./condition.jl:150
 [6] notify (repeats 2 times)
   @ Base ./condition.jl:148 [inlined]
 [7] cache_PATH()
   @ REPL.REPLCompletions ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:339
 [8] (::REPL.REPLCompletions.var"#14#17")()
   @ REPL.REPLCompletions ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:386
```

```julia
julia> versioninfo()
Julia Version 1.11.0-DEV.1269
Commit 2f60a38ca0 (2024-01-13 15:16 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin23.0.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE = eager
```

This was on #52883 but I don't think it's related to the PR changes there.

### PR DESCRIPTION
**Pull request by IanButterworth**
Followup to https://github.com/JuliaLang/julia/pull/52833

- [x] Switch to waiting on the cache task for tests (Fixes https://github.com/JuliaLang/julia/issues/52890)
- [x] Only yield if at least 0.01s since last yield, to keep performance but not block typing
- [x] If 10s has passed since last cache re-cache, incase the filesystem has changed

Fixes https://github.com/JuliaLang/julia/issues/52890

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -276,7 +276,7 @@ function cached_PATH_changed()
     global cached_PATH_string
     @lock(PATH_cache_lock, cached_PATH_string) !== get(ENV, "PATH", nothing)
 end
-const PATH_cache_finished = Base.Condition() # used for sync in tests
+const PATH_cache_finished = Threads.Condition() # used for sync in tests
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:279]:
```suggestion
const PATH_cache_finished = Base.Event() # used for sync in tests
```

Looks like you aren't managing the state and lock during the tests, so this may need to be an Event in that case (which manages those for you) to avoid concurrency errors and missed events. The tests can call `Base.reset(PATH_cache_finished)` to prepare.

An alternate better option here might be making this a `Union{Task,Nothing}` so you can `wait()` on the worker task directly when required, e.g. so that tab completion with `<tab>` is still correct after that previous PR change.

Comment (IanButterworth) [reply stdlib/REPL/src/REPLCompletions.jl]: Updated to the latter

File: stdlib/REPL/src/REPLCompletions.jl [hunk 2]
```diff
@@ -271,25 +271,34 @@ end
...
+PATH_cache_task::Union{Task,Nothing} = nothing # used for sync in tests
+next_cache_update::Float64 = 0.0
+function maybe_spawn_cache_PATH()
+    global PATH_cache_task, next_cache_update
+    @lock PATH_cache_lock begin
+        PATH_cache_task isa Task && !istaskdone(PATH_cache_task) && return
+        time() < next_cache_update && return
+    end
+    PATH_cache_task = Threads.@spawn REPLCompletions.cache_PATH()
+    Base.errormonitor(PATH_cache_task)
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:283]:
```suggestion
        PATH_cache_task = Threads.@spawn REPLCompletions.cache_PATH()
        Base.errormonitor(PATH_cache_task)
    end
```
(to fix the data race here)

**Review by vtjnash — APPROVED** [review]
Thank you!
