### PR TITLE
Fix #29766: printing of InexactError

### LINKED ISSUE #29766: confusing argument printing in InexactError
```
julia> Int(1.5)
ERROR: InexactError: Int64(Int64, 1.5)
```

I believe this is due to generic code that's also used for functions like `trunc`. But in this case it should print `Int64(1.5)`.

### PR DESCRIPTION
**Pull request by kim366**
Only omits the type, if the function is not that type's constructor

### CODE REVIEW

File: base/errorshow.jl [hunk 1]
```diff
@@ -153,7 +153,11 @@ function showerror(io::IO, ex::UndefVarError)
 end
 
 function showerror(io::IO, ex::InexactError)
-    print(io, "InexactError: ", ex.func, '(', ex.T, ", ", ex.val, ')')
+    if  Symbol(ex.T) === ex.func
```
Comment (JeffBezanson) [inline base/errorshow.jl]: I would use `nameof(ex.T)` (since it's a type) instead of `Symbol`.

**Comment by fredrikekre** [comment]
See also #29779

**Comment by JeffBezanson** [comment]
Thanks. Please add a brief description to the commit message (even just a couple words) instead of just the fixed issue number.

**Comment by kim366** [comment]
Ok

**Comment by kim366** [comment]
Right, I did not see the other PR. Should I close mine?

**Comment by JeffBezanson** [comment]
I think this is better for now since it's minimal. You'll need to bring over some of the doctest changes from that PR though.

**Comment by kim366** [comment]
Done :)

**Comment by kim366** [comment]
I feel like force-pushing is not the right method, but I want to keep it as one commit

**Comment by KristofferC** [comment]
Force pushing is fine, but even you add multiple commits it can be squashed by the person who merges it with the GitHub UI.

**Comment by kim366** [comment]
I see, ok

**Comment by kim366** [comment]
I thought Hacktibwefest was impossible, but now I‘m at 3 PRs merged in 2 weeks
