### PR TITLE
Test: quote Symbol values in @test failure pretty printing

### LINKED ISSUE #57287: Failure to quote symbols in pretty printing in `@test` failures
```julia
julia> x = 1; y = :sym; @test x == y
Test Failed at REPL[48]:1
  Expression: x == y
   Evaluated: 1 == sym
```

Should be `Evaluated 1 == :sym`

### PR DESCRIPTION
**Pull request by apoorvdarshan**
## Summary

- Wrap `Symbol` values in `QuoteNode` in `eval_test_comparison` and `eval_test_function` so that `@test` failure messages display symbols with the `:` prefix (e.g., `:sym` instead of `sym`)
- Add tests for symbol comparison and symbol-in-function-call failure pretty printing

Fixes #57287

### CODE REVIEW

**Comment by vtjnash** [comment]
Added a variety of other related fixes, so that we aren't just playing whack-a-mole with awkward-specific pattern matching from issue to PR. Should be safe to merge now.

File: stdlib/Test/src/Test.jl [hunk 1]
```diff
@@ -368,33 +368,35 @@ struct Threw <: ExecutionResult
...
+            # chained comparisons stop running at the first `false`
             res = op(a, b)
         end
-        quoted_args[i] = a
-        quoted_args[i+2] = b
-        i += 2
     end
 
+    for i = 1:2:n
+        comparison_args[i] = quoted(comparison_args[i])
```
Comment (Keno) [inline stdlib/Test/src/Test.jl:387]: I think https://github.com/JuliaLang/julia/pull/61149 was right that `quoted` is the wrong predicate here in that it may have insufficiently many levels of quoting for correct printing.

Comment (vtjnash) [reply stdlib/Test/src/Test.jl:387]: Not Meta.quot as there, this is quoted, which is the optimal predicate here (and fairly new)

Comment (Keno) [reply stdlib/Test/src/Test.jl:387]: Alright, never mind. I thought `quoted` was a no-op on `QuoteNode`, but it's not.

**Review by Keno — APPROVED** [review]
