### PR TITLE
Optimize findall(f, ::AbstractArray{Bool})

### LINKED ISSUE #42187: Performance regression in `findall` on `Bool` array with predicate
Repro:

```jl
using BenchmarkTools
const y = rand(Bool, 1000)
@btime findall(x -> x > 1, y)
```

1.6:

```jl
julia> @btime findall(x -> x > 1, y)
  300.167 ns (1 allocation: 80 bytes)
Int64[]
```

1.7:

```jl
julia> @btime findall(x -> x > 1, y)
  702.505 ns (6 allocations: 4.50 KiB)
Int64[]
```

Also, note the increase in allocations

### PR DESCRIPTION
**Pull request by jakobnissen**
Fix https://github.com/JuliaLang/julia/issues/42187

The code is slightly more complicated than before, but faster than before the regression.
Also added more tests to cover some cases that was not covered before.

Benchmark (updated 2022-01-08):
```
using BenchmarkTools
A = rand(Bool, 2^16);

@btime findall(A);
@btime findall(!, A);
@btime findall(i -> i > 1, A);

1.7.0:
  267.358 μs (2 allocations: 255.86 KiB)
  59.157 μs (7 allocations: 268.67 KiB)
  7.508 μs (6 allocations: 12.44 KiB)

This PR:
  36.038 μs (2 allocations: 254.48 KiB)
  45.537 μs (5 allocations: 257.72 KiB)
  524.746 ns (2 allocations: 80 bytes)
```

### CODE REVIEW

**Comment by KristofferC** [comment]
Out of curiosity, do you know what caused the regression in the first place?

**Comment by jakobnissen** [comment]
Appears to be https://github.com/JuliaLang/julia/pull/37177, which sped up findall by instantiating a vector of bool (or rather, a bitvector) firsts and working on that. Of course, that is needless when the input is already a vector of bool.

**Comment by jakobnissen** [comment]
I don't understand the whitespace CI failure. There is no trailing whitespace. Running `git rebase --whitespace=fix HEAD~1` doesn't seem to change anything (according to `git diff findallbool origin/findallbool`). In the CI failure there is a message: `# We're changing some of the values so the `let` trick isn't applicable`. Is there a problem with using `let` in Base?

File: base/array.jl [hunk 1]
```diff
@@ -2331,20 +2331,46 @@ Int64[]
 function findall(A)
     collect(first(p) for p in pairs(A) if last(p))
 end
+
 # Allocating result upfront is faster (possible only when collection can be iterated twice)
-function findall(A::AbstractArray{Bool})
-    n = count(A)
+function findall(f::Function, A::AbstractArray{Bool})
+    # Compute f for true and false only once
+    ft, ff = f(true), f(false)
```
Comment (KristofferC) [inline base/array.jl:2338]: I think it is fine to assume a pure function here. I guess it could be argued that it is a bit wasteful to call `f(true)` on `findall(expensive_function, [false])`. I don't know if it is worth complicating the code for it though, probably not.

Comment (jakobnissen) [reply base/array.jl:2338]: That's true. On the other hand, it's much cheaper if the function takes any significant time to compute, since here there will only be 2 calls to f, instead of 1 call per element of A. I suppose the Base solution can only be the most generally applicable one, with special cases having to be handled by hand-crafted for loops.

File: base/array.jl [hunk 2]
```diff
@@ -2331,20 +2331,46 @@ Int64[]
...
+
+function _findall(invert::Bool, I::Vector, A::AbstractArray{Bool})
     cnt = 1
-    for (i,a) in pairs(A)
-        if a
-            I[cnt] = i
-            cnt += 1
-        end
+    len = length(I)
+    @inbounds for (k, v) in pairs(A)
```
Comment (vtjnash) [inline base/array.jl:2352]: this is probably not inbounds

**Comment by KristofferC** [comment]
> I don't understand the whitespace CI failure.

You need to rebase on master to get the fix.

**Comment by jakobnissen** [comment]
Okay, should be good now.

File: base/array.jl [hunk 3]
```diff
@@ -2336,20 +2336,48 @@ Int64[]
...
+    i = firstindex(A)
+    cnt = 1
+    len = length(I)
+    @inbounds while cnt ≤ len
+        I[cnt] = i
+        cnt += A[i] ⊻ invert
+        i = nextind(A, i)
+    end
+    I
+end
```
Comment (nalimilan) [inline base/array.jl:2375]: I assume you have checked that this method for vectors is faster than the generic one for arrays when compiled for vectors? :-)

**Review by nalimilan — COMMENTED** [review]
Woops, thanks! I can't believe I missed that obvious case at  #37177. :-/

File: base/array.jl (hunk 3 above)
Comment (jakobnissen) [reply base/array.jl:2375]: Yep, this is the one the benchmark in the OP times.

Comment (nalimilan) [reply base/array.jl:2375]: Yes, but I mean, is it faster than the method for `AbstractArray` that you also introduce in this PR?

Comment (jakobnissen) [reply base/array.jl:2375]: Ah, I see! Yes, it is faster, but only by about 30%

Comment (nalimilan) [reply base/array.jl:2375]: Yeah, maybe we could just drop it. Isn't the performance difference between the two methods due to `@inbounds`?

Though regarding `@inbounds` I think it's considered as OK to assume that `nextind` returns a valid index. I don't understand why @vtjnash said that `@inbounds` isn't OK for the `AbstractArray` method.

Comment (jakobnissen) [reply base/array.jl:2375]: Redid the benchmark again more carefully - there is actually a significant difference between the vector and array implementations. So keeping it for now.

File: base/array.jl (hunk 2 above)
Comment (nalimilan) [reply base/array.jl]: @vtjnash Why wouldn't this be in bounds? We known that `cnt` cannot be larger than `length(A)`.

File: base/array.jl [hunk 4]
```diff
@@ -2336,20 +2336,48 @@ Int64[]
...
+        cnt += v ⊻ invert
     end
     I
 end
 
+function _findall!(I::Vector, invert::Bool, A::AbstractVector{Bool})
+    i = firstindex(A)
+    cnt = 1
+    len = length(I)
+    @inbounds while cnt ≤ len
```
Comment (vtjnash) [inline base/array.jl:2369]:
```suggestion
    while cnt ≤ len
```

Comment (nalimilan) [reply base/array.jl]: I still don't understand the problem here... :-/

Comment (jakobnissen) [reply base/array.jl]: Just out of curiosity, I would also like to know the policy here. Is the idea that a custom subtype of AbstractArray may implement indexing wrong, and therefore it's better to throw an indexerror instead of a potential segfault, even when we know it's inbounds for well-defined arrays? The cost of boundschecking here is significant - about 60% increased runtime for long vectors on my laptop.

File: base/array.jl (hunk 2 above)
Comment (oscardssmith) [reply base/array.jl:2357]: `Base` can't assume that `AbstractArray` have correct implementations of `length`

Comment (KristofferC) [reply base/array.jl:2357]: @oscardssmith, I think we have some problems then :P

https://github.com/JuliaLang/julia/blob/5bf1ca5c724143091973ef6632f1b3026d8021af/base/sort.jl#L502-L517

https://github.com/JuliaLang/julia/blob/5bf1ca5c724143091973ef6632f1b3026d8021af/base/abstractarray.jl#L450-L453

https://github.com/JuliaLang/julia/blob/5bf1ca5c724143091973ef6632f1b3026d8021af/base/reduce.jl#L410-L431

etc etc

Comment (mbauman) [reply base/array.jl:2357]: But also `I` is a `Vector` and is not abstract.

File: base/array.jl (hunk 1 above)
Comment (KristofferC) [reply base/array.jl:2343]: Yes, but in my example above there is only one element in the array.

**Comment by jakobnissen** [comment]
What this PR needs now is a decision on two details:
* Currently, this PR evaluates `f(true)` and `f(false)` up front for speed. If `f` is a slow function and the input array contains zero or one element, this will make the PR slower. In most cases, it will be faster though. Also, its correctness assumes `f` is side effect-free. Are these two things acceptable?
* Currently, this PR uses `@inbounds`, assuming the input type has a well-defined `AbstractArray` interface (e.g. `length` is not implemented wrong). Is this OK?

If both points are fine, this can be merged.

File: base/array.jl [hunk 5]
```diff
@@ -2329,19 +2329,39 @@ function findall(A)
...
+    end
+    I
+end
+
+function _findall(f::Function, I::Vector, A::AbstractVector{Bool})
+    i = firstindex(A)
+    cnt = 1
+    len = length(I)
+    @inbounds while cnt ≤ len
+        I[cnt] = i
```
Comment (oscardssmith) [inline base/array.jl:2354]: This line can be `@inbounds` but the next 2 can't. `A` can be any AbstractArray, so can have broken indexing.

File: base/array.jl [hunk 6]
```diff
@@ -2329,19 +2329,39 @@ function findall(A)
...
-            I[cnt] = i
-            cnt += 1
-        end
+    len = length(I)
+    for (k, v) in pairs(A)
+        cnt > len && break
+        I[cnt] = k
+        cnt += f(v)
+    end
+    I
```
Comment (JeffBezanson) [inline base/array.jl:2346]: We could handle impure `f` here (e.g. calling `rand`) by checking the length again, and returning only the used part of the vector if `cnt < len`.

File: base/array.jl [hunk 7]
```diff
@@ -2329,19 +2329,39 @@ function findall(A)
...
     cnt = 1
-    for (i,a) in pairs(A)
-        if a
-            I[cnt] = i
-            cnt += 1
-        end
+    len = length(I)
+    for (k, v) in pairs(A)
+        cnt > len && break
+        I[cnt] = k
```
Comment (JeffBezanson) [inline base/array.jl:2343]: Can stop the iteration early if `cnt == len` after this line.

File: base/array.jl (hunk 5 above)
Comment (nalimilan) [reply base/array.jl:2354]: We discussed this above. AFAIK the policy is that we use `@inbounds` when it only relies on the `AbstractArray` implementation being correct. Otherwise fallback definitions couldn't be fast. It would be too bad to force each array package to redefine all these methods just to add `@inbounds`.

Comment (jakobnissen) [reply base/array.jl:2354]: I don't know if that issue is "officially" settled. This issue is relevant. https://github.com/JuliaLang/julia/issues/42030. FWIW, I think having default implementation not be able to assume that the interface is implemented correctly is way too restrictive. It's also inconsistent: It's easy to wreck Julia by writing wrong implementations anyway.

File: base/array.jl (hunk 6 above)
Comment (jakobnissen) [reply base/array.jl]: I guess it's better to not have uninitialized indices. I've added a check that `cnt == len` and a `resize!` if not, for both methods.

File: base/array.jl (hunk 5 above)
Comment (vtjnash) [reply base/array.jl:2356]: There are many expressions in this loop, and while there is a good argument that `A[i]` and `I[cnt]` are always inbounds (since they are checked in the loop iteration), the other expressions are not inbounds.

Comment (jakobnissen) [reply base/array.jl]: Okay, I'm moving the `@inbounds` annotation to only the `Vector` since that is surely guaranteed.

File: base/array.jl [hunk 8]
```diff
@@ -2329,19 +2329,41 @@ function findall(A)
...
+    resize!(I, cnt - 1)
+end
+
+function _findall(f::Function, I::Vector, A::AbstractVector{Bool})
+    i = firstindex(A)
+    cnt = 1
+    len = length(I)
+    while cnt ≤ len
+        @inbounds I[cnt] = i
+        cnt += f(A[i])
```
Comment (nalimilan) [inline base/array.jl:2357]: We can also assume that `A[i]` is in bounds as @vtjnash noted.
```suggestion
        cnt += f(@inbounds A[i])
```

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/42202#issuecomment-1132523631) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c748312_vs_b81a20c/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42202#issuecomment-1132523631) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/15dc499_vs_b81a20c/report.html).

**Comment by aviatesk** [comment]
@nanosoldier `runtests(["AeroAcoustics", "CellMLToolkit", "DiffEqFinancial", "FundamentalsNumericalComputation", "ImageBase", "InspectDR", "LongwaveModePropagator", "NonconvexMMA", "Tapestree", "UKCarbonIntensityData", "ClusteringGA", "DistributedArrays", "ElasticArrays", "FHIRClient", "GPUArrays", "GaussianMixtureAlignment", "HorseML", "OptimizationAlgorithms", "PointwiseKDEs", "QuadEig", "Rfam"], vs = ":master")`

**Comment by aviatesk** [comment]
Any remaining discussion on this? The nanosolidier benchmark/pkgeval look good to me.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42202#issuecomment-1133463590) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/61a725c_vs_88def1a/report.html).

**Comment by aviatesk** [comment]
@nanosoldier `runtests(["DistributedArrays", "PointwiseKDEs"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42202#issuecomment-1133480969) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/61a725c_vs_88def1a/report.html).

**Comment by aviatesk** [comment]
The failure within PointwiseKDEs seems real.

**Comment by jakobnissen** [comment]
I can look at it tomorrow if necessary :)

**Comment by aviatesk** [comment]
Yes please, I didn't follow the details.

**Comment by jakobnissen** [comment]
I think the failure of PointwiseKDEs is unrelated:
* I don't think the test suite even calls `findall`. Modifying `findall` using `Revise` to print to the terminal does not result in any printing when running the test suite
* When running the test suite on master without this PR also fails sporadically (about one in every three runs).

**Comment by nalimilan** [comment]
We don't usually run all packages' testsuites before merging PRs anyway. I don't see any reason why this one would be breaking.
