### PR TITLE
Ensure immutable isbits Union fields get set correctly

### LINKED ISSUE #23351: Memory corruption in Pair
On lastest master I get
```julia
julia> Pair{Union{Float64,Int},Int}(1,1)
Pair{Union{Float64, Int64},Int64}(1, 4696029064)

julia> Pair{Union{Void,Int},Int}(1,1)
Pair{Union{Void, Int64},Int64}(1, 4707506520)

julia> Pair{Union{Void,Int},Int}(nothing,1)

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
has_tight_type at ./show.jl:290
show at ./show.jl:301
show at ./replutil.jl:4
unknown function (ip: 0x111bd47f6)
display at ./repl/REPL.jl:125
unknown function (ip: 0x111bd4756)
display at ./repl/REPL.jl:128
unknown function (ip: 0x111bd4456)
display at ./multimedia.jl:277
inner at ./essentials.jl:605
jl_apply at /Users/andreasnoack/julia-dev/src/./julia.h:1447 [inlined]
jl_f__apply at /Users/andreasnoack/julia-dev/src/builtins.c:440
jl_f__apply_latest at /Users/andreasnoack/julia-dev/src/builtins.c:478
print_response at ./repl/REPL.jl:146
jlcall_print_response_20800 at /Users/andreasnoack/julia-dev/usr/lib/julia/sys.dylib (unknown line)
print_response at ./repl/REPL.jl:132
jlcall_print_response_20796 at /Users/andreasnoack/julia-dev/usr/lib/julia/sys.dylib (unknown line)
do_respond at ./repl/REPL.jl:658
unknown function (ip: 0x111bcf381)
do_call at /Users/andreasnoack/julia-dev/src/interpreter.c:70
eval at /Users/andreasnoack/julia-dev/src/interpreter.c:262
eval_body at /Users/andreasnoack/julia-dev/src/interpreter.c:539
jl_toplevel_eval_body at /Users/andreasnoack/julia-dev/src/interpreter.c:511
jl_toplevel_eval_flex at /Users/andreasnoack/julia-dev/src/toplevel.c:601
jl_toplevel_eval_in at /Users/andreasnoack/julia-dev/src/builtins.c:510
eval at ./repl/LineEdit.jl:3
run_interface at ./repl/LineEdit.jl:1646
run_frontend at ./repl/REPL.jl:961
run_repl at ./repl/REPL.jl:182
_start at ./client.jl:425
true_main at /Users/andreasnoack/julia-dev/./julia (unknown line)
main at /Users/andreasnoack/julia-dev/./julia (unknown line)
Allocations: 3286156 (Pool: 3285956; Big: 200); GC: 6
[1]    50893 segmentation fault  ./julia
```
It works on 0.6

### PR DESCRIPTION
**Pull request by quinnj**
@vtjnash, this isn't quite right yet. When constructed, the selector byte and any non-union fields aren't getting set correctly.

I'm kind of just taking a stab here, and I'm guessing that my use of `fval_info` and `dest` are not quite right, hence the non-working solution here. For example, when I run
```julia
struct BitsUnion
    x::Union{Int64, Float64}
end
BitsUnion(5.0)
```
the `fval_info` is
```
(lldb) call jl_(fval_info.constant)
#<null>
(lldb) call jl_(fval_info.typ)
Float64
(lldb) p fval_info.isimmutable
(const bool) $0 = false
```
I'm not sure why the `fval_info.constant` isn't set, but that causes problems when we try to `compute_tindex_unboxed` later against `BitsUnion`. 

I won't be able to do much else on this for the rest of the day, but any pointers/tips/direction you or @yuyichao could provide would be much appreciated.

fix #23351

### CODE REVIEW

**Comment by quinnj** [comment]
Ok, a little more sleuthing:
- Turns out when you call `julia_type_to_llvm` on `Union{Int64, Float64}`, the resulting `Type *` has `isPointerTy() == true`
- I believe that's why the value setting isn't happening correctly, since `emit_unbox` thinks it's dealing w/ a pointer type when it should be unboxing inline as a `Float64` or `Int64`

I'm not quite sure what the right solution here is though. Modify `emit_unbox`? Lie to LLVM and call `emit_unbox` w/ the largest Union element? 

I feel like there still might be another issue going on, because in the llvm code for `BitsUnion(5.0)`, I still don't see a selector byte store for some reason. Would that be getting optimized out for some reason? Or "clobbered" somehow due to the Union-is-a-pointertype issue?

File: src/builtins.c [hunk 1]
```diff
@@ -259,6 +259,10 @@ JL_CALLABLE(jl_f_sizeof)
     jl_value_t *x = args[0];
     if (jl_is_unionall(x) || jl_is_uniontype(x)) {
         x = jl_unwrap_unionall(x);
+        size_t elsize = 0, al = 0;
+        int isinline = jl_islayout_inline(x, &elsize, &al);
```
Comment (vtjnash) [inline src/builtins.c]: This will have the curious property that `T == S` will not imply `sizeof(T) == sizeof(S)`. I'm not sure if that's going to be an issue, but it does make be nervous. In particular, consider `Union{Tuple{Int64}, Tuple{Int8}}`, which doesn't include selector bits, vs. `Tuple{Union{Int64, Int8}}`, which throws an error.

**Comment by quinnj** [comment]
Bump @vtjnash, I could really use your help/direction here.

**Comment by quinnj** [comment]
Alright, added some tests for @vtjnash's help w/ the fix. Let's see what CI says. Anyone else want to take a look?

**Comment by quinnj** [comment]
That's a lot of great green checkmarks; a shame that Travis is backed up so far.

**Comment by vtjnash** [comment]
Looks like Travis caught another bug though:

	From worker 5:	compare_fields at /home/travis/build/JuliaLang/julia/src/builtins.c:94
(that line is assuming isbits_layout === isdatatype)

**Comment by quinnj** [comment]
Mac failure is #23215; everything else looks all good.

**Comment by Keno** [comment]
@vtjnash is this good to go?

File: src/rtutils.c [hunk 2]
```diff
@@ -883,9 +883,12 @@ static size_t jl_static_show_x_(JL_STREAM *out, jl_value_t *v, jl_datatype_t *vt
                     n += jl_static_show_x(out, *(jl_value_t**)fld_ptr, depth);
                 }
                 else {
-                    n += jl_static_show_x_(out, (jl_value_t*)fld_ptr,
-                                           (jl_datatype_t*)jl_field_type(vt, i),
-                                           depth);
+                    jl_datatype_t *ft = (jl_datatype_t*)jl_field_type(vt, i);
+                    if (jl_is_uniontype(ft)) {
+                        uint8_t sel = ((uint8_t*)fld_ptr)[jl_field_size(vt, i) - 1];
```
Comment (JeffBezanson) [inline src/rtutils.c]: This operation should be abstracted.

**Comment by quinnj** [comment]
I'm still seeing a segfault w/
```julia
struct A
    x::Union{Float64, Void}
end

getx(a::A) = a.x

getx(A(1.0))
```

**Comment by quinnj** [comment]
Ok, looks like the segfault is coming from 
```
data = ctx.builder.CreateSelect(isboxed_union,
-> 5661	                                    ctx.builder.CreateLoad(retvalinfo.gcroot),
   5662	                                    data);
```
when `retvalinfo.gcroot` is accessed. Note that I'm running master merged w/ this branch locally, in case that makes a difference.

**Comment by Keno** [comment]
@quinnj You might try rebasing on top of https://github.com/JuliaLang/julia/pull/23571, which cleans up some of this code. I'll take a look if it still crashes.

**Comment by quinnj** [comment]
That indeed seems to have fixed the problem @keno. I've pushed this branch as rebased on top of #23571

**Comment by quinnj** [comment]
Hmmm, travis linux 64-bit & julia freebsd ci both stalled during tests; I imagine unrelated? Have we seen those kinds of hangs elsewhere?

**Comment by nalimilan** [comment]
Yes, I've seen a hang today in another PR.

**Comment by quinnj** [comment]
Ok, rebased this again on top of @Keno 's new gcroot commit. Also added a test for the codgen-getfield crash I saw above. Let's see what CI says on all of this.

**Comment by quinnj** [comment]
CI all looks good, just the one hang on 32-bit travis linux. I'll let @Keno & @vtjnash decide when this is good to go. I'll keep doing more testing on my end.

File: src/llvm-late-gc-lowering.cpp [hunk 3]
```diff
@@ -1156,10 +1156,9 @@ bool LateLowerGCFrame::CleanupIR(Function &F) {
                 (gc_use_func != nullptr && callee == gc_use_func)) {
                 /* No replacement */
             } else if (pointer_from_objref_func != nullptr && callee == pointer_from_objref_func) {
-                auto *ASCI = new AddrSpaceCastInst(CI->getOperand(0),
-                    CI->getType(), "", CI);
-                ASCI->takeName(CI);
-                CI->replaceAllUsesWith(ASCI);
+                auto *ptr = new PtrToIntInst(CI->getOperand(0), CI->getType(), "", CI);
```
Comment (Keno) [inline src/llvm-late-gc-lowering.cpp]: This isn't valid by IR invariants (it'll complain on LLVM 5.0+). Why does this need to be an int?

File: test/libgit2.jl [hunk 4]
```diff
@@ -76,6 +76,8 @@ end
     a = Base.cconvert(Ptr{LibGit2.StrArrayStruct}, p)
     b = Base.unsafe_convert(Ptr{LibGit2.StrArrayStruct}, a)
     @test p == convert(Vector{String}, unsafe_load(b))
+    @noinline gcuse(a) = a
```
Comment (Keno) [inline test/libgit2.jl]: Should use `Core.gcuse` now.

File: src/llvm-late-gc-lowering.cpp (hunk 3 above)
Comment (vtjnash) [reply src/llvm-late-gc-lowering.cpp]: That's what CI->getType() is. We can worry about LLVM 5 when we start supporting it.

**Review by vtjnash — APPROVED** [review]

File: src/llvm-late-gc-lowering.cpp (hunk 3 above)
Comment (Keno) [reply src/llvm-late-gc-lowering.cpp]: @yuyichao is running in that configuration AFAIK.

Comment (yuyichao) [reply src/llvm-late-gc-lowering.cpp]: I think 4.0 already has non-integral pointer so this will complain there already.

I'm on 4.0 but I do test svn from time to time to make sure it's ready whenever Arch's package is updated.

Should be enough to just keep the old `addrspacecast` and add an `ptrtoint` on top?

Comment (yuyichao) [reply src/llvm-late-gc-lowering.cpp]: This comment is not addressed and it breaks LLVM 4.0 .

**Comment by StefanKarpinski** [comment]
:heart:

**Comment by maleadt** [comment]
This breaks `llvmcall(fun::Ptr)` pretty spectacularly:


```
$ gdb julia

(gdb) break ccall.cpp:1083
Breakpoint 1 (ccall.cpp:1083) pending.

(gdb) run
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.1704 (2017-09-07 16:53 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 1875957dec* (0 days old master)
|__/                   |  x86_64-unknown-linux-gnu

julia> x() = Base.llvmcall(C_NULL, Void, Tuple{Ptr{Int}, Int}, C_NULL, 1)
x (generic function with 1 method)

julia> x()

Thread 1 "julia" hit Breakpoint 1, emit_llvmcall (ctx=..., args=0x7fffeb1c6750, nargs=5) at /home/tbesard/Work/Julia-CUDA/julia-dev/src/ccall.cpp:1083
1083            assert(isPtr);

(gdb) call argtypes[0]->dump()
i64

(gdb) call argtypes[1]->dump()
i64
```

As seen on LLVM.jl, bisected to 1875957dec25c780339d34c3a0d7fda7490b7072.

**Comment by vtjnash** [comment]
llvmcall is still experimental (unstable) anyways

**Comment by maleadt** [comment]
> llvmcall is still experimental (unstable) anyways

Yeah sure stuff breaks on master all the time, just reporting the fact.

**Comment by maleadt** [comment]
OK, so looking at the actual commits this seems fully intended. Is this anonymization of pointers to native-width integers going to be the default from now on? Even though `llvmcall` is unstable, this seems unnecessarily breaking..
