### PR TITLE
Don't error on help for keyword functions

### LINKED ISSUE #23991: help for functions with keyword gives unclear error message:
```jl
help?> f(;x=1)
ERROR: function typeof does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at ./boot.jl:237
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #23991.

Also allows for help where some arguments are undefined.

### CODE REVIEW

File: stdlib/REPL/src/docview.jl [hunk 1]
```diff
@@ -293,9 +293,32 @@ repl(io::IO, other) = esc(:(@doc $other))
 
 repl(x) = repl(stdout, x)
 
+_repl_typeof(arg::Symbol) = :(::(@isdefined($arg) ? typeof($arg) : Any))
+_repl_typeof(arg) = isexpr(arg, :kw) ? :(Expr(:kw, arg[1], _repl_typeof(arg[2]))) :
+                                       :(typeof($arg))
```
Comment (JeffBezanson) [inline stdlib/REPL/src/docview.jl]: `:(::(typeof($arg)))` ?

Comment (simonbyrne) [reply stdlib/REPL/src/docview.jl]: Good catch, thanks.

File: stdlib/REPL/src/docview.jl [hunk 2]
```diff
@@ -293,9 +293,32 @@ repl(io::IO, other) = esc(:(@doc $other))
...
+            if isexpr(arg, :kw)
+                push!(kwargs.args, arg)
+            else
+                push!(args, arg)
+            end
+        end
+        args = _repl_typeof.(args)
+        kwargs.args = _repl_typeof.(kwargs.args)
+
+        x.args = Any[x.args[1], kwargs, args...]
```
Comment (JeffBezanson) [inline stdlib/REPL/src/docview.jl]: `kwargs` should be omitted if it's empty and the original expression did not have `:parameters`.

Comment (simonbyrne) [reply stdlib/REPL/src/docview.jl]: I was hoping to leave this as a hook so that I could provide different help for different combinations of keyword arguments. see https://github.com/simonbyrne/KeywordDispatch.jl/issues/5
