### PR TITLE
Re-fix ccall tests

### LINKED ISSUE #12122: ccall test races with GC
I once saw this in MEMDEBUG mode. It depends on precise timing but it's pretty clear what's going on:

```
     * ccall               exception on 1: ERROR: LoadError: test failed: -4919131752989213765 is 881
 in expression: unsafe_load(ccall_echo_func(IntLike(881),Ptr{IntLike},Ref{IntLike})).x === 881
 in error at ./error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in include at ./boot.jl:254
 in runtests at /home/jeff/src/julia/test/testdefs.jl:197
 in anonymous at multi.jl:629
 in run_work_thunk at multi.jl:590
 in remotecall_fetch at multi.jl:663
 in remotecall_fetch at multi.jl:678
 in anonymous at task.jl:1401
while loading /home/jeff/src/julia/test/ccall.jl, in expression starting on line 20
ERROR: LoadError: LoadError: test failed: -4919131752989213765 is 881
 in expression: unsafe_load(ccall_echo_func(IntLike(881),Ptr{IntLike},Ref{IntLike})).x === 881
 in error at ./error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in include at ./boot.jl:254
 in runtests at /home/jeff/src/julia/test/testdefs.jl:197
 in anonymous at multi.jl:629
 in run_work_thunk at multi.jl:590
 in remotecall_fetch at multi.jl:663
 in remotecall_fetch at multi.jl:678
 in anonymous at task.jl:1401
while loading /home/jeff/src/julia/test/ccall.jl, in expression starting on line 20
while loading /home/jeff/src/julia/test/runtests.jl, in expression starting on line 5
```

`-4919131752989213765` is `0xbbbbbbbbbbbbbbbb`, so the `IntLike` value must have been freed before its contents could be loaded.

### PR DESCRIPTION
**Pull request by yuyichao**
The ccall_echo wrapper is not allowed to allocate.

Alternative is to use a `@generated` function although it seems that this is more likely to work for longer.....

Ref https://github.com/JuliaLang/julia/pull/12185 (Re-fix #12122)

### CODE REVIEW

File: test/ccall.jl [hunk 1]
```diff
@@ -15,37 +15,55 @@ ccall_test_func(x) = ccall((:testUcharX, libccalltest), Int32, (UInt8,), x % UIn
...
+    @test @ccall_echo_func(164, IntLike, Int).x === 164
+end
+@test @ccall_echo_func(IntLike(828), Int, IntLike) === 828
+@test @ccall_echo_func(913, Any, Any) === 913
+@test @ccall_echo_objref(553, Ptr{Any}, Any) === 553
+@test @ccall_echo_func(124, Ref{Int}, Any) === 124
+@test @ccall_echo_load(422, Ptr{Any}, Ref{Any}) === 422
+@test @ccall_echo_load([383], Ptr{Int}, Ref{Int}) === 383
+@test @ccall_echo_load(Ref([144,172],2), Ptr{Int}, Ref{Int}) === 172
+# @test @ccall_echo_load(Ref([8],1,1), Ptr{Int}, Ref{Int}) === 8
```
Comment (tkelman) [inline test/ccall.jl]: should this be test_broken or does it crash horribly?

**Comment by yuyichao** [comment]
Given the line number I believe this should fix https://travis-ci.org/JuliaLang/julia/jobs/194550704

File: test/ccall.jl (hunk 1 above)
Comment (yuyichao) [inline test/ccall.jl]: This fails with a method error on `Ref([8],1,1)`. Blame shows that this has been disabled since it was added. @vtjnash is it a TODO to add fancy indexing support to `RefArray`? (or is it something else that was not working)

**Comment by kshyatt** [comment]
Ready to roll?

**Review by vtjnash — APPROVED** [review]
`@generated` would probably also have been fine, but yes, lgtm
