### PR TITLE
IRShow: print invalid `SSAValue` in red

### LINKED ISSUE #46470: Highlight out-of-bounds SSANodes in red in IR
The function in the following screenshot has 121 SSAValues, but some pass accidentally left an SSAValue(129) in there. It can be difficult to see such errors in the printing, since the ssa values just blend in. I think it would be good to highlight incorrect values like this SSAValue(129) in red to ease debugging.

Screenshot from 2022-08-24 00-48-19

### PR DESCRIPTION
**Pull request by aviatesk**
fix #46470

### CODE REVIEW

File: base/show.jl [hunk 1]
```diff
@@ -1686,7 +1686,14 @@ end
 
 ## AST printing ##
 
-show_unquoted(io::IO, val::SSAValue, ::Int, ::Int)      = print(io, "%", val.id)
+function show_unquoted(io::IO, val::SSAValue, ::Int, ::Int)
+    if get(io, :maxssaid, typemax(Int))::Int < val.id
+        color = :red # invalid SSAValue, print this in red for better recognition
+    else
+        color = :plain
```
Comment (Keno) [inline base/show.jl:1693]: This will undo any formatting that is externally applied, I think this is better of as just a regular `print`.
