### PR TITLE
bpart: Fix a hang in a particular corner case

### LINKED ISSUE #58257: bpart-related hang during precompilation
Happens on 1.12 and nightly. MWE:

```julia
module CUDA
module a
using ..CUDA
macro b(c)
    d = c.args[1]
    e = quote
        check() do
        end
    end
    g = Expr(:call, d.args...)
    h = Expr(:function, g, e)
    esc(h )
end
export @b
Base.get!(i, j) = k
export @l
macro l()
    key = nothing
    if key ==nothing
        quote
            get!($) do
            end
        end
    end
end
end
using .a
function m(res)
    if v()
    end
end
function check(f)
    if  m(res)
end
end
@b function n(w)
end
deviceid(o) = 
 p
  get! 
function Base.get!(constructor, q, o) begin
        if begin
                if constructor()
                end
            end
        end
    end
end
function __init__()
    n(r)

end
function s()
  @l end
function t(o)
  deviceid(dev) + @l  end
const u = 
function x(o)
  get!(u, dev) do
      s()
  end
end
struct v function v()
    t(statedevice)
    x(statedevice)
  end
end
end
```

Hangs in:

```
jl_resolve_implicit_import at /cache/build/tester-amdci5-9/julialang/julia-master/src/module.c:227
jl_resolve_implicit_import at /cache/build/tester-amdci5-9/julialang/julia-master/src/module.c:385 [inlined]
jl_get_binding_partition_ at /cache/build/tester-amdci5-9/julialang/julia-master/src/module.c:387 [inlined]
jl_get_binding_partition_with_hint at /cache/build/tester-amdci5-9/julialang/julia-master/src/module.c:406
lookup_binding_partition at ./runtime_internals.jl:235 [inlined]
scan_specified_partitions at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3619
scan_leaf_partitions at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3648
abstract_eval_globalref at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3671
abstract_eval_special_value at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2978
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3761 [inlined]
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3734 [inlined]
typeinf_local at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4283
```

Reduced from https://github.com/JuliaGPU/CUDA.jl/issues/2762

cc @keno

### PR DESCRIPTION
**Pull request by Keno**
The `jl_get_binding_partition_with_hint` version of the bpart lookup did not properly set the `max_world` of the gap, leaving it at `~(size_t)0`. Having a `gap` with that `max_world`, but with `gap.replace` set is inconsistent and ended up causing an integer overflow downstream in the computation of `expected_prev_min_world`, which looked like a concurrent modification causing an infinite retry. Fixes #58257

### CODE REVIEW

File: Compiler/test/inference.jl [hunk 1]
```diff
@@ -6428,4 +6428,21 @@ global invalid_setglobal!_exct_modeling::Int
...
+    end
+    using .B58257
+    # World age here is N+1
+    @eval f() = $(GlobalRef(B58257, :get!))
+end
+
+## The sequence of events is critical here.
+A58257.get!      # Creates binding partition in A, N+1:∞
+A58257.B58257.get!    # Creates binding partition in A.B, N+1:∞
+Base.invoke_in_world(UInt(38678), getglobal, A58257, :get!) # Expands binding partition in A through <N
```
Comment (vtjnash) [inline Compiler/test/inference.jl:6445]: Why are you using random numbers as worlds? This will break very badly someday...

Comment (Keno) [reply Compiler/test/inference.jl:6445]: Was supposed to be captured earlier, just forgot to commit the change. will fix.
