### PR TITLE
Fix macro hygiene when calling the macro in the same module.

### LINKED ISSUE #14893: Macro hygiene only protect you in different modules.
This was reported at Stack Overflow:

* http://stackoverflow.com/questions/35094986/does-macro-hygiene-only-protect-you-in-different-modules

```julia
   _       _ _(_)_     |  By greedy hackers for greedy hackers
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2446 (2016-02-01 14:54 UTC)
 _/ |\__'_|_|_|\__'_|  |  custom/a9c732a (fork: 2 commits, 0 days)
|__/                   |  Arch Linux x86_64

julia> macro g(y)
           :((x, $y, $(esc(y))))
       end

       x = 1
       function t()
           x = 2
           println(macroexpand(:(@g(x))))
           println(@g(x))
       end

       t()
       println(x)
(x,x,x)
(2,2,2)
1

julia> workspace()

julia> module A
       macro g(y)
           :((x, $y, $(esc(y))))
       end
       x = 1
       end

       x = 3

       function t()
           x = 2
           println(macroexpand(:(A.@g(x))))
           println(A.@g(x))
       end

       t()
(A.x,A.x,x)
(1,1,2)
```

> I had expected the result to be (1, 1, 2).

> However, if I define the macro in a different module, it works as expected.

> Seems the hygiene simply prefix the symbols with the module namespace. Therefore it is impossible for the macro expander to distinguish different scopes in the first case.

### PR DESCRIPTION
**Pull request by yuyichao**
There is a surprising number of base code that relies on the wrong behavior....

One broken test/code that need to be fixed on this commit is the [MacroGlobalFunction test](https://github.com/JuliaLang/julia/commit/a8284df44d61bdeb3f03779ee9cbcb6fdd04a8c4#diff-75b23cc61d190dd99feab17b8e297ee3L3463). The test doesn't work if the macro is used outside the module so I think the fix is correct. However, should the macro expander detect this case and avoid modifying the function name that is defined to be global already?

Closes #14893

c.c. @JeffBezanson about the test mentioned above and since the code was added a long time ago (https://github.com/JuliaLang/julia/commit/605bc65c59451b567bd64e750c1e659424759fe2) I can't really find a explanation why the check is necessary.

### CODE REVIEW

**Comment by yuyichao** [comment]
Also, the `NULL` check was added in https://github.com/JuliaLang/julia/commit/7de4648fcdc8fc69b9c0b1fbc0cefe4698c9a2a7#diff-ee48e36e4d097c33660f778b57339696L97. From the code it seems that `module` should never be `NULL` and when I put an `abort` there it never triggers when running the whole test. Why is the `NULL` check there?

**Comment by JeffBezanson** [comment]
The NULL check might be left over from a case that used to happen during bootstrap.

**Comment by yuyichao** [comment]
OK, I comment out that code (replaced it with an `assert`) and updated the comment in `macroexpand.scm`. Let's see if the CI is happy about it...

**Comment by JeffBezanson** [comment]
> should the macro expander detect this case and avoid modifying the function name that is defined to be global already?

No, it should apply normal hygiene rules, but this is going to require some further fixes. For example in 0.4:

```
julia> module Foo
               macro m()
                quote
                 global x
                 x = 2
                end
               end
            end
Foo

julia> macroexpand(:(@Foo.m))
quote  # none, line 4:
    global Foo.x # none, line 5:
    Foo.x = 2
end
```

This is correct, but gets a `invalid syntax in "global" declaration` error. On master there seems to be a regression, since we get

```
julia> macroexpand(:(@Foo.m))
quote  # none, line 4:
    global x # none, line 5:
    #2#x = 2
end
```

I can see why this regression was not caught, since the code doesn't work either way.

Your change to ast.c is fine, but changing the test should not have been necessary. We'd need the macro expansion to return a more permissive kind of module reference that lets you define a new function using the syntax `M.f(x) = x`. Currently that gives `f not defined`. As it is, this change will break code that does something like

```
macro m()
    quote
        global f
        f(x) = 2
    end
end
@m
```

which would include any module that uses macros to define its own functions. This might be too breaking.

**Comment by yuyichao** [comment]
What do you think is the best solution for this? Allowing assign to `m.x` (including method definition) if `m` is current module?

**Comment by JeffBezanson** [comment]
Maybe we should just go ahead and allow `mod.x = y` generally.

**Comment by yuyichao** [comment]
I'm also thinking maybe we can avoid replacing `f` with `M.f` if there's `global f`? This way we can make sure `:(global a; a = 1)` behaves the same as `:(global a = 1)`?

**Comment by JeffBezanson** [comment]
I think we will still need to return `M.f` to make sure the correct module is used.

**Comment by yuyichao** [comment]
> the correct module is used.

Currently if a macro returns `:(global a = 1)` it creates a global variable `a` in the calling module and if `:(global a; a = 1)` it is an error. I find it a little weird that this two have different behaviors....

**Comment by yuyichao** [comment]
This PR should be ready now. Before someone restarted AppVeyor there was a timeout (that was not just hanging after the tests are done) possibly due to hitting the swap or something similar.

This still have different behavior for `global a = 1` vs `global a; a = 1` in a macro from a different module (the first one defines `a` in caller module and the second defines `a` in macro defining module).

File: src/interpreter.c [hunk 1]
```diff
@@ -232,9 +232,25 @@ static jl_value_t *eval(jl_value_t *e, interpreter_state *s)
...
+            jl_module_t *m = (jl_module_t*)jl_data_ptr(fname)[0];
+            jl_sym_t *sym = (jl_sym_t*)jl_data_ptr(fname)[1];
+            assert(jl_is_symbol(sym));
+            jl_binding_t *b = jl_get_binding_for_method_def(m, sym);
+            jl_value_t *gf = jl_generic_function_def(sym, &b->value,
+                                                     (jl_value_t*)m, b);
+            if (jl_expr_nargs(ex) == 1)
+                return gf;
+        } else if (jl_is_symbol(fname)) {
             jl_value_t **bp=NULL;
```
Comment (vtjnash) [inline src/interpreter.c]: I wrote a more complete diff for this file while attempting to do something else:
https://gist.github.com/vtjnash/3775a58db1efe7489e5922ad1eb117f3

Comment (vtjnash) [inline src/interpreter.c]: the handling in codegen.cpp also needs to be updated for this case

File: src/julia-syntax.scm [hunk 2]
```diff
@@ -1609,6 +1609,16 @@
...
        (case (car lhs)
+         ((globalref)
+          ;; M.b =
+          (let* ((a   (cadr lhs))
+                 (b   (caddr lhs))
+                 (rhs (caddr e))
+                 (rr  (if (or (symbol-like? rhs) (atom? rhs)) rhs (make-ssavalue))))
+            `(block
+              ,.(if (eq? rr rhs) '() `((= ,rr ,(expand-forms rhs))))
+              (call (core setfield!) ,a (quote ,b) ,rr)
```
Comment (vtjnash) [inline src/julia-syntax.scm]: it should be valid to lower this line to `(= ,lhs ,rr)`. that should save us from needing to change the meaning of setfield. it looks like it should be handled correctly since https://github.com/JuliaLang/julia/issues/10403

Comment (yuyichao) [inline src/julia-syntax.scm]: What commit are you talking about? https://github.com/JuliaLang/julia/issues/10403 is an issue not a PR and all commits referenced in that issue are older than this one and I'm pretty sure `$(GlobalRef(...)) = ...` is not handled anywhere when I wrote this.

**Comment by yuyichao** [comment]
Rebased on top of master and Jameson's `interpreter.c` change. CI passed.

Also moved the handling of `GlobalRef` assignments fully to the runtime/JIT (needed to fix `defined-julia-global`) so `setfield!` on the module doesn't need any change anymore.

There's still a difference between `global a; a = 1` and `global a = 1` but that's not new and is a related but different issue so it doesn't have to be addressed in this PR.

**Review by vtjnash — APPROVED** [review]

**Comment by tkelman** [comment]
This could use a NEWS mention given how commonly macros were hitting this.
