### PR TITLE
Fix a few naming conflicts in LinAlg/BLAS. Fixes #14268.

### LINKED ISSUE #14268: Name conflicts between Base.LinAlg and Base.LinAlg.BLAS
I noticed that there are several names in common between the two:
```
julia> intersect(names(Base.LinAlg,true), names(Base.LinAlg.BLAS,true))
5-element Array{Symbol,1}:
 :BLAS
 :axpy!
 :dot
 :eval
 :gemv!
```

axpy! is explicitly imported in blas.jl but dot and gemv! are not.  If this was not intentional, let's fix it by importing these two.  If this was intentional, then I am not sure which dot to extend in CUBLAS for example.

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

File: base/linalg.jl [hunk 1]
```diff
@@ -212,6 +212,7 @@ include("linalg/exceptions.jl")
 include("linalg/generic.jl")
 
 include("linalg/blas.jl")
+import .BLAS: gemv! # consider renaming gemv! in matmul
```
Comment (tkelman) [inline base/linalg.jl]: what's the reasoning here / what do you mean by this?

Comment (andreasnoack) [inline base/linalg.jl]: It looks ugly to have an `import` here, so I was reminded that, in general, I think we should just call the multiplication methods `mul!` when we have the transpose type. The `ge` and `v` information is carried in the argument types. The name `m!` is a bit short though :smile:.

Comment (tkelman) [inline base/linalg.jl]: Right, makes sense, thanks. Though there is the question of whether we should have a Julia API that includes the additional scalar-multiple inputs, and if so whether or not they should match the Fortran ordering.
