### PR TITLE
src/codegen.cpp: fix segfault on `@code_native` with eltype (#34434)

### LINKED ISSUE #31396: Method `round(x::Rational, r::RoundingMode)` is not defined
While `round(::Type{T}, x::Rational, r::RoundingMode)  where {T} ` and `round(x::Rational)` are defined in `rational.jl`, no method exists for `round(x::Rational, r::RoundingMode)`.

e.g.
```
julia> round(1//2)
0//1

julia> round(1//2, RoundNearestTiesUp)
ERROR: MethodError: no method matching round(::Rational{Int64}, ::RoundingMode{:NearestTiesUp})

julia> round(Rational, 1//2, RoundNearestTiesUp)
1//1
```

### LINKED ISSUE #34434: Segfault calling @code_native on eltype
`@code_native` segfaults when called on eltype in Julia 3.1. I've tested with numeric and array inputs:

```julia
julia> @code_native eltype(1)

signal (11): Segmentation fault: 11
in expression starting at REPL[3]:1
Twine at /Users/julia/buildbot/worker/package_macos64/build/usr/include/llvm/ADT/Twine.h:164 [inlined]
Twine at /Users/julia/buildbot/worker/package_macos64/build/usr/include/llvm/ADT/Twine.h:268 [inlined]
jl_get_llvmf_decl at /Users/julia/buildbot/worker/package_macos64/build/src/codegen.cpp:1662
_dump_function_linfo at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/InteractiveUtils/src/codeview.jl:100
_dump_function at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/InteractiveUtils/src/codeview.jl:84
_dump_function at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/InteractiveUtils/src/codeview.jl:71 [inlined]
#code_native#9 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/InteractiveUtils/src/codeview.jl:148 [inlined]
#code_native at ./none:0
#code_native#10 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/InteractiveUtils/src/codeview.jl:150
code_native at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/InteractiveUtils/src/codeview.jl:150
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:328
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0
jl_interpret_toplevel_thunk_callback at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:888
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x11ceeee8f)
unknown function (ip: 0x0)
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:897
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:814
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:764
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:823 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:843
eval at ./boot.jl:330
eval_user_input at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:86
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:118 [inlined]
#26 at ./task.jl:333
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:659
Allocations: 7344139 (Pool: 7342220; Big: 1919); GC: 8
Segmentation fault: 11
```

Version info:

```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.8.8
  [98e50ef6] JuliaFormatter v0.2.4
  [e5e0dc1b] Juno v0.7.2
```

### PR DESCRIPTION
**Pull request by anaveragehuman**
Fixes #34434

According to git bisect:

8c445663547791e59f33f9e8d49b276332107614 is the first bad commit

```                                               
git bisect start                                                                                          
# bad: [c6da87ff4bc7a855e217856757ad3413cf6d1f79] Set VERSION to 1.2.0 (#32964)                           
git bisect bad c6da87ff4bc7a855e217856757ad3413cf6d1f79                                               
# good: [55e36cc308b66d3472990a06b2797f9f9154ea0a] Set VERSION to 1.1.1 (#31969)                      
git bisect good 55e36cc308b66d3472990a06b2797f9f9154ea0a                                                  
# good: [b55b85cd9952ce39246d1bcb6c4b0417ac457531] spawn/IO: supercharge the API (#30278)                 
git bisect good b55b85cd9952ce39246d1bcb6c4b0417ac457531                                                  
# good: [0b38dd0ac1ec977166e71fdee92d2ac5d1ee36fe] More xrefs for the meta docs                           
git bisect good 0b38dd0ac1ec977166e71fdee92d2ac5d1ee36fe                                                  
# bad: [a3997800b0b8d364c628d2a2ec8ae8e246b8f63f] Fix Int64 overrun potential in skip_deleted (#31452)    
git bisect bad a3997800b0b8d364c628d2a2ec8ae8e246b8f63f                                                   
# good: [a168bc8a8c73f6f6b536a40ced32df8c528a7b4b] Merge pull request #31324 from JuliaLang/vc/tuple_props
git bisect good a168bc8a8c73f6f6b536a40ced32df8c528a7b4b
# good: [672bf8bea7b01a1828fc21e6689c8d3fa5f46ea6] realpath buffer is a vector (#31433)
git bisect good 672bf8bea7b01a1828fc21e6689c8d3fa5f46ea6
# good: [c0b40d8530dc62cebc556e026ab5ae5409a7bd29] Merge pull request #31413 from JuliaLang/jn/nfc-1
git bisect good c0b40d8530dc62cebc556e026ab5ae5409a7bd29
# good: [11156024da041ea0060fd267f6acd8d83193b653] Fix #31396 (#31401)
git bisect good 11156024da041ea0060fd267f6acd8d83193b653
# good: [53d7fbfbd67607659e33b779b9c91668dff7ca71] Replaced `Any[...]` with `[...]` in example (#31526)
git bisect good 53d7fbfbd67607659e33b779b9c91668dff7ca71
# good: [9f125f90cdb823e5682868838eded05c394f1944] add test for #28762, at-inferred error (#31430)
git bisect good 9f125f90cdb823e5682868838eded05c394f1944
# bad: [8c445663547791e59f33f9e8d49b276332107614] internals: better representation for code (#31191)
git bisect bad 8c445663547791e59f33f9e8d49b276332107614
# good: [4b1230277ca50c70ee517578db1ec30483cf9ad9] add a nop conversion for some (#31536)
git bisect good 4b1230277ca50c70ee517578db1ec30483cf9ad9
# first bad commit: [8c445663547791e59f33f9e8d49b276332107614] internals: better representation for code (#31191)
```

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
The blamed commit is included in quite a few releases, so I'm wondering if this did really introduce the bug or if the bug was there but not as visible? I've marked for backporting to 1.4 but maybe needs to be backported to 1.3 as well.

**Comment by JeffBezanson** [comment]
The bug does exist in 1.3 as well.

**Comment by AnAverageHuman** [comment]
> The blamed commit is included in quite a few releases, so I'm wondering if this did really introduce the bug or if the bug was there but not as visible? I've marked for backporting to 1.4 but maybe needs to be backported to 1.3 as well.

I started bisecting from 1.2.0 because I noticed it was also broken:

```
/dev/shm$ julia-1.2.0/bin/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @code_native eltype(1)

signal (11): Segmentation fault
in expression starting at REPL[1]:1
Twine at /buildworker/worker/package_linux64/build/usr/include/llvm/ADT/Twine.h:268 [inlined]
jl_get_llvmf_decl at /buildworker/worker/package_linux64/build/src/codegen.cpp:1637
_dump_function_linfo at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/InteractiveUtils/src/codeview.jl:100
_dump_function at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/InteractiveUtils/src/codeview.jl:84
_dump_function at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/InteractiveUtils/src/codeview.jl:71 [inlined]
```

I tested each commit listed in the bisect log above manually with these commands, marking bad if it segfaulted and good otherwise:
```sh
make -j8
./julia <<< 'Main.@code_native eltype(1)'
```

So yes, I think it has actually been broken since that commit.

**Comment by ararslan** [comment]
Suggested test which kind of sucks but fails without this change and should work with it:
```julia
@testset "Issue #34434" begin
    io = IOBuffer()
    code_native(io, eltype, Tuple{Int})
    @test occursin("eltype", String(take!(io)))
end
```

**Comment by KristofferC** [comment]
Would it be better to put the test in `stdlib/InteractiveUtils/test/runtets.jl`?

**Comment by ararslan** [comment]
I think it makes sense to be part of the Base tests in this case, since it isn't testing InteractiveUtils functionality as much as it is testing for a bug in the core of Julia by way of InteractiveUtils for lack of a better reproducer.

**Comment by KristofferC** [comment]
Putting dependencies on standard libraries in the Base tests seems bad though.

**Comment by ararslan** [comment]
Sure, that makes sense.

File: src/codegen.cpp [hunk 1]
```diff
@@ -1685,7 +1685,7 @@ void *jl_get_llvmf_decl(jl_method_instance_t *mi, size_t world, bool getwrapper,
         // internal error
         return NULL;
 
-    const jl_llvm_functions_t &decls = codeinst->functionObjectsDecls;
+    jl_llvm_functions_t &decls = codeinst->functionObjectsDecls;
```
Comment (vtjnash) [inline src/codegen.cpp]:
```suggestion
    jl_llvm_functions_t decls = codeinst->functionObjectsDecls;
```

**Comment by sethaxen** [comment]
Thanks for the fix!
