### PR TITLE
Fix `copyto!(dest, Rdest::CartesianIndices, src, Rsrc::CartesianIndices)` with different step. 

### LINKED ISSUE #45282: `copyto!` with `CartesianIndices` assumes identical step in source and destination indices
https://github.com/JuliaLang/julia/blob/9a0e79723159e168099097cbe435826b4abe0597/base/multidimensional.jl#L1105-L1129

Now that `CartesianIndices` may contain `StepRange`s, the implementation doesn't seem correct.

```julia
julia> a = rand(4)
4-element Vector{Float64}:
 0.7766672217743518
 0.5138339000883105
 0.7793932733439368
 0.6377375487030642

julia> b = zeros(2);

julia> copyto!(b, CartesianIndices(b), a, CartesianIndices((1:2:3,)))
2-element Vector{Float64}:
 0.7766672217743518
 0.0

julia> a[CartesianIndices((1:2:3,))]
2-element Vector{Float64}:
 0.7766672217743518
 0.7793932733439368
```

### PR DESCRIPTION
**Pull request by N5N3**
Local bench shows no performance regression, if the `indices`s of `Rdest` and `Rsrc` are all `NTuple{N,<:AbstractUnitRange}`.
Close #45282.

### CODE REVIEW

File: test/copy.jl [hunk 1]
```diff
@@ -63,6 +63,10 @@ end
         @test B[5:7,2:3] == A
         B[5:7,2:3] .= 0
         @test all(x->x==0, B)
+        copyto!(B, CartesianIndices((3:2:7,1:2:3)), A, RA)
+        @test B[3:2:7,1:2:3] == A
+        copyto!(B, CartesianIndices((7:-1:5,3:-1:2)), A, CartesianIndices(map(reverse, axes(A))))
```
Comment (jishnub) [inline test/copy.jl:68]: Maybe add one more test, where the indices of `B` have a positive step and those of `A` have a negative step? That should complement the current tests where the step is positive or negative for both.

Comment (N5N3) [reply test/copy.jl]: Added.

**Comment by N5N3** [comment]
`power` test failure looks like a real regression (after #42031?) CC @oscardssmith.
On master
```julia
julia> x, y = 48.718f0, -2.f0;

julia> Base.Math.pow_body(x,y)
0.0004213288f0

julia> x^y
0.00042132882f0

julia> x^-2
0.00042132882f0
```
