### PR TITLE
Change ≅ to ≣ in numbers.jl tests

### LINKED ISSUE #18598: Intermittent failure in math test
I just had a `make test` (against 0.6.0-dev.711) spitting out
```
	From worker 7:	     * math                 Test Failed
	From worker 7:	  Expression: lgamma(-300im) ≅ -473.1718507425924 - 1410.3490664555823im
	From worker 7:	   Evaluated: -473.1718507425924 - 1410.349066455582im isequal -473.1718507425924 - 1410.3490664555823im
error in running finalizer: Base.MethodError(f=Base.#real(), args=(Base.RemoteChannel{Base.Channel{Int64}}(where=1, whence=1, id=2),))
error in running finalizer: Base.MethodError(f=Base.#real(), args=(Base.RemoteChannel{Base.Channel{Int64}}(where=1, whence=1, id=2),))
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
```
some more pages of that line repeating, ending in
```
Exception running test math :
On worker 7:
LoadError: There was an error during testing
 in record at ./test.jl:397
 in do_test at ./test.jl:281
 in include_string at ./loading.jl:478
 in include_from_node1 at ./loading.jl:544
 in macro expansion at ./util.jl:232 [inlined]
 in runtests at /home/hol/Projects/julia/test/testdefs.jl:7
 in #619 at ./multi.jl:1425
 in run_work_thunk at ./multi.jl:1005
 in macro expansion at ./multi.jl:1425 [inlined]
 in #618 at ./event.jl:68
while loading /home/hol/Projects/julia/test/math.jl, in expression starting on line 658
ERROR: LoadError: Some tests exited with errors.
 in (::##11#18)() at /home/hol/Projects/julia/test/runtests.jl:72
 in cd(::##11#18, ::String) at ./file.jl:69
 in include_from_node1(::String) at ./loading.jl:541
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:326
while loading /home/hol/Projects/julia/test/runtests.jl, in expression starting on line 26
Makefile:12: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:569: recipe for target 'test' failed
make: *** [test] Error 2
```

(All other tests completed successfully, output omitted.)

Re-running the tests, everything looks fine. Can anyone make sense of that?

### PR DESCRIPTION
**Pull request by p-zubieta**
Fixes #18598

### CODE REVIEW

**Comment by stevengj** [comment]
We should probably use something like `≣` (identical to) in numbers.jl anyway (for `isequal`) rather than `≅`

**Comment by pabloferz** [comment]
`≣` seems better. PR updated.

**Comment by stevengj** [comment]
LGTM.

**Comment by stevengj** [comment]
Travis failure due to timeout on OSX (log saved in gist: https://gist.github.com/stevengj/3be00775bf429cfbe1af1147b3781eb5) … restarted Travis.

File: test/numbers.jl [hunk 1]
```diff
@@ -1,5 +1,7 @@
 # This file is a part of Julia. License is MIT: http://julialang.org/license
 
+≣(a, b) = isequal(a, b) # convenient for comparing NaNs
```
Comment (stevengj) [inline test/numbers.jl]: As a general style note, when we define operators to be equivalent to functions, we generally use `const ≣ = isequal`.  This has some advantages: docstrings for `≣` work, typing `≣` at the REPL prints `isequal` so it is elf-documenting to some extent, and compilation time is decreased.  Not that these considerations matter much in a test file, however.

Comment (pabloferz) [inline test/numbers.jl]: Noted. The reason I defined as a function was to avoid something like #18598 again (in the case someone defines `≣` as another function in another test).

Comment (stevengj) [inline test/numbers.jl]: Okay.
