### PR TITLE
[JuliaLowering] Take macro lno from argument, not provenance

### LINKED ISSUE #150: Macro inside macro expanded with incorrect `__source__` argument
```julia
julia> using Test
julia> macro srcfile()
           string(__source__.file)
       end
@srcfile (macro with 1 method)

julia> @test occursin("REPL", @srcfile)
Test Failed at REPL[2]:1
  Expression: occursin("REPL", #= REPL[2]:1 =# @srcfile())
   Evaluated: occursin("REPL", "/home/topolarity/repos/julia/usr/share/julia/stdlib/v1.14/Test/src/Test.jl")
ERROR: There was an error during testing
```

This test passes with flisp lowering. Causes failures in Artifacts and Downloads and TOML tests.

### PR DESCRIPTION
**Pull request by mlechu**
Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/150

### CODE REVIEW

File: JuliaLowering/src/macro_expansion.jl [hunk 1]
```diff
@@ -276,9 +276,12 @@ function expand_macro(ctx, ex)
     mctx = MacroContext(ctx.graph, ex, current_layer(ctx), ctx.expr_compat_mode)
     macfunc = eval_macro_name(ctx, mctx, macname)
     raw_args = ex[3:end]
-    macro_loc = let loc = source_location(LineNumberNode, ex)
+    macro_loc = if ex[2].value isa LineNumberNode
```
Comment (topolarity) [inline JuliaLowering/src/macro_expansion.jl]: This should probably check the kind of `ex[2]`, esp. since I believe it is occasionally `nothing::K"core"`?

File: JuliaLowering/src/macro_expansion.jl [hunk 2]
```diff
@@ -276,9 +276,16 @@ function expand_macro(ctx, ex)
...
     raw_args = ex[3:end]
-    macro_loc = let loc = source_location(LineNumberNode, ex)
+    macro_loc = if kind(ex[2]) === K"Value"
+        loc = ex[2].value
+        if loc isa LineNumberNode
         # Some macros, e.g. @cmd, don't play nicely with file == nothing
         isnothing(loc.file) ? LineNumberNode(loc.line, :none) : loc
+        elseif loc isa Core.MacroSource
+            loc.lno
+        end
```
Comment (topolarity) [inline JuliaLowering/src/macro_expansion.jl:288]:
```suggestion
        else
            LineNumberNode(0, :none)
        end
```
or an assertion failure, etc.

**Review by topolarity — APPROVED** [review]
This should make a big difference for the stdlib tests, thanks!
