### PR TITLE
Fix LU factorization in-place operations

### LINKED ISSUE #445: A_ldiv_B!(::LU, ::StridedVector) not updating input rhs
See https://github.com/JuliaLang/julia/blob/bf83397c1c7677ea8776ab792b761fcb3d0607ef/base/linalg/lu.jl#L248. When applying the permutations via `getindex`, a new vector is returned so the input vector is not updated with the solution. The fix is to apply the permutation in place.

Update: Should probably mention that this only happens for the generic fallback and not for BLAS element types.

### LINKED ISSUE #22683: A_ldiv_B!(::LU, ::StridedVector) not updating input rhs
See https://github.com/JuliaLang/julia/blob/bf83397c1c7677ea8776ab792b761fcb3d0607ef/base/linalg/lu.jl#L248. When applying the permutations via `getindex`, a new vector is returned so the input vector is not updated with the solution. The fix is to apply the permutation in place.

Update: Should probably mention that this only happens for the generic fallback and not for BLAS element types.

### PR DESCRIPTION
**Pull request by haampie**
Fixes JuliaLang/LinearAlgebra.jl#445.

### CODE REVIEW

File: base/linalg/lu.jl [hunk 1]
```diff
@@ -236,32 +236,50 @@ end
...
-    At_ldiv_B!(UnitLowerTriangular(A.factors),
-    At_ldiv_B!(UpperTriangular(A.factors), b))[invperm(ipiv2perm(A.ipiv, length(b)))]
-At_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, B::StridedMatrix) =
-    At_ldiv_B!(UnitLowerTriangular(A.factors),
-    At_ldiv_B!(UpperTriangular(A.factors), B))[invperm(ipiv2perm(A.ipiv, size(B,1))),:]
+
+function At_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, b::StridedVector)
+    At_ldiv_B!(UnitLowerTriangular(A.factors), At_ldiv_B!(UpperTriangular(A.factors), b))
+    b_permuted = b[invperm(ipiv2perm(A.ipiv, length(b)))]
+    copy!(b, b_permuted)
```
Comment (tkelman) [inline base/linalg/lu.jl]: couldn't this permute in place?

Comment (haampie) [inline base/linalg/lu.jl]: I was thinking the same, but `permute!` copies the permutation array, so a new allocation of roughly the same size is done anyway. Also the docs suggest using `b[perm]`. But if the array or number type is special, then `permute!` might be better.

**Comment by Sacha0** [comment]
Regarding three-argument `[i]permute!` methods, having run into the same lack last week I opened an issue: #22815. Best! (Wonderful meeting you last month Harmen! :) )

File: base/linalg/lu.jl [hunk 2]
```diff
@@ -236,32 +236,50 @@ end
...
+end
+
+function At_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, B::StridedMatrix)
+    At_ldiv_B!(UnitLowerTriangular(A.factors), At_ldiv_B!(UpperTriangular(A.factors), B))
+    B_permuted = B[invperm(ipiv2perm(A.ipiv, size(B,1))), :]
```
Comment (Sacha0) [inline base/linalg/lu.jl]: Perhaps space-separate the arguments to `size` as in the similar method above? :)

File: test/linalg/lu.jl [hunk 3]
```diff
@@ -83,10 +83,29 @@ debug && println("(Automatic) Square LU decomposition. eltya: $eltya, eltyb: $el
                 @test norm(a*(lua\c) - c, 1) < ε*κ*n # c is a vector
                 @test norm(a'*(lua'\c) - c, 1) < ε*κ*n # c is a vector
                 @test AbstractArray(lua) ≈ a
-                if eltya <: Real && eltyb <: Real
```
Comment (Sacha0) [inline test/linalg/lu.jl]: Were these eltype restrictions not necessary? :)

File: test/linalg/lu.jl [hunk 4]
```diff
@@ -83,10 +83,29 @@ debug && println("(Automatic) Square LU decomposition. eltya: $eltya, eltyb: $el
...
+
+                At_ldiv_B!(b_dest, lua, b)
+                At_ldiv_B!(c_dest, lua, c)
+                @test norm(b_dest - lua.' \ b, 1) < ε*κ*2n
+                @test norm(c_dest - lua.' \ c, 1) < ε*κ*n
+
+                Ac_ldiv_B!(b_dest, lua, b)
+                Ac_ldiv_B!(c_dest, lua, c)
+                @test norm(b_dest - lua' \ b, 1) < ε*κ*2n
+                @test norm(c_dest - lua' \ c, 1) < ε*κ*n
```
Comment (Sacha0) [inline test/linalg/lu.jl]: Perhaps DRY out these tests? For example, something along the lines of
```julia
for Aq_ldiv_B! in (A_ldiv_B!, At_ldiv_B!, Ac_ldiv_B!)
    Aq_ldiv_B!(b_dest, lua, b)
    Aq_ldiv_B!(c_dest, lua, c)
    @test norm(b_dest - lua \ b, 1) < ε*κ*2n
    @test norm(c_dest - lua \ c, 1) < ε*κ*n
end
```
might serve?

File: base/linalg/lu.jl [hunk 5]
```diff
@@ -236,32 +236,50 @@ end
...
+    b_permuted = b[ipiv2perm(A.ipiv, length(b))]
+    A_ldiv_B!(UpperTriangular(A.factors), A_ldiv_B!(UnitLowerTriangular(A.factors), b_permuted))
+    copy!(b, b_permuted)
+end
+
+function A_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, B::StridedMatrix)
+    B_permuted = B[ipiv2perm(A.ipiv, size(B, 1)), :]
+    A_ldiv_B!(UpperTriangular(A.factors), A_ldiv_B!(UnitLowerTriangular(A.factors), B_permuted))
+    copy!(B, B_permuted)
+end
```
Comment (Sacha0) [inline base/linalg/lu.jl]: Not necessary in this pull request, but DRYing out these and the similar method definitions below might be nice. For example, as a first step perhaps something along the lines of
```julia
function A_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, B::StridedVecOrMat)
    B_permuted = _ipivpermute(B, A.ipiv)
    A_ldiv_B!(UpperTriangular(A.factors), A_ldiv_B!(UnitLowerTriangular(A.factors), B_permuted))
    copy!(B, B_permuted)
end
_ipivpermute(b::StridedVector, ipiv) = b[ipiv2perm(ipiv, length(b))]
_ipivpermute(B::StridedMatrix, ipiv) = B[ipiv2perm(ipiv, size(B, 1)), :]
```
would do the trick? :)

**Comment by haampie** [comment]
Thanks @Sacha0! Nice meeting you as well. I'll condense it a bit :)

File: test/linalg/lu.jl (hunk 3 above)
Comment (haampie) [inline test/linalg/lu.jl]: `'` and `.'` are equivalent for real matrices but not for complex ones, and I think the idea has been to restrict the `.'` test to complex matrices. But then it should have read `<: Complex`. When fixing that I thought it wasn't really necessary to do that test conditionally; makes it easier to read what's happening.

File: base/linalg/lu.jl [hunk 6]
```diff
@@ -236,32 +236,50 @@ end
...
 A_ldiv_B!(A::LU{T,<:StridedMatrix}, B::StridedVecOrMat{T}) where {T<:BlasFloat} =
     @assertnonsingular LAPACK.getrs!('N', A.factors, A.ipiv, B) A.info
-A_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, b::StridedVector) =
-    A_ldiv_B!(UpperTriangular(A.factors),
-    A_ldiv_B!(UnitLowerTriangular(A.factors), b[ipiv2perm(A.ipiv, length(b))]))
-A_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, B::StridedMatrix) =
-    A_ldiv_B!(UpperTriangular(A.factors),
-    A_ldiv_B!(UnitLowerTriangular(A.factors), B[ipiv2perm(A.ipiv, size(B, 1)),:]))
+
+function A_ldiv_B!(A::LU{<:Any,<:StridedMatrix}, b::StridedVector)
```
Comment (andreasnoack) [inline base/linalg/lu.jl]: I think it is sufficient to do `A_ldiv_B!(UpperTriangular(A[:U]), A_ldiv_B!(LinAlg.UnitLowerTriangular(A[:L]), view(b, A[:p])))` here.

Comment (haampie) [inline base/linalg/lu.jl]: I have tried exactly this, but the problem is that the user works with `b` itself after calling `A_ldiv_B!(LU, b)`, and `b` has to be permuted. So whether you do the permutation during the backward & forward substitutions implicitly with a view doesn't really matter, the permutation has to be applied in the end anyway.

Comment (haampie) [inline base/linalg/lu.jl]: I didn't know about `A[:p]` btw, thanks

**Comment by haampie** [comment]
OK... We should have used the `ipiv` array (I didn't even consider it), since that provides a way to sequentially apply the permutation in-place:

```julia
function my_A_ldiv_B!(A::LU, b::StridedVector)
    for i = eachindex(A.ipiv)
        b[i], b[A.ipiv[i]] = b[A.ipiv[i]], b[i]
    end

    A_ldiv_B!(UpperTriangular(A.factors), A_ldiv_B!(UnitLowerTriangular(A.factors), b))
end
```

**Review by andreasnoack — APPROVED** [review]

File: test/linalg/lu.jl (hunk 4 above)
Comment (haampie) [inline test/linalg/lu.jl]: I've tried it, but it doesn't seem to work :(

```
> transpose(lufact(rand(3, 3))) \ rand(3)
ERROR: transpose not implemented for Base.LinAlg.LU{Float64,Array{Float64,2}}
```

Comment (fredrikekre) [inline test/linalg/lu.jl]: It is because `A.' \ B` becomes `At_ldiv_B(A, B)` (not `transpose(A) \ B`). Perhaps this will do?
```julia
for (Aq_ldiv_B!, f) in (
        (A_ldiv_B!, \),
        (At_ldiv_B!, At_ldiv_B),
        (Ac_ldiv_B!, Ac_ldiv_B) )
    Aq_ldiv_B!(b_dest, lua, b)
    Aq_ldiv_B!(c_dest, lua, c)
    @test norm(b_dest - f(lua, b), 1) < ε*κ*2n
    @test norm(c_dest - f(lua, c), 1) < ε*κ*n
end
```

Comment (haampie) [inline test/linalg/lu.jl]: Thx, so is `.' \` parsed as a single operator or something?

Comment (fredrikekre) [inline test/linalg/lu.jl]: Yes,
```julia
julia> expand(Main, :(A'\B))
:(Ac_ldiv_B(A, B))
```
and similarly for `*` as well.

Comment (StefanKarpinski) [inline test/linalg/lu.jl]: This is definitely kind of a hack and we want to [get rid of it](https://github.com/JuliaLang/julia/issues/5332), but we're not quite there yet.
