### PR TITLE
inference: fix vararg normalization in rewrap

### LINKED ISSUE #39082: Internal error: encountered unexpected error in runtime: TypeError...
Our packages [AbstractAlgebra](https://github.com/Nemocas/AbstractAlgebra.jl), [Hecke](https://github.com/thofma/Hecke.jl), etc. started failing on master. I could reduce the error to the following MWE:

```julia
julia> struct Q end

julia> Base.typed_hvcat(a::Q, b, c...) = hvcat(b, c...)

julia> Q()[1//1 0; 0 1//1]
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type, got=T<:(Base.Rational{T} where T<:Integer))
[...]
```
(full backtrace: https://gist.github.com/thofma/23a37bd230758994871b42686de507ca)

```julia
julia> versioninfo()
Julia Version 1.7.0-DEV.205
Commit 5ee2d601ed* (2021-01-01 10:48 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, ivybridge)
```

This is working fine on 1.5.1 and on the release1.6 branch, so this is a regression on the master branch.

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #39082

### CODE REVIEW

File: base/compiler/typelattice.jl [hunk 1]
```diff
@@ -122,6 +122,8 @@ function ⊑(@nospecialize(a), @nospecialize(b))
     (a === Any || b === NOT_FOUND) && return false
     a === Union{} && return true
     b === Union{} && return false
+    @assert !isa(a, TypeVar) || a
+    @assert !isa(b, TypeVar) || b
```
Comment (aviatesk) [inline base/compiler/typelattice.jl:126]: we use this pattern to print the exact bad `TypeVar` ?

Comment (vtjnash) [reply base/compiler/typelattice.jl:126]: With `@test` that works pretty well. But I'm going to remove this, since here it just throws `TypeError: non-boolean (TypeVar) used in boolean context`, which isn't helpful.

File: base/compiler/typelattice.jl [hunk 2]
```diff
@@ -122,6 +122,8 @@ function ⊑(@nospecialize(a), @nospecialize(b))
     (a === Any || b === NOT_FOUND) && return false
     a === Union{} && return true
     b === Union{} && return false
+    @assert !isa(a, TypeVar) "invalid lattice item"
```
Comment (Keno) [inline base/compiler/typelattice.jl:125]: This function is somewhat hot. Move this check all the way down to the `===` check?

File: base/compiler/typeutils.jl [hunk 3]
```diff
@@ -5,7 +5,7 @@
 #####################
 
 function rewrap(@nospecialize(t), @nospecialize(u))
-    if isa(t, TypeVar) || isa(t, Type)
+    if isa(t, TypeVar) || isa(t, Type) || isa(t, Core.TypeofVararg)
```
Comment (Keno) [inline base/compiler/typeutils.jl:8]: I did add a specialization of `rewrap_unionall` that handles this case (since anything else would be breaking), but I'm not all that convinced that `rewrap_unionall` should actually work on Vararg. In many cases it's the wrong thing to do. Maybe just make the `Vararg` case explicit here, since this is an internal function? Alternatively, I think there's only one or two callsites of this that allow a Vararg, so maybe they should use a different entrypoint.

Comment (vtjnash) [reply base/compiler/typeutils.jl:8]: I think the || already makes it pretty explicit. We can consider other designs later as continued clean up, but this seems to fix CI regression for now.

File: base/compiler/typelattice.jl (hunk 2 above)
Comment (vtjnash) [reply base/compiler/typelattice.jl:125]: I don't think a pointer comparison will affect this, relative to the many other egal and subtyping test it does

File: base/compiler/typeutils.jl (hunk 3 above)
Comment (Keno) [reply base/compiler/typeutils.jl:8]: alright
