### PR TITLE
Fix `IOBuffer` `skip` regression

### LINKED ISSUE #57962: `IOBuffer` `skip` regression
https://github.com/JuliaLang/julia/pull/57570 broke `skip` for `IOBuffer`. This is causing TranscodingStreams.jl tests to fail on nightly.

MWE:

```julia
iob = IOBuffer(repeat("x", 400))
skip(iob, 10)
skip(iob, 400)
read(iob)
```

This throws:

```
ERROR: InexactError: convert(UInt64, -10)
Stacktrace:
  [1] throw_inexacterror(func::Symbol, to::Type, val::Int64)
    @ Core ./boot.jl:815
  [2] check_sign_bit
    @ ./boot.jl:821 [inlined]
  [3] toUInt64
    @ ./boot.jl:932 [inlined]
  [4] UInt64
    @ ./boot.jl:962 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] _string_n
    @ ./strings/string.jl:109 [inlined]
  [7] StringMemory
    @ ./iobuffer.jl:167 [inlined]
  [8] StringVector
    @ ./iobuffer.jl:168 [inlined]
  [9] read(io::IOBuffer)
    @ Base ./iobuffer.jl:894
 [10] top-level scope
    @ REPL[22]:1
```

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #57962

This reverts the changes to `skip` added in #57570

The code before #57570 was written in a very specific way to avoid overflow errors, so I'm not sure why this was changed.

### CODE REVIEW

**Review by jakobnissen — APPROVED** [review]
No idea why I changed this. Thanks for fixing this.

**Comment by nhz2** [comment]
Yeah, the code is a bit convoluted here. I should try to port over the cleaner version I have in https://github.com/JuliaIO/InputBuffers.jl/blob/6a6571ce349e2798f326e7e401cab2922d7e421f/src/InputBuffers.jl#L66-L69

File: test/iobuffer.jl [hunk 1]
```diff
@@ -497,6 +497,13 @@ end
     end
 end
 
+@testset "issue #57962" begin
+    io = IOBuffer(repeat("x", 400))
+    skip(io, 10)
+    skip(io, 400)
+    @test position(io) == 400
```
Comment (vtjnash) [inline test/iobuffer.jl:504]: Note that this result is a bug also (correct answer is 410), and any package relying on this is going to have a bad time

**Review by vtjnash — APPROVED** [review]

File: test/iobuffer.jl (hunk 1 above)
Comment (nhz2) [reply test/iobuffer.jl:504]: TranscodingStreams.jl has it's own more specific definition of `skip` so doesn't rely on this.
https://github.com/JuliaIO/TranscodingStreams.jl/blob/ea4533afaf175443198f5d98009266b6b5f2d882/src/stream.jl#L355-L362

Comment (nhz2) [reply test/iobuffer.jl]: I changed this test to instead check `isempty(read(io))` after skipping past the end. This seems consistent with how `IOStream` currently works as well. Though currently https://github.com/JuliaLang/julia/pull/58024 says this should throw some kind of error.

**Comment by nsajko** [comment]
As far as I see CI failed to run. Please rebase and force push to force CI to run again.
