### PR TITLE
output the system image as static data

### LINKED ISSUE #19199: SIGSEGV on arm (Raspberry Pi 3)
master branch at 10ffbae.  My last successful build was at b7f1aa7.
```
raspberrypi% gdb usr/bin/julia
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from usr/bin/julia...done.
(gdb) run
Starting program: /home/sachs/src/julia-master/usr/bin/julia
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x753e2760 (LWP 15617)]

Program received signal SIGSEGV, Segmentation fault.
jl_deserialize_value (s=<optimized out>, loc=<optimized out>)
    at /home/sachs/src/julia-master/src/dump.c:1401
1401            return jl_array_ptr_ref(s->tree_literal_values, read_uint16(s->s));
(gdb) Quit
```

### LINKED ISSUE #22320: embedding crash (?) on Windows
The following python code, run in the `bin/` install directory, exits on both win32 and win64 in 0.6-rc3. (works ok in 0.5.2 when jl_init signature is adjusted accordingly)

```
from cffi import FFI
ffi = FFI()
ffi.cdef("void jl_init();")
c = ffi.dlopen("libjulia.dll")
c.jl_init()
```

I looked at a backtrace in windbg on win32 and saw a stackoverflow (`jl_array_to_string` I think), but the vm timed out.

ref: https://discourse.julialang.org/t/interfacing-julia-red-error-with-julia-0-6-rc3/4180

### PR DESCRIPTION
**Pull request by vtjnash**
This replaces the current lisp-y system image compression with an static image format. This is more similar to how it would be handled in a static compiler.

benefits:
 - faster gc (fewer live objects)
 - smaller memory footprint (static mmap image allows OS to share pages and delay loading some)
 - uses less stack space (and doesn't require the various heuristic hacks that we have in dump.c to keep stack size in check)
 - simpler format (I think this'll make it easier to extend)
 - faster startup (less work to do)
 - expected to be easier to track how various optimizations affect memory usage (since on-disk size equals in-memory size)

fixes https://github.com/JuliaLang/julia/issues/19199
fixes https://github.com/JuliaLang/julia/issues/22320

### CODE REVIEW

File: src/staticdata.c [hunk 1]
```diff
@@ -0,0 +1,1635 @@
...
+// list of modules being deserialized with __init__ methods
+// (not used in MODE_AST)
+jl_array_t *jl_module_init_order;
+
+// hash of definitions for predefined function pointers
+static htable_t fptr_to_id;
+// array of definitions for the predefined function pointers
+// (reverse of fptr_to_id)
+static const jl_fptr_t id_to_fptrs[] = {
+  NULL, NULL,
```
Comment (ararslan) [inline src/staticdata.c]: Should be 4 space indents (plus closing `}` on its own line)

**Comment by JeffBezanson** [comment]
Cool! You can probably guess what I'm going to ask but here goes: any data on sysimg size and startup time?

File: src/gc.c [hunk 2]
```diff
@@ -1953,15 +2005,20 @@ mark: {
...
         meta_updated = 0;
         // Symbols are always marked
         assert(vt != jl_symbol_type);
         if (vt == jl_simplevector_type) {
             size_t l = jl_svec_len(new_obj);
             jl_value_t **data = jl_svec_data(new_obj);
-            if (update_meta)
-                gc_setmark(ptls, o, bits, l * sizeof(void*) + sizeof(jl_svec_t));
+            if (update_meta) {
+                if (foreign_alloc)
```
Comment (yuyichao) [inline src/gc.c]: Since `objprofile_count` is a non-default debug option, I think it'll be better to make `update_meta = 0` in this case and do this in an else branch so that it's more clear to the compiler that the two branches can be merged together. It also seems like it's exactly the same code so maybe just do at the very beginning

```c
if (update_meta) {
    if (((void*)o >= sysimg_base && (void*)o < sysimg_end)) {
        update_meta = 0;
        objprofile_count(vt, bits == GC_OLD_MARKED, jl_datasize_size(vt));
    }
}
```

Comment (vtjnash) [inline src/gc.c]: That's a copy-paste error (weren't supposed to be the same). Sadly, I had implemented this the other way first (as you suggested), then forgot what what I was doing, and changed them all back to this version

**Comment by vtjnash** [comment]
```
$ time ./julia-80369bf7b4/bin/julia -e 0
real	0m0.433s
user	0m0.420s
sys	0m0.476s

$ time ./julia -e 0
real	0m0.333s
user	0m0.320s
sys	0m0.648s
```
```
$ time ./julia-80369bf7b4/bin/julia -e 'for i = 1:10; @time gc(false); end'
  0.133410 seconds, 99.95% gc time
  0.129873 seconds, 99.99% gc time
  0.127389 seconds, 99.99% gc time
  0.103277 seconds, 99.99% gc time
  0.000170 seconds, 98.40% gc time
  0.000152 seconds, 98.71% gc time
  0.000152 seconds, 98.76% gc time
  0.000151 seconds, 98.75% gc time
  0.000152 seconds, 98.76% gc time
  0.000152 seconds, 98.72% gc time
real	0m1.510s
user	0m1.616s
sys	0m1.500s

$ time ./julia -e 'for i = 1:10; @time gc(false); end'
  0.004610 seconds, 99.40% gc time
  0.002450 seconds, 99.89% gc time
  0.001323 seconds, 99.81% gc time
  0.000376 seconds, 99.35% gc time
  0.000110 seconds, 98.10% gc time
  0.000110 seconds, 98.03% gc time
  0.000109 seconds, 98.07% gc time
  0.000109 seconds, 98.15% gc time
  0.000109 seconds, 98.01% gc time
  0.000109 seconds, 98.07% gc time

real	0m0.930s
user	0m1.144s
sys	0m1.788s
```
```
$ time ./julia-80369bf7b4/bin/julia -e 'for i = 1:10; @time gc(); end'
  0.091677 seconds, 99.94% gc time
  0.093045 seconds, 99.99% gc time
  0.166092 seconds, 99.99% gc time
  0.090291 seconds, 99.99% gc time
  0.090208 seconds, 99.99% gc time
  0.090224 seconds, 99.99% gc time
  0.090873 seconds, 99.99% gc time
  0.090771 seconds, 99.99% gc time
  0.090349 seconds, 99.99% gc time
  0.090110 seconds, 99.99% gc time
real	0m1.991s
user	0m2.212s
sys	0m1.788s

$ time ./julia -e 'for i = 1:10; @time gc(); end'
  0.004310 seconds, 99.42% gc time
  0.002271 seconds, 99.89% gc time
  0.071036 seconds, 99.99% gc time
  0.069055 seconds, 99.99% gc time
  0.068984 seconds, 99.99% gc time
  0.069206 seconds, 99.99% gc time
  0.069419 seconds, 99.99% gc time
  0.069340 seconds, 99.99% gc time
  0.069038 seconds, 99.99% gc time
  0.069223 seconds, 99.99% gc time
real	0m1.478s
user	0m1.548s
sys	0m1.516s
```

RSS 148M from ```./julia-80369bf7b4/bin/julia -e 'run(`htop`)'```
RSS 126M from ```./julia -e 'run(`htop`)'```

size -A usr/lib/julia/sys.o
.data             73132035      0

sysimg size breakdown:
```
     sys data: 45716212 # random mutable data
  isbits data: 15671784 # mostly AST data
      symbols:   249675
    tags list:  2345872 # this can be compressed much better
   reloc list:  8834488 # this can be compressed much better
    gvar list:    79592 # 19898 pointers inserted into our generated code
    fptr list:   215464 # approximately 13500 methods compiled
```

$ ls -lh usr/lib/julia/
total 367M
-rw-rw-r-- 1 vtjnash vtjnash 6.8M Jun  6 18:23 inference.ji
-rw-rw-r-- 1 vtjnash vtjnash 100M Jun  6 18:27 sys-debug.o
-rwxrwxr-x 1 vtjnash vtjnash  88M Jun  6 18:28 sys-debug.so
-rw-rw-r-- 1 vtjnash vtjnash  91M Jun  6 18:27 sys.o
-rwxrwxr-x 1 vtjnash vtjnash  83M Jun  6 18:27 sys.so

File: src/staticdata.c [hunk 3]
```diff
@@ -255,8 +258,9 @@ static void jl_serialize_value_(jl_serializer_state *s, jl_value_t *v)
         return;
     }
 
-    size_t item = backref_table_numel++;
-    char *pos = (char*)HT_NOTFOUND + 1 + item;
+    size_t item = ++backref_table_numel;
+    assert(item < (1 << 28) && "too many items to serialize");
```
Comment (tkelman) [inline src/staticdata.c]: 28 appears often here but its significance isn't obvious, give it a name

**Comment by JeffBezanson** [comment]
Nice. Sysimg is larger as one would expect, but seems to be totally worth it.

File: src/staticdata.c [hunk 4]
```diff
@@ -0,0 +1,1683 @@
...
+        jl_register_fptrs(sysimage_base, fvars, linfos, sysimg_fvars_max);
+    }
+}
+
+
+
+static void jl_update_all_gvars(jl_serializer_state *s)
+{
+    if (sysimg_gvars == NULL)
+       return;
```
Comment (tkelman) [inline src/staticdata.c]: one too few spaces

File: src/staticdata.c [hunk 5]
```diff
@@ -0,0 +1,1683 @@
...
+}
+
+
+static inline uint32_t load_uint32_be(uintptr_t *base)
+{
+    uint32_t b3 = *(uint8_t*)(*base)++;
+    uint32_t b2 = *(uint8_t*)(*base)++;
+    uint32_t b1 = *(uint8_t*)(*base)++;
+    uint32_t b0 = *(uint8_t*)(*base)++;
+    return b0 | (b1 << 8) | (b2 << 16) | (b3 << 24);
```
Comment (yuyichao) [inline src/staticdata.c]:
```c
    uint32_t v;
    memcpy(&v, base, 4);
    return ntohl(v);
```
Is much easier for the compiler to optimize.

File: src/gc.c [hunk 6]
```diff
@@ -644,6 +644,37 @@ void gc_setmark_buf(jl_ptls_t ptls, void *o, uint8_t mark_mode, size_t minsz)
     gc_setmark_buf_(ptls, o, mark_mode, minsz);
 }
 
+void jl_gc_force_mark_old(jl_ptls_t ptls, jl_value_t *v)
```
Comment (yuyichao) [inline src/gc.c]: This (and `gc_sweep_sysimg` etc below) should go into a header. It happens way too often when we put declaration in C files and they get out of sync when the implementation is updated.

**Comment by vtjnash** [comment]
just for fun: @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22254#issuecomment-310733709) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/525c30f18795bf3447fd68ad9d888fe10aadd1c1/3b3ef6f_vs_5176ded/report.md). cc @jrevels

**Comment by ihnorton** [comment]
Backport? @vtjnash said that would be the simplest fix for stack size issues in 0.6...

**Comment by tkelman** [comment]
This is a pretty large change. What about the stack size compiler flag?

**Comment by ihnorton** [comment]
That should work for embedders, more-or-less, but it's probably unreasonable to ask Python to recompile. That said, I have no idea how many people use pyjulia.
