### PR TITLE
Fix incorrect results from floating-point division (fld, cld, div)

### LINKED ISSUE #49450: Incorrect results from floating-point division (`fld`, `cld`, `div`)
Julia has a [`div`](https://docs.julialang.org/en/v1/base/math/#Base.div) function that is used to implement [floor division](https://docs.julialang.org/en/v1/base/math/#Base.fld) (`fld`) and [ceil division](https://docs.julialang.org/en/v1/base/math/#Base.cld) (`cld`). I think I’ve found a bug that causes all of these division functions to return incorrect results.

Floor division is documented to return the largest integer less than or equal to `x / y`. It should never return a number that is *greater* than `x / y`.

But it does:

```julia
julia> 514 / Float16(0.75)
Float16(685.5)

julia> div(514, Float16(0.75)) # should round down, but rounds up instead
Float16(686.0)

julia> fld(514, Float16(0.75)) # likewise
Float16(686.0)

julia> fld(514, Float16(0.75)) ≤ 514 / Float16(0.75)
false
```

Similarly, ceil division should never return a number that is *smaller* than regular division, but it does:

```julia
julia> 515 / Float16(0.75)
Float16(686.5)

julia> cld(515, Float16(0.75)) # should round up, but rounds down instead
Float16(686.0)

julia> cld(515, Float16(0.75)) ≥ 515 / Float16(0.75)
false
```

This behavior is not limited to 16-bit floats. Here’s a case where `fld` produces an incorrect result for `Float32` inputs:

```julia
julia> 4_194_307 / Float32(0.75) # = 5592409.5
5.5924095f6

julia> fld(4_194_307, Float32(0.75)) # = 5592410, incorrectly rounded up
5.59241f6

julia> fld(4_194_307, Float32(0.75)) ≤ 4_194_307 / Float32(0.75)
false
```

And here’s the same for `cld`:

```julia
julia> 4_194_308 / Float32(0.75) # = 5592410.5

julia> cld(4_194_308, Float32(0.75)) # = 5592410, incorrectly rounded down
5.59241f6

julia> cld(4_194_308, Float32(0.75)) ≥ 4_194_308 / Float32(0.75)
false
```

The equivalent operations in Python produce the correct results:

```python
# For 16-bit floats:
>>> np.float16(514) / np.float16(0.75) # regular division
685.5
>>> np.float16(514) // np.float16(0.75) # floor division
685.0

# For 32-bit floats:
>>> np.float32(4_194_307) / np.float32(0.75) # regular division
5592409.5
>>> np.float32(4_194_307) // np.float32(0.75) # floor division
5592409.0
```

Examples of this incorrect behavior are not hard to find – for most floats, you can find a divisor that will make either `fld` or `cld` return the wrong answer.

Here are some examples for `Float16` where either `fld` or `cld` is incorrect:

- `cld(1, Float16(0.000999)) < 1 / Float16(0.000999)`
- `cld(2, Float16(0.001999)) < 2 / Float16(0.001999)`
- `cld(3, Float16(0.002934)) < 3 / Float16(0.002934)`
- `cld(4, Float16(0.003998)) < 4 / Float16(0.003998)`
- `fld(5, Float16(0.004925)) > 5 / Float16(0.004925)`

And here are some for `Float32`:

- `fld(5, Float32(6.556511e-7)) > 5 / Float32(6.556511e-7)`
- `fld(10, Float32(1.3113022e-6)) > 10 / Float32(1.3113022e-6)`
- `fld(11, Float32(1.4305115e-6)) > 11 / Float32(1.4305115e-6)`
- `cld(16, Float32(2.8014183e-6)) < 16 / Float32(2.8014183e-6)`
- `cld(17, Float32(2.2053719e-6)) < 17 / Float32(2.2053719e-6)`

For simplicity I’ve presented examples where the first argument is an integer; this bug also occurs for non-integral inputs.

A divisor producing the wrong result can be found for over 51% of all possible 16-bit floats. I have not evaluated how widespread this is for `Float32`, but the results above suggest that it is similarly easy to find failures there too.

I’ve tracked the invocations down to [this definition](https://github.com/JuliaLang/julia/blob/72aec423c2ab9f80c249d63fdd68b35833cfd7ed/base/div.jl#L370) of `div`, which has existed at least as far back as [Julia 1.6](https://github.com/JuliaLang/julia/blob/f9720dc2ebd6cd9e3086365f281e62506444ef37/base/div.jl#L279):

```julia
div(x::T, y::T, r::RoundingMode) where {T<:AbstractFloat} =
	convert(T, round((x - rem(x, y, r)) / y))
```

### PR DESCRIPTION
**Pull request by lvlte**
This fixes #49450 (more details in [this comment](https://github.com/JuliaLang/julia/issues/49450#issuecomment-3694946121)).

### CODE REVIEW

**Comment by adienes** [comment]
unfortunately does not solve the whole issue

```
julia> x = 1.125899906841625e15
1.125899906841625e15

julia> y = 0.1
0.1

julia> div(x, y, RoundDown)
1.125899906841625e16

julia> div(big(x), big(y), r)
1.1258999068416249e16
```

**Comment by lvlte** [comment]
@adienes @Seelengrab Float64 cannot represent the value 1.1258999068416249e16. 

```julia
julia> x, y = 1.125899906841625e15, 0.1
(1.125899906841625e15, 0.1)

julia> prevfloat(x/y), x/y, nextfloat(x/y)
(1.1258999068416248e16, 1.125899906841625e16, 1.1258999068416252e16)
```

As already mentioned in the issue :

> If eps(x/y) > 1, x/y rounds to an unsafe integer which can't be floored/ceiled if it needs to because x/y ± 1 is not representable (except for 2^53 - 1).

**Comment by adienes** [comment]
`Float64` can represent `1.1258999068416248e16` though, which would be the correct result under `RoundDown`

**Comment by lvlte** [comment]
> `Float64` can represent `1.1258999068416248e16` though, which would be the correct result under `RoundDown`

Could you at least explain why do you think it should be the correct result ?

`fld` is defined as the "_Largest integer less than or equal to `x / y`_", and `1.1258999068416248e16` is not the largest integer less than or equal to `x / y` because the remainder is not significant :

```julia
julia> 1.125899906841625e15 / 0.1
1.125899906841625e16

julia> (1.125899906841625e15 - 1.125899906841625e15 % 0.1) / 0.1
1.125899906841625e16

julia> 1.125899906841625e15 / 0.1 - (1.125899906841625e15 % 0.1) / 0.1
1.125899906841625e16
```

Getting `1.1258999068416248e16` would implies the remainder is significantly greater than it really is. 

Also, `1.1258999068416248e16` is off by one just as `1.125899906841625e16`, but the latter is closer to the exact result of x divided by y, and rounding in that direction is consistent with the behavior of floating-point rounding when there is a tie, which is to round to the nearest integer.

**Comment by adienes** [comment]
so your concern is that since the condition is impossible (since the largest integer not exceeding `x/y` is not in fact representable in the return type), we should be allowed to violate the rounding conditions?

I don't mean that question as sophistry; it is a fair argument and one that has appeared a few times to attempt to justify behavior of accidental integer overflow e.g. in https://github.com/JuliaLang/julia/issues/34325, also discussed in https://github.com/JuliaLang/julia/issues/50486 . but I think due to the high performance needs of functions like `div` and `fld` we won't reach the same conclusions as in those issues.

there are basically three paths forward as I see it:

* when the conditions in the docstring cannot be satisfied, throw a `DomainError`. this is the approach taken by, for example, `gcd` and `lcm`
* promote to a type with higher precision that can represent the correct value
* amend the docstring to make a promise it can actually keep, and then amend the implementation to match that new specification

unfortunately the first two paths would be disastrous for performance and type-stability and are non-starters, so by process of elimination that leaves only the third. I would suggest an amendment to the docstring --- and, I believe, this is what most discussion participants in https://github.com/JuliaLang/julia/issues/49450 were implicitly assuming already --- to something like

> return the largest integer *representable in T* less than or equal to `x / y` 

and under this definition, a type-stable and fast `/(::Float64, ::Float64)` is at least possible, although it is not the current implementation

**Comment by lvlte** [comment]
You are missing the point : the floating-point division `x/y` returns an integer and its remainder, even normalized, is not significant enough compared to the result, so for consistency the fld and cld for the same type should give the same result. Using more precision should remain at the discretion of the user when using these functions. I don't think we should tweak every operation result considering the same operation with types allowing more precision. This would be like trying to fix all cases where `x - x % y` equals `x` in Float64 with `x ± eps(x)` because the results are different with BigFloat, a completely arbitrary choice which is not requested by the user and that could break consistency between operations. 

I'm not comfortable with the idea that `abs(cld(x, y) - fld(x, y))` equals 2 (in this example) as it would imply for all cases where `eps(x/y) > 1` that the absolute difference should be equal to `eps(x/y)`, which would make the results dependent on the magnitude of x/y, instead of having a consistent value that is either 0 or 1.

> return the largest integer _representable in T_ less than or equal to `x / y`. 

1.125899906841625e16 still satisfies the premise. 

Also, the current implementation gives the same results for those case where `eps(x/y) > 1`. This PR solves the issue for all other cases where cld, fld, div, give an inexact result and where the exact result is representable. 

You didn't explain why 1.1258999068416248e16 should be preferred, and what is violating the rounding conditions.

**Comment by adienes** [comment]
here's what I'm looking at:
```
julia> x, y
(1.125899906841625e15, 0.1)

julia> big(x) / big(y)
1.125899906841624937500000000055459109526978519729750209567102918209446384572968e16
```

so to my eyes the "correct" integer would be `11258999068416249` . but this is not representable in `Float64`. the reason I suggest to round downwards to `11258999068416248` rather than upwards to `11258999068416250`  is that is usually what I would assume flooring division (aka `RoundDown`) does



as a side note: 
> You are missing the point ... You didn't explain

I would invite you to use phrasing that more clearly reaffirms that we are collaborating together to solve the bug, rather than that we are arguing 🙂

**Comment by lvlte** [comment]
> so your concern is that [since ...] we should be allowed to violate the rounding conditions?

doesn't sound like "we are collaborating together to solve the bug" but rather like "we are arguing" about the legitimacy of a PR that doesn't improve anything or even asks to break things because my concern is. Again, the implementation I propose fixes cld, fld, div, giving an inexact result where the exact result is representable, and for those edge cases where `eps(x/y) > 1`, it doesn't imply being allowed to violate anything but just matches the current implementation, which i think is correct and I explained why.

**Comment by adienes** [comment]
well I can appreciate the fervent defense and I do apologize for having given off the wrong impression during review.

this might be a fun one to discuss on triage, so I'll tag for review on the next meeting

**Comment by Seelengrab** [comment]
FWIW, the other partial fix in https://github.com/JuliaLang/julia/pull/49637 for Float16 & Float32 as far as I can tell makes the same decision that @adienes mentions, in particular see https://github.com/JuliaLang/julia/pull/49637#issuecomment-1536503712

So it would be good to be consistent and have Float64 behave the same.

**Comment by lvlte** [comment]
The comment you mention doesn't involve x,y such that `eps(x/y) > 1`, but yes it reminds us that having `x/y` rounded to an integer doesn't mean the mathematical result is an integer. To better illustrate my point, i would like to insist on the consistency between the quotient and remainder, and between the operations that involve them : 

Example 1 `eps(x/y) ≤ 1` (no disagreement, this PR just fixes inexact results) :
```julia
julia> x, y = 1.0, 0.1
(1.0, 0.1)

julia> a, r = divrem(x, y, RoundDown)    # accurate
(9.0, 0.09999999999999995)

julia> a + r/y == x/y, a + r/y, x/y      # accurate, consistent
(true, 10.0, 10.0)
```

Example 2 `eps(x/y) > 1` (current behavior, which this PR currently doesn't affect) : 
```julia
julia> x, y = 1.125899906841625e15, 0.1
(1.125899906841625e15, 0.1)

julia> a, r = divrem(x, y, RoundDown)    # inaccurate (intrinsic roundoff)
(1.125899906841625e16, 0.03750000000005546)

julia> a + r/y == x/y, a + r/y, x/y      # inaccurate (intrinsic roundoff), consistent
(true, 1.125899906841625e16, 1.125899906841625e16)
```

Now from example 2, let say because the remainder is not zero we force `a` to be rounded further down to the previous representable integer :
```julia
julia> a = 1.1258999068416248e16         # inaccurate (arbitrary roundoff)
1.1258999068416248e16

julia> a + r/y == x/y, a + r/y, x/y      # inaccurate (arbitrary roundoff), inconsistent
(false, 1.1258999068416248e16, 1.125899906841625e16)
```

**Comment by lvlte** [comment]
Regarding the behavior of `div` with Float16/Float32, I don't think the partial fix actually makes the decision of forcing rounding further down/up in those situations where `eps(x/y) > 1` and where the remainder is not significant. I mean, currently `div()` might behave like that with the partial fix in certain cases, but not in others (which is problematic, I'm just discovering this), eg. if we compute fld as `Float32(round(Float64(x) / Float64(y), RoundDown))` step by step, we get :
```julia
julia> x, y = 2.096153f6, 0.1f0
(2.096153f6, 0.1f0)

julia> round(Float64(x) / Float64(y), RoundDown)
2.0961529e7

julia> Float32(2.0961529e7)    # rounded down
2.0961528f7
```
```julia
julia> x, y = nextfloat(x), y + 2*eps(y)
(2.0961531f6, 0.10000002f0)

julia> round(Float64(x) / Float64(y), RoundDown)
2.0961527e7

julia> Float32(2.0961527e7)    # rounded up
2.0961528f7
```

The rounding for non-representable numbers is done by `Float32()` here and it can go both ways if not set explicitly. 

If the decision was made to round down/up further for non representable numbers, we should have a partial fix that makes the "final" rounding explicit : 
```julia
div(x::Float32, y::Float32, r::RoundingMode) = Float32(round(Float64(x) / Float64(y), r), r)
div(x::Float16, y::Float16, r::RoundingMode) = Float16(round(Float32(x) / Float32(y), r), r)
```

Not only is this not the case, but the comment that comes with that fix tells us cases where `eps(x/y) > 1` are not addressed :
```julia
# Vincent Lefèvre: "The Euclidean Division Implemented with a Floating-Point Division and a Floor"
# https://inria.hal.science/inria-00070403
# Theorem 1 implies that the following are exact if eps(x/y) <= 1
div(x::Float32, y::Float32, r::RoundingMode) = Float32(round(Float64(x) / Float64(y), r))
```

Also, #49450 was closed as completed after the Float16/Float32 fix, and reopened shortly after only to address inexact results with Float64 and mixed types involving Float64, not to address those cases where `eps(x/y) > 1` with Float16/Float32. So I'm wondering (even more) why the concern of solving unsolvable cases suddenly become a necessity in the meantime, without anybody mentioning it in the issue, or even just asking (given the comment above) "what about those cases where eps(x/y) > 1" ?

Now, if we were to leave those edge cases aside for Float64 as they are for Float16/Float32, the new fix proposed here should work seamlessly for all of them (I mean without the partial fix, but I haven't tested). In the other case, `if eps(x/y) > 1 ...` can still be done once in the generic `div()` definition.

**Comment by adienes** [comment]
as a note for triage: it does not seem like there is a whole ton of precedent to draw from. but I guess there is one in Common Lisp:

```
(format t "~a~%" (ffloor 1.125899906841625d15 0.1d0)) ;; 1.125899906841625d16
```

so they currently do the same thing Julia does here (and round upwards < eps, rather than downwards > eps)

**Comment by lvlte** [comment]
I did more tests to ensure the generic fix works for all float types (without the partial fix for Float16/Float32), it does so I removed the partial fix. 

Now for the cases where `eps(x/y) > 1`, there are a few options :
- keep the current behavior, just add a warning in the documentation, the caller can still double check the result using 
`a, r, = divrem(x,y); if abs(a) ≥ maxintfloat(a) && r != 0 do_something() end` 
- throw a DomainError or InexactError (could be a breaking change)
- force rounding further down/up (could be a breaking change)
- promote to a higher precision type (possible performance hit)
- use an extra argument to let the caller decide among the options above
- add a type argument so that the caller can decide to use more (or less) precision (promote accordingly and keep the current behavior)

The last two options seems the more reasonable to me as we can set the arg default to match the current behavior, but it would require more work (it might be preferable to create a separate issue).

**Comment by oscardssmith** [comment]
I'm slightly biased since I don't think these functions should exist at all, but to me, the current behavior seems least breaking and is arguably correct, so I would go with that. I do think we should run this by triage to confirm though.

**Comment by oscardssmith** [comment]
Triage approves of the semantics as implimented, but would prefer a warning in the docs about the subtitles of the behavior.

**Comment by nsajko** [comment]
> of the semantics as implemented

Just to clarify; this is as implemented on `master`, or as implemented on the PR branch?

**Comment by adienes** [comment]
as implemented in PR, with the main point tipping the scales being that if you compute in higher precision and cast back down, what you get would be `==` to the result here

File: test/numbers.jl [hunk 1]
```diff
@@ -4,6 +4,8 @@ using Base.MathConstants
 using Random
 using LinearAlgebra
 
+using Test
+
```
Comment (nsajko) [inline test/numbers.jl:7]: Avoid unrelated change?

```suggestion
```

File: CLAUDE.md
Comment (nsajko) [inline CLAUDE.md:1]: This also seems to be an unrelated change?

File: base/div.jl [hunk 2]
```diff
@@ -43,21 +43,27 @@ julia> div(4, 3, RoundFromZero)
...
-the number 6 precisely. Therefore the true value of `6.0 / 0.1` is slightly less
-than 60. When doing division, this is rounded to precisely `60.0`, but
-`div(6.0, 0.1, RoundToZero)` always truncates the true value, so the result is `59.0`.
+!!! note "Floating-point numbers"
+    Accurate results for floating-point arguments are only guaranteed when the
+    true value of `x / y` is within the range of exactly representable integers
+    for the given floating-point type, that is, when `eps(x/y) ≤ 1`, or in other
+    words, given `a = div(x, y)`, when `abs(a) < maxintfloat(a)`.
+
+    Because `div(x, y)` implements strictly correct truncated rounding based on the true
```
Comment (adienes) [inline base/div.jl]: I know this is wording taken from the original docstring, but, if possible, I think we could find a more descriptive / less opinionated word than "correct" here. if we do use the word "correct," I think the responsibility is on us to be very pedantic / technical / precise about what we mean by correctness

File: CLAUDE.md
Comment (lvlte) [reply CLAUDE.md:1]: This was required one month ago, the first build check would have failed without this change. The file has been updated on master since then.

File: base/div.jl (hunk 2 above)
Comment (lvlte) [reply base/div.jl]: The end of the sentence precisely describes what it means by "correct" I think, but maybe just : 

> Because `fld(x, y)` implements strict floored rounding based on the true value of floating-point numbers ...

File: CLAUDE.md
Comment (adienes) [inline CLAUDE.md:1]: this file seems unrelated

Comment (nsajko) [reply CLAUDE.md:1]: Yeah, already pointed out above.

**Comment by adienes** [comment]
the implementation is reasonably well-defended, and the semantics already approved by triage. the tests could probably be a bit more thorough, but it's good we added a least a few more edge cases. in particular, I'm imagining we could add a few more tests for the case when `eps > 1` to confirm the property `if you compute in higher precision and cast back down, what you get would be == to the result here`

the rest of my comments would just be working on the docs a bit. the examples given in the warnings are great! but reading through them, I see the following terms several times

* `accurate`, `precise`, `strict rounding`, `numerical value`, `true value`

and I think as a first-time-reader I would not really know how to make sense of or distinguish these terms. I'm wondering if we can choose just one or two pieces of nomenclature and use them consistently.

for example, just an idea: "mathematical value" to describe the point on the real number line occupied by `x / y`, "floating-point value" to describe the number you get under IEEE arithmetic of `x / y`

might be applied to this block
> Accurate results for floating-point arguments are only guaranteed when the
    true value of `x / y` is within the range of exactly representable integers
    for the given floating-point type, that is, when `eps(x/y) ≤ 1`, or in other
    words, given `a = div(x, y)`, when `abs(a) < maxintfloat(a)`.

to

> Accurate results for floating-point arguments are only guaranteed when the
    **_mathematical value_** of `x / y` is within the range of exactly representable integers
    for the given floating-point type, that is, when `eps(x/y) ≤ 1`, or in other
    words, given `a = div(x, y)`, when `abs(a) < maxintfloat(a)`.

I might also say there "when `floor(x/y)` and `ceil(x/y)` are representable by the given floating-point type" rather than "within the range of exactly representable integers --- as written I'm not sure it's 100% correct, as `div` gives you a floating-point value but the guarantee is about mathematical values.

we could apply these terms to the second block as
> Because `fld(x, y)` implements floored rounding based on the floating-point value of the division, unintuitive situations can arise. For example: ...

>    What is happening here is that the floating-point value of the number written
    as `0.1` is slightly larger than the mathematical value 1/10, while `6.0` represents
    the mathematical value 6 precisely. Therefore the mathematical value of the expression `6.0 / 0.1` is slightly less
    than 60. When doing division, this is rounded to precisely `60.0`, but
    `fld(6.0, 0.1)` always takes the floor of the mathematical value, so the result is `59.0`


although, to be fair, these docs changes could be left for a separate PR. if you're not interested in changing that here I do think they are correct as written, just confusing.

**Comment by lvlte** [comment]
I agree for the first part, using "mathematical value" instead of "true value" makes more sense here. 

Though adding `floor(x/y)` and `ceil(x/y)` in the mix might be more confusing imho, unless you meant their mathematical equivalent : accurate results (floating-point integer equal to $\left\lceil \frac{x}{y} \right\rceil$ or $\left\lfloor \frac{x}{y} \right\rfloor$) are actually guaranteed when the mathematical value $\frac{x}{y}$ is within the range of "safe" integers `[-maxintfloat(T), +maxintfloat(T)]` for the given floating-point type `T`. 

Also in the second block, I don't think it's a good idea to replace "true value" by "floating-point value of the division", precisely because the result of the floating-point division `x/y` (which I understand is what you meant, but maybe I'm also confused by the wording) is subject to roundoff error in both direction, while `div(x, y, r)` is rounded according to `r` as long as the condition mentioned in the first block is satisfied. I would suggest instead : 

> Because `div(x, y)` implements strict truncated rounding based on the quotient and remainder of the Euclidean division $\frac{x}{y}$, unintuitive situations can arise [...]

I don't know if Julia docs supports latex symbols, but it would certainly help make the distinction between floating-point vs mathematical operations/results (though not possible in REPL).

**Comment by nsajko** [comment]
> I don't know if Julia docs supports latex symbols

They do.

**Comment by adienes** [comment]
yeah, `floor` `ceil` may not be a great part of the spitball. I would more highly prioritize being a bit neater about those terms I listed above rather than just using "true value" with a context-dependent meaning

**Comment by adienes** [comment]
thank you! in my opinion the new docs are more clear.

just need to remove the diff to `CLAUDE.md` and it looks good to go to me!

**Review by adienes — APPROVED** [review]
