### PR TITLE
fix #41347, better checks for `yield` and `yieldto` with finished tasks

### LINKED ISSUE #41347: Yielding to finished task results in fatal exception
Behaviour on Julia 1.5.3, 1.6.1, and 1.7.0-beta2:
```julia
julia> t = @async true
Task (done) @0x00007fba6f5fb730

julia> yield(t)
ERROR: fatal: error thrown and no exception handler available.
TypeError(func=:typeassert, context="", expected=Int32, got=nothing)
jl_type_error_rt at /home/omus/julia/1.6/src/rtutils.c:119
jl_type_error at /home/omus/julia/1.6/src/rtutils.c:127
uv_write at ./stream.jl:992
unsafe_write at ./stream.jl:1064
write at ./strings/io.jl:185 [inlined]
print at ./strings/io.jl:187 [inlined]
#with_output_color#814 at ./util.jl:91
with_output_color##kw at ./util.jl:71 [inlined]
#printstyled#815 at ./util.jl:105 [inlined]
printstyled##kw at ./util.jl:105 [inlined]
display_error at ./client.jl:102
display_error at ./client.jl:107
jl_apply at /home/omus/julia/1.6/src/julia.h:1703 [inlined]
jl_f__call_latest at /home/omus/julia/1.6/src/builtins.c:714
#invokelatest#2 at ./essentials.jl:708 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
_start at ./client.jl:487
jfptr__start_28164 at /home/omus/julia/1.6/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/omus/julia/1.6/src/julia.h:1703 [inlined]
true_main at /home/omus/julia/1.6/src/jlapi.c:560
repl_entrypoint at /home/omus/julia/1.6/src/jlapi.c:702
main at julia-1.6 (unknown line)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
_start at julia-1.6 (unknown line)
```

The behaviour on Julia 1.4.2 didn't result in this fatal exception:
```julia
julia> t = @async true
Task (done) @0x00007fbaaa8109d0

julia> yield(t)

WARNING: Workqueue inconsistency detected: popfirst!(Workqueue).state != :runnable
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #41347

### CODE REVIEW

File: src/task.c [hunk 1]
```diff
@@ -475,12 +475,7 @@ JL_DLLEXPORT void jl_switch(void)
     if (t == ct) {
         return;
     }
-    if (t->_state != JL_TASK_STATE_RUNNABLE || (t->started && t->stkbuf == NULL)) {
-        ct->_isexception = t->_isexception;
-        ct->result = t->result;
-        jl_gc_wb(ct, ct->result);
-        return;
-    }
+    assert(t->_state == JL_TASK_STATE_RUNNABLE);
```
Comment (vtjnash) [inline src/task.c:478]:
```suggestion
    if (t->started && t->stkbuf == NULL)
        jl_error("task already exited");
```

**Review by vtjnash — APPROVED** [review]
I dislike this `_state` field, and the duplication with `_started` and `_isexception`
