### PR TITLE
fix perf in exp(::Matrix) (for smallish matrices)

### LINKED ISSUE #565: Matrix exponential slow in Julia 0.7 / 1.0
In Julia 0.6.4:
```julia
julia> @btime expm([1 0; 2 0])
  3.601 μs (46 allocations: 4.55 KiB)
```
In Julia 0.7 and 1.0:
```julia
julia> @btime exp([1 0; 2 0])
  16.710 μs (67 allocations: 4.55 KiB)
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/LinearAlgebra.jl/issues/565

Before:
```jl
julia> @btime exp([1. 0; 2 0])
  18.912 μs (73 allocations: 4.80 KiB)
```

After:

```jl
julia> @btime exp([1. 0; 2 0])
  3.529 μs (25 allocations: 2.30 KiB)
```

**Edit: The text below is no longer relevant:**

Should the broadcasting be able to do better here? cc @mbauman  Here is a MWE

```jl
f(A, A2, A4, A6, CC, Inn)      =  A * (A6 * (CC[14]*A6  + CC[12]*A4  + CC[10]*A2)  + CC[8]*A6  + CC[6]*A4  + CC[4]*A2  + CC[2]*Inn)
f_dots(A, A2, A4, A6, CC, Inn) =  A * (A6 * (CC[14]*A6 .+ CC[12]*A4 .+ CC[10]*A2) .+ CC[8]*A6 .+ CC[6]*A4 .+ CC[4]*A2 .+ CC[2]*Inn)
CC = rand(100); A = rand(2,2); A2 = A*A; A4 = A2*A2; A6 = A2 * A4; Inn = rand(2,2);

@btime f($A, $A2, $A4, $A6, $CC, $Inn)
  6.949 μs (28 allocations: 1.69 KiB)

@btime f_dots($A, $A2, $A4, $A6, $CC, $Inn)
  565.278 ns (11 allocations: 1.20 KiB)
```

Update since it is being discussed: using full fusion:

```jl
f_ddots(A, A2, A4, A6, CC, Inn) =  A * (A6 * @.((CC[14]*A6  + CC[12]*A4  + CC[10]*A2)  + CC[8]*A6  + CC[6]*A4  + CC[4]*A2  + CC[2]*Inn))

@btime f_ddots($A, $A2, $A4, $A6, $CC, $Inn)
  1.787 μs (7 allocations: 464 bytes)
```

### CODE REVIEW

**Comment by stevengj** [comment]
#29113 is about the matrix exponential, which has nothing to do with broadcasting.  In 0.6 you need to call `expm` for this.

File: stdlib/LinearAlgebra/src/dense.jl [hunk 1]
```diff
@@ -541,10 +541,10 @@ function exp!(A::StridedMatrix{T}) where T<:BlasFloat
         A2 = A * A
         A4 = A2 * A2
         A6 = A2 * A4
-        U  = A * (A6 * (CC[14]*A6 + CC[12]*A4 + CC[10]*A2) +
-                  CC[8]*A6 + CC[6]*A4 + CC[4]*A2 + CC[2]*Inn)
-        V  = A6 * (CC[13]*A6 + CC[11]*A4 + CC[9]*A2) +
-                   CC[7]*A6 + CC[5]*A4 + CC[3]*A2 + CC[1]*Inn
+        U  = A * (A6 * (CC[14]*A6 .+ CC[12]*A4 .+ CC[10]*A2) .+
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/dense.jl]: `CC[14]*A6` etcetera should be `CC[14].*A6` in order to fuse.    Probably cleaner to just do `@.(CC[14]*A6 + CC[12]*A4 + …)`

File: stdlib/LinearAlgebra/src/dense.jl [hunk 2]
```diff
@@ -541,10 +541,10 @@ function exp!(A::StridedMatrix{T}) where T<:BlasFloat
...
+                  CC[8]*A6 .+ CC[6]*A4 .+ CC[4]*A2 .+ CC[2]*Inn)
+        V  = A6 * (CC[13]*A6 .+ CC[11]*A4 .+ CC[9]*A2) .+
+                   CC[7]*A6 .+ CC[5]*A4 .+ CC[3]*A2 .+ CC[1]*Inn
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/dense.jl]: If we really wanted to we could split out the `+ CC[2]*Inn` operation into a separate loop that just updates the diagonals in-place.

In general, it looks like there are lots of opportunities for avoiding temporary array allocations in this routine if we care, both by re-using arrays and by using things like `rmul!`.

File: stdlib/LinearAlgebra/src/dense.jl (hunk 1 above)
Comment (stevengj) [reply stdlib/LinearAlgebra/src/dense.jl]: (I'm not sure why `CC` is an array rather than a bunch of scalars.   Not that any of these micro-optimizations matter for large arrays.)

Comment (KristofferC) [reply stdlib/LinearAlgebra/src/dense.jl]: That makes the code three times slower so I rather not do that.

Comment (KristofferC) [reply stdlib/LinearAlgebra/src/dense.jl]: Like, I put a MWE on the top so we can talk about actual performance instead of theoretical performance :P

Comment (mbauman) [reply stdlib/LinearAlgebra/src/dense.jl]: That looks like #28126, particularly since when I tried it I saw a 2x gain.  :-\

```julia
julia> @btime f_dots2($A, $A2, $A4, $A6, $CC, $Inn)
  254.430 ns (5 allocations: 560 bytes)
2×2 Array{Float64,2}:
 0.516647  0.311652
 0.186972  0.116884
```

Comment (KristofferC) [reply stdlib/LinearAlgebra/src/dense.jl]: Ok, I also get that, but not when using the macro... Did I mess up?

Comment (KristofferC) [reply stdlib/LinearAlgebra/src/dense.jl]: Ah nvm, I see now

Comment (KristofferC) [reply stdlib/LinearAlgebra/src/dense.jl]: Anyway, just pushed it with explicit dots.

Comment (mbauman) [reply stdlib/LinearAlgebra/src/dense.jl]: Ah, the difference appears to be in the n-ary operations.  The parser doesn't use special n-ary parsing for `.+` but the `@.` macro does.

**Comment by Keno** [comment]
Do we have this as a nanosoldier benchmark and didn't notice? If not, add it?

**Comment by KristofferC** [comment]
Benchmark label is on there so anyone feel free to add it.
