### PR TITLE
Make setindex! work for views of BitArrays

### LINKED ISSUE #20715: repeat broken for BitArrays
This used to work
```julia
julia> repeat(bitrand(2,2), inner = (2,1), outer = (1,2))
ERROR: MethodError: Cannot `convert` an object of type SubArray{Bool,2,BitArray{2},Tuple{UnitRange{Int64},UnitRange{Int64}},false} to an object of type Bool
This may have arisen from a call to the constructor Bool(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] macro expansion at ./multidimensional.jl:1025 [inlined]
 [2] _unsafe_setindex!(::BitArray{2}, ::SubArray{Bool,2,BitArray{2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}, ::UnitRange{Int64}, ::UnitRange{Int64}) at ./multidimensional.jl:1023
 [3] setindex!(::BitArray{2}, ::SubArray{Bool,2,BitArray{2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}, ::UnitRange{Int64}, ::UnitRange{Int64}) at ./multidimensional.jl:1019
 [4] _repeat at ./abstractarraymath.jl:424 [inlined]
 [5] #repeat#110(::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Function, ::BitArray{2}) at ./abstractarraymath.jl:365
 [6] (::Base.#kw##repeat)(::Array{Any,1}, ::Base.#repeat, ::BitArray{2}) at ./<missing>:0
```
but we probably didn't have tests for it. It looks like we need a `setindex!` method for views of `BitArrays`

cc: @pabloferz, @mbauman

### PR DESCRIPTION
**Pull request by andreasnoack**
by loosening signature for Arrays to AbstractArrays. This is not the fastest solution but it should be correct.

Fixes #20715

### CODE REVIEW

File: base/bitarray.jl [hunk 1]
```diff
@@ -335,7 +335,7 @@ end
 @inline try_bool_conversion(x::Real) = x == 0 || x == 1 || throw(InexactError())
 @inline unchecked_bool_convert(x::Real) = x == 1
 
-function copy_to_bitarray_chunks!(Bc::Vector{UInt64}, pos_d::Int, C::Array{<:Real}, pos_s::Int, numbits::Int)
+function copy_to_bitarray_chunks!(Bc::Vector{UInt64}, pos_d::Int, C::AbstractArray{<:Real}, pos_s::Int, numbits::Int)
```
Comment (mbauman) [inline base/bitarray.jl]: May as well get rid of the `{<:Real}` and test something like `B[1:3] = Any[true,false,true]` while we're at it.  The `try_bool_conversion` below will catch any non-Real values.

Comment (andreasnoack) [inline base/bitarray.jl]: There is a method just for `Array` in line 318. I'm not sure what the relation between the two methods is.

Comment (mbauman) [inline base/bitarray.jl]: Aha, sure, so then I'd keep this one restricted to `<:Real` and then also widen the method on 318 to `AbstractArray`.  That'd preserve the original intention of these two methods.

**Comment by andreasnoack** [comment]
cc: @carlobaldassi

File: base/bitarray.jl (hunk 1 above)
Comment (carlobaldassi) [inline base/bitarray.jl]: If I remember correctly, the main reason for the `Real` restriction was that this method relies on a particular definition of the conversion to Bools (see line 330 above), as defined in "bool.jl". For general non-Real types however converting to Bools is not defined, therefore the user would have to define their own method, and the BitArray code should use the user-defined function, otherwise the behavior would be very confusing.
We could remove the restriction (and the function above) and implement two fallback methods instead:

```julia
@inline try_bool_conversion(x) = true
@inline unchecked_bool_convert(x) = Bool(x)
```

By the way we could then also add the `Complex` case in this way:

```julia
@inline try_bool_conversion(x::Complez) = isreal(x) ? try_bool_conversion(real(x)) : throw(InexactError())
@inline unchecked_bool_convert(x) = unchecked_bool_convert(real(x))
```

I'm not sure it's worth it however, I'm pretty sure I had also checked the performance at the time of writing these functions (things may have changed of course).

**Comment by carlobaldassi** [comment]
I suppose this is ok, but does it work correctly with AbstractArrays with unusual (non-1-based) indexing?

File: base/bitarray.jl (hunk 1 above)
Comment (andreasnoack) [inline base/bitarray.jl]: Thanks for the explanation. I'll leave such a change for another PR and just loosen the signature for now such that views go through.

**Comment by andreasnoack** [comment]
> I suppose this is ok, but does it work correctly with AbstractArrays with unusual (non-1-based) indexing?

Good point. I don't think this will work for non-1-based indexing. I've restricted the signatures to `StridedArray` as rewriting the methods to allow for non-1-based indexing seems like a much bigger task.

**Comment by mbauman** [comment]
That's just trading one broken behavior for another. Both versions are broken for non-one based arrays; I'd prefer to stick with the wider `AbstractArray` since it'd be correct in more situations and have a more relevant error message.

**Comment by andreasnoack** [comment]
> Both versions are broken for non-one based arrays

Can non-1-based arrays be `StridedArray`? I thought they'd have to subtype `AbstractArray` and not `DenseArray`.

**Comment by mbauman** [comment]
No, but they'll fall back to the scalar method that tries to convert them to Bool.
