### PR TITLE
fix #17338, broken showing of SimpleVector

### LINKED ISSUE #17338: Display broken for SimpleVector (svec)
Trying to display an `svec` produces the following exception:
```julia
julia> Tuple.parameters
Error showing value of type SimpleVector:
ERROR: MethodError: no method matching indices(::SimpleVector, ::Int64)WARNING: Error showing method candidates, aborted

 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::SimpleVector) at ./REPL.jl:114
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::SimpleVector) at ./REPL.jl:117
 in display(::SimpleVector) at ./multimedia.jl:143
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:134
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:121
 in (::Base.REPL.##18#19{Bool,Base.REPL.##29#38{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:631
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1570
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:882
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##598#599) at ./REPL.jl:167
 in _start() at ./client.jl:364
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: base/essentials.jl [hunk 1]
```diff
@@ -173,6 +173,7 @@ done(v::SimpleVector,i) = (i > v.length)
 isempty(v::SimpleVector) = (v.length == 0)
 indices(v::SimpleVector) = (OneTo(length(v)),)
 linearindices(v::SimpleVector) = indices(v, 1)
+indices(v::SimpleVector, d) = d <= 1 ? indices(v)[d] : OneTo(1)
```
Comment (tkelman) [inline base/essentials.jl]: this isn't the default fallback definition for `indices` ?

Comment (JeffBezanson) [inline base/essentials.jl]: Yes, but SimpleVector is not an AbstractArray. It might be possible to make it so, but that would be a more complicated change.

Comment (tkelman) [inline base/essentials.jl]: does the fallback need to be only for AbstractArray or does it make sense for Any?

Comment (timholy) [inline base/essentials.jl]: Seems reasonable to make it the default fallback.
