### PR TITLE
non-x86: ensure cgmemmgr caches are consistent

### LINKED ISSUE #17577: build failure on arm
Using fresh clone of master at db11bc7.  My last successful build was at e18ed61.
```
/home/sachs/src/julia-master/base/precompile.jl

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
Allocations: 44889342 (Pool: 44888794; Big: 548); GC: 25
Segmentation fault
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
Makefile:229: recipe for target '/home/sachs/src/julia-master/usr/lib/julia/sys.o' failed
make[1]: *** [/home/sachs/src/julia-master/usr/lib/julia/sys.o] Error 1
Makefile:99: recipe for target 'julia-sysimg-release' failed
make: *** [julia-sysimg-release] Error 2
```

### PR DESCRIPTION
**Pull request by vtjnash**
this ensures that the writes are completed before flushing the icache
otherwise, platforms like ARM would potentially fail to see some of the writes
and were especially likely to miss the relocations applied to the JIT code

fix #17577

### CODE REVIEW

**Comment by vtjnash** [comment]
CI failure was unrelated (spawn InterruptException)

File: src/cgmemmgr.cpp [hunk 1]
```diff
@@ -462,11 +462,12 @@ class ROAllocator {
     virtual ~ROAllocator() {}
     virtual void finalize()
     {
-        if (exec) {
-            for (auto &alloc: allocations) {
-                sys::Memory::InvalidateInstructionCache(alloc.rt_addr,
-                                                        alloc.sz);
-            }
+        for (auto &alloc: allocations) {
+            // ensure the mapped pages are consistent
```
Comment (yuyichao) [inline src/cgmemmgr.cpp]: Coherent is probably the right word since this is talking about the same memory location having different values simultaneously due to split caches.

**Comment by ViralBShah** [comment]
I cherry picked this commit locally on my release-0.5 branch on arm, and it fixed my arm build that had been broken for a very long time on cortex A15.

**Comment by ViralBShah** [comment]
Ideally I would have loved to get this in the 0.5.0 release, but I know it is way too late for that.

**Comment by yuyichao** [comment]
The change is a no-op on x86 so the backport requirement can in principle be relaxed.

**Comment by ViralBShah** [comment]
@tkelman Do you think we can get this into 0.5, since it doesn't change anything on x86 (even though it is not obvious in the commit diff)?

**Comment by tkelman** [comment]
Since #18100 was reverted on release-0.5 I don't think it's strictly necessary there. I'd rather it be on master a little longer because of the non-obvious part you mention. I'll most likely un-revert #18100 and backport this at the same time for 0.5.1.

**Comment by yuyichao** [comment]
> even though it is not obvious in the commit diff

`llvm::Memory::InvalidateInstructionCache` is no op on x86.

**Comment by vtjnash** [comment]
@tkelman there is no bug in #18100. However, as Viral mentioned above, this commit is required to build the tip of the release-0.5 branch on ARM.

**Comment by yuyichao** [comment]
> there is no bug in #18100

In another word, the bug was in https://github.com/JuliaLang/julia/pull/16777, but somehow was never exposed until later.

**Comment by tkelman** [comment]
release-0.5 was able to build without this, just not reliably, #18100 made the issue occur 100% of the time. this is in #18546 anyway.
