### PR TITLE
fix debug typo in "add missing invoke edge for nospecialize targets (#51036)"

### LINKED ISSUE #51146: Recent regression in spurious invalidations.
Running with Pkg out of the sysimage (using this commit https://github.com/JuliaLang/julia/commit/412c8f440fac0ffb1966f7beddf76a0cb4cc3b0c) and the following Pkg commit https://github.com/JuliaLang/Pkg.jl/commit/f2d8b64cd37dfcfb1caa3b4e81b76b3b8462db44 there is a recent regression where the precompilation workload in Pkg seems to get heavily invalidated and becomes basically worthless:

```
# Good
julia> @time Pkg.add("Example")
...
  1.735661 seconds (3.62 M allocations: 237.936 MiB, 7.02% gc time, 45.09% compilation time)

# Bad
julia> @time Pkg.add("Example")
...
 11.234634 seconds (4.29 M allocations: 307.999 MiB, 91.73% compilation time: 73% of which was recompilation)
```

This recompilation seems spurious since there are no (AFAIK) other packages getting loaded that would cause this.

This was bisected to https://github.com/JuliaLang/julia/pull/51036 cc @vtjnash 

Marking for 1.10 since the offending commit is marked for backporting.

### PR DESCRIPTION
**Pull request by vtjnash**
Causes `matches` to get replaced with `MethodMatch` instead, which then later will fail to match with the expected value.

Fixes #51146

### CODE REVIEW

File: src/staticdata_utils.c [hunk 1]
```diff
@@ -510,7 +510,7 @@ static void jl_collect_edges(jl_array_t *edges, jl_array_t *ext_targets, jl_arra
 #ifndef NDEBUG
                     jl_methtable_t *mt = jl_method_get_table(m);
                     if ((jl_value_t*)mt != jl_nothing) {
-                        matches = jl_gf_invoke_lookup_worlds(invokeTypes, (jl_value_t*)mt, world, &min_valid, &max_valid);
+                        jl_value_t *matches = jl_gf_invoke_lookup_worlds(invokeTypes, (jl_value_t*)mt, world, &min_valid, &max_valid);
```
Comment (gbaraldi) [inline src/staticdata_utils.c:513]: Maybe give it another name if it's not the same thing as the `matches` above?

Comment (vtjnash) [reply src/staticdata_utils.c:513]: It is the same, we just are using it to assert that (note the NDEBUG above it)

Comment (gbaraldi) [reply src/staticdata_utils.c:513]: Oh, I missed that oops
