### PR TITLE
fix `eigvals,eigvecs,eigen` for `Diagonal{Matrix}`

### LINKED ISSUE #594: broken eig functions for Diagonal{Matrix}
Bug noted in JuliaLang/julia#21598, filing a separate issue so that it doesn't get lost.
```jl
julia> using LinearAlgebra

julia> I2 = Matrix(I, 2,2); D = Diagonal([2.0*I2, 3.0*I2])
2×2 Diagonal{Array{Float64,2},Array{Array{Float64,2},1}}:
 [2.0 0.0; 0.0 2.0]          ⋅         
         ⋅           [3.0 0.0; 0.0 3.0]

julia> eigvals(Diagonal([2.0*I2, 3.0*I2]))  # SHOULD RETURN ARRAY OF SCALARS!
2-element Array{Array{Float64,1},1}:
 [2.0, 2.0]
 [3.0, 3.0]

julia> eigvecs(D)
ERROR: MethodError: no method matching zero(::Type{Array{Float64,2}})
Closest candidates are:
  zero(::Type{LibGit2.GitHash}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeights.VersionWeight}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/resolve/VersionWeights.jl:19
  zero(::Type{Pkg.Resolve.MaxSum.FieldValues.FieldValue}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/resolve/FieldValues.jl:44
  ...
Stacktrace:
 [1] zeros(::Type{Array{Float64,2}}, ::Tuple{Int64,Int64}) at ./array.jl:467
 [2] Array{Array{Float64,2},2}(::UniformScaling{Bool}, ::Tuple{Int64,Int64}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/uniformscaling.jl:317
 [3] eigvecs(::Diagonal{Array{Float64,2},Array{Array{Float64,2},1}}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/diagonal.jl:486
 [4] top-level scope at none:0

julia> eigen(D)
ERROR: MethodError: no method matching isfinite(::Array{Float64,2})
Closest candidates are:
  isfinite(::BigFloat) at mpfr.jl:858
  isfinite(::Missing) at missing.jl:79
  isfinite(::Float16) at float.jl:545
  ...
Stacktrace:
 [1] (::getfield(Base, Symbol("##54#55")){typeof(isfinite)})(::Array{Float64,2}) at ./operators.jl:853
 [2] _any at ./reduce.jl:614 [inlined]
 [3] #any#548 at ./reducedim.jl:655 [inlined]
 [4] any at ./reducedim.jl:655 [inlined]
 [5] #eigen#114(::Bool, ::Bool, ::Function, ::Diagonal{Array{Float64,2},Array{Array{Float64,2},1}}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/diagonal.jl:488
 [6] eigen(::Diagonal{Array{Float64,2},Array{Array{Float64,2},1}}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/diagonal.jl:488
 [7] top-level scope at none:0
```
Should be quite easy to fix.

### PR DESCRIPTION
**Pull request by fatteneder**
Fixes https://github.com/JuliaLang/LinearAlgebra.jl/issues/594.

There has been another attempt on fixing this https://github.com/JuliaLang/julia/pull/31509, but that seemed to have stopped two years ago.

@stevengj @dkarrasch Since you were involved in the issue and the other PR, may I ask you to also review this?

---

I hope I understood correctly how the fix in JuliaLang/LinearAlgebra.jl#594 was meant to work:
I implemented it such that the results of `eigvals(D), eigvecs(D), eigen(D)` behave as in the case with ordinary matrices, e.g.
if `D` is a block diagonal matrix then
```julia
julia> vals, vecs = eigen(D)
julia> D * vecs == vecs * Diagonal(vals) # true
```

Closes JuliaLang/julia#31509.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Bump @dkarrasch @stevengj

File: stdlib/LinearAlgebra/test/diagonal.jl [hunk 1]
```diff
@@ -766,6 +766,28 @@ end
...
+@testset "Eigensystem for block diagonal (issue #30681)" begin
+    I2 = Matrix(I, 2,2)
+    D = Diagonal([2.0*I2, 3.0*I2])
+    eigD = eigen(D)
+    evals = [ 2.0, 2.0, 3.0, 3.0 ]
+    evecs = [ [[ 1.0, 0.0 ]]  [[ 0.0, 1.0 ]]  [[ 0.0, 0.0 ]]  [[ 0.0, 0.0 ]];
+              [[ 0.0, 0.0 ]]  [[ 0.0, 0.0 ]]  [[ 1.0, 0.0 ]]  [[ 0.0, 1.0 ]] ]
+    @test eigD.values == evals
+    @test eigD.vectors == evecs
+    @test D * eigD.vectors == transpose(eigD.values) .* eigD.vectors
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/diagonal.jl:778]:
```suggestion
    @test D * eigD.vectors ≈ eigD.vectors * Diagonal(eigD.values)
```

File: stdlib/LinearAlgebra/test/diagonal.jl [hunk 2]
```diff
@@ -766,6 +766,28 @@ end
...
+
+    I3 = Matrix(I, 3,3)
+    D = Diagonal([[0.0 -1.0; 1.0 0.0], 2.0*I3])
+    eigD = eigen(D)
+    evals = [ -1.0im, 1.0im, 2.0, 2.0, 2.0 ]
+    evecs = [ [[ 1/sqrt(2)+0im, 1/sqrt(2)*im ]]  [[ 1/sqrt(2)+0im, -1/sqrt(2)*im ]]  [[ 0.0, 0.0 ]]       [[ 0.0, 0.0 ]]      [[ 0.0, 0.0]];
+              [[ 0.0, 0.0, 0.0 ]]                [[ 0.0, 0.0, 0.0 ]]                 [[ 1.0, 0.0, 0.0 ]]  [[ 0.0, 1.0, 0.0 ]] [[ 0.0, 0.0, 1.0]] ]
+    @test eigD.values == evals
+    @test eigD.vectors == evecs
+    @test D * eigD.vectors == transpose(eigD.values) .* eigD.vectors
```
[the remark this answers is not in the document]
Comment (dkarrasch) [reply stdlib/LinearAlgebra/test/diagonal.jl:788]:
```suggestion
    @test eigD.values == evals
    @test eigD.vectors == evecs
    @test D * eigD.vectors ≈ eigD.vectors * Diagonal(eigD.values)
```

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 3]
```diff
@@ -768,11 +768,33 @@ function pinv(D::Diagonal{T}, tol::Real) where T
...
-eigvecs(D::Diagonal) = Matrix{eltype(D)}(I, size(D))
+    reduce(vcat, eigvals(x) for x in D.diag) #For block matrices, etc.
+function eigvecs(D::Diagonal{T}) where T<:AbstractMatrix
+    diag_vecs = [ eigvecs(x) for x in D.diag ]
+    matT = reduce((a,b) -> promote_type(typeof(a),typeof(b)), diag_vecs)
+    ncols_diag = [ size(x, 2) for x in D.diag ]
+    nrows = size(D, 1)
+    vecs = Matrix{Vector{eltype(matT)}}(undef, nrows, sum(ncols_diag))
+    for ij in eachindex(D)
+        i,j = Tuple(ij)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/diagonal.jl:784]: How about
```suggestion
    for j in axes(D, 2), i in axes(D, 1)
```
? Using CartesianIndex first and then immediately turning into a tuple looks a bit "round the corner".

**Review by dkarrasch — COMMENTED** [review]
Some small comments, otherwise LGTM. The crucial thing was to be able to multiply the diagonal matrix of matrices with the eigenvector matrix. That works nicely, as the tests show.

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 4]
```diff
@@ -768,11 +768,33 @@ function pinv(D::Diagonal{T}, tol::Real) where T
     Diagonal(Di)
 end
 
+# TODO Docstrings for eigvals, eigvecs, eigen all mention permute, scale, sortby as keyword args
```
Comment (fatteneder) [inline stdlib/LinearAlgebra/src/diagonal.jl:771]: @dkarrasch Do you have an opinion on this?

**Review by fatteneder — COMMENTED** [review]
Thank you for the review. Will try to update this soonish.

**Comment by dkarrasch** [comment]
Just in case: if you agree with the suggestions, you can switch to the "Files changed" tab, then "add suggestion to batch" for the agreed suggestions, and then push the commit. No need to get back to your own codebase.

File: stdlib/LinearAlgebra/src/diagonal.jl (hunk 4 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/diagonal.jl:771]: One would need to check if these keywords apply to all methods. I saw that you already implemented `sortby` in `eigen`. `scale` and `permute` don't apply to all methods, IIRC. I think they are specific to dense LAPACK matrices.

Comment (fatteneder) [reply stdlib/LinearAlgebra/src/diagonal.jl:771]: I checked again and remembered that I added `scale, permute` to `eigen(::Diagonal{<:AbstractMatrix},...)`, because also `eigen(::Diagonal,...)` specifies them but doesn't actually use them. So I guess we could leave as it is, then they are just without effect.

**Review by dkarrasch — APPROVED** [review]

**Comment by dkarrasch** [comment]
Thanks @fatteneder for your contribution!
