### PR TITLE
fix #21397, `Nullable(Tuple)` method error

### LINKED ISSUE #21397: `Nullable(Tuple)` method error
Expected behavior:

```
julia> Nullable(Tuple)
Nullable{DataType}(Tuple)
```

Observed behavior:

```
julia> Nullable(Tuple)
ERROR: MethodError: no method matching Nullable{T<:(Type{T} where T<:Tuple)}(::Type{Tuple}, ::Bool)
Stacktrace:
 [1] Nullable(::Type{T} where T<:Tuple, ::Bool) at ./nullable.jl:34 (repeats 2 times)
```

This is a very strange bug, especially because

```
julia> @code_warntype Nullable(Tuple)
Variables:
  #self#::Any
  value::Type{Tuple}

Body:
  begin 
      return $(Expr(:new, Nullable{DataType}, true, :(value)))
  end::Nullable{DataType}
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -4820,3 +4820,8 @@ f21271() = convert(Tuple{Type{Int}, Type{Float64}}, (Int, Float64))::Tuple{Type{
 f21271(x) = x::Tuple{Type{Int}, Type{Float64}}
 @test_throws TypeError f21271()
 @test_throws TypeError f21271((Int, Float64))
+
+# issue #21397
+bar21397(x::T) where T = T
```
Comment (vtjnash) [inline test/core.jl]: Fomatting

**Review by vtjnash — APPROVED** [review]
