### PR TITLE
types: fix cache computation

### LINKED ISSUE #41503: Julia nightly throwing at `jl_datatype_isinlinealloc`
A recent version of Julia nightly started throwing errors on tests in Manifolds.jl, see for example these CI runs: https://github.com/JuliaManifolds/Manifolds.jl/pull/381/checks?check_run_id=3010181089 . On Windows, for example, a part of the error reads:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1f9b127 -- jl_datatype_isinlinealloc at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:253 [inlined]
jl_datatype_isinlinealloc at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:250 [inlined]
union_isinlinable at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:277 [inlined]
union_isinlinable at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:266
in expression starting at D:\a\Manifolds.jl\Manifolds.jl\test\centered_matrices.jl:3
```
and on Ubuntu:
```
signal (11): Segmentation fault
in expression starting at /home/runner/work/Manifolds.jl/Manifolds.jl/test/centered_matrices.jl:3
jl_datatype_isinlinealloc at /buildworker/worker/package_linux64/build/src/datatype.c:253 [inlined]
union_isinlinable at /buildworker/worker/package_linux64/build/src/datatype.c:277 [inlined]
jl_islayout_inline at /buildworker/worker/package_linux64/build/src/datatype.c:300
jl_compute_field_offsets at /buildworker/worker/package_linux64/build/src/datatype.c:446
inst_datatype_inner at /buildworker/worker/package_linux64/build/src/jltypes.c:1520
```

I'll try making an MWE.

### PR DESCRIPTION
**Pull request by vtjnash**
Need to compute `cacheable` after normalization, since the purpose of
the normalization was to turn these into normal cacheable objects,
when applicable.

Brokenness exposed by #36211
Fixes #41503

### CODE REVIEW

**Comment by Sacha0** [comment]
Thanks for working on this Jameson! Excited to test this out! :)

**Comment by martinholters** [comment]
I remember being a bit puzzled about the `cachable` being piped through various function calls, stemming from different origins with slightly different computations rules. So this definitely improves clarity. :+1: And your reasoning also makes perfect sense. I'm  bit hesitant to "officially" approve as I have no idea whether this change has any other implications. (Is there a good reason why is was structured the way it was before? Or did it just not really matter before #36211?)

File: src/jltypes.c [hunk 1]
```diff
@@ -1593,14 +1593,13 @@ jl_tupletype_t *jl_inst_arg_tuple_type(jl_value_t *arg1, jl_value_t **args, size
                 // `jl_typeof(ai)`, but that will require some redesign of the caching
                 // logic.
                 ai = (jl_value_t*)jl_wrap_Type(ai);
-                cacheable = 0;
```
Comment (martinholters) [inline src/jltypes.c:1596]: This one is beyond me. What case did this prevent from caching?

Comment (vtjnash) [reply src/jltypes.c:1596]: it is a different way to compute the same thing

**Comment by Sacha0** [comment]
🎉

**Comment by benlorenz** [comment]
Can this be backported to 1.7 / get a `backport 1.7` label please? (It does belong to the 1.7 milestone already but was merged only into master so far)
It should apply cleanly now that #41659 is already on the backports branch.

I also verified that this fixes the issue (`jl_datatype_isinlinealloc` segfault) we observed in Oscar.jl with the latest julia 1.7.
