### PR TITLE
fix thread scheduler variable used

### LINKED ISSUE #32511: Large numbers of threads hang in `@threads`
This is non-deterministic (huzzah) but luckily easy enough to trigger.  I think using `@benchmark` more reliably triggers it since it's running threaded loops many thousands of times.  Here's a test script:

```julia
using BenchmarkTools, Base.Threads

function func_threaded(val, N)
    sums = [0*(1 .^ val) for thread_idx in 1:nthreads()]
    @threads for idx in 1:N
        sums[threadid()] += idx.^val
    end
    return sum(sums)
end

@benchmark func_threaded(2.0, 1<<10)
```

And here's a log showing the fact that it hangs approximately 2/5 of the time:

```bash
$ for idx in $(seq 1 10); do echo "Run ${idx}:"; JULIA_NUM_THREADS=8 time julia-master thread_lock.jl; done
Run 1:
^C
signal (2): Interrupt: 2
in expression starting at /Users/sabae/src/julia/thread_lock.jl:11
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 2855175 (Pool: 2854832; Big: 343); GC: 11
       24.81 real         5.27 user         0.34 sys
Run 2:
^C
signal (2): Interrupt: 2
in expression starting at /Users/sabae/src/julia/thread_lock.jl:11
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 2129862 (Pool: 2129518; Big: 344); GC: 8
       28.74 real         1.38 user         0.21 sys
Run 3:
        6.94 real        39.42 user         1.78 sys
Run 4:
        7.02 real        39.16 user         1.79 sys
Run 5:
        7.07 real        40.29 user         1.81 sys
Run 6:
^C
signal (2): Interrupt: 2
in expression starting at /Users/sabae/src/julia/thread_lock.jl:11
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 8821151 (Pool: 8820777; Big: 374); GC: 39
       28.69 real        36.36 user         1.67 sys
Run 7:
        6.85 real        40.36 user         1.77 sys
Run 8:
        6.82 real        40.23 user         1.76 sys
Run 9:
        6.99 real        40.07 user         1.79 sys
Run 10:
^C
signal (2): Interrupt: 2
in expression starting at /Users/sabae/src/julia/thread_lock.jl:11
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 3580053 (Pool: 3579711; Big: 342); GC: 14
       19.33 real        10.11 user         0.55 sys
```

### PR DESCRIPTION
**Pull request by vtjnash**
It turns out that a scheduler can get stuck if you wake up the wrong thread. Who knew that using the wrong variable could cause such subtle issues. Might be a contender for worst-bug-debugging award (I'll let you parse that with any associativity you want).  Meanwhile, we get some extra optimizations too from staring at this code for several days straight.

fixes #32511

note that to reproduce more, it helps to disable `sleep_check_after_threshold`

### CODE REVIEW

**Comment by JeffBezanson** [comment]
The example code in the issue failed reliably enough that it's probably worth adding as a test.

**Review by JeffBezanson — APPROVED** [review]

File: src/partr.c [hunk 1]
```diff
@@ -298,6 +321,7 @@ JL_DLLEXPORT int jl_enqueue_task(jl_task_t *task)
 //  sleep_check_after_threshold() -- if sleep_threshold ns have passed, return 1
 static int sleep_check_after_threshold(uint64_t *start_cycles)
 {
+    JULIA_DEBUG_SLEEPWAKE( return 1; ) // hammer on the sleep/wake logic much harder
```
Comment (JeffBezanson) [inline src/partr.c]: Could you add semicolons after these? This seems to confuse emacs auto-indent.

File: src/partr.c [hunk 2]
```diff
@@ -340,54 +364,59 @@ static int sleep_check_after_threshold(uint64_t *start_cycles)
...
+
 /* ensure thread tid is awake if necessary */
 JL_DLLEXPORT void jl_wakeup_thread(int16_t tid)
 {
     jl_ptls_t ptls = jl_get_ptls_states();
+    int16_t uvlock = jl_atomic_load(&jl_uv_mutex.owner);
     int16_t self = ptls->tid;
-    int16_t uvlock = jl_atomic_load_acquire(&jl_uv_mutex.owner);
-    if (tid == self) {
+    unsigned long system_tid = jl_all_tls_states[tid]->system_id;
```
Comment (JeffBezanson) [inline src/partr.c]: `tid` might be -1 !

File: src/partr.c (hunk 1 above)
Comment (vtjnash) [reply src/partr.c]: Is that better?
