### PR TITLE
inference: limit single-level nested `Type` signature

### LINKED ISSUE #40336: limit_type_size failure for Type{Type{..}}
```
julia> f(@nospecialize(t)) = f(Type{t})
f (generic function with 1 method)

julia> @code_typed f(Int)
ERROR: StackOverflowError:
```

So clearly this type-limit isn't working:
```
        if isType(t) # allow taking typeof as Type{...}, but ensure it doesn't start nesting
            tt = unwrap_unionall(t.parameters[1])
            if isa(tt, DataType) && !isType(tt)
                is_derived_type_from_any(tt, sources, depth) && return t
            end
        end
```
Reported by @aviatesk

### PR DESCRIPTION
**Pull request by vtjnash**
Previously `type_more_complex` returns `false` for `Type{Type{...}}`
compared against `Type{...}`. Per comment there, this should return `true`,
but the code was ordered incorrect (it was also missing support for
Vararg, after the recent changes).

Fixes #40336, Replaces #40341

@aviatesk I think this is a more complete fix, that matches the intent of the comment there.

### CODE REVIEW

File: base/compiler/typelimits.jl [hunk 1]
```diff
@@ -128,7 +128,15 @@ function _limit_type_size(@nospecialize(t), @nospecialize(c), sources::SimpleVec
         end
         return Vararg{VaT}
     elseif isa(t, DataType)
-        if isa(c, DataType)
+        if isa(c, Core.TypeofVararg)
+            # Tuple{Vararg{T}} --> Tuple{T} is OK
+            return _limit_type_size(t, c.T, sources, depth, 0)
```
Comment (aviatesk) [inline base/compiler/typelimits.jl:133]:
```suggestion
            return _limit_type_size(t, unwrapva(c), sources, depth, 0)
```
for the consistency with the other parts ?

**Review by aviatesk — APPROVED** [review]
Thanks, LGTM.

File: base/compiler/typelimits.jl (hunk 1 above)
Comment (vtjnash) [reply base/compiler/typelimits.jl:133]: @keno ^

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40379#issuecomment-816153497) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c165fbe_vs_7d6dfe1/report.md). cc @christopher-dG
