### PR TITLE
Make `parse(T, "")` and `parse(T, " ")` etc, more specific regarding whitespace and empty strings

### LINKED ISSUE #20587: Misleading error message trying to parse empty string as Integer
```
julia> parse(Int, "", 16)
ERROR: ArgumentError: invalid base: base must be 2 ≤ base ≤ 62, got 0
Stacktrace:
 [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:63
 [2] parse(::Type{Int64}, ::String, ::Int64) at ./parse.jl:146
```

Would have expected an error about the string being empty, not an invalid base.

### PR DESCRIPTION
**Pull request by Tetralux**
Fixes #20587.

Before this PR:
```
julia> parse(Int, "", 16)
ERROR: ArgumentError: invalid base: base must be 2 ≤ base ≤ 62, got 0
Stacktrace:
 [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:63
 [2] parse(::Type{Int64}, ::String, ::Int64) at ./parse.jl:146
```

After this PR:
```
julia> parse(Int, "", 16)
ERROR: ArgumentError: input string is empty or only contains whitespace
Stacktrace:
 [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at .\parse.jl:62
 [2] parse(::Type{Int64}, ::String, ::Int64) at .\parse.jl:161
```

This message will also appear for `parse(T, "")` and `parse(T, " ")`, etc.

### CODE REVIEW

File: base/parse.jl [hunk 1]
```diff
@@ -58,6 +58,10 @@ end
 
 function tryparse_internal{T<:Integer}(::Type{T}, s::AbstractString, startpos::Int, endpos::Int, base_::Integer, raise::Bool)
     _n = Nullable{T}()
+    if isempty(strip(s))
```
Comment (JeffBezanson) [inline base/parse.jl]: I think calling `strip` will be too expensive here --- this function is very performance-critical, and most inputs don't need `strip` at all. I believe `parseint_preamble` returns a base of `0` if there is a problem; we should check for all-whitespace strings only in that case.

**Review by JeffBezanson — CHANGES_REQUESTED** [review]

File: base/parse.jl (hunk 1 above)
Comment (H-225) [inline base/parse.jl]: Should have spotted that. Will commit shortly.

**Comment by H-225** [comment]
Sorry that took a while. Took me farting around for an hour, trying to make it better for `Bool`, only to realise there was a _much_ simpler way of doing it. >D

File: base/parse.jl [hunk 2]
```diff
@@ -126,27 +130,49 @@ end
...
     (len == 4) && (0 == ccall(:memcmp, Int32, (Ptr{UInt8}, Ptr{UInt8}, UInt),
         p, "true", 4)) && (return Nullable(true))
     (len == 5) && (0 == ccall(:memcmp, Int32, (Ptr{UInt8}, Ptr{UInt8}, UInt),
         p, "false", 5)) && (return Nullable(false))
-    raise && throw(ArgumentError("invalid Bool representation: " *
-        repr(SubString(sbuff, startpos, endpos))))
-    Nullable{Bool}()
+
+    substr = SubString(sbuff, startpos, endpos)
+    if count(isspace, sbuff) == len # all chars were whitespace
```
Comment (JeffBezanson) [inline base/parse.jl]: I'm not too familiar with this code, but should this be checking `substr` instead of `sbuff`?

Comment (H-225) [inline base/parse.jl]: I should probably add a test for that. >)

**Comment by H-225** [comment]
Third time's a charm.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20588#issuecomment-279290741) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f35a4118d958dcf7cf6e78067711b922bd566ef6/3eea67f_vs_b1e2b9c/report.md). cc @jrevels

File: base/parse.jl [hunk 3]
```diff
@@ -126,27 +130,49 @@ end
 
 function tryparse_internal(::Type{Bool}, sbuff::Union{String,SubString},
         startpos::Int, endpos::Int, base::Integer, raise::Bool)
-    len = endpos-startpos+1
-    p = pointer(sbuff)+startpos-1
+    null = Nullable{Bool}()
```
Comment (nalimilan) [inline base/parse.jl]: I don't really see the point of defining this variable. Why not write `Nullable{Bool}()` where you need it?

File: base/parse.jl [hunk 4]
```diff
@@ -126,27 +130,49 @@ end
...
         p, "true", 4)) && (return Nullable(true))
     (len == 5) && (0 == ccall(:memcmp, Int32, (Ptr{UInt8}, Ptr{UInt8}, UInt),
         p, "false", 5)) && (return Nullable(false))
-    raise && throw(ArgumentError("invalid Bool representation: " *
-        repr(SubString(sbuff, startpos, endpos))))
-    Nullable{Bool}()
+
+    substr = SubString(sbuff, startpos, endpos)
+    if count(isspace, substr) == len # all chars were whitespace
+        raise && throw(ArgumentError("input string only contains whitespace"))
```
Comment (nalimilan) [inline base/parse.jl]: This looks a bit weird stylistically. Why not wrap both branches inside an `if raise` block?

File: base/parse.jl [hunk 5]
```diff
@@ -126,27 +130,49 @@ end
...
     (len == 4) && (0 == ccall(:memcmp, Int32, (Ptr{UInt8}, Ptr{UInt8}, UInt),
         p, "true", 4)) && (return Nullable(true))
     (len == 5) && (0 == ccall(:memcmp, Int32, (Ptr{UInt8}, Ptr{UInt8}, UInt),
         p, "false", 5)) && (return Nullable(false))
-    raise && throw(ArgumentError("invalid Bool representation: " *
-        repr(SubString(sbuff, startpos, endpos))))
-    Nullable{Bool}()
+
+    substr = SubString(sbuff, startpos, endpos)
+    if count(isspace, substr) == len # all chars were whitespace
```
Comment (nalimilan) [inline base/parse.jl]: `all(isspace, substr)` would be simpler (if I'm not missing something).

File: base/parse.jl [hunk 6]
```diff
@@ -159,8 +185,11 @@ tryparse(::Type{Float32}, s::SubString{String}) = ccall(:jl_try_substrtof, Nulla
 tryparse{T<:Union{Float32,Float64}}(::Type{T}, s::AbstractString) = tryparse(T, String(s))
 
 function parse{T<:AbstractFloat}(::Type{T}, s::AbstractString)
-    nf = tryparse(T, s)
-    isnull(nf) ? throw(ArgumentError("invalid number format $(repr(s)) for $T")) : get(nf)
+    result = tryparse(T, s)
+    if isnull(result)
+        throw(ArgumentError("cannot parse $(repr(s)) as $T"))
+    end
+    return get(result)
```
Comment (nalimilan) [inline base/parse.jl]: You can use `unsafe_get` since you have already checked `isnull`.

File: test/parse.jl [hunk 7]
```diff
@@ -199,6 +199,52 @@ macro f(args...) end; @f ""
 @test parse(Int,'3') == 3
 @test parse(Int,'3', 8) == 3
 
+# Issue 20587
+for T in vcat(subtypes(Signed), subtypes(Unsigned))
+    for s in ["", " ", "  "]
+         # Without a base (handles things like "0x00001111", etc)
```
Comment (nalimilan) [inline test/parse.jl]: Remove one space here.

File: test/parse.jl [hunk 8]
```diff
@@ -199,6 +199,52 @@ macro f(args...) end; @f ""
...
+                @test exception_with_base.msg == "input string only contains whitespace"
+            end
+        else
+            @test exception_with_base.msg == "input string is empty or only contains whitespace"
+        end
+    end
+
+    # Test `tryparse_internal` with part of a string
+    let b = "                   "
+        result = @test_throws ArgumentError get(Base.tryparse_internal(Bool, b, 7, 11, 0, true)) == true
```
Comment (nalimilan) [inline test/parse.jl]: `== true` is redundant (same below).

File: test/parse.jl [hunk 9]
```diff
@@ -199,6 +199,52 @@ macro f(args...) end; @f ""
...
+            else
+                @test exception_without_base.msg == "input string only contains whitespace"
+            end
+        else
+            @test exception_without_base.msg == "input string is empty or only contains whitespace"
+        end
+
+        # With a base
+        result = @test_throws ArgumentError parse(T, s, 16)
+        exception_with_base = result.value
```
Comment (nalimilan) [inline test/parse.jl]: I would find it clearer to always access `result.value` instead of defining `exception_with_base` (same below).

Comment (H-225) [inline test/parse.jl]: I defined them separately so that it reminds you they are exceptions, and so that in the test-failed message you see which one it was, since let-expressions obscure the line number.

File: test/parse.jl (hunk 7 above)
Comment (H-225) [inline test/parse.jl]: Sorry - from where?

**Comment by H-225** [comment]
So, the old parsing code for integers was forgiving of leading and trailing whitespace.
The old boolean parsing code was not.

My new integer parsing code is _also_ forgiving of whitespace.
My new boolean parsing code is _not_.

Shall I make them _both_ forgiving of it?

**Review by JeffBezanson — APPROVED** [review]

**Comment by tkelman** [comment]
either both should allow whitespace or neither should - maybe the latter if it's possible to get any performance benefits from that

**Comment by H-225** [comment]
@tkelman 
With some naive benchmarking, it takes about 1ms more time to be forgiving of whitespace in both cases.
It also seems that float parsing is _also_ forgiving of whitespace.
