### PR TITLE
Fix #10959 bugs with UTF-32 conversions

### LINKED ISSUE #10959: Poor performance (and excessive garbage collection) in utf8/utf16/utf32 conversion functions
These all tend to be rather slow because they create an empty array, and append to it 1 character at a time... also, instead of having specific converters for things like:
ASCIIString -> UTF16String, UTF8String -> UTF16String, UTF32String -> UTF16String
ASCIIString -> UTF32String, UTF8String -> UTF32String, UTF16String -> UTF32String
these are handled by a single generic function (encode16 for UTF16String)

### PR DESCRIPTION
**Pull request by ScottPJones**
Added new `convert` methods that use the `check_string` function to validate input
Added tests for many sorts of valid/invalid data
Depends on PR #11551 and #11575

### CODE REVIEW

File: base/utf16.jl [hunk 1]
```diff
@@ -1,9 +1,33 @@
...
-utf16_is_surrogate(c::UInt16) = (c & 0xf800) == 0xd800
-utf16_get_supplementary(lead::UInt16, trail::UInt16) = Char(UInt32(lead-0xd7f7)<<10 + trail)
+# Quickly copy and set trailing \0
+@inline function fast_utf_copy{S <: Union(UTF16String, UTF32String), T <: Union(UInt16, Char)}(::Type{S}, ::Type{T}, len, dat, flag::Bool=false)
+     @inbounds return flag ? S(setindex!(copy!(Vector{T}(len+1),1,dat,1,len),0,len+1)) : S(setindex!(copy!(Vector{T}(len), dat), 0, len))
+end
+
+# Get rest of character ch from 3-byte UTF-8 sequence in dat
+@inline function get_utf8_3byte(dat, pos, ch)
+    @inbounds return ((ch & 0xf) << 12) | (UInt32(dat[pos-1] & 0x3f) << 6) | (dat[pos] & 0x3f)
```
Comment (nalimilan) [inline base/utf16.jl]: Probably, the `@inbounds` declaration should be in the caller? From inside the function, you cannot be sure that the index is correct, and from the caller, you don't know that the function assumes this.

(Also, missing new line before next function.)

File: base/utf16.jl [hunk 2]
```diff
@@ -20,92 +44,254 @@ function endof(s::UTF16String)
...
+            return false
+        else
+            i += 1
+        end
+    end
+    return i > n || !is_surrogate_codeunit(data[i])
+end
+
+function convert(::Type{UTF16String}, str::AbstractString)
+"
```
Comment (nalimilan) [inline base/utf16.jl]: Isn't the convention to put docs before the function, rather than inside it? (Or has anybody asked you to change this? :-)

Also, AFAICT this syntax actually creates a string object in the function, which isn't needed at all in that context.

**Comment by tkelman** [comment]
Just wondering, is there any really good reason we really need a UTF32 type in base instead of as a package? Is it actually commonly used at all?

**Comment by quinnj** [comment]
@tkelman, if I remember correctly there are some OSX libraries that only deal with UTF32, (I know iODBC is that way as an example), so I think that was one of the motivations for including (plus the fact that we already support UTF8 and UTF16 and there are no other packages for different string encodings yet).

File: base/utf16.jl (hunk 2 above)
Comment (hayd) [inline base/utf16.jl]: Also, strings should be """ and the top line should not be indented (otherwise it's read as a codeblock).

(Aside: Indentation is preserved after lists which is probably a bug.)

Comment (ScottPJones) [inline base/utf16.jl]: @hayd I've already brought up the fact that @doc strings are not allowed for most of the code in Base.
""" strings are not even supported, nor are enumerations.   If you program in Base, you need to be careful of what
has already been defined.  (Note: I have a local branch where I've gotten """ to work, at least early enough for my
changes to the `utf*` files.
@nalimilan How will the string be associated correctly with the method? There is no `@doc` macro with `->` to make that association at that point in Base.
Have you used Python?  Having """ as a specially formatted string constant seems to be taken directly from Python.  Python docstrings are placed as the first expression in a function.
If bare strings are going to be picked up for documentation, why would you want to have it before the function, instead of in it?  That's just inventing a new style for documentation, instead of using what many people are already very familiar with.

What string object?  It's not assigned to anything, passed as an argument, nor returned.  Julia optimizes it away totally.
```julia
julia> function foobar()
       "this is a test"
       0
       end

	.section	__TEXT,__text,regular,pure_instructions
Filename: none
Source line: 0
	pushq	%rbp
	movq	%rsp, %rbp
	xorl	%eax, %eax
Source line: 3
	popq	%rbp
	retq
```

Comment (hayd) [inline base/utf16.jl]: The top-line indentation and moving it above the function definition stand.

You can say we were wrong: "The string is compiled away" and "we don't have """ at this stage in Base". Please be concise.

**Comment by ScottPJones** [comment]
Any library where the C compiler uses wchar_t is defined as char32_t... you absolutely need UTF32 support in Base.
Note, nothing *fancy* needs to be in Base, for UTF16 or UTF32, just basic string operations, conversions, and validation...

File: base/utf16.jl (hunk 2 above)
Comment (nalimilan) [inline base/utf16.jl]: I didn't say it would get associated with the method, just that in places where `@doc` is supported, the [string must appear *before* the function](http://docs.julialang.org/en/latest/manual/documentation/). So I don't see the point of putting it after if it doesn't match that convention. What Python does is irrelevant here -- if you want to discuss how Julia/Docile.jl docs should work, open another issue.

Why not just use `#` comments? That's as close as the Docile.jl system as your current solution, and it's closer to the existing docs (yes, there are some, though they are usually short).

Comment (ScottPJones) [inline base/utf16.jl]: What do you mean?
>The top-line indentation and moving it above the function definition stand.

File: base/utf16.jl (hunk 1 above)
Comment (ScottPJones) [inline base/utf16.jl]: I didn't know I could do that... plus I'd intended those to be private functions, only called inside the conversion or validation code.

Comment (nalimilan) [inline base/utf16.jl]: > I'd intended those to be private functions, only called inside the conversion or validation code.

Yeah, but if you can make it safer, better do it. Heard of this recent story about the `sector_div` kernel macro doing things people wouldn't expect when they were not experts of that part of the code? http://lwn.net/Articles/645720/

**Comment by tkelman** [comment]
> Any library where the C compiler uses wchar_t is defined as char32_t... you absolutely need UTF32 support in Base.

Not if we don't use any of those libraries for any other code in base. My question is could you copy-paste all code related to UTF32 types, move it to a package, and have everything else continue to work equally well? My hypothesis is yes (grepping base and my `~/.julia` for `UTF32String` shows very very few matches). And it would only be a disruptive change for packages that need to interface to such libraries, of which there don't look to be very many. If this type is rarely used in practice, I'm not sure it's worth hundreds of lines of specialized code to deal with it.

**Comment by tknopp** [comment]
This does not answer Tonys question:

> Is it actually commonly used at all?

So, how many Julia packages use it?

**Comment by ScottPJones** [comment]
@tkelman I'm afraid that is totally off topic.   `UTF32String` is currently in Base, and if you want to see about having moved out of base, you should raise an issue about it.
What does whether or not core code calls a library using wchar_t, have to do with the fact that being able to access C/C++ libraries is part of the core functionality of Julia?

**Comment by tkelman** [comment]
This PR is still nearly as large as the original one. It'll get smaller if the separate validation and UTF16 PR's get merged and this one gets rebased to not count those changes, but for the UTF32 type in particular the benefit vs code size tradeoff is really not self-evident.

But looking now at how the `Cwstring` type works, it would probably be messy and not worth trying to move `UTF32String` out of base. So nevermind on that, but this PR could still stand to aim for generality over verbosity in the code.

File: base/utf16.jl (hunk 2 above)
Comment (hayd) [inline base/utf16.jl]: *If* you go with the "Docile without `@doc`" syntax. Then

\1. The docstring should be *above* the function (optionally start/end with a new line):
```
"docstring"
function foo() ...
```

\2. If you indent four spaces or more then it's read as a Code block. e.g.

```
"
    Converts an AbstractString to a UTF16String
"
```
is read as a code block:

    Converts an AbstractString to a UTF16String

Which is not what you want.

**Comment by ScottPJones** [comment]
@tkelman This isn't anything as large!  Just two files modified, 246 net new lines, over half of those documentation, and 50 were testing,  This PR is set up so that any review (of this part) can be done, without having to wait until first #11575 and then #11551 are merged in, and since I was told to split things into smaller, more manageable chunks.

**Comment by ScottPJones** [comment]
The updates to the comments are now in, as requested.

**Comment by ScottPJones** [comment]
Updated again, ready to go after #11575 and #11551 get merged (if they do!)

File: base/utf16.jl (hunk 1 above)
Comment (ScottPJones) [inline base/utf16.jl]: Yep, I changed those, thanks...

**Comment by ScottPJones** [comment]
OK, this has now been rebased since #11551 just got merged in.  Please take a look!  Thanks!

File: base/utf32.jl [hunk 3]
```diff
@@ -5,25 +5,239 @@ next(s::UTF32String, i::Int) = (s.data[i], i+1)
...
+"
+Converts a UTF-32 encoded vector of `UInt32` to a `UTF8String`
+
+### Returns:
+*   `UTF8String`
+
+### Throws:
+*   `UnicodeError`
+"
+function convert(::Type{UTF8String}, dat::Vector{UInt32})
```
Comment (tkelman) [inline base/utf32.jl]: this method doesn't belong here, it has all the same issues that `convert(::Type{UTF8String}, dat::Vector{UInt16})` had in the other PR

File: base/utf32.jl [hunk 4]
```diff
@@ -5,25 +5,239 @@ next(s::UTF32String, i::Int) = (s.data[i], i+1)
...
+"
+Converts a UTF-32 encoded vector of `UInt32` to a `UTF16String`
+
+### Returns:
+*   `::UTF16String`
+
+### Throws:
+*   `UnicodeError`
+"
+function convert(::Type{UTF16String}, dat::Vector{UInt32})
```
Comment (tkelman) [inline base/utf32.jl]: same here - there should not be conversions between vectors of integers and string types that have different bit widths

Comment (ScottPJones) [inline base/utf32.jl]: I knew you'd be bothered by that, however, those are necessary to handle `Vector{Char}` to `UTF8String` and `Vector{Char}` to `UTF16String`

Comment (tkelman) [inline base/utf32.jl]: Then these should explicitly be the methods for the conversions they are needed by, not for vectors of integers. If exactly this conversion is needed by code outside of base, it should do the reinterpret the other direction to `Char` instead of to integer.

**Comment by ScottPJones** [comment]
@tkelman Those have been removed, hopefully the added reinterpret and new variable won't slow things down. 0 lines saved, 2 one line convert with reinterpret removed, 1 line added to 2 methods.

File: base/utf32.jl [hunk 5]
```diff
@@ -5,25 +5,239 @@ next(s::UTF32String, i::Int) = (s.data[i], i+1)
...
+"
+Converts a vector of `Char` to a `UTF8String`
+
+### Returns:
+*   `UTF8String`
+
+### Throws:
+*   `UnicodeError`
+"
+function convert(::Type{UTF8String}, chrs::Vector{Char})
```
Comment (tkelman) [inline base/utf32.jl]: seems as though this method belongs in `utf8.jl`, and `convert(::Type{UTF16String}, chrs::Vector{Char})` belongs in `utf16.jl` ?

File: base/utf32.jl [hunk 6]
```diff
@@ -5,25 +5,239 @@ next(s::UTF32String, i::Int) = (s.data[i], i+1)
...
+function convert(::Type{UTF32String}, str::AbstractString)
+    len, flags = unsafe_checkstring(str)
+    buf = Vector{Char}(len+1)
+    out = 0
+    @inbounds for ch in str ; buf[out += 1] = ch ; end
+    @inbounds buf[out + 1] = 0 # NULL termination
+    UTF32String(buf)
+end
+
+convert(::Type{UTF8String},  dat::Vector{Char})   = convert(UTF8String, reinterpret(UInt32, dat))
```
Comment (nalimilan) [inline base/utf32.jl]: This method is the same as the one below now that you changed its signature.

File: base/utf32.jl (hunk 5 above)
Comment (ScottPJones) [inline base/utf32.jl]: They depend on knowledge of UTF-32 encoding, hence here is best.

File: base/utf32.jl (hunk 6 above)
Comment (ScottPJones) [inline base/utf32.jl]: Which are the same?  convert from a `Vector{Char}` is not the same as convert from UTF32String, due to the trailing 0 word in UTF32String.

File: base/utf32.jl (hunk 5 above)
Comment (nalimilan) [inline base/utf32.jl]: Doesn't sound like a good argument to me. Better organize code logically based on the types it acts on, rather than by required skills. You typically don't think "I'm good at UTF-32, I'm going to work on all places where it's used in Julia", but rather "I need to fix a bug with `UTF8String`, let's see where this code lives".

File: base/utf32.jl (hunk 6 above)
Comment (tkelman) [inline base/utf32.jl]: As I commented, you have two methods with the exact same signature `convert(::Type{UTF8String},  dat::Vector{Char})`

Comment (tkelman) [inline base/utf32.jl]: had, looks like you just fixed it

File: base/utf32.jl (hunk 5 above)
Comment (ScottPJones) [inline base/utf32.jl]: I didn't mean a human knowledge of UTF-32 encoding, I meant that logically, UTF32String is essentially a Vector{Char}, so the functions dealing with them seemed to belong here.
The functions to deal with these were here originally also, I didn't think I should change that organization.  If you all feel that reorganization is necessary, that is outside the scope of this PR.

File: base/utf32.jl (hunk 6 above)
Comment (ScottPJones) [inline base/utf32.jl]: Yeah, just a typo from bouncing back and forth between this and deprecating stuff.

**Comment by ScottPJones** [comment]
This did pass 2 out of 3 on travis, something about prebuild rebuild expired on the one that failed, doesn't seem to have anything to do with the change.

**Comment by tkelman** [comment]
hm, assertion failure on osx travis `Assertion failed: (bp), function jl_deserialize_value, file dump.c, line 1019.
/Users/travis/build.sh: line 41: 10005 Abort trap: 6           /tmp/julia/bin/julia -J local.ji -e 'true'`

**Comment by ScottPJones** [comment]
Do you think that has anything to do with the change?  This had been having passing builds on all platforms, and there have been other changes I thought in the low-level code recently.
I'm testing on a Mac myself, and haven't seen any assertion failures.

**Comment by ScottPJones** [comment]
Have the issues with travis been resolved, so that the testing can be restarted on this?
The one test out of 4 that failed had to so with dealing with the .ji files, where there has been a lot of changes recently, it doesn't seem likely that it has anything to do with UTF-32 conversions.

**Comment by ScottPJones** [comment]
Bump.  This has passed all tests, I've moved things how @nalimilan suggested, this would also add some more coverage for string testing.

**Comment by ScottPJones** [comment]
Ugh! This failed because spawn doesn't seem to be working on a  JULIA_CPU_CORES == 1 build

**Comment by ScottPJones** [comment]
Ok, all green again!

**Comment by ScottPJones** [comment]
Bump: this has been essentially unchanged for over a month (just removal of a method, and moving two methods to utf8.jl and utf16.jl).  The external problems causing Travis or Appveyor problems also seem to have been fixed.

**Comment by ScottPJones** [comment]
Bump: Any further issues with getting these bug fixes and increased testing in?

**Comment by tkelman** [comment]
You still never really addressed the initial feedback of having too many specialized code paths for a not-very-convincing benefit. Many many times it has been asked whether you had a representative application or stand-in skeleton of one that spends a substantial amount of time in conversion to or from UTF32, and whether you can accomplish the bug fixes in a generic way without needing separate methods for every possible combination.

**Comment by ScottPJones** [comment]
If you just search for `UTF32String`, you won't find that much, but there are many calls that use `Cwstring`.
It has already been discussed here that `Cwstring` is `UTF32String` for non-Windows platforms, which seems to me to make handling `UTF32String` correctly fairly important.
This already is about as generic as it could be, fixes bugs in code that is already in Base, and adds much needed unit testing to show that those bugs are indeed fixed.

File: base/unicode/utf8.jl [hunk 7]
```diff
@@ -238,6 +238,67 @@ function convert(::Type{UTF8String}, a::Array{UInt8,1}, invalids_as::AbstractStr
...
+Converts an already validated vector of `UInt16` or `UInt32` to a `UTF8String`
+
+### Input Arguments:
+* `dat` Vector of code units (`UInt16` or `UInt32`), explicit `\0` is not converted
+* `len` length of output in bytes
+
+### Returns:
+* `UTF8String`
+"
+function encode_to_utf8{T<:Union{UInt16, UInt32}}(::Type{T}, dat, len)
```
Comment (jakebolewski) [inline base/unicode/utf8.jl]: @ScottPJones do you have plans to use this function somewhere?  Otherwise why not include it as part of the convert method?

Comment (jakebolewski) [inline base/unicode/utf8.jl]: Nevermind, I see it is used in the uft32 conversion code.

File: base/unicode/utf16.jl [hunk 8]
```diff
@@ -195,44 +195,52 @@ function convert(::Type{UTF8String}, str::UTF16String)
...
-Converts an already validated vector of `UInt16` or `UInt32` to a `UTF8String`
+Converts a vector of `Char` to a `UTF16String`
+
+### Returns:
+*   `::UTF16String`
+
+### Throws:
+*   `UnicodeError`
+"
+function convert(::Type{UTF16String}, chrs::Vector{Char})
```
Comment (tkelman) [inline base/unicode/utf16.jl]: Same situation as all the previous PR's, this is a conversion from a vector to a string that's based on a different element type, and shouldn't be here. Neither should `convert(::Type{UTF8String}, ::Vector{Char})`.

**Comment by jakebolewski** [comment]
@tkelman I don't find that argument very convincing.  If we are going to support multiple string types, there is unavoidable complexity in inter-converting between multiple representations.

lgtm

**Comment by tkelman** [comment]
Fine, though the vector-to-string conversions with mismatched element types are breaking the abstraction and should be deleted. I also couldn't find a single instance of `Cwstring` in any package that I use, aside from Compat.

**Comment by jakebolewski** [comment]
Yes, but instead of the back and forth why don't we just fix it now and move on?

**Comment by tkelman** [comment]
I'm about to.
