### PR TITLE
Replace realpath implementation with libuv

### LINKED ISSUE #32298: realpath error: The operation completed successfully
```julia
julia> realpath("\\\\.\\C:")
ERROR: SystemError: realpath: The operation completed successfully.
Stacktrace:
 [1] #windowserror#45(::Nothing, ::typeof(Base.windowserror), ::Symbol, ::Bool) at .\error.jl:148
 [2] windowserror at .\error.jl:148 [inlined]
 [3] realpath(::String) at .\path.jl:351
 [4] top-level scope at REPL[39]:1
```

sure it did...

Julia Version 1.3.0-DEV.390
Commit c630477c4e6 (2019-06-11 10:36 UTC)
OS: Windows (i686-w64-mingw32)

### LINKED ISSUE #32597: realpath error on Windows network folder
`realpath` fails on Windows when resolving the full UNC path in certain cases.  I suspect it's happen when the server folder is a sub-directory of a locked folder.

A non-locked folder works just fine, in this case "Shared" is not locked.
```
realpath("J:\\")
"UNC\\ServerName\Shared\\"
```

In the case of a locked folder it errors, in this case "Home" is a locked folder, and the expected return should be `"UNC\\ServerName\Home\Username"`.

```
realpath("H:\\")
ERROR: SystemError: realpath: The operation completed successfully.
Stacktrace:
 [1] #windowserror#45(::Nothing, ::typeof(Base.windowserror), ::Symbol, ::Bool) at .\error.jl:148
 [2] windowserror at .\error.jl:148 [inlined]
 [3] realpath(::String) at .\path.jl:351
 [4] top-level scope at REPL[30]:1
```

From what I understand, on Windows Server the contents of a locked folder are only viable to the Administrator, but sub-folders can still be viewed with the proper permissions.  It is done so that other users can't discover the existence of sub-directories.

The underlying library and function was changed per discussion in #30588.  See also #32298.

### LINKED ISSUE #33127: realpath gives wrong path for network drives on windows with 1.2
See also discussion over at JuliaLang/Pkg.jl#1328 and JuliaDynamics/DrWatson.jl#82

For network drives `realpath` returns a wrong path.
```
julia> realpath("Z://")
"UNC\\Mac\\Home\\"

julia> realpath("C://")
"C:\\"
```

Tested on:
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
It's this call:
```
 349 len = ccall(:GetFinalPathNameByHandleW, stdcall, UInt32, (Int, Ptr{UInt16}, UInt32, UInt32),
 350                              h, buf, (oldlen=len)-1, 0x0)
```
with `buf` being
```
1|julia> transcode(String,buf)
"\\\\?\\UNC\\Mac\\Home\\\ .... garbage due to length not being corrected"
```

### PR DESCRIPTION
**Pull request by musm**
fixes #32597 fixes #32298 fixes #33127

### CODE REVIEW

File: base/path.jl [hunk 1]
```diff
@@ -338,28 +338,6 @@ abspath(a::AbstractString, b::AbstractString...) = abspath(joinpath(a,b...))
...
-    try
-        buf = Vector{UInt16}(undef, 256)
-        oldlen = len = length(buf)
-        while len >= oldlen
-            len = ccall(:GetFinalPathNameByHandleW, stdcall, UInt32, (Int, Ptr{UInt16}, UInt32, UInt32),
-                            h, buf, (oldlen=len)-1, 0x0)
-            windowserror(:realpath, iszero(len))
-            resize!(buf, len) # strips NUL terminator on last call
-        end
-        if 4 < len < 264 && 0x005c == buf[1] == buf[2] == buf[4] && 0x003f == buf[3]
```
Comment (vtjnash) [inline base/path.jl]: I seem to recall that libuv is missing the length check, but otherwise lgtm

**Comment by musm** [comment]
`realpath` on master throws `SystemError` whereas this changes it to `Base.IOError` which seems more logical.

File: base/path.jl (hunk 1 above)
Comment (musm) [reply base/path.jl]: You mean a max path type length check? I don't think I see that this is an issue.

**Comment by musm** [comment]
filewatching failure on win32 and another fluke on freebsd

File: base/path.jl (hunk 1 above)
Comment (stevengj) [reply base/path.jl]: libuv [doesn't check that `len > 4`](https://github.com/libuv/libuv/blob/813264add0c3b5fba782e4bb849bffad4701ecf6/src/win/fs.c#L2496-L2498), but since it uses `wcsncmp` (which stops at NUL chars) it should be fine there.  It doesn't check `len < 264` either, but I guess excluding actual paths with length > 263 that start with `\\?\` is less of a practical concern?

Comment (musm) [reply base/path.jl]: Paths that start with `\\?\` are extended paths and  can extend up to 32 767 characters

**Comment by musm** [comment]
merge?

**Review by stevengj — APPROVED** [review]
