### PR TITLE
Fixup `hash(::Real)` broken by #49996

### LINKED ISSUE #50065: hash(BigFloat) broken after #49996
```julia> versioninfo()
Julia Version 1.10.0-DEV.1428
Commit 19610191c8 (2023-06-02 14:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.5.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> hash(1.0) == hash(BigFloat(1.0))
false
```

@LilithHafner

### PR DESCRIPTION
**Pull request by LilithHafner**
I mishandled nonzero `pow` returned by `decompose(::BigFloat)`.

Fixes #50065 and adds a test

### CODE REVIEW

File: test/hashing.jl [hunk 1]
```diff
@@ -310,3 +310,6 @@ struct AUnionParam{T<:Union{Nothing,Float32,Float64}} end
 @test Type{AUnionParam{<:Union{Nothing,Float32,Float64}}} === Type{AUnionParam}
 @test Type{AUnionParam.body}.hash == 0
 @test Type{Base.Broadcast.Broadcasted}.hash != 0
+
+# Issue #50065
+@test hash(1.0) == hash(BigFloat(1.0))
```
Comment (oscardssmith) [inline test/hashing.jl:315]: add `1//1` and `big(1)` for good measure.

Comment (LilithHafner) [reply test/hashing.jl]: I think it makes sense to add BigFloat and BigInt to the massive cross-product at the top instead.

**Comment by LilithHafner** [comment]
My justification for changing the collisions bound and comment describing it is that the comment is misleading. 
```julia
julia> collides = [];

julia> for T = types, S = types, x = vals
           a = coerce(T, x)
           b = coerce(S, x)
           eq = hash(a) == hash(b)
           #println("$(typeof(a)) $a")
           #println("$(typeof(b)) $b")
           if isequal(a, b)
               @test eq
           elseif eq
               push!(collides, (a,b)) 
           end
       end
       # each pair of types has one collision for these values

julia> using StatsBase; countmap(typeof.(collides))
Dict{DataType, Int64} with 40 entries:
  Tuple{UInt64, Int8}                      => 2
  Tuple{UInt64, Rational{Int16}}           => 2
  Tuple{Rational{Int8}, Rational{UInt64}}  => 2
  Tuple{Float32, Rational{UInt64}}         => 9
  Tuple{Float64, Rational{UInt64}}         => 14
  ⋮                                        => ⋮
```

On average, each pair of types has 0.947 collisions. Adding BigFloat and BigInt increases this average to 1.076. The new bound is exactly the number of current collisions.

**Comment by LilithHafner** [comment]
New tests on this PR unearthed https://github.com/JuliaLang/julia/issues/50075. I'm going to skip BigInt tests for now.

File: test/hashing.jl (hunk 1 above)
Comment (oscardssmith) [reply test/hashing.jl]: well I'm sure glad I suggested testing `BigInt` :)

**Comment by oscardssmith** [comment]
Sounds good. https://github.com/JuliaLang/julia/pull/50076 should fix that part of this.

**Comment by LilithHafner** [comment]
Test failure looks unrelated
