### PR TITLE
Fix relocation verification code

### LINKED ISSUE #296: FATAL ERROR: Symbol "__cxxjl_personality_v0"not found
All C++ function calls give the following error
```jl
C++ > 1+1
FATAL ERROR: Symbol "__cxxjl_personality_v0"not found
signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 5203384 (Pool: 5202226; Big: 1158); GC: 7
[1]    4602 abort      ~/julia-dev/julia
```
I'm on
```
julia> versioninfo()
Julia Version 0.6.0-dev.885
Commit 86b1e53* (2016-10-04 21:57 UTC)
DEBUG build
Platform Info:
  OS: macOS (x86_64-apple-darwin16.1.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.0 (ORCJIT, haswell)
```
and master version of `Cxx.jl`.

### PR DESCRIPTION
**Pull request by Keno**
The code needs to use the mangled name in order to find symbols. On OS X,
mangling adds an underscore, while on linux mangling does nothing. Since
this verification code only exists when assertions are turned on, not
many people have run into this (since it's a bug in the verification,
not actually indicative of a problem).

Nevertheless, fixes https://github.com/Keno/Cxx.jl/issues/296.

### CODE REVIEW

**Comment by vtjnash** [comment]
Lgtm

File: test/llvmcall.jl [hunk 1]
```diff
@@ -143,6 +143,16 @@ function confuse_declname_parsing()
...
+# Test for proper mangling of external (C) functions
+function call_jl_errno()
+    llvmcall(
+    (""" declare i32 @jl_errno()""",
+    """
+    %r = call i32 @jl_errno()
+    ret i32 %r
+    """),Int32,Tuple{})
+end
+call_jl_errno()
```
Comment (tkelman) [inline test/llvmcall.jl]: should the result be tested?

Comment (Keno) [inline test/llvmcall.jl]: No the result is meaningless. jl_errno is just a convenient exported function with a simple signature.
