### PR TITLE
Fix offset LinearIndices range indexing (fixes #27986)

### LINKED ISSUE #27986: Offset arrays indexing of indexes bug
I found some questionable behavior regarding indices of `OffsetArray`s.

```
julia> include("test/TestHelpers.jl")
Main.TestHelpers

julia> using Main.TestHelpers.OAs

julia> a = [11,12,13]
3-element Array{Int64,1}:
 11
 12
 13

julia> b = OffsetArray(a, (-3,))
OffsetArray{Int64,1,Array{Int64,1}} with indices -2:0:
 11
 12
 13

julia> i = LinearIndices(b)
LinearIndices{1,Tuple{Base.Slice{UnitRange{Int64}}}} with indices -2:0:
 -2
 -1
  0

julia> i[-2]
-2

julia> i[-2:end]
-5:-3
```
I suspect this is a bug. Because these are a `Slice` I feel the scalar `getindex` behavior is correct and the behavior [here](https://github.com/JuliaLang/julia/blob/master/base/indices.jl#L374) is wrongly assuming 1-based indexing.

### PR DESCRIPTION
**Pull request by timholy**
CC @andyferris 

Fixes #27986.

### CODE REVIEW

File: base/indices.jl [hunk 1]
```diff
@@ -364,14 +364,14 @@ IndexStyle(::Type{<:LinearIndices}) = IndexLinear()
 axes(iter::LinearIndices) = map(indices1, iter.indices)
 size(iter::LinearIndices) = map(unsafe_length, iter.indices)
 function getindex(iter::LinearIndices, i::Int)
-    @_inline_meta
+    @_propagate_inbounds_meta
```
Comment (mbauman) [inline base/indices.jl]: Propagate inbounds should only be needed if this function itself calls `getindex` — I think `@inline` should be correct here.  Did you see this make a difference?

**Review by mbauman — APPROVED** [review]
Thanks for the fix!

File: base/indices.jl (hunk 1 above)
Comment (timholy) [reply base/indices.jl]: Ah, you're right, I am rusty on that machinery. Will correct. Thanks for looking!

**Review by andyferris — APPROVED** [review]
