### PR TITLE
serialize kwftypes via their real type

### LINKED ISSUE #16471: Precompiling Bio.jl crashed on recent master branch.
Precompiling the master branch of Bio.jl package crashes with segmentation fault. This is reproducible both on OSX and on Linux (logs of Travis CI are here: https://travis-ci.org/BioJulia/Bio.jl/jobs/131278787, https://travis-ci.org/BioJulia/Bio.jl/jobs/131278801). This is also reproducible on my local machine (https://github.com/BioJulia/Bio.jl/issues/191). The smallest reproducing code would be:
```julia
julia> Pkg.clone("https://github.com/BioJulia/Bio.jl.git")

julia> using Bio
```

When I disabled precompile with `--compilecache=no` flag, the Bio module was successfully loaded.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #16471

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Awesome. Relieved to have this fixed.

File: test/compile.jl [hunk 1]
```diff
@@ -20,16 +20,28 @@ try
...
+              module Bar
+                  @doc "bar function" bar(x) = x + 2
+                  include_dependency("bar.jl")
+              end
+
+              # test that types and methods get reconnected correctly
+              # issue 16529 (adding a method to a type with no instances)
+              (::Task)(::UInt8, ::UInt16, ::UInt32) = 2
+
+              # issue 16471 (capturing references to an kwfunc)
```
Comment (tkelman) [inline test/compile.jl]: a

File: src/dump.c [hunk 2]
```diff
@@ -529,6 +529,20 @@ static void jl_serialize_datatype(ios_t *s, jl_datatype_t *dt)
         tag = 4;
     else if (dt == jl_uint8_type)
         tag = 8;
+
+    if (strncmp(jl_symbol_name(dt->name->name), "#kw#", 4) == 0) {
+        /* XXX: yuck, but the auto-generated kw types from the serializer isn't a real type, so we *must* be very careful */
+        assert(tag == 0 || tag == 5 || tag == 6);
```
Comment (tkelman) [inline src/dump.c]: are the meanings of these tags written down anywhere? should give them names instead of magic numbers
