### PR TITLE
Fix thread-safety violation in Allocations Profiler: Create a new per-thread backtrace buffer in ptls

### LINKED ISSUE #44099: allocation profiler not threadsafe
@vtjnash pointed out this thread safety bug not caught by our tests: https://github.com/JuliaLang/julia/pull/42768#discussion_r803097408

This can result in multiple threads corrupting the stack traces from each others' allocs, leading to a corrupted profile.

Fix involves keeping a buffer per thread.
EDIT: And/or maybe reusing the existing backtrace buffer in the `ptls` object. (See the linked thread, above)

cc @NHDaly

### PR DESCRIPTION
**Pull request by NHDaly**
Another approach to fix https://github.com/JuliaLang/julia/issues/44099. 

This is an alternative approach to https://github.com/JuliaLang/julia/pull/44114, but it creates a separate per-thread allocations backtrace buffer, to avoid potential sharing issues.

CC: @vilterp

### CODE REVIEW

**Comment by vilterp** [comment]
Nice thanks. I’m a bit more comfortable with this, but need more input 🤷‍♂️

**Comment by NHDaly** [comment]
Yeah, same here. Would be happy to get input from someone else, like @vtjnash or @vchuravy. Otherwise, i'd prefer this approach too, i think

File: src/gc-alloc-profiler.cpp [hunk 1]
```diff
@@ -49,15 +49,22 @@ jl_combined_results g_combined_results; // Will live forever.
 // === stack stuff ===
 
 jl_raw_backtrace_t get_raw_backtrace() JL_NOTSAFEPOINT {
-    // A single large buffer to record backtraces onto
-    static jl_bt_element_t static_bt_data[JL_MAX_BT_SIZE];
+    // We first record the backtrace onto a MAX-sized buffer, so that we don't have to
+    // allocate the buffer until we know the size. To ensure thread-safety, we use a
+    // per-thread backtrace buffer.
+    jl_ptls_t ptls = jl_current_task->ptls;
+    jl_bt_element_t *shared_bt_data_buffer = ptls->profiling_bt_buffer;
```
Comment (vtjnash) [inline src/gc-alloc-profiler.cpp:56]:
```suggestion
    jl_bt_element_t *shared_bt_data_buffer = ptls->profiling_bt_buffer;
    if (shared_bt_data_buffer == NULL)
        ptls->profiling_bt_buffer = shared_bt_data_buffer = \
                malloc_s(sizeof(jl_bt_element_t) * (JL_MAX_BT_SIZE + 1));
```

File: src/gc-alloc-profiler.cpp [hunk 2]
```diff
@@ -49,15 +49,22 @@ jl_combined_results g_combined_results; // Will live forever.
...
 
     // Then we copy only the needed bytes out of the buffer into our profile.
     size_t bt_bytes = bt_size * sizeof(jl_bt_element_t);
     jl_bt_element_t *bt_data = (jl_bt_element_t*) malloc(bt_bytes);
-    memcpy(bt_data, static_bt_data, bt_bytes);
+    memcpy(bt_data, shared_bt_data_buffer, bt_bytes);
+
+    // Now, "clear" the ptls buffer, so that this buffer isn't incorrectly rooting objects
+    // in that buffer.
+    ptls->bt_size = 0;
```
Comment (vtjnash) [inline src/gc-alloc-profiler.cpp:67]: doesn't look like you are rooting this anyways
```suggestion
```

Comment (vtjnash) [reply src/gc-alloc-profiler.cpp:67]: Though since it is not being rooted upon return, you need to avoid examining the `jl_pgcstack` in the `rec_backtrace`

File: src/gc-alloc-profiler.cpp (hunk 1 above)
Comment (NHDaly) [reply src/gc-alloc-profiler.cpp:56]: oops - yes, thank you! We discussed doing exactly this yesterday, but i forgot to get to it. 🙏

File: src/gc-alloc-profiler.cpp (hunk 2 above)
Comment (NHDaly) [reply src/gc-alloc-profiler.cpp:70]: oops yep you're totally right of course. this is leftover cruft. Thank you!

Comment (NHDaly) [reply src/gc-alloc-profiler.cpp]: > Though since it is not being rooted upon return, you need to avoid examining the `jl_pgcstack` in the `rec_backtrace`

Can you expand on this? Thanks for your help.

Comment (vtjnash) [reply src/gc-alloc-profiler.cpp]: `rec_backtrace` assumes the result is guaranteed to always be in a GC rooted buffer, so it can later be safely unpacked and examined. This does not appear to ensure that safety.

Comment (vilterp) [reply src/gc-alloc-profiler.cpp]: Hey @vtjnash  — Thanks. You're right that without rooting, some of the pointers recorded here will be unsafe to dereference later.

The problem is, even if we were to fix that problem for this buffer, the backtraces would still be immediately copied to the profiler's vector of allocations, which isn't rooted either: https://github.com/JuliaLang/julia/blob/1ad2396f05fa63a71e5842c814791cd7c7715100/src/gc-alloc-profiler.cpp#L30

So we'd have to fix it there too for these pointers to be safely unpacked and dereferenced.

We spent a bunch of time in https://github.com/JuliaLang/julia/pull/42768 trying to figure out how to root that buffer, before noticing that the CPU profiler just sidesteps this problem — it doesn't root the main buffer, and just renders stack frames it can't dereference as `unknown`. In practice, with the alloc profiler as well as the CPU profiler, there haven't been too many `unknown` frames. So, we ultimately mimicked the CPU profiler.

I filed https://github.com/JuliaLang/julia/issues/43796 to address this for both the CPU and alloc profiler — a bigger project which may involve special-casing the GC to scan both their backtrace buffers, as well as these intermediate buffers. In the meantime, I think 1.8 would be in pretty good shape if we fix this thread safety bug but not fix the few `unknown`s.

**Comment by vilterp** [comment]
Build failing with a type error; fixed in https://github.com/JuliaLang/julia/pull/44235

**Comment by IanButterworth** [comment]
Is this ready to merge?

File: src/gc-alloc-profiler.cpp [hunk 3]
```diff
@@ -49,15 +49,24 @@ jl_combined_results g_combined_results; // Will live forever.
...
+        shared_bt_data_buffer = (jl_bt_element_t*) malloc_s(size);
+        ptls->profiling_bt_buffer = shared_bt_data_buffer;
+    }
 
-    size_t bt_size = rec_backtrace(static_bt_data, JL_MAX_BT_SIZE, 2);
+    size_t bt_size = rec_backtrace(shared_bt_data_buffer, JL_MAX_BT_SIZE, 2);
 
     // Then we copy only the needed bytes out of the buffer into our profile.
     size_t bt_bytes = bt_size * sizeof(jl_bt_element_t);
     jl_bt_element_t *bt_data = (jl_bt_element_t*) malloc(bt_bytes);
```
Comment (vtjnash) [inline src/gc-alloc-profiler.cpp:67]:
```suggestion
    jl_bt_element_t *bt_data = (jl_bt_element_t*) malloc_s(bt_bytes);
```

**Review by vtjnash — APPROVED** [review]
SGTM

**Comment by KristofferC** [comment]
> I think we'll also want to backport to 1.8 as well.

It already has the label so it will get backported.

**Comment by vilterp** [comment]
@KristofferC oh I see, great; you're way ahead of me :)

**Comment by vilterp** [comment]
Thanks Sacha 🙏
