### PR TITLE
fix some macro expander issues with new 0.6 syntax

### LINKED ISSUE #21581: Macro hygiene problems with function return type and where
OK:

```julia
julia> module Foo
           macro bar()
               :(foo(x) = x; foo(1))
           end
       end
Foo

julia> Foo.@bar
1

julia> macroexpand(:(Foo.@bar))
quote 
    #3#foo(#4#x) = begin  # REPL[1], line 3:
            #4#x
        end
    #3#foo(1)
end
```

Problem:

```julia
julia> module Foo2
           macro bar()
               :(foo(x)::Int = x; foo(1))
           end
       end
Foo2

julia> Foo2.@bar
ERROR: syntax: "Foo2.x" is not a valid function argument name

julia> macroexpand(:(Foo2.@bar))
quote 
    (Foo2.foo)(Foo2.x)::Foo2.Int = Foo2.x
    (Foo2.foo)(1)
end
```

Related problems manifest in other cases:

```julia
julia> global function foo(x)::Int
       end
ERROR: syntax: invalid syntax in "global" declaration

julia> global function foo(x)
       end
foo (generic function with 1 method)
```

In general I think there are several places that need to be updated for `(function (:: ,ex ,rettype) ,body)` and `(function (where ,ex ,ex2) ,body)` syntax.

Some of the sites I identified are

macroexpand.scm
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/macroexpand.scm#L52
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/macroexpand.scm#L105
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/macroexpand.scm#L141
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/macroexpand.scm#L255
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/macroexpand.scm#L305
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/macroexpand.scm#L318

julia-syntax.scm
- https://github.com/JuliaLang/julia/blob/2d803f30ef2ca9eb143da9b32a6243d31e85aa18/src/julia-syntax.scm#L1319

I would make a PR, but I'm a little reluctant to because I don't know if simply adding cases for `where` and `::` to each of the above sites is the best solution.

### LINKED ISSUE #22026: 0.6-rc1 `where` throwing "invalid type paramer" error in macro
The following code demonstrates a problem with the new `where` syntax. Reverting to the old syntax of putting type paramers first fixes the issue:

```julia
julia> module FooModule
               macro foo(TYP)
                       quote
                               foofunction(x::Type{T}) where {T<:Number} = x
                       end
               end
               
               struct Foo end
               @foo Foo
       end
ERROR: syntax: invalid type parameter name "FooModule.T"

julia> module FooModule2
               macro foo(TYP)
                       quote
                               foofunction{T<:Number}(x::Type{T}) = x
                       end
               end
               
               struct Foo end
               @foo Foo
       end
FooModule2
```

### LINKED ISSUE #22122: lowering bug using global annotation inside a let block using where syntax
the following does not work
```julia
julia> let
       global @inline function foo(x::T) where {T}
       T
       end
       end
```
but the following does work 
```julia
julia> let
       global @inline function foo{T}(x::T)
       T
       end
       end
```

### LINKED ISSUE #22135: Syntactic erorr in one-liner definition of generated functions with where syntax
```julia
julia> @generated foo(x::T) where T = x
ERROR: invalid syntax; @generated must be used with a function definition

julia> @generated foo(x::T where T) = x
foo (generic function with 1 method)

julia> @inline foo(x::T) where T = x
foo (generic function with 1 method)

julia> @fastmath foo(x::T) where T = x
foo (generic function with 1 method)
```
Is there a particular reason why the first definition is a syntactic error?

First reported at https://discourse.julialang.org/t/one-liner-definition-of-generated-functions-with-where-syntax/3982

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #22135, fixes #22122, fixes #22026, fixes #21581 
Now also #16096

### CODE REVIEW

**Comment by fredrikekre** [comment]
This also fixes #19351:tada:

**Comment by tkelman** [comment]
The various helper functions sure could use comments describing what they're doing.

> This also fixes #19351🎉

would be good to add a test for that as well then, if not exactly covered

**Comment by JeffBezanson** [comment]
Done and done.

File: base/essentials.jl [hunk 1]
```diff
@@ -34,9 +34,17 @@ convert(::Type{Tuple{Vararg{T}}}, x::Tuple) where {T} = cnvt_all(T, x...)
...
+    isa(ex, Expr) && (ex.head === :call ||
+                      ((ex.head === :where || ex.head === :(::)) &&
+                       eventually_call(ex.args[1])))
+end
+
 macro generated(f)
     isa(f, Expr) || error("invalid syntax; @generated must be used with a function definition")
-    if f.head === :function || (isdefined(:length) && f.head === :(=) && length(f.args) == 2 && f.args[1].head == :call)
+    if f.head === :function || (isdefined(:length) && f.head === :(=) && length(f.args) == 2 &&
+                                eventually_call(f.args[1]))
```
Comment (vtjnash) [inline base/essentials.jl]: use existing `is_short_function_def` instead

**Review by vtjnash — APPROVED** [review]
