### PR TITLE
fix #23173, segfault on `@eval import $(:.)`

### LINKED ISSUE #23173: segfault on `@eval import $x` with `x = :.`
```
signal (11): Segmentation fault
while loading /home/zac/.vscode/extensions/julialang.language-julia-0.7.0-rc.5/scripts/languageserver/main.jl, in expression starting on line 27
eval_import_path_ at /home/zac/github/julia-master/src/toplevel.c:361
eval_import_path at /home/zac/github/julia-master/src/toplevel.c:430 [inlined]
jl_toplevel_eval_flex at /home/zac/github/julia-master/src/toplevel.c:510
jl_toplevel_eval_in at /home/zac/github/julia-master/src/builtins.c:496
macro expansion at /home/zac/.vscode/extensions/julialang.language-julia-0.7.0-rc.5/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:34 [inlined]
#3 at ./event.jl:73
unknown function (ip: 0x7f59c401193f)
jl_call_fptr_internal at /home/zac/github/julia-master/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/zac/github/julia-master/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/zac/github/julia-master/src/gf.c:1933
jl_apply at /home/zac/github/julia-master/src/julia.h:1424 [inlined]
start_task at /home/zac/github/julia-master/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 11642048 (Pool: 11639283; Big: 2765); GC: 26
```
The relevant code run is `@eval import $modname` at `languageserverinstance.jl`, line 34
with `modname = :.`

I can't replicate this in the REPL but has been happening with the [julia-vscode](https://github.com/JuliaEditorSupport/julia-vscode) plugin. 

We were accidentally importing the first argument of any import statement which resulted in `@eval import $(:.)` when relative module paths were used in code.

To replicate (though it doesn't occur 100% of time) you: 
1. need [vscode](url) and the plugin (install from [vsix](https://github.com/JuliaEditorSupport/julia-vscode/releases/download/v0.7.0-rc.5/language-julia-0.7.0-rc.5.vsix))
2. when installed open `~/.vscode/extensions/julialang.language-julia-0.7.0-rc.5/scripts/languageserver/packages/CSTParser`
3. open `src/CSTParser.jl` and when it is finished parsing/loading up hover over something.
4. error logs can be found from the `View: Toggle Output` command

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/parse.jl [hunk 1]
```diff
@@ -1297,3 +1297,6 @@ let ex = parse("maximum(@elapsed sleep(1) for k = 1:10)")
     @test isa(ex, Expr) && ex.head === :call && ex.args[2].head === :generator &&
         ex.args[2].args[1].head === :macrocall
 end
+
+# issue #23173
+@test_throws ErrorException eval(:(import $(:.)))
```
Comment (vtjnash) [inline test/parse.jl]: ErrorException("invalid module path")

**Review by vtjnash — APPROVED** [review]
