### PR TITLE
Fast path constants in update_julia_type only if correct type

### LINKED ISSUE #47247: Assertion `Order == AtomicOrdering::NotAtomic && !isboxed && rhs.typ == jltype` fails on some packages
Example PkgEval run: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c6440b9_vs_d0156b5/MarkdownAST.primary.log

Repro locally:

```
(jl_KaV2L5) pkg> test MarkdownAST
     Testing MarkdownAST
      Status `/tmp/jl_ojFOCg/Project.toml`
...
     Testing Running tests...
julia: /home/kc/julia/src/cgutils.cpp:1892: jl_cgval_t typed_store(jl_codectx_t&, llvm::Value*, llvm::Value*, jl_cgval_t, jl_cgval_t, jl_value_t*, llvm::MDNode*, llvm::MDNode*, llvm::Value*, bool, llvm::AtomicOrdering, llvm::AtomicOrdering, unsigned int, bool, bool, bool, bool, bool, bool, const jl_cgval_t*, const string&): Assertion `Order == AtomicOrdering::NotAtomic && !isboxed && rhs.typ == jltype' failed.

[189132] signal (6): Aborted
in expression starting at /home/kc/.julia/packages/MarkdownAST/EC78A/test/fromstdlib.jl:10
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7ff43862871a)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
typed_store at /home/kc/julia/src/cgutils.cpp:1892
emit_setfield at /home/kc/julia/src/cgutils.cpp:3628
emit_f_opfield at /home/kc/julia/src/codegen.cpp:3010
emit_call at /home/kc/julia/src/codegen.cpp:4133
emit_expr at /home/kc/julia/src/codegen.cpp:4995
emit_ssaval_assign at /home/kc/julia/src/codegen.cpp:4592
emit_stmtpos at /home/kc/julia/src/codegen.cpp:4827 [inlined]
emit_function at /home/kc/julia/src/codegen.cpp:7790
jl_emit_code at /home/kc/julia/src/codegen.cpp:8124
jl_emit_codeinst at /home/kc/julia/src/codegen.cpp:8172
jl_compile_workqueue at /home/kc/julia/src/codegen.cpp:8293
_jl_compile_codeinst at /home/kc/julia/src/jitlayers.cpp:203
jl_generate_fptr_impl at /home/kc/julia/src/jitlayers.cpp:432
jl_compile_method_internal at /home/kc/julia/src/gf.c:2158 [inlined]
jl_compile_method_internal at /home/kc/julia/src/gf.c:2099
_jl_invoke at /home/kc/julia/src/gf.c:2442 [inlined]
ijl_apply_generic at /home/kc/julia/src/gf.c:2632
jl_apply at /home/kc/julia/src/julia.h:1869 [inlined]
```

The packages that error with this are:

```
"StructTypes"
"MarkdownAST"
```

### PR DESCRIPTION
**Pull request by apaz-cli**
Fixes #47247

### CODE REVIEW

File: test/compiler/codegen.jl [hunk 1]
```diff
@@ -781,3 +781,7 @@ f_isdefined_nospecialize(@nospecialize(x)) = isdefined(x, 1)
 # Test codegen for isa(::Any, Type)
 f_isa_type(@nospecialize(x)) = isa(x, Type)
 @test !occursin("jl_isa", get_llvm(f_isa_type, Tuple{Any}, true, false, false))
+
+# Issue #47247
+f47247(a::Ref{Int64}, b::Nothing) = setfield!(a, :x, b)
+@test_throws TypeError f47247(Ref(5), nothing)
```
Comment (vtjnash) [inline test/compiler/codegen.jl:787]: needs whitespace (will fail the CI check--check your editor configuration to make it automatic)

**Review by vtjnash — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

File: test/compiler/codegen.jl [hunk 2]
```diff
@@ -781,3 +781,7 @@ f_isdefined_nospecialize(@nospecialize(x)) = isdefined(x, 1)
 # Test codegen for isa(::Any, Type)
 f_isa_type(@nospecialize(x)) = isa(x, Type)
 @test !occursin("jl_isa", get_llvm(f_isa_type, Tuple{Any}, true, false, false))
+
+# Issue #47247
+f47247(a::Ref{Int64}, b::Nothing) = setfield!(a, :x, b)
```
Comment (vtjnash) [inline test/compiler/codegen.jl:786]:
```suggestion
f47247(a::Ref{Int}, b::Nothing) = setfield!(a, :x, b)
```
```
Error in testset compiler/codegen:
Test Failed at /cache/build/default-amdci4-1/julialang/julia-master/julia-f2a768b0cb/share/julia/test/compiler/codegen.jl:787
  Expression: f47247(Ref(5), nothing)
    Expected: TypeError
      Thrown: MethodError
```
