### PR TITLE
fixed the overflow problem of powermod(x::Integer, p::Integer, m::T)

### LINKED ISSUE #48166: powermod(n, typemin(T), m) gives stack overflow.
As per the title, `powermod(n, typemin(T), m)` gives a StackOverflowError, where `T` is some Integer type.  It is because of the following line.
```
function powermod(x::Integer, p::Integer, m::T) where T<:Integer
    p < 0 && return powermod(invmod(x, m), -p, m)
    ...
end
```

The obvious solution is to add a check and deal with the usecase separately.  Not sure if adding that check is worth it, but thought I'd submit the issue regardless.

Version Info:
Julia Version 1.8.3
Commit 0434deb161* (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: 8 × Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores

### PR DESCRIPTION
**Pull request by StonerShaw**
Fixed #48166

### CODE REVIEW

**Comment by oscardssmith** [comment]
This isn't a great solution since it is type unstable and probably pretty slow. A better approach would probably be to compute `powermod(invmod(x, m) -(p÷2), m)^2 % m`

**Comment by KristofferC** [comment]
> This isn't a great solution since it is type unstable 

I don't really see the type stability issue.

**Comment by oscardssmith** [comment]
Good point. I forgot that the type of the exponent of `powermod` doesn't matter for the type of the result.

File: base/intfuncs.jl [hunk 1]
```diff
@@ -369,6 +369,7 @@ julia> powermod(5, 3, 19)
 ```
 """
 function powermod(x::Integer, p::Integer, m::T) where T<:Integer
+    p < 0 && p == typemin(typeof(p)) && return mod(powermod(invmod(x, m), -(p÷2), m)^2, m)
```
Comment (oscardssmith) [inline base/intfuncs.jl:372]: Although this for most sensible integer types it would give wrong results if `typemin(typeof(p))` is odd so it would probably be good to check for that. Also, I believe this will cause `powermod(2, big(-3), 2)` to fail since `BigInt` doesn't have `typemin` defined. The better check would probably be `p==-p` (with a comment about how this is true for typemin)

Comment (StonerShaw) [reply base/intfuncs.jl:372]: Thank you for the suggestions! I have optimized it, but I wonder is it necessary to check the typemin(typeof(p)) (in this case, it is equals to p) is even or odd. Because for the signed integers in the form of 2's complement repretation, the minimum will always be even

Comment (oscardssmith) [reply base/intfuncs.jl:372]: it  would probably not matter in practice, but the iseven(typemin(T)) should constant fold making it free, and it will prevent a really weird bug when someone calls this with a very odd integer type.

Comment (StonerShaw) [reply base/intfuncs.jl:372]: got it

File: base/intfuncs.jl [hunk 2]
```diff
@@ -369,8 +369,18 @@ julia> powermod(5, 3, 19)
 ```
 """
 function powermod(x::Integer, p::Integer, m::T) where T<:Integer
-    p < 0 && return powermod(invmod(x, m), -p, m)
     p == 0 && return mod(one(m),m)
+    # When the concrete type of p is sigened and has the lowerst value,
```
Comment (oscardssmith) [inline base/intfuncs.jl:373]:
```suggestion
    # When the concrete type of p is signed and has the lowest value,
```

File: base/intfuncs.jl [hunk 3]
```diff
@@ -369,8 +369,18 @@ julia> powermod(5, 3, 19)
...
+    # `p != 0 && p == -p` is equivalent to `p == typemin(typeof(p))` for 2's complement repretation.
```
Comment (oscardssmith) [inline base/intfuncs.jl:374]:
```suggestion
    # `p != 0 && p == -p` is equivalent to `p == typemin(typeof(p))` for 2's complement representation.
    # but will work for integer types like `BigInt` that don't have `typemin` defined
```

File: test/intfuncs.jl [hunk 4]
```diff
@@ -267,6 +267,9 @@ end
     @test powermod(2, -2, 5) == 4
     @test powermod(2, -1, -5) == -2
     @test powermod(2, -2, -5) == -1
+
+    @test powermod(2, typemin(Int128), 5) == 1
+    @test powermod(2, typemin(Int128), -5) == -4
```
Comment (oscardssmith) [inline test/intfuncs.jl:272]: add a test for `BigInt` power to make sure this still works for types without `typemin`.

**Review by oscardssmith — APPROVED** [review]

File: base/intfuncs.jl (hunk 2 above)
Comment (barucden) [reply base/intfuncs.jl:373]: This comment does not seem to be addressed, the typos are still there.

Comment (StonerShaw) [reply base/intfuncs.jl]: Sorry for that…… I have corrected them

**Comment by oscardssmith** [comment]
Thanks for the PR!
