### PR TITLE
RFC: add procs argument to @-everywhere and move code to a function

### LINKED ISSUE #18166: Error invoking worker from module
I'm pretty confused about this. Am I doing something wrong here? 

``` julia
julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> module M
       function f()
       remotecall_fetch(()->1, 2)
       end
       end
M

julia> M.f()
ERROR: On worker 2:
UndefVarError: M not defined
 in deserialize at ./serialize.jl:602
 in handle_deserialize at ./serialize.jl:581
 in deserialize at ./serialize.jl:541
 in deserialize_datatype at ./serialize.jl:822
 in handle_deserialize at ./serialize.jl:571
 in deserialize_msg at ./multi.jl:120
 in message_handler_loop at ./multi.jl:1317
 in process_tcp_streams at ./multi.jl:1276
 in #538 at ./event.jl:68
 in #remotecall_fetch#526(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1062
 in #remotecall_fetch#529(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in f() at ./REPL[2]:3
```

### PR DESCRIPTION
**Pull request by vtjnash**
Adding a function `remotecall_eval` lets us simplify code that previously needed awkward contortions to use `remotecall_fetch` on an anonymous function. This allows us to transform the more complex pattern of:

```julia
@sync for pid in pids
    @async remotecall_fetch(Core.eval, wid, Main, quote
        expression
    end)
end
```
into:
```julia
@everywhere pids expression
```

which resolves #18166

~~(note: This is against PR #22588, since I wanted to use this functionality to simplify its tests. When the RFCs are removed, I'll rebase whichever ones we decide to merge first.)~~

### CODE REVIEW

File: base/distributed/macros.jl [hunk 1]
```diff
@@ -65,55 +65,77 @@ end
...
+    @everywhere bar = 1
 
 will define `Main.bar` on all processes.
 
 Unlike [`@spawn`](@ref) and [`@spawnat`](@ref),
-`@everywhere` does not capture any local variables. Prefixing
-`@everywhere` with [`@eval`](@ref) allows us to broadcast
-local variables using interpolation :
+`@everywhere` does not capture any local variables.
+Instead, local variable can be broadcast using interpolation:
```
Comment (tkelman) [inline base/distributed/macros.jl]: variables

File: base/distributed/macros.jl [hunk 2]
```diff
@@ -65,55 +65,77 @@ end
...
-    imps = [Expr(:import, m) for m in extract_imports(ex)]
-    quote
-        $(isempty(imps) ? nothing : Expr(:toplevel, imps...))
-        sync_begin()
-        for pid in workers()
-            async_run_thunk(()->remotecall_fetch(eval_ew_expr, pid, $(Expr(:quote,ex))))
-            yield() # ensure that the remotecall_fetch has been started
+    remotecall_eval(m::Module, procs, expression)
+
+Execute an expression under module `m` on all procs.
```
Comment (tkelman) [inline base/distributed/macros.jl]: on the specified `procs`

**Comment by tkelman** [comment]
this by itself is less controversial than https://github.com/JuliaLang/julia/pull/22588. please decouple them.

File: test/compile.jl [hunk 3]
```diff
@@ -578,27 +578,23 @@ let
             end
             """)
 
-        @sync for wid in test_workers
-            @async remotecall_fetch(Core.eval, wid, Base, quote
-                unshift!(LOAD_PATH, $load_path)
-                unshift!(LOAD_CACHE_PATH, $load_cache_path)
-            end)
+        @everywhere test_workers begin
```
Comment (tkelman) [inline test/compile.jl]: this is a pretty indirect test, could use something more specific in the distributed tests
