### PR TITLE
more accurate and faster lgamma, and use a more standard branch cut

### LINKED ISSUE #18292: lgamma() fails for large negative imaginary arguments
The `lgamma()` function in julia-0.4.6 has trouble with large negative imaginary arguments, e.g.

    julia> lgamma(-300im)
    -Inf + NaN*im

scipy.special.gammaln() gives a more reasonable answer:

    >>> import scipy.special
    >>> scipy.special.gammaln(-300.0j)
    (-473.17185074259248-1410.3490664555823j)

### PR DESCRIPTION
**Pull request by stevengj**
This fixes #18292, replacing @JeffBezanson's 2011 `lgamma` function from 4675b10e1284e606e948fa400081aceb8d3ef11b with a rewritten one that should fix several accuracy problems, and is also about 3x faster (and about 40% faster than the one in SciPy).

I am marking this "breaking" because I changed it to use a more standard branch cut for `real(z) < 0`, the same as SciPy's [loggamma](http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.loggamma.html#scipy.special.loggamma) function and Mathematica's [LogGamma](https://reference.wolfram.com/language/ref/LogGamma.html).   This is a different branch cut than you would get from `log(gamma(z))`! (It differs by some multiple of 2π in the imaginary part, so `exp(lgamma(z))` is still the same Γ function.)  The new branch cut has the advantage of being analytic everywhere in the complex plane except along the negative real axis.

To do:
- [x] Needs more tests.
- [x] The recurrence relation can be sped up using a trick by Hare (1997), which is used in SciPy, of taking the log of the product of the shifts and keeping track of the sign of the real part so that the correct branch cut is chosen, rather than computing the sum of the logs of the shifts.
- [x] Fix accuracy close to zero at z=2

### CODE REVIEW

**Comment by stevengj** [comment]
Okay, I implemented the log(product) trick with the correct branch cut, which seems like it gives a 30% or more speed improvement, and added some more tests.

Should be good to merge once tests are green.

**Comment by stevengj** [comment]
Hmm, I need to improve accuracy near the other zero (at `z=2`) as well, hold on.

**Comment by stevengj** [comment]
Okay, fixed.

**Comment by stevengj** [comment]
@StefanKarpinski or @ViralBShah or @jiahao, okay to merge?

File: base/special/gamma.jl [hunk 1]
```diff
@@ -33,49 +33,91 @@ Compute the logarithmic factorial of `x`
...
-        z = logpi - b - a
+function lgamma end
+
+# asymptotic series for log(gamma(z)), valid for sufficiently large real(z) or |imag(z)|
+@inline function lgamma_asymptotic(z::Complex{Float64})
+    zinv = inv(z)
+    t = zinv*zinv
+    # coefficients are bernoulli[2:n+1] .// (2*(1:n).*(2*(1:n) - 1))
+    return (z-0.5)*log(z) - z + 9.1893853320467274178032927e-01 + # <-- log(2pi)/2
+       zinv*@evalpoly(t, 8.3333333333333333333333368e-02,-2.7777777777777777777777776e-03,7.9365079365079365079365075e-04,-5.9523809523809523809523806e-04,8.4175084175084175084175104e-04,-1.9175269175269175269175262e-03,6.4102564102564102564102561e-03,-2.9550653594771241830065352e-02)
```
Comment (tkelman) [inline base/special/gamma.jl]: wrap this

File: base/special/gamma.jl [hunk 2]
```diff
@@ -33,49 +33,91 @@ Compute the logarithmic factorial of `x`
...
+        # the 2pi * floor(...) stuff is to choose the correct branch cut for log(sinpi(z))
+        return Complex(1.1447298858494001741434262, # log(pi)
+                       copysign(6.2831853071795864769252842, y) # 2pi
+                       * floor(0.5*x+0.25)) -
+               log(sinpi(z)) - lgamma(1-z)
+    elseif abs(x - 1) + yabs < 0.1
+        # taylor series around zero at z=1
+        # ... coefficients are [-eulergamma; [(-1)^k * zeta(k)/k for k in 2:15]]
+        w = Complex(x - 1, y)
+        return w * @evalpoly(w, -5.7721566490153286060651188e-01,8.2246703342411321823620794e-01,-4.0068563438653142846657956e-01,2.705808084277845478790009e-01,-2.0738555102867398526627303e-01,1.6955717699740818995241986e-01,-1.4404989676884611811997107e-01,1.2550966952474304242233559e-01,-1.1133426586956469049087244e-01,1.000994575127818085337147e-01,-9.0954017145829042232609344e-02,8.3353840546109004024886499e-02,-7.6932516411352191472827157e-02,7.1432946295361336059232779e-02,-6.6668705882420468032903454e-02)
```
Comment (tkelman) [inline base/special/gamma.jl]: likewise

File: base/special/gamma.jl (hunk 1 above)
Comment (stevengj) [inline base/special/gamma.jl]: I felt like it was actually easier to read the code when these lines were left unwrapped, especially on github or in an editor like Atom that does not line-wrap for you, because then you don't have several lines of indecipherable numbers interrupting the flow of the code.

Comment (tkelman) [inline base/special/gamma.jl]: The code is several lines of numbers. The flow is line continuation / indent.

Comment (stevengj) [inline base/special/gamma.jl]: ok, fine

**Comment by stevengj** [comment]
Bump.  Okay to merge?

**Comment by StefanKarpinski** [comment]
Sure, although I'm not remotely qualified to judge this :)

**Comment by dlfivefifty** [comment]
@tkelman What exactly are you hoping to verify?   Are you after something mathematically rigorous, or rather just a second point of comparison?

It's not currently possible to do anything mathematically rigorous in ApproxFun, though I had a chat with David Sanders of https://github.com/dpsanders/ValidatedNumerics.jl and the following should be implementable:  the Fourier/Taylor/Chebyshev/Laurent coefficients can be calculated rigorously as intervals, provided that the input function

1.  can be rigorously evaluated pointwise on intervals
2. has the first few derivatives implemented via automatic differentiation (also evaluatable on intervals)

A side effect should mean evaluation of the resulting `Fun` also gives a rigorous interval.

**Comment by dlfivefifty** [comment]
@dpsanders

**Comment by stevengj** [comment]
In this case, you need to check it in the complex plane.  Here is a quick check with 10^7 points against SciPy:

```
using PyCall
lg = pyimport("scipy.special")["loggamma"]
z = (randn(10^7) + randn(10^7)*im) * 10;
err(a,b) = abs(a - b) / abs(b)
maximum(err.(lgamma.(z), lg(z)))
```
gives `1.175661212573326e-13`.

**Comment by dlfivefifty** [comment]
If your algorithm is a sequence of analytic operations, then you wouldn't need to check everywhere in the complex plane: accuracy along a contour would give accuracy within the enclosed region (provided you avoid the singularities of lgamma).

**Comment by stevengj** [comment]
@dlfivefifty, that's only if you assume that there are no bugs and your code is really computing an analytic function.   This is not a good thing to assume, particularly for code that involves switching between multiple approximations.

**Comment by stevengj** [comment]
Note also that at the point of maximum difference compared to SciPy, i.e. `z[indmax(err.(lgamma.(z), lg(z)))] == 1.5000165664503786 - 0.014135858766095162im`, my code is actually more accurate.   I checked against WolframAlpha at that point, and my actual relative error is `2.6e-15`, whereas SciPy's error is `1.1e-13`.

**Comment by dlfivefifty** [comment]
But you can't "rigorously" verify you don't have any bugs...

What you could do is for each approximation scheme, instead of running it on a `z::Complex128`, run the code on 

```julia
z=Fun(identity,Taylor(Circle(z_0,r)))
```

Then check the returned Fun is accurate compared to 

```
Fun(z->old_lgamma(z),Taylor(Circle(z_0,r)))
```

This will give a pretty good guarantee that it is accurate everywhere inside the circle.

**Comment by stevengj** [comment]
In my experience, the most effective ways to test special-function implementations are (1) exhaustive randomized tests against other implementations combined with (2) tests near known problem spots:
* Crossover points between two different approximations
* Near zeros, singularities, and branch cuts.
* Extreme arguments (very large, very small, Inf, NaN).

**Comment by dlfivefifty** [comment]
Running the same algorithm on a special data type that checks for a region is not "assuming" it is smooth on the inside: as long as the functions you call are smooth on the inside, then the result is also smooth on the inside.

**Comment by stevengj** [comment]
@dlfivefifty, the problem is that the functions you call are not smooth.   You are discontinuously switching between different approximation techniques in different regions of the complex plane, with the intention that the approximations are different only close to the machine-precision level.   You need to check that (a) each approximation branch is bug-free and (b) that the approximations are each accurate to the desired precision in the whole region where they are used.

**Comment by stevengj** [comment]
Also, you need to check the *relative* accuracy everywhere in each region, and I think the technique you are discussing only bounds the *absolute* error.

**Comment by dlfivefifty** [comment]
In that case you are probably better off with the random check.

**Comment by dlfivefifty** [comment]
PS to check relative error all you would have to do is check

```norm((u_approx - u_ex)/u_ex - 1)```

on the boundary provided that u_ex has no zeros.

**Comment by stevengj** [comment]
@dlfivefifty, we actually want to check the relative error in both the real and imaginary parts separately.   In any case, as I said, checking on circular contours does not help with the discontinuities in the approximation techniques, nor does it necessarily exercise all the code paths, nor does it deal with the fact that `lgamma` has zeros, poles, and branch cuts.

**Comment by dlfivefifty** [comment]
Yes, for `lgamma` checking at random points suffices.  But that's not possible for functions with many parameters since the number of random points needed grows exponentially: I don't think you can verify even Hypergeometric 2F1 this way.

However, if you split an algorithm into separate components built out of analytic functions (essentially all functions that are used are piecewise analytic), then each component can be checked individually only on the boundary of the domain where it is used.

**Comment by stevengj** [comment]
As I said above, I don't think checking at random points suffices even for `lgamma`.  Just that it is a good starting point and sanity check, complemented by checking the "hard cases" more carefully.  (Even then, it is not practical to prove that you don't have a bug.)

If you have a function of multiple arguments, even Bessel or polygamma functions (much less hypergeometric functions), I don't follow you — your technique only applies to contours in the complex plane, not to multidimensional manifolds, no?   And even for single-argument functions it doesn't apply for checking the real and imaginary parts separately since these are not generally analytic anyway.

**Comment by dlfivefifty** [comment]
Bessel/hypergeometric are analytic in all arguments, so you need only check at the boundary of a multidimensional manifold in the multivariate complex plane.

The real and imaginary parts of an analytic function are harmonic, and so their error is also maximized at the boundary.

**Comment by stevengj** [comment]
Oh right. But note that the real and imaginary parts typically have even many more zeros than the function as a whole, you probably don't get the relative error this way.

Ignoring the whole issue of zeros etc., implementing your scheme in practice for a high-dimensional problem is going to be challenging because of the large number of odd-shaped high-dimensional manifolds that are probably required to exhaustively check all of the different approximation regions, especially once you factor in things like recurrences (each iteration of which introduces a new manifold).  And in the end, you still have a curse of dimensionality, just with one dimension less.

**Comment by stevengj** [comment]
Anyway, this argument seems academic.  As discussed above, it is not particularly applicable to `lgamma`, and if you want to go and implement your approach for checking, say the Bessel function implementations, good luck to you.

Since no one seems to have any objection to the change of branch cuts, and the new implementation is a clear improvement on the old one in every other way, I'm going to go ahead and merge in the next day or two.

**Comment by dlfivefifty** [comment]
I was only answering @tkelman's question: " is this one of those things where ApproxFun can help us rigorously verify our results against the series expansion?" , not suggesting you actually do it.

**Comment by stevengj** [comment]
I think the correct answer to @tkelman's question is simply, "no."

**Comment by dlfivefifty** [comment]
A more precise correct answer is: 

1. Yes for real values, if you break of the real line at points where the algorithm changes/at roots, and assume other functions called are correct.  You don't need ApproxFun, just interval arithmetic.
2. No for complex values, it's theoretically possible but too complicated.
