### PR TITLE
REPL: fix bug when all the input buffer can't be printed

### LINKED ISSUE #24049: REPL does not handle well multi-line input bigger than the screen
When entering a mulit-line input bigger than the available number of lines in the screen window, it becomes impossible to navigate back to the beginning of the input (or it seems kind of possible in a blind way, i.e. the screen is not refreshed accordingly).

### PR DESCRIPTION
**Pull request by rfourquet**
When the input buffer contained too many lines, it was
still possible to edit it, but blindly for the n invisible
lines: indeed, the first n lines where never shown even
when the cursor was moved in their region.
Fix that, by centering the cursor in the available space
when all the lines can't be shown at the same time.
Other strategies are possible, some nicer, but this is
probably the simplest, by far, as it is "stateless": it
doesn't need to remember what happened during the last
refresh or to know what event triggered the refresh.

Fixes #24049.
This is an embarassingly simple 10 lines patch, when compared to the time it took me to come up with :sweat_smile: We could eventually improve the behavior, for example to implement what IPython does, i.e. don't change the visible region when the cursor movement doesn't force to unhide a line. But this would be a feature request rather than a long standing bug.

### CODE REVIEW

File: stdlib/REPL/src/LineEdit.jl [hunk 1]
```diff
@@ -395,16 +397,24 @@ function refresh_multi_line(termbuf::TerminalBuffer, terminal::UnixTerminal, buf
...
+        end
         # We need to deal with on-screen characters, so use textwidth to compute occupied columns
-        llength = textwidth(l)
-        slength = sizeof(l)
+        llength = textwidth(line)
+        slength = sizeof(line)
         cur_row += 1
         # lwrite: what will be written to termbuf
-        lwrite = region_active ? highlight_region(l, regstart, regstop, written, slength) :
-                                 l
```
Comment (rfourquet) [inline stdlib/REPL/src/LineEdit.jl]: I literally spent 5 minutes trying to find where was the else clause, thinking there was a bug and even going through git-log to find where this was introduced... So I allowed myself to make this unrelated change for clarity and maybe save time to future readers of this code.

File: stdlib/REPL/src/LineEdit.jl [hunk 2]
```diff
@@ -395,16 +397,24 @@ function refresh_multi_line(termbuf::TerminalBuffer, terminal::UnixTerminal, buf
...
+                     # Note: when there are too many lines for rows, we still print the first lines
+                     # even if they are going to not be visible in the end: for simplicity, but
+                     # also because it does the 'right thing' when the window is resized
     while moreinput
-        l = readline(buf, keep=true)
-        moreinput = endswith(l, "\n")
+        line = readline(buf, keep=true)
+        moreinput = endswith(line, "\n")
+        if moreinput && lastline # we want to print only one "visual" line, so
+            line = line[1:end-1] # don't include the trailing "\n"
```
Comment (vtjnash) [inline stdlib/REPL/src/LineEdit.jl]: use chomp (so that this won't fail if the last character is multi-byte)

**Review by vtjnash — APPROVED** [review]
Yay, this seems good! Yeah, this seemed very tricky to figure out the right approach—so I'm glad you were able to!

Does this handle the case where the user has shrunk the terminal to show just a single row? It looks like it does, but wanted to confirm if you'd tested it, since that'd be the ultimate proof.

File: stdlib/REPL/src/LineEdit.jl (hunk 2 above)
Comment (rfourquet) [reply stdlib/REPL/src/LineEdit.jl]: Ah right, maybe `prevind(line, end-1)` is fine too, as we know the last character is `'\n'` ?

**Comment by rfourquet** [comment]
> Does this handle the case where the user has shrunk the terminal to show just a single row?

Ouch! I had tested up to two rows, as this is the minimum panel size that tmux allows me, but one row seems buggy. Will investigate.

File: stdlib/REPL/src/LineEdit.jl (hunk 2 above)
Comment (vtjnash) [reply stdlib/REPL/src/LineEdit.jl]: we know that `end` is `\n`, but that tells nothing about `end-1` (or `prevind(line, endof(line))`)—but `chomp`/`chop` is simpler

**Comment by rfourquet** [comment]
Alright, fixed the 1-row case, still high time-spent/LOC ratio, but gets better :)
