### PR TITLE
fix #55389: type-unstable `join`

### LINKED ISSUE #55389: Regression in inferred return type for `join` on simple iterator.
```julia-repl
julia> itr = ("foo" for _ in 1:100)
Base.Generator{UnitRange{Int64}, var"#1#2"}(var"#1#2"(), 1:100)

julia> @code_warntype join(itr)
MethodInstance for join(::Base.Generator{UnitRange{Int64}, var"#1#2"})
  from join(iterator) @ Base strings/io.jl:374
Arguments
  #self#::Core.Const(join)
  iterator::Base.Generator{UnitRange{Int64}, var"#1#2"}
Body::Union{Base.AnnotatedString{String}, String}
```

This used to infer to `String`.

Ref https://github.com/JuliaLang/julia/pull/54919.

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

File: base/strings/io.jl [hunk 1]
```diff
@@ -354,7 +354,8 @@ function join(io::IO, iterator, delim="")
 end
 
 function _join_preserve_annotations(iterator, args...)
-    if isconcretetype(eltype(iterator)) && !_isannotated(eltype(iterator)) && !any(_isannotated, args)
+    et = @default_eltype(iterator)
+    if isconcretetype(et) && !_isannotated(et) && !any(_isannotated, args)
```
Comment (KristofferC) [inline base/strings/io.jl:358]: Should `et` be used instead of the `eltype` call in the other branch as well?

**Comment by tecosaur** [comment]
Thanks for jumping on this Simeon!

**Review by tecosaur — APPROVED** [review]

File: base/strings/io.jl (hunk 1 above)
Comment (simeonschaub) [reply base/strings/io.jl:358]: Yes, that's probably sensible. I pushed the change
