### PR TITLE
fix #10324

### LINKED ISSUE #10324: REPL Tab Completion on Unicode Filenames
The setup

    shell> mkdir /tmp/julia_test
    julia> for i=0:9; run(`touch /tmp/julia_test/λ.$i.test`); end

The first test:

    shell> ls /tmp/julia_test/<TAB>

correctly completes to

    shell> ls /tmp/julia_test/λ.

The second (failing) test:

    shell> ls /tmp/julia_test/λ<TAB>

incorrectly erases the final / and completes to

    shell> ls /tmp/julia_testλ.

This does not happen if the filenames are named `L.$i.test`

Finally:

```
julia> versioninfo()
Julia Version 0.3.5-pre+121
Commit e424d33 (2015-01-07 00:19 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

### PR DESCRIPTION
**Pull request by dhoegh**
This fixes #10324.

### CODE REVIEW

**Comment by dhoegh** [comment]
The Appveyor failure is unrelated.

**Comment by JeffBezanson** [comment]
Awesome, thanks!

File: base/REPLCompletions.jl [hunk 1]
```diff
@@ -130,8 +130,12 @@ function complete_path(path::AbstractString, pos)
             push!(matches, id ? file * (@windows? "\\\\" : "/") : file)
         end
     end
-    matches = UTF8String[replace(s, r"\s", "\\ ") for s in matches]
-    return matches, nextind(path, pos - sizeof(prefix) - length(matchall(r" ", prefix))):pos, length(matches) > 0
+    matches = UTF8String[replace(s, r" ", "\\ ") for s in matches]
```
Comment (JeffBezanson) [inline base/REPLCompletions.jl]: Are you sure we don't need the `\s` to escape all spaces?

Comment (dhoegh) [inline base/REPLCompletions.jl]: yes, this lines change is actually not for fixing the bug. The reason for this is to replace space in path with `"\ "` so it is correctly escaped for paths and files. I have incidentally introduced `"\s"` instead of `" "` in pull #8838. It do not seem to do any difference since file names cannot contain tabs, return carriage and new line. However I think it is more correct to only match `" "`

Comment (JeffBezanson) [inline base/REPLCompletions.jl]: Ok.

Comment (vtjnash) [inline base/REPLCompletions.jl]: > It do not seem to do any difference since file names cannot contain tabs, return carriage and new line.

posix filenames can contain any character except `/` (i haven't looked at the rest of this PR to see how that fits in)

Comment (dhoegh) [inline base/REPLCompletions.jl]: Ok. The only case the code take into account since it replaces `"\s"` with `"\\ "` but it should then be replaced like: `replace(s, r"(\s)", "\\1")`? I will revert this line change and then correct it in another pull because there are multiple other places that then needs to be changed.

**Comment by dhoegh** [comment]
Bump this can be merged, unless I should revert 2b81792 as I discuss in https://github.com/JuliaLang/julia/pull/10357#issuecomment-76521021. I think I should revert because it is not correct to replace all occurrences of a whitespace char in a filename like with an escaped space like `replace(s, r"\s", "\\ ")`.
