### PR TITLE
Lowering: Insert QuoteNode for captured boxed value

### LINKED ISSUE #52531: Mutable let block variable treated as immutable in Julia 1.10
MWE:
```julia
let
    global set_a, get_a
    _a::Int       = -1
    set_a(a::Int) = (_a = a; return get_a())
    get_a()       = _a
end
    
set_a(1)
get_a()
set_a(2)
get_a()
```
Wrong output in Julia 1.10:
```julia
julia> let
           global set_a, get_a
           _a::Int       = -1
           set_a(a::Int) = (_a = a; return get_a())
           get_a()       = _a
       end
get_a (generic function with 1 method)

julia> set_a(1)
-1

julia> get_a()
-1

julia> set_a(2)
-1

julia> get_a()
-1
```
Correct output in Julia 1.9.4:
```julia
julia> let
           global set_a, get_a
           _a::Int       = -1
           set_a(a::Int) = (_a = a; return get_a())
           get_a()       = _a
       end
get_a (generic function with 1 method)

julia> set_a(1)
1

julia> get_a()
1

julia> set_a(2)
2

julia> get_a()
2
```

### PR DESCRIPTION
**Pull request by vchuravy**
`Core.Box` is not self-quoting so it should be captured in a QuoteNode.
This has been benign until the improved effect system, we handle `QuoteNode`
of a mutable value as a global access, whereas a direct reference to a value
is treated as inaccessible memory.

Fixes #52531

### CODE REVIEW

File: test/compiler/effects.jl [hunk 1]
```diff
@@ -1356,3 +1356,20 @@ end
...
+    is_initialized52531()            = _is_initialized
+end
+
+@test !is_initialized52531()
+@test set_initialized52531(true)
+@test is_initialized52531()
+@test !set_initialized52531(false)
+@test !is_initialized52531()
+foo52531(4)
+@test is_initialized52531()
```
Comment (aviatesk) [inline test/compiler/effects.jl:1375]:
```suggestion
let
    global is_initialized52531, set_initialized52531
    _is_initialized = false
    set_initialized52531!(flag::Bool) = (_is_initialized = flag)
    is_initialized52531()             = _is_initialized
end
top_52531(_) = (set_initialized52531!(true); nothing)
@test !Core.Compiler.is_consistent(Base.infer_effects(is_initialized52531))
@test !Core.Compiler.is_removable_if_unused(Base.infer_effects(set_initialized52531!, (Bool,)))(false)
@test !is_initialized52531()
foo52531(0)
@test is_initialized52531()
```

**Review by aviatesk — APPROVED** [review]
