### PR TITLE
fix null comparisons for non-standard address spaces

### LINKED ISSUE #780: incorrect first value for simple kernel on 1.12
Reduced from the example in https://github.com/JuliaGPU/AMDGPU.jl/issues/766#issuecomment-2977262871:

```julia-repl
julia> using AMDGPU

julia> function kern!(C, A, ta)
           i = workitemIdx().x
           @inbounds begin
               x = ta == 0 ? A[1] : (ta == 1 ? A[1] : A[1])
               C[i] = x
           end
           nothing
       end
kern! (generic function with 1 method)

julia> C = AMDGPU.zeros(ComplexF64, 2, 2)
2×2 ROCArray{ComplexF64, 2, AMDGPU.Runtime.Mem.HIPBuffer}:
 0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im

julia> @roc groupsize=2 gridsize=2 kern!(C, AMDGPU.ones(ComplexF64, 1), 1)
AMDGPU.Runtime.HIPKernel{typeof(kern!), Tuple{AMDGPU.Device.ROCDeviceMatrix{ComplexF64, 1}, AMDGPU.Device.ROCDeviceVector{ComplexF64, 1}, Int64}}(kern!, AMDGPU.HIP.HIPFunction(Ptr{Nothing}(0x000000000fcec3c0), AMDGPU.HIP.HIPModule(Ptr{Nothing}(0x000000000fe23de0)), Symbol[]))

julia> C
2×2 ROCArray{ComplexF64, 2, AMDGPU.Runtime.Mem.HIPBuffer}:
 0.0-4.84973e17im  0.0+0.0im
 1.0+0.0im         0.0+0.0im
```

The first item in `C` should be `1` as well, but it is not. Curiously, this only happens for `ComplexF64` and everything works as expected if one either changes `ta` from 1 to 0 or makes C a vector instead of a matrix. Any ideas what could be happening here?

The kernel lowers to the following LLVM IR:

```llvm
; GPUCompiler.CompilerJob{GPUCompiler.GCNCompilerTarget, AMDGPU.Compiler.HIPCompilerParams}(MethodInstance for (::GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0")(::KernelAbstractions.CompilerMetadata{KernelAbstractions.NDIteration.DynamicSize, KernelAbstractions.NDIteration.DynamicCheck, Nothing, CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, KernelAbstractions.NDIteration.NDRange{1, KernelAbstractions.NDIteration.DynamicSize, KernelAbstractions.NDIteration.DynamicSize, CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, ::AMDGPU.Device.ROCDeviceVector{ComplexF64, 1}, ::ComplexF64), CompilerConfig for GPUCompiler.GCNCompilerTarget, 0x00000000000096cb)
;  @ none within `gpu_fill_kernel!`
define amdgpu_kernel void @_Z16gpu_fill_kernel_16CompilerMetadataI11DynamicSize12DynamicCheckv16CartesianIndicesILi1E5TupleI5OneToI5Int64EEE7NDRangeILi1ES0_S0_S8_S8_EE14ROCDeviceArrayI7ComplexI7Float64ELi1ELi1EESF_({ ptr, ptr, ptr, ptr, ptr, ptr, i32, i32, ptr, ptr, ptr, ptr } %state, { [1 x [1 x [1 x i64]]], [2 x [1 x [1 x [1 x i64]]]] } %"__ctx__::CompilerMetadata", { [1 x i64], ptr addrspace(1), i64 } %"a::ROCDeviceArray", [2 x double] %"val::Complex") local_unnamed_addr #2 {
conversion:
  %"__ctx__::CompilerMetadata.fca.0.0.0.0.extract" = extractvalue { [1 x [1 x [1 x i64]]], [2 x [1 x [1 x [1 x i64]]]] } %"__ctx__::CompilerMetadata", 0, 0, 0, 0
  %"__ctx__::CompilerMetadata.fca.1.0.0.0.0.extract" = extractvalue { [1 x [1 x [1 x i64]]], [2 x [1 x [1 x [1 x i64]]]] } %"__ctx__::CompilerMetadata", 1, 0, 0, 0, 0
  %"__ctx__::CompilerMetadata.fca.1.1.0.0.0.extract" = extractvalue { [1 x [1 x [1 x i64]]], [2 x [1 x [1 x [1 x i64]]]] } %"__ctx__::CompilerMetadata", 1, 1, 0, 0, 0
  %0 = call i32 @llvm.amdgcn.workgroup.id.x()
  %1 = call i32 @llvm.amdgcn.workitem.id.x()
  %2 = add nuw nsw i32 %1, 1
  %3 = icmp sgt i64 %"__ctx__::CompilerMetadata.fca.1.0.0.0.0.extract", 0
  call void @llvm.assume(i1 %3)
  %4 = icmp sgt i64 %"__ctx__::CompilerMetadata.fca.1.1.0.0.0.extract", 0
  call void @llvm.assume(i1 %4)
  %5 = zext nneg i32 %2 to i64
  %6 = zext i32 %0 to i64
  %7 = mul i64 %"__ctx__::CompilerMetadata.fca.1.1.0.0.0.extract", %6
  %8 = add i64 %7, %5
  %9 = icmp slt i64 %8, 1
  %10 = icmp sgt i64 %8, %"__ctx__::CompilerMetadata.fca.0.0.0.0.extract"
  %.not10 = or i1 %9, %10
  br i1 %.not10, label %L297, label %L133

L133:                                             ; preds = %conversion
  %"a::ROCDeviceArray.fca.1.extract" = extractvalue { [1 x i64], ptr addrspace(1), i64 } %"a::ROCDeviceArray", 1
; ┌ @ /home/simeon/.julia/packages/KernelAbstractions/C3nYQ/src/macros.jl:322 within `macro expansion`
; │┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/array.jl:86 within `#setindex!`
; ││┌ @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/pointer.jl:88 within `unsafe_store!`
; │││┌ @ none within `pointerset`
; ││││┌ @ none within `macro expansion` @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/base.jl:39
       %11 = getelementptr [2 x double], ptr addrspace(1) %"a::ROCDeviceArray.fca.1.extract", i64 %7
       %12 = zext nneg i32 %1 to i64
       %13 = getelementptr [2 x double], ptr addrspace(1) %11, i64 %12
       %"val::Complex.elt" = extractvalue [2 x double] %"val::Complex", 0
       store double %"val::Complex.elt", ptr addrspace(1) %13, align 8
       %.repack11 = getelementptr [2 x double], ptr addrspace(1) %11, i64 %12, i64 1
       %"val::Complex.elt12" = extractvalue [2 x double] %"val::Complex", 1
       store double %"val::Complex.elt12", ptr addrspace(1) %.repack11, align 8
; ││└└└
; ││ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/array.jl:87 within `#setindex!`
    br label %L297

L297:                                             ; preds = %L133, %conversion
; │└
   ret void
; └
}
; GPUCompiler.CompilerJob{GPUCompiler.GCNCompilerTarget, AMDGPU.Compiler.HIPCompilerParams}(MethodInstance for kern!(::AMDGPU.Device.ROCDeviceMatrix{ComplexF64, 1}, ::AMDGPU.Device.ROCDeviceVector{ComplexF64, 1}, ::Int64), CompilerConfig for GPUCompiler.GCNCompilerTarget, 0x00000000000096cb)
;  @ REPL[2]:1 within `kern!`
define amdgpu_kernel void @_Z5kern_14ROCDeviceArrayI7ComplexI7Float64ELi2ELi1EES_IS2_Li1ELi1EE5Int64({ ptr, ptr, ptr, ptr, ptr, ptr, i32, i32, ptr, ptr, ptr, ptr } %state, { [2 x i64], ptr addrspace(1), i64 } %"C::ROCDeviceArray", { [1 x i64], ptr addrspace(1), i64 } %"A::ROCDeviceArray", i64 signext %"ta::Int64") local_unnamed_addr #2 {
conversion:
  %"A::ROCDeviceArray.fca.1.extract" = extractvalue { [1 x i64], ptr addrspace(1), i64 } %"A::ROCDeviceArray", 1
  %0 = alloca [2 x double], align 8, addrspace(5)
  %1 = alloca [2 x i64], align 8, addrspace(5)
  %2 = alloca [2 x double], align 8, addrspace(5)
;  @ REPL[2]:4 within `kern!`
  switch i64 %"ta::Int64", label %L69 [
    i64 0, label %guard_pass20
    i64 1, label %L48
  ]

L48:                                              ; preds = %conversion
; ┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/array.jl:81 within `#getindex`
; │┌ @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/pointer.jl:85 within `unsafe_load`
; ││┌ @ none within `pointerref`
; │││┌ @ none within `macro expansion` @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/base.jl:39
      %.unpack21 = load double, ptr addrspace(1) %"A::ROCDeviceArray.fca.1.extract", align 8
      %.elt22 = getelementptr inbounds [2 x double], ptr addrspace(1) %"A::ROCDeviceArray.fca.1.extract", i64 0, i64 1
      %.unpack23 = load double, ptr addrspace(1) %.elt22, align 8
      store double %.unpack21, ptr addrspace(5) %0, align 8
      %.fca.1.gep4 = getelementptr inbounds [2 x double], ptr addrspace(5) %0, i32 0, i32 1
      store double %.unpack23, ptr addrspace(5) %.fca.1.gep4, align 8
      %.not24 = icmp eq ptr addrspace(5) %0, null
      br i1 %.not24, label %L75, label %guard_pass30

L69:                                              ; preds = %conversion
      %.unpack25 = load double, ptr addrspace(1) %"A::ROCDeviceArray.fca.1.extract", align 8
      %.elt26 = getelementptr inbounds [2 x double], ptr addrspace(1) %"A::ROCDeviceArray.fca.1.extract", i64 0, i64 1
      %.unpack27 = load double, ptr addrspace(1) %.elt26, align 8
      store double %.unpack25, ptr addrspace(5) %2, align 8
      %.fca.1.gep = getelementptr inbounds [2 x double], ptr addrspace(5) %2, i32 0, i32 1
      store double %.unpack27, ptr addrspace(5) %.fca.1.gep, align 8
      %.not28 = icmp eq ptr addrspace(5) %2, null
      br i1 %.not28, label %L75, label %guard_pass35

L75:                                              ; preds = %guard_pass35, %guard_pass30, %L69, %L48
      %.not29 = icmp eq ptr addrspace(5) %1, null
      br i1 %.not29, label %L76, label %guard_pass25

L76:                                              ; preds = %guard_pass25, %guard_pass20, %L75
      %.sroa.05.0 = phi double [ %.sroa.05.0.copyload6, %guard_pass25 ], [ undef, %L75 ], [ %.unpack, %guard_pass20 ]
      %.sroa.6.0 = phi double [ %.sroa.6.0.copyload8, %guard_pass25 ], [ undef, %L75 ], [ %.unpack18, %guard_pass20 ]
; └└└└
;  @ REPL[2]:2 within `kern!`
; ┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/indexing.jl:122 within `workitemIdx`
; │┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/indexing.jl:87 within `workitemIdx_x`
; ││┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/indexing.jl:3 within `_index`
; │││┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/indexing.jl:3 within `macro expansion` @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/base.jl:39
      %3 = call i32 @llvm.amdgcn.workitem.id.x()
      %"C::ROCDeviceArray.fca.1.extract" = extractvalue { [2 x i64], ptr addrspace(1), i64 } %"C::ROCDeviceArray", 1
; └└└└
;  @ REPL[2]:5 within `kern!`
; ┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/array.jl:86 within `#setindex!`
; │┌ @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/pointer.jl:88 within `unsafe_store!`
; ││┌ @ none within `pointerset`
; │││┌ @ none within `macro expansion` @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/base.jl:39
      %4 = zext nneg i32 %3 to i64
      %5 = getelementptr inbounds [2 x double], ptr addrspace(1) %"C::ROCDeviceArray.fca.1.extract", i64 %4
      store double %.sroa.05.0, ptr addrspace(1) %5, align 8
      %.repack30 = getelementptr inbounds [2 x double], ptr addrspace(1) %"C::ROCDeviceArray.fca.1.extract", i64 %4, i64 1
      store double %.sroa.6.0, ptr addrspace(1) %.repack30, align 8
; │└└└
; │ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/array.jl:87 within `#setindex!`
   ret void

guard_pass20:                                     ; preds = %conversion
; └
;  @ REPL[2]:4 within `kern!`
; ┌ @ /home/simeon/.julia/dev/AMDGPU/src/device/gcn/array.jl:81 within `#getindex`
; │┌ @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/pointer.jl:85 within `unsafe_load`
; ││┌ @ none within `pointerref`
; │││┌ @ none within `macro expansion` @ /home/simeon/.julia/packages/LLVM/2JPxT/src/interop/base.jl:39
      %.elt17 = getelementptr inbounds [2 x double], ptr addrspace(1) %"A::ROCDeviceArray.fca.1.extract", i64 0, i64 1
      %.unpack18 = load double, ptr addrspace(1) %.elt17, align 8
      %.unpack = load double, ptr addrspace(1) %"A::ROCDeviceArray.fca.1.extract", align 8
      br label %L76

guard_pass25:                                     ; preds = %L75
; └└└└
;  @ REPL[2]:1 within `kern!`
  %.sroa.05.0.copyload6 = load double, ptr addrspace(5) %1, align 8
  %.sroa.6.0..sroa_idx7 = getelementptr inbounds i8, ptr addrspace(5) %1, i32 8
  %.sroa.6.0.copyload8 = load double, ptr addrspace(5) %.sroa.6.0..sroa_idx7, align 8
  br label %L76

guard_pass30:                                     ; preds = %L48
  call void @llvm.memcpy.p5.p5.i64(ptr addrspace(5) noundef align 8 dereferenceable(16) %1, ptr addrspace(5) noundef nonnull align 8 dereferenceable(16) %0, i64 16, i1 false)
  br label %L75

guard_pass35:                                     ; preds = %L69
  call void @llvm.memcpy.p5.p5.i64(ptr addrspace(5) noundef align 8 dereferenceable(16) %1, ptr addrspace(5) noundef nonnull align 8 dereferenceable(16) %2, i64 16, i1 false)
  br label %L75
}
```

### PR DESCRIPTION
**Pull request by simeonschaub**
Apparently this is what clang does. Still need to go through other
places we create or compare against null pointers. Also needs tests.
Thanks to @gbaraldi for helping me debug!

fixes JuliaGPU/AMDGPU.jl#780, JuliaGPU/AMDGPU.jl#766

ref ROCm/llvm-project#281

### CODE REVIEW

**Comment by gbaraldi** [comment]
Is this wrong in 1.10/11 as well?

**Comment by simeonschaub** [comment]
The AMDGPU issues only manifest themselves in 1.12 onwards, but it might be good to fix on earlier versions nonetheless

File: src/cgutils.cpp [hunk 1]
```diff
@@ -1601,10 +1601,18 @@ static void undef_var_error_ifnot(jl_codectx_t &ctx, Value *ok, jl_sym_t *name,
...
 static Value *null_pointer_cmp(jl_codectx_t &ctx, Value *v)
 {
     ++EmittedNullchecks;
-    return ctx.builder.CreateIsNotNull(v);
+    Type *T = v->getType();
+    return ctx.builder.CreateICmpNE(
+            v,
+            ctx.builder.CreateAddrSpaceCast(
+                Constant::getNullValue(ctx.builder.getPtrTy(AddressSpace::Derived)),
+                PointerType::get(T, T->getPointerAddressSpace())));
```
Comment (vtjnash) [inline src/cgutils.cpp]:
```suggestion
                Constant::getNullValue(ctx.builder.getPtrTy(0)), T);
```

I expect AMD to still have a very bad time of this, since LLVM does currently define these as being identical and expect it to constant fold away.

Comment (gbaraldi) [reply src/cgutils.cpp]: I think they've forbidden this somewhat (this causes problems elsewhere but we should just follow what clang does for now). Because LLVM-ir doesn't not have a way to represent nulls that aren't 0 properly until https://github.com/llvm/llvm-project/pull/131557

**Comment by simeonschaub** [comment]
Ok, going through `cgutils.cpp` and `codegen.cpp`, I think all the other null pointers used there live inside one of the adress spaces listed in https://github.com/JuliaLang/julia/blob/d7c70bcbab2cba3f7decb3ffa21cc4ef73ed87cb/src/llvm-codegen-shared.h#L18, all of which I believe don't have this non-zero null issue, so I reverted back to the original fix.

Regarding testing, I wasn't able to produce any kind of test case without pulling in the whole GPUCompiler stack, would it be fine to not have them in Base as the tests in AMDGPU.jl already cover this? Or do you have any other ideas for how to test this?

**Comment by gbaraldi** [comment]
LGTM
