### PR TITLE
fix Sockets type stability issues

### LINKED ISSUE #59397: `juliac.jl --trim` build fails with `Sockets` module
### Environment

- **Julia version:** 1.12.0-rc1
- **OS:** Windows 11 (x64)

### Description

Attempting to compile a Julia script which implements `Sockets` module into a standalone executable with `juliac.jl --experimental --trim` in Julia 1.12.0-rc1 fails with `Verifier error #...: unresolved call from statement ...`.

Compiling without `--trim` succeeds.

### Steps to reproduce

Paste the following minimal working example into `SocketTest.jl`:

```julia
module SocketTest

using Sockets

export main

function @main(args::Vector{String})::Cint
    sock = connect("localhost", parse(Int, args[1]))

    if isopen(sock)
        write(sock, "Hello")
        flush(sock)
        close(sock)
    end

    return 0
end

end

using .SocketTest
```

Compiling **with** `--trim`:

```
julia --project=. ...\contrib\juliac\juliac.jl --experimental --output-exe sockettest --trim SocketTest.jl
```

fails with the following messages:

[SocketTest_Logs.txt](https://github.com/user-attachments/files/21985978/SocketTest_Logs.txt)

Compiling **without** `--trim` succeeds.

### Additional notes

I don't know if this is the correct way to do it (I'm not an expert), but inserting the snippet below into `juliac-trim-stdlib.jl`:
```diff
--- juliac-trim-stdlib_orig.jl	2025-07-13 01:17:33.000000000 +0200
+++ juliac-trim-stdlib.jl	2025-08-26 11:41:23.714173100 +0200
@@ -22,6 +22,19 @@
         end
     end
 
+    Sockets = find_loaded_root_module(Base.PkgId(
+        Base.UUID("6462fe0b-24de-5631-8697-dd941f90decc"), "Sockets"))
+    if Sockets !== nothing
+        @eval Sockets begin
+            function show(io::IO, stream::Base.LibuvStream)
+                print(io, typeof(stream), "(",
+                    Sys.iswindows() ? Base.Libc._get_osfhandle(stream) : Base._fd(stream), " ",
+                    Base.uv_status_string(stream), ", ",
+                    bytesavailable(stream.buffer), " bytes waiting)")
+            end
+        end
+    end
+
     Artifacts = find_loaded_root_module(Base.PkgId(
         Base.UUID("56f22d72-fd6d-98f1-02f0-08ddc0907c33"), "Artifacts"))
     if Artifacts !== nothing
```

seems to fix the errors related to `show()`:

[SocketTest_Logs_ShowFix.txt](https://github.com/user-attachments/files/21985977/SocketTest_Logs_ShowFix.txt)

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #59397

### CODE REVIEW

**Comment by topolarity** [comment]
Probably worth adding `using Sockets` (and more?) to our JLL `--trim` example.

Eventually we can split this out into its own example, but better to have the coverage until that CI is added.

**Comment by JeffBezanson** [comment]
OK I added a test, and separated out the hello test for minimum executable size from tests that various things are trimmable, so that can grow arbitrarily large.

**Review by vtjnash — APPROVED** [review]

File: test/trimming/trimmability.jl [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    tot = sum(sorted_arr)
+    tot = prod(sorted_arr)
+    a = any(x -> x > 0, sorted_arr)
+    b = all(x -> x >= 0, sorted_arr)
+    c = map(x -> x^2, sorted_arr)
+    d = mapreduce(x -> x^2, +, sorted_arr)
+    # e = reduce(xor, rand(Int, 10))
+
+    try
+        sock = connect("localhost", 4900)
```
Comment (nsajko) [inline test/trimming/trimmability.jl:42]: CI for PR #59442 segfaults on this line:

```none
[1246] signal 11 (1): Segmentation fault
in expression starting at none:0
speccache_eq at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:144 [inlined]
speccache_eq at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:136
jl_smallintset_lookup at /cache/build/tester-demeter6-13/julialang/julia-master/src/smallintset.c:137
jl_specializations_get_linfo_ at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:183
cache_method at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:1585
jl_mt_assoc_by_type at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:1867
jl_lookup_generic_ at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:4168 [inlined]
ijl_apply_generic at /cache/build/tester-demeter6-13/julialang/julia-master/src/gf.c:4194
jl_apply at /cache/build/tester-demeter6-13/julialang/julia-master/src/julia.h:2382 [inlined]
jl_uv_call_close_callback at /cache/build/tester-demeter6-13/julialang/julia-master/src/jl_uv.c:171
jl_uv_closeHandle at /cache/build/tester-demeter6-13/julialang/julia-master/src/jl_uv.c:191 [inlined]
jl_uv_closeHandle at /cache/build/tester-demeter6-13/julialang/julia-master/src/jl_uv.c:175
uv__finish_close at /workspace/srcdir/libuv/src/unix/core.c:342
uv__run_closing_handles at /workspace/srcdir/libuv/src/unix/core.c:356
uv_run at /workspace/srcdir/libuv/src/unix/core.c:445
ijl_process_events at /cache/build/tester-demeter6-13/julialang/julia-master/src/jl_uv.c:397
process_events; at ./libuv.jl:133 [inlined]
wait at ./task.jl:1188
#wait#401 at ./condition.jl:141
wait; at ./condition.jl:136 [inlined]
wait_connected at /cache/build/tester-demeter6-13/julialang/julia-master/usr/share/julia/stdlib/v1.13/Sockets/src/Sockets.jl:539
connect; at /cache/build/tester-demeter6-13/julialang/julia-master/usr/share/julia/stdlib/v1.13/Sockets/src/Sockets.jl:579 [inlined]
connect at /cache/build/tester-demeter6-13/julialang/julia-master/usr/share/julia/stdlib/v1.13/Sockets/src/Sockets.jl:564
main at /cache/build/builder-amdci4-5/julialang/julia-master/test/trimming/trimmability.jl:42
_main at /cache/build/builder-amdci4-5/julialang/julia-master/usr/share/julia/juliac/juliac-buildscript.jl:33
main at /cache/build/builder-amdci4-5/julialang/julia-master/usr/bin/trimmability (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x402338) at /workspace/srcdir/glibc-2.17/csu/../sysdeps/x86_64/start.S
Allocations: 1 (Pool: 1; Big: 0); GC: 0
```

Perhaps this is flaky?

CI link:

* https://buildkite.com/julialang/julia-master/builds/50301/steps/canvas?sid=01990f94-ac54-4864-9b1a-cd113ad3c427#01990f94-ac86-4a66-b6f4-f1a96386fafd/1042-1104

Comment (vtjnash) [reply test/trimming/trimmability.jl:42]: I would suggest reverting since this PR broke CI, but there isn't really anything to revert in the source, it is just adding a broken test. Perhaps we can just disable the test until Jeff can fix it?
