### PR TITLE
mark julia threads as initialized

### LINKED ISSUE #105: MethodError when using (indirectly) StaticArrays
Since julia version 0.6 I get an error `Julia exception: MethodError` when I try to call a julia module (https://github.com/gher-ulg/divand.jl/) from python. I tried to track the origin of this error and it seems that it is related to the module StaticArrays (which is used indirectly in my module trough the model Roots, requiring ForewardDiff which requires StaticArrays).

Here is the minimal code which reproduces this issue:

The file `TestModule.jl`:

```julia
module TestModule
# this line generates the error, despite StaticArrays are not used
# RuntimeError: Julia exception: MethodError(TestModule.myx2, (Any[1, 2, 3],), 0x0000000000005537)
using StaticArrays
myx2(x)  = x.^2

export myx2
end
```

The file `test_simple_module.py`:

```python
import julia
j = julia.Julia()
# add to directory to TestModule.jl
j.eval('push!(LOAD_PATH,joinpath(ENV["HOME"],"projects/Julia/share"))')
j.using('TestModule')
print j.myx2([1,2,3])
```

I run this example as:

```bash
~/.julia/v0.6/Conda/deps/usr/bin/python2.7 test_simple_module.py
```
The produces the following error:
```
WARNING: redefining constant JULIA_HOME
Traceback (most recent call last):
  File "test_simple_module.py", line 6, in <module>
    print j.myx2([1,2,3])
RuntimeError: Julia exception: MethodError(TestModule.myx2, (Any[1, 2, 3],), 0x0000000000005537)
```

(The python interpreter that comes with my Ubuntu installation produces a Segmentation fault)

One can also reproduce this error by just copying 2 lines from `StaticArrays`:

```julia
module TestModule
# The error above can also be reproduced by just including these two lines from StaticArrays.jl
# from StaticArrays/src/StaticArrays.jl
abstract type StaticArray{S <: Tuple, T, N} <: AbstractArray{T, N} end
# from StaticArrays/src/convert.jl:3
@inline (::Type{SA})(x...) where {SA <: StaticArray} = SA(x)

myx2(x)  = x.^2

export myx2
end
```

In particular it is the conversion operation `(::Type{SA})(x...)` which generates this `MethodError` error.
I am using `pyjulia` current as of today (last update Fri Jun 16 22:59:09 2017, commit  d01b42b).
229 packages depend on `StaticArrays`. It is possible that this issue affect other packages as well.

Any help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by vtjnash**
This ensures that cfunction can see that Julia state is initialized on this thread, and thus letting it run in the newest world age.

I think this should fix https://github.com/JuliaPy/pyjulia/issues/105, although I don't have pyjulia installed right now to test.

### CODE REVIEW

**Comment by ararslan** [comment]
Is it possible to add a test for this?

**Review by Keno — APPROVED** [review]
Confirmed to fix the pyjulia issue. Does need a test. Probably the embedding test is the right place to put this.

File: examples/embedding/embedding.c [hunk 1]
```diff
@@ -40,62 +57,98 @@ int main()
...
     }
 
     {
         // 1D arrays
 
-        jl_value_t* array_type = jl_apply_array_type( (jl_value_t*)jl_float64_type, 1 );
-        jl_array_t* x          = jl_alloc_array_1d(array_type , 10);
+        jl_value_t* array_type = jl_apply_array_type((jl_value_t*)jl_float64_type, 1);
+        jl_array_t* x          = jl_alloc_array_1d(array_type, 10);
+        // JL_GC_PUSH* is required here to ensures that `x` is not deleted
```
Comment (tkelman) [inline examples/embedding/embedding.c]: to ensure that
