### PR TITLE
fix #15722, support BigInts in precompiled modules and sysimg

### LINKED ISSUE #15722: big_str is dangerous in combination with compilation
```
__precompile__()
module Crash
const x = big"123"
__init__() = @show x
end # module
```

```
julia> using Crash
INFO: Precompiling module Crash...

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
__gmpz_get_str at /home/ubuntu/julia-debugger/usr/bin/../lib/libgmp.so (unknown line)
base at ./gmp.jl:518
[inline] at ./gmp.jl:509
showall at ./show.jl:1428
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is ugly, but I think it's necessary if we're going to do #26991.

The only limitation here is that you can't mutate BigInts from the system image, but I think that's acceptable since we don't expose a mutating API, constants shouldn't be mutated anyway, and we typically have more control over what goes into a system image (as opposed to a precompiled package).

### CODE REVIEW

File: src/dump.c [hunk 1]
```diff
@@ -921,6 +922,17 @@ static void jl_serialize_value_(jl_serializer_state *s, jl_value_t *v, int as_li
         for (i = 0; i < jl_datatype_nfields(jl_lineinfonode_type); i++)
             jl_serialize_value(s, jl_get_nth_field(v, i));
     }
+    else if (jl_bigint_type && jl_typeis(v, jl_bigint_type)) {
+        write_uint8(s->s, TAG_SHORT_GENERAL);
+        write_uint8(s->s, ((jl_datatype_t*)jl_bigint_type)->size);
```
Comment (vtjnash) [inline src/dump.c]: `jl_datatype_size`
