### PR TITLE
Fix integer overflow in `isapprox`

### LINKED ISSUE #50380: `isapprox` can give absurd result in case of integer overflow
I was surprised to realize this:
```julia
julia> Int8(-68) ≈ Int8(60)
true
```

This is because of the way the `isapprox` fallback is defined, and more precisely to:
```julia
julia> abs(Int8(-68) - Int8(60))
-128
```

Shouldn't we define a custom method for integers that is robust to overflow`?

### PR DESCRIPTION
**Pull request by nalimilan**
Ensure that `isapprox` gives correct results when comparing an integer with another integer or with a float. For comparison between integers, the fix only works when keeping default values for `rtol` and `norm`, and with `atol < 1`.

It is not possible to handle the (atypical) case where `norm !== abs`, but that's OK since the user is responsible for providing a safe function.

It would be possible to handle the case where `rtol > 0` or `atol >= 1`, but with complex code which would check for overflow and handle all possible corner cases; it would work only for types defined in Base and would not be extensible by packages. So I'm not sure that's worth it. At least with PR fixes the most common case.

Fixes https://github.com/JuliaLang/julia/issues/50380.

### CODE REVIEW

File: base/floatfuncs.jl [hunk 1]
```diff
@@ -304,7 +304,20 @@ true
 function isapprox(x::Number, y::Number;
                   atol::Real=0, rtol::Real=rtoldefault(x,y,atol),
                   nans::Bool=false, norm::Function=abs)
-    x == y || (isfinite(x) && isfinite(y) && norm(x-y) <= max(atol, rtol*max(norm(x), norm(y)))) || (nans && isnan(x) && isnan(y))
+    x′, y′ = promote(x, y) # to avoid integer overflow
+    x == y ||
+        (isfinite(x) && isfinite(y) && norm(x-y) <= max(atol, rtol*max(norm(x′), norm(y′)))) ||
```
Comment (nalimilan) [inline base/floatfuncs.jl:309]: Technically this can give slightly different results than before even in the absence of overflow, since promotion may round values larger than `maxintfloat`, giving a slightly different tolerance. But this should be OK.

File: base/floatfuncs.jl [hunk 2]
```diff
@@ -304,7 +304,20 @@ true
 function isapprox(x::Number, y::Number;
                   atol::Real=0, rtol::Real=rtoldefault(x,y,atol),
                   nans::Bool=false, norm::Function=abs)
-    x == y || (isfinite(x) && isfinite(y) && norm(x-y) <= max(atol, rtol*max(norm(x), norm(y)))) || (nans && isnan(x) && isnan(y))
+    x′, y′ = promote(x, y) # to avoid integer overflow
```
Comment (oscardssmith) [inline base/floatfuncs.jl:307]: If we have the other method, why do we need to widen here?

Comment (nalimilan) [reply base/floatfuncs.jl:307]: Because the other method is called only when both values are integer, but here `norm(x)` can overflow if `x` is an integer and `y` is a float. See tests added by the same commit.

**Review by stevengj — APPROVED** [review]
