### PR TITLE
avoid corrupting String on conversion of StringVector to String

### LINKED ISSUE #39717: Segfault in regex `match`ing
The following snippet
```julia
import HTTP
resp = HTTP.get("https://finance.yahoo.com/quote/A/financials", status_exception = true)
body = String(resp.body)
m = match(r"root\.App\.main = (.*);$"m, resp.body |> String)
```
gives me a segfault:
```
❯ julia --project 2-3-21/segfault.jl

signal (11): Segmentation fault: 11
in expression starting at none:0
gc_setmark_pool_ at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:0 [inlined]
gc_setmark_pool at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:751 [inlined]
gc_setmark at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:758 [inlined]
gc_mark_loop at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:2572
_jl_gc_collect at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:2902
jl_gc_collect at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:3108
maybe_collect at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:827 [inlined]
jl_gc_pool_alloc at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:1142
UseRef at ./compiler/ssair/ir.jl:263 [inlined]
UseRefIterator at ./compiler/ssair/ir.jl:268 [inlined]
userefs at ./compiler/ssair/ir.jl:382 [inlined]
renumber_ssa2! at ./compiler/ssair/ir.jl:810
process_node! at ./compiler/ssair/ir.jl:925
process_node! at ./compiler/ssair/ir.jl:984 [inlined]
iterate at ./compiler/ssair/ir.jl:1151
iterate at ./compiler/ssair/ir.jl:1094 [inlined]
foreach at ./abstractarray.jl:2009 [inlined]
compact! at ./compiler/ssair/ir.jl:1298
compact! at ./compiler/ssair/ir.jl:1296 [inlined]
run_passes at ./compiler/ssair/driver.jl:137
optimize at ./compiler/optimize.jl:174
typeinf at ./compiler/typeinfer.jl:33
typeinf_ext at ./compiler/typeinfer.jl:570
typeinf_ext at ./compiler/typeinfer.jl:601
jfptr_typeinf_ext_21449.clone_1 at /Applications/Julia-1.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1690 [inlined]
jl_type_infer at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:296
jl_generate_fptr at /Users/julia/buildbot/worker/package_macos64/build/src/jitlayers.cpp:290
jl_compile_method_internal at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1964
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2224 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2398
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1690 [inlined]
run_finalizer at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:277
jl_gc_run_finalizers_in_list at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:363
run_finalizers at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:391 [inlined]
jl_gc_run_all_finalizers at /Users/julia/buildbot/worker/package_macos64/build/src/gc.c:428
jl_atexit_hook at /Users/julia/buildbot/worker/package_macos64/build/src/init.c:245
main at /usr/local/bin/julia (unknown line)
Allocations: 12847820 (Pool: 12844466; Big: 3354); GC: 13
zsh: segmentation fault  julia --project 2-3-21/segfault.jl
```

I'm running 
```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
and
```
(Sam-David) pkg> st -m
Status `~/Dropbox/Sam-David/Manifest.toml`
  [c7e460c6] ArgParse v1.1.1
  [56f22d72] Artifacts v1.3.0
  [fbb218c0] BSON v0.2.6
  [336ed68f] CSV v0.8.3
  [324d7699] CategoricalArrays v0.9.2
  [944b1d66] CodecZlib v0.7.0
  [34da2185] Compat v3.25.0
  [a8cc5b0e] Crayons v4.0.4
  [9a962f9c] DataAPI v1.6.0
  [a93c6f00] DataFrames v0.22.5
  [864edb3b] DataStructures v0.18.9
  [e2d170a0] DataValueInterfaces v1.0.0
  [e7dc6d0d] DataValues v0.4.13
  [e2ba6199] ExprTools v0.1.3
  [8f5d6c58] EzXML v1.1.0
  [48062228] FilePathsBase v0.9.9
  [59287772] Formatting v0.4.2
  [cd3eb016] HTTP v0.9.3
  [83e8ac13] IniFile v0.5.0
  [41ab1584] InvertedIndices v1.0.0
  [1c8ee90f] IterableTables v1.0.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.2.0
  [9da8a3cd] JLSO v2.4.0
  [682c06a0] JSON v0.21.1
  [94ce4f54] Libiconv_jll v1.16.0+7
  [1914dd2f] MacroTools v0.5.6
  [739be429] MbedTLS v1.0.3
  [c8ffd9c3] MbedTLS_jll v2.16.8+1
  [f28f55f0] Memento v1.1.2
  [e1d29d7a] Missings v0.4.5
  [78c3b35d] Mocking v0.7.1
  [bac558e1] OrderedCollections v1.4.0
  [69de0a69] Parsers v1.0.15
  [2dfb63ee] PooledArrays v1.1.0
  [08abe8d2] PrettyTables v0.11.1
  [92933f4c] ProgressMeter v1.5.0
  [1a8c2f83] Query v1.0.0
  [2aef5ad7] QueryOperators v0.9.3
  [3cdcf5f2] RecipesBase v1.1.1
  [189a3867] Reexport v1.0.0
  [ae029012] Requires v1.1.2
  [91c51154] SentinelArrays v1.2.16
  [a2af1166] SortingAlgorithms v0.3.1
  [856f2bd8] StructTypes v1.2.3
  [cea106d9] Syslogs v0.3.0
  [5e66a065] TableShowUtils v0.2.5
  [3783bdb8] TableTraits v1.0.0
  [382cd787] TableTraitsUtils v1.0.1
  [bd369af6] Tables v1.3.2
  [b718987f] TextWrap v1.0.1
  [f269a46b] TimeZones v1.5.3
  [3bb67fe8] TranscodingStreams v0.9.5
  [5c2747f8] URIs v1.2.0
  [fdbf4ff8] XLSX v0.7.6
  [02c8fc9c] XML2_jll v2.9.10+3
  [a5390f91] ZipFile v0.9.3
  [83775a58] Zlib_jll v1.2.11+18
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
```

My best guess is that it's because `resp.body` is getting read twice. On the second occasion, there's nothing left to be read, which should result in an empty string. Somehow, I'm guessing, this ends up being a null pointer/bad pointer when passing things off to the PCRE library. This is all just guesswork however.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #39717

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

File: src/array.c [hunk 1]
```diff
@@ -483,6 +483,12 @@ JL_DLLEXPORT jl_array_t *jl_pchar_to_array(const char *str, size_t len)
 JL_DLLEXPORT jl_value_t *jl_array_to_string(jl_array_t *a)
 {
     size_t len = jl_array_len(a);
+    if (len == 0) {
+        // this may seem like purely an optimization (which it also is), but it
+        // also ensures that calling `String(a)` doesn't corrupt a previous
```
Comment (quinnj) [inline src/array.c:488]: Just curious, but why/how exactly does a previous string get corrupted w/o this? The segfault seems to be gc-related; something about the original string now being "shared" between two strings?

Comment (vtjnash) [reply src/array.c:488]: We truncate the array here (so that future uses will get a fresh data object), but that ends up truncating the string later, if it is still the data pointer and we call this immediately. See the added tests.

**Review by JeffBezanson — APPROVED** [review]
