### PR TITLE
fix #17997, don't load packages in `Main`

### LINKED ISSUE #17997: don't load packages into `Main` by default?
This came up recently and there doesn't seem to be an issue about it.

The problem is that `Main` is both the default interactive namespace, and the "root" namespace used for loading packages. For example, say we have

```
module A
using B
end
```

If I do `using A` at the prompt, I also see `B` defined. However when other modules do `using A` they don't see `B` at all. (Note this does _not_ have the same effect as `using B` at the prompt; you only see the symbol `B` itself, and still can't see things from inside `B`.)

In the original implementation of modules in 2012 there was a module called `Root` where packages were loaded, and interaction happened in `Root.Main`. We decided this was more complex than necessary and changed it pretty quickly, just a couple months later I believe.

I don't feel like I have tripped over this issue much myself, but it bears discussing.

### LINKED ISSUE #21969: Precompilation fails with Iterators.jl dependency
Example:

```julia
using DifferentialEquations

INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\Combinatorics.ji for module Combinatorics.
WARNING: The call to compilecache failed to create a usable precompiled cache file for module Combinatorics. Got:
WARNING: Module Iterators uuid did not match cache file.
```

Also posted at https://github.com/JunoLab/Atom.jl/issues/86. For some reason, the REPL works but Juno fails often, and if I hit it with a few `using`s in the REPL (for some reason, a few), and then close and re-open Juno, it's finally able to find the right precompilation caches. I'm not entirely sure if this is Juno or Base.

### PR DESCRIPTION
**Pull request by JeffBezanson**
This refactors loading so that top-level modules are stored in an internal table instead of exposed in `Main`. It's close to working, but currently still fails a couple of the `compile` tests.

Each top-level module has an identifying key. Currently, this is just a Symbol of the module name like we use now, but designed to be generalized. This adds a small API to the loader to manage top-level ("root") modules:

- `is_root_module(m)`: Test whether `m` is a root module, which means it needs to be identified by a loader key.
- `root_module(key)`: Get the root module with the given key.
- `root_module_key(m)`: Get the key for a root module.
- `root_module_exists(key)`: Test whether a module with the given key has been loaded.
- `register_root_module(key, mod)`: Record that a given root module is available under a certain key.
- `require(name)`: In `using Foo`, this function accepts `:Foo` and returns the module it should map to. `:Foo` can either be used directly as a module key, or (in the near future, IIUC) combined with an environment to look up a UUID to use as the key.

This API replaces introspection of the `Main` module in various places.

close #17997
close #21969

### CODE REVIEW

File: src/toplevel.c [hunk 1]
```diff
@@ -339,99 +336,87 @@ static int jl_eval_expr_with_compiler_p(jl_value_t *e, int compileloops, jl_modu
...
-        assert(jl_is_symbol(s));
-        m = (jl_module_t*)jl_eval_global_var(m, (jl_sym_t*)s);
+        var = (jl_sym_t*)jl_array_ptr_ref(args, i);
+        if (!jl_is_symbol(var))
+            jl_type_error("import or using", (jl_value_t*)jl_sym_type, (jl_value_t*)var);
+        if (i == jl_array_len(args)-1)
+            break;
+        m = (jl_module_t*)jl_eval_global_var(m, var);
         if (!jl_is_module(m))
             jl_errorf("invalid import statement");
```
Comment (vtjnash) [inline src/toplevel.c]: could use a better error message here, since this sounds like the syntax is invalid: `s/statement/path: %s is not a module/`

File: src/toplevel.c [hunk 2]
```diff
@@ -339,99 +336,87 @@ static int jl_eval_expr_with_compiler_p(jl_value_t *e, int compileloops, jl_modu
...
-        }
-    }
-
-    for(; i < jl_array_len(args)-1; i++) {
-        jl_value_t *s = jl_array_ptr_ref(args,i);
-        assert(jl_is_symbol(s));
-        m = (jl_module_t*)jl_eval_global_var(m, (jl_sym_t*)s);
+        var = (jl_sym_t*)jl_array_ptr_ref(args, i);
+        if (!jl_is_symbol(var))
+            jl_type_error("import or using", (jl_value_t*)jl_sym_type, (jl_value_t*)var);
```
Comment (vtjnash) [inline src/toplevel.c]: pass the right name (import or using) as an argument? not super important, but seems like it should be trivial enough

File: src/toplevel.c [hunk 3]
```diff
@@ -339,99 +336,87 @@ static int jl_eval_expr_with_compiler_p(jl_value_t *e, int compileloops, jl_modu
...
+static jl_value_t *root_module_func=NULL;
+
+jl_module_t *jl_lookup_root_module(jl_value_t *key)
+{
+    if (root_module_func == NULL && jl_base_module != NULL)
+        root_module_func = jl_get_global(jl_base_module, jl_symbol("root_module"));
+    jl_value_t *m = NULL;
+    if (root_module_func != NULL) {
+        jl_value_t *rmargs[2] = {root_module_func, key};
+        m = jl_apply(rmargs, 2);
```
Comment (vtjnash) [inline src/toplevel.c]: the system state will get severely corrupted if you call `jl_apply` from this context

File: base/loading.jl [hunk 4]
```diff
@@ -315,25 +316,66 @@ all platforms, including those with case-insensitive filesystems like macOS and
...
+            invokelatest(callback, mod)
+        end
+    end
+    return M
+end
+
+const loaded_modules = ObjectIdDict()
+const module_keys = ObjectIdDict()
+
+function register_root_module(key, m::Module)
```
Comment (vtjnash) [inline base/loading.jl]: This seems like a bad idea. Maybe `require` should set a global flag (`haskey(package_locks, m)` or perhaps better would be `isempty(package_locks)`) that disables rooting of the object in `Main.m`?

File: base/loading.jl [hunk 5]
```diff
@@ -288,6 +288,7 @@ function reload(name::AbstractString)
         error("use `include` instead of `reload` to load source files")
     else
         # reload("Package") is ok
+        delete!(loaded_modules, Symbol(name))
```
Comment (vtjnash) [inline base/loading.jl]: This seems like it can be losing gc-roots. Although in practice, it will perhaps often get rooted in the Tuple type cache, I'm not sure if that'll be entirely sufficient to make sure the contained types can get garbage-collected while there is still instances of their objects around.

File: base/loading.jl [hunk 6]
```diff
@@ -345,7 +387,7 @@ function _require(mod::Symbol)
     if loading !== false
         # load already in progress for this module
         wait(loading)
```
Comment (vtjnash) [inline base/loading.jl]: return `wait(loading)`?

File: base/loading.jl [hunk 7]
```diff
@@ -364,7 +406,9 @@ function _require(mod::Symbol)
         if JLOptions().use_compilecache != 0
             doneprecompile = _require_search_from_serialized(mod, path)
             if !isa(doneprecompile, Bool)
-                return # success
+                M = doneprecompile[end]
```
Comment (vtjnash) [inline base/loading.jl]: this list isn't sorted by that key (it's sorted by load order), I think you'll need to scan it to find when the module you wanted was defined

File: base/loading.jl [hunk 8]
```diff
@@ -391,14 +435,20 @@ function _require(mod::Symbol)
...
 
         # just load the file normally via include
         # for unknown dependencies
+        local M
         try
-            Base.include_relative(Main, path)
+            # TODO: this is a hack to handle circular module references
+            tempmod = Module(temp_mod_name)
+            loaded_modules[mod] = tempmod
+            M = Base.include_relative(tempmod, path)
```
Comment (vtjnash) [inline base/loading.jl]: This isn't currently expected to return a module. We'll need to add a deprecation warning here if we want to change the API.

**Review by vtjnash — COMMENTED** [review]
👍

File: src/dump.c [hunk 9]
```diff
@@ -1514,7 +1516,11 @@ static jl_value_t *jl_deserialize_value_module(jl_serializer_state *s)
     jl_sym_t *mname = (jl_sym_t*)jl_deserialize_value(s, NULL);
     int ref_only = read_uint8(s->s);
     if (ref_only) {
-        jl_value_t *m_ref = jl_get_global((jl_module_t*)jl_deserialize_value(s, NULL), mname);
+        jl_value_t *m_ref;
+        if (ref_only == 1)
+            m_ref = jl_get_global((jl_module_t*)jl_deserialize_value(s, NULL), mname);
+        else
+            m_ref = (jl_value_t*)jl_lookup_root_module((jl_value_t*)mname);
```
[the remark this answers is not in the document]
Comment (JeffBezanson) [reply src/dump.c]: What can I return from this function then?

File: src/dump.c [hunk 10]
```diff
@@ -2001,23 +2004,8 @@ static void jl_reinit_item(jl_value_t *v, int how, arraylist_t *tracee_list)
...
-                    if (jl_generating_output() && jl_options.incremental) {
-                        jl_errorf("Cannot replace module %s during incremental precompile.", jl_symbol_name(mod->name));
-                    }
-                    jl_printf(JL_STDERR, "WARNING: replacing module %s.\n",
-                              jl_symbol_name(mod->name));
-                }
-                b->value = v;
-                jl_gc_wb_binding(b, v);
+            case 2: {
+                // top level modules handled by loader
```
[the remark this answers is not in the document]
Comment (JeffBezanson) [reply src/dump.c]: Aren't submodules handled just by deserializing bindings and their values?

File: base/loading.jl (hunk 4 above)
Comment (JeffBezanson) [reply base/loading.jl]: This function is really only meant for internal use. Nobody but the loading code should call it. Does that address your concern, or is there something else?

File: base/loading.jl (hunk 5 above)
Comment (JeffBezanson) [reply base/loading.jl]: Agreed, we can just keep an old-modules list.

File: src/dump.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply src/dump.c]: In some cases, yes. But this code also handles conditional-require (the behavior of adding them to Main was just a side-detail).

File: src/dump.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply src/dump.c]: Er, you can't. All external state must be prepared by `read_verify_mod_list`, once `jl_deserialize_value` starts in earnest, this can only return existing references into that array.

File: base/loading.jl (hunk 4 above)
Comment (vtjnash) [reply base/loading.jl]: This design appears to assume there will be a 1-to-1 correlation between `require` and module definition, which doesn't always happen now. I think a simpler design would be handle that decision point during construction, rather than post-factum mutation.

File: src/dump.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (JeffBezanson) [reply src/dump.c]: This doesn't change any global state --- it just looks up the module by name.

File: base/loading.jl (hunk 4 above)
Comment (JeffBezanson) [reply base/loading.jl]: I think we'll be able to handle it either way. If loading something defines 0 modules, we can store `nothing` here instead of a module (to provide "load once" semantics). If a file defines multiple modules, you won't be able to reference all of them without a distinct `using` statement for each one you want anyway. But we should definitely discourage or disallow that. @StefanKarpinski even briefly floated the idea of removing the `module` keyword (or making it optional), and having the loader make modules instead (thus enforcing 1-to-1 file-to-module by construction).

**Comment by JeffBezanson** [comment]
@vtjnash The main thing I'm having trouble with here is the infamous `2.0 === 97.0` failure in the compile tests. I haven't yet figured out what's causing it. Is there an invalidation step I missed that relies on things being in `Main`?

**Comment by JeffBezanson** [comment]
After making this change, Documenter no longer worked with just `using Documenter`. Somehow it requires a hard binding for `Documenter` in `Main`, possibly due to calling `names`. I got around this for now by adding an ad-hoc rule: if you write `using X` in `Main` then a hard binding for `X` is also added. We might want to do that everywhere, which would also allow removing the self binding (`Base.Base`) that exists in every module.

**Comment by JeffBezanson** [comment]
I think this is ready to go.

File: src/dump.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply src/dump.c]: This should just be using an index into `mod_array = jl_get_loaded_modules();` (as deserialized by `read_verify_mod_list`)

File: base/loading.jl [hunk 11]
```diff
@@ -315,25 +316,86 @@ all platforms, including those with case-insensitive filesystems like macOS and
...
+    for m in a
+        if module_parent(m) === m
+            register_root_module(module_name(m), m)
+        end
     end
 end
 
 function _require(mod::Symbol)
+    if root_module_exists(mod)
+        return root_module(mod)
```
Comment (vtjnash) [inline base/loading.jl]: It looks weird to require that all exit points to this function call the function `root_module(mod)` and return the result. Seems like this should be handled in the caller instead.

File: examples/clustermanager/0mq/ZMQCM.jl [hunk 12]
```diff
@@ -1,6 +1,10 @@
 # This file is a part of Julia. License is MIT: https://julialang.org/license
 
-using ZMQ
+# the 0mq clustermanager depends on package ZMQ. For testing purposes, at least
+# make sure the code loads without it.
+try
+    using ZMQ
+end
```
Comment (vtjnash) [inline examples/clustermanager/0mq/ZMQCM.jl]: revert?

Comment (JeffBezanson) [reply examples/clustermanager/0mq/ZMQCM.jl]: This test is intended to work without ZMQ installed. Previously this was handled by putting a fake empty `ZMQ` module in Main.

File: base/interactiveutil.jl [hunk 13]
```diff
@@ -566,7 +566,7 @@ end
 Return an array of methods with an argument of type `typ`.
 
 The optional second argument restricts the search to a particular module or function
-(the default is all modules, starting from Main).
+(the default is all modules).
```
Comment (vtjnash) [inline base/interactiveutil.jl]: New implementation doesn't do this anymore. I'm not against making it recursive, but it should be consistent, and possibly in a separate commit / PR.

File: src/dump.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (JeffBezanson) [reply src/dump.c]: Ok, I'll try that.

**Comment by JeffBezanson** [comment]
Comments addressed.

**Comment by JeffBezanson** [comment]
@vtjnash You'll probably want to take another look to make sure I didn't make a total hash of dump.c.

File: src/toplevel.c [hunk 14]
```diff
@@ -120,6 +120,35 @@ static void jl_module_load_time_initialize(jl_module_t *m)
     }
 }
 
+jl_module_t *jl_lookup_root_module(jl_value_t *key)
+{
+    jl_value_t *loaded_modules = jl_get_global(jl_base_module, jl_symbol("loaded_modules"));
+    jl_array_t *ht = (jl_array_t*)jl_get_nth_field(loaded_modules, 0);
+    assert(jl_is_array(ht));
+    return (jl_module_t*)jl_eqtable_get(ht, key, NULL);
+}
```
Comment (vtjnash) [inline src/toplevel.c]: drop this function (unused now)

File: examples/clustermanager/0mq/ZMQCM.jl (hunk 12 above)
Comment (vtjnash) [reply examples/clustermanager/0mq/ZMQCM.jl]: Could we now always just put a fake module in `Base.__toplevel__` instead?

File: base/loading.jl [hunk 15]
```diff
@@ -288,6 +288,7 @@ function reload(name::AbstractString)
         error("use `include` instead of `reload` to load source files")
     else
         # reload("Package") is ok
+        unreference_module(Symbol(name))
```
Comment (vtjnash) [inline base/loading.jl]: should be unnecessary

File: base/loading.jl [hunk 16]
```diff
@@ -315,21 +316,78 @@ all platforms, including those with case-insensitive filesystems like macOS and
...
+
+const loaded_modules = ObjectIdDict()
+const module_keys = ObjectIdDict()
+
+function register_root_module(key, m::Module)
+    if haskey(loaded_modules, key)
+        oldm = loaded_modules[key]
+        if oldm !== m
+            name = module_name(oldm)
+            warn("replacing module $name.")
```
Comment (vtjnash) [inline base/loading.jl]: Are we doing Uppercase messages? I don't precisely remember what style we've started to settle on.

File: base/loading.jl [hunk 17]
```diff
@@ -391,14 +450,17 @@ function _require(mod::Symbol)
...
             else
-                return # success
+                register_all(m)
+                return
             end
         end
 
         # just load the file normally via include
         # for unknown dependencies
+        local M
```
Comment (vtjnash) [inline base/loading.jl]: `M` is unused?

File: base/interactiveutil.jl [hunk 18]
```diff
@@ -678,8 +673,7 @@ download(url, filename)
     workspace()
 
 Replace the top-level module (`Main`) with a new one, providing a clean workspace. The
-previous `Main` module is made available as `LastMain`. A previously-loaded package can be
-accessed using a statement such as `using LastMain.Package`.
```
Comment (vtjnash) [inline base/interactiveutil.jl]: How does one do this now? / What does `workspace()` do? / Should we add `empty!(Base. loaded_modules)`, and (re-)register the new modules with `register_root_module`? / Should we add a new function to do that (`Base.reset_require()` or argument to `workspace`) instead?

Comment (JeffBezanson) [reply base/interactiveutil.jl]: I'll update the doc string. I think `workspace()` should *just* give you a new Main module. So `using X` in the new Main module will point to the already-loaded copy. To re-load packages there is `reload`.

File: examples/clustermanager/0mq/ZMQCM.jl (hunk 12 above)
Comment (JeffBezanson) [reply examples/clustermanager/0mq/ZMQCM.jl]: I wouldn't encourage that. We would need a better official way to mock out packages. Would probably need more design to fully work with pkg3.

File: base/loading.jl (hunk 16 above)
Comment (JeffBezanson) [reply base/loading.jl]: We don't seem to be totally consistent yet. On a quick search it's close to 50/50. There are some other occurrences of this same message that are lowercase.

**Comment by StefanKarpinski** [comment]
Oh yeah, it's party time now.

**Comment by vtjnash** [comment]
Can you fix PkgEval ASAP (I think this is the cause of the breakage)? Otherwise, I think we should temporarily revert this tomorrow, so that we prepare a fix for the breakage at a more leisurely pace.

**Comment by JeffBezanson** [comment]
Do you have a link to a description of the problem?

I really don't think we need to revert this --- PkgEval does not need to work 100% of the time on master. Posting a fix ASAP should be good enough.

**Comment by KristofferC** [comment]
I think this also broke JLD? https://github.com/JuliaLang/julia/commit/ff9fb483172ad792c47b7652eff1173044f3b9ae

**Comment by ararslan** [comment]
It broke Nanosoldier via the JLD breakage

**Comment by timholy** [comment]
Probably the source of this?
```julia
julia> module A
       export foo
       foo() = 1
       end
Main.A

julia> using A
ERROR: ArgumentError: Module A not found in current path.
Run `Pkg.add("A")` to install the A package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:417
 [2] require(::Symbol) at ./loading.jl:320

julia> A.foo()
1

julia> foo()
ERROR: UndefVarError: foo not defined
```

**Comment by timholy** [comment]
Also worth mentioning that something (probably this?) broke Revise:
```julia
julia> using Revise
init
mod = Main
_module_name(ex) = :Revise
names(Main) = 5-element Array{Symbol,1}:
 :Base     
 :Core     
 :Main     
ERROR: UndefVarError: Revise not defined
Stacktrace:
 [1] parse_module!(::Dict{Module,DataStructures.OrderedSet{Revise.RelocatableExpr}}, ::Expr, ::Symbol, ::Module, ::String) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:521
 [2] parse_expr!(::Dict{Module,DataStructures.OrderedSet{Revise.RelocatableExpr}}, ::Expr, ::Symbol, ::Module, ::Any) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:456
 [3] parse_source!(::Dict{Module,DataStructures.OrderedSet{Revise.RelocatableExpr}}, ::String, ::Symbol, ::Int64, ::Module, ::Any) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:402
 [4] parse_source!(::Dict{Module,DataStructures.OrderedSet{Revise.RelocatableExpr}}, ::String, ::Module, ::String) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:364
 [5] parse_source(::String, ::Module, ::String) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:338
 [6] parse_pkg_files(::Symbol) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:302
 [7] watch_package(::Symbol) at /home/tim/.julia/v0.7/Revise/src/Revise.jl:548
 [8] (::getfield(Base, Symbol("#inner#4")){Array{Any,1},typeof(Revise.watch_package),Tuple{Symbol}})() at ./essentials.jl:660
 [9] require(::Symbol) at ./loading.jl:333
```
Output is from adding a `println("init")` at the top of the `__init__` function and
```julia
@show mod _module_name(ex) names(Main)
```
just above [the line that triggered the error](https://github.com/timholy/Revise.jl/blob/cf06d0d6d13cad25246568499fb1d7a2690a4b33/src/Revise.jl#L520). Yet
```julia
julia> using FixedPointNumbers

julia> getfield(Main, :FixedPointNumbers)
FixedPointNumbers
```
still seems to work fine, so it's a puzzling (scope?) error.

**Comment by fredrikekre** [comment]
`using .A` works. And I kind of like that the dot is needed, since that is what you would have to do if the module was defined in another module, e.g.
```julia
julia> module A
       module B
       end
       using .B # . needed here, just like in the REPL now
       end
```

**Comment by nalimilan** [comment]
Related regression: the following now fails.
```julia
module A
    module B
    end

    @eval Main using $(Symbol(@__MODULE__)).B
end
```

It sounds unexpected that `@__MODULE__` does not give the correct name allowing to load a module. Is there a better way of doing this? (I need this kind of thing to test the REPL at #23806.)

**Comment by yuyichao** [comment]
You can still do `.A.B` or `Main.A.B`. Note that `@__MODULE__` here is just `A`.

Also note that this is not a safe assumption to make in the test. You should directly eval the whole thing in `Main` instead.

**Comment by yuyichao** [comment]
> It sounds unexpected that `@__MODULE__` does not give the correct name allowing to load a module.

And FWIW, it never was....

**Comment by nalimilan** [comment]
@yuyichao My problem is that `Base.runtests` creates modules with unpredictable names. Hence the hackish code to load a module in the fake REPL for testing purposes. Simpler solution welcome.

**Comment by yuyichao** [comment]
That's exactly what I said, you shouldn't try to get that name in the first place. You should

> directly eval the whole thing in `Main` instead.

**Comment by nalimilan** [comment]
I can do that, though that's not pretty in the context of that REPL test.

**Comment by yuyichao** [comment]
It's as pretty as it can possibly be (much better than hacking a import path), much closer to what the REPL is actually used for (evaluating code in the REPL and not somewhere else), and is a fundamental property of the REPL.
