### PR TITLE
optimizer: bail out of inlining if ir_inline_unionsplit will fail

### LINKED ISSUE #44238: Internal error in runtime when testing Polyhedra.jl
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f51f24c_vs_2ca8b0c/Polyhedra.primary.log

```
Internal error: encountered unexpected error in runtime:
MethodError(f=Base.string, args=(Expr(:call, :==, Expr(:call, :length, :aparams), Expr(:call, :length, :mparams)),), world=0x000000000000124a)
jl_method_error_bare at /workspace/srcdir/src/gf.c:1851
jl_method_error at /workspace/srcdir/src/gf.c:1869
jl_lookup_generic_ at /workspace/srcdir/src/gf.c:2494 [inlined]
ijl_apply_generic at /workspace/srcdir/src/gf.c:2509
macro expansion at ./error.jl:231 [inlined]
ir_inline_unionsplit! at ./compiler/ssair/inlining.jl:483
batch_inline! at ./compiler/ssair/inlining.jl:617
ssa_inlining_pass! at ./compiler/ssair/inlining.jl:85
jfptr_ssa_inlining_passNOT._15640.clone_1 at /opt/julia/lib/julia/sys.so (unknown line)
_jl_invoke at /workspace/srcdir/src/gf.c:2331 [inlined]
ijl_apply_generic at /workspace/srcdir/src/gf.c:2513
run_passes at ./compiler/optimize.jl:514
optimize at ./compiler/optimize.jl:505 [inlined]
_typeinf at ./compiler/typeinfer.jl:253
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:856
abstract_call_method at ./compiler/abstractinterpretation.jl:593
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:132
abstract_call_known at ./compiler/abstractinterpretation.jl:1593
...
```

Seems to error here:

https://github.com/JuliaLang/julia/blob/2db86f2360a03530b34b1d35bd86fb53fa841422/base/compiler/ssair/inlining.jl#L483

### PR DESCRIPTION
**Pull request by vtjnash**
Intersection cannot deal with this `metharg`, so it does not simplify
the type at all when handling this case. This can cause us to run into
an assertion later, where we assume the intersection of a non-Varags
type will always return a simple DataType without Varargs.

Fixes #44238

    atype = Tuple{typeof(Base.similar),
      Tuple{Union{Polyhedra.Polyhedron{T}, Polyhedra.Representation{T}} where T},
      Array{_A, 1} where _A,
      Array{_C, 1} where _C,
      Array{_B, 1} where _B}

    metharg = Tuple{typeof(Base.similar),
      Tuple{Vararg{Union{Polyhedra.Polyhedron{T}, Polyhedra.Representation{T}} where T}},
      Vararg{Union{Union{AbstractArray{var"#s14", 1}, Polyhedra.AbstractRepIterator{var"#s13", var"#s14"} where var"#s13", Polyhedra.AllRepIterator{var"#s14", var"#s14", LinElemT, LRT, RT} where RT<:Polyhedra.AbstractRepIterator{var"#s14", var"#s14"} where LRT<:Polyhedra.AbstractRepIterator{var"#s14", LinElemT} where LinElemT where var"#s14"} where var"#s14"<:(Polyhedra.HyperPlane{T, AT} where AT<:AbstractArray{T, 1}), Union{AbstractArray{var"#s14", 1}, Polyhedra.AbstractRepIterator{var"#s13", var"#s14"} where var"#s13", Polyhedra.AllRepIterator{var"#s14", var"#s14", LinElemT, LRT, RT} where RT<:Polyhedra.AbstractRepIterator{var"#s14", var"#s14"} where LRT<:Polyhedra.AbstractRepIterator{var"#s14", LinElemT} where LinElemT where var"#s14"} where var"#s14"<:(Polyhedra.HalfSpace{T, AT} where AT<:AbstractArray{T, 1}), Union{AbstractArray{var"#s14", 1}, Polyhedra.AbstractRepIterator{var"#s13", var"#s14"} where var"#s13", Polyhedra.AllRepIterator{var"#s14", var"#s14", LinElemT, LRT, RT} where RT<:Polyhedra.AbstractRepIterator{var"#s14", var"#s14"} where LRT<:Polyhedra.AbstractRepIterator{var"#s14", LinElemT} where LinElemT where var"#s14"} where var"#s14"<:AbstractArray{T, 1}, Union{AbstractArray{var"#s14", 1}, Polyhedra.AbstractRepIterator{var"#s13", var"#s14"} where var"#s13", Polyhedra.AllRepIterator{var"#s14", var"#s14", LinElemT, LRT, RT} where RT<:Polyhedra.AbstractRepIterator{var"#s14", var"#s14"} where LRT<:Polyhedra.AbstractRepIterator{var"#s14", LinElemT} where LinElemT where var"#s14"} where var"#s14"<:(Polyhedra.Line{T, AT} where AT<:AbstractArray{T, 1}), Union{AbstractArray{var"#s14", 1}, Polyhedra.AbstractRepIterator{var"#s13", var"#s14"} where var"#s13", Polyhedra.AllRepIterator{var"#s14", var"#s14", LinElemT, LRT, RT} where RT<:Polyhedra.AbstractRepIterator{var"#s14", var"#s14"} where LRT<:Polyhedra.AbstractRepIterator{var"#s14", LinElemT} where LinElemT where var"#s14"} where var"#s14"<:(Polyhedra.Ray{T, AT} where AT<:AbstractArray{T, 1})} where T}}

Currently `typeintersection(atype, metharg) === metharg`

### CODE REVIEW

File: base/compiler/ssair/inlining.jl [hunk 1]
```diff
@@ -820,9 +820,10 @@ end
 function analyze_method!(match::MethodMatch, argtypes::Vector{Any},
                          flag::UInt8, state::InliningState)
     method = match.method
+    spec_types = match.spec_types
     methsig = method.sig
```
Comment (aviatesk) [inline base/compiler/ssair/inlining.jl:824]:
```suggestion
```
Unrelated, but this variable seems unused anywhere.

File: base/compiler/ssair/inlining.jl [hunk 2]
```diff
@@ -832,6 +833,13 @@ function analyze_method!(match::MethodMatch, argtypes::Vector{Any},
         # call this function
         return nothing
     end
+    if !match.fully_covers
```
Comment (aviatesk) [inline base/compiler/ssair/inlining.jl:836]: Even when `match.fully_covers`, `spec_types` can contain Varargs?
```julia
julia> @eval Core.Compiler let
           foo(a...) = length(a)
           matches = _methods_by_ftype(Tuple{typeof(foo),Int,Vararg{Int}}, -1, get_world_counter())
           matches[1]
       end
       
Core.MethodMatch(Tuple{Core.Compiler.var"#foo#431", Int64, Vararg{Int64}}, svec(), (::Core.Compiler.var"#foo#431")(a...) in Core.Compiler at none:2, true)
```

Comment (vtjnash) [reply base/compiler/ssair/inlining.jl:836]: If it fully covers, then we don't need inline the subtyping computation later (which is what failed)

**Review by aviatesk — APPROVED** [review]
