### PR TITLE
optimizer: keep statements that may throw from being optimized by SROA

### LINKED ISSUE #48067: optimizer: SROA should preserve statement that may throw
```julia
julia> @inline function foo(a::Int, b)
           r = Ref(a)
           try
               setfield!(r, :x, b)
               nothing
           catch err
               return 42
           end
       end
foo (generic function with 1 method)

julia> code_typed(foo, (Int,String))
1-element Vector{Any}:
 CodeInfo(
1 ─      nothing::Nothing
2 ─ %2 = $(Expr(:enter, #4))
3 ─      unreachable
4 ┄      $(Expr(:leave, 1))
5 ─      $(Expr(:pop_exception, :(%2)))::Any
└──      return 42
) => Int64

julia> foo(42, "julia")

[26644] signal (4.1): Illegal instruction: 4
in expression starting at REPL[10]:1
...
```

### PR DESCRIPTION
**Pull request by aviatesk**
SROA should verify a statement won't throw, otherwise it can't be eliminated safely.
Note that this commit skips the nothrow-ness verification on `getfield` statement. This is acceptable because currently we are unable to prove it in the presence of potentially undefined fields. This is okay because our SROA pass will eliminate such a `getfield` statement only if it determines that the forwarded value safely defines the potentially undefined field.

fixes https://github.com/JuliaLang/julia/issues/48067.

### CODE REVIEW

File: base/compiler/ssair/passes.jl [hunk 1]
```diff
@@ -953,14 +951,21 @@ function sroa_pass!(ir::IRCode, inlining::Union{Nothing,InliningState}=nothing)
...
+            val = stmt.args[3]
+        else
+            # Analyze `getfield` / `isdefined` / `setfield!` call:
+
+            # Verify this statement won't throw, otherwise it can't be eliminated safely.
+            # XXX We should verify nothrow-ness of `getfield` statement here, but currently
+            # we are unable to prove it in the presence of potentially undefined fields.
+            # So we skip this verification for now since it would be proven to be nothrow
+            # if SROA on it is successful.
+            if !is_getfield && (compact[SSAValue(idx)][:flag] & IR_FLAG_NOTHROW) == 0
```
Comment (Keno) [inline base/compiler/ssair/passes.jl:964]: I think we should probably still do the processing here so we can lift fields out of the sroa, and just not do the stmt removal at the end.

Comment (Keno) [reply base/compiler/ssair/passes.jl:964]: In particular, it's quite possible that LLVM will be able to prove nothrow even if we can't, but it might not be able to do the SROA itself.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

File: base/compiler/ssair/passes.jl (hunk 1 above)
Comment (aviatesk) [reply base/compiler/ssair/passes.jl]: Okay, I moved the check into `sroa_mutables!`.

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48068#issuecomment-1369315585) failed.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Review by Keno — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48068#issuecomment-1370400880) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/ce6fbae_vs_52af407/report.md).

**Comment by aviatesk** [comment]
The test failures on Windows seem not to relate to this change. Going to merge.
