### PR TITLE
RFC: Delay throwing when CHOLMOD factorizations fail

### LINKED ISSUE #437: Sparse solves with col-permuted matrix
The minimal example:
```
B = speye(3)
B[:,[3,2,1]] \ [1.0; 1.0; 1.0]
```

gives
```
ERROR: ArgumentError: matrix has one or more zero pivots
 in #ldltfact!#10(::Float64, ::Function, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1350
 in (::Base.LinAlg.#kw##ldltfact!)(::Array{Any,1}, ::Base.LinAlg.#ldltfact!, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./<missing>:0
 in #ldltfact#12(::Float64, ::Array{Int64,1}, ::Function, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1386
 in #ldltfact#13(::Array{Any,1}, ::Function, ::Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}) at ./sparse/cholmod.jl:1426
 in \(::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}) at ./sparse/linalg.jl:871
```

The expected behavior is to get the solution vector `[1.0; 1.0; 1.0]`.

### LINKED ISSUE #22335: Sparse solves with col-permuted matrix
The minimal example:
```
B = speye(3)
B[:,[3,2,1]] \ [1.0; 1.0; 1.0]
```

gives
```
ERROR: ArgumentError: matrix has one or more zero pivots
 in #ldltfact!#10(::Float64, ::Function, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1350
 in (::Base.LinAlg.#kw##ldltfact!)(::Array{Any,1}, ::Base.LinAlg.#ldltfact!, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./<missing>:0
 in #ldltfact#12(::Float64, ::Array{Int64,1}, ::Function, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1386
 in #ldltfact#13(::Array{Any,1}, ::Function, ::Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}) at ./sparse/cholmod.jl:1426
 in \(::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}) at ./sparse/linalg.jl:871
```

The expected behavior is to get the solution vector `[1.0; 1.0; 1.0]`.

### PR DESCRIPTION
**Pull request by andreasnoack**
Introduce `issuccess` function to test if a `Factorization` succeeded.

Fixes JuliaLang/LinearAlgebra.jl#437

### CODE REVIEW

File: base/linalg/cholesky.jl [hunk 1]
```diff
@@ -462,7 +467,7 @@ function A_ldiv_B!(C::CholeskyPivoted, B::StridedMatrix)
 end
 
 function det(C::Cholesky)
-    C.info == 0 || throw(PosDefException(C.info))
+    issuccess(C) || throw(PosDefException(C.info))
```
Comment (fredrikekre) [inline base/linalg/cholesky.jl]: perhaps clearer to check `isposdef` since we throw an `PosDefException` here? (eg. #22245 )? same below

File: base/linalg/factorization.jl [hunk 2]
```diff
@@ -16,6 +16,24 @@ macro assertnonsingular(A, info)
...
+Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
+[1.0 0.0; 0.0 1.0]
+successful: true
+
+julia> cholfact([1 0; 0 -1])
+Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
+[1.0 0.0; 0.0 -1.0]
+successful: false
+```
+"""
```
Comment (tkelman) [inline base/linalg/factorization.jl]: I think this needs to be attached to something

File: base/sparse/cholmod.jl [hunk 3]
```diff
@@ -1750,17 +1752,22 @@ end
...
+    return s.minor == size(F, 1)
+end
+
+function isposdef(F::Factor)
+    if issuccess(F)
+        s = unsafe_load(F.p)
+        if s.is_ll == 1
+            return true
+        else
+            return :maybe
```
Comment (tkelman) [inline base/sparse/cholmod.jl]: wouldn't it be better for this to be type stable if possible?

Comment (andreasnoack) [inline base/sparse/cholmod.jl]: Yes. It is WIP. I need to figure out the best way to test if an LDLt `Factor` is PD.

File: base/linalg/factorization.jl [hunk 4]
```diff
@@ -16,6 +16,26 @@ macro assertnonsingular(A, info)
    :($(esc(info)) == 0 ? $(esc(A)) : throw(SingularException($(esc(info)))))
 end
 
+"""
+
```
Comment (tkelman) [inline base/linalg/factorization.jl]: no blank line at the start of docstrings

File: base/sparse/cholmod.jl (hunk 3 above)
Comment (tkelman) [inline base/sparse/cholmod.jl]: ahk. that branch is covered in tests?

Comment (andreasnoack) [inline base/sparse/cholmod.jl]: I'm pretty sure it is but a lot of stuff was still broken so there was many test failures. I'll take a look at the coverage when tests pass.

**Comment by tkelman** [comment]
I like the approach. I wonder if it's too much of a pun to dispatch this on the existing `success` function.

**Comment by andreasnoack** [comment]
I'm fine with overloading `success`. I don't see how it could cause confusion. The only minor issue is the missing `is` that most other of our testing functions have and that `success(Cmd)` is mainly about side effects whereas `success(Factorization)` is just checking a state.

File: base/sparse/cholmod.jl [hunk 5]
```diff
@@ -1750,17 +1760,27 @@ end
 
 det(L::Factor) = exp(logdet(L))
 
-function isposdef(A::SparseMatrixCSC{<:VTypes,SuiteSparse_long})
```
Comment (tkelman) [inline base/sparse/cholmod.jl]: does the fallback work for this now?

Comment (andreasnoack) [inline base/sparse/cholmod.jl]: Yes and I believe that https://github.com/JuliaLang/julia/pull/22345/files#diff-f75d450eb1491e3f787ed1ae6b40424fR378 should be exercising that.

File: base/sparse/cholmod.jl (hunk 3 above)
Comment (andreasnoack) [inline base/sparse/cholmod.jl]: I've updated the tests such that all branches are now covered.

File: base/linalg/bunchkaufman.jl [hunk 6]
```diff
@@ -88,8 +88,15 @@ size(B::BunchKaufman, d::Integer) = size(B.LD, d)
 issymmetric(B::BunchKaufman) = B.symmetric
 ishermitian(B::BunchKaufman) = !B.symmetric
 
+issuccess(B::BunchKaufman) = B.info == 0
+
+function Base.show(io::IO, F::BunchKaufman)
+    println(io, summary(F))
```
Comment (tkelman) [inline base/linalg/bunchkaufman.jl]: this should show the factor as done for lu and cholesky

Comment (andreasnoack) [inline base/linalg/bunchkaufman.jl]: I don't think that is useful for sparse factorizations.

Comment (andreasnoack) [inline base/linalg/bunchkaufman.jl]: Oops. Too fast. The problem here is that constructing the factor is a mess and not that useful.

Comment (tkelman) [inline base/linalg/bunchkaufman.jl]: it's pedagogically useful - isn't there a helper function in lapack for this?
