### PR TITLE
zero-index get/setindex(::ReinterpretArray) require a length of 1

### LINKED ISSUE #58232: `getindex` too relaxed on reinterpreted array
```julia
julia> a=[1,2,3]
3-element Vector{Int64}:
 1
 2
 3

julia> a[]
ERROR: BoundsError: attempt to access 3-element Vector{Int64} at index []
Stacktrace:
 [1] throw_boundserror(A::Vector{Int64}, I::Tuple{})
   @ Base ./essentials.jl:14
 [2] checkbounds
   @ ./abstractarray.jl:699 [inlined]
 [3] _getindex
   @ ./abstractarray.jl:1340 [inlined]
 [4] getindex(::Vector{Int64})
   @ Base ./abstractarray.jl:1312
 [5] top-level scope
   @ REPL[24]:1

julia> reinterpret(UInt8, a)[]
0x01
```

the last line should error as well

### PR DESCRIPTION
**Pull request by adienes**
fix https://github.com/JuliaLang/julia/issues/58232

o3 helped me understand the existing implementations but code is mine

### CODE REVIEW

**Comment by nsajko** [comment]
This method seems like it may need adjustment, too:

https://github.com/JuliaLang/julia/blob/3ae69f688db8e5dc30bcc1256731c4732dfcd24e/base/reinterpretarray.jl#L379-L385

**Comment by adienes** [comment]
yup. also this currently breaks 0-dimensional reinterpetarrays

File: test/reinterpretarray.jl [hunk 1]
```diff
@@ -524,7 +524,6 @@ end
     @test_throws ArgumentError reinterpret(Missing, fill(1f0, ()))
     @test_throws ArgumentError reinterpret(reshape, Float64, fill(nothing, ()))
     @test_throws ArgumentError reinterpret(reshape, Nothing, fill(17, ()))
-    @test_throws MethodError z[] = nothing
```
Comment (adienes) [inline test/reinterpretarray.jl]: I'm not sure if this was a bad test or not

this used to throw

```
julia> z[] = nothing
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type Tuple{}
```

and now is a no-op
```
julia> z[] = nothing
```

but, these are not `ConvertArrays` they are `ReinterpretArrays`, and we can in fact call `reinterpret(Tuple{}, nothing)` without error

Comment (mbauman) [reply test/reinterpretarray.jl]: The status quo behaviors are very strange.  0-dimensional setindex! reinterprets, but 1-d converts?

```Julia
julia> z = reinterpret(UInt, fill(1.0, 1))
1-element reinterpret(UInt64, ::Vector{Float64}):
 0x3ff0000000000000

julia> z[1] = Int32(1)//Int32(1)
1//1

julia> z
1-element reinterpret(UInt64, ::Vector{Float64}):
 0x0000000000000001

julia> z[1] = 1.5
ERROR: InexactError: UInt64(1.5)
Stacktrace:
 [1] UInt64
   @ ./float.jl:973 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] _setindex_ra!
   @ ./reinterpretarray.jl:583 [inlined]
 [4] setindex!(a::Base.ReinterpretArray{UInt64, 1, Float64, Vector{Float64}, false}, v::Float64, inds::Int64)
   @ Base ./reinterpretarray.jl:548
 [5] top-level scope
   @ REPL[25]:1

julia> z[] = 1.5
ERROR: InexactError: UInt64(1.5)
Stacktrace:
 [1] UInt64
   @ ./float.jl:973 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] _setindex_ra!
   @ ./reinterpretarray.jl:583 [inlined]
 [4] setindex!
   @ ./reinterpretarray.jl:548 [inlined]
 [5] setindex!(a::Base.ReinterpretArray{UInt64, 1, Float64, Vector{Float64}, false}, v::Float64)
   @ Base ./reinterpretarray.jl:543
 [6] top-level scope
   @ REPL[26]:1

julia> z = reinterpret(UInt, fill(1.0, ()))
0-dimensional reinterpret(UInt64, ::Array{Float64, 0}):
0x3ff0000000000000

julia> z[1] = Int32(1)//Int32(1)
1//1

julia> z
0-dimensional reinterpret(UInt64, ::Array{Float64, 0}):
0x0000000000000001

julia> z[] = Int32(1)//Int32(1)
1//1

julia> z
0-dimensional reinterpret(UInt64, ::Array{Float64, 0}):
0x0000000100000001

julia> z[1] = 1.5
ERROR: InexactError: UInt64(1.5)
Stacktrace:
 [1] UInt64
   @ ./float.jl:973 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] _setindex_ra!
   @ ./reinterpretarray.jl:583 [inlined]
 [4] setindex!(a::Base.ReinterpretArray{UInt64, 0, Float64, Array{Float64, 0}, false}, v::Float64, i::Int64)
   @ Base ./reinterpretarray.jl:555
 [5] top-level scope
   @ REPL[32]:1

julia> z[] = 1.5
1.5

julia> z
0-dimensional reinterpret(UInt64, ::Array{Float64, 0}):
0x3ff8000000000000
```

Comment (adienes) [reply test/reinterpretarray.jl]: ~indeed weird. I think this PR technically makes the state of affairs a bit more consistent in this respect (always reinterpret at 0 dims) but maybe it's worth broadening the scope of this PR to clean it up ?~


I think I was misinterpreting something --- added the `convert(T, v)` call to restore the old behavior

**Comment by adienes** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/58814#issuecomment-3009082031) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3d00e1f_vs_b06d260/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

3 packages crashed on the previous version too.

## ✖ Packages that failed

**11 packages failed only on the current version.**

 - Package fails to precompile: 1 packages
 - Package has test failures: 3 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 6 packages

1554 packages failed on the previous version too.

## ✔ Packages that passed tests

**20 packages passed tests only on the current version.**

 - Other: 20 packages

5163 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**6 packages successfully loaded only on the current version.**

 - Other: 6 packages

3025 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

902 packages were skipped on the previous version too.



</details>

**Comment by adienes** [comment]
@nanosoldier `runtests(["LLLplus", "Skipper", "MLJTSVDInterface", "XDiag", "Permanents", "DataInterpolations", "Miter", "OnlinePortfolioSelection", "Isoplot", "TNRKit", "NetworkJumpProcesses"])`

File: base/reinterpretarray.jl [hunk 2]
```diff
@@ -376,12 +376,10 @@ elsize(::Type{<:ReinterpretArray{T}}) where {T} = sizeof(T)
...
-@propagate_inbounds function getindex(a::NonReshapedReinterpretArray{T,0,S}) where {T,S}
-    if isprimitivetype(T) && isprimitivetype(S)
-        reinterpret(T, a.parent[])
-    else
-        a[firstindex(a)]
-    end
+@propagate_inbounds function getindex(a::ReinterpretArray{T,0,S,IsReshaped}) where {T,S,IsReshaped}
+    check_readable(a)
+    check_ptr_indexable(a) && return _getindex_ptr(a)
+    return reinterpret(T, a.parent[])
```
Comment (N5N3) [inline base/reinterpretarray.jl]: L382 is valid only for `NonReshapedReinterpretArray`, it would break `reinterpret(reshape, Tuple{Int8,Int}, view([1,1], [1,2]))`.

File: base/reinterpretarray.jl [hunk 3]
```diff
@@ -391,8 +389,6 @@ check_ptr_indexable(a::Array, sz) = sizeof(eltype(a)) !== sz
 check_ptr_indexable(a::Memory, sz) = true
 check_ptr_indexable(a::AbstractArray, sz) = false
 
-@propagate_inbounds getindex(a::ReinterpretArray) = a[firstindex(a)]
```
Comment (N5N3) [inline base/reinterpretarray.jl:394]: It seems simpler to replace L394 with
```julia
@propagate_inbounds getindex(a::ReshapedReinterpretArray{T,0}) where {T} = a[firstindex(a)]
```
?
`firstindex` is fine here, as we know checkbounds would pass.

Comment (adienes) [reply base/reinterpretarray.jl:394]: thank you for the review!

~would `only(a)` be acceptable here rather than `a[firstindex(a)]` ? I know it is not necessary because a 0 dimensional array has only a single index, but in my opinion that would make it extra-clear that this is a special case~

answer: it is not.

I suppose the `AbstractArray` fallback ends up calling `_to_linear_index(A::AbstractArray) = first(LinearIndices(A))` anyway, so it's the same just obfuscated

Comment (N5N3) [reply base/reinterpretarray.jl:394]: I agree `only(a)` would be more clear, but we don't have that for `setindex!` 😂
Perhaps some comment is enough?

Comment (adienes) [reply base/reinterpretarray.jl:394]: I've added the test case from `reinterpret(reshape, Tuple{Int8,Int}, view([1,1], [1,2]))` and applied your suggestion to change (narrow) only the signature of `getindex(::ReinterpretArray)`. I've done the modification for `setindex!(::ReinterpretArray)`, assuming that the problem/suggestion applied to both analogously

File: NEWS.md [hunk 4]
```diff
@@ -17,6 +17,8 @@ is considered a bug fix ([#47102])
 
   - The `hash` algorithm and its values have changed. Most `hash` specializations will remain correct and require no action. Types that reimplement the core hashing logic independently, such as some third-party string packages do, may require a migration to the new algorithm. ([#57509])
 
+* indexless `getindex` and `setindex!` (i.e. `A[]`) on `ReinterpretArray` of nonzero dimensionality now correctly throw a `BoundsError`. ([#58814])
```
Comment (mbauman) [inline NEWS.md]:
```suggestion
* Indexless `getindex` and `setindex!` (i.e. `A[]`) on `ReinterpretArray` now correctly throw a `BoundsError` when there is more than one element. ([#58814])
```

File: test/reinterpretarray.jl [hunk 5]
```diff
@@ -36,6 +37,10 @@ test_many_wrappers(B, (identity, tslow)) do _B
     @test @inferred(size(reinterpret(reshape, Int128, _B))) == (3,)
 end
 
+test_many_wrappers(C) do Cr
+    @test reinterpret(reshape, Tuple{Int8, Int}, Cr) == fill((1,1))
+end
```
Comment (mbauman) [inline test/reinterpretarray.jl:42]:
```suggestion
    @test reinterpret(reshape, Tuple{Int8, Int}, Cr)[] === (Int8(1),1)
    r = reinterpret(reshape, Tuple{Int, Int}, Cr)
    r[] = (2,2)
    @test r[] === (2,2)
    r[1] = (3,3)
    @test r[1,1] === (3,3)
end
```

Do these tests pass?

Comment (adienes) [reply test/reinterpretarray.jl:42]: `@test reinterpret(reshape, Tuple{Int8, Int}, Cr)[] === (Int8(1),1)` does, but the subsequent ones fail with a `BoundsError` upon trying to assign to `r[]` and `r[1]`  --- this behavior (BoundsError) matches master though

Comment (mbauman) [reply test/reinterpretarray.jl:42]: I suppose that's a different bug and a different BoundsError.

File: test/reinterpretarray.jl (hunk 1 above)
Comment (mbauman) [reply test/reinterpretarray.jl]: Wait, does this still happen?  Could you add tests for it?  Or should it be punted to a separate issue/fix?

Comment (adienes) [reply test/reinterpretarray.jl]: yeah, the behavior of all these are unchanged. I'm happy to broaden the scope of the PR but my guess is it's a separate problem

Comment (mbauman) [reply test/reinterpretarray.jl]: Seems distinct enough to tackle separately... especially since this PR just _adds errors_ whereas that fixing that one would _change values_.

Comment (adienes) [reply test/reinterpretarray.jl]: I think a fix would be
```
@propagate_inbounds function setindex!(a::ReinterpretArray{T,N,S}, v, i::Int) where {T,N,S}
    check_writable(a)
    check_ptr_indexable(a) && return _setindex_ptr!(a, v, i)
    inds = _to_subscript_indices(a, i)
    if isa(IndexStyle(a), IndexLinear) || (inds === ())
        return _setindex_ra!(a, v, i, ())
    end
    _setindex_ra!(a, v, inds[1], tail(inds))
end
```

note the added `|| (inds === ())`

maybe I can fold it into https://github.com/JuliaLang/julia/pull/58293

Comment (mbauman) [reply test/reinterpretarray.jl]: I think it's distinct.  I'll open a PR for it, I have a fix.

**Review by mbauman — APPROVED** [review]

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/58814#issuecomment-3016655226) has completed - no new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3d00e1f_vs_b06d260/report.html) is available.

<details><summary>Report summary</summary>

## ✔ Packages that passed tests

10 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**1 packages successfully loaded only on the current version.**

 - Other: 1 packages




</details>
