### PR TITLE
correct posixly shell quoting

### LINKED ISSUE #10120: REPL shell mode calls the shell with incorrectly escaped arguments
```
shell> ./julia -E "println(ARGS)"
bash: syntax error near unexpected token `('

shell> ./julia -E \"println(ARGS)\"
"println(ARGS)"

shell> ./julia -E println\(ARGS\)
bash: syntax error near unexpected token `('
```

### PR DESCRIPTION
**Pull request by vtjnash**
Ensures that `addprocs` arguments will be passed through a posix shell correctly, (including those with shell-metacharacters such as being added in #21849 for `-C`, but also weird cases like `--` and files named `\r`).

fix #10120

### CODE REVIEW

**Comment by yuyichao** [comment]
You do make me wonder if I should have chosen another character instead.
OTOH though, `,` is what llvm use for features so I'd like to keep that, `/` is a bit strange since it usually mean nesting (path) which this isn't, `:` looks similar to `;` but it feel like a lower evel of separation than `,`........................

**Comment by vtjnash** [comment]
> You do make me wonder if I should have chosen another character instead.

This was not the motivation for the PR, I just thought it would be interesting to note current known cases that this fixes (passing other exeflags is usually pretty rare, as is having shell metacharacters in the path).

**Comment by yuyichao** [comment]
> This was not the motivation for the PR

Yes, I know. I just wonder if this can cause other random script to error. Though this is just a compile flag so you normally won't use it in a script or `addproc`.

File: test/repl.jl [hunk 1]
```diff
@@ -103,16 +103,16 @@ fake_repl() do stdin_write, stdout_read, repl
...
+    #if !Sys.iswindows()
+    #    write(stdin_write, ";")
+    #    readuntil(stdout_read, "shell> ")
+    #    write(stdin_write, "echo hello >/dev/null\n")
+    #    let s = readuntil(stdout_read, "\n")
+    #        @test contains(s, "shell> ") # make sure we echoed the prompt
+    #        @test contains(s, "echo hello >/dev/null") # make sure we echoed the input
+    #    end
+    #    @test readuntil(stdout_read, "\n") == "\e[0m\n"
+    #end
```
Comment (vtjnash) [inline test/repl.jl]: Note: these disabled tests are left as motivation for someone to finish the implementation of https://github.com/JuliaLang/julia/issues/20401 🙂

Comment (JeffBezanson) [reply test/repl.jl]: Do these tests not pass anymore?

Comment (vtjnash) [reply test/repl.jl]: With the current deprecation, they're partially broken. Hence the motivation for someone to remove the deprecation and finish implementing the #20401

**Comment by StefanKarpinski** [comment]
Would it be possible to just make `shell_escape` POSIX-compatible by default? If so, I think we should just do that since it seems good to just default to shell escaping in a way that works in POSIX shells.

**Comment by vtjnash** [comment]
> Would it be possible to just make shell_escape POSIX-compatible by default? 

Perhaps, since I think currently shell_parse will get the same result when called on the result of shell_escape_posixly (that's partially of the idea of the function - to be an overly conservatively approximation of all shells). I don't think there's any particular reason to remove shell_escape however, since it's useful for its intended purpose (as a pretty-printer for Cmd objects), and I'm not sure what  #20401 will want for changes to the parser.

**Comment by vtjnash** [comment]
> since I think currently shell_parse will get the same result

Actually, this isn't true, but upon further review, I think it may actually be due to other bugs in shell_escape, rather than being due to divergence between shell_parse and posix sh:
```julia
julia> Base.shell_escape(` '$a"' `)
"'\$a\"'"

julia> Base.shell_escape(` '\$a\"' `)
"'\\\$a\\\"'"
```
