### PR TITLE
Fix codegen error path for imported non-owned bindings

### LINKED ISSUE #45350: Codegen for assigning to imported bindings segfaults
```
julia> module Foo
       global x::Int = 2
       end

julia> import .Foo: x

julia> foo() = (global x = 3)
foo (generic function with 1 method)

julia> foo()

signal (11): Segmentation fault
in expression starting at REPL[9]:1
emit_varinfo_assign at /home/keno/julia/src/codegen.cpp:4552
emit_assignment at /home/keno/julia/src/codegen.cpp:4631
```

As seen on PkgEval in [BEAST](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/dc8a715_vs_6d9ae9d/BEAST.primary.log) and [OpenDSSDirect](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/dc8a715_vs_6d9ae9d/OpenDSSDirect.primary.log)

### PR DESCRIPTION
**Pull request by Keno**
The code assumed that a null return from `global_binding_pointer`
was impossible. However, it happens in the error path, causing
a bad memory reference later when the lhs is treated as a slot.

Fixes #45350

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -4607,27 +4607,27 @@ static void emit_assignment(jl_codectx_t &ctx, jl_value_t *l, jl_value_t *r, ssi
...
+    }
+
     jl_binding_t *bnd = NULL;
     Value *bp = NULL;
     if (jl_is_symbol(l))
         bp = global_binding_pointer(ctx, ctx.module, (jl_sym_t*)l, &bnd, true); // now bp != NULL or bnd != NULL
-    else if (jl_is_globalref(l))
+    else {
+        assert(jl_is_globalref(l));
         bp = global_binding_pointer(ctx, jl_globalref_mod(l), jl_globalref_name(l), &bnd, true); // now bp != NULL or bnd != NULL
```
Comment (vtjnash) [inline src/codegen.cpp:4623]: this this comment wrong then?

Comment (Keno) [reply src/codegen.cpp:4623]: Yes
