### PR TITLE
Fix axpy! and add tests.

### LINKED ISSUE #315: Bug in daxpy!
Reported by Tomas (see [https://groups.google.com/forum/#!topic/julia-users/BxWs1Vj_6Ng](url))

> Hello all,
> I was polishing my call and I have found the following definition of daxpy! I was not aware of
> 
> ``` julia
> function axpy!{Ti<:Integer,Tj<:Integer}(α, x::AbstractArray, rx::AbstractArray{Ti}, y::AbstractArray, ry::AbstractArray{Tj})
>     if length(x) != length(y)
>         throw(DimensionMismatch("x has length $(length(x)), but y has length $(length(y))"))
>     elseif minimum(rx) < 1 || maximum(rx) > length(x)
>         throw(BoundsError(x, rx))
>     elseif minimum(ry) < 1 || maximum(ry) > length(y)
>         throw(BoundsError(y, ry))
>     elseif length(rx) != length(ry)
>         throw(ArgumentError("rx has length $(length(rx)), but ry has length $(length(ry))"))
>     end
>     for i = 1:length(rx)
>         @inbounds y[ry[i]] += x[rx[i]]*α
>     end
>     y
> end
> 
> ```
> 
> Is the first check
>  length(x) != length(y)
> really an intended behavior? 
> 
> The multiplication goes over indexes rx and ry, should not be the check  length(rx) != length(ry) ?
> 
> Thanks for the clarification.
> Tomas

### LINKED ISSUE #15393: Bug in daxpy!
Reported by Tomas (see [https://groups.google.com/forum/#!topic/julia-users/BxWs1Vj_6Ng](url))

> 
> Hello all,
> I was polishing my call and I have found the following definition of daxpy! I was not aware of
> 
> 
> ```julia
> function axpy!{Ti<:Integer,Tj<:Integer}(α, x::AbstractArray, rx::AbstractArray{Ti}, y::AbstractArray, ry::AbstractArray{Tj})
>     if length(x) != length(y)
>         throw(DimensionMismatch("x has length $(length(x)), but y has length $(length(y))"))
>     elseif minimum(rx) < 1 || maximum(rx) > length(x)
>         throw(BoundsError(x, rx))
>     elseif minimum(ry) < 1 || maximum(ry) > length(y)
>         throw(BoundsError(y, ry))
>     elseif length(rx) != length(ry)
>         throw(ArgumentError("rx has length $(length(rx)), but ry has length $(length(ry))"))
>     end
>     for i = 1:length(rx)
>         @inbounds y[ry[i]] += x[rx[i]]*α
>     end
>     y
> end
> 
> ```
> Is the first check
>  length(x) != length(y)
> really an intended behavior? 
> 
> The multiplication goes over indexes rx and ry, should not be the check  length(rx) != length(ry) ?
> 
> Thanks for the clarification.
> Tomas
>

### PR DESCRIPTION
**Pull request by musm**
Fixed bug in LinAlg.axpy! and added test. Fixes JuliaLang/LinearAlgebra.jl#315. 

Is it convention for tests to explicit say `Base.LinAlg.axpy!`  vs `LinAlg.axpy!`  ?

### CODE REVIEW

**Comment by musmo** [comment]
@tkelman fixed sorry about that. I squashed the commits and then I had to force the pull in order to resolve `hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.`

**Comment by musmo** [comment]
Also some of the tests in the file kinda don't make sense especially for axpy! where  `*` and `+` aren't defined for Char's even though the tests are using them.

File: test/linalg/generic.jl [hunk 1]
```diff
@@ -200,6 +199,16 @@ let
     @test LinAlg.axpy!(α, x, deepcopy(y)) != Matrix{Int}[α] .* x
 end
 
+# test that LinAlg.axpy! works for x and y of different dimensions
+let
+    α = 5
+    x = ones(Int, 2, 3)
```
Comment (stevengj) [inline test/linalg/generic.jl]: probably use `x = 2:7` or similar, so that the test checks that the right elements of `x` are being added to `y`.

Comment (musmo) [inline test/linalg/generic.jl]: Changes fixed.

**Comment by stevengj** [comment]
LGTM.
