### PR TITLE
Markdown: inside a list, fix code blocks containing multiple consecutive empty lines

### LINKED ISSUE #59967: [Markdown] indented code blocks with more than one blank line don't render correct
*This is a bug report first written in <https://github.com/JuliaDocs/Documenter.jl/issues/2783>. But there it was stated, that it is an upstream issue. Hence, here it is again.*

---

The title says it all. Thus, the code

````markdown

- code block with multiple blank lines without indention works fine

```julia
domaths(x::Number) = x + 5


domath(x::Int) = x + 10
```

- code block with maximum one blank line with indention works fine

  ```julia
  domaths(x::Number) = x + 5

  domath(x::Int) = x + 10
  ```

- code block with more than one blank line with indention doesn't work

  ```julia
  domaths(x::Number) = x + 5


  domath(x::Int) = x + 10
  ```
````

results in

image showing the result of above code

### PR DESCRIPTION
**Pull request by phantomsoldierking**
fixes #59967

below is the output of example mentioned in the issue,
image

not sure if its the right way to do it, but all the markdown tests passed, please suggest if any changes

### CODE REVIEW

**Comment by fingolfin** [comment]
Thank you for working on this!

Could you perhaps add a test that verifies the issue? There are various examples in `stdlib/Markdown/test/runtests.jl` that could be adapted: basically you provide your problematic input as a string and let Markdown parse it, then verify the structure of the resulting Markdown object is right (or you ask it to convert to HTML, and verify the resulting HTML is "right", etc.)

File: stdlib/Markdown/src/Common/block.jl [hunk 1]
```diff
@@ -292,9 +292,32 @@ function list(stream::IO, block::MD)
...
             if startswith(stream, "\n")
                 if newline
-                    # Double newline ends the current list.
-                    pushitem!(list, buffer)
-                    break
+                    # We have a double newline. Peek ahead to see if the next non-blank
+                    # line is indented. If so, continue the list item.
+                    saved_pos = position(stream)
+
+                    #Skip any additional blank lines and check indntation
```
Comment (fingolfin) [inline stdlib/Markdown/src/Common/block.jl]: Please put a space after `#` to follow the style of the surrounding code. Also: typo :-)
```suggestion
                    # Skip any additional blank lines and check indentation
```

File: stdlib/Markdown/src/Common/block.jl [hunk 2]
```diff
@@ -292,9 +292,32 @@ function list(stream::IO, block::MD)
...
+                            still_indented = true
+                            break
+                        else
+                            break
+                        end
+                    end
+                    #Reset stream to position after the double newline we detected
+                    seek(stream, saved_pos)
+                    if still_indented
+                        #Multiple blank lines within indented content - allow it
```
Comment (fingolfin) [inline stdlib/Markdown/src/Common/block.jl]:
```suggestion
                        # Multiple blank lines within indented content - allow it
```

File: stdlib/Markdown/test/runtests.jl [hunk 3]
```diff
@@ -1354,6 +1354,36 @@ end
...
+    @test occursin("<li>", html)
+
+    # Content must not be dropped or split
+    @test occursin("item", html)
+    @test occursin("domaths", html)
+    @test occursin("domath", html)
+
+    # And importantly: no premature list termination
+    # Apply occursin elementwise using broadcasting
+    @test count(occursin.("<li>", split(html, '\n'))) == 1
```
Comment (fingolfin) [inline stdlib/Markdown/test/runtests.jl]: But this test also passes with the *current* version of the code. You are not actually testing that your change does something!

I would recommend to just test the full HTML output as is done e.g. in line 1122 and in other places. That then also will catch other (intended or unintended) changes affecting this output.

Comment (fingolfin) [reply stdlib/Markdown/test/runtests.jl]: Also, in your example, I don't think the code is indented far enough to be considered code: you need 4 spaces *plus* the current indent of the list, so here 6 spaces.

Indeed, your Markdown snippet, rendered by GitHub:

- item

    domaths(x::Number) = x + 5


    domath(x::Int) = x + 10


And here with the 6 space indentation

- item

      domaths(x::Number) = x + 5


      domath(x::Int) = x + 10

Comment (phantomsoldierking) [reply stdlib/Markdown/test/runtests.jl]: sorry for the wrong test, it does not check for code element in html, and also the issue was not indentation in markdown but indented code snippets in list render was inconsistent.
I have changed it to include the example mentioned in the issue itself

File: stdlib/Markdown/test/runtests.jl [hunk 4]
```diff
@@ -1354,6 +1354,32 @@ end
     @test insert_hlines(nothing) === nothing
 end
 
+@testset "#59967: indented code blocks with more than one blank line" begin
+    # Test the broken case in issue: indented code block with multiple blank lines
+    md = Markdown.parse("""
+- code block with more than one blank line with indention does not work
```
Comment (fingolfin) [inline stdlib/Markdown/test/runtests.jl]: While it doesn't matter for the effectiveness of the test, let's still avoid a potentially confusing message: multiple blank lines now *do* work. Also, it is "indentation" not "indention".
```suggestion
- code block inside a list with more than one blank line with indentation works
```

File: stdlib/Markdown/test/runtests.jl [hunk 5]
```diff
@@ -1354,6 +1354,32 @@ end
...
+
+
+  domath(x::Int) = x + 10
+  ```
+""")
+
+    expected =
+        """
+        <ul>
+        <li><p>code block with more than one blank line with indention does not work</p>
```
Comment (fingolfin) [inline stdlib/Markdown/test/runtests.jl]:
```suggestion
        <li><p> code block inside a list with more than one blank line with indentation works</p>
```

File: stdlib/Markdown/test/runtests.jl [hunk 6]
```diff
@@ -1354,6 +1354,32 @@ end
...
+    # Test the broken case in issue: indented code block with multiple blank lines
+    md = Markdown.parse("""
+- code block with more than one blank line with indention does not work
+  ```julia
+  domaths(x::Number) = x + 5
+
+
+  domath(x::Int) = x + 10
+  ```
+""")
```
Comment (fingolfin) [inline stdlib/Markdown/test/runtests.jl]: Your test currently only tests the "positive" case: that the list is not ended prematurely. But I think we should also verify that it still ends when it should end. How about adding something like this:
```suggestion
- another entry, now testing code blocks without fences

      # this is a code block
      x = 1 + 1
      
      
      # Two empty lines don't interrupt the code
      y = x * 3

- a final list entry

And now to something completely different!
""")
```
which GitHub markdown renders as a list with three entries, followed by a paragraph:


- code block inside a list with more than one blank line with indentation work
  ```julia
  domaths(x::Number) = x + 5


  domath(x::Int) = x + 10
  ```
- another entry, now testing code blocks without fences

      # this is a code block
      x = 1 + 1
      
      
      # Two empty lines don't interrupt the code
      y = x * 3

- a final list entry

And now to something completely different!

File: stdlib/Markdown/src/Common/block.jl (hunk 2 above)
Comment (fingolfin) [reply stdlib/Markdown/src/Common/block.jl]: Not sure why this comment was merged as resolved when it isn't? Please also check your other comments for these missing spaces.

**Review by fingolfin — COMMENTED** [review]
Thanks, looking much better. Some minor remarks are left, then this should be ready

File: stdlib/Markdown/test/runtests.jl (hunk 6 above)
Comment (phantomsoldierking) [reply stdlib/Markdown/test/runtests.jl]: thank you for the suggestions, I have made the changes please check

**Review by fingolfin — APPROVED** [review]
Looks good to me, thanks!

**Comment by fingolfin** [comment]
@phantomsoldierking thanks for this! I don't know what your motivation for fixing this was, but if you are interested in working on some more Markdown related things to tweak, check out issues #30198, #22076, #16004.

In particular I think while this patch fixed that particular instance, it probably was too narrow, and fixing the other related issues might even result in *simpler* code (basically, stopping after multiple empty lines seems to just not be the right thing to do)

**Comment by phantomsoldierking** [comment]
Thank you for the suggestion, will work on those issues and try. Also Thanks a lot for helping me in this pr(I am a student trying to contribute to open source)
