### PR TITLE
fixes #8416 (and duplicated issue #9664)

### LINKED ISSUE #8416: Different behavior of .* in sparse and non-sparse matrices and problem in sparse lufact()
I'm fiddling with sparse matrices and have found a few quirks :-)  

What I pretend to do is use LU factorization in sparse matrices (for now in real matrices, but I hope to get it done also in sparse complex matrices) 

First, in the manual, in the Linear Algebra section (http://docs.julialang.org/en/release-0.3/stdlib/linalg/) there is the relation between the L and U factors (in the case of F=lufact(A) operation they are named/extracted as F[:L] and F[:U] )  and a line and column permutation of the factorized sparse matrix A that reads as 
<code>
F[:L] * F[:U] == Rs .* A[F[:p], F[:q]]
</code>
It seems to me (according to the explanation in that section) that it should read as 
<code>
F[:L] * F[:U] == F[:Rs]  .* A[F[:p], F[:q]]
</code>
because Rs doesn't exist per se (it has to be extracted from the object F, and so is  F[:Rs]).

Aside that typo, additionally the RHS of that expression when evaluated gives an error due to a mismatch in dimensions. Indeed there is not a perfect equivalence/behavior of the .* operator (this doesn't happen with the .+ operator, for example) in real and in complex matrices, as the session below clearly shows. I end that session with an example of the failure, by applying lufact() and exemplifying the error. 

I checked the code around "sparse/sparsematrix.jl:531" where the error is triggered and there is a check of conformant dimensions for matrix dot product .* (and of other operators) 
<pre>
	   .............
           if size(A,1) != size(B,1) || size(A,2) != size(B,2)
                throw(DimensionMismatch(""))			# line 531 of the source code
            end
	   ...............
</pre>
(where A and B are the operands) which means that the .* operator  only accepts operands with the same dimensions. I think that it is what triggers the error.
	   
But then this configures a different behavior for .* in sparse and non sparse matrix representations. 
	
Below is a session with julia 0.3.0 running in windows 7 in AMD 8-core Piledriver processor where the above cases are visible, with added comments. I experimented in julia 0.2.1 in Linux-Ubuntu (over Virtualbox) and the behavior of .* is the same as in windows 7; however, in 0.2.1 lufact() is not implemented for sparses, so I could not check it.

<pre>
# H and v are a matrix and a vector, Hs and vs the corresponding sparse objects.

julia> H=[1 0; 2 -1.0]
2x2 Array{Float64,2}:
 1.0   0.0
 2.0  -1.0

julia> v=[2,3.0]
2-element Array{Float64,1}:
 2.0
 3.0

julia> Hs=sparse(H)
2x2 sparse matrix with 3 Float64 entries:
        [1, 1]  =  1.0
        [2, 1]  =  2.0
        [2, 2]  =  -1.0

julia> vs=sparse(v)
2x1 sparse matrix with 2 Float64 entries:
        [1, 1]  =  2.0
        [2, 1]  =  3.0

julia> v .* H
2x2 Array{Float64,2}:
 2.0   0.0
 6.0  -3.0

julia> v .* Hs
ERROR: DimensionMismatch("")
 in .* at sparse/sparsematrix.jl:531

julia> vs .* H
ERROR: DimensionMismatch("")
 in .* at sparse/sparsematrix.jl:531

julia> vs .* Hs
ERROR: DimensionMismatch("")
 in .* at sparse/sparsematrix.jl:531

# product * is OK

julia> H * Hs
2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

julia> Hs * H
2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

# does difference in sizes of v and vs explain something?

julia> size(H)
(2,2)

julia> size(Hs)
(2,2)

julia> size(v)
(2,)

julia> size(vs)
(2,1)

## the .+ operator is OK with mismatch in operand dimensions (sparse or not)

julia> v .+ H
2x2 Array{Float64,2}:
 3.0  2.0
 5.0  2.0

julia> v .+ Hs
2x2 Array{Float64,2}:
 3.0  2.0
 5.0  2.0

julia> vs .+ H
2x2 Array{Float64,2}:
 3.0  2.0
 5.0  2.0

julia> vs .+ Hs
2x2 Array{Float64,2}:
 3.0  2.0
 5.0  2.0

# for conformant sparse operands is OK

julia> Hs .* Hs
2x2 sparse matrix with 3 Float64 entries:
        [1, 1]  =  1.0
        [2, 1]  =  4.0
        [2, 2]  =  1.0

# now we lufact(Hs) and show the problem with F[:Rs] .* A[F[:p], F[:q]]

julia> S=lufact(Hs)
UMFPACK LU Factorization of a 2-by-2 sparse matrix
Ptr{Void} @0x0000000020c65560

julia> S[:L]
2x2 sparse matrix with 2 Float64 entries:
        [1, 1]  =  1.0
        [2, 2]  =  1.0

julia> S[:U]
2x2 sparse matrix with 3 Float64 entries:
        [1, 1]  =  -0.333333
        [1, 2]  =  0.666667
        [2, 2]  =  1.0

julia> S[:p]
2-element Array{Int64,1}:
 2
 1

julia> S[:q]
2-element Array{Int64,1}:
 2
 1

julia> S[:Rs]
2-element Array{Float64,1}:
 1.0
 0.333333

julia> Hsperm=Hs[S[:p],S[:q]]
2x2 sparse matrix with 3 Float64 entries:
        [1, 1]  =  -1.0
        [1, 2]  =  2.0
        [2, 2]  =  1.0

julia> S[:Rs] .* Hsperm
ERROR: DimensionMismatch("")
 in .* at sparse/sparsematrix.jl:531

</pre>

### PR DESCRIPTION
**Pull request by amartgon**
I believe this fixes the problem with Vector .\* Sparse and Sparse .\* Vector  (#8416  and JuliaLang/julia#9664)

### CODE REVIEW

**Comment by tkelman** [comment]
This looks like it could substantially slow down elementwise multiplication of sparse matrices with the same sizes, since `broadcast!` is not at all optimized for sparse arrays.

**Comment by tkelman** [comment]
A better solution to this is to stop using 1-column matrices as sparse vectors. There is a PR open for a sparse vector type, might be good to just get that into shape.

**Comment by quinnj** [comment]
Ah yes, I forgot I had got the sparse vector work started. I'll try to pick
that back up to push it along.

**Comment by simonster** [comment]
Shouldn't we make broadcasting work (efficiently) for SparseMatrices whether or not we have sparse vectors?

**Comment by tkelman** [comment]
Yeah, that'd be great. Any proposals for how to go about doing that? This doesn't apply just to sparse, but all of the structured matrix types - and not just to broadcast, but all of the reductions and other "generic" operations throughout base. There isn't currently a great way of conveying or utilizing structural information in an extensible, truly generic way that works for anything that isn't dense. But now I'm repeating myself from #8001. In the meantime, one method at a time, one type at a time.

**Comment by simonster** [comment]
For the case where one input is a SparseMatrix and one is a dense column or row vector, we can just call `scale`, which already exists for SparseMatrixCSC.

For the case where both the inputs are SparseMatrices, one of which is a single row/column, and the output is a SparseMatrix, I'm not sure there is a sufficiently efficient general-purpose way to handle things, and we should probably just implement the methods.

As far as a general purpose way to iterate for reductions etc., we could have something like an iterator version of `findnz` which falls back to @timholy's Cartesian product iterator for the dense case, although I believe there's still some overhead to the Cartesian product iterator and you're right that we may need to think harder about how to handle row-major arrays.

**Comment by ViralBShah** [comment]
I think generic is the harder part, but we should at least make broadcast make with the current sparse data structures.

**Comment by amartgon** [comment]
Things are never as easy as they look at first sight.. Thanks for the performance tests and all the comments: really useful for me to better understand the problem.

I would like to work on making broadcast efficient with SparseMatrixCSC. This first version would work only with 2D, so Cartesian indexing would not be used. Most of the code for efficient operations is already there. It would just be necessary to call it from a broadcast! method and ensure that sparse matrix operations use it consistently.  I also think this is not incompatible with introducing new sparse types in the future. 

Does it make sense?

**Comment by tkelman** [comment]
> Does it make sense?

Yes, if you're interested in taking a crack at it please go ahead.

For sparse broadcast, we may need a new classification to more clearly differentiate operators that produce a nonzero when either of their inputs are nonzero, vs operators that return a nonzero only when both of their inputs are nonzero.

**Comment by JeffBezanson** [comment]
What's the status of this?

**Comment by tkelman** [comment]
Sparse broadcast needs design work. Adding proper SparseVectors has an open PR, but with conflicts and in need of a rebase.

**Comment by amartgon** [comment]
Regarding only broadcast of SparseMatrixCSC: I have been working on it and advancing, though not as fast as I'd like. I think I can have a proposal (implementation) by the end of this week.

It would include a new `broadcast` method for the case of two sparse operands (even though the general broadcast methods take n operands). And another method, which could be called `broadcast_zpreserving`, for binary operations that have zero result when any of the two operands is 0 (such as .*). This `broadcast_zpreserving` would take one sparse operand and other that would be any type of array or constant. 

This would reflect the distinction between types of operators mentioned by tkelman:
>For sparse broadcast, we may need a new classification to more clearly differentiate operators that >produce a nonzero when either of their inputs are nonzero, vs operators that return a nonzero only >when both of their inputs are nonzero.

**Comment by tkelman** [comment]
Sounds like an interesting approach, I look forward to seeing what you can come up with @amartgon.

**Comment by amartgon** [comment]
Here is the proposal. I  think it can be a starting point to be generalized in the future for other sparse structures. Any comments are very welcome.

Bellow a few simple performance tests included. Methods with the suffix "_old" are the old implementation of the operations, which I renamed this way before deleting them. First calls to methods so that they get compiled are omitted.

My conclusion: most operations have a small overhead, but some cases such as  `sparse .* dense` are much faster. Other cases such as `sparse(n x m) .* sparse(n x 1)` did not work at all before.
 
```julia

julia> A = sprand(10000,10000,0.3); B = sprand(10000,10000,0.3); BF = full(B);

julia>  @time A.+B; #new
elapsed time: 0.976550561 seconds (915 MB allocated, 0.64% gc time in 1 pauses with 1 full sweep)

julia>  @time A.+B; #new
elapsed time: 1.031963776 seconds (915 MB allocated, 0.61% gc time in 1 pauses with 1 full sweep)

julia>  @time A.+B; #new
elapsed time: 1.058726632 seconds (915 MB allocated, 9.80% gc time in 1 pauses with 0 full sweep)

julia>  @time A+B; #old
elapsed time: 1.018026417 seconds (915 MB allocated, 12.78% gc time in 2 pauses with 1 full sweep)

julia>  @time A+B; #old
elapsed time: 0.990413792 seconds (915 MB allocated, 10.85% gc time in 2 pauses with 1 full sweep)

julia>  @time A+B; #old
elapsed time: 0.961619903 seconds (915 MB allocated, 11.15% gc time in 2 pauses with 1 full sweep)

julia>

julia>

djulia> @time A.*B; #new
elapsed time: 0.689984741 seconds (915 MB allocated, 0.86% gc time in 1 pauses with 1 full sweep)

julia> @time A.*B; #new
elapsed time: 0.688215981 seconds (915 MB allocated, 0.86% gc time in 1 pauses with 1 full sweep)

julia> @time A.*B; #new
elapsed time: 0.699050298 seconds (915 MB allocated, 1.01% gc time in 1 pauses with 1 full sweep)

julia> @time Base.SparseMatrix.times_old(A,B);  #old
elapsed time: 0.575538209 seconds (915 MB allocated, 7.48% gc time in 2 pauses with 1 full sweep)

julia> @time Base.SparseMatrix.times_old(A,B);  #old
elapsed time: 0.574641348 seconds (915 MB allocated, 7.61% gc time in 2 pauses with 1 full sweep)

julia> @time Base.SparseMatrix.times_old(A,B);  #old
elapsed time: 0.584391185 seconds (915 MB allocated, 7.42% gc time in 2 pauses with 1 full sweep)

julia>

julia>

julia> @time A.*BF; #new
elapsed time: 0.472082517 seconds (457 MB allocated, 1.39% gc time in 1 pauses with 1 full sweep)

julia> @time A.*BF; #new
elapsed time: 0.469774405 seconds (457 MB allocated, 1.42% gc time in 1 pauses with 1 full sweep)

julia> @time A.*BF; #new
elapsed time: 0.480360273 seconds (457 MB allocated, 1.16% gc time in 1 pauses with 1 full sweep)

julia> @time Base.SparseMatrix.times_old(A,BF);  #old
elapsed time: 2.437033787 seconds (1602 MB allocated, 4.56% gc time in 5 pauses with 4 full sweep)

julia> @time Base.SparseMatrix.times_old(A,BF);  #old
elapsed time: 2.500815834 seconds (1602 MB allocated, 5.77% gc time in 4 pauses with 3 full sweep)

julia> @time Base.SparseMatrix.times_old(A,BF);  #old
elapsed time: 2.464224123 seconds (1602 MB allocated, 5.73% gc time in 4 pauses with 3 full sweep)
```

File: base/broadcast.jl [hunk 1]
```diff
@@ -98,6 +99,207 @@ function gen_broadcast_body_iter(nd::Int, narrays::Int, f::Function)
     end
 end
 
+## Broadcasting cores specialized for returning a SparseMatrixCSC
```
Comment (tkelman) [inline base/broadcast.jl]: More common terminology here would be "kernels" rather than "cores"

File: base/number.jl [hunk 2]
```diff
@@ -11,6 +11,8 @@ length(x::Number) = 1
 endof(x::Number) = 1
 getindex(x::Number) = x
 getindex(x::Number, i::Integer) = i == 1 ? x : throw(BoundsError())
+getindex(x::Number, i1::Integer, i2::Integer) = 1 == i1 == i2 ? x : throw(BoundsError())
+getindex(x::Number, i1::Integer, i2::Integer, i3::Integer) = 1 == i1 == i2 == i3 ? x : throw(BoundsError())
```
Comment (tkelman) [inline base/number.jl]: these (and the cholmod changes too) seem small and unrelated, can they be split out?

**Comment by tkelman** [comment]
Overall this looks pretty good, the `sparse .* dense` improvement is especially nice. Have you profiled to see where the ~20% difference in `sparse .* sparse` is coming from? Would be ideal to close that gap, or failing that, leave the existing implementation in place for now. I like the improved generality here, but performance regressions are annoying if we can avoid them.

File: base/broadcast.jl (hunk 1 above)
Comment (amartgon) [inline base/broadcast.jl]: Yes, I agree. I'll correct it. Thanks!

File: base/number.jl (hunk 2 above)
Comment (amartgon) [inline base/number.jl]: The reasons of changes in unrelated files are:
* In sysimg.jl: include sparse.jl before broadcast.jl, needed because SparseMatrixCSC type is now used inside broadcast.jl.
* In cholmod.jl: after the changes in sysimg.jl julia build failed. The reason was that operator .== was being used in cholmod.jl, before it was defined in broadcast.jl. I repaced the operator by equivalent code. This change could probably be avoided by reorganizing the code in the modules (and not modying sysimg.jl), but I think it's cleaner having all broadcasting code together.
* In number.jl: this change makes broadcasting of the types <NUMBER> <OP> <ARRAY> and <ARRAY> <OP> <NUMBER> much faster for the common case of 2 and 3 dimensional arrays (for SparseMatrixCSC, only the 2 dimensions case is relevant).

Comment (tkelman) [inline base/number.jl]: > "NUMBER OP ARRAY" and "ARRAY OP NUMBER"

Didn't SparseMatrixCSC already have specialized implementations for these? They should perhaps have been checking whether the number input was zero, but otherwise I'd expect them to be faster than the more general broadcast approach.

**Comment by amartgon** [comment]
About the ~20% difference in `sparse .* sparse`:

There was also ~10% difference in `sparse .+ sparse`, although in the particular runs I posted it was not clear.
After further testing (and taking into account that the new algorithm is basically the same as the old), It turns out that the differences come from storing the array fields in local variables:
```
colptrA = A.colptr; rowvalA = A.rowval; nzvalA = A.nzval
colptrB = B.colptr; rowvalB = B.rowval; nzvalB = B.nzval
```
I thought it was just a matter of style and omitted it when adapting the code. After changing it, the old and the new version seem to have undistinguishable running times. I'll submit a corrected version.

**Comment by tkelman** [comment]
Yeah, unfortunately manually hoisting field access to temporary variables does make a difference right now. Eventually Julia's compiler might get smart enough to do that kind of thing automatically, but for now it's a little bit of manual code ugliness in exchange for better performance. I should've mentioned this in some code comments, at least you were able to identify it yourself.

Also have a look at #10536 which is somewhat related (sparse reductions rather than broadcast), be aware that the bootstrapping order changes here and there might result in some conflicts that would need to be rebased depending which gets merged first.

**Comment by simonster** [comment]
Linking #9755 for the hoisting issue.

As far as bootstrapping order goes, if we are eventually planning to move sparse matrices to a separate package (as advocated by @tknopp), we should probably try to put all of the sparse matrix-related code in the SparseMatrix module and load it at the end.

**Comment by ViralBShah** [comment]
I don't think it is realistic to move sparse support out of base. What is likely is to have new sparse data structure implementations in packages and make it easy to do so.

**Comment by tkelman** [comment]
Sparse matrices are one of those things like bigints/bigfloats, FFT's, and hell even blas and lapack, that shouldn't really be required runtime dependencies for every piece of code written in the language - if you're not using the functionality it isn't absolutely necessary for the rest of the language to function. This is 1.0-type stuff, but eventually there should be ways of selectively disabling big chunks of what's currently in base, for embedding and static compilation use cases. The shorter-term default situation is we'll probably want to take SuiteSparse out into a package for licensing reasons, but base will need to provide a scaffolding for different packages to be able to plug in various different formats and solver libraries.

File: base/number.jl (hunk 2 above)
Comment (amartgon) [inline base/number.jl]: Yes, I had deleted them. But now I've been testing them and they are faster than broadcasting (and only a couple of lines of code), I'll put them back.
The changes in number.jl  would still be relevant for broadcasting of user-defined functions.

**Comment by amartgon** [comment]
This last commit includes the changes we've been commenting on, and also a reorganization of the new code (moving it from `broadcast.jl` into `/sparsematrix.jl`) so that no modification in the bootstrap process (`sysimg.jl`) is needed. If there are no new comments or detected problems, this could be the final version.

File: base/sparse/sparsematrix.jl [hunk 3]
```diff
@@ -735,8 +892,18 @@ end # macro
...
+.+{Tv1,Ti1,Tv2,Ti2}(A_1::SparseMatrixCSC{Tv1,Ti1}, A_2::SparseMatrixCSC{Tv2,Ti2}) =
+   broadcast!(+, spzeros(eltype_plus(A_1, A_2), promote_type(Ti1, Ti2), broadcast_shape(A_1, A_2)...), A_1, A_2)
+
+function .-{Tva,Tia,Tvb,Tib}(A::SparseMatrixCSC{Tva,Tia}, B::SparseMatrixCSC{Tvb,Tib})
+    broadcast!(-, spzeros(eltype_plus(A, B), promote_type(Tia, Tib), broadcast_shape(A, B)...), A, B)
+end
+
+## element-wise comparison operators returning SparseMatrixCSC ##
+.<{Tv1,Ti1,Tv2,Ti2}(A_1::SparseMatrixCSC{Tv1,Ti1}, A_2::SparseMatrixCSC{Tv2,Ti2}) = broadcast!(<, spzeros( Bool, promote_type(Ti1, Ti2), broadcast_shape(A_1, A_2)...), A_1, A_2)
+.!={Tv1,Ti1,Tv2,Ti2}(A_1::SparseMatrixCSC{Tv1,Ti1}, A_2::SparseMatrixCSC{Tv2,Ti2}) = broadcast!(!=, spzeros( Bool, promote_type(Ti1, Ti2), broadcast_shape(A_1, A_2)...), A_1, A_2)
```
Comment (tkelman) [inline base/sparse/sparsematrix.jl]: `!=` returns true on entries that are zero in both inputs, so this generally won't return sparse

**Comment by tkelman** [comment]
Looks pretty good, thanks for rebasing. It will fail on appveyor due to a hasty broken-on-windows merge yesterday, sorry.

I don't think `broadcast_zpreserving` should be exported.

File: base/sparse/sparsematrix.jl (hunk 3 above)
Comment (amartgon) [inline base/sparse/sparsematrix.jl]: Not sure I undertand... Wouldn't that be `.==`?

Comment (tkelman) [inline base/sparse/sparsematrix.jl]: whoops, too early in the morning, you're right

**Comment by amartgon** [comment]
Here is a version where `broadcast_zpreserving` is not exported.

**Comment by tkelman** [comment]
I like it. I think it would be worth squashing these commits.

@ViralBShah @simonster any feedback?

**Comment by amartgon** [comment]
Any news about this? (Just a friendly reminder).

**Comment by ViralBShah** [comment]
Thanks for the heads up. I really would prefer to see all the broadcasting code go into sparsematrix.jl. Is there a reason to still have some code in broadcast.jl?

Also, can you squash these commits too and rebase to the latest master. I do want to get it merged. Thanks for persisting.

**Comment by ViralBShah** [comment]
@tanmaykm Could you please review this PR too?

**Comment by amartgon** [comment]
Hi!
Code moved into sparsematrix.jl, commits squashed and rebased to lastest master...

**Comment by ViralBShah** [comment]
@amartgon Thanks for this work and for being patient.

**Comment by amartgon** [comment]
Great! Thanks to all who provided helpful comments!
