### PR TITLE
fix another bug in circular type detection

### LINKED ISSUE #41349: certain recursive type definitions are not allocated inline
In this example, Julia does not realize that `B` can be allocated inline, which leads to `B` being boxed when used inside other types:
```julia
julia> struct A{T}
           x::Ptr{T}
       end

julia> struct B
           x::A{B}
       end

julia> B.name.flags
0x00
```

### LINKED ISSUE #41503: Julia nightly throwing at `jl_datatype_isinlinealloc`
A recent version of Julia nightly started throwing errors on tests in Manifolds.jl, see for example these CI runs: https://github.com/JuliaManifolds/Manifolds.jl/pull/381/checks?check_run_id=3010181089 . On Windows, for example, a part of the error reads:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1f9b127 -- jl_datatype_isinlinealloc at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:253 [inlined]
jl_datatype_isinlinealloc at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:250 [inlined]
union_isinlinable at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:277 [inlined]
union_isinlinable at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:266
in expression starting at D:\a\Manifolds.jl\Manifolds.jl\test\centered_matrices.jl:3
```
and on Ubuntu:
```
signal (11): Segmentation fault
in expression starting at /home/runner/work/Manifolds.jl/Manifolds.jl/test/centered_matrices.jl:3
jl_datatype_isinlinealloc at /buildworker/worker/package_linux64/build/src/datatype.c:253 [inlined]
union_isinlinable at /buildworker/worker/package_linux64/build/src/datatype.c:277 [inlined]
jl_islayout_inline at /buildworker/worker/package_linux64/build/src/datatype.c:300
jl_compute_field_offsets at /buildworker/worker/package_linux64/build/src/datatype.c:446
inst_datatype_inner at /buildworker/worker/package_linux64/build/src/jltypes.c:1520
```

I'll try making an MWE.

### PR DESCRIPTION
**Pull request by vtjnash**
Similar to #35275, but through a supertype instead of through the parameters
Fixes #41503
Fixes #41349

### CODE REVIEW

File: src/builtins.c [hunk 1]
```diff
@@ -1487,22 +1487,38 @@ static int equiv_field_types(jl_value_t *old, jl_value_t *ft)
...
 }
 
+// If a field can reference the same type as a field, then the inlining
+// recursive depth is not statically bounded for some layouts, so we cannot
+// inline it. The only way fields can reference this type (due to
+// syntax-enforced restrictions) is via being passed as a type parameter. Thus
+// we can conservatively check this by examining only the parameters of the
+// dependent types.
+// affects_layout is a hack introduced by #35275 to workaround a problem
+// introduced by #34223: it checks whether we will need to potentially need to
```
Comment (JeffBezanson) [inline src/builtins.c:1497]:
```suggestion
// introduced by #34223: it checks whether we will potentially need to
```

File: src/builtins.c [hunk 2]
```diff
@@ -1487,22 +1487,38 @@ static int equiv_field_types(jl_value_t *old, jl_value_t *ft)
     return 1;
 }
 
+// If a field can reference the same type as a field, then the inlining
```
Comment (JeffBezanson) [inline src/builtins.c:1490]:
```suggestion
// If a field can reference its enclosing type, then the inlining
```
?

File: src/builtins.c [hunk 3]
```diff
@@ -1537,16 +1553,23 @@ JL_CALLABLE(jl_f__typebody)
         else {
             dt->types = (jl_svec_t*)ft;
             jl_gc_wb(dt, ft);
-            if (!dt->name->mutabl) {
-                dt->name->mayinlinealloc = 1;
+            // If a supertype can reference the same type, then we may not be
+            // able to compute the layout of the object before needing to
+            // publish it, so we must assume it cannot be inlined, if that
+            // check passes, then we also still need to check the object
```
Comment (JeffBezanson) [inline src/builtins.c:1559]:
```suggestion
            // check passes, then we also still need to check the fields too.
```

**Comment by JeffBezanson** [comment]
Replaces #41359 ?

File: test/core.jl [hunk 4]
```diff
@@ -7219,8 +7219,17 @@ end
...
+@test isbitstype(B33954)
+
+struct A41503{d}
+    e::d
+end
+struct B41503{j,k} <: AbstractArray{A41503{B41503{Any,k}},Any}
+    l::k
+end
+@test !isbitstype(B41503{Any,Any})
+@test_broken isbitstype(B41503{Any,Int})
```
Comment (simeonschaub) [inline test/core.jl:7232]: Test case from #41359:
```suggestion
@test_broken isbitstype(B41503{Any,Int})

# issue #41349
struct A41349{T}
    x::Ptr{T}
end
struct B41349
    x::A41349{B41349}
end
@test isbitstype(B41349)
@test isbitstype(Tuple{B41349})
```

Comment (vtjnash) [reply test/core.jl:7232]: That is already a couple lines higher (where it used to say test_broken)

Comment (simeonschaub) [reply test/core.jl:7232]: It has another level of nesting for the free type parameter though, so I think it wouldn't hurt to have that as another test case.

**Comment by Sacha0** [comment]
Regarding https://github.com/JuliaLang/julia/issues/41503, we hit what appears to be that issue while testing 1.7-beta3. Carrying this patch regrettably does not seem to resolve the presentation that we hit, though reverting https://github.com/JuliaLang/julia/commit/7ffc10bf4ee13d0d0669a6a2315907a2361c38df does. Hope that's helpful :).

**Comment by Sacha0** [comment]
(Please find a stacktrace in https://github.com/JuliaLang/julia/issues/41503#issuecomment-877244616.)

File: src/builtins.c [hunk 5]
```diff
@@ -1537,16 +1553,23 @@ JL_CALLABLE(jl_f__typebody)
...
+            // itselpasses, then we also still need to check the parameters of
+            // the fields too.
```
Comment (vtjnash) [inline src/builtins.c:1561]:
```suggestion
            // check passes, then we also still need to check the fields too.
```

**Comment by JeffBezanson** [comment]
@Sacha0 can you provide an example of a case that still fails with this PR?

**Comment by Sacha0** [comment]
@JeffBezanson I will try to reduce the issue enough to pass something useful along tomorrow. Would an rr trace do the trick, absent an MRE? :)

**Comment by antoine-levitt** [comment]
The issue in https://github.com/JuliaLang/julia/issues/41532 is not fixed by this patch for me (tested in nightly). Reproducer is adding and testing DFTK.

**Comment by JeffBezanson** [comment]
> Would an rr trace do the trick, absent an MRE? :)

An rr trace is as good as gold, as always :)

**Comment by antoine-levitt** [comment]
When running under --bug-report=rr I got a segfault ending with
```
┌ Error: Debugged process failed
│   exitcode = 0
│   termsignal = 11
└ @ BugReporting ~/.julia/packages/BugReporting/AZD4C/src/BugReporting.jl:191
Segmentation fault (core dumped)
```
with no prompt to upload a trace. There's 420M worth of files in a folder in .julia/artifacts/, should I upload that somewhere? But really `Pkg.add("DFTK"); Pkg.test("DFTK")` reproduces the bug reliably and so should be easier to debug than rr.

**Comment by Sacha0** [comment]
Apologies for not noting the following in this thread earlier: We shipped an rr trace to relevant folks out-of-band, from which they were able to produce an MRE, so there may be no need for more at the moment :).
