### PR TITLE
fix #32843, codegen attempting `typeof(NULL)` for some union tags

### LINKED ISSUE #32843: codegen emits `jl_typeof(NULL)` (which obviously segfaults)
I cannot tell you what is causing this error. I apologize.

``` Julia
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type, got=
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6b607810 -- jl_is_tuple_type at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1061 [inlined]
jl_static_show_x_ at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:954
in expression starting at no file:0
jl_is_tuple_type at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1061 [inlined]
jl_static_show_x_ at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:954
jl_static_show_x at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:1030
jl_static_show_x_ at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:983
jl_static_show_x at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:1030 [inlined]
jl_static_show at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:1035
jl_type_infer at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:259
jl_compile_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1797 [inlined]
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1841
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
#9 at C:\Users\julia\AppData\Local\Julia-1.1.1\share\julia\stdlib\v1.1\REPL\src\REPLCompletions.jl:135
filter! at .\array.jl:2338
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
filtered_mod_names at C:\Users\julia\AppData\Local\Julia-1.1.1\share\julia\stdlib\v1.1\REPL\src\REPLCompletions.jl:88
unknown function (ip: 0000000001EB91A5)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
complete_symbol at C:\Users\julia\AppData\Local\Julia-1.1.1\share\julia\stdlib\v1.1\REPL\src\REPLCompletions.jl:143
completions at C:\Users\julia\AppData\Local\Julia-1.1.1\share\julia\stdlib\v1.1\REPL\src\REPLCompletions.jl:714
basecompletionadapter at C:\Users\Francis Smart\.juliapro\JuliaPro_v1.1.1.1\packages\Atom\cR6bU\src\completions.jl:22
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
#193 at C:\Users\Francis Smart\.juliapro\JuliaPro_v1.1.1.1\packages\Atom\cR6bU\src\completions.jl:11
withpath at C:\Users\Francis Smart\.juliapro\JuliaPro_v1.1.1.1\packages\CodeTools\xGemk\src\utils.jl:30
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
withpath at C:\Users\Francis Smart\.juliapro\JuliaPro_v1.1.1.1\packages\Atom\cR6bU\src\eval.jl:46
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
#192 at C:\Users\Francis Smart\.juliapro\JuliaPro_v1.1.1.1\packages\Atom\cR6bU\src\completions.jl:7
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
handlemsg at C:\Users\Francis Smart\.juliapro\JuliaPro_v1.1.1.1\packages\Atom\cR6bU\src\comm.jl:164
unknown function (ip: 000000001407F793)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:556
#19 at .\task.jl:259
unknown function (ip: 000000001407A74A)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2197
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\task.c:572
Allocations: 72694615 (Pool: 72682716; Big: 11899); GC: 162
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
also fixes part of #40065

### CODE REVIEW

File: src/cgutils.cpp [hunk 1]
```diff
@@ -2472,6 +2472,27 @@ static Value *compute_box_tindex(jl_codectx_t &ctx, Value *datatype, jl_value_t
...
+    ctx.builder.SetInsertPoint(nonnull);
+    Value *typof = emit_typeof(ctx, v);
+    ctx.builder.CreateBr(postBB);
+    nonnull = ctx.builder.GetInsertBlock(); // could have changed
+    ctx.builder.SetInsertPoint(postBB);
+    PHINode *ti = ctx.builder.CreatePHI(typof->getType(), 2);
+    ti->addIncoming(Constant::getNullValue(typof->getType()), entry);
+    ti->addIncoming(typof, nonnull);
+    return ti;
+}
```
Comment (vtjnash) [inline src/cgutils.cpp:2494]: FWIW, we have a concise form of this function's pattern now. No need to change this, just thought I'd let you know about the alternative:
```julia
    Value *isnull = ctx.builder.CreateIsNull(v);
    return emit_guarded_test(ctx, isnull, V_rnull, [&] {
          return emit_typeof(ctx, v);
    });
```

**Review by vtjnash — APPROVED** [review]

**Comment by KristofferC** [comment]
I merged this into https://github.com/JuliaLang/julia/pull/40209 with the assumption that this will be merged to master so I can run a PkgEval with this included.
