### PR TITLE
Fix associative types not being shown in full at the REPL. Fixes #14684

### LINKED ISSUE #14684: Displaying a Dict in the REPL is frustrating
E.g.
````
julia> factor(prod(primes(30)))
Dict(7=>1,23=>1,13=>1,2=>1,3=>1,29=>1,19=>1,17=>1,11=>1,5=>1…)
```
The problem: my screen is wide enough to show much more than that.
Worse: this example shows actually all the factors, so the ellipsis is misleading in this case.

I personally prefer the old way of displaying a Dict (in a column), but at least let's use all the line width available (like the current displaying of ranges), and if possible a space after commas for readability. 

PS: IMHO `factor` was already frustrating by not showing the factors in sorted order, but now it is almost unusable as is in the REPL.

### PR DESCRIPTION
**Pull request by Tetralux**
Edit: Be aware I am new to this, so feel free to correct me. :)

This PR reinstates a method for `writemime` which does the pretty-printing for a `Associative` which @vtjnash removed at some point several months ago in preparation for the functionality to be integrated with `show`. See https://github.com/JuliaLang/julia/issues/14684#issuecomment-172042769.

My intention for this PR is to provide a stop-gap until that integration it completed.

### CODE REVIEW

**Comment by H-225** [comment]
It occurs to me that a test for this might be required. If so, let me know and I can do that promptly.

**Comment by tkelman** [comment]
yes please do add a test. thanks!

**Comment by H-225** [comment]
@tkelman Test has been added.

**Comment by H-225** [comment]
The failed check appears to be due to `--compile=all` and is not related to this PR.

File: test/replutil.jl [hunk 1]
```diff
@@ -336,3 +336,11 @@ withenv("JULIA_EDITOR" => nothing, "VISUAL" => nothing, "EDITOR" => nothing) do
     ENV["JULIA_EDITOR"] = "\"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl\" -w"
     @test Base.editor() == ["/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl", "-w"]
 end
+
+# Issue #14684: `display` should prints associative types in full.
+let d = Dict(1 => 2, 3 => 45)
+    buf = IOBuffer()
+    td = TextDisplay(buf)
+    display(td, d)
+    @test bytestring(td.io) == "$(summary(d)):\n  3 => 45\n  1 => 2"
```
Comment (ivarne) [inline test/replutil.jl]: It seems like this test depends on `Dict` values being printed in a particular order (but unlike https://github.com/JuliaLang/julia/pull/15853, it doesn't seem to matter now). Hashing and order might change in the future though.

Comment (H-225) [inline test/replutil.jl]: @ivarne A fair point. I'll change it to match the style of #15853.

**Comment by H-225** [comment]
Rebased and changed test to work regardless of `Dict` ordering of key-value pairs.

**Comment by H-225** [comment]
Squashed the commits.

**Comment by vtjnash** [comment]
thanks!
