### PR TITLE
fix MEMPROFILE code for the new garbage collector

### LINKED ISSUE #12840: MEMPROFILE is broken
Hi All,

I am working on building/porting Julia on ppc64le architecture. I am using Ubuntu 14.10 on top of ppc64le hardware, while compiling Julia code (master branch) I was getting segmentation fault, I am able to resolve this segmentation fault by turning on `MEMDEBUG` flag from `src/options.h` file.

I decided to work more this issue and try to find out root cause of segmentation fault, so I started studying/understanding memory management scheme of Julia. 

To understanding GC and de-allocation mechanism I turn on profiling options `MEMPROFILE`, `GC_TIME` from `options.h`  file (by default they are commented out I uncomment those) but when I try to compile code with these profiling flags on julia compilation (make debug) gets failed.

Below compilation errors I observed after enabling, 
1. `GC_TIME` flag 
   
   ```
   gc.c:237:26: error: current_heap undeclared (first use in this function)
    #define HEAP(x) (*((void)current_heap,&(x)))
   ```
2. `MEMPROFILE` flag
   
   ```
   gc.c:2414:21: error: pool_t has no member named pages
   ```

My Machine details are: 
`Linux 3.16.0-30-generic #40-Ubuntu SMP ppc64le ppc64le ppc64le GNU/Linux`

-Mahesh

### PR DESCRIPTION
**Pull request by vtjnash**
As suggested recently on the issues list.

Fixes #12840

### CODE REVIEW

File: src/gc-debug.c [hunk 1]
```diff
@@ -1078,44 +1075,56 @@ void gc_stats_all_pool(void)
...
+                   (long long)(no ? (nold * 100) / no : 0),
+                   (long long)(nb / 1024),
+                   (long long)(nb ? (noldbytes * 100) / nb : 0),
+                   (long long)tw,
+                   (long long)(nb ? (tw * 100) / nb : 0),
+                   (long long)tp);
 }
 
+size_t jl_array_nbytes(jl_array_t *a) JL_NOTSAFEPOINT;
+
```
Comment (yuyichao) [inline src/gc-debug.c:1090]: Move to .h file instead.

**Review by yuyichao — CHANGES_REQUESTED** [review]

**Review by yuyichao — APPROVED** [review]
