### PR TITLE
Use triple quotes in TOML.print when string contains newline

### LINKED ISSUE #55083: `TOML.print` generates invalid TOML on stdout when the values include multiline strings
```julia
julia> TOML.print(Dict("a" => """x\nx"""))
a = "x\nx"

julia> TOML.parse("""a = "x\nx" """)
ERROR: TOML Parser error:
none:2:-1 error: newline character in single quoted string
  a = "x
       ^ 
Stacktrace:
 [1] parse
   @ ./toml_parser.jl:445 [inlined]
 [2] parse(str::String)
   @ TOML ~/.julia/juliaup/julia-1.10.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/TOML/src/TOML.jl:71
 [3] top-level scope
   @ REPL[99]:1
```

Interestingly, this seems to only be an issue with `stdout` and is handled correctly with other IO streams

```julia
julia> io = IOBuffer();  TOML.print(io, Dict("a" => """x\nx""")); TOML.parse(seekstart(io))
Dict{String, Any} with 1 entry:
  "a" => "x\nx"
```

I'm guessing this intersection of two different expectations -- we generally don't include triple quotes for `show`-type methods going to `stdout`, but in this particular case, it prevents a simple copy-paste of the generated TOML into other use cases.

```julia
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
```

### PR DESCRIPTION
**Pull request by palday**
closes #55083 

Shouldu this also check for `\r`?

### CODE REVIEW

File: stdlib/TOML/src/print.jl [hunk 1]
```diff
@@ -101,9 +101,10 @@ function printvalue(f::MbyFunc, io::IO, value::TOMLValue, sorted::Bool)
     value isa AbstractFloat  ? Base.print(io, isnan(value) ? "nan" :
                                               isinf(value) ? string(value > 0 ? "+" : "-", "inf") :
                                               Float64(value)) :  # TOML specifies IEEE 754 binary64 for float
-    value isa AbstractString ? (Base.print(io, "\"");
+    value isa AbstractString ? (qmark = Base.contains(value, "\n") ? "\"\"\"" : "\"";
```
Comment (ararslan) [inline stdlib/TOML/src/print.jl:104]:
```suggestion
    value isa AbstractString ? (qmark = Base.contains(value, "\n") ? "\"\"\"" : "\"";
```

File: stdlib/TOML/test/print.jl [hunk 2]
```diff
@@ -195,3 +195,13 @@ LocalPkg = {path = "LocalPkg"}
 """
 @test toml_str(d; sorted=true, inline_tables) == s
 @test roundtrip(s)
+
+# multline strings (#55083)
```
Comment (ararslan) [inline stdlib/TOML/test/print.jl:199]: The typo checking CI job apparently fails on typos in comments 🙃
```suggestion
# multiline strings (#55083)
```

**Comment by ararslan** [comment]
> Shouldu this also check for `\r`?

Probably not necessary since what we're looking for here is line endings and both DOS and UNIX line endings contain `\n` already. I wonder what other languages' TOML libraries do for an `\r` without an `\n`.

**Review by KristofferC — APPROVED** [review]
