### PR TITLE
Return original sharedarray object when deserializing on the creating node. 

### LINKED ISSUE #22139: Local instance of remote reference not found
The following is a minimal reproducer of something that a lab member first reported to me on April 25, and it fails on at least 0.5.0, 0.5.2, and 0.6-rc2:
```julia
function breakme!(arrays)
    for i = 1:100
        @show i
        @sync begin
            for (j, w) in enumerate(wprocs)
                @async begin
                    val = j + (i-1)/100
                    arrays[j] = remotecall_fetch(fill!, w, arrays[j], val)
                end
            end
        end
        gc(true)
    end
    arrays
end

wprocs = addprocs(2)
arrays = [SharedArray{Float64}((3, 3); pids=[1,w]) for w in wprocs]
```
With this I get:
```julia
julia> breakme!(arrays)
i = 1
i = 2
ERROR: On worker 2:
Local instance of remote reference not found
channel_from_id at ./distributed/remotecall.jl:144
init_loc_flds at ./sharedarray.jl:388
deserialize at ./sharedarray.jl:425
handle_deserialize at ./serialize.jl:687
deserialize at ./serialize.jl:634
ntuple at ./tuple.jl:108
handle_deserialize at ./serialize.jl:664
deserialize_msg at ./distributed/messages.jl:98
message_handler_loop at ./distributed/process_messages.jl:161
process_tcp_streams at ./distributed/process_messages.jl:118
#99 at ./event.jl:73
#remotecall_fetch#141(::Array{Any,1}, ::Function, ::Function, ::Base.Distributed.Worker, ::SharedArray{Float64,2}, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:354
remotecall_fetch(::Function, ::Base.Distributed.Worker, ::SharedArray{Float64,2}, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:346
#remotecall_fetch#144(::Array{Any,1}, ::Function, ::Function, ::Int64, ::SharedArray{Float64,2}, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:367
remotecall_fetch(::Function, ::Int64, ::SharedArray{Float64,2}, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:367
macro expansion at /home/tim/tmp/evil_sharedarray.jl:8 [inlined]
(::##3#4{Array{SharedArray{Float64,2},1}})() at ./task.jl:335

...and 1 more exception(s).

Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] breakme!(::Array{SharedArray{Float64,2},1}) at /home/tim/tmp/evil_sharedarray.jl:4
```
The explicit `gc` call is not strictly necessary (it fails eventually even without it), but it really helps reproducibility---without it I often have to call `breakme!` multiple times to get it to fail.

I've spent a couple hours debugging this, and while I don't fully understand what's going on, I am pretty sure that it's being triggered by a call to `del_clients` by the SharedArray finalizer. In particular, if you replace
```julia
 arrays[j] = remotecall_fetch(fill!, w, arrays[j], val)
```
with
```julia
a = remotecall_fetch(fill!, w, arrays[j], val)
```
then it doesn't fail. I'm guess that this is something like "two SharedArrays shouldn't point to the same remote object" or something. But that doesn't quite seem right, because `a` also points to the same object. Perhaps the compiler realizes it's not used and does something sneaky?

### PR DESCRIPTION
**Pull request by amitmurthy**
Check and return existing SharedArray objects when deserializing
on the node which created the array.

Closes https://github.com/JuliaLang/julia/issues/22139

The shared array implementation does not serialize/deserialize remote references to the memory mapped segments when `SharedArray` objects are sent between processes. This is to avoid the overhead of distributed `gc`. Only the creating process keeps remote references to the segments, which are released when the `SharedArray` object is collected.     

In #22139, a shared array object is round-tripped from a worker and reassigned to a local variable. Currently, deserializing creates a new object instance and the reassigning resulted in garbage collection of the original object, which in turn resulted in the remote references being released.

This PR fixes it by keeping weak refs to shared array objects created on the local process, and when deserializing locally the existing object is returned.

The PR does not change the requirement that the process creating the shared array needs to continue holding a reference to the object as long as it is used anywhere in the cluster.

For example, the below may still fail depending on when `s` gets collected:
```
s = SharedArray{Float64}(3,3)
r = remotecall(identity, remote_pid, s)
s = nothing
gc()
fetch(r)
```

### CODE REVIEW

**Comment by amitmurthy** [comment]
cc @timholy

File: base/sharedarray.jl [hunk 1]
```diff
@@ -2,7 +2,21 @@
 
 import .Serializer: serialize_cycle_header, serialize_type, writetag, UNDEFREF_TAG
 
+const SA_CTR = Ref(1)
+next_sa_ctr() = (id = SA_CTR[]; SA_CTR[] = id+1; id)
+
+mutable struct SA_ID
```
Comment (timholy) [inline base/sharedarray.jl]: Any particular reason to make this `mutable`? I don't see any code that modifies one after construction. You wouldn't need the `hash` and `==` defs if it were just a `struct`.

File: base/sharedarray.jl [hunk 2]
```diff
@@ -421,9 +455,19 @@ function serialize(s::AbstractSerializer, S::SharedArray)
 end
 
 function deserialize(s::AbstractSerializer, t::Type{<:SharedArray})
+    ref_exists = deserialize(s)
+    if ref_exists
+        sref = sa_refs[SA_ID(deserialize(s), deserialize(s))]
+        if sref.value !== nothing
+            return sref.value
+        else
+            throw(ErrorException("Expected reference to shared array instance not found"))
```
Comment (timholy) [inline base/sharedarray.jl]: Could this just be `error("Expected...")`?

File: base/sharedarray.jl [hunk 3]
```diff
@@ -421,9 +455,19 @@ function serialize(s::AbstractSerializer, S::SharedArray)
 end
 
 function deserialize(s::AbstractSerializer, t::Type{<:SharedArray})
+    ref_exists = deserialize(s)
+    if ref_exists
+        sref = sa_refs[SA_ID(deserialize(s), deserialize(s))]
+        if sref.value !== nothing
+            return sref.value
+        else
```
Comment (timholy) [inline base/sharedarray.jl]: Could just put `end` here, the `else` is redundant because of the `return`.

**Review by timholy — COMMENTED** [review]
LGTM. Many thanks!

File: base/sharedarray.jl (hunk 1 above)
Comment (amitmurthy) [inline base/sharedarray.jl]: You are right. A previous(different) implementation was relying on a finalizer to cleanup.

Now we can just use `Base.Distributed.RRID`. Will update.

**Comment by amitmurthy** [comment]
Updated.

**Comment by amitmurthy** [comment]
AV failure is unrelated (libgit2).

**Comment by timholy** [comment]
Thanks a ton, @amitmurthy!
