### PR TITLE
Correct handling of non-Booleans in at-test

### LINKED ISSUE #35888: Non-booleans in at-test
I would have expected an "Expression evaluated to non-Boolean" here, but at least the test fails:
```julia
julia> using Test

julia> @test isequal(5)
Test Failed at REPL[2]:1
  Expression: isequal(5)
   Evaluated: isequal(5)
ERROR: There was an error during testing
```
This, however, is interesting:
```julia
julia> @test !isequal(5)
Test Passed
```
This happens only on Julia ≥ 1.2. On Julia 1.0 and 1.1, "Expression evaluated to non-Boolean" is printed.

### PR DESCRIPTION
**Pull request by sostock**
Fixes #35888.

### CODE REVIEW

File: stdlib/Test/src/Test.jl [hunk 1]
```diff
@@ -263,18 +263,18 @@ struct Threw <: ExecutionResult
...
     kw_suffix = ""
     if evaluated.head === :comparison
         args = evaled_args
+        res = true
+        i = 1
         while i < n
             a, op, b = args[i], args[i+1], args[i+2]
             if res
-                res = op(a, b) === true  # Keep `res` type stable
+                res = op(a, b)
```
Comment (Keno) [inline stdlib/Test/src/Test.jl:277]: won't this fail on the next iteration if this isn't a bool?

File: stdlib/Test/src/Test.jl [hunk 2]
```diff
@@ -311,7 +311,7 @@ function eval_test(evaluated::Expr, quoted::Expr, source::LineNumberNode, negate
 
     Returned(res,
```
Comment (Keno) [inline stdlib/Test/src/Test.jl:312]: Same on line 308, this expects `res` to be a Bool

File: stdlib/Test/src/Test.jl (hunk 1 above)
Comment (Keno) [reply stdlib/Test/src/Test.jl:277]: same issue below. Maybe just do an early return here if the result turns out not to be `Bool`?

Comment (sostock) [reply stdlib/Test/src/Test.jl:277]: That’s the point, it now matches the behavior outside of `@test`:
```julia
julia> 1 < missing < 2
ERROR: TypeError: non-boolean (Missing) used in boolean context
```

File: stdlib/Test/src/Test.jl (hunk 2 above)
Comment (sostock) [reply stdlib/Test/src/Test.jl:312]: Line 308 doesn’t expect `res` to be a `Bool`, it just expects a type for which a `Base.:!` is defined. Otherwise it errors, like it should. In my opinion, that’s the desired behavior (if we don’t want code inside `@test` to behave differently from code outside of it).

File: stdlib/Test/src/Test.jl (hunk 1 above)
Comment (sostock) [reply stdlib/Test/src/Test.jl:277]: Returning early is wrong, we *want* an error to be thrown (`eval_test` is always run inside a `try` block).

Comment (sostock) [reply stdlib/Test/src/Test.jl:277]: I could make `eval_test` return a `Threw` object in these cases instead of actually throwing (and I would do so if you think it’s better), but I don’t see the point of that. The evaluation of the test expression can throw nonetheless and I think it’s clearer to do the error handling in one place (in the expression returned by `get_test_result`).
