### PR TITLE
Fix `remove-argument-side-effects` with keyword call

### LINKED ISSUE #60152: keyword arguments don't work on left-hand side of broadcast assignments
Copied from [this Discourse thread](https://discourse.julialang.org/t/keyword-arguments-not-allowed-on-left-hand-side-of-broadcast-assignments/133920).

Broadcasting with assignment works with a function call on the left-hand side. However, function calls with keyword arguments do not work for some reason:
```
julia> f(v; a = 0) = copy(v)
f (generic function with 1 method)

julia> f([1, 2, 3]) .*= 2
3-element Vector{Int64}:
 2
 4
 6

julia> f([1, 2, 3]; a = 1) .*= 2
ERROR: syntax: invalid syntax ; (thismodule).a = 1
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

Here is what @stevengj commented on Discourse:

> A similar error occurs with Julia 1.9.4, which uses the old Scheme parser, so the problem doesn’t seem specific to the new JuliaSyntax.jl. In fact, `Meta.parse("f([1,2,3]; a=1) .*= 2")` succeeds so it doesn’t seem to be a parser issue at all, but rather a problem in the lowering phase.

```
Julia Version 1.12.1
Commit ba1e628ee49 (2025-10-17 13:02 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by mlechu**
Fix #60152, which impacted both lowering implementations.
      `remove-argument-side-effects` assumed all `kw` arguments from a
     `parameters` block had already been dumped into the argument list, which is
     not true in some cases.  In addition:

- JuliaLowering hit a MethodError in the dumped-`kw` case regardless.  There are other issues with `kw` which I'm ignoring in this PR (see https://github.com/JuliaLang/julia/pull/60162)

- Delete some ancient history: `&` [used to be a valid argument](https://github.com/JuliaLang/julia/commit/a378b750fd7e387f0504e7605c464944092e29e1#diff-5d79463faae0f7f19454c7f9888498d9f876082e258ab3efdca36a0ee64b0c87L72) head sometime in 2012 apparently!

### CODE REVIEW

File: test/syntax.jl [hunk 1]
```diff
@@ -3746,6 +3746,15 @@ end
     let; execs += 1; array; end::Vector{Int} .= 7
     @test array == [7]
     @test execs == 4
+
+    # remove argument side effects on lhs kwcall
+    pa_execs = 0
+    kw_execs = 0
+    f60152(v, pa; kw) = copy(v)
+    @test (f60152([1, 2, 3], 0; kw=0) .*= 2) == [2,4,6]
```
Comment (Keno) [inline test/syntax.jl:3754]: Should this function do something with the kw, to make sure it actually as the right value?

Comment (Keno) [reply test/syntax.jl:3754]: Maybe the test below is enough, although it technically tests something slightly different.

**Review by Keno — APPROVED** [review]

**Comment by matthias314** [comment]
Thanks for fixing this! Should the fix be backported?

**Comment by mlechu** [comment]
The flisp part (julia-syntax.scm, test/syntax.jl) could be backported
