### PR TITLE
make `sign(pi)` work

### LINKED ISSUE #37931: `sign(pi)` errors
Didn't find an existing issue
```
julia> sign(pi)
ERROR: InexactError: Bool(-1)
```
https://discourse.julialang.org/t/problem-with-sign-pi/47801/

### PR DESCRIPTION
**Pull request by Moelf**
fix #37931

### CODE REVIEW

**Comment by Moelf** [comment]
just leave it here for discussion, it's conceptually annoying to me.
This fix is not perfect, because now `one(pi) !== sign(pi)`. But fixing `one(pi)` to 1.0 will be a breaking change?

File: base/number.jl [hunk 1]
```diff
@@ -133,6 +133,7 @@ signbit(x::Real) = x < 0
 Return zero if `x==0` and ``x/|x|`` otherwise (i.e., ±1 for real `x`).
 """
 sign(x::Number) = iszero(x) ? x/abs(oneunit(x)) : x/abs(x)
+sign(x::AbstractIrrational) = ifelse(x < zero(x), -1.0, 1.0)
```
Comment (JeffBezanson) [inline base/number.jl:136]: Should move this to irrationals.jl.

File: test/numbers.jl [hunk 2]
```diff
@@ -460,6 +460,8 @@ end
     @test sign(-0//1) == 0
     @test sign(1//0) == 1
     @test sign(-1//0) == -1
+    @test sign(pi) === 1.0
```
Comment (petvana) [inline test/numbers.jl:463]:
```suggestion
    @test sign(pi) == 1
```
This allowes different return type in the future. Like for `@test sign(1.0) == 1`

**Review by carstenbauer — APPROVED** [review]

File: test/numbers.jl [hunk 3]
```diff
@@ -460,6 +460,8 @@ end
     @test sign(-0//1) == 0
     @test sign(1//0) == 1
     @test sign(-1//0) == -1
+    @test sign(pi) == 1
+    @test sign(pi) === -sign(-pi)
```
Comment (fingolfin) [inline test/numbers.jl:464]: Note that `-pi` is a `Float64`, so your second new test doesn't really test anything...

Comment (petvana) [reply test/numbers.jl:464]: I believe, in addition to `@test sign(-pi) == -1`, it tests `sign()` returns the same type. This may be also beneficial for other cases for detecting possible type instability.

Comment (Moelf) [reply test/numbers.jl:464]: @fingolfin we reasoned that since `-pi` goes to Float64, `sing(pi)` should also return a Float64. This is to test that

**Comment by StefanKarpinski** [comment]
Bump? This seems reasonable to me.

**Comment by Moelf** [comment]
half-year gentel bump

**Comment by StefanKarpinski** [comment]
Is closing and reopening the pull request still a way to restart CI?

**Comment by oscardssmith** [comment]
can we rebase and merge?

**Comment by Moelf** [comment]
oh no

File: base/irrationals.jl [hunk 4]
```diff
@@ -153,6 +153,8 @@ zero(::Type{<:AbstractIrrational}) = false
 one(::AbstractIrrational) = true
 one(::Type{<:AbstractIrrational}) = true
 
+sign(x::AbstractIrrational) = ifelse(x < zero(x), -1.0, 1.0)
```
Comment (stevengj) [inline base/irrationals.jl:156]: Why not return `±1` (`Int`) instead of `±1.0`?

For example, you'd ideally like `sign(pi) * 2.3f0` to return a `Float32`, not a `Float64`.

Comment (Moelf) [reply base/irrationals.jl:156]: Because  -pi returns Float64

Comment (ViralBShah) [reply base/irrationals.jl:156]: Feels to me that returning integers is better.

Comment (Moelf) [reply base/irrationals.jl:156]: if we return an integer here, then there will be three different types among:
- `sign(pi)`
- `zero(pi)`
- `-pi`

Comment (fingolfin) [reply base/irrationals.jl:156]: If integer is better here, wouldn't it then also be better for `sign(::Float64)`? (No, I am not suggesting to make this change, it'd surely be breaking)

Comment (Moelf) [reply base/irrationals.jl:156]: yeah, sign should be Int8 for everything really
