### PR TITLE
fix a number of minor nits with inline line numbers

### LINKED ISSUE #17317: Backtraces: some line numbers are still 0
```jl
@inline foo1(x) = foo2(x)
@inline foo2(x) = foo3(x)
@noinline foo3(x) = x ÷ 3

function bar(n)
    X = rand(1:10, n)
    Y = [foo1(x) for x in X]
end

bar(1)
@profile bar(10^7)
data = unique(Profile.fetch())
vsf = Base.StackTraces.lookup.(data)
for sfs in vsf
    for sf in sfs
        if sf.line == 0
            @show sf
        end
    end
end
```
Results:
```jl
sf =  in rand at random.jl:0 [inlined]
sf =  in rand at random.jl:0 [inlined]
sf =  in rand(::MersenneTwister, ::Base.Random.RangeGeneratorInt{Int64,UInt64}) at random.jl:0
sf =  in mt_setfull! at random.jl:0 [inlined]
sf =  in reserve_1 at random.jl:0 [inlined]
sf =  in rand_ui52_raw at random.jl:0 [inlined]
sf =  in rand at random.jl:0 [inlined]
sf =  in mt_pop! at random.jl:0 [inlined]
sf =  in rand_inbounds at random.jl:0 [inlined]
sf =  in rand_ui52_raw_inbounds at random.jl:0 [inlined]
sf =  in rand_ui52_raw at random.jl:0 [inlined]
sf =  in rand at random.jl:0 [inlined]
sf =  in rand(::MersenneTwister, ::Base.Random.RangeGeneratorInt{Int64,UInt64}) at random.jl:0
sf =  in rand(::MersenneTwister, ::Base.Random.RangeGeneratorInt{Int64,UInt64}) at random.jl:0
sf =  in gen_rand at random.jl:0 [inlined]
sf =  in reserve_1 at random.jl:0 [inlined]
sf =  in rand_ui52_raw at random.jl:0 [inlined]
sf =  in rand at random.jl:0 [inlined]
sf =  in foo3(::Int64) at testprof.jl:0
```
This is with a completely-fresh julia master,
```jl
julia> versioninfo()
Julia Version 0.5.0-dev+5188
Commit 36d36b0* (2016-07-07 03:28 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

### PR DESCRIPTION
**Pull request by vtjnash**
- the inlining pass would discard the first LineNumberNode, without
  checking that it matched the line number of the function declaration
- the CurrentDebugLocation shouldn't be set while emitting the prologue
- implement inlining info for pre-MCJIT llvm
- improve printing of relative symbols in disassembly (e.g. 'callq "_setindex!"')
  and hide the first line number if it is zero
- print inlining info during jl_gdblookup

also fix llvm 3.3 build

fix #17317

### CODE REVIEW

File: src/ccall.cpp [hunk 1]
```diff
@@ -246,8 +247,8 @@ static Value *emit_plt(FunctionType *functype, const AttributeSet &attrs,
                                         llvmgv, runtime_lib);
         builder.CreateStore(builder.CreateBitCast(ptr, T_pvoidfunc), got);
         SmallVector<Value*, 16> args;
-        for (auto &arg: plt->args())
-            args.push_back(&arg);
+        for (Function::arg_iterator arg = plt->arg_begin(), arg_e = plt->arg_end(); arg != arg_e; ++arg)
+            args.push_back(&*arg);
```
Comment (yuyichao) [inline src/ccall.cpp]: Is this change still necessary with the `LLVM37` `ifdef` above?

**Comment by timholy** [comment]
Anything worth stealing from the test-case in #17317, as a test?

**Comment by JeffBezanson** [comment]
Nice, thanks.

File: src/ccall.cpp [hunk 2]
```diff
@@ -1694,14 +1696,16 @@ static jl_cgval_t emit_ccall(jl_value_t **args, size_t nargs, jl_codectx_t *ctx)
 
         PointerType *funcptype = PointerType::get(functype,0);
         if (imaging_mode) {
-#if defined(_CPU_ARM_) || defined(_CPU_PPC_) || defined(_CPU_PPC64_)
-            // ARM, PPC, PPC64 (as of LLVM 3.9) doesn't support `musttail`
-            // for vararg functions.
-            if (functype)
+#ifdef LLVM37
+            // ARM, PPC, PPC64 (as of LLVM 3.9) doesn't support `musttail` for vararg functions.
```
Comment (tkelman) [inline src/ccall.cpp]: don't support

File: src/ccall.cpp [hunk 3]
```diff
@@ -1694,14 +1696,16 @@ static jl_cgval_t emit_ccall(jl_value_t **args, size_t nargs, jl_codectx_t *ctx)
...
+            // And musttail can't proceed unreachable, but is required for vararg (https://llvm.org/bugs/show_bug.cgi?id=23766)
```
Comment (tkelman) [inline src/ccall.cpp]: what does "can't proceed unreachable" mean?

Comment (yuyichao) [inline src/ccall.cpp]: precede

File: src/debuginfo.cpp [hunk 4]
```diff
@@ -1277,50 +1277,61 @@ int jl_getFunctionInfo(jl_frame_t **frames_out, size_t pointer, int skipC, int n
...
-                char *oldname = frames[0].func_name;
-                frames[0].func_name = jl_demangle(frames[0].func_name);
-                free(oldname);
-            }
+        LLVMContext &Ctx = (*it).second.func->getContext();
+
+        DISubprogram debugscope(prev.Loc.getScope(Ctx));
+        jl_copy_str(&frames[0].file_name, debugscope.getFilename().str().c_str());
+        // the DISubprogram has the un-mangled name, so use that if
+        // available. However, if the scope need not be the current
```
Comment (tkelman) [inline src/debuginfo.cpp]: grammar makes no sense here - what is "if the scope need not be the current subprogram" trying to say?

File: src/ccall.cpp (hunk 1 above)
Comment (vtjnash) [inline src/ccall.cpp]: Not really, but I wanted to keep the code consistent, since the only bit missing is musttail.

File: src/debuginfo.cpp (hunk 4 above)
Comment (tkelman) [inline src/debuginfo.cpp]: @Keno what is this trying to say? d912e42bd253bc460d53c09b49205a52d9e24110

Comment (Keno) [inline src/debuginfo.cpp]: If I had to guess I'd say that the `if` is superflous and that the scope can be file scope rather than function scope.

**Comment by timholy** [comment]
I spent a few minutes trying to add some tests, but it doesn't seem straightforward.
