### PR TITLE
fixes #10318

### LINKED ISSUE #10318: UnixDomainCM test often fails
e.g. here https://travis-ci.org/JuliaLang/julia/jobs/52073495

I also see this *very* often when running the tests locally on linux.

### PR DESCRIPTION
**Pull request by amitmurthy**
Closes #10318

### CODE REVIEW

File: examples/clustermanager/simple/UnixDomainCM.jl [hunk 1]
```diff
@@ -9,7 +9,7 @@ function launch(manager::UnixDomainCM, params::Dict, launched::Array, c::Conditi
     for i in 1:manager.np
         sockname = tempname()
         try
-            cmd = `$(params[:exename]) --worker=custom $(@__FILE__) worker $sockname`
```
Comment (amitmurthy) [inline examples/clustermanager/simple/UnixDomainCM.jl]: @jakebolewski - sometime the workers were launched with "worker" option set as default (and this was responsible for #10318) . I suspect it to be due to the second "worker" argument towards the end. Do you think this is a possibility with the way `getopt_long` works?

Comment (jakebolewski) [inline examples/clustermanager/simple/UnixDomainCM.jl]: Did the filename have a "-" character in it?  Do you have any examples of what the arguments were that caused this to happen?

Comment (amitmurthy) [inline examples/clustermanager/simple/UnixDomainCM.jl]: No. And I don't have the actual args printed either. The command would have been something like 

`home/bezanson/src/julia/usr/bin/julia --worker=custom /home/bezanson/src/julia/usr/share/doc/julia/examples/clustermanager/simple/UnixDomainCM.jl worker /tmp/juliaxHYvd3`
