### PR TITLE
Fix Ctrl+Q for stack traces

### LINKED ISSUE #36340: Ctrl+Q stopped working for stack traces etc.
After #35556, Ctrl+Q works only if the method table is shown via `display(d::REPLDisplay, mime::MIME"text/plain", x)`.  So, for example, Ctrl+Q still works with `methods(Base._in)` but not with `?Base._in`.  Ctrl+Q also does not work with stacktraces anymore.

I still think #35556 is a good approach because it makes `show` on method table thread-safe.  So, I'd suggest to keep #35556 and somehow find a way to use the display system for the cases where Ctrl+Q does not work.  But I'm also OK with reverting #35556 if Ctrl+Q on, e.g., stacktraces is essential for people and the fix is hard.

cc @simeonschaub

### PR DESCRIPTION
**Pull request by simeonschaub**
This should be a more general fix than #36341. It currently silently gets stuck while generating precompile statements on my machine, but not sure if that's reproducible.

close #36340

### CODE REVIEW

**Comment by tkf** [comment]
Maybe try `debug_output = stdout`?

https://github.com/JuliaLang/julia/blob/bf3ed5788eb9993db71798372128d47855d86715/contrib/generate_precompile.jl#L69

File: stdlib/REPL/src/REPL.jl [hunk 1]
```diff
@@ -451,7 +456,7 @@ mutable struct LineEditREPL <: AbstractREPL
         new(t,hascolor,prompt_color,input_color,answer_color,shell_color,help_color,history_file,in_shell,
             in_help,envcolors,false,nothing, Options(), nothing, Tuple{String,Int}[])
 end
-outstream(r::LineEditREPL) = r.t
+outstream(r::LineEditREPL) = IOContext(r.t, :LAST_SHOWN_LINE_INFOS => r.last_shown_line_infos)
```
Comment (tkf) [inline stdlib/REPL/src/REPL.jl:459]: Don't you need to `empty!` it? Or maybe just use `Tuple{String,Int}[]` as before?

Comment (simeonschaub) [reply stdlib/REPL/src/REPL.jl:459]: No, `r.last_shown_line_infos` is still needed later to actually jump to the correct definition. The functions that then write to `LAST_SHOWN_LINE_INFOS` should actually `empty!` this array already.

File: stdlib/REPL/src/REPL.jl [hunk 2]
```diff
@@ -212,29 +212,34 @@ function display(d::REPLDisplay, mime::MIME"text/plain", x)
...
 display(d::REPLDisplay, x) = display(d, MIME("text/plain"), x)
 
 function print_response(repl::AbstractREPL, @nospecialize(response), show_value::Bool, have_color::Bool)
     repl.waserror = response[2]
     io = IOContext(outstream(repl), :module => Main)
+
     print_response(io, response, show_value, have_color, specialdisplay(repl))
+
+    if repl isa LineEditREPL && !isempty(repl.last_shown_line_infos)
+        repl.last_shown_line_infos = infos
```
Comment (simeonschaub) [inline stdlib/REPL/src/REPL.jl:236]: :facepalm: That line should have been deleted

File: stdlib/REPL/src/REPL.jl (hunk 1 above)
Comment (simeonschaub) [reply stdlib/REPL/src/REPL.jl:459]: Apparently, this doesn't always get cleared though...

Comment (simeonschaub) [reply stdlib/REPL/src/REPL.jl:450]: I think you are right, this should still get emptied, because otherwise `last_shown_line_infos` is not empty when other things get printed to the REPL and the hint still gets shown.

**Comment by simeonschaub** [comment]
@tkf What do you think should be done about the helpmode case? The relevant code is in `docview.jl`, but the problem is that `io` is not passed through as an argument and some of those functions are documented, so I don't know if we can just easily change them.

**Comment by tkf** [comment]
I guess we need https://github.com/JuliaLang/julia/issues/34949 to fix help mode? This PR as-is is still a big usability improvement/fix so I think we should just merge this.

Do you think it's possible to write a few tests for this?

**Comment by simeonschaub** [comment]
It's probably possible to write a test here, but I'm not really familiar with how `REPLTests.fake_repl` works, so I would appreciate any pointers from people who have written those existing REPL tests. Last time I looked into it, I didn't get very far.

**Comment by tkf** [comment]
I think it'd be easier to unit-test this than doing an integration test. It's a bit cumbersome to setup a REPL instance, though:

```julia
julia> term = REPL.TTYTerminal("dumb",IOBuffer(),IOBuffer(),IOBuffer());

julia> repl = REPL.LineEditREPL(term, false);

julia> repl.specialdisplay = REPL.REPLDisplay(repl);

julia> REPL.print_response(repl, (:hello, false), true, false)

julia> String(take!(term.out_stream))
":hello\n"
```

**Comment by simeonschaub** [comment]
> I guess we need #34949 to fix help mode? This PR as-is is still a big usability improvement/fix so I think we should just merge this.

 #36289 doesn't really buy us a lot here, because `methods` actually gets called in e.g. `Docs.@doc Base._in`, which in turn calls `REPL.lookup_doc`, so fixing this would mean having to change how parts of the Docs module work.

**Comment by tkf** [comment]
Ah, I see. So `Docs.@doc` macro creates a string before it is printed again. Yeah, it sounds like a non-trivial problem.

File: stdlib/REPL/src/REPL.jl [hunk 3]
```diff
@@ -451,7 +447,11 @@ mutable struct LineEditREPL <: AbstractREPL
         new(t,hascolor,prompt_color,input_color,answer_color,shell_color,help_color,history_file,in_shell,
             in_help,envcolors,false,nothing, Options(), nothing, Tuple{String,Int}[])
 end
-outstream(r::LineEditREPL) = r.t
+function outstream(r::LineEditREPL)
+    linfos = r.last_shown_line_infos
+    empty!(linfos)
+    IOContext(r.t, :LAST_SHOWN_LINE_INFOS => linfos)
```
Comment (tkf) [inline stdlib/REPL/src/REPL.jl:453]:
```suggestion
    IOContext(r.t, :LAST_SHOWN_LINE_INFOS => Tuple{String,Int}[])
```

File: stdlib/REPL/src/REPL.jl [hunk 4]
```diff
@@ -212,29 +212,25 @@ function display(d::REPLDisplay, mime::MIME"text/plain", x)
...
 end
 display(d::REPLDisplay, x) = display(d, MIME("text/plain"), x)
 
 function print_response(repl::AbstractREPL, @nospecialize(response), show_value::Bool, have_color::Bool)
     repl.waserror = response[2]
     io = IOContext(outstream(repl), :module => Main)
+
     print_response(io, response, show_value, have_color, specialdisplay(repl))
+
+    if repl isa LineEditREPL && !isempty(repl.last_shown_line_infos)
```
Comment (tkf) [inline stdlib/REPL/src/REPL.jl:227]:
```suggestion
    if repl isa LineEditREPL && !isempty(infos)
        repl.last_shown_line_infos = infos
```

File: stdlib/REPL/src/REPL.jl [hunk 5]
```diff
@@ -212,29 +212,25 @@ function display(d::REPLDisplay, mime::MIME"text/plain", x)
...
-        )
-    end
-
     nothing
 end
 display(d::REPLDisplay, x) = display(d, MIME("text/plain"), x)
 
 function print_response(repl::AbstractREPL, @nospecialize(response), show_value::Bool, have_color::Bool)
     repl.waserror = response[2]
     io = IOContext(outstream(repl), :module => Main)
```
Comment (tkf) [inline stdlib/REPL/src/REPL.jl:223]:
```suggestion
    infos = Tuple{String,Int}[]
    io = IOContext(outstream(repl), :module => Main, :LAST_SHOWN_LINE_INFOS => infos)
```

File: stdlib/REPL/src/REPL.jl [hunk 6]
```diff
@@ -451,7 +447,11 @@ mutable struct LineEditREPL <: AbstractREPL
         new(t,hascolor,prompt_color,input_color,answer_color,shell_color,help_color,history_file,in_shell,
             in_help,envcolors,false,nothing, Options(), nothing, Tuple{String,Int}[])
 end
-outstream(r::LineEditREPL) = r.t
+function outstream(r::LineEditREPL)
+    linfos = r.last_shown_line_infos
+    empty!(linfos)
+    IOContext(r.t, :LAST_SHOWN_LINE_INFOS => linfos)
+end
```
Comment (tkf) [inline stdlib/REPL/src/REPL.jl:454]:
```suggestion
outstream(r::LineEditREPL) = r.t
```

**Review by tkf — COMMENTED** [review]
I think it's better to set `IOContext` outside `outstream`.  This function sounds like an accessor function and having a side-effect is not great.  For example, it'd mean some innocent use like

https://github.com/JuliaLang/julia/blob/5142abf4507525a7a02e7d984ce39802ee4fe134/stdlib/REPL/src/REPL.jl#L982

would clear out `last_shown_line_infos`.  I think it'd be cleaner if we can keep `outstream` as a simple accessor.  We've already discussed this in https://github.com/JuliaLang/julia/pull/36344#discussion_r442324513 but do you think the change I suggested here work?  It's just moving what we were doing in `display` to `print_response`.

File: stdlib/REPL/src/REPL.jl (hunk 6 above)
Comment (simeonschaub) [reply stdlib/REPL/src/REPL.jl:454]: Interestingly enough, that doesn't work for `show(::MethodTable)` anymore. Will have to investigate.

**Comment by KristofferC** [comment]
Bump.

File: stdlib/REPL/test/replcompletions.jl [hunk 7]
```diff
@@ -110,7 +110,7 @@ end
 
 let s = "using REP"
     c, r = test_complete(s)
-    @test count(isequal("REPL"), c) == 1
+    @test count(isequal("REPL"), c) == 2
```
Comment (simeonschaub) [inline stdlib/REPL/test/replcompletions.jl:113]: I have no clue what's going on here...

**Review by simeonschaub — COMMENTED** [review]
Sorry, my laptop crashed, that's why it took me some time to restore the changes I made. I refactored most of the logic behind the hint message into `with_methodtable_hint` to avoid duplicating this code. I also realized that `LAST_SHOWN_LINE_INFOS` should probably be lowercase now, since it's no longer a global variable.

File: stdlib/REPL/test/replcompletions.jl (hunk 7 above)
Comment (simeonschaub) [reply stdlib/REPL/test/replcompletions.jl:113]: Weird, this now breaks the CI test,  but was needed locally on my machine for tests to pass 🤔.

Comment (KristofferC) [reply stdlib/REPL/test/replcompletions.jl]: > Weird, this now breaks the CI test, but was needed locally on my machine for tests to pass

Yeah, it's a bug in the REPL tests.

Comment (simeonschaub) [reply stdlib/REPL/test/replcompletions.jl]: Does CI run the tests with different options or why isn't this bug present there?

Comment (KristofferC) [reply stdlib/REPL/test/replcompletions.jl]: https://github.com/JuliaLang/julia/issues/32377 has some more info.

File: base/methodshow.jl [hunk 8]
```diff
@@ -240,17 +240,17 @@ function show_method_table(io::IO, ms::MethodList, max::Int=-1, header::Bool=tru
     end
     n = rest = 0
     local last
-    LAST_SHOWN_LINE_INFOS = get(io, :LAST_SHOWN_LINE_INFOS, Tuple{String,Int}[])
+    last_shown_line_infos = get(io, :last_shown_line_infos, Tuple{String,Int}[])
 
-    resize!(LAST_SHOWN_LINE_INFOS, 0)
+    resize!(last_shown_line_infos, 0)
```
Comment (KristofferC) [inline base/methodshow.jl:245]: What's the point in modifying `last_shown_line_infos` when it isn't provided by the `io`? The result will never be used in that case, right?

Comment (simeonschaub) [reply base/methodshow.jl:245]: Yes, you are correct, this was just the easiest way to implement this at the time. Do you think it's worth refactoring this logic?

File: stdlib/REPL/test/replcompletions.jl (hunk 7 above)
Comment (simeonschaub) [reply stdlib/REPL/test/replcompletions.jl]: Ah, thanks for the pointer!

File: base/methodshow.jl (hunk 8 above)
Comment (KristofferC) [reply base/methodshow.jl:245]: I think it would be better to do 

```
last_linfo = get(io, :last_shown_line_infos, nothing)
...
last_linfo === nothing || push!(last_shown_line_infos, (string(file), line))
```

Is the `resize!` needed now? There is always a length zero coming from the `io`, no?

**Comment by staticfloat** [comment]
Just a note that this is somehow freezing up the buildbots :(

**Comment by simeonschaub** [comment]
Are they actually frozen? To me, it looked like they finished, but somehow didn't report back correctly to GitHub. Might have been because GitHub was down for a while?

**Comment by tkf** [comment]
Yeah it looks like the problem is on GitHub side. For example, `tester_linux64` is finished but `package_linux64` still says it's pending.

File: base/methodshow.jl (hunk 8 above)
Comment (tkf) [reply base/methodshow.jl:245]: I think we still need `resize!` since you can print multiple stack traces in one `io`. Previous discussion:

https://github.com/JuliaLang/julia/pull/35556#discussion_r435535024
https://github.com/JuliaLang/julia/pull/35556#issuecomment-643663448

**Comment by staticfloat** [comment]
> Are they actually frozen? To me, it looked like they finished, but somehow didn't report back correctly to GitHub.

Yes they're freezing, I go in manually and end them.  Here's one that was been running for 21 hours before I killed it: https://build.julialang.org/#/builders/77/builds/1247

**Comment by simeonschaub** [comment]
Do you think that's related to this PR? That's kind of the annoying thing about changing something in REPL – You change some small thing and suddenly some other thing gets silently broken/stuck. :smile:

**Comment by staticfloat** [comment]
Yes, it's been consistent with this PR, unfortunately.  Here's another one: https://build.julialang.org/#/builders/77/builds/1281

That being said, the latest version of this seems to have made it through the `package_*` builders for `win64`, so maybe you fixed it?  I'm only seeing it on Windows, perhaps there's something particularly weird about that platform's handling of this?

**Comment by simeonschaub** [comment]
Weird... I don't see how any of these changes could have fixed this.

**Comment by simeonschaub** [comment]
I've rebased onto the latest master, let's hope the Windows build still goes through. :grin:

**Comment by simeonschaub** [comment]
@staticfloat All tests now passed, so it seems like this should be ok now. @tkf Would you be willing to review?

File: stdlib/REPL/src/REPL.jl [hunk 9]
```diff
@@ -495,6 +484,22 @@ function complete_line(c::LatexCompletions, s)
     return unique!(map(completion_text, ret)), partial[range], should_complete
 end
 
+with_methodtable_hint(f, repl) = f(outstream(repl))
+function with_methodtable_hint(f, repl::LineEditREPL)
```
Comment (tkf) [inline stdlib/REPL/src/REPL.jl:488]: :+1: I think this is a clean approach!

**Review by tkf — APPROVED** [review]
LGTM!

**Comment by tkf** [comment]
@KristofferC Do you want to review it again?

If no objections, let's merge this in a few days.

**Comment by simeonschaub** [comment]
Bump.

**Comment by tkf** [comment]
Thanks for the fix! (and the ping)
