### PR TITLE
Don't error when transposing an empty buffer

### LINKED ISSUE #45417: `EOFError` in the REPL on pressing `ctrl+t` after typing a single character
Steps to reproduce
```julia
julia> # press any alphanumeric character key here, eg 'a', followed by ctrl + t

julia> a┌ Error: Error in the keymap
│   exception =
│    EOFError: read end of file
│    Stacktrace:
│      [1] read
│        @ ./iobuffer.jl:217 [inlined]
│      [2] read
│        @ ./io.jl:776 [inlined]
│      [3] edit_transpose_chars(buf::IOBuffer)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:1094
│      [4] edit_transpose_chars(s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:1086
│      [5] (::REPL.LineEdit.var"#163#218")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2397
│      [6] #invokelatest#2
│        @ ./essentials.jl:799 [inlined]
│      [7] invokelatest
│        @ ./essentials.jl:796 [inlined]
│      [8] (::REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#163#218", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:1533
│      [9] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2665
│     [10] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2567
│     [11] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/REPL.jl:1253
│     [12] (::REPL.var"#49#54"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL ./task.jl:494
└ @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2667

julia> VERSION
v"1.9.0-DEV.624"
```

From the [discourse thread](https://discourse.julialang.org/t/what-does-the-repl-keybinding-ctrl-t-correspond-to/81424/2), I understand that `ctrl+t` performs a character transpose. Perhaps this should be a no-op if there's only one character on the line?

### PR DESCRIPTION
**Pull request by perryprog**
This fixes an issue where transposing an empty buffer in the REPL with ^T would cause an error.

Fixes #45417—for real this time! (See also #45420, which introduced this bug.)

### CODE REVIEW

File: stdlib/REPL/src/LineEdit.jl [hunk 1]
```diff
@@ -1101,7 +1101,7 @@ end
 
 function edit_transpose_chars(buf::IOBuffer)
     # Moving left but not transpoing anything is intentional, and matches Emacs's behavior
-    eof(buf) && char_move_left(buf)
+    eof(buf) && position(buf) !== 0 && char_move_left(buf)
     position(buf) == 0 && return false
```
Comment (Keno) [inline stdlib/REPL/src/LineEdit.jl:1105]: Just swap this and the line above rather than duplicating the condition?

Comment (perryprog) [reply stdlib/REPL/src/LineEdit.jl:1105]: That was the original logic that led to #45417 being filed—what will happen is if the buffer's position is at 1, with a length of 1, then we'll try to read past the end of the buffer.

Since I figured that it'd be best to be as close to Emacs as possible, I went with just flipping those two lines (hence the comment).

In this PR, I'm not sure there's a good way to get around the duplication of the `position(buf)` stuff unless I'm missing something obvious (which isn't unlikely)—we ultimately need to check it twice, first time to make sure we can move left, and then again to make sure we aren't at the start of the buffer. One other idea could be something like this though, but I'm not sure which I prefer (probably this version, but I'm curious what you think):
```julia
function edit_transpose_chars(buf::IOBuffer)
    content(buf) == "" && return false

    # Moving left but not transpoing anything is intentional, and matches Emacs's behavior
    eof(buf) && char_move_left(buf)
    position(buf) == 0 && return false 
    # ...
```

Comment (Keno) [reply stdlib/REPL/src/LineEdit.jl:1105]: Ah, I see `char_move_left` might update the buf position. Alright, seems reasonable I suppose

**Review by Keno — APPROVED** [review]
