### PR TITLE
Ensure sizeof returns correctly for isbits Union arrays. Fixes #23321

### LINKED ISSUE #23321: `sizeof` returns erroneous results for Union arrays
```
julia> v = Union{Int,Void}[rand(Bool) ? k : nothing for k = 1:10]
10-element Array{Union{Void, Int64},1}:
   nothing
  2
  3
   nothing
   nothing
   nothing
   nothing
  8
  9
 10

julia> sizeof(v)
1762099360
```

Based on multiple Julia sessions, the number appears to be some random integer multiplied by the length of the array. A fresh Julia session is more likely to result in 0 so it seems like it's probably accessing the wrong memory somewhere.

### PR DESCRIPTION
**Pull request by quinnj**
The only other question I have is whether we should also define `sizeof(Union{Void, Int8})`, i.e. should sizeof return for isbits Unions? I feel like we should, mainly because it _does_ actually have a definitize size now in structs & array elements.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
> should sizeof return for isbits Unions

:+1: Yes I agree it should.

File: src/builtins.c [hunk 1]
```diff
@@ -270,8 +270,15 @@ JL_CALLABLE(jl_f_sizeof)
...
-        return jl_box_long(jl_array_len(x) * ((jl_array_t*)x)->elsize);
+    if (jl_is_array(x)) {
+        jl_value_t *ety = jl_tparam0(jl_typeof(x));
+        size_t elsize = 0, al = 0;
+        int isboxed = !jl_islayout_inline(ety, &elsize, &al);
+        if (isboxed)
+            elsize = sizeof(void*);
+        size_t len = jl_array_len(x);
+        return jl_box_long((!isboxed && jl_is_uniontype(ety)) ? len * elsize + len : len * elsize);
+    }
```
Comment (JeffBezanson) [inline src/builtins.c]: This logic should already be captured by `((jl_array_t*)x)->elsize`. In fact, I believe it is.

Comment (JeffBezanson) [inline src/builtins.c]: Ah, except for the `+ len` part. I'm not totally sure that should be reported as part of the array size; kind of a tough call.

File: src/codegen.cpp [hunk 2]
```diff
@@ -2718,18 +2718,24 @@ static bool emit_builtin_call(jl_codectx_t &ctx, jl_cgval_t *ret, jl_value_t *f,
...
+            size_t elsz = 0, al = 0;
+            bool isboxed = !jl_islayout_inline(ety, &elsz, &al);
             if (!jl_has_free_typevars(ety)) {
-                if (!jl_array_store_unboxed(ety)) {
+                if (isboxed) {
                     elsize = ConstantInt::get(T_size, sizeof(void*));
                 }
                 else {
-                    elsize = ConstantInt::get(T_size, jl_datatype_size(ety));
+                    elsize = ConstantInt::get(T_size, elsz);
```
Comment (JeffBezanson) [inline src/codegen.cpp]: We should have a more convenient `jl_type_size` function for just getting the size.

File: src/builtins.c (hunk 1 above)
Comment (quinnj) [inline src/builtins.c]: You're right, we can just use `->elsize`. I updated the PR to *not* include the `+ len` as part of the size. I think it will keep this more on the "optimization" side of things as opposed to necessarily committing to the layout. I also updated to give a size for isbits Union types.

File: src/codegen.cpp (hunk 2 above)
Comment (quinnj) [inline src/codegen.cpp]: In this case, we need the size and whether it's boxed anyway.

**Comment by quinnj** [comment]
I'm guessing this is an unrelated libuv travis failure
```
	From worker 6:	Assertion failed: (args[0]), function jl_uv_call_close_callback, file /Users/travis/build/JuliaLang/julia/src/jl_uv.c, line 73.
	From worker 6:	
	From worker 6:	signal (6): Abort trap: 6
	From worker 6:	while loading no file, in expression starting on line 0
	From worker 6:	__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
	From worker 6:	Allocations: 224681289 (Pool: 224650756; Big: 30533); GC: 594
```

**Comment by fredrikekre** [comment]
Looks like #23215

**Comment by quinnj** [comment]
Do you want to take one more look @JeffBezanson?
