### PR TITLE
reorganize some code in dump.c

### LINKED ISSUE #16883: packages with overly complicated recursively defined types aren't precompilable
edit: jwn DataFrames is unconnected to this bug. CategoricalArrays just doesn't work with precompilation ~~(for currently unknown reasons)~~ due to the complexity of the type definition recursion exceeding the current capabilities of the incremental deserializer

original text below:

----

I get this segfault reliably when I add `CategoricalArrays` to the `REQUIRES` file of `DataFrames`. I'm using DataFrames from latest master (https://github.com/JuliaStats/DataFrames.jl/commit/3400fbc81cc9d7409e288ff1319305d67f3ffec2) and CategoricalArrays from latest master too (https://github.com/nalimilan/CategoricalArrays.jl/commit/b2476fe5fff481b24c618b55c58af40d55d475ac).

```julia
julia> using DataFrames
INFO: Precompiling module DataFrames...

signal (11): Erreur de segmentation
while loading /home/milan/.julia/DataFrames/src/DataFrames.jl, in expression starting on line 16
push_root at /home/milan/Dev/julia/src/gc.c:1245
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
push_root at /home/milan/Dev/julia/src/gc.c:1335
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
push_root at /home/milan/Dev/julia/src/gc.c:1335
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
push_root at /home/milan/Dev/julia/src/gc.c:1335
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
push_root at /home/milan/Dev/julia/src/gc.c:1335
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
push_root at /home/milan/Dev/julia/src/gc.c:1335
gc_push_root at /home/milan/Dev/julia/src/gc.c:1104
_jl_gc_collect at /home/milan/Dev/julia/src/gc.c:1607
__pool_alloc at /home/milan/Dev/julia/src/gc.c:704
newstruct at /home/milan/Dev/julia/src/julia_internal.h:67
jl_f_tuple at /home/milan/Dev/julia/src/builtins.c:653
next at ./array.jl:302
unknown function (ip: 0x7fda6d75a123)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
_require_from_serialized at ./loading.jl:182
unknown function (ip: 0x7fda6d86b68e)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
_require_from_serialized at ./loading.jl:202
require at ./loading.jl:332
unknown function (ip: 0x7fda6d86d0cb)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
jl_apply at /home/milan/Dev/julia/src/julia.h:1381
eval_import_path at /home/milan/Dev/julia/src/toplevel.c:411
jl_toplevel_eval_flex at /home/milan/Dev/julia/src/toplevel.c:434
jl_toplevel_eval_flex at /home/milan/Dev/julia/src/toplevel.c:446
jl_parse_eval_all at /home/milan/Dev/julia/src/ast.c:699
jl_load at /home/milan/Dev/julia/src/toplevel.c:579
include_from_node1 at ./loading.jl:426
unknown function (ip: 0x7fda6d81c80c)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
do_call at /home/milan/Dev/julia/src/interpreter.c:65
eval at /home/milan/Dev/julia/src/interpreter.c:173
jl_toplevel_eval_flex at /home/milan/Dev/julia/src/toplevel.c:539
jl_toplevel_eval_in_warn at /home/milan/Dev/julia/src/builtins.c:571
macro expansion; at ./none:2
unknown function (ip: 0x7fda79fb921f)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
jl_toplevel_eval_in_warn at /home/milan/Dev/julia/src/builtins.c:571
eval at ./boot.jl:225
unknown function (ip: 0x7fda6d7fff20)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
process_options at ./client.jl:243
_start at ./client.jl:322
unknown function (ip: 0x7fda6d855ce4)
jl_call_method_internal at /home/milan/Dev/julia/src/julia_internal.h:93
jl_apply at /home/milan/Dev/julia/ui/../src/julia.h:1381
main at /home/milan/Dev/julia/ui/repl.c:678
unknown function (ip: 0x7fda78f6957f)
unknown function (ip: 0x401718)
Allocations: 2043527 (Pool: 2042339; Big: 1188); GC: 2

```

### PR DESCRIPTION
**Pull request by vtjnash**
fix #16883

improve performance of packages with many ambiguous methods (such as CategoricalArrays)

correctly classify primary datatypes during MODE_MODULE_POSTWORK

### CODE REVIEW

File: src/dump.c [hunk 1]
```diff
@@ -1246,12 +1236,32 @@ static jl_value_t *jl_deserialize_datatype(ios_t *s, int pos, jl_value_t **loc)
...
+        assert(pos > 0);
+        assert(mode != MODE_MODULE_POSTWORK);
+        arraylist_push(&flagref_list, loc);
+        arraylist_push(&flagref_list, (void*)(uintptr_t)pos);
+        dt->uid = -1; // mark that this type needs a new uid
+    }
+
+    int has_instance = (flags >> 3) & 1;
+    if (has_instance) {
+        assert(mode != MODE_MODULE_POSTWORK); // there shouldn't be an instance on a type with uid = 0
```
Comment (tkelman) [inline src/dump.c]: of a type

Comment (vtjnash) [inline src/dump.c]: also true, but this is asserting specifically that `dt->instance` isn't being assigned to
