### PR TITLE
Accept a function to strip like rstrip and lstrip

### LINKED ISSUE #31195: `strip` does not take predicate functions.
From `strip`'s docstring (emphasis mine):
> The optional chars argument specifies which characters to remove: it can be a single character, vector or set of characters, **or a predicate function**.

However:
```
julia> a = "hello!"
"hello!"

julia> strip(a, ispunct)
ERROR: MethodError: no method matching rstrip(::String, ::typeof(ispunct))
```
(note the error is in `rstrip`, not `strip`.)

```
julia> methods(strip)
# 2 methods for generic function "strip":
[1] strip(s::AbstractString) in Base at strings/util.jl:214
[2] strip(s::AbstractString, chars) in Base at strings/util.jl:215

julia> methods(rstrip)
# 3 methods for generic function "rstrip":
[1] rstrip(s::AbstractString) in Base at strings/util.jl:194
[2] rstrip(f, s::AbstractString) in Base at strings/util.jl:189
[3] rstrip(s::AbstractString, chars::Union{AbstractChar, Tuple{Vararg{AbstractChar,N} where N}, Set{#s55} where #s55<:AbstractChar, AbstractArray{#s56,1} where #s56<:AbstractChar}) in Base at strings/util.jl:195
```

```
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.2.0)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

Edited to add: even if you put the predicate function first, `strip` doesn't work.

### PR DESCRIPTION
**Pull request by ararslan**
`strip` is documented to accept a function argument but it does not. `rstrip` and `lstrip` do, so it seems this was simply an oversight.

Fixes #31195.

NOTE: #31213 should be merged first!

### CODE REVIEW

**Comment by nalimilan** [comment]
I'm not sure why but @simonbyrne didn't add that method in https://github.com/JuliaLang/julia/pull/27309#issuecomment-393286974.

**Comment by simonbyrne** [comment]
I think it was an oversight as that PR got modified.

**Review by simonbyrne — APPROVED** [review]

File: test/strings/util.jl [hunk 1]
```diff
@@ -53,6 +53,7 @@ end
     @test strip(" \u2009 hi \u2009 ") == "hi"
     @test strip("foobarfoo", ['f','o']) == "bar"
     @test strip("foobarfoo", ('f','o')) == "bar"
+    @test strip(ispunct, "¡Hola!") == "Hola"
```
Comment (StefanKarpinski) [inline test/strings/util.jl]: ❤️

**Review by StefanKarpinski — APPROVED** [review]

**Comment by sbromberger** [comment]
Thank you!!
