### PR TITLE
Fix duplicate error when using generator in Dict

### LINKED ISSUE #33147: Dict construction calls generator side effects twice on failure
Greetings...

This is not a major issue, but potentially reflects some underlying bug and is certainly confusing: when creating a `Dict` with a generator expression and an exception occurs, for some reason  the generator restarts until it hits the exception a second time.  Once it hits the exception a second time, it stops, thankfully.  For example (using `@show` to track execution) `Dict(x => sqrt(@show x) for x=[1,2,3,4,-5,6])` does everything (but the 6) twice.  I would have expected it to immediately error out, but...

```julia
julia> Dict(x => sqrt(@show x) for x=[1,2,3,4,-5,6])
x = 1
x = 2
x = 3
x = 4
x = -5
x = 1
x = 2
x = 3
x = 4
x = -5
ERROR: DomainError with -5.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(::Symbol, ::Float64) at ./math.jl:31
 [2] sqrt at ./math.jl:493 [inlined]
 [3] sqrt at ./math.jl:519 [inlined]
 [4] #21 at ./show.jl:576 [inlined]
 [5] iterate at ./generator.jl:47 [inlined]
 [6] _all(::getfield(Base, Symbol("##238#240")), ::Base.Generator{Array{Int64,1},getfield(Main, Symbol("##21#22"))}, ::Colon) at ./reduce.jl:744
 [7] all at ./reduce.jl:732 [inlined]
 [8] Dict(::Base.Generator{Array{Int64,1},getfield(Main, Symbol("##21#22"))}) at ./dict.jl:130
 [9] top-level scope at REPL[7]:1
caused by [exception 1]
DomainError with -5.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(::Symbol, ::Float64) at ./math.jl:31
 [2] sqrt at ./math.jl:493 [inlined]
 [3] sqrt at ./math.jl:519 [inlined]
 [4] #21 at ./show.jl:576 [inlined]
 [5] iterate at ./generator.jl:47 [inlined]
 [6] Dict{Int64,Float64}(::Base.Generator{Array{Int64,1},getfield(Main, Symbol("##21#22"))}) at ./dict.jl:103
 [7] dict_with_eltype at ./abstractdict.jl:538 [inlined]
 [8] dict_with_eltype at ./abstractdict.jl:545 [inlined]
 [9] Dict(::Base.Generator{Array{Int64,1},getfield(Main, Symbol("##21#22"))}) at ./dict.jl:128
 [10] top-level scope at REPL[7]:1
```

In my case an exception occurred near the end of a calculation that should have taken 30 minutes.  I started getting suspicious when it was still running after 40 minutes, even more so when I noticed it was re-doing parts of the job that should have been finished earlier.  Granted I of course should have written code that didn't crash, but still. :)

Many thanks for a great programming environment...

Version info, if that helps.  (The same issue also occurs on 1.3.0-rc1.0)
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes: #33147
Replaces/Closes: #40445

The difference here, compared to past implementations, is that we use the zero-cost `isiterable` check on every intermediate step, instead of wrapping the call in a try/catch and then trying to re-approximate the `isiterable` afterwards. Some samples:

```julia
julia> Dict(i for i in 1:3)                                                        
ERROR: ArgumentError: AbstractDict(kv): kv needs to be an iterator of 2-tuples or pairs                                                                               
Stacktrace:                                                                                                                                                           
 [1] _throw_dict_kv_error()                                                        
   @ Base ./dict.jl:118                                                                                                                                               
 [2] grow_to!                                                                      
   @ ./dict.jl:132 [inlined]                                                       
 [3] dict_with_eltype                                                                                                                                                 
   @ ./abstractdict.jl:592 [inlined]                                                                                                                                  
 [4] Dict(kv::Base.Generator{UnitRange{Int64}, typeof(identity)})                                                                                                     
   @ Base ./dict.jl:120                                                            
 [5] top-level scope                                                                                                                                                  
   @ REPL[1]:1                                                                     
                                                                                                                                                                      
julia> Dict(i => error("$i") for i in 1:3)                                         
ERROR: 1                                                                                                                                                              
Stacktrace:                                                                                                                                                           
 [1] error(s::String)                                                                                                                                                 
   @ Base ./error.jl:35                                                                                                                                               
 [2] (::var"#3#4")(i::Int64)                                                       
   @ Main ./none:0                                                                 
 [3] iterate                                                                                                                                                          
   @ ./generator.jl:48 [inlined]                                                   
 [4] grow_to!                                                                      
   @ ./dict.jl:124 [inlined]                                                       
 [5] dict_with_eltype                                                              
   @ ./abstractdict.jl:592 [inlined]                                               
 [6] Dict(kv::Base.Generator{UnitRange{Int64}, var"#3#4"})                                                                                                            
   @ Base ./dict.jl:120                                                                                                                                               
 [7] top-level scope                                                               
   @ REPL[2]:1                                                                                                                                                        
```

The other unrelated change here is that `dest = empty(dest, typeof(k), typeof(v))` is made conditional, so we do not unconditionally construct an empty Dict in order to discard it and allocate an exact duplicate of it, but only do so if inference wasn't precise originally.

### CODE REVIEW

File: base/abstractdict.jl [hunk 1]
```diff
@@ -579,6 +579,55 @@ _tablesz(x::T) where T <: Integer = x < 16 ? T(16) : one(T)<<(top_set_bit(x-one(
 
 TP{K,V} = Union{Type{Tuple{K,V}},Type{Pair{K,V}}}
 
+# validate the contents of this iterator by testing the iteration protocol (isiterable) on it
+_throw_dict_kv_error() = throw(ArgumentError("AbstractDict(kv): kv needs to be an iterator of 2-tuples or pairs"))
```
Comment (fingolfin) [inline base/abstractdict.jl:583]: The comment looks as if it is attached to `_throw_dict_kv_error()` but it seems to talk about something else?

Comment (vtjnash) [reply base/abstractdict.jl:583]: Good point. This is the error thrown when the check described in that comment fails. The comment and function used to be inline in the function, and then I moved both here to avoid repeating them every time it called the function

Comment (vtjnash) [reply base/abstractdict.jl:583]:
```suggestion
# This error is throw if `grow_to!` cannot validate the contents of the iterator argument, which it does by testing the iteration protocol (isiterable) on it each time it is about to start iteration on it
_throw_dict_kv_error() = throw(ArgumentError("AbstractDict(kv): kv needs to be an iterator of 2-tuples or pairs"))
```
