### PR TITLE
fix #42078, improve the idempotency of callsite inlining

### LINKED ISSUE #42078: callsite inlining interacts very badly with source deletion
There are several points in our codegen pipeline that discard the inferred source code that is not "inlineable",
and it easily breaks the idempotency of callsite inlining, e.g.:
```julia
julia> using LinearAlgebra

julia> const CC = Core.Compiler;

julia> function getsource(mi)
           codeinf = CC.get(CC.code_cache(CC.NativeInterpreter()), mi, nothing)
           return isnothing(codeinf) ? nothing : 
                  isdefined(codeinf, :inferrred) ? nothing :
                  typeof(codeinf.inferred)
       end
getsource (generic function with 1 method)

julia> code_typed1(args...; kwargs...) = first(only(code_typed(args...; kwargs...))).code
code_typed1 (generic function with 1 method)

julia> mi = only(methods(factorize, (Matrix{Float64},))).specializations[1]
MethodInstance for LinearAlgebra.factorize(::Matrix{Float64})

julia> getsource(mi)

julia> code_typed1() do
           A = Array(Bidiagonal(fill(1.0, (5, 5)), :U))
           @inline factorize(A)
       end |> length
431 # succeed in inlining

julia> getsource(mi)
Vector{UInt8} (alias for Array{UInt8, 1})

julia> let # run the codegen pipeline
           A = Array(Bidiagonal(fill(1.0, (5, 5)), :U))
           factorize(A)
       end;

julia> getsource(mi)
Nothing # the inferred source has been discarded

julia> code_typed1() do
           A = Array(Bidiagonal(fill(1.0, (5, 5)), :U))
           @inline factorize(A)
       end |> length
37 # inlining failed, becuase there is no inferred source available

julia> getsource(mi)
Nothing
```

We can keep the idempotency If we turn off following lines:
- https://github.com/JuliaLang/julia/blob/2a0ab37ea475ed49150ecff1358d68567945f37a/src/codegen.cpp#L7743-L7743
- https://github.com/JuliaLang/julia/blob/2a0ab37ea475ed49150ecff1358d68567945f37a/base/compiler/types.jl#L216-L216

but of course this leads to the fat sysimages...:
> master
```
❯ ls -la ./usr/lib/julia/
total 434420
drwxr-xr-x 2 aviatesk aviatesk      4096 Sep  1 03:44 .
drwxr-xr-x 5 aviatesk aviatesk     16384 Sep  1 01:23 ..
-rw-r--r-- 1 aviatesk aviatesk  14742218 Sep  1 03:38 corecompiler.ji
-rw-r--r-- 1 aviatesk aviatesk  92237537 Sep  1 03:40 sys.ji
-rw-r--r-- 1 aviatesk aviatesk 177971028 Sep  1 03:44 sys-o.a
-rwxr-xr-x 1 aviatesk aviatesk 159864072 Sep  1 03:44 sys.so
```

> with source deletion turned off
```
 ls -la ./usr/lib/julia/
total 457132
drwxr-xr-x 2 aviatesk aviatesk      4096 Sep  1 03:49 .
drwxr-xr-x 5 aviatesk aviatesk     16384 Sep  1 03:39 ..
-rw-r--r-- 1 aviatesk aviatesk  16111154 Sep  1 03:43 corecompiler.ji
-rw-r--r-- 1 aviatesk aviatesk  95654621 Sep  1 03:45 sys.ji
-rw-r--r-- 1 aviatesk aviatesk 187393556 Sep  1 03:49 sys-o.a
-rwxr-xr-x 1 aviatesk aviatesk 168911408 Sep  1 03:49 sys.so
```

So that actually means, we really want "re-inference" stuff here after all ?
https://github.com/JuliaLang/julia/blob/2a0ab37ea475ed49150ecff1358d68567945f37a/base/compiler/optimize.jl#L38-L44

### PR DESCRIPTION
**Pull request by aviatesk**
After #41328, inference can observe statement flags and try to re-infer
a discarded source if it's going to be inlined.
The re-inferred source will only be cached into the inference-local
cache, and won't be cached globally.

### CODE REVIEW

File: base/compiler/typeinfer.jl [hunk 1]
```diff
@@ -834,14 +842,10 @@ function typeinf_code(interp::AbstractInterpreter, method::Method, @nospecialize
...
+    frame = InferenceState(result, :no, interp)
     frame === nothing && return (nothing, Any)
-    if typeinf(interp, frame) && run_optimizer
-        opt_params = OptimizationParams(interp)
-        result.src = src = OptimizationState(frame, opt_params, interp)
-        optimize(interp, src, opt_params, ignorelimited(result.result))
-        frame.src = finish!(interp, result)
-    end
+    run_optimizer && (frame.cached = true)
+    typeinf(interp, frame)
```
Comment (vtjnash) [inline base/compiler/typeinfer.jl:848]: The previous form here was intended to be an example of running an external optimization pipeline. I think cached=false also has some follow-on effects of deciding how to resolve (and optimize) cycles?

File: test/compiler/inline.jl [hunk 2]
```diff
@@ -614,3 +614,40 @@ end
...
+    mi = let
+        specs = collect(only(methods(f42078)).specializations)
+        specs[findfirst(!isnothing, specs)]::Core.MethodInstance
+    end
+
+    let # codegen will discard the source because it's not supposed to be inlined in general context
+        a = 42
+        f42078(a)
+    end
+    @assert getsource(mi) === nothing
```
Comment (vtjnash) [inline test/compiler/inline.jl:644]: might be better to set this field explicitly to `nothing`, since `julia-debug` or `-g2` won't discard the source

**Review by vtjnash — COMMENTED** [review]
Changing this to a symbol seems like a great idea

File: base/compiler/typeinfer.jl (hunk 1 above)
Comment (aviatesk) [reply base/compiler/typeinfer.jl:847]: Yeah, that's why I made this change. Currently the optimization behavior really changes depending on the cache configuration, and it causes `typeinf_code` to behave slightly different from actual execution, which is very confusing.

For example, https://github.com/JuliaLang/julia/blob/5629856e80c1f50201ca5c775f518593e2b1ad89/test/compiler/inline.jl#L176 was marked as `@test_broken` for long, but I found it has been functional actually
(the problem was that the previous `cached = false` hinders `type_annotate!` to do additional clean up work).

And this change is necessary for the test case added in this PR, because callsite inlining depends on `typeinf_edge`, which actually changes its behavior depending on caller's `cache` configuration.

External consumer can still plugin their own optimization pipeline by overloading `OptimizationState`, so I think this change is okay.

**Comment by aviatesk** [comment]
Test failures on linux 32 seem unrelated to this PR.
