### PR TITLE
fix promote_op function

### LINKED ISSUE #28370: `promote_op` doesn't play well with `Union{Missing, T}`
Sometimes I use `promote_op` to predict the element type of containers for non-trivial operations where the element type might change.

However, while working out how my packages might work with `missing` in v0.7 I came across this stumbling block:

```
julia> Base.promote_op(+, Int, Union{Float64, Missing})
Any
```

(I do realize there is a momentum to rely less on inference and more on "the type of actual elements at run-time" (at least in `Base`)... but sometimes the `promote_op` pattern is the quickest path to victory and I don't see why it shouldn't work as well as possible).

### PR DESCRIPTION
**Pull request by vtjnash**
This function had some weird and broken extraneous code,
using Core.Inference directly is not recommended,
but where we are going to do it anyways, we should at least do it correctly.

The `cumsum` code had a test to assert that `Real + Real` was convertable to `Real`.
This was hacked into the code poorly. It is now hacked in directly.
We can separately debate if this is a good idea,
I am simply preserving the existing behavior of the code
but implementing it correctly (by changing the behavior of the actual function,
instead of by convincing inference to return the incorrect answer).

close #28370 -- not really fixable, but just don't expect to get good results from inference and you should be all set.

### CODE REVIEW

File: base/complex.jl [hunk 1]
```diff
@@ -991,7 +991,3 @@ function complex(A::AbstractArray{T}) where T
     end
     convert(AbstractArray{typeof(complex(zero(T)))}, A)
 end
-
-## promotion to complex ##
-
-_default_type(T::Type{Complex}) = Complex{Int}
```
Comment (JeffBezanson) [inline base/complex.jl]: :100:

File: base/promotion.jl [hunk 2]
```diff
@@ -364,15 +364,10 @@ max(x::Real, y::Real) = max(promote(x,y)...)
...
 minmax(x::Real, y::Real) = minmax(promote(x, y)...)
 
-# "Promotion" that takes a function into account and tries to preserve
-# non-concrete types. These are meant to be used mainly by elementwise
-# operations, so it is advised against overriding them
-_default_type(T::Type) = T
-
 if isdefined(Core, :Compiler)
-    const _return_type = Core.Compiler.return_type
+    const _unsafe_return_type = Core.Compiler.return_type
```
Comment (JeffBezanson) [inline base/promotion.jl]: Technically we're allowed to rename this, but I believe several packages use it so we should continue to support the old name.

**Comment by JeffBezanson** [comment]
> The `cumsum` code had a test to assert that `Real + Real` was convertable to `Real`.

Out of curiosity, where is this code?

**Comment by vtjnash** [comment]
> Out of curiosity, where is this code?

I'm referring specifically to the addition of this method:
`add_sum(x::Real, y::Real)::Real = x + y`

Previously, this result was achieved by defining that the result eltype was the typejoin of the input types with the result of calling `+` on Int (`typejoin(Real, Real, _return_type(+, (Int, Int))`).
```julia
    R = promote_op(add_sum, T, T)
    out = similar(A, R)
    cumsum!(out, A, dims=dims)
    return out
```

Since there's a `cumsum` test for this, presumably it's intentional. (But that could also be a future PR to change.) I guess the assertion here is intended to imply that `+` must form a ring? But in that case, it seems that the `promote_op` call would be unnecessary altogether.
