### PR TITLE
fix #36031: Printf bug for BigInt

### LINKED ISSUE #36031: Printf bug for BigInt
The following fails on master, as well as 1.4:
```
julia> using Printf

julia> @printf "%.5e" big(10)
ERROR: MethodError: no method matching decode_dec(::BigInt)
Closest candidates are:
  decode_dec(::BigInt, ::Any) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:932
  decode_dec(::Integer, ::Any) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:892
  decode_dec(::Real, ::Any) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:855
  ...
Stacktrace:
 [1] ini_dec(::BigInt, ::Int64, ::Array{UInt8,1}) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:1062
 [2] ini_dec(::Base.TTY, ::BigInt, ::Int64, ::String, ::Int64, ::Int64, ::Char, ::Array{UInt8,1}) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:845
 [3] top-level scope at REPL[6]:1
```
It seems like `decode_dec(::BigInt)` calls a method that does not exist.

### PR DESCRIPTION
**Pull request by simeonschaub**
These were omitted during testing and weren't valid anymore. Should probably be backported as this is a bugfix.
close #36031

### CODE REVIEW

File: stdlib/Printf/src/Printf.jl [hunk 1]
```diff
@@ -942,10 +942,12 @@ function decode_0ct(x::BigInt, digits)
     pt = Base.ndigits0z(x, 8) + 1
     length(digits) < pt+1 && resize!(digits, pt+1)
     neg && (x.size = -x.size)
-    p = convert(Ptr{UInt8}, digits) + 1
-    GMP.MPZ.get_str!(p, 8, x)
+    GC.@preserve digits begin
+        p = convert(Ptr{UInt8}, pointer(digits)) + 1
```
Comment (simonbyrne) [inline stdlib/Printf/src/Printf.jl:946]:
```suggestion
        p = pointer(digits,2)
```

File: stdlib/Printf/src/Printf.jl [hunk 2]
```diff
@@ -1059,13 +1061,16 @@ function ini_dec(x::BigInt, n::Int, digits)
     end
     d = Base.ndigits0z(x)
     if d <= n
-        info = decode_dec(x)
+        info = decode_dec(x, digits)
         d == n && return info
```
Comment (simonbyrne) [inline stdlib/Printf/src/Printf.jl:1065]:
```suggestion
probably a good idea to use the same convention as elsewhere
```suggestion
        len,pt,neg = decode_dec(x, digits)
        d == n && return (len,pt,neg)
```

File: stdlib/Printf/src/Printf.jl [hunk 3]
```diff
@@ -1059,13 +1061,16 @@ function ini_dec(x::BigInt, n::Int, digits)
...
-        p = convert(Ptr{Cvoid}, digits) + info[2]
-        ccall(:memset, Ptr{Cvoid}, (Ptr{Cvoid}, Cint, Csize_t), p, '0', n - info[2])
+
+        GC.@preserve digits begin
+            p = convert(Ptr{Cvoid}, pointer(digits)) + info[2]
+            ccall(:memset, Ptr{Cvoid}, (Ptr{Cvoid}, Cint, Csize_t), p, '0', n - info[2])
```
Comment (simonbyrne) [inline stdlib/Printf/src/Printf.jl:1069]:
```suggestion
            ccall(:memset, Ptr{Cvoid}, (Ptr{Cvoid}, Cint, Csize_t), pointer(digits, pt+1), '0', n - pt)
```

File: stdlib/Printf/src/Printf.jl [hunk 4]
```diff
@@ -1059,13 +1061,16 @@ function ini_dec(x::BigInt, n::Int, digits)
...
+        end
         return info
```
Comment (simonbyrne) [inline stdlib/Printf/src/Printf.jl:1071]:
```suggestion
        return (len,pt,neg)
```

File: stdlib/Printf/src/Printf.jl [hunk 5]
```diff
@@ -1059,13 +1061,16 @@ function ini_dec(x::BigInt, n::Int, digits)
...
     end
-    return (n, d, decode_dec(round(BigInt,x/big(10)^(d-n)))[3])
+    return (n, d, decode_dec(round(BigInt,x/big(10)^(d-n)), digits)[3])
```
Comment (simonbyrne) [inline stdlib/Printf/src/Printf.jl:1073]:
```suggestion
    _, _, neg = decode_dec(round(BigInt,x/big(10)^(d-n)), digits)
    return (n, d, neg)
```

**Review by simonbyrne — COMMENTED** [review]
A few suggestions

**Comment by simonbyrne** [comment]
Thanks!
