### PR TITLE
Optimizer: Update SROA def-uses after DCE

### LINKED ISSUE #57141: v1.12 throws `UndefVarError: not defined in local scope` for variable renamed in function before being captured by a closure
~I've not yet been able to create a minimal reproduction of this that doesn't depend on a private package (sorry), but~ i can at least start a bisect to try to find the offending commit.

[Edit: better repro in message below]

In a private package, which has a function like
```julia
function assign_node_ids(node, starting_id::Int)
    ii = starting_id

    function _traverse(φ::BackIRType)
        new_φ = copy_and_assign_id(φ, ii)
        if new_φ !== φ
            ii += 1
        end
        return new_φ
    end

    _traverse(n) = n

    return (_traverse(node), ii)
end
function assign_node_ids(node)
    return assign_node_ids(node, 0)[1]
end
```
Calling the function like
```julia
node = make_node(...)
assign_node_ids(node)
```
throws
```julia
ERROR: UndefVarError: `ii` not defined in local scope
Suggestion: check for an assignment to a local variable that shadows a global of the same name.
Stacktrace:
 [1] (::RAI_BackIR.Utilities.var"#_traverse#assign_node_ids##0")(φ::RAI_BackIR.Atom)
   @ RAI_BackIR.Utilities ~/repos/raicode/packages/RAI_BackIR/src/Utilities/traversal.jl:104
 [2] assign_node_ids
   @ ~/repos/raicode/packages/RAI_BackIR/src/Utilities/traversal.jl:113 [inlined]
 [3] assign_node_ids(node::RAI_BackIR.Atom)
   @ RAI_BackIR.Utilities ~/repos/raicode/packages/RAI_BackIR/src/Utilities/traversal.jl:117
 [4] top-level scope
   @ REPL[1]:1
```

The error disappears if the function is marked `@noinline` or the variable isn't renamed in the function, i.e.
```julia
@noinline function assign_node_ids(node, starting_id::Int)
    ii = starting_id
    ...
end
```
or 
```julia
function assign_node_ids(node, ii::Int) 
    ...    
```

### PR DESCRIPTION
**Pull request by serenity4**
Fixes https://github.com/JuliaLang/julia/issues/57141.

Given the function

```julia
julia> function _f()
           ref = Ref{Any}()
           ref[] = 3
           @assert isdefined(ref, :x)
           inner = Returns(ref)
           x = inner()
           (x, ref[])
       end
_f (generic function with 1 method)

julia> f() = first(_f())
f (generic function with 1 method)
```

Here is before:
```julia
julia> @code_typed f()
CodeInfo(
1 ─ %1 = %new(Base.RefValue{Any})::Base.RefValue{Any}
└──      goto #3
2 ─      unreachable
3 ─      return %1
) => Base.RefValue{Any}
```

Here is after this PR:
```julia
julia> @code_typed f()
CodeInfo(
1 ─ %1 = %new(Base.RefValue{Any})::Base.RefValue{Any}
│          builtin Base.setfield!(%1, :x, 3)::Int64
│   %3 =   builtin Main.isdefined(%1, :x)::Bool
└──      goto #3 if not %3
2 ─      goto #4
3 ─ %6 =    invoke Base.AssertionError("isdefined(ref, :x)"::String)::AssertionError
│          builtin Base.throw(%6)::Union{}
└──      unreachable
4 ─      return %1
) => Base.RefValue{Any}
```

The elimination of `setfield!` was due to a use still being recorded for `ref[]` in the def-use data while DCE eliminated this `getindex` call (by virtue of not using the second tuple element in the result).

### CODE REVIEW

File: Compiler/src/ssair/passes.jl [hunk 1]
```diff
@@ -1511,6 +1511,10 @@ function sroa_pass!(ir::IRCode, inlining::Union{Nothing,InliningState}=nothing)
             used_ssas[x.id] -= 1
         end
         ir = complete(compact)
+        # remove any use that has been optimized away by the DCE
+        for (intermediaries, defuse) in values(defuses)
+            filter!(x -> ir[SSAValue(x.idx)][:stmt] !== nothing, defuse.uses)
+        end
```
Comment (serenity4) [inline Compiler/src/ssair/passes.jl:1517]: Since we don't use `defuses` until here, we could also defer its computation to after the DCE, which would probably be more robust. I just went with the simplest fix here.

I'm also assuming in this update that definitions (`setfield!`) won't be optimized away by DCE, if that is incorrect I can also update these.

**Comment by serenity4** [comment]
I believe the test failure to be unrelated, I could not reproduce locally

File: Compiler/test/irpasses.jl [hunk 2]
```diff
@@ -2030,3 +2030,19 @@ let code = Any[
...
+let src = code_typed1(()) do
+        f = function ()
+            ref = Ref{Any}()
+            ref[] = 0
+            @assert isdefined(ref, :x)
+            inner() = ref[] + 1
+            (inner(), ref[])
+        end
+        first(f())
+    end
```
Comment (aviatesk) [inline Compiler/test/irpasses.jl:2045]:
```suggestion
let src = code_typed1(()) do
        f = function ()
            ref = Ref{Any}()
            ref[] = 0
            @assert isdefined(ref, :x)
            inner() = ref[] + 1
            (inner(), ref[])
        end
        first(@inline f())
    end
```
Since this test case assumes `f` is inlined here. Otherwise you can just do:
```julia
let src = code_typed1() do
         ref = Ref{Any}()
         ref[] = 0
         @assert isdefined(ref, :x)
         inner() = ref[] + 1
         (inner(), ref[])
    end
```
?

File: Compiler/test/irpasses.jl [hunk 3]
```diff
@@ -2030,3 +2030,19 @@ let code = Any[
...
+    ex = src.code[2]
+    @test isexpr(ex, :call) && argextype(ex.args[1], src) === Const(setfield!)
```
Comment (aviatesk) [inline Compiler/test/irpasses.jl:2047]:
```suggestion
    @test count(iscall((src, setfield!)), src.code) == 1
```
would be a bit more robust.

File: Compiler/src/ssair/passes.jl (hunk 1 above)
Comment (aviatesk) [reply Compiler/src/ssair/passes.jl:1517]: No, `setfield!` won't be DCEed here.

**Review by aviatesk — APPROVED** [review]

File: Compiler/src/ssair/passes.jl [hunk 4]
```diff
@@ -1511,6 +1511,10 @@ function sroa_pass!(ir::IRCode, inlining::Union{Nothing,InliningState}=nothing)
             used_ssas[x.id] -= 1
         end
         ir = complete(compact)
+        # remove any use that has been optimized away by the DCE
+        for (intermediaries, defuse) in values(defuses)
+            filter!(x -> ir[SSAValue(x.idx)][:stmt] !== nothing, defuse.uses)
```
Comment (aviatesk) [inline Compiler/src/ssair/passes.jl:1516]: We should probably add `x::SSAUse` annotation here.

Comment (serenity4) [reply Compiler/src/ssair/passes.jl:1516]: I don't think this is necessary, `defuse` is already typed as `SSADefUse` in the `defuses` container and `.uses` is also typed to be `SSAUse`:
```julia
struct SSADefUse
    uses::Vector{SSAUse}
    defs::Vector{Int}
end
```

Comment (aviatesk) [reply Compiler/src/ssair/passes.jl:1516]: Yes, that’s true in general cases, but since `Compiler` code needs to be inferred even before inference is fully set up during bootstrap, there is a best practice of declaring method signatures as concretely as possible. 

More broadly, even in cases where inference doesn’t work perfectly, having concrete method signatures allows that the method can still be compiled, making this a generally useful technique. In this specific case, inference is very likely to succeed, but given that other parts of the code follow this convention, it might make sense to do so here as well.

That said, I’m not entirely sure if this best practice is still necessary in the current implementation of `Compiler.jl`. What do you think on this @vtjnash?

Comment (vtjnash) [reply Compiler/src/ssair/passes.jl:1516]: It is mainly about readability here. A lot of untyped arguments makes it really hard to understand what is supposed to happen in the code. If only one thing can happen, then it is usually better to assert that it happened, both so that if something different happens the compiler gets an error and so the reader can see what the author expected to happen.

**Comment by tpapp** [comment]
I found that this PR fixes a bug for me in 1.11.4, could it be backported to 1.11.5 (if there is one)?

See [discussion](https://discourse.julialang.org/t/how-to-isolate-report-non-deterministic-bug/127176/).
