### PR TITLE
Better error message for invalid shared library on system path

### LINKED ISSUE #15899: Error from Libdl.dlopen is misleading when library file in fact contains a linker script
From my problem trying to get the TermWin package to work on Arch Linux x86_64, Julia 0.4.5, I find that I'm getting this error when trying to dlopen `libncurses`:

```sh
$ julia -e 'Libdl.dlopen("libncurses")'
ERROR: could not load library "libncurses"
libncurses: cannot open shared object file: No such file or directory
 in dlopen at libdl.jl:36
```

On my system, the file `/usr/lib/libncurses.so` actually does exist, but instead of a binary, it contains a linker script:

```sh
$ cat /usr/lib/libncurses.so
INPUT(-lncursesw)
```

Running with `strace` confirms that Julia does find both `libncurses.so` and `libncursesw.so`:
```sh
$ strace -f julia -e 'Libdl.dlopen("libncurses")' > strace.out 2>&1
```
Please look [here](https://gist.github.com/b80dec27d59918cf5490d2766cec76cf) for the full log.

If `Libdl.dlopen` is meant to behave more or less as the system `dlopen` (which doesn't support linker scripts, see [here](https://www.sourceware.org/ml/libc-alpha/2011-07/threads.html#00139) for arguments for and against), it should produce a different error message, as this small C program demonstrates.

```c
#include <stdio.h>
#include <dlfcn.h>

#define MODULE "libncurses.so" /* NOT working */

int main(int argc, char *argv[])
{
  void *hnd;
  if ((hnd = dlopen(MODULE, RTLD_LAZY | RTLD_DEEPBIND)) != NULL) {
    printf("Successfully dlopened %s, handle: %p\n", MODULE, hnd);
    dlclose(hnd);
  } else {
    printf("Failed to dlopen %s: %s\n", MODULE, dlerror());
  }
  return 0;
}
```

Compiling it using `cc -o dlopen dlopen.c -ldl`, then running it produces:
```sh
$ ./dlopen 
Failed to dlopen libncurses.so: /usr/lib/libncurses.so: file too short
```

Replacing `libncurses.so` with `libncursesw.so`, recompiling and running again produces:
```sh
$ ./dlopen 
Successfully dlopened libncursesw.so, handle: 0x1c8b030
```

This works in Julia:
```sh
$ julia -e 'Libdl.dlopen("libncursesw")'
```

### PR DESCRIPTION
**Pull request by yuyichao**
By checking the one with only one extension name the last.

Fixes #15899 

Edit:
And I'm not sure how to test this since the error message is system-dependent and can be translated.

### CODE REVIEW

File: src/dlload.c [hunk 1]
```diff
@@ -21,18 +21,33 @@
...
+static int endswith_extension(const char *path)
+{
+    if (!path)
+        return 0;
+    size_t len = strlen(path);
+    // Skip the first one since it is empty
+    for (size_t i = 1;i < N_EXTENSIONS;i++) {
+        const char *ext = extensions[i];
+        size_t extlen = strlen(ext);
+        if (memcmp(ext, path + len - extlen, extlen) == 0) {
```
Comment (vtjnash) [inline src/dlload.c]: `if (len - extlen >= 0 && ...`

Comment (yuyichao) [inline src/dlload.c]: Done.

**Comment by vtjnash** [comment]
lgtm
