### PR TITLE
Fix length of Iterators.Stateful with underlying mutable iterator

### LINKED ISSUE #43245: Bug: Length of iterators.Stateful can be wrong
MWE:
```julia
julia> collect(Iterators.Stateful(Iterators.Stateful(1:1)))
ERROR: ArgumentError: destination has fewer elements than required
```
What happens is that the inner constructor for `Stateful` calls `iterate` on its argument, while at the same time setting `taken = 0`. I don't know why it does that.

### PR DESCRIPTION
**Pull request by jakobnissen**
Previously, Iterators.Stateful kept track of how many elements have been taken,
and reported its length as the length of the underlying iterator minus the
number of taken elements.
However, this assumes the underlying iterator is immutable. If it is mutable,
then the reported length is the same as the number of remaining elements,
meaning the wrapper Stateful should not subtract the number of taken elements.

After this PR, Stateful instead stores the length of the underlying iterator,
if that can be known, and subtracts one every time an element is taken. Hence,
the number of remaining elements is being kept track of directly.

Fixes #43245

### CODE REVIEW

File: base/iterators.jl [hunk 1]
```diff
@@ -1341,20 +1341,29 @@ mutable struct Stateful{T, VS}
     itr::T
     # A bit awkward right now, but adapted to the new iteration protocol
     nextvalstate::Union{VS, Nothing}
-    taken::Int
+    # Number of remaining elements, or nothing if not known or infinite
+    remaining::Union{Int, Nothing}
```
Comment (vtjnash) [inline base/iterators.jl:1345]:
```suggestion
    # Number of remaining elements, or nothing if not known or infinite
    remaining::N
```
(making this a new type parameter)

File: base/iterators.jl [hunk 2]
```diff
@@ -1341,20 +1341,29 @@ mutable struct Stateful{T, VS}
...
         VS = approx_iter_type(T)
-        return new{T, VS}(itr, iterate(itr)::VS, 0)
+        itl = iterlength(itr)
+        return new{T, VS}(itr, iterate(itr)::VS, itl)
     end
 end
 
+function iterlength(it)::Union{Int, Nothing}
+    itz = IteratorSize(it)
+    (itz isa HasLength || itz isa HasShape) ? Int(length(it)) : nothing
```
Comment (vtjnash) [inline base/iterators.jl:1359]:
```suggestion
    if IteratorSize(it) isa Union{HasLength,HasShape}
        return length(it)
    else
        return -1
    end
```

File: base/iterators.jl [hunk 3]
```diff
@@ -1391,7 +1400,10 @@ convert(::Type{Stateful}, itr) = Stateful(itr)
     else
         val, state = vs
         Core.setfield!(s, :nextvalstate, iterate(s.itr, state))
-        s.taken += 1
+        rem = s.remaining
+        if rem !== nothing
+            s.remaining = rem - 1
+        end
```
Comment (vtjnash) [inline base/iterators.jl:1406]:
```suggestion
        rem = s.remaining
        @assert !iszero(rem)
        s.remaining = rem - 1
```

File: base/iterators.jl [hunk 4]
```diff
@@ -1404,7 +1416,7 @@ end
 IteratorSize(::Type{Stateful{T,VS}}) where {T,VS} = IteratorSize(T) isa HasShape ? HasLength() : IteratorSize(T)
 eltype(::Type{Stateful{T, VS}} where VS) where {T} = eltype(T)
 IteratorEltype(::Type{Stateful{T,VS}}) where {T,VS} = IteratorEltype(T)
-length(s::Stateful) = length(s.itr) - s.taken
+length(s::Stateful) = s.remaining::Int # should never be called if remaining is nothing
```
Comment (vtjnash) [inline base/iterators.jl:1419]:
```suggestion
length(s::Stateful) = (len = s.len; len > 0 ? len : length(s.itr) - (one(len) - len))
```

**Review by vtjnash — COMMENTED** [review]
Thanks! I think it might remain useful to keep the prior behavior also, by using the signbit instead of a Union. Commented my suggestions on how to do that.

**Comment by vtjnash** [comment]
> * What is the advantage of having `remaining` be a type param instead of just an `Int`? Given that it will only be used to store an integer? Is it to prevent overflow for iterators who return their length as e.g. BigInt?

Mostly just to avoid any possible regression here. Though `length` is typically expected to be an `Int`, it isn't strictly required. Someone might theoretically pair it with a truncating iterator (such as via `zip`), making the length the shorter of this and the other.

> * What is the purpose of keeping the old behaviour? As far as I can tell, all it does it to defer the call to `length` when the wrapper iterator has no length from instatiation of Stateful until `length(::Stateful)` is called. It will error either way.
>   Edit: Ah, I guess it's to not require that the underlying iterator actually implements `length`, like the `CharStr` in the tests I had to modify to make it work. For backwards compatibility?

Yeah, that was my hope

File: base/iterators.jl [hunk 5]
```diff
@@ -1337,24 +1337,40 @@ julia> sum(a) # Sum the remaining elements
 7
 ```
 """
-mutable struct Stateful{T, VS}
+mutable struct Stateful{T, VS, N <: Signed}
```
Comment (vtjnash) [inline base/iterators.jl:1340]:
```suggestion
mutable struct Stateful{T, VS, N<:Integer}
```
This should not need to assume it is `signed`

Comment (jakobnissen) [reply base/iterators.jl:1340]: Ah right. If their length implementation returns an unsigned, this never underflows anyway.

**Review by vtjnash — APPROVED** [review]

**Comment by jakobnissen** [comment]
@vtjnash I think this should be good to go, and would be nice to get in v1.9 :)

**Comment by vtjnash** [comment]
Thanks for the bump

**Comment by aviatesk** [comment]
Bisected that this introduced a regression reported at https://github.com/JuliaLang/julia/issues/46719.
