### PR TITLE
fix numerous issues with WeakKeyDict

### LINKED ISSUE #26939: BigFloat stored in WeakKeyDicts cause segfaults when garbage collected
In v0.6.2

This error is similar to https://github.com/JuliaLang/julia/issues/18204#issuecomment-265679348

MWE:
```
x = WeakKeyDict()
x[big"1.0"] = 1
gc()
```

REPL:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> x = WeakKeyDict()
WeakKeyDict{Any,Any} with 0 entries

julia> x[big"1.0"] = 1
1

julia> gc()

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f33961c1a4f)
decompose at ./hashing2.jl:140
hash at ./hashing2.jl:32
hashindex at ./dict.jl:210 [inlined]
ht_keyindex at ./dict.jl:322
delete! at ./dict.jl:558 [inlined]
#333 at ./weakkeydict.jl:113
lock at ./lock.jl:101
#311 at ./weakkeydict.jl:25
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
run_finalizer at /buildworker/worker/package_linux64/build/src/gc.c:111
jl_gc_run_finalizers_in_list at /buildworker/worker/package_linux64/build/src/gc.c:200
run_finalizers at /buildworker/worker/package_linux64/build/src/gc.c:234 [inlined]
jl_gc_collect at /buildworker/worker/package_linux64/build/src/gc.c:2112
gc at ./base.jl:144
unknown function (ip: 0x7f336bfa35af)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:75
eval at /buildworker/worker/package_linux64/build/src/interpreter.c:242
jl_interpret_toplevel_expr at /buildworker/worker/package_linux64/build/src/interpreter.c:34
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:577
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7f33907cdd2f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7f339084f18f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
macro expansion at /home/uniwa/students2/students/20361362/linux/.julia/v0.6/Revise/src/Revise.jl:775 [inlined]
#17 at ./event.jl:73
unknown function (ip: 0x7f336bf9409f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 2381902 (Pool: 2380620; Big: 1282); GC: 3
Segmentation fault (core dumped)
(venv_p3) 20361362@ECM-DTC-678L:~$ 
```

### PR DESCRIPTION
**Pull request by vtjnash**
Delay cleanup of WeakKeyDict items until the next insertion. (And fix
`get!`, since previously usage of it would have added keys without
finalizers to the dict.)

The most significant change here is that I'm changing the way WeakKey works: now instead of the GC clearing the internal reference *after* the last instance of it disappears from the system (after running finalizers), I'm instead clearing it *prior to* (happens-before) scheduling any finalization. This is significant because—while this breaks the old implementation of WeakKeyDict—it is a necessary property for precise detection of whether the object is still strongly alive after recovering a reference to it out of a WeakKey object. This happens to be how other languages do it (https://docs.oracle.com/javase/8/docs/api/java/lang/ref/WeakReference.html, https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/weak-references), so I feel reassured this is the right change.

This also means we could also now drop the internal `lock` that was need to make this thread-safe (not implemented yet). Thoughts?

Fixes #26939

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I like the general idea but there are still some issues. For example I was able to look up `nothing`:
```
julia> d = WeakKeyDict{Any,Any}();

julia> d[[1]]=1
julia> d[[2]]=1
julia> d[[3]]=1
julia> d[[4]]=1
julia> d[[5]]=1

julia> GC.gc()

julia> d[nothing]
1

julia> d
WeakKeyDict{Any, Any} with 5 entries:

julia> 
```

`length` is a tough one. It should probably also call `_cleanup_locked`. Of course it's still hard to use correctly since the true length can change at any time. But we could at least have the property that the length is correct if no GC happens (haha) during the process of getting the length and then iterating.

**Comment by vtjnash** [comment]
Yeah, I'm not quite sure how to deal with that. I'm considering just defining `summary` to print "at most", so it's less odd (and define it as SizeUnknown for collect). I don't really want to make `length` O(n) or mutating, but it is non-trivial then to do better than this.

**Comment by Keno** [comment]
Overall direction looks right to me.

**Review by Keno — APPROVED** [review]

File: base/weakkeydict.jl [hunk 1]
```diff
@@ -69,56 +64,144 @@ function WeakKeyDict(kv)
...
 islocked(wkh::WeakKeyDict) = islocked(wkh.lock)
 lock(f, wkh::WeakKeyDict) = lock(f, wkh.lock)
 trylock(f, wkh::WeakKeyDict) = trylock(f, wkh.lock)
 
 function setindex!(wkh::WeakKeyDict{K}, v, key) where K
     !isa(key, K) && throw(ArgumentError("$(limitrepr(key)) is not a valid key for type $K"))
-    finalizer(wkh.finalizer, key)
+    # 'nothing' is not valid both because 'finalizer' will reject it,
+    # and because we therefore use it as a sentinel value
+    key === nothing && throw(ArgumentError("`nothing` is not a valid key for type WeakKeyDict"))
```
Comment (JeffBezanson) [inline base/weakkeydict.jl:94]:
```suggestion
    key === nothing && throw(ArgumentError("`nothing` is not a valid WeakKeyDict key"))
```
Only because the other similar messages refer to the element type instead of the collection type.

**Comment by JeffBezanson** [comment]
It still seems worthwhile to me for length to call `_cleanup_locked`.
