### PR TITLE
Fix `Base.libblas_name`/`Base.liblapack_name`

### LINKED ISSUE #981: `BandedMatrices` Nightly CI failure on Windows with 'could not load library "libblastrampoline"'
The run: https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/actions/runs/4024201852/jobs/6915956298#step:21:120141
Error message:
```julia
Test threw exception
  Expression: Matrix(A * B) ≈ Matrix(A) * Matrix(B)
  could not load library "libblastrampoline"
  The specified module could not be found. 
  Stacktrace:
    [1] gbmv!(trans::Char, m::Int64, n::Int64, kl::Int64, ku::Int64, alpha::Float64, A::Ptr{Float64}, st::Int64, x::Ptr{Float64}, incx::Int64, beta::Float64, y::Ptr{Float64}, incy::Int64)
      @ BandedMatrices D:\a\BandedMatrices.jl\BandedMatrices.jl\src\blas.jl:19
    [2] A11_Btop_Ctop_gbmv!
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\src\banded\gbmm.jl:39 [inlined]
    [3] _gbmm!(α::Float64, A_data::Matrix{Float64}, B_data::Matrix{Float64}, β::Float64, C_data::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, ::Tuple{Int64, Int64, Int64}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
      @ BandedMatrices D:\a\BandedMatrices.jl\BandedMatrices.jl\src\banded\gbmm.jl:305
    [4] gbmm!(tA::Char, tB::Char, α::Float64, A::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, B::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, β::Float64, C::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}})
      @ BandedMatrices D:\a\BandedMatrices.jl\BandedMatrices.jl\src\banded\gbmm.jl:288
    [5] _banded_muladd!
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\src\generic\matmul.jl:196 [inlined]
    [6] materialize!
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\src\generic\matmul.jl:204 [inlined]
    [7] muladd!
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\muladd.jl:70 [inlined]
    [8] copyto!
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\muladd.jl:77 [inlined]
    [9] copy(M::ArrayLayouts.MulAdd{BandedMatrices.BandedColumns{ArrayLayouts.DenseColumnMajor}, BandedMatrices.BandedColumns{ArrayLayouts.DenseColumnMajor}, ArrayLayouts.ZerosLayout, Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, Zeros{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}})
      @ ArrayLayouts C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\muladd.jl:72
   [10] copy
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:119 [inlined]
   [11] materialize
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:116 [inlined]
   [12] mul
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:117 [inlined]
   [13] *
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:204 [inlined]
   [14] macro expansion
      @ C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\stdlib\v1.10\Test\src\Test.jl:477 [inlined]
   [15] macro expansion
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\test\test_banded.jl:153 [inlined]
   [16] macro expansion
      @ C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\stdlib\v1.10\Test\src\Test.jl:1502 [inlined]
   [17] macro expansion
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\test\test_banded.jl:149 [inlined]
   [18] macro expansion
      @ C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\stdlib\v1.10\Test\src\Test.jl:1502 [inlined]
   [19] top-level scope
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\test\test_banded.jl:30
```
There are many other similar errors.

The package uses `Base.libblas_name` to get the BLAS library. Tests are passing on other configurations (nightly on linux/max os) and on all platforms for v1.8.5 and v1.6.

Version info:
```
Julia Version 1.10.0-DEV.443
Commit bd8ffef2b9 (2023-01-27 05:51 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 2 × Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 1 on 2 virtual cores
```

### LINKED ISSUE #48427: `BandedMatrices` Nightly CI failure on Windows with 'could not load library "libblastrampoline"'
The run: https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/actions/runs/4024201852/jobs/6915956298#step:21:120141
Error message:
```julia
Test threw exception
  Expression: Matrix(A * B) ≈ Matrix(A) * Matrix(B)
  could not load library "libblastrampoline"
  The specified module could not be found. 
  Stacktrace:
    [1] gbmv!(trans::Char, m::Int64, n::Int64, kl::Int64, ku::Int64, alpha::Float64, A::Ptr{Float64}, st::Int64, x::Ptr{Float64}, incx::Int64, beta::Float64, y::Ptr{Float64}, incy::Int64)
      @ BandedMatrices D:\a\BandedMatrices.jl\BandedMatrices.jl\src\blas.jl:19
    [2] A11_Btop_Ctop_gbmv!
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\src\banded\gbmm.jl:39 [inlined]
    [3] _gbmm!(α::Float64, A_data::Matrix{Float64}, B_data::Matrix{Float64}, β::Float64, C_data::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, ::Tuple{Int64, Int64, Int64}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
      @ BandedMatrices D:\a\BandedMatrices.jl\BandedMatrices.jl\src\banded\gbmm.jl:305
    [4] gbmm!(tA::Char, tB::Char, α::Float64, A::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, B::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, β::Float64, C::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}})
      @ BandedMatrices D:\a\BandedMatrices.jl\BandedMatrices.jl\src\banded\gbmm.jl:288
    [5] _banded_muladd!
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\src\generic\matmul.jl:196 [inlined]
    [6] materialize!
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\src\generic\matmul.jl:204 [inlined]
    [7] muladd!
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\muladd.jl:70 [inlined]
    [8] copyto!
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\muladd.jl:77 [inlined]
    [9] copy(M::ArrayLayouts.MulAdd{BandedMatrices.BandedColumns{ArrayLayouts.DenseColumnMajor}, BandedMatrices.BandedColumns{ArrayLayouts.DenseColumnMajor}, ArrayLayouts.ZerosLayout, Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, Zeros{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}})
      @ ArrayLayouts C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\muladd.jl:72
   [10] copy
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:119 [inlined]
   [11] materialize
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:116 [inlined]
   [12] mul
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:117 [inlined]
   [13] *
      @ C:\Users\runneradmin\.julia\packages\ArrayLayouts\4IG3b\src\mul.jl:204 [inlined]
   [14] macro expansion
      @ C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\stdlib\v1.10\Test\src\Test.jl:477 [inlined]
   [15] macro expansion
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\test\test_banded.jl:153 [inlined]
   [16] macro expansion
      @ C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\stdlib\v1.10\Test\src\Test.jl:1502 [inlined]
   [17] macro expansion
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\test\test_banded.jl:149 [inlined]
   [18] macro expansion
      @ C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\stdlib\v1.10\Test\src\Test.jl:1502 [inlined]
   [19] top-level scope
      @ D:\a\BandedMatrices.jl\BandedMatrices.jl\test\test_banded.jl:30
```
There are many other similar errors.

The package uses `Base.libblas_name` to get the BLAS library. Tests are passing on other configurations (nightly on linux/max os) and on all platforms for v1.8.5 and v1.6.

Version info:
```
Julia Version 1.10.0-DEV.443
Commit bd8ffef2b9 (2023-01-27 05:51 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 2 × Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 1 on 2 virtual cores
```

### PR DESCRIPTION
**Pull request by giordano**
On Windows they need to include the major soversion of libblastrampoline.

Fix JuliaLang/LinearAlgebra.jl#981.

### CODE REVIEW

File: base/Base.jl [hunk 1]
```diff
@@ -186,9 +186,10 @@ end
 include(strcat((length(Core.ARGS)>=2 ? Core.ARGS[2] : ""), "build_h.jl"))     # include($BUILDROOT/base/build_h.jl)
 include(strcat((length(Core.ARGS)>=2 ? Core.ARGS[2] : ""), "version_git.jl")) # include($BUILDROOT/base/version_git.jl)
 
-# These used to be in build_h.jl and are retained for backwards compatibility
-const libblas_name = "libblastrampoline"
-const liblapack_name = "libblastrampoline"
+# These used to be in build_h.jl and are retained for backwards compatibility.
+# NOTE: keep in sync with `libblastrampoline_jll.libblastrampoline`.
+const libblas_name = "libblastrampoline" * (Sys.iswindows() ? "-5" : "")
+const liblapack_name = libblas_name
```
Comment (staticfloat) [inline base/Base.jl:192]: Can we somehow mark this as deprecated and instead tell this [list of packages](https://juliahub.com/ui/Search?q=libblas_name&type=code) that they should use `libblastrampoline_jll.libblastrampoline` instead?

Comment (giordano) [reply base/Base.jl:192]: Can you deprecate a variable (that is, with a nice warning when you try to access it)?  And I'm not sure that's a future-proof option, in case we come up with yet another blas idea in the future, `Base.libblas_name` looks more agnostic.

**Comment by giordano** [comment]
I added a test for the use of `Base.libblas_name`, to avoid regressing again like in #48427.

**Comment by giordano** [comment]
Ehr, does anyone know what [would cause](https://buildkite.com/julialang/julia-master/builds/20535#0185f962-eaee-42cc-872c-5c605cf33ca6/2320-2343)
```
      From worker 12:	Exception: EXCEPTION_ACCESS_VIOLATION at 0x5fed810 -- dot_compute at C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-86e64109fb\bin\libopenblas64_.dll (unknown line)
      From worker 12:	in expression starting at C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-86e64109fb\share\julia\stdlib\v1.10\LinearAlgebra\test\blas.jl:719
      From worker 12:	dot_compute at C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-86e64109fb\bin\libopenblas64_.dll (unknown line)
      From worker 12:	ddot_k_ZEN at C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-86e64109fb\bin\libopenblas64_.dll (unknown line)
```
This is in the newly added test, it fails only on 64-bit Windows....

**Comment by giordano** [comment]
Using the 64-bit Windows build in this PR, I tried to run
```julia
using LinearAlgebra, Libdl
dot_sym = dlsym(dlopen(Base.libblas_name), "cblas_ddot" * (Sys.WORD_SIZE == 64 ? "64_" : ""))
@ccall $(dot_sym)(2::Cint, [2.0, 3.0]::Ref{Cdouble}, 1::Cint, [4.0, 5.0]::Ref{Cdouble}, 1::Cint)::Cdouble
```
under Wine and it worked fine for me, so I have no clue of what's going on here.  I'm happy to change the test to something else if someone can suggest something which doesn't crash on Windows.

**Comment by staticfloat** [comment]
The problem is that on 64-bit systems, you need to pass the integers as `Int64`, not `Cint`.  Why this works on some platforms and not others is more of an accident around calling conventions and values that just so happen to be zero, than anything else.

**Comment by giordano** [comment]
That worked, thanks!  netlib documentation isn't very helpful, I found the signature of `cblas_ddot` at https://netlib.org/lapack/explore-html/db/d91/cblas__ddot_8c_source.html, where the integer arguments have type [`CBLAS_INT`](https://netlib.org/lapack/explore-html/de/da0/cblas_8h_ac28e6243e4c6cd0b876f1c60a7c228c1.html#ac28e6243e4c6cd0b876f1c60a7c228c1) which is
```c
#define CBLAS_INT   int32_t
```
:shrug:

**Comment by staticfloat** [comment]
Right, but that’s for an LP64 build. ILP64 means defining CBLSS_INT to be int64_t.

I myself have caused such issues dozens of times in the past. It’s easy to forget. :P
