### PR TITLE
remove svec(#null) from the language

### LINKED ISSUE #46784: `Core._apply` segfaults on svec(#undef)
Is `svec(#undef)` supposed to be visible in Julia? Right now we have a case where `typeintersect` might fail to fill in type-parameters, leading to a segfault when we splat the result into an `apply_type` call:

```
julia> const RO38{B<:Val, M<:AbstractMatrix} =
           Tuple{
           <:Union{B, <:Val{<:B}},
           M,
           Union{AbstractMatrix{B}, AbstractMatrix{<:Vector{<:B}}}}
Tuple{var"#s1", M, Union{AbstractMatrix{B}, AbstractMatrix{<:Vector{<:B}}}} where {B<:Val, M<:(AbstractMatrix), var"#s1"<:(Union{B, var"#s2"} where var"#s2"<:(Val{<:B}))}

julia> typeintersect(RO38{T,S} where {T,S}, RO38)
Tuple{Union{var"#s1", var"#s11"}, 
[3247358] signal (11): Segmentation fault
in expression starting at none:0
ijl_isa at /data/vtjnash/julia/src/subtype.c:2075
sig_match_simple at /data/vtjnash/julia/src/typemap.c:239 [inlined]
...
Segmentation fault
```
with additional MWEs:
```
julia> T = ccall(:jl_new_structv, Any, (Any, Ptr{Cvoid}, UInt32), Union, [S, S], 2) where S<:AbstractMatrix;

julia> (ti, env) = ccall(:jl_type_intersection_with_env, Any, (Any, Any), T, AbstractMatrix); env
svec(#undef)

julia> identity(env...)
Segmentation fault
```

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/issues/46735#issuecomment-1245729821_

### PR DESCRIPTION
**Pull request by vtjnash**
This was not supported, and almost never used, so audit all places it could happen and avoid it at the source.

Fix #46784

### CODE REVIEW

File: base/essentials.jl [hunk 1]
```diff
@@ -690,7 +690,7 @@ end
 
 @eval getindex(v::SimpleVector, i::Int) = Core._svec_ref($(Expr(:boundscheck)), v, i)
 function length(v::SimpleVector)
-    return ccall(:jl_svec_len, Int, (Any,), v)
+    return unsafe_load(Ptr{Int}(pointer_from_objref(v)))
```
Comment (Keno) [inline base/essentials.jl:693]: Missing GC preserve?

File: test/core.jl [hunk 2]
```diff
@@ -784,7 +784,7 @@ end
 mutable struct Type11167{T,N} end
 function count11167()
     let cache = Type11167.body.body.name.cache
-        return sum(i -> isassigned(cache, i), 0:length(cache))
+        return sum(i -> cache[i] !== nothing, 1:length(cache), init=0)
```
Comment (Keno) [inline test/core.jl:787]:
```suggestion
        return count(e->e !== nothing, cache)
```
?

Comment (KristofferC) [reply test/core.jl:787]: Or maybe `count(!=(nothing), cache)` :)

File: src/subtype.c [hunk 3]
```diff
@@ -3547,17 +3547,26 @@ jl_value_t *jl_type_intersection_env_s(jl_value_t *a, jl_value_t *b, jl_svec_t *
...
         jl_svec_t *e = jl_alloc_svec(sz);
         *penv = e;
-        for(i=0; i < sz; i++)
+        for (i = 0; i < sz; i++)
             jl_svecset(e, i, env[i]);
+        jl_unionall_t *ub = (jl_unionall_t*)b;
+        for (i = 0; i < sz; i++) {
+            assert(jl_is_unionall(ub));
+            // TODO: assert(env[i] != NULL);
+            if (env[i] == NULL)
```
Comment (JeffBezanson) [inline src/subtype.c:3566]: Did you mean to put this before/during assigning to the svec?

Comment (vtjnash) [reply src/subtype.c:3566]: Uncertain, since if this ever happens, it is because intersection/subtyping made a mistake. This is just there to avoid that mistake causing Julia to crash.

File: test/core.jl [hunk 4]
```diff
@@ -784,7 +784,7 @@ end
 mutable struct Type11167{T,N} end
 function count11167()
     let cache = Type11167.body.body.name.cache
-        return sum(i -> isassigned(cache, i), 0:length(cache))
+        return count(e->e !== nothing, cache)
```
Comment (vtjnash) [inline test/core.jl:787]:
```suggestion
        return count(!isnothing, cache)
```

File: base/essentials.jl (hunk 1 above)
Comment (vtjnash) [reply base/essentials.jl:693]:
```suggestion
    return @GC.preserve v unsafe_load(Ptr{Int}(pointer_from_objref(v)))
```

File: test/core.jl (hunk 2 above)
Comment (vtjnash) [reply test/core.jl]: nothing usually should not be compared with `==`, but it turns out we may have a shorter predicate for this (`!isnothing`)

File: base/essentials.jl [hunk 5]
```diff
@@ -690,7 +690,7 @@ end
 
 @eval getindex(v::SimpleVector, i::Int) = Core._svec_ref($(Expr(:boundscheck)), v, i)
 function length(v::SimpleVector)
-    return ccall(:jl_svec_len, Int, (Any,), v)
+    return @GC.preserve v unsafe_load(Ptr{Int}(pointer_from_objref(v)))
```
Comment (vtjnash) [inline base/essentials.jl:693]:
```suggestion
    t = @_gc_preserve_begin v
    len = unsafe_load(Ptr{Int}(pointer_from_objref(v)))
    @_gc_preserve_end t
    return len
```

File: base/essentials.jl [hunk 6]
```diff
@@ -690,7 +690,10 @@ end
 
 @eval getindex(v::SimpleVector, i::Int) = Core._svec_ref($(Expr(:boundscheck)), v, i)
 function length(v::SimpleVector)
-    return ccall(:jl_svec_len, Int, (Any,), v)
+    t = @_gc_preserve_begin v
+    len = unsafe_load(Ptr{Int}(pointer_from_objref(v)))
+    @_gc_preserve_end t
```
Comment (vtjnash) [inline base/essentials.jl:695]: @keno is our inlining smart enough to insert this `_gc_preserve_end` automatically when required?
