### PR TITLE
fix #24305, stack overflow when intersecting sequence of big unions

### LINKED ISSUE #24305: Segmentation fault: 11
This simple code gives signal segv
I cannot figure out what's wrong :-(

```julia
f1(x,y,z) = x*y-z^2-1;
f2(x,y,z) = x*y*z+y^2-x^2-2;
f3(x,y,z) = exp(x)+z-exp(y)-3;

function Fun(x)
    return [ f1(x[1],x[2],x[3]); f2(x[1],x[2],x[3]); f3(x[1],x[2],x[3]) ];
end;

function Jac(x)
    return [ x[2] x[1] -2*x[3] ; x[2]*x[3]-2x[1]  x[1]*x[3]+2x[2]  x[1]*x[2] ; exp(x[1])  -exp(x[2])  1 ];
end

x = ones(3); # [1.0, 1.0, 1.0];

for it=1:5
    h = - \(Jac(x),Fun(x))
    x = x+h
end
```

The propblem is probably with for loop. One can try and do several steps without loop.
My julia is Version 0.6.0 (2017-06-19 13:05 UTC)
I tried both on Mac and Win. The same problem.

### PR DESCRIPTION
**Pull request by JeffBezanson**
There are two issues here. First, the `JL_GC_PUSH` in the loop was doing repeated allocas, leading to a stack overflow.

With that fixed, the stack overflow turns into an apparent hang due to matching a 6-element Union with 9 arguments (6^9). This was only an issue in global scope since in that case the arguments were `Any`. That can be fixed by moving the `Any` case above the Union case in intersection. Doing that broke one test, but that test was checking `B <: typeintersect(A, B)`, which is not correct in general, so changing it should be legitimate.

For reference, the culprit here is the `hvcat` method in sparsevector.jl that uses `_TypedDenseConcatGroup`. It would be nice to be able to do without those large union types. Large union types whose components have free variables will tend to hit exponential-time cases in subtyping.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Forgot to add the test case from the issue. If this passes tests, I'll add it.

**Comment by JeffBezanson** [comment]
Ok, seems this doesn't fully work. I'm not shocked.

**Comment by pabloferz** [comment]
Re. `_TypedDenseConcatGroup`. I guess a trait for the `hvcat` methods might avoid using those large unions. I can try to give it a go.

**Comment by JeffBezanson** [comment]
Ok, "fixed" by adding an iteration cutoff.

File: test/subtype.jl [hunk 1]
```diff
@@ -1229,3 +1235,22 @@ struct A23764{T, N, S} <: AbstractArray{Union{T, S}, N}; end
 struct A23764_2{T, N, S} <: AbstractArray{Union{Ref{T}, S}, N}; end
 @test Tuple{A23764_2{T, 1, Void} where T} <: Tuple{AbstractArray{T,N}} where {T,N}
 @test Tuple{A23764_2{T, 1, Void} where T} <: Tuple{AbstractArray{T,N} where {T,N}}
+
+# issue #24305
+f24305(x) = [g24305(x) g24305(x) g24305(x) g24305(x); g24305(x) g24305(x) 0 0];
+@test_throws UndefVarError f24305(1)
```
Comment (vtjnash) [inline test/subtype.jl]: Should use a specific error here (such as `UndefVarError(:f24305)`)

File: test/subtype.jl [hunk 2]
```diff
@@ -1229,3 +1235,22 @@ struct A23764{T, N, S} <: AbstractArray{Union{T, S}, N}; end
...
+
+f1_24305(x,y,z) = x*y-z^2-1
+f2_24305(x,y,z) = x*y*z+y^2-x^2-2
+f3_24305(x,y,z) = exp(x)+z-exp(y)-3
+Fun_24305(x) = [ f1_24305(x[1],x[2],x[3]); f2_24305(x[1],x[2],x[3]); f3_24305(x[1],x[2],x[3]) ]
```
Comment (vtjnash) [inline test/subtype.jl]: adding spaces to the above expressions to make them readable would be appreciated
