### PR TITLE
fix using non one-based indexing arrays in threads loops

### LINKED ISSUE #33394: Threads.@threads incorrectly iterates over IdentityUnitRange
```julia
julia> for i in Base.IdentityUnitRange(-1:1)
           println(i);
       end
-1
0
1

julia> Threads.@threads for i in Base.IdentityUnitRange(-1:1)
           println(i);
       end
1
2
3

julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```
Thanks!

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/33394

```jl
julia> Threads.@threads for i in Base.IdentityUnitRange(-1:1)
                 println(i);
             end
1
-1
0
```

Also swaps out the `unsafe_getindex` call for an `@inbounds`.

### CODE REVIEW

File: base/threadingconstructs.jl [hunk 1]
```diff
@@ -43,7 +43,7 @@ function _threadsfor(iter,lbody)
                 len, rem = 1, 0
             end
             # compute this thread's iterations
-            f = 1 + ((tid-1) * len)
+            f = firstindex(r) + ((tid-1) * len)
```
Comment (c42f) [inline base/threadingconstructs.jl]: I feel like I'm missing something and there should be an abstraction to represent this computation. It's something like:

```julia
# Construct a range which starts at 1 and yields the indices of `r` when indexed:
# Why don't we have a name for this??
inds = firstindex(r):lastindex(r)

f = inds[(tid-1) * len]
l = inds[tid*len - 1]
```

@andyferris I feel like you might have thought about this. Do you have a name for it?

**Review by c42f — APPROVED** [review]
This looks fine to me. Could possibly be considered nicer with the `inds` trick, but very optional.
