### PR TITLE
Fix MethodError printing in case of ambiguity

### LINKED ISSUE #17007: Ugly method ambiguity errors
Ambiguity errors are really hard to read and leak `svec` in 0.5. I consider this as a regression since ambiguity warnings were much cleaner on 0.4.
```julia
julia> f(x::Integer, y::Integer) = true
f (generic function with 1 method)

julia> f(x::Int, y::Any) = false
f (generic function with 2 methods)

julia> f(1, 2)
ERROR: MethodError: f(::Int64, ::Int64) is ambiguous. Candidates:
  svec(Tuple{#f,Int64,Int64},svec(),f(x::Int64, y) at REPL[2]:1)
  svec(Tuple{#f,Int64,Int64},svec(),f(x::Integer, y::Integer) at REPL[1]:1)
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

### PR DESCRIPTION
**Pull request by timholy**
Fixes #17007.

### CODE REVIEW

File: base/replutil.jl [hunk 1]
```diff
@@ -116,7 +116,7 @@ function showerror(io::IO, ex::MethodError)
     f = ex.f
     meth = methods_including_ambiguous(f, arg_types)
     if length(meth) > 1
-        return showerror_ambiguous(io, meth, f, arg_types)
+        return showerror_ambiguous(io, map(x->x[3], meth), f, arg_types)
```
Comment (timholy) [inline base/replutil.jl]: @JeffBezanson, or would you rather change this in `methods_including_ambiguous`?

Comment (JeffBezanson) [inline base/replutil.jl]: Yes, I guess it would be best for that function to return the same kind of result as `methods`.
