### PR TITLE
fix #36104, assign global name during type definitions

### LINKED ISSUE #36104: Referring to `Foo.F` inside struct `F` defined in module `Foo` now errors with UndefVar error
```jl
module Foo
    struct F
        v::Foo.F
    end
end
```

Works in 1.4, errors in 1.5 with

```
ERROR: UndefVarError: F not defined
```

From PkgEval on 1.5 (https://github.com/JuliaCI/NanosoldierReports/blob/90885ffd4005a91d0dc4150b8c1453f2f5948eb0/pkgeval/by_hash/194ddda_vs_b5f13c3/logs/Persa/1.5.0-DEV-f11a73bd9c.log).

### PR DESCRIPTION
**Pull request by JeffBezanson**
Alternative to #36111. Handling re-definitions is the tricky part. I realized one thing we did before was reset the global binding to undefined if an error happens during type definition, but that is invalid, so we don't do it anymore (with or without this PR). Hopefully that is the only remaining difference with v1.4.

This first checks if the new type object might be compatible with an existing one, and if so throws away the new one and uses the old type and parameters. Then we check that each step (supertype and field types) remains compatible as it runs.

fixes #36104

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -7221,3 +7221,17 @@ struct AVL35416{K,V}
...
 @test AVL35416(Node35416{AVL35416{Integer,AbstractString},Int,String}()) isa AVL35416{Integer,AbstractString}
+
+# issue #36104
+module M36104
+struct T36104
+    v::Vector{M36104.T36104}
+end
+end
+@test fieldtypes(M36104.T36104) == (Vector{M36104.T36104},)
+@test_throws ErrorException @eval(struct X36104; x::error(); end)
```
Comment (vtjnash) [inline test/core.jl:7232]:
```suggestion
@test_throws ErrorException("expected") @eval(struct X36104; x::error("expected"); end)
```

**Review by vtjnash — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Well, unsurprisingly, incomplete types throw a wrench into the works. We have some in the tests just to test that case; hopefully it will not really happen outside of that. I think I will return `Any` from `supertype` if the supertype is not set, and give an error from `fieldtypes`?

**Comment by vtjnash** [comment]
For soundness, the correct answer for `supertype` seems would have to be `Union{}`, not `Any`. I think #32658 was adding to the work required to handle incomplete `fieldtypes`

I don't think this PR needs to be changing our handling of `supertype`, as the current proposal (in #32658) is to not change it.

**Comment by JeffBezanson** [comment]
> I don't think this PR needs to be changing our handling of `supertype`

But then it breaks callers, like `subtypes`.

**Comment by JeffBezanson** [comment]
This should be ok now. As a bonus, also fixes #21816!
All it sacrifices is that you can't refer to the new type via its module within the supertype expression, e.g.
```
struct Foo <: AbstractVector{Mod.Foo}
```
but I expect that to be extremely rare.
