### PR TITLE
Require gnu11 on icc. Use static_assert only with c11 or on gcc 4.6+

### LINKED ISSUE #12881: c11 _Static_assert is used in c99 mode
The build fails when linking ``usr/bin/julia``
```
/scratch/julia/usr/lib/libjulia.so: undefined reference to `_Static_assert'
collect2: ld returned 1 exit status
make[1]: *** [/scratch/julia/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2
```

I am on 
```
Distributor ID:	CentOS
Release:	6.6

LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
```
with 
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               3301.000
BogoMIPS:              6584.39
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
```
```
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
ldd (GNU libc) 2.12
```

### PR DESCRIPTION
**Pull request by yuyichao**
See #12881 and https://github.com/JuliaLang/julia/commit/a96afe2f1d65a4e9d20a65d8fbab20b66069495b#commitcomment-12870463 for more detail.

`static_assert` is a [`c11`](http://en.cppreference.com/w/c/error/static_assert) / [`c++11`](http://en.cppreference.com/w/cpp/language/static_assert) feature so the easiest way to solve this is to require c11. This [should be fine](https://github.com/JuliaLang/julia/issues/12881#issuecomment-136504051) on all supported compilers but would make it impossible to compile on gcc < 4.6. It would be nice to not break those compilers until we switch to a llvm version that requires c++11.

This patch basically make sure `jl_uv.c` can be compiled no matter if it is in c11 mode (with some special code for gcc to make sure we have static assert on gcc without requiring c11). This also requires gnu11 on icc.

Fix #12881

@mschauer if you can verify that this fixes the build issue on gcc 4.4.
@kshyatt If you could verify this fixes the icc build issue as well.

### CODE REVIEW

**Comment by yuyichao** [comment]
Also cc @Keno since you added this assertion.

**Comment by mschauer** [comment]
Thanks! I check tomorrow, when I am on the same machine again.

**Comment by mschauer** [comment]
Regarding the build failure, @amitmurthy 's explanation possibly applies, https://github.com/JuliaLang/julia/pull/11503

File: src/jl_uv.c [hunk 1]
```diff
@@ -27,8 +27,23 @@
...
+#  ifdef __cplusplus
+#    if __cplusplus < 201103L
+#      define static_assert
+#    endif
+#  else
+#    define static_assert
+// Remove the following gcc special handling when we officially requires
+// gcc 4.7 (for c++11) and -std=gnu11
+#    ifdef __GNUC__
+#      if __GNUC__ >= 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
```
Comment (TomekTrzeciak) [inline src/jl_uv.c]: this condition is true on gcc44, even though __GNUC__ = 4 and __GNUC_MINOR__ = 4

Comment (ScottPJones) [inline src/jl_uv.c]: Yep, typo there, should be > 4, not >= 4

**Comment by mschauer** [comment]
Compiles and all test pass on gcc 4.4.

File: src/jl_uv.c [hunk 2]
```diff
@@ -27,8 +27,23 @@
...
-#if defined(_COMPILER_MICROSOFT_) && !defined(_Static_assert)
-#define _Static_assert static_assert
+
+#ifndef static_assert
+#  ifdef __cplusplus
+#    if __cplusplus < 201103L
+#      define static_assert
+#    endif
+#  else
+#    define static_assert
```
Comment (TomekTrzeciak) [inline src/jl_uv.c]: Shouldn't this be
```C
define static_assert(...)=
```
to effectively remove the assert? Otherwise I'm getting:
```
jl_uv.c: In function 'jl_write':
jl_uv.c:384: warning: left-hand operand of comma expression has no effect
jl_uv.c:382: warning: statement with no effect
```

Comment (yuyichao) [inline src/jl_uv.c]: I think you are right I was thinking about defining static alert as alert but removed it

**Comment by yuyichao** [comment]
Fixed ...  @Keno again since you are back.

**Comment by Keno** [comment]
LGTM.

**Comment by kshyatt** [comment]
Tested with `icc` version 15 and everything looks good.

**Comment by tkelman** [comment]
MSVC was apparently not happy with this.
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xkeycheck.h(224)
: warning C4005: 'static_assert' : macro redefinition
        jl_uv.c(34) : see previous definition of 'static_assert'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xkeycheck.h(250)
: fatal error C1189: #error :  The C++ Standard Library forbids macroizing keywo
rds. Enable warning C4005 to find the forbidden macro.
make[1]: *** [jl_uv.o] Error 2
```

Does
```diff
diff --git a/src/jl_uv.c b/src/jl_uv.c
index a89d2df..871a875 100644
--- a/src/jl_uv.c
+++ b/src/jl_uv.c
@@ -30,7 +30,7 @@

 #ifndef static_assert
 #  ifdef __cplusplus
-#    if __cplusplus < 201103L
+#    if (__cplusplus < 201103L) && !defined(_COMPILER_MICROSOFT_)
 #      define static_assert(...)
 #    endif
 #  else
```
seem reasonable?

**Comment by yuyichao** [comment]
Sure. Seems weird though that it's complaining about a c++11 keyword is redefined in non-c++11 mode...

**Comment by tkelman** [comment]
As I understand it MSVC doesn't really have standards modes. It just does whatever the version you're using happens to implement. Why people use this compiler escapes me, but there you go.

**Comment by yuyichao** [comment]
Since the `__cplusplus` part is probably only for MSVC, it the current version doesn't work for it, I guess you should just remove the definition of `static_assert` for c++ altogether

**Comment by tkelman** [comment]
I think we'll actually be able to get rid of the compiling in C++ mode if we switch to VS 2015, I just haven't tested that recently.
