### PR TITLE
check if cachefile dependencies can be fulfilled

### LINKED ISSUE #21266: Loading precompiled package fails if a former transitive dependency is not present
If a transitive dependency was present when a module was last precompiled, but gets removed due to being no longer required, the dependent module fails to load. Example:
```
~/Julia$ rm -rf jlpkgtmp && JULIA_PKGDIR=$PWD/jlpkgtmp julia-0.6/julia --depwarn=no
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.beta.11 (2017-04-03 14:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit daefda4* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.init(); Pkg.add("StatsModels")
INFO: Initializing package repository /home/tkelman/Julia/jlpkgtmp/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of CategoricalArrays from https://github.com/JuliaData/CategoricalArrays.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
INFO: Cloning cache of DataTables from https://github.com/JuliaData/DataTables.jl.git
INFO: Cloning cache of FileIO from https://github.com/JuliaIO/FileIO.jl.git
INFO: Cloning cache of GZip from https://github.com/JuliaIO/GZip.jl.git
INFO: Cloning cache of NullableArrays from https://github.com/JuliaStats/NullableArrays.jl.git
INFO: Cloning cache of Reexport from https://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SortingAlgorithms from https://github.com/JuliaCollections/SortingAlgorithms.jl.git
INFO: Cloning cache of SpecialFunctions from https://github.com/JuliaMath/SpecialFunctions.jl.git
INFO: Cloning cache of StatsBase from https://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of StatsModels from https://github.com/JuliaStats/StatsModels.jl.git
INFO: Installing CategoricalArrays v0.1.3
INFO: Installing Compat v0.21.0
INFO: Installing DataStructures v0.5.3
INFO: Installing DataTables v0.0.2
INFO: Installing FileIO v0.3.1
INFO: Installing GZip v0.3.0
INFO: Installing NullableArrays v0.1.0
INFO: Installing Reexport v0.0.3
INFO: Installing SortingAlgorithms v0.1.1
INFO: Installing SpecialFunctions v0.1.1
INFO: Installing StatsBase v0.13.1
INFO: Installing StatsModels v0.0.2
INFO: Package database updated

julia> using StatsModels
INFO: Precompiling module StatsModels.
<some unrelated method overwrite warnings>

julia> exit()
~/Julia$ JULIA_PKGDIR=$PWD/jlpkgtmp julia-0.6/julia --depwarn=no
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.beta.11 (2017-04-03 14:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit daefda4* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.pin("StatsBase", v"0.13.0") # does not depend on SpecialFunctions
INFO: Creating StatsBase branch pinned.36e5b015.tmp
INFO: Removing SpecialFunctions v0.1.1

julia> using StatsModels # this should trigger a recompile, not fail
ERROR: ArgumentError: Module SpecialFunctions not found in current path.
Run `Pkg.add("SpecialFunctions")` to install the SpecialFunctions package.
Stacktrace:
 [1] require(::Symbol) at ./loading.jl:403
 [2] _include_from_serialized(::String) at ./loading.jl:157
 [3] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:194
 [4] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:224
 [5] require(::Symbol) at ./loading.jl:409

julia> touch(Pkg.dir("StatsModels", "src", "StatsModels.jl"));

julia> using StatsModels
INFO: Recompiling stale cache file /home/tkelman/Julia/jlpkgtmp/lib/v0.6/StatsModels.ji for module StatsModels.
<some unrelated method overwrite warnings>
```

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #21266. I was not able to reproduce the original issue,
because the dependency chain changed and `DataArrays` also
depends on `SpecialFunctions`.

We are writing transitive dependencies to the `.ji` file,
because at the moment of loading the `.ji` files there is no
difference between transitive dependencies or direct dependencies.
Just a list of preconditions, that need to be fullfilled.

Instead of changing that fairly complex piece of logic during
feature freeze I decided to try a less disruptive approach
and check in `stale_cachefile`, if all dependencies are
available.

Any suggestions for tests?

### CODE REVIEW

File: base/loading.jl [hunk 1]
```diff
@@ -742,7 +743,17 @@ function stale_cachefile(modpath::String, cachefile::String)
             DEBUG_LOADING[] && info("JL_DEBUG_LOADING: Rejecting cache file $cachefile due to it containing an invalid cache header.")
             return true # invalid cache file
         end
-        modules, files = parse_cache_header(io)
+        modules, files, required_modules = parse_cache_header(io)
+
+        # Check if transitive dependencies can be fullfilled
+        for mod in keys(required_modules)
+            isdefined(Main, mod) && continue
```
Comment (vchuravy) [inline base/loading.jl]: It might be better to check here for `:Core, :Base, ...`.

**Comment by vchuravy** [comment]
A different solutions that would probably work, but is imho tricky to implement: Ensure a consistent ordering in the module dependency list, so that direct dependencies are loaded first. But at the point where that list is written we have no information about direct or indirect dependencies.

File: base/loading.jl (hunk 1 above)
Comment (tkelman) [inline base/loading.jl]: why would staleness depend on the in memory state of Main?

Comment (vchuravy) [inline base/loading.jl]: I am checking if the module is already loaded here, since if it is `read_verify_mod_list` from `dump.c`, won't fail. Just added a commit to be more explicit (it safes a few calls to `find_in_node_path`)

**Comment by tkelman** [comment]
for testing, we should be able to create a stack of 3 placeholder modules. Precompile the top one, then remove the bottom one and change the middle to not depend on it any more. That should reproduce the failure on master I believe.

**Review by vtjnash — APPROVED** [review]
I hate to slow it down this much (I've seen `find_in_node_path` can be a hot spot), since it'll probably cause a measurable performance regression in #15048). But this looks valid.

File: base/loading.jl [hunk 2]
```diff
@@ -699,7 +699,16 @@ function parse_cache_header(f::IO)
         push!(files, (String(read(f, n)), ntoh(read(f, Float64))))
     end
     @assert totbytes == 4 "header of cache file appears to be corrupt"
-    return modules, files
+    # read the list of modules that are required to be present during loading
+    required_modules = Dict{Symbol, UInt64}()
```
Comment (musm) [inline base/loading.jl]: nitpick :P but no space between {Symbol,UInt64}

Comment (KristofferC) [inline base/loading.jl]: According to?

Comment (musm) [inline base/loading.jl]: consistency with https://github.com/JuliaLang/julia/blob/70fdbe83a3022363fadbedef344b88dc3f05ea88/base/loading.jl#L683

and

https://github.com/JuliaLang/julia/blob/70fdbe83a3022363fadbedef344b88dc3f05ea88/base/loading.jl#L683

**Comment by vchuravy** [comment]
Added a test. (Developed against master with `Base.require`)

File: test/compile.jl [hunk 3]
```diff
@@ -325,6 +325,41 @@ try
...
+    Base.compilecache("FooBarT2")
+    write(FooBarT1_file,
+          """
+          __precompile__(true)
+          module FooBarT1
+          end
+          """)
+    rm(FooBarT_file)
+    @test Base.stale_cachefile(FooBarT2_file, joinpath(dir2, "FooBarT2.ji"))
+    # Before #21492 this would fail: Base.require(:FooBarT2)
```
Comment (tkelman) [inline test/compile.jl]: why don't we run it then?

Comment (vchuravy) [inline test/compile.jl]: My logic was that if the line above fails it should also fail (and we don't quite have a `@test_nothrow`), but you are right it shouldn't hurt also doing it here.

Comment (tkelman) [inline test/compile.jl]: we could test that it returns `=== nothing` if that's what it's supposed to do

**Comment by vchuravy** [comment]
I addressed all comments, there was one intermediate travis failure that is backed here https://gist.github.com/vchuravy/aa4a715b99ef33435892bfd934bcc577, but it seems unrelated.

**Comment by vchuravy** [comment]
with regard to performance (all tests done on a clean PKGDIR and after `Pkg.init(); Pkg.add("DataFrames")`)

##### This branch
```
# Precompilation run
JULIA_PKGDIR=${HOME}/jl21266 time ./julia -e "using DataFrames"
21.93user 5.97system 0:21.54elapsed 129%CPU (0avgtext+0avgdata 271452maxresident)k
0inputs+6000outputs (0major+160067minor)pagefaults 0swaps

# After precompilation
JULIA_PKGDIR=${HOME}/jl21266 time ./julia -e "using DataFrames"
1.47user 0.74system 0:01.42elapsed 155%CPU (0avgtext+0avgdata 211916maxresident)k
0inputs+0outputs (0major+11971minor)pagefaults 0swaps
```

##### Current master
```
JULIA_PKGDIR=${HOME}/jl21266 time ./julia -e "using DataFrames"
21.55user 6.02system 0:21.14elapsed 130%CPU (0avgtext+0avgdata 271000maxresident)k
0inputs+6016outputs (0major+160987minor)pagefaults 0swaps

 JULIA_PKGDIR=${HOME}/jl21266 time ./julia -e "using DataFrames"
1.49user 0.76system 0:01.48elapsed 151%CPU (0avgtext+0avgdata 214772maxresident)k
0inputs+0outputs (0major+12437minor)pagefaults 0swaps
```

@vtjnash is there a better way to check the performance impact? Right now it seems imperceptible, but it might be worse if the `JULIA_PKGDIR` is on a remote filesystem.

**Comment by vtjnash** [comment]
Those timings look good.

**Comment by bjarthur** [comment]
this PR breaks Gadfly.jl's ability to pre-compile:

```
julia> using Gadfly
INFO: Recompiling stale cache file /Users/arthurb/.julia/lib/v0.6/Gadfly.ji for module Gadfly.
WARNING: The call to compilecache failed to create a usable precompiled cache file for module Compose. Got:
WARNING: Module Iterators uuid did not match cache file.
WARNING: eval from module Main to Gadfly:    
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/arthurb/.julia/v0.6/Compose/src/Compose.jl")::Any
  ** incremental compilation may be broken for this module **

WARNING: imported binding for Iterators overwritten in module Main
```

**Comment by vchuravy** [comment]
Thanks for letting me know I am looking into it. What version of Compose/Gadfly are you using?

**Comment by bjarthur** [comment]
i'm on the master branch of each.

**Comment by KristofferC** [comment]
I have also gotten the `WARNING: Module Iterators uuid did not match cache file.` recently and that was before this commit. Are you sure this is the commit that broke it?

**Comment by bjarthur** [comment]
i've checkout out e0c497b22289487aff417380cdbdefa77255dd3b and everything works fine.

**Comment by fredrikekre** [comment]
I got the same error just now, and as for `@bjarthur` everything works if i checkout e0c497b . I tried removing `~/.julia/lib/v0.6/` but I get the same failure.
Found this from `using PGFPlots` but (for me) it boils down to the following error message from `using AxisArrays`

```julia
julia> using AxisArrays
INFO: Recompiling stale cache file /home/fredrik/.julia/lib/v0.6/AxisArrays.ji for module AxisArrays.
WARNING: The call to compilecache failed to create a usable precompiled cache file for module AxisArrays. Got:
WARNING: Module Iterators uuid did not match cache file.
ERROR: LoadError: Declaring __precompile__(true) is only allowed in module files being imported.
Stacktrace:
 [1] __precompile__(::Bool) at ./loading.jl:318
 [2] __precompile__() at ./loading.jl:314
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] require(::Symbol) at ./loading.jl:453
while loading /home/fredrik/.julia/v0.6/AxisArrays/src/AxisArrays.jl, in expression starting on line 1
```

**Comment by vchuravy** [comment]
@vtjnash I might need your help here

In a fresh Julia session
```
julia> Base.module_uuid(Main.Iterators)
0x000003c21dc6b0cb

julia> using Iterators
WARNING: imported binding for Iterators overwritten in module Main

julia> Base.module_uuid(Main.Iterators)
0x0000057e0e7d6f6b

julia> Base.parse_cache_header(joinpath(first(Base.LOAD_CACHE_PATH), "Compose.ji"))
...,  :Iterators=>0x0000057e0e7d6f6b, ...
```

But when we are restoring the module in `src/dump.c` `read_verify_mod_list`, we first check if the binding is already defined in `Main` and so we do not load the `Iterators` module provided by the package and then have an uuid conflict with `Base.iterators`. This is a issue independent of the PR above.

**Comment by tkelman** [comment]
x-ref https://github.com/JuliaLang/julia/pull/19108, possibly relevant?

File: base/loading.jl [hunk 4]
```diff
@@ -742,7 +743,22 @@ function stale_cachefile(modpath::String, cachefile::String)
...
         end
-        modules, files = parse_cache_header(io)
+        modules, files, required_modules = parse_cache_header(io)
+
+        # Check if transitive dependencies can be fullfilled
+        for mod in keys(required_modules)
+            if mod == :Main || mod == :Core || mod == :Base
+                continue
+            # Module is already loaded
+            elseif isdefined(Main, mod)
```
Comment (vtjnash) [inline base/loading.jl]: needs a check for `isbindingresolved(Main, mod)` first, to avoid causing `isdefined` to resolve the binding
