### PR TITLE
REPL: use atreplinit to change the active module during precompilation

### LINKED ISSUE #55800: Julia nightly failure to precompile REPL
In the most recent run of the GAP.jl CI runs with Julia nightly it fails to precompile REPL. Note that GAP.jl has REPL in its dependencies.

For example [this log](https://github.com/oscar-system/GAP.jl/actions/runs/10922171634/job/30315886858):
```
  12985.1 ms  ✓ AbstractAlgebra
           ✗ REPL
  28704.7 ms  ✓ Parsers
   1370.0 ms  ✓ JSON
           ✗ Pkg → REPLExt
    462.3 ms  ✓ GAP_lib_jll
    618.2 ms  ✓ GAP_pkg_juliainterface_jll
   3727.9 ms  ✓ Aqua
           ✗ Documenter
           ✗ GAP
  21 dependencies successfully precompiled in 65 seconds. 32 already precompiled.

ERROR: LoadError: The following 3 direct dependencies failed to precompile:

GAP --code-coverage=@/home/runner/work/GAP.jl/GAP.jl --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=error --inline=yes --startup-file=no --track-allocation=none --check-bounds=yes --compiled-modules=yes 

Failed to precompile GAP [c863536a-3901-11e9-33e7-d5cd0df7b904] to "/home/runner/.julia/compiled/v1.12/GAP/jl_ST05dz".
WARNING: Method definition formatdoc(Base.Docs.DocStr) in module REPL at /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/REPL/src/docview.jl:79 overwritten in module REPL at /cache/build/builder-amdci4-3/julialang/julia-master/usr/share/julia/stdlib/v1.12/REPL/src/docview.jl:79.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Error: Unexpected error (Review REPL precompilation with debug_output on):
│ 2004lERROR: Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
└ @ REPL.Precompile /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/REPL/src/precompile.jl:26
ERROR: LoadError: Failed to precompile REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] to "/home/runner/.julia/compiled/v1.12/REPL/jl_QGthvI".
Stacktrace:
...
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/55800

This seems the best option without piping an option through the REPL api to set the active module at the point the mistate is created.

### CODE REVIEW

File: stdlib/REPL/src/precompile.jl [hunk 1]
```diff
@@ -37,9 +37,22 @@ function repl_workload()
...
+            end
+            REPL.activate(REPL.Precompile; interactive_utils=false)
+        end
+        Base.errormonitor(t)
+    end
+
     repl_script = """
-    import REPL
-    REPL.activate(REPL.Precompile; interactive_utils=false) # Main is closed so we can't evaluate in it
+    sleep(1) # give the above async atreplinit a chance to change active_module
```
Comment (vtjnash) [inline stdlib/REPL/src/precompile.jl:55]: Sigh, I thought #55316 was supposed to fix this, but this API still feels like a disaster there.

I think you can replace this with an `Event` wait signaled by the atreplinit (and move the rest of the contents of the async block here?)
