### PR TITLE
AnnotatedStrings, and a string styling stdlib

### LINKED ISSUE #28690: Default REPL output is difficult to read on light background
I'm using Julia on macOS, and my terminals have a light (almost white) background. The default color scheme of the REPL is difficult to read there, as e.g. yellow (for warnings) is almost unreadable.

[This page](https://unix.stackexchange.com/questions/245378/common-environment-variable-to-set-dark-or-light-terminal-background) has some hints for how to automatically detect whether the terminal background is light or dark.

### LINKED ISSUE #40228: Improve visibilty of line location in stacktrace e.g. Ability to override/disable muted colour in stacktraces
Having updated to use the new Julia v1.6 release, i see that there's [improved stacktrace formatting](https://julialang.org/blog/2021/03/julia-1.6-highlights/#improved_stacktrace_formatting). 

I really appreciate that Julia tries to make these kind of usability improvements! The colouring of modules, for example, is a really helpful addition for more easily seeing the source of errors.

I know that making somewhat opinionated choices about UI, especially colours, is a tricky business, and from looking at the issues and PRs, a lot of care and effort has gone in (https://github.com/JuliaLang/julia/issues/36026 / https://github.com/JuliaLang/julia/pull/36134 / https://github.com/JuliaLang/julia/pull/37773).

However, i do have a bit of an issue and am wondering if something in Base can help:
I now find it **difficult to read the filepath/line location of errors, due to the muted grey (`:light_black`) colour of this info**. (Unlike the module colour change, i find this change makes it harder for me to see the source of errors)

This is a significant drop in useability for me. For context, i work as a full-time Julia programmer and basically live in the terminal, so am spending tens of hours a week in the Julia REPL. And it being difficult to read where errors come from is something that effects my day-to-day work. Which is to say, i don't just want to be picky about colour-schemes - i'm opening the issue because it's a change that effects my work quite a bit and because i'm hoping there will be a simple way to avoid it.

I'm wondering if there could, for example, be **a way to "opt-out" of various bits of colouring**, and just have the colour set to `:normal`? Essentially, i'd like to be able to set everything that's `:light_black` to use `:normal` instead.

I see there are already various environment variables for customising the new stacktrace printing (`JULIA_STACKTRACE_EXPAND_BASEPATHS`, `JULIA_STACKTRACE_CONTRACT_HOMEDIR`, `JULIA_STACKTRACE_LINEBREAKS`). 

I wonder if it would be possible to add one (or two) extra?
- e.g a `JULIA_STACKTRACE_COLOR_LINES` which could default to `true`, but could be set to `false` to have `:normal` used . 
  - we may then want a `JULIA_STACKTRACE_COLOR_MODULES` to match (again, i've no personal need for this; i'd leave this set to the default `true`)

i'm not hoping/expecting to have full customisability in Base, but the ability to "opt-out" and instead get the more conservative error printing that was in the previous Julia v1.x versions would be appreciated.

---

Some more detail:

My terminal has a fairly standard dark background and looks very much like the image from the v1.6 announcement blog:
image

I believe is I use ITerm2's default `Dark` theme.  (I think ITerm2 is the most commonly used terminal on MacOS). It looks like this (apparently a little less dark than the one above):
Screenshot 2021-03-27 at 10 57 19

I find e.g. the text `~/.julia/packages/Tables/UxLRG/src/tofromdatavalues.jl:42` difficult to read, where `tofromdatavalues.jl:42` is usually really useful info that i'm looking for.

i just mention this for the sake of being specific :) And, in case it's relevant, to say i don't have a really unusual, highly colourful theme. Also i suspect that for lots of people the lines are easy enough to read, and I have no qualms with this being the default appearance. I don't have great vision (i wear glasses), but beyond sometimes bumping up the font size don't usually have problems reading stuff in the terminal or elsewhere.

I really don't want to get into a debate about which colours to use, or to try to find a colour-scheme that works with every possible terminal theme (which isn't possible). i'd just prefer to find a way to set 'normal' colour for this text.

Thanks for any help!

### LINKED ISSUE #41435: color scheme support
As suggested here: https://github.com/JuliaLang/julia/pull/41423#issuecomment-872208265 it would be good to support theming Julia's colors. There's also https://github.com/JuliaLang/julia/issues/41295 but I think that may overcomplexify things. Without @staticfloat's input, I'm not entirely clear on how using Preferences in Julia would work, whereas I have a pretty clear idea about how adding a config file to theme Julia's colors would work: Instead of hardcoding colors, if Julia is run in color mode, it would look in a file called `~/.julia/config/colors.toml` that maps uses of colors as keys to some kind of color description as values. Here are some questions:

1. What are the color keys? Presumably descriptions of how we use colors.
2. What are the color values? `#123abc` strings? ANSI color names? Either?
3. Do we need anything else in the file or is it just this map?

I think for usability we'd probably also want to have changes to this file take effect immediately, so we'd want to remember the inode, size, mtime and ctime and if any of them changes, reload the file. We also want to take care that if we're not using color the file never needs to be looked at.

### LINKED ISSUE #41791: Provide entry point for color customization
Julia uses hardcoded colors for generating output (for example stacktraces) and unfortunately color choice is not always suitable for all users for various reasons.

I propose to use the following approach instead of colors hardcoding:

```julia
# define somewhere at the beginning

const COLOR = Ref((; foo = :red, bar = :green))

# and later in the code, when color is needed
printstyled("what you need to print", COLOR[].foo)
```

This simple change does not provide full-fledged color theme switching by itself (this probably should be implemented JuliaLang/julia#41435), but it provides an entry point for all future color theme related stuff. I.e. all user level convenience functions would just modify this variable one way or another. And anyway this proposal allows color customization right here and now (maybe slightly cumbersome) unlike the current situation.

Implementing this feature looks like a good beginner PR, doesn't require large modifications of the code base and it solves color issues.

### PR DESCRIPTION
**Pull request by tecosaur**
Styled content is hard to deal with. This contribution aims to drastically improve that.

Closes #41791, closes #41435, and I think also resolves #40228 and resolves #28690.

## New public API

Within `Base`:

- `AnnotatedString`
- `AnnotatedChar`
- `annotatedstring`

From the stdlib:

- `Base.Face`
- `addface!`
- `@S_str`

## Motivation

Julia already treats the REPL experience better than most other languages out there (🐍), and I think it's great how often I see the REPL as a selling point of Julia.

However... styling is hard. Across `Base` and the package ecosystem we have a painful mixture of raw ANSI codes and an unsightly pile of `printstyled` lines. This isn't just ugly, this leads to reoccurring issues with incorrectly computed string lengths/padding and unterminated styling codes (e.g. #37568 and #45521).

We can do better than this. Rethinking our approach to styled content allows us to do away with this class of bugs/headaches altogether, and gain a number of shiny new features at the same time.

Hy hope is that the capabilities introduced by this PR will lead to a much more robust approach to string styling, and by making it easier to produce well-styled content even more beautiful REPL experiences across the board.

## Rundown of changes

An `StyledString` type is introduced that effectively sits on top of other string types. It wraps another `AbstractString` but then separately stores a list of attributes applied to particular regions of the wrapped string. Regions are represented by a `UnitRange{Int}`, and attributes as a `Pair{Symbol, Any}`.

This effectively creates "content" and "attributes" layers, allowing both to be handled much better (conveniently and robustly) than when mixed together. Attributes can be *`Any`thing*, which allows for more than just styling information, e.g. hyperlinks, or other data which makes sense to attach to a region of a string like source location information. Really `StyledString` should be called `PropertizedString`, but I think that's much less catchy 😛.

An `StyledChar` type is also added, which is a mirror of `AbstractString`, just wrapping an `AbstractChar` instead.

To handle styling information, a new type is added to contain all possibly relevant styling information — `Face`. This is very much inspired by https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces.html, as I have found this system to work rather well in practice (why invent a new approach when there's a lovely battle-tested one we can be inspired by? 😉).

The main way faces work is by having a global `Dics{Symbol, Face}` of face names. This has a number of advantages:
- It makes it easy to reference faces by their name
- Packages can easily add new faces
- It makes it possible for faces to inherit from other faces (e.g. have a `:julia_help_prompt` face that inherits from `:julia_prompt`)

Conversion functions to accept and load face specifications from a `Dict{String, Any}` are also added. By loading `~/.julia/config/faces.toml` this resolves #41435.

To handle printing faces well, we need to inquire about the terminal a fair bit more, and so I've replaced `tcap` with a terminfo parser implemented in accordance with `term(5)`.

Lastly, we have a string macro (`@S_str`) that was rather nasty to write, but is very convenient.

#### Currently unimplemented

- `replace`
- property removal

## Usage examples

The example from the `@S_str` docs

image

Easy nested styling

image

No more issues with unterminated ANSI codes

image

String functions operate on the unstyled content, while preserving styling where possible

image

image

Styled text will actually automatically fall back to the un-styled form when printed to an `io` with `:color != true`.

image

Incrementally styling a string, and changing face definitions on-the-fly (note: this uses currently "private API" functions)

image

## Fancier usage examples

The result of the example "banner using `S"..."`" commit

image

A fancier `^R` implementation, that's been implemented using `StyledString`s and `JuliaSyntax` that would be a massive pain to do via `printstyled` et al.

image

With very little work, docstring previews could look like this

image

### CODE REVIEW

**Comment by longemen3000** [comment]
seems similar to Crayons.jl ? https://github.com/KristofferC/Crayons.jl

**Comment by tecosaur** [comment]
> seems similar to Crayons.jl?

Only in the sense that both Crayons.jl and this PR provide a more thorough approach to ANSI styling than `printstyled`. However:
- Crayons-marked content is not an `AbstractString`, and so does not work with string functions like `lpad` etc.
- Crayons does not resolve either the "truncation of styled content leaving unterminated ANSI codes" issue or the "ANSI sequences mess with string calculations" issue
- Most of the "Usage examples" are not possible with Crayons
- Crayons does not adjust printing based on the terminal capabilities (e.g. support for italics, truecolor)
- Crayons only supports some styles, not arbitrary attributes
- Crayons is built around ANSI-code styling, this is more general
- Crayons do not support stylistic inheritance, package-extended styles, or user-customisation of styles
- Crayons is not part of `Base`, and so cannot be used to improve how styled content is handled in `Base` (and I'd argue doesn't go far enough to warrant inclusion … while I think this PR does)

I'd encourage you to take a closer look at this contribution.

File: base/strings/styled.jl [hunk 1]
```diff
@@ -0,0 +1,363 @@
...
+StyledString(s::S, region::UnitRange{Int}, props::Pair{Symbol, <:Any}...)
+StyledString(s::S, properties::Vector{Tuple{UnitRange{Int}, Pair{Symbol, <:Any}}})
+```
+
+A StyledString can also be created with [`styledstring`](@ref), which acts much
+like [`string`](@ref) but preserves any styling present in the arguments.
+"""
+struct StyledString{S <: AbstractString} <: AbstractString
+    string::S
+    properties::Vector{Tuple{UnitRange{Int}, Pair{Symbol, Any}}}
```
Comment (KristofferC) [inline base/strings/styled.jl:23]: If we want to use this within Base, I think there cannot be an `Any` here so I think that needs to be restricted.

File: base/strings/styled.jl [hunk 2]
```diff
@@ -0,0 +1,363 @@
...
+StyledChar(c::AbstractChar) = convert(StyledChar, c)
+StyledChar(c::UInt32) = convert(StyledChar, Char(c))
+StyledChar{C}(c::UInt32) where {C <: AbstractChar} = convert(StyledChar, C(c))
+
+promote_rule(::Type{<:StyledString}, ::Type{<:AbstractString}) = StyledString
+
+## AbstractString interface ##
+
+ncodeunits(s::StyledString) = ncodeunits(s.string)
+codeunits(s::StyledString) = codeunits(s.string)
```
Comment (KristofferC) [inline base/strings/styled.jl:102]: Are all these needed? Doesn't the `AbstractString` interface provide some of these?

File: base/strings/styled.jl [hunk 3]
```diff
@@ -0,0 +1,363 @@
...
+    if i <= lastindex(s.string); (s[i], nextind(s, i)) end
+eltype(::Type{<:StyledString{S}}) where {S} = StyledChar{eltype(S)}
+firstindex(s::StyledString) = firstindex(s.string)
+lastindex(s::StyledString) = lastindex(s.string)
+
+function getindex(s::StyledString, i::Integer)
+    @boundscheck checkbounds(s, i)
+    @inbounds if isvalid(s, i)
+        StyledChar(s.string[i], textproperties(s, i))
+    else string_index_err(s, i) end
```
Comment (KristofferC) [inline base/strings/styled.jl:116]:
```suggestion
    else
        string_index_err(s, i)
    end
```

File: base/strings/util.jl [hunk 4]
```diff
@@ -484,13 +486,15 @@ function rpad(
     s::Union{AbstractChar,AbstractString},
     n::Integer,
     p::Union{AbstractChar,AbstractString}=' ',
-) :: String
+) :: if any(isa.((s, p), Union{StyledString, StyledChar, SubString{<:StyledString}})) StyledString{String} else String end
```
Comment (KristofferC) [inline base/strings/util.jl:489]: This is too complicated of a type assert.

**Review by KristofferC — COMMENTED** [review]
Just a set of basic comments that popped up from an initial reading of the code.

**Comment by bicycle1885** [comment]
It would be very nice if we could somehow unify this stylized strings and my format strings (https://github.com/bicycle1885/Fmt.jl) in Base.

File: base/regex.jl [hunk 5]
```diff
@@ -212,9 +212,9 @@ julia> hr
 "11"
 ```
 """
-struct RegexMatch <: AbstractMatch
-    match::SubString{String}
-    captures::Vector{Union{Nothing,SubString{String}}}
+struct RegexMatch{S<:AbstractString} <: AbstractMatch
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/regex.jl:215]: That's exactly what gave me the confidence to actually make this change. If this turns out to be awful for some reason, one (less nice) alternative that's occurred to me:

```julia
struct GenericRegexMatch{S<:AbstractString} ...

const RegexMatch = GenericRegexMatch{String}
```

but I hope this change will be acceptable.

File: base/regex.jl [hunk 6]
```diff
@@ -418,11 +418,26 @@ function match(re::Regex, str::Union{SubString{String}, String}, idx::Integer,
                                         SubString(str, unsafe_load(p,2i+1)+1,
                                                   prevind(str, unsafe_load(p,2i+2)+1)) for i=1:n]
     off = Int[ unsafe_load(p,2i+1)+1 for i=1:n ]
-    result = RegexMatch(mat, cap, unsafe_load(p,1)+1, off, re)
+    result = RegexMatch{String}(mat, cap, unsafe_load(p,1)+1, off, re)
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/regex.jl:421]: Without it I see (on `make`):
```
error during bootstrap:
LoadError("sysimg.jl", 3, LoadError("Base.jl", 314, LoadError("version.jl", 168, LoadError("version.jl", 168, MethodError(LoadError(at "sysimg.jl" line 3: LoadError(at "Base.jl" line 314: LoadError(at "version.jl" line 168: LoadError(at "version.jl" line 168: MethodError(f=Base.RegexMatch{S} where S<:AbstractString, args=(Base.SubString{String}(string="0-", offset=0, ncodeunits=2), Array{Union{Nothing, Base.SubString{String}}, (7,)}[
  Base.SubString{String}(string="0-", offset=0, ncodeunits=1),
  nothing,
  nothing,
  Base.SubString{String}(string="0-", offset=1, ncodeunits=1),
  nothing,
  nothing,
  nothing], 0x0000000000000001, Array{Int64, (7,)}[1, 0, 0, 2, 0, 0, 0], Base.Regex(pattern="^
    v?                                      # prefix        (optional)
    (\d+)                                   # major         (required)
    (?:\.(\d+))?                            # minor         (optional)
    (?:\.(\d+))?                            # patch         (optional)
    (?:(-)|                                 # pre-release   (optional)
    ([a-z][0-9a-z-]*(?:\.[0-9a-z-]+)*|-(?:[0-9a-z-]+\.)*[0-9a-z-]+)?
    (?:(\+)|
    (?:\+((?:[0-9a-z-]+\.)*[0-9a-z-]+))?    # build         (optional)
    ))
$", compile_options=0x040a008a, match_options=0x40000000, regex=0x00000000040c4d00)), world=0x00000000000035ba)))))
jl_method_error_bare at /home/tec/Desktop/TEC/Projects/available/julia/src/gf.c:2203
jl_method_error at /home/tec/Desktop/TEC/Projects/available/julia/src/gf.c:2221
jl_lookup_generic_ at /home/tec/Desktop/TEC/Projects/available/julia/src/gf.c:3050 [inlined]
ijl_apply_generic at /home/tec/Desktop/TEC/Projects/available/julia/src/gf.c:3065
match at ./regex.jl:421
```

the good news is I can't see any instances of `RegexMatch(...)` in the wild outside of Julia forks: https://grep.app/search?q=RegexMatch%28&filter[lang][0]=Julia

File: base/strings/faces.jl [hunk 7]
```diff
@@ -0,0 +1,698 @@
...
+Otherwise, `nothing` is returned.
+"""
+function tryparse(::Type{SimpleColor}, rgb::String)
+    if startswith(rgb, '#') && length(rgb) == 7
+        SimpleColor(parse(Int, rgb[2:3], base=16),
+              parse(Int, rgb[4:5], base=16),
+              parse(Int, rgb[6:7], base=16))
+    elseif startswith(rgb, 'a':'z')
+        SimpleColor(Symbol(rgb))
+    end
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:69]: Hmm, since none of the other branches have a `return`, how about just?:

```julia
else
    nothing
end
```

File: base/strings/faces.jl [hunk 8]
```diff
@@ -0,0 +1,698 @@
...
+Attempt to parse `rgb` as a `SimpleColor`. If `rgb` starts with
+`#` and has a length of 7, it is converted into a `RGBTuple`-backed `SimpleColor`.
+If `rgb` starts with `a`-`z`, `rgb` is interpreted as a color name
+and converted to a `Symbol`-backed `SimpleColor`.
+
+Otherwise, `nothing` is returned.
+"""
+function tryparse(::Type{SimpleColor}, rgb::String)
+    if startswith(rgb, '#') && length(rgb) == 7
+        SimpleColor(parse(Int, rgb[2:3], base=16),
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:64]: I suppose I should be a bit stricter since we only want `[0-9a-f]`, say
```julia
ncodeunits(rgb) == 7 && first(rgb) == '#' && all(∈(('#',) ∪ ('0':'9') ∪ ('a':'f')), rgb)
```

File: base/strings/faces.jl [hunk 9]
```diff
@@ -0,0 +1,698 @@
...
+withfaces(f) = f()
+
+## Face combination and inheritence ##
+
+"""
+    merge(a::Face, b::Face)
+Merge the properties of the text faces `a` and `b`, with those
+of `b` taking priority.
+"""
+merge(a::Face, b::Face) = if isnothing(a.inherit)
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:324]: Done

File: base/strings/styled.jl (hunk 1 above)
Comment (tecosaur) [reply base/strings/styled.jl:23]: Could you elaborate on why, is it a performance concern?

`Any` rather than say `Face` is a deliberate design choice to make this as broadly useful as possible. For instance, off the top of my head: it's useful to allow a `Face`, a `Symbol` naming a face, a `String` giving a hyperlink, Sixel image data, a source code position, and I'd imagine a bunch of things that will occur to other people.

File: base/regex.jl (hunk 6 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/regex.jl:421]: Ok, this seems to be solved by adding this constructor:
```julia
RegexMatch(match::SubString{S}, captures::Vector{Union{Nothing,SubString{S}}},
           offset::Union{Int, UInt}, offsets::Vector{Int}, regex::Regex) where {S<:AbstractString} =
    RegexMatch{S}(match, captures, offset, offsets, regex)
```

Yes, the `Union{Int, UInt}` is needed (because of `unsafe_load(p,1)+1` on line 425)

File: base/strings/styled.jl (hunk 2 above)
Comment (tecosaur) [reply base/strings/styled.jl:102]: There isn't a default implementation, without out these you get:

```julia

ERROR: MethodError: no method matching ncodeunits(::StyledString{String})

Closest candidates are:
  ncodeunits(::SubString)
   @ Base strings/substring.jl:81
  ncodeunits(::StyledChar)
   @ Base ~/Desktop/TEC/Projects/available/julia/base/strings/styled.jl:121
  ncodeunits(::SubstitutionString)
   @ Base regex.jl:568
  ...
```

File: base/strings/styled.jl (hunk 3 above)
Comment (tecosaur) [reply base/strings/styled.jl:116]: Done

File: base/strings/util.jl (hunk 4 above)
Comment (tecosaur) [reply base/strings/util.jl:489]: Huh, I just tested type inference and it seems like it's completely resolved (to a `String`/`StyledString` as appropriate), so I suppose no type assert is needed at all?

File: base/strings/faces.jl [hunk 10]
```diff
@@ -0,0 +1,698 @@
...
+         if strikethrough isa Bool
+             strikethrough
+         else ascolor(strikethrough) end,
+         inverse,
+         if inherit isa Symbol
+             (inherit,)
+         else inherit end)
+end
+
+convert(::Type{Face}, spec::NamedTuple) = Face(; spec...)
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:167]: I think I did this for `Dict -> Face` conversion, but ended up not using it. Removed.

File: base/strings/faces.jl [hunk 11]
```diff
@@ -0,0 +1,698 @@
...
+              inverse::Union{Nothing, Bool} = nothing,
+              inherit::Union{Nothing, Symbol, Tuple{Vararg{Symbol}}} = nothing,
+              _...) # Simply ignore unrecognised keyword arguments.
+    ascolor(::Nothing) = nothing
+    ascolor(c::SimpleColor) = c
+    ascolor(c::Union{Symbol, RGBTuple, UInt32}) = SimpleColor(c)
+    Face(font, ascolor(foreground), ascolor(background), weight, slant,
+         if underline isa Tuple{<:Union{Symbol, RGBTuple, UInt32}, Symbol}
+             (ascolor(underline[1]), underline[2])
+         elseif underline isa Union{Symbol, RGBTuple, UInt32}
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:153]: Ah, that is unfortunate. Changed.

File: base/strings/faces.jl [hunk 12]
```diff
@@ -0,0 +1,698 @@
...
+name, `default` is added to both [`DEFAULT_FACES`](@ref) and (a copy of) to
+[`FACES`](@ref), with the [`FACES`](@ref) value returned.
+
+Should the face `name` already exist, `nothing` is returned.
+"""
+function addface!(name::Symbol, default::Face)
+    if !haskey(DEFAULT_FACES, name)
+        DEFAULT_FACES[name] = default
+        FACES[name] = copy(default)
+    end
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:229]: The idea is that this adds a way to undo user customisation, which is applied to `FACES` but not `DEFAUtL_FACES`.

File: base/strings/faces.jl [hunk 13]
```diff
@@ -0,0 +1,698 @@
...
+In the unlikely event that the face `name` does not have a default value,
+it is deleted, a warning message is printed, and `nothing` returned.
+"""
+function resetfaces!(name::Symbol)
+    if !haskey(FACES, name)
+    elseif haskey(DEFAULT_FACES, name)
+        FACES[name] = copy(DEFAULT_FACES[name])
+    else # This shouldn't happen
+        delete!(FACES, name)
+        println(stderr,
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:255]: Really `@warn` would be most appropriate, but the `@warn` macro is not defined at this point, and so this is my compromise.

**Comment by tecosaur** [comment]
> It would be very nice if we could somehow unify this stylized strings and my format strings (https://github.com/bicycle1885/Fmt.jl) in Base.

That's an interesting idea. String formatting and styling at once does seem like it could be nice, I imagine something like `S"{warn:$(sqrt(2)):.2f}"` could be done. However, I don't want to let perfect be the enemy of the good, so I'm wary of jumping on tying these two things together and making a harder to review/merge PR.

Perhaps we could leave a 'hole' in the `S"..."` syntax which would allow for formatting to be supported down the road?

File: base/strings/faces.jl [hunk 14]
```diff
@@ -0,0 +1,698 @@
...
+- `inherit` (a `Tuple{Vararg{Symbol}}`): Names of faces to inherit from,
+  with earlier faces taking priority. All faces inherit from the `:default` face.
+"""
+struct Face
+    font::Union{Nothing, String}
+    foreground::Union{Nothing, SimpleColor}
+    background::Union{Nothing, SimpleColor}
+    weight::Union{Nothing, Symbol}
+    slant::Union{Nothing, Symbol}
+    underline::Union{Nothing, Bool, SimpleColor,
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:130]: Changed

File: base/strings/faces.jl [hunk 15]
```diff
@@ -0,0 +1,698 @@
...
+                     Tuple{<:Union{Nothing, SimpleColor}, Symbol}}
+    strikethrough::Union{Nothing, Bool}
+    inverse::Union{Nothing, Bool}
+    inherit::Union{Nothing, Tuple{Vararg{Symbol}}}
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:134]: Changed

**Comment by stevengj** [comment]
> Packages can easily add new faces

Not composably, though?  Having a mutable global namespace for this seems like it invites conflicts.

**Comment by tecosaur** [comment]
> Packages can easily add new faces
>
> Not composably, though?

Can you elaborate on what you mean by "composibly"? We have inheritance, e.g. `mypackage_repl_mode_prompt` can inherit from `julia_prompt` and `mypackage_main`. In my mind (and from my experience with this system over the past few years), that should be sufficient.

> Having a mutable global namespace for this seems like it invites conflicts.

A package could use its own face dictionary and `withfaces`, however this would fragment customisation, and easy (central) user customisation is another goal of this implementation. Currently, all face definitions can be modified by a user's `faces.toml`, which I think is highly desirable.

We can encourage package authors to use the face format name `pkgname_facename`, and so solve this potential issue via convention. Of course, there can be bad actors, but that's true of virtually any system we can dream up. For what it's worth, Emacs has had this system for at least 30 years, and I have yet to hear of anybody having any issues with face-name conflicts, and that's just thanks to this convention.

**Comment by tecosaur** [comment]
Changes in this force-push: Made the styled string macro (`@S_str`) more interpolate-able (i.e. made it so that properties can be interpolated as well as content).

**Comment by tecosaur** [comment]
So far this has just received a few surface-level comments. Is there anything I can do to make this easier to review?

If anybody wants to discuss the design/implementation more, I'm also happy to voice chat etc. in addition to comments here. There seems to be a decent amount of interest in this functionality (by :rocket: reacts it's currently the №4 open PR), and it would be great to see this translate into movement towards making this a shoo-in for merging :smiley:.

**Comment by tecosaur** [comment]
Because it's not much extra work, I've implemented `show(::IO, ::MIME"text/html", ::StyledString)`.

```html
<pre>               <span style="color: #008000;font-weight: 700;">_</span>
   <span style="color: #000080;font-weight: 700;">_</span>       _ <span style="color: #800000;font-weight: 700;">_</span><span style="color: #008000;font-weight: 700;">(_)</span><span style="color: #800080;font-weight: 700;">_</span>     <span style="color: #808080;">│</span>  <span style="font-weight: 700;">Documentation:</span> <a href="https://docs.julialang.org"><span style="text-decoration: #808080 underline;">https://docs.julialang.org</a></span>
  <span style="color: #000080;font-weight: 700;">(_)</span>     | <span style="color: #800000;font-weight: 700;">(_)</span><span style="font-weight: 700;"> </span><span style="color: #800080;font-weight: 700;">(_)</span>    <span style="color: #808080;">│</span>
   _ _   _| |_  __ _   <span style="color: #808080;">│</span>  Type <span style="color: #808000;background-color: #3a3a3a;font-weight: 700;">?</span> for help, <span style="color: #000080;background-color: #3a3a3a;font-weight: 700;">]?</span> for <a href="https://pkgdocs.julialang.org/"><span style="text-decoration: #808080 underline;">Pkg</a></span> help.
  | | | | | | |/ _` |  <span style="color: #808080;">│</span>
  | | |_| | | | (_| |  <span style="color: #808080;">│</span>  Version <span style="font-weight: 700;">1.10.0-DEV.1328</span> <span style="font-weight: 300;">(<span style="">2023-05-16<span style="">)</span></span></span>
 _/ |\__'_|_|_|\__'_|  <span style="color: #808080;">│</span>  <span style="color: #000080;">styled-strings</span>/<span style="color: #808080;">a68bb6f5cd*</span> (<span style="color: #008000;font-weight: 700;">↑<span style="font-weight: 400;font-style: italic;"> <span style="">11<span style=""> commits</span></span></span></span><span style="font-style: italic;">, </span><span style="color: #808000;">⌛<span style="font-style: italic;"> <span style="">2<span style=""> <span style="">days</span></span></span></span></span>)
|__/                   <span style="color: #808080;">│</span>

</pre>
```

if GitHub allowed span style in `<pre>`, this is what you'd see (in dark mode):

image

Happy to take out if this seems like too much for `Base`, I just think it's a nice way of demonstrating another aspect of the improved flexibility of this approach as compared to `printstyled` etc. — the ability to easily support extension to different output modes.

**Comment by vtjnash** [comment]
> Is there anything I can do to make this easier to review?

Probably not. If there is a tiny piece we could merge that first, but it is unclear if that makes sense here. The most convincing change is quite simple to make it easier: click "ready for review" so it doesn't look like you are still experimenting on it. Similarly, make sure the build is passing. Particularly for something this large, I don't want to iterate too many times on the review with just fixing up bugs since it tends to drown out the main discussion (Github in particular struggles with more than about 20 comments active at a time).

I am excited by this since, by the sound of things, this will mostly close out my old PR https://github.com/JuliaLang/julia/pull/27430 (though I can still look back through there later to see if I had any useful gadgets written to try to port to this). Showing that "text/html" was a sensible output there was also my demo to test whether it would be worth including, so I am glad to see it here now ;)

**Comment by tecosaur** [comment]
Thanks for your comments @vtjnash, I was hoping that before marking this as "ready for review" and getting into the details more people would give some feedback on the overall design/approach.

If the overall design looks acceptable, I'll go ahead and write tests, docs, and make sure the build passes.

That said, I've received consistently positive feedback so far. @StefanKarpinski seemed keen on the idea when I discussed it on Slack, and above it seems like @KristofferC's comments were mainly nit-picks. So, perhaps I should just go ahead with the tests/docs/news anyway and mark this as a non-draft PR?

Oh, and from a glance at #27430 it looks like what we may be interested in lifting over is a few of the minor things like the pretty range printing. In terms of the actual system/approach itself, I'm pretty sure this PR subsumes it entirely, and by quite some margin too :grin:.

**Comment by gbaraldi** [comment]
When a PR is marked as draft people think you are still playing with things and that lots may still change. When you mark it as ready for review then people will take a look.
Of course being able to build and having some tests/examples doesn't hurt for reviewing as well.
In any case great job with the PR. From a  far away glance it looks awesome

**Comment by tecosaur** [comment]
I feel like `S"styled"` is pretty comparable to `s"substitution"`. Descripiveness is good, but so is terseness, particularly when I can see this being used a lot. While I'm with you in general regarding descriptive naming, I think there are instances where the convenience is worth going for something shorter, and I think this is one of them.

Besides, I don't think there's much need to guess what it means, for two reasons:
1. I feel like if you see `S"The {bold:{italic:quick} {(foreground=#cd853f):brown} fox} jumped over the {link={https://en.wikipedia.org/wiki/Laziness}:lazy} dog"` (or similar) it's pretty obviously text + styling information.
2. We have the lovely `help?>`, which while not a panacea makes it pretty trivial to go from "I wonder what `S""` is?" to the docstring.

Before going with `S""` I did a search and couldn't find much use of `S""` in the wild: https://grep.app/search?q=macro%20S_str&case=true&filter[lang][0]=Julia, and in particular couldn't find any uses of `S""` in a package written for use outside the package's internals.

Oh, and with regards to
> Compared to functions, it's much more involved to qualify string macro names (as in `MyPackage.@S_str("...")`)

This actually isn't the case. See the following example:

```julia
julia> module Demo
       macro s_str(s)
       3
       end
       f() = s"test"
       end
Main.Demo

julia> Demo.s"hey"
3
```

**Comment by tecosaur** [comment]
> Almost forgot about substitution-strings. It makes the argument to avoid S"" for styled strings in Base even stronger.

Case matters, and I can't see much potential for confusion. A similar complaint could be applied to `r""` and `raw""`.

> It's not huge, but more than that website shows: [definitions](https://github.com/search?q=%2F%28%3F-i%29macro+S_str%2F+lang%3AJulia&type=code) and [usages](https://github.com/search?q=%2F%28%3F-i%29%5CbS%22%5Cw%2F+lang%3AJulia&type=code).

Okay, looks like there are a very small number of other packages too. Most of those results look to be forks of an old Julia version that actually had `S""` defined, and forks of DirectSum.

Similarly, if I look for `style""` there are a bunch of matches for that too. I don't think it's vital to use a prefix that *no-one* uses, so much as one that's very rarely used, and my impression is that `S""` easily clears this bar.

**Comment by tecosaur** [comment]
Hmmm, I remain unconvinced.

Anyway, we can leave that for now. It's a pretty trivial change that can be made just before merging, and I'm much more interested in discussing the actual design of the system at this stage.

**Comment by tecosaur** [comment]
> Why should this be exported at all, btw?

Why should anything be exported? I think, when something is broadly useful. I fully expect `S""` to be at least as useful as other Base exports.

File: base/strings/styled.jl [hunk 16]
```diff
@@ -0,0 +1,365 @@
...
+end
+
+eltype(::StyleIterator{S}) where { S <: AbstractString} =
+    Tuple{SubString{S}, Vector{Pair{Symbol, Any}}}
+
+"""
+    eachstyle(s::StyledString{S})
+    eachstyle(s::SubString{StyledString{S}})
+
+Identify the contiguously substrings of `s` with a constant style, and return
```
Comment (ericphanson) [inline base/strings/styled.jl:319]:
```suggestion
Identify the contiguous substrings of `s` with a constant style, and return
```

File: base/strings/faces.jl [hunk 17]
```diff
@@ -0,0 +1,778 @@
...
+    color
+end
+
+"""
+A [`Face`](@ref) is a collection of graphical attributes for displaying text.
+Faces control how text is displayed in the terminal, and possibly other
+places too.
+
+Most of the time, a [`Face`](@ref) will be stored in the [`FACES`](@ref) dict as
+a unique association with a *face name* Symbol, and will be most often reffered
```
Comment (ericphanson) [inline base/strings/faces.jl:94]:
```suggestion
a unique association with a *face name* Symbol, and will be most often referred
```

File: base/strings/faces.jl [hunk 18]
```diff
@@ -0,0 +1,778 @@
...
+to by this name instead of the `Face` object itself.
+
+## Attributes
+
+All attributes can be set via the keyword constructor, and default to `nothing`.
+
+- `foreground` (a `SimpleColor`): The text foreground color.
+- `background` (a `SimpleColor`): The text backgrond color.
```
Comment (ericphanson) [inline base/strings/faces.jl:102]:
```suggestion
- `background` (a `SimpleColor`): The text background color.
```

File: base/strings/faces.jl [hunk 19]
```diff
@@ -0,0 +1,778 @@
...
+    :highlight => Face(inherit=:emphasis, inverse=true),
+    # Julia prompts
+    :julia_prompt => Face(weight=:bold),
+    :julia_main_prompt => Face(inherit=[:green, :julia_prompt]),
+    :julia_help_prompt => Face(inherit=[:yellow, :julia_prompt]),
+    :julia_pkg_prompt => Face(inherit=[:blue, :julia_prompt]),
+)
+
+"""
+The global set of availible faces.
```
Comment (ericphanson) [inline base/strings/faces.jl:229]:
```suggestion
The global set of available faces.
```

**Review by ericphanson — COMMENTED** [review]
I think a section in the manual about faces would be helpful. Reading the PR, I don't really understand the difference between `FACES` and `DEFAULT_FACES`, since e.g. both are updated by `addface!`.

I wonder if it would also be helpful to update some of the code in Base that uses stuff like `printstyled` to instead use this system, to see what it looks like in practice.

**Comment by tecosaur** [comment]
Thanks for taking a look at this PR Eric!

> I think a section in the manual about faces would be helpful.

Mmmm, at this point I'm thinking some work on the manual and tests would be helpful for people taking a look at this PR.

> Reading the PR, I don't really understand the difference between `FACES` and `DEFAULT_FACES`, since e.g. both are updated by `addface!`.

Gah, I've just remembered that if I document these in the manual they become part of the public API (how I hate this). Is there some way I can talk about them without making them part of the public API? (Separately, I think a conversation needs to happen about how much of the functionality should be part of the public API)

> I wonder if it would also be helpful to update some of the code in Base that uses stuff like printstyled to instead use this system, to see what it looks like in practice.

I was hoping that the "[example] Use styled strings with the julia banner" commit would function in this way, but perhaps a bit more is needed?

**Comment by tecosaur** [comment]
Update on more examples: Looking through a bit more of the codebase and thinking a bit, there's a lot that can be done to integrate StyledStrings into bits of Base, and stdlibs like `REPL` and `Markdown`. I feel that those efforts should go on in separate PRs, but I can certainly provide examples that show some of the benefits that motivate this system.

For instance, in with the "Julia banner using StyledStrings" the "`]?` for Pkg help" uses the colouring of the Pkg repl, and if we tweak `LineEdit.Prompt` to accept a `StyledString` prompt other than making the prefix/suffix approach redundant, it will also allow for the user-customisation of the prompt style, and the re-use of that style in the banner.

image

**Comment by tecosaur** [comment]
The rebased commits have the typo fixes from Eric, + a few other minor fixes and tweaks.

**Comment by nathanrboyer** [comment]
[Term.jl](https://fedeclaudi.github.io/Term.jl/dev/basics/styled_text/#Styled-text) is another package which includes some of this functionality. I particularly like its `@style` macro:
`mytext = @style "this is my text" blue bold underline`. Does this PR have a way to list multiple styles together like `S"{blue, bold, underline: this is my text}"`, or do you have to nest them like `S"{blue: {bold: {underline: this is my text}}}"`?
(I couldn't figure out how to test this PR branch myself, sorry.)

**Comment by tecosaur** [comment]
The core functionality of this PR is actually more fundamental (which is part of why I think it's a good fit for Base) — a special string subtype that allows for the annotation of arbitrary region-specific information. This is then extended in two ways for convenience:
- String styling attributes (basically `faces.jl`)
- A convenience macro (`@S_str`)

I believe your question is actually answered by the `@S_str` docstring (or at least I hope so):
> Construct a styled string. Within the string, `{<specs>:<content>}` structures
apply the formatting to `<content>`, according to the list of comma-separated
specifications `<specs>`. Each spec can either take the form of a face name,
an inline face specification, or a `key=value` pair. The value must be wrapped
by `{...}` should it contain any of the characters `,=:{}`.
> \
> String interpolation with `$` functions in the same way as regular strings,
except quotes need to be escaped. Faces, keys, and values can also be
interpolated with `$`.

So, your example can simply be expressed as `S"{blue,bold,underline:this is my text}"`, or written without a macro as `StyledString("this is my text", :face => [:blue, :bold, :underline])`.

**Comment by vtjnash** [comment]
Perhaps this is a PR we can finish and merge at JuliaCon? (not saying it needs to wait that long either though, if it is ready sooner!)

**Comment by tecosaur** [comment]
If I can write the docs and tests and we sort this out beforehand, great! I'll see how much time I have though, and if not finishing and merging this at JuliaCon sounds great, it's always nicer to discuss things in person :slightly_smiling_face: (though I won't be around for the whole hackathon day).

File: base/strings/styled.jl (hunk 1 above)
Comment (StefanKarpinski) [reply base/strings/styled.jl:23]: Bump. @KristofferC: can you elaborate on why this is an issue. Are you worried about invalidations at call sites?

File: base/strings/styled.jl [hunk 20]
```diff
@@ -0,0 +1,365 @@
...
+function *(a::StyledString, b::StyledString)
+    combinedproperties = copy(a.properties)
+    append!(combinedproperties,
+            [(start + lastindex(a) => stop + lastindex(a), prop)
+             for ((start, stop), prop) in b.properties])
+    StyledString(a.string * b.string, combinedproperties)
+end
+
+*(a::StyledString, b::AbstractString) = a * convert(StyledString, b)
+*(a::AbstractString, b::StyledString) = convert(StyledString, a) * b
```
Comment (StefanKarpinski) [inline base/strings/styled.jl:141]: Rather than having these two, it feels like a `promote_type` method might be better, although I suppose this avoids allocating a new `StyledString` object every time you want to concatenate.

Comment (StefanKarpinski) [reply base/strings/styled.jl:141]: I don't think this comment should affect merging this or not; can be adjusted later.

File: base/strings/styled.jl (hunk 1 above)
Comment (KristofferC) [reply base/strings/styled.jl:23]: That was my worry yes (which I don't know if it is correct). But I was worried that we would use `StyledStrings` in a bunch of places and everywhere where `.properties` is used we would propagate an `Any` call to those methods and any method extension would then invalidate the whole printing system.

Maybe @timholy or @vtjnash knows better if this is a problem in practice.

Comment (tecosaur) [reply base/strings/styled.jl:23]: I think the key function in this regard may be `getface`, which is responsible for actually taking the string/some styles and saying "here's the overall/combined face you need to think about". It's taken some tinkering, but it's actually completely type stable.

```jl
julia> s = StyledString("some stuff", [(1:6, :face => :italic), (3:8, :face => :blue)])
"some stuff"

julia> @code_warntype Base.getface(s, 3)
MethodInstance for Base.getface(::StyledString{String}, ::Int64)
  from getface(s::StyledString, i::Integer) @ Base strings/faces.jl:424
Arguments
  #self#::Core.Const(Base.getface)
  s::StyledString{String}
  i::Int64
Body::Base.Face
1 ─ %1 = Base.textproperties(s, i)::Vector{Pair{Symbol, Any}}
│   %2 = Base.getface(%1)::Base.Face
└──      return %2
```

The other function called within that `getfaces` call and `eachstyled` is `textproperties`, which is also completely type stable.

```jl
julia> @code_warntype Base.textproperties(s, 3)
MethodInstance for Base.textproperties(::StyledString{String}, ::Int64)
  from textproperties(s::StyledString, i::Integer) @ Base strings/styled.jl:280
Arguments
  #self#::Core.Const(Base.textproperties)
  s::StyledString{String}
  i::Int64
Locals
  #485::Base.var"#485#486"{Int64}
  props::Vector{Tuple{UnitRange{Int64}, Pair{Symbol, Any}}}
Body::Vector{Pair{Symbol, Any}}
1 ─ %1 = Base.:(var"#485#486")::Core.Const(Base.var"#485#486")
│   %2 = Core.typeof(i)::Core.Const(Int64)
│   %3 = Core.apply_type(%1, %2)::Core.Const(Base.var"#485#486"{Int64})
│        (#485 = %new(%3, i))
│   %5 = #485::Base.var"#485#486"{Int64}
│   %6 = Base.getproperty(s, :properties)::Vector{Tuple{UnitRange{Int64}, Pair{Symbol, Any}}}
│        (props = Base.filter(%5, %6))
│   %8 = Base.broadcasted(Base.last, props)::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(last), Tuple{Vector{Tuple{UnitRange{Int64}, Pair{Symbol, Any}}}}}
│   %9 = Base.materialize(%8)::Vector{Pair{Symbol, Any}}
└──      return %9
```

This is the result of checking `@code_warntype` + benchmarking a bunch during development of these functions. I think `eachstyled` could maybe be improved a bit algorithmically, but microbenchmarks don't have me too concerned, though improvements (if possible) would be nice.

```jl
# This PR

julia> io = IOContext(IOBuffer(), :color => true)
IOContext(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1))

julia> @btime Base.banner(io)
  120.062 μs (1021 allocations: 180.61 KiB)

julia> io = IOContext(IOBuffer(), :color => false)
IOContext(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1))

julia> @btime Base.banner(io)
  12.746 μs (130 allocations: 17.77 KiB)

# On 1.10 beta 1

julia> @btime Base.banner(io)
  7.888 μs (31 allocations: 3.40 KiB)
```

So, that's a ~13x performance overhead for printing 60 styled regions. Only ~30% of this is actually from `eachstyle(banner_string)` though, which I take to mean that ~70% of this increace is in the printing, which is upstream of `strings/faces.jl` (see `strings/io.jl#979`).

**Comment by tecosaur** [comment]
I've now cherry-picked the Terminfo parser commits into #50797, which drops the size of this PR to ~1.5k new loc instead of ~2.5k :slightly_smiling_face:. It does also mean I'll see if we can get that PR sorted as a prerequisite now before coming back to get this one over the line (I can start writing some docs concurrently though).

**Comment by tecosaur** [comment]
For compat, I've now produced https://github.com/tecosaur/StyledStrings.jl, which I've just finished working on, but I *think* adds compat support for this feature back to Julia 1.0.

**Comment by tecosaur** [comment]
If somebody could add the `don't squash` label, that would be appreciated.

**Comment by tecosaur** [comment]
So I'm guessing the main thing I need to do now is add docs and tests? Or is there any more discussion to be had before I start doing the finishing touches? (I suppose this can also always be improved after merging in breaking ways until 1.11 is cut).

File: base/strings/faces.jl [hunk 21]
```diff
@@ -0,0 +1,779 @@
...
+```
+
+Also see `tryparse(SimpleColor, rgb::String)`.
+"""
+struct SimpleColor
+    value::Union{Symbol, RGBTuple}
+end
+
+SimpleColor(r::Integer, g::Integer, b::Integer) = SimpleColor((; r=UInt8(r), g=UInt8(g), b=UInt8(b)))
+SimpleColor(rgb::UInt32) = SimpleColor(reverse(reinterpret(UInt8, [rgb]))[2:end]...)
```
Comment (kdheepak) [inline base/strings/faces.jl:50]: Should there be another function for handling 256 colors? https://www.ditig.com/256-colors-cheat-sheet

Maybe `SimpleColor(ansi_value::UInt8) = ...`?

File: base/strings/faces.jl [hunk 22]
```diff
@@ -0,0 +1,779 @@
...
+    foreground::Union{Nothing, SimpleColor}
+    background::Union{Nothing, SimpleColor}
+    weight::Union{Nothing, Symbol}
+    slant::Union{Nothing, Symbol}
+    underline::Union{Nothing, Bool, SimpleColor,
+                     Tuple{<:Union{Nothing, SimpleColor}, Symbol}}
+    strikethrough::Union{Nothing, Bool}
+    inverse::Union{Nothing, Bool}
+    inherit::Vector{Symbol}
+end
```
Comment (kdheepak) [inline base/strings/faces.jl:135]: There are some terminals that support "hidden" or "conceal" attributes. Do you know if that can be supported? There's also ways blink text in a terminal and I don't see that in the PR.

Comment (kdheepak) [reply base/strings/faces.jl:135]: Here's the attribute table from `Crossterm` for reference:

image

File: base/strings/faces.jl [hunk 23]
```diff
@@ -0,0 +1,779 @@
...
+==(a::Face, b::Face) =
+    getfield.(Ref(a), fieldnames(Face)) ==
+    getfield.(Ref(b), fieldnames(Face))
+
+"""
+The default values for all defined faces. [`FACES`](@ref) is initially set to a
+copy of this value. This essentially allows for any modifications to
+[`FACES`](@ref) to be undone.
+"""
+const DEFAULT_FACES = Dict{Symbol, Face}(
```
Comment (kdheepak) [inline base/strings/faces.jl:179]: Should this maybe be `_DEFAULT_FACES`? 

It'd be nice to signal that the values in here should never change. Updating the docstring to state that would also help.

File: base/strings/faces.jl [hunk 24]
```diff
@@ -0,0 +1,779 @@
...
+    Changing faces is not thread-safe.
+"""
+function withfaces(f, altfaces::Dict{Symbol, Face})
+    global FACES
+    oldfaces, FACES = FACES, altfaces
+    try f()
+    finally
+        FACES = oldfaces
+    end
+end
```
Comment (kdheepak) [inline base/strings/faces.jl:333]: Is there a reason you don't have a `rethrow` here?

```suggestion
function withfaces(f, altfaces::Dict{Symbol, Face})
    global FACES
    oldfaces, FACES = FACES, altfaces
    try 
        f()
    catch err
        FACES = oldfaces
        rethrow(err)
    finally
        FACES = oldfaces
    end
end

File: base/strings/faces.jl [hunk 25]
```diff
@@ -0,0 +1,779 @@
...
+
+Apply `face` to `s`, along `range` if specified, or the whole of `s`.
+"""
+face!(s::Union{<:StyledString, <:SubString{<:StyledString}},
+      range::UnitRange{Int}, face::Union{Symbol, Face}) =
+          textproperty!(s, range, :face, face)
+
+face!(s::Union{<:StyledString, <:SubString{<:StyledString}},
+      face::Union{Symbol, Face}) =
+          textproperty!(s, firstindex(s):lastindex(s), :face, face)
```
Comment (kdheepak) [inline base/strings/faces.jl:446]: You have an example in the PR where you have `face!(str, 5:12, :test)`. 

image

Are the indices into the codepoints or the grapheme indices for the string?

How does it handle printing out an emoji like this:  🤦🏼‍♂️ ? What does the `face!` function do for a string like `str = " 🤦🏼‍♂️  the quick brown fox jumps over the lazy dog"`

This has 5 codepoints:

    🤦 : U+1F926 FACE PALM
    🏼 : U+1F3FC EMOJI MODIFIER FITZPATRICK TYPE-3
    ‍: U+200D ZERO WIDTH JOINER
    ♂ : U+2642 MALE SIGN (Ml)
    ️: U+FE0F VARIATION SELECTOR-16

But some terminals (ones that support it) display it in 1 cell width.

File: base/strings/faces.jl (hunk 21 above)
Comment (tecosaur) [reply base/strings/faces.jl:50]: I don't think so, I think we only want to support 4-bit colour and 24-bit RGB. We fall back from 24-bit RGB to 8-bit colour automatically when needed.

File: base/strings/faces.jl (hunk 24 above)
Comment (tecosaur) [reply base/strings/faces.jl:333]: It's not needed/

File: base/strings/faces.jl (hunk 25 above)
Comment (tecosaur) [reply base/strings/faces.jl:446]: It's just Julia string indexing, i.e. codepoints.

File: base/strings/faces.jl (hunk 22 above)
Comment (tecosaur) [reply base/strings/faces.jl:135]: From what I can tell, blinking and hidden text are rarely supported and (to me at least) not as clearly useful as the attributes currently supported.

File: base/strings/faces.jl (hunk 23 above)
Comment (tecosaur) [reply base/strings/faces.jl:179]: Hmm, this could be done. Really neither `DEFAULT_FACES` not `FACES` should be directly accessed. I also wonder if `FACES` should be renamed to `CURRENT_FACES` or this changed to a `NamedTuple{(:default, :current)}`.

**Comment by jariji** [comment]
> We can encourage package authors to use the face format name `pkgname_facename`, and so solve this potential issue via convention. Of course, there can be bad actors, but that's true of virtually any system we can dream up. For what it's worth, Emacs has had this system for at least 30 years, and I have yet to hear of anybody having any issues with face-name conflicts, and that's just thanks to this convention.

Emacs in general is organized around namespacing by convention, which is enough of a problem that there are [many packages](https://www.emacswiki.org/emacs/Namespaces) dedicated to addressing the issue. 

Maybe faces are less of a problem because there won't be so many in practice, but using underscore for "namespacing" here seems like an unnecessary regression, given the standard Julia conflict-avoiding systems:  UUIDs for avoiding conflicts between packages and the module-namespace system for avoiding conflicts between symbols.

I didn't really follow how the inheritance thing works and I'm generally concerned about adding a mutable global symbol table. Could this part of the proposal be spelled out more?

**Comment by tecosaur** [comment]
@jariji Hmm, I've got quite a few thoughts on this, but I'm not a fan of typing essays when a paragraph might do, so I'll just start with one (IMO) of the more compelling reasons for adopting this method.

Simply put, if we want to have this easily customisable by users (which I see as one of the goals of this, see also #41435), we need a way of referring to faces in a TOML file. Two obvious ways of doing so spring to mind:
- using some sort of UUID system
- using names

If we want a face TOML file that's simple, using names is really the only way to go. Here's a sample of what's accepted with this PR:
```toml
# Inside ~/.julia/config/Faces.toml
[stacktraces.filepath] # equivalent to stacktraces_filepath
foreground = "bright_yellow" # grey is too dim
```

If we use some package/UUID namespaced system, we could cook up another way of making customisations, but it wouldn't be nearly so simple to use or reason about. I see `FACES` as operating similarly to `ENV`, which is also why `withfaces(f, faces...)` is part of this PR.

-----

Regarding how inheritance works, it's fairly straightforward: you can provide a list (`Vector{Symbol}`) of faces that you inherit styling information from. Any attributes not explicitly specified are inherited from this list, with earlier faces taking priority.

You can see this with the REPL face examples.
```julia
# Within DEFAULT_FACES
:repl_prompt => Face(weight=:bold),
:repl_prompt_main => Face(inherit=[:green, :repl_prompt]),
```

For example, if I were to add a third inheritance, say a thin red face called `red_herring`, it would work like this:

File: base/strings/faces.jl (hunk 23 above)
Comment (tecosaur) [reply base/strings/faces.jl:179]: This thought is complicated by the fact that one is a `const` and the other isn't. I'm also wary of just slapping underscores in front of everything non-public API.

File: base/strings/faces.jl [hunk 26]
```diff
@@ -0,0 +1,779 @@
...
+
+"""
+    merge(faces::Face...)
+    merge(faces::Vector{Face})
+
+Merge the properties of `faces` into a single face, with the properties
+of subsequent faces overriding the properties of prior faces.
+"""
+merge(a::Face, b::Face, others::Face...) = merge(merge(a, b), others...)
+merge(faces::Vector{Face}) = foldl(merge, faces, init=Face())
```
Comment (jariji) [inline base/strings/faces.jl:368]: `merge` semantics are well defined to take `k` arguments and merge them, not to `foldl` a vector of them. The proposed `::Vector{Face}` behavior is technically allowed but I don't think it should be added.

File: base/strings/faces.jl [hunk 27]
```diff
@@ -0,0 +1,779 @@
...
+
+"""
+    merge(face::Face)
+
+Merge any inherited faces of `face` into a self-contained [`Face`](@ref).
+"""
+function merge(face::Face)
```
Comment (jariji) [inline base/strings/faces.jl:375]: Likewise here, `merge` already has a meaning. If a function for canonicalizing a face is needed, then I think it's better to use another name.

**Comment by jariji** [comment]
On namespacing, perhaps modules could declare certain faces, and then the face would be identified by their qualified name `Base.stacktraces_filepath` rather than being an unqualified global name.

File: base/strings/faces.jl (hunk 27 above)
Comment (tecosaur) [reply base/strings/faces.jl:375]: With respect to `Face`s, `merge` has in my mind a single meaning: merge all faces, implicit and explicit. The purpose of this single-arity method is to merge the implicit faces within `face` (i.e. inherited values) to a single stand-alone `Face`. I see this as fitting with the spirit of `merge`, but am quite willing to entertain other approaches.

Comment (tecosaur) [reply base/strings/faces.jl:375]: In a way, there's almost a single method here: `merge(faces::Face...)` and the fact that we actually have:

```
merge(a::Face)
merge(a::Face, b::Face)
merge(a::Face, b::Face, others::Face...)
``` 

is more an implementation detail than anything else (I'm still thinking about the comment you made about `Vector{Face}`, so let's leave that aside here).

File: base/strings/faces.jl (hunk 26 above)
Comment (jariji) [reply base/strings/faces.jl:368]: Suppose Base defines `merge(::Vector...)` to behave like it does for `Dict`s, returning another `Vector`. Then you're in trouble, because `merge(::Vector{Face})` is in conflict with that.

File: base/strings/faces.jl (hunk 27 above)
Comment (tecosaur) [reply base/strings/faces.jl:375]: It's a bit hard to actually separate those two operations, in order to merge several faces I think you need to canonicalise them.

**Comment by jariji** [comment]
I was thinking about instead of `inherit=[(:Base, :stacktraces_filepath)]` having `inherit=[(Base.stacktraces_filepath,)]` where `Base.stacktraces_filepath` is some kind of `Face` or `FacePlaceholder` configuration object.

**Comment by tecosaur** [comment]
With the current system, if you want to pass around `Face`s directly you still can (with slightly more involved inheritance). 

However, I find the convenience that comes with a central `Dict{Symbol, Face}` rather compelling (including how it can be reset to default values and allows for `withfaces`, which are not minor features in my mind) and so am not keen to abandon it without a really good justification for why we're better off without it.

**Comment by jariji** [comment]
`withfaces` isn't listed in the public API section above.  I wonder if some of this would be better setting a dynamic scope https://github.com/JuliaLang/julia/pull/50958 rather than mutating globals.

**Comment by PallHaraldsson** [comment]
Is StyledChar very useful? I would like to get rid of Char eventually..., I know what it's for, why useful, and e.g. can fit in a register.

I also dislike AbstractChar for the same reason (and wouldn't want people adding a lot of subtypes to it; and it's slow if you restrict your structs to it). Since StyledChar is a struct, it no longer fits in one register will use the heap, so would it be better to drop it to simplify? or `const StyledChar = StyledString` of important ans someone would look for it for consistency/"completeness"?

File: base/strings/faces.jl (hunk 27 above)
Comment (jariji) [reply base/strings/faces.jl:375]: If there's a rule `forall x, merge(x) == x` does this method break it?

Comment (tecosaur) [reply base/strings/faces.jl:375]: Hmm, it wouldn't hold `∀x`, or rather any `x` where `x.inherit` is populated.

As mentioned though, the root problem in trying to have a merge-but-don't-canonicalise method is that the two are mixed. The base case (`merge(x)`) is just a special case of the general behavior.

**Comment by tecosaur** [comment]
> `withfaces` isn't listed in the public API section above.

The current public API section is not what I think is *useful*, but what I think is *essential*. I was hoping for a conversation about what should/shouldn't be part of the public API, but that hasn't received any comment and so it's still the minimal starting point.

> I wonder if some of this would be better setting a dynamic scope #50958 rather than mutating globals.

`withfaces` could be reimplemented that way, but I think `DEFAULT_FACES` / `FACES` would still need to be globals, and this regards where the `Dict{Symbol, Face}` should live, not whether it should exist.

**Comment by tecosaur** [comment]
> Is StyledChar very useful? [...] Since StyledChar is a struct, it no longer fits in one register, and will use the heap, so would it be better to drop it to simplify?

I think the core question here is do we want to be consistent with `getindex(::AbstractString, ::Integer) -> AbstractChar` (and other similar methods, like `iterate(::AbstractString)`. If so we need `StyledChar`, otherwise we can get by without it.

File: base/strings/faces.jl (hunk 26 above)
Comment (tecosaur) [reply base/strings/faces.jl:368]: I'll see about finding where this method is used and replacing them with the `foldl` form.

File: base/strings/faces.jl (hunk 27 above)
Comment (tecosaur) [reply base/strings/faces.jl:375]: About to push a change that I think will have both of us happy.

File: base/strings/faces.jl (hunk 26 above)
Comment (tecosaur) [reply base/strings/faces.jl:368]: About to push a change that removes this.

File: base/strings/faces.jl (hunk 23 above)
Comment (tecosaur) [reply base/strings/faces.jl:179]: Going to try a NamedTuple approach.

**Comment by tecosaur** [comment]
Changes I've just pushed:
- Make styled concatenation with `*` work better
- Make `StyledChar` display more similarly to `Char`
- Add a face `height` parameter (not useful in a TTY, but useful everywhere else)
  - Minor consideration: should this be called `size` instead? `pt` is a height-based unit though
- Fix a `S""` edge case
- Make `merge`ing faces behave more like `merge`ing NamedTuples
- Fix some inheritance bugs
- Add a custom `Face` show method
- Consolidate `FACES` and `DEFAULT_FACES` into a single NamedTuple

**Comment by tecosaur** [comment]
Demo of the new `Face` show methods:

image

**Comment by tecosaur** [comment]
Ok, this should not be merged without removal of the `[example] Use styled strings with the julia banner` and some tests + docs + discussion about the public API, but I'll mark this as not-draft anyway in the hope of getting more eyes/reviews on this.

**Comment by tecosaur** [comment]
> I wonder how this large addition (almost 2k new lines) fits into the recent push to remove existing stdlibs and turn them into separate packages.

It doesn't. This isn't intendet to be a stdlib, it's intended to be a basic piece of functionality to be used throughout `Base`, the standard library, and wider package ecosystem.
As mentioned in the initial message, this solves provides functionality that has already been asked for in `Base` and there are bugs in `Base` that this system would prevent from occurring. See #50817 for some more concrete plans on what would be done next with this.

> does it actually need to be exported by default?

I think we'd want some things to be exported by default, the question of what things hasn't really happened yet.

> as I understand, this styledstrings functionality and API hasn't been tried out in any package yet

With regard to seeing if the design works out in practice, it's very much worth noting that this isn't a new design I've come up with, it's a reimplementation of a system that has been around for ~40 years. If that's not "tried and tested", I don't know what is.

> Lots of design questions popping up in this thread, even without actual widespread usage of this functionality, evidences that the design is not as obvious so that to get it right from the first try.

This has been about things like the `merge` methods implemented, etc. not the basic design.

Also, as mentioned earlier there is a package for compat purposes and to make it easier to try this out. There's nothing stopping people from giving this a whirl themselves.

**Comment by tecosaur** [comment]
> The generic concept of "styling program output" surely has been around for long. But this specific interface/API - surely not, right?

It has, this is heavily based on Emacs' face attributes system, which you can see mentioned in the 1985 Emacs 13 manual for instance.

The "specific interface/API" is of course different, since this hasn't been implemented in Julia before. The project here is to effectively carry over the (good) ideas, and make it easy to use. A lot of work has been put into doing so, and the aspects of the implementation that could be revised are far from being part of the public API. Please don't pooh-pooh in general terms.

> I couldn't find it, neither in this thread [...]

https://github.com/JuliaLang/julia/pull/49586#issuecomment-1668671822

**Comment by tecosaur** [comment]
If you want to read more about the source of inspiration here Alex, you could take a look at https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Properties.html, https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Props-and-Strings.html, and https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces.html.

**Comment by tecosaur** [comment]
> Not sure why you feel there's any hurry to add this into Base

So myself and others can do things using it in Base and the standard library. See that meta-issue I linked earlier. This has also been maturing for most of a year now, I'm not sure if I'd call that rushed...

**Comment by tecosaur** [comment]
> Putting this in Base (if documented and considered public) effectively freezes the design

With the currently proposed minimal API, I don't see much as actually being frozen. The main thing is
```julia
struct StyledString{S <: AbstractString} <: AbstractString
    string::S
    properties::Vector{Tuple{UnitRange{Int}, Pair{Symbol, Any}}}
end
```

the constructors of `StyledString` + `StyledChar` + `Face`, and the `addface!` and `styledstring` methods.

These are all aspects of the design that I am very confident about, and notably have not needed to be changed since this effort started (`Face` did just gain support for a `height=` keyword following JuliaCon, but that would be a backwards-compatible change).

The only other bit of design that's set in stone as the public API is the `S""` helper macro, which is just a convenience styled string constructor.

I think we might want to actually add a bit more to the public API, but that discussion has yet to really happen and can be had right at the end of this process anyway.

**Comment by tecosaur** [comment]
> an implementation almost in the abstract, without any actual users (packages).

I do think I see the point you're making, I just don't feel it actually holds here. I have (another unpublished) package that uses this system extensively, and have substantial experience with the analogue of this implementation in Emacs that serves as the inspiration here. I'd definitely count these two as giving me a concrete basis to evaluate the details of this implementation, even if it's not a collection of people using a published Julia package.

Particularly given my main ambitions with this system lie in `Base` and the standard library, I think it's hard to extensively demonstrate the utility in that regard without having this available in `Base` to use — I see it as a bit of a chicken and egg problem (unless you want to build a much bigger PR, which I'm not a fan of).

I also think it's worth noting that it's not as if once this PR is merged everything within it is suddenly set in stone. We have till the next version of Julia comes out to tinker with it and adjust it as needed. In that respect, this is actually a good reason to try to finish this sooner rather than later. With 1.11 in early-ish development, the sooner this is merged the longer this process can go for.

Alternatively we could wait for 1.12 or 1.13, but I think there's also a danger of the process getting dragged out too much and losing momentum I think.

File: base/strings/styled.jl (hunk 1 above)
Comment (tecosaur) [reply base/strings/styled.jl:23]: I'm going to mark this as resolved unless anybody wants to re-raise it :)

**Comment by jkrumbiegel** [comment]
I think in general this would be useful to have, and I do think this is even more general than things from `Statistics` or `LinearAlgebra`, because almost all packages out there print things to the REPL. And if it gets that much easier to style that in a coherent way, it will have a large beneficial impact on the ecosystem. Especially for peripheral stuff like this, people are hesitant to use the features if they mean additional dependencies. I for one have never added a styling package to any package of mine, only used `printstyled`. But I would certainly make use of this here.

I haven't looked at the implementation closely, but I guess the core terminal capabilities are pretty fixed and have been so for a long time, so it should be reasonably clear how to translate that into Julia without going through a long package test phase. The global faces without module namespacing I'm not sure about, I'd tend towards a bit less convenience if we can do away with that.

**Comment by rafaqz** [comment]
Personal big vote for putting this in Base. I am sick of how hard styling in `show` is with `printstyled`.

Having better styling in base rather than a package is actually important. Often we cant justify adding a dependency to packages with many dependencies just to make things pretty. If this is not in base all my styling code will keep using `printstyled` and custom hacks forever.

But clear communication via text, our core medium, is a fundamental part of the language we should always be improving.

**Comment by christiangnrd** [comment]
On the default MacOS Terminal, the banner text stops rendering after this code gets displayed `doclink = S"{bold:Documentation:} {(underline=grey),link={https://docs.julialang.org}:https://docs.julialang.org}"` (line 448 in client.jl)   image

Interestingly, the text can be copied from the terminal, it just doesn't show up.

Copy-paste of MWE:
```
julia> S"Test:{(underline=grey),link={https://example.com}:example}"
"Test:example"

julia> S"Test:{(underline=grey,link={https://example.com}):example}"
"Test:example"

julia> S"Test:{underline=grey,link={https://example.com}:example}"
"Test:example"
```

Screenshot of MWE using Terminal:
image

Screenshot of MWE using iTerm2:
image

**Comment by tecosaur** [comment]
Interesting, I wonder if Terminal.app is doing something funky with the OSC 8 hyperlinks? Sounds like some testing is in order, worst case I suppose some special-case behaviour can be added.

**Comment by christiangnrd** [comment]
I believe it might be the underline. After a bit more experimentation:
image

Here's a text version edited to only show what is seen:

```
julia> doclink_og = S"{bold:Documentation:} {(underline=grey),link={https://docs.julialang.org}:https://docs.julialang.org}"
"Documentation:

julia> show(stdout,"text/html", doclink_og)
<pre><span style="font-weight: 700;">Documentation:</span> <a href="https://docs.julialang.org"><span style="text-decoration: initial underline;">https://docs.julialang.org</a></span></pre>
julia> doclink_no_underline = S"{bold:Documentation:} {link={https://docs.julialang.org}:https://docs.julialang.org}"
"Documentation: https://docs.julialang.org"

julia> show(stdout,"text/html", doclink_no_underline)
<pre><span style="font-weight: 700;">Documentation:</span> <a href="https://docs.julialang.org">https://docs.julialang.org</a></pre>
julia> doclink_no_link = S"{bold:Documentation:} {underline=grey:https://docs.julialang.org}"
"Documentation: https://docs.julialang.org"

julia> show(stdout,"text/html", doclink_no_link)
<pre><span style="font-weight: 700;">Documentation:</span> https://docs.julialang.org</pre>
julia> doclink_no_link = S"{bold:Documentation:} {(underline=grey):https://docs.julialang.org}"
"Documentation:

julia> show(stdout,"text/html", doclink_no_link)
<pre><span style="font-weight: 700;">Documentation:</span> <span style="text-decoration: initial underline;">https://docs.julialang.org</span></pre>```

**Comment by christiangnrd** [comment]
This keeps getting more interesting.
Screenshot 2023-09-03 at 16 47 07

The text in the rest rest of the line for the red, green, blue, and white options is blinking (even the " which should not be affected)

**Comment by tecosaur** [comment]
@christiangnrd turns out the fancy-underline capability code needed a little rearranging to actually work as intended. I'll push a fix momentarily.

**Comment by christiangnrd** [comment]
It's working now!

**Comment by tecosaur** [comment]
Just pushed:
- A fix for multi-codepoint strings within interpolations `$(...)` in the `S""` macro
- A custom `show` method for `SimpleColor`s, using the same display as `Face` (and refactoring `Face`'s method to call `show(io, MIME("text/plain"), ::SimpleColor)`)
- A `StyledString(::AbstractVector{AbstractChar})` method as an analogue of `String(::AbstractVector{AbstractChar})` that keeps styling information.

Here's a fun demo from the Julia slack showing off those last two changes:

image

**Comment by LilithHafner** [comment]
Adding triage label per @tecosaur's request on slack to get more feedback from folks, especially about what may become part of the Base API.

**Comment by tecosaur** [comment]
Thanks, I think it could be good to chat with a few people about:
- The bones/structure of this PR
- What should be the public API
- Next steps with Base
- Answer any questions/concerns/etc. prior to final polish and "let's merge this!"

I have just noticed though that the triage call goes on a 2:15 am my time though :sweat_smile: so it might have to be a case of other people submitting questions on notice and me answering them in text at a sane hour, which isn't ideal but might be the best possible option?

**Comment by tecosaur** [comment]
I've just pushed an overhauled `S""` macro. See the commit message for details, but the bullet points are that it is now:
- More maintainable (no longer one big for loop)
- More correct (I've generated a quarter million test cases, and whittled the errors down to 0)
- You can now interpolate inline face values (e.g. `foreground=$(expr)`)

I've also developed an EBNF grammar for the `S""` macro (and used it to generate the test cases), here it is:

```
styledstring = { styled | interpolated | escaped | plain } ;

specialchar = '{' | '}' | '$' | '"' ;
anychar = [\u0-\u1fffff] ;
plain = { anychar - specialchar } ;
escaped = '\', specialchar ;

interpolated = '$', ? expr ? | '$(', ? expr ?, ')' ;

styled = '{', ws, properties, ':', content, '}' ;
content = { interpolated | escaped | plain | styled } ;
properties = property | properties, ws, ',', ws, property
property = face | inlineface | keyvalue ;
ws = { ' ' | '\\t' | '\\n' } ; (* whitespace *)

face = facename | interpolated ;
facename = [A-Za-z0-9_]+ ;

inlineface = '(', ws, [ faceprop ], { ws, ',', faceprop }, ws, ')' ;
faceprop = [a-z]+, ws, '=', ws, ( [^,)]+ | interpolated) ;

keyvalue = key, ws, '=', ws, value ;
key = ( [^\${}=,:], [^=,:]* ) | interpolated ;
value = simplevalue | curlybraced | interpolated ;
curlybraced = '{' { escaped | plain } '}' ;
simplevalue = [^\${},:], [^,:]* ;
```

**Comment by adienes** [comment]
I have no idea how big of a lift this would be so it's just musing

I know earlier in this thread there was some concern about the use of a global face dict (intended for user customization). Would context-dependent values be a more appropriate design (had they been available at the time of writing this PR), and if so, would it be worth rebasing on top of https://github.com/JuliaLang/julia/pull/50958 to use the `ScopedValue` therein?

**Comment by tecosaur** [comment]
See https://github.com/JuliaLang/julia/pull/49586#issuecomment-1700512479 for some of my current thoughts on why I think the current system is desirable, and:

> `withfaces` could be reimplemented that way, but I think `DEFAULT_FACES` / `FACES` would still need to be globals, and this regards where the `Dict{Symbol, Face}` should live, not whether it should exist.

**Comment by tecosaur** [comment]
I've just pushed a start on test cases, and a few minor fixes that were made along the way.

**Comment by tecosaur** [comment]
Just pushed some draft documentation and a NEWS entry

**Comment by jariji** [comment]
Is it possible to represent interleaved annotations as a string macro? as a repr? For example

```xml
<b>Hello <i> world </b> goodbye </i> world
```

**Comment by tecosaur** [comment]
Interleaved like that? I can't think of any non-annoying way of handling it.

**Comment by jariji** [comment]
I mean it's not possible to write that string using `@S_str`, right?

**Comment by tecosaur** [comment]
`S"{bold,italic:Hello world} {italic:goodbye} world"` is what you'd currently do.

**Comment by brenhinkeller** [comment]
Looks like this has docs, news, and tests now so removing those blocking labels

File: base/strings/styled.jl [hunk 28]
```diff
@@ -0,0 +1,388 @@
...
+codepoint(c::StyledChar) = codepoint(c.char)
+
+# Avoid the iteration fallback with comparison
+cmp(a::StyledString, b::AbstractString) = cmp(a.string, b)
+cmp(a::AbstractString, b::StyledString) = cmp(a, b.string)
+# To avoid method ambiguity
+cmp(a::StyledString, b::StyledString) = cmp(a.string, b.string)
+
+==(a::StyledString, b::StyledString) =
+    a.string == b.string && a.properties == b.properties
```
Comment (jakobnissen) [inline base/strings/styled.jl:133]: Do we want this, instead of just comparing the underlying string? (I.e. I would almost always consider two strings equal if they have the same word-for-word content). And if we do want this, does the order of the elements in the properties matter?

Comment (tecosaur) [reply base/strings/styled.jl:133]: This is something I'm not sure, as it depends on the notion of equality used.

Comment (jakobnissen) [reply base/strings/styled.jl:133]: One approach: First test the strings. If they are the same, then run `styledstring_optimize!` on both strings, then check if they have the same number of elements in the properties vector. Then  `issetequal` on the properties vector.

Comment (tecosaur) [reply base/strings/styled.jl:133]: Sure, but what I'm reconsidering is what `==` should be for `StyledStrings`. If we just compare the underlying string with `==`, what operator is appropriate when checking properties too?

Comment (tecosaur) [reply base/strings/styled.jl:133]: Hmm, would it be unreasonable to define this as `isequal`?

**Comment by tecosaur** [comment]
Pushed:
- Docs and docstring tweaks
- Minor code reorganisation
- Removed the example commit so it isn't accidentally merged
- A little general polish and bugfixing

**Comment by adienes** [comment]
how much do the `@inbounds` added here impact performance? there's no `OffsetStrings.jl` package lurking in the closet is there? 😛

**Comment by tecosaur** [comment]
I'm not sure how much the `@inbounds` affect performance, but there's absolutely no change with substring offsets — that's actually why the new `SubString` inner constructor is needed and why `@inbounds` can be used.

File: base/strings/styled.jl (hunk 28 above)
Comment (jariji) [reply base/strings/styled.jl]: > I would almost always consider two strings equal if they have the same word-for-word content

I wouldn't do that for the same reason I'd consider `OrderedDict`s with different orders unequal. I expect that `x::T, y::T, f`, for any function `f` in the API of `T`, we have `x == y implies f(x) == f(y)`. Since the style is in the API of `StyledString`, I expect two strings with different styles to be unequal.

File: base/strings/styled.jl (hunk 20 above)
Comment (tecosaur) [reply base/strings/styled.jl]: This is obsolete with the adjustment to the `string` method made.

**Comment by tecosaur** [comment]
FYI @jariji `S"{bold:Hello }{bold,italic:world}{italic: goodbye} world"` now generates interleaved styling regions even though it isn't written that way.

**Comment by tecosaur** [comment]
Ok, at this point I think the PR is in good shape to review. The current test failures are due to:
- The `needs X` PR labels (I think those should be removed now)
- Docstring generation relating to which symbols are exported (might as well wait for the conclusion of the "what should be exported?" discussion before fixing this all up)

File: base/strings/styled.jl (hunk 28 above)
Comment (tecosaur) [reply base/strings/styled.jl:160]: Ok, I'm currently leaving this as same-string-with-same-properties. Regarding ordering, most of the time the properties _should_ be in sorted order, which should make things easier. `::StyledString == ::AbstactString` now holds if the `StyledString` has no properties and `==` holds on the underlying string.

**Comment by jariji** [comment]
I think it's bad that this uses a syntax `"{a:x}"` very similar to the ["formatted string literals" syntax](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) from Python and Rust and Fmt.jl/Format.jl/Formatting.jl but switches the argument order: `value:presentation` vs `presentation:value`.

Python: `"{math.pi:.3f}"`
This PR: `"{red:math.pi}"`

I consider the Python style canonical at this point so any syntax in this space should be designed around it, not the other way around.

**Comment by tecosaur** [comment]
Hmm, that's a reasonable point, but I'm still more inclined towards the `{attributes:content}` syntax for a few reasons:
- It allows for an attributes-content-formatting order (e.g. `{attributes:content:formatting}`
- Many other languages/libraries have styling/attributes before content, e.g.
  - HTML (`<span attrs...>content</span>`)
  - RTF, which has `{\b bold}` etc.
  - Rust's console: `style.apply_to(content)`
  - Crayons.jl: `RED(content)` etc.

I'll also note that in terms of language, you tend to put adjectives before a noun, and verb-like qualifications afterwards, e.g.
- The big red dog `{big,red:dog}`
- The hedge trimmed into a pyramid `{hedge:pyramid}`

Formatting specifications are verb-like (note the subject-verb order in "the number rounded to 3 decimal places" and "the string is padded to 12 characters wide"). Most of the world's languages follow an adjectives-subject-verb word order.

**Comment by kdheepak** [comment]
[You mention in a previous comment](https://github.com/JuliaLang/julia/pull/49586#issuecomment-1535016803) that it would be possible to leave a hole for formatting to be supported. Is that still the case? If this implementation can support `S"{number:.3f}"`, `S"{red:number}"` and `S"{red:number:.3f}"` that'd be pretty awesome.

**Comment by tecosaur** [comment]
It has yet to be discussed, but even without it doing anything now, I think there's a strong argument for leaving "room" for a formatting directive in the syntax.

**Comment by LilithHafner** [comment]
> I'll also note that in terms of language, you tend to put adjectives before a noun, and verb-like qualifications afterwards, e.g.
> * The big red dog `{big,red:dog}`

This norm is language dependent. For example, Spanish typically places adjectives after the noun.
* el gran perro rojo `{gran:perro:rojo}`
* el texto en cursiva roja `{texto:cursiva,roja}`

**Comment by vchuravy** [comment]
One of the questions that was raised during triage is how much of this code needs to be in base proper and how much could be in a standard library?

**Review by vchuravy — COMMENTED** [review]
I do think we need to make this concurrency safe.

**Comment by tecosaur** [comment]
It depends if we just want to define the types, or also want to use them. If we're talking amount of code, half this PR is docs/docstrings/tests. Then you've got a chunk of code related to printing and defining/resolving faces. I.e. actually making the system work for printing.

We could reduce it to just the docs/tests + core types, but I think that would only make sense if `Base` did no printing. We're quite far away from that being a reality, and TBH I don't see much benefit in this course of action. I'm actually concerned that such an action could reduce some of the benefits I think we could hope to see by embracing this system more fully.

Anyway, hopefully, we can organise a triage-y call and actually discuss this (and the rest of the points for discussion collected earlier). I'd love to be able to not just have this system in 1.11, but make good use of it too.

File: base/strings/faces.jl [hunk 29]
```diff
@@ -0,0 +1,1244 @@
...
+end
+
+"""
+Globally named [`Face`](@ref)s.
+
+`default` gives the initial values of the faces, and `current` holds the active
+(potentially modified) set of faces. This two-set system allows for any
+modifications to the active faces to be undone.
+"""
+const FACES = let default = Dict{Symbol, Face}(
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:267]: Very much so. This way it's trivially package-extensible (just adding new entries). An append-only dict would be the stricter form.

File: base/strings/faces.jl [hunk 30]
```diff
@@ -0,0 +1,1244 @@
...
+# Examples
+
+```jldoctest
+julia> withfaces(:yellow => Face(foreground=:red), :green => :blue) do
+           println(S"{yellow:red} and {green:blue} mixed make {magenta:purple}")
+       end
+"red and blue mixed make purple"
+```
+"""
+function withfaces(f, keyvals::Pair{Symbol, <:Union{Face, Symbol, Nothing}}...)
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:400]: It isn't. A `ScopedValue` may make sense, but I'd think that's something it would make most sense to investigate later.

[the remark this answers is not in the document]
Comment (jpsamaroo) [reply base/strings/faces.jl:400]: I think we really want this to use Scoped values before the feature makes it into a release. A global dictionary works for package extensibility, but it doesn't make sense for locally modifying faces (which may occur on multiple tasks concurrently for printing-heavy workloads).

[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:400]: Quite possibly. But we can make that change after merging `ScopedValues`, can't we? Worst case, say there's an odd hold-up from that, upgrading this from thread-unsafe to thread-safe is a non-breaking change.

[the remark this answers is not in the document]
Comment (jpsamaroo) [reply base/strings/faces.jl:400]: It was just merged this morning 😊

[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:400]: Oooh, very nice. I'll give that a look then.

[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:400]: That said, it could be good to first chat on a triage-y call about what effective use of that looks like.

[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:400]: Well, first roadblock: `ScopedValue` is loaded after these files :(

**Comment by vchuravy** [comment]
So one idea from Stefan was. Maybe we can have the minimal infrastructure in Base and a way to have a fallback print that ignores the styling.

Long-term we want to support use-cases where a small sysimg is essential and so we want to still down Base much more.

**Comment by tecosaur** [comment]
I've just been exchanging some DMs with Stefan on slack about that :joy:.

Regarding sysimage size, the `text/plain` printing contributes 1kB, not nothing, but:
1. I think it's worth it
2. Since the printing code only adds specialisations, it can be removed later in a non-breaking way (just with a visual impact)

Oh and the fallback you mention already exists, try `julia --color=no` with this PR.

**Comment by ParadaCarleton** [comment]
> * el gran perro rojo `{gran:perro:rojo}`

funnily enough that shows how Spanish places adjectives on both sides :smile:

With that in mind, though, I still agree, because in Julia (and Python), properties/adjectives go after the thing they describe, e.g. `x.property` instead of `property.x`.

**Comment by ParadaCarleton** [comment]
> how much do the `@inbounds` added here impact performance? there's no `OffsetStrings.jl` package lurking in the closet is there? 😛

Maybe we should remove any `@inbounds` if we can? If nothing else it encourages bad habits for any new users who read the code for this. Inbounds can also get really iffy with non-ASCII strings. 

Luckily, I don't think there's a need for it here; the compiler should be able to prove there's no out-of-bounds indexing, and string styling is unlikely to be a major performance bottleneck in practical applications.

**Comment by tecosaur** [comment]
@ParadaCarleton please deal with the _specifics_ of the `@inbounds` in this PR. I didn't just through them in for a laugh, and if you have particular objections to particular objections here you'll also want to argue for changes in other parts of the codebase. Here are some examples (one of my introduced `@inbounds` in the first block, an existing example somewhere else in `Base` the second).

https://github.com/JuliaLang/julia/blob/5be358fdd0c340f417e5f9ecaf99022397819638/base/strings/styled.jl#L133-L134

https://github.com/JuliaLang/julia/blob/3c0d4802fadd4eb81657cd495fea2cc722646014/base/strings/basic.jl#L155-L156

-----

https://github.com/JuliaLang/julia/blob/5be358fdd0c340f417e5f9ecaf99022397819638/base/strings/styled.jl#L139-L146

https://github.com/JuliaLang/julia/blob/3c0d4802fadd4eb81657cd495fea2cc722646014/base/strings/basic.jl#L182-L185

-----

https://github.com/JuliaLang/julia/blob/5be358fdd0c340f417e5f9ecaf99022397819638/base/strings/substring.jl#L40-L45

https://github.com/JuliaLang/julia/blob/3c0d4802fadd4eb81657cd495fea2cc722646014/base/strings/substring.jl#L31-L37

While there are some nice general comments that can be applied to this PR without going to the effort of actually looking at the details, I'd like to reassure people that I have in fact put some thought into most of it, and so if people could either avoid or substantiate sweeping statements that would be appreciated.

**Comment by nsajko** [comment]
> you'll also want to argue for changes in other parts of the codebase

This is a PR that's being reviewed. The PR's changes themselves are by far the most relevant thing to discuss while it's being reviewed and unrelated changes are supposed to be off-topic, in my opinion.

> I'd like to reassure people that I have in fact put some thought into most of it, and so if people could either avoid or substantiate sweeping statements that would be appreciated.

Pretty sure you're being overly defensive. I can see *why* you'd be overly defensive, seeing as such a large change is presumably difficult to review in-depth. One thing that would make it easier to review, though, is **removing** inbounds directives.

**Comment by tecosaur** [comment]
Once again, if it would be possible to get more nuanced commentary than "inbounds bad" that would be appreciated, particularly when said `@inbounds` closely mirrors other code in Base that is presumably that way for a reason (I do think that when making a PR to Base, the code already in Base is quite relevant).

Look, I appreciate these general statements are generally true, but that's not specifically helpful when the `@inbounds` are present on more than a whim.

**Comment by adienes** [comment]
not to poke on it too much, but maybe at least one or two tests for error on out-of-bounds access (particularly for `RegexMatch`) would be worth it?

I don't doubt that you have thought through the usage of `@inbounds` carefully, and mirroring existing usage in doing so. But on the other hand, it occasionally feels like 90% of the deepest and most silently destructive bugs in Julia come from `@inbounds`, so can't be too careful.... just for example, such tests would have caught https://github.com/JuliaArrays/StaticArrays.jl/issues/1199

**Comment by rafaqz** [comment]
@tecosaur has asked for specific feedback... will someone asking to remove inbounds macros please just add review comments where they think there are problems and specifically show why.

From a quick skim there are at least a few that are totally ok, some that may need checks and tests, some that may need removal.

We all know the general problem, the real work is pointing out the specific problems in this PR. 

If you do that everyone following this can also see what you mean without scrolling through 2000 lines of code.

**Comment by adienes** [comment]
I hope I am not coming across as adversarial, as I do not intend to

> @tecosaur has asked for specific feedback... will someone asking to remove inbounds macros please just add review comments where they think there are problems and specifically show why.

but I am not asking to remove them, only to be careful and add tests, the first of which is already done. asking to add `at least one or two tests for error on out-of-bounds access`  feels like it is specific enough feedback to be actionable

**Comment by rafaqz** [comment]
Isnt it better to just comment on which specific inbounds you want tested l?

When someone has already asked three times for more specific feedback?

There are multiple onbounds macris, which ones do you want one

File: base/regex.jl [hunk 31]
```diff
@@ -212,14 +212,30 @@ julia> hr
...
     regex::Regex
 end
 
+RegexMatch(match::SubString{S}, captures::Vector{Union{Nothing,SubString{S}}},
+           offset::Union{Int, UInt}, offsets::Vector{Int}, regex::Regex) where {S<:AbstractString} =
+    RegexMatch{S}(match, captures, offset, offsets, regex)
+
+function RegexMatch{StyledString{S}}(m::RegexMatch{S}, str::StyledString{S}) where {S<:AbstractString}
+    RegexMatch{StyledString{S}}(
+        (@inbounds SubString{StyledString{S}}(
```
Comment (LilithHafner) [inline base/regex.jl:229]: If this method of `RegexMatch` is public, then, IIUC, this `@inbounds` allows folks to create a substring that violates invariants using only safe public API if `m` and `str` come from different strings:

```julia
julia> str = StyledString{String}("abc",[])
"abc"

julia> m = match(r"def", "abcdef")
RegexMatch("def")

julia> rm = RegexMatch{StyledString{String}}(m, str); # Should this error?

julia> m2 = rm.match;

julia> dump(m2)
SubString{StyledString{String}}
  string: StyledString{String}
    string: String "abc"
    properties: Array{Tuple{UnitRange{Int64}, Pair{Symbol, Any}}}((0,))
  offset: Int64 3
  ncodeunits: Int64 3
```

If it's a private method, then ideally it would have a name that isn't exported. I prefer the solution of renaming this to `_RegexMatch`. In general, I don't like adding private methods to public functions.

Comment (tecosaur) [reply base/regex.jl]: Thanks @LilithHafner. This is just needed for the two `match` functions. I implemented this as a constructor because it, well, constructs a `RegexMatch` from an existing one.

I've just pushed this change:

```julia
function _styledmatch(m::RegexMatch{S}, str::StyledString{S}) where {S<:AbstractString}
    RegexMatch{StyledString{S}}(
        (@inbounds SubString{StyledString{S}}(
            str, m.match.offset, m.match.ncodeunits, Val(:noshift))),
        Union{Nothing,SubString{StyledString{S}}}[
            if !isnothing(cap)
                (@inbounds SubString{StyledString{S}}(
                    str, cap.offset, cap.ncodeunits, Val(:noshift)))
            end for cap in m.captures],
        m.offset, m.offsets, m.regex)
end

match(re::Regex, str::StyledString{S}) where {S<:AbstractString}
    m = match(re, str.string)
    if !isnothing(m)
        _styledmatch(m, str)
    end
end

function match(re::Regex, str::StyledString{S}, idx::Integer, add_opts::UInt32=UInt32(0)) where {S<:AbstractString}
    m = match(re, str.string, idx, add_opts)
    if !isnothing(m)
        _styledmatch(m, str)
    end
end
```

Even though it's no longer used the `{S<:AbstractString}` in the `match` methods seems to be needed to beat out the "convert to `String` and try again" fallback method in terms of method specificity.

Comment (LilithHafner) [reply base/regex.jl]: Lovely! 

> the {S<:AbstractString} in the match methods seems to be needed to beat out the "convert to String and try again" fallback method in terms of method specificity.

I don't understand how this is the case. IIUC, the set of alternative methods is
```
 [1] match(re::Regex, str::Union{SubString{String}, String}, idx::Integer)
 [2] match(r::Regex, s::AbstractString, i::Integer)
 [3] match(re::Regex, str::StyledString{S}) where S<:AbstractString
 [4] match(r::Regex, s::AbstractString)
 [5] match(re::Regex, str::Union{SubString{String}, String}, idx::Integer, add_opts::UInt32)
```
none of which are ambiguous with or more specific than
```
match(re::Regex, str::StyledString, idx::Integer, add_opts::UInt32=UInt32(0))
```

Comment (tecosaur) [reply base/regex.jl]: Neither can I! When I removed them though, I saw:

```
  ArgumentError: regex matching is only available for the String type; use String(s) to convert
  Stacktrace:
   [1] match(r::Regex, s::StyledString{String}, i::Int64)
     @ Base ./regex.jl:458 
   [2] match(r::Regex, s::StyledString{String})
     @ Base ./regex.jl:457
```

where the methods [2] and [1] are:

```julia
match(r::Regex, s::AbstractString) = match(r, s, firstindex(s))
match(r::Regex, s::AbstractString, i::Integer) = throw(ArgumentError(
    "regex matching is only available for the String type; use String(s) to convert"
))
```

Thinking about it, the type restriction was the only thing that changed in the `match` method ... so I just added them back :shrug:.

Comment (tecosaur) [reply base/regex.jl]: Ah, I've just recalled that the `julia` process I had there may have been from a version that tried scoping `_styledmatch`, which would mess things up :sweat_smile:.

I'll try re-checking and push the version we both expect would work if it actually does.

**Comment by Krastanov** [comment]
The S macro would cause some consternation to users of QuantumClifford.jl, which exports an S macro for the preparation of Stabilizer states (a concept in quantum information science). Of course, the use of `StyledStrings.@S_str` will be ecosystem wide, so there is a reason to prioritize it, but could you consider not having it visible in Main by default? May it be set so that it needs an explicit `using`/`import`?

**Comment by jkrumbiegel** [comment]
What's the benefit of exporting `S""`? It's accessible with a little less friction, but even `Base.S"` is not terrible if you don't want to write `using Base: @S_str`. I think keeping it unexported is better, I don't foresee that hindering adoption.

**Comment by tecosaur** [comment]
One thought that I'm going to bring up in the triage-y call later this week (scheduled outside of the normal triage, because I can't make that one) is putting the new string type + some basic functions in Base, and then putting the faces/printing in a small `StyledStrings` stdlib. There would mean that you'd have to import it to get `S""` et al.,  but there are also tradeoffs that need discussing.

Speaking of the triage-y meeting, do come along if you're interested in this feature. There's currently a when2meet out (https://www.when2meet.com/?21623435-cWncQ) and after a time becomes clear (it's currently looking like some time during next week) we'll be announcing the time in #triage on Slack.

Once set I'll mention it here too.

**Comment by tecosaur** [comment]
The StyledStrings triage call will be held on the triage zoom at 13:00 UTC this Wednesday (in ~32h).

**Comment by tecosaur** [comment]
Thanks to everyone who turned up to the call, it was a good chat!

These are the conclusions I've noted down from it:
- Thanks for that long triage chat everyone! Conclusions I've noted down from it:
- Rename `Styled{String,Chat}` to `Tagged{String,Char}`
- Move everything other than the `Tagged{String,Char}` type + changes to base string functions for them into a `StyledStrings` stdlib
- Base will have `Tagged{String,Chat}` (but not the struct fields) + `textproperties + `textproperty!` as the public API
- The global face dictionary stays (for now), but it's not directly exposed and will use a `ScopedValue` or possibly HMAT directly
- The `addface!` in `__init__` also stays, with grumbling about the code-smell that it is and openness to a better way of doing things that doesn't sacrifice convenience/ease of use
- The styling macro will be `style"content"` and we'll add a "syntax hole" for formatting like so: `style"{styles:content:formatspec}"`
- A `TaggedIO` type likely will be useful to have to make use of this with `show` / `showerror`, but that can come later
- Public API for `StyledStrings` stdlib will just be what's needed by library authors to define a new face
- Only export the `style""` macro
- With the above comments applied, happy to merge now and improve/tweak in the future

**Review by LilithHafner — COMMENTED** [review]
I left several minor comments; none of them are merge-blockers, so address them or not as you see fit

File: base/strings/faces.jl [hunk 32]
```diff
@@ -0,0 +1,1244 @@
...
+```julia
+SimpleColor(name::Symbol)  # e.g. :red
+SimpleColor(rgb::RGBTuple) # e.g. (r=1, b=2, g=3)
+SimpleColor(r::Integer, b::Integer, b::Integer)
+SimpleColor(rgb::UInt32)   # e.g. 0x123456
+```
+
+Also see `tryparse(SimpleColor, rgb::String)`.
+"""
+struct SimpleColor
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:23]: I don't think so, and I can't say I see how to make that happen. It would be nice though!

File: base/strings/faces.jl [hunk 33]
```diff
@@ -0,0 +1,1244 @@
...
+specialchar = '{' | '}' | '\$' | '\\\"' ;
+anychar = [\u0-\u1fffff] ;
+plain = { anychar - specialchar } ;
+escaped = '\\\\', specialchar ;
+
+interpolated = '\$', ? expr ? | '\$(', ? expr ?, ')' ;
+
+styled = '{', ws, properties, ':', content, '}' ;
+content = { interpolated | escaped | plain | styled } ;
+properties = property | properties, ws, ',', ws, property
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:694]: Done, thanks :)

File: base/strings/faces.jl [hunk 34]
```diff
@@ -0,0 +1,1244 @@
...
+
+specialchar = '{' | '}' | '\$' | '\\\"' ;
+anychar = [\u0-\u1fffff] ;
+plain = { anychar - specialchar } ;
+escaped = '\\\\', specialchar ;
+
+interpolated = '\$', ? expr ? | '\$(', ? expr ?, ')' ;
+
+styled = '{', ws, properties, ':', content, '}' ;
+content = { interpolated | escaped | plain | styled } ;
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:693]: About to change when `:` needs to be escaped within "plain" content.

File: base/strings/faces.jl (hunk 32 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/faces.jl:23]: Actually, I think I see a way for this to happen. I could tweak the code, and `Colors.jl` could implement `convert(SimpleColor, ::Colorant)`.

**Comment by jariji** [comment]
`style"content"` looks odd. I'd expect the body of that string to be a style, like with `dateformat"yyyy-mm-dd"` or `colorant"yellow"`, not a styled string. It seems better to call it `styled"content"`.

**Comment by PallHaraldsson** [comment]
I (style) or styled"content" to not conflict with S_str macro already available elsewhere? Any exported (added) macro or function would hypothetically conflict. I might be ok with styled_str and PkgEval to at least reduce the odds. Base.S"content" wasn't thought good enough (though suggested)?

**Comment by tecosaur** [comment]
`style"content"` is to avoid potential confusion with `S"content"` vs. `s"\1"`. Personally I still quite like `S""` but I'm not married to it, I'll just be doing `const var"@S_str" = var"@style_str"` in my own code :sweat_smile:.

**Comment by tecosaur** [comment]
I've just pushed most of the changes that came up in the call, I'll try to finish it off tomorrow.

File: base/regex.jl [hunk 35]
```diff
@@ -423,6 +427,32 @@ function match(re::Regex, str::Union{SubString{String}, String}, idx::Integer,
...
+function match(re::Regex, str::StyledString, idx::Integer, add_opts::UInt32=UInt32(0))
+    m = match(re, str.string, idx, add_opts)
+    if !isnothing(m)
+        _styledmatch(m, str)
+    end
+end
+
 match(r::Regex, s::AbstractString) = match(r, s, firstindex(s))
 match(r::Regex, s::AbstractString, i::Integer) = throw(ArgumentError(
     "regex matching is only available for the String type; use String(s) to convert"
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/regex.jl]: Updated.

File: base/regex.jl [hunk 36]
```diff
@@ -212,14 +212,18 @@ julia> hr
...
 ```
 """
-struct RegexMatch <: AbstractMatch
-    match::SubString{String}
-    captures::Vector{Union{Nothing,SubString{String}}}
+struct RegexMatch{S<:AbstractString} <: AbstractMatch
+    match::SubString{S}
+    captures::Vector{Union{Nothing,SubString{S}}}
     offset::Int
     offsets::Vector{Int}
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/regex.jl:219]: I see what you're saying, but I'm inclined to think this should be touched in another PR.

[the remark this answers is not in the document]
Comment (tecosaur) [reply base/regex.jl:219]: I see what you're saying, but I'm inclined to think this should be touched in another PR.

[the remark this answers is not in the document]
Comment (LilithHafner) [reply base/regex.jl:219]: I mistakenly thought you added those fields in this PR; I agree with you.

**Comment by PallHaraldsson** [comment]
>There's no longer any name conflict concern now that styling will be split off into a stdlib, i.e. the styling macro is only available after using StyledStrings.

In that case could you, i.e. should you just go with S"content"? I know it's used in some obscure package, and even so both can be used. It would be a bit awkward, I think ok, since would this very likely not be used with that Quantum computing) package if I recall?

I think I agree with the proposed styled (or S) rather than style so will you at least consider that (too)? That is, if you no longer like that single letter S (usable inmost cases, I could believe, except when you would need Base.S).

**Comment by gbaraldi** [comment]
The issue is that `s"string"` is already a thing (SubstitutionString), so I would be concerned that it's easy to typo one into the other, and still get some kind of string out, though the wrong one.

**Comment by tecosaur** [comment]
Regarding `S""`/`s""`, substitution strings only appear in very specific contexts, I personally find they look different enough, and error messages complaining about type should make it pretty obvious I think.

I still consider `S""` to be the nicest option that's been raised so far (other than `🌈""`, which is great fun :grin: but too annoying to type), I'm just not sure that it's worth fighting for.

File: base/strings/util.jl [hunk 37]
```diff
@@ -458,13 +458,15 @@ function lpad(
     s::Union{AbstractChar,AbstractString},
     n::Integer,
     p::Union{AbstractChar,AbstractString}=' ',
-) :: String
+)
+    stringfn = if any(isa.((s, p), Union{TaggedString, TaggedChar, SubString{<:TaggedString}}))
+        taggedstring else string end
```
Comment (vchuravy) [inline base/strings/util.jl:463]: This is a bit of a code-smell to me.

Could this be a dispatch on `string`?

File: test/choosetests.jl [hunk 38]
```diff
@@ -151,7 +151,7 @@ function choosetests(choices = [])
 
     filtertests!(tests, "unicode", ["unicode/utf8"])
     filtertests!(tests, "strings", ["strings/basic", "strings/search", "strings/util",
-                   "strings/io", "strings/types"])
+                   "strings/io", "strings/types", "strings/tagged"])
```
Comment (vchuravy) [inline test/choosetests.jl:154]: also test that `make -C test StyledStrings` works. I think there is a list of stdlibs in here somewhere.

File: base/strings/util.jl (hunk 37 above)
Comment (tecosaur) [reply base/strings/util.jl:463]: Could you elaborate on what you mean by "dispatch on `string`"?

Comment (vchuravy) [reply base/strings/util.jl:463]: should `string(args...)` with `any(a isa Union{TaggedString, TaggedChar, SubString{<:TaggedString}}) for a in args)` just be, taggedstring? Instead of `taggedstring` being a new function.

The kinds of `isa` check you are doing seems to be something that we normally express in dispatch.

Comment (tecosaur) [reply base/strings/util.jl:463]: I asked this during the triage call, the comment was that I shouldn't violate `string(xs...)` returning a `String`. That said `string(x)` will return any `AbstractString` not string :shrug:

File: test/choosetests.jl (hunk 38 above)
Comment (tecosaur) [reply test/choosetests.jl:154]: Yep, it does work. I see that a few of the tests to need to be updated though: I may have forgotten about them in the rename :sweat_smile:.

File: base/strings/util.jl (hunk 37 above)
Comment (tecosaur) [reply base/strings/util.jl:463]: I'm happy to do whatever, just so long as I'm not told to undo it :stuck_out_tongue:

File: test/choosetests.jl (hunk 38 above)
Comment (tecosaur) [reply test/choosetests.jl:154]:
```

00:28:02 ❯ make -C test StyledStrings
make: Entering directory '/home/tec/Documents/Projects/julia/test'
    JULIA test/StyledStrings
Running parallel tests with:
  nworkers() = 1
  nthreads() = 18
  Sys.CPU_THREADS = 20
  Sys.total_memory() = 31.147 GiB
  Sys.free_memory() = 14.820 GiB

Test      (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
StyledStrings  (1) |        started at 2023-10-06T00:28:05.044
StyledStrings  (1) |     1.17 |   0.01 |  0.9 |     115.34 |   385.13

Test Summary: | Pass  Total  Time
  Overall     |   84     84  2.1s
    SUCCESS
make: Leaving directory '/home/tec/Documents/Projects/julia/test'
```

There we go :slightly_smiling_face:

**Comment by jariji** [comment]
Is it worth thinking about `lazy""` styled strings? Currently we have

```
  lazy"str"


  Create a LazyString using regular string interpolation syntax. Note that interpolations are evaluated at LazyString
  construction time, but printing is delayed until the first access to the string.
```

**Comment by jariji** [comment]
Re https://github.com/JuliaLang/julia/pull/49586#issuecomment-1721785073 I don't think the current syntax proposal can work, because it conflicts with the established format-string syntax. `{a:x}` can mean `{content:format}` or `{style:content}`. 

If a syntax _like_ this is desired, it could be `{style^content}` or `{content:style=red}` or `{content:@red}` or something else.

**Comment by PallHaraldsson** [comment]
>nicest option that's been raised so far (other than 🌈"", which is great fun 😁 but too annoying to type)

There is precedence for an emoji in Mojo, for it's file type... plus allowing ASCII. I'm not seriously suggesting the rainbow only; or as a synonym though, but something to consider. [Mojo 0.4.0 with at least one minor breaking change is out, "2 seconds" ago, then I saw it a few minutes ago, so it reminded me.]

**Comment by tecosaur** [comment]
@jariji with opinions like these, you should have been on the call :wink:.

> Is it worth thinking about `lazy""` styled strings?

I don't think so.

> is it correct to assume that potential changes to styled string syntax (the `{style:text}` thingy) are possible in the future without Julia 2.0

@aplavin potentially, but I don't see it as likely.

> Re https://github.com/JuliaLang/julia/pull/49586#issuecomment-1721785073 I don't think the current syntax proposal can work

@jariji :raised_eyebrow: that's a bit strong. I'd contend that it currently _is_ "working".

It's also worth taking note of the point from the triage meeting about disallowing un-escaped colons in styled content, to allow for `{styles:content:formatting}` in the future. E.g. `{:$(pi):.3f}`. The syntax here cannot mirror python's f-strings because _these are not doing the same thing_.

**Comment by jariji** [comment]
The current proposal conflicts with f-strings syntactically on the interpretation of `{a:x}`, and privileges styling over formatting by putting styling first, requiring an extra colon for formatting. If a formatting syntax is going to be in the stdlib, I'd rather formatting get design priority rather than fitting it in around styling syntax.

String formatting is much more common than styling in programming, and has a widely used syntax so its design space is quite constrained; the styling syntax is wide open. If Formatting.jl, Format.jl, PyFormattedStrings.jl, Fmt.jl all want to do their common job one way, it rather undermines them by pulling a conflicting syntax into the stdlib ahead of them.

File: base/strings/tagged.jl [hunk 39]
```diff
@@ -0,0 +1,357 @@
+# This file is a part of Julia. License is MIT: https://julialang.org/license
+
+"""
+    TaggedString{S <: AbstractString} <: AbstractString
+
+A string with annotated regions (often styling information).
+
+More specifically, this is a thin wrapper around any other [`AbstractString`](@ref),
+allows arbitary tagged values to be attached to regions of the wrapped string.
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:9]: The string is annotated with tagged values. The language needs to be updated for consistency/clarity.

File: base/strings/tagged.jl [hunk 40]
```diff
@@ -0,0 +1,357 @@
...
+
+Each tag takes the form of a `Pair{Symbol, <:Any}`, the first value being the
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:11]: Yep, this is another case of language needing to be updated for clarity.

File: base/strings/tagged.jl [hunk 41]
```diff
@@ -0,0 +1,357 @@
...
+    string::S
+    properties::Vector{Tuple{UnitRange{Int}, Pair{Symbol, Any}}}
+end
+
+"""
+    TaggedChar{S <: AbstractChar} <: AbstractChar
+
+A Char annotated with tags.
+
+More specifically, this is a thin wrapper around any other [`AbstractChar`](@ref),
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:45]: "thin" in the sense of complexity not bytes, we could always get rid of that word though.

File: base/strings/tagged.jl [hunk 42]
```diff
@@ -0,0 +1,357 @@
...
+"""
+struct TaggedString{S <: AbstractString} <: AbstractString
+    string::S
+    properties::Vector{Tuple{UnitRange{Int}, Pair{Symbol, Any}}}
+end
+
+"""
+    TaggedChar{S <: AbstractChar} <: AbstractChar
+
+A Char annotated with tags.
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:43]: Mmmm, probably good to have an elaboration in one place and link to it.

File: base/strings/tagged.jl [hunk 43]
```diff
@@ -0,0 +1,357 @@
...
+
+```julia
+TaggedChar(s::S) -> TaggedChar{S}
+TaggedChar(s::S, properties::Vector{Pair{Symbol, <:Any}})
+```
+
+# Examples
+
+```jldoctest
+julia> TaggedChar('j', :tag => 1)
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:68]: Yep, `textproperties`.

File: base/strings/tagged.jl [hunk 44]
```diff
@@ -0,0 +1,357 @@
...
+==(a::TaggedString, b::AbstractString) = isempty(a.properties) && a.string == b
+==(a::AbstractString, b::TaggedString) = isempty(b.properties) && a == b.string
+
+"""
+    taggedstring(values...)
+
+Create a `TaggedString` from any number of `values` using their
+[`print`](@ref)ed representation.
+
+This acts like [`string`](@ref), but takes care to preserve any properties
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:160]: Some unification is probably in order. It's not completely senseless though. We have a string with properties, those properties annotate the string with tags applied to certain regions.

File: base/strings/tagged.jl [hunk 45]
```diff
@@ -0,0 +1,357 @@
...
+
+# TODO implement `replace(::TaggedString, ...)`
+
+## End AbstractString interface ##
+
+"""
+    textproperty!(str::TaggedString, [range::UnitRange{Int}], tag::Symbol, value)
+    textproperty!(str::SubString{TaggedString}, [range::UnitRange{Int}], tag::Symbol, value)
+
+Add `tag` with `value` in `str`, over `range` if specified or the whole
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:302]: Not really, though the `Pair{Symbol, <:Any}` is really a tagged value (`:tag => value`). An editing pass for consistency/clarity seems like a good idea though.

File: base/strings/tagged.jl [hunk 46]
```diff
@@ -0,0 +1,357 @@
...
+    (textproperty!(s.string, s.offset .+ (range), tag, value); s)
+
+textproperty!(s::SubString{<:TaggedString}, tag::Symbol, value) =
+    (textproperty!(s.string, s.offset .+ (1:s.ncodeunits), tag, value); s)
+
+"""
+    textproperties(s::TaggedString, i::Integer)
+    textproperties(s::SubString{TaggedString}, i::Integer)
+
+Get the text properties that apply to `s` at index `i`.
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:333]: More or less.

File: base/strings/tagged.jl [hunk 47]
```diff
@@ -0,0 +1,357 @@
...
+## End AbstractString interface ##
+
+"""
+    textproperty!(str::TaggedString, [range::UnitRange{Int}], tag::Symbol, value)
+    textproperty!(str::SubString{TaggedString}, [range::UnitRange{Int}], tag::Symbol, value)
+
+Add `tag` with `value` in `str`, over `range` if specified or the whole
+string otherwise.
+"""
+function textproperty!(s::TaggedString, range::UnitRange{Int}, tag::Symbol, val)
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:305]: _Maybe_, I'm not quite sold though.

**Comment by tecosaur** [comment]
> The current proposal conflicts with f-strings syntactically on the interpretation of {a:x}, and privileges styling over formatting by putting styling first, requiring an extra colon for formatting. If a formatting syntax is going to be in the stdlib, I'd rather formatting get design priority rather than fitting it in around styling syntax.

Yes, because this PR doesn't provide any string formatting capabilities. This PR _is not about string formatting_ (which is part of why I find the reoccurring comparisons to f-strings etc. unhelpful).

I just see that in the future it might be nice to be able to do formatting and styling at the same time, and so I'm being careful to leave space for that capability by allowing for `{style:content:fmt}`.

> String formatting is much more common than styling in programming, and has a widely used syntax so its design space is quite constrained; the styling syntax is wide open.

Indeed, which is why the styling syntax choices doesn't "conflict" with f-strings...

> `{a:x}` can mean `{content:format}` or `{style:content}`

No, that's just `{style:content}`. If you want format and no styling you need to do `{:content:format}`.

> If a syntax like this is desired, it could be `{style^content}` or `{content:style=red}` or `{content:@red}` or something else.

I can't say I'm a fan of any of those, unfortunately. `^` is a weird delimiter, I don't think `style=red` works because of the various style forms. `@`-prefixing seems the least bad, but I'm not sure it works out for all forms.

If you'd like to seriously propose an alternative, it would be helpful if you could come up with a fully-formed proposal given the very late stage this PR is at, and then either convince me it's worth going to the (significant) effort of re-implementing and re-verifying or find someone else willing to do so.

File: base/strings/tagged.jl (hunk 41 above)
[the remark this answers is not in the document]
Comment (Tokazama) [reply base/strings/tagged.jl:45]: How about "simple" instead of "thin"

File: base/strings/tagged.jl (hunk 44 above)
[the remark this answers is not in the document]
Comment (Tokazama) [reply base/strings/tagged.jl:160]: Maybe the ship has sailed on this but I'd call this metadata not tags.

File: base/strings/tagged.jl (hunk 41 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:45]: Sounds good to me :+1:

File: base/strings/tagged.jl (hunk 44 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:160]: This is metadata, the use of phrases like "tagged regions" is an effort to describe the form the metadata takes and how it is applied.

File: base/strings/tagged.jl (hunk 41 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:45]: Changed.

File: base/strings/tagged.jl (hunk 42 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:43]: Reworded.

**Comment by tecosaur** [comment]
On another topic, prompted by the recent review by Alex Plavin, I'm thinking it could be a good idea to reduce the terminology from "Tags"/"Annotations"/"Properties" to just "Tags"/"Annotations" and in line with that rename:

- `textproperties` → `annotations`
- `textproperty!` → `annotate!`

I'm liking the idea of this rename, as it seems like the least awkward/most descriptive naming option that's come to mind. Let me know what you think, or even just :+1: / :-1: reacts to indicate if this sounds good would be appreciated.

**Comment by jkrumbiegel** [comment]
Why Tags and Annotations? To me, Tags sounds sufficient. Annotations evoke text descriptions, and I don't think that's quite accurate. Tags could be anything as you typed those content fields `Any` on purpose. So `tags` and `tag!`?

**Comment by tecosaur** [comment]
To me "annotation" is just a particularly good fit for how I see this feature. The way Wikipedia puts it meshes well with my own understanding of the word:

> An annotation is extra information associated with a particular point in a document or other piece of information.

In this way, a string is _annotated_ with _tagged values_ to produce a `TaggedString`.

IMO the key aspect of "annotation" that "tag" doesn't have is the sense of applying to a particular position/region. Usually when I think of "tagging" something it's tagging the entire object ("tag a file", "tag a suitcase", etc.).

File: base/strings/tagged.jl (hunk 39 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:9]: Have tweaked.

File: base/strings/tagged.jl (hunk 40 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:11]: Tweaked.

File: base/strings/tagged.jl (hunk 44 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:160]: Tweaked.

File: base/strings/tagged.jl (hunk 46 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:333]: So, look like I'll probably change this to annotations.

File: base/strings/tagged.jl (hunk 47 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:305]: See the current conversation on using `annotations` / `annotate!`.

File: base/strings/tagged.jl (hunk 45 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/tagged.jl:302]: Tweaked this.

**Comment by jkrumbiegel** [comment]
One more suggestion, what about `attach` and `attachment`? That to me sounds less like text and more like something arbitrary that is connected to something else at a certain point. If not, I'm also ok with annotation, it's not the critical point of this PR.

**Comment by PallHaraldsson** [comment]
There are pros and cons to merging this.

I haven't had time to review, trusting others, nor do I know the real need and issues of this, vs. having this in a fully external package. It's about color/styles strings, and we do have color already in the REPL, so if this is only for Julia then not a huge need to add this?

I'm thinking can we merge this but mark this new stdlib Experimental, at least for a while. It seems urgent to me to merge this if we want to have this as part of the API, and then backport to 1.10 (likely new LTS).

But I want to have it both ways, in case this isn't a good idea, or at least needs some changes. So I don't want to commit to the exact API.

Color is of course important to those of us not colorblind, but one question, will this package help at all with GUIs? If they would handle color differently, making this all redundant, this doesn't seem hugely important to most users.

I want to change and simplify string handling in Julia. I don't really like Char or AbstractString. I would want to just by able to type my strings as String in structs. That will not be slower even with this new stdlib, but will rule out its use(?).

If I go with AbstractString in my struct then they are slower, since Julia needs to dynamically make sure they are strings, and follow a pointer (will either way, since strings are variable length, but in my replacement string type this would not be needed, they stored inline, with no pointer; followed unless the string large).

I'm not sure how Julia handles this, but since you subtype AbstractString, does that mean use of Strings will get slower, since there are more subtypes to go through, exclude? Does it make sense for you to NOT subtype AbstractString? In my ideal world it would go away, if only one good type is available for strings (plus SubString, that may possibly also be merged), and with my type I think I could kill of all competitors.

**Comment by LilithHafner** [comment]
What if the string were annotated with annotations?

**Comment by ParadaCarleton** [comment]
> There are pros and cons to merging this. E.g. even if not bloating the sysimage (and startup time of Julia), it will add to what PackageCompiler.jl will distribute(?). Even if you don't use the functionality. It has an opt-in way to exclude stdlibs, I think all, or a list of, still, it's a manual step many users will not know of or go through.

Users who don't know how to go through this step probably aren't that worried about how big the sysimage is, but this is very small either way :)

> Color is of course important to those of us not colorblind, but one question, will this package help at all with GUIs? If they would handle color differently, making this all redundant, this doesn't seem hugely important to most users.

It should make UI code substantially easier. Right now, pretty-printing is a bit of a pain, which is what StyledStrings aim to fix.

> I want to change and simplify string handling in Julia. I don't really like Char or AbstractString. I would want to just by able to type my strings as String in structs. That will not be slower even with this new stdlib, but will rule out its use(?).

I think this is a real pain point but more related to the lack of concrete inheritance in Julia and the clunkiness of the `Abstract` convention than anything else. I'd much prefer a keyword or like `^String` (short for supertype of `String`), but . Using `String` instead of `AbstractString` is incorrect even now, since there are e.g. StaticStrings.

> I'm not sure how Julia handles situations like AbstractString currently, but since you subtype AbstractString, does that mean use of `String`s will get slower (or only after `using StyledStrings`), since there are more subtypes to go through, exclude?

This won't have any performance effects.

**Comment by serenity4** [comment]
> Color is of course important to those of us not colorblind, but one question, will this package help at all with GUIs? If they would handle color differently, making this all redundant, this doesn't seem hugely important to most users.

Yes, a lot. When rendering rich text, you need to handle many attributes that may be associated with portions of text (bold?, italic?, strikethrough?, underlined?, color, font, size...). This PR helps in that regard as we then have a streamlined way of working with annotated text; even if the style display that tagged strings bring to the REPL via printing may not be relevant for GUIs (they would use most likely use a custom rendering engine - except perhaps terminal-based UIs), the ability to easily attach attributes to sections of text with a principled API is very helpful. The rendering engine then no longer has to define its own API to represent attributes that users would interact with, and can instead focus on rendering the same data structures that would be used in other rendering contexts (e.g. printing text to the REPL instead of rendering a text widget).

**Comment by LilithHafner** [comment]
> I'm not sure how Julia handles situations like AbstractString currently

```julia
struct MyType{S <: AbstractString}
    x::S
end
```
Then `MyType{String}` and `MyType{AnnotatedString{String}}` are both concrete types (like `Vector{Int}`).

**Comment by tecosaur** [comment]
Julius, thanks for responding for my request for second opinions :slightly_smiling_face:. Attachment is an interesting idea, but feels further from what's actually going on that annotation does to me -- so with my thoughts and the :+1:s that message received I'm going to go ahead and change "text properties" to "annotations".

> There are pros and cons to merging this

We've already discussed this PR in triage, once in the general call then a special call just for this PR. My understanding is that this PR _is_ going to be merged, once I've made the changes discussed in the call (done) and updated the Docs to match (to do), unless there are any major revelations or oversights.

> Color is of course important to those of us not colorblind

And to those of us to are colourblind (I am not), being able to change the colours used I think would be a boon for accessibility.

-----

I'll push the terminology change in a sec, then I'll be working on the docs, and then ... we hit the merge button? Let me know if I've forgotten anything.

**Comment by PallHaraldsson** [comment]
>>There are pros and cons to merging this

>We've already discussed this PR in triage

I don't want it NOT merged (to get into 1.10).

You my point of mentioning cons, was bringing some up, but not to block merging, rather ask for Experimental, which you did not address:

>I'm thinking can we merge this but mark this new stdlib Experimental, at least for a while. [..]
>But I want to have it both ways

I'm not trying to single your code out, this could be a policy for all new code/API. It's not that I don't trust triage so much or any people involved. 

Regarding my question on GUIS, it seems confirmed this does not help for those (I meant desktop, even web or mobile GUI):
>may not be relevant for GUIs (they would use most likely use a custom rendering engine - except perhaps terminal-based UIs)

while this comment didn't seem to agree:
>It should make UI code substantially easier. Right now, pretty-printing is a bit of a pain, which is what StyledStrings aim to fix.

Most users may use the REPL, either alone or in VS Code, and this will help with text-based but I don't believe a huge priority. Would this help with e.g. Pluto?

This new functionality could have gone into its own external package, but if this were Julia itself then not, but I'm not aware of real (color) problems for the REPL. One argument for getting something into Julia is that it's only justified if it helps Julia. Another, is everything that helps a lot, or most of users ("batteries included argument", but then implementations need to be real good and not much change of them changing). I would like to excise a lot, and the REPL has been recently.

**Comment by serenity4** [comment]
> Regarding my question on GUIs, it seems confirmed this does not help for those (I meant desktop, even web or mobile GUI):
> > may not be relevant for GUIs (they would use most likely use a custom rendering engine - except perhaps terminal-based UIs)
>
> while this comment didn't seem to agree:
>
> > It should make UI code substantially easier. Right now, pretty-printing is a bit of a pain, which is what StyledStrings aim to fix.

You forgot the start of the sentence for the first quote:

> **even if the style display that tagged strings bring to the REPL via printing** may not be relevant for GUIs [...]

The annotation functionality introduced here *is* very useful, as mentioned in the other parts of that same comment. More convenient REPL printing is only part of what this PR brings, it is the rest that is of interest in the context of non-terminal-based GUIs.

The second quote is, I believe, referring to terminal-based UIs, and therefore agrees with the first one.

**Comment by PallHaraldsson** [comment]
>>I'm not sure how Julia handles situations like AbstractString currently

>struct MyType{S <: AbstractString}
>    x::S
>end

Exactly, but I want to do:
```
struct MyType
    x::String
end
```

since it's faster. I meant, that it is, and (e.g. for a vector of my type) an AbtractString can never be as fast. It's just not possible, the question is just how does Julia implement the slowness, slow or very slow.

>I think this is a real pain point but more related to the lack of concrete inheritance in Julia and the clunkiness of the Abstract convention than anything else.

No change in Julia could change the inherent slowness.

>Using String instead of AbstractString is incorrect even now, since there are e.g. StaticStrings.

I't snot wrong, per se. It's better to use AbstractString is function definitions yes (as opposed to String or none, i.e. Any). But it's worse for structs, thatn String. Yes then you can't point to `StaticString`s, but that's not the point of them. They are to have inlined, i.e. make fast, which means you would use that type in the struct. The only reason to use AbstractString in structs is to allow all types, but that's not needed, since you can convert any to String. For my type you could say using String is worse in structs since it rules out using mine without conversion. But I'm aiming for one best type, that would go into Julia and replace String as the default.

My point in mentioning all this is, does use String in structs somehow conflict with the PR here?

**Comment by serenity4** [comment]
>  I'm not aware of real (color) problems for the REPL

The "problem", currently, is that styled output is a bit of a pain. Many don't want to take in external dependencies just for some pretty-printing, which is understandable, and then printing typically requires the use of `printstyled`, such as

```julia
struct T
  value::Any
end

function Base.show(io::IO, ::MIME"text/plain", x::T)
  printstyled(io, typeof(x); bold = true)
  print(io, '(')
  printstyled(io, "value"; color = :red)
  print(io, ": ")
  printstyled(io, x.value; italic = true)
  print(io, ')')
end
```

which I believe a `@style_str` (or whatever name ends up being merged) would enable to write as:
```julia
Base.show(io::IO, ::MIME"text/plain", x::T) = print(io, style"{bold:$(typeof(x))}({red:value}: {italic:$(x.value)})")
```

It is really convenient and IMHO well worthy of being built-in.

**Comment by PallHaraldsson** [comment]
>Many don't want to take in external dependencies just for some pretty-printing, which is understandable

Why I want this merged (with "Experimental")and upvoted a comment stating that. This is pain, but it's avoidable pain (with a dependency, so the question is maybe is this very useful for scripts, rather than multi-file apps). I mean nothing you can do in Julia can't NOT be done in a package (more or less, at least this), so any addition needs to be justified well.

**Comment by tecosaur** [comment]
> I'm not aware of real (color) problems for the REPL

@PallHaraldsson I'm getting a growing sense that you haven't read the initial message.

> However... styling is hard. Across Base and the package ecosystem we have a painful mixture of raw ANSI codes and an unsightly pile of printstyled lines. This isn't just ugly, this leads to reoccurring issues with incorrectly computed string lengths/padding and unterminated styling codes (e.g. https://github.com/JuliaLang/julia/pull/37568 and https://github.com/JuliaLang/julia/pull/45521).

**Comment by serenity4** [comment]
If I understand your concern about slowness, if you don't intend to both support `String` and `TaggedString` in `MyType` in this example, then you can keep using a single `String` field, avoiding type parameters for `MyType` (which may be inconvenient as you point out). You can always convert whatever `TaggedString` value comes in to a `String` if you don't care about tags.

A unique `String` type replacing `AbstractString` is not realistic given all the various kinds of strings out there.

And to clarify, not parametrizing your structs doesn't make them faster, it just makes it easier to avoid forgetting about parametrizing them to keep concrete types all the way.

**Comment by PallHaraldsson** [comment]
>A unique String type replacing AbstractString is not realistic given all the various kinds of strings out there.

Well I think it is (but I haven't thought styling through, and even if it should at some point be part of that string...), I know all strings including String are a compromize, so in some sense you're correct. But most users don't care and just use what the language provides e.g. String (or the awful C-strings in C and C++). With a one good compromize you can satisfy most (and the rest, very few can use other _concrete_ types or AbstractString, in structs).

>It is really convenient and IMHO well worthy of being built-in.

You former/status que example is actually very readable already. The latter this PR, is convenient, likely very good, was shorter not obviously otherwise better or for sure the only way to do this.

I took a look what's available in other languages, if Python has the same (I assume same or similar syntax, and if not the exact same syntax, then that would be considered a downside here). I'm not sure if I found the corresponding module, regarding color/style, but anyway, it's argualbe we should be able to do this since other languages have built-in:

>pprint is a Python module made to print data structures in a pretty way. It has long been part of the Python standard library, so installing it separately isn’t necessary. All you need to do is to import its pprint() function:
>[example printing JSON indented]
>
>pp() is just a wrapper around pprint(), and it’ll behave exactly the same way.
>
>Note: Python has included this alias since version 3.8.0 alpha 2.

At least this is a minimally moving target for API, i.e. with non-breaking addition pp().

**Comment by rafaqz** [comment]
@PallHaraldsson you are essentially arguing againsts all Base `AbstractArray` types. Clearly, we need those types, not just `Array`.

We also need non `String` `AbstractString`.

A styled string is much easier to compose than manually calling `printstyled`. It will be a very useful addition to the language.

**Comment by tecosaur** [comment]
For those that can't be bothered to read the initial statement, I think the reasons for inclusion can be fairly decently summed up as:

- Making it easier to do fancy styling
- Raising the bar on how fancy we can be
- Making styling composable
- Being able to do said fanciness in the standard library, and lowering how big a decision it is to use it in the wider ecosystem
- Entirely avoiding two classes of bugs that are easy to cause with the current state of affairs
- Providing a system that is versatile enough it can be used for more than just what you see here

**Comment by LilithHafner** [comment]
> Maybe I missed it, but still didn't see a definite answer of whether updating "styled string" syntax in the future would be non-breaking for Julia. Can anyone clarify it?

None of this will ever be a part of the Base API so once we have upgradable stdlibs, it will be possible to release StyledStrings 2.0 with breaking changes. How easily accessible 2.0 stdlibs will be in Julia 1.x is still an open question.

File: base/strings/tagged.jl [hunk 48]
```diff
@@ -0,0 +1,388 @@
...
+                    ┌───┸─────────┐
+  "this is an example tagged string"
+  └──┰────────┼─────┘      │
+     A        └───┰────────┘
+                  B
+```
+
+Each tagged value (`A`, `B`, and `C` in the above diagram) is applied to a
+`UnitRange` of a string consists of a `Pair{Symbol, <:Any}` where the `Symbol`
+"tag" is used to label `Any` "value".
```
Comment (kdheepak) [inline base/strings/tagged.jl:23]: This sentence probably needs to be reworded, right? I'm not able to follow quite exactly what it is trying to say here.

File: base/strings/tagged.jl [hunk 49]
```diff
@@ -0,0 +1,388 @@
...
+
+Tags to not need to be unique, the same region can be annotated with the same
```
Comment (kdheepak) [inline base/strings/tagged.jl:25]:
```suggestion
Tags do not need to be unique, the same region can be annotated with the same
```

File: base/strings/tagged.jl [hunk 50]
```diff
@@ -0,0 +1,388 @@
...
+tag multiple times.
+
+See also [`TaggedChar`](@ref), [`taggedstring`](@ref), [`annotations`](@ref), and
+[`annotate!`](@ref).
+
+!!! warning
+    While the constructors are part of the Base public API, the fields
+    of `TaggedString` are not. This it to allow for potential future
```
Comment (kdheepak) [inline base/strings/tagged.jl:33]:
```suggestion
    of `TaggedString` are not. This is to allow for potential future
```

**Comment by tecosaur** [comment]
Thanks for the reviews @kdheepak, I'll wait to see if CI succeeds now, and then incorporate your comments.

File: base/strings/tagged.jl (hunk 48 above)
Comment (tecosaur) [reply base/strings/tagged.jl:23]: Ah, yea. Does an "and" help much?

> Each tagged value (`A`, `B`, and `C` in the above diagram) is applied to a
`UnitRange` of the string, and consists of a `Pair{Symbol, <:Any}` where the `Symbol`
"tag" is used to label `Any` "value".

Comment (tecosaur) [reply base/strings/tagged.jl:23]: Alternative version:

> The above diagram represents a `TaggedString` where three ranges have been
annotated (labeled `A`, `B`, and `C`). Each annotation must take the form of a
`Pair{Symbol, <:Any}`, where a `Symbol` "tag" is used to label `Any` "value".

**Comment by tecosaur** [comment]
Ok, looks like there are two sources of CI errors at this point:
- A doctest error (easy to resolve)
- An error from the `misc` set??

```
Error in testset misc:
Test Failed at /cache/build/default-armageddon-2/julialang/julia-master/julia-573e6263ab/share/julia/test/misc.jl:1291
  Expression: isdefined(mod, v)
```

**Comment by PallHaraldsson** [comment]
Since the types are now TaggedString and TaggedChar, should the stdlib be named TaggedStrings too? And then T"content", getting around upper case S dilemma, and styled/style. I see at the top S_str vs "new `@styled_str` string macro" in NEWS, but neither in the code...

Otherwise, I'll repeat, I want this merged, on master, with "Experimental" since we want this into 1.10 too. On master this could of course change until it's released as stable, but then we're stuck with names, of the stdlib, T or S macro and all, so this better be good.

I don't like seeing Any in code, since there almost nothing you can assume about it, so is Pair{Symbol, Any} I see a mistake?

Note, @rafaqz I'm not arguing against this if marked "Experimental", then no anxiety. I'm doing the best I can reviewing this.

>you are essentially arguing againsts all Base AbstractArray types. Clearly, we need those types, not just Array.
>
>We also need non String AbstractString.

That's a food for thought. I'm not against AbstractString (only its overuse, I wasn't at first clear); or AbstractArray or Abstract anything in function definitions, i.e. multiple dispatch is awesome!

For structs however the same limitations apply for AbstractArray (and Any even more), i.e. it's slower. It doesn't matter much for typically huge `Array`s. You need a huge variety of array types (unlike for strings), e.g. sparse, but you would rarely mix types, e.g. sparse and sense in a vector or [Abstract]arrays.

When you want small arrays, e.g. 2x2 you want an external package for that, and you absolutely want it inlined in your struct, i.e. not use AbstractArray there.

**Comment by adienes** [comment]
>  I want this merged into 1.10

feature freeze for 1.10 was almost 4 months ago

**Comment by PallHaraldsson** [comment]
I suspect this will be backported to 1.10, 1.10.x x= 1 or 2. So, ok it doesn't need to be marked Experimental right away... if not backported soon. If this is really good, as claimed, I don't believe you do NOT want it backported to LTS. That would limit its use much in the (package) ecosystem?

**Comment by oscardssmith** [comment]
This will not be backported to 1.10

**Comment by LilithHafner** [comment]
> The current proposal conflicts with f-strings syntactically on the interpretation of {a:x}, and privileges styling over formatting by putting styling first, requiring an extra colon for formatting. If a formatting syntax is going to be in the stdlib, I'd rather formatting get design priority rather than fitting it in around styling syntax.

This is a reasonable concern. I imagine that if we add an f-string stdlib it will use a string macro other than `@styled_str` (e.g. it may use `@f_str`). Because of that, it may implement different precedence rules. It would be quite reasonable to have `f"{a:b}"` parse as format specifier, `f"{a:b:c}"` parse as both, and `f"{a:b:}` parse as style information. I think those design decisions should be addressed if and when f-strings are added to Julia and do not think this PR substantially restricts the available design space for that feature. Consequently, I do not believe this concern blocks this PR from merging.

File: base/exports.jl [hunk 51]
```diff
@@ -1087,8 +1087,15 @@ eval(Expr(:public,
     :Generator,
     :ImmutableDict,
     :OneTo,
+    :TaggedString,
+    :TaggedChar,
     :UUID,
 
+# Tagged strings
+    :textproperties,
```
Comment (LilithHafner) [inline base/exports.jl:1095]: > An error from the misc set??

`textproperties` is marked as public but not defined. It is causing the misc test failure.

Also, I don't think any of this should be part of the Base API (only the StyledStrings API), so Base should not mark any of these symbols as public. Symbol publicness, like export status, is on a per-binding basis, so it is different for Base to mark these as public than for StyledStrings to mark them as public.

File: base/strings/tagged.jl (hunk 48 above)
Comment (tecosaur) [reply base/strings/tagged.jl]: Used the alternative version.

File: base/strings/tagged.jl (hunk 49 above)
Comment (tecosaur) [reply base/strings/tagged.jl]: Thanks.

File: base/strings/tagged.jl (hunk 50 above)
Comment (tecosaur) [reply base/strings/tagged.jl]: Thanks.

File: base/exports.jl (hunk 51 above)
Comment (tecosaur) [reply base/exports.jl:1095]: Ah oops, that should be `taggedstring`.

Regarding what's public, I was under the impression that with regard to `TaggedString`s we wanted to just make public API enough that they could be used. `annotate!`/`annotations` is so that the fields of the struct itself don't need to be directly accessed.

**Comment by tecosaur** [comment]
Ok, so now it's just the `isdefined(mod, v)` thing that's making CI fail, but I thought I fixed the issue there? :thinking:

File: base/exports.jl (hunk 51 above)
Comment (LilithHafner) [reply base/exports.jl:1095]: Yes, you are right.

**Comment by LilithHafner** [comment]
> I thought I fixed the issue there? 🤔

`textproperties` is still marked as public.

**Comment by LilithHafner** [comment]
> In this way, a string is annotated with tagged values to produce a TaggedString.

I think that we should stick with a single term for this concept.

A string is annotated with annotations to produce an AnnotatedString.

or

A string is tagged with tags (tagged values) to produce a TaggedString.

For public names, I prefer the names (in this order)

1) `AnnotatedString`, `AnnotatedChar`, `annotatedstring`, `annotate!`, `annotations`
2) `TaggedString`, `TaggedChar`, `taggedstring`, `tag!`, `tags`
3) `TaggedString`, `TaggedChar`, `taggedstring`, `add_tag!`, `get_tags`
4) `TaggedString`, `TaggedChar`, `taggedstring`, `annotate!`, `annotations` (current)

1–3 are all pretty similar, but I don't like 4 as much.

**Comment by tecosaur** [comment]
> `textproperties` is still marked as public.

I guess this is what I get for rebasing + conflict resolving at 3 in the morning :sweat_smile: (I might be just a little desperate to bring this odyssey to a close).

> I think that we should stick with a single term for this concept.

Eh, I see the attraction here but I have to say after thinking on it so far I find the nuance conceptually helpful / a bit clearer.

> A string is annotated with annotations to produce an AnnotatedString.

Indeed, and the annotations take the form of tagged values.

I think the current docstring does a decent job of laying out how I see it.

> ```text
>                         C
>                     ┌───┸─────────┐
>   "this is an example tagged string"
>   └──┰────────┼─────┘      │
>      A        └───┰────────┘
>                   B
> ```
> 
> The above diagram represents a `TaggedString` where three ranges have been
> annotated (labeled `A`, `B`, and `C`). Each annotation must take the form of a
> `Pair{Symbol, <:Any}`, where a `Symbol` "tag" is used to label `Any` "value".
> 
> Tags do not need to be unique, the same region can be annotated with the same
> tag multiple times.

> For public names, I prefer the names (in this order)
>  [...]

My preferences: 4, 1, 2, 3

**Comment by jkrumbiegel** [comment]
Hm from your own description I would then think `AnnotatedString` where there are annotations that consist of a Symbol `label` paired to a `value`. I don't really see why `tag` is needed as an additional concept. It doesn't really add anything over `annotation` especially if the tag is just the label part of the annotation, so it's less important.

**Comment by tecosaur** [comment]
Lilith/Julius: Mmmm, I'm coming around to "label" being a more helpful term than "tag".

Alex: On annotate-y functions already being written somewhere else, two things come to mind.
- These symbols are currently *not* exported from Base
- If you think something better could be used, please suggest it

**Comment by LilithHafner** [comment]
In support of 2.1b: I think it is acceptable to add methods as long as you are interpreting the method name according to the same definition of the word.

Annotate (verb)
1. add notes to (a text or diagram) giving explanation or comment.

If Plots.annotate! adds notes to a diagram and Base.annotate! adds notes to a string, then they can share a function.

Run (verb)
3. extend or cause to extend in a particular direction.
7. be in or cause to be in operation; function or cause to function.

If CAD.run used definition 3 to extend an existing element further and Base.run uses definition 7 to start a command or task, then they cannot (should not) share a function.

**Comment by tecosaur** [comment]
I'm going to assume that the Libdl/LibCURL/ccall errors in CI are unrelated to this PR.

File: test/strings/tagged.jl [hunk 52]
```diff
@@ -0,0 +1,99 @@
+# This file is a part of Julia. License is MIT: https://julialang.org/license
+
+@testset "TaggedString" begin
+    str = Base.TaggedString("some string")
+    @test str == Base.TaggedString(str.string, Tuple{UnitRange{Int64}, Pair{Symbol, Any}}[])
```
Comment (LilithHafner) [inline test/strings/tagged.jl:5]:
```suggestion
    @test str == Base.TaggedString(str.string, Tuple{UnitRange{Int}, Pair{Symbol, Any}}[])
```

Comment (tecosaur) [reply test/strings/tagged.jl:5]: Ah yep, thanks :)

**Comment by tecosaur** [comment]
So, I'm thinking maybe I should:
- Rename `TaggedString` to `AnnotatedString`
- Replace references to "tags" in docstrings etc. with "labels"

Would that make people happier about the naming scheme?

**Comment by tecosaur** [comment]
I'd also really like to go for something shorter than `styled""`, but I seem to have a hard time convincing people it's worth it 🫤.

**Comment by jkrumbiegel** [comment]
> I'd also really like to go for something shorter than styled""

I think shorter would be better for this as well, as you will probably create a bunch of them when you use this stdlib. On the other hand, short like `S""` is going to conflict with other packages more easily as in, other packages are going to be defining this as well. A real conflict only appears if this is default-exported, though. As long as it isn't, I don't see a problem with choosing the shorter name. I think an argument pro shorter name is that redefining macro names is a bit annoying (as you showed above, you have to use `var"` syntax so users are probably not going to do this on their own.

**Review by kdheepak — COMMENTED** [review]
Some minor comments. Excited for this feature to land! Thanks for all your work on it!

File: NEWS.md [hunk 53]
```diff
@@ -43,6 +48,16 @@ New library features
 Standard library changes
 ------------------------
 
+#### StyledStrings
+
+* A new standard library for handling styling in a more comprehensive and structured way.
+* The new `Faces` struct serves as a container for text styling information
+  (think typeface), and comes with a framework to provide a convenient,
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply NEWS.md:55]: To try to preserve the connection and brevity (one or two people asked "why is this called Face?" or similar early on), how do you find `(think typeface, as well as color and decoration)`?

File: NEWS.md [hunk 54]
```diff
@@ -8,6 +8,11 @@ New language features
   difference between `public` and `export` is that `public` names do not become
   available when `using` a package/module. ([#50105])
 * `ScopedValue` implement dynamic scope with inheritance across tasks ([#50958]).
+* A new `AbstractString` type, `TaggedString`, is introduced that allows for
+  (arbitrary) regional annotations to be attached to an underlying string. This is
+  very useful for allowing styling information to be encoded separately, and is
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply NEWS.md:13]: Rephrased to: `This type is particularly useful for holding styling information,`

File: base/strings/basic.jl [hunk 55]
```diff
@@ -309,7 +318,8 @@ end
     ==(a::AbstractString, b::AbstractString) -> Bool
 
 Test whether two strings are equal character by character (technically, Unicode
-code point by code point).
+code point by code point). Should either string be a [`TaggedString`](@ref) the
+string properties must match too.
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply base/strings/basic.jl:322]: This is a less clear improvement to me (compared to the other suggestions).

File: doc/src/manual/strings.md [hunk 56]
```diff
@@ -1203,3 +1203,51 @@ Notice that the first two backslashes appear verbatim in the output, since they
...
+julia> typeof(lpad(str, 7))
+Base.TaggedString{String}
+
+julia> str2 = Base.TaggedString(" julia", [(2:6, :face => :magenta)])
+" julia"
+
+julia> Base.taggedstring(str, str2)
+"hello there julia"
+
+julia> str * str2 == Base.taggedstring(str, str2) # *-concatination still works
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply doc/src/manual/strings.md:1247]: Ah, yep.

File: NEWS.md (hunk 53 above)
[the remark this answers is not in the document]
Comment (kdheepak) [reply NEWS.md:55]: That would read better for me!

File: base/strings/basic.jl (hunk 55 above)
[the remark this answers is not in the document]
Comment (kdheepak) [reply base/strings/basic.jl:322]: This was the only sentence in there that made me trip up and have to re-read it, but that might just be me :)

File: NEWS.md [hunk 57]
```diff
@@ -8,6 +8,11 @@ New language features
   difference between `public` and `export` is that `public` names do not become
   available when `using` a package/module. ([#50105])
 * `ScopedValue` implement dynamic scope with inheritance across tasks ([#50958]).
+* A new `AbstractString` type, `TaggedString`, is introduced that allows for
+  (arbitrary) regional annotations to be attached to an underlying string. This is
```
[the remark this answers is not in the document]
Comment (tecosaur) [reply NEWS.md:12]: Yep.

File: NEWS.md (hunk 53 above)
[the remark this answers is not in the document]
Comment (tecosaur) [reply NEWS.md:55]: Sold! :wink:

**Comment by LilithHafner** [comment]
> So, I'm thinking maybe I should:
> 
> * Rename `TaggedString` to `AnnotatedString`
> * Replace references to "tags" in docstrings etc. with "labels"
> 
> Would that make people happier about the naming scheme?

Yes to the first change.
For the second change, why change "tags" to "labels"? Are both terms currently in use in the documentation for this PR?

**Comment by tecosaur** [comment]
> For the second change, why change "tags" to "labels"? Are both terms currently in use in the documentation for this PR?

Currently it's just "tags", but I think these two are much of a muchness, so I'm happy to just go with whatever.

**Comment by jkrumbiegel** [comment]
> I'm happy to just go with whatever

Agreed, not that important, just that only one term is used consistently. I like `label` better 🤷‍♂️

**Comment by tecosaur** [comment]
Ok, so with regards to actually getting this merged, I'd think the `TaggedString` to `AnnotatedString` change would be fine to make without putting it through triage, but I'm not sure how to resolve the different opinions around what's a good/acceptable string macro.

**Comment by serenity4** [comment]
If I'm not mistaken, triage was OK with something, then issues about export conflicts came up. I think the main issue was that the macro would clash with other symbols; but that issue goes away with not exporting the macro from Base (requiring the stdlib to be explicitly loaded to trigger a conflict). Perhaps any potential conflicts are therefore acceptable now?

And given that we've changed the nomenclature from "styled" to "annotated", how about an `A"..."`/`a"..."` syntax? (instead of the original `S"..."`).

**Comment by serenity4** [comment]
Then to recap, I guess we need to resolve in order:
- Short vs long (`S""` vs `style""` )
- If long:
  - Name vs adjective (`style""` vs `styled""`)

**Comment by LilithHafner** [comment]
> And given that we've changed the nomenclature from "styled" to "annotated", how about an A"..."/a"..." syntax? (instead of the original S"...").

IIUC, the macro is specifically for constructing styled strings. If you want to make an annotated string with annotations unrelated to style, then this macro is probably not a great choice. This means it should still be named `s`, `S`, `style`, `styled` or somesuch even as the return type has shifted from `StyledString` to `TaggedString` to `AnnotatedString`.

In the past when I have come to the conclusion that triage made a bad API design decision and we should do something else instead I've brought it back up at a later traige and raised points the first triage didn't consider. I think it would be a good idea to bring `S`/`styled` back up at another triage; I'm not bold enough to merge `S` after last triage said `style`>`S`.

**Comment by tecosaur** [comment]
Well, given the next triage is in ~2 days perhaps it's best if I were to write up a short list of points around the `S""` / `styled""` decision that I think warrant a bit more head-scratching and then see what the decision is when I wake up.

**Comment by tecosaur** [comment]
> If you want to make an annotated string with annotations unrelated to style, then this macro is probably not a great choice.

I actually do think it works decently well for that too, `"{lang=en,pos=noun:word}"` "just works". Styling info is privileged by:
- a lone key being interpreted as `face=$key`
- a special "inline face" form

**Comment by tecosaur** [comment]
> Is there any discussion/motivation for choosing this specific syntax for the styling macro?

Discussion, no. The motivation is that particularly for short snippets of text, constructing a `AnnotatedString` manually is annoying, and so we want something more convenient or people won't use this as much. I came up with the syntax by looking around for something similar (couldn't find much), and then thinking about what I thought would work well.

> I don't see it in the docs anywhere, but would be great to have for such a major feature addition.

Would it really?

> Especially, comparing to existing and highly popular syntaxes like Python's `rich` package.

I had a look at `rich` and couldn't see any styling syntax, just https://rich.readthedocs.io/en/stable/text.html.

> Kinda weird to ignore existing styled string syntaxes that have been in the wild for quite some time.

# :raised_eyebrow:

With that said, two things:
1. It's worth noting that the syntax has at this point gone through triage without any objections
2. At this point, if you're interested in any changes to the syntax you'll need to do some combination of (a) convincing me/triage it's worth it, (b) creating a fully-formed proposal for an alternative or change from the current syntax, and possibly be willing to implement it.

**Comment by tecosaur** [comment]
Sounds like Triage didn't get a chance to actually get to the short-macro naming, so with that in mind this might be merged around the start of November?

**Comment by tecosaur** [comment]
Ah, glad to see you're not proposing I switch to a different syntax :sweat_smile:. I might be slightly sensitized to incomplete change-of-syntax suggestions...

With the string concatenation example, that also mentions why it's included

> While `*` may seem like a surprising choice to users of languages that provide `+` for string concatenation [...]

I'm not sure that of the people that read the `StyledStrings` docs that many of them will be familiar with `rich`'s syntax (which is unlike `*` vs. `+` a syntax that doesn't go across languages/well-known packages), so I'm not sure I see nearly as strong a motivation to include a rationale.

Put another way, since such a rationale would be more than a sentence or two I'm suspicious of whether it would provide enough value to enough readers to be worthwhile.

That said, we could do a short explanation like:

> This RTF-like syntax uses `{`/`}` delimited styled regions in part because it is a nicer match to the underlying representation, and avoids the need to repeat information when closing a styled region.

With that last part, it's effectively a tradeoff:
- Rich's BBcode-y style works better for interleaved styling (arguably)
  - bbcode-y: `[bold]hey [italic]there [/bold] you[/italic]`
  - sxml-y: `{bold:hey }{bold,italic:there }{italic:you}`
    - NB: This is converted into an interleaved representation at parse-time
- This sxml-y style works better for non-interleaved styling
  - bbcode-y: `[bold red] ! [/bold] Warning:[/red] [italic]Something worrying[/italic]`
  - sxml-y: `{red: {bold:!} Warning:} {italic:Something worrying}`
  
Aside from the technical considerations, I've also formed the view that the RTF-y/sxml-y form is a better syntactic compromise.

**Comment by kdheepak** [comment]
Regarding the discussion around `S""` / `styled""`, what do you think about calling it either `f""` / `format""` / `F""` / `fmt""` instead? 

"Formatting" is a common term used to describe bold / italic / colors etc in text editing AND because this PR would allow for a conventional (in programming languages) string formatting functionality in the future, a name based on "formatting" could be a reasonable choice. This kind of name would also avoid any confusion with `s""`, so the short-hand name is easier to justify. Also, I think it helps that `f""` style syntax is common in Python (and other languages?) for formatting.

**Comment by Tokazama** [comment]
There's been a lot of discussion around terminology and syntax. I typically don't have strong feelings when it comes to that sort of thing, but I do think we should be conscientious of how much syntax and terminology this addition is taking on. We have "face", "style", "tag", and "annotate". These are all pretty common terms but I imagine the definitions here won't line up with everything else. For example, some aren not pleased with base exporting `position` (https://github.com/JuliaLang/julia/issues/33799). 

(BTW, great work here and way to patiently facilitate the often arduous process of bike-shedding!)

**Comment by jkrumbiegel** [comment]
image

I read somewhere that this PR would enable italics, but for me it's underlined in both VSCode and iTerm2 on an M1 Mac. 

Also, as you can see nothing specifically happens when displaying a string with a nonexistent face. I'm not sure if that's a good default, shouldn't it error if you spell a face wrong (and then try to display it)?

**Comment by jkrumbiegel** [comment]
image

This should probably also not be a warning but an error, I don't like it if misspecified input is still handled in some way. If the colon needs to be escaped, it needs to be escaped.

**Comment by jkrumbiegel** [comment]
image

This could probably a bit friendlier, as it seems natural to interpolate a string into a string

**Comment by jkrumbiegel** [comment]
A bug with interpolation when styles are empty:

image

**Comment by tecosaur** [comment]
> Regarding the discussion around `S""` / `styled""`, what do you think about calling it either `f""` / `format""` / `F""` / `fmt""` instead?

@kdheepak  I'm open to it, and could see it making quite a bit of sense if/when formatting capability is actually added. Not completely sure though, for instance it seems less obvious to me that `StyledStrings` should export a  "format" macro than a "styling" macro.

If we actually call this `f""` (or similar), I'd also think we might want to think about making formatting values more convenient. Instead of `{:$(a):fmt}` say `${:a:fmt}`, or similar. This is a bit more work, but might be worth it? I'm a bit wary of how much this is holding up other work already though (see #50817), at the very least I think I'd need help.

**Comment by tecosaur** [comment]
> There's been a lot of discussion around terminology and syntax. I typically don't have strong feelings when it comes to that sort of thing, but I do think we should be conscientious of how much syntax and terminology this addition is taking on. We have "face", "style", "tag", and "annotate". These are all pretty common terms but I imagine the definitions here won't line up with everything else. For example, some aren not pleased with base exporting position (#.33799).

@Tokazama right. Terminology is needed though, and I think a pretty major factor is that currently nothing is exported, and there are less things that even _could_ be exported from Base (just the types and `annotate!` / `annotations`).

> (BTW, great work here and way to patiently facilitate the often arduous process of bike-shedding!)

(thanks :slightly_smiling_face:)

**Comment by tecosaur** [comment]
> I read somewhere that this PR would enable italics, but for me it's underlined in both VSCode and iTerm2 on an M1 Mac.

@jkrumbiegel Hmm, the behavior there is determined by `haskey(Base.current_terminfo, :enter_italics_mode)`. This is either a terminfo related bug, or those terminals don't advertise italic support.

> Also, as you can see nothing specifically happens when displaying a string with a nonexistent face. I'm not sure if that's a good default, shouldn't it error if you spell a face wrong (and then try to display it)?

Because loss of styling is an aesthetic issue, and so IMO lesser than a "different string" -type issue, I'm feel the "skip faces that don't exist" behavior is reasonable.

> This should probably also not be a warning but an error, I don't like it if misspecified input is still handled in some way. If the colon needs to be escaped, it needs to be escaped.

I kind of like the idea that using this macro the only thing that will error is undefined variables / invalid interpolations.

Maybe it would be good to try for a stricter model? I"m not sure myself.

> Same for these (and there's a typo in extraneous). For these here it would also be really useful if they had the same "pointing" feature as the message above.

Hmm, we could probably indicate the start of the terminated styles.

> This could probably a bit friendlier, as it seems natural to interpolate a string into a string. At least the error could be more specific than a method error, with a suggestion to use Symbols which do work for this

Agreed on this being friendlier, not sure exactly what form that should take though myself.

> A bug with interpolation when styles are empty:

Ah yep, that'll need to be fixed.

**Comment by jkrumbiegel** [comment]
> Agreed on this being friendlier, not sure exactly what form that should take though myself.

Probably just throwing a more informative error suggesting what types are appropriate there

> Hmm, we could probably indicate the start of the terminated styles.

Would be worth it I think because that's one of the most common errors you're going to have with this I think, when you style some strings that happen to have curly braces.

> I kind of like the idea that using this macro the only thing that will error is undefined variables / invalid interpolations.

Have to disagree there :) While warnings seem friendlier at first, I think they bite you later when things run on CI for example. These invalid syntax errors are things that should mostly be trivial to fix for a user, so the benefit of "hey we're doing something half-correct for you so don't have to stop what you were doing" is not that large.

> Because loss of styling is an aesthetic issue, and so IMO lesser than a "different string" -type issue, I'm feel the "skip faces that don't exist" behavior is reasonable.

I would say a terminal swallowing color info because of some setting is an aesthetic issue, a face that you expect to be there not being there is not. Unless you anticipate your system should regularly have the situation that faces are disappearing, and it would be too annoying if things kept throwing errors, I think this classifies as a bug. Think about how much trouble the Documenter ecosystem had with half-broken docs because the thinking was, well an unreachable URL or a failing example is not a reason to completely break the build, right?

**Comment by tecosaur** [comment]
> Probably just throwing a more informative error suggesting what types are appropriate there.

Mmm, how I go about this will just take a little thought (i.e. where in the code I introduce a check, and how).

> Would be worth it I think because that's one of the most common errors you're going to have with this I think, when you style some strings that happen to have curly braces.

Got this working:

image

> Have to disagree there :) While warnings seem friendlier at first, I think they bite you later when things run on CI for example. 

Ok, yea, that's fairly convincing to me. I'll just need to see about making a new error type with a nice `showerror` method.

> I would say a terminal swallowing color info because of some setting is an aesthetic issue, a face that you expect to be there not being there is not. Unless you anticipate your system should regularly have the situation that faces are disappearing, and it would be too annoying if things kept throwing errors, I think this classifies as a bug.

So, one key consideration here is around "Unless you anticipate your system should regularly have the situation that faces are disappearing", I anticipate situations where you would want text to match the style of another package, should it be loaded. With this "soft-error" (nothing thrown, you just don't see styling from non-existent named faces), approach this can be done easily. Otherwise... I guess you could resort to a package extension that changes a global variable saying what faces should be used on load? But that seems uglier to me.

**Comment by tecosaur** [comment]
I'd also like to note that changes like those I've just done/mentioned can be made after merging. IMO the only "blocker" is picking the canonical styling macro name, because that would be slightly more annoying to change in stdlibs etc.

I would like to get this merged sooner rather than later because there are multiple pieces of work, not just from me, that are waiting on this. But I suppose we'll be waiting till at least the triage meeting in another week and a half for the macro naming to be put to bed.

**Comment by jkrumbiegel** [comment]
> So, one key consideration here is around "Unless you anticipate your system should regularly have the situation that faces are disappearing", I anticipate situations where you would want text to match the style of another package, should it be loaded. With this "soft-error" (nothing thrown, you just don't see styling from non-existent named faces), approach this can be done easily. Otherwise... I guess you could resort to a package extension that changes a global variable saying what faces should be used on load? But that seems uglier to me.

I still think that mechanism is kind of confusing, and I know there has been discussion on the `Faces` mechanism in the past. But I don't think it's good if I do styling in `Makie` where I use a face called `diffeq_custom_face` or so and leave it up to chance whether that's ever loaded or not, or if it changes in ways that I couldn't predict. This is basically the problem with the global faces storage, you cannot really make predictions about it. Rather than concluding from this that missing faces must be ignored when rendering, I would question the underlying reference mechanism again.

As far as I can tell, currently faces are special in that they are resolved as entries in the global dict when encountered in the styling macro. Couldn't we change that to a function call instead that resolves this in the current module? So `S"{someface:text}" would resolve to `CurrentModule._get_face_someface()` which the module owner can define somehow. And if they wanted to use other faces they could load them from other modules first maybe? Probably this mechanism would need convenience macros so you don't actually have to write `_get_face_someface` and so that there can't be name clashes. But I think if you rely on a face from another package, that should be handled like any other thing that you depend on, with a clear failure mode.

**Comment by PallHaraldsson** [comment]
>IMO the only "blocker" is picking the canonical styling macro name, because that would be slightly more annoying to change in stdlibs etc.

I think you can merge as is, after I guess, changing the top outdated comment, since this is blocking other work, and can be changed later. I assume 1.11 will not be released as stable anytime soon anyway, and this not backported to 1.10. I would like it marked experimental when it hits some stable version.

It seems the stdlib should be named AnnotatedStrings, but even that could be changed later, if I'm right or wrong. And the stdlib is not referenced here in the PR, except in doc part?

About outdated:
TaggedString
TaggedChar
[..]
@S_str

I'm not sure if you need to export any kind of Char from Base. If not strictly needed then I would want it skipped. And the macro, not defined here, should it me `@A_str`?

**Comment by tecosaur** [comment]
Having let this sit for a bit, I think there's some more consideration to do for how the styling macro is named and incorporates formatting. I think that would be best discussed in another round of changes after getting this feature in, so we can start doing things with the styling functionality in the meantime.

I'm thinking, if I just leave the name as `styled""` for now, I don't think there's actually anything that hasn't been approved by triage? Perhaps we just merge this as-is for now, and open another issue/PR to hash out the macro naming + syntax format/future-proofing?

The CI failure is unrelated (`Libdl`, `LinearAlgebra/diagonal`, `ccall`, and a JIT duplicate session error).

If possible, I'd want a chance to rebase just before merging so I could make the commit references in https://github.com/JuliaLang/StyledStrings.jl/commit/0dfde57f5a37bafe line up, but I suspect that thanks to the way GitHub does merges (not using `git merge`) that may not be possible.

**Comment by LilithHafner** [comment]
IIUC using the "Merge pull request" option will preserve commit hashes. It will perform a fast-forward if possible, and otherwise create a merge commit.

@tecosaur, after you rebase is this ready to merge from your end?

**Comment by tecosaur** [comment]
> after you rebase is this ready to merge from your end?

I've just done the rebase, and I think so! :crossed_fingers:

I suspect we'll want to make some more tweaks to this before 1.11 is cut, but what we have here now is pretty solid and cleared by triage, so I think we should be good to slap merge at long, long last 🙂.

**Comment by LilithHafner** [comment]
Thank you for your patience, perseverance, and contribution! I can't wait to see what folks build with this :)

**Comment by tecosaur** [comment]
For continued bikeshedding of formatting, please direct your attention to https://github.com/JuliaLang/StyledStrings.jl/issues/1 :slightly_smiling_face:.
