### PR TITLE
give finalizers their own RNG state

### LINKED ISSUE #42752: Heisenbug in "test guarded Random.seed!"
Just as a record, I saw:

```
Error in testset Test:
Test Failed at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.8/Test/test/runtests.jl:777
  Expression: orig == Random.default_rng()
   Evaluated: Xoshiro(0x947b9af2ba269897, 0x95ae8d9a31382b32, 0x8a532dc2baa61f2e, 0x7213512241a4dfbd) == TaskLocalRNG()
Error in testset Test:
Test Failed at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.8/Test/test/runtests.jl:778
  Expression: rand(orig) == rand()
   Evaluated: 0.6209946085911393 == 0.7846500004305739
```

https://build.julialang.org/#/builders/7/builds/4863/steps/5/logs/stdio

in #42725. It vanished after re-running the test by merging `master` even though there doesn't seem a change that could fix the result https://github.com/JuliaLang/julia/compare/a4903fd0e7882532b3329ab47888c3c051f868cc...76c243141a611da572bda3332f836b898998225f.

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #42752

### CODE REVIEW

File: src/gc.c [hunk 1]
```diff
@@ -396,9 +405,17 @@ static void run_finalizers(jl_task_t *ct)
...
+
+    uint64_t save_rngState[4];
+    memcpy(&save_rngState[0], &ct->rngState[0], sizeof(save_rngState));
+    memcpy(&ct->rngState[0], &finalizer_rngState[0], sizeof(save_rngState));
+
     // This releases the finalizers lock.
     jl_gc_run_finalizers_in_list(ct, &copied_list);
     arraylist_free(&copied_list);
+
+    memcpy(&finalizer_rngState[0], &ct->rngState[0], sizeof(save_rngState));
```
Comment (vtjnash) [inline src/gc.c:417]: This does not have the lock anymore? (and seems unnecessary)

File: src/init.c [hunk 2]
```diff
@@ -753,6 +753,8 @@ static NOINLINE void _finish_julia_init(JL_IMAGE_SEARCH rel, jl_ptls_t ptls, jl_
         JL_GC_POP();
     }
 
+    jl_gc_init_finalizer_rng_state();
```
Comment (vtjnash) [inline src/init.c:756]: Do we have a guarantee to have randomness by now? And not expect finalizers to attempt to need randomness before now?

Comment (vtjnash) [reply src/init.c:756]: sounds best to me

File: src/gc.c [hunk 3]
```diff
@@ -396,9 +405,17 @@ static void run_finalizers(jl_task_t *ct)
     }
     jl_atomic_store_relaxed(&jl_gc_have_pending_finalizers, 0);
     arraylist_new(&to_finalize, 0);
+
+    uint64_t save_rngState[4];
```
Comment (Keno) [inline src/gc.c:409]: Should this also apply to `jl_finalize_th`?

Comment (JeffBezanson) [reply src/gc.c:409]: I guess we should to be consistent, but it's not essential since it would appear explicitly in user code.

Comment (Keno) [reply src/gc.c:409]: Well, we should define what the semantics are regardless with a view towards #44056. If regular finalize doesn't do this, we do need a version that does for that purpose.

Comment (JeffBezanson) [reply src/gc.c:409]: We discussed this and decided that since explicit `finalize` is synchronous, it can just use the current task RNG as before. Since eager finalizer call insertion and finalizer inlining require `:notaskstate` (IIUC) this should be fine right?

**Review by vtjnash — APPROVED** [review]
