### PR TITLE
bugfixes for rsplit (for unicode and empty strings)

### LINKED ISSUE #26225: rsplit failure for multi-byte characters
```
julia> ö.<TAB>
┌ Error: Error in the keymap
│   exception =
│    StringIndexError("ö.", 2)
│    Stacktrace:
│     [1] string_index_err(::String, ::Int64) at ./strings/string.jl:7
│     [2] Type at ./strings/substring.jl:32 [inlined]
│     [3] Type at ./strings/substring.jl:38 [inlined]
│     [4] _rsplit(::String, ::String, ::Int64, ::Bool, ::Array{SubString{String},1}) at ./strings/util.jl:360
│     [5] #rsplit#338 at ./strings/util.jl:335 [inlined]
│     [6] #rsplit at ./<missing>:0 [inlined]
│     [7] complete_symbol(::String, ::getfield(REPL.REPLCompletions, Symbol("##15#17"))) at /Users/kristoffer/julia/usr/share/julia/site/v0.7/REPL/src/REPLCompletions.jl:47
│     [8] completions(::String, ::Int64) at /Users/kristoffer/julia/usr/share/julia/site/v0.7/REPL/src/REPLCompletions.jl:619
│     [9] complete_line(::REPL.REPLCompletionProvider, ::REPL.LineEdit.PromptState) at /Users/kristoffer/julia/usr/share/julia/site/v0.7/REPL/src/REPL.jl:341
│     [10] complete_line(::REPL.LineEdit.PromptState, ::Int64) at /Users/kristoffer/julia/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:310
│     [11] complete_line(::REPL.LineEdit.MIState) at /Users/kristoffer/julia/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:301
....
└ @ REPL.LineEdit LineEdit.jl:2319
```

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #26225 (`rsplit` failure for strings with multi-byte Unicode characters).

Also, I noticed that `rsplit` was broken in both 0.6 and 0.7 for empty splitter strings: `split("abc", "")` gives `["a","b","c"]` (correct, I think — and there was a test for this so it was clearly the intended behavior), but `rsplit("abc", "")` on 0.6 incorrectly gives `["ab","c"]`.  In this PR, they both give `["a","b","c"]`, and the case with `limit=2` is also tested.

The new `rsplit` implementation is both more correct (I think) and shorter.

I also noticed that both `rsplit` and `split` were incorrectly(?) using `start(string)` to get `firstindex`.    Or is this always guaranteed to return `1`?

Finally, I simplified the `split`/`rsplit` tests by replacing `isequal` with `==`, since the two should be equivalent for strings.  `==` is more readable, allowed me to use chained comparisons, and gives better diagnostic output for `@test` failures.

### CODE REVIEW

**Comment by stevengj** [comment]
Is `firstindex(string)` guaranteed to always be `1` for all `AbstractString` types?  If so, the code could be simplified further.  If not, the `_split` implementation is wrong.

**Comment by stevengj** [comment]
CI failures seem unrelated.  Timeouts on FreeBSD and Win64, and `rmdir: Permission denied` on Win32.

Okay to merge?

File: base/strings/util.jl [hunk 1]
```diff
@@ -275,9 +275,9 @@ split(str::T, splitter::Char;
     _split(str, equalto(splitter), limit, keep, T <: SubString ? T[] : SubString{T}[])
 
 function _split(str::AbstractString, splitter, limit::Integer, keep_empty::Bool, strs::Array)
-    i = start(str)
+    @assert (i = firstindex(str)) == 1
```
Comment (nalimilan) [inline base/strings/util.jl]: Do we really need to assert this? Why do it here and not elsewhere? I think implementations which get this wrong will realize it quite soon even without assertions given that may things will fail.

Comment (stevengj) [reply base/strings/util.jl]: I'm asserting it because the subsequent code relies on it.  Basically, I think of this as a comment with some added value.  Assertions are cheap so we shouldn't hesitate to add them, no?

Comment (vtjnash) [reply base/strings/util.jl]: `(i = firstindex(str))` though goes against the recently added documention that use of `@assert` might not work in the future (#25610)

Comment (stevengj) [reply base/strings/util.jl]: Okay, will fix.

Comment (StefanKarpinski) [reply base/strings/util.jl]: Not really since the argument here is to delete it which is exactly what the compiler would do.

Comment (stevengj) [reply base/strings/util.jl]: @StefanKarpinski, the point is that you can't completely delete this code because it contains an assignment.  Hence this is not correct usage of `@assert`.

Comment (StefanKarpinski) [reply base/strings/util.jl]: Ah, yes. That's true. I missed that bit.
