### PR TITLE
fix docstring for code_llvm [ci skip]

### LINKED ISSUE #26264: Markdown formatting methods containing two underscores e.g. `code_llvm_raw`
The formatting is busted for functions that contain two `_`, since the markdown rendering underscores the part between the `_`

```
help?> code_llvm
search: code_llvm @code_llvm

  code_llvm([io=stdout,], f, types)

  Prints the LLVM bitcodes generated for running the method matching the
  given generic function and type signature to io.

  All metadata and dbg.* calls are removed from the printed bitcode. Use
  codellvmraw for the full IR.
```

### PR DESCRIPTION
**Pull request by vchuravy**
fixes #26264

### CODE REVIEW

**Review by dpsanders — COMMENTED** [review]
Maybe spell out what IR means.

File: stdlib/InteractiveUtils/src/codeview.jl [hunk 1]
```diff
@@ -116,7 +116,7 @@ end
 Prints the LLVM bitcodes generated for running the method matching the given generic
 function and type signature to `io`.
 
-All metadata and dbg.* calls are removed from the printed bitcode. Use code_llvm_raw for the full IR.
+All metadata and dbg.* calls are removed from the printed bitcode. Use [`code_llvm_raw`](@ref) for the full IR.
```
Comment (JeffBezanson) [inline stdlib/InteractiveUtils/src/codeview.jl]: `code_llvm_raw` isn't documented, so I'm not sure this will work as a ref.
