### PR TITLE
Make return type of broadcast inferrable with heterogeneous arrays

### LINKED ISSUE #28382: Poor inference of `[1, 2] + `[3.0, missing]`
I have been trying to get into using `missing` and fast `Union` types in my worflow and seem to be coming up with some issues. It's most easily highlighted by:

```
julia> @code_warntype [1, 2] + [3.0, missing]
Body::Array
44 1 ── %1  = (Base.getfield)(Bs, 1, true)::Array{Union{Missing, Float64},1}                                                                               │╻╷╷         iterate
   └───       goto #7 if not true                                                                                                                          │           
   2 ┄─ %3  = φ (#1 => %1, #6 => %12)::Array{Union{Missing, Float64},1}                                                                                    │           
   │    %4  = φ (#1 => 2, #6 => %13)::Int64                                                                                                                │           
45 │          invoke Base.promote_shape(_2::Array{Int64,1}, %3::Array{Union{Missing, Float64},1})                                                          │           
   │    %6  = (Base.slt_int)(1, %4)::Bool                                                                                                                  ││╻           <
   └───       goto #4 if not %6                                                                                                                            ││          
   3 ──       goto #5                                                                                                                                      ││          
   4 ── %9  = (Base.getfield)(Bs, %4, true)::Array{Union{Missing, Float64},1}                                                                              ││╻           getindex
   │    %10 = (Base.add_int)(%4, 1)::Int64                                                                                                                 ││╻           +
   └───       goto #5                                                                                                                                      ││          
   5 ┄─ %12 = φ (#4 => %9)::Array{Union{Missing, Float64},1}                                                                                               │           
   │    %13 = φ (#4 => %10)::Int64                                                                                                                         │           
   │    %14 = φ (#3 => true, #4 => false)::Bool                                                                                                            │           
   │    %15 = (Base.not_int)(%14)::Bool                                                                                                                    │           
   └───       goto #7 if not %15                                                                                                                           │           
   6 ──       goto #2                                                                                                                                      │           
47 7 ── %18 = (getfield)(Bs, 1)::Array{Union{Missing, Float64},1}                                                                                          │           
   │    %19 = (Core.tuple)(A, %18)::Tuple{Array{Int64,1},Array{Union{Missing, Float64},1}}                                                                 ││╻           broadcasted
   │    %20 = (Base.arraysize)(A, 1)::Int64                                                                                                                │││╻╷╷╷╷       instantiate
   │    %21 = (Base.slt_int)(%20, 0)::Bool                                                                                                                 ││││╻╷╷╷        combine_axes
   │    %22 = (Base.ifelse)(%21, 0, %20)::Int64                                                                                                            │││││┃│││││      broadcast_axes
   │    %23 = %new(Base.OneTo{Int64}, %22)::Base.OneTo{Int64}                                                                                              ││││││┃│││        axes
   │    %24 = (Base.arraysize)(%18, 1)::Int64                                                                                                              ││││││╻╷╷         broadcast_axes
   │    %25 = (Base.slt_int)(%24, 0)::Bool                                                                                                                 │││││││╻╷╷╷        axes
   │    %26 = (Base.ifelse)(%25, 0, %24)::Int64                                                                                                            ││││││││┃│││        map
   │    %27 = %new(Base.OneTo{Int64}, %26)::Base.OneTo{Int64}                                                                                              │││││││││┃│          Type
   │    %28 = (%26 === %22)::Bool                                                                                                                          ││││││╻╷╷╷╷       _bcs
   │    %29 = (Base.and_int)(true, %28)::Bool                                                                                                              │││││││╻           _bcs1
   └───       goto #9 if not %29                                                                                                                           ││││││││┃           _bcsm
   8 ──       goto #10                                                                                                                                     │││││││││   
   9 ── %32 = (%22 === 1)::Bool                                                                                                                            │││││││││╻           ==
   └───       goto #10                                                                                                                                     │││││││││   
   10 ┄ %34 = φ (#8 => %29, #9 => %32)::Bool                                                                                                               ││││││││    
   └───       goto #12 if not %34                                                                                                                          ││││││││    
   11 ─       goto #18                                                                                                                                     ││││││││    
   12 ─ %37 = (%22 === %26)::Bool                                                                                                                          │││││││││╻╷          ==
   │    %38 = (Base.and_int)(true, %37)::Bool                                                                                                              ││││││││││╻           &
   └───       goto #14 if not %38                                                                                                                          │││││││││   
   13 ─       goto #15                                                                                                                                     │││││││││   
   14 ─ %41 = (%26 === 1)::Bool                                                                                                                            │││││││││╻           ==
   └───       goto #15                                                                                                                                     │││││││││   
   15 ┄ %43 = φ (#13 => %38, #14 => %41)::Bool                                                                                                             ││││││││    
   └───       goto #17 if not %43                                                                                                                          ││││││││    
   16 ─       goto #18                                                                                                                                     ││││││││    
   17 ─ %46 = %new(Base.DimensionMismatch, "arrays could not be broadcast to a common size")::DimensionMismatch                                            ││││││││╻           Type
   │          (Base.Broadcast.throw)(%46)                                                                                                                  ││││││││    
   └───       $(Expr(:unreachable))                                                                                                                        ││││││││    
   18 ┄ %49 = φ (#11 => %27, #16 => %23)::Base.OneTo{Int64}                                                                                                │││││││     
   │    %50 = (Core.tuple)(%49)::Tuple{Base.OneTo{Int64}}                                                                                                  │││││││     
   └───       goto #19                                                                                                                                     │││││││     
   19 ─       goto #20                                                                                                                                     ││││││      
   20 ─       goto #21                                                                                                                                     │││││       
   21 ─ %54 = %new(Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(+),Tuple{Array{Int64,1},Array{Union{Missing, Float64},1}}}, +, %19, %50)::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(+),Tuple{Array{Int64,1},Array{Union{Missing, Float64},1}}}
   └───       goto #22                                                                                                                                     ││││        
   22 ─ %56 = invoke Base.Broadcast.copy(%54::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(+),Tuple{Array{Int64,1},Array{Union{Missing, Float64},1}}})::Array
   └───       goto #23                                                                                                                                     │││         
   23 ─       goto #24                                                                                                                                     ││          
   24 ─       return %56                  
```
As you can see, the resultant output is (correctly but imprecisely) inferred to be `Array` (not even `Vector`?).

I find this example interesting for two reasons

 1. Performance (resulting from imprecise inference)
 2. Predictable interface provided by output container

Regarding performance, I find it quite usual to combine combinations of "functional" operations like `+`, `map`, etc, together with hand-written loops in the same scope. In fact, predictably good performance over loops, recursion, higher-order programming, etc is kind of one of our main selling points. In the above, performance will be pessimised if I loop over the output since neither the container type (even the array dimensionality is lost, somehow!) nor the element type is well known. I'm guessing but I'd predict that `Vector{Union{Missing, Float64}}` would be fastest for subsequent iteration, but it's possible that if inference found something like `Vector{<:Union{Missing, Float64}}` then this would also be quite fast (I'm not sure, really).

Regarding the second, more semantic issue of what the output *actually* becomes at run time, I'm a bit confused about what I'm meant to assume I can *do* with the output container. For these input *types*, we can get

```julia
julia> Int[] + Union{Float64, Missing}[]
0-element Array{Union{Missing, Float64},1}

julia> Int[1] + Union{Float64, Missing}[3.0]
1-element Array{Float64,1}:
 4.0

julia> Int[2] + Union{Float64, Missing}[missing]
1-element Array{Missing,1}:
 missing

julia> Int[1, 2] + Union{Float64, Missing}[3.0, missing]
2-element Array{Union{Missing, Float64},1}:
 4.0     
  missing
```

As a programmer, this scares me somewhat because I might get subtly different program behavior (or program correctness) depending on my input data. My concerm is that I might perform tests with mixtures of `Missing` and `Float64` input values but be caught out in rare cases in production when all (or none) of the inputs are `missing`.

In this hypothetical scenario, my (tested, production) code might look something like
```julia
vec3 = vec1 + vec2
for i in keys(vec3)
    if isless(vec3[i], 0) # vec3 can't have any negative elements
        vec3[i] = missing
    end
end
return vec3
```
But unfortunately this would sometimes fail, depending on my input data, which may vary in size and quality (and maybe 1 in 10,000 times are all non-`missing`).

As a coder, I need to be able to predict the interface provided by the outputs of operation so I can write reliable code. Generally, I've noted that the output of `+`, `map`, `broadcast`, `filter` (for `Array` inputs) tend to be mutable `Array`s, and generally am unafraid to mutate them. Naively, I would track in my head the eltypes of `vec1` and `vec2` and assume I can populate `vec3` with anything consistent.

I'm not sure what the best solution is, but from my perspective I find any potential (performance?) gains in returning the narrowest container that fits the run-time data questionable in value compared to understanding the semantic guarantees as a code author.

### PR DESCRIPTION
**Pull request by nalimilan**
Inference is not able to detect the element type automatically, but we can do it manually since we know `promote_typejoin` is used for widening.

Fixes #28382. The same changes should be applied to `map`.

### CODE REVIEW

File: base/broadcast.jl [hunk 1]
```diff
@@ -623,8 +623,31 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
 eltypes(t::Tuple{Any,Any}) = Tuple{_broadcast_getindex_eltype(t[1]), _broadcast_getindex_eltype(t[2])}
 eltypes(t::Tuple) = Tuple{_broadcast_getindex_eltype(t[1]), eltypes(tail(t)).types...}
 
+Base.@pure function promote_typejoin_union(::Type{T}) where T
```
Comment (nalimilan) [inline base/broadcast.jl]: This is probably very wrong and @vtjnash will find lots of issues with this, but at least it should get the ball rolling.

File: test/broadcast.jl [hunk 2]
```diff
@@ -360,7 +360,7 @@ end
 let f17314 = x -> x < 0 ? false : x
     @test eltype(broadcast(f17314, 1:3)) === Int
     @test eltype(broadcast(f17314, -1:1)) === Integer
-    @test eltype(broadcast(f17314, Int[])) == Union{Bool,Int}
+    @test eltype(broadcast(f17314, Int[])) === Integer
```
Comment (nalimilan) [inline test/broadcast.jl]: This is a *minor change* which I think can be considered as a bug fix, in the sense that before this PR the element type when the input is empty will never be observed when the array isn't empty (we can only ever observe `Int`, `Bool` or `Integer`). I could change the PR to preserve the existing behavior if we want (e.g. for backports).

Comment (mbauman) [reply test/broadcast.jl]: Oh that's interesting.  Yeah, here's the current behaviors:

```
julia> eltype(broadcast(f17314, Int[]))
Union{Bool, Int64}

julia> eltype(broadcast(f17314, Int[1]))
Int64

julia> eltype(broadcast(f17314, Int[-1]))
Bool

julia> eltype(broadcast(f17314, Int[1,-1]))
Integer
```

The reason for using inference here in the first place is to preserve the performance in the non-empty case.  Adding a _fourth_ possible return type defeats such a purpose, so I'm in support of this change.

**Review by mbauman — COMMENTED** [review]
I cannot meaningfully review the way in which you achieve the change in behaviors here, but I approve of the result and think this is a minor change worth making.

File: test/broadcast.jl (hunk 2 above)
Comment (andyferris) [reply test/broadcast.jl]: Exactly - we either need to change the last to match the first, or the first to match the last.

This PR seems the least breaking, and suitable for v1.x. If we ever wanted to consider the other way around maybe that should be a v2.0 change?

File: base/broadcast.jl (hunk 1 above)
Comment (andyferris) [reply base/broadcast.jl]: I can at least offer that this function doesn't seem to contain anything that has bitten me before.

Comment (andyferris) [reply base/broadcast.jl]: To follow that up, if anyone overloads `_promote_typejoin` (they might if they want to introduce a `Nothing` or `Missing` style of type that naturally forms a `Union` with other types - otherwise we have to consider these two as "blessed" types) or `typejoin` (they shouldn't do this) then you are in trouble here.

Comment (nalimilan) [reply base/broadcast.jl]: @vtjnash Bump. I need your input to make progress on this.

Comment (vtjnash) [reply base/broadcast.jl]: `promote_typejoin` is not pure (by design), so this is invalid

Comment (nalimilan) [reply base/broadcast.jl]: Yes, but what would be a correct approach? :-)

Comment (nalimilan) [reply base/broadcast.jl]: OK, I think I've found a correct approach: since `promote_typejoin` doesn't apply recursively inside tuples, we can split the part operation on tuple types into a separate method which is `@pure` since it only calls `typejoin`, and a non-pure part which is correctly inferred even without `@pure`.

**Comment by vtjnash** [comment]
I'm still not sure. I'm not really sure that `Base._return_type` is reporting the right answer here, and I'm not sure that various hackery to make the answer more contorted is really the right solution that.

**Comment by nalimilan** [comment]
> I'm still not sure. I'm not really sure that `Base._return_type` is reporting the right answer here, and I'm not sure that various hackery to make the answer more contorted is really the right solution that.

What do you mean? Why would `return_type` be incorrect? If it's imprecise in some cases, that's OK. Also it's already used, in particular when the result is empty. This PR doesn't really make things worse in that regard as it only affects inference.

Or do you have a better proposal? I agree it would be nice if the compiler did that automatically, but until it does we really need to avoid the inference failure that `broadcast` creates with `Union{T,Missing}`.

File: base/broadcast.jl [hunk 3]
```diff
@@ -623,8 +623,44 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        pi = p[i]
+        U = Core.Compiler.unwrapva(pi)
+        if U === Union{}
+            ci = Union{}
+        elseif U isa Union
+            ci = typejoin(U.a, U.b)
+        else
+            ci = U
+        end
+        c[i] = i == lf && Core.Compiler.isvarargtype(pi) ? Vararg{ci} : ci
```
Comment (vtjnash) [inline base/broadcast.jl:656]:
```suggestion
        c[i] = i == lf && Core.Compiler.isvarargtype(pi) ? Vararg{ci, N} : ci
```

The Vararg parameter needs to be extracted from `pi` also

File: base/broadcast.jl [hunk 4]
```diff
@@ -623,8 +623,44 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+    end
+end
+
+@pure function typejoin_union_tuple(::Type{T}) where {T}
+    p = T.parameters
+    lr = length(p)::Int
+    if lr == 0
+        return Tuple{}
+    end
+    lf, fixed = Core.Compiler.full_va_len(p)
```
Comment (vtjnash) [inline base/broadcast.jl:644]:
```suggestion
    lf = lr
```
(`full_va_len` has no applicability here, since it's the number of fields, but you want to iterate over `p`)

File: base/broadcast.jl [hunk 5]
```diff
@@ -623,8 +623,44 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        promote_typejoin(promote_typejoin_union(T.a), promote_typejoin_union(T.b))
+    elseif T <: Tuple
+        typejoin_union_tuple(T)
+    else
+        T
+    end
+end
+
+@pure function typejoin_union_tuple(::Type{T}) where {T}
+    p = T.parameters
```
Comment (vtjnash) [inline base/broadcast.jl:639]:
```suggestion
@pure function typejoin_union_tuple(T::Type)
    p = (unwrap_unionall(T)::DataType).parameters
```

(accessing `.parameters` of `Type{T}` is always bad practice, since the `typeof` isn't stable)

File: base/broadcast.jl [hunk 6]
```diff
@@ -623,8 +623,44 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
 eltypes(t::Tuple{Any,Any}) = Tuple{_broadcast_getindex_eltype(t[1]), _broadcast_getindex_eltype(t[2])}
 eltypes(t::Tuple) = Tuple{_broadcast_getindex_eltype(t[1]), eltypes(tail(t)).types...}
 
+function promote_typejoin_union(::Type{T}) where T
+    if T === Union{}
+        return Union{}
```
Comment (vtjnash) [inline base/broadcast.jl:628]: all branches should have the same `return` structure (all or none)

File: base/broadcast.jl [hunk 7]
```diff
@@ -788,7 +824,13 @@ const NonleafHandlingStyles = Union{DefaultArrayStyle,ArrayConflict}
...
     @inbounds dest[I] = val
     # Now handle the remaining values
-    return copyto_nonleaf!(dest, bc′, iter, state, 1)
+    if dest isa AbstractArray
+        # Give inference a helping hand on the element type and dimensionality
+        # (work-around for #28382)
+        return copyto_nonleaf!(dest, bc′, iter, state, 1)::AbstractArray{<:ElType, ndims(dest)}
+    else
+        return copyto_nonleaf!(dest, bc′, iter, state, 1)
+    end
```
Comment (vtjnash) [inline base/broadcast.jl:833]:
```suggestion
    # The typeassert gives inference a helping hand on the element type and dimensionality
    # (work-around for #28382)
    return copyto_nonleaf!(dest, bc′, iter, state, 1)::(dest isa AbstractArray ? AbstractArray{<:ElType, ndims(dest)} : Any)
```

**Comment by vtjnash** [comment]
Upon much reflection, I now think this is actually sensible, and does actually help slightly to decouple inference from the result here, as `Core.Compiler.return_types` returns lists of types as a Union (possible inside a Tuple), and for usability, that shouldn't actually ever be consumed directly, but instead converted into a proper simplified type (as done here). I think there's some implication there also that users of `return_types` should never use anything but `typejoin` to widen their types, but that's just a predicability/quality improvement not correctness. And possibly `return_types` should do be doing this itself directly (to prevent users from depending on the specific complexities of inference in ways that can't even be seen at runtime), but this seems at least reasonable as an improvement to this consumer.

**Comment by nalimilan** [comment]
Thanks for the review. I'm amazed I didn't get more things wrong. :-p
I've added code to compute `N` for `Vararg`, let me know if it's correct.

Unfortunately, after rebasing against current master, the return type is only inferred as `AbstractArray{...}` while on the previous state of the PR if was inferred as a concrete `Array{...}` type. This is due to the fact that `copyto_nonleaf!` is now inferred as `Any` while before (on 1.5.0 is was still the case) it was inferred as `Array`, as indicated by e.g. `@code_warntype Base.Broadcast.copyto_nonleaf!([1], Base.Broadcast.Broadcasted(+, ([1,2], [1,missing])), [1, 2], 1, 1)`. This PR is still an improvement so I could relax the tests for now until we find the fix.

File: base/broadcast.jl [hunk 8]
```diff
@@ -691,8 +691,48 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        return promote_typejoin(promote_typejoin_union(T.a), promote_typejoin_union(T.b))
+    elseif T <: Tuple
+        return typejoin_union_tuple(T)
+    else
+        return T
+    end
+end
+
+@pure function typejoin_union_tuple(::Type{T}) where {T}
+    p = (Core.Compiler.unwrap_unionall(T)::DataType).parameters
```
Comment (vtjnash) [inline base/broadcast.jl:707]:
```suggestion
    p = (Base.unwrap_unionall(T)::DataType).parameters
```

Comment (vtjnash) [reply base/broadcast.jl:707]: but might also be a `::Union` (for which both elements are Tuple), since `promote_typejoin_union` doesn't handle this case (of UnionAll wrappers)

File: base/broadcast.jl [hunk 9]
```diff
@@ -691,8 +691,48 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+    elseif T isa Union
+        return promote_typejoin(promote_typejoin_union(T.a), promote_typejoin_union(T.b))
+    elseif T <: Tuple
+        return typejoin_union_tuple(T)
+    else
+        return T
+    end
+end
+
+@pure function typejoin_union_tuple(::Type{T}) where {T}
```
Comment (vtjnash) [inline base/broadcast.jl:706]:
```suggestion
@pure function typejoin_union_tuple(T::Type)
```

Don't force the compiler to specialize methods (and it's more concise to write)

File: base/broadcast.jl [hunk 10]
```diff
@@ -691,8 +691,48 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        U = Core.Compiler.unwrapva(pi)
+        if U === Union{}
+            ci = Union{}
+        elseif U isa Union
+            ci = typejoin(U.a, U.b)
+        else
+            ci = U
+        end
+        if i == lr && Core.Compiler.isvarargtype(pi)
+            N = (Core.Compiler.unwrap_unionall(pi)::DataType).parameters[2]
```
Comment (vtjnash) [inline base/broadcast.jl:724]:
```suggestion
            N = (Base.unwrap_unionall(pi)::DataType).parameters[2]
```

**Review by vtjnash — COMMENTED** [review]
SGTM

**Comment by nalimilan** [comment]
Woops, CI failure is due to a call like `typeof.([iszero, isdigit])`. The final eltype is `DataType`, which isn't a subtype of `eltype(bc)` (which a more specific `Type`).

I though something like `ElType′ = ElType isa Type ? DataType : ElType` would do, but then I get other failures during bootstrap (don't know where yet but it's due to a failing `convert`). Any ideas? I guess I could just avoid asserting the return type in that case, but there's probably a better solution.

File: base/broadcast.jl (hunk 8 above)
Comment (nalimilan) [reply base/broadcast.jl:707]: Sorry, not sure what I need to change here. :-)

Comment (vtjnash) [reply base/broadcast.jl]: The type-assert—it's either a Union or DataType here

**Comment by nalimilan** [comment]
OK I think I've found a solution. I've also made the test less strict, with `@test_broken` for cases that should be fixed separately (cf. https://github.com/JuliaLang/julia/pull/30485/#issuecomment-673396551).

File: base/broadcast.jl (hunk 8 above)
Comment (nalimilan) [reply base/broadcast.jl]: Got it. I've pushed a fix.

File: base/broadcast.jl [hunk 11]
```diff
@@ -691,8 +691,48 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        return promote_typejoin(promote_typejoin_union(T.a), promote_typejoin_union(T.b))
+    elseif T <: Tuple
+        return typejoin_union_tuple(T)
+    else
+        return T
+    end
+end
+
+@pure function typejoin_union_tuple(T::Type)
+    p = (Base.unwrap_unionall(T)::Union{DataType, Union}).parameters
```
Comment (vtjnash) [inline base/broadcast.jl:707]: Union doesn't have a `parameters` field—you need to call typejoin_union_tuple on the separate halves

Comment (vtjnash) [reply base/broadcast.jl:707]:
```suggestion
    u = Base.unwrap_unionall(T)
    u isa Union && return typejoin(
            typejoin_union_tuple(rewrap_unionall(u.a, T)),
            typejoin_union_tuple(rewrap_unionall(u.b, T)))
    p = (u::DataType).parameters    
```

File: base/broadcast.jl [hunk 12]
```diff
@@ -691,8 +691,48 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        return Tuple{}
+    end
+    c = Vector{Any}(undef, lr)
+    for i = 1:lr
+        pi = p[i]
+        U = Core.Compiler.unwrapva(pi)
+        if U === Union{}
+            ci = Union{}
+        elseif U isa Union
+            ci = typejoin(U.a, U.b)
```
Comment (vtjnash) [inline base/broadcast.jl:719]:
```suggestion
            ci = typejoin(rewrap_unionall(U.a, T), rewrap_unionall(U.b, T))
```

File: base/broadcast.jl [hunk 13]
```diff
@@ -691,8 +691,48 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+            ci = U
+        end
+        if i == lr && Core.Compiler.isvarargtype(pi)
+            N = (Base.unwrap_unionall(pi)::DataType).parameters[2]
+            c[i] = Vararg{ci, N}
+        else
+            c[i] = ci
+        end
+    end
+    return Tuple{c...}
```
Comment (vtjnash) [inline base/broadcast.jl:730]:
```suggestion
    return rewrap_unionall(Tuple{c...}, T)
```

File: base/broadcast.jl (hunk 11 above)
Comment (nalimilan) [reply base/broadcast.jl]: Thanks!

**Comment by nalimilan** [comment]
Good to go @vtjnash?

File: base/broadcast.jl [hunk 14]
```diff
@@ -877,7 +921,11 @@ const NonleafHandlingStyles = Union{DefaultArrayStyle,ArrayConflict}
     dest = similar(bc′, typeof(val))
     @inbounds dest[I] = val
     # Now handle the remaining values
-    return copyto_nonleaf!(dest, bc′, iter, state, 1)
+    # The typeassert gives inference a helping hand on the element type and dimensionality
+    # (work-around for #28382)
+    ElType′ = ElType <: Type ? DataType : ElType
```
Comment (vtjnash) [inline base/broadcast.jl:926]:
```suggestion
    ElType′ = ElType <: Type ? Type : ElType
```

File: base/broadcast.jl [hunk 15]
```diff
@@ -691,8 +691,52 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        if U === Union{}
+            ci = Union{}
+        elseif U isa Union
+            ci = typejoin(Base.rewrap_unionall(U.a, T), Base.rewrap_unionall(U.b, T))
+        else
+            ci = U
+        end
+        if i == lr && Core.Compiler.isvarargtype(pi)
+            N = (Base.unwrap_unionall(pi)::DataType).parameters[2]
+            c[i] = Vararg{ci, N}
```
Comment (vtjnash) [inline base/broadcast.jl:729]:
```suggestion
            c[i] = Base.rewrap_unionall(Vararg{ci, N}, pi)
```

File: base/broadcast.jl [hunk 16]
```diff
@@ -691,8 +691,52 @@ eltypes(t::Tuple{Any}) = Tuple{_broadcast_getindex_eltype(t[1])}
...
+        return Tuple{}
+    end
+    c = Vector{Any}(undef, lr)
+    for i = 1:lr
+        pi = p[i]
+        U = Core.Compiler.unwrapva(pi)
+        if U === Union{}
+            ci = Union{}
+        elseif U isa Union
+            ci = typejoin(Base.rewrap_unionall(U.a, T), Base.rewrap_unionall(U.b, T))
```
Comment (vtjnash) [inline base/broadcast.jl:723]: @JeffBezanson is it okay that we're re-wrapping both these and the result in the same T?

Comment (JeffBezanson) [reply base/broadcast.jl:723]: Hmm, right, we've hit something like this before (#36407). For example `Tuple{T, T, Ref{T}} where T`. If you rewrap `Ref{T}` then the outer `T` loses its invariant occurrence, making the other two Ts diagonal. So this can potentially give too narrow a type.

**Comment by JeffBezanson** [comment]
IIUC, only the type assertion is needed for the inference improvement, and it seems to me that is much easier?

File: base/broadcast.jl (hunk 16 above)
Comment (JeffBezanson) [reply base/broadcast.jl:723]: I think `typejoin` tolerates types with free variables (at least, it calls itself recursively that way), so the fix is probably just to not call `rewrap` until the top level.

**Comment by nalimilan** [comment]
> IIUC, only the type assertion is needed for the inference improvement, and it seems to me that is much easier?

AFAICT all changes are needed. `promote_typejoin_union` is needed to compute e.g. `Integer` when the function returns either `Int` or `Bool`. Otherwise the computed eltype will be `Union{Int, Bool}`, which isn't a supertype of `Integer`, so the assertion will fail.

What could be avoided is the minor change of eltype from `Union{Int, Bool}` to `Integer` when the input is empty (https://github.com/JuliaLang/julia/pull/30485#discussion_r243698858), but that doesn't make the PR more complex.

File: base/broadcast.jl (hunk 16 above)
Comment (nalimilan) [reply base/broadcast.jl:723]: In concrete terms, what should I do? :-D

**Comment by nalimilan** [comment]
Bump. This is going to miss 1.6 (meaning it will reach its second anniversary without being released...).

File: base/broadcast.jl (hunk 16 above)
Comment (JeffBezanson) [reply base/broadcast.jl:723]: Replace this line with
```
ci = typejoin(U.a, U.b)
```

**Comment by nalimilan** [comment]
Thanks @vtjnash and @JeffBezanson. I'll merge tomorrow if nobody objects (FreeBSD failure seems unrelated).

File: test/broadcast.jl [hunk 17]
```diff
@@ -950,3 +950,41 @@ p0 = copy(p)
...
+    @test_broken Core.Compiler.return_type(+, Tuple{Vector{Int},
+                                                    Vector{Union{Float64, Missing}}}) ==
+        Vector{<:Union{Float64, Missing}}
+    @test isequal(tuple.([1, 2], [3.0, missing]), [(1, 3.0), (2, missing)])
+    @test_broken Core.Compiler.return_type(broadcast, Tuple{typeof(tuple), Vector{Int},
+                                                            Vector{Union{Float64, Missing}}}) ==
+        Vector{<:Tuple{Int, Any}}
+    @test Core.Compiler.return_type(broadcast, Tuple{typeof(tuple), Vector{Int},
+                                                     Vector{Union{Float64, Missing}}}) ==
+        AbstractVector{<:Tuple{Int, Any}}
```
Comment (simeonschaub) [inline test/broadcast.jl:978]: #39618 seems to fix these tests. @nalimilan Could that mean that this workaround might not even be needed anymore? Or does it maybe just fix this particular example?

Comment (nalimilan) [reply test/broadcast.jl:978]: Ah then it's great! Actually all the work I did in this PR had not effect for now due to this inference failure (a regression due to changes to reduce compile time introduced since 1.5). So if you can replace these `@test_broken` with `@test` then it's perfect!

Comment (simeonschaub) [reply test/broadcast.jl:978]: Ah, cool. Thanks for checking!
