### PR TITLE
Fix use-after-free bugs in debuginfo

### LINKED ISSUE #44562: MacOS: use-after-free during debuginfo registration leads to segfault
When running the `read` test on the m1 mac get non fatal segfaults like
```
signal (11): Segmentation fault: 11
in expression starting at none:0

signal (11): Segmentation fault: 11
in expression starting at none:0
```

I caught it on lldb on a non-debug buid:
```
in expression starting at none:0
libjulia-internal.1.9.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 55818 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x102527bc0)
    frame #0: 0x000000010187436c libjulia-internal.1.9.dylib`jl_exit_thread0_cb(exitstate=139) at signals-mach.c:408 [opt]
   405 	}
   406 	
   407 	static void JL_NORETURN jl_exit_thread0_cb(int exitstate)
-> 408 	{
   409 	CFI_NORETURN
   410 	   jl_critical_error(exitstate - 128, NULL, jl_current_task);
   411 	   jl_exit(exitstate);
Target 0: (julia) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x102527bc0)
  * frame #0: 0x000000010187436c libjulia-internal.1.9.dylib`jl_exit_thread0_cb(exitstate=139) at signals-mach.c:408 [opt]
    frame #1: 0x00000001ea3e4b68 libsystem_c.dylib
    frame #2: 0x0000000190c431e4 libsystem_c.dylib`__v2printf + 408
    frame #3: 0x0000000190c72038 libsystem_c.dylib`_vsnprintf + 268
    frame #4: 0x0000000101850cd4 libjulia-internal.1.9.dylib`ijl_safe_printf(fmt=<unavailable>) at jl_uv.c:623:5 [opt]
    frame #5: 0x0000000101874168 libjulia-internal.1.9.dylib`jl_critical_error(sig=11, context=0x0000000000000000, ct=0x000000010907c010) at signal-handling.c:315:9 [opt]
    frame #6: 0x0000000101874394 libjulia-internal.1.9.dylib`jl_exit_thread0_cb(exitstate=139) at signals-mach.c:410:5 [opt]
```

### LINKED ISSUE #44947: CI: non-deterministic failures in `cmdlineargs`, `spawn` on both Intel macOS and Apple Silicon macOS
Here are some examples of `cmdlineargs` failing on macOS x86_64:
1. https://buildkite.com/julialang/julia-master/builds/11163#d4f443e0-f55b-4d56-ad5c-ad3b35ce943b
2. https://buildkite.com/julialang/julia-master/builds/11162#493281b1-84b7-495f-b73b-19da937e7f12

Here are some examples of `spawn` failing on macOS x86_64:
1. https://buildkite.com/julialang/julia-master/builds/11162#c33f71cc-cedc-4fc0-8d63-510890ce121a

### PR DESCRIPTION
**Pull request by pchintalapudi**
Fixes #44562 
Fixes #44947 

This is achieved by making the debug info global variables a part of the JIT engine, which should leak their memory with our JIT rather than being destroyed on process exit. 

We also do the following as part of the move:
1. Consolidate all of the debug info global variables into one large struct
   1. This sequences all of the destructor orderings, and ties their lifetimes together for easier analysis. 
1. Make debug info threadsafe
   1. This is achieved by locking around the data structures within the debug info registry

### CODE REVIEW

File: src/debuginfo.cpp [hunk 1]
```diff
@@ -181,212 +438,11 @@ static void create_PRUNTIME_FUNCTION(uint8_t *Code, size_t Size, StringRef fnnam
 }
 #endif
 
-struct revcomp {
```
Comment (pchintalapudi) [inline src/debuginfo.cpp:184]: We now use `std::greater<size_t>` instead of revcomp

**Comment by DilumAluthge** [comment]
@pchintalapudi Does this fix https://github.com/JuliaLang/julia/issues/44562?

**Comment by pchintalapudi** [comment]
I'm hoping for that, but I want to get results for macos before confirming that.

**Comment by DilumAluthge** [comment]
I guess we can just check the Buildkite CI logs for both the macOS x86_64 tester and the macOS Apple Silicon tester, and see if there are still any segfaults in the logs.

**Comment by DilumAluthge** [comment]
Looks like the Windows builders are failing.

**Comment by pchintalapudi** [comment]
I'll tackle that and the analyzegc failures once the mac tester finishes, just to see if it works.

**Comment by DilumAluthge** [comment]
You'll find the macOS x86_64 tester in the `Test` group - look for the job named `test x86_64-apple-darwin`.

The macOS Apple Silicon tester is in the `Allow Fail` group - look for the job named `test aarch64-apple-darwin`.

**Comment by pchintalapudi** [comment]
Macos tests look successful for 07eb7bf

**Comment by DilumAluthge** [comment]
Just to be safe, before merging, we should let the macOS x86_64 tester run to completion, just to make sure that there aren't any segfaults right at the very end.

**Comment by DilumAluthge** [comment]
macOS x86_64 also looks segfault free on https://github.com/JuliaLang/julia/commit/f0b06f8b0cd4169b27ad6c34abd458967376c6cd: https://buildkite.com/julialang/julia-master/builds/11193#aa5af690-dc6a-4023-a4f6-0e1115f2397c

**Comment by pchintalapudi** [comment]
Looks like Mac+aarch64 is also clean: https://buildkite.com/julialang/julia-master/builds/11193#7749e3f8-a7fd-4f3f-bed1-30a0496e6540

File: src/debuginfo.cpp [hunk 2]
```diff
@@ -803,12 +836,13 @@ static objfileentry_t &find_object_file(uint64_t fbase, StringRef fname) JL_NOTS
...
 
 // GOAL: Read debuginfo from file
-    // TODO: need read/write lock here for objfilemap synchronization
-    obfiletype::iterator it = objfilemap.find(fbase);
-    if (it != objfilemap.end())
-        // Return cached value
-        return it->second;
-    auto &entry = objfilemap[fbase]; // default initialized
+    objfileentry_t entry{nullptr, nullptr, 0};
+    {
```
Comment (vtjnash) [inline src/debuginfo.cpp:840]: what is the random scope block for? temporaries are usually destroyed by `;`

File: src/jitlayers.h [hunk 3]
```diff
@@ -334,6 +335,8 @@ class JuliaOJIT {
     TargetMachine &getTargetMachine();
     const Triple& getTargetTriple() const;
     size_t getTotalBytes() const;
+
+    JITDebugInfoRegistry &getDebugInfoRegistry();
```
Comment (vtjnash) [inline src/jitlayers.h:339]:
```suggestion
    JITDebugInfoRegistry &getDebugInfoRegistry() const;
```

File: src/jitlayers.cpp [hunk 4]
```diff
@@ -1398,6 +1398,10 @@ void JuliaOJIT::shareStrings(Module &M)
         GV->eraseFromParent();
 }
 
+JITDebugInfoRegistry &JuliaOJIT::getDebugInfoRegistry() {
```
Comment (vtjnash) [inline src/jitlayers.cpp:1401]:
```suggestion
JITDebugInfoRegistry &JuliaOJIT::getDebugInfoRegistry() const {
```

File: src/debuginfo.cpp (hunk 2 above)
Comment (pchintalapudi) [reply src/debuginfo.cpp:840]: It's an artifact of when I was doing a find-and-set manually, rather than just directly using emplace. I'll get rid of this one plus the lower one too.

**Comment by vtjnash** [comment]
This seems a good approach. Thanks!

**Comment by pchintalapudi** [comment]
@vtjnash Do you have suggestions on how to fix the analyzegc failures? I tried to mark `getDebugInfoRegistry` with `JL_NOTSAFEPOINT`, but that didn't stop the analyzer from complaining about the call.

File: src/jitlayers.h (hunk 3 above)
Comment (pchintalapudi) [reply src/jitlayers.h:339]: I don't think we can mark this method as const, since it returns a non-const reference to the debug info registry? And that reference has to be non-const because debuginfo will change it, but we protect it so thread safety shouldn't be an issue at this point.

Comment (vtjnash) [reply src/jitlayers.h:339]: ah, okay. I suppose marking `const this` would force it to require the return type to be `const JITDebugInfoRegistry&`?

**Comment by vtjnash** [comment]
`getDebugInfoRegistry` should be marked `JL_NOTSAFEPOINT`, but you might need to teach the analyzer how to find properties of CxxMember function calls, since finding their decl site is different from finding the decl target for a basic C function call.

**Comment by pchintalapudi** [comment]
Now that the analyzegc check is passing, I think we can merge this into master if tests pass and no segfaults are observed on macos?

**Comment by pchintalapudi** [comment]
@DilumAluthge do we need to rerun the windows testers? I haven't seen these kinds of errors before.

**Comment by DilumAluthge** [comment]
Let me try rebooting the Windows VMs.

**Comment by DilumAluthge** [comment]
@vtjnash If CI passes, is this good to merge from your point of view?

**Comment by vtjnash** [comment]
yep, seemed to be good to go

**Comment by maleadt** [comment]
Doesn't this need a backport? Otherwise we'll still have #44562 on 1.8. (cc @KristofferC)

**Comment by DilumAluthge** [comment]
It would be great to get this backported.
