### PR TITLE
more predictable global binding resolution

### LINKED ISSUE #17387: for-loop in top-level if-block blocks variable re-binding the first time around.
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+5297 (2016-07-11 19:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 0572533* (0 days old master)
|__/                   |  x86_64-pc-linux-gnu

julia> if true
           @everywhere a=1
           @show pi = 1
           @show pi==1
           @show typeof(pi)
           theta0 = pi==1 ? 1 : error("Should not get here!")
       end
WARNING: imported binding for pi overwritten in module Main
pi = 1 = 1
pi == 1 = false
typeof(pi) = Irrational{:π}
ERROR: Should not get here!
 in macro expansion; at ./REPL[2]:6 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

Note that: the `if` and `@everywhere` is necessary.  Exchanging the `if` with a `let` or `for` stops the bug.  Executing the the if-block again does not error again.  Works on 0.4.

### LINKED ISSUE #18933: more predictable global binding resolution
@JeffBezanson and I discussed this one (a long while ago) and I could have sworn I'd opened an issue about it, but I can't find it so perhaps I didn't. Whether a binding comes from a `using` or not should be predictable from the content of a module, not what is done with the module. Example:

``` jl
module A
    x = 1
    export x
end

module B
    using A
    x!(v) = global x = v
end
```

Currently, we can, in two separate Julia sessions, have `B.x` either be an import from `A` or be a global binding from `B`, depending on what the caller does:

``` jl
julia> module A
           x = 1
           export x
       end
A

julia> module B
           using A
           x!(v) = global x = v
       end
B

julia> B.x
1

julia> B.x!("bah")
WARNING: imported binding for x overwritten in module B
"bah"
```

Session 2:

``` jl
julia> module A
           x = 1
           export x
       end
A

julia> module B
           using A
           x!(v) = global x = v
       end
B

julia> B.x!("bah");

julia> B.x
"bah"
```

Arguably, the _definition_ of the function `x!` which assigns `B.x` should cause `B.x` not to refer to `A.x`, rather than the _evaluation_ of `x!` causing that binding to occur. Thus, in the first case, `B.x` when occurring before any call to `B.x!` should be an undefined reference. This may not be worth bothering with, but it could make life easier for static compilation and I really doubt many people are depending on the current behavior. cc @vtjnash

### PR DESCRIPTION
**Pull request by vtjnash**
~~This takes any syntactic assignment to a global inside a function and ensure we create the binding immediately.~~

EDIT: The design of this PR has changed, although the net effect is generally much less breaking (since now the divergence of the new vs. existing behavior was previously typically an error case):

    This changes the meaning of `global` from being a directive when used at toplevel,
    which forces the introduction of a new global when used in certain contexts,
    to always being just an scope annotation that there should exist a global binding for the given name.

fix #18933
fix #17387

### CODE REVIEW

**Comment by vtjnash** [comment]
Of course, CI is failing because a couple of deprecations were written to depend on the old behavior of #17387 and will need an minor update to Compat first to disable this fix in one place in the code.

File: test/core.jl [hunk 1]
```diff
@@ -5089,3 +5089,23 @@ m22929_2.x = m22929_1
 @test !isdefined_22929_x(m22929_1)
 @test isdefined_22929_1(m22929_2)
 @test isdefined_22929_x(m22929_2)
+
+# issue 18933
+module GlobalDef18933
+    using Base.Test
+    f() = (global sin; nothing)
```
Comment (JeffBezanson) [inline test/core.jl]: Hm, this is kind of a weird case. Normally `global sin` at the toplevel would create a binding in the current module. But I see that since `f` doesn't assign to `sin`, maybe it shouldn't here. I guess this behavior is probably ok.

File: src/julia-syntax.scm [hunk 2]
```diff
@@ -2841,35 +2868,45 @@ f(x) = yt(x)
...
+                         ,ex
+                         ,rhs1))))))
+     ((and (pair? var) (or (eq? (car var) 'outerref)
+                           (eq? (car var) 'globalref)))
+
+      `(= ,var ,rhs0))
+     ((ssavalue? var)
+      `(= ,var ,rhs0))
+     (else
+       (error (string "invalid assignment location \"" (deparse var) "\"")))))
```
Comment (JeffBezanson) [inline src/julia-syntax.scm]: This looks like a good refactoring. Am I right that there's no functional change except for this error?

File: src/julia-syntax.scm [hunk 3]
```diff
@@ -2738,15 +2752,28 @@
...
+    ;; if we collected any assignments to globals
+    ;; annotate them now at the toplevel
+    (let ((glob-decl (map (lambda (e) `(global ,e)) (table.keys glob-assign))))
+      (if (null? glob-decl)
+          e
+          (insert-after-meta
+            (if (and (pair? e) (eq? (car e) 'block))
+                e
+                `(block ,e))
+            glob-decl)))))
```
Comment (JeffBezanson) [inline src/julia-syntax.scm]: I'm not totally convinced it's worth adding this code instead of just looking for global assignments in `jl_resolve_globals`.

File: src/julia-syntax.scm (hunk 2 above)
Comment (vtjnash) [inline src/julia-syntax.scm]: yes. I was thinking of using this code-path to test for globals, but ended up deciding to put it elsewhere.

File: test/core.jl (hunk 1 above)
Comment (vtjnash) [inline test/core.jl]: Yes, it is rather awkward that we use `global` to mean different operations depending on the scope.

File: src/julia-syntax.scm (hunk 3 above)
Comment (vtjnash) [inline src/julia-syntax.scm]: This moves the global decls from local scope (where the syntax does not inherently create new bindings), to global scope (where it does). I'm generally inclined to do all scope and syntax lowering here, rather than implementing any part of it in post-processing code.

File: test/core.jl (hunk 1 above)
Comment (vtjnash) [inline test/core.jl]: even worse, before we weren't even consistent about what this syntax did. for example:
```julia
if true
    global sin
    nothing
end
```
did not create a new global binding, but merely annotated that if a variable named `sin` was used, that its scope is global.

Comment (JeffBezanson) [inline test/core.jl]: Ow, good point.

Should add a test for exactly that case.

File: src/julia-syntax.scm (hunk 3 above)
Comment (JeffBezanson) [inline src/julia-syntax.scm]: Ok, I'm on board.

File: test/core.jl (hunk 1 above)
Comment (vtjnash) [inline test/core.jl]: It's a minor breaking change (but I suspect it will break a handful of packages anyways), but this PR means that:
```
let
   global function f(); return 1; end
end
```
Now expands to
```
global f
f() = 1
```
And thus will _not_ add to an existing binding from `import`, but will instead give an overwrite notice.

**Comment by vtjnash** [comment]
Make sure that @nanosoldier `runbenchmarks(ALL, vs = ":master")` isn't unhappy about the syntax chnage.

File: test/core.jl (hunk 1 above)
Comment (JeffBezanson) [inline test/core.jl]: It's possible we'll require explicit qualification for extension anyway, so this might be moot. However, in the meantime it's possible that `global x` should not overwrite "hard-imported" bindings. That will be less breaking, since currently it gives a warning.

Comment (vtjnash) [inline test/core.jl]: Sure. That operation gives a warning now, so presumably it would be less breaking for it to be ignored (have `global x` mean more consistently the statement "x is a global" rather than the being sometimes the command "make x global").

File: NEWS.md [hunk 4]
```diff
@@ -32,6 +32,13 @@ Language changes
   * `{ }` expressions now use `braces` and `bracescat` as expression heads instead
     of `cell1d` and `cell2d`, and parse similarly to `vect` and `vcat` ([#8470]).
 
+  * The `global` keyword now always introduces a new binding when appearing in toplevel (global) scope.
+    Whereas, previously, embedding it in a block (such as `begin; global sin; nothing; end`) would change its meaning.
+    Additionally, the new bindings are now created before the statement is executed.
+    For example, `f() = (global sin = rand(); nothing)` will now reliably shadow the `Base.sin` function,
```
Comment (tkelman) [inline NEWS.md]: no comma at the end of this line

File: doc/make.jl [hunk 5]
```diff
@@ -1,152 +0,0 @@
-# Install dependencies needed to build the documentation.
```
Comment (tkelman) [inline doc/make.jl]: put this back

**Review by tkelman — DISMISSED** [review]

File: NEWS.md (hunk 4 above)
Comment (vtjnash) [inline NEWS.md]: The comma makes this a dependent clause, which I think is preferable here (the additional statements are present for additional clarity, but aren't as uniformly true as the first statement).

File: doc/make.jl (hunk 5 above)
Comment (vtjnash) [inline doc/make.jl]: fortunately, it looks like AppVeyor won't give this PR a passing mark without this (but FreeBSD will). Need to merge a couple PRs to the doc packages first.

File: NEWS.md (hunk 4 above)
Comment (tkelman) [inline NEWS.md]: "with a new, undefined `sin` variable" is an incomplete fragment with no clear subject of its own

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22984#issuecomment-318718929) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3abb7f1ff67009ace0f2a77c4fdd16aa7ecc0c01/145351a_vs_100a6fc/report.md). cc @ararslan

File: src/julia-syntax.scm (hunk 2 above)
Comment (StefanKarpinski) [inline src/julia-syntax.scm]: maybe put this in a separate PR, especially if it's a completely independent change?

File: test/core.jl [hunk 6]
```diff
@@ -5089,3 +5089,34 @@ m22929_2.x = m22929_1
...
 @test isdefined_22929_x(m22929_2)
+
+# issue 18933
+module GlobalDef18933
+    using Base.Test
+    # test that global declaration vs assignment operates correctly in local scope
+    f() = (global sin; nothing)
+    g() = (global cos; cos = 2; nothing)
+    @test @isdefined sin
+    @test !@isdefined cos
```
Comment (StefanKarpinski) [inline test/core.jl]: It would be handy here to have some way to test what a binding refers to without dereferencing it, but that may be beyond the scope of this PR. E.g. `resolvebinding(:sin) == :(Base.sin)` and `resolvebinding(:cos) == :cos`.

File: test/core.jl [hunk 7]
```diff
@@ -5089,3 +5089,34 @@ m22929_2.x = m22929_1
...
+        @test @isdefined tan
+        @test tan() === nothing
+    end
+    # test that global declaration side-effects ignore conditionals
+    if false
+        global sincos
+        nothing
+    end
+    @test !@isdefined sincos
+    @test isdefined(Base, :sincos)
```
Comment (StefanKarpinski) [inline test/core.jl]: I find this last one slightly surprising, but I suppose it fall naturally out of `if` not introducing scope. Should this also test the same things with assignment?

**Review by vtjnash — COMMENTED** [review]
Jeff and I have discussed some of the implications of this fix for the `global` keyword, and have decided we should change the meaning of the keyword slightly, affecting the error case.

Currently, `global` means "make a new global" when used as a toplevel statement, but means "there is a global" when used anywhere else. Typically these two statements actually end up doing the same action, and thus differ only in the warning / error case.

This PR had been written to fix the keyword to mean "make a new global" when used in global scope or when there is an assignment to a global in local scope. But to otherwise mean "there is a global".

We have instead decided it should always mean "there is a global". This mainly just impacts cases where we currently give a warning ("WARNING: imported binding for sin overwritten in module Main"), and instead makes that operation a no-op. Because that means bindings can no longer be deleted (which was invalid anyways for various reasons), assignment to an existing global imported from another module will now emit an error ("cannot assign variables in other modules") rather than emitting a warning.

File: src/julia-syntax.scm (hunk 3 above)
Comment (vtjnash) [inline src/julia-syntax.scm]: Also, while having `jl_resolve_globals` do this will mostly work, it's still broken if the global code has any other side-effects, since the current scope rules can't preserve the happens-before relationship the user may have intended. Ignoring the trivial cases like code that uses `eval` or `include`, another example of where we must give the wrong behavior is if `import` is in the same block as `global`. (so `import Foo.bar; global bar() = 3` will execute in the wrong order, for example)

File: NEWS.md (hunk 4 above)
Comment (tkelman) [inline NEWS.md]: the comma here does not make sense and should be removed. "with ..." is not standalone, it is directly describing the shadowing

File: src/module.c [hunk 8]
```diff
@@ -129,26 +127,29 @@ JL_DLLEXPORT jl_module_t *jl_get_module_of_binding(jl_module_t *m, jl_sym_t *var
...
-                jl_errorf("error in method definition: function %s.%s must be explicitly imported to be extended", jl_symbol_name(b->owner->name),
-                          jl_symbol_name(var));
+        if (b->owner != m) {
+            if (b->owner == NULL) {
+                b->owner = m;
+            }
+            else {
+                jl_binding_t *b2 = jl_get_binding(b->owner, var);
+                if (b2 == NULL || b2->value == NULL)
+                    jl_errorf("invalid method definition: imported function %s.%s does not exist", jl_symbol_name(b->owner->name), jl_symbol_name(var));
```
Comment (tkelman) [inline src/module.c]: wrap long line

File: NEWS.md (hunk 4 above)
Comment (StefanKarpinski) [inline NEWS.md]: this is not important

Comment (tkelman) [inline NEWS.md]: these are the release notes, which people will read, they should read clearly

Comment (vtjnash) [inline NEWS.md]: https://en.wikipedia.org/wiki/Relative_clause#Restrictive_and_non-restrictive

If it was a complete fragment, this would be a comma splice. The rest of the sentence, on the other hand, is complete and stands on its own.

File: src/julia-syntax.scm (hunk 2 above)
Comment (vtjnash) [inline src/julia-syntax.scm]: It's largely just a re-indentation to accommodate printing the error message. It seems that lisp just usually makes trivial edits require re-indenting the entire function :(

**Comment by JeffBezanson** [comment]
I've been kicking the tires on this a bit and it seems good. :+1:

**Review by JeffBezanson — APPROVED** [review]
