### PR TITLE
Overload `Base.literal_pow` for `AbstractQ`

### LINKED ISSUE #1060: AbstractQ literal_pow (Q^2) missing
`Base.literal_pow` should be overloaded so that `Q^2` works, i.e., we want the following to not error:

```julia
julia> Q = qr(randn(5,5)).Q
5×5 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}

julia> Q*Q
5×5 Matrix{Float64}:
 -0.908458   0.15328    0.171023   0.346546    0.0431982
 -0.0574299  0.850477  -0.260641  -0.419498    0.171693
  0.0887003  0.307879   0.330109   0.0439806  -0.886813
  0.381531   0.369071   0.5402     0.521318    0.393233
  0.134058   0.148969  -0.70854    0.655912   -0.166092

julia> Q^2
ERROR: MethodError: no method matching ^(::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, ::Int64)

Closest candidates are:
  ^(::Regex, ::Integer)
   @ Base regex.jl:863
  ^(::Missing, ::Integer)
   @ Base missing.jl:165
  ^(::Missing, ::Number)
   @ Base missing.jl:123
  ...

Stacktrace:
 [1] literal_pow(f::typeof(^), x::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, ::Val{2})
   @ Base ./intfuncs.jl:351
 [2] top-level scope
   @ REPL[177]:1
```

### LINKED ISSUE #53989: AbstractQ literal_pow (Q^2) missing
`Base.literal_pow` should be overloaded so that `Q^2` works, i.e., we want the following to not error:

```julia
julia> Q = qr(randn(5,5)).Q
5×5 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}

julia> Q*Q
5×5 Matrix{Float64}:
 -0.908458   0.15328    0.171023   0.346546    0.0431982
 -0.0574299  0.850477  -0.260641  -0.419498    0.171693
  0.0887003  0.307879   0.330109   0.0439806  -0.886813
  0.381531   0.369071   0.5402     0.521318    0.393233
  0.134058   0.148969  -0.70854    0.655912   -0.166092

julia> Q^2
ERROR: MethodError: no method matching ^(::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, ::Int64)

Closest candidates are:
  ^(::Regex, ::Integer)
   @ Base regex.jl:863
  ^(::Missing, ::Integer)
   @ Base missing.jl:165
  ^(::Missing, ::Number)
   @ Base missing.jl:123
  ...

Stacktrace:
 [1] literal_pow(f::typeof(^), x::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, ::Val{2})
   @ Base ./intfuncs.jl:351
 [2] top-level scope
   @ REPL[177]:1
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes JuliaLang/LinearAlgebra.jl#1060.

There's a decision to be made here. What do we want `Q^-1` to return? `Q'::AbstractQ` or `Q'*I::Matrix`? On Julia v1.9 and older, `Q^p` returned the matrix representation for any `p` except `p=-1`, where it returned `inv(Q)` which was defined to be `Q'`. I have returned to this behavior after finding out.

### CODE REVIEW

**Comment by dkarrasch** [comment]
I changed things to the matrix approach: so only `Q^(+/-1)` are lazy, all other powers use `power_by_squaring`. @dlfivefifty Could you please take a quick look?

File: stdlib/LinearAlgebra/src/abstractq.jl [hunk 1]
```diff
@@ -18,6 +18,10 @@ transpose(Q::AbstractQ{<:Real}) = AdjointQ(Q)
 transpose(Q::AbstractQ) = error("transpose not implemented for $(typeof(Q)). Consider using adjoint instead of transpose.")
 adjoint(adjQ::AdjointQ) = adjQ.Q
 
+(^)(Q::AbstractQ, p::Integer) = p < 0 ? power_by_squaring(inv(Q), -p) : power_by_squaring(Q, p)
+@inline Base.literal_pow(::typeof(^), Q::AbstractQ, ::Val{1}) = Q
+@inline Base.literal_pow(::typeof(^), Q::AbstractQ, ::Val{-1}) = inv(Q)
```
Comment (mbauman) [inline stdlib/LinearAlgebra/src/abstractq.jl:23]:
```suggestion
```

Is there a reason for these? The fallback should work just fine here, no?

**Comment by mbauman** [comment]
Ah, ok, I see. This is fallout from https://github.com/JuliaLang/julia/pull/46196, where we lost the `AbstractArray` `^` method.

**Comment by dkarrasch** [comment]
Hihi, technically, one could make `Q^p::AbstractQPower <: AbstractQ` and lazy, similar to `Q^1` and `Q^-1`. :smile: If `Q` is not a matrix, why should `Q^p` be? For instance, we loose the size flexibility of the right-most copy of `Q` in `Q*Q*...*Q`.

**Comment by dlfivefifty** [comment]
`Q^2` should be equal to `Q*Q`. Since the latter works so should the former.

**Comment by dkarrasch** [comment]
Ok, then I think this is ready to go, isn't it?

**Review by dlfivefifty — APPROVED** [review]

**Comment by dlfivefifty** [comment]
Looks fine to me! Thanks!
