### PR TITLE
Array fixes for non-power-of-2 sized elements

### LINKED ISSUE #287: EXCEPTION_ACCESS_VIOLATION working with UInt160
The file `test.csv` contains:
```
from,to,value
0x3f2f381491797cc5c0d48196c14fd0cd00cdfa2d,0x4bd5f0ee173c81d42765154865ee69361b6ad289,803990000000000000000
0xfd2605a2bf58fdbb90d11da55df61628b47f9e8c,0x88b3672d21fecaa5313c37c59de4ed53fd8c72fd,10000000000000000
0xf55cdbdf978f539ea4ee10621f7f1a0f9f00f7d9,0x6baf48e1c966d16559ce2dddb616ffa720048512,5000000000000000
0x6baf48e1c966d16559c12dddb616ffa72004851e,0xf55cdbdf978f539ea4eee0621f7f1a0f9f00f7d2,50000000000000000
0xaf880fc7567d5595cacc115c3fc14c8742c26c9e,0x543807d0af2c58b49d7f25659d0472d4d8b8e82a,20000000000000000000
0xa1e4380a3b1f749673e170229993ee55f35663b4,0x0000000000000000000000000000000000002000,0
0xa89ac93b23370472daa1337e9afdf642543f3e57,0xb5046cb3dc1dedbd364514a2848e44c1de4e2147,1000000000000000000000
0xf86a3ea8071f7095c7db1a05ae507a8929dbb876,0x7cd05927fe0aa3b6552db959e7539ae28dcb2dcf,100000000000000000000
0x39d4a931402c0c79c451186f24df8729cf957031,0xe1f5b8dc9336bc9637ea97c3f3b13cd363f88824,999590000000000000000
0xa89ac93b23370472daa1337e9afdf642543f3e57,0xb5046cb3dc1dedbd364514a2848e44c1de4e2147,1000000000000000000000
```

With Julia 1.1.0, JuliaDB 0.12.0 I run:

```
using JuliaDB, JuliaDBMeta, BitIntegers, TextParse, DataValues

BitIntegers.@define_integers 160 AddressInt AddressUInt

AddressUInt_parser = CustomParser(AddressUInt) do str, i, len, opts
    ii = findnext(isequal(','), str, i)
    return DataValues.DataValue{AddressUInt}(parse(AddressUInt, str[i:ii-1])), ii 
end

@time transactions = JuliaDB.loadtable("C:\\Users\\Max\\Desktop\\test.csv",
    colparsers = Dict(
        "from" => AddressUInt_parser, 
        "to" => AddressUInt_parser,
        "value" => UInt64)
)
```
and get:
```
11.378640 seconds (45.11 M allocations: 2.185 GiB, 5.40% gc time)
Table with 10 rows, 3 columns:
Columns:
#  colname  type
───────────────────────
1  from     AddressUInt
2  to       AddressUInt
3  value    Float64
```
But:
```
JuliaDB.save(transactions, "C:\\Users\\Max\\Desktop\\test2")
```
yields:
```
ArgumentError: unsafe_wrap: pointer 00000000001F0244 is not properly aligned to 8 bytes
```

And:
```
reindex(transactions, :to)
```
(not always, but run it a couple of times, or with `:from:`) yields:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x43a2e751a -- jl_gc_alloc_ at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:1112 [inlined]
jl_gc_alloc at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:2911
in expression starting at no file:0
jl_gc_alloc_ at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:1111 [inlined]
jl_gc_alloc at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:2911
_new_array_ at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:100
_new_array at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:160 [inlined]
jl_alloc_array_1d at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:420
Type at .\boot.jl:402 [inlined]
Type at .\boot.jl:411 [inlined]
similar at .\array.jl:317 [inlined]
similar at .\abstractarray.jl:573 [inlined]
_unsafe_getindex at .\multidimensional.jl:654
_getindex at .\multidimensional.jl:642 [inlined]
getindex at .\abstractarray.jl:927 [inlined]
#65 at C:\Users\Max\.julia\packages\StructArrays\Du4zZ\src\structarray.jl:131
macro expansion at .\namedtuple.jl:182 [inlined]
map at .\namedtuple.jl:177 [inlined]
getindex at C:\Users\Max\.julia\packages\StructArrays\Du4zZ\src\structarray.jl:131
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
#reindex#164 at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:94
unknown function (ip: 000000001D1053DB)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:81
unknown function (ip: 000000001D1050D2)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
#reindex#164 at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:85
unknown function (ip: 000000001D104F5B)
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:42
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:81 [inlined]
#reindex#165 at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:99 [inlined]
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:99
unknown function (ip: 000000001D104AAE)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:99
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:411
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:362 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:755
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:885
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 0000000008B5909F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_toplevel_eval at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:773 [inlined]
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:793
eval at .\boot.jl:328
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\REPL\src\REPL.jl:117 [inlined]
#26 at .\task.jl:259
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:572
Allocations: 77644630 (Pool: 77631017; Big: 13613); GC: 171

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x43a2e751a -- jl_gc_alloc_ at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:1112 [inlined]
jl_gc_alloc at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:2911
in expression starting at no file:0
jl_gc_alloc_ at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:1111 [inlined]
jl_gc_alloc at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:2911
_new_array_ at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:100
_new_array at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:160 [inlined]
jl_alloc_array_1d at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:420
Type at .\boot.jl:402 [inlined]
Type at .\boot.jl:416 [inlined]
Type at .\compiler/ssair\ir.jl:489
Type at .\compiler/ssair\ir.jl:487 [inlined]
compact! at .\compiler/ssair\ir.jl:1268
run_passes at .\compiler/ssair\driver.jl:117
optimize at .\compiler\optimize.jl:164
typeinf at .\compiler\typeinfer.jl:35
typeinf_ext at .\compiler\typeinfer.jl:576
typeinf_ext at .\compiler\typeinfer.jl:613
jfptr_typeinf_ext_1.clone_1 at C:\Users\Max\AppData\Local\Julia-1.1.0\lib\julia\sys.dll (unknown line)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
jl_type_infer at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:277
jl_compile_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1819 [inlined]
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1863
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
jl_atexit_hook at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\init.c:234
jl_exit at /home/Administrator/buildbot/worker/package_win64/build/src\jl_uv.c:592
jl_exception_handler at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\signals-win.c:310
__julia_personality at /home/Administrator/buildbot/worker/package_win64/build/src/support\win32_ucontext.c:28
_chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlWalkFrameChain at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
jl_gc_alloc_ at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:1111 [inlined]
jl_gc_alloc at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:2911
_new_array_ at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:100
_new_array at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:160 [inlined]
jl_alloc_array_1d at /home/Administrator/buildbot/worker/package_win64/build/src\array.c:420
Type at .\boot.jl:402 [inlined]
Type at .\boot.jl:411 [inlined]
similar at .\array.jl:317 [inlined]
similar at .\abstractarray.jl:573 [inlined]
_unsafe_getindex at .\multidimensional.jl:654
_getindex at .\multidimensional.jl:642 [inlined]
getindex at .\abstractarray.jl:927 [inlined]
#65 at C:\Users\Max\.julia\packages\StructArrays\Du4zZ\src\structarray.jl:131
macro expansion at .\namedtuple.jl:182 [inlined]
map at .\namedtuple.jl:177 [inlined]
getindex at C:\Users\Max\.julia\packages\StructArrays\Du4zZ\src\structarray.jl:131
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
#reindex#164 at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:94
unknown function (ip: 000000001D1053DB)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:81
unknown function (ip: 000000001D1050D2)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
#reindex#164 at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:85
unknown function (ip: 000000001D104F5B)
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:42
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:81 [inlined]
#reindex#165 at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:99 [inlined]
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:99
unknown function (ip: 000000001D104AAE)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
reindex at C:\Users\Max\.julia\packages\IndexedTables\OaPrA\src\selection.jl:99
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:411
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:362 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:755
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:885
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 0000000008B5909F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_toplevel_eval at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:773 [inlined]
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:793
eval at .\boot.jl:328
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\REPL\src\REPL.jl:117 [inlined]
#26 at .\task.jl:259
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:572
Allocations: 77646265 (Pool: 77632652; Big: 13613); GC: 171
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Before:
```
julia> primitive type TypeWith24Bits 24 end

julia> x = Core.Intrinsics.trunc_int(TypeWith24Bits, 0x112233); a = [x,x];

julia> Core.arrayset(true, a, x, 2)
2-element Array{TypeWith24Bits,1}:
 TypeWith24Bits(0x112233)
 TypeWith24Bits(0x111122)
```

After: works.

Fixes https://github.com/JuliaComputing/JuliaDB.jl/issues/287#issuecomment-507281028

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -6461,6 +6461,13 @@ let A=[0, missing], B=[missing, 0], C=Vector{Union{Int, Missing}}(undef, 6)
     @test isequal(C, [0, missing, missing, missing, 0, missing])
 end
 
+# non-power-of-2 element sizes
+primitive type TypeWith24Bits 24 end
+let x = Core.Intrinsics.trunc_int(TypeWith24Bits, 0x112233), a = [x,x]
+    Core.arrayset(true, a, x, 2)
```
Comment (vtjnash) [inline test/core.jl]: `a[2] = x`, or are you intentionally trying to avoid this being compiled (could use a comment)?

Can you add a test for `a = [(x, x), (x, x)]` also?

Might be good to use something other than `x` here also, so that the mutation here is observable.

Comment (JeffBezanson) [reply test/core.jl]: OK. Yes, I was trying to avoid the compiled form since I believe it does the right thing.

**Comment by chethega** [comment]
Can we add the backport label?

Reason is that `@code_native Base.elsize([])` is a real mess before (afaiu because `Core.sizeof(Ptr)` and `Ptr` is non-concrete, which messes up constant folding). Now we use `Core.sizeof(Ptr{Cvoid})` which constant folds properly.

**Comment by JeffBezanson** [comment]
In julia 1.x:
```
julia> @code_native Base.elsize([])
	.text
; Function elsize {
; Location: abstractarray.jl:106
	movl	$8, %eax
	retq
	nopw	%cs:(%rax,%rax)
;}
```

How to reproduce what you're seeing?

**Comment by chethega** [comment]
```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5###U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

julia> @code_typed Base.elsize([])
CodeInfo(
1 ─ %1 = Base.Ptr::Type{Ptr}
│   %2 = Core.sizeof::typeof(Core.sizeof)
│   %3 = (%2)(%1)::Int64
└──      return %3
) => Int64

julia> @code_native Base.elsize([])
	.text
; ┌ @ abstractarray.jl:153 within `elsize' @ array.jl:201
; │┌ @ abstractarray.jl:153 within `sizeof'
	pushq	%rax
	movabsq	$140487341557840, %rax  # imm = 0x7FC5C216C850
	movq	%rax, (%rsp)
	movabsq	$jl_f_sizeof, %rax
	movq	%rsp, %rsi
	xorl	%edi, %edi
	movl	$1, %edx
	callq	*%rax
; │└
; │ @ abstractarray.jl:153 within `elsize'
	movq	(%rax), %rax
	popq	%rcx
	retq
	nopw	(%rax,%rax)

```
That is fixed on master. I saw the spurious `jl_f_sizeof` call in some `pointer(a, i)` and tracked the fix back to this PR. I have only tested master and 1.2.0, but `git blame` suggests that it is not a recent regression.

`Core.sizeof(Ptr)` is not constant-folded on master either, but your PR changed to `Core.sizeof(Ptr{Cvoid})` (and also fixed the original issue, and also added `@pure` good measure). A minimal backport would just replace `Core.sizeof(Ptr)` with `Core.sizeof(Ptr{Cvoid})`.

**Comment by KristofferC** [comment]
```
julia> @code_native Base.elsize([])
        .text
; ┌ @ abstractarray.jl:153 within `elsize'
        movl    $8, %eax
        retq
        nopw    %cs:(%rax,%rax)
; └
```

on 1.3 at least.
