### PR TITLE
[REPLCompletions] allow symbol completions within incomplete macrocall expression

### LINKED ISSUE #51827: Tab completion doesn't work in macros together with module qualification
Seems specific to some macros, e.g.
```
@code_warntype Base.ac<TAB>  # gives nothing
@time Base.ac<TAB>           # works
```

### PR DESCRIPTION
**Pull request by aviatesk**
fix #51827

### CODE REVIEW

File: stdlib/REPL/test/replcompletions.jl [hunk 1]
```diff
@@ -2085,6 +2085,18 @@ for (s, compl) in (("2*CompletionFoo.nam", "named"),
...
+# allows symbol completion within incomplete :macrocall
+# https://github.com/JuliaLang/julia/issues/51827
+macro issue51827(args...)
+    length(args) ≥ 2 || error("@issue51827: incomplete arguments")
+    return args
+end
+let s = "@issue51827 Base.ac"
+    c, r, res = test_complete_context(s)
+    @test res
+    "aquire" in c
```
Comment (KristofferC) [inline stdlib/REPL/test/replcompletions.jl:2097]:
```suggestion
    @test "acquire" in c
```

or?

Comment (aviatesk) [reply stdlib/REPL/test/replcompletions.jl:2097]: Ah, yes. Thanks.
