### PR TITLE
fix #11726: updates for llvm-svn api changes

### LINKED ISSUE #11726: New failure when building on Windows + LLVM SVN
Hi, 
I tried the 2 in 1 of rebuilding the Win LLVM3.7 version and using the @tkelman  tk/winbuild branch but I'm getting this error now. I suspect it has nothing to do with the winbuild branch but I'm mentioning it in case it does

    codegen.cpp: In function 'void jl_setup_module(llvm::Module*, bool)':
    codegen.cpp:708:63: error: no matching function for call to 'llvm::Module::setTargetTriple(const llvm::Triple&)'
         m->setTargetTriple(jl_TargetMachine->getTargetTriple());
                                                               ^
    In file included from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22:0,
                 from codegen.cpp:12:
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note: candidate: void llvm::Module::setTargetTriple(llvm::StringRef)
    void setTargetTriple(StringRef T) { TargetTriple = T; }
        ^
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note:   no known conversion for argument 1 from 'const llvm::Triple' to 'llvm::StringRef'
    codegen.cpp: In function 'void jl_init_codegen()':
    codegen.cpp:5771:59: error: no matching function for call to 'llvm::Module::setTargetTriple(const llvm::Triple&)'
     m->setTargetTriple(jl_TargetMachine->getTargetTriple());
                                                           ^
    In file included from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22:0,
                 from codegen.cpp:12:
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note: candidate: void llvm::Module::setTargetTriple(llvm::StringRef)
    void setTargetTriple(StringRef T) { TargetTriple = T; }
        ^
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note:   no known conversion for argument 1 from 'const llvm::Triple' to 'llvm::StringRef'
    codegen.cpp:5772:71: error: no matching function for call to 'llvm::Module::setTargetTriple(const llvm::Triple&)'
     engine_module->setTargetTriple(jl_TargetMachine->getTargetTriple());
                                                                       ^
    In file included from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22:0,
                 from codegen.cpp:12:
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note: candidate: void llvm::Module::setTargetTriple(llvm::StringRef)
    void setTargetTriple(StringRef T) { TargetTriple = T; }
        ^
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note:   no known conversion for argument 1 from 'const llvm::Triple' to 'llvm::StringRef'
    Makefile:72: recipe for target 'codegen.o' failed

### PR DESCRIPTION
**Pull request by ihnorton**

### CODE REVIEW

File: src/cgutils.cpp [hunk 1]
```diff
@@ -1397,7 +1397,13 @@ static Value *emit_getfield_knownidx(Value *strct, unsigned idx, jl_datatype_t *
         }
     }
     else if (strct->getType()->isPointerTy()) { // something stack allocated
+#       ifdef LLVM37
+        Value *addr = builder.CreateConstInBoundsGEP2_32(
+            cast<PointerType>(strct->getType()->getScalarType())->getElementType(),
+            strct, 0, idx);
```
Comment (ihnorton) [inline src/cgutils.cpp]: not sure if this is correct. I thought that it would just be `elty` here, but that causes LLVM to assert out, so I used the type that is checked in the failing assertion... seems to work, but unsightly.

Comment (ihnorton) [inline src/cgutils.cpp]: @vtjnash

Comment (vtjnash) [inline src/cgutils.cpp]: i think you can write the same a bit more concisely as `strct->getContainedType(0)`. i'm surprised as well that it's not the same as `elty` in some or all cases though.

Comment (ihnorton) [inline src/cgutils.cpp]: I'll check and change later. the failing case was `GenSym` in inference, FWIW.
