### PR TITLE
REPL: improve prompt! async function handler

### LINKED ISSUE #54754: REPL errors "randomly" after fake Pkg prompt
Just as an example:

image

```
(Base) julia> Base.explicit_loadUnhandled Task ERROR: TaskFailedException

    nested task error: ArgumentError: IOBuffer not marked
    Stacktrace:
     [1] reset
       @ ./io.jl:1429 [inlined]
     [2] reset
       @ ./stream.jl:1489 [inlined]
     [3] peek(s::TTY, ::Type{Char})
       @ Base ./stream.jl:1496
     [4] peek(t::REPL.Terminals.TTYTerminal, ::Type{Char})
       @ REPL.Terminals ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/Terminals.jl:161
     [5] (::REPL.LineEdit.var"#281#283"{REPL.Terminals.TTYTerminal})()
       @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/LineEdit.jl:2834
Stacktrace:
 [1] _wait_multiple(waiting_tasks::Tuple{Task, Task}, throwexc::Bool, all::Bool, failfast::Bool)
   @ Base ./task.jl:513
 [2] _wait_multiple
   @ ./task.jl:417 [inlined]
 [3] waitany
   @ ./task.jl:397 [inlined]
 [4] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
   @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/LineEdit.jl:2833
 [5] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
   @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/LineEdit.jl:2743
 [6] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
   @ REPL ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:1504
 [7] (::REPL.var"#75#81"{REPL.LineEditREPL, REPL.REPLBackendRef})()
   @ REPL ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:496
ERROR: TaskFailedException
Stacktrace:
  [1] try_yieldto(undo::typeof(ensure_rescheduled))
    @ Base ./task.jl:1100
  [2] wait()
    @ Base ./task.jl:1164
  [3] wait(c::GenericCondition{ReentrantLock}; first::Bool)
    @ Base ./condition.jl:139
  [4] wait
    @ ./condition.jl:134 [inlined]
  [5] take_buffered(c::Channel{Any})
    @ Base ./channels.jl:493
  [6] take!
    @ ./channels.jl:487 [inlined]
  [7] repl_backend_loop(backend::REPL.REPLBackend, get_module::Function)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:353
  [8] start_repl_backend(backend::REPL.REPLBackend, consumer::Any; get_module::Function)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:343
  [9] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_
```

Probably related to https://github.com/JuliaLang/julia/pull/54674 looking at the blame.

cc @IanButterworth

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/54754

Or at least that's the intention. @vtjnash does this look better? From some quick testing it seems robust but I wasn't sure whether it would cause noise when people interrupt running code?

### CODE REVIEW

**Comment by vtjnash** [comment]
This seems much better as an architecture. Ideally we could unify it better so that match_input would return these other fcn also, instead of needing a lock and a second Task to deal with them, but the lock already provides that required synchronization

**Review by vtjnash — APPROVED** [review]

File: stdlib/REPL/src/LineEdit.jl [hunk 1]
```diff
@@ -2828,40 +2828,45 @@ function prompt!(term::TextTerminal, prompt::ModalInterface, s::MIState = init_s
     try
         activate(prompt, s, term, term)
         old_state = mode(s)
+        l = Base.ReentrantLock()
+        t = @async while true
+            fcn = take!(s.async_channel)
+            status = @lock l fcn(s)
```
Comment (Keno) [inline stdlib/REPL/src/LineEdit.jl:2834]: I don't think this works. `match_input` needs to be serialized with any potential execution of this function, which may affect the keymap, make arbitrary modifications to the REPL, etc.

Comment (Keno) [reply stdlib/REPL/src/LineEdit.jl:2834]: no, that doesn't work either. The semantics need to be that waiting for the input (through either channel) happens outside the lock, but the modification of the channel `take!` or `read` happens only inside the lock. Otherwise, you're potentially dropping input.
