### PR TITLE
only use accurate powf function

### LINKED ISSUE #19872: ^(::Float64, ::Integer) incorrect subnormal results
For some reason `powi` seems to be flushing some subnormals to zero:

From 0.4 (correct behaviour):
```
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> 2.0^(-1022)
2.2250738585072014e-308

julia> 2.0^(-1023)
1.1125369292536007e-308

julia> 2.0^(-1024)
5.562684646268003e-309
```

On 0.5 (incorrect)
```

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

julia> 2.0^(-1022)
2.2250738585072014e-308

julia> 2.0^(-1023)
1.1125369292536007e-308

julia> 2.0^(-1024)
0.0
```

On master (incorrect)
```
julia> versioninfo()
Julia Version 0.6.0-dev.1898
Commit 2e0b00180* (2017-01-04 13:04 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> 2.0^(-1022)
2.2250738585072014e-308

julia> 2.0^(-1023)
1.1125369292536007e-308

julia> 2.0^(-1024)
0.0
```

### PR DESCRIPTION
**Pull request by vtjnash**
The powi intrinsic optimization over calling powf is that it is inaccurate.
We don't need that.

When it is equally accurate (e.g. tiny constant powers),
LLVM will already recognize and optimize any call to a function named `powf`,
and produce the same speedup.

fix #19872

### CODE REVIEW

**Comment by vtjnash** [comment]
Note that this reverts https://github.com/JuliaLang/julia/issues/2741#issuecomment-47008166 (e.g. restores https://github.com/JuliaLang/julia/commit/f2b3192eb2e59dd34e1e2838036a13167410814f), since being correct is more important than being a few % faster.

File: test/math.jl [hunk 1]
```diff
@@ -959,9 +959,13 @@ end
 end
 
 @testset "issue #13748" begin
-    let A = [1 2; 3 4]; B = [5 6; 7 8]; C = [9 10; 11 12]
-        @test muladd(A,B,C) == A*B + C
-    end
```
Comment (JeffBezanson) [inline test/math.jl]: Did you mean to delete this?

File: src/codegen.cpp [hunk 2]
```diff
@@ -5964,7 +5961,7 @@ static void init_julia_llvm_env(Module *m)
         &pow,
```
Comment (yuyichao) [inline src/codegen.cpp]: This breaks compilation here.

What's the reason again that we can't do the `static_cast` unconditionally? Including `<math.h>` in C++ code causes `using std::pow;` which provides additional overloads for `float` and `long double`.

Comment (yuyichao) [inline src/codegen.cpp]: More precisely what `glibc` + `libstdc++`/`libc++` do when `<math.h>` is directly included by c++ code is roughly

```c++
extern double pow(double, double);

namespace std {
using ::pow;
float pow(float, float);
long double pow(long double, long double);
// template version for promotion...
}

using std::pow;
```

It shouldn't be possible to overwrite a previously defined `::pow(double, double)` so I expect MSVC to do something similar and it should be safe in general to specify the overload type using a `static_cast`.

Comment (vtjnash) [inline src/codegen.cpp]: My main concern would be whether those are the same function. I would expect that the C++ version is getting name mangled might not end up picking up the openlibm version.

Comment (yuyichao) [inline src/codegen.cpp]: I don't think that is an issue.

1. These should be inline functions that calls the C `::pow`, `::powf`, `::powl`.
2. For C++ implementations that provide these it shouldn't be allowed to overwrite the existing `::pow(double, double)` symbol so the it should always be the C one.
3. At least in the generic linux binary `cglobal(:pow)` and `ccall(:pow, ..)` points to the `libm` version.

**Comment by StefanKarpinski** [comment]
Are we moving ahead with this? If not, we should remove the 0.6.0 label. If so, it would be good to get the tests passing...

**Comment by vtjnash** [comment]
That's the plan, just made an error in rebasing. But it also now made a good excuse to try out the new `llvmcall` support.

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by tkelman** [comment]
replutil test failure on win32 is real - probably related to #17251, will see if locally running with `--precompiled=no` makes it pass

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19890#issuecomment-274725188) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a00a4a716b498ec9cd3b42e8f4925687674aebe7/74776c0_vs_06fa32c/report.md). cc @jrevels

**Comment by StefanKarpinski** [comment]
Another failure in `test/replutil.jl`...?

**Comment by JeffBezanson** [comment]
`test/replutil` tends to generate action-at-a-distance test failures, since it looks at e.g. what is printed for method tables of Base functions. Change some methods and the output changes.

**Comment by tkelman** [comment]
This failure is very specific to debug info in backtraces for the pow function. Not action at a distance at all, for this PR.

**Comment by vtjnash** [comment]
>  [1] nan_dom_err; at .\math.jl:311 [inlined]

looks like the name-demanger is getting confused here, nothing to do with #17251

**Comment by vtjnash** [comment]
> possible performance regressions were detected

Just a note that these performance reductions are both expected and intentional. It's good that we have a record of them though, and will probably want to link back here / note this on the nightly as well.

**Comment by KristofferC** [comment]
Is it expected that `exp` became a lot slower as well? I thought we had a pure julia version of that right now.

**Comment by tkelman** [comment]
We should probably revert exp back to using openlibm then, if changing the pow calculation used by julia is going to be this expensive. Or change its code to opt in to the other pow version, if it isn't needed for accuracy in the innards of the exp implementstion? cc @musm

**Comment by KristofferC** [comment]
The julia code for `exp` seemed very well tested for accuracy so it should be possible to keep the performance for `exp` which is where a lot of the slowdowns are being reported.

**Comment by tkelman** [comment]
could `@fastmath` be usable for allowing users to annotate whether they prefer accuracy or speed for this?

**Comment by vtjnash** [comment]
yes, `FastMath.pow` implements the fast (previous) version

**Comment by vtjnash** [comment]
It looks like `exp` was just computing `2 ^ constant`, and my change was stopping it from doing constant propagation / inlining. Easy fix.

**Comment by tkelman** [comment]
great @nanosoldier `runbenchmarks(ALL, vs=":master")`

File: base/math.jl [hunk 3]
```diff
@@ -677,14 +679,11 @@ function modf(x::Float64)
...
-^(x::Float64, y::Float64) = nan_dom_err(ccall((:pow,libm),  Float64, (Float64,Float64), x, y), x+y)
-^(x::Float32, y::Float32) = nan_dom_err(ccall((:powf,libm), Float32, (Float32,Float32), x, y), x+y)
-
-^(x::Float64, y::Integer) = x^Int32(y)
-^(x::Float64, y::Int32) = powi_llvm(x, y)
-^(x::Float32, y::Integer) = x^Int32(y)
-^(x::Float32, y::Int32) = powi_llvm(x, y)
-^(x::Float16, y::Integer) = Float16(Float32(x)^y)
+@inline ^(x::Float64, y::Float64) = nan_dom_err(ccall("llvm.pow.f64", llvmcall, Float64, (Float64, Float64), x, y), x + y)
+@inline ^(x::Float32, y::Float32) = nan_dom_err(ccall("llvm.pow.f32", llvmcall, Float32, (Float32, Float32), x, y), x + y)
```
Comment (musm) [inline base/math.jl]: I might have missed something, but why now llvm for `^` when both arguments are floats? the libm pow function is accurate.

Comment (vtjnash) [inline base/math.jl]: It resolves to the same function, but give an optimization hint for llvm that we mean *that* pow, and not just some random function named pow.

**Comment by musm** [comment]
https://github.com/JuliaLang/julia/blob/e577f8e763d81fd8fa24e37859881d45c145b857/base/math.jl#L508
Also needs  `^ = Base.FastMath.pow_fast `  for similar reason. Should trigger a regression.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19890#issuecomment-275744024) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c55b9b4ecdc84f73fb916d5696d0181d4d539514/441405c_vs_8091c21/report.md). cc @jrevels

**Comment by tkelman** [comment]
ldexp uses pow in the subnormal case, which maybe nanosoldier didn't hit? looks like it's only powers of two so should also use the fast version

**Comment by vtjnash** [comment]
I also fixed pow to do constant propagation, so it doesn't show up anymore.

**Comment by tkelman** [comment]
Where and how? That sounds easy to break if it isn't tested and tracked.

**Comment by vtjnash** [comment]
I added `@inline` so the inliner would stop getting tripped up by the cold branch for error checking. We have perf testing for this now.

**Comment by tkelman** [comment]
including the subnormal branch of ldexp?

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vtjnash** [comment]
What's that got to do with anything? Nanosoldier was already run before I rebased this today (https://github.com/JuliaLang/julia/pull/19890#issuecomment-275796933)

**Comment by tkelman** [comment]
@musm requested that you use the fast pow in ldexp which you have not done

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/19890#issuecomment-275980514):
```
NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]")
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e6157010d42bbc53a36031945702b0751be2cb70/a45b4f9_vs_65afe47/report.md)
cc @jrevels

**Comment by jrevels** [comment]
Nanosoldier is failing on master right now, so the failure here is probably unrelated to this PR (ref [my comment here](https://github.com/JuliaLang/julia/commit/65afe479cfd5afd6c782aafc2a18dac5a55cb4de#commitcomment-20657791))

**Comment by KristofferC** [comment]
Are we waiting for nanosoldier to work again to check before this is merged?

**Comment by tkelman** [comment]
waiting for ldexp and exp to use a consistent choice of pow between the two. if fast pow is no longer necessary in exp either then yes nanosoldier will be needed to verify that

**Comment by tkelman** [comment]
I think the issue with Compat shouldn't be a problem when nanosoldier runs against latest master
@nanosoldier `runbenchmarks(ALL, vs=":master")`

File: base/special/exp.jl [hunk 4]
```diff
@@ -114,13 +118,13 @@ function exp{T<:Union{Float32,Float64}}(x::T)
...
             # multiply by 2.0 first to prevent overflow, which helps extends the range
-            k == exponent_max(T) && return y*T(2.0)*T(2.0)^(exponent_max(T) - 1)
+            k == exponent_max(T) && return y * T(2.0) * T(2.0)^(exponent_max(T) - 1)
             twopk = reinterpret(T, rem(exponent_bias(T) + k, fpinttype(T)) << significand_bits(T))
             return y*twopk
         else
             # add significand_bits(T) + 1 to lift the range outside the subnormals
             twopk = reinterpret(T, rem(exponent_bias(T) + significand_bits(T) + 1 + k, fpinttype(T)) << significand_bits(T))
-            return y*twopk*T(2.0)^(-significand_bits(T) - 1)
+            return y * twopk * T(2.0)^(-significand_bits(T) - 1)
```
Comment (vtjnash) [inline base/special/exp.jl]: should this also be `eps(T) / 2`?

Comment (musm) [inline base/special/exp.jl]: I think it's better as is, since the intent of the code is a lot more clear with it being explicit same with `ldexp`  (which is why I didn't use `eps`, as it makes the scaling and explicit) 

but if they must change it would also make sense to change both 
`T(2.0)^(exponent_max(T) - 1)`
and
`T(2.0)^(-significand_bits(T) - 1)`
should either both us the `^ = Base.FastMath.pow_fast` or be evaluated ahead as constants. 

I have to admit it's a little disappointing that we have to now work around these  cases as such

Comment (vtjnash) [inline base/special/exp.jl]: > I have to admit it's a little disappointing that we have to now work around these cases as such

All of these options generate exactly the same result. Just trying to understand what should be in the code for the most clarity.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19890#issuecomment-278726061) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3eff07a82690bb404e65a9d4eadae96ed5388818/4939f20_vs_3bc9a16/report.md). cc @jrevels

File: base/special/exp.jl (hunk 4 above)
Comment (simonbyrne) [inline base/special/exp.jl]: @musm I'm still not sure I quite understand the issue here. All these expressions are still being constant folded. e.g. on this branch:
```
julia> import Base.significand_bits

julia> foo(T) = T(2.0)^(-significand_bits(T) - 1)
foo (generic function with 1 method)

julia> @code_llvm foo(Float64)

define double @julia_foo_65393(i8**) #0 !dbg !5 {
L12:
  ret double 0x3CA0000000000000
}

julia> @code_llvm foo(Float32)

define float @julia_foo_65426(i8**) #0 !dbg !5 {
L12:
  ret float 0x3E70000000000000
}
```

Comment (simonbyrne) [inline base/special/exp.jl]: @musm I'm still not sure I quite understand the issue here. All these expressions are still being constant folded. e.g. on this branch:
```
julia> import Base.significand_bits

julia> foo(T) = T(2.0)^(-significand_bits(T) - 1)
foo (generic function with 1 method)

julia> @code_llvm foo(Float64)

define double @julia_foo_65393(i8**) #0 !dbg !5 {
L12:
  ret double 0x3CA0000000000000
}

julia> @code_llvm foo(Float32)

define float @julia_foo_65426(i8**) #0 !dbg !5 {
L12:
  ret float 0x3E70000000000000
}
```

Comment (simonbyrne) [inline base/special/exp.jl]: (so this means 1282205a0285ffacd431f5e0a13cbcf8524468f2 is unnecessary, and can be removed).

Comment (tkelman) [inline base/special/exp.jl]: that commit seems like an improvement in readability to me

Comment (musm) [inline base/special/exp.jl]: > @musm I'm still not sure I quite understand the issue here. All these expressions are still being constant folded. e.g. on this branch:

I'm a little confused then why we need:
https://github.com/JuliaLang/julia/pull/19890/files#diff-4da275bf96d6e97c1918f46754df04d1R68
in the `exp` function since 
https://github.com/JuliaLang/julia/blob/1282205a0285ffacd431f5e0a13cbcf8524468f2/base/special/exp.jl#L121
and 
https://github.com/JuliaLang/julia/blob/1282205a0285ffacd431f5e0a13cbcf8524468f2/base/special/exp.jl#L127
should also be constant folded (i.e. `T(2.0)^(exponent_max(T) - 1)` and  `T(2.0)^(-significand_bits(T) - 1)` ). So doesn't that make the`    ^ = Base.FastMath.pow_fast` unnecessary  (the benchmarks showed otherwise...?)  (here's the def for `exponent_max` https://github.com/JuliaLang/julia/blob/1282205a0285ffacd431f5e0a13cbcf8524468f2/base/float.jl#L751)

@tkelman 
> that commit seems like an improvement in readability to me
The reason I suggested the current code is more clear is that it's really obvious what's currently happening with the `signficand_bits` and the scaling, e.g.  see the line and the following one
https://github.com/JuliaLang/julia/blob/master/base/math.jl#L556
it may be less readable, but I believe it's more clear and would be  a lot easier to quickly infer what it's doing upon first glance or in the future when revisiting the logic. 

This type of scaling is also used in almost the exact same logic, repeatedly, in the `exp` function https://github.com/JuliaLang/julia/blob/1282205a0285ffacd431f5e0a13cbcf8524468f2/base/special/exp.jl#L118
I'd prefer to keep as it as is currently, if possible, due to these reasons.

Comment (vtjnash) [inline base/special/exp.jl]: The benchmark is for an older commit which had a bug.

Comment (simonbyrne) [inline base/special/exp.jl]: ok, then we should get rid of the `^ = Base.FastMath.pow_fast` if it isn't needed.

Comment (tkelman) [inline base/special/exp.jl]: any way to add a test more visible than the perf tracking that the constant propagation is working reliably?

**Comment by musm** [comment]
Is the only thing left to do here is to drop the last commit, revert the exp function changes, and rerun nanosoldier?

**Comment by stevengj** [comment]
I don't think "correctness" is the right way to frame this question.  Exponentiation is not guaranteed to be rounded to 1 ulp, so it's a question of slightly more vs. slightly less roundoff error.

The question is, is the marginal increase in accuracy worth it for the decrease in performance here?  (Exponentiation-by-squaring and similar algorithms for `x^p` have O(√log(p)) rms error growth, I believe, so the error is quite reasonable even for large `p`.)

**Comment by stevengj** [comment]
My impression is that Fortran compilers have been inlining literal integer powers as repeated multiplications for decades, and I've never heard of anyone complaining about the accuracy. e.g. see the [gfortran code for this](gfor_fndecl_math_powi).

**Comment by stevengj** [comment]
Ah, looking more carefully at the gfortran code, it only does the power expansion for float types for powers `>2` or `<-1` if `-funsafe-math-optimizations` is set and `-Os` is not set. See [this line](https://github.com/gcc-mirror/gcc/blob/01991e362c8d4751e97cb80fa23c2f0d1478387f/gcc/fortran/trans-expr.c#L2879-L2881).

**Comment by stevengj** [comment]
And I guess our @fastmath already calls `powi`.

**Comment by StefanKarpinski** [comment]
It seems like there ought to be more efficient ways to compute `x^p` precisely for floating-point `x` and fixed `p` than calling the general `pow` function.

**Comment by simonbyrne** [comment]
Probably not for arbitrary `x`: `pow(x,y)` is typically implemented as a slightly-extended precision version of `exp(y*log(x))`.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19890#issuecomment-281791383) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b3e401bf172f8109d6547d171ffd8de7aeaa09f2/9973b8c_vs_0cebddf/report.md). cc @jrevels

**Comment by tkelman** [comment]
so the simple version regressed - is that the Val literal lowering change making inlining or constant prop less predictable?

**Comment by vtjnash** [comment]
Moving the value into the type domain can potentially thwart constant folding. In this case, it's this constant-value function that got broken:
```
exp_small_thres(::Type{Float64}) = 2.0^-28
```

**Comment by vtjnash** [comment]
We should really stop dispatching on `Type{Val{...}}`. Working with types is much harder on inference and the runtime than `Val{...}`. Constructing the value is effectively free (it's a singleton, so it's already constructed), and it's much more likely to be properly constant folded and dispatched. Plus there are a lot of fast paths in the runtime that can be accessed by a singleton which cannot exist for types (They instead often get handed off to the very slow fallback code).

**Comment by tkelman** [comment]
were you waiting for something before running @nanosoldier `runbenchmarks(ALL, vs=":master")` again?

**Comment by JeffBezanson** [comment]
+100 https://github.com/JuliaLang/julia/pull/19890#issuecomment-282091331

The only real problem is that `Val{x}()` is a bit long. I believe we could define

```
@pure Val(x) = Val{x}()
```

which would allow it to be constant-folded and inferred just as well, so you could write `Val(3)`.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19890#issuecomment-282168390) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/729b08f059470aa27c8d55b9c2bf25e2d3a5b3d8/2dee700_vs_7968717/report.md). cc @jrevels

**Comment by vtjnash** [comment]
> `@pure Val(x) = Val{x}()`

true. that then just has the problem that calling the `Val(x)` constructor requires the slow path :P

I'll also just reiterate that the fact there's a number of methods `foo(::Type{Val{true}})` is just completely awful. Just call it `foo_true()` if you're really hate your code reader that much.

**Comment by JeffBezanson** [comment]
Agreed; we should not have public APIs with `Val{true}` and `Val{false}`. A rare case where a name with an underscore is less ugly.

**Comment by vtjnash** [comment]
```
~/julia/base$ grep -RI 'Val{true}\|Val{false}' . | wc -l
      68
```

anyways, enough OT - I think we can go ahead and merge this?

**Comment by JeffBezanson** [comment]
Yes, seems like it's time.

**Comment by stevengj** [comment]
The constant-folding of powers is fixed by #20783, following the suggestion to use `Val{p}()`.

File: base/math.jl [hunk 5]
```diff
@@ -20,13 +20,23 @@ import Base: log, exp, sin, cos, tan, sinh, cosh, tanh, asin,
...
+
+for T in (Float16, Float32, Float64)
+    @eval significand_bits(::Type{$T}) = $(trailing_ones(significand_mask(T)))
+    @eval exponent_bits(::Type{$T}) = $(sizeof(T)*8 - significand_bits(T) - 1)
+    @eval exponent_bias(::Type{$T}) = $(Int(exponent_one(T) >> significand_bits(T)))
+    # maximum float exponent
+    @eval exponent_max(::Type{$T}) = $(Int(exponent_mask(T) >> significand_bits(T)) - exponent_bias(T))
+    # maximum float exponent without bias
+    @eval exponent_raw_max(::Type{$T}) = $(Int(exponent_mask(T) >> significand_bits(T)))
+end
```
Comment (musm) [inline base/math.jl]: @vtjnash  Out of curiosity, what was the reason behind moving these functions from `float.jl` to `math.jl`?  I had some code that imported `Base.significand_bits`, and now it needs `Base.Math.significand_bits` to work on master.

Comment (vtjnash) [inline base/math.jl]: They were incorrectly marked `@pure`, and only used here. You can import them from `Base.Math` on old code also, to be compatible.
