### PR TITLE
Fix buffer overflow in jloptions

### LINKED ISSUE #60298: ASAN 1.12.1 heap-buffer-overflow in `jl_parse_opts`
```
==90989==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5020000012b2 at pc 0x7f0610c2c68d bp 0x7fffab777f10 sp 0x7fffab777f08
WRITE of size 2 at 0x5020000012b2 thread T0
    #0 0x7f0610c2c68c in ijl_parse_opts /home/vchuravy/src/julia-1.12/src/jloptions.c:673:21
    #1 0x7f0610c60448 in jl_repl_entrypoint /home/vchuravy/src/julia-1.12/src/jlapi.c:1112:5
    #2 0x7f06153eb432 in jl_load_repl /home/vchuravy/src/julia-1.12/cli/loader_lib.c:601:12

0x5020000012b2 is located 0 bytes after 2-byte region [0x5020000012b0,0x5020000012b2)
allocated by thread T0 here:
    #0 0x7f0614961f8f in malloc /workspace/srcdir/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x7f0610c3159c in malloc_s /home/vchuravy/src/julia-1.12/src/support/dtypes.h:368:15
    #2 0x7f0610c2c5b6 in ijl_parse_opts /home/vchuravy/src/julia-1.12/src/jloptions.c:671:40
    #3 0x7f0610c60448 in jl_repl_entrypoint /home/vchuravy/src/julia-1.12/src/jlapi.c:1112:5
    #4 0x7f06153eb432 in jl_load_repl /home/vchuravy/src/julia-1.12/cli/loader_lib.c:601:12
    #5 0x5574f1653646 in main /home/vchuravy/src/julia-1.12/cli/loader_exe.c:58:15
    #6 0x7f0614427674  (/usr/lib/libc.so.6+0x27674) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #7 0x7f0614427728 in __libc_start_main (/usr/lib/libc.so.6+0x27728) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #8 0x5574f1652174 in _start (/home/vchuravy/src/julia-1.12-asan/asan/usr/bin/julia-debug+0x1174)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/vchuravy/src/julia-1.12/src/jloptions.c:673:21 in ijl_parse_opts
Shadow bytes around the buggy address:
  0x502000001000: fa fa 00 fa fa fa 00 fa fa fa 03 fa fa fa 00 00
  0x502000001080: fa fa fd fa fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x502000001100: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x502000001180: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x502000001200: fa fa fd fd fa fa 00 04 fa fa fd fd fa fa 07 fa
=>0x502000001280: fa fa 00 00 fa fa[02]fa fa fa fa fa fa fa fa fa
  0x502000001300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000001380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000001400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000001480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000001500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==90989==ABORTING
ERROR: failed process: Process(`/home/vchuravy/src/julia-1.12-asan/asan/usr/bin/julia-debug -C native -J/home/vchuravy/src/julia-1.12-asan/asan/usr/lib/julia/sys-debug.so -g2 -O0 --color=no --history-file=no --startup-file=no --project=/home/vchuravy/src/Enzyme/Project.toml --eval 'append!(empty!(Base.DEPOT_PATH), ["/home/vchuravy/.julia", "/home/vchuravy/src/julia-1.12-asan/asan/usr/local/share/julia", "/home/vchuravy/src/julia-1.12-asan/asan/usr/share/julia"])
append!(empty!(Base.DL_LOAD_PATH), String[])
```

### PR DESCRIPTION
**Pull request by vchuravy**
We currently assume that we have two threadspools, but the code above the mallocchanges the `jl_options.nthreadpools`

before we had:

```
-            if (jl_options.nthreadpools == 2)
-                ntpp[1] = (int16_t)nthreadsi;
+            ntpp[1] = (int16_t)nthreadsi;
```

Fixes #60298

### CODE REVIEW

File: src/jloptions.c [hunk 1]
```diff
@@ -725,7 +725,9 @@ JL_DLLEXPORT void jl_parse_opts(int *argcp, char ***argvp)
                 }
                 jl_options.nthreads = nthreads + nthreadsi;
             }
-            int16_t *ntpp = (int16_t *)malloc_s(jl_options.nthreadpools * sizeof(int16_t));
+            // TODO: Currently we assume a fixed number of threadpools
+            int nthreadpools = 2;
+            int16_t *ntpp = (int16_t *)malloc_s(nthreadpools * sizeof(int16_t));
             ntpp[0] = (int16_t)nthreads;
             ntpp[1] = (int16_t)nthreadsi;
```
Comment (topolarity) [inline src/jloptions.c]:
```suggestion
            assert(jl_options.nthreadpools == 1 || jl_options.nthreadpools == 2);
            int16_t *ntpp = (int16_t *)malloc_s(jl_options.nthreadpools * sizeof(int16_t));
            ntpp[0] = (int16_t)nthreads;
            if (jl_options.nthreadpools == 2)
                ntpp[1] = (int16_t)nthreadsi;
```

I don't think it's correct to say that we "assume a fixed number of threadpools" - we support only exactly 1 or 2

We just happen to implement disabling the second threadpool by setting its `jl_n_threads_per_pool` to 0 internally, but that doesn't affect the `jl_options` format.

Comment (vchuravy) [reply src/jloptions.c]: Yeah, I was looking at https://github.com/JuliaLang/julia/pull/57087 and @IanButterworth has explicitly removed the ` if (jl_options.nthreadpools == 2)` I am unsure if there is an assumption elsewhere that this buffer is two element sized.

Comment (vchuravy) [reply src/jloptions.c]: Looking through the code, there seems no such assumption.

Comment (topolarity) [reply src/jloptions.c]: There shouldn't be - we have a test that does this explicitly (https://github.com/JuliaLang/julia/blob/9bb8684279eea93afd0729b67ff01b16eeb0cb89/test/gcext/gcext.c#L605-L608) as well as code in the wild, etc. that does

**Review by IanButterworth — APPROVED** [review]
Thanks, apologies. How did this slip through CI for so long?

**Comment by topolarity** [comment]
> How did this slip through CI for so long?

I suspect `malloc` usually pads the allocation so that this is mostly benign (but sanitizers will catch it of course)

**Comment by giordano** [comment]
I'm assuming this should be backported to v1.13, in addition to v1.12
