### PR TITLE
flatten recursive call to cat_shape

### LINKED ISSUE #36750: cat StackOverflow error
On Julia 1.4.2.

```
julia> s = [rand((0.0,1.0), 2,5,100) for _ = 1:5000];
julia> cat(s...; dims=3)
ERROR: StackOverflowError:
Stacktrace:
 [1] cat_shape(::Tuple{Bool,Bool,Bool}, ::Tuple{Int64,Int64,Int64}, ::Tuple{Int64,Int64,Int64}, ::Tuple{Int64,Int64,Int64}, ::Vararg{Tuple{Int64,Int64,Int64},N} where N) at ./abstractarray.jl:1395 (repeats 4820 times)
 [2] _cat_t(::Int64, ::Type{T} where T, ::Array{Float64,3}, ::Vararg{Array{Float64,3},N} where N) at ./abstractarray.jl:1440
 [3] cat_t(::Type{Float64}, ::Array{Float64,3}, ::Vararg{Array{Float64,3},N} where N; dims::Int64) at ./abstractarray.jl:1437
 [4] _cat(::Int64, ::Array{Float64,3}, ::Vararg{Array{Float64,3},N} where N) at ./abstractarray.jl:1565
 [5] cat(::Array{Float64,3}, ::Vararg{Array{Float64,3},N} where N; dims::Int64) at ./abstractarray.jl:1564
 [6] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by johnnychen94**
This brings a faster `cat` for arrays, especially for large ones

```julia
julia> s = [rand((0.0,1.0), 2,5,100) for _ = 1:5];

# before
julia> @btime cat(s...; dims=3);
  13.694 μs (83 allocations: 42.39 KiB)

# after
julia> @btime cat(s...; dims=3);
  10.816 μs (49 allocations: 41.19 KiB)

julia> s = [rand((0.0,1.0), 2,5,100) for _ = 1:5000];

# before
julia> @btime cat(s...; dims=3);
  751.367 ms (12552030 allocations: 803.21 MiB)

# after
julia> @btime cat(s...; dims=3);
  12.766 ms (30044 allocations: 40.10 MiB)
```

Similar results can be observed for `hcat` and `vcat`.

This also fixes #36750, would be nice to get this backported.

It is worth to note that there is actually a much slower workaround to #36750 

```julia
julia> s = [rand((0.0,1.0), 2,5,100) for _ = 1:5000];

julia> @btime reduce((x,y)->cat(x,y, dims=3), s);
  5.377 s (144963 allocations: 11.78 GiB)
```

and this is widely used in Flux community, e.g., https://github.com/FluxML/model-zoo/blob/4bf84760b370f264eadc7b19f6fb2070dd689bee/vision/dcgan_mnist/dcgan_mnist.jl#L27

cc: @cossio

### CODE REVIEW

File: base/abstractarray.jl [hunk 1]
```diff
@@ -1535,9 +1535,8 @@ cat_indices(A::AbstractArray, d) = axes(A, d)
 cat_similar(A, T, shape) = Array{T}(undef, shape)
 cat_similar(A::AbstractArray, T, shape) = similar(A, T, shape)
 
-cat_shape(dims, shape::Tuple) = shape
-@inline cat_shape(dims, shape::Tuple, nshape::Tuple, shapes::Tuple...) =
-    cat_shape(dims, _cshp(1, dims, shape, nshape), shapes...)
+cat_shape(dims, shape::Tuple{Vararg{Int}}) = shape
+cat_shape(dims, shapes::Tuple) = reduce((x,y)->_cshp(1, dims, x, y), shapes; init=())
```
Comment (JeffBezanson) [inline base/abstractarray.jl:1539]: I think it would probably be even better/simpler just to write a loop.

File: base/deprecated.jl [hunk 2]
```diff
@@ -230,4 +230,8 @@ function tuple_type_cons(::Type{S}, ::Type{T}) where T<:Tuple where S
     Tuple{S, T.parameters...}
 end
 
+# these were internal functions, but some packages seem to be relying on them
+@deprecate cat_shape(dims, shape::Tuple{}, shapes::Tuple...) cat_shape(dims, shapes)
```
Comment (mbauman) [inline base/deprecated.jl:234]: This exported `cat_shape` for 1.6. 😿
