### PR TITLE
Fix jl_free(NULL)

### LINKED ISSUE #19963: jl_free(NULL) crashes
At the moment julia crashes when `jl_free` is called with a null pointer. The standard (see C99 section 7.20.2.3) says that if a null pointer is provided, no action occurs.

We encountered this while wrapping a C library, which we hooked up with julias memory functions.

The following minor change to `jl_free` should fix it.

```c
JL_DLLEXPORT void jl_free(void *p)
{
    int64_t *pp; 
    size_t sz;

    if (p != NULL) {
        pp = (int64_t *)p - 2; 
        sz = pp[0];
        jl_gc_counted_free(pp, sz); 
    }    
}
```

### PR DESCRIPTION
**Pull request by thofma**
Fix #19963.

Backporting would be nice.

### CODE REVIEW

File: src/gc.c [hunk 1]
```diff
@@ -2047,9 +2047,14 @@ JL_DLLEXPORT void *jl_calloc(size_t nm, size_t sz)
...
 JL_DLLEXPORT void jl_free(void *p)
 {
-    int64_t *pp = (int64_t *)p - 2;
-    size_t sz = pp[0];
-    jl_gc_counted_free(pp, sz);
+    int64_t *pp;
+    size_t sz;
+
+    if (p != NULL) {
+        pp = (int64_t *)p - 2;
```
Comment (yuyichao) [inline src/gc.c]: No need to separate declaration and assignments

**Comment by tkelman** [comment]
a slightly longer commit message would be preferable

**Comment by thofma** [comment]
Done.

**Review by yuyichao — APPROVED** [review]

**Comment by tkelman** [comment]
it may also be worth adding a quick test so we're less likely to accidentally change this

**Comment by StefanKarpinski** [comment]
Test can just be that using `ccall` to call `jl_null` with `C_NULL` as its argument doesn't segfault.

**Comment by thofma** [comment]
I have added also a test for #15240 (kind of related). I hope the tests are ok.

File: test/core.jl [hunk 2]
```diff
@@ -4862,3 +4862,12 @@ end
 @test_throws ErrorException isless(MyTime(1), now())
 
 end
+
+# issue #15240
+
+p15240 = ccall(:jl_realloc, Ptr{Void}, (Ptr{Void}, Csize_t), C_NULL, 10)
+ccall(:jl_free, Void, (Ptr{Void}, ), p15240)
```
Comment (StefanKarpinski) [inline test/core.jl]: These should be written as tests, even if just testing that the returned value is `nothing`. Otherwise they don't get counted in the test stats at the end.

Comment (thofma) [inline test/core.jl]: I'll open a new PR to address this.

Comment (StefanKarpinski) [inline test/core.jl]: Thanks!
