### PR TITLE
LinearAlgebra: Correct return type of inv(::Diagonal)

### LINKED ISSUE #46307: Cannot invert diagonal complex rational matrices
This fails:
```Julia
using LinearAlgebra
julia> inv(Diagonal([1//1+im]))
```

The error is
```
ERROR: DivideError: integer division error
```

I am using
```
julia> versioninfo()
Julia Version 1.8.0-rc4
Commit 7853436ccd7 (2022-08-08 07:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.5.0)
  CPU: 16 × Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 16 virtual cores
```

### PR DESCRIPTION
**Pull request by eschnett**
Closes https://github.com/JuliaLang/julia/issues/46307.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 1]
```diff
@@ -675,7 +675,7 @@ for f in (:exp, :cis, :log, :sqrt,
 end
 
 function inv(D::Diagonal{T}) where T
-    Di = similar(D.diag, typeof(inv(zero(T))))
+    Di = similar(D.diag, typeof(inv(one(T))))
```
Comment (simeonschaub) [inline stdlib/LinearAlgebra/src/diagonal.jl:678]:
```suggestion
    Di = similar(D.diag, typeof(inv(oneunit(T))))
```
Otherwise this might break `inv` for unitful matrices. Maybe add a test for those as well?

**Review by simeonschaub — COMMENTED** [review]
Seems like the methods for `pinv` below have the same issue, might as well fix those too?

File: stdlib/LinearAlgebra/src/diagonal.jl (hunk 1 above)
Comment (eschnett) [reply stdlib/LinearAlgebra/src/diagonal.jl:678]: Will do.

**Comment by eschnett** [comment]
`pinv` calculates for each element `isfinite(inv(D.diag[i]))`. This breaks for complex rationals, where `inv` isn't defined for zero. We will have to check for `!iszero(D.diag[i]) && isfinite(inv(D.diag[i]))`.

File: stdlib/LinearAlgebra/src/diagonal.jl (hunk 1 above)
Comment (eschnett) [reply stdlib/LinearAlgebra/src/diagonal.jl:678]: I tried to add unitful tests, but it's way too tedious. To handle arithmetic operations for mock unitful numbers, as well as norms, quite a bit of infrastructure is necessary. It doesn't make sense to build this just for the `diagonal.jl` test case. It would make more sense to just `using Unitful`. Or to add such tests to `Unitful.jl`.

**Comment by eschnett** [comment]
The build errors seem unrelated. (The `LinearAlgebra/diagonal` tests all succeed.)

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 2]
```diff
@@ -686,20 +686,34 @@ function inv(D::Diagonal{T}) where T
...
-    Di = similar(D.diag, typeof(inv(zero(T))))
-    if( !isempty(D.diag) ) maxabsD = maximum(abs.(D.diag)) end
-    for i = 1:length(D.diag)
-        if( abs(D.diag[i]) > tol*maxabsD && isfinite(inv(D.diag[i])) )
-            Di[i]=inv(D.diag[i])
-        else
-            Di[i]=zero(T)
+    Di = similar(D.diag, typeof(inv(oneunit(T))))
+    if !isempty(D.diag)
+        maxabsD = maximum(abs.(D.diag))
```
Comment (N5N3) [inline stdlib/LinearAlgebra/src/diagonal.jl:706]:
```suggestion
        maxabsD = maximum(abs, D.diag)
```

**Review by N5N3 — COMMENTED** [review]
#45511 is still open on master.

File: stdlib/LinearAlgebra/test/diagonal.jl [hunk 3]
```diff
@@ -529,7 +529,7 @@ end
 end
 
 @testset "inverse" begin
-    for d in (randn(n), [1, 2, 3], [1im, 2im, 3im])
+    for d in [randn(n), Int[], [1, 2, 3], [1im, 2im, 3im], [1//1, 2//1, 3//1], [1+1im//1, 2//1, 3im//1]]
```
Comment (N5N3) [inline stdlib/LinearAlgebra/test/diagonal.jl:532]:
```suggestion
    for d in Any[randn(n), Int[], [1, 2, 3], [1im, 2im, 3im], [1//1, 2//1, 3//1], [1+1im//1, 2//1, 3im//1]]
```

File: stdlib/LinearAlgebra/test/diagonal.jl [hunk 4]
```diff
@@ -538,6 +538,14 @@ end
     @test_throws SingularException inv(Diagonal([0im, 1im, 2im]))
 end
 
+@testset "pseudoinverse" begin
+    for d in [randn(n), zeros(n), Int[], [0, 2, 0.003], [0im, 1+2im, 0.003im], [0//1, 2//1, 3//100], [0//1, 1//1+2im, 3im//100]]
```
Comment (N5N3) [inline stdlib/LinearAlgebra/test/diagonal.jl:542]:
```suggestion
    for d in Any[randn(n), zeros(n), Int[], [0, 2, 0.003], [0im, 1+2im, 0.003im], [0//1, 2//1, 3//100], [0//1, 1//1+2im, 3im//100]]
```

**Review by N5N3 — COMMENTED** [review]
#45511 is still open on master. Use `Any[]` to avoid unwanted promotion.

**Comment by eschnett** [comment]
The reported errors are unrelated (they are in libgit).
