### PR TITLE
Workaround GDB JIT debugging bug with shared linked LLVM

### LINKED ISSUE #17856: GDB JIT object registration does not work with LLVM shared library
Not sure if this is due to our compile/link flag or GDB/LLVM bug. (Probably should test on a version of lldb that support jit code registration but somehow my lldb is behaving strangely right now).

Of course an acceptable solution is to make native code debugging in Gallium with and without rr as good as gdb/lldb and also easily installable so that we can remove this interface altogether.

### PR DESCRIPTION
**Pull request by yuyichao**
This is of course still a GDB bug but I think the issue can be closed since this is a reliable/well defined enough workaround. The gdb bug can probably also be fixed by reversing the lookup order since the global variable doesn't have any PLT. I'll try that on GDB later.

Fix #17856
@Keno

### CODE REVIEW

File: src/jitlayers.cpp [hunk 1]
```diff
@@ -287,6 +287,13 @@ extern "C" {
 
 namespace {
 
+// Use a local variable to hold the addresses to avoid generating a PLT
```
Comment (tkelman) [inline src/jitlayers.cpp]: I've asked this before and still don't remember, what's PLT?

Comment (yuyichao) [inline src/jitlayers.cpp]: It's `Procedure Linkage Table`. It's a function named `foo@plt` generated in the object file (`libjulia`) that will lazily lookup and jump to a function in another object file `libLLVM`. The GDB internal lookup function finds the PLT in our object file instead of the real one in `libLLVM` so it then lookup everything else in the wrong file and couldn't find it....

**Comment by yuyichao** [comment]
GDB patch https://sourceware.org/ml/gdb/2017-01/msg00050.html

**Comment by yuyichao** [comment]
I verified that this workaround works in a few cases that the old workaround somehow didn't work before. It'll be nice if any other people experienced this too can also confirm.

Will merge later this weekend.
