### PR TITLE
prevent wait() from gc-rooting the next task

### LINKED ISSUE #6597: task-related memory leaks
This is split off from #6567, since the memory leak seems to be a separate issue from the crash. That leak happened because `getnext_tasklet` got leaked. In fact, any closure that gets used in a `sync`/`async` block seems to get leaked. That is pretty easy to reproduce:

``` julia
function f()
    a = zeros(2^28)
    g() = a
    @sync @async g()
    nothing
end
f()
gc()
```

results in Julia holding on to 2GB. The leak happens in part because `current_task().last` is still around, and that holds a reference to the task, which holds a reference to `g`.

I tried setting `current_task().last = current_task()`, but Julia still seems to hold on to the memory, I think because `g` is referenced from Main's `constant_table`. This does not leak:

``` julia
function f()
    a = zeros(2^28)
    g = ()->a
    @sync @async g()
    current_task().last = current_task()
    nothing
end
f()
gc()
```

### PR DESCRIPTION
**Pull request by vtjnash**
Using an extra indirection through a Ref allows jl_switch_task to ensure that a task-switch
in wait() won't hold onto the Task in a gc-root after switching to it,
since popping a Task from the Workqueue shouldn't cause it to get a gc-root in
the current Task.

fix #6597

### CODE REVIEW

File: base/event.jl [hunk 1]
```diff
@@ -199,45 +199,53 @@ function throwto(t::Task, exc::ANY)
...
             end
         else
-            let t = shift!(Workqueue)
-                if t.state != :queued
-                    # assume this somehow got queued twice,
-                    # probably broken now, but try discarding this switch and keep going
-                    # can't throw here, because it's probably not the fault of the caller to wait
-                    # and don't want to use print() here, because that may try to incur a task switch
-                    ccall(:jl_safe_printf, Void, (Ptr{UInt8}, Int32...),
-                        "\nWARNING: Workqueue inconsistency detected: shift!(Workqueue).state != :queued\n")
```
Comment (JeffBezanson) [inline base/event.jl]: I know this never happens, but why was this deleted? Should it be an assertion instead?

Comment (vtjnash) [inline base/event.jl]: It's just moved. I needed it to be a separate function to ensure that the gc-root for `t` gets dropped and that this function is just left with `Ref(t)`.

File: src/julia.h [hunk 2]
```diff
@@ -1520,7 +1520,7 @@ typedef struct _jl_task_t {
 } jl_task_t;
 
 JL_DLLEXPORT jl_task_t *jl_new_task(jl_function_t *start, size_t ssize);
-JL_DLLEXPORT void jl_switchto(jl_task_t *t);
+JL_DLLEXPORT void jl_switchto(jl_task_t **pt);
```
Comment (StefanKarpinski) [inline src/julia.h]: This a fairly breaking C API change, no?

Comment (vtjnash) [inline src/julia.h]: Yes. It also destroys its argument, which it pretty surprising for a typical API (effectively, this is now marked `std::move`). We haven't had a stable C API in the past however.

Comment (JeffBezanson) [inline src/julia.h]: We should perhaps make `jl_switchto` a thin wrapper for `jl_switchto_ref`, more to make the API easier to use than for backwards-compatibility. Could also use a comment stating the that argument is written to.

**Comment by JeffBezanson** [comment]
Just for fun, I ran

```
julia> c=Channel(0)

julia> function ping(c)
         for i=1:1000000
          put!(c,0)
         end
       end

julia> function pong(c)
         for i=1:1000000
          take!(c)
         end
       end

julia> @time @sync begin
         @async ping(c)
         @async pong(c)
       end
```

This change doubles the amount of allocation, but there doesn't seem to be any significant time difference. Bravo, GC.

File: src/julia.h (hunk 2 above)
Comment (StefanKarpinski) [inline src/julia.h]: Not complaining, just observing mostly. I guess with 1.0 we should consider having a stable C API. Either that or say that it's not stable and that language SemVer doesn't apply to internals.

**Comment by StefanKarpinski** [comment]
Any change in memory pressure? I would assume not since there's no time change.

**Comment by vtjnash** [comment]
> Any change in memory pressure

That depends on the usage. If the task was short lived, memory pressure may be lower (since we should now be unlikely to have one long sleeping task accidentally pin some other task in memory). But also as Jeff noted, we need to allocate an extra pointer-sized object while doing the task switch to gain that benefit.

**Comment by StefanKarpinski** [comment]
Seems like a good tradeoff.
