### PR TITLE
`@kwdef`: handle const and atomic fields

### LINKED ISSUE #45020: Base.@kwdef structs constructor ignores @atomic fields
When the struct has non-atomic fields, a named args constructor is created but without the atomic field argument.
```

julia> Base.@kwdef mutable struct KWD
       @atomic atom::Int
       kk::String
       end
KWD

julia> methods(KWD)
# 3 methods for type constructor:
[1] KWD(; kk) in Main at util.jl:478
[2] KWD(atom::Int64, kk::String) in Main at REPL[5]:2
[3] KWD(atom, kk) in Main at REPL[5]:2
```

When the struct has only atomic fields, no named args constructor is created
```
julia> Base.@kwdef mutable struct KWD2
       @atomic atom::Int
       end

julia> methods(KWD2)
# 2 methods for type constructor:
[1] KWD2(atom::Int64) in Main at REPL[1]:2
[2] KWD2(atom) in Main at REPL[1]:2
```

thanks

### LINKED ISSUE #45573: at-kwdef not working with const fields
```julia
using Base: @kwdef

@kwdef struct Foo
    a::Int
    b::Int=2
end
@kwdef mutable struct Bar
    a::Int
    b::Int=2
end
@kwdef mutable struct Baz
    const a::Int
    b::Int=2
end

a = 1
Foo(; a) # => Foo(1, 2)
Bar(; a) # => Bar(1, 2)
Baz(; a) # =>
# ERROR: MethodError: no method matching Baz(; a=1)
# Closest candidates are:
#   Baz(; b) at util.jl:493 got unsupported keyword argument "a"
#   Baz(::Int64, ::Int64) at Untitled-1:10 got unsupported keyword argument "a"
#   Baz(::Any, ::Any) at Untitled-1:10 got unsupported keyword argument "a"
# Stacktrace:
#  [1] kwerr(kw::NamedTuple{(:a,), Tuple{Int64}}, args::Type)
#    @ Base ./error.jl:165
#  [2] top-level scope
#    @ Untitled-1:16
```

```julia
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc656 (2022-05-27 18:33 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 2 × Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, sandybridge)
  Threads: 1 on 2 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/45020
Fixes https://github.com/JuliaLang/julia/issues/45573

### CODE REVIEW

File: base/util.jl [hunk 1]
```diff
@@ -577,7 +577,16 @@ function _kwdef!(blk, params_args, call_args)
             push!(params_args, ei)
             push!(call_args, ei)
         elseif ei isa Expr
-            if ei.head === :(=)
+            is_atomic = ei.head == :atomic
+            ei = is_atomic ? first(ei.args) : ei # strip "@atomic" and add it back later
+            is_const = ei.head == :const
```
Comment (aviatesk) [inline base/util.jl:582]:
```suggestion
            is_atomic = ei.head === :atomic
            ei = is_atomic ? first(ei.args) : ei # strip "@atomic" and add it back later
            is_const = ei.head === :const
```
As a convention, we generally use `===` for `Symbol` comparison (at least within the Base`).

Comment (IanButterworth) [reply base/util.jl]: With this fixed do you think this is good to go?

**Review by aviatesk — APPROVED** [review]
Yeah, LGTM.
