### PR TITLE
Conversion methods sparse matrix -> special linalg type

### LINKED ISSUE #851: Conversion to Diagonal should work in general if matrices have the correct structure
What works and what doesn't:

```julia
julia> convert(Diagonal, Diagonal(1:2))
2×2 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅
 ⋅  2

julia> convert(Diagonal, Diagonal(1:2)[:,:])
ERROR: MethodError: Cannot `convert` an object of type 
  SparseArrays.SparseMatrixCSC{Int64, Int64} to an object of type 
  Diagonal
Closest candidates are:
  convert(::Type{var"#s832"} where var"#s832"<:Diagonal, ::Union{LinearAlgebra.AbstractTriangular, Bidiagonal, Diagonal, SymTridiagonal, Tridiagonal}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:53
  convert(::Type{T}, ::Factorization) where T<:AbstractArray at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/factorization.jl:58
  convert(::Type{T}, ::T) where T<:AbstractArray at abstractarray.jl:14
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[30]:1
```

The second operation should work as the off-diagonal elements are zero.

### LINKED ISSUE #40924: Conversion to Diagonal should work in general if matrices have the correct structure
What works and what doesn't:

```julia
julia> convert(Diagonal, Diagonal(1:2))
2×2 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅
 ⋅  2

julia> convert(Diagonal, Diagonal(1:2)[:,:])
ERROR: MethodError: Cannot `convert` an object of type 
  SparseArrays.SparseMatrixCSC{Int64, Int64} to an object of type 
  Diagonal
Closest candidates are:
  convert(::Type{var"#s832"} where var"#s832"<:Diagonal, ::Union{LinearAlgebra.AbstractTriangular, Bidiagonal, Diagonal, SymTridiagonal, Tridiagonal}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:53
  convert(::Type{T}, ::Factorization) where T<:AbstractArray at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/factorization.jl:58
  convert(::Type{T}, ::T) where T<:AbstractArray at abstractarray.jl:14
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[30]:1
```

The second operation should work as the off-diagonal elements are zero.

### PR DESCRIPTION
**Pull request by carstenbauer**
In this PR I add conversion methods to the SparseArrays stdlib which enable the conversion from `AbstractSparseMatrixCSC` to the special `LinearAlgebra` matrix types `Diagonal`, `Tridiagonal`, `SymTridiagonal`, `LowerTriangular`, `UpperTriangular`. This has been brought up in JuliaLang/LinearAlgebra.jl#851.

(cc @dkarrasch, @jishnub )

Close JuliaLang/LinearAlgebra.jl#851.

### CODE REVIEW

File: stdlib/SparseArrays/test/sparse.jl [hunk 1]
```diff
@@ -78,6 +78,24 @@ end
...
+    @test convert(Diagonal, sparse(Diagonal(1:2))) == Diagonal(1:2)
+    @test convert(Tridiagonal, sparse(Tridiagonal(1:3, 4:7, 8:10))) isa Tridiagonal
+    @test convert(Tridiagonal, sparse(Tridiagonal(1:3, 4:7, 8:10))) == Tridiagonal(1:3, 4:7, 8:10)
+    @test convert(SymTridiagonal, sparse(SymTridiagonal(1:4, 5:7))) isa SymTridiagonal
+    @test convert(SymTridiagonal, sparse(SymTridiagonal(1:4, 5:7))) == SymTridiagonal(1:4, 5:7)
+
+    lt = LowerTriangular([1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0])
+    @test convert(LowerTriangular, sparse(lt)) isa LowerTriangular
+    @test convert(LowerTriangular, sparse(lt)) == lt
+
```
Comment (dkarrasch) [inline stdlib/SparseArrays/test/sparse.jl:93]: Whitespace
```suggestion

```

**Comment by simeonschaub** [comment]
Looks like you need to rebase on a more recent master branch.

**Comment by crstnbr** [comment]
Indeed, my bad. Should be fine now.

File: stdlib/SparseArrays/test/sparse.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/SparseArrays/test/sparse.jl:93]: Same whitespace issue after the rebase. ;-)

Comment (crstnbr) [reply stdlib/SparseArrays/test/sparse.jl]: Fixed it again :)
