### PR TITLE
Make exit_on_sigint work again

### LINKED ISSUE #17706: Unreliable SIGINT delivery
Calling `kill(self, 2)` in 0.5 is unreliable:
```julia
ccall(:kill, Void, (Cint, Cint,), getpid(), 2)
```

Running this snippet results in different possible errors:

```
signal (2): Interrupt
while loading no file, in expression starting on line 0
anonymous at ./<missing> (unknown line)
jl_call_method_internal at /home/tbesard/Projects/Julia/src/julia_internal.h:178 [inlined]
jl_toplevel_eval_flex at /home/tbesard/Projects/Julia/src/toplevel.c:569
jl_parse_eval_all at /home/tbesard/Projects/Julia/src/ast.c:717
jl_load at /home/tbesard/Projects/Julia/src/toplevel.c:596 [inlined]
jl_load_ at /home/tbesard/Projects/Julia/src/toplevel.c:605
```

```
signal (2): Interrupt
while loading no file, in expression starting on line 0
jl_unbox_int64 at /home/tbesard/Projects/Julia/src/alloc.c:1179
jl_f_getfield at /home/tbesard/Projects/Julia/src/builtins.c:689
```

```
signal (2): Interrupt
while loading no file, in expression starting on line 0
```

```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
```

None of them properly delivering the SIGINT.

Meanwhile, on 0.4:

```
$ julia crash.jl
$ echo $?
130     # indicates SIGINT
```

This is a reduced test-case from `core.jl`, which in its current form it only fails when running under ASAN:

```julia
function crash()
    ccall(:jl_exit_on_sigint, Void, (Cint,), 0)
    try
        ccall(:kill, Void, (Cint, Cint,), getpid(), 2)
        for i in 1:10
            Libc.systemsleep(0.1)
            ccall(:jl_gc_safepoint, Void, ()) # wait for SIGINT to arrive
        end
    catch ex
        isa(ex, InterruptException) || rethrow(ex)
    end
    ccall(:jl_exit_on_sigint, Void, (Cint,), 1)
end

crash()
```

```
ASAN:DEADLYSIGNAL
=================================================================
==17111==ERROR: AddressSanitizer: SEGV on unknown address 0x7fed15b90000 (pc 0x7fecf6cc140e bp 0x7ffe17280530 sp 0x7ffe172803b0 T0)
    #0 0x7fecf6cc140d  (<unknown module>)
    #1 0x7fecf6cc154f  (<unknown module>)
    #2 0x7fed244605d0 in jl_call_method_internal /home/tbesard/Projects/Julia/src/julia_internal.h:178:16
    #3 0x7fed244694c2 in jl_apply_generic /home/tbesard/Projects/Julia/src/gf.c:1928:23
    #4 0x7fed244bf131 in do_call /home/tbesard/Projects/Julia/src/interpreter.c:66:26
    #5 0x7fed244b5cbf in eval /home/tbesard/Projects/Julia/src/interpreter.c:190:16
    #6 0x7fed244b50f1 in jl_interpret_toplevel_expr /home/tbesard/Projects/Julia/src/interpreter.c:31:12
    #7 0x7fed2451d436 in jl_toplevel_eval_flex /home/tbesard/Projects/Julia/src/toplevel.c:558:26
    #8 0x7fed2448fc71 in jl_parse_eval_all /home/tbesard/Projects/Julia/src/ast.c:717:26
    #9 0x7fed2451f970 in jl_load /home/tbesard/Projects/Julia/src/toplevel.c:596:12
    #10 0x7fed2451fb9a in jl_load_ /home/tbesard/Projects/Julia/src/toplevel.c:605:23
    #11 0x7fed13335361 in julia_include_from_node1_19006 loading.jl:426
    #12 0x7fed1333552b in jlcall_include_from_node1_19006 (/home/tbesard/Projects/Julia/build/sanitize/usr/lib/julia/sys-debug.so+0x30952b)
    #13 0x7fed244605d0 in jl_call_method_internal /home/tbesard/Projects/Julia/src/julia_internal.h:178:16
    #14 0x7fed244694c2 in jl_apply_generic /home/tbesard/Projects/Julia/src/gf.c:1928:23
    #15 0x7fed1336b061 in julia_process_options_20109 client.jl:262
    #16 0x7fed1336d5ea in julia__start_20103 client.jl:318
    #17 0x7fed1336e178 in jlcall__start_20103 (/home/tbesard/Projects/Julia/build/sanitize/usr/lib/julia/sys-debug.so+0x342178)
    #18 0x7fed244605d0 in jl_call_method_internal /home/tbesard/Projects/Julia/src/julia_internal.h:178:16
    #19 0x7fed244694c2 in jl_apply_generic /home/tbesard/Projects/Julia/src/gf.c:1928:23
    #20 0x4dd344 in jl_apply /home/tbesard/Projects/Julia/ui/../src/julia.h:1392:12
    #21 0x4dcb3c in true_main /home/tbesard/Projects/Julia/ui/repl.c:112:9
    #22 0x4dc9ad in main /home/tbesard/Projects/Julia/ui/repl.c:232:15
    #23 0x7fed23134740 in __libc_start_main (/usr/lib/libc.so.6+0x20740)
    #24 0x4190c8 in _start (/home/tbesard/Projects/Julia/build/sanitize/usr/bin/julia-debug+0x4190c8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
==17111==ABORTING
```

I'm not sure what's happening, but there seems to be an issue with the SIGINT delivery. If I transform the above test-case, ASAN sometimes spits out more information. In those cases, it traps a use-after-free on a known address, with those addresses always being freed by some trace starting at `__cxa_finalize`. So it looks like the SIGUSR2 thrown by `jl_try_deliver_sigint` causes the world to collapse?

cc @yuyichao

### PR DESCRIPTION
**Pull request by yuyichao**
- Add more `try`-`catch` and sigatomic for top-level code/new tasks
  
  So that we don't need to run `jl_exit` in strange (signal handler) context
  due to missing exception handler.
- Implement `jl_call_in_ctx` on unix.
  
  Use it to make sure that `jl_rethrow` and `jl_exit` are running on the right
  thread and right stack when an exception/exit is caused by a signal.
  
  Fix #17706

Tested locally on Linux x86/x64/aarch64/arm and Mac (windows sigint handling seems to be really unreliable in general). According to musl source code, it should work there too. Implementation on platforms that I don't have access to (FreeBSD, PowerPC) is left as an exercise for people who do. =)

This uses assembly to set the register values instead of using sigreturn since it doesn't work reliably on Mac and may not work in the future due to mitigation of [sigreturn oriented programming](https://en.wikipedia.org/wiki/Sigreturn-oriented_programming). (Just like all other low level features that we want to use that is blocked by security fixes....)

The final implementation is on the edge of what I'm happy to merge during feature freeze/backport after branching so I'll let others decide when this should be merge and whether it should be backported to 0.5 branch.

### CODE REVIEW

File: src/signals-unix.c [hunk 1]
```diff
@@ -46,17 +46,89 @@ static bt_context_t *jl_to_bt_context(void *sigctx)
...
+    uintptr_t rsp = jl_get_rsp_from_ctx(ctx);
+    if (!rsp) {
+        fptr();
+        return;
+    }
+    // Align the stack and leave 128bytes red zone on all platforms.
+    // (Only a few actually needs these but doesn't hurt to do on all of them).
+    rsp &= -16; // ensure 16-byte alignment
+    rsp -= 128; // 128bytes red zone
+#if defined(_CPU_X86_64_)
```
Comment (vtjnash) [inline src/signals-unix.c]: tkelmans's going to complain that MSVC doesn't support the `asm` keyword

**Comment by vtjnash** [comment]
looks like a good improvement to me

File: src/signals-unix.c (hunk 1 above)
Comment (yuyichao) [inline src/signals-unix.c]: Well, this is in ...-**unix**.c, I'll be happy to learn how to write this in msvc compatible way when we support using MSVC to build for unix =)

File: base/task.jl [hunk 2]
```diff
@@ -105,6 +105,7 @@ suppress_excp_printing(t::Task) = isa(t.storage, ObjectIdDict) ? get(get_task_tl
 
 # runtime system hook called when a task finishes
 function task_done_hook(t::Task)
+    # `finish_task` set `sigatomic` before entering this function
```
Comment (tkelman) [inline base/task.jl]: sets?

File: src/signals-unix.c [hunk 3]
```diff
@@ -46,17 +46,89 @@ static bt_context_t *jl_to_bt_context(void *sigctx)
...
+#else
+    // TODO Add support for FreeBSD and PowerPC(64)?
+    return 0;
+#endif
+}
+
+static void jl_call_in_ctx(void (*fptr)(void), void *ctx)
+{
+    // Modifying the ucontext should work too but sigreturn orientated
+    // programming mitigation can works against us by rejecting ucontext
```
Comment (tkelman) [inline src/signals-unix.c]: can work against us

File: src/signals-unix.c [hunk 4]
```diff
@@ -199,11 +271,39 @@ static void jl_try_deliver_sigint(void)
...
 }
 
+// Write only by signal handling thread, read only by main thread
+// no sync necessary.
+static int thread0_exit_state = 0;
+static void jl_exit_thread0_cb(void)
+{
+    // This can get stuck if it happens at a unfortunate spot
+    // (unavoidable due to its async nature).
+    // Try harder to exit each time if we get mutliple exit requests.
```
Comment (tkelman) [inline src/signals-unix.c]: multiple

**Comment by yuyichao** [comment]
Go back to modifying the ucontext since the concern I had was mainly due to a misunderstanding of a LWN article....

I'll need to repeat the test on the 5 architectures again.

File: src/signals-unix.c [hunk 5]
```diff
@@ -46,17 +46,101 @@ static bt_context_t *jl_to_bt_context(void *sigctx)
...
                                           jl_to_bt_context(sigctx));
     ptls->exception_in_transit = e;
-    // TODO throw the error by modifying sigctx for supported platforms
-    // This will avoid running the atexit handler on the signal stack
-    // if no excepiton handler is registered.
-    jl_rethrow();
+    // Do not use the main stack if this is a stack overflow since that will
+    // not work....
+    if (e == jl_stackovf_exception)
+        jl_rethrow();
```
Comment (vtjnash) [inline src/signals-unix.c]: on `mach`, we re-use the signal stack for the rethrow call. should we eventually do that here too?

Comment (yuyichao) [inline src/signals-unix.c]: Set `sp` to the top of the signal stack and `jmp` to the function?

Comment (vtjnash) [inline src/signals-unix.c]: it does `jl_call_in_ctx` with `sp` set to the top of the signal stack (`ptls2->signal_stack + sig_stack_size`), to preserve call to sigreturn (and in the `mach` case, to get back to the right `tid`)

Comment (yuyichao) [inline src/signals-unix.c]: Sure, Just need quite a bit of signal stack space for this to be reliable.

**Comment by yuyichao** [comment]
Increase the signal stack size and use that stack for every call from the signal handler now.
This version relies much less on low level access to ucontext (only for playing nicely with the kernel). Also added a signal stack overflow detection (and call `_exit`).

File: src/signals-mach.c [hunk 6]
```diff
@@ -304,6 +317,41 @@ static void jl_try_deliver_sigint(void)
...
 }
 
+static void jl_exit_thread0(int exitstate)
+{
+    jl_ptls_t ptls2 = jl_all_tls_states[0];
+    mach_port_t thread = pthread_mach_thread_np(ptls2->system_id);
+    kern_return_t ret = thread_suspend(thread);
+    HANDLE_MACH_ERROR("thread_suspend", ret);
+
+    // This abort `sleep` and other syscall.
```
Comment (tkelman) [inline src/signals-mach.c]: aborts `sleep` and other syscalls

File: src/signals-unix.c [hunk 7]
```diff
@@ -28,14 +28,10 @@
...
 
-#if defined(JL_USE_INTEL_JITEVENTS)
-unsigned sig_stack_size = SIGSTKSZ;
-#elif defined(_CPU_AARCH64_)
-// The default SIGSTKSZ causes stack overflow in libunwind.
-#define sig_stack_size (1 << 16)
-#else
-#define sig_stack_size SIGSTKSZ
-#endif
+// 8M signal stack, same with default stack size and enough
```
Comment (tkelman) [inline src/signals-unix.c]: same as?

File: src/signals-unix.c [hunk 8]
```diff
@@ -117,27 +197,36 @@ static void segv_handler(int sig, siginfo_t *info, void *context)
...
         return;
     }
-    if (ptls->safe_restore || is_addr_on_stack(jl_get_ptls_states(), info->si_addr)) { // stack overflow, or restarting jl_
+    if (ptls->safe_restore || is_addr_on_stack(ptls, info->si_addr)) { // stack overflow, or restarting jl_
         jl_unblock_signal(sig);
-        jl_throw_in_ctx(jl_stackovf_exception, context);
+        jl_throw_in_ctx(ptls, jl_stackovf_exception, context);
+    }
+    else if (jl_is_on_sigstack(ptls, info->si_addr, context)) {
+        // This mainly happen when one of the finalizer during final cleanup
```
Comment (tkelman) [inline src/signals-unix.c]: happens when one of the finalizers

File: src/signals-unix.c [hunk 9]
```diff
@@ -199,11 +288,39 @@ static void jl_try_deliver_sigint(void)
     pthread_kill(ptls2->system_id, SIGUSR2);
 }
 
+// Write only by signal handling thread, read only by main thread
+// no sync necessary.
+static int thread0_exit_state = 0;
+static void jl_exit_thread0_cb(void)
+{
+    // This can get stuck if it happens at a unfortunate spot
```
Comment (tkelman) [inline src/signals-unix.c]: at an unfortunate

**Comment by JeffBezanson** [comment]
I would probably not put this in 0.5.0 but can go in 0.5.x once we're confident that it works well.

**Comment by vtjnash** [comment]
what's left on this? it lgtm, and it's after branching now so that resolves the question of whether to do it before.

**Comment by yuyichao** [comment]
Should be ready. I guess I need to rebase though.

**Comment by yuyichao** [comment]
Rebased.

**Comment by maleadt** [comment]
I've extracted the signal stack size change for backporting: see 467e18120d71f999b2b0528126dcc7d084bad84c. @yuyichao, does this look OK?

**Comment by yuyichao** [comment]
Yeah, should be fine and it should fix most of the symptoms.
