### PR TITLE
Fix return type in broadcast when there are Type arguments

### LINKED ISSUE #19419: Broadcast with type argument generating incorrect output types
I noticed this behavior with `round`, `ceil`, and `floor` at least.

```
julia> broadcast(round, Int, [1,2,3])
3-element Array{Float64,1}:
 1.0
 2.0
 3.0

julia> broadcast(round, Int, 1.0*[1,2,3])
3-element Array{Int64,1}:
 1
 2
 3
```

### PR DESCRIPTION
**Pull request by p-zubieta**
Fixes #19419

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by Sacha0** [comment]
Am I making a mistake below? `ziptype` now returns the correct type, but inference seems unhappy with the `_default_eltype`-`first`-`generator`-`zip` mechanism:
```julia
julia> begin
           ftype(f, A) = typeof(f)
           ftype(f, A...) = typeof(a -> f(a...))
           ftype(T::Type, A) = Type{T}
           ftype(T::Type, A...) = Type{T}
           ziptype(A) = Tuple{eltype(A)}
           ziptype(T::Type) = Tuple{Type{T}}
           ziptype(A, B) = Iterators.Zip2{ziptype(A), ziptype(B)}
           @inline ziptype(A, B, C, D...) = Iterators.Zip{ziptype(A), ziptype(B, C, D...)}
       end
ziptype (generic function with 4 methods)

julia> As = (Int, [1,2,3])
(Int64,[1,2,3])

julia> zt = ziptype(As...)
Base.Iterators.Zip2{Tuple{Type{Int64}},Tuple{Int64}}

julia> ft = ftype(round, As...)
##1#2{Base.#round}

julia> Base._default_eltype(Base.Generator{zt,ft})
Any
```
yet
```julia
julia> Core.Inference.return_type(round, Tuple{Type{Int},Int})
Int64
```
(I imagine there is a good reason for the `_default_eltype`-`first`-`generator`-`zip` mechanism? I.e. rather than simply constructing a call to `return_type` like that above?) Best!

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19421#issuecomment-263026791) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a0887e4dae6fbcc6c5efb85e83411a22cf546f3d/eaf0589_vs_03c2464/report.md). cc @jrevels

**Comment by pabloferz** [comment]
@Sacha0 I don't understand all the underlying details in inference all too well, but I'll try to convey what I can grasp from the problems that led to the current mechanism, which has the limitation you noticed.

`Core.Inference.return_type` is inherently non-inferable, but it gets a special treatment during inference, I believe, when called inside a pure function, so that rules out using it inside `broadcast_c` directly. So you might wonder if you can write a pure function, say `foo`, that takes the function and the types, and which you can embed in broadcast. I think a difficulty with this, is that if you don't know the function you'll be calling, you can't ensure the pureness of `foo`. Additionally, you can't mark `foo` as pure given the way inference works.

Maybe there is another approach that could work, but I haven't been able to devise one, the only thing that I have found to work most of the time is the `_default_eltype`-`first`-`generator`-`zip` mechanism.

**Comment by vtjnash** [comment]
> Core.Inference.return_type is inherently non-inferable, but it gets a special treatment during inference, I believe, when called inside a pure functio

That's backwards. It's distinctly not pure, so it must never be called from a function annotated as such. But since the bound on its return value is actually inferrable, it has special handling inside type inference. (I still need to look at this PR to understand if it's correct, but I've been afk for Thanksgiving)

**Comment by pabloferz** [comment]
@vtjnash Thanks for clarifying. That makes more sense.

**Comment by pabloferz** [comment]
Just a question then, to understand the situation better. Under what conditions the bound of `return_type` cannot be inferred or when it fails to get handled during inference?

**Comment by Sacha0** [comment]
> It's distinctly not pure, so it must never be called from a function annotated as such.

@vtjnash: [`promote_eltype_op` is annotated pure, and calls `promote_op`](https://github.com/JuliaLang/julia/blob/579cfcba98242fdd7b2f1bda2160bc4b7ac0cd62/base/abstractarray.jl#L1771-L1774). [`promote_op` calls `_default_eltype`](https://github.com/JuliaLang/julia/blob/579cfcba98242fdd7b2f1bda2160bc4b7ac0cd62/base/promotion.jl#L225-L239), [which in turn calls `Core.Inference.return_type`](https://github.com/JuliaLang/julia/blob/579cfcba98242fdd7b2f1bda2160bc4b7ac0cd62/base/array.jl#L347-L351). So IIUC, `promote_eltype_op` is invalid? Thanks!

**Comment by vtjnash** [comment]
Absolutely.

**Comment by pabloferz** [comment]
The use of `@pure` in `promote_eltype_op` is a reminiscent of the time when `promote_op` wasn't relying on inference. I removed it and simplified the whole mechanism so it works better.

**Comment by pabloferz** [comment]
Could we ask `@nanosoldier` again how is the performance?

File: base/broadcast.jl [hunk 1]
```diff
@@ -257,17 +257,13 @@ end
...
-ftype(f, A) = typeof(f)
-ftype(f, A...) = typeof(a -> f(a...))
-ftype(T::DataType, A) = Type{T}
-ftype(T::DataType, A...) = Type{T}
-ziptype(A) = Tuple{eltype(A)}
-ziptype(A, B) = Iterators.Zip2{Tuple{eltype(A)}, Tuple{eltype(B)}}
-@inline ziptype(A, B, C, D...) = Iterators.Zip{Tuple{eltype(A)}, ziptype(B, C, D...)}
+@pure typestuple(a) = Tuple{eltype(a)}
+@pure typestuple(T::Type) = Tuple{Type{T}}
+@pure typestuple(a, b...) = Tuple{typestuple(a).types..., typestuple(b...).types...}
```
Comment (Sacha0) [inline base/broadcast.jl]: 💯

**Comment by Sacha0** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by Sacha0** [comment]
The most recent simplifications look great! Do they make the test result now inferable? Best!

**Comment by pabloferz** [comment]
> The most recent simplifications look great! Do they make the test result now inferable?

Yep

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19421#issuecomment-266354770) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/12f25ca54b42c00fcf69516f08c9cda747b368d5/fd773fb_vs_579cfcb/report.md). cc @jrevels

File: test/broadcast.jl [hunk 2]
```diff
@@ -352,3 +352,6 @@ StrangeType18623(x,y) = (x,y)
 # Issue 18622
 @test @inferred muladd.([1.0], [2.0], [3.0])::Vector{Float64} == [5.0]
 @test @inferred tuple.(1:3, 4:6, 7:9)::Vector{Tuple{Int,Int,Int}} == [(1,4,7), (2,5,8), (3,6,9)]
+
+# 19419
+@test @inferred broadcast(round, Int, [1])::Vector{Int} == [1]
```
Comment (Sacha0) [inline test/broadcast.jl]: With `broadcast(round, Int, [1])` now inferred, drop the `::Vector{Int}`? Also, shouldn't these combined `@test-@inferred` tests be written `@test @inferred(broadcast(round, Int, [1])) == [1]` instead? Otherwise the `@inferred` checks whether the `==` expression is inferable rather than the LHS? Likewise several of the preceding tests. Best!

**Review by Sacha0 — APPROVED** [review]
These changes look great. Travis, Appveyor, and Nanosoldier approve. Absent objections or requests for time, I plan to merge this following the test touchups. Best!

**Comment by Sacha0** [comment]
(As an aside, though this PR dramatically reduces the amount of red in `@code_warntype broadcast(round, Int, [1, 2, 3])`, some red remains. Perhaps worth looking into at a later point? Best!)

**Comment by pabloferz** [comment]
Tests fixed. The AV error was an unrelated server failure. Some of the `map_newindexer` methods in `Broadcast` would have to be changed to reduce those red marks, but that can be done later as you point out (those do not affect the overall inferability of `broadcast`).

**Comment by Sacha0** [comment]
Thanks again @pabloferz! :100:

**Comment by KristofferC** [comment]
This (probably) caused the following regression:

```jl
julia> using StaticArrays

julia> s = rand(SVector{3});

julia> Base.Test.@inferred s * 0.0
```

Ping @andyferris

**Comment by KristofferC** [comment]
Not saying that there is anything wrong with this PR, it could be how `StaticArray` uses broadcast. Just bringing it up.

**Comment by pabloferz** [comment]
The problem with `StaticArrays` comes from the fact that the new approach now suffers (I believe) a manifestation of #15276. The old approach didn't had this problem but it is unable get things like `broadcast(round, Int, [1])` to be inferable.

I could implement a mixed approach between the one in this PR and the previous mechanism that handles (except for some possible corner cases) both issues.

Another option is see if something can be done on the inference end (@JeffBezanson)

Here is an example of something that used to work with the old approach but currently does not

```julia
foo(f, A, n) = broadcast(x -> f(x, n), A)
broadcast(+, [1.0, 2.0, 3.0], 1) # Not inferable but was before
```

**Comment by Sacha0** [comment]
Ouch. Just confirmed
```julia
foo(f, A, n) = broadcast(x -> f(x, n), A)
Base.Test.@inferred foo(+, [1.0, 2.0, 3.0], 1)
```
previously worked (with concrete inferred type), but now fails. Odd though, the `_default_eltype`-`first`-`generator`-`zip` mechanism appeared to likewise fail in my testing for [this related discourse thread](https://discourse.julialang.org/t/towards-broadcast-over-combinations-of-sparse-matrices-and-scalars/910)? Testing further. Best!

**Comment by Sacha0** [comment]
Checked, both the example above and that from the linked discourse thread fail on master, but both work on the commit prior to the merge commit for this pull request. I must've made a mistake when testing for the related discourse thread? Best!

**Comment by tkelman** [comment]
If there isn't an easy fix to be had soon, could at least add some test_broken cases that we would ideally like to work, for tracking purposes

**Comment by Sacha0** [comment]
> the new approach now suffers (I believe) a manifestation of #15276. The old approach didn't had this problem but it is unable get things like broadcast(round, Int, [1]) to be inferable.

Ref. `@yuyichao`'s [comment on discourse](https://discourse.julialang.org/t/towards-broadcast-over-combinations-of-sparse-matrices-and-scalars/910/4).
