### PR TITLE
fix #41908, inference error in subst_trivial_bounds

### LINKED ISSUE #41908: julia type inference crashes (typeerror)
my tests started crashing with the stacktrace:

```
Internal error: encountered unexpected error in runtime:
TypeError(func=:AbstractTensorMap, context="S", expected=S<:(TensorKit.ElementarySpace{𝕜} where 𝕜), got=TensorKit.HomSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, TensorKit.ProductSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, 0}, TensorKit.ProductSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, 0}})
jl_type_error_rt at /home/maarten/julia/src/rtutils.c:119
check_datatype_parameters at /home/maarten/julia/src/jltypes.c:1229
inst_datatype_inner at /home/maarten/julia/src/jltypes.c:1392
...
```

happens at least on julia 1.6.2, and also on master.

I wasn't able to really reduce it down very far, as it's a reasonably large codebase. To run it, you need my fork of TensorKit.jl, and the planocalypse branch of MPSKit.jl . I will try to reduce it down further, but so far I didn't have much luck.

```
using TensorKit,MPSKit;

#define some new sectortype - with the property that braiding is forbidden
struct PlanarTrivial <: TensorKit.Sector end
struct 𝔹 end
Base.:^(::Type{𝔹}, d::Int) = GradedSpace(PlanarTrivial()=>d);

Base.one(::Type{PlanarTrivial})  = PlanarTrivial();
Base.conj(c::PlanarTrivial) = PlanarTrivial();
TensorKit.:⊗(c1::PlanarTrivial, c2::PlanarTrivial) = (PlanarTrivial(),)

Base.IteratorSize(::Type{TensorKit.SectorValues{PlanarTrivial}}) = TensorKit.HasLength()
Base.length(::TensorKit.SectorValues{PlanarTrivial}) = 1
Base.iterate(::TensorKit.SectorValues{PlanarTrivial}, i = 0) = i==0 ? (PlanarTrivial(),1) : nothing;
Base.getindex(::TensorKit.SectorValues{PlanarTrivial}, i::Int) = i == 1 ? PlanarTrivial() : ArgumentError("lol");
TensorKit.findindex(::TensorKit.SectorValues{PlanarTrivial}, c::PlanarTrivial)  = 1
Base.isless(::PlanarTrivial, ::PlanarTrivial) = false;
TensorKit.BraidingStyle(::Type{PlanarTrivial}) = TensorKit.NoBraiding();
TensorKit.FusionStyle(::Type{PlanarTrivial}) = TensorKit.UniqueFusion();
TensorKit.Fsymbol(args::Vararg{PlanarTrivial,6}) = 1
TensorKit.Nsymbol(args::Vararg{PlanarTrivial,3}) = 1


# use mpskit
alg = GradientGrassmann(verbosity=0,maxiter=1);
mpo = InfiniteMPO([TensorMap(rand,ComplexF64,𝔹^2*𝔹^2,𝔹^2*𝔹^2)]);
state = InfiniteMPS([𝔹^2],[𝔹^10]);
(state,envs) = leading_boundary(state,mpo,alg);

```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #41908

### CODE REVIEW

File: test/compiler/inference.jl [hunk 1]
```diff
@@ -3403,3 +3403,10 @@ end
         @test @inferred(f40177(T)) == fieldtype(T, 1)
     end
 end
+
+# issue #41908
+struct Diagonalish{T,V<:AbstractVector{T}} <: AbstractMatrix{T}
+end
+f41908(x::Diagonalish{Int, T}) where {Int<:T<:Int} = 1
```
Comment (martinholters) [inline test/compiler/inference.jl:3410]: The `Diagonal` thing was just the first that came to mind in #41908, we could just as well use `Complex{String}` here.
```suggestion
f41908(x::Complex{T}) where {String<:T<:String} = 1
```
Not that it matters much, but when in doubt, I tend to prefer simpler test cases.

File: test/compiler/inference.jl [hunk 2]
```diff
@@ -3403,3 +3403,10 @@ end
...
+g41908() = f41908(Any[1][1])
+@test Base.return_types(g41908, ()) == Any[Int]
```
Comment (martinholters) [inline test/compiler/inference.jl:3412]: Given that `f41908` is effectively uncallable, it seems `Union{}` would also be permissible (even preferable) here:
```suggestion
@test only(Base.return_types(g41908, ())) <: Int
```

File: base/compiler/utilities.jl [hunk 3]
```diff
@@ -156,7 +156,15 @@ function subst_trivial_bounds(@nospecialize(atypes))
...
-        return subst_trivial_bounds(atypes{v.ub})
+        subst = try
+            atypes{v.ub}
+        catch
+            # Note in rare cases a var bound might not be valid to substitute.
+            nothing
+        end
+        if subst !== nothing
+            return subst_trivial_bounds(subst)
+        end
```
Comment (martinholters) [inline base/compiler/utilities.jl:167]: Oh boy, this is a nice example for justifying a
```julia
try
catch
else
    # code that runs when no exception was thrown
end
```
construct. But given that we don't have it, I guess this is fine.

**Review by vtjnash — APPROVED** [review]
