### PR TITLE
Fix inconsistency between exct and nothrow effect

### LINKED ISSUE #52846: IR verification error caused by exct modeling changes
MWE, reduced from the subtype tests:

```
$ julia -g2
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1246 (2024-01-10)
 _/ |\__'_|_|_|\__'_|  |  Commit 124ce943ef7* (0 days old master)
|__/                   |

julia> using Test

julia> issub(x,y) = x <: y

julia> function doit()
           @test issub(Array, Vector where T)
       end

julia> Base.code_ircode(doit, ())
Block 8 ends in return or unreachable, but has successors
  1 ──       nothing::Nothing
  2 ──       nothing::Nothing
  3 ──       nothing::Nothing
  4 ──       nothing::Nothing
2 5 ── %5  = enter #8
  6 ──       $(Expr(:leave, :(%5)))
  7 ──       goto #11
  8 ┄─       unreachable
  9 ──       unreachable
  10 ─       nothing::Nothing
  11 ┄ %11 = φ (#7 => $(QuoteNode(Test.Returned(false, nothing, :(#= REPL[3]:2 =#)))))::Union{Test.Returned, Test.Threw}
  │    %12 = Test.do_test::Core.Const(Test.do_test)
  │    %13 = (isa)(%11, Test.Returned)::Bool
  └───       goto #13 if not %13
  12 ─ %15 = π (%11, Test.Returned)
  │    %16 = invoke %12(%15::Test.ExecutionResult, $(QuoteNode(:(issub(Array, Vector where T))))::Any)::Union{Test.Error, Test.Fail, Test.Pass}
  └───       goto #15
  13 ─       nothing::Nothing
  14 ─ %19 = π (%11, Test.Threw)
  │    %20 = invoke %12(%19::Test.ExecutionResult, $(QuoteNode(:(issub(Array, Vector where T))))::Any)::Union{Test.Error, Test.Fail, Test.Pass}
  └───       goto #15
  15 ┄ %22 = φ (#12 => %16, #14 => %20)::Union{Test.Error, Test.Fail, Test.Pass}
  └───       return %22

```

Bisected to #51754, cc @keno. Possibly related to https://github.com/JuliaLang/julia/issues/52808?

### PR DESCRIPTION
**Pull request by Keno**
Fixes #52846. Different unreachability checks use different definitions for this and were inconsistenct, causing the assertion.

Since the exct modeling isn't fully plubmed through all corners of the compiler yet, also change the caller code to force the nothrow effect to be authoritative for the time being.

### CODE REVIEW

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -3288,10 +3294,12 @@ function typeinf_local(interp::AbstractInterpreter, frame::InferenceState)
...
                 stmt, currstate, frame)
-            if exct !== Union{}
-                update_exc_bestguess!(interp, exct, frame)
-            end
             if !has_curr_ssaflag(frame, IR_FLAG_NOTHROW)
+                if exct !== Union{}
+                    update_exc_bestguess!(interp, exct, frame)
+                    # TODO: assert that these conditions match. For now, we assume the `nothrow` flag
+                    # to be correct, but allow the exct to be an over-approximation.
+                end
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:3302]: In the future, I think the exct modeling should encompass the nothrow modeling. But I agree with you that this approach might be the best for now. We'd seize opportunities to enhance exct modeling as they arise.

File: base/compiler/abstractinterpretation.jl [hunk 2]
```diff
@@ -2119,8 +2119,14 @@ function abstract_call_known(interp::AbstractInterpreter, @nospecialize(f),
...
         end
         pT = typevar_tfunc(𝕃ᵢ, n, lb_var, ub_var)
-        effects = builtin_effects(𝕃ᵢ, Core._typevar, Any[n, lb_var, ub_var], pT)
-        return CallMeta(pT, Any, effects, call.info)
+        typevar_argtypes = Any[n, lb_var, ub_var]
+        effects = builtin_effects(𝕃ᵢ, Core._typevar, typevar_argtypes, pT)
+        if effects.nothrow
+            exct = Union{}
+        else
+            exct = builtin_exct(𝕃ᵢ, Core._typevar, argtypes, pT)
```
[the remark this answers is not in the document]
Comment (Keno) [reply base/compiler/abstractinterpretation.jl:2127]: Thanks for the catch, that's just a typo.

File: base/compiler/abstractinterpretation.jl (hunk 1 above)
Comment (Keno) [reply base/compiler/abstractinterpretation.jl:3302]: Yes, we should eventually delete the nothrow effect in favor of this, but I don't think there's any urgency.

**Review by aviatesk — APPROVED** [review]
