### PR TITLE
clarify error message for constant redefinition

### LINKED ISSUE #28689: Segmentation fault from changing constants
I have been struggling for quite some time to debug a code by one of my students, and finally managed to trace the error down to modifying constant global variables, which are not `isbits`, and which have been referred to in functions that are compiled. Julia gives a gentle warning upon redefining constants, but you don't expect a segmentation fault resulting from it. The bug was originally in a julia 0.6 code, but the same still happens in 1.1-DEV
```julia
const A = randn(10)
function f()
   return sum(A)
end

f() # -> returns something

A = randn(10) # -> redefine, Julia prints a warning

f() # -> still returns the old value

# do some more stuff, until at some point the garbage collector is triggered
GC.gc()

f() # -> segfault, probably not directly, but eventually, just do some more times gc() and other allocating stuff

```

### PR DESCRIPTION
**Pull request by vtjnash**
Before it sounded like a linter message (the description was that this was a gentle notice), now it should be clearer that this warning means Julia may now be partially dysfunctional.

Closes #28689

### CODE REVIEW

File: src/module.c [hunk 1]
```diff
@@ -691,7 +691,7 @@ JL_DLLEXPORT void jl_checked_assignment(jl_binding_t *b, jl_value_t *rhs)
                 jl_errorf("invalid redefinition of constant %s",
                           jl_symbol_name(b->name));
             }
-            jl_printf(JL_STDERR, "WARNING: redefining constant %s\n",
+            jl_printf(JL_STDERR, "WARNING: redefinition of constant %s may cause Julia to fail\n",
```
Comment (vtjnash) [inline src/module.c]:
```suggestion
            jl_printf(JL_STDERR, "WARNING: redefinition of constant %s may cause the program to fail\n",
```

Comment (StefanKarpinski) [reply src/module.c]:
```suggestion
            jl_printf(JL_STDERR, "WARNING: redefinition of constant %s may cause problems (including crashes), continue at your own risk\n",
```

Comment (vtjnash) [reply src/module.c]: Or:
```suggestion
            jl_printf(JL_STDERR, "WARNING: redefinition of constant %s may sometimes fail or cause crashes\n",
```

Comment (vtjnash) [reply src/module.c]: Or:
```suggestion
            jl_printf(JL_STDERR, "WARNING: redefinition of constant %s causes undefined behavior, which is not a bug\n",
```

Comment (KristofferC) [reply src/module.c]: This would be printed as

> redefinition of constant `foo` may sometimes fail or cause crashes

and make it sound like it is a particular statement about `foo`.

Comment (KristofferC) [reply src/module.c]: So something like:

> WARNING: redefinition of constant `foo`. Redefining constants may fail or cause crashes.

is better imo.

Comment (StefanKarpinski) [reply src/module.c]: I like that last wording 👍

Comment (vtjnash) [reply src/module.c]:
```suggestion
            jl_printf(JL_STDERR, "WARNING: redefinition of constant %s. This may fail, cause incorrect answers, or produce other errors.\n",
```

**Comment by vtjnash** [comment]
Okay to merge?

**Review by KristofferC — APPROVED** [review]
