### PR TITLE
Fix real matrix sqrt and log for edge cases

### LINKED ISSUE #825: Real matrix sqrt fails for specific  quasi-triangular matrix
Since JuliaLang/julia#39973, `sqrt` raises an error for the following quasi-triangular matrix:
```julia
julia> x = [-1 -eps() 0 0;
            eps() -1 0 0;
            0 0 -1 -eps();
            0 0 eps() -1]
4×4 Matrix{Float64}:
 -1.0          -2.22045e-16   0.0           0.0
  2.22045e-16  -1.0           0.0           0.0
  0.0           0.0          -1.0          -2.22045e-16
  0.0           0.0           2.22045e-16  -1.0

julia> sqrt(x)
ERROR: LAPACKException(1)
Stacktrace:
  [1] chklapackerror(ret::Int64)
    @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:38
  [2] trsyl!(transa::Char, transb::Char, A::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, B::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, C::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, isgn::Int64)
    @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6469
  [3] trsyl!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6450 [inlined]
  [4] _sylvester_2x2!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/dense.jl:1563 [inlined]
  [5] _sqrt_quasitriu_offdiag_block_2x2!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2525 [inlined]
  [6] _sqrt_quasitriu_offdiag_block!(R::Matrix{Float64}, A::Matrix{Float64})
    @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2419
  [7] _sqrt_quasitriu!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2385 [inlined]
  [8] sqrt_quasitriu(A0::Matrix{Float64})
    @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2372
  [9] sqrt(A::Matrix{Float64})
    @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/dense.jl:803
 [10] top-level scope
    @ REPL[55]:1
```

The expected square root of this matrix is 
```julia
julia> y = Float64[eps()/2 -1 0 0; 1 eps()/2 0 0; 0 0 eps()/2 -1; 0 0 1 eps()/2]
4×4 Matrix{Float64}:
 1.11022e-16  -1.0          0.0           0.0
 1.0           1.11022e-16  0.0           0.0
 0.0           0.0          1.11022e-16  -1.0
 0.0           0.0          1.0           1.11022e-16

julia> y^2 == x
true
```

The error is raised because `LinearAlgebra._sqrt_real_2x2!` solves the diagonal blocks as
```julia
julia> LinearAlgebra._sqrt_real_2x2!(zeros(2, 2), x[1:2, 1:2]). # note that the diagonal is exactly 0 when it should be eps()/2
2×2 Matrix{Float64}:
 0.0  -1.0
 1.0   0.0
```

So the offdiagonal block is the solution to the sylvester equation
```julia
julia> sylvester([0.0 -1.0; 1.0 0.0], [0.0 -1.0; 1.0 0.0], zeros(2, 2))
ERROR: LAPACKException(1)
Stacktrace:
 [1] chklapackerror(ret::Int64)
   @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:38
 [2] trsyl!(transa::Char, transb::Char, A::Matrix{Float64}, B::Matrix{Float64}, C::Matrix{Float64}, isgn::Int64)
   @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6469
 [3] trsyl!
   @ ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6450 [inlined]
 [4] sylvester(A::Matrix{Float64}, B::Matrix{Float64}, C::Matrix{Float64})
   @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/dense.jl:1535
 [5] top-level scope
   @ REPL[135]:1
```

when we should be computing

```julia
julia> sylvester([eps()/2 -1.0; 1.0 eps()/2], [eps()/2 -1.0; 1.0 eps()/2], zeros(2, 2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```

There are two ways to fix this. First, we can improve the accuracy of `LinearAlgebra._sqrt_real_2x2!`. Second, for `sylvester(A, B, C)`, whenever `A` and `B` are finite and `C` is zero, the zero matrix is a solution. `LAPACK.trsyl!` seems to error in this case, but we would want to avoid that, so we can just return the zero matrix then. Note that this would not change the behavior of `sylvester`, just the utility function `_sylvester_2x2!`.

### LINKED ISSUE #40141: Real matrix sqrt fails for specific  quasi-triangular matrix
Since #39973, `sqrt` raises an error for the following quasi-triangular matrix:
```julia
julia> x = [-1 -eps() 0 0;
            eps() -1 0 0;
            0 0 -1 -eps();
            0 0 eps() -1]
4×4 Matrix{Float64}:
 -1.0          -2.22045e-16   0.0           0.0
  2.22045e-16  -1.0           0.0           0.0
  0.0           0.0          -1.0          -2.22045e-16
  0.0           0.0           2.22045e-16  -1.0

julia> sqrt(x)
ERROR: LAPACKException(1)
Stacktrace:
  [1] chklapackerror(ret::Int64)
    @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:38
  [2] trsyl!(transa::Char, transb::Char, A::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, B::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, C::SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, isgn::Int64)
    @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6469
  [3] trsyl!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6450 [inlined]
  [4] _sylvester_2x2!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/dense.jl:1563 [inlined]
  [5] _sqrt_quasitriu_offdiag_block_2x2!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2525 [inlined]
  [6] _sqrt_quasitriu_offdiag_block!(R::Matrix{Float64}, A::Matrix{Float64})
    @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2419
  [7] _sqrt_quasitriu!
    @ ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2385 [inlined]
  [8] sqrt_quasitriu(A0::Matrix{Float64})
    @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/triangular.jl:2372
  [9] sqrt(A::Matrix{Float64})
    @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/dense.jl:803
 [10] top-level scope
    @ REPL[55]:1
```

The expected square root of this matrix is 
```julia
julia> y = Float64[eps()/2 -1 0 0; 1 eps()/2 0 0; 0 0 eps()/2 -1; 0 0 1 eps()/2]
4×4 Matrix{Float64}:
 1.11022e-16  -1.0          0.0           0.0
 1.0           1.11022e-16  0.0           0.0
 0.0           0.0          1.11022e-16  -1.0
 0.0           0.0          1.0           1.11022e-16

julia> y^2 == x
true
```

The error is raised because `LinearAlgebra._sqrt_real_2x2!` solves the diagonal blocks as
```julia
julia> LinearAlgebra._sqrt_real_2x2!(zeros(2, 2), x[1:2, 1:2]). # note that the diagonal is exactly 0 when it should be eps()/2
2×2 Matrix{Float64}:
 0.0  -1.0
 1.0   0.0
```

So the offdiagonal block is the solution to the sylvester equation
```julia
julia> sylvester([0.0 -1.0; 1.0 0.0], [0.0 -1.0; 1.0 0.0], zeros(2, 2))
ERROR: LAPACKException(1)
Stacktrace:
 [1] chklapackerror(ret::Int64)
   @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:38
 [2] trsyl!(transa::Char, transb::Char, A::Matrix{Float64}, B::Matrix{Float64}, C::Matrix{Float64}, isgn::Int64)
   @ LinearAlgebra.LAPACK ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6469
 [3] trsyl!
   @ ~/projects/julia/stdlib/LinearAlgebra/src/lapack.jl:6450 [inlined]
 [4] sylvester(A::Matrix{Float64}, B::Matrix{Float64}, C::Matrix{Float64})
   @ LinearAlgebra ~/projects/julia/stdlib/LinearAlgebra/src/dense.jl:1535
 [5] top-level scope
   @ REPL[135]:1
```

when we should be computing

```julia
julia> sylvester([eps()/2 -1.0; 1.0 eps()/2], [eps()/2 -1.0; 1.0 eps()/2], zeros(2, 2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```

There are two ways to fix this. First, we can improve the accuracy of `LinearAlgebra._sqrt_real_2x2!`. Second, for `sylvester(A, B, C)`, whenever `A` and `B` are finite and `C` is zero, the zero matrix is a solution. `LAPACK.trsyl!` seems to error in this case, but we would want to avoid that, so we can just return the zero matrix then. Note that this would not change the behavior of `sylvester`, just the utility function `_sylvester_2x2!`.

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes JuliaLang/LinearAlgebra.jl#825, also ~eliminates an unnecessary scalar `sqrt`~ tries to reduce potential numerical issues in `_sqrt_real_2x2!`.

The added tests fail on master. Test 1 fails unless we make this change to `_sqrt_real_2x2!`. Test 2 also fails unless we make this change to `_sqrt_quasitriu_offdiag_block_2x2!`.

Edit: Test 3 tests the case where `NaN`s would cause `LAPACK.trsyl!` to error.

### CODE REVIEW

**Comment by oscardssmith** [comment]
How does this affect the performance?

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 1]
```diff
@@ -2435,25 +2435,31 @@ function _sqrt_quasitriu_offdiag_block!(R, A)
...
+    d = a11 - a22
     θ = (a11 + a22) / 2
-    μ² = -(a11 - a22)^2 / 4 - a21 * a12
-    μ = sqrt(μ²)
-    if θ > 0
-        α = sqrt((sqrt(θ^2 + μ²) + θ) / 2)
-    else
-        α = μ / sqrt(2 * (sqrt(θ^2 + μ²) - θ))
-    end
+    μ = sqrt(-d^2 - 4 * a21 * a12) / 2
```
Comment (sethaxen) [inline stdlib/LinearAlgebra/src/triangular.jl:2445]: I updated this method to follow exactly what Higham recommended in the reference. Also following @stevengj's suggestion in https://github.com/JuliaLang/julia/pull/39973#discussion_r599035462, now `hypot` is used for computing `α`. @stevengj, can you clarify your suggestion on how `hypot` could be used to compute `μ` more stably?

**Comment by sethaxen** [comment]
> How does this affect the performance?

This version of `_sqrt_real_2x2!` takes about 5ns longer than on master (~35ns on master, ~40ns here). Using the same benchmark code and matrices as in https://github.com/JuliaLang/julia/pull/39973#issuecomment-796379587, `sqrt_quasitriu` takes about 16.5 μs on master and 17.2μs here.

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 2]
```diff
@@ -2435,25 +2435,31 @@ function _sqrt_quasitriu_offdiag_block!(R, A)
...
+    f = d / 4α
+    R[1, 1] = α + f
     R[2, 1] = a21 / c
     R[1, 2] = a12 / c
-    R[2, 2] = a22 / c + d
+    R[2, 2] = α - f
     return R
 end
 
+# real part of square root of θ+im*μ
```
Comment (jebej) [inline stdlib/LinearAlgebra/src/triangular.jl:2456]: not sure if it matters here but this function has a sign issue when both parts are negative:

```julia
julia> function _real_sqrt(θ, μ)
           iszero(θ) && iszero(μ) && return sqrt(zero(θ)^2 + zero(μ)^2)
           t = sqrt((abs(θ) + hypot(θ, μ)) / 2)        
           return θ ≥ 0 ? t : μ / 2t
       end
_real_sqrt (generic function with 1 method)

julia> _real_sqrt(-0.3,-0.2)
-0.1740044935431251

julia> real(sqrt(-0.3-0.2im))
0.1740044935431251
```

Comment (jebej) [reply stdlib/LinearAlgebra/src/triangular.jl:2456]: sorry, this is actually not a sign issue, just a choice of which root to choose

Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl:2456]: That's right, yes.

File: stdlib/LinearAlgebra/src/triangular.jl (hunk 1 above)
Comment (stevengj) [reply stdlib/LinearAlgebra/src/triangular.jl:2445]: It's not about numerical stability, it's about avoiding spurious overflow/underflow.  For example, consider the case where `a21 = -(a12 = 1e300)`.

It's not exactly a `hypot` call, but it can maybe use a similar algorithm, e.g.:
```s
μₛ = max(abs(d), abs(a21), abs(a12))
μ = iszero(μₛ) ? float(μₛ) : μₛ * sqrt(-(d/μₛ)^2 - 4 * (a21/μₛ) * (a12/μₛ)) / 2
```

Comment (stevengj) [reply stdlib/LinearAlgebra/src/triangular.jl:2445]: (Unfortunately, all those additional divisions might have a non-negligible performance impact, since it sounds like this routine is performance-critical.)

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 3]
```diff
@@ -2435,25 +2435,31 @@ function _sqrt_quasitriu_offdiag_block!(R, A)
...
+@inline function _real_sqrt(θ, μ)
+    iszero(θ) && iszero(μ) && return sqrt(zero(θ)^2 + zero(μ)^2)
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/triangular.jl:2458]: Why is this special case needed?   Won't you get `t=0` and return `t` (from the `θ ≥ 0` branch) below?

File: stdlib/LinearAlgebra/src/triangular.jl (hunk 1 above)
Comment (stevengj) [reply stdlib/LinearAlgebra/src/triangular.jl:2445]: Maybe just `μₛ = max(abs(a21), abs(a12))` will suffice, since it looks like you must always have `|d| < max(|a21|, |a12|)` in this function (in order to have a real square root).

File: stdlib/LinearAlgebra/src/triangular.jl (hunk 3 above)
Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl:2458]: Yes, this is just for efficiency, because we can then skip a `sqrt` and `hypot` call. Perhaps something like this is more useful.

Comment (stevengj) [reply stdlib/LinearAlgebra/src/triangular.jl:2458]: Is it common enough to be worth the cost of the extra checks in the nonzero cases?

Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl:2458]: Actually, come to think of it, we should never hit this branch. If the 2x2 block has eigenvalues equal to 0, then it's the zero matrix, and it's not a 2x2 block.

File: stdlib/LinearAlgebra/src/triangular.jl (hunk 1 above)
Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl:2445]: Okay, thanks, I'll try that.

Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl]: I tested, and this _substantially_ improves the stability of the matrix square root.

**Comment by sethaxen** [comment]
With these changes, `_sqrt_real_2x2!` is ~40% slower. That being said, on a 20x20 matrix, `sqrt_quasitriu` is only ~4% slower. `sqrt` overflows and underflows much less with these changes, so I think this decrease in performance is worth it.

#### Updated Benchmarks

Setup:
```julia
using Random; Random.seed!(1)
F = schur(randn(20, 20)^2)
x = F.T[1:2,1:2] # 2x2 block
y = zero(x)
```

Before:
```julia
julia> @btime $(LinearAlgebra._sqrt_real_2x2!)($y, $x);
  35.130 ns (0 allocations: 0 bytes)
 
julia> @btime $(LinearAlgebra.sqrt_quasitriu)($(F.T));
  16.750 μs (1 allocation: 3.25 KiB)
```

This PR:
```julia
julia> @btime $(LinearAlgebra._sqrt_real_2x2!)($y, $x);
  50.037 ns (0 allocations: 0 bytes)

julia> @btime $(LinearAlgebra.sqrt_quasitriu)($(F.T));
  17.486 μs (1 allocation: 3.25 KiB)
```

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 4]
```diff
@@ -2445,7 +2445,8 @@ Base.@propagate_inbounds function _sqrt_real_2x2!(R, A)
     # avoid overflow/underflow of μ
     # for real sqrt, |d| ≤ 2 max(|a12|,|a21|)
     μₛ = max(abs(a12), abs(a21))
-    μ = μₛ * sqrt(-(d / μₛ)^2 - 4 * (a21 / μₛ) * (a12 / μₛ)) / 2
+    μₛ⁻¹ = inv(μₛ)
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/triangular.jl:2448]: Technically this only works if the scale factor is not subnormal.

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 5]
```diff
@@ -2435,25 +2435,34 @@ function _sqrt_quasitriu_offdiag_block!(R, A)
...
-        α = sqrt((sqrt(θ^2 + μ²) + θ) / 2)
-    else
-        α = μ / sqrt(2 * (sqrt(θ^2 + μ²) - θ))
-    end
+    # avoid overflow/underflow of μ
+    # for real sqrt, |d| ≤ 2 max(|a12|,|a21|)
+    μₛ = max(abs(a12), abs(a21))
+    μₛ⁻¹ = inv(μₛ)
+    μ = μₛ * sqrt(-(d * μₛ⁻¹)^2 - 4 * (a21 * μₛ⁻¹) * (a12 * μₛ⁻¹)) / 2
+    α = _real_sqrt(θ, μ)
```
Comment (sethaxen) [inline stdlib/LinearAlgebra/src/triangular.jl:2450]: @stevengj if we do this, then is there any need to use `hypot` in `_real_sqrt`?
```suggestion
    μ = sqrt(-(d * μₛ⁻¹)^2 - 4 * (a21 * μₛ⁻¹) * (a12 * μₛ⁻¹)) / 2
    α = _real_sqrt(θ * μₛ⁻¹, μ) * sqrt(μₛ)
```
we could then go back to writing in terms of `μ²` and get almost as fast as the original performance.

File: stdlib/LinearAlgebra/src/triangular.jl (hunk 4 above)
Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl:2448]: Hm okay, so division is safer.

File: stdlib/LinearAlgebra/src/triangular.jl (hunk 5 above)
Comment (stevengj) [reply stdlib/LinearAlgebra/src/triangular.jl:2450]: I don’t think this is safe, because theta might have a different scale.

File: stdlib/LinearAlgebra/src/triangular.jl [hunk 6]
```diff
@@ -2435,25 +2435,34 @@ function _sqrt_quasitriu_offdiag_block!(R, A)
...
-    if θ > 0
-        α = sqrt((sqrt(θ^2 + μ²) + θ) / 2)
-    else
-        α = μ / sqrt(2 * (sqrt(θ^2 + μ²) - θ))
-    end
+    # avoid overflow/underflow of μ
+    # for real sqrt, |d| ≤ 2 max(|a12|,|a21|)
+    μₛ = max(abs(a12), abs(a21))
+    μₛ⁻¹ = inv(μₛ)
+    μ = μₛ * sqrt(-(d * μₛ⁻¹)^2 - 4 * (a21 * μₛ⁻¹) * (a12 * μₛ⁻¹)) / 2
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/triangular.jl:2449]: Unfortunately on second thought this is not sufficient. It will cause a spurious underflow if a12=1e300 and a21=-1e-300, for example.

Comment (sethaxen) [reply stdlib/LinearAlgebra/src/triangular.jl]: I think I worked it out. The real schur decomposition produces `a11==a22`, so `d=0` is always true. Then we compute `sqrt(abs(a12))` and `sqrt(abs(a21))` instead and multiply that product, which I think should be safe from overflow and underflow.

**Comment by sethaxen** [comment]
The 2x2 diagonal block computation of `log` suffered from the same overflow/underflow, so I also adopted a similar approach for that.

**Comment by sethaxen** [comment]
With the recent changes, `_sqrt_real_2x2!` is almost as fast as the original:
```julia
julia> @btime $(LinearAlgebra._sqrt_real_2x2!)($y, $x);
  38.129 ns (0 allocations: 0 bytes)

julia> @btime $(LinearAlgebra.sqrt_quasitriu)($(F.T));
  17.354 μs (1 allocation: 3.25 KiB)
```

**Review by stevengj — APPROVED** [review]

**Comment by musm** [comment]
This is a bugfix so this probably needs to be backported?

**Comment by sethaxen** [comment]
> This is a bugfix so this probably needs to be backported?

No, this fixes bugs introduced in #39973. The new tests added here, which fail on master, pass on Julia 1.6.

**Comment by musm** [comment]
Merging, as this has been approved by @stevengj  and has had enough time for any objections or comments since then.
