### PR TITLE
fix scope rules: implicitly using a global doesn't add it to the scope

### LINKED ISSUE #21900: adding information to the section "Scope of Variables" (also: regression in variable scope identification pass)
Hi!

It was not clear to, after Reading the section [Scope of variables](https://docs.julialang.org/en/stable/manual/variables-and-scoping/) in the docs, that a variable is defined for a whole block, no matter where the variable is defined within the block. Perhaps it would be worthwhile calrifying this in the docs since understanding the scoping rules fully is very important. Perhaps adding something like this:

============================================================

Note that the location of a variable definition within a scope block is irrelevant (similar as with the 
`local` and `global` keywords as the following two examples show:

```
for i = 1:10
    foo = 1
    for j = 1:10
        foo = 10
    end
    bar = foo + 1
end
```

```
for i = 1:10
    for j = 1:10
        foo = 10
    end
    bar = foo + 1
    foo = 1
end
```

whereas the following example will fail:

```
for i = 1:10
    for j = 1:10
        foo = 10
    end
    bar = foo + 1   # Here foo is not defined
end
```

============================================================

I hope it is okay to ask for documentation improvements through issues, since creating a pull request for beginners needing good documentation is not so easy.

All the best
Jan

### PR DESCRIPTION
**Pull request by vtjnash**
fix #21900

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -438,16 +438,27 @@ glotest()
...
 end
 @test_throws UndefVarError f7234_a()
+@test f7234_cnt == 1
 begin
     global glob_x2 = 24
-    f7234_b() = (glob_x2 += 1)
+    function f7234_b()
+        global f7234_cnt += 1
+        glob_x2 += 1
+        global f7235_cnt += -10000
```
Comment (tkelman) [inline test/core.jl]: is this supposed to say 7234?

did anyone review this?
