### PR TITLE
power uses Float64 exponents for integers

### LINKED ISSUE #53881: BUG: `^(::Float64, ::Union{Int, Float64})` incorrect for very large negative exponents
The floating point power function fails for a border case of integer argument:

```
julia> 2.0 ^ typemin(Int) # should be 0.0
0.5

julia> (-1.0) ^ typemin(Int) # should be 1.0
-1.0
```

The bug seems to be here: [Base.Math.pow_body(::Float64, ::Integer)](https://github.com/JuliaLang/julia/blob/e07c0f1ddbfc89ad1ac4dda7246d8ed5d0d57c19/base/math.jl#L1326)

### PR DESCRIPTION
**Pull request by KlausC**
Improve performance of `^(::Float64, n::Integer)` in the case of `abs(n) > 2^13`.

While `pow_body` is unreliable for `abs(n) > 2^25` this implementation provides errors of a few ULPs, while runtime is capped to that of the `Float64` implementation.

Fixes  #53881
See also #53886.

### CODE REVIEW

**Comment by KlausC** [comment]
@oscardssmith I would be interested in your opinion!

**Comment by oscardssmith** [comment]
this looks really good to me. I need to spend a little time benchmarking to make sure all the details look good, but I'm theory, this looks great!

File: base/math.jl [hunk 1]
```diff
@@ -37,7 +37,7 @@ end
     throw(DomainError(x,
         LazyString(f," was called with a real argument < -1 but will only return a complex result if called with a complex argument. Try ", f,"(Complex(x)).")))
 end
-@noinline function throw_exp_domainerror(x)
+@assume_effects :terminates_globally @noinline function throw_exp_domainerror(x)
```
Comment (oscardssmith) [inline base/math.jl:40]: Is this really necessary? Throwing an error really should be known to terminate. Is LazyString getting in the way somehow? If so, IMO, this should be fixed on the LazyString side, not here.

File: base/math.jl [hunk 2]
```diff
@@ -1255,6 +1255,15 @@ function modf(x::T) where T<:IEEEFloat
     return (rx, ix)
 end
 
+@inline function use_power_by_squaring(n::Union{Int32,Int64,Int128,UInt32,UInt64,UInt128})
```
Comment (oscardssmith) [inline base/math.jl:1258]: is this function really used during bootstrap?

File: base/math.jl [hunk 3]
```diff
@@ -1267,19 +1276,28 @@ end
...
+        use_power_by_squaring(yint) && return @noinline pow_body(x, yint)
+    end
+    2*xu==0 && return abs(y)*Inf*(!(y>0)) # if x === +0.0 or -0.0 (Inf * false === 0.0)
+    s = 1
+    if x < 0
+        !yisint && throw_exp_domainerror(x) # y isn't an integer
+        s = ifelse(isodd(yint), -1, 1)
+    end
+    !isfinite(x) && return copysign(x,s)*(y>0 || isnan(x))           # x is inf or NaN
+    return copysign(pow_body(abs(x), y), s)
```
Comment (oscardssmith) [inline base/math.jl:1291]: why is this necessary?

File: base/math.jl [hunk 4]
```diff
@@ -1308,14 +1326,37 @@ end
     return T(exp2(log2(abs(widen(x))) * y))
 end
 
-# compensated power by squaring
 @constprop :aggressive @inline function ^(x::Float64, n::Integer)
+    T = Int64
+    m = n >= typemax(T) ? typemax(T) : n <= typemin(T) ? typemin(T) : n
+    x^(m%Int64)
+end
```
Comment (oscardssmith) [inline base/math.jl:1333]:
```suggestion
return x^clamp(n, Int64)
```

File: base/math.jl [hunk 5]
```diff
@@ -1308,14 +1326,37 @@ end
...
+# compensated power by squaring
+@constprop :aggressive @inline function ^(x::Float64, n::Int64)
     n == 0 && return one(x)
-    return pow_body(x, n)
+    if use_power_by_squaring(n)
+        return pow_body(x, n)
+    else
+        s = ifelse(x < 0 && isodd(n), -1.0, 1.0)
```
Comment (oscardssmith) [inline base/math.jl:1340]: can't this just be `pow_body(x, Float64(n))`?

File: base/special/exp.jl [hunk 6]
```diff
@@ -250,7 +250,7 @@ end
             twopk = (k + UInt64(53)) << 52
             return reinterpret(T, twopk + reinterpret(UInt64, small_part))*0x1p-53
         end
-        #k == 1024 && return (small_part * 2.0) * 2.0^1023
+        k == 1024 && return (small_part * 2.0) * 2.0^1023
```
Comment (oscardssmith) [inline base/special/exp.jl:253]: what's the case where this is necessary? I looked a bunch for it, but never could find it.

File: base/math.jl (hunk 1 above)
Comment (KlausC) [reply base/math.jl:40]: I had really to struggle with the compiler effects and I am not yet finished. This was an intermediate step and I will see, it it works without. (at the end we need ^(Float,Int) and ^(Float,Float) to be foldable.

File: base/math.jl (hunk 2 above)
Comment (KlausC) [reply base/math.jl:1258]: At least, when I called `Base.top_set_bit` the bootstrap compiler could not be built.

File: base/math.jl (hunk 3 above)
Comment (KlausC) [reply base/math.jl:1291]: You mean the sign extraction? In the master release the case of negative and integer `y` did not occur, because that was all handled in `^(Float, Int)`. Now we must handle also this signed case.

File: base/math.jl [hunk 7]
```diff
@@ -1267,19 +1276,28 @@ end
...
+    s = 1
+    if x < 0
+        !yisint && throw_exp_domainerror(x) # y isn't an integer
+        s = ifelse(isodd(yint), -1, 1)
+    end
+    !isfinite(x) && return copysign(x,s)*(y>0 || isnan(x))           # x is inf or NaN
+    return copysign(pow_body(abs(x), y), s)
+end
+
+@assume_effects :total @noinline function pow_body(x::Float64, y::Float64)
```
[the remark this answers is not in the document]
Comment (KlausC) [reply base/math.jl:1294]: I would very appreciate help to find out which effects are needed. Actually that was the first successful attempt, which rendered `^(Float64, Int64)` and `^(Float64,Float64)` foldable, as is verified in `test/math.jl` and maybe `test/numbers.jl`.
I will mitigate this assume_effects if possible.

File: base/math.jl (hunk 4 above)
Comment (KlausC) [reply base/math.jl:1333]: `clamp` was detected buggy when I tried to use it here (#54038), therefore this work-around.

File: base/math.jl (hunk 5 above)
Comment (KlausC) [reply base/math.jl:1340]: I will check, if `pow_body(Float,Float)` supports negative `x`. In the original code comments there is a hint, that the sign bit of `x` is used for a special purpose.

File: base/special/exp.jl (hunk 6 above)
Comment (KlausC) [reply base/special/exp.jl:253]: `prevfloat(1.0) ^ ( log2(floatmax()) / log2(prevfloat(1.0))` delivered `NaN` instead of the expected `Inf`.

File: base/math.jl (hunk 5 above)
Comment (oscardssmith) [reply base/math.jl:1340]: oh yeah, I think I used it for subnormal exponents

File: base/math.jl (hunk 4 above)
Comment (KlausC) [reply base/math.jl:1333]: I agree, that PR should be merged before this one.

File: base/math.jl (hunk 2 above)
Comment (KlausC) [reply base/math.jl:1258]: ... and  `Base.BitInteger` was not available. Obviously during bootstrap `^` is called.
Nevertheless I will probably simplify this function, because the exact modelling of the expected runtime, depending on the value of `n`, does not yield essential advantage over using something like `nmin <= n <= nmax` with sensible limits.

File: base/math.jl (hunk 1 above)
Comment (KlausC) [reply base/math.jl:40]: Seems not required - removed

File: base/math.jl (hunk 2 above)
Comment (oscardssmith) [reply base/math.jl:1258]: > nmin <= n <= nmax with sensible limits.
agreed that this is the way forward (especially since then you can just use `Integer`

File: base/math.jl (hunk 7 above)
[the remark this answers is not in the document]
Comment (KlausC) [reply base/math.jl:1294]: `@assume_effects :terminates_locally` was not enough.

[the remark this answers is not in the document]
Comment (oscardssmith) [reply base/math.jl:1294]: so the only problem with the effects is that `throw_exp_domainerror` was causing issues (I believe because of throw block de-optimization). However, the fix is very easy. If you just remove the LazyString, everything works out.

File: base/math.jl [hunk 8]
```diff
@@ -37,7 +37,7 @@ end
     throw(DomainError(x,
         LazyString(f," was called with a real argument < -1 but will only return a complex result if called with a complex argument. Try ", f,"(Complex(x)).")))
 end
-@noinline function throw_exp_domainerror(x)
+@assume_effects :terminates_globally @noinline function throw_exp_domainerror(x)
     throw(DomainError(x, LazyString(
```
Comment (oscardssmith) [inline base/math.jl:41]:
```suggestion
@noinline function throw_exp_domainerror(x)
    throw(DomainError(x,
```

Comment (oscardssmith) [reply base/math.jl:41]: The lazystring was what was breaking effects.

File: base/math.jl (hunk 7 above)
[the remark this answers is not in the document]
Comment (KlausC) [reply base/math.jl]: > so the only problem with the effects is that throw_exp_domainerror was causing issues

Sorry to have to contradict. According to my observations, there is no problem with `throw_exp_domainerror`. Neither removing `LazyString` nor adding  or removing `@assume_effects` from there made any difference.
Also this function is not called from `pow_body(Float,Float)` directly or indirectly.

[the remark this answers is not in the document]
Comment (KlausC) [reply base/math.jl]: Continuing my experiments with `@assume_effects for `pow_body(Float,Float)` lead to the result:
`@assume_effects :foldable` was sufficient to make `^(Float,Float)` foldable.

**Comment by KlausC** [comment]
Results of benchmark tests:
The abscissa is `sign(n) * log2(abs(n)` for integer exponents `n`.
The ordinate is in time per `x^n` for `x` close to `1.0`.
The first graph show execution times for ´x^n´ power_by_squaring, the second one for `n -> exp(log(x)*n)`.

grafik

The result of the merged version with parameters `nmin = -2^12, nmax = 3*2^13`:

grafik

**Comment by KlausC** [comment]
This plot demonstrates, that power-by-squaring has performance degradation, if result is `Inf`, and iteration continues.

grafik

File: base/math.jl (hunk 7 above)
[the remark this answers is not in the document]
Comment (oscardssmith) [reply base/math.jl]: hmm. I think I must have ran into an issue where Revise magically fixed the effects.

**Comment by oscardssmith** [comment]
note that the subnormal performance issue is only present on Intel cpus, AMD deals with subnormal much better.

**Comment by KlausC** [comment]
This screenshot shows the runtimes in v1.10.2.

image

**Comment by KlausC** [comment]
Statistics of accuracy evaluations. Note the very rare cases of 2 ULPs for low exponents (4 or 8), which can be explained by subnormal effects!
Evaluation functions defined in [script](https://raw.githubusercontent.com/KlausC/PlotDomainColoring.jl/main/src/statistics.jl?token=GHSAT0AAAAAACQXZY7KTJHPTIAUQVU7O746ZQ3WCBQ).

```
julia> nx = [randpower(maxex = 2^63-1) for _ in 1:10^6];

julia> D = stat_ulps(nx);

julia> overview(D)
1000000
0 => 947081.0
1 => 52919.0
total: n: 1.0e6 - median: 0.028 - mean: 0.053 ± 0.224 ulps

julia> nx = [randpower(maxex = 2^12) for _ in 1:10^6];

julia> D = stat_ulps(nx);

julia> overview(D)
1000000
0 => 767308.0
1 => 232689.0
2 => 3.0
total: n: 1.0e6 - median: 0.152 - mean: 0.233 ± 0.422 ulps

julia> nx = [randpower(maxex = 20) for _ in 1:10^6];

julia> D = stat_ulps(nx);

julia> overview(D)
1000000
0 => 807276.0
1 => 192718.0
2 => 6.0
total: n: 1.0e6 - median: 0.119 - mean: 0.193 ± 0.394 ulps

julia> D[2]
6-element Vector{Any}:
 (4, -1.3443718769635203e-77)
 (-4, -8.590649363573623e76)
 (-4, 9.096283725387172e76)
 (8, -3.621102224996767e-39)
 (-8, -3.2458640793370833e38)
 (-8, 2.727732223112257e38)
```

**Comment by KlausC** [comment]
The failed tests seem unrelated.
I am all set. Can someone review and merge if appropriate,

**Review by oscardssmith — APPROVED** [review]

**Comment by KlausC** [comment]
I have no idea, why `test compiler/codegen` uses `^` as a guinea-pig and also don't see how I should change the code in order to make this test succeed.

File: base/math.jl [hunk 9]
```diff
@@ -1292,7 +1292,7 @@ end
     return copysign(pow_body(abs(x), y), s)
 end
 
-@assume_effects :foldable @noinline function pow_body(x::Float64, y::Float64)
+@assume_effects :foldable @inline function pow_body(x::Float64, y::Float64)
```
[the remark this answers is not in the document]
Comment (KlausC) [reply base/math.jl:1295]: I introduced this, because I wanted to calm the last test in `compiler/codegen.jl`, which was introduced for PR #52194. In v1.10.2, this method is also inlined, and `exp_impl` is @inline at the definition site.
That did not work, because I could not enforce `exp_impl` to be inlined into `^` this way.

I would prefer to change that compiler test to make the implementation of `^` independent of those obscure multiversioning issues. @gbaraldi

[the remark this answers is not in the document]
Comment (oscardssmith) [reply base/math.jl:1295]: yeah, I think you could change the test to just be something like `evalpoly(Float64, NTuple{10, Float64})` rather than `^(Float64,Float64)`.

**Review by oscardssmith — APPROVED** [review]

File: base/math.jl [hunk 10]
```diff
@@ -1314,14 +1327,32 @@ end
...
+            return pow_body(x, y) * copysign(pow_body(x, n2), s)
+        end
+    end
 end
 
+# compensated power by squaring
+# this method is only reliable for -2^20 < n < 2^20 (cf. #53881 #53886)
 @assume_effects :terminates_locally @noinline function pow_body(x::Float64, n::Integer)
     y = 1.0
+    n == 0 && return y
```
Comment (oscardssmith) [inline base/math.jl:1355]: given that `n==0` is explicitly checked for in both versions of `^`, I'm pretty sure this is always redundant.

File: test/math.jl [hunk 11]
```diff
@@ -1470,6 +1470,24 @@ end
     # two cases where we have observed > 1 ULP in the past
     @test 0.0013653274095082324^-97.60372292227069 == 4.088393948750035e279
     @test 8.758520413376658e-5^70.55863059215994 == 5.052076767078296e-287
+
+    # issue #53881
+    @test prevfloat(1.0) ^ -Int64(2)^62 == 2.2844135865398217e222
```
Comment (oscardssmith) [inline test/math.jl:1475]: this test is slightly overspecified. I would change it to `≈`

**Comment by oscardssmith** [comment]
Other than the final 2 comments, I think is ready to merge.

**Comment by KristofferC** [comment]
Causes a test error on 1.11, won't backport.

**Comment by KlausC** [comment]
> Causes a test error on 1.11, won't backport.

@KristofferC is there a chance to look at the failed test output? I could not verify that locally.

**Comment by KristofferC** [comment]
It is only on 32-bit. https://github.com/JuliaLang/julia/pull/58062 might fix it. But it is too late for 1.11.5, it can go into 1.11.6 if it is fixed with the earlier-mentioned PR. 

The error was https://buildkite.com/julialang/julia-release-1-dot-11/builds/451#019619be-f75a-400d-b019-9d047c239bd3

```

Test Failed at /cache/build/tester-amdci5-15/julialang/julia-release-1-dot-11/julia-88568a8784/share/julia/test/math.jl:1600
--
  | Expression: Core.Compiler.is_foldable(effects)
  | Context: effects = (+c,+e,+n,!t,+s,+m,+u,+o,+r)
  | T = Float64
```
