### PR TITLE
CSL_jll: Fix `libatomic` path for FreeBSD

### LINKED ISSUE #57808: CompilerSupportLibraries_jll missing libatomic
New CSL bug (since 4975b84a078b2785041107b6339596e778545226) caught in CI:
```
      From worker 5:	┌ Error: missing libatomic in CompilerSupportLibraries_jll
      From worker 5:	└ @ Main.Test72Main_misc /usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-2/julialang/julia-master/julia-db251ca6ae/share/julia/test/misc.jl:1419
Compiler/EscapeAnalysis                          (2) |    77.60 |   1.27 |  1.6 |    2064.53 |  2613.46
Compiler/inline                                  (2) |        started at 2025-03-17T18:21:06.279
misc                                             (5) |         failed at 2025-03-17T18:21:30.887
Test Failed at /usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-2/julialang/julia-master/julia-db251ca6ae/share/julia/test/misc.jl:1420
  Expression: isdefined(mod, v)
```
https://buildkite.com/julialang/julia-master/builds/45913#0195a4f9-507d-401a-a442-286f09c0125a

### PR DESCRIPTION
**Pull request by topolarity**
This is required to avoid introducing a name / binding in the Module without a corresponding definition.

Resolves #57808

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

File: stdlib/CompilerSupportLibraries_jll/src/CompilerSupportLibraries_jll.jl [hunk 1]
```diff
@@ -5,7 +5,10 @@
 baremodule CompilerSupportLibraries_jll
 using Base, Libdl, Base.BinaryPlatforms
 
-export libgfortran, libstdcxx, libgomp, libatomic, libgcc_s
+export libgfortran, libstdcxx, libgomp, libgcc_s
+if !Sys.isfreebsd()
+    export libatomic
+end
```
Comment (giordano) [inline stdlib/CompilerSupportLibraries_jll/src/CompilerSupportLibraries_jll.jl:11]: As I already said in https://github.com/JuliaLang/julia/issues/57808#issuecomment-2730962540, I'm confused: libatomic _is_ in https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.3.1%2B0/CompilerSupportLibraries.v1.3.1.x86_64-unknown-freebsd-libgfortran5.tar.gz.  I'm not convinced this the right solution, feels to me like libatomic is getting lost.

Comment (topolarity) [reply stdlib/CompilerSupportLibraries_jll/src/CompilerSupportLibraries_jll.jl]: Thanks for pointing that out @giordano , I think you're right.

**Comment by staticfloat** [comment]
Yes, when manually putting these files together, I must have searched for the presence of `libatomic.so.1`, not `libatomic.so.*`.  Whoops.
