### PR TITLE
avoid overflow in histrange

### LINKED ISSUE #13326: hist(rand(Int64,50)) results in DomainError
It looks like histrange() calls log10() with a negative argument due to Int64 overflow.

```jl
julia> hist(rand(Int64,50))                                                                                                                                                     
ERROR: DomainError                                                                                                                                                              
 in histrange at statistics.jl:555                                                                                                                                              
 in hist at statistics.jl:599
```

I was able to replicate this on juliabox:
```jl
julia> versioninfo()                                                                                                                                                            
Julia Version 0.3.11                                                                                                                                                            
Commit 483dbf5* (2015-07-27 06:18 UTC)                                                                                                                                          
Platform Info:                                                                                                                                                                  
  System: Linux (x86_64-unknown-linux-gnu)                                                                                                                                      
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz                                                                                                                                
  WORD_SIZE: 64                                                                                                                                                                 
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)                                                                                                          
  LAPACK: libopenblas                                                                                                                                                           
  LIBM: libopenlibm                                                                                                                                                             
  LLVM: libLLVM-3.3  
```

### PR DESCRIPTION
**Pull request by simonbyrne**
fixes #13326

### CODE REVIEW

File: test/statistics.jl [hunk 1]
```diff
@@ -307,6 +307,11 @@ end
 @test histrange([1, 600], 4) == 0.0:200.0:600.0
 @test histrange([1, -1000], 4) == -1500.0:500.0:500.0
 
+# issue #13326
+l,h = extrema(histrange([typemin(Int),typemax(Int)], 10)
```
Comment (tkelman) [inline test/statistics.jl]: missing a close paren

Comment (simonbyrne) [inline test/statistics.jl]: thanks!
