### PR TITLE
Inference of circcopy and circshift

### LINKED ISSUE #35248: `circcopy!`does not infer for 3D arrays (does for 2D)
Hello,

Cross posting from [discourse](https://discourse.julialang.org/t/circcopy-does-not-infer-for-3d-arrays/36401) . This affects the inference of the [fft for 3D arrays](https://discourse.julialang.org/t/fft-w-does-not-infer/36393/10) for example.

Feel free to close if this is not a bug.

Cheers!

### LINKED ISSUE #35396: circshift does not infer for arrays of dimension >2
Hello,

this is related to https://github.com/JuliaLang/julia/issues/35248, they probably fail to infer for the same reason (recursive function definitions). 

```
julia> @code_warntype debuginfo=:source optimize=:true circshift!(zeros(3,3),rand(3,3),(1,1))
Variables
  #self#::Core.Compiler.Const(circshift!, false)
  dest::Array{Float64,2}
  src::Array{Float64,2}
  shiftamt::Tuple{Int64,Int64}
  inds::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}

Body::Array{Float64,2}
....

julia> @code_warntype debuginfo=:source optimize=:true circshift!(zeros(3,3,3),rand(3,3,3),(1,1,1))
Variables
  #self#::Core.Compiler.Const(circshift!, false)
  dest::Array{Float64,3}
  src::Array{Float64,3}
  shiftamt::Tuple{Int64,Int64,Int64}
  inds::Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}

Body::Any
...
│           invoke Base._circshift!(_2::Array{Float64,3}, %171::Tuple{UnitRange{Int64},UnitRange{Int64}}, _3::Array{Float64,3}, %172::Tuple{UnitRange{Int64},UnitRange{Int64}}, %169::Tuple{Base.OneTo{Int64}}, %170::Tuple{Int64})
│    %174 = Core.tuple(%79, %160)::Tuple{UnitRange{Int64},UnitRange{Int64}}
│    %175 = Core.tuple(%82, %163)::Tuple{UnitRange{Int64},UnitRange{Int64}}
│    %176 = invoke Base._circshift!(_2::Array{Float64,3}, %174::Tuple{UnitRange{Int64},UnitRange{Int64}}, _3::Array{Float64,3}, %175::Tuple{UnitRange{Int64},UnitRange{Int64}}, %169::Tuple{Base.OneTo{Int64}}, %170::Tuple{Int64})::Any
└───        goto #25
25 ─        goto #26
26 ─        return %176
...
```

I will try to push an easy fix, not sure if that is the right approach though.

Cheers!

### PR DESCRIPTION
**Pull request by raminammour**
Hello,

Locally, this fixes https://github.com/JuliaLang/julia/issues/35396 and fixes https://github.com/JuliaLang/julia/issues/35248. I guess the recursive function definition is not inferring and the type assertion helps. It prevents the type instability to propagate further.

This is an easy/lazy fix, please feel free to close if this is not appropriate or suggest a better fix :)

Cheers!

### CODE REVIEW

**Comment by stevengj** [comment]
LGTM, but would be nice to know what the source of the underlying inference failure is.

@JeffBezanson, are we running into a limitation of the underlying inference code here for mutually recursive functions?

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
Would be good to have a test, though.  Maybe just put `@inferred` into some of the existing `circshift` and `circcopy` tests?

**Review by stevengj — CHANGES_REQUESTED** [review]
Needs regression tests.

**Comment by raminammour** [comment]
I agree that this needs test so it doesn't regress again. Note that the inference succeeds for 2D arrays but not for dimensions 3 or higher. Looking at the tests quickly, all are <= 2D tests.

File: test/arrayops.jl [hunk 1]
```diff
@@ -702,8 +702,17 @@ end
     @test_throws ArgumentError Base.circshift!(a, a, 1)
     b = copy(a)
     @test Base.circshift!(b, a, 1) == [5,1,2,3,4]
```
Comment (stevengj) [inline test/arrayops.jl:704]: You can just add `@inferred(...)` to this.

Comment (raminammour) [reply test/arrayops.jl]: Ok, I guess it can't hurt. But note that the tests I added before are needed.
Inference succeeds without this PR (the type assertion), for arrays of dimension 1 & 2. So this test would pass, even without this PR.

**Comment by timholy** [comment]
This seems fine. If someone wants to put time into a more thorough fix,
- consider removing the `@inline` and `@noinline` annotations
- avoid growing tuples. Use `setindex` (without the !) to modify tuples that start out with the length of the dimensionality. `shiftamt` can still shrink as a marker of which dimension is being worked on currently.
