### PR TITLE
Don't ignore memcpy in GC root placement

### LINKED ISSUE #23522: nondeterministic ranges test failure
Similar to https://github.com/JuliaLang/julia/issues/23497 but I think this is actually quite difference since the test is nondeterministic even after the random number is fixed. Possibly a compiler/llvm bug. I haven't looked into it yet.

Reproduced with the following code.
When it fails, none of `strt`, `Δ`, `stop` are `NaN` but the start and end of `r` are both `NaN`.

```julia
@noinline function f(strt, Δ, i, r, stop)
    @show(strt, Δ, i, r, stop)
    ccall(:jl_breakpoint, Void, ())
    error("")
end

function range_fuzztests(N)
    for i = 1:N
        strt = 1.3761519988366908
        Δ = -0.7928641255557751
        stop = 0.5832878732809157
        r = strt:Δ:stop
        if !(strt == first(r))
            f(strt, Δ, i, r, stop)
        end
    end
end
# @code_warntype range_fuzztests(5 * 2^16)
# @code_llvm range_fuzztests(5 * 2^16)
range_fuzztests(5 * 2^16)
```

### PR DESCRIPTION
**Pull request by Keno**
If @yuyichao's analysis is correct, should fix #23522, though I've been unable to reproduce the failure myself (perhaps due to differing LLVM versions).

### CODE REVIEW

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/23522 might only be reproducible with `WITH_GC_DEBUG_ENV` on. (or at least `WITH_GC_SCRUB`) The `NaN` comes from the GC filling possibly unrooted object with `0xff`.

**Comment by Keno** [comment]
Can you check this PR locally and see if it fixes your issue?

**Comment by yuyichao** [comment]
Checking.

File: src/llvm-late-gc-lowering.cpp [hunk 1]
```diff
@@ -727,8 +727,8 @@ State LateLowerGCFrame::LocalScan(Function &F) {
         for (auto it = BB.rbegin(); it != BB.rend(); ++it) {
             Instruction &I = *it;
             if (CallInst *CI = dyn_cast<CallInst>(&I)) {
-                if (isa<IntrinsicInst>(CI)) {
-                    // Intrinsics are never GC uses/defs
+                if (isa<IntrinsicInst>(CI) && !isa<MemIntrinsic>(CI)) {
```
Comment (yuyichao) [inline src/llvm-late-gc-lowering.cpp]: I assume this covers other intrinsics that touches memory? (like scatter, gather etc.)?

Comment (yuyichao) [reply src/llvm-late-gc-lowering.cpp]: And maybe add this condition back below where we check `pointer_from_objref` and `memcmp` so that they won't be treated as safepoints?

**Review by yuyichao — APPROVED** [review]
Running the script in https://github.com/JuliaLang/julia/issues/23522 102 times without triggering the issue. The llvm IR generated for `colon(::Float64, ::Float64, ::Float64)` also looks correct now.

LGTM other than the minor comments above.

**Comment by yuyichao** [comment]
Just for fun, the probability that this didn't fix #23522 is smaller than 10^-200 ;-p

File: src/llvm-late-gc-lowering.cpp (hunk 1 above)
Comment (Keno) [reply src/llvm-late-gc-lowering.cpp]: Ah, I forgot about scatter and gather. There's probably also some machine specific intrinsic intrinsics that take memory operands. Probably easiest to just check debug and lifetime here (which are the only ones we emit frequently), but still declare all intrinsics as non-safepoint.

File: src/llvm-late-gc-lowering.cpp [hunk 2]
```diff
@@ -728,8 +728,16 @@ State LateLowerGCFrame::LocalScan(Function &F) {
...
+                    // Most intrinsics are not gc uses/defs, however some have
+                    // memory operands and could thus be GC uses. To be conservative,
+                    // we only skip processing for those that we know we emit often
+                    // and cannot possibly be GC uses.
+                    IntrinsicInst *II = cast<IntrinsicInst>(CI);
+                    if (isa<DbgInfoIntrinsic>(CI) ||
+                        II->getIntrinsicID() == Intrinsic::lifetime_start ||
+                        II->getIntrinsicID() == Intrinsic::lifetime_end) {
+                        continue;
+                    }
```
Comment (yuyichao) [inline src/llvm-late-gc-lowering.cpp]: This version certainly looks better than the original one, which already looks good to me but you did remind me of a llvm intrinsic that I happened to notice the other day. [`llvm.load.relative`](http://llvm.org/docs/LangRef.html#llvm-load-relative-intrinsic) is the only instruction I've found so far that returns a derived pointer. Probably don't need to worry about it as long as LLVM optimization passes don't emit it?

Comment (Keno) [reply src/llvm-late-gc-lowering.cpp]: Thanks, I didn't know about that intrinsic (in my defensive it's only about a year old ;)), but yeah, I don't think we have to worry about it.
