### PR TITLE
Make flisp calls thread safe and task switch safe

### LINKED ISSUE #14354: flisp is not thread safe
I'm pretty sure people already know this but I'm just looking for new ways to crash julia with threading and I couldn't find this problem mentioned in any open issues (https://github.com/JuliaLang/julia/issues/10421 or https://github.com/JuliaLang/julia/issues/1790).

The following code easily causes a segfault in flisp
```jl
@threads for i in 1:10000
    parse("1")
end
```

Garding `parse("1")` with a lock makes the SegFault go away. However, I'm not sure adding a `flisp` lock is the right solution here. We call back to arbitrary julia code/runtime in `macroexpand` and doing that while holding a lock doesn't sound like a particularly good idea. (We also don't hold any lock when instantiating a stage function....)

What's the right solution here? Can we release the `flisp` lock when evaluating julia code? (can flisp handle that?) Or can flisp be made more thread safe?

@JeffBezanson

### PR DESCRIPTION
**Pull request by yuyichao**
This wrap ~~most~~ all of the flisp states (~~there's a few static buffers that I didn't wrap so this dosn't make flisp completely thread safe~~ all wrapped now) in a struct and switch the context when different tasks/threads want to run the parser.

I've come to the conclusion that we have to do this since we have a few places that need to maintain the flisp states while executing arbitrary julia code. This not only include macro expansions (which we can kind of deal with in an ugly way by not allowing task switches or threads/locks) but also `jl_parse_eval_all` which is used by `jl_load` and not allowing task switches there basically means not allowing it anywhere. Moreover, this is also the only way I can think of to make the parser thread safe without dead lock.

The context manage for the parser/flisp currently create new context on demand and saves the used context in a free list so the only case we need to instantiate multiple instances of flisp is when the user code actually need them (i.e. in all the cases that currently segfault).

Things that can be improved.
1. The flisp contexts are never freed. Mainly because I didn't find a way to do that. (Ref https://github.com/JuliaLang/julia/issues/13540)
2. ~~We keep two static copy of the flisp context (since julia keeps a few more states) We could save one of them by moving that to the flisp main function instead.~~ Done

Fix #14354 
@JeffBezanson

### CODE REVIEW

**Comment by yuyichao** [comment]
Task switch safe and thread safe are tested with the following two scripts on top of #14190 .

[Task switch safe](https://github.com/yuyichao/explore/blob/52aaf54b3bca956501960c9a543c4118a40c961e/julia/gc_thread/flisp-task.jl)
[Thread safe](https://github.com/yuyichao/explore/blob/52aaf54b3bca956501960c9a543c4118a40c961e/julia/gc_thread/flisp.jl)

File: src/flisp/cvalues.c [hunk 1]
```diff
@@ -4,28 +4,31 @@
 #define NWORDS(sz) (((sz)+3)>>2)
 #endif
 
-static int ALIGN2, ALIGN4, ALIGN8, ALIGNPTR;
-
-value_t int8sym, uint8sym, int16sym, uint16sym, int32sym, uint32sym;
-value_t int64sym, uint64sym;
-value_t ptrdiffsym, sizesym, bytesym, wcharsym;
-value_t floatsym, doublesym;
-value_t gftypesym, stringtypesym, wcstringtypesym;
```
Comment (yuyichao) [inline src/flisp/cvalues.c]: This (`gftypesym`) should be the only global symbol that I removed. It doesn't seem to be used anywhere. @JeffBezanson

File: src/flisp/table.c [hunk 2]
```diff
@@ -89,16 +87,16 @@ value_t fl_table(value_t *args, uint32_t nargs)
...
     size_t cnt = (size_t)nargs;
     if (cnt & 1)
-        lerror(ArgError, "table: arguments must come in pairs");
+        lerror(fl_ArgError, "table: arguments must come in pairs");
     value_t nt;
     // prevent small tables from being added to finalizer list
     if (cnt <= HT_N_INLINE) {
-        tabletype->vtable->finalize = NULL;
-        nt = cvalue(tabletype, sizeof(htable_t));
-        tabletype->vtable->finalize = free_htable;
```
Comment (yuyichao) [inline src/flisp/table.c]: And this should be the only change that is not simply renaming so that I can make the `vtable` field (and the `vtab` argument) a const pointer. @JeffBezanson

**Comment by yuyichao** [comment]
Some of the renaming in flisp might not be strictly necessary but I add the `fl_` prefix to all the fields in the flisp global context (even those that are not exported) to avoid accidental name clashing since macros are not protected by c scope.

File: src/ast.c [hunk 3]
```diff
@@ -25,20 +25,68 @@ extern "C" {
...
+}
+
+typedef struct _jl_ast_context_t {
+    fl_global_context_t fl;
+    fltype_t *jvtype;
+
+    value_t true_sym;
+    value_t false_sym;
+    value_t error_sym;
+    value_t null_sym;
```
Comment (JeffBezanson) [inline src/ast.c]: These symbols are constants, and not allocated on flisp's managed heap, so it should be possible to share them among all contexts.

**Comment by JeffBezanson** [comment]
What's the performance impact on the front end? Some of the variables in flisp (e.g. `Stack`) are very hot so I'd be curious.

**Comment by yuyichao** [comment]
@JeffBezanson Any suggestions what I should benchmark?

**Comment by JeffBezanson** [comment]
`using Gadfly` with nothing precompiled. Or just a source file with a simple function definition repeated 10000 times or so.

**Comment by JeffBezanson** [comment]
I think we should get rid of the jl_start_parsing_file/jl_parse_next API. It's gratuitously stateful. Then maybe we could make flisp contexts thread-local (allocated lazily) instead of needing a context manager. But we should get rid of that API anyway since it's pretty ugly.

**Comment by yuyichao** [comment]
I just did a simple test with `include_string("1 + 1\n1 + 1")` (will try more careful ones later) and it seems that with this naive approach, the time is indeed ~2x longer (310us -> 650us). However, using the same trick for the TLS buffer, (using a `__attribute__((const))` getter function instead) the difference in time is down to <10% slower (310us -> 330us).

**Comment by JeffBezanson** [comment]
Interesting. We might also want to lift the value of key variables like fl_Stack into local variables in apply_cl (where all the work is done).

**Comment by yuyichao** [comment]
I wasn't paying too much attention on the frontend performance when I made the change (was mainly focusing on getting rid of the crash...). I'll benchmark it more carefully and do some optimizations as you suggested tomorrow (I mean today....). I agree with getting rid of the `jl_parse_next` API, especially since that was the stateful part that I didn't realize (and therefore got a lot of segfaults) for a long time...

I'm not totally convienced that we should just disallow context switches in macros but if we can make io synchronous in it and get rid of the context manager, I can live with that too. (Adding it back won't be hard anyway if there's a case that's hard to workaround....)

**Comment by yuyichao** [comment]
So I've tried my simple `include_string` benchmark and also parsing and expanding `inference.jl` (the largest `.jl` file I find in base and I only parse or expand it in order to avoid also timing the evaluation).

With my original version, it seems to be ~20-30% slower (the 2x slower I quote last night must have been some CPU frequency scaling issues during the few minutes I was running the tests). Either defining the functions as `const` or caching the global load for some hot functions get this down to ~5-6% slower.

I pick the caching method even though it requires slightly more code since we don't have to worry about compiler mis-optimization this way (because the `const` function is not allowed to move pass a `enter` or `leave`)

**Comment by yuyichao** [comment]
Hmm, this is the first time I see the io error on OSX travis
https://travis-ci.org/JuliaLang/julia/jobs/97284396

**Comment by tkelman** [comment]
That rules out docker then?

**Comment by yuyichao** [comment]
I guess?
I tried a few different make command locally but couldn't reproduce it, we shouldn't be doing anything funny on the file either (`strace` just shows `stat` and `open`)

**Comment by yuyichao** [comment]
So I went one step further and make flisp truely stateless. The global context is removed and the flisp context is always explicitly passed around as the first argument (except for the hash table function, which use the last argument to be consistent with the convension of libc functions for user data). There's also some renaming to keep the code shorter.

This simplifies the context manager a lot. It only needs to manage the reference counting now and the save and restore operations are gone. This also makes it possible to run multiple flisp instances on difference threads concurrently. There's still a flisp lock but it is only used to protect the critical regions of the context manager free list.

Note that the `JL_LOCK` needs to be replaced with `jL_LOCK_NOGC` after #14190.

**Comment by yuyichao** [comment]
Benchmarked on a desktop that doesn't have dynamic frequency scaling problem.

`include_string("1 + 1\n1 + 1")`: ~4-5% slower
`parse` on `inference.jl` (whole file wrapped in a module): ~3-4% slower
`expand` the AST from previous one: ~3-4% slower

I'm personally happy with this level of performance hit as the price of getting rid of segfaults....

**Comment by yuyichao** [comment]
Travis/PR Lin32:

```
The command "make $BUILDOPTS -C base version_git.jl.phony" exited with 0.
1.01s$ make $BUILDOPTS NO_GIT=1 -C deps > deps.log || cat deps.log
libtool: install: warning: remember to run `libtool --finish /home/travis/build/JuliaLang/julia/usr/lib'
Makefile:44: Makefile.config: No such file or directory
Makefile:141: /Makefile.rules: No such file or directory
make[1]: *** No rule to make target `/Makefile.rules'.  Stop.
make: *** [build/llvm-3.3/build_Release/Release/lib/libLLVMCodeGen.a] Error 2
make: *** Waiting for unfinished jobs....
```

Not even starting to build our code yet?

**Comment by yuyichao** [comment]
Travis should be fixed now. Restarted.

**Comment by yuyichao** [comment]
Ping.

**Comment by yuyichao** [comment]
Same with https://github.com/JuliaLang/julia/pull/14190#issuecomment-169063023 . This needs an update after #14190 is merged so will merge after a rebase and CI run after #14190.

**Comment by JeffBezanson** [comment]
:+1:

**Comment by vtjnash** [comment]
Do you have any thoughts on how we can fix `jl_gc_preserve`? Currently, it isn't task-switch safe either.

**Comment by yuyichao** [comment]
> Do you have any thoughts on how we can fix `jl_gc_preserve`?

Good point. I only checked it is thread safe but didn't think about task switches. The `jl_gc_preserve` API always feels scratchy so even though task switch during macro expansion is not the best thing to do, maybe we can just remove that api and use a root array in the flisp context instead? (and make sure the array is rooted on stack)?
