### PR TITLE
Fix #16326: use typesof in code_* for all :call expressions

### LINKED ISSUE #16326: `@code_*` can't handle anonymous function arguments
```jl
function isort!(v::Vector, lt::Function=<)
    @inbounds for i = 2:length(v)
        j = i
        x = v[i]
        while j > 1
            if lt(x, v[j-1])
                v[j] = v[j-1]
                j -= 1
                continue
            end
            break
        end
        v[j] = x
    end
    return v
end
```

```jl
julia> @code_native isort!(a, (x,y)->abs(x)<abs(y))
ERROR: expression is not a function call, or is too complex for @code_native to analyze; break it down to simpler parts if possible
 in error(::String) at ./error.jl:21
 in eval(::Module, ::Any) at ./boot.jl:230
```

### PR DESCRIPTION
**Pull request by ihnorton**
Not sure about `The tricky cases [...] like ref for getindex, vcat, etc.`, but this fixes #16326 and #16487.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
+1 This is much needed. I wonder what's causing the failure?

**Comment by tkelman** [comment]
test?

**Comment by ihnorton** [comment]
767ddc7

File: base/interactiveutil.jl [hunk 1]
```diff
@@ -278,7 +278,8 @@ typesof(args...) = Tuple{map(a->(isa(a,Type) ? Type{a} : typeof(a)), args)...}
 gen_call_with_extracted_types(fcn, ex0::Symbol) = Expr(:call, fcn, Meta.quot(ex0))
 function gen_call_with_extracted_types(fcn, ex0)
     if isa(ex0, Expr) &&
-        any(a->(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex0.args)
+          (any(a->(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex0.args) ||
+           ex0.head == :call)
```
Comment (andreasnoack) [inline base/interactiveutil.jl]: I think this kills the branch in 296 completely. The main requirement for fixing https://github.com/JuliaLang/julia/issues/17469 is that the expression goes through the `expand` step in line 290. However, it's hard to predict the consequences of changes to this function.
