### PR TITLE
Stop using view in adaptive sort

### LINKED ISSUE #45522: Error in runtime on master
The following code produces a runtime error on master (commit 5a32626 from today):
```julia
using FASTX # v1.3.0
println(first(FASTQ.Reader(IOBuffer("@A\nA\n+\nA"))))
```
The error is:
```
Internal error: encountered unexpected error in runtime:
UndefVarError(var=:view)
ijl_undefined_var_error at /home/jakni/code/julia/src/rtutils.c:132
ijl_get_binding_or_error at /home/jakni/code/julia/src/module.c:407
sort! at ./sort.jl:775
sort! at ./sort.jl:864 [inlined]
#sort!#8 at ./sort.jl:913 [inlined]
sort! at ./sort.jl:907 [inlined]
#sort#9 at ./sort.jl:961 [inlined]
sort at ./sort.jl:961 [inlined]
domsort_ssa! at ./compiler/ssair/slot2ssa.jl:399
construct_ssa! at ./compiler/ssair/slot2ssa.jl:906
slot2reg at ./compiler/optimize.jl:691 [inlined]
run_passes at ./compiler/optimize.jl:546
run_passes at ./compiler/optimize.jl:561 [inlined]
optimize at ./compiler/optimize.jl:510 [inlined]
_typeinf at ./compiler/typeinfer.jl:257
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:907
abstract_call_method at ./compiler/abstractinterpretation.jl:601
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:161
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
abstract_call at ./compiler/abstractinterpretation.jl:1768
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1889
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2243
typeinf_local at ./compiler/abstractinterpretation.jl:2420
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2518
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:907
abstract_call_method at ./compiler/abstractinterpretation.jl:601
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:161
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
abstract_call at ./compiler/abstractinterpretation.jl:1768
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1889
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2243
typeinf_local at ./compiler/abstractinterpretation.jl:2420
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2518
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:907
abstract_call_method at ./compiler/abstractinterpretation.jl:601
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:161
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
abstract_call at ./compiler/abstractinterpretation.jl:1768
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1889
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2243
typeinf_local at ./compiler/abstractinterpretation.jl:2420
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2518
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:907
abstract_call_method at ./compiler/abstractinterpretation.jl:601
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:161
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
abstract_call at ./compiler/abstractinterpretation.jl:1768
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1889
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2243
typeinf_local at ./compiler/abstractinterpretation.jl:2420
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2518
```

### PR DESCRIPTION
**Pull request by LilithHafner**
Fixes #45522

### CODE REVIEW

**Comment by LilithHafner** [comment]
Local tests look good
```julia
(jl_2RvVlb) pkg> status
Status `/private/var/folders/hc/fn82kz1j5vl8w7lwd4l079y80000gn/T/jl_2RvVlb/Project.toml`
  [c2308a5c] FASTX v1.3.0

julia> using FASTX

julia> println(first(FASTQ.Reader(IOBuffer("@A\nA\n+\nA"))))
@A
A
+
A
```
I don't think we should include this test in test/sorting.jl.

File: base/sort.jl [hunk 1]
```diff
@@ -761,6 +761,12 @@ function _extrema(v::AbstractVector, lo::Integer, hi::Integer, o::Ordering)
     end
     mn, mx
 end
+function _issorted(v::AbstractVector, lo::Integer, hi::Integer, o::Ordering)
+    @inbounds for i in (lo+1):hi
```
Comment (jishnub) [inline base/sort.jl:765]: Is `@inbounds` safe here? I didn't see a check for `lo` and `hi` being in `eachindex(v)`, but perhaps I've missed it. Maybe that needs to be added if it's not there already

Comment (LilithHafner) [reply base/sort.jl:765]: Sort of. The safety issues here are part of the larger issue of clearly demarcating the sorting API. [Officially](https://docs.julialang.org/en/v1/manual/faq/#man-api), "Functions, types, and constants are not part of the public API if they are not included in the documentation, _even if they have docstrings_." `_issorted`, much like `_extrema` above is clearly internal. `sort!(v::AbstractVector)` is clearly a part of the public API, and, as far as I can tell, whenever that public facing `sort!` calls `sort!(v, lo, hi, alg, order)`, `lo` and `hi` are drawn from within the axes of the input vector. The `sort!(v, lo, hi, alg, order)` method is not mentioned in the documentation and assumes `lo` and `hi` are inbounds everywhere already. This is bad because the function is public facing and it's ambiguous whether those methods are public or not.

If you call standard sorting methods it is somewhat safe, checked two-ish frames up the call stack. This is not good enough, but adding bounds checking here would not meaningfully improve the situation. For example, we make the same assumption that `lo` and `hi` are inbounds just above with `lenm1 < 40 && return sort!(v, lo, hi, SMALL_ALGORITHM, o)` and just below with `v_min, v_max = _extrema(v, lo, hi, o)`.

I plan to fix all this in a refactoring described [here](https://github.com/JuliaLang/julia/discussions/44876#discussioncomment-2768446) (hopefully in v1.9 or v1.10).

**Comment by ViralBShah** [comment]
Should we try get this merged, or should we wait on the refactor?

**Comment by LilithHafner** [comment]
Let's proceed here. The changes are pretty low risk, and I'd be happy to merge as is. I don't think bounds checking is necessary here given the conventions we have in this part of the codebase. Still, this code only runs for lengths > 30 ish, so we can add explicit bounds checking before the loop without measurable performance overhead if folks prefer it that way.

**Comment by ViralBShah** [comment]
Yeah it would be good to bring the bounds check in and get this merged.

**Comment by LilithHafner** [comment]
Refactoring, making sorting a stdlib, and improving quicksort are all pretty orthogonal, but I suspect that would have some merge conflicts.

I think it makes sense to improve quicksort before refactoring because one of the advantages it brings is that making quicksort stable simplifies policy, which will be good to either take advantage of (if it merges) or not wrongly hope for (if benchmarking or code review comes out catastrophically negative).

I also think that making sorting a stdlib should come after refactoring because part of sorting will have to stay behind for `Core.Compiler.Sort.sort!`, and I'd like to have sorting nicely formatted when it comes time to make that split.

**Comment by LilithHafner** [comment]
Lol, not entirely orthogonal, that build error and merge conflict would not have happened if sorting was a stdlib.

**Comment by LilithHafner** [comment]
This looks good to me. If other folks agree, I'd like to merge it so I can use `_issorted` to address https://github.com/JuliaLang/julia/pull/45222#issuecomment-1188290358.

**Comment by ViralBShah** [comment]
Would it be helpful to have a label for `sorting`?

**Comment by ViralBShah** [comment]
I believe CI is down for maintenance. So this probably needs to be held until CI is back online and we can run everything again.

**Comment by LilithHafner** [comment]
> Would it be helpful to have a label for sorting?

It would be helpful to me. I often find myself using the search term "sort".

> So this probably needs to be held until CI is back online and we can run everything again.

The results from 11 hours ago seem pretty good to me. Is there a worry that they are a false positive?
