### PR TITLE
optimizer: fix #42246, set `ssaflags` correctly when inserting coverage statements

### LINKED ISSUE #42246: noinline/inline macros broken by code-coverage
```
$ ./julia --code-coverage=foo.info -q

julia> g() = @noinline IOBuffer("a")
g (generic function with 1 method)
                                                                                                 
julia> @code_typed g()
CodeInfo(
     @ REPL[1]:1 within `g`
1 ──       $(Expr(:code_coverage_effect))::Nothing
│   ┌ @ strings/io.jl:302 within `GenericIOBuffer`
│   │       $(Expr(:code_coverage_effect))::Nothing
│   │┌ @ strings/string.jl:85 within `unsafe_wrap`
│   ││ %3  = $(Expr(:foreigncall, :(:jl_string_to_array), Ref{Vector{UInt8}}, svec(Any), 0, :(:ccall), "a"))::Vector{UInt8}
```
expected:
```
julia> @code_typed g()
CodeInfo(
    @ REPL[9]:1 within `g`
1 ─ %1 = invoke Main.IOBuffer("a"::String)::IOBuffer
└──      return %1
) => IOBuffer
```

### LINKED ISSUE #42258: optimizer: `ssaflags` can be strange after optimization
It seems that `(ci::CodeInfo).ssaflags` is sometimes processed badly during optimization
(and it will confuse [the inlining cost model](https://github.com/JuliaLang/julia/blob/3794f9a3071f4e80fa58af9891251e91856aa837/base/compiler/optimize.jl#L543)).

Given the following definition of `Core.Compiler.setindex!(::Core.Compiler.UseRef, ::Any)`:
https://github.com/JuliaLang/julia/blob/3794f9a3071f4e80fa58af9891251e91856aa837/base/compiler/ssair/ir.jl#L415-L455

I found `ssaflags` is set correctly before optimization (every "throw block" gets marked with `IR_FLAG_THROW_BLOCK = 0x01 << 3`:
```julia
julia> function show_with_flags(io::IO, @nospecialize x)
           src, rt = x
           buf = IOBuffer()
           show(IOContext(buf, :color => true), src => rt)
           s = String(take!(buf))
           for (i, line) in enumerate(split(s, '\n'))
               i -= 1
               if checkbounds(Bool, src.code, i)
                   println(io, repr(src.ssaflags[i]), " ", line)
               else
                   println(line)
               end
           end
       end;

julia> show_with_flags(@nospecialize x) = show_with_flags(stdout::IO, x);

julia> code_typed(Core.Compiler.setindex!, (Core.Compiler.UseRef, Core.Compiler.NewSSAValue);
                  optimize=false) |> 
                  only |>
                  show_with_flags
CodeInfo(
0x00 1 ──        nothing::Core.Const(nothing)
0x00 │           Core.NewvarNode(:(rhs))::Any
0x00 │           (stmt = Core.Compiler.getproperty(x, :stmt))::Any
0x00 │    %4   = (stmt isa Core.Compiler.Expr)::Bool
0x00 └───        goto #12 if not %4
...
0x00 │           Core.Compiler.setindex!(%137, v, %138)::Any
0x00 └───        goto #51
0x08 50 ─ %141 = Core.Compiler.BoundsError()::Any
0x08 └───        Core.Compiler.throw(%141)::Union{}
0x00 51 ┄        return x
) => Union{Core.Compiler.NewSSAValue, Core.Compiler.UseRef}

julia> # extracts 0x08 statments
       let (ci, rt) = code_typed(Core.Compiler.setindex!, (Core.Compiler.UseRef, Core.Compiler.NewSSAValue);
                  optimize=false) |> 
                  only
           filter(collect(zip(ci.ssaflags, ci.code))) do (flag, _)
               (flag & Core.Compiler.IR_FLAG_THROW_BLOCK) ≠ 0
           end
       end
24-element Vector{Tuple{UInt8, Any}}:
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%20)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%31)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%43)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%56)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%68)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%80)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%92)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%106)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%114)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%127)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%135)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%141)))
```

But after optimization some `0x08` statements no longer correspond to "throw block", and rather they're scattered around arbitrary places:
```julia
julia> code_typed(Core.Compiler.setindex!, (Core.Compiler.UseRef, Core.Compiler.NewSSAValue);
                  optimize=true) |> 
                  only |>
                  show_with_flags
CodeInfo(
0x10 1 ── %1   = Core.Compiler.getproperty(x, :stmt)::Any
0x10 │    %2   = (%1 isa Core.Compiler.Expr)::Bool
0x00 └───        goto #25 if not %2
0x10 2 ── %4   = π (%1, Expr)
0x10 │    %5   = Core.Compiler.getproperty(%4, :head)::Symbol
...
0x00 └───        unreachable
0x00 67 ─ %221 = Core.Compiler.BoundsError()::Any
0x00 │           Core.Compiler.throw(%221)::Union{}
0x00 └───        unreachable
0x00 68 ┄        return x
) => Union{Core.Compiler.NewSSAValue, Core.Compiler.UseRef}

julia> # extracts 0x08 statments
       let (ci, rt) = code_typed(Core.Compiler.setindex!, (Core.Compiler.UseRef, Core.Compiler.NewSSAValue);
                  optimize=true) |> 
                  only
           filter(collect(zip(ci.ssaflags, ci.code))) do (flag, _)
               (flag & Core.Compiler.IR_FLAG_THROW_BLOCK) ≠ 0
           end
       end
22-element Vector{Tuple{UInt8, Any}}:
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%50)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%66)))
 (0x08, :(goto %80 if not %75))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x18, nothing)
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(goto %108 if not %102))
 (0x18, nothing)
 (0x08, :(goto %120 if not %114))
 (0x18, :(Core.Compiler.getproperty(_2, :op)))
 (0x18, :(Core.Compiler.getproperty(_2, :op)))
 (0x18, :(Core.Compiler.getproperty(%140, :values)))
 (0x18, :(Core.Compiler.getproperty(%148, :values)))
 (0x18, :(Core.Compiler.getproperty(_2, :op)))
 (0x08, :(goto %221 if not %179))
 (0x18, :(Core.Compiler.getproperty(_2, :op)))
 (0x08, :(unreachable))
 (0x18, :(Core.Compiler.getproperty(%190, :values)))
 (0x08, :(Core.Compiler.BoundsError()))
 (0x08, :(Core.Compiler.throw(%218)))
```

There are several points where new statement can be inserted in the optimization, and AFAIU we basically need to check if each construction of `NewInstruction` is valid and correctly inherits the statement flags:
https://github.com/JuliaLang/julia/blob/3794f9a3071f4e80fa58af9891251e91856aa837/base/compiler/ssair/ir.jl#L154-L175

This issue might also confuse `propagate_inbounds` and callsite inlining stuff, because they also use `ssaflags` set before optimization.

As a final target, the following case should pass once this issue gets resolved:
```julia
let 
    ci, rt = code_typed(Core.Compiler.setindex!, (Core.Compiler.UseRef, Core.Compiler.NewSSAValue);
               optimize=true) |> 
               only
    idx = filter(1:length(ci.code)) do i
        stmt = ci.code[i]
        if Meta.isexpr(stmt, :call)
            t = Core.Compiler.argextype(stmt.args[1], ci, Any[])
            ft = Core.Compiler.widenconst(t)
            return ft === typeof(BoundsError) || ft === typeof(throw)
        end
        false
    end
    @test all(ci.ssaflags[idx]) do flag
        flag & Core.Compiler.IR_FLAG_THROW_BLOCK ≠ 0
    end
end
```

### PR DESCRIPTION
**Pull request by aviatesk**
It seems that this change still doesn't resolve #42258 though.

### CODE REVIEW

File: test/compiler/inline.jl [hunk 1]
```diff
@@ -650,3 +650,32 @@ let
         @test ninlined == length(code)
     end
 end
+
+let # https://github.com/JuliaLang/julia/issues/42246
+    local back = pwd()
+    try
+        @test mktempdir() do dir
+            cd(dir)
```
Comment (KristofferC) [inline test/compiler/inline.jl:658]: Possible to use `cd(dir) do...` here?

Comment (aviatesk) [reply test/compiler/inline.jl:658]: woa, very nice !
