### PR TITLE
Fix `show` for `MethodList` when methods are from another module

### LINKED ISSUE #49382: Error when showing method list
Reproducer:
```
julia> module A
           abstract type B end
       end;

julia> (::Type{A.B})() = 1;

julia> methods(A.B)
# 1 method for type constructor:Error showing value of type Base.MethodList:
ERROR: "B" is not defined in module Main
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] which
    @ ./reflection.jl:1643 [inlined]
  [3] show_method_table(io::IOContext{Base.TTY}, ms::Base.MethodList, max::Int64, header::Bool)
    @ Base ./methodshow.jl:303
  [4] show_method_table
    @ ./methodshow.jl:289 [inlined]
  [5] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, ms::Base.MethodList)
    @ Base ./methodshow.jl:349
```
Note that it does not happen if ` (::Type{A.B})() = 1` is inside `module A ... end`.

### LINKED ISSUE #49403: show_method_table error
#45069 seems to assume that `mt[1]` value is meaningful (though it seems probably never true), and crashes if is isn't
```
julia> @time methods(Base.Broadcast.BroadcastStyle, Tuple{Type{<:Any}})
  0.004502 seconds (2.26 k allocations: 75.891 KiB)
# 45 methods for type constructor:Error showing value of type Base.MethodList:
ERROR: "BroadcastStyle" is not defined in module RecursiveArrayTools
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] which(m::Module, s::Symbol)
    @ Base ./reflection.jl:1632
  [3] show_method_table(io::IOContext{Base.TTY}, ms::Base.MethodList, max::Int64, header::Bool)
    @ Base ./methodshow.jl:303
  [4] show_method_table
    @ ./methodshow.jl:289 [inlined]
  [5] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, ms::Base.MethodList)
    @ Base ./methodshow.jl:349
  [6] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:271
  [7] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:552
  [8] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:259
  [9] display(d::REPL.REPLDisplay, x::Any)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:276
 [10] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [11] #invokelatest#2
    @ ./essentials.jl:863 [inlined]
 [12] invokelatest
    @ ./essentials.jl:860 [inlined]
 [13] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:300
 [14] (::REPL.var"#57#58"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:282
 [15] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:552
 [16] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:280
 [17] (::REPL.var"#do_respond#80"{Bool, Bool, REPL.var"#93#103"{REPL.LineEditREPL, REPL.REPLHistoryProvider}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:894
 [18] #invokelatest#2
    @ ./essentials.jl:863 [inlined]
 [19] invokelatest
    @ ./essentials.jl:860 [inlined]
 [20] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2648
 [21] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1295
 [22] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:514
```

### LINKED ISSUE #52043: `methods(Core.OpaqueClosure)` errors
```julia
julia> methods(Core.OpaqueClosure)
# 2 methods for type constructor:Error showing value of type Base.MethodList:
ERROR: "OpaqueClosure" is not defined in module Base.Experimental
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] which
    @ ./reflection.jl:1924 [inlined]
  [3] show_method_table(io::IOContext{Base.TTY}, ms::Base.MethodList, max::Int64, header::Bool)
    @ Base ./methodshow.jl:304
  [4] show_method_table
    @ Base ./methodshow.jl:290 [inlined]
  [5] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, ms::Base.MethodList)
    @ Base ./methodshow.jl:350
  [6] (::REPL.var"#57#58"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:288
  [7] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:584
  [8] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:274
  [9] display
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:293 [inlined]
 [10] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [11] #invokelatest#2
    @ ./essentials.jl:929 [inlined]
 [12] invokelatest
    @ ./essentials.jl:926 [inlined]
 [13] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:330
 [14] (::REPL.var"#59#60"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:299
 [15] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:584
 [16] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:297
 [17] (::REPL.var"#do_respond#82"{Bool, Bool, REPL.var"#95#107"{…}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:926
 [18] #invokelatest#2
    @ Base ./essentials.jl:929 [inlined]
 [19] invokelatest
    @ Base ./essentials.jl:926 [inlined]
 [20] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2722
 [21] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1352
 [22] (::REPL.var"#64#70"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:401
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by ararslan**
When a type is defined in one module but its constructor's methods are defined elsewhere, `show_method_table` errors due to an incorrect lookup of the defining module used to determine colors for printing. In particular, the code had been assuming that the type is defined (in the sense of `isdefined`) in the module in which its constructor's first method (in the sense of `first(methods())`) is defined, which isn't always true.

To fix this, we can look through the available methods and choose the first in which the type is defined in the method's module, falling back to the method table's module otherwise. I'm not sure that this is necessarily the best way to fix the issue but it does fix it.

Fixes #49382
Fixes #49403
Fixes #52043

### CODE REVIEW

File: base/methodshow.jl [hunk 1]
```diff
@@ -301,7 +301,8 @@ function show_method_table(io::IO, ms::MethodList, max::Int=-1, header::Bool=tru
     last_shown_line_infos === nothing || empty!(last_shown_line_infos)
 
     modul = if mt === _TYPE_NAME.mt && length(ms) > 0 # type constructor
-            which(ms.ms[1].module, ms.ms[1].name)
+            i = findfirst(m -> isdefined(m.module, m.name), ms.ms)
+            i === nothing ? mt.module : which(ms.ms[i].module, ms.ms[i].name)
```
Comment (aviatesk) [inline base/methodshow.jl:305]:
```suggestion
            sig = Base.unwrap_unionall(ms[1].sig)::DataType # Tuple{Type{...}}
            ((sig.parameters[1]::DataType).parameters[1]::DataType).name.module
```
This seems very hacky, but would be more correct?

Comment (vtjnash) [reply base/methodshow.jl:305]: I would think most of those type asserts are invalid, because the general assumption here (that method tables are owned by modules) is invalid itself

Comment (vtjnash) [reply base/methodshow.jl:305]: Looking over the code a bit closer, it looks like it wants to check it the method itself is being defined on a function / type in the same module or in a dependency. But that needs to be a per-method query, and is not valid to derive from the method table

Comment (ararslan) [reply base/methodshow.jl:305]: I guess the difficulty is defining what "same module" means here since you need to select a starting point for comparison in order to cycle the colors. @aviatesk's suggestion does seem better than what I've implemented, except it uses `ms[1]` as on current master, the defining module of which isn't necessarily meaningful. But it at least shouldn't error since it isn't using `which` as on master.

Comment (ararslan) [reply base/methodshow.jl:305]: Combining part of @aviatesk's suggestion with part of what's currently implemented in this PR:
```suggestion
            i = something(findfirst(m -> isdefined(m.module, m.name), ms.ms), 1)
            parentmodule(fieldtype(unwrap_unionall(ms[i].sig), 1).parameters[1])
```
Does this seem reasonable, @vtjnash?

Comment (vtjnash) [reply base/methodshow.jl:305]: It is a bit better. The more generally correct version of this needs to be done for each method however, first attempting to derive the method table it is being added to, then deriving if it is the same as the method itself. Something like this:
```suggestion
mmt = get_methodtable(meth)
modulecolor = if mmt.module === parentmodule(meth)
        nothing
    else
        # mmt is only particularly relevant for external method tables. Since the primary method table is shared, we now need to distinguish "primary" methods by trying to check if there is a primary DataType to identify it with
        # c.f. how `jl_method_def` would derive this same information (for the name)
        ft = argument_datatype((unwrap_unionall(meth.sig)::DataType).parameters[1]) # try to get the type associated with the first argument
        isType(ft) && (ft = argument_datatype(ft.parameters[1])) # if the ft is `Type`, try to unwrap it again
        if ft === nothing || parentmodule(meth) === parentmodule(ft) !== Core
            nothing
        else
            # get color for meth
        end
end
...
```

n.b. In C, the first `ft` computation is called  `jl_nth_argument_datatype`, but it seems we don't export that to Julia

**Review by aviatesk — APPROVED** [review]
LGTM. I've looked into the discussion and it seems reasonable to me.

**Review by vtjnash — APPROVED** [review]
Why would the method table lookup ever return nothing?

**Comment by ararslan** [comment]
> Why would the method table lookup ever return nothing?

I wondered the same, turns out it does so for builtins. This is actually handled explicitly in a couple of places, e.g.: https://github.com/JuliaLang/julia/blob/9443c761871c4db9c3213a1e01804286292c3f4d/base/compiler/utilities.jl#L157-L158

Method table lookup uses the first item of the method's signature, but the method for a builtin has signature `Tuple`, which causes `nth_methodtable` to return `nothing`.
