### PR TITLE
fixes to generalized zeta function zeta(s, z)

### LINKED ISSUE #7228: extend hurwitz zeta(s, z) to real(s) < 1
Currently, the `zeta(s, z)` function is restricted to `real(s) > 1`.   This could probably be relaxed to `real(s) > 0.5` without changing the code, but  to extend to `real(s) < 0.5` looks like it will require a different approximation technique.

I've been looking around, and so far the most promising technique is based on exploiting the functional equation derived by Hurwitz and reviewed in [this 2001 paper by Knopp and Robbins](http://www.ams.org/proc/2001-129-07/S0002-9939-01-06033-6/S0002-9939-01-06033-6.pdf):
eq1
where `F` is the periodized zeta function:
eq2
Unfortunately, that means you need to come up with a method to compute `F(s,a)` (at least for `real(s) > 0.5`, and I haven't found anything already worked out online.   In principle, it should be possible to derive an asymptotic expansion using e.g. the [Euler–Maclaurin method](http://en.wikipedia.org/wiki/Euler%E2%80%93Maclaurin_formula#Asymptotic_expansion_of_sums), along with a shift recurrence for `F(s,a+1)`.

It looks doable, but a fair amount of work, so I'm leaving this as a to-do issue until a real need comes up.  The [Scipy zeta](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.zeta.html) function (a wrapper around the Cephes zeta) only supports real arguments with `s > 1`, and I don't see any complaints about this, so maybe it isn't a big need.

### PR DESCRIPTION
**Pull request by stevengj**
This fixes #7228, extending the generalized zeta function to arbitrary complex s ≠ 1.

Also, I changed the definition of the generalized zeta function slightly, which is why I'm labeling this as a "breaking" change although the change probably doesn't affect anyone.

Before, it was the Hurwitz zeta function, equivalent to [HurwitzZeta](http://reference.wolfram.com/language/ref/HurwitzZeta.html) in Mathematica.  My new `zeta(s,z)` is, instead, equivalent to the [Zeta](http://reference.wolfram.com/language/ref/Zeta.html) function in Mathematica, which chooses a different branch cut for the exponentiation when `real(z) < 0` compared to Hurwitz.   In particular, there are two advantages to the `Zeta[s, z]` definition:
- It is more Julian, because it is more type-stable: it gives a real output for real inputs `s` and `z`, whereas the Hurwitz zeta is complex for real inputs when `z < 0` and `s` is not an integer.
- It strictly expands the domain.  In a similar vein, nonpositive-integer `z` values are now handled by dropping those (divergent terms) from the sum in the definition.
- It is equivalent to the Hurwitz zeta function when `real(z) > 0`, which is probably the case that most people care about anyway.  (This is the case used for the polygamma function.)

### CODE REVIEW

File: base/special/gamma.jl [hunk 1]
```diff
@@ -277,29 +280,34 @@ function zeta(s::Union{Int,Float64,Complex{Float64}},
...
+                ζₒ= ζ
+                ζ += pow_oftype(ζ, minus_z - ν, minus_s)
+                ζ == ζₒ && break # prevent long loop for large -x > 0
+                                 # FIXME: still slow for small m, large Im(z)
+            end
+        else # x ≥ 0 && z != 0
+            ζ += pow_oftype(ζ, z, minus_s)
         end
-        for ν = max(1,1-nx):n-1
+        for ν in (real(s) > 0 ? (max(1,1-nx):n-1) : (n-1:-1:max(1,1-nx)))
```
Comment (stevengj) [inline base/special/gamma.jl]: The code is compact this way.  I'm not sure whether it is a bad idea for performance to have the loop range be determined by a conditional like this, vs. having two versions of the loop (with the same body, ugh)?  @JeffBezanson ?

Comment (yuyichao) [inline base/special/gamma.jl]: maybe at least make it type stable?

File: base/docs/helpdb/Base.jl [hunk 2]
```diff
@@ -9595,8 +9595,12 @@ zeta(s)
...
     zeta(s, z)
 
-Hurwitz zeta function ``\\zeta(s, z)``.  (This is equivalent to the Riemann zeta function
-``\\zeta(s)`` for the case of `z=1`.)
+Generalized zeta function ``\\zeta(s, z)``, defined
+by the sum ``\\sum_{k=0}^\\infty ((k+z)^2)^{-s/2}``, where
+any term with ``k+z=0`` is excluded.  For ``\\Re z > 0``,
+this definition is equivalent to the Hurwitz zeta function
+``\\sum_{k=0}^\\infty (k+z)^{-s}``.   For ``z=1``, it yields
+the Riemann zeta function ``\\zeta(s)``.
```
Comment (tkelman) [inline base/docs/helpdb/Base.jl]: run genstdlib and commit the update

File: base/special/gamma.jl (hunk 1 above)
Comment (stevengj) [inline base/special/gamma.jl]: Looks like it kills type inference, especially because I have two different iterator types.  #15946.   I will update the patch to duplicate the loops.

**Comment by stevengj** [comment]
Since @StefanKarpinski gave the thumbs up, and I addressed the problems in the comments, is this good to merge?
