### PR TITLE
Couple of tuple speed-ups and fixes

### LINKED ISSUE #20718: Too many allocations when binary dot operators for tuples are used multiple times in a single line
When binary dot operators (e.g., `.+`, `.-`, `.*`) for _tuples_ are used multiple times in a single line, too many allocations occur, and the code runs very slow as a result.  For example,
```julia
julia> VERSION
v"0.6.0-dev.2888"

julia> using BenchmarkTools

julia> t1 = (1,2); t2 = (3,4); t3 = (5,6);

julia> @benchmark $t1 .+ $t2
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  mean time:        1.845 ns (0.00% GC)

julia> @benchmark $t1 .+ $t2 .+ $t3
BenchmarkTools.Trial:
  memory estimate:  1.11 KiB
  allocs estimate:  48
  mean time:        12.008 μs (2.66% GC)
```

In contrast, binary dot operators for _arrays_ do not suffer from such an increased number of allocations when used multiple times in a single line:
```julia
julia> a1 = [1,2]; a2 = [3,4]; a3 = [5,6];

julia> @benchmark $a1 .+ $a2
BenchmarkTools.Trial:
  memory estimate:  96 bytes
  allocs estimate:  1
  mean time:        53.404 ns (12.80% GC)

julia> @benchmark $a1 .+ $a2 .+ $a3
BenchmarkTools.Trial:
  memory estimate:  96 bytes
  allocs estimate:  1
  mean time:        62.715 ns (10.94% GC)
```

### PR DESCRIPTION
**Pull request by p-zubieta**
Should fix #20718

### CODE REVIEW

File: base/tuple.jl [hunk 1]
```diff
@@ -160,7 +160,8 @@ heads(t::Tuple, ts::Tuple...) = (t[1], heads(ts...)...)
 tails() = ()
 tails(t::Tuple, ts::Tuple...) = (tail(t), tails(ts...)...)
 map(f, ::Tuple{}, ts::Tuple...) = ()
```
Comment (Sacha0) [inline base/tuple.jl]: Tangentially, this method seems incongruous with the spirit of `map`?
```julia
julia> map(+, (), (1,2))
()

julia> map(+, [], [1,2])
ERROR: DimensionMismatch("dimensions must match")
Stacktrace:
 [1] promote_shape(::Tuple{Base.OneTo{Int64}}, ::Tuple{Base.OneTo{Int64}}) at ./indices.jl:79
 [2] _array_for(::Type{Any}, ::Base.Iterators.Zip2{Array{Any,1},Array{Int64,1}}, ::Base.HasShape) at ./array.jl:406
 [3] collect(::Base.Generator{Base.Iterators.Zip2{Array{Any,1},Array{Int64,1}},Base.##3#4{Base.#+}}) at ./array.jl:416
 [4] map(::Function, ::Array{Any,1}, ::Array{Int64,1}) at ./abstractarray.jl:1888
```

File: base/tuple.jl [hunk 2]
```diff
@@ -160,7 +160,8 @@ heads(t::Tuple, ts::Tuple...) = (t[1], heads(ts...)...)
...
-map(f, t1::Tuple, t2::Tuple, ts::Tuple...) = (f(heads(t1, t2, ts...)...), map(f, tails(t1, t2, ts...)...)...)
+map(f, t1::Tuple, t2::Tuple, ts::Tuple...) = (@_inline_meta;
```
Comment (Sacha0) [inline base/tuple.jl]: Does this definition not result in arbitrarily deep inlining in the same manner that [the two argument form](https://github.com/JuliaLang/julia/blob/474d05d0bef8bd2fad984db0223162de922f0315/base/tuple.jl#L145) does without [this additional definition]( https://github.com/JuliaLang/julia/blob/474d05d0bef8bd2fad984db0223162de922f0315/base/tuple.jl#L149) that limits inlining?

Comment (pabloferz) [inline base/tuple.jl]: You're right, I looked at this backwards, is `heads` and `tails` what should be fine to inline. I'll try another solution.

**Comment by pabloferz** [comment]
Updated to avoid code blowup for large tuples.

This should also fix #20723 now. Unlike `map(+, [], [1,2])`, `map(+, [], [1,2])` would throw `ERROR: BoundsError: attempt to access ()`. Should I make it throw `DimensionMismatch("dimensions must match")` also?

File: base/tuple.jl [hunk 3]
```diff
@@ -132,7 +132,7 @@ All16{T,N} = Tuple{T,T,T,T,T,T,T,T,
                    T,T,T,T,T,T,T,T,Vararg{T,N}}
 function map(f, t::Any16)
     n = length(t)
-    A = Array{Any}(n)
+    A = Array{Any,1}(n)
```
Comment (Sacha0) [inline base/tuple.jl]: Perhaps `Vector`?

File: base/tuple.jl [hunk 4]
```diff
@@ -148,19 +148,22 @@ function map(f, t::Tuple, s::Tuple)
 end
 function map(f, t::Any16, s::Any16)
     n = length(t)
-    A = Array{Any}(n)
+    A = Array{Any,1}(n)
```
Comment (Sacha0) [inline base/tuple.jl]: Likewise here, perhaps `Vector`?

File: base/tuple.jl (hunk 3 above)
Comment (pabloferz) [inline base/tuple.jl]: Can't use `Vector` here because of bootstrapping.

File: base/tuple.jl [hunk 5]
```diff
@@ -148,19 +148,22 @@ function map(f, t::Tuple, s::Tuple)
...
 heads() = ()
-heads(t::Tuple, ts::Tuple...) = (t[1], heads(ts...)...)
+heads(t::Tuple, ts::Tuple...) = (@_inline_meta; (t[1], heads(ts...)...))
 tails() = ()
-tails(t::Tuple, ts::Tuple...) = (tail(t), tails(ts...)...)
-map(f, ::Tuple{}, ts::Tuple...) = ()
-map(f, t1::Tuple, t2::Tuple, ts::Tuple...) = (f(heads(t1, t2, ts...)...), map(f, tails(t1, t2, ts...)...)...)
+tails(t::Tuple, ts::Tuple...) = (@_inline_meta; (tail(t), tails(ts...)...))
+map(f, ::Tuple{}...) = ()
+map(f, t::Tuple, ts::Tuple...) = (@_inline_meta;
```
Comment (Sacha0) [inline base/tuple.jl]: Do these definitions exceed the line-length recommendation? If not, perhaps condense these definitions to single lines?

Comment (pabloferz) [inline base/tuple.jl]: It is 92 characters, right? If so, then indeed this exceeds the line-length recommendation.

File: base/tuple.jl [hunk 6]
```diff
@@ -20,7 +20,7 @@ endof(t::Tuple) = length(t)
 size(t::Tuple, d) = d==1 ? length(t) : throw(ArgumentError("invalid tuple dimension $d"))
 getindex(t::Tuple, i::Int) = getfield(t, i)
 getindex(t::Tuple, i::Real) = getfield(t, convert(Int, i))
-getindex(t::Tuple, r::AbstractArray{<:Any,1}) = tuple([t[ri] for ri in r]...)
+getindex(t::Tuple, r::AbstractArray{<:Any,1}) = (n = length(eachindex(r)); ntuple(i->t[r[i]], n))
```
Comment (Sacha0) [inline base/tuple.jl]: Could you explain this change's purpose? Could indexing `r` with indices `1:n` (rather than iterating over `r`'s elements, or indexing `r` more genernically) be an issue? If not, why `length(eachindex(r))` rather than simply `length(r)`? Does using `ntuple` here not potentially hurt inference?

File: base/tuple.jl (hunk 5 above)
Comment (Sacha0) [inline base/tuple.jl]: Yes. I see the first definition exceeds the limit by a few characters though the second does not; I assume you split the second definition for consistency, so cheers :).

File: base/tuple.jl (hunk 6 above)
Comment (pabloferz) [inline base/tuple.jl]: > Could indexing r with indices 1:n be an issue?

I feel like we are slowly moving to support non traditional indexing, to support things like, e.g., `OffsetArrays`. That's why I wrote it like this.

> Does using ntuple here not potentially hurt inference?

This is already non-inferable so it doesn't hurt changing it to make it faster.

**Comment by Sacha0** [comment]
> I feel like we are slowly moving to support non traditional indexing, to handle things like, e.g., OffsetArrays. That's why I wrote it like this.

Exactly :). The proposed definition indexes `r` from `1:n`, as `i` iterates over `1:n` in `ntuple`. So if indexing `r` from `1:n` is not correct, the proposed definition will not be correct.

> This is already non-inferable so it doesn't hurt changing it to make it faster.

Consider
```julia
julia> foo(t::Tuple, r::AbstractArray{<:Any,1}) = tuple([t[ri] for ri in r]...)
foo (generic function with 1 method)

julia> bar(t::Tuple, r::AbstractArray{<:Any,1}) = (n = length(eachindex(r)); ntuple(i->t[r[i]], n))
bar (generic function with 1 method)

julia> @code_warntype foo((1,2,3), [1])
Variables:
  #self#::#foo
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  #1::##1#2{Tuple{Int64,Int64,Int64}}

Body:
  begin
      #1::##1#2{Tuple{Int64,Int64,Int64}} = $(Expr(:new, :($(QuoteNode(##1#2{Tuple{Int64,Int64,Int64}}))), :(t)))
      SSAValue(0) = #1::##1#2{Tuple{Int64,Int64,Int64}}
      SSAValue(1) = $(Expr(:new, :($(QuoteNode(Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}))), SSAValue(0), :(r)))
      SSAValue(2) = $(Expr(:invoke, MethodInstance for collect(::Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}), :(Base.collect), SSAValue(1)))
      return (Core._apply)(Main.tuple, SSAValue(2))::Tuple{Vararg{Int64,N} where N}
  end::julia> foo(t::Tuple, r::AbstractArray{<:Any,1}) = tuple([t[ri] for ri in r]...)
foo (generic function with 1 method)

julia> bar(t::Tuple, r::AbstractArray{<:Any,1}) = (n = length(eachindex(r)); ntuple(i->t[r[i]], n))
bar (generic function with 1 method)

julia> @code_warntype foo((1,2,3), [1])
Variables:
  #self#::#foo
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  #1::##1#2{Tuple{Int64,Int64,Int64}}

Body:
  begin
      #1::##1#2{Tuple{Int64,Int64,Int64}} = $(Expr(:new, :($(QuoteNode(##1#2{Tuple{Int64,Int64,Int64}}))), :(t)))
      SSAValue(0) = #1::##1#2{Tuple{Int64,Int64,Int64}}
      SSAValue(1) = $(Expr(:new, :($(QuoteNode(Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}))), SSAValue(0), :(r)))
      SSAValue(2) = $(Expr(:invoke, MethodInstance for collect(::Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}), :(Base.collect), SSAValue(1)))
      return (Core._apply)(Main.tuple, SSAValue(2))::Tuple{Vararg{Int64,N} where N}
  end::Tuple{Vararg{Int64,N} where N}

julia> @code_warntype bar((1,2,3), [1])
Variables:
  #self#::#bar
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  n::Int64
  #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location abstractarray.jl eachindex 744
      # meta: location abstractarray.jl indices1 63
      # meta: location abstractarray.jl indices 56
      SSAValue(3) = (Base.arraysize)(r::Array{Int64,1}, 1)::Int64
      # meta: location tuple.jl map 124
      SSAValue(2) = SSAValue(3)
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      n::Int64 = (Core.typeassert)((Base.select_value)((Base.slt_int)(SSAValue(2), 0)::Bool, 0, SSAValue(2))::Int64, Int64)::Int64
      #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}} = $(Expr(:new, :($(QuoteNode(##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}))), :(t), :(r)))
      SSAValue(0) = #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}
      return $(Expr(:invoke, MethodInstance for ntuple(::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}, ::Int64), :(Main.ntuple), SSAValue(0), :(n)))
  end::Tuple

julia>

julia> @code_warntype bar((1,2,3), [1])
Variables:
  #self#::#bar
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  n::Int64
  #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location abstractarray.jl eachindex 744
      # meta: location abstractarray.jl indices1 63
      # meta: location abstractarray.jl indices 56
      SSAValue(3) = (Base.arraysize)(r::Array{Int64,1}, 1)::Int64
      # meta: location tuple.jl map 124
      SSAValue(2) = SSAValue(3)
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      n::Int64 = (Core.typeassert)((Base.select_value)((Base.slt_int)(SSAValue(2), 0)::Bool, 0, SSAValue(2))::Int64, Int64)::Int64
      #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}} = $(Expr(:new, :($(QuoteNode(##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}))), :(t), :(r)))
      SSAValue(0) = #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}
      return $(Expr(:invoke, MethodInstance for ntuple(::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}, ::Int64), :(Main.ntuple), SSAValue(0), :(n)))
  end::Tuple
```
The existing definition yields `Tuple{Vararg{Int64,N} where N}` whereas the propose definition yields only `Tuple`; some information is lost?

File: base/tuple.jl (hunk 6 above)
Comment (Sacha0) [inline base/tuple.jl]: > I feel like we are slowly moving to support non traditional indexing, to handle things like, e.g., OffsetArrays. That's why I wrote it like this.

Exactly :). The proposed definition indexes `r` from `1:n`, as `i` iterates over `1:n` in `ntuple`. So if indexing `r` from `1:n` is not correct, the proposed definition will not be correct.

> This is already non-inferable so it doesn't hurt changing it to make it faster.

Consider
```julia
julia> foo(t::Tuple, r::AbstractArray{<:Any,1}) = tuple([t[ri] for ri in r]...)
foo (generic function with 1 method)

julia> bar(t::Tuple, r::AbstractArray{<:Any,1}) = (n = length(eachindex(r)); ntuple(i->t[r[i]], n))
bar (generic function with 1 method)

julia> @code_warntype foo((1,2,3), [1])
Variables:
  #self#::#foo
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  #1::##1#2{Tuple{Int64,Int64,Int64}}

Body:
  begin
      #1::##1#2{Tuple{Int64,Int64,Int64}} = $(Expr(:new, :($(QuoteNode(##1#2{Tuple{Int64,Int64,Int64}}))), :(t)))
      SSAValue(0) = #1::##1#2{Tuple{Int64,Int64,Int64}}
      SSAValue(1) = $(Expr(:new, :($(QuoteNode(Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}))), SSAValue(0), :(r)))
      SSAValue(2) = $(Expr(:invoke, MethodInstance for collect(::Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}), :(Base.collect), SSAValue(1)))
      return (Core._apply)(Main.tuple, SSAValue(2))::Tuple{Vararg{Int64,N} where N}
  end::julia> foo(t::Tuple, r::AbstractArray{<:Any,1}) = tuple([t[ri] for ri in r]...)
foo (generic function with 1 method)

julia> bar(t::Tuple, r::AbstractArray{<:Any,1}) = (n = length(eachindex(r)); ntuple(i->t[r[i]], n))
bar (generic function with 1 method)

julia> @code_warntype foo((1,2,3), [1])
Variables:
  #self#::#foo
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  #1::##1#2{Tuple{Int64,Int64,Int64}}

Body:
  begin
      #1::##1#2{Tuple{Int64,Int64,Int64}} = $(Expr(:new, :($(QuoteNode(##1#2{Tuple{Int64,Int64,Int64}}))), :(t)))
      SSAValue(0) = #1::##1#2{Tuple{Int64,Int64,Int64}}
      SSAValue(1) = $(Expr(:new, :($(QuoteNode(Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}))), SSAValue(0), :(r)))
      SSAValue(2) = $(Expr(:invoke, MethodInstance for collect(::Base.Generator{Array{Int64,1},##1#2{Tuple{Int64,Int64,Int64}}}), :(Base.collect), SSAValue(1)))
      return (Core._apply)(Main.tuple, SSAValue(2))::Tuple{Vararg{Int64,N} where N}
  end::Tuple{Vararg{Int64,N} where N}

julia> @code_warntype bar((1,2,3), [1])
Variables:
  #self#::#bar
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  n::Int64
  #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location abstractarray.jl eachindex 744
      # meta: location abstractarray.jl indices1 63
      # meta: location abstractarray.jl indices 56
      SSAValue(3) = (Base.arraysize)(r::Array{Int64,1}, 1)::Int64
      # meta: location tuple.jl map 124
      SSAValue(2) = SSAValue(3)
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      n::Int64 = (Core.typeassert)((Base.select_value)((Base.slt_int)(SSAValue(2), 0)::Bool, 0, SSAValue(2))::Int64, Int64)::Int64
      #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}} = $(Expr(:new, :($(QuoteNode(##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}))), :(t), :(r)))
      SSAValue(0) = #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}
      return $(Expr(:invoke, MethodInstance for ntuple(::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}, ::Int64), :(Main.ntuple), SSAValue(0), :(n)))
  end::Tuple

julia>

julia> @code_warntype bar((1,2,3), [1])
Variables:
  #self#::#bar
  t::Tuple{Int64,Int64,Int64}
  r::Array{Int64,1}
  n::Int64
  #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location abstractarray.jl eachindex 744
      # meta: location abstractarray.jl indices1 63
      # meta: location abstractarray.jl indices 56
      SSAValue(3) = (Base.arraysize)(r::Array{Int64,1}, 1)::Int64
      # meta: location tuple.jl map 124
      SSAValue(2) = SSAValue(3)
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      n::Int64 = (Core.typeassert)((Base.select_value)((Base.slt_int)(SSAValue(2), 0)::Bool, 0, SSAValue(2))::Int64, Int64)::Int64
      #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}} = $(Expr(:new, :($(QuoteNode(##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}))), :(t), :(r)))
      SSAValue(0) = #3::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}
      return $(Expr(:invoke, MethodInstance for ntuple(::##3#4{Tuple{Int64,Int64,Int64},Array{Int64,1}}, ::Int64), :(Main.ntuple), SSAValue(0), :(n)))
  end::Tuple
```
The existing definition yields `Tuple{Vararg{Int64,N} where N}` whereas the propose definition yields only `Tuple`; some information is lost?

Comment (pabloferz) [inline base/tuple.jl]: Somehow I forgot that `eachindex

**Comment by pabloferz** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

File: base/tuple.jl (hunk 5 above)
Comment (vtjnash) [inline base/tuple.jl]: these should be written as long-form methods if they need to split across multiple lines

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20720#issuecomment-281564098) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/baae3a0e1e860ebeef21db308c8f0f1f04e98fe9/9751350_vs_35ce0fd/report.md). cc @jrevels

**Comment by felixrehren** [comment]
Those `sqrtm` tests seem very noisy. I can't think how these changes to tuples would have affected them. cc @jrevels

File: base/tuple.jl [hunk 7]
```diff
@@ -20,7 +20,10 @@ endof(t::Tuple) = length(t)
 size(t::Tuple, d) = d==1 ? length(t) : throw(ArgumentError("invalid tuple dimension $d"))
 getindex(t::Tuple, i::Int) = getfield(t, i)
 getindex(t::Tuple, i::Real) = getfield(t, convert(Int, i))
-getindex(t::Tuple, r::AbstractArray{<:Any,1}) = tuple([t[ri] for ri in r]...)
+function getindex(t::Tuple, r::AbstractArray{<:Any,1})
+    s = Ref(start(r))
+    ntuple(j -> ((i, s[]) = next(r, s[]); t[i]), length(r))
+end
```
Comment (Sacha0) [inline base/tuple.jl]: This change seems orthogonal to the other changes in this pull request. Perhaps split this change into a separate pull request for additional discussion and to attract additional review eyes? (I remain concerned about losing `eltype` information with this change, and see no reason that that information is not important in general.)

File: base/tuple.jl [hunk 8]
```diff
@@ -94,17 +97,23 @@ julia> ntuple(i -> 2*i, 4)
...
+        n == 6  ? (f(1), f(2), f(3), f(4), f(5), f(6)) :
+        n == 7  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7)) :
+        n == 8  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8)) :
+        n == 9  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9)) :
+        n == 10 ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10)) :
+        _ntuple(f, n)
+    return t
+end
+
+_ntuple(f::Function, n::Integer) = (@_noinline_meta; ([f(i) for i = 1:n]...))
```
Comment (Sacha0) [inline base/tuple.jl]: Why switch from splatting a generator to splatting an array?

File: base/tuple.jl [hunk 9]
```diff
@@ -94,17 +97,23 @@ julia> ntuple(i -> 2*i, 4)
...
+        n == 1  ? (f(1),) :
+        n == 2  ? (f(1), f(2)) :
+        n == 3  ? (f(1), f(2), f(3)) :
+        n == 4  ? (f(1), f(2), f(3), f(4)) :
+        n == 5  ? (f(1), f(2), f(3), f(4), f(5)) :
+        n == 6  ? (f(1), f(2), f(3), f(4), f(5), f(6)) :
+        n == 7  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7)) :
+        n == 8  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8)) :
+        n == 9  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9)) :
+        n == 10 ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10)) :
```
Comment (Sacha0) [inline base/tuple.jl]: Does this change impact behavior for `10 < n < 16`? (Out of curiosity, what motivates this change?)

Comment (pabloferz) [inline base/tuple.jl]: The current implementation is slower for that range of values.

File: base/tuple.jl (hunk 8 above)
Comment (pabloferz) [inline base/tuple.jl]: For the time being, is faster than using the generator.

File: base/tuple.jl (hunk 7 above)
Comment (pabloferz) [inline base/tuple.jl]: With the changes to `ntuple`, the `eltype` for this would be inferred.

Comment (Sacha0) [inline base/tuple.jl]: Interesting :). Out of curiosity, which of the simultaneous `ntuple` changes make the new `getindex` version's `eltype` inferable? (The generator splat to array splat change?)

If this version does not lose `eltype` inferability, then cheers form this end. (Though having another pair of eyes on these changes would still be worthwhile.) Best!

Comment (pabloferz) [inline base/tuple.jl]: Turns out that inference works different when you directly return something like `c1 ? r1 : c2 ? r2 : c3 ? r3 ...` to when you assign that to a variable and then return the variable. So basically what improved things was assigning the tuple before returning it.

I won't leave this version as is as it messes inference when using this function inside macros in some circumstances (because of the closure). But I have a slightly different version that doesn't have that problem.

**Comment by pabloferz** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20720#issuecomment-282520622):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/52c43786fed81355c25d697ad28630776d800050/9f7f312_vs_466af85/report.md)
cc @jrevels

File: base/tuple.jl (hunk 7 above)
Comment (Sacha0) [inline base/tuple.jl]: Nice find! Inference's sensitivity to such things is somewhat disconcerting. Best!

**Comment by pabloferz** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20720#issuecomment-286527393):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d051c999f6529a578b756121fe00187b778ea659/e4b45ec_vs_64409a0/report.md)
cc @jrevels

**Comment by pabloferz** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20720#issuecomment-287185463) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2cb5ad3e47f0669c30b8eed1eec3bebc444fb46d/e7023ca_vs_e8e8012/report.md). cc @jrevels

**Comment by pabloferz** [comment]
Once more to see if anything is noise

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20720#issuecomment-287234430) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/276d119a80c2245dda32433b53d63761657c3e12/0a3256d_vs_4eb8c06/report.md). cc @jrevels

File: base/range.jl [hunk 10]
```diff
@@ -151,6 +151,10 @@ unitrange_last{T}(start::T, stop::T) =
     ifelse(stop >= start, convert(T,start+floor(stop-start)),
                           convert(T,start-oneunit(stop-start)))
 
+if isdefined(Main, :Base)
+    getindex(t::Tuple, r::UnitRange) = (o = r.start - 1; ntuple(n -> t[o + n], length(r)))
```
Comment (timholy) [inline base/range.jl]: Maybe `AbstractUnitRange`? And use `first(r)` rather than `r.start`?

File: base/tuple.jl (hunk 9 above)
Comment (timholy) [inline base/tuple.jl]: Interesting that LLVM doesn't reduce this to a calculated-jump. If you care enough to try, would a binary tree implementation be better? (It's less nice from a code-simplicity standpoint, so don't feel you have to do this.)

File: base/tuple.jl [hunk 11]
```diff
@@ -148,19 +154,28 @@ function map(f, t::Tuple, s::Tuple)
...
 # n argument function
-heads() = ()
-heads(t::Tuple, ts::Tuple...) = (t[1], heads(ts...)...)
-tails() = ()
-tails(t::Tuple, ts::Tuple...) = (tail(t), tails(ts...)...)
-map(f, ::Tuple{}, ts::Tuple...) = ()
-map(f, t1::Tuple, t2::Tuple, ts::Tuple...) = (f(heads(t1, t2, ts...)...), map(f, tails(t1, t2, ts...)...)...)
+heads(ts::Tuple...) = map(t -> t[1], ts)
+tails(ts::Tuple...) = map(tail, ts)
+map(f, ::Tuple{}...) = ()
```
Comment (timholy) [inline base/tuple.jl]: This is a breaking change because of this:
```julia
julia> map(+, (), (3,), (4,))
()
```
Consequently, this PR will have to wait until 1.0-dev.

**Review by timholy — COMMENTED** [review]
:+1:

File: base/tuple.jl (hunk 11 above)
Comment (tkelman) [inline base/tuple.jl]: should that be a dimension mismatch error?

Comment (pabloferz) [inline base/tuple.jl]: I thought this was a bug. X-ref: https://github.com/JuliaLang/julia/issues/20723

Comment (timholy) [inline base/tuple.jl]: I don't really like that behavior (I like this better), but I'd be surprised if there isn't code out there that counts on the current behavior. So even though I'd call this an improvement, I think it's dangerous to introduce a behavior change at this stage of the release process unless there's reason (1) to be certain it's a bug, or (2) be almost certain no one had been using this. But don't take that as official policy, it's just my viewpoint.

Comment (tkelman) [inline base/tuple.jl]: since we had an alpha tag, I plan on running a pkgeval comparison before tagging a beta, so we could find out

**Comment by pabloferz** [comment]
> Interesting that LLVM doesn't reduce this to a calculated-jump.

It does if I remove the assignment and return directly, but then inference isn't able to at least figure out the `eltype` (it infers `Tuple` instead `NTuple{N,T} where N` for the appropriate `T`).

> If you care enough to try, would a binary tree implementation be better?

For now I'd like to keep the code simplicity and leave other approaches for another occasion.

File: base/tuple.jl (hunk 11 above)
Comment (pabloferz) [inline base/tuple.jl]: I missed the beta tagging. Should this had to be merged before? If so, is there a way to checked if this brakes packages? Worse case, I can just drop the last commit, but wanted to now if it could be included.

Comment (tkelman) [inline base/tuple.jl]: Forgot about this since it was inactive for a few weeks and was missed in triage since it wasn't on the milestone. If you rebase the branch I can run pkgeval manually.

Comment (pabloferz) [inline base/tuple.jl]: All right, rebased then.

Comment (tkelman) [inline base/tuple.jl]: Some of these are flaky tolerances or timeouts, but AxisArrays failure looks related https://gist.github.com/2290f8d80dea51c9dc4aa3b4de59daf2

Comment (pabloferz) [inline base/tuple.jl]: https://github.com/JuliaArrays/AxisArrays.jl/pull/74

**Review by Sacha0 — APPROVED** [review]
Thanks for sticking with this @pabloferz! :)

File: base/tuple.jl (hunk 11 above)
Comment (pabloferz) [inline base/tuple.jl]: Could we merge this then, or should we wait until a new version of AxisArrays is tagged=

Comment (pabloferz) [inline base/tuple.jl]: @timholy what do you think?

Comment (timholy) [inline base/tuple.jl]: Go for it. I just tagged a new release.
