### PR TITLE
fix #14182: OS X linker target mismatch warning

### LINKED ISSUE #14182: Linker warning on OSX -- wrong version number used?
I see this warning when building Julia (0.5 master):

```
ld: warning: object file (/Users/eschnett/src/julia05/usr/lib/julia/sys.o) was built for newer OSX version (15.0) than being linked (10.7)
```

Note that the OSX version of my system is 10.11 (El Capitan), while my kernel version is 15.0. This looks as if some script used the kernel version instead of the OSX version when using the `-macos_version_min` option to `ld`.

PS: There's no "OSX" or "Apple" label for issues. But there's an "MS-DOS" one?

### PR DESCRIPTION
**Pull request by ihnorton**
fix #14182. ref: https://github.com/ldc-developers/ldc/pull/1209

### CODE REVIEW

File: src/jitlayers.cpp [hunk 1]
```diff
@@ -1070,6 +1070,7 @@ void jl_dump_native(const char *bc_fname, const char *unopt_bc_fname, const char
     TheTriple.setObjectFormat(Triple::COFF);
 #elif defined(_OS_DARWIN_)
     TheTriple.setObjectFormat(Triple::MachO);
+    TheTriple.setOS(llvm::Triple::MacOSX);
```
Comment (ararslan) [inline src/jitlayers.cpp]: In the off chance that Julia works on PureDarwin (I assume no one has ever tried), perhaps this should be in its own `#ifdef __APPLE__`?

Comment (tkelman) [inline src/jitlayers.cpp]: same difference https://github.com/JuliaLang/julia/blob/090e549d895882bab7a15566d1a8f1f9c1f0f660/src/support/platform.h#L72-L73

Comment (ararslan) [inline src/jitlayers.cpp]: Oh cool. Don't mind me then.
