### PR TITLE
Fix calculation of displayed time, show UTC offset

### LINKED ISSUE #22103: Printing of Signature in libgit2
[Here:](https://github.com/JuliaLang/julia/blob/f67f58e525f7b11517e6f77135a767e3a38f2f4d/base/libgit2/signature.jl#L38) the unix time is computed as: `sig.time + sig.time_offset`. However, the  [docs for `TimeStruct`](https://github.com/JuliaLang/julia/blob/f67f58e525f7b11517e6f77135a767e3a38f2f4d/base/libgit2/types.jl#L47) says: `offset::Cint    # timezone offset in minutes`.

Should there be a `*60` on the `sig.time_offset` in show?

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #22103.

### CODE REVIEW

**Review by kshyatt — APPROVED** [review]

File: base/libgit2/signature.jl [hunk 1]
```diff
@@ -35,7 +35,12 @@ function Base.convert(::Type{GitSignature}, sig::Signature)
     return GitSignature(sig_ptr_ptr[])
 end
 
-Base.show(io::IO, sig::Signature) = print(io, "Name: $(sig.name), Email: $(sig.email), Time: $(Dates.unix2datetime(sig.time + sig.time_offset))")
+function Base.show(io::IO, sig::Signature)
+    print(io, "Name: ", sig.name, ", ")
+    print(io, "Email: ", sig.email, ", ")
+    print(io, "Time: ", Dates.unix2datetime(sig.time + 60*sig.time_offset))
+    @printf(io, "%+03i:%02i", divrem(sig.time_offset,60)...)
```
Comment (Sacha0) [inline base/libgit2/signature.jl]: Missing space between arguments to `divrem`?

Comment (KristofferC) [inline base/libgit2/signature.jl]: Fixed
