### PR TITLE
Check if argument is NULL in jl_f_apply. Fix #11772

### LINKED ISSUE #11772: Seg fault when zipping cell array
```julia
julia> c = cell(5)
5-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef

julia> zip(c...)

signal (11): Segmentation fault: 11
jl_method_table_assoc_exact at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:245
jl_apply_generic at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1396
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/builtins.c:281
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:59
eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:207
jl_toplevel_eval_flex at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:496
jl_f_top_eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/builtins.c:399
eval_user_input at REPL.jl:53
jlcall_eval_user_input_20251 at  (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:982
anonymous at task.jl:95
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/task.c:423
julia_trampoline at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/init.c:1053
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by yuyichao**
AFAICT, this can only happen in `apply`. I did a rough search and other places all looks ok for me.

The optimization in `codegen` is probably fine as well since it's directly forwarding the input parameters.

~~P.S. The `onstack` logic looks weird for me. It seems that the index calculation is wrong.~~

Fix #11772

### CODE REVIEW

**Comment by yuyichao** [comment]
Maybe I should add more test to cover all code paths?

**Comment by yuyichao** [comment]
Ahh. Never mind with the `onstack` part. It's a really strange use of `JL_GC_PUSHARGS` though....

**Comment by yuyichao** [comment]
Is it actually possible to have svec and tuple with embedded NULL from julia?

File: src/builtins.c [hunk 1]
```diff
@@ -436,7 +458,10 @@ JL_CALLABLE(jl_f_apply)
             jl_value_t *argarr = jl_apply(jl_append_any_func, &args[1], nargs-1);
             assert(jl_typeis(argarr, jl_array_any_type));
             JL_GC_PUSH1(&argarr);
-            jl_value_t *result = jl_apply(f, jl_cell_data(argarr), jl_array_len(argarr));
+            size_t new_narg = jl_array_len(argarr);
+            jl_value_t **new_args = jl_cell_data(argarr);
+            jl_check_nargs_defined(new_args, new_narg);
```
Comment (JeffBezanson) [inline src/builtins.c]: I don't think it's necessary to check the result of `append_any`. It's a julia function so it already checks for null on access.

**Comment by JeffBezanson** [comment]
I would not bother to check tuples and svecs. They can only have NULLs temporarily while being initialized internally, and can't be splatted in that state.

Thanks for fixing this; indeed it is pretty embarrassing.

File: src/builtins.c (hunk 1 above)
Comment (yuyichao) [inline src/builtins.c]: So I guess extending `Base.append_any` would be undefined behavior (just like many other non-exported functions)

**Comment by yuyichao** [comment]
> I would not bother to check tuples and svecs. They can only have NULLs temporarily while being initialized internally, and can't be splatted in that state.

That's what I guess but I wasn't sure about it. Will do.

File: src/builtins.c (hunk 1 above)
Comment (JeffBezanson) [inline src/builtins.c]: Yes, you definitely should not extend or redefine that function.

**Comment by yuyichao** [comment]
Done

File: src/builtins.c [hunk 2]
```diff
@@ -436,7 +436,8 @@ JL_CALLABLE(jl_f_apply)
             jl_value_t *argarr = jl_apply(jl_append_any_func, &args[1], nargs-1);
             assert(jl_typeis(argarr, jl_array_any_type));
             JL_GC_PUSH1(&argarr);
-            jl_value_t *result = jl_apply(f, jl_cell_data(argarr), jl_array_len(argarr));
+            jl_value_t *result = jl_apply(f, jl_cell_data(argarr),
```
Comment (JeffBezanson) [inline src/builtins.c]: I guess you prefer an 80-column limit? Anyway usually better to avoid unrelated formatting changes like this.

Comment (yuyichao) [inline src/builtins.c]: Yes. But this is a left over from my previous version. Will change it back ....

**Comment by yuyichao** [comment]
And done again....

Just canceled a few duplicated Travis job (hopefully didn't accidentally canceled anything wrong) so hopefully it will finish the backlog earlier....

**Comment by yuyichao** [comment]
This bug is also presented in 0.3, should this be backported?

**Comment by yuyichao** [comment]
@JuliaBackports ?

**Comment by pao** [comment]
I think the tag is the "proper" way to add to the backport list now; I'm not sure anyone is actively watching the user account? We added both at about the same time because we weren't sure what was going to be most convenient. I'm honestly not sure, but since this has sat for a couple of days, let's give it a go.

**Comment by yuyichao** [comment]
It is already backported in https://github.com/JuliaLang/julia/pull/11786.

**Comment by pao** [comment]
Ah. Guess it didn't crossreference because the only mention of this issue number was in the title?

**Comment by tkelman** [comment]
I watch the julia-backports mailing list, but it's less visible than the label. I prefer people use the label when there's a corresponding issue or pull request that goes along with the proposed backport, and only ping the `@juliabackports` user for un-attached commits. Or for non-collaborators who don't have permissions to modify issue/pr labels.

I still need to write down my personal backporting policy to make it more formal.

**Comment by yuyichao** [comment]
> Ah. Guess it didn't crossreference because the only mention of this issue number was in the title?

Right. I always forgot about that, especially when refering a closed issue.... = = ................

**Comment by pao** [comment]
No problem, @yuyichao. And I think that @tkelman's personal backporting policy is *de facto* the Julia backporting policy, so it would be cool to have that as a reference.

**Comment by tkelman** [comment]
If there isn't already an entry for the lack of cross-references from issue/pr titles at https://github.com/isaacs/github/issues, there should be

**Comment by pao** [comment]
That doesn't seem like a particularly effective outlet, looking at the closed issue list. Contacting GitHub directly seems like a better choice (and it has worked for me in the past.)
