### PR TITLE
Fix: waitall can throw when all tasks are done

### LINKED ISSUE #59901: `waitall` doesn't throw
It doesn't throw like `foreach(wait, tasks)`, is this normal?
```julia
julia> f(d) = 1 ÷ d;

julia> waitall(Threads.@spawn(f(i)) for i = 0:1) # no error
(Task[Task (failed) @0x00007ced9879eb30, Task (done) @0x00007ced9879ec20], Task[])
```
(found in https://discourse.julialang.org/t/waitall-tasks-doesnt-throw-as-foreach-wait-tasks-does/133260?u=waltermadelim)

### PR DESCRIPTION
**Pull request by jakobnissen**
Closes #59901

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: base/task.jl [hunk 1]
```diff
@@ -435,19 +435,21 @@ function _wait_multiple(waiting_tasks, throwexc=false, all=false, failfast=false
...
-        else
-            done_mask[i] = false
         end
     end
 
-    if nremaining == 0
-        return tasks, Task[]
-    elseif any(done_mask) && (!all || (failfast && exception))
+    # We can return early all tasks are done, or if any is done and we only
+    # needed to wait for one, or if any task failed and we have failfast
```
Comment (Seelengrab) [inline base/task.jl:442]: Is the throwing & failfast combination tested?

**Comment by aviatesk** [comment]
@mrkn Let me CC who originally design and implement this function, just in case.

File: base/task.jl (hunk 1 above)
Comment (jakobnissen) [reply base/task.jl:442]: Yes, in both of the testsets added in this PR (they take different paths through the function).

**Comment by mrkn** [comment]
@jakobnissen Thank you for the fix.  I hadn't handle the case where `nremaining == 0` and some tasks threw exceptions, so I couldn't catch this bug.

**Comment by jakobnissen** [comment]
Test failures appear unrelated

**Comment by JamesWrigley** [comment]
I took the liberty of marking this for backporting to 1.12 because it seems like a rather important bugfix.
