### PR TITLE
Change convert function in base/namedtuple.jl

### LINKED ISSUE #47604: convert on named tuple can give "T not defined" error
This came up on [discourse](https://discourse.julialang.org/t/why-cant-this-named-tuple-be-converted-to-a-supertype/90329), the operation itself doesn't make sense  (it's "converting" to an abstract type that is already a supertype of the value so there's nothing to do) but it seems to have uncovered a bug:

```julia
julia> convert(@NamedTuple{a::S} where S, (; a=1))
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] convert(#unused#::Type{NamedTuple{(:a,), Tuple{S}} where S}, nt::NamedTuple{(:a,), Tuple{Int64}})
   @ Base ./namedtuple.jl:152
 [2] top-level scope
   @ REPL[2]:1
```

while for example the following works:

```julia
julia> convert(@NamedTuple{a::Vector{S}} where S, (; a=[1]))
(a = [1],)
```

```
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

### PR DESCRIPTION
**Pull request by vmpyr**
Fixes: #47604

### CODE REVIEW

File: base/namedtuple.jl [hunk 1]
```diff
@@ -179,8 +179,11 @@ nextind(@nospecialize(t::NamedTuple), i::Integer) = Int(i)+1
...
 convert(::Type{NamedTuple{names}}, nt::NamedTuple{names}) where {names} = nt
 
-function convert(::Type{NamedTuple{names,T}}, nt::NamedTuple{names}) where {names,T<:Tuple}
-    NamedTuple{names,T}(T(nt))::NamedTuple{names,T}
+function convert(::Type{NamedTuple{names,T1}}, nt::NamedTuple{names,T2}) where {names,T1<:Tuple,T2<:Tuple}
+    if (T1<:T2)
+        return nt
+    end
+    NamedTuple{names,T1}(T1(nt))::NamedTuple{names,T1}
 end
```
Comment (vtjnash) [inline base/namedtuple.jl:187]: It is a little more complicated than that, since T1 is not defined. We can compute it though, with some effort:
```suggestion
convert(::Type{NT}, nt::NT) where {names, NT<:NamedTuple{names}} = nt
convert(::Type{NT}, nt::NT) where {names, T<:Tuple, NT<:NamedTuple{names,T}} = nt
function convert(::Type{NT}, nt::NamedTuple{names}) where
                       {names, T<:Tuple, NT<:NamedTuple{names,T}}
    if !@isdefined T
       # converting abstract NT to an abstract Tuple type, to a concrete NT1, is not straightforward, so this could just be an error, but we define it anyways
       # _tuple_error(NT, nt)
       T1 = Tuple{ntuple(i -> fieldtype(NT, i), Val(length(names)))...}
       NT1 = NamedTuple{names, T1}
    else
       T1 = T
       NT1 = NT
    end
    return NT1(T1(nt))::NT1::NT
end
```

various examples
```julia
julia> convert(NamedTuple{(:a,),Tuple{I}} where I, (;a=1))
(a = 1,)

julia> convert(NamedTuple{(:a,),Tuple{Any}}, (;a=1))
NamedTuple{(:a,), Tuple{Any}}((1,))

julia> convert(NamedTuple{(:a,),}, (;a=1))
(a = 1,)

julia> convert(NamedTuple{(:a,),Tuple{I}} where I<:Unsigned, (;a=1))
NamedTuple{(:a,), Tuple{Unsigned}}((0x0000000000000001,))

julia> convert(NamedTuple{(:a,),Tuple{I}} where I<:AbstractString, (;a=1))
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type AbstractString

julia> convert(NamedTuple, (;a=1))
(a = 1,)
```

**Comment by vmpyr** [comment]
Ohh, I thought it was pretty straightforward. Can we still not do what I did but define T1 and T2 beforehand? I'm making these changes anyway, thanks!

**Comment by inkydragon** [comment]
It would be nice to add some tests.

File: test/namedtuple.jl [hunk 2]
```diff
@@ -76,6 +76,23 @@ let NT = NamedTuple{(:a,:b),Tuple{Int8,Int16}}, nt = (x=3,y=4)
...
+    @test conv2 == NamedTuple{(:a,), Tuple{Any}}((1,))
+
+    conv3 = convert(NamedTuple{(:a,),}, (;a=1))
+    @test conv3 == (a = 1,)
+
+    conv4 = convert(NamedTuple{(:a,),Tuple{I}} where I<:Unsigned, (;a=1))
+    @test conv4 == NamedTuple{(:a,), Tuple{Unsigned}}((0x0000000000000001,))
+
+    conv5 = convert(NamedTuple, (;a=1))
+    @test conv1 == (a = 1,)
```
Comment (vtjnash) [inline test/namedtuple.jl:93]: 1. Use `===` to compare types as well as values
2. Use convert(Unsigned,1), since `0x00...` is sized for 64-bit machines
3. add a test_throws for convert(AbstractString, 1)
```suggestion
    @test conv1 === (a = 1,)

    conv2 = convert(NamedTuple{(:a,),Tuple{Any}}, (;a=1))
    @test conv2 === NamedTuple{(:a,), Tuple{Any}}((1,))

    conv3 = convert(NamedTuple{(:a,),}, (;a=1))
    @test conv3 === (a = 1,)

    conv4 = convert(NamedTuple{(:a,),Tuple{I}} where I<:Unsigned, (;a=1))
    @test conv4 === NamedTuple{(:a,), Tuple{Unsigned}}((1,))

    conv5 = convert(NamedTuple, (;a=1))
    @test conv1 === (a = 1,)
    
    res = @test_throws MethodError convert(NamedTuple{(:a,),Tuple{I}} where I<:AbstractString, (;a=1))
    @test res.value.f === :convert && res.value.args === (AbstractString, 1)
```

Comment (vmpyr) [reply test/namedtuple.jl:93]: Okay, will do. Also can you please explain me what `test_throws` does exactly? Especially here where you are testing the output of `test_throws` as well. Does it simply return the error associated with a function call?

Comment (vmpyr) [reply test/namedtuple.jl:93]: Hi, I think, in line 96 of your suggestion it should be:
```
@test conv_res.value.f === convert && conv_res.value.args === (AbstractString, 1)
```
instead of:
```
@test conv_res.value.f === :convert && conv_res.value.args === (AbstractString, 1)
```
I'm making the commit accordingly.
