### PR TITLE
replace broken replaceuserpath function with existing contractuser one

### LINKED ISSUE #39674: Bug in user path replacement in stacktrace
My home directory, `/home/akosuas`, is a symlink to `/data/home/akosuas`. 

In 1.6, the new stacktrace printing is broken when the code is being run from `/data/home/akosuas`. It prints paths like:
```
....
 [5] top-level scope
  @ /data~/foo/bar
```

Because it is doing a `replace("/data/home/akosuas", "/home/akosuas" => "~")` rather than a prefix-replace:
https://github.com/JuliaLang/julia/blob/master/base/errorshow.jl#L556

At minimum, it would be nice to avoid this bug. Even better, perhaps, would be to resolve whether any prefix of the path, after resolving symlinks, is the home directory.

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #39674

### CODE REVIEW

File: base/errorshow.jl [hunk 1]
```diff
@@ -698,7 +691,7 @@ end
 function print_stackframe(io, i, frame::StackFrame, n::Int, digit_align_width, modulecolor)
     file, line = string(frame.file), frame.line
     stacktrace_expand_basepaths() && (file = something(find_source_file(file), file))
-    stacktrace_contract_userdir() && (file = replaceuserpath(file))
+    stacktrace_contract_userdir() && (file = contractuser(file))
```
Comment (KristofferC) [inline base/errorshow.jl:694]: This doesn't seem to work on Windows (which might be why the custom function was called).

Comment (vtjnash) [reply base/errorshow.jl:694]: That is exactly the wrong reason to define a new function however

Comment (vtjnash) [reply base/errorshow.jl:694]: Can you open a new issue to change that function? It is okay to assign me.
