### PR TITLE
codegen: take gc roots (and alloca alignment) more seriously

### LINKED ISSUE #54720: Concurrent program crashes 1.12 nightly build (1.10 is fine)
I attached the code that reproduces the crash. I'm sorry for the extension but couldn't attach a Julia source file.

You may need to give it a few tries though. It should crash in a few seconds, but sometimes it just hangs. I have a 16 core machine, so that may also affect the outcome.

See [discussion](https://discourse.julialang.org/t/lock-free-sorted-linked-list/115157/13) for some details.

I installed Julia with juliaup.

```
julia> versioninfo()
Julia Version 1.12.0-DEV.670
Commit 5cb1107cce1 (2024-06-06 03:00 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 4800HS with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver2)
Threads: 16 default, 0 interactive, 16 GC (on 16 virtual cores)
Environment:
  JULIA_NUM_THREADS = 4
```

[crash.jl.txt](https://github.com/user-attachments/files/15685479/crash.jl.txt)

image

### PR DESCRIPTION
**Pull request by vtjnash**
Due to limitations in the LLVM implementation, we are forced to emit fairly bad code here. But we need to make sure it is still correct with respect to GC rooting.

Fixes #54720

### CODE REVIEW

**Comment by Keno** [comment]
Can we get a test? At the very least a codegen test if the runtime behavior is non-deterministic.

**Comment by gbaraldi** [comment]
Also maybe split this into two commits. One that does the seemingly NFC changes to use the `Align` type and the other with  the functional changes.

File: src/cgutils.cpp [hunk 1]
```diff
@@ -2120,12 +2119,15 @@ static jl_cgval_t typed_store(jl_codectx_t &ctx,
         FailOrder = AtomicOrdering::Monotonic;
     unsigned nb = isboxed ? sizeof(void*) : jl_datatype_size(jltype);
     AllocaInst *intcast = nullptr;
+    Type *intcast_eltyp = nullptr;
+    bool tracked_pointers = isboxed || CountTrackedPointers(elty).count > 0;
     if (!isboxed && Order != AtomicOrdering::NotAtomic && !elty->isIntOrPtrTy()) {
+        intcast_eltyp = elty;
+        elty = Type::getIntNTy(ctx.builder.getContext(), 8 * nb);
```
Comment (gbaraldi) [inline src/cgutils.cpp:2126]: Does this need a check so that N isn't too large? Or does the code that falls back to a lock avoid that?

**Comment by vtjnash** [comment]
Added some tests to exercise this case, which was good because it found that https://github.com/JuliaLang/julia/pull/54121 had also introduced bugs in there recently when the spelling of the haspadding flag was changed to haspadding || !isbitsegal :/

File: src/cgutils.cpp (hunk 1 above)
Comment (vtjnash) [reply src/cgutils.cpp:2126]: there is no limit on how large N can be per the standard (but yes, we limit to MAX_ATOMIC_SIZE because it generates better code)

**Comment by KristofferC** [comment]
I started backporting this but got a bit uncomfortable that I did things right. @vtjnash  maybe you could do it instead?

**Comment by vtjnash** [comment]
Pushed to https://github.com/JuliaLang/julia/pull/55530. For future cases like this, note that Visual Studio Code was able to complete almost the entire merge automatically (where git itself failed quite a bit). Although not quite complete, since it also uncovered a bug, which I pushed to the backports branch and opened on master here: https://github.com/JuliaLang/julia/pull/55530
