### PR TITLE
post-opt: run full scan within `check_inconsistency!`

### LINKED ISSUE #51837: Code optimizer compiles failing check away on Julia master
Hey folks,

our CI running with Julia master caught what seems like an optimizer bug, MRE:
```julia
_nbytes(::UInt8) = 1
_nbytes(x::Union{String,Char}) = ncodeunits(x)
function _validate_parser_args(;openquotechar, closequotechar, delim, escapechar, decimal, newlinechar, ignorerepeated)
    _nbytes(openquotechar) == 1 || throw(ArgumentError("`openquotechar` must be a single-byte character"))
    _nbytes(closequotechar) == 1 || throw(ArgumentError("`closequotechar` must be a single-byte character"))
    if isnothing(delim)
        ignorerepeated && throw(ArgumentError("auto-delimiter detection not supported when `ignorerepeated=true`; please provide delimiter like `delim=','`"))
    else
        _nbytes(delim) == 1 || throw(ArgumentError("`delim` must be a single-byte character"))
    end
    _nbytes(escapechar) == 1 || throw(ArgumentError("`escapechar` must be a single-byte character"))
    _nbytes(decimal) == 1 || throw(ArgumentError("`decimal` must be a single-byte character"))

    if !isnothing(newlinechar)
        _nbytes(newlinechar) > 1 && throw(ArgumentError("`newlinechar` must be a single-byte character."))
        ((newlinechar % UInt8) in ((openquotechar % UInt8), (closequotechar % UInt8), (escapechar % UInt8), (something(delim, 0x00) % UInt8))) &&
            throw(ArgumentError("`newlinechar` must be different from `delim`, `openquotechar`, `closequotechar`, and `escapechar`"))
    end

    return nothing
end

# Should throw, but returns nothing
_validate_parser_args(openquotechar='α', closequotechar='α', delim=',', decimal='.', escapechar='\\', newlinechar='\n', ignorerepeated=true)
```

On `1.10.0-beta3` we get the following expected result:
```julia
julia> _validate_parser_args(openquotechar='α', closequotechar='α', delim=',', decimal='.', escapechar='\\', newlinechar='\n', ignorerepeated=true)
ERROR: ArgumentError: `openquotechar` must be a single-byte character
Stacktrace:
 [1] _validate_parser_args(; openquotechar::Char, closequotechar::Char, delim::Char, escapechar::Char, decimal::Char, newlinechar::Char, ignorerepeated::Bool)
   @ Main ./REPL[3]:2
 [2] top-level scope
   @ REPL[4]:1
```
On latest nigthly 
```julia
julia> versioninfo()
Julia Version 1.11.0-DEV.719
Commit 17a36eeb061 (2023-10-24 08:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```
I get the following outputs for `code_typed`:
```
julia> @code_typed optimize=false _validate_parser_args(openquotechar='α', closequotechar='α', delim=',', decimal='.', escapechar='\\', newlinechar='\n', ignorerepeated=true)
CodeInfo(
1 ──       Core.NewvarNode(:(@_4))::Any
│    %2  = Core.isdefined(@_2, :openquotechar)::Core.Const(true)
└───       goto #3 if not %2
2 ──       (@_4 = Core.getfield(@_2, :openquotechar))::Char
└───       goto #4
3 ──       Core.Const(:(Core.UndefKeywordError(:openquotechar)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%6)))::Union{}
4 ┄─ %8  = @_4::Char
│          (openquotechar = %8)::Char
│    %10 = Core.isdefined(@_2, :closequotechar)::Core.Const(true)
└───       goto #6 if not %10
5 ──       (@_4 = Core.getfield(@_2, :closequotechar))::Char
└───       goto #7
6 ──       Core.Const(:(Core.UndefKeywordError(:closequotechar)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%14)))::Union{}
7 ┄─ %16 = @_4::Char
│          (closequotechar = %16)::Char
│    %18 = Core.isdefined(@_2, :delim)::Core.Const(true)
└───       goto #9 if not %18
8 ──       (@_4 = Core.getfield(@_2, :delim))::Char
└───       goto #10
9 ──       Core.Const(:(Core.UndefKeywordError(:delim)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%22)))::Union{}
10 ┄ %24 = @_4::Char
│          (delim = %24)::Char
│    %26 = Core.isdefined(@_2, :escapechar)::Core.Const(true)
└───       goto #12 if not %26
11 ─       (@_4 = Core.getfield(@_2, :escapechar))::Char
└───       goto #13
12 ─       Core.Const(:(Core.UndefKeywordError(:escapechar)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%30)))::Union{}
13 ┄ %32 = @_4::Char
│          (escapechar = %32)::Char
│    %34 = Core.isdefined(@_2, :decimal)::Core.Const(true)
└───       goto #15 if not %34
14 ─       (@_4 = Core.getfield(@_2, :decimal))::Char
└───       goto #16
15 ─       Core.Const(:(Core.UndefKeywordError(:decimal)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%38)))::Union{}
16 ┄ %40 = @_4::Char
│          (decimal = %40)::Char
│    %42 = Core.isdefined(@_2, :newlinechar)::Core.Const(true)
└───       goto #18 if not %42
17 ─       (@_4 = Core.getfield(@_2, :newlinechar))::Char
└───       goto #19
18 ─       Core.Const(:(Core.UndefKeywordError(:newlinechar)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%46)))::Union{}
19 ┄ %48 = @_4::Char
│          (newlinechar = %48)::Char
│    %50 = Core.isdefined(@_2, :ignorerepeated)::Core.Const(true)
└───       goto #21 if not %50
20 ─       (@_4 = Core.getfield(@_2, :ignorerepeated))::Bool
└───       goto #22
21 ─       Core.Const(:(Core.UndefKeywordError(:ignorerepeated)))::Union{}
└───       Core.Const(:(@_4 = Core.throw(%54)))::Union{}
22 ┄ %56 = @_4::Bool
│          (ignorerepeated = %56)::Bool
│    %58 = (:openquotechar, :closequotechar, :delim, :escapechar, :decimal, :newlinechar, :ignorerepeated)::Core.Const((:openquotechar, :closequotechar, :delim, :escapechar, :decimal, :newlinechar, :ignorerepeated))
│    %59 = Core.apply_type(Core.NamedTuple, %58)::Core.Const(NamedTuple{(:openquotechar, :closequotechar, :delim, :escapechar, :decimal, :newlinechar, :ignorerepeated)})
│    %60 = Base.structdiff(@_2, %59)::Core.Const(NamedTuple())
│    %61 = Base.pairs(%60)::Core.Const(Base.Pairs{Symbol, Union{}, Tuple{}, @NamedTuple{}}())
│    %62 = Base.isempty(%61)::Core.Const(true)
└───       goto #24 if not %62
23 ─       goto #25
24 ─       Core.Const(:(Base.kwerr(@_2, @_3)))::Union{}
25 ┄ %66 = Main.:(var"#_validate_parser_args#1")(openquotechar, closequotechar, delim, escapechar, decimal, newlinechar, ignorerepeated, @_3)::Core.Const(nothing)
└───       return %66
) => Nothing
```
which is the same as what we get on `1.10.0-beta3`, but if we set `optimize=true`:
```
julia> @code_typed optimize=true _validate_parser_args(openquotechar='α', closequotechar='α', delim=',', decimal='.', escapechar='\\', newlinechar='\n', ignorerepeated=true)
CodeInfo(
1 ─     nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
│       nothing::Nothing
└──     return nothing
) => Nothing
```

### PR DESCRIPTION
**Pull request by aviatesk**
Otherwise we fail to scan all statements.

fix #51837

### CODE REVIEW

File: base/compiler/optimize.jl [hunk 1]
```diff
@@ -707,9 +706,10 @@ function ((; sv)::ScanStmt)(inst::Instruction, idx::Int, lstmt::Int, bb::Int)
 end
 
 function check_inconsistentcy!(sv::PostOptAnalysisState, scanner::BBScanner)
-    scan!(ScanStmt(sv), scanner, true)
+    scan!(ScanStmt(sv), scanner, false)
```
Comment (aviatesk) [inline base/compiler/optimize.jl:709]: @Keno, I'm trying to understand the rationale behind the two-phase approach in `scan!` within `ipo_dataflow_analysis!`. Currently we first run `scan!` with the `forward_only` flag enabled, and in a case when the scan isn't completed (meaning control backedges are found), we then run it again with `forward_only` disabled. I'm concerned about the potential redundancy in this approach. Wouldn't it be more efficient to perform a full scan just once (and perform the additional inconsistency-check if necessary)?

Comment (Keno) [reply base/compiler/optimize.jl:709]: I don't think we run it again, we just continue running it with the same state.

**Review by Keno — APPROVED** [review]

File: base/compiler/optimize.jl (hunk 1 above)
Comment (aviatesk) [reply base/compiler/optimize.jl:709]: Ah, I got it. Thanks.
