### PR TITLE
Profile: Fix checks of remaining backtrace buffer

### LINKED ISSUE #35870: Condition where backtrace buffer for profiling is full
On Linux, the number of stored instruction pointers will be less than the specified maximum number.
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

julia> using Profile

julia> Profile.init(n = 100)

julia> Profile.clear()

julia> @profile rand(Float64, 100, 100);

julia> length(Profile.fetch())
99
```
In fact, the source code specifies that. ~However, I don't understand the meaning of the `-1`.~ The null sentinels are counted properly.
https://github.com/JuliaLang/julia/blob/f12cde0e8c7f4268838d3201dd9e13b90ea44633/src/signals-unix.c#L700-L706

Although the behavior is safer in terms of memory access, the warning below is not displayed correctly.
https://github.com/JuliaLang/julia/blob/3af96bcefcb0aec559d4652fd75e1bc3fcfe99da/stdlib/Profile/src/Profile.jl#L308-L315

I'm still studying how profiling works, so I am not confident in making a PR for this issue.

### PR DESCRIPTION
**Pull request by kimikage**
Fixes #35870

`jl_unw_stepn` requires a free space of `JL_BT_MAX_ENTRY_SIZE + 1` regardless of the actual entry size. Therefore, the tail of the backtrace buffer is eventually filled with sentinel, i.e. `0`.

It is necessary to export `JL_BT_ MAX_ENTRY_SIZE` to detect the buffer fullness in the Profile package. For this reason, and in order to commonize the code between OSs, this PR adds `jl_profile_is_buffer_full()`.

~**Edit:**
I don't feel that this change is as simple as the problem which this fixes (i.e. the display of a warning).Therefore, hoping that the backtrace handling will be radically improved in the future, I think that it is enough to add a broken test for now.~

### CODE REVIEW

File: src/signal-handling.c [hunk 1]
```diff
@@ -288,6 +288,11 @@ JL_DLLEXPORT int jl_profile_is_running(void)
     return running;
 }
 
+JL_DLLEXPORT int jl_profile_is_buffer_full(void)
+{
+    return bt_size_cur + JL_BT_MAX_ENTRY_SIZE + 1 >= bt_size_max;
```
Comment (kimikage) [inline src/signal-handling.c:293]: I don't know the intent of the `+ 1` (changed in PR #34019). 
https://github.com/JuliaLang/julia/blob/852ff2bdab0b0cac987c0f1ef552ef11202cd2d5/src/stackwalk.c#L94
So based on the current implementation, I added extra `1` for the sentinel. (Note the difference between `>` and `>=`.)

**Comment by kimikage** [comment]
I'll close this as there are other PRs which modify the `Profile`.

File: src/signal-handling.c (hunk 1 above)
Comment (vtjnash) [reply src/signal-handling.c:293]: Yes, we now always add the unwind info from the stack walk (+1) to the current trace (n), then also may insert an entry with up to JL_BT_MAX_ENTRY_SIZE additional information.

This PR looks correct to me, modulo needing to be updated. Is there any particular reason you did not think so?

Comment (kimikage) [reply src/signal-handling.c:293]: I think this PR fix will work, but the intent or purpose of `+1` is not clear. I think one of the causes of the bug which this PR is trying to fix, is this unclear specification.

This is a matter of agreement between the `jl_unw_stepn` and its callers, and, of course, I am not saying #34019 is wrong.

We can reopen this PR, but I think it would be more beneficial to create a new PR than to open a stack walk lecture for me.

Comment (kimikage) [reply src/signal-handling.c:293]: BTW, I also don't understand the intent of timing control on Windows.
https://github.com/JuliaLang/julia/blob/29a6e66e4944c6d79e1f672ae4648a76599b2f21/src/signals-win.c#L340-L342

It was also weird before PR #37101, but I thought it was best effort, assuming the frequency was peaked in the first place.
PR #37101 seems to be trying to improve it by using `timeBeginPeriod`/`timeEndPeriod`. However, the unit of `nsecprof / GIGA` should be seconds. :confused:

Comment (vtjnash) [reply src/signal-handling.c:293]: Ah thanks for that find! I knew the logic there had been weird, but didn't notice that the units of `timeout` were wrong also. Should be even better after https://github.com/JuliaLang/julia/pull/38208 in that case. Realistically, this just meant it always used the minimum interval (1-2ms), so hardly noticeable to most people, but worth fixing.

Comment (vtjnash) [reply src/signal-handling.c:293]: Almost all looks right about that new version, if you want to make it a PR.

Note that this is using `timeout += tc.wPeriodMin` (and not `max(,1)`) since the documentation for the `Sleep` function says it returns up to that many milliseconds early. So you have to add that value to be able to set the actual desired timeout (https://docs.microsoft.com/en-us/windows/win32/sync/wait-functions#wait-functions-and-time-out-intervals)

Comment (kimikage) [reply src/signal-handling.c:293]: Oh, I'm sorry. I commented in https://github.com/JuliaLang/julia/pull/38208#issuecomment-718008334

Comment (vtjnash) [reply src/signal-handling.c:293]: Now that the units issue is fixed, do you want to rebase and land that revised version of yours for this issue? Thanks!

**Comment by kimikage** [comment]
I've rebased the commit and am re-opening this PR.
However, I'm not familiar with the C and I still don't understand the current codebase.
