### PR TITLE
Various fixes to byte / bytearray search

### LINKED ISSUE #54578: Conflation of UInt8 and Int8 in search functions
When looking at the source code in `base/string/search.jl`, I found some issues:
```julia
julia> findfirst(==(Int8(-1)), [0xff]) # buggy
1

julia> findfirst([Int8(-1)], [0xff]) # also buggy
1:1
```
This is buggy, since `!isequal(0xff, Int8(-1))`.

Probably added in https://github.com/JuliaLang/julia/pull/37283

### PR DESCRIPTION
**Pull request by jakobnissen**
This was originally intended as a targeted fix to #54578, but I ran into a bunch of smaller issues with this code that also needed to be solved and it turned out to be difficult to fix them with small, trivial PRs.

I would also like to refactor this whole file, but I want these correctness fixes to be merged first, because a larger refactoring has higher risk of getting stuck without getting reviewed and merged.

## Larger things that needs decisions
* The internal union `Base.ByteArray` has been deleted. Instead, the unions `DenseInt8` and `DenseUInt8` have been added. These more comprehensively cover the types that was meant, e.g. `Memory{UInt8}` was incorrectly not covered by the former. As stated in the TODO, the concept of a "memory backed dense byte array" is needed throughout Julia, so this ideally needs to be implemented as a single type and used throughout Base. The fix here is a decent temporary solution. See #53178 #54581
* The `findall` docstring between two arrays was incorrectly not attached to the method - now it is. **Note that this change _changes_ the documentation** since it includes a docstring that was previously missed. Hence, it's an API addition.
* Added a new minimal `testhelpers/OffsetDenseArrays.jl` which provide a `DenseVector` with offset axes for testing purposes.

## Trivial fixes
* `findfirst(==(Int8(-1)), [0xff])` and similar findlast, findnext and findprev is no longer buggy, see #54578
* `findfirst([0x0ff], Int8[-1])` is similarly no longer buggy, see #54578
* `findnext(==('\xa6'), "æ", 1)` and `findprev(==('\xa6'), "æa", 2)` no longer incorrectly throws an error
* The byte-oriented find* functions now work correctly with offset arrays
* Fixed incorrect use of `GC.@preserve`, where the pointer was taken before the preserve block.
* More of the optimised string methods now also apply to `SubString{String}`

Closes #54578

### CODE REVIEW

**Comment by giordano** [comment]
> This fixes an issue introduced in commit 5d8225a 

There's no such commit.

File: test/strings/search.jl [hunk 1]
```diff
@@ -429,6 +429,13 @@ end
             @test_throws BoundsError findprev(pattern, A, -3)
         end
     end
+
+    @test_throws InexactError findfirst(==(UInt8(-1)), [0xff])
+    @test_throws InexactError findnext(==(UInt8(-1)), [0xff], 1)
+    @test_throws InexactError findprev(==(UInt8(-1)), [0xff], 1)
+    @test_throws InexactError findfirst([UInt8(-1)], [0xff])
+    @test_throws InexactError findnext([UInt8(-1)], [0xff], 1)
+    @test_throws InexactError findprev([UInt8(-1)], Union{UInt8, Int8}[0xff], 1)
```
Comment (nhz2) [inline test/strings/search.jl:438]: I think these find functions should return `nothing` if unmatched.

```suggestion
    @test isnothing(findfirst(==(Int8(-1)), [0xff]))
    @test isnothing(findnext(==(Int8(-1)), [0xff], 1))
    @test isnothing(findprev(==(Int8(-1)), [0xff], 1))
    @test isnothing(findfirst([Int8(-1)], [0xff]))
    @test isnothing(findnext([Int8(-1)], [0xff], 1))
    @test isnothing(findprev([Int8(-1)], Union{UInt8, Int8}[0xff], 1))
```

Comment (jakobnissen) [reply test/strings/search.jl:438]: Yes you're right.

**Comment by jakobnissen** [comment]
This is a little more tricky than expected, because there are several issues with the code in this file, so it needs some more work. Also, some decisions might need to be made. Currently:

# THIS IS STILL A WIP

## Larger things that needs decisions
* The internal union `Base.ByteArray` has been deleted. Instead, the unions `DenseInt8` and `DenseUInt8` have been added. These more comprehensively cover the types that was meant, e.g. `Memory{UInt8}` was incorrectly not covered by the former. As stated in the TODO, the concept of a "memory backed dense byte array" is needed throughout Julia, so this ideally needs to be implemented as a single type and used throughout Base. See #53178
* In current Julia, the method `findfirst(::AbstractArray{<:Union{Int8, UInt8}}, ::AbstractArray{<:Union{Int8, UInt8}})` have been specifically documented. This method was buggily implemented. Ideally, this needs to be correctly implemented, such that this is not a breaking change. However, this is a little tricky because it might require rewriting the algorithm.

## Trivial fixes
* `findfirst(==(Int8(-1)), [0xff])` is no longer buggy
* Using `Base.first_utf8_byte` instead of `x::AbstractChar % UInt8` is safer and faster
* `GC.@preserve` was incorrectly used, as the pointer was taken before the preserve block.

File: base/strings/search.jl [hunk 2]
```diff
@@ -10,6 +10,27 @@ match strings with [`match`](@ref).
 """
 abstract type AbstractPattern end
 
+# TODO: These unions represent bytes in memory that can be accessed via a pointer.
+# this property is used throughout Julia, e.g. also in IO code.
+# This deserves a better solution - see #53178.
+# If such a better solution comes in place, these unions should be replaced.
+const DenseInt8 = Union{
+    <:DenseArray{Int8},
+    <:FastContiguousSubArray{Int8,N,<:DenseArray} where N
```
Comment (martinholters) [inline base/strings/search.jl:19]:
```suggestion
    DenseArray{Int8},
    FastContiguousSubArray{Int8,N,<:DenseArray} where N
```

File: base/strings/search.jl [hunk 3]
```diff
@@ -10,6 +10,27 @@ match strings with [`match`](@ref).
...
+}
+
+# Note: This union is different from that above in that it includes CodeUnits.
+# Currently, this is redundant as CodeUnits <: DenseVector, but this subtyping
+# is buggy and may be removed in the future, see #54002
+const DenseUInt8 = Union{
+    <:DenseArray{UInt8},
+    <:FastContiguousSubArray{UInt8,N,<:DenseArray} where N,
+    CodeUnits{UInt8, <:Union{String, SubString{String}}},
+    <:FastContiguousSubArray{UInt8,N,<:CodeUnits{UInt8, <:Union{String, SubString{String}}}} where N,
```
Comment (martinholters) [inline base/strings/search.jl:29]:
```suggestion
    DenseArray{UInt8},
    FastContiguousSubArray{UInt8,N,<:DenseArray} where N,
    CodeUnits{UInt8, <:Union{String, SubString{String}}},
    FastContiguousSubArray{UInt8,N,<:CodeUnits{UInt8, <:Union{String, SubString{String}}}} where N,
```

**Comment by jakobnissen** [comment]
Test failures look unrelated

File: base/strings/search.jl [hunk 4]
```diff
@@ -20,38 +41,48 @@ function findnext(pred::Fix2{<:Union{typeof(isequal),typeof(==)},<:AbstractChar}
...
+# iszero is special, in that the bitpattern for zero for Int8 and UInt8 is the same,
+# so we can use memchr even if we search for an Int8 in an UInt8 array or vice versa
+findfirst(::typeof(iszero), a::DenseUInt8OrInt8) = nothing_sentinel(_search(a, zero(UInt8)))
+findnext(::typeof(iszero), a::DenseUInt8OrInt8, i::Integer) = nothing_sentinel(_search(a, zero(UInt8), i))
+
+function _search(a::Union{String,SubString{String},DenseUInt8OrInt8}, b::Union{Int8,UInt8}, i::Integer = 1)
+    @boundscheck if i < 1
         throw(BoundsError(a, i))
     end
     n = sizeof(a)
```
Comment (nhz2) [inline base/strings/search.jl:74]: Is `sizeof` defined for all `DenseArray{UInt8}`? Should this be `length` for arrays, and `sizeof` for strings?

File: base/strings/search.jl [hunk 5]
```diff
@@ -20,38 +41,48 @@ function findnext(pred::Fix2{<:Union{typeof(isequal),typeof(==)},<:AbstractChar}
...
-    if i > n
+    @boundscheck if i > n
```
Comment (nhz2) [inline base/strings/search.jl:75]: I don't think this can have `@boundscheck` because this `if` block can return zero.

File: base/strings/search.jl [hunk 6]
```diff
@@ -60,41 +91,50 @@ function _search(a::ByteArray, b::AbstractChar, i::Integer = 1)
...
+# See comments above for findfirst(::typeof(iszero)) methods
+findlast(::typeof(iszero), a::DenseUInt8OrInt8) = nothing_sentinel(_rsearch(a, zero(UInt8)))
+findprev(::typeof(iszero), a::DenseUInt8OrInt8, i::Integer) = nothing_sentinel(_rsearch(a, zero(UInt8), i))
 
-function _rsearch(a::Union{String,ByteArray}, b::Union{Int8,UInt8}, i::Integer = sizeof(a))
+function _rsearch(a::Union{String,SubString{String},DenseUInt8OrInt8}, b::Union{Int8,UInt8}, i::Integer = sizeof(a))
     if i < 1
         return i == 0 ? 0 : throw(BoundsError(a, i))
     end
     n = sizeof(a)
```
Comment (nhz2) [inline base/strings/search.jl:126]: Same possible issue with `sizeof` here.

**Comment by nhz2** [comment]
This PR is missing tests for searching different possible `DenseArray`s. For example, a `DenseArray` that has zero based indexing.

**Comment by jakobnissen** [comment]
Thanks for your review. I agree in principle, but there are no offset arrays subtyping densearrays to test against. The existing offset arrays in `test/testhelpers` is 800 lines. Implementing another, slightly different array for test purposes is out of scope, especially considering that no-where else in Base does this.

File: base/strings/search.jl [hunk 7]
```diff
@@ -37,31 +61,41 @@ const DenseBytes = Union{
...
+        return i == lst+1 ? 0 : throw(BoundsError(a, i))
+    end
+    GC.@preserve a begin
+        p = pointer(a)
+        q = ccall(:memchr, Ptr{UInt8}, (Ptr{UInt8}, Int32, Csize_t), p+i-fst, b, n_bytes)
     end
-    p = pointer(a)
-    q = GC.@preserve a ccall(:memchr, Ptr{UInt8}, (Ptr{UInt8}, Int32, Csize_t), p+i-1, b, n-i+1)
-    return q == C_NULL ? 0 : Int(q-p+1)
+    return q == C_NULL ? 0 : (q-p+fst) % Int
```
Comment (nhz2) [inline base/strings/search.jl:95]: Here `0` is being returned as a sentinel value, but `0` may be a valid index, for example, if `q === p ` and `fst == 0`

Comment (jakobnissen) [reply base/strings/search.jl]: Thanks - done.

**Comment by jakobnissen** [comment]
Test failures are unrelated

File: base/strings/search.jl [hunk 8]
```diff
@@ -70,41 +112,52 @@ function _search(a::ByteArray, b::AbstractChar, i::Integer = 1)
...
+findprev(::typeof(iszero), a::DenseUInt8OrInt8, i::Integer) = _rsearch(a, zero(UInt8), i)
 
-function _rsearch(a::Union{String,ByteArray}, b::Union{Int8,UInt8}, i::Integer = sizeof(a))
-    if i < 1
-        return i == 0 ? 0 : throw(BoundsError(a, i))
+function _rsearch(a::Union{String,SubString{String},DenseUInt8OrInt8}, b::Union{Int8,UInt8}, i::Integer = last_byteindex(a))
+    fst = firstindex(a)
+    lst = last_byteindex(a)
+    if i < fst
+        return i == 0 ? nothing : throw(BoundsError(a, i))
```
Comment (nhz2) [inline base/strings/search.jl:147]:
```suggestion
        return i == fst - 1 ? nothing : throw(BoundsError(a, i))
```

File: base/strings/search.jl [hunk 9]
```diff
@@ -70,41 +112,52 @@ function _search(a::ByteArray, b::AbstractChar, i::Integer = 1)
...
+    end
+    n_bytes = lst - i + 1
```
Comment (nhz2) [inline base/strings/search.jl:149]:
```suggestion
```

File: base/strings/search.jl [hunk 10]
```diff
@@ -10,7 +10,39 @@ match strings with [`match`](@ref).
...
+
+function last_utf8_byte(c::Char)
+    u = reinterpret(UInt32, c)
+    shift = ((4 - ncodeunits(c)) * 8) & 31
+    (u >> shift) % UInt8
+end
+
+# Whether the given byte is guaranteed to be the only byte in a Char
+# This holds even in the presence of invalid UTF8
+is_standalone_byte(x::UInt8) = (x < 0x80) | (x > 0xf7)
```
Comment (nhz2) [inline base/strings/search.jl:42]: These functions seem unused.

**Review by nhz2 — CHANGES_REQUESTED** [review]

**Review by nhz2 — APPROVED** [review]

**Comment by jakobnissen** [comment]
Bump

**Comment by jakobnissen** [comment]
Bump

**Comment by jakobnissen** [comment]
Bump - I think this is good to go, and it contains several bugfixes

**Comment by giordano** [comment]
All tests are broken on master because of this PR, I'm going to revert it.

**Comment by nhz2** [comment]
Seems like there was an issue combining this PR and #54593
