### PR TITLE
relax dispatch for the `IteratorSize` method for `Generator`

### LINKED ISSUE #58109: `IteratorSize` incorrect for some subtypes of `Generator`
```julia-repl
julia> collection_of_iterators = [Iterators.map(identity, 3), Iterators.map(sqrt, 3)];

julia> Base.IteratorSize.(collection_of_iterators)
2-element Vector{Base.HasShape{0}}:
 Base.HasShape{0}()
 Base.HasShape{0}()

julia> Base.IteratorSize(eltype(collection_of_iterators))  # incorrect, hits the fallback method
Base.HasLength()
```

There are two correct options for the return type here:
* `HasShape{0}`: precise and accurate
* `SizeUnknown`: imprecise, but still accurate

The fix should be simple, this is the relevant method, just need to relax the dispatch:

https://github.com/JuliaLang/julia/blob/772745beb7d71a68960733b866448d3630b8266f/base/generator.jl#L101-L101

NB: This is perhaps part of a wider issue of `HasLength` not being a correct fallback, but that's a separate topic.

### PR DESCRIPTION
**Pull request by nsajko**
Fixes #58109

### CODE REVIEW

File: base/generator.jl [hunk 1]
```diff
@@ -98,7 +98,7 @@ IteratorSize(::Type{Any}) = SizeUnknown()
 
 IteratorSize(::Type{<:Tuple}) = HasLength()
 IteratorSize(::Type{<:AbstractArray{<:Any,N}})  where {N} = HasShape{N}()
-IteratorSize(::Type{Generator{I,F}}) where {I,F} = IteratorSize(I)
+IteratorSize(::Type{<:Generator{I}}) where {I} = (@isdefined I) ? IteratorSize(I) : SizeUnknown()
```
Comment (fingolfin) [inline base/generator.jl:101]: Apologies for the dumb question, but in which scenario would `@isdefined I` return `false` ?

**Review by fingolfin — APPROVED** [review]

**Comment by nsajko** [comment]
Rebased to get rid of the merge commit. Not sure, but I think the merge commit might have prevented automatic backport.

**Comment by giordano** [comment]
Most PRs are squash-merged, there's no merge commit anyway.

**Comment by nsajko** [comment]
I *think* the autobackport functionality maybe works directly with the PR, not with the squashed commit, though? Again, not sure.
