### PR TITLE
fix bug in serialization of nested anonymous functions across processes

### LINKED ISSUE #19463: Problem with @spawn
The following code gives an `UndefVarError` the first two times the function `foo` is called and then it works.

```jl
julia> addprocs(4)
@every4-element Array{Int64,1}:
 2
 3
 4
 5

julia> @everywhere function foo()

           f1 = () -> begin
               return 1
           end

           f2 = () -> begin
               r1 = @spawn f1()
               r = fetch(r1)
               return r
           end

           f3 = () -> begin
               r1 = @spawn f1()
               r2 = @spawn f2()
               rr1 = fetch(r1)
               rr2 = fetch(r2)
               return rr1 + rr2
           end

           f4 = () -> begin
               r1 = @spawn f1()
               r2 = @spawn f2()
               r3 = @spawn f3()
               rr1 = fetch(r1)
               rr2 = fetch(r2)
               rr3 = fetch(r3)
               return rr1 + rr2 + rr3
           end

           f4()
       end

julia> foo()
ERROR: On worker 4:
On worker 2:
UndefVarError: ##7#23 not defined
 in #6 at ./REPL[2]:8
 in #13 at ./multi.jl:1936
 in #642 at ./multi.jl:1451
 in run_work_thunk at ./multi.jl:1004
 in run_work_thunk at ./multi.jl:1013 [inlined]
 in #617 at ./event.jl:66
 in #remotecall_fetch#626 at ./multi.jl:1073
 in remotecall_fetch at ./multi.jl:1065
 in #remotecall_fetch#629 at ./multi.jl:1086
 in remotecall_fetch at ./multi.jl:1086
 in call_on_owner at ./multi.jl:1159
 in fetch at ./multi.jl:1185
 in #9 at ./REPL[2]:17
 in #20 at ./multi.jl:1936
 in #642 at ./multi.jl:1451
 in run_work_thunk at ./multi.jl:1004
 in run_work_thunk at ./multi.jl:1013 [inlined]
 in #617 at ./event.jl:66
 in #remotecall_fetch#626(::Array{Any,1}, ::Function, ::Function, ::Base.Worker, ::Base.RRID, ::Vararg{Any,N}) at ./multi.jl:1073
 in remotecall_fetch(::Function, ::Base.Worker, ::Base.RRID, ::Vararg{Any,N}) at ./multi.jl:1065
 in #remotecall_fetch#629(::Array{Any,1}, ::Function, ::Function, ::Int64, ::Base.RRID, ::Vararg{Any,N}) at ./multi.jl:1086
 in remotecall_fetch(::Function, ::Int64, ::Base.RRID, ::Vararg{Any,N}) at ./multi.jl:1086
 in call_on_owner(::Function, ::Future, ::Int64, ::Vararg{Int64,N}) at ./multi.jl:1159
 in fetch(::Future) at ./multi.jl:1185
 in (::##14#30{##5#21,##6#22{##5#21},##9#25{##5#21,##6#22{##5#21}}})() at ./REPL[2]:27
 in foo() at ./REPL[2]:31
```
I haven't been able to reproduce the error with `@spawnat`.

### PR DESCRIPTION
**Pull request by amitmurthy**
This fixes https://github.com/JuliaLang/julia/issues/19463

AFAICT the issue was with nested anonymous functions not being serialized across multiple worker boundaries. An anonymous function with nested functions sent from 1 to 2, would deserialize them into `__deserialized_types__`. But when 2 is sending to 3, these would not be sent.

Tests are pending.

### CODE REVIEW

**Comment by amitmurthy** [comment]
AV error is unrelated (libgit2).

@JeffBezanson , a reduced version of the test code is 
```
addprocs(4)
function bar()
    b1 = () -> (println(1);1)
    b2 = () -> (println(2);x=fetch(@spawnat 2 b1());println(2.1);x)
    b3 = () -> (println(3);x=fetch(@spawnat 3 b2());println(3.1);x)
    b4 = () -> (println(4);x=fetch(@spawnat 4 b3());println(4.1);x)
    b4()
end
bar()
```

which fails on master and is fixed by this PR.

File: base/distributed/clusterserialize.jl [hunk 1]
```diff
@@ -88,8 +88,9 @@ function serialize(s::ClusterSerializer, g::GlobalRef)
     # Record if required and then invoke the default GlobalRef serializer.
     sym = g.name
     if g.mod === Main && isdefined(g.mod, sym)
-        v = getfield(Main, sym)
-         if (binding_module(Main, sym) === Main) && (s.anonfunc_id != 0)
+        if (binding_module(Main, sym) === Main) && (s.anonfunc_id != 0) &&
+            !startswith(string(sym), "#") # Anonymous functions are handled via FULL_GLOBALREF_TAG
```
Comment (JeffBezanson) [inline base/distributed/clusterserialize.jl]: Does this need to be a reliable test for non-anonymous-functions?

Comment (amitmurthy) [inline base/distributed/clusterserialize.jl]: My understanding is: 

Merely checking for the symbol starting with `#` covers all hidden bindings under `Main`. As we anyway don't send type definitions, explicitly declared functions, etc, I don't see a problem. Anonymous functions are being handled as a special case in `serialize(s::AbstractSerializer, g::GlobalRef)` via `FULL_GLOBALREF_TAG`.

Comment (JeffBezanson) [inline base/distributed/clusterserialize.jl]: OK. Please add that test case, then this looks good.

**Review by JeffBezanson — APPROVED** [review]

File: base/serialize.jl [hunk 2]
```diff
@@ -437,7 +437,9 @@ function serialize(s::AbstractSerializer, t::Task)
 end
 
 function serialize(s::AbstractSerializer, g::GlobalRef)
-    if g.mod === Main && isdefined(g.mod, g.name) && isconst(g.mod, g.name)
+    if (g.mod === __deserialized_types__ ) ||
+        (g.mod === Main && isdefined(g.mod, g.name) && isconst(g.mod, g.name))
```
Comment (tkelman) [inline base/serialize.jl]: superficial, but I think this would look a little nicer as
```diff
diff --git a/base/distributed/clusterserialize.jl b/base/distributed/clusterserialize.jl
index 9fb256d1e2..a5ed2cca61 100644
--- a/base/distributed/clusterserialize.jl
+++ b/base/distributed/clusterserialize.jl
@@ -89,8 +89,7 @@ function serialize(s::ClusterSerializer, g::GlobalRef)
     sym = g.name
     if g.mod === Main && isdefined(g.mod, sym)
         if (binding_module(Main, sym) === Main) && (s.anonfunc_id != 0) &&
-            !startswith(string(sym), "#") # Anonymous functions are handled via FULL_GLOBALREF_TAG
-
+                !startswith(string(sym), "#") # Anonymous functions are handled via FULL_GLOBALREF_TAG
             push!(get!(s.glbs_in_tnobj, s.anonfunc_id, []), sym)
         end
     end
diff --git a/base/serialize.jl b/base/serialize.jl
index 70f1203d59..caad7e3a0a 100644
--- a/base/serialize.jl
+++ b/base/serialize.jl
@@ -438,8 +438,7 @@ end

 function serialize(s::AbstractSerializer, g::GlobalRef)
     if (g.mod === __deserialized_types__ ) ||
-        (g.mod === Main && isdefined(g.mod, g.name) && isconst(g.mod, g.name))
-
+            (g.mod === Main && isdefined(g.mod, g.name) && isconst(g.mod, g.name))
         v = getfield(g.mod, g.name)
         unw = unwrap_unionall(v)
         if isa(unw,DataType) && v === unw.name.wrapper && should_send_whole_type(s, unw)
```
rather than having a blank line

Comment (amitmurthy) [inline base/serialize.jl]: I am going to let this one be. I find the blank line better.

Comment (tkelman) [inline base/serialize.jl]: Wastes space, and the line continuation looks like it's a normal statement within the block at a glance. Distinguishing it with a different indentation level helps a lot and is done in many other places.
