### PR TITLE
cumsum fixes (fixes #18363 and #18336)

### LINKED ISSUE #18336: cumsum loses the sign of zero imaginary part
```
julia> cumsum(1.7 - 0.0im + (0:7))
8-element Array{Complex{Float64},1}:
  1.7+0.0im
  4.4+0.0im
  8.1+0.0im
 12.8+0.0im
 18.5+0.0im
 25.2+0.0im
 32.9+0.0im
 41.6+0.0im
```
(I would have expected `-0.0im` imaginary parts.)

Similarly for `cumprod`.

### LINKED ISSUE #18363: cumsum! does not check array sizes
```
julia> cumsum!([0,0], 1:4)

signal (11): Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by stevengj**
This fixes JuliaLang/julia#18336 and JuliaLang/julia#18363 — there were an embarrassing number of problems with `cumsum` and `cumprod` for corner cases.  (My fault, I think, since I wrote this routine back in JuliaLang/julia#4039.)

The breaking change is that `cumsum(v)` now uses `similar(v, rcum_promote_type(+, eltype(v)))` rather than the broken `_cumsum_type(v)` function, where `rcum_promote_type` is a new function that calls `promote_op` for numbers but which leaves most other types alone.   I don't think this should change any working cases for `cumsum` of numeric types, but it might break some unusual user-defined types in which `+` produces a different type.

(The user can still control the result type manually by passing an array to `cumsum!`, however.)

### CODE REVIEW

**Comment by stevengj** [comment]
Also fixes #13244.

**Comment by stevengj** [comment]
(I thought about using `r_promote` or similar to widen the `cumsum` result.   However, widening makes more sense for a `reduce` operation, where you are only widening a single scalar result, than in a function like this where you are allocating a whole array.   Also, the user can always widen manually if desired by passing the desired array type to `cumsum!`, unlike `reduce`.)

**Comment by stevengj** [comment]
As @andreasnoack pointed out, this does not produce the expected result for `Bool` arrays, so maybe we should use something like `r_promote` after all.

I'm conflicted on whether we should widen a sum of, say `UInt16`, though.

**Comment by stevengj** [comment]
Okay, updated it to use the same type as `sum`.  It just seems easier to understand if we are consistent.

File: base/arraymath.jl [hunk 1]
```diff
@@ -472,12 +469,16 @@ for (f, f!, fp, op) = ((:cumsum, :cumsum!, :cumsum_pairwise!, :+),
     @eval function ($f!)(result::AbstractVector, v::AbstractVector)
         n = length(v)
         if n == 0; return result; end
-        ($fp)(v, result, $(op==:+ ? :(zero(first(v))) : :(one(first(v)))), first(indices(v,1)), n)
+        li = linearindices(v)
```
Comment (timholy) [inline base/arraymath.jl]: Best would be to have `n = length(li)` since that's guaranteed to work even if `v` has non-1 indices.

Comment (stevengj) [inline base/arraymath.jl]: Doesn't `length(v)` return the number of elements in the array regardless?  Or is `length(v)` equivalent to `last(linearindices(v))`?  The latter would seem odd to me.

Comment (stevengj) [inline base/arraymath.jl]: Ah, I see that the `length` documentation says it returns "For ordered, indexable collections, the maximum index i for which getindex(collection, i) is valid."

Okay, changed it to `length(li)` as you suggest.   It still seems strange to me.

(Note also that this `cumsum` method is only for `AbstractVector`, and the `length` documentation says that it "Returns the number of elements in A." for any `AbstractArray`.)

**Comment by StefanKarpinski** [comment]
Slightly tangential but I really think we should probably make Bool
non-numeric like Char.

**Comment by TotalVerb** [comment]
I agree with @StefanKarpinski. There really ought to be a `F2` type to model the integers mod 2 (a field that's small enough to promote upward to any other type) to replace the current `Bool` hackery.

File: base/arraymath.jl (hunk 1 above)
Comment (timholy) [inline base/arraymath.jl]: http://docs.julialang.org/en/latest/devdocs/offset-arrays/#background

Though if this isn't to be backported, then perhaps you could just stick with the original, since the situation with `length` is just for 0.5. However, packages probably haven't started preparing for 0.6 yet, so they may not support `length` yet for unconventional arrays.

**Comment by stevengj** [comment]
Seems like a random Travis timeout on OSX.  I'll try restarting CI.  (Is there a way to just restart Travis?)

**Comment by stevengj** [comment]
Darn it, now Travis is succeeding but one of the AppVeyor builds is timing out.  These random CI failures are really frustrating.

**Comment by tkelman** [comment]
You can restart specific CI services through their UI. I also request that you please make a backup of travis failure logs to a gist before restarting, as restarted builds there overwrite previous logs.

**Comment by tkelman** [comment]
> I'm conflicted on whether we should widen a sum of, say `UInt16`, though.

I'd much rather not widen `UInt16` or `UInt8` or `Float16` arrays in `cumsum`, if I'm using an array of that type I am probably doing so because I want to reduce the memory usage. For reductions to a smaller output size this is less important (and the overflow prevention more worth the tradeoff) than something that returns an array of the same size as its input.

**Comment by stevengj** [comment]
@tkelman, okay, so it should just use `typeof(zero(T)+zero(T))` for `T<:Number`?

**Comment by tkelman** [comment]
I think that sounds sane. I'm not sure which corner cases the current `typeof(+zero(T))` for `Number` and
`typeof(v[1]+v[1])` otherwise are intended to address. There might be non-`Number` types where addition results in a different type, but those could be tricky to deal with.

**Comment by andreasnoack** [comment]
`typeof(zero(T)+zero(T))` is not correct. See https://github.com/JuliaLang/julia/issues/14237. Why not `promote_op(+,T,S)`?

**Comment by stevengj** [comment]
@tkelman, the main current corner case seems to be `Bool`, which gets promoted to `Int`.

@andreasnoack, `promote_op(+,T,S)` seems fine, although `promote_op` seems like it might go away at some point.

**Comment by stevengj** [comment]
Hmm, no, it looks like `promote_op` is too conservative about falling back to `Any`.  e.g. `Base.promote_op(+, Vector{Int}, Vector{Int})` returns `Any`.  I guess I could only use `promote_op` for `T<:Number`.

**Comment by stevengj** [comment]
Hmm, also need to handle `cumsum` of `Vector{Vector{Bool}}` and similar, grr.

**Comment by stevengj** [comment]
Okay, the new behavior should be more consistent with the old `cumsum` in not widening numeric types (except `Bool`).

**Comment by stevengj** [comment]
Better?

File: base/arraymath.jl [hunk 2]
```diff
@@ -470,14 +476,18 @@ for (f, f!, fp, op) = ((:cumsum, :cumsum!, :cumsum_pairwise!, :+),
     end
 
     @eval function ($f!)(result::AbstractVector, v::AbstractVector)
-        n = length(v)
+        li = linearindices(v)
+        li != linearindices(result) && throw(BoundsError())
```
Comment (timholy) [inline base/arraymath.jl]: Should this be an `DimensionMismatch` and include a helpful message about the nature of the problem?

**Comment by timholy** [comment]
Aside from one small comment, LGTM.

File: base/arraymath.jl (hunk 1 above)
Comment (JeffBezanson) [inline base/arraymath.jl]: I think the definition/documentation for `length` should be revisited. It makes more sense to me for it to always return an element count, and have nothing to do with indices. The docs should say "returns the number of elements generated by an iterator".

File: base/arraymath.jl (hunk 2 above)
Comment (stevengj) [inline base/arraymath.jl]: ok

Comment (timholy) [inline base/arraymath.jl]: Great. Test needs to change too.

Comment (stevengj) [inline base/arraymath.jl]: whoops, right.

File: base/arraymath.jl [hunk 3]
```diff
@@ -446,8 +446,14 @@ ctranspose{T<:Real}(A::AbstractVecOrMat{T}) = transpose(A)
...
-_cumsum_type{T<:Number}(v::AbstractArray{T}) = typeof(+zero(T))
-_cumsum_type(v) = typeof(v[1]+v[1])
+# see discussion in #18364 ... we try not to widen type of the resulting array
+# from cumsum or cumprod, but in some cases (+, Bool) we may not have a choice.
+rcum_promote_type{T<:Number}(op, ::Type{T}) = promote_op(op, T)
+rcum_promote_type{T}(op, ::Type{T}) = T
+
+# handle sums of Vector{Bool} and similar.   it would be nice to handle
+# any AbstractArray here, but it's not clear how that would be possible
+rcum_promote_type{T,N}(op, ::Type{Array{T,N}}) = Array{rcum_promote_type(op,T), N}
```
Comment (pabloferz) [inline base/arraymath.jl]: I think you can do

```julia
rcum_promote_type{T}(op, ::Type{T}) = promote_eltype_op(op, T)
rcum_promote_type{T}(op, ::Type{Array{T,N}) = Array{rcum_promote_type(op, T), N}
```

without specializing for `Number`

Comment (stevengj) [inline base/arraymath.jl]: `promote_eltype_op` gives the wrong answers for non-`Number` arguments anyway.  e.g. it gives `Base.promote_eltype_op(+, Vector{Real}) --> Real` when I want `Vector{Real}`.

Comment (pabloferz) [inline base/arraymath.jl]: Yeah, that's why I left the second definition. Maybe some day if we have triangular dispatch or something like that.

**Comment by StefanKarpinski** [comment]
This is a (minor) breaking change, but the previous behavior could be argued to be buggy. Should we consider backporting this fix?

**Comment by stevengj** [comment]
I would say the odds of this breaking someone's code is pretty low.   About the only cases that should actually break would be `cumsum` of an array of non-`Array` collections of `Bool`, or `cumsum` of a non-`Number` type for which `+` produces a different type.   I doubt there are any actual examples of such code in the wild.
