### PR TITLE
Fix underlines in cmd printing

### LINKED ISSUE #25589: Special underline printing for commands disappeared
The code is still there, but looks like the new way to do coloration broke it:
https://github.com/JuliaLang/julia/blob/master/base/process.jl#L105-L111
```
`curl abc`
```
should have underlines under the command parts.

### PR DESCRIPTION
**Pull request by Keno**
Fixes #25589

### CODE REVIEW

File: base/process.jl [hunk 1]
```diff
@@ -103,7 +103,7 @@ function show(io::IO, cmd::Cmd)
     (print_env || print_dir) && print(io, "setenv(")
     print(io, '`')
     print(io, join(map(cmd.exec) do arg
```
Comment (vtjnash) [inline base/process.jl]: Should be `join(io,)`, not `print(io, join(,))`

**Review by vtjnash — APPROVED** [review]
