### PR TITLE
avoid calling `check_ambiguous_matches` when trying to add same Method

### LINKED ISSUE #23456: check_ambiguous_visitor Assertion failure
Steps to reproduce on latest master:
```julia
Pkg.clone("CategoricalArrays"); using CategoricalArrays
```

My output:
```julia
julia> using CategoricalArrays
INFO: Recompiling stale cache file /Users/jacobquinn/.julia/lib/v0.7/CategoricalArrays.ji for module CategoricalArrays.
Assertion failed: (!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)), function check_ambiguous_visitor, file /Users/jacobquinn/julia/src/gf.c, line 1128.

signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 10101350 (Pool: 10099217; Big: 2133); GC: 16
Abort trap: 6
```
FWIW, I tried on the current `jq/bitsunions` branch as well and got the same result (not that this is necessarily related, but I happened to be on the branch when I first saw the bug).

### PR DESCRIPTION
**Pull request by JeffBezanson**
I believe #24083 might have fixed part of #23456 --- after that the assertion `assert(closure->after)` in `check_ambiguous_visitor` fails for me instead. That seems to happen because the method list for the precompiled NullableArrays package has two references to `Base.:(==)(Base.Nullable{S}, Base.Nullable{T}) where T where S`. When we try to add the same method again, `jl_method_table_insert` calls `check_ambiguous_matches`, which doesn't expect to be called on a signature already in the table.

Should fix #23456.

### CODE REVIEW

File: src/gf.c [hunk 1]
```diff
@@ -1420,6 +1420,12 @@ JL_DLLEXPORT void jl_method_table_insert(jl_methtable_t *mt, jl_method_t *method
             (jl_tupletype_t*)type, simpletype, jl_emptysvec, (jl_value_t*)method, 0, &method_defs,
             method->min_world, ~(size_t)0, &oldvalue);
     if (oldvalue) {
+        if (oldvalue == (jl_value_t*)method) {
+            // redundant add of same method; no need to do anything
```
Comment (vtjnash) [inline src/gf.c]: Sounds like a bug elsewhere? There should be a one-to-one relation between jl_new_method and jl_method_table_insert to avoid corruption.

Comment (JeffBezanson) [reply src/gf.c]: I thought that might be the case. There were definitely two references to the same method in the list argument to `jl_insert_methods`. We can look into that. I still think this change makes sense as a defensive measure though.

**Review by vtjnash — APPROVED** [review]
