### PR TITLE
throw ArgumentError when accessing an invalid UTF-8 indice, rather th…

### LINKED ISSUE #7811: SubString{UTF8String} and UTF8String have different slicing behaviour
Found this on [stackoverflow](http://stackoverflow.com/q/25082347/112019)

```jlcon
julia> a = "æøå"
"æøå"

julia> a[2:end]
"øå"

julia> b = SubString(a,1)
"æøå"

julia> b[2:end]
ERROR: invalid SubString indexes
 in getindex at ./string.jl:657
```
I'm not sure what the correct behaviour should be, but having them different seems wrong. Some relevant discussion in https://github.com/JuliaLang/julia/issues/5446

### PR DESCRIPTION
**Pull request by tkelman**
…an attempting to adjust it. fix #7811 

cc @vtjnash (any changes to make here? it's your branch, i'm just turning it into a PR) @scottpjones

### CODE REVIEW

**Comment by ScottPJones** [comment]
:+1:

**Comment by vtjnash** [comment]
I had just forotten about this. It should be fine to merge

**Comment by tkelman** [comment]
I'm not really qualified to hit merge on anything unicode-related, could someone else review and merge if you agree?

File: base/string.jl [hunk 1]
```diff
@@ -185,10 +185,9 @@ function search(s::AbstractString, c::Chars, i::Integer)
         return 1 <= i <= nextind(s,endof(s)) ? i :
                throw(BoundsError(s, i))
     end
-    if i < 1
+    if i < 1 || i > nextind(s,endof(s))
```
Comment (nalimilan) [inline base/string.jl]: Doesn't look like you're catching all invalid indices here, are you? Shouldn't this be `i > endof(s)`?
```julia
julia> s = "café"
"café"

julia> nextind(s,endof(s))
6

julia> s[5]
ERROR: ArgumentError: invalid UTF-8 character index
 in next at ./utf8.jl:80
 in getindex at string.jl:62
```

File: base/utf8.jl [hunk 2]
```diff
@@ -112,8 +103,11 @@ function getindex(s::UTF8String, r::UnitRange{Int})
     isempty(r) && return empty_utf8
     i, j = first(r), last(r)
     d = s.data
+    if i < 1 || i > length(s.data)
```
Comment (nalimilan) [inline base/utf8.jl]: Same here?
```julia
julia> s = "café"
"café"

julia> length(s.data)
5

julia> s[5]
ERROR: ArgumentError: invalid UTF-8 character index
 in next at ./utf8.jl:80
 in getindex at string.jl:62
```

Comment (nalimilan) [inline base/utf8.jl]: Ah, got it, you count on `is_utf8_start(d[i])` to catch other cases below. As you like.

File: base/dates/io.jl [hunk 3]
```diff
@@ -100,12 +100,12 @@ slotparse(slot::Slot{Millisecond},x) = !ismatch(r"[^0-9\s]",x) ? slot.period(Bas
 slotparse(slot::Slot{DayOfWeekSlot},x) = nothing
 
 function getslot(x,slot::DelimitedSlot,df,cursor)
-    endind = first(search(x,df.trans[slot.i],cursor+1))
+    endind = first(search(x,df.trans[slot.i],nextind(x,cursor)))
```
Comment (nalimilan) [inline base/dates/io.jl]: Thanks, this kind of silent assumption is particularly nasty. I think I have uncovered some of these in my string index branch.

**Comment by nalimilan** [comment]
From what I can tell it's OK (but I may have missed details). Regarding my remarks about bounds checking, do as you prefer!

File: base/utf8.jl (hunk 2 above)
Comment (vtjnash) [inline base/utf8.jl]: Yeah, would probably be clearer and faster to write that as sizeof(s), since this is a boundscheck, not a UTF8 validation.

File: base/ascii.jl [hunk 4]
```diff
@@ -17,7 +17,11 @@ sizeof(s::ASCIIString) = sizeof(s.data)
 getindex(s::ASCIIString, r::Vector) = ASCIIString(getindex(s.data,r))
 getindex(s::ASCIIString, r::UnitRange{Int}) = ASCIIString(getindex(s.data,r))
 getindex(s::ASCIIString, indx::AbstractVector{Int}) = ASCIIString(s.data[indx])
-search(s::ASCIIString, c::Char, i::Integer) = c < Char(0x80) ? search(s.data,c%UInt8,i) : 0
+function search(s::ASCIIString, c::Char, i::Integer)
+    i == sizeof(s) + 1 && return 0
+    (i < 1 || i > sizeof(s)) && throw(BoundsError(s, i))
+    return c < Char(0x80) ? search(s.data,c%UInt8,i) : 0
+end
 rsearch(s::ASCIIString, c::Char, i::Integer) = c < Char(0x80) ? rsearch(s.data,c%UInt8,i) : 0
```
Comment (ScottPJones) [inline base/ascii.jl]: Why doesn't this also do the bounds checking that was added for search?  Is it handled in the other rsearch method?
I think the bounds check needs to be done *before* you return 0 (for `c < 0x80`)

File: base/dates/io.jl (hunk 3 above)
Comment (ScottPJones) [inline base/dates/io.jl]: I'm not sure I understand this... will nextind silently skip over UTF-8 continuation characters? (not a good thing)

Comment (StefanKarpinski) [inline base/dates/io.jl]: Yes, that's the whole point of nextind and prevind – they exist so that you can find where the next valid character index is.

Comment (ScottPJones) [inline base/dates/io.jl]: So, wouldn't the code in io.jl be better as it was before, now that the error will be thrown in search?

Comment (nalimilan) [inline base/dates/io.jl]: No, this line was assuming that the string it index was ASCII, while what we want is the next Unicode codepoint. (This code is not working with the internals of the string, it just needs to access its characters via the high-level API.)

**Comment by ScottPJones** [comment]
Anybody concerned about the issue in rsearch?

**Comment by ScottPJones** [comment]
@tkelman :grinning: How about addressing the issues I raised reviewing *your* PR?  Seriously, it would be nice to get these sorts of fixes in...

**Comment by tkelman** [comment]
I don't actually know anything about what this code is doing. I just wanted to ping @vtjnash by opening this so he wouldn't forget about it.

**Comment by ScottPJones** [comment]
Oh, sorry, I saw the "Author" tag, and had forgotten that you'd just put his branch into a PR...

**Comment by jiahao** [comment]
> @tkelman :grinning: How about addressing the issues I raised reviewing *your* PR?

@ScottPJones kindly respect others' time by not pinging them frivolously. This is a borderline violation of our [community standards](http://julialang.org/community/standards/), viz. 

> Be aware that most community members contribute on a voluntary basis, so ideas and bug reports are ok, but demands are not.

**Comment by vtjnash** [comment]
> Anybody concerned about the issue in rsearch?

yes, but i was not prepared when making this PR to extend it further and test rsearch as well. that should be a separate commit, and perhaps a separate PR anyways.

**Comment by ScottPJones** [comment]
@jiahao That was NOT a frivolous ping.   It was simply an *honest* mistake, pinging tkelman instead of vtjnash, because of the line at the top: "tkelman wants to merge...", which I'd already said I was sorry for.  *Your* ping could be considered frivolous, OTOH...
@vtjnash OK, that makes sense to do it in another PR, but you didn't address the other issue I raised:
>I think the bounds check needs to be done before you return 0 (for c < 0x80)

**Comment by vtjnash** [comment]
@ScottPJones it is counterproductive to try to point blame back at another volunteer in the community.

> I think the bounds check needs to be done before you return 0 (for c < 0x80)

Is this in the context of rsearch? I believe I covered this case for search.

i'm definitely trying to get back to the PR, but still trying to get caught back up on everything else right now.

**Comment by ScottPJones** [comment]
@vtjnash I wasn't trying to "point blame".  I *was* a bit taken aback by being told it was a "frivolous" ping, when pinging tkelman... which was an honest mistake, because it was he who *brought* me into this thread in the first place!  I just wanted him to remember this issue, since nobody had responded to my comment here, and he was in contact with me constantly on a couple other threads, reviewing the Unicode PRs I've been trying to get in. Hence the smiley face.  If I'd known that this PR was really you, I wouldn't have said anything, assuming you could be too busy to respond yet.

Looking again at it (and not from on my phone), that is rsearch, you have taken care of it for search.
rsearch will need to be fixed another day.

**Comment by tkelman** [comment]
Arguing about pinging back and forth is indeed unproductive. Given the new unicode error handling framework from #11573, the patch in this PR would need to be adapted to fit into it to resolve the conflict.

**Comment by vtjnash** [comment]
> Given the new unicode error handling framework from #11573, the patch in this PR would need to be adapted to fit into it to resolve the conflict.

I've pushed an update for that.

> Why doesn't this also do the bounds checking that was added for search? Is it handled in the other rsearch method?

afaict, none of the rsearch methods do this. also, as a breadcrumb, i have not attempted to add validation the endpoint index passed to a few of these methods (`getindex(s::UTF8String, r::UnitRange{Int})` or `SubString`)

**Comment by ScottPJones** [comment]
Ok, good point about the other places lacking validation. :+1: to this change

**Comment by ScottPJones** [comment]
I think I see a problem with part of this change, in `next()`, where it now simply gives an index error if it is not at a valid UTF-8 starting character.  The problem is, since strings are not validated in Julia, that the index might have hit a Latin1 character, for example, and then get an invalid index error, instead of skipping the bad byte, and returning a `0xfffd` replacement character, as it does elsewhere, [or give an invalid character error].
