### PR TITLE
Slightly loosen a test so that linalg tests pass when using MKL

### LINKED ISSUE #88: 3 failing linear algebra tests
As discovered in #87, we have 3 failing linear algebra tests when using MKL. The linear algebra tests in base Julia should be updated to avoid these MKL failures. 

```
generic_matvecmul: Test Failed at /Users/viral/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:155
  Expression: mul!(C, vf, transpose(vf), 2, 3) == (2vf) * vf' .+ 3C0
   Evaluated: [2.9837043345199064 5.899929255539283 6.651392023016039; 6.025562250935813 10.38960512791965 14.658917816045047; 6.276549958989374 12.258712347100156 19.724949794054112] == [2.9837043345199064 5.899929255539283 6.651392023016039; 6.025562250935813 10.389605127919651 14.658917816045047; 6.276549958989374 12.258712347100156 19.724949794054112]
Stacktrace:
 [1] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:155 [inlined]
 [3] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
 [4] top-level scope
   @ ~/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:137
generic_matvecmul: Test Failed at /Users/viral/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:155
  Expression: mul!(C, vf, transpose(vf), 2, 3) == (2vf) * vf' .+ 3C0
   Evaluated: [2.4338804716044002 6.514890604092303 8.24149867094044; 6.180853707653564 10.593462538455617 12.90060330723743; 7.2628537427846185 13.824800166483692 19.869377858505533] == [2.4338804716044002 6.514890604092303 8.24149867094044; 6.180853707653565 10.593462538455617 12.90060330723743; 7.2628537427846185 13.824800166483692 19.869377858505533]
Stacktrace:
 [1] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:155 [inlined]
 [3] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
 [4] top-level scope
   @ ~/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:137
generic_matvecmul: Test Failed at /Users/viral/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:155
  Expression: mul!(C, vf, transpose(vf), 2, 3) == (2vf) * vf' .+ 3C0
   Evaluated: [4.0994828031796935 4.431945420994351 6.995323239689444; 5.179671893950673 9.651778006305165 13.96059811500117; 7.957265202880356 13.814745672222667 18.528518999229213] == [4.0994828031796935 4.431945420994351 6.995323239689444; 5.1796718939506725 9.651778006305165 13.96059811500117; 7.957265202880356 13.814745672222667 18.528518999229213]
Stacktrace:
 [1] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:155 [inlined]
 [3] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
 [4] top-level scope
   @ ~/Desktop/Julia_Releases/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/test/matmul.jl:137
```

### PR DESCRIPTION
**Pull request by ViralBShah**
Fixes https://github.com/JuliaLinearAlgebra/MKL.jl/issues/88

The MKL.jl tests have now been updated to run the entire LinearAlgebra test suite. Thus, when PkgEval runs its tests, it will be nice to see that MKL.jl tests fully pass. In order for that to happen, we want to have this PR merged and included in 1.7 as well (in the next RC).

### CODE REVIEW

File: stdlib/LinearAlgebra/test/matmul.jl [hunk 1]
```diff
@@ -152,7 +152,7 @@ end
     for vf in (copy(vvf), view(vvf, 1:3)), C in (copy(CC), view(CC, 1:3, 1:3))
         @test mul!(C, vf, transpose(vf)) == vf*vf'
         C .= C0 = rand(eltype(C), size(C))
-        @test mul!(C, vf, transpose(vf), 2, 3) == 2vf*vf' .+ 3C0
+        @test mul!(C, vf, transpose(vf), 2, 3) ≈ 2vf*vf' .+ 3C0
```
Comment (andreasnoack) [inline stdlib/LinearAlgebra/test/matmul.jl:155]: I'm wondering if this was exact equality for a reason, cc @tkf

Comment (ViralBShah) [reply stdlib/LinearAlgebra/test/matmul.jl:155]: The difference is `1e-15` in one of the elements. 3 of these tests fail with MKL.

**Comment by DilumAluthge** [comment]
I wonder if there's a way that we could keep this test as exact equality by default, and only switch to approximate equality if the backend is MKL.

**Comment by KristofferC** [comment]
Isn't approximate equality what you would expect?

**Review by KristofferC — APPROVED** [review]

**Comment by ViralBShah** [comment]
> Isn't approximate equality what you would expect?

I was surprised to see exact equality in that test. I would expected it to be approximate.

> I wonder if there's a way that we could keep this test as exact equality by default, and only switch to approximate equality if the backend is MKL.

I don't think it is worthwhile. We'll want to add support for Accelerate too (see the M1 issues) and what not. It would be much nicer to have a test suite that passes on all BLAS. The tolerances are quite stringent.

File: stdlib/LinearAlgebra/test/matmul.jl (hunk 1 above)
Comment (andreasnoack) [reply stdlib/LinearAlgebra/test/matmul.jl:155]: In the test above, I think the idea is that it should be the exact same code path and therefore exact equality. It wasn't obvious to me that this test should take the same path for right and left hand side but wondered if that was your intention. If not then this PR should be fine.

Comment (tkf) [reply stdlib/LinearAlgebra/test/matmul.jl:155]: Yeah, sorry, I was sloppy. This change LGTM too.

**Comment by ViralBShah** [comment]
Marking as backport for both 1.6 and 1.7, so that MKL tests could in theory pass on both.
