### PR TITLE
[JuliaLowering] Fix identifier -> GlobalRef conversion

### LINKED ISSUE #174: `QuoteNode(::GlobalRef)` becomes `Symbol` during macro-expansion
```julia
macro gr1()
    return QuoteNode(GlobalRef(Base, :foo))
end
println(@gr1())
println(typeof(@gr1())) # Symbol, should be GlobalRef
```

Probably a missing reverse conversion from https://github.com/JuliaLang/julia/pull/61410.

This has caused `@invokelatest` to regress again, which can be hit pretty easily by typing `<backspace>` in the REPL Pkg prompt.

### PR DESCRIPTION
**Pull request by topolarity**
This fixes the `@invokelatest` macro.

This is a somewhat blind fix without understanding the broader structure of `compat.jl`, so let me know if I'm in the wrong direction @mlechu. Resolves https://github.com/JuliaLang/JuliaLowering.jl/issues/174.

### CODE REVIEW

File: JuliaLowering/src/compat.jl [hunk 1]
```diff
@@ -450,7 +450,7 @@ function est_to_dst(st::SyntaxTree)
                 r3 -> @ast g st [K"." rec(l) r3]
             end
         end
-        [K"inert" [K"Identifier"]] -> @ast g st st[1]=>K"Symbol"
+        ([K"inert" [K"Identifier"]], when=!hasattr(st[1], :mod)) -> @ast g st st[1]=>K"Symbol"
         # [K"quote" [K"Identifier"]] -> @ast g st st[1]=>K"Symbol"
```
Comment (mlechu) [inline JuliaLowering/src/compat.jl]:
```suggestion
```
Can clean this dead code I've left; `quote` should be gone (and https://github.com/JuliaLang/JuliaLowering.jl/issues/168 should be handled) during macro expansion.

File: JuliaLowering/test/macros.jl [hunk 2]
```diff
@@ -881,3 +881,26 @@ end
...
+Base.include_string(test_mod, raw"""
+function test_invokelatest()
+    @eval test_mod invokelatest_target(x, y) = x + y
+    @invokelatest(invokelatest_target(1, 2))
+end
+""")
+
+@testset "Base macros" begin
+    @test test_invokelatest() === 3
+end
```
Comment (mlechu) [inline JuliaLowering/test/macros.jl]:
```suggestion
@testset "invokelatest" begin
    jl_eval(test_mod,
            :(function test_invokelatest()
                  @eval invokelatest_target(x, y) = x + y
                  out = @invokelatest(invokelatest_target(1, 2))
                  Base.delete_binding(@__MODULE__, :invokelatest_target)
                  out
              end))

    # the following test needs to define this to be effective
    @test_throws UndefVarError JuliaLowering.include_string(test_mod, "invokelatest_target(1,2)")
    @test JuliaLowering.include_string(test_mod, "test_invokelatest()") === 3
end

```

Just to hit JL and make the test re-runnable

Comment (topolarity) [reply JuliaLowering/test/macros.jl]: Doesn't the macro get expanded by `fl_eval` then?

**Review by mlechu — APPROVED** [review]
Thanks for the fix!

File: JuliaLowering/test/macros.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/test/macros.jl]: Correct, edited

Comment (topolarity) [reply JuliaLowering/test/macros.jl]: Good fixes, thanks
