### PR TITLE
cache compile dep tracking

### LINKED ISSUE #18069: precompile loads the wrong library after recompile_stale
the return value of `compilecache` is being ignored by `recompile_stale`, leading to state corruption and loading of the wrong file:

```julia
juser@juliabox:~$ /opt/julia-0.4.6/bin/julia                                                                                                                           
               _
   _       _ _(_)_     |  A fresh approach to technical computing                                                                                                      
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org                                                                                                     
   _ _   _| |_  __ _   |  Type "?help" for help.                                                                                                                       
  | | | | | | |/ _` |  |                                                                                                                                               
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)                                                                                                         
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release                                                                                                       
|__/                   |  x86_64-unknown-linux-gnu                                                                                                                     
                                                                                                                                                                       
julia> using JSON                                                                                                                                                      
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/JSON.ji for module JSON.                                                                        
                                                                                                                                                                       
julia> Base.module_uuid(JSON)                                                                                                                                          
0x0000000000096afb                                                                                                                                                     
                                                                                                                                                                       
julia>                                                                                                                                                                 
juser@juliabox:~$ /opt/julia-0.4.6/bin/julia                                                                                                                           
               _
   _       _ _(_)_     |  A fresh approach to technical computing                                                                                                      
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org                                                                                                     
   _ _   _| |_  __ _   |  Type "?help" for help.                                                                                                                       
  | | | | | | |/ _` |  |                                                                                                                                               
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)                                                                                                         
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release                                                                                                       
|__/                   |  x86_64-unknown-linux-gnu                                                                                                                     
                                                                                                                                                                       
julia> using JSON                                                                                                                                                      
                                                                                                                                                                       
julia> Base.module_uuid(JSON)                                                                                                                                          
0x000000001644d120                                                                                                                                                     
```

### PR DESCRIPTION
**Pull request by vtjnash**
This implements the dependency tracking for compilecache that I was envisioning from the beginning. The idea here is to not only fix #18069 (the first commit), but also to make sure the situation seen on JuliaBox can't happen. Instead, it will prefer using a stale cache over replacing it with one that can't be loaded into the current session. In a different (new) session, it will rebuild the whole cache as normal.

For example, after this PR, the following works, whereas in the existing design, loading FixedPointNumbers would require first calling `reload(:Compat)`:

```
julia> using Compat
shell> touch ~/.julia/v0.6/Compat/src/Compat.jl
julia> using FixedPointNumbers # needs Compat
```

### CODE REVIEW

File: base/loading.jl [hunk 1]
```diff
@@ -556,42 +585,61 @@ module_uuid(m::Module) = ccall(:jl_module_uuid, UInt64, (Any,), m)
...
+        for (mod, uuid) in _concrete_dependencies
+            if get(modules, mod, UInt64(0)) === uuid
+                provides_concrete = true
+            else
+                return false # cachefile doesn't provide the required version of the dependency
+            end
+        end
+        provides_concrete && return false # this is the file we want
+
+        # now check if this file is fresh relative to it's source files
```
Comment (tkelman) [inline base/loading.jl]: its

File: base/loading.jl [hunk 2]
```diff
@@ -511,73 +585,72 @@ module_uuid(m::Module) = ccall(:jl_module_uuid, UInt64, (Any,), m)
 
 isvalid_cache_header(f::IOStream) = 0 != ccall(:jl_read_verify_header, Cint, (Ptr{Void},), f.ios)
 
-function cache_dependencies(f::IO)
```
Comment (tkelman) [inline base/loading.jl]: this wasn't exported, but renaming it will break AWSLambda.jl

File: base/loading.jl [hunk 3]
```diff
@@ -511,73 +585,72 @@ module_uuid(m::Module) = ccall(:jl_module_uuid, UInt64, (Any,), m)
...
     while true
         n = ntoh(read(f, Int32))
         n == 0 && break
+        totbytes -= 4 + n + 8
+        if n < 0 # probably means this wasn't a valid file to be read by Base.parse_cache_header
+            error("EOF while reading cache header")
+        end
         push!(files, (String(read(f, n)), ntoh(read(f, Float64))))
     end
+    @assert totbytes == 4
```
Comment (tkelman) [inline base/loading.jl]: better error? if this goes wrong it'll be a pain to debug

**Comment by tkelman** [comment]
Please elaborate in some comments what is meant by "concrete dependency." That term is used many times here but not explained at all.

**Comment by ViralBShah** [comment]
@tkelman We will need a new release of 0.4 based on this - perhaps this and any other things can form the basis of a final 0.4 release. 

For now, we have a temporary workaround on JuliaBox.

**Comment by ViralBShah** [comment]
Cc @nkottary @tanmaykm

File: base/loading.jl (hunk 2 above)
Comment (vtjnash) [inline base/loading.jl]: I also changed what it does, since Base doesn't need this functionality. I can put back `cache_dependencies` with some tests and just not export it since looking at AWSLambda.jl, it looks like it was using it correctly.

File: base/loading.jl [hunk 4]
```diff
@@ -126,60 +126,72 @@ function find_source_file(file::String)
...
         if isfile_casesensitive(path)
             push!(paths, path)
         end
     end
-    paths
+    return paths
 end
 
+# these return either the array of modules loaded from the path / content given
+# an Exception that describes why it couldn't be loaded
```
Comment (tkelman) [inline base/loading.jl]: or an Exception ?

File: base/loading.jl [hunk 5]
```diff
@@ -494,14 +551,38 @@ end
 compilecache(mod::Symbol) = compilecache(string(mod))
 function compilecache(name::String)
     myid() == 1 || error("can only precompile from node 1")
+    # decide where to get the source from from
```
Comment (tkelman) [inline base/loading.jl]: source file from?

File: base/loading.jl (hunk 2 above)
Comment (tkelman) [inline base/loading.jl]: it needs to not be breaking if it's going to be backported

File: base/loading.jl [hunk 6]
```diff
@@ -511,26 +592,55 @@ module_uuid(m::Module) = ccall(:jl_module_uuid, UInt64, (Any,), m)
...
     while true
         n = ntoh(read(f, Int32))
         n == 0 && break
+        totbytes -= 4 + n + 8
+        if n < 0 # probably means this wasn't a valid file to be read by Base.parse_cache_header
+            error("EOF while reading cache header")
+        end
         push!(files, (String(read(f, n)), ntoh(read(f, Float64))))
     end
+    @assert totbytes == 4 "header of cache file appears to be corrupt"
```
Comment (tkelman) [inline base/loading.jl]: this still isn't enough information to be a useful error message. the value that occurred? which cache file was being processed?

File: doc/manual/modules.rst [hunk 7]
```diff
@@ -257,24 +257,32 @@ the statements in a module often involves compiling a large amount of code.
 Julia provides the ability to create precompiled versions of modules
 to reduce this time.
 
-There are two mechanisms that can achieve this:
-incremental compile and custom system image.
-
-To create a custom system image that can be used when starting Julia with the ``-J`` option,
-recompile Julia after modifying the file ``base/userimg.jl`` to require the desired modules.
```
Comment (tkelman) [inline doc/manual/modules.rst]: this still works and documentation of it shouldn't be removed

File: doc/manual/modules.rst [hunk 8]
```diff
@@ -257,24 +257,32 @@ the statements in a module often involves compiling a large amount of code.
...
+Alternatively, you can manually call ``Base.compilecache(modulename)``.
+The resulting cache files will be stored in ``Base.LOAD_CACHE_PATH[1]``.
+Subsequently, the module is automatically recompiled upon ``import``
+whenever any of its dependencies change;
+dependencies are modules it imports, the Julia build, files it includes,
+or explicit dependencies declared by ``include_dependency(path)`` in the module file(s).
+
+For file dependencies, a change is determined by examining whether the timestamp
+of each file loaded by `include` or added explicity by ``include_dependency`` is unchanged
+(to within a small margin of several seconds to account for misbehaving systems).
```
Comment (tkelman) [inline doc/manual/modules.rst]: the rounding isn't a margin

File: doc/manual/modules.rst [hunk 9]
```diff
@@ -290,12 +298,20 @@ initialization steps that must occur at *runtime* from steps that can
 occur at *compile time*.  For this purpose, Julia allows you to define
 an ``__init__()`` function in your module that executes any
 initialization steps that must occur at runtime.
+This function will not be called during compilation
+(``--output-*`` or ``__precompile__()``).
+You may, of course, call it manually if necessary,
+but the default is to assume this function deals with local state
+which does not need to be captured in the compiled image.
+And it will be called anytime the module is loaded,
```
Comment (tkelman) [inline doc/manual/modules.rst]: any time

Comment (vtjnash) [inline doc/manual/modules.rst]: anytime, adv., adj., and int.
View as: Outline |Full entryKeywords: On |OffQuotations: Show all |Hide all
Pronunciation:  Brit.	 /ˈɛnɪtʌɪm/ , U.S.  /ˈɛniˌtaɪm/
Forms:  See any adj., pron., n., and adv.   and time n., int., and conj.
Frequency (in current use):  
Origin: Formed within English, by compounding. Etymons: any adj., time n.
Etymology: < any adj. + time n.
 
Compare sometime adv. and one time adv.
Often written as two words. (Word division in Middle English examples frequently reflects editorial choices of modern editors of texts, rather than the practice of the manuscripts.)
 
Compare adverbial use of the dative singular of the corresponding noun phrase in Old English, with both elements inflected for case and number:
OE   Wulfstan Institutes of Polity (Corpus Cambr. 201) 134   Nagan læwede men freolstidum ne fæstentidum þurh hæmedþingc wifes gemanan, þe ma þe heahhades menn þæt þing agon ænigum timan.
(Show Less)
 A. adv.
 1.
 
 a. Esp. with reference to a future event: at any point in time; (following a negative) ever.

a1375   William of Palerne (1867) l. 5148   Þat sche wold miswerche wrongli any time.
a1425   Wyclif Sel. Eng. Wks. (1871) II. 137   No jogelyng ne falseheed was ony tyme in Crist.
a1425   Rule St. Benet (Lansd.) (1902) 1 (MED),   Þat he..be not greuyd ony tyme be our euyl dedis.
c1450  (▸c1350)    Alexander & Dindimus (Bodl.) (1929) l. 484 (MED),   Whan þe watur wiþ þe wind þe wawus up casteth, And þouh hit turne any time to tempest of windus, Hit ne awecheþ no wawe nor no watur rereth.
a1538   A. Abell Roit or Quheill of Tyme f. 72v, in Dict. Older Sc. Tongue at Ony-time,   That nane suld dispair of the mercy of God onytyme.
1577   H. I. tr. H. Bullinger 50 Godlie Serm. II. To King sig. Aa.ij,   God..cannot any time either erre, or conceiue any false opinions or repugning counsells.
1650   T. Venner Treat. Tobacco in Via Recta (rev. ed.) 415   Tobacco any way, or any time used, is most pernicious unto dry melan-cholerick bodies.
1799   J. Robertson Gen. View Agric. Perth 433   If..the lease be forfeited or adjudged any time before the last years of the contract.
1859   ‘G. Eliot’ Adam Bede I. i. xiii. 251   It was as if she had been wooed by a river-god, who might any time take her to his wondrous halls below a watery heaven.
1932   W. Faulkner Light in August xv. 341   If you want to get to Jefferson anytime soon, you'd better go to town and hire a car.
1979   Observer 10 June 33/5   Suddenly you are in the Slide Area. No stopping any time.
2010   N.Y. Rev. Bks. 29 Apr. 29/3   Prospects for meaningful reforms anytime soon are surely limited.
(Hide quotations)
 
Categories »
 
 b. Followed by this or these and an expression of time: for the whole of the specified length of time up to the present. Cf. this pron. and adj. 5f, these pron. and adj. 3e. Now rare (arch. or regional in later use).

?1589   T. Nashe Almond for Parrat sig. D3,   You think that no man dare touch you, because you haue plaid the scuruie scolde anie time these twentie yeeres.
1592   G. Harvey Foure Lett. iii. 29   The poore Tennement of his Purse..hath bene the Diuels Dauncing schoole, anie time this halfe yeare.
1673   R. Leigh Transposer Rehears'd 39   This is a Plot..this has been a brewing any time this Thirty years.
1732   H. Baker & J. Miller tr. Molière Blunderer i. v. 23 in Sel. Comedies III   A Brace of Hundred Pieces that have been due any time this two long Years.
1879   H. James in Scribner's Monthly Dec. 209/2   He had been in love with Angela Vivian any time these three years.
1916   A. Lowell Men, Women & Ghosts 279   ‘I'll marry yer as soon As I c'n raise the money.’ ‘You've said that any time these five year, But you don't do nothin'.’
1955   F. Debenham Nyasaland 106,   I imagine that they could have retired to comfort and ease in England any time these last twenty years.
1989   S. Raven Blood of My Bone (2001) ii. 78   ‘When were you in a Greek prison, Julian?’..‘Any time these last fifteen years.’
(Hide quotations)
 
 
 2. In relative use: whenever, if ever.

1822   London Mag. Sept. 240   Here's my brother Felix can give me the breadth of my back five times out of four, any time he likes.
1873   Trollope Eustace Diamonds II. lii. 335   If I found I didn't like him, I'd leave him even after the altar. I'd leave him any time I found I didn't like him.
1915   P. G. Wodehouse Psmith, Journalist iv. 26   Any time you're in bad. Glad to be of service.
1976   National Observer (U.S.) 14 Aug. 4/1   The iron rule of business dictates staying open anytime there's a decent chance to turn a profit.
2011   D. Young Mastering Nikon D7000 iv. 219   Anytime you want to take pictures without a memory card, you'll need to select this setting.
(Hide quotations)
 
 B. adj. (attrib.).
 
  That can take place, be used, etc., at any time.

1870   A. Thackeray Let. Nov. in Lett. A. T. Ritchie (1924) viii. 143,   I did like your last letter. It was like a real anytime talk with you.
1904   Kingdom Jan. 1/1   Would it not be a good thing to meet the devil on his own ground and have an any time church?
1966   G. N. Leech Eng. in Advertising xv. 139   The any-time cereal.
2001   N.Y. Times 17 May g6/2   It is an anytime, anyplace solution.
(Hide quotations)
 
 C. int.
Categories »
 
  Orig. U.S. Used as a response to an expression of thanks. Cf. you are (or you're) welcome at welcome adj. 3d.

1961   Hartford (Connecticut) Courant 16 July 14 a/1   ‘Okay, thank you.’ ‘Any time.’
1985   M. Gagnon Inner Ring 37   ‘Thanks for the advice, Deirdre.’ ‘Any time,’ I said.
2001   M. Blake 24 Karat Schmooze xxv. 283   Reece said, ‘Cheers for seeing me right last night.’ ‘Anytime.’
(Hide quotations)
 
↑↓
Back to top

"anytime, adv., adj., and int." OED Online. Oxford University Press, June 2016. Web. 22 August 2016.

Comment (tkelman) [inline doc/manual/modules.rst]: none of those uses apply here

**Comment by ViralBShah** [comment]
Merge?

File: doc/manual/modules.rst (hunk 8 above)
Comment (vtjnash) [inline doc/manual/modules.rst]: in what way?

File: doc/manual/modules.rst (hunk 7 above)
Comment (vtjnash) [inline doc/manual/modules.rst]: It doesn't have anything to do with Modules, so it doesn't belong in the module docs, and it's already described in more useful detail in the devdocs where it belongs.

File: base/loading.jl (hunk 6 above)
Comment (vtjnash) [inline base/loading.jl]: no

Comment (tkelman) [inline base/loading.jl]: "no" what? more words please.

File: doc/manual/modules.rst (hunk 8 above)
Comment (tkelman) [inline doc/manual/modules.rst]: it checks if the time exactly matches, or if the time exactly matches the rounded value. that's stricter than a margin would imply

File: base/loading.jl (hunk 2 above)
Comment (vtjnash) [inline base/loading.jl]: already fixed

File: doc/manual/modules.rst [hunk 10]
```diff
@@ -257,24 +257,33 @@ the statements in a module often involves compiling a large amount of code.
...
+The resulting cache files will be stored in ``Base.LOAD_CACHE_PATH[1]``.
+Subsequently, the module is automatically recompiled upon ``import``
+whenever any of its dependencies change;
+dependencies are modules it imports, the Julia build, files it includes,
+or explicit dependencies declared by ``include_dependency(path)`` in the module file(s).
+
+For file dependencies, a change is determined by examining whether the modification time
+of each file loaded by `include` or added explicity by ``include_dependency`` is unchanged,
+or equal to the modification time truncated to the nearest second
+(to accomodate systems that can't copy mtime with sub-second accuracy).
```
Comment (tkelman) [inline doc/manual/modules.rst]: accommodate has 2 m's, and should spell out mtime otherwise it's jargon

File: doc/manual/modules.rst (hunk 9 above)
Comment (stevengj) [inline doc/manual/modules.rst]: In modern usage, "anytime" is considered rather informal. 

* https://books.google.com/ngrams/graph?content=anytime%2Cany+time&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Canytime%3B%2Cc0%3B.t1%3B%2Cany%20time%3B%2Cc0
*  https://www.grammarly.com/handbook/grammar/adjectives-and-adverbs/14/anytime-vs-any-time/

When you have a choice between a spelling that will look "sloppy" to a large fraction of readers and a spelling that is universally considered correct, it's best to choose the latter unless you are actively trying for an informal feel.

File: base/loading.jl (hunk 6 above)
Comment (tkelman) [inline base/loading.jl]: Seriously, please explain yourself using full sentences. If this assertion ever happens in practice due to some bug or corruption somewhere, it will make life much easier if the error indicates as much as possible about where it is, what it's trying to do, and why it failed. Otherwise I anticipate having a really nasty time debugging issues like this while trying to deploy something for a customer on a tight deadline.

Comment (stevengj) [inline base/loading.jl]: Assertion failures are not really intended for end users.   And developers would end up just grepping for the string anyway, so a terse message is probably fine.

Comment (tkelman) [inline base/loading.jl]: A terse message and grepping in the source code won't help a developer who encounters the error understand what's going on and what caused the problem. I do things with precompiled ji files often that lead me to believe I will have a high chance of encountering this at some point. I would like to not have to swear at Jameson (or swear at Keno, if Gallium can't help) when it happens.

Comment (stevengj) [inline base/loading.jl]: The file would have to be corrupted in a very specific way for you to encounter this, so I seriously doubt there is a "high chance" of that.

Assertions are a separate universe from normal error messages.  You want to sprinkle asserts liberally throughout the source code to help find bugs, but there is not much point in making very helpful error messages for them — any assertion failure is pretty much guaranteed to require you to dig through the source code and debug, because it is an error by the programmer and not an error by the user.

Comment (tkelman) [inline base/loading.jl]: Good point, the earlier errors in this function should also have more information if at all possible.

> Assertions are a separate universe from normal error messages.

I get that they're not intended to be user-friendly, but given

> any assertion failure is pretty much guaranteed to require you to dig through the source code and debug, because it is an error by the programmer and not an error by the user

I don't understand why you want to leave landmines with so little information for yourself if you're bothering to check something at all. If you have any doubt that you might be wrong and it might ever fail, why the resistance to leaving more breadcrumbs to help future you out and have an easier time of the digging and debugging? Especially if something only happens rarely or on a specific remote system reported by a user where you can't immediately reproduce.

Comment (tkelman) [inline base/loading.jl]: And in terms of what I'm doing, I am specifically modifying the .ji file headers. If this were an assertion somewhere else I'd be a lot less worried about it.

Comment (tkelman) [inline base/loading.jl]: Last time I had this argument about assertions (https://github.com/JuliaLang/julia/pull/17459#discussion_r71439534 to be specific) it failed a few days later (https://github.com/JuliaLang/PkgDev.jl/issues/48#issuecomment-236054874) and it would've been more useful if the error had said something about what went in to the condition that failed. Why is less information better?

File: doc/manual/modules.rst [hunk 11]
```diff
@@ -257,24 +257,33 @@ the statements in a module often involves compiling a large amount of code.
...
+This will cause it to be automatically compiled the first time it is imported.
+Alternatively, you can manually call ``Base.compilecache(modulename)``.
+The resulting cache files will be stored in ``Base.LOAD_CACHE_PATH[1]``.
+Subsequently, the module is automatically recompiled upon ``import``
+whenever any of its dependencies change;
+dependencies are modules it imports, the Julia build, files it includes,
+or explicit dependencies declared by ``include_dependency(path)`` in the module file(s).
+
+For file dependencies, a change is determined by examining whether the modification time (mtime)
+of each file loaded by `include` or added explicity by ``include_dependency`` is unchanged,
```
Comment (tkelman) [inline doc/manual/modules.rst]: rst, needs double backticks

File: doc/manual/modules.rst [hunk 12]
```diff
@@ -290,12 +299,20 @@ initialization steps that must occur at *runtime* from steps that can
 occur at *compile time*.  For this purpose, Julia allows you to define
 an ``__init__()`` function in your module that executes any
 initialization steps that must occur at runtime.
+This function will not be called during compilation
+(``--output-*`` or ``__precompile__()``).
+You may, of course, call it manually if necessary,
+but the default is to assume this function deals with local state
+which does not need to be captured in the compiled image.
+And it will be called anytime the module is loaded,
+including if it is being looded into an incremental compile
```
Comment (tkelman) [inline doc/manual/modules.rst]: loaded

File: base/loading.jl (hunk 6 above)
Comment (JeffBezanson) [inline base/loading.jl]: It seems this is not really about assertions, but instead a claim that some condition thought to be impossible is in fact possible, and an important failure mode that needs diagnostics.

The question is, would it have come up if this assertion had not been written at all? People should be free to add as many assertions as possible, the more the merrier, without drawing fire about some assertion needing a better message. Otherwise you're just discouraging writing assertions. But if there is some independent reason to believe this is an important failure mode, then it's reasonable to ask for better diagnostics.

Comment (tkelman) [inline base/loading.jl]: That's fair, but couldn't we also just write assertions with useful messages? In a perfect world we'd just have rr recording at all times and a full reproducible dump occur at every error, messages be damned. But we don't live there yet.

We're shipping a product to customers in which the build process involves careful modifications of the cache file headers - so I'm paying attention to anything related that might cause that process to fail. The modifications we're making could easily be susceptible to off-by-one bugs, or mishandling of unicode paths, that kind of thing. More eyes reviewing that always appreciated.

If the assertion hadn't been written, then I don't know what the consequence would be of this particular error condition passing through unchecked. Would it be better or worse than the assertion failing without printing any helpful state about why it failed?

**Comment by stevengj** [comment]
This should help with #12508 too.

**Comment by vtjnash** [comment]
ah, yes, this actually should fix #12252 and #12508

File: base/loading.jl (hunk 6 above)
Comment (tkelman) [inline base/loading.jl]: Jameson, this is deeply frustrating. Why is it not possible to be more detailed here if this fails?

Comment (vtjnash) [inline base/loading.jl]: As Jeff and Steven explained, this is not itself an error, an assert is a detection that something else previously was wrong. There is no value here in what the local values were. This is just trying to halt the process before it does any further damage, as it has no idea why it went wrong (those cases were already tested for and return more detailed messages).

Comment (tkelman) [inline base/loading.jl]: I'm going to hold you to that "no value" when it happens and we need to find out why and fix it.

can "EOF while reading cache header" at least say which header it was trying to read?

Comment (tkelman) [inline base/loading.jl]: How about the following proposal. Can we write a detailed .ji file integrity checker, with as much diagnostic info as possible? Or a diagnostic mode that could be opt in? It could be done here or elsewhere, but if elsewhere it would need to be kept up to date. For the normal path where we don't expect people to be modifying ji files, leave as is.

**Comment by ViralBShah** [comment]
@tkelman Is this PR included in 0.5rc3? If not, are you thinking to put out 0.5rc4 with this included - or is this slated for 0.5.1?

**Comment by tkelman** [comment]
#18276
