### PR TITLE
inlining: make union splitting account for uncovered call

### LINKED ISSUE #48397: Julia 1.9: precompile prints errors when mixing pkgimages=yes and pkgimages=no
If you precompile the same package environment twice, once with `julia --pkgimages=yes`, and once with `julia --pkgimages=no`, then calling `Pkg.precompile()` a third time will print lots of errors:

```
➜   julia19 --pkgimages=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-beta3 (2023-01-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.9) pkg> activate hellohello
  Activating new project at `~/temp/hellohello`

(hellohello) pkg> add HTTP
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/temp/hellohello/Project.toml`
  [cd3eb016] + HTTP v1.7.3
    Updating `~/temp/hellohello/Manifest.toml`
  [d1d4a3ce] + BitFlags v0.1.7
  [944b1d66] + CodecZlib v0.7.0
  [cd3eb016] + HTTP v1.7.3
  [83e8ac13] + IniFile v0.5.1
  [692b3bcd] + JLLWrappers v1.4.1
  [e6f89c97] + LoggingExtras v1.0.0
...
Precompiling environment...
  16 dependencies successfully precompiled in 3 seconds

(hellohello) pkg> 
➜  julia19 --pkgimages=yes
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-beta3 (2023-01-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.9) pkg> activate hellohello
  Activating project at `~/temp/hellohello`

(hellohello) pkg> precompile
Precompiling environment...
  16 dependencies successfully precompiled in 8 seconds

(hellohello) pkg> 
➜  julia19 --pkgimages=no 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-beta3 (2023-01-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.9) pkg> activate hellohello
  Activating project at `~/temp/hellohello`

(hellohello) pkg> precompile

(hellohello) pkg> ┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
┌ Error: Pkg.precompile error
│   exception =
│    fatal error in type inference (type bound)
│    Stacktrace:
│     [1] get!(default::Pkg.API.var"#212#213"{UInt128, Base.PkgId, String, String}, h::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, key::Tuple{Base.PkgId, UInt128, String, String})
│       @ Base ./dict.jl:468
│     [2] _is_stale!(stale_cache::Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1051
│     [3] macro expansion
│       @ /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1371 [inlined]
│     [4] (::Pkg.API.var"#235#264"{Bool, Pkg.Types.Context, Vector{Task}, Pkg.API.var"#handle_interrupt#256"{Base.Event, ReentrantLock, Base.TTY}, Pkg.API.var"#color_string#254", Base.Event, Base.Event, ReentrantLock, Vector{Base.PkgId}, Vector{Base.PkgId}, Dict{Base.PkgId, String}, Vector{Base.PkgId}, String, Vector{Base.PkgId}, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Dict{Base.PkgId, Bool}, Vector{Pkg.Types.PackageSpec}, Dict{Base.PkgId, String}, Dict{Tuple{Base.PkgId, UInt128, String, String}, Union{Bool, Tuple{Vector{Any}, String}}}, Vector{Base.PkgId}, Bool, Base.TTY, Base.Semaphore, String, Vector{String}, Vector{Base.PkgId}, Base.PkgId})()
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API /Applications/Julia-1.9 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/API.jl:1260
(hellohello) pkg> 

julia> 1+1
2
```

### PR DESCRIPTION
**Pull request by aviatesk**
JuliaLang/julia#44421 changed the union-splitting to skip generating unnecessary fallback dynamic dispatch call when there is any fully covered call.
But it turned out that this is only valid when there is any fully covered call in matches for all signatures that inference split, and it is invalid if there is any union split signature against which any uncovered call is found.

Consider the following example:

    # case 1
        # def
        nosplit(::Any) = [...]
        nosplit(::Int) = [...]
        # call
        nosplit(a::Any)
            split1: a::Any ┬ nosplit(a::Int)
                           └ nosplit(a::Any) # fully covers split1

    # case 2
        # def
        convert(::Type{T}, ::T) = T
        # call
        convert(::Type{Union{Bool,Tuple{Int,String}}}, a::Union{Bool,Tuple{Int,Any}})
            split1: a::Bool           ─ convert(::Type{Bool}, ::Bool)                           # fully covers split1
            split2: a::Tuple{Int,Any} ─ convert(::Type{Tuple{Int,String}}, ::Tuple{Int,String}) # NOT fully covers split2

JuliaLang/julia#44421 allows us to optimize the the first case, but handles the second case wrongly. This commit fixes it up while still optimizing the first case.

fix #48397.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Review by Keno — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48455#issuecomment-1408471645) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/ba60e2d_vs_6ab660d/report.md).

File: test/compiler/inline.jl [hunk 1]
```diff
@@ -1910,3 +1910,22 @@ function elim_full_ir(y)
...
+let src = code_typed1((Union{Bool,Tuple{String,Any}},)) do x
+        f48397(x)
+    end
+    @test any(iscall((src, f48397)), src.code)
+end
+g48397::Union{Bool,Tuple{String,Any}} = ("48397", 48397)
+@test_throws MethodError let
+    Base.Experimental.@force_compile
+    f48397(g48397)
+end
```
Comment (vtjnash) [inline test/compiler/inline.jl:1927]: You can make these tests more reliable by looking at the return value here
```suggestion
let err = (@test_throws MethodError let
     Base.Experimental.@force_compile
     f48397(g48397)
 end).value
     @test err.f === f48397 && err.args === (g48397,)
 end
```
