### PR TITLE
REPL: make UndefVarError aware of imported modules

### LINKED ISSUE #55914: confusing error when Pkg is not imported but REPL mode has been used
Although Pkg is loaded, it's not accessible from Main here, so the hint `a global variable of this name also exists in Pkg.` seems confusing here:

```julia-repl
(@v1.12) pkg> instantiate

julia> Pkg
ERROR: UndefVarError: `Pkg` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in Pkg.
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/55914

```
(@v1.12) pkg>

julia> Pkg
ERROR: UndefVarError: `Pkg` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: Pkg is loaded but not imported in the active module `Main`.

julia> activate
ERROR: UndefVarError: `activate` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in Pkg, which is loaded but not imported in the active module `Main`.

julia> import Pkg

julia> activate
ERROR: UndefVarError: `activate` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in Pkg.

```

### CODE REVIEW

File: base/experimental.jl [hunk 1]
```diff
@@ -321,7 +321,7 @@ function show_error_hints(io, ex, args...)
             @invokelatest handler(io, ex, args...)
         catch err
             tn = typeof(handler).name
-            @error "Hint-handler $handler for $(typeof(ex)) in $(tn.module) caused an error"
+            @error "Hint-handler $handler for $(typeof(ex)) in $(tn.module) caused an error" err
```
Comment (vtjnash) [inline base/experimental.jl:324]: IIRC, if you name this _exception it will get better printing, and if you pass _exception=current_exceptions() it will do even better (though also will include stacktraces, so YMMV)

**Review by vtjnash — APPROVED** [review]
The text feels like a bit of a mouthful (particularly if we end up printing it a couple times), since we can pretty much assume that the module is loaded but not imported if the scope is Module (as otherwise we would not have had an UndefVarError). Maybe we can just wordsmith the default text a bit instead, based on the scope type?

e.g. "Hint: a global variable of this name may be made accessible by importing Pkg in the current active module $active"

File: base/experimental.jl (hunk 1 above)
Comment (IanButterworth) [reply base/experimental.jl:324]: I intentionally didn't include the stacktrace but I'll add it. Though `_exceptions` doesn't seem to be special (but I do see a couple of uses of it in Base/REPL)

```
julia> try
       error("some error")
       catch e
       @error "log error" _exception=current_exceptions()
       end
┌ Error: log error
│   _exception =
│    1-element ExceptionStack:
│    some error
│    Stacktrace:
│      [1] error(s::String)
│        @ Base ./error.jl:44
│      [2] top-level scope
│        @ REPL[7]:2
│      [3] __repl_entry_eval_expanded_with_loc(mod::Module, ast::Any, toplevel_file::Ref{Ptr{UInt8}}, toplevel_line::Ref{Int32})
│        @ REPL ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:331
...
```
```
julia> try
       error("some error")
       catch e
       @error "log error" exception=current_exceptions()
       end
┌ Error: log error
│   exception =
│    1-element ExceptionStack:
│    some error
│    Stacktrace:
│      [1] error(s::String)
│        @ Base ./error.jl:44
│      [2] top-level scope
│        @ REPL[8]:2
│      [3] __repl_entry_eval_expanded_with_loc(mod::Module, ast::Any, toplevel_file::Ref{Ptr{UInt8}}, toplevel_line::Ref{Int32})
│        @ REPL ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:331
...
```
