### PR TITLE
ARM ABI

### LINKED ISSUE #12344: parallel test crashing on arm (perhaps when there is a firewall)
The parallel test is failing on arm. The chromebook by default has a firewall that refuses everything. I believe I have set it up to accept all connections. Irrespective, we shouldn't be getting a segfault, and perhaps a better error about connection refused.

````
     * parallel             
signal (11): Segmentation fault

signal (11): Segmentation fault
exception on 1ERROR (unhandled task failure): connect: connection refused (ECONNREFUSED)
: ERROR: connect: connection refused (ECONNREFUSED)

signal (11): Segmentation fault
Segmentation fault (core dumped)
````

### PR DESCRIPTION
**Pull request by maleadt**
Hi all,

I wanted to run Julia on my Raspberry Pi 2, so I have taken a stab at implementing an ARM ABI interface for Julia. This fixes the following issues: #13508, #12355, #12347, #12343, and partially fixes #12344 (the `parallel` test suite doesn't pass yet, but the segfaults are fixed).

Although I'm happy with how most of Julia now works on my ARM-based computer, I don't think that implementing ABI's in this ad-hoc fashion is really future-proof. I'm sure there's missing features (not caught by the current test suite), and I'm not entirely convinced by the current ABI interface (`needPassByRef`, `use_sret`, `preferred_llvm_type` etc). Maybe we should look into using [llvm-abi](https://github.com/scross99/llvm-abi) ([announcement thread](http://thread.gmane.org/gmane.comp.compilers.clang.devel/43502/)), a library for generating ABI-compliant LLVM IR?

Some questions/uncertainties:
- I've added checks on EABI (AAPCS) and VFP procedure calling, currently `#error`ing out if not found. I'm not sure if this is appropriate, but the ABI currently relies on this.
- I'm currently casting heterogeneous aggregates to integer arrays for alignment purposes, because this is what Clang does. On x86 however, Clang uses the `align` attribute. I don't think this is easy to add without messing with `ccall`, but it might be a neater way of aligning aggregates.

### CODE REVIEW

File: src/abi_arm.cpp [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+{
+    return;
+}
+
+Type *preferred_llvm_type(jl_value_t *ty, bool isret)
+{
+    // TODO: If the argument is an integral Fundamental Data Type that is
+    // smaller than a word, then it is zero- or sign-extended to a full word and
+    // its size is set to 4 bytes. If the argument is a Half-precision Floating
+    // Point Type it is converted to Single Precision.
```
Comment (vtjnash) [inline src/abi_arm.cpp]: you can return `T_int32` and the callee of this function will zero/sign extend to accommodate

File: src/abi_arm.cpp [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+            // Align heterogeneous aggregates
+            // TODO: can this be done using the 'align' attribute?
+            size_t max_size = 0;
+            for (size_t i = 0; i < members; ++i) {
+                jl_value_t *fty = jl_field_type((jl_datatype_t*)ty,i);
+                size_t size = jl_datatype_size(fty);
+                max_size = size>max_size ? size : max_size;
+            }
+            Type* T = Type::getIntNTy(getGlobalContext(), max_size*8);
+            return ArrayType::get(T, members);
```
Comment (vtjnash) [inline src/abi_arm.cpp]: from what i recall, the function callee is not going to handle this correctly. it's going to assume that the memory layout was the same and try to do a cast through memory to change the llvm type.

File: src/abi_arm.cpp [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+
+#ifndef __ARM_PCS_VFP
+#  error "the Julia ARM ABI implementation requires VFP support"
+#endif
+
+typedef bool AbiState;
+AbiState default_abi_state = 0;
+
+inline bool isHomogeneousAggregate(jl_value_t *ty, const jl_value_t *&base,
+                                   size_t &members) {
```
Comment (vtjnash) [inline src/abi_arm.cpp]: this implementation doesn't match the ARM definition of a "Homogeneous Aggregates", due to the restriction that "The test for homogeneity is applied after data layout is completed and without regard to access control or other source language restrictions" (whereas this is being done with regards to the source language types).

e.g. the example given in the docs says that a vector of 8 x i8 and a vector of 4 x i16 should be considered homogeneous since they are both the same fundamental ARM type (containerized vector) and size (64 bytes)

**Comment by vtjnash** [comment]
> Maybe we should look into using llvm-abi (announcement thread), a library for generating ABI-compliant LLVM IR?

i had seen that announcement thread, but that library doesn't actually have a very good or complete ABI implementation and yet contains considerably more code.

> On x86 however, Clang uses the align attribute

afaics, this is only meaningful when applied to byval arguments. if not specified, it defaults to the platform-default value, which should be perfectly suitable for our requirements.

> I'm currently casting heterogeneous aggregates to integer arrays for alignment purposes, because this is what Clang does. 

yep, it looks like clang does the following:
```
define void @test_4(%struct.struct4* noalias sret %agg.result, [3 x i32] %a.coerce) #1 {
  %a = alloca %struct.struct4, align 4
  %1 = bitcast %struct.struct4* %a to [3 x i32]*
  store [3 x i32] %a.coerce, [3 x i32]* %1, align 1
```

File: src/abi_arm.cpp (hunk 2 above)
Comment (vtjnash) [inline src/abi_arm.cpp]: looking at clang ast, i think this can be implemented as:
```c
size_t align = jl_datatype_alignment(ty);
size_t size = jl_datatype_size(ty);
Type* T = Type::getIntNTy(getGlobalContext(), align*8);
return ArrayType::get(T, (size + align - 1) / align);
```
(the caller of this function will do the same cast-through-memory as clang to make this work)

**Comment by maleadt** [comment]
Thanks for the feedback, @vtjnash, I'll be looking at it. Seems like there's some other places I'm dropping the ball (not generating `sret`s where Clang does, and seemingly lucking out). I'm going to have a look at some improved testing, maybe by direct comparison against Clang's function signatures instead of actually executing code and hoping it crashes.

**Comment by ViralBShah** [comment]
Would have been a good idea to keep this open, and force push to this branch. That way the discussion around the ARM ABI could have continued here. Anyways, it can always a new PR.

**Comment by maleadt** [comment]
Huh, the delete & close was actually an unintended artifact of a `git push --mirror` from a host which didn't have the `arm_abi` branch... Let's see if I can fix this up.

**Comment by ViralBShah** [comment]
Any updates on this one to get it to a state where we can merge it? I have been salivating on this PR for a few days and hoping we can even backport it as well.

**Comment by JeffBezanson** [comment]
+1 This is an awesome piece of work. Would be great to bring it to conclusion.

**Comment by maleadt** [comment]
Sorry, haven't had the time to work on this, and I won't for the next few days either. I'll look at it next week, but if anyone is impatient enough to pick this up, be my guest :-)

**Comment by maleadt** [comment]
As promised, here is a reworked version of this PR. The current version is much more thorough, follows the docs better, and aligns with @yuyichao's recent AArch64 work.

It successfully passes my extended version of the `ccall` test suite (see PR #14215), except the `Int128` test passing an `Int128` to a C function accepting a `struct { int64_t, int64_t }`. I'm not sure how to make sense of that.

@vtjnash `isHomogeneous` currently still works on Julia types, will fix tomorrow. I just wanted to get some eyes on this already.

File: src/abi_arm.cpp [hunk 4]
```diff
@@ -0,0 +1,304 @@
...
+//
+//===----------------------------------------------------------------------===//
+//
+// The Procedure Call Standard can be found here:
+// http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042f/IHI0042F_aapcs.pdf
+//
+//===----------------------------------------------------------------------===//
+
+// LIMITATIONS
+// - doesn't respect register usage, these should be encoded in the ABI state
```
Comment (yuyichao) [inline src/abi_arm.cpp]: I think this is handled by llvm and it should handle it well as long as we emit the correct lowered type.

**Comment by yuyichao** [comment]
> It successfully passes my extended version of the `ccall` test suite (see PR #14215), except the `Int128` test passing an `Int128` to a C function accepting a `struct { int64_t, int64_t }`. I'm not sure how to make sense of that.

I haven't fully read the AArch32 calling convension doc yet but I do remember `__int128` is not a machine type on it (on the other hand it is on AArch64) so the frontend (us) shouldn't emit such types for calling c functions. (i.e. you should probably translate `i128` into `[2 x i64]`, this is what I do for `bitstype`s of invalid (no C correspondence) sizes for AArch64).

That test is technically wrong for AArch64 since `struct {int64_t, int64_t}` and `__int128` has different alignment requirement. It is fine for now though since there's no practical differences when passing as the first/only parameter.

File: src/abi_arm.cpp (hunk 4 above)
Comment (maleadt) [inline src/abi_arm.cpp]: I think you're right, I had thought the split register/stack mode would need to be generated by the front-end but it seems part of ARMCallingConv.td.

**Comment by maleadt** [comment]
Decomposing the `Int128` into `[2 x i64]` turned out slightly more complex, as in this case it needed to be `sret` too and Julia didn't honour the ABI's preferred type in case of `sret`.

**Comment by maleadt** [comment]
This should be pretty feature complete now. I guess the homogeneous aggregate detection could be shared between ABI's, [like Clang does it](http://clang.llvm.org/doxygen/CodeGen_2TargetInfo_8cpp_source.html#l03867), but I don't really feel like tackling that right now.

**Comment by ViralBShah** [comment]
Do the commits need squashing? While @vtjnash should review and merge the commits, I am guessing that tests are not necessary here since the failing tests that this PR will fix are sufficient to catch future regressions.

**Comment by maleadt** [comment]
Yeah, those tests + those from #14215 should cover the ABI sufficiently. Maybe there should be a CI bot for ARM too? Anyway, I'll squash/rebase/remove the RFC tag tomorrow morning.

**Comment by ViralBShah** [comment]
On Travis, one has to compile with a cross compiling toolchain and then test in qemu, which is meaningless. There is a plan to at least set up buildbots that can run every night on a scaleway machine. @staticfloat almost has this going, but currently giving `armv7` as the option to `-march` is failing.

File: src/abi_arm.cpp [hunk 5]
```diff
@@ -0,0 +1,315 @@
...
+#endif
+
+namespace {
+
+typedef bool AbiState;
+AbiState default_abi_state = 0;
+
+void needPassByRef(AbiState *state,jl_value_t *ty, bool *byRef, bool *inReg)
+{
+    // B.1 (TODO)
```
Comment (yuyichao) [inline src/abi_arm.cpp]: This is irrelevant. It doesn't really exist in C and it roughly correspond to our `Any` which is indeed passing by pointer.

File: src/abi_arm.cpp [hunk 6]
```diff
@@ -0,0 +1,315 @@
...
+    // - A 64-bit or 128-bit containerized vector type.
+    size_t vec_size = isContainerizedVector(dt);
+    if (vec_size == 8 || vec_size == 16) {
+        *vfp = true;
+        return;
+    }
+
+    // - A Homogeneous Aggregate
+    Type *base = NULL;
+    if (isLegalHA(dt, base)) {
```
Comment (yuyichao) [inline src/abi_arm.cpp]: I think you can just use almost the same logic (without `__fp128`) with AArch64 here. Section 6.1.2.1 says,

```
For the VFP the following argument types are VFP CPRCs.
* A half-precision floating-point type.
* A single-precision floating-point type.
* A double-precision floating-point type.
* A 64-bit or 128-bit containerized vector type.
* A Homogeneous Aggregate with a Base Type of a single- or double-precision floating-point type with one to
four Elements.
* A Homogeneous Aggregate with a Base Type of 64-bit containerized vectors with one to four Elements.
* A Homogeneous Aggregate with a Base Type of 128-bit containerized vectors with one to four Elements.
```

In particular, only HA of `f32` or `f64` are relavant (and vectors too but we don't have that in julia). This is basically the same definition of [HFA and HVA in the AArch64 calling convention](https://github.com/JuliaLang/julia/blob/5cbb72ca46791c6491a098399642c00daf97cec0/src/abi_aarch64.cpp#L45). (FWIW, I find the AArch64 calling convention much easier to read.....) and I think it can make the `isLegal*` functions above much simpler.

File: src/abi_arm.cpp [hunk 7]
```diff
@@ -0,0 +1,315 @@
...
+        *vfp = true;
+        return;
+    }
+}
+
+static void classify_return_arg(jl_value_t *ty, bool *reg, bool *vfpreg,
```
Comment (yuyichao) [inline src/abi_arm.cpp]: The output parameter can probably be reduced a little bit (e.g. seems that `reg ^ vfpreg ^ onstack` is always true)

File: src/abi_arm.cpp [hunk 8]
```diff
@@ -0,0 +1,315 @@
...
+    //   Any result whose type would satisfy the conditions for a VFP CPRC is
+    //   returned in the appropriate number of consecutive VFP registers
+    //   starting with the lowest numbered register (s0, d0, q0).
+    classify_cprc(dt, vfpreg);
+    if (*vfpreg)
+        return;
+
+    // - A Half-precision Floating Point Type is returned in the least
+    //   significant 16 bits of r0.
+    if (dt == jl_float16_type) {
```
Comment (yuyichao) [inline src/abi_arm.cpp]: I was trying to figure out how clang handles this but it (and also gcc) always complains that `__fp16` is not allowed as parameter or return type. Doesn't really hurt to keep this here though.

File: src/abi_arm.cpp [hunk 9]
```diff
@@ -0,0 +1,315 @@
...
+    // - A word-sized Fundamental Data Type (eg., int, float) is returned in r0.
+    // NOTE: assuming "fundamental type" == jl_is_bitstype, might need exact def
+    if (jl_is_bitstype(dt) && dt->size <= 8) {
+        *reg = true;
+        return;
+    }
+
+    // A 128-bit containerized vector is returned in r0-r3.
+    size_t vec_size = isContainerizedVector(dt);
+    if (vec_size == 128) {
```
Comment (yuyichao) [inline src/abi_arm.cpp]: I know this is always false now but I think even when we support this the check should be `16` and it should already be checked by the cprc case above.

File: src/abi_arm.cpp (hunk 5 above)
Comment (maleadt) [inline src/abi_arm.cpp]: OK.

File: src/abi_arm.cpp (hunk 6 above)
Comment (maleadt) [inline src/abi_arm.cpp]: The AAPCS doc is much harder to read indeed, some sections just seem out of order... I guess they've build on that experience when drafting the AArch doc.

Anyway, I think some aspects of the more complex legality definition are needed though, for example handling of nested composites with the same type (this happens in my extended test suite containing `struct { complex{T}, complex{T} }`). I also thought that it might be interesting to keep the definition a bit more general, in order to share it between ABI's later on (mimicking Clang here).
That said, I don't have particulary strong feelings, so if you prefer a simpler, stand-alone ABI definition I'm willing to simplify it.

File: src/abi_arm.cpp (hunk 9 above)
Comment (maleadt) [inline src/abi_arm.cpp]: By the way, this might interest you: I've created a small `ccall` replacement macro at [maleadt/checked_ccall](https://github.com/maleadt/julia/commit/5fd721cb61588d5295e1aa8ec1ba003716a0e1d2)  which extracts and prints both `call` instructions based on a corresponding `call_$TEST` method in `libccalltest`. Pretty hackish and unportable, but eases development.

File: src/abi_arm.cpp (hunk 8 above)
Comment (maleadt) [inline src/abi_arm.cpp]: By the way, this might interest you: I've created a small `ccall` replacement macro at [maleadt/checked_ccall](https://github.com/maleadt/julia/commit/5fd721cb61588d5295e1aa8ec1ba003716a0e1d2)  which extracts and prints both `call` instructions based on a corresponding `call_$TEST` method in `libccalltest`. Pretty hackish and unportable, but eases development.

File: src/abi_arm.cpp (hunk 9 above)
Comment (maleadt) [inline src/abi_arm.cpp]: Oh yeah, nicely spotted. I kept the (redundant) definition there in case we ever want to support ARMv7 without VFP. Not sure anybody is still using that though..

File: src/abi_arm.cpp (hunk 6 above)
Comment (yuyichao) [inline src/abi_arm.cpp]: Maybe I'm missing something but why does `struct { complex{T}, complex{T} }` matter here? I couldn't find anywhere in the doc saying that it need to be treated in a special way.

File: src/abi_arm.cpp (hunk 9 above)
Comment (yuyichao) [inline src/abi_arm.cpp]: I won't worry about arm without vfp too much since IIRC they have other issues (don't pass number tests?). Leaving a comment here should probably be enough.

Comment (maleadt) [inline src/abi_arm.cpp]: `numbers` issue seems independent of VFP, seeing how it still fails on my system...
Will replace by a comment though.

File: src/abi_arm.cpp (hunk 6 above)
Comment (maleadt) [inline src/abi_arm.cpp]: See section 4.3:

> The definitions are recursive; that is, each of the types may contain a Composite Type as a member.

For example:

```c
struct large_nonha {
    struct {
        double a;
        float b;
    };
};

struct large_ha {
    struct {
        double a;
        double b;
    };
};

struct large_nonha foo() {}
struct large_ha bar() {}
```

Using clang, this yields:
```llvm
%struct.large_nonha = type { %struct.anon }
%struct.anon = type { double, float }
%struct.large_ha = type { %struct.anon.0 }
%struct.anon.0 = type { double, double }

define void @foo(%struct.large_nonha* noalias sret %agg.result)
define %struct.large_ha @bar()
```

I assume this might apply to AArch64 as well?

Comment (yuyichao) [inline src/abi_arm.cpp]: You are right. I guess the relevant statement is `where all of the Fundamental Data Types of the members that
compose the type are the same.` (instead of each member) So `struct {double; struct {double; double};}` and `struct {double; struct {double[2];};}` are both HA .... Will fix that for AArch64.

**Comment by maleadt** [comment]
Addressed @yuyichao's comments, and squashed the commits.

File: src/abi_arm.cpp [hunk 10]
```diff
@@ -0,0 +1,285 @@
...
+    return NULL;
+}
+
+// Check whether a type is a legal homogeneous aggregate. Returns the number of
+// members.
+static size_t isLegalHA(jl_datatype_t *dt, Type *&base) {
+    // Homogeneous aggregates are only used for VFP registers,
+    // so use that definition of legality (section 6.1.2.1)
+
+    if (jl_is_structtype(dt)) {
```
Comment (yuyichao) [inline src/abi_arm.cpp]: I noticed this when fixing it for AArch64. I think you need to check `pointerfree` here. `haspadding` should be another field to check as a fast path.

File: src/abi_arm.cpp [hunk 11]
```diff
@@ -0,0 +1,285 @@
...
+        // ... with one to four Elements.
+        size_t members = jl_datatype_nfields(dt);
+        if (members < 1 || members > 4)
+            return 0;
+
+        base = NULL;
+        for (size_t i = 0; i < members; ++i) {
+            Type *T = isLegalHAType((jl_datatype_t*)jl_field_type(dt,i));
```
Comment (yuyichao) [inline src/abi_arm.cpp]: And I believe the members counting is wrong for recursive types.

**Comment by maleadt** [comment]
@yuyichao I addressed your comments.

Other pending reviews? If not, is this good to go?

**Comment by yuyichao** [comment]
LGTM =)

@vtjnash Any comments? If not I'll merge later today.

**Comment by ViralBShah** [comment]
Bumping again to see if we can backport to 0.4. Looks like it shouldn't be a difficult backport and fairly self-contained.

**Comment by ViralBShah** [comment]
@tkelman As you had mentioned to me, the codegen restructure makes it difficult to have a clean backport to 0.4. Perhaps ARM should just wait for 0.5.

**Comment by tkelman** [comment]
I thought I phrased it the other way around - anything that depends on the codegen rewrite will obviously be tough to backport on its own, but most of the currently backport-tagged arm-related PR's look more or less standalone? Let's see what ends up being easy to backport for 0.4.4 and how many arm bugs we can fix there without spending too much effort.

**Comment by ViralBShah** [comment]
I actually have backported pretty much all of them. There are compile errors in the arm ABI file, because they refer to things that were not in 0.4.

**Comment by tkelman** [comment]
You introduced a bunch of CI failures. Could you have gone through a PR?

**Comment by ViralBShah** [comment]
I never pushed I thought.

**Comment by ViralBShah** [comment]
At least I didn't mean to, but might have done it out of habit, when on a branch - except this was the release branch. Can we get rid of them right away?

**Comment by tkelman** [comment]
Revert the commits that are broken. The release branch is protected so force pushing is disabled. Does release-0.4 compile on arm with llvm 3.7.1? If the new ABI doesn't compile on ARM without the codegen rewrite then that's a regression w.r.t. 0.4.3 so that should probably also be reverted.

**Comment by ViralBShah** [comment]
I have reverted locally the arm abi patches. I think the rest should be ok, and this will give a fully functioning build, with llvm 3.7.1. Once I do that successfully, I can push the reverts.

**Comment by tkelman** [comment]
See my commit comments. d93b819bb7ea159efbbebf271049d1c4db5b1fd6 and dfba26bde58b9b9fae66001b136c67391243c394 aren't correct as-is for backporting. And e8c44f6d3488ad41a064404df0c09f1635abe5a6 needs to be adjusted.
