### PR TITLE
ntuple: ensure eltype is always `Int`

### LINKED ISSUE #55790: ntuple eltype depends on tuple length for UInt64
Both on julia 1.10.5 and julia 1.11.0-rc3, calling `ntuple(f, n::UInt64)` gives the following unexpected behavior:

```julia
julia> ntuple(identity, UInt64(10))
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

julia> ntuple(identity, UInt64(11))
(0x0000000000000001, 0x0000000000000002, 0x0000000000000003, 0x0000000000000004, 0x0000000000000005, 0x0000000000000006, 0x0000000000000007, 0x0000000000000008, 0x0000000000000009, 0x000000000000000a, 0x000000000000000b)
```

I imagine this is due to the fact that for `n <= 10` there is an hard-coded version using `Int`, whereas the generic fallback respects the `UInt64` eltype. I suppose this is a pretty rare corner case (99% of the time I suspect `ntuple` is called with `n::Int`), but it caused some hard to figure out bug in some library code, so I thought it was worth reporting.

### PR DESCRIPTION
**Pull request by barucden**
Fixes #55790

### CODE REVIEW

**Comment by nsajko** [comment]
I think it'd be slightly better to construct an `Int`, with an `::Int` type assertion immediately afterwards, right at the beginning of the `ntuple` method.
* I think this would be faster for `BigInt` input, as comparing `Int` with `Int` should be faster than with `BigInt`.
* This would lead to more consistent error messages on the off chance someone passes in an `Integer` value whose `Int` constructor doesn't return `Int`.

**Review by nsajko — APPROVED** [review]

**Comment by barucden** [comment]
Makes sense, thank you.

File: base/ntuple.jl [hunk 1]
```diff
@@ -16,22 +16,24 @@ julia> ntuple(i -> 2*i, 4)
...
-        n == 3  ? (f(1), f(2), f(3)) :
-        n == 4  ? (f(1), f(2), f(3), f(4)) :
-        n == 5  ? (f(1), f(2), f(3), f(4), f(5)) :
-        n == 6  ? (f(1), f(2), f(3), f(4), f(5), f(6)) :
-        n == 7  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7)) :
-        n == 8  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8)) :
-        n == 9  ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9)) :
-        n == 10 ? (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10)) :
-        _ntuple(f, n)
+    n_ = Int(n)::Int
```
Comment (nsajko) [inline base/ntuple.jl:19]: Could make the diff smaller by renaming the method argument from `n::Integer` to `m::Integer` and then doing `n = Int(m)::Int` instead of `n_ = Int(n)::Int`.

File: base/ntuple.jl [hunk 2]
```diff
@@ -14,8 +14,9 @@ julia> ntuple(i -> 2*i, 4)
 (2, 4, 6, 8)
 ```
 """
-@inline function ntuple(f::F, n::Integer) where F
-    # marked inline since this benefits from constant propagation of `n`
+@inline function ntuple(f::F, m::Integer) where F
+    # marked inline since this benefits from constant propagation of `m`
+    n = Int(m)::Int
```
Comment (MasonProtter) [inline base/ntuple.jl:19]: This can be written as
```suggestion
    n::Int = m
```
which is syntax sugar for `n = convert(Int, m)::Int

Comment (adienes) [reply base/ntuple.jl]: `convert(Int, m)` is not the same as `Int(m)` though

Comment (barucden) [reply base/ntuple.jl]: It seems fine though, no?
https://github.com/JuliaLang/julia/blob/17445fe752b7b99633ca306af0981baca9f66bda/base/number.jl#L6-L7

**Comment by timholy** [comment]
If there's any risk this could take a while to compile (e.g., `f` is big and `@inline`), then the pattern
```julia
function slow_to_compile(f::F, n::Int) where F
    # body
end
slow_to_compile(f::F, n::Integer) where F = slow_to_compile(f, convert(Int, n)::Int)
```
might be better: it ensures the "real work" function only gets compiled for `Int`.

**Comment by barucden** [comment]
Got it! Thank you.

**Comment by barucden** [comment]
Bump

**Comment by barucden** [comment]
Bump
