### PR TITLE
[JuliaLowering] Fix break/continue in try

### LINKED ISSUE #171: `continue` inside `for` does not respect `finally`
```julia
for x in [1,2,3]
    try
        println("try: ", x)
        continue
    finally
        println("finally: ", x)
    end
end
```
JuliaLowering runs this as:
```julia
try: 1
try: 2
try: 3
```
but it should be:
```julia
try: 1
finally: 1
try: 2
finally: 2
try: 3
finally: 3
```

### PR DESCRIPTION
**Pull request by mlechu**
Alternative to https://github.com/JuliaLang/julia/pull/61523, fix https://github.com/JuliaLang/JuliaLowering.jl/issues/171.  

Push to `ctx.handler_token_stack` before construction of the `FinallyHandler`, since the `JumpTarget` constructor needs it.  The extra entry is ignored in `enter_finally_block`'s call to `emit_leave_handler`, but not in the one in `emit_break`.  These changes should directly match flisp.

I think we're still missing some `pop_exception`s compared to flisp, but wanted to get this PR up given the other one.  As noted in the tests, I need to port https://github.com/JuliaLang/julia/pull/55876, which duplicates the finally block and only adds `pop_exception` to one copy.

### CODE REVIEW

**Review by topolarity — APPROVED** [review]
Test coverage is better than mine 🙂

I also think this is much closer to what flisp does so let's take it

File: JuliaLowering/test/exceptions.jl [hunk 1]
```diff
@@ -348,6 +348,172 @@ begin
...
+            end
+            push!(out, ("bad", x))
+        end
+        out
+    end
+    """) == [("try", 1)]
+    @test isempty(current_exceptions())
+
+    # TODO: commented out to avoid polluting the exception stack; need to port
+    # https://github.com/JuliaLang/julia/pull/55876
```
Comment (topolarity) [inline JuliaLowering/test/exceptions.jl:465]: Do you think we should go ahead and do this now while we're fixing up `try-finally`?

Comment (mlechu) [reply JuliaLowering/test/exceptions.jl:465]: I originally planned to, but this change should be OK on its own too.  I need to port `rename_assigned_ssavalues` to properly copy finally blocks, which could potentially be a pain.

Comment (topolarity) [reply JuliaLowering/test/exceptions.jl:465]: Ah darn, I was hoping our `ssavar` logic would handle that OK if you just lower it twice

**Comment by topolarity** [comment]
Tests apparently (mostly) passed on https://github.com/JuliaLang/julia/pull/61523/

It looks like in one of the test cases on that PR, you might not emit anything for the "break"?

**Comment by topolarity** [comment]
Thanks @mlechu !
