### PR TITLE
fix some cases of diagonal subtyping when a var also appears invariantly

### LINKED ISSUE #26108: subtyping bug with comparing diagonal and triangular tuples
```julia
T, S = Tuple{T, T, Any} where T, Tuple{T, T, Vector{T}} where T
(Tuple{T, T, Any} where T, Tuple{T, T, Array{T, 1}} where T)

julia> S <: T
true
```

However, it's easy to find types (such as `R = Tuple{Int16, Int32, Vector{Any}}`) for which returning `true` here makes inference unsound

### LINKED ISSUE #26716: subtyping bug: diagonality is ignored in union
Both julia 0.6.2 and dev incorrectly say true on these judgments (on the left we have equivalent types, on the right the same type):
```
julia> (Tuple{Q,Bool} where Q<:Union{Int,P} where P) <: Tuple{Union{T,Int}, T} where T
true

julia> (Tuple{Union{Int,P},Bool} where P) <: Tuple{Union{T,Int}, T} where T
true

julia> (Union{Tuple{Int,Bool}, Tuple{P,Bool}} where P) <: Tuple{Union{T,Int}, T} where T
true
```
Correct answer is false, because variable `T` is (1) diagonal (2) matched both with `P` and `Bool`. 

If we rewrite the RHS into an equivalent type with an explicit diagonal type, then julia gives a correct answer.
```
julia> (Tuple{Union{T,Int}, T} where T) == Union{Tuple{Int, T} where T, Tuple{T1,T1} where T1}
true

julia> (Tuple{Q,Bool} where Q<:Union{Int,P} where P) <: Union{Tuple{Int, T} where T, Tuple{T1,T1} where T1} 
false

julia> (Union{Tuple{Int,Bool}, Tuple{P,Bool}} where P) <: Union{Tuple{Int, T} where T, Tuple{T1,T1} where T1}
false
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a part of #31833 that seems to be pretty non-breaking.

fix #26108, fix #26716

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34272#issuecomment-571185063) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/a82728a035c90c18125ecc3a5b09b16944c68f42/pkgeval-49623bd_vs_1878343/report.md). cc @maleadt

**Comment by vtjnash** [comment]
GeometryTypes package is an interesting case:

>  MethodError: *(::StaticArrays.SArray{Tuple{2,2},Int64,2,4}, ::HyperRectangle{2,Int64}) is ambiguous. Candidates:
    *(m::StaticArrays.SArray{Tuple{N1,N1},T1,2,L} where L, h::HyperRectangle{N2,T2}) where {N1, N2, T1, T2} in GeometryTypes at /home/pkgeval/.julia/packages/GeometryTypes/06goY/src/hyperrectangles.jl:83
    *(m::StaticArrays.SArray{Tuple{N,N},T1,2,L} where L, h::HyperRectangle{N,T2}) where {N, T1, T2} in GeometryTypes at /home/pkgeval/.julia/packages/GeometryTypes/06goY/src/hyperrectangles.jl:121

So we have `A = Tuple{V{Tuple{N,N}}, V{N}} where N` vs. `B = Tuple{V{Tuple{N1,N1}}, V{N2}} where {N1, N2}`, where before this change `A <: B`, while it seems that afterwards it's presumably not considering N1 to be in invariant position anymore.

**Comment by JeffBezanson** [comment]
Yeah, that's one of the trickiest cases. It's hard to say what we even want `Ref{Tuple{T,T}} where T` to mean. I tried making that T concrete but maybe it can't be.

**Comment by vtjnash** [comment]
Right. It's not obvious whether that only means the values for T are required to be the same (because the Tuple itself is invariant), or whether for soundness it must mean that T is also concrete. I'm leaning towards the former interpretation, but maybe it's better if it is the latter (as done here).

**Comment by vtjnash** [comment]
Note: I think that case is described in https://github.com/JuliaLang/julia/issues/26175#issuecomment-372746252, where we see it's currently undecidable given `Tuple{T, T} where T` whether `Tuple{R, R}` (for any value of `R` except `Union{}`) is a proper subtype of it, and is therefore also partly the motivation for #24614 (and this PR).

**Comment by JeffBezanson** [comment]
Ok, I may have found a version of this that fixes #31824 too, without needing to change any `convert` methods and without changing that case from GeometryTypes :tada: .

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by maleadt** [comment]
I did a bunch of Nanosoldier development changing the report repo layout, so I had to restart your job:
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34272#issuecomment-572185705) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/2ad0447642b690d0f7890b7f398dc2cfaf3a6f54/by_hash/40298e3_vs_8a19ef8/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Hmm, the correct commit is listed at the top of the report, but in the versioninfo output in the logs it looks like it actually ran with the wrong commit. And indeed GeometryTypes passes locally but failed with the same error in the pkgeval run.

**Comment by maleadt** [comment]
> Hmm, the correct commit is listed at the top of the report, but in the versioninfo output in the logs it looks like it actually ran with the wrong commit.

The commit is always going to be different, because we build the merge commit (which doesn't really exist) instead of the head of this pull request. It's possible that some caching is happening though, and that the previous merge commit was used. I'll have a look.

**Comment by maleadt** [comment]
Trying a more fine-grained run first, as suggested by the report (the system is now busy doing releast-1.4 builds):

@nanosoldier `runtests(["ClusteringGA", "CurrenciesBase", "FameSVD", "GeometryTypes", "Graph500", "HTTP", "IncrementalInference", "JuliaDB", "KissMCMC", "LCMCore", "Lerche", "LoopThrottle", "MbedTLS", "Mocking", "OhMyREPL", "RigidBodyDynamics", "Sched", "StanMamba"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34272#issuecomment-572654835) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/d479b71951555b727dbd9b5e84e38c56c182be94/pkgeval/by_hash/40298e3_vs_538797b/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Ok, IncrementalInference and Sched failures seem to be intermittent, and MbedTLS also crashes on other branches, so this looks OK so far.

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34272#issuecomment-573990654) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/ef11c95ad4682aae1816c2c0c57c44dc1416c78e/pkgeval/by_hash/40298e3_vs_dd79e77/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Starting to look good! QuantumAlgebra has an unreachable instruction to investigate; that's about it.

**Comment by JeffBezanson** [comment]
Fixed! Also double-checked that all the other failing packages pass locally.
This is now ready to merge :tada: :tada:

File: test/subtype.jl [hunk 1]
```diff
@@ -136,6 +136,35 @@ function test_diagonal()
     @test  issub(Tuple{Tuple{T, T}} where T>:Int, Tuple{Tuple{T, T} where T>:Int})
     @test  issub(Vector{Tuple{T, T} where Number<:T<:Number},
                  Vector{Tuple{Number, Number}})
+
+    @test !issub(Type{Tuple{T,Any} where T},   Type{Tuple{T,T}} where T)
```
Comment (martinholters) [inline test/subtype.jl:140]: I'm confused...
```julia
julia> Type{Tuple{T, Any} where T} <: Type{Tuple{Any,Any}} <: Type{Tuple{T, T}} where T
true

julia> Type{Tuple{T, Any} where T} <:                         Type{Tuple{T, T}} where T
false
```
In fact, we have
```julia
julia> Type{Tuple{T, Any} where T} == Type{Tuple{Any,Any}}
true
```
which looks right to me, as `(Tuple{T, Any} where T) == Tuple{Any,Any}`, noting the covariance of `T` here. But `Type{Tuple{Any,Any}} <: Type{Tuple{T, T}} where T` also looks fine: LHS and RHS become equal for one specific choice of `T` on the RHS, namely `Any`. And `T` does not fall under the diagonal rule. (It would if the `where` were inside the `Type{}`.) So that would leave me with the conclusion that `Type{Tuple{T, Any} where T} <: Type{Tuple{T, T}} where T` should hold. Yet here, we test for the opposite. Wrong test or wrong reasoning? (Note that as it is now, this violates transitivity, so there must be a bug somewhere.)

Comment (martinholters) [reply test/subtype.jl:140]: The same violation of transitivity can be observed for this simpler case, BTW:
```julia
julia> Ref{Tuple{T} where T} <: Ref{Tuple{Any}} <: Ref{Tuple{T}} where T
true

julia> Ref{Tuple{T} where T} <:                    Ref{Tuple{T}} where T
false
```
I'd guess we have an issue for this somewhere, but couldn't find one at a quick glance.
