### PR TITLE
fix codegen for getfield of homogeneous tuples

### LINKED ISSUE #34206: Malformed view created by ntuple on master
```
function mre()
  a = [44]
  b = ntuple(_ -> view(a, :), 1)[1]
  @assert pointer(a) == pointer(b)
end
```
The assertion in the above function fails on
```
julia> versioninfo()
Julia Version 1.4.0-DEV.667
Commit acb7bd93fb* (2019-12-27 21:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```
Works fine on 1.3 and it seems like this issue was introduced by the recent layout changes.

### LINKED ISSUE #34207: Unreachable reached
TOMLs attached. This occurs on nightly, but not on 1.0–1.3. On Linux "Unreachable reached" is printed, on macOS, it simply segfaults:

```julia
❯ /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.667 (2019-12-27)
 _/ |\__'_|_|_|\__'_|  |  Commit acb7bd93fb (0 days old master)
|__/                   |

(@v1.4) pkg> activate .
Activating environment at `/private/tmp/crash/Project.toml`
```
```julia
julia> using AtomicLevels, HalfIntegers

julia> function crash(a, b)
           ao,bo = Orbital(:k, a.orb.ℓ),Orbital(:k, b.orb.ℓ)
           i,j = ao ≤ bo ? (1,2) : (2,1)
           uv = (ao,bo)[[i,j]]
           m′m = (abs(a.m[1]), abs(b.m[1]))
           # Intermittent segfault on next line
           m′,m = uv[1] < uv[2] ? m′m[[i,j]] : reverse(minmax(m′m...))
       end
crash (generic function with 1 method)

julia> o = SpinOrbital(o"ks", 0, half(1))
ks₀α

julia> crash(o, o)

signal (11): Segmentation fault: 11
in expression starting at REPL[5]:1
_platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 30720411 (Pool: 30719296; Big: 1115); GC: 6
zsh: segmentation fault  /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia
```
[TOMLs.zip](https://github.com/JuliaLang/julia/files/4007026/TOMLs.zip)

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is an alternative to #34208. Uses the same method as the `typed_load` call for `arrayref`.

fix #34206, fix #34207

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: src/codegen.cpp [hunk 1]
```diff
@@ -2903,8 +2903,11 @@ static bool emit_builtin_call(jl_codectx_t &ctx, jl_cgval_t *ret, jl_value_t *f,
                                 emit_datatype_nfields(ctx, emit_typeof_boxed(ctx, obj)),
                                 jl_true);
                         }
+                        bool isboxed = !jl_datatype_isinlinealloc(jt);
                         Value *ptr = maybe_decay_tracked(data_pointer(ctx, obj));
-                        *ret = typed_load(ctx, ptr, vidx, jt, obj.tbaa, nullptr, false);
+                        *ret = typed_load(ctx, ptr, vidx,
```
Comment (Keno) [inline src/codegen.cpp]: The return cgval gets annotated with the type we pass in. Does widening to `Any` pessimize later codegen?

Comment (JeffBezanson) [reply src/codegen.cpp]: I'd guess not really, since codegen generally uses inferred types when it needs type info. We're also doing the same thing for arrayref on pointer arrays, so it'd better work :stuck_out_tongue:
