### PR TITLE
win32: Fix SEH frame sentinel

### LINKED ISSUE #43569: numbers test crashes under wine
If my debugger stack is to be trusted (and I'm not 100% sure it is), then this originates as a divide by zero in LLVM:
```
=> 0x000000006acc1581 <_ZN12_GLOBAL__N_111DAGCombiner19visitVECTOR_SHUFFLEEPN4llvm6SDNodeE+15969>:	idivl  (%rcx)
   0x000000006acc1583 <_ZN12_GLOBAL__N_111DAGCombiner19visitVECTOR_SHUFFLEEPN4llvm6SDNodeE+15971>:	mov    0x83536(%rip),%rdx        # 0x6ad44ac0 <_ZN4llvm16DAGTypeLegalizer25SoftenFloatRes_FP16_TO_FPEPNS_6SDNodeE+80>
   0x000000006acc158a <_ZN12_GLOBAL__N_111DAGCombiner19visitVECTOR_SHUFFLEEPN4llvm6SDNodeE+15978>:	mov    $0x2,%ecx
   0x000000006acc158f <_ZN12_GLOBAL__N_111DAGCombiner19visitVECTOR_SHUFFLEEPN4llvm6SDNodeE+15983>:	mov    %eax,(%rdx)
   0x000000006acc1591 <_ZN12_GLOBAL__N_111DAGCombiner19visitVECTOR_SHUFFLEEPN4llvm6SDNodeE+15985>:	call   0x6acc1540 <_ZN12_GLOBAL__N_111DAGCombiner19visitVECTOR_SHUFFLEEPN4llvm6SDNodeE+15904>
```

### PR DESCRIPTION
**Pull request by Keno**
The last entry sentinel for Win64 SEH is `~0L` not NULL. Apparently
this doesn't cause issues on windows proper, but does crash wine.
Arguably if Windows doesn't have issues then we should just fix
this in wine, but since we control the source and nobody else
ever seems to have run into this, let's just fix it and save
the good Wine folks some headache. Fixes #43569.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
SGTM. It was supposed to follow this line, which now your fix does:

https://github.com/dlang/druntime/blob/master/src/core/thread/fiber.d#L1269

**Comment by DilumAluthge** [comment]
I noticed that `tester_win32` has now started to fail on master. Could the failures be related to this PR?

Example failure: https://build.julialang.org/#/builders/42/builds/697/steps/5/logs/stdio

**Comment by Keno** [comment]
No, this is win64 only

File: src/win32_ucontext.c [hunk 1]
```diff
@@ -71,7 +71,7 @@ void jl_makecontext(win32_ucontext_t *ucp, void (*func)(void))
     jmpbuf->Rip = (unsigned long long)func;
     jmpbuf->Rsp = (unsigned long long)stack_top;
     jmpbuf->Rbp = 0;
-    jmpbuf->Frame = 0; // SEH frame
+    jmpbuf->Frame = ~0L; // SEH frame
```
Comment (yuyichao) [inline src/win32_ucontext.c:74]: Isn't `long` 32bit on windows?

Comment (Keno) [reply src/win32_ucontext.c:74]: `L` is long long in recent standards versions, but I guess we should just spell this out as `~(uint64_t)0`.
