### PR TITLE
Fixed matrix logarithm

### LINKED ISSUE #415: logm issue
As reported by @iamnapo in https://github.com/JuliaLang/LinearAlgebra.jl/issues/414

```julia
julia> B = [3 2; -5 -3]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> expm(logm(B))
2×2 Array{Float64,2}:
 -5.33599  -5.66504
 17.5616   18.4572
```

### LINKED ISSUE #21179: logm issue
As reported by @iamnapo in https://github.com/JuliaLang/julia/issues/21143#issuecomment-289306668

```julia
julia> B = [3 2; -5 -3]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> expm(logm(B))
2×2 Array{Float64,2}:
 -5.33599  -5.66504
 17.5616   18.4572
```

### PR DESCRIPTION
**Pull request by iamnapo**
Fixed JuliaLang/LinearAlgebra.jl#415

### CODE REVIEW

File: base/linalg/triangular.jl [hunk 1]
```diff
@@ -1757,19 +1757,10 @@ function logm(A0::UpperTriangular{T}) where T<:Union{Float64,Complex{Float64}}
...
-    end
-    while norm(dm1, Inf) > theta[tmax]
-        for i = 1:n
-            d[i] = sqrt(d[i])
-        end
-        for i = 1:n
-            dm1[i] = d[i] - 1
-        end
+    while norm(d-1, Inf) > theta[tmax] && s < maxsqrt
+        d = sqrt.(d)
```
Comment (jebej) [inline base/linalg/triangular.jl]: `d .= sqrt.(d)` for in place update

File: base/linalg/triangular.jl [hunk 2]
```diff
@@ -1964,16 +1955,9 @@ function invsquaring(A0::UpperTriangular, theta)
...
-    for i = 1:n
-        dm1[i] = d[i] - 1
-    end
-    while norm(dm1, Inf) > theta[tmax]
-        for i = 1:n
-            d[i] = sqrt(d[i])
-            dm1[i] = d[i] - 1
-        end
+    while norm(d-1, Inf) > theta[tmax] && s < maxsqrt
+        d = sqrt.(d)
```
Comment (jebej) [inline base/linalg/triangular.jl]: same here

**Comment by tkelman** [comment]
if no one else has any review comments, would be good to squash (without the ci skip) so tests run on that latest change. this looks like a pretty straightforward improvement to me, and doesn't seem to introduce new code with a license to check on.

File: base/linalg/triangular.jl [hunk 3]
```diff
@@ -1757,19 +1757,10 @@ function logm(A0::UpperTriangular{T}) where T<:Union{Float64,Complex{Float64}}
...
-        dm1[i] = d[i] - 1.
-    end
-    while norm(dm1, Inf) > theta[tmax]
-        for i = 1:n
-            d[i] = sqrt(d[i])
-        end
-        for i = 1:n
-            dm1[i] = d[i] - 1
-        end
+    while norm(d-1, Inf) > theta[tmax] && s < maxsqrt
```
Comment (tkelman) [inline base/linalg/triangular.jl]: on second reading... why remove the in place d-1 preallocation?

Comment (iamnapo) [inline base/linalg/triangular.jl]: `dm1` changes again inside the while loop. I think both approaches are equal in time and memory, this one is just shorter. No?

Comment (jebej) [inline base/linalg/triangular.jl]: `norm(d-1)` will allocate a new vector each time, you could do instead
```julia
d = complex(diag(A))
dm1 = d .- 1
while norm(dm1, Inf) > theta[tmax] && s < maxsqrt
    d .= sqrt.(d)
    dm1 .= d .- 1
    s = s + 1
end
```

Comment (iamnapo) [inline base/linalg/triangular.jl]: Oh, ok. I'll change it

Comment (jebej) [inline base/linalg/triangular.jl]: it's really what was there before but with the new dot notation

File: base/linalg/triangular.jl [hunk 4]
```diff
@@ -1758,6 +1758,7 @@ function logm(A0::UpperTriangular{T}) where T<:Union{Float64,Complex{Float64}}
 
     # Compute repeated roots
     d = complex(diag(A))
+    dm1 = Vector{T}(n)
```
Comment (tkelman) [inline base/linalg/triangular.jl]: this one isn't necessary, and the one below wouldn't be if you used `dm1 = d .- 1` or `dm1 = d - 1` instead of `dm1 .= d .- 1`

the `.=` is in place, `=` allocates a new vector

File: base/linalg/dense.jl [hunk 5]
```diff
@@ -554,37 +554,33 @@ julia> logm(A)
...
     end
     if ishermitian(A)
-        return full(logm(Hermitian(A)))
+        return logm(Hermitian(A))
     end
 
     # Use Schur decomposition
     n = checksquare(A)
     if istriu(A)
         retmat = full(logm(UpperTriangular(complex(A))))
```
Comment (tkelman) [inline base/linalg/dense.jl]: purely a style point, but looks like we don't need a variable for retmat with this version, could replace each `retmat =` with `return` ?

File: test/linalg/dense.jl [hunk 6]
```diff
@@ -481,6 +481,32 @@ end
     @test expm(A10) ≈ eA10
 end
 
+@testset "Additional matrix logarithm tests" for elty in (Float64, Complex{Float64})
+    A11 = convert(Matrix{elty}, [3 2; -5 -3])
+    @test expm(logm(A11)) ≈ A11
+
+    A12 = convert(Matrix{elty}, [1 -1; 1 -1])
+    @test typeof(logm(A12)) <: AbstractMatrix
```
Comment (tkelman) [inline test/linalg/dense.jl]: could this be more specific?

**Review by tkelman — APPROVED** [review]
looks good to me if it passes tests. should be squashed on merge if not before (and the ci skip removed from the intermediate commit message when squashing)
