### PR TITLE
don't make a copy on the stack when creating a new symbol (fixes #12569)

### LINKED ISSUE #12569: Segfault in `symbol(rand(n))` for large n
See below.

```julia
Davids-MBP:julia David$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6625 (2015-08-11 16:56 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f3cbf09 (0 days old master)
|__/                   |  x86_64-apple-darwin14.4.0

julia> A = [1:5_000_000...];

julia> symbol(A)
ERROR: ReadOnlyMemoryError()
 in symbol at ./expr.jl:6
 in symbol at expr.jl:10

julia> A = rand(5_000_000);

julia> symbol(A)

signal (11): Segmentation fault: 11
jl_symbol_n at /Users/David/julia/src/alloc.c:461
symbol at ./expr.jl:6
symbol at expr.jl:10
jl_apply at /Users/David/julia/src/gf.c:1657
jl_apply at /Users/David/julia/src/interpreter.c:55
eval at /Users/David/julia/src/interpreter.c:213
jl_toplevel_eval_flex at /Users/David/julia/src/toplevel.c:525
jl_toplevel_eval_in at /Users/David/julia/src/builtins.c:567
eval_user_input at REPL.jl:63
jlcall_eval_user_input_21072 at  (unknown line)
anonymous at task.jl:92
jl_apply at /Users/David/julia/src/task.c:231
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by stevengj**
This avoids making a copy in `jl_symbol_n`, which was only happening to guarantee that we add a NUL terminator to the string (which was probably there already).  Instead, it just passes the string length around as needed.  (Fixes #12569.)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Doesn't this mean we could also support symbols with embedded NULs? (Not that I have any plan to use this, but it seems like a pointless limitation.)

**Comment by stevengj** [comment]
@StefanKarpinski, no, this patch is not sufficient for that.  The assumption that symbols are NUL-terminated strings is all over the place.

File: src/alloc.c [hunk 1]
```diff
@@ -414,18 +414,18 @@ static void unmark_symbols_(jl_sym_t *root)
...
-    uptrint_t h = hash_symbol(str, strlen(str));
+    uptrint_t h = hash_symbol(str, len);
 
     // Tree nodes sorted by major key of (int(hash)) and minor key o (str).
     while (*ptree != NULL) {
         x = (int)(h-(*ptree)->hash);
         if (x == 0) {
-            x = strcmp(str, (*ptree)->name);
-            if (x == 0)
+            x = strncmp(str, (*ptree)->name, len);
```
Comment (yuyichao) [inline src/alloc.c]: Could also be `memcmp`?

**Comment by yuyichao** [comment]
The `jl_tagged_gensym` function below is doing something very similar. Maybe we should fix that one as well?

File: src/alloc.c (hunk 1 above)
Comment (stevengj) [inline src/alloc.c]: No, because `(*ptree)->name` might be shorter than `len`.

Comment (yuyichao) [inline src/alloc.c]: Ahh right nvm

**Comment by stevengj** [comment]
@yuyichao, updated to fix `jl_tagged_gensym`.

File: src/alloc.c (hunk 1 above)
Comment (vtjnash) [inline src/alloc.c]: since they are constructed to be null terminated with no embedded null characters, it likely could be `memcmp` (it'll also stop at the first difference), but this should be the same

**Comment by stevengj** [comment]
Hmm, I can't reproduce the test failure, must be a problem with merge?  I'll try another rebase.

**Comment by stevengj** [comment]
This is a new one to me: `git rebase` succeeded with no errors, but left `<<<<<<< HEAD` in `test/core.jl`.  So it's a git bug.

File: src/alloc.c (hunk 1 above)
Comment (stevengj) [inline src/alloc.c]: @vtjnash, that is not guaranteed by the `memcmp` spec, and is probably [not true in practice](http://blogs.msdn.com/b/oldnewthing/archive/2010/10/14/10075623.aspx) because optimized `memcmp` implementations will read multiple bytes at a time, e.g. into SIMD registers.

**Comment by tkelman** [comment]
I'm working on a small set of backports for a likely-final 0.3.x release. Do you still want this on release-0.3? There are quite a few conflicts as `alloc.c` changed substantially in the GC rewrite. I can resolve most of them in what seem like the correct direction to me, but `jl_argumenterror_type` is not present anywhere on release-0.3 so the actual exception throwing part of this would require finding additional backports.
