### PR TITLE
Broaden signature of eigen and eigvals to AbstractMatrix to allow for Adjoint and Transpose input.

### LINKED ISSUE #551: LinearAlgebra.eigen fails on Transposed / Adjoint matrices (Julia 1.0.0)
The `eigen` / `eigen!` functions of the `LinearAlgebra` package fail with the `Adjoint` and `Transposed` types.

Given a square matrix `A` (e.g. a `10×10 Array{Float64,2}`), both the following statements fail:
`E = eigen(A')`
`E = eigen(transpose(A))`
with errors
`ERROR: MethodError: no method matching eigen(::Adjoint{Float64,Array{Float64,2}})`
and 
`ERROR: MethodError: no method matching eigen(::Transpose{Float64,Array{Float64,2}})`
respectively.

A simple fix could be to define the method
`LinearAlgebra.eigen(x::Union{Transpose{T, A}, Adjoint{T, A}}) where {T, A<:AbstractMatrix} = eigen(copy(x))` (credit: Twan Koolen on discourse).

However, it could be more efficient to use LAPACK functions directly computing left eigenvectors (i.e. eigenvectors of the transposed) without making another copy of the matrix. It looks like the wrapper `LinearAlgebra.LAPACK.geevx!` has such a feature. In `eigen.jl`, the lower level LAPACK call (line 40 as of tag `v1.0.0`) is
`A, WR, WI, VL, VR, _ = LAPACK.geevx!(permute ? (scale ? 'B' : 'P') : (scale ? 'S' : 'N'), 'N', 'V', 'N', A)`
According to the [documentation](https://docs.julialang.org/en/v1.0.0/stdlib/LinearAlgebra/#LinearAlgebra.LAPACK.geevx!),
`A, WR, WI, VL, VR, _ = LAPACK.geevx!(permute ? (scale ? 'B' : 'P') : (scale ? 'S' : 'N'), 'V', 'N', 'N', A)`
should compute left eigenvectors instead. 

I am very new to Julia (I have been mostly a Matlab programmer so far), so I am not quite sure what is a clean way to insert such a fix into `eigen.jl`. At least, duplicating the `eigen!` code in `eigen.jl` does not seem to be a very good idea. Also, adding this may not cover all `eigen` methods for special matrices. (The `eigen!` method in `eigen.jl` applies to `StridedMatrix{T}`, which I assume excludes at least sparse matrices.)

Note: this issue is similar to Issue JuliaLang/LinearAlgebra.jl#523 regarding `svdfact` (now `svd`)  which was fixed in PR JuliaLang/julia#27916 . The fix for `svd` will not work here though.

### LINKED ISSUE #28714: LinearAlgebra.eigen fails on Transposed / Adjoint matrices (Julia 1.0.0)
The `eigen` / `eigen!` functions of the `LinearAlgebra` package fail with the `Adjoint` and `Transposed` types.

Given a square matrix `A` (e.g. a `10×10 Array{Float64,2}`), both the following statements fail:
`E = eigen(A')`
`E = eigen(transpose(A))`
with errors
`ERROR: MethodError: no method matching eigen(::Adjoint{Float64,Array{Float64,2}})`
and 
`ERROR: MethodError: no method matching eigen(::Transpose{Float64,Array{Float64,2}})`
respectively.

A simple fix could be to define the method
`LinearAlgebra.eigen(x::Union{Transpose{T, A}, Adjoint{T, A}}) where {T, A<:AbstractMatrix} = eigen(copy(x))` (credit: Twan Koolen on discourse).

However, it could be more efficient to use LAPACK functions directly computing left eigenvectors (i.e. eigenvectors of the transposed) without making another copy of the matrix. It looks like the wrapper `LinearAlgebra.LAPACK.geevx!` has such a feature. In `eigen.jl`, the lower level LAPACK call (line 40 as of tag `v1.0.0`) is
`A, WR, WI, VL, VR, _ = LAPACK.geevx!(permute ? (scale ? 'B' : 'P') : (scale ? 'S' : 'N'), 'N', 'V', 'N', A)`
According to the [documentation](https://docs.julialang.org/en/v1.0.0/stdlib/LinearAlgebra/#LinearAlgebra.LAPACK.geevx!),
`A, WR, WI, VL, VR, _ = LAPACK.geevx!(permute ? (scale ? 'B' : 'P') : (scale ? 'S' : 'N'), 'V', 'N', 'N', A)`
should compute left eigenvectors instead. 

I am very new to Julia (I have been mostly a Matlab programmer so far), so I am not quite sure what is a clean way to insert such a fix into `eigen.jl`. At least, duplicating the `eigen!` code in `eigen.jl` does not seem to be a very good idea. Also, adding this may not cover all `eigen` methods for special matrices. (The `eigen!` method in `eigen.jl` applies to `StridedMatrix{T}`, which I assume excludes at least sparse matrices.)

Note: this issue is similar to Issue #27132 regarding `svdfact` (now `svd`)  which was fixed in PR #27916 . The fix for `svd` will not work here though.

### PR DESCRIPTION
**Pull request by andreasnoack**
The is a very simple fix of JuliaLang/LinearAlgebra.jl#551. Eventually, we might be able to avoid materializing the adjoint, but the benefit will in most cases be very limited so I think we should add the simple fix right away.

Fixes JuliaLang/LinearAlgebra.jl#551

### CODE REVIEW

**Comment by kragol** [comment]
Thanks @andreasnoack for addressing the issue. You may also want to look at the `eigen(A,B)` methods for generalized eigenvalue decomposition (or even some other functions like `cholesky`, `lq` or `schur` which have issues with `Adjoint` or `Transpose` types too).

File: stdlib/LinearAlgebra/test/eigen.jl [hunk 1]
```diff
@@ -132,4 +132,12 @@ end
     @test factstring == "$(summary(e))\neigenvalues:\n$valsstring\neigenvectors:\n$vecsstring"
 end
 
+@testset "eigen of an Adjoint" begin
+    A = randn(3,3)
+    @test eigvals(A') == eigvals(copy(A'))
+    @test eigen(A')   == eigen(copy(A'))
+end
+
+end
```
Comment (fredrikekre) [inline stdlib/LinearAlgebra/test/eigen.jl]:
```suggestion
```

File: stdlib/LinearAlgebra/test/eigen.jl [hunk 2]
```diff
@@ -132,4 +132,11 @@ end
     @test factstring == "$(summary(e))\neigenvalues:\n$valsstring\neigenvectors:\n$vecsstring"
 end
 
+@testset "eigen of an Adjoint" begin
+    A = randn(3,3)
+    @test eigvals(A') == eigvals(copy(A'))
+    @test eigen(A')   == eigen(copy(A'))
+end
```
Comment (nickrobinson251) [inline stdlib/LinearAlgebra/test/eigen.jl]: Is it worth explicity testing `eigmin` and `eigmax` too?
```suggestion
    @test eigmin(A') == eigmin(copy(A'))
    @test eigmax(A') == eigmax(copy(A'))
end
```

**Review by nickrobinson251 — COMMENTED** [review]
Fixes https://github.com/JuliaLang/julia/issues/31843 too

So maybe worth testing that case?
