### PR TITLE
Enable analyzegc checks for try catch and fix found issues

### LINKED ISSUE #53491: Still gc crash
It seems there are still some problems in the gc with the recent master, despite the fix in  #53355.

I'm running 
```
Julia Version 1.12.0-DEV.89
Commit 35cb8a556b* (2024-02-27 06:12 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen Threadripper PRO 5945WX 12-Cores
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 24 virtual cores)
Environment:
  JULIA_EDITOR = emacs -nw
```
compiled and installed on this machine.

Here is an MWE which frequently results in  a crash. It runs fine in version `1.10.1` installed from snap on Ubuntu 23.10.

```
using .Threads

function fun(N)
    parts = Iterators.partition(1:N, 1 + N ÷ nthreads())

    tasks = [@spawn begin
                 s = Vector{Float64}(undef, length($part))
                 base = first($part)
                 for i in $part
                     s[i-base+1] = 1/i
                 end
                 return s
             end for part in parts]

    mapreduce(vcat, tasks) do t
        fetch(t)::Vector{Float64}
    end
end

println(sum(fun(42)))

println(sum(fun(10_000_000)))
```

Without the line with `fun(42)` it seems to work. 

With the above program in the file `crash.jl`, a typical crash looks like
```
$ julia -t 12 -e 'include("crash.jl")'
4.326742806648339
GC error (probable corruption)
C error (probable corruption)
Allocations: 618918 (Pool: 618895; Big: 23); GC: 1
Allocations: 618918 (Pool: 618895; Big: 23); GC: 1

!!! ERROR in jl_ -- ABORTING !!!

!!! ERROR in jl_ -- ABORTING !!!
GC error (probable corruption)

[1214416] signal 6 (-6): Aborted

[1214416] si618918 (Pool: 618895; Big: 23); GC: 1
in expression starting at none:0
 Big: 23); in expression starting at none:0
Allocations: 618918 (Pool: 618895; Big: 23); GC: 1
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by gbaraldi**
This PR also makes a successful `JL_TRY` not do so much work + fixes clang not finding the sdk when running those tests in macos. 
Fixes https://github.com/JuliaLang/julia/issues/53491

### CODE REVIEW

File: src/rtutils.c [hunk 1]
```diff
@@ -260,9 +260,18 @@ JL_DLLEXPORT void jl_enter_handler(jl_handler_t *eh)
...
+JL_DLLEXPORT void jl_eh_restore_state(jl_handler_t *eh, int had_exception)
 {
+    // It's always correct to pass 1 to had_exception, but it can be unnecessary if we know there was no exception.
     jl_task_t *ct = jl_current_task;
+    if (!had_exception) {
+        ct->eh = eh->prev;
+        ct->gcstack = eh->gcstack;
+        ct->world_age = eh->world_age;
+        ct->ptls->defer_signal = eh->defer_signal;
+        return;
```
[the remark this answers is not in the document]
Comment (topolarity) [reply src/rtutils.c:273]: What's the error you get from the static analyzer?

Do you have a branch to play with?

File: src/julia.h [hunk 2]
```diff
@@ -2337,24 +2337,32 @@ extern void (*real_siglongjmp)(jmp_buf _Buf, int _Value);
...
 // flow edges. But for now, just hide this as best we can
-extern int had_exception;
-#define JL_TRY if (1)
-#define JL_CATCH if (had_exception)
+#define JL_TRY                                                    \
+    int i__try, i__catch; jl_handler_t __eh;                          \
+    size_t __excstack_state = jl_excstack_state();                \
+    jl_enter_handler(&__eh);                                      \
+    for (i__try=2; i__try; i__try--)                                 \
+        if (i__try==2)                                             \
```
Comment (topolarity) [inline src/julia.h:2348]: I don't think this models that we can enter the catch block from part-way through the try block, so it seems like this is still unsound?

File: src/julia.h [hunk 3]
```diff
@@ -2337,24 +2338,34 @@ extern void (*real_siglongjmp)(jmp_buf _Buf, int _Value);
...
 #ifdef __clang_gcanalyzer__
 
-// This is hard. Ideally we'd teach the static analyzer about the extra control
-// flow edges. But for now, just hide this as best we can
 extern int had_exception;
-#define JL_TRY if (1)
-#define JL_CATCH if (had_exception)
+
+// The analyzer assumes that the TRY block always executes to completion because we do not model throwing
+// This means it might add both false positives and negatives, because it doesn't model the fact that we can leave the try block early (by erroring).
```
Comment (topolarity) [inline src/julia.h:2344]:
```suggestion
// The analyzer assumes that the TRY block always executes to completion.
// This can lead to both false positives and false negatives, since it doesn't model the fact that throwing always leaves the try block early.
```

**Review by JeffBezanson — APPROVED** [review]

**Comment by giordano** [comment]
Does this need a test?  #53491 has a reproducer, although it isn't systematic.

File: src/rtutils.c [hunk 4]
```diff
@@ -297,6 +297,16 @@ JL_DLLEXPORT void jl_eh_restore_state(jl_handler_t *eh)
...
+{
+    jl_task_t *ct = jl_current_task;
+    ct->eh = eh->prev;
+    ct->gcstack = eh->gcstack;
+    ct->world_age = eh->world_age;
+    ct->ptls->defer_signal = eh->defer_signal;
+    return;
+}
+
 JL_DLLEXPORT void jl_pop_handler(int n)
```
Comment (vtjnash) [inline src/rtutils.c:310]: The PR LGTM. Just a note though that codegen always calls this function exclusively, even though it knows `n` is constant and probably also therefore usually knows `eh`. Which means it may be able to optimize that performance by calling `jl_eh_restore_state_noexcept` directly. But in the meantime, jl_pop_handler should call this new function too and be marked JL_NOTSAFEPOINT. Similarly, in interpreter.c, you can split the call to `jl_eh_restore_state` into the `continue_at` and `catch` cases there for consistency with this.

File: src/jloptions.c [hunk 5]
```diff
@@ -859,7 +859,7 @@ JL_DLLEXPORT void jl_parse_opts(int *argcp, char ***argvp)
                 if (isnan(sz) || sz < 0) {
                     jl_errorf("julia: invalid argument to --heap-size-hint (%s)", optarg);
                 }
-                jl_options.heap_size_hint = sz < UINT64_MAX ? (uint64_t)sz : UINT64_MAX;
+                jl_options.heap_size_hint = (uint64_t)sz < UINT64_MAX ? (uint64_t)sz : UINT64_MAX;
```
Comment (topolarity) [inline src/jloptions.c:862]:
```suggestion
                const long double limit = ldexpl(1.0, 64); // UINT64_MAX + 1;
                jl_options.heap_size_hint = sz < limit ? (uint64_t)sz : UINT64_MAX;
```

File: src/rtutils.c [hunk 6]
```diff
@@ -297,6 +297,16 @@ JL_DLLEXPORT void jl_eh_restore_state(jl_handler_t *eh)
...
 }
 
+JL_DLLEXPORT void jl_eh_restore_state_noexcept(jl_handler_t *eh)
+{
+    jl_task_t *ct = jl_current_task;
+    ct->eh = eh->prev;
+    ct->gcstack = eh->gcstack;
+    ct->world_age = eh->world_age;
+    ct->ptls->defer_signal = eh->defer_signal;
+    return;
```
Comment (vtjnash) [inline src/rtutils.c:307]:
```suggestion
```
None of these are actually relevant/required. The gc-analysis static pass would already detect violations of this

**Comment by vtjnash** [comment]
```julia
julia> f() = try; GC.safepoint(); finally; end
f (generic function with 2 methods)

julia> @btime f()
  21.514 ns (0 allocations: 0 bytes) # master
  11.170 ns (0 allocations: 0 bytes) # PR
```

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/53527#issuecomment-1998297819) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/91b045a_vs_0f04b33/report.md).
