### PR TITLE
fix with_output_color to pass along iocontext

### LINKED ISSUE #18711: Base.with_output_color should pass on the IOContext properties
```jl
julia> buf = IOContext(IOBuffer(), :hello => "Hello World")
IOContext(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1))

julia> Base.with_output_color(:red, buf) do buf
           print(get(buf, :hello, "Sadness"))
       end
Sadness

julia> print(get(buf, :hello, "Sadness"))
Hello World
```

### PR DESCRIPTION
**Pull request by KristofferC**
fixes #18711

### CODE REVIEW

File: base/util.jl [hunk 1]
```diff
@@ -301,8 +301,9 @@ end
 
 function with_output_color(f::Function, color::Union{Int, Symbol}, io::IO, args...)
     buf = IOBuffer()
+    buf_context = IOContext(io, buf)
```
Comment (vtjnash) [inline base/util.jl]: shouldn't this be `IOContext(buf, io)`?

Comment (KristofferC) [inline base/util.jl]: You are right. That was bad... Will add a test for `print_with_color` that would have caught this.

Comment (KristofferC) [inline base/util.jl]: Updated. Testing `print_with_color` is kinda awkward because it only looks at the global variable in base. I evaled into it but maybe that is not ok.

File: test/misc.jl [hunk 2]
```diff
@@ -452,3 +452,26 @@ if is_windows()
         err18083 == 0 && error(Libc.GetLastError())
     end
 end
+
+let
+    old_have_color = Base.have_color
+     try
```
Comment (tkelman) [inline test/misc.jl]: indent is off

File: test/misc.jl [hunk 3]
```diff
@@ -452,3 +452,26 @@ if is_windows()
...
+
+let
+    global c_18711 = 0
+    buf = IOContext(IOBuffer(), :hascontext => true)
+    Base.with_output_color(:red, buf) do buf
+        global c_18711
+        get(buf, :hascontext, false) && (c_18711 += 1)
+    end
+    @test c_18711 == 1
+
```
Comment (tkelman) [inline test/misc.jl]: remove the unnecessary blank line

File: test/misc.jl (hunk 2 above)
Comment (KristofferC) [inline test/misc.jl]: fixed

File: test/misc.jl (hunk 3 above)
Comment (KristofferC) [inline test/misc.jl]: fixed

**Comment by KristofferC** [comment]
Any further comments? Is it worth to always create the IOContext or should that be conditioned on that the input is an IOContext itself?

**Review by vtjnash — APPROVED** [review]
