### PR TITLE
[JuliaLowering] Fix `@nospecialize`

### LINKED ISSUE #166: "expected identifier or `identifier::type`" when using JuliaLowering-evaluated (old-style) `@nospecialize` macro
An "old-style" copy of `@nospecialize` (taken from bootstrap) does not work:
```julia
macro _nospecialize(vars...)
    if nfields(vars) === 1
        # in argument position, need to fix `@nospecialize x=v` to `@nospecialize (kw x v)`
        var = getfield(vars, 1)
        if isa(var, Expr) && var.head === :(=)
            var.head = :kw
        end
    end
    return Expr(:escape, Expr(:meta, :nospecialize, vars...))
end

(obj::Returns)(@_nospecialize(args...); @_nospecialize(kw...)) = obj.value
```

<details>
<summary>
Full Error
</summary>

```julia
┌ Info: JuliaLowering threw given input:
│   code =
│    :((obj::Returns)(#= /home/topolarity/repos/julia/base/mwe2.jl:5 =# @nospecialize(args...); #= /home/topolarity/repos/julia/base/mwe2.jl:5 =# @nospecialize(kw...)) = begin
│              #= /home/topolarity/repos/julia/base/mwe2.jl:5 =#
│              obj.value
│          end)
│   st0 =
│    SyntaxTree with attributes mod,kind,var_id,toplevel_pure,scope_type,name_val,syntax_flags,meta,scope_layer,value,jl_source,is_toplevel_thunk,source,__macro_ctx__
│    [=]                                                          │
│      [call]                                                     │
│        [::]                                                     │
│          obj                                :: Identifier       │
│          Returns                            :: Identifier       │
│        [parameters]                                             │
│          [macrocall]                                            │
│            @nospecialize                    :: Identifier       │
│            :(#= /home/topolarity/repos/julia/base/mwe2.jl:5 =#) :: Value │
│            [...]                                                │
│              kw                             :: Identifier       │
│        [macrocall]                                              │
│          @nospecialize                      :: Identifier       │
│          :(#= /home/topolarity/repos/julia/base/mwe2.jl:5 =#) :: Value │
│          [...]                                                  │
│            args                             :: Identifier       │
│      [block]                                                    │
│        [.]                                                      │
│          obj                                :: Identifier       │
│          [inert]                                                │
│            value                            :: Identifier       │
│
│   st1 =
│    SyntaxTree with attributes toplevel_pure,scope_type,name_val,syntax_flags,meta,scope_layer,mod,kind,value,var_id,jl_source,is_toplevel_thunk,source
│    [=]                                                          │
│      [call]                                                     │
│        [::]                                                     │
│          obj                                :: Identifier       │ scope_layer=1
│          Returns                            :: Identifier       │ scope_layer=1
│        [parameters]                                             │
│          [meta]                                                 │
│            nospecialize                     :: Identifier       │ scope_layer=1
│            [...]                                                │
│              kw                             :: Identifier       │ scope_layer=1
│        [meta]                                                   │
│          nospecialize                       :: Identifier       │ scope_layer=1
│          [...]                                                  │
│            args                             :: Identifier       │ scope_layer=1
│      [block]                                                    │
│        [.]                                                      │
│          obj                                :: Identifier       │ scope_layer=1
│          [inert]                                                │
│            value                            :: Identifier       │
│
│   file = "/home/topolarity/repos/julia/base/mwe2.jl"
│   line = 5
└   mod = Main
ERROR: LoadError: LoweringError:
#= /home/topolarity/repos/julia/base/mwe2.jl:5 =# - expected identifier or `identifier::type`
Expression:
  (meta nospecialize (... kw))
Containing expressions:
  (= (call (:: obj Returns) (parameters (meta nospecialize (... kw))) (meta nospecialize (... args))) (block (. obj (inert value))))

Detailed provenance:
  (meta nospecialize (... kw))
  └─ (meta nospecialize (... kw))
     ├─ (meta nospecialize (... kw))
     │  └─ @ /home/topolarity/repos/julia/base/mwe2.jl:5
     └─ (macrocall @nospecialize :(#= /home/topolarity/repos/julia/base/mwe2.jl:5 =#) (... kw))
        └─ @ /home/topolarity/repos/julia/base/mwe2.jl:5

Stacktrace:
 [1] expand_forms_2(ctx::Base.JuliaLowering.MacroExpansionContext{Dict{Symbol, Any}}, ex::Base.JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
   @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:4474
 [2] core_lowering_hook(code::Any, mod::Module, file::String, line::UInt64, world::UInt64, _warn::Bool)
   @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/hooks.jl:28
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:323
 [4] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:344
 [5] _start()
   @ Base ./client.jl:585
in expression starting at /home/topolarity/repos/julia/base/mwe2.jl:5
```
</details>

```julia
julia> (obj::Returns)(@nospecialize(args...); @nospecialize(kw...)) = obj.value # works

julia> (obj::Returns)(@_nospecialize(args...); @_nospecialize(kw...)) = obj.value # fails
┌ Info: JuliaLowering threw given input:
```

### PR DESCRIPTION
**Pull request by mlechu**
Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/166 and related bugs:
- "new" `@nospecialize` should produce the same form as "old" `@nospecialize`
- Fix validation rejecting nospecialize on kwargs
- Fix function-body `@nospecialize` not propagating to wrapper methods (in optional positional and kw cases).  Femtolisp lowering does this by storing meta statements in the beginning of all method bodies and juggling that (usually in a variable named `prologue`) in function desugaring.  It isn't a great deal cleaner, but this PR absorbs meta statements from the body and stores it in the function's params in `est_to_dst` so desugaring doesn't need to worry about it.
- Bundle lowered `meta nospecialize` into one statement like flisp instead of one per slot

Note this implementation will have `method.nospecialize == -1` when everything is marked nospecialize (same as flisp), but also when each individual param is marked, i.e. `function f(x,y); @nospecialize(); end` and `function f(@nospecialize(x), @nospecialize(y)); end` are the same.  I'm hoping this can become a slot flag rather than IR-meta in the future.

TODO: There are a number of places we should inform users when `@nospecialize` is a no-op, but this isn't specific to JL.

### CODE REVIEW

**Comment by jakobnissen** [comment]
See also this issue, would be nice to fix while `@nospecialize` is being re-implemented: https://github.com/JuliaLang/julia/issues/49512

**Comment by topolarity** [comment]
Good changes overall, but it looks like this picked up a small regression:
```julia
function instanceof_tfunc(@nospecialize(t), astag::Bool=false, @nospecialize(troot) = t); end
```

which means it's a ripe time to add `Compiler` to the JL-stdlib tests 🙂

**Comment by mlechu** [comment]
That's funny, thanks for finding this.  flisp lowering doesn't actually mark `troot` nospecialize in that example, so maybe it should be an error?

**Comment by topolarity** [comment]
> That's funny, thanks for finding this. flisp lowering doesn't actually mark `troot` nospecialize in that example, so maybe it should be an error?

I worry this won't be hard to find in the ecosystem hah, but spiritually I agree otherwise

File: JuliaLowering/test/functions.jl [hunk 1]
```diff
@@ -478,20 +484,110 @@ end
...
+            @nospecialize x
+            (x, y)
+        end
+        (f_body_nospecialize_nontrivial_sig2(10, [20]), f_body_nospecialize_nontrivial_sig2(30))
+    end
+    """) == ((10, [20]), (30, []))
+    test_arg_unspecialized(test_mod.f_body_nospecialize_nontrivial_sig2, 1)
+    test_arg_specialized(test_mod.f_body_nospecialize_nontrivial_sig2, 2)
+
+    @testset "all positional arg forms" for arg0 in [:x, :(x::Type), :(::Type), :(_), :(_::Type)],
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:519]: Should this include defaults / optional args?

**Review by topolarity — APPROVED** [review]
Changes look good to me. Thanks @mlechu !

It would be good to test the `@nospecialize` edge case we hit (unless I missed it). More long-term, we probably also need to fuzz with a full argument grammar at some point (incl. `@nospecialize`, kwargs, defaults / optional args, destructuring, sparams, etc.) given how much desugaring logic is dedicated to these and how many surprising interactions there are.

But that certainly doesn't have to be part of this PR. This is a great improvement in behavior and coverage for now.

File: JuliaLowering/test/functions.jl (hunk 1 above)
Comment (mlechu) [reply JuliaLowering/test/functions.jl:519]: Two lines below!

File: JuliaLowering/test/functions_ir.jl [hunk 2]
```diff
@@ -1170,6 +1170,54 @@ end
 11  TestMod.f
 12  (return %₁₁)
 
+########################################
+# Error: nospecialize should be outermost expr in arg
+function f_bad_nospecialize(@nospecialize(x)=1); end
+#---------------------
+LoweringError:
+function f_bad_nospecialize(@nospecialize(x)=1); end
+#                           └──────────────┘ ── expected identifier or `identifier::type`
```
Comment (mlechu) [inline JuliaLowering/test/functions_ir.jl:1179]: This test also at least tracks what we're doing in the edge case we saw.  Behaviour may change.
