### PR TITLE
fix internal IR corruption from use of a global

### LINKED ISSUE #39508: internal IR corruption from use of a local variable assigned in a try block
There's two optimizer errors here (compare to `--compile=min`): one is that `errio` is supposed to be assigned in the catch block, two is that it shouldn't print Internal error. This bug was introduced between v0.6 and v0.7.
```julia
julia> function etset()
       local errio
       try
       errio = stderr::IO
       f(errio)
       catch
       errio
       end
       end
etset (generic function with 1 method)

julia> etset()
Internal error: encountered unexpected error during compilation of etset:
ErrorException("unsupported or misplaced expression "undefcheck" in function etset")
jl_errorf at /data/vtjnash/julia/src/rtutils.c:77
emit_expr at /data/vtjnash/julia/src/codegen.cpp:4732
emit_ssaval_assign at /data/vtjnash/julia/src/codegen.cpp:4031
emit_stmtpos at /data/vtjnash/julia/src/codegen.cpp:4273 [inlined]
emit_function at /data/vtjnash/julia/src/codegen.cpp:7013
jl_emit_code at /data/vtjnash/julia/src/codegen.cpp:7378
jl_emit_codeinst at /data/vtjnash/julia/src/codegen.cpp:7423
_jl_compile_codeinst at /data/vtjnash/julia/src/jitlayers.cpp:124
jl_generate_fptr at /data/vtjnash/julia/src/jitlayers.cpp:352
jl_compile_method_internal at /data/vtjnash/julia/src/gf.c:1978
jl_compile_method_internal at /data/vtjnash/julia/src/gf.c:1932 [inlined]
_jl_invoke at /data/vtjnash/julia/src/gf.c:2237 [inlined]
jl_apply_generic at /data/vtjnash/julia/src/gf.c:2427
jl_apply at /data/vtjnash/julia/src/julia.h:1737 [inlined]
do_call at /data/vtjnash/julia/src/interpreter.c:117
eval_value at /data/vtjnash/julia/src/interpreter.c:206
eval_stmt_value at /data/vtjnash/julia/src/interpreter.c:157 [inlined]
eval_body at /data/vtjnash/julia/src/interpreter.c:588
jl_interpret_toplevel_thunk at /data/vtjnash/julia/src/interpreter.c:717
top-level scope at REPL[15]:1
jl_toplevel_eval_flex at /data/vtjnash/julia/src/toplevel.c:884
jl_toplevel_eval_flex at /data/vtjnash/julia/src/toplevel.c:829
jl_toplevel_eval_flex at /data/vtjnash/julia/src/toplevel.c:829
jl_toplevel_eval_in at /data/vtjnash/julia/src/toplevel.c:936
eval at ./boot.jl:369 [inlined]
eval_user_input at /data/vtjnash/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:139
repl_backend_loop at /data/vtjnash/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:200
start_repl_backend at /data/vtjnash/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:185
#run_repl#42 at /data/vtjnash/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:317
run_repl at /data/vtjnash/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:305
_jl_invoke at /data/vtjnash/julia/src/gf.c:2226 [inlined]
jl_apply_generic at /data/vtjnash/julia/src/gf.c:2427
#913 at ./client.jl:394
unknown function (ip: 0x7f1dca4f222f)
_jl_invoke at /data/vtjnash/julia/src/gf.c:2226 [inlined]
jl_apply_generic at /data/vtjnash/julia/src/gf.c:2427
jl_apply at /data/vtjnash/julia/src/julia.h:1737 [inlined]
jl_f__call_latest at /data/vtjnash/julia/src/builtins.c:728
#invokelatest#2 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:708 [inlined]
run_main_repl at ./client.jl:379
exec_options at ./client.jl:309
_start at ./client.jl:492
jfptr__start_20617 at /data/vtjnash/julia/usr/lib/julia/sys.so (unknown line)
_jl_invoke at /data/vtjnash/julia/src/gf.c:2226 [inlined]
jl_apply_generic at /data/vtjnash/julia/src/gf.c:2427
jl_apply at /data/vtjnash/julia/src/julia.h:1737 [inlined]
true_main at /data/vtjnash/julia/src/jlapi.c:557
repl_entrypoint at /data/vtjnash/julia/src/jlapi.c:699
main at /data/vtjnash/julia/cli/loader_exe.c:51
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at ./julia (unknown line)
ERROR: 

UndefVarError: errio not defined
Stacktrace:
 [1] etset()
   @ Main ./REPL[14]:7
 [2] top-level scope
   @ REPL[15]:1

caused by: UndefVarError: f not defined
Stacktrace:
 [1] etset()
   @ Main ./REPL[14]:5
 [2] top-level scope
   @ REPL[15]:1
```

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #39508

### CODE REVIEW

**Comment by Keno** [comment]
Can we come up with a form that is always legal to have here? Requiring the type lifting pass to be run seems like a code smell.

File: base/compiler/ssair/passes.jl [hunk 1]
```diff
@@ -548,11 +548,12 @@ function getfield_elim_pass!(ir::IRCode)
             # Also, we should probably have a version of typeassert
             # that's defined not to return its value to make life easier
             # for the backend.
-            pi = insert_node_here!(compact,
-                PiNode(stmt.args[2], compact.result[idx][:type]),
-                compact.result[idx][:type],
-                compact.result[idx][:line], true)
-            compact.ssa_rename[compact.idx-1] = pi
+            Y = stmt.args[2]
+            if !isa(Y, GlobalRef)
```
Comment (Keno) [inline base/compiler/ssair/passes.jl:552]: Why doesn't `GlobalRef` work here? Can you explain that in a comment or in the commit message?

Comment (vtjnash) [reply base/compiler/ssair/passes.jl:552]: GlobalRef is not pure, so it is invalid to duplicate it

**Comment by vtjnash** [comment]
I'm not sure. This part of the code needs more documentation. The issue is we're inserting a use of an SSAValue, whose purpose (later) is to tell us is to let us track backwards (through PhiNodes) to discover if it was legal dynamically

File: base/compiler/ssair/passes.jl (hunk 1 above)
Comment (Keno) [reply base/compiler/ssair/passes.jl:552]: Wasn't the whole point of https://github.com/JuliaLang/julia/pull/36450 to change that? What non-purity remains?

**Comment by Keno** [comment]
What prevents us from just making `undefcheck` a legal codegen form? I thought it was that way originally.

File: base/compiler/ssair/passes.jl (hunk 1 above)
Comment (vtjnash) [reply base/compiler/ssair/passes.jl:552]: They can also still be non-constant

**Comment by vtjnash** [comment]
I don't think it ever existed (I tried to search back a little, but didn't see anything). `undefcheck` doesn't feel directly legal because it is an operation on the inferred type of the SSAValue. That's also why we see type_lift_pass is where final legalization happens, since it is taking that information out of the type domain, and inserting runtime values that track it where necessary (generally initialized by a Phi(c)Node, since otherwise we should have a certainty that it is defined, or not).

File: base/compiler/ssair/passes.jl (hunk 1 above)
Comment (Keno) [reply base/compiler/ssair/passes.jl:552]: If there is a data race you mean? In that case, what if instead of not doing the canonicalization, we did:
```
%a = GlobalRef(...)
typassert(%a, T)
PiNode(%a, T)
```

**Comment by Keno** [comment]
> `undefcheck` doesn't feel directly legal because it is an operation on the inferred type of the SSAValue.

I'm not sure I agree with that. It's a dynamic check on the definedness on that branch. I guess the issue is that we don't have the capacity to track this in codegen and if we did, it would just look like `type_lift_pass`, so we might as well call that pass required. I'm not sure I 100% like that since `type_lift_pass` was supposed to be an optimization, but I guess it's the most expedient path for now.

File: base/compiler/ssair/slot2ssa.jl [hunk 2]
```diff
@@ -147,6 +148,7 @@ function fixemup!(cond, rename, ir::IRCode, ci::CodeInfo, idx::Int, @nospecializ
                     return true
                 end
             end
+            # temporarily corrupt the isdefined node. type_lift_pass! will fix it
```
Comment (Keno) [inline base/compiler/ssair/slot2ssa.jl:151]: Should this be a separate Expr head then?

File: base/compiler/ssair/passes.jl (hunk 1 above)
Comment (vtjnash) [reply base/compiler/ssair/passes.jl:552]: That's fine too

File: base/compiler/ssair/slot2ssa.jl (hunk 2 above)
Comment (vtjnash) [reply base/compiler/ssair/slot2ssa.jl:151]: Probably would be more accurate? But possibly annoying to implement? Dunno. I was going for the minimal fix

**Comment by vtjnash** [comment]
I've dropped the objectionable commit and created https://github.com/JuliaLang/julia/pull/39893 for the better alternative of it. This should be ready to merge

**Review by Keno — APPROVED** [review]
Still would prefer to have the type lifting pass be purely an optimization, but let's fix the crash. We're doing worse things elsewhere in the compiler.

**Comment by vtjnash** [comment]
Agreed. I think the main challenge is that we need a concretization pass at some point to split maybe-undef variables, and it either looks a lot like this pass, but could be run separately / very early, or it just is this pass.
