### PR TITLE
Execute AM/PM Dates tests in the C locale.

### LINKED ISSUE #32515: Dates test is locale dependent
When running `make test-Dates` under the "en_GB.UTF-8" locale I get the following errors:
```

Error in testset Dates/io:
Test Failed at /home/othill/Sources/julia/julia/usr/share/julia/stdlib/v1.3/Dates/test/io.jl:580
  Expression: uppercase(t12) == Dates.format(t, "II:MMp") == Dates.format(d, "II:MMp") == Libc.strftime("%I:%M%p", tmstruct)
   Evaluated: "12:00AM" == "12:00AM" == "12:00AM" == "12:00am"
Error in testset Dates/io:
Test Failed at /home/othill/Sources/julia/julia/usr/share/julia/stdlib/v1.3/Dates/test/io.jl:580
  Expression: uppercase(t12) == Dates.format(t, "II:MMp") == Dates.format(d, "II:MMp") == Libc.strftime("%I:%M%p", tmstruct)
   Evaluated: "12:07AM" == "12:07AM" == "12:07AM" == "12:07am"
Error in testset Dates/io:
Test Failed at /home/othill/Sources/julia/julia/usr/share/julia/stdlib/v1.3/Dates/test/io.jl:580
  Expression: uppercase(t12) == Dates.format(t, "II:MMp") == Dates.format(d, "II:MMp") == Libc.strftime("%I:%M%p", tmstruct)
   Evaluated: "01:24AM" == "01:24AM" == "01:24AM" == "01:24am"
Error in testset Dates/io:
Test Failed at /home/othill/Sources/julia/julia/usr/share/julia/stdlib/v1.3/Dates/test/io.jl:580
  Expression: uppercase(t12) == Dates.format(t, "II:MMp") == Dates.format(d, "II:MMp") == Libc.strftime("%I:%M%p", tmstruct)
   Evaluated: "12:00PM" == "12:00PM" == "12:00PM" == "12:00pm"
Error in testset Dates/io:
Test Failed at /home/othill/Sources/julia/julia/usr/share/julia/stdlib/v1.3/Dates/test/io.jl:580
  Expression: uppercase(t12) == Dates.format(t, "II:MMp") == Dates.format(d, "II:MMp") == Libc.strftime("%I:%M%p", tmstruct)
   Evaluated: "12:15PM" == "12:15PM" == "12:15PM" == "12:15pm"
Error in testset Dates/io:
Test Failed at /home/othill/Sources/julia/julia/usr/share/julia/stdlib/v1.3/Dates/test/io.jl:580
  Expression: uppercase(t12) == Dates.format(t, "II:MMp") == Dates.format(d, "II:MMp") == Libc.strftime("%I:%M%p", tmstruct)
   Evaluated: "11:59PM" == "11:59PM" == "11:59PM" == "11:59pm"
```
When using `LC_TIME=en_US.UTF-8` in the shell before `make  test-Dates` then there are no errors.

The difference between the two locales is that in "en_GB" `am_pm="am;pm"` while in "en_US" `am_pm="AM;PM"`.

Some googling indicates that the C standard indicates the use of these values as is and that the `%p -> uppercase` and `%P -> lowercase` convention is only a de facto standard used by other languages mimicking the C interface.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaLang/julia/issues/32515

### CODE REVIEW

File: stdlib/Dates/test/io.jl [hunk 1]
```diff
@@ -534,6 +539,9 @@ end
     end
     # if am/pm is missing, defaults to 24-hour clock
     @eval Time("13:24", "II:MMp") == Time("13:24", "HH:MM")
+
+    # recover the locale
```
Comment (fredrikekre) [inline stdlib/Dates/test/io.jl]: Should this be done in a `finally` block?

**Comment by Keno** [comment]
Ah locale, one of those horrible ideas from the C standard.
