### PR TITLE
Pkg.free: correctly set target nullable object

### LINKED ISSUE #17481: Pkg.free error
````
julia> Pkg.free("Rmath")
INFO: Freeing Rmath
INFO: Removing Rmath v0.1.1
ERROR: MethodError: no method matching reset!(::Base.LibGit2.GitRepo, ::Nullable{Void}, ::String)
Closest candidates are:
  reset!{T<:AbstractString,S<:Base.LibGit2.GitObject}(::Base.LibGit2.GitRepo, ::Nullable{S<:Base.LibGit2.GitObject}, ::T<:AbstractString...)
  reset!(::Base.LibGit2.GitRepo, ::AbstractString, ::AbstractString...)
  reset!(::Base.LibGit2.GitRepo, ::Base.LibGit2.Oid, ::Int32)
  ...
 in reset!(::Base.LibGit2.GitRepo, ::String, ::String) at .\libgit2\libgit2.jl:316
 in restore(::Base.LibGit2.State, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:484
 in transact(::Base.Pkg.Entry.##22#25{Base.LibGit2.GitRepo,String}, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:500
 in (::Base.Pkg.Entry.##21#24{String})(::Base.LibGit2.GitRepo) at .\pkg\entry.jl:255
 in with(::Base.Pkg.Entry.##21#24{String}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:660
 in free(::String) at .\pkg\entry.jl:247
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#free,Tuple{String}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#free,Tuple{String}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in free(::String) at .\pkg\pkg.jl:183
 in eval(::Module, ::Any) at .\boot.jl:234
 in macro expansion at .\REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:46

julia> versioninfo()
Julia Version 0.5.0-dev+5478
Commit 43f3c05 (2016-07-18 02:34 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

julia>
````

### PR DESCRIPTION
**Pull request by wildart**
Fixed #17481 when target object was incorrectly set when commit was not found by `revparse`.

### CODE REVIEW

**Comment by Keno** [comment]
Add a test?

**Comment by wildart** [comment]
@tkelman Ready to merge

File: base/libgit2/libgit2.jl [hunk 1]
```diff
@@ -310,19 +310,19 @@ end
 
 """ git reset [<committish>] [--] <pathspecs>... """
 function reset!(repo::GitRepo, committish::AbstractString, pathspecs::AbstractString...)
-    target_obj = isempty(committish) ? Nullable{GitAnyObject}() :
-                                       Nullable(revparse(repo, committish))
+    obj = revparse(repo, !isempty(committish) ? committish : Consts.HEAD_FILE)
+    obj === nothing && return # do not remove entries in the index matching the provided pathspecs with empty target commit tree
```
Comment (tkelman) [inline base/libgit2/libgit2.jl]: so revparse isn't returning Nullable yet?

File: test/libgit2.jl [hunk 2]
```diff
@@ -468,6 +468,65 @@ mktempdir() do dir
...
+            # stage file
+            LibGit2.add!(repo, test_file)
+
+            # modified file staged
+            st_stg = LibGit2.status(repo, test_file)
+            @test LibGit2.isset(get(st_stg), LibGit2.Consts.STATUS_INDEX_MODIFIED)
+            @test !LibGit2.isset(get(st_stg), LibGit2.Consts.STATUS_WT_MODIFIED)
+
+            # try to unstage to unknown commit
+            LibGit2.reset!(repo, "XYZ", test_file)
```
Comment (tkelman) [inline test/libgit2.jl]: this isn't an error?

File: test/libgit2.jl [hunk 3]
```diff
@@ -468,6 +468,65 @@ mktempdir() do dir
...
+
+            # status should not change
+            st_new = LibGit2.status(repo, test_file)
+            @test get(st_new) == get(st_stg)
+
+            # try to unstage to HEAD
+            LibGit2.reset!(repo, LibGit2.Consts.HEAD_FILE, test_file)
```
Comment (tkelman) [inline test/libgit2.jl]: so this does nothing with no feedback?

**Comment by tkelman** [comment]
so what should have happened in the case from https://github.com/JuliaLang/julia/issues/17481?

File: base/libgit2/libgit2.jl (hunk 1 above)
Comment (wildart) [inline base/libgit2/libgit2.jl]: yet, great Nullability is coming.

File: test/libgit2.jl (hunk 2 above)
Comment (wildart) [inline test/libgit2.jl]: no, nothing should happen

**Comment by wildart** [comment]
do not no, error was very strange - `revparse` failed for `HEAD`

**Comment by tkelman** [comment]
and we're sure this would fix it?

File: test/libgit2.jl (hunk 2 above)
Comment (wildart) [inline test/libgit2.jl]: I'm thinking of throwing exception when `revparse` (inside `reset!`) fails to find anything. At lease it would give some info about nature of failure.

Comment (tkelman) [inline test/libgit2.jl]: wouldn't you get an error if you tried to reset to something nonexistent with cmdline git?

Comment (tkelman) [inline test/libgit2.jl]: yeah I think more exceptions/nulls and less silent doing-nothing would be a good direction. let's change the internals as a separate pr though, I think this one's good to merge

**Comment by wildart** [comment]
We have test for `Pkg.free` already, obviously something happened with repo that lead to `revparse` failure to find `HEAD`. At least this error is fixed.
