### PR TITLE
Recover from UndefVarErrors while deserializing CapturedExceptions

### LINKED ISSUE #20231: Handle deserialization errors in RemoteExceptions
If an exception type (or any data fields in the exception) thrown in a worker is not present on the destination node, deserialization of the exception results in a loss of the original error and the stacktrace (if the original exception is wrapped in a CapturedException). 

The root cause is shown below:

```
julia> remotecall_fetch(()->eval(quote
         type Foo <: Exception
           x
         end
         throw(Foo(1))
       end), 2)
ERROR: UndefVarError: Foo not defined
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:841
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:909
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:856
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:909
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:856
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
 in deserialize_msg(::Base.ClusterSerializer{TCPSocket}, ::Type{Base.ResultMsg}) at ./multi.jl:120
 in deserialize_msg(::Base.ClusterSerializer{TCPSocket}) at ./multi.jl:130
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:1371
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:1328
 in (::Base.##505#506{TCPSocket,TCPSocket,Bool})() at ./event.jl:73
Stacktrace:
 [1] #remotecall_fetch#493(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1093
 [2] remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1085
 [3] #remotecall_fetch#496(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1106
 [4] remotecall_fetch(::Function, ::Int64) at ./multi.jl:1106
```

While it is difficult to recover a valid object after a deserialization error, we could at least capture the type of the original error, say a `BoundsError` as part of the deserialization error stack. 

Since remotecalls always wrap the remote exception in a `RemoteException` we can capture a bit more information of the original error. We could
- add a short stringified description of the original error type and the first line from the original callstack as the first field to be deserialized in a specific `deserialize(s::AbstractSerializer, t::Type{T}) where T <: RemoteException` implementation.
- This implementation will catch any further deserialization errors and rethrow it with the short stringified desc of the original error added.

This way some information of the original error is retained even in the event of deserialization errors.

Ref : https://github.com/JuliaLang/julia/issues/20027#issuecomment-274791944

### PR DESCRIPTION
**Pull request by amitmurthy**
The first commit in this PR closes #20231 

The second commit prevents printing of callstacks not directly related to a root exception captured via container exception types.

### CODE REVIEW

File: base/multi.jl [hunk 1]
```diff
@@ -1015,7 +1015,63 @@ remote exception and a serializable form of the call stack when the exception wa
 RemoteException(captured) = RemoteException(myid(), captured)
 function showerror(io::IO, re::RemoteException)
     (re.pid != myid()) && print(io, "On worker ", re.pid, ":\n")
-    showerror(io, re.captured)
+    showerror(io, get_root_exception(re.captured))
+end
+
+# Specialized serialize-deserialize implementations for CapturedException to overcome
+# any deserialization errors in `CapturedException.ex`` which can hide the original
```
Comment (tkelman) [inline base/multi.jl]: was the doubled trailing backtick intended?

File: test/parallel_exec.jl [hunk 2]
```diff
@@ -1463,3 +1463,18 @@ syms = setup_syms(3, workers())
 clear!(syms, workers())
 test_clear(syms, workers())
 
+# Test partial recovery from a deserialization error in CapturedException
+try
+    expr =
+    quote
```
Comment (tkelman) [inline test/parallel_exec.jl]: this would more be more obviously the value of expr if it were indented, and maybe start with `expr = quote` on the same line

File: test/parallel_exec.jl [hunk 3]
```diff
@@ -1463,3 +1463,18 @@ syms = setup_syms(3, workers())
...
+        type DontExistOn1
+            x
+        end
+        throw(BoundsError(DontExistOn1(1), 1))
+    end
+    remotecall_fetch(()->eval(expr), id_other)
```
Comment (tkelman) [inline test/parallel_exec.jl]: add `error("unexpected")` after this so it doesn't silently pass if the remotecall somehow doesn't throw

**Comment by amitmurthy** [comment]
Merging this once CI passes.
