### PR TITLE
Normalize floating point environment on startup

### LINKED ISSUE #38419: Complex signed NaN test fails on Darwin/Aarch64
```
Test Failed at /Users/julia/julia23/test/complex.jl:1049
  Expression: isequal(one(T) / complex(T(Inf), T(-NaN)), complex(zero(T), zero(T)))
   Evaluated: isequal(0.0f0 - 0.0f0im, 0.0f0 + 0.0f0im)
Test Failed at /Users/julia/julia23/test/complex.jl:1054
  Expression: isequal(one(T) / complex(T(-Inf), T(-NaN)), complex(-(zero(T)), zero(T)))
   Evaluated: isequal(-0.0f0 - 0.0f0im, -0.0f0 + 0.0f0im)
Test Failed at /Users/julia/julia23/test/complex.jl:1067
  Expression: isequal(one(T) / complex(T(-NaN), T(Inf)), complex(-(zero(T)), -(zero(T))))
   Evaluated: isequal(0.0f0 - 0.0f0im, -0.0f0 - 0.0f0im)
Test Failed at /Users/julia/julia23/test/complex.jl:1071
  Expression: isequal(one(T) / complex(T(-NaN), T(-Inf)), complex(-(zero(T)), zero(T)))
   Evaluated: isequal(0.0f0 + 0.0f0im, -0.0f0 + 0.0f0im)
```
The reason for this seems to be that Apple turns on the `RunFast` flag, which normalizes away the sign bit of the NaN on certain operations. The question is to what extent we want to allow that or do we need to turn off `RunFast` or adjust the test or one of the implementations? Note that these tests do pass for Float64, only Float32 is at issue.

cc @stevengj

### PR DESCRIPTION
**Pull request by Keno**
In #38419 we noticed that on AArch64 Darwin, processes start with the
FZ and DN floating point flags set. To maintain consistency across platforms,
reset these flags whenever we start julia. Not that default_nans isn't available
on x86, so while we do have julia-level wrappers for the fz flag, I'm not
adding any for the dn flag. The function is exported, so if somebody really
needs it in some aarch64-specific code, they can ccall it.

cc @oscardssmith 
Fixes #38419

### CODE REVIEW

**Review by yuyichao — APPROVED** [review]
LGTM.

FWIW, I believe I tested subnormals on the ARM cores and they weren't really slower. Of course it was with cortex-a57 and things might have changed.

File: src/processor_fallback.cpp [hunk 1]
```diff
@@ -160,3 +160,13 @@ extern "C" JL_DLLEXPORT int32_t jl_set_zero_subnormals(int8_t isZero)
 {
     return isZero;
 }
+
+extern "C" JL_DLLEXPORT int32_t jl_get_default_nans(void)
+{
+    return 0;
+}
+
+extern "C" JL_DLLEXPORT int32_t jl_set_zero_subnormals(int8_t isDefault)
```
Comment (KlausC) [inline src/processor_fallback.cpp:169]: shouldn't that be ` jl_set_default_nans` ?

Comment (Keno) [reply src/processor_fallback.cpp:169]: Thanks
