### PR TITLE
Fix: History search with multi-byte characters

### LINKED ISSUE #61653: REPL history hang with >1-byte characters
With this entry in history:
```
julia> Αα
```

if I ctrl-R and paste `α` (backslash-alpha doesn't work as I would expect in the history searcher), history hangs until I hit ctrl-C.  Output provided here, but it's a bit of an interleaved mess:
```
┌ Error: Error in the keymap
│   exception =                                                                                                                                          6s 
│    TaskFailedException
│    Stacktrace:
│      [1] #wait#581
│        @ ./task.jl:363 [inlined]
│      [2] wait
│        @ ./task.jl:360 [inlined]
│      [3] fetch
│        @ ./task.jl:554 [inlined]
│      [4] runsearch(histfile::REPL.History.HistoryFile, term::Base.Terminals.TTYTerminal, prefix::String, terminal_properties::REPL.LineEdit.TerminalProperties)
│        @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:19
│      [5] histsearch(::REPL.History.HistoryFile, ::Vararg{Any})
│        @ REPL ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/REPL.jl:105
│      [6] history_search(mistate::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2766
│      [7] (::REPL.LineEdit.var"#250#251")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2728
│      [8] (::REPL.LineEdit.var"#match_input##0#match_input##1"{REPL.LineEdit.var"#250#251", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:1899
│      [9] macro expansion
│        @ ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:3054 [inlined]
│     [10] macro expansion
│        @ ./lock.jl:376 [inlined]
│     [11] (::REPL.LineEdit.var"#prompt!##2#prompt!##3"{Base.Terminals.TTYTerminal, REPL.LineEdit.ModalInterface, REPL.LineEdit.MIState, REPL.LineEdit.Prompt})()
│        @ REPL.LineEdit ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:3043
│    
│        nested task error: StringIndexError: invalid index [2], valid nearby indices [1]=>'Α', [3]=>'α'
│        Stacktrace:
│          [1] string_index_err(s::AbstractString, i::Int64)
│            @ Base ./strings/string.jl:12
│          [2] getindex_continued(s::String, i::Int64, u::UInt32)
│            @ Base ./strings/string.jl:499
│          [3] getindex
│            @ ./strings/string.jl:490 [inlined]───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│          [4] matchregions(spec::REPL.History.FilterSpec, candidate::String)                                                                              │
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/resumablefiltering.jl:345                                              │
│          [5] focus_matches(search::REPL.History.FilterSpec, content::Base.AnnotatedString{String}, targetwidth::Int64)                                   │
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/display.jl:535                                                         │
│          [6] print_candidate(io::IOContext{IOBuffer}, search::REPL.History.FilterSpec, cand::REPL.History.HistEntry, width::Int64; selected::Bool, hover::Bool)                                                                                                                                                      │
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/display.jl:489                                                         │
│          [7] print_candidate                                                                                                                             │
│            @ ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/display.jl:465 [inlined]                                                            │
│          [8] update_candidates(io::IOContext{IOBuffer}, oldcands::REPL.History.CandsState{SubArray{REPL.History.HistEntry, 1, Vector{REPL.History.HistEntry}, Tuple{UnitRange{Int64}}, true}}, newcands::REPL.History.CandsState{SubArray{REPL.History.HistEntry, 1, Vector{REPL.History.HistEntry}, Tuple{UnitRange{Int64}}, true}}, force::Bool)                                                                                                                               │
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/display.jl:410                                                         │
│          [9] redisplay_candidates(io::IOContext{IOBuffer}, oldstate::REPL.History.SelectorState, oldrows::Int64, newstate::REPL.History.SelectorState, newrows::Int64)                                                                                                                                               │
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/display.jl:379─────────────────────────────────────────╴Ctrl+S to save╶╯
│         [10] redisplay_all(io::Base.TTY, oldstate::REPL.History.SelectorState, newstate::REPL.History.SelectorState, pstate::REPL.LineEdit.PromptState; buf::IOContext{IOBuffer})
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/display.jl:71
│         [11] run_display!(::@NamedTuple{term::Base.Terminals.TTYTerminal, prompt::REPL.LineEdit.Prompt, istate::REPL.LineEdit.MIState, pstate::REPL.LineEdit.PromptState}, events::Channel{Symbol}, hist::Vector{REPL.History.HistEntry}, terminal_properties::REPL.LineEdit.TerminalProperties)
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:178
│         [12] (::REPL.History.var"#runsearch##2#runsearch##3"{REPL.History.HistoryFile, REPL.LineEdit.TerminalProperties, @NamedTuple{term::Base.Terminals.TTYTerminal, prompt::REPL.LineEdit.Prompt, istate::REPL.LineEdit.MIState, pstate::REPL.LineEdit.PromptState}, Channel{Symbol}})()
│            @ REPL.History ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:17
└ @ REPL.LineEdit ~/a/julia/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:3056
```

### PR DESCRIPTION
**Pull request by jakobnissen**
REPL.History.matchregions used naive string indexing, which assumed the last character of match regions were ASCII. This led to StringIndexError when searching for e.g. "α".

Tests were created with Claude Opus 4.7

Closes #61653

### CODE REVIEW

File: stdlib/REPL/test/history.jl [hunk 1]
```diff
@@ -400,6 +400,22 @@ end
...
+            @test matchregions(spec_ab, "αβ") == [1:3]
+            # Two exact matches separated by a single space should merge, even when
+            # the boundary characters are multibyte
+            spec_two = FilterSpec(ConditionSet("=αβ;=γδ"))
+            @test matchregions(spec_two, "αβ γδ") == [1:8]
+            # Adjacent multibyte matches (no space) must not merge
+            @test matchregions(spec_two, "αβγδ") == [1:3, 5:7]
+            # Multi-character gap must not merge
+            @test matchregions(spec_two, "αβ  γδ") == [1:3, 7:9]
+            # ASCII sanity: single-space-separated matches still merge
```
Comment (adienes) [inline stdlib/REPL/test/history.jl:415]:
```suggestion
```

I would have to imagine this last one is covered by existing tests

Comment (jakobnissen) [reply stdlib/REPL/test/history.jl:415]: Yeah, they are. Does it matter though? Enough to re-run CI?

Comment (adienes) [reply stdlib/REPL/test/history.jl:415]: perhaps not
