### PR TITLE
Optimize away try/catch blocks that are known not to trigger

### LINKED ISSUE #34270: Optimize away overhead from setting up try catch if exception is impossible
There are a bunch of senarios, in which is should be possible to know at compile time if an exception will be thrown. (especially if we exclude unrecoverable externally triggged exceptions like out of memory).
 
E.g. if the code is inlined to only builtin's / LLVM intrinsics,
and there is no exception present in the code.
(maybe there could be for different iinput types, but we specialized on that so those go away).

Right now, even in the most obvious case, the compiler can't tell.
So it includes all this overhead to be ready to catch exception.

### Example:
```
julia> function danger()
           1.0
       end
danger (generic function with 1 method)

julia> function safe()
           try
               1.0
           catch
               rethrow()
           end
       end
safe (generic function with 1 method)

julia> @btime safe()
  17.163 ns (0 allocations: 0 bytes)
1.0

julia> @btime danger()
  0.031 ns (0 allocations: 0 bytes)
1.0
```

Realistic case:
https://github.com/JuliaDiff/ChainRulesCore.jl/issues/82

### PR DESCRIPTION
**Pull request by Keno**
This leverages the support from #51590 to delete any try catch block that is known not to be triggered (either because the try-body is empty to because we have proven `:nothrow` for all contained statements).

Fix #34270.

### CODE REVIEW

**Comment by Keno** [comment]
@nanosoldier `runtests()`.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/51674#issuecomment-1758890389) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/51135f4_vs_64a127d/report.html) is available.

**Comment by Keno** [comment]
@nanosoldier `runtests(["AlignedSpans", "AtmosphericModels", "WinchModels", "OptimizationMetaheuristics", "TMLE", "LongwaveModePropagator", "KitePodModels", "MixedModelsPermutations", "HetaSimulator", "ModeCouplingTheory", "SpatialEcology", "TrajectoryGamesBase", "DTables", "ChemicalIdentifiers", "StatsKit", "NCEI", "ManifoldDiff", "AstrodynamicalModels", "TimeseriesTools", "MiseEnPage", "SGtSNEpi", "GIFImages", "HiGHS", "FinEtoolsVoxelMesher", "Grumps", "GasChromatographySimulator", "HierarchicalTemporalMemory", "KiteUtils", "LinRegOutliers", "CausalityTools", "MINDFulMakie", "EpithelialDynamics1D", "UnfoldSim", "GeoInterfaceMakie", "MRINavigator", "JumpProblemLibrary", "EarlyStopping", "OndaEDFSchemas", "MinimallyDisruptiveCurves", "PALEOaqchem", "MetidaBioeq", "RangeTrees", "Agents", "PlutoStaticHTML", "Petri", "MixedModelsDatasets", "Tapestree", "RxEnvironments", "MixedModelsSim", "OndaEDF", "InteractiveDynamics", "SymbolicNumericIntegration", "HiQGA", "ManifoldsBase", "BayesianQuadrature", "PALEOocean", "Dynesty", "BDisposal", "Legolas", "AnovaMixedModels", "GeometricIntegrators", "MixedModelsSerialization", "DPFEHM", "IterativeLearningControl", "HierarchicalEOM", "RigorousInvariantMeasures", "BM3DDenoise"])`

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -2981,6 +2981,20 @@ function update_bestguess!(interp::AbstractInterpreter, frame::InferenceState,
     end
 end
 
+function propagate_to_error_handler!(frame::InferenceState, currpc::Int, W, 𝕃ᵢ, currstate)
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:2984]:
```suggestion
function propagate_to_error_handler!(frame::InferenceState, currpc::Int, W::BitSet, 𝕃ᵢ::AbstractLattice, currstate::VarTable)
```

File: base/compiler/abstractinterpretation.jl [hunk 2]
```diff
@@ -3121,26 +3133,15 @@ function typeinf_local(interp::AbstractInterpreter, frame::InferenceState)
...
                 stoverwrite1!(currstate, changes)
-                let cur_hand = frame.handler_at[currpc], l, enter
-                    while cur_hand != 0
-                        enter = frame.src.code[cur_hand]::Expr
-                        l = enter.args[1]::Int
-                        exceptbb = block_for_inst(frame.cfg, l)
-                        # propagate new type info to exception handler
-                        # the handling for Expr(:enter) propagates all changes from before the try/catch
-                        # so this only needs to propagate any changes
-                        if stupdate1!(𝕃ᵢ, states[exceptbb]::VarTable, changes)
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:3138]: This was the only place where we used `stupdate1!`, so we can remove it now if I remember correctly

**Review by aviatesk — APPROVED** [review]
LGTM.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/51674#issuecomment-1762415012) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3e0fe63_vs_64a127d/report.html) is available.

**Review by aviatesk — APPROVED** [review]
