### PR TITLE
ArgumentError("stream is closed or unusable") -> IOError

### LINKED ISSUE #29260: ArgumentError("stream is closed or unusable") in check_open should be IOError
`ArgumentError("stream is closed or unusable")` is thrown from various `IO` write and connect methods.
It would probably be better to throw the new `IOError` in this case. Currently error handling code has to parse the "stream is closed or unusable" message to know that this is a recoverable IO error and not a precondition violation.

"stream must be open" is not really a valid function precondition because even if the caller checks that the stream is open before calling the function it may be closed by the other end by the time the function tries to use it.

Changing to `IOError` would simplify handling of retry-able IO errors in places like this:
```julia
Is `exception` caused by a possibly recoverable IO error.
"""
isioerror(e) = false
isioerror(::Base.EOFError) = true
isioerror(::Base.IOError) = true
isioerror(e::ArgumentError) = e.msg == "stream is closed or unusable"
```
https://github.com/JuliaWeb/HTTP.jl/blob/1de41febaaa0912183878c068633210b6e30a05d/src/IOExtras.jl#L35-L40

### PR DESCRIPTION
**Pull request by samoconnor**
Fix #29260

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Technically breaking, but very unlikely to actually break any code. We should run PkgEval to make sure it doesn't actually break anything in the wild.

**Comment by KristofferC** [comment]
Test already exist.

File: base/stream.jl [hunk 1]
```diff
@@ -253,7 +253,7 @@ end
 
 function check_open(x::Union{LibuvStream, LibuvServer})
     if !isopen(x) || x.status == StatusClosing
-        throw(ArgumentError("stream is closed or unusable"))
+        throw(IOError("stream is closed or unusable", 0))
```
Comment (JeffBezanson) [inline base/stream.jl]: It's a bit strange that the error code is 0, since that usually means "no error". Maybe we should pick something from the libuv error codes.

Comment (samoconnor) [reply base/stream.jl]: Could use [`UV_ENOTCONN`](https://github.com/libuv/libuv/blob/81c77427afb39b6fa6c0ecffdc1c1e2b3dde7aea/include/uv.h#L120) or [`UV_EBADF`](https://github.com/libuv/libuv/blob/40498795ab457dfa3a00a5aad45ba9db3bf71588/src/unix/stream.c#L803-L805), but error handling code that checks for particular codes may rely on some particular semantic per the libuv docs. I chose `0` to mean "there is no uv error code for this `IOError`".

[`UV_UNKNOWN`](https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/include/uv.h#L138) would be another option.

My preference would be to remove the `code` field from `IOError` and then add subtypes (`AddirInUseError <: IOError`, `ConnResetError <: IOError`, etc) as needed for particular cases where error handling code needs to know the cause. e.g. #15879. (We could still [use the code to build the error string](https://github.com/JuliaLang/julia/blob/e4d933d6b1a9c47fbffc4651488154b517649f65/base/libuv.jl#L78), but not store it in the `IOError` struct.)

It doesn't seem quite right to expose the internal codes of the IO library we happen to be using today.

**Comment by vtjnash** [comment]
Merge now? That would get this included in the 1.1 pkgeval run, and let us know if we can keep it.

**Comment by JeffBezanson** [comment]
Sure, why not.
