### PR TITLE
fix #30303, escaping $ when showing Symbols

### LINKED ISSUE #30303: Unescaped $ when using `show` on `Symbol`
The output here is trying to display the Julia code for creating the Symbol below but it fails to show that `$` is escaped:
```julia
julia> Symbol("USD\$")
Symbol("USD$")

julia> Symbol("USD$")
ERROR: syntax: invalid interpolation syntax: "$""
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: base/show.jl [hunk 1]
```diff
@@ -1031,7 +1031,7 @@ function show_unquoted_quote_expr(io::IO, @nospecialize(value), indent::Int, pre
             print(io, ":")
             print(io, value)
         else
-            print(io, "Symbol(\"", escape_string(s), "\")")
+            print(io, "Symbol(\"", escape_string(s, "\"\$"), "\")")
```
Comment (vtjnash) [inline base/show.jl]: replace `print(io, "Symbol(\"", escape_string(s, "\"\$"), "\")")` with `print(io, "Symbol(", repr(s), ")")`?

Comment (JeffBezanson) [reply base/show.jl]: ok

Comment (vtjnash) [reply base/show.jl]: might even be good to go through and do a total cleanup pass of the code, since there aren't many left

**Review by ararslan — APPROVED** [review]

**Review by omus — APPROVED** [review]
