### PR TITLE
Define copy!, setindex!, and arithmetic for Symmetric and Hermitian

### LINKED ISSUE #383: Cannot add UniformScaling to symmetric sparse matrix
I can't seem to add a symmetric sparse matrix to a UniformScaling.
This code:
```julia
#Create a sparse symmetric matrix
A = Symmetric( sparse([1 -1; -1 1]) )
#Add an identity doesn't work
# "indexed assignment not defined for Symmetric{Int64, SparseMatrixCSC{Int64,Int64}}"
AI = A + I
```
produces the following
`"indexed assignment not defined for Symmetric{Int64, SparseMatrixCSC{Int64,Int64}}"`

`versioninfo()`
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

### LINKED ISSUE #19225: Cannot add UniformScaling to symmetric sparse matrix
I can't seem to add a symmetric sparse matrix to a UniformScaling.
This code:
```julia
#Create a sparse symmetric matrix
A = Symmetric( sparse([1 -1; -1 1]) )
#Add an identity doesn't work
# "indexed assignment not defined for Symmetric{Int64, SparseMatrixCSC{Int64,Int64}}"
AI = A + I
```
produces the following
`"indexed assignment not defined for Symmetric{Int64, SparseMatrixCSC{Int64,Int64}}"`

`versioninfo()`
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

### PR DESCRIPTION
**Pull request by ararslan**
Fixes JuliaLang/LinearAlgebra.jl#383

This implements `copy!` for `Symmetric` and `Hermitian` types, as well as `+` and `-` for `Symmetric` and `Hermitian` with `UniformScaling`.

### CODE REVIEW

File: base/linalg/symmetric.jl [hunk 1]
```diff
@@ -133,6 +133,8 @@ convert{T}(::Type{AbstractMatrix{T}}, A::Hermitian) = Hermitian(convert(Abstract
 
 copy{T,S}(A::Symmetric{T,S}) = (B = copy(A.data); Symmetric{T,typeof(B)}(B,A.uplo))
 copy{T,S}(A::Hermitian{T,S}) = (B = copy(A.data); Hermitian{T,typeof(B)}(B,A.uplo))
+copy!(dest::Symmetric, src::Symmetric) = copy!(dest.data, src.data)
+copy!(dest::Hermitian, src::Hermitian) = copy!(dest.data, src.data)
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: this is not correct if uplo differs

File: base/linalg/uniformscaling.jl [hunk 2]
```diff
@@ -56,6 +56,10 @@ ishermitian(J::UniformScaling) = isreal(J.λ)
 (-)(B::BitArray{2}, J::UniformScaling)      = Array(B) - J
 (-)(J::UniformScaling, B::BitArray{2})      = J - Array(B)
 
+for t in (:Symmetric, :Hermitian), op in (:+, :-)
+    @eval ($op)(X::$t, J::UniformScaling) = ($t)(($op)(X.data, J), Symbol(X.uplo))
```
Comment (tkelman) [inline base/linalg/uniformscaling.jl]: should test that Hermitian plus a complex UniformScaling with nonzero imag component currently should error

File: base/linalg/symmetric.jl (hunk 1 above)
Comment (ararslan) [inline base/linalg/symmetric.jl]: Good catch! Will fix, thanks!

File: base/linalg/uniformscaling.jl (hunk 2 above)
Comment (ararslan) [inline base/linalg/uniformscaling.jl]: Done. Thanks!

File: base/linalg/symmetric.jl (hunk 1 above)
Comment (tkelman) [inline base/linalg/symmetric.jl]: should write a test too that would have caught that

**Comment by ararslan** [comment]
While I'm at it, would it make sense to implement other operators on `Symmetric`/`Hermitian` with `UniformScaling`, e.g. `*` and `/`? If so, which operators?

**Comment by stevengj** [comment]
`*` and `/` are not nearly so useful, because you can just multiply or divide by a scalar instead.

**Comment by ararslan** [comment]
It appears that operations on `Symmetric` and `Hermitian` with scalars similarly fails. I could define those as well...

**Comment by ararslan** [comment]
In fact, if the `Symmetric` constructor actually verified symmetry, we could just define
```julia
op(x::Symmetric, y) = Symmetric(op(x.data, y), Symbol(x.uplo))
```
That allow for any kind of operation and would ensure symmetry of the result.

**Comment by stevengj** [comment]
That sounds useful.

**Comment by ararslan** [comment]
Okay, can do.

**Review by andreasnoack — CHANGES_REQUESTED** [review]

**Comment by tkelman** [comment]
Symmetric is a view wrapper type though, the inactive triangle should never be read from so its contents don't need to be symmetric

File: base/linalg/uniformscaling.jl (hunk 2 above)
Comment (ararslan) [inline base/linalg/uniformscaling.jl]: Yep, that seems to have done the trick. I was able to remove all of the special methods for `Symmetric` and `Hermitian` with `UniformScaling`. Thanks!

**Comment by ararslan** [comment]
I'm getting a weird result in another case that I'd appreciate some insight on:
```julia
julia> Y = Symmetric(sparse([1 -1; -1 1]))
2×2 Symmetric{Int64,SparseMatrixCSC{Int64,Int64}}:
  1  -1
 -1   1

julia> Y * I
2×2 Symmetric{Int64,SparseMatrixCSC{Int64,Int64}}:
          1  4635441232
 4635441232           1
```
This seems to happen with any `*` on a `Symmetric` or `Hermitian`. For whatever reason, `+` and `-` do indeed work as expected.

File: base/linalg/symmetric.jl [hunk 3]
```diff
@@ -107,6 +107,24 @@ end
     r
 end
 
+function setindex!(A::Symmetric, v, i::Integer, j::Integer)
+    if (A.uplo == 'U' && i >= j) || (A.uplo == 'L' && i <= j)
```
Comment (ararslan) [inline base/linalg/symmetric.jl]: That makes sense. Then I'm back to defining specific methods for things, since only being able to set the diagonal doesn't allow more general operations, but maybe that's fine.

**Comment by ararslan** [comment]
Okay, I've improved my initial implementation of `copy!`, restricted `setindex!` to the diagonals only, defined `+`, `-`, `*`, and `/` for `Symmetric` and `Hermitian` with scalars, and added more tests. The tests pass locally, so hopefully CI likes it too.

Thanks so much for your help, everyone!

File: base/linalg/symmetric.jl [hunk 4]
```diff
@@ -218,6 +248,10 @@ A_mul_B!{T<:BlasComplex,S<:StridedMatrix}(C::StridedMatrix{T}, A::StridedMatrix{
 *(A::HermOrSym, B::HermOrSym) = full(A)*full(B)
 *(A::StridedMatrix, B::HermOrSym) = A*full(B)
 
+for T in (:Symmetric, :Hermitian), op in (:+, :-, :*, :/)
+    @eval ($op)(A::$T, x::Number) = ($T)(($op)(A.data, x), Symbol(A.uplo))
```
Comment (andreasnoack) [inline base/linalg/symmetric.jl]: The `Hermitian` operations should probably be restricted to operations with `x::Real`.

Comment (ararslan) [inline base/linalg/symmetric.jl]: I had thought about that, but there are cases where operating with a complex value could still produce a real diagonal. But restricting to `Real` does seem the safer option.

File: base/linalg/symmetric.jl [hunk 5]
```diff
@@ -107,6 +107,17 @@ end
...
 end
 
+function setindex!(A::Symmetric, v, i::Integer, j::Integer)
+    i == j || throw(ArgumentError("Cannot set a non-diagonal index in a symmetric matrix"))
+    setindex!(A.data, v, i, j)
+end
+
+function setindex!(A::Hermitian, v, i::Integer, j::Integer)
+    i == j || throw(ArgumentError("Cannot set a non-diagonal index in a Hermitian matrix"))
+    isreal(v) || throw(ArgumentError("Cannot set a nonreal value to the diagonal in a Hermitian matrix"))
```
Comment (ararslan) [inline base/linalg/symmetric.jl]: Good call. Fixed. Thanks!

**Comment by ararslan** [comment]
The CI failure appears to be unrelated. (One of the tests in the ambiguity test set is returning a non-boolean value.)

**Comment by tkelman** [comment]
That's a messy hack so when that test fails it tells you what the ambiguities were. But it's related.

**Comment by ararslan** [comment]
Ohhhh okay, so the `Tuple{Method,Method}` thing in the log is the list of ambiguities. I guess it's angry about my `+` and `-` definitions begin ambiguous with `AbstractArray{Bool,N<:Any}`. Hmm.

**Comment by ararslan** [comment]
Any idea what I could do to ameliorate that? As long as `Bool <: Number` the solution is not clear to me.

**Comment by tkelman** [comment]
Probably have to define some ambiguity-resolving methods for the Bool case where the existing method and yours intersect?

**Comment by ararslan** [comment]
That seems to have done the trick. Thanks so much, @tkelman!

**Comment by ararslan** [comment]
Looking better now, @andreasnoack?

File: test/linalg/symmetric.jl [hunk 6]
```diff
@@ -250,3 +250,36 @@ let a = randn(2,2)
     cc = copy(c)
     @test conj!(c) == conj(Array(c))
 end
+
+# 19225
+let X = sparse([1 -1; -1 1])
```
Comment (andreasnoack) [inline test/linalg/symmetric.jl]: I think these should to into the sparse tests for modularity. However, you might want to test the functionality with dense arrays as well.

**Review by andreasnoack — CHANGES_REQUESTED** [review]
See the comment at line 255

File: test/linalg/symmetric.jl (hunk 6 above)
Comment (ararslan) [inline test/linalg/symmetric.jl]: I removed the `sparse` wrapper for these tests, then copied a simplified version of what's currently here to the sparse tests. Let me know if the format looks okay.

**Comment by ararslan** [comment]
All good now?

**Comment by ararslan** [comment]
Bump. @andreasnoack

**Review by andreasnoack — APPROVED** [review]

File: base/linalg/symmetric.jl [hunk 7]
```diff
@@ -107,6 +107,21 @@ end
     r
 end
 
+function setindex!(A::Symmetric, v, i::Integer, j::Integer)
+    i == j || throw(ArgumentError("Cannot set a non-diagonal index in a symmetric matrix"))
```
Comment (KristofferC) [inline base/linalg/symmetric.jl]: This change doesn't make sense to me. Why shouldn't you be able to set an off diagonal element?

Comment (andreasnoack) [inline base/linalg/symmetric.jl]: Then it wouldn't be symmetric anymore.

Comment (KristofferC) [inline base/linalg/symmetric.jl]: ?. This is a symmetric wrapper so it is implicitly symmetric no matter what you do with it. Setting `A[i,j] = v` is the same as `A[i,j] = A[j,i] = v`.

Comment (ararslan) [inline base/linalg/symmetric.jl]: The problem then is that the behavior of `setindex!` differs from everywhere else in that it sets multiple values at once.

Comment (andreasnoack) [inline base/linalg/symmetric.jl]: Yeah. We discussed that and it was considered too surprising. Are you considering a generic case where modifying the underlying buffer would be inconvenient?

Comment (KristofferC) [inline base/linalg/symmetric.jl]: It cripples the use of the wrapper though (enough that it can basically only be used for dispatch). There need to be some way to assemble into the wrapped matrix.. I'm fine with disallowing setting elements on the "wrong" side of the diagonal but imo setting on the correct side should be allowed.

Comment (KristofferC) [inline base/linalg/symmetric.jl]: Of course I can just use `.data` but modifying the underlying buffer is breaking the abstraction.

Comment (ararslan) [inline base/linalg/symmetric.jl]: I'm not sure what you mean by the right and wrong sides of a diagonal. Doesn't that only apply to triangular matrices?

Comment (KristofferC) [inline base/linalg/symmetric.jl]: I mean the `.uplo` field.

Comment (ararslan) [inline base/linalg/symmetric.jl]: `Diagonal` doesn't have `.uplo`, it only has `.diag`

Comment (ararslan) [inline base/linalg/symmetric.jl]: Sorry, I got confused about what we were talking about, disregard that last comment

Comment (ararslan) [inline base/linalg/symmetric.jl]: Only being able to assign to the upper or lower triangle depending on the value of `uplo` also breaks the abstraction; the user shouldn't have to care about which triangle is stored since all they want to know about it is that it's symmetric.

Comment (tkelman) [inline base/linalg/symmetric.jl]: we could introduce a symset! function, or something similar, that generically changes values in a way that maintains symmetry.

**Comment by fredrikekre** [comment]
Just leaving a note here that this broke the following:
```julia
julia> A = rand(2, 2); S = Symmetric(A); D = Diagonal(rand(2));

julia> S*D
ERROR: ArgumentError: Cannot set a non-diagonal index in a symmetric matrix
Stacktrace:
 [1] setindex!(::Symmetric{Float64,Array{Float64,2}}, ::Float64, ::Int64, ::Int64) at ./linalg/symmetric.jl:126
 [2] scale!(::Symmetric{Float64,Array{Float64,2}}, ::Symmetric{Float64,Array{Float64,2}}, ::Array{Float64,1}) at ./linalg/matmul.jl:19
 [3] *(::Symmetric{Float64,Array{Float64,2}}, ::Diagonal{Float64}) at ./linalg/diagonal.jl:152

julia> D*S
ERROR: ArgumentError: Cannot set a non-diagonal index in a symmetric matrix
Stacktrace:
 [1] setindex!(::Symmetric{Float64,Array{Float64,2}}, ::Float64, ::Int64, ::Int64) at ./linalg/symmetric.jl:126
 [2] scale!(::Symmetric{Float64,Array{Float64,2}}, ::Array{Float64,1}, ::Symmetric{Float64,Array{Float64,2}}) at ./linalg/matmul.jl:34
 [3] *(::Diagonal{Float64}, ::Symmetric{Float64,Array{Float64,2}}) at ./linalg/diagonal.jl:154
```

which I stumbled upon trying to add tests for #22396

File: base/linalg/symmetric.jl (hunk 7 above)
Comment (martinholters) [inline base/linalg/symmetric.jl]: The usefulness of a `symset!` not withstanding, we could also think about permitting `setindex!` operations that maintain symmetry. E.g. `A[:,:] = 0` might be expected to work. Also `A[[CartesianIndex(1,2), CartesianIndex(2,1)]] = 1`, although `symset!` would of course be nicer for this case.
