### PR TITLE
Fix arrayref nothrow predicate for undef-able arrays

### LINKED ISSUE #28326: UndefRefError when showing Array{Any}(undef, 2, 2, 2)
```julia
julia> show(Array{Any}(undef, 2, 2, 2))
Any[ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:732 [inlined]
 [2] _show_nonempty(::IOContext{Base.TTY}, ::SubArray{Any,2,Array{Any,3},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Int64},false}, ::String) at ./arrayshow.jl:386
 [3] (::getfield(Base, Symbol("##376#377")){String})(::IOContext{Base.TTY}, ::SubArray{Any,2,Array{Any,3},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Int64},false}) at ./arrayshow.jl:404
 [4] show_nd(::IOContext{Base.TTY}, ::Array{Any,3}, ::getfield(Base, Symbol("##376#377")){String}, ::Bool) at ./arrayshow.jl:294
 [5] _show_nonempty at ./arrayshow.jl:403 [inlined]
 [6] show(::Base.TTY, ::Array{Any,3}) at ./arrayshow.jl:421
 [7] show(::Array{Any,3}) at ./show.jl:314
 [8] top-level scope at none:0
```

This is weird, as this array is tested in "test/show.jl", but this has not been spotted by CI. The test fails locally though, for me.

### PR DESCRIPTION
**Pull request by Keno**
Previously the nothrow predicate said we were allowed to remove an unused
call if it was marked as inbounds. However, this is only true if none of
the entries of the array can be `#undef` (i.e. if the element type is a
bitstype of bitsunion). Correct the predicate and add a test case.

Fixes #28326

### CODE REVIEW

File: base/compiler/tfuncs.jl [hunk 1]
```diff
@@ -995,13 +995,29 @@ function tuple_tfunc(@nospecialize(argtype))
     return argtype
 end
 
+function array_type_undefable(a)
```
Comment (Keno) [inline base/compiler/tfuncs.jl]: `@nospecialize`
