### PR TITLE
inference: ~~refine~~ replace recursion non-detection algorithm

### LINKED ISSUE #23371: intermittent type inference of `Any` in CI
Seen this a couple of times on the circle-ci and the bsd worker, opening an issue to track it. Stacktrace:
```
Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: return type RowVector{Float64,Array{Float64,1}} does not match inferred return type Any
  Stacktrace:
   [1] include_relative(::Module, ::String) at ./loading.jl:464
   [2] eval(::Module, ::Any) at ./boot.jl:291
   [3] ==(::Array{Any,1}, ::Array{String,1}) at ./abstractarray.jl:0
   [4] warn at ./util.jl:583 [inlined]
   [5] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:156
   [6] vect at ./array.jl:96 [inlined]
   [7] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:151
   [8] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:154
   [9] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:52
  while loading /usr/home/julia/worker/11rel-amd64/build/test/statistics.jl, in expression starting on line 177
```

Some logs: https://gist.github.com/fredrikekre/9c80c0504e12aa7acb0fd4443b3f3fec

### PR DESCRIPTION
**Pull request by vtjnash**
~~Refinement~~ Replacement of #21933 recursion detection and handling.

The general idea here of the first commit is that it is sufficient to prevent recursion complexity growth over entire *edges*. Previously, we only considered the callee vertex when detecting recursive method calls. However, it should also be valid to consider both vertexes. But considering the callee also, we can significantly increase the range of cases that we can allow inference to consider, without triggering the recursion detection limiter. This should be generally sufficient to ensure we can infer "bottleneck"-type functions, without significantly sacrificing our convergence requirements.

For an example of when this new heuristic comes into effect, consider `print`: a significant number of these methods are reached from calling vararg `print` and themselves call vararg `print`.
```julia
print(arg...) = foreach(print, arg)
print(arg) = print("hi", 1, 2, 3)
```
Naively, those recursive vararg `print` calls have no obvious complexity bound on their own, and thus can't be inferred. However, when we add in the consideration of this PR that each one has a different caller method, that doesn’t need to be detected as recursion.

Thus, ~~this may incidentally~~ should fix #23371 ~~(though my actually reason for this is for some other WIP I have locally).~~

Update:
The remaining commits in the PR make it harder to trigger the unbounded recursion detection, but increase the effective penalty for doing so. Now inference runs in one of two modes: limited or unlimited. This allows us to cache the limited and unlimited inference results separately.

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -5463,6 +5464,7 @@ t4 = vcat(A23567, t2, t3)
 @test t4[11:15] == A23567
 
 for U in unboxedunions
+    Base.unionlen(U) > 5 && continue # larger values cause subtyping to crash
```
Comment (martinholters) [inline test/core.jl]: Related? If so, how? Does the better inference perform more/other subtype checks that now trigger the crash?

File: base/inference.jl [hunk 2]
```diff
@@ -1770,15 +1770,7 @@ function abstract_call_method(method::Method, @nospecialize(f), @nospecialize(si
...
     tm = _topmod(sv)
-    if (# promote_typeof signature may be used with many arguments
-          !istopfunction(tm, f, :promote_typeof)
-        # assume getindex methods aren't directly recursive, since wrappers like ReshapedArrays won't look like it here
-        # should still manage to detect recursive growth either via other intermediate methods or actual type-equal signature recursion
-       && !istopfunction(tm, f, :getindex)
-       && !istopfunction(tm, f, :setindex!)
-        # the construct-to-convert method is a bottleneck in inference,
-        # so just assume that recursion will get prevented at some other point
-       && !(method.sig == Tuple{Type, Any}))
```
Comment (martinholters) [inline base/inference.jl]: 💯 for being able to remove all those special cases!

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by JeffBezanson** [comment]
Still seems to be an inference problem on AV. Oh well.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23912#issuecomment-332867645) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/92a20c4981f2b639b66e5098261e7143c81372d9/db40843_vs_d1b6f78/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
I've seen the exact same inference issue on AV in https://github.com/JuliaLang/julia/pull/23827 and https://github.com/JuliaLang/julia/pull/23273.

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by martinholters** [comment]
A few words on the changes to the type complexity limiting would be appreciated.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23912#issuecomment-334054885) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ae529b1fc32a322a976d99203266dbdb7f726a87/e331737_vs_ffb66cd/report.md). cc @ararslan

**Comment by vtjnash** [comment]
The main change is just that I relaxed the rules for unbounded recursion detection. For example, the hard cutoff on depth and length is gone. As a trade-off, the handling of recursion now limits more aggressively. Overall, that should mean this is actually friendlier to code that wants to recursively reduce some tuple (as demonstrated by the nanosoldier results), while being faster to handle cases where there is "accidental" recursion (Typical cases were I see this are from depwarn – due to a couple deprecated primitive functions – and the REPL code – due to specializations of refresh_multi_line. Also the inference code – since it is indeed a heavily recursive algorithm.)

**Comment by vtjnash** [comment]
All passing finally (except for new flakiness in sprand tests). Will merge tomorrow.

**Comment by ChrisRackauckas** [comment]
Does this fix https://github.com/JuliaLang/julia/issues/22255 ?
