### PR TITLE
Make sure the LLVM metadata is initialized before our custom LLVM pass

### LINKED ISSUE #17600: Multiple regressions in last daily bencmark
Noticed by @Sacha0 https://github.com/JuliaLang/julia/commit/5fe9e5342b06ef0cec58e67b9f7e4e82a9f0a860#commitcomment-18371997

Report: https://github.com/JuliaCI/BaseBenchmarkReports/blob/049d3920f3b933d4a84f9739407cd870cbbbb7df/daily_2016_7_22/report.md

### PR DESCRIPTION
**Pull request by yuyichao**
The issue is that the pass manager used for `code_llvm` is different from the one for JIT, which causes the really confusing result when we check the code with `code_llvm`........

Fix #17600

@JeffBezanson can you verify?

### CODE REVIEW

**Comment by yuyichao** [comment]
Let's see if I can get the syntax right =)

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by yuyichao** [comment]
c9b5d9d with this patch generate identical assembly with the previous commit (b27d520) here on llvm 3.7.1 (modulo inlined pointer addresses).

File: src/codegen.cpp [hunk 1]
```diff
@@ -4889,7 +4889,7 @@ extern "C" void jl_fptr_to_llvm(jl_fptr_t fptr, jl_lambda_info_t *lam, int specs
 #define V128_BUG
 #endif
 
-static void init_julia_llvm_env(Module *m)
+static void init_julia_llvm_meta()
```
Comment (JeffBezanson) [inline src/codegen.cpp]: `init_julia_llvm_meta(void)`

Comment (yuyichao) [inline src/codegen.cpp]: I think the c++compat warning is only for C code (and we have many `()` in C++ function declarations/definitions) but sure....

**Comment by vtjnash** [comment]
lgtm (nanosoldier didn't reply, so you didn't get it right)

**Comment by JeffBezanson** [comment]
This nullable failure keeps happening; really weird.

**Comment by yuyichao** [comment]
> nanosoldier didn't reply

It did, but disappeared after a force push.

**Comment by JeffBezanson** [comment]
Confirmed fixed for me locally (after much rebuilding of LLVM :)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17641#issuecomment-235454470) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/bdda723f60a34dfd5cb7554b9d94cb5c225f9bd3/fdaaefa_vs_0030eec/report.md). cc @jrevels
