### PR TITLE
fix #28990, improve top-level location info

### LINKED ISSUE #28990: LineNumber nodes in :toplevel expressions are ignored
`LineNumber` nodes can be used to add line numbers to a `:block` expression, but are ignored in `:toplevel` expressions:
```jl
julia> eval(Expr(:block, LineNumberNode(4, :foo), :(error("blah"))))
ERROR: blah
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at foo:4                   #### ⟵ DESIRED LINE NUMBER
 [3] eval at ./boot.jl:319 [inlined]
 [4] eval(::Expr) at ./client.jl:399
 [5] top-level scope at none:0

julia> eval(Expr(:toplevel, LineNumberNode(4, :foo), :(error("blah"))))
ERROR: blah
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at none:0                   ### ⟵ MISSING LINE NUMBER
 [3] eval at ./boot.jl:319 [inlined]
 [4] eval(::Expr) at ./client.jl:399
 [5] top-level scope at none:0
```
This seems like it makes it unnecessarily hard to add a line number when evaluating an arbitrary expression, because you can't put toplevel-only expressions (e.g. `module` or `struct`) inside `:block` expressions.

(This came up in addressing stevengj/SoftGlobalScope.jl#3.)

### PR DESCRIPTION
**Pull request by JeffBezanson**
This fixes #28990, plus the following issue:
Before:
```
julia> error()
ERROR: 
Stacktrace:
 [1] error() at ./error.jl:42
 [2] top-level scope at none:0
```
After:
```
julia> error()
ERROR: 
Stacktrace:
 [1] error() at ./error.jl:42
 [2] top-level scope at REPL[1]:1
```

This works by (1) passing an initial filename and line number to lowering (so that locations set in a `:toplevel` expression can apply to the following expression), and (2) making the REPL use the same parsing function that files (and `include_string`) use, which puts a line node before each expression.

`Base.parse_input_line` now wraps everything in a `:toplevel` expression including a line node.

The low-level parser entry points are simplified and renamed to parse-one, parse-all, and parse-file.

The `ex === ()` check in `parse` I believe was dead code; it looks like something that was left out when we replaced `()` with `nothing` a long time ago. All parsing functions return `nothing` for `parse("")`, so giving an error here would be breaking but we can consider whether we want to switch to that.

Question 1: I believe the code in interpreter.c setting `jl_lineno` ~~(which this PR removes)~~ is not necessary, since we should now be able to get line numbers from the interpreter stack trace mechanism. Can anyone think of a reason we need that code?

Question 2: I don't understand the need for the change to `repl_filename`. Without it, the filename for the first repl input is `REPL[0]` if the input is very simple, e.g. `error()` as in the example above. But if I insert even just a single space (within the same input cell) before `error()`, then you get `REPL[1]`.

### CODE REVIEW

**Comment by vtjnash** [comment]
> Can anyone think of a reason we need that code?

I find it can be invaluable for debugging segfaults, when the stack can be all smashed up and such. It's usually the first thing I type when opening gdb. Doesn't need to be particularly reliable (try/finally) or even exported for that use-case though.

File: base/client.jl [hunk 1]
```diff
@@ -146,15 +146,30 @@ function eval_user_input(@nospecialize(ast), show_value::Bool)
...
+            # if a parse error happens in the middle of a multi-line input
+            # return only the error, so that none of the input is evaluated.
+            return last
+        end
+    end
+    return ex
+end
+
 function parse_input_line(s::String; filename::String="none", depwarn=true)
     # For now, assume all parser warnings are depwarns
```
Comment (vtjnash) [inline base/client.jl]: I don't think the parser has any deprecations, so this support code is dead and should be removed

**Review by vtjnash — APPROVED** [review]

File: base/client.jl (hunk 1 above)
Comment (JeffBezanson) [reply base/client.jl]: We might add more parser deprecations in the future.
