### PR TITLE
Optimize issorted for rev=true

### LINKED ISSUE #54217: Unexpected allocation in issorted
`issorted` unexpectedly allocates when called with a custom `AbstractVector`, but only for `rev=true`. Also, the timing is larger for `rev=true`, I don't know if it's related. Intutively it should be same amount of work? (it's much worse in 1.10)

```
using BenchmarkTools                                                                                     
                                                                                                         
struct S <: AbstractVector{Float64}                                                                      
    v::Vector{Float64}                                                                                   
end                                                                                                      
                                                                                                         
Base.@propagate_inbounds Base.getindex(s::S, i) = s.v[i]                                                 
Base.length(s::S) = length(s.v)                                                                          
Base.size(s::S) = size(s.v)                                                                              
                                                                                                         
v = sort!(rand(10))                                                                                      
rv = sort(v, rev=true)                                                                                   
s = S(v)                                                                                                 
rs = S(sort(v, rev=true))                                                                                
                                                                                                         
@btime issorted($v)                                                                                      
@btime issorted($s)                                                                                      
@btime issorted($rv, rev=true)                                                                           
@btime issorted($rs, rev=true)                                                                           
```

Output:
```
  9.476 ns (0 allocations: 0 bytes)
  9.698 ns (0 allocations: 0 bytes)
  20.047 ns (0 allocations: 0 bytes)
  24.705 ns (1 allocation: 16 bytes)
```
```
Julia Version 1.12.0-DEV.383
Commit 903ffff167* (2024-04-22 04:40 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen Threadripper PRO 5945WX 12-Cores
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver3)
Threads: 24 default, 0 interactive, 24 GC (on 24 virtual cores)
```

### PR DESCRIPTION
**Pull request by LilithHafner**
Fixes #54217 by inserting an explicit branch on `rev`.
```julia
julia> using Chairmarks

julia> struct S <: AbstractVector{Float64}
           v::Vector{Float64}
       end

julia> Base.@propagate_inbounds Base.getindex(s::S, i) = s.v[i]

julia> Base.size(s::S) = size(s.v)

julia> v = sort!(rand(10));

julia> rv = sort(v, rev=true);

julia> s = S(v);

julia> rs = S(sort(v, rev=true));

julia> @b issorted($v)
7.973 ns

julia> @b issorted($s)
11.693 ns

julia> @b issorted($v, rev=false)
11.987 ns

julia> @b issorted($s, rev=false)
15.509 ns

julia> @b issorted($rv, rev=true)
18.178 ns

julia> @b issorted($rs, rev=true)
27.119 ns (1 allocs: 16 bytes)

julia> @eval Base.Sort function issorted(itr;
               lt=isless, by=identity, rev::Union{Bool,Nothing}=nothing, order::Ordering=Forward)
           # Explicit branching because the compiler can't optimize away the
           # type instability of the `ord` call with Bool `rev` parameter.
           if rev === true
               issorted(itr, ReverseOrdering(ord(lt,by,nothing,order)))
           else
               issorted(itr, ord(lt,by,nothing,order))
           end
       end
issorted (generic function with 5 methods)

julia> @b issorted($v)
8.213 ns

julia> @b issorted($s)
12.078 ns

julia> @b issorted($v, rev=false)
10.812 ns

julia> @b issorted($s, rev=false)
14.343 ns

julia> @b issorted($rv, rev=true)
10.823 ns

julia> @b issorted($rs, rev=true)
14.408 ns
```

### CODE REVIEW

**Comment by LilithHafner** [comment]
Branching on ordering as early as possible should be beneficial for sorting runtime (though not necessarily compile time). When I benchmarked this, however, I found a surprisingly small to negligible difference.

I'd be open to merging a PR that stops telling the compiler to specialize on whether an order is reversed, but I'd want to see some motivation for it in benchmarks (e.g. decreased compile times).

Such a PR would also need to adapt existing special cases for ForwardOrdering and ReverseOrdering which are substantially faster than generic orderings in some common cases.

---

I would say the underlying issue here is the failure of constant propagation combined with not explicitly forcing a runtime branch. For example, `sort!($rs, rev=true)` happens not to have this allocation or runtime hit.

**Comment by nsajko** [comment]
My logic is that [`Base.Order.ord`](https://docs.julialang.org/en/v1/base/sort/#Base.Order.ord) is itself a public function, so it'd, ideally, be type-stable.

File: base/sort.jl [hunk 1]
```diff
@@ -85,9 +85,16 @@ julia> issorted([1, 2, -2, 3], by=abs)
...
 """
-issorted(itr;
-    lt=isless, by=identity, rev::Union{Bool,Nothing}=nothing, order::Ordering=Forward) =
-    issorted(itr, ord(lt,by,rev,order))
+function issorted(itr;
+        lt=isless, by=identity, rev::Union{Bool,Nothing}=nothing, order::Ordering=Forward)
+    # Explicit branching because the compiler can't optimize away the
+    # type instability of the `ord` call with Bool `rev` parameter.
+    if rev === true
+        issorted(itr, ReverseOrdering(ord(lt,by,nothing,order)))
```
Comment (nsajko) [inline base/sort.jl:93]: `ord(lt,by,nothing,order)` is duplicated. Could you instead assign it to a variable before the `if` statement, and then use the variable in both branches?

Comment (LilithHafner) [reply base/sort.jl]: As I was making that change I grepped for `=== false` and found this paradigm repeated many times through the file in various formats, so I copied the style used elsewhere which does contain two `ord` calls but does not have redundancy.
