### PR TITLE
Fix sparse Subarray fill!

### LINKED ISSUE #38009: Sparse matrices broadcast broken
This is obviously working on 1.5 and I am pretty sure it was working a few days ago, but on recent master:
```julia
julia> using SparseArrays

julia> M = spzeros(Int, 5, 5); M[1, 3] = 1; M[1, 4] = 1; M[1, 5] = 1;

julia> M[2, 3:3] .= 1
ERROR: MethodError: no method matching getindex(::Int64, ::UnitRange{Int64})
Closest candidates are:
  getindex(::Number) at number.jl:93
  getindex(::Number, ::Integer) at number.jl:94
  getindex(::Number, ::Integer...) at number.jl:99
  ...
Stacktrace:
 [1] _spsetnz_setindex!(A::SparseMatrixCSC{Int64, Int64}, x::Int64, I::Int64, J::UnitRange{Int64})
   @ SparseArrays ~/julia/juliadev/usr/share/julia/stdlib/v1.6/SparseArrays/src/sparsematrix.jl:2707
 [2] fill!(V::SubArray{Int64, 1, SparseMatrixCSC{Int64, Int64}, Tuple{Int64, UnitRange{Int64}}, false}, x::Int64)
   @ SparseArrays ~/julia/juliadev/usr/share/julia/stdlib/v1.6/SparseArrays/src/sparsematrix.jl:2587
 [3] copyto!
   @ ./broadcast.jl:894 [inlined]
 [4] materialize!
   @ ./broadcast.jl:848 [inlined]
 [5] materialize!(dest::SubArray{Int64, 1, SparseMatrixCSC{Int64, Int64}, Tuple{Int64, UnitRange{Int64}}, false}, bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(identity), Tuple{Int64}})
   @ Base.Broadcast ./broadcast.jl:845
 [6] top-level scope
   @ REPL[23]:1

julia> versioninfo()
Julia Version 1.6.0-DEV.1210
Commit a1da84c3b0 (2020-10-13 13:46 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Closes #38009.

This should actually improve performance in broadcasted scalar assignments to sparse matrices (`dest .= val`). The functionality touched here hasn't been called since #26347, which had a missing `<:` and hided the function in dispatch, which was fixed in #37856, but revealed #38009. Also, #26347 added support for `Integer`s, whereas the original code was written only for `I::AbstractVector{<:Integer}`, which included indexing into `I`. I haven't replaced the obviously scalar indexing calls by calls to the helper function, to allow for the detection of any flaws in the indexing logic (it's pretty involved, I must admit). You can index into a number, but only with index `1`. So, if there were scalar indexing calls with helper indices other than `1`, we should still see it, but tests seem to pass locally.

### CODE REVIEW

File: stdlib/SparseArrays/src/sparsematrix.jl [hunk 1]
```diff
@@ -2738,6 +2738,9 @@ function _spsetnz_setindex!(A::AbstractSparseMatrixCSC{Tv}, x::Tv,
     end
     return A
 end
+# ignore indexing into a Number by range
+_getrowinds(I::Number, range) = I
+_getrowinds(I::AbstractVector{<:Integer}, range) = I[range]
```
Comment (mbauman) [inline stdlib/SparseArrays/src/sparsematrix.jl:2743]: Might as well preserve that huge `@inbounds` block through here.

```suggestion
_getrowinds(I::AbstractVector{<:Integer}, range) = @inbounds I[range]
```

File: stdlib/SparseArrays/src/sparsematrix.jl [hunk 2]
```diff
@@ -2704,7 +2704,7 @@ function _spsetnz_setindex!(A::AbstractSparseMatrixCSC{Tv}, x::Tv,
                                 resize!(nzvalA, nnzA)
                             end
                             r = rowidx:(rowidx+(new_stop-new_ptr))
-                            rowvalA[r] .= I[new_ptr:new_stop]
+                            rowvalA[r] .= _getrowinds(I, new_ptr:new_stop)
```
Comment (vtjnash) [inline stdlib/SparseArrays/src/sparsematrix.jl:2707]:
```suggestion
                            rowvalA[r] .= I <: Number ? I : I[new_ptr:new_stop]
```
I feel like this might be more concise? But I'm happy either way

Comment (dkarrasch) [reply stdlib/SparseArrays/src/sparsematrix.jl]: Agreed.

File: stdlib/SparseArrays/src/sparsematrix.jl [hunk 3]
```diff
@@ -2704,7 +2704,7 @@ function _spsetnz_setindex!(A::AbstractSparseMatrixCSC{Tv}, x::Tv,
                                 resize!(nzvalA, nnzA)
                             end
                             r = rowidx:(rowidx+(new_stop-new_ptr))
-                            rowvalA[r] .= I[new_ptr:new_stop]
+                            rowvalA[r] .= I <: Number ? I : I[new_ptr:new_stop]
```
Comment (mbauman) [inline stdlib/SparseArrays/src/sparsematrix.jl:2707]:
```suggestion
                            rowvalA[r] .= I isa Number ? I : I[new_ptr:new_stop]
```

Comment (dkarrasch) [reply stdlib/SparseArrays/src/sparsematrix.jl]: 🤦

**Comment by dkarrasch** [comment]
By the way, does this supersede #24711? Not necessarily this PR here, but more like #37856? @KristofferC
