### PR TITLE
Fix #10959 bugs with UTF-16 conversions

### LINKED ISSUE #10959: Poor performance (and excessive garbage collection) in utf8/utf16/utf32 conversion functions
These all tend to be rather slow because they create an empty array, and append to it 1 character at a time... also, instead of having specific converters for things like:
ASCIIString -> UTF16String, UTF8String -> UTF16String, UTF32String -> UTF16String
ASCIIString -> UTF32String, UTF8String -> UTF32String, UTF16String -> UTF32String
these are handled by a single generic function (encode16 for UTF16String)

### PR DESCRIPTION
**Pull request by ScottPJones**
Rewrote a number of the conversions between `ASCIIString`, `UTF8String`, and `UTF16String`.
Rewrote `length()` for `UTF16String`.
Improved `reverse()` for `UTF16String`.

Added over 150 lines of testing code to detect the above conversion problems

Added (in a gist) code to show other conversion problems not yet fixed:
https://gist.github.com/ScottPJones/4e6e8938f0559998f9fc

Added (in a gist) code to benchmark the performance, to ensure that adding the extra validity
checking did not adversely affect performance (in fact, performance was greatly improved).
https://gist.github.com/ScottPJones/79ed895f05f85f333d84

### CODE REVIEW

**Comment by hayd** [comment]
FWIW I think this is a big improvement over #11004, I really like the break up into multiple files. Honestly, I'm glad this is a separate PR and away from the 500 comment behemoth; getting directed to that on a git bisect would be terrible. +1

**Comment by ScottPJones** [comment]
@hayd #11004 already *had* the breakup into multiple files... that's what surprised me about the closing it off in the middle of active review... but I am glad to get away from the 500 comments, CodeHub crashes when trying to read it!

**Comment by tkelman** [comment]
Could you summarize what's different here relative to the status of where #11004 left off? The diff appears to be only about 100 lines shorter here, but I'm having a hard time seeing exactly where.

File: base/utfconvert.jl [hunk 1]
```diff
@@ -0,0 +1,444 @@
...
+@param[in]  str::UTF8String
+
+@return     ::UTF16String
+@throws     ArgumentError
+""" ->
+=#
+function convert(::Type{UTF16String}, str::UTF8String)
+    dat = str.data
+    # handle zero length string quickly
+    sizeof(dat) == 0 && return empty_utf16
```
Comment (jakebolewski) [inline base/utfconvert.jl]: I think it is best to return an explicit copy here, not an alias to a global.  The empty UTF16String is immutable, but its best not to propagate undefined behavior if some user level function decides to muck with string internals.

File: base/utf16.jl [hunk 2]
```diff
@@ -30,92 +15,69 @@ function endof(s::UTF16String)
...
+unsafe_convert{T<:Union(Int16,UInt16)}(::Type{Ptr{T}}, s::UTF16String) =
+    convert(Ptr{T}, pointer(s))
+
 function convert(::Type{UTF16String}, data::AbstractVector{UInt16})
     !isvalid(UTF16String, data) && throw(ArgumentError("invalid UTF16 data"))
     len = length(data)
-    d = Array(UInt16, len + 1)
-    d[end] = 0 # NULL terminate
-    UTF16String(copy!(d,1, data,1, len))
+    @inbounds return UTF16String(setindex!(copy!(Vector{UInt16}(len+1),1,data,1,len),0,len+1))
```
Comment (tkelman) [inline base/utf16.jl]: Would this call for making a variant of `fast_utf_copy` that takes an offset? (and would need to move the function definition to before this file) The original code has this 1-offset, could you add a comment as to why?

**Comment by ScottPJones** [comment]
I incorporated most of the last round of comments from the reviews (I was running unit tests on that when it was closed :disappointed: ) [all of the things that I said I would fix], I moved (at least for now, I think it is a step backwards) some of the conversion functions from `utfconvert.jl` to `utf16.jl`/`utf32.jl` to make the diffs cleaner (and so I wouldn't get dinged for stuff I didn't change).  There is some potential for further refactoring of a couple functions, and removal of some functions, but those suggestions either were definitely, or likely to be breaking changes, and so I didn't feel they were appropriate for this PR.

File: base/utfconvert.jl (hunk 1 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: That is the technique used by utf8.jl, I don't know who wrote that...

File: base/utf16.jl (hunk 2 above)
Comment (ScottPJones) [inline base/utf16.jl]: That's all because of the bloody handling of \0... one of the many inconsistencies between the various string types in Julia.

File: base/utferror.jl [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+@brief      Throws ArgumentError with information about the specific error, location, and character
+
+@param[in]  errcode Error code for Unicode error (one of UTF_ERR_*)
+@param[in]  charpos Index of invalid byte or character
+@param[in]  invchar Invalid byte or character
+
+@throws never returns, always throws ArgumentError
+""" ->
+=#
+function utf_errfunc(errcode::Integer, charpos, invchar)
```
Comment (jakebolewski) [inline base/utferror.jl]: Instead of  ad-hoc template substitution, I still think it would be more explicit to construct and throw the exception at the point of the error.  `utf_errfunc` does not really cut down on code redundancy in throwing similar error messages.

File: base/utfconvert.jl [hunk 4]
```diff
@@ -0,0 +1,444 @@
...
+    # handle zero length string quickly
+    sizeof(dat) == 0 && return empty_utf32
+    # Validate UTF-8 encoding, and get number of words to create
+    len, flags = check_string_utf8(dat)
+    # Optimize case where no characters > 0x7f
+    totlen = len+1
+    flags == 0 && return fast_utf_copy(Char, totlen, dat)
+    # has multi-byte UTF-8 sequences
+    buf = Vector{Char}(totlen)
+    @inbounds buf[totlen] = 0 # NULL termination
```
Comment (jakebolewski) [inline base/utfconvert.jl]: It would be useful to remove any inbounds annotations  that have no measurable impact on performance (I suspect many of them make no difference in the actual runtime).

File: base/utferror.jl (hunk 3 above)
Comment (yuyichao) [inline base/utferror.jl]: My guess is this function is used to avoid creating GC frame. I still think it is the safest to mark it as `@noinline` though.

File: base/utfconvert.jl [hunk 5]
```diff
@@ -0,0 +1,444 @@
...
+        buf[out + 1] = 0xf0 | (ch >>> 18)
+        buf[out + 2] = 0x80 | ((ch >>> 12) & 0x3f)
+        buf[out + 3] = 0x80 | ((ch >>> 6) & 0x3f)
+        buf[out + 4] = 0x80 | (ch & 0x3f)
+    end
+end
+
+#=
+"""
+@brief      Converts an AbstractString to a UTF16String
```
Comment (jakebolewski) [inline base/utfconvert.jl]: A superficial comment.  I would make this less java-doc'y and just simple plain text.  It does not no really fit in with the comment structure of the rest of the code base.

File: base/utfconvert.jl [hunk 6]
```diff
@@ -0,0 +1,444 @@
+# This file is a part of Julia. License is MIT: http://julialang.org/license
+
+# Functions to convert to different UTF encodings
+
+# Quickly copy and set trailing \0
+@inline function fast_utf_copy(T::Type{UInt16}, len, dat)
+    @inbounds return UTF16String(setindex!(copy!(Vector{T}(len), dat), 0, len))
```
Comment (jakebolewski) [inline base/utfconvert.jl]: presumably these inbounds are unnecessary, as they save only a couple bounds checks.

File: base/utfconvert.jl (hunk 4 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: I'm sorry, but that would be ages of work to try to figure out, for what real gain?

File: base/utf32.jl [hunk 7]
```diff
@@ -1,42 +1,17 @@
...
-    UTF32String(a)
-end
+sizeof(s::UTF32String) = sizeof(s.data) - sizeof(Char)
 
 function convert(::Type{UTF32String}, data::AbstractVector{Char})
     len = length(data)
-    d = Array(Char, len + 1)
-    d[end] = Char(0) # NULL terminate
-    UTF32String(copy!(d,1, data,1, len))
+    @inbounds return UTF32String(setindex!(copy!(Vector{Char}(len+1),1,data,1,len),0,len+1))
```
Comment (tkelman) [inline base/utf32.jl]: Same comment here as above, where `fast_utf_copy` would be more concise for this. And looking into how the 5-argument `copy!` works, I think it's 1-based so when both offsets are 1 it may be equivalent to 2-arg `copy!`? Perhaps with different behavior when source and dest are different lengths. Maybe safe and equally generic to use this 5-arg offset-starting-at-1 form in `fast_utf_copy` ?

File: base/utfconvert.jl (hunk 5 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: The rest of the code base hardly has enough comments to count...  I am trying to push people to start really documenting their code, and `doxygen` (not `javadoc`) is used already elsewhere in Julia (in C code), and it supports Markdown syntax.  I've also been working on making the `@doc` support be able to work much earlier in the build process.

File: base/utferror.jl (hunk 3 above)
Comment (jakebolewski) [inline base/utferror.jl]: Creating a gc-frame is not the end of the world, it is created virtually everywhere in the Julia codebase.   I would guess that the change would be marginal to insignificant in terms of performance.

Comment (ScottPJones) [inline base/utferror.jl]: I actually saw a major difference, in some early tests I did...

File: base/utfconvert.jl (hunk 4 above)
Comment (tkelman) [inline base/utfconvert.jl]: > for what real gain?

Increasing the chances of this getting merged. Annotations like this should only be used where you're sure they make a difference, not haphazardly.

This is dangerously close to "resubmit[ting] the same pull request" which Stefan asked you not to do, in the interest of saving everyone reviewing time looking at the same exact issues.

File: base/utfconvert.jl (hunk 6 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: Again, if it even saves a couple of bounds checks, having the `@inbounds` doesn't hurt anything, does?

File: base/utferror.jl (hunk 3 above)
Comment (tkelman) [inline base/utferror.jl]: I agree that this extra indirection for error handling is unusual and should be removed for now. We don't have any other infrastructure anywhere else in base for internationalizing error messages, we don't need it here at this very moment. We can work on a more generic solution for that problem and start using it across the entire codebase later.

File: base/utf32.jl (hunk 7 above)
Comment (ScottPJones) [inline base/utf32.jl]: The difference is that it picks up the length from the target array, but here the target array is 1 larger than the source (because of that bloody \0 again).  There were only two occurrences of this, one for UTF16String, and another for UTF32String, so why bother making a function or two?

File: base/utfconvert.jl (hunk 4 above)
Comment (jakebolewski) [inline base/utfconvert.jl]: @ScottPJones could you run the benchmarks you have with just removing all the `@inbounds` annotations you have in this file?  That should be a simple search and delete  That would give a rough overview of the performance hit bounds checking causes in this code.

File: base/utferror.jl (hunk 3 above)
Comment (ScottPJones) [inline base/utferror.jl]: I was going to start using this for all the Unicode related error messages right now.

File: base/utfconvert.jl (hunk 6 above)
Comment (tkelman) [inline base/utfconvert.jl]: It can result in undefined behavior if the array access turns out to be out of bounds. That inbounds annotation may end up turning off bounds checking everywhere inside the `UTF16String` constructor call, which could end up doing unsafe things. Maybe the current code is safe, but some future refactoring might make it unsafe and we'd start getting intermittent hard-to-reproduce segfaults instead of BoundsErrors. Hence the strong desire to limit the number of places we use these performance annotations.

File: base/utferror.jl (hunk 3 above)
Comment (jakebolewski) [inline base/utferror.jl]: Do you have hard numbers, or a benchmark I could run to verify this?

File: base/utf32.jl (hunk 7 above)
Comment (tkelman) [inline base/utf32.jl]: Because you already made almost exactly the same function, and this code is ugly and not immediately clear. It's also a refactoring that doesn't make the old code any clearer, so seems unnecessary. If it were a single short function call that would look nicer.

File: base/utferror.jl (hunk 3 above)
Comment (ScottPJones) [inline base/utferror.jl]: Just because something hasn't been thought about before, and isn't currently handled elsewhere, is not at all a good excuse for not trying to improve things... having *something* is better than saying, "some time in the future, we'll design something better and use it..." this lets people see how at least one approach (that has been used for > 20 years internationally) works.

Comment (tkelman) [inline base/utferror.jl]: Even if it helps performance noticeably, cutting out this style of error handling will make this PR both smaller and less contentious. Save the diff, apply it as a reverse diff for a later branch and separate PR.

File: base/utfconvert.jl (hunk 4 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: Even that may take an hour, but is doable.... I'm building now.

File: base/utfconvert.jl (hunk 6 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: I did not add those haphazardly, BTW, and the UTF16String constructor is in this set of code (utftype.jl).

File: base/utferror.jl (hunk 3 above)
Comment (hayd) [inline base/utferror.jl]: @ScottPJones whilst this is all true, you have to save this battle for another PR. It's quite a big/important change that requires reflection/discussion. Keep this focussed. :)

File: base/utfconvert.jl (hunk 1 above)
Comment (tkelman) [inline base/utfconvert.jl]: Ah, indeed. @jakebolewski should we just add a `copy` on https://github.com/JuliaLang/julia/blob/c85f1be7b7dec67af4e8ff9a0690284d77d09c7e/base/utf8.jl#L123?

File: base/utferror.jl (hunk 3 above)
Comment (jakebolewski) [inline base/utferror.jl]: @ScottPJones, could you clarify what "major" means? (ex. % performance hit).

File: base/utfconvert.jl (hunk 5 above)
Comment (hayd) [inline base/utfconvert.jl]: I don't see how `@doc` could happen before strings are defined, it needs to parse strings into Markdown. We may be stuck with a sep. file (as is trialed at the moment in `basedocs.jl`), I guess another option in principle is to do a second pass of the files and just apply the docstrings (don't run anything)...

I think the idea was (by 0.4 release) for the `@doc` macro to be optional you just write:
```
"""docstring *with markdown*"""
function f(...
```

But this is way off topic!

File: base/utferror.jl (hunk 3 above)
Comment (jakebolewski) [inline base/utferror.jl]: I'm just trying to get some numbers to put with your statements.  That was really all @stevengj was asking for. Hard numbers that can be reproduced often lead to performance improvements in Base Julia code and the standard library.

File: base/utfconvert.jl (hunk 1 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: Is potentially creating tons of extra allocations ("" is *very* common) to protect against someone doing something bad really a good thing?   Ban things like using C pointers then...

File: base/utf32.jl (hunk 7 above)
Comment (ScottPJones) [inline base/utf32.jl]: I wish you all would agree first on how stuff should be done in julia... that type of "ugly code" I was told to use, by Jameson...  I've been trying to be responsive to everybody's advice... but I feel like I've got whiplash!
`UTF32String(setindex!(copy!(Vector{Char}(length(d)+1), d), 0, length(d)+1))`

File: base/utferror.jl (hunk 3 above)
Comment (ScottPJones) [inline base/utferror.jl]: That error handling *is* an important part of this change.
Go compare what sort of error messages you got before (when it even detected errors) compared to with this change.

File: base/utf32.jl [hunk 8]
```diff
@@ -73,26 +45,24 @@ function convert(T::Type{UTF32String}, bytes::AbstractArray{UInt8})
         copy!(d,1, data, 2, length(data)-1)
     elseif data[1] == Char(0xfffe0000) # byte-swapped
         d = Array(Char, length(data))
-        for i = 2:length(data)
-            d[i-1] = bswap(data[i])
-        end
+        @inbounds for i = 2:length(data) ; d[i-1] = bswap(data[i]) ; end
```
Comment (tkelman) [inline base/utf32.jl]: Another unnecessary change - if you measured the `@inbounds` as making a difference then it can probably stay, but there's no need to rearrange formerly indented code to put it on one line like this.

Comment (ScottPJones) [inline base/utf32.jl]: That was from when I thought it had to be on one line for @inbounds to work...

File: base/utferror.jl (hunk 3 above)
Comment (tkelman) [inline base/utferror.jl]: The error *messages* are great. This separate-function, `const`-coded *implementation* of them is what we're objecting to. It's very un-Julian. We do need people fighting the battle to make error handling better, but using the implementation style that you have here doesn't need to be a part of the "fix bugs in unicode conversions" PR.

File: base/utfconvert.jl (hunk 5 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: It doesn't need to parse strings into Markdown, not at that time, it just needs to save the string and certain information in a structure.  I and others have been discussing all of this on Google groups...  Simple string parsing is done in Lisp, the thing I had to move earlier is parsing triple quoted strings.

File: base/utf32.jl (hunk 7 above)
Comment (tkelman) [inline base/utf32.jl]: Can you find a link to that comment by @vtjnash? Did he specifically say that the existing code on these lines should change at all? You're going to have to take a moving average of all the review you get since everyone's style is a little different, as you've probably noticed by now.

File: base/utferror.jl (hunk 3 above)
Comment (jakebolewski) [inline base/utferror.jl]: @ScottPJones we are not arguing that better error messages are not hugely beneficial.  If writing the code this way (extracting out into a separate function, using global error constants) was motivated by performance issues then it is best to say:

> I wrote this code first with inline `throw(Exception())` but that created a GC frame which degraded performance in the validation function.  I extracted out the error functions this way and that resulted in a 25% performance increase shown by the following benchmark:

```julia
function bench()
    # some code
end
@time bench()
```

File: base/utfconvert.jl [hunk 9]
```diff
@@ -0,0 +1,444 @@
...
+# Get rest of character ch from 4-byte UTF-8 sequence in dat
+@inline function get_utf8_4(dat, pos, ch)
+    @inbounds return (((ch & 0x7) << 18)
+                        | (UInt32(dat[pos-2] & 0x3f) << 12)
+                        | (UInt32(dat[pos-1] & 0x3f) << 6)
+                        | (dat[pos] & 0x3f))
+end
+
+# Output a character as a 4-byte UTF-8 sequence
+@inline function output_utf8_4(buf, out, ch)
```
Comment (tkelman) [inline base/utfconvert.jl]: this is mutating, should have trailing `!`

Comment (tkelman) [inline base/utfconvert.jl]: also the names of this and the `get_utf8_` functions would be clearer as `_3byte` or `_4byte` imo

File: base/utfconvert.jl (hunk 4 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: It's 5:30am now, and I need a couple hours of sleep, but I'm seeing from 21%-100% slower without the @inbounds.   I'll stick them in a Gist later.  That's pretty major difference to me...

File: base/utfconvert.jl (hunk 9 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: Yep, I'll fix

File: base/utf32.jl (hunk 7 above)
Comment (ScottPJones) [inline base/utf32.jl]: It was in one of comments that isn't shown anymore, because it's to an outdated diff... I'll try to track it down... (after some sleep)

**Comment by tkelman** [comment]
We already have 50ish comments worth of mostly minor review back-and-forth on this new PR. Given this is only about 10% different than #11004 I have a sneaky feeling @StefanKarpinski would object pretty strongly to merging it as is, even after addressing the review comments that have been made up to this point.

So, question for you @ScottPJones. How much of a **correct** bugfix version of this could we distill this down to, strictly using `check_string_abs`? None of the other `check_string_*` variants for now. And as few as possible, maximally generic `convert` methods, parameterized on the input and output types to reuse as many lines of code as possible.

File: base/utfcheck.jl [hunk 10]
```diff
@@ -0,0 +1,255 @@
...
+@brief      Validates and calculates number of characters in a UTF-32 encoded vector of UInt32
+
+@param[in]  dat     Vector{UInt32}
+@param[in]  options flags to determine error handling (default 0)
+
+@return     (total characters, flags, 4-byte, 3-byte, 2-byte)
+@throws     ArgumentError
+""" ->
+=#
+function check_string_utf32(dat::Vector{UInt32}, len::Int, options::Integer=0)
```
Comment (stevengj) [inline base/utfcheck.jl]: This function is almost line-for-line identical with `check_string_abs`.  Can't you merge them?  i.e. why can't you use `ch, pos = next(dat, pos)`?

Comment (ScottPJones) [inline base/utfcheck.jl]: I'd answered this before... but again 1) I had done *exactly* that, and ran into severe performance degradation, which @JeffBezanson looked into and *may* have totally addressed, and would need some time to adequately benchmark, look into generated code, etc. before I would feel comfortable trying that again, 2) I had been told previously that I should not mix `AbstractString` and `Vector{T}` in a method like that, so I am getting conflicting requirements from the reviewers.

File: base/utfconvert.jl (hunk 4 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: Please take a look at the following two gists (if you don't trust what I said above :grinning:):
https://gist.github.com/ScottPJones/983e7d284bb001a5645b ; `@inbounds` version
https://gist.github.com/ScottPJones/eb3dd92729c6aa9ba3aa ; no `@inbounds` version

File: base/utferror.jl (hunk 3 above)
Comment (ScottPJones) [inline base/utferror.jl]: This current structure was motived by a number of things:
1) Long familiarity [25 years] with a very powerful system for having localizable messages,
    where the messages can handle differences in word order between languages, and can handle
    plain output messages, warning messages, and error messages, with any number of arguments
    included in the output.
2) Fairly severe performance problems with GC frames, when I first implemented this by adding
    a new UnicodeError.  If that were totally fixed (see @yuyichao's #11508), I would prefer to move
    back to using UnicodeError, but I really don't think that that should be a reason to hold this up.
3) Enum's not working in Base, at least not early enough to be useful for this.
    When I first started implementing this, I used Enums, which is what all of those const's really
    meant to be.
So, yes, these could be better, but not at the moment, because of issues out of my control.
I will definitely change them to be what I'd originally wanted (which I think you all as well would prefer), as soon as those issues are dealt with.

**Comment by nalimilan** [comment]
I don't think my question from https://github.com/JuliaLang/julia/pull/11004/files#r31562735 about checking for surrogates in `Char`s obtained by indexing an `AbstractString` (in `check_string_abs`) has been addressed. Do we consider part of the `AbstractString` interface that `getindex` must return valid codepoints (as I think we should)?

**Comment by ScottPJones** [comment]
I think that is a whole separate issue, and definitely should not be addressed here.
What I implemented correctly handles the way things *currently* are.

**Comment by ScottPJones** [comment]
@nalimilan I opened a new PR (I must be a glutton for punishment!) where I think it might be a good place to discuss the issue you raised. (#11558)

File: base/utferror.jl (hunk 3 above)
Comment (tkelman) [inline base/utferror.jl]: 1 is not relevant here. You're continuing to argue from authority as resistance against changes we are all telling you will help this PR be smaller, less controversial, and more likely to be merged.

2. If you had written that down, with numbers, saying "changing just the error code structure from something simple to this resulted in x% speedup on this benchmark gist" (btw please provide an executive summary of the numbers in those gists, there's way too much data there to parse at a glance) as @jakebolewski said, then we'd probably give in on this point if x were large enough.

3 is superficial, Enums are new and not yet widely used, and would still result in this looking like C-written-in-Julia instead of idiomatic Julia code.

Every line of code in this PR is under your control. Dozens of people have suggested dozens of ways to break this down and make this substantially better.

**Comment by ScottPJones** [comment]
@tkelman Maybe, I'll try that out, and look at the native code generated.  Thanks!

File: base/utferror.jl (hunk 3 above)
Comment (ScottPJones) [inline base/utferror.jl]: 1) I actually wasn't trying to "argue from authority" at all.  @jakebolewski had talked about my motivations for making the change this way, and I was trying to answer that as best I could.
Are Julians *always* so sensitive about talking about one's experience, in the context of a technical discussion?  IMO, it can help shed light on a issue... I, for example, am very interested to learn about Julian's experiences in the technical/numeric/scientific computing world.  The type of arguing that I've seen here that does bother me is "argument from a *position* of authority", and people willing to use that position to curtail or stifle discussion.

2) I have tried to give the numbers and executive summaries as I went along, but with 500+ comments, I think the early ones where I tested different error handling strategies got lost in the chaff.  As soon as I have a minute (I *am* also busy working here in Belgium), I'll try to recreate my tests that pointed me to the issue of GC frame creation [and I know that @yuyichao is working hard to fix things so it wouldn't even be an issue].  I *did* give an executive summary just before I went to bed, did you miss it?  21-100% slower without the `@inbounds` macros... (I think more frequently closer to 100%).

3) Well, first off, I haven't really seen that much consistency in the Julia code I've been looking at...
(maybe because it is older code, who knows), so I don't totally buy the argument that *everything* must be written in "idiomatic" Julia code.  Different people also have different ideas of what constitutes good structure and practice...  Does Julia really need some sort of unwritten style that everybody must follow? (at least, if it were *written down*, people might have a chance of knowing what was expected, and using that, or debating whether the current practice really is good...)
I'm not sure at all that the suggestions that I haven't incorporated so far would make things "substantially better"...

About the error handling: the reason the *very first thing* that I implemented was the better error handling, is that I would *not* have been able to easily find and fix all of the many bugs in the current code without the enhanced messages.   It all ties together...  this PR adds some extra overhead already to do complete validity checking, which people worried about in the initial comments on #11004... A big goal of mine was to at the very least, not introduce any regressions in performance (the performance was so bad already, that would have been criminal).  Because of my approaches, not only is the code not slower, even with the extra checking, it is faster as well.
At least in my early benchmarking, the extra overhead in the inner loops (which is *where* the error checking happens!) made the performance frequently worse than the current bad performance.

All of the above is why I really do not think it is at all a good think to try to split this up as has been suggested.

Comment (ScottPJones) [inline base/utferror.jl]: About the micro benchmarking... I know that the way it just runs things and uses `@time` and everything is really crappy... I really haven't had time to learn how best to collect all of the information that I wish to and save it for later processing... I miss having a high speed database always available just by adding a `^` character to the associative array!  (my changes to gc.c that already got merged actually help collect the data, but storing and retrieving)
Any pointers to how better to benchmark things like this, and produce a nice spreadsheet or graph in julia, would be *greatly* appreciated!

**Comment by ScottPJones** [comment]
OK, I haven't gotten *everything* asked for changed (because I want to make sure the performance doesn't suffer, esp. to the point of being a regression compared to the current code), but hopefully this will make people happier, and it still maintains my design goals.
Especially look at the changes to `utferror.jl` and `utfcheck.jl`.
Thanks everybody for the time spent reviewing this, I *really* do appreciate it!

**Comment by yuyichao** [comment]
Not really relavant for this PR but the travis test got killed by OOM killer and the test passes??? WTH?

**Comment by yuyichao** [comment]
https://travis-ci.org/JuliaLang/julia/jobs/65276682#L4036

File: base/utfconvert.jl (hunk 5 above)
Comment (hayd) [inline base/utfconvert.jl]: @ScottPJones Can you link to this discussion, i can't see to find it on either group.

It's somewhat confusing to me that unlike Markdown, Docile is still being actively developed on  *outside* base. So it *seems* like this isn't going to make it to 0.4? (or is there an issue I'm missing?)

**Comment by ScottPJones** [comment]
Yes, what's up with the strange OOM errors? I saw cases before my change, so I don't think it is related.
Anyway, I'd appreciate it if people could take a look at the latest version, I was able to make things more generic without performance degrading (it seems @JeffBezanson's changes did fix the bugs I stumbled across before).  Thanks!

**Comment by yuyichao** [comment]
Yeah, the OOM killer has nothing to do with this PR, the `dmesg` output is added as an indicator for OOM errors. This issue is tracked separately https://github.com/JuliaLang/julia/issues/11553 .

I was just a little surprised that the OOM killer firing doesn't make the test fail......

**Comment by ScottPJones** [comment]
Yes, such a nasty ending definitely *should* make the test fail (whether it was caused by the PR or not!)

File: base/utfcheck.jl [hunk 11]
```diff
@@ -0,0 +1,187 @@
...
+                      dat::T,
+                      len::Int = (T == AbstractString ? endof(dat) : (sizeof(dat)>>>(T==Vector{UInt16}?1:2))),
+                      pos::Int = (T == AbstractString ? start(dat) : 0)
+                      ; options::Integer = 0)
+    local ch::UInt32
+    flags::UInt = 0
+    totalchar = num2byte = num3byte = num4byte = 0
+    @inbounds while pos < len
+        if T == AbstractString
+             ch, pos = next(dat, pos)
```
Comment (tkelman) [inline base/utfcheck.jl]: any reason this wouldn't work for the vector cases too?

Comment (ScottPJones) [inline base/utfcheck.jl]: Please be more specific... wouldn't *what* work for the vector cases?   Thanks!

Comment (tkelman) [inline base/utfcheck.jl]: `ch, pos = nex(dat, pos)`, you might not need this `if T == AbstractString` at all

**Comment by tkelman** [comment]
> Maybe, I'll try that out, and look at the native code generated. Thanks!

The comment that this was in response to seems to be hidden due to a rebase (you don't need to rebase and squash every single update, sometimes it's easier to follow the discussion if things stay as incremental commits until all feedback has been addressed, then squashing at that point), but the implementation of `fast_utf_copy` still looks the same.

The improved generality of `check_string` looks much better now, and the UTF-8 case looks different enough that it probably wouldn't make much sense to try folding that in too.

Now can the same be done for all the `convert` methods?

File: base/utfcheck.jl (hunk 11 above)
Comment (ScottPJones) [inline base/utfcheck.jl]: Oh!  I had just copied that from the older code that walked over an `AbstractString`... I had thought, for an `AbstractString`, you couldn't count on the next position being +1, so that's why you had to use `next`, and `start`, and `endof`.  Given that that is the way most of the rest of the code dealing with `AbstractString`s was coded, could we just leave that as is for now, and I'll try to investigate it more thoroughly later?  (and then I could revamp the other places as well, all in other *small* PR)

**Comment by ScottPJones** [comment]
Oh, I didn't get a chance to test your version of `fast_utf_copy` yet (I always run my full tests on every change, no matter how small it looks, so it takes a while)... went out to dinner and crashed after!  I'll try to do that today, I haven't forgotten!

Since I had been told to squash before, I've been doing it religiously!  I see what you mean, and will now wait until somebody asks me to (hopefully before a Merge! :tada: )

About the convert methods... I'd almost prefer (for now), to leave them as is, and as I become a more proficient Julia programmer, try to merge them better later... (and have the time to do the thorough benchmarking to prove there are no performance regressions... would that be OK?

Thanks again for the assiduous reviewing!  You all deserve medals!

File: base/utfcheck.jl (hunk 11 above)
Comment (ScottPJones) [inline base/utfcheck.jl]: Hmm... or did you mean to change it do always do `ch, pos = next(dat, pos)`?
I'll take a quick look at the code generated in both cases... that would be great if it boiled down to the same code... :grinning:

Comment (tkelman) [inline base/utfcheck.jl]: I meant to always use `next`, since that's more general and should have the same meaning for simple vectors - and ideally generate nearly the same code

File: base/utfcheck.jl [hunk 12]
```diff
@@ -0,0 +1,187 @@
...
+        end
+    end
+    num3byte != 0 && (flags |= UTF_UNICODE3)
+    num4byte != 0 && (flags |= UTF_UNICODE4)
+    return totalchar, flags, num4byte, num3byte, num2byte
+end
+
+#=
+@doc """
+@brief      Validates and calculates number of characters in a UTF-16 encoded vector of UInt16
```
Comment (nalimilan) [inline base/utfcheck.jl]: Description is out of sync with code here.

File: base/utfconvert.jl (hunk 5 above)
Comment (ScottPJones) [inline base/utfconvert.jl]: It was here: https://groups.google.com/forum/#!topic/julia-dev/sM0VyVbFewQ

I don't understand either... and I think the `@doc/Markdown` stuff wasn't factored quite well enough when it was added to Base, but it sounds like the Docile version has been making a lot of changes that would make it much nicer in Base...

File: base/utfcheck.jl [hunk 13]
```diff
@@ -0,0 +1,187 @@
...
+
+const UTF_LONG = 1              # Long encodings are present
+const UTF_LATIN1 = 2            # characters in range 0x80-0xFF present
+const UTF_UNICODE2 = 4          # characters in range 0x100-0x7ff present
+const UTF_UNICODE3 = 8          # characters in range 0x800-0xd7ff, 0xe000-0xffff
+const UTF_UNICODE4 = 16         # non-BMP characters present
+const UTF_SURROGATE = 32        # surrogate pairs present
+
+# Get a UTF-8 continuation byte, give error if invalid, and update position and character value
+@inline function get_continuation(ch::UInt32, byt::UInt8, pos)
```
Comment (nalimilan) [inline base/utfcheck.jl]: This function doesn't look like it updates `pos` at all.

File: base/utfcheck.jl [hunk 14]
```diff
@@ -0,0 +1,187 @@
...
+@return     (total characters, flags, 4-byte, 3-byte, 2-byte)
+@throws     ArgumentError
+""" ->
+=#
+function check_string(dat::Vector{UInt8}, len::Int = sizeof(dat), pos::Int = 0 ; options::Integer=0)
+    local byt::UInt8, ch::UInt32, surr::UInt32
+    flags::UInt = 0
+    totalchar = num2byte = num3byte = num4byte = 0
+    @inbounds while pos < len
+        ch = dat[pos += 1]
```
Comment (nalimilan) [inline base/utfcheck.jl]: I'd prefer if you wrote `pos += 1` on the line before.

File: base/utfcheck.jl [hunk 15]
```diff
@@ -0,0 +1,187 @@
...
+        totalchar += 1
+        if ch > 0x7f
+            # Check UTF-8 encoding
+            if ch < 0xe0
+                # 2-byte UTF-8 sequence (i.e. characters 0x80-0x7ff)
+                (pos == len) && utf_errfunc(UTF_ERR_SHORT, pos, ch)
+                ch = get_continuation(ch & 0x3f, dat[pos += 1], pos)
```
Comment (nalimilan) [inline base/utfcheck.jl]: Looks like `get_continuation` would better return a tuple of `ch, pos`, since you apparently update it everytime you call that function. And instead of passing `dat[pos += 1]`, you could pass `dat` and leave the function extract the relevant element.

Comment (nalimilan) [inline base/utfcheck.jl]: Same story with `get_supplementary`.

**Comment by tkelman** [comment]
> Since I had been told to squash before, I've been doing it religiously! I see what you mean, and will now wait until somebody asks me to

It helps to do once in a while to clean things up (and before merging), as long as the review comments so far have been addressed. But github can be hard to predict sometimes, it's supposed to keep old comments in the PR thread collapsed under "Show outdated diff," but sometimes they vanish and you have to dig up the old sha to find them.

> I'd almost prefer (for now), to leave them as is

Not to be mean or anything, but of course you would? That's the minimal-work answer here. The convert methods still take up half the size of this PR, which is gradually improving relative to where #11004 left off, but hasn't been broken up into smaller easier to review pieces - which was the reason for closing the previous PR.

What would happen if we were to cut this in half (essentially as `@ihnorton` suggested towards the end of #11004). `utferror.jl` is small enough now that I think it can stay, and `utfcheck.jl` with its `check_string` methods will obviously be key functionality for many future changes here. Leave most of your refactorings to `utf16.jl` and `utf32.jl` but with the existing conversions in place for now. `utfconvert.jl` is just too long and too many methods to review along with the rest of the change all at once, I'm positive it can be done in a much more general and concise way without sacrificing performance. The first half would not directly be fixing anything, but it would be putting in place the necessary infrastructure to do so later, and would be smaller and easier to merge without worrying about breaking existing behavior.

File: base/utfcheck.jl (hunk 14 above)
Comment (nalimilan) [inline base/utfcheck.jl]: Ah, since you use that trick all over the place, and not only when calling `get_continuation`, I guess it would be too disruptive to change that.

Comment (ScottPJones) [inline base/utfcheck.jl]: I was just doing exactly what the code previously had done... most of the string processing code using that idiom...

File: base/utfcheck.jl (hunk 15 above)
Comment (ScottPJones) [inline base/utfcheck.jl]: They used to... let me play around with it... I'm still figuring out exactly what I can do in Julia without affecting performance, and this is all in very tight critical loops.

**Comment by ScottPJones** [comment]
>Not to be mean or anything, but of course you would? That's the minimal-work answer here. 

After all the work I've put into this, and other bug fixes for Julia, responding again and again to sometimes conflicting reviewer suggestions, you really want to accuse me of looking for a minimal-work approach?
:grinning: (I really don't take offense, but if you look at all I've done so far, how could you think that of me?)  It's simply a matter of available time in the next few weeks... if this doesn't get in (and the fixes I will do depending on the functionality), then I've got to set up where all the developers here only use my fixed julia repository... extra work I'd like to avoid.   I'd like to make those smaller, and in fact had smaller more "generic" versions along the line, but they performed terribly, so I'd like to be cautious and go with what I know works and performs well at the moment, and improve stuff later iteratively in small PRs.

Splitting things up doesn't seem like it would accomplish much at all...  `utfconvert.jl` is where the `utfcheck.jl` validations is called, so without `uftconvert.jl`, you have no better error messages, no bug fixes (and can't check in the better validation because of the way the unit-test system works :disappointed: , so why bother?
Existing behavior *is* broken.  That is what I am trying to fix.

**Comment by tkelman** [comment]
Please don't hold this hostage to merging the whole thing at once. That's not productive and has led to these bugs staying on master for longer then they've needed to. What would merging the infrastructure but not the actual fixes accomplish? For one thing we'd be able to backport bugfixes if the infrastructure is already present in 0.4.0 but not all the fixes make it in.

Getting all the convert methods right, maintainable, generic, performant, and avoiding repeated code is still going to require a lot of work. If we merge this as-is in one big chunk then it's quite likely it could need to be reverted all at once if it causes major issues in packages. That's why Stefan reverted the previous PR, it wasn't out of spite, it was trying to save you and the community time and frustration if we ended up merging a version of this that we don't really like but are tired of going back-and-forth on. A few of us were about to do that just to put an end to the 500-comment disaster of the previous PR.

**Comment by ScottPJones** [comment]
Well, I still say that closing the previous PR, before even saying just how he felt it needed to be split up, was not well done at all, when reviewers where still giving good suggestions, and I was actively responding to them...
You at least have tried to give suggestions as to what to do, without resorting what seems like an abuse of power to halt things.  There are ways and ways of doing things...  Your way has been much better
(and appreciated).

So, you are saying that just adding the utferror.jl, and utfcheck.jl, to set up the framework, *without* actually using them (because that is all done in utfcheck.jl), which wouldn't fix any bugs yet either, would help get this eventually in?

**Comment by tkelman** [comment]
> So, you are saying that just adding the utferror.jl, and utfcheck.jl, to set up the framework, without actually using them (because that is all done in utfcheck.jl), which wouldn't fix any bugs yet either, would help get this eventually in?

IMO yes. Others should speak up with their opinions too. It would be adding code that isn't directly used or tested at first (could we do some simple correctness tests just for the `check_string` function?), but it would separate concerns, because I think `utfcheck.jl` is getting very close to as good as that code will get for now. `utfconvert.jl` will need quite a bit more work I think, and it'll be easier to focus on if that were in a separate, smaller, followup PR. (At a bare minimum, it should absolutely be separate commits.)

**Comment by ScottPJones** [comment]
>For one thing we'd be able to backport bugfixes if the infrastructure is already present in 0.4.0 but not all the fixes make it in.

*This* is precisely what I was looking for, a *reason* for requesting extra work from me...
That makes sense, and I will try to do so... (at the moment, though, I'm trying to track down a very bad regression in performance :cry:, the UTF-16 -> UTF-32, UTF-32 -> UTF-8, and UTF-32 -> UTF-16 have all of the sudden got twice as slow [maybe not all of the issues with making the function generic have been addressed...])

**Comment by ScottPJones** [comment]
@tkelman The quicker somebody reviews and hopefully approves #11573, I can pull that out of this PR, and push another PR that is just the `check_string` stuff...

**Comment by ScottPJones** [comment]
I've changed this to WIP, until hopefully #11573 and #11575 get approved and merged, and I can change this to be based on those PRs, which contain some improvements to the same files here.
(If somebody could tell me how to change this so that it is branched off of `ScottPJones/julia` `spj/checkstring` (i.e. #11575), instead of `ScottPJones/julia` master, I could start cleaning this up already, or maybe I need to just wait until #11575 makes it in, if it does.

**Comment by pao** [comment]
Unfortunately, I don't believe there's a straightforward way to switch the PR branch. You can replace it using the GitHub API, and if you use the `hub` utility this is possible. Typically though, most people don't bother and just open a new cross-referenced PR.

**Comment by tkelman** [comment]
@pao I don't think that's what @ScottPJones meant, I think he meant to change the base of the commits within this PR. That would just be done by rebasing against a different branch than master.

**Comment by ScottPJones** [comment]
Yes, and it worked OK for #11575, so now if that's merged, I can rebase this one and push again. Thanks everybody!

**Comment by pao** [comment]
Ah, yeah, misunderstood. (Why do I triage before coffee?) Carry on.

**Comment by ScottPJones** [comment]
I have rebased this on #11575, so this should wait until that is hopefully merged in to pull the trigger on this.
I have split out the UTF-16 changes from the UTF-32 changes, so that this is a more manageable size.
Thanks everybody, I await your comments, good or bad!

File: base/utf16.jl [hunk 16]
```diff
@@ -1,9 +1,33 @@
 # This file is a part of Julia. License is MIT: http://julialang.org/license
 
-utf16_is_lead(c::UInt16) = (c & 0xfc00) == 0xd800
-utf16_is_trail(c::UInt16) = (c & 0xfc00) == 0xdc00
-utf16_is_surrogate(c::UInt16) = (c & 0xf800) == 0xd800
-utf16_get_supplementary(lead::UInt16, trail::UInt16) = Char(UInt32(lead-0xd7f7)<<10 + trail)
+# Quickly copy and set trailing \0
+@inline function fast_utf_copy{S <: Union(UTF16String, UTF32String), T <: Union(UInt16, Char)}(::Type{S}, ::Type{T}, len, dat, flag::Bool=false)
```
Comment (tkelman) [inline base/utf16.jl]: - this is mutating
- please break exceedingly long lines
- as asked before, can this use the 5-argument `copy!` in all cases, offsetting the length at the call site for the cases where required?

File: base/utf16.jl [hunk 17]
```diff
@@ -20,92 +44,254 @@ function endof(s::UTF16String)
...
+    @inbounds for i = 1:n-1
+        ch = d[n-i]
+        if is_surrogate_lead(ch)
+            out[i],out[i-1] = out[i-1],ch
+        else
+            out[i] = ch
         end
     end
-    return UTF16String(out)
+    UTF16String(out)
```
Comment (tkelman) [inline base/utf16.jl]: leave the `return`

File: base/utf16.jl [hunk 18]
```diff
@@ -20,92 +44,254 @@ function endof(s::UTF16String)
...
+            # output surrogate pair
+            buf[out += 1] = UInt16(0xd7c0 + (ch >>> 10))
+            buf[out += 1] = UInt16(0xdc00 + (ch & 0x3ff))
         end
     end
-    return i > n || !utf16_is_surrogate(data[i])
+    UTF16String(buf)
+end
+
+function convert(::Type{UTF8String}, dat::Vector{UInt16})
```
Comment (tkelman) [inline base/utf16.jl]: Do you really need to add convert methods from vectors of integers to string types? That seems like only the constructor should ever be doing that.

Comment (ScottPJones) [inline base/utf16.jl]: Vectors of characters is how people have to deal with mutable strings in Julia, of course you need this. Anyway, I didn't add that capability, taking vectors of integers was already there in utf16.jl before any of my changes.

File: base/utf16.jl (hunk 17 above)
Comment (ScottPJones) [inline base/utf16.jl]: That's not the convention in the surrounding code, and the code before any of my changes.

File: base/utf16.jl (hunk 18 above)
Comment (vtjnash) [inline base/utf16.jl]: that doesn't necessarily explain why you need to convert from `Vector{UInt16}` to `UTF8String`, but only why it makes sense to create a `UTF16String` from a `Vector{UInt16}`

Comment (ScottPJones) [inline base/utf16.jl]: You need to be consistent.  Converting from UTF-16 or UTF-32 to UTF-8 is a critical function, and you need to be able to do it whether you are getting it from a `Vector{UInt16}`, or whatever.

**Comment by ScottPJones** [comment]
This has now been updated, comments before function, no 4-space indent for brief description.

File: base/utf16.jl (hunk 18 above)
Comment (tkelman) [inline base/utf16.jl]: String aren't mutable in base Julia. If conversions between different encodings from vectors of integers to strings aren't in base now, we're not adding them here.

File: base/utf16.jl (hunk 16 above)
Comment (ScottPJones) [inline base/utf16.jl]: I haven't had time to test it with changing to use 5-argument copy!, I'll try to do that this afternoon.

Comment (tkelman) [inline base/utf16.jl]: I think it would still need the flag to distinguish whether or not you need an offset, the main benefit would be if both cases can use the same 5-argument copy instead of needing to switch code depending on `flag`

File: base/utf16.jl (hunk 17 above)
Comment (tkelman) [inline base/utf16.jl]: It shows up as a diff, of you deleting the `return` from this line, which is unnecessary.

Comment (ScottPJones) [inline base/utf16.jl]: That was just making it more consistent with most all of the other locations in the utf*.jl files.

File: base/utf16.jl (hunk 16 above)
Comment (ScottPJones) [inline base/utf16.jl]: And you've tested to see that that actually can generate the same code?  That's why I haven't done that change yet, I want to determine if it would affect anything.

File: base/utf16.jl (hunk 2 above)
Comment (tkelman) [inline base/utf16.jl]: can this now use `fast_utf_copy` ?

**Comment by ScottPJones** [comment]
Updated again, including changes from #11575 (and base)

File: base/utf16.jl [hunk 19]
```diff
@@ -20,92 +45,248 @@ function endof(s::UTF16String)
...
+*   ::Type{UTF8String}
+*   dat::Vector{UInt16}
+
+### Returns:
+*   UTF8String
+
+### Throws:
+*   UnicodeError
+"
+function convert(::Type{UTF8String}, dat::Vector{UInt16})
```
Comment (tkelman) [inline base/utf16.jl]: Isn't this method redundant with calling `convert(UTF8String, UTF16String(dat))` ?

Comment (ScottPJones) [inline base/utf16.jl]: No, unfortunately not.  This is why I was complaining about the inconsistencies in the Julia string types:
`ASCIIString` and `UTF8String` have implicit `\0`s, but `UTF16String` and `UTF32String` have to have
*explicit* `\0` words added (There is also the inconsistency that `UTF32String`'s elements are `Char`,
but the rest have `UInt8` or `UInt16` elements).  I believe there are currently bugs related to those inconsistencies...
hopefully I'll have time to investigate/fix those later.

Comment (tkelman) [inline base/utf16.jl]: Wouldn't the conversion from UTF16String into UTF8String have to take that into account? Would this just be slower, or incorrect?

In the long term it would be good to resolve these inconsistencies. In the short term, I don't think we should implement any conversions between integer/char vectors and string types, other than for the matching-size case which the string constructor would use.

Comment (ScottPJones) [inline base/utf16.jl]: That is why the setup code is different.  When you have a `Vector{UInt16}` that needs to be converted, there is no explicit `\0` word, so you check for sizeof(dat) to be 0 to see if it is empty,
but when you have a UTF16String, there must be an explicit `\0` which you have to account for.

The integer/char vectors to/from string type conversions are actually some of the most useful of the conversions, because you need them when taking data from a database record, or something passed in via ZMQ, for example.
I think @quinnj 's `String` package so far is the best path I've seen to removing these inconsistencies, and also making some of the conversions less necessary.
Another issue is that some of these conversions using integer/char vectors are already part of Base, so removing them might break packages... (I'm trying to determine what string functionality is actually in use, at least in Base itself or in the registered packages).
For example, would anyone object to a PR removing `RopeString`?

Comment (tkelman) [inline base/utf16.jl]: `RopeString` might be a candidate for moving to a package during 0.5-dev. Not right now.

Please answer the question, "would this just be slower, or incorrect?" The fact that doing a dedicated special-purpose routine for this particular conversion is only a slight modification of otherwise repeated code is one of the big objections here. As far as what might be in scope before 0.4, let's prioritize modifying the existing code to be correct first, maximally generic/minimally verbose second, and performant third.

Comment (ScottPJones) [inline base/utf16.jl]: Why do you want to keep `RopeString`, when it isn't used in Base or any registered package?
I wouldn't even move it to a package, I'd simply remove it.

What are you referring to, when you say "would this just be slower, or incorrect?"  The current conversions are incorrect, and these conversions fix those bugs.  Also, why is having something maximally generic more important than having the functions performant enough to be useful?  Other reviewers have agreed that the performance is more important than having the code "maximally generic" (back during the #11004 discussions).

Comment (tkelman) [inline base/utf16.jl]: Are you absolutely positive RopeString is completely unused across every single package, and all possibly private code? It might be, but I'd want to verify that first, and at least provide a working place to get the same code outside of base before removing it completely.

And other reviewers have asked, would getting rid of mostly-repeated specialized methods by using simpler one-liners actually make a substantial difference for performance? There's still too much code here.

**Comment by ScottPJones** [comment]
I have downloaded every registered package.  I grep'ed for `RopeString` in every single file ending in `.jl`
Not a single occurrence.

I haven't seen any examples of simple one-liners that are actually correct.
If you have an example in mind, please show it.
I've already shown by my micro-benchmarks that there is a substantial difference in performance as well.
I'm not sure why you think there is "too much code".  There is enough code to perform the conversions correctly, and, as a side effect, much faster than before.
These conversions are also heavily used, for example, for the Windows APIs...

File: base/utf16.jl [hunk 20]
```diff
@@ -20,92 +45,248 @@ function endof(s::UTF16String)
...
+        elseif is_surrogate_codeunit(data[i])
+            return false
+        else
+            i += 1
+        end
+    end
+    return i > n || !is_surrogate_codeunit(data[i])
+end
+
+"
```
Comment (vtjnash) [inline base/utf16.jl]: i dislike this particular comment on the sole grounds that it provides no additional information in 14 lines that was not provided by the subsequent one line of code (`function convert(::Type{UTF16String}, str::AbstractString)`)

i agree that base could use more frequent comments (and generally appreciate the inline comments you've put in this PR), but let's not write text just for the sake of writing text.

File: base/utf16.jl (hunk 19 above)
Comment (vtjnash) [inline base/utf16.jl]: i don't see this method in the current list of methods: 
```julia
julia> convert(UTF8String,UInt16[])
ERROR: MethodError: `convert` has no method matching convert(::Type{UTF8String}, ::Array{UInt16,1})
```
therefore it should getting added amidst this PR.

But, from what I can tell, none of the existing methods accept a data in one format and output it in a different format. they are all either String -> String conversions (no interpretation) or Byte -> String interpretation (no conversion).
```julia
julia> convert(UTF8String,\t
convert(::Type{UTF8String}, s::UTF8String) at utf8.jl:215
convert(::Type{UTF8String}, s::ASCIIString) at utf8.jl:216
convert(::Type{UTF8String}, a::Array{UInt8,1}) at utf8.jl:217
convert(::Type{UTF8String}, a::Array{UInt8,1}, invalids_as::AbstractString) at utf8.jl:219
convert(::Type{UTF8String}, s::UTF16String) at utf16.jl:81
convert(::Type{UTF8String}, s::AbstractString) at utf8.jl:239
convert{T<:Union(UTF8String,ASCIIString)}(::Type{T<:Union(UTF8String,ASCIIString)}, data::AbstractArray{Char,1}) at utf32.jl:35
convert{T<:AbstractString}(::Type{T<:AbstractString}, v::AbstractArray{Char,1}) at utf32.jl:31
convert{S<:AbstractString}(::Type{S<:AbstractString}, g::Base.UTF8proc.GraphemeIterator{S<:AbstractString}) at utf8proc.jl:232
convert{T}(::Type{T}, x::T) at essentials.jl:57
julia> convert(UTF8String,
```
so i don't see the value in adding this special case at all. At a minimum, this would be inconsistent. But, it also seems incorrect to me as well, since this particular method is trying to do both interpretation (of UInt16 bytes as a UTF16 native-endian string) and conversion (to UTF8), and then ends up not doing either in a particularly well-defined manner.

> Also, why is having something maximally generic more important than having the functions performant enough to be useful? Other reviewers have agreed that the performance is more important than having the code "maximally generic" (back during the #11004 discussions)

there's a big difference between writing an optimized kernel to hand-optimize certain functions vs. duplicating code in an attempt to subvert the abstraction layer. It is sometimes acceptable to define a hand-optimized method (like `convert(::UTF8String, ::UTF16String)`, rather than always falling back on `convert(::UTF8String, ::AbstractString)`), where the behavior is the same, but optimized in ways that would have been too costly for a compiler to determine.

(breadcrumb: mentioned this issue previously in https://github.com/JuliaLang/julia/pull/11004#discussion_r31568679, but perhaps not quite as clearly)

File: base/utf16.jl [hunk 21]
```diff
@@ -20,92 +45,248 @@ function endof(s::UTF16String)
...
+Converts an already validated vector of UInt16 or UInt32 to a UTF8String
+
+### Input Arguments:
+*    dat         Vector{T}
+*    len         length of output in bytes
+
+### Returns:
+*   UTF8String
+"
+function encode_to_utf8{T<:Union(UInt16, UInt32)}(::Type{T}, dat, len)
```
Comment (vtjnash) [inline base/utf16.jl]: can the `T` parameter be dropped now?

**Comment by vtjnash** [comment]
> These conversions are also heavily used, for example, for the Windows APIs...

but not exactly high-performance APIs, so why does this matter? https://github.com/JuliaLang/julia/pull/11004#issuecomment-96307824

> I have downloaded every registered package. I grep'ed for RopeString ...

OT

> I haven't seen any examples of simple one-liners that are actually correct.
If you have an example in mind, please show it.

I think the most generic String -> String conversion method would look something like:
```julia
function convert{T<:AbstractString}(::Type{T}, str::AbstractString)
    dat = string_builder(T, check_string(str)...)
    for c in str
        push!(dat, c)
    end
    return finalize(dat)
end
```
where `string_builder` would return a thin wrapper around an output array and a position pointer (using the return values of `check_string` to optimize the result), `push!` would add the character `c` at the current position, and `finalize` would append the final `\0` byte and return the newly constructed string object. this should be fully correct (and is effectively what IOBuffer implements), but is also notably slower, since the compiler has no real hope of doing all of the inlining necessary to unroll this.
but something like this also helps to cut down on the N^2 number of conversion methods necessary to hand-write if you want to be able to go directly from any format to any other format. if you squint a bit, i think all of your methods follow this pattern already.

thus, once you do all that inlining, it's less obvious why `function convert(::Type{UTF16String}, str::UTF8String)` https://github.com/JuliaLang/julia/pull/11551/files#diff-c77c77957abcbf5ff43edad984ad701dR148 is needed when you have `function convert(::Type{UTF16String}, str::AbstractString)` https://github.com/JuliaLang/julia/pull/11551/files#diff-c77c77957abcbf5ff43edad984ad701dR117 with nearly the same code (but a lot shorter). i still would expect this hand optimized version to be faster however, since it is able to fuse the conditionals for reading and writing the data into a single `if`-statement. thus it seems reasonable that this may be a method where some code duplication is warranted.

File: base/utf16.jl (hunk 21 above)
Comment (ScottPJones) [inline base/utf16.jl]: Why?  That's needed so that it can be used both in this PR, and in the PR to fix the bugs with UTF-32 handling.

File: base/utf16.jl (hunk 20 above)
Comment (ScottPJones) [inline base/utf16.jl]: That's not true, it gives both the return type of the function, and lists what errors are thrown.
That information is not present on the first line of the function.
The idea was to have that information also available to  the help system, and to things like Doxygen.
If you could list the exceptions thrown by a function, like in CLU, and had a way of specifying the return type
(which has been proposed), that would not be necessary.

**Comment by ScottPJones** [comment]
N^2?  I'm talking about 6 total, including UTF32, which is not in this PR, not 9, and I'm not at all saying that any other encodings outside of UTF8, UTF16, UTF32 would need direct conversions.
The old `utf16.jl` had 10 `convert` methods, and 1 helper function `encode16` (which was only called from one place).  Two of those methods were marked `#TODO optimize this`, which this PR does.
This new `utf16.jl` has 14 `convert` methods, removes `encode16`, and adds `encode_to_utf8`, used twice here, and which is also used by the new `utf32.jl`, so I don't see that there is really all that much code duplication.
These conversions are the ones that are needed to interface to the OS (Windows API calls, Unix/Linux/OS X with wchar_t), to C/C++ libraries (ICU), to databases... @mbauman already showed how, in a simple "real-world" test, 97% of the time was spent in the conversion code...

File: base/utf16.jl (hunk 20 above)
Comment (nalimilan) [inline base/utf16.jl]: Right, but all information which is provided by the signature should not be repeated in the comment. The doc system should be smart enough to extract that automatically. (I think I said that in another comment already.)

File: base/utf16.jl (hunk 19 above)
Comment (ScottPJones) [inline base/utf16.jl]: Please take a look at @quinnj 's new `Strings.jl` package, in particular at `Encodings.jl`
(esp. the version in my PR for `Strings.jl`).
That is really how I believe strings should be handled.
The current design of strings in Julia conflates the storage representation (i.e. bytes, 16-bit words, 32-bit words), with both the character set (ASCII vs. Unicode), and how those are logically encoded (i.e. UTF8 vs. UTF16 vs. UTF32).  It also mixes in `\0` termination (and not in a consistent fashion), which ends up causing some of what you've seen as code duplication (necessary to handle those inconsistencies).

This isn't "subverting" the abstraction layer, since this is the module that *implements* that abstraction layer.  If you want real examples of subverting the abstraction layer, I have many,
in `datafmt.jl`, `expr.jl`, `LineEdit.jl`, `pointer.jl`, `printf.jl`, `regex.jl`, `REPL.jl`, and `string.jl`, and those are just in Base...

**Comment by ScottPJones** [comment]
@vtjnash You still haven't shown a "one-liner", that is 7 lines of code, exactly the same as the extra `convert` function that was being discussed, and that's not even counting the extra functions you'd have to add `string_builder` and `finalize` (which wouldn't even work generically, because of the inconsistencies of how `'\0'` is handled currently).  Also, using `push!` to build up a vector is rather slow.
Part of what makes my convert code faster is that I avoid that, by allocating the vector with the correct size right at the start, and then being able to use simple assignments without bounds checking.

File: base/utf16.jl (hunk 20 above)
Comment (ScottPJones) [inline base/utf16.jl]: Please go look at the latest version - there is information there that could not be extracted from the signature.

Comment (ScottPJones) [inline base/utf16.jl]: And yes, you are correct, and I totally agree, that if the information *is* provided by the signature, it doesn't need to be repeated.  The signature also does not indicate whether a parameter is used for input, output, or both, something that my original doxygen format comments made nicely explicit, with `@param[in]`, `@param[out]`, and `@param[in,out]`.
I'd redone the comments in #11575, but hadn't gone back to update these PRs, while waiting for some resolution on #11575.

Comment (nalimilan) [inline base/utf16.jl]: That's better, but if you think in terms of how the docs will be presented when they will be supported in Base, the generic `convert` function will already have its description printed, so you don't need to explain what the first argument means (and it's quite weird to describe an argument which is fixed to `UTF16String`). As for documenting `str`, the only interesting point is that `\0` is not needed, but I don't think this should be explained here: people using that function should not care about the underlying representation of their string, as they are using the high-level interface.

The rest of the doc looks fine to me.

Comment (ScottPJones) [inline base/utf16.jl]: About the comment on `'\0'`, that was to contrast it with the other functions, such as UTF16String(),
which *requires* an explicit `'\0'`.   I'll just go remove the Input Arguments sections though...

Comment (nalimilan) [inline base/utf16.jl]: Yeah, but `UTF16String` operates on raw data, where the caller needs to know low-level interpretation details.

Comment (ScottPJones) [inline base/utf16.jl]: Unfortunately, the lines between `UTF16String()`, `convert`, and `utf16` have not been all that well drawn, in that many of the `convert` functions also work on raw data... I hope that this can all be cleaned up... possibly with @quinnj's `String.jl` package...

File: base/utf16.jl (hunk 19 above)
Comment (ScottPJones) [inline base/utf16.jl]: >Are you absolutely positive RopeString is completely unused across every single package, and all possibly private code?

Of course there is no way to know if something is used in private code... why even bring that up?

There are changes being merged every day that probably break things in private code, and ones like eliminating `start_timer`/`stop_timer` that definitely are in 9 different registered packages...
(Those might get caught by deprecated, but I doubt having messages pop up when using `PyCall` for example, would be good).
It seems inconsistent, that such care is taken about trying to remove something that apparently is never used, while not wanting to add code that would be heavily used.

Comment (tkelman) [inline base/utf16.jl]: Breaking changes happen on master, that's inevitable. But if you're going to remove code wholesale, is it really that hard to be thorough about it and move same functionality outside of base as a package? It should take maybe half an hour's work to do.

File: base/utf16.jl (hunk 21 above)
Comment (tkelman) [inline base/utf16.jl]: UTF-32 handling is dealt with in a separate PR, so extending this method to a parametric union belongs there.

**Comment by tkelman** [comment]
> Also, using push! to build up a vector is rather slow.
Part of what makes my convert code faster is that I avoid that, by allocating the vector with the correct size right at the start

ref `sizehint!`

What @vtjnash's sketch accomplishes that your code doesn't is it gives a unified pattern for all conversions that only needs to be expressed generically once, then the small differences between different variations can be captured by dispatch in the separately factored individual operations.

> I don't see that there is really all that much code duplication.

Not exact duplication, but multiple different implementations, slightly different from one another, but all unrolled and customized. We're suggesting that these aren't all needed - there's one pattern that is being repeated a few too many times, and I'm sure every different combination is not absolutely required to improve performance of the few commonly occurring conversion directions.

We've asked for a while now, if this PR is to be taken as a bug fix, what is the minimum amount of code that can accomplish that. We're not convinced this is anywhere near that minimum as currently written.

File: base/utf16.jl (hunk 19 above)
Comment (ScottPJones) [inline base/utf16.jl]: Remember,  I'm still fairly new using git and GitHub (2 months), it might take *you* only an half hour to move something from base to a package, but I've never made a package so far.  If you really think somebody might be using it in their private code, I'm happy to learn how to create a package, figure out how to set up its own unit tests etc., It's stuff I need to learn anyway.
Any pointers would be greatly appreciated, as always!

File: base/utf16.jl [hunk 22]
```diff
@@ -20,100 +45,240 @@ function endof(s::UTF16String)
...
+"
+Converts a UTF-16 encoded vector of `UInt16` to a `UTF8String`
+
+### Returns:
+*   `UTF8String`
+
+### Throws:
+*   `UnicodeError`
+"
+function convert(::Type{UTF8String}, dat::Vector{UInt16})
```
Comment (vtjnash) [inline base/utf16.jl]: i still think this method definition should not be added (https://github.com/JuliaLang/julia/pull/11551#discussion_r32376121)

Comment (ScottPJones) [inline base/utf16.jl]: @tkelman @vtjnash hasn't provided code that works, or is generic.  The "sketch" just tries to hide complexity behind "string_builder" and "finalize", and it wouldn't even work for anything but `UTF32String` (where does it output 1-4 code units for UTF-8 encoding, or surrogate pairs for UTF-16 encoding?).  I know about `sizehint!`, but I think `push!` still has a lot more overhead than something like `buf[pos += 1] = ch`, even with `sizehint!` done beforehand.

I'll explain tomorrow why the conversions from `Vector{UInt16}` are so important for anybody dealing with Java, C++, libraries like ICU, database access... past my bedtime now!

Comment (tkelman) [inline base/utf16.jl]: You don't need to explain it, we get the message. We're telling you to please not add conversions between vectors of integers and non-matching string types to base. None of "dealing with Java, C++, libraries like ICU, database access" are mandatory base-language functionality right now. Construction of and basic conversion between these string types are, and this PR needs to focus on fixing bugs instead of adding new methods.

Aside from the differences in whether or not there's an explicit trailing 0, how is `convert(::Type{UTF8String}, dat::Vector{UInt16})` absolutely mandatory when you can do `convert(UTF8String, UTF16String(dat))`? It seems like an unnecessary shortcut method to skip a pass, or avoid boundary issues with current trailing-null inconsistencies, and would be better-suited to remain in your own code than being added to base.

Comment (ScottPJones) [inline base/utf16.jl]: You are arguing about a single method, which is important to fix consistency problems also with the conversion methods (i.e. if there are `Vector{UInt8} -> UTF16String`, `Vector{UInt16} -> UTF16String` conversions, why isn't there a corresponding `Vector{UInt16} -> UTF8String` method?)  It is only 5 lines of code (only 1 of which is the same as the `UTF16String -> UTF8String` method), and adds only 1206 bytes to sys.dylib.

Your example `convert(UTF8String, UTF16String(dat))` won't even work for any of the places where you want to do a conversion, because pretty much none of the code outside of Julia is going to have the trailing `\0`, and you'll just get a "UTF16String data must be NULL-terminated" error.
That is why it is absolutely mandatory, to eliminate the current inconsistency in methods, and to actually allow people to use it.

I think that basic functionality that is useful for most all user code and packages that deal with a feature, such as string processing in this case, should definitely be in base, it prevents people from having to reinvent the wheel (possibly incorrectly) all over the place.

BTW, removing `RopeStrings`, which nobody is using, at least in any registered package, adds 4784 bytes to `sys.dylib`, whereas this PR only adds 3320.

Comment (vtjnash) [inline base/utf16.jl]: > You are arguing about a single method, which is important to fix consistency problems also with the conversion methods (i.e. if there are Vector{UInt8} -> UTF16String, Vector{UInt16} -> UTF16String conversions, why isn't there a corresponding Vector{UInt16} -> UTF8String method?)

exactly, this method is inconsistent with the behavior of the Vector{UInt8} -> String class of functions (which \*interpret\* a bytestream as the given string type and do not perform any conversion)

> BTW, removing RopeStrings, which nobody is using, at least in any registered package, adds 4784 bytes to sys.dylib, whereas this PR only adds 3320.

please stay on topic

> Your example convert(UTF8String, UTF16String(dat)) won't even work for any of the places where you want to do a conversion, because pretty much none of the code outside of Julia is going to have the trailing \0, and you'll just get a "UTF16String data must be NULL-terminated" error.

if the data isn't null terminated, then the current convention is to use the lowercase (`utf16`) conversion function, which also ensure the data is copied to avoid assorted data aliasing issues. the direct constructor was intended for use when the user has data that is known, a priori, to already be a valid UTF16 string and just needs to add the type tag.

Comment (ScottPJones) [inline base/utf16.jl]: >exactly, this method is inconsistent with the behavior of the Vector{UInt8} -> String class of functions (which *interpret* a bytestream as the given string type and do not perform any *conversion*)

That's a whole other mess, which I've already filed two issues about... the methods for UTF8, UTF16, and UTF32 are all inconsistent, and don't correctly detect BOMs.
I'm *trying* to work through all of the inconsistencies present in the code.

>if the data isn't null terminated, then the current convention is to use the lowercase (utf16) conversion function, which also ensure the data is copied to avoid assorted data aliasing issues. 

The `utf8`, `utf16`, and `utf32` functions are also inconsistent, and do you *really* want to force strings to be copied twice, just because of having to deal with a trailing `\0` byte?
That doesn't sound very good to me at all.

Comment (ScottPJones) [inline base/utf16.jl]: About the direct constructors, @tkelman brought up using the direct constructor, but those are also horribly inconsistent... `ASCIIString` and `UTF8String` want just the data, but `UTF16String` and `UTF32String` require the last word to be an explicit `\0`.  If it weren't for that, there would be no need for an extra method so that people could do conversions without lots of extra copying.

Comment (nalimilan) [inline base/utf16.jl]: How about fixing these methods, instead of adding different ones?

Comment (ScottPJones) [inline base/utf16.jl]: @nalimilan I'm *trying* to get stuff fixed, but Rome wasn't built in a day! :grinning:
I've also been told to make small PRs, not to lump everything in to one...
The `utf*` functions will be fixed, in large part, by *having* the new convert methods such as this one, that don't require extra copies, and which do correct validation, that they can use.
If this goes in, then I'll be able to do another PR fixing the issues with `utf*`.

File: base/utf16.jl [hunk 23]
```diff
@@ -20,100 +45,240 @@ function endof(s::UTF16String)
...
 convert(T::Type{UTF16String}, data::AbstractArray{UInt16}) =
     convert(T, reshape(data, length(data)))
 
 convert(T::Type{UTF16String}, data::AbstractArray{Int16}) =
     convert(T, reinterpret(UInt16, data))
 
+function convert(::Type{UTF16String}, data::AbstractVector{UInt16})
+    !isvalid(UTF16String, data) && throw(UnicodeError(UTF_ERR_INVALID_16,0,0))
+    len = length(data)
+    @inbounds return UTF16String(setindex!(copy!(Vector{UInt16}(len+1),1,data,1,len),0,len+1))
```
Comment (tkelman) [inline base/utf16.jl]: deja vu since I feel like I've said this 2 or 3 times already, but should this line be using `fast_utf_copy` ?

File: base/utf16.jl [hunk 24]
```diff
@@ -20,100 +45,240 @@ function endof(s::UTF16String)
...
-    UTF16String(copy!(d,1, data,1, len))
+function convert(::Type{UTF16String}, str::ASCIIString)
+    dat = str.data
+    @inbounds return fast_utf_copy(UTF16String, UInt16, length(dat), dat, true)
 end
 
+convert(::Type{Vector{UInt16}}, str::UTF16String) = str.data
+convert(::Type{Array{UInt16}},  str::UTF16String) = str.data
+
+convert(::Type{UTF16String}, str::UTF16String)    = str
```
Comment (tkelman) [inline base/utf16.jl]: Is this needed?

File: base/utf16.jl (hunk 23 above)
Comment (ScottPJones) [inline base/utf16.jl]: I hope I didn't mess anything up with the rebasing to master!  I'll check that out, thanks.

File: base/utf16.jl (hunk 24 above)
Comment (ScottPJones) [inline base/utf16.jl]: I believe that was there before - I'm pretty sure all I did was change s -> str.

Comment (tkelman) [inline base/utf16.jl]: You're right, just wasn't showing up very clearly in the diff. Seems like a vacuous definition though.

Comment (ScottPJones) [inline base/utf16.jl]: I wondered about those myself, but `ASCIIString`, `UTF8String` and `UTF32String` all have the same definition... (I'll probably make them all just have one parameterized definition in another cleanup PR later)

Comment (ScottPJones) [inline base/utf16.jl]: One thought just came to me... since strings are not (currently :grinning:) validated, maybe those `convert`s should actually do the validity checking that the other `convert` methods normally do...
I think for consistency's sake, that needs to happen, but I'd have to be very careful about seeing where `convert` might be called with the same type... don't want to kill performance!

File: base/utf16.jl (hunk 22 above)
Comment (nalimilan) [inline base/utf16.jl]: I wasn't implying you didn't work to improve this. But you said that the new functions are needed because the direct constructors are broken.Thus I suggest fixing them, instead of adding functions not to use it. Or maybe I'm missing the point.

File: base/utf16.jl (hunk 24 above)
Comment (nalimilan) [inline base/utf16.jl]: At least these definitions are not needed as currently written:
````
julia> @which convert(Int, 1)
convert{T}(::Type{T}, x::T) at essentials.jl:57
```

Which is defined as:
```
convert{T}(::Type{T}, x::T) = x
```

Given this general definition, I'm not sure doing a validation for strings is a good idea. It could create an unexpected performance hit in some cases where a conversion is performed "just in case". Better use `isvalid` explicitly.

Comment (ScottPJones) [inline base/utf16.jl]: @nalimilan Let me explain about the 3 types of functions:

  * The constructors: `ASCIIString`, `UTF8String`, `UTF16String`, `UTF32String`.
    These are totally unsafe, and really should not be used in user code.  They do no validation
    (except for the stupid, inconsistent, insistence of `UTF16String` and `UTF32String` to have a `0`
    word after the real data).  They build a string that directly uses the `Vector` passed in (see #11391, where there was another inconsistency that I fixed earlier).
     In another PR, I'd like to make the unsafe behavior harder to reach, with maybe a Val argument that must be true, to get the unsafe current behavior, which is currently needed for the conversions)

  * The convert methods.  These are very inconsistent, and even after this set of PRs, there are still more bugs that need to be addressed (a couple of them are #11501, #11502, but there are still a lot more to work through :disappointed: )  As I said before, the `convert{T}(::Type{T}, x::T) = x` really should be doing validation/conversion, but that could be expensive, unless we make sure that all strings are validated (which will help performance, because other operations don't need to worry about bad data, and improve security as well).   The conversion methods are all I'm trying to fix in these PRs.

 *  The `ascii`, `utf8`, `utf16`, and `utf32` convenience functions.
     These are, for the most part, simply wrappers around doing a `convert(::T, ....)`, except that they also add loading from a `Ptr{}`, both `\0` terminated and counted.

@tkelman I hadn't done the `AbstractVector{UInt16}` method before, because I hadn't touched any of the `AbstractArray` and `AbstractVector` methods that were already there...  I've gone ahead and fixed it now, since you raised the question, I just hope Stefan doesn't come down on me for doing more than one thing in a PR! :grinning:

**Comment by ScottPJones** [comment]
Are these bug fixes good to go now?  Thanks!

File: base/utf16.jl (hunk 24 above)
Comment (ScottPJones) [inline base/utf16.jl]: >Better use isvalid explicitly.

@nalimilan The string conversion functions (except for some bugs) all have the contract that they validate the string.  However, `isvalid` is simply too strict to be useful in very many cases.
One of the fixes with this PR was to change to using `unsafe_checkstring`, which allows handling
`Modified UTF-8` and `CESU-8`.  Another PR will need to deal with the inconsistency that there is a `convert` method for UTF-8 that allows passing a replacement character or string for when invalid sequences are found, instead of throwing an error, but not for ASCII, UTF-16, or UTF-32...

**Comment by tkelman** [comment]
Not while there's still a `convert(::Type{UTF8String}, dat::Vector{UInt16})` method in this PR.

File: base/utf16.jl (hunk 24 above)
Comment (tkelman) [inline base/utf16.jl]: I think the only behavior that makes sense for `convert` of a value into its own type is to be a no-op. Constructors could be given additional `UTF16String(str::UTF16String)` methods for validation if you're really paranoid about converting a string from somewhere else that hasn't been validated into its own type.

Comment (ScottPJones) [inline base/utf16.jl]: It's not paranoia, it's just that since the type constructors do not guarantee a valid string (in fact, they basically let you get away with anything... because they take `Vector`s of raw code units, so that you can keep an alias... there is no guarantee even that a string is really immutable...)

Comment (ScottPJones) [inline base/utf16.jl]: Maybe the only way to solve this, is to move all validation/conversion into the inner constructors... which would also eliminate the hole of making a mutable string...
But, that's not for this PR, but another...

**Comment by ScottPJones** [comment]
OK, anything else?

**Comment by ScottPJones** [comment]
@tkelman This is now also rebased (because of changes to `test/strings` from other merges), all issues addressed.

**Comment by ScottPJones** [comment]
The unit tests on AppVeyor actually passed, and then it exited with a 3... not sure what's broken on AppVeyor, but it doesn't seem related to my change at all.

**Comment by nalimilan** [comment]
I've restarted it.

**Comment by tkelman** [comment]
Don't restart appveyor jobs that fail in that way until #11807 gets fixed

**Comment by ScottPJones** [comment]
That bit #11810 also

File: base/utf16.jl [hunk 25]
```diff
@@ -1,9 +1,34 @@
 # This file is a part of Julia. License is MIT: http://julialang.org/license
 
-utf16_is_lead(c::UInt16) = (c & 0xfc00) == 0xd800
-utf16_is_trail(c::UInt16) = (c & 0xfc00) == 0xdc00
-utf16_is_surrogate(c::UInt16) = (c & 0xf800) == 0xd800
-utf16_get_supplementary(lead::UInt16, trail::UInt16) = Char(UInt32(lead-0xd7f7)<<10 + trail)
+# Quickly copy and set trailing \0
+@inline function fast_utf_copy{S <: Union{UTF16String, UTF32String}, T <: Union{UInt16, Char}}(
```
Comment (stevengj) [inline base/utf16.jl]: What's the purpose of the `flag` argument, since you always seem to pass `true`?

File: base/utf16.jl [hunk 26]
```diff
@@ -20,100 +45,220 @@ function endof(s::UTF16String)
...
+Converts an already validated vector of `UInt16` or `UInt32` to a `UTF8String`
+
+### Input Arguments:
+* `dat` Vector of code units (`UInt16` or `UInt32`), explicit `\0` is not converted
+* `len` length of output in bytes
+
+### Returns:
+* `UTF8String`
+"
+function encode_to_utf8{T<:Union{UInt16, UInt32}}(::Type{T}, dat, len)
```
Comment (stevengj) [inline base/utf16.jl]: Why not just `encode_to_utf8{T<:Union{UInt16, UInt32}}(dat::AbstractVector{T}, len)`, rather than redundantly passing `T` ... isn't `dat` always going to be some kind of vector of `T`?

File: base/utf16.jl (hunk 24 above)
Comment (stevengj) [inline base/utf16.jl]: Note that there is already a [generic convert definition](https://github.com/JuliaLang/julia/blob/master/base/essentials.jl#L59) for `convert{T}(::Type{T}, x::T) = x`, so we don't need to duplicate that for specific types `T`.

File: base/utf16.jl [hunk 27]
```diff
@@ -136,6 +281,9 @@ function convert(T::Type{UTF16String}, bytes::AbstractArray{UInt8})
     UTF16String(d)
 end
 
+convert(::Type{UTF16String}, str::UTF16String)    = str
```
Comment (stevengj) [inline base/utf16.jl]: also redundant with https://github.com/JuliaLang/julia/blob/master/base/essentials.jl#L59

File: base/utf16.jl (hunk 25 above)
Comment (ScottPJones) [inline base/utf16.jl]: That was for the conversion that @tkelman absolutely did not want in the PR (which is probably the most useful one for me), conversion of `Vector{UInt16}` to UTF8String.

File: base/utf16.jl (hunk 26 above)
Comment (ScottPJones) [inline base/utf16.jl]: That was more for the future, where I want the first argument to really be an Encoding, see @quinnj's nice Strings.jl that he's been working on.

File: base/utf16.jl (hunk 27 above)
Comment (ScottPJones) [inline base/utf16.jl]: Yes, but this was about fixing bugs, not removing stuff, I was told many times not to do too many things in a single PR, so I was planning on addressing that after hopefully these bug fix PRs get in.

**Comment by ScottPJones** [comment]
@stevengj Are my responses enough to satisfy you on the 3 notes, or do you want things changed?  Thanks!

**Comment by ScottPJones** [comment]
@stevengj I just tried to remove those (from `ascii.jl`, `utf8.jl`, `utf16.jl`, and `utf32.jl`), but ended up with the following fun:
```julia
socket.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 128: LoadError(at "socket.jl" line 644: StackOverflowError()))
rec_backtrace at /j/julia/src/task.c:644
eval at /j/julia/usr/lib/libjulia.dylib (unknown line)
jl_parse_eval_all at /j/julia/src/toplevel.c:567
jl_load at /j/julia/src/toplevel.c:610
include at boot.jl:254
jl_apply at /j/julia/src/interpreter.c:55
eval at /j/julia/src/interpreter.c:212
jl_toplevel_eval_flex at /j/julia/src/toplevel.c:517
jl_eval_module_expr at /j/julia/src/toplevel.c:156
jl_parse_eval_all at /j/julia/src/toplevel.c:567
jl_load at /j/julia/src/toplevel.c:610
exec_program at /j/julia/usr/bin/julia (unknown line)
true_main at /j/julia/usr/bin/julia (unknown line)
main at /j/julia/usr/bin/julia (unknown line)
```

File: base/utf16.jl (hunk 27 above)
Comment (ScottPJones) [inline base/utf16.jl]: It turns out, that that line in `essentials.jl` never gets used... when I remove the definition above, I get:
```julia
julia> @which convert(UTF16String, utf16("foo"))
convert(::Type{UTF16String}, s::AbstractString) at utf16.jl:75
```
which is defined as:
```julia
convert(::Type{UTF16String}, s::AbstractString) = encode16(s)
```
So I don't think I *can* do anything about those, they are really there for a reason, to keep the AbstractString version from being used.

**Comment by ScottPJones** [comment]
Can this go in so we can move on to ripping apart my next set of bug fixes? :grinning:

**Comment by tkelman** [comment]
I think this looks fine now, doesn't look like there are any obvious candidates for much code reuse in what's left.

**Comment by ScottPJones** [comment]
Bump: this code hasn't changed in almost two weeks (just been rebased to keep up with other changes being put into base).  Anything preventing it from being merged in now?

**Comment by stevengj** [comment]
LGTM.

**Comment by ScottPJones** [comment]
Thanks, @tkelman!

**Comment by tkelman** [comment]
Crap, I think I'm going to have to revert this, I'm now getting an error `syntax: invalid character ""`. This is one case where it would've been ideal to run an immediately pre-merge integration test. Please restore the branch, make a copy of it and file a new PR.

**Comment by tkelman** [comment]
Scratch that, I think it's an unrelated problem caused by a mistake I made, will fix.

**Comment by ScottPJones** [comment]
There is also a fix to JSON.jl in JuliaLang/JSON.jl#111
