### PR TITLE
Test for #26771

### LINKED ISSUE #26771: Inference regression with Union{T,Nothing} arrays
The following MWE used to be inferred as `Array{_,1} where _` on Julia 0.6, but on a recent master it's only inferred as `Array`. This regression is probably recent, as it breaks `@inferred` on `vcat` for CategoricalArrays, yet I hadn't noticed any test failure until today.
```julia
function f(a)
    v = [1, nothing]
    [v[x] for x in a]
end
@code_warntype f([1])
```

### PR DESCRIPTION
**Pull request by oscardssmith**
Fixes #26771

### CODE REVIEW

File: test/arrayops.jl [hunk 1]
```diff
@@ -2860,3 +2860,8 @@ end
     @test String(take!(b)) ==
         "BoundsError: attempt to access 2×2 Matrix{Float64} at index [10, \"bad index\"]"
 end
+
+@testset "inference of Union{T,Nothing} arrays 26771" begin
+    f(a) = (v = [1, nothing]; [v[x] for x in a])
+    @test eltype(f([1])) == Int
```
Comment (timholy) [inline test/arrayops.jl:2866]:
```suggestion
    @test only(Base.return_types(f, (Int,))) === Union{Array{Int,0}, Array{Nothing,0}}
    @test only(Base.return_types(f, (UnitRange{Int},))) <: Vector
```

Comment (timholy) [reply test/arrayops.jl:2866]: The key point about #26771 is successful inference of the dimensionality in the face of uncertain eltype.
