### PR TITLE
Make verify trim printing more readable (also fix the colours)

### LINKED ISSUE #60412: Severe memory consumption (20 GB+) when printing certain `--trim` errors
This is with a modified version of `libsimple.jl`:
```julia
module SimpleLib

struct CTree{T}
    children::Vector{CTree{T}}
end

Base.@ccallable "tree_size" function size(tree::CTree{Float64})::Int64
    children = tree.children
    length(children) != 0 && println(stderr, "bad time", children[1])
    # Return the size of this sub-tree
    return sum(Int[
        size(child)
        for child in children
    ]; init=1)
end

end
```

This triggers a severe over-consumption of memory:
```julia
$ ./julia ./contrib/juliac/juliac.jl --experimental --trim=safe test/trimming/libsimple.jl --output-lib libsimple.so --compile-ccallable
Error #1: <hangs here and rapidly exhausts memory>
[1777] signal 15: Terminated
in expression starting at none:0
unknown function (ip: 0x7d2d58b8950a) at /lib/x86_64-linux-gnu/libc.so.6
GenericMemory at ./boot.jl:615 [inlined]
array_new_memory at ./array.jl:1101 [inlined]
_growend_internal! at ./array.jl:1181
_growend! at ./array.jl:1205 [inlined]
_push! at ./array.jl:1348 [inlined]
push! at ./array.jl:1345 [inlined]
verify_create_stackframes at ./../usr/share/julia/Compiler/src/verifytrim.jl:269
verify_print_error at ./../usr/share/julia/Compiler/src/verifytrim.jl:234
verify_typeinf_trim at ./../usr/share/julia/Compiler/src/verifytrim.jl:511
unknown function (ip: 0x7d2d5092a640) at (unknown file)
_jl_invoke at /home/topolarity/repos/julia/src/gf.c:4116 [inlined]
ijl_apply_generic at /home/topolarity/repos/julia/src/gf.c:4313
jl_apply at /home/topolarity/repos/julia/src/julia.h:2285 [inlined]
jl_f_invoke_in_world at /home/topolarity/repos/julia/src/builtins.c:908
verify_typeinf_trim at ./../usr/share/julia/Compiler/src/typeinfer.jl:1838 [inlined]
typeinf_ext_toplevel at ./../usr/share/julia/Compiler/src/typeinfer.jl:1832
compile_and_emit_native at ./../usr/share/julia/Compiler/src/precompile.jl:415
jfptr_compile_and_emit_native_87134 at /home/topolarity/repos/julia/usr/lib/julia/sys.so (unknown line)
_jl_invoke at /home/topolarity/repos/julia/src/gf.c:4100 [inlined]
ijl_apply_generic at /home/topolarity/repos/julia/src/gf.c:4313
jl_apply at /home/topolarity/repos/julia/src/julia.h:2285 [inlined]
jl_create_native_impl at /home/topolarity/repos/julia/src/aotcompile.cpp:749
ijl_create_system_image at /home/topolarity/repos/julia/src/staticdata.c:3385
ijl_write_compiler_output at /home/topolarity/repos/julia/src/precompile.c:140
ijl_atexit_hook at /home/topolarity/repos/julia/src/init.c:280
jl_repl_entrypoint at /home/topolarity/repos/julia/src/jlapi.c:1139
main at /home/topolarity/repos/julia/cli/loader_exe.c:58
unknown function (ip: 0x7d2d58a2a1c9) at /lib/x86_64-linux-gnu/libc.so.6
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/topolarity/repos/julia/usr/bin/julia (unknown line)
unknown function (ip: (nil)) at (unknown file)
Allocations: 14933162 (Pool: 14933070; Big: 92); GC: 28

Failed to compile test/trimming/libsimple.jl
```

The OOM is so bad that it can knock me out of the WSL2 VM:
```console
$ ./julia ./contrib/juliac/juliac.jl --experimental --trim=safe test/trimming/libsimple.jl --output-lib libsimple.so --compile-ccallable
Error #1<abruptly exits VM session>
PS C:\Users\topolarity> wsl
Catastrophic failure
Error code: Wsl/Service/E_UNEXPECTED
PS C:\Users\topolarity> wsl
Catastrophic failure
Error code: Wsl/Service/E_UNEXPECTED
```

### PR DESCRIPTION
**Pull request by gbaraldi**
pr:
image

master:
image

Inspired by @jakobnissen's blog https://viralinstruction.com/posts/aoc2025/

Written with AI help

### CODE REVIEW

File: Compiler/src/verifytrim.jl [hunk 1]
```diff
@@ -49,76 +49,223 @@ const runtime_functions = Symbol[
...
+function print_styled(io::IO, @nospecialize(x), stable::Bool)
+    stable ? printstyled(io, x; color=:light_black) : print(io, x)
+end
+
+# Check if we should elide the type annotation for a statement
+function should_elide_type(newstmt, @nospecialize(typ))
+    newstmt isa Expr && newstmt.head ∈ (:quote, :inert) && return true
+    newstmt isa GlobalRef && isdispatchelem(typ) && return true
+    newstmt isa Union{Int, UInt8, UInt16, UInt32, UInt64, Float16, Float32, Float64, String, QuoteNode} && return true
+    newstmt isa Callable && return true
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]:
```suggestion
    newstmt isa QuoteNode && return true
    is_self_quoting(newstmt) && return true
```

Unless you're trying to control for bad object printing, this seems like a more consistent choice.

File: Compiler/src/verifytrim.jl [hunk 2]
```diff
@@ -49,76 +49,223 @@ const runtime_functions = Symbol[
...
-# wrap a statement in a typeassert for printing clarity, unless that info seems already obvious
-function mapssavaluetypes(codeinfo::CodeInfo, sptypes::Vector{VarState}, stmt)
-    @nospecialize stmt
-    newstmt = mapssavalues(codeinfo, sptypes, stmt)
-    typ = widenconst(argextype(stmt, codeinfo, sptypes))
-    if newstmt isa Expr
-        if newstmt.head ∈ (:quote, :inert)
-            return newstmt
+# Check if a union is small with concrete types (same logic as code_warntype's is_expected_union)
+function is_expected_union(@nospecialize(u::Union))
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]: Maybe instead of duplicating, we should move these into the Compiler printing utilities and have `InteractiveUtils` pull them in from there?

File: Compiler/src/verifytrim.jl [hunk 3]
```diff
@@ -49,76 +49,223 @@ const runtime_functions = Symbol[
...
+        printstyled(io, typ; color=:yellow)
+    elseif isdispatchelem(typ)
+        printstyled(io, typ; color=:light_black)
+    else
+        printstyled(io, typ; color=:red, bold=true)
+    end
+end
+
+# Print with light_black if stable, normal otherwise
+function print_styled(io::IO, @nospecialize(x), stable::Bool)
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]:
```suggestion
function print_nontype(io::IO, @nospecialize(x), stable::Bool)
```

Not a great name, but better than `print_styled` and `printstyled` floating around in the same function

File: Compiler/src/verifytrim.jl [hunk 4]
```diff
@@ -49,76 +49,223 @@ const runtime_functions = Symbol[
...
+    stable ? printstyled(io, x; color=:light_black) : print(io, x)
+end
+
+# Check if we should elide the type annotation for a statement
+function should_elide_type(newstmt, @nospecialize(typ))
+    newstmt isa Expr && newstmt.head ∈ (:quote, :inert) && return true
+    newstmt isa GlobalRef && isdispatchelem(typ) && return true
+    newstmt isa Union{Int, UInt8, UInt16, UInt32, UInt64, Float16, Float32, Float64, String, QuoteNode} && return true
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]: This is a really random set of types - Any justification for it?

I thought this might be either:
  - Base types that already print their type (e.g. `Float16`) or are supported as literals
  - Objects that are self-quoting

but it doesn't seem to match either

File: Compiler/src/verifytrim.jl [hunk 5]
```diff
@@ -49,76 +49,223 @@ const runtime_functions = Symbol[
...
+        else
+            return stmt
+        end
+    end
+end
+
+# Convert Core.Argument to slot name symbol if available
+function argument_name(codeinfo::CodeInfo, arg::Core.Argument)
+    slotnames = codeinfo.slotnames
+    if slotnames !== nothing && arg.n <= length(slotnames)
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl:103]: The IR verifier seems to suggest that `codeinfo.slotnames` is always populated and the right length - Is that not true?

File: Compiler/src/verifytrim.jl [hunk 6]
```diff
@@ -49,76 +49,223 @@ const runtime_functions = Symbol[
...
+        return Expr(:call, Symbol("φ "))
     end
     return stmt
 end
 
-function verify_print_stmt(io::IOContext{IO}, codeinfo::CodeInfo, sptypes::Vector{VarState}, stmtidx::Int)
-    if codeinfo.slotnames !== nothing
-        io = IOContext(io, :SOURCE_SLOTNAMES => sourceinfo_slotnames(codeinfo))
+# Colors for matching parentheses at different nesting levels
+const PAREN_COLORS = (:blue, :yellow, :magenta, :cyan, :green)
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]: I'm really not a fan of multi-colored parentheses personally

They really overload the maximum number of visual items I can track at a time. Do you think they're very helpful?

File: Compiler/src/verifytrim.jl [hunk 7]
```diff
@@ -377,9 +524,13 @@ function verify_typeinf_trim(io::IO, codeinfos::Vector{Any}, onlywarn::Bool)
         warn, desc = desc
         severity = warn ? 2 : 1
         no = (counts[severity] += 1)
-        print(io, warn ? "Verifier warning #" : "Verifier error #", no, ": ")
+        if warn
+            printstyled(io, "Verifier warning #", no, ": "; color=Base.warn_color(), bold=true)
+        else
+            printstyled(io, "Verifier error #", no, ": "; color=Base.error_color(), bold=true)
+        end
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]:
```suggestion
        printstyled(io, "Problem #", no, ": "; color=Base.warn_color(), bold=true)
```

The index is shared but these are counted separately, so changing between "error" / "warning" seems a bit confusing to me

**Review by topolarity — COMMENTED** [review]
Looks like a solid improvement to me. Thanks @gbaraldi !

File: Compiler/src/verifytrim.jl (hunk 4 above)
Comment (gbaraldi) [reply Compiler/src/verifytrim.jl]: These were already in the code tbf. The diff is messy

Comment (topolarity) [reply Compiler/src/verifytrim.jl]: I did not realize that! In that case, I won't bother you about it 🙂

File: Compiler/src/verifytrim.jl (hunk 5 above)
Comment (gbaraldi) [reply Compiler/src/verifytrim.jl:103]: Where do you see that?

Comment (gbaraldi) [reply Compiler/src/verifytrim.jl:103]: Most uses I see do check it.

File: Compiler/src/verifytrim.jl (hunk 7 above)
Comment (gbaraldi) [reply Compiler/src/verifytrim.jl]: I went with just error here. I don't think the user deciding to ignore errors means we should print them as warnings

File: Compiler/src/verifytrim.jl [hunk 8]
```diff
@@ -47,78 +47,208 @@ const runtime_functions = Symbol[
...
-    @nospecialize stmt
-    if stmt isa SSAValue
-        return mapssavalues(codeinfo, sptypes, codeinfo.code[stmt.id])
-    elseif stmt isa PiNode
-        return mapssavalues(codeinfo, sptypes, stmt.val)
+# Convert Core.Argument to slot name symbol if available
+function argument_name(codeinfo::CodeInfo, arg::Core.Argument)
+    slotnames = codeinfo.slotnames
+    if slotnames !== nothing && arg.n <= length(slotnames)
+    return slotnames[arg.n]
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]: odd indentation

**Review by topolarity — CHANGES_REQUESTED** [review]
Looks like you're missing a `repr` when printing constant values:
```julia
Error #1: unresolved call from statement Base.print(
  Base.stdout::IO,
  x::String,

::String # this is "\n"::String
)::Nothing
```

ran into this with:
```julia
function @main(ARGS)
    println("hello!")
end
```

This can also end up with some pretty complex output at times:
```julia
Main.SimpleLib.unsafe_wrap(
  Main.SimpleLib.Array::Type{Array},
  Base.getproperty(
    Base.getproperty(
      Main.SimpleLib.tree::Any,
      …::Symbol
    )::Any,
    :data::Symbol
  )::Any,
  Base.getproperty(
    Base.getproperty(
      Main.SimpleLib.tree::Any,
      …::Symbol
    )::Any,
    :length::Symbol
  )::Any
)::Array{T, N} where {N, T}
```

I'm not sure unwrapping that many calls is needed? It seems that beyond 1 or 2 you are likely to want to dive into the IR instead.

Oh and the usage of "…" reminds me of `Varargs`, but that's not what it means. It would be good to make that clearer somehow.

File: Compiler/src/verifytrim.jl [hunk 9]
```diff
@@ -78,8 +78,10 @@ function print_type_colored(io::IO, @nospecialize(typ))
 end
 
 # Print with light_black if stable, normal otherwise
+# Use repr for strings/chars to show quotes
 function print_nontype(io::IO, @nospecialize(x), stable::Bool)
-    stable ? printstyled(io, x; color=:light_black) : print(io, x)
+    txt = x isa Union{AbstractString, AbstractChar} ? Base.repr(x) : x
```
Comment (topolarity) [inline Compiler/src/verifytrim.jl]: Any reason not to always use `repr`?

**Review by topolarity — APPROVED** [review]
This is looking pretty good now! 

My only remaining wishlist is to translate intrinsics back to user-familiar syntax, such as:
    - `getproperty(x::T, :field)::FieldT` -> `(x::T).field::FieldT`
    - `Base.memoryrefget((…)::MemoryRef{T}, (…)::Symbol, (…)::Bool)` -> `(...)[]::T`
    - etc.

I'm sure there will be plenty of details to work out w.r.t. when we can do that faithfully without mis-leading the user and exactly how we want to translate it all, so probably best left to a separate PR anyway.

Very minor, but I also think it'd be nice to have an extra newline before the stacktrace, like:
```julia
Error #1: unresolved call from statement Main.SimpleLib.println(
  Main.SimpleLib.stderr::IO,
  "bad time"::String,
  Base.memoryrefget((…)::MemoryRef{Main.SimpleLib.CTree{Float64}}, (…)::Symbol, (…)::Bool)::Main.SimpleLib.CTree{Float64}
)::Any

Stacktrace:
 [1] size(tree::Main.SimpleLib.CTree{Float64})
   @ Main.SimpleLib ~/repos/julia/test/trimming/libsimple.jl:9
 [2] size(tree::Main.SimpleLib.CTree{Float64})
   @ Main.SimpleLib ~/repos/julia/test/trimming/libsimple.jl:11
```

Other than that, this looks ready to go to me. Thanks again @gbaraldi !

**Comment by topolarity** [comment]
Actually hold on.. This seems to still have pretty aggressive nesting somehow:

```julia
Base.prod(
  Base.getfield(
    Main.SimpleLib.unsafe_wrap(
      (…)::Type{Array},
      Base.getproperty(
        Base.getproperty(
          Main.SimpleLib.tree::Any,
          (…)::Symbol
        )::Any,
        (…)::Symbol
      )::Any,
      Base.getproperty(
        Base.getproperty(
          Main.SimpleLib.tree::Any,
          (…)::Symbol
        )::Any,
        (…)::Symbol
      )::Any
    )::Array{T, N} where {N, T},
    (…)::Symbol
  )::NTuple{N, Int64} where N
)::Int64
```

Is the limit not being applied?

This would almost be readable if we translated the intrinsics back to syntax, but as-is it's pretty overwhelming

**Comment by topolarity** [comment]
Also the `(…)::Symbol` is hiding some pretty crucial information.. That's a really nice identifier to have.

Can we avoid abbreviating "small" constant values in that position?

**Comment by gbaraldi** [comment]
We may want to port this to 1.13. and maybe even 1.12 (it's technically a bug fix of https://github.com/JuliaLang/julia/issues/60412
