### PR TITLE
task: drop parent and module references

### LINKED ISSUE #29059: eval in __init__ causes incorrect precompilation warning
Noticed in a couple of packages since precompile is on by default. Setup:
```julia
using Pkg
A = joinpath(pwd(), "PackageA");
B = joinpath(pwd(), "PackageB");
Pkg.generate.(["PackageA", "PackageB"]);
Pkg.activate(A);
Pkg.develop(PackageSpec(path = B));
Pkg.activate();
Pkg.develop([PackageSpec(path = A), PackageSpec(path = B)]);
write(joinpath(A, "src", "PackageA.jl"), "module PackageA\nusing PackageB\nend");
write(joinpath(B, "src", "PackageB.jl"), "module PackageB\n__init__() = eval(:(b() = 1))\nend");
```
and then
```julia
julia> using PackageA
[ Info: Precompiling PackageA [578a9956-b149-11e8-3635-0b7267ab0bb3]
WARNING: eval from module PackageB to PackageA:    
Expr(:call, :b) = Expr(:block, #= Symbol("/home/fredrik/PackageB/src/PackageB.jl"):2 =#, 1)
  ** incremental compilation may be broken for this module **
```

See e.g. https://github.com/JuliaDocs/Documenter.jl/issues/806

### PR DESCRIPTION
**Pull request by vtjnash**
The parent link can unnecessarily hold memory references live, and the current-module function is gone.
Their uses have been deprecated in favor of the macros @`__FILE__` and @`__MODULE__`.
The `workspace()` function is also gone now, so we can remove the support code for it.

To implement detection of broken incremental compilation (and help
ensure the module is permanently rooted as is generally expected),
keep track of all "open" modules in a hashtable (jl_current_modules).
We can further refine this later, if desired (e.g. also allow any
submodule and of any item in `jl_module_init_order`).

Also removes the global `module_stack` state. This makes us a bit more
robust to async module definition. We could perhaps do even more here,
if necessary (e.g. by checking first that all parents are initialized,
instead of just the direct ancestor). But this is hopefully a vanishingly
rare situation anyways.

closes #29059 (rewords the message to be less confusing)

### CODE REVIEW

File: src/precompile.c [hunk 1]
```diff
@@ -88,6 +96,13 @@ void jl_write_compiler_output(void)
                            (const char*)s->buf, (size_t)s->size);
         }
     }
+    for (size_t i = 0; i < jl_current_modules.size; i += 2) {
+        if (jl_current_modules.table[i + 1] != HT_NOTFOUND) {
+            jl_printf(JL_STDERR, "\nWARNING: detected unclosed module: ");
+            jl_static_show(JL_STDERR, (jl_value_t*)jl_current_modules.table[i]);
+            jl_printf(JL_STDERR, "\n  ** incremental compilation may be broken for this module **\n\n");
+        }
+    }
```
Comment (vtjnash) [inline src/precompile.c]: example output:
```
$ ./julia --output-ji x.ji --sysimage usr/lib/julia/sys.so -e 'module A; end; @async(@eval module As; sleep(1); end); yield(); module B; module C; exit(0); end; end' --output-incremental=yes

WARNING: detected unclosed module: B
  ** incremental compilation may be broken for this module **


WARNING: detected unclosed module: B.C
  ** incremental compilation may be broken for this module **


WARNING: detected unclosed module: As
  ** incremental compilation may be broken for this module **
```
I assume this never happens in real code (and thus isn't worthwhile to try to handle), but since this already added the infrastructure to be able detect it, might as well print a warning.

File: src/toplevel.c [hunk 2]
```diff
@@ -267,25 +202,44 @@ jl_value_t *jl_eval_module_expr(jl_module_t *parent_module, jl_expr_t *ex)
...
+                jl_module_run_initializer(m);
             }
-            assert(module_stack.len == l);
-            module_stack.len = stackidx;
-        }
-        JL_CATCH {
-            module_stack.len = stackidx;
-            jl_rethrow();
         }
     }
```
Comment (vtjnash) [inline src/toplevel.c]: For example, the old code would run the `A` method too early in the following highly-contrived example:
```julia
julia> @async @eval module B; sleep(3); __init__() = println("B"); end
Task (runnable) @0x0000000114947190

julia> module A; module A2; __init__() = println("A"); end; sleep(10); end
A
B
```
(should print B after 3 seconds, then A after 10; instead prints A then B after 3 seconds)
This also seems vanishingly-unlikely to make a difference to anyone. I just mention it as a side-effect of the other code changes.

File: src/jlapi.c [hunk 3]
```diff
@@ -86,14 +86,11 @@ JL_DLLEXPORT jl_value_t *jl_eval_string(const char *str)
 {
     jl_value_t *r;
     JL_TRY {
-        const char *filename = "none";
+        const char filename[] = "none";
         jl_value_t *ast = jl_parse_input_line(str, strlen(str),
                 filename, strlen(filename));
         JL_GC_PUSH1(&ast);
-        size_t last_age = jl_get_ptls_states()->world_age;
-        jl_get_ptls_states()->world_age = jl_get_world_counter();
```
Comment (JeffBezanson) [inline src/jlapi.c]: This changes behavior; should be done separately.

Comment (vtjnash) [reply src/jlapi.c]: It's deadcode—jl_toplevel_eval already handles managing of the world-age

**Review by JeffBezanson — APPROVED** [review]

**Comment by Keno** [comment]
Can the `jl_current_modules` thing be used to fix #28917?

**Comment by vtjnash** [comment]
Yeah, probably might as well. I inserted  some comments here to the effect, but wanted to defer addressing it to a separate PR.

**Comment by Keno** [comment]
Sure.
