### PR TITLE
check for powershell version in download

### LINKED ISSUE #26459: New download implementation doesn't work on Win7
https://github.com/JuliaLang/julia/pull/25477 changed the way ``download`` works on Windows: it now always uses PowerShell. The new implementation uses features that are not available on a fully patched Win 7 SP1 system, though, and so doesn't work there. In particular, ``[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12`` does not work on those systems, because the version of .Net that ships with Win7 doesn't have the ``Tls12`` value in it. This now affects both base, and also BinDeps.jl (which uses the same strategy). I'm not sure about BinaryProvider.jl.

I learned about this because one of my students is on a system like this and BinDeps.jl essentially doesn't work for him. I then installed a clean Win7 SP1 in a VM, ran Windows Update until everything was installed and tried things, and same story.

Now, there are probably lots of users out there that have for some reason or another a newer version of .Net & PowerShell installed on their Win 7 systems, and then everything will work. But if the message is that Win 7 is fully supported, it should probably work on a system as MS ships it.

### PR DESCRIPTION
**Pull request by simonbyrne**
fixes #26459

### CODE REVIEW

File: base/download.jl [hunk 1]
```diff
@@ -11,7 +11,16 @@ if Sys.iswindows()
         client = "New-Object System.Net.Webclient"
         # in the following we escape ' with '' (see https://ss64.com/ps/syntax-esc.html)
         downloadfile = "($client).DownloadFile('$(replace(url, "'" => "''"))', '$(replace(filename, "'" => "''"))')"
-        run(`$ps -NoProfile -Command "$tls12; $downloadfile"`)
+        # PowerShell v3 or later is required for Tls12
+        ps = run(pipeline(`$ps -Version 3 -NoProfile -Command "$tls12; $downloadfile"`; stderr=stderr); wait=false)
```
Comment (JeffBezanson) [inline base/download.jl]: `proc` instead of `ps`?

**Comment by simonbyrne** [comment]
@davidanthoff Do you have better suggestions for an error message?

**Review by vtjnash — APPROVED** [review]

**Comment by davidanthoff** [comment]
No better idea for an error message, I think this is probably enough to get people googling, right?
