### PR TITLE
Widen diagonal var during `Type` unwrapping in `instanceof_tfunc`

### LINKED ISSUE #27031: incorrect handling of covariant tuple fieldtypes causes crash
This MWE triggers a crash (written by @vtjnash):

```julia
x = 1.0
@noinline bar1(tt::Tuple{T,T}, ::Type{Val{T}}) where {T} = notsame(tt)
@noinline notsame(tt::Tuple{T, T}) where {T} = error()
@noinline notsame(tt::Tuple{T, S}) where {T, S} = "OK"
foo1() = bar1((x, 1.0), Val{_Any})
_Any = Any
foo1()
x = 1
foo1()
```

This prints:

```julia
Unreachable reached at 0x10d5a6de4

signal (4): Illegal instruction: 4
in expression starting at no file:0
foo1 at ./REPL[5]:1
do_call at /Users/jarrettrevels/data/repos/julia7/src/interpreter.c:324
eval_body at /Users/jarrettrevels/data/repos/julia7/src/interpreter.c:559
jl_interpret_toplevel_thunk_callback at /Users/jarrettrevels/data/repos/julia7/src/interpreter.c:798
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x109b42caf)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /Users/jarrettrevels/data/repos/julia7/src/interpreter.c:807
jl_toplevel_eval_flex at /Users/jarrettrevels/data/repos/julia7/src/toplevel.c:856
jl_toplevel_eval_in at /Users/jarrettrevels/data/repos/julia7/src/builtins.c:624
eval at ./boot.jl:317 [inlined]
eval at /Users/jarrettrevels/data/repos/julia7/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:5
eval_user_input at /Users/jarrettrevels/data/repos/julia7/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
macro expansion at /Users/jarrettrevels/data/repos/julia7/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:116 [inlined]
#28 at ./event.jl:92
jl_fptr_trampoline at /Users/jarrettrevels/data/repos/julia7/src/gf.c:1838
jl_apply at /Users/jarrettrevels/data/repos/julia7/src/./julia.h:1540 [inlined]
start_task at /Users/jarrettrevels/data/repos/julia7/src/task.c:268
Allocations: 2757027 (Pool: 2755329; Big: 1698); GC: 6
[1]    23580 illegal hardware instruction  julia7
```

So this is perhaps another example where  #24614 could make life easier for inference

```julia
julia> versioninfo()
Julia Version 0.7.0-DEV.5036
Commit 9de318a (2018-05-07 18:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
```

### LINKED ISSUE #52168: `Unreachable reached at 0x7fb1e395276a`, Illegal instruction
Testing an in-development version of my package reproducibly reaches unreachable. RR trace obtained with `julia --bug-report=rr`: https://julialang-dumps.s3.amazonaws.com/reports/2023-11-14T18-13-29-nsajko.tar.zst

As far as I understand the source of my package isn't necessary given the RR trace? In any case, I think this is a type inference issue because the stack trace point to a line that includes a type assertion.

I'm not sure if the Rr trace contains the relevant info, considering that unreachable gets reached during testing. Inform me if another Rr trace is needed.

This is with nightly Julia:

```julia-repl
julia> versioninfo()
Julia Version 1.11.0-DEV.894
Commit 9754dbbde5c (2023-11-13 18:40 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 3
  JULIA_PKG_PRECOMPILE_AUTO = 0
```

Stack trace:

```
Unreachable reached at 0x7fb1e395276a

[40752] signal 4 (2): Illegal instruction
in expression starting at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:60
merge_oblivious_sd at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Merging.jl:121
merge_oblivious_impl at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Merging.jl:124
merge_oblivious at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Merging.jl:140
merge at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Merging.jl:165
sorted_impl at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Sorting.jl:83
sorted_impl at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Sorting.jl:81
sorted at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/src/Sorting.jl:128
macro expansion at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:34 [inlined]
macro expansion at /cache/build/builder-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:676 [inlined]
test_sorting_shared at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:34
test_sorting at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:38
unknown function (ip: 0x7fb1e3953901)
_jl_invoke at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:2910 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:3092
test_sorting at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:57
unknown function (ip: 0x7fb1e3951fc5)
_jl_invoke at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:2910 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:3092
macro expansion at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:66 [inlined]
macro expansion at /cache/build/builder-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1687 [inlined]
macro expansion at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:65 [inlined]
macro expansion at /cache/build/builder-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1598 [inlined]
top-level scope at /home/nsajko/src/gitlab.com/nsajko/TupleSorting/test/runtests.jl:61
jl_toplevel_eval_flex at /cache/build/builder-amdci4-2/julialang/julia-master/src/toplevel.c:932
jl_toplevel_eval_flex at /cache/build/builder-amdci4-2/julialang/julia-master/src/toplevel.c:884
ijl_toplevel_eval_in at /cache/build/builder-amdci4-2/julialang/julia-master/src/toplevel.c:992
eval at ./boot.jl:425 [inlined]
include_string at ./loading.jl:2133
_jl_invoke at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:2910 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:3092
_include at ./loading.jl:2193
include at ./sysimg.jl:38
unknown function (ip: 0x7fb2086fa7c5)
_jl_invoke at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:2910 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:3092
jl_apply at /cache/build/builder-amdci4-2/julialang/julia-master/src/julia.h:2130 [inlined]
do_call at /cache/build/builder-amdci4-2/julialang/julia-master/src/interpreter.c:126
eval_value at /cache/build/builder-amdci4-2/julialang/julia-master/src/interpreter.c:223
eval_stmt_value at /cache/build/builder-amdci4-2/julialang/julia-master/src/interpreter.c:174 [inlined]
eval_body at /cache/build/builder-amdci4-2/julialang/julia-master/src/interpreter.c:641
jl_interpret_toplevel_thunk at /cache/build/builder-amdci4-2/julialang/julia-master/src/interpreter.c:795
jl_toplevel_eval_flex at /cache/build/builder-amdci4-2/julialang/julia-master/src/toplevel.c:941
jl_toplevel_eval_flex at /cache/build/builder-amdci4-2/julialang/julia-master/src/toplevel.c:884
ijl_toplevel_eval_in at /cache/build/builder-amdci4-2/julialang/julia-master/src/toplevel.c:992
eval at ./boot.jl:425 [inlined]
exec_options at ./client.jl:291
_start at ./client.jl:525
jfptr__start_65686.1 at /home/nsajko/tmp/jl/jl/julia-9754dbbde5/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:2910 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-2/julialang/julia-master/src/gf.c:3092
jl_apply at /cache/build/builder-amdci4-2/julialang/julia-master/src/julia.h:2130 [inlined]
true_main at /cache/build/builder-amdci4-2/julialang/julia-master/src/jlapi.c:586
jl_repl_entrypoint at /cache/build/builder-amdci4-2/julialang/julia-master/src/jlapi.c:738
main at /cache/build/builder-amdci4-2/julialang/julia-master/cli/loader_exe.c:58
unknown function (ip: 0x7fb214e91ccf)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 231262030 (Pool: 231256281; Big: 5749); GC: 59
ERROR: Package TupleSorting errored during testing (received signal: 4)
```

### PR DESCRIPTION
**Pull request by N5N3**
close #52168
close #27031

### CODE REVIEW

**Comment by N5N3** [comment]
@nanosoldier `runtests()`

File: src/subtype.c [hunk 1]
```diff
@@ -4304,6 +4304,211 @@ int jl_subtype_matching(jl_value_t *a, jl_value_t *b, jl_svec_t **penv)
...
+    }
+    else if (jl_is_unionall(type)) {
+        jl_value_t *body = ((jl_unionall_t*)type)->body;
+        jl_tvar_t *var = ((jl_unionall_t*)type)->var;
+        jl_varbinding_t *v = troot;
+        for (; v != NULL; v = v->prev) {
+            if (v->var == (jl_tvar_t *)var)
+                break;
+        }
+        if (v == NULL) {
```
Comment (vtjnash) [inline src/subtype.c:4411]: This doesn't seem quite right to me. My original code only could replace a single TypeVar at a time, so it stopped recursion if it found that var. Since you are doing a whole batch here, I suggest instead setting `v->var = NULL` if `v != NULL` before computing `newbody`, and then re-setting it to `v->var = var` afterwards (before computing `newvar`.

File: src/subtype.c [hunk 2]
```diff
@@ -4304,6 +4304,211 @@ int jl_subtype_matching(jl_value_t *a, jl_value_t *b, jl_svec_t **penv)
...
+static jl_value_t *_widen_diagonal(jl_value_t *t, jl_varbinding_t *troot) {
+    check_diagonal(t, troot, 0);
+    int any_concrete = 0;
+    for (jl_varbinding_t *v = troot; v != NULL; v = v->prev) {
+        v->concrete = v->occurs_cov > 1 && v->occurs_inv == 0;
+        any_concrete |= v->concrete;
+    }
+    if (!any_concrete)
+        return t; // no diagonal
+    return insert_nondiagonal(t, troot, 0);
```
Comment (vtjnash) [inline src/subtype.c:4486]: Since you already checked occurs_inv, it may be already fine to do `wident2ub` always?
```suggestion
    return insert_nondiagonal(t, troot, 1);
```
In effect though, that may be the same as implementing it as a map of `rewrap_unionall` over the fields (but recursively) roughly doing `map(rewrap_unionall, t.parameters, Repeated(u))`?

I think the tricky cases I was thinking of were possibly something like:
`Tuple{Val{S}, T, T} where {S, T<:S}` or perhaps
`Tuple{S, T, T} where {S, T<:S}` or perhaps
`Tuple{S, Vararg{T}} where {S, T<:S}`

These could be safely widened to `Tuple{Val, Any, Any}`, `Tuple{Any, Any, Any}`, and `Tuple{Any, Vararg{Any}}` respectively, but I was hoping to instead convert them to the more precise results of `Tuple{Val{S}, T1, T2} where {S, T1<:S, T2<:S}`, `Tuple{S, T1, T2} where {S, T1<:S, T2<:S}`, and `Tuple{S, Vararg{Union{T1,T2} where T1<:S where T2<:S}} where S`

(though normally allocation normalization will have incorrectly broken that last type anyways, since it quickly converts that to `Tuple{S, Vararg{T where T<:S}} where S` which it thinks is equal to `Tuple{S, Vararg{S}} where S` even though it is not necessarily correct to replace T.ub with T in the expression `T where T` there–as that also implies a new constraint on the `Vararg`: that it is a diagonal Vararg when it was not intended to be)

**Review by vtjnash — COMMENTED** [review]
Thanks for tackling this and trying to make the `widen_diagonal` function a bit smarter!

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52228#issuecomment-1819039383) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/1fc9d54_vs_72cd63c/report.html) is available.

File: src/subtype.c (hunk 2 above)
Comment (N5N3) [reply src/subtype.c:4486]: It seems ok that
```julia
julia> CC.instanceof_tfunc(Type{Tuple{S, Vararg{T}}} where {S, T<:S})[1]
Tuple{S, Vararg{S}} where S
```
As `S` should be always concrete at runtime and `Tuple{S, Vararg{S}} where S` should cover all possible types.

The current code fails for this case though
```julia
julia> CC.instanceof_tfunc(Type{Tuple{S, S, Vararg{T}}} where {S, T<:S})[1]
Tuple{S2, S1, Vararg{S}} where {S, S1<:S, S2<:S}
```
It shows that the `widen2ub` branch should be recursive, and return `Tuple{S2, S1, Vararg{Any}} where {S, S1<:S, S2<:S}` instead.

File: src/subtype.c [hunk 3]
```diff
@@ -4304,6 +4304,212 @@ int jl_subtype_matching(jl_value_t *a, jl_value_t *b, jl_svec_t **penv)
...
+    else if (jl_is_uniontype(type)) {
+        jl_value_t *a = ((jl_uniontype_t*)type)->a;
+        jl_value_t *b = ((jl_uniontype_t*)type)->b;
+        jl_value_t *newa = NULL;
+        jl_value_t *newb = NULL;
+        JL_GC_PUSH2(&newa, &newb);
+        newa = insert_nondiagonal(a, troot, widen2ub);
+        newb = insert_nondiagonal(b, troot, widen2ub);
+        if (newa != a || newb != b)
+            type = (jl_value_t *)jl_new_struct(jl_uniontype_type, newa, newb);
```
Comment (vtjnash) [inline src/subtype.c:4442]: Should this use the jl_union_type normalization? I think newa and newb might have common elements after this. E.g. `Union{Tuple{S, T, T}, Tuple{T, T, S}} where {S, T}`

Comment (N5N3) [reply src/subtype.c:4442]: I think `newa` and `newb` would have no common elements if there's no widened `Vararg`, as we always insert a unique free typevar.
But for `Vararg`, there might be common elements as different `TypeVar` might have the same ub.

File: src/subtype.c [hunk 4]
```diff
@@ -4499,7 +4499,8 @@ static jl_value_t *widen_diagonal(jl_value_t *t, jl_unionall_t *u, jl_varbinding
     if (vb.innervars != NULL) {
         for (size_t i = 0; i < jl_array_nrows(vb.innervars); i++) {
             jl_tvar_t *var = (jl_tvar_t*)jl_array_ptr_ref(vb.innervars, i);
-            nt = jl_type_unionall(var, nt);
+            if (jl_has_typevar(nt, var))
+                nt = jl_type_unionall(var, nt);
```
Comment (vtjnash) [inline src/subtype.c:4503]: I think this check is already inside `jl_type_unionall`, so is unnecessary to duplicate here

File: src/subtype.c [hunk 5]
```diff
@@ -4304,6 +4304,213 @@ int jl_subtype_matching(jl_value_t *a, jl_value_t *b, jl_svec_t **penv)
...
+    JL_GC_PUSH2(&vb.innervars, &nt);
+    if (jl_is_unionall(u->body))
+        nt = widen_diagonal(t, (jl_unionall_t *)u->body, &vb);
+    else
+        nt = _widen_diagonal(t, &vb);
+    if (vb.innervars != NULL) {
+        for (size_t i = 0; i < jl_array_nrows(vb.innervars); i++) {
+            jl_tvar_t *var = (jl_tvar_t*)jl_array_ptr_ref(vb.innervars, i);
+            if (jl_has_typevar(nt, var))
+                nt = jl_type_unionall(var, nt);
```
Comment (N5N3) [inline src/subtype.c:4503]:
```suggestion
            nt = jl_type_unionall(var, nt);
```

**Comment by nsajko** [comment]
Will this fix get backported for v1.10? Just curious.

**Comment by KristofferC** [comment]
This is entangled with https://github.com/JuliaLang/julia/pull/51317 which is not marked for backporting and I am not comfortable to do the backport manually myself @N5N3 .

**Comment by N5N3** [comment]
Oh, didn't notice the Compiler side change. Will take a look tonight. @KristofferC
