### PR TITLE
RNG: fix Sampler selection for GLOBAL_RNG

### LINKED ISSUE #33170: Random Sampler selection got broken with thread safe RNG change
These lines:

https://github.com/JuliaLang/julia/blob/36c59c144122dbf09fc0e1f0f1e9defbbd2f254d/stdlib/Random/src/Random.jl#L139-L140

makes a selection of the Sampler to use based on `typeof(rng)`. 

On 1.2 we have

```jl
julia> typeof(Random.GLOBAL_RNG)
MersenneTwister
```

while on 1.3

```jl
julia> typeof(Random.GLOBAL_RNG)
Random._GLOBAL_RNG
```

This means that the specialized version here:

https://github.com/JuliaLang/julia/blob/36c59c144122dbf09fc0e1f0f1e9defbbd2f254d/stdlib/Random/src/RNGs.jl#L600-L603

no longer matches and we end up with the slower fallback sampler:

1.2:

```jl
julia> Random.Sampler(Random.GLOBAL_RNG, 1:4, Val(1))
Random.SamplerRangeFast{UInt64,Int64}(1, 0x0000000000000002, 0x0000000000000003, 0x0000000000000003)
```

1.3:

```jl
julia> Random.Sampler(Random.GLOBAL_RNG, 1:4, Val(1))
Random.SamplerRangeInt{Int64,UInt64}(1, 2, 0x0000000000000004, 0x000fffffffffffff)
```

As a side note, this also changes the random number stream:

1.2:

```jl
julia> Random.seed!(1234);

julia> rand(rng, 2:4)
2
```

1.3:

```jl
julia> Random.seed!(1234);

julia> rand(rng, 2:4)
3
```

cc @rfourquet, @vtjnash

### PR DESCRIPTION
**Pull request by rfourquet**
Fix #33170.

### CODE REVIEW

File: stdlib/Random/src/Random.jl [hunk 1]
```diff
@@ -136,8 +136,12 @@ the amount of precomputation, if applicable.
 *types* and *values*, respectively. [`Random.SamplerSimple`](@ref) can be used to store
 pre-computed values without defining extra types for only this purpose.
 """
-Sampler(rng::AbstractRNG, x, r::Repetition=Val(Inf)) = Sampler(typeof(rng), x, r)
-Sampler(rng::AbstractRNG, ::Type{X}, r::Repetition=Val(Inf)) where {X} = Sampler(typeof(rng), X, r)
+Sampler(rng::AbstractRNG, x, r::Repetition=Val(Inf)) = Sampler(_typeof(rng), x, r)
+Sampler(rng::AbstractRNG, ::Type{X}, r::Repetition=Val(Inf)) where {X} = Sampler(_typeof(rng), X, r)
+
+# GLOBAL_RNG currently represents a MersenneTwister
+_typeof(x) = typeof(x)
```
Comment (nalimilan) [inline stdlib/Random/src/Random.jl]: Maybe call this `typeof_rng` instead? `_typeof` sounds much more general.

File: stdlib/Random/src/Random.jl [hunk 2]
```diff
@@ -136,8 +136,13 @@ the amount of precomputation, if applicable.
...
 """
-Sampler(rng::AbstractRNG, x, r::Repetition=Val(Inf)) = Sampler(typeof(rng), x, r)
-Sampler(rng::AbstractRNG, ::Type{X}, r::Repetition=Val(Inf)) where {X} = Sampler(typeof(rng), X, r)
+Sampler(rng::AbstractRNG, x, r::Repetition=Val(Inf)) = Sampler(typeof_rng(rng), x, r)
+Sampler(rng::AbstractRNG, ::Type{X}, r::Repetition=Val(Inf)) where {X} =
+    Sampler(typeof_rng(rng), X, r)
+
+# GLOBAL_RNG currently represents a MersenneTwister
+typeof_rng(rng::AbstractRNG) = typeof(rng)
+typeof_rng(::_GLOBAL_RNG) = MersenneTwister
```
Comment (KristofferC) [inline stdlib/Random/src/Random.jl]: `_GLOBAL_RNG` is not defined here yet.

Comment (rfourquet) [reply stdlib/Random/src/Random.jl]: Ah right, is this why CI didn't build? I couldn't understand CI failures (am still used to travis interface).
