### PR TITLE
relocation: account for trailing path separator in depot paths

### LINKED ISSUE #55340: precompilation problems with 1.11.0-rc2
This issue looks similar to #53983, but details are different. On top of that, I don't know how ~~to reproduce it~~ others can reproduce it. Here is a very simple case of the problem:

I have an existing depot in `/usr/local/julia`. I make sure that there are no subfolders `compiled/v1.11` or `environments/v1.11` and then do the following:
```
~$ /usr/local/julia-1.11.0-rc2/bin/julia -q --startup-file=no
julia> using Base64
[ Info: Precompiling Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] 

julia> exit()

~$ /usr/local/julia-1.11.0-rc2/bin/julia -q --startup-file=no
julia> using Base64
[ Info: Precompiling Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] (cache misses: wrong source (1))

julia> exit()

~$ /usr/local/julia-1.11.0-rc2/bin/julia -q --startup-file=no
julia> using Base64
[ Info: Precompiling Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] (cache misses: wrong source (1))
```
and so on. With a newly created, completely empty depot the problem does not arise. Is there anything else that I should delete inside the existing depot? Any other ideas?
```
Julia Version 1.11.0-rc2
Commit 34c3a63147b (2024-07-29 06:24 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_DEPOT_PATH = /usr/local/julia
```

### PR DESCRIPTION
**Pull request by fatteneder**
Fixes #55340

### CODE REVIEW

File: base/loading.jl [hunk 1]
```diff
@@ -3131,7 +3131,7 @@ function replace_depot_path(path::AbstractString)
             depot = dirname(depot)
         end
 
-        if startswith(path, depot)
+        if startswith(path, string(depot, Filesystem.pathsep())) || path == depot
```
Comment (giordano) [inline base/loading.jl:3134]: I think you want to do something like https://github.com/JuliaLang/julia/blob/85f4db2eaa15fedf738f8a8c16c7168024780f7c/base/file.jl#L235

**Review by giordano — COMMENTED** [review]
If I understand it correctly, this is yet another instance of #43137

File: base/loading.jl (hunk 1 above)
Comment (giordano) [reply base/loading.jl:3134]: It looks like I keep making the same suggestions: https://github.com/JuliaLang/julia/pull/51892#discussion_r1373628965

Comment (fatteneder) [reply base/loading.jl:3134]: I think that would falsely insert a `@depot` when `path="/depot/julia-rc/somefile.jl"` and `depot="/path/julia"`, which is what this PR fixes.

Comment (fatteneder) [reply base/loading.jl:3134]: But thanks for making me double check, I realized I had the paths wrong in the tests.

Comment (topolarity) [inline base/loading.jl:3134]: In many cases, Windows accepts `/` as a path separator - is there any risk of that appearing here?

Comment (fatteneder) [reply base/loading.jl:3141]: oh, I did not know that.
I pushed a fix with an accompanying test.

Comment (topolarity) [reply base/loading.jl:3141]: Thanks! The replace isn't safe for UNC paths (it destroys double slashes `\\`), but maybe we don't support those?

https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#example-ways-to-refer-to-the-same-file shows some exotic ways to build paths on Windows, in case we do.

Comment (fatteneder) [reply base/loading.jl:3136]: I now settled to just use `abspath` to normalize both.
That should also increase the accuracy in matching depots in cases where one is an absolute and the other a relative one.

**Comment by KristofferC** [comment]
Seems like something is not good right now:

```
ERROR: LoadError: ArgumentError: embedded NULs are not allowed in C strings: "/cache/build/builder-amdci5-4/julialang/julia-master/\0+\x16,\xe1v\xe4\xf0\xb8.L=\xdaK3\x89\xf4StyledStrings
```

**Comment by fatteneder** [comment]
Windows now chokes on `abspath` and complains about an invalid character:
```
Base.InvalidCharError{Char}(char=Char(0xc6000000))
throw_invalid_char at .\char.jl:93
UInt32 at .\char.jl:140 [inlined]
convert at .\char.jl:192 [inlined]
cconvert at .\essentials.jl:675 [inlined]
lowercase at .\strings\unicode.jl:294 [inlined]
map at .\strings\basic.jl:667
lowercase at .\strings\unicode.jl:636 [inlined]
abspath at .\path.jl:452
replace_depot_path at .\loading.jl:3126
```

Any idea what that could be?

**Comment by vtjnash** [comment]
abspath does not always preserve being a path to the same file (except usually on Windows), so generally is not correct to use compared to other alternatives

File: base/loading.jl (hunk 1 above)
Comment (fatteneder) [reply base/loading.jl:3136]: I traced back the use of `replace_depot_path` and found that these issues should already be taken care of.
In particular,
- the `path` argument will be absolute and normalized when it arrives, which happens at `base/loading.jl:_include_dependency`,
- the elements of `DEPOT_PATH` also went through `abspath` before they are handed over to precompilation, see `base/loading.jl:create_expr_cache`.

So I will revert changes related to this and make the tests pass again.

**Comment by fatteneder** [comment]
this should be good to go now

File: base/loading.jl (hunk 1 above)
Comment (topolarity) [reply base/loading.jl:3136]: Where is `DEPOT_PATH` normalized if I do `--output-ji` with `JULIA_DEPOT_PATH`?

It seems like that would also hit this code path, iiuc

Comment (fatteneder) [reply base/loading.jl:3136]: Right before spawning the precompilation process, here https://github.com/JuliaLang/julia/blob/f2f76d8833541091ef13a47c49bb77b2263d9937/base/loading.jl#L2812

Shouldn't `--output-ji` hit that too?

Comment (topolarity) [reply base/loading.jl:3136]: That's something that spawns a process with `--output-ji` not the other way around

Comment (fatteneder) [reply base/loading.jl:3136]: I am sorry, I don't understand.
Where would be the entry point for what you describe?

Comment (topolarity) [reply base/loading.jl:3136]: Ah, my point is that it's legal to spawn Julia with `--output-ji` outside of the spawning that precompilation does, and in that case the DEPOT_PATH may not be normalized

Comment (fatteneder) [reply base/loading.jl:3136]: Ok, I see. Indeed, that's problematic.

**Comment by IanButterworth** [comment]
@topolarity @giordano @gbaraldi bump for approval

**Review by topolarity — COMMENTED** [review]
How does `normalize_depots_for_relocation` resolve the path separator / UNC prefix issues on Windows?

It feels like this code should be using `splitdrive` / `splitdir` / `splitpath` similar to https://github.com/JuliaLang/julia/pull/55720/

File: base/loading.jl [hunk 2]
```diff
@@ -3176,23 +3176,29 @@ mutable struct CacheHeaderIncludes
...
 
+function normalize_depots_for_relocation()
+    depots = String[]
+    sizehint!(depots, length(DEPOT_PATH))
+    for d in DEPOT_PATH
+        isdir(d) || continue
+        if isdirpath(d)
+            d = dirname(d)
+        end
+        push!(depots, d)
```
Comment (fatteneder) [inline base/loading.jl:3197]:
```suggestion
        push!(depots, abspath(d))
```

**Comment by fatteneder** [comment]
@topolarity this should be addressed by the `abspath` call I added

**Comment by fatteneder** [comment]
I see what you mean, but I would address that in a separate PR.

Pkgimage compilation has been using `abspath` so far without problems. Adding `normalize_depots_for_relocation` just extends this to user provided `--output-ji`.

**Review by topolarity — APPROVED** [review]
I think we might want to normalize our depots upon start-up instead of doing it on-the-fly here - The Julia-C interaction here is starting to get pretty ad-hoc.

That's a bigger change though, and this seems like an improvement so let's take this in for now.
