### PR TITLE
Fix incorrect sign of atanh(complex(x,y)) if x == -1

### LINKED ISSUE #31054: atan(1.0+im) is incorrectly signed
```
atan(1.0+im) == 1.0172219678978514 - 0.40235947810852507im
```
The sign of the imaginary part should be positive.

### PR DESCRIPTION
**Pull request by cafaxo**
In the case that x==-1, we have to flip the sign of ξ. Fixes the problem noticed in #31054.

Update:
The current Julia implementation was mistranscribed from the reference: The multiplication with the sign of x is missing (see [#31061 (comment)](https://github.com/JuliaLang/julia/pull/31061#issuecomment-463653341)). This PR currently adds that multiplication, fixing both the original sign issue and the problems (DomainError) near `z=-1+0im`.

### CODE REVIEW

File: base/complex.jl [hunk 1]
```diff
@@ -958,7 +958,7 @@ function atanh(z::Complex{T}) where T<:AbstractFloat
             η = zero(y)
         else
             ym = ay+ρ
-            ξ = log(sqrt(sqrt(4+y*y))/sqrt(ym))
+            ξ = copysign(log(sqrt(sqrt(4+y*y))/sqrt(ym)),x)
```
Comment (StefanKarpinski) [inline base/complex.jl]:
```suggestion
            ξ = copysign(log(sqrt(sqrt(4+y*y))/sqrt(ym)), x)
```

**Comment by stevengj** [comment]
The `η = zero(y)` in the `if y == 0` also seems wrong.

**Comment by Keno** [comment]
This should have a test to prevent this from regressing.

**Comment by StefanKarpinski** [comment]
> The `η = zero(y)` in the `if y == 0` also seems wrong.

Should it be `η = y` in that case?

**Comment by chethega** [comment]
Can we also fix `atanh(prevfloat(-1.0) + 0im)`? 

Most complex functions return some complex mix of `Inf` and `NaN` for singularities, instead of throwing. Worst case, `NaN + NaN*im` seems like a better alternative.

**Comment by martinholters** [comment]
I think we have at some point decided that throwing an appropriate error is more Julian than silently producing `NaN`. The exception is where something built-in gives `NaN` and, for performance, we don't do an extra check to throw instead. (`0.0/0.0` would be the prime example for the latter.)

**Comment by stevengj** [comment]
Arguably in the `y==0` case it should be `η = copysign(oftype(y,pi)/4, y)`, but I guess we wanted to agree with `atan(real(z))` in that case.  But at least we should do `η = y` to not discard the sign of zero.

**Comment by stevengj** [comment]
Note that 
```jl
julia> ccall(:catanh, ComplexF64, (ComplexF64,), complex(1.0, +0.0))
Inf + 0.7853981633974483im

julia> ccall(:catanh, ComplexF64, (ComplexF64,), complex(1.0, -0.0))
Inf - 0.7853981633974483im
```
so that would also argue for `η = copysign(oftype(y,pi)/4, y)` in the `y==0` case.

**Comment by stevengj** [comment]
Note that this code was from #2891 by @jiahao, which cites Kahan, but I think it mistranscribed the reference, which says:
image

**Comment by stevengj** [comment]
Note that this reference doesn't have the `copysign` on the `ξ` term…

**Comment by cafaxo** [comment]
Yes, is differs in another way: It does `z = β * conj(z)`. Thus it only has to handle the case `x == 1`. The case `x == -1` cannot occur, in contrast to the current julia implementation.

**Comment by cafaxo** [comment]
We can fix `atanh(prevfloat(-1.0) + 0im)` by multiplying z with the sign of x and then multiplying the result again with that sign, as in the paper. As we do not have to handle `x == -1` anymore, we can drop the copysign that this PR would currently introduct to fix the sign issue. This results in
```
julia> ccall(:catanh, ComplexF64, (ComplexF64,), prevfloat(-1.0) + 0im)
-18.36840028483855 + 1.5707963267948966im

julia> atanh(prevfloat(-1.0) + 0im)
-18.36840028483855 + 1.5707963267948966im
``` 
Should I add this change?

File: test/complex.jl [hunk 2]
```diff
@@ -1065,3 +1065,7 @@ end
 
     @test @inferred(2.0^(3.0+0im)) === @inferred((2.0+0im)^(3.0+0im)) === @inferred((2.0+0im)^3.0) === 8.0+0.0im
 end
+
+@testset "issue #31054" begin
+    @test tanh(atanh(-1.0+1.0im)) == -1.0+1.0im
```
Comment (simonbyrne) [inline test/complex.jl]: Test all four combinations?:
```suggestion
    @test tanh(atanh(complex(1.0,1.0))) == complex(1.0,1.0)
    @test tanh(atanh(complex(1.0,-1.0))) == complex(1.0,-1.0)
    @test tanh(atanh(complex(-1.0,1.0))) == complex(-1.0,1.0)
    @test tanh(atanh(complex(-1.0,-1.0))) == complex(-1.0,-1.0)
```

**Comment by stevengj** [comment]
I don't understand the rationale for the `ay+ρ` logic in the code (either Julia's or Kahan's).  Eliminating that seems to make the code more accurate as well as simpler.

In particular, consider the following example where our current code gives quite inaccurate results:
```
julia> atanh(1+2.98e-154im)
176.7528106982835 + 0.7853981633974483im

julia> tanh(atanh(1+2.98e-154im))
1.0 + 5.963336292480018e-154im
```

In contrast, `catanh(z) = ccall(:catanh, ComplexF64, (ComplexF64,), z)` gives accurate results
```jl
julia> catanh(1+2.98e-154im)
177.09966410056285 + 0.7853981633974483im

julia> tanh(catanh(1+2.98e-154im))
1.0 + 2.9799999999999177e-154im
```

And if I simplify our `atanh` implementation to just eliminate the `+ρ` factors, I get similarly accurate results:
```jl
function myatanh(z::Complex{T}) where T<:AbstractFloat
    Ω = prevfloat(typemax(T))
    θ = sqrt(Ω)/4
    x, y = reim(z)
    ax = abs(x)
    ay = abs(y)
    if ax > θ || ay > θ #Prevent overflow
        if isnan(y)
            if isinf(x)
                return Complex(copysign(zero(x),x), y)
            else
                return Complex(real(1/z), y)
            end
        end
        if isinf(y)
            return Complex(copysign(zero(x),x), copysign(oftype(y,pi)/2, y))
        end
        return Complex(real(1/z), copysign(oftype(y,pi)/2, y))
    elseif ax==1
        ξ = copysign(log(sqrt(sqrt(4+y*y))/sqrt(ay)), x)
        η = copysign(oftype(y,pi)/2 + atan(ay/2), y)/2
    else #Normal case
        ysq = ay^2
        ξ = log1p(4x/((1-x)^2 + ysq))/4
        η = angle(Complex((1-x)*(1+x)-ysq, 2y))/2
    end
    Complex(ξ, η)
end

julia> myatanh(1+2.98e-154im)
177.09966410056285 + 0.7853981633974483im

julia> tanh(myatanh(1+2.98e-154im))
1.0 + 2.9799999999999177e-154im
```

What problem does the `+ρ` supposedly solve?

**Comment by stevengj** [comment]
As a more minor matter, I also don't understand why we do `log(sqrt(sqrt(4+y*y))` rather than `log(4+y*y)/4`

**Comment by stevengj** [comment]
@cafaxo, I agree that flipping the sign seems like a good idea.

**Comment by StefanKarpinski** [comment]
This seems like a minor change to everyone on triage: technically breaking, but better, so we should change it but not backport that change. Keep in mind that users of long term support versions are super conservative and want their programs to keep working as is unless the previous behavior was so horribly wrong that it couldn't be working right.

**Comment by JeffBezanson** [comment]
Triage thinks we should not backport this to the LTS 1.0 release, since it causes different answers.

**Comment by simonbyrne** [comment]
That logic seems odd: it's breaking because it currently gives _the wrong result_.

**Comment by JeffBezanson** [comment]
In practice, not all wrong results are created equal. Some wrong results are so wrong that they could only cause breakage, whereas others just cause "different" answers. For example, a program might contain a (possibly unintentional) workaround for this issue. So it's a judgment call.

**Comment by chethega** [comment]
>I think we have at some point decided that throwing an appropriate error is more Julian than silently producing `NaN`. The exception is where something built-in gives `NaN` and, for performance, we don't do an extra check to throw instead. (`0.0/0.0` would be the prime example for the latter.)

Really? We take the effort to compute the right quadrant for `exp(Inf+1.6*im)`, return `NaN`s for `exp(3+Inf*im)`, and we prefer to throw on complex `atanh`, because the argument `arg_ = 4x/((1-x)^2+ysq)` to real `log1p` becomes less than one in floating point arithmetic for some arguments, even though `1+arg_ = ((1+x)^2 +ysq)/((1-x)^2 +ysq)` is nonnegative in real arithmetic? This looks very unintended to me.

**Comment by simonbyrne** [comment]
I don't quite understand what you mean by "different" answers. This is clearly a bug: it currently gives a result that is mathematically incorrect (i.e. it isn't a "there are multiple valid results" we should choose a different one case).

Anyway, consider this my formal appeal against the triage decision.

**Comment by simonbyrne** [comment]
> I think we have at some point decided that throwing an appropriate error is more Julian than silently producing `NaN`. The exception is where something built-in gives `NaN` and, for performance, we don't do an extra check to throw instead. (`0.0/0.0` would be the prime example for the latter.)

See #5234, which is still unresolved. We don't seem to do it for complex numbers though, e.g.
```
julia> sin(Inf)
ERROR: DomainError with Inf:
sin(x) is only defined for finite x.
Stacktrace:
 [1] sin_domain_error(::Float64) at ./special/trig.jl:28
 [2] sin(::Float64) at ./special/trig.jl:39
 [3] top-level scope at none:0

julia> sin(Inf+0.0*im)
NaN + 0.0im
```

**Comment by chethega** [comment]
Well, using `catanh(z) = ccall(:catanh, ComplexF64, (ComplexF64,), z)`:
```
julia> tanh(catanh(prevfloat(-1.0)+0.0im))
-1.0000000000000002 + 2.719262146893785e-32im
```
So I'd argue that this is an especially egregious precision error, where we throw `DomainError` instead of returning a perfectly fine and precise answer that is compatible with all our branch-cuts due to wrong handling of floating point arithmetic. No need for philosophical debates about `NaN` vs `DomainError`. 

I would consider any result close to `NaN`/`Inf` as kinda OK, though, because we are very close to a singularity.

**Comment by simonbyrne** [comment]
My general feeling is that "if you're doing complex arithmetic, you're going to get a few NaNs"

**Comment by cafaxo** [comment]
I have applied to two of the discussed changes.
@stevengj I get
```julia
julia> ccall(:catanh, ComplexF64, (ComplexF64,), complex(1.0, +0.0))
Inf + 0.0im

julia> ccall(:catanh, ComplexF64, (ComplexF64,), complex(1.0, -0.0))
Inf - 0.0im
```
on my machine. Should we change the behavior in that case anyway?
I have not dropped the `ρ`, but I also do not know why it is there.

**Comment by stevengj** [comment]
Hmm, the C99 standard says:
image
i.e. on your machine `catanh` is following the standard.  

* On the one hand, if we take the limit of `1+iε` as ε⟶±0 we get `∞±iπ/4`.
* On the other hand, it is nice to keep `atanh(complex(x,0.0))` equivalent to the real-argument case `atanh(x)`, which always returns a real result.
* Following the C99 standard for mathematical functions is usually a good thing in the absence of a compelling argument to the contrary.

So, I guess on balance it is probably better to be conservative here and stick with `η = y` for `ax == 1 && y == 0`.

**Comment by JeffBezanson** [comment]
Ok, triage might be wrong about this one.

**Comment by chethega** [comment]
Can't we just use a different expansion near `-1.0+0im`?  `if abs(x+1)+abs(y) < 1e-2 ξ = log((1+x)^2 +ysq)/((1-x)^2 +ysq)/4 end`, or something. 

Our expansion near that singularity is needlessly bad, which leads to rounding causing the `DomainError`. `log1p` is definitely the right expansion near `z=0`, and looks ok near `z=1+0im`.

**Comment by cafaxo** [comment]
The current Julia implementation mistranscribed the reference: The multiplication with the sign of x is missing (see https://github.com/JuliaLang/julia/pull/31061#issuecomment-463653341). This PR currently adds that multiplication back, fixing both the original sign issue and the problems near `z=-1+0im`.

**Comment by StefanKarpinski** [comment]
Should this also add some tests of for `x ± 0.0im` values to make sure that the branch cuts are correct?

**Comment by simonbyrne** [comment]
There are a bunch of branch cut and limit tests here:
https://github.com/JuliaLang/julia/blob/dfee9457c0fa218501fdc4f752451200cff1e5fa/test/complex.jl#L684-L730
so can add those there.

**Comment by StefanKarpinski** [comment]
I guess they were not incorrect previously then. Carry on.

**Comment by cafaxo** [comment]
I have added test for the cases that were fixed by replacing `η = zero(y)` with `η = y`.

**Comment by simonbyrne** [comment]
Looks like the CI failures are due to getting slightly different values here:
https://github.com/JuliaLang/julia/blob/e5e1253b5ec4ed3fb5b6e12f72dda1dd4348e667/stdlib/LinearAlgebra/src/dense.jl#L927-L930

**Review by stevengj — APPROVED** [review]

**Comment by simonbyrne** [comment]
Thanks @cafaxo!

**Comment by StefanKarpinski** [comment]
It would be nice to clean up the commit message when squashing this kind of PR. The GitHub UI makes it quite easy to do—you just need to edit the message in the web interface.

**Comment by simonbyrne** [comment]
Good point, will do in future.

**Comment by fp4code** [comment]
A partial backport should be done! This is not about the choice of the cut, just
    tanh(atanh(-1.0 + 0.1im)) ≈ 1.0 + 0.1im
**is a wrong result**!
