### PR TITLE
Use correct module when printing code_llvm for opaque closures

### LINKED ISSUE #51842: OpaqueClosures cause the LLVM verifier to error or segfault
For example:
```
julia> code_llvm(()) do; Base.Experimental.@opaque(@noinline x::Int->println(x))(1) end                                                                                                                                                                                                          
Global is referenced in a different module!                                                                                                                                                                                                                                                      
{}* @"*Main.Base.println#491.jit"                           
; ModuleID = '#9'                                                                                                                               
  %"*Main.Base.println#491" = load {}*, {}** @"*Main.Base.println#491", align 8, !dbg !DILocation(line: 1, scope: <0x556b30a08d70>), !tbaa !27, !invariant.load !0, !alias.scope !29, !noalias !30                                                                                               
void ({} addrspace(11)*, i64)* @"julia_opaque closure_489"                                                                                      
; ModuleID = 'opaque closure'                                                                                                                   
Failed to verify module '#9', dumping entire module!                                                                                            
```

### PR DESCRIPTION
**Pull request by gbaraldi**
Another way to fix this is to only look at the globals in `m` instead of globals_target. 

Fixes https://github.com/JuliaLang/julia/issues/51842

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: test/opaque_closure.jl [hunk 1]
```diff
@@ -347,3 +347,5 @@ let ir = Base.code_ircode((Int,Int)) do x, y
     code_llvm(io, oc, (Int,Int))
     @test occursin("j_*_", String(take!(io)))
 end
+                                                        
+code_llvm(()) do; Base.Experimental.@opaque(@noinline x::Int->println(x))(1) end #Shouldn't crash
```
Comment (vtjnash) [inline test/opaque_closure.jl:351]:
```suggestion

code_llvm(()) do; Base.Experimental.@opaque(@noinline x::Int->println(x))(1) end #Shouldn't crash
```
