### PR TITLE
Fix gc_setmark size for strings

### LINKED ISSUE #20360: segfault creating large string
Reported by @ScottPJones on [discourse](https://discourse.julialang.org/t/segmentation-fault-trying-to-create-a-large-string-on-v0-6-0-dev-2486/1807), reproduced by me on MacOS X.   Not an out-of-memory problem (this is on a machine with 16GB of RAM, and `String(Vector{UInt8}(2^33))` works fine on 0.5).

```julia
julia> String(Vector{UInt8}(2^32));

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
gc_setmark_pool_ at /Users/stevenj/Documents/Code/julia/src/gc.c:518 [inlined]
gc_setmark_pool at /Users/stevenj/Documents/Code/julia/src/gc.c:544
gc_setmark at /Users/stevenj/Documents/Code/julia/src/gc.c:553 [inlined]
gc_mark_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1563 [inlined]
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1206
gc_mark_stack at /Users/stevenj/Documents/Code/julia/src/gc.c:1303
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1477
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_mark_stack at /Users/stevenj/Documents/Code/julia/src/gc.c:1303
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1477
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1463
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_mark_module at /Users/stevenj/Documents/Code/julia/src/gc.c:1242
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1473
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1430
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1430
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1430
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1430
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1492
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_mark_module at /Users/stevenj/Documents/Code/julia/src/gc.c:1242
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1473
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
gc_mark_module at /Users/stevenj/Documents/Code/julia/src/gc.c:1242
gc_scan_obj at /Users/stevenj/Documents/Code/julia/src/gc.c:1473
gc_push_root at /Users/stevenj/Documents/Code/julia/src/gc.c:1209
jl_gc_mark_thread_local at /Users/stevenj/Documents/Code/julia/src/gc.c:1591 [inlined]
_jl_gc_collect at /Users/stevenj/Documents/Code/julia/src/gc.c:1809
jl_gc_collect at /Users/stevenj/Documents/Code/julia/src/gc.c:1969
jl_gc_pool_alloc at /Users/stevenj/Documents/Code/julia/src/gc.c:856
eval_user_input at ./REPL.jl:69
unknown function (ip: 0x10ec71566)
jl_apply_generic at /Users/stevenj/Documents/Code/julia/src/gf.c:2217
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x10ec689ef)
jl_apply_generic at /Users/stevenj/Documents/Code/julia/src/gf.c:2217
jl_apply at /Users/stevenj/Documents/Code/julia/src/./julia.h:1411 [inlined]
start_task at /Users/stevenj/Documents/Code/julia/src/task.c:261
Allocations: 1650210 (Pool: 1649033; Big: 1177); GC: 1
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by yuyichao**
This is only an issue for strings since normal object cannot be this big.

Fix #20360

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -4609,3 +4609,27 @@ end
 
 # issue #19963
 @test_nowarn ccall(:jl_free, Void, (Ptr{Void}, ), C_NULL)
+
+# Wrong string size on 64bits for large string.
+if Sys.WORD_SIZE == 64
+    @noinline function test_large_string20360(slot)
+        try
+            slot[] = Base._string_n(2^32)
```
Comment (tkelman) [inline test/core.jl]: is this expected to always pass, never pass, or depend on how much memory you have? does running this test require several gigs of memory?

Comment (yuyichao) [inline test/core.jl]: The hope is that it can always work, which is why a much lower level function is used to allocate the string. FWIW, this is smaller than the default heap size we use.
The allocation should success unless a tight VM limit is set, in which case it should raise a OOM error and pass the test.
Without touching the string, we shouldn't trigger the OOM killer after the allocation succeeded and the OS should usually happily hand back a large number of COW zero pages with only the first page dirty due to metadata stored in there. The `tester` function makes sure that the allocation is free'd immediately afterwards.

Comment (tkelman) [inline test/core.jl]: a subset of that would be good as comments so people don't mess up the try-catch by accident

Comment (yuyichao) [inline test/core.jl]: ....... Sure. Though I'll be very surprised if anyone will mess up the try-catch by accident if he reads any part of it. The type check on the error should be very obvious what it is guarding against......
