### PR TITLE
Check that file being precompiled contains a module

### LINKED ISSUE #45832: Loading package outside of main module when precompiling could have better error message
Brought up on Zulip; the following package code:
```
$ cat src/TestPackage.jl
using Example

module TestPackage

end # module
```
gives a rather bizarre error:
```
$ julia -e 'using TestPackage'
ERROR: LoadError: ArgumentError: Package Base does not have Example in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have Base checked out for development and have
  added Example as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Base
Stacktrace:
```

Perhaps code outside the main module should be ignored altogether, or have a descriptive error? In any case, the error message above should be improved.

### LINKED ISSUE #51626: Improve error message when extension file does not contain module
I just tried to create a package extension, but forgot to wrap the code in the extension file in its own module. I got an error saying:
```
[ Info: Precompiling TestExt [29286dec-c893-52d1-88fe-e07e79eb4405]
ERROR: LoadError: ArgumentError: Package Base does not have Test in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have Base checked out for development and have
  added Test as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Base
Stacktrace:
 [1] macro expansion
   @ Base ./loading.jl:1770 [inlined]
 [2] macro expansion
   @ Base ./lock.jl:267 [inlined]
 [3] __require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1747
```
IMO this error is pretty confusing because it claimed I was trying to load `Test` from `Base`, whereas in fact, I tried loading it in my extension module.

### PR DESCRIPTION
**Pull request by IanButterworth**
Proposal to catch when a `module` declaration is either missing, or after a `using/import` earlier and provide clearer error messages.

Fixes https://github.com/JuliaLang/julia/issues/51626
Fixes https://github.com/JuliaLang/julia/issues/45832

### CODE REVIEW

**Comment by vtjnash** [comment]
Seems fine. Also see https://github.com/JuliaLang/julia/pull/43257 for an idea of how to solve this entirely, though I couldn't quite find solutions yet to some problems it had

File: base/loading.jl [hunk 1]
```diff
@@ -2249,6 +2249,9 @@ end
 # this is called in the external process that generates precompiled package files
 function include_package_for_output(pkg::PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String},
                                     concrete_deps::typeof(_concrete_dependencies), source::Union{Nothing,String})
+    if !occursin("module ", readuntil(input, "module ", keep = true))
+        throw(ErrorException("Package $pkg source file $input does not contain a module."))
+    end
```
Comment (fatteneder) [inline base/loading.jl:2254]: Perhaps a more robust solution that respects comments and allows for a macro
```julia
rgx = r"^\s*(?:@\w*\s*)module"m
if occursin(input, rgx)
  throw(ErrorException("Package $pkg source file $input does not contain a module."))
end
```

**Comment by fredrikekre** [comment]
Fixes #45832 as well I suppose?

File: base/loading.jl (hunk 1 above)
Comment (IanButterworth) [reply base/loading.jl:2254]: Input is a path and there's no `readuntil` that takes a regex. Also it should accept baremodule I think.

Comment (fatteneder) [reply base/loading.jl:2254]: Upsi.
This here would work with a filename
```julia
    rgx = r"^\s*(?:@\w*\s*)*(?:bare)?module"
    if !any(l -> contains(l, rgx), eachline(input))
        # throw
    end
```

Comment (IanButterworth) [reply base/loading.jl]: Added, thanks!

**Comment by IanButterworth** [comment]
@fredrikekre it didn't quite, but it should now

**Comment by maleadt** [comment]
Would have been good to run PkgEval here (and file upstream PRs) as this broke a couple of packages:
- https://gitlab.com/aplavin/RectiGrids.jl/-/blob/010000040eadd19b1e950a9d66df4d483808f202/src/RectiGrids.jl#L1-4
- https://github.com/TorkelE/Why.jl/blob/746b8a09e7c00c45bc20d53d5f6e3f1efd6691f4/src/Why.jl#L1-L3
- https://github.com/hsugawa8651/ExtendedKronigPennyMatrix.jl/blob/3e738eede458b62f7f238175cdb9d840025a98f0/src/ExtendedKronigPennyMatrix.jl#L1-L6
- https://github.com/oscar-system/GAP.jl/blob/5aa8c47d71d101c85ac3fe8416c77b2846084353/src/GAP.jl#L1-L8

**Comment by IanButterworth** [comment]
Yeah, I assumed too much. Updates:

- [gitlab.com/aplavin/RectiGrids.jl/-/blob/010000040eadd19b1e950a9d66df4d483808f202/src/RectiGrids.jl#L1-4](https://gitlab.com/aplavin/RectiGrids.jl/-/blob/010000040eadd19b1e950a9d66df4d483808f202/src/RectiGrids.jl#L1-4)
 (allowed by https://github.com/JuliaLang/julia/pull/51689)
- [TorkelE/Why.jl@746b8a0/src/Why.jl#L1-L3](https://github.com/TorkelE/Why.jl/blob/746b8a09e7c00c45bc20d53d5f6e3f1efd6691f4/src/Why.jl#L1-L3)
 (already fixed on master)
- [hsugawa8651/ExtendedKronigPennyMatrix.jl@3e738ee/src/ExtendedKronigPennyMatrix.jl#L1-L6](https://github.com/hsugawa8651/ExtendedKronigPennyMatrix.jl/blob/3e738eede458b62f7f238175cdb9d840025a98f0/src/ExtendedKronigPennyMatrix.jl#L1-L6)
 (https://github.com/hsugawa8651/ExtendedKronigPennyMatrix.jl/pull/32)

**Comment by maleadt** [comment]
Thanks!
