### PR TITLE
remove precompile mutation step from staticdata

### LINKED ISSUE #48047: Missing backedge somewhere on master?
It appears that something around backedge tracking broke somewhat recently (I'm assuming with pkgimages, but haven't bisected yet). In particular, changing Core.Compiler no longer gets picked up by Cthulhu. To reproduce, apply a patch to base/compiler, e.g.
```
diff --git a/base/compiler/abstractinterpretation.jl b/base/compiler/abstractinterpretation.jl
index b3e18a6ee7..fc8e2d1aee 100644
--- a/base/compiler/abstractinterpretation.jl
+++ b/base/compiler/abstractinterpretation.jl
@@ -547,6 +547,8 @@ function abstract_call_method(interp::AbstractInterpreter, method::Method, @nosp
         return MethodCallResult(Any, false, false, nothing, Effects())
     end
 
+    @show sig
+
     # Limit argument type tuple growth of functions:
     # look through the parents list to see if there's a call to the same method
     # and from the same method.
```

This will not show up in Cthulhu:
```
julia> using Revise

julia> Revise.track(Core.Compiler)

julia> using Cthulhu

julia> @descend optimize=false sin(1.0)
[snip]
sin(x::T) where T<:Union{Float32, Float64} @ Base.Math special/trig.jl:29
```

However, if I force-reevaluate `do_typeinf!`, it does show up:
```
julia> Core.eval(Cthulhu, quote
       function do_typeinf!(interp::AbstractInterpreter, mi::MethodInstance)
           result = InferenceResult(mi)
           # we may want to handle the case when `InferenceState(...)` returns `nothing`,
           # which indicates code generation of a `@generated` has been failed,
           # and show it in the UI in some way ?
           # branch on https://github.com/JuliaLang/julia/pull/42082
           frame = @static hasmethod(InferenceState, (InferenceResult,Symbol,AbstractInterpreter)) ?
                   InferenceState(result, #=cache=# :global, interp)::InferenceState :
                   InferenceState(result, #=cached=# true, interp)::InferenceState
           CC.typeinf(interp, frame)
           return nothing
       end
       end)

julia> @descend optimize=false sin(1.);
:sig = Tuple{typeof(Base.abs), Float64}
:sig = Tuple{Type{Float64}, Base.Irrational{:π}}
:sig = Tuple{typeof(Base.:(/)), Float64, Int64}
:sig = Tuple{typeof(Base.promote), Float64, Int64}
:sig = Tuple{typeof(Base._promote), Float64, Int64}
```

This suggests that there is some cached version of `do_typeinf!` that fails to notice the revision of the Core.Compiler method. @timholy any ideas - is this known?

### PR DESCRIPTION
**Pull request by vtjnash**
Make sure things are properly ordered here, so that when serializing, nothing is mutating the system at the same time.

Fix #48047

### CODE REVIEW

File: src/gf.c [hunk 1]
```diff
@@ -281,11 +281,9 @@ jl_code_info_t *jl_type_infer(jl_method_instance_t *mi, size_t world, int force)
...
     jl_task_t *ct = jl_current_task;
     if (ct->reentrant_inference == (uint16_t)-1) {
-        // TODO: We should avoid attempting to re-inter inference here at all
-        // and turn on this warning, but that requires further refactoring
-        // of the precompile code, so for now just catch that case here.
-        //jl_printf(JL_STDERR, "ERROR: Attempted to enter inference while writing out image.");
-        return NULL;
+        // We must avoid attempting to re-enter inference here
+        assert(0 && "attempted to enter inference while writing out image");
+        abort();
```
Comment (Keno) [inline src/gf.c:286]: aborting here in non-debug mode seems a bit aggressive. Generally the image may still be ok even if this fails, and it seems unfriendly to the user to not try and continue.

Comment (vtjnash) [reply src/gf.c:286]: There is not really any points in this code that would be calling back into julia now, so I had considered deleting this special flag, but I did want to make it hard for someone to introduce the same mistake again. In most later places, the image might also not be complete, which also seemed more aggravating to encounter for the user than a clear abort and backtrace from the source of the problem

**Review by timholy — APPROVED** [review]
LGTM. I also favor the assert.

~~Is the external methodtable the main fix, and most of the rest (nice) cleanup? I like both the conditional-`edges` allocation and the typemap visitor pattern.~~  Oh nvm, I now see you're calling `jl_prepare_serialization_data` twice as in https://github.com/JuliaLang/julia/pull/48054#issuecomment-1372822970
