### PR TITLE
base/stat.jl: Mask `UV_EINVAL` error codes for `jl_stat`

### LINKED ISSUE #26685: isfile() now throws an error on Windows
On Windows, `isfile()` now throws an error when given an "invalid argument".

On 0.6:
```
julia> isfile("http://google.com")
false
```

On 0.7:
```
julia> isfile("http://google.com")
ERROR: stat: invalid argument (EINVAL)
Stacktrace:
 [1] stat(::String) at .\stat.jl:68
 [2] isfile(::String) at .\stat.jl:303
 [3] top-level scope
```

### PR DESCRIPTION
**Pull request by staticfloat**
This fixes https://github.com/JuliaLang/julia/issues/26685, where libuv decided to throw `UV_EINVAL` on windows for invalid-filepaths such as `foo??` or `http://google.com`, instead of returning `UV_ENOENT` as they were previously [0].  This causes windows to throw errors on calls such as `isfile("http://google.com")`, whereas other platforms simply return `false`.  This change simply ignores `UV_EINVAL` alongside the other "allowed failure" error codes.

[0] https://github.com/libuv/libuv/pull/1088

### CODE REVIEW

File: base/stat.jl [hunk 1]
```diff
@@ -65,7 +65,9 @@ macro stat_call(sym, arg1type, arg)
     return quote
         stat_buf = zeros(UInt8, ccall(:jl_sizeof_stat, Int32, ()))
         r = ccall($(Expr(:quote, sym)), Int32, ($(esc(arg1type)), Ptr{UInt8}), $(esc(arg)), stat_buf)
-        r == 0 || r == Base.UV_ENOENT || r == Base.UV_ENOTDIR || throw(_UVError("stat", r))
+        if !(r in (0, Base.UVENOENT, Base.UV_ENOTDIR, Base.UVEINVAL))
```
Comment (vtjnash) [inline base/stat.jl]:
```suggestion
        if !(r in (0, Base.UV_ENOENT, Base.UV_ENOTDIR, Base.UV_EINVAL))
```

**Comment by musm** [comment]
This explains the mysterious error I was getting which let to the ugly `try` `catch` stuff in https://github.com/JuliaLang/julia/pull/32369

**Comment by musm** [comment]
can we merge this? Probably also needs backports labels..

**Comment by musm** [comment]
Ok I can now confirm the buildbot failures are unrelated. This seems good to merge then.
