### PR TITLE
Fix option -p 1, support -p auto

### LINKED ISSUE #10414: -p option regression
Two issues:

1. `julia -p 1` does not launch an additional worker
2. Plain `julia -p` or even `julia -p auto` should launch as many workers as the number of cores

### PR DESCRIPTION
**Pull request by amitmurthy**
Closes #10414

@jakebolewski , could you please take a look?

### CODE REVIEW

**Comment by amitmurthy** [comment]
AppVeyor error is unrelated.

**Comment by jakebolewski** [comment]
Maybe `all` instead of `auto`?  Otherwise lgtm.

File: ui/repl.c [hunk 1]
```diff
@@ -186,9 +187,14 @@ void parse_opts(int *argcp, char ***argvp)
             break;
         case 'p': // procs
             errno = 0;
-            jl_options.nprocs = strtol(optarg, &endptr, 10);
-            if (errno != 0 || optarg == endptr || *endptr != 0 || jl_options.nprocs < 1)
-                jl_errorf("julia: -p,--procs=<n> must be an integer >= 1\n");
+            if (!strcmp(optarg,"auto")) {
+                jl_options.nprocs = jl_cpu_cores();
```
Comment (jakebolewski) [inline ui/repl.c]: If this is spinning up N additional workers, shouldn't this be `jl_cpu_cores() - 1`?

Comment (amitmurthy) [inline ui/repl.c]: It refers to additional worker processes. Since the master will be the driver and not used for computation, it makes sense to fire up as many workers as cores.

**Comment by amitmurthy** [comment]
The term `auto` is used both in the machinefile format and addprocs via ssh. Better to be consistent about it.

**Comment by jakebolewski** [comment]
Thanks for fixing this.
