### PR TITLE
Fix `fieldtype_tfunc` for union types

### LINKED ISSUE #40177: A "fatal error in type inference (type bound)" in Julia 1.6.0-rc3 and 1.7.0-DEV.749
I'm getting `fatal error in type inference (type bound)` from the following program (extracted from [an old version of UnionArrays.jl](https://github.com/JuliaFolds/UnionArrays.jl/blob/e28437c0263f6a975c60b7abfb10e7639f90c3d6/src/impl/vectors.jl#L62)) when executed with Julia 1.6.0-rc3 and 1.7.0-DEV.749:

```julia
module MWE

function maybe_sizeof(T::Type)
    if isbitstype(T)
        return Core.sizeof(T)
    else
        return nothing  # this path is not expected to be taken
    end
end

foldltupletype(op, ::Type{T}, ::Type{<:Tuple{}}) where T = T
foldltupletype(op, ::Type{T}, ::Type{S}) where {T, S <: Tuple} =
    foldltupletype(op, op(T, Base.tuple_type_head(S)), Base.tuple_type_tail(S))

buffereltypefor(::Type{ETS}) where {ETS <: Tuple} =
    foldltupletype(Nothing, ETS) do S, T
        if maybe_sizeof(S) < maybe_sizeof(T)
            T
        else
            S
        end
    end

end # module MWE

MWE.buffereltypefor(Union{Tuple{Val{1}}, Tuple{Tuple{NTuple{9, Int64}}}})
```

Arguably, this is a misuse of the internal (now even deprecated) functions `tuple_type_tail` etc.; i.e., the code above was meant to process non-union `Tuple` types. So maybe it cannot be considered as a bug? At the same time, the behavior in Julia 1.5 is a bit more forgiving (although I'm not sure if that's a side effect of `tuple_type_head` marked as pure back then?):

```
ERROR: LoadError: MethodError: no method matching isless(::Int64, ::Nothing)
Closest candidates are:
  isless(::Missing, ::Any) at missing.jl:87
  isless(::Real, ::AbstractFloat) at operators.jl:166
  isless(::Real, ::Real) at operators.jl:355
  ...
Stacktrace:
 [1] <(::Int64, ::Nothing) at ./operators.jl:277
 [2] (::Main.MWE.var"#1#2")(::Type{T} where T, ::Type{T} where T) at /home/arakaki/repos/scratch/2021/scratch/03/24-173828.jl:18
 [3] foldltupletype(::Main.MWE.var"#1#2", ::Type{Nothing}, ::Type{Union{Tuple{Val{1}}, Tuple{Tuple{NTuple{9,Int64}}}}}) at /home/arakaki/repos/scratch/2021/scratch/03/24-173828.jl:13
 [4] buffereltypefor(::Type{Union{Tuple{Val{1}}, Tuple{Tuple{NTuple{9,Int64}}}}}) at /home/arakaki/repos/scratch/2021/scratch/03/24-173828.jl:16
```

I wonder if there is a way to make the type inference more robust to code like this?

### PR DESCRIPTION
**Pull request by martinholters**
On master:
```julia
julia> T = Union{Tuple{Val}, Tuple{Tuple}}
Union{Tuple{Val}, Tuple{Tuple}}

julia> fieldtype(T, 1)
Union{Tuple, Val}

julia> Core.Compiler.fieldtype_tfunc(Core.Const(T), Core.Const(1))
Union{Type{Val}, Type{Tuple}} # should be Type{Union{Tuple, Val}}
```
I tried to be conservative here in the sense that in cases where this PR changes the result, it is actually for the better, but there may be cases left where `fieldtype_tfunc` remains unsound for `Type{Union{...}}` input.

Fixes #40177.

### CODE REVIEW

File: base/compiler/tfuncs.jl [hunk 1]
```diff
@@ -1015,8 +1015,17 @@ function _fieldtype_tfunc(@nospecialize(s), exact::Bool, @nospecialize(name))
...
+        tb0 = _fieldtype_tfunc(rewrap(u.b, s), exact, name)
+        ta, exacta, _, istypea = instanceof_tfunc(ta0)
+        tb, exactb, _, istypeb = instanceof_tfunc(tb0)
+        if exact && exacta && exactb
+            return Const(Union{ta, tb})
+        end
+        if istypea && istypeb
+            return Type{<:Union{ta, tb}}
+        end
+        return tmerge(ta0, tb0)
```
Comment (vtjnash) [inline base/compiler/tfuncs.jl:1028]:
```suggestion
        return Any
```

**Review by JeffBezanson — APPROVED** [review]

File: base/compiler/tfuncs.jl (hunk 1 above)
Comment (martinholters) [reply base/compiler/tfuncs.jl]: Yes, that would certainly be sound, but might loose a bit too much precision? In particular, e.g. this test then fails:
https://github.com/JuliaLang/julia/blob/61b6994884642f8fc7e18844d37dc70b9dfdb9ab/test/compiler/inference.jl#L679

Comment (martinholters) [reply base/compiler/tfuncs.jl]: Oh, I missed that Jeff had committed that suggestion. Should we turn that test into a `@test_broken` or is there something which is both sound and sufficiently precise?

File: base/compiler/tfuncs.jl [hunk 2]
```diff
@@ -1015,8 +1015,17 @@ function _fieldtype_tfunc(@nospecialize(s), exact::Bool, @nospecialize(name))
     exact = exact && !has_free_typevars(s)
     u = unwrap_unionall(s)
     if isa(u, Union)
-        return tmerge(_fieldtype_tfunc(rewrap(u.a, s), exact, name),
-                      _fieldtype_tfunc(rewrap(u.b, s), exact, name))
+        ta0 = _fieldtype_tfunc(rewrap(u.a, s), exact, name)
+        tb0 = _fieldtype_tfunc(rewrap(u.b, s), exact, name)
+        ta, exacta, _, istypea = instanceof_tfunc(ta0)
```
Comment (vtjnash) [inline base/compiler/tfuncs.jl:1020]: Perhaps this would be valid?
```suggestion
        ta0 ⊑ tb0 && return tb0
        tb0 ⊑ ta0 && return ta0
        ta, exacta, _, istypea = instanceof_tfunc(ta0)
```

File: base/compiler/tfuncs.jl (hunk 1 above)
Comment (JeffBezanson) [reply base/compiler/tfuncs.jl]: Maybe we want `(istypea || ta === Union{})`? I think that's the only remaining case here we would want to handle with `tmerge`?

File: base/compiler/tfuncs.jl (hunk 2 above)
Comment (martinholters) [reply base/compiler/tfuncs.jl:1020]: Sounds good. I had tried with "if one is Bottom, return the other" which also does the trick, but this seems even better.

File: base/compiler/tfuncs.jl (hunk 1 above)
Comment (martinholters) [reply base/compiler/tfuncs.jl]: I think Jameson's proposal (https://github.com/JuliaLang/julia/pull/41667#discussion_r674232647) is quite an elegant solution.

**Comment by martinholters** [comment]
I think the CI failure on FreeBSD is unrelated/also seen elsewhere? Then this should be good to go.
