### PR TITLE
fix `code_warntype` on `OpaqueClosure`s

### LINKED ISSUE #54375: `@code_warntype` on `OpaqueClosure` throws.
```
julia> g = Base.Experimental.@opaque Tuple{Float64} x -> 0.0
(::Float64)::Float64->◌

julia> @code_warntype g(1.0)
ERROR: type OpaqueClosure has no field nargs
Stacktrace:
 [1] getproperty
   @ ./Base.jl:49 [inlined]
 [2] code_warntype(io::Base.TTY, f::Any, tt::Any; world::UInt64, interp::Core.Compiler.NativeInterpreter, debuginfo::Symbol, optimize::Bool, kwargs::@Kwargs{})
   @ InteractiveUtils ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/InteractiveUtils/src/codeview.jl:156
 [3] code_warntype(io::Base.TTY, f::Any, tt::Any)
   @ InteractiveUtils ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/InteractiveUtils/src/codeview.jl:146
 [4] code_warntype(::Any, ::Vararg{Any}; kwargs...)
   @ InteractiveUtils ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/InteractiveUtils/src/codeview.jl:173
 [5] top-level scope
   @ REPL[12]:1
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/54375

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]

File: stdlib/InteractiveUtils/test/runtests.jl [hunk 1]
```diff
@@ -770,3 +770,8 @@ end
 @testset "Docstrings" begin
     @test isempty(Docs.undocumented_names(InteractiveUtils))
 end
+
+@testset "code_warntype OpaqueClosure" begin
+    g = Base.Experimental.@opaque Tuple{Float64} x -> 0.0
+    @test warntype_hastag(g, Tuple{Float64}, "::Float64")
+end
```
Comment (aviatesk) [inline stdlib/InteractiveUtils/test/runtests.jl:777]: We need to have this code before `end # module WarnType`
