### PR TITLE
Loosen the signature on indices passed to _flatten. Fixes #17275.

### LINKED ISSUE #17275: getindex slice fails with CartesianIndex for v0.5
Hello, 

In a `NamedArrays` test I needed cartesian indexing for displaying arrays with `ndims()>2`.  In v0.4 this construction works:
```julia
a = rand(2,2,2)
a[:, :, CartesianIndex((1,))]
```
but in v0.5 (0.5.0-dev+5154) I get
```
ERROR: MethodError: no method matching _flatten(::Tuple{}, ::Colon, ::Colon, ::CartesianIndex{1})
Closest candidates are:
  _flatten(::Any, ::Integer, ::Any...)
  _flatten(::Any, ::CartesianIndex{N}, ::Any...)
  _flatten(::Any)
 in getindex(::Array{Float64,3}, ::Colon, ::Colon, ::CartesianIndex{1}) at ./abstractarray.jl:701
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

### PR DESCRIPTION
**Pull request by timholy**
Ref #17275.

### CODE REVIEW

File: base/multidimensional.jl [hunk 1]
```diff
@@ -27,10 +27,11 @@ CartesianIndex{N}(index::NTuple{N,Integer}) = CartesianIndex{N}(index)
 (::Type{CartesianIndex{N}}){N}(index::Integer...) = CartesianIndex{N}(index)
 (::Type{CartesianIndex{N}}){N}() = CartesianIndex{N}(())
 # Un-nest passed CartesianIndexes
-CartesianIndex(index::Union{Integer, CartesianIndex}...) = CartesianIndex(_flatten((), index...))
-_flatten(out) = out
-@inline _flatten(out, i::Integer, I...)        = _flatten((out..., i), I...)
-@inline _flatten(out, i::CartesianIndex, I...) = _flatten((out..., i.I...), I...)
+CartesianIndex(index::Union{Integer, CartesianIndex}...) = CartesianIndex(flatten(index))
+Base.@pure flatten(I) = (_flatten(I...)...,)
```
Comment (tkelman) [inline base/multidimensional.jl]: is this different than the `flatten` in `iterators.jl` ?

Comment (timholy) [inline base/multidimensional.jl]: It produces the same outcome, but it's non-lazy. Note that I'm not importing `Base.flatten`, so this doesn't "globally" extend `flatten`.

Comment (vtjnash) [inline base/multidimensional.jl]: fwiw, I think a `pure` function should usually not be extended, but I'm not certain.

Comment (timholy) [inline base/multidimensional.jl]: You mean, there should be only one method?

Comment (vtjnash) [inline base/multidimensional.jl]: perhaps. although more importantly, external code need to be careful about how they overload it (e.g. don't write code that could trigger a #265-style error)

Comment (timholy) [inline base/multidimensional.jl]: For sure. Come to think of it, I don't need the `@pure` annotation on `_flatten`, just on `flatten`. (right?)

The only reason it was marked pure is because of #17126, but this `flatten` has since been redesigned several times, and in testing with this version I'm getting equal performance with `@inline`. So I'll change it.
