### PR TITLE
fix macroexpansion scope miscalculation

### LINKED ISSUE #23239: at-evalpoly is broken
The following works fine in 0.6:
```
julia> f(x) = @evalpoly x 1.0 2.0 3.0
f (generic function with 1 method)

julia> Base.Test.@inferred f(3.0)
ERROR: return type Float64 does not match inferred return type Any
Stacktrace:
 [1] error(::String) at ./error.jl:28
```
Probably the same as JuliaMath/SpecialFunctions.jl#42, where it was bisected to #22985.

cc @vtjnash

### PR DESCRIPTION
**Pull request by vtjnash**
previously, we were treating hygienic-scope as also introducing a new scope-block
that was wrong (and inconsistent with previous behavior)

also, we were failing to set the outermost flag when entering a
hygienic-scope block, further compounding the above error

fix #23239

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I'm hoping this also changes the behavior of the test at https://github.com/JuliaLang/julia/blob/131807cc574bc8452b463247d4903d2eb6cfec6b/test/parse.jl#L784

File: test/parse.jl [hunk 1]
```diff
@@ -771,19 +771,26 @@ macro iter()
...
+    @test local_foo16096(2.0) == 1
     @test !@isdefined foo16096
-    @test isdefined(M16096, :foo16096)
+    @test !@isdefined it
+    @test !isdefined(M16096, :foo16096)
+    @test !isdefined(M16096, :it)
+    @test_broken typeof(local_foo16096).name.module === M16096
+    @test_broken typeof(local_foo16096).name.mt.module === M16096
+    @test_broken getfield(M16096, typeof(local_foo16096).name.mt.name) === local_foo16096
+    @test_broken !isdefined(@__MODULE__, typeof(local_foo16096).name.mt.name)
```
Comment (JeffBezanson) [inline test/parse.jl]: I actually don't think the current behavior is broken. I interpret the purpose of this macro as defining a method in the caller's module. If you consider e.g. the `vectorize` macros, if my module defines `foo` and I write `@vectorize_1arg foo`, I want it to add a new method in my module, not in Base.

File: src/macroexpand.scm [hunk 2]
```diff
@@ -407,10 +407,30 @@
                      (and (eq? (car e) '=) (length= e 3)
                           (eventually-call? (cadr e))))))
 
+;; count hygienic / escape pairs
+;; and fold together a list resulting from applying the function to
+;; and block at the same hygienic scope
```
Comment (tkelman) [inline src/macroexpand.scm]: is this supposed to say "applying the function to a block at the same hygienic scope" ?

**Comment by stevengj** [comment]
For completeness, can we add a test specifically for the `@evalpoly` inference issue in #23239, and another test for the correctness issue identified in [this comment](https://github.com/JuliaLang/julia/issues/23239#issuecomment-322460258) by @dlfivefifty?

File: test/parse.jl (hunk 1 above)
Comment (vtjnash) [inline test/parse.jl]: Hygiene means that you either need `esc` (so hygiene rules don't apply), or it'll gensym the name (so you'll define `#1#foo#`). I suppose either case is actually OK to me. I was thinking it might make more sense to not be creating a global with a gensym name – but the goal of this PR was only to restore the v0.6 behavior for these cases, not propose changes.

Comment (JeffBezanson) [inline test/parse.jl]: No matter what the name is, the type introduced by this macro should be in the caller's module, not `M16096`. I'm not proposing a behavior change, just that this test should be inverted and `test_broken` should be changed to `test`.

Comment (vtjnash) [inline test/parse.jl]: > as defining a method in the caller's module

Also, fwiw, it's best to be precise in terminology, since this test has nothing to do with `Method`, but instead is testing for the properties of the function's type. Macroexpand (and expand in general) would require severe contortions (spliced in calls to `eval`) to affect that property. This instead is testing specifically for whether the macro added a new global bindings (and where).

**Comment by vtjnash** [comment]
@stevengj Yes, that case was reduced to create the tests added to core.jl (including the `@inferred`): https://github.com/JuliaLang/julia/pull/23247/files#diff-75b23cc61d190dd99feab17b8e297ee3R5005

File: test/parse.jl (hunk 1 above)
Comment (JeffBezanson) [inline test/parse.jl]: Types always have global bindings. Hygiene can only affect whether the function object has a global name, which is not the issue here.

**Comment by ararslan** [comment]
Any idea whether this also fixes BenchmarkTools?

**Comment by ararslan** [comment]
Doesn't appear to. Was it intended to?

**Comment by ararslan** [comment]
...I'll take that as a no then?

**Comment by quinnj** [comment]
I think @vtjnash mentioned elsewhere that this would be a partial fix, but not all the way.

**Comment by ararslan** [comment]
Okay thanks, I didn't see that.
