### PR TITLE
fix #16783, closure conversion in typeassert for var with declared type

### LINKED ISSUE #16783: Lowering bug when local is the RHS of a typeassert
```
function foo()
    T = UInt32
    x::T = 0
    bar() = x+1
end
```

```
julia> foo()()
ERROR: UndefVarError: T not defined
 in (::#bar#2{DataType})() at ./REPL[3]:4
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

breaks https://github.com/andrewcooke/CRC.jl

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -4263,3 +4263,11 @@ end
 g1090{T}(x::T)::T = x+1.0
 @test g1090(1) === 2
 @test g1090(Float32(3)) === Float32(4)
+
+# issue #16783
+function foo()
```
Comment (tkelman) [inline test/core.jl]: this is probably going to need a number

Comment (yuyichao) [inline test/core.jl]: Or a module
