### PR TITLE
RFC: Fix #11356

### LINKED ISSUE #11356: Unexpected `NaN` returned by `round(::Float64,::Int)`
Running julia version 0.3.8:
```
julia> round(0.01,308)
0.01
julia> round(0.01,309)
NaN
```
Is this intended?  It's rather inconvenient to deal with.

### PR DESCRIPTION
**Pull request by Mx-Glitter**
Hello Julia!

I just started learning the language and I figured I should try to contribute by tackling an "up for grabs" issue.

I'm pretty sure my code is not up to the Julia standards, and I don't know if I implemented the expected behavior so I'd love if you could give me some feedback.

The behavior I chose is coherent with what we see with large precision:
- Too much precision always return the original number
- Too few precision returns zero (with the sign of the orignal number) but for 2 edge cases with `ceil` and `floor`

Thanks in advance, cheers!

### CODE REVIEW

**Comment by Triiistan** [comment]
Unit tests added

**Comment by tkelman** [comment]
@simonbyrne does this look like the right behavior here?

File: test/numbers.jl [hunk 1]
```diff
@@ -1833,6 +1833,29 @@ approx_eq(a, b) = approx_eq(a, b, 1e-6)
 @test approx_eq(ceil(-123.456,1), -123.4)
 @test approx_eq(floor(123.456,1), 123.4)
 @test approx_eq(floor(-123.456,1), -123.5)
+# rounding with too much (or too few) precision
+for x in (12345.6789, 0, -12345.6789)
+  y = float(x)
```
Comment (tkelman) [inline test/numbers.jl]: 4-space indent would be more in line with the conventions elsewhere in base

Comment (Triiistan) [inline test/numbers.jl]: Done

File: base/floatfuncs.jl [hunk 2]
```diff
@@ -138,7 +138,26 @@ for f in (:round, :ceil, :floor, :trunc)
...
+                elseif x > 0
+                    if ceil == $f
+                        return convert(eltype(x), Inf)
+                    end
+                    return convert(eltype(x), 0)
+                elseif x < 0
+                    if floor == $f
+                        return -convert(eltype(x), Inf)
+                    end
+                    return convert(eltype(x), -0)
```
Comment (simonbyrne) [inline base/floatfuncs.jl]: `-0` is an integer, which doesn't have signed zeros, so the result will be `0.0`. You could use `-convert(eltype(x), 0)`, or simply `-zero(x)`.

**Comment by simonbyrne** [comment]
This seems like a reasonable solution.

File: base/floatfuncs.jl (hunk 2 above)
Comment (Triiistan) [inline base/floatfuncs.jl]: Used your recommendation

**Comment by sbromberger** [comment]
This breaks `round(Array{Float64,1}, Int)`: https://groups.google.com/forum/#!topic/julia-users/ThJZOienK2Y

**Comment by Triiistan** [comment]
Sorry for that!

**Comment by sbromberger** [comment]
@Triiistan no worries - @simonster fixed it last night :)
