### PR TITLE
remove io :multiline attribute

### LINKED ISSUE #16910: Messy @test output in case of success since IOContext changes
With recent master:
```julia
julia> @test [1,2] == [1,2]
Test Passed
  Expression: [1,2] == [1,2]
   Evaluated: 2-element Array{Int64,1}:
 1
 2 == (generic function with 128 methods) 2-element Array{Int64,1}:
 1
 2

```

The `Evaluated` part was likely supposed to use compact or non-`multiline` printing of arrays and methods.

### LINKED ISSUE #17087: Display regression for tuples of arrays
While updating the doctests I found that Julia 0.4.6 displays `findn` and `findnz` as the following:
```julia
julia> I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];

julia> S = sparse(I,J,V)
5x18 sparse matrix with 4 Int64 entries:
	[1 ,  4]  =  1
	[4 ,  7]  =  2
	[5 ,  9]  =  3
	[3 , 18]  =  -5

julia> findn(S)
([1,4,5,3],[4,7,9,18])

julia> findnz(S)
([1,4,5,3],[4,7,9,18],[1,2,3,-5])
```

while Julia 0.5-dev does:
```julia
julia> I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];

julia> S = sparse(I,J,V)
5×18 sparse matrix with 4 Int64 nonzero entries:
	[1 ,  4]  =  1
	[4 ,  7]  =  2
	[5 ,  9]  =  3
	[3 , 18]  =  -5

julia> findn(S)
(4-element Array{Int64,1}:
 1
 4
 5
 3,4-element Array{Int64,1}:
  4
  7
  9
 18)

julia> findnz(S)
(4-element Array{Int64,1}:
 1
 4
 5
 3,4-element Array{Int64,1}:
  4
  7
  9
 18,4-element Array{Int64,1}:
  1
  2
  3
 -5)
```

### LINKED ISSUE #17090: `macroexpand` display regression
Two different display issues here:

1. Functions now are always displayed in parenthesis
2. Nested calls show: `generic function with N method(s)`

0.4.6
```julia
julia> macroexpand( :(@edit println("")) )
:(Base.edit(println,(Base.typesof)("")))
```

0.5-dev
```julia
julia> macroexpand(:(@edit println("")))
:((Base.edit)(println,(typesof (generic function with 1 method))("")))
```

### PR DESCRIPTION
**Pull request by vtjnash**
this attribute doesn't nest properly,
and functions just end up branching almost the entire code based
on this parameter, so it's cleaner as a separate method

fix JuliaLang/julia#17087
fix JuliaLang/julia#16910
fix JuliaLang/julia#17090

### CODE REVIEW

File: base/deprecated.jl [hunk 1]
```diff
@@ -788,6 +788,19 @@ function symperm{Tv,Ti}(A::SparseMatrixCSC{Tv,Ti}, pinv::Vector{Ti})
         "Pkg.add(\"SuiteSparse\") to install SuiteSparse on Julia v0.5."))
 end
 
+# needs to be a macro so that we can use ::@mime(s) in type declarations
+eval(Multimedia, quote
+export @MIME
+macro MIME(s)
+    Base.warn_once("@MIME(\"\") is deprecated, use MIME\"\" instead.")
```
Comment (tkelman) [inline base/deprecated.jl]: apparently this has been deprecated for almost 3 years, just was never in this file - I think it would be safe to just delete it? https://github.com/JuliaLang/julia/commit/af8c18c1f088e59b3bc0249fd4e4bfd27851606d

File: base/dict.jl [hunk 2]
```diff
@@ -147,38 +90,7 @@ end
...
-        if limit
-            str = sprint(0, show, v, env=io)
-            str = _truncate_at_width_or_chars(str, cols, "\r\n")
-            print(io, str)
-        else
-            show(io, v)
-        end
-    end
-end
+show(io::IO, iter::Union{KeyIterator,ValueIterator}) = show(io, collect(iter))
```
Comment (tkelman) [inline base/dict.jl]: this will be showing them as if they're a different type than they actually are? should at least have a header?

Comment (vtjnash) [inline base/dict.jl]: it'll show them in compact form without a header (ie. when you call `show` directly, instead of displaying a mimetype)

**Comment by JeffBezanson** [comment]
This seems to make it impossible to implement single and multiline output for different mime types.

**Comment by vtjnash** [comment]
Can you give an example? This doesn't prevent you from making writers for other mimetypes.

**Comment by JeffBezanson** [comment]
IIUC, this puts multiline output in methods with mimetypes, and single line output in methods with 2 arguments. So how do you define both single and multiline output for html?

**Comment by vtjnash** [comment]
> IIUC, this puts multiline output in methods with mimetypes, and single line output in methods with 2 arguments. So how do you define both single and multiline output for html?

By using the (not yet provided by a package) Builder-type objects. This change defines the mime-type methods as outputting documents, and the show methods as outputting strings. The overlap between the two would be handled by the IO object, when outputting a mime-aware value into a document-aware context.

**Comment by JeffBezanson** [comment]
OK, I think where we ended up on this is to do this change for now, and if we need to implement single-line outputs for, say, HTML, that can be expressed by passing a display height of 1 in the IOContext.

**Comment by kshyatt** [comment]
I've restarted the AV build. @vtjnash if it passes, do you want to rebase and see if that passes CI, and then merge?

**Comment by JeffBezanson** [comment]
Rebased.

File: base/replutil.jl [hunk 3]
```diff
@@ -3,6 +3,139 @@
...
+
+function show(io::IO, ::MIME"text/plain", t::Task)
+    show(io, t)
+    if t.state == :failed
+        println(io)
+        showerror(io, CapturedException(t.result, t.backtrace))
+    end
+end
+
+show(io::IO, ::MIME"text/plain", X::AbstractArray) = showarray(io, X, false)
```
Comment (andreasnoack) [inline base/replutil.jl]: @vtjnash Following up [on my other comment](https://github.com/JuliaLang/julia/issues/24588#issuecomment-344909687). Why did you define these methods for `MIME"text/plain"` instead of two-argument `show` as https://github.com/JuliaLang/julia/pull/16563 prescribes?
