### PR TITLE
Fix #10838

### LINKED ISSUE #10838: reduce machinery assumes bitwise operators are scalar
Here's the symptom:

```jl
julia> reduce(&,fill([true],16))
ERROR: TypeError: non-boolean (Array{Bool,1}) used in boolean context
 in mapreduce_impl at reduce.jl:316
 in _mapreduce at reduce.jl:149
 in reduce at reduce.jl:159
```

The problem was introduced in this commit: https://github.com/JuliaLang/julia/commit/5336b78819f506bdca2b68985d45557a615b3aff. The issue seems to be that this commit assumes that boolean operators like `&` and `|` can only produce `Bool` values, which is not the case, e.g. when the reduction is over arrays of booleans instead of booleans. Opening an issue since this reduce machinery is really complicated and I'm not sure what the best way to fix this is.

cc @lindahua

### PR DESCRIPTION
**Pull request by lindahua**
This patch restricts the efficient short-circuit implementation only to `AbstractArray{Bool}`, for reduction with `&` or `|` over general arrays, e.g. arrays of bool arrays, it simply falls back to the general implementation, which works fine.

Tests are added.

cc: @StefanKarpinski

### CODE REVIEW

File: test/reduce.jl [hunk 1]
```diff
@@ -195,6 +195,11 @@ prod2(itr) = invoke(prod, (Any,), itr)
 @test all(x->x>0, [4]) == true
 @test all(x->x>0, [-3, 4, 5]) == false
 
+@test reduce(|, fill(trues(5), 3))  == trues(5)
+@test reduce(|, fill(falses(5), 3)) == falses(5)
+@test reduce(&, fill(trues(5), 3))  == trues(5)
+@test reduce(&, fill(falses(5), 3)) == falses(5)
```
Comment (StefanKarpinski) [inline test/reduce.jl]: I don't think the issue was triggered until the array was at least 16 long, so this test probably passed before as well.

**Comment by simonster** [comment]
Looks like you changed the wrong signatures (`MaxFun` and `MinFun` instead of `AndFun` and `OrFun`). The tests pass, but only because we don't actually get to that code for arrays of length <16.

**Comment by lindahua** [comment]
I am modifying this PR

**Comment by simonster** [comment]
lgtm

**Comment by StefanKarpinski** [comment]
Backported: https://github.com/JuliaLang/julia/commit/83b52f9e399921b58d7ab86487a9275a04e8c775
