### PR TITLE
Fix #20108 fix #20111: method display errors

### LINKED ISSUE #20108: REPL bug
```julia
julia> Array()
ERROR: MethodError: no method matching Array()WARNING: Error showing method candidates, aborted


julia> versioninfo()
Julia Version 0.6.0-dev.2128
Commit a1f232e* (2017-01-16 20:52 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

### LINKED ISSUE #20111: `methods` of closure Error showing value of type Base.MethodList
```
julia> K(x) = y -> x
K (generic function with 1 method)

julia> methods(K(1))
# 1 method for generic function "(::#1)":
Error showing value of type Base.MethodList:
ERROR: type UnionAll has no field name
Stacktrace:
 [1] #show#365(::Nullable{DataType}, ::Function, ::IOContext{Base.Terminals.TTYTerminal}, ::Method) at ./methodshow.jl:95
 [2] (::Base.#kw##show)(::Array{Any,1}, ::Base.#show, ::IOContext{Base.Terminals.TTYTerminal}, ::Method) at ./<missing>:0
 [3] show_method_table(::IOContext{Base.Terminals.TTYTerminal}, ::Base.MethodList, ::Int64, ::Bool) at ./methodshow.jl:147
 [4] show(::IOContext{Base.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Base.MethodList) at ./replutil.jl:4
 [5] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Base.MethodList) at ./REPL.jl:122
 [6] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::Base.MethodList) at ./REPL.jl:125
 [7] display(::Base.MethodList) at ./multimedia.jl:183
```

possibly related: #20108, #19998

### PR DESCRIPTION
**Pull request by ihnorton**
Both errors from trying to access fields of `::UnionAll` objects.
replutil seems to be reasonably well-tested already, but hit some corner cases here.

### CODE REVIEW

**Comment by tkelman** [comment]
can we test these under a fake repl output, if the corner cases only happen in interactive display?

File: base/replutil.jl [hunk 1]
```diff
@@ -515,6 +515,7 @@ function show_method_candidates(io::IO, ex::MethodError, kwargs::Vector=Any[])
                     # If the methods args is longer than input then the method
                     # arguments is printed as not a match
                     for (k, sigtype) in enumerate(sig[length(t_i)+1:end])
+                        sigtype = unwrap_unionall(sigtype)
```
Comment (JeffBezanson) [inline base/replutil.jl]: I think this should only be done in the `isvarargtype` case. Otherwise we won't correctly show argument types that are UnionAlls.

This code also doesn't seem to handle arguments written as `::Vararg{T,N}`, but that's a separate issue.

**Review by JeffBezanson — DISMISSED** [review]

**Comment by ihnorton** [comment]
Updated. Added tests.

File: test/replutil.jl [hunk 2]
```diff
@@ -453,6 +453,19 @@ let d = Dict(1 => 2, 3 => 45)
...
+    try Array() catch err end
+    Base.show_method_candidates(buf,err)
+    @test isa(err, MethodError)
+    @test contains(String(buf), "Closest candidates are:")
+end
+
+# Issue 20111
+let K20111(x) = y -> x, buf = IOBuffer()
+  show(buf, methods(K20111(1)))
+  @test contains(String(buf), " 1 method for generic function")
```
Comment (tkelman) [inline test/replutil.jl]: 4-space

**Review by Keno — APPROVED** [review]
LGTM once the whitespace change requested by @tkelman is addressed.
