### PR TITLE
RFC: make UndefVarError messages more precise and informative

### LINKED ISSUE #17062: More help for users when encountering UndefVarError
The [printing of `UndefVarError`](https://github.com/JuliaLang/julia/blob/45fa65f1f950609e471ad5f15f31bea103f8c823/base/replutil.jl#L103) is very minimalistic and can be improved to look for common mistakes.
- [ ] Look for variable names that is similar to Base functions/types (eg, levenshtein distance/length)
- [ ] Collect a list of function names in other languages and add explanation of how to get equivalent results in Julia
- [ ] Collect a list of function names in common packages so that we can point users to the correct package (especially relevant now that we have started to move functions out of Base).

I opened the similar issue https://github.com/JuliaLang/julia/issues/7512 a while ago, but it was hard to find a general solution.

Ref https://github.com/JuliaLang/julia/issues/17046#issuecomment-227391728, and cc @tknopp

### LINKED ISSUE #18877: Unexpected behavior when assigning to function
I am not sure if this is a bug, but the following certainly creates some unexpected behavior (unexpected error message at least) and debugging headache where the assignment to length was supposed to be a test `length(b)==2`.

``` julia
function f(a, b)
    N = length(a)
    length(b) = 2
    return N
end
f((1,2),(3,4))
```

which results in

``` julia
ERROR: UndefVarError: length not defined
 in f(::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}) at ./REPL[3]:2
```

especially when the assignment is not even reachable

``` julia
function g(a, b)
    return length(a)
    length(b) = 2
end
g((1,2),(3,4))
```

``` julia
ERROR: UndefVarError: length not defined
 in g(::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}) at ./REPL[6]:2
```

Notice that the error occurs at the `length(a)` call, not in the assignment statements.

Running Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)

### LINKED ISSUE #25263: Add way to get module of variable from an UndefVarError
Repeat of Discourse Post:

+ [Way to get module of undef variable?](https://discourse.julialang.org/t/way-to-get-module-of-undef-variable/7931)

-------

From Post:

> If you do:
> 
> ```
> cur_error = nothing 
> 
> try 
>   foo(bar::Main.baz) = "Rambo"
> catch tmp_error
>   cur_error = tmp_error
> end
> ```
> 
> which gives
> 
> ```
> > cur_error
> UndefVarError(:baz)
> 
> > cur_error.var
> :baz
> ```
> 
> -----
> 
> The thing I'm kind of curious about is if there is a way to get the module that should have `:baz` in it (i.e. `Main`)?

### LINKED ISSUE #35126: Error message for variable with same name as function could be more explicit
```
julia> f(x) = 2
f (generic function with 1 method)

julia> let
       f = f(2)
       end
ERROR: UndefVarError: f not defined
Stacktrace:
 [1] top-level scope at REPL[7]:2
```

### LINKED ISSUE #39280: Defining a `Foo{T}` constructor for `Foo{T, S <: T}`
The manual doesn't provide a definition for what it means to define a constructor for a parametric type where the number of type parameters accepted by the constructor is fewer than the number of type parameters for the type. In simple cases, it works as expected, but for more complicated cases, the lack of a formal semantics leads to mass confusion, as demonstrated by [this Discourse thread](https://discourse.julialang.org/t/using-parametric-type-inside-outer-parametric-constructor/53388).

From that thread, we came up with the following MWE.

This works:

```julia
julia> struct Bar{T, S} end

julia> Bar{T}() where {T} = T

julia> Bar{Integer}()
Integer
```

But this does not:

```julia
julia> struct Foo{T, S <: T} end

julia> Foo{T}() where {T} = T

julia> Foo{Integer}()
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] Foo{Integer,S} where S<:Integer() at ./REPL[2]:1
 [2] top-level scope at REPL[3]:1
```

Without a definition of what it means to define `Foo{T}() where {T} = # ...` it's difficult to know if this is a bug or if this is expected behavior. And if it is the expected behavior, it would be nice to know what the semantic rule is that explains this behavior (and it would be nice to have that explanation in the manual).

### LINKED ISSUE #41728: UndefVarError for a struct type parameter
Not sure if that's the intended behaviour or not, but seems surprising:
```
julia> struct A{T}
               x::Vector{<:T}
       end

# ok:
julia> A([1, 2, 3])
A{Int64}([1, 2, 3])

# fails:
julia> A(Any[1, 2, 3])
ERROR: UndefVarError: T not defined
```
In my particular case, this code was a mistake anyway: I intended to write
```
struct A{T<:SomeSuperT}
    x::Vector{T}
end
```
instead.  But maybe it is relevant in the wider context.

I'm using the latest julia release:
```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

### LINKED ISSUE #48731: Clearer error message when unable to determine exact type parameter value in a method
It is possible to define methods where Julia is unable to determine a concrete value for a type parameter, leading to a `UndefVarError`:

```julia
julia> foo(::Ref{<:T}) where T = T
foo (generic function with 1 method)

julia> foo(Ref{String}())
String

julia> foo(Ref{AbstractString}())
ERROR: UndefVarError: `T` not defined
```

The error is confusing since, from a user's perspective, `T` is very much defined/declared in the `where` part of the method definition.

Rather, could we throw a dedicated `AmbiguousTypeParameter` error here (bikeshed, please)? Preferably with a docstring that would explain that it's possible to construct signatures where you can't uniquely figure out a type. And would also probably suggest avoiding unnecessary subtyping in method signature (like in the `Ref{<:T}` example above), since that is most likely an error on the user's part.

A couple of related issues I was able to find: https://github.com/JuliaLang/julia/issues/25307, https://github.com/JuliaLang/julia/issues/39277, https://github.com/JuliaLang/julia/issues/39280, https://github.com/JuliaLang/julia/issues/41841, https://github.com/JuliaLang/julia/issues/41728. It also caused some discussion [on Zulip recently](https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/.E2.9C.94.20Spooky.20error.20with.20parametric.20types.20in.20tuples).

_While for a different issue, the hints in https://github.com/JuliaLang/julia/issues/34393 might also help with the implementation here._

### LINKED ISSUE #49917: UndefVarError shadowing function
The bug:
```julia
function f(s, price)
    @show f
    f = s * price
end

f(2, 3)
```
```julia-repl
ERROR: LoadError: UndefVarError: `f` not defined
Stacktrace:
 [1] macro expansion
   @ Main ./show.jl:1153 [inlined]
 [2] f(s::Int64, price::Int64)
   @ Main ~/git/julia/bug.jl:2
 [3] top-level scope
   @ ~/git/julia/bug.jl:5
in expression starting at /home/apaz/git/julia/bug.jl:5
```

User's `versioninfo()`:
```julia-repl
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 7900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 69 on 24 virtual cores
```
I also replicated this on my own machine on master.

```julia-repl
julia> Meta.parse("function f(s, price)\n  @show f\n  f = s * price\nend")
:(function f(s, price)
      #= none:1 =#
      #= none:2 =#
      #= none:2 =# @show f
      #= none:3 =#
      f = s * price
  end)
```

```julia-repl
julia> @code_lowered f(2, 3)
CodeInfo(
1 ─      value = f
│   %2 = f
│   %3 = Base.repr(%2)
│        Base.println("f = ", %3)
│        value
│   %6 = s * price
│        f = %6
└──      return %6
)
```

```julia-repl
julia> @code_typed f(2, 3)
CodeInfo(
1 ─     $(Expr(:throw_undef_if_not, :f, false))::Any
└──     unreachable
) => Union{}
```

### LINKED ISSUE #50369: UndefVarError if trying to shadow global variable using let
When working with Pluto, I like to wrap more complex cells using `let` and reuse simple variable names.
Within Pluto, everything works fine, but when executing the notebook as a standalone script, Julia complains about some variables not being defined.

### MWE

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.1 (2023-06-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> x = 5
5

julia> y = let
           x = 2x
           x += 1
       end
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] top-level scope
   @ REPL[2]:2
```

### Workaround

By removing the initial line break, Julia gets what I mean.
But I think this is a bug of Julia (and I don't want to use different variable names or edit the whole already-too-long notebook). :upside_down_face: 

```
julia> y = let x = 2x
           x += 1
       end
11

julia> x
5
```

### PR DESCRIPTION
**Pull request by vtjnash**
Record the 'scope' of the variable that was undefined (the Module, or a descriptive word such as :local or :static_parameter). Add that scope to the error message, and expand the hint suggestions added by the REPL to include more specific advice on common mistakes:

  - forgetting to set an initial value
  - forgetting to import a global
  - creating a local of the same name as a global
  - not matching a static parameter in a signature subtype

Fixes #17062 (although more could probably be done to search for typos using REPL.string_distance and getting the method from stacktrace)
Fixes #18877
Fixes #25263
Fixes #35126
Fixes #39280
Fixes #41728
Fixes #48731
Fixes #49917
Fixes #50369

(this needs a fix to a Distributed test, which can be done concurrent with any discussion about exact wording here)

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -1303,6 +1303,50 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
         print(io, "\nsuggestion: To exit Julia, use Ctrl-D, or type exit() and press enter.")
     end
+    if isdefined(ex, :scope)
+        scope = ex.scope
+        if scope isa Module
+            bnd = ccall(:jl_get_module_binding, Any, (Any, Any, Cint), scope, var, true)::Core.Binding
+            if isdefined(bnd, :owner)
+                owner = bnd.owner
+                if owner === bnd
+                    print(io, "\nsuggestion: add an appropriate import or assignment. This global was declared by not assigned.")
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:1313]:
```suggestion
                    print(io, "\nSuggestion: add an appropriate import or assignment. This global was declared but not assigned.")
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 2]
```diff
@@ -1303,6 +1303,50 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+                end
+            else
+                owner = ccall(:jl_binding_owner, Ptr{Cvoid}, (Any, Any), scope, var)
+                if C_NULL == owner
+                    print(io, "\nsuggestion: check for spelling errors or missing imports. No global of this name exists in this Module.")
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:1318]:
```suggestion
                    print(io, "\nSuggestion: check for spelling errors or missing imports. No global of this name exists in this Module.")
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 3]
```diff
@@ -1303,6 +1303,50 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+                    owner = bnd
+                else
+                    owner = unsafe_pointer_to_objref(owner)::Core.Binding
+                end
+            end
+            if owner !== bnd
+                # this could use jl_binding_dbgmodule for the exported location in the message too
+                print(io, "\nsuggestion: this global was defined as `$(owner.globalref)` but not assigned a value.")
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:1326]:
```suggestion
                print(io, "\nSuggestion: this global was defined as `$(owner.globalref)` but not assigned a value.")
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 4]
```diff
@@ -1303,6 +1303,50 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+            end
+        elseif scope === :static_parameter
+            print(io, "\nsuggestion: run Test.detect_unbound_args to detect Method signatures arguments that do not fully constrain a type parameter inside an invariant {} scope for this matching call signature.")
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:1329]:
```suggestion
            print(io, "\nSuggestion: run Test.detect_unbound_args to detect method arguments that do not fully constrain a type parameter.")
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 5]
```diff
@@ -1303,6 +1303,50 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+        elseif scope === :local
+            print(io, "\nsuggestion: check for an assignment to a local that shadows a global of the same name")
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:1331]:
```suggestion
            print(io, "\nSuggestion: check for an assignment to a local that shadows a global of the same name.")
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 6]
```diff
@@ -1303,6 +1303,50 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+        end
+    else
+        scope = undef
+    end
+    warnfor(m, var) = Base.isbindingresolved(m, var) && isdefined(m, var) && (print(io, "\nhint: a global of this name also exists in $m"); true)
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:1336]:
```suggestion
    warnfor(m, var) = Base.isbindingresolved(m, var) && isdefined(m, var) && (print(io, "\nHint: a global variable of this name also exists in $m"); true)
```

**Comment by JeffBezanson** [comment]
This is great! :tada:

File: stdlib/REPL/src/REPLCompletions.jl (hunk 1 above)
Comment (albheim) [reply stdlib/REPL/src/REPLCompletions.jl:1313]: Just noting that if "suggestion" should be capitalized, there are also a few additions in the docs that should be updated. 

And there are a few occurrences right above this that have the uncapitalized version, making for inconsistent usage if these are updated, though maybe it doesn't really fit in the scope of this PR to fix that.
