### PR TITLE
inference: Make test indepdent of the `Complex` method table

### LINKED ISSUE #59073: Intermittent inference test failure
```

Error in testset Compiler/inference:
--
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-grannysmith-C07ZQ07FJYVY.0/build/default-grannysmith-C07ZQ07FJYVY-0/julialang/julia-master/julia-76319085f6/share/julia/Compiler/test/inference.jl:3553
  | Expression: Base.return_types(f_overly_abstract_complex, Tuple{}) == [Complex]
  | Evaluated: Any[Any] == UnionAll[Complex]

```

E.g. https://buildkite.com/julialang/julia-master/builds/49331/steps/canvas?jid=0198336b-61ad-4008-8f44-ff9ba7c95cd3.

Probably an ordering issue.

### PR DESCRIPTION
**Pull request by Keno**
The test helpers in both the base tests and linear algebra add `(::Type{<:Number})(::Furlong)` methods (for their own respective copies of furlong). These methods intersect with `Complex(::Any)`. Having only one of these isn't a problem, but if both get added, we consider that too many methods and bail. In discussion this with Jeff (who originally wrote the test), our preference is that inference tests should be as standalone from the base system's method tables as possible, so adjust the test (as opposed to e.g. changing the Furlong signatures).

Fixes #59073

### CODE REVIEW

File: Compiler/test/inference.jl [hunk 1]
```diff
@@ -3549,8 +3549,14 @@ f31974(n::Int) = f31974(1:n)
...
-f_overly_abstract_complex() = Complex(Ref{Number}(1)[])
-@test Base.return_types(f_overly_abstract_complex, Tuple{}) == [Complex]
+# Issue #33472
+struct WrapperWithUnionall33472{T<:Real}
+    x::T
+end
+
+f_overly_abstract33472() = WrapperWithUnionall33472(Ref{Number}(1)[])
+# Check that this doesn't infer as `WrapperWithUnionall33472{T<:Number}`.
+@test Base.return_types(f_overly_abstract33472, Tuple{}) == [WrapperWithUnionall33472]
```
Comment (JeffBezanson) [inline Compiler/test/inference.jl:3559]: This looks like it has a decent chance to be inferred as `WrapperWithUnionall33472{Int}`.

Comment (Keno) [reply Compiler/test/inference.jl:3559]: Ok, I can write it as inferencebarrier with a type assert, which is the usual pattern. I was mostly just preserving what is already there.

**Review by JeffBezanson — APPROVED** [review]

**Comment by IanButterworth** [comment]
Merging given approved to get CI happy again
