### PR TITLE
Subtype: Improve `simple_meet` resolution for `Union` inputs

### LINKED ISSUE #49354: Testing Arrow asserts in subtyping on 1.9
```julia
(jl_sshwyM) pkg> add Arrow; test Arrow
...
testing: dictencode keyword
testing: nesteddictencode keyword
Assertion failed: (obvious_subtype == 3 || obvious_subtype == subtype || jl_has_free_typevars(x) || jl_has_free_typevars(y)), function ijl_subtype_env, file subtype.c, line 1946.

[21676] signal (6): Abort trap: 6
in expression starting at /Users/kristoffercarlsson/.julia/packages/Arrow/P0wVk/test/runtests.jl:46
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
```

Seems to work fine on master. Regression introduced in one of the backports it seems. 

Ref: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9aa7669_vs_7b39515/Arrow.primary.log

### PR DESCRIPTION
**Pull request by N5N3**
close #49354. (The fix is somehow limited as `obviously_disjoint` is simple to deceive.)

### CODE REVIEW

**Comment by giordano** [comment]
To be backported to 1.9?

File: src/jltypes.c [hunk 1]
```diff
@@ -717,6 +717,84 @@ jl_value_t *simple_union(jl_value_t *a, jl_value_t *b)
...
+        for (j = nta; j < nt; j++) {
+            if (temp[j] == NULL) continue;
+            int subs = simple_subtype2(temp[i], temp[j], hasfree || jl_has_free_typevars(temp[j]));
+            int subab = subs & 1, subba = subs >> 1;
+            if (subba && !subab) {
+                stemp[i] = -1;
+            }
+            if (subab && !subba) {
+                stemp[j] = -1;
+                temp[j] = temp[i];
```
Comment (vtjnash) [inline src/jltypes.c:754]: Does this make the algorithm slightly unstable to ordering? Eventually, for `!overesi`, this algorithm could return `Union{a, b}` for all `a` and `b` from the original `a` and `b` for which it could prove that element is a `<:` of the other union. That may often be `Union{}`, but doesn't have to be.

Secondly for `!overesi`, it similarly can return any type that is both `<:a` and `<:b` but `>:intersect(a,b)`. I don't think that is quite the same as removing any element from `b` that is potentially a subtype of an element `a`. For example, if it had `Tuple{E1}` and `Tuple{E2}` in `a`, but had `Tuple{Union{E1,E2}}` in `b`, it may be incorrect to "forget" that `Tuple{E2}` was in the union (unless `!overesi`)

Comment (N5N3) [reply src/jltypes.c:754]: I'm afraid that I didn’t get the 1st concern, `simple_intersect`only joins preserved types in `a`, or preserved and substituted ones in`b`, thus it seems unlikely to return `Union{a,b}`?

But the 2nd concern is correct, the current algorithm works well only for injective elements. We’d better perform the “substitution” after the subtyping

Comment (vtjnash) [reply src/jltypes.c:754]: For `!overesi`, it isn't a concern, but an observation that this can return the Union of all provably preservable elements (all elements of `a` that are definite subtypes of `b` and all elements of `b` that are definitely subtypes of `a`)

Comment (N5N3) [reply src/jltypes.c:754]: IIUC, this is exactly what we want?
The result should `>:` all elements from `a` if it `<:b` and all elements from `b` if it `<:a`.
I think there's no need to worry about `Union{Int, Real} ∩ Integer` (a[i] <: b[j] <: a[k]) as all other path should have normalize it.

Comment (vtjnash) [reply src/jltypes.c]: It may already be doing much of this, and I just haven't fully understood that part of the algorithm. The example I am thinking here is that if you had a=`Union{Int32, Int64, AbstractString}` and b=`Union{Integer, String}`, then the `!overesi` intersection can be any type that is `<:Union{Int32, Int64, String}` (often chosen as `Union{}` currently) while the `overesi` intersection is any value that is `>:Union{Int32, Int64, String}`, which might be chosen as either of `a` or `b` currently.

File: src/jltypes.c [hunk 2]
```diff
@@ -776,9 +772,16 @@ jl_value_t *simple_intersect(jl_value_t *a, jl_value_t *b, int overesi)
...
         return jl_bottom_type;
     }
-    nt = subs[0] ? nta : nt;
-    count = subs[0] ? nta : ntb;
-    i = subs[0] ? 0 : nta;
+    nt = subs[0] ? nta : subs[1] ? nt  : nt;
+    i  = subs[0] ? 0   : subs[1] ? nta : 0;
+    count = nt - i;
+    if (!subs[0] && !subs[1]) {
+        // prepare for over esitimation
```
Comment (vtjnash) [inline src/jltypes.c:779]: sp: estimation

File: src/jltypes.c (hunk 1 above)
Comment (N5N3) [reply src/jltypes.c]: For `!overesi`, the algorithm requires all undisjointable part in `a`(`b`) <: `b`(`a`), otherwise it would always return `Union{}`.
Since the "Subtitution" has been replaced with an elimination with partiality, elements in `a` would be removed if we can't prove it `<:b`, while elements in `b` would be removed only if we can prove it `>:a`.

**Comment by timholy** [comment]
Thanks @N5N3!

**Comment by KristofferC** [comment]
@N5N3, this seems to fail `analyzegc` on the 1.9 backport branch.

**Comment by N5N3** [comment]
Sorry, didn’t notice that. Looks like there’re some GC mark change on master.
Will take a look tomorrow.
