### PR TITLE
fix `bit_map!` with aliasing

### LINKED ISSUE #50780: 1.9.2 Base.map!(|,a,a,b) yields wrong answer on BitVector
The  testset for the DataStructures.jl package are now failing in 1.9.2.  In particular, IntSet is not working.  I have traced the error to a bug with the Base.map! function applied to BitVector.  See below for the incorrect output from map!:

EDIT: I did not report this bug correctly in my first post.  The bug is actually with `map!(|,a,a,b)` not with `map!(|,a,b)`.  Please refer to my follow-up post below.

```julia
julia> a = BitVector([1,1,0,0,1,1,0,0]);

julia> b = BitVector([1,0,1,0,1,0,1,0]);

julia> map!(|, a, b);

julia> a
8-element BitVector:
 1
 0
 1
 0
 1
 0
 1
 0
```

### PR DESCRIPTION
**Pull request by oscardssmith**
fixes #50780 caused by #47013.

### CODE REVIEW

File: base/bitarray.jl [hunk 1]
```diff
@@ -1791,9 +1791,10 @@ function bit_map!(f::F, dest::BitArray, A::BitArray) where F
     dest_last = destc[len_Ac]
     _msk = _msk_end(A)
     # first zero out the bits mask is going to change
-    destc[len_Ac] = (dest_last & (~_msk))
     # then update bits by `or`ing with a masked RHS
-    destc[len_Ac] |= f(Ac[len_Ac]) & _msk
+    # DO NOT SEPARATE ONTO TO LINES.
```
Comment (ericphanson) [inline base/bitarray.jl:1795]:
```suggestion
    # DO NOT SEPARATE INTO TWO LINES.
```

Comment (oscardssmith) [reply base/bitarray.jl:1795]: oops :)
