### PR TITLE
typeintersect: fix `constraintkind` for non-covariant var

### LINKED ISSUE #50195: Hang during type intersection
The following MWE hangs / StackOverflows during type intersection:

```julia
a = Tuple{
    typeof(parent),
    Type{
        X48,
    } where {X48<:Union{
        Base.LogicalIndex,
        SubArray{
            T,
            N,
            X5,
        } where {X5<:Union{
            Base.ReinterpretArray{X2} where X2<:Union{SubArray{X3,X4} where X3},
        }} where X4,
    }} where {N} where T,
}
b = Tuple{
    typeof(parent),
    Type{
        X16,
    } where X16<:(
        SubArray{
            X15,
            X14,
            X5,
        } where {X5<:Union{
            Base.ReinterpretArray{X2} where X2<:Union{SubArray{X3,X13} where X3,X13},
        }} where {X13<:Src} where {X14} where {X15}
    ),
} where {Src}
typeintersect(a, b)
```

(Reduced from CUDA.jl.)

Bisected to 5235bfb483a29d27724b6dbc4b9a9842390cf47a, from https://github.com/JuliaLang/julia/pull/49261. cc @N5N3

### PR DESCRIPTION
**Pull request by N5N3**
The pre-check for `constraintkind` failed to predict `occurs_cov` (`!var_occurs_invariant` doesn't means `occurs_cov > 0`). And false `constraintkind` might cause circular constraints during the env contraction.

This PR fixes it by adding missing check back.
MWE added.
close #50195.

### CODE REVIEW

File: src/subtype.c [hunk 1]
```diff
@@ -3014,6 +3014,39 @@ static jl_value_t *intersect_unionall_(jl_value_t *t, jl_unionall_t *u, jl_stenv
...
+    }
+    else if (jl_is_uniontype(v)) {
+        return always_occurs_cov(((jl_uniontype_t*)v)->a, var, param) ||
+               always_occurs_cov(((jl_uniontype_t*)v)->b, var, param);
+    }
+    else if (jl_is_unionall(v)) {
+        jl_unionall_t *ua = (jl_unionall_t*)v;
+        return ua->var != var && (
+            always_occurs_cov(ua->var->lb, var, 0) ||
+            always_occurs_cov(ua->var->ub, var, 0) ||
```
Comment (vtjnash) [inline src/subtype.c:3033]:
```suggestion
            always_occurs_cov(ua->var->lb, var, 1) ||
            always_occurs_cov(ua->var->ub, var, 0) ||
```

To make this valid, it might also need to track whether the var here ends up eventually constraining it?
```
&& !occurs(ua->var->ub, var) || always_occurs_cov(ua->body, ua->var, param))
```

Comment (vtjnash) [reply src/subtype.c:3033]: I think I misunderstood the meaning of the `always_occurs_cov` to mean `only_cov`, which was not the intent. I guess this function is actually equivalent to `Core.Compiler.constrains_param && !occurs_inv`

A use as a lower bound does not create a constraint on the lower bound for var:
```suggestion
            always_occurs_cov(ua->var->ub, var, 0) ||
```

File: src/subtype.c [hunk 2]
```diff
@@ -3014,6 +3014,39 @@ static jl_value_t *intersect_unionall_(jl_value_t *t, jl_unionall_t *u, jl_stenv
...
+{
+    if (param > 1) {
+        return 0;
+    }
+    else if (v == (jl_value_t*)var) {
+        return param == 1;
+    }
+    else if (jl_is_uniontype(v)) {
+        return always_occurs_cov(((jl_uniontype_t*)v)->a, var, param) ||
+               always_occurs_cov(((jl_uniontype_t*)v)->b, var, param);
```
Comment (vtjnash) [inline src/subtype.c:3027]:
```suggestion
        return always_occurs_cov(((jl_uniontype_t*)v)->a, var, param) &&
               always_occurs_cov(((jl_uniontype_t*)v)->b, var, param);
```

**Comment by maleadt** [comment]
Thanks! Confirmed that this makes the CUDA.jl hang disappear (i.e. not only the reduced MWE).

File: src/subtype.c (hunk 1 above)
Comment (N5N3) [reply src/subtype.c:3033]: I guess they have some little difference? But the suggestions make sense (As their task looks similar).

`always_occurs_cov` should perform a conservative estimation on the `occurs_cov` after 1st intersection.
As we want to match the branch `if (vb.occurs_cov && noinv)` below.

`var_occurs_inside` is not a good template here:
1. We only perform `intersect_aside` on `ub`.
2. The union decision should not affect the conservativeness.
