### PR TITLE
Try not to use address of local variable as stack address to copy.

### LINKED ISSUE #16792: Julia crashes on musl libc systems
Julia is on the process of being ported to a musl libc system (Alpine Linux).
However, there is a bug about "illegal instructions" making it crash.

```
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-alpine-linux-musl


signal (4): Illegal instruction
jl_unprotect_stack at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_unprotect_stack at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_switchto at /usr/bin/../lib/julia/libjulia.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
_init at /usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x7f4d6b945d67)
unknown function (ip: 0x7f4d6b9458bf)
__libc_start_main at /lib/ld-musl-x86_64.so.1 (unknown line)
Illegal instruction
```

When using `--precompiled=no`:

```
$ julia --precompiled=no
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-alpine-linux-musl


signal (4): Illegal instruction
jl_unprotect_stack at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_unprotect_stack at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_switchto at /usr/bin/../lib/julia/libjulia.so (unknown line)
yieldto at ./task.jl:71
wait at ./task.jl:371
Illegal instruction
```

If `/usr/lib/julia/sys.so` is deleted, then:

```
$ julia
Illegal option -p
ERROR: system image file "/usr/bin/../lib/julia/sys.so" not found
```

It has also been tried to run it on a vanilla kernel (Alpine by default has a grsec kernel) but the exact same errors were observed.

Recompiling OpenBLAS without `DYNAMIC_ARCH` or setting `JULIA_CPU_TARGET` didn't make any difference either.

For the Julia developers that don't run Alpine Linux, here's a Dockerfile to help you reproduce the issue:

```
FROM alpine
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.4/main" > /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN echo "https://alpine.geeknet.cz/packages/edge/testing" >> /etc/apk/repositories
RUN wget -O "/etc/apk/keys/jakub@jirutka.cz-56d0d9fd.rsa.pub"
RUN https://alpine.geeknet.cz/keys/jakub%40jirutka.cz-56d0d9fd.rsa.pub
RUN apk update
RUN apk add julia julia-dev
RUN julia
```

Thanks.

/cc @tkelman @jirutka

### PR DESCRIPTION
**Pull request by yuyichao**
This can trigger bounds check on some libc.

Fixes #16792

### CODE REVIEW

**Comment by albap** [comment]
@yuyichao thanks a lot!

**Comment by vtjnash** [comment]
lgtm

**Comment by ivarne** [comment]
@jirutka suggests that this should be backported to release-0.4 in [#16792](https://github.com/JuliaLang/julia/issues/16792#issuecomment-224456213). Adding the appropriate label.

**Comment by tkelman** [comment]
@yuyichao can you confirm whether this should be safe to backport?

**Comment by yuyichao** [comment]
Should be safe to backport.

File: src/task.c [hunk 1]
```diff
@@ -144,8 +144,8 @@ static void NOINLINE save_stack(jl_tls_states_t *ptls, jl_task_t *t)
 {
     if (t->state == done_sym || t->state == failed_sym)
         return;
-    volatile char *_x;
-    size_t nb = (char*)ptls->stackbase - (char*)&_x;
+    char *frame_addr = (char*)jl_get_frame_addr();
+    size_t nb = (char*)ptls->stackbase - frame_addr;
```
Comment (tkelman) [inline src/task.c]: replacing `ptls->stackbase` with `jl_stackbase` is appropriate for release-0.4, right?

Comment (yuyichao) [inline src/task.c]: Should be. That is also not changed in this PR.
