### PR TITLE
JuliaSyntax parser-based REPL completions overhaul

### LINKED ISSUE #55420: [REPL] Autocompletion of arguments inside `ModuleName.function` call is broken
On f0a2a7a0a9, autocompletion of the arguments inside function calls of the form `Module.function` is broken, only keywords are suggested, not types, variables, functions, etc.  For example:
```
M.f(p<TAB>
```
directly autocompletes to
```
M.f(primitive type
```
because `primitive type` is the only keyword starting with `p`. This is a regression, autocompletion in this situation used to work in previous versions.

### LINKED ISSUE #55429: Tab completion not working with module specification in `@time` calls involving another macro
This seems similar to https://github.com/JuliaLang/julia/issues/51827.
What doesn't work:
```julia
julia> @time @eval Base.Iden<TAB>
```
No completion or suggestions are offered.
Using either `@time` or `@eval` in isolation works, but the combination doesn't.
Versioninfo:
```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.1024
Commit e7e8768a775 (2024-08-08 23:44 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_EDITOR = subl
```
However, this behavior is present on v1.10.4 as well.

This isn't specific to `@eval`, as the same behavior is seen if other macros are used:
```julia
julia> @time @code_warntype Base.Iden<TAB>
```

Curiously, swapping the order of the macros gets completion to work:
```julia
julia> @eval @time Base.Iden<TAB>
julia> @code_warntype @time Base.Iden<TAB>
```
These complete as expected, so perhaps it's only certain macros for which this doesn't work.

### LINKED ISSUE #55518: [REPL] Autocompletion of `ModuleName.@macro_name` is broken
On 5230d27de9
```
julia> Base.@time nothi<TAB>
```
autocompletes `nothi` to `nothing_sentinel`:
```
julia> Base.@time nothing_sentinel
ERROR: UndefVarError: `nothing_sentinel` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] macro expansion
   @ ./timing.jl:579 [inlined]
 [2] top-level scope
   @ ./REPL[17]:1
```
If I understand it correctly, `ModuleName.@macro symbol<TAB>` autocompletes `symbol` inside `ModuleName`, not `Main`:
```
julia> module Issue55518
       macro name(expr) :($(esc(expr))) end
       const not_really_what_I_wanted = something
       end
Main.Issue55518

julia> using .Issue55518

julia> Issue55518.@name not<TAB>
```
This works correctly in Julia v1.10 and v1.11.0-rc1

### LINKED ISSUE #55520: [REPL] Autocompletion of `@benchmark A .= A setup=(A=` is broken
On faa6095e983:
```julia-repl
julia> @benchmark A .= A setup=(A=p<TAB>
```
autocompletes `p` to `primitive type`, the only things completed at this point are 	keywords.  This is a regression in Julia v1.12, it works as expected in Julia v1.10.  This is similar to #55420, but the condition is quite different.

### LINKED ISSUE #55842: [REPL] Autocompletion broken for macro names if there's other text after it
On d6fa66ff6a:
```julia-repl
julia> @<TAB> using Dates
```
or
```julia-repl
julia> @tim<TAB> using Dates
```
don't complete at all the macro name if there's something else after the `@` sign.  This is a regression compared to all previous versions (v1.0 to v1.11)

### LINKED ISSUE #56389: Incorrect package-name autocompletion suggestion within `begin-end` block
At the top level, the completion suggestion is correct:
Image

However, within a `begin-end` block, the suggestion is incorrect:
Image

This issue happens on nightly.
```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.1515
Commit 9850a388122 (2024-10-29 21:02 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_EDITOR = subl
```
This appears to be a regression, as the suggestion is correct on v1.11.1:
Image

### LINKED ISSUE #57307: Regression in autocomplete for Julia 1.10
I feel like I discussed this with people before but there isn't an issue:

```
~> julia +1.9 -q 

julia> nt = (col1 = 5, secondcol = 6)
(col1 = 5, secondcol = 6)

julia> nt.col1 = nt.sec<TAB> # autocompletes

julia> exit()

~> julia +1.10 -q

julia> nt = (col1 = 5, secondcol = 6)
(col1 = 5, secondcol = 6)

julia> nt.col1 = nt.sec<TAB> # crickets
```

Still broken on 1.11.3, so I assume this is a JuliaSyntax thing?

### LINKED ISSUE #57611: [REPL] Autocompletion of `v = Module.Submodule.<TAB>` is broken
Yes another REPL autocompletion bug in 1.12.  On both 49263b78d49 (`release-1.12` branch) and a5157c0fc5631195aef5872fb2f7a4b09d1818ea (`master`)
```
platform = Base.BinaryPlatforms.<TAB>
```
doesn't complete anything.  Can be reproduced with any `Module.Submodule` name, not just `Base.BinaryPlatforms`, that's just an example.  Removing the left-hand side of the assignment solves the issue.  This is of course a regression, used to work correctly in v1.11-.  I believe this is distinct from [all other bugs I reported](https://github.com/JuliaLang/julia/issues?q=sort%3Aupdated-desc%20state%3Aopen%20label%3Acompletions%20label%3AREPL%20label%3Abug%20author%3Agiordano).

### LINKED ISSUE #57624: BoundsError when completing a Cmd-string in the REPL
Applies to 1.11 and nightly.

```
julia> `ls ~/De<TAB>┌ Error: Error in the keymap
│   exception =
│    BoundsError: attempt to access 8-codeunit String at index [16]
│    Stacktrace:
│      [1] _nextind_str
│        @ ./strings/string.jl:199 [inlined]
│      [2] nextind
│        @ ./strings/string.jl:193 [inlined]
│      [3] completions(string::String, pos::Int64, context_module::Module, shift::Bool, hint::Bool)
│        @ REPL.REPLCompletions ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:1278
│      [4] complete_line(c::REPL.REPLCompletionProvider, s::REPL.LineEdit.PromptState, mod::Module; hint::Bool)
│        @ REPL ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/REPL.jl:637
│      [5] complete_line(s::REPL.LineEdit.PromptState, repeats::Int64, mod::Module; hint::Bool)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:428
│      [6] complete_line(s::REPL.LineEdit.PromptState, repeats::Int64, mod::Module)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:427
│      [7] complete_line(s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:369
│      [8] edit_tab(s::REPL.LineEdit.MIState, jump_spaces::Bool, delete_trailing::Bool)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2419
│      [9] edit_tab
│        @ ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2419 [inlined]
│     [10] (::REPL.LineEdit.var"#118#174")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2465
│     [11] #invokelatest#2
│        @ ./essentials.jl:1055 [inlined]
│     [12] invokelatest
│        @ ./essentials.jl:1052 [inlined]
│     [13] (::REPL.LineEdit.var"#30#31"{REPL.LineEdit.var"#118#174", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:1711
│     [14] macro expansion
│        @ ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2861 [inlined]
│     [15] macro expansion
│        @ ./lock.jl:273 [inlined]
│     [16] (::REPL.LineEdit.var"#282#284"{REPL.Terminals.TTYTerminal, REPL.LineEdit.ModalInterface, REPL.LineEdit.MIState, ReentrantLock, REPL.LineEdit.Prompt})()
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2851
└ @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.3+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2863
```

### LINKED ISSUE #57772: !ismi^tab does not tab complete inside function call
The tab completion of !ismis works in the plain REPL but if I try to do that after I already typed an existing function it does not work anymore. 
The example is to do `sum(!ismis^tab` which should tab complete to `sum(!ismissing)` but doesn't. 

This is on julia 1.11.4 and on the current nightly   Commit b8dc57e59db (0 days old master)

### LINKED ISSUE #58099: autocompletion not working after `<:`
When I press `TAB` after
```
julia> Int <: Base.BitI
```
I get no completions. The similar line
```
julia> Int == Base.BitI
```
completes as expected to `Base.BitInteger`.

Tested on Julia 1.11.4.

### PR DESCRIPTION
**Pull request by xal-0**
# Overview

As we add REPL features, bugs related to the ad-hoc parsing done by
`REPLCompletions.completions` have crept in.  This pull request replaces most of
the manual parsing (regex, `find_start_brace`) with a new approach that parses
the entire input buffer once, before and after the cursor, using JuliaSyntax.
We then query the parsed syntax tree to determine the kind of completion
to be done.

# Changes
- New, JuliaSyntax-based completions mechanism.

- The `complete_line` interface now has the option of replacing arbitrary
  regions of text in the input buffer by returning a `Region` (`Pair{Int, Int}`
  for consistency with the convention in LineEdit, and `pos` being a 0-based
  byte offset).  ~~This is used to improve the handling of auto-inserted closing
  delimiters.~~. Leaving this unchanged for now.

- Fixes parsing-related bugs:
  - fix #55420
  - fix #55429
  - fix #55518
  - fix #55520
  - fix #55842
  - fix #56389
  - fix #57307
  - fix #57611
  - fix #57624
  - fix #58099

- Fixes some bugs that exist on 28d3bd56d36 that were found by fuzzing:
  - `x \"` + `TAB` throws a `FieldError` exception
  - String completion would sometimes delete the entire input buffer.
  - Completions should not happen inside comments.

- The duplicate code for path completion in strings, `Cmd`-strings, and the
  shell has been removed, causing paths to complete the same way for all three.
  Now, `~` is expanded in two situations:
  - If `foo` exists, or if `foo` does not exist but there are no
    possible completions:
    ```
    "~/foo/b|"     =TAB=>   "~/foo/bar|"
    "~/foo/bar|"   =TAB=>   "/home/user/foo/bar|"
       OR
    "~/foo/bar"|   =TAB=>   "/home/user/foo/bar"|
    ```

  - If the current path ends with a `/` and you hit TAB again:
    ```
    "~/foo/|"      =TAB=>   "/home/user/foo/|"
       OR
    "~/foo/"|      =TAB=>   "/home/user/foo/"|
    ```

# Future work
- Method completions could be changed to look for methods with exactly the given
  number of arguments if the closing `)` is present, and search for signatures
  with the right prefix otherwise.

    - It would be nice to be able to search by type as well as value (perhaps
      by putting `::T` in place of arguments).

- Other REPL features could benefit from JuliaSyntax, so it might be worth
  sharing the parse tree between completions and other features:

    - Emacs-style sexpr navigation: `C-M-f`/`C-M-b`/`C-M-u`, etc.
    - Improved auto-indent.

- It would be nice if hints worked even when the cursor is between text.

- `CursorNode` is a slightly tweaked copy of `SyntaxNode` from JuliaSyntax that
  tracks the parent node but includes all trivia.  It is used with `seek_pos`,
  which navigates to the innermost node at a given position so we can examine
  nearby nodes and the parent.  This could probably duplicate less code from
  JuliaSyntax.

### CODE REVIEW

**Comment by IanButterworth** [comment]
This sounds great! I think we should backport it to at least 1.12 given it fixes so many issues.

File: stdlib/REPL/test/replcompletions.jl [hunk 1]
```diff
@@ -2484,3 +2494,43 @@ let (c, r, res) = test_complete_context("global xxx::Number = Base.", Main)
...
+    @test "type_test" in c
+    @test r == 28:32
+    @test s[r] == "type_"
+end
+
+# #55518
+let s = "CompletionFoo.@barfoo kwtest"
+    c, r = test_complete(s)
+    @test isempty(c)
+end
```
Comment (giordano) [inline stdlib/REPL/test/replcompletions.jl:2522]: I'm not sure this quite cover all the broken cases reported in #55518 (there are a few scattered in the discussion)

**Review by giordano — COMMENTED** [review]
@xal-0 first of all, speaking as the author of most of the issues linked to this PR, thank you for tackling this!

Also, can you please add a test for #57772 as well?  I verified this works already (which is amazing!)

**Comment by StefanKarpinski** [comment]
Bravo. Truly excellent quality-of-life PR 👏🏻

**Comment by giordano** [comment]
> Bravo. Truly excellent quality-of-life PR 👏🏻

Best part is that this PR has a negative diff, depsite the fact it added many tests.

File: stdlib/REPL/test/replcompletions.jl [hunk 2]
```diff
@@ -158,6 +158,10 @@ let ex =
             export exported_symbol
             exported_symbol(::WeirdNames) = nothing
 
+            macro ignoremacro(e...)
+                :nothing
```
Comment (giordano) [inline stdlib/REPL/test/replcompletions.jl:162]: Should this be
```suggestion
                nothing
```
?
```julia-repl
julia> macro ignoremacro(e...)
           :nothing
       end
@ignoremacro (macro with 1 method)

julia> @macroexpand @ignoremacro
:(Main.nothing)

julia> macro ignoremacro(e...)
           nothing
       end
@ignoremacro (macro with 1 method)

julia> @macroexpand @ignoremacro

julia> 
```

Comment (xal-0) [reply stdlib/REPL/test/replcompletions.jl:162]: I was actually unaware that so many things were self-quoting!

File: stdlib/REPL/test/replcompletions.jl (hunk 1 above)
Comment (xal-0) [reply stdlib/REPL/test/replcompletions.jl]: I've added a few more from the thread

File: stdlib/REPL/test/replcompletions.jl [hunk 3]
```diff
@@ -2484,3 +2502,109 @@ let (c, r, res) = test_complete_context("global xxx::Number = Base.", Main)
...
+    @test r == 1:4
+end
+
+# #56389
+let s = "begin\n  using Linear"
+    c, r = test_complete(s)
+    @test "LinearAlgebra" in c
+    @test r == 15:20
+    @test s[r] == "Linear"
+end
```
Comment (IanButterworth) [inline stdlib/REPL/test/replcompletions.jl:2518]: This doesn't pass when run via `Pkg.test("REPL")` because `Base.runtests` puts all stdlibs on the load path, whereas `Pkg.test` only does REPL deps and test deps.
```suggestion
let s = "begin\n  using Ran"
    c, r = test_complete(s)
    @test "Random" in c
    @test r == 15:17
    @test s[r] == "Ran"
end
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 4]
```diff
@@ -1550,44 +1326,52 @@ function shell_completions(string, pos, hint::Bool=false)
...
+        cmd_escape && (p = do_cmd_escape(p))
+        p
+    end
+
+    paths, dir, success = complete_path(path; contract_user=expanded, shell_escape, cmd_escape, string_escape, kws...)
+    dir = dir == "" ? dir : escape(dir)
+
+    # Expand '~' if the user hits TAB after exhausting completions (either
+    # because we have found an existing file, or there is no such file).
+    full_path = ispath(path) || isempty(paths)
```
Comment (IanButterworth) [inline stdlib/REPL/src/REPLCompletions.jl:1364]: I found two cases that can cause `ispath` to error, so I think we should make a `safe_ispath`

Something like this? Or just never throw and just return false?
```
function safe_ispath(path::AbstractString)
    try
        return ispath(path)
    catch err
        if err isa Base.IOError # i.e. name too long (ENAMETOOLONG)
            return false
        elseif err isa Base.ArgumentError && occursin("embedded NULs", err.msg)
            return false
        else
            rethrow()
        end
    end
end
```

Comment (xal-0) [reply stdlib/REPL/src/REPLCompletions.jl:1364]: I'll avoid modifying Base for the time being because we already convert some `access(2)` return values to `false`.  It feels a little hacky to keep adding exceptions here. https://github.com/JuliaLang/julia/blob/bc98abcfbe392d2a0a09ed631b85f4675a34b380/base/stat.jl#L376-L379

Of the errors that could be returned for `F_OK` that we might want to handle, it looks like we're missing `EACCES`, `EIO`, `ELOOP`, and `ENAMETOOLONG`.

**Comment by xal-0** [comment]
`isdir` suffers from similar problems as `ispath`. On Windows, `isdir("D:\\")` can fail if no disc is inserted, because libuv doesn't handle `ERROR_NOT_READY`:

```
julia> isdir("D:\\")
ERROR: IOError: stat("D:\\"): unknown error (UNKNOWN)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:106 [inlined]
 [2] checkstat
   @ .\stat.jl:186 [inlined]
 [3] stat(path::String)
   @ Base.Filesystem .\stat.jl:192
 [4] isdir(path::String)
   @ Base.Filesystem .\stat.jl:586
 [5] top-level scope
   @ REPL[1]:1
```

**Comment by xal-0** [comment]
I am going to disable the shell completion tests until the shell mode can parse Windows paths...
```
shell> cd C:\Users
ERROR: IOError: cd("C:Users"): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:106 [inlined]
 [2] cd(dir::String)
   @ Base.Filesystem .\file.jl:91
 [3] repl_cmd(cmd::Cmd, out::Base.TTY)
   @ Base .\client.jl:64
 [4] top-level scope
   @ none:1
```

**Comment by vtjnash** [comment]
> until the shell mode can parse Windows paths

The shell mode has no problem with Windows paths which is why the REPL has tests for it. It just sounds like you lost a call to `Base.shell_escape` on that code path.

File: stdlib/REPL/src/REPLCompletions.jl [hunk 5]
```diff
@@ -302,16 +304,23 @@ const sorted_keyvals = ["false", "true"]
 complete_keyval!(suggestions::Vector{Completion}, s::String) =
     complete_from_list!(suggestions, KeyvalCompletion, sorted_keyvals, s)
 
-function do_raw_escape(s)
-    # escape_raw_string with delim='`' and ignoring the rule for the ending \
-    return replace(s, r"(\\+)`" => s"\1\\`")
+function do_cmd_escape(s)
+    return Base.shell_escape_posixly(Base.escape_raw_string(s, '`'))
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:308]: This seems like nonsense: I can't think of any case where we'd expect it'd be useful for the the REPL to pass the string unmodified to a posix shell for use as an argument in a julia script, which is what this transform order implements.

The previous transform took a string `text` that was already in posix-shell form (e.g. for raw input to shell_parse for `shell> text` mode) and corrects it for the julia parser (e.g. for ``:(`text`)``)
```
julia> a = `\\ b\\\\`
`'\' 'b\'`
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 6]
```diff
@@ -1136,399 +957,352 @@ function get_loading_candidates(pkgstarts::String, project_file::String)
     return loading_candidates
 end
 
-function complete_loading_candidates!(suggestions::Vector{Completion}, pkgstarts::String, project_file::String)
-    for name in get_loading_candidates(pkgstarts, project_file)
-        push!(suggestions, PackageCompletion(name))
+function complete_loading_candidates!(suggestions::Vector{Completion}, s::String)
+    for name in ("Core", "Base")
```
[the remark this answers is not in the document]
Comment (xal-0) [reply stdlib/REPL/src/REPLCompletions.jl:962]: Do you have an example where it misbehaves? This should only fire when we're completing the first component of an import path with no leading dots.

File: stdlib/REPL/src/REPLCompletions.jl (hunk 5 above)
Comment (xal-0) [reply stdlib/REPL/src/REPLCompletions.jl:308]: I intended `cmd_escape` to make it possible to complete shell commands inside Cmd-strings, but mixed up the order (``Base.escape_raw_string(Base.shell_escape_posixly(s), '`')`` does what I want I think):
```
julia> println(R.do_cmd_escape("file ` 1"))
'file \` 1'

julia> @macroexpand `'file \` 1'`
:(Base.cmd_gen((("file ` 1",),)))
```

Comment (xal-0) [reply stdlib/REPL/src/REPLCompletions.jl:308]: Completion with `shell_escape_posixly` is still unwieldy because you get partial completions that insert only the opening quote, and can't complete any further.

**Comment by IanButterworth** [comment]
What's the status of this? I'm just wondering whether it's worth getting it in and continuing work in PRs?

**Comment by xal-0** [comment]
With the REPL completions working well enough on Windows again, this is ready for review again. 👍

File: stdlib/REPL/src/REPLCompletions.jl (hunk 6 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply stdlib/REPL/src/REPLCompletions.jl:970]: Oh, right, I switched the argument order of startswith in my head and was just confused

**Comment by KristofferC** [comment]
🎤 ⬇️

**Comment by IanButterworth** [comment]
As someone who tried and failed to fix the issues this closes by patching the old approach, thank you for fixing this properly!
