### PR TITLE
fix #31993, intersection of `Type{Vec}` and `Type{<:Vec{T}}`

### LINKED ISSUE #31993: ambiguity error with non-applicable methods
```julia
julia> g(::Type{<:AbstractVector{T}}, ::Int) where {T} = 1

julia> g(Vector, 1)
ERROR: MethodError: no method matching g(::Type{Array{T,1} where T}, ::Int64)
Closest candidates are:
  g(::Type{#s1} where #s1<:AbstractArray{T,1}, ::Int64) where T at REPL[1]:1
Stacktrace:
 [1] top-level scope at REPL[2]:1

julia> g(::Type{Vector}, ::Any) = 2

julia> g(Vector, 1)
ERROR: MethodError: g(::Type{Array{T,1} where T}, ::Int64) is ambiguous. Candidates:
  g(::Type{#s1} where #s1<:AbstractArray{T,1}, ::Int64) where T in Main at REPL[1]:1
  g(::Type{Array{T,1} where T}, ::Any) in Main at REPL[3]:1
Possible fix, define
  g(::Type{Array{T,1} where T}, ::Int64)
Stacktrace:
 [1] top-level scope at REPL[4]:1

julia> f() = g(Vector, 1); f() # works on Julia 1.1 ! But errors on master
2
```
The last line with `f` is the reason why tests in my package where passing on 1.1 but not on master.

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #31993

### CODE REVIEW

File: test/subtype.jl [hunk 1]
```diff
@@ -1529,3 +1529,16 @@ end
...
+@testintersect(Tuple{Type{<:AbstractVector{T}}, Int} where T,
+               Tuple{Type{Vector}, Any},
+               Union{})
+@testintersect(Tuple{Type{<:AbstractVector{T}}, Int} where T,
+               Tuple{Type{Vector{T} where Int<:T<:Int}, Any},
+               Tuple{Type{Vector{Int}}, Int})
+let X = LinearAlgebra.Symmetric{T, S} where S<:(AbstractArray{U, 2} where U<:T) where T,
+    Y = Union{LinearAlgebra.Hermitian{T, S} where S<:(AbstractArray{U, 2} where U<:T) where T,
+              LinearAlgebra.Symmetric{T, S} where S<:(AbstractArray{U, 2} where U<:T) where T}
+    @test X <: Y
```
Comment (rfourquet) [inline test/subtype.jl]: I'm out of my depth here, but just in case: this test passes already, is there a typo?

Comment (JeffBezanson) [reply test/subtype.jl]: Yes, it passes on master, but didn't pass with one version of this change I tried (found by an assertion failure during the build).

**Review by Keno — APPROVED** [review]
