### PR TITLE
Multiversioning: support for aliases (from @ccallable)

### LINKED ISSUE #34064: "LLVM ERROR: Broken module found, compilation aborted!" when compiling a sysimage with a ccallable function and a certain cpu target
When trying to change the cpu target used when generating "apps" in PackageCompiler (https://github.com/KristofferC/PackageCompilerX.jl/pull/43) with the "app" at (https://github.com/KristofferC/PackageCompilerX.jl/blob/master/examples/MyApp/src/MyApp.jl) I hit the following CI error

Linux (https://travis-ci.com/KristofferC/PackageCompilerX.jl/jobs/265321335#L264-L267):
```
<unknown>: error: Cannot represent a difference across sections
Aliasee should be either GlobalValue or ConstantExpr
i32 ()* @julia_main
LLVM ERROR: Broken module found, compilation aborted!
```

Mac (https://travis-ci.com/KristofferC/PackageCompilerX.jl/jobs/265321336#L197-L212);
```
signal (11): Segmentation fault: 11
in expression starting at none:0
_ZN12_GLOBAL__N_119X86MachObjectWriter16recordRelocationEPN4llvm16MachObjectWriterERNS1_11MCAssemblerERKNS1_11MCAsmLayoutEPKNS1_10MCFragmentERKNS1_7MCFixupENS1_7MCValueERy at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm16MachObjectWriter16recordRelocationERNS_11MCAssemblerERKNS_11MCAsmLayoutEPKNS_10MCFragmentERKNS_7MCFixupENS_7MCValueERy at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm11MCAssembler6layoutERNS_11MCAsmLayoutE at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm11MCAssembler6FinishEv at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN12_GLOBAL__N_115MCMachOStreamer10FinishImplEv at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm10MCStreamer6FinishEv at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm10AsmPrinter14doFinalizationERNS_6ModuleE at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm13FPPassManager14doFinalizationERNS_6ModuleE at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /Users/travis/julia/lib/julia/libLLVM.dylib (unknown line)
operator() at /Users/sabae/buildbot/worker/package_macos64/build/src/jitlayers.cpp:1086 [inlined]
jl_dump_native at /Users/sabae/buildbot/worker/package_macos64/build/src/jitlayers.cpp:1095
jl_write_compiler_output at /Users/sabae/buildbot/worker/package_macos64/build/src/precompile.c:93
jl_atexit_hook at /Users/sabae/buildbot/worker/package_macos64/build/src/init.c:230
main at /Users/travis/julia/bin/julia (unknown line)
```

It can be reprod on the linked branch above with pwd in the root git repo and running:

```
using PackageCompilerX
 create_sysimage(:MyApp, sysimage_path="MyApp.so", cpu_target="generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)", project="examples/MyApp", incremental=false)
```

Note that `incremental=false` seems to be needed (which means that a new sysimage is bootstrapped from scratch (`corecompiler.ji` -> `sys.ji` -> `sys.o`).

I can reduce it to just a set of raw commands if that would be helpful.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaLang/julia/issues/34064, cc @KristofferC, verified with https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x64/1.6/julia-c2db4248a9-linux64.tar.gz (from https://github.com/JuliaLang/julia/pull/37510, which includes the change) where the MWE from https://github.com/JuliaLang/julia/issues/34064 works:

```
julia> app_content = """
       Base.@ccallable function julia_main()::Cint
           return 0
       end
       """
"Base.@ccallable function julia_main()::Cint\n    return 0\nend\n"

julia> # Create the sysimage
       cmd = `$(get_julia_cmd()) --sysimage=$tmp_sys_ji --cpu-target='generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)'
                                 --output-o=sys.o -e $app_content`
`/tmp/julia-c2db4248a9/bin/julia --color=yes --startup-file=no --sysimage=/tmp/julia-c2db4248a9/sys.ji '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' --output-o=sys.o -e 'Base.@ccallable function julia_main()::Cint
    return 0
end
'`

julia> run(cmd)
Process(`/tmp/julia-c2db4248a9/bin/julia --color=yes --startup-file=no --sysimage=/tmp/julia-c2db4248a9/sys.ji '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' --output-o=sys.o -e 'Base.@ccallable function julia_main()::Cint
    return 0
end
'`, ProcessExited(0))
```

### CODE REVIEW

**Comment by yuyichao** [comment]
I don't think this is correct. If the function is cloned then all uses of it, including global aliases must be updated.

**Comment by maleadt** [comment]
> I don't think this is correct. If the function is cloned then all uses of it, including global aliases must be updated.

Yeah, this was a quick fix that happened to work :slightly_smiling_face: Don't we keep the original functions for aliases to point to? From my reading of `fix_gv_uses`, we save global variable addresses to relocate at run time, but with aliases we can't do that?

**Comment by yuyichao** [comment]
Correct, it was not supported and doesn't have a trivial fix https://github.com/JuliaLang/julia/pull/21849#pullrequestreview-68125998 .

There are basically two options,

1. Do not clone a function if there's a global alias pointing to it. (will need to update the `clone_all` check). This will also need to add assertions to make sure the calling convention isn't broken. (no vector type allowed in the argument/return value)

2. Emit a wrapper function for global alias. Two suboptions for this one.

    1. This can be either done via a normal function, which suffers from the same no vector register constraint.
    2. Or done with an module level assembly to emit an architecture depending tail call.

**Comment by yuyichao** [comment]
Also ref https://github.com/JuliaLang/julia/pull/21849#issuecomment-336201502 which is essentially about the second option above.

**Comment by maleadt** [comment]
I went with the custom trampoline + slot option, which seems to work nicely for the `@ccallable` stuff I'm introducing in https://github.com/JuliaLang/julia/pull/37510:

```
julia> Float16(1.)

Thread 1 "julia" hit Breakpoint 1, 0x00007fffecd6e250 in __truncdfhf2 () from usr/lib/julia/sys.so
(gdb) disassemble
Dump of assembler code for function __truncdfhf2:
=> 0x00007fffecd6e250 <+0>:     push   %rax
   0x00007fffecd6e251 <+1>:     mov    0x507bba0(%rip),%rax        # 0x7ffff1de9df8 <__truncdfhf2.reloc_slot>
   0x00007fffecd6e258 <+8>:     pop    %rcx
   0x00007fffecd6e259 <+9>:     jmpq   *%rax
End of assembler dump.
(gdb) ni 4
0x00007fffec565950 in jlcapi___truncdfhf2_17404 () from usr/lib/julia/sys.so
```

File: src/llvm-multiversioning.cpp [hunk 1]
```diff
@@ -697,18 +698,59 @@ Constant *CloneCtx::rewrite_gv_init(const Stack& stack)
...
+{
+    Function *F = cast<Function>(alias->getAliasee());
+
+    auto Name = alias->getName();
+    alias->setName("");
+    Function *trampoline =
+        Function::Create(F->getFunctionType(), alias->getLinkage(), Name, &M);
+    trampoline->copyAttributesFrom(F);
+    alias->eraseFromParent();
+    GlobalVariable *slot =
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:712]: I believe this can use the cached version `get_reloc_slot`.

File: src/llvm-multiversioning.cpp [hunk 2]
```diff
@@ -697,18 +698,59 @@ Constant *CloneCtx::rewrite_gv_init(const Stack& stack)
     return res;
 }
 
+// replace an alias to a function with a trampoline and (uninitialized) global variable slot
+std::pair<Function *, GlobalVariable *> CloneCtx::rewrite_alias(GlobalAlias *alias)
+{
+    Function *F = cast<Function>(alias->getAliasee());
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:704]: And we need to check to make sure the calling convension is unchanged. For now an `assert(!is_vector(F->getFunctionType()))` should be enough.

File: src/llvm-multiversioning.cpp (hunk 1 above)
Comment (maleadt) [reply src/llvm-multiversioning.cpp:712]: I originally did so, but those slots are of type `void*` whereas the initializer set by `fix_gv_uses` / `rewrite_gv_init` has the original function type.

Comment (yuyichao) [reply src/llvm-multiversioning.cpp:712]: The type shouldn't matter at all. The one for gv has the type only because it is not used by anyone else and the slot is already there so there isn't any better option.

Comment (maleadt) [reply src/llvm-multiversioning.cpp:712]: LLVM doesn't like it though:
```
llvm-9.0.1/lib/IR/Globals.cpp:394: void llvm::GlobalVariable::setInitializer(llvm::Constant*): Assertion `InitVal->getType() == getValueType() && "Initializer type must match GlobalVariable type"' failed.
```

Comment (yuyichao) [reply src/llvm-multiversioning.cpp]: It shouldn't need any initialization.

File: src/llvm-multiversioning.cpp [hunk 3]
```diff
@@ -697,18 +698,59 @@ Constant *CloneCtx::rewrite_gv_init(const Stack& stack)
...
+
+    auto ptr = irbuilder.CreateLoad(F->getType(), slot);
+    ptr->setMetadata(llvm::LLVMContext::MD_tbaa, tbaa_const);
+    ptr->setMetadata(llvm::LLVMContext::MD_invariant_load, MDNode::get(ctx, None));
+
+    std::vector<Value *> Args;
+    for (auto &arg : trampoline->args())
+        Args.push_back(&arg);
+    auto call = irbuilder.CreateCall(ptr, makeArrayRef(Args));
+    call->setTailCallKind(CallInst::TCK_MustTail);
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:727]: See the check in `ccall.cpp` regarding vararg function and musttail. It doesn't work everywhere and it should check for vararg functions on unsupported platforms and abort.

File: src/llvm-multiversioning.cpp [hunk 4]
```diff
@@ -697,18 +698,59 @@ Constant *CloneCtx::rewrite_gv_init(const Stack& stack)
...
+
+    if (F->getReturnType() == T_void)
+        irbuilder.CreateRetVoid();
+    else
+        irbuilder.CreateRet(call);
+
+    return std::make_pair(trampoline, slot);
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:734]: No need to return anything. Just use the shared slot.

File: src/llvm-multiversioning.cpp [hunk 5]
```diff
@@ -697,18 +698,59 @@ Constant *CloneCtx::rewrite_gv_init(const Stack& stack)
...
+}
+
 void CloneCtx::fix_gv_uses()
 {
     auto single_pass = [&] (Function *orig_f) {
         bool changed = false;
         for (auto uses = ConstantUses<GlobalValue>(orig_f, M); !uses.done(); uses.next()) {
-            changed = true;
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:705]: This change isn't needed. A use should always be fixed.

**Review by yuyichao — CHANGES_REQUESTED** [review]

File: src/llvm-multiversioning.cpp [hunk 6]
```diff
@@ -697,6 +696,48 @@ Constant *CloneCtx::rewrite_gv_init(const Stack& stack)
...
+    ptr->setMetadata(llvm::LLVMContext::MD_tbaa, tbaa_const);
+    ptr->setMetadata(llvm::LLVMContext::MD_invariant_load, MDNode::get(ctx, None));
+
+    std::vector<Value *> Args;
+    for (auto &arg : trampoline->args())
+        Args.push_back(&arg);
+    auto call = irbuilder.CreateCall(ptr, makeArrayRef(Args));
+    call->setTailCallKind(CallInst::TCK_MustTail);
+    // musttail support is very bad on ARM, PPC, PPC64 (as of LLVM 3.9)
+    // Known failures includes vararg and sret.
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:729]: See the comment you copied. `musttail` cannot be used unconditionally (not for `sret`). It should also not be needed for non-vararg so just setting it for `vararg` functions should be fine. In other cases `tail` should be used instead.

File: src/llvm-multiversioning.cpp [hunk 7]
```diff
@@ -707,8 +748,15 @@ void CloneCtx::fix_gv_uses()
             auto info = uses.get_info();
             // We only support absolute pointer relocation.
             assert(info.samebits);
-            // And only for non-constant global variable initializers
-            auto val = cast<GlobalVariable>(info.val);
+            GlobalVariable *val;
+            if (auto alias = dyn_cast<GlobalAlias>(info.val)) {
+                rewrite_alias(alias);
+                uint32_t id;
+                std::tie(id, val) = get_reloc_slot(orig_f);
```
Comment (yuyichao) [inline src/llvm-multiversioning.cpp:755]: [As I said](https://github.com/JuliaLang/julia/pull/37530#discussion_r487687922), there should be no need to do anything here, just `continue` should be fine. You can leave the `auto val = cast<GlobalVariable>(info.val);` line unchanged after the `GlobalAlias` branch.
The reason I said you don't need return value is because you don't need them, not because you can get it again after returning nothing......

Also, to be padentic, you want to pass in `orig_f` to `rewrite_alias` and use that to do the lookup instead. I think global alias allows constant expression and we accept it as long as it's a simple cast. (asserted above).
Since we are emitting a function, we **could** accept more complicated expressions here but that's not necessary for now....

**Review by yuyichao — DISMISSED** [review]

File: src/llvm-multiversioning.cpp (hunk 7 above)
Comment (maleadt) [reply src/llvm-multiversioning.cpp:755]: But then the GV never gets initialized because `gv_relocs.emplace_back(addr, fid);` doesn't get hit. And having `rewrite_alias` add a use of `orig_f` seems like it would invalidate the `uses` iterator?

Comment (yuyichao) [reply src/llvm-multiversioning.cpp:755]: > `gv_relocs.emplace_back(addr, fid);`

This should not be needed and that's whole point of using the global slot everyone else uses instead of creating a new one. Special initialization of global variables are only needed because they are different from the normal ones returned by `get_reloc_slot`.

>  having rewrite_alias add a use of orig_f

Nothing like that should be needed and in fact it is not valid to do so. The global variables are all NULL initialized. `orig_f` isn't used by anyone.

Comment (maleadt) [reply src/llvm-multiversioning.cpp:755]: Then how does the runtime know how to initialize that slot? `get_reloc_slot` doesn't register it.
With `rewrite_alias` using `get_reloc_slot` (i.e. not creating a custom one) and:

```patch
@@ -750,9 +750,8 @@ void CloneCtx::fix_gv_uses()
             assert(info.samebits);
             GlobalVariable *val;
             if (auto alias = dyn_cast<GlobalAlias>(info.val)) {
-                rewrite_alias(alias);
-                uint32_t id;
-                std::tie(id, val) = get_reloc_slot(orig_f);
+                rewrite_alias(alias, orig_f);
+                continue;
             }
```

```
julia> Float16(1.0)

Thread 1 "julia" hit Breakpoint 1, 0x00007fffecc0a740 in __truncdfhf2 () from /home/tim/Julia/julia/build/release/usr/lib/julia/sys.so
(gdb) disassemble
Dump of assembler code for function __truncdfhf2:
=> 0x00007fffecc0a740 <+0>:     jmpq   *0x51db222(%rip)        # 0x7ffff1de5968 <jlcapi___truncdfhf2_21535.reloc_slot>
End of assembler dump.
(gdb) ni
0x0000000000000000 in ?? ()
(gdb) c
Continuing.

Thread 1 "julia" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
```

Comment (yuyichao) [reply src/llvm-multiversioning.cpp:755]: Hmmm, it does register it in `const_relocs`.

Comment (yuyichao) [reply src/llvm-multiversioning.cpp:755]: I seems that the issue could be this function not being in `fvars`? I'm not sure if that's even supported.

Comment (maleadt) [reply src/llvm-multiversioning.cpp:755]: > I seems that the issue could be this function not being in `fvars`?

Yes, that seems to be the case. I had a quick look but the way `jl_sysimg_fvars` is populated in `jl_create_native` and how that ought to work with `jl_compile_extern_c` is not obvious.

Comment (maleadt) [reply src/llvm-multiversioning.cpp]: If I put the C wrapper in `fvars` (https://github.com/JuliaLang/julia/pull/37530/commits/8064e00e1aa63d86277a662c6c42f14ddbbe6c71), multiversioning seems to work: the original function now gets a proper ID, I get an entry in `jl_dispatch_reloc_slots`, etc

```
@jl_dispatch_fvars_offsets = constant [860 x i32] [i32 trunc (i64 sub (i64 ptrtoint (void ()* @jlcapi_dummy_ccallable_2883.clone_1 to i64), i64 ptrtoint (void ()* @jlcapi_dummy_ccallable_2883 to i64)) to i32), ...]

@jl_sysimg_fvars_base = alias i64, bitcast (void ()* @jlcapi_dummy_ccallable_2883 to i64*)
```

At run-time however the slot is not initialized and I still get a nullptr SEGV.

Comment (maleadt) [reply src/llvm-multiversioning.cpp]: Did some more debugging, and it looks like the slots generated for the newly-created alias GVs are never listed in `jl_dispatch_fvars_idxs`, so no relocation ever happens (the run-time logic just skips past them). Other GVs are explicitly added to `gv_relocs`, which is then used to populate `shared_relocs` resulting in an entry in `jl_dispatch_fvars_idxs`. By reusing `get_reloc_slot`, which adds to `const_relocs`, that doesn't happen.
Could you explain the logic how non-GV slots are chosen to be listed in `jl_dispatch_fvars_idxs`, and/or how to adapt that for this case? Just push them to `gv_relocs` manually?

Comment (yuyichao) [reply src/llvm-multiversioning.cpp]: OK, I missed the mutation of the `fvars` in `get_func_id` which is why I thought this isn't supposed to work but yes it should work. The point was to basically use the logic for instruction relocation rather than global variable one since this is what you are doing. The missing part is that you need to record that this function needs to be relocated for the target. This is done by pushing the id into the `relocs` set for the group and the target. Something like,

```c++
    for (auto &grp: groups) {
        grp.relocs.insert(id);
        for (auto &tgt: grp.clones) {
            tgt.relocs.insert(id);
        }
    }
```

within `rewrite_alias` after you got the `id`.

Comment (maleadt) [reply src/llvm-multiversioning.cpp]: That works for target 0 | CLONE_ALL, but doesn't cover https://github.com/JuliaLang/julia/blob/2898b93264a4dfed09a30251af00b54f37cb1e1d/src/llvm-multiversioning.cpp#L1053-L1057

I guess I want `tgt.vmap[base_f] = base_f` here, but `map_get` is designed to skip over such identical mappings.

**Comment by yuyichao** [comment]
The way the information is collected is more or less OK I guess. There are still a few other issues though. The module merger doesn't seem to handle use of `@ccallable` functions very well, the use of the alias should also be fixed, and there are still a few old changes here that should be removed. I'm testing locally.

**Comment by maleadt** [comment]
Any update, @yuyichao? I had hoped to get this in 1.6.

**Comment by yuyichao** [comment]
Not before the build on master is unbroken...

**Comment by yuyichao** [comment]
Also, if the goal is https://github.com/JuliaLang/julia/pull/37510#issuecomment-693613477, this is not really valid.

**Comment by maleadt** [comment]
> Also, if the goal is [#37510 (comment)](https://github.com/JuliaLang/julia/pull/37510#issuecomment-693613477), this is not really valid.

Why not? I get that there's issues with GC across the proposed runtime functions, but wouldn't it be OK for these simple methods? I'd like to move to compiler-rt at some point, but this seems like the least invasive option, reusing our existing software implementation around (without having to reimplement it in C).

**Comment by yuyichao** [comment]
> it be OK for these simple methods?

There's no such guarantee. And cfunction does interact with runtime.

> I'd like to move to compiler-rt at some point, but this seems like the least invasive option, reusing our existing software implementation around (without having to reimplement it in C).

What's wrong with reimplement it in C? These are basically C functions already. They don't use any fancy features for generic code, they use trivial calling conventions, everything is statically typed and the document linked in the code uses C as well. This doesn't have to be in compiler-rt, libjulia would be fine and if the plan is to move to compiler-rt, having a working C version should be a good start.

**Comment by maleadt** [comment]
Rebased.

@yuyichao, could you give this another look?

@KristofferC Verified that this still fixes the issue (the MWE from https://github.com/JuliaLang/julia/issues/34064#issuecomment-563465109). I did run into an LLVM assertion failure in some of the code added here, but can't reproduce that anymore; could you give this a quick spin to see if you can?

**Comment by KristofferC** [comment]
I do in fact get an assertion with this PR:

```
❯ ./bin/MyApp
Assertion failed: (success), function jl_reinit_item, file /Users/kristoffercarlsson/julia/src/staticdata.c, line 1455.
[1]    63440 abort      ./bin/MyApp
```


Example repro (in PackageCompiler repo):

```
using PackageCompiler
create_app("examples/MyApp/", "/tmp/MyAppCompiled";force=true, incremental=true, cpu_target="native")
run(`/tmp/MyAppCompiled/bin/MyApp`)
```

**Comment by maleadt** [comment]
Verified to fix the linked PackageCompiler issue, so let's go ahead and merge this.
