### PR TITLE
Check output dimensions for 2x2 and 3x3 in-place matmuls

### LINKED ISSUE #382: Lack of DimensionMismatch error for A_mul_B! with small matrices
Behavior for 'big' matrices:
```julia
A = rand(6, 6)
B = rand(5, 5)
C = rand(5, 5)
A_mul_B!(A, B, C)
```
results in
```
ERROR: DimensionMismatch("A has size (5,5), B has size (5,5), C has size (6,6)")
```

However,
```julia
A = rand(6, 6)
B = rand(3, 3)
C = rand(3, 3)
A_mul_B!(A, B, C)
```
does not produce an error.

### LINKED ISSUE #19224: Lack of DimensionMismatch error for A_mul_B! with small matrices
Behavior for 'big' matrices:
```julia
A = rand(6, 6)
B = rand(5, 5)
C = rand(5, 5)
A_mul_B!(A, B, C)
```
results in
```
ERROR: DimensionMismatch("A has size (5,5), B has size (5,5), C has size (6,6)")
```

However,
```julia
A = rand(6, 6)
B = rand(3, 3)
C = rand(3, 3)
A_mul_B!(A, B, C)
```
does not produce an error.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes JuliaLang/LinearAlgebra.jl#382

`matmul2x2!` and `matmul3x3!` currently don't check whether the destination array is actually 2x2 or 3x3, respectively. Larger matrices go through `Base.BLAS.gemm!`, which performs such a check. This makes the behavior consistent, thereby fixing the linked issue.

### CODE REVIEW

File: base/linalg/matmul.jl [hunk 1]
```diff
@@ -656,6 +656,7 @@ function matmul2x2{T,S}(tA, tB, A::AbstractMatrix{T}, B::AbstractMatrix{S})
 end
 
 function matmul2x2!{T,S,R}(C::AbstractMatrix{R}, tA, tB, A::AbstractMatrix{T}, B::AbstractMatrix{S})
+    size(C) == (2, 2) || throw(DimensionMismatch("Destination matrix is not 2×2"))
```
Comment (KristofferC) [inline base/linalg/matmul.jl]: In my opinion, this error message would be better to look identical to the one from the larger matrix case.

Comment (ararslan) [inline base/linalg/matmul.jl]: Good call. Will fix.

Comment (ararslan) [inline base/linalg/matmul.jl]: Updated. I just copied the checking code from `Base.BLAS.gemm!` so hopefully that should everything entirely consistent.

**Review by andreasnoack — APPROVED** [review]

**Comment by ararslan** [comment]
Looking back at this, the size check seems unnecessarily complex; it seems to me that it could more clearly be expressed as
```julia
size(A) == size(B) == size(C) == (3,3)
```
Does that seem like a worthwhile simplification?

**Comment by ararslan** [comment]
Great. Size check simplified.

**Comment by ararslan** [comment]
Is this good to go?
