### PR TITLE
fix #21369, exception state overwritten by caught internal errors

### LINKED ISSUE #21369: Mistaken inference error on first call
Distilled from ImageMagick.jl:
```julia
mapIM(x::Number) = x

function breaks(img, mapi=identity)
    local imgw
    try
        imgw = map(x->mapIM(mapi(x)), img)
    catch
        warn("this type didn't work")
        rethrow()
    end
end

mutable struct TestType end

breaks([TestType() TestType()])
```

Upon usage:
```julia
julia> include("/home/tim/tmp/im_bug.jl")
WARNING: this type didn't work
ERROR: LoadError: TypeError: Dense: in T, expected T<:Union{Complex{Float64}, Float64}, got Type{StackFrame}
Stacktrace:
 [1] _methods_by_ftype(::Any, ::Int64, ::UInt64, ::Array{UInt64,1}, ::Array{UInt64,1}) at ./reflection.jl:521
 [2] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1267
 [3] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1864
 [4] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1894
 [5] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1917
 [6] copy!(::Array{Any,1}, ::Core.Inference.Generator{Array{Any,1},Core.Inference.##187#188{Array{Any,1},Core.Inference.InferenceState}}) at ./abstractarray.jl:565
 [7] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1868
 [8] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1917
 [9] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2040
 [10] typeinf_frame(::Core.Inference.InferenceState) at ./inference.jl:2704
 [11] typeinf_loop(::Core.Inference.InferenceState) at ./inference.jl:2603
 [12] typeinf_frame(::Core.MethodInstance, ::Core.Inference.InferenceState, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2473
 [13] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2496
 [14] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1386
 [15] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1864
 [16] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1894
 [17] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1917
 [18] typeinf_frame(::Core.Inference.InferenceState) at ./inference.jl:2757
 [19] typeinf_loop(::Core.Inference.InferenceState) at ./inference.jl:2603
 [20] typeinf_frame(::Core.MethodInstance, ::Core.Inference.InferenceState, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2473
 [21] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2496
 [22] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1386
 [23] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1864
 [24] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1894
 [25] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1917
 [26] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2040
 [27] typeinf_frame(::Core.Inference.InferenceState) at ./inference.jl:2704
 [28] typeinf_loop(::Core.Inference.InferenceState) at ./inference.jl:2603
 [29] typeinf_frame(::Core.MethodInstance, ::Core.Inference.InferenceState, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2473
 [30] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2496
 [31] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1386
 [32] abstract_call(::Any, ::Tuple{}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1864
 [33] abstract_apply(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1516
 [34] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1648
 [35] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1894
 [36] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1917
 [37] typeinf_frame(::Core.Inference.InferenceState) at ./inference.jl:2757
 [38] typeinf_loop(::Core.Inference.InferenceState) at ./inference.jl:2620
 [39] typeinf_frame(::Core.MethodInstance, ::Void, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2473
 [40] typeinf_code(::Core.MethodInstance, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2543
 [41] typeinf_ext(::Core.MethodInstance, ::UInt64) at ./inference.jl:2582
 [42] #warn#515(::Array{Any,1}, ::Function, ::String, ::Vararg{String,N} where N) at ./util.jl:585
 [43] breaks(::Array{TestType,2}, ::Base.#identity) at /home/tim/tmp/im_bug.jl:8
 [44] breaks(::Array{TestType,2}) at /home/tim/tmp/im_bug.jl:4
 [45] include_from_node1(::String) at ./loading.jl:539
 [46] include(::String) at ./sysimg.jl:14
while loading /home/tim/tmp/im_bug.jl, in expression starting on line 15

julia> breaks([TestType() TestType()])
WARNING: this type didn't work
ERROR: MethodError: no method matching mapIM(::TestType)
Closest candidates are:
  mapIM(::Number) at /home/tim/tmp/im_bug.jl:1
Stacktrace:
 [1] _collect(::Array{TestType,2}, ::Base.Generator{Array{TestType,2},##3#4{Base.#identity}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:441
 [2] breaks(::Array{TestType,2}, ::Base.#identity) at /home/tim/tmp/im_bug.jl:6
 [3] breaks(::Array{TestType,2}) at /home/tim/tmp/im_bug.jl:4
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: src/gc.c [hunk 1]
```diff
@@ -108,7 +108,7 @@ static void run_finalizer(jl_ptls_t ptls, jl_value_t *o, jl_value_t *ff)
     JL_TRY {
         size_t last_age = jl_get_ptls_states()->world_age;
         jl_get_ptls_states()->world_age = jl_world_counter;
-        jl_apply(args, 2);
+        jl_apply_with_saved_exception_state(args, 2, 0);
         jl_get_ptls_states()->world_age = last_age;
     }
     JL_CATCH {
```
Comment (yuyichao) [inline src/gc.c]: We should either remove this or keep it working. (Printing a warning if an unexpected error happens in a finalizer is probably still somewhat useful.)

**Review by yuyichao — CHANGES_REQUESTED** [review]

File: src/gc.c (hunk 1 above)
Comment (yuyichao) [inline src/gc.c]: Actually didn't realized that this is what the `0` is for...

Comment (yuyichao) [inline src/gc.c]: Though in that case, does the copying of backtrace actually do anything at all? If an error is thrown it'll just hit this catch and the exception and backtraces will still be overwritten? Seems that the saving should move to the caller of this function, outside the loop.

Comment (JeffBezanson) [inline src/gc.c]: Yes, it still does something, in case a finalizer catches and hides an exception. However you're right that saving the state inside this loop is inefficient. C is just not good for this kind of programming :(

Comment (yuyichao) [inline src/gc.c]: > in case a finalizer catches and hides an exception.

Ah, yeah.

> C is just not good for this kind of programming :(

Agreed. Luckily, there's only one caller so it should be sufficient to add the saving logic to `jl_gc_run_finalizers_in_lilst` after releasing the finalizer lock.

**Comment by JeffBezanson** [comment]
Updated.

**Review by yuyichao — APPROVED** [review]

**Comment by JeffBezanson** [comment]
@vtjnash There's an interesting error on 64-bit linux on travis here where my change to static_eval apparently tries to call something in world 0. Why would this happen only on 64-bit travis/linux? Works locally.

**Comment by vtjnash** [comment]
I'm not sure why only x86-64 exercises this code path, but it is correct in observing that previously this function did not exercise any dynamic dispatch code, and with the change, it now is attempting to do so.

**Comment by JeffBezanson** [comment]
How could the current world get set to 0? Is there any code that does that?

**Comment by vtjnash** [comment]
It's the default world. It can sometimes get triggered when you try to run `_apply` from invalid contexts, like inside codegen. In this case, world=1 would be sufficient however, so it's not too wrong.
