### PR TITLE
fix rounding edge cases on `cld`, `fld`, and `rem`

### LINKED ISSUE #45875: Strange `cld` behaviour
According to the documentation `cld(x,y)` gives the  "Smallest integer larger than or equal to `x/y`. Equivalent to `div(x, y, RoundUp)`."

In practice, I find:
```
julia> cld(1.1, 0.1)
12.0

julia> div(1.1, 0.1, RoundUp)
11.0
```
This is on
```
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc6565 (2022-05-27 18:33 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

### PR DESCRIPTION
**Pull request by t-bltg**
- fix https://github.com/JuliaLang/julia/issues/45875;
- make docstrings more consistent (spacing around operators and after commas).

cc @eschnett for removal of `cld` def introduced in https://github.com/JuliaLang/julia/pull/8111.

Two tests marked broken before are now passing at https://github.com/JuliaLang/julia/blob/f4801ff2b50594568f0bb66a1b4d8ee9181d76bf/test/numbers.jl#L2554
One test had its sign modified (`0.0` -> `-0.0`): `isequal(rem(nextfloat(typemin(T)), T(2), RoundUp), -0.0)`.

### CODE REVIEW

**Review by LilithHafner — APPROVED** [review]
Thanks!

File: base/div.jl [hunk 1]
```diff
@@ -123,31 +123,31 @@ julia> fld.(-5:5, 3)'
...
-julia> 6.0/big(0.1)
+julia> 6.0 / big(0.1)
 59.99999999999999666933092612453056361837965690217069245739573412231113406246995
 ```
 What is happening here is that the true value of the floating-point number written
-as `0.1` is slightly larger than the numerical value 1/10 while `6.0` represents
-the number 6 precisely. Therefore the true value of `6.0 / 0.1` is slightly less
-than 60. When doing division, this is rounded to precisely `60.0`, but
+as `0.1` is slightly larger than the numerical value `1 / 10` while `6.0` represents
+the number `6` precisely. Therefore the true value of `6.0 / 0.1` is slightly less
```
Comment (LilithHafner) [inline base/div.jl:135]: Backticks represent Julia code, but 1/10 and 6 are mathematical concepts here, free from any implementation details.
```suggestion
as `0.1` is slightly larger than the numerical value 1/10 while `6.0` represents
the number 6 precisely. Therefore the true value of `6.0 / 0.1` is slightly less
```

File: base/div.jl [hunk 2]
```diff
@@ -66,8 +66,8 @@ without any intermediate rounding.
   ``(y, 0]`` otherwise. The result may not be exact if `x` and `y` have different signs, and
   `abs(x) < abs(y)`. See also [`RoundDown`](@ref).
 
-- if `r == RoundUp`, then the result is in the interval `(-y,0]` if `y` is positive, or
-  `[0,-y)` otherwise. The result may not be exact if `x` and `y` have the same sign, and
+- if `r == RoundUp`, then the result is in the interval `(-y, 0]` if `y` is positive, or
+  `[0, -y)` otherwise. The result may not be exact if `x` and `y` have the same sign, and
```
Comment (LilithHafner) [inline base/div.jl:70]:
```suggestion
- if `r == RoundUp`, then the result is in the interval ``(-y, 0]`` if `y` is positive, or
  ``[0, -y)`` otherwise. The result may not be exact if `x` and `y` have the same sign, and
```

File: base/div.jl [hunk 3]
```diff
@@ -123,31 +123,31 @@ julia> fld.(-5:5, 3)'
...
+julia> 6.0 / big(0.1)
 59.99999999999999666933092612453056361837965690217069245739573412231113406246995
 ```
 What is happening here is that the true value of the floating-point number written
-as `0.1` is slightly larger than the numerical value 1/10 while `6.0` represents
-the number 6 precisely. Therefore the true value of `6.0 / 0.1` is slightly less
-than 60. When doing division, this is rounded to precisely `60.0`, but
+as `0.1` is slightly larger than the numerical value `1 / 10` while `6.0` represents
+the number `6` precisely. Therefore the true value of `6.0 / 0.1` is slightly less
+than `60`. When doing division, this is rounded to precisely `60.0`, but
```
Comment (LilithHafner) [inline base/div.jl:136]:
```suggestion
than 60. When doing division, this is rounded to precisely `60.0`, but
```
Same as above.

**Review by LilithHafner — COMMENTED** [review]
This feels like two separate PRs, one fixes `cld` and the other is whitespace.

File: base/div.jl (hunk 1 above)
Comment (t-bltg) [reply base/div.jl]: Ha, good point, thanks for the clarification.

**Comment by t-bltg** [comment]
> This feels like two separate PRs, one fixes cld and the other is whitespace.

Thanks, I've rebased the PR so that one commit denotes the actual fix and the others contains whitespace, style & docstring modifications: I don't think splitting this into two PRs is needed.

File: test/numbers.jl [hunk 4]
```diff
@@ -1650,8 +1650,17 @@ end
...
+    @test mod(Int64(2), typemax(Int64)) == 2  # issue #3046
+    @testset "issue #45875" begin
+        @test cld(+1.1, 0.1) == +12.0
+        @test fld(+1.1, 0.1) == +11.0
+        @test cld(-1.1, 0.1) == -11.0
+        @test fld(-1.1, 0.1) == -12.0
+        @test div(+1.1, 0.1, RoundDown) == +11.0
+        @test div(+1.1, 0.1, RoundUp) == +12.0
+        @test div(-1.1, 0.1, RoundDown) == -12.0
+        @test div(-1.1, 0.1, RoundUp) == -11.0
```
[the remark this answers is not in the document]
Comment (t-bltg) [reply test/numbers.jl]: Neat !

**Comment by LilithHafner** [comment]
Pending CI, this looks good to me. Do you think it is ready to merge?

**Comment by t-bltg** [comment]
> Pending CI

I keep re-triggering CI, but unrelated spurious failures keep showing.

> Do you think it is ready to merge?

Yes.

**Comment by LilithHafner** [comment]
The CI failure seems unrelated to me.

Thanks for your contribution! It's nice to see `# FIXME: The broken case erroneously returns -Inf` get removed.
