### PR TITLE
fix/unify eigenvalue promotion

### LINKED ISSUE #491: incorrect promotion of rational types in eigvals etc
As pointed out [on discourse](https://discourse.julialang.org/t/eigenvalues-of-matrices-with-rational-entries/7550), the `eigvals` functions and a number of other linalg functions are incorrectly promoting rationals to `Float32` rather than `Float64`.

They are calling `promote_type(Float32, typeof(one(T)/norm(one(T))))`.  The `Float32` was added by @andreasnoack in JuliaLang/julia#5526 to ensure that `Float16` data was promoted to `Float32`, and the `norm` call was added by @andreasnoack in JuliaLang/julia#5652, at which point he changed `norm(::Rational)` to produce a floating-point result.   However, the `norm(::Rational)` method was subsequently changed back to produce a rational result, at which point this bug was introduced.

A simple fix would be to add a `float` call here (and in other functions that use this promotion scheme).

### LINKED ISSUE #24935: incorrect promotion of rational types in eigvals etc
As pointed out [on discourse](https://discourse.julialang.org/t/eigenvalues-of-matrices-with-rational-entries/7550), the `eigvals` functions and a number of other linalg functions are incorrectly promoting rationals to `Float32` rather than `Float64`.

They are calling `promote_type(Float32, typeof(one(T)/norm(one(T))))`.  The `Float32` was added by @andreasnoack in #5526 to ensure that `Float16` data was promoted to `Float32`, and the `norm` call was added by @andreasnoack in #5652, at which point he changed `norm(::Rational)` to produce a floating-point result.   However, the `norm(::Rational)` method was subsequently changed back to produce a rational result, at which point this bug was introduced.

A simple fix would be to add a `float` call here (and in other functions that use this promotion scheme).

### PR DESCRIPTION
**Pull request by stevengj**
Fixes JuliaLang/LinearAlgebra.jl#491.  Also unifies the promotion code to call a single `LinAlg.eigtype` function rather than copy-and-pasting the same `promote_type` call everywhere.

### CODE REVIEW

**Review by andreasnoack — COMMENTED** [review]
This is a nice cleanup but I still think we should avoid the call to `float`. To be as generic as possible, the promotion should be composed out of the operations in the algorithm. For future fancy types, the meaning of `float` might not be obvious. That is e.g. the case for types for automatic differentiation but there might be other cases as well. I think the most obvious solution is to ensure that `norm(1) === norm([1])`.

File: base/linalg/eigen.jl [hunk 1]
```diff
@@ -199,6 +198,9 @@ function eigvals!(A::StridedMatrix{<:BlasComplex}; permute::Bool=true, scale::Bo
     return LAPACK.geevx!(permute ? (scale ? 'B' : 'P') : (scale ? 'S' : 'N'), 'N', 'N', 'N', A)[2]
 end
 
+# promotion type to use for eigenvalues of a Matrix{T}
+eigtype(T) = (Base.@_pure_meta; promote_type(Float32, typeof(float(zero(T)/norm(one(T))))))
```
Comment (andreasnoack) [inline base/linalg/eigen.jl]: I don't think the `Base.@_pure_meta` part is necessary here. At least it doesn't change anything for `Int` and `Rational{Int}`.

**Comment by stevengj** [comment]
We are promoting with `Float32` (to deal with `Float16` data) already.  I don't understand how that could work, but calling `float` could fail.

Forcing `norm(::Rational)` to return a float, just because `norm(::Vector{<:Rational})` does (must), doesn't seem like a good solution to me.

**Comment by andreasnoack** [comment]
You are right that since we are already explicitly promoting with `Float32`, it probably doesn't make a difference to use `float`. I've haven't been able to come up with an example where it matters so let's just keep the `float`.

However, I don't really get why don't think it makes sense to require the promotion in `norm(Rational)`. You can argue that `abs` is a totally fine norm on `Rational` but we kind of pretend that it is a generic two norm such that it would be an optimized version of `norm(x::Number) = sqrt(abs2(x))` and `sqrt(1//1) isa Float64`. Furthermore, `vecnorm` is supposed to handle all all iterables and for all length one iterables but `Number` (even though it is an iterable), the result would be `Float64`.

File: base/linalg/eigen.jl (hunk 1 above)
Comment (andreasnoack) [reply base/linalg/eigen.jl]: Do you want the annotation to stay? These macro annotations are no particularly pretty so if they don't help, I think it would be better not to have it.

**Comment by stevengj** [comment]
We usually don't convert to floating-point when we don't have to.  `norm(x::Number) = abs(x)` makes sense and is arguably the *right* definition for scalars, and there's no need for this to give a floating-point result (e.g. for `norm(::Integer)`), so it shouldn't give an inexact result needlessly.

I would be totally fine with a `vecnorm(x::Number) = norm(::Number)` method, but I don't think it's worth the trouble.

**Comment by stevengj** [comment]
In any case, since you agree that `float` is okay here, I think the discussion of whether `norm(::Integer)` and `norm(::Rational)` should return floating-point results can be pushed to another issue.

Okay to merge?  (The CI failure `Error in testset linalg/lapack:
Test Failed at /tmp/julia/share/julia/test/linalg/lapack.jl:360
  Expression: triu(inv(A)) ≈ triu(LAPACK.sytri!('U', B, ipiv))` seems unrelated.)

**Comment by andreasnoack** [comment]
The `float` is actually problemetic for `Unums.jl` and maybe other special interval-like number types. You could argue that they should just define their own versions of all the `eigx` methods but I think it would be better just to have
```julia
eigtype(T) = promote_type(Float32, typeof(zero(T)/sqrt(abs2(one(T)))))
```
I think that should do the right thing for all the cases we are considering here.

**Comment by stevengj** [comment]
Okay, changed to use `sqrt`

**Review by fredrikekre — APPROVED** [review]
