### PR TITLE
pinv now works for hermitian matrices.

### LINKED ISSUE #40911: `pinv` fails for `Hermitian` matrices
In julia v1.6.1
```julia
julia> Q = randn(2,2); Q = Q'Q; pinv(Hermitian(Q))
ERROR: MethodError: no method matching svd(::Hermitian{Float64, Matrix{Float64}}; full=false)
Closest candidates are:
  svd(::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:843 got unsupported keyword argument "full"
  svd(::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:843 got unsupported keyword argument "full"
  svd(::StridedMatrix{T}, ::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/svd.jl:370 got unsupported keyword argument "full"
  ...
Stacktrace:
 [1] pinv(A::Hermitian{Float64, Matrix{Float64}}; atol::Float64, rtol::Float64)
   @ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:1388
 [2] pinv(A::Hermitian{Float64, Matrix{Float64}})
   @ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:1367
 [3] top-level scope
   @ REPL[219]:1

julia> Q = randn(2,2); Q = Q'Q; svd(Hermitian(Q))
SVD{Float64, Float64, Matrix{Float64}}
U factor:
2×2 Matrix{Float64}:
 -0.516423  -0.856334
  0.856334  -0.516423
singular values:
2-element Vector{Float64}:
 6.56785
 3.81471
Vt factor:
2×2 Matrix{Float64}:
 -0.516423   0.856334
 -0.856334  -0.516423
```

### PR DESCRIPTION
**Pull request by ArunS-tack**
Fixes #40911. 

**Before**

```
julia> Q = randn(2,2); Q = Q'Q; pinv(Hermitian(Q))
ERROR: MethodError: no method matching svd(::Hermitian{Float64, Matrix{Float64}}; full=false)
Closest candidates are:
  svd(::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:843 got unsupported keyword argument "full"
  svd(::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:843 got unsupported keyword argument "full"
  svd(::StridedMatrix{T}, ::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/svd.jl:370 got unsupported keyword argument "full"
  ...
Stacktrace:
 [1] pinv(A::Hermitian{Float64, Matrix{Float64}}; atol::Float64, rtol::Float64)
   @ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:1388
 [2] pinv(A::Hermitian{Float64, Matrix{Float64}})
   @ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:1367
 [3] top-level scope
   @ REPL[219]:1
```
```
julia> A = randn(3,3); svd(Hermitian(A),full=true)
MethodError: no method matching svd(::Hermitian{Float64, Matrix{Float64}}; full=true)
Closest candidates are:
  svd(::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:843 got unsupported keyword argument "full"
  svd(::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}, !Matched::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:843 got unsupported keyword argument "full"
  svd(!Matched::StridedMatrix{T}, !Matched::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/svd.jl:370 got unsupported keyword argument "full"
  ...
top-level scope at untitled-caf8cf46142215c9cc05f796bc9cc619:3
eval at boot.jl:360 [inlined]
```

**After**

```
julia> Q = randn(2,2); Q = Q'Q; pinv(Hermitian(Q))
2×2 Matrix{Float64}:
 39.4657    -0.425089
 -0.425089   0.76294
```
```
julia> A = randn(3,3); svd(Hermitian(A),full=true)
SVD{Float64, Float64, Matrix{Float64}}
U factor:
3×3 Matrix{Float64}:
  0.617115   0.184267  0.764994
 -0.399113  -0.764557  0.506124
 -0.678143   0.617655  0.398276
singular values:
3-element Vector{Float64}:
 3.01828539776972
 2.24865206964243
 0.5683700735641573
Vt factor:
3×3 Matrix{Float64}:
  0.617115  -0.399113  -0.678143
 -0.184267   0.764557  -0.617655
 -0.764994  -0.506124  -0.398276
```

### CODE REVIEW

**Comment by andreasnoack** [comment]
Thanks for fixing this. It would be great if you could add a test of `svd(::Hermitian; full=true)`.

**Comment by ArunSanganal** [comment]
> Thanks for fixing this. It would be great if you could add a test of `svd(::Hermitian; full=true)`.

Done.

**Comment by dkarrasch** [comment]
> Thanks for fixing this. It would be great if you could add a test of `svd(::Hermitian; full=true)`.

@ArunSanganal This was referring to adding a test to the CI test suite, not to the original github post. Besides the `src` folder, there is also a `test` folder in `stdlib/LinearAlgebra`. This will make sure that the feature is working/bug is fixed and continue to do so under future development.

**Comment by ArunSanganal** [comment]
Oh, my bad. I ll get on to it right away.

**Comment by ArunSanganal** [comment]
> > Thanks for fixing this. It would be great if you could add a test of `svd(::Hermitian; full=true)`.
> 
> @ArunSanganal This was referring to adding a test to the CI test suite, not to the original github post. Besides the `src` folder, there is also a `test` folder in `stdlib/LinearAlgebra`. This will make sure that the feature is working/bug is fixed and continue to do so under future development.

I am confused with how to add a test case for svd as it gives 3 outputs (U factor, singular values and vt factor), like if I copy-paste the output in the test file, I am quite sure it would not recognize it when carrying out the test.

**Comment by dkarrasch** [comment]
You can check how the other SVD tests are written. Like you could first evaluate `F = svd(Hermitian(A); full=true)` and then check things like `@test F.U'F.U ≈ I` etc. If the call itself fails (as it does currently), the CI tests would notice. You could also choose a very specific `A`, say, `Matrix(1.0I, 3, 3)`, and then only check that `@test F.S ≈ ones(3)`.

File: stdlib/LinearAlgebra/test/svd.jl [hunk 1]
```diff
@@ -23,6 +23,11 @@ using LinearAlgebra: BlasComplex, BlasFloat, BlasReal, QRPivoted
     @test F.U'F.U ≊ Matrix(I, 2, 2)
     @test F.Vt'*F.Vt ≊ [1]
     @test @inferred(svdvals(3:4)) ≊ [5]
+
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/svd.jl:26]: whitespace...
```suggestion

```

**Review by dkarrasch — COMMENTED** [review]
Nice. And another test for the `pinv` issue, then this is good to go.

File: stdlib/LinearAlgebra/test/pinv.jl [hunk 2]
```diff
@@ -157,7 +157,13 @@ end
...
         @test a.diag[2] ≈ 0.0
     end
-
+    
+    @testset "hermitian matrices" begin
+        Q=ones(2,2)
+        C=pinv(Hermitian(Q))/0.25
+        @test C≈ones(2,2)
+    end
+
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/pinv.jl:166]:
```suggestion

    @testset "hermitian matrices" begin
        Q = ones(2,2)
        C = pinv(Hermitian(Q))/0.25
        @test C ≈ ones(2,2)
    end

```
