### PR TITLE
more friendly/useful error for stack overflow in type inference

### LINKED ISSUE #44852: StackOverflow Type Inference Error
We ran into an issue where Julia type inference breaks down and results in a stack overflow(SO) while working on an application for a client. The issue is present in both Julia 1.6.5 and Julia 1.7.2. On MacOS the SO terminates quickly, but on Ubuntu instances it propagates a stack trace for > 24hours (>600MB).

We cannot share the example but we have made an RR available (hopefully it was collected correctly). 
Private Link:
https://github.com/RelationalAI/raicode/issues/7471

Possibly related issues: 
https://github.com/JuliaLang/julia/issues/43050
https://github.com/JuliaLang/julia/issues/38364

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #44852

### CODE REVIEW

**Comment by JeffBezanson** [comment]
With #44970:
```
julia> foldr(+, Tuple(1:5000))
Internal error: stack overflow in type inference of foldr(Function, NTuple{5000, Int64})
This might be caused by recursion over very long tuples or argument lists.
12502500

julia> 
```

File: src/gf.c [hunk 1]
```diff
@@ -317,10 +317,19 @@ jl_code_info_t *jl_type_infer(jl_method_instance_t *mi, size_t world, int force)
...
-        jl_printf((JL_STREAM*)STDERR_FILENO, "Internal error: encountered unexpected error in runtime:\n");
-        jl_static_show((JL_STREAM*)STDERR_FILENO, jl_current_exception());
-        jl_printf((JL_STREAM*)STDERR_FILENO, "\n");
-        jlbacktrace(); // written to STDERR_FILENO
+        jl_value_t *e = jl_current_exception();
+        if (e == jl_stackovf_exception) {
+            jl_printf((JL_STREAM*)STDERR_FILENO, "Internal error: stack overflow in type inference of ");
+            jl_static_show_func_sig(JL_STDERR, (jl_value_t*)mi->specTypes);
+            jl_printf(JL_STDERR, ".\n");
+            jl_printf((JL_STREAM*)STDERR_FILENO, "This might be caused by recursion over very long tuples or argument lists.\n");
```
Comment (vtjnash) [inline src/gf.c:325]: `JL_STDERR` is an object, not a file, and it is not interchangable with `STDERR_FILENO` (they get flushed at slightly different times)

**Review by aviatesk — APPROVED** [review]

**Comment by NHDaly** [comment]
awesome, thanks! :)
