### PR TITLE
fix error show edge case

### LINKED ISSUE #44289: Error determining location should not throw in showing method candidates
The error printing for method errors tries to print method locations and gives a very gnarly error if it can't. This should be fixed to fail gracefully.
``` 
Error: Error showing method candidates, aborted
│   exception =
│    could not determine location of method definition
│    Stacktrace:
│      [1] error(s::String)
│        @ Base ./error.jl:35
│      [2] functionloc
│        @ ./methodshow.jl:164 [inlined]
│      [3] show_method_candidates(io::IOContext{Base.TTY}, ex::MethodError, kwargs::Any)
│        @ Base ./errorshow.jl:510
│      [4] showerror(io::IOContext{Base.TTY}, ex::MethodError)
│        @ Base ./errorshow.jl:327
│      [5] showerror(io::IOContext{Base.TTY}, ex::MethodError, bt::Vector{Base.StackTraces.StackFrame}; backtrace::Bool)
│        @ Base ./errorshow.jl:88
│      [6] show_exception_stack(io::IOContext{Base.TTY}, stack::Base.ExceptionStack)
│        @ Base ./errorshow.jl:877

```

### PR DESCRIPTION
**Pull request by oscardssmith**
fixes https://github.com/JuliaLang/julia/issues/44289

### CODE REVIEW

**Comment by oscardssmith** [comment]
Can we merge this without tests? I have a reliable reproducer
```
julia> eval(Expr(:function, :(f()), 1))
f (generic function with 1 method)

julia> f(1)
ERROR: MethodError: no method matching f(::Int64)┌ Error: Error showing method candidates, aborted
│   exception =
│    could not determine location of method definition
│    Stacktrace:
```
but the error occurs in error printing which is annoying to test.

**Comment by KristofferC** [comment]
Hm, why is it annoying to test? I think there is a bunch of tests of error printing.

**Comment by oscardssmith** [comment]
TIL about `showerror`. Thanks! I believe this is now ready to merge.

File: test/error.jl [hunk 1]
```diff
@@ -86,3 +86,13 @@ end
...
     @test e.extrainfo === nothing
 end
+
+@testset "MethodError for methods without line numbers" begin
+    try
+        eval(Expr(:function, :(f()),0))
+        f(1)
+    catch e
+        s =  sprint(showerror, e)
+        @test s == "MethodError: no method matching f(::Int64)\nClosest candidates are:\n  f() at none:0"
```
Comment (simeonschaub) [inline test/error.jl:96]:
```suggestion
        eval(Expr(:function, :(f44319()), 0))
        f44319(1)
    catch e
        s = sprint(showerror, e)
        @test s == "MethodError: no method matching f44319(::Int64)\nClosest candidates are:\n  f44319() at none:0"
```
otherwise there might be tons of warnings if methods of `f` are redefined
