### PR TITLE
Fix GC.gc docstring

### LINKED ISSUE #51796: Possibly confusing documentation for GC.gc()
As written in `base/gcutils.jl`:

```
"""
    GC.gc([full=true])

Perform garbage collection. The argument `full` determines the kind of
collection: A full collection (default) sweeps all objects, which makes the
next GC scan much slower, while an incremental collection may only sweep
so-called young objects.

!!! warning
    Excessive use will likely lead to poor performance.
"""
```

Note, however that passing `JL_GC_FULL` to `jl_gc_collect` [will trigger a recollection if the last sweep was not full](https://github.com/JuliaLang/julia/blob/01f6c4c8b86f62af923a600327f9b6be1a905193/src/gc.c#L3346).

In any case, this is a strong indication that `GC.gc(true)` will trigger a full mark, and if so, the docs might need to be adjusted for clarity.

### PR DESCRIPTION
**Pull request by d-netto**
GC.gc(true) will perform a full mark (note the use of [recollect in gc.c ](https://github.com/JuliaLang/julia/blob/5eaad532f961d4d1a1630b5c5b60499d2a7b9ae5/src/gc.c#L3338)if the previous sweep was not full).

Fixes https://github.com/JuliaLang/julia/issues/51796.

### CODE REVIEW

File: base/gcutils.jl [hunk 1]
```diff
@@ -119,9 +119,9 @@ const GC_INCREMENTAL = 2
     GC.gc([full=true])
 
 Perform garbage collection. The argument `full` determines the kind of
-collection: A full collection (default) sweeps all objects, which makes the
-next GC scan much slower, while an incremental collection may only sweep
-so-called young objects.
+collection: a full collection (default) traverses all live objects (e.g. full mark)
```
Comment (KristofferC) [inline base/gcutils.jl:122]:
```suggestion
collection: a full collection (default) traverses all live objects (i.e. full mark)
```

or? I don't really understand the "e.g." usage here.

File: base/gcutils.jl [hunk 2]
```diff
@@ -119,9 +119,9 @@ const GC_INCREMENTAL = 2
     GC.gc([full=true])
 
 Perform garbage collection. The argument `full` determines the kind of
-collection: A full collection (default) sweeps all objects, which makes the
-next GC scan much slower, while an incremental collection may only sweep
-so-called young objects.
+collection: a full collection (default) traverses all live objects (i.e. full mark)
+and should reclaim memory from all unreachable objects. An incremental collection only
+reclaims memory from young objects which are not reachable.
```
Comment (kpamnany) [inline base/gcutils.jl:125]:
```suggestion

The GC may decide to perform a full collection even if an incremental collection was requested.

```

Comment (kpamnany) [reply base/gcutils.jl:125]: Actually, not sure if this is true?

Comment (d-netto) [reply base/gcutils.jl:125]: This is true. If the last sweep happened, by chance, to be full, then we'll do a full mark.

**Review by NHDaly — APPROVED** [review]
Cool, thanks!
