### PR TITLE
MPFR tests: skip the `log2(x) == log2(42)` test

### LINKED ISSUE #41417: Error in testset mpfr
From https://build.julialang.org/#/builders/65/builds/674/steps/5/logs/stdio

```
Error in testset mpfr:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\mpfr.jl:609
  Expression: log2(x) == log2(42)
   Evaluated: 5.3923174227787607 == 5.39231742277876
```

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #41417 

See also: #41450

### CODE REVIEW

File: test/mpfr.jl [hunk 1]
```diff
@@ -606,7 +606,11 @@ end
         @test log(x) == log(42)
         @test isinf(log(BigFloat(0)))
         @test_throws DomainError log(BigFloat(-1))
-        @test log2(x) == log2(42)
+        if Sys.iswindows()
+            @test_broken log2(x) == log2(42)
+        else
+            @test log2(x) == log2(42)
+        end
```
Comment (simeonschaub) [inline test/mpfr.jl:613]: Since I don't think this is necessarily related to the OS, I think it would be better to not make any assumptions about whether this will pass/fail:
```suggestion
        # issue #41450
        @test_skip log2(x) == log2(42)
```

**Review by simeonschaub — APPROVED** [review]
