### PR TITLE
recompute sparams during inference after widening a method signature

### LINKED ISSUE #18399: Segfault in hvcat
This is a slight modification of @maleadt's example in https://github.com/JuliaLang/julia/pull/18398 but this version doesn't call the method that the PR modifies. It is a regression from 0.4.

```jl
immutable TSlow{T,N} <: AbstractArray{T,N}
    data::Dict{NTuple{N,Int}, T}
    dims::NTuple{N,Int}
end
TSlow{T,N}(::Type{T}, dims::NTuple{N,Int}) = TSlow{T,N}(Dict{NTuple{N,Int}, T}(), dims)

Base.convert{T,N  }(::Type{TSlow     }, X::AbstractArray{T,N}) = convert(TSlow{T,N}, X)
Base.convert{T,N  }(::Type{TSlow{T,N}}, X::AbstractArray     ) = TSlow(T, size(X))

Base.size(A::TSlow) = A.dims
Base.linearindexing{A<:TSlow}(::Type{A}) = Base.LinearSlow()
Base.getindex{T}(A::TSlow{T,3}, i1::Int, i2::Int, i3::Int) = zero(T)
Base.setindex!{T}(A::TSlow{T,3}, v, i1::Int, i2::Int, i3::Int) = return nothing

function test_cat()
    B = TSlow(reshape([1:27...], 3, 3, 3))
    C = TSlow([1 2; 3 4])

    Base.typed_hcat(Float64, B)
    Base.typed_hcat(Float64, B, B, B)
    try
        hvcat((2), C, C)
    end
    hvcat((2,2), 'a', 5, 2//3, 1)
end

test_cat()
```
gives
```
signal (11): Segmentation fault: 11
while loading /Users/andreasnoack/Desktop/hvcatbug.jl, in expression starting on line 27
collect at ./array.jl:304
getindex at ./tuple.jl:10
unknown function (ip: 0x313c086e6)
jl_call_method_internal at /Users/andreasnoack/julia/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/andreasnoack/julia/src/gf.c:1930
hvcat at ./abstractarray.jl:1358
test_cat at /Users/andreasnoack/Desktop/hvcatbug.jl:24
unknown function (ip: 0x313c016ff)
jl_call_method_internal at /Users/andreasnoack/julia/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/andreasnoack/julia/src/gf.c:1930
do_call at /Users/andreasnoack/julia/src/interpreter.c:66
eval at /Users/andreasnoack/julia/src/interpreter.c:190
jl_toplevel_eval_flex at /Users/andreasnoack/julia/src/toplevel.c:558
jl_parse_eval_all at /Users/andreasnoack/julia/src/ast.c:717
jl_load at /Users/andreasnoack/julia/src/toplevel.c:596 [inlined]
jl_load_ at /Users/andreasnoack/julia/src/toplevel.c:605
include_from_node1 at ./loading.jl:426
jlcall_include_from_node1_20195 at /Users/andreasnoack/julia/usr/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/andreasnoack/julia/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/andreasnoack/julia/src/gf.c:1930
process_options at ./client.jl:262
_start at ./client.jl:318
jlcall__start_21540 at /Users/andreasnoack/julia/usr/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/andreasnoack/julia/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/andreasnoack/julia/src/gf.c:1930
true_main at /Users/andreasnoack/bin/julia (unknown line)
main at /Users/andreasnoack/bin/julia (unknown line)
Allocations: 2009974 (Pool: 2009090; Big: 884); GC: 1
[1]    36411 segmentation fault  julia ~/Desktop/hvcatbug.jl
```

### PR DESCRIPTION
**Pull request by vtjnash**
also avoid an expensive loop in the common case of the hotpath

fix #18399

### CODE REVIEW

File: src/cgutils.cpp [hunk 1]
```diff
@@ -1089,6 +1089,9 @@ static jl_cgval_t emit_getfield_knownidx(const jl_cgval_t &strct, unsigned idx,
         fieldval.gcroot = strct.gcroot;
         return fieldval;
     }
+    else if (isa<UndefValue>(strct.V)) {
+        return jl_cgval_t();
```
Comment (yuyichao) [inline src/cgutils.cpp]: :+1: We might need to do this more consistently in other places too though.

File: test/inference.jl [hunk 2]
```diff
@@ -336,3 +336,30 @@ f18222(x) = true
...
+    g = Base.Generator(cb, 1)
+    return g.f(1)
+end
+function cat_t18399(X...)
+    for i = 2:1
+        X[i]
+        d->i
+    end
+end
+C = TSlow18399{Int}(1)
```
Comment (yuyichao) [inline test/inference.jl]: `C`, and `GB` should probably be renamed. (Or just put the whole thing in a module might be better given how many top level names there are).

File: src/cgutils.cpp (hunk 1 above)
Comment (vtjnash) [inline src/cgutils.cpp]: or more callers need to look at `strct.typ` instead of `exprtype` (since exprtype can be wrong / meaningless in dead code)
