### PR TITLE
fix #15489, don't check conversions during mixed signedness arithmetic

### LINKED ISSUE #15489: Interaction of addition and checked conversion
Consider for example:

```
julia> 0x00007ffea27edaa0+(-40)
ERROR: InexactError()
in +(::UInt64, ::Int64) at ./promotion.jl:172
in eval(::Module, ::Any) at ./boot.jl:267

julia> 0x00007ffea27edaa0-40
0x00007ffea27eda78
```

It is understandable why this happens, but the behavior is annoying. At least for integers of the same size, this addition is unambiguous.

### PR DESCRIPTION
**Pull request by JeffBezanson**
also skip checks for integer bitwise ops

### CODE REVIEW

File: base/int.jl [hunk 1]
```diff
@@ -770,3 +770,23 @@ else
...
+for op in (:+, :-, :*)
+    @eval function $op(a::Unsigned, b::Signed)
+        T = promote_typeof(a, b)
+        return $op(a % T, b % T)
+    end
+    @eval function $op(a::Signed, b::Unsigned)
+        T = promote_typeof(a, b)
+        return $op(a % T, b % T)
+    end
+end
```
Comment (StefanKarpinski) [inline base/int.jl]: Wouldn't these definitions work for `Integer` as well? Would collapse all of these definitions.

**Comment by StefanKarpinski** [comment]
The basic observation here is that `(a + b) % n == (a % n) + (b % n) % n` for any `a`, `b`, `n`, so whatever the modulus of the target integer type, we can mod the original arguments into that, then do overflowing integer operations in that modulus and get the same result as if we'd done the operations in arbitrary precision and then reduced to the modulus of the target type. None of that depends on the signedness of the arguments, so we can do this completely universally for all kinds of integers – as long as they implement some kind of modular arithmetic.

**Comment by JeffBezanson** [comment]
That's right. But I was worried about integer types that might implement `convert` and `promote_rule`, but not `%`. Maybe we should add a fallback `%` that calls `convert`?

**Comment by StefanKarpinski** [comment]
The argument works for `-` and `*` for all `n` and for bitwise ops when `n` is a power of 2.

**Comment by StefanKarpinski** [comment]
Beautiful! 👏

**Comment by JeffBezanson** [comment]
Failure on 64-bit AV might be a variation of #23371?

**Comment by StefanKarpinski** [comment]
I don't think these failures are related, but I really wish we could get a clean CI run here.

**Comment by StefanKarpinski** [comment]
Ah, this feels very nice. I'm very pleased with how this turned out.
