### PR TITLE
fix keyword values being shown in `MethodError`

### LINKED ISSUE #45219: Avoid printing values of keyword arguments while displaying a MethodError
Related to [this discourse thread](https://discourse.julialang.org/t/why-are-kwargs-printed-in-full-in-a-methoderror/80592)

MWE:

```julia
julia> f(a::Int; b = nothing) = a
f (generic function with 1 method)

julia> f(2.0, b = zeros(10))
ERROR: MethodError: no method matching f(::Float64; b=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
Closest candidates are:
  f(::Int64; b) at REPL[1]:1
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

The value of the keyword argument has nothing to do with the error, and only adds visual clutter. In some cases, displaying the keyword arguments might take up considerable screen space and be time-consuming.

In case there is a mismatch in the type of the keyword argument, the error thrown is a `TypeError`, which doesn't show the value of the argument. Arguably, this is the case that might benefit from the values being displayed.

```julia
julia> h(a::Int; b::Float64 = 0.0) = a
h (generic function with 1 method)

julia> h(2, b = 4)
ERROR: TypeError: in keyword argument b, expected Float64, got a value of type Int64
Stacktrace:
 [1] top-level scope
   @ REPL[9]:1
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/45219

### CODE REVIEW

File: base/errorshow.jl [hunk 1]
```diff
@@ -272,8 +272,7 @@ function showerror(io::IO, ex::MethodError)
         if !isempty(kwargs)
             print(io, "; ")
             for (i, (k, v)) in enumerate(kwargs)
-                print(io, k, "=")
-                show(IOContext(io, :limit => true), v)
+                print(io, k, "::", typeof(v))
```
Comment (vtjnash) [inline base/errorshow.jl:275]: Should this be 'showarg'?

Comment (KristofferC) [reply base/errorshow.jl:275]: So `f(::Float64; v=view(::Matrix{Float64}, :, :) with eltype Float64)`. That doesn't look right?
