### PR TITLE
Subtype: Fix some diagonal rule related false alarm

### LINKED ISSUE #33137: Subtyping bug: equivalent types behave differently when matching with diagonal variables
In Julia 1.2.0,
```julia
julia> (Tuple{Q,Int} where Q<:Int) <: Tuple{T,T} where T
false

julia> (Tuple{Int,Int}) <: Tuple{T,T} where T
true
```
I think the first check should return `true` because the types on the left-hand side are equivalent:
```julia
julia> (Tuple{Q,Int} where Q<:Int) <: Tuple{Int,Int}
true

julia> Tuple{Int,Int} <: Tuple{Q,Int} where Q<:Int
true
```

Version info:
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### LINKED ISSUE #53021: automatically generated counterexamples for `<:` transitivity
Here's a Git repository containing a Julia package that generates counterexamples to the transitivity property that `<:` is supposed to satisfy:

https://gitlab.com/nsajko/SubtypingRelationExperiments.jl

So far I tested it on v1.10 and v1.11-DEV: the results between these two versions are the same and may be found under `results/`. I'll give just two of the counterexamples here, see the rest on my repo:

This is the first counterexample in the results:

```
counterexample triplet:  (Tuple{X, X} where X<:Union{}, Tuple{C, C}, Tuple{X, X, Vararg{Any}} where C<:X<:C)
```

In the REPL:

```julia-repl
julia> struct C end

julia> const T1 = Tuple{X, X} where X<:Union{}
Tuple{X, X} where X<:Union{}

julia> const T2 = Tuple{C, C}
Tuple{C, C}

julia> const T3 = Tuple{X, X, Vararg{Any}} where C<:X<:C
Tuple{X, X, Vararg{Any}} where C<:X<:C

julia> T1 <: T2 <: T3
true

julia> T1 <: T3
false
```

This is the last counterexample in the results:

```
counterexample triplet:  (Tuple{A, X, Vararg{X}} where X<:C, Tuple{Any, Vararg{C}}, Tuple{Any, Vararg{X}} where X>:C)
```

In the REPL:

```julia-repl
julia> abstract type A end

julia> struct C <: A end

julia> const T1 = Tuple{A, X, Vararg{X}} where X<:C
Tuple{A, X, Vararg{X}} where X<:C

julia> const T2 = Tuple{Any, Vararg{C}}
Tuple{Any, Vararg{C}}

julia> const T3 = Tuple{Any, Vararg{X}} where X>:C
Tuple{Any, Vararg{X}} where X>:C

julia> T1 <: T2 <: T3
true

julia> T1 <: T3
false
```

### PR DESCRIPTION
**Pull request by N5N3**
close #33137
close #53021

### CODE REVIEW

**Comment by nsajko** [comment]
This decreases the number of intransitive triplets found in the experiment from 6035 to 5123. Here's a sample of those which are not fixed with this PR:

```julia
(Tuple{Any, X} where X<:A, Tuple{X, X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{Any}} where X>:Any, Tuple{X, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{A}} where X<:Union{}, Tuple{X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{X}} where X<:A, Tuple{X, Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, C, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{Any}} where A<:X<:A, Tuple{Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, Any, Vararg{A}}, Tuple{X, Any, Vararg{A}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{A}} where A<:X<:A, Tuple{X, A, Vararg{A}} where X>:Any, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{A}} where X, Tuple{X, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, Any, Vararg{A}}, Tuple{X, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X} where X<:Union{}, Tuple{X, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X, Vararg{Any}} where A<:X<:A, Tuple{X, Any, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X} where C<:X<:A, Tuple{X, Any, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A)
(Tuple{A, A, Vararg{X}} where X<:A, Tuple{X, Any, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X} where X<:C, Tuple{X, Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{A}} where X>:Any, Tuple{Any, Vararg{Any}}, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X} where C<:X<:A, Tuple{X, Any} where X>:Any, Tuple{Vararg{X}} where X>:A)
(Tuple{A, A, Vararg{X}} where X, Tuple{X, Any, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{X}} where X<:Union{}, Tuple{X, Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, A, Vararg{X}} where X<:C, Tuple{X, Any, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, A, Vararg{A}}, Tuple{X, A, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A)
(Tuple{A, A, Vararg{X}} where X<:A, Tuple{X, X, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, Any, Vararg{A}}, Tuple{X, Any, Vararg{A}} where X>:Any, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X, Vararg{C}} where C<:X<:C, Tuple{X, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, A, Vararg{X}} where X<:A, Tuple{X, A, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, Any, Vararg{C}}, Tuple, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X} where A<:X<:A, Tuple{X, X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, X, Vararg{X}} where C<:X<:A, Tuple{X, Any, Vararg{A}} where A<:X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X, Vararg{X}} where X<:C, Tuple{X, X, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X} where X>:Any, Tuple{X, Any} where X>:A, Tuple{Vararg{X}} where X>:A)
(Tuple{A, A, Vararg{X}} where X>:A, Tuple{X, Any, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A)
(Tuple{Any, X} where X>:C, Tuple{X, Any, Vararg{A}} where X>:C, Tuple{Vararg{X}} where X>:A)
```

**Comment by N5N3** [comment]
Not surprising to me though. The remaining might no be caused by diagonal check.
I guess an assertation build is helpful here to figure out if some of these failure comes from `obvious_subtype` optimization.

**Comment by vtjnash** [comment]
current CI failure is related, though seems like a test issue
```
Error in testset core:
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XG3Q6T6R70.0/build/default-honeycrisp-XG3Q6T6R70-0/julialang/julia-master/julia-afee770a4f/share/julia/test/core.jl:243
  Expression: f20511(Union{Integer, T} where T <: Unsigned) == 1
   Evaluated: 0 == 1
```

File: src/jltypes.c [hunk 1]
```diff
@@ -556,6 +556,33 @@ static void isort_union(jl_value_t **a, size_t len) JL_NOTSAFEPOINT
...
+    if (hasfree == 0) {
+        // issue #24521: don't merge Type{T} where typeof(T) varies
+        return !(jl_is_type_type(a) && jl_is_type_type(b) &&
+             jl_typeof(jl_tparam0(a)) != jl_typeof(jl_tparam0(b))) &&
+             jl_subtype(a, b);
+    }
+    if (jl_is_typevar(a)) {
+        jl_value_t *na = ((jl_tvar_t*)a)->ub;
+        hasfree &= jl_has_free_typevars(na);
+        return simple_subtype(na, b, hasfree);
```
Comment (vtjnash) [inline src/jltypes.c:574]: In `Tuple{Union{Integer,T}, T} where T`, would this cause the result to become `Tuple{T, T} where T`, instead of the correct result with a switched Union:

```
julia> (Union{Tuple{Integer,T}, Tuple{T, T}} where T) == (Tuple{Union{Integer,T}, T} where T)
true
```

**Comment by nsajko** [comment]
This PR introduces some new counterexamples to the expected transitivity of `<:`.

Julia script `/tmp/pr_regressions.jl`:

```julia
abstract type A end
struct C <: A end

triplets = [
  (Tuple{A, X, Vararg{X}} where X<:C, Tuple{A, Vararg{X}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:C, Tuple{A, Vararg{X}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:C, Tuple{Any, Vararg{X}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:C, Tuple{Any, Vararg{X}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:Union{}, Tuple{A, Vararg{X}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:Union{}, Tuple{A, Vararg{X}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:Union{}, Tuple{Any, Vararg{X}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, X, Vararg{X}} where X<:Union{}, Tuple{Any, Vararg{X}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{Any, X, Vararg{X}} where X<:C, Tuple{Any, Vararg{X}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{Any, X, Vararg{X}} where X<:C, Tuple{Any, Vararg{X}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{Any, X, Vararg{X}} where X<:Union{}, Tuple{Any, Vararg{X}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{Any, X, Vararg{X}} where X<:Union{}, Tuple{Any, Vararg{X}} where X>:C, Tuple{Vararg{X}} where X>:A),
]

f(t) = t[1] <: t[2] <: t[3]
g(t) = t[1] <: t[3]

println(f.(triplets))
println(g.(triplets))
```

Results:

```
$ ./julia-nightly/bin/julia /tmp/pr_regressions.jl 
Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
$ ./julia-pr_53034/bin/julia /tmp/pr_regressions.jl 
Bool[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by aviatesk** [comment]
Will this allow #48205 to be merged safely, or at least fix the first part of Jameson's concerns (xref: https://github.com/JuliaLang/julia/pull/48205#issuecomment-1377333830)?

**Comment by N5N3** [comment]
> Will this allow #48205 to be merged safely, or at least fix the first part of Jameson's concerns (xref: [#48205 (comment)](https://github.com/JuliaLang/julia/pull/48205#issuecomment-1377333830))?

We do more normalization after replacing `simple_join` with `simple_union`.
But the concern on `datatype_name_cmp` still holds, perhaps https://github.com/JuliaLang/julia/pull/48205 needs some type complexity check?

File: src/jltypes.c (hunk 1 above)
Comment (N5N3) [reply src/jltypes.c]: Well it turns out this branch might affect method definition.
On master
```julia
julia> f(x::Union{AbstractArray,T}) where {T<:Vector} = T
f (generic function with 1 method)

julia> f([1])
ERROR: UndefVarError: `T` not defined
Stacktrace:
 [1] f(x::Vector{Int64})
   @ Main .\REPL[3]:1
 [2] top-level scope
   @ REPL[4]:1
```
This PR
```julia
julia> f(x::Union{AbstractArray,T}) where {T<:Vector} = T
WARNING: method definition for f at REPL[1]:1 declares type variable T but does not use it.
f (generic function with 1 method)

julia> f([1])
ERROR: UndefVarError: `T` not defined in static parameter matching
Suggestion: run Test.detect_unbound_args to detect method arguments that do not fully constrain a type parameter.
Stacktrace:
 [1] f(x::Vector{Int64})
   @ Main .\REPL[1]:1
 [2] top-level scope
   @ REPL[2]:1
```
Not sure if this is a regression.

**Comment by N5N3** [comment]
@nsajko These new counterexamples seems fine.
They didn't appear on master just because the bad normalization breaks `t[1] <: t[2]`.
And `t[1] <: t[3]` is still broken.

File: src/jltypes.c (hunk 1 above)
Comment (nsajko) [reply src/jltypes.c]: > Not sure if this is a regression.

IMO this is an improvement, not a regression, because it's better to throw than be ambiguous.

Comment (nsajko) [reply src/jltypes.c]: I.e., you may have fixed a correctness bug?

**Comment by N5N3** [comment]
@nsajko local test shows that f8c20cc fixes all of the remaining counterexamples.

**Comment by nsajko** [comment]
Nice! However I still get 3815 counterexamples (with the version of the experiment code as available on Gitlab): [counterexamples.jl.txt](https://github.com/JuliaLang/julia/files/14054293/counterexamples.jl.txt)

Inline sample, with just the initial few counterexamples:

```julia
abstract type A end
struct C <: A end

triplets = [
  (Tuple{A, A, Any, Vararg{Any}}, Tuple, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, A, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, A, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, Any, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{A, X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, A, Any, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, A, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, A, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, Any, Any, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, Any, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, Vararg{Any}}, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{Any, X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, A, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Any, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where C<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where X, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{Any}} where X>:C, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, X, Vararg{Any}} where A<:X<:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, X, Vararg{Any}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, X, Vararg{Any}} where X>:Any, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{Any}}, Tuple{X, X, Vararg{X}} where X>:A, Tuple{Vararg{X}} where X>:A),
  (Tuple{A, A, Any, Vararg{A}}, Tuple, Tuple{Vararg{X}} where X>:A),
]

f(t) = t[1] <: t[2] <: t[3]
g(t) = t[1] <: t[3]

function d(v)
  allequal(v) || error("not all elements are equal")
  first(v)
end

println(d(f.(triplets)))
println(d(g.(triplets)))

File: src/jltypes.c (hunk 1 above)
Comment (vtjnash) [reply src/jltypes.c]: @N5N3 That is an interesting observation. It is sort of awkward that whether we catch that issue at definition or runtime depends somewhat on what normalizations are implemented for Union. I think I am okay with that change however. It seems fairly unlikely packages would have written that, and the solution is quite simple (just don't write that TypeVar in that place to fix the warning). In particular, it was already doing a similar normalization in several cases, so it is at least not an unexpected new behavior:

```
(on master)

julia> Union{Integer,T} where T<:Integer
Union{Integer, T} where T<:Integer

julia> Union{Any,T} where T<:Integer
Any # not a Union or TypeVar

julia> Union{Int64, T} where T<:Integer
Union{Int64, T} where T<:Integer

julia> Union{Union{},T} where T<:Integer
Integery # not a Union or TypeVar
```

No, this was not fixing a correctness bug. There is no ambiguity there.

Comment (vtjnash) [reply src/jltypes.c]: Unrelatedly, this PR is now very close to the unrelated issue encountered in https://github.com/JuliaLang/julia/issues/51637#issuecomment-1879245236, where it may error when the normalization fails, instead of simply not doing this normalization, if you are interested in taking a look at how it can avoid throwing the exception from normalization in the example there (for a later PR).

File: test/core.jl [hunk 2]
```diff
@@ -8101,3 +8101,14 @@ end
...
 @test_throws ErrorException Core.Intrinsics.pointerref(Ptr{Vector{Int64}}(C_NULL), 1, 0)
+
+# #53034 (Union normalization for typevar elimination)
+@test Tuple{Int,Any} <: Tuple{Union{Int,T},T} where {T>:Int}
+@test Tuple{Int,Any} <: Tuple{Union{Int,T},T} where {T>:Integer}
+# #53034 (Union normalization for Type elimination)
+@test Int isa Type{Union{Int,T2} where {T2<:T1}} where {T1}
+@test Int isa Type{Union{Int,T1}} where {T1}
+@test Int isa Union{UnionAll, Type{Union{Int,T2} where {T2<:T1}}} where {T1}
+@test Int isaUnion{Union, Type{Union{Int,T1}}} where {T1}
```
Comment (vtjnash) [inline test/core.jl:8112]:
```suggestion
@test Int isa Union{Union, Type{Union{Int,T1}}} where {T1}
```

**Review by vtjnash — APPROVED** [review]
