### PR TITLE
Handle incorrect call type in abstract_invoke

### LINKED ISSUE #46839: Unexpected error in runtime
```julia-repl
julia> using BenchmarkTools

julia> @btime invoke(BitSet, Any, x) setup=(x=rand(1:10_000, 10));
Internal error: encountered unexpected error in runtime:
TypeError(func=:specializations, context="", expected=DataType, got=Union{})
ijl_type_error_rt at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
ijl_type_error at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_specializations_get_linfo_ at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
#specialize_method#283 at ./compiler/utilities.jl:207
specialize_method at ./compiler/utilities.jl:193 [inlined]
typeinf_edge at ./compiler/typeinfer.jl:882
abstract_call_method at ./compiler/abstractinterpretation.jl:613
abstract_invoke at ./compiler/abstractinterpretation.jl:1682
abstract_call_known at ./compiler/abstractinterpretation.jl:1735
abstract_call at ./compiler/abstractinterpretation.jl:1901
abstract_call at ./compiler/abstractinterpretation.jl:1880
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2031
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2244
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2438
typeinf_local at ./compiler/abstractinterpretation.jl:2613
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2711
_typeinf at ./compiler/typeinfer.jl:232
typeinf at ./compiler/typeinfer.jl:215
typeinf_edge at ./compiler/typeinfer.jl:937
abstract_call_method at ./compiler/abstractinterpretation.jl:613
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:152
abstract_call_known at ./compiler/abstractinterpretation.jl:1830
abstract_call at ./compiler/abstractinterpretation.jl:1901
abstract_call at ./compiler/abstractinterpretation.jl:1880
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2031
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2244
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2438
typeinf_local at ./compiler/abstractinterpretation.jl:2613
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2711
_typeinf at ./compiler/typeinfer.jl:232
typeinf at ./compiler/typeinfer.jl:215
typeinf_ext at ./compiler/typeinfer.jl:1061
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1094
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1090
jfptr_typeinf_ext_toplevel_16233.clone_1 at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_type_infer at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_generate_fptr_impl at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-codegen.1.9.dylib (unknown line)
jl_compile_method_internal at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
#_run#48 at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:99
_run##kw at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:92
unknown function (ip: 0x117edcc0d)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_f__call_latest at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:807 [inlined]
invokelatest##kw at ./essentials.jl:802 [inlined]
#run_result#45 at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:34 [inlined]
run_result##kw at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:34 [inlined]
#run#49 at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:117
run##kw at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:117 [inlined]
run##kw at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:117 [inlined]
#warmup#54 at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:169 [inlined]
warmup at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:168
unknown function (ip: 0x117edc202)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
do_call at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
eval_body at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
top-level scope at /Users/x/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:575
jl_toplevel_eval_flex at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
ijl_toplevel_eval_in at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
eval at ./boot.jl:370 [inlined]
eval_user_input at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:152
repl_backend_loop at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:248
#start_repl_backend#46 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:233
start_repl_backend##kw at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:230 [inlined]
#run_repl#59 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:372
run_repl at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:357
jfptr_run_repl_59859.clone_1 at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
#1013 at ./client.jl:421
jfptr_YY.1013_27944.clone_1 at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_f__call_latest at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:805 [inlined]
invokelatest at ./essentials.jl:802 [inlined]
run_main_repl at ./client.jl:405
exec_options at ./client.jl:322
_start at ./client.jl:522
jfptr__start_54539.clone_1 at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
true_main at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.9.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.9.dylib (unknown line)
ERROR: TypeError: in invoke, expected Type{T} where T<:Tuple, got Type{Any}
Stacktrace:
 [1] var"##core#312"(x::var"##314") where var"##314"
   @ Main ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:489
 [2] var"##sample#313"(::Any, __params::BenchmarkTools.Parameters)
   @ Main ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:495
 [3] _run(b::BenchmarkTools.Benchmark, p::BenchmarkTools.Parameters; verbose::Bool, pad::String, kwargs::Base.Pairs{Symbol, Integer, NTuple{4, Symbol}, NamedTuple{(:samples, :evals, :gctrial, :gcsample), Tuple{Int64, Int64, Bool, Bool}}})
   @ BenchmarkTools ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:99
 [4] #invokelatest#2
   @ ./essentials.jl:807 [inlined]
 [5] #run_result#45
   @ ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:34 [inlined]
 [6] run(b::BenchmarkTools.Benchmark, p::BenchmarkTools.Parameters; progressid::Nothing, nleaves::Float64, ndone::Float64, kwargs::Base.Pairs{Symbol, Integer, NTuple{5, Symbol}, NamedTuple{(:verbose, :samples, :evals, :gctrial, :gcsample), Tuple{Bool, Int64, Int64, Bool, Bool}}})
   @ BenchmarkTools ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:117
 [7] #warmup#54
   @ ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:169 [inlined]
 [8] warmup(item::BenchmarkTools.Benchmark)
   @ BenchmarkTools ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:168
 [9] top-level scope
   @ ~/.julia/packages/BenchmarkTools/7xSXH/src/execution.jl:575
```
I get this in 1.8.0, and a recent (11 days) master
```
julia> versioninfo()
Julia Version 1.9.0-DEV.1318
Commit e36e56b1490 (2022-09-08 01:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, skylake)
  Threads: 1 on 2 virtual cores
Environment:
  LD_LIBRARY_PATH = /usr/local/lib
  JULIA_PKG_PRECOMPILE_AUTO = 0
```

### PR DESCRIPTION
**Pull request by apaz-cli**
Abstract interpreter was returning Any where calling the method would result in a MethodError, implying that the result should have been that the code was unreachable.

Fixes #46839

### CODE REVIEW

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -1679,15 +1679,18 @@ function abstract_invoke(interp::AbstractInterpreter, (; fargs, argtypes)::ArgIn
     ft = widenconst(ft′)
     ft === Bottom && return CallMeta(Bottom, EFFECTS_THROWS, NoCallInfo())
     (types, isexact, isconcrete, istype) = instanceof_tfunc(argtype_by_index(argtypes, 3))
-    types === Bottom && return CallMeta(Bottom, EFFECTS_THROWS, NoCallInfo())
+    unwrapped = unwrap_unionall(types)
+    if types === Bottom || types === Any || !(unwrapped isa DataType)
+        return CallMeta(Bottom, EFFECTS_THROWS, NoCallInfo())
```
Comment (Keno) [inline base/compiler/abstractinterpretation.jl:1684]: This doesn't seem right. If types is `Any`, we don't know much about what the types are, so it seems hard to believe that we would be able to prove that it throws. Perhaps you'd want to add these conditions to the `isexact` check on the next line instead?

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1684]: we know that it is exactly a literal `Any` here (from the previous check), not `<:Any`

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1684]: ah, nevermind, I got the order of those tests mixed up, and we are indeed now bypassing the `isexact` check

Comment (Keno) [reply base/compiler/abstractinterpretation.jl:1684]: Isn't that only true if `isexact` is set?

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1684]: The `isexact` check can also just be moved above this, since `types===Union{}` will always also be `isexact`

File: test/compiler/AbstractInterpreter.jl [hunk 2]
```diff
@@ -351,3 +351,7 @@ let NoinlineModule = Module()
         @test count(iscall((src, inlined_usually)), src.code) == 0
     end
 end
+
+# Issue #46839
+@test code_typed(()->invoke(BitSet, Any, x), ())[1][2] === Union{}
+@test code_typed(()->invoke(BitSet, Union{Tuple{Int32},Tuple{Int64}}, 1), ())[1][2] === Union{}
```
Comment (Keno) [inline test/compiler/AbstractInterpreter.jl:357]: This seems incorrect:
```
julia> invoke(BitSet, Tuple{Union{Int32,Int64}}, 1)
BitSet with 1 element:
  1
```

Comment (vtjnash) [reply test/compiler/AbstractInterpreter.jl:357]: When forming `Type`, it is usually required to preserve the type kind of the parameter, so that might be okay? Otherwise I suppose we need to compute the switched version of the Tuple/Union

Comment (Keno) [reply test/compiler/AbstractInterpreter.jl:357]: I'm not entirely sure what you're saying. My comment was purely saying that you cannot return `Union{}` here, because the function that it models does return.

Comment (vtjnash) [reply test/compiler/AbstractInterpreter.jl:357]: this exact call does fail though
```
julia> invoke(BitSet, Union{Tuple{Int32},Tuple{Int64}}, 1)
ERROR: TypeError: in invoke, expected Type{T} where T<:Tuple, got Type{Union{Tuple{Int32}, Tuple{Int64}}}
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

Comment (Keno) [reply test/compiler/AbstractInterpreter.jl:357]: Ok, I confused myself. Carry on.

Comment (vtjnash) [reply test/compiler/AbstractInterpreter.jl:357]: We perhaps should add handling for the Union case, since it is probably possible to get ml_matches for each, then Union and combine duplicate Methods. And it makes things more complete and uniform.

**Comment by apaz-cli** [comment]
Moved the isexact check up. It looked like CI was failing earlier, but we'll see what it thinks this time.

**Comment by vtjnash** [comment]
Looks like you forgot to make the change described?
