### PR TITLE
Make sleep(n) and Timer creation more MT-safe

### LINKED ISSUE #32152: sleep(n) sometimes segfaults in a threaded loop
When the following code is run with JULIA_NUM_THREADS=4, occasionally (about every 3 runs) I get a segfault on the second threaded loop invocation. I can't reproduce this with JULIA_NUM_THREADS=1.

MWE:

```
function f()
    Threads.@threads for i in 1:Threads.nthreads()
        sleep(1)
    end
end

println("First loop")
f()
println("Second loop")
f()
println("Done")
```

Occasional segfault message:

```
> JULIA_NUM_THREADS=4 julia-nightly tloop.jl
First loop
Second loop

signal (11): Segmentation fault
in expression starting at /home/jpsamaroo/tloop.jl:10
heap_remove at /workspace/srcdir/libuv/src/heap-inl.h:196
uv_timer_stop at /workspace/srcdir/libuv/src/timer.c:97
uv__run_timers at /workspace/srcdir/libuv/src/timer.c:160
uv_run at /workspace/srcdir/libuv/src/unix/core.c:375
jl_task_get_next at /buildworker/worker/package_linux64/build/src/partr.c:421
poptaskref at ./task.jl:568
wait at ./task.jl:575
wait at ./condition.jl:104
stream_wait at ./stream.jl:47
wait at ./asyncevent.jl:116
sleep at ./asyncevent.jl:187 [inlined]
macro expansion at /home/jpsamaroo/tloop.jl:3 [inlined]
#2#threadsfor_fun at ./threadingconstructs.jl:64
#2#threadsfor_fun at ./threadingconstructs.jl:31
unknown function (ip: 0x7faa244052ec)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2043 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2213
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1624 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:594
unknown function (ip: 0xffffffffffffffff)
Allocations: 152504 (Pool: 152439; Big: 65); GC: 0
Segmentation fault (core dumped)
```

EDIT: Corrected versioninfo():
```
julia> versioninfo()
Julia Version 1.3.0-DEV.289
Commit e39f498aca (2019-05-25 00:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_REVISE_POLL = 1
  JULIA_LOAD_PATH = @dev:@:@v#.#:@stdlib
  JULIA_PKG3_PRECOMPILE = 1
```
@JeffBezanson

### PR DESCRIPTION
**Pull request by jpsamaroo**
This returns some of the locking removed by https://github.com/JuliaLang/julia/pull/32029/commits/93e3d284a6205d9a9cca6d5bdb3856439e0b55ad (which @JeffBezanson said was removed because it was probably incorrect), but this time the calls to `uv_update_time` and `uv_timer_start` are done within a single lock/unlock of the global libuv lock (instead of two separate lock/unlock pairs).

This still hangs every so often on my system with `JULIA_NUM_THREADS=8` when running a slightly longer version of the test laid out in https://github.com/JuliaLang/julia/issues/32152, which I'd like to have this PR fix once I figure out the root cause. I also think this PR should have at least one test to ensure highly-contended calls to `sleep` or `Timer` don't cause segfaults or hangs; I'll add a simple test to this PR soon to get something on the table.

(Eventually) fixes https://github.com/JuliaLang/julia/issues/32152

### CODE REVIEW

**Comment by JeffBezanson** [comment]
`uv_timer_init` needs to be inside the lock too since it inserts into a queue in the event loop object.

File: src/jl_uv.c [hunk 1]
```diff
@@ -1085,6 +1085,25 @@ JL_DLLEXPORT int jl_queue_work(work_cb_t work_func, void *work_args, void *work_
...
+{
+    JL_UV_LOCK();
+    int err = uv_timer_init(loop, handle);
+    if (err) {
+        // TODO: this codepath is currently not tested
+        free(handle);
+        return err;
+    }
+
+    jl_uv_associate_julia_struct((uv_handle_t *)handle, (jl_value_t *)handle);
```
Comment (vtjnash) [inline src/jl_uv.c]: one of these things is not like the other—you can't cast to both libuv and julia

File: src/jl_uv.c [hunk 2]
```diff
@@ -1085,6 +1085,25 @@ JL_DLLEXPORT int jl_queue_work(work_cb_t work_func, void *work_args, void *work_
...
 
+JL_DLLEXPORT int jl_uv_update_timer_start(uv_loop_t* loop, uv_timer_t* handle,
+                                          uv_timer_cb cb, uint64_t timeout,
+                                          uint64_t repeat)
+{
+    JL_UV_LOCK();
+    int err = uv_timer_init(loop, handle);
+    if (err) {
+        // TODO: this codepath is currently not tested
+        free(handle);
```
Comment (vtjnash) [inline src/jl_uv.c]: missing JL_UV_UNLOCK on this codepath, also probably better to keep the `free` call in Julia

File: src/jl_uv.c (hunk 1 above)
Comment (jpsamaroo) [reply src/jl_uv.c]: Sorry, I'm getting slightly confused by what's what, since in the following two locations it seems that we're already passing objects which (to my uneducated eyes) seem to end up with casts that are essentially the same as what you pointed out at:

https://github.com/JuliaLang/julia/blob/4b0c8e7edb848e8f8b9047ee12678d8e8b0609bf/base/asyncevent.jl#L90
https://github.com/JuliaLang/julia/blob/4b0c8e7edb848e8f8b9047ee12678d8e8b0609bf/base/asyncevent.jl#L102-L103

Those two libuv calls don't expect a `jl_value_t*`, even though that's what we're doing there, right? I assume it works because `this.handle` is the first field in the `Timer` struct so the pointers are the same anyway?

File: src/jl_uv.c (hunk 2 above)
Comment (jpsamaroo) [reply src/jl_uv.c]: Hopefully my latest commit addresses both of these properly :smile:

File: base/asyncevent.jl [hunk 3]
```diff
@@ -87,21 +87,17 @@ mutable struct Timer
         interval ≥ 0 || throw(ArgumentError("timer cannot have negative repeat interval of $interval seconds"))
 
         this = new(Libc.malloc(_sizeof_uv_timer), ThreadSynchronizer(), true)
-        err = ccall(:uv_timer_init, Cint, (Ptr{Cvoid}, Ptr{Cvoid}), eventloop(), this)
+        err = ccall(:jl_uv_update_timer_start, Cint,
+              (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, UInt64, UInt64),
```
Comment (JeffBezanson) [inline base/asyncevent.jl]: The second type should be `Any`.

Comment (JeffBezanson) [reply base/asyncevent.jl]: What's happening is the `unsafe_convert` method below causes `this.handle` to be passed instead of `this` when the argument type is `Ptr{Cvoid}`.

Comment (JeffBezanson) [reply base/asyncevent.jl]:
```suggestion
              (Ptr{Cvoid}, Any, Ptr{Cvoid}, Ptr{Cvoid}, UInt64, UInt64),
```

Comment (jpsamaroo) [reply base/asyncevent.jl]: I made the change, although it hung on "Generating precompile statements..." for me (no CPU activity):

```
Generating precompile statements...
signal (15): Terminated
in expression starting at /opt/julia-dev/contrib/generate_precompile.jl:8
epoll_pwait at /lib64/libc.so.6 (unknown line)
uv__io_poll at /workspace/srcdir/libuv/src/unix/linux-core.c:261
uv_run at /workspace/srcdir/libuv/src/unix/core.c:361
jl_task_get_next at /opt/julia-dev/src/partr.c:421
poptaskref at ./task.jl:568
wait at ./task.jl:575
wait at ./condition.jl:104
wait_readbyte at ./stream.jl:1177
readuntil at ./stream.jl:867 [inlined]
readuntil_string at ./io.jl:645 [inlined]
#readuntil#295 at ./io.jl:768
readuntil at ./io.jl:765 [inlined]
#2 at /opt/julia-dev/contrib/generate_precompile.jl:127
```

File: src/jl_uv.c [hunk 4]
```diff
@@ -1085,6 +1085,24 @@ JL_DLLEXPORT int jl_queue_work(work_cb_t work_func, void *work_args, void *work_
     return 0;
 }
 
+JL_DLLEXPORT int jl_uv_update_timer_start(uv_loop_t* loop, jl_value_t* jltimer,
+                                          uv_timer_t* uvtimer, uv_timer_cb cb,
+                                          uint64_t timeout, uint64_t repeat)
+{
+    JL_UV_LOCK();
+    int err = uv_timer_init(loop, uvtimer);
+    if (err) {
```
Comment (vtjnash) [inline src/jl_uv.c]: this actually can't fail, so we can just delete the error checking code (or make it an abort)

File: src/jl_uv.c [hunk 5]
```diff
@@ -1085,6 +1085,24 @@ JL_DLLEXPORT int jl_queue_work(work_cb_t work_func, void *work_args, void *work_
...
+        JL_UV_UNLOCK();
+        return err;
+    }
+
+    jl_uv_associate_julia_struct((uv_handle_t*)uvtimer, jltimer);
+    uv_update_time(loop);
+    err = uv_timer_start(uvtimer, cb, timeout, repeat);
```
Comment (vtjnash) [inline src/jl_uv.c]: similarly, this can't actually fail either, we can just `abort` if it returns non-zero

File: base/asyncevent.jl (hunk 3 above)
Comment (JeffBezanson) [reply base/asyncevent.jl]: Strange. Works for me.

Comment (jpsamaroo) [reply base/asyncevent.jl]: Huh, yeah, seems like it was just bad state. A rebuild worked for me.

**Review by JeffBezanson — APPROVED** [review]

**Comment by alhirzel** [comment]
I believe I encountered one of the hanging conditions mentioned at the top of the PR, and wanted to note for others that `Libc.systemsleep` can be used instead (as mentioned in #14494) when a busysleep is needed, e.g. when emulating a task scheduler.
