### PR TITLE
fix #16096, incorrect var renaming inside macrocall exprs in macroexpand

### LINKED ISSUE #16096: `esc` cannot be used in function arguments
``` julia
module Foo
macro iter()
  quote
    @inline function Base.start(sub)
      it = 1
    end
  end
end
end
```

Macroexpanding `Foo.@iter` yields a function with an argument `Foo.sub` and a local `Foo.it`, both of which are broken.

In fewer cases (but still in this case) 0.4 also qualifies `sub`, but gensyms `it` correctly.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -3864,3 +3864,17 @@ function f16023()
     x = 1
 end
 @test_throws UndefVarError f16023()
+
+# issue #16096
+module M16096
+macro iter()
+  quote
```
Comment (tkelman) [inline test/core.jl]: wrong indent
