### PR TITLE
Fix relpath when path and startpath are in the same drive

### LINKED ISSUE #40237: Breaking `relpath` change on Windows with Julia 1.6
I realize I should have been testing on nightly to catch things like this earlier, but it looks like a breaking `relpath` change was introduced in Julia 1.6 for Windows. The following test now fails:

```julia
rel_str = joinpath("..", "src", "FilePathsBase.jl")
rel_fp = Path(rel_str)
@test relpath(abspath(rel_str)) == rel_str
@test string(relpath(absolute(rel_fp))) == rel_str
```
with 
```julia
relpath: Test Failed at D:\a\FilePathsBase.jl\FilePathsBase.jl\test\system.jl:224
  Expression: relpath(abspath(rel_str)) == rel_str
   Evaluated: "D:\\a\\FilePathsBase.jl\\FilePathsBase.jl\\src\\FilePathsBase.jl" == "..\\src\\FilePathsBase.jl"
```

I'm guessing this was introduced by https://github.com/JuliaLang/julia/pull/38259 because the default `startpath` of `.` doesn't have a drive letter? I'm guessing we probably want to special case relative path arguments? I can make a PR, but I just wanted to confirm that we want to maintain the old behaviour first.

https://github.com/rofinn/FilePathsBase.jl/runs/2206524503?check_suite_focus=true#step:7:86

### PR DESCRIPTION
**Pull request by musm**
When startpath == ".", assume the startpath is in the same drive.
This subsequently required tweaking the existing logic to then
canonicalize the drive letter casing (uppercased) in instances where the drive casing
differs.

close #40237

### CODE REVIEW

File: base/path.jl [hunk 1]
```diff
@@ -517,12 +517,20 @@ function relpath(path::String, startpath::String = ".")
...
+        path_drive, path_without_drive = splitdrive(path)
+        startpath_drive, startpath_without_drive = splitdrive(startpath)
+        isempty(startpath_drive) && (startpath_drive = path_drive) # by default assume same as path drive
+
+        path_drive = uppercase(path_drive) # canonicalize drive letters to uppercasing for comparison
+        startpath_drive = uppercase(startpath_drive)
+
+        path_drive != startpath_drive && return abspath(path) # if drives differ return first path
+        path_arr  = split(abspath(path_drive * path_without_drive),      path_separator_re)
+        start_arr = split(abspath(startpath_drive * startpath_without_drive), path_separator_re)
```
Comment (vtjnash) [inline base/path.jl:530]: Since `path_drive` may involve a DNS lookup, I think we should preserve the input case:
```suggestion
        startpath_drive = uppercase(startpath_drive) # canonicalize drive letters to uppercasing for comparison
        uppercase(path_drive) == startpath_drive || return abspath(path) # if drives differ return first path
        path_arr  = split(abspath(path_drive * path_without_drive),      path_separator_re)
        start_arr = split(abspath(path_drive * startpath_without_drive), path_separator_re)
```

Comment (musm) [reply base/path.jl]: Even better, thank you for the review. PR updated.

**Review by vtjnash — APPROVED** [review]
