### PR TITLE
`alg` keyword for svd and svd!

### LINKED ISSUE #607: `svd` gives wrong results (upstream LAPACK bug)
See [this discourse thread](https://discourse.julialang.org/t/svd-better-default-to-gesvd-instead-of-gesdd/20603).

There is an [upstream bug in LAPACK's `gesdd`](https://github.com/Reference-LAPACK/lapack/issues/316) when run in full mode (`'A'`). Since our `svd`, only call `LinearAlgebra.LAPACK.gesdd!` under the hood, it currently gives wrong results:

```julia
using LinearAlgebra

function compan(c::AbstractVector{T}) where T
    N = length(c)
    A = diagm(-1 => ones(T, N-1))
    @inbounds for i in 1:N
        A[1,i] = - c[i]/c[1]
    end
    A
end

function svdvaldiff(N)
  A = compan(reverse( vcat(1, 1 ./ cumprod(1:N, dims=1)) ));
  svals_DnC = svd(A).S
  svals_QR  = svdvals(A)

  return maximum(svals_DnC - svals_QR)
end

function DnC_QR_comparison(Nmax=40)
    for N in 1:Nmax
        println("N = $(N), max diff svdvals: ", svdvaldiff(N)) 
    end
end

DnC_QR_comparison()
```

which produces

```julia
julia> DnC_QR_comparison()
N = 1, max diff svdvals: 0.0
N = 2, max diff svdvals: 0.0
N = 3, max diff svdvals: 0.0
N = 4, max diff svdvals: 0.0
N = 5, max diff svdvals: 0.0
N = 6, max diff svdvals: 0.0
N = 7, max diff svdvals: 0.0
N = 8, max diff svdvals: 0.0
N = 9, max diff svdvals: 0.0
N = 10, max diff svdvals: 0.0
N = 11, max diff svdvals: 0.0
N = 12, max diff svdvals: 0.0
N = 13, max diff svdvals: 0.0
N = 14, max diff svdvals: 0.0
N = 15, max diff svdvals: 0.0
N = 16, max diff svdvals: 0.0
N = 17, max diff svdvals: 0.0
N = 18, max diff svdvals: 0.0
N = 19, max diff svdvals: 0.0
N = 20, max diff svdvals: 0.0
N = 21, max diff svdvals: 0.0
N = 22, max diff svdvals: 0.0
N = 23, max diff svdvals: 0.0
N = 24, max diff svdvals: 0.0
N = 25, max diff svdvals: 749.7516745517077
N = 26, max diff svdvals: 166.767736950586
N = 27, max diff svdvals: 584.3097624800283
N = 28, max diff svdvals: 635.9955873150014
N = 29, max diff svdvals: 752.0372910883041
N = 30, max diff svdvals: 934.3056077045787
N = 31, max diff svdvals: 532.6321090336445
N = 32, max diff svdvals: 644.2861698543643
N = 33, max diff svdvals: 362.0563181932318
N = 34, max diff svdvals: 524.8519471908377
N = 35, max diff svdvals: 681.9577012165146
N = 36, max diff svdvals: 959.8179240905338
N = 37, max diff svdvals: 116.35110997021529
N = 38, max diff svdvals: 510.2091542800206
N = 39, max diff svdvals: 245.12683184534578
N = 40, max diff svdvals: 6.869915826281117
```

Note that if one replace `'A'` by `'N'` in the `gesdd!` call everything is fine.

Since it doesn't seem to be clear whether this is a bug in the implementation of `gesdd` or a shortcoming of the divide-and-conquer approach, I suggest that we default to `gesvd` for `full=true` until this is resolved. (Note that this comes with a performance penalty for large matrices.)

### LINKED ISSUE #31023: `svd` gives wrong results (upstream LAPACK bug)
See [this discourse thread](https://discourse.julialang.org/t/svd-better-default-to-gesvd-instead-of-gesdd/20603).

There is an [upstream bug in LAPACK's `gesdd`](https://github.com/Reference-LAPACK/lapack/issues/316) when run in full mode (`'A'`). Since our `svd`, only call `LinearAlgebra.LAPACK.gesdd!` under the hood, it currently gives wrong results:

```julia
using LinearAlgebra

function compan(c::AbstractVector{T}) where T
    N = length(c)
    A = diagm(-1 => ones(T, N-1))
    @inbounds for i in 1:N
        A[1,i] = - c[i]/c[1]
    end
    A
end

function svdvaldiff(N)
  A = compan(reverse( vcat(1, 1 ./ cumprod(1:N, dims=1)) ));
  svals_DnC = svd(A).S
  svals_QR  = svdvals(A)

  return maximum(svals_DnC - svals_QR)
end

function DnC_QR_comparison(Nmax=40)
    for N in 1:Nmax
        println("N = $(N), max diff svdvals: ", svdvaldiff(N)) 
    end
end

DnC_QR_comparison()
```

which produces

```julia
julia> DnC_QR_comparison()
N = 1, max diff svdvals: 0.0
N = 2, max diff svdvals: 0.0
N = 3, max diff svdvals: 0.0
N = 4, max diff svdvals: 0.0
N = 5, max diff svdvals: 0.0
N = 6, max diff svdvals: 0.0
N = 7, max diff svdvals: 0.0
N = 8, max diff svdvals: 0.0
N = 9, max diff svdvals: 0.0
N = 10, max diff svdvals: 0.0
N = 11, max diff svdvals: 0.0
N = 12, max diff svdvals: 0.0
N = 13, max diff svdvals: 0.0
N = 14, max diff svdvals: 0.0
N = 15, max diff svdvals: 0.0
N = 16, max diff svdvals: 0.0
N = 17, max diff svdvals: 0.0
N = 18, max diff svdvals: 0.0
N = 19, max diff svdvals: 0.0
N = 20, max diff svdvals: 0.0
N = 21, max diff svdvals: 0.0
N = 22, max diff svdvals: 0.0
N = 23, max diff svdvals: 0.0
N = 24, max diff svdvals: 0.0
N = 25, max diff svdvals: 749.7516745517077
N = 26, max diff svdvals: 166.767736950586
N = 27, max diff svdvals: 584.3097624800283
N = 28, max diff svdvals: 635.9955873150014
N = 29, max diff svdvals: 752.0372910883041
N = 30, max diff svdvals: 934.3056077045787
N = 31, max diff svdvals: 532.6321090336445
N = 32, max diff svdvals: 644.2861698543643
N = 33, max diff svdvals: 362.0563181932318
N = 34, max diff svdvals: 524.8519471908377
N = 35, max diff svdvals: 681.9577012165146
N = 36, max diff svdvals: 959.8179240905338
N = 37, max diff svdvals: 116.35110997021529
N = 38, max diff svdvals: 510.2091542800206
N = 39, max diff svdvals: 245.12683184534578
N = 40, max diff svdvals: 6.869915826281117
```

Note that if one replace `'A'` by `'N'` in the `gesdd!` call everything is fine.

Since it doesn't seem to be clear whether this is a bug in the implementation of `gesdd` or a shortcoming of the divide-and-conquer approach, I suggest that we default to `gesvd` for `full=true` until this is resolved. (Note that this comes with a performance penalty for large matrices.)

### PR DESCRIPTION
**Pull request by carstenbauer**
This PR adds an `alg` keyword to `svd` and `svd!` which allows the user to switch between a divide-and-conquer algorithm (default, `LAPACK.gesdd!`) and a simple algorithm (`LAPACK.gesvd!`).

In the future, [Jacobi methods](https://discourse.julialang.org/t/calling-lapacks-jacobi-svd-dgesvj/20602) could also be added. (#31080)

See JuliaLang/LinearAlgebra.jl#607 and https://discourse.julialang.org/t/svd-better-default-to-gesvd-instead-of-gesdd/20603 for related discussions.

Closes JuliaLang/LinearAlgebra.jl#607.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Can you add some tests? 

I'm not sure I like `alg` as a keyword: maybe use the full `algorithm` (LAPACK calls them "drivers", but that is far from obvious).

**Comment by ararslan** [comment]
FWIW `sort` also uses `alg`.

**Comment by crstnbr** [comment]
> Can you add some tests?

Sure. What should I test? Only that the keyword argument exists or also that the results differ (maybe for something as in https://github.com/JuliaLang/julia/issues/31023)?

**Comment by StefanKarpinski** [comment]
> Only that the keyword argument exists or also that the results differ (maybe for something as in #31023)?

I would test first that the keywords are accepted and that the results look like correct SVDs, i.e.:
1. that `U*S*V' ≈ X`
2. that `U` and `V` are approximately orthogonormal
3. that the singular values are all non-negative
4. if there are particular characteristics that each algorithm should have, test those

**Comment by crstnbr** [comment]
This is being discussed on Slack. @andreasnoack pointed out the he made a [similar change](https://github.com/JuliaGPU/CuArrays.jl/blob/master/src/solver/highlevel.jl#L88-L95) in `CuArrays.jl` recently.

Maybe it's better to call the keyword `method` as people seem to prefer it and it would be consistent with aboves change.

The remaining questions seem to be:
* How verbose do we want to be, e.g. `:divide` vs `:divideandconquer`?
* Do we want to use `Symbol`s, `Enum`s, or even types?

**Comment by StefanKarpinski** [comment]
> Maybe it's better to call the keyword `method` as people seem to prefer it and it would be consistent with aboves change.

Possibly but keep in mind that "method" already has a fairly well-established meaning in programming languages which does not really agree with this meaning. It's fine to call these methods informally but "algorithm" seems both more precise and less confusing in this context.

**Comment by simonbyrne** [comment]
Someone pointed out on Slack (I forgot who), that we do use `alg` in `sort`, so there is precedence.

I'm not hugely keen on using symbols as enums though.

**Comment by ararslan** [comment]
I said that in [a comment](https://github.com/JuliaLang/julia/pull/31057#issuecomment-463344163) in this PR 5 days ago. :neutral_face:

**Comment by andreasnoack** [comment]
I think we should consider using a struct for this. Then the `svd` can be extended easily by the `JacobiSVD` package.

**Comment by crstnbr** [comment]
Alright, I updated this one. I'm unsure about naming. I introduced

```julia
abstract type SVDAlgorithm end
struct DivideAndConquer <: SVDAlgorithm end
struct Simple <: SVDAlgorithm end
```

but in particular `Simple` seems very general and vague. Any suggestions?

**Comment by andreasnoack** [comment]
Some of these types might make sense across more than a single factorization e.g. there is also a divide and conquer version of the symmetric tridiagonal eigensolver so either we should just have a shared `Algorithm` type in `LinearAlgebra` or we'd have to put `SVD` in the struct names. I'd prefer the former.

**Comment by StefanKarpinski** [comment]
I'm not too keen on the name "Simple". That doesn't really narrow it down. Does this simple algorithm not have a proper name?

**Comment by simonbyrne** [comment]
Golub and Van Loan just call it "The SVD Algorithm".

From [this paper on the history of the SVD](https://epubs.siam.org/doi/abs/10.1137/1035134) 
> The singular value decomposition was introduced into numerical analysis by [Golub and Kahan [23, 1965], who proposed a computational algorithm. However, it was Golub [24, 1970] who gave the algorithm that has been the workhorse of the past two decades.

The referenced papers are:
 - [Golub and Kahan (1965)](https://epubs.siam.org/doi/abs/10.1137/0702016)
 - [Golub and Reinsch (1970)](https://link.springer.com/chapter/10.1007/978-3-642-86940-2_10)

"Golub-Kahan" usually refers to the bidiagonalization step. So I guess we could call it `GolubReinsch`? However as @andreasnoack points out, SVD algorithms are in some sense equivalent to symmetric eigenvalue algorithms: if I understand it correctly, the equivalent is the QR algorithm, which [as the wikipedia article points out, is a terrible name](https://en.wikipedia.org/wiki/QR_algorithm#Renaming_proposal).

Maybe @higham might be able to help here.

**Comment by crstnbr** [comment]
Alright, would be great if someone could review this. AFAICT, the two run failures are unrelated.

**Comment by crstnbr** [comment]
bump :)

**Comment by crstnbr** [comment]
Would be great if this would make it into 1.3. Could someone review this before feature freeze?

File: stdlib/LinearAlgebra/test/svd.jl [hunk 1]
```diff
@@ -139,4 +139,35 @@ aimg  = randn(n,n)/2
     end
 end
 
+
+
+@testset "SVD Algorithms" begin
+    ≊(x,y) = isapprox(x,y,rtol=1e-15)
```
Comment (tpapp) [inline stdlib/LinearAlgebra/test/svd.jl]: I think you can use plain vanilla
```julia
x ≈ y rtol = 8*eps()
```
in tests below.

File: stdlib/LinearAlgebra/test/svd.jl [hunk 2]
```diff
@@ -139,4 +139,35 @@ aimg  = randn(n,n)/2
...
+
+    allpos = (v) -> begin
```
Comment (tpapp) [inline stdlib/LinearAlgebra/test/svd.jl]: I am not sure you need a custom function for this, eg
```julia
all(sx1.S .≥ 0)
```
is fine for tests.

File: stdlib/LinearAlgebra/src/svd.jl [hunk 3]
```diff
@@ -54,14 +54,15 @@ function SVD{T}(U::AbstractArray, S::AbstractVector{Tr}, Vt::AbstractArray) wher
...
+
 # iteration for destructuring into components
 Base.iterate(S::SVD) = (S.U, Val(:S))
 Base.iterate(S::SVD, ::Val{:S}) = (S.S, Val(:V))
 Base.iterate(S::SVD, ::Val{:V}) = (S.V, Val(:done))
 Base.iterate(S::SVD, ::Val{:done}) = nothing
 
 """
-    svd!(A; full::Bool = false) -> SVD
+    svd!(A; full::Bool = false, alg::Algorithm = DivideAndConquer()) -> SVD
```
Comment (tpapp) [inline stdlib/LinearAlgebra/src/svd.jl]: I would consider a 
```julia
default_svd_algorithm(A) = DivideAndConquer()
```
then
```julia
svd!(A; full::Bool = false, alg::Algorithm = default_svd_algorithm(A))
```
which would keep things flexible (cf `Sort.defalg` in `Base`).

**Comment by tpapp** [comment]
FWIW, I have reviewed, but note that I am not a core dev so I am not sure how much it helps. I just really like the change and would also love to see it in 1.3.

File: stdlib/LinearAlgebra/test/svd.jl (hunk 1 above)
Comment (crstnbr) [reply stdlib/LinearAlgebra/test/svd.jl]: Doesn't really matter, right? Also, I'd have to repeat the `rtol = 8*eps()` a bunch of times.

Comment (crstnbr) [reply stdlib/LinearAlgebra/test/svd.jl]: Also note that I copied this idea from further up in the file (a piece not added by me).

File: stdlib/LinearAlgebra/test/svd.jl (hunk 2 above)
Comment (crstnbr) [reply stdlib/LinearAlgebra/test/svd.jl]: Alright.

**Comment by StefanKarpinski** [comment]
@andreasnoack, could you possibly find the time to review this?

File: stdlib/LinearAlgebra/src/svd.jl [hunk 4]
```diff
@@ -92,18 +97,25 @@ julia> A
...
 ```
 """
-function svd!(A::StridedMatrix{T}; full::Bool = false) where T<:BlasFloat
+function svd!(A::StridedMatrix{T}; full::Bool = false, alg::Algorithm = default_svd_alg(A)) where T<:BlasFloat
     m,n = size(A)
     if m == 0 || n == 0
         u,s,vt = (Matrix{T}(I, m, full ? m : n), real(zeros(T,0)), Matrix{T}(I, n, n))
     else
-        u,s,vt = LAPACK.gesdd!(full ? 'A' : 'S', A)
+        if typeof(alg) == DivideAndConquer
```
Comment (andreasnoack) [inline stdlib/LinearAlgebra/src/svd.jl]: Better to use dispatch for this

File: stdlib/LinearAlgebra/src/svd.jl [hunk 5]
```diff
@@ -120,6 +132,9 @@ and `V` is `N \\times N`, while in the thin factorization `U` is `M
 \\times K` and `V` is `N \\times K`, where `K = \\min(M,N)` is the
 number of singular values.
 
+If `alg = DivideAndConquer()` a divide-and-conquer algorithm is used to calculate the SVD.
+Another (typically slower) option is `alg = GolubReinsch()`.
```
Comment (andreasnoack) [inline stdlib/LinearAlgebra/src/svd.jl]:
```suggestion
Another (typically slower but more accurate) option is `alg = GolubReinsch()`.
```

**Review by andreasnoack — COMMENTED** [review]
It mostly looks ready to go. I've added a few comments and suggestions.

File: stdlib/LinearAlgebra/src/LinearAlgebra.jl [hunk 6]
```diff
@@ -156,6 +156,12 @@ else
     const BlasInt = Int32
 end
 
+
+abstract type Algorithm end
+struct DivideAndConquer <: Algorithm end
+struct GolubReinsch <: Algorithm end
```
[the remark this answers is not in the document]
Comment (crstnbr) [reply stdlib/LinearAlgebra/src/LinearAlgebra.jl]: Ok, I'll change it to `QRIteration` (just in case you haven't noticed `GolubReinsch` was suggested above.)

File: stdlib/LinearAlgebra/src/svd.jl (hunk 4 above)
Comment (crstnbr) [reply stdlib/LinearAlgebra/src/svd.jl]:
```julia
function svd!(A::StridedMatrix{T}; full::Bool = false, alg::Algorithm = default_svd_alg(A)) where T<:BlasFloat
    m,n = size(A)
    if m == 0 || n == 0
        u,s,vt = (Matrix{T}(I, m, full ? m : n), real(zeros(T,0)), Matrix{T}(I, n, n))
    else
        u,s,vt = _lapack_svd(A,full,alg)
    end
    SVD(u,s,vt)
end


_lapack_svd(A::StridedMatrix{T}, full::Bool, alg::Algorithm) where T<:BlasFloat = throw(ArgumentError("Unsupported value for `alg` keyword."))
_lapack_svd(A::StridedMatrix{T}, full::Bool, alg::DivideAndConquer) where T<:BlasFloat = LAPACK.gesdd!(full ? 'A' : 'S', A)
function _lapack_svd(A::StridedMatrix{T}, full::Bool, alg::QRIteration) where T<:BlasFloat
    c = full ? 'A' : 'S'
    u,s,vt = LAPACK.gesvd!(c, c, A)
end
```

Is this what you have in mind?

Comment (andreasnoack) [reply stdlib/LinearAlgebra/src/svd.jl]: Yes exactly. (I'd just call it `_svd!`, though)

**Comment by crstnbr** [comment]
Implemented the comments by @andreasnoack. Tests pass locally.

**Comment by andreasnoack** [comment]
@fredrikekre I've forgotten how we add the compat annotations. Could you help us out here?

**Comment by crstnbr** [comment]
Until when does this have to be merged to be in 1.3?

**Comment by ararslan** [comment]
> I've forgotten how we add the compat annotations

In the docstring for the function, add
```
!!! compat "Julia 1.3"
    The `method` keyword argument requires Julia 1.3 or later.
```

**Comment by crstnbr** [comment]
@ararslan the keyword argument is named `alg`

I added the compat annotation and fixed the NEWS.md conflict.

**Comment by Jutho** [comment]
Great addition; I had this in some local packages. 1.3 will be a great release.
