### PR TITLE
REPL: fix #27184, ensure macro existence before lowering

### LINKED ISSUE #27184: REPL completion error: UndefVarError
Open julia with REPL, type `@nonexist.` and hit Tab:

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.5138 (2018-05-19 22:52 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a465d33f6 (1 day old master)
|__/                   |  x86_64-redhat-linux

julia> @nonexist.┌ Error: Error in the keymap
│   exception =
│    LoadError: UndefVarError: @nonexist not defined
│    Stacktrace:
│     [1] top-level scope
│     [2] lower at ./meta.jl:68 [inlined]
│     [3] get_type(::Expr, ::Module) at /TEST/usr/share/julia/stdlib/v0.7/REPL/src/REPLCompletions.jl:362
│     [4] complete_symbol(::String, ::getfield(REPL.REPLCompletions, Symbol("##15#17"))) at /TEST/usr/share/julia/stdlib/v0.7/REPL/src/REPLCompletions.jl:63
│     [5] completions(::String, ::Int64) at /TEST/usr/share/julia/stdlib/v0.7/REPL/src/REPLCompletions.jl:648
...

```

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -456,6 +456,12 @@ function get_type(sym::Expr, fn::Module)
     # try to analyze nests of calls. if this fails, try using the expanded form.
     val, found = try_get_type(sym, fn)
     found && return val, found
+    # https://github.com/JuliaLang/julia/issues/27184
+    if isexpr(sym, :macrocall)
+        s = first(sym.args)
+        isa(s, Symbol) && !isdefined(fn, s) && return Any, false
+        isa(s, GlobalRef) && !isdefined(s.mod, s.name) && return Any, false
```
Comment (simeonschaub) [inline stdlib/REPL/src/REPLCompletions.jl:463]: This does not seem to handle `A.@b. <tab>` yet

Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl]: ops, thanks !

File: stdlib/REPL/src/REPLCompletions.jl [hunk 2]
```diff
@@ -384,6 +384,7 @@ function get_value(sym::Expr, fn)
 end
 get_value(sym::Symbol, fn) = isdefined(fn, sym) ? (getfield(fn, sym), true) : (nothing, false)
 get_value(sym::QuoteNode, fn) = isdefined(fn, sym.value) ? (getfield(fn, sym.value), true) : (nothing, false)
+get_value(sym::GlobalRef, fn) = get_value(sym.name, sym.mod)
```
Comment (aviatesk) [inline stdlib/REPL/src/REPLCompletions.jl:387]: I added this method because `Core.@cmd` macro will be lowered with `GlobalRef`, but this one looks a bit weird since it totally ignores the context `fn`.
Maybe special-casing it inside `isexpr(sym, :macrocall)` block within `get_type` looks better ?

Comment (simeonschaub) [reply stdlib/REPL/src/REPLCompletions.jl:387]: This seems like the correct thing to do to me. Of course, we would expect all `GlobalRef`s emitted by the parser to actually exist, but I don't think being more defensive here hurts.

Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl:387]: okay, then I will leave this as is.

**Review by simeonschaub — APPROVED** [review]
