### PR TITLE
expose `findall` for `Vector{UInt8}`

### LINKED ISSUE #45295: findall(::Array{UInt8}, ::Array{UInt8}) not implemented
Trying to use find* functions with UInt8 arrays, I found PR [37283](https://github.com/JuliaLang/julia/pull/37283).
In news.md, it says that "findfirst, findnext, findlast, and findall" support it, but it is wrong. 
It is supported by `findprev` also and not by `findall`.

```julia
> VERSION
v"1.7.2"
> a = rand(UInt8, 2);
> b = rand(UInt8, 10);
> findfirst(a, b)

> findprev(a, b, 10)

> findall(a, b)
ERROR: MethodError: no method matching findall(::Vector{UInt8}, ::Vector{UInt8})
Closest candidates are:
  findall(::Base.Fix2{typeof(in), <:Union{Real, Array{<:Real}}}, ::Array{<:Real}) at /usr/share/julia/base/array.jl:2417
  findall(::Base.Fix2{typeof(in)}, ::AbstractArray) at /usr/share/julia/base/array.jl:2426
  findall(::Function, ::AbstractArray) at /usr/share/julia/base/array.jl:2257
  ...
```

### PR DESCRIPTION
**Pull request by Moelf**
fix #45295

### CODE REVIEW

File: test/regex.jl [hunk 1]
```diff
@@ -69,6 +69,10 @@
     @test findall('→', "OH⁻ + H₃CBr →  HOH₃CBr⁻ → HOCH₃ + Br⁻") == [17, 35]
     @test findall('a', "") == Int[]
     @test findall('c', "batman") == Int[]
+    @test findall([0x52, 0x62], [0x40, 0x52, 0x62, 0x63]) == [2:3]
+    @test findall([0x52, 0x62], [0x40, 0x52, 0x62, 0x63, 0x52, 0x64]) == [2:3, 5:6]
```
Comment (ianatol) [inline test/regex.jl:73]:
```suggestion
    @test findall([0x52, 0x62], [0x40, 0x52, 0x62, 0x63, 0x52, 0x62]) == [2:3, 5:6]
```

File: base/regex.jl [hunk 2]
```diff
@@ -444,6 +444,11 @@ findfirst(r::Regex, s::AbstractString) = findnext(r,s,firstindex(s))
         string::AbstractString;
         overlap::Bool = false,
     )
+    findall(
+        pattern::Vector{UInt8}
+        string::Vector{UInt8};
```
Comment (vtjnash) [inline base/regex.jl:449]:
```suggestion
        A::Vector{UInt8};
```

File: base/regex.jl [hunk 3]
```diff
@@ -486,6 +496,20 @@ function findall(t::Union{AbstractString,AbstractPattern}, s::AbstractString; ov
     return found
 end
 
+function findall(t::T, s::T; overlap::Bool=false) where {T <: Vector{UInt8}}
```
Comment (vtjnash) [inline base/regex.jl:499]: This prototype appears to normally be defined for:
```suggestion
function findall(t::Union{AbstractString, AbstractPattern, AbstractVector{<:Union{Int8,UInt8}}},
                 s::Union{AbstractString, AbstractPattern, AbstractVector{<:Union{Int8,UInt8}}},
                 ;
                 overlap::Bool=false)
```

which appears to me to avoid the need to copy the code.

If feasible, I think this may be good to move this to `strings/search.jl`, with the other similar cases (you may need to move `AbstractPattern` to the `strings/basic.jl` file too).

Comment (Moelf) [reply base/regex.jl:499]: In that case I'd make an internal function like _findall and only define the public one for type constraints?

I don't think I can fit both methods in one go right?

Comment (vtjnash) [reply base/regex.jl:499]: I don't see an obvious reason you'd need to do that (I might be misreading something though), but it could be useful (for code reuse). It seems the current pattern would be to name it `_asearch`

Comment (Moelf) [reply base/regex.jl:499]: I mean if I want to avoid duplicating the function body?
