### PR TITLE
fix jl_get_llvmf functionality for OrcJIT / MCJIT

### LINKED ISSUE #14592: code_native: "Unable to find function pointer"
I see this (Julia master):
```
julia> code_native(muladd, (Float64,Float64,Float64))
WARNING: Unable to find function pointer
```

However, this works:
```
julia> code_native(muladd, (Float32,Float32,Float32))
	.section	__TEXT,__text,regular,pure_instructions
	pushq	%rbp
	movq	%rsp, %rbp
	vfmadd213ss	%xmm2, %xmm1, %xmm0
	popq	%rbp
	retq
	nopl	(%rax,%rax)
```

This works as well:
```
julia> f(x,y,z) = muladd(x,y,z)
f (generic function with 1 method)

julia> code_native(f, (Float64,Float64,Float64))
	.section	__TEXT,__text,regular,pure_instructions
	pushq	%rbp
	movq	%rsp, %rbp
	vfmadd213sd	%xmm2, %xmm1, %xmm0
	popq	%rbp
	retq
	nopl	(%rax,%rax)
```

### PR DESCRIPTION
**Pull request by vtjnash**
fixes #14592

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -1324,88 +1322,78 @@ void *jl_get_llvmf(jl_function_t *f, jl_tupletype_t *tt, bool getwrapper, bool g
...
-#if defined(USE_ORCJIT) || defined(USE_MCJIT)
-    if (linfo->functionObjects.functionObject == NULL && linfo->functionObjects.specFunctionObject == NULL) {
-        jl_compile_linfo(linfo, NULL);
-    }
-    if (getdeclarations) {
-        JL_GC_POP();
-        if (getwrapper || linfo->functionObjects.specFunctionObject == NULL)
-            return linfo->functionObjects.functionObject;
+    if (!getdeclarations) {
+        Function *llvmDecl = nullptr;
```
Comment (tkelman) [inline src/codegen.cpp]: this needs some ifdefs to preserve the ability to build against llvm 3.3, which I think we should try to keep working for a little while

Comment (yuyichao) [inline src/codegen.cpp]: This probably need c++11 but does it need LLVM 3.7?

Comment (tkelman) [inline src/codegen.cpp]: the latter implies the former, but not the other way around. with gcc 4 and old llvm's llvm-config flags we can't assume c++11

Comment (yuyichao) [inline src/codegen.cpp]: What I mean is that since we are officially swithcing to LLVM 3.7.1 now, we can require a c++11 compiler. Keeping LLVM 3.3 support is useful to compare compiler regressions but not so much about keeping c++98 compatibility.

In any case replacing `nullptr` with `NULL` is a trivial way to fix this usage of `c++11` feature...

Comment (vtjnash) [inline src/codegen.cpp]: Using NULL would be good. I tested this against llvm-3.3, but I think clang doesn't complain while gcc would.
