### PR TITLE
Fix assume effects handling for gc_safe

### LINKED ISSUE #59552: `Base.@assume_effects :effect @ccall gc_safe=true call()::Ret` doesn't work
Bug:

```julia-repl
julia> Base.@assume_effects :nothrow @ccall gc_safe=true f()::Cvoid
ERROR: LoadError: MethodError: no method matching var"@ccall_effects"(::LineNumberNode, ::Module, ::UInt16, ::Expr, ::Expr)
The function `@ccall_effects` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  var"@ccall_effects"(::LineNumberNode, ::Module, ::UInt16, ::Any)
   @ Base c.jl:461

Stacktrace:
 [1] fl_lower
   @ ./flfrontend.jl:24 [inlined]
 [2] fl_lower(ex::Expr, mod::Module, filename::Ptr{UInt8}, lineno::UInt64)
   @ Base ./flfrontend.jl:23
in expression starting at REPL[4]:1
```

Workaround (at least I _think_ the behavior is identical):

```julia
Base.@assume_effects :nothrow let
    @ccall gc_safe=true f()::Cvoid
end
```

The `gc_safe` feature was introduced in PR #49933.

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes https://github.com/JuliaLang/julia/issues/59552

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
Did this land in time for 1.12?

**Comment by gbaraldi** [comment]
Yes

File: test/ccall.jl [hunk 1]
```diff
@@ -1970,14 +1970,15 @@ end
...
-    @ccall gc_safe=true jl_rand()::UInt64
+    Base.@assume_effects :nothrow @ccall gc_safe=true jl_rand()::UInt64
 end
 
 let llvm = sprint(code_llvm, gc_safe_ccall, ())
     # check that the call works
     @test gc_safe_ccall() isa UInt64
     # check for the gc_safe store
     @test occursin("store atomic i8 2", llvm)
+    @test Base.infer_effects(gc_safe_ccall, Tuple{}) == true
```
Comment (vchuravy) [inline test/ccall.jl]:
```
Error in testset ccall:
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XG3Q6T6R70.0/build/default-honeycrisp-XG3Q6T6R70-0/julialang/julia-master/julia-7bde44d5c7/share/julia/test/ccall.jl:1981
  Expression: Base.infer_effects(gc_safe_ccall, Tuple{}) == true
   Evaluated: (!c,!e,+n,!t,!s,!m,!u,+o,!r) == true
ERROR: LoadError: Test run finished with errors
```
