### PR TITLE
Fix Base.libllvm_path and jl_get_libllvm don't support non-ASCII characters in path on Windows (#45126)

### LINKED ISSUE #45126: Base.libllvm_path and jl_get_libllvm don't support non-ASCII characters in path on Windows
On Windows, if there are non-ASCII character in the path to LLVM--for example, if someone's name is non-English--then the function will not return the correct result. The function does not error, it just returns malformed UTF-8. However, this results in packages like LLVM.jl refusing to compile if the returned string is malformed UTF-8.

### PR DESCRIPTION
**Pull request by wesjenkins**
Fixes issue #45126, where Base.libllvm_path doesn't support non-ASCII characters. jl_get_libllvm_impl has been changed from using GetModuleFileNameA to using GetModuleFileNameW, along with WideCharToMultiByte to turn it into UTF-8.

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -8530,11 +8530,14 @@ extern "C" JL_DLLEXPORT jl_value_t *jl_get_libllvm_impl(void) JL_NOTSAFEPOINT
...
     if (!GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, (LPCSTR)&llvm::DebugFlag, &mod))
         return jl_nothing;
-
-    char path[MAX_PATH];
-    if (!GetModuleFileNameA(mod, path, sizeof(path)))
+    wchar_t path16[MAX_PATH];
+    DWORD n16 = GetModuleFileNameW(mod, path16, MAX_PATH);
+    if (n16 <= 0)
+        return jl_nothing;
+    char path8[MAX_PATH * 2];
```
Comment (vtjnash) [inline src/codegen.cpp:8537]: Why *2, not *3?

**Review by vtjnash — APPROVED** [review]

File: src/codegen.cpp [hunk 2]
```diff
@@ -8530,11 +8530,14 @@ extern "C" JL_DLLEXPORT jl_value_t *jl_get_libllvm_impl(void) JL_NOTSAFEPOINT
...
+    if (!WideCharToMultiByte(CP_UTF8, 0, path16, n16, path8, MAX_PATH * 2, NULL, NULL))
```
Comment (vtjnash) [inline src/codegen.cpp:8538]: Might need +1 to add a trailing null byte here?

Comment (wesjenkins) [reply src/codegen.cpp:8538]: Yeah, you're right, I need to fix the null, I'll do that.

File: src/codegen.cpp (hunk 1 above)
Comment (wesjenkins) [reply src/codegen.cpp:8537]: I can bump it up to 3 to be safe

**Comment by giordano** [comment]
Is this somehow related to #33486?

**Comment by zpcpi** [comment]
I still have similar problems
#48648

**Comment by vtjnash** [comment]
Sorry we forgot to merge this!

**Comment by vtjnash** [comment]
@KristofferC that is a rather awkward commit message, which seems to mention several changes that you squashed out of the final version
