### PR TITLE
raise maximum file descriptor limit.

### LINKED ISSUE #40891: Raise RLIMIT_NOFILE at startup
> nodejs/node@6820054 is how Node.js raises the file descriptor limit. Afterwards, soft limit == hard limit; there's no way for libuv retrieve the old soft limit again. Defaulting to 256 or 1024, depending on the platform, is the only way.

> FWIW, Node.js has been doing that for 8 years and I don't recall a single bug report. I recently added similar logic to Deno (denoland/deno@d46b37f), again to no ill effect. I suspect the select() bug with fds > 1023 is pretty much theoretical nowadays.

Refs https://github.com/libuv/libuv/issues/3181

### PR DESCRIPTION
**Pull request by ArunS-tack**
closes #40891 .

### CODE REVIEW

File: src/support/libsupportinit.c [hunk 1]
```diff
@@ -51,6 +52,35 @@ void libsupport_init(void)
...
+        } else {
+          min = rl.rlim_cur;
+        }
+      } while (min + 1 < max);
+    }
+  }
+  // Ignore SIGPIPE
+  RegisterSignalHandler(SIGPIPE, SIG_IGN);
+  RegisterSignalHandler(SIGINT, SignalExit);
+  RegisterSignalHandler(SIGTERM, SignalExit);
```
Comment (vtjnash) [inline src/support/libsupportinit.c:81]:
```suggestion
```

File: src/support/libsupportinit.c [hunk 2]
```diff
@@ -51,6 +52,31 @@ void libsupport_init(void)
     }
 }
 
+#ifdef __POSIX__
```
Comment (imciner2) [inline src/support/libsupportinit.c:55]:
```suggestion
#if defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE >= 200112L
```
Julia does not have the `__POSIX__` define to identify a POSIX system (it is non-standard and was used by the Node.js system because they defined it).

File: src/support/libsupportinit.c [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
 #include <locale.h>
 #include "libsupport.h"
+#include <sys/resource.h>
```
Comment (imciner2) [inline src/support/libsupportinit.c:5]: This should also be guarded by the test for posix compatibility.

File: src/support/libsupportinit.c [hunk 4]
```diff
@@ -51,6 +52,31 @@ void libsupport_init(void)
...
+      do {
+        rl.rlim_cur = min + (max - min) / 2;
+        if (setrlimit(RLIMIT_NOFILE, &rl)) {
+          max = rl.rlim_cur;
+        } else {
+          min = rl.rlim_cur;
+        }
+      } while (min + 1 < max);
+    }
+  }
```
Comment (imciner2) [inline src/support/libsupportinit.c:77]: This entire code block is outside a function, so when the correct define is used it causes a build error. I am guessing you meant for this to be included inside `libsupport_init` above?

**Review by imciner2 — CHANGES_REQUESTED** [review]

**Comment by imciner2** [comment]
Also, the Julia code formatting uses 4-space tabs, but the added code block uses 2-space tabs. It would be nice if you could update that when you make the changes.

File: src/support/libsupportinit.c (hunk 2 above)
Comment (ArunSanganal) [reply src/support/libsupportinit.c]: can i include ```#ifdef __POSIX__ ``` after I have defined it here ```#if defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE >= 200112L```?

**Comment by ArunSanganal** [comment]
@imciner2 can you review the PR now? Are there any further changes that need to be implemented?

**Comment by imciner2** [comment]
When I was testing this I noticed that I think the new code is in the wrong place in the function. It should probably go before the locale initialization code (so it is probably best placed on line 28). Right now the file descriptor limit won't be increased if the terminal is in the UTF8 locale already (since that part of the locale init function has a return in the if check it skips this code).

**Comment by ArunSanganal** [comment]
> When I was testing this I noticed that I think the new code is in the wrong place in the function. It should probably go before the locale initialization code (so it is probably best placed on line 28). Right now the file descriptor limit won't be increased if the terminal is in the UTF8 locale already (since that part of the locale init function has a return in the if check it skips this code).

I guess that makes sense. I will do the necessary.

**Comment by ArunSanganal** [comment]
How do you test if the descriptor has been increased or not?

**Comment by imciner2** [comment]
> How do you test if the descriptor has been increased or not?

On linux I can check the `/prod/PID/limits` file where `PID` is the PID for the Julia process. That file will show the limit for open files (both the soft and hard limits), so you can then check to make sure the soft limit was increased from its default (which for me is 1024).

**Comment by ArunSanganal** [comment]
> > How do you test if the descriptor has been increased or not?
> 
> On linux I can check the `/prod/PID/limits` file where `PID` is the PID for the Julia process. That file will show the limit for open files (both the soft and hard limits), so you can then check to make sure the soft limit was increased from its default (which for me is 1024).

How do you check that macOS?

**Comment by ArunSanganal** [comment]
@vtjnash any updates on this?

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
Thanks for the reminder, it had slipped my mind. I think this seems good. We have occasionally found resource leaks with the small default (which is why the default is small), but I think that would be a bad reason to not go with this.
