### PR TITLE
@lock export from Base, closes #36441

### LINKED ISSUE #36441: Can we export, document, and emphasize the `at-lock` macro?
For more context: https://discourse.julialang.org/t/poor-performance-of-lock-l-do-closures-caused-by-poor-performance-of-capturing-closures/42067/13

Base already provides a `@lock l expr` macro, which (as outlined in the above discourse thread) is often more performant than the related function form `lock(f, l)`.

https://github.com/JuliaLang/julia/blob/6c9bc51b80a626a656aeca9758556495c1676c2b/base/lock.jl#L178-L188

But this macro is not very discoverable, for at least these reasons, and is not widely used:
1. It's not currently exported, so not very discoverable:
    ```julia
    julia> @lock ReentrantLock() 2
    ERROR: LoadError: UndefVarError: @lock not defined
    in expression starting at REPL[1]:1
    ```
2. It's not mentioned in any of the docstrings for locks, so again not very discoverable
3. It doesn't have its own docstring, so not very discoverable
4. It seems like this should be preferred over the existing `lock(f, lock)`. Can we deprecate that in favor of this?

------

Can we export it, add docstrings for it, and maybe reference it from the other docstrings?

And/or maybe even emphasize that you should probably prefer this over the function form?

### PR DESCRIPTION
**Pull request by sairus7**

### CODE REVIEW

**Comment by ronisbr** [comment]
Hi @sairus7 

Thanks for this PR! IMHO, to truly close #36441 we need to do the following in addition to export `@lock`:

1. Add a docstring to this macro.
2. Add a small text in the documentation showing in which contexts it should be used.

For more information, you can see: https://discourse.julialang.org/t/poor-performance-of-lock-l-do-closures-caused-by-poor-performance-of-capturing-closures/42067/13

**Comment by vtjnash** [comment]
bump? needs docs and news for this

**Comment by sairus7** [comment]
@ronisbr I've added docstrings and `@lock_nofail` export. 
Does it cover 1 and 2, or should I seach for some other places in documentation to add a mention about these macro? If so, can you point me to it?

**Comment by ronisbr** [comment]
Hi @sairus7 !

For me it is perfect and fully addressed my points 1 and 2. I think we only need to add an entry in NEWS.md informing that `@lock` and `@lock_nofail` is now exported.

**Review by ronisbr — APPROVED** [review]

**Comment by sairus7** [comment]
> add an entry in NEWS.md informing that `@lock` and `@lock_nofail` is now exported

Seems NEWS.md file is excluded from julia repo, so how to do this?

**Comment by ronisbr** [comment]
> Seems NEWS.md file is excluded from julia repo, so how to do this?

No, it does not seem to be excluded, check here:

https://github.com/JuliaLang/julia/blob/master/NEWS.md

**Comment by sairus7** [comment]
Added this to news, not sure if the right section.

**Comment by ronisbr** [comment]
LGTM!

**Review by ronisbr — APPROVED** [review]

**Comment by ronisbr** [comment]
@sairus7 

We have a problem in the building:

```
base/lock.jl:208:`lock(l)` and `unlock(l)` functions. It is often more performant than function form 
base/lock.jl:227:Equivalent to `@lock l expr` for cases in which we can guarantee that the function 
Error: trailing whitespace found in source file(s)
```

I believe you need to remove trailing spaces from those doc strings.

File: base/lock.jl [hunk 1]
```diff
@@ -201,6 +201,14 @@ function trylock(f, l::AbstractLock)
     return false
 end
 
+"""
+    @lock l expr
+
+Macro version for `lock(f, l::AbstractLock)`. It wraps an arbitrary `expr` with a pair of
+`lock(l)` and `unlock(l)` functions. It is often more performant than function form
+`lock(f, l)`, because it don't capture variables into a lambda.
+See [`lock`](@ref).
```
Comment (fredrikekre) [inline base/lock.jl:210]: Perhaps something like this? Just a suggestion, but since the expansion is pretty short I think it is nice to show that no "magic" is happening under the hood.
````suggestion
Lock the lock `l`, evaluate `expr` inside [`try`](@ref), and unlock `l`. Expands to:
```julia
lock(l)
try
    expr
finally
    unlock(l)
end
```
This is similar to using [`lock`](@ref) with a `do` block:
```julia
lock(l) do
    expr
end
```
but avoids creating a closure.
````

File: base/exports.jl [hunk 2]
```diff
@@ -675,6 +675,8 @@ export
     istaskstarted,
     istaskfailed,
     lock,
+    @lock,
+    @lock_nofail,
```
Comment (fredrikekre) [inline base/exports.jl:679]: Should this really be exported? It feels very internal, and you don't really gain much from using it. Compare e.g.
```julia
lock(l)
do_stuff()
more_stuff()
unlock(l)
```
with
```julia
@lock_nofail l begin
    do_stuff()
    more_stuff()
end
```
Same number of lines, and the former is much more readable since it doesn't hide things.

Comment (sairus7) [reply base/exports.jl:679]: Why is this internal?
This is simplification and performance improvement for external functionality, see issue and discussion attached.

Comment (sairus7) [reply base/exports.jl:679]: I think this is the case for comparison:
```julia
lock(l) do
    do_stuff()
    more_stuff()
end
```

```julia
@lock l begin
    do_stuff()
    more_stuff()
end
```

The second is more performant than the first. 

But, if you think that it is redundant, then maybe the first form with lambda should be deprecated as well?

Comment (ronisbr) [reply base/exports.jl:679]: IMHO, we should export both. In this case, one can start to develop using `@lock` and for parts that we can ensure in a latter development stage that no exception will be thrown, we just add `_nofail` without changing anything.

Comment (sairus7) [reply base/exports.jl:679]: Also, `@lock` hides try-catch that can be a common pattern to use it, so why should we repeat it everytime?

Comment (ronisbr) [reply base/exports.jl:679]: I think @fredrikekre's comment is about `@lock_nofail` only.

Comment (ronisbr) [reply base/exports.jl:679]: Side note: `@lock_nofail` is not a good name IMHO. It can be mistaken to "a lock that will never fail" instead of "a lock of a function that must never fail". Perhaps `@lock_unsafe` is a better option, but this is a discussion for another time I think.

File: base/lock.jl (hunk 1 above)
Comment (sairus7) [reply base/lock.jl:210]: Lock the lock `l`, evaluate `expr` inside [`try`](@ref), and unlock `l`.
The same docstring is just above this one, for a `lock` function. So maybe we should just reference to it and add only `delta` docstring?

File: base/exports.jl (hunk 2 above)
Comment (sairus7) [reply base/exports.jl:679]: Ok, I will remove `@lock_nofail` from export

Comment (sairus7) [reply base/exports.jl:679]: Should I?)

Comment (ronisbr) [reply base/exports.jl:679]: I do not know. Let's wait @fredrikekre . I think it should be exported as well.

Comment (sairus7) [reply base/exports.jl:679]: Now I remember Jeff Bezanson talk about "too many ways for doing the same thing".

File: base/lock.jl (hunk 1 above)
Comment (sairus7) [reply base/lock.jl:210]: Should we provide examples of expanded macro? I didn't see any of that in docs before with any other macro.

File: base/exports.jl (hunk 2 above)
Comment (fredrikekre) [reply base/exports.jl:679]: I was indeed talking about `@lock_nofail`. I just don't see the point of it when it doesn't really save you much typing.

`@lock` is different since the macro expands to more boiler plate code with the `try`/`finally` etc.

We can see what other people think too, but perhaps in the interest of getting this PR merged it might make sense to split it into another PR.

File: base/lock.jl (hunk 1 above)
Comment (fredrikekre) [reply base/lock.jl:210]: I just thought it was short enough that it could be included, and including it is by far the easiest way to explain what is happening IMO but the full `lock`-`do` example might not be needed. Perhaps like this?

````suggestion
Lock the lock `l`, evaluate `expr` inside [`try`](@ref), and unlock `l`. Expands to:
```julia
lock(l)
try
    expr
finally
    unlock(l)
end
```
This is similar to using [`lock`](@ref) with a `do` block but avoids creating a closure.
````

Comment (sairus7) [reply base/lock.jl]: How about just sending user to `lock` docs? From next commit:
```julia
"""
Macro version for `lock(f, l::AbstractLock)`, but with `expr` instead of `f` function.
This is similar to using [`lock`](@ref) with a `do` block, but avoids creating a closure
and thus can improve the performance.
"""
```

File: base/exports.jl (hunk 2 above)
Comment (sairus7) [reply base/exports.jl]: Ok, removed `@lock_nofail` from exports. This is another story now.

File: base/lock.jl (hunk 1 above)
Comment (fredrikekre) [reply base/lock.jl]: What's wrong with including the expansion in the docstring? Then it becomes self-explanatory. I don't understand what "macro version of lock" means.

Comment (sairus7) [reply base/lock.jl]: Just never seen code expansion in other macro docstrings, so I thought that `macroexpand` should be used for this.
I have included the expansion now. Should I also change "macro version of lock"? For example, to this: "Equivalent to lock but ..."

**Comment by sairus7** [comment]
I think all conversations above are resolved now.

**Comment by NHDaly** [comment]
Fantastic, thanks all! :) 🙌

**Comment by ronisbr** [comment]
Nice!! Thank you @sairus7 for you contribution :)
