### PR TITLE
REPLCompletions: Add completions for var"" identifiers

### LINKED ISSUE #49280: Tab completion doesn't work correctly for var"" symbols
Hmmm, playing around with this a bit, I did notice that unusual symbol names (such as those that might require use of `var""` to access them) can confuse the tab autocompletion, since the `var""` syntax looks like a string, and so it starts to auto-suggest filenames, rather than symbol names:

```
julia> struct WeirdNames
       end
       Base.propertynames(::WeirdNames) = (Symbol("oh no!"), Symbol("oh yes!"))

julia> WeirdNames().var"oh 
.buildkite-external-version  .clang-format                .clangd                      .codecov.yml                 .devcontainer/               .git-blame-ignore-revs
.git/                        .gitattributes               .github/                     .gitignore                   .mailmap                     CITATION.bib
CITATION.cff                 CONTRIBUTING.md              HISTORY.md                   LICENSE.md                   Make.inc                     Makefile
NEWS.md                      README.md                    THIRDPARTY.md                VERSION                      base/                        cli/
contrib/                     deps/                        doc/                         etc/                         julia                        julia.spdx.json
pkgimage.mk                  src/                         stdlib/                      sysimage.mk                  test/                        usr-staging/
usr/
```

_Originally posted by @staticfloat in https://github.com/JuliaLang/julia/issues/49206#issuecomment-1492347255_

### PR DESCRIPTION
**Pull request by Keno**
Fixes #49280. Mostly just moving code around, but there's one extra place where we're pattern matching var"". I do hope that after the future parser replacement, we can do these things on the in-progress AST rather than textually.

### CODE REVIEW

File: stdlib/REPL/test/replcompletions.jl [hunk 1]
```diff
@@ -1801,3 +1807,27 @@ let s = "pop!(global_xs)."
...
+# Test completion of non-Expr literals
+let s = "\"abc\"."
+    c, r = test_complete(s)
+    # (no completion, but shouldn't error)
+    @test isempty(c)
+end
+
+let s = "`abc`.e"
+    c, r = test_complete(s)
+    # (no completion, but shouldn't error)
```
Comment (aviatesk) [inline stdlib/REPL/test/replcompletions.jl:1831]:
```suggestion
    # (completions for the fields of `Cmd`)
```

File: stdlib/REPL/test/replcompletions.jl [hunk 2]
```diff
@@ -132,6 +132,12 @@ let ex = quote
         macro testcmd_cmd(s) end
         macro tϵsτcmδ_cmd(s) end
 
+        var"complicated symbol with spaces" = 5
+
+        struct WeirdNames
+        end
```
Comment (aviatesk) [inline stdlib/REPL/test/replcompletions.jl:138]:
```suggestion
        struct WeirdNames end
```

**Review by aviatesk — APPROVED** [review]

File: stdlib/REPL/test/replcompletions.jl (hunk 1 above)
Comment (Keno) [reply stdlib/REPL/test/replcompletions.jl]: thanks
