### PR TITLE
canonicalize Windows environment variables to uppercase

### LINKED ISSUE #29334: environment vars on Windows should be case-insensitive
Disclaimer: I don't personally use Windows and I inferred this behavior only through appveyor. So maybe I'm missing some points here.

Anyway, how do you update `PATH` to be used for `setenv(command::Cmd, env)` on Windows?  For example, if I do

```julia
env_var = copy(ENV)
env_var["PATH"] = "some_new_path" * ';' * env_var["PATH"]
setenv(command::Cmd, env_var)
```

it doesn't work since the original PATH is in `env_var["Path"]` not `env_var["PATH"]`.  I had to [implement](https://github.com/JuliaPy/Conda.jl/blob/dfdfa387ab3a8d98bf038bf2ccbde3641db5c870/src/Conda.jl#L118-L121) something like this (https://github.com/JuliaPy/Conda.jl/pull/121#discussion_r219715161):

```julia
env_var = copy(ENV)
all_keys = collect(keys(env_var))
ikey = findfirst(x -> uppercase(x) == "PATH", all_keys)
has_key = ikey !== nothing
path_key = has_key ? all_keys[ikey] : "PATH"
if has_key
    env_var[path_key] = extra_path * path_sep * env_var[path_key]
else
    env_var[path_key] = extra_path
end
```

I tried `empty!(ENV); merge!(ENV, env_var)` but apparently `empty!(ENV)` is not implemented (at least on Linux).  Also, it would have emitted bunch of syscalls so maybe not a good idea in the first place.

So, I thought maybe `Base` needs to have a case-insensitive (in-memory) dictionary and `copy(ENV)` on Windows should return it.  It also facilitates cross-platform testing.

cc: @stevengj

### PR DESCRIPTION
**Pull request by stevengj**
This PR mostly fixes #29334 by canonicalizing Windows environment variables (which are case-insensitive case-preserving) to uppercase when they are iterated, copied, etcetera.

Otherwise it is easy to write buggy code for Windows by following our [`setenv` documentation](https://github.com/JuliaLang/julia/blob/a153feaa0b167520d6e42d1aa03d224ec0064a7c/base/process.jl#L226), e.g.
```jl
env = copy(ENV)
env["PATH"] = ....   # incorrect if PATH was capitalized as Path!
setenv(`some command`, env)
```
For example, I found code "in the wild" that does problematic things like this in [Conda.jl](https://github.com/JuliaPy/Conda.jl/blob/4725842e6985ec3c8def8da0ebd5f42a9d27fcae/src/Conda.jl#L95-L98), [BinDeps.jl](https://github.com/JuliaPackaging/BinDeps.jl/blob/master/src/dependencies.jl#L216-L217), [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl/blob/e7709648f122284318a63cf9914d6eef95300825/src/Documenter.jl#L759-L760), the [REPL](https://github.com/JuliaLang/julia/blob/a153feaa0b167520d6e42d1aa03d224ec0064a7c/stdlib/REPL/test/repl.jl#L733-L734), and [`Base.runtests`](https://github.com/JuliaLang/julia/blob/a153feaa0b167520d6e42d1aa03d224ec0064a7c/base/util.jl#L816-L817) — all of these examples don't take into account the case-insensitivity of Windows environment variables, and all should be fixed by this PR.

It still doesn't throw if the user explicitly writes something like `merge!(ENV, Dict("key" => "1", "KEY" => "2"))`, but that could be addressed in a separate PR … that seems like a much less pressing problem to me.

### CODE REVIEW

File: base/env.jl [hunk 1]
```diff
@@ -100,7 +100,7 @@ if Sys.iswindows()
         if m === nothing
             error("malformed environment entry: $env")
         end
-        return (Pair{String,String}(m.captures[1], m.captures[2]), (pos+(len+1)*2, blk))
+        return (Pair{String,String}(uppercase(m.captures[1]), m.captures[2]), (pos+(len+1)*2, blk))
```
Comment (vtjnash) [inline base/env.jl]: Should be `ASCII.uppercase` (do we have such a thing?)

**Comment by vtjnash** [comment]
Aside: I noticed the design here has a resource leak here for `GetEnvironmentStringsW` in some cases. We should probably eagerly copy the environment to an array so that we can call `FreeEnvironmentStrings` correctly

File: base/env.jl (hunk 1 above)
Comment (stevengj) [reply base/env.jl]: I just checked, and Windows is also case-insensitive for Unicode characters, e.g. [U+00ee](http://www.fileformat.info/info/unicode/char/00EE/index.htm) vs. [U+00ce](http://www.fileformat.info/info/unicode/char/00CE/index.htm), so arguably we should uppercase those as well.

Comment (vtjnash) [reply base/env.jl]: Actually, I take that back, I have no idea what table is used by windows (I'm guessing that it isn't well-defined or stable or consistent)

libuv uses `LCMapStringW(LOCALE_INVARIANT, LCMAP_UPPERCASE)`
MS doesn't really say how the comparison is done: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlcompareunicodestring

Comment (stevengj) [reply base/env.jl]: Okay, updated to use `LCMapStringW`.

**Comment by stevengj** [comment]
Hooray, green CI!

**Comment by stevengj** [comment]
I think this qualifies as a minor change — almost any code that this could break was buggy anyway.

For example, the following code would now break:
```jl
ENV["foo"]="bar"
env = copy(ENV)
env["foo"] # now fails because the key is called "FOO"
```
but this code was buggy — it would fail anyway if there were already an environment variable `"Foo"` or `"FOO"` etc.

In practice, I looked over the existing packages that call `copy(ENV)` and it doesn't look like any of them will be broken by this change, and in fact nearly all of them are buggy without this change.

**Comment by stevengj** [comment]
@vtjnash, can we leave fixing the potential resource leak (for when you don't finish the iterator) for another PR, since that is an unrelated issue?  Or do you want me to fix it here?

**Comment by vtjnash** [comment]
Later PR

**Comment by stevengj** [comment]
@StefanKarpinski, do you have any opinion on this?  It's a slightly tricky case for compatibility vs correctness.

**Comment by StefanKarpinski** [comment]
I think it seems like a good idea and you have gone to admirable lengths to make it correct (i.e. using Windows own case tables) instead of almost correct (using our own case tables). Seems good for a minor release to me.

**Comment by stevengj** [comment]
Added NEWS and documentation as suggested, thanks.

**Review by vtjnash — APPROVED** [review]

**Comment by stevengj** [comment]
CI failures are an unrelated Travis glitch (and everything was green before the latest commit, which just updated documentation).

I think this should be good to merge.

**Comment by vtjnash** [comment]
Tried to kick them (travis failed to start the jobs), although still gtg whenever you want to merge from my perspective.

**Comment by StefanKarpinski** [comment]
> (On Windows, system environment variables are case-insensitive, and `ENV` correspondingly converts	all keys to uppercase for display, iteration, and copying.  Portable code should not rely on the	existence of lower-case environment variables or on the ability to distinguish variables by case.)

Since this is what we're recommending, wouldn't it make sense to just convert `ENV` keys to uppercase on Windows on insertion and lookup as well? Or is that effectively what happens already? In that case shouldn't we delete the "on the	existence of lower-case environment variables" part since it's impossible to rely on that on Windows?

**Comment by stevengj** [comment]
> Since this is what we're recommending, wouldn't it make sense to just convert ENV keys to uppercase on Windows on insertion and lookup as well? Or is that effectively what happens already?

`ENV[key]` access is already case-insensitive.  However, I don't think we should explicitly convert keys to uppercase in `getenv`/`setenv`, because:

* `ENV` access is case-preserving, so even we convert all keys to uppercase, `ENV["FOO"]="bar"` could still result in a lower-case `"foo"` variable if `"foo"` was already defined.  (Unless you propose that every `setenv` call first deletes any existing environment variable, which I don't think we should do.)

* If for some obscure reason you need to set a lowercase environment variable (e.g. a subprocess checks the case for some reason), I'd hate to lose that ability entirely.

> In that case shouldn't we delete the "on the	existence of lower-case environment variables" part since it's impossible to rely on that on Windows?

I'm not sure what you mean?  It already says that portable code should *not* rely on lower case being preserved.

**Comment by stevengj** [comment]
Stefan, relying on lower case being preserved was and is a problem if you make a copy of ENV, as described above: https://github.com/JuliaLang/julia/pull/30593#issuecomment-451693383

**Comment by stevengj** [comment]
How about rephrasing it as:

> (On Windows, system environment variables are case-insensitive, and ENV correspondingly converts all keys to uppercase for display, iteration, and copying. Portable code should not rely on the ability to distinguish variables by case, and should beware that setting an ostensibly lowercase variable may result in an uppercase `ENV` key.)

**Comment by StefanKarpinski** [comment]
That does clarify it.
