### PR TITLE
REPL: add OSC 52 clipboard fallback and graceful degradation

### LINKED ISSUE #60145: REPL search save-to-clipboard feature needs better errors
Hitting Ctrl-S in the REPL search and hitting clipboard can give:
```
┌ Error: Error in the keymap
│   exception =
│    TaskFailedException
│    Stacktrace:
│      [1] #wait#580
│        @ ./task.jl:363 [inlined]
│      [2] wait
│        @ ./task.jl:360 [inlined]
│      [3] fetch
│        @ ./task.jl:554 [inlined]
│      [4] runsearch(histfile::REPL.History.HistoryFile, term::Base.Terminals.TTYTerminal, prefix::String)
│        @ REPL.History ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:18
│      [5] histsearch(::REPL.History.HistoryFile, ::Vararg{Any})
│        @ REPL ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/REPL.jl:105
│      [6] history_search(mistate::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2718
│      [7] (::REPL.LineEdit.var"#247#248")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2685
│      [8] (::REPL.LineEdit.var"#match_input##0#match_input##1"{REPL.LineEdit.var"#247#248", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:1857
│      [9] macro expansion
│        @ ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2996 [inlined]
│     [10] macro expansion
│        @ ./lock.jl:376 [inlined]
│     [11] (::REPL.LineEdit.var"#prompt!##2#prompt!##3"{Base.Terminals.TTYTerminal, REPL.LineEdit.ModalInterface, REPL.LineEdit.MIState, REPL.LineEdit.Prompt})()
│        @ REPL.LineEdit ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2985
│    
│        nested task error: no clipboard command found, please install xsel or xclip or wl-clipboard
│        Stacktrace:
│         [1] error
│           @ ./error.jl:44
│         [2] clipboardcmd()
│           @ InteractiveUtils ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/InteractiveUtils/src/clipboard.jl:62
│         [3] clipboard(x::SubString{String})
│           @ InteractiveUtils ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/InteractiveUtils/src/clipboard.jl:65
│         [4] saveclipboard(msgio::Base.TTY, content::SubString{String})
│           @ REPL.History ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:385
│         [5] run_display!(::@NamedTuple{term::Base.Terminals.TTYTerminal, prompt::REPL.LineEdit.Prompt, istate::REPL.LineEdit.MIState, pstate::REPL.LineEdit.PromptState}, events::Channel{Symbol}, hist::Vector{REPL.History.HistEntry})
│           @ REPL.History ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:180
│         [6] (::REPL.History.var"#runsearch##2#runsearch##3"{REPL.History.HistoryFile, @NamedTuple{term::Base.Terminals.TTYTerminal, prompt::REPL.LineEdit.Prompt, istate::REPL.LineEdit.MIState, pstate::REPL.LineEdit.PromptState}, Channel{Symbol}})()
│           @ REPL.History ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/History/search.jl:16
└ @ REPL.LineEdit ~/julia-loadingfix/usr/share/julia/stdlib/v1.14/REPL/src/LineEdit.jl:2998
```
This is not an exceptional situation and should print a friendly error inline or disable the clipboard option (with an explanation).

### PR DESCRIPTION
**Pull request by Keno**
When pressing Ctrl-S → Clipboard in REPL history search on a system without clipboard tools (xsel, xclip, wl-clipboard), a TaskFailedException stack trace was thrown. This adds:

- `OncePerId{T}`: a new callable struct that caches `initializer(key)` per mutable key object via WeakKeyDict, for general-purpose per-object caching
- `has_system_clipboard()` in InteractiveUtils to detect native clipboard availability per platform
- OSC 52 terminal clipboard support as a fallback, with proper DA1 (Primary Device Attributes) query to detect terminal capability
- Graceful degradation: when neither clipboard mechanism is available, the Clipboard option is skipped and a friendly message is shown instead of a stack trace

Fixes #60145

### CODE REVIEW

File: stdlib/REPL/src/History/search.jl [hunk 1]
```diff
@@ -375,14 +375,86 @@ function savefile(term::Base.Terminals.TTYTerminal, content::AbstractString)
...
 """
-function saveclipboard(msgio::IO, content::AbstractString)
+function saveclipboard(term::Base.Terminals.TTYTerminal, content::AbstractString)
+    out = term.out_stream
     nlines = count('\n', content) + 1
-    clipboard(content)
-    println(msgio, S"\e[1G\e[2K{grey,bold:history>} {shadow:Copied $nlines \
+    if InteractiveUtils.has_system_clipboard()
+        InteractiveUtils.clipboard(content)
+    elseif _can_osc52(term)
```
Comment (Keno) [inline stdlib/REPL/src/History/search.jl]: Should probably prefer OSC 52 over system clipboard command.

File: stdlib/REPL/src/History/search.jl [hunk 2]
```diff
@@ -375,14 +375,86 @@ function savefile(term::Base.Terminals.TTYTerminal, content::AbstractString)
...
+"""
+    _query_da1_osc52(term::Base.Terminals.TTYTerminal) -> Bool
+
+Send a DA1 (Primary Device Attributes) query (`\\e[c`) and check whether the
+terminal advertises feature `52` (OSC 52 clipboard) in its response.
+Returns `false` on timeout or if the streams are not TTYs.
+
+See neovim/neovim#34472 for background on using DA1 rather than `XTGETTCAP`.
+"""
+function _query_da1_osc52(term::Base.Terminals.TTYTerminal)
```
Comment (Keno) [inline stdlib/REPL/src/History/search.jl]: This doesn't seem to be working. iTerm2 3.6.6 reports this in DA1, but this doesn't pick it up. I'm also concerned that this may be fighting with the REPL over the input stream. Perhaps a better way to handle this would be to teach the REPL to interpret these escape sequences when they come in.

File: stdlib/REPL/src/History/search.jl (hunk 1 above)
Comment (tecosaur) [reply stdlib/REPL/src/History/search.jl]: Using OSC 52 when possible seems like it would also help with copying over SSH.

File: stdlib/REPL/src/History/search.jl [hunk 3]
```diff
@@ -375,14 +375,86 @@ function savefile(term::Base.Terminals.TTYTerminal, content::AbstractString)
...
+    inp = term.in_stream
+    (out isa Base.TTY && inp isa Base.TTY) || return false
+    # Send DA1 query
+    write(out, "\e[c")
+    # Read response byte-by-byte with 600 ms timeout.
+    # DA1 response format: \e[?<param1>;<param2>;...;<paramN>c
+    buf = UInt8[]
+    deadline = time() + 0.6
+    while time() < deadline
+        if bytesavailable(inp) > 0
```
Comment (Keno) [inline stdlib/REPL/src/History/search.jl]: Don't work if we're not reading stdin currently and can also swallow other stdin input depending on delays. May not be a huge issue here, but I think this again speaks to handling this in the keymap.

File: stdlib/REPL/src/History/search.jl (hunk 1 above)
Comment (Keno) [reply stdlib/REPL/src/History/search.jl]: yes

File: stdlib/REPL/src/History/search.jl (hunk 2 above)
Comment (tecosaur) [reply stdlib/REPL/src/History/search.jl]: I've struggled with this for a while, you can see a similar approach I took a while ago with colour detection in https://code.tecosaur.net/tec/DoomThemes.jl/src/branch/main/src/termtheme.jl#L42-L66, but I was never able to get beyond "mostly working".

Having chatted to Jameson about this, it's not really possible to do what other C-ish terminal queries do with attempted reads with a timeout.

Following that discussion, the approach I've landed on is asynchronously making the queries on startup. See: #59958

File: base/weakkeydict.jl [hunk 4]
```diff
@@ -212,3 +212,53 @@ end
...
+    const cache::WeakKeyDict{Any, T}
+    const initializer::F
+
+    OncePerId{T}(initializer::F) where {T, F} = new{T,F}(WeakKeyDict{Any, T}(), initializer)
+    OncePerId{T,F}(initializer::F) where {T, F} = new{T,F}(WeakKeyDict{Any, T}(), initializer)
+    function OncePerId(initializer)
+        T = Base.promote_op(initializer, Any)
+        new{T, typeof(initializer)}(WeakKeyDict{Any, T}(), initializer)
+    end
+end
```
Comment (tecosaur) [inline base/weakkeydict.jl]: Is this PR really the appropriate place to introduce `OncePerId`?

File: stdlib/REPL/src/History/search.jl (hunk 2 above)
Comment (Keno) [reply stdlib/REPL/src/History/search.jl]: Yes, upon further consideration, I think the appropriate thing to do is to put it in the keymap and just treat that as key event.

File: base/weakkeydict.jl (hunk 4 above)
Comment (Keno) [reply base/weakkeydict.jl]: Meh, it's a small abstraction that just adapts WeakKeyDict to what the caches look like these days, but we won't need it anyway if we're using the other approach, so moot for now.

**Comment by Keno** [comment]
Rebased on top of #61181. Seems to work well.
