### PR TITLE
fix trailing indices stackoverflow in reinterpreted array

### LINKED ISSUE #54623: reintepret reshape of 0-dimensional array
I installed Julia with the command `curl -fsSL https://install.julialang.org | sh`. I couldn't find anyone else talking about this specific issue anywhere I looked, but I apologize if I just missed it. There seems to be a problem displaying `reinterpret`ed/`reshape`ed 0-dimensional arrays. Despite the fact that the elements of this array are `Int64`s, they are shown as 0-dimensional arrays of `Int64`s with unrelated contents. The setup is shown below.
```julia
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 10 default, 0 interactive, 5 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = 10

julia> r = reinterpret(reshape, Int, fill(1 => 2))
2-element reinterpret(reshape, Int64, ::Array{Pair{Int64, Int64}, 0}) with eltype Int64:
 fill(4538293232)
 fill(4539746992)

julia> r[1], r[2], collect(r)
(1, 2, [1, 2])

julia> typeof(r)
Base.ReinterpretArray{Int64, 1, Pair{Int64, Int64}, Array{Pair{Int64, Int64}, 0}, true}

julia> typeof(fill(4538293232))
Array{Int64, 0}

julia> eltype(r)
Int64
```

### LINKED ISSUE #57170: Extra 1 dimensions in reinterpreted arrays cause stack overflow
Hi, thanks for everyone's work on Julia!

Following the manual on arrays, one can add extra "1" in indexing Nd arrays.
This works as expected for `Array` but creates a Stack Overflow with `ReinterpretArray` on 1.10, last release and nightly.
```julia
X = rand(Float32, (2,5))
X[1, :, 1] # works as expected

X2 = rand(ComplexF32, 5)
Xr = reinterpret(reshape, Float32, X2)
Xr[1, :, 1] # Stack overflow
```

The stack overflow error:
```
[1] _getindex(::Base.IndexSCartesian2{2}, ::Base.ReinterpretArray{Float32, 2, ComplexF32, Vector{ComplexF32}, true}, ::Int64, ::Int64, ::Vararg{Int64})
@ Base ./multidimensional.jl:953
[2] getindex(::Base.ReinterpretArray{Float32, 2, ComplexF32, Vector{ComplexF32}, true}, ::Int64, ::Int64, ::Int64)
 @ Base ./abstractarray.jl:1342
 [3] macro expansion
@ ./multidimensional.jl:979 [inlined]
[4] macro expansion
@ ./cartesian.jl:64 [inlined]
[5] macro expansion
@ ./multidimensional.jl:977 [inlined]
[6] _unsafe_getindex!
@ ./multidimensional.jl:987 [inlined]
[7] _unsafe_getindex(::Base.IndexSCartesian2{2}, ::Base.ReinterpretArray{Float32, 2, ComplexF32, Vector{ComplexF32}, true}, ::Int64, ::Int64, ::Int64)
 @ Base ./multidimensional.jl:968
 [8] _getindex(::Base.IndexSCartesian2{2}, ::Base.ReinterpretArray{Float32, 2, ComplexF32, Vector{ComplexF32}, true}, ::Int64, ::Int64, ::Vararg{Int64})
@ Base ./multidimensional.jl:954
--- the above 7 lines are repeated 11134 more times ---
 [77947] getindex
 @ ./abstractarray.jl:1342 [inlined]
[77948] macro expansion
@ ./multidimensional.jl:979 [inlined]
[77949] macro expansion
@ ./cartesian.jl:64 [inlined]
[77950] macro expansion
@ ./multidimensional.jl:977 [inlined]
[77951] _unsafe_getindex!
@ ./multidimensional.jl:987 [inlined]
[77952] _unsafe_getindex
 @ ./multidimensional.jl:968 [inlined]
[77953] _getindex
@ ./multidimensional.jl:954 [inlined]
[77954] getindex(::Base.ReinterpretArray{Float32, 2, ComplexF32, Vector{ComplexF32}, true}, ::UnitRange{Int64}, ::Function, ::Int64)
 @ Base ./abstractarray.jl:1342
```

### PR DESCRIPTION
**Pull request by adienes**
would fix https://github.com/JuliaLang/julia/issues/57170, fix https://github.com/JuliaLang/julia/issues/54623

@nanosoldier `runbenchmarks("array", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/58293) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4856b67_vs_748775b/report.md).

**Comment by adienes** [comment]
I think it's all noise, which makes sense, since this adds a method that didn't exist before. I just wanted to check it didn't somehow accidentally hijack some call that would otherwise hit a generic fallback, and with negative performance implications

File: base/reinterpretarray.jl [hunk 1]
```diff
@@ -314,11 +314,11 @@ end
 _maybe_reshape(::IndexSCartesian2, A::ReshapedReinterpretArray, I...) = A
 
 # fallbacks
-function _getindex(::IndexSCartesian2, A::AbstractArray{T,N}, I::Vararg{Int, N}) where {T,N}
+function _getindex(::IndexSCartesian2, A::AbstractArray{T,N}, I::Int...) where {T,N}
```
Comment (N5N3) [inline base/reinterpretarray.jl]: It looks simpler to fuse the index transformation for IndexCartesian.
```julia
# fallbacks
function _getindex(::IndexSCartesian2, A::AbstractArray, I::Vararg{Int, N}) where {N}
    @_propagate_inbounds_meta
    _getindex(IndexCartesian(), A, I...)
end
function _setindex!(::IndexSCartesian2, A::AbstractArray, v, I::Vararg{Int, N}) where {N}
    @_propagate_inbounds_meta
    _setindex!(IndexCartesian(), A, v, I...)
end
```
And we can get rid of the change on L400/546

Comment (adienes) [reply base/reinterpretarray.jl]: I'm not sure I understand --- as I'm currently interpreting the suggestion it seems to break
`reinterpret(reshape, Int, [(1,2,3), (4,5,6)])[CartesianIndex(1,2)]`

Comment (N5N3) [reply base/reinterpretarray.jl]: Well, all test passed with a clean build of master + 243acf270e68df0daf65bcf18a9146c116c6b5a1
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.13.0-DEV.797 (2025-07-02)
 _/ |\__'_|_|_|\__'_|  |  IndexSCartesian2/243acf270e (fork: 1 commits, 0 days)
|__/                   |

julia> reinterpret(reshape, Int, [(1,2,3), (4,5,6)])[CartesianIndex(1,2)]
4

julia> using Test

julia> let a = rand(ComplexF32, 5)
           r = reinterpret(reshape, Float32, a)
           ref = Array(r)

           @test r[1, :, 1]        == ref[1, :]
           @test r[1, :, 1, 1, 1]  == ref[1, :]
           @test r[1, :, UInt8(1)] == ref[1, :]

           r[2, :, 1] .= 0f0
           ref[2,  :] .= 0f0
           @test r[2, :, 1] == ref[2, :]

           @test r[4] == ref[4]
           @test_throws BoundsError r[1, :, 2]
       end
Test Passed
      Thrown: BoundsError

julia> @testset "issue #54623" begin
           x = 0xabcdef01234567
           @test reinterpret(reshape, UInt8, fill(x)) == [0x67, 0x45, 0x23, 0x01, 0xef, 0xcd, 0xab, 0x00]
           @test reinterpret(reshape, UInt8, [x]) == [0x67; 0x45; 0x23; 0x01; 0xef; 0xcd; 0xab; 0x00;;]
       end
Test Summary: | Pass  Total  Time
issue #54623  |    2      2  0.7s
Test.DefaultTestSet("issue #54623", Any[], 2, false, false, true, 1.751465561164e9, 1.751465561857e9, false, "REPL[4]", Random.Xoshiro(0x95ed4d976c673035, 0xca8373fdf45b5562, 0x0a3f6ee6a24417ca, 0xaacc2a1d0e39feda, 0xd449faddd8639f43))

julia> versioninfo()
Julia Version 1.13.0-DEV.797
Commit 243acf270e (2025-07-02 13:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-12650H
  WORD_SIZE: 64
  LLVM: libLLVM-20.1.2 (ORCJIT, alderlake)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)
```

Comment (adienes) [reply base/reinterpretarray.jl]: ahh ok sounds good I had missed the need to remove the `{T, N}` parameters from `::AbstractArray`
