### PR TITLE
JuliaSyntax: fix anonymous function parsing

### LINKED ISSUE #60202: Parsing anonymous function fails on 1.14
https://github.com/bramtayl/Unzip.jl/pull/12

Fails on julia 1.14

1.14
```
julia> function zip_missing(::Tuple{}, longer)
           map(function (second_one)
               (missing, second_one)
           end, longer)
       end
ERROR: ParseError:
# Error @ REPL[2]:2:18
function zip_missing(::Tuple{}, longer)
    map(function (second_one)
#                └──────────┘ ── Invalid signature in function definition
Stacktrace:
 [1] top-level scope
   @ REPL:1
```
1.12.1
```
julia> function zip_missing(::Tuple{}, longer)
           map(function (second_one)
               (missing, second_one)
           end, longer)
       end
zip_missing (generic function with 1 method)
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/60202

```
julia> function zip_missing(::Tuple{}, longer)
		      map(function (second_one)
		          (missing, second_one)
		      end, longer)
		  end
zip_missing (generic function with 1 method)
```

Written by Claude

### CODE REVIEW

**Comment by Keno** [comment]
Just for reference, @KristofferC just touched this code in https://github.com/JuliaLang/JuliaSyntax.jl/pull/580

File: JuliaSyntax/test/parser.jl [hunk 1]
```diff
@@ -603,6 +603,7 @@ tests = [
         "macro \$f()    end"   =>  "(macro (call (\$ f)) (block))"
         "macro (\$f)()  end"   =>  "(macro (call (parens (\$ f))) (block))"
         "function (x) body end"=>  "(function (tuple-p x) (block body))"
+        "function (x)\n    body\nend"=>  "(function (tuple-p x) (block body))"
```
Comment (fingolfin) [inline JuliaSyntax/test/parser.jl:614]: Maybe also insert a involving explicitly a tuple `()` as the body?

E.g. near line 622-628, where in https://github.com/JuliaLang/JuliaSyntax.jl/pull/580 this test was inserted:
```
        "function (\n        f\n        )() end" =>  "(function (call (parens f)) (block))"
```
well now we want to test something like this (not sure if I got it quite right)
```
        "function (\n        x\n        )\n() end" =>  "(function (tuple-p x) (block (tuple-p)))"
```

Because for me, on master, this parses:
```julia
function(y)
  body
end
```
but this does not:
```julia
function(y)
  ()
end
```

**Comment by IanButterworth** [comment]
The fix here has become quite complicated.. @c42f @KristofferC

**Comment by fogti** [comment]
Would it be possible to add a unit test for this? (incl. for the previous change that affected this part of the code)

Did we actually find out where the error comes from (by bisecting starting from Julia-1.12)?

**Comment by IanButterworth** [comment]
There are a couple of tests added already. 

I believe the issue was introduced by https://github.com/JuliaLang/JuliaSyntax.jl/pull/580

File: JuliaSyntax/src/julia/parser.jl [hunk 2]
```diff
@@ -2218,10 +2218,23 @@ function parse_function_signature(ps::ParseState, is_function::Bool)
...
+                # Otherwise there's whitespace/newline before `)`.
+                first_no_skip = peek(ps, 1, skip_newlines=false)
+                if first_no_skip == K")"
+                    # Directly before ), token after ) is peek(2, skip_newlines=false)
+                    token_after_paren = peek(ps, 2, skip_newlines=false)
+                else
+                    # There's whitespace before ), so ) is at peek(2, skip_newlines=false)
+                    # and what follows ) is peek(3, skip_newlines=false)
+                    token_after_paren = peek(ps, 3, skip_newlines=false)
+                end
```
Comment (fogti) [inline JuliaSyntax/src/julia/parser.jl]: This could be compacted into:

```suggestion
                token_after_paren = peek(ps, if first_no_skip == K")"
                    # Directly before ), token after ) is peek(2)
                    2
                else
                    # There's whitespace before ), so ) is at peek(2)
                    # and what follows ) is peek(3)
                    3
                end, skip_newlines=false)
```

Is there no function to scan for the next token that isn't whitespace?

Comment (IanButterworth) [reply JuliaSyntax/src/julia/parser.jl]: That's less readable IMO

Comment (fogti) [reply JuliaSyntax/src/julia/parser.jl]: sure... But it might be worth it to factor out the functionality that finds the count offset of the next token after whitespace...

File: JuliaSyntax/src/julia/parser.jl [hunk 3]
```diff
@@ -2218,10 +2218,23 @@ function parse_function_signature(ps::ParseState, is_function::Bool)
...
+                else
+                    # There's whitespace before ), so ) is at 2
+                    # and what follows ) is at 3
+                    3
+                end
+                token_after_paren = peek(ps, next_token_pos, skip_newlines=false)
+                # If token_after_paren is a newline, this is an anonymous function
+                has_newline_after_paren = _maybe_grouping_parens && token_after_paren == K"NewlineWs"
+                # Get the next significant token to determine if we need to parse a call
+                next_kind = peek(ps, 2, skip_newlines=_maybe_grouping_parens && !has_newline_after_paren)
```
Comment (fogti) [inline JuliaSyntax/src/julia/parser.jl:2237]: I think it would make a lot of sense to split the logic with a case distinction on `_maybe_grouping_parens`:

```suggestion
                next_kind = if _maybe_grouping_parens
                    # Check if there's a newline between `)` and the next `(` or `.`.
                    # We need to find where `)` is and check what immediately follows it.
                    # If peek(1, skip_newlines=false) is `)`, we're directly before it.
                    # Otherwise there's whitespace/newline before `)`.
                    next_token_pos = if peek(ps, 1, skip_newlines=false) == K")"
                        # Directly before ), token after ) is at 2
                        2
                    else
                        # There's whitespace before ), so ) is at 2
                        # and what follows ) is at 3
                        3
                    end
                    token_after_paren = peek(ps, next_token_pos, skip_newlines=false)
                    # If token_after_paren is a newline, this is an anonymous function
                    # Get the next significant token to determine if we need to parse a call
                    peek(ps, 2, skip_newlines= token_after_paren != K"NewlineWs")
                else
                    # Get the next significant token to determine if we need to parse a call
                    peek(ps, 2, skip_newlines=false)
                end
```

Comment (fogti) [reply JuliaSyntax/src/julia/parser.jl:2237]: Subsequently, it makes sense to inspect more closely what happens if `_maybe_grouping_parens` is true: If the next tokens are:
* `K")", K"NewlineWs"`, then we call `peek(ps, 2, skip_newlines=false) = token_after_paren`
* `K")", !K"NewlineWs"`, then we call `peek(ps, 2, skip_newlines=true) = token_after_paren`
* `!K")", x/*we expect K")" here, but don't check that*/, K"NewlineWs"`, then we call `peek(ps, 2, skip_newlines=false)=token_after_paren` (I think (hope I interpret it correctly) that `__lookahead_index` treats the case with `skip_newlines=true` such that it also skips newlines entirely, including in the count up to `n=2`)
* `!K")", x, !K"NewlineWs", then we call `peek(ps, 2, skip_newlines=false)=token_after_paren`

So, I think we can omit the `peek(ps, 2, skip_newlines= token_after_paren != K"NewlineWs")` entirely.

```suggestion
                next_token_pos = if _maybe_grouping_paren
                    # Check if there's a newline between `)` and the next `(` or `.`.
                    # We need to find where `)` is and check what immediately follows it.
                    # If peek(1, skip_newlines=false) is `)`, we're directly before it.
                    # Otherwise there's whitespace/newline before `)`.
                    if peek(ps, 1, skip_newlines=false) == K")"
                        # Directly before ), token after ) is at 2
                        2
                    else
                        # There's whitespace before ), so ) is at 2
                        # and what follows ) is at 3
                        3
                    end
                else
                    2
                end
                # Get the next significant token to determine if we need to parse a call
                next_kind = peek(ps, next_token_pos, skip_newlines=false)
```

**Comment by lgoettgens** [comment]
It would be great to get this in better earlier than later. As long as https://github.com/JuliaLang/julia/issues/60202 is unresolved, Unzip.jl won't precompile, including all of its dependents (which e.g. contain Plots.jl and thus a rather large fraction of the ecosystem), and any nanosoldier runs for other changes in nightly won't check these packages at all

**Comment by IanButterworth** [comment]
Agreed. This still needs review by someone familiar with JuliaSyntax for the general approach.
