### PR TITLE
always create new cache files in default path when recompiling 

### LINKED ISSUE #14368: precompile shouldn't try to overwrite stale read-only cache files
A lot of people are seeing failures on JuliaBox (JuliaLang/JuliaBox#338, stevengj/PyPlot.jl#185, JuliaLang/IJulia.jl#159) because JuliaBox ships precompiled cache files in a read-only directory `/opt/julia_packages/.julia/lib/v0.4/`.   If these cache files are stale, Julia tries to recompile them, but it begins by trying to delete the stale old cache file, which throws an exception, e.g.
```
julia> using Compat                                                                                                                                                
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.                                                                
ERROR: unlink: read-only file system (EROFS)                                                                                                                       
 in unlink at fs.jl:102                                                                                                                                            
 in rm at file.jl:59                                                                                                                                               
 in create_expr_cache at loading.jl:330                                                                                                                            
 in recompile_stale at loading.jl:461                                                                                                                              
 in _require_from_serialized at loading.jl:83                                                                                                                      
 in _require_from_serialized at ./loading.jl:109                                                                                                                   
 in require at ./loading.jl:219 
```

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #14368, by always calling `Base.compilecache` when creating new cache files (including when recompiling), so that new cache files are always put in the same place (`Base.LOAD_CACHE_PATH[1]`).

Should probably be backported because this is causing problems on JuliaBox.

### CODE REVIEW

**Comment by stevengj** [comment]
@tkelman, it looks like AppVeyor is hitting a timeout on 64-bit Windows?  Is this my fault, or is there some other recurring glitch?

**Comment by stevengj** [comment]
Yay, tests are green.

**Comment by stevengj** [comment]
I'll plan to merge on Monday if there are no objections.

File: test/compile.jl [hunk 1]
```diff
@@ -71,6 +72,16 @@ try
     end
     Base.compilecache("FooBar")
     sleep(2)
+    @test isfile(joinpath(dir, "FooBar.ji"))
+
+    touch(FooBar_file)
+    insert!(Base.LOAD_CACHE_PATH, 1, dir2)
+    Base.recompile_stale(:FooBar, joinpath(dir, "FooBar.ji"))
+    sleep(2)
```
Comment (tkelman) [inline test/compile.jl]: I hope this is enough for slow or highly-loaded systems? Would it be better to do a polling file watcher or something similar?

Comment (tkelman) [inline test/compile.jl]: This still isn't very future-proof. Needs improvement before I'd be comfortable backporting this. We shouldn't be making assumptions about how long distro buildbots, limited-resource VM's, or small embedded processors are going to take to do codegen here.

Comment (stevengj) [inline test/compile.jl]: `recompile_stale` is synchronous, so the length of time to do the codegen is not relevant.   `sleep(2)` is only there for paranoia about reading a file on the filesystem that was created by another process which has just completed.

Comment (tkelman) [inline test/compile.jl]: Ah, sorry about that, my mistake on what the `sleep` was for. Could've used a comment to that effect.
