### PR TITLE
workaround wrong paths reported for stdlib functions 

### LINKED ISSUE #26314: `edit` and `less` fail for stdlib functions in distribution binaries
The trouble is that file names in stdlib methods are (inappropriate) absolute paths:

```julia
julia> ml=methods(edit)
# 5 methods for generic function "edit":
[1] edit(path::AbstractString) in InteractiveUtils at 
/buildworker/worker/package_linux64/build/usr/share/julia/site/v0.7/InteractiveUtils/src/editless.jl:37
#etc.

julia> less(edit,(AbstractString,))
/buildworker/worker/package_linux64/build/usr/share/julia/site/v0.7/InteractiveUtils/src/editless.jl: 
No such file or directory
```

We can cheat:
```julia
julia> ml.ms[1].file=Symbol("../site/v0.7/InteractiveUtils/src/editless.jl");
julia> less(edit,(AbstractString,)) # this works
```
This is troublesome for those of us who want to consult "The Real Documentation" but  didn't build from source.

(edited to fit more useful issue title)

### PR DESCRIPTION
**Pull request by KristofferC**
Not really clean to special case it just ofr `less` and `edit` but that is where people seems to encounter this issue the most. The workaround could potentially be put in `find_source_file` but that is a bit more "invasive".

This is also kinda hard to test. I tested it by evaluating this into `InteractveUtils` in a released julia.

Fixes https://github.com/JuliaLang/julia/issues/26314

### CODE REVIEW

**Comment by fredrikekre** [comment]
Maybe add this for `@which` too?

**Comment by cossio** [comment]
Something holding this from being merged? Would be nice to have this issue fixed.

**Comment by KristofferC** [comment]
> Something holding this from being merged? Would be nice to have this issue fixed.

I improved the implementation a bit but should be good to go now.

Tried it locally with the executable built by the buildbot and `@which`, `@edit` and `@less` work well with stdlib functions now.

**Review by fredrikekre — APPROVED** [review]

File: base/methodshow.jl [hunk 1]
```diff
@@ -118,6 +118,16 @@ end
 default_methodloc(method::Method) = method.file, method.line
 const methodloc_callback = Ref{Function}(default_methodloc)
 
+# This function does the method location updating
+function updated_methodloc(m)
+    file, line = invokelatest(methodloc_callback[], m)
+    if file !== nothing && isdefined(@__MODULE__, :Sys)
```
Comment (vtjnash) [inline base/methodshow.jl]:
```suggestion
    if file !== nothing && Sys.BUILD_STDLIB_PATH != Sys.STDLIB
```
Is Sys ever not defined?

And should we put this inside `default_methodloc`, or do we want to do this unconditionally?

File: base/methodshow.jl [hunk 2]
```diff
@@ -248,7 +258,7 @@ function show_method_table(io::IO, ms::MethodList, max::Int=-1, header::Bool=tru
             show(io, meth; kwtype=kwtype)
             file, line = meth.file, meth.line
             try
```
Comment (vtjnash) [inline base/methodshow.jl]: move these `try; catch` inside `updated_methodloc` also

File: base/methodshow.jl [hunk 3]
```diff
@@ -118,6 +118,16 @@ end
...
 const methodloc_callback = Ref{Function}(default_methodloc)
 
+# This function does the method location updating
+function updated_methodloc(m)
+    file, line = invokelatest(methodloc_callback[], m)
+    if file !== nothing && isdefined(@__MODULE__, :Sys)
+        # BUILD_STDLIB_PATH gets defined in sysinfo.jl
+        file = replace(String(file), normpath(Sys.BUILD_STDLIB_PATH) => normpath(Sys.STDLIB))
+    end
+    return Symbol(file), line
```
Comment (vtjnash) [inline base/methodshow.jl]:
```suggestion
    return string(file), line
```

File: base/methodshow.jl [hunk 4]
```diff
@@ -118,6 +118,16 @@ end
 default_methodloc(method::Method) = method.file, method.line
 const methodloc_callback = Ref{Function}(default_methodloc)
 
+# This function does the method location updating
+function updated_methodloc(m)
+    file, line = invokelatest(methodloc_callback[], m)
```
Comment (vtjnash) [inline base/methodshow.jl]:
```suggestion
    file, line = try
            invokelatest(methodloc_callback[], m)
        catch
            default_methodloc(m)
        end
    file === nothing && return (string(m.file), m.line)
    file = string(file)
```

File: base/methodshow.jl [hunk 5]
```diff
@@ -118,6 +118,16 @@ end
 default_methodloc(method::Method) = method.file, method.line
 const methodloc_callback = Ref{Function}(default_methodloc)
 
+# This function does the method location updating
+function updated_methodloc(m)
```
Comment (vtjnash) [inline base/methodshow.jl]:
```suggestion
function updated_methodloc(m)::Tuple{String, Int32}
```

File: base/methodshow.jl (hunk 1 above)
Comment (KristofferC) [reply base/methodshow.jl]: It's not defined when this function gets defined and I was worried if there was some error before `Sys` gets defined then it would crash when trying to print some method.

Comment (KristofferC) [reply base/methodshow.jl]: I think we want to do this unconditionally.

**Comment by rapus95** [comment]
Can this still make it into 1.3 or does the feature freeze prohibit it?

**Comment by KristofferC** [comment]
It will not make it into 1.3.0 for sure. Maybe 1.3.1.

**Comment by rapus95** [comment]
Btw as this request is called workaround, I guess you'd not call it the idiomatic way.
Would it generally make sense to use the `pathof(module)` function to determine the path of the module where the function was defined and then resolve the path relative to that?

**Comment by KristofferC** [comment]
> Btw as this request is called workaround, I guess you'd not call it the idiomatic way.

I dunno... If it works, it works:P

I did some fixups here @vtjnash

File: base/methodshow.jl [hunk 6]
```diff
@@ -119,8 +119,25 @@ end
...
+const methodloc_callback = Ref{Function}()
+
+# This function does the method location updating
+function updated_methodloc(m::Method)::Tuple{String, Int32}
+    file, line = string(m.file), m.line
+    if isassigned(methodloc_callback)
+        file, line = try
+            invokelatest(methodloc_callback[], m)
+        catch
+        end
```
Comment (rapus95) [inline base/methodshow.jl]: This will produce a misleading error if the call fails, won't it?
```julia
julia> a,b = try div(4,0) catch end
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:600
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:600
  iterate(::ExponentialBackOff) at error.jl:218
  ...
Stacktrace:
 [1] indexed_iterate(::Nothing, ::Int64) at .\tuple.jl:66
 [2] top-level scope at REPL[645]:1
```

Comment (KristofferC) [reply base/methodshow.jl]: Yep, good point. I mixed two different things here (originally had something inside the `catch`).

Comment (rapus95) [reply base/methodshow.jl]: Idk how logging is handled for Base but I could imagine adding some `@debug e` (or even `@debug error(e)`) might help in some circumstances.

**Comment by musm** [comment]
Does `Pkg.Operations.jl` need an update as well? 
I get the wrong paths as well when interacting with the Package Manager.
```
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\Operations.jl:494
```

**Comment by KristofferC** [comment]
I guess `@info` embeds the full path as well at macro expansion time. But that's for another PR.

**Comment by rapus95** [comment]
Sad that it won't make it into 1.3 even though it is already merged 🙈

**Comment by KristofferC** [comment]
Could be put into 1.3.1 if it doesnt cause any problems on master.

**Comment by crstnbr** [comment]
> Could be put into 1.3.1 if it doesnt cause any problems on master.

I'm begging for it! This has been bugging me for way too long now. 😊

**Comment by KristofferC** [comment]
I have my script set to ignore backport labels that also has a triage label because we said we would triage backports at some point. This doesn't seem to happen though so the result is that PRs (like this) just get forgotten. I'll just backport stuff that includes the triage label as well.
