### PR TITLE
fix #25857, `typeinfo` problem in showing arrays with abstract tuple types

### LINKED ISSUE #25857: Error displaying an array of tuples of tuples
```
julia> [((), BitArray{0}), ((1,), BitVector), ((1,2), BitMatrix)]
3-element Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}:
Error showing value of type Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}:
ERROR: BoundsError: attempt to access svec(Vararg{Int64,N} where N)
  at index [2]
Stacktrace:
 [1] getindex(::SimpleVector, ::Int64) at ./essentials.jl:512
 [2] show_delim_array(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Tuple{Int64,Int64}, ::Char, ::Char, ::Char, ::Bool, ::Int64, ::Int64) at ./show.jl:688
 [3] show_delim_array at ./show.jl:674 [inlined]
 [4] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Tuple{Int64,Int64}) at ./show.jl:706
 [5] show_delim_array(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Tuple{Tuple{Int64,Int64},DataType}, ::Char, ::Char, ::Char, ::Bool, ::Int64, ::Int64) at ./show.jl:688
 [6] show_delim_array at ./show.jl:674 [inlined]
 [7] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Tuple{Tuple{Int64,Int64},DataType}) at ./show.jl:706
 [8] #sprint#343(::IOContext{REPL.Terminals.TTYTerminal}, ::Int64, ::Function, ::Function, ::Tuple{Tuple{Int64,Int64},DataType}, ::Vararg{Tuple{Tuple{Int64,Int64},DataType},N} where N) at ./strings/io.jl:89
 [9] #sprint at ./<missing>:0 [inlined]
 [10] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::Tuple{Tuple{Int64,Int64},DataType}) at ./show.jl:1842
 [11] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}, ::Base.OneTo{Int64}, ::Base.OneTo{Int64}, ::Int64, ::Int64, ::Int64) at ./arrayshow.jl:68
 [12] print_matrix(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./arrayshow.jl:187
 [13] print_matrix at ./arrayshow.jl:160 [inlined]
 [14] print_array at ./arrayshow.jl:309 [inlined]
 [15] _display(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}) at ./arrayshow.jl:345
 [16] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}) at ./arrayshow.jl:348
 [17] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}) at /data/mbauman/julia-master/usr/share/julia/site/v0.7/REPL/src/REPL.jl:125
 [18] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}) at /data/mbauman/julia-master/usr/share/julia/site/v0.7/REPL/src/REPL.jl:128
 [19] display(::Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}) at ./multimedia.jl:291
 [20] (::getfield(Base, Symbol("#inner#4")){Base.Iterators.IndexValue{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},typeof(display),Tuple{Array{Tuple{Tuple{Vararg{Int64,N} where N},DataType},1}}})() at ./essentials.jl:646
 [21] #invokelatest#3 at ./essentials.jl:647 [inlined]
 [22] invokelatest at ./essentials.jl:646 [inlined]
 [23] print_response(::REPL.Terminals.TTYTerminal, ::Any, ::Nothing, ::Bool, ::Bool, ::Nothing) at /data/mbauman/julia-master/usr/share/julia/site/v0.7/REPL/src/REPL.jl:146
 [24] print_response(::REPL.LineEditREPL, ::Any, ::Nothing, ::Bool, ::Bool) at /data/mbauman/julia-master/usr/share/julia/site/v0.7/REPL/src/REPL.jl:132
 [25] (::getfield(REPL, Symbol("#do_respond#15")){Bool,getfield(REPL, Symbol("##25#35")){REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /data/mbauman/julia-master/usr/share/julia/site/v0.7/REPL/src/REPL.jl:706
 [26] top-level scope
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/show.jl [hunk 1]
```diff
@@ -1181,3 +1181,6 @@ end
     @test repr("text/plain", context=:compact=>true) == "\"text/plain\""
     @test repr(MIME("text/plain"), context=:compact=>true) == "MIME type text/plain"
 end
+
+# issue #25857
+@test repr([(1,),(1,2),(1,2,3)]) == "Tuple{Int64,Vararg{Int64,N} where N}[(1,), (1, 2), (1, 2, 3)]"
```
Comment (rfourquet) [inline test/show.jl]: I wonder if `Int64` should be changed to `$Int` to pass on 32 bits machines. Also, there is a "typeinfo" `@testset` already, you could insert this test there (at line 1124).

**Review by rfourquet — APPROVED** [review]

**Comment by rfourquet** [comment]
Thanks! I had just finished preparing a PR myself but much uglier :) (I didn't know that `fieldtype` handled nicely `Vararg`).
