### PR TITLE
Remove potential unitialized memory in the GC stack

### LINKED ISSUE #60622: GC corruption / segfault on 1.12
Split out from https://github.com/JuliaLang/julia/issues/59483 

Reproducer
```
using BlockArrays, LazyBandedMatrices, FillArrays, InfiniteArrays
using LazyBandedMatrices: BlockBroadcastVector

m = 1.0
T = Float64

B = BlockVcat(
    BlockBroadcastVector{T}(vcat,
        unitblocks(-(1:∞)/2),
        unitblocks(2 * (2:∞) ./ ((m+3):2:∞)))',
    BlockBroadcastVector{T}(vcat,
        unitblocks(-(1:∞) .* ((m+1):∞) .* ((3m+2+6):6:∞) ./ (10*(1:∞).^2 .+ 4m*(m+1) .+ (13m+6) * (1:∞))),
        unitblocks(((m+2):∞) .* (2:∞) ./ (((m+3):2:∞) .* ((m+4):2:∞))))',
    BlockBroadcastVector{T}(vcat,
        unitblocks((1:∞) .* ((m+2):2:∞) .* ((m+2):∞) ./ (2*(10*(1:∞).^2 .+ 4m*(m+1) .+ (13m+6) * (1:∞)))),
        unitblocks(-2 * (2:∞).^2 ./ (((m+3):2:∞) .* ((m+4):2:∞))))',
    BlockBroadcastVector{T}(vcat,
        unitblocks(-(2:∞) .* ((m+2):2:∞) .* (1:∞) ./ (10*(1:∞).^2 .+ 4m*(m+1) .+ (13m+6) * (1:∞))),
        unitblocks(Zeros{T}(∞)))'
)

# MINIMAL reproducer: :limit => true causes GC segfault
# Without :limit, we get ArgumentError (safe)
# With :limit, we get GC corruption (unsafe)
io = IOContext(stdout, :limit => true)
show(io, MIME"text/plain"(), B)
```

```
% julia +nightly --project=repro ./repro/repro.jl
4×ℵ₀-blocked 4×ℵ₀ BlockVcat{Float64}:

[10889] signal 10 (1): Bus error: 10
in expression starting at /Users/ian/Documents/GitHub/julia/repro/repro.jl:28
gc_try_setmark_tag at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:262 [inlined]
gc_try_claim_and_push at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:1708 [inlined]
gc_mark_stack at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:2060 [inlined]
gc_mark_outrefs at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:2344 [inlined]
gc_mark_and_steal at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:2568
_jl_gc_collect at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:3088
ijl_gc_collect at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:3510
maybe_collect at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:356 [inlined]
jl_gc_small_alloc_inner at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:733 [inlined]
ijl_gc_small_alloc at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gc-stock.c:782
Array at ./boot.jl:676 [inlined]
getindex at ./array.jl:436 [inlined]
#ir_abstract_constant_propagation#216 at ./../usr/share/julia/Compiler/src/ssair/irinterp.jl:325
ir_abstract_constant_propagation at ./../usr/share/julia/Compiler/src/ssair/irinterp.jl:319 [inlined]
semi_concrete_eval_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:1262
abstract_call_method_with_const_args at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:886
abstract_call_method_with_const_args at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:861 [inlined]
handle1 at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:177
infercalls at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:247
abstract_call_gf_by_type at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:328
abstract_call_known at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2821
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2931
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2924 [inlined]
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3084
abstract_eval_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3102 [inlined]
abstract_eval_statement_expr at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3466
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3865 [inlined]
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3822 [inlined]
typeinf_local at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4375
jfptr_typeinf_local_92137.1 at /Users/ian/.julia/juliaup/julia-nightly/lib/julia/sys.dylib (unknown line)
typeinf at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4567
const_prop_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:1343
abstract_call_method_with_const_args at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:892
abstract_call_method_with_const_args at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:861 [inlined]
handle1 at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:177
infercalls at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:247
abstract_call_gf_by_type at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:328
abstract_call_known at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2821
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2931
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2924 [inlined]
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3084
abstract_eval_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3102 [inlined]
abstract_eval_statement_expr at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3466
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3865 [inlined]
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3822 [inlined]
typeinf_local at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4375
jfptr_typeinf_local_92137.1 at /Users/ian/.julia/juliaup/julia-nightly/lib/julia/sys.dylib (unknown line)
typeinf at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4567
const_prop_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:1343
abstract_call_method_with_const_args at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:892
abstract_call_method_with_const_args at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:861 [inlined]
handle1 at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:177
infercalls at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:247
abstract_call_gf_by_type at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:328
abstract_call_known at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2821
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2931
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:2924 [inlined]
abstract_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3084
abstract_eval_call at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3102 [inlined]
abstract_eval_statement_expr at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3466
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3865 [inlined]
abstract_eval_basic_statement at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:3822 [inlined]
typeinf_local at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4375
jfptr_typeinf_local_92137.1 at /Users/ian/.julia/juliaup/julia-nightly/lib/julia/sys.dylib (unknown line)
typeinf at ./../usr/share/julia/Compiler/src/abstractinterpretation.jl:4567
typeinf_ext at ./../usr/share/julia/Compiler/src/typeinfer.jl:1532
typeinf_ext_toplevel at ./../usr/share/julia/Compiler/src/typeinfer.jl:1715 [inlined]
typeinf_ext_toplevel at ./../usr/share/julia/Compiler/src/typeinfer.jl:1724
jfptr_typeinf_ext_toplevel_86800.1 at /Users/ian/.julia/juliaup/julia-nightly/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/./julia.h:2285 [inlined]
jl_type_infer at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gf.c:463
jl_compile_method_internal at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gf.c:3636
_jl_invoke at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gf.c:4108 [inlined]
ijl_apply_generic at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/gf.c:4313
getindex at /Users/ian/.julia/packages/LazyBandedMatrices/r8bvb/src/blockconcat.jl:81
getindex at /Users/ian/.julia/packages/BlockArrays/wmk4q/src/blockaxis.jl:7 [inlined]
getindex at /Users/ian/.julia/packages/LazyBandedMatrices/r8bvb/src/blockconcat.jl:83
isassigned at ./multidimensional.jl:1641
unknown function (ip: 0x11186c297) at (unknown file)
alignment at ./arrayshow.jl:68
_print_matrix at ./arrayshow.jl:207
print_matrix at ./arrayshow.jl:171 [inlined]
print_matrix at ./arrayshow.jl:171 [inlined]
print_array at ./arrayshow.jl:365 [inlined]
show at ./arrayshow.jl:406
unknown function (ip: 0x1117a4acf) at (unknown file)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/./julia.h:2285 [inlined]
do_call at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/interpreter.c:123
eval_stmt_value at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/interpreter.c:194
eval_body at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/interpreter.c:675
jl_interpret_toplevel_thunk at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/interpreter.c:884
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/toplevel.c:757
jl_eval_toplevel_stmts at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/toplevel.c:600
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/toplevel.c:698
ijl_toplevel_eval at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/toplevel.c:769 [inlined]
ijl_toplevel_eval_in at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/toplevel.c:814
eval at ./boot.jl:489
include_string at ./loading.jl:3151
_include at ./loading.jl:3211
include at ./Base.jl:309
exec_options at ./client.jl:344
_start at ./client.jl:585
jfptr__start_76619.1 at /Users/ian/.julia/juliaup/julia-nightly/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/./julia.h:2285 [inlined]
true_main at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/jlapi.c:971
jl_repl_entrypoint at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/src/jlapi.c:1138
Allocations: 7235957 (Pool: 7235903; Big: 54); GC: 9
zsh: bus error  julia +nightly --project=repro ./repro/repro.jl
```

Some investigation that needs sanity checking in https://github.com/JuliaLang/julia/pull/60621

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes #60622 

This was a very messy thing. But apparently the code we generate for value_to_pointer is liable to being transformed by LLVM, and under some transformations specifically LICM we can materialize a root that didn't exist at codegen time and that root is liable to being being undef which can cause segfaults
This conservativaly initializes the gc pointers to zero.

### CODE REVIEW

**Comment by gbaraldi** [comment]
Only issue was. Writing a test for this was almost impossible.

File: src/codegen.cpp [hunk 1]
```diff
@@ -2430,6 +2430,43 @@ static inline jl_cgval_t value_to_pointer(jl_codectx_t &ctx, const jl_cgval_t &v
         Align align(julia_alignment(v.typ));
         Type *ty = julia_type_to_llvm(ctx, v.typ);
         AllocaInst *loc = emit_static_alloca(ctx, ty, align);
+        if (CountTrackedPointers(ty).count > 0) {
+            auto tracked = TrackCompositeType(ty);
+            jl_aliasinfo_t ai = jl_aliasinfo_t::fromTBAA(ctx, ctx.tbaa().tbaa_gcframe);
+            Instruction *last_inserted = ctx.topalloca;
+            for (const auto &indices : tracked) {
```
Comment (topolarity) [inline src/codegen.cpp]: Should be as simple as:
```c++
    jl_datatype_t *dt = (jl_datatype_t *)v.typ;
    bool hasptr = dt->layout->first_ptr >= 0;
    size_t npointers = hasptr ? dt->layout->npointers : 0;
    auto InsertPoint = ctx.builder.saveIP();
    ctx.builder.SetInsertPoint(ctx.topalloca->getParent(), ++ctx.topalloca->getIterator());
    for (size_t i = 0; i < npointers; i++) {
        // make sure these are nullptr early from LLVM's perspective, in case it decides to SROA it
        Value *ptr_field = emit_ptrgep(ctx, loc, jl_ptr_offset(dt, i) * sizeof(void *));
        StoreInst *store = ctx.builder.CreateAlignedStore(
            Constant::getNullValue(ctx.types().T_prjlvalue), ptr_field, Align(sizeof(void *)));
    }
    ctx.builder.restoreIP(InsertPoint);
```
although you can get fancier if you want to coalesce adjacent roots to a single `memset`.

This logic should probably be moved to `cgutils.cpp` and implemented more similar to `split_value_into` / `undef_derived_strct`

**Comment by topolarity** [comment]
> Writing a test for this was almost impossible.

It might be a reasonable addition to the GCinvariantPass?
Any `alloca` containing a `ptr(10)` should set that memory to 0 in the first basic block IIUC.

**edit:** Gabriel pointed out that DCE and (post-)dominating stores / loads will break that check, so that won't work sadly.

**Comment by gbaraldi** [comment]
Addressed the review feedback - simplified the code to use Julia's datatype layout information (`jl_ptr_offset`) instead of walking LLVM types with `TrackCompositeType`, as suggested.
