### PR TITLE
specialized complex^real methods

### LINKED ISSUE #14342: wrong sign of zero for (x+0im)^(negative real)
With Julia 0.5, `(2.0+0im)^-2` correctly gives `0.25 - 0.0im`, but `(2.0+0im)^-2.1` gives `0.23325824788420185 + 0.0im`.  Notice that the sign of the imaginary part is incorrect, in that `(2.0+δ*im)^-2.1` should give a negative imaginary part as `δ ⟶ 0⁺`.

cc: @jiahao

### PR DESCRIPTION
**Pull request by stevengj**
This adds specialized methods for `complex^real`, which would previously have first promoted to `complex^complex`.  Fixes #14342.

The performance improvement seems to be very small in typical cases (e.g. 6-8% for `Complex{Float64}^Float64`), but it fixes a longstanding bug in the sign of the zero imaginary part for `(2.0+0im)^-2.1` and similar.

### CODE REVIEW

File: base/complex.jl [hunk 1]
```diff
@@ -631,7 +631,24 @@ function log1p(z::Complex{T}) where T
...
+    er = exp10(real(z))
+    theta = imag(z) * log(convert(T, 10))
+    s, c = sincos(theta)
+    Complex(er * c, er * s)
+end
+exp10(z::Complex) = exp10(float(z))
+
+# _cpow helper function to avoid method ambiguity with ^(::Complex,::Real)
+function _cpow(z::Complex{T}, p::Union{T,Complex{T}})::Complex{T} where T<:AbstractFloat
     if p == 2 #square
```
Comment (stevengj) [inline base/complex.jl]: Note that this `p==2` special-case code dates all the way back to @jiahao in #2891, who I guess added it as a performance optimization.

Performance optimization for `z^2` is probably mainly for literal powers, though, so maybe we should move this to a `literal_pow` method?  For `Complex64` and `Complex128`, `z^2` is already inlined as `z*z`, but maybe you can save an operation or two by specializing it further.

**Review by ararslan — APPROVED** [review]
