### PR TITLE
Base: prevent `precision` infinite recursion

### LINKED ISSUE #52909: `precision(Union{Float16,Float32})` recurs without bound (until `StackOverflowError`)
```julia-repl
julia> precision(Union{Float16,Float32})
ERROR: StackOverflowError:
Stacktrace:
     [1] _precision(x::Type, base::Int64)
       @ Base ./float.jl:844
     [2] _precision(x::Type)
       @ Base ./float.jl:843
--- the above 2 lines are repeated 26657 more times ---
 [53317] _precision(x::Type, base::Int64)
       @ Base ./float.jl:844

julia> versioninfo()
Julia Version 1.11.0-DEV.1276
Commit fc6295df630 (2024-01-15 05:47 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

Fix incoming.

### PR DESCRIPTION
**Pull request by nsajko**
Make the single-argument method of `_precision` into its own function.

Now `precision(Union{Float16,Float32})` results in a `MethodError` instead of in a `StackOverflowError`.

Fixes #52909

### CODE REVIEW

File: base/float.jl [hunk 1]
```diff
@@ -836,12 +836,12 @@ number of significand digits in that base.
 """
 function precision end
 
-_precision(::Type{Float16}) = 11
-_precision(::Type{Float32}) = 24
-_precision(::Type{Float64}) = 53
+precision_with_base_2(::Type{Float16}) = 11
```
Comment (gbaraldi) [inline base/float.jl:839]: I would keep a leading underscore here

Comment (nsajko) [reply base/float.jl:839]: Are underscore prefixes really still necessary now that we have `public`?

**Comment by nsajko** [comment]
Added back the `_` name prefix, removed a default argument value (`=2`), added more tests.

**Comment by nsajko** [comment]
bump

**Review by gbaraldi — APPROVED** [review]
