### PR TITLE
fix #17572, error during inference due to `<:` on non-Type

### LINKED ISSUE #17572: Inference crashed because of `<: 0`
The following snippet of (nonsensical) code makes inference trip over doing a subtype check on with a value as type:

```julia
immutable Dual{N}
    value::Int
    partials::NTuple{1,Int}
end

import Base.*
function *{F,A}(a, b::Array{Dual{A}})
    return Dual{2}(b[1], NTuple{2,A}((1, 1)))
end

a = [Dual{0}(1, (1,))]
f(x) = x*x
f(a)
```

```
WARNING: An error occured during inference. Type inference is now partially disabled.
TypeError(func=:subtype, context="", expected=Type, got=0)
rec_backtrace at /home/tbesard/Projects/Julia/src/stackwalk.c:84
record_backtrace at /home/tbesard/Projects/Julia/src/task.c:232 [inlined]
jl_throw at /home/tbesard/Projects/Julia/src/task.c:550
jl_type_error_rt at /home/tbesard/Projects/Julia/src/builtins.c:105
jl_type_error at /home/tbesard/Projects/Julia/src/builtins.c:111
jl_f_issubtype at /home/tbesard/Projects/Julia/src/builtins.c:372
⊑ at ./inference.jl:1235
```

Tested on 0.5, latest master. Doesn't occur on 0.4.
Repro lifted from real-life code from ForwardDiff (cc @jrevels).

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -4452,3 +4452,15 @@ end
...
+function f17572{A}(::Type{Val{A}})
+    return Tuple{Int}(Tuple{A}((1,)))
+end
+try
+    f17572(Val{0})
+    @test false
+catch me
+    # cannot convert to non-type `0`
+    @test isa(me,MethodError) && me.f === convert
+end
```
Comment (vtjnash) [inline test/core.jl]: this test doesn't fail for me on master. I think you need to call `code_typed` directly and show that there is no error being thrown.

also, since it's not testing core, it should go in `test/inference.jl` (so you don't get rebase conflicts :)
