### PR TITLE
[Test] Print RNG of a failed testset and add option to set it

### LINKED ISSUE #56235: [Test] Print RNG seed of a failed testset
When a testset fails, it'd be nice if `@testset` also printed the RNG status to let people reproduce the failure.  Basically, we'd need to show `tls_seed_orig` (thanks @IanButterworth for pointing this out) https://github.com/JuliaLang/julia/blob/75f498e919f891ec6a42c9c07d4dff740daecd33/stdlib/Test/src/Test.jl#L1698-L1701 to the user, and maybe also a way to manually set the seed (just like `Base.runtest` does for julia's own tests).

Ref: https://github.com/JuliaLang/julia/issues/55878#issuecomment-2374928286

### PR DESCRIPTION
**Pull request by giordano**
Also, add a keyword option to `@testset` to let users override the seed used there, to make testsets more replicable.

This is a draft at the moment because it needs adding tests and docs, but I'm saving my progress so far.  To give you a taster of what this PR enables:
```
julia> using Random, Test

julia> @testset begin
           @test rand() == 0
       end;
test set: Test Failed at REPL[2]:2
  Expression: rand() == 0
   Evaluated: 0.559472630416976 == 0

Stacktrace:
 [1] top-level scope
   @ REPL[2]:2
 [2] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1713 [inlined]
 [3] macro expansion
   @ REPL[2]:2 [inlined]
 [4] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:679 [inlined]
Test Summary: | Fail  Total  Time
test set      |    1      1  0.9s
ERROR: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
Random seed for this testset: Xoshiro(0x2e026445595ed28e, 0x07bb81ac4c54926d, 0x83d7d70843e8bad6, 0xdbef927d150af80b, 0xdbf91ddf2534f850)

julia> @testset seed=Xoshiro(0x2e026445595ed28e, 0x07bb81ac4c54926d, 0x83d7d70843e8bad6, 0xdbef927d150af80b, 0xdbf91ddf2534f850) begin
           @test rand() == 0.559472630416976
       end;
Test Summary: | Pass  Total  Time
test set      |    1      1  0.0s
```
This also works with nested testsets, and testsets on for loops:
```
julia> @testset seed=Xoshiro(0xc380f460355639ee, 0xb39bc754b7d63bbf, 0x1551dbcfb5ed5668, 0x71ab5a18fec21a25, 0x649d0c1be1ca5436) "Outer" begin
           @test rand() == 0.0004120194925605336
           @testset seed=Xoshiro(0xee97f5b53f7cdc49, 0x480ac387b0527d3d, 0x614b416502a9e0f5, 0x5250cb36e4a4ceb1, 0xed6615c59e475fa0) "Inner: $(i)" for i in 1:10
               @test rand() == 0.39321938407066637
           end
       end;
Test Summary: | Pass  Total  Time
Outer         |   11     11  0.0s
```

Being able to see what was the seed inside a testset and being able to set it afterwards should make replicating test failures which only depend on the state of the RNG much easier to debug.

### CODE REVIEW

**Review by IanButterworth — COMMENTED** [review]
Printing the seed is clearly helpful, but it seems a bit too prominent in the messaging being right at the bottom, IMO. Especially given that it's always printed whether or not randomness is involved.

Could it be placed higher up, in the testset report table or around the
```
test set: Test Failed at REPL[2]:2
  Expression: rand() == 0
   Evaluated: 0.559472630416976 == 0
 ```
 
 Also I think the PR title should highlight that this adds the `seed` arg too.

**Comment by giordano** [comment]
> Especially given that it's always printed whether or not randomness is involved.

I took inspiration from [`Base.runtests`](https://docs.julialang.org/en/v1/stdlib/Test/#Base.runtests) which also always prints the seed.  It's hard to know in advance whether it'll be helpful, but it's an information hard to retrieve when needed.

> or around the
> ```
> test set: Test Failed at REPL[2]:2
>   Expression: rand() == 0
>    Evaluated: 0.559472630416976 == 0
>  ```

I think that'd be very misleading, besides increasing the noise:

* the seed is a global property of the testset, not of an individual `@test`: the RNG state could have changed in the meantime, and the user may have also independently changed the seed within a testset, both situations making the print next to a single `@test` failure meaningless
* if there are multiple failures within a `@testset` the seed would be printed multiple times instead of just once.

**Comment by IanButterworth** [comment]
I believe this currently only prints the seed for the outmost testset? Which in most cases will be a generic package testset, so not particularly helpful at minimizing a reproducer.

**Comment by giordano** [comment]
> I believe this currently only prints the seed for the outmost testset?

If you're referring to the case
```
julia> @testset "Outer" begin
           @test true
           @testset "Inner: $(i)" for i in 1:10
               @test false
           end
       end;
```
it'll print the seed of the failing testset, which is the inner one, same for each iteration, which is also the same as the outer one: by default the seed is reset at the entry of all testsets.

> so not particularly helpful at minimizing a reproducer.

Not true, as explained above.  The way I prepared the [example of nested testsets in the OP](https://github.com/JuliaLang/julia/pull/56260#issue-2601010382), also used in the tests of this PR, was exactly by making fail a test and get its seed printed.

**Comment by IanButterworth** [comment]
Great. Could you share an example of what that nested example error messaging looks like?

**Comment by giordano** [comment]
For a script like
```julia
@testset "outer" begin
    @test 1 == rand()
    @testset "inner" for i in 1:2
        @test 0 == rand()
    end
end
```
the output would be
```
outer: Test Failed at /tmp/foo.jl:2
  Expression: 1 == rand()
   Evaluated: 1 == 0.716232669101837

Stacktrace:
 [1] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ /tmp/foo.jl:2 [inlined]
 [3] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1752 [inlined]
 [4] top-level scope
   @ /tmp/foo.jl:2
inner: Test Failed at /tmp/foo.jl:4
  Expression: 0 == rand()
   Evaluated: 0 == 0.716232669101837

Stacktrace:
 [1] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ /tmp/foo.jl:4 [inlined]
 [3] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1841 [inlined]
 [4] macro expansion
   @ /tmp/foo.jl:3 [inlined]
 [5] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1752 [inlined]
 [6] top-level scope
   @ /tmp/foo.jl:2
inner: Test Failed at /tmp/foo.jl:4
  Expression: 0 == rand()
   Evaluated: 0 == 0.716232669101837

Stacktrace:
 [1] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ /tmp/foo.jl:4 [inlined]
 [3] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1841 [inlined]
 [4] macro expansion
   @ /tmp/foo.jl:3 [inlined]
 [5] macro expansion
   @ ~/repo/julia/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1752 [inlined]
 [6] top-level scope
   @ /tmp/foo.jl:2
Test Summary: | Fail  Total  Time
outer         |    3      3  0.0s
  inner       |    1      1  0.0s
  inner       |    1      1  0.0s
ERROR: LoadError: Some tests did not pass: 0 passed, 3 failed, 0 errored, 0 broken.
Random seed for this testset: Xoshiro(0xf5732468b1b480c6, 0x5fb6e91b080a696b, 0x4b5f1f0ce9b0d71c, 0xa6b0d91b1e0f1213, 0x1c496ab82cb16f18)
```
And you can fix the test failure with
```
julia> @testset seed=Xoshiro(0xf5732468b1b480c6, 0x5fb6e91b080a696b, 0x4b5f1f0ce9b0d71c, 0xa6b0d91b1e0f1213, 0x1c496ab82cb16f18) "outer" begin
           @test 0.716232669101837 == rand()
           @testset "inner" for i in 1:2
               @test 0.716232669101837 == rand()
           end
       end;
Test Summary: | Pass  Total  Time
outer         |    3      3  0.0s
```
The innermost testset takes the same seed as the outer one (same behaviour as now) unless explicitly changed separately (for example if you don't care about it in the outermost testset):
```
julia> @testset "outer" begin
           @test true
           @testset seed=Xoshiro(0xf5732468b1b480c6, 0x5fb6e91b080a696b, 0x4b5f1f0ce9b0d71c, 0xa6b0d91b1e0f1213, 0x1c496ab82cb16f18) "inner" for i in 1:2
               @test 0.716232669101837 == rand()
           end
       end;
Test Summary: | Pass  Total  Time
outer         |    3      3  0.0s
```

**Comment by IanButterworth** [comment]
Ok. What about two failing testsets side by side inside the outer one, where the rng is advanced between them? I think they'd need different seeds?

**Comment by giordano** [comment]
The seed is the initial one, once you set it, the entire testset is reproducible (unless the user messes with the RNG separately):
```
julia> @testset begin
           @test rand() == 0
           @test rand() == 1
       end;
test set: Test Failed at REPL[7]:2
  Expression: rand() == 0
   Evaluated: 0.716232669101837 == 0

Stacktrace:
[..]
test set: Test Failed at REPL[7]:3
  Expression: rand() == 1
   Evaluated: 0.8170765284222054 == 1

Stacktrace:
[...]
Test Summary: | Fail  Total  Time
test set      |    2      2  0.0s
ERROR: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.
Random seed for this testset: Xoshiro(0xf5732468b1b480c6, 0x5fb6e91b080a696b, 0x4b5f1f0ce9b0d71c, 0xa6b0d91b1e0f1213, 0x1c496ab82cb16f18)

julia> @testset seed=Xoshiro(0xf5732468b1b480c6, 0x5fb6e91b080a696b, 0x4b5f1f0ce9b0d71c, 0xa6b0d91b1e0f1213, 0x1c496ab82cb16f18) begin
           @test rand() == 0.716232669101837
           @test rand() == 0.8170765284222054
       end;
Test Summary: | Pass  Total  Time
test set      |    2      2  0.0s
```

**Comment by IanButterworth** [comment]
I guess I'm not familiar-enough with how testset seeding works. I was expecting these random numbers to be different because of the `rand()` inbetween advancing the rng.
```
julia> @testset "Foo.jl" begin
       @testset "A" begin
           @test rand() == 0
       end
       rand() # consume from the rng
       @testset "B" begin
           @test rand() == 0
       end
       end
A: Test Failed at REPL[2]:3
  Expression: rand() == 0
   Evaluated: 0.43649682434505155 == 0

Stacktrace:
[...]
B: Test Failed at REPL[2]:7
  Expression: rand() == 0
   Evaluated: 0.43649682434505155 == 0

Stacktrace:
[...]
Test Summary: | Fail  Total  Time
Foo.jl        |    2      2  1.3s
  A           |    1      1  1.3s
  B           |    1      1  0.0s
ERROR: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.
Random seed for this testset: Random.Xoshiro(0x30ab5f2fdb422621, 0x0fdcee1703e8bed4, 0x8c6b65bba7203491, 0xa870774e4a827ce5, 0xb96e6943342ed3b5)
```

So, as you say the seed of the outermost testset is enough (if the rng hasn't been messed with).

My only remaining issue is that it feels suboptimal to give it the last word in the error. Would it be possible to do this:
```
Test Summary: | Fail  Total  Time
Foo.jl        |    2      2  1.3s
  A           |    1      1  1.3s
  B           |    1      1  0.0s
Random seed for this testset: Random.Xoshiro(0x30ab5f2fdb422621, 0x0fdcee1703e8bed4, 0x8c6b65bba7203491, 0xa870774e4a827ce5, 0xb96e6943342ed3b5)
<red>ERROR: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.</red>
```

**Comment by IanButterworth** [comment]
Actually, that's how `Base.runtests` shows it. Also can we show a single value like that to be more concise?
```
...
  | 2024-12-28 09:10:09 EST | threads                                         \|      129                     129   3m48.6s
  | 2024-12-28 09:10:09 EST | Distributed                                     \|       15                      15   7m41.5s
  | 2024-12-28 09:10:09 EST | gc                                              \|       56                      56   1m15.8s
  | 2024-12-28 09:10:09 EST | stress                                          \|      118                     118   1m40.6s
  | 2024-12-28 09:10:09 EST | FAILURE
  | 2024-12-28 09:10:09 EST |  
  | 2024-12-28 09:10:09 EST | The global RNG seed was 0x3d5666147dbcf4156907fb87d7ce9ca4.
  | 2024-12-28 09:10:09 EST |  
  | 2024-12-28 09:10:09 EST | Error in testset compileall:
  | 2024-12-28 09:10:09 EST | Test Failed at /cache/build/tester-demeter6-13/julialang/julia-master/julia-8152312357/share/julia/test/compileall.jl:6
  | 2024-12-28 09:10:09 EST | Expression: success(pipeline(`$(Base.julia_cmd()) --compile=all --strip-ir --output-o $(dir)/sys.o.a -e 'exit()'`, stderr = stderr))
```

**Comment by giordano** [comment]
> My only remaining issue is that it feels suboptimal to give it the last word in the error. 

Done.  I also added a note in the docstring to explain how seeds of nested testsets work (it's mainly explaining the current status)

**Review by IanButterworth — APPROVED** [review]
Great

File: stdlib/Test/test/runtests.jl [hunk 1]
```diff
@@ -1712,13 +1712,13 @@ end
...
-                      no-record   |    x     x      x       x      ?  \s*?s
-                      b           |    1                           1  \s*\d*.\ds
-                    ERROR: Some tests did not pass: 3 passed, 1 failed, 1 errored, 1 broken.
+                    Test Summary: \| Pass  Fail  Error  Broken  Total  Time
+                    outer         \|    3     1      1       1      6  \s*\d*.\ds
+                      a           \|    1                           1  \s*\d*.\ds
+                      custom      \|    1     1      1       1      4  \s*\?s
+                      no-record   \|    x     x      x       x      \?  \s*\?s
+                      b           \|    1                           1  \s*\d*.\ds
+                    Random seed of the outermost testset: .*
```
Comment (giordano) [inline stdlib/Test/test/runtests.jl:1721]: @Seelengrab this test introduced in #53215 was completely broken because the `|` were interpreted inside the regex as alternatives, so it was sufficient to match any of the alternatives to get the test to pass, writing total garbate (like the `ERROR` line which isn't even in the output, or the `?` symbols which actually have a meaning inside regex unless escaped) would be irrelevant for the purpose of matching.

Comment (Seelengrab) [reply stdlib/Test/test/runtests.jl:1721]: Whoops, thank you! The fix is good though.

File: stdlib/Test/src/Test.jl [hunk 2]
```diff
@@ -1717,9 +1752,11 @@ function testset_beginend_call(args, tests, source)
         # by wrapping the body in a function
         local default_rng_orig = copy(default_rng())
         local tls_seed_orig = copy(Random.get_tls_seed())
+        local tls_seed = isnothing(get_seed(ts)) ? set_seed!(ts, tls_seed_orig) : get_seed(ts)
         try
             # default RNG is reset to its state from last `seed!()` to ease reproduce a failed test
-            copy!(Random.default_rng(), tls_seed_orig)
+            copy!(Random.default_rng(), tls_seed)
```
Comment (Seelengrab) [inline stdlib/Test/src/Test.jl:1758]: It should be documented that the seed needs to be a copyable RNG, not something like `Random.RandomDevice` which can't be copied. Unfortunately, the only reliable way check for that is calling `copy` and seeing if it throws...

File: stdlib/Test/test/runtests.jl [hunk 3]
```diff
@@ -1753,3 +1753,18 @@ module M54082 end
         @test only(result) isa Test.Fail
     end
 end
+
+# Note: if the stream of numbers generated by the given RNG changes, then we'll need to
+# change the reference results as well and that's fine.
```
Comment (Seelengrab) [inline stdlib/Test/test/runtests.jl:1758]: Do these tests really need to test the numbers returned by the rng? I think it's sufficient to test that `rand() == rand(copy_of_rng_passed_to_testset)`, which would make these tests stable in face of changes of the RNG stream.

Comment (giordano) [reply stdlib/Test/test/runtests.jl]: Done.

File: stdlib/Test/src/Test.jl (hunk 2 above)
Comment (giordano) [reply stdlib/Test/src/Test.jl:1761]: Done, but I the way I see this option to be used is to reproduce failures observed on CI.  If someone wants to use a fancy RNG to make tests reproducible they should call `rand(rng)` anyway.

**Comment by giordano** [comment]
I renamed the option from `seed` to `rng`, because that's really an RNG object, not a seed.  Which also answers the question

> Also can we show a single value like that to be more concise?

No, unless you can invert the `Random.hash_seed` function https://github.com/JuliaLang/julia/blob/27ebbf01ccc44d78694516ff6daf55af65b7439b/stdlib/Random/src/Xoshiro.jl#L259-L260 What `Base.runtests` uses is a proper seed, what `@testset` uses is an RNG.

File: NEWS.md [hunk 4]
```diff
@@ -180,6 +180,15 @@ Standard library changes
 
 #### Test
 
+* A failing `DefaultTestSet` now prints to screen the random number generator (RNG) of the failed test, to help reproducing a stochastic failure which only depends on the state of the RNG.
+  It is also possible seed a test set by passing the `seed` keyword argument to `@testset`:
```
Comment (IanButterworth) [inline NEWS.md:184]:
```suggestion
  It is also possible seed a test set by passing the `rng` keyword argument to `@testset`:
```
Haven't checked for others

File: NEWS.md [hunk 5]
```diff
@@ -180,6 +180,15 @@ Standard library changes
 
 #### Test
 
+* A failing `DefaultTestSet` now prints to screen the random number generator (RNG) of the failed test, to help reproducing a stochastic failure which only depends on the state of the RNG.
+  It is also possible seed a test set by passing the `RNG` keyword argument to `@testset`:
```
Comment (IanButterworth) [inline NEWS.md:184]:
```suggestion
  It is also possible seed a test set by passing the `rng` keyword argument to `@testset`:
```

Don't think it's capitalized?

File: stdlib/Test/src/Test.jl (hunk 2 above)
Comment (Seelengrab) [reply stdlib/Test/src/Test.jl:1761]: 100% agreed in principle, but unfortunately not every package takes an RNG object as part of their API, even if they internally call `rand`. I've hit that exact "bug" in Supposition.jl too, which is exactly why I now seed the default RNG from the one I provide :) 

One case that this still doesn't (and can't) cover is when a library doesn't use the default RNG at all, but rather some other source of randomness (e.g. as happened [here](https://github.com/Seelengrab/Supposition.jl/issues/56#issuecomment-2530505150)). [Arpack](https://arpack.julialinearalgebra.org/stable/) for example uses  an RNG internally, but that one doesn't seem to be seedable from Julia, so even with the feature from this PR, failures involving this library are going to be non-deterministic.

**Review by IanButterworth — APPROVED** [review]
