### PR TITLE
Fix missing GC root

### LINKED ISSUE #32751: encountered unexpected error in runtime (Type inference)
Reported by @asinghvi17:
https://github.com/JuliaPlots/Makie.jl/issues/374
```
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type, got=<?#0x135b025d0::<circular reference @-1>>)
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:217
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:454
jl_type_error_rt at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:118
jl_f_apply_type at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:927
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:625
argtypes_to_type at ./compiler/typeutils.jl:46 [inlined]
abstract_call at ./compiler/abstractinterpretation.jl:838
abstract_call at ./compiler/abstractinterpretation.jl:636
abstract_eval_call at ./compiler/abstractinterpretation.jl:875
abstract_eval at ./compiler/abstractinterpretation.jl:945
typeinf_local at ./compiler/abstractinterpretation.jl:1202
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1258
typeinf at ./compiler/typeinfer.jl:12
typeinf_ext at ./compiler/typeinfer.jl:577
typeinf_ext at ./compiler/typeinfer.jl:608
jfptr_typeinf_ext_1.clone_1 at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2043 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2213 [inlined]
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_type_infer at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:209
jl_compile_method_internal at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1776
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2048 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2213
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:625
render at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:137
render_frame at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:88
#renderloop#36 at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:10
renderloop at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:2
#31 at ./task.jl:292
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:604
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type, got=<?#0x135b025d0::<circular reference @-1>>)
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:217
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:454
jl_type_error_rt at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:118
jl_f_apply_type at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:927
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:625
argtypes_to_type at ./compiler/typeutils.jl:46 [inlined]
abstract_call at ./compiler/abstractinterpretation.jl:838
abstract_call at ./compiler/abstractinterpretation.jl:636
abstract_eval_call at ./compiler/abstractinterpretation.jl:875
abstract_eval at ./compiler/abstractinterpretation.jl:945
typeinf_local at ./compiler/abstractinterpretation.jl:1202
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1258
typeinf at ./compiler/typeinfer.jl:12
typeinf_ext at ./compiler/typeinfer.jl:577
typeinf_ext at ./compiler/typeinfer.jl:608
jfptr_typeinf_ext_1.clone_1 at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2043 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2213 [inlined]
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_type_infer at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:209
jl_compile_method_internal at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1776
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2048 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2213
glViewport at /Users/anshul/.julia/packages/ModernGL/oi403/src/functionloading.jl:39
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:625
render at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:137
render_frame at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:88
#renderloop#36 at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:10
renderloop at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:2
#31 at ./task.jl:292
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:604
┌ Error: Error while rendering!
│   exception =
│    MethodError: Cannot `convert` an object of type Tuple{Core.Compiler.UseRef,Nothing} to an object of type Int32
│    Closest candidates are:
│      convert(::Type{T}, ::T) where T<:Number at number.jl:6
│      convert(::Type{T}, ::Number) where T<:Number at number.jl:7
│      convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23
│      ...
└ @ GLMakie ~/.julia/dev/GLMakie/src/rendering.jl:154
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type, got=Array{Any, (3,)}[
  Array{Any, (4,)}[
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=typeof(Base.get)(), actual=false), undef=false),
  Core.Compiler.VarState(typ=Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=:color, actual=false), undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=false, actual=false), undef=false)],
  Array{Any, (4,)}[
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=typeof(Base.get)(), actual=false), undef=false),
  Core.Compiler.VarState(typ=Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=:color, actual=false), undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=false, actual=false), undef=false)],
  Array{Any, (4,)}[
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=typeof(Base.get)(), actual=false), undef=false),
  Core.Compiler.VarState(typ=Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=:color, actual=false), undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=false, actual=false), undef=false)]])
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:217
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:454
jl_type_error_rt at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:118
jl_f_apply_type at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:927
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:625
tuple_tfunc at ./compiler/tfuncs.jl:1187
matching_cache_argtypes at ./compiler/inferenceresult.jl:98
InferenceResult at ./compiler/inferenceresult.jl:12 [inlined]
InferenceResult at ./compiler/inferenceresult.jl:12 [inlined]
typeinf_ext at ./compiler/typeinfer.jl:575
typeinf_ext at ./compiler/typeinfer.jl:608
jfptr_typeinf_ext_1.clone_1 at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2043 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2213 [inlined]
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_type_infer at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:209
jl_compile_method_internal at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1776
_jl_invoke at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2048 [inlined]
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2213
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:625
showerror at ./errorshow.jl:172
#656 at ./errorshow.jl:76
#with_output_color#704 at ./util.jl:365
with_output_color at ./util.jl:363
#showerror#655 at ./errorshow.jl:75
showvalue at ./none:0 [inlined]
#handle_message#2 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Logging/src/ConsoleLogger.jl:117
#handle_message at ./none:0
unknown function (ip: 0x156a4f342)
logging_error at ./logging.jl:339
unknown function (ip: 0x156a4f060)
macro expansion at ./logging.jl:322 [inlined]
#renderloop#36 at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:19
renderloop at /Users/anshul/.julia/dev/GLMakie/src/rendering.jl:2
#31 at ./task.jl:292
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1630 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:604
GC error (probable corruption) :
Allocations: 262669614 (Pool: 262621640; Big: 47974); GC: 220
Array{Any, (3,)}[
  Array{Any, (4,)}[
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=typeof(Base.get)(), actual=false), undef=false),
  Core.Compiler.VarState(typ=Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=:color, actual=false), undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=false, actual=false), undef=false)],
  Array{Any, (4,)}[
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=typeof(Base.get)(), actual=false), undef=false),
  Core.Compiler.VarState(typ=Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=:color, actual=false), undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=false, actual=false), undef=false)],
  Array{Any, (4,)}[
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=typeof(Base.get)(), actual=false), undef=false),
  Core.Compiler.VarState(typ=Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=:color, actual=false), undef=false),
  Core.Compiler.VarState(typ=Core.Compiler.Const(val=false, actual=false), undef=false)]]
0x12b565000: Queued root: 0x13ac5b490 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565018: Queued root: 0x1130c33f0 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565030: Queued root: 0x13ab97070 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565048: Queued root: 0x111bcac50 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565060: Queued root: 0x1127aa9f0 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565078: Queued root: 0x112aa25e0 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565090: Queued root: 0x1106b6980 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5650a8: Queued root: 0x13a37fb50 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5650c0: Queued root: 0x1106b6ae0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5650d8: Queued root: 0x10f9faee0 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5650f0: Queued root: 0x112aae730 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565108: Queued root: 0x1367dd960 :: 0x10f462e40 (bits: 3)
        of type Core.TypeMapEntry
0x12b565120: Queued root: 0x112da97f0 :: 0x10f4394a0 (bits: 3)
        of type Core.MethodTable
0x12b565138: Queued root: 0x112da9d80 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565150: Queued root: 0x111f13fb0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565168: Queued root: 0x1131c7c50 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565180: Queued root: 0x1108222f0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565198: Queued root: 0x11098ab40 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5651b0: Queued root: 0x10f63a990 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5651c8: Queued root: 0x1119d1d70 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5651e0: Queued root: 0x1119d2f90 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5651f8: Queued root: 0x113267ba0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565210: Queued root: 0x10f580110 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565228: Queued root: 0x1119d0c10 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b565240: Queued root: 0x11013fc30 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b565258: Queued root: 0x113455d30 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565270: Queued root: 0x1124bba70 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b565288: Queued root: 0x1124a4ac0 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5652a0: Queued root: 0x110184ff0 :: 0x10f462e40 (bits: 3)
        of type Core.TypeMapEntry
0x12b5652b8: Queued root: 0x110184d50 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b5652d0: Queued root: 0x110f9c2b0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5652e8: Queued root: 0x110f9f150 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565300: Queued root: 0x111d65780 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565318: Queued root: 0x1128b2100 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565330: Queued root: 0x1111a77d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565348: Queued root: 0x11116c4d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565360: Queued root: 0x1116b65e0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565378: Queued root: 0x110f98f40 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b565390: Queued root: 0x13a51aef0 :: 0x10f462e40 (bits: 3)
        of type Core.TypeMapEntry
0x12b5653a8: Queued root: 0x119771110 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5653c0: Queued root: 0x11352d5b0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5653d8: Queued root: 0x10f59f530 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5653f0: Queued root: 0x10f8a9950 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565408: Queued root: 0x1115263a0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565420: Queued root: 0x111710770 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565438: Queued root: 0x134d5b430 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565450: Queued root: 0x110f1b590 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565468: Queued root: 0x110c10e20 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565480: Queued root: 0x110fa06d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565498: Queued root: 0x11059ef50 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5654b0: Queued root: 0x110462f00 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5654c8: Queued root: 0x110f1c5d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5654e0: Queued root: 0x11121e7d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5654f8: Queued root: 0x10fc09450 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565510: Queued root: 0x10fa6df60 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565528: Queued root: 0x111149490 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565540: Queued root: 0x111149940 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565558: Queued root: 0x1111b6820 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565570: Queued root: 0x11117bd30 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565588: Queued root: 0x1105993e0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5655a0: Queued root: 0x110dd7f50 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5655b8: Queued root: 0x11084e100 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5655d0: Queued root: 0x11047f8b0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5655e8: Queued root: 0x111bffb40 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565600: Queued root: 0x111fa6490 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565618: Queued root: 0x110798350 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565630: Queued root: 0x111022150 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565648: Queued root: 0x10fb84ad0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565660: Queued root: 0x110d96610 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565678: Queued root: 0x10f7bb1f0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565690: Queued root: 0x110798520 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5656a8: Queued root: 0x110f1b290 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5656c0: Queued root: 0x1101fd5c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5656d8: Queued root: 0x110588f40 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5656f0: Queued root: 0x111fa1d80 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565708: Queued root: 0x11101c310 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565720: Queued root: 0x110c07a20 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565738: Queued root: 0x111bff300 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565750: Queued root: 0x1101e5de0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565768: Queued root: 0x110d956e0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565780: Queued root: 0x1116d6090 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565798: Queued root: 0x10fd715e0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5657b0: Queued root: 0x10f5114c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5657c8: Queued root: 0x111680b60 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5657e0: Queued root: 0x110167e60 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5657f8: Queued root: 0x110697990 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565810: Queued root: 0x110697d70 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565828: Queued root: 0x110697c20 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565840: Queued root: 0x110697840 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565858: Queued root: 0x1106976f0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565870: Queued root: 0x110167c40 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565888: Queued root: 0x10fa14e00 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5658a0: Queued root: 0x1106972e0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5658b8: Queued root: 0x110697190 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5658d0: Queued root: 0x111a5aa90 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5658e8: Queued root: 0x10f59f050 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565900: Queued root: 0x10f8a9150 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565918: Queued root: 0x10fb1b9e0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565930: Queued root: 0x10fb1b8a0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565948: Queued root: 0x11068e690 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565960: Queued root: 0x11068e830 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565978: Queued root: 0x11068e550 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565990: Queued root: 0x11069d480 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5659a8: Queued root: 0x11069d340 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5659c0: Queued root: 0x11069ce10 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5659d8: Queued root: 0x11069c940 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5659f0: Queued root: 0x11069c800 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565a08: Queued root: 0x11069c2d0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565a20: Queued root: 0x1106b7580 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565a38: Queued root: 0x1116a6180 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565a50: Queued root: 0x111d378c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565a68: Queued root: 0x111743ff0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565a80: Queued root: 0x111d32c80 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565a98: Queued root: 0x1116a61e0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565ab0: Queued root: 0x1116a6310 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565ac8: Queued root: 0x1308f6010 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b565ae0: Queued root: 0x1197b0e50 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b565af8: Queued root: 0x111d6c210 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565b10: Queued root: 0x10fe1b8e0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565b28: Queued root: 0x10fc15b20 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565b40: Queued root: 0x110168ad0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565b58: Queued root: 0x110698750 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565b70: Queued root: 0x110698b60 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565b88: Queued root: 0x110698a10 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565ba0: Queued root: 0x110698600 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565bb8: Queued root: 0x1106984b0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565bd0: Queued root: 0x10fe1b7b0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565be8: Queued root: 0x10fe1b680 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565c00: Queued root: 0x10fe1b5e0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565c18: Queued root: 0x10fbc6ef0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565c30: Queued root: 0x1108bb4a0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565c48: Queued root: 0x110186d30 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565c60: Queued root: 0x111841800 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565c78: Queued root: 0x111d94c10 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565c90: Queued root: 0x1191e6450 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565ca8: Queued root: 0x110184d10 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565cc0: Queued root: 0x1124bf1f0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565cd8: Queued root: 0x1124b17b0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565cf0: Queued root: 0x10f8c5660 :: 0x10f439290 (bits: 3)
        of type Module
0x12b565d08: Queued root: 0x110f1df30 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565d20: Queued root: 0x1111586b0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565d38: Queued root: 0x111166d40 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565d50: Queued root: 0x111149fa0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565d68: Queued root: 0x11114a690 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565d80: Queued root: 0x110976e50 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565d98: Queued root: 0x110f97cb0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b565db0: Queued root: 0x111ab2800 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565dc8: Queued root: 0x1349f3300 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565de0: Queued root: 0x1116d5710 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565df8: Queued root: 0x1111aa980 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565e10: Queued root: 0x11116f560 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565e28: Queued root: 0x1119d8ba0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565e40: Queued root: 0x1109fc2b0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565e58: Queued root: 0x111d62cf0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565e70: Queued root: 0x110c8d4c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565e88: Queued root: 0x111d618e0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565ea0: Queued root: 0x110bfbd80 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565eb8: Queued root: 0x7fe498b28040 :: 0x10f439370 (bits: 3)
        of type Core.SimpleVector
0x12b565ed0: Queued root: 0x110b80140 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565ee8: Queued root: 0x1109f4ac0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565f00: Queued root: 0x111b766d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565f18: Queued root: 0x111cc9290 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565f30: Queued root: 0x111b6fcd0 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b565f48: Queued root: 0x10f9efac0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565f60: Queued root: 0x10fa6e770 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565f78: Queued root: 0x1109753c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565f90: Queued root: 0x1129376c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565fa8: Queued root: 0x11126c9d0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565fc0: Queued root: 0x110df2e60 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565fd8: Queued root: 0x111e3a970 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b565ff0: Queued root: 0x138cd4b90 :: 0x10f439370 (bits: 3)
        of type Core.SimpleVector
0x12b566008: Queued root: 0x138807970 :: 0x10f439370 (bits: 3)
        of type Core.SimpleVector
0x12b566020: Queued root: 0x11126c7c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566038: Queued root: 0x111244eb0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566050: Queued root: 0x110ded870 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b566068: Queued root: 0x11097a670 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566080: Queued root: 0x1108fde10 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566098: Queued root: 0x1113eceb0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5660b0: Queued root: 0x1113caac0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5660c8: Queued root: 0x112852240 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5660e0: Queued root: 0x10fb7b8c0 :: 0x10f4394a0 (bits: 3)
        of type Core.MethodTable
0x12b5660f8: Queued root: 0x10fb84ed0 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b566110: Queued root: 0x110f43480 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566128: Queued root: 0x1114ab580 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566140: Queued root: 0x11146ae40 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566158: Queued root: 0x7fe49a6dbe40 :: 0x10f439370 (bits: 3)
        of type Core.SimpleVector
0x12b566170: Queued root: 0x11352cc00 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566188: Queued root: 0x110eebcf0 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b5661a0: Queued root: 0x1104a90f0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5661b8: Queued root: 0x10fa04a10 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5661d0: Queued root: 0x10fa048c0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b5661e8: Queued root: 0x10fadfee0 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b566200: Queued root: 0x1172e2c70 :: 0x10f462e40 (bits: 3)
        of type Core.TypeMapEntry
0x12b566218: Queued root: 0x10fae0100 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b566230: Queued root: 0x135d84e20 :: 0x10f462e40 (bits: 3)
        of type Core.TypeMapEntry
0x12b566248: Queued root: 0x1306a2630 :: 0x10f4a6cf0 (bits: 3)
        of type Method
0x12b566260: Queued root: 0x13a0de450 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b566278: Queued root: 0x13a0de4d0 :: 0x10f4a7150 (bits: 3)
        of type Core.MethodInstance
0x12b566290: Queued root: 0x11146f6b0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5662a8: Queued root: 0x1116c9380 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5662c0: Queued root: 0x10f9f1730 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5662d8: Queued root: 0x119228fb0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5662f0: Queued root: 0x10fe08b50 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566308: Queued root: 0x1197572d0 :: 0x10f439d20 (bits: 3)
        of type Core.TypeMapLevel
0x12b566320: Queued root: 0x111d4ae00 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566338: Queued root: 0x110ed3fd0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566350: Queued root: 0x10f827d70 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566368: Queued root: 0x11296e6e0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566380: Queued root: 0x113423010 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566398: Queued root: 0x110f70c90 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5663b0: Queued root: 0x112a7c570 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5663c8: Queued root: 0x1111a44c0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5663e0: Queued root: 0x1111d9400 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b5663f8: Queued root: 0x111168dc0 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566410: Queued root: 0x1111da030 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566428: Queued root: 0x111169d90 :: 0x10f439ac0 (bits: 3)
        of type Array{Any, 1}
0x12b566440: Queued root: 0x119ed7f70 :: 0x10f4c8c70 (bits: 3)
        of type REPL.LineEdit.MIState
0x12b566458:  r-- Stack frame 0x1596a7360 -- 0 of 31 (direct)
Unknown pc 0x1096686d6 --- ABORTING !!!
```

It was happening quite regularly when I tried using 1.3 as the default, but now I'm not managing to reproduce it... I hope that @JeffBezanson or @vtjnash can already do something with the stack traces, while I'm trying to reproduce this.

### PR DESCRIPTION
**Pull request by Keno**
There is at least two bugs here:
1. We have a missing GC root
2. The analyzer didn't catch it

The second problem is perhaps the more interesting of the two. At first I thought, there may be a missing case in the analyzer, but it turns out the function is just too complicated, so while the analyzer knows the value is unrooted, it has a hard time seeing the use (an assignment to an array is only illegal if the analyzer knows the array on the LHS is an array of rooted locations), because `newargs` gets reassigned all over the places. To have at least some modicum of regression-safety, here, add a fake use that is easier for the analyzer to understand (and would have caught this issue), but it seems we're still very close to some sort of detectability threshold here.

Fixes #32751

### CODE REVIEW

**Comment by Keno** [comment]
It's a bit weird. Removing the `nargs == 2` check early in the function enables the analyzer to catch this. Would be worth revisiting on later LLVM and if not filing a bug report about. It should really be able to catch this.

File: src/julia_internal.h [hunk 1]
```diff
@@ -1062,6 +1062,16 @@ extern arraylist_t partial_inst;
...
 #endif // _COMPILER_GCC_
 
+#ifdef __clang_analyzer__
+  // Not a safepoint (so it dosn't free other values), but an artificial use.
+  // Usually this is unnecessary because the analyzer can see all real uses,
+  // but sometimes real uses are harder for the analyzer to see, or it may
+  // give up before it sees it, so this can be helpful to be explicit.
+  void JL_GC_ASSERT_LIVE(jl_value_t *v);
+#else
+  #define JL_GC_ASSERT_LIVE(x) (void)x;
```
Comment (JeffBezanson) [inline src/julia_internal.h]: Parens instead of the semicolon here?

Comment (Keno) [reply src/julia_internal.h]: yes
