### PR TITLE
Test: `@test_throws` add 3-arg form for testing exception type and message

### LINKED ISSUE #59113: Test `@test_throws` error type and partial message in one call
Currently I think you have to do two calls to test the type and partial message of an error.
```julia
@test_throws ErrorException error("error foo 1")
@test_throws r"error foo" error("error foo 1")
```
I think adding a 2 arg form like this would be generally useful
```julia
@test_throws ErrorException r"error foo" error("error foo 1")
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Closes https://github.com/JuliaLang/julia/issues/59113

Adds a way to test the error type and message matching in one call.

e.g.
```
    @test_throws ErrorException "error foo" error("error foo 1")
    @test_throws DomainError r"sqrt.*negative" sqrt(-1)
    @test_throws BoundsError "at index [2]" [1][2]
    @test_throws ErrorException ["error", "foo"] error("error foo bar")
```
rather than having to call each thing twice to test the error type and the message (where it's inconvenient to construct the whole error object).

### CODE REVIEW

File: stdlib/Test/src/Test.jl [hunk 1]
```diff
@@ -799,17 +799,29 @@ end
...
+a string, regular expression, or list of strings occurring in the displayed error message,
+a matching function, or a value.
+
 Note that `@test_throws` does not support a trailing keyword form.
 
 !!! compat "Julia 1.8"
     The ability to specify anything other than a type or a value as `exception` requires Julia v1.8 or later.
 
+!!! compat "Julia 1.13"
+    The three-argument form `@test_throws extype pattern expr` requires Julia v1.12 or later.
```
Comment (christiangnrd) [inline stdlib/Test/src/Test.jl:823]: Typo?
```suggestion
    The three-argument form `@test_throws extype pattern expr` requires Julia v1.13 or later.
```

Comment (icweaver) [reply stdlib/Test/src/Test.jl:823]: bump. Thanks for this really nice feature!

Comment (IanButterworth) [reply stdlib/Test/src/Test.jl:823]: Fixes are easier to approve as PRs :)

Comment (icweaver) [reply stdlib/Test/src/Test.jl:823]: For sure 👍🏾 https://github.com/JuliaLang/julia/pull/61431
