### PR TITLE
handle the condition in `in` when `step(r::AbstractRange)` equals 0 

### LINKED ISSUE #41784: `in(x, ::StepRangeLen)` fails when step is zero
Working on #41769, I found an error:

```julia
julia> r = StepRangeLen(3, 0, 5)
StepRangeLen(3, 0, 5)

julia> 3 in r
ERROR: DivideError: integer division error
Stacktrace:
 [1] div
   @ ./int.jl:278 [inlined]
 [2] div
   @ ./div.jl:257 [inlined]
 [3] div
   @ ./div.jl:302 [inlined]
 [4] fld
   @ ./div.jl:268 [inlined]
 [5] mod
   @ ./int.jl:270 [inlined]
 [6] in(x::Int64, r::StepRangeLen{Int64, Int64, Int64, Int64})
   @ Base ./range.jl:1346
 [7] top-level scope
   @ REPL[23]:1
```
This is because 3 is inside the range, and `step(r) == 0` makes `mod` on [this line](https://github.com/JuliaLang/julia/blob/master/base/range.jl#L1338) fail.

*Slightly* related is #41402, which deals with a completely different problem, but eventually sees division error in `mod`. Perhaps `mod` should check the modulo and throw a better error too?

### PR DESCRIPTION
**Pull request by thazhemadam**
Fixes #41784.

Before:

```julia
julia> r = StepRangeLen(3, 0, 5)
StepRangeLen(3, 0, 5)

julia> 3 in r
ERROR: DivideError: integer division error
Stacktrace:
 [1] div
   @ ./int.jl:278 [inlined]
 [2] div
   @ ./div.jl:257 [inlined]
 [3] div
   @ ./div.jl:302 [inlined]
 [4] fld
   @ ./div.jl:268 [inlined]
 [5] mod
   @ ./int.jl:270 [inlined]
 [6] in(x::Int64, r::StepRangeLen{Int64, Int64, Int64, Int64})
   @ Base ./range.jl:1346
 [7] top-level scope
   @ REPL[23]:1
```

After:
```julia
julia> StepRangeLen(3, 0, 5)
StepRangeLen(3, 0, 5)

julia> 3 in r
true

julia> 4 in r
false
```
```julia
julia> rc = StepRangeLen('a', 0, 5)
StepRangeLen('a', 0, 5)

julia> 'a' in rc
true

julia> 'b' in rc
false
```

### CODE REVIEW

**Comment by thazhemadam** [comment]
@martinholters could you please review this PR?

**Review by martinholters — COMMENTED** [review]
Thanks for picking this up. Mostly looks good to me, but let's take the time and see whether we can make it even better. BUT do take my suggestions with a grain of salt: I haven't actually tested them and might have missed something...

File: base/range.jl [hunk 1]
```diff
@@ -1371,11 +1371,11 @@ in(x::T, r::AbstractRange{T}) where {T} = _in_range(x, r)
 in(x::Integer, r::AbstractUnitRange{<:Integer}) = (first(r) <= x) & (x <= last(r))
 
 in(x::Real, r::AbstractRange{T}) where {T<:Integer} =
-    isinteger(x) && !isempty(r) && x >= minimum(r) && x <= maximum(r) &&
-        (mod(convert(T,x),step(r))-mod(first(r),step(r)) == 0)
+    isinteger(x) && !isempty(r) && ((iszero(step(r)) && (x == minimum(r))) || (x >= minimum(r) && x <= maximum(r) &&
+        (mod(convert(T,x),step(r))-mod(first(r),step(r)) == 0)))
```
[the remark this answers is not in the document]
Comment (thazhemadam) [reply base/range.jl]: You're right. That reads better too 👍🏼

File: base/range.jl [hunk 2]
```diff
@@ -1371,11 +1371,13 @@ in(x::T, r::AbstractRange{T}) where {T} = _in_range(x, r)
 in(x::Integer, r::AbstractUnitRange{<:Integer}) = (first(r) <= x) & (x <= last(r))
 
 in(x::Real, r::AbstractRange{T}) where {T<:Integer} =
-    isinteger(x) && !isempty(r) && x >= minimum(r) && x <= maximum(r) &&
-        (mod(convert(T,x),step(r))-mod(first(r),step(r)) == 0)
+    isinteger(x) && !isempty(r) &&
+    (iszero(step(r)) ? x == first(r) : (x >= minimum(r) && x <= maximum(r) &&
+    (mod(convert(T,x),step(r))-mod(first(r),step(r)) == 0)))
```
Comment (martinholters) [inline base/range.jl:1376]:
```suggestion
        (mod(convert(T,x),step(r))-mod(first(r),step(r)) == 0)))
```
(indented as already done for the `AbstractChar` case)

File: test/ranges.jl [hunk 3]
```diff
@@ -2112,3 +2112,16 @@ end
...
+    # test `in` when step equals 0
+    # test for Int
+    x = abs(rand(Int))
+    @test (x in StepRangeLen(x, 0, abs(rand(Int)))) == true
+    @test ((x - 1) in StepRangeLen(x, 0, abs(rand(Int)))) == false
+
+    # test for Char
+    x = rand(Char)
+    @test (x in StepRangeLen(x, 0, abs(rand(Int)))) == true # true case
+    @test ((x - 1) in StepRangeLen(x, 0, abs(rand(Int)))) == false # false case
```
Comment (martinholters) [inline test/ranges.jl:2126]: AFAICT, `x` has a non-zero probability of being set to `'\0'` here for which `x-1` fails. Just pick an arbitrary, fixed `x`?
(And the remarks for the `Int` test case apply similarly, too, of course.)

File: test/ranges.jl [hunk 4]
```diff
@@ -2112,3 +2112,16 @@ end
 @test length(range(1, 100, length=big(100)^100)) == big(100)^100
 @test length(range(big(1), big(100)^100, length=big(100)^100)) == big(100)^100
 @test length(0 * (1:big(100)^100)) == big(100)^100
+
+@testset "issue #41784" begin
+    # test `in` when step equals 0
+    # test for Int
+    x = abs(rand(Int))
```
Comment (martinholters) [inline test/ranges.jl:2119]: Why the `abs` here? Shouldn't
```suggestion
    x = rand(Int)
```
work as well?

File: test/ranges.jl [hunk 5]
```diff
@@ -2112,3 +2112,16 @@ end
...
+    @test (x in StepRangeLen(x, 0, abs(rand(Int)))) == true
+    @test ((x - 1) in StepRangeLen(x, 0, abs(rand(Int)))) == false
```
Comment (martinholters) [inline test/ranges.jl:2121]:
```suggestion
    @test (x in StepRangeLen(x, 0, 0)) == false
    @test ((x - 1) in StepRangeLen(x, 0, rand(1:100))) == false
    @test ((x + 1) in StepRangeLen(x, 0, rand(1:100))) == false
```
for good measure

File: test/ranges.jl [hunk 6]
```diff
@@ -2112,3 +2112,16 @@ end
 @test length(range(1, 100, length=big(100)^100)) == big(100)^100
 @test length(range(big(1), big(100)^100, length=big(100)^100)) == big(100)^100
 @test length(0 * (1:big(100)^100)) == big(100)^100
+
+@testset "issue #41784" begin
+    # test `in` when step equals 0
+    # test for Int
+    x = abs(rand(Int))
+    @test (x in StepRangeLen(x, 0, abs(rand(Int)))) == true
```
Comment (martinholters) [inline test/ranges.jl:2120]: If the length is zero (probability is small but non-zero), this will fail.
```suggestion
    @test (x in StepRangeLen(x, 0, rand(1:100))) == true
```
instead?

**Review by martinholters — CHANGES_REQUESTED** [review]
Upon closer inspection, the tests need some adjustments.

File: test/ranges.jl (hunk 3 above)
Comment (thazhemadam) [reply test/ranges.jl:2126]: Ah, that's right. I set it to `x - 1` because I accounted for the probability of it overflowing, but ended up missing this. I'll just set it to some arbitrary value like you suggested instead!

File: test/ranges.jl (hunk 6 above)
Comment (thazhemadam) [reply test/ranges.jl:2120]: Ah, that's right too. I was trying to introduce as much randomness as I could but makes more sense!

**Review by martinholters — APPROVED** [review]
LGTM now, CI failures seem unrelated. Another pair of eyes would be appreciated, otherwise I'll merge in a few days.

**Comment by vtjnash** [comment]
@martinholters Please also check commit messages for correctness also when you merge code. This was not "Signed-off-by" the author (we also don't generally use that tag in our processes currently).

**Comment by martinholters** [comment]
Ah, sorry. Those went past me as "some meta data that Github will have gotten right", which of course they weren't.
