### PR TITLE
Avoid overflow in first/last (continue #45843)

### LINKED ISSUE #45842: `first` sometimes returns incorrect results when used with nonstandard indexing
The function `first(itr, n)` is defined to get the first `n` elements of the collection `itr`, or fewer elements if `itr` is not long enough.

It behaves properly with plain arrays:

```jl
julia> a = [2, 3, 4];

julia> first(a, typemax(Int))
3-element Vector{Int64}:
 2
 3
 4
```

However, it returns the wrong answer with offset arrays:

```jl
julia> using OffsetArrays

julia> b = OffsetArray(a, 2:4);

julia> first(b, typemax(Int))
Int64[]
```

The culprit is this “faster method for vectors”:

https://github.com/JuliaLang/julia/blob/bc9fdcef490f32c48e92fe93c373b2aa7076e55b/base/abstractarray.jl#L467-L471

The expression `begin + n - 1` overflows and becomes negative, causing the array to be incorrectly indexed with an empty index range.

```
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
  ```

### PR DESCRIPTION
**Pull request by jishnub**
Continue and close #45843. This fixes https://github.com/JuliaLang/julia/issues/45842, but doesn't work correctly for non-compliant array types such as a `StarWarsArray`. However, once you're not complying with the `AbstractArray` interface, all bets are off.

Theoretically, we may work around this failure by checking if the axis is an `AbstractUnitRange`, and calling the fallback method if it isn't. This still produces an incorrect answer as of now, but at least makes the result consistent. Currently, the answers are inconsistent (they're wrong in different ways).

Bearing this in mind, it might make sense to remove the `@inbounds` annotation in these two functions. This will turn the incorrect result for `StarWarsArrays` into an error (as `checkbounds` is not defined for a `Vector` axis), but might help avoid segfaults in certain cases. Benchmarking for simple cases, I don't see any performance difference without `@inbounds`.

### CODE REVIEW

File: base/abstractarray.jl [hunk 1]
```diff
@@ -488,7 +488,7 @@ first(itr, n::Integer) = collect(Iterators.take(itr, n))
 # Faster method for vectors
 function first(v::AbstractVector, n::Integer)
     n < 0 && throw(ArgumentError("Number of elements must be nonnegative"))
-    @inbounds v[begin:min(begin + n - 1, end)]
+    v[range(begin, length=min(n, length(v)))]
```
Comment (N5N3) [inline base/abstractarray.jl:491]: If we just want to avoid all possible overflow, `checked_length`/`checked_add`/`checked_sub` seems more intuitive? As `length` itself might have overflowed
```julia
julia> typemin(Int):typemax(Int) |> Base.checked_length
ERROR: OverflowError: 9223372036854775807 - -9223372036854775808 overflowed for type Int64
Stacktrace:
 [1] throw_overflowerr_binaryop(op::Symbol, x::Int64, y::Int64)
   @ Base.Checked .\checked.jl:163
 [2] checked_sub
   @ .\checked.jl:232 [inlined]
 [3] checked_length
   @ .\range.jl:719 [inlined]
 [4] |>(x::UnitRange{Int64}, f::typeof(Base.checked_length))
   @ Base .\operators.jl:907
 [5] top-level scope
   @ REPL[6]:1

julia> typemin(Int):typemax(Int) |> length
0
```

Comment (jishnub) [reply base/abstractarray.jl]: Updated now to use `checked_length`
