### PR TITLE
fix `exponent` and `top_set_bit` fallbacks  for `Integer`

### LINKED ISSUE #53887: generic methods for `top_set_bit` and `exponent` give wrong result
The method for `Base.top_set_bit` for general integers may give incorrect results:
```
julia> using Base: top_set_bit

julia> top_set_bit(2^50)
51

julia> invoke(top_set_bit, Tuple{Integer}, 2^50)
50
```
The reason is that inside
https://github.com/JuliaLang/julia/blob/b18d2cc7046bee7b4a03842d709236ac1c081305/base/intfuncs.jl#L706
the added `1` may get lost due to the limited floating-point precision used by `log2`.

All integer types from `Base` except for `Bool` have dedicated methods for `top_set_bit`,
```
julia> methods(top_set_bit)
# 3 methods for generic function "top_set_bit" from Base:
 [1] top_set_bit(x::BigInt)
     @ Base.GMP gmp.jl:608
 [2] top_set_bit(x::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8})
     @ int.jl:509
 [3] top_set_bit(x::Integer)
     @ intfuncs.jl:668
```
so I don't know if this generic method is supposed to be relevant at all (beyond `Bool`). I stumbled upon this bug when using `top_set_bit` for large integers defined by [`BitIntegers.jl`](https://github.com/rfourquet/BitIntegers.jl).

The function `top_set_bit` was introduced in #47523. [This comment ](https://github.com/JuliaLang/julia/pull/47523#issuecomment-1309821317) sounds as if the function is not meant to be public. On the other hand, it does have a docstring. Since `top_set_bit` appears to be faster than `ndigits`,
```
julia> x = Int64(2)^60; @btime top_set_bit($x); @btime ndigits($x; base = 2, pad = 0);
  3.001 ns (0 allocations: 0 bytes)
  6.088 ns (0 allocations: 0 bytes)

julia> x = Int128(2)^120; @btime top_set_bit($x); @btime ndigits($x; base = 2, pad = 0);
  2.672 ns (0 allocations: 0 bytes)
  8.461 ns (0 allocations: 0 bytes)
```
it would be a pity if it were not considered public.

I used Julia 1.10.0. The problem is still present in master.

### PR DESCRIPTION
**Pull request by adienes**
fixes https://github.com/JuliaLang/julia/issues/53887

### CODE REVIEW

File: base/math.jl [hunk 1]
```diff
@@ -980,6 +980,26 @@ function _exponent_finite_nonzero(x::T) where T<:IEEEFloat
...
 end
 
+function _ilog2_step(y::T, d::T, s) where {T<:Integer}
+    if fld(y, d) ≥ d
+        y, n = _ilog2_step(y, d*d, s+s)
+    else
+        n = 0
+    end
+    if y ≥ d
+        y = fld(y, d)
```
Comment (oscardssmith) [inline base/math.jl]: is the compiler figurign out that d is a power of 2?

Comment (adienes) [reply base/math.jl]: I don't think so. but it wasn't clear to me what the contract of `Integer` is. `fld` seemed like a safer bet  generically than `>>`

Comment (oscardssmith) [reply base/math.jl]: IMO, `>>` would be better. It should be as easy to support for integers (they can always implement it with `fld` if they want)

**Comment by barucden** [comment]
Question: We have `leading_zeros(x::Integer)`. Wouldn't it simplify the implementation of `exponent`? `exponent = number_of_bits - number_of_leading_zeros - 1`?

It wouldn't help for `exponent(::BigInt)`, but we could have a specialized method for that (and there is `Base.GMP.MPZ.sizeinbase`).

**Comment by adienes** [comment]
I think the docstring lies --- `leading_zeros` is only defined for `BitInteger` not `Integer` (which makes sense)
```
"""
    leading_zeros(x::Integer)::Integer

Number of zeros leading the binary representation of `x`.

# Examples
'''jldoctest
julia> leading_zeros(Int32(1))
31
'''
"""
leading_zeros(x::BitInteger) = (ctlz_int(x) % Int)::Int
```

however, it is a good point that `exponent(::BitInteger)` could use this.

File: base/gmp.jl [hunk 2]
```diff
@@ -605,10 +605,18 @@ Number of ones in the binary representation of abs(x).
 """
 count_ones_abs(x::BigInt) = iszero(x) ? 0 : MPZ.mpn_popcount(x)
 
+_bit_magnitude(x::BigInt) = x.size * sizeof(Limb) << 3 - leading_zeros(GC.@preserve x unsafe_load(x.d, x.size))
```
Comment (barucden) [inline base/gmp.jl:609]: Isn't this function equivalent to `MPZ.sizeinbase(x, 2)`? The [MPZ docs](https://gmplib.org/manual/Miscellaneous-Integer-Functions#index-mpz_005fsizeinbase) say 
> It will be noted that mpz_sizeinbase(op,2) can be used to locate the most significant 1 bit in op, counting from 1.

Comment (adienes) [reply base/gmp.jl:609]: yes, it looks like it is. I'm not sure which would be better to use though, so this currently is closer to status quo

Comment (oscardssmith) [reply base/gmp.jl:609]: I think this version may be incorrect since IIUC `BigInt`s can have leading zero limbs.

Comment (adienes) [reply base/gmp.jl:609]: are you sure? I think there are several other places throughout `Base` it is assumed that nonzero `x.size` points to the largest nonzero limb, e.g. in `prod`, `hash`, and float conversion

Comment (oscardssmith) [reply base/gmp.jl:609]: I'm not sure.

**Comment by adienes** [comment]
specifics for triage:

* should `exponent` be considered as a "float-only" algorithm, or should it match its current docstring, which would require that sometimes `exponent(x) != exponent(float(x))`
* can `BigInt` have leading zero limbs?

File: base/gmp.jl (hunk 2 above)
Comment (LilithHafner) [reply base/gmp.jl:609]:
```suggestion
"UB if x <= 0"
_bit_magnitude(x::BigInt) = x.size * sizeof(Limb) << 3 - leading_zeros(GC.@preserve x unsafe_load(x.d, x.size))
```
size represents the sign of the int, so worth noting that this us UB (unsafe_load out of bounds) on negatives.

**Comment by adienes** [comment]
posterity: triage agrees with the bugfix but wants more hazard signs around the `unsafe_load` for malformed inputs now that it's in its own function

**Review by oscardssmith — APPROVED** [review]
