### PR TITLE
Restrict lfact to the domain of factorial

### LINKED ISSUE #21318: lfact(x) incorrectly evaluates to 0 for negative x
`lfact(x)`, the logarithmic factorial of `x`, gives the wrong answers for negative values of `x`.

Consider for example (-3)! = Γ(-2). Computing `factorial(-3)` raises a `DomainError`, as does `gamma(-2)`. However, `exp(lfact(-3)) == 1.0`, which is wrong:

```jl
julia> lfact(-3)
0.0

julia> exp(lfact(-3)) # = (-3)! = Γ(-2)
1.0

julia> factorial(-3)
ERROR: DomainError:
Stacktrace:
 [1] factorial_lookup(::Int64, ::Array{Int64,1}, ::Int64) at ./combinatorics.jl:30
 [2] factorial(::Int64) at ./combinatorics.jl:39

julia> gamma(-2.0)
ERROR: DomainError:
Stacktrace:
 [1] nan_dom_err at ./math.jl:299 [inlined]
 [2] gamma(::Float64) at ./special/gamma.jl:3
```

The fix should be a simple correction to the one-line definition:

```jl
lfact(x::Real) = (x<=1 ? zero(float(x)) : lgamma(x+oneunit(x)))
```

(also the domain of `lfact` is wrong - it should be consistent with `factorial`.)

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #21318

Currently `lfact` accepts any real number, whereas `factorial` accepts only nonnegative integers. This reconciles the two by similarly restricting `lfact` to nonnegative integers.

Technically this is a breaking change, since for example `lfact(-3.0)` will throw an error where it did not before.

### CODE REVIEW

**Review by jiahao — APPROVED** [review]
lgtm

**Comment by stevengj** [comment]
Why do we even have this function? Isn't lgamma sufficient?

**Comment by ararslan** [comment]
Perhaps, though `lfact` is rather convenient, since using `lgamma` for the same purpose requires knowing or remembering the factorial/gamma function relationship. Based on a GitHub search for `lfact` in Julia code, it's being used in over 100 repositories.

**Comment by jiahao** [comment]
I encountered this use case when implementing [Fisher's exact test](https://en.wikipedia.org/wiki/Fisher%27s_exact_test) for myself. In a formula with lots of binomial coefficients it gets tiresome to mentally rewrite `logfact(x)` into `loggamma(x+1)` 9 times in just one formula. And as @ararslan points out, it's used by many other packages.

**Comment by stevengj** [comment]
If we restrict it to integers, should we use a look-up table to accelerate it for small values of n, e.g. n < 256?

**Comment by jiahao** [comment]
At least in my use case, I'm handling integers which aren't limited to n < 256 and I suspect that it would be true of many use cases where `factorial` is not being used explicitly. I don't have a good sense of what are good values to precompute.

**Comment by ararslan** [comment]
Bettering the performance is somewhat beyond my intended scope for this PR, which was merely to fix the linked issue. I'd be happy to address performance in a future PR though.

Using a lookup table for small _n_ seems okay to me, but I think Jiahao has a good point that one of the primary use cases for `lfact` is for situations where `factorial` would otherwise overflow, so a lookup for small _n_ might not be that useful. Perhaps it would be better for larger _n_, but I similarly don't have a good sense for which values should be precomputed.

**Comment by stevengj** [comment]
`factorial` overflows for `n>20` with `Int64`, so a 256-element lookup table would go well beyond this.

Of course, if we are adding a lookup table we might as well add it to `lgamma(n::Integer)` instead of in `lfact`

**Comment by stevengj** [comment]
It just seems weird to have an API function just to add one to an argument.

**Comment by ararslan** [comment]
Well, we have `factorial`, which could similarly just be `Int(gamma(x-1))`. Knowing the identity *x*! = Γ(*x*-1) shouldn't be required for using factorials, IMO.

File: base/special/gamma.jl [hunk 1]
```diff
@@ -27,9 +27,9 @@ lgamma_r(x::Number) = lgamma(x), 1 # lgamma does not take abs for non-real x
 """
     lfact(x)
 
-Compute the logarithmic factorial of `x`
+Compute the logarithmic factorial of a nonnegative integer `x`.
```
Comment (stevengj) [inline base/special/gamma.jl]: Should have a cross-reference to `lgamma`

Comment (ararslan) [inline base/special/gamma.jl]: Good idea, thanks.

File: base/special/gamma.jl [hunk 2]
```diff
@@ -27,9 +27,10 @@ lgamma_r(x::Number) = lgamma(x), 1 # lgamma does not take abs for non-real x
...
+Equivalent to [`lgamma`](@ref) of `x + 1`.
```
Comment (stevengj) [inline base/special/gamma.jl]: , but `lgamma` extends this function to non-integer `x`.

Comment (ararslan) [inline base/special/gamma.jl]: Is this what you had in mind, @stevengj?

Comment (ararslan) [inline base/special/gamma.jl]: Oooh, nice. Thanks.

Comment (ararslan) [inline base/special/gamma.jl]: Once CI finishes I'll push the commit that contains that change with a `[ci skip]`. When this is merged, it should be squashed and the skip should be removed.

**Comment by ararslan** [comment]
The previous commit passed CI, the most recent one trivially edits the docstring so I've skipped CI. `make check-whitespace` ran and passed locally.

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
@ararslan, how did you calculate that `lfact` is used in over 100 repositories?  I grepped all registered Julia packages for `lfact(` calls, removing calls to `cholfact`, and I found only three packages using it: Celeste, Discretizers, and Distributions.

**Comment by ararslan** [comment]
I used GitHub search with the query `lfact language:julia`, which brings up 121 repositories. Not all are registered packages--some are end-user code.

**Comment by stevengj** [comment]
(@ararslan, I tried it, and the majority of the hits there are duplicates and false positives. e.g. there appear to be dozens of copies of the `gamma.jl` file from Base/SpecialFunctions.)

**Comment by ararslan** [comment]
I must have missed that--sorry about that.
