### PR TITLE
Fix #9618

### LINKED ISSUE #9618: DomainError in bigint_pow
`big(3)^big(9)^big(9)^big(9)`

gives

`
ERROR: DomainError
 in bigint_pow at gmp.jl:352
 in ^ at gmp.jl:356
`

This is for Julia 0.3.4 on 64-bit Arch Linux.

### PR DESCRIPTION
**Pull request by jiahao**
If y in (x::BigInt)^y exceeds typemax of Uint and |x|>=2, the result will
overflow. In this case, return OverflowError. Otherwise retain the
current behavior of returning a DomainError.

### CODE REVIEW

**Comment by matrixmorpheus** [comment]
I'm going to give you one piece of advice.  This needs tests.

**Comment by jiahao** [comment]
I realized that the logic in `big(x)^y` isn't quite right for large `y`. First, the check should be for `y > typemax(Culong)`; and second, `0^y` in this case is still computable (`== 0`).

Updated with tests.

File: test/numbers.jl [hunk 1]
```diff
@@ -2126,3 +2126,8 @@ end
 #Issue #5570
 @test map(x -> int(mod1(uint(x),uint(5))), 0:15) == [5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
 
+# Issue #9618: errors thrown by large exponentiations
+@test_throws DomainError big(2)^-(big(typemax(Uint))+1)
```
Comment (tkelman) [inline test/numbers.jl]: this should be UInt for 0.4

Comment (jiahao) [inline test/numbers.jl]: Thanks, fixed
