### PR TITLE
Generalize Bool parse method to AbstractString

### LINKED ISSUE #57: `parse(Bool, s::String3)` giving InexactError
```julia 
julia> using InlineStrings

julia> String3("0")
"0"

julia> parse(Bool, String3("0"))
ERROR: InexactError: Bool(10)

julia> parse(Bool, String(String3("0")))
false
```

is this expected to work? It was confusing hitting this when working with a DataFrame

### PR DESCRIPTION
**Pull request by quinnj**
Fixes https://github.com/JuliaStrings/InlineStrings.jl/issues/57.

We currently have a specialization for `parse(Bool, ::Union{String, SubString{String})` where `true` and `false` are parsed appropriately. The restriction to `Union{String, SubString{String}}`, however, means we don't get this behavior for other `AbstractString`s. In the linked issue above, for InlineStrings, we end up going through the generic integer parsing codepath which results in an `InexactError` when we try to do `Bool(10)`.

The proposal in this PR takes advantage of the fact that there is only the 2 comparisons where we do `_memcmp` that require the input string to be "dense" (in memory), and otherwise, we just do a comparison against a `SubString` of the input string.

Relatedly, I've wanted to introduce the concept of an abstrac type like:

```julia
abstract type MemoryAddressableString <: AbstractString
```

where the additional required interface would be being able to call `pointer(::MemoryAddressableString)`, since a lot of our string algorithms depend on doing these kind of pointer operations and hence makes it quite a pain to implement your own custom string type.

### CODE REVIEW

File: base/parse.jl [hunk 1]
```diff
@@ -202,10 +202,15 @@ function tryparse_internal(::Type{Bool}, sbuff::Union{String,SubString{String}},
     end
 
     len = endpos - startpos + 1
-    p   = pointer(sbuff) + startpos - 1
-    GC.@preserve sbuff begin
-        (len == 4) && (0 == _memcmp(p, "true", 4)) && (return true)
-        (len == 5) && (0 == _memcmp(p, "false", 5)) && (return false)
+    if sbuff isa Union{String, SubString{String}}
+        p   = pointer(sbuff) + startpos - 1
```
Comment (StefanKarpinski) [inline base/parse.jl:206]:
```suggestion
        p = pointer(sbuff) + startpos - 1
```

File: test/parse.jl [hunk 2]
```diff
@@ -41,6 +41,17 @@ Base.iterate(::Issue29451String, i::Integer=1) = i == 1 ? ('0', 2) : nothing
...
 @test parse(Int, Issue29451String()) == 0
 
+# https://github.com/JuliaStrings/InlineStrings.jl/issues/57
+struct InlineStringIssue57 <: AbstractString end
+Base.ncodeunits(::InlineStringIssue57) = 4
+Base.lastindex(::InlineStringIssue57) = 4
+Base.isvalid(::InlineStringIssue57, i::Integer) = 0 < i < 5
+Base.iterate(::InlineStringIssue57, i::Integer=1) = i == 1 ? ('t', 2) : i == 2 ? ('r', 3) : i == 3 ? ('u', 4) : i == 4 ? ('e', 5) : nothing
+import Base: ==
+==(::SubString{InlineStringIssue57}, x::String) = x == "true"
```
Comment (nickrobinson251) [inline test/parse.jl:51]: may as well overload this one in the same style (also slightly safer not to import `==` i guess)
```suggestion
Base.:(==)(::SubString{InlineStringIssue57}, x::String) = x == "true"
```

**Review by nickrobinson251 — COMMENTED** [review]
👍

**Comment by LilithHafner** [comment]
Possibly worth changing this `1` to `startpos`

https://github.com/JuliaLang/julia/blob/cee0a0494c70208b6cd5a32ccdf75d954a429870/base/parse.jl#L186

**Comment by mkitti** [comment]
@KristofferC could we back port this? Someone else just ran into this issue:
https://discourse.julialang.org/t/string7-and-bools-bug-or-feature/101188/5
