### PR TITLE
Inference-based promote_op is not pure (fix #19270)

### LINKED ISSUE #19270: Mysterious inference failure
This bug has appeared in the last few days on master. Depending on the order in which you call `f` and `g`, you get different results. In all cases, the `Any` result is unexpected and didn't happen before.

First call order:
```julia
julia> f{S,T}(x::S, y::T) = Base.promote_op(^, S, T)
f (generic function with 1 method)

julia> f(Nullable(0.0f0), Nullable(BigInt(0)))
Nullable{Any}

julia> g{S,T}(x::Nullable{S}, y::Nullable{T}) = Base.promote_op(^, S, T)
g (generic function with 1 method)

julia> g(Nullable(0.0f0), Nullable(BigInt(0)))
Float32
```

Second call order:
```julia
julia> g{S,T}(x::Nullable{S}, y::Nullable{T}) = Base.promote_op(^, S, T)
g (generic function with 1 method)

julia> g(Nullable(0.0f0), Nullable(BigInt(0)))
Any

julia> f{S,T}(x::S, y::T) = Base.promote_op(^, S, T)
f (generic function with 1 method)

julia> f(Nullable(0.0f0), Nullable(BigInt(0)))
Nullable{Float32}
```

### PR DESCRIPTION
**Pull request by p-zubieta**
Fix #19270. Also addresses https://github.com/JuliaLang/julia/pull/18642#discussion_r87088141

### CODE REVIEW

**Comment by ararslan** [comment]
Would it be possible to add a test to ensure that the linked issue is resolved?

**Comment by pabloferz** [comment]
> Would it be possible to add a test to ensure that the linked issue is resolved?

Sure (done).

File: test/nullable.jl [hunk 1]
```diff
@@ -387,3 +387,7 @@ end
 
 # issue #11675
 @test repr(Nullable()) == "Nullable{Union{}}()"
+
```
Comment (nalimilan) [inline test/nullable.jl]: Could you add a comment with the PR/issue number? That's really useful when you want to understand what is being tested exactly.

Otherwise, LGTM.

**Review by nalimilan — APPROVED** [review]
