### PR TITLE
fix spurious overflow for Float16(::Rational)

### LINKED ISSUE #52394: spurious overflow in Rational-to-Float16 conversion
It would be nice if this gave a correctly rounded result rather than overflowing:
```jl
julia> Float16(10^9 // (10^9 + 1)) # spurious overflow
NaN16

julia> Float16(Float64(10^9 // (10^9 + 1))) # correctly rounded
Float16(1.0)
```
It's not specific to `Float16` arithmetic, in principle, but that's where it shows up most easily since `Float32` and `Float64` cannot be overflowed by `Int`.

(I ran into this when implementing a recursive pairwise `mean` in https://github.com/JuliaLang/julia/issues/52365#issuecomment-1839681290)

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #52394.

*Update*: also fixes `Float32` for `UInt128`, since currently `Float32((typemax(UInt128)-0x01) // typemax(UInt128))` gives `Nan32`.

### CODE REVIEW

File: base/rational.jl [hunk 1]
```diff
@@ -145,6 +145,8 @@ function (::Type{T})(x::Rational{S}) where T<:AbstractFloat where S
     P = promote_type(T,S)
     convert(T, convert(P,x.num)/convert(P,x.den))::T
 end
+Float16(x::Rational{<:Union{Int16,Int32,Int64,Int128,UInt16,UInt32,UInt64,UInt128}}) =
```
Comment (andrewjradcliffe) [inline base/rational.jl:148]: `Int16` is not necessary here; see this [comment](https://github.com/JuliaLang/julia/issues/52394#issuecomment-1853158388).

However(!) `UInt128` can still produce spurious overflow since it can overflow `Float32`.
The easy fix is to add
```julia
Float32(x::Rational{UInt128}) = Float32(Float64(x))
```

File: base/rational.jl [hunk 2]
```diff
@@ -145,6 +145,8 @@ function (::Type{T})(x::Rational{S}) where T<:AbstractFloat where S
...
+    Float16(Float32(x)) # avoid spurious overflow (#52394)
```
Comment (stevengj) [inline base/rational.jl:149]:
```suggestion
 # avoid spurious overflow (#52394).  (Needed for UInt16 or larger;
 # we also include Int16 for consistency of accuracy.)
Float16(x::Rational{<:Union{Int16,Int32,Int64,UInt16,UInt32,UInt64}}) =
    Float16(Float32(x))
Float16(x::Rational{<:Union{Int128,UInt128}}) =
    Float16(Float64(x)) # UInt128 overflows Float32, include Int128 for consistency
```

File: test/float16.jl [hunk 3]
```diff
@@ -203,6 +203,9 @@ const minsubf16_32 = Float32(minsubf16)
 # issues #33076
 @test Float16(1f5) == Inf16
 
+# issue #52394
+@test Float16(10^8 // (10^9 + 1)) == convert(Float16, 10^8 // (10^9 + 1)) == Float16(0.1)
```
Comment (stevengj) [inline test/float16.jl:207]:
```suggestion
@test Float16(10^8 // (10^9 + 1)) == convert(Float16, 10^8 // (10^9 + 1)) == Float16(0.1)
@test Float16((typemax(UInt128)-1) // typemax(UInt128)) == Float16(1.0)
```

File: base/rational.jl [hunk 4]
```diff
@@ -145,6 +145,12 @@ function (::Type{T})(x::Rational{S}) where T<:AbstractFloat where S
     P = promote_type(T,S)
     convert(T, convert(P,x.num)/convert(P,x.den))::T
 end
+ # avoid spurious overflow (#52394).  (Needed for UInt16 or larger;
+ # we also include Int16 for consistency of accuracy.)
+Float16(x::Rational{<:Union{Int16,Int32,Int64,UInt16,UInt32,UInt64}}) =
+    Float16(Float32(x))
+Float16(x::Rational{<:Union{Int128,UInt128}}) =
+    Float16(Float64(x)) # UInt128 overflows Float32, include Int128 for consistency
```
Comment (stevengj) [inline base/rational.jl:153]:
```suggestion
Float16(x::Rational{<:Union{Int128,UInt128}}) =
    Float16(Float64(x)) # UInt128 overflows Float32, include Int128 for consistency
Float32(x::Rational{<:Union{Int128,UInt128}}) =
    Float32(Float64(x)) # UInt128 overflows Float32, include Int128 for consistency
```

File: test/float16.jl [hunk 5]
```diff
@@ -203,6 +203,10 @@ const minsubf16_32 = Float32(minsubf16)
...
+@test Float16((typemax(UInt128)-0x01) // typemax(UInt128)) == Float16(1.0)
```
Comment (stevengj) [inline test/float16.jl:208]:
```suggestion
@test Float16((typemax(UInt128)-0x01) // typemax(UInt128)) == Float16(1.0)
@test Float32((typemax(UInt128)-0x01) // typemax(UInt128)) == Float32(1.0)
```

**Review by fingolfin — APPROVED** [review]

File: base/rational.jl [hunk 6]
```diff
@@ -145,6 +145,14 @@ function (::Type{T})(x::Rational{S}) where T<:AbstractFloat where S
...
+Float32(x::Rational{<:Union{Int128,UInt128}}) =
+    Float32(Float64(x)) # UInt128 overflows Float32, include Int128 for consistency
```
Comment (vtjnash) [inline base/rational.jl:155]: Wouldn't these suffer from double-rounding accuracy loss? @oscardssmith

**Review by vtjnash — APPROVED** [review]

File: base/rational.jl (hunk 6 above)
Comment (oscardssmith) [reply base/rational.jl:155]: they would. Doing this properly is fairly hard though.

Comment (oscardssmith) [reply base/rational.jl:155]: Also worth noting that `Float16(num)/Float16(den)` also potentially has triple rounding.

Comment (fingolfin) [reply base/rational.jl:155]: Question is: is this problem worse than the problem this PR fixes? I.e. should we merge and improve this later, or should this wait until this PR does it "right" (whatever that means?)

Comment (oscardssmith) [reply base/rational.jl:155]: we should merge and improve later.

Comment (vtjnash) [reply base/rational.jl:155]: That was my thought as well, but want to confirm.

Comment (vtjnash) [reply base/rational.jl:155]: Would doing it "properly" be something like:
```julia
a = Float64(x)
b = Float32(a)
# check if we double-rounded in the wrong direction
if x > a && b < a && nextfloat(b) < a
    b = nextfloat(b)
elseif x < a && b > a && prevfloat(b) > a
    b = prevfloat(b)
end
return b
```

**Comment by nsajko** [comment]
Was there a point to merging this? This PR was just a quick fix compared to the thorough fix of #49749.

**Comment by oscardssmith** [comment]
Primarily that it was a quick fix, compared to the thorough fix of #49749 :). To be slightly more serious, I think we should merge the more thorough fix, but this was an improvement that was ready to merge first.

File: base/rational.jl (hunk 6 above)
Comment (stevengj) [reply base/rational.jl:155]: A example of a test case where double rounding gives a different result is:
```jl
julia> r = 12928845309018111//18014398509481984
12928845309018111//18014398509481984

julia> Float32(r) == Float32(Float64(r))
false
```
