### PR TITLE
Loosen signature in triangular solver from Strided- to AbstractMatrix.

### LINKED ISSUE #16196: L\b with cholesky L returning stackoverflow error
Reference #3630.

I have a matrix `K_` with dimensions 252x252. This matrix is positive semidefinite (a gram matrix from a mercer kernel). For numerical purposes I am trying not to use

```julia
> pinv(K_)*tsla

252-element DataArrays.DataArray{Float64,1}:
 0.289256
 0.283591
 0.265911
 0.284096
 0.281966
 0.286117
 0.295026
 0.290874
 0.28921 
 0.291895
 0.293412
 0.29149 
 0.286033
 ⋮       
 0.296586
 0.298044
 0.28968 
 0.293612
 0.294002
 0.301217
 0.300779
 0.302519
 0.299725
 0.298498
 0.293113
 0.288902
```
which does work. Because `K_` is positive semidefinite I am trying to compute the Cholesky factorization `K_ = L*L'` first and then solve with `L'\(L\tsla)`. This, however, returns a stack overflow error:

```julia
> L = chol(K_)
> L'\(L\tsla)

LoadError: StackOverflowError:
while loading In[92], in expression starting on line 2
```

What is interesting is that this is not happening in general. If I do, with bigger dimensions,

```julia
> A = randn(500,500)
> A = A'*A
> L = chol(A)
> b = randn(500,1)
> L\(L'\b) ≈ pinv(A)*b

true
```

we have the correct result.

I am attaching my specific arrays here, created with `writecsv()`
[matrices.zip](https://github.com/JuliaLang/julia/files/249396/matrices.zip)

Is there a reason why this should happen?

### PR DESCRIPTION
**Pull request by andreasnoack**
Remove many unnecessary type parameters. Fixes #16196

### CODE REVIEW

File: base/linalg/diagonal.jl [hunk 1]
```diff
@@ -106,6 +106,22 @@ end
...
+            B = A.data * D
+            for i = 1:size(A, 1)
+                B[i,i] = D.diag[i]
+            end
+            return $uplo(B)
+        end
+    end
+end
+(*)(A::AbstractTriangular, D::Diagonal) =
+    error("this method should never get called. Please make a bug report.")
```
Comment (tkelman) [inline base/linalg/diagonal.jl]: would it be better to define a general purpose fallback here?

File: base/linalg/triangular.jl [hunk 2]
```diff
@@ -1297,72 +1318,85 @@ for t in (UpperTriangular, UnitUpperTriangular, LowerTriangular, UnitLowerTriang
...
+#     end
+# end
+for f in (:A_mul_Bc, :A_mul_Bt, :Ac_mul_Bc, :At_mul_Bt)
     @eval begin
         ($f)(A::AbstractTriangular, B::AbstractTriangular) = ($f)(full(A), B)
     end
 end
 
 ## The general promotion methods
+for mat in (:AbstractVector, AbstractMatrix)
```
Comment (tkelman) [inline base/linalg/triangular.jl]: why not use a named union instead of this loop?

File: base/linalg/diagonal.jl (hunk 1 above)
Comment (andreasnoack) [inline base/linalg/diagonal.jl]: This was necessary to avoid an ambiguity warning but with https://github.com/JuliaLang/julia/pull/16125 it's not necessary anymore. I'm working on an updated version.

File: base/linalg/triangular.jl (hunk 2 above)
Comment (andreasnoack) [inline base/linalg/triangular.jl]: It was necessary to split the union to avoid ambiguity warnings but now that https://github.com/JuliaLang/julia/pull/16125 is merged, I'll revisit this and see if it can be simplified.

**Comment by andreasnoack** [comment]
Just rebased this PR. The test time for the `triangular.jl` goes from 360 seconds to 950 seconds. Second time takes about 30 seconds so it's still all about compilation. I don't know why this change makes the tests run so much slower.

**Comment by andreasnoack** [comment]
I found it. It was caused by the removal of the `At_mul_Bt` method. `A.'B.'` therefore ended up dispatching to `generic_matmatmul!` which is really slow to compile. On my machine, it takes more than 0.6 seconds to compile a single version of it and here it was done for four matrix types and seven element types which is `4*7*4*7*0.6 = 470` seconds.

I think I'll try to figure out how often we are calling `generic_matmatmul!` without a good reason. It might also be faster if we split up the function in smaller pieces.

File: base/linalg/triangular.jl [hunk 3]
```diff
@@ -1291,87 +1291,223 @@ function A_rdiv_Bt!(A::StridedMatrix, B::UnitLowerTriangular)
...
+        function ($f)(A::AbstractTriangular, B::AbstractTriangular)
+            TAB = typeof(zero(eltype(A))*zero(eltype(B)) + zero(eltype(A))*zero(eltype(B)))
+            BB = similar(B, TAB, size(B))
+            copy!(BB, B)
+            ($g)(convert(AbstractArray{TAB}, A), BB)
+        end
+    end
+end
+
+for mat in (:AbstractVector, AbstractMatrix)
```
Comment (tkelman) [inline base/linalg/triangular.jl]: why is only one of these quoted?

Comment (andreasnoack) [inline base/linalg/triangular.jl]: I didn't notice that. It doesn't give an error inside `@eval`.

**Comment by andreasnoack** [comment]
Ha. Compare https://travis-ci.org/JuliaLang/julia/jobs/131233006#L1653 to https://travis-ci.org/JuliaLang/julia/jobs/131231896#L1654

From 1045 to 487 seconds just by avoiding calls to `generic_matmatmul!` for `XTriangular`.

File: base/linalg/diagonal.jl [hunk 4]
```diff
@@ -104,9 +104,26 @@ end
...
+            B = A.data * D
+            for i = 1:size(A, 1)
+                B[i,i] = D.diag[i]
+            end
+            return $uplo(B)
+        end
+    end
+end
+(*)(A::AbstractTriangular, D::Diagonal) = error("this method should never be reached")
+(*)(D::Diagonal, A::AbstractTriangular) = error("this method should never be reached")
```
Comment (tkelman) [inline base/linalg/diagonal.jl]: are these only necessary to resolve ambiguity?

Comment (andreasnoack) [inline base/linalg/diagonal.jl]: Yes.

File: base/linalg/triangular.jl [hunk 5]
```diff
@@ -1291,87 +1291,262 @@ function A_rdiv_Bt!(A::StridedMatrix, B::UnitLowerTriangular)
...
 end
 
+for f in (:A_mul_B!, :A_ldiv_B!)
+    @eval begin
+        $f(A::UpperTriangular, B::UpperTriangular) =
+            UpperTriangular($f(A, triu!(B.data)))
+        $f(A::UnitUpperTriangular, B::UpperTriangular) =
+            UpperTriangular($f(A, triu!(B.data)))
+        $f(A::UpperTriangular, B::UnitUpperTriangular) =
+            UpperTriangular($f(A, triu!(B.data)))
```
Comment (tkelman) [inline base/linalg/triangular.jl]: I don't think this is correct, it uses the diagonals from `B.data` without setting them to 1 first.
```
 _/ |\__'_|_|_|\__'_|  |  Commit 1ce4ef0* (0 days old master)
|__/                   |  x86_64-w64-mingw32

julia> A = UpperTriangular(rand(5,5))
5×5 UpperTriangular{Float64,Array{Float64,2}}:
 0.817395  0.512978  0.151383  0.545986   0.680636
  ⋅        0.371017  0.326811  0.0279858  0.242921
  ⋅         ⋅        0.738791  0.0559057  0.272851
  ⋅         ⋅         ⋅        0.780668   0.0159331
  ⋅         ⋅         ⋅         ⋅         0.285675

julia> B = LinAlg.UnitUpperTriangular(rand(5,5))
5×5 Base.LinAlg.UnitUpperTriangular{Float64,Array{Float64,2}}:
 1.0  0.881164  0.0395179   0.265299  0.901799
 0.0  1.0       0.00318107  0.382759  0.909275
 0.0  0.0       1.0         0.525351  0.858504
 0.0  0.0       0.0         1.0       0.447239
 0.0  0.0       0.0         0.0       1.0

julia> B.data
5×5 Array{Float64,2}:
 0.169828  0.881164   0.0395179   0.265299  0.901799
 0.244341  0.701702   0.00318107  0.382759  0.909275
 0.952765  0.907991   0.68711     0.525351  0.858504
 0.924607  0.821667   0.173782    0.737463  0.447239
 0.22737   0.0277924  0.332617    0.311489  0.0209441

julia> C = LinAlg.A_mul_B!(A, B)
5×5 UpperTriangular{Float64,Array{Float64,2}}:
 0.138816  1.08022   0.137951  0.895375  1.59197
  ⋅        0.260344  0.225736  0.334339  0.63553
  ⋅         ⋅        0.507631  0.429353  0.664973
  ⋅         ⋅         ⋅        0.575714  0.349478
  ⋅         ⋅         ⋅         ⋅        0.0059832

julia> full(A) * full(B)
5×5 Array{Float64,2}:
 0.817395  1.39594   0.379941  1.51437   2.59939
 0.0       0.371017  0.410563  0.292349  0.705814
 0.0       0.0       0.738791  0.373108  0.783665
 0.0       0.0       0.0       0.780668  0.28876
 0.0       0.0       0.0       0.0       0.285675
```

Comment (andreasnoack) [inline base/linalg/triangular.jl]: True. Time to add some tests to `triangular.jl`.
