### PR TITLE
Make `normalize` work for `Number`s

### LINKED ISSUE #994: LinearAlgebra.normalize fails for a `Vector{Dual128}`
```julia
julia> using DualNumbers, LinearAlgebra

julia> v = [Dual(1.0)]
1-element Vector{Dual128}:
 1.0 + 0.0ɛ

julia> normalize(v)
ERROR: MethodError: no method matching __normalize!(::Vector{Dual128}, ::Dual128)

Closest candidates are:
  __normalize!(::AbstractArray, ::Real)
   @ LinearAlgebra ~/packages/julias/julia-1.9/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1795

Stacktrace:
 [1] normalize
   @ ~/packages/julias/julia-1.9/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1869 [inlined]
 [2] normalize(a::Vector{Dual128})
   @ LinearAlgebra ~/packages/julias/julia-1.9/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1866
 [3] top-level scope
   @ REPL[20]:1
```
The issue seems to be that
```julia
julia> Dual128 <: Real
false

julia> Dual128 <: Number
true
```
although this does have `norm` defined:
```julia
julia> norm(v)
1.0 + 0.0ɛ
```

### LINKED ISSUE #49148: LinearAlgebra.normalize fails for a `Vector{Dual128}`
```julia
julia> using DualNumbers, LinearAlgebra

julia> v = [Dual(1.0)]
1-element Vector{Dual128}:
 1.0 + 0.0ɛ

julia> normalize(v)
ERROR: MethodError: no method matching __normalize!(::Vector{Dual128}, ::Dual128)

Closest candidates are:
  __normalize!(::AbstractArray, ::Real)
   @ LinearAlgebra ~/packages/julias/julia-1.9/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1795

Stacktrace:
 [1] normalize
   @ ~/packages/julias/julia-1.9/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1869 [inlined]
 [2] normalize(a::Vector{Dual128})
   @ LinearAlgebra ~/packages/julias/julia-1.9/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1866
 [3] top-level scope
   @ REPL[20]:1
```
The issue seems to be that
```julia
julia> Dual128 <: Real
false

julia> Dual128 <: Number
true
```
although this does have `norm` defined:
```julia
julia> norm(v)
1.0 + 0.0ɛ
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Closes  JuliaLang/LinearAlgebra.jl#994.

@jishnub To make this work with DualNumbers.jl, one would need to add `typemax` and `prevfloat` methods for `Dual` numbers.

### CODE REVIEW

File: test/testhelpers/DualNumbers.jl [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+Base.promote_rule(::Type{Dual{T}}, ::Type{Dual{S}}) where {T,S} = Dual{promote_type(T, S)}
+
+Base.convert(::Type{Dual{T}}, x::Dual{T}) where {T} = x
+Base.convert(::Type{Dual{T}}, x::Dual) where {T} = Dual(convert(T, x.val), convert(T, x.eps))
+Base.convert(::Type{Dual{T}}, x::Real) where {T} = Dual(convert(T, x), zero(T))
+
+Base.float(x::Dual) = Dual(float(x.val), float(x.eps))
+# the folowing two are needed for normalize
+Base.typemax(x::Dual) = Dual(typemax(x.val), zero(x.eps))
+Base.prevfloat(x::Dual{<:AbstractFloat}) = prevfloat(x.val)
```
Comment (dkarrasch) [inline test/testhelpers/DualNumbers.jl:34]: I think these are the only "controversial" lines, as there is no precedence in `DualNumbers.jl`. Should `prevfloat` also return a `Dual`? I guess `typemax` should return a `Dual`, shouldn't it?

Comment (jishnub) [reply test/testhelpers/DualNumbers.jl:35]: Dual numbers seem to have an ordering defined based on their `value`, so the `typemax` definition makes sense, as it should return a `Dual`. `prevfloat` should ideally not return a `Dual`, as other functions like `floor` and `ceil` don't

Comment (dkarrasch) [reply test/testhelpers/DualNumbers.jl:35]: Thanks! Then I think this can be merged.
