### PR TITLE
Make eltype of range(::Integer; step, length) depend on typeof(step)

### LINKED ISSUE #37295: Return type of `range` with different keyword arguments
`range(start::T; step, length)` creates a `StepRange{T}`, but `range(::T; step, stop)` promotes the eltype:
```julia
julia> a = range(1, step=1//2, length=3)
1:1//2:2

julia> b = range(1, step=1//2, stop=2)
1//1:1//2:2//1
```
I would prefer if `range(1, step=1//2, length=3)` also created a `StepRange{Rational{Int},Rational{Int}}`, because a `StepRange{Int,Rational{Int}}` might not be usable:
```julia
julia> a[2]
ERROR: InexactError: Int64(3//2)
```

### PR DESCRIPTION
**Pull request by sostock**
Fixes #37295. This makes `range(1; step=1//2, length=3)` return a `StepRange{Rational{Int}}` instead of a `StepRange{Int}`.

Current behavior:
```julia
julia> range(1, step=1//1, length=5) # StepRange{Int, Rational{Int}}
1:1//1:5

julia> range(1, step=1//2, length=5)
ERROR: ArgumentError: StepRange{<:Integer} cannot have non-integer step
Stacktrace:
[...]
```
With this PR:
```julia
julia> range(1, step=1//1, length=5) # StepRange{Rational{Int}, Rational{Int}}
1//1:1//1:5//1

julia> range(1, step=1//2, length=5)
1//1:1//2:3//1
```

### CODE REVIEW

File: base/range.jl [hunk 1]
```diff
@@ -116,7 +116,7 @@ _range(a::T, step::T, ::Nothing, len::Integer) where {T <: AbstractFloat} =
 _range(a::T, step, ::Nothing, len::Integer) where {T} =
     _rangestyle(OrderStyle(T), ArithmeticStyle(T), a, step, len)
 _rangestyle(::Ordered, ::ArithmeticWraps, a::T, step::S, len::Integer) where {T,S} =
-    StepRange{T,S}(a, step, convert(T, a+step*(len-1)))
+    StepRange{typeof(a+0*step),S}(a, step, a+step*(len-1))
```
Comment (johnnychen94) [inline base/range.jl:119]: I think `promote_type(T, S)` is better here.

File: test/ranges.jl [hunk 2]
```diff
@@ -1692,3 +1692,8 @@ end
     @test @inferred(intersect(big(1):big(5), 3)) == 3:3
     @test @inferred(intersect(3, big(1):big(5))) == 3:3
 end
+
+@testset "eltype of range(::Integer; step::Rational, length) (#37295)" begin
+    @test range(1, step=1//2, length=3) == range(1//1, step=1//2, length=3)
+    @test eltype(range(1, step=1//2, length=3)) === Rational{Int}
+end
```
Comment (johnnychen94) [inline test/ranges.jl:1699]: might also need to test if `range(::Rational; step::Interger, length)` works.

File: base/range.jl (hunk 1 above)
Comment (sostock) [reply base/range.jl:119]: That won’t work correctly for ranges of `Char`s (`promote_type(Char, Int) == Any`). However, `a+0*step` should probably be replaced by `a+false*step` to avoid unnecessary widening.

File: test/ranges.jl (hunk 2 above)
Comment (sostock) [reply test/ranges.jl:1699]: I agree.

File: base/range.jl [hunk 3]
```diff
@@ -116,9 +116,9 @@ _range(a::T, step::T, ::Nothing, len::Integer) where {T <: AbstractFloat} =
 _range(a::T, step, ::Nothing, len::Integer) where {T} =
     _rangestyle(OrderStyle(T), ArithmeticStyle(T), a, step, len)
 _rangestyle(::Ordered, ::ArithmeticWraps, a::T, step::S, len::Integer) where {T,S} =
-    StepRange{T,S}(a, step, convert(T, a+step*(len-1)))
+    StepRange{typeof(a+false*step),S}(a, step, a+step*(len-1))
```
Comment (stevengj) [inline base/range.jl:119]: `iterate` uses `unsafe_getindex(r, i)` where `i::Int` here, so to be consistent should this be `0*step`?

Comment (sostock) [reply base/range.jl:119]: Good point, I will change it.

**Review by stevengj — APPROVED** [review]

File: base/range.jl (hunk 3 above)
Comment (sostock) [reply base/range.jl]: Actually, the `false` in `a+false*step` had a purpose, because this used to work:
```julia
julia> range(typemax(Int)//1, step=1, length=0)
ERROR: OverflowError: 9223372036854775807 + 1 overflowed for type Int64
[...]
```
I will create a new PR that adds the `false` back.

**Comment by sostock** [comment]
Unfortunately, this breaks at least one package (Unitful, cf. https://travis-ci.org/github/PainterQubits/Unitful.jl/jobs/748770136). Should this PR be reverted or Unitful be adapted to the new behavior?

**Comment by johnnychen94** [comment]
This seems like an intended change to me given that `1u"m" !== 1000u"mm"`.

```julia
julia> promote(1u"mm", 2u"m")
(1//1000 m, 2//1 m)
```

and it's just another case for

```julia
julia> first(range(1, step=1.0, length=4)) === 1
false
```
