### PR TITLE
Automatically up-convert eltype in SPQR

### LINKED ISSUE #673: Backslash with Float32 SparseMatrixCSC fails on qr call
```julia
julia> using SparseArrays

julia> A = spdiagm(0 => -ones(Float32, 4), 1=>ones(Float32,4))[1:end-1, :]
4×5 SparseMatrixCSC{Float32,Int64} with 8 stored entries:
  [1, 1]  =  -1.0
...

julia> b = rand(Float32, 4);

julia> A \ b
ERROR: MethodError: no method matching qr(::SparseMatrixCSC{Float32,Int64}, ::Type{Val{true}}; tol=3.0345731f-5)
Closest candidates are:
  qr(::AbstractArray{T,2}, ::Any) where T at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/qr.jl:363 got unsupported keyword argument "tol"
  qr(::SparseMatrixCSC; tol) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
  qr(::AbstractArray{T,2}) where T at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/qr.jl:369 got unsupported keyword argument "tol"
Stacktrace:
 [1] #qr#4(::Float32, ::typeof(qr), ::SparseMatrixCSC{Float32,Int64}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
 [2] qr(::SparseMatrixCSC{Float32,Int64}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
 [3] \(::SparseMatrixCSC{Float32,Int64}, ::Array{Float32,1}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SparseArrays/src/linalg.jl:1376
 [4] top-level scope at REPL[4]:1
```

This only fails for the float32 version for some reason... my initial digging couldn't find where it is going wrong.

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### LINKED ISSUE #33425: Backslash with Float32 SparseMatrixCSC fails on qr call
```julia
julia> using SparseArrays

julia> A = spdiagm(0 => -ones(Float32, 4), 1=>ones(Float32,4))[1:end-1, :]
4×5 SparseMatrixCSC{Float32,Int64} with 8 stored entries:
  [1, 1]  =  -1.0
...

julia> b = rand(Float32, 4);

julia> A \ b
ERROR: MethodError: no method matching qr(::SparseMatrixCSC{Float32,Int64}, ::Type{Val{true}}; tol=3.0345731f-5)
Closest candidates are:
  qr(::AbstractArray{T,2}, ::Any) where T at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/qr.jl:363 got unsupported keyword argument "tol"
  qr(::SparseMatrixCSC; tol) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
  qr(::AbstractArray{T,2}) where T at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/qr.jl:369 got unsupported keyword argument "tol"
Stacktrace:
 [1] #qr#4(::Float32, ::typeof(qr), ::SparseMatrixCSC{Float32,Int64}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
 [2] qr(::SparseMatrixCSC{Float32,Int64}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
 [3] \(::SparseMatrixCSC{Float32,Int64}, ::Array{Float32,1}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SparseArrays/src/linalg.jl:1376
 [4] top-level scope at REPL[4]:1
```

This only fails for the float32 version for some reason... my initial digging couldn't find where it is going wrong.

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by dkarrasch**
This intends to close JuliaLang/LinearAlgebra.jl#673, one way or another.

I realized that we do up-convert in the other two sparse factorizations, UMFPACK and CHOLMOD, and this is clearly documented. So one option is to do the same with SPQR. Another option that we discussed over at JuliaLang/LinearAlgebra.jl#673 is to throw an error message.

The previous line below the docstring was calling a non-existent method, so I moved the main workhorse below the docstring, adapted the conversion functions from UMFPACK, and added a "!!! note" (maybe it should be a compat annotation?).

### CODE REVIEW

File: stdlib/SuiteSparse/src/spqr.jl [hunk 1]
```diff
@@ -206,7 +189,43 @@ Column permutation:
...
+LinearAlgebra.qr(A::SparseMatrixCSC{<:Union{ComplexF16,ComplexF32}}; tol=_default_tol(A)) =
+    qr(convert(SparseMatrixCSC{ComplexF64}, A); tol=tol)
+LinearAlgebra.qr(A::Union{SparseMatrixCSC{T},SparseMatrixCSC{Complex{T}}};
+   tol=_default_tol(A)) where {T<:AbstractFloat} =
+    throw(ArgumentError(string("matrix type ", typeof(A), "not supported. ",
+    "Try qr(convert(SparseMatrixCSC{Float64/ComplexF64,Int}, A)) for ",
+    "sparse floating point QR using SPQR or qr(Array(A)) for generic ",
+    "dense QR.")))
+LinearAlgebra.qr(A::SparseMatrixCSC; tol=_default_tol(A)) = qr(float(A); tol=tol)
+# function LinearAlgebra.qr(A::SparseMatrixCSC; tol=_default_tol(A))
```
Comment (andreasnoack) [inline stdlib/SuiteSparse/src/spqr.jl]: Should this one be deleted?

**Review by andreasnoack — APPROVED** [review]
LGTM (just the question about the function that is commented out)

File: stdlib/SuiteSparse/src/spqr.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/SuiteSparse/src/spqr.jl]: Yes, this was just a placeholder in case we decide not to upconvert but to error. I'll delete this then and merge.

**Comment by dkarrasch** [comment]
I'll also add a short comment to the !!!note docstring, something like
```
!!! note
     `qr(A::SparseMatrixCSC)` uses the SPQR library that is part of SuiteSparse.
     As this library only supports sparse matrices with [`Float64`](@ref) or
     `ComplexF64` elements, `qr` converts `A` (as of Julia v1.4) into a copy that is of type
     `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}` as appropriate.
```
Or any other suggestion?
