### PR TITLE
deprecate cholfact[!](A, uplo)

### LINKED ISSUE #22187: cholfact[!] does not respect the uplo character
`cholfact` and `cholfact!` has an optional `uplo` input to only consider the upper/lower part of the matrix, but this is not taken into account when checking `ishermitian()`. For instance:

```julia
julia> A = [2. 1.; 0. 2.]
2×2 Array{Float64,2}:
 2.0  1.0
 0.0  2.0

julia> cholfact(A, :U)
ERROR: ArgumentError: matrix is not symmetric/Hermitian. This error can be avoided by calling cholfact(Hermitian(A)) which will ignore either the upper or lower triangle of the matrix.
Stacktrace:
 [1] cholfact(::Array{Float64,2}, ::Symbol) at ./linalg/cholesky.jl:344
```

This faulty behavior is actually also [tested(!)](https://github.com/JuliaLang/julia/blob/093115660130afc79d1eb09929bf9a0bba776822/test/linalg/cholesky.jl#L261-L263).

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix #22187

### CODE REVIEW

**Review by andreasnoack — APPROVED** [review]

File: base/deprecated.jl [hunk 1]
```diff
@@ -1350,6 +1350,14 @@ end
 @deprecate srand(filename::AbstractString, n::Integer=4) srand(read!(filename, Array{UInt32}(Int(n))))
 @deprecate MersenneTwister(filename::AbstractString)  srand(MersenneTwister(0), read!(filename, Array{UInt32}(Int(4))))
 
+# PR ??
```
Comment (tkelman) [inline base/deprecated.jl]: would save some future work if you'd be willing to add in a news entry now

Comment (fredrikekre) [inline base/deprecated.jl]: Sure thing. Just didn't know what PR number this would end up with.

Comment (fredrikekre) [inline base/deprecated.jl]: Done.

File: base/deprecated.jl [hunk 2]
```diff
@@ -1350,6 +1350,14 @@ end
 @deprecate srand(filename::AbstractString, n::Integer=4) srand(read!(filename, Array{UInt32}(Int(n))))
 @deprecate MersenneTwister(filename::AbstractString)  srand(MersenneTwister(0), read!(filename, Array{UInt32}(Int(4))))
 
+# PR #22188
+@deprecate cholfact!(A::StridedMatrix, uplo::Symbol, ::Type{Val{false}}) cholfact!(Hermitian(A, uplo), Val{false})
+@deprecate cholfact!(A::StridedMatrix, uplo::Symbol) cholfact!(Hermitian(A, uplo))
+@deprecate cholfact(A::StridedMatrix, uplo::Symbol, ::Type{Val{false}}) cholfact(Hermitian(A, uplo), Val{false})
+@deprecate cholfact(A::StridedMatrix, uplo::Symbol) cholfact(Hermitian(A, uplo))
+@deprecate cholfact!(A::StridedMatrix, uplo::Symbol, ::Type{Val{true}}; tol = 0.0) cholfact!(Hermitian(A, uplo), Val{true}, tol = tol)
+@deprecate cholfact(A::StridedMatrix, uplo::Symbol, ::Type{Val{true}}; tol = 0.0) cholfact(Hermitian(A, uplo), Val{true}, tol=tol)
```
Comment (Sacha0) [inline base/deprecated.jl]: Negligible, but inconsistent spacing around the keyword argument line to line? :)

File: test/linalg/cholesky.jl [hunk 3]
```diff
@@ -94,18 +91,12 @@ using Base.LinAlg: BlasComplex, BlasFloat, BlasReal, QRPivoted, PosDefException
         U = Bidiagonal([2,sqrt(eltya(3))],[-1],true) / sqrt(eltya(2))
         @test full(chol(S)) ≈ full(U)
 
-        #lower Cholesky factor
```
Comment (Sacha0) [inline test/linalg/cholesky.jl]: Comment worth preserving/revising?

Comment (fredrikekre) [inline test/linalg/cholesky.jl]: I thought it only applied to the tests which are now deprecated? Both `Hermitian(A, :U)` and `Hermitian(A, :L)` are tested in the tests just below.

File: base/deprecated.jl (hunk 2 above)
Comment (fredrikekre) [inline base/deprecated.jl]: Thanks, fixed

File: test/linalg/cholesky.jl (hunk 3 above)
Comment (Sacha0) [inline test/linalg/cholesky.jl]: My suggestion to preserve/revise the comment associated with that block was independent of whether that comment applies primarily or strictly to the deprecated tests: There is no other comment describing the surviving contents of that block, and having an up to date comment describing the remaining tests in that block would be worthwhile :).

Comment (fredrikekre) [inline test/linalg/cholesky.jl]: Makes sense! I will add something descriptive :)

Comment (Sacha0) [inline test/linalg/cholesky.jl]: Awesome! Thanks! :)

Comment (fredrikekre) [inline test/linalg/cholesky.jl]: Done! Moved around some things, I think it is clearer now.

Comment (Sacha0) [inline test/linalg/cholesky.jl]: If you mean that the comment added on line 61 should also apply to this block, perhaps move this block adjacent to the block to which that comment is attached (rather than leave those blocks separated by the block dedicated to Strang matrices)? Forty lines, paragraph breaks, and other comments interceding obscures the relationship :).

Comment (fredrikekre) [inline test/linalg/cholesky.jl]: Hmm, I confused myself. Actually, there is no reason not to merge the two blocks, I will do that.

Comment (fredrikekre) [inline test/linalg/cholesky.jl]: Ended up adding a comment instead.

**Comment by fredrikekre** [comment]
Rebased.

**Review by Sacha0 — APPROVED** [review]
Thanks @fredrikekre! :)
