### PR TITLE
Check channel state on iterate

### LINKED ISSUE #52974: `iterate` on `Channel` fails to throw errors, against docs
MWE:
```julia
julia> collect(walkdir("dsaasds"))
Tuple{String, Vector{String}, Vector{String}}[]
```

I believe this is a bug, per the docstring of `walkdir`, which promises:
>  If walkdir or stat encounters a IOError it will rethrow the error by default.

In the code above, it should raise:
```julia
julia> readdir("dsaasds")
ERROR: IOError: readdir("dsaasds"): no such file or directory (ENOENT)
```

The bug happens due to the following code in `walkdir`. The context is that `walkdir` returns a `Channel`, in the code called `chnl`:
```julia
try
    f(p) # a readdir call
catch err
    isa(err, IOError) || rethrow()
    try
        onerror(err) # this is throw(err)
    catch err2
        close(chnl, err2)
    end
    return
end
```
So this happens:
* `f(p)` raises an `IOError`
* `onerror(err)` occurs in the inner try block, throwing the error again
* This is caught by the second `catch` block, closing the channel with this error. This is wrong, because the error is never thrown

Here is another variation on the same bug. Here I have
```
.
└── bar
   └── <Permission denied (os error 13)>
```
(i.e. I have read access to `.` but not to `bar`). Then:
```julia
julia> w = walkdir(".");

julia> iterate(w)
((".", ["bar"], String[]), nothing)

julia> iterate(w) # returns nothing, but should throw

julia> collect(walkdir(".")) # somehow, throws here
ERROR: IOError: readdir("./bar"): permission denied (EACCES
```

### PR DESCRIPTION
**Pull request by jakobnissen**
Before, iterate on Channel would return `nothing` when the channel was closed, not checking if it was closed with an error.

Closes #52974

### CODE REVIEW

File: base/channels.jl [hunk 1]
```diff
@@ -619,6 +619,7 @@ function iterate(c::Channel, state=nothing)
             end
         end
     else
+        check_channel_state(c)
```
Comment (vtjnash) [inline base/channels.jl:622]: You could inline this implementation, or perhaps more easily, just delete the `isopen` check at the top and let `take!` handle everything (as it already implements everything necessary)

**Comment by jakobnissen** [comment]
Test failures appear to be spurious libgit connection issues.

I think this PR is good to go, modulo one decision: This PR's current behaviour is that `iterate` on a closed channel will not throw if the channel is not empty. The docs for `close` states that this is the case for `take!` and `fetch`, but does not mention `iterate`. Is this correct? Could the docs for `close` be expanded to mention `iterate`?

**Comment by jakobnissen** [comment]
Bump

**Review by quinnj — APPROVED** [review]
I like the change/fix/clean up here; I've been annoyed before that it always throws when done iterating.

**Comment by jakobnissen** [comment]
Bump

**Review by gbaraldi — APPROVED** [review]
