### PR TITLE
Fix #13823, add logabsdet for complex matrices

### LINKED ISSUE #13823: logabsdet for complex matrices
`logabsdet` is a function that returns `(log(abs(det(M))), sign(det(M))` but may provide increased accuracy and/or speed (and is less likely to overflow).  At the moment it [works only for real matrices](https://github.com/JuliaLang/julia/blob/40e16bf249a507e8cc4ab1c900de6e8302d56fba/base/linalg/lu.jl#L167-L190), but I believe it would be great if it were implemented also for complex matrices.

From glancing at the code (and earlier discussion at #3070), I see no reason it cannot work for complex matrices as well.  Note that julia's `sign` function is indeed implemented for complex numbers, so the interface can be exactly equivalent to the current one.

EDIT: ~~on the other hand, I believe `logdet` should only be implemented for real matrices, as is currently the case.~~  OK, apparently `logdet` is implemented for some complex matrices.

Thoughts?

CC @mishmash

### PR DESCRIPTION
**Pull request by kshyatt**
Following the discussion over at JuliaLang/LinearAlgebra.jl#277, I added `logabsdet` for `Complex` types. I changed the test a little bit to make sure the `sign`s will match (they are only ever not exactly the same for the complex matrices).

### CODE REVIEW

File: test/linalg/generic.jl [hunk 1]
```diff
@@ -22,11 +22,11 @@ for elty in (Int, Rational{BigInt}, Float32, Float64, BigFloat, Complex{Float32}
     debug && println("element type: $elty")
 
     @test_approx_eq logdet(A) log(det(A))
+    @test_approx_eq logabsdet(A)[1] log(abs(det(A)))
+    @test logabsdet(A)[2] ≈ sign(det(A))
```
Comment (tkelman) [inline test/linalg/generic.jl]: could this test exact equality for real and approx for complex?

Comment (kshyatt) [inline test/linalg/generic.jl]: It sure could!

**Comment by andreasnoack** [comment]
:+1:

**Comment by tkelman** [comment]
lgtm
