### PR TITLE
AMD Zen 3 CPU support (Fixes #45657)

### LINKED ISSUE #45657: Julia v1.8.0-rc1: support for znver3 (even though underlying LLVM13 supports is) is missing
This is with the official https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.0-rc1-linux-x86_64.tar.gz
```
$ /opt/julia/bin/julia --cpu-target znver2 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1 (2022-05-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> exit()
$ /opt/julia/bin/julia --cpu-target native
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1 (2022-05-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> exit()
$ /opt/julia/bin/julia --cpu-target znver3 
ERROR: Your CPU does not support the CX16 instruction, which is required by this version of Julia!  This is often due to running inside of a virtualized environment.  Please read https://docs.julialang.org/en/v1/devdocs/sysimg/ for more.
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-31
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 5950X 16-Core Processor
    CPU family:          25
    Model:               33
    Thread(s) per core:  2
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            0
    Frequency boost:     disabled
    CPU(s) scaling MHz:  67%
    CPU max MHz:         6017.8462
    CPU min MHz:         2200.0000
    BogoMIPS:            8050.09
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse
                         3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_p
                         state ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbn
                         oinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    8 MiB (16 instances)
  L3:                    64 MiB (2 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-31
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

### PR DESCRIPTION
**Pull request by LebedevRI**
I've omitted `invpcid` feature since it's clearly omitted for other CPU's.

It's a bit sad that the very same code
is being repeated in every project :/

Fixes https://github.com/JuliaLang/julia/issues/45657

### CODE REVIEW

**Comment by LebedevRI** [comment]
CC @yuyichao, thanks.

**Comment by vchuravy** [comment]
> It's a bit sad that the very same code is being repeated in every project

There is some community around archspec

**Comment by LebedevRI** [comment]
image
Yes, _please_, i was just about to ask for that :)

**Comment by LebedevRI** [comment]
One caveat that i'm observing here, is that specifying `JULIA_CPU_TARGET=native` in `Make.user`
produces bad sysimage:
```
$ ./usr/bin/julia --cpu-target znver3
ERROR: Unable to find compatible target in system image.
```
... but it works with `JULIA_CPU_TARGET=znver3`.

I guess it's expected?

File: src/processor_x86.cpp [hunk 1]
```diff
@@ -286,6 +288,7 @@ static constexpr CPUSpec<CPU, feature_sz> cpus[] = {
 
     {"znver1", CPU::amd_znver1, CPU::generic, 0, Feature::znver1},
     {"znver2", CPU::amd_znver2, CPU::generic, 0, Feature::znver2},
+    {"znver3", CPU::amd_znver3, CPU::generic, 0, Feature::znver3},
```
Comment (yuyichao) [inline src/processor_x86.cpp:291]: `{"znver3", CPU::amd_znver3, CPU::amd_znver2, 130000, Feature::znver3}`

Note that this is one of the main reasons the code is repeated. I don't think any other project carries a database for LLVM versions.

**Comment by yuyichao** [comment]
> I guess it's expected?

This should not happen on the same machine.

**Review by yuyichao — DISMISSED** [review]

File: src/processor_x86.cpp (hunk 1 above)
Comment (LebedevRI) [reply src/processor_x86.cpp:291]: Aha. Admittedly, i did not understood this particular line indeed.
Let me see if that helps.

**Comment by LebedevRI** [comment]
Now with `JULIA_CPU_TARGET=native`, both the `--cpu-target native` and the `--cpu-target znver3` work.

**Comment by LebedevRI** [comment]
I'm not sure i understand those test failures.
They seem to be happening even on znver2 and AArch64 builds.

File: src/processor_x86.cpp [hunk 2]
```diff
@@ -553,6 +556,10 @@ static CPU get_amd_processor_name(uint32_t family, uint32_t model, const uint32_
         if (model >= 0x30)
             return CPU::amd_znver2;
         return CPU::amd_znver1;
+    case 0x19:  // AMD Family 19h
+        if (model <= 0x0f || model == 0x21)
```
Comment (vchuravy) [inline src/processor_x86.cpp:560]: What is `model 0x21`? Zen3+?

File: src/processor_x86.cpp [hunk 3]
```diff
@@ -553,6 +556,10 @@ static CPU get_amd_processor_name(uint32_t family, uint32_t model, const uint32_
...
+            return CPU::amd_znver3;  // 00h-0Fh, 21h: Zen3
+        return CPU::generic;
```
Comment (vchuravy) [inline src/processor_x86.cpp:562]: Should we return `amd_znver3` unconditionally as a baseline for Fam 19h?

File: src/processor_x86.cpp (hunk 2 above)
Comment (LebedevRI) [reply src/processor_x86.cpp:560]:
```
$ lscpu 
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-31
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 5950X 16-Core Processor
    CPU family:          25
    Model:               33
    Thread(s) per core:  2
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            0
    Frequency boost:     disabled
    CPU(s) scaling MHz:  67%
    CPU max MHz:         6017.8462
    CPU min MHz:         2200.0000
    BogoMIPS:            8050.39
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse
                         3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_p
                         state ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbn
                         oinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    8 MiB (16 instances)
  L3:                    64 MiB (2 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-31
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected

```

Comment (vchuravy) [reply src/processor_x86.cpp:560]: Ah great we might have to backport this https://reviews.llvm.org/D121708

File: src/processor_x86.cpp (hunk 3 above)
Comment (LebedevRI) [reply src/processor_x86.cpp:562]: If you are telling me to do that (?) i can do that since i see that to be the usual pattern here,
but i've explicitly avoided doing that here because that is not what the other 4 sources of truth do:
* https://github.com/halide/Halide/blob/76793b48af0b29fd9958a63b97447a42c6a6654d/src/Target.cpp#L108-L149
* https://github.com/llvm/llvm-project/blob/955cff803e081640e149fed0742f57ae1b84db7d/llvm/lib/Support/Host.cpp#L968-L1041
* https://github.com/llvm/llvm-project/blob/955cff803e081640e149fed0742f57ae1b84db7d/compiler-rt/lib/builtins/cpu_model.c#L520-L586
* https://github.com/gcc-mirror/gcc/blob/000c1b89d259fadb466e1f2e63c79da45fd17372/gcc/common/config/i386/cpuinfo.h#L111-L264

Comment (vchuravy) [reply src/processor_x86.cpp:562]: https://github.com/llvm/llvm-project/blob/955cff803e081640e149fed0742f57ae1b84db7d/compiler-rt/lib/builtins/cpu_model.c#L579-L586 this does set the CPU familiy to znver3, but not the subtype.
similar https://github.com/gcc-mirror/gcc/blob/000c1b89d259fadb466e1f2e63c79da45fd17372/gcc/common/config/i386/cpuinfo.h#L257-L263 

I would rather gracefully degrade to something that is an almost right schedule instead all the way to generic.

**Review by vchuravy — APPROVED** [review]

File: src/processor_x86.cpp (hunk 2 above)
Comment (LebedevRI) [reply src/processor_x86.cpp:560]: It //seems// like we're ok:
```
$ ./usr/bin/julia --cpu-target native
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1.1 (2022-06-13)
 _/ |\__'_|_|_|\__'_|  |  znver3-backport/658769b229 (fork: 181 commits, 116 days)
|__/                   |

julia> versioninfo(verbose=true)
Julia Version 1.8.0-rc1.1
Commit 658769b229 (2022-06-13 18:49 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Debian GNU/Linux bookworm/sid
  uname: Linux 5.18.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1 (2022-06-06) x86_64 unknown
  CPU: AMD Ryzen 9 5950X 16-Core Processor: 
                 speed         user         nice          sys         idle          irq
       #1-32  4025 MHz     316620 s        127 s      34319 s   10846451 s          0 s
  Memory: 125.78296279907227 GB (68213.7578125 MB free)
  Uptime: 35338.25 sec
  Load Avg:  0.48  0.64  2.16
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 1 on 32 virtual cores
Environment:
  XDG_SESSION_PATH = /org/freedesktop/DisplayManager/Session1
  CXXFLAGS = -pipe
  HOME = /home/lebedevri
  PROFILEHOME = 
  XDG_SEAT_PATH = /org/freedesktop/DisplayManager/Seat0
  CPPFLAGS = -pipe
  TERM = xterm-256color
  PATH = /home/lebedevri/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  CFLAGS = -pipe
```

**Comment by yuyichao** [comment]
> Oh, i get it now. Zen 3 also implemented cet_ss (Control flow enforcement (CET) shadow stack),
> it is being detected for sysimage, but i didn't list it in features.

Was the thing that didn't work compiling with native and running with znver3? Yeah that'll not work if there's a mismatch. Compiling and running with native (the default) should work though no matter what feature you've listed for znver3..

File: src/processor_x86.cpp (hunk 1 above)
Comment (yuyichao) [reply src/processor_x86.cpp]: These are the fallback to support older llvm versions.

**Review by yuyichao — APPROVED** [review]
LGTM. I'm just assuming that the feature set and CPU id is correct.......

**Comment by LebedevRI** [comment]
> > Oh, i get it now. Zen 3 also implemented cet_ss (Control flow enforcement (CET) shadow stack),
> > it is being detected for sysimage, but i didn't list it in features.
> 
> Was the thing that didn't work compiling with native and running with znver3? Yeah that'll not work if there's a mismatch. Compiling and running with native (the default) should work though no matter what feature you've listed for znver3..

Something like that, yes. I've debugged that by dumping the `imgt.en.features` and `target.dis.features`
in `match_sysimg_targets()`, looking for the mismatched bit, and comparing the bit index to the enum https://github.com/JuliaLang/julia/blob/628209c1f2f746e3fc21ccd7cb34e67289403d44/src/features_x86.h#L61.

> LGTM. I'm just assuming that the feature set and CPU id is correct.......

I'm confident that it is, and it works now.

**Comment by yuyichao** [comment]
You could just do a `ccall(:jl_dump_host_cpu, Cvoid, ())` to see the detected featured .......

**Comment by LebedevRI** [comment]
> You could just do a `ccall(:jl_dump_host_cpu, Cvoid, ())` to see the detected featured .......

I could, but i didn't know i could. Still looks good:
```
julia> ccall(:jl_dump_host_cpu, Cvoid, ())
CPU: znver3
Features: sse3, pclmul, ssse3, fma, cx16, sse4.1, sse4.2, movbe, popcnt, aes, xsave, avx, f16c, rdrnd, fsgsbase, bmi, avx2, bmi2, rdseed, adx, clflushopt, clwb, sha, pku, shstk, vaes, vpclmulqdq, rdpid, sahf, lzcnt, sse4a, prfchw, mwaitx, xsaveopt, xsavec, xsaves, clzero, wbnoinvd

```

**Comment by LebedevRI** [comment]
Apologies, i'm not familiar with the julia's PR workflow.
Do i need to do anything further to get this merged?
It seems like #45613 still has not been reverted, so CI will stay red.

**Comment by LebedevRI** [comment]
@KristofferC thank you!
