### PR TITLE
FileWatching,test: remove max timeout

### LINKED ISSUE #33311: watch_folder timeout failure on Windows
See https://build.julialang.org/#/builders/65/builds/4473 (from #33291):
```
Error in testset FileWatching:
Test Failed at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win32\build\share\julia\stdlib\v1.4\FileWatching\test\runtests.jl:388
  Expression: #= C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win32\build\share\julia\stdlib\v1.4\FileWatching\test\runtests.jl:388 =# @elapsed(c = watch_folder(dir, timeout)) < 0.5
   Evaluated: 0.86873192 < 0.5
```
from [this test](https://github.com/JuliaLang/julia/blob/da86a22bb315bc73ed03c8da83e4fe6634dcc805/stdlib/FileWatching/test/runtests.jl#L388).

This hard-coded timeout was already increased once by @staticfloat in #27707, maybe it has to be increased again?  Or is there a deeper problem?

### PR DESCRIPTION
**Pull request by vtjnash**
This has been pretty flaky on CI systems, and isn't really required of the tests.

fix #33311

### CODE REVIEW

File: stdlib/FileWatching/test/runtests.jl [hunk 1]
```diff
@@ -176,24 +163,24 @@ file = joinpath(dir, "afile.txt")
...
-    @test @elapsed(@test(watch_folder(dir, 0) == ("" => FileWatching.FileEvent()))) <= 2
+    @test(watch_folder(dir, 0) == ("" => FileWatching.FileEvent()))
     @test @elapsed(@test(watch_folder(dir, 0) == ("" => FileWatching.FileEvent()))) <= 0.5
     @test length(FileWatching.watched_folders) == 1
     @test unwatch_folder(dir) === nothing
     @test isempty(FileWatching.watched_folders)
-    @test 0.001 <= @elapsed(@test(watch_folder(dir, 0.004) == ("" => FileWatching.FileEvent()))) <= 2
-    @test 0.001 <= @elapsed(@test(watch_folder(dir, 0.004) == ("" => FileWatching.FileEvent()))) <= 0.5
+    @test 0.002 <= @elapsed(@test(watch_folder(dir, 0.004) == ("" => FileWatching.FileEvent())))
+    @test 0.002 <= @elapsed(@test(watch_folder(dir, 0.004) == ("" => FileWatching.FileEvent()))) <= 0.5
```
Comment (staticfloat) [inline stdlib/FileWatching/test/runtests.jl]: Should this `0.5` be removed as well?

Comment (vtjnash) [reply stdlib/FileWatching/test/runtests.jl]: No, `0.004` is less than our internal threshold of `0.01`, so this is actually just checking `@elapsed sleep(0.004)` and not testing the filesystem performance

Comment (staticfloat) [reply stdlib/FileWatching/test/runtests.jl]: So, should we remove this test then, if it's not testing filesystem performance?
