### PR TITLE
Extensible and fast date parsing

### LINKED ISSUE #20876: Dates.parse(::AbstractString, ::DateFormat) removed without deprecation
Julia 0.5 had a `Dates.parse` function which could parse a string into an `Array{Period}`. The function was useful for parsing `DateTime`s which needed modification before constructing a `DateTime` object.

For example on Julia 0.5:

```julia
julia> df = Dates.DateFormat("yyyy-mm-dd HH:MM");

julia> DateTime("2016-03-03 24:00", df)
ERROR: ArgumentError: Hour: 24 out of range (0:23)
 in DateTime(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at ./dates/types.jl:149
 in DateTime(::Base.Dates.Year, ::Base.Dates.Month, ::Base.Dates.Day, ::Base.Dates.Hour, ::Base.Dates.Minute) at ./dates/types.jl:172
 in DateTime(::String, ::Base.Dates.DateFormat) at ./dates/io.jl:268

julia> Dates.parse("2016-03-03 24:00", df)
5-element Array{Base.Dates.Period,1}:
 2016 years
 3 months  
 3 days    
 24 hours  
 0 minutes 
```

In Julia 0.6

```julia
julia> Dates.parse("2016-03-03 24:00", Dates.DateFormat("yyyy-mm-dd HH:MM"))
ERROR: MethodError: no method matching parse(::String, ::DateFormat{Symbol("yyyy-mm-dd HH:MM"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'H'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'M'}}})
Closest candidates are:
  parse(::AbstractString, ::Int64; greedy, raise) at parse.jl:215
  parse(::AbstractString; raise) at parse.jl:230
```

### PR DESCRIPTION
**Pull request by omus**
The introduction of fast date time parsing (#19545) no longer allows external packages to extend the format specifiers used within `DateFormat`. This PR re-introduces full extensibility without impacting the previous performance gains. I've also revised the code to make extended specifiers also fast.

- [x] Document ~`parse(::Type{Vector}, ...)`~ `parse_components(...)`
- [x] Document `tryparse_core`
- [x] Document `tryparse_internal`
- [x] ~Add additional benchmarks~ Benchmarks will be added to TimeZones.jl

Fixes #20876

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("dates", vs = ":master")`

File: base/dates/io.jl [hunk 1]
```diff
@@ -252,13 +253,21 @@ const SLOT_RULE = Dict{Char, Type}(
     's' => Millisecond,
 )
 
-slot_order(::Type{Date}) = (Year, Month, Day)
-slot_order(::Type{DateTime}) = (Year, Month, Day, Hour, Minute, Second, Millisecond)
-
-slot_defaults(::Type{Date}) = map(Int64, (1, 1, 1))
-slot_defaults(::Type{DateTime}) = map(Int64, (1, 1, 1, 0, 0, 0, 0))
+const FORMAT_DEFAULTS = Dict{Type, Any}(
```
Comment (quinnj) [inline base/dates/io.jl]: The `Any` here allows TimeZones.jl to add and return a default timezone I presume?

**Comment by omus** [comment]
Thanks @KristofferC. I was just looking up that how to run the benchmarks

File: base/dates/parse.jl [hunk 2]
```diff
@@ -1,97 +1,132 @@
...
+            letter = first(token.parameters)
+            push!(directive_letters, letter)
+
+            di += 1
+        end
     end
+    return tokens, directive_index, directive_letters
+end
+
+genvar(t::DataType) = Symbol(lowercase(string(t.name.name)))
```
Comment (quinnj) [inline base/dates/parse.jl]: Hopefully this is ok or the right way to do this?

File: base/dates/parse.jl [hunk 3]
```diff
@@ -1,97 +1,132 @@
...
-        pos <= len && @goto error
+        pos > len || @goto error
 
         @label done
-        parts = Base.@ntuple $N val
-        return R(reorder_args(parts, $field_order, $field_defaults, err_idx)::$tuple_type)
+        return Nullable{$R}($(Expr(:tuple, directive_names...))), directive_idx
 
         @label error
         # Note: Keeping exception generation in separate function helps with performance
```
Comment (quinnj) [inline base/dates/parse.jl]: so is this comment no longer applicable?

File: base/dates/io.jl (hunk 1 above)
Comment (omus) [inline base/dates/io.jl]: `Any` is used for extensibility. Specifically for TimeZones.jl I'm using an empty string as the default. If/when this is converted into a ZonedDateTime an exception is raised telling the user that the timezone given is invalid.

File: base/dates/parse.jl (hunk 3 above)
Comment (omus) [inline base/dates/parse.jl]: I tested this again and it no longer seems to be an issue. I originally found this problem.

**Review by quinnj — APPROVED** [review]
This will be great to have.

File: base/dates/parse.jl (hunk 2 above)
Comment (omus) [inline base/dates/parse.jl]: I'm sure this is going to generate lots of discussion. Basically I need to map the specifier types to a variable name. Using separate variable names allows the generated code to avoid type instability problems (occurs once extended). Additionally, I can't get away with using `gensym` as some of the code requires me to match up the variable names. See `tryparse_internal`

**Comment by omus** [comment]
Failure on Appveyor was caused from me wrapping a long line incorrectly.

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20952#issuecomment-285171891):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/af0e20d4d954b5874155104b728771e219cafdad/f93eaf8_vs_8436f45/report.md)
cc @jrevels

**Comment by omus** [comment]
@quinnj we've been rather inconsistent on what we call the special characters (`yyyy`) which we use to indicate a token we need to parse. We've used terms like slot, code, or format specifier in the past.

We should probably stick to a consistent term in both the code and in the manual. What do you prefer:
- slot
- code
- [format specifier](https://en.wikipedia.org/wiki/Printf_format_string)
- [conversion specifier](http://man7.org/linux/man-pages/man3/printf.3.html)

File: base/dates/io.jl [hunk 4]
```diff
@@ -252,13 +253,21 @@ const SLOT_RULE = Dict{Char, Type}(
...
+    Minute => Int64(0),
+    Second => Int64(0),
+    Millisecond => Int64(0),
+)
 
-slot_types{T<:TimeType}(::Type{T}) = typeof(slot_defaults(T))
+const FORMAT_TRANSLATIONS = Dict{Type{<:TimeType}, Tuple}(
+    Date => (Year, Month, Day),
+    DateTime => (Year, Month, Day, Hour, Minute, Second, Millisecond),
+)
```
Comment (vtjnash) [inline base/dates/io.jl]: Should we make all these ImmutableDict? They're small enough that may be a performance and memory improvement (however inconsequential overall), and would help enforce that the data feeding into a generated function can't be modified (esp. if that code wants to eventually be precompiled)

Comment (omus) [inline base/dates/io.jl]: @vtjnash switching these to `ImmutableDict`s would remove ability to extend code.

**Comment by quinnj** [comment]
@omus, yeah, i'm fine with whatever. Format specifier seems fine to me.

File: base/dates/io.jl (hunk 4 above)
Comment (omus) [inline base/dates/io.jl]: Originally these were defined through methods (which I prefer):
```julia
slot_order(::Type{DateTime}) = (Year, Month, Day, Hour, Minute, Second, Millisecond)
```
Unfortunately this cannot be used here since generated functions cannot call methods defined after the generated function definition.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("dates", vs = ":master")`

File: base/dates/parse.jl [hunk 5]
```diff
@@ -200,3 +235,38 @@ function Base.parse(::Type{DateTime}, s::AbstractString, df::typeof(ISODateTimeF
...
+)
+    nt = tryparse_internal(T, str, df, false)
+    if isnull(nt)
+        Nullable{T}()
+    else
+        Nullable{T}(T(unsafe_get(nt)...))
+    end
+end
+
+@generated function Base.parse(::Type{Vector}, str::AbstractString, df::DateFormat)
```
Comment (tkelman) [inline base/dates/parse.jl]: this is a bit of an odd method, weren't you going to deprecate it?

Comment (omus) [inline base/dates/parse.jl]: I added a deprecation for `parse(::AbstractString, ::DateFormat)`.

Comment (omus) [inline base/dates/parse.jl]: I agree that the method signature is a bit odd. Maybe a different function name like `parse_tokens(::AbstractString, ::DateFormat)` would be better?

Comment (tkelman) [inline base/dates/parse.jl]: if it doesn't have to be an externally visible method of parse, then yeah a local name would raise fewer eyebrows

(does the deprecation need to be eval'ed?)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20952#issuecomment-285182787) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d2b5238e6751bd877b8ea69c35c6668a17d97c53/4a225ae_vs_e596063/report.md). cc @jrevels

File: base/dates/parse.jl (hunk 5 above)
Comment (omus) [inline base/dates/parse.jl]: The original `parse` function was only defined in `Base.Dates.parse` and wasn't exported. I believe I need the eval to define a function in another module.

File: base/dates/parse.jl [hunk 6]
```diff
@@ -1,97 +1,132 @@
...
+
+genvar(t::DataType) = Symbol(lowercase(string(t.name.name)))
 
-    field_defaults = slot_defaults(T)
-    field_order = tuple(order...)
-    tuple_type = slot_types(T)
 
-    # `slot_order`, `slot_defaults`, and `slot_types` return tuples of the same length
-    assert(num_types == length(field_order) == length(field_defaults))
+@generated function tryparse_core(str::AbstractString, df::DateFormat, raise::Bool=false)
```
Comment (shashi) [inline base/dates/parse.jl]: It will be great if this function can take a start index and return an end position... I've had to hack around this to get this, because it's very useful when you're parsing dates and some more stuff after / a list of dates

File: base/dates/parse.jl [hunk 7]
```diff
@@ -1,97 +1,132 @@
...
-    ntuple(Val{N}) do i
-        if idx[i] == 0 || idx[i] >= default_from
-            default[i]
-        else
-            val[idx[i]]
-        end
-    end
-end
+@generated function tryparse_internal{T<:TimeType}(
+    ::Type{T}, str::AbstractString, df::DateFormat, raise::Bool=false,
```
Comment (shashi) [inline base/dates/parse.jl]: And/ or this method should also take a position and return an end position....

File: base/dates/parse.jl [hunk 8]
```diff
@@ -1,97 +1,132 @@
...
-#
-function reorder_args{N}(val::Tuple, idx::NTuple{N}, default::Tuple, default_from::Integer)
-    ntuple(Val{N}) do i
-        if idx[i] == 0 || idx[i] >= default_from
-            default[i]
-        else
-            val[idx[i]]
-        end
-    end
-end
```
Comment (shashi) [inline base/dates/parse.jl]: Cool that you got rid of this! :)

File: base/dates/parse.jl (hunk 5 above)
Comment (shashi) [inline base/dates/parse.jl]: We should consider having "Parser types" (kinda like the token types in this module) and using their objects of those types as the first argument to parse rather than have it always be `Type` of the return value. That is not sustainable as you can see.

Comment (shashi) [inline base/dates/parse.jl]: But of course that's not in the scope of this changeset.

**Review by shashi — APPROVED** [review]
Apart from the minor (but useful) changes to arguments / return values in tryparse_internal, this is good!

File: base/dates/parse.jl (hunk 2 above)
Comment (tkelman) [inline base/dates/parse.jl]: is there a reflection function for this?

File: base/dates/io.jl (hunk 4 above)
Comment (vtjnash) [inline base/dates/io.jl]: That is correct. A generated function cannot be relied upon to observe any external mutation.

File: base/dates/parse.jl (hunk 2 above)
Comment (omus) [inline base/dates/parse.jl]: I can use `Base.datatype_name` to replace `t.name.name`. There doesn't seem to be anything that will make a lowercase version of a Symbol

File: base/dates/parse.jl (hunk 6 above)
Comment (omus) [inline base/dates/parse.jl]: I think this can be supported.

**Comment by omus** [comment]
@nanosoldier `runbenchmarks("dates", vs = ":master")`

**Comment by omus** [comment]
I'll be revising some of the documentation and type names in `dates/io.jl` to be more consistent. I'll save that for another PR though.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20952#issuecomment-285808972) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d8dead6755c212c9b9c49e7f6744f4385c92a966/24431f2_vs_0e970f0/report.md). cc @jrevels

File: base/dates/parse.jl [hunk 9]
```diff
@@ -1,131 +1,158 @@
...
+
+"""
+    tryparsenext_core(str::AbstractString, pos::Int, len::Int, df::DateFormat)
+
+Parses the string according to the directives within the DateFormat. Parsing will start at
+character index `pos` and will stop when all directives are used or we have parsed up to the
+end of the string (`len`).
+
+Returns a 3-element tuple `(values, pos, num_parsed)`:
+* `values::Nullable{Tuple}`: A tuple which contains a values for each `DatePart` within the
```
Comment (tkelman) [inline base/dates/parse.jl]: a value for each

File: base/dates/parse.jl [hunk 10]
```diff
@@ -1,131 +1,158 @@
...
+  `DateFormat` in the order in which the occur. If the string ends before we finish parsing
```
Comment (tkelman) [inline base/dates/parse.jl]: order in which they occur

File: base/dates/parse.jl [hunk 11]
```diff
@@ -1,131 +1,158 @@
...
+  all the directives the missing values will be filled in with default values.
+* `pos::Int`: The character index at which parsing stopped.
+* `num_parsed::Int`: The number of values which were parsed and stored within `values`.
+  Useful for distinguishing parsed values from default values.
+"""
+@generated function tryparsenext_core(
+    str::AbstractString, pos::Int, len::Int, df::DateFormat, raise::Bool=false,
```
Comment (tkelman) [inline base/dates/parse.jl]: raise not documented?

File: base/dates/parse.jl [hunk 12]
```diff
@@ -1,131 +1,158 @@
...
+    tryparsenext_internal(::Type{<:TimeType}, str::AbstractString, pos::Int, len::Int, df::DateFormat)
+
+Parses the string according to the directives within the DateFormat. The specified TimeType
+type determines the type of and order of tokens returned. If the given DateFormat or string
+does not provide a required token a default value will be used.
 
-@generated function tryparse_internal{T<:TimeType}(
-    ::Type{T}, str::AbstractString, df::DateFormat, raise::Bool=false,
+Returns a 2-element tuple `(values, pos)`:
+* `values::Nullable{Tuple}`: A tuple which contains a values for each token as specified by
```
Comment (tkelman) [inline base/dates/parse.jl]: a value for each

File: base/dates/parse.jl (hunk 11 above)
Comment (omus) [inline base/dates/parse.jl]: That was an oversight. I made it a keyword at one point and meant to mention it in the docstring details.

File: base/dates/parse.jl (hunk 12 above)
Comment (StefanKarpinski) [inline base/dates/parse.jl]: shouldn't we be doing these edits on the PR branch?

File: base/dates/parse.jl [hunk 13]
```diff
@@ -17,15 +17,16 @@ end
 genvar(t::DataType) = Symbol(lowercase(string(Base.datatype_name(t))))
 
 """
-    tryparsenext_core(str::AbstractString, pos::Int, len::Int, df::DateFormat)
+    tryparsenext_core(str::AbstractString, pos::Int, len::Int, df::DateFormat, raise=false)
 
 Parses the string according to the directives within the DateFormat. Parsing will start at
-character index `pos` and will stop when all directives are used or we have parsed up to the
-end of the string (`len`).
+character index `pos` and will stop when all directives are used or we have parsed up to,
```
Comment (tkelman) [inline base/dates/parse.jl]: there shouldn't be a comma at the end of the line here

File: base/dates/parse.jl [hunk 14]
```diff
@@ -110,14 +111,14 @@ Returns a 3-element tuple `(values, pos, num_parsed)`:
 end
 
 """
-    tryparsenext_internal(::Type{<:TimeType}, str::AbstractString, pos::Int, len::Int, df::DateFormat)
+    tryparsenext_internal(::Type{<:TimeType}, str, pos, len, df::DateFormat, raise=false)
```
Comment (tkelman) [inline base/dates/parse.jl]: should raise also be described here?

**Comment by omus** [comment]
@nanosoldier `runbenchmarks("dates", vs = ":master")`

File: base/dates/parse.jl [hunk 15]
```diff
@@ -115,7 +115,8 @@ end
 
 Parses the string according to the directives within the DateFormat. The specified TimeType
 type determines the type of and order of tokens returned. If the given DateFormat or string
-does not provide a required token a default value will be used.
+does not provide a required token a default value will be used. If the provided string
+cannot be parsed an exception will be thrown only if `raise` is true.
```
Comment (StefanKarpinski) [inline base/dates/parse.jl]: I guess the natural question is what happens otherwise?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20952#issuecomment-286143799) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/159c10da7a2e8b9afb571fb5311e1d30c6f2c875/9a96fc2_vs_a132ae2/report.md). cc @jrevels

File: base/dates/parse.jl (hunk 15 above)
Comment (omus) [inline base/dates/parse.jl]: I'll update the docstring to explain what happens in either case.

**Comment by omus** [comment]
Nanosoldier failures appear to be noise

**Comment by omus** [comment]
@nanosoldier `runbenchmarks("dates", vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20952#issuecomment-286806429):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d1585fd03740c3bc4ce4195fa22e346a873cc58c/08fcc75_vs_c399558/report.md)
cc @jrevels

**Comment by jrevels** [comment]
Nanosoldier breakage is due to https://github.com/JuliaLang/julia/issues/21028

File: base/dates/parse.jl [hunk 16]
```diff
@@ -1,97 +1,162 @@
...
+
+        pos > len || @goto error
 
         @label done
-        parts = Base.@ntuple $N val
-        return R(reorder_args(parts, $field_order, $field_defaults, err_idx)::$tuple_type)
+        return Nullable{$R}($(Expr(:tuple, value_names...))), pos, num_parsed
 
         @label error
         # Note: Keeping exception generation in separate function helps with performance
```
Comment (tkelman) [inline base/dates/parse.jl]: is this comment no longer accurate?

Comment (omus) [inline base/dates/parse.jl]: Correct. I'll make sure to remove that.

**Comment by StefanKarpinski** [comment]
This looks good to go as soon as you're done tweaking things, @omus. Merge when ready.

**Comment by omus** [comment]
Code changes are done. @tkelman any other comments?

**Comment by Sacha0** [comment]
@omus, might this work warrant a NEWS.md entry? Best!
