### PR TITLE
ppc64le abi

### LINKED ISSUE #16036: Compilation failed on ppc64
Hi All, I am trying to compile Julia 0.4.5 on Power8, Redhat 7.2/64-bit. My "Make.user" file:

    prefix=${SOFT}/julia  
[julia.ppc64.log.zip](https://github.com/JuliaLang/julia/files/234398/julia.ppc64.log.zip)

                  # <-- custom destination folder, SOFT is defined in .bashrc
    include $(JULIAHOME)/Make.powerpc

The failure happens while "inference.jl" is compiled (the complete output file is attached):

```
inference.jl
julia: /home/albert/tmp/julia-0.4.5/deps/llvm-3.6.0/lib/CodeGen/MachineLICM.cpp:960: bool {anonymous}::MachineLICM::IsLoopInvariantInst(llvm::MachineInstr&): Assertion `MRI->getVRegDef(Reg) && "Machine instr not mapped for this vreg?!"' failed.

signal (6): Aborted
/bin/sh: line 1: 102713 Aborted                 (core dumped) /home/albert/tmp/julia-0.4.5/usr/bin/julia -C native --output-ji /home/albert/tmp/julia-0.4.5/usr/lib/julia/inference0.ji -f coreimg.jl
make[1]: *** [/home/albert/tmp/julia-0.4.5/usr/lib/julia/inference0.ji] Error 134
make: *** [julia-inference] Error 2
```

### LINKED ISSUE #16456: Get backtraces working on Power
Getting the unwinder and backtraces would be the last major issue for the Julia port on Power. Opening this issue to track progress.

### PR DESCRIPTION
**Pull request by vtjnash**
ref #16455 (vector abi is not yet implemented)
fix #16456
close #16036

### CODE REVIEW

File: src/options.h [hunk 1]
```diff
@@ -113,9 +113,9 @@
 #  define MEMDEBUG
 #  define KEEP_BODIES
 #  endif
-// Memory sanitizer also needs thread-local storage
+// Memory sanitizer also needs small memory model
```
Comment (Keno) [inline src/options.h]: No, it needs thread local storage. Please don't keep changing this. Being able to use memory sanitizer is important.

File: src/abi_ppc64le.cpp [hunk 2]
```diff
@@ -0,0 +1,111 @@
+//===-- abi_ppc64le.cpp - Power v2 ABI description ---------------------*- C++ -*-===//
+//
+//                         LDC – the LLVM D compiler
+//
+// This file is distributed under the BSD-style LDC license:
```
Comment (tkelman) [inline src/abi_ppc64le.cpp]: add to list in `contrib/add_license_to_files.jl`

File: src/abi_win32.cpp [hunk 3]
```diff
@@ -67,7 +67,7 @@ Type *preferred_llvm_type(jl_value_t *ty, bool isret)
         return NULL;
     jl_datatype_t *dt = (jl_datatype_t*)ty;
     // rewrite integer sized (non-sret) struct to the corresponding integer
-    if (!dt->nfields || use_sret(NULL, ty))
+    if (!dt->nfields)
```
Comment (tkelman) [inline src/abi_win32.cpp]: Why is this change included in a power PR?

Comment (vtjnash) [inline src/abi_win32.cpp]: `preferred_llvm_type` no longer gets called if `sret` is true

File: src/options.h (hunk 1 above)
Comment (vtjnash) [inline src/options.h]: This flag doesn't directly toggle TLS, it toggles small memory model (and PIC). The small memory model isn't supported by the SectionMemoryManager (the result being occasional random segfaults and memory corruption). When you fix the SMM, I'll stop removing the flag.

Comment (Keno) [inline src/options.h]: Both of which are required for TLS. I'd rather have a flag that occasionally segfaults but otherwise tells me where memory bugs are than one that doesn't work at all.

Comment (Keno) [inline src/options.h]: Also, of course the proper fix is to teach LLVM how to do TLS in the large memory model.

File: src/debuginfo.cpp [hunk 4]
```diff
@@ -1515,8 +1515,10 @@ static DW_EH_PE parseCIE(const uint8_t *Addr, const uint8_t *End)
     // Assume there's no EH Data field, which exist when the augmentation
     // string has "eh" in it.
     p += augmentation_len + 1;
-    // Code Alignment Factor (1 byte) should always be 1
-    assert(*p == 1);
+    // Code Alignment Factor (1 byte)
+    // should always be 1 on x86, 4 on PPC, etc.
+    // (used for DW_CFA_advance_loc / not used here)
+    //assert(*p == 1);
```
Comment (yuyichao) [inline src/debuginfo.cpp]: might worth keeping the assertion (with the check corrected).

Comment (vtjnash) [inline src/debuginfo.cpp]: what's the correct check? the only reference seems to be some random guys blog at the url above. I'm surprised it's not 4 on ARM also, but perhaps due to thumb mode accommodations it was 1 there too? If we were to need to use this parameter, then presumably we would actually use it's value, instead of pre-asserting something about the environment

Comment (yuyichao) [inline src/debuginfo.cpp]: It's mainly for making sure that the value we skip is what we think it is.

Comment (yuyichao) [inline src/debuginfo.cpp]: P.S. ARM doesn't use this code path. AArch64 (which doesn't have thumb) does seems to have `1` for this value though....

Comment (vtjnash) [inline src/debuginfo.cpp]: curious. it's 1 by default, but it (`MinInstAlignment`) is overridden to 4 for only the `Lanai`, `Hexagon`, and `PowerPC` backends

Comment (yuyichao) [inline src/debuginfo.cpp]: If you also don't have any reliably source explaining what the value should be, I guess it's fine to remove the assert .......

Comment (Keno) [inline src/debuginfo.cpp]: It's the value of the smallest possible instruction on that architecture. It's used to factor code offsets in the DWARF opcodes.

Comment (Keno) [inline src/debuginfo.cpp]: Well, note quite. More precisely it's the largest possible value such that any valid instruction on that architecture is a multiple of that value.

Comment (vtjnash) [inline src/debuginfo.cpp]: Is it just an oversight that this isn't 4 on AArch64?

Comment (Keno) [inline src/debuginfo.cpp]: Not sure. Are there instructions on AArch64 that are shorter than 4 bytes (or does AArch64 not have alignment requirements, which could also be a reason)?

Comment (yuyichao) [inline src/debuginfo.cpp]: I think AArch64 drops thumb and all instructions are 32bits. `$pc` is also required to be 4 bytes aligned http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/ch05s01s02.html

File: src/abi_ppc64le.cpp (hunk 2 above)
Comment (vtjnash) [inline src/abi_ppc64le.cpp]: I'll fix this one. There's a bunch more that need to be fixed though (`src/support/dirname.c` is missing from the list and the script needs to be rerun).

File: src/debuginfo.cpp (hunk 4 above)
Comment (Keno) [inline src/debuginfo.cpp]: Then that looks like an oversight.

**Comment by vtjnash** [comment]
I'm running into an llvm bug when trying to build the debug version, however, the fix will be included in llvm 3.8 (http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20160530/360643.html)

**Comment by Keno** [comment]
LLVM patch committed upstream as http://reviews.llvm.org/rL271425. Shall we ask for a backport to 3.8.1?

**Comment by tkelman** [comment]
I think we missed the deadline for that, but we could try and see?

**Comment by Keno** [comment]
Yes, you're right. They're expecting to release 3.8.1rc1 today. I think we're fine with 3.9. There's much more work to be done before people will want to use julia with non-bundled versions of LLVM, so I don't think there's much of a rush.

File: src/abi_ppc64le.cpp (hunk 2 above)
Comment (tkelman) [inline src/abi_ppc64le.cpp]: in a separate pr then?

Comment (vtjnash) [inline src/abi_ppc64le.cpp]: I was planning on just pushing the update to master, no?

**Comment by tkelman** [comment]
rc1 was apparently pushed back to monday, maybe we could try our luck asking for this to be done between rc's?
