### PR TITLE
(#42139) Fixes _is_mailto in resolution of autolink in Markdown module

### LINKED ISSUE #42139: Markdown autolink resolution _is_mailto can fail with bad string indexing
This was reported by a Franklin user but ended up being a bug with the Markdown module:

```julia
julia> Markdown.parse("<一轮红日初升>")
ERROR: StringIndexError: invalid index [6], valid nearby indices [4]=>'轮', [7]=>'红'
```

This is because Markdown sees the `< ... >` and tries to form an auto link and seems to be using string indexing in doing so. CommonMark.jl handles this well

```julia
julia> import CommonMark as CM
julia> p = CM.Parser()
julia> CM.html(p("<一轮红日初升>"))
"<p>&lt;一轮红日初升&gt;</p>\n"
```

actually reading the full stack trace points to `_is_mailto` being the culprit 

https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/stdlib/Markdown/src/Common/inline.jl#L151-L156

ironically there's a comment specifying that it's a bit risky to be slicing the string (also it's a bit odd to check the first 6 characters with a 7 character string)

A suggestion would be to replace https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/stdlib/Markdown/src/Common/inline.jl#L154-L155

using `first` and `nextind`, I opened a PR with this here: https://github.com/JuliaLang/julia/pull/42140

### PR DESCRIPTION
**Pull request by tlienart**
Closes #42139

### CODE REVIEW

File: stdlib/Markdown/src/Common/inline.jl [hunk 1]
```diff
@@ -149,10 +149,9 @@ end
 const _email_regex = r"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
 
 function _is_mailto(s::AbstractString)
-    length(s) < 6 && return false
-    # slicing strings is a bit risky, but this equality check is safe
-    lowercase(s[1:6]) == "mailto:" || return false
-    return occursin(_email_regex, s[6:end])
+    length(s) < 7 && return false
+    lowercase(first(s, 7)) == "mailto:" || return false
```
Comment (martinholters) [inline stdlib/Markdown/src/Common/inline.jl:153]:
```suggestion
    startswith(s, "mailto:") || return false
```
Or I guess we could just include the `mailto:` in the regex (and rename it to, say, `_mailto_regex`). I don't think it's used anywhere else.

Comment (tlienart) [reply stdlib/Markdown/src/Common/inline.jl:153]: :+1: I guess I was trying to have the change that was as close as possible to the current situation but this makes more sense, will do this
