### PR TITLE
better error for esc outside of macro expansion

### LINKED ISSUE #55788: `esc` outside of macro context should give a better error message
This barfs flisp internals:

```
julia> eval(esc(:(const x=1)))
ERROR: syntax: invalid syntax (escape (block (= (ssavalue 6) 1) (block (newvar x) (null) (block (null) (= x (ssavalue 6))) (const (globalref (thismodule) x) x) (ssavalue 6))))
Stacktrace:
 [1] top-level scope
   @ none:1
 [2] eval
   @ ./boot.jl:438 [inlined]
 [3] eval(x::Expr)
   @ Main ./sysimg.jl:48
 [4] top-level scope
   @ REPL[1]:1
```

### PR DESCRIPTION
**Pull request by simeonschaub**
fixes #55788

### CODE REVIEW

File: test/syntax.jl [hunk 1]
```diff
@@ -3985,3 +3985,5 @@ begin
   end
 end
 @test f45494() === (0,)
+
+@test_throws "\"esc(:(...))\" used outside of macro expansion" eval(esc(:(const x=1)))
```
Comment (simeonschaub) [inline test/syntax.jl:3989]:
```suggestion
@test_throws "\"esc(...)\" used outside of macro expansion" eval(esc(:(const x=1)))
```

**Review by Keno — APPROVED** [review]
