### PR TITLE
Remove package extensions in Pkg functions

### LINKED ISSUE #20630: Automatically remove `.jl` termination in `Pkg.add`
```
julia> Pkg.add("Lint.jl")
ERROR: unknown package Lint.jl
```

### PR DESCRIPTION
**Pull request by fredrikekre**
This implements #20630 and allows for eg.

```julia
Pkg.add("SpecialFunctions.jl")
Pkg.rm("SpecialFunctions.jl")
...
```
by stripping of the terminating `.jl` extension.

TODO:
- [x] add tests (ideas?)
- [x] documentation (where should this be documented?)

fix #20630

### CODE REVIEW

**Comment by ararslan** [comment]
Thanks for working on this! As a test, you could add/remove the Example package both with and without the .jl suffix.

File: test/pkg.jl [hunk 1]
```diff
@@ -496,6 +496,53 @@ temp_pkg_dir() do
...
+        Pkg.free("Example.jl")
+        Pkg.status("Example.jl", iob)
+        str = chomp(String(take!(iob)))
+        @test endswith(str, string(Pkg.installed("Example.jl")))
+        Pkg.checkout("Example.jl")
+        Pkg.free(("Example.jl",))
+        Pkg.status("Example.jl", iob)
+        str = chomp(String(take!(iob)))
+        @test endswith(str, string(Pkg.installed("Example.jl")))
+        @test isempty(Pkg.dependents("Example.jl"))
```
Comment (tkelman) [inline test/pkg.jl]: this seems a little fragile, anyone could break this by adding a package that depends on Example in the future (which is kinda silly, but allowed)

Comment (fredrikekre) [inline test/pkg.jl]: I just copied from the usual test suite: https://github.com/JuliaLang/julia/blob/1297ede6cf40e0ad7e893fc4a2916a20a3df78ce/test/pkg.jl#L127

Comment (fredrikekre) [inline test/pkg.jl]: But yeah, both tests seem fragile.

File: base/pkg/pkg.jl [hunk 2]
```diff
@@ -37,6 +37,10 @@ const cd = Dir.cd
 
 dir(path...) = Dir.path(path...)
 
+# remove extension .jl
+const PKGEXT = ".jl"
+splitjl(pkg::AbstractString) = endswith(pkg, PKGEXT) ? splitext(pkg)[1] : pkg
```
Comment (yuyichao) [inline base/pkg/pkg.jl]: Not that it really matters but `pkg[1:(end - 3)]` would be much faster...

File: doc/src/manual/packages.md [hunk 3]
```diff
@@ -171,6 +171,14 @@ git config --global url."https://".insteadOf git://
 
 However, this change will be system-wide and thus the use of [`Pkg.setprotocol!()`](@ref) is preferable.
 
+!!! note
+    The package manager functions accept package names with the `.jl` extension:
```
Comment (ararslan) [inline doc/src/manual/packages.md]: I'd probably word this to say that it's possible but is stripped out internally so as not to encourage this style of use. Maybe "The package manager functions also accept the `.jl` suffix on package names, though the suffix is stripped out internally."

**Comment by fredrikekre** [comment]
Failures seems unrelated? Feel free to restart.

**Comment by KristofferC** [comment]
Restarded travis, log at: https://gist.github.com/KristofferC/162cbe28353847ad4197e5e9c2337454

File: test/pkg.jl (hunk 1 above)
Comment (StefanKarpinski) [inline test/pkg.jl]: Seems pretty hypothetical. If anyone does that, we can fix the tests then.

Comment (tkelman) [inline test/pkg.jl]: That would immediately break the tests of all past versions of julia though, which isn't great. Would be better to move this to a section of the tests that's running against a known past commit of metadata, rather than the latest.

Comment (fredrikekre) [inline test/pkg.jl]: Feel free to push a commit to this branch fixing this and the test linked in my comment above or handle it in a separate PR. I am not sure how I should go about it.

**Comment by fredrikekre** [comment]
Bump. (Too late for this to be merged?)

**Review by KristofferC — APPROVED** [review]

**Review by ararslan — APPROVED** [review]
