### PR TITLE
fix #37872, avoid cycles in codegen for `===`

### LINKED ISSUE #37872: Internal error with StackOverflowError while compiling a function
MWE:
```
julia> function swapliterals!(@nospecialize(swaps::AbstractDict))
           swaps === Base.ImmutableDict(Int128 => :big)
       end
swapliterals! (generic function with 1 method)

julia> swapliterals!(Dict(Int=>Int))
Internal error: encountered unexpected error during compilation of swapliterals!:
StackOverflowError()
jl_type_intersection_env_s at /local/src/julia/src/subtype.c:3305
emit_f_is at /local/src/julia/src/codegen.cpp:2553
emit_bits_compare at /local/src/julia/src/codegen.cpp:2503
operator() at /local/src/julia/src/codegen.cpp:2573
emit_guarded_test<emit_f_is(jl_codectx_t&, const jl_cgval_t&, const jl_cgval_t&, llvm::Value*, llvm::Value*)::<lambda()>&> at /local/src/julia/src/codegen.cpp:
2322
operator() at /local/src/julia/src/codegen.cpp:2354 [inlined]
[...]
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #37872

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -2564,8 +2564,8 @@ static Value *emit_f_is(jl_codectx_t &ctx, const jl_cgval_t &arg1, const jl_cgva
         (jl_pointer_egal(rt1) || jl_pointer_egal(rt2)))
         return ctx.builder.CreateICmpEQ(boxed(ctx, arg1), boxed(ctx, arg2));
 
-    bool justbits1 = jl_is_concrete_immutable(rt1);
-    bool justbits2 = jl_is_concrete_immutable(rt2);
+    bool justbits1 = jl_is_concrete_immutable(rt1) && ((jl_datatype_t*)rt1)->isinlinealloc;
+    bool justbits2 = jl_is_concrete_immutable(rt2) && ((jl_datatype_t*)rt2)->isinlinealloc;
```
Comment (yuyichao) [inline src/codegen.cpp:2568]: The old implementation avoids this by calling `emit_box_compare` for pointer fields so I think a better fix to make sure there's no regression is to do the check in `emit_bits_compare` on `fldty` instead when the field is a pointer.

**Review by vtjnash — APPROVED** [review]

File: src/codegen.cpp [hunk 2]
```diff
@@ -2500,8 +2500,15 @@ static Value *emit_bits_compare(jl_codectx_t &ctx, jl_cgval_t arg1, jl_cgval_t a
                 Value *nullcheck2 = nullptr;
                 auto fld1 = emit_getfield_knownidx(ctx, arg1, i, sty, &nullcheck1);
                 auto fld2 = emit_getfield_knownidx(ctx, arg2, i, sty, &nullcheck2);
-                answer = ctx.builder.CreateAnd(answer, emit_f_is(ctx, fld1, fld2,
-                                                                 nullcheck1, nullcheck2));
+                if (jl_field_isptr(sty, i) && jl_is_concrete_immutable(fldty)) {
+                    // concrete immutables that are !isinlinealloc might be reference cycles
+                    // issue #37872
+                    answer = emit_box_compare(ctx, fld1, fld2, nullcheck1, nullcheck2);
```
Comment (vtjnash) [inline src/codegen.cpp:2506]:
```suggestion
                    answer = ctx.builder.CreateAnd(answer,  emit_box_compare(ctx, fld1, fld2, nullcheck1, nullcheck2));
```

Comment (JeffBezanson) [reply src/codegen.cpp:2506]: ooooooops
