### PR TITLE
The `cfunction` 1.0 deserves

### LINKED ISSUE #1096: julia functions as C callbacks
--- update ---
the original issue is pretty much covered by cfunction. the remaining issues are:
- [ ] support closures
- [x] adding conversion wrapper in case of inexact matches

---- original text ---
To enable certain function calls to C code, it would be helpful to have a function callback API in Julia (this is partly inspired by the libuv interface, which ended up handling most of these issues by creating a tight coupling between julila function and types and libuv callbacks and types)

The two issues that I currently see would need to be handled are:
1) Since pointers are leaving control of Julia, the garbage collector needs to know not to clean-up anything that may be used in the future (and notified when it can)
2) Since C doesn't natively have type information, it requires some sort of reverse ccall interface

To handle 1, I think it may be safest to create a garbage collector allocation pool. Objects can be pushed to and popped from it from within Julia (using ref counting?). Then possibly add a default behavior that parameters to a ccall containing a Callback object are automatically saved until all callbacks are manually deleted. (since additional and previous calls to C functions may also hold onto object pointers, it may be useful to have this as a separately available function)

To handle 2, it will be necessary to indicate type information to the ccall. One possibility is to make a type that contains the information ```type Callback{ params <: Tuple } end ``` and is passed to the ccall in the third argument tuple. A generic function name would then be passed in the parameters list. A second possibility is to make Callback a simple type that contains all of that information ```type Callback; params <: Tuple; f :: Function; end```. A third (similar) possibility is to do the exact function lookup in Julia and require something like the value returned by getmethods and printed by whicht. In any case, I envision that ccall would JIT an intermediary function that converts from raw bits types to Julia types. This prompts the last possibility (and possibly my favorite) of having make_callback return a raw pointer to a newly JIT'd  intermediary C function:

```
callback_fcn = make_callback(fcn::Function, arg_types::Tuple)
arg2 = "test"
cpreserve(arg2); cpreserve(fcn) # if args are not automatically preserved
ccall(:cfcn, Void, (Ptr, String), callback_fcn, arg2)
...
crelease(arg2) # if args are not automatically preserved
crelease(fcn) # if args are automatically preserved, arg2 won't be freed till after this point
```

A final question is whether pointer_to_array is the best way to grab a c array? Or is there some way to indicate this in the argument type?

Thoughts and alternatives? Am I missing any challenging callback argument types?

### LINKED ISSUE #12256: precompiling cfunction calls
I noticed in stevengj/PyCall.jl#167 that, even after running `Base.compile`, some `cfunction` calls in my `__init__` function were taking a significant amount of time (0.8 seconds for 6 functions).

I could work around this by adding some explicit `precompile` lines in order to ensure that these were compiled, but this raises three problems:

* Calls to `cfunction` in `__init__` should really cause the corresponding functions to be precompiled automatically.

* Even after precompiling, `cfunction` was quite expensive: 0.25 seconds for 6 functions.

* Calling `precompile` causes the functions to be compiled at the wrong time — *before* `__init__` is called rather than *after*.  Since my `__init__` initializes some `global const` variables that are referenced in the precompiled functions, this means that type inference does not work properly when precompiling (since Julia does not know the types of those globals yet).

cc: @vtjnash

### LINKED ISSUE #26070: Error when calling cfunction on a constructor
If one calls `cfunction` on a constructor, Julia throws an error about closures.

```julia
julia> struct Thing
       x::Int
       end

julia> cfunction(Thing, Ref{Thing}, (Int,))
ERROR: closures are not yet c-callable
Stacktrace:
 [1] cfunction(::Type{T} where T, ::Type{T} where T, ::Tuple{DataType}) at ./c.jl:24
```

There is some discussion on [Discourse](https://discourse.julialang.org/t/constructors-and-cfunction/9067), where it was suggested that this is a bug.

I've tested this on two different machines, and both give the same behavior.  The `versioninfo` output for each is below.

```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, has well)
```

```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

### PR DESCRIPTION
**Pull request by vtjnash**
This PR turns `cfunction` into a macro, and has it work more similarly to `ccall` (no runtime compiler required, defined by the containing method parameters, supports any type object including closures). In most cases, v0.6 code should just need to add an `@`. But it also has new advanced capabilities to efficiently create gc-managed runtime closures pointers! This will fix #12256, fix #26070 and close #1096 (I feel slightly cheated to not get to close a 3-digit issue on this one 😜).

Implements https://github.com/vtjnash/julep/wiki/0004:-Static-compilation-for-cfunction

The best place to see the net effect of this change is perhaps the stdlib, but also the docs (where I have an example of qsort), or the Julep (which has a more complete exploration of qsort usages), or lastly perhaps the tests (which try to have examples of weird uses of almost everything).

~~Syntax questions:~~

1. ~~Creating a closure over the value of a local variable requires annotating with `$`: i.e. `ptr = @cfunction $cl RT (A, B)`. However, I've also considered instead using `local` for this purpose instead: `ptr = @cfunction local cl RT (A, B)`. Thoughts on which one reads better? As can be seen from there being zero usages in this repo (outside of tests), this feature isn't a particularly common need / the other form is more preferred and easier to use (when possible), so I don't really care either way.~~

2. ~~Should I continue to use basically the same syntax as before (i.e. just add `@`), or use the following alternate syntax rearrangement, or just try to provide both: `ptr = @cfunction cl(A, B)::RT` (which, for the variant that creates a closure over the value of the local variable `cl`, would be `ptr = @cfunction $cl(A, B)::RT` or `ptr = @cfunction local cl(A, B)::RT`)~~

### CODE REVIEW

File: stdlib/LibGit2/src/tree.jl [hunk 1]
```diff
@@ -12,27 +12,33 @@ subtree, traversing upwards through it, then traversing the next right subtree
...
 A negative value returned from `f` stops the tree walk. A positive value means
 that the entry will be skipped if `post` is `false`.
 """
-function treewalk(f::Function, tree::GitTree, payload=Any[], post::Bool = false)
-    cbf = cfunction(f, Cint, Tuple{Cstring, Ptr{Cvoid}, Ptr{Cvoid}})
-    cbf_payload = Ref{typeof(payload)}(payload)
+function treewalk(f, tree::GitTree, post::Bool = false)
     # NOTE: don't use @check/GitError directly, because the code can be arbitrary
+    payload = Any[ tree, f ]
+    cbf = @cfunction(function treewalk_callback(root_cstr::Cstring, entry_ptr::Ptr{Cvoid}, payload::Vector{Any})::Cint
```
Comment (maleadt) [inline stdlib/LibGit2/src/tree.jl]: Isn't it possible to capture `tree` and `f` instead of using the `payload` mechanism?

Comment (vtjnash) [reply stdlib/LibGit2/src/tree.jl]: Yes, it's just slower that way than to just use the C API correctly

File: base/c.jl [hunk 2]
```diff
@@ -16,24 +16,56 @@ respectively.
...
+    let construtor = false end
+end
+unsafe_convert(::Type{Ptr{Cvoid}}, cf::CFunction) = cf.ptr
+
 """
-    cfunction(f::Function, returntype::Type, argtypes::Type) -> Ptr{Cvoid}
+    @cfunction(callable, ReturnType, (ArgumentTypes...,)) -> Ptr{Cvoid}
+    @cfunction(\$callable, ReturnType, (ArgumentTypes...,)) -> CFunction
+
+Generate a C-callable function pointer from the Julia function `f`
```
Comment (JeffBezanson) [inline base/c.jl]: There is no `f` :)

File: base/exports.jl [hunk 3]
```diff
@@ -925,6 +925,7 @@ export
 
 # C interface
     cfunction,
```
Comment (JeffBezanson) [inline base/exports.jl]: Remove this?

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 4]
```diff
@@ -911,6 +917,34 @@ mylibvar = Libdl.dlopen("mylib")
 ccall(@dlsym("myfunc", mylibvar), Cvoid, ())
 ```
 
+## Closure cfunctions
+
+The first argument to [`@cfunction`](@ref) can be marked with a `$`, in which case
+the return value will instead be a `struct CFunction` which closes over the argument.
```
Comment (JeffBezanson) [inline doc/src/manual/calling-c-and-fortran-code.md]: Out of curiosity: what happens if I don't use a `$`, but I give a global name that's bound to a non-singleton function object?

**Comment by JeffBezanson** [comment]
I think the `$` syntax is good. It looks like the first argument can also be a function expression, which also gets `$` treatment?

File: stdlib/LibGit2/src/tree.jl (hunk 1 above)
Comment (StefanKarpinski) [reply stdlib/LibGit2/src/tree.jl]: I presume it's slower because closure support requires a stub that sets the locals and jumps to the "real" function? Whereas without any closed-over variables, it can just call directly.

Comment (vtjnash) [reply stdlib/LibGit2/src/tree.jl]: Yes, and in addition to the indirect function call, it also requires allocation to be able to track the lifetime, and runtime work to manage and handle that, etc.

File: doc/src/manual/calling-c-and-fortran-code.md (hunk 4 above)
Comment (vtjnash) [reply doc/src/manual/calling-c-and-fortran-code.md]: Like `ccall`, it's resolved by the macro to close over the value (not the binding), since that's almost always what you want anyways, and makes it easier to avoid accidentally shooting your self in the (gc) foot.

**Comment by vtjnash** [comment]
> which also gets $ treatment?

Not really. Because I felt that it read nicely to keep the function definition and use together this way, I'm (ab)using the knowledge that it got evaluated in global scope early, and then treated as a constant. In either case, it can be an arbitrary expression, the `$` keyword just indicates when to evaluate it.

**Comment by stevengj** [comment]
+1 for `ptr = @cfunction $cl(A, B)::RT`

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 5]
```diff
@@ -182,26 +185,26 @@ an integer less/greater than zero if `a` should appear before/after `b` (or zero
 is permitted). Now, suppose that we have a 1d array `A` of values in Julia that we want to sort
 using the `qsort` function (rather than Julia's built-in `sort` function). Before we worry about
 calling `qsort` and passing arguments, we need to write a comparison function that works for some
-arbitrary type T:
+arbitrary type T (which defines `<`):
```
Comment (nalimilan) [inline doc/src/manual/calling-c-and-fortran-code.md]: `T` isn't used in the example anymore.

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 6]
```diff
@@ -182,26 +185,26 @@ an integer less/greater than zero if `a` should appear before/after `b` (or zero
...
-           return convert(Cint, a < b ? -1 : a > b ? +1 : 0)::Cint
+julia> function mycompare(a, b)::Cint
+           return (a < b) ? -1 : ((a > b) ? +1 : 0)
        end
 mycompare (generic function with 1 method)
 ```
 
 Notice that we have to be careful about the return type: `qsort` expects a function returning
-a C `int`, so we must be sure to return `Cint` via a call to `convert` and a `typeassert`.
+a C `int`, so we annotate the return type of the function be sure it returns a `Cint`.
```
Comment (nalimilan) [inline doc/src/manual/calling-c-and-fortran-code.md]: Missing "to"?

**Comment by tknopp** [comment]
@vtjnash: Any chance that this will fix https://discourse.julialang.org/t/performance-issue-with-gtk-jl/6171. That inference on callbacks requires up to minutes is a major issue when using Gtk currently.

**Comment by giordano** [comment]
Did I miss it or this change isn't mentioned in `NEWS.md`?

File: base/c.jl [hunk 7]
```diff
@@ -16,24 +16,56 @@ respectively.
 """
 cglobal
 
+struct CFunction
+    ptr::Ptr{Cvoid}
+    f::Any
+    _1::Ptr{Cvoid}
+    _2::Ptr{Cvoid}
+    let construtor = false end
```
[the remark this answers is not in the document]
Comment (vtjnash) [reply base/c.jl]: It disables creation of the default constructors (ensuring that this type is not accidentally constructible from user code).
