### PR TITLE
Throw an exception for invalid hostnames in addprocs.

### LINKED ISSUE #20372: addprocs() hangs forever if the nodename does not exist
```
            _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> addprocs(["a"])
ssh: Could not resolve hostname a: nodename nor servname provided, or not known
^CERROR: InterruptException:
 in read_worker_host_port(::Pipe) at ./multi.jl:1589
 in connect(::Base.SSHManager, ::Int64, ::WorkerConfig) at ./managers.jl:385
 in create_worker(::Base.SSHManager, ::WorkerConfig) at ./multi.jl:1786
 in setup_launched_worker(::Base.SSHManager, ::WorkerConfig, ::Array{Int64,1}) at ./multi.jl:1733
 in (::Base.##649#653{Base.SSHManager,Array{Int64,1}})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in macro expansion at ./task.jl:327 [inlined]
 in #addprocs_locked#645(::Array{Any,1}, ::Function, ::Base.SSHManager) at ./multi.jl:1688
 in #addprocs_locked#645(::Array{Any,1}, ::Function, ::Base.SSHManager) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in (::Base.#kw##addprocs_locked)(::Array{Any,1}, ::Base.#addprocs_locked, ::Base.SSHManager) at ./<missing>:0
 in #addprocs#644(::Array{Any,1}, ::Function, ::Base.SSHManager) at ./multi.jl:1658
 in #addprocs#644(::Array{Any,1}, ::Function, ::Base.SSHManager) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in (::Base.#kw##addprocs)(::Array{Any,1}, ::Base.#addprocs, ::Base.SSHManager) at ./<missing>:0
 in #addprocs#744(::Bool, ::Cmd, ::Int64, ::Array{Any,1}, ::Function, ::Array{String,1}) at ./managers.jl:112
 in addprocs(::Array{String,1}) at ./managers.jl:111
```

JULIA_WORKER_TIMEOUT has no impact

```
julia> ENV["JULIA_WORKER_TIMEOUT"]
"1"
```

### PR DESCRIPTION
**Pull request by amitmurthy**
closes #20372

### CODE REVIEW

File: base/distributed/cluster.jl [hunk 1]
```diff
@@ -210,13 +210,27 @@ end
...
+
+        conninfo = wait(readtask)
+        ntries -= 1
         bind_addr, port = parse_connection_info(conninfo)
         if bind_addr != ""
             return bind_addr, port
         end
     end
+    close(io)
+    error("Error trying to read worker host:port from worker")
```
Comment (tkelman) [inline base/distributed/cluster.jl]: can we say anything more about what's causing this?

Comment (amitmurthy) [inline base/distributed/cluster.jl]: The user gets to see the cause since the ssh command prints an error message of the form `ssh: Could not resolve hostname a: nodename nor servname provided, or not known`. However that is not known in this function here - it could be any other ssh error, an error running the julia command or a timeout.

This PR betters the current behavior. Identifying the root cause which requires a bit more restructuring can be done in a separate PR.

File: base/distributed/cluster.jl [hunk 2]
```diff
@@ -210,13 +210,27 @@ end
 # The master process uses this to connect to the worker and subsequently
 # setup a all-to-all network.
 function read_worker_host_port(io::IO)
-    while true
-        conninfo = readline(io)
+    t0 = time()
+    timeout = worker_timeout()
+
+    ntries = 1000
```
Comment (tkelman) [inline base/distributed/cluster.jl]: should this be configurable instead of a hard-coded number?

Comment (amitmurthy) [inline base/distributed/cluster.jl]: We expect the workers to first print out the host:port it is listening on STDOUT.  Ignoring non-matching lines is to make the process of reading host:port a bit more resilient if the spawned command is printing informational/warning messages.

 In the case where the `ssh` command exits with an error, `readline(io)` returns an empty string (`io` being the output stream of the spawned command) and hence we need a limit on the number of tries.

I don't really see a need to make this configurable and documented at this time.

Comment (tkelman) [inline base/distributed/cluster.jl]: that should at least be put in a comment to explain what the code is doing and why 1000 is a reasonable value to use

Comment (amitmurthy) [inline base/distributed/cluster.jl]: OK.

File: base/distributed/cluster.jl [hunk 3]
```diff
@@ -210,12 +210,46 @@ end
...
+        readtask = @schedule readline(io)
+        yield()
+        while !istaskdone(readtask) && ((time() - t0) < timeout)
+            sleep(0.05)
+        end
+        !istaskdone(readtask) && break
+
+        conninfo = wait(readtask)
+        if conninfo == "" && !isopen(io)
+            error("Unable to read host:port string from worker. Launch command exited with error?")
```
Comment (tkelman) [inline base/distributed/cluster.jl]: is this a question?

File: test/distributed_exec.jl [hunk 4]
```diff
@@ -1269,19 +1269,79 @@ end
...
+
+struct ErrorSimulator <: ClusterManager
+    mode
+end
+
+function Base.launch(manager::ErrorSimulator, params::Dict, launched::Array, c::Condition)
+    exename = params[:exename]
+
+    if manager.mode == :timeout
+        io, pobj = open(pipeline(detach(setenv(`$(Base.julia_cmd(exename)) -e "sleep(10)"`)); stderr=STDERR), "r")
```
Comment (tkelman) [inline test/distributed_exec.jl]: --startup-file=no on these

File: base/distributed/cluster.jl (hunk 3 above)
Comment (amitmurthy) [inline base/distributed/cluster.jl]: In all probability the launch command exited with an error. However we cannot be sure that it actually exited with a non-zero code.

File: test/distributed_exec.jl [hunk 5]
```diff
@@ -1269,19 +1269,79 @@ end
...
+if DoFullTest
+    testruns = Any[(()->addprocs(["errorhost20372"]), "Unable to read host:port string from worker. Launch command exited with error?")]
+end
+append!(testruns, Any[
+            (()->addprocs(ErrorSimulator(:exit)), "Unable to read host:port string from worker. Launch command exited with error?"),
+            (()->addprocs(ErrorSimulator(:ntries)), "Unexpected output from worker launch command. Host:port string not found."),
+            (()->addprocs(ErrorSimulator(:timeout)), "Timed out waiting to read host:port string from worker.")
+        ])
+
+old_jwt = get(ENV, "JULIA_WORKER_TIMEOUT", :undefined)
```
Comment (tkelman) [inline test/distributed_exec.jl]: withenv might be cleaner here

Comment (amitmurthy) [inline test/distributed_exec.jl]: Cool! I was unaware of `withenv`

**Comment by tkelman** [comment]
appveyor failure is a new one, assertion failure during cholmod test? `Expression: jl_typeis(a, jl_array_any_type)`

**Comment by amitmurthy** [comment]
Log at https://gist.github.com/amitmurthy/1fb5609c74eff0dd7437779fb7e25919

Restarting AV job.
