### PR TITLE
Avoid broken kind type handling when compiling `isa`

### LINKED ISSUE #27078: isa_tfunc not working around broken subtyping in the way I hoped it would
```julia
julia> bar(T::Type{S}) where {S} = isa(T, UnionAll) ? bar(T.body) : T
bar (generic function with 1 method)

julia> V = Vector{Vector{T}} where T
Array{Array{T,1},1} where T

julia> bar(V)

ERROR: type DataType has no field body
Stacktrace:
 [1] getproperty at ./sysimg.jl:15 [inlined]
 [2] bar(::Type{Array{Array{T,1},1} where T}) at ./REPL[1]:1 (repeats 2 times)
 [3] top-level scope
```

If I remove the `Type{S} where S`:

```julia
julia> bar(T) = isa(T, UnionAll) ? bar(T.body) : T
bar (generic function with 1 method)

julia> V = Vector{Vector{T}} where T
Array{Array{T,1},1} where T

julia> bar(V)
Array{Array{T,1},1}
```

Title might not be quite correct, but the sadness this bug causes me is very real

### PR DESCRIPTION
**Pull request by jrevels**
This fixes https://github.com/JuliaLang/julia/issues/27078, https://github.com/jrevels/Cassette.jl/issues/42, and some other bugs with tuples.

I'm not at all a fan of my replacements for the tuple handling code here - I just need to get the aforementioned bugs fixed. It should be "more correct" than it was before (modulo any bugs I introduced...), but it feels like it's going to be slower w.r.t. to compilation, runtime, or both. I haven't done benchmarking yet, though. I would be **extremely grateful** for some tips on faster/cleaner alternatives (as long as they don't reintroduce the bugs I'm trying to fix). This might be another case in favor of making `ntuple` an intrinsic...EDIT: see comment below, moved the tuple changes out of this PR

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

### CODE REVIEW

File: src/cgutils.cpp [hunk 1]
```diff
@@ -1046,26 +1046,33 @@ static void emit_type_error(jl_codectx_t &ctx, const jl_cgval_t &x, Value *type,
...
+
+    // TODO: This optimization suffers from incorrectness issues due to broken subtyping for
+    // kind types (see https://github.com/JuliaLang/julia/issues/27078). For actual `isa`
+    // calls, this optimization should already have been performed upstream anyway, but
+    // having this optimization in codegen might still be beneficial for `typeassert`s
+    // if we can make it correct.
+    //
+    // Optional<bool> known_isa;
+    // if (x.constant)
+    //     known_isa = jl_isa(x.constant, type);
```
Comment (JeffBezanson) [inline src/cgutils.cpp]: Isn't this case correct? The result of an actual call to jl_isa seems like it should be correct by definition. I agree this optimization is probably redundant though.

Comment (jrevels) [reply src/cgutils.cpp]: Yeah, makes sense. I'll uncomment this branch out and see if it still passes tests (I assume it will).

File: base/tuple.jl [hunk 2]
```diff
@@ -219,48 +219,6 @@ fill_to_length(t::Tuple{}, val, ::Val{2}) = (val, val)
...
-end
-
-function _totuple(T, itr, s...)
-    @_inline_meta
-    y = iterate(itr, s...)
-    y === nothing && _totuple_err(T)
-    (convert(tuple_type_head(T), y[1]), _totuple(tuple_type_tail(T), itr, y[2])...)
-end
-
-_totuple(::Type{Tuple{Vararg{E}}}, itr, s...) where {E} = (collect(E, Iterators.rest(itr,s...))...,)
```
Comment (JeffBezanson) [inline base/tuple.jl]: This definition could be combined with the next by adding an `@isdefined(E)` check.

File: base/essentials.jl [hunk 3]
```diff
@@ -243,10 +216,14 @@ function typename(a::Union)
 end
 typename(union::UnionAll) = typename(union.body)
 
-convert(::Type{T}, x::T) where {T<:Tuple{Any, Vararg{Any}}} = x
-convert(::Type{Tuple{}}, x::Tuple{Any, Vararg{Any}}) = throw(MethodError(convert, (Tuple{}, x)))
-convert(::Type{T}, x::Tuple{Any, Vararg{Any}}) where {T<:Tuple} =
-    (convert(tuple_type_head(T), x[1]), convert(tuple_type_tail(T), tail(x))...)
```
Comment (JeffBezanson) [inline base/essentials.jl]: Do you have test cases where these fail?

File: base/essentials.jl [hunk 4]
```diff
@@ -141,33 +141,6 @@ end
 argtail(x, rest...) = rest
 tail(x::Tuple) = argtail(x...)
 
-# TODO: a better / more infer-able definition would pehaps be
-#   tuple_type_head(T::Type) = fieldtype(T::Type{<:Tuple}, 1)
```
Comment (JeffBezanson) [inline base/essentials.jl]: I think we should instate this definition of `tuple_type_head`, and add a correct implementation of `tuple_type_tail`.

File: base/iterators.jl [hunk 5]
```diff
@@ -749,9 +749,12 @@ julia> collect(Iterators.product(1:2, 3:5))
...
 product(iters...) = ProductIterator(iters)
 
-IteratorSize(::Type{ProductIterator{Tuple{}}}) = HasShape{0}()
-IteratorSize(::Type{ProductIterator{T}}) where {T<:Tuple} =
-    prod_iteratorsize( IteratorSize(tuple_type_head(T)), IteratorSize(ProductIterator{tuple_type_tail(T)}) )
+function IteratorSize(::Type{ProductIterator{T}}) where {T<:Tuple}
+    if isvatuple(T)
+        throw(ArgumentError("Cannot compute IteratorSize for ProductIterator{$T}"))
+    end
+    return reduce(prod_iteratorsize, HasShape{0}(), ntuple(i -> IteratorSize(fieldtype(T, i))), fieldcount(T))
```
Comment (JeffBezanson) [inline base/iterators.jl]: Indeed, using `ntuple` and `reduce` in cases like this is pretty hard on the compiler. We should try to make tuple_type_tail work, or manually recur over field indices.

File: base/essentials.jl (hunk 4 above)
Comment (jrevels) [reply base/essentials.jl]: Hmm....what would a correct implementation of `tuple_type_tail` look like when we have covariance + diagonal constraints?

Comment (JeffBezanson) [reply base/essentials.jl]: Well, you seem content with `fieldtype((Tuple{T,T} where T<:AbstractFloat), 1) == AbstractFloat`, so it might not be a problem.

`tuple_type_tail(Tuple{T,T} where T) == Tuple{T} where T` seems correct to me. Do you have a counterexample?

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/27736):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f16a1a8a64938556fb4137de31192cf52e9e96f8/6b81c5b_vs_dd49081/report.md)
cc @ararslan

File: base/essentials.jl (hunk 4 above)
Comment (jrevels) [reply base/essentials.jl]: Here's an example that seems wrong to me for master's `tuple_type_tail`:

```julia
julia> t = (Val(Any), 1, 1.0)
(Val{Any}(), 1, 1.0)

julia> typeof(t) <: Tuple{Val{T},T,T} where T
true

julia> typeof(Base.tail(t)) <: Base.tuple_type_tail(Tuple{Val{T},T,T} where T)
false
```

That's what I meant by covariance + diagonal constraints mucking things up, but I could totally be ignorant about the correct meaning of `tuple_type_tail` - apologies if so!

> Well, you seem content with fieldtype((Tuple{T,T} where T<:AbstractFloat), 1) == AbstractFloat, so it might not be a problem.

Yeah, @vtjnash told me `fieldtype` usually gets the right answers in these cases, which is why I replaced all the usages of `tuple_type_head`/`tuple_type_tail` with it. I'm just not sure how to use `fieldtype` to compute `tuple_type_tail` in general e.g. on vatuple types with unconstrained lengths.

File: base/essentials.jl (hunk 3 above)
Comment (jrevels) [reply base/essentials.jl]: The actual problem that I'm trying to workaround with this PR's `fieldtype`-based implementation is e.g.:

```julia
julia> using Cassette

julia> Cassette.@context Ctx
ERROR: invalid redefinition of constant Ctx
Stacktrace:
 [1] top-level scope at /Users/jarrettrevels/.julia/dev/Cassette/src/macros.jl:19

julia> Cassette.@overdub(Ctx(), convert(Tuple{Vararg{Float64}}, (1,2)))
ERROR: type DataType has no field body
Stacktrace:
 [1] execution at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:9 [inlined]
 [2] macro expansion at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:171 [inlined]
 [3] overdub_recurse at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:201 [inlined]
 [4] overdub_execute at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:35 [inlined]
 [5] getproperty at ./sysimg.jl:15 [inlined]
 [6] overdub_recurse(::Cassette.Context{getfield(Main, Symbol("##CtxName#350")),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(getproperty), ::Type{Vararg{Float64,N} where N}, ::Symbol) at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:0
 [7] overdub_execute at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:35 [inlined]
 [8] unwrap_unionall at ./essentials.jl:179 [inlined]
 [9] overdub_recurse(::Cassette.Context{getfield(Main, Symbol("##CtxName#350")),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(Base.unwrap_unionall), ::Type{Vararg{Float64,N} where N}) at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:0
 [10] overdub_execute at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:35 [inlined]
 [11] unwrapva at ./essentials.jl:224 [inlined]
 [12] overdub_recurse(::Cassette.Context{getfield(Main, Symbol("##CtxName#350")),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(Base.unwrapva), ::Type{Vararg{Float64,N} where N}) at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:0
 [13] overdub_execute at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:35 [inlined]
 [14] tuple_type_head at ./essentials.jl:154 [inlined]
 [15] overdub_recurse(::Cassette.Context{getfield(Main, Symbol("##CtxName#350")),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(Base.tuple_type_head), ::Type{Tuple{Vararg{Float64,N} where N}}) at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:0
 [16] overdub_execute at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:35 [inlined]
 [17] convert at ./essentials.jl:248 [inlined]
 [18] overdub_recurse(::Cassette.Context{getfield(Main, Symbol("##CtxName#350")),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(convert), ::Type{Tuple{Vararg{Float64,N} where N}}, ::Tuple{Int64,Int64}) at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:0
 [19] overdub_execute at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:35 [inlined]
 [20] #19 at /Users/jarrettrevels/.julia/dev/Cassette/src/macros.jl:94 [inlined]
 [21] overdub_recurse(::Cassette.Context{getfield(Main, Symbol("##CtxName#350")),Nothing,Cassette.NoPass,Nothing,Nothing}, ::getfield(Main, Symbol("##19#20"))) at /Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl:0
 [22] top-level scope at none:0
```

which seems to be from `tuple_type_head`/`tuple_type_tail` hitting some kindtype subtyping/inference issues that I don't fully understand. With this PR, I get the correct answer e.g.

```
julia> Cassette.@overdub(Ctx(), convert(Tuple{Vararg{Float64}}, (1,2)))
(1.0, 2.0)
```

**Comment by jrevels** [comment]
I've removed the more controversial tuple stuff from this PR, leaving only the `isa` fixes. I'll make a follow-up PR to try tackle the tuple stuff in a saner way

**Comment by jrevels** [comment]
So improving the `isa` tfunc just exposed a much sillier bug in the subtyping tests. I just pushed a fix for it in this PR, but here's the behavior on `master` for giggles:

```julia
julia> issubstrict(x, y) = (x <: y) && !(y <: x)
issubstrict (generic function with 1 method)

julia> f() = issubstrict(Int where T, Integer where T<:Integer)
f (generic function with 1 method)

# the SSA values that should be inferred as Type{T}s are inferred as Ts!!!
# but it doesn't matter because the `isa` tfunc still had a correct fallback of `Bool`
julia> code_typed(f, optimize = false)
1-element Array{Any,1}:
 CodeInfo(
1 1 ─      T@_3 = (Core.TypeVar)(:T)                                        │
  │   %2 = Core.UnionAll(:(_3::Core.Compiler.PartialTypeVar(T, true, true)), Main.Int)::Int64
  │        T@_2 = (Core.TypeVar)(:T, Main.Integer)                          │
  │   %4 = Core.UnionAll(:(_2::Core.Compiler.PartialTypeVar(T<:Integer, true, true)), Main.Integer)::Integer
  │   %5 = Main.issubstrict(%2, %4)::Bool                                   │
  └──      return %5                                                        │
) => Bool
```

**Comment by jrevels** [comment]
Okay, narrowed down the latest bug to this test case:

```julia
@noinline function g(f, a::T, ::Type{S} = Any) where {T, S}
    cf = @cfunction $f Ref{T} (Ref{T},)
    GC.gc()
    @assert cf === Base.cconvert(Ptr{Cvoid}, cf)
    GC.@preserve cf begin
        fptr = Base.unsafe_convert(Ptr{Cvoid}, cf)
        b = ccall(fptr, Ref{T}, (Ref{T},), a)
    end
end

g(identity, 1)
```

Note that you may need to try this several times (restarting Julia each time) to see errors here - sometimes it just outputs `1` as expected. When it does error, it seems that one of several different errors pops up, and which one you get is somewhat arbitrary...

```julia
julia> g(identity, 1)
ERROR: TypeError: in cfunction, in cfunction, expected Union{LinearAlgebra.Adjoint{T,Array{T,1}}, LinearAlgebra.RowVector{T,Array{T,1}}, LinearAlgebra.Transpose{T,Array{T,1}}, LinearAlgebra.AbstractTriangular{T,A} where A<:(Array{T,2} where T), LinearAlgebra.Hermitian{T,A} where A<:(Array{T,2} where T), LinearAlgebra.Symmetric{T,A} where A<:(Array{T,2} where T)}, got Int64
Stacktrace:
 [1] macro expansion at ./REPL[1]:89 [inlined]
 [2] macro expansion at ./gcutils.jl:87 [inlined]
 [3] g(::Function, ::Int64, ::Type{Any}) at ./REPL[1]:5
 [4] g(::Function, ::Int64) at ./REPL[1]:2
 [5] top-level scope at none:0
```

```julia
julia> g(identity, 1)
ERROR: TypeError: in cfunction, in cfunction, expected Core.Compiler.UseRef(nothing, 0), got Int64
Stacktrace:
 [1] macro expansion at ./REPL[1]:89 [inlined]
 [2] macro expansion at ./gcutils.jl:87 [inlined]
 [3] g(::Function, ::Int64, ::Type{Any}) at ./REPL[1]:5
 [4] g(::Function, ::Int64) at ./REPL[1]:2
 [5] top-level scope at none:0
```

```julia
julia> g(identity, 1)
ERROR: TypeError: in cfunction, in cfunction, expected Core.Compiler.UseRef(Core.UpsilonNode(Core.Compiler.Argument(2)), 2), got Int64
Stacktrace:
 [1] macro expansion at ./REPL[1]:89 [inlined]
 [2] macro expansion at ./gcutils.jl:87 [inlined]
 [3] g(::Function, ::Int64, ::Type{Any}) at ./REPL[1]:5
 [4] g(::Function, ::Int64) at ./REPL[1]:2
 [5] top-level scope at none:0
```

```julia
julia> g(identity, 1)
ERROR: TypeError: in cfunction, in cfunction, expected Core.Compiler.Pair{Int64,Any}(2, :((Base.arraylen)(Core.SSAValue(1)))), got Int64
Stacktrace:
 [1] macro expansion at ./REPL[1]:89 [inlined]
 [2] macro expansion at ./gcutils.jl:87 [inlined]
 [3] g(::Function, ::Int64, ::Type{Any}) at ./REPL[1]:5
 [4] g(::Function, ::Int64) at ./REPL[1]:2
 [5] top-level scope at none:0
```

...etc.

**Comment by jrevels** [comment]
Bump, any thoughts on the above? 

This PR works around one of the last correctness bugs that kills Cassette, if we can get it merged there will only be one last perf issue blocking the closure of #25492, and it would be wonderful if we could close that before v0.7 is released.

**Comment by maleadt** [comment]
Looks like a missing GC root:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-beta.73 (2018-06-28 14:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  jr/avoidbrokenkindtypes/e181dfe63e* (fork: 7 commits, 1 day)
|__/                   |  x86_64-unknown-linux-gnu

julia> @noinline function g(f, a::T, ::Type{S} = Any) where {T, S}
           cf = @cfunction $f Ref{T} (Ref{T},)
           GC.gc()
           @assert cf === Base.cconvert(Ptr{Cvoid}, cf)
           GC.@preserve cf begin
               fptr = Base.unsafe_convert(Ptr{Cvoid}, cf)
               b = ccall(fptr, Ref{T}, (Ref{T},), a)
           end
       end
g (generic function with 2 methods)

julia> g(identity, 1)
=================================================================
==13366==ERROR: AddressSanitizer: heap-use-after-free on address 0x610009f99278 at pc 0x7f8eb592b7e2 bp 0x7fff564f6600 sp 0x7fff564f65f8
READ of size 8 at 0x610009f99278 thread T0
    #0 0x7f8eb592b7e1 in jl_is_concrete_type julia/src/julia.h:1087:12
    #1 0x7f8eb592b17b in jl_isa julia/src/subtype.c:1248:9
LLVMSymbolizer: error reading file: No such file or directory.
    #2 0x7f8e9b81e6b7  (/memfd:julia-codegen (deleted)+0x216b7)
LLVMSymbolizer: error reading file: No such file or directory.
    #3 0x7f8e9b81e52a  (/memfd:julia-codegen (deleted)+0x2152a)
LLVMSymbolizer: error reading file: No such file or directory.
    #4 0x7f8e9b81e406  (/memfd:julia-codegen (deleted)+0x21406)
LLVMSymbolizer: error reading file: No such file or directory.
    #5 0x7f8e9b81e427  (/memfd:julia-codegen (deleted)+0x21427)
    #6 0x7f8eb57b5cde in jl_fptr_trampoline julia/src/gf.c:1813:12
    #7 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
    #8 0x7f8eb5dc4fb7 in do_call julia/src/interpreter.c:324:26
    #9 0x7f8eb5dc102b in eval_value julia/src/interpreter.c:428:16
    #10 0x7f8eb5dc2e3c in eval_stmt_value julia/src/interpreter.c:363:23
    #11 0x7f8eb5dbea90 in eval_body julia/src/interpreter.c:671:21
    #12 0x7f8eb5dbf8b5 in jl_interpret_toplevel_thunk_callback julia/src/interpreter.c:788:21
    #13 0x7f8eb581252b in enter_interpreter_frame (julia/build/sanitize/usr/bin/../lib/libjulia-debug.so.0.7+0x18852b)
    #14 0x7f8eb5dbfa90 in jl_interpret_toplevel_thunk julia/src/interpreter.c:797:26
    #15 0x7f8eb5883dc2 in jl_toplevel_eval_flex julia/src/toplevel.c:814:18
    #16 0x7f8eb5887b20 in jl_toplevel_eval julia/src/toplevel.c:823:12
    #17 0x7f8eb57fd4f3 in jl_toplevel_eval_in julia/src/builtins.c:633:13
    #18 0x7f8e9d3e2e0c in japi1_eval_3916 boot.jl:319
    #19 0x7f8eb57b90b6 in jl_fptr_args julia/src/gf.c:1823:12
    #20 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
LLVMSymbolizer: error reading file: No such file or directory.
    #21 0x7f8e9b80597b  (/memfd:julia-codegen (deleted)+0x897b)
LLVMSymbolizer: error reading file: No such file or directory.
    #22 0x7f8e9b8050da  (/memfd:julia-codegen (deleted)+0x80da)
    #23 0x7f8eb57b90b6 in jl_fptr_args julia/src/gf.c:1823:12
    #24 0x7f8eb57b5cde in jl_fptr_trampoline julia/src/gf.c:1813:12
    #25 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
    #26 0x7f8eb5824e87 in jl_apply julia/src/julia.h:1532:12
    #27 0x7f8eb5824c83 in start_task julia/src/task.c:268:19

0x610009f99278 is located 56 bytes inside of 128-byte region [0x610009f99240,0x610009f992c0)
freed by thread T0 here:
    #0 0x4c602b in free julia/deps/srccache/llvm-6.0.0/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:68:3
    #1 0x7f8eb58fb161 in jl_free_aligned julia/src/julia_internal.h:845:5
    #2 0x7f8eb58fb56b in sweep_big_list julia/src/gc.c:793:13
    #3 0x7f8eb58fac27 in sweep_big julia/src/gc.c:805:9
    #4 0x7f8eb58f99ac in gc_sweep_other julia/src/gc.c:1221:5
    #5 0x7f8eb58f2d29 in _jl_gc_collect julia/src/gc.c:2562:5
    #6 0x7f8eb58f1db2 in jl_gc_collect julia/src/gc.c:2633:13
LLVMSymbolizer: error reading file: No such file or directory.
    #7 0x7f8e9b81e4ff  (/memfd:julia-codegen (deleted)+0x214ff)
    #8 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
    #9 0x7f8eb5dc4fb7 in do_call julia/src/interpreter.c:324:26
    #10 0x7f8eb5dc102b in eval_value julia/src/interpreter.c:428:16
    #11 0x7f8eb5dc2e3c in eval_stmt_value julia/src/interpreter.c:363:23
    #12 0x7f8eb5dbea90 in eval_body julia/src/interpreter.c:671:21
    #13 0x7f8eb5dbf8b5 in jl_interpret_toplevel_thunk_callback julia/src/interpreter.c:788:21
    #14 0x7f8eb581252b in enter_interpreter_frame (julia/build/sanitize/usr/bin/../lib/libjulia-debug.so.0.7+0x18852b)
    #15 0x7f8eb5883dc2 in jl_toplevel_eval_flex julia/src/toplevel.c:814:18
    #16 0x7f8eb5887b20 in jl_toplevel_eval julia/src/toplevel.c:823:12
    #17 0x7f8eb57fd4f3 in jl_toplevel_eval_in julia/src/builtins.c:633:13
    #18 0x7f8e9d3e2e0c in japi1_eval_3916 boot.jl:319
    #19 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
LLVMSymbolizer: error reading file: No such file or directory.
    #20 0x7f8e9b80597b  (/memfd:julia-codegen (deleted)+0x897b)
LLVMSymbolizer: error reading file: No such file or directory.
    #21 0x7f8e9b8050da  (/memfd:julia-codegen (deleted)+0x80da)
    #22 0x7f8eb57b90b6 in jl_fptr_args julia/src/gf.c:1823:12
    #23 0x7f8eb57b5cde in jl_fptr_trampoline julia/src/gf.c:1813:12
    #24 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
    #25 0x7f8eb5824e87 in jl_apply julia/src/julia.h:1532:12
    #26 0x7f8eb5824c83 in start_task julia/src/task.c:268:19

previously allocated by thread T0 here:
    #0 0x4c7125 in __interceptor_posix_memalign julia/deps/srccache/llvm-6.0.0/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:157:3
    #1 0x7f8eb58e667a in jl_malloc_aligned julia/src/julia_internal.h:825:9
    #2 0x7f8eb58e63c9 in jl_gc_big_alloc julia/src/gc.c:742:30
    #3 0x7f8eb58e6c78 in jl_gc_pool_alloc julia/src/gc.c:948:12
    #4 0x7f8eb58e62c1 in jl_gc_alloc_ julia/src/julia_internal.h:274:13
    #5 0x7f8eb58f3cb1 in jl_gc_alloc julia/src/gc.c:2668:12
    #6 0x7f8eb589788c in jl_new_struct julia/src/datatype.c:761:22
    #7 0x7f8eb57a4161 in jl_rewrap_unionall julia/src/jltypes.c:963:9
    #8 0x7f8eb5a9eedf in emit_cfunction(jl_codectx_t&, _jl_value_t*, jl_cgval_t const&, _jl_value_t*, jl_svec_t*) julia/src/codegen.cpp:4784:22
    #9 0x7f8eb5a5844d in emit_expr(jl_codectx_t&, _jl_value_t*, long) julia/src/codegen.cpp:3962:16
    #10 0x7f8eb5af3815 in emit_ssaval_assign(jl_codectx_t&, long, _jl_value_t*) julia/src/codegen.cpp:3616:16
    #11 0x7f8eb5a610c9 in emit_stmtpos(jl_codectx_t&, _jl_value_t*, int) julia/src/codegen.cpp:3853:9
    #12 0x7f8eb599d02b in emit_function(_jl_method_instance_t*, _jl_code_info_t*, unsigned long, _jl_llvm_functions_t*, jl_cgparams_t const*) julia/src/codegen.cpp:6305:13
    #13 0x7f8eb598b878 in jl_compile_linfo julia/src/codegen.cpp:1177:17
    #14 0x7f8eb5a96990 in emit_invoke(jl_codectx_t&, jl_expr_t*, _jl_value_t*) julia/src/codegen.cpp:3101:37
    #15 0x7f8eb5a57def in emit_expr(jl_codectx_t&, _jl_value_t*, long) julia/src/codegen.cpp:3939:16
    #16 0x7f8eb5af3815 in emit_ssaval_assign(jl_codectx_t&, long, _jl_value_t*) julia/src/codegen.cpp:3616:16
    #17 0x7f8eb5a610c9 in emit_stmtpos(jl_codectx_t&, _jl_value_t*, int) julia/src/codegen.cpp:3853:9
    #18 0x7f8eb599d02b in emit_function(_jl_method_instance_t*, _jl_code_info_t*, unsigned long, _jl_llvm_functions_t*, jl_cgparams_t const*) julia/src/codegen.cpp:6305:13
    #19 0x7f8eb598b878 in jl_compile_linfo julia/src/codegen.cpp:1177:17
    #20 0x7f8eb57c882e in jl_compile_method_internal julia/src/gf.c:1778:21
    #21 0x7f8eb57b5c9c in jl_fptr_trampoline julia/src/gf.c:1812:25
    #22 0x7f8eb57cfe0a in jl_apply_generic julia/src/gf.c:2151:23
    #23 0x7f8eb5dc4fb7 in do_call julia/src/interpreter.c:324:26
    #24 0x7f8eb5dc102b in eval_value julia/src/interpreter.c:428:16
    #25 0x7f8eb5dc2e3c in eval_stmt_value julia/src/interpreter.c:363:23
    #26 0x7f8eb5dbea90 in eval_body julia/src/interpreter.c:671:21
    #27 0x7f8eb5dbf8b5 in jl_interpret_toplevel_thunk_callback julia/src/interpreter.c:788:21
    #28 0x7f8eb581252b in enter_interpreter_frame (julia/build/sanitize/usr/bin/../lib/libjulia-debug.so.0.7+0x18852b)
    #29 0x7f8eb5883dc2 in jl_toplevel_eval_flex julia/src/toplevel.c:814:18

SUMMARY: AddressSanitizer: heap-use-after-free julia/src/julia.h:1087:12 in jl_is_concrete_type
Shadow bytes around the buggy address:
  0x0c20813eb1f0: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c20813eb200: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c20813eb210: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c20813eb220: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c20813eb230: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
=>0x0c20813eb240: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd[fd]
  0x0c20813eb250: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c20813eb260: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c20813eb270: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c20813eb280: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c20813eb290: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13366==ABORTING
```

Looks like `declrt` doesn't get properly rooted after `emit_cfunction` returns?

File: src/cgutils.cpp [hunk 6]
```diff
@@ -1060,17 +1060,25 @@ static void emit_type_error(jl_codectx_t &ctx, const jl_cgval_t &x, Value *type,
...
-        known_isa = true;
-    else {
-        intersected_type = jl_type_intersection(x.typ, type);
-        if (intersected_type == (jl_value_t*)jl_bottom_type)
-            known_isa = false;
     }
+    // else if (jl_subtype(x.typ, type))
+    //     known_isa = true;
+    // else {
+    //     intersected_type = jl_type_intersection(x.typ, type);
```
[the remark this answers is not in the document]
Comment (jrevels) [reply src/cgutils.cpp]: Nope, doesn't fix the MWE above. I did push the commit to uncomment the branch, though, since it seems more correct to my naive eyes and doesn't hurt the test cases I'm trying to fix with this PR.

File: src/cgutils.cpp [hunk 7]
```diff
@@ -1060,13 +1060,18 @@ static void emit_type_error(jl_codectx_t &ctx, const jl_cgval_t &x, Value *type,
...
     Optional<bool> known_isa;
     jl_value_t *intersected_type = type;
     if (x.constant)
         known_isa = jl_isa(x.constant, type);
-    else if (jl_subtype(x.typ, type))
-        known_isa = true;
-    else {
+    else if (jl_subtype(x.typ, type)) {
+        // known_isa = true;
+    } else {
```
Comment (jrevels) [inline src/cgutils.cpp]: Okay, the minimal change that my tests hinge on seems to be here. [Here is a gist of the tests I'm using to check this PR](https://gist.github.com/jrevels/4e56e78d91d53ca29af73b5b36d506d0).

Before commenting out `known_isa = true`, some of the tests fail. 

After commenting out `known_isa = true`, all of them pass except for the `g(identity, 1)` MWE reported earlier.

Does anybody know (or can help figure out) how to get all of these tests passing so this can be merged?

**Comment by jrevels** [comment]
Rebased to avoid going stale. Is there anything extra I should be doing to get responses to the questions in this PR? If I should do anything before requesting more attention on this, please tell me and I'll do it. 

Sorry for the repeat bumping, I just fear that this PR will end up like https://github.com/JuliaLang/julia/pull/24852, which was waiting on review for *months* that never came.

**Comment by DokFaust** [comment]
In an unpatched version of Julia, `@code_warntype`

**Comment by DokFaust** [comment]
Probably you know this, but maybe it is interesting.
On Julia master, without the patch, `@code_warntype` returns
```
julia> @code_warntype g(identity,1)
Variables:
  #self#::typeof(g)
  f::typeof(identity)
  a::Int64

Body:
  begin
      $(Expr(:invoke, MethodInstance for g(::Function, ::Int64, ::Type{Any}), :(#self#), :(f), 
:(a), :(Main.Any)))::Int64
      return Core.SSAValue(1)
  end::Int64
```
while after the patch,

**Comment by pablosanjose** [comment]
I cannot reproduce on MacOS. I tried the test case on more than 30 freshly launched REPLs and it didn't error.
```
julia> versioninfo()
Julia Version 0.7.0-beta.152
Commit ee07b8cb23 (2018-07-04 17:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin17.6.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

File: src/subtype.c [hunk 8]
```diff
@@ -1165,6 +1165,13 @@ JL_DLLEXPORT int jl_types_equal(jl_value_t *a, jl_value_t *b)
     return jl_subtype(a, b) && jl_subtype(b, a);
 }
 
+JL_DLLEXPORT int jl_is_not_broken_subtype(jl_value_t *a, jl_value_t *b)
+{
+    // TODO: the final commented out check here isn't correct; it should be closer to the
+    // `issingletype` check used by `isnotbrokensubtype` in `base/compiler/typeutils.jl`
+    return !jl_is_kind(b) || !jl_is_type_type(a); // || jl_is_datatype_singleton((jl_datatype_t*)jl_tparam0(a));
+}
+
```
Comment (jrevels) [inline src/subtype.c]: I've added this check before the problematic subtyping check in `emit_isa` and [it allows the tests in the previously provided gist](https://gist.github.com/jrevels/4e56e78d91d53ca29af73b5b36d506d0) to pass, including the final heisenbuggy one. It's emulating the `isbrokensubtype` predicate we're using in the `isa` tfunc for this PR. As you can see by the TODO, this predicate is probably overly strict. 

BTW, thanks to @maleadt, @DokFaust, @pablosanjose for looking into this. Much appreciated! 

Would also be nice to get some review from core codegen contributors. If tests pass here, then I'm going to merge right away unless there are any objections.

**Comment by jrevels** [comment]
Tests pass locally (besides one weird libgit2 test that's certainly unrelated). Fingers crossed for CI...

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by JeffBezanson** [comment]
Looks ok to me. Do we know why that inference regression in test/sets happened?

**Comment by jrevels** [comment]
Checking back, it looks like only one of these actually regressed:

```julia
@inferred replace([1, missing], missing=>2)
ERROR: return type Array{Int64,1} does not match inferred return type Union{Array{Int64,1}, Array{Union{Missing, Int64},1}}
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at none:0
```

The other one is actually fine, I must've made a mistake earlier when testing. I'll remove the `@test_broken` on that one. 

> Do we know why that inference regression in test/sets happened?

The point of the new `isnotbrokensubtype` check here is to try to prevent const propagation that depends potentially broken subtype checks; it seems this is one of the const propagations that is now prevented. 

On `master`:

```julia
# grab the actual anonymous function that exhibits the regression 
julia> f = eval((@code_lowered replace([1, missing], missing=>2)).code[2].args[2])

julia> code_typed(f, map(Core.Typeof, (nothing, replace, [1, missing], missing=>2)), optimize=false)
1-element Array{Any,1}:
 CodeInfo(
448 1 ─       Core.NewvarNode(:(T))                                         │
    │         Core.NewvarNode(:(U))                                         │
    │         :(V = (Core._apply)(Base.promote_valuetype, Core.Compiler.Argument(5)))
449 │   %4  = Base.isa(%%count, Base.Nothing)::Core.Compiler.Const(true, false)
    │         Core.SSAValue(4)                                              │
450 │   %6  = Base.eltype(%%A)::Core.Compiler.Const(Union{Missing, Int64}, false)
    │   %7  = Core.tuple(%6)::Core.Compiler.Const((Union{Missing, Int64},), false)
    │   %8  = Core._apply(Base.subtract_singletontype, %7, %%old_new)::Core.Compiler.Const(Int64, false)
    │         :(T = (Base.promote_type)(Core.SSAValue(8), V::Core.Compiler.Const(Int64, false)))
451 │   %10 = Base._similar_or_copy(%%A, :(_7::Core.Compiler.Const(Int64, false)))::Array{Int64,1}
    │   %11 = Base.typemax(Base.Int)::Core.Compiler.Const(9223372036854775807, false)
    │   %12 = Base.replace_pairs!(%10, %%A, %11, %%old_new)::Array{Int64,1} │
    └──       return %12                                                    │
453 2 ─       Core.Compiler.Const(:((Base.eltype)(A)), false)               │
    │         Core.Compiler.Const(:(U = (Base.promote_type)(Core.SSAValue(14), V)), false)
454 │         Core.Compiler.Const(:((Base._similar_or_copy)(A, U)), false)  │
    │         Core.Compiler.Const(:((Base.check_count)(count)), false)      │
    │         Core.Compiler.Const(:((Base.replace_pairs!)(Core.SSAValue(16), A, Core.SSAValue(17), old_new)), false)
    └──       Core.Compiler.Const(:(return Core.SSAValue(18)), false)       │
) => Array{Int64,1}
```

This branch:

```julia
julia> code_typed(f, map(Core.Typeof, (nothing, replace, [1, missing], missing=>2)), optimize=false)
1-element Array{Any,1}:
 CodeInfo(
448 1 ─       Core.NewvarNode(:(T))                                         │
    │         Core.NewvarNode(:(U))                                         │
    │         :(V = (Core._apply)(Base.promote_valuetype, Core.Compiler.Argument(5)))
449 │   %4  = Base.isa(%%count, Base.Nothing)::Core.Compiler.Const(true, false)
    │         Core.SSAValue(4)                                              │
450 │   %6  = Base.eltype(%%A)::Core.Compiler.Const(Union{Missing, Int64}, false)
    │   %7  = Core.tuple(%6)::Core.Compiler.Const((Union{Missing, Int64},), false)
    │   %8  = Core._apply(Base.subtract_singletontype, %7, %%old_new)::Union{Type{Int64}, Type{Union{Missing, Int64}}}
    │         :(T = (Base.promote_type)(Core.SSAValue(8), V::Core.Compiler.Const(Int64, false)))
451 │   %10 = Base._similar_or_copy(%%A, %%T)::Union{Array{Int64,1}, Array{Union{Missing, Int64},1}}
    │   %11 = Base.typemax(Base.Int)::Core.Compiler.Const(9223372036854775807, false)
    │   %12 = Base.replace_pairs!(%10, %%A, %11, %%old_new)::Union{Array{Int64,1}, Array{Union{Missing, Int64},1}}
    └──       return %12                                                    │
453 2 ─       Core.Compiler.Const(:((Base.eltype)(A)), false)               │
    │         Core.Compiler.Const(:(U = (Base.promote_type)(Core.SSAValue(14), V)), false)
454 │         Core.Compiler.Const(:((Base._similar_or_copy)(A, U)), false)  │
    │         Core.Compiler.Const(:((Base.check_count)(count)), false)      │
    │         Core.Compiler.Const(:((Base.replace_pairs!)(Core.SSAValue(16), A, Core.SSAValue(17), old_new)), false)
    └──       Core.Compiler.Const(:(return Core.SSAValue(18)), false)       │
) => Union{Array{Int64,1}, Array{Union{Missing, Int64},1}}
```

Note the difference at `%8`. 

There might be a way to make `isnotbrokensubtype` less strict without sacrificing the correctness needed to pass the aforementioned tests, but that's probably out of my league.

**Comment by jrevels** [comment]
More minimal:

master:

```julia
julia> code_typed(Base.subtract_singletontype, (Type{Union{Missing,Int}}, Pair{Missing,Int}), optimize=false)
1-element Array{Any,1}:
 CodeInfo(
466 1 ─ %1 = Base.issingletontype(:($(Expr(:static_parameter, 2))))::Core.Compiler.Const(true, true)
    │        Core.SSAValue(1)                                               │
467 │   %3 = :(Core.Compiler)::Core.Compiler.Const(Core.Compiler, false)    │
    │   %4 = Base.getproperty(%3, :typesubtract)::Core.Compiler.Const(Core.Compiler.typesubtract, false)
    │   %5 = :($(Expr(:static_parameter, 1)))::Core.Compiler.Const(Union{Missing, Int64}, false)
    │   %6 = %4(%5, :($(Expr(:static_parameter, 2))))::Core.Compiler.Const(Int64, false)
    └──      return %6                                                      │
469 2 ─      Core.Compiler.Const(:(return $(Expr(:static_parameter, 1))), false)
) => Type{Int64}
```

this PR:

```julia
julia> code_typed(Base.subtract_singletontype, (Type{Union{Missing,Int}}, Pair{Missing,Int}), optimize=false)
1-element Array{Any,1}:
 CodeInfo(
466 1 ─ %1 = Base.issingletontype(:($(Expr(:static_parameter, 2))))::Core.Compiler.Const(true, true)
    │        Core.SSAValue(1)                                               │
467 │   %3 = :(Core.Compiler)::Core.Compiler.Const(Core.Compiler, false)    │
    │   %4 = Base.getproperty(%3, :typesubtract)::Core.Compiler.Const(Core.Compiler.typesubtract, false)
    │   %5 = :($(Expr(:static_parameter, 1)))::Core.Compiler.Const(Union{Missing, Int64}, false)
    │   %6 = %4(%5, :($(Expr(:static_parameter, 2))))::Union{Type{Int64}, Type{Union{Missing, Int64}}}
    └──      return %6                                                      │
469 2 ─      Core.Compiler.Const(:(return $(Expr(:static_parameter, 1))), false)
) => Union{Type{Int64}, Type{Union{Missing, Int64}}}
```

**Comment by jrevels** [comment]
Gah tests are failing now on the merge commit with master due to https://github.com/JuliaLang/julia/pull/27912

**Comment by jrevels** [comment]
Man, this was so close. Finally got tests passing, and then got sniped at the finish line by changes to master...

I've rebased and will investigate.

**Comment by jrevels** [comment]
@Keno did #27912 depend on constant propagation occurring upstream/downstream from the optimizer? This PR disables constant propagation for certain cases where it could yield incorrect results, and after rebasing, the tests from #27912 are failing here. Any tips/insights?

**Comment by Keno** [comment]
Which tests are you seeing fail?

**Comment by jrevels** [comment]
The ones added in #27912:

```
# Issue 27910
f27910() = ((),)[2]
@test_throws BoundsError f27910()

# Issue 9765
f9765(::Bool) = 1
g9765() = f9765(isa(1, 1))
@test_throws TypeError g9765()
```

With this PR, it seems they're behaving the way they would before #27912, i.e.

```
# no BoundsError
julia> f27910()
()

# no TypeError
julia> g9765()
1
```

All other tests are passing.

**Comment by Keno** [comment]
Are you sure you didn't just accidentally forget to rebuild the sysimage?

**Comment by jrevels** [comment]
> Are you sure you didn't just accidentally forget to rebuild the sysimage?

I'm not sure of anything these days :p failures are happening on CI here: https://freebsdci.julialang.org/#/builders/1/builds/11024/steps/8/logs/stdio

**Comment by jrevels** [comment]
Errr actually it looks like only `g9765()` is problematic (returns `1`), and `f27910()` is correctly throwing a `BoundsError`

**Comment by jrevels** [comment]
Reason might be because here:

```
julia> isa_tfunc(1, 1)
Core.Compiler.Const(false, false)
```

while on master:

```
julia> isa_tfunc(Int, Int)
Bool
```

(where `isa_tfunc = Core.Compiler.T_FFUNC_VAL[findfirst(x->x===isa, Core.Compiler.T_FFUNC_KEY)][3]`)

**Comment by Keno** [comment]
Yep, that'd do it (though of course `Union{}` would be a better answer from the tfunc here). I'll look into rewriting that part of the inliner.

File: base/compiler/tfuncs.jl [hunk 9]
```diff
@@ -391,15 +394,17 @@ add_tfunc(isa, 2, 2,
                   if t === Bottom
                       return Const(false)
```
Comment (jrevels) [inline base/compiler/tfuncs.jl]: > though of course Union{} would be a better answer from the tfunc here

Changing this to `return Bottom` seems to fix `g9765()`, and I *think* is correct based on this PR's `instanceof_tfunc` implementation. Unsure, though, this stuff hurts my brain 😛 

I'll run tests and see how it goes.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27736#issuecomment-403083836) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/465fb595607d6ce3a0e74fcf551cde2b9eb07dcf/6c2d757_vs_feaee9e/report.md). cc @ararslan

File: base/compiler/tfuncs.jl (hunk 9 above)
Comment (vtjnash) [reply base/compiler/tfuncs.jl]: That doesn't look quite right. Here's the patch I'm using over in #27972 which needed this same fix:
```diff
diff --git a/base/compiler/tfuncs.jl b/base/compiler/tfuncs.jl
index 161e26e984..a7b9d5fa58 100644
--- a/base/compiler/tfuncs.jl
+++ b/base/compiler/tfuncs.jl
@@ -388,12 +390,18 @@ add_tfunc(typeassert, 2, 2,
               return typeintersect(v, t)
           end, 4)
 add_tfunc(isa, 2, 2,
-          function (@nospecialize(v), @nospecialize(t))
-              t, isexact = instanceof_tfunc(t)
+          function (@nospecialize(v), @nospecialize(tt))
+              t, isexact = instanceof_tfunc(tt)
+              if t === Bottom
+                  # check if t could be equivalent to typeof(Bottom), since that's valid in `isa`, but the set of `v` is empty
+                  # if `t` cannot have instances, it's also invalid on the RHS of isa
+                  if typeintersect(widenconst(tt), Type) === Union{}
+                      return Union{}
+                  end
+                  return Const(false)
+              end
               if !has_free_typevars(t)
-                  if t === Bottom
-                      return Const(false)
-                  elseif v ⊑ t
+                  if v ⊑ t
                       if isexact
                           return Const(true)
                       end
@@ -401,7 +409,7 @@ add_tfunc(isa, 2, 2,
                       # this tests for knowledge of a leaftype appearing on the LHS
                       # (ensuring the isa is precise)
                       return Const(false)
-                  elseif isexact && typeintersect(v, t) === Bottom
+                  elseif typeintersect(v, t) === Bottom
                       if !iskindtype(v) #= subtyping currently intentionally answers this query incorrectly for kinds =#
                           return Const(false)
                       end
diff --git a/test/compiler/compiler.jl b/test/compiler/compiler.jl
index 9c6d32d529..e22b12f216 100644
--- a/test/compiler/compiler.jl
+++ b/test/compiler/compiler.jl
@@ -1189,7 +1189,7 @@ let isa_tfunc = Core.Compiler.T_FFUNC_VAL[
     @test isa_tfunc(typeof(Union{}), Const(Int)) === Const(false) # any result is ok
     @test isa_tfunc(typeof(Union{}), Const(Union{})) === Const(false)
     @test isa_tfunc(typeof(Union{}), typeof(Union{})) === Const(false)
-    @test isa_tfunc(typeof(Union{}), Union{}) === Const(false) # any result is ok
+    @test isa_tfunc(typeof(Union{}), Union{}) === Union{}
     @test isa_tfunc(typeof(Union{}), Type{typeof(Union{})}) === Const(true)
     @test isa_tfunc(typeof(Union{}), Const(typeof(Union{}))) === Const(true)
     let c = Conditional(Core.SlotNumber(0), Const(Union{}), Const(Union{}))
@@ -1204,7 +1204,7 @@ let isa_tfunc = Core.Compiler.T_FFUNC_VAL[
     @test isa_tfunc(Val{1}, Type{Val{T}} where T) === Bool
     @test isa_tfunc(Val{1}, DataType) === Bool
     @test isa_tfunc(Any, Const(Any)) === Const(true)
-    @test isa_tfunc(Any, Union{}) === Const(false) # any result is ok
+    @test isa_tfunc(Any, Union{}) === Union{}
     @test isa_tfunc(Any, Type{Union{}}) === Const(false)
     @test isa_tfunc(Union{Int64, Float64}, Type{Real}) === Const(true)
     @test isa_tfunc(Union{Int64, Float64}, Type{Integer}) === Bool
```

Comment (jrevels) [reply base/compiler/tfuncs.jl]: Ah, nice - this fixes the `isa_tfunc(typeof(Union{}), Const(Union{}))` that I broke with my version of the fix (it should indeed return `Const(false)`, but my patch was making it return `Union{}`.

Thanks!

**Comment by jrevels** [comment]
Perf changes are spurious, the one CI failure is from curl failing to download something.
