### PR TITLE
fix #34824, improve various cases of showing method signatures

### LINKED ISSUE #34824: invalid error message for type parameter
```julia
julia> VERSION
v"1.5.0-DEV.299"

julia> struct Foo{T<:Real,TX<:AbstractVector{T},TFX}
       Δ::T
       x::TX
       fx::TFX
       residual_norm::T
       converged::Bool
       iterations::Int
       end

julia> function Foo(Δ::T1, x::AbstractVector{T2}, fx, residual_norm::T3, converged,
       iterations) where {T1 <: Real, T2 <: Real, T3 <: Real}
       T = promote_type(T1, T2, T3)
       Tx = T.(x)
       Foo{T,typeof(Tx)}(T(Δ), Tx, fx, T(residual_norm), converged, iterations)
       end
Foo

julia> Foo(1, [1.0, 2.0], nothing, 1.0, true, 0)
ERROR: MethodError: no method matching Foo{Float64,Array{Float64,1},TFX} where TFX(::Float64, ::Array{Float64,1}, ::Nothing, ::Float64, ::Bool, ::Int64)
Stacktrace:
 [1] Foo(::Int64, ::Array{Float64,1}, ::Nothing, ::Float64, ::Bool, ::Int64) at ./REPL[3]:5
 [2] top-level scope at REPL[4]:1
```

Note the `where TFX(::Float64, ::Array{Float64,1}, ::Nothing, ::Float64, ::Bool, ::Int64)`.

([discussion on Discourse](https://discourse.julialang.org/t/repeated-type-parameter-in-method-error-of-promoting-constructor/34892))

### PR DESCRIPTION
**Pull request by JeffBezanson**
The code for this was duplicated several times (more than 3, depending how you count), with all sorts of problems. Here are some examples.

Before:
```
julia> methods(Complex)
# 7 methods for type constructor:
[1] (::Type{Complex})(x::Real) in Base at complex.jl:16
...

julia> methods(Complex{Int})
# 7 methods for type constructor:
[1] (::Type{Complex{T}})(x::AbstractIrrational) where T<:Real in Base at irrationals.jl:34
...

julia> (Complex{T} where T<:Integer)(1.2)
ERROR: MethodError: no method matching Complex{T} where T<:Integer(::Float64)
Closest candidates are:
  Complex{T} where T<:Integer(::T) where T<:Number at boot.jl:715

julia> (::Union{Nothing,Int})(::Nothing) = nothing

julia> nothing("")
ERROR: MethodError: no method matching (::Nothing)(::String)
Closest candidates are:
  Any(::Nothing) at REPL[6]:1
```

After:
```
julia> methods(Complex)
# 7 methods for type constructor:
[1] Complex(x::Real) in Base at complex.jl:16
...

julia> methods(Complex{Int})
# 7 methods for type constructor:
[1] Complex{T}(x::AbstractIrrational) where T<:Real in Base at irrationals.jl:47
...

julia> (Complex{T} where T<:Integer)(1.2)
ERROR: MethodError: no method matching (Complex{T} where T<:Integer)(::Float64)
Closest candidates are:
  (::Type{T})(::T) where T<:Number at boot.jl:715

julia> (::Union{Nothing,Int})(::Nothing) = nothing

julia> nothing("")
ERROR: MethodError: no method matching (::Nothing)(::String)
Closest candidates are:
  (::Union{Nothing, Int64})(::Nothing) at REPL[1]:1
```

Fixes #34824. Replaces #35311.

Discussion questions:
- I decided to print methods on unionalls as `(Foo{T} where T)(x)` even though that is not currently valid input syntax. With #35861 it would be, so I think it's ok.
- The "closest candidates" printing used to show the *called* type in the head of each signature, instead of the type from the definition (see third example above). That was probably intentional and I can see a case for it, but I think it's confusing because it looks like it's showing definitions that don't actually exist. I think we should show the same thing that e.g. `methods(t)` shows.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: base/show.jl [hunk 1]
```diff
@@ -1742,6 +1742,30 @@ function demangle_function_name(name::AbstractString)
...
+        show(io, f)
+        parens && print(io, ")")
+    else
+        if html
+            print(io, "($fargname::<b>", ft, "</b>)")
+        else
+            print(io, "($fargname::", ft, ")")
+        end
+    end
+end
```
Comment (vtjnash) [inline base/show.jl:1767]:
```suggestion
    nothing
end
```
(otherwise may be odd this function signature was ::union(nothing, false))
