### PR TITLE
Mark min_world and max_world as non-const

### LINKED ISSUE #361: `ErrorException("setfield!: const field .max_world of type CodeInstance cannot be changed")`
On 1.9: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c6440b9_vs_d0156b5/Checkpointing.primary.log

### PR DESCRIPTION
**Pull request by vchuravy**
As noted in https://github.com/JuliaLang/julia/pull/46203#issuecomment-1286882083

Fixes JuliaGPU/GPUCompiler.jl#361

### CODE REVIEW

File: src/jltypes.c [hunk 1]
```diff
@@ -2572,7 +2572,7 @@ void jl_init_types(void) JL_GC_DISABLED
                         jl_emptysvec,
                         0, 1, 1);
     jl_svecset(jl_code_instance_type->types, 1, jl_code_instance_type);
-    const static uint32_t code_instance_constfields[1] = { 0b000001010111101 }; // Set fields 1, 3-6, 8, 10 as const
+    const static uint32_t code_instance_constfields[1]  = { 0b000001010110001 }; // Set fields 1, 3-6, 8, 10 as const
```
Comment (KristofferC) [inline src/jltypes.c:2575]: Does the comment need updating?

Comment (vchuravy) [inline src/jltypes.c:2575]:
```suggestion
    const static uint32_t code_instance_constfields[1]  = { 0b000001010110001 }; // Set fields 1, 5-6, 8, 10 as const
```

**Comment by maleadt** [comment]
```
Test Failed at /cache/build/default-amdci5-0/julialang/julia-master/julia-58b2963121/share/julia/test/core.jl:26
  Expression: Set((fieldname(T, i) for i = 1:fieldcount(T) if isconst(T, i))) == Set(c)
   Evaluated: Set([:rettype_const, :def, :ipo_purity_bits, :argescapes, :rettype]) == Set([:max_world, :rettype_const, :def, :ipo_purity_bits, :min_world, :argescapes, :rettype])
```

Test needs to be updated.
