### PR TITLE
Fix #23646: relpath recognizes Windows drive letters

### LINKED ISSUE #23646: relpath broken for windows
The `relpath` function does not seem to be working properly for Windows.  The first two bad cases below are caused by a failure to be case-insensitive.  The third bad case is caused by lack of recognition of drive letters.

```julia
julia> relpath("c:/Users/vavasis/Documents", "c:/users/vavasis/Documents")
"..\\..\\..\\Users\\vavasis\\Documents"

julia> relpath("c:/Users/vavasis/Documents", "C:/users/vavasis/Documents")
"..\\..\\..\\..\\c:\\Users\\vavasis\\Documents"

julia> relpath("c:/Users/vavasis/Documents", "E:/")
"..\\c:\\Users\\vavasis\\Documents"
```

### PR DESCRIPTION
**Pull request by belamenso**
Fixes #23646.
This pull introduces two changes in behavior of `relpath`. All changes and tests should apply only to platforms on which `Sys.iswindows()` is true.
1. For `relpath(a,b)` where `a` and `b` are from different Windows drives, `abspath(a)` is returned.
1. Paths are still case-sensitive, but not in the drive letter part preventing eg. `relpath("C:\\a", "c:\\") == "..\\C:\\a"`.

### CODE REVIEW

**Comment by belamenso** [comment]
Can somebody review this?

**Comment by musm** [comment]
Thanks, this does improve the situation, but I think there are still issues we need to resolve with `relpath`, which might require bigger changes.  See my comments in https://github.com/JuliaLang/julia/issues/23646

**Comment by musm** [comment]
In particular
```julia
relpath("d:x","d:a/b/c")  returns "..\\..\\..\\d:x" but should return  "..\\..\\..\\x"      ("d:a/b/c" is a relative path in the current directory in the d drive)
```

**Comment by belamenso** [comment]
The code should now correctly handle drive prefixes in relative paths, as verified by additional tests. I did not implement throwing `ArgumentError` for `relpath` between different drives, in such cases the absolute path of the requested destination is returned. Adding an exception to this method would be a breaking change.

```julia
relpath("d:x","d:a/b/c") == "..\\..\\..\\x"
relpath("c:/Users/vavasis/Documents", "E:/") == "c:\\Users\\vavasis\\Documents"
relpath("D","d") == "..\\D"
relpath("d:\\x", "D:\\x") == "."
relpath("c:/Users/vavasis/Documents", "C:/users/vavasis/Documents") == "..\\..\\..\\Users\\vavasis\\Documents"
relpath("c:/Users/vavasis/Documents", "c:/users/vavasis/Documents") == "..\\..\\..\\Users\\vavasis\\Documents"
```
@musm

**Review by musm — APPROVED** [review]

**Comment by musm** [comment]
Can you add to the doc string  about case insensitive of drive letters on Windows and also that if there's a drive mismatch we return the first path?

**Comment by belamenso** [comment]
Done.

File: base/path.jl [hunk 1]
```diff
@@ -495,15 +495,23 @@ contractuser(path::AbstractString)
 Return a relative filepath to `path` either from the current directory or from an optional
 start directory. This is a path computation: the filesystem is not accessed to confirm the
 existence or nature of `path` or `startpath`.
+
+On Windows, case sensitivity is applied to every part of the path but drive letters. If
+`path` and `startpath` refer to different drives, an absolute path of `path` is returned.
```
Comment (musm) [inline base/path.jl:500]:
```suggestion
On Windows, case sensitivity is applied to every part of the path except drive letters. If
`path` and `startpath` refer to different drives, the absolute path of `path` is returned.
```
