### PR TITLE
Inference for splatting numbers (and more)

### LINKED ISSUE #22291: Inference failure for splatting numbers
This fails on at least 0.5.2, 0.6.0-rc2, and master: 

```julia
julia> wrap(ind) = (ind...)
wrap (generic function with 1 method)

julia> wrap(1)
(1,)

julia> using Base.Test

julia> @inferred(wrap(1))
ERROR: return type Tuple{Int64} does not match inferred return type Tuple{Vararg{Int64,N} where N}
Stacktrace:
 [1] error(::String) at ./error.jl:21
```

Fix coming momentarily.

### PR DESCRIPTION
**Pull request by martinholters**
Fixes #22291, closes #22292 (from where I've taken the tests).

But even more:
```julia
julia> using LinearAlgebra; foo(x) = (x...,); @code_warntype foo(qr(rand(3,3))) # master
Body::Tuple{Vararg{Union{Array{Float64,2}, LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}},N} where N}
1 1 ─ %1 = Core._apply(Core.tuple, %%x)::Tuple{Vararg{Union{Array{Float64,2}, LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}},N} where N}
  └──      return %1  

julia> using LinearAlgebra; foo(x) = (x...,); @code_warntype foo(qr(rand(3,3))) # this PR
Body::Tuple{LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}},Array{Float64,2}}
1 1 ─ %1 = Core._apply(Core.tuple, %%x)::Tuple{LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}},Array{Float64,2}}                   │
  └──      return %1 
```

### CODE REVIEW

**Comment by martinholters** [comment]
Same error across the board:
```
PHI node has multiple entries for the same basic block with different incoming values!
  %value_phi7 = phi i64 [ %587, %L111 ], [ %588, %L111 ], [ %value_phi4, %L47.L112_crit_edge ]
label %L111
  %588 = load i64, i64* %29, align 8, !dbg !512983, !tbaa !8715
  %587 = load i64, i64* %29, align 8, !dbg !512983, !tbaa !8715
LLVM ERROR: Broken function found, compilation aborted!
```
This is interesting, because a) it somehow managed to build locally and b) even if inference gives a wrong result, bad things may happen, but invalid LLVM IR should not be among them AFAICT.

**Comment by martinholters** [comment]
Can anyone give me a clue how I can figure out what method is being compiled when that error is thrown?

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -372,37 +372,54 @@ function precise_container_type(@nospecialize(arg), @nospecialize(typ), vtypes::
...
+        return ret
+    end
+    while valtype !== Any
+        nounion = typesubtract(stateordonet, Nothing)
         if !isa(nounion, DataType) || !(nounion <: Tuple) || isvatuple(nounion) || length(nounion.parameters) != 2
-            return Vararg{Any}
+            valtype = Any
+            break
         end
         if nounion.parameters[1] <: valtype && nounion.parameters[2] <: statetype
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl]: Copy this conditional above? (or at least the `nounion.parameters[2] <: statetype` part of it). If the new `statetype` is narrower, this must have been an infinite iterator (or throws an error).

File: base/number.jl [hunk 2]
```diff
@@ -233,7 +233,8 @@ julia> widemul(Float32(3.), 4.)
 """
 widemul(x::Number, y::Number) = widen(x)*widen(y)
 
-iterate(x::Number, done = false) = done ? nothing : (x, true)
+iterate(x::Number) = (x, true)
```
Comment (vtjnash) [inline base/number.jl]: Should never matter (after inference, inlining, or SROA), but constructing `(x, nothing)` would require 1 byte less space. Maybe use that instead?

File: base/compiler/abstractinterpretation.jl [hunk 3]
```diff
@@ -372,37 +372,54 @@ function precise_container_type(@nospecialize(arg), @nospecialize(typ), vtypes::
...
         return Any[Vararg{eltype(tti0)}]
     else
-        return Any[abstract_iteration(typ, vtypes, sv)]
+        return abstract_iteration(typ, vtypes, sv)
     end
 end
 
 # simulate iteration protocol on container type up to fixpoint
 function abstract_iteration(@nospecialize(itertype), vtypes::VarTable, sv::InferenceState)
     tm = _topmod(sv)
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl]: As implemented right now, this actually always uses `Base`, not `_topmod(sv)` to find `iterate`. We should probably redefine this as `if isdefined(Main, :Base) || !isdefined(Main.Base, :iterate) || !isconst(Main.Base, :iterate)` to be pedantic and precise about correctness here

File: base/number.jl (hunk 2 above)
Comment (martinholters) [reply base/number.jl]: Yes. I've actually changed that locally to see whether it makes a difference with the failure in `make julia-debug` (which it doesn't), and realized that it might be better anyway.

File: base/compiler/abstractinterpretation.jl (hunk 1 above)
Comment (martinholters) [reply base/compiler/abstractinterpretation.jl]: True. However, for an infinite iterator, we get a slightly wider type then, e.g. `Tuple{Char,Vararg{Char,N} where N}` instead of `Body::Tuple{Char,Char,Char,Char,Char,Char,Char,Char,Char,Char,Char,Char,Char,Vararg{Char,N} where N}` for splatting `Iterators.repeated('a')`. Probably doesn't matter. Or is your suggestion to `return Any[Bottom}` (instead of `break`ing out of the loop) then? While theoretically correct (or did I get something wrong?), that looks rather aggressive.

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (martinholters) [reply base/compiler/abstractinterpretation.jl]: Ok, will adjust then.

**Comment by martinholters** [comment]
Ok, I've incorporated the comments locally (including returning Bottom for infinite iterators), but I'm struggling with the invalid LLVM IR when doing `make julia-debug`. I've narrowed it down to happen during `jl_dump_native`, and `dump()`ing the module, I find
```
; Function Attrs: sspstrong
define internal nonnull %jl_value_t addrspace(10)* @julia__unsafe_getindex_19848(%jl_value_t addrspace(10)* nonnull dereferenceable(32), i64
, %jl_value_t addrspace(10)* nonnull dereferenceable(40)) #11 !dbg !532598 {
top:
  %A = alloca %jl_value_t addrspace(10)*
  %I = alloca %jl_value_t addrspace(10)*
  %3 = alloca i64
  %4 = alloca i8
; ...
L111:                                             ; preds = %L110
  %587 = load i64, i64* %29, align 8, !dbg !532774, !tbaa !8717
  %588 = load i64, i64* %29, align 8, !dbg !532774, !tbaa !8717
  br i1 true, label %L112, label %L112, !dbg !532774

L112:                                             ; preds = %L111, %L111, %L47.L112_crit_edge
  %value_phi7 = phi i64 [ %587, %L111 ], [ %588, %L111 ], [ %value_phi4, %L47.L112_crit_edge ]
; ...
}
; ...
```
with this debug info (excerpt):
```
!4 = !{}
!8686 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !8687, size: 64, align: 64)
!8698 = !DIBasicType(name: "Int64", size: 64, encoding: DW_ATE_unsigned)
!8967 = !DIDerivedType(tag: DW_TAG_typedef, name: "Array", baseType: !8686)
!12765 = !{!8698}
!25612 = !DICompositeType(tag: DW_TAG_structure_type, name: "Tuple", size: 64, align: 64, elements: !12765,
                          runtimeLang: DW_LANG_Julia, identifier: "128")
!44905 = !{!8686, !8698, !25612}
!47125 = !{!8698, !8686}
!72478 = !DICompositeType(tag: DW_TAG_structure_type, name: "BitArray", size: 192, align: 64, elements: !44905,
                          runtimeLang: DW_LANG_Julia, identifier: "7968")
!117780 = !DICompositeType(tag: DW_TAG_structure_type, name: "#_unsafe_getindex", align: 8, elements: !4,
                           runtimeLang: DW_LANG_Julia, identifier: "7962")
!411431 = !DICompositeType(tag: DW_TAG_structure_type, name: "BitArray", size: 256, align: 64, elements: !411432,
                           runtimeLang: DW_LANG_Julia, identifier: "7969")
!411432 = !{!8686, !8698, !23573}
!532598 = distinct !DISubprogram(name: "_unsafe_getindex", linkageName: "julia__unsafe_getindex_19848",
                                 scope: null, file: !1846, line: 594, type: !532599, isLocal: false,
                                 isDefinition: true, scopeLine: 594, isOptimized: true, unit: !7664,
                                 variables: !532601)
!532599 = !DISubroutineType(types: !532600)
!532600 = !{!72478, !411431, !8698, !8967}
!532601 = !{!532602, !532603, !532604}
!532602 = !DILocalVariable(name: "#self#", arg: 1, scope: !532598, file: !1846, line: 594, type: !117780)
!532603 = !DILocalVariable(name: "A", arg: 3, scope: !532598, file: !1846, line: 594, type: !411431)
!532604 = !DILocalVariable(name: "I...", arg: 4, scope: !532598, file: !1846, line: 594, type: !532605)
!532605 = !DICompositeType(tag: DW_TAG_structure_type, name: "Tuple", size: 128, align: 64, elements: !47125,
                           runtimeLang: DW_LANG_Julia, identifier: "36316")
```
How do I figure out for which types this was specialized exactly?

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (martinholters) [reply base/compiler/abstractinterpretation.jl]: Um, are you sure? If I look at e.g. `Core.Compiler.append_any(1)`, it seems to be calling `Core.Compiler.iterate`. And that's what we want to reflect, no?

**Comment by martinholters** [comment]
Ok, with #27609 in, this now seems to pass CI (Circle 64bit was killed (OOM?), Travis on OSX was hit by #26725). I've also addressed Jameson's remarks, so unless @nanosoldier `runbenchmarks(ALL, vs=":master")` disagrees, this should be good to go.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27434#issuecomment-398004486) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/fb5778c6ad6c16a36d7ae16285b6ea452200fa18/66ca2fd_vs_404e0fe/report.md). cc @ararslan

**Comment by martinholters** [comment]
As I let this go a bit stale, @nanosoldier `runbenchmarks(ALL, vs=":master")` once more, and if everything looks ok, I'll merge.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27434#issuecomment-400201660) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4abc2d4b96306c8d55d2b2709f23008a13ecae05/55f77e0_vs_4e3902d/report.md). cc @ararslan

**Comment by martinholters** [comment]
The logical next step would be eliding the call to `_apply` in more cases, i.e. when all involved iterables are inferred to result in a fixed length (up to some limit, probably). From what I understand, that would mean reworking the condition at https://github.com/JuliaLang/julia/blob/2e168b5b8ea8127df096e2769e39bf6fb7df6ceb/base/compiler/ssair/inlining.jl#L793-L794 and handling the respective case with unrolled `iterate` calls in https://github.com/JuliaLang/julia/blob/2e168b5b8ea8127df096e2769e39bf6fb7df6ceb/base/compiler/ssair/inlining.jl#L556

But I'm relatively clueless how to thread the information gathered during inference through to the inlining pass. If @Keno or @vtjnash can give me a hint, I might try to give it a shot.

File: base/compiler/abstractinterpretation.jl (hunk 3 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl]: I don’t think there’s any callers of `Core.Compiler.append_any`. The implementation of _apply right now always uses Base
