### PR TITLE
fix #32775 and #34023, issues showing `kw` and `parameters` exprs

### LINKED ISSUE #32775: improve show to handle `;` in a tuple
```
julia> ( :((a,; b)) ) # :/ would be nice for this to round-trip through `show`
:(($(Expr(:parameters, :b)), a))

julia> :( g(a,; b) ) # should print like this, using the same code as handles `:call`:
:(g(a; b))
```

### LINKED ISSUE #34023: Printing of kw-args with bang needs a space
Keyword arguments are usually written without space: `fn(;a=1) = a^2`.  However if the kwarg ends in a bang this does not work:
```julia

julia> f(;fn!=x->x[1]=1) = 1
ERROR: syntax: invalid keyword argument syntax "(fn != x -> begin
    # REPL[24], line 1
    x[1] = 1
end)"
Stacktrace:
 [1] top-level scope at REPL[24]:1
```
and a space is needed.  Could no-space be supported?  

This would then also be consistent with the current printing of the Expr:
```julia
julia> Expr(:kw, :fn!, :a)
:(fn!=a)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
This attempts to track where `=` expressions are parsed with head `kw` and show them correctly, using fallback `Expr(...)` printing when necessary. Also handles `;` in tuples, since that is closely related.

fix #32775
fix #34023

### CODE REVIEW

File: stdlib/Test/test/runtests.jl [hunk 1]
```diff
@@ -183,18 +183,18 @@ let fails = @testset NoThrowTestSet begin
...
-        @test occursin("Expression: isapprox(1 - 2, 2 - 1; atol=1 - 1)", str)
-        @test occursin("Evaluated: isapprox(-1, 1; atol=0)", str)
+        @test occursin("Expression: isapprox(1 - 2, 2 - 1; atol = 1 - 1)", str)
+        @test occursin("Evaluated: isapprox(-1, 1; atol = 0)", str)
     end
 
     let str = sprint(show, fails[13])
         @test occursin("Expression: isapprox(1, 2; k...)", str)
-        @test occursin("Evaluated: isapprox(1, 2; atol=0, nans=true)", str)
+        @test occursin("Evaluated: isapprox(1, 2; atol = 0, nans = true)", str)
```
Comment (ararslan) [inline stdlib/Test/test/runtests.jl]: :(

Comment (JeffBezanson) [reply stdlib/Test/test/runtests.jl]: I find the spaces more readable, and I know at least some others agree. It also simplifies the code by not needing to special-case identifiers ending in `!`.

Comment (StefanKarpinski) [reply stdlib/Test/test/runtests.jl]: Matches https://github.com/domluna/JuliaFormatter.jl as well as BlueStyle, I believe.

Comment (ararslan) [reply stdlib/Test/test/runtests.jl]: No, both Blue and YASGuide say no spaces around `=` for keyword arguments. AFAIK JuliaFormatter is the only one that does it.

Comment (JeffBezanson) [reply stdlib/Test/test/runtests.jl]: I guess it's one thing if you prefer no spaces around `=`, but I don't see why spaces would be considered good for assignments but bad for keyword arguments. Interestingly, https://www.python.org/dev/peps/pep-0008/ agrees with you. It recommends this style:
```
function f(; x::Int = 0, y=1)
```
i.e. using spaces only when there is a type declaration. That seems pretty fussy to me though. Why not just always allow spaces?

Comment (ararslan) [reply stdlib/Test/test/runtests.jl]: Though not stated explicitly, it's also what JuliaStats uses, modeled after what's used in much of Base.

Comment (ararslan) [reply stdlib/Test/test/runtests.jl]: > I don't see why spaces would be considered good for assignments but bad for keyword arguments.

It provides visual distinction between the two, since they aren't the same.

Comment (JeffBezanson) [reply stdlib/Test/test/runtests.jl]: What about `=>` for computed keyword arguments?

Comment (ararslan) [reply stdlib/Test/test/runtests.jl]: Most guides (and code) I've seen use space around `=>` regardless of where it occurs, since it always means the same thing.

**Review by vtjnash — APPROVED** [review]
Is it worthwhile to print an extra block expression for `Expr(:call, :call, :(a = 2))`, which has the same syntax meaning though a different parse structure:
```julia
call( (a = 2;) )
```

**Comment by JeffBezanson** [comment]
That's clever! I think it's better to print the exact structure whenever possible though, even if that means using the ugly `$(Expr(...))`. Should come up rarely enough.

File: stdlib/Test/test/runtests.jl (hunk 1 above)
Comment (JeffBezanson) [reply stdlib/Test/test/runtests.jl]: You know, I'm not sure this is the right place to discuss this. The expression printer is not a style guide or code formatting tool, so I'm not sure it matters.
