### PR TITLE
gf lookup: avoid creating unintended specializations and cache misses

### LINKED ISSUE #36669: `@allocated` test in InteractiveUtils failing on CI
See https://build.julialang.org/#/builders/34/builds/1613 and https://build.julialang.org/#/builders/34/builds/1623. This seems new (within the last day or so).

### PR DESCRIPTION
**Pull request by vtjnash**
The typemap code was forgetting to handle the case where the user needed
to look for something complicated (like AbstractVec{Float64}) in the
method table cache (such as for ==).

edit: fixes #36669

### CODE REVIEW

File: base/compiler/typelattice.jl [hunk 1]
```diff
@@ -84,8 +84,10 @@ struct NotFound end
 
 const NOT_FOUND = NotFound()
 
-const CompilerTypes = Union{Type, MaybeUndef, Const, Conditional, NotFound, PartialStruct}
-==(x::CompilerTypes, y::CompilerTypes) = x === y
+const CompilerTypes = Union{MaybeUndef, Const, Conditional, NotFound, PartialStruct}
+==(x::CompilerTypes, y::CompilerTypes) = false
```
Comment (JeffBezanson) [inline base/compiler/typelattice.jl:88]: I guess we never use this method, but this definition still seems a little hazardous?

**Comment by Keno** [comment]
Did I remember correctly that this may help #36669?

**Comment by vtjnash** [comment]
Yes, just waiting for this to finish CI (with Jeff's correction)

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Hmm, does the buildbot not have `pbpaste`?

**Comment by Keno** [comment]
> Hmm, does the buildbot not have `pbpaste`?

Long story - don't ask. Should be fixed in the near future.
