### PR TITLE
Run ambiguity test inside a clean process

### LINKED ISSUE #28804: CI test failure due to ambiguous method in ccall test
https://travis-ci.org/JuliaLang/julia/jobs/418783280#L2142-L2145
```
Some tests did not pass: 597 passed, 1 failed, 0 errored, 0 broken.LinearAlgebra/matmul: Test Failed at /tmp/julia/share/julia/stdlib/v1.1/LinearAlgebra/test/matmul.jl:449
  Expression: detect_ambiguities(LinearAlgebra, Base; imported=true, recursive=true) == []
   Evaluated: Tuple{Method,Method}[(unsafe_convert(::Type{Main.Test97Main_ccall.SpillPint}, vr) in Main.Test97Main_ccall at /tmp/julia/share/julia/test/ccall.jl:1268, unsafe_convert(::Type{T}, x::T) where T in Base at essentials.jl:346)] == Any[]
```
Looks like this may happen if the ccall test and the LinearAlgebra tests are run on the same worker? May need a `unsafe_convert(::Type{SpillPint}, x::SpillPint) = x` method.

### PR DESCRIPTION
**Pull request by tkf**
fixes #28804

### CODE REVIEW

File: stdlib/LinearAlgebra/test/ambiguous_exec.jl [hunk 1]
```diff
@@ -0,0 +1,4 @@
+# This file is a part of Julia. License is MIT: https://julialang.org/license
+
+using Test, LinearAlgebra
+@test detect_ambiguities(LinearAlgebra; imported=true, recursive=true) == []
```
Comment (tkf) [inline stdlib/LinearAlgebra/test/ambiguous_exec.jl]: I was previously doing `detect_ambiguities(LinearAlgebra, Base; ...)` by accident but I suppose I didn't need `Base` there?

**Review by Keno — APPROVED** [review]

**Comment by ararslan** [comment]
Looks like 32-bit Windows is hitting a GC bug:
```
      From worker 6:	
      From worker 6:	Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
      From worker 6:	Exception: EXCEPTION_ACCESS_VIOLATION at 0x682b1f5a -- gc_try_setmark at /cygdrive/c/projects/julia/src\gc.c:1428 [inlined]
      From worker 6:	gc_mark_scan_obj8 at /cygdrive/c/projects/julia/src\gc.c:1554 [inlined]
      From worker 6:	gc_mark_loop at /cygdrive/c/projects/julia/src\gc.c:1818
      From worker 6:	in expression starting at C:\projects\julia\julia-e47bb0e211\share\julia\test\sorting.jl:35
      From worker 6:	gc_try_setmark at /cygdrive/c/projects/julia/src\gc.c:1425 [inlined]
      From worker 6:	gc_mark_scan_obj8 at /cygdrive/c/projects/julia/src\gc.c:1554 [inlined]
      From worker 6:	gc_mark_loop at /cygdrive/c/projects/julia/src\gc.c:1818
```

**Comment by Keno** [comment]
Let's watch for failures like that after merging. I'm hoping one of my recent gc root PRs may have fixed it, but wasn't picked up in this CI run yet.
