### PR TITLE
fix typo in Float32 random number generation

### LINKED ISSUE #57336: `rand(Float32, n)` generates two values of the same number over and over when n is < 16
```julia
julia> rand(Float32, 8)
8-element Vector{Float32}:
 0.20123601
 0.20123601
 0.20944309
 0.20944309
 0.22612727
 0.22612727
 0.67038965
 0.67038965
```

### PR DESCRIPTION
**Pull request by KristofferC**
introduced in https://github.com/JuliaLang/julia/pull/56144

### CODE REVIEW

File: stdlib/Random/test/runtests.jl [hunk 1]
```diff
@@ -1250,6 +1250,12 @@ end
     @test length(xs) == 3
 end
 
+@testset "float32 bug" begin
+    a = rand(Float32, 4)
+    @test a[1] != a[2]
+    @test a[3] != a[4]
```
Comment (martinholters) [inline stdlib/Random/test/runtests.jl:1256]:
```julia
    @test length(unique(rand(Float32, 14))) > 10
```
would be less specific and should have a reasonably low probability of accidental failure as well. (Could be adjusted by modifying the 10, of course.)

Comment (giordano) [reply stdlib/Random/test/runtests.jl]: Yeah, that seems to be less likely to hit a random failure:
```
julia> all(length(unique(rand(Float32, 14))) > 10 for _ in 1:100_000_000)
true

julia> all(allunique(rand(Float32, 4)) for _ in 1:100_000_000)
false
```

File: stdlib/Random/test/runtests.jl [hunk 2]
```diff
@@ -1250,6 +1250,10 @@ end
     @test length(xs) == 3
 end
 
+@testset "Float32 RNG typo" begin
+    @test length(unique(rand(Float32, 14))) > 10
+end
```
Comment (giordano) [inline stdlib/Random/test/runtests.jl:1255]: Extend to other types as well?  This won't catch similar issues otherwise.

File: stdlib/Random/test/runtests.jl [hunk 3]
```diff
@@ -1250,6 +1250,12 @@ end
     @test length(xs) == 3
 end
 
+@testset "Float32 RNG typo" begin
+    for T in (Float16, Float32, Float64)
+        @test length(unique(rand(T, 14))) > 10
```
Comment (giordano) [inline stdlib/Random/test/runtests.jl:1255]: As mentioned at https://github.com/JuliaLang/julia/pull/57338#discussion_r1948993368, this is testing only one codepath for generating random numbers, it'd be better to test both
```suggestion
        # Make sure generated numbers are sufficiently diverse
        # for both SIMD and non-SIMD RNG code paths.
        @test length(unique!(rand(T, 14))) > 10
        @test length(unique!(rand(T, 34))) > 20
```

File: stdlib/Random/test/runtests.jl [hunk 4]
```diff
@@ -1250,6 +1250,12 @@ end
     @test length(xs) == 3
 end
 
+@testset "Float32 RNG typo" begin
```
[the remark this answers is not in the document]
Comment (KristofferC) [reply stdlib/Random/test/runtests.jl:1253]: Well, that oversells it a bit maybe heh.

File: stdlib/Random/test/runtests.jl (hunk 2 above)
Comment (KristofferC) [reply stdlib/Random/test/runtests.jl]: The test here is pretty much just to check that the concrete issue is fixed. I don't think there is much value in extending the tests more than that.

Comment (giordano) [reply stdlib/Random/test/runtests.jl]: Well, it'd have caught https://github.com/JuliaLang/julia/pull/55997#issuecomment-2395036394

Comment (giordano) [reply stdlib/Random/test/runtests.jl]: > Why wasn't the test added there?

I was thinking of count iszero tests, but those are brittle at best, especially for Float16 (which generates 2048 unique numbers, so the probability of picking exactly 0 is non-negligible) and especially for small vectors (which was the broken case),  I could hit test failures fairly easily.

**Review by fingolfin — APPROVED** [review]
