### PR TITLE
Fix `pkgdir` for extensions

### LINKED ISSUE #55719: `pkgdir` returns wrong dir for extension if extension is in its own folder
https://github.com/JuliaLang/julia/blob/0c0fdf0489106aa64d5d9eabb5fc358f17310378/base/loading.jl#L528

Assumes the result of `pathof` is a `.../src/Foo.jl` path. Extensions can be located at `.../ext/FooExt.jl` or `.../ext/FooExt/FooExt.jl`

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/55719

### CODE REVIEW

File: base/loading.jl [hunk 1]
```diff
@@ -508,6 +508,8 @@ package root.
 To get the root directory of the package that implements the current module
 the form `pkgdir(@__MODULE__)` can be used.
 
+If an extension module is given, the root of the parent package is returned.
```
Comment (KristofferC) [inline base/loading.jl:511]: Why shouldn't it give the path to the extension?

Comment (Seelengrab) [reply base/loading.jl:511]: Extensions aren't fully fledged packages themselves, right? The resulting path would not point to a package.

Comment (KristofferC) [reply base/loading.jl:511]: Well, they load like a normal package at least. But I see that `pkgdir` gives you the path to where the whole package is stored so it would be hard to have an analogy for that for an extension so maybe this is the best thing to do.

File: base/loading.jl [hunk 2]
```diff
@@ -525,7 +527,23 @@ function pkgdir(m::Module, paths::String...)
...
     path = pathof(rootmodule)
     path === nothing && return nothing
-    return joinpath(dirname(dirname(path)), paths...)
+    original = path
+    path = dirname(path)
+    if endswith(path, "src")
+        path = dirname(path)
+    elseif contains(path, "ext")
+        # extensions can reside at `../ext/FooExt.jl` or `../ext/FooExt/FooExt.jl`
+        if endswith(path, "ext")
```
Comment (topolarity) [inline base/loading.jl:536]: Would this be correct if `path` is something like `../test/QuickText`?
(since `endswith("QuickText", "ext") === true`)

Comment (IanButterworth) [reply base/loading.jl]: Indeed. Thanks

File: base/loading.jl [hunk 3]
```diff
@@ -525,7 +527,23 @@ function pkgdir(m::Module, paths::String...)
...
+        if splitpath(path)[end] == "ext"
+            path = dirname(path)
+        else
+            path = dirname(path)
+            splitpath(path)[end] == "ext" || error("Unexpected path structure for extension module: $original")
+            path = dirname(path)
+        end
+    else
+        error("Unexpected path structure for module source: $original")
+    end
```
Comment (fingolfin) [inline base/loading.jl:545]: Could use `splitdir` to simplify the logic a bit
```suggestion
    path, base = splitdir(path)
    if base == "src"
        # default
    elseif base == "ext"  # extension in `../ext/FooExt.jl`
        # source code
    elseif basename(path) == "ext"  # extension in `../ext/FooExt/FooExt.jl`
        path = dirname(path)
    else
        error("Unexpected path structure for module source: $original")
    end
```
Or even just this (less resilient but simpler)
```suggestion
    path, base = splitdir(path)
    if basename(path) == "ext"
        # extension in `../ext/FooExt/FooExt.jl` so we need to go up another level
        path = dirname(path)
    end
```

Comment (IanButterworth) [reply base/loading.jl]: Thanks. Pushed with minor tweaks.
