### PR TITLE
`copyto!` fix for `BitArray`/`AbstractArray`

### LINKED ISSUE #25968: copyto! dispatches incorrectly for BitVector
```
julia> a = BitVector([true, false, true])
3-element BitArray{1}:
  true
 false
  true

julia> unsafe_copyto!(a, 2, a, 1, 2)
3-element BitArray{1}:
  true
  true
 false

julia> a = BitVector([true, false, true])
3-element BitArray{1}:
  true
 false
  true

julia> copyto!(a, 2, a, 1, 2)
3-element BitArray{1}:
 true
 true
 true

julia> @which unsafe_copyto!(a, 2, a, 1, 2)
unsafe_copyto!(dest::BitArray, doffs::Integer, src::Union{BitArray, Array}, soffs::Integer, n::Integer) in Base at bitarray.jl:419

julia> @which copyto!(a, 2, a, 1, 2)
copyto!(dest::AbstractArray, dstart::Integer, src::AbstractArray, sstart::Integer, n::Integer) in Base at abstractarray.jl:724

julia> versioninfo()
Julia Version 0.7.0-DEV.3736
Commit 4b1cf22f98 (2018-02-06 16:41 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
Environment:
```

This is also broken on v0.6.2.

### PR DESCRIPTION
**Pull request by N5N3**
This PR fix #25968 via dispatching `copyto!` to `Base.unsafe_copyto!`
Also the missing aliasing check is added to the general fallback for `AbstractArray`.
Test added.

### CODE REVIEW

File: base/abstractarray.jl [hunk 1]
```diff
@@ -894,10 +894,9 @@ function copy!(dst::AbstractVector, src::AbstractVector)
     if length(dst) != length(src)
         resize!(dst, length(src))
     end
-    for i in eachindex(dst, src)
-        @inbounds dst[i] = src[i]
-    end
-    dst
+    firstindex(dst) == firstindex(src) || throw(ArgumentError(
```
Comment (fredrikekre) [inline base/abstractarray.jl:897]: Should be moved to the top so `dst` isn't resized.
