### PR TITLE
Fix sret alloca alignment to match callee's preferred type alignment

### LINKED ISSUE #3034: Julia 1.12: Misaligned address error
MWE, reduced from DiffEqGPU.jl:

```julia
using CUDA
struct Dual
    value::Float32
    partials::NTuple{6,Float32}
end
mul_partials(val, dp) = Dual(val, ntuple(i -> dp[i]*val + dp[i]*val, 6))
Base.:*(x::Dual, y::Dual) = mul_partials(x.value*y.value, x.partials)
Base.:+(x::Dual, y::Dual) = Dual(x.value+y.value, x.partials)
f(u) = (u[1]*u[1]+u[1]*u[1], u[1]*u[1], u[1]*u[1])
kernel(us) = (us[1] = f(us[1]); nothing)
d = Dual(1f0, (0f0,0f0,0f0,0f0,0f0,0f0))
@cuda kernel(CuArray([(d,d,d)]))
```

### PR DESCRIPTION
**Pull request by maleadt**
The caller's sret alloca used julia_alignment (union_align) which can be smaller than the LLVM preferred type alignment that the callee uses for its loads/stores. For example, a struct of floats gets julia_alignment=4 but the callee uses DL.getPrefTypeAlign()=8, generating 8-byte-aligned memcpy operations. On strict-alignment targets (NVPTX), the resulting misaligned access causes CUDA_ERROR_MISALIGNED_ADDRESS.

Fix by computing the sret type's preferred alignment from the callee's StructRet attribute and taking the max with union_align, matching the alignment the callee computes for its sret parameter.

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/3034
Regression introduced in 1.12 by #55730

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -5314,7 +5314,20 @@ static jl_cgval_t emit_call_specfun_other(jl_codectx_t &ctx, bool is_opaque_clos
         if (returninfo.all_roots) {
             result = emit_static_roots(ctx, returninfo.union_bytes / sizeof(void *));
         } else {
-            result = emit_static_alloca(ctx, returninfo.union_bytes, Align(returninfo.union_align));
+            Align alloca_align(returninfo.union_align);
+            if (returninfo.cc == jl_returninfo_t::SRet) {
+                // The callee determines the sret parameter alignment from the LLVM
+                // preferred type alignment (which may exceed julia_alignment), and
```
Comment (vtjnash) [inline src/codegen.cpp]: Is this an LLVM bug? That's not a valid change to the IR we emitted in our callee

Comment (vtjnash) [reply src/codegen.cpp]: Ah, I see in the LangRef, the alignment attribute is not optional for sret

Comment (maleadt) [reply src/codegen.cpp]: So the change is OK?

**Comment by gbaraldi** [comment]
LGTM

File: src/codegen.cpp (hunk 1 above)
Comment (vtjnash) [reply src/codegen.cpp]: No, you should be setting the alignment attribute when we set the sret

File: src/ccall.cpp [hunk 2]
```diff
@@ -1311,6 +1311,10 @@ std::string generate_func_sig(const char *fname)
             if (!ctx->TargetTriple.isOSWindows()) {
                 // llvm used to use the old mingw ABI, skipping this marking works around that difference
                 retattrs.addStructRetAttr(lrt);
+                Align al = ctx->DL.getPrefTypeAlign(lrt);
+                if (al > Align(MAX_ALIGN))
+                    al = Align(MAX_ALIGN);
+                retattrs.addAlignmentAttr(al);
```
Comment (topolarity) [inline src/ccall.cpp]: Is it not sufficient to set this attribute, without adjusting for the type's preferred alignment at all?

Comment (maleadt) [reply src/ccall.cpp]: No, and I verified the problem persists without the alloca alignment change.

Comment (topolarity) [reply src/ccall.cpp]: Interesting. That does suggest an LLVM bug (or a missing detail in the LangRef?) to me

Comment (maleadt) [reply src/ccall.cpp]: Ah wait, I hadn't removed all alignment overrides. Let me look closer.

Comment (maleadt) [reply src/ccall.cpp]: Looks like this works, but Github is all unicorns so I'll only be able to push this later today or tomorrow.

Comment (topolarity) [inline src/ccall.cpp]: seems that this should match https://github.com/JuliaLang/julia/blob/acd9708a2a443037d078a1630f7988452dc29769/src/ccall.cpp#L2151

**Review by topolarity — APPROVED** [review]
Thanks @maleadt !

**Review by vtjnash — APPROVED** [review]
