### PR TITLE
[JuliaLowering] Refactor scope resolution pass

### LINKED ISSUE #101: REPL hook-related issues
I'm starting to use JL in the REPL via @mlechu's experimental `JULIA_USE_FLISP_LOWERING=0` hook.

This is a catch-all issue to document any issues I encounter:
 1. defining functions prints an anonymized name and seems to be the `typeof(f)` instead of `f`:
    ```julia
    julia> foo(x,y) = (x = y + y; x)
    #foo##0 (generic function with 1 method)

    julia> var"#foo##0"(1,2)
    ERROR: MethodError: no method matching var"#foo##0"(::Int64, ::Int64)

    julia> var"#foo##0".instance(1,2)
    4
    ```
 2. `const x = ...` does not work:
     ```julia
     julia> const x = 3
    ┌ Info: JuliaLowering threw given input:
    │   code =
    │    quote
    │        $(Expr(:softscope, true))
    │        const x = 3
    │    end
    │   st0 =
    │    SyntaxTree with attributes kind,var_id,toplevel_pure,scope_type,name_val,syntax_flags,meta,scope_layer,value,is_toplevel_thunk,source
    │    [scope_block]                                                │ scope_type
    │      [const]                                                    │
    │        [=]                                                      │
    │          x                                  :: Identifier       │
    │          3                                  :: Integer          │
    │
    │   file = "REPL[7]"
    │   line = 1
    └   mod = Main
    ERROR: LoweringError:
    #= REPL[7]:1 =# - unsupported `const` declaration on local variable
    ```
 3. non-`global` top-level assignments do not work:
    ```julia
    julia> y = 13
    13
    julia> y
    ERROR: UndefVarError: `y` not defined in `Main`
    Suggestion: check for spelling errors or missing imports.
    ```

### PR DESCRIPTION
**Pull request by mlechu**
### Soft scope
We currently treat flisp's `'(block (softscope true))` as a scope that "is
soft", but this isn't correct. It should behave more like a toggle, where if the
scope surrounding `(softscope true)` is the top-level thunk, neutral scopes not
protected by a hard scope become permeable to already-defined globals.  I've
added `K"softscope"` for this.

Fixes https://github.com/JuliaLang/JuliaLowering.jl/issues/101.
`JuliaLowering.activate!()` should be much more usable in the REPL now, as
globals won't be accidentally eaten by the "soft scope."

### Shadowing behaviour
Found while cleaning up the lhs-resolution step with the change above.  This PR
allows static parameters to be shadowed by globals and locals as long as they're
explicit (and not in the same scope).  flisp allows this with globals, and the
explicit locals that desugar to `local-def` forms (which JuliaLowering doesn't
have).

This change is more permissive than flisp in the local case, since after looking
into why shadowing was disallowed I realized it was just was just to prevent
assignment to the static parameter (#32623).  The flisp fix leads to some funny
behaviour:

```
julia> function f(x::T) where T
     let
         global T # remove this T and the other two will fight
         let; local T; end
     end
     end
f (generic function with 1 method)
```

### Bindings/LambdaBindings
In figuring out how to use the variable bookkeeping system, I ran into inaccuracies.

`LambdaBindings` is currently a per-lambda map from unique variable to four
flags: `captured`, `read`, `assigned`, and `called`.  I think (but correct me if
I'm wrong @c42f) this was a misinterpretation of the holy text: in flisp
lowering, a local variable captured by some other lambda does show up in both
lambdas' variable lists, but is the same underlying object, and flag mutations
on one variable are seen by all lambdas.

I tried to think of other reasons for tracking vinfo per lambda within lowering,
but if we're doing something about the capture-boxing issue, we need something
more complex anyway.

This PR moves all vinfo to `BindingInfo` and deletes the incorrect bookkeeping
in `LambdaBindings`. We still need to have a per-lambda flag for capturedness
(different from the variable-level `capt` vinfo flag). With the added flags,
I've just made BindingInfo mutable since our previous workflow (BindingId is an
index into a vector; mutate the vector) doesn't give us the benefits of
immutability anyway.

## Enhancements
- Scopes are retained until the end of the pass, so consumers like JETLS can
  answer questions like "what names are available at my cursor?"  Recreating
  this previously-discarded information was a bit hacky! [[1]](https://github.com/aviatesk/JETLS.jl/blob/6b43afe9e6f5392fc63714a8127a7653e94d9dba/src/utils/ast.jl#L115-L200) [[2]](https://github.com/iuliadmtru/ScopeVars/blob/f7da77eb07d644d3bcd57a3677791b6158d2d8b1/src/find_scope_vars.jl)
- Hopefully enough tests and explanatory comments to make up for the large diff

## TODO
- Our use of `K"local"` in desugaring is dubious in some places
- I've added `expr_compat_mode` to the scope analysis context, but we still need
  to implement flisp hygiene exemptions for globals (see note in test/scopes.jl).
- Reviewing the IR changes, the `#self#` argument still has extra flags set in
  some cases.  This is an existing desugaring bug with a comment that took me
  too long to find: we shouldnn't be using the same `#self#` binding for
  multiple methods defined by one function body

### CODE REVIEW

File: JuliaLowering/src/bindings.jl [hunk 1]
```diff
@@ -1,74 +1,69 @@
...
+    binfo.is_internal        && print(io, ", is_internal")
+    binfo.is_ambiguous_local && print(io, ", is_ambiguous_local")
+    binfo.is_nospecialize    && print(io, ", is_nospecialize")
+    binfo.is_read            && print(io, ", is_read")
+    binfo.is_called          && print(io, ", is_called")
+    binfo.is_assigned        && print(io, ", is_assigned")
+    binfo.is_assigned_once   && print(io, ", is_assigned_once")
+    binfo.is_captured        && print(io, ", is_captured")
+    binfo.is_always_defined  && print(io, ", is_always_defined")
+    binfo.is_used_undef      && print(io, ", is_used_undef")
```
Comment (topolarity) [inline JuliaLowering/src/bindings.jl]: Doesn't this no longer round-trip when pasting into, e.g., the REPL?

Maybe worth it for compactness, but would be nice to restore.

File: JuliaLowering/test/scopes.jl [hunk 2]
```diff
@@ -58,23 +58,281 @@ begin
...
+| arg      || shadow(??) | error | error (not unique) |                    |
+| sparam   || shadow(??) | error | error (sparam/arg) | error (not unique) |
+=#
+@testset "Conflicts in the same local scope" begin
+
+    # no-op cases.  It would probably be clearer (but breaking) if these were
+    # errors like the conflict cases (two of the same decl should never do
+    # anything, and the user might be expecting two variables).
+    @testset "global,global" begin
+        s = "function (); global g; global g; 1; end"
```
Comment (topolarity) [inline JuliaLowering/test/scopes.jl:75]: JuliaLowering seems to accept this example, but flisp does not:
```julia
julia> JuliaLowering.include_string(TestMod,"""
       function (); global g; const g = 1; end
       """)
#anon###0 (generic function with 1 method)

julia> function (); global g; const g = 1; end
ERROR: syntax: `global const` declaration not allowed inside function around REPL[5]:1
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

somehow `global g` gets JL to look the other way

File: JuliaLowering/test/scopes.jl [hunk 3]
```diff
@@ -58,23 +58,281 @@ begin
...
+                       local lname = false
+                       global gname = false
+                       $e
+                   end)(#=called=#))
+
+lhs_names = (:lname, :gname, :argname, :spname)
+
+# For each distinct outer and inner scope, and each kind of variable in the
+# outer scope, set the same name to true from the inner scope
+@testset "Behaviour of `=` in local scope (shadow or assign-existing)" begin
```
Comment (topolarity) [inline JuliaLowering/test/scopes.jl:208]: I love exhaustive testing like this, even if it's a bit "shallow" w.r.t. the AST depth.

Really nice!

File: JuliaLowering/src/bindings.jl [hunk 4]
```diff
@@ -1,74 +1,69 @@
...
-    id::IdTag                 # Unique integer identifying this binding
-    name::String
-    kind::Symbol              # :local :global :argument :static_parameter
-    node_id::Int              # ID of associated K"BindingId" node in the syntax graph
-    mod::Union{Nothing,Module} # Set when `kind === :global`
+mutable struct BindingInfo
+    const id::IdTag                 # Unique integer identifying this binding
+    const name::String
+    const kind::Symbol              # :local :global :argument :static_parameter
+    const node_id::Int              # ID of associated K"BindingId" node in the syntax graph
```
Comment (topolarity) [inline JuliaLowering/src/bindings.jl]: For my own understanding, is `node_id <-> id` a 1:1 mapping?

File: JuliaLowering/src/bindings.jl [hunk 5]
```diff
@@ -106,147 +101,81 @@ function _binding_id(ex::SyntaxTree)
...
+    binding_ex(ctx, _new_binding(
+        ctx, nameref, name, :global; is_internal=true, mod=mod, kws...))
 end
 
-function binding_ex(ctx::AbstractLoweringContext, id::IdTag)
+function binding_ex(ctx::AbstractLoweringContext, b::BindingInfo)
     # Reconstruct the SyntaxTree for this binding. We keep only the node_id
     # here, because that's got a concrete type. Whereas if we stored SyntaxTree
     # that would contain the type of the graph used in the pass where the
     # bindings were created and we'd need to call reparent(), etc.
```
Comment (topolarity) [inline JuliaLowering/src/bindings.jl:156]: I'm confused by these comments.. this implementation seems very similar to `reparent()`

I know they're not yours, but can you explain where it's different?

File: JuliaLowering/src/bindings.jl [hunk 6]
```diff
@@ -106,147 +101,81 @@ function _binding_id(ex::SyntaxTree)
...
-end
-
-function update_lambda_binding!(ctx::AbstractLoweringContext, x; kws...)
-    update_lambda_binding!(current_lambda_bindings(ctx), x; kws...)
+    # For finding the parent lambda in variable analysis
+    scope_id::ScopeId
+    # A map from every referenced local binding ID to whether the local is
+    # captured (true) or native to this lambda (false).  References in inner
+    # lambdas count: `inner.locals_capt[id]` implies `haskey(locals_capt, id)`
+    locals_capt::Dict{IdTag,Bool}
```
Comment (topolarity) [inline JuliaLowering/src/bindings.jl:174]:
```suggestion
    locals::BitSet
    captured::BitSet
```

Probably a micro-optimization, but this seems slightly clearer to me

File: JuliaLowering/src/closure_conversion.jl [hunk 7]
```diff
@@ -233,10 +234,8 @@ end
 function closure_type_fields(ctx, srcref, closure_binds, is_opaque)
     capture_ids = Vector{IdTag}()
```
Comment (topolarity) [inline JuliaLowering/src/closure_conversion.jl:235]: Another micro-optimization, but `Vector{IdTag}` should probably be `BitSet`
(since these are small and contiguous)

File: JuliaLowering/src/scope_analysis.jl [hunk 8]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
-    scope_stack::Vector{ScopeInfo}
-    # Variables which were implicitly global due to being assigned to in top
-    # level code
-    implicit_toplevel_globals::Set{NameKey}
+    # Usually, globals in the top scope are ignored.  These are globals that may
+    # be assigned to without the `global` keyword in soft scopes due to being
+    # assigned to at top level, or passing the defined-and-owned-global check.
+    defined_toplevel_globals::Set{NameKey}
+    enable_soft_scopes::Bool
+    expr_compat_mode::Bool
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl:70]: This looks unused?

File: JuliaLowering/src/scope_analysis.jl [hunk 9]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
+    for id in sort!(collect(values(scope.vars)))
+        binfo = get_binding(ctx, id)
         if binfo.kind == :local
             push!(stmts, @ast ctx srcref [K"local" binding_ex(ctx, id)])
         end
     end
 end
 
-function _resolve_scopes(ctx, ex::SyntaxTree)
+function _resolve_scopes(ctx, ex::SyntaxTree, @nospecialize(scope))
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl]:
```suggestion
function _resolve_scopes(ctx, ex::SyntaxTree, @nospecialize(scope::Union{Nothing,ScopeInfo}))
```

IIUC you assume this, so best to mark it
(should also dramatically help inference, given the `@nospecialize`)

File: JuliaLowering/src/scope_analysis.jl [hunk 10]
```diff
@@ -544,18 +456,18 @@ function _resolve_scopes(ctx, ex::SyntaxTree)
...
-                vk = var_kind(ctx, NameKey(v))
-                if vk !== :local
+                b = resolve_name(ctx, v)
+                if isnothing(b) || !(b.kind in (:local, :argument))
                     throw(LoweringError(v, "`outer` annotations must match with a local variable in an outer scope but no such variable was found"))
                 end
             end
         elseif etype == "global_toplevel_only"
-            if !ctx.scope_stack[end].is_toplevel_global_scope
+            if !is_top_scope(scope)
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl:467]: Won't this throw a `MethodError` is `scope isa Nothing`?

File: JuliaLowering/src/scope_analysis.jl [hunk 11]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
-                              i > 1 || lookup_binding(ctx, id).kind != :global)
-            return id
-        end
+top_scope(ctx) = ctx.scopes[1]
+is_top_scope(scope::ScopeInfo) = scope.parent_id === 0
+enclosing_lambda(ctx, scope::ScopeInfo) = ctx.scopes[scope.lambda_id]
+parent(ctx, scope::ScopeInfo) = is_top_scope(scope) ? nothing :
+    ctx.scopes[scope.parent_id]
+
+enclosing_lambda(ctx, lb::LambdaBindings) = ctx.scopes[lb.scope_id]
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl]: This method is somewhat confusing, since it's a weird name if you come to this operation by saying "I'd like to get the `ScopeInfo` corresponding to the lambda."

```suggestion
```

I'd see whether `enclosing_lambda(ctx, scope(ctx, lb))` (or similar) is not too awkward instead

**Review by topolarity — COMMENTED** [review]
I still need to do another once-over of the core pass logic, but this should be useful (mostly very minor) feedback in the mean time.

File: JuliaLowering/src/scope_analysis.jl [hunk 12]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
 end
 
 struct ScopeResolutionContext{GraphType} <: AbstractLoweringContext
     graph::GraphType
     bindings::Bindings
     mod::Module
+    # Every lexical scope, indexed by ScopeId
+    scopes::Vector{ScopeInfo}
+    # Current stack of scopes to look for names in, innermost scope last
+    scope_stack::Vector{ScopeId}
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl:62]: Is this identical to the sequence of scopes you get if you follow the `parent(ctx, scope)` chain?

File: JuliaLowering/src/scope_analysis.jl [hunk 13]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
-            is_always_defined = args_kind == :argument
-            id = init_binding(ctx, arg, varkey, args_kind;
-                              is_nospecialize=getmeta(arg, :nospecialize, false),
-                              is_always_defined=is_always_defined)
-            var_ids[varkey] = id
-        elseif ka != K"BindingId" && ka != K"Placeholder"
-            throw(LoweringError(arg, "Unexpected lambda arg kind"))
+# If `b` is local and not yet recorded in the lambda bindings, mark it as
+# `capt`.  Also, (if `capt==true`), add it to any parent lambdas.
+function record_lambda_var!(ctx, scope::Union{ScopeInfo, LambdaBindings}, b, capt)
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl]:
```suggestion
function record_lambda_var!(ctx, scope::ScopeInfo, b; is_captured)
```

File: JuliaLowering/src/scope_analysis.jl [hunk 14]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
+    if bk === :global
+        home_scope = top_scope(ctx)
+        mod = ctx.scope_layers[ex.scope_layer].mod
+    else
+        home_scope = scope
+        mod = nothing
     end
-    id
+    b = _new_binding(ctx, ex, nk.name, bk; mod, kws...)
+    home_scope.vars[nk] = b.id
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl]:
```suggestion
    declaration_scope.vars[nk] = b.id
```

File: JuliaLowering/src/scope_analysis.jl [hunk 15]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
-    global_vars::Dict{NameKey,IdTag}
-    # Stack of name=>id mappings for each scope, innermost scope last.
-    scope_stack::Vector{ScopeInfo}
-    # Variables which were implicitly global due to being assigned to in top
-    # level code
-    implicit_toplevel_globals::Set{NameKey}
+    # Usually, globals in the top scope are ignored.  These are globals that may
+    # be assigned to without the `global` keyword in soft scopes due to being
+    # assigned to at top level, or passing the defined-and-owned-global check.
+    defined_toplevel_globals::Set{NameKey}
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl]: I actually do prefer the old `implicit` name or `implicitly_scoped_globals`? "top-level global" is a bit redundant, IIUC?

File: JuliaLowering/src/scope_analysis.jl [hunk 16]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
+            declare_in_scope!(ctx, scope, ex, :argument;
+                              is_nospecialize=getmeta(ex, :nospecialize, false))
+        else
+            real_k = new_k === :destructured_arg ? :local : new_k
+            declare_in_scope!(ctx, scope, ex, real_k)
+        end
+    elseif old_k === new_k
+        (new_k === :global || new_k === :local) && return bid
+        throw(LoweringError(ex, "function $(_var_str(new_k)) name not unique"))
+    # See note in test/scopes.jl
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl]: can you add some identifier to the note you mean?

File: JuliaLowering/src/scope_analysis.jl [hunk 17]
```diff
@@ -17,493 +17,405 @@ function NameKey(ex::SyntaxTree)
...
-                init_lambda_binding(lambda_bindings, id)
-            end
-        end
+    #---------------------------------------------------------------------------
+    # Find assignment targets, possibly introducing implicit locals and globals
+    for (bid, node_id) in sort!(collect(scope.binding_assignments))
+        # mutable nameless bindings may be introduced in desugaring
+        maybe_declare_in_scope!(ctx, scope, SyntaxTree(ctx.graph, node_id),
+                                get_binding(ctx, bid).kind)
     end
```
Comment (topolarity) [inline JuliaLowering/src/scope_analysis.jl:269]: It feels like it should be possible to unify this with the logic for `scope.assignments` below, since semantically they aren't any different iiuc?

Not a required re-work by any means, but it seems like it might be nice

**Review by topolarity — APPROVED** [review]
Seems like the right approach (and indeed closer to flisp) to update shared bindings across all lambdas simultaneously.

Changes are looking good to me. Nice work @mlechu!

Feel free to take or drop the nits / ideas, as desired.

File: JuliaLowering/src/bindings.jl (hunk 4 above)
Comment (mlechu) [reply JuliaLowering/src/bindings.jl]: No, it's just metadata describing why lowering made it.  The line
```
newleaf(ctx, ex, K"BindingId", b.id)
```
in `_resolve_scopes` creates a new BindingId node for each reference to an identifier.  I tried not creating this node for space-efficiency but realized it messed with provenance.

File: JuliaLowering/src/bindings.jl (hunk 1 above)
Comment (mlechu) [reply JuliaLowering/src/bindings.jl]: Fair point, though the compact printing is good for debugging

File: JuliaLowering/src/bindings.jl (hunk 5 above)
Comment (mlechu) [reply JuliaLowering/src/bindings.jl:156]: They are pretty similar, but for different purposes. `reparent` is "change the graph of this tree (graph structure must be identical to the original, but attributes on the graph may change)".  `binding_ex(ctx, id)` is just an alternative to an `@ast` call where we don't want to make another node (or don't have a good provenance reference for one).  I'm not sure it works so well as a space-saving measure given my comment above on binding nodes not being reused, though.

File: JuliaLowering/src/scope_analysis.jl (hunk 12 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:62]: (discussed in meeting) I'm mirroring our handling of macro scope layers but agree doing `parent` would be cleaner.

File: JuliaLowering/src/scope_analysis.jl (hunk 15 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl]: `implicit` was inaccurate, since they can also be explicit.  The point of this set is to consider extra globals when resolving an assignment-lhs in softened scope. Unknown to me when starting this refactor, flisp does more than checking the current world's defined-and-assigned globals; it also scans the top-level scope for implicit and explicit global assignments.  Maybe `soft_assignable_globals` would be a better name.

File: JuliaLowering/src/scope_analysis.jl (hunk 8 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:70]: Yup, I may have lost a sentence somewhere in the PR comment.  We'll need this if we want to replicate flisp's bad hygiene with globals with some hope of making things better.

File: JuliaLowering/src/scope_analysis.jl (hunk 17 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:269]: I thought that originally, but it was just extra complexity (need a `Union{BindingId, NameKey}` key type in `scope.assignments` and `Base.isless` defined between them, as well as `declare_in_scope!` handling `K"BindingId"` all for resolving something that's already resolved)

File: JuliaLowering/src/scope_analysis.jl (hunk 10 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:467]: Good catch.  We shouldn't hit this, but I've added an assert at the top of this function
```
    @assert scope isa ScopeInfo || k === K"lambda"
```

File: JuliaLowering/test/scopes.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/test/scopes.jl:75]: Thanks for finding this.  I think JL has partially designed for a future implementation of local const, but it should be disallowed for now.

File: JuliaLowering/test/scopes.jl (hunk 3 above)
Comment (mlechu) [reply JuliaLowering/test/scopes.jl:208]: Gives me a sense of security.  If you have other sledgehammer-testing ideas, send them my way!

File: JuliaLowering/src/bindings.jl (hunk 5 above)
Comment (c42f) [reply JuliaLowering/src/bindings.jl:156]: This comment might have been moved somewhere along the way because the "here" isn't very clear anymore.

`binding_ex` isn't actually a space saving measure to avoiding making new nodes. Rather, it's about accurate provenance when introducing bare binding IDs back into an AST.  For example, in desugaring of `@local`.

File: JuliaLowering/test/scopes.jl [hunk 18]
```diff
@@ -58,23 +58,292 @@ begin
...
+        @test_throws LoweringError JuliaLowering.include_string(test_mod, s)
+    end
+    @testset "arg,local" begin
+        s = "function (x); local x; end"
+        @test_throws LoweringError JuliaLowering.include_string(test_mod, s)
+    end
+    @testset "sparam,local" begin
+        s = "function (a::s) where {s}; local s; end"
+        @test_throws LoweringError JuliaLowering.include_string(test_mod, s)
+    end
```
Comment (c42f) [inline JuliaLowering/test/scopes.jl:95]: I think we already test these cases more comprehensively in scopes_ir.jl  (it's more comprehensive because we also test the error messages there)

So I think we can remove these.  Generally my rule of thumb has been to avoid `@test_throws LoweringError` because the IR tests give a convenient way of asserting that the error message has the correct provenance.

Side note - I think it would be nice to bring our IR tests and `eval()` tests closer together with a bit of test infrastructure refactoring at some point. The aim being twofold:
* Reduce confusion and duplication in cases like this 
* Reduce duplication for cases where we want to both test the structure of the IR and the value that it `eval()`'s to.

File: JuliaLowering/test/scopes.jl [hunk 19]
```diff
@@ -58,23 +58,292 @@ begin
...
+
+    # globals may overlap args or sparams (buggy?)  TODO: decide whether it's
+    # worth replicating this behaviour.  We would likely need to copy the way
+    # flisp nests an extra scope block in every lambda.
```
Comment (c42f) [inline JuliaLowering/test/scopes.jl:99]: Eek.  I can't recall right now whether I intentionally tried to depart from the weird flisp behavior or not.  seems potentially breaking to be different (even though it's consistent) - may need to be changed via syntax evolution I guess.

File: JuliaLowering/test/scopes.jl (hunk 18 above)
Comment (c42f) [reply JuliaLowering/test/scopes.jl:95]: Maybe it would also help if we simply added a bit more structure to the IR tests.   Eg, allow structuring the IR test files so that we can group the content into test sets?

**Comment by c42f** [comment]
> `LambdaBindings` is currently a per-lambda map from unique variable to four flags: `captured`, `read`, `assigned`, and `called`. I think (but correct me if I'm wrong @c42f) this was a misinterpretation of the holy text: in flisp lowering, a local variable captured by some other lambda does show up in both lambdas' variable lists, but is the same underlying object, and flag mutations on one variable are seen by all lambdas.

`LambdaBindings` is information about "how is a binding used by the current lambda", as opposed to "how is this binding used by all lambdas".

This distinction can be important as soon as we start work on unboxing captures, so yes I did this on purpose and at first glance I don't like removing this infrastructure - even though it's clearly incomplete at this stage.

> This PR moves all vinfo to BindingInfo and deletes the incorrect bookkeeping

Can you point me to examples of the inaccuracies?  Obviously if they affect semantics of evaluation this is a problem to fix! 

But if they're internal differences you should expect that we'll be diverging a lot from flisp once we properly start on unboxing.

**Comment by c42f** [comment]
As another more concrete example of why `LambdaBindings` is useful, consider the `is_called` flag.

This is metadata which applies to how argument slots are used within the body of the `CodeInfo` - it eventually gets mapped into the CodeInfo's `called` field and used within gf.c for specialization heuristics. These heuristics shouldn't care about the use of a function argument in other lambdas it happens to be captured into, but merely about its direct use in the body of statements. I would argue that flisp is wrong if it tracks this information globally. To make this concrete:

```julia
function f(g)
    function h()
        g()  # should not set `is_called` on `g`'s slot flag in `f`
    end
end
```

You're certainly right to notice a disconnect with flisp - because I didn't actually port the flisp implementation of `vinfo` closely, but instead referred to the runtime C code's actual usage of the metadata which is being produced by lowering as the source of truth.

**Comment by topolarity** [comment]
> These heuristics shouldn't care about the use of a function argument in other lambdas it happens to be captured into, but merely about its direct use in the body of statements.

I don't know if I agree with that - Calling `h()` inside of `f()` would suffer (it will not infer well) if `g` is not marked as called. The heuristic could try to chain this reasoning explicitly by checking whether `h` is called before propagating the flag, but we really do need to match whatever flisp does for specialization behavior to be the same.

**Comment by mlechu** [comment]
> This distinction can be important as soon as we start work on unboxing captures

I'll elaborate on my claim "we need something more complex anyway".  Almost every lambda-vinfo-flags-based unboxing proof I can think of requires other machinery complex enough to make the flags unnecessary.

Right now (ignoring flisp's `lambda-optimize-vars`, which we don't do yet) lowering makes boxes assuming nothing about (1) what parts of the function (including inner functions) are executed or (2) what order they're executed in.  `vinfo` per lambda lambda seem to give us the former until we start trying to use them---when is an inner lambda actually called?  We could call the defining expression, or assign it to a global, or pass it as an argument to `map`, or only call it after a dominating assignment.

The one case the flags give us anything new is when the inner lambda is never called, but proving this in anything other than a trivial case requires basic-block-level or maybe even statement-level analysis.  But with basic-block-level analysis, why are we tracking one "assume everything executes" flag per inner lambda in the first place?

File: JuliaLowering/test/scopes.jl (hunk 19 above)
Comment (mlechu) [reply JuliaLowering/test/scopes.jl:99]: Eek indeed.  I'd be willing to call it a julia bug given how strange it would be to call it part of the language, but we can see what pkgeval says.  I've seen someone ask if decl keywords do something to an existing variable, which is confusion to prevent.

File: JuliaLowering/test/scopes.jl (hunk 18 above)
Comment (mlechu) [reply JuliaLowering/test/scopes.jl:95]: > So I think we can remove these. 

It feels like more effort to selectively delete cases from an "every combination" testset than to just have the full matrix there.

> Side note - I think it would be nice to bring our IR tests and eval() tests closer together with a bit of test infrastructure refactoring at some point

The split we have now is nice in that IR tests don't need to run (no setting up globals) and `eval()` tests don't need to be limited to readable amounts of IR.  My main gripe with our tests isn't duplication, it's that we need to write more of them :)

**Comment by c42f** [comment]
> Calling h() inside of f() would suffer (it will not infer well) if g is not marked as called

Hmm. I was convinced it would be the job of the optimizer to deal with inlining the implementation of `h`, after which the call of `g()` would be self-evident... the same behavior as if `h` were a manually defined closure:

```julia
struct _h_type{G}
    g::G
end

function (h::_h_type)()
   h.g()
end

function f(g)
    h = _h_type(g)
    h()   # lowering cannot know that g is called
end
```

But perhaps I'm mistaken and this is a case where the compiler can use the fact that `h` is a closure to do better than the hand written version?

We also have the following example where the heuristic guesses wrong because the closure isn't called. But I'll concede it's a less likely case and it's high probability that any closure will be called during the lifetime of the enclosing function.

```julia
function f(g)
    function h()
        g()
    end
    return h
end
```

**Comment by c42f** [comment]
Basically - I admit I thought this was an outright bug which I was fixing but it's not actually simple :sweat_smile:

**Comment by c42f** [comment]
> I'll elaborate on my claim "we need something more complex anyway". Almost every lambda-vinfo-flags-based unboxing proof I can think of requires other machinery complex enough to make the flags unnecessary.

I agree that information global to the body of a lambda isn't very powerful. It can help, but the cases it helps with are rather trivial - and I don't think very useful. We need some simple data flow analysis to do unboxig as best we can within lowering.  And "as best we can" is not very powerful because our escape analysis will be extremely pessimistic without information from the optimizer.

Ok, so I'm a bit happier with deleting this stuff for now, assuming that we may need to completely refactor it in the next step anyway.  Would still like to know whether the `is_called` heuristic's behavior with respect to captures was intended or a mere side effect of the way vinfo happens to work currently.

**Comment by topolarity** [comment]
I'm going to merge this as-is

I am a fan of @c42f 's ambitions to improve the specialization heuristics / tighten up the flags here. Nonetheless, I think we'll want to save that for "Phase 2" of the JuliaLowering initiative, after we have already gotten parity with flisp 👍 

This is definitely an improvement in terms of bugs / parity, so let's get it in!

File: JuliaLowering/test/scopes.jl (hunk 19 above)
Comment (c42f) [reply JuliaLowering/test/scopes.jl:99]: Sounds reasonable.

File: JuliaLowering/test/scopes.jl (hunk 18 above)
Comment (c42f) [reply JuliaLowering/test/scopes.jl:95]: > My main gripe with our tests isn't duplication, it's that we need to write more of them :)

Haha! It's the bane of any new project when switching from "this is going fast and everything is changing all the time" to "oh this about to be production code".

Having done several big new development projects, there's always this transition period, and it's critical to the longer term success. So I really appreciate your efforts - and likewise I'll try to do my best to beef up tests whenever I see any missing.

If I find a way to make the tests "more fun" to write I'll also put in the effort there.  I am happy that we have IR tests at all - in contrast to existing lowering. They're still a bit clunky to work with - perhaps we may yet find a way to improve that.

**Comment by c42f** [comment]
> Nonetheless, I think we'll want to save that for "Phase 2" of the JuliaLowering initiative, after we have already gotten parity with flisp

I think that's pretty fair in this case - even if it's a bug (I'm now unsure about this) - keeping consistency with flisp is reasonable because changing specialization could have subtle side effects and need its own review.

Side note - there's several other probable-bugs which I came up against in working through the flisp code for the lowering port as a whole. I mostly chose to fix them when they seemed obviously buggy so we'll be able to close a few existing issues once the integration work is done. Obviously we could reimplement the bugs but that's a bit depressing so hopefully we'll be able to get away with just leaving them fixed :sweat_smile:
