### PR TITLE
Fix reduce(vcat,...) type inference (#40277)

### LINKED ISSUE #40277: `reduce` type inference on 1.6
On julia 1.5
```julia
julia> using Test

julia> x_vecs = ([5, ], [1.0, 2.0, 3.0]);

julia> @inferred reduce(vcat, x_vecs)
4-element Array{Float64,1}:
 5.0
 1.0
 2.0
 3.0
```

On julia 1.6
```julia
julia> @inferred reduce(vcat, x_vecs)
ERROR: return type Vector{Float64} does not match inferred return type AbstractVector{T} where T
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ REPL[66]:1

julia> @inferred vcat(x_vecs...)
4-element Vector{Float64}:
 5.0
 1.0
 2.0
 3.0
```

### PR DESCRIPTION
**Pull request by dlfivefifty**
Fixes #40277

### CODE REVIEW

**Comment by thchr** [comment]
This may be a stupid question, but why does `sum(map(length, V))` lead to succesful inference here while `sum(length, V)` doesn't (which I thought would be more idiomatic)? Same, question essentially for the original `mapreduce(length, +, V)`?

I realize `V` is a tuple, which I guess is a salient point, but I had imagined either of those variations would "work" the same way (e.g., they have the same performance and essentially the same native code in isolation; but I can see how that is separate from how they interact with inferrence)?

**Comment by JeffBezanson** [comment]
Not a stupid question at all; they should be the same. Maybe due to #35800.

**Comment by dlfivefifty** [comment]
I've had to work around quite a few type-inference issues and there are a number of rules of thumbs I've picked up:
1. `map(f, v)` is more reliable than `broadcast(f, v)`
2. `sum(map(f, v))` is more reliable than `mapreduce(f, +, v)`
3. Sometimes it helps to write out a `map` or `mapreduce` explicitly: i.e. instead of `mapreduce(f, +, v)` one could write a function `mapplus(v...)` a la
```julia
mapplus() = 0
mapplus(x, y...) = f(x) + mapplus(x, y...)
```

**Comment by KristofferC** [comment]
I added an extra test that was reported from that issue

**Review by KristofferC — APPROVED** [review]

File: base/abstractarray.jl [hunk 1]
```diff
@@ -1490,7 +1490,7 @@ AbstractVecOrTuple{T} = Union{AbstractVector{<:T}, Tuple{Vararg{T}}}
 
 _typed_vcat_similar(V, ::Type{T}, n) where T = similar(V[1], T, n)
 _typed_vcat(::Type{T}, V::AbstractVecOrTuple{AbstractVector}) where T =
```
Comment (simeonschaub) [inline base/abstractarray.jl:1492]: Can we make this change just for `V::Tuple` and keep using `mapreduce` for `V::AbstractVector`, since in that case, it is probably beneficial to avoid the extra allocation?

Comment (dlfivefifty) [reply base/abstractarray.jl:1492]: Since `vcat` itself is allocating I don't think this will make any noticeable difference, but it's easy to add if there's a good argument for why it's still needed.
