### PR TITLE
parentindices and parent of substring

### LINKED ISSUE #49341: SubString: parentindices don't work
For array views, `parentindices` return the view indices in the parent. However, this function doesn't work for string views:
```julia
julia> view([1,2,3], 2:3) |> parentindices
(2:3,)

julia> view("abc", 2:3) |> parentindices
ERROR: MethodError: no method matching parentindices(::SubString{String})
```
Would be very useful to support it too. For example, to retrieve substring locations after string functions like `split`.

`parentindices` should be computable from `SubString`, though it doesn't directly contain the range and I'm not sure how to compute it correctly given how strings are indexed:
```julia
julia> view("abc", 2:3) |> dump
SubString{String}
  string: String "abc"
  offset: Int64 1
  ncodeunits: Int64 2
```

### PR DESCRIPTION
**Pull request by aplavin**
Fix https://github.com/JuliaLang/julia/issues/49341

### CODE REVIEW

**Comment by jakobnissen** [comment]
Thanks for the PR! Could you perhaps also update the docstring of `parent` and `parentindices` to mention the functions also work for `SubString`?

Also, I would feel more comfortable if some more senior dev gave this feature a thumbs up. While your addition looks great to me personally, I've seen a few times now that the semantics of certain Julia functions get eroded over time as people add new methods that doesn't _quite_ correspond to the intended semantics of the original function. I'm not 100% sure what the semantics of `parentindices` ought to be.

**Comment by StefanKarpinski** [comment]
I'm ok with this. In general the `parent` stuff is a bit regrettable, but given that we have it and it makes sense for the `SubString` type, it seems like it ought to work for that type.

File: test/strings/basic.jl [hunk 1]
```diff
@@ -176,8 +176,11 @@ end
     x = "abcdefg"
     @testset "basic unit range" begin
         @test SubString(x, 2:4) == "bcd"
-        @test view(x, 2:4) == "bcd"
-        @test view(x, 2:4) isa SubString
+        sx = view(x, 2:4)
+        @test sx == "bcd"
+        @test sx isa SubString
+        @test parent(sx) == x
```
Comment (jakobnissen) [inline test/strings/basic.jl:182]:
```suggestion
        @test parent(sx) === x
```

**Review by jakobnissen — APPROVED** [review]
