### PR TITLE
fix printing of Float32s

### LINKED ISSUE #33904: wriedlm writes Float32s in a way it cannot parse back
Circuitscape.jl tests pass (with 1 known error) on 1.3-rc5 and earlier releases. However on master (Julia Version 1.4.0-DEV.512 Commit 5516f40839 (2019-11-20 18:41 UTC)), I noticed more test failures. It seems like a regression.

https://github.com/Circuitscape/Circuitscape.jl/issues/202

This shouldn't have happened:
```
Raster One to All: Error During Test at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:366
  Test threw exception
  Expression: compare_aagrid(r, x, tol)
  MethodError: no method matching compare_aagrid(::Array{Any,2}, ::Array{Float64,2}, ::Float64)
  Closest candidates are:
    compare_aagrid(::Array{T,2}, !Matched::Array{T,2}, ::Any) where T at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:398
    compare_aagrid(::Array{T,2}, !Matched::Array{T,2}) where T at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:398
  Stacktrace:
   [1] compare_all_output(::String, ::Bool) at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:366
   [2] macro expansion at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:330 [inlined]
   [3] macro expansion at /Users/viral/julia/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1110 [inlined]
   [4] macro expansion at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:324 [inlined]
   [5] macro expansion at /Users/viral/julia/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1110 [inlined]
   [6] runtests(::typeof(compute_single)) at /Users/viral/.julia/dev/Circuitscape/src/utils.jl:260
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/33904

### CODE REVIEW

File: test/show.jl [hunk 1]
```diff
@@ -966,7 +966,8 @@ test_repr("(:).a")
 @test isa(repr("text/plain", String(UInt8[0x00:0xff;])), String)
 
 # don't use julia-specific `f` in Float32 printing (PR #18053)
-@test sprint(print, 1f-7) == "1.0f-7"
```
Comment (quinnj) [inline test/show.jl]: lol....

**Review by quinnj — APPROVED** [review]
This LGTM

File: test/show.jl (hunk 1 above)
Comment (KristofferC) [reply test/show.jl]: 🤫
