### PR TITLE
[JuliaLowering] Make locals introduced in `K"method_defs"` top-level

### LINKED ISSUE #134: "Found unexpected binding of kind local" when lowering closure with static parameter
```julia
julia> JuliaLowering.include_string(Main, raw"""
       foo() = function inner(::Type{SV}) where SV
           nothing
       end
       """; expr_compat_mode=true)

ERROR: LoweringError:
foo() = function inner(::Type{SV}) where SV
#                                        └┘ ── Found unexpected binding of kind local
    nothing
end

Detailed provenance:
#₈/SV
└─ SV
   └─ SV
      └─ @ string:1
```

<details>
<summary>Stacktrace</summary>

```julia
Stacktrace:
  [1] _renumber(ctx::JuliaLowering.LinearIRContext{…}, ssa_rewrites::Dict{…}, slot_rewrites::Dict{…}, label_table::Dict{…}, ex::JuliaSyntax.SyntaxTree{…})
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/linear_ir.jl:994
  [2] #_renumber##2
    @ ~/repos/julia/JuliaLowering/src/linear_ir.jl:1018 [inlined]
  [3] mapchildren(f::JuliaLowering.var"#_renumber##2#_renumber##3"{…}, ctx::JuliaLowering.LinearIRContext{…}, ex::JuliaSyntax.SyntaxTree{…}, do_map_child::JuliaSyntax.var"#mapchildren##1#mapchildren##2")
    @ JuliaSyntax ~/repos/julia/JuliaSyntax/src/porcelain/syntax_graph.jl:658
  [4] mapchildren(f::Function, ctx::JuliaLowering.LinearIRContext{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
    @ JuliaSyntax ~/repos/julia/JuliaSyntax/src/porcelain/syntax_graph.jl:695
  [5] _renumber(ctx::JuliaLowering.LinearIRContext{…}, ssa_rewrites::Dict{…}, slot_rewrites::Dict{…}, label_table::Dict{…}, ex::JuliaSyntax.SyntaxTree{…})
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/linear_ir.jl:1017
  [6] renumber_body(ctx::JuliaLowering.LinearIRContext{Dict{…}}, input_code::JuliaSyntax.SyntaxList{Dict{…}, Vector{…}}, slot_rewrites::Dict{Int64, Int64})
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/linear_ir.jl:1058
  [7] compile_lambda(outer_ctx::JuliaLowering.LinearIRContext{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/linear_ir.jl:1132
  [8] linearize_ir(ctx::JuliaLowering.ClosureConversionCtx{Dict{Symbol, Any}}, ex::JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/linear_ir.jl:1170
  [9] lower_step(iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module, world::UInt64)
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:98
 [10] lower_step(iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module)
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:46
 [11] lower_step(iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module, world::UInt64)
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:71
 [12] lower_step
    @ ~/repos/julia/JuliaLowering/src/eval.jl:46 [inlined]
 [13] _eval(mod::Module, iter::JuliaLowering.LoweringIterator{Dict{Symbol, Any}})
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:478
 [14] #eval#133
    @ ~/repos/julia/JuliaLowering/src/eval.jl:466 [inlined]
 [15] eval
    @ ~/repos/julia/JuliaLowering/src/eval.jl:462 [inlined]
 [16] #include_string#135
    @ ~/repos/julia/JuliaLowering/src/eval.jl:535 [inlined]
 [17] include_string
    @ ~/repos/julia/JuliaLowering/src/eval.jl:533 [inlined]
 [18] kwcall(::@NamedTuple{expr_compat_mode::Bool}, ::typeof(JuliaLowering.include_string), mod::Module, code::String)
    @ JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:533
 [19] top-level scope
    @ REPL[1]:1
Some type information was truncated. Use `show(err)` to see complete types.
```
</details>

### PR DESCRIPTION
**Pull request by mlechu**
flisp lowering emits `method` expressions directly from desugaring, but this
makes life hard when variables in the method signature are lifted in closure
conversion.  JuliaLowering bundles method expressions together under a
`method_defs` expression to make this lifting easier, but its scope analysis
ignores the `method_defs` form, so we end up lifting variable uses without their
declarations.  This PR makes `method_defs` behave like a normal `scope_block` in
scope resolution (i.e. names are not lifted), but all introduced locals are
placed in the top-level lambda for the purposes of `analyze_variables!` and
beyond.

I did this by adding an `is_lifted` field to `ScopeInfo`.  There's probably a
way to do it with the existing `scope.lambda_id`, but the real containing lambda
could be handy to keep around, and I think this is easier to reason about.

Something like this PR was discussed as a cleaner alternative to copying flisp's
`replace-vars`, though I suspect the best solution would be to have desugaring
not tear apart methods so eagerly and completely.

Also in this PR:
- Some cleanup was needed in scope_analysis.jl to make this work:
  `resolve_scopes` is now always responsible for assigning variables to lambdas,
  and `analyze_variables` is always responsible for captures.

- Made declaration-finding a bit stricter, requiring desugaring tweaks.
  Desugaring currently makes a bunch of `new_local_binding`s that get declared
  in multiple unrelated scopes in the output (e.g. an argument that's followed
  by an optional positional arg in the input).  The semantics of this elude me,
  and I think `BindingInfo`s are supposed to refer to unique variables, so this
  PR uses scope-layer-separated symbols instead.
  - The new `lambda_id` field on BindingInfo is part of this.  I think this
    could eventually replace most of `lambda_bindings` eventually.

- The above fixes the `#self#` discrepancy mentioned in
  https://github.com/JuliaLang/julia/pull/60316.  The slot flags in the IR tests
  better match flisp now.

Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/134.  SparseArrays and
SuiteSparse now precompile!

https://github.com/JuliaLang/JuliaLowering.jl/issues/139 is not fixed by this
change, but I do think it's a prerequisite, because that's what I started working
on before finding myself here...

### CODE REVIEW

File: JuliaLowering/src/closure_conversion.jl [hunk 1]
```diff
@@ -126,36 +126,33 @@ function convert_for_type_decl(ctx, srcref, ex, type, do_typeassert)
...
-    if !ctx.toplevel_pure
-        decl = @ast ctx src_ex [K"block"
-            [K"call"
-                "declare_global"::K"core"
-                mod::K"Value" name::K"Symbol" strong::K"Bool"
-                type
-            ]
-            [K"latestworld"]
-            "nothing"::K"core"
+function make_globaldecl(ctx, src_ex, mod, name, strong=false, type=nothing)
```
Comment (c42f) [inline JuliaLowering/src/closure_conversion.jl:129]: Good cleanup to get rid of `ret_nothing` here and use TOMBSTONE :+1:

File: JuliaLowering/src/desugaring.jl [hunk 2]
```diff
@@ -93,6 +93,13 @@ function check_no_assignment(exs, msg="misplaced assignment statement in `[ ...
     end
 end
 
+# Generating a new_local_binding or ssaval should only be done if we can
+# guarantee there's some scope it's declared in, and that it's not declared or
+# used outside of that scope (binding capture is OK).  This is the alternative.
+function fresh_sym(ctx, srcref::SyntaxTree, name::String)
```
Comment (c42f) [inline JuliaLowering/src/desugaring.jl]: Looks reasonable. Hopefully it's not a problem to have a *lot* of scope layers... they are lighter than `BindingInfo` though so I guess it's fine!

It would be nice to ensure these never end up global "by mistake" in the same way that macro expanded identifiers skip accidentally becoming global by the use of the is_macro_expansion flag on the scope layer. I think we should rename that flag to implicit_toplevel_globals and use it here too.

How about calling it `newvar()` or `new_var()` I feel that would fit in a bit more neatly with the rest of the naming.

File: JuliaLowering/src/desugaring.jl [hunk 3]
```diff
@@ -2758,7 +2757,8 @@ function keyword_function_defs(ctx, srcref, callex_srcref, name_str, typevar_nam
         for n in kw_names
             # If not using slots for the keyword argument values, still declare
             # them for reflection purposes.
-            push!(kw_val_stmts, @ast ctx n [K"local"(meta=CompileHints(:is_internal, true)) n])
+            local_n = @ast ctx n [K"local" n]
+            push!(kw_val_stmts, setmeta!(local_n, :is_internal, true))
```
Comment (c42f) [inline JuliaLowering/src/desugaring.jl]: Why the mutating variant?

In general I feel we should avoid expression mutation in lowering if possible outside of utilities in ast.jl. Yes, even in trivial/local cases because using mutation just makes everything harder to reason about.

I see there's quite a lot now... Can we do less of it, not more?  If it's just a matter of annoying `@ast` syntax or inconvenient utility functions I'd much prefer to fix those rather than do more mutation.

File: JuliaLowering/src/scope_analysis.jl [hunk 4]
```diff
@@ -29,27 +29,40 @@ struct ScopeInfo
...
+        is_permeable = ex.is_toplevel_thunk
+        is_lifted = false
+    else
+        parent = ctx.scopes[parent_id]
+        lambda_id = kind(ex) === K"lambda" ? id : parent.lambda_id
+        is_permeable = (
+            kind(ex) === K"scope_block" && ex.scope_type === :neutral &&
+                parent_id !== 0 && ctx.scopes[parent_id].is_permeable)
+        is_lifted = kind(ex) === K"method_defs" ||
+            (kind(ex) !== K"lambda" && parent.is_lifted)
```
Comment (c42f) [inline JuliaLowering/src/scope_analysis.jl:61]: tricky.  looks correct :+1:

File: JuliaLowering/src/scope_analysis.jl [hunk 5]
```diff
@@ -113,8 +126,12 @@ _var_str(v) = v === :local ? "local variable" :
 function maybe_declare_in_scope!(ctx, scope::ScopeInfo, ex, new_k::Symbol)
     if kind(ex) === K"BindingId"
         bid = ex.var_id
-        @assert get_binding(ctx, bid).kind === new_k
-        record_lambda_var!(ctx, scope, get_binding(ctx, bid), capt=false)
+        b = get_binding(ctx, bid)
+        @assert b.kind === new_k
+        if b.lambda_id !== 0
+            throw(LoweringError(ex, "cannot declare a BindingId in multiple scopes"))
```
Comment (c42f) [inline JuliaLowering/src/scope_analysis.jl]: I assume this would be an internal error in lowering?

File: JuliaLowering/src/scope_analysis.jl [hunk 6]
```diff
@@ -152,29 +169,38 @@ function declare_in_scope!(ctx, scope::ScopeInfo, ex, bk::Symbol; kws...)
         declaration_scope = scope
         mod = nothing
     end
-    b = _new_binding(ctx, ex, nk.name, bk; mod, kws...)
+    b = _new_binding(ctx, ex, nk.name, bk;
+                     mod, is_internal=getmeta(ex, :is_internal, false), kws...)
```
Comment (c42f) [inline JuliaLowering/src/scope_analysis.jl]: Looks reasonable. It could also be ok or maybe good to have an extra flag on `ScopeLayer` for `is_internal`. A bit like a "light" version of `BindingInfo`.

File: JuliaLowering/src/scope_analysis.jl [hunk 7]
```diff
@@ -183,6 +209,7 @@ function needs_resolution(ex)
 end
 
 function resolve_name(ctx, ex; exclude_toplevel_globals=false)
+    # TODO: probably want to cache these lookups
```
Comment (c42f) [inline JuliaLowering/src/scope_analysis.jl:211]: Sure, could easily have a lazily filled cache on the scope if we find it helps performance.

**Review by c42f — COMMENTED** [review]
This seems like the right way to go.  I'd avoided writing the equivalent of `fresh_sym` for a while because I didn't want so many scope layers but seeing it in action it's clear this is better.

We could also consider replacing the very-few other places where desugaring uses `new_local_binding()` in future.

Looks good to me just needs a few tests I guess we should cover the crazy cases such as the following

```julia
julia> function g()
           function f(x::(let z = T; Vector{z} end)) where {T <: Integer}
               @info "hi"
           end
       end
g (generic function with 1 method)

julia> g()([1])
[ Info: hi

julia> g()(["what"])
ERROR: MethodError: no method matching (::var"#f#g##2")(::Vector{String})
The function `f` exists, but no method is defined for this combination of argument types.
```

File: JuliaLowering/src/desugaring.jl (hunk 2 above)
Comment (topolarity) [reply JuliaLowering/src/desugaring.jl]: The documentation for `ScopeLayer` could also use some minor updates:

> Normal code contains a single scope layer, whereas each macro expansion
generates a new layer.

Comment (topolarity) [reply JuliaLowering/src/desugaring.jl]: P.S. I don't really grok the exact rules for `fresh_sym` vs. `new_local_binding` yet (I need to do some independent study), but is it worth adding a quick note for the remaining uses about why they are correct, given the extra side conditions?

File: JuliaLowering/src/scope_analysis.jl (hunk 6 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl]: Good idea, added a flag.  This particular line is unrelated right now (just moves some code from https://github.com/JuliaLang/julia/pull/60587) but I could track it with the internal scope layer system instead.

File: JuliaLowering/src/scope_analysis.jl (hunk 5 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl]: Yep, just wanted to see the tree.  Should we make an InternalLoweringError?

File: JuliaLowering/src/desugaring.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/src/desugaring.jl]: > How about calling it newvar() or new_var() I feel that would fit in a bit more neatly with the rest of the naming.

(Pedantry alert) Not a variable for the same reason `new_local_binding` didn't work, maybe `newsym`?

> I don't really grok the exact rules for fresh_sym vs. new_local_binding yet

> is it worth adding a quick note for the remaining uses about why they are correct

`new_local_binding` signals to scope resolution that the job is already done, and we don't need to go through the local/global declaration/assignment dance to figure out how many variables some symbol corresponds to.  `fresh_sym` is just `gensym` with a number (layer_id) instead of name mangling.  I think we could replace the existing `new_local_binding` calls with `fresh_sym` and it would be fine.

Comment (c42f) [reply JuliaLowering/src/desugaring.jl]: > Not a variable for the same reason new_local_binding didn't work

How is it not equivalent to a normal identifier? It seems the same to me?

> `fresh_sym` is just `gensym` with a number instead of name mangling

It achieves the same thing, sure.  But it should be a normal hygienic name, equivalent to a macro using a variable.

File: JuliaLowering/src/scope_analysis.jl (hunk 5 above)
Comment (c42f) [reply JuliaLowering/src/scope_analysis.jl]: I don't think we need a whole new exception type. A utility function could be useful though:

```
internal_error(ex, msg) = throw(LoweringError(ex, "Internal lowering error: $msg"))
```

File: JuliaLowering/src/desugaring.jl (hunk 3 above)
Comment (mlechu) [reply JuliaLowering/src/desugaring.jl]: This particular change looks like a mistake, as I remember trying to change it to `@ast ctx n [K"local" n(meta=CompileHints(:is_internal, true))]`.  

Agree we should avoid mutation, but I'd argue the `push!` on this line is a bigger problem for reasoning about.

> inconvenient utility functions

I did make them more inconvenient in https://github.com/JuliaLang/julia/pull/60191.  `makenode(ctx, ex, etc; a=b)` became `setattr!(makenode(ctx, ex, etc), :a, b)` in a bunch of places. I'm OK with restoring the previous syntax with a macro at some point.

**Comment by mlechu** [comment]
Tests added, a few broken.  @c42f do you remember if static parameter capture was left as a TODO at some point?

File: JuliaLowering/src/desugaring.jl (hunk 3 above)
Comment (c42f) [reply JuliaLowering/src/desugaring.jl]: > I did make them more inconvenient

Ah yes. A macro would be fine if we can't resurrect the keyword function in a way which is reasonable on the compiler.

File: JuliaLowering/test/scopes_ir.jl [hunk 8]
```diff
@@ -199,12 +199,14 @@ end
...
 8   (call core.svec %₅ %₆ %₇)
 9   --- method core.nothing %₈
-    slots: [slot₁/#self#(!read) slot₂/z]
+    slots: [slot₁/#self# slot₂/z]
     1   (call core.apply_type top.Dict core.Symbol core.Any)
     2   (call %₁)
     3   (gotoifnot true label₅)
-    4   (call top.setindex! %₂ slot₂/z :z)
-    5   (return %₂)
+    4   (call top.setindex! %₂ slot₁/#self# :#self#)
```
Comment (c42f) [inline JuliaLowering/test/scopes_ir.jl]: `@locals` should not (or currently does not, in flisp) include internal names so I think this is a bug.

File: JuliaLowering/src/desugaring.jl [hunk 9]
```diff
@@ -4635,6 +4624,11 @@ function expand_forms_2(ctx::DesugaringContext, ex::SyntaxTree, docs=nothing)
         ]
     elseif k == K"inert" || k == K"inert_syntaxtree"
         ex
+    elseif k == K"foreigncall"
+        @ast ctx ex [K"foreigncall"
+            expand_C_library_symbol(ctx, ex[1])
+            map(c->expand_forms_2(ctx, c), ex[2:end])...
+        ]
```
Comment (c42f) [inline JuliaLowering/src/desugaring.jl]: Needs test?

File: JuliaLowering/test/closures.jl [hunk 10]
```diff
@@ -472,6 +472,81 @@ end
...
+""") == (1, Int)
+
+@test_broken JuliaLowering.include_string(test_mod, """
+begin
+    function f_many_closure_sp_capt(x::T where T)
+        function (); function (); function (); (x, T) end; end; end
+    end
+    f_many_closure_sp_capt(1)()()()
+end
+""") == (1, Int)
```
Comment (c42f) [inline JuliaLowering/test/closures.jl:527]: I don't expect this test to work: the `T` is not a typevar which is in scope for the inner closure, it's just a part of the `UnionAll` definition?

Did you mean to use `f_many_closure_sp_capt(x::T) where T` ?

File: JuliaLowering/test/closures.jl [hunk 11]
```diff
@@ -472,6 +472,81 @@ end
...
+
+@test_broken JuliaLowering.include_string(test_mod, """
+begin
+    function f_argcapt_sp(x::T) where T
+        (inner_x::T)->(x, inner_x, T)
+    end
+    f_argcapt_sp(1)(2)
+end
+""") == (1, 2, Int)
```
Comment (c42f) [inline JuliaLowering/test/closures.jl:536]: This one seems to be a bug, yes.

I thought I tried to make this work. But maybe I'm just remembering reading the flisp code which goes to extra lengths to get selected cases working when inner method declarations depend on static parameters from the outer function.

If I remember flisp makes this work by making the type of `inner` parametric on `T`

File: JuliaLowering/src/desugaring.jl [hunk 12]
```diff
@@ -1915,7 +1924,7 @@ function expand_call(ctx, ex)
         @chk numchildren(ex) in 2:3  (ex, "cglobal must have one or two arguments")
         return @ast ctx ex [K"call"
             ex[1]
-            expand_C_library_symbol(ctx, ex[2])
+            expand_forms_2(ctx, ex[2])
```
Comment (c42f) [inline JuliaLowering/src/desugaring.jl:1927]: Note that removing `static_eval` here works at runtime but causes the tuple to be outlined in the lowered IR. That's fine provided the compiler later inlines it again during constant propagation but it does make `cglobal` performance depend on that optimization.  (Probably fine??)

Basically we want to avoid hitting the fallback path here https://github.com/JuliaLang/julia/blob/9484a9202916ab6e23e058ce9bbb1d91ab75c867/src/ccall.cpp#L815

File: JuliaLowering/src/scope_analysis.jl [hunk 13]
```diff
@@ -198,11 +224,7 @@ function _find_scope_decls!(ctx, scope, ex)
     if k === K"local" && kind(ex[1]) === K"Identifier"
         var_k = getmeta(ex, :is_destructured_arg, false) ?
             :destructured_arg : :local
-        if getmeta(ex, :is_internal, false)
-            declare_in_scope!(ctx, scope, ex[1], var_k; is_internal=true)
-        else
```
Comment (c42f) [inline JuliaLowering/src/scope_analysis.jl:203]: I'm not sure this is a bug a such, but it may be causing the bug in the way `@locals` expands?

File: JuliaLowering/test/closures.jl [hunk 14]
```diff
@@ -472,6 +472,81 @@ end
...
+
+# Note this doesn't work in flisp either
```
Comment (c42f) [inline JuliaLowering/test/closures.jl]:
```suggestion
# Inner method typevar `U` depending on a static parameter `T` so hoisting the method def
# for `inner` out to top level would require detecting this and making `inner` parametric on `T`.
# Note this doesn't work in flisp either
```

File: JuliaLowering/test/function_calls_ir.jl [hunk 15]
```diff
@@ -502,9 +502,11 @@ ccall(:foo, Csize_t, (Cstring..., Cstring...), "asdfg", "blah")
 # cglobal special support for (sym, lib) tuple
```
Comment (c42f) [inline JuliaLowering/test/function_calls_ir.jl:502]:
```suggestion
# cglobal special support for (sym, lib) tuple
# unlike flisp we outline the tuple and allow constant propgation to put it back
# before codegen generates code for `cglobal`
```

**Review by c42f — COMMENTED** [review]
Looking close!

There's a few bugs (or probable-bugs) I've spotted.

> do you remember if static parameter capture was left as a TODO at some point

It looks like the extra logic to make this work never made it?  I remember at least reading the flisp version and being slightly horrified at the way this was done, but can't remember if it was implemented (and it seems not)

File: JuliaLowering/src/desugaring.jl (hunk 12 above)
Comment (topolarity) [reply JuliaLowering/src/desugaring.jl:1927]: Ironically this probably optimizes successfully linearized but not otherwise, thanks to https://github.com/JuliaLang/julia/issues/60978

would be good to check though

File: JuliaLowering/src/scope_analysis.jl (hunk 13 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:203]: The original branch on is_internal was from https://github.com/JuliaLang/julia/pull/60587/changes.  Both `declare_in_scope` and `maybe_declare_in_scope` work here given that we only use `is_internal` in one place, but generally the `maybe` variant is correct if we have `is_internal` elsewhere.

File: JuliaLowering/test/scopes_ir.jl (hunk 8 above)
Comment (mlechu) [reply JuliaLowering/test/scopes_ir.jl]: Yup, I wasn't reading from the new `is_internal` scope layer flag

File: JuliaLowering/src/desugaring.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/src/desugaring.jl]: (resolved on slack: var != sym)

File: JuliaLowering/test/closures.jl (hunk 10 above)
Comment (mlechu) [reply JuliaLowering/test/closures.jl:527]: Yes + fixed, thanks!

File: JuliaLowering/src/scope_analysis.jl [hunk 16]
```diff
@@ -168,8 +168,8 @@ function declare_in_scope!(ctx, scope::ScopeInfo, ex, bk::Symbol; kws...)
         declaration_scope = scope
         mod = nothing
     end
-    b = _new_binding(ctx, ex, nk.name, bk;
-                     mod, is_internal=getmeta(ex, :is_internal, false), kws...)
+    is_internal = ctx.scope_layers[nk.layer].is_internal || getmeta(ex, :is_internal, false)
```
Comment (c42f) [inline JuliaLowering/src/scope_analysis.jl:171]: I think the `is_internal` meta isn't used elsewhere so we can delete it?

**Review by c42f — APPROVED** [review]
Should be good to go except for a minor cleanup.

Test failures seem unrelated?

File: JuliaLowering/src/scope_analysis.jl (hunk 16 above)
Comment (mlechu) [reply JuliaLowering/src/scope_analysis.jl:171]: Still produced from kw-function desugaring for now

**Comment by topolarity** [comment]
Thanks @mlechu and @c42f ! This ended up looking significantly better than the equivalent flisp hacks.

I would probably still be in favor of eliminating (or re-factoring) this weird lifted scoping in the future rather than complicate any lowering-side analyses we want to do eventually (I guess maybe they can just skip these top-level sections entirely), but that's definitely a >1.0 concern 👍
