### PR TITLE
Fix sparse type parameter (fixes #22110)

### LINKED ISSUE #22110: spzeros and speye are really slow
I searched and couldn't find any open issue on this, which surprised me.

Not too sure what the problem is with the code in Base, but if I write my own `spzeros`, it is much faster (the same thing happens with `speye`):

```julia
julia> using BenchmarkTools

julia> @benchmark spzeros(5,5)
BenchmarkTools.Trial:
  memory estimate:  1.11 KiB
  allocs estimate:  18
  --------------
  minimum time:     9.330 μs (0.00% GC)
  median time:      9.953 μs (0.00% GC)
  mean time:        10.215 μs (0.00% GC)
  maximum time:     60.647 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> function my_spzeros(m,n)
           ((m < 0) || (n < 0)) && throw(ArgumentError("invalid Array dimensions"))
           rowval = Vector{Int}(0)
           colptr = ones(Int,n+1)
           nzval  = Vector{Float64}(0)
           return SparseMatrixCSC(m,n,colptr,rowval,nzval)
       end
my_spzeros (generic function with 1 method)

julia> @benchmark my_spzeros(5,5)
BenchmarkTools.Trial:
  memory estimate:  336 bytes
  allocs estimate:  4
  --------------
  minimum time:     88.951 ns (0.00% GC)
  median time:      97.654 ns (0.00% GC)
  mean time:        117.422 ns (13.87% GC)
  maximum time:     1.565 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     965
```

### PR DESCRIPTION
**Pull request by jebej**

### CODE REVIEW

File: base/sparse/sparsematrix.jl [hunk 1]
```diff
@@ -1418,7 +1423,7 @@ if not specified.
 `sparse(α*I, m, n)` can be used to efficiently create a sparse
```
Comment (jebej) [inline base/sparse/sparsematrix.jl]: Is this supposed to work?

Comment (jebej) [inline base/sparse/sparsematrix.jl]: yes, on 0.6

**Review by KristofferC — COMMENTED** [review]
Was it needed to put in so many places just to fix `spzeros` and `speye`? Or are the other ones fixing other things?

**Comment by jebej** [comment]
It fixes `similar` as well, which I have checked, and I assume (haven't tested it) it would fix `_mapreducezeros`, since I just made the same change.

**Comment by jebej** [comment]
It seems to have passed the [sparse tests](https://travis-ci.org/JuliaLang/julia/jobs/236935696#L1441) and all those functions are being tested, so I think it's okay.

File: base/sparse/sparsematrix.jl [hunk 2]
```diff
@@ -292,7 +292,10 @@ function copy!(A::SparseMatrixCSC, B::SparseMatrixCSC)
     return A
 end
 
-similar(S::SparseMatrixCSC, Tv::Type = eltype(S)) = SparseMatrixCSC(S.m, S.n, copy(S.colptr), copy(S.rowval), Vector{Tv}(length(S.nzval)))
+function similar(S::SparseMatrixCSC, ::Type{Tv} = eltype(S)) where {Tv}
```
Comment (musm) [inline base/sparse/sparsematrix.jl]: No need for the braces around `{Tv}`

Comment (musm) [inline base/sparse/sparsematrix.jl]: same for  `speye_scaled` and  `_mapreducezeros`

Comment (jebej) [inline base/sparse/sparsematrix.jl]: Unfortunately I don't know how to fix this without opening an other pull request :( I just edited the file in Github... I hope that's not a huge issue.

Comment (musm) [inline base/sparse/sparsematrix.jl]: On the same git branch make these changes then commit then and push them. They will show up here

Comment (ViralBShah) [inline base/sparse/sparsematrix.jl]: Editing in github is not going to be convenient for contributing to Julia. Git can be a bit difficult at first, but you can pretty easily get into the groove. Basically, once you have a branch set up to be a PR, you can keep committing to the same branch. When we merge your PR, we will combine into one big commit.

Opening a new PR every time creates a lot of noise otherwise, and splits the discussion and reviews into too many places.

**Comment by kshyatt** [comment]
Congrats on your first Julia PR, @jebej! Welcome to julia, and thanks for taking a whack at this 🐛 .

File: base/sparse/sparsematrix.jl [hunk 3]
```diff
@@ -1428,7 +1433,7 @@ end
 
 speye_scaled(diag, m::Integer, n::Integer) = speye_scaled(typeof(diag), diag, m, n)
 
-function speye_scaled(T, diag, m::Integer, n::Integer)
+function speye_scaled(::Type{T}, diag, m::Integer, n::Integer) where T
```
Comment (tkelman) [inline base/sparse/sparsematrix.jl]: this is technically more restrictive than the existing signature, but looks like no one is calling this in registered packages and all the call sites in base pass a type

Comment (jebej) [inline base/sparse/sparsematrix.jl]: Given T is passed as a type argument to Vector it needs to be a type, no?

Comment (jebej) [inline base/sparse/sparsematrix.jl]: Given T is passed as a type argument to Vector it needs to be a type, no?

File: base/sparse/sparsematrix.jl (hunk 2 above)
Comment (nalimilan) [inline base/sparse/sparsematrix.jl]: Maybe better keep the short function syntax for one-liners like this?

Comment (tkelman) [inline base/sparse/sparsematrix.jl]: it's a pretty long line

Comment (nalimilan) [inline base/sparse/sparsematrix.jl]: Of course you would split it into two lines (as in other places in the file).

**Comment by jebej** [comment]
Is there anything else to do here?

**Comment by KristofferC** [comment]
Let's run the benchmarks just to check and then we can merge

@nanosoldier `runbenchmarks("sparse", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22111#issuecomment-304722425) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a7b4a209ccf84696989646c791d722835ae42430/14f65e6_vs_75541d2/report.md). cc @jrevels

**Comment by KristofferC** [comment]
Thanks!
