### PR TITLE
Fix serialization of code instances.

### LINKED ISSUE #46296: Assertion/hang precompiling code that calls inference with custom AbstractInterpreter
See https://github.com/JuliaLang/julia/issues/46296#issuecomment-1210463854 for a MWE.

---

I was trying out SnoopPrecompile with CUDA.jl in an attempt to reduce TTFX, but doing so crashes Julia. I added the following to CUDA.jl's `src/precompile.jl`:

```julia
using SnoopPrecompile

@precompile_all_calls begin
    target = PTXCompilerTarget(; cap=v"7.0")
    params = CUDACompilerParams()
    job = CompilerJob(target, FunctionSpec(identity, Tuple{Nothing}, true), params)
    GPUCompiler.code_native(devnull, job)
end
```

On 1.8, this results in:

```
signal (11): Segmentation fault
in expression starting at none:1
jl_deserialize_value_singleton at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/src/dump.c:1941 [inlined]
jl_deserialize_value at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/src/dump.c:2160
```

From a cursory look, it's inspecting `dt->instance` while `dt` is null. Reproducing this doesn't require a GPU, CUDA.jl can precompile without, but in any case here's an rr recording: https://s3.amazonaws.com/julialang-dumps/reports/2022-08-09T15-39-40-maleadt.tar.zst

I wanted to cut-out CUDA and reproduce this on GPUCompiler with a debug build, but I'm getting a different error adding the following to GPUCompiler's `src/precompile.jl`:

```julia
using SnoopPrecompile

struct CUDACompilerParams <: AbstractCompilerParams end

@precompile_all_calls begin
    target = PTXCompilerTarget(; cap=v"7.0")
    params = CUDACompilerParams()
    job = CompilerJob(target, FunctionSpec(identity, Tuple{Nothing}, true), params)
    GPUCompiler.code_native(devnull, job)
end
```

i.e. the same but with a dummy `CUDACompilerParams` definition. Trying to precompile GPUCompiler on 1.8 hangs, on 1.9 with a debug build it results in:

```
julia-debug: /home/tim/Julia/src/julia/src/dump.c:2159: jl_deserialize_value: Assertion `offs < backref_list.len' failed.
```

Maybe this is the same error? Again, here's an rr trace: https://s3.amazonaws.com/julialang-dumps/reports/2022-08-09T15-34-52-maleadt.tar.zst

### PR DESCRIPTION
**Pull request by maleadt**
If a code instance is encountered in a Julia object directly, as opposed to e.g. during serialization of a method instance, we'll already have populated the backref table at the start of `jl_serialize_value`. That means `jl_serialize_code_instance` can't just bail out, even though I presume that's still useful for nested calls. It would be cleaner to remove the check and call `jl_serialize_value` for nested code instances, but then the undocumented `internal` flag gets lost, so cc @Keno @timholy for thoughts on this.

Fixes https://github.com/JuliaLang/julia/issues/46296
Introduced by https://github.com/JuliaLang/julia/pull/39512, so we could backport this all the way back to 1.7 if we want.

### CODE REVIEW

File: src/dump.c [hunk 1]
```diff
@@ -678,7 +680,7 @@ static void jl_serialize_code_instance(jl_serializer_state *s, jl_code_instance_
     if (write_ret_type && codeinst->rettype_const &&
             jl_typeis(codeinst->rettype_const, jl_partial_opaque_type)) {
         if (skip_partial_opaque) {
-            jl_serialize_code_instance(s, codeinst->next, skip_partial_opaque, internal);
+            jl_serialize_code_instance(s, codeinst->next, skip_partial_opaque, internal, 0);
```
Comment (timholy) [inline src/dump.c:683]: Why not pass `force` here?

File: src/dump.c [hunk 2]
```diff
@@ -962,10 +964,10 @@ static void jl_serialize_value_(jl_serializer_state *s, jl_value_t *v, int as_li
         }
         jl_serialize_value(s, (jl_value_t*)backedges);
         jl_serialize_value(s, (jl_value_t*)NULL); //callbacks
-        jl_serialize_code_instance(s, mi->cache, 1, internal);
+        jl_serialize_code_instance(s, mi->cache, 1, internal, 0);
```
Comment (timholy) [inline src/dump.c:967]: What if a MethodInstance is a code-object? Would you want to serialize the CodeInstances that it points to? If so...we might have to keep track at a higher level of how we got here: if by traversing a module, then don't force, but if we're caching code, then force.

**Review by timholy — COMMENTED** [review]
This seems like a valid idea, but I'm wondering if we need to be more general about tracking how we got to `jl_serialize_code_instance`. I've not seen these before so I'm not sure whether MethodInstances could also be part of Julia objects, but presumably a package like
```julia
module MyPackage
const some_mis = [first(methods(sum)).specializations[1]]
end
```
would serve as a test case.

File: test/precompile.jl [hunk 3]
```diff
@@ -1290,3 +1290,43 @@ precompile_test_harness("__init__ cachepath") do load_path
...
+
+        sig = Tuple{typeof(identity), Nothing}
+        meth = which(sig)
+        ti, env = ccall(:jl_type_intersection_with_env, Any,
+                    (Any, Any), meth.sig, sig)
+        mi = ccall(:jl_specializations_get_linfo, Ref{Core.MethodInstance},
+                (Any, Any, Any, UInt), meth, ti, env, 1)
+
+        const interp = Interpreter()
+        Core.Compiler.typeinf_ext_toplevel(interp, mi)
```
Comment (vtjnash) [inline test/precompile.jl:1326]: this seems too fiddly of a test, using too many internal interfaces, than external consumers should be using

IIUC, the only thing needed here is to have a variable with `global some_code = Core.CodeInstance(mi, Any, nothing, nothing, zero(Int32), typemin(UInt64), typemax(UInt64), zero(UInt32), zero(UInt32), nothing, 0x00)`

and then a test that the variable still exists later

File: src/dump.c (hunk 1 above)
Comment (maleadt) [reply src/dump.c:683]: I'm just preserving how this function worked before. Presumably there was a reason that `jl_serialize_code_instance` didn't serialize CIs with backref entries on recursive calls to `jl_serialize_code_instance`, so I'm just preserving that behavior. Instead, I'm only forcing the CIs to be serialized when I know that the backref table initialization doesn't mean that the object has been serialized, i.e., from the `jl_is_code_instance` branch in `jl_serialize_value`.

File: src/dump.c (hunk 2 above)
Comment (maleadt) [reply src/dump.c:967]: Not setting `force=0` doesn't mean that the CI won't be serialized, it only means that it can't have a backref table entry. Since we're calling `jl_serialize_code_instance` here on a field that wasn't the direct input to `jl_serialize_value` (which populates the backref table), IIUC that means we will either serialize it for the first time, or the backref table will have an entry point to a successfully serialized CI.

And this does indeed seem to work as expected. With your example above, I can successfully precompile the array of MIs and inspect the CI in the cache:

```julia
module CodeInstancePrecompile

const some_mis = [first(methods(identity)).specializations[1]]

__init__() = @show some_mis[].cache

end
```
```
❯ JULIA_LOAD_PATH=. jl --startup-file=no -e 'using CodeInstancePrecompile'
(some_mis[]).cache = Core.CodeInstance(MethodInstance for identity(::Base.BottomRF{typeof(Base.add_sum)}), #undef, 0x0000000000000001, 0xffffffffffffffff, Base.BottomRF{typeof(Base.add_sum)}, Base.BottomRF{typeof(Base.add_sum)}(Base.add_sum), nothing, 0x00000155, 0x00000155, nothing, false, false, Ptr{Nothing} @0x00000001034d3a08, Ptr{Nothing} @0x0000000000000000, 0x00)
```

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
It is a confusing bit of code needing to track if we came via `jl_serialize_generic` already or not, but this PR seems right

**Comment by vtjnash** [comment]
```
ERROR: LoadError: MethodError: no method matching Core.CodeInstance(::Core.MethodInstance, ::Type{Any}, ::Nothing, ::Nothing, ::Int32, ::UInt64, ::UInt64, ::UInt32, ::UInt32, ::Nothing, ::UInt8)
Closest candidates are:
  Core.CodeInstance(::Core.MethodInstance, ::Any, ::Any, ::Any, ::Int32, ::UInt32, ::UInt32, ::UInt32, ::UInt32, ::Any, ::UInt8)
   @ Core boot.jl:423
  Core.CodeInstance(::Core.Compiler.InferenceResult, ::Any, ::Core.Compiler.WorldRange)
   @ Core compiler/typeinfer.jl:286
```
