### PR TITLE
Fix fastmath for vararg +, *, min, max methods

### LINKED ISSUE #54456: Should n-arg fastmath addition default to using to 2-arg fastmath addition for all types
Currently the n-arg fastmath addition only uses fastmath for `Float16, Float32` and `Float64`,
https://github.com/JuliaLang/julia/blob/931f6de4ca739b5d7a333e941e43ccdc0f5a4051/base/fastmath.jl#L171-L172
It otherwise falls back to non fastmath addition even when `add_fast(x, y)` is defined, like for `ComplexF64` and types in SIMD.jl.

As the 2-arg fastmath add, `add_fast(x, y)`, is defined for all types, should `add_fast(x::T, y::T, zs::T...)` be defined as above for all `T`.

The comment at the non fastmath n-arg addition definition seems to suggest that this would be expected and also should `add_fast(x::T, y::T, zs::T...)` switch to using `afoldl`?
https://github.com/JuliaLang/julia/blob/931f6de4ca739b5d7a333e941e43ccdc0f5a4051/base/operators.jl#L636-L637

Presumably, if we change the behaviour for addition, we want to change it for the other operators as well.

### PR DESCRIPTION
**Pull request by Zentrik**
Currently using the fastmath vararg +, *, min, max methods only actually sets fastmath if they are specifically overloaded even when the correct 2 argument methods have been defined.
As such, `ComplexF32, ComplexF64` do not currently set fastmath when using the vararg methods. This will also fix any other types, such as those in SIMD.jl, which don't overload the vararg methods.

E.g. 
```julia
x = ComplexF64(1)
f(x) = @fastmath x + x + x
```
now works correctly.

I see no reason why the vararg methods shouldn't default to using the fastmath 2 argument methods instead of the non fastmath ones, which is the current behaviour.

I also switched the implementation to use `afoldl` as that's what the non fastmath vararg methods use.

Fixes #54456 and https://github.com/eschnett/SIMD.jl/issues/108.

### CODE REVIEW

**Comment by KristofferC** [comment]
This seems clearly good to me. I think n-arg parsing has shown to be a failure but unfortunately it seems to broken to change it now (https://github.com/JuliaLang/julia/pull/48849).

File: base/fastmath.jl [hunk 1]
```diff
@@ -273,6 +266,31 @@ for op in (:+, :-, :*, :/, :(==), :!=, :<, :<=, :cmp, :rem, :min, :max, :minmax)
...
+        # note: these definitions must not cause a dispatch loop when +(a,b) is
+        # not defined, and must only try to call 2-argument definitions, so
+        # that defining +(a,b) is sufficient for full functionality.
+        ($op_fast)(a, b, c, xs...) = (@inline; afoldl($op_fast, ($op_fast)(($op_fast)(a,b),c), xs...))
+        # a further concern is that it's easy for a type like (Int,Int...)
+        # to match many definitions, so we need to keep the number of
+        # definitions down to avoid losing type information.
+        # type promotion
+        $op_fast(a::Number, b::Number, c::Number, xs::Number...) =
+        $op_fast(promote(x,y,c,xs...)...)
```
Comment (kimikage) [inline base/fastmath.jl:289]: @Zentrik, @KristofferC 

`a, b, c` != `x, y, c`

Comment (KristofferC) [reply base/fastmath.jl:289]: Nice catch, indicates some missing coverage.
