### PR TITLE
avoid timing race in async test

### LINKED ISSUE #46360: CI: Intermittent failure in misc.jl 27164 test
```


Error in testset misc:
--
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-fde3a68005/share/julia/test/misc.jl:249
  | Expression: x27164[] == 2
  | Evaluated: 1 == 2

```

https://buildkite.com/julialang/julia-master/builds/14752#0182a08a-0771-4394-890e-fe4e703e171a

### PR DESCRIPTION
**Pull request by vtjnash**
This is the test from #27164.

The test was checking whether sleep(1) (which is started first) or sleep(0.05) (which is nominally shorter) returned first. Switch the order so that the short sleep should always end first.

Fixes #46360

### CODE REVIEW

File: test/misc.jl [hunk 1]
```diff
@@ -241,8 +241,8 @@ do_something_async_27164() = @async(begin sleep(1); x27164[] = 2; end)
 
 let t = nothing
     @sync begin
-        t = do_something_async_27164()
         @async (sleep(0.05); x27164[] = 1)
+        t = do_something_async_27164()
```
Comment (Keno) [inline test/misc.jl:245]: Why use `sleep` here at all? Why not have a condition that is waited on in `do_something_async_27164` and notified after the `async`? Sure that'll cause a deadlock rather than a fail if the system has a bug, but I think as is, this could still fail if the system decides to take a long break after starting the `do_something_async_27164` task, no?

Comment (vtjnash) [reply test/misc.jl:246]: ah, that would be much smarter

**Review by Keno — APPROVED** [review]
LGTM, thanks.
