### PR TITLE
typeintersect: fix `UnionAll` unaliasing bug caused by innervars.

### LINKED ISSUE #53621: Assertion error in type intersection when testing NDTensors on 1.11
Put this in the REPL:

```julia 
using NDTensors
dev = NDTensors.Unwrap.cpu
elt = Float32
S = dev(tensor(Diag(randn(elt, 2)), (2, 2)))
V = dev(tensor(Dense(randn(elt, 12, 2)'), (3, 4, 2)))
S1 = contract(S, (2, -1), V, (3, 4, -1))
```

```
julia> S1 = contract(S, (2, -1), V, (3, 4, -1))
Assertion failed: (!has_innerdep || btemp->depth0 == vb->depth0), function finish_unionall, file subtype.c, line 2916.

[98613] signal 6: Abort trap: 6
in expression starting at REPL[6]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
pthread_kill at /usr/lib/system/libsystem_pthread.dylib (unknown line)
abort at /usr/lib/system/libsystem_c.dylib (unknown line)
__assert_rtn at /usr/lib/system/libsystem_c.dylib (unknown line)
finish_unionall at /Users/kristoffercarlsson/julia1.11/src/subtype.c:2916
intersect_unionall_ at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3125
intersect_unionall at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3173
intersect at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3822
intersect_unionall_ at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3082
intersect_unionall at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3173
intersect at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3822
intersect_all at /Users/kristoffercarlsson/julia1.11/src/subtype.c:4042
intersect_aside at /Users/kristoffercarlsson/julia1.11/src/subtype.c:2395
intersect at /Users/kristoffercarlsson/julia1.11/src/subtype.c:3766
intersect_all at /Users/kristoffercarlsson/julia1.11/src/subtype.c:4042
intersect_aside at /Users/kristoffercarlsson/julia1.11/src/subtype.c:2395
var_lt at /Users/kristoffercarlsson/julia1.11/src/subtype.c:728
local_forall_exists_subtype at /Users/kristoffercarlsson/julia1.11/src/subtype.c:1572
forall_exists_equal at /Users/kristoffercarlsson/julia1.11/src/subtype.c:1615
subtype at /Users/kristoffercarlsson/julia1.11/src/subtype.c:1445
subtype_unionall at /Users/kristoffercarlsson/julia1.11/src/subtype.c:907
subtype_unionall at /Users/kristoffercarlsson/julia1.11/src/subtype.c:907
...
```

### PR DESCRIPTION
**Pull request by N5N3**
The MWE in https://github.com/JuliaLang/julia/issues/53366#issuecomment-1974013439 has been broken since v1.7.
I haven't checked which change caused the regression but more thorough `UnionAll`-renaming does fix it.

The 2nd commit fixes the wrapping order of innervars, as newly inserted innervar might depend on existing ones.

close #53621

### CODE REVIEW

**Comment by N5N3** [comment]
@nanosoldier `runtests()`

**Comment by topolarity** [comment]
Thanks for the quick work, @N5N3!

I tried backporting this change to 1.10 and the patch applies (mostly) cleanly, but the test case is unfortunately still broken.

Would you be able to look into a backport and see what's going on?

**Comment by N5N3** [comment]
@topolarity which test case?
My local backport shows v1.10 is fine. (https://github.com/JuliaLang/julia/issues/53366#issuecomment-1974013439 works correctly) And there should be no confusing conflict.

**Comment by topolarity** [comment]
Ah, my mistake - I managed to drop one of the commits when I was back-porting.

Looking good here :+1:

File: src/subtype.c [hunk 1]
```diff
@@ -3033,10 +3034,40 @@ static jl_value_t *finish_unionall(jl_value_t *res JL_MAYBE_UNROOTED, jl_varbind
...
+                    jl_array_ptr_set(vb->innervars, count, (jl_value_t*)var);
+                count++;
+            }
+        }
+        if (count != len)
+            jl_array_del_end(vb->innervars, len - count);
+        if (res != jl_bottom_type) {
+            while (count > 1) {
+                int changed = 0;
+                for (size_t i = 0; i < count - 1; i++) {
```
Comment (vtjnash) [inline src/subtype.c:3053]: This could perhaps use a comment here:
```suggestion
                // Now need to re-sort the vb->innervars using the partial-ordering predicate `jl_has_typevar`
                // If this is slow, we could probably switch to a simple insertion sort, but for now we use a variant on bubble sort for partial-orders
                for (size_t i = 0; i < count - 1; i++) {
```

**Review by vtjnash — APPROVED** [review]

**Review by topolarity — APPROVED** [review]

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53553#issuecomment-1976164035) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/7442e18_vs_2b95956/report.html) is available.

**Comment by gbaraldi** [comment]
The crashes in pkgeval seem real.

**Comment by N5N3** [comment]
@nanosoldier `runtests(["NSGAII", "UnitfulRecipes", "OutlierDetectionTrees", "MLJTSVDInterface", "SelfOrganizingMaps", "ImplicitPlots", "MLJDecisionTreeInterface", "OutlierDetectionNeighbors", "GPLinearODEMaker", "MLJClusteringInterface", "TidierCats", "Pyehtim", "GraviPet", "MLJGLMInterface", "Ipaper", "ScientificTypes", "MLJScientificTypes", "PlantRayTracer", "EconPDEs", "CategoricalDistributions", "MLJNaiveBayesInterface", "SkyDomes", "GeoTables", "AnyMOD", "MLJXGBoostInterface", "StatsLearnModels", "MLJEnsembles", "MCMCChains", "StatisticalMeasures", "MLJTestInterface", "ReducedComplexityModeling", "OutlierDetection", "OrdinalMultinomialModels", "GenerativeTopographicMapping", "MLJTuning", "DiffEqFinancial", "PredefinedDynamicalSystems", "GeneralizedSDistributions", "SensitivityRankCondition", "SchwarzChristoffel", "MLJTestIntegration", "EMpht", "ManifoldDiffEq", "DifferentialEquations", "LowRankIntegrators", "HetaSimulator", "Petri", "Bactos", "ChargeTransport", "EditorsRepo", "TSML", "SemanticTrajectories", "MINDFulMakie", "StateSpacePartitions", "FSimPlots", "NeuroAnalysis"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53553#issuecomment-1980948680) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c06f961_vs_2b95956/report.html) is available.
