### PR TITLE
make codepoint(c) work for overlong chars

### LINKED ISSUE #54343: `isuppercase`/`islowercase` fail on invalid characters
MWE:

```julia
julia> isuppercase('\xf0\x8e\x80\x80')
ERROR: Base.InvalidCharError{Char}('\xf0\x8e\x80\x80')
Stacktrace:
 [1] throw_invalid_char(c::Char)
   @ Base ./char.jl:86
 [2] UInt32
   @ ./char.jl:133 [inlined]
 [3] isuppercase(c::Char)
   @ Base.Unicode ./strings/unicode.jl:403
 [4] top-level scope
   @ REPL[12]:1

julia> Base.ismalformed('\xf0\x8e\x80\x80')
false
```

Either this is a requirement, or we can safely return `false` here, as is done for malformed characters. Does utf8proc handle invalid/malformed chars on its own? [The docs](https://juliastrings.github.io/utf8proc/doc/utf8proc_8h.html#a47d7028b0593b165fb30561db9e3a57c) aren't clear about this.

### PR DESCRIPTION
**Pull request by stevengj**
As discussed in #54393, `codepoint(c)` should succeed for overlong encodings, and whenever `ismalformed(c)` returns `false`.   This should be backwards compatible since it simply removes an error, and should be strictly faster than before since it merely removes a call to `Base.is_overlong_enc`.

Also, `Base.ismalformed` and `Base.isoverlong` are declared `public` (but not yet exported) and are included in the manual, since they are referenced in the docstring of `codepoint` etcetera.   I also made `Base.show_invalid` 
a `public` and documented function, since it is referenced from the `ismalformed` docs and is required by new implementations of `AbstractChar` types that support malformed data.

Fixes #54343, closes #54393.

### CODE REVIEW

**Comment by nhz2** [comment]
These changes seems to be at odds with other docs, because now `codepoint(a) == codepoint(b)` no longer implies `a == b`
https://github.com/JuliaLang/julia/blob/197295c84aab217bffde01a4339f1d0e8e95fb98/base/char.jl#L4-L10

Also, the information that a `Char` is overlong will be silently destroyed by conversion to `UInt32` instead of throwing an error.
https://github.com/JuliaLang/julia/blob/197295c84aab217bffde01a4339f1d0e8e95fb98/base/char.jl#L40-L44

**Comment by stevengj** [comment]
> A character represents a Unicode code point

The basic problem is that this is an oversimplification. The `Char` type represents the encoding, not just the codepoint, and can represent byte sequences that don’t encode Unicode code points.

**Review by StefanKarpinski — APPROVED** [review]
Looks great to me

**Comment by stevengj** [comment]
Unrelated CI failure, updating and re-running CI.

File: base/char.jl [hunk 1]
```diff
@@ -112,24 +125,35 @@ end
...
+For example, well-formed characters can include invalid Unicode
+codepoints like `'\\U110000'`, unpaired surrogates such as `'\\ud800'`,
+and can also include overlong encodings ([`Base.isoverlong`](@ref)).
+Malformed data, in contrast, cannot be decoded to a codepoint
+(`codepoint` will throw an exception).
+
+See also [`Base.show_invalid`](@ref).
 """
 ismalformed(c::AbstractChar) = false
+public ismalformed
```
Comment (LilithHafner) [inline base/char.jl:145]: This belongs in `base/public.jl`

**Comment by LilithHafner** [comment]
The docstring of `codepoint` currently reads "...throw an exception if `c` does not represent a valid character...". That should be changes to "...represent a malformed character..." and link to the definition of invalid but not malformed.

**Comment by StefanKarpinski** [comment]
Triage likes but would also like for "malformed" to be documented somewhere and to adjust the docstring of codepoint to refer to malformed rather than invalid. @LilithHafner feels that it would be good to block the publicness of `ismalformed` on documentation of what it means, so maybe that's a good ordering:

1. Add docstring for `ismalformed` defining what it does
2. Make `ismalformed` public
3. Update `codepoint` docstring to refer to malformed versus invalid

An additional comment regarding equality and comparison:

- Valid strings are compared as lexicographically ordered sequences of code points
- A valid string and an invalid string must never be equal
- Comparison of invalid strings is implementation-defined and may error but should be an ordering:
  - Reflexive: `s == s` for all strings
  - Antisymmetric: `s <= t` and `t <= s` implies `s == t`
  - Transitive: `s <= t` and `t <= u` implies `s <= u`
  - Total: either `s <= t` or `t <= s` or both are an error

This allows each string type to define a total ordering on valid and invalid strings in a way that's efficient and consistent within the type, but comparisons of invalid strings across types can simply error since there's no sensible way to implement that and forcing it to be consistent would force valid comparisons to be done inefficiently.

**Comment by stevengj** [comment]
1. `ismalformed` already has a docstring in this PR
2. `ismalformed` is already public in this PR
3. the `codepoint` docs already refer to malformed rather than valid in this PR

File: base/char.jl (hunk 1 above)
Comment (stevengj) [reply base/char.jl]: Okay, I've moved the `public` declarations to `base/public.jl`

File: base/char.jl [hunk 2]
```diff
@@ -76,9 +80,18 @@ end
 
 Return the Unicode codepoint (an unsigned integer) corresponding
 to the character `c` (or throw an exception if `c` does not represent
-a valid character). For `Char`, this is a `UInt32` value, but
+a well-formed character). For `Char`, this is a `UInt32` value, but
```
Comment (LilithHafner) [inline base/char.jl:83]: Would this be equivalent?
```suggestion
to the character `c` (or throw an exception if `c` represents
a malformed character). For `Char`, this is a `UInt32` value, bu
```
If so, I think it is more clear because `malformed` more clearly refers to `ismalformed`.

File: base/char.jl [hunk 3]
```diff
@@ -112,22 +125,31 @@ end
 #           not to support malformed or overlong encodings.
 
 """
-    ismalformed(c::AbstractChar) -> Bool
+    Base.ismalformed(c::AbstractChar) -> Bool
 
 Return `true` if `c` represents malformed (non-Unicode) data according to the
```
Comment (LilithHafner) [inline base/char.jl:130]: I would interpret "non-Unicode" to mean "not valid according to the Unicode spec" which IIUC is what `Base.isvalid` checks.

File: base/char.jl [hunk 4]
```diff
@@ -112,22 +125,31 @@ end
...
 
-See also [`show_invalid`](@ref).
+Any *non*-malformed `c` can be mapped to an integer codepoint
+by [`codepoint(c)`](@ref); this includes codepoints that are
+not valid Unicode characters ([`isvalid(c)`](@ref) is `false`).
+For example, well-formed characters can include invalid Unicode
+codepoints like `'\\U110000'`, unpaired surrogates such as `'\\ud800'`,
+and can also include overlong encodings ([`Base.isoverlong`](@ref)).
+Malformed data, in contrast, cannot be decoded to a codepoint
+(`codepoint` will throw an exception).
```
Comment (LilithHafner) [inline base/char.jl:140]: IIUC Unicode does not define a notion of malformedness separate from validity. Is this the only place that the distinction between malformed and wellformed invalid unicode is defined?

File: base/char.jl (hunk 3 above)
Comment (stevengj) [reply base/char.jl:130]: Maybe "non-codepoint"

Comment (stevengj) [reply base/char.jl:130]:
```suggestion
Return `true` if `c` represents malformed (non-codepoint) data according to the
```

File: base/char.jl (hunk 4 above)
Comment (stevengj) [reply base/char.jl:140]: malformed-ness is a property of the encoding.

However, the UTF-8 encoding (that `String` and `Char` use) is [specified within the Unicode standard](https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-2/#G11165).

File: base/char.jl (hunk 2 above)
Comment (stevengj) [reply base/char.jl]: Done.

**Comment by stevengj** [comment]
Windows build failure looks unrelated: `ERROR: Unable to open agent private key path 'C:\secrets/agent.key'!  Make sure your agent has this file deployed within it!`

**Review by LilithHafner — APPROVED** [review]
I'd like a more complete/specific/accessible definition of malformed vs invalid, or a link to the specific part of the unicode standard that defines it; but I don't think that is blocking given the level of docs already in this PR.

**Comment by inkydragon** [comment]
> malformed vs invalid

I didn't find a definition for either word, but did find a definition for their antonyms.
[Glossary of Unicode Terms](https://www.unicode.org/glossary/)

> [D84 _Ill-formed_][D84]: A Unicode code unit sequence that purports to be in a Unicode encoding form is called _ill-formed_ if and only if it does _not_ follow the specification of that [Unicode encoding form][D79].
>
> - Any code unit sequence that would correspond to a code point outside the defined range of Unicode scalar values would, for example, be ill-formed.
> - UTF-8 has some strong constraints on the possible byte ranges for leading and trailing bytes. A violation of those constraints would produce a code unit sequence that could not be mapped to a Unicode scalar value, resulting in an ill-formed code unit sequence.

xref:
- [D85 Well-formed][D85]
- [D92 UTF-8 encoding form][D92]

> [D89 In a Unicode encoding form][D89]: ...
>
> - A Unicode string consisting of a well-formed UTF-8 code unit sequence is said to be in _UTF-8_. Such a Unicode string is referred to as a _valid UTF-8 string_, or a _UTF-8 string_ for short.

[D79]: https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G25583
[D84]: https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G32733
[D85]: https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G32849
[D89]: https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G32849
[D92]: https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G34920

**Comment by LilithHafner** [comment]
Assuming UTF-8,

Unicode specifies that any code unit sequence not listed in [this table](https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G27506) is ill-formed and not well-formed.

IIUC, our definition of malformed is different from Unicode's definition of ill-formed. For example, overlong characters are not `Base.ismalformed`  but are ill-formed according to Unicode.

**Comment by StefanKarpinski** [comment]
There's no official definition of "malformed". However, IMO this is a missing concept from the Unicode spec. The spec is generally a bit vague and self-contradictory on handling invalid data. There's a difference between a character that is sensibly encoded but not allowed—e.g. because it is a surrogate code point or too high or an overlong encoding—and data that simply doesn't follow the expected structure of an encoding. This distinction only applies to UTF-8 because any sequence of code units in UTF-16 is well-formed—the only encoding error you can have is unpaired surrogates, which is well-formed but invalid. (The only way you can have truly malformed UTF-16 is if you have an odd number of bytes so your last code unit is incomplete.) Why does this distinction matter? There are a few reasons:

1. If you're trying to decode an invalid string and you encounter a well-formed but invalid character, you should treat it as a single invalid character, not multiple invalid code units; if you encounter malformed data, you should treat it as multiple invalid code units in the way that the Unicode spec recommends for producing replacement characters.

2. It's coherent to ask some kinds of questions about well-formed but invalid characters. For example, you can ask what code point a well-formed character encodes. It may be an illegal one (surrogate, too high), or it may be an illegal encoding of a valid code point (overlong), but there's a single sensible answer to the question and this answer is sometimes useful. For example, if the data is WTF-8 or Modified UTF-8 or CESU-8, these are all slight variations on UTF-8 that are mostly valid but deviate from the standard in minor ways. If the data is malformed, on the other hand, then there simply is no coherent answer to "what code point does this encode".

**Comment by stevengj** [comment]
(Fixed merge conflicts.)

File: NEWS.md [hunk 5]
```diff
@@ -30,12 +30,8 @@ New library features
 Standard library changes
 ------------------------
 
-* `gcdx(0, 0)` now returns `(0, 0, 0)` instead of `(0, 1, 0)` ([#40989]).
```
[the remark this answers is not in the document]
Comment (stevengj) [reply NEWS.md]: I don't see that in the diff.  Are you looking at a commit rather than the overall "Files Changed" diff?

**Comment by stevengj** [comment]
Unrelated CI failure: 
```
fatal: unable to access 'https://github.com/JuliaCI/external-buildkite-buildkite-plugin/': Error in the HTTP2 framing layer
$ git clone -v -- https://github.com/JuliaCI/extern
```

**Comment by oscardssmith** [comment]
github actions are broken this afternoon.

**Comment by stevengj** [comment]
Green CI, can this be merged now?

**Comment by LilithHafner** [comment]
I don't have objections.
