### PR TITLE
Fix `@fastmath x^2` inlining regression for `Float32` and `Float16`

### LINKED ISSUE #60639: power_by_squaring is not inlined for `x^2`
I am using Julia 1.12.4. It seems that `@fastmath` breaks efficient integer powers for Float32.

Simple code:
```Julia
f(x) = @fastmath x^2
```

This is good (Float64):
```
julia> @code_llvm debuginfo=:none f(1.0)
; Function Signature: f(Float64)
define double @julia_f_3688(double %"x::Float64") #0 {
top:
  %0 = fmul double %"x::Float64", %"x::Float64"
  ret double %0
}
```

This is bad (Float32):
```
julia> @code_llvm debuginfo=:none f(1.0f0)
; Function Signature: f(Float32)
define float @julia_f_3715(float %"x::Float32") #0 {
top:
  %0 = fpext float %"x::Float32" to double
  %1 = call double @"j_#power_by_squaring#401_3717"(double %0, i64 signext 2)
  %2 = fptrunc double %1 to float
  ret float %2
}
```

Not only is `power_by_squaring` not inlined, it even converts to and from `Float64`!

See also https://github.com/JuliaLang/julia/issues/59804. I assume this fixed things for Float64 but not for Float32.

### PR DESCRIPTION
**Pull request by Yashagarwal9798**
## Summary

This PR fixes the performance regression where `@fastmath x^2` for `Float32` was not being inlined to efficient LLVM code, unlike `Float64`.

## Problem

As reported in #60639, `@fastmath x^2` for `Float32` was falling back to `power_by_squaring` instead of using the LLVM `powi` intrinsic. This resulted in:
- Unnecessary function calls instead of inline multiplication
- Potential type promotion to `Float64`
- Suboptimal generated code compared to `Float64`

Before this fix, `@code_llvm @fastmath Float32(1.5)^2` would show calls to `power_by_squaring`, while `Float64` correctly used the `llvm.powi` intrinsic.

## Solution

Added the missing `pow_fast` methods for `Float32` and `Float16`:

- `pow_fast(::Float32, ::Int32)` - uses `llvm.powi.f32.i32` intrinsic directly
- `pow_fast(::Float32, ::Integer)` - wrapper that converts to `Int32` when safe, matching the `Float64` pattern
- `pow_fast(::Float16, ::Integer)` - converts to `Float32`, computes, and converts back

This mirrors the existing implementation for `Float64` which already used `llvm.powi.f64.i32`.

## Testing

Added a regression test that verifies `@fastmath x^2` generates inline `fmul` instructions (not `power_by_squaring` calls) for `Float16`, `Float32`, and `Float64`.

Fixes #60639

### CODE REVIEW

File: base/fastmath.jl [hunk 1]
```diff
@@ -301,8 +301,13 @@ exp10_fast(x::Union{Float32,Float64}) = Base.Math.exp10_fast(x)
     z = y % Int32
     z == y ? pow_fast(x, z) : x^y
 end
-pow_fast(x::Float32, y::Integer) = x^y
+@inline function pow_fast(x::Float32, y::Integer)
+    z = y % Int32
+    z == y ? pow_fast(x, z) : x^y
+end
```
Comment (oscardssmith) [inline base/fastmath.jl]: combine this with the method above

Comment (oscardssmith) [inline base/fastmath.jl]:
```suggestion
@inline function pow_fast(x::Union{Float32, Float64}, y::Integer)
    z = y % Int32
    z == y ? pow_fast(x, z) : x^y
end
```

File: test/fastmath.jl [hunk 2]
```diff
@@ -303,6 +303,17 @@ end
     @test @fastmath (1 + 1 / n) ^ 4503599627370496 ≈ ℯ
 end
 
+# Test that x^2 is inlined to fmul for all float types (issue #60639)
+@testset "pow_fast inlining for literal powers" begin
```
Comment (oscardssmith) [inline test/fastmath.jl:307]: also test that `@fastmath x^y` produces approximately correct  results for Float32/Float16 for both exponents that fit and that don't fit within Int32.

**Comment by adienes** [comment]
@Yashagarwal9798 please be aware that all uses of AI must be disclosed

File: base/fastmath.jl (hunk 1 above)
Comment (Yashagarwal9798) [reply base/fastmath.jl]: Done, combined Float32 and Float64 into a single method using `Union{Float32,Float64}`.

Comment (Yashagarwal9798) [reply base/fastmath.jl]: Applied, thanks for the suggestion!

File: test/fastmath.jl (hunk 2 above)
Comment (Yashagarwal9798) [reply test/fastmath.jl:307]: Added correctness tests that verify `@fastmath x^y` produces correct results for Float16/Float32 with:
- Exponents that fit in Int32 (2, 10, -3)
- Exponents that don't fit in Int32 (2^40)

**Review by oscardssmith — APPROVED** [review]

File: base/fastmath.jl [hunk 3]
```diff
@@ -297,12 +297,13 @@ exp10_fast(x::Union{Float32,Float64}) = Base.Math.exp10_fast(x)
...
 
-@inline function pow_fast(x::Float64, y::Integer)
+@inline function pow_fast(x::Union{Float32,Float64}, y::Integer)
     z = y % Int32
     z == y ? pow_fast(x, z) : x^y
 end
-pow_fast(x::Float32, y::Integer) = x^y
 pow_fast(x::Float64, y::Int32) = ccall("llvm.powi.f64.i32", llvmcall, Float64, (Float64, Int32), x, y)
+pow_fast(x::Float32, y::Int32) = ccall("llvm.powi.f32.i32", llvmcall, Float32, (Float32, Int32), x, y)
+@inline pow_fast(x::Float16, y::Integer) = Float16(pow_fast(Float32(x), y))
```
Comment (giordano) [inline base/fastmath.jl]: `llvm.powi.f16.i32` exists
```julia-repl
julia> pow_fast(x::Float32, y::Int32) = ccall("llvm.powi.f32.i32", llvmcall, Float32, (Float32, Int32), x, y)
pow_fast (generic function with 1 method)

julia> @inline pow_fast(x::Float16, y::Integer) = Float16(pow_fast(Float32(x), y))
pow_fast (generic function with 2 methods)

julia> powi(x::Float16, y::Int32) = ccall("llvm.powi.f16.i32", llvmcall, Float16, (Float16, Int32), x, y)
powi (generic function with 1 method)

julia> powi(Float16(1.1), Int32(2))
Float16(1.209)

julia> pow_fast(Float16(1.1), Int32(2))
Float16(1.209)
```

Comment (giordano) [reply base/fastmath.jl]: Native code, at least on aarch64 with `fp16` extension, is the same (doing an intermediate conversion to single precision), but that's the business of the backend, we shouldn't force intermediate conversions unnecessarily in case the backend is able to do operations natively.

Comment (oscardssmith) [reply base/fastmath.jl]: `llvm.powi.f16.i32` produces inncorrect results on x86.
```
julia> ccall("llvm.powi", llvmcall, Float16, (Float16, Int32), Float16(1), Int32(5))
Float16(0.0)
```

Comment (giordano) [reply base/fastmath.jl]:
```
julia> ccall("llvm.powi", llvmcall, Float16, (Float16, Int32), Float16(1), Int32(5))
Float16(1.0)

julia> versioninfo()
Julia Version 1.14.0-DEV.1530
Commit 915a69fee00 (2026-01-09 10:17 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 192 × AMD Ryzen Threadripper PRO 7995WX 96-Cores
  WORD_SIZE: 64
  LLVM: libLLVM-20.1.8 (ORCJIT, znver4)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 192 virtual cores)
```

Comment (oscardssmith) [reply base/fastmath.jl]: oh cool. It was fixed between LLVM 18 and 20 apparently. In that case we should use it.

Comment (Yashagarwal9798) [reply base/fastmath.jl]: Updated to use the native `llvm.powi.f16.i32` intrinsic for Float16 as well.

File: base/fastmath.jl [hunk 4]
```diff
@@ -297,12 +297,13 @@ exp10_fast(x::Union{Float32,Float64}) = Base.Math.exp10_fast(x)
...
 
-@inline function pow_fast(x::Float64, y::Integer)
+@inline function pow_fast(x::Union{Float16,Float32,Float64}, y::Integer)
     z = y % Int32
     z == y ? pow_fast(x, z) : x^y
 end
-pow_fast(x::Float32, y::Integer) = x^y
 pow_fast(x::Float64, y::Int32) = ccall("llvm.powi.f64.i32", llvmcall, Float64, (Float64, Int32), x, y)
+pow_fast(x::Float32, y::Int32) = ccall("llvm.powi.f32.i32", llvmcall, Float32, (Float32, Int32), x, y)
+pow_fast(x::Float16, y::Int32) = ccall("llvm.powi.f16.i32", llvmcall, Float16, (Float16, Int32), x, y)
```
Comment (oscardssmith) [inline base/fastmath.jl]:
```suggestion
pow_fast(x::T, y::Int32) where T <: IEEEFloat = ccall("llvm.powi", llvmcall, T, (T, Int32), x, y)
```

Comment (Yashagarwal9798) [reply base/fastmath.jl]: Applied the suggested change, using the generic `IEEEFloat` type with the overloaded `llvm.powi` intrinsic.

**Comment by DilumAluthge** [comment]
Build failure looks real?

```
error during bootstrap:
LoadError("sysimg.jl", 3, LoadError("Base.jl", 222, LoadError("fastmath.jl", 300, UndefVarError(:IEEEFloat, 0x0000000000005e69, Base.FastMath))))
```

File: base/fastmath.jl [hunk 5]
```diff
@@ -297,12 +297,11 @@ exp10_fast(x::Union{Float32,Float64}) = Base.Math.exp10_fast(x)
 
 # builtins
 
-@inline function pow_fast(x::Float64, y::Integer)
+@inline function pow_fast(x::T, y::Integer) where T <: IEEEFloat
```
Comment (oscardssmith) [inline base/fastmath.jl]:
```suggestion
@inline function pow_fast(x::T, y::Integer) where T <: Base.IEEEFloat
```

File: base/fastmath.jl [hunk 6]
```diff
@@ -297,12 +297,11 @@ exp10_fast(x::Union{Float32,Float64}) = Base.Math.exp10_fast(x)
...
     z = y % Int32
     z == y ? pow_fast(x, z) : x^y
 end
-pow_fast(x::Float32, y::Integer) = x^y
-pow_fast(x::Float64, y::Int32) = ccall("llvm.powi.f64.i32", llvmcall, Float64, (Float64, Int32), x, y)
+pow_fast(x::T, y::Int32) where T <: IEEEFloat = ccall("llvm.powi", llvmcall, T, (T, Int32), x, y)
```
Comment (oscardssmith) [inline base/fastmath.jl]:
```suggestion
pow_fast(x::T, y::Int32) where T <: Base.IEEEFloat = ccall("llvm.powi", llvmcall, T, (T, Int32), x, y)
```

File: base/fastmath.jl [hunk 7]
```diff
@@ -297,12 +297,11 @@ exp10_fast(x::Union{Float32,Float64}) = Base.Math.exp10_fast(x)
...
 # builtins
 
-@inline function pow_fast(x::Float64, y::Integer)
+@inline function pow_fast(x::T, y::Integer) where T <: Base.IEEEFloat
     z = y % Int32
     z == y ? pow_fast(x, z) : x^y
 end
-pow_fast(x::Float32, y::Integer) = x^y
-pow_fast(x::Float64, y::Int32) = ccall("llvm.powi.f64.i32", llvmcall, Float64, (Float64, Int32), x, y)
+pow_fast(x::T, y::Int32) where T <: Base.IEEEFloat = ccall("llvm.powi", llvmcall, T, (T, Int32), x, y)
```
Comment (oscardssmith) [inline base/fastmath.jl]:
```suggestion
pow_fast(x::Float16, y::Int32) = ccall("llvm.powi", llvmcall, Float16, (Float16, Int32), x, y)
pow_fast(x::Float32, y::Int32) = ccall("llvm.powi", llvmcall, Float32, (Float32, Int32), x, y)
pow_fast(x::Float64, y::Int32) = ccall("llvm.powi", llvmcall, Float64, (Float64, Int32), x, y)
```

**Comment by DilumAluthge** [comment]
@oscardssmith CI is all green now.

**Comment by oscardssmith** [comment]
@Yashagarwal9798 thanks for the PR!

**Comment by Yashagarwal9798** [comment]
Thanks! really glad I could help improve the project.

**Comment by eschnett** [comment]
This is a candidate for backporting. Although this concerns only an optimization, generating inefficient code for `x^2` is a disaster performance-wise.

**Comment by oscardssmith** [comment]
Agreed. If we backport, we need to be careful not to back-port the Float16 version of this to 1.12 (LLVM only recently doesn't produce garbage on x86 with this intrinsic). 1.13 should receive the back-port unmodified though. I'll put up the 1.12 PR.

**Comment by vchuravy** [comment]
@oscardssmith did you open a PR to backport this to 1.12?

**Comment by oscardssmith** [comment]
I did, but I linked to https://github.com/JuliaLang/julia/pull/60640/changes so it didn't tag.
