### PR TITLE
Fix and test Float16 Rational comparison

### LINKED ISSUE #59622: Intransitive equality comparing rationals to Float16.
```julia-repl
julia> Float16(6.0e-8) == big(1//16777216) == 1//16777216
true

julia> Float16(6.0e-8) == 1//16777216
false

julia> versioninfo()
Julia Version 1.13.0-DEV.1096
Commit 8a384ab93e4 (2025-09-07 17:14 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (aarch64-linux-gnu)
  CPU: 8 × unknown
  WORD_SIZE: 64
  LLVM: libLLVM-20.1.8 (ORCJIT, apple-m2)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 8 virtual cores)
```

### PR DESCRIPTION
**Pull request by LilithHafner**
Found and fix recommended by Eric Demer.

Previously, we had this non-transitivity:

```julia-repl
julia> Float16(6.0e-8) == big(1//16777216) == 1//16777216
true

julia> Float16(6.0e-8) == 1//16777216
false
```

From Eric,

>  This is presumably not the preferred way to inform you of such issues, but
 
> like last time, the other ways I found have Terms that I am not willing to agree to
and
> this time, I imagine it is in fact a bug, rather than just a foot-gun
 
> .
 
 
 
> Multiplication of  Float16 s  by the built-in BitInteger types hits the generic
> ::Number fallback, which just promotes the inputs and then multiplies the results.
> These pairs of inputs promote to Float16, so for Int32,UInt32 and larger,
> multiplying this way can give Inf16 even when [[the Float16 input is neither
> NaN nor infinite] and [the exact product has absolute value at most 1]].
 
> While the decision for the above specifically might be
> "That's just what one gets for doing arithmetic with Float16."
> ,  a current consequence of this is that
> == between  Float16 s  and  Rationals for the wide-enough built-in BitInteger types
> gives wrong output, and as a result,  isequal  is not transitive:
 
> https://paste.ee/p/LfxRlI7F has a paste of a REPL session demonstrating this.
 
 
> Ideally, one would define arithmetic operations between
> built-in BitFloats and built-in BitIntegers so that when there
> are no nans and no infs, the output is == to the result of
> convert both inputs to Rational{BigInt}, multiply those Rationals, and then round.
>  
> The much-easier-to-implement patch, on the other hand,
> would be just defining  ==(x::Float16,q::Rational) = ==(Float32(x),q)
> ,  since the built-in BitInteger types are not large-enough
> to cause the comparison issue with Float32:
 
> If q is not a power of 2, then the count_ones part will be false,
> else for the built-in BitInteger types, q.den is at most UInt128(2)^127.
> This is strictly less than  floatmax(Float32) .
> When q.den is a power of 2 and less than floatmax(Float32),
> q.den can be represented exactly and the only way for
> multiplication by it to be inexact is exceeding the exponent range.
> In such cases, the exact product is at least big"2"^128, so the Float product is Inf32,
> and q is at most typemax(UInt128), since q.den is non-zero so q is finite.
> typemax(UInt128) < big"2"^128 < Inf32  ,    so for Float32,
> the  x*q.den == q.num  part still works even in these cases.
>  
 
 
>  (Those who are curious about _why_ I didn't agree to the Terms for the
> other ways, can view my explanation at  https://paste.ee/p/Y325uIJL .) 

Fixes #59622

### CODE REVIEW

**Comment by oscardssmith** [comment]
I think this isn't a Float16 issue. There is nothing different about the Float16 method than any other abstractFloat so I don't think this is correct.

File: base/rational.jl [hunk 1]
```diff
@@ -441,6 +441,7 @@ fma(x::Rational, y::Rational, z::Rational) = x*y+z
 <=(x::Rational, y::Integer ) = x.num <= widemul(x.den,y)
 <=(x::Integer , y::Rational) = widemul(x,y.den) <= y.num
 
+==(x::Float16, q::Rational) = widen(x) == q
 function ==(x::AbstractFloat, q::Rational)
     if isfinite(x)
         (count_ones(q.den) == 1) & (x*q.den == q.num)
```
Comment (oscardssmith) [inline base/rational.jl:447]:
```suggestion
function ==(x::AbstractFloat, q::Rational)
    if isfinite(x)
        (count_ones(q.den) == 1) & (ldexp(x, top_set_bit(q.den-1)) == q.num)
```

This should work for all precision (at the cost of a little speed)

Comment (oscardssmith) [reply base/rational.jl:447]: specifically on 11th gen intel, I see a ~1ns slowdown from 6.9 to 8ns for Float32 inputs with this change (and no change for Float16)

Comment (topolarity) [reply base/rational.jl]: A bit unrelated, but this made me realize that we're missing a `tol = 0` fast-path for `Base.rationalize`

**Comment by LilithHafner** [comment]
@oscardssmith, can we merge this? I'd like to close #59622.

**Comment by oscardssmith** [comment]
yes.

**Comment by giordano** [comment]
@oscardssmith I believe this was already asked a few days ago, can you please squash-merge the PRs?

**Comment by oscardssmith** [comment]
oops sorry, my github merge defaults switched for no apparent reason.

**Comment by KristofferC** [comment]
> for no apparent reason.

The default is what you last did, so if your last action was a merge it will be on merge. You just have to read the button.
