### PR TITLE
[Makefile] Fix codesign of libjulia when installing it on macOS

### LINKED ISSUE #44502: Invalid code signature on libjulia.1.9.dylib
I'm still trying to get Julia master to compile… this time I'm using the binary builder, to avoid trouble, but a Julia compiled and installed with:

```
make VERBOSE=1 prefix=/opt/julia-1.9.0-DEV-811e534c PYTHON=python3 MACOSX_VERSION_MIN=12 install
```

will crash when it is launched:

```
$ /opt/julia/bin/julia -v  
zsh: killed     /opt/julia/bin/julia -v
```

because 

```
$ codesign -vvv /opt/julia/lib/libjulia.1.9.dylib 
/opt/julia/lib/libjulia.1.9.dylib: invalid signature (code or signature have been modified)
In architecture: arm64
```

The library in the build directory has correct signature:

```
$ codesign -vvv usr/lib/libjulia.1.9.dylib
usr/lib/libjulia.1.9.dylib: valid on disk
usr/lib/libjulia.1.9.dylib: satisfies its Designated Requirement
```

but it gets modified during install:

```
# Next, overwrite relative path to libjulia-internal in our loader if $(LOADER_BUILD_DEP_LIBS) != $(LOADER_INSTALL_DEP_LIBS)
/private/tmp/julia/usr/tools/stringreplace $(strings -t x - /opt/julia-1.9.0-DEV-811e534c/lib/libjulia.1.9.dylib | grep $(python3 /private/tmp/julia/contrib/relative_path.py /private/tmp/julia/usr/lib /private/tmp/julia/usr/lib/libgcc_s.2.dylib):$(python3 /private/tmp/julia/contrib/relative_path.py /private/tmp/julia/usr/lib /private/tmp/julia/usr/lib/libopenlibm.dylib):@$(python3 /private/tmp/julia/contrib/relative_path.py /private/tmp/julia/usr/lib /private/tmp/julia/usr/lib/libjulia-internal.1.dylib):@$(python3 /private/tmp/julia/contrib/relative_path.py /private/tmp/julia/usr/lib /private/tmp/julia/usr/lib/libjulia-codegen.1.dylib):$ | awk '{print $1;}') $(python3 /private/tmp/julia/contrib/relative_path.py /opt/julia-1.9.0-DEV-811e534c/lib /opt/julia-1.9.0-DEV-811e534c/lib/julia/libgcc_s.2.dylib):$(python3 /private/tmp/julia/contrib/relative_path.py /opt/julia-1.9.0-DEV-811e534c/lib /opt/julia-1.9.0-DEV-811e534c/lib/julia/libopenlibm.dylib):@$(python3 /private/tmp/julia/contrib/relative_path.py /opt/julia-1.9.0-DEV-811e534c/lib /opt/julia-1.9.0-DEV-811e534c/lib/julia/libjulia-internal.1.dylib):@$(python3 /private/tmp/julia/contrib/relative_path.py /opt/julia-1.9.0-DEV-811e534c/lib /opt/julia-1.9.0-DEV-811e534c/lib/julia/libjulia-codegen.1.dylib): 255 "/opt/julia-1.9.0-DEV-811e534c/lib/libjulia.1.9.dylib"
```

which invalidates the signature.

### PR DESCRIPTION
**Pull request by giordano**
Probably it isn't the cleanest solution possible, but it does the job for me :slightly_smiling_face: 

Fix #44502

```console
% prefix=$(mktemp -d)
% make install prefix=$prefix
# ...
% $prefix/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.154 (2022-03-08)
 _/ |\__'_|_|_|\__'_|  |  mg/macos-codesign-install/31c7573f8f (fork: 1 commits, 0 days)
|__/                   |

julia>
```

### CODE REVIEW

**Comment by staticfloat** [comment]
We don't want to use `ldid`, we want to use `codesign`.

We have the invocation [here](https://github.com/JuliaLang/julia/blob/88062ea7cb35bd5769e4f7895c9db9d64acc9535/Makefile#L432-L441), we basically want to do this after `make install` as well.  We should probably make this a shell script that gets invoked by the makefiles, rather than a bunch of makefile rules.

File: contrib/codesign.sh [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+        usage
+    fi
+else
+    usage
+fi
+
+echo "Codesigning with identity ${MACOS_CODESIGN_IDENTITY}"
+for f in ${MACHO_FILES}; do
+    echo "Codesigning ${f}..."
+    codesign -s "${MACOS_CODESIGN_IDENTITY}" --option=runtime ${ENTITLEMENTS} -vvv --timestamp --deep --force "${f}"
```
Comment (giordano) [inline contrib/codesign.sh:37]: `make binary-dist` worked fine in CI, yay!  But I wish posix shells supported arrays, leaving `${ENTITLEMENTS}` unquoted makes me uncomfortable :disappointed:

**Review by staticfloat — APPROVED** [review]

**Comment by fxcoudert** [comment]
This was only included for 1.9, and it still fails for released 1.8.0: https://github.com/JuliaLang/julia/issues/44502#issuecomment-1218230227

Could the patch be backported?

**Comment by DilumAluthge** [comment]
Do we also need to backport this to 1.6?

**Comment by fxcoudert** [comment]
> Do we also need to backport this to 1.6?

I don't think so. Julia 1.6 did not support macOS ARM (aka Apple Silicon), and on macOS Intel the binaries produced by the system compiler are not signed by default (unlike ARM, where they systematically have an ad hoc signature). So on Intel, the binary is still valid after `stringreplace` is run, because it's unsigned.
