### PR TITLE
Load Pkg if not already to reinstate missing package add prompt

### LINKED ISSUE #52090: Missing package install prompt not showing before Pkg is loaded
Regression since Pkg was moved out of the sysimage.

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/52090

Similar to https://github.com/JuliaLang/julia/pull/51921

### CODE REVIEW

**Comment by vtjnash** [comment]
This should not load until after the user selects it as the action. Hard nack from me on loading Pkg whenever the user hits enter.

**Comment by IanButterworth** [comment]
That won't work as Pkg is used to identify if the package exists in a registry.

**Comment by IanButterworth** [comment]
Though, I had it in the wrong place. Now Pkg is loaded once it's known that missing packages have been requested.

**Comment by vtjnash** [comment]
Yes, that seems better. I think this is not the correct way to load packages though, since it will be getting incorrect info from the manifest. It may be enough to add this to the project.toml deps for REPL?

**Comment by IanButterworth** [comment]
Pkg depends on REPL, so I don't think that's possible?

**Comment by IanButterworth** [comment]
What about temporarily activating Pkg's environment?

**Comment by IanButterworth** [comment]
.. if not in the manifest already

**Comment by vtjnash** [comment]
Yeah true. It seems like it needs some sort of PkgExt added manifest to keep it from being confusing

File: stdlib/REPL/src/REPL.jl [hunk 1]
```diff
@@ -1523,6 +1522,15 @@ function run_frontend(repl::StreamREPL, backend::REPLBackendRef)
     nothing
 end
 
+function load_pkg()
+    pkgid = Base.PkgId(Base.UUID("44cfe95a-1eb2-52ea-b672-e2afdf69b78f"), "Pkg")
```
Comment (Keno) [inline stdlib/REPL/src/REPL.jl:1526]:
```suggestion
    Base.generating_output(true) && return nothing
    pkgid = Base.PkgId(Base.UUID("44cfe95a-1eb2-52ea-b672-e2afdf69b78f"), "Pkg")
```
to avoid the spurious dependency issue Jameson mentioned. Other than that, I think this is good to go.

File: stdlib/REPL/src/REPL.jl [hunk 2]
```diff
@@ -1586,6 +1585,16 @@ function run_frontend(repl::StreamREPL, backend::REPLBackendRef)
     nothing
 end
 
+function load_pkg()
+    Base.generating_output(true) && return nothing
+    pkgid = Base.PkgId(Base.UUID("44cfe95a-1eb2-52ea-b672-e2afdf69b78f"), "Pkg")
+    if Base.locate_package(pkgid) !== nothing # Only try load Pkg if we can find it
+        Pkg = Base.require(pkgid)
```
Comment (KristofferC) [inline stdlib/REPL/src/REPL.jl:1592]: This should use the new `require_stdlib` functionality.

**Review by KristofferC — APPROVED** [review]
