### PR TITLE
fix intersection returning Union{} for diagonal vars with different Type{X} arguments

### LINKED ISSUE #59490: Miscompile when dispatching on type stored in struct
```julia
@inline _indexed_ndims() = 0
@inline _indexed_ndims(::Type{T}, rest...) where {T <: Integer} = _indexed_ndims(rest...)
@inline _indexed_ndims(::Type{T}, rest...) where {eT <: Integer, T <: AbstractVector{eT}} = 1 + _indexed_ndims(rest...)
@inline _indexed_ndims(::Type{Colon}, rest...) = 1 + _indexed_ndims(rest...)

function promote_symtype(::typeof(getindex), ::Type{T}, Ts::Vararg{S, N}) where {N, eT, T <: AbstractArray{eT, N}, S <: Type{<:Any}}
    nD = _indexed_ndims(Ts...)
    nD == 0 ? eT : Array{eT, nD}
end

function promote_symtype(::typeof(getindex), ::Type{T}, Ts...) where {T}
    throw(ArgumentError(""))
end
struct Foo
    x::Union{DataType, UnionAll, Union}
end
foo = Foo(Matrix{Number})
bench(x::Foo) = promote_symtype(getindex, x.x, typeof(1:2), Int)
bench(foo)
```

Results in:

<details>

<summary> On Julia 1.12.0-rc1+0.aarch64.apple.darwin14 </summary>

```
[10606] signal 4: Illegal instruction: 4
in expression starting at REPL[13]:1
bench at ./REPL[12]:1
unknown function (ip: 0x15b840097) at (unknown file)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/./julia.h:2369 [inlined]
do_call at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/interpreter.c:124
eval_stmt_value at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/interpreter.c:193
eval_body at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/interpreter.c:688
jl_interpret_toplevel_thunk at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/interpreter.c:897
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/toplevel.c:1038
__repl_entry_eval_expanded_with_loc at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:302
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/./julia.h:2369 [inlined]
jl_f_invokelatest at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/builtins.c:854
toplevel_eval_with_hooks at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:309
toplevel_eval_with_hooks at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:313
toplevel_eval_with_hooks at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:313
toplevel_eval_with_hooks at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:313
toplevel_eval_with_hooks at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:306 [inlined]
eval_user_input at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:331
repl_backend_loop at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:453
#start_repl_backend#41 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:428
start_repl_backend at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:425 [inlined]
#run_repl#50 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:654
run_repl at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/usr/share/julia/stdlib/v1.12/REPL/src/REPL.jl:640
unknown function (ip: 0x15b36c68f) at (unknown file)
run_std_repl at ./client.jl:482
jfptr_run_std_repl_60333.1 at /Users/aayush/.julia/juliaup/julia-1.12.0-beta4+0.aarch64.apple.darwin14/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/./julia.h:2369 [inlined]
jl_f_invokelatest at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/builtins.c:854
run_main_repl at ./client.jl:503
repl_main at ./client.jl:590 [inlined]
_start at ./client.jl:565
jfptr__start_59543.1 at /Users/aayush/.julia/juliaup/julia-1.12.0-beta4+0.aarch64.apple.darwin14/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/./julia.h:2369 [inlined]
true_main at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/jlapi.c:959
jl_repl_entrypoint at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-12/src/jlapi.c:1126
Allocations: 11414757 (Pool: 11412619; Big: 2138); GC: 14
```

</details>

<details>

<summary> On Julia 1.11.6 </summary>

```
[10325] signal 4 (1): Illegal instruction: 4
in expression starting at REPL[9]:1
getindex at /Users/aayush/Julia/SciML/SymbolicUtils.jl/src/types.jl:2135
unknown function (ip: 0x30241c1df)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/./julia.h:2157 [inlined]
do_call at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:126
eval_stmt_value at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:174
eval_body at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:666
jl_interpret_toplevel_thunk at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:824
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:943
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:886
eval_body at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:628
eval_body at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:539
jl_interpret_toplevel_thunk at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/interpreter.c:824
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:943
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:886
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:886
ijl_toplevel_eval at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:952 [inlined]
ijl_toplevel_eval_in at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/toplevel.c:994
eval at ./boot.jl:430 [inlined]
eval_user_input at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:261
repl_backend_loop at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:368
#start_repl_backend#59 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:343
start_repl_backend at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:340
#run_repl#76 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:500
run_repl at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:486
jfptr_run_repl_10324.1 at /Users/aayush/.julia/juliaup/julia-1.11.6+0.aarch64.apple.darwin14/share/julia/compiled/v1.11/REPL/u0gqU_cXxqm.dylib (unknown line)
#1150 at ./client.jl:446
jfptr_YY.1150_14980.1 at /Users/aayush/.julia/juliaup/julia-1.11.6+0.aarch64.apple.darwin14/share/julia/compiled/v1.11/REPL/u0gqU_cXxqm.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/./julia.h:2157 [inlined]
jl_f__call_latest at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/builtins.c:875
#invokelatest#2 at ./essentials.jl:1055 [inlined]
invokelatest at ./essentials.jl:1052 [inlined]
run_main_repl at ./client.jl:430
repl_main at ./client.jl:567 [inlined]
_start at ./client.jl:541
jfptr__start_73912.1 at /Users/aayush/.julia/juliaup/julia-1.11.6+0.aarch64.apple.darwin14/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/./julia.h:2157 [inlined]
true_main at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/jlapi.c:900
jl_repl_entrypoint at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-11/src/jlapi.c:1059
Allocations: 76529336 (Pool: 76526315; Big: 3021); GC: 58
zsh: trace trap  julia --check-bounds=yes --project=@. -t 1
```

</details>

Changing the first `promote_symtype` method to this:

```julia
function promote_symtype(::typeof(getindex), ::Type{T}, Ts::Vararg{Any, N}) where {N, eT, T <: AbstractArray{eT, N}}
    nD = _indexed_ndims(Ts...)
    nD == 0 ? eT : Array{eT, nD}
end
```

Avoids the error.

### PR DESCRIPTION
**Pull request by adienes**
because `Tuple{Type{X}, Type{Y}}` can match `Tuple{T, T} where {T<:Type{<:Any}}`, as the diagonal rule also allows a concrete _supertype_ of the arguments, which `DataType` satisfies

[🤖] solution'd and written by Opus 4.6

fixes https://github.com/JuliaLang/julia/issues/59490

### CODE REVIEW

**Comment by N5N3** [comment]
The direction of re-intersection seems promising.
However, the current changes might not yet fully address the underlying issue. Consider the following example:
```julia
typeintersect(
    Tuple{Any, Union{Type{Vector},Type{Int}}, Type{Int8}}, 
    Tuple{Int, S, S} where {S}
)
```
After the 1st intersection , `S`'ub becomes `Union{Type{Vector}, Type{Int}}`, which has no concrete supertype thus the  re-intersection would be skipped.

One possible approach is similar to the trick used in #20508: in the first pass, we could expand ~`Type`s into their “kinds”, and compute the `S`'ub
(here we would get S <: typeintersect(Union{DataType,UnionAll}, DataType) = DataType,~ `S`'ub to its kind (here we would get `S <: Union{Type{Vector}, Type{Int}}` -> `S <: Union{UnionAll, DataType}` -> `S <: Type{Int8}` -> `S <: DataType`) and then rely on a subsequent pass to eliminate the unwanted Type{Vector} part.

Also, we might need 3 rounds of intersection here: The 1st to prove the diagonal rule and set `constraintkind = 1`; the 2nd to compute `S`'ub, and 3rd to produce the final result.

**Comment by adienes** [comment]
thank you for the extra test case. I attempted to apply your approach, let me know if I misinterpreted any part!

File: src/subtype.c [hunk 1]
```diff
@@ -3497,6 +3521,34 @@ static jl_value_t *intersect_unionall(jl_value_t *t, jl_unionall_t *u, jl_stenv_
...
+    else if (res == jl_bottom_type && vb.constraintkind == 1 &&
+             vb.occurs_cov > 1) {
+        // vb.constraintkind == 1 implies occurs_inv == 0, together with occurs_cov > 1
+        // means vb is diagonal
+        // res == jl_bottom_type may be a false negative if vb.ub contains different
+        // Type{X} variables, which may have a concrete common super type (queried via w)
+        jl_value_t *w = widen_Type_union_pointwise(vb.ub);
+        if (w != vb.ub) {
+            vb.ub = w;
+            if (jl_subtype(vb.ub, u->var->ub)) {
```
Comment (vtjnash) [inline src/subtype.c]: I'm suspicious of a call to `jl_subtype` happening from this deep inside the subtyping algorithm, ignoring all the current status of the algorithm

Comment (adienes) [reply src/subtype.c]: looking around the other uses of `jl_subtype`, I see many are gated behind some kind of `if (!jl_has_free_typevars(t))` ; would that suffice here?

Comment (vtjnash) [reply src/subtype.c]: Only if you're using it as an optimization and not for correctness (otherwise you have to use one of the internal subtyping calls)

File: src/subtype.c [hunk 2]
```diff
@@ -886,6 +887,27 @@ static jl_value_t *widen_Type(jl_value_t *t JL_PROPAGATES_ROOT) JL_NOTSAFEPOINT
     return t;
 }
 
+// Map Type{X} to kind type (DataType, UnionAll, Union, TypeofBottom) over union
```
Comment (N5N3) [inline src/subtype.c:898]: Perhaps we can fuse this with the `widen_Type` by adding a  `concrete_only` like flag?
```c
static jl_value_t *widen_Type(jl_value_t *t JL_PROPAGATES_ROOT, int concrete_only) JL_NOTSAFEPOINT
{
    if (jl_is_type_type(t) && !jl_is_typevar(jl_tparam0(t)))
        return jl_typeof(jl_tparam0(t));
    if (jl_is_uniontype(t)) {
        jl_value_t *a = widen_Type(((jl_uniontype_t*)t)->a, concrete_only);
        jl_value_t *b = widen_Type(((jl_uniontype_t*)t)->b, concrete_only);
        if (concrete_only) {
            if (a == b) return a;
        }
        else {
            if (a != ((jl_uniontype_t*)t)->a || b != ((jl_uniontype_t*)t)->b) {
                JL_GC_PUSH2(&a, &b);
                jl_value_t *ans = simple_join(a, b);
                JL_GC_POP();
                return ans;
            }
        }
    }
    // add the missing unionall handling (`Tuple{Union{Type{Vector{T}} where {T},Type{Int}},Type{Int8}} <: Tuple{S, S} where {S}` returns false on master)
    if (jl_is_unionall(t)) {
        jl_unionall_t *u = (jl_unionall_t*)t;
        jl_value_t *body = widen_Type(u->body, concrete_only);
        if (body != u->body) {
            if (concrete_only || !jl_has_typevar(body, u->var)) {
                return body;
            }
            else {
                JL_GC_PUSH1(&body);
                jl_value_t *ans = (jl_value_t*)jl_type_unionall(u->var, body);
                JL_GC_POP();
                return ans;
            }
        }
    }
    return t;
}
```

File: src/subtype.c [hunk 3]
```diff
@@ -3497,6 +3521,37 @@ static jl_value_t *intersect_unionall(jl_value_t *t, jl_unionall_t *u, jl_stenv_
             res = intersect_unionall_(t, u, e, R, param, &vb);
         }
     }
+    else if (res == jl_bottom_type && vb.constraintkind == 1 &&
```
Comment (N5N3) [inline src/subtype.c]: With the change below (always try Type widening for constraintkind == 1), we can trust the intersection result (no false `Union{}`), and only trigger the final re-intersection if `widen_to_kind == 1` && `occurs_cov > 1` && `vb.ub is a kind`
```c
    if (res != jl_bottom_type && vb.constraintkind == 1 && vb.widen_to_kind && vb.occurs_cov > 1 && is_leaf_bound(vb.ub)) {
        restore_env(e, &se, 1);
        vb.lb = vb.var->lb;
        vb.occurs_cov = vb.occurs_inv = 0;
        res = intersect_unionall_(t, u, e, R, param, &vb);
    }
```

File: src/subtype.c [hunk 4]
```diff
@@ -2841,6 +2863,8 @@ static jl_value_t *intersect_var(jl_tvar_t *b, jl_value_t *a, jl_stenv_t *e, int
         if (e->triangular && check_unsat_bound(ub, b, e))
             return jl_bottom_type;
         set_bound(&bb->ub, ub, b, e);
+        if (bb->constraintkind == 1 && bb->widen_to_kind)
+            set_bound(&bb->ub, widen_Type_union_pointwise(bb->ub), b, e);
```
Comment (N5N3) [inline src/subtype.c]: Perhaps we can always try to widening `bb->ub` if `bb->constraintkind == 1` and let the flag to record if `ub` really got widened, i.e.
```c
    if (e->triangular && param == 1) {
        if (check_unsat_bound(ub, b, e))
            return jl_bottom_type;
        set_bound(&bb->ub, ub, b, e);
        return (jl_value_t*)b;
    }
    else if (bb->constraintkind == 1) {
        // We'd better widen `Type`s in ub to their kind to avoid false `Union{}`  
        jl_value_t *ub2 = widen_Type(ub, 0);
        if (ub2 == ub) {
            // There's no Type in ub, just set the bound and return b.
            set_bound(&bb->ub, ub, b, e);
            return (jl_value_t*)b;
        }
        else {
            // The ub get widened, set the flag if the new ub is not a simple kind,
            // which means it might change after further intersection. (thus need re-intersection)
            int concrete = is_leaf_bound(ub2);
            bb->widen_to_kind |= !concrete; // TODO: the flag needs save/restore?
            set_bound(&bb->ub, ub2, b, e);
            // if ub2 become a kind, return `ub` directly.
            // otherwise, return `b` (TODO: perhaps `ub` is better?)
            return concrete ? ub : (jl_value_t*)b;
        }
    }
```

**Review by N5N3 — COMMENTED** [review]
Some suggestions on code fusing and re-intersection logic.

File: src/subtype.c (hunk 1 above)
Comment (adienes) [reply src/subtype.c]: replaced with `try_subtype_in_env` and added test case

```
@test typeintersect(Tuple{Ref{DataType}, Type{Int64}, Type{Float64}, Union{Int64,String}},
                    (Tuple{Ref{T}, S, S, Int} where {S<:T}) where T) === Tuple{Ref{DataType}, Type{Int64}, Type{Float64}, Int64}
```

File: src/subtype.c (hunk 4 above)
Comment (adienes) [reply src/subtype.c]: will this miss cases where we have a diagonal variable with an upper bound? e.g. intersecting `Tuple{Type{Int64}, Type{String}}` with `Tuple{T, T} where T<:Type{<:Number}` we'd widen both positions to `DataType`. so I think we'd have to guard it with `jl_subtype(ub2, ub)`. happy to do so but just wanted to check this was intentional

File: src/subtype.c (hunk 2 above)
Comment (adienes) [reply src/subtype.c:898]: good catch on the unionall handling, appears to also fix this bug on master
```
julia> Tuple{Union{Type{Vector{T}} where T, Type{Int64}}, Type{Int8}} <: Tuple{S, S} where S
false
```


re: consolidation, if this is only a stylistic concern, then I might advocate for the current method split in the spirit of [anti-if pattern 1](https://code.joejag.com/2016/anti-if-the-missing-patterns.html). maybe I could use a more descriptive name instead?

File: src/subtype.c (hunk 4 above)
Comment (N5N3) [reply src/subtype.c]: Good catch! Didn't realize this pattern.
We need to recheck validity of Type widening if `ub2 != ub`.

File: src/subtype.c (hunk 2 above)
Comment (N5N3) [reply src/subtype.c:898]: > if this is only a stylistic concern,

Yes, this is primarily a stylistic suggestion. I'm fine with keeping them as two separate methods.

> use a more descriptive name instead?

To me, `widen_Type_union_pointwise` is more like `widen_Type` while the current `widen_Type` is something like `widen_Type_if_concrete`, not sure if that's enough.

Comment (adienes) [reply src/subtype.c:898]: how about `widen_Type_if_concrete` and `widen_Type_to_union` ?

Comment (N5N3) [reply src/subtype.c:898]: LGTM

File: src/subtype.c (hunk 4 above)
Comment (N5N3) [reply src/subtype.c]: Well, perhaps we'd better do this check within `widen_Type_to_union`.
The widening might be partially valid if the diagonal var has a `Union` ub, e.g.
```julia
typeintersect(Tuple{Union{Type{Val},Type{Int}}, Type{Vector}}, Tuple{T, T} where T<:Union{UnionAll,Type{<:Number}})
```

**Comment by adienes** [comment]
I've attempted to apply the suggestion to widen already in the intersection to avoid the false `Union{}` in the first place. Claude was also very helpful in stress testing with some adversarial intersections that I've added as test cases (but necessitated extra complexity to handle)

File: src/subtype.c [hunk 5]
```diff
@@ -3533,35 +3578,30 @@ static jl_value_t *intersect_unionall(jl_value_t *t, jl_unionall_t *u, jl_stenv_
...
-                vb.lb = u->var->lb;
-                vb.concrete = 0;
-                vb.widen_to_kind = 1;
-                vb.occurs_cov = vb.occurs_inv = 0;
+    if (res != jl_bottom_type && vb.constraintkind == 1 && vb.widened_to_kind) {
+        // a `Type` was widened to a non-concrete kind union during intersection
+        if (vb.occurs_cov > 1) {
+            // diagonal: reintersect with the widened leaf bound to recover precision
+            // or return Union{} if the widened bound is not a leaf
+            if (is_leaf_bound(vb.ub)) {
```
Comment (N5N3) [inline src/subtype.c:3574]: In fact, non-leaf `lb` (rather than `ub`) violates the diagonal rule. Looks like the remaining `@test_broken` stems from this.

File: src/subtype.c [hunk 6]
```diff
@@ -874,49 +874,70 @@ static int is_leaf_typevar(jl_tvar_t *v) JL_NOTSAFEPOINT
...
+// sets `*filtered` to the union of original (non-widened) surviving members
+static jl_value_t *widen_Type_to_union(jl_value_t *t, jl_value_t *bound, jl_stenv_t *e, jl_value_t **filtered)
 {
-    if (jl_is_type_type(t) && !jl_is_typevar(jl_tparam0(t)))
-        return jl_typeof(jl_tparam0(t));
+    if (jl_is_type_type(t) && !jl_is_typevar(jl_tparam0(t))) {
+        jl_value_t *w = jl_typeof(jl_tparam0(t));
+        if (!try_subtype_in_env(w, bound, e)) {
+            *filtered = jl_bottom_type;
+            return jl_bottom_type;
```
Comment (N5N3) [inline src/subtype.c]: I'm not sure return a `Union{}` is a good idea here, this might remove part of `ub` and make the result too narrow, e.g.
```julia
typeintersect(Tuple{Union{Type{Val},Type{Int8}},Union{Type{Val},Type{Int}}}, NTuple{2,<:Union{Type{<:Val},DataType}})
```
why not just return `t`?

BTW, there seems no need to maintain `filtered` if `widen_Type_to_union` only performs widening (and does no filtering). IIUC, it was added only for the branch in L2916, we could return ub there if ub2 is concrete.

Comment (adienes) [reply src/subtype.c]: thanks, this is simpler. replaced all the filtering logic with a `-1` value for `widened_to_kind` denoting if narrowing a non-concrete result from `widen_Type_to_union` across diagonal positions failed to produce a leaf bound

to summarize my current understanding:

* when we encounter a `Type` in some ub, widen it to its kind (taking the map if the ub is a union), respecting declared upper bounds
* if positions share a concrete kind, use that as the bound and return original types
* if the positions do not all widen to the same concrete kind, we may need reintersection
* if the variables are diagonal, we try to narrow the union of kinds across positions
* if that works, reintersect against the narrowed result
* if that's not possible, give up and reintersect without widening `Type`s
* otherwise variables turned out to be nondiagonal, just reintersect with constraintkind = 0

writing this here to make sure that both: 1. what I want to do is correct and 2. the implementation matches my intention 🙂

File: src/subtype.c (hunk 5 above)
Comment (adienes) [reply src/subtype.c:3574]: I do not yet understand the lb connection / this comment

File: src/subtype.c (hunk 6 above)
Comment (N5N3) [reply src/subtype.c]: > if the variables are diagonal, we try to narrow the union of kinds across positions

As mentioned above, diagonal variables are allowed to hold non-concrete `ub`. A simple example without `Type`:
```julia
julia> typeintersect(Tuple{Union{Int,Int8},Union{Int,Int8}},NTuple{2})
Tuple{T, T} where T<:Union{Int64, Int8}
```
So it is ok to re-intersect with Type widening for diagonal variables, though the result might be over-estimated，e.g.
```julia
A = Tuple{Union{Type{Vector}, Type{Int64}}, Union{Type{Matrix}, Type{Float64}}} # the `@test_broken` in L2829
B = (Tuple{S, S} where S)
typeintersect(A, B) # should return `Tuple{S, S} where S<:Union{DataType, UnionAll}` if we re-intersect with Type widening
```
And the newly added test in L2818 seems too narrow for the same reason. (it should return `NTuple{2, <:Union{Val, DataType}}`)

Comment (adienes) [reply src/subtype.c]: > So it is ok to re-intersect with Type widening for diagonal variables

if we accept the overestimate it doesn't even need reintersection right? this should be the same as the first pass afaict

when observing a non-leaf widened bound, maybe we could manually distribute over the union? so first reintersect with `Type{Val}` to get `Tuple{Type{Val}, Type{Val}}`, then reintersect with `DataType` for `Tuple{Type{Int8}, Type{Int64}}`, and take the union of the two for the precise intersection

Comment (adienes) [reply src/subtype.c]: I guess `switch_union_tuple` breaks the result. this comment seems relevant:  https://github.com/JuliaLang/julia/blob/2ba9b37b3f8074106e21b621fe58a9518ae07cd8/src/subtype.c#L4609-L4611

so the original overestimate is actually better anyway

Comment (N5N3) [reply src/subtype.c]: > it doesn't even need reintersection
Exactly! I guess we could omit even more re-intersection (e.g. return `ub` instead of `TypeVar` eagerly for the 1st round of intersection, and skipping re-intersection for non-diagonal case), but that could be future optimization.

**Review by N5N3 — APPROVED** [review]

**Comment by adienes** [comment]
thank you so much for the detailed review !
