### PR TITLE
Fix `unaliascopy(::SubArray)` with `indices` of `Array{<:CartesianIndex}`

### LINKED ISSUE #47644: Missing `convert` from `Int` to `CartesianIndex{1}`
```julia
julia> convert(CartesianIndex{1}, 1)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type CartesianIndex{1}

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:64
  CartesianIndex{N}(::Integer...) where N
   @ Base multidimensional.jl:72
  CartesianIndex{N}(::Integer...) where N
   @ Base multidimensional.jl:75

Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> convert(Int, CartesianIndex{1}(1)) # the other way works, so there's a correspondence
1

julia> CartesianIndex{1}(1) # a constructor is defined
CartesianIndex(1,)

julia> versioninfo()
Julia Version 1.10.0-DEV.12
Commit ee0f3fc334a (2022-11-16 00:27 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = :/usr/lib/x86_64-linux-gnu/gtk-3.0/modules
  JULIA_EDITOR = subl
```
Perhaps the conversion from an `Int` to a `CartesianIndex{1}` should work as well.

Real-world case: https://discourse.julialang.org/t/using-views-with-cartesianindices-is-this-a-bug/19823/3

### PR DESCRIPTION
**Pull request by N5N3**
This PR fixes the bug caused by the trimming trick.
`Base.index_lengths` is not a proper tool to calculate the trimmed shape as `indices` might consume more than 1 dim.
And we can avoid the unneeded "`repeat`" when we meet `Array{CartesianIndex{0}}`

Test added.
Close #47644.

### CODE REVIEW

File: base/subarray.jl [hunk 1]
```diff
@@ -107,15 +107,32 @@ unaliascopy(A::SubArray) = typeof(A)(unaliascopy(A.parent), map(unaliascopy, A.i
...
+_trimmed_shape1(::Real) = (1,)
+_trimmed_shape1(i::AbstractArray{<:Integer}) = (length(i),)
+_trimmed_shape1(i::AbstractArray{<:AbstractCartesianIndex{0}}) = ()
+_trimmed_shape1(i::AbstractArray{<:AbstractCartesianIndex{N}}) where {N} = (length(i), ntuple(Returns(1), Val(N - 1))...)
 # Transform indices to be "dense"
 _trimmedindex(i::Real) = oftype(i, 1)
-_trimmedindex(i::AbstractUnitRange) = oftype(i, oneto(length(i)))
-_trimmedindex(i::AbstractArray) = oftype(i, reshape(eachindex(IndexLinear(), i), axes(i)))
-
+_trimmedindex(i::AbstractUnitRange{<:Integer}) = oftype(i, oneto(length(i)))
```
Comment (N5N3) [inline base/subarray.jl:128]: It should be noted that "_trimmedindex" must preserve the input "axes".
This line is not valid for "Base.IdentityUnitRange" etc.
Perhaps we'd better restrict the signature to e.g.  `I<:Tuple{Vararg{Union{Real,UnitRange,OneTo,StepRange,Array}}}`

**Review by vtjnash — APPROVED** [review]

File: base/subarray.jl (hunk 1 above)
Comment (N5N3) [reply base/subarray.jl]: Ok, at least we can do tail trimming in this case.
