### PR TITLE
lufact overhaul

### LINKED ISSUE #308: sparse lufact fallback not correctly defined
In trying to troubleshoot JuliaLang/LinearAlgebra.jl#301, I discovered that the following code seems to result in an infinite loop in `SparseArrays.normestinv`, an unexported function for estimating the norm of the inverse of the input sparse matrix.

``` jl
julia> srand(5); Ac = sprandn(20,20,.5) + im* sprandn(20, 20,.5);

julia> Af = convert(SparseMatrixCSC{Complex64}, Ac);

julia> SparseArrays.normestinv(Af, 1) #hangs
```

Probably related: 

``` jl
julia> SparseArrays.normestinv(sparse(ones(Complex64, 1, 1)), 1)
ERROR: StackOverflowError:
 in float at operators.jl:381
 in call at essentials.jl:56 (repeats 509 times)
```

### LINKED ISSUE #15099: sparse lufact fallback not correctly defined
In trying to troubleshoot #14778, I discovered that the following code seems to result in an infinite loop in `SparseArrays.normestinv`, an unexported function for estimating the norm of the inverse of the input sparse matrix.

```jl
julia> srand(5); Ac = sprandn(20,20,.5) + im* sprandn(20, 20,.5);

julia> Af = convert(SparseMatrixCSC{Complex64}, Ac);

julia> SparseArrays.normestinv(Af, 1) #hangs
```

Probably related: 

```jl
julia> SparseArrays.normestinv(sparse(ones(Complex64, 1, 1)), 1)
ERROR: StackOverflowError:
 in float at operators.jl:381
 in call at essentials.jl:56 (repeats 509 times)
```

### PR DESCRIPTION
**Pull request by jiahao**
- Correct fallbacks for sparse `lufact`. Closes JuliaLang/LinearAlgebra.jl#308
- Also overhauls docstrings for `lufact`, separating out dense and sparse methods.
- Document that sparse `lufact` creates a copy of input if not of eltype `Complex128` or `Float64`.
- Create two separate entries for dense and sparse `lufact` in stdlib docs. It's now clear that sparse `lufact` does not support pivoting. 
- Add simple tests for `getindex(::UmfpackLU)`.

Includes minor changes in `sparse/umfpack.jl`:
- `Union{Int32}` -> `Int32`
- Use default value for `show_umf_ctrl` and `show_umf_info`
- `size` now throws `ArgumentError` instead of `ErrorException`

### CODE REVIEW

File: base/sparse/umfpack.jl [hunk 1]
```diff
@@ -113,12 +148,13 @@ function lufact{Tv<:UMFVTypes,Ti<:UMFITypes}(S::SparseMatrixCSC{Tv,Ti})
     finalizer(res, umfpack_free_symbolic)
     umfpack_numeric!(res)
 end
-lufact(A::SparseMatrixCSC) = lufact(float(A))
+lufact{T<:Real}(A::SparseMatrixCSC{T}) = lufact(map(Float64, A))
```
Comment (andreasnoack) [inline base/sparse/umfpack.jl]: Use `convert` here
```jl
julia> A = sparse(rand(1:1000, 2000), rand(1:500, 2000), rand(-10:10, 2000));

julia> @time map(Float64, A);
  0.042705 seconds (500.01 k allocations: 7.663 MB, 9.65% gc time)

julia> @time convert(SparseMatrixCSC{Float64}, A);
  0.000035 seconds (25 allocations: 16.281 KB)
```
We might also want to throw on big types because we usually don't want to reduce precision silently.

**Comment by andreasnoack** [comment]
Apart from that, the changes are great.

File: base/sparse/umfpack.jl (hunk 1 above)
Comment (jiahao) [inline base/sparse/umfpack.jl]: Our current deprecation warning says to use `map(Float64, A)`. Is that worth changing?

Comment (andreasnoack) [inline base/sparse/umfpack.jl]: There doesn't seem to be a big difference for dense arrays but for sparse matrices it doesn't seem like a good advice. However, I think it will soon be time to remove the deprecation warning. As I remember it, `float64` was deprecated in 0.4.0 so in 0.5.0 it should be an error if we follow the normal practice.

**Comment by jiahao** [comment]
I've tightened the fallbacks to work only for Base floats of less than double precision, and used convert instead

**Comment by jiahao** [comment]
Getting the fallbacks correct without throwing ambiguity warnings has turned out to be more delicate than I had expected. Originally I simply deleted the `lufact(A::SparseMatrixCSC) = lufact(float(A))` method, but this fallback is still needed for, say, integer eltypes.

This latest version builds and tests correctly on my local machine.

File: base/sparse/umfpack.jl [hunk 2]
```diff
@@ -113,12 +148,17 @@ function lufact{Tv<:UMFVTypes,Ti<:UMFITypes}(S::SparseMatrixCSC{Tv,Ti})
     finalizer(res, umfpack_free_symbolic)
     umfpack_numeric!(res)
 end
+lufact{Tv<:Union{Float16,Float32}, Ti<:UMFITypes}(A::SparseMatrixCSC{Tv,Ti}) = lufact(convert(SparseMatrixCSC{Float64,Ti}, A))
+lufact{Tv<:Union{Complex32,Complex64}, Ti<:UMFITypes}(A::SparseMatrixCSC{Tv,Ti}) = lufact(convert(SparseMatrixCSC{Complex128,Ti}, A))
+lufact{T<:AbstractFloat}(A::Union{SparseMatrixCSC{T},SparseMatrixCSC{Complex{T}}}) = throw(ArgumentError("matrix type $(typeof(A)) not supported. Try lufact(convert(SparseMatrixCSC{Float64/Complex128,Int}, A)) for sparse floating point LU using UMFPACK or lufact(full(A)) for generic dense LU."))
```
Comment (tkelman) [inline base/sparse/umfpack.jl]: break some of these long lines?

**Comment by jiahao** [comment]
Mysterious test failure seems unrelated?

https://travis-ci.org/JuliaLang/julia/jobs/110034014#L1602-L1619

```
Exception running test subarray :
On worker 4:
LoadError: Mismatch
 in test_cartesian at /tmp/julia/share/julia/test/subarray.jl:152
```

**Comment by tkelman** [comment]
same error as #14991 but with the right error message now
