### PR TITLE
REPL: fix #40247, improve `getfield` type completion

### LINKED ISSUE #40247: Tab completion can't always determine field names
Tab completion fails to infer field names:
```
julia> Pkg.dependencies()[Pkg.project().dependencies["Revise"]].┌ Error: Error in the keymap                                                                                                   
│   exception =                                                                                                                                                                                
│    BoundsError: attempt to access 1-element Array{Any,1} at index [2]
```

But it has no trouble when broken down in two steps:
```
julia> x = Pkg.dependencies()[Pkg.project().dependencies["Revise"]];

julia> x.
dependencies         git_source            is_pinned             is_tracking_registry  name                  tree_hash
git_revision         is_direct_dep         is_tracking_path      is_tracking_repo      source                version
```

<details>
<summary>Stack trace</summary>
```
julia> Pkg.dependencies()[Pkg.project().dependencies["Revise"]].┌ Error: Error in the keymap                                                                                                                                                                                                                                  
│   exception =                                                                                                                                                                                     
│    BoundsError: attempt to access 1-element Array{Any,1} at index [2]                                                                                                                                                                                                                                                     
│    Stacktrace:                                                                                                                                                                                        
│     [1] getindex at ./array.jl:809 [inlined]                                                                                                                                                                                                                                                                                
│     [2] get_value_getfield(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCom                                                                                                                                                                                      pletions.jl:361 (repeats 2 times)                                                                                                                                                                                                                                           
│     [3] try_get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletio                                                                                                                                                                                      ns.jl:405                                                                                                                                                                   
│     [4] try_get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletio                                                                                                                                                                                      ns.jl:417                                                                                                                                                                   
│     [5] get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletions.j                                                                                                                                                                                      l:426                                                                                                                                                       
│     [6] get_type_call(::Expr) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletions.jl:380                                                                                                                                                                                      
│     [7] try_get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletio                                                                                                                                                                                      ns.jl:408                                                                                                                                                                                                                           
│     [8] try_get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletio                                                                                                                                                                                      ns.jl:415                                                                                                                                                                                                                           
│     [9] get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletions.j                                                                                                                                                                                      l:426                                                                                                                                                                                                               
│     [10] get_type_call(::Expr) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletions.jl:38                                                                                                                                                                                      0                                                                                                                                                                                                   
│     [11] try_get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompleti                                                                                                                                                                                      ons.jl:408                                                                                                                                                                                                                              
│     [12] try_get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompleti                                                                                                                                                                                      ons.jl:415                                                                                                                                                                                                                              
│     [13] get_type(::Expr, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompletions.                                                                                                                                                                                      jl:426                                                                                                                                                                                                                  
│     [14] complete_symbol(::String, ::REPL.REPLCompletions.var"#21#25", ::Module) at /buildworker/worker/package_linux64/build/usr/shar                                                                                                                                                                                      e/julia/stdlib/v1.5/REPL/src/REPLCompletions.jl:122                                                                                                                                                                                                                                                                           
│     [15] completions(::String, ::Int64, ::Module) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/RE                                                                                                                                                                                      PLCompletions.jl:716                                                                                                                                                                                                                                                            
│     [16] completions(::String, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPLCompleti                                                                                                                                                                                      ons.jl:580                                                                                                                                                                                                                              
│     [17] complete_line(::REPL.REPLCompletionProvider, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/                                                                                                                                                                                      REPL/src/REPL.jl:464                                                                                                                                                                                                                                                            
│     [18] complete_line(::REPL.LineEdit.PromptState, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/RE                                                                                                                                                                                      PL/src/LineEdit.jl:329                                                                                                                                                                                                                                                                  
│     [19] complete_line(::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/Line                                                                                                                                                                                      Edit.jl:320                                                                                                                                                                                                                                 
│     [20] edit_tab(::REPL.LineEdit.MIState, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL                                                                                                                                                                                      /src/LineEdit.jl:2032 (repeats 2 times)                                                                                                                                                                                                                                                                                       
│     [21] (::REPL.LineEdit.var"#109#162")(::Any, ::Any, ::Vararg{Any,N} where N) at /buildworker/worker/package_linux64/build/usr/share                                                                                                                                                                                      /julia/stdlib/v1.5/REPL/src/LineEdit.jl:2073                                                                                                                                                                                                                                                                                  
│     [22] #invokelatest#1 at ./essentials.jl:710 [inlined]                                                                                                                                                                                                                                                                   
│     [23] invokelatest at ./essentials.jl:709 [inlined]                                                                                                                                                                                                                                                                      
│     [24] (::REPL.LineEdit.var"#22#23"{REPL.LineEdit.var"#109#162",String})(::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:1364
│     [25] prompt!(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:2447
│     [26] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:2350
│     [27] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:1144
│     [28] (::REPL.var"#38#42"{REPL.LineEditREPL,REPL.REPLBackendRef})() at ./task.jl:356
└ @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:2449
```
</details>

### PR DESCRIPTION
**Pull request by aviatesk**
This PR makes field completions work for complex expression case, which is reported in #40247 .

One thing I noticed while working on this was that the current implementation of 
`REPL.REPLCompletions.completions(::String, ::Int, ::Module)` doesn't work for 
simpler cases.
For example, with this PR we can get completions for this complex case
```julia
struct Rs
    rs::Vector{Regex}
end
foo() = Rs([r"foo"])

foo().rs[1]. # completes to `.regex`, etc.
```

while we can't get completions for this simpler one:
```julia
struct R
    r::Regex
end
foo() = R(r"foo")

foo().r. # no completion happens
```

Well, in this PR I just focused on fixing #40247, and leave a fix for the problem described above
to another PR.

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -387,14 +387,17 @@ get_value(sym::QuoteNode, fn) = isdefined(fn, sym.value) ? (getfield(fn, sym.val
...
-    val, found = get_value_getfield(ex.args[2],fn) #Look up Base in Main and returns the module
-    (found && length(ex.args) >= 3) || return (nothing, false)
-    return get_value_getfield(ex.args[3], val) #Look up max in Base and returns the function if found.
-end
-get_value_getfield(sym, fn) = get_value(sym, fn)
+# Return the type of a getfield call expression
+function get_type_getfield(ex::Expr, fn::Module)
+    length(ex.args) == 3 || return Any, false # should never happen, but just for safety
+    obj, x = ex.args[2:3]
+    objt, found = get_type_getfield(obj, fn)
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:394]: This is an existing problem, but `obj` here wasn't a getfield expression, so this dispatch is rubbish.
```suggestion
    objt, found = get_type(obj, fn)
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 2]
```diff
@@ -387,14 +387,17 @@ get_value(sym::QuoteNode, fn) = isdefined(fn, sym.value) ? (getfield(fn, sym.val
...
+    found || return Any, false
+    fld = isa(x, QuoteNode) ? x.value : x
+    isdefined(objt, fld) || return Any, false
+    return fieldtype(objt, fld), true
+end
+get_type_getfield(@nospecialize(sym), fn) = get_type(sym, fn)
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:400]:
```suggestion
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 3]
```diff
@@ -387,14 +387,17 @@ get_value(sym::QuoteNode, fn) = isdefined(fn, sym.value) ? (getfield(fn, sym.val
...
-    return get_value_getfield(ex.args[3], val) #Look up max in Base and returns the function if found.
-end
-get_value_getfield(sym, fn) = get_value(sym, fn)
+# Return the type of a getfield call expression
+function get_type_getfield(ex::Expr, fn::Module)
+    length(ex.args) == 3 || return Any, false # should never happen, but just for safety
+    obj, x = ex.args[2:3]
+    objt, found = get_type_getfield(obj, fn)
+    found || return Any, false
+    fld = isa(x, QuoteNode) ? x.value : x
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:396]: If `x` isn't a QuoteNode, then it is some expression, not a Symbol
```suggestion
    if x isa QuoteNode
        fld = x.value
    elseif isexpr(x, :quote) || isexpr(x, :inert)
        fld = x.args[1]
    else
        fld = nothing # we don't know how to get the value of variable `x` here
    end
    fld isa Symbol || return Any, false
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 4]
```diff
@@ -387,14 +387,17 @@ get_value(sym::QuoteNode, fn) = isdefined(fn, sym.value) ? (getfield(fn, sym.val
...
+    isdefined(objt, fld) || return Any, false
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:397]: This isn't necessary
```suggestion
```

File: stdlib/REPL/src/REPLCompletions.jl [hunk 5]
```diff
@@ -387,14 +387,17 @@ get_value(sym::QuoteNode, fn) = isdefined(fn, sym.value) ? (getfield(fn, sym.val
...
+    return fieldtype(objt, fld), true
```
Comment (vtjnash) [inline stdlib/REPL/src/REPLCompletions.jl:398]:
```suggestion
    objt isa Type && hasfield(objt, fld) && return fieldtype(objt, fld), true
    objt isa Module && isdefined(objt, fld) && return typeof(getfield(objt, fld)), true
    return Any, false
```

File: stdlib/REPL/src/REPLCompletions.jl (hunk 4 above)
Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl:404]: true, I can't understand why the added test has been passed with the existence of this check ...

File: stdlib/REPL/src/REPLCompletions.jl (hunk 5 above)
Comment (aviatesk) [reply stdlib/REPL/src/REPLCompletions.jl:406]: I think `objt` will never be `Module`, so the second line won't be necessary.
Also I found `hasfield` fails when we check `Union{}`, and so the special case is needed here. (I wonder if we need other special cases)

Anyway, should be resolved in 140d5af.

**Comment by aviatesk** [comment]
@vtjnash ready for merge ?
