### PR TITLE
Intersect: fix `intersect_tuple` for inputs with bad normalization.

### LINKED ISSUE #49484: Subtyping-related crash in SpecialExponentialFamilies.jl
PkgEval contains the following in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-04/22/SpecialExponentialFamilies.primary.log:

```
[225] signal (11.1): Segmentation fault
in expression starting at /home/pkgeval/.julia/packages/SpecialExponentialFamilies/Xsb8p/test/test_twintower.jl:7
obviously_egal at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:313
intersect_varargs at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3099 [inlined]
intersect_tuple at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3163
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3612
intersect_all at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3814
intersect_aside at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2346
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3512
intersect_invariant at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3273
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3619
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2939
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3598
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2939
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3598
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2939
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3598
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2943
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3572
intersect_all at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3814
intersect_aside at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2346
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3512
intersect_invariant at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3273
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3619
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2939
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3598
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2943
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3572
intersect_tuple at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3170
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3612
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2939
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3598
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2939
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3598
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2943
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3572
intersect_unionall_ at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2943
intersect_unionall at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:2997
intersect at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3572
intersect_all at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3814
intersect_types at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3873
ijl_has_empty_intersection at /cache/build/default-amdci5-3/julialang/julia-master/src/subtype.c:3884
ml_matches at /cache/build/default-amdci5-3/julialang/julia-master/src/gf.c:3774
ijl_matching_methods at /cache/build/default-amdci5-3/julialang/julia-master/src/gf.c:2279
```

rr recording: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/rr/SpecialExponentialFamilies-1682262783.tar.zst

From this trace, I created the following reproducer:

```julia
struct BlockedUnitRange{CS} <: AbstractUnitRange{Int}
    first::Int
    lasts::CS
    global _BlockedUnitRange(f, cs::CS) where CS = new{CS}(f, cs)
end

struct Block{N, T}
    n::NTuple{N, T}
    Block{N, T}(n::NTuple{N, T}) where {N, T} = new{N, T}(n)
    Block{1, T}(n::Tuple{T}) where T = new{1, T}(n)
end

struct BlockRange{N,R<:NTuple{N,AbstractUnitRange{Int}}} <: AbstractArray{Block{N,Int},N}
    indices::R
    BlockRange{N,R}(inds::R) where {N,R} = new{N,R}(inds)
end

struct BlockSlice{BB,INDS<:AbstractUnitRange{Int}} <: AbstractUnitRange{Int}
    block::BB
    indices::INDS
end

abstract type AbstractBlockArray{T, N} <: AbstractArray{T, N} end

struct BlockArray{T, N, R <: AbstractArray{<:AbstractArray{T,N},N}, BS<:NTuple{N,AbstractUnitRange{Int}}} <: AbstractBlockArray{T, N}
    blocks::R
    axes::BS

    global @inline _BlockArray(blocks::R, block_sizes::BS) where {T, N, R<:AbstractArray{<:AbstractArray{T,N},N}, BS<:NTuple{N,AbstractUnitRange{Int}}} =
        new{T, N, R, BS}(blocks, block_sizes)
end

struct ApplyArray{T, N, F, Args<:Tuple} <: AbstractArray{T,N}
    f::F
    args::Args
end

abstract type AbstractInfUnitRange{T<:Real} <: AbstractUnitRange{T} end

struct InfStepRange{T,S} <: OrdinalRange{T,S}
    start::T
    step::S
    function InfStepRange{T,S}(start::T, step::S) where {T,S}
        new{T,S}(start, step)
    end
end

x = Tuple{Type{Base.Broadcast.BroadcastStyle}, Type{var"#s172"} where var"#s172"<:(Base.SubArray{Float64, 1, Arr, var"#s19", false} where var"#s19"<:Tuple{Vararg{BlockSlice{BlockRange{1, Tuple{II}}, INDS} where INDS<:Base.AbstractUnitRange{Int64}, 1}})} where II<:(Union{AbstractInfUnitRange{T}, InfStepRange{T, S} where S} where T) where Arr<:(BlockArray{T, N, R, BS} where BS<:Tuple{Vararg{Base.AbstractUnitRange{Int64}, N}} where R<:(AbstractArray{var"#s1", N} where var"#s1"<:AbstractArray{T, N}) where N where T)
Tuple{Type{Base.Broadcast.BroadcastStyle}, Type{<:SubArray{Float64, 1, Arr, <:Tuple{Vararg{BlockSlice{BlockRange{1, Tuple{II}}}, 1}}, false}}} where {Arr<:(BlockArray), II<:(Union{AbstractInfUnitRange{T}, InfStepRange{T}} where T)}

y = Tuple{Type{Base.Broadcast.BroadcastStyle}, Type{var"#s11"} where var"#s11"<:(Base.SubArray{var"#s10", N, var"#s9", I, L} where L where var"#s9"<:(ApplyArray{T, N, F, Args} where Args<:Tuple where F where N where T) where var"#s10")} where I<:Tuple{BlockSlice{var"#s34", var"#s33"} where var"#s33"<:(BlockedUnitRange{CS} where CS) where var"#s34", BlockSlice{var"#s32", var"#s31"} where var"#s31"<:(BlockedUnitRange{CS} where CS) where var"#s32", Vararg{Any}} where N
Tuple{Type{Base.Broadcast.BroadcastStyle}, Type{<:SubArray{<:Any, N, <:ApplyArray, I}}} where {N, I<:Tuple{BlockSlice{<:Any, <:BlockedUnitRange}, BlockSlice{<:Any, <:BlockedUnitRange}, Vararg{Any}}}

ccall(:jl_has_empty_intersection, Any, (Any, Any), x, y)
```

Or, reduced:

```julia
struct Block; end
struct BlockRange{NBlock, N}; end
struct BlockSlice{INDSAbstractUnitRangeT, N}; end
struct ApplyArray; end

x = Tuple{Type, Type{T} where T<:(SubArray{Float64, 1, <:AbstractArray, U} where U<:Tuple{Vararg{BlockSlice{BlockRange{Tuple{II}}}, 1}})} where II<:Union
y = Tuple{Type, Type{T} where T<:(SubArray{U, N, <:ApplyArray, I} where U)} where I<:Tuple where N
ccall(:jl_has_empty_intersection, Any, (Any, Any), x, y)
```

Bisected to #49277, cc @vtjnash. Looks like `i2` can be NULL after the refactor:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007fc7bbabf25d in obviously_egal (a=a@entry=0x7fc7b4006060, b=0x0) at /home/tim/Julia/src/julia/src/subtype.c:313
313	    if (jl_typeof(a) != jl_typeof(b)) return 0;

#1  0x00007fc7bbac9ad1 in intersect_varargs (param=-1320370064, e=0x7fffa191c670, offset=2, vmy=<optimized out>, vmx=<optimized out>) at /home/tim/Julia/src/julia/src/subtype.c:3099
3099	    else if (xp2 && obviously_egal(xp1, ii) && obviously_egal(xp2, i2))
(rr) p i2
$3 = (jl_value_t *) 0x0
```

### PR DESCRIPTION
**Pull request by N5N3**
close #49484.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: src/subtype.c [hunk 1]
```diff
@@ -3060,13 +3065,15 @@ static jl_value_t *intersect_varargs(jl_vararg_t *vmx, jl_vararg_t *vmy, ssize_t
...
+    if (ii == jl_bottom_type)
+        return jl_bottom_type;
     // in Vararg{T1} <: Vararg{T2}, need to check subtype twice to
     // simulate the possibility of multiple arguments, which is needed
     // to implement the diagonal rule correctly.
-    if (intersect(xp1, yp1, e, param==0 ? 1 : param) == jl_bottom_type)
-        return jl_bottom_type;
-    jl_value_t *i2=NULL, *ii = intersect(xp1, yp1, e, 1);
+    if (!((xp2 && jl_is_long(xp2) && jl_unbox_long(xp2) == 1) || (yp2 && jl_is_long(yp2) && jl_unbox_long(yp2) == 1)))
+        ii = intersect(xp1, yp1, e, 1);
```
Comment (vtjnash) [inline src/subtype.c:3076]: Doesn't this imply that xp2 cannot get narrowed later to be assigned the value `1` or `0`, or is that handled elsewhere?

Comment (N5N3) [reply src/subtype.c:3076]: IIUC, we never do that if `Vararg` has fixed length? (We usually unwrap them and fill the `parameters`, thus their lengths are unchangeable.)

Comment (N5N3) [reply src/subtype.c:3076]: Ah yes, this check doesn’t make much sense as `Vararg` might have been consumed. Perhaps we should let `intersect_tuple` handle these cases.
