### PR TITLE
fix #36116, diff(::AbstractRange) returns an Array

### LINKED ISSUE #36116: diff on some ranges now error
```jl
julia> diff(0:2)
ERROR: ArgumentError: step cannot be zero
Stacktrace:
 [1] steprange_last(::Int64, ::Int64, ::Int64) at ./range.jl:215
 [2] StepRange at ./range.jl:205 [inlined]
 [3] _rangestyle at ./range.jl:118 [inlined]
 [4] _range at ./range.jl:116 [inlined]
 [5] #range#43 at ./range.jl:91 [inlined]
 [6] -(::UnitRange{Int64}, ::UnitRange{Int64}) at ./range.jl:1044
 [7] broadcasted at ./broadcast.jl:1081 [inlined]
 [8] broadcasted at ./broadcast.jl:1263 [inlined]
 [9] diff(::UnitRange{Int64}; dims::Int64) at ./multidimensional.jl:849
 [10] diff(::UnitRange{Int64}) at ./multidimensional.jl:809
 [11] top-level scope at REPL[3]:1

julia> diff(collect(0:2))
2-element Array{Int64,1}:
 1
 1
```

In 1.4, both of these gave a consistent answer.

From PkgEval for 1.5 (https://github.com/JuliaCI/NanosoldierReports/blob/90885ffd4005a91d0dc4150b8c1453f2f5948eb0/pkgeval/by_hash/194ddda_vs_b5f13c3/logs/ContinuumArrays/1.5.0-DEV-f11a73bd9c.log).

### PR DESCRIPTION
**Pull request by mbauman**
It's oh so tempting to simply define `diff(r::AbstractRange) = fill(step(r), length(r)-1)`, (or even a `Fill`), but this preserves the behavior that we had on 1.4 and before — and is arguably what folks want. It's not the repeated theoretical step, but the realized sequential differences of the generated elements.

### CODE REVIEW

File: base/multidimensional.jl [hunk 1]
```diff
@@ -848,6 +848,10 @@ function diff(a::AbstractArray{T,N}; dims::Integer) where {T,N}
 
     return view(a, r1...) .- view(a, r0...)
 end
+function diff(r::AbstractRange; dims::Integer=1)
+    dims == 1 || throw(ArgumentError("dimension $dims out of range (1:$N)"))
+    return [@inbounds r[i+1] - r[i] for i in firstindex(r):lastindex(r)-1]
```
Comment (JeffBezanson) [inline base/multidimensional.jl:853]:
```suggestion
    return T[@inbounds r[i+1] - r[i] for i in firstindex(r):lastindex(r)-1]
```

Comment (mbauman) [inline base/multidimensional.jl:853]:
```suggestion
function diff(r::AbstractRange{T}; dims::Integer=1) where {T}
    dims == 1 || throw(ArgumentError("dimension $dims out of range (1:$N)"))
    return T[@inbounds r[i+1] - r[i] for i in firstindex(r):lastindex(r)-1]
```

File: base/multidimensional.jl [hunk 2]
```diff
@@ -848,6 +848,10 @@ function diff(a::AbstractArray{T,N}; dims::Integer) where {T,N}
 
     return view(a, r1...) .- view(a, r0...)
 end
+function diff(r::AbstractRange{T}; dims::Integer=1) where {T}
+    dims == 1 || throw(ArgumentError("dimension $dims out of range (1:$N)"))
```
Comment (mbauman) [inline base/multidimensional.jl:852]:
```suggestion
    dims == 1 || throw(ArgumentError("dimension $dims out of range (1:1)"))
```

File: test/ranges.jl [hunk 3]
```diff
@@ -1607,6 +1607,15 @@ end
     @test collect(r) == ['a','c','e','g']
 end
 
+@testset "diff of ranges, #36116" begin
+    for r in (0:2, 0:1:2, 0.0:1.0:2.0, LinRange(0,2,3))
+        @test diff(r) == diff(collect(r)) == fill(1, 2)
+    end
```
Comment (mbauman) [inline test/ranges.jl:1613]:
```suggestion
        @test_throws ArgumentError diff(r, dims=2)
    end
```
