### PR TITLE
Fix #11419: Install libopenlibm.dll.a in windows.

### LINKED ISSUE #11419: bundle libopenlibm.lib on windows for embedding with julia-config.jl
This scenario grew out of my investigation of why **Base.Dates.unix2datetime** was crashing, turns out it's not that function but **round**, I know, weird, rite?  Better to simply show an example

    #include <julia.h>

    int main(int argc, char *argv[])
    {

        jl_init(JULIA_INIT_DIR);

        jl_eval_string("println(sqrt(2.0))");
        jl_eval_string("println(round(1.0))");

        return 0;
    }

and built using the following Makefile in an msys2 env

    JL_SHARE = $(shell julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))')
    CFLAGS   += $(shell $(JL_SHARE)/julia-config.jl --cflags)
    CXXFLAGS += $(shell $(JL_SHARE)/julia-config.jl --cflags)
    LDFLAGS  += $(shell $(JL_SHARE)/julia-config.jl --ldflags)
    LDLIBS   += $(shell $(JL_SHARE)/julia-config.jl --ldlibs)
    CC = gcc

    all: embed_example

Results in the following

    $ make
    gcc -DJULIA_INIT_DIR=\"C:\\\\Julia\\\\julia-04051e9699\\\\lib\" -IC:\\Julia\\julia-04051e9699\\include\\julia  -LC:\\Julia\\julia-04051e9699\\bin  embed_example.c  -ljulia -o embed_example

    jeffw@xun MINGW64 ~/src/julia-embed-test
    $ ./embed_example
    1.4142135623730951

    Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
    Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0)
    unknown function (ip: 0)

The call to **sqrt** is not necessary to cause the error, just to give some context that the Julia engine is functioning.  It's not just **round** either, it's at least **trunc** as well and I suspect all of the *llvm* macros.  I have not managed to debug this more fully because it's not easy to know where to begin.  This does not happen on OS/X or Linux nor in a non-embedding scenario as can be seen when using the REPL of the same Julia install.

    $ julia
                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "help()" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.4.0-dev+9597 (2015-05-23 02:32 UTC)
     _/ |\__'_|_|_|\__'_|  |  Commit 04051e9* (0 days old master)
    |__/                   |  x86_64-w64-mingw32

    julia> round(2.0)
    2.0

### PR DESCRIPTION
**Pull request by twadleigh**
Addresses #11419. This is a WIP pending the merge of https://github.com/JuliaLang/openlibm/pull/145.

### CODE REVIEW

File: contrib/julia-config.jl [hunk 1]
```diff
@@ -51,6 +51,8 @@ end
 function ldlibs()
     if is_unix()
         return replace("""-Wl,-rpath,$(libDir()) -ljulia""","\\","\\\\")
+    elseif is_windows()
+        return replace("""-ljulia -lopenlibm""","\\","\\\\")
```
Comment (tkelman) [inline contrib/julia-config.jl]: looks like the replacement doesn't do anything? also why have this as a new case?

Comment (twadleigh) [inline contrib/julia-config.jl]: Yeah, the replacement seems unnecessary. I was just following the pattern that was there before.

The new case is because `-lopenlibm` is only for windows and not, e.g., for OS X.

Comment (tkelman) [inline contrib/julia-config.jl]: we don't support anything that is neither unix nor windows. if we did, who know whether it would use backslashes in paths...

**Comment by twadleigh** [comment]
Pending version bump.

File: deps/openlibm.version [hunk 2]
```diff
@@ -1,2 +1,2 @@
 OPENLIBM_BRANCH=v0.5.3
-OPENLIBM_SHA1=71e79eb6f74d3f04ce724195b8ef5846a70d281e
+OPENLIBM_SHA1=b6b8422bc2255f880803d2670c9722e67eddeaeb
```
Comment (tkelman) [inline deps/openlibm.version]: use the tag, and update the checksum files - remove the old, add the new

**Comment by twadleigh** [comment]
Should be good to go now.

**Comment by stevengj** [comment]
LGTM.

**Comment by twadleigh** [comment]
I noticed this didn't make it into 0.5.0. Might it be considered for backporting into 0.5.1?

**Comment by stevengj** [comment]
Added a backport tag to make sure the possibility of backporting this gets reviewed.
