### PR TITLE
Correct @fastmath when accessing fields

### LINKED ISSUE #14318: `@fastmath` prevents accessing fields called `min` or `max`
This is an example of what is going wrong:
```Julia
type T min::Float64 end
x=T(1)

julia> x.min
1.0

julia> @fastmath x.min
ERROR: TypeError: getfield: expected Symbol, got Expr
```

The `@fastmath` macro replaces the symbol `min` by `fast_min` in the expression. This makes the field `min` inaccessible, as Julia now tries to access something like `x.fast_min`.

The best short-term solution is probably to not perform this replacement in `getfield` and `setfield` calls.

A better solution would be to temporarily (i.e. lexically scoped) search a module `FastMath` before `Base` while resolving function names. Is this possible?

### PR DESCRIPTION
**Pull request by eschnett**
Skip `quote` expresstion to handle e.g. `@fastmath x.min` without expanding `min` to `min_fast`.
Clean up code (remove parentheses, use `===` instead of `==`).
Closes #14318.

### CODE REVIEW

**Comment by yuyichao** [comment]
Could use a test?

File: base/fastmath.jl [hunk 1]
```diff
@@ -88,14 +88,18 @@ const rewrite_op =
          :^= => :^)
 
 function make_fastmath(expr::Expr)
+    if expr.head === :quote
+        return expr
+    end
     op = get(rewrite_op, expr.head, :nothing)
-    if op != :nothing
+    if op !== :nothing
+        info("FM: rewriting op $(expr.head) with $op")
```
Comment (jakebolewski) [inline base/fastmath.jl]: leftover debug output?
