### PR TITLE
Output disassembly labels via the streamer

### LINKED ISSUE #14184: `code_native` shows labels in wrong places
I built Julia, master branch, on OS X, with LLVM 3.7.0 and with threading enabled.

This function:
```Julia
function axpy!(a,x,y)
    @inbounds for i in eachindex(y)
        y[i] += a*x[i]
    end
end
```
leads to this output:
```
julia> code_native(axpy!, (Float64, Vector{Float64}, Vector{Float64}))
L99:L128:L172:L177:L208:	.section	__TEXT,__text,regular,pure_instructions
	pushq	%rbp
	movq	%rsp, %rbp
	movq	8(%rsi), %rax
	cmpq	$1, %rax
	jl	L238
	movl	$1, %r8d
	movq	(%rsi), %rcx
	movq	(%rdi), %rdx
	cmpq	$0, %rax
	je	L177
	movl	$1, %r8d
	leaq	1(%rax), %r9
	movq	%rax, %r10
	andq	$-8, %r10
	orq	$1, %r10
	cmpq	$1, %r10
	je	L172
	leaq	-1(%rax), %rdi
	shlq	$3, %rdi
	leaq	(%rcx,%rdi), %rsi
	leaq	(%rdi,%rdx), %rdi
	cmpq	%rdi, %rcx
	ja	L99
	movl	$1, %r8d
	cmpq	%rsi, %rdx
	jbe	L172
	vbroadcastsd	%xmm0, %ymm1
	leaq	32(%rcx), %rsi
	leaq	32(%rdx), %rdi
	movq	%rax, %r8
	shrq	$3, %r8
	shlq	$3, %r8
	nopl	(%rax,%rax)
	vmulpd	-32(%rdi), %ymm1, %ymm2
	vmulpd	(%rdi), %ymm1, %ymm3
	vaddpd	-32(%rsi), %ymm2, %ymm2
	vaddpd	(%rsi), %ymm3, %ymm3
	vmovupd	%ymm2, -32(%rsi)
	vmovupd	%ymm3, (%rsi)
	addq	$64, %rsi
	addq	$64, %rdi
	addq	$-8, %r8
	jne	L128
	movq	%r10, %r8
	cmpq	%r8, %r9
	je	L238
	addq	$1, %rax
	subq	%r8, %rax
	addq	$-1, %r8
	shlq	$3, %r8
	addq	%r8, %rdx
	addq	%r8, %rcx
	nopw	%cs:(%rax,%rax)
	vmulsd	(%rdx), %xmm0, %xmm1
	vaddsd	(%rcx), %xmm1, %xmL238:m1
	vmovsd	%xmm1, (%rcx)
	addq	$-1, %rax
	addq	$8, %rdx
	addq	$8, %rcx
	cmpq	$0, %rax
	jne	L208
	movabsq	$4436967440, %rax       ## imm = 0x10876C010
	popq	%rbp
	vzeroupper
	retq
```

Note that (a) many labels are wrongly accumulated near the top, and (b) label "L238:m1" is missing a line break before the label.

### PR DESCRIPTION
**Pull request by eschnett**
This ensures they appear in the correct order.
Fixes #14184.

### CODE REVIEW

**Comment by vtjnash** [comment]
there are two more near https://github.com/JuliaLang/julia/pull/14187/files#diff-5060fdfc5cb40a40ce5729ca8c4e4cf2R582

**Comment by eschnett** [comment]
@vtjnash I corrected those as well.

File: src/codegen.cpp [hunk 1]
```diff
@@ -1454,14 +1454,22 @@ void jl_dump_asm_internal(uintptr_t Fptr, size_t Fsize, size_t slide,
...
+                          formatted_raw_ostream &stream
+#endif
+                          );
 
 extern "C" DLLEXPORT
 const jl_value_t *jl_dump_function_asm(void *f, int raw_mc)
 {
     std::string code;
     llvm::raw_string_ostream stream(code);
+#ifdef LLVM37
```
Comment (yuyichao) [inline src/codegen.cpp]: I guess this (and the one below) could have been a `#ifndef LLVM37`. Not a big deal though.

Thanks for the fix =)
