### PR TITLE
Make trimmed binaries initialize on first call

### LINKED ISSUE #57941: juliac --trim on windows gives exception
```
module HelloWorld

Base.@ccallable function main()::Cint
    println(Core.stdout, "Hello world")
    return 0
end

end
```

1.13.0-DEV.325, Windows 11, Powershell: 

>julia juliac.jl --output-exe hello --trim --experimental hello.jl

Compiles to a 12.7 MB binary, but gives an error when run:

>Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks. Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff959ffcd21 -- Hello world

After compiling without `--trim --experimental` the resulting exe works fine.

### PR DESCRIPTION
**Pull request by gbaraldi**
This technically also makes normal julia shared libraries that use ccallable autoinit

The bindir that I set is guaranteed to be wrong in some cases. @topolarity suggested looking for julia there but it seems to me it's a bit useless most of the time so not sure yet

### CODE REVIEW

File: src/threading.c [hunk 1]
```diff
@@ -453,19 +455,88 @@ JL_DLLEXPORT jl_gcframe_t **jl_adopt_thread(void)
     return &ct->gcstack;
 }
 
+static char * get_path_from_sym(void *sym)
```
Comment (topolarity) [inline src/threading.c:458]: This seems like it should be in `dlload.c` next to `jl_find_dynamic_library_by_addr`
(maybe call it `jl_find_dynamic_library_path_by_addr`)

Comment (topolarity) [reply src/threading.c:458]: Looks like we already have `jl_pathname_for_handle` actually

File: src/threading.c [hunk 2]
```diff
@@ -453,19 +455,88 @@ JL_DLLEXPORT jl_gcframe_t **jl_adopt_thread(void)
...
+        if (new_dir != lib_dir) {
+            // On some platforms, dirname() mutates.  On others, it does not.
+            memcpy(lib_dir, new_dir, strlen(new_dir)+1);
+            free((void*)new_dir);
+        }
+        char *libbindir = NULL;
+#ifdef _OS_WINDOWS_
+        libbindir = lib_dir;
+#else
+        (void)asprintf(&libbindir, "%s" PATHSEPSTRING ".." PATHSEPSTRING "%s",lib_dir, "bin");
```
Comment (topolarity) [inline src/threading.c:530]: This should probably be relative to the `libjulia.so` directory and not the sysimage itself - otherwise this won't work with a folder structure like this:
```julia
- julia/
    - libjulia.so
    - ...
- trim_compiled.so
```

(which we do support - the `rpath` checks both the current directory and an adjacent `julia/`)

File: src/threading.c (hunk 1 above)
Comment (gbaraldi) [reply src/threading.c:458]: That one is slightly different since it takes in a library handle

Comment (topolarity) [reply src/threading.c:458]: Right, but this seems simpler:
```julia
void *handle = jl_find_dynamic_library_by_addr(...);
const char *filepath = jl_pathname_for_handle(handle);
```

or is there a reason to re-implement that via the fused operation?

Comment (gbaraldi) [reply src/threading.c:458]: I guess that's fine as well.

File: src/threading.c (hunk 2 above)
Comment (topolarity) [reply src/threading.c:530]: Yeah `jl_get_libdir()` is the same path, so sounds good to me

File: src/threading.c [hunk 3]
```diff
@@ -1,11 +1,13 @@
...
 #include <string.h>
 #include <inttypes.h>
-
+#ifndef _OS_WINDOWS_
+#include <dlfcn.h>
+#endif
+#include <libgen.h> // defines dirname
 #include "julia.h"
 #include "julia_internal.h"
 #include "julia_assert.h"
```
Comment (topolarity) [inline src/threading.c:13]:
```suggestion
#include "julia.h"
#include "julia_internal.h"
#include "julia_assert.h"
#ifndef _OS_WINDOWS_
#include <dlfcn.h>
#endif
#include <libgen.h> // defines dirname
```

`_OS_WINDOWS_` is apparently provided by system headers

File: src/jlapi.c [hunk 4]
```diff
@@ -88,7 +88,20 @@ JL_DLLEXPORT void jl_init_with_image(const char *julia_bindir,
...
+        char *libbindir = NULL;
+#ifdef _OS_WINDOWS_
+        libbindir = strdup(jl_get_libdir());
+#else
+        (void)asprintf(&libbindir, "%s" PATHSEPSTRING ".." PATHSEPSTRING "%s", jl_get_libdir(), "bin");
+#endif
+        if (!libbindir) {
+            printf("jl_init unable to find libjulia!\n");
+            abort();
+        }
```
Comment (topolarity) [inline src/jlapi.c:103]: Oops, don't forget to update `jl_options.julia_bindir`:
```suggestion
#ifdef _OS_WINDOWS_
        jl_options.julia_bindir = strdup(jl_get_libdir());
#else
        int written = asprintf(&jl_options.julia_bindir, "%s" PATHSEPSTRING ".." PATHSEPSTRING "%s", jl_get_libdir(), "bin");
        if (written < 0) 
            abort(); // unexpected: memory allocation failed
#endif
```

The error check for `asprintf` needs to be this way according to https://man7.org/linux/man-pages/man3/asprintf.3.html

Also `jl_get_libdir()` will panic / abort rather than return `NULL`, so no need to handle that error

File: src/threading.c [hunk 5]
```diff
@@ -1,14 +1,16 @@
...
 #include <string.h>
 #include <inttypes.h>
-
 #include "julia.h"
 #include "julia_internal.h"
 #include "julia_assert.h"
+#ifndef _OS_WINDOWS_
+#include <dlfcn.h>
+#endif
+#include <libgen.h> // defines dirname
```
Comment (topolarity) [inline src/threading.c:13]:
```suggestion
```

**Review by topolarity — APPROVED** [review]
This looks good to me.

We'll have to follow up soon for multi-threading concerns (@vtjnash is skeptical of the `jl_enter_threaded_region()`) but this is big step in the right direction.
