### PR TITLE
fix printing of pairs containing array (fix #25466)

### LINKED ISSUE #25466: Vector{Pair} - display errors for element type Pair{Any,Vector}
```
julia> pairs = Vector{Pair}()
0-element Array{Pair,1}

julia> push!(pairs, ""=>[1])
1-element Array{Pair,1}:
Error showing value of type Array{Pair,1}:
ERROR: AssertionError: Array{Int64,1} is not a subtype of Pair
Stacktrace:
 [1] typeinfo_prefix(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{Int64,1}) at ./arrayshow.jl:480
 [2] show_vector(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{Int64,1}, ::Char, ::Char) at ./arrayshow.jl:433 (repeats 2 times)
 [3] show at ./arrayshow.jl:447 [inlined]
 [4] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Pair{String,Array{Int64,1}}) at ./show.jl:424

julia> pairs[1]
"" => [1]
```

### LINKED ISSUE #26256: AssertionError when showing values of `Pair{Symbol,Array{T,N}}`
```
julia> [:A=>rand(2)]
1-element Array{Pair{Symbol,Array{Float64,1}},1}:
Error showing value of type Array{Pair{Symbol,Array{Float64,1}},1}:
ERROR: AssertionError: Array{Float64,1} is not a subtype of Pair{Symbol,Array{Float64,1}}
Stacktrace:
 [1] typeinfo_prefix(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{Float64,1}) at ./arrayshow.jl:479
 [2] show_vector(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{Float64,1}, ::Char, ::Char) at ./arrayshow.jl:432 (repeats 2 times)
 [3] show at ./arrayshow.jl:446 [inlined]
 [4] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Pair{Symbol,Array{Float64,1}}) at ./show.jl:579
 [5] #sprint#345(::IOContext{REPL.Terminals.TTYTerminal}, ::Int64, ::Function, ::Function, ::Pair{Symbol,Array{Float64,1}}, ::Vararg{Pair{Symbol,Array{Float64,1}},N} where N) at ./strings/io.jl:91
 [6] #sprint at ./<missing>:0 [inlined]
 [7] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::Pair{Symbol,Array{Float64,1}}) at ./show.jl:1789
 [8] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Pair{Symbol,Array{Float64,1}},1}, ::Base.OneTo{Int64}, ::Base.OneTo{Int64}, ::Int64, ::Int64, ::Int64) at ./arrayshow.jl:68
 [9] print_matrix(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Pair{Symbol,Array{Float64,1}},1}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./arrayshow.jl:187
 [10] print_matrix at ./arrayshow.jl:160 [inlined]
 [11] print_array at ./arrayshow.jl:309 [inlined]
 [12] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Array{Pair{Symbol,Array{Float64,1}},1}) at ./arrayshow.jl:345
 [13] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Array{Pair{Symbol,Array{Float64,1}},1}) at /buildworker/worker/build_ubuntu64/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:131
 [14] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::Array{Pair{Symbol,Array{Float64,1}},1}) at /buildworker/worker/build_ubuntu64/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:134
 [15] display(::Array{Pair{Symbol,Array{Float64,1}},1}) at ./multimedia.jl:287
 [16] (::getfield(Base, Symbol("#inner#4")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},typeof(display),Tuple{Array{Pair{Symbol,Array{Float64,1}},1}}})() at ./essentials.jl:639
 [17] #invokelatest#3 at ./essentials.jl:640 [inlined]
 [18] invokelatest at ./essentials.jl:639 [inlined]
 [19] print_response(::REPL.Terminals.TTYTerminal, ::Any, ::Nothing, ::Bool, ::Bool, ::Nothing) at /buildworker/worker/build_ubuntu64/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:152
 [20] print_response(::REPL.LineEditREPL, ::Any, ::Nothing, ::Bool, ::Bool) at /buildworker/worker/build_ubuntu64/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:138
 [21] (::getfield(REPL, Symbol("#do_respond#42")){Bool,getfield(REPL, Symbol("##52#61")){REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /buildworker/worker/build_ubuntu64/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:704
 [22] top-level scope
```

```
julia> versioninfo()
Julia Version 0.7.0-DEV.4390
Commit 79c7bdd9ec (2018-02-26 07:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  JULIA_BINDIR = /opt/julia/bin
  JULIA_HOME = /opt/julia0p6/bin
```

### PR DESCRIPTION
**Pull request by rfourquet**
E.g `[:A => rand(2)]`.

Fixes #25466.

### CODE REVIEW

File: base/show.jl [hunk 1]
```diff
@@ -577,12 +577,16 @@ function show(io::IO, p::Pair)
     iocompact = IOContext(io, :compact => get(io, :compact, true))
     has_tight_type(p) || return show_default(iocompact, p)
 
+    typeinfo = get(io, :typeinfo, Any)
+    typeinfos = typeinfo <: Pair ?
```
Comment (vtjnash) [inline base/show.jl]: `&& isa(unwrap_unionall(typeinfo, DataType))`

**Review by vtjnash — APPROVED** [review]

File: base/show.jl (hunk 1 above)
Comment (rfourquet) [reply base/show.jl]: I can only think of `typeinfo = Union{}` where this added test would make a difference, are there other cases? otherwise, we might as well test `typeinfo !== Union{}`?

**Comment by rfourquet** [comment]
@JeffBezanson I agree; the `@assert` is useful for finding unimplemented `typeinfo` handling in `Base` code, but too strict for user-defined code. See #26630 for a possible solution.

File: base/show.jl (hunk 1 above)
Comment (vtjnash) [reply base/show.jl]: Any Union. And why would we not just test the actual constraint currently imposed by fieldtype?

Comment (rfourquet) [reply base/show.jl]: Ah ok thanks, hadn't thought about `Union` of `Pair`s. 

> And why would we not just test the actual constraint currently imposed by fieldtype?

I don't really know what you mean. I should also update this test with `p isa typeinfo` by the way.

Comment (rfourquet) [reply base/show.jl]: I'm not familiar enough with `unwrap_unionall` (let alone the constraints imposed by `fieldtype`), but it would seem to me that only testing `isa(unwrap_unionall(typeinfo), DataType)` would not be enough. For all likely cases, testing for `typeinfo !== Union{}` (itself unlikely to happen) would be sufficient for now, and is taken care of by the test `p isa typeinfo` that I just added. I will merge later today if no objection.

**Comment by rfourquet** [comment]
CI failures seem irrelevant.
