### PR TITLE
Limit type-printing in MethodError

### LINKED ISSUE #50803: Long types printed in MethodError
As reported in https://discourse.julialang.org/t/type-parameter-display-in-1-10-for-methoderror/102516

```julia
a = view(reinterpret(reshape, UInt8, PermutedDimsArray(rand(5, 7), (2, 1))), 2:3, 2:4, 1:4); # a mildly-complex type
function foo end

julia> foo(a, a, a, a, a, a, a)
ERROR: MethodError: no method matching foo(::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false}, ::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false}, ::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false}, ::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false}, ::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false}, ::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false}, ::SubArray{UInt8, 3, Base.ReinterpretArray{UInt8, 3, Float64, PermutedDimsArray{Float64, 2, (2, 1), (2, 1), Matrix{Float64}}, true}, Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}}, false})
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

### PR DESCRIPTION
**Pull request by timholy**
Demo:

```julia
julia> a = view(reinterpret(reshape, UInt8, PermutedDimsArray(rand(5, 7), (2, 1))), 2:3, 2:4, 1:4); # a mildly-complex type

julia> function f50803 end
f50803 (generic function with 0 methods)

julia> f50803(a, a, a, a, a, a)
ERROR: MethodError: no method matching f50803(::SubArray{…}, ::SubArray{…}, ::SubArray{…}, ::SubArray{…}, ::SubArray{…}, ::SubArray{…})
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

Fixes #50803

### CODE REVIEW

File: base/errorshow.jl [hunk 1]
```diff
@@ -268,20 +268,28 @@ function showerror(io::IO, ex::MethodError)
...
-                print(io, k, "::", typeof(v))
-                i == length(kwargs)::Int || print(io, ", ")
+                print(iob, k, "::", typeof(v))
+                i == length(kwargs)::Int || print(iob, ", ")
             end
         end
-        print(io, ")")
+        print(iob, ")")
+        str = String(take!(unwrapcontext(iob)[1]))
+        ioc = IOContext(io)
```
Comment (JeffBezanson) [inline base/errorshow.jl:287]: I don't see why this extra IOContext is needed?

Comment (timholy) [reply base/errorshow.jl:287]: Just for reduced specialization and inferrability (in case `io` is not an `IOContext`), but I can delete it if you prefer.

File: base/errorshow.jl [hunk 2]
```diff
@@ -268,20 +268,25 @@ function showerror(io::IO, ex::MethodError)
...
-                print(io, k, "::", typeof(v))
-                i == length(kwargs)::Int || print(io, ", ")
+                print(iob, k, "::", typeof(v))
+                i == length(kwargs)::Int || print(iob, ", ")
             end
         end
-        print(io, ")")
+        print(iob, ")")
+        str = String(take!(unwrapcontext(iob)[1]))
+        ioc = !haskey(io, :displaysize) ? IOContext(io, :displaysize => displaysize(io)) : io
```
Comment (JeffBezanson) [inline base/errorshow.jl:287]: So it looks like in this case we will use the default `displaysize()`, but the code path for stacktraces defaults to `typemax`? Is there a good reason for that or should we just change `type_limited_string_from_context` to call `displaysize(io)`?

Comment (JeffBezanson) [reply base/errorshow.jl:287]: Note this might fully be my fault for putting in typemax instead of using the normal default display size.

Comment (timholy) [reply base/errorshow.jl:287]: I wasn't sure why it was `typemax`. I'd certainly support changing it to always call `displaysize(io)`.

Comment (timholy) [reply base/errorshow.jl:287]: If we agree to make that change, we can move the call to `displaysize` into `type_limited_string_from_context`.

Comment (JeffBezanson) [reply base/errorshow.jl:287]: Ok please go ahead and do that.

**Review by JeffBezanson — APPROVED** [review]
