### PR TITLE
inference: improve cycle detection

### LINKED ISSUE #17278: Inference (?) hang on recursive methods
Here's what I suspect is a second example of the problem noted in #17137, but which can be easily replicated on master:

``` jl
julia> I = (CartesianIndex{1}(2), 3, CartesianIndex{1}(3))
(CartesianIndex{1}((2,)),3,CartesianIndex{1}((3,)))

julia> _flatten(out) = out
_flatten (generic function with 1 method)

julia> _flatten(out, i, I...)        = _flatten((out..., i), I...)
_flatten (generic function with 2 methods)

julia> _flatten(out, i::CartesianIndex, I...) = _flatten((out..., i.I...), I...)
_flatten (generic function with 3 methods)

julia> _flatten((), I...)
^C^C^C^C^C^C^CWARNING: Force throwing a SIGINT
WARNING: An error occured during inference. Type inference is now partially disabled.
InterruptException()
unknown function (ip: 0x7f7341157bdf)
^C^C^C^C
```

All those Ctrl-Cs come from the fact that this call hangs, at least for minutes.

Interestingly, change `i` to `i::Int` in the second `_flatten` method, and it works fine.

Discovered in the course of trying to fix #17275.

### LINKED ISSUE #19570: Type inference infinite loop?
Under
```julia
julia> versioninfo()
Julia Version 0.6.0-dev.1529
Commit 9ae5e06* (2016-12-08 23:28 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```
the following works as expected
```julia
julia> begin
           foo(args...) = bar(((),), (), args...)
           bar(scals, mats, lastarg::SparseMatrixCSC) = (scals..., ()), (mats..., lastarg)
           bar(scals, mats, nextarg, remargs...) = bar((Base.front(scals)..., (last(scals)..., nextarg)), mats, remargs...)
           # bar(scals, mats, nextarg::SparseMatrixCSC, remargs...) = bar((scals..., ()), (mats..., nextarg), remargs...)
       end
bar (generic function with 2 methods)

julia> foo(1.0, speye(2))
(((1.0,),()),(

	[1, 1]  =  1.0
	[2, 2]  =  1.0,))
```
but the same with the additional `bar` definition uncommented hangs indefinitely, and on interrupt the trace points to inference. Note that replacing the body of the commented `bar` definition with e.g. `println("narwhal")` works fine as well. Best!

(Originally [posted to discourse](https://discourse.julialang.org/t/type-inference-infinite-loop/856).)

### LINKED ISSUE #20714: Inference hang when inlining is off
If you check out the master branch of AxisArrays.jl (currently, this is commit 4d2f8ccc08d582adcf0a029d28f5ccd12b72f406), then the following script succeeds with normal inlining but hangs during inference with `--inline=no`:
```julia
using AxisArrays

Base.reduced_indices(A::AxisArray, region)  = reduced_indices(axes(A), region)

@inline reduced_indices{Ax<:Axis}(axs::Tuple{Vararg{Axis}}, region::Type{Ax}) =
    _reduced_indices(reduced_axis, (), region, axs...)

@inline _reduced_indices{name}(f, out, chosen::Type{Axis{name}}, ax::Axis{name}, axs...) =
    _reduced_indices(f, (out..., f(ax)), chosen, axs...)
@inline _reduced_indices{name}(f, out, chosen::Axis{name}, ax::Axis{name}, axs...) =
    _reduced_indices(f, (out..., f(ax)), chosen, axs...)
@inline _reduced_indices(f, out, chosen, ax::Axis, axs...) =
    _reduced_indices(f, (out..., ax), chosen, axs...)
_reduced_indices(f, out, chosen) = out

reduced_axis(ax) = ax(oftype(ax.val, Base.OneTo(1)))

C = AxisArray(collect(reshape(1:15,3,5)), :y, :x)
sum(C, Axis{:x})
```

Observed in https://github.com/JuliaArrays/AxisArrays.jl/pull/56.

### LINKED ISSUE #21244: Inference failure with 0.6 + StaticArrays hcat
With StaticArrays latest master,
```julia
using StaticArrays

struct Foo
    bar::SMatrix{3, 3, Float64}
    Foo() = new(eye(SMatrix{3, 3, Float64}))
end

function f(foo::Foo)
    hcat(foo.bar[:, SVector(1, 2)], zeros(SMatrix{3, 3, Float64}))
end

foo = Foo()
f(foo)
```
sometimes results in
```
WARNING: An error occurred during inference. Type inference is now partially disabled.

signal (11): Segmentation fault
while loading /home/twan/code/RigidBodyDynamics/v0.6/RigidBodyDynamics/segfault.jl, in expression starting on line 13
_ZN4llvm17ScheduleDAGMILive19updatePressureDiffsENS_8ArrayRefINS_16RegisterMaskPairEEE at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
_ZN4llvm17ScheduleDAGMILive15initRegPressureEv at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
_ZN4llvm17ScheduleDAGMILive8scheduleEv at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
unknown function (ip: 0x7fd185333fd0)
unknown function (ip: 0x7fd18533c83f)
_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /home/twan/code/julia/usr/bin/../lib/libLLVM-3.9.so (unknown line)
operator() at /home/twan/code/julia/src/jitlayers.cpp:442 [inlined]
_M_invoke at /usr/include/c++/5/functional:1857
operator() at /usr/include/c++/5/functional:2267 [inlined]
addModuleSet<llvm::SmallVector<std::unique_ptr<llvm::Module>, 1u>, llvm::RTDyldMemoryManager*, std::unique_ptr<llvm::orc::LambdaResolver<JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)>, JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)> >, std::default_delete<llvm::orc::LambdaResolver<JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)>, JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)> > > > > at /home/twan/code/julia/usr/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h:73 [inlined]
addModule at /home/twan/code/julia/src/jitlayers.cpp:569
jl_add_to_ee at /home/twan/code/julia/src/jitlayers.cpp:792 [inlined]
jl_finalize_function at /home/twan/code/julia/src/jitlayers.cpp:803
getAddressForFunction at /home/twan/code/julia/src/codegen.cpp:1360
jl_generate_fptr at /home/twan/code/julia/src/codegen.cpp:1457
jl_compile_method_internal at /home/twan/code/julia/src/julia_internal.h:313 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:341 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
println at ./boot.jl:378 [inlined]
println at ./boot.jl:382
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
typeinf_loop at ./inference.jl:2657
typeinf_frame at ./inference.jl:2467
typeinf_code at ./inference.jl:2537
unknown function (ip: 0x7fd18128c5dd)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
typeinf_ext at ./inference.jl:2576
unknown function (ip: 0x7fd18126bfe2)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
jl_apply at /home/twan/code/julia/src/julia.h:1416 [inlined]
jl_type_infer at /home/twan/code/julia/src/gf.c:269
jl_compile_for_dispatch at /home/twan/code/julia/src/gf.c:1629
jl_compile_method_internal at /home/twan/code/julia/src/julia_internal.h:294 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:341 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
f at /home/twan/code/RigidBodyDynamics/v0.6/RigidBodyDynamics/segfault.jl:9
unknown function (ip: 0x7fcf53f60792)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
do_call at /home/twan/code/julia/src/interpreter.c:75
eval at /home/twan/code/julia/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/twan/code/julia/src/interpreter.c:34
jl_toplevel_eval_flex at /home/twan/code/julia/src/toplevel.c:577
jl_parse_eval_all at /home/twan/code/julia/src/ast.c:873
jl_load at /home/twan/code/julia/src/toplevel.c:616
include_from_node1 at ./loading.jl:539
unknown function (ip: 0x7fd1813edf3b)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
include at ./sysimg.jl:14
unknown function (ip: 0x7fd18129167b)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
process_options at ./client.jl:305
_start at ./client.jl:371
unknown function (ip: 0x7fd18141b578)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
jl_apply at /home/twan/code/julia/ui/../src/julia.h:1416 [inlined]
true_main at /home/twan/code/julia/ui/repl.c:127
main at /home/twan/code/julia/ui/repl.c:264
__libc_start_main at /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:291
unknown function (ip: 0x401668)
Allocations: 3910719 (Pool: 3909327; Big: 1392); GC: 5
Segmentation fault (core dumped)
```
other times in
```
WARNING: An error occurred during inference. Type inference is now partially disabled.
StackOverflowError()
forall_exists_subtype at /home/twan/code/julia/src/subtype.c:881
jl_subtype_env at /home/twan/code/julia/src/subtype.c:948
abstract_eval at ./inference.jl:1902
unknown function (ip: 0x7efefe0b0df6)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
copy! at ./abstractarray.jl:565
abstract_eval_call at ./inference.jl:1866
abstract_eval at ./inference.jl:1915
unknown function (ip: 0x7efefe0b0df6)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234
copy! at ./abstractarray.jl:565
abstract_eval_call at ./inference.jl:1866
abstract_eval at ./inference.jl:1915
unknown function (ip: 0x7efefe0b0df6)
jl_call_fptr_internal at /home/twan/code/julia/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/twan/code/julia/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/twan/code/julia/src/gf.c:2234

<repeating>
```

`versioninfo()`:
```
Julia Version 0.6.0-pre.alpha.329
Commit cded1db (2017-03-31 00:28 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

StaticArrays SHA: bd3236ac39372aa84891bea066c71d63559af29e

cc: @andyferris

### PR DESCRIPTION
**Pull request by vtjnash**
This helps ensure that inference converges, by ensuring that any recursion must be finite. Also fixed a number of functions in base that weren't finite under recursion and thus could trigger infinite loops in inference (especially if we tried to infer based just on method signatures). I'm mildly optimistic that this will permit increasing of `tupletype_len` :)

fixes https://github.com/JuliaLang/julia/issues/21244
fixes https://github.com/JuliaLang/julia/issues/17278
fixes https://github.com/JuliaLang/julia/issues/20714
fixes https://github.com/JuliaLang/julia/issues/19570

### CODE REVIEW

File: base/abstractarray.jl [hunk 1]
```diff
@@ -1160,30 +1160,32 @@ cat_similar(A::AbstractArray, T, shape) = similar(A, T, shape)
...
+@inline function _cshp(ndim::Int, ::Tuple{}, shape, ::Tuple{})
+    _cs(ndim, shape[1], 1)
+    (1, _cshp(ndim + 1, (), tail(shape), ())...)
+end
+@inline function _cshp(ndim::Int, ::Tuple{}, shape, nshape)
+    next = _cs(ndim, shape[1], nshape[1])
+    (next, _cshp(ndim + 1, (), tail(shape), tail(nshape))...)
+end
+@inline function _cshp(ndim::Int, dims, shape, nshape)
+	a = shape[1]
```
Comment (ararslan) [inline base/abstractarray.jl]: Should be 4 space indents

File: base/inference.jl [hunk 2]
```diff
@@ -734,6 +747,172 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
     return R
 end
 
+function limit_type_size(t::ANY, compare::ANY, source::ANY)
+    source = svec(unwrap_unionall(compare), unwrap_unionall(source))
+    source[1] === source[2] && (source = svec(source[1]))
+    type_more_complex(t, compare, source) || return t
+    r = _limit_type_size(t, compare, source)
+    #@assert !isa(t, Type) || t <: r
```
Comment (ararslan) [inline base/inference.jl]: Is this something you'd expect would be reenabled at some point?

Comment (vtjnash) [inline base/inference.jl]: perhaps. currently it would just trigger the same false-bug detection as https://github.com/JuliaLang/julia/pull/21907

File: base/tuple.jl [hunk 3]
```diff
@@ -126,36 +127,11 @@ function _ntuple(f, n)
...
-ntuple(f, ::Type{Val{6}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6)))
-ntuple(f, ::Type{Val{7}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7)))
-ntuple(f, ::Type{Val{8}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8)))
-ntuple(f, ::Type{Val{9}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9)))
-ntuple(f, ::Type{Val{10}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10)))
-ntuple(f, ::Type{Val{11}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10), f(11)))
-ntuple(f, ::Type{Val{12}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10), f(11), f(12)))
-ntuple(f, ::Type{Val{13}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10), f(11), f(12), f(13)))
-ntuple(f, ::Type{Val{14}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10), f(11), f(12), f(13), f(14)))
-ntuple(f, ::Type{Val{15}}) = (@_inline_meta; (f(1), f(2), f(3), f(4), f(5), f(6), f(7), f(8), f(9), f(10), f(11), f(12), f(13), f(14), f(15)))
```
Comment (KristofferC) [inline base/tuple.jl]: Is this not needed anymore?

File: base/array.jl [hunk 4]
```diff
@@ -73,12 +73,7 @@ end
 size(a::Array, d) = arraysize(a, d)
 size(a::Vector) = (arraysize(a,1),)
 size(a::Matrix) = (arraysize(a,1), arraysize(a,2))
-size(a::Array) = (@_inline_meta; _size((), a))
-_size(out::NTuple{N}, A::Array{_,N}) where {_,N} = out
-function _size(out::NTuple{M}, A::Array{_,N}) where _ where M where N
-    @_inline_meta
-    _size((out..., size(A,M+1)), A)
-end
+size(a::Array{<:Any,N}) where {N} = (@_inline_meta; ntuple(M -> size(a, M), Val{N}))
```
Comment (timholy) [inline base/array.jl]: If a function like this one was not detected as convergent, will this likely wreak havoc among packages that used any kind of lispy recursion?

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Review by martinholters — COMMENTED** [review]
Ok, not the time/patience to work through the details here, I admit.

But if I understand correctly, this would not yet solve the evil case of https://github.com/JuliaLang/julia/issues/21244#issuecomment-292551930, or does it? Would imposing an additional limit on the recursion depth, independent of type complexity, be feasible and reasonable?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21933#issuecomment-302344168) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2aa6d94539c60eb1976c35d6e4b4f15843f5b2ef/ef67986_vs_259daca/report.md). cc @jrevels

File: base/linalg/dense.jl [hunk 5]
```diff
@@ -653,12 +653,15 @@ function inv(A::StridedMatrix{T}) where T
...
+        Ai = convert(typeof(parent(Ai)), Ai)
     elseif istril(AA)
         Ai = inv(LowerTriangular(AA))
+        Ai = convert(typeof(parent(Ai)), Ai)
     else
         Ai = inv(lufact(AA))
+        Ai = convert(typeof(parent(Ai)), Ai)
     end
-    return convert(typeof(parent(Ai)), Ai)
+    return Ai
```
Comment (vtjnash) [inline base/linalg/dense.jl]: we eventually want inference to make this transform, but in generally it's quite difficult (and we are currently doing a pretty poor job of the generated code for this)

File: base/array.jl (hunk 4 above)
Comment (vtjnash) [inline base/array.jl]: lispy recursion is fine. This is just more concise and clear. However, collector arguments aren't allowed. Hopefully I've shown enough examples in this PR of fixing method calls of that sort.

File: base/tuple.jl (hunk 3 above)
Comment (vtjnash) [inline base/tuple.jl]: it was just for adding the inline meta (https://github.com/JuliaLang/julia/pull/21446), which the generated function can already do

**Comment by vtjnash** [comment]
@martinholters yes, this fixes all of the issues brought up in https://github.com/JuliaLang/julia/issues/21244

> Would imposing an additional limit on the recursion depth, independent of type complexity, be feasible and reasonable?

There's an existing limit on recursion depth for argument types (which also bounds the recursion depth), but the computation of it was inaccurate (leading to potentially unbounded recursion depth). This fixes the inaccuracy (demonstrated by the failures in the issue that you linked), and thus should ensure that inference will not run into infinite cases (and also generally tries to avoid very large cases).

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(["array","broadcast"], vs = ":master")`

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks([["array"],["broadcast"]], vs = ":master")`

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("array", "broadcast", vs = ":master")`

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks("array" || "broadcast", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21933#issuecomment-302534411) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/81d609d5f0da20359418f10e09257a1bcac45bd4/028a1cb_vs_6ba63e5/report.md). cc @jrevels

File: base/abstractarray.jl [hunk 6]
```diff
@@ -1160,30 +1158,32 @@ cat_similar(A::AbstractArray, T, shape) = similar(A, T, shape)
...
-@inline _cshp(dims, out, shape, ::Tuple{}) =
-    _cshp(tail(dims), (out..., shape[1] + dims[1]), tail(shape), ())
-@inline _cshp(dims, out, ::Tuple{}, nshape) =
-    _cshp(tail(dims), (out..., nshape[1]), (), tail(nshape))
-@inline function _cshp(::Tuple{}, out, shape, ::Tuple{})
-    _cs(length(out) + 1, false, shape[1], 1)
-    _cshp((), (out..., 1), tail(shape), ())
+_cshp(ndim::Int, ::Tuple{}, ::Tuple{}, ::Tuple{}) = ()
+_cshp(ndim::Int, ::Tuple{}, ::Tuple{}, nshape) = nshape
+_cshp(ndim::Int, dims, ::Tuple{}, ::Tuple{}) = (map(b -> 1, dims)...)
```
Comment (pabloferz) [inline base/abstractarray.jl]: I believe that the splatting can be avoided here (being `dims` a tuple). So just `map(b -> 1, dims)` should do.

File: base/tuple.jl [hunk 7]
```diff
@@ -126,36 +127,11 @@ function _ntuple(f, n)
...
-# Build up the output until it has length N
-_ntuple(out::NTuple{N,Any}, f::F, ::Type{Val{N}}) where {F,N} = out
-function _ntuple(out::NTuple{M,Any}, f::F, ::Type{Val{N}}) where {F,N,M}
-    @_inline_meta
-    _ntuple((out..., f(M+1)), f, Val{N})
-end
+# inferrable ntuple (enough for bootstrapping)
+ntuple(f, ::Type{Val{0}}) = ()
+ntuple(f::F, ::Type{Val{1}}) where {F} = (@_inline_meta; (f(1),))
+ntuple(f::F, ::Type{Val{2}}) where {F} = (@_inline_meta; (f(1), f(2)))
```
Comment (TotalVerb) [inline base/tuple.jl]: Since these functions are called, why is the specialization-forcing needed?

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21933#issuecomment-302758702) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b980abf1a2a505c071a29fc23d6e36c75333df82/b3d9f6c_vs_0663c4f/report.md). cc @jrevels

**Comment by martinholters** [comment]
The AppVeyor failure looks real, but it's a bit strange that inference should be platform and OS specific. But unless I missed something, only `sparse/higherorderfns` and `arrayops` ran on the same worker as the failing `numbers` test, and running only these three tests (on one worker) works fine for me locally, so it doesn't look like a inter-test dependency. Ideas?

**Comment by vtjnash** [comment]
I'm not sure of the specifics, but that method may be annotated incorrectly (will be fixed by https://github.com/JuliaLang/julia/pull/21771/files#diff-e7776a0970cdf71c5c96557db2986f86L315).

File: base/inference.jl [hunk 8]
```diff
@@ -736,6 +747,174 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
...
+    return r
+end
+
+function type_more_complex(t::ANY, c::ANY, sources::SimpleVector)
+    if isa(c, TypeVar)
+        if isa(t, TypeVar)
+            return type_more_complex(t.ub, c.ub, sources) ||
+                   type_more_complex(t.lb, c.lb, sources);
```
Comment (tkelman) [inline base/inference.jl]: unnecessary semicolons

File: base/inference.jl [hunk 9]
```diff
@@ -736,6 +747,174 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
...
+        if isa(c, DataType)
+            tP = t.parameters
+            isempty(tP) && return false
+            if t.name === c.name
+                cP = c.parameters
+                length(tP) > length(cP) && return true
+                for i = 1:length(tP)
+                    type_more_complex(tP[i], cP[i], sources) && return true
+                end
+            else # allow deviation in the type name, if all of it's parameters came from the sources
```
Comment (tkelman) [inline base/inference.jl]: its

File: base/inference.jl [hunk 10]
```diff
@@ -736,6 +747,174 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
...
+    t === c && return t # quick egal test
+    isa(t, Type) && isa(c, Type) && c <: t && return t # t is already wider than the comparison
+    let baset = unwrap_unionall(t)
+        for s in sources
+            is_derived_type(baset, s) && return t # t isn't something new
+        end
+    end
+    if isa(t, TypeVar)
+        if isa(c, TypeVar)
+            if t.ub === c.ub && t.lb === c.ub
```
Comment (tkelman) [inline base/inference.jl]: Is it intentional that this is comparing a lower bound to an upper bound, when everywhere else upper is compared to upper and lower is compared to lower? If so, could really use a comment explaining why.
If not intentional and this is a typo, if it passes tests then that's indicative of missing coverage.

File: base/inference.jl [hunk 11]
```diff
@@ -1289,133 +1494,140 @@ function abstract_call_gf_by_type(f::ANY, atype::ANY, sv::InferenceState)
...
-                allsame = true
-                # allow specializing on longer arglists if all the trailing
-                # arguments are the same, since there is no exponential
-                # blowup in this case.
-                for i = (lsig + 2):ls
-                    if sigtuple.parameters[i] != fst
-                        allsame = false
-                        break
+        # TODO: FIXME: this heuristic depends on non-local state making type-inference unpredictable
+        # it also should to be integrated into the cycle resolution and iterated to convergence
```
Comment (tkelman) [inline base/inference.jl]: should be integrated

File: base/inference.jl [hunk 12]
```diff
@@ -1566,6 +1778,9 @@ function abstract_apply(aft::ANY, fargs::Vector{Any}, aargtypes::Vector{Any}, vt
     return res
 end
 
+# TODO: this function is a very buggy and poor model of the return_type function
+# since abstract_call_gf_by_type is a very inaccurate model of _method and of typeinf_type,
+# while this assumes that it is an exact of both
```
Comment (tkelman) [inline base/inference.jl]: exact what of both?

**Comment by martinholters** [comment]
CI failures seem to be related to this:
```julia
julia> bar(::Type{T}, y::Type{S}) where {T,S} = promote_type(T,S)
bar (generic function with 1 method)

julia> @code_warntype bar(Int64, Int128)
Variables:
  #self#::#bar
  #unused#::Any
  y::Any

Body:
  begin
      return $(Expr(:invoke, MethodInstance for promote_result(::Type{Int64}, ::Type{Int128}, ::Type{Union{}}, ::Type{Int128}), :(Base.promote_result), Int64, Int128, Union{}, Int128))::Any
  end::Any

julia> @code_warntype promote_type(Int64, Int128)
Variables:
  #self#::Base.#promote_type
  #unused#@_2::Any
  #unused#@_3::Any

Body:
  begin
      #= line 161 =#
      return Int128
  end::Type{Int128}

julia> @code_warntype bar(Int64, Int128)
Variables:
  #self#::#bar
  #unused#::Any
  y::Any

Body:
  begin
      return Int128
  end::Type{Int128}
```
(which affects `promote` and hence makes basic arithmetic operations non-inferable).

File: base/inference.jl [hunk 13]
```diff
@@ -1428,35 +1655,57 @@ function abstract_call_method(method::Method, f::ANY, sig::ANY, sparams::SimpleV
...
-            allsame = true
-            # allow specializing on longer arglists if all the trailing
-            # arguments are the same, since there is no exponential
-            # blowup in this case.
-            for i = (lsig + 2):ls
-                if sigtuple.parameters[i] != fst
-                    allsame = false
-                    break
+        # TODO: FIXME: this heuristic depends on non-local state making type-inference unpredictable
+        # it also should to be integrated into the cycle resolution and iterated to convergence
```
Comment (tkelman) [inline base/inference.jl]: should be integrated

File: base/multidimensional.jl [hunk 14]
```diff
@@ -450,31 +446,26 @@ _maybe_reshape(::IndexCartesian, A::AbstractVector, I...) = A
...
-    quote
-        # This is specifically not inlined to prevent exessive allocations in type unstable code
-        @nexprs $N d->(I_d = I[d])
-        shape = @ncall $N index_shape I
-        dest = similar(A, shape)
-        map(unsafe_length, indices(dest)) == map(unsafe_length, shape) || throw_checksize_error(dest, shape)
-        @ncall $N _unsafe_getindex! dest A I
-    end
+function _unsafe_getindex(::IndexStyle, A::AbstractArray, I::Vararg{Union{Real, AbstractArray}, N}) where N
+    # This is specifically not inlined to prevent exessive allocations in type unstable code
```
Comment (tkelman) [inline base/multidimensional.jl]: pre-existing typo, but should be "excessive"

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by vtjnash** [comment]
Thank you @martinholters, that was very, very helpful. I've incorporated changes to the type_more_complex that I think should help it always avoid that case, be more correct, and do better in general.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21933#issuecomment-306365606) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/fb6bb8a434bf4a2eb67bdda0a45d4c03637c3759/2062122_vs_5aa15ff/report.md). cc @jrevels

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21933#issuecomment-306648202) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/65b01beaac0c2e1e2bc79ef546d6503f8a74999c/c6f3d48_vs_285ec1f/report.md). cc @jrevels

**Comment by vtjnash** [comment]
The CI failure appears to have been a github networking issue (after test completion) and the benchmarks are just showing the usual noisy culprits, so this should be all set for merging.

File: base/inference.jl [hunk 15]
```diff
@@ -737,6 +752,244 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
     return R
 end
 
+function limit_type_size(t::ANY, compare::ANY, source::ANY)
```
Comment (martinholters) [inline base/inference.jl]: Could use a comment what this does, especially what the `source` parameter is about. Reading this diff top to bottom, it took me a while to figure it out...

**Review by martinholters — COMMENTED** [review]
Remarks to `type_more_complex` apply to `_limit_type_size` as well.
In general, that these two functions are so similar (with respect to the conditions) makes me feel a little uneasy. I imagine that they should always be changed in lockstep, such that `type_mode_complex(t, ...)` iff `_limit_type_size(t, ...) != t`? Seems likely to be broken eventually.

**Comment by timholy** [comment]
Might see if this closes #20714.

**Comment by martinholters** [comment]
@timholy Looks like it does. Didn't try the OP case there, but the two reduced ones from the comments are fixed by this.

**Comment by timholy** [comment]
Awesome. To help organize things I just tagged a couple of other old issues I'd filed (#17278, #16122, #21449) with an "inference" label.

**Comment by vtjnash** [comment]
@timholy thanks. It fixed at least two of those. I think StaticArrays may have already addressed one of them and I recall not being able to reproduce the ArrayIteration one.

**Comment by vtjnash** [comment]
> I imagine that they should always be changed in lockstep, such that type_more_complex(t, ...) iff _limit_type_size(t, ...) != t?

Splitting this allows being more lenient about what is considered a more complex type, while being faster at converging when hitting the limit.

They often do get edited in lockstep, but it don't think they require much mutual agreement. They both must independently be monotonic over the type lattice, but I think that it requires remarkably little coordination between them to achieve this (indeed, they actually don't coordinate very much right now). Since `type_more_complex` runs first, it just needs to be monotonic and self-consistent. Then `_limit_type_size` can make or not make a change that `type_more_complex` disagrees with, as long as `_limit_type_size` itself converges to a fixed point when run iterative over the type it returns (aka is monotonic). This is perhaps also similar to how `type_depth` / `limit_type_depth` are paired.

For a simple concrete example, lets say we are operating only over the positive integers. And lets say `more-complex` considers complexity to be `t <= c` (e.g. monotonically decreasing). And lets say `type-size` considers complexity to be `!(t > 10)` (e.g. finite set). Clearly these disagree about what types are permitted to ensure convergence. However, since the domain of the disagreement is finite, convergence of inference in this case is nevertheless assured. I think that this shows that since both `more-complex` and `type-size` return false for a finite set of types (given `c`), the intersection of those sets must also be finite.

Thus while we could assert either of:
```
@assert !type_more_complex(t, r, source, TUPLE_COMPLEXITY_LIMIT_DEPTH)
@assert !type_more_complex(r, compare, source, TUPLE_COMPLEXITY_LIMIT_DEPTH)
```
I don't think either condition is actually necessary. But I'm not entirely convinced of this yet, let me know if you have better counter-examples.

File: base/inference.jl [hunk 16]
```diff
@@ -737,6 +752,244 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
...
+        if isa(t, TypeVar)
+            return !(t.lb === Union{} || t.lb === c.lb) || # simplify lb towards Union{}
+                   type_more_complex(t.ub, c.ub, sources, tupledepth)
+        end
+        c.lb === Union{} || return true
+        return type_more_complex(t, c.ub, sources, max(tupledepth, 1)) # allow replacing a TypeVar with a concrete value
+    elseif isa(c, Union)
+        if isa(t, Union)
+            return type_more_complex(t.a, c.a, sources, tupledepth) ||
+                   type_more_complex(t.b, c.b, sources, tupledepth)
```
Comment (martinholters) [inline base/inference.jl]: Ah yes, makes sense.

**Comment by vtjnash** [comment]
CI succeed, it just timed out while trying to handle the cache afterwards :/. Anyways, I think this is gtg.

**Comment by martinholters** [comment]
There is also this in the Travis job that later timed out:
```
EOFError()EOFError()EOFError(CapturedException()CapturedException(CapturedException(EOFError(), EOFError(), EOFError(), EOFError(Any[)Any[CapturedException(Any[(EOFError((), (unsafe_readunsafe_readunsafe_read(::Any[(::(Base.AbstractIOBuffer{Array{UInt8,::1}}, ::Ptr{UInt8}, ::UInt32) at iobuffer.jl:105, 1), (unsafe_read(::TCPSocket, ::Ptr{UInt8}, ::UInt32) at stream.jl:752, 1), (unsafe_read(::TCPSocket, ::Base.RefValue{Base.NTuple{AbstractIOBuffer{Array{UInt8,1}}, ::Ptr{UInt8}, ::UInt324,Int32}}, ::Int32) at io.jl:362, 1), () at iobuffer.jl:105, 1), (unsafe_read(::TCPSocket, ::Ptr{UInt8}, ::UInt32) at stream.jl:752, 1), (unsafe_read(::TCPSocket, ::Base.RefValue{NTuple{(Base.4,Int32}}, ::Int32) at io.jl:362, 1), (read at io.jl:364 [inlined], 1), (deserialize_hdr_raw at messages.jl:170 [inlined], 1), (message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:157, 1), (process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:118, 1), (AbstractIOBuffer{Array{UInt8,1}}, ::Ptr{UInt8}, ::UInt32) at iobuffer.jl:105, 1), (unsafe_read(::TCPSocket, ::Ptr{UInt8}, ::UInt32) at stream.jl:752, 1), (unsafe_read(::TCPSocket, ::Base.RefValue{NTuple{read at io.jl:364 [inlined], 1), (deserialize_hdr_raw at messages.jl:170 [inlined], 1), (message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:157, 1), (process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:118, 1), (4,Int32(::Base.Distributed.##99#100{TCPSocket,TCPSocket,Bool})() at event.jl:73, 1)])

Process(32) - Unknown remote, closing connection.

(::Base.Distributed.##99#100{TCPSocket,TCPSocket,Bool})() at event.jl:73, 1)])

Process(34) - Unknown remote, closing connection.

unsafe_read(::Base.AbstractIOBufferEOFError()CapturedException(EOFError(), Any[(unsafe_read(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Ptr{UInt8}, ::UInt32) at iobuffer.jl:105, 1), (unsafe_read(::TCPSocket, ::Ptr{UInt8}, ::UInt32) at stream.jl:752, 1), (unsafe_read(::TCPSocket, ::Base.RefValue{NTuple{4,Int32}}, ::Int32) at io.jl:362, 1), (read at io.jl:364 [inlined], 1), (deserialize_hdr_raw at messages.jl:170 [inlined], 1), (message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:157, 1), (process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:118, 1), ((::Base.Distributed.##99#100{TCPSocket,TCPSocket,Bool})() at event.jl:73, 1)])

Process(34) - Unknown remote, closing connection.
```
Likely unrelated, but I've restarted the job, old log back up [here](https://gist.github.com/martinholters/a9d5c919d47f6b20e54eb8290d52fd25).

**Comment by martinholters** [comment]
Hm, that error message is logged again, but it doesn't make the tests fail, and it appears in other PRs, too, so shouldn't stop this, but if anyone can shed some light on what's going on, that would be appreciated.

Meanwhile, I'm merging this.

**Comment by amitmurthy** [comment]
Seems like it is artifact of the topology tests run as part of the distributed test. I'll take a look, doesn't seem to be an issue on OSX though.

**Comment by amitmurthy** [comment]
I am not seeing it with the nightly build on Anubis. Don't have ready access to any other Linux machine....

File: base/inference.jl [hunk 17]
```diff
@@ -778,6 +793,253 @@ function limit_type_depth(t::ANY, d::Int, cov::Bool, vars::Vector{TypeVar}=TypeV
...
+            isgenerator = (t.name.name === :Generator && t.name.module === _topmod(t.name.module))
+            for i = 1:length(tP)
+                tPi = tP[i]
+                cPi = cP[i + ntail]
+                if isgenerator
+                    let tPi = unwrap_unionall(tPi),
+                        cPi = unwrap_unionall(cPi)
+                        if isa(tPi, DataType) && isa(cPi, DataType) &&
+                                !tPi.abstract && !cPi.abstract &&
+                                sym_isless(cPi.name.name, tPi.name.name)
```
Comment (JeffBezanson) [inline base/inference.jl]: This looks like it could lead to really unpredictable effects.

I also think `type_more_complex` and `is_derived_type` could use a whole bunch of unit tests, mostly as examples illustrating what they do.
