### PR TITLE
Prevent update_julia_type from creating a broken cgval_t.

### LINKED ISSUE #48394: Regression in getfield inference breaks OrdinaryDiffEq
The OrdinaryDiffEq.jl tests have recently been starting to fail, as seen on PkgEval: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-01/22/OrdinaryDiffEq.primary.log

```
[18] signal (11.1): Segmentation fault
in expression starting at /home/pkgeval/.julia/packages/OrdinaryDiffEq/W2xe3/test/interface/composite_algorithm_test.jl:21
maybe_bitcast at /cache/build/default-amdci4-3/julialang/julia-master/src/cgutils.cpp:516 [inlined]
emit_unbox at /cache/build/default-amdci4-3/julialang/julia-master/src/intrinsics.cpp:401
```

The cause seems to be an invalid `cgval_t` that codegen stumbles on:

```
(rr) p val
$21 = {V = 0x0, Vboxed = 0x0, TIndex = 0x0, constant = 0x0, typ = 0x7f7ad6e59b70 <jl_system_image_data+85502064>, isboxed = false, isghost = false, tbaa = 0x267fe58, promotion_point = 0x0, promotion_ssa = -1}
(rr) call jl_(val.typ)
Bool
```

This is a non-ghost value with type `Bool`, but doesn't have an LLVM value, which is invalid AFAIK.
The SSA value comes from an `invoke` to `getproperty`:

`emit_ssaval_assign`:
```
(rr) call jl_(r)
Expr(:invoke, getproperty(OrdinaryDiffEq.Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, Symbol) from getproperty(Any, Symbol), SSAValue(846), SSAValue(849), :(:lazy))
```

Inference knows that the `lazy` field returns a Bool (through const-prop, I assume), but codegen somehow doesn't consider the `lazy` field:

`emit_invoke` -> `emit_call_specfun_other`:
```
(rr) call jl_(inferred_retty)
Bool

(rr) call jl_(jlretty)
Union{typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}
```

As a result, `emit_call_specfun_other` thinks this returns a ghost value:

```
(rr) p *cc
$44 = jl_returninfo_t::Ghosts
(rr) p retval
$45 = {V = 0x0, Vboxed = 0x0, TIndex = 0x0, constant = 0x0, typ = 0x7f7ad6e5b6a0 <jl_system_image_data+85509024>, isboxed = false, isghost = true, tbaa = 0x0, promotion_point = 0x0, promotion_ssa = -1}
(rr) call jl_(retval.typ)
Union{}
```

... which then gets poisoned by `update_julia_type`, adding back the `Bool` from inference:

```
Run till exit from #0  emit_call_specfun_other
Value returned is $47 = {V = 0x0, Vboxed = 0x0, TIndex = 0x0, constant = 0x0, typ = 0x7f7ad6e59b70 <jl_system_image_data+85502064>, isboxed = false, isghost = false, tbaa = 0x267fe58, promotion_point = 0x0, promotion_ssa = -1}
(rr) call jl_($47.typ)
Bool
```

As codegen gets the return type by looking in the cache, I guess we're inferring & caching a bad code instance for this `getproperty` method?

---

MWE:

```julia
using OrdinaryDiffEq, ODEProblemLibrary, LinearAlgebra, DiffEqBase, DataStructures

choice_function(integrator) = (Int(integrator.t < 0.5) + 1)
code_llvm(OrdinaryDiffEq.perform_step!, Tuple{OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}, OrdinaryDiffEq.Vern7{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}}, typeof(choice_function)}, true, Array{Float64, 2}, Nothing, Float64, Float64, Float64, Float64, Float64, Float64, Array{Array{Float64, 2}, 1}, SciMLBase.ODESolution{Float64, 3, Array{Array{Float64, 2}, 1}, Array{Array{Float64, 2}, 1}, Base.Dict{Symbol, Float64}, Array{Float64, 1}, Array{Array{Array{Float64, 2}, 1}, 1}, SciMLBase.ODEProblem{Array{Float64, 2}, Tuple{Float64, Float64}, true, Float64, SciMLBase.ODEFunction{true, SciMLBase.FullSpecialize, ODEProblemLibrary.var"#6#7", LinearAlgebra.UniformScaling{Bool}, ODEProblemLibrary.var"#8#9", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}, OrdinaryDiffEq.Vern7{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}}, typeof(choice_function)}, OrdinaryDiffEq.CompositeInterpolationData{SciMLBase.ODEFunction{true, SciMLBase.FullSpecialize, ODEProblemLibrary.var"#6#7", LinearAlgebra.UniformScaling{Bool}, ODEProblemLibrary.var"#8#9", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Array{Array{Float64, 2}, 1}, Array{Float64, 1}, Array{Array{Array{Float64, 2}, 1}, 1}, OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Tsit5Cache{Array{Float64, 2}, Array{Float64, 2}, Array{Float64, 2}, OrdinaryDiffEq.Tsit5ConstantCache{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}, OrdinaryDiffEq.Vern7Cache{Array{Float64, 2}, Array{Float64, 2}, Array{Float64, 2}, OrdinaryDiffEq.Vern7Tableau{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}}, typeof(choice_function)}}, DiffEqBase.DEStats, Array{Int64, 1}}, SciMLBase.ODEFunction{true, SciMLBase.FullSpecialize, ODEProblemLibrary.var"#6#7", LinearAlgebra.UniformScaling{Bool}, ODEProblemLibrary.var"#8#9", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Tsit5Cache{Array{Float64, 2}, Array{Float64, 2}, Array{Float64, 2}, OrdinaryDiffEq.Tsit5ConstantCache{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}, OrdinaryDiffEq.Vern7Cache{Array{Float64, 2}, Array{Float64, 2}, Array{Float64, 2}, OrdinaryDiffEq.Vern7Tableau{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}}, typeof(choice_function)}, OrdinaryDiffEq.DEOptions{Float64, Float64, Float64, Float64, OrdinaryDiffEq.PIController{Base.Rational{Int64}}, typeof(DiffEqBase.ODE_DEFAULT_NORM), typeof(LinearAlgebra.opnorm), Nothing, SciMLBase.CallbackSet{Tuple{}, Tuple{}}, typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), DataStructures.BinaryHeap{Float64, DataStructures.FasterForward}, DataStructures.BinaryHeap{Float64, DataStructures.FasterForward}, Nothing, Nothing, Int64, Tuple{}, Tuple{}, Tuple{}}, Array{Float64, 2}, Float64, Nothing, OrdinaryDiffEq.DefaultInit}, OrdinaryDiffEq.Vern7Cache{Array{Float64, 2}, Array{Float64, 2}, Array{Float64, 2}, OrdinaryDiffEq.Vern7Tableau{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.False())}, Bool})
```

Gotta love those SciML types 😅 

---

Bisected to #48203, cc @keno @aviatesk 

```
e3979486a28d126b642d9c20afb2adb2982c297f is the first bad commit
commit e3979486a28d126b642d9c20afb2adb2982c297f
Author: Keno Fischer <keno@juliacomputing.com>
Date:   Mon Jan 9 22:35:45 2023 +0000

    effects: Refine effects for getfield of unknown field

    When all fields are known initialized syntactically, we do not
    need to test whether accessing the fields will give an UndefRef.
    We only need to check for the fields that are not syntactically
    known to be initialized.

    As a result, this commit improves `:consistent`-cy of `getfield` call,
    which is better in general but leads to inference/inlining accuracy
    regression in some edge cases because now irinterp is enabled on more
    frames. There are two regressions, but we are fine with them so we
    modify the test cases:
    - inlining regression: irinterp ends up some extra junk basic blocks,
      that LLVM can optimize away down the road.
    - inference regressions: these regressions are all related to the
      `MustAlias` lattice extension, which was added for JET's use case
      especially and not enabled in base yet. Since JET doesn't enable
      irinterp, this commit marks the regressed cases as broken.

 base/compiler/tfuncs.jl    |  2 +-
 test/compiler/effects.jl   | 16 +++++++++++++---
 test/compiler/inference.jl |  6 +++---
 test/compiler/inline.jl    | 10 ++++------
 4 files changed, 21 insertions(+), 13 deletions(-)
bisect run success
```

### PR DESCRIPTION
**Pull request by maleadt**
When then incoming value is a union without any non-ghost component, we cannot update it with a non-ghost type.

Closes https://github.com/JuliaLang/julia/issues/48394 (confirmed that it works with the OrdinaryDiffEx MWE), fix by @vtjnash

### CODE REVIEW

**Comment by Keno** [comment]
Can we get a standalone test case?

**Comment by maleadt** [comment]
I'm not sure how. I can create a testcase for the IR change, but can't get codegen to trigger an invalid use of the value:

```julia
struct Vern7
    x::Nothing
    y::Bool
end

struct Tsit5
    x::Nothing
end

function f(a, b, i)
    c = i ? a : b
    c.y
end

Base.code_ircode(f, Tuple{Vern7, Tsit5, Bool})
```

As expected, `invoke %7(%9::Tsit5, :y::Symbol)::Bool` on master, `Base.getfield(%8, :y)::Union{}` on 1.9.

**Review by vtjnash — APPROVED** [review]

**Review by Keno — APPROVED** [review]

File: test/compiler/codegen.jl [hunk 1]
```diff
@@ -804,3 +804,19 @@ function f34459(args...)
...
+end
+struct Y48394
+    x::Nothing
+    z::Missing
+end
+function F48394(a, b, i)
+    c = i ? a : b
+    c.y
+end
+@test !occursin("llvm.trap", get_llvm(F48394, Tuple{X48394, Y48394, Bool}))
```
Comment (Keno) [inline test/compiler/codegen.jl:822]: I do in general also like calling these functions in addition to the codegen test, just to make sure the test itself is good and doesn't bitrot, but I don't want to hold up this PR further.

Comment (maleadt) [reply test/compiler/codegen.jl:822]: Good idea, I'll add it; I messed up the test so this needs a fix anyway.

**Review by Keno — APPROVED** [review]
