### PR TITLE
fix #22032, `for f() in 1:10 ...`

### LINKED ISSUE #22032: Using function as for loop variable causes a segfault
Ref. https://github.com/JuliaLang/julia/issues/21944#issuecomment-303334726

```
julia> for f() in 1:10; f(); end # need to call the function to trigger segfault

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
jl_f_getfield at src/builtins.c:599
f at ./<missing>:0
unknown function (ip: 0x7f8b4bc3e25f)
jl_call_fptr_internal at src/julia_internal.h:348 [inlined]
jl_call_method_internal at src/julia_internal.h:367 [inlined]
jl_apply_generic at src/gf.c:1923
macro expansion at ./REPL[0]:1 [inlined]
anonymous at ./<missing> (unknown line)
jl_call_fptr_internal at src/julia_internal.h:348 [inlined]
jl_call_method_internal at src/julia_internal.h:367 [inlined]
jl_toplevel_eval_flex at src/toplevel.c:587
jl_toplevel_eval_in at src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7f8b6a25ad6f)
jl_call_fptr_internal at src/julia_internal.h:348 [inlined]
jl_call_method_internal at src/julia_internal.h:367 [inlined]
jl_apply_generic at src/gf.c:1923
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7f8b6a2e631f)
jl_call_fptr_internal at src/julia_internal.h:348 [inlined]
jl_call_method_internal at src/julia_internal.h:367 [inlined]
jl_apply_generic at src/gf.c:1923
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x7f8b4bc3936f)
jl_call_fptr_internal at src/julia_internal.h:348 [inlined]
jl_call_method_internal at src/julia_internal.h:367 [inlined]
jl_apply_generic at src/gf.c:1923
jl_apply at src/julia.h:1422 [inlined]
start_task at src/task.c:267
unknown function (ip: 0xffffffffffffffff)
```

I guess the construct should just error. The alternative would be that `f` gets redefined in every loop iteration, but that redefinition would not be visible inside the loop (same world age). Does not seem especially useful.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -539,6 +539,19 @@ end
 @test a[2](10) == 12
 @test a[3](10) == 13
 
+# issue #22032
+let a = []
+    for f() in 1:3
+        push!(a, f())
+    end
+    @test a == [1,2,3]
+end
```
Comment (StefanKarpinski) [inline test/core.jl]: Maybe also this test:

```jl
let a = []
    for f() in 1:3
        push!(a, f)
    end
    @test [f() for f in a] == [1,2,3]
end
```

Just to make sure that the closure capture is working as it should.
