### PR TITLE
fix jl_isa optimization

### LINKED ISSUE #21271: Segfault on tuple-type return type declaration
This code didn't segfault on 0.5. (I know --- this isn't correct Julia; #11535, #10947)

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.beta.15 (2017-04-04 12:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 18e864b828 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> foo()::Tuple{Type{Int}, Type{Float64}} = (Int, Float64)
foo (generic function with 1 method)

julia> foo()

signal (4): Illegal instruction: 4
while loading no file, in expression starting on line 0
foo at ./<missing>:0
unknown function (ip: 0x31ab5970f)
do_call at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:75
eval at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:242
jl_interpret_toplevel_expr at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:34
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:577
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/builtins.c:484
eval at ./boot.jl:235
jlcall_eval_18129 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x31ab55976)
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x31ab5074f)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1416 [inlined]
start_task at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:261
Allocations: 1432893 (Pool: 1431447; Big: 1446); GC: 0
Illegal instruction: 4
```

It might be because `convert` returns a value of the "wrong" type; `T = Tuple{Type{Int}}; convert(T, (Int,))::T` is an error.

### PR DESCRIPTION
**Pull request by vtjnash**
isa<Constant> was catching icmp instructions with constant operands, which can happen with two leaf types with a non-empty intersection, i.e. Tuple{DataType} and Tuple{Type{Int}}.

### CODE REVIEW

File: src/cgutils.cpp [hunk 1]
```diff
@@ -941,13 +941,46 @@ static void emit_type_error(const jl_cgval_t &x, Value *type, const std::string
...
+    }
+    else if (type == jl_bottom_type) {
+        return false;
+    }
+    else if (jl_is_type_type(type)) {
+        return false;
+    }
+    else if (jl_is_uniontype(type)) {
+        jl_uniontype_t *u = (jl_uniontype_t*)type;
+        return verify_type_is_constructable(u->a) && verify_type_is_constructable(u->b);
```
Comment (JeffBezanson) [inline src/cgutils.cpp]: I think this would have to be `||` instead of `&&`. I also think this whole function should not be necessary; we can leave these cases to constant folding and `jl_isa`.

File: src/cgutils.cpp [hunk 2]
```diff
@@ -941,13 +941,46 @@ static void emit_type_error(const jl_cgval_t &x, Value *type, const std::string
...
+            if (!verify_type_is_constructable(jl_svecref(tt, i)))
+                return false;
+        }
+        return true;
+    }
+    else if (type == jl_bottom_type) {
+        return false;
+    }
+    else if (jl_is_type_type(type)) {
+        return false;
```
Comment (JeffBezanson) [inline src/cgutils.cpp]: This doesn't look right --- isn't this saying that `x isa Type{...}` is always false?

File: src/cgutils.cpp (hunk 1 above)
Comment (vtjnash) [inline src/cgutils.cpp]: Oops, yes this needs ternary logic here (to detect the cases where jl_subtype doesn't imply jl_isa – which could be either false positive or false negative).

**Review by JeffBezanson — APPROVED** [review]
