### PR TITLE
`load_library()` panics on errors when `err=0`

### LINKED ISSUE #47027: Better error messages when `libjulia-codegen` fails to load
In https://github.com/JuliaLang/julia/pull/41936 we added the ability to run Julia without codegen linked in to the process, to make it easier to separate codegen from the rest of the runtime, for use in situations where we actually don't want the ability to generate new code.  Unfortunately, our loader mechanism can currently get confused between the case where `libjulia-codegen` is missing (and therefore should not be linked in), and the case where `libjulia-codegen` fails to load due to some error.  We need to disambiguate these two cases, and only optimistically continue execution if `libjulia-codegen` is actually missing from the `lib/julia` folder.

The current behavior is that [`cli/loader_lib.c` attempts to load `libjulia-codegen`](https://github.com/JuliaLang/julia/blob/fcdc5bc21296520c04349c901e234477c5e2ffad/cli/loader_lib.c#L207-L219), and if it fails, it always tries to continue in codegen-less mode (which apparently doesn't work that well on 1.8.X).

I suggest we try to `access()` our libjulia-codegen path before trying to `dlopen()` it, and only enter codegen-less mode if `access()` fails.  Otherwise, `dlopen()` errors should be fatal just like for `libjulia-internal`.

### PR DESCRIPTION
**Pull request by apaz-cli**
load_library with `err=0` now panics on errors, provided that the file is openable. It used to never panic on errors, leading to confusion between when cases the libjuliacodegen library had been intentionally removed and when it tried but failed to load.

Fixes #47027

### CODE REVIEW

File: cli/loader_lib.c [hunk 1]
```diff
@@ -55,19 +58,21 @@ static void * load_library(const char * rel_path, const char * src_dir, int err)
...
 #if defined(_OS_WINDOWS_)
+#define PATH_EXISTS() !_waccess(wpath, EACCES)
     wchar_t wpath[2*JL_PATH_MAX + 1] = {0};
     if (!utf8_to_wchar(path, wpath, 2*JL_PATH_MAX)) {
         jl_loader_print_stderr3("ERROR: Unable to convert path ", path, " to wide string!\n");
         exit(1);
     }
     handle = (void *)LoadLibraryExW(wpath, NULL, LOAD_WITH_ALTERED_SEARCH_PATH);
 #else
+#define PATH_EXISTS() !access(path, EACCES)
```
Comment (vtjnash) [inline cli/loader_lib.c:69]: `access` doesn't take an error code as an argument

File: cli/loader_lib.c [hunk 2]
```diff
@@ -55,19 +58,21 @@ static void * load_library(const char * rel_path, const char * src_dir, int err)
     strncat(path, rel_path, sizeof(path) - 1);
 
 #if defined(_OS_WINDOWS_)
+#define PATH_EXISTS() !_waccess(wpath, 4)
```
Comment (vtjnash) [inline cli/loader_lib.c:61]: We could use [_waccess_s](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/access-s-waccess-s?view=msvc-170) here, to check both whether the file exists (which is all that `_waccess(wpath, 4)` checks) and whether the current user has permission to read it

But I am inclined to say we should just check existence (F_OK), so that any permission errors in opening the file will get reported by `dlerror` as fatal errors for the process, as a more conservative (more noisy) default. WDYT?

Comment (apaz-cli) [reply cli/loader_lib.c:61]: It looks like the fact that `_waccess_s` exists implies that `_waccess` is deprecated. It's unclear to me how the two are different, other than that the CRT is expected to ensure that the arguments and memory are valid.

On the other point, I agree. Under the assumption that everything is installed correctly, the only way that the lib could become unreadable is if the user did something dumb. It would be better if it didn't silently break in that case.

Comment (vtjnash) [reply cli/loader_lib.c]: `_waccess` probably only checks for existence and the value of the advisory read-only flag, while `_waccess_s` checks instead the actual access permissions of the file (probably calling https://learn.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-accesscheck)

File: cli/loader_lib.c [hunk 3]
```diff
@@ -31,6 +31,9 @@ void jl_loader_print_stderr3(const char * msg1, const char * msg2, const char *
 }
 
 /* Wrapper around dlopen(), with extra relative pathing thrown in*/
+/* If err, then loads the library successfully or panics.
+ * If !err, then loads the library or returns null if it could not be opened,
+ * or panics if opening failed for any other reason. */
```
Comment (vtjnash) [inline cli/loader_lib.c:36]: can you add a comment here for future readers about why we picked F_OK?

File: cli/loader_lib.c (hunk 2 above)
Comment (vtjnash) [reply cli/loader_lib.c]: ah, shoot, this is loader_lib.c, so we don't have access to msvc here yet anyways, so that point is rather moot anyways. We need to do this the extra-hard way apparently, only using KERNEL32 to write our own `access` function:
```
$ objdump -x libjulia-internal.dll | grep 'DLL Name'
        DLL Name: libjulia.dll
        DLL Name: ADVAPI32.dll
        DLL Name: dbghelp.dll
        DLL Name: IPHLPAPI.DLL
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: ole32.dll
        DLL Name: PSAPI.DLL
        DLL Name: libwinpthread-1.dll
        DLL Name: Secur32.dll
        DLL Name: SHELL32.dll
        DLL Name: USER32.dll
        DLL Name: USERENV.dll
        DLL Name: WINMM.DLL
        DLL Name: WS2_32.dll
        DLL Name: libgcc_s_sjlj-1.dll
        DLL Name: libstdc++-6.dll
$ objdump -x libjulia.dll | grep 'DLL Name'
        DLL Name: KERNEL32.dll
```

File: cli/loader_lib.c (hunk 3 above)
Comment (apaz-cli) [reply cli/loader_lib.c:41]: Amended to elaborate.

**Comment by apaz-cli** [comment]
Removed extra whitespace that I accidentally added. Added a test, and CI is passing.

**Review by vtjnash — APPROVED** [review]

**Review by giordano — APPROVED** [review]
```console
$ julia-1.8.2/bin/julia -q

SYSTEM: caught exception of type ^C^C^C^C^C^C^CWARNING: Force throwing a SIGINT
fatal: error thrown and no exception handler available.
InterruptException()
$ julia-57f9db2279/bin/julia -q
ERROR: Unable to load dependent library /home/dc-gior1/tmp/julia-57f9db2279/bin/../lib/julia/libjulia-codegen.so.1
Message:/usr/local/software/master/gcc/8/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/dc-gior1/tmp/julia-57f9db2279/bin/../lib/julia/libjulia-codegen.so.1)
```
Much better error, yay!

**Comment by gbaraldi** [comment]
@giordano maybe this can show what's going on with windows on gcc12?

**Comment by giordano** [comment]
I was thinking (and hoping) the same!

**Comment by vtjnash** [comment]
That was the goal

**Comment by DilumAluthge** [comment]
This PR broke the x86_64-w64-mingw32 tests.

**Comment by staticfloat** [comment]
It looks to me like we might be missing a UTF16 -> UTF8 conversion somewhere.

File: cli/loader_lib.c [hunk 4]
```diff
@@ -55,19 +67,21 @@ static void * load_library(const char * rel_path, const char * src_dir, int err)
...
+#define PATH_EXISTS() !access(path, F_OK)
     handle = dlopen(path, RTLD_NOW | (err ? RTLD_GLOBAL : RTLD_LOCAL));
 #endif
-
     if (handle == NULL) {
-        if (!err)
+        if (!err && !PATH_EXISTS())
             return NULL;
+#undef PATH_EXISTS
         jl_loader_print_stderr3("ERROR: Unable to load dependent library ", path, "\n");
```
Comment (giordano) [inline cli/loader_lib.c:85]: Should use `wpath` on Windows?

**Comment by inkydragon** [comment]
```
jl_loader_print_stderr3
-> jl_loader_print_stderr
-> fputs
-> loader_fputs
-> utf8_to_wchar + fwrite
```
https://github.com/JuliaLang/julia/blob/b01fd3367b431c1882c3e4beaadc766902644264/cli/loader_win_utils.c#L27-L31


So on windows the default error message we output is wchar.
Maybe it should be converted to UTF8 when reading.

https://github.com/JuliaLang/julia/blob/b01fd3367b431c1882c3e4beaadc766902644264/test/compiler/codegen.jl#L707-L710

File: cli/loader_lib.c (hunk 4 above)
Comment (apaz-cli) [reply cli/loader_lib.c:85]: It should be utf8. The function expects it to be utf8. That it isn't is very odd, and this PR made no changes that would break that.

Comment (giordano) [reply cli/loader_lib.c:85]: Yes, but the tests introduced here triggered the error, [tests were already failing in this PR](https://buildkite.com/julialang/julia-master/builds/17576#01841ed4-f497-4e8b-98c1-f2a6fec2e9d5/592-1457), but the fact that Windows tests are allowed to fail means that the failure was overlooked

**Comment by PallHaraldsson** [comment]
Should this be reverted since causing CI errors elsewhere?
