### PR TITLE
Fix at-views for setindex expression

### LINKED ISSUE #59383: at-views macro broken for assignment
The `@views` macro should only affect "rvalue" indexing expressions, as shown in,

```julia
julia> @macroexpand @views x[a:b] = c
:(x[a:b] = c)
```

Until recently, this also works for indexing with `begin` or `end`

```julia
# Julia 1.13.0-DEV.989
julia> @macroexpand @views x[begin:end] = c
:(x[(firstindex)(x):(lastindex)(x)] = c)
```

but is broken (I assume as an side effect of #59239) now

```julia
# 1.13.0-DEV.1030
julia> @macroexpand @views x[begin:end] = c
:(begin
          local var"##S#139" = x
          #= views.jl:117 =#
          #= views.jl:117 =#
          (Base.maybeview)(var"##S#139", (firstindex)(var"##S#139"):(lastindex)(var"##S#139"))
      end = c)
```

Note that this is clearly macro hygiene related and it was also broken previously if the array object is a non-trivial expression,

```julia
# Julia 1.13.0-DEV.989
julia> @macroexpand @views f(x)[begin:end] = c
:(let var"##S#289" = f(x)
          (Base.maybeview)(var"##S#289", (firstindex)(var"##S#289"):(lastindex)(var"##S#289"))
      end = c)
```

Although it wasn't explicitly stated, the document for `@views` seems to be pretty reassuring that only expressions that is an "rvalue" array indexing will be affected so I assume array assignment should be supported (implemented as no-op). This also have real-world use https://github.com/SciML/BoundaryValueDiffEq.jl/blob/25e9002100500c527cd217d014aab19e047d1d2a/lib/BoundaryValueDiffEqFIRK/src/collocation.jl#L135 that's now broken.

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #59383

### CODE REVIEW

**Comment by yuyichao** [comment]
Note that if this is to be backported ~some additional fix may be needed. https://github.com/JuliaLang/julia/pull/58905 removed an use of the `replace_ref_begin_end_!` function outside of `views.jl` and that would need to be fixed (by appending two `false` arguments).~ This depends on https://github.com/JuliaLang/julia/pull/59239

**Comment by vtjnash** [comment]
I don't believe this is quite right. I think the intended expansion of `x[begin] = y` is `let x = x; x[length(x)] = y` ==> e.g. that the `let` should move outside of the `=` so that the lowering expansion remains valid, but still does take the view

**Comment by yuyichao** [comment]
Updated.

Should also work for other flavors of assignments now `.=`, `+=`, `.+=` etc.

I kept the way `in_quote_context` is passed around as a variable even when it's value is known.

**Comment by yuyichao** [comment]
> that the let should move outside of the = so that the lowering expansion remains valid, but still does take the view

I'm pretty sure the normal `setindex!` case should not use the view. And I don't think there is necessarily anything that needs to be done for expressions that would be lowered to just `setindex!`. This is the case even when no micro hygiene was involved on previous versions,

```julia
julia> @macroexpand @views x[a:b] = c
:(x[a:b] = c)
```

It seems that `@views` is only intended for anything that would be a `getindex` but not `setindex!` and it differentiates the two cases clearly when the expression lowers to both,

```julia
julia> @macroexpand @views x[a:b] += c
:(let var"#2#a" = x, var"#1#i1" = a:b
      var"#2#a"[var"#1#i1"] = (Base.maybeview)(var"#2#a", var"#1#i1") + c
  end)

julia> @macroexpand @views x[a:b] .+= c
:(let var"#4#a" = x, var"#3#i1" = a:b
      var"#4#a"[var"#3#i1"] .= (Base.maybeview)(var"#4#a", var"#3#i1") .+ c
  end)
```

That said, I wasn't perfectly happy with simply ignoring these cases as in the previous implementation because it's inconsistent with the function name. Also, the previous one didn't handle other flavors of assignments correctly and handling those does require the lowering style that you suggested.

File: base/views.jl [hunk 1]
```diff
@@ -46,77 +121,7 @@ function replace_ref_begin_end_!(__module__::Module, ex, withex, in_quote_contex
         end
```
Comment (vtjnash) [inline base/views.jl:121]: FWIW, this error has also always been incorrect, if the intent of this function is to predict lowering. Lowering does not consider this to be invalid, and simply skips the replacement when `withex === nothing`:
```
julia> var"begin" = var"end" = 3
3
```

File: base/views.jl [hunk 2]
```diff
@@ -132,6 +137,18 @@ function replace_ref_begin_end_!(__module__::Module, ex, withex, in_quote_contex
             escs -= 1
         elseif ex.head === :meta || ex.head === :inert
             return ex, used_withex
+        elseif !in_quote_context && last(string(ex.head)) == '=' && Meta.isexpr(ex.args[1], :ref)
+            for i = eachindex(ex.args)
+                if i == 1
+                    # we'll deal with the ref expression later
+                    continue
+                end
```
Comment (vtjnash) [inline base/views.jl:145]: Seems an odd way to deal with a binary operator being to loop from 1 to 2 skipping 1
```suggestion
            let i = 2
```

File: base/views.jl [hunk 3]
```diff
@@ -132,6 +137,18 @@ function replace_ref_begin_end_!(__module__::Module, ex, withex, in_quote_contex
             escs -= 1
         elseif ex.head === :meta || ex.head === :inert
             return ex, used_withex
+        elseif !in_quote_context && last(string(ex.head)) == '=' && Meta.isexpr(ex.args[1], :ref)
```
Comment (vtjnash) [inline base/views.jl:140]:
```suggestion
        elseif !in_quote_context && last(string(ex.head)) == '=' && Meta.isexpr(Meta.unescape(ex.args[1]), :ref)
```

File: base/views.jl [hunk 4]
```diff
@@ -132,6 +137,18 @@ function replace_ref_begin_end_!(__module__::Module, ex, withex, in_quote_contex
...
+            for i = eachindex(ex.args)
+                if i == 1
+                    # we'll deal with the ref expression later
+                    continue
+                end
+                ex.args[i], used = replace_ref_begin_end_!(__module__, ex.args[i], withex, in_quote_context, escs)
```
Comment (vtjnash) [inline base/views.jl:146]:
```suggestion
                rhs, used = reescape(replace_ref_begin_end_!(__module__, unescape(ex.args[i]), withex, in_quote_context, escs)
                ex.args[i] = reescape(rhs, ex.args[i])

```

File: base/views.jl (hunk 2 above)
Comment (yuyichao) [reply base/views.jl:145]: I was going to handle only `args[2]` here. However, the code below treated it as if there could be more than 2 argument for this expression https://github.com/JuliaLang/julia/blob/cbea8cf28e0f617333130add1c4ab2a51f6c979c/base/views.jl#L272 when it handles the generic assignment cases.

File: base/views.jl (hunk 4 above)
Comment (yuyichao) [reply base/views.jl:146]: I assume the first reescape should not be there.

Comment (yuyichao) [reply base/views.jl:146]: Also, why should the escape/unescape be done on this argument? This should just be a generic handling of the an expression just like the first argument of the :ref expression and exactly the same as the fallback case below. I assume `replace_ref_begin_end_!` is handling the escaping part correctly, else many more places would need to be fixed.

I could see though, that the first argument (the LHS) needs to be handled manually since we need to see through escape to figure out if the LHS of an assignment operator is an `Expr(:ref)`. The implementation of `@views` below doesn't seem to handle this either though, and should probably be fixed at the same time,

```julia
julia> macro views_wrapper(lhs, rhs)
           quote
               @views $(esc(lhs)) += $(esc(rhs))
           end
       end
@views_wrapper (macro with 1 method)

julia> @macroexpand @views_wrapper x[a:b] 1
quote
    #= REPL[3]:3 =#
    (Base.maybeview)(x, a:b) += 1
end
```

Comment (yuyichao) [reply base/views.jl:146]: And another issue seems to be that this function also straight up ignore escape expressions in general (unless they appears in `hygienic-scope` expressions). Shouldn't that logic only apply if the "begin"/"end" is escaped compared to the ref expression?

Basically, I feel like `esc(:(x[begin:end]))` should be processed whereas `:(x[$(esc(:(var"begin":var"end")))])` shouldn't.

Comment (vtjnash) [reply base/views.jl:146]: Yes, lots of code handles `esc` wrong. Including lowering, which considers `begin`/`end` to ignore scope (as we currently emulate here)

Comment (yuyichao) [reply base/views.jl:146]: Right now `x[esc(begin:end)]` is being lowered to `x[begin:end]`. Would this be considered a bug in the long term or is it the job of  this function to lift the begin/end out of the argument of ref?

Comment (vtjnash) [reply base/views.jl:146]: It might be considered a bug (seems unexpected anyways), but for now I think the goal is to match what lowering does, and lowering does not currently consider those to be variables (applicable to scope) but rather special syntax (nothing to escape, since it isn't a variable)

**Comment by KristofferC** [comment]
Is this good to go?

**Comment by vtjnash** [comment]
It is technically breaking (changes the meaning of begin/end in macros), but those were pretty weird anyways
