### PR TITLE
fix #26939, segfault in WeakKeyDict due to wrong finalization order

### LINKED ISSUE #26939: BigFloat stored in WeakKeyDicts cause segfaults when garbage collected
In v0.6.2

This error is similar to https://github.com/JuliaLang/julia/issues/18204#issuecomment-265679348

MWE:
```
x = WeakKeyDict()
x[big"1.0"] = 1
gc()
```

REPL:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> x = WeakKeyDict()
WeakKeyDict{Any,Any} with 0 entries

julia> x[big"1.0"] = 1
1

julia> gc()

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f33961c1a4f)
decompose at ./hashing2.jl:140
hash at ./hashing2.jl:32
hashindex at ./dict.jl:210 [inlined]
ht_keyindex at ./dict.jl:322
delete! at ./dict.jl:558 [inlined]
#333 at ./weakkeydict.jl:113
lock at ./lock.jl:101
#311 at ./weakkeydict.jl:25
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
run_finalizer at /buildworker/worker/package_linux64/build/src/gc.c:111
jl_gc_run_finalizers_in_list at /buildworker/worker/package_linux64/build/src/gc.c:200
run_finalizers at /buildworker/worker/package_linux64/build/src/gc.c:234 [inlined]
jl_gc_collect at /buildworker/worker/package_linux64/build/src/gc.c:2112
gc at ./base.jl:144
unknown function (ip: 0x7f336bfa35af)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:75
eval at /buildworker/worker/package_linux64/build/src/interpreter.c:242
jl_interpret_toplevel_expr at /buildworker/worker/package_linux64/build/src/interpreter.c:34
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:577
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7f33907cdd2f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7f339084f18f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
macro expansion at /home/uniwa/students2/students/20361362/linux/.julia/v0.6/Revise/src/Revise.jl:775 [inlined]
#17 at ./event.jl:73
unknown function (ip: 0x7f336bf9409f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 2381902 (Pool: 2380620; Big: 1282); GC: 3
Segmentation fault (core dumped)
(venv_p3) 20361362@ECM-DTC-678L:~$ 
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
This will probably be a bit slower but at least the code is shorter. And of course this doesn't handle finalizers added by different threads, but that's a different sort of problem; it might as well at least work with one thread. We could also improve the situation in the future by not using finalizers in the implementation of `WeakKeyDict`.

Fix #26939.

### CODE REVIEW

File: src/gc.c [hunk 1]
```diff
@@ -104,7 +100,10 @@ static void schedule_finalization(void *o, void *f)
 
 static void run_finalizer(jl_ptls_t ptls, jl_value_t *o, jl_value_t *ff)
 {
-    assert(!jl_typeis(ff, jl_voidpointer_type));
+    if (jl_is_cpointer(ff)) {
+        ((void (*)(void*))jl_unbox_voidpointer(ff))(o);
```
Comment (ararslan) [inline src/gc.c]: > `((void (*)(void*))`

I have never appreciated Julia more than in this moment.

File: src/gc.c [hunk 2]
```diff
@@ -55,10 +55,6 @@ pagetable_t memory_map;
 bigval_t *big_objects_marked = NULL;
 
 // finalization
-// `ptls->finalizers` and `finalizer_list_marked` might have tagged pointers.
```
Comment (yuyichao) [inline src/gc.c]: Why does the optimization has to be removed?

Comment (JeffBezanson) [reply src/gc.c]: I guess it doesn't have to be.

Comment (yuyichao) [reply src/gc.c]: The place that you need to handle tagged pointer will be [here](https://github.com/JuliaLang/julia/blob/521dec9bf4990a0ec0fb827e1167e6c5195d392d/src/gc.c#L1869).

Comment (JeffBezanson) [reply src/gc.c]: Thanks.

**Review by yuyichao — APPROVED** [review]
LGTM. I don't think there's any guarantee that we'll give here but the change in the order is ok.
