### PR TITLE
inference: SCC handling missing for return_type_tfunc

### LINKED ISSUE #39361: Regression (change) in inference after SCC PR
https://github.com/JuliaLang/julia/pull/39116 caused the following change:

```jl
julia> using MutableArithmetics

julia> MutableArithmetics.copy_if_mutable(Vector{Int}[])
Any[]
# Vector{Int64}[] before #39116
```

What is interesting is that when running it through the interpreter it still gives the older ("better") result

```jl
julia> using JuliaInterpreter

julia> @interpret MutableArithmetics.copy_if_mutable(Vector{Int}[])
Vector{Int64}[]
```

This caused a few packages to start failing in the backport branch (for example https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/7d1533d_vs_8240225/MultivariateBases.1.6.0-beta1-85c46c0116.log).

I'll put a 1.6 blocker on this for now, but I don't know if this is expected or how it should be assessed.

cc @vtjnash

### PR DESCRIPTION
**Pull request by vtjnash**
This has actually been broken for a long time, so it only got noticed
when it caused a regression.

Fixes #39361

### CODE REVIEW

File: base/compiler/tfuncs.jl [hunk 1]
```diff
@@ -1619,25 +1619,25 @@ function return_type_tfunc(interp::AbstractInterpreter, argtypes::Vector{Any}, s
                     if isa(rt, Const)
                         # output was computed to be constant
                         return Const(typeof(rt.val))
+                    end
+                    rt = widenconst(rt)
+                    if rt === Bottom || (isconcretetype(rt) && !iskindtype(rt))
+                        # output cannot be improved so it is known for certain
+                        return Const(rt)
+                    elseif !isempty(sv.pclimitations)
```
Comment (Sacha0) [inline base/compiler/tfuncs.jl:1627]: IIUC, this clause contains the only functional change (perhaps modulo some difference between `hasuniquerep(rt)` and `(isconcretetype(rt) && !iskindtype(rt))` that I'm not familiar with in the preceding conditional), adapting this code to the new limitation mechanisms? :)

**Review by Sacha0 — APPROVED** [review]
Thanks Jameson! :)

File: base/compiler/tfuncs.jl (hunk 1 above)
Comment (vtjnash) [reply base/compiler/tfuncs.jl:1627]: The other condition is arguably more functional: has `hasuniquerep` was the wrong predicate to change to in 88a4db25828, so this changes it back.

Comment (Sacha0) [reply base/compiler/tfuncs.jl:1627]: Awesome, thanks for the explanation! :)
