### PR TITLE
fix overflow in CartesianIndices iteration

### LINKED ISSUE #30998: Vectorization failure for CartesianIndices
@peterahrens send me on a goose chase, which led me down to a peculiar observation. Given a relatively simple reduction loop (intentionally not using `@simd` here):

```julia
function vecfail(A)
     @inbounds begin
         acc = zero(eltype(A))
         N = length(A)
         for I in CartesianIndices(A)
              acc = Base.FastMath.add_fast(acc, A[I])
         end
     end
     return acc
end
```

Turns into this nice loop before `loop-vectorize`, https://godbolt.org/z/aIU_3u

```llvm
; ...
L6:                                               ; preds = %L6.lr.ph, %L6
  %value_phi13 = phi i64 [ 0 , %L6.lr.ph ], [ %13, %L6 ]
  %value_phi2 = phi float [ 0.000000e+00, %L6.lr.ph ], [ %12, %L6 ]
  %9 = add i64 %value_phi13, -1
  %10 = getelementptr inbounds float, float addrspace(13)* %8, i64 %9
  %11 = load float, float addrspace(13)* %10, align 4
  %12 = fadd fast float %11, %value_phi2
  %13 = add i64 %value_phi13, 1
  ; %13 = add nsw i64 %value_phi13, 1
  %14 = icmp sgt i64 %13, %5
  ; %14 = icmp eq i64 %13, %5
  br i1 %14, label %L10, label %L6
; ...
```

If one comments out either `%14` or `%13` and uses the version below the function vectorize just find.

I came up with two fixes to Base.

#### Change `iterate`
```julia
@eval Base.IteratorsMD begin
         @inline function iterate(iter::CartesianIndices, state)
             nextstate = CartesianIndex(inc(state.I, first(iter).I, last(iter).I))
             nextstate.I[end] == (last(iter.indices[end])+1) && return nothing
             nextstate, nextstate
         end
       end
```

#### Change `inc` to use `unsafe_inc`
```julia
@eval Base.IteratorsMD begin
       function unsafe_inc(i::Int64)
                Base.llvmcall("""
                %i = add nsw i64 %0, 1
                ret i64 %i
                """, Int64, Tuple{Int64}, i)
              end
       @inline inc(state::Tuple{Int}, start::Tuple{Int}, stop::Tuple{Int}) = (unsafe_inc(state[1]),)
       @inline function inc(state, start, stop)
         if state[1] < stop[1]
           return (unsafe_inc(state[1]),tail(state)...)
         end
         newtail = inc(tail(state), tail(start), tail(stop))
         (start[1], newtail...)
       end
       end
```

It would be nice if we could convince LLVM to do this reasoning for us.
Some random data I collected as well:

```
➜  $OPT -analyze -scalar-evolution vecfailsum.opt.ll -S
Printing analysis 'Scalar Evolution Analysis' for function 'julia_vecfailsum_12014':
Classifying expressions for: @julia_vecfailsum_12014
  %1 = call %jl_value_t*** @julia.ptls_states()
  -->  %1 U: full-set S: full-set
  %2 = addrspacecast %jl_value_t addrspace(10)* %0 to %jl_value_t addrspace(11)*
  -->  %2 U: full-set S: full-set
  %3 = bitcast %jl_value_t addrspace(11)* %2 to %jl_array_t addrspace(11)*
  -->  %2 U: full-set S: full-set
  %4 = getelementptr inbounds %jl_array_t, %jl_array_t addrspace(11)* %3, i64 0, i32 1
  -->  (8 + %2)<nsw> U: full-set S: full-set
  %5 = load i64, i64 addrspace(11)* %4, align 8
  -->  %5 U: full-set S: full-set
  %7 = bitcast %jl_value_t addrspace(11)* %2 to float addrspace(13)* addrspace(11)*
  -->  %2 U: full-set S: full-set
  %8 = load float addrspace(13)*, float addrspace(13)* addrspace(11)* %7, align 8
  -->  %8 U: full-set S: full-set
  %value_phi13 = phi i64 [ 1, %L6.lr.ph ], [ %13, %L6 ]
  -->  {1,+,1}<%L6> U: full-set S: full-set		Exits: <<Unknown>>		LoopDispositions: { %L6: Computable }
  %9 = add i64 %value_phi13, -1
  -->  {0,+,1}<%L6> U: full-set S: full-set		Exits: <<Unknown>>		LoopDispositions: { %L6: Computable }
  %10 = getelementptr inbounds float, float addrspace(13)* %8, i64 %9
  -->  {%8,+,4}<%L6> U: full-set S: full-set		Exits: <<Unknown>>		LoopDispositions: { %L6: Computable }
  %13 = add i64 %value_phi13, 1
  -->  {2,+,1}<%L6> U: full-set S: full-set		Exits: <<Unknown>>		LoopDispositions: { %L6: Computable }
Determining loop execution counts for: @julia_vecfailsum_12014
Loop %L6: Unpredictable backedge-taken count. 
Loop %L6: Unpredictable max backedge-taken count. 
Loop %L6: Unpredictable predicated backedge-taken count. 

➜  $OPT -analyze -scalar-evolution vecsum.opt.ll -S
Printing analysis 'Scalar Evolution Analysis' for function 'julia_vecsum_12012':
Classifying expressions for: @julia_vecsum_12012
  %1 = call %jl_value_t*** @julia.ptls_states()
  -->  %1 U: full-set S: full-set
  %2 = addrspacecast %jl_value_t addrspace(10)* %0 to %jl_value_t addrspace(11)*
  -->  %2 U: full-set S: full-set
  %3 = bitcast %jl_value_t addrspace(11)* %2 to %jl_array_t addrspace(11)*
  -->  %2 U: full-set S: full-set
  %4 = getelementptr inbounds %jl_array_t, %jl_array_t addrspace(11)* %3, i64 0, i32 1
  -->  (8 + %2)<nsw> U: full-set S: full-set
  %5 = load i64, i64 addrspace(11)* %4, align 8
  -->  %5 U: full-set S: full-set
  %7 = bitcast %jl_value_t addrspace(11)* %2 to float addrspace(13)* addrspace(11)*
  -->  %2 U: full-set S: full-set
  %8 = load float addrspace(13)*, float addrspace(13)* addrspace(11)* %7, align 8
  -->  %8 U: full-set S: full-set
  %value_phi13 = phi i64 [ 1, %L7.lr.ph ], [ %13, %L7 ]
  -->  {1,+,1}<%L7> U: [1,0) S: [1,0)		Exits: (-1 + %5)		LoopDispositions: { %L7: Computable }
  %9 = add i64 %value_phi13, -1
  -->  {0,+,1}<%L7> U: [0,-1) S: [0,-1)		Exits: (-2 + %5)		LoopDispositions: { %L7: Computable }
  %10 = getelementptr inbounds float, float addrspace(13)* %8, i64 %9
  -->  {%8,+,4}<%L7> U: full-set S: full-set		Exits: (-8 + (4 * %5) + %8)		LoopDispositions: { %L7: Computable }
  %13 = add i64 %value_phi13, 1
  -->  {2,+,1}<%L7> U: [2,1) S: [2,1)		Exits: %5		LoopDispositions: { %L7: Computable }
Determining loop execution counts for: @julia_vecsum_12012
Loop %L7: backedge-taken count is (-2 + %5)
Loop %L7: max backedge-taken count is -2
Loop %L7: Predicated backedge-taken count is (-2 + %5)
 Predicates:

Loop %L7: Trip multiple is 1
```

### PR DESCRIPTION
**Pull request by vchuravy**
Make iteration over CartesianIndices blazing fast.
Fixes #30998, by avoiding the potential overflow.

LLVM was right..., based on the given semantics it
is not possible to determine the loop-bounds of the
loop in:

```julia
function vecfail(A)
     @inbounds begin
         acc = zero(eltype(A))
         N = length(A)
         for I in CartesianIndices(A)
              acc = Base.FastMath.add_fast(acc, A[I])
         end
     end
     return acc
end
```

Since it is possible for the iteration to overflow:

```julia-repl
julia> I = CartesianIndices(1:typemax(Int64));

julia> i= last(I)
CartesianIndex(9223372036854775807,)

julia> iterate(I, i)
(CartesianIndex(-9223372036854775808,), CartesianIndex(-9223372036854775808,))
```

### CODE REVIEW

File: base/multidimensional.jl [hunk 1]
```diff
@@ -334,9 +334,14 @@ module IteratorsMD
         iterfirst, iterfirst
     end
     @inline function iterate(iter::CartesianIndices, state)
-        nextstate = CartesianIndex(inc(state.I, first(iter).I, last(iter).I))
-        nextstate.I[end] > last(iter.indices[end]) && return nothing
-        nextstate, nextstate
+        # If we increment before the condition check, we run the
+        # risk of an integer overflow.
+        if state.I[end] < last(iter.indices[end])
```
Comment (Keno) [inline base/multidimensional.jl]: perhaps a stupid question, but doesn't this do one fewer iterations than before?

Comment (StefanKarpinski) [reply base/multidimensional.jl]: If so then we definitely need a test to catch that 😁

Comment (vchuravy) [reply base/multidimensional.jl]: xD, indeed for the ND-case this would drop the last few iterations. Added a test and @YingboMa fixed the logic.

**Comment by vchuravy** [comment]
I should add that this helps vectorize 1D CartesianIndices, but doesn't help with ND. The loop we lower two has two induction variables. instead of being a inner and a outer for-loop.

I would love for:
```julia
function vecfail(A)
            @inbounds begin
                acc = zero(eltype(A))
                for I in CartesianIndices(A)
                     acc = Base.FastMath.add_fast(acc, A[I])
                end
            end
            return acc
       end
```

to be more or less equivalent to

```julia
using Base.Cartesian
@generated function vecfail(A::AbstractArray{T, N}) where {T, N}
             quote
             @inbounds begin
                acc = zero(eltype(A))
                @nloops $N i A begin
                     acc = Base.FastMath.add_fast(acc, @nref($N, A, i))
                end
            end
            return acc
            end
       end
```

I know `eachindex` with arrays that support linear indexing will already get me there.

**Comment by vchuravy** [comment]
Ok updated once again after I realized that
```
state == last(iter) && return nothing
```

is basically equivalent to:

```
        idxend = map(last, iter.indices)
        all(map(>=, state.I, idxend)) && return nothing
```

Since the latter already accepts invalid state. I also experimented with checked arithmetic, but that didn't help with vectorisation.

**Review by timholy — COMMENTED** [review]
Nice work! I think between this suggestion and my refinement in the comment below, we may have a fix (or close to it) for #9080! That's one of the few bugs whose number I know by memory, so to me that's a big deal.

See [this gist](https://gist.github.com/timholy/ec45d4b0472e1722acc37974c37fe697) and then:
```julia
julia> includet("/tmp/iterc.jl")

julia> using BenchmarkTools

julia> @btime sumcart_manual($A)
  102.337 ms (0 allocations: 0 bytes)
5.0001993217249475e7

julia> @btime sumcart_iter($A)
  131.513 ms (0 allocations: 0 bytes)
5.0001993217249475e7

julia> @btime sumcart_newiter($A)
  105.207 ms (0 allocations: 0 bytes)
5.0001993217249475e7
```

**Comment by timholy** [comment]
With regards to the multidimensional case, note that `@simd` strips off the first dimension's iteration variable to create two loops, an outer `n-1`-dimensional iteration and an inner 1-dimensional iteration. So at least in the typical case you can vectorize across the first dimension. Would be nice to need that and get the equivalent of the `@nloops` approach.

File: base/multidimensional.jl [hunk 2]
```diff
@@ -334,9 +338,11 @@ module IteratorsMD
         iterfirst, iterfirst
     end
     @inline function iterate(iter::CartesianIndices, state)
+        # If we increment before the condition check, we run the
+        # risk of an integer overflow. This intentionally allows for invalid state.
+        state == last(iter) && return nothing
```
[the remark this answers is not in the document]
Comment (vchuravy) [reply base/multidimensional.jl]: Thanks! I went a slightly different approach that constructs the tuple in anycase and propagates a boolean to check if it is valid.

**Comment by vchuravy** [comment]
> Would be nice to need that and get the equivalent of the `@nloops` approach.

I wonder if Polly could do things like this, but right now both `-loop-analysis` and `-scalar-evolution` get confused about the 2D case. (I will punt on that though)

File: base/multidimensional.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (timholy) [reply base/multidimensional.jl]: Does this still solve #9080?

[the remark this answers is not in the document]
Comment (vchuravy) [reply base/multidimensional.jl]: :/ No.

```
julia> @benchmark sumcart_iter($A)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     190.778 ms (0.00% GC)
  median time:      191.650 ms (0.00% GC)
  mean time:        191.665 ms (0.00% GC)
  maximum time:     192.456 ms (0.00% GC)
  --------------
  samples:          27
  evals/sample:     1

julia> @benchmark sumcart_manual($A)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     102.647 ms (0.00% GC)
  median time:      103.522 ms (0.00% GC)
  mean time:        103.663 ms (0.00% GC)
  maximum time:     105.404 ms (0.00% GC)
  --------------
  samples:          49
  evals/sample:     1
```

**Comment by vchuravy** [comment]
Interesting using Tim's variant I do see a speedup 200->150, but not the same speedup as if I am using `_newiter` from the gist 200->100.

**Comment by timholy** [comment]
> but not the same speedup as if I am using _newiter from the gist 200->100

Just to check, are you saying that if you "wire this in" to `Base.iterate` and then rely on lowering to reduce the `for` loop to an `iterate` loop, it's slower than the version I produced by manual lowering? If so, what's the difference between the two `@code_lowered`s?

**Comment by vchuravy** [comment]
> Just to check, are you saying that if you "wire this in" to `Base.iterate` and then rely on lowering to reduce the `for` loop to an `iterate` loop, it's slower than the version I produced by manual lowering? If so, what's the difference between the two `@code_lowered`s?

Exactly! I rewrote the `newiter` version to match more closely what the `iter` version produces:

```julia 

using Base: tail

@inline function myiterate(iter::CartesianIndices)
    iterfirst, iterlast = first(iter), last(iter)
    if any(map(>, iterfirst.I, iterlast.I))
        return nothing
    end
    iterfirst, iterfirst
end
@inline function myiterate(iter::CartesianIndices, state)
    inc((), state.I, first(iter).I, last(iter).I)
end
# 0-d cartesian ranges are special-cased to iterate once and only once
myiterate(iter::CartesianIndices{0}, done=false) = done ? nothing : (CartesianIndex(), true)

# increment & carry
@inline inc(out, ::Tuple{}, ::Tuple{}, ::Tuple{}) = nothing
@inline function inc(out, state::Tuple{Int}, start::Tuple{Int}, stop::Tuple{Int})
    if state[1] < stop[1]
        nextstate = CartesianIndex(out..., state[1]+1)
        return nextstate, nextstate
    end
    return nothing
end
@inline function inc(out, state, start, stop)
    if state[1] < stop[1]
        nextstate = CartesianIndex(out..., state[1]+1, tail(state)...)
        return nextstate, nextstate
    end
    return inc((out..., start[1]), tail(state), tail(start), tail(stop))
end


function sumcart_newiter(A)
    s = 0.0
    iter = CartesianIndices(A)
    ret = myiterate(iter)
    @inbounds while !(ret === nothing)
        I, state = ret
        s += A[I]
        ret = myiterate(iter, state)
    end
    return s
end
```

The only difference is that this a `head-loop` and the iteration loop produces a `check + tail-loop`. For the curious I put both produced LLVM IR into godbolt and setup MCA for both https://godbolt.org/z/8owxJT

**Comment by vchuravy** [comment]
Ok... before a755c6a

```
julia> @benchmark sumcart_iter($A)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     158.716 ms (0.00% GC)
  median time:      163.086 ms (0.00% GC)
  mean time:        174.294 ms (0.00% GC)
  maximum time:     288.133 ms (0.00% GC)
  --------------
  samples:          29
  evals/sample:     1
```

after:

```
julia> @benchmark sumcart_iter($A)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     105.531 ms (0.00% GC)
  median time:      106.831 ms (0.00% GC)
  mean time:        107.862 ms (0.00% GC)
  maximum time:     120.262 ms (0.00% GC)
  --------------
  samples:          47
  evals/sample:     1
```

This is a a bit odd since LLVM prefers `do ... while` loops, and definitely requires a nanosoldier run.

@nanosoldier `runbenchmarks(ALL, vs = "@5a6b972282a91ceea422c479433e7d1413fea2b4")`

**Comment by jekbradbury** [comment]
What does this lowering change look like in terms of the equivalent Julia syntax? I think there’s an example of for loop lowering in the manual that might need to be adjusted.

File: base/multidimensional.jl [hunk 3]
```diff
@@ -334,20 +340,26 @@ module IteratorsMD
...
+        return inc((), state.I, first(iter).I, last(iter).I)
     end
 
     # increment & carry
-    @inline inc(::Tuple{}, ::Tuple{}, ::Tuple{}) = ()
-    @inline inc(state::Tuple{Int}, start::Tuple{Int}, stop::Tuple{Int}) = (state[1]+1,)
-    @inline function inc(state, start, stop)
+    # increment post check to avoid integer overflow
+    @inline inc(out, ::Tuple{}, ::Tuple{}, ::Tuple{}) = nothing
+    @inline function inc(out, state::Tuple{Int}, start::Tuple{Int}, stop::Tuple{Int})
```
Comment (timholy) [inline base/multidimensional.jl]: Do we even need this method anymore? I think it's covered by the generic case.

File: base/multidimensional.jl [hunk 4]
```diff
@@ -142,11 +146,13 @@ module IteratorsMD
     # nextind and prevind with CartesianIndex
     function Base.nextind(a::AbstractArray{<:Any,N}, i::CartesianIndex{N}) where {N}
         iter = CartesianIndices(axes(a))
-        return CartesianIndex(inc(i.I, first(iter).I, last(iter).I))
+        valid, I = inc(i.I, first(iter).I, last(iter).I)
```
Comment (timholy) [inline base/multidimensional.jl]: Should this really be called `valid`? How about just `_`?

**Review by timholy — COMMENTED** [review]
Really fascinating. I am not the best person to comment on LLVM's preferences for various lowered forms, and certainly not the changes to `julia-synax.scm`. It will be interesting to see the nanosoldier run.

File: base/multidimensional.jl (hunk 3 above)
Comment (vchuravy) [reply base/multidimensional.jl]: I don't think so. I added it because this is a common pattern elsewhere (probably steming from a time when inference liked code like this more).

File: base/multidimensional.jl (hunk 4 above)
Comment (vchuravy) [reply base/multidimensional.jl]:
```suggestion
        _, I = inc(i.I, first(iter).I, last(iter).I)
```

**Comment by vchuravy** [comment]
> What does this lowering change look like in terms of the equivalent Julia syntax? I think there’s an example of for loop lowering in the manual that might need to be adjusted.

Since we don't have a `do ... while` loop in Julia. Loop lowering on master currently looks like this:
```
next = iterate(iter)
if !(next === nothing)
   @label loop
   I, state = next
  # ...
  next = iterate(iter, state)
  if !(next === nothing)
    @goto loop
  end
end
```

my change changes it back to how it was on 0.6, but with the new iteration protocol
```
next = iterate(iter)
while !(next === nothing)
  I, state = next
  ...
  next = iterate(iter, state)
end
```

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31011#issuecomment-462180912) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/118199381089aa697b70c0b8ffccbfd589c2a45c/0afd1ef_vs_5a6b972/report.md). cc @ararslan

**Comment by vchuravy** [comment]
The nanosoldier results are confusing and all over the board. How can this change lead to half the memory usage....

File: base/multidimensional.jl [hunk 5]
```diff
@@ -95,6 +95,10 @@ module IteratorsMD
     # access to index tuple
     Tuple(index::CartesianIndex) = index.I
 
+    # equality
+    import Base: ==
+    ==(a::CartesianIndex{N}, b::CartesianIndex{N}) where N = a.I == b.I
```
Comment (ararslan) [inline base/multidimensional.jl]: No need for the `import`, this can just be `Base.:(==)(...)`, which is more explicit.

**Comment by ararslan** [comment]
The results will be noisier the more benchmarks are run at once, so if there are a few in particular you're interested in, you could do those specifically instead of `ALL`. That should give more reliable results.

**Comment by vchuravy** [comment]
**sigh**

Current Julia:
```
julia> A = zeros(3,3)
3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> nextind(A, CartesianIndex(3,3))
CartesianIndex(1, 4)

nextind(CartesianIndices((1:3, 1:typemax(Int))), CartesianIndex(3,typemax(Int)))
CartesianIndex(1, -9223372036854775808)
```

Looking at the docs for `nextind` the expected behaviour might be a `BoundsError`?

**Comment by vchuravy** [comment]
Okay. I decided not to experiment with loop-form and just focus on fixing the over/underflows. 

Notes:
- Lowering of cartesian loops with N>=2 is something I still want to further investigate, but the general realisation is that SCEV doesn't like it and can't figure out that the loops are bounded.
  A potential idea might be to have an IR pass that converts loops of this form to loop nests (hopefully solving this issue in general) and avoiding the kind of strip-mining transformation `@simd` does.
- I am unsure about the semantics for `nextind` usage generally seems to allow one illegal index to be returned and then calling `nextind` on that is supposed to give you a `BoundsError`.
- I rewrote `findnext` to avoid the overflow, but it would be cleaner to directly call `iterate`, but it is not clear to me whether `start` can be expected to be a proper iterator state.

**Comment by vchuravy** [comment]
> I am unsure about the semantics for nextind usage generally seems to allow one illegal index to be returned and then calling nextind on that is supposed to give you a BoundsError.

I went back to the form `valid, i = inc()`, which allows `nextind`/`prevind` to produce the nextindex. These might still underflow/overflow so I will leave the changes for `findnext` et.al, but I could also revert those and open a separate PR.

This also sets us up with a CGF that I believe to be amenable to be transformed into a loop nest.

**Comment by vchuravy** [comment]
There seems to be an inferrability issue:

```
  Test threw exception
  Expression: #= /tmp/julia/share/julia/test/reducedim.jl:55 =# @inferred(maximum(Areduc, dims=region)) ≈ safe_maximum(Areduc, region)
  return type Array{Float64,4} does not match inferred return type Array{_A,4} where _A
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] top-level scope at /tmp/julia/share/julia/test/reducedim.jl:55
   [3] top-level scope at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1186
   [4] include at ./boot.jl:325 [inlined]
   [5] include_relative(::Module, ::String) at ./loading.jl:1042
   [6] include at ./Base.jl:31 [inlined]
   [7] include(::String) at /tmp/julia/share/julia/test/testdefs.jl:13
   [8] top-level scope at /tmp/julia/share/julia/test/testdefs.jl:23
   [9] top-level scope at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [10] top-level scope at /tmp/julia/share/julia/test/testdefs.jl:22
   [11] top-level scope at util.jl:289
   [12] top-level scope at /tmp/julia/share/julia/test/testdefs.jl:20
```

Haven't had time to take a deeper look.

**Comment by vchuravy** [comment]
I plan to merge this tomorrow.

File: base/array.jl [hunk 6]
```diff
@@ -1781,8 +1783,12 @@ CartesianIndex(2, 1)
 """
 function findprev(A, start)
     i = start
-    while i >= first(keys(A))
+    f = first(keys(A))
+    i < f && return nothing
+    while true
         A[i] && return i
+        i == f && break
+        # prevind(A, l) can throw/underflow
```
Comment (mbauman) [inline base/array.jl]: Simple copy-paste comment here and below.  Not sure these comments are needed in the first place.

```suggestion
        # prevind(A, f) can throw/underflow
```

File: base/array.jl [hunk 7]
```diff
@@ -1868,8 +1874,12 @@ CartesianIndex(2, 1)
 """
 function findprev(testf::Function, A, start)
     i = start
-    while i >= first(keys(A))
+    f = first(keys(A))
+    i < f && return nothing
+    while true
         testf(A[i]) && return i
+        i == f && break
+        # prevind(A, l) can throw/underflow
```
Comment (mbauman) [inline base/array.jl]:
```suggestion
        # prevind(A, f) can throw/underflow
```

(marking this one too since you can now batch these line commits)

**Comment by mbauman** [comment]
I wanna see another nanosoldier run first. There were some fairly major regressions in array iteration in the run in February.

@nanosoldier `runbenchmarks("array" || "union", vs = ":master")`

**Comment by vchuravy** [comment]
Fair enough, the run in February was the experiment in changing the loop structure for the iteration protocol.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31011#issuecomment-477697593) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c07da687856acba854807a635c4944bd30539419/fc3865f_vs_c0ebd97/report.md). cc @ararslan

**Comment by vchuravy** [comment]
@mbauman The nanosoldier results look clean. Are you okay with squash merging this as is?
