### PR TITLE
fix -1.0^big

### LINKED ISSUE #44452: Regression in floating point power
1.7:

```jl
julia> (-1.0)^(1.0e63)
1.0
```

1.8:

```jl
julia> (-1.0)^(1.0e63)
ERROR: DomainError with -1.0:
Exponentiation yielding a complex result requires a complex argument.
```

Causes SpecialFunctions to fail tests.

### PR DESCRIPTION
**Pull request by oscardssmith**
Now returns 1.0 correctly

### CODE REVIEW

File: base/math.jl [hunk 1]
```diff
@@ -999,6 +999,7 @@ end
 @constprop :aggressive function ^(x::Float64, y::Float64)
     yint = unsafe_trunc(Int, y) # Note, this is actually safe since julia freezes the result
     y == yint && return x^yint
+    x === -1.0 && y >= 2*inv(eps()) && return 1.0
```
Comment (ianatol) [inline base/math.jl:1002]: I think the regression from #44452 happens for more than just specifically `-1.0`:

```julia
julia> VERSION
v"1.7.0"

julia> (-0.999999)^(1.0e63)
0.0

```

```julia
julia> VERSION
v"1.9.0-DEV.135"

julia> (-0.999999)^(1.0e63)
ERROR: DomainError with -0.999999:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
 [1] throw_exp_domainerror(x::Float64)
   @ Base.Math ./math.jl:37
 [2] ^(x::Float64, y::Float64)
   @ Base.Math ./math.jl:1002
 [3] top-level scope
   @ REPL[60]:1
```

Comment (oscardssmith) [reply base/math.jl:1002]: yuck. This is moderately annoying.

Comment (oscardssmith) [reply base/math.jl]: should be fixed.

Comment (ianatol) [reply base/math.jl]: LGTM, maybe could use a couple more tests

File: base/math.jl [hunk 2]
```diff
@@ -999,6 +999,7 @@ end
 @constprop :aggressive function ^(x::Float64, y::Float64)
     yint = unsafe_trunc(Int, y) # Note, this is actually safe since julia freezes the result
     y == yint && return x^yint
+    y >= 2*inv(eps()) && return x^typemax(Int64)
```
Comment (giordano) [inline base/math.jl:1002]: To be clear, this is assuming all numbers larger than `2*inv(eps())` are integers and have the same parity as `typemax(Int64)`?

Comment (oscardssmith) [reply base/math.jl:1002]: Oops. This should be `typemax(Int64)-1`.

Comment (oscardssmith) [reply base/math.jl]: the reason this is correct is that `inv(eps())` is the point at which `eps(x)=1`, so once you are twice that big, all your floats are even.

Comment (giordano) [reply base/math.jl]: But why?  How do you know the parity of numbers larger than `maxintfloat`?

Comment (giordano) [reply base/math.jl]: Oh well, I see `isinteger` gives `true` for numbers larger than `maxintfloat` (basically for the reason you gave above), so I guess that's consistent at least.

Comment (oscardssmith) [reply base/math.jl]: since the mantissa only has 52 (or fewer) bits, of the exponent is grater than 52, the number is even (and if it's 52, it's an integer)

**Comment by oscardssmith** [comment]
I believe this is now working.

**Comment by oscardssmith** [comment]
I'm merging this tomorrow unless someone objects.
