### PR TITLE
fix #22787, another bounds circularity in type intersection

### LINKED ISSUE #22787: Weird stackoverflow in inner constructor w/ use of const variable
Latest master, OSX
```julia
julia> sz = 3576
3576

julia> struct works
           data::NTuple{sz, UInt8}
           works() = new(ntuple(x->0x00, sz))
       end

julia> @time works()
  0.034114 seconds (27.93 k allocations: 1.803 MiB)
```
and
```julia
julia> const sz2 = 3576
3576

julia> struct doesntwork
           data::NTuple{sz2, UInt8}
           doesntwork() = new(ntuple(x->0x00, sz2))
       end

julia> @time doesntwork()
Internal error: encountered unexpected error in runtime:
StackOverflowError()
intersect at /Users/jacobquinn/julia/src/subtype.c:1897
intersect_unionall_ at /Users/jacobquinn/julia/src/subtype.c:1510
intersect_unionall at /Users/jacobquinn/julia/src/subtype.c:1555
intersect at /Users/jacobquinn/julia/src/subtype.c:1914
intersect_ufirst at /Users/jacobquinn/julia/src/subtype.c:1189 [inlined]
intersect_var at /Users/jacobquinn/julia/src/subtype.c:1244
intersect_invariant at /Users/jacobquinn/julia/src/subtype.c:1759
intersect at /Users/jacobquinn/julia/src/subtype.c:1999
intersect_tuple at /Users/jacobquinn/julia/src/subtype.c:1657 [inlined]
intersect at /Users/jacobquinn/julia/src/subtype.c:1965
intersect_unionall_ at /Users/jacobquinn/julia/src/subtype.c:1510
intersect_unionall at /Users/jacobquinn/julia/src/subtype.c:1555
intersect at /Users/jacobquinn/julia/src/subtype.c:1914
intersect_all at /Users/jacobquinn/julia/src/subtype.c:2035
jl_type_intersection_env_s at /Users/jacobquinn/julia/src/subtype.c:2139
jl_typemap_intersection_node_visitor at /Users/jacobquinn/julia/src/typemap.c:481
jl_typemap_intersection_visitor at /Users/jacobquinn/julia/src/typemap.c:545
jl_typemap_intersection_visitor at /Users/jacobquinn/julia/src/typemap.c:536
ml_matches at /Users/jacobquinn/julia/src/gf.c:2381
jl_matching_methods at /Users/jacobquinn/julia/src/gf.c:1615
abstract_call_gf_by_type at ./inference.jl:1650
...
...
...
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Note the added tests are broken, but at least they don't stack overflow. The first test is reduced from the issue. The second test is a simpler version that did not overflow before, but did incorrectly give `Union{}` before. That makes me hopeful that this will not make anything worse.

### CODE REVIEW

**Comment by Sacha0** [comment]
(The single tester_macos64 failure is in Distributed and appears unrelated.)

**Comment by Sacha0** [comment]
(tester_linuxaarch64 timed out with no preceding failures.)

**Review by Sacha0 — APPROVED** [review]
I do not fully understand the context of the changes to `intersect` and so can't comment meaningfully on those changes, but `comparto_var` in isolation seems sensical to me and the tests look good. Thanks Jeff! :)

**Comment by Sacha0** [comment]
If no one beats me to it, and absent objections or requests for time, I plan to merge these changes on November 2 late in the day PT. Thanks again Jeff!

File: test/subtype.jl [hunk 1]
```diff
@@ -1786,3 +1786,10 @@ let X1 = Tuple{AlmostLU, Vector{T}} where T,
     @test I >: actual
     @test_broken I == actual
 end
+
+# issue #22787
+# for now check that these don't stack overflow
+@test_broken typeintersect(Tuple{Type{Q}, Q, Ref{Q}} where Q<:Ref,
+                           Tuple{Type{S}, Union{Ref{S}, Ref{R}}, R} where R where S) != Union{}
+@test_broken typeintersect(Tuple{Type{T}, T, Ref{T}} where T,
+                           Tuple{Type{S}, Ref{S}, S} where S) != Union{}
```
Comment (NHDaly) [inline test/subtype.jl:1795]: If I'm not mistaken, `@test_broken` passes, even if they do stack overflow:

Here's an example of these tests passing on master, despite the stack overflow:
```julia
julia> # for now check that these don't stack overflow
       @test_broken typeintersect(Tuple{Type{Q}, Q, Ref{Q}} where Q<:Ref,
                                  Tuple{Type{S}, Union{Ref{S}, Ref{R}}, R} where R where S) != Union{}
Test Broken
  Expression: typeintersect(Tuple{Type{Q}, Q, Ref{Q}} where Q <: Ref, (Tuple{Type{S}, Union{Ref{S}, Ref{R}}, R} where R) where S) != Union{}

julia> @test_broken typeintersect(Tuple{Type{T}, T, Ref{T}} where T,
                                  Tuple{Type{S}, Ref{S}, S} where S) != Union{}
Test Broken
  Expression: typeintersect(Tuple{Type{T}, T, Ref{T}} where T, Tuple{Type{S}, Ref{S}, S} where S) != Union{}

julia> # You can see that it's stack overflowing when we remove the `@test_broken`:
       @test typeintersect(Tuple{Type{Q}, Q, Ref{Q}} where Q<:Ref,
                                  Tuple{Type{S}, Union{Ref{S}, Ref{R}}, R} where R where S) != Union{}
Error During Test at REPL[4]:2
  Test threw exception
  Expression: typeintersect(Tuple{Type{Q}, Q, Ref{Q}} where Q <: Ref, (Tuple{Type{S}, Union{Ref{S}, Ref{R}}, R} where R) where S) != Union{}
  StackOverflowError:
  Stacktrace:
    [1] typeintersect(a::Any, b::Any)
      @ Base ./reflection.jl:563
    [2] top-level scope
      @ REPL[4]:2
    [3] eval(m::Module, e::Any)
      @ Core ./boot.jl:360
...
```

Comment (NHDaly) [reply test/subtype.jl:1795]: Maybe you can change to something like this, which _would_ fail if they stack overflow, but still allow the broken intersection test? Thanks!

```suggestion
@testset begin
    # These tests don't pass, but for now check that at least they don't stack overflow
    t = typeintersect(Tuple{Type{Q}, Q, Ref{Q}} where Q<:Ref,
                           Tuple{Type{S}, Union{Ref{S}, Ref{R}}, R} where R where S)
    @test_broken t != Union{}
    t = typeintersect(Tuple{Type{T}, T, Ref{T}} where T,
                           Tuple{Type{S}, Ref{S}, S} where S)
    @test_broken t != Union{}
end
```

Comment (NHDaly) [reply test/subtype.jl:1795]: The above suggestion passes for me on this branch, and fails on master.

Comment (martinholters) [reply test/subtype.jl:1795]: To stop my head spinning... what's the correct answer to these intersection problems?

Comment (vtjnash) [reply test/subtype.jl:1795]: Here's some:
```
julia> Tuple{Type{Ref}, Ref{Ref}, Ref{Ref}} <: Tuple{Type{T}, Ref{T}, T} where T
true
julia> Tuple{Type{Ref}, Ref{Ref}, Ref{Ref}} <: Tuple{Type{T}, T, Ref{T}} where T
true

julia> Tuple{Type{Ref{<:Ref}}, Ref{Ref{<:Ref}}, Ref{Ref{<:Ref}}} <: Tuple{Type{T}, T, Ref{T}} where T
true
julia> Tuple{Type{Ref{<:Ref}}, Ref{Ref{<:Ref}}, Ref{Ref{<:Ref}}} <: Tuple{Type{T}, T, Ref{T}} where T
true

julia> Tuple{Type{Ref{<:Ref{<:Ref}}}, Ref{Ref{<:Ref{<:Ref}}}, Ref{Ref{<:Ref{<:Ref}}}} <: Tuple{Type{T}, T, Ref{T}} where T
true
julia> Tuple{Type{Ref{<:Ref{<:Ref}}}, Ref{Ref{<:Ref{<:Ref}}}, Ref{Ref{<:Ref{<:Ref}}}} <: Tuple{Type{T}, Ref{T}, T} where T
true
```
I don't know if there's a general closed-form expression of this, since it seems to be the Union of this out to infinity?
