### PR TITLE
consistency on :, UnitRange, StepRange, & StepRangeLen

### LINKED ISSUE #37169: 1.0:5.0 should be UnitRange{Float64}
In Julia 1.5.0, the help text of `:` promises
```
help?> :
  (:)(start, [step], stop)

  Range operator. a:b constructs a range from a to b with a step size of 1 (a
  UnitRange) , and a:s:b is similar but uses a step size of s (a StepRange).
```
However, at present `a:b` is not acually a `UnitRange` if `a` and `b` are floats:
```
julia> isa(1.0:5.0,UnitRange)
false

julia> typeof(1.0:5.0)
StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}
```
Expected behaviour:
```
julia> 1.0:5.0 === UnitRange{Float64}(1.0,5.0)
true
```
The culprit appears to be the line
```
# AbstractFloat specializations
(:)(a::T, b::T) where {T<:AbstractFloat} = (:)(a, T(1), b)
```
in [base/range.jl](https://github.com/JuliaLang/julia/blob/96786e22ccabfdafd073122abb1fb69cea921e17/base/range.jl#L14), the purpose of which I don't understand. It appears to override the line
```
(:)(start::T, stop::T) where {T<:Real} = UnitRange{T}(start, stop)
```

The reason this is a concern:
```
julia> foo(subrange::UnitRange{<:Real}) = last(subrange)
foo (generic function with 1 method)

julia> foo(1.0:5.0)
ERROR: MethodError: no method matching foo(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}})

```

### PR DESCRIPTION
**Pull request by udohjeremiah**
This fixes #37169.

Also I had opened a PR at #47001 before now, but messed it up trying to fix the #37169 issue.

As seen from the issue on #37169, `a:b` does not always create a `UnitRange`. And though the current docs says **"often a `UnitRange`"**, I feel it should just say it all (since saying only `UnitRange` can raise confusions as the issue states).

Also the docs on `UnitRange` and `StepRange` shows the syntax from which they can be created. `StepRangeLen` however does not show this (which I don't see any reason for).

### CODE REVIEW

File: base/range.jl [hunk 1]
```diff
@@ -469,9 +469,10 @@ A range `r` where `r[i]` produces values of type `T` (in the first
 form, `T` is deduced automatically), parameterized by a `ref`erence
 value, a `step`, and the `len`gth. By default `ref` is the starting
 value `r[1]`, but alternatively you can supply it as the value of
-`r[offset]` for some other index `1 <= offset <= len`. In conjunction
-with `TwicePrecision` this can be used to implement ranges that are
-free of roundoff error.
+`r[offset]` for some other index `1 <= offset <= len`. The syntax `a:b`
+or `a:b:c` with `a`, `b`, and `c` all floating-points creates a `StepRangeLen`.
```
Comment (sostock) [inline base/range.jl:473]:
```suggestion
or `a:b:c`, where any of `a`, `b`, or `c` are floating-point numbers, creates a
`StepRangeLen`.
```
They don’t have to be _all_ floating-point numbers, one of them is enough. `1:2.0`, `1.0:2:3`, `1:2.0:3` all create `StepRangeLen`s.

I also changed "floating-points" to "floating-point numbers".

Comment (mcabbott) [reply base/range.jl:473]: Maybe the first question is whether this should be documented at all. Or is the exact type of range you get just an implementation detail?

Comment (sostock) [reply base/range.jl]: I would actually say it is an implementation detail that shouldn’t be documented. Especially because anyone can define their own datatypes, for which `a:b:c` can return whatever they want.

File: base/range.jl [hunk 2]
```diff
@@ -32,8 +32,8 @@ _colon(::Any, ::Any, start::T, step, stop::T) where {T} =
     (:)(start, [step], stop)
 
 Range operator. `a:b` constructs a range from `a` to `b` with a step size
-of 1 (often a [`UnitRange`](@ref)), and `a:s:b` is similar but uses a step
-size of `s` (a [`StepRange`](@ref) or [`StepRangeLen`](@ref)).
+equal to 1 (a [`UnitRange`](@ref) or [`StepRangeLen`](@ref)), and `a:s:b` is
```
Comment (sostock) [inline base/range.jl:35]: There are cases where `a:b` returns neither a `UnitRange` nor a `StepRangeLen`, even in `Base`:
```
julia> typeof('a':'d')
StepRange{Char, Int64}
```
Furthermore, anyone can define their own types and `:` methods. For example, [InfiniteArrays.jl](https://github.com/JuliaArrays/InfiniteArrays.jl) defines `1:∞` to return an `InfUnitRange{Int}` (a type that is also defined in that package).

Comment (udohjeremiah) [reply base/range.jl:35]: I agree that there are cases where `a:b` returns neither a `UnitRange` nor a `StepRangeLen`, even in `Base`, as you've pointed out, but adding the behaviour of what outside packages would do is not "useful" here, since anyone can extend it to what they want.

The aim of docstrings is to provide information on what is the expected behaviour of a function in `Base`; so should we extend that docstring to add `StepRange`, or just leave it all out?

Comment (udohjeremiah) [reply base/range.jl]: I think the updated docstrings serves all parties.
