### PR TITLE
fix some issues with color configuration

### LINKED ISSUE #30703: No color in printstyled when pipe is used
Hi guys!

I am trying to save a text file with the output of a Julia script but with the escape sequences so that I can render the colors. However, when I call Julia using pipe, I get no colors. Even if I have `--color=yes`. You can test by starting Julia as:

    julia --color=yes | tee

The logo will be gray (but `julia>` will be colored). Is there a way to provide another option, like `--color=force` so that `printstyled` always use the escape sequences?

### PR DESCRIPTION
**Pull request by JeffBezanson**
The issues here were truly surprising. Try running julia with `--color=no` (i guess I never do). Most color goes away, but all prompts are still bold, and while other prompts are un-colored, the Pkg prompt is still blue. I almost abandoned hope when I saw that. Then there is #30703, where redirecting to a pipe (`julia | tee`) removes most color, except *all* prompts are colored and bold, and `--color=yes` doesn't re-enable color. So this does the following:

- If `--color` is specified and stdout or stderr is not a TTY, wrap it in an IOContext with the color setting.
- Consistently use `get` on an io stream everywhere to determine whether to use color.
- Thread the color setting through to `write_prompt` to disable bold.
- Disable beep color if `hascolor=false` is passed to the REPL.

Needs #36688 to work. Should fix or help #36671. Fixes #30703.

### CODE REVIEW

File: stdlib/REPL/src/REPL.jl [hunk 1]
```diff
@@ -849,7 +855,7 @@ end
 
 function reset(repl::LineEditREPL)
     raw!(repl.t, false)
-    print(repl.t, Base.text_colors[:normal])
+    hascolor(repl) && print(repl.t, Base.text_colors[:normal])
```
Comment (vtjnash) [inline stdlib/REPL/src/REPL.jl:858]: Possible odd to return a Boolean?

**Review by vtjnash — APPROVED** [review]
Epic!

File: stdlib/REPL/src/REPL.jl [hunk 2]
```diff
@@ -436,9 +436,15 @@ mutable struct LineEditREPL <: AbstractREPL
     last_shown_line_infos::Vector{Tuple{String,Int}}
     interface::ModalInterface
     backendref::REPLBackendRef
-    LineEditREPL(t,hascolor,prompt_color,input_color,answer_color,shell_color,help_color,history_file,in_shell,in_help,envcolors) =
+    function LineEditREPL(t,hascolor,prompt_color,input_color,answer_color,shell_color,help_color,history_file,in_shell,in_help,envcolors)
+        opts = Options()
+        opts.hascolor = hascolor
+        if !hascolor
+            opts.beep_colors = [""]
+        end
```
Comment (rfourquet) [inline stdlib/REPL/src/REPL.jl:444]: Maybe this logic belongs in the `Options` constructor taking kwargs? e.g. in the body of that method, replace `beep_colors` by `hascolor ? beep_colors : [""]` (or change the default value by `hascolor ? ["\e[90m"] : [""]`).

File: stdlib/REPL/src/LineEdit.jl [hunk 3]
```diff
@@ -1259,21 +1259,21 @@ refresh_line(s, termbuf) = refresh_multi_line(termbuf, s)
 default_completion_cb(::IOBuffer) = []
 default_enter_cb(_) = true
 
-write_prompt(terminal, s::PromptState) = write_prompt(terminal, s.p)
+write_prompt(terminal, s::PromptState, hascolor::Bool) = write_prompt(terminal, s.p, hascolor)
```
Comment (StefanKarpinski) [inline stdlib/REPL/src/LineEdit.jl:1262]: Maybe call this just `color`? It's typically only set if the terminal has color, but it could be called with anything.

**Review by Keno — APPROVED** [review]

**Comment by Keno** [comment]
Modulo passing CI of course ;)

**Comment by giordano** [comment]
With this PR now I get
```
$ ./julia --color=yes -e 'printstyled(stderr, "Hello world\n"; color=:cyan)' 2>&1 | cat -A
^[[36mHello world^[[39m$
$ ./julia --color=yes -e '@info "Hello world"' 2>&1 | cat -A
[ Info: Hello world$
```
:thinking:

**Comment by giordano** [comment]
As far as I can see, the problem is that the stream of the global logger doesn't have the `color` flag, even though it should be `stderr`:
```
$ usr/bin/julia --color=yes -e 'using Logging; @show get(global_logger().stream, :color, nothing)' 2>&1 | cat -A
get((global_logger()).stream, :color, nothing) = nothing$
```

File: base/client.jl [hunk 4]
```diff
@@ -210,6 +210,14 @@ function exec_options(opts)
     history_file          = (opts.historyfile != 0)
     color_set             = (opts.color != 0) # --color!=auto
     global have_color     = color_set ? (opts.color == 1) : nothing # --color=on
+    if color_set
+        if !isa(stdout, TTY)
+            global stdout = IOContext(stdout, :color => have_color::Bool)
+        end
+        if !isa(stderr, TTY)
+            global stderr = IOContext(stderr, :color => have_color::Bool)
```
Comment (tkf) [inline base/client.jl:218]: I think fixing the issue @giordano observed https://github.com/JuliaLang/julia/pull/36689#issuecomment-659782477 requires calling `global_logger(ConsoleLogger(stderr))` again here?  This is because, at this point, `Logging.__init__` is already executed and `global_logger` is configured without `IOContext`.

**Comment by giordano** [comment]
Seems to finally work
```
$ ./julia -e '@info "Hello world"' 2>&1 | cat -A
[ Info: Hello world$
$ ./julia --color=yes -e '@info "Hello world"' 2>&1 | cat -A
^[[36m^[[1m[ ^[[22m^[[39m^[[36m^[[1mInfo: ^[[22m^[[39mHello world$
$ ./julia --color=no -e '@info "Hello world"' 2>&1 | cat -A
[ Info: Hello world$
```
:tada:

**Comment by ianshmean** [comment]
🌈

**Comment by ianshmean** [comment]
Confirmed to work in github actions (by locally building this PR, then mounting as a github self-hosted runner)
image

**Comment by giordano** [comment]
The failure in macOS seems unrelated?  Good to merge otherwise?
