### PR TITLE
codegen: avoid bad tbaa paths

### LINKED ISSUE #33590: Precompiling BioSequences fails on debug mode with LLVM assertions on "Access type node must be a valid scalar type"
```jl
julia> using BioSequences
[ Info: Precompiling BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59]
Access type node must be a valid scalar type
  %131 = load i64, i64 addrspace(11)* %123, align 8, !dbg !10122, !tbaa !10124
!10124 = !{!180, !180, i64 0}
!180 = !{!"jtbaa"}
Access type node must be a valid scalar type
  %147 = load i64, i64 addrspace(11)* %123, align 8, !dbg !10130, !tbaa !10124
!10124 = !{!180, !180, i64 0}
!180 = !{!"jtbaa"}
Access type node must be a valid scalar type
  %173 = load i64, i64 addrspace(11)* %123, align 8, !dbg !10146, !tbaa !10124
!10124 = !{!180, !180, i64 0}
!180 = !{!"jtbaa"}
Access type node must be a valid scalar type
  %543 = load i64, i64 addrspace(11)* %123, align 8, !dbg !10147, !tbaa !10124
!10124 = !{!180, !180, i64 0}
!180 = !{!"jtbaa"}
Access type node must be a valid scalar type
  %549 = load i64, i64 addrspace(11)* %123, align 8, !dbg !10129, !tbaa !10124
!10124 = !{!180, !180, i64 0}
!180 = !{!"jtbaa"}
Access type node must be a valid scalar type
  %555 = load i64, i64 addrspace(11)* %123, align 8, !dbg !10121, !tbaa !10124
!10124 = !{!180, !180, i64 0}
!180 = !{!"jtbaa"}
LLVM ERROR: Broken function found, compilation aborted!
ERROR: LoadError: Failed to precompile BioSymbols [3c28c6f8-a34d-59c4-9654-267d177fcfa9] to /home/kc/.julia/compiled/v1.4/BioSymbols/WGJJN_waeDF.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1247
 [3] _require(::Base.PkgId) at ./loading.jl:1009
 [4] require(::Base.PkgId) at ./loading.jl:907
 [5] require(::Module, ::Symbol) at ./loading.jl:902
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:457
 [10] top-level scope at ./none:3
in expression starting at /home/kc/.julia/packages/BioSequences/7i86L/src/BioSequences.jl:188
ERROR: Failed to precompile BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59] to /home/kc/.julia/compiled/v1.4/BioSequences/i7zyu_waeDF.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1247
 [3] _require(::Base.PkgId) at ./loading.jl:1009
 [4] require(::Base.PkgId) at ./loading.jl:907
 [5] require(::Module, ::Symbol) at ./loading.jl:902
```

### PR DESCRIPTION
**Pull request by vtjnash**
This avoids cases where getMostGenericTBAA could return broken answers.

fix #33590

### CODE REVIEW

**Review by Keno — APPROVED** [review]
LGTM in terms of changes, but looks like one of the llvmpasses tests needs to be updated.

File: test/compiler/codegen.jl [hunk 1]
```diff
@@ -407,3 +407,11 @@ function f1_30093(r)
 end
 
 @test f1_30093(Ref(0)) == nothing
+
+# issue 33590
+function f33590(b, x)
```
Comment (KristofferC) [inline test/compiler/codegen.jl]: These tests pass on master for me.

**Comment by vtjnash** [comment]
Oops, I blamed getMostGenericTBAA, but the bad TBAA node was actually emitted on the next line of code (which tried to handle when getMostGenericTBAA fails) https://github.com/JuliaLang/julia/blob/4e3174107c5808958fef9e50920c03e18854d76c/src/intrinsics.cpp#L814-L819
