### PR TITLE
fix #21793, regression in serializing nested closure

### LINKED ISSUE #21793: Anonymous functions that return anonymous functions error on deserialization.
Originally reported at https://github.com/JuliaLang/julia/issues/19456#issuecomment-300331988
Reproducing below:

```
julia> y = (x) -> (() -> x)
(::#1) (generic function with 1 method)

julia> g = y(1)

julia> g()
1

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=fa
lse, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> serialize(io, y)

julia> seekstart(io)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=fa
lse, size=316, maxsize=Inf, ptr=1, mark=-1)

julia> deserialize(io) # crashes
``` 

Going through the history of changes to `base/serialize.jl`, commit https://github.com/JuliaLang/julia/commit/e3bec2a34d724843040e8101d22c5bfacf891968#diff-aec7b7bfc3115e923e4137ad38876951 is the first one that causes the above failure.

cc: @JeffBezanson

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

File: test/serialize.jl [hunk 1]
```diff
@@ -300,6 +300,15 @@ main_ex = quote
...
         $Test.@test deserialize(ds) === g2
+
+        # issue #21793
+        y = x -> (() -> x)
+        seekstart(s)
+        serialize(s, y)
+        seekstart(s)
+        y2 = deserialize(s)
+        x2 = y2(2)
+        @test x2() == 2
```
Comment (odow) [inline test/serialize.jl]: Looks like this should be `$Test.@test x2() == 2`

**Comment by JeffBezanson** [comment]
Failure looks unrelated.
