### PR TITLE
Restore cfunction special case in inlining

### LINKED ISSUE #27178: New Optimizer triggers (wrong) LoadError
This small program compiled (and run) until commit 88f17129c78f10dd939a6dd1810a57d5324cb1bf (Julia Version 0.7.0-DEV.5097), i.e. the activation of the new optimizer. [This is a minimal example derived from production code, in order to show the effect.]

```julia
mutable struct CallThisFunc{FCN_TYPE}
  fcn         :: FCN_TYPE
end

function use_cb_func(cb::CTF) where CTF<:CallThisFunc
  println(stderr, "going to use fcn: ", cb.fcn)
  return nothing
end

function cfunc_for_use_cb_func(cbi::CI) where CI
  return @cfunction(use_cb_func, Cvoid, (Ref{CI},))
end

function get_c_func(fcn::FCN_TYPE) where FCN_TYPE<:Function
  return cfunc_for_use_cb_func(CallThisFunc(fcn))
end

get_c_func(sin)
```
With the new optimizer one now gets the Error message:
```
ERROR: LoadError: cfunction argument 1 type Ref should have an element type, not Ref{<:T}.
Stacktrace:
 [1] cfunc_for_use_cb_func at /TEST/mytest.jl:11 [inlined]
 [2] get_c_func(::typeof(sin)) at /TEST/mytest.jl:15
 [3] top-level scope
 [4] include at ./boot.jl:314 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1067
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] exec_options(::Base.JLOptions) at ./client.jl:327
 [8] _start() at ./client.jl:457
```

since:
```
Julia Version 0.7.0-DEV.5097
Commit 88f17129c (2018-05-13 00:20 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

### PR DESCRIPTION
**Pull request by Keno**
As far as I'm concerned this entire mechanism (storing raw DataTypes in the AST)
is a hack and we should come up with something better at some point, but until
then, but back the hack and add a test for the feature. Fixes #27178.

### CODE REVIEW

File: test/ccall.jl [hunk 1]
```diff
@@ -1433,3 +1433,13 @@ function callthis_26607(args)
 end
 @test callthis_26607(Int64(0)) === nothing
 @test callthis_26607(Int32(0)) === nothing
+
+# issue #27178 (cfunction special case in inlining)
+mutable struct CallThisFunc27178{FCN_TYPE}
+  fcn::FCN_TYPE
```
Comment (ararslan) [inline test/ccall.jl]: Should be 4 spaces for indentation
