### PR TITLE
fix mask computation when marking objarray

### LINKED ISSUE #48405: `jl_gc_mark_queue_objarray` can no longer handle arrays containing null pointers
~~Before the mark loop rewrite it was possible to have null pointers in the array that's provided to `jl_gc_mark_queue_objarray`, but this situation causes a segfault now. Working around this change is pretty straightforward, just call `jl_gc_mark_queue_obj` for all non-null pointers, but I think null-pointers in this array should remain supported.~~

When an old foreign object contains an array of pointers where at least one points to a young object, `jl_gc_mark_queue_objarray` does not fully update the GC state of the parent object. Previously it was possible to return 0 from the mark function when `jl_gc_mark_queue_objarray` was used.

Reproducer:

```
#include <julia.h>
#include <julia_gcext.h>

JULIA_DEFINE_FAST_TLS

    typedef struct
{
    jl_value_t **ptrs;
} mytype;

uintptr_t markfunc(jl_ptls_t ptls, jl_value_t *obj)
{
    jl_gc_mark_queue_objarray(ptls, obj, ((mytype *)obj)->ptrs, 1);
    return 0;
}

void sweepfunc(jl_value_t *obj)
{
    mytype *myinstance = (mytype *)obj;
    free(myinstance->ptrs);
}

mytype *new_mytype(jl_datatype_t *ty)
{
    jl_ptls_t ptls = jl_current_task->ptls;
    mytype *instance = (mytype *)jl_gc_alloc_typed(ptls, sizeof(mytype), (void *)ty);
    instance->ptrs = malloc(sizeof(jl_value_t *));
    instance->ptrs[0] = NULL;
    jl_gc_schedule_foreign_sweepfunc(ptls, (jl_value_t *)instance);

    return instance;
}

int main(int argc, char *argv[])
{
    jl_init();
    jl_sym_t *sym = jl_symbol("ForeignType");
    jl_datatype_t *ty = jl_new_foreign_type(
        sym, jl_base_module, jl_any_type, markfunc, sweepfunc, 1, 0);

    jl_set_const(jl_base_module, sym, (jl_value_t *)ty);

    jl_value_t **args;
    JL_GC_PUSHARGS(args, 1);

    mytype *instance = new_mytype(ty);
    args[0] = (jl_value_t *)instance;
    jl_gc_collect(JL_GC_FULL);
    jl_gc_collect(JL_GC_FULL);
    assert(jl_astaggedvalue(instance)->bits.gc == 3);

    instance->ptrs[0] = (jl_value_t *)new_mytype(ty);
    jl_gc_wb((const void *)instance, (const void *)instance->ptrs[0]);
    assert(jl_astaggedvalue(instance)->bits.gc == 1);
    jl_gc_collect(JL_GC_FULL);
    // The GC-bits are 3 when I use the most recent master, 1 when I use Julia 1.8 or 1.9
    // If the GC bits are 3, a GC error occurs
    assert(jl_astaggedvalue(instance)->bits.gc == 1); 
    jl_gc_collect(JL_GC_FULL);

    JL_GC_POP();

    jl_atexit_hook(0);
    return 0;
}
```

### PR DESCRIPTION
**Pull request by d-netto**
Fixes https://github.com/JuliaLang/julia/issues/48405.

### CODE REVIEW

**Comment by giordano** [comment]
Can add a test?

File: src/gc.c [hunk 1]
```diff
@@ -2242,7 +2242,7 @@ JL_DLLEXPORT int jl_gc_mark_queue_obj(jl_ptls_t ptls, jl_value_t *obj)
 JL_DLLEXPORT void jl_gc_mark_queue_objarray(jl_ptls_t ptls, jl_value_t *parent,
                                             jl_value_t **objs, size_t nobjs)
 {
-    uintptr_t nptr = (nobjs << 2) & (jl_astaggedvalue(parent)->bits.gc & 3);
+    uintptr_t nptr = (nobjs << 2) | (jl_astaggedvalue(parent)->bits.gc & 2);
```
Comment (fingolfin) [inline src/gc.c:2245]: Thank you for the fix!

The previous code always would end up with `nptr` equal to zero, so clearly was wrong. It was added just recently, replacing code that was in place a couple years, and that old code used effectively `bits.gc & 2`, so that change also seems plausible to me -- albeit without having looked further into `gc_mark_objarray`. But I have no reason to mistrust your judgement on this, just pointing out the limits to which I understand/approve this :-).

**Review by fingolfin — APPROVED** [review]
