### PR TITLE
Try to fix deadlock in code loading

### LINKED ISSUE #26028: Julia hangs when precompiling package with certain pattern
Package `Foo` with following structure:

### `Foo.jl`

```
__precompile__()
module Foo

module Bar
    x = 0
end

function __init__()
    include(joinpath(@__DIR__, "bar.jl"))
end

end
```

### bar.jl

```
import Foo.Bar.x
```

Trying to do `using Foo` now hangs indefinitely. Removing `__precompile__()` makes it work. Works on 0.6.2.

Stacktrace after interrupting is:

```
Stacktrace:
 [1] process_events at ./libuv.jl:82 [inlined]
 [2] wait() at ./event.jl:258
 [3] wait(::Condition) at ./event.jl:46
 [4] _require(::Base.PkgId) at ./loading.jl:934
 [5] require(::Module, ::Symbol) at ./loading.jl:874
 [6] include at ./boot.jl:295 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1067
 [8] include at ./sysimg.jl:26 [inlined]
 [9] include at /Users/kristoffer/.julia/v0.7/Foo/src/Foo.jl:2 [inlined]
 [10] __init__() at /Users/kristoffer/.julia/v0.7/Foo/src/Foo.jl:9
 [11] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:656
 [12] _require_from_serialized(::String) at ./loading.jl:718
 [13] _require(::Base.PkgId) at ./loading.jl:1004
 [14] require(::Module, ::Symbol) at ./loading.jl:874
in expression starting at /Users/kristoffer/.julia/v0.7/Foo/src/bar.jl:1
```

### PR DESCRIPTION
**Pull request by Keno**
If a precompiled package's init function tries to itself require that
package (e.g. by importing a symbol from a submodule of that package),
we would run into a deadlock. Fix that by delaying the running of
initializers until after we've had a chance to register any root module.

Fixes #26028

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by iblis17** [comment]
FreeBSD CI workers got randomly frozen builds after this PR merged.

all the following build is on 0e32871bfcee426fc4bf8c5d70af3f472b069868
- master build failed/worker `abeing`: https://freebsdci.julialang.org/#/builders/1/builds/11930
- master build failed/worker `gaebolg`: https://freebsdci.julialang.org/#/builders/1/builds/11931
- master build passed/worker `abeing`: https://freebsdci.julialang.org/#/builders/1/builds/11932

**Comment by ararslan** [comment]
I'm hesitant to backport this if it causes FreeBSD issues.

**Comment by Keno** [comment]
@iblis17 I'm not sure this is related. Those builds ran at about the same time and both hung at a place where they would be trying to do network I/O. The builds afterwards failed with a network error and the ones after that succeeded. Could there have been intermittent network problems?

**Comment by iblis17** [comment]
Seems no hanging now. It may be network issue.

(But there aren't any exceptions raised. What's the timeout config of our libgit2.

File: base/loading.jl [hunk 1]
```diff
@@ -611,7 +611,8 @@ end
 # or an Exception that describes why it couldn't be loaded
 # and it reconnects the Base.Docs.META
 function _include_from_serialized(path::String, depmods::Vector{Any})
-    restored = ccall(:jl_restore_incremental, Any, (Cstring, Any), path, depmods)
+    sv = ccall(:jl_restore_incremental, Any, (Cstring, Any), path, depmods)
+    restored = sv[1]
```
Comment (KristofferC) [inline base/loading.jl]: @Keno, this looks incorrect. The return value from `jl_restore_incremental` is not indexable?

Comment (Keno) [reply base/loading.jl]: This same commit changed the regular return value to be an exception, but you are correct that something got messed up with the other return path in this function. Wanna fix it and ideally at a test case ;)?
