### PR TITLE
[LateLowerGC] Fix typo sret handling so we properly handle selects in the worklist

### LINKED ISSUE #57737: `Unexpected SRet argument`
After https://github.com/JuliaLang/julia/pull/57720 was merged, this is the next error on the Oscar.jl testsuite with nightly.

CI log: https://github.com/oscar-system/Oscar.jl/actions/runs/13808965133/job/38625936986#step:11:1670
```julia
  %172 = select i1 %171, ptr %15, ptr %16
Unexpected SRet argument

[1349253] signal 6 (-6): Aborted
in expression starting at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/test/Serialization/loading.jl:1
unknown function (ip: 0x7f677ae51ebc) at /lib/x86_64-linux-gnu/libc.so.6
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
FindSretAllocas at /cache/build/default-maughin-0/julialang/julia-master/src/llvm-late-gc-lowering.cpp:1160
LocalScan at /cache/build/default-maughin-0/julialang/julia-master/src/llvm-late-gc-lowering.cpp:1224
runOnFunction at /cache/build/default-maughin-0/julialang/julia-master/src/llvm-late-gc-lowering.cpp:2562
run at /cache/build/default-maughin-0/julialang/julia-master/src/llvm-late-gc-lowering.cpp:2603
run at /cache/build/default-maughin-0/julialang/julia-master/usr/include/llvm/IR/PassManagerInternal.h:90
_ZN4llvm11PassManagerINS_8FunctionENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_ at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/bin/../lib/julia/libLLVM.so.19.1jl (unknown line)
run at /cache/build/default-maughin-0/julialang/julia-master/usr/include/llvm/IR/PassManagerInternal.h:90
_ZN4llvm27ModuleToFunctionPassAdaptor3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/bin/../lib/julia/libLLVM.so.19.1jl (unknown line)
run at /cache/build/default-maughin-0/julialang/julia-master/usr/include/llvm/IR/PassManagerInternal.h:90
_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_ at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/bin/../lib/julia/libLLVM.so.19.1jl (unknown line)
run at /cache/build/default-maughin-0/julialang/julia-master/src/pipeline.cpp:789
operator() at /cache/build/default-maughin-0/julialang/julia-master/src/jitlayers.cpp:1584
withModuleDo<(anonymous namespace)::sizedOptimizerT<N>::operator()(llvm::orc::ThreadSafeModule) [with long unsigned int N = 4]::<lambda(llvm::Module&)> > at /cache/build/default-maughin-0/julialang/julia-master/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136 [inlined]
operator() at /cache/build/default-maughin-0/julialang/julia-master/src/jitlayers.cpp:1545 [inlined]
operator() at /cache/build/default-maughin-0/julialang/julia-master/src/jitlayers.cpp:1697 [inlined]
addModule at /cache/build/default-maughin-0/julialang/julia-master/src/jitlayers.cpp:2156
jl_compile_codeinst_now at /cache/build/default-maughin-0/julialang/julia-master/src/jitlayers.cpp:629
jl_compile_codeinst_impl at /cache/build/default-maughin-0/julialang/julia-master/src/jitlayers.cpp:949
jl_compile_method_internal at /cache/build/default-maughin-0/julialang/julia-master/src/gf.c:3010
_jl_invoke at /cache/build/default-maughin-0/julialang/julia-master/src/gf.c:3492 [inlined]
ijl_apply_generic at /cache/build/default-maughin-0/julialang/julia-master/src/gf.c:3700
#6428 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:362
unknown function (ip: 0x7f6749f39ca2) at (unknown file)
load_node at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/serializers.jl:232
#load_typed_object#6426 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:361
load_typed_object at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:351
#load#6717 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:782
load at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:716 [inlined]
#6744 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:812 [inlined]
#open#328 at ./io.jl:410
open at ./io.jl:407 [inlined]
#load#6742 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:811 [inlined]
load at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/Serialization/main.jl:808
unknown function (ip: 0x7f67143b1bc2) at (unknown file)
jl_apply at /cache/build/default-maughin-0/julialang/julia-master/src/julia.h:2341 [inlined]
do_call at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:124
eval_value at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:242
eval_body at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:580
eval_body at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:557
eval_body at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:557
eval_body at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:557
eval_body at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:557
jl_interpret_toplevel_thunk at /cache/build/default-maughin-0/julialang/julia-master/src/interpreter.c:897
jl_toplevel_eval_flex at /cache/build/default-maughin-0/julialang/julia-master/src/toplevel.c:1032
jl_toplevel_eval_flex at /cache/build/default-maughin-0/julialang/julia-master/src/toplevel.c:972
ijl_toplevel_eval at /cache/build/default-maughin-0/julialang/julia-master/src/toplevel.c:1044
ijl_toplevel_eval_in at /cache/build/default-maughin-0/julialang/julia-master/src/toplevel.c:1089
eval at ./boot.jl:489
include_string at ./loading.jl:2855
_include at ./loading.jl:2915
include at ./Base.jl:306
macro expansion at ./timing.jl:621 [inlined]
#_timed_include#45 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/utils/tests.jl:5
_timed_include at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/utils/tests.jl:1 [inlined]
_timed_include at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/utils/tests.jl:1 [inlined]
#55 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/utils/tests.jl:258
with_unicode at /home/oscarci-tester/oscar-runners/runner-24/julia/packages/AbstractAlgebra/DNYYA/src/PrettyPrinting.jl:1852
#test_module#53 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/utils/tests.jl:206 [inlined]
test_module at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/src/utils/tests.jl:205 [inlined]
#21 at ./none (unknown line) [inlined]
#21 at /home/oscarci-tester/oscar-runners/runner-24/_work/Oscar.jl/Oscar.jl/test/runtests.jl:0
unknown function (ip: 0x7f6716b1f912) at (unknown file)
#exec_from_cache#147 at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/share/julia/stdlib/v1.13/Distributed/src/workerpool.jl:387
exec_from_cache at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/share/julia/stdlib/v1.13/Distributed/src/workerpool.jl:387
unknown function (ip: 0x7f6719a2f556) at (unknown file)
jl_apply at /cache/build/default-maughin-0/julialang/julia-master/src/julia.h:2341 [inlined]
jl_f_invokelatest at /cache/build/default-maughin-0/julialang/julia-master/src/builtins.c:853
jl_apply at /cache/build/default-maughin-0/julialang/julia-master/src/julia.h:2341 [inlined]
jl_f__apply_iterate at /cache/build/default-maughin-0/julialang/julia-master/src/builtins.c:841
#handle_msg##4 at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/share/julia/stdlib/v1.13/Distributed/src/process_messages.jl:287
run_work_thunk at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/share/julia/stdlib/v1.13/Distributed/src/process_messages.jl:70
#handle_msg##2 at /home/oscarci-tester/oscar-runners/runner-24/_work/_tool/julia/nightly/x64/share/julia/stdlib/v1.13/Distributed/src/process_messages.jl:287
unknown function (ip: 0x7f675d5e1fc7) at (unknown file)
jl_apply at /cache/build/default-maughin-0/julialang/julia-master/src/julia.h:2341 [inlined]
start_task at /cache/build/default-maughin-0/julialang/julia-master/src/task.c:1249
Allocations: 439465608 (Pool: 439401793; Big: 63815); GC: 63
```

cc @benlorenz @fingolfin

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes https://github.com/JuliaLang/julia/issues/57737

### CODE REVIEW

File: src/llvm-gc-interface-passes.h [hunk 1]
```diff
@@ -46,6 +46,7 @@
 #include "llvm-pass-helpers.h"
 #include <map>
 #include <string>
+#include <optional>
```
Comment (giordano) [inline src/llvm-gc-interface-passes.h:49]: Should this include be in `src/llvm-late-gc-lowering.cpp` rather than here? I don't see uses of `optional` in this file.

**Review by vtjnash — APPROVED** [review]

File: src/llvm-gc-interface-passes.h (hunk 1 above)
Comment (gbaraldi) [reply src/llvm-gc-interface-passes.h:49]: I was just following the pattern where that pass doesn't include any of it's own headers

File: src/llvm-late-gc-lowering.cpp [hunk 2]
```diff
@@ -1152,12 +1152,12 @@ static SmallSetVector<AllocaInst *, 8> FindSretAllocas(Value* SRetArg) {
                 } else {
                     llvm_dump(SI);
                     dbgs() << "Malformed Select\n";
-                    abort();
+                    return {};
```
Comment (topolarity) [inline src/llvm-late-gc-lowering.cpp:1155]: Why'd we get rid of the aborts here?

Comment (gbaraldi) [reply src/llvm-late-gc-lowering.cpp:1155]: It just got moved elsewhere, I wanted to print the whole function and that wasn’t available in the function
