### PR TITLE
missing gc-root store in subtype

### LINKED ISSUE #56141: Segfault when marking GC shadow stack
See https://buildkite.com/julialang/julia-master/builds/40903#01928664-6aa2-43b2-a0a0-49ab0fd41de7.

We're probably storing a garbage pointer in the shadow stack.

Don't know if it's reproducible.

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #56141
Introduced by #52228 (a624d445c02c)

### CODE REVIEW

File: src/subtype.c [hunk 1]
```diff
@@ -4700,12 +4700,12 @@ static jl_value_t *insert_nondiagonal(jl_value_t *type, jl_varbinding_t *troot,
         jl_value_t *n = jl_unwrap_vararg_num(type);
         if (widen2ub == 0)
             widen2ub = !(n && jl_is_long(n)) || jl_unbox_long(n) > 1;
-        jl_value_t *newt;
-        JL_GC_PUSH2(&newt, &n);
-        newt = insert_nondiagonal(t, troot, widen2ub);
-        if (t != newt)
+        jl_value_t *newt = insert_nondiagonal(t, troot, widen2ub);
```
Comment (gbaraldi) [inline src/subtype.c:4703]: Is this just an optimization? Or is this the actual fix?

Comment (vtjnash) [reply src/subtype.c:4703]: It is a similar fix, though not actually the one that crashed

File: src/subtype.c [hunk 2]
```diff
@@ -4700,12 +4700,12 @@ static jl_value_t *insert_nondiagonal(jl_value_t *type, jl_varbinding_t *troot,
...
+        if (t != newt) {
+            JL_GC_PUSH1(&newt);
```
Comment (Keno) [inline src/subtype.c:4705]: Could maybe use a comment that `n` doesn't need the root because it derives from `type`? I could see someone accidentally refactoring this to overwrite `type` early.

Comment (vtjnash) [reply src/subtype.c:4705]: The type is an argument, so you cannot overwrite it, and the gc verifier would probably catch that mistake anyways

**Comment by vtjnash** [comment]
We could augment the static analysis to expand this macro to `if (*x) jl_typeof(*x)`, which would trigger the undefined access heuristics to see that as a mistake, but I am not really sure the extra complexity in that check is worthwhile, as this mistake is very rare to see
