### PR TITLE
Fixed #38346: Eigen decomposition of Symmetric Matrix containing NaNs now throws exception

### LINKED ISSUE #780: LinearAlgebra: eigen decomposition of Symmetric Matrix containing NaNs never throws. It just runs forever.
On my (Windows) PC the following runs forever without ever throwing or finishing. The error seems to come from inside LAPACK. The key elements seems to be that the matrix is Symmetric and contains a NaN.
``
using LinearAlgebra
aa = [1 2      3;
         2 NaN 4;
         3 4       5]
bb = Symmetric(aa)
eigen(bb)
``

### LINKED ISSUE #38346: LinearAlgebra: eigen decomposition of Symmetric Matrix containing NaNs never throws. It just runs forever.
On my (Windows) PC the following runs forever without ever throwing or finishing. The error seems to come from inside LAPACK. The key elements seems to be that the matrix is Symmetric and contains a NaN.
``
using LinearAlgebra
aa = [1 2      3;
         2 NaN 4;
         3 4       5]
bb = Symmetric(aa)
eigen(bb)
``

### PR DESCRIPTION
**Pull request by kc611**
Fixes JuliaLang/LinearAlgebra.jl#780.

As suggested by @KlausC in the issue 

> There seems missing a call to `ckfinite` or analogous in `syevr!`

adding a call to 'ckfinite' in 'syevr' is a nice fix for the problem. Since Eigen decomposition for both symmetric and hermitian  matrix is making call to 'syevr' function it fixes the issue for both. Diagonal matrices already had such a fail-safe for NaN values 

https://github.com/JuliaLang/julia/blob/af3cd59e13c93fcb3e3788a79b0168127473d18a/stdlib/LinearAlgebra/src/diagonal.jl#L674-L676

### CODE REVIEW

**Comment by dkarrasch** [comment]
@kc611 Thank you and welcome! Can you please add a test (à la `@test_throws ...`) to make sure the function throws when it should throw?

**Comment by kc611** [comment]
It seems that there was already a test present for Eigen of matrices with NaN values. I extended it's functionality to Symmetric, Hermitian and Diagonal(just in case) ones.

**Review by dkarrasch — DISMISSED** [review]

File: stdlib/LinearAlgebra/src/lapack.jl [hunk 1]
```diff
@@ -5030,6 +5030,7 @@ for (syev, syevr, sygvd, elty) in
                         vl::AbstractFloat, vu::AbstractFloat, il::Integer, iu::Integer, abstol::AbstractFloat)
             chkstride1(A)
             n = checksquare(A)
+            chkfinite(A)
```
Comment (KlausC) [inline stdlib/LinearAlgebra/src/lapack.jl:5033]: I am not sure, that `chfinite` should be called unmodified. As it checks all elements of `A`, that could erroneously throw exceptions, if there is a non-finite element in the unused part of `A`.
Only one triagle of `A` should be checked, dependant on `uplo`.

**Review by KlausC — CHANGES_REQUESTED** [review]

File: stdlib/LinearAlgebra/src/lapack.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/lapack.jl:5033]: Good point.

**Review by JeffBezanson — CHANGES_REQUESTED** [review]
Has comments that need to be addressed.

File: stdlib/LinearAlgebra/src/lapack.jl (hunk 1 above)
Comment (kc611) [reply stdlib/LinearAlgebra/src/lapack.jl:5033]: Looks like this will require adding another function similar to chkfinite() something like :

`function chkuplofinite(A::AbstractMatrix, uplo::AbstractChar)`

which will then check upper or lower part of matrix for non-finite element according to `uplo`
Should I go ahead and implement this?

Comment (kc611) [reply stdlib/LinearAlgebra/src/lapack.jl]: @dkarrasch @KlausC I've added the functionality as requested.

File: stdlib/LinearAlgebra/src/lapack.jl [hunk 2]
```diff
@@ -95,6 +95,23 @@ function chkfinite(A::AbstractMatrix)
     return true
 end
 
+function chkuplofinite(A::AbstractMatrix, uplo::AbstractChar)
+    m, n = size(A)
+    if uplo == 'U'
+        for i in 1:m, j in i:n
```
Comment (KlausC) [inline stdlib/LinearAlgebra/src/lapack.jl:101]: what do you think about changing the loops to iterate column-wise?
` for j = 1:n, i = 1:j`

File: stdlib/LinearAlgebra/src/lapack.jl [hunk 3]
```diff
@@ -95,6 +95,23 @@ function chkfinite(A::AbstractMatrix)
...
+            if !isfinite(A[i,j])
+                throw(ArgumentError("matrix contains Infs or NaNs"))
+            end
+        end
+    else
+        for i in 1:m, j in 1:i
```
Comment (KlausC) [inline stdlib/LinearAlgebra/src/lapack.jl:107]: column order would be
`for j = 1:n, i = j:m`

File: stdlib/LinearAlgebra/src/lapack.jl [hunk 4]
```diff
@@ -95,6 +95,23 @@ function chkfinite(A::AbstractMatrix)
     return true
 end
 
+function chkuplofinite(A::AbstractMatrix, uplo::AbstractChar)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/lapack.jl:98]: To play it safe, I think we should also check that we may indeed assume one-based indexing:
```suggestion
function chkuplofinite(A::AbstractMatrix, uplo::AbstractChar)
    require_one_based_indexing(A)
```

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/lapack.jl:98]: ... and once we have that, the loops below should get a `@inbounds` prepended.

**Comment by kc611** [comment]
Changed the iterations to column-wise (the loops looks a bit clean and consistent that way) and added one based indexing check and `@inbounds` as suggested.

Also I was thinking about adding a test case where the code is not supposed to throw exception. But dropped the idea since I could not find any appropriate way for doing that (#18780). Any suggestions?

**Comment by KlausC** [comment]
To verify, that a test does not throw and exception you could do for example:
```
@test eigen(...) isa Eigen
or
@test something....   !== []
or
@test something...  !== nothing  (if you expect any return type != nothing
```

File: stdlib/LinearAlgebra/test/eigen.jl [hunk 5]
```diff
@@ -101,11 +101,12 @@ end
...
         @test_throws(ArgumentError, eigen(fill(eltya, 2, 2)))
         test_matrix = rand(typeof(eltya),3,3)
-        test_matrix[2,2] = eltya
+        test_matrix[1,3] = eltya
         @test_throws(ArgumentError, eigen(test_matrix))
         @test_throws(ArgumentError, eigen(Symmetric(test_matrix)))
         @test_throws(ArgumentError, eigen(Hermitian(test_matrix)))
-        @test_throws(ArgumentError, eigen(Diagonal(test_matrix)))
+        @test eigen(Symmetric(transpose(test_matrix))) isa Eigen
+        @test eigen(Hermitian(transpose(test_matrix))) isa Eigen
```
Comment (KlausC) [inline stdlib/LinearAlgebra/test/eigen.jl:109]: better use `Symmetric/Hermitian(test_matrix, :L)` to test also this code branch.

**Review by dkarrasch — APPROVED** [review]
LGTM!

**Comment by dkarrasch** [comment]
The usual unrelated test failures. Thank you very much @kc611, and sorry that it took a while. Your contribution is much appreciated!
