### PR TITLE
Also merge var with unchanged bounds.

### LINKED ISSUE #46735: Unreachable reached in AtomicStructures.jl on Julia 1.8.1, but not 1.8.0
https://github.com/JuliaAtoms/AtomicStructure.jl/actions/runs/3042781441/jobs/4901317463#step:6:200

Steps to reproduce:
```julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 32 virtual cores

(v1.8) pkg> activate .
  Activating new project at `/export/stefanos/work/projects/test-code/test-atomic-structure`

(test-atomic-structure) pkg> add AtomicStructure
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/export/stefanos/work/projects/test-code/test-atomic-structure/Project.toml`
  [e24b7630] + AtomicStructure v0.1.2
    Updating `/export/stefanos/work/projects/test-code/test-atomic-structure/Manifest.toml`
  ⋮

(test-atomic-structure) pkg> test AtomicStructure
```
The same test suite works fine on 1.6 and 1.8.0. Will endeavour to produce MWE.

### PR DESCRIPTION
**Pull request by N5N3**
I skipped it as I thought unchanged bounds means there's no restriction added on this var.
But examples from #46735 show that it should not be skiped as the current `env` might not be valid if the var's bounds get fixed (by another Unions decision.)

close #46735. Test added.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
SGTM

File: src/subtype.c [hunk 1]
```diff
@@ -3251,15 +3251,13 @@ static int merge_env(jl_stenv_t *e, jl_value_t **root, jl_savedenv_t *se, int co
...
-            if (v->lb != lb)
-                jl_svecset(*root, n, lb ? jl_bottom_type : v->lb);
-            ub = jl_svecref(*root, n+1);
-            vub = v->ub;
-            if (vub != ub)
-                jl_svecset(*root, n+1, ub ? simple_join(ub, vub) : vub);
-        }
+        jl_value_t *lb = jl_svecref(*root, n);
+        if (v->lb != lb)
+            jl_svecset(*root, n, lb ? v->var->lb : v->lb);
```
Comment (vtjnash) [inline src/subtype.c:3256]: does this need to be a `simple_meet(lb, v->lb)`, or why does this use v->var->lb, but the ub use v->ub? (sorry if this is a dumb question, as I don't understand very well what this is doing)

Comment (N5N3) [reply src/subtype.c:3256]: Oh yes, `simple_meet` should be prefered here. I just forget that we have this tool. (and `v->var->lb` should be a valid low bound here.)
