### PR TITLE
[JuliaLowering] Fix destructured arg handling, improve error messages

### LINKED ISSUE #133: "invalid kind ... in local declaration" when lowering "splatted splat"
This syntax is nearly unreadable to me, but apparently we support it and use it in `Test`!

```julia
julia> Base.JuliaLowering.include_string(Main, raw"""
       _args_and_call((args..., f)...) = (args, f(args))
       """)
ERROR: LoweringError:
_args_and_call((args..., f)...) = (args, f(args))
#               └─────┘ ── invalid kind ... in local declaration

Detailed provenance:
(... args)
└─ (... args)
   └─ (... args ...)
      └─ @ string:1
```

which is supposed to behave similar to what `_args_and_call(args..., f)` looks like it would do:
```julia
julia> foo((head..., tail)...) = (head, tail)
foo (generic function with 1 method)

julia> foo(1,2,3,4)
((1, 2, 3), 4)
```

<details>
<summary>Stacktrace</summary>

```julia
Stacktrace:
    [1] make_lhs_decls(ctx::Base.JuliaLowering.DesugaringContext{…}, stmts::Base.JuliaSyntax.SyntaxList{…}, declkind::Base.JuliaSyntax.Kind, declmeta::Base.ImmutableDict{…}, ex::Base.JuliaSyntax.SyntaxTree{…}, type_decls::Bool)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:2197
    [2] make_lhs_decls(ctx::Base.JuliaLowering.DesugaringContext{…}, stmts::Base.JuliaSyntax.SyntaxList{…}, declkind::Base.JuliaSyntax.Kind, declmeta::Base.ImmutableDict{…}, ex::Base.JuliaSyntax.SyntaxTree{…}, type_decls::Bool)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:2194
    [3] expand_decls(ctx::Base.JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::Base.JuliaSyntax.SyntaxTree{Dict{Symbol, Any}})
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:2213
    [4] expand_forms_2(ctx::Base.JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::Base.JuliaSyntax.SyntaxTree{Dict{Symbol, Any}}, docs::Nothing)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:4527
    [5] expand_forms_2
      @ ~/repos/julia/JuliaLowering/src/desugaring.jl:4420 [inlined]
    [6] #expand_forms_2##2
      @ ~/repos/julia/JuliaLowering/src/desugaring.jl:4656 [inlined]
    [7] mapchildren(f::Base.JuliaLowering.var"#expand_forms_2##2#expand_forms_2##3"{…}, ctx::Base.JuliaLowering.DesugaringContext{…}, ex::Base.JuliaSyntax.SyntaxTree{…}, do_map_child::Base.JuliaSyntax.var"#mapchildren##1#mapchildren##2")
      @ Base.JuliaSyntax ~/repos/julia/usr/share/julia/JuliaSyntax/src/porcelain/syntax_graph.jl:658
 ┌  [8] mapchildren
 │    @ ~/repos/julia/usr/share/julia/JuliaSyntax/src/porcelain/syntax_graph.jl:695 [inlined]
 ├  [9] expand_forms_2(ctx::Base.JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::Base.JuliaSyntax.SyntaxTree{Dict{Symbol, Any}}, docs::Nothing)
 │    @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:4656
 ├ [10] expand_forms_2
 │    @ ~/repos/julia/JuliaLowering/src/desugaring.jl:4420 [inlined]
 ├ [11] expand_forms_2(ctx::Base.JuliaLowering.DesugaringContext{Dict{Symbol, Any}}, ex::Base.JuliaSyntax.SyntaxTree{Dict{Symbol, Any}}, docs::Nothing)
 │    @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/desugaring.jl:4503
 ├ [12] expand_forms_2
 │    @ ~/repos/julia/JuliaLowering/src/desugaring.jl:4420 [inlined]
 ╰───── repeated 10 times
   [58] expand_forms_2
      @ ~/repos/julia/JuliaLowering/src/desugaring.jl:4674 [inlined]
   [59] lower_step(iter::Base.JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module, world::UInt64)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:95
   [60] lower_step(iter::Base.JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:46
   [61] lower_step(iter::Base.JuliaLowering.LoweringIterator{Dict{Symbol, Any}}, mod::Module, world::UInt64)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:71
   [62] lower_step
      @ ~/repos/julia/JuliaLowering/src/eval.jl:46 [inlined]
   [63] _eval(mod::Module, iter::Base.JuliaLowering.LoweringIterator{Dict{Symbol, Any}})
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:478
   [64] #eval#133
      @ ~/repos/julia/JuliaLowering/src/eval.jl:466 [inlined]
   [65] eval
      @ ~/repos/julia/JuliaLowering/src/eval.jl:462 [inlined]
   [66] #include_string#135
      @ ~/repos/julia/JuliaLowering/src/eval.jl:535 [inlined]
   [67] include_string
      @ ~/repos/julia/JuliaLowering/src/eval.jl:533 [inlined]
   [68] include_string(mod::Module, code::String)
      @ Base.JuliaLowering ~/repos/julia/JuliaLowering/src/eval.jl:533
   [69] top-level scope
      @ REPL[4]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by mlechu**
- Take this opportunity to clean up a couple pieces of desugaring given invariants from the validator
- Fix https://github.com/JuliaLang/JuliaLowering.jl/issues/133, which I think was just a simple failure to recurse.  Test.jl now precompiles!
- Test every function arg form that I know flisp accepts
- Test error messages for function arg forms that the validator rejects

### CODE REVIEW

File: JuliaLowering/test/functions.jl [hunk 1]
```diff
@@ -512,13 +512,153 @@ end
     @test cl(x = 20) == 21
 end
 
+@testset "all known valid positional argument forms" begin
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:553]: As usual, very pleased to have coverage like this. Thank you.

File: JuliaLowering/test/functions.jl [hunk 2]
```diff
@@ -512,13 +512,153 @@ end
...
+    begin
+        f_vararg_tuple = function ((x,(y,z)...)...=(1,(2,3)...)...)
+            (x,y,z)
+        end
+        f_vararg_tuple(4,5,6,7), f_vararg_tuple()
+    end
+    """) === ((4,5,6), (1,2,3))
+    @test JuliaLowering.include_string(test_mod, """
+    begin
+        f_vararg_tuple = function ((x,y,z)::Tuple...)
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:675]: Do you have coverage also for `Vararg` in type position?

Thinking of stuff like:
```julia
julia> foo(x::Vararg{Int}) = x
julia> foo(1,2,3)
(1, 2, 3)
julia> bar((a,b,c)::Vararg{Int}) = (a,b,c)
julia> bar(1,2,3)
(1, 2, 3)
julia> baz(((a,b)...,c)::Vararg{Int}) = (a,b,c)
julia> baz(1,2,3)
(1, 2, 3)
julia> quaf(((a,b)...,c)::Vararg{Tuple{Vararg{Int}}}) = (a,b,c)
julia> quaf((1,2),(3,),(4,))
((1, 2), (3,), (4,))
```

I believe this is essentially equivalent to `...` but just to be sure.

File: JuliaLowering/test/functions.jl [hunk 3]
```diff
@@ -512,13 +512,153 @@ end
...
+        end
+    end
+    """) isa Function
+    @test JuliaLowering.include_string(test_mod, """
+    begin
+        f_vararg_tuple = function ((;x,y,z)::NamedTuple...)
+            (x,y,z)
+        end
+    end
+    """) isa Function
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:693]: Is there a reason we don't execute these?

File: JuliaLowering/test/functions.jl [hunk 4]
```diff
@@ -512,13 +512,153 @@ end
...
+    begin
+        f_vararg_tuple = function ((x,y,z)...)
+            (x,y,z)
+        end
+        f_vararg_tuple(1,2,3), f_vararg_tuple(1,2,3,4,5)
+    end
+    """) === ((1,2,3), (1,2,3))
+    @test JuliaLowering.include_string(test_mod, """
+    begin
+        f_vararg_tuple = function ((x,y,z)...=(1,2,3)...)
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:649]: These should probably all get unique names to make sure lowering doesn't accidentally create an unexpected dispatch type and you end up testing an old definition.

File: JuliaLowering/test/functions.jl [hunk 5]
```diff
@@ -512,13 +512,153 @@ end
...
+            else
+                Expr(:(::), p, Any)
+            end
+        end
+        new_ps => vals
+    end
+
+    pparams_req = let
+        # tuple of params => tuple of acceptable values
+        pparams_untyped = [
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:575]: It would be nice to cover some "overrun" cases as well:
```julia
julia> foo(((a, b), c) = ((1,2,3), (4,5,6), (7,8))...) = (a,b,c)
julia> foo()
(1, 2, (4, 5, 6))
julia> foo((1,2,3), (4,5), (6,7))
(1, 2, (4, 5))
```

File: JuliaLowering/src/validation.jl [hunk 6]
```diff
@@ -724,51 +717,70 @@ function _calldecl_positionals(vcx, params_meta, kw_kind)
...
-    [K"..." t] -> vst1_param_simple_tuple(vcx, t)
-    t -> vst1_param_simple_tuple(vcx, t)
+vst1_pparam_simple_tuple_or_splat(vcx, st) = @stm st begin
+    [K"..." t] -> vst1_pparam_simple_tuple(vcx, t)
+    t -> vst1_pparam_simple_tuple(vcx, t)
 end
-
-vst1_param_simple_tuple(vcx, st) = @stm st begin
+# Similar to an assignment to a tuple LHS, but does not allow `::`.  Also should
+# not allow ref, curly, or call, but flisp does, so we may need to change this.
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl:753]: Ah this is what @xal-0 mentioned the other day.

I like the idea of starting with this restriction and seeing where we hit this in the ecosystem.

**Review by topolarity — APPROVED** [review]
Thanks! A couple of requests for addl. tests, but no major issues.

FWIW I did not review the desugaring changes in detail, so let me know if there's something that you'd like eyes on.

> Test.jl now precompiles!

Superb. Just a few left!

File: JuliaLowering/test/functions.jl [hunk 7]
```diff
@@ -512,13 +512,153 @@ end
...
+            @test ((func_ref = Core.eval(test_mod, reference_lower(test_mod, f_expr))) isa Function)
+            @test ((func_test = JuliaLowering.eval(test_mod, f_st)) isa Function)
+            Core.@latestworld
+            @test func_ref(args_i...) == func_test(args_i...)
+        end
+    end
+
+    pparams_default = map(make_defaults, pparams_req)
+
+    @testset "default args" for (params_i, args_i) in pparams_default
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:621]: Does this also cover "misplaced" `...` cases like:
```julia
julia> foo(x = 5...) = x # ... is allowed here, but does nothing
julia> foo(1, 2)
ERROR: MethodError: no method matching foo(::Int64, ::Int64)
julia> foo()
5
```

File: JuliaLowering/test/functions.jl [hunk 8]
```diff
@@ -512,13 +512,153 @@ end
...
+                                   Expr(:call, gensym(), params_i...),
+                                   Expr(:tuple, :x, :y, :z)),
+                    f_st = JuliaLowering.expr_to_est(f_expr)
+
+            local func_ref, func_test
+            @test ((func_ref = Core.eval(test_mod, reference_lower(test_mod, f_expr))) isa Function)
+            @test ((func_test = JuliaLowering.eval(test_mod, f_st)) isa Function)
+            Core.@latestworld
+            @test func_ref(args_i...) == func_test(args_i...)
+            @test func_ref() == func_test()
```
Comment (topolarity) [inline JuliaLowering/test/functions.jl:632]: One more suggestion: it would be nice if these tests checked that the method(s) were defined with the right `atype` (tuple signature type).

```julia
julia> foo(x::Tuple{Any,Any}...) = x
julia> only(methods(foo)).sig
Tuple{typeof(foo), Vararg{Tuple{Any, Any}}}
```

File: JuliaLowering/test/functions.jl (hunk 2 above)
Comment (mlechu) [reply JuliaLowering/test/functions.jl:675]: Thanks for these examples; I'll add them as tests.  (They shouldn't go through much of the desugaring I tweaked here because `Vararg` is the already-desugared form, but we want them anyway)

File: JuliaLowering/test/functions.jl (hunk 3 above)
Comment (mlechu) [reply JuliaLowering/test/functions.jl:693]: These are the uncallable-but-allowed-by-lowering cases mentioned in the comment above.  The tests are just me being careful in case flisp is allowing them on purpose and there is a way to call these that I'm missing. I could block them in the validator if we want.

File: JuliaLowering/test/functions.jl (hunk 4 above)
Comment (mlechu) [reply JuliaLowering/test/functions.jl:649]: I should be using `let` here instead of `begin`, but creating an anonymous function `x = function (args...)` shouldn't do that (though correct me if I'm wrong)

File: JuliaLowering/test/functions.jl (hunk 7 above)
Comment (mlechu) [reply JuliaLowering/test/functions.jl:621]: Thanks, I didn't know that could be done.  Looks like we intend to support this for the final parameter only (https://github.com/JuliaLang/julia/pull/50563)

File: JuliaLowering/test/functions.jl (hunk 3 above)
Comment (topolarity) [reply JuliaLowering/test/functions.jl:693]: Ah right, the "Tuple has no field x" case - I think you're right that these are uncallable.

Semi-related, it's probably worth it to have some (non-splatted) NamedTuple argument destructuring tests, unless I missed those somewhere else.

Doesn't have to hold up this change though

File: JuliaLowering/test/functions.jl (hunk 4 above)
Comment (topolarity) [reply JuliaLowering/test/functions.jl:649]: My eyes were on the call-site and I didn't even notice this was anonymous

Good point, should be OK 👍

File: JuliaLowering/test/functions.jl (hunk 7 above)
Comment (topolarity) [reply JuliaLowering/test/functions.jl:621]: Yeah I think the intention is for the argument to be splatted / `Vararg` too, but this also works as a quirk

Based on Keno's change, we might get away with forbidding this for a non-Vararg final parameter one day

File: JuliaLowering/test/functions.jl (hunk 3 above)
Comment (mlechu) [reply JuliaLowering/test/functions.jl:693]: Should be tested here
https://github.com/JuliaLang/julia/pull/60880/changes#diff-d05944d22d6ce13a0a22565a6463271ec4f17a1be583dbc8c212e3b9b4c648f1R585-R587

**Comment by mlechu** [comment]
Going to let #60885 merge first so the box checker can get in; will fix conflicts here
