### PR TITLE
predicate function negation with ComposedFunction

### LINKED ISSUE #44748: !foo should use (!) ∘ foo
As [discussed on Discourse](https://discourse.julialang.org/t/base-including-notnan-notnothing/78458/7), it would be nice to have `!foo` return a `ComposedFunction`, which would

1. allow dispatch and specialized methods for `!foo`
2. allow nicer pretty printing of `!foo` as `"!foo"` rather than as `"#xx (generic function with 1 method)"` (by overloading `show` for `ComposedFunction{typeof(!)}`)
3. allow `!!foo === foo`

Although `!foo` and `f ∘ g` were introduced at the same time in #17155, when `∘` was subsequently updated in Julia 1.6 to return a special `ComposedFunction` type (#37517), the `!` implementation was not correspondingly updated, which seems like an oversight.

On a related note, it would also be good to fix the `ComposedFunction` show method to put parentheses around operators (or other composed functions), as this is currently broken:
```jl
julia> (!) ∘ isnan
! ∘ isnan

julia> ! ∘ isnan
ERROR: syntax: "∘" is not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1
```

Should be a fairly easy PR.

### PR DESCRIPTION
**Pull request by markmbaum**
Closes #44748 , this small PR does the following
* redefines predicate function negation `!(f::Function) = (!) ∘ f`
* updates the `show` method for `ComposedFunction` to print operators in parentheses
* adds a method for `!(f::ComposedFunction{typeof(!)})` that allows `!!f === f`
* adds a test for `!!f === f` and a few tests for showing composed functions

thanks for the tutelage @stevengj !

### CODE REVIEW

File: base/operators.jl [hunk 1]
```diff
@@ -1035,11 +1035,20 @@ end
 ∘(f, g, h...) = ∘(f ∘ g, h...)
 
 function show(io::IO, c::ComposedFunction)
-    show(io, c.outer)
+    if c.outer |> Symbol |> Base.isoperator
+        print(io, '(', c.outer, ')')
+    else
+        show(io, c.outer)
+    end
```
Comment (stevengj) [inline base/operators.jl:1042]: Probably cleaner to have a
```jl
showfunction(io::IO, f) = show(io, x)
showfunction(io::IO, f::Function) = Base.isoperator(Symbol(f)) ? print(io, '(', f, ')') : show(io, f)
showfunction(io::IO, f::ComposedFunction) = print(io, '(', f, ')')
```
and then call this for both `inner` and `outer`.

File: base/operators.jl [hunk 2]
```diff
@@ -1035,11 +1035,20 @@ end
...
     print(io, " ∘ ")
     show(io, c.inner)
 end
 
+function show(io::IO, c::ComposedFunction{typeof(!)})
+    print(io, "!")
```
Comment (stevengj) [inline base/operators.jl:1048]:
```suggestion
    print(io, '!')
```

File: test/operators.jl [hunk 3]
```diff
@@ -179,6 +179,7 @@ end
     str = randstring(20)
     @test filter(!isuppercase, str) == replace(str, r"[A-Z]" => "")
     @test filter(!islowercase, str) == replace(str, r"[a-z]" => "")
+    @test !!isnan === isnan
```
Comment (stevengj) [inline test/operators.jl:182]: Maybe
```jl
@test repr(!isnan) == "!isnan"
@test repr((-) ∘ sin) == "(-) ∘ sin"
```
to test the `show` methods.

File: base/operators.jl (hunk 1 above)
Comment (stevengj) [reply base/operators.jl:1042]: Note that `print` output` can differ from `show`, so we want to be careful to distinguish the two:
```jl
julia> show(sin ∘ cos)
sin ∘ cos
julia> print(sin ∘ cos)
ComposedFunction{typeof(sin), typeof(cos)}(sin, cos)
```

Comment (stevengj) [reply base/operators.jl:1042]: We might also want to define:
```jl
function show_function(io::IO, c::ComposedFunction, compact::Bool)
    if compact
        show(io, f)
    else
        print(io, "ComposedFunction(")
        show_function(io, c.outer, false)
        print(io, ", ")
        show_function(io, c.inner, false)
        print(io, ')')
    end
end
````
with a fallback
```jl
show_function(io::IO, x, compact::Bool) = show(io, x)
```
in case the `inner` or `outer` field is not a `Function`.

This way, `print` won't print the `typeof` (which is redundant), and the `compact` parameter will nest.

File: base/operators.jl [hunk 4]
```diff
@@ -1035,11 +1035,25 @@ end
...
+    _showcomposed(io, c.inner)
+end
+
+_showcomposed(io::IO, x) = show(io, x)
+#display operators like + and - inside parens
+_showcomposed(io::IO, f::Function) = isoperator(Symbol(f)) ? (print(io, '('); show(io, f); print(io, ')')) : show(io, f)
+#nesting for chained composition
+_showcomposed(io::IO, f::ComposedFunction) = (print(io, '('); show(io, f); print(io, ')'))
+#no nesting when ! is the outer function in a composition chain
+_showcomposed(io::IO, f::ComposedFunction{typeof(!)}) = (print(io, '!'); show(io, f.inner))
```
Comment (markmbaum) [inline base/operators.jl:1055]: an additional method was needed here to show `!sin ∘ cos` instead of `(!sin) ∘ cos`

File: base/show.jl [hunk 5]
```diff
@@ -468,6 +468,20 @@ end
 show(io::IO, f::Function) = show_function(io, f, get(io, :compact, false)::Bool)
 print(io::IO, f::Function) = show_function(io, f, true)
 
+function show_function(io::IO, c::ComposedFunction, compact::Bool)
```
Comment (stevengj) [inline base/show.jl:471]: I would put this method into operators.jl along with the other `ComposedFunction` methods.

File: base/operators.jl (hunk 4 above)
Comment (stevengj) [inline base/operators.jl:1055]:
```suggestion
_showcomposed(io::IO, f::ComposedFunction{typeof(!)}) = show(io, f)
```

File: base/operators.jl [hunk 6]
```diff
@@ -1035,11 +1035,25 @@ end
 ∘(f, g, h...) = ∘(f ∘ g, h...)
 
 function show(io::IO, c::ComposedFunction)
-    show(io, c.outer)
+    _showcomposed(io, c.outer)
```
Comment (stevengj) [inline base/operators.jl:1038]:
```suggestion
    c.outer isa ComposedFunction ? show(io, c.outer) : _showcomposed(io, c.outer)
```
This way `f ∘ g ∘ h` will print as `"f ∘ g ∘ h"` and not `"(f ∘ g) ∘ h"`

File: base/operators.jl [hunk 7]
```diff
@@ -1060,7 +1074,8 @@ julia> filter(!isletter, str)
 "∀  > 0, ∃  > 0: |-| <  ⇒ |()-()| < "
 ```
 """
-!(f::Function) = (x...)->!f(x...)
+!(f::Function) = (!) ∘ f
+!(f::ComposedFunction{typeof(!)}) = f.inner #allows !!f === f
```
Comment (martinholters) [inline base/operators.jl:1078]: This may come as a surprise if there is a `!` definition for some type `T` such that `!!(x::T) != x`, as then we may have `!!f(x) != (!!f)(x)` if the return type of `f` is `T`. But probably that's just an argument for not defining such a `!`.

Comment (markmbaum) [reply base/operators.jl:1078]: I was wondering about this. It wouldn't cause problems to allow `!!f` definitions even though I can't imagine a reason to do so.

Comment (StefanKarpinski) [reply base/operators.jl:1092]: That's a good point, @martinholters, but I think your take that it's an argument for not doing that is where I fall on that. If they really want to they can always overload `!` for their function as an escape hatch.

**Review by StefanKarpinski — APPROVED** [review]

File: test/operators.jl [hunk 8]
```diff
@@ -179,6 +179,11 @@ end
...
+    @test repr(!isnan) == "!isnan"
+    @test repr((-) ∘ sin) == "(-) ∘ sin"
+    @test repr(cos ∘ (sin ∘ tan)) == "cos ∘ (sin ∘ tan)"
```
Comment (stevengj) [inline test/operators.jl:185]:
```suggestion
    @test repr(cos ∘ (sin ∘ tan)) == "cos ∘ (sin ∘ tan)"
    @test repr(cos ∘ sin ∘ tan) == "cos ∘ sin ∘ tan" == repr((cos ∘ sin) ∘ tan) 
```

File: base/operators.jl [hunk 9]
```diff
@@ -1035,11 +1035,39 @@ end
...
+    else
+        print(io, "ComposedFunction(")
+        show_function(io, c.outer, false)
+        print(io, ", ")
+        show_function(io, c.inner, false)
+        print(io, ')')
+    end
+end
+
+show_function(io::IO, x, ::Bool) = show(io, x)
```
Comment (stevengj) [inline base/operators.jl:1069]: This fallback method should be in `show.jl` where `show_function` is defined.

**Review by stevengj — DISMISSED** [review]

**Comment by stevengj** [comment]
Should have an item in `NEWS.md`.

File: base/operators.jl [hunk 10]
```diff
@@ -1060,7 +1086,8 @@ julia> filter(!isletter, str)
 "∀  > 0, ∃  > 0: |-| <  ⇒ |()-()| < "
```
Comment (stevengj) [inline base/operators.jl:1086]: The docs for `!f` should be updated to say that it returns a `ComposedFunction`, with a compat note indicating that this is new in 1.9

**Review by stevengj — APPROVED** [review]

File: base/operators.jl (hunk 1 above)
Comment (JeffBezanson) [reply base/operators.jl]: This behavior of `print` looks like a bug to me; if `print` is called then `show_function` should fall back to `show` instead of `show_default`. So I don't think methods should be added to `show_function`, we can fix it instead.

**Comment by DilumAluthge** [comment]
`cmdlineargs` failures on `test_x86_64-apple-darwin` are https://github.com/JuliaLang/julia/issues/44947
