### PR TITLE
fix #39600: broadcast fusion broken for comparison

### LINKED ISSUE #39600: Dotted comparison chains don't fuse with surrounding dotted calls
I'd expect the following to create just one fused loop, but it creates two (two `materialize`s):

```julia-repl
julia> Meta.@lower (!).(1 .< A .< 2)
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.broadcasted(<, 1, A)
│   %2 = Base.broadcasted(<, A, 2)
│   %3 = Base.broadcasted(&, %1, %2)
│   %4 = Base.materialize(%3)
│   %5 = Base.broadcasted(!, %4)
│   %6 = Base.materialize(%5)
└──      return %6
))))
```

It should look like:

```julia-repl
julia> Meta.@lower  (!).((1 .< A) .& (A .< 2))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.broadcasted(<, 1, A)
│   %2 = Base.broadcasted(<, A, 2)
│   %3 = Base.broadcasted(&, %1, %2)
│   %4 = Base.broadcasted(!, %3)
│   %5 = Base.materialize(%4)
└──      return %5
))))
```

### PR DESCRIPTION
**Pull request by simeonschaub**
fixes #39600

### CODE REVIEW

File: test/syntax.jl [hunk 1]
```diff
@@ -2696,3 +2696,14 @@ end == 4
     x25652 = x+3
     x25652
 end == 4
+
+@testset "issue #39600" begin
+    A = 1:.5:2
+    @test (!).(1 .< A .< 2) == [true, false, true]
+    @test .!(1 .< A .< 2) == [true, false, true]
+    @test (.!)(1 .< A .< 2) == [true, false, true]
```
Comment (simeonschaub) [inline test/syntax.jl:2704]: Fun fact: these all have slightly different surface syntax :)

**Review by JeffBezanson — APPROVED** [review]
