### PR TITLE
Artifacts: use a different way of getting the UUID of a module

### LINKED ISSUE #54930: Overrides.toml broken on master
It seems that somehow (and in no way obvious to me how) commit https://github.com/JuliaLang/julia/commit/a1a2ac63cffd11f0edc3fe730797023867d82527 (#54739) broke the use of the Overrides.toml file. Details of the testing I did:

/home/bjanssens/.julia/artifacts/Overrides.toml:
```toml
[3eaa8342-bff7-56a5-9981-c04077f7cee7]
libcxxwrap_julia = "/home/bjanssens/src/build/libcxxwrap_julia"
```

Normal Overrides.toml behavior (tested on Julia 1.10 here):
```julia
julia> using libcxxwrap_julia_jll, Libdl

julia> println.(filter(x -> contains(x, "cxx"), dllist()));
/home/bjanssens/.julia/compiled/v1.10/libcxxwrap_julia_jll/9VnAb_YexWl.so
/home/bjanssens/src/build/libcxxwrap_julia/lib/libcxxwrap_julia.so
/home/bjanssens/src/build/libcxxwrap_julia/lib/libcxxwrap_julia_stl.so
```

Behavior on Julia master at or after commit `a1a2ac6`:
```julia
julia> using libcxxwrap_julia_jll, Libdl
[ Info: Precompiling libcxxwrap_julia_jll [3eaa8342-bff7-56a5-9981-c04077f7cee7] (cache misses: invalid header (4))

julia> println.(filter(x -> contains(x, "cxx"), dllist()));
/home/bjanssens/.julia/compiled/v1.12/libcxxwrap_julia_jll/9VnAb_MRJjp.so
/home/bjanssens/.julia/artifacts/9a7be4f65e83c37ef55fd1b9e2e6b3361fd0a483/lib/libcxxwrap_julia.so
/home/bjanssens/.julia/artifacts/9a7be4f65e83c37ef55fd1b9e2e6b3361fd0a483/lib/libcxxwrap_julia_stl.so
```

I have tested this with an `Overrides.toml` both in `~/.julia/artifacts` and in `usr/local/share/julia/artifacts/` in the Julia build dir.

### PR DESCRIPTION
**Pull request by KristofferC**
Hopefully fixes https://github.com/JuliaLang/julia/issues/54930 but I don't know how to reproduce the issue.

cc @barche, @staticfloat, @vtjnash

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by barche** [comment]
I confirm that this fixes the issue for me, even though I'll probably be migrating to using a preferences file instead.

File: stdlib/Artifacts/src/Artifacts.jl [hunk 1]
```diff
@@ -546,9 +546,10 @@ end
 
 function _artifact_str(__module__, artifacts_toml, name, path_tail, artifact_dict, hash, platform, @nospecialize(lazyartifacts))
     moduleroot = Base.moduleroot(__module__)
-    if haskey(Base.module_keys, moduleroot)
+    pkg = Base.PkgId(moduleroot)
```
Comment (vtjnash) [inline stdlib/Artifacts/src/Artifacts.jl:549]:
```suggestion
    pkg = Base.PkgId(__module__)
```
