### PR TITLE
inference: fix and improve instanceof_tfunc-based queries

### LINKED ISSUE #23045: `isa` miscompile
Consider the following:
```
julia> struct F{X}
       end

julia> struct A; end

julia> struct B; end

julia> x = F{A}()
F{A}()

julia> isa(x, F{B})
false

julia> foo(x, k) = isa(x, F{k})
foo (generic function with 1 method)

julia> foo(x, B)
true

julia> @code_typed foo(x, B)
CodeInfo(:(begin
        return false
    end)) => Bool
```
Happens on both 0.6 and master. Similar to #22779 perhaps.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #23045

### CODE REVIEW

File: test/inference.jl [hunk 1]
```diff
@@ -1101,4 +1101,51 @@ let isa_tfunc = Core.Inference.t_ffunc_val[
...
+    @test subtype_tfunc(DataType, Const(Type{Int})) === Bool
+    @test subtype_tfunc(DataType, Const(Type{Array})) === Bool
+    @test subtype_tfunc(UnionAll, Const(Type{Int})) === Bool
+    @test subtype_tfunc(UnionAll, Const(Type{Array})) === Bool
+    @test subtype_tfunc(Union, Const(Union{Float32, Float64})) === Bool
+    @test subtype_tfunc(Union, Type{Union}) === Bool
+    @test subtype_tfunc(Union{}, Const(Int)) === Const(true) # any result is ok
+    @test subtype_tfunc(Union{}, Const(Union{})) === Const(true) # any result is ok
+    @test subtype_tfunc(Union{}, typeof(Union{})) === Bool # any result is ok
+    @test subtype_tfunc(Union{}, Union{}) === Const(true) # any result is ok
```
Comment (JeffBezanson) [inline test/inference.jl]: I wouldn't expect this to be called on `Union{}` much, if ever. Probably should test `Type{Union{}}` instead of or in addition to this.

**Review by JeffBezanson — APPROVED** [review]
