### PR TITLE
Don't error when transposing a single character

### LINKED ISSUE #45417: `EOFError` in the REPL on pressing `ctrl+t` after typing a single character
Steps to reproduce
```julia
julia> # press any alphanumeric character key here, eg 'a', followed by ctrl + t

julia> a┌ Error: Error in the keymap
│   exception =
│    EOFError: read end of file
│    Stacktrace:
│      [1] read
│        @ ./iobuffer.jl:217 [inlined]
│      [2] read
│        @ ./io.jl:776 [inlined]
│      [3] edit_transpose_chars(buf::IOBuffer)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:1094
│      [4] edit_transpose_chars(s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:1086
│      [5] (::REPL.LineEdit.var"#163#218")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2397
│      [6] #invokelatest#2
│        @ ./essentials.jl:799 [inlined]
│      [7] invokelatest
│        @ ./essentials.jl:796 [inlined]
│      [8] (::REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#163#218", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:1533
│      [9] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2665
│     [10] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2567
│     [11] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/REPL.jl:1253
│     [12] (::REPL.var"#49#54"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL ./task.jl:494
└ @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2667

julia> VERSION
v"1.9.0-DEV.624"
```

From the [discourse thread](https://discourse.julialang.org/t/what-does-the-repl-keybinding-ctrl-t-correspond-to/81424/2), I understand that `ctrl+t` performs a character transpose. Perhaps this should be a no-op if there's only one character on the line?

### PR DESCRIPTION
**Pull request by perryprog**
This fixes an issue where an error would be thrown in the REPL if you tried to transpose an input that was a single character while your cursor was to the right of that character (e.g., "A|"). To fix this, let's move left once before we check for if we're at the start of a line. This does change behavior slightly in that the cursor can move left once without actually transposing anything, but this seems to match what Emacs does with M-x transpose-chars in an equivalent situation.

Fixes #45417.

### CODE REVIEW

File: stdlib/REPL/test/lineedit.jl [hunk 1]
```diff
@@ -375,6 +375,16 @@ let buf = IOBuffer()
     @test content(buf) == "βγαεδ"
     LineEdit.edit_transpose_chars(buf)
     @test content(buf) == "βγαδε"
+
+    seek(buf, 0)
+    @inferred(LineEdit.edit_clear(buf))
```
Comment (perryprog) [inline stdlib/REPL/test/lineedit.jl:380]: And a quick question: this probably doesn't need to have a `@inferred`, right? (Though I imagine it doesn't really matter.)

Comment (KristofferC) [reply stdlib/REPL/test/lineedit.jl:380]: I think it was added to the other places as some type instabilities in the REPL was addressed.
