### PR TITLE
Precompile out of env deps in serial within precompilepkgs

### LINKED ISSUE #59121: Unclear error message when needing to precompile due to incompatible stacked environment
Just wanted to record this from our discussion earlier.
When you have a stacked environment with a package in your default environment that's incompatible with your current environment, you get this unclear message:
```
(project env) pkg> precompile

julia> using GLMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] (cache misses: wrong source (4), incompatible header (2), mismatched flags (2))
```

This is made more confusing by `]precompile` doing nothing.

I wouldn't want precompilation to switch into my default environment, but including something in the error message indicating this incompatibility would be helpful.

Julia 1.11.6.

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/59121

Brings serial precompilation jobs into the parallel precompilation job, so users don't have to hit the old error-looking serial log path.

These jobs will likely take longer because they may be precompiling their deps internally, so the `(serial)` label has been added.

## Master

Screenshot 2025-07-28 at 5 10 32 PM

## PR

Screenshot 2025-07-28 at 5 12 22 PM

Screenshot 2025-07-28 at 5 12 45 PM

## Todo
- [x] Explain what `(serial)` means in the docs

### CODE REVIEW

File: base/precompilation.jl [hunk 1]
```diff
@@ -630,15 +649,28 @@ function _precompilepkgs(pkgs::Vector{String},
     end
     @debug "precompile: extensions collected"
 
+    serial_deps = Base.PkgId[] # packages that are being precompiled in serial
+
+    if _from_loading && !isempty(requested_pkgs)
```
Comment (vtjnash) [inline base/precompilation.jl]: SGTM
```suggestion
    if _from_loading
```

File: base/precompilation.jl [hunk 2]
```diff
@@ -468,6 +483,7 @@ function precompilepkgs(pkgs::Vector{String}=String[];
                         fancyprint::Bool = can_fancyprint(io) && !timing,
                         manifest::Bool=false,
                         ignore_loaded::Bool=true)
+    @debug "precompilepkgs called with: pkgs=$(pkgs), internal_call=$(internal_call), strict=$(strict), warn_loaded=$(warn_loaded), timing=$(timing), _from_loading=$( _from_loading), configs=$(configs), io=$(io), fancyprint=$(fancyprint), manifest=$(manifest), ignore_loaded=$(ignore_loaded)"
```
Comment (vtjnash) [inline base/precompilation.jl]: String interpolation is strongly frowned upon since it has terrible formatting and performance
```suggestion
    @debug "precompilepkgs called with" pkgs internal_call strict warn_loaded timing _from_loading configs fancyprint manifest ignore_loaded
```

**Comment by IanButterworth** [comment]
One thing that needs figuring out here is that the previous `[Info : Precompiling` logs were hidden `@debug`s on non-interactive mode. But `Base.precompilepkgs` always prints to stderr (unless there's nothing to be done).

So there are some tests that actually precompile packages that are being tripped up that monitor stderr.

I'm not sure whether to fix tests here, or restore that hidden precompilation behavior..

---

I opted to keep it printing to stderr in noninteractive mode too and fix tests. I think its ok to print this stuff to stderr.

File: base/precompilation.jl (hunk 2 above)
Comment (IanButterworth) [reply base/precompilation.jl]: My bad. I know better. Bad tab completion suggestion

**Comment by topolarity** [comment]
> the (serial) label has been added.

Should this be labelled `(non-parallel)` or `(single-process)`?

And should it be attached to the `Precompiling...` prompt, instead of individual packages?

I worry that `(serial)` is only obvious if you've already been taught what "serial pre-compilation" means - One might walk away with the impression that this is compiling a customized version of the package (esp. since that's what, e.g., gray `-O3` text in the same spot means)

**Comment by IanButterworth** [comment]
`(non-parallel)` SGTM
