### PR TITLE
effects: taint `:consistent`-cy on `:inbounds` and `:boundscheck` exprs

### LINKED ISSUE #48099: Failing boundscheck tests aren't running
[boundscheck.jl](https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/boundscheck.jl) spawns Julia processes to execute [boundscheck_exec.jl](https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/boundscheck_exec.jl) with different values for the `--check-bounds` flag.

For the `--check-bounds=auto` case, it omits the `--check-bounds` flag since it's the default value:
https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/boundscheck.jl#L5

The problem is the command returned by `Base.julia_cmd()` includes flags that were used to spawn the current Julia process. Since all the test processes are [run with `--check-bounds=yes`](https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/Makefile#L26), that means this process is actually running with `--check-bounds=yes` instead of `auto`.

It's easy to fix by explicitly adding `--check-bounds=auto` to the command. Doing that uncovers some failing tests:
```
Test Failed at test/boundscheck_exec.jl:35
  Expression: A1_wrap() == 0
   Evaluated: 1 == 0
```

There are a few other failures in there too. Don't know yet what the proper fixes are.

Original thread from another issue: https://github.com/JuliaLang/julia/pull/48003#discussion_r1060247756

### PR DESCRIPTION
**Pull request by aviatesk**
- taint `:consistent`-cy on `:boundscheck` expr
- taint `:consistent`-cy on `:inbounds` expr N.B it turns out that we didn't taint it correctly before, since `jl_code_info_set_ir` encodes `:inbounds` expressions into `ssaflags` and eliminates them before abstract interpretation
- improved `ntuple` effects slightly

fix #48099

### CODE REVIEW

**Review by Keno — APPROVED** [review]

File: base/compiler/inferencestate.jl [hunk 1]
```diff
@@ -184,7 +184,7 @@ mutable struct InferenceState
         #       are stronger than the inbounds assumptions, since the latter
         #       requires dynamic reachability, while the former is global).
         inbounds = inbounds_option()
-        noinbounds = inbounds === :on || (inbounds === :default && !any_inbounds(code))
+        noinbounds = inbounds === :on || (inbounds === :default && all(flag::UInt8->iszero(flag&IR_FLAG_INBOUNDS), src.ssaflags))
```
Comment (aviatesk) [inline base/compiler/inferencestate.jl:187]: On further thought, we probably need to taint :consistent-cy _always_ when we see `:inbounds` or `:boundscheck` expressions since e.g. a `-check-bounds=no` session may use cache that is generated in `-check-bounds=yes`?
In other word, I think we can't do this until we separate cache with boundscheck flag.

Comment (KristofferC) [reply base/compiler/inferencestate.jl:187]: But they are separated now I think. Since the Pkg image stuff.

Comment (vchuravy) [reply base/compiler/inferencestate.jl:187]: With `--pkgimage=yes` the caches are split, with `--pkgimage=no` they aren't.

Comment (aviatesk) [reply base/compiler/inferencestate.jl:187]: Okay, then I think we can safely skip tainting `:consistent`-cy when abstract interpret sees `:inbounds`/`:boundscheck` exprs if `--pkgimages=yes && --checkbounds=yes`.

A next question would be: is it fast enough to check `JLOptions().[use_pkgimages|check_bounds]` during abstract interpret?

Comment (Keno) [reply base/compiler/inferencestate.jl:187]: They are split with pkgimages, but the sysimage itself is still not split, so we can't do this.

File: base/math.jl [hunk 2]
```diff
@@ -192,24 +192,24 @@ evalpoly(x, p::AbstractVector) = _evalpoly(x, p)
 function _evalpoly(x, p)
     Base.require_one_based_indexing(p)
     N = length(p)
-    ex = p[end]
+    ex = getfield(p, N)
```
Comment (aviatesk) [inline base/math.jl:195]:
```suggestion
    ex = p[N]
```

File: base/math.jl [hunk 3]
```diff
@@ -192,24 +192,24 @@ evalpoly(x, p::AbstractVector) = _evalpoly(x, p)
...
     for i in N-1:-1:1
-        ex = muladd(x, ex, p[i])
+        ex = muladd(x, ex, getfield(p, i))
```
Comment (aviatesk) [inline base/math.jl:197]:
```suggestion
        ex = muladd(x, ex, p[i])
```

File: base/compiler/inferencestate.jl (hunk 1 above)
Comment (aviatesk) [reply base/compiler/inferencestate.jl:187]: So we need to taint `:consistent`-cy always upon :inbounds or :boundscheck expressions, and probably want to remove these `:noinbounds` effect bits until we completely separate cache by boundscheck flag?

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48158#issuecomment-1375424320) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/643a0fc_vs_708d1bd/report.md).

File: base/compiler/abstractinterpretation.jl [hunk 4]
```diff
@@ -2169,22 +2169,35 @@ function abstract_eval_cfunction(interp::AbstractInterpreter, e::Expr, vtypes::V
...
+            if isexpr(stmt, :call)
+                f = abstract_eval_value(interp, stmt.args[1], vtypes, sv)
+                if f isa Const && f.val === getfield
+                    # boundscheck of `getfield` call is analyzed by tfunc potentially without
+                    # tainting :consistent-cy when it's known to be nothrow
+                    @goto delay_effects_analysis
+                end
+            end
+        end
+        merge_effects!(interp, sv, Effects(EFFECTS_TOTAL; consistent=ALWAYS_FALSE, noinbounds=false))
```
Comment (aviatesk) [inline base/compiler/abstractinterpretation.jl:2192]: I really don't like this hack, but I'd like to have it for now since we end up tainting :consistent`-cy of `getindex(::Tuple, ::Int)` call too aggressively even when it's known to be nothrow.
