### PR TITLE
Fix problems with TypeVars in intersection and type_match_

### LINKED ISSUE #11136: Type constraint ignored by `typeintersect` and function ambiguity check
(I was going to wait for the original reporter to report it here but since I don't want to spam the mailing list with update of my minimum test case, I decided to report it here myself)

See the mailing list thread [here](https://groups.google.com/forum/#!topic/julia-users/x-2XlNWwh2I)

Minimum working example
```julia
type A
end

type B
end

f{T}(::T, ::T) = nothing
f{T<:B}(::A, ::T) = nothing

g{T<:B}(::A, ::T) = nothing
g{T}(::T, ::T) = nothing

t1 = f.env.defs.sig
t2 = f.env.defs.next.sig

println("Signatures: $t1, $t2")
println("Intersect: $(typeintersect(t1, t2))")
println("Intersect: $(typeintersect(t2, t1))")
```

Output after fixing the ambigious error output formatting.
```julia
Warning: New definition 
    f(A, T<:B) at /home/yuyichao/tmp/julia/type_intersect.jl:10
is ambiguous with: 
    f(T, T) at /home/yuyichao/tmp/julia/type_intersect.jl:9.
To fix, define 
    f(A, A)
before the new definition.
Signatures: Tuple{T,T}, Tuple{A,T<:B}
Intersect: Union()
Intersect: Tuple{A,A}
```

### PR DESCRIPTION
**Pull request by timholy**
Fixes #11136. Don't merge until @JeffBezanson gets enough free time to look this over.

### CODE REVIEW

**Comment by timholy** [comment]
The second commit fixes #8652

**Comment by timholy** [comment]
...whoops, no it doesn't (or rather, it breaks other stuff). It made it through `test-core`, so I thought I was good.

I'll discuss more in #8652.

**Comment by timholy** [comment]
OK, this one should work (it passes locally). Interestingly, it also fixes #8045.

**Comment by timholy** [comment]
Hmm, the PR (not the push) has now failed twice on the `repl` test with an `unknown function` segfault, only on 32-bit. But the push and AppVeyor give this a pass on 32-bit, so I'm guessing it's OK? I'm trying once more.

**Comment by mbauman** [comment]
It is possible that there's a difference — the PR build merges the branch into master.  You could also try rebasing to see if the push then fails, too.

**Comment by timholy** [comment]
I just did an up-to-the-minute rebase, and it passed locally (but this was 64-bit, which also passed on Travis).

**Comment by timholy** [comment]
The CI problems seem to have been fixed. Nice!

**Comment by timholy** [comment]
Of my various open PRs, now that Jeff seems back (already!) I'm going to bump this particular one. It's short, I think it's one of the last barriers to merging static compilation, and Jeff seems likely to be the only suitable reviewer.

**Comment by timholy** [comment]
Hah, but I just discovered that a small addition also fixes #11367.

**Comment by Keno** [comment]
Thanks @timholy, amazing work, as always!

File: src/jltypes.c [hunk 1]
```diff
@@ -739,6 +739,36 @@ static jl_value_t *intersect_typevar(jl_tvar_t *a, jl_value_t *b,
                 break;
             }
         }
+        if (jl_is_typevar(b)) {
+            for(i=0; i < penv->n; i+=2) {
+                if (penv->data[i] == b && !jl_is_typevar(penv->data[i+1])) {
+                    if (jl_types_equal((jl_value_t*)a, penv->data[i+1])) {
```
Comment (JeffBezanson) [inline src/jltypes.c]: This seems very odd to me, since `a` is a typevar. I would think `jl_types_equal` would always return false in this case.

File: test/core.jl [hunk 2]
```diff
@@ -146,7 +152,20 @@ end
 
 # issue #2997
 let T = TypeVar(:T,Union(Float64,Array{Float64,1}),true)
-    @test typeintersect(T,Real) === Float64
+    testintersect(T,Real,Float64)
+end
+
+# issue #8652
+args_morespecific(a, b) = ccall(:jl_args_morespecific, Cint, (Any,Any), a, b)
```
Comment (JeffBezanson) [inline test/core.jl]: This should have a `!= 0` in it to make it a predicate.

**Comment by JeffBezanson** [comment]
Putting us all to shame --- just try to find a neuroscientist who knows as much about type systems! :)

File: src/jltypes.c (hunk 1 above)
Comment (timholy) [inline src/jltypes.c]: You're right, it probably can be deleted. I'll check it out.

**Comment by timholy** [comment]
I'm just trying to keep up with @simonster in doing our clan proud.

Besides, #11242 was type-system boot camp, in every respect except shaving my head (which is good, since there is so little to shave).

**Comment by timholy** [comment]
Right as usual, Jeff. And thanks for the speedy review!

**Comment by carnaval** [comment]
:clap:
