### PR TITLE
[p7zip_jll] Set `LIBPATH` and `LIBPATH_list` at init-time

### LINKED ISSUE #39154: Bundled 7z broken on alpine
```
Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/julia-1.6.0-beta1/libexec/7z)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /root/julia-1.6.0-beta1/libexec/7z)
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZdlPv: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _Znam: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_end_catch: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_allocate_exception: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_pure_virtual: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZdaPv: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __gxx_personality_v0: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_begin_catch: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_rethrow: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_throw: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _Znwm: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _Unwind_Resume: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZSt9terminatev: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_call_unexpected: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: __cxa_free_exception: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTIPKc: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTVN10__cxxabiv116__enum_type_infoE: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTIPKw: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTIi: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTVN10__cxxabiv117__class_type_infoE: symbol not found
Error relocating /root/julia-1.6.0-beta1/libexec/7z: _ZTVN10__cxxabiv121__vmi_class_type_infoE: symbol not found
```
see https://github.com/docker-library/julia/pull/50, https://github.com/docker-library/julia/pull/51

cc @tianon

### PR DESCRIPTION
**Pull request by giordano**
Fix #39154, take 2 (or 3?).  Ref: https://github.com/docker-library/julia/pull/51#issuecomment-776297077

Should be backported to `release-1.6`

### CODE REVIEW

File: stdlib/p7zip_jll/src/p7zip_jll.jl [hunk 1]
```diff
@@ -85,6 +85,8 @@ function __init__()
     init_p7zip_path()
     PATH[] = dirname(p7zip_path)
     push!(PATH_list, PATH[])
+    append!(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)])
+    LIBPATH[] = join(LIBPATH_list, pathsep)
```
Comment (giordano) [inline stdlib/p7zip_jll/src/p7zip_jll.jl:89]: As far as I could see, most JLLs do something like
https://github.com/JuliaLang/julia/blob/5d7e13f0dec118f86df2cf3d8999549cd47c32c2/stdlib/LibGit2_jll/src/LibGit2_jll.jl#L33-L34
because they're libraries, and only need to add to the libpath the directory they're in.  However, 7zip is in a different directory, the best I could do was to try both `joinpath(Sys.BINDIR, Base.LIBDIR, "julia")` and `joinpath(Sys.BINDIR, Base.LIBDIR)`, is there a better way to find the directory where libstdc++ is?

**Review by staticfloat — APPROVED** [review]

**Comment by fredrikekre** [comment]
tester_linux64:
```
ERROR: LoadError: On worker 23:
UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty
   @ ./Base.jl:33
 [2] #447
   @ /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Distributed/test/distributed_exec.jl:1607
 [3] #106
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:278
 [4] run_work_thunk
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:63
 [5] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:278 [inlined]
 [6] #105
   @ ./task.jl:406
Stacktrace:
 [1] (::Base.var"#876#878")(x::Task)
   @ Base ./asyncmap.jl:177
 [2] foreach(f::Base.var"#876#878", itr::Vector{Any})
   @ Base ./abstractarray.jl:2146
 [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::Vector{Int64})
   @ Base ./asyncmap.jl:177
 [4] wrap_n_exec_twice
   @ ./asyncmap.jl:153 [inlined]
 [5] async_usemap(f::var"#446#448", c::Vector{Int64}; ntasks::Int64, batch_size::Nothing)
   @ Base ./asyncmap.jl:103
 [6] #asyncmap#860
   @ ./asyncmap.jl:81 [inlined]
 [7] asyncmap
   @ ./asyncmap.jl:81 [inlined]
 [8] reuseport_tests()
   @ Main /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Distributed/test/distributed_exec.jl:1601
 [9] top-level scope
   @ /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Distributed/test/distributed_exec.jl:1637
in expression starting at /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Distributed/test/distributed_exec.jl:1636
```
Is there an open issue about this? Logs: https://build.julialang.org/#/builders/71/builds/566/steps/5/logs/stdio
