### PR TITLE
Fix fielddesc_type related asserts

### LINKED ISSUE #38479: Possibly inaccurate assert() in gc.c
We have observed a possibly broken assert() condition in `src/gc.c` ([link](https://github.com/JuliaLang/julia/blob/c9a149b46196629b6547b906dab444c8a06dc262/src/gc.c#L2665)).

It says:

```c
assert(layout->nfields > 0 && layout->fielddesc_type != 3 && "opaque types should have been handled specially");
```

However, immediately following is a series of tests, with the last branch specifically handling the case of `layout->fielddesc_type == 3`, and that is also where it should normally happen (this is the layout type where GC marking is determined by a custom mark function).

I suspect that the assert() should actually be something like:

```
assert((layout->nfields > 0 || layout->fielddesc_type == 3) && "opaque types should have been handled specially"); 
```

We noticed it, because we hit errors when running with Julia assertions enabled in [GAP.jl](https://github.com/oscar-system/GAP.jl).

This should normally have been caught by the tests in `test/gcext`, but it appears I failed to hook up that particular test to the Julia test harness when submitting the patch for the GC extensions. So the test isn't actually run normally; and as a result, the code in `test/gcext` itself also isn't up to date for 1.6. I plan on submitting a PR that fixes that also.

### LINKED ISSUE #38504: gcext segfaults
Running the `tests/gcext` tests segfaults on the latest `master` (72e67d707ba1f399f082e149080a5eaa24bc63a0):

```
$ ./gcext 
MethodError: no method matching find_package(Internal error: encountered unexpected error in runtime:
ReadOnlyMemoryError()
task_scanner at ./gcext (unknown line)
gc_mark_loop at /home/sabae/src/julia-master/src/gc.c:2585
_jl_gc_collect at /home/sabae/src/julia-master/src/gc.c:2973
jl_gc_collect at /home/sabae/src/julia-master/src/gc.c:3179
maybe_collect at /home/sabae/src/julia-master/src/gc.c:828 [inlined]
jl_gc_pool_alloc at /home/sabae/src/julia-master/src/gc.c:1143
jl_gc_alloc_ at /home/sabae/src/julia-master/src/julia_internal.h:282 [inlined]
jl_gc_alloc at /home/sabae/src/julia-master/src/gc.c:3221
_new_array_ at /home/sabae/src/julia-master/src/array.c:122 [inlined]
_new_array at /home/sabae/src/julia-master/src/array.c:190 [inlined]
jl_alloc_array_1d at /home/sabae/src/julia-master/src/array.c:461
Array at ./boot.jl:448 [inlined]
Array at ./boot.jl:467 [inlined]
getindex at ./array.jl:391 [inlined]
simple_dce! at ./compiler/ssair/ir.jl:1358
getfield_elim_pass! at ./compiler/ssair/passes.jl:724
run_passes at ./compiler/ssair/driver.jl:132
optimize at ./compiler/optimize.jl:186
_typeinf at ./compiler/typeinfer.jl:239
typeinf at ./compiler/typeinfer.jl:211
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:307
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:154
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:307
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:154
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_ext at ./compiler/typeinfer.jl:835
typeinf_ext_toplevel at ./compiler/typeinfer.jl:868
typeinf_ext_toplevel at ./compiler/typeinfer.jl:864
jfptr_typeinf_ext_toplevel_12333 at /home/sabae/src/julia-master/usr/lib/julia/sys.so (unknown line)
_jl_invoke at /home/sabae/src/julia-master/src/gf.c:2191 [inlined]
jl_apply_generic at /home/sabae/src/julia-master/src/gf.c:2373
jl_apply at /home/sabae/src/julia-master/src/julia.h:1693 [inlined]
jl_type_infer at /home/sabae/src/julia-master/src/gf.c:300
jl_generate_fptr at /home/sabae/src/julia-master/src/jitlayers.cpp:316
jl_compile_method_internal at /home/sabae/src/julia-master/src/gf.c:1924
jl_compile_method_internal at /home/sabae/src/julia-master/src/gf.c:1878 [inlined]
_jl_invoke at /home/sabae/src/julia-master/src/gf.c:2183 [inlined]
jl_apply_generic at /home/sabae/src/julia-master/src/gf.c:2373
showerror at ./errorshow.jl:265
unknown function (ip: 0x7f3fa7f6af48)
_jl_invoke at /home/sabae/src/julia-master/src/gf.c:2191 [inlined]
jl_apply_generic at /home/sabae/src/julia-master/src/gf.c:2373
jl_apply at /home/sabae/src/julia-master/src/julia.h:1693 [inlined]
jl_call2 at /home/sabae/src/julia-master/src/jlapi.c:247
checked_eval_string at ./gcext (unknown line)
main at ./gcext (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at ./gcext (unknown line)
::Module, Internal error: encountered unexpected error in runtime:
OutOfMemoryError()
jl_gc_big_alloc at /home/sabae/src/julia-master/src/gc.c:894
jl_gc_alloc_ at /home/sabae/src/julia-master/src/julia_internal.h:287 [inlined]
jl_gc_alloc at /home/sabae/src/julia-master/src/gc.c:3221
jl_alloc_svec_uninit at /home/sabae/src/julia-master/src/simplevector.c:60
jl_specializations_get_linfo at /home/sabae/src/julia-master/src/gf.c:160
specialize_method at ./compiler/utilities.jl:144 [inlined]
specialize_method at ./compiler/utilities.jl:134 [inlined]
typeinf_edge at ./compiler/typeinfer.jl:708
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_edge at ./compiler/typeinfer.jl:745
abstract_call_method at ./compiler/abstractinterpretation.jl:466
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:130
abstract_call_known at ./compiler/abstractinterpretation.jl:1003
abstract_call at ./compiler/abstractinterpretation.jl:1026
abstract_call at ./compiler/abstractinterpretation.jl:1010
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1132
typeinf_local at ./compiler/abstractinterpretation.jl:1386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1442
_typeinf at ./compiler/typeinfer.jl:216
typeinf at ./compiler/typeinfer.jl:211
typeinf_ext at ./compiler/typeinfer.jl:835
typeinf_ext_toplevel at ./compiler/typeinfer.jl:868
typeinf_ext_toplevel at ./compiler/typeinfer.jl:864
jfptr_typeinf_ext_toplevel_12333 at /home/sabae/src/julia-master/usr/lib/julia/sys.so (unknown line)
_jl_invoke at /home/sabae/src/julia-master/src/gf.c:2191 [inlined]
jl_apply_generic at /home/sabae/src/julia-master/src/gf.c:2373
jl_apply at /home/sabae/src/julia-master/src/julia.h:1693 [inlined]
jl_type_infer at /home/sabae/src/julia-master/src/gf.c:300
jl_generate_fptr at /home/sabae/src/julia-master/src/jitlayers.cpp:316
jl_compile_method_internal at /home/sabae/src/julia-master/src/gf.c:1924
jl_compile_method_internal at /home/sabae/src/julia-master/src/gf.c:1878 [inlined]
_jl_invoke at /home/sabae/src/julia-master/src/gf.c:2183 [inlined]
jl_apply_generic at /home/sabae/src/julia-master/src/gf.c:2373
showerror at ./errorshow.jl:265
unknown function (ip: 0x7f3fa7f6af48)
_jl_invoke at /home/sabae/src/julia-master/src/gf.c:2191 [inlined]
jl_apply_generic at /home/sabae/src/julia-master/src/gf.c:2373
jl_apply at /home/sabae/src/julia-master/src/julia.h:1693 [inlined]
jl_call2 at /home/sabae/src/julia-master/src/jlapi.c:247
checked_eval_string at ./gcext (unknown line)
main at ./gcext (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at ./gcext (unknown line)
::String)
Closest candidates are:
  find_package(::Any) at loading.jl:239
```

Pinging @fingolfin as I believe you are the last person to touch this file.  :)

### PR DESCRIPTION
**Pull request by rbehrends**
Fixes #38479, fixes #38504.

### CODE REVIEW

**Comment by fingolfin** [comment]
It also fixes #38504 , doesn't it?

**Comment by rbehrends** [comment]
> It also fixes #38504 , doesn't it?

It does, but I saw that issue only after I had already opened the PR.

File: src/gc.c [hunk 1]
```diff
@@ -2662,7 +2662,7 @@ mark: {
             if (npointers == 0)
                 goto pop;
             uintptr_t nptr = npointers << 2 | (bits & GC_OLD);
-            assert(layout->nfields > 0 && layout->fielddesc_type != 3 && "opaque types should have been handled specially");
+            assert((layout->nfields > 0 || layout->fielddesc_type == 3) && "opaque types should have been handled specially");
```
Comment (fingolfin) [inline src/gc.c:2665]: Just to double check my understanding of this assertion: it is triggered if `npointer > 0` yet `nfields == 0` (except for foreign types, where this is allowed). Because in this situation, the type is considered "opaque", which fits with the definition of `jl_is_layout_opaque`:
```C
static inline int jl_is_layout_opaque(const jl_datatype_layout_t *l) JL_NOTSAFEPOINT
{
    return l->nfields == 0 && l->npointers > 0;
}
```
This returns true even for foreign types -- which however makes perfect sense, as foreign types which contain npointers certainly are "opaque".


So from this perspective, this change looks correct to me.

**Comment by fingolfin** [comment]
@vtjnash does this seem reasonable to you?
