### PR TITLE
Fix Win32 ABI

### LINKED ISSUE #13242: C format string warnings on Windows
I am building Julia 0.4-rc2 on 64-bit Windows, using Cygwin and gcc 4.9. I see (potentially severe?) warnings about mismatching C format strings.

```
$ git status
On branch release-0.4
Your branch is up-to-date with 'origin/release-0.4'.
nothing to commit, working directory clean
```

```
$ uname -a
CYGWIN_NT-6.1 pi0005009 2.2.1(0.289/5/3) 2015-08-20 11:42 x86_64 Cygwin
$ cc --version
cc (GCC) 4.9.3
```

```
ccalltest.c: In function ‘cptest’:
ccalltest.c:85:5: warning: unknown conversion type character ‘l’ in format [-Wformat=]
     if (verbose) fprintf(stderr,"%lld + %lld i\n", (long long)a->real, (long long)a->imag);
     ^
ccalltest.c:85:5: warning: unknown conversion type character ‘l’ in format [-Wformat=]
ccalltest.c:85:5: warning: too many arguments for format [-Wformat-extra-args]
ccalltest.c: In function ‘test_big’:
ccalltest.c:349:5: warning: unknown conversion type character ‘l’ in format [-Wformat=]
     if (verbose) fprintf(stderr,"%lld %lld %c\n", (long long)a.x, (long long)a.y, a.z);
     ^
ccalltest.c:349:5: warning: unknown conversion type character ‘l’ in format [-Wformat=]
ccalltest.c:349:5: warning: format ‘%c’ expects argument of type ‘int’, but argument 3 has type ‘int64_t’ [-Wformat=]
ccalltest.c:349:5: warning: too many arguments for format [-Wformat-extra-args]
```

### PR DESCRIPTION
**Pull request by yuyichao**
- Extend ccall test (Ref https://github.com/JuliaLang/julia/pull/14215 from @maleadt)
- Enable a few more tests on OSX

Fixes #13242

### CODE REVIEW

**Comment by yuyichao** [comment]
Note that I can't find a complete document on Win32 ABI so the fix is only based on the ldc source code and what clang emit.

The new tests also pass on AArch64.

**Comment by yuyichao** [comment]
Tentatively add backport 0.4 label for the win32 fix, if it doesn't cause much conflicts.

**Comment by yuyichao** [comment]
[Win64 failure](https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.13096/job/n9e44gys0h0v8j6a#L1249) looks [intermittent](https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.13095/job/cihr7nwnfjg7bd87) and was seen on [Travis lin32 recently](https://travis-ci.org/JuliaLang/julia/jobs/106141253#L1847)

File: src/abi_win32.cpp [hunk 1]
```diff
@@ -42,34 +42,34 @@ AbiState default_abi_state = 0;
 
 bool use_sret(AbiState *state, jl_value_t *ty)
 {
-    if (!jl_is_datatype(ty) || jl_is_abstracttype(ty) || jl_is_cpointer_type(ty) || jl_is_array_type(ty))
-        return false;
-    size_t size = jl_datatype_size(ty);
-    if (size <= 8)
+    // Assume jl_is_datatype(ty) && !jl_is_abstracttype(ty)
```
Comment (vtjnash) [inline src/abi_win32.cpp]: is this assumption being checked somewhere?

File: src/abi_win32.cpp [hunk 2]
```diff
@@ -42,34 +42,34 @@ AbiState default_abi_state = 0;
...
+    // This covers the special case of Complex64
+    size_t size = dt->size;
+    if (size == 1 || size == 2 || size == 4 || size == 8)
         return false;
     return true;
 }
 
 void needPassByRef(AbiState *state, jl_value_t *ty, bool *byRef, bool *inReg)
 {
-    if (!jl_is_datatype(ty) || jl_is_abstracttype(ty) || jl_is_cpointer_type(ty) || jl_is_array_type(ty))
```
Comment (vtjnash) [inline src/abi_win32.cpp]: Base treats `Array{T,N}` special (it has no fields, but is always handled as a Ref pointer)

File: src/abi_win32.cpp [hunk 3]
```diff
@@ -42,34 +42,34 @@ AbiState default_abi_state = 0;
...
-        return;
-    size_t size = jl_datatype_size(ty);
-    if (size <= 8)
-        return;
-    *byRef = true;
+    // Assume jl_is_datatype(ty) && !jl_is_abstracttype(ty)
+    jl_datatype_t *dt = (jl_datatype_t*)ty;
+    // Use pass by reference for all structs
+    *byRef = dt->nfields > 0;
```
Comment (vtjnash) [inline src/abi_win32.cpp]: also need byRef for size > 8

File: src/abi_win32.cpp (hunk 1 above)
Comment (yuyichao) [inline src/abi_win32.cpp]: Yes, the caller always check that.

File: src/abi_win32.cpp (hunk 2 above)
Comment (yuyichao) [inline src/abi_win32.cpp]: so `dt->nfields > 0 == false` and the new version is the same with the version before?

File: src/abi_win32.cpp (hunk 3 above)
Comment (yuyichao) [inline src/abi_win32.cpp]: There's no such type (non-struct type that is larger than 8 bytes) in C that can be passed as argument so I'm not sure what's the best thing to do here.

Comment (vtjnash) [inline src/abi_win32.cpp]: There's `long double`, but it doesn't really count since it isn't in Julia. In Julia such a type is `Int128`. It doesn't map directly to C, so I've been mapping it to `struct {uint64_t lo, uint64_t hi}` as a sane default.

File: src/abi_win32.cpp (hunk 1 above)
Comment (vtjnash) [inline src/abi_win32.cpp]: ah, so we do.

File: src/abi_win32.cpp (hunk 3 above)
Comment (yuyichao) [inline src/abi_win32.cpp]: I can treat non-standard size bitstype as struct (I believe that's how I treat it in the aarch64 abi). How should `long double` be passed? I believe the ARM and AArch64 abi check for that by `size == 16` and `<: FloatingPoint`. We can do that for other platform too if it require special ABI.

The `Int128` test should actually be fixed (or comment about) for aarch64 since it is actually a c type. Probably a different PR.

Comment (vtjnash) [inline src/abi_win32.cpp]: > size == 16 and <: FloatingPoint

we may want to revisit that as well. in particular, that might accidentally include a non-IEEE type (such as an mpfr-like value). the other cases are handled explicitly (with comparisons to Float64, etc).

> The Int128 test should actually be fixed (or comment about) for aarch64 since it is actually a c type. Probably a different PR.

sounds good. my original ccall test code was making lots of shortcuts based upon how i knew the x86-family ABIs would behave
