### PR TITLE
staticdata: Memoize `type_in_worklist` query

### LINKED ISSUE #53331: Deeply recursive types highlight performance issue in sysimg creation, type_in_worklist is inefficient.
I have been experiencing long delays between finishing a precompilation workload (using PrecompileTools.jl) and exiting precompilation. In the full-scale example, the numbers were
- First call to the function without PrecompileTools: ~40seconds
- First call to the function during precompilation: ~20seconds
- Time between the function returning and precompilation finishing (start of test suite): ~1200seconds

I have been able to reproduce the issue in a small package: https://github.com/simsurace/WeirdPrecompilationProblem.jl
The numbers are much smaller for the MRE, but there is still a large delay of approx. 2minutes between the function returning and precompilation finishing on all of my machines (Linux and MacOS).

This is a follow-up from a discussion with @vchuravy on Slack.

### PR DESCRIPTION
**Pull request by topolarity**
When pre-compiling `stdlib/` this cache has a 91% hit rate, so this seems fairly profitable. It also dramatically improves some pathological cases, a few of which have been hit in the wild (arguably due to inference bugs)

Without this PR, this package takes exponentially long to pre-compile:
```julia
function BigType(N)
    (N == 0) && return Nothing
    T = BigType(N-1)
    return Pair{T,T}
end
foo(::Type{T}) where T = T
precompile(foo, (Type{BigType(40)},))
```

For an in-the-wild test case hit by a customer, this reduces pre-compilation time from over an hour to just ~two and a half minutes.

Resolves #53331.

### CODE REVIEW

File: src/staticdata.c [hunk 1]
```diff
@@ -3367,11 +3376,14 @@ JL_DLLEXPORT void jl_create_system_image(void **_native_data, jl_array_t *workli
     int64_t datastartpos = 0;
     JL_GC_PUSH4(&mod_array, &extext_methods, &new_ext_cis, &edges);
 
+    jl_query_cache query_cache = { 0 };
+    htable_new(&query_cache.type_in_worklist, 0);
```
Comment (vtjnash) [inline src/staticdata.c:3380]:
```suggestion
    jl_query_cache query_cache;
    htable_new(&query_cache.type_in_worklist, 0);
```

please add code to `htable_free` this also

Comment (topolarity) [reply src/staticdata.c:3380]: Ack, nice catch - I deleted this on accident with the logging code for the hit rate check

**Review by JeffBezanson — APPROVED** [review]
