### PR TITLE
Call constructor instead of `oftype(..., nothing)` to construct a null Nullable.

### LINKED ISSUE #20078: BoundsError in 2d comprehension
From MAT.jl's test suite

```jl
julia> Any[v for _ in 1:1, v in (1.0, 2.01, "string", Any["string1" "string2"])]
ERROR: BoundsError: attempt to access 1×4 Array{Any,2} at index [5]
Stacktrace:
 [1] copy!(::Array{Any,2}, ::Base.Generator{Base.Iterators.Prod2{UnitRange{Int64},Tuple{Float64,Float64,String,Array{Any,2}}},##1#2}) at ./abstractarray.jl:499
 [2] _collect(::Type{Any}, ::Base.Generator{Base.Iterators.Prod2{UnitRange{Int64},Tuple{Float64,Float64,String,Array{Any,2}}},##1#2}, ::Base.HasShape) at ./array.jl:313
 [3] collect(::Type{Any}, ::Base.Generator{Base.Iterators.Prod2{UnitRange{Int64},Tuple{Float64,Float64,String,Array{Any,2}}},##1#2}) at ./array.jl:310
```

Bisection blames https://github.com/JuliaLang/julia/pull/18457

cc: @JeffBezanson

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #20078

### CODE REVIEW

File: base/iterators.jl [hunk 1]
```diff
@@ -539,7 +539,7 @@ end
     end
 
     if done(p.a, s1)
-        return (v1,v2), (start(p.a), s2, oftype(nv2,nothing), done(p.b,s2))
+        return (v1,v2), (start(p.a), s2, typeof(nv2)(), done(p.b,s2))
```
Comment (nalimilan) [inline base/iterators.jl]: Or maybe clearer as `Nullable{eltype(nv2)}()`?

Comment (yuyichao) [inline base/iterators.jl]: Sure...

**Review by JeffBezanson — APPROVED** [review]
