### PR TITLE
Fix similar(::Array, ::UInt)

### LINKED ISSUE #16247: Indexing with `UInt64`
I got an issue when indexing a matrix with a range of `UInt64`.

 ```
Version 0.5.0-dev+3438 (2016-04-07 15:46 UTC)
Commit a92c7ff (29 days old master)
x86_64-linux-gnu

julia> A = zeros(3,3)
julia> A[:,0x1:0x2] # ok UInt8
julia> A[:,1:2] # ok Int64
julia> A[:,UnitRange{UInt}(0x1:0x2)] # not ok UInt64
ERROR: MethodError: no method matching Array{T,N}(::Tuple{Int64,UInt64}, ::Int64, ::Int64)
Closest candidates are:
  (::Type{TypeError})(::Any, ::Any, ::Any, ::Any)
  (::Type{Expr})(::ANY...)
  (::Type{Core.Inference.Generator{I,F}})(::Any, ::Any, ::Any...)
  ...
 [inlined code] from ./range.jl:341
 in _unsafe_getindex(::Base.LinearFast, ::Array{Float64,2}, ::Colon, ::UnitRange{UInt64}) at ./multidimensional.jl:224
 [inlined code] from ./multidimensional.jl:217
 in getindex(::Array{Float64,2}, ::Colon, ::UnitRange{UInt64}) at ./abstractarray.jl:476
 in eval(::Module, ::Any) at ./boot.jl:237
```

I cannot reproduce the issue with a vector
```
julia> x = zeros(3)
julia> x[UnitRange{UInt}(0x1:0x2)] # ok
```

I am using Julia v0.5 nightly with Ubuntu 14.04 but my version is still 29 days old (it seems that there is no newer version for Ubuntu 14.04 in the ppa) so if this has been fixed recently, I apologize. Can someone reproduce it on the latest development version ?

### PR DESCRIPTION
**Pull request by mbauman**
The integer was getting interpreted as a type -- simply ensure that the type argument is indeed a type.  Fixes #16247

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Arguably, we should audit most places where code in Base has untyped arguments. Maybe we should write `::Any` on the ones where we've decided that we really mean it. Leaving type annotations off when hacking is great but it's kind of error prone in code that's as important as Base Julia's code base.

File: test/arrayops.jl [hunk 1]
```diff
@@ -1589,3 +1589,10 @@ end
 @test f15894(ones(Int, 100)) == 100
 
 end
+
+# issue #16247
+let A = zeros(3,3)
+    @test size(A[:,0x1:0x2]) == (3, 2)
+    @test size(A[:,UInt(1):UInt(2)]) == (3,2)
+    @test size(similar(A, UInt(3), 0x3)) == size(similar(A, (UInt(3), 0x3))) == (3,3)
```
Comment (timholy) [inline test/arrayops.jl]: Aren't the first two identical?

**Comment by vtjnash** [comment]
This was helpful, since it's also the reason the `similar` methods (no pun intended) were being detected as ambiguous (https://github.com/JuliaLang/julia/pull/16255/commits/3f64401a6a9f00582bed32922dd450d72b5f4932)
