### PR TITLE
correctly parse integer types in readdlm. fixes #9289

### LINKED ISSUE #9289: readdlm improper handling of Int64
I think [this has been mentioned before](https://groups.google.com/forum/#!searchin/julia-users/readdlm/julia-users/43NSoG59XaU/v7rjGAmqz7YJ), but I don't think an issue was submitted (or at least, I couldn't find it).

Namely, `readdlm()` improperly handles Int64.
For example, given a text file consisting only of the line `-9223355253176920979`, readdlm gives the following incorrect result:
```
test=readdlm("test.txt",Int64)
1x1 Array{Int64,2}:
 -922335525317692160
```

### PR DESCRIPTION
**Pull request by tanmaykm**
Continued from #9316 
- Separate `colval` method for `Integer`s.
- Used `tryparse_internal` methods instead of `float64_isvalid`.
- Modified `tryparse_internal` to be able to parse a section of a string (avoids unnecessary `SubString` creation).
- If return array is of `Any` type, try parsing as the most common types (`Int`, `Bool` and `Float64`) before falling back to `SubString`. The previous behavior was to try `Float64` only.

There is no significant impact on performance with this change.

### CODE REVIEW

File: base/gmp.jl [hunk 1]
```diff
@@ -87,7 +86,7 @@ function tryparse_internal(::Type{BigInt}, s::AbstractString, base::Int, raise::
     z = BigInt()
     err = ccall((:__gmpz_set_str, :libgmp),
                Int32, (Ptr{BigInt}, Ptr{UInt8}, Int32),
-               &z, SubString(s,i), base)
+               &z, bytestring(SubString(s,i,endpos)), base)
```
Comment (JeffBezanson) [inline base/gmp.jl]: I believe ccall converts to ByteString automatically.

File: base/string.jl [hunk 2]
```diff
@@ -1527,21 +1527,30 @@ function parseint_preamble(signed::Bool, s::AbstractString, base::Int)
     return sgn, base, j
 end
 
+function tryparse_internal{S<:ByteString}(::Type{Bool}, sbuff::S, startpos::Int, endpos::Int, raise::Bool)
+    len = endpos-startpos+1
+    p = pointer(sbuff)+startpos-1
+    (len == 4) && (0 == ccall(:memcmp, Int32, (Ptr{UInt8}, Ptr{UInt8}, UInt), p, pointer("true"), 4)) && (return Nullable(true))
```
Comment (JeffBezanson) [inline base/string.jl]: You never need to call `pointer` on ccall arguments; ccall already handles that.

Comment (tanmaykm) [inline base/string.jl]: Yes, thanks. Updated now.
