### PR TITLE
Fix `Vararg` methods widening with unused type variable.

### LINKED ISSUE #48950: Unexpected `TypeError: in Vararg, in type, expected Type, got Vararg{Union{Float64, AbstractArray}}` in Julia 1.9
One of the tests of https://gitlab.kuleuven.be/ppw-okpiv/research/GradientDiffusion.jl/ fails in Julia 1.9-beta/rc1 with `ERROR: TypeError: in Vararg, in type, expected Type, got Vararg{Union{Float64, AbstractArray}}`. In Julia 1.8 it works without issues.

This is a minimal working/failing example:
```julia
module j
    struct k{
        b,
        c}
        d
        function k(e::Vararg{Union{b, AbstractArray}}) where b
            c = Union
            new{b, c}(e)
        end
    end
    l(a) = getfield(a, :d)
    function a(b, c)
        c(l(b[])...)
    end
    function o(a)
        function(b, ::Vararg{Union{c, AbstractArray}}) where {c, d}
        end
    end
    function fit(z, f, d)
        b = [ k([0.], 0.) ]
        a(b, (i...) -> d(z, i...))
    end
end
c = d = []
j.fit(j, d, j.o(c))
```
Output in Julia 1.8: 
```
```

Output in Julia 1.9:
```
ERROR: TypeError: in Vararg, in type, expected Type, got Vararg{Union{Float64, AbstractArray}}
Stacktrace:
 [1] (::Main.j.var"#3#4"{Module, Main.j.var"#1#2"})(::Vector{Float64}, ::Vararg{Any})
   @ Main.j .\REPL[7]:21
 [2] a
   @ .\REPL[7]:13 [inlined]
 [3] fit(z::Module, f::Vector{Any}, d::Function)
   @ Main.j .\REPL[7]:21
 [4] top-level scope
   @ REPL[9]:1
```

The example is reproducible in Windows and Linux.
i.e. of versioninfo():
```
Julia Version 1.9.0-rc1
Commit 3b2e0d8fbc (2023-03-07 07:51 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
```

### PR DESCRIPTION
**Pull request by N5N3**
close #48950.

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -7973,3 +7973,6 @@ let spec = only(methods(g47476)).specializations
     @test any(mi -> mi !== nothing && Base.isvatuple(mi.specTypes), spec)
     @test all(mi -> mi === nothing || !Base.has_free_typevars(mi.specTypes), spec)
 end
+
+f48950(::Union{c,Nothing}...) where {c,d} = 1
+@test f48950(1, 1) == 1
```
Comment (vtjnash) [inline test/core.jl:7978]:
```suggestion
f48950(::Union{Int,d}, ::Union{c,Nothing}...) where {c,d} = 1
@test f48950(1, 1, 1) == 1
```
this ensures it is a legal definition (no warning), but still hits the same code path
