### PR TITLE
Make Vararg not a DataType

### LINKED ISSUE #30995: Vararg behaves strangely in Core.Typeof
```julia
julia> y = Array.body.body
Array{T,N}

julia> Type{y}
Type{Array{T,N}}

julia> x = Vararg.body.body
Vararg{T,N}

julia> Type{x}
ERROR: TypeError: in Type, in parameter, expected Type, got Vararg{T,N}
Stacktrace:
 [1] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by Keno**
Currently `Vararg` is a DataType, but is special cased in a
bunch of places to give it special behavior (e.g. in subtyping
and of course in tuple construction). However, unlike all other
DataTypes, it cannot appear as a type parameter, which caused trouble in
PR #38071. Having it be a DataType is a bit of a pun of convenience
in the first place - it's a lot more similar to a tvar (which can
be considered an implementation detail of UnionAll in the same way
Vararg is an implementation detail of Tuple), which has its own
non-type object. This PR does the same to Vararg, and moves it
from being an abstract DataType with special cased behavior to
its own custom type (called `Core.VarargMarker`). The user facing
behavior should be mostly unchanged, since `boot.jl` now has:
```
const Vararg{T, N} = VarargMarker{T, N}
```
i.e. we have a handly UnionAll wrapper that looks just like it
used to. The biggest difference is probably that VarargMarker
does not have `.parameters`, so code that tries to reach into
that explicitly will need to be adjusted. We could provide
a compatibility `getproperty` method to adapt that, but I'd
prefer to see how many packages need updating first, before
going that route.

This is essentially complete, but a few cleanup items remain.

Closes #30995 #34690 #26625 #37316

### CODE REVIEW

**Comment by martinholters** [comment]
:+1: Completely agree, `Vararg` is sufficiently different from a data type that it should probably not be a `DataType`. The code changes needed to deal with the new definition in my eyes also tend to improve clarity, which is good sign. It also makes it more obvious where a `Vararg` is to be expected and that it usually deserves some extra thought how to deal with it.

Because it took me moment to wrap my head around it, some remarks that might help others grok what's happening:
With this PR `Core.VarargMarker{Int,2} isa Core.VarargMarker`, while for a normal unionall/data type, one would expect a `<:` instead of the `isa`. And indeed, previously `Vararg{Int,2} <: Vararg`. (This errors on this PR, but maybe should be restored?) But note that e.g. also `Union{Int,Float64} isa Union`, so it's not completely new and exotic. Furthermore `Vararg{T,N} == Core.VarargMarker{T,N}` does not imply `Vararg == Core.VarargMarker`. The former is a `UnionAll`, the latter a `DataType`.

File: src/dump.c [hunk 1]
```diff
@@ -567,6 +567,11 @@ static void jl_serialize_value_(jl_serializer_state *s, jl_value_t *v, int as_li
         jl_serialize_value(s, ((jl_tvar_t*)v)->lb);
         jl_serialize_value(s, ((jl_tvar_t*)v)->ub);
     }
+    else if (jl_is_vararg_marker(v)) {
+        write_uint8(s->s, TAG_VARARG);
+        jl_serialize_value(s, ((jl_vararg_marker_t*)v)->T);
+        jl_serialize_value(s, ((jl_vararg_marker_t*)v)->N);
+    }
```
Comment (JeffBezanson) [inline src/dump.c:574]: Did you encounter any particular reason this is needed? I would think the default case would work for these.

Comment (Keno) [reply src/dump.c:574]: No, I thought I did, but I think the default is fine. I'll try removing it and see if things work out.

File: src/subtype.c [hunk 2]
```diff
@@ -1313,6 +1318,15 @@ static int subtype(jl_value_t *x, jl_value_t *y, jl_stenv_t *e, int param)
             e->invdepth = saved;
             return issub;
         }
+        if (jl_is_vararg_marker(xd)) {
+            if (!jl_is_vararg_marker(yd))
+                return 0;
+            // N.B.: This case is only used for raw varargs that are not part
+            // of a tuple (those that are have special handling in subtype_tuple).
+            // Vararg isn't really a proper type, but it does sometimes show up
+            // as e.g. Type{Vararg}, so we'd like to handle that correctly.
```
Comment (JeffBezanson) [inline src/subtype.c:1327]: `Type{Vararg}` is not allowed. Ideally we would give an error here too, but if that's too breaking we can instead just change this comment to say it's provided for compatibility with code that uses `<:` to compare Vararg objects.

Comment (Keno) [reply src/subtype.c:1327]: This comment is old, it just moved from below. I can try giving an error and see what needs to be updated.

Comment (JeffBezanson) [reply src/subtype.c:1327]: Oh, as Martin noticed above it looks like passing Vararg to `<:` is already an error in this PR :) We can try to go with that, and change this to an assertion.

**Comment by JeffBezanson** [comment]
Hmm, at first I thought it would be more compatible to keep `Vararg::UnionAll` true, but especially if we're going to change the fields of `Vararg` maybe it doesn't really matter. Getting rid of that constraint allows us to have one object Vararg instead of both Vararg and VarargMarker, plus `Vararg{Int} isa Vararg` is more directly analogous to `Union{Int, Float64} isa Union`. So maybe that is the right way to go.

**Comment by Keno** [comment]
Ok, I can try that.

**Comment by Keno** [comment]
I've updated this along these lines, disallowing `Vararg` inside a `UnionAll`, which I think is the right way to go, but we still end up with `Vararg` and `VarargMarker`, which need to be two separate things, since otherwise, you can't refer to the type of a `Vararg` (and people use a raw Vararg without any parameters as in `Tuple{Vararg}` and want that to mean `Tuple{Vararg{Any}}`, so `Vararg` can't be that type).

**Comment by yurivish** [comment]
Would this change this close #34690?

```
julia> methods(Core.Vararg) # This does not
ERROR: TypeError: in Type, in parameter, expected Type, got Vararg
Stacktrace:
 [1] signature_type(::Any, ::Any) at ./reflection.jl:767
 [2] _methods at ./reflection.jl:830 [inlined]
 [3] methods(::Any, ::Any) at ./reflection.jl:875
 [4] methods(::Any) at ./reflection.jl:890
 [5] top-level scope at REPL[24]:1
```

**Comment by Keno** [comment]
```
julia> methods(Core.Vararg)
# 0 methods:

```
;)

**Comment by Keno** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

File: base/boot.jl [hunk 3]
```diff
@@ -242,14 +242,23 @@ ccall(:jl_toplevel_eval_in, Any, (Any, Any),
...
     _expr(:meta, :nospecialize, x)
 end
 
+TypeVar(n::Symbol) = _typevar(n, Union{}, Any)
+TypeVar(n::Symbol, @nospecialize(ub)) = _typevar(n, Union{}, ub)
+TypeVar(n::Symbol, @nospecialize(lb), @nospecialize(ub)) = _typevar(n, lb, ub)
+
+UnionAll(v::TypeVar, @nospecialize(t)) = ccall(:jl_type_unionall, Any, (Any, Any), v, t)
+
+const Vararg = ccall(:jl_toplevel_eval_in, Any, (Any, Any), Core, _expr(:new, VarargMarker))
```
Comment (JeffBezanson) [inline base/boot.jl:256]: In this case, maybe call it `TypeofVararg` to go with `TypeofBottom`? This could also use jl_new_struct instead of eval.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38136#issuecomment-715984362) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/48947f1692b4c6a8aef8538d1c457f146e6b1225/pkgeval/by_hash/778823f_vs_d474c98/report.md). cc @maleadt

**Comment by Keno** [comment]
Alright, fully disallowing Vararg in UnionAll turned out to be a little aggressive. Apparently people like to write `Tuple{Vararg{<:Real}}` even though the `<:` doesn't do anything here (we already used to normalize on tuple construction to move it inside the vararg, so it doesn't even implicate the diagonal rule). I've added back that normalization into the UnionAll constructor, though it'll complain if depwarns are enabled, so we can remove it whenever people stop using this pattern or in 2.0 at the latest (it's actually only a few packages, so it's not too bad, but enough that I want to add the compat).

**Comment by Keno** [comment]
Alright, @JeffBezanson this works now, but there's some decisions to make for subtyping. Essentially, we need some sentinel value to indicate that a typevar must remain unbound. Previously, we'd just set it to the inner typevar, but we a) don't have that anymore and b) I don't think it necessarily makes much sense. In the commit I just pushed I'm using the vararg itself as the typevar, but of course the assertion that I added that we're not putting a vararg into subtyping fires there, so basically we need to decide what to use as the sentinel value here.

**Comment by Keno** [comment]
(I've pushed something I think is reasonable, but this stuff is pretty messy, since it isn't really designed to reason about int ranges)

**Comment by Keno** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38136#issuecomment-716794279) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/0dd5d869065b20b39813bc517ddfe4480bb53b07/pkgeval/by_hash/c80e395_vs_c293757/report.md). cc @maleadt

**Comment by Keno** [comment]
Alright, looks like we're down to just the StaticArrays open-coding unwrapva issue, which I have a PR for at https://github.com/JuliaArrays/StaticArrays.jl/pull/843.

**Comment by Keno** [comment]
MbedTLS segfault is unrelated: https://github.com/JuliaLang/MbedTLS.jl/pull/227

File: base/compiler/inferencestate.jl [hunk 4]
```diff
@@ -192,6 +192,8 @@ function sptypes_from_meth_instance(linfo::MethodInstance)
                     ty = UnionAll(tv, Type{tv})
                 end
             end
+        elseif isa(v, Core.VarargMarker)
+            ty = Int
```
Comment (JeffBezanson) [inline base/compiler/inferencestate.jl:196]: Fixes #37316?

Comment (Keno) [reply base/compiler/inferencestate.jl:196]: Yes

File: src/subtype.c [hunk 5]
```diff
@@ -959,12 +959,18 @@ static int subtype_tuple_varargs(struct subtype_tuple_env *env, jl_stenv_t *e, i
...
+                return 0;
+            e->Rinvdepth++;
+            record_var_occurrence(ylv, e, 2);
+            e->Rinvdepth--;
+        }
+        // We need some sort of sentinel here for the lower bound.
+        // When we still had typevars in every Vararg, this was always
+        // a typevar, but now we just use the vararg marker itself as the
+        // sentinel.
+        return var_gt((jl_tvar_t*)yp1, env->vtx, e, 2);
```
Comment (JeffBezanson) [inline src/subtype.c]: Is this passing a VarargMarker to `var_gt`? I think only types should be passed to it. If the only goal is to set the lower bound, I think it's better to do that directly.

Comment (JeffBezanson) [reply src/subtype.c]: Oops, guess I shouldn't comment on intermediate commits :)

Comment (Keno) [reply src/subtype.c]: Yes. This doesn't work. I fixed it in a follow up commit.

File: src/builtins.c [hunk 6]
```diff
@@ -1002,6 +1002,16 @@ JL_CALLABLE(jl_f_apply_type)
         // substituting typevars (a valid_type_param check here isn't sufficient).
         return (jl_value_t*)jl_type_union(&args[1], nargs-1);
     }
+    else if (jl_is_vararg_marker(args[0])) {
+        jl_vararg_marker_t *vm = (jl_vararg_marker_t*)args[0];
+        if (!vm->T) {
+            JL_NARGS(apply_type, 2, 3);
+            return (jl_value_t*)jl_wrap_vararg(args[1], nargs == 3 ? args[2] : NULL);
+        } else if (!vm->N) {
```
Comment (vtjnash) [inline src/builtins.c:1010]:
```suggestion
        }
        else if (!vm->N) {
```

File: src/jltypes.c [hunk 7]
```diff
@@ -529,6 +550,33 @@ JL_DLLEXPORT jl_value_t *jl_type_union(jl_value_t **ts, size_t n)
...
+        if (T_has_tv && N_has_tv) {
+            jl_error("Wrapping `Vararg` directly in UnionAll is disallowed if the typevar occurs in both `T` and `N`");
+        }
+        if (T_has_tv) {
+            jl_value_t *wrapped = jl_type_unionall(v, vm->T);
+            JL_GC_PUSH1(&wrapped);
+            wrapped = (jl_value_t*)jl_wrap_vararg(wrapped, vm->N);
+            JL_GC_POP();
+            return wrapped;
+        } else {
```
Comment (vtjnash) [inline src/jltypes.c:574]:
```suggestion
        }
        else {
```

**Review by vtjnash — COMMENTED** [review]
Looking very good so far

File: base/compiler/typelattice.jl [hunk 8]
```diff
@@ -220,6 +220,7 @@ widenconst(c::PartialTypeVar) = TypeVar
 widenconst(t::PartialStruct) = t.typ
 widenconst(t::Type) = t
 widenconst(t::TypeVar) = t
+widenconst(t::Core.VarargMarker) = t
```
Comment (JeffBezanson) [inline base/compiler/typelattice.jl:223]: Shouldn't widenconst not be called on one of these?

File: base/essentials.jl [hunk 9]
```diff
@@ -255,6 +255,14 @@ function rewrap_unionall(@nospecialize(t), @nospecialize(u))
     return UnionAll(u.var, rewrap_unionall(t, u.body))
 end
 
+function rewrap_unionall(t::Core.VarargMarker, u)
+    isdefined(t, :T) || return t
+    if !isdefined(t, :N) || (isdefined(t, :N) && t.N == u.var)
```
Comment (JeffBezanson) [inline base/essentials.jl:260]:
```suggestion
    if !isdefined(t, :N) || t.N === u.var
```

File: base/essentials.jl [hunk 10]
```diff
@@ -255,6 +255,14 @@ function rewrap_unionall(@nospecialize(t), @nospecialize(u))
     return UnionAll(u.var, rewrap_unionall(t, u.body))
 end
 
+function rewrap_unionall(t::Core.VarargMarker, u)
```
Comment (JeffBezanson) [inline base/essentials.jl:258]:
```suggestion
function rewrap_unionall(t::Core.VarargMarker, @nospecialize(u))
```

File: test/compiler/inference.jl [hunk 11]
```diff
@@ -627,7 +627,7 @@ function maybe_vararg_tuple_1()
 end
 @test Type{Tuple{Vararg{Int}}} <: Base.return_types(maybe_vararg_tuple_1, ())[1]
 function maybe_vararg_tuple_2()
-    x = Type[Vararg{Int}][1]
+    x = [Vararg{Int}][1]
```
Comment (JeffBezanson) [inline test/compiler/inference.jl:630]:
```suggestion
    x = Any[Vararg{Int}][1]
```

File: base/compiler/abstractinterpretation.jl [hunk 12]
```diff
@@ -1045,10 +1045,11 @@ function sp_type_rewrap(@nospecialize(T), linfo::MethodInstance, isreturn::Bool)
         spsig = linfo.def.sig
         if isa(spsig, UnionAll)
             if !isempty(linfo.sparam_vals)
-                env = pointer_from_objref(linfo.sparam_vals) + sizeof(Ptr{Cvoid})
-                T = ccall(:jl_instantiate_type_in_env, Any, (Any, Any, Ptr{Any}), T, spsig, env)
+                sparam_vals = Any[isa(v, Core.VarargMarker) ? TypeVar(:N, Union{}, Any) :
```
[the remark this answers is not in the document]
Comment (Keno) [reply base/compiler/abstractinterpretation.jl:1048]: That's new in this PR to mark an unbound intvalued parameter (We used to use the TypeVar of the unbound Vararg as the sentinel, but we don't have that anymore). Any other non-Type, non-Int sentinel value would do also. I suppose we could change the C interface from `spvals` to `sptypes` as we've done elsewhere. Since `Const` is now a builtin, that should actually work ok.

File: base/compiler/tfuncs.jl [hunk 13]
```diff
@@ -555,18 +554,32 @@ function typeassert_type_instance(@nospecialize(v), @nospecialize(t))
...
+                if new_fields[i] === Bottom
+                    return Bottom
+                end
             end
         end
-        return tuple_tfunc(new_fields)
+        tt = tuple_tfunc(new_fields)
+        if isa(tt, PartialStruct)
+            if !(widenconst(tt) <: ti)
+                return PartialStruct(ti, tt.fields)
```
[the remark this answers is not in the document]
Comment (Keno) [reply base/compiler/tfuncs.jl:577]: So the concern here is that we used to `typeassert_type_instance` the `Vararg`, which while I don't think is entirely correct, did give some precision that we're now losing here. I didn't see a great way to get that back without essentially duplicating intersection over the inference lattice, so I though at least this way we'd recover some precision.

File: base/compiler/typelattice.jl (hunk 8 above)
Comment (Keno) [reply base/compiler/typelattice.jl:223]: Ideally yes, but currently inference is pretty liberal about calling both this and rewrap_unionall on non-Types and I just wanted to preserve the status quo for now. I'd argue a similar argument could be made for `TypeVar` just above.

File: base/promotion.jl [hunk 14]
```diff
@@ -157,9 +157,8 @@ function full_va_len(p)
     isempty(p) && return 0, true
     last = p[end]
     if isvarargtype(last)
-        N = unwrap_unionall(last).parameters[2]
-        if isa(N, Int)
-            return length(p)::Int + N - 1, true
+        if isdefined(last, :N) && isa(last.N, Int)
+            return length(p)::Int + last.N - 1, true
```
[the remark this answers is not in the document]
Comment (Keno) [reply base/promotion.jl:161]: Type assert on last.N?

File: test/compiler/inference.jl (hunk 11 above)
Comment (Keno) [reply test/compiler/inference.jl:630]: This is already tested by the test just above. I figured the most natural translation would be to just have this be typed as ` typeof(Vararg)`..

File: test/syntax.jl [hunk 15]
```diff
@@ -1968,7 +1968,7 @@ let a(; b) = b
 end
 
 # issue #33987
-f33987(args::(Vararg{Any, N} where N); kwargs...) = args
+f33987(args::Vararg{Any, N}; kwargs...) where N = args
```
Comment (JeffBezanson) [inline test/syntax.jl:1971]: This doesn't test the same thing. Might as well delete the test, although it should keep working as long as the deprecation is in place.

Comment (Keno) [reply test/syntax.jl:1971]: Fair. I'd changed this before I put in the deprecation, so I'll change it back to still get the parsing case.

**Comment by Keno** [comment]
StaticArrays has been tagged with a compatibility fix, so let's see what the damage is now:

@nanosoldier `runtests(["ACME", "AEMS", "AES", "AIBECS", "ALFA", "ARDESPOT", "AbstractPlotting", "Accessors", "ActuaryUtilities", "Adapode", "AdvancedHMC", "AgentsPlots", "AlgebraOfGraphics", "AlgebraicPetri", "AlphaStableDistributions", "ApproxBayes", "ApproxFun", "ApproxFunFourier", "ApproxFunOrthogonalPolynomials", "ArnoldiMethodTransformations", "ArrayInterface", "ArraysOfArrays", "AstroImages", "AtlasRobot", "Augmentor", "AutomotiveSimulator", "AxisTables", "BEAST", "BangBang", "BasicPOMCP", "BeliefUpdaters", "BenchmarkFunctions", "BenchmarkProfiles", "Bernstein", "BifurcationKit", "BlackBoxOptim", "BoundingSphere", "BridgeLandmarks", "BridgeSDEInference", "CGAL", "CalculusWithJulia", "Cambrian", "CartesianGrids", "Causal", "ChainRulesCore", "ChaosTools", "ColorSchemes", "CommonRLInterface", "CommunityDetection", "CompScienceMeshes", "ComplexPhasePortrait", "ComplexRegions", "ComponentArrays", "ConnectFourSolver", "ConstrainedControl", "ConstrainedDynamics", "ConstrainedSystems", "ControlSystemIdentification", "CoordinateTransformations", "CrossEntropyMethod", "Curves", "CxxWrap", "DFControl", "DFTK", "DailyTreasuryYieldCurve", "DelayDiffEq", "DelayEmbeddings", "DiffEqBayes", "DiffEqOperators", "DiffResults", "DifferentialForms", "DimensionalPlotRecipes", "DiscreteValueIteration", "Distributions", "Dolo", "DrawSimpleGraphs", "DynamicGridsGtk", "DynamicalBilliards", "DynamicalSystemsBase", "ERFA", "EchogramColorSchemes", "EcologicalNetworksPlots", "EffectiveWaves", "EvalMetrics", "EvoDynamics", "ExprTools", "ExtremeStats", "FIB", "FSInteraction", "FastJet", "FiniteDifferences", "FlashWeave", "ForestBiometrics", "FreeTypeAbstraction", "FymEnvs", "GEMPIC", "GXBeam", "Gaston", "GaussianDistributions", "GaussianFilters", "GaussianRandomFields", "Genie", "GeoArrays", "GeoEstimation", "Geodesy", "GeometricProblems", "GlobalSensitivityAnalysis", "Gnuplot", "GraphPlot", "GraphRecipes", "GridArrays", "GridInterpolations", "GridUtilities", "GridapPETSc", "GrowthMaps", "GrundmannMoeller", "GuidedProposals", "HybridArrays", "HyperbolicPlane", "Hyperopt", "ImageFeatures", "ImageFiltering", "ImageInTerminal", "ImageSegmentation", "ImageTracking", "ImageTransformations", "Images", "ImplicitPlots", "IncrementalPruning", "InteractiveChaos", "InteractiveCodeSearch", "Interpolations", "IntervalArithmetic", "IntervalRootFinding", "InverseDistanceWeighting", "Ising2D", "Jags", "JuliaDB", "JuliaInterpreter", "Jusdl", "Kaleido", "Kinetic", "Kpax3", "LASindex", "LCIO", "LabelledArrays", "Langevin", "LaserTypes", "Layered", "LifeContingencies", "LightGraphs", "LinRegOutliers", "LinearCovarianceModels", "LinearDynamicsModels", "LocalApproximationValueIteration", "LocalizationMicroscopy", "LocallyWeightedRegression", "LuxurySparse", "MCTS", "MCVI", "MIRT", "MPSKitModels", "MakieLayout", "Manifolds", "Manopt", "MbedTLS", "MechanismGeometries", "MeshCore", "MeshSteward", "Meshing", "MetaImageFormat", "ModularIndices", "MonteCarloMeasurements", "NBodySimulator", "NLSolvers", "NMRTools", "NRRD", "NeighbourLists", "NetworkLayout", "NeuroAnalysis", "ObservationSchemes", "OceanGrids", "OceanographyCruises", "OpenDSSDirect", "OpenSpiel", "OpenStreetMapXPlot", "PGFPlots", "POMCPOW", "POMDPFiles", "POMDPModels", "POMDPSimulators", "POMDPSolve", "POMDPXFiles", "Packing", "ParticleFilters", "ParticleMDI", "PassiveTracerFlows", "PhaseSpaceIO", "PhysicalTrees", "PiecewiseIncreasingRanges", "PlotMesh", "PlotThemes", "PoincareInvariants", "PointBasedValueIteration", "PointPatterns", "PolyChaos", "PowerModelsAnalytics", "PredictMDExtra", "Publish", "PyCall", "QMDP", "QuadraticFormsMGHyp", "QuaternionIntegrator", "ReactionNetworkImporters", "RecurrenceAnalysis", "Reel", "RegionTrees", "Remark", "Revise", "RigidBodyTools", "RoME", "RobotDynamics", "RobotZoo", "Robotlib", "RootedTrees", "RvSpectMLPlots", "SARSOP", "SOFA", "SatelliteDynamics", "SatelliteToolbox", "SauterSchwabQuadrature", "SchumakerSpline", "SeisNoise", "SemiDiscretizationMethod", "SeparatingAxisTheorem2D", "SequentialMonteCarlo", "Setfield", "ShaderAbstractions", "SignalAnalysis", "SignalDecomposition", "SimpleDiffEq", "SimpleDrawing", "SimpleSDMLayers", "SingularSpectrumAnalysis", "SkyCoords", "SolidStateDetectors", "StateSpaceEcon", "StateSpaceReconstruction", "StaticPolynomials", "StatsPlots", "StochasticDelayDiffEq", "StochasticProcesses", "StochasticSemiDiscretizationMethod", "Strided", "SubstitutionModels", "TSML", "Tar", "TensorBoardLogger", "TensorKit", "TensorKitManifolds", "TensorValues", "TheNumberLine", "ThreadPools", "TightBinding", "TimeseriesPrediction", "TransformVariables", "UnitfulAstrodynamics", "UnitfulRecipes", "UnivariateFunctions", "VIDA", "ValkyrieRobot", "VertexFinder", "ViscousFlow", "VisualRegressionTests", "VoronoiCells", "WhereTheWaterFlows", "WordCloud", "WorldOceanAtlasTools", "YaoExtensions", "Yields", "Z3"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38136#issuecomment-718247860) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/626eb5dbe956e97cb1780cbb7ebdeb925927350c/pkgeval/by_hash/cdd2414_vs_4fedd83/report.md). cc @maleadt

**Comment by martinholters** [comment]
JuliaInterpreter.jl is another offender:
https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/8bd596bf16f4ce87f839f3d1b6e5a5d25d7db8b4/src/utils.jl#L250-L259

**Comment by vtjnash** [comment]
That seems still potentially correct, since it's testing whether https://github.com/JuliaLang/julia/issues/30995 is an issue

**Comment by Keno** [comment]
Rebased and fixed one more PkgEval-found issue.

**Comment by Keno** [comment]
@nanosoldier `runtests(["Adapode", "AlphaStableDistributions", "AxisTables", "BifurcationKit", "CGAL", "ConnectFourSolver", "CxxWrap", "DailyTreasuryYieldCurve", "DelayDiffEq", "DiffEqOperators", "DifferentialForms", "ExprTools", "FastJet", "HybridArrays", "ImageSegmentation", "InteractiveCodeSearch", "JuliaDB", "JuliaInterpreter", "LASindex", "LCIO", "LabelledArrays", "MPSKitModels", "Manifolds", "Manopt", "NeuroAnalysis", "OpenSpiel", "Publish", "PyCall", "RegionTrees", "Remark", "Revise", "SOFA", "SatelliteDynamics", "StochasticDelayDiffEq", "Tar", "TensorKit", "TensorKitManifolds", "TensorValues", "Z3"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38136#issuecomment-719103447) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/98c9eedabdfd484d9f18dda18c268292d2524d8e/pkgeval/by_hash/c1c80e7_vs_78ade6c/report.md). cc @maleadt

**Comment by Keno** [comment]
This is basically good to go from my perspective. One more full package eval for good measure:
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/38136#issuecomment-721415268):
```
NanosoldierError: failed to run tests: HTTP/1.1 404 Not Found while requesting https://julialangnightlies.s3.amazonaws.com/bin/linux/x64/1.6/julia-2af16f969b-linux64.tar.gz
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/146e799_vs_2af16f9/report.md)
cc @maleadt

**Comment by maleadt** [comment]
Downloads.jl changed; let's try again:

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38136#issuecomment-721548421) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/146e799_vs_1f9e8bd/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Failure summary:
AbstractTensors: does `t <: Vararg`
CGAL: can't find jl_vararg_type in libcxxwrap
ConnectFourSolver: cxxwrap
FastJet: cxxwrap
LCIO: cxxwrap
Manopt: StaticArrays
OpenSpiel: cxxwrap
QML: cxxwrap
SDPA: cxxwrap
SDPAFamily: cxxwrap
Z3: cxxwrap

**Comment by Keno** [comment]
Yeah. I want to look at the issues in CodeTransformations, DelayDiffEq and Transducers, bit otherwise this is looking good. Will also do the type rename, and do a squash and rebase

**Comment by Keno** [comment]
Other than that, we discussed that the only thing to do was a rename `VarargMarker` -> `TypeOfVararg`. I had proposed a show method to print the latter as `typeof(Vararg)`, but that proposal was not liked. (Just leaving notes for myself)

**Comment by JeffBezanson** [comment]
`TypeofVararg`. (We don't capitalize the "o" in `TypeofBottom`; it is what it is :)

**Comment by Keno** [comment]
Alright. Rename is done. Looked at the test failures. CodeTransformation creates invalid internal data structures and just asserts  if you run with assertions on unrelated to this change. DelayDiffEq and Transducers are fixed.

**Comment by Keno** [comment]
I'll plan to merge this once CI is green.

File: base/compiler/inferencestate.jl (hunk 4 above)
Comment (simeonschaub) [reply base/compiler/inferencestate.jl:196]: It doesn't look like this was enough:
```julia
julia> f(::NTuple{N}) where {N} = N
f (generic function with 1 method)

julia> code_warntype(f, Tuple{Tuple})
Variables
  #self#::Core.Const(f)
  #unused#::Tuple{Vararg{T, N}} where T where N

Body::Any
1 ─     return $(Expr(:static_parameter, 1))
```
Or is this check flawed in some way?

**Comment by timholy** [comment]
In the packages I've looked at, where this seems to be causing the most trouble is places like

```julia
map(T -> T <: Real, sig.parameters)
```

Is the absence of support for having `Vararg` on the left side of `<:` deliberate? If so, no worries, but if that's an oversight it might make sense to address it.

**Comment by Keno** [comment]
> Is the absence of support for having `Vararg` on the left side of `<:` deliberate?

Yes, because the code you posted is probably buggy. You want `map(T -> Base.unwrapva(T) <: Real, sig.parameters)`.

**Comment by bkamins** [comment]
Does this change qualify to be included in NEWS.md section "deprecated" section?
