### PR TITLE
re-enable ndigits(::Bool, b) (fix #21919)

### LINKED ISSUE #21919: Broken booleans as numbers?
A recent change broke

```julia
julia> ndigits(true)
1
```

I'm not too fussed about this, and can understand why it didn't go through a deprecation cycle. But I was under the impression that the shift from `Bool <: Integer` to `Bool` as a separate concept has yet to happen. If so, I think it's better to continue to support integer operations on `Bool`.

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

File: base/intfuncs.jl [hunk 1]
```diff
@@ -360,38 +360,39 @@ ndigits(x::Integer) = iszero(x) ? 1 : ndigits0z(x)
 ## ndigits with specified base ##
 
 # The suffix "nb" stands for "negative base"
-function ndigits0znb(n::Integer, b::Integer)
-    # precondition: b < -1 && !(typeof(n) <: Unsigned)
+function ndigits0znb(x::Integer, b::Integer)
```
Comment (ararslan) [inline base/intfuncs.jl]: Out of curiosity, why change the variable name?

Comment (rfourquet) [inline base/intfuncs.jl]: Only for consistency, most `ndigits` methods were receiving an `x`... Sorry to have done two things in this PR.

Comment (ararslan) [inline base/intfuncs.jl]: Oh it's no problem, I was just wondering.

**Review by ararslan — APPROVED** [review]
