### PR TITLE
Make more types jl_static_show readably

### LINKED ISSUE #52677: trace-compile precompile statements incorrect for non-Int signed integer types
```julia
julia> Val{Int32(10)}()
precompile(Tuple{Type{Base.Val{10}}})
```
Which should instead be `precompile(Tuple{Type{Base.Val{Int32(10)}}})`.

Related to #28808, #38902

### PR DESCRIPTION
**Pull request by xal-0**
Makes more types survive `jl_static_show`:
- Symbols
  - Symbols printed in the `:var"foo"` form use raw string escaping, fixing `:var"a\b"`, `:var"a\\"`, `:var"$a"`, etc.
  - Symbols that require parens use parens (`:(=)`, ...)
- Signed integers: Except for `Int`, signed integers print like `Int8(1)`.
- Floats: floats are printed in a naive but reversible (TODO: double check) way. `Inf(16|32|)` and `NaN(16|32|)` are printed, and `Float16`/`Float32` print the type (`Float32(1.5)`).  `Float64`s are printed with a trailing `.0` if it is necessary to disambiguate from `Int`.

Fixes #52677, https://github.com/JuliaLang/julia/issues/58484#issuecomment-2902468354, https://github.com/JuliaLang/julia/issues/58484#issuecomment-2898733637, and the specific case mentioned in #58484.  Improves the situation for #38902 but does not close it, because a few cases still do not round-trip (inexhaustive list):
- Non-canonical NaNs
- BFloat16
- User-defined primitive types.  This one is tricky, because they can have a size different from any type we have literals for.
- Without #40652 or something similar, precompile statements will still fail with field names.

### CODE REVIEW

**Comment by KristofferC** [comment]
For https://github.com/JuliaLang/julia/pull/40652, can we thread something through to not show the field name in precompile printing contexts? Seems unnecessary to have the correctness of the printing be bike shredded on how people want it to print in the debugger.

File: src/rtutils.c [hunk 1]
```diff
@@ -777,6 +804,42 @@ static int jl_static_is_function_(jl_datatype_t *vt) JL_NOTSAFEPOINT {
...
+{
+    size_t n = 0;
+    // TODO: non-canonical NaNs do not round-trip
+    // TOOD: BFloat16
+    const char *size_suffix = vt == jl_float16_type ? "16" :
+                              vt == jl_float32_type ? "32" :
+                                                      "";
+    // Digits required to print p significand bits: ceil(p * log(10, 2))
+    //   Float16   4
+    //   Float32   8
```
Comment (vtjnash) [inline src/rtutils.c:818]: These seem unlikely correct, since the standard given results are one higher for these:
https://github.com/JuliaLang/julia/pull/57977/files#r2028868985
```suggestion
    //   Float16   5
    //   Float32   9
```

File: src/rtutils.c [hunk 2]
```diff
@@ -777,6 +804,42 @@ static int jl_static_is_function_(jl_datatype_t *vt) JL_NOTSAFEPOINT {
...
+    }
+    else if (vt == jl_float64_type) {
+        // If no decimal point or exponent will be printed, we must add ".0"
+        double ipart, fpart;
+        fpart = modf(v, &ipart);
+        int dotzero = v == 0 || (fpart == 0.0 && fabs(ipart) < 1e17);
+        n += jl_printf(out, "%.17g%s", v, dotzero ? ".0" : "");
+    }
+    else if (vt == jl_float32_type) {
+        n += jl_printf(out, "Float32(%.8g)", v);
```
Comment (vtjnash) [inline src/rtutils.c:834]: This can be implemented compactly similar to f64 case, with style '%e' and  `e` replaced with `f` in the buffer

File: src/rtutils.c (hunk 1 above)
Comment (xal-0) [reply src/rtutils.c:826]: Corrected formula from https://dl.acm.org/doi/pdf/10.1145/93542.93559: 

$N = 2 + \left\lfloor\frac{n}{\log_b B}\right\rfloor$

Comment (xal-0) [reply src/rtutils.c:826]:
```
function find_counterexample(T, prec, r)
    buf = zeros(UInt8, 32)
    for i=r
        x = reinterpret(T, i)
        isnan(x) && continue
        n = @ccall snprintf(buf::Ptr{UInt8}, 32::Csize_t, "%.*g"::Cstring; prec::Cint, x::Cdouble)::Csize_t
        ok, y = @ccall jl_try_substrtof(buf::Ptr{UInt8}, 0::Csize_t, n::Csize_t)::Tuple{Bool,Float32}
        ok && x === T(y) || return x
    end
end

@assert find_counterexample(Float16, 4, 0x0000:0xffff) === Float16(0.00010014)
@assert find_counterexample(Float16, 5, 0x0000:0xffff) === nothing

@assert find_counterexample(Float32, 8, 0x00000000:0xffffffff) === 1.00000075f-36
@assert find_counterexample(Float32, 9, 0x00000000:0xffffffff) === nothing
```

File: src/rtutils.c [hunk 3]
```diff
@@ -777,6 +812,55 @@ static int jl_static_is_function_(jl_datatype_t *vt) JL_NOTSAFEPOINT {
...
+    else if (isinf(v)) {
+        n += jl_printf(out, "%sInf%s", v < 0 ? "-" : "", size_suffix);
+    }
+    else if (vt == jl_float64_type) {
+        size_t m = snprintf(buf, sizeof buf, "%.17g", v);
+        jl_uv_puts(out, buf, m);
+        n += m;
+        // If there is no decimal point or exponent, disambiguate
+        if (!strpbrk(buf, ".e"))
+            jl_printf(out, ".0");
```
Comment (vtjnash) [inline src/rtutils.c:844]: While clever, would it be better to use the standard flag `#` for this to preserve all trailing zeros (rather than to imply the trailing digit is `.0` which may not be entirely true given final digit rounding, though I think it would have to round-trip the same since 17 digits is full accuracy)
```suggestion
        n += jl_printf(buf, sizeof buf, "%#.17g", v);
```

Comment (vtjnash) [reply src/rtutils.c]: I assume that later printed as `Float16(-0)`, no? (though that makes it `isequal 0.0`, not `-0.0`)

File: src/rtutils.c [hunk 4]
```diff
@@ -954,17 +1034,21 @@ static size_t jl_static_show_x_(JL_STREAM *out, jl_value_t *v, jl_datatype_t *vt
         int f = *(uint32_t*)jl_data_ptr(v);
         n += jl_printf(out, "#<intrinsic #%d %s>", f, jl_intrinsic_name(f));
     }
+    else if (vt == jl_long_type) {
+        // Avoid unnecessary Int64(x)/Int32(x)
+        n += jl_printf(out, "%" PRIdPTR, *(intptr_t*)v);
+    }
     else if (vt == jl_int64_type) {
```
[the remark this answers is not in the document]
Comment (vtjnash) [reply src/rtutils.c:1041]: It isn't problematic, since that `Int128()` printing means a bitcast, not a function call

[the remark this answers is not in the document]
Comment (vtjnash) [reply src/rtutils.c:1041]: Because it is human readable, and thus a useful debugging tool. Someone should implement a de-serializer if they want to use this for generating precompile statements.

[the remark this answers is not in the document]
Comment (kpamnany) [reply src/rtutils.c:1041]: This is a disingenuous argument @vtjnash -- nobody reads this output for debugging (and we've tried); on the contrary, it is actively used for generating precompile statements. It would be better to remove all the "little gotchas".

**Comment by KristofferC** [comment]
Backporting this to 1.11 gives:

```
Test Failed at /home/kc/julia1.11/test/show.jl:1562
  Expression: v === eval(Meta.parse(static_shown(v)))
   Evaluated: Float16(1.0) === Inf16

Test Failed at /home/kc/julia1.11/test/show.jl:1562
  Expression: v === eval(Meta.parse(static_shown(v)))
   Evaluated: Float16(1.5) === Inf16

Test Failed at /home/kc/julia1.11/test/show.jl:1562
  Expression: v === eval(Meta.parse(static_shown(v)))
   Evaluated: Float16(0.4893) === Inf16

Test Failed at /home/kc/julia1.11/test/show.jl:1562
  Expression: v === eval(Meta.parse(static_shown(v)))
   Evaluated: Float16(0.00010014) === Inf16
....
```

Am I missing some other PR that is needed?

**Comment by kpamnany** [comment]
We needed https://github.com/JuliaLang/julia/pull/52799 also, to backport this to our 1.10 build.

**Comment by KristofferC** [comment]
That should already be on 1.11 though?

**Comment by kpamnany** [comment]
Ah, okay. Then I don't know. Sorry.

**Comment by topolarity** [comment]
Probably related to the Float16 intrinsic fixes that @xal-0 made in 1.12?

**Comment by KristofferC** [comment]
I think it was due to a missing header declaration of a function which defined it implicitly and maybe caused undefined behavior?  On CI this errored and after fixing that it seems like things are OK. Could that be a possible scenario?
