### PR TITLE
restore non-copying String behavior, add unsafe_string*, ...

### LINKED ISSUE #16470: String constructor can segfault
```julia
julia> String(convert(Ptr{UInt8}, 1))
Segmentation fault: 11
```

expected result: `MethodError`, `"Ptr{UInt8}(1)"`, anything but crashing?

Julia constructors shouldn't segfault, only methods that can should have `unsafe_` in the name

### PR DESCRIPTION
**Pull request by stevengj**
This PR closes #16470 and #16713.    It:
- Restores the old non-copying behavior of the `String(a::Vector{UInt8})` constructor, which once again takes ownership of the array.  `bytestring(a)` is now deprecated to `String(copy(a))`.
- Renames `String(ptr, len)` to `unsafe_string(ptr, len)` (this function makes a copy from a pointer).
- Renames `pointer_to_string(ptr, len)` to ~~`unsafe_string_wrapper(ptr, len)`~~  `unsafe_wrap(String, ptr, len)`, which is hopefully more descriptive and now begins with `unsafe` as people seem to prefer.  (This function does not copy the date, but simply "wraps" a `String` around the data.)
- Renames `pointer_to_array` to ~~`unsafe_array_wrapper`~~ `unsafe_wrap(Array, ...)` for consistency.

~~(Note that I had to work around #16730 to document the  `String(a::Vector{UInt8})` constructor by calling `doc!` manually.)~~

In the course of making this change, I had to manually inspect every call to `String(...)`, and I cleaned up many of the call sites somewhat.

### CODE REVIEW

**Comment by stevengj** [comment]
Another possible name, based on @nalimilan's suggestion, would be `unsafe_wrapper(String, ptr, len)` and `unsafe_wrapper(Array, ptr, len)`.  I don't have strong feelings on this.

**Comment by tkelman** [comment]
If we're going to be renaming both these things, +1 to using a more general `unsafe_wrapper(T, ptr, len)` which would be extensible.

File: base/libc.jl [hunk 1]
```diff
@@ -159,7 +159,7 @@ function strftime(fmt::AbstractString, tm::TmStruct)
     if n == 0
         return ""
     end
-    return String(pointer(timestr), n)
+    return unsafe_string(pointer(timestr), n)
```
Comment (vtjnash) [inline base/libc.jl]: I think `String(timestr[1:n])` would be better here

File: base/pointer.jl [hunk 2]
```diff
@@ -35,38 +35,65 @@ unsafe_convert{S,T}(::Type{Ptr{S}}, a::AbstractArray{T}) = convert(Ptr{S}, unsaf
...
-function pointer_to_string(p::Ptr{UInt8}, len::Integer, own::Bool=false)
-    a = ccall(:jl_ptr_to_array_1d, Vector{UInt8},
-              (Any, Ptr{UInt8}, Csize_t, Cint), Vector{UInt8}, p, len, own)
-    ccall(:jl_array_to_string, Ref{String}, (Any,), a)
-end
-pointer_to_string(p::Ptr{UInt8}, own::Bool=false) =
-    pointer_to_string(p, ccall(:strlen, Csize_t, (Cstring,), p), own)
+# unsafe pointer to string conversions (don't make a copy, unlike unsafe_string)
+# (Cstring versions are in c.jl)
+unsafe_string_wrapper(p::Union{Ptr{UInt8},Ptr{Int8}}, len::Integer, own::Bool=false) = ccall(:jl_array_to_string, Ref{String}, (Any,), ccall(:jl_ptr_to_array_1d, Vector{UInt8}, (Any, Ptr{UInt8}, Csize_t, Cint), Vector{UInt8}, p, len, own))
```
Comment (vtjnash) [inline base/pointer.jl]: wrap this line at the start of the ccalls so it fits on github

**Comment by vtjnash** [comment]
The `unsafe_wrap(String, ptr, len)` suggestion sounds good to me. The rest of the PR lgtm.

File: base/client.jl [hunk 3]
```diff
@@ -221,45 +221,45 @@ function process_options(opts::JLOptions)
...
-            eval(Main, parse_input_line(String(opts.postboot)))
+            eval(Main, parse_input_line(unsafe_string(opts.postboot)))
         end
         # load file
         if !isempty(ARGS) && !isempty(ARGS[1])
             # program
             repl = false
             # remove filename from ARGS
-            global PROGRAM_FILE = String(shift!(ARGS))
+            global PROGRAM_FILE = shift!(ARGS)
```
Comment (tkelman) [inline base/client.jl]: maybe a typeassert just in case?

File: base/deprecated.jl [hunk 4]
```diff
@@ -700,11 +703,13 @@ hist2d(v::AbstractMatrix, n1::Integer, n2::Integer) =
 hist2d(v::AbstractMatrix, n::Integer) = hist2d(v, n, n)
 hist2d(v::AbstractMatrix) = hist2d(v, sturges(size(v,1)))
 
-
-
 @deprecate cell(dims::Integer...) Array{Any}(dims...)
 @deprecate cell(dims::Tuple{Vararg{Integer}}) Array{Any}(dims)
 
+@deprecate pointer_to_array{T,N}(p::Ptr{T}, d::Union{Integer,NTuple{N,Int},NTuple{N,Integer}}, own::Bool=false) unsafe_array_wrapper(p, d, own)
```
Comment (tkelman) [inline base/deprecated.jl]: line length - maybe paren form would be better for splitting this

File: base/gmp.jl [hunk 5]
```diff
@@ -514,8 +514,7 @@ hex(n::BigInt) = base(16, n)
 function base(b::Integer, n::BigInt)
     2 <= b <= 62 || throw(ArgumentError("base must be 2 ≤ base ≤ 62, got $b"))
     p = ccall((:__gmpz_get_str,:libgmp), Ptr{UInt8}, (Ptr{UInt8}, Cint, Ptr{BigInt}), C_NULL, b, &n)
-    len = Int(ccall(:strlen, Csize_t, (Cstring,), p))
-    String(pointer_to_array(p,len,true))
+    unsafe_string_wrapper(p, true)
```
Comment (tkelman) [inline base/gmp.jl]: wouldn't the `strlen` have at least checked for embedded nuls here?

File: base/sysimg.jl [hunk 6]
```diff
@@ -341,6 +341,21 @@ include("docs/Docs.jl")
...
+
+Create a new `String` from a vector `v` of bytes containing
+UTF-8 encoded characters.   This function takes "ownership" of
+the array, which means that you should not subsequently modify
+`v` (since strings are supposed to be immutable in Julia) for
+as long as the string exists.
+
+If you need to subsequently modify `v`, use `String(copy(v))` instead.
+"""
+), Dict(:source => :(String(v::Vector{UInt8}) = new(v)), :path=>"boot.jl", :linenumber=>219, :module=>current_module())), Tuple{Vector{UInt8}})
```
Comment (tkelman) [inline base/sysimg.jl]: hopefully this is temporary, but that 219 is likely to go stale quickly

File: base/sysimg.jl [hunk 7]
```diff
@@ -341,6 +341,21 @@ include("docs/Docs.jl")
...
+
```
Comment (MichaelHatherly) [inline base/sysimg.jl]: `:path` and `:linenumber` are meant to point to where the docstring is rather than the method that it documents.  Should also just use the call syntax rather than calling `doc!` directly

```julia
"""
...
"""
String(v::Vector{UInt8})
```

to get the correct metadata.

Placing it with the actual definition would be best, but I don't think it would be possible to have it in `boot.jl` since not enough is defined at that point to get the docsystem working. Perhaps put it with some of the later `String` defs, or maybe in `docs/basedocs.jl` where other "difficult" docs have be put.

**Comment by nalimilan** [comment]
+1 for the cleanup!

I wonder about `unsafe_string` though, since it has no parallel for arrays. Maybe we should even merge it into `unsafe_wrapper` via a `copy` argument?  It would be more natural to me, since the two operations are very similar.

File: base/libc.jl (hunk 1 above)
Comment (nalimilan) [inline base/libc.jl]: Looks like the same pattern is used in several other places. Should they also be changed?

File: base/pointer.jl [hunk 8]
```diff
@@ -35,38 +35,65 @@ unsafe_convert{S,T}(::Type{Ptr{S}}, a::AbstractArray{T}) = convert(Ptr{S}, unsaf
...
+    unsafe_array_wrapper(pointer, dims, own=false)
+
+Wrap a native pointer as a Julia Array object. The pointer element type determines the array
+element type. `own` optionally specifies whether Julia should take ownership of the memory,
+calling `free` on the pointer when the array is no longer referenced.
+
+This function is labelled "unsafe" because it will crash if `pointer` is not
+a valid memory address to data of the requested length.
+"""
+unsafe_array_wrapper
```
Comment (nalimilan) [inline base/pointer.jl]: Cosmetic point: maybe more logical to document `function unsafe_array_wrapper end` *before* its methods definitions?

File: base/gmp.jl (hunk 5 above)
Comment (stevengj) [inline base/gmp.jl]: `unsafe_string_wrapper` calls `strlen` if you don't pass `len`.   Anyway, `mpz_get_str` returns a nul-terminated string, so it won't have embedded nuls.

File: base/sysimg.jl (hunk 6 above)
Comment (stevengj) [inline base/sysimg.jl]: Yeah, but I figured it is better than nothing, and it's not terrible if the line number is wrong anyway... I don't know if we even use this for anything right now.

File: base/sysimg.jl (hunk 7 above)
Comment (stevengj) [inline base/sysimg.jl]: Ah, I didn't know that you could use a docstring with the call syntax.   Is this documented anywhere?  If not, it should be.

File: base/pointer.jl (hunk 8 above)
Comment (stevengj) [inline base/pointer.jl]: You can't document it before it is defined.

Comment (tkelman) [inline base/pointer.jl]: you can define it with the zero-method `function end` syntax though, just for the purposes of documenting

File: base/gmp.jl (hunk 5 above)
Comment (tkelman) [inline base/gmp.jl]: should unsafe_string_wrapper call strlen as Cstring though?

File: base/pointer.jl (hunk 8 above)
Comment (stevengj) [inline base/pointer.jl]: Ah, I see.   (It would be good if this were explained in the manual.  There's an obscure comment about the `function end` syntax being "preferred" with no explanation.)

Comment (tkelman) [inline base/pointer.jl]: yes it would. we should write down a list of new things that are poorly documented that you've been noticing.

File: base/sysimg.jl (hunk 7 above)
Comment (MichaelHatherly) [inline base/sysimg.jl]: It's mentioned very briefly in http://docs.julialang.org/en/latest/manual/documentation/#functions-and-methods. Definitely worth expanding that part of the manual.

File: base/libc.jl (hunk 1 above)
Comment (stevengj) [inline base/libc.jl]: Probably.  But there are also a lot of `unsafe_string(pointer(buffer))` usages that are not so easily changed, because they use nul-termination to compute the string length.

File: base/client.jl (hunk 3 above)
Comment (stevengj) [inline base/client.jl]: `ARGS` is a `Vector{String}`, a typeassert seems superfluous.  The only reason for the `String` call here was that this used to be `UTF8String(shift!(ARGS))` and in those days the conversion was needed to avoid having the type of `PROGRAM_FILE` depend on the arguments.   I think it just got auto search-and-replaced by `String` when @StefanKarpinski made the switch.

File: base/gmp.jl (hunk 5 above)
Comment (stevengj) [inline base/gmp.jl]: No.  Or rather, it doesn't matter.  `Cstring` does not check for embedded nuls if it is passed a pointer argument — there is no way to do so, unless you have independent information on the length.   When you pass a pointer, `Cstring` is equivalent to `Ptr{UInt8}`.

**Comment by stevengj** [comment]
Renamed to `unsafe_wrap(T, ptr, ...)` for `T=Array` or `T=String`.

File: base/datafmt.jl [hunk 9]
```diff
@@ -40,26 +40,22 @@ readdlm(input, dlm::Char, eol::Char; opts...) =
...
-           isa(input, IO) ? readstring(input) :
-           input
-    readdlm_string(sinp, dlm, T, eol, auto, optsd)
-end
-
-function as_mmap(fname::AbstractString, fsz::Int64)
-    open(fname) do io
-        Mmap.mmap(io, Vector{UInt8}, (Int(fsz),))
+    fsz = filesize(input)
+    if use_mmap && fsz > 0 && fsz < typemax(Int)
```
Comment (stevengj) [inline base/datafmt.jl]: This check is from the original code, but I think the `fsz > 0` check is probably because of #10516, so this check can be removed now.

And I don't understand the `typemax(Int)` check.... is there any circumstance in which `fsz > typemax(Int)` and `readstring(input)` will succeed?  And why would `mmap` fail if `fsz == typemax(Int)`?

Comment (stevengj) [inline base/datafmt.jl]: @tanmaykm, you added the original version of this code in #3468, can you comment?

Comment (stevengj) [inline base/datafmt.jl]: Hmm, or actually it was @timholy in dcb01ae1948f1ef71a5c003562998ff233287832, for #3658.  Is this still relevant?

Comment (stevengj) [inline base/datafmt.jl]: The current `mmap` actually requires `len < typemax(Int) - PAGESIZE`

Comment (stevengj) [inline base/datafmt.jl]: And why don't we use `mmap` by default on Windows?

Comment (tkelman) [inline base/datafmt.jl]: many people want to see this file removed from base entirely

Comment (stevengj) [inline base/datafmt.jl]: Sometimes I think this drive to push things out of Base is venturing too much into purism for its own sake.   Julia's core market is technical users, and the "batteries included" philosophy is very appealing there.    Also, because Julia is so rapidly evolving, it is a struggle to keep packages up to date, whereas including key functionality in Base makes it much easier to update it along with changes to the core language.  (It also makes it easier to evaluate changes, because we immediately see their impact.)

But in any case, not a debate for this PR.

Comment (tkelman) [inline base/datafmt.jl]: we constantly get complaints that readcsv is slow. independent developments outside of base are already better. don't want to get into Python's situation of broken batteries that no one uses because the packages are better and the stdlib is frozen. need to limit scope if julia the language is going to get to 1.0 soon enough for it to succeed outside of academic early adopters.

things being developed in different repos is just a workflow and automation problem that is easily solvable.

**Comment by StefanKarpinski** [comment]
Thank you, @stevengj! This was a wonderful birthday present.

**Comment by stevengj** [comment]
I can't reproduce the Travis method ambiguity error on OSX, and it's weird that this failure doesn't occur on any other platform.  Maybe I should just rebase and try again?

**Comment by stevengj** [comment]
Yay, tests are green.

**Comment by TotalVerb** [comment]
Was the original ambiguity problem a Julia bug? That should probably be reported as a separate issue.

**Comment by stevengj** [comment]
I'm not actually sure, since I couldn't reproduce it. I could see how the original method definitions might be ambiguous, though I didn't think about it too hard since the code needed simplifying anyway.

**Comment by TotalVerb** [comment]
I don't understand how this is supposed to work. Is this expected?

```julia
julia> f{T}(::Union{Type{Array},Type{Array{T}}}, ::Integer) = 1
f (generic function with 1 method)

julia> f(Array, 1)
ERROR: MethodError: no method matching f(::Type{Array}, ::Int64)
Closest candidates are:
  f{T}(::Union{Type{Array{T,N}},Type{Array}}, ::Integer)
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

julia> f{T}(::Union{Type{Array},Type{Array{T}}}, ::Int) = 2
f (generic function with 2 methods)

julia> f(Array, 1)
ERROR: MethodError: f(::Type{Array}, ::Int64) is ambiguous. Candidates:
  svec(Tuple{#f,Type{Array},Int64},svec(T),f{T}(::Union{Type{Array{T,N<:Any}},Type{Array}}, ::Int64) at REPL[4]:1)
  svec(Tuple{#f,Type{Array},Int64},svec(T),f{T}(::Union{Type{Array{T,N<:Any}},Type{Array}}, ::Integer) at REPL[2]:1)
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

I think what I don't understand here is:

 - why the first method didn't match,
 - and how there can be an ambiguity when the first method didn't match in the first place.

If I'm not missing something obvious here, I'll report it as a separate issue.

**Comment by yuyichao** [comment]
The type parameter cannot be determined.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/13702

**Comment by yuyichao** [comment]
This is at least possible to handle and it seems that this is correctly handled on master (which is why #3738 is closed). The case you had above should not work and explaining it better in the doc is why #13702 is still open AFAICT.

File: base/strings/basic.jl [hunk 10]
```diff
@@ -19,31 +19,43 @@ This representation is often appropriate for passing strings to C.
...
+(The pointer can be safely freed afterwards.) If `length` is specified
+(the length of the data in bytes), the string does not have to be NUL-terminated.
+
+This function is labelled "unsafe" because it will crash if `p` is not
+a valid memory address to data of the requested length.
 
-Create a string from the address of a C (0-terminated) string encoded as UTF-8.
-A copy is made so the pointer can be safely freed. If `length` is specified, the
-string does not have to be 0-terminated.
+See also [`unsafe_string_wrapper`](:func:`unsafe_string_wrapper`), which takes a pointer
```
Comment (tkelman) [inline base/strings/basic.jl]: not called that any more

File: base/pointer.jl [hunk 11]
```diff
@@ -35,38 +35,61 @@ unsafe_convert{S,T}(::Type{Ptr{S}}, a::AbstractArray{T}) = convert(Ptr{S}, unsaf
...
 # unsafe pointer to array conversions
-function pointer_to_array{T}(p::Ptr{T}, d::Integer, own::Bool=false)
-    ccall(:jl_ptr_to_array_1d, Vector{T},
-          (Any, Ptr{Void}, Csize_t, Cint), Array{T,1}, p, d, own)
-end
-function pointer_to_array{T,N}(p::Ptr{T}, dims::NTuple{N,Int}, own::Bool=false)
+"""
+    unsafe_wrap(Array, pointer, dims, own=false)
+
+Wrap a native pointer as a Julia `Array `object. The pointer element type determines the array
```
Comment (tkelman) [inline base/pointer.jl]: ```  `Array` object.```

File: doc/stdlib/c.rst [hunk 12]
```diff
@@ -112,11 +112,13 @@
 
    Calling ``Ref(array[, index])`` is generally preferable to this function.
 
-.. function:: pointer_to_array(pointer, dims[, take_ownership::Bool])
+.. function:: unsafe_wrap(Array, pointer, dims, own=false)
 
    .. Docstring generated from Julia source
 
-   Wrap a native pointer as a Julia Array object. The pointer element type determines the array element type. ``own`` optionally specifies whether Julia should take ownership of the memory, calling ``free`` on the pointer when the array is no longer referenced.
+   Wrap a native pointer as a Julia ``Array `object. The pointer element type determines the array element type. `dims`` is either an integer (for a 1d array) or a tuple of the array dimensions. ``own`` optionally specifies whether Julia should take ownership of the memory, calling ``free`` on the pointer when the array is no longer referenced.
```
Comment (tkelman) [inline doc/stdlib/c.rst]: genstdlib got surprisingly confused by swapping a space and backtick...

File: NEWS.md [hunk 13]
```diff
@@ -92,6 +92,16 @@ Breaking changes
...
 
+  * Strings ([#16107]):
+
+    * The `UTF8String` and `ASCIIString` types have been merged into a single
+      `String` type ([#16058]).  Use `isascii(s)` to check whether
+      a string contains only ASCII characters.
+
+    * The basic string construction routines are now `string(args...)`,
+      `String(s)`, `unsafe_string(ptr)` (formerly `bytestring(ptr)`), and
+      `unsafe_wrap(String, ptr)` (formerly `pointer_to_array`) ([#16731]).
```
Comment (JeffBezanson) [inline NEWS.md]: Did you mean `pointer_to_string` here?

**Comment by JeffBezanson** [comment]
A big +1 to merging this.

**Comment by stevengj** [comment]
Rebased.

**Comment by StefanKarpinski** [comment]
I'm guessing that the libgit2 error is unrelated.

**Comment by tkelman** [comment]
#16555. merge away

**Comment by bkamins** [comment]
@stevengj This PR in particular introduced https://github.com/JuliaLang/julia/blob/master/stdlib/DelimitedFiles/src/DelimitedFiles.jl#L229

This makes `readdlm` mutate `input` if it is `Vector{UInt8}`. Was it intended or rather `String(copy(input))` should be a proper implementation here?

**Comment by stevengj** [comment]
@bkamins, `String(input)` looks correct to me there — there is no need to make a copy of `input`, because `input` is never modified during the execution of the function and the string is discarded on return.  So avoiding the copy is good.

**Comment by bkamins** [comment]
The problem is that `input` is modified. See:
```
julia> using DelimitedFiles

julia> s = """a,b,c
       1,2,3"""
"a,b,c\n1,2,3"

julia> input = Vector{UInt8}(s)
11-element Array{UInt8,1}:
 0x61
 0x2c
 0x62
 0x2c
 0x63
 0x0a
 0x31
 0x2c
 0x32
 0x2c
 0x33

julia> readdlm(input, ',')
2×3 Array{Any,2}:
  "a"   "b"   "c"
 1     2     3

julia> input
0-element Array{UInt8,1}
```

**Comment by stevengj** [comment]
Oh, right, I forgot that `String(bytes)` nowadays truncates the `bytes` array.

It seems a shame to make a copy here, since the input could potentially be quite large.  We could use `unsafe_string(pointer(bytes), length(bytes))` as long as we do `GC.@preserve`.   Alternatively, maybe we should have an `unsafe_string(bytes)` method that makes a string without truncating `bytes`.
