### PR TITLE
Fix tbaa usage when storing into heap allocated immutable structs

### LINKED ISSUE #58470: `Union{Nothing,Int}` field in mutable struct, when set to `nothing`, sometimes reads as garbage `Int` in >=1.11
MWE:
```julia
mutable struct Wrapper
    x::Union{Nothing,Int}
end

function findsomething(dict, inds)
    default = Wrapper(nothing)
    for i in inds
        x = get(dict, i, default).x
        if !isnothing(x)
            return x
        end
    end
    return nothing
end

for i in 1:100000
    x = findsomething(Dict(1 => Wrapper(nothing)), [2])
    if !isnothing(x)
        @error "" x
        break
    end
end

```
Output:
```sh
$ julia +lts     --startup-file=no bug.jl  # 1.10.9
$ julia +release --startup-file=no bug.jl  # 1.11.5
┌ Error:
│   x = 4494295104
└ @ Main ~/bug/bug.jl:19
$ julia +beta    --startup-file=no bug.jl  # 1.12-beta3
┌ Error:
│   x = 0
└ @ Main ~/bug/bug.jl:19
$ julia +nightly --startup-file=no bug.jl  # 1.13-DEV.590
┌ Error:
│   x = 2
└ @ Main ~/bug/bug.jl:19
```
As shown, in Julia >=1.11, `default` can get corrupted such that `default.x` reads as a garbage `Int` instead of `nothing`, even though it was initialized to `nothing` and never mutated.

This does not happen if `Wrapper` is not mutable and/or `default` is a global const instead of a local.

Xref https://discourse.julialang.org/t/unmutated-mutable-type-being-corrupted/129161

Platform info (except Julia version as shown above):
```julia-repl
ulia> versioninfo()
Julia Version 1.11.5
Commit 760b2e5b739 (2025-04-14 06:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 14 × Apple M4 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 10 virtual cores)
```

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes https://github.com/JuliaLang/julia/issues/58470. In https://github.com/JuliaLang/julia/pull/54604 this was half fixed but at that point I was already skeptical of the union selector being part of stack, where it's actually part of a value. ~~This creates a immutunionselbyte tbaa and a mut version.~~

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -331,11 +331,12 @@ struct jl_tbaacache_t {
     // LLVM should have enough info for alias analysis of non-gcframe stack slot
     // this is mainly a place holder for `jl_cgval_t::tbaa`
     MDNode *tbaa_stack;      // stack slot
-    MDNode *tbaa_unionselbyte;   // a selector byte in isbits Union struct fields
+    MDNode *tbaa_immut_unionselbyte;   // a selector byte in isbits Union struct fields
```
Comment (topolarity) [inline src/codegen.cpp:334]: These comments are organized (and indentation is formatted) to represent the tree of the TBAA hierarchy, so any updates should preserve that

**Review by topolarity — CHANGES_REQUESTED** [review]

File: src/codegen.cpp [hunk 2]
```diff
@@ -386,8 +386,11 @@ struct jl_tbaacache_t {
         MDNode *tbaa_mutab_scalar;
         std::tie(tbaa_mutab, tbaa_mutab_scalar) =
             tbaa_make_child(mbuilder, "jtbaa_mutab", tbaa_value_scalar);
+        MDNode *tbaa_immut_scalar;
         tbaa_datatype = tbaa_make_child(mbuilder, "jtbaa_datatype", tbaa_mutab_scalar).first;
-        tbaa_immut = tbaa_make_child(mbuilder, "jtbaa_immut", tbaa_value_scalar).first;
+        tbaa_mutable_unionselbyte = tbaa_make_child(mbuilder, "jtbaa_mut_unionselbyte", tbaa_mutab_scalar).first;
+        std::tie(tbaa_immut, tbaa_immut_scalar) = tbaa_make_child(mbuilder, "jtbaa_immut", tbaa_value_scalar);
+        tbaa_immut_unionselbyte = tbaa_make_child(mbuilder, "jtbaa_immut_unionselbyte", tbaa_immut_scalar).first;
```
Comment (topolarity) [inline src/codegen.cpp:393]: This expresses that `tbaa_immut_unionselbyte` does not alias `tbaa_stack` - is that what you intended?

Comment (gbaraldi) [reply src/codegen.cpp:393]: It doesn't (it never did which is why it was odd that is was there).

Comment (topolarity) [reply src/codegen.cpp:393]: Is this not a usage on the stack? https://github.com/JuliaLang/julia/blob/4b90899c7dfc98db75ff47e9005d208d69aa29d9/src/cgutils.cpp#L4328

Comment (gbaraldi) [reply src/codegen.cpp:393]: But that means it doesn't alias tbaa_immut which causes some issues 😄

**Review by topolarity — APPROVED** [review]
Nice work! This looks more consistent with the hierarchy now 👍

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/58483#issuecomment-2898838445) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/3d47432_vs_c940a31/report.md).
