### PR TITLE
isposdef rewrite with help of cholfact

### LINKED ISSUE #392: isposdef() is incorrect
isposdef() is claiming that some (though not all) positive-semi definite matrices are positive definite when they are not:

```
julia> A = [1.69  2.21; 2.21  2.89]
2×2 Array{Float64,2}:
 1.69  2.21
 2.21  2.89
julia> det(A)
0.0
julia> isposdef(A)
true
julia> isposdef(ones(2,2))
false
```

I'm not sure what's causing this behaviour -- it looks like isposdef() attempts to make a Cholesky decomposition of the matrix, and all positive semi-definite matrices have a Cholesky decomposition (though IIRC there is no general algorithm for finding them). It seems to me that it would be simpler to just implement Sylvestor's criterion with something like
```
sylvestor(A) = issymmetric(A) & all([det(A[1:j, 1:j]) > 0 for j = 1:size(A)[1]])
```

Version info:
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

### LINKED ISSUE #20004: isposdef() is incorrect
isposdef() is claiming that some (though not all) positive-semi definite matrices are positive definite when they are not:

```
julia> A = [1.69  2.21; 2.21  2.89]
2×2 Array{Float64,2}:
 1.69  2.21
 2.21  2.89
julia> det(A)
0.0
julia> isposdef(A)
true
julia> isposdef(ones(2,2))
false
```

I'm not sure what's causing this behaviour -- it looks like isposdef() attempts to make a Cholesky decomposition of the matrix, and all positive semi-definite matrices have a Cholesky decomposition (though IIRC there is no general algorithm for finding them). It seems to me that it would be simpler to just implement Sylvestor's criterion with something like
```
sylvestor(A) = issymmetric(A) & all([det(A[1:j, 1:j]) > 0 for j = 1:size(A)[1]])
```

Version info:
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Finally implementing https://github.com/JuliaLang/LinearAlgebra.jl/issues/422 after JuliaLang/julia#21595, JuliaLang/julia#21976 and JuliaLang/julia#22188 :tada: 

I removed the `isposdef[!](::Matrix, ::Symbol)` methods (similarly as for JuliaLang/julia#22188). They were not documented, and I got the feeling they were more of internal methods to dispatch to LAPACK. This is potentially breaking, since there are no real replacement. The closest would be to deprecate it for `isposdef(Hermitian(A, uplo))` but that may throw an `ArgumentError` in the `Hermitian` constructor for `Matrix{Complex}`. Should we:
1. throw an error saying it is discontinued?
2. copy the old code to deprecated.jl and throw a depwarn?
3. keep it?

Fix JuliaLang/LinearAlgebra.jl#392

### CODE REVIEW

**Comment by andreasnoack** [comment]
Great. I think deprecation for `isposdef(Hermitian(A, uplo))` is the best solution

> but that may throw an `ArgumentError` in the `Hermitian` constructor for `Matrix{Complex}`

Argh. The `Hermitian` constructor exception again.

**Comment by fredrikekre** [comment]
Test failure is caused by this...

```julia
julia> typeof(Hermitian(Symmetric(rand(2, 2))))
Hermitian{Float64,Symmetric{Float64,Array{Float64,2}}}
```

Any objections to make that `Hermitian{Float64, Array{Float64,2}}` similarly as in #21622? It simplifies methods like this:

```julia
isposdef(A::AbstractMatrix) = ishermitian(A) && isposdef(cholfact(Hermitian(A)))
```
if `A` would be `Symmetric`. Otherwise we need a special method for `isposdef(::Symmetric)`.

**Comment by fredrikekre** [comment]
It is possible to skip the check in the constructor though, so this will work:
```julia
@deprecate isposdef(A::AbstractMatrix, UL::Symbol) isposdef(Hermitian{eltype(A), typeof(A)}(A, char_uplo(UL)))
```
assuming `LAPACK.potrf!` will return a positive `info`.

**Comment by fredrikekre** [comment]
Actually that method is bugged (essentially the same problem as #22187), so we should probably go with option 1 above?

```julia
julia> A = complex.(rand(2, 2), rand(2, 2)); A[2, 1] = conj(A[1, 2]); A
2×2 Array{Complex{Float64},2}:
 0.826553+0.997144im  0.281465+0.162411im
 0.281465-0.162411im  0.146851+0.549507im

julia> ishermitian(A)
false

julia> isposdef(A)
false

julia> isposdef(A, :U)
true

julia> isposdef(Hermitian{eltype(A), typeof(A)}(A, 'U'))
true
```

Deprecate it as in https://github.com/JuliaLang/julia/pull/22245#issuecomment-306721485 would at least result in the same bugged behavior but feels weird to keep supporting a bugged function ....

**Comment by fredrikekre** [comment]
Rebased after #22264 and added deprecations,  should be good now.

**Review by KristofferC — APPROVED** [review]

File: base/linalg/dense.jl [hunk 1]
```diff
@@ -74,10 +71,8 @@ julia> isposdef(A)
 true
 ```
 """
-function isposdef(A::AbstractMatrix{T}) where T
-    S = typeof(sqrt(one(T)))
-    isposdef!(S == T ? copy(A) : convert(AbstractMatrix{S}, A))
-end
+isposdef(A::AbstractMatrix{T}) where {T} =
+    isposdef!(copy_oftype(A, promote_type(typeof(chol(one(T))),Float32)))
```
Comment (tkelman) [inline base/linalg/dense.jl]: why the promotion with Float32 in such a general method?

Comment (fredrikekre) [inline base/linalg/dense.jl]: Copied from here: https://github.com/JuliaLang/julia/blob/2d8c0f9160812dba14c08b3602d907f561e843fe/base/linalg/cholesky.jl#L279-L280
Essentially to be able to call `cholfact` inplace.

The alternative would be to define:
`isposdef(A::AbstractMatrix) = ishermitian(A) && isposdef(cholfact(A))`
that might actually be cleaner, and avoids the copy if `A` is not Hermitian.
Thoughts?

File: test/linalg/eigen.jl [hunk 2]
```diff
@@ -35,14 +35,15 @@ aimg  = randn(n,n)/2
         @test eab[1] == eigvals(fill(α,1,1),fill(β,1,1))
         @test eab[2] == eigvecs(fill(α,1,1),fill(β,1,1))
 
-        d,v   = eig(a)
         @testset "non-symmetric eigen decomposition" begin
+            d,v   = eig(a)
```
Comment (Sacha0) [inline test/linalg/eigen.jl]: Perhaps fix the odd spacing? :)

File: base/linalg/dense.jl (hunk 1 above)
Comment (fredrikekre) [inline base/linalg/dense.jl]: So with `isposdef2` as in the comment above we have the following:
```julia
julia> for n in (10, 100, 1000)
           A = rand(n,n); B = A'A
           println("non-hermitian $n x $n")
           @btime isposdef($A)
           @btime isposdef2($A)
           println("hermitian $n x $n")
           @btime isposdef($B)
           @btime isposdef2($B)
       end
non-hermitian 10 x 10
  69.209 ns (2 allocations: 912 bytes)
  7.838 ns (0 allocations: 0 bytes)
hermitian 10 x 10
  487.292 ns (8 allocations: 1.05 KiB)
  500.427 ns (9 allocations: 1.08 KiB)
non-hermitian 100 x 100
  4.054 μs (3 allocations: 78.22 KiB)
  7.653 ns (0 allocations: 0 bytes)
hermitian 100 x 100
  37.041 μs (9 allocations: 78.38 KiB)
  36.770 μs (10 allocations: 78.41 KiB)
non-hermitian 1000 x 1000
  808.359 μs (3 allocations: 7.63 MiB)
  7.651 ns (0 allocations: 0 bytes)
hermitian 1000 x 1000
  6.166 ms (9 allocations: 7.63 MiB)
  6.129 ms (10 allocations: 7.63 MiB)
```

So I will definitely update to the definition in the comment above.

File: test/linalg/eigen.jl (hunk 2 above)
Comment (fredrikekre) [inline test/linalg/eigen.jl]: Fixed

File: base/linalg/dense.jl (hunk 1 above)
Comment (tkelman) [inline base/linalg/dense.jl]: doesn't need to be addressed in this PR, but does that indicate that maybe the other instance of this Float32 promotion should maybe get the same treatment?

Comment (fredrikekre) [inline base/linalg/dense.jl]: It's from 186287a2a891baf0edf658220b43e3077af00904 but from the comment it seems like it could have been removed in 5e880747d8c0e444863a6676a4ea43c758858999?

Comment (andreasnoack) [inline base/linalg/dense.jl]: I'm a bit rusty on the promotion logic here but there is a difference between pivoted and non-pivoted since we don't yet have a generic version for the latter.
