### PR TITLE
fix #34659, regression in showing empty arrays as matrix elements

### LINKED ISSUE #34659: Wrong display for arrays of empty arrays
The display of `[Int[]]` got recently broken, probably in #34387:
```julia
julia> [[1]]
1-element Array{Array{Int64,1},1}:
 [1]

julia> [Int[]]
1-element Array{Array{Int64,1},1}:
 0-element Array{Int64,1}
```

cc @fchorney

### PR DESCRIPTION
**Pull request by JeffBezanson**
Fixes #34659, by just hacking it in.
This is an alternative to #34733.

Before:
```
julia> [Int[]]
1-element Array{Array{Int64,1},1}:
 0-element Array{Int64,1}
```
After (same output as 1.4):
```
julia> [Int[]]
1-element Array{Array{Int64,1},1}:
 []
```
If this is ok I'll add tests.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Ah, so the same hack is needed for other container types:
```
julia> [Dict()]
1-element Array{Dict{Any,Any},1}:
 Dict{Any,Any} with 0 entries
```

I could add AbstractDict and AbstractSet to the hack of course. Or I think an alternative is to always use parseable syntax for empty containers, in other words
```
julia> Dict()
Dict{Any,Any}()
```

the idea being that the output `Dict{Any,Any} with 0 entries` doesn't add much value.

**Comment by StefanKarpinski** [comment]
I think printing the empty versions of those with a reconstructable syntax is preferable.

**Comment by JeffBezanson** [comment]
Done. I went a little bit inconsistent and decided that `3×0 Array{Float64,2}` is preferable to `Array{Float64}(undef,3,0)` though.

**Comment by JeffBezanson** [comment]
Some examples:
```
julia> permutedims([zeros(3,2),zeros(2,2)])
1×2 Array{Array{Float64,2},2}:
 [0.0 0.0; 0.0 0.0; 0.0 0.0]  [0.0 0.0; 0.0 0.0]

julia> permutedims([zeros(3,0),zeros(2,0)])
1×2 Array{Array{Float64,2},2}:
 3×0 Array{Float64,2}  2×0 Array{Float64,2}

julia> permutedims([zeros(3),zeros(2)])
1×2 Array{Array{Float64,1},2}:
 [0.0, 0.0, 0.0]  [0.0, 0.0]

julia> permutedims([Int[],Int[]])
1×2 Array{Array{Int64,1},2}:
 []  []

julia> keys(Dict())
Base.KeySet for a Dict{Any,Any} with 0 entries

julia> [keys(Dict())]
1-element Array{Base.KeySet{Any,Dict{Any,Any}},1}:
 Base.KeySet for a Dict{Any,Any} with 0 entries

julia> permutedims([keys(Dict()), keys(Dict())])
1×2 Array{Base.KeySet{Any,Dict{Any,Any}},2}:
 []  []

julia> [undef,undef]
2-element Array{UndefInitializer,1}:
 UndefInitializer(): array initializer with undefined values
 UndefInitializer(): array initializer with undefined values

julia> permutedims([undef,undef])
1×2 Array{UndefInitializer,2}:
 UndefInitializer()  UndefInitializer()
```

**Comment by tkf** [comment]
What'll happen to

```julia
julia> view(ones(3), 2:1)
0-element view(::Array{Float64,1}, 2:1) with eltype Float64
```

?  Is it going to be

`SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}(Float64[])`

?

**Comment by JeffBezanson** [comment]
That is a good question. Apparently, views don't have a reasonable `show` method:
```
julia> show(view(ones(3), 2:1))
Float64[]
```
so I'm not sure what to do.

**Comment by JeffBezanson** [comment]
> Is it going to be
> 
> `SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}(Float64[])`

Maybe --- the current output is:
```
julia> x=view(ones(3,3), 2:1,3:1);

julia> x
0×0 view(::Array{Float64,2}, 2:1, 3:2) with eltype Float64

julia> show(x)

```
that's right folks, the empty string. :scream: :scream:

**Comment by JeffBezanson** [comment]
TIL people hate parseable output so much they would rather have NO output.

**Comment by tkf** [comment]
Isn't empty string a valid Julia code?

File: base/arrayshow.jl [hunk 1]
```diff
@@ -320,6 +320,7 @@ print_array(io::IO, X::AbstractArray) = show_nd(io, X, print_matrix, true)
 # typeinfo aware
 # implements: show(io::IO, ::MIME"text/plain", X::AbstractArray)
 function show(io::IO, ::MIME"text/plain", X::AbstractArray)
+    isempty(X) && ndims(X) == 1 && return show(io, X)
```
Comment (tkf) [inline base/arrayshow.jl:323]: This is essentially what I suggested in #34733, but why not `get(io, :compact, false) === true && return show(io, X)`?

Comment (JeffBezanson) [reply base/arrayshow.jl:323]: Hmm, there are tests for this, e.g.
```
replstr([x, x], :compact => true) == "2-element Array{Float64,1}:\n 3.14159\n 3.14159"
```
I guess the idea was to be able to keep the overall repl printing format but forcing elements to be shown compactly.

Comment (tkf) [reply base/arrayshow.jl]: I see. I think this is another instance of the limitation for using `:compact` to mean "small width" and "single line."

**Comment by rfourquet** [comment]
> 3×0 Array{Float64,2} is preferable to Array{Float64}(undef,3,0)

At least for numbers, what about `zeros(Float64, 3, 0)` ?

**Comment by JeffBezanson** [comment]
That's a good idea, but I think it's a bit fiddly to need to know whether `zeros` would work for a certain type. I'll just leave it like this for now, future improvements welcome.
