### PR TITLE
Add repeat for Char to fix performance of pow

### LINKED ISSUE #22785: Add specialized repeat function for Char
Ref https://github.com/JuliaLang/julia/pull/22532#issuecomment-314616151

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaLang/julia/issues/22785

But more importantly fix the bug for  `::Char ^ 0` and `::Char^1`

As a future optimization someone may want to improve the nonascii case to remove the allocation for the string conversion. 

```julia
# benchmark using 0.6

julia> using BenchmarkTools; import Base.repeat, Base._string_n

julia> function repeat(c::Char, r::Integer)
           r < 0 && throw(ArgumentError("can't repeat a character $r times"))
           if isascii(c)
               out = _string_n(r)
               ccall(:memset, Ptr{Void}, (Ptr{UInt8}, Cint, Csize_t), out, c, r)
               return out
           else
               return repeat(string(c), r)
           end
       end
repeat (generic function with 4 methods)

julia> @btime repeat($('x'), $(100));
  28.140 ns (1 allocation: 128 bytes)

julia> @btime repeat($("x"), $(100));
  280.596 ns (1 allocation: 128 bytes)

julia> @btime repeat($('x'), $(10));
  18.158 ns (1 allocation: 32 bytes)

julia> @btime repeat($("x"), $(10));
  42.239 ns (1 allocation: 32 bytes)

julia> @btime repeat($('x'), $(2));
  18.158 ns (1 allocation: 32 bytes)

julia> @btime repeat($("x"), $(2));
  21.711 ns (1 allocation: 32 bytes)
```

### CODE REVIEW

File: base/strings/string.jl [hunk 1]
```diff
@@ -425,6 +425,17 @@ function reverse(s::String)
     String(buf)
 end
 
+"""
+    repeat(s::String, r::Integer)
+
+Repeat a string `r` times.
```
Comment (tkelman) [inline base/strings/string.jl]: little odd that repeat is currently in the linalg doc index, maybe should be moved to more general collections section

Comment (stevengj) [inline base/strings/string.jl]: We could have it in both the linalg and string indices, with `AbstractArray` and `AbstractString` signatures.

Comment (stevengj) [inline base/strings/string.jl]: But I'm not sure why anyone would ever call `repeat` for a string rather than using `^`.

File: base/strings/string.jl [hunk 2]
```diff
@@ -438,3 +449,25 @@ function repeat(s::String, r::Integer)
     end
     return out
 end
+
+"""
+    repeat(c::Char, r::Integer) -> String
```
Comment (stevengj) [inline base/strings/string.jl]: Why don't we use Julia syntax `repeat(c::Char, r::Integer)::String` for this sort of thing?

File: base/strings/string.jl [hunk 3]
```diff
@@ -438,3 +449,25 @@ function repeat(s::String, r::Integer)
...
+Repeat a character `r` times.
+
+# Examples
+```jldoctest
+julia> repeat('A', 3)
+"AAA"
+```
+"""
+function repeat(c::Char, r::Integer)
+    r < 0 && throw(ArgumentError("can't repeat a character $r times"))
```
Comment (stevengj) [inline base/strings/string.jl]: Put the `r < 0` check inside the `isascii` check, since `repeat(string(c), r)` also does this check; otherwise you are doing the same check twice for non-ascii chars.

File: test/strings/basic.jl [hunk 4]
```diff
@@ -478,8 +478,8 @@ Base.endof(x::CharStr) = endof(x.chars)
 @test cmp(CharStr("\U1f596"), "\U1f596\U1f596") == -1
 
 # repeat function
-@test repeat("xx",3) == repeat("x",6) == "xxxxxx"
-@test repeat("αα",3) == repeat("α",6) == "αααααα"
+@test repeat("xx",3) == repeat("x",6) == repeat('x',6) == "xxxxxx"
+@test repeat("αα",3) == repeat("α",6) == repeat('α',6) == "αααααα"
```
Comment (stevengj) [inline test/strings/basic.jl]: I would also add a regression test for `^` to make `'x'^0 == ""` and `'x'^1 == "x"`.

File: base/strings/string.jl (hunk 2 above)
Comment (musm) [inline base/strings/string.jl]: Agreed, that change should however be made or brought up in another PR/issue.

File: base/strings/string.jl (hunk 1 above)
Comment (musm) [inline base/strings/string.jl]: Where is the doc index? Is there anything to do here with the signature?

Comment (musm) [inline base/strings/string.jl]: Updated PR please check if this now looks good.

File: base/strings/types.jl [hunk 5]
```diff
@@ -160,9 +160,9 @@ function repeat(s::AbstractString, r::Integer)
 end
 
 """
-    ^(s::AbstractString, n::Integer)
+    ^(s::Union{AbstractString,Char}, n::Integer)
 
-Repeat `n` times the string `s`.
+Repeat `n` times the string or character `s`.
```
Comment (fredrikekre) [inline base/strings/types.jl]: Almost reads like "repeat n * string". Perhaps:
``Repeat the string or character `s` `n` times.``

**Comment by musm** [comment]
Interestingly the performance characteristics of `repeat` on master have changed substantially than from `0.6`.

File: test/strings/basic.jl (hunk 4 above)
Comment (musm) [inline test/strings/basic.jl]: Thanks done.

File: base/strings/string.jl (hunk 1 above)
Comment (tkelman) [inline base/strings/string.jl]: the multiple docstrings would need to be distinguished by signature otherwise they will all be repeated in both sections

Comment (musm) [inline base/strings/string.jl]: @tkelman thanks will update. This means I should include:
```julia
Base.repeat(::String, r::Integer)
Base.repeat(::Char, r::Integer)
```

Actually should we not add the following fallback method ?
```julia
repeat(s::AbstractString, r::Integer) = repeat(string(s), r)
```

File: test/strings/basic.jl [hunk 6]
```diff
@@ -478,8 +478,12 @@ Base.endof(x::CharStr) = endof(x.chars)
...
+@test repeat("x",1) == repeat('x',1) == "x"
+@test repeat("x",0) == repeat('x',0) == ""
+@test "x"^1 == 'x'^1 == "x"
+@test "x"^0 == 'x'^0 == ""
```
Comment (stevengj) [inline test/strings/basic.jl]: Probably merge these two tests with the previous lines, e.g. `@test "x"^1 == 'x'^1 == repeat("x",1) == repeat('x',1) == "x"`

**Comment by musm** [comment]
Updated to also test  `AbstractString`  subtypes

File: base/strings/string.jl (hunk 2 above)
Comment (musm) [inline base/strings/string.jl]: I couldn't find an open issue on this, so I filed one here https://github.com/JuliaLang/julia/issues/22804

File: base/strings/types.jl [hunk 7]
```diff
@@ -152,6 +152,17 @@ reverseind(s::RevString, i::Integer) = endof(s) - i + 1
 reverseind(s::SubString{String}, i::Integer) =
     reverseind(s.string, nextind(s.string, endof(s.string))-s.offset-s.endof+i-1) - s.offset
 
+"""
+    repeat(s::AbstractString, r::Integer)
+
+Repeat a string `r` times.
```
Comment (stevengj) [inline base/strings/types.jl]: Probably the docstring should also cross-reference `^`; similarly for `Char`.

File: base/strings/string.jl (hunk 1 above)
Comment (tkelman) [inline base/strings/string.jl]: well those two docstrings would probably be fine to list together since they're closely related - it's the array one that should be in a different section

**Comment by musm** [comment]
@tkelman and @stevengj  I have addressed your reviews

(please, don't forget to squash merge)

File: base/strings/types.jl [hunk 8]
```diff
@@ -155,7 +155,7 @@ reverseind(s::SubString{String}, i::Integer) =
 """
     repeat(s::AbstractString, r::Integer)
 
-Repeat a string `r` times.
+Repeat a string `r` times. This can equivalently be accomplished by calling [`^`](@ref).
```
Comment (stevengj) [inline base/strings/types.jl]: Would be clearer to write:
```
by calling [`s^r`](@ref ^).
```
Ideally, we should cross-reference `^(::AbstractString, ::Integer)` ... @MichaelHatherly, does `@ref ^(::AbstractString, ::Integer)` work in Documenter?

Comment (musm) [inline base/strings/types.jl]: Thanks, fixed.

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
(Travis failure is #17626.)

**Comment by musm** [comment]
I think there is a bug in the implentation here
e.g. try this on `$` , which spits

`"\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$"`

**Comment by TotalVerb** [comment]
@musm That's because `$` must be escaped within double quotes.

**Comment by musm** [comment]
@TotalVerb  oh right, thanks!

I added a new commit which removed the `GenericString` test by accident, I dropped the commit.

**Comment by KristofferC** [comment]
Good to go then?

**Comment by musm** [comment]
yes
