### PR TITLE
Lookup metadata for inlined frames for stack traces

### LINKED ISSUE #41031: Metadata missing from inlined frames in backtraces
Having the parent Module and other method metadata available for each frame in a backtrace is quite useful for pretty printing, but we're currently missing it for inlined frames. For example:

```julia
julia> bar() = backtrace()
julia> foo() = bar()

julia> st = stacktrace(foo())
15-element Vector{Base.StackTraces.StackFrame}:
 bar at REPL[10]:1 [inlined]
 foo() at REPL[11]:1
 top-level scope at REPL[13]:1
...
```

For the `foo` frame, the `linfo` field contains the `MethodInstance` which in turn can be traced back to the `Method` using `st[2].linfo.def` to get the `Module` or other desired metadata. However, for the `bar` frame we just get `nothing` here.

```julia
julia> dump(st[1])
Base.StackTraces.StackFrame
  func: Symbol bar
  file: Symbol ./REPL[10]
  line: Int64 1
  linfo: Nothing nothing
  from_c: Bool false
  inlined: Bool true
  pointer: UInt64 0x00007f832223b37c

julia> dump(st[2])
Base.StackTraces.StackFrame
  func: Symbol foo
  file: Symbol ./REPL[11]
  line: Int64 1
  linfo: Core.MethodInstance
    def: Method
      name: Symbol foo
      module: Module Main
      file: Symbol REPL[11]
      line: Int32 1
    [.....]
  from_c: Bool false
  inlined: Bool false
  pointer: UInt64 0x00007f832223b37c
```

A place to start looking is inside the lookup code at
https://github.com/JuliaLang/julia/blob/1a2285bb0537eb53d2d7cd2894f0276bfb9f3985/src/debuginfo.cpp#L542

As suggested there, we should have the MethodInstance (or a CodeInfo thunk for toplevel code... IIRC) for the parent non-inlined frame in `new_frames[n_frames-1]`. So if we made sure that contained sufficient information about inlined methods we could fill in `linfo` in some way from there.

See also https://github.com/JuliaLang/julia/issues/33065#issuecomment-582824628

### PR DESCRIPTION
**Pull request by BioTurboNick**
Partially resolves #41031 

~~This PR implements a lookup for information about an inlined stack frame from the parent frame's cached, inferred CodeInfo.~~

~~Currently, this lookup fails if a parent frame's code has not been inferred. This merely results in the status quo for those frames.~~

~~I was giving a best guess about populating the MethodInstance and Method fields necessary to make things work. I also stumbled into what might be a nicer display for the inlined methods as well, if the arguments information can't be populated. (Though note how the top frame shows the aforementioned issue:~~

~~New approach (10/16/21) to avoid freaking out the GC: LineInfoNodes for inlined frames stored directly in the MethodInstance (via new field `inlined`) for the parent method after the inlining compiler pass. `jl_frame_t->linfo` is now a union that either holds a MethodInstance (`linfo->mi`), or Module (`linfo->module`), modeled after the `def` union in MethodInstance. When the stack frame lookup occurs in `lookup_pointer`, the inlined frames are matched with the LineInfoNodes from the parent frame, and the module is stored in `jl_frame_t->linfo.module`. The stack frame printing code has been adjusted to match.~~

Approach as of 5/19/22: Storing MethodInstance reference in the LineInfoNode instead of just the method name, then doing a multi-stage lookup when generating stack traces, that first tries to find the specific MethodInstance; if that fails, uses the Method; if that fails, uses the Module. This allows inlined stack frames to present more detailed information.

```
a() = k
@noinline b() = a()
c() = b()
d() = c()
e() = d()
e()
```

Current:
image

This PR:
image

Also added documentation to clarify that `inferred` in a `jl_code_instance_t` may contain a `jl_array_t`.

### CODE REVIEW

**Comment by BioTurboNick** [comment]
Although I have apparently violated the GC's correctness guarantees...

**Comment by BioTurboNick** [comment]
Closing because this isn't the right approach.

**Comment by BioTurboNick** [comment]
Reopening because I have a different approach that might be okay, need to run CI to check.

**Comment by BioTurboNick** [comment]
> @BioTurboNick you want the method right? Not the precise method instance? Then storing the signature (and not `atypes`) should suffice, cc: @aviatesk

Other stack frames display the specialized types, so it wouldn't be consistent, though it would be easier.

**Comment by BioTurboNick** [comment]
Tada!

```
a(x) = l
@noinline b(x) = a(x)
c(x) = b(x)
d(x) = c(x)
d(4)
d(4.0)
```

image

**Comment by BioTurboNick** [comment]
The current code works except for certain frames where the `inferred` field of the uncompressed CodeInfo is `nothing`, so the linetable cannot be looked up.

An example of this case is seen when running `@btime not_defined_var`, e.g. `#run_result#38` and `#invokelatest#2`.

The parent MethodInstance for these two inlined frames is `MethodInstance for BenchmarkTools.var"#run#42"(::Nothing, ::Float64, ::Float64, ::Base.Pairs{Symbol, Integer, NTuple{5, Symbol}, NamedTuple{(:verbose, :samples, :evals, :gctrial, :gcsample), Tuple{Bool, Int64, Int64, Bool, Bool}}}, ::typeof(run), ::BenchmarkTools.Benchmark, ::BenchmarkTools.Parameters)`

This issue could be resolved by, in these rare cases, relying on one of the other approaches I used. But before I try that, is there another place that a linetable could be found?

**Review by timholy — COMMENTED** [review]
This looks a lot like what I was imagining. Very impressive work!

What's the effect of this implementation on sysimg size? My only other major concern is the serialization issue I alluded to earlier, that's something else we should be sure folks are OK with before merging this.

**Comment by BioTurboNick** [comment]
Just rebased this to the current master.

Wondering if there's anything blocking this? Or if there are parallel efforts that would render this unnecessary. Also curious about my question re: the benefit of removing cached inferred code?

File: base/compiler/ssair/inlining.jl [hunk 1]
```diff
@@ -306,6 +306,19 @@ function finish_cfg_inline!(state::CFGInliningState)
     end
 end
 
+@noinline function method_name(m)
+    m = m isa LineInfoNode ? m.method : m
+    m = m isa MethodInstance ? m.def : m
+    m = m isa Method ? m.name : m
+    m = m isa Symbol ? m : Symbol("")
+    return m
+end
```
Comment (BioTurboNick) [inline base/compiler/ssair/inlining.jl:315]: At the moment, I don't recall why I have both this and the Base.StackTraces version.

**Comment by ToucheSir** [comment]
I know there has been much fanfare around getting terser stack traces, but this is just as big a QoL feature when troubleshooting library code (especially for library code Debugger.jl and Cthulhu can't handle). Just an anecdote for a use case that is more pressing than the original pretty printing one in #41031. If anyone wants a live demo, just find any Zygote stacktrace ;)

**Comment by BioTurboNick** [comment]
Hmm... not sure what's going on with the test failures. I'm sure there's some subtle interaction between my attempt to store MethodInstance info and this failure.

Worse comes to worse, could drop that part of this PR and focus just on the lookup-fallback code.

**Comment by BioTurboNick** [comment]
Alright, for the moment I'm stripping out my attempt to store additional MethodInstance information. I'll just stick with the fallbacks for Method lookup.

Unfortunately, that only provides the Module for stack traces and not types... I should check because I thought it would at least find the Method info.

**Comment by BioTurboNick** [comment]
...crap somehow I had reset to the wrong commit on a different branch and had erased the work. Luckily I preserved it as a separate branch before continuing. Recovering.

**Comment by BioTurboNick** [comment]
Turns out I couldn't separate any parts; everything is now restored and slightly better.

**Review by vchuravy — APPROVED** [review]
This looks reasonable to me.

**Comment by vchuravy** [comment]
Can you squash the commits down a bit?

File: base/stacktraces.jl [hunk 2]
```diff
@@ -107,11 +188,26 @@ Base.@constprop :none function lookup(pointer::Ptr{Cvoid})
     infos = ccall(:jl_lookup_code_address, Any, (Ptr{Cvoid}, Cint), pointer, false)::Core.SimpleVector
     pointer = convert(UInt64, pointer)
     isempty(infos) && return [StackFrame(empty_sym, empty_sym, -1, nothing, true, false, pointer)] # this is equal to UNKNOWN
+    parent_linfo = infos[end][4]
+    inlinetable = get_inlinetable(parent_linfo)
+    miroots = inlinetable === nothing ? get_method_instance_roots(parent_linfo) : nothing # fallback if linetable missing
     res = Vector{StackFrame}(undef, length(infos))
-    for i in 1:length(infos)
+    for i ∈ reverse(1:length(infos))
```
[the remark this answers is not in the document]
Comment (BioTurboNick) [reply base/stacktraces.jl:195]: Out of curiosity, why use written-out `in` here?

[the remark this answers is not in the document]
Comment (vchuravy) [reply base/stacktraces.jl:195]: General Base doesn't use much unicode, and the general policy is to match the formatting of the code around.

**Comment by BioTurboNick** [comment]
Not sure what's causing this precompile test failure. 

```
Error in testset precompile:
--
  | Test Failed at /cache/build/default-amdci5-5/julialang/julia-master/julia-3dcfc9db48/share/julia/test/precompile.jl:1058
  | Expression: isempty(m.specializations)
  | Evaluated: isempty(svec(MethodInstance for Invoke0x030e7e97c2365aad.hnc(::Int64), nothing, nothing, nothing, nothing, nothing, nothing, nothing))
```

**Comment by BioTurboNick** [comment]
@vchuravy @aviatesk 

What do we think, is this PR ready?

**Comment by BioTurboNick** [comment]
Bump with all green

**Comment by vtjnash** [comment]
Sorry for just the post merge foodback, but what is the space and performance implications of this? If I understand correctly, code is more expensive now and more poorly stored in order to support a rare use case that people don't like anyways (that of printing types in backtraces)

**Comment by BioTurboNick** [comment]
- Having full method information available for each frame is useful even if some would prefer to omit or truncate them when printed by default. Stacktraces with inlined frames are emitted all the time, the use case is not rare.
- Size: https://github.com/JuliaLang/julia/pull/41099#issuecomment-950179148 Was +5 MB to the sysimg, but I haven't checked since then.
- Performance: If it has broader effects I couldn't say, but throwing exceptions are already expensive operations.

If someone there are inefficiencies to this approach, would be great if someone more familiar with the internals would identify them and suggest improvements.

**Comment by aviatesk** [comment]
Compared `./usr/lib/julia` size:

> On a152d116bf79f327cd4adaa8712d864db9c5602b (previous commit)
```
➜ ls -la ./usr/lib/julia                
total 886888
drwxr-xr-x    7 aviatesk  staff        224 Apr 27 12:21 .
drwxr-xr-x  281 aviatesk  staff       8992 Apr 27 12:18 ..
-rw-r--r--    1 aviatesk  staff   18380016 Apr 27 12:19 corecompiler.ji
-rw-r--r--    1 aviatesk  staff  189431616 Apr 27 12:21 sys-o.a
-rwxr-xr-x    1 aviatesk  staff  157043096 Apr 27 12:21 sys.dylib
drwxr-xr-x    3 aviatesk  staff         96 Apr  5 21:32 sys.dylib.dSYM
-rw-r--r--    1 aviatesk  staff   89224928 Apr 27 12:19 sys.ji
```

> On 2cd0149fc6034d8785b66a1e0e2cadf26c4d1ca3
```
➜ ls -la ./usr/lib/julia
total 910544
drwxr-xr-x    7 aviatesk  staff        224 Apr 27 12:21 .
drwxr-xr-x  281 aviatesk  staff       8992 Apr 27 12:17 ..
-rw-r--r--    1 aviatesk  staff   18846536 Apr 27 12:19 corecompiler.ji
-rw-r--r--    1 aviatesk  staff  194243560 Apr 27 12:21 sys-o.a
-rwxr-xr-x    1 aviatesk  staff  161871528 Apr 27 12:21 sys.dylib
drwxr-xr-x    3 aviatesk  staff         96 Apr 14 19:20 sys.dylib.dSYM
-rw-r--r--    1 aviatesk  staff   91228312 Apr 27 12:19 sys.ji
```

**Comment by aviatesk** [comment]
Performance benchmark is running at:
https://github.com/JuliaLang/julia/commit/2cd0149fc6034d8785b66a1e0e2cadf26c4d1ca3#commitcomment-110772131

We might want to consider reverting this PR and preparing a new one that asserts the cost performance of the current PR and includes test cases that demonstrate the benefits of this improvement. It's rare for inlined frames to be involved in stack traces since we usually don't inline erroneous method calls.

**Comment by BioTurboNick** [comment]
> It's rare for inlined frames to be involved in stack traces since we usually don't inline erroneous method calls.

Can you clarify? I see inlined frames in many stacktraces. E.g. `sum([])`

**Comment by aviatesk** [comment]
My reasoning is that method errors are usually caused by dynamic dispatch, which often results in the inlining cost for the parent frame being too high for it to be inlined. As a result, we typically see type information for frames that are close to where the error occurs:
```
Stacktrace:
  [1] zero(#unused#::Type{Any})
    @ Base ./missing.jl:106
  [2] reduce_empty(#unused#::typeof(+), #unused#::Type{Any})
    @ Base ./reduce.jl:338
  [3] reduce_empty(#unused#::typeof(Base.add_sum), #unused#::Type{Any})
    @ Base ./reduce.jl:347
  [4] mapreduce_empty(#unused#::typeof(identity), op::Function, T::Type)
    @ Base ./reduce.jl:367
  [5] reduce_empty(op::Base.MappingRF{typeof(identity), typeof(Base.add_sum)}, #unused#::Type{Any})
    @ Base ./reduce.jl:356
  [6] reduce_empty_iter
    @ ./reduce.jl:379 [inlined]
  [7] mapreduce_empty_iter(f::Function, op::Function, itr::Vector{Any}, ItrEltype::Base.HasEltype)
    @ Base ./reduce.jl:375
  [8] _mapreduce(f::typeof(identity), op::typeof(Base.add_sum), #unused#::IndexLinear, A::Vector{Any})
    @ Base ./reduce.jl:427
  [9] _mapreduce_dim
    @ ./reducedim.jl:365 [inlined]
 [10] #mapreduce#800
    @ ./reducedim.jl:357 [inlined]
 [11] mapreduce
    @ ./reducedim.jl:357 [inlined]
 [12] #_sum#810
    @ ./reducedim.jl:999 [inlined]
 [13] _sum
    @ ./reducedim.jl:999 [inlined]
 [14] #_sum#809
    @ ./reducedim.jl:998 [inlined]
 [15] _sum
    @ ./reducedim.jl:998 [inlined]
 [16] #sum#807
    @ ./reducedim.jl:994 [inlined]
 [17] sum(a::Vector{Any})
    @ Base ./reducedim.jl:994
 [18] top-level scope
    @ REPL[11]:1
```

The other frames might indeed be inlined, so you are right, it might be an overstatement to say  "it's rare to be involved". But I'm still wondering if the type information for those frames are really valuable enough to justify the performance cost associated with it.

**Comment by vtjnash** [comment]
When inlined, you also know that Cthulhu will always recover that type information as well, so this is likely unnecessary to store for the user experience

**Comment by vchuravy** [comment]
> When inlined, you also know that Cthulhu will always recover that type information as well, so this is likely unnecessary to store for the user experience

Most people do not (and arguably should not) use Cthulhu. Giving more precision in the inlined stack traces is useful from a general usability perspective.

Julia often and deeply inlines code and I for one have been frustrated by the stacktraces more than once. 
(Partially why I wrote Cthulhu in the first place, we couldn't answer the question "How did we get there" without a dedicated tool). So the existence of Cthulhu is not an argument for the previous state, but an indictment thereof.

**Comment by BioTurboNick** [comment]
sys data: +2.07 MB
isbits data: +1.90 MB
symbols: +237 B
tags list: +2.09 kB
reloc list: +280 kB
gvar list: +120 B
fptr list: +344 B

I'm guessing most of that is from storing MethodInstances of inlined functions in the line table entries?

There are two places where a MethodInstance is placed in a LineInfoNode - `typeinf_ext` (previously was method name) and `ir_inline_linetable!` (previously was method def). Perhaps one of those is unnecessary?

Perhaps there's some point where it could be determined that MethodInstances aren't needed for some entries and could be stripped back out?

How did you generate those numbers, so I could check myself?

**Comment by vtjnash** [comment]
This is a [SnoopCompile](https://github.com/timholy/PkgCacheInspector.jl) feature

File: base/stacktraces.jl [hunk 3]
```diff
@@ -95,6 +96,82 @@ function hash(frame::StackFrame, h::UInt)
...
+normalize_method_name(m::Method) = m.name
+normalize_method_name(m::MethodInstance) = (m.def::Method).name
+normalize_method_name(m::Symbol) = m
+normalize_method_name(::Any) = Symbol("")
+@noinline method_name(m::LineInfoNode) = normalize_method_name(m.method)
+
+get_inlinetable(::Any) = nothing
+function get_inlinetable(mi::MethodInstance)
+    mi.def isa Method && mi.cache.inferred !== nothing || return nothing
+    linetable = ccall(:jl_uncompress_ir, Any, (Any, Any, Any), mi.def, mi.cache, mi.cache.inferred).linetable
```
[the remark this answers is not in the document]
Comment (vtjnash) [reply base/stacktraces.jl:103]: The runtime usually tries hard to *not* preserve the information you expect to be here (with an exception made that it is preserved only in the system image). The `cache` is only intended to be a list of all possible native code targets, without reliable debuginfo, but here you inspect only the first one while expecting it to be guaranteed to contain the correct debug tables.

[the remark this answers is not in the document]
Comment (BioTurboNick) [reply base/stacktraces.jl:103]: Can you clarify what you mean by reliable/correct?

In this code, if two possible MethodInstances are found, it falls back on the Method; am I missing another place where it finds just the first when there may be others?

**Comment by BioTurboNick** [comment]
> This is a [PkgCacheInspector](https://github.com/timholy/PkgCacheInspector.jl) feature

I've poked around a bit and it's not clear how to use it for the sysimage, vs. packages?

**Comment by fonsp** [comment]
Nice work! 🎉

This PR broke a feature in Pluto.jl that iterates a backtrace. It might be nice to run nanosoldier on this PR to check other packages? (It would have caught our issue 🌝)

**Comment by BioTurboNick** [comment]
Thanks! And thanks for the heads-up @fonsp. So the issue is just that sometimes a `Module` appears where there previously was `Nothing`?

**Comment by pankgeorg** [comment]
> Thanks! And thanks for the heads-up @fonsp. So the issue is just that sometimes a `Module` appears where there previously was `Nothing`?

Yes, the types of `linfo` were extended from `Union{Nothing, Core.CodeInfo, Core.MethodInstance}` to `Union{Nothing, Core.CodeInfo, Core.MethodInstance, Method, Module}`

This is how we handle frames:

https://github.com/fonsp/Pluto.jl/blob/8edd75b1e76599ab0bf69f75e634d9762502e431/src/runner/PlutoRunner.jl#L1075-L1105

File: base/stacktraces.jl [hunk 4]
```diff
@@ -52,8 +52,9 @@ struct StackFrame # this type should be kept platform-agnostic so that profiles
     file::Symbol
     "the line number in the file containing the execution context"
     line::Int
-    "the MethodInstance or CodeInfo containing the execution context (if it could be found)"
-    linfo::Union{MethodInstance, CodeInfo, Nothing}
+    "the MethodInstance or CodeInfo containing the execution context (if it could be found), \
+     or Module (for macro expansions)"
+    linfo::Union{MethodInstance, Method, Module, CodeInfo, Nothing}
```
Comment (aviatesk) [inline base/stacktraces.jl:57]: Is it really necessary to allow `linfo::Module`? From what I can tell, this module information is never used or explicitly tested, so there's no need to store it here. I'm concerned that this heavy-union field definition complicates the code unnecessarily.

Comment (BioTurboNick) [reply base/stacktraces.jl:57]: It's possible it's out of date, but at least at one point it was needed to look up the module for `macro expansion` frame.

Comment (aviatesk) [reply base/stacktraces.jl:57]: We should have implemented test cases for these new features. Do you have any use case for that information? Otherwise we should clean that up.

Comment (BioTurboNick) [reply base/stacktraces.jl:57]: Ok. But I just described the use case. Is this causing a problem somewhere right now? Otherwise something to look at when the underlying problem #50204 is resolved someway and the full functionality can be restored here.
