### PR TITLE
Group import hints

### LINKED ISSUE #53000: Group import hint by bindings
We have the following:
```
julia> solve(ODEProblem(sys, [1.], (0., 1e-2)), Rosenbrock23())
ERROR: UndefVarError: `solve` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in SciMLBase.
Hint: a global variable of this name also exists in DiffEqBase.
Hint: a global variable of this name also exists in JumpProcesses.
Hint: a global variable of this name also exists in AbstractAlgebra.
Hint: a global variable of this name also exists in LinearSolve.
Hint: a global variable of this name also exists in SimpleNonlinearSolve.
Hint: a global variable of this name also exists in NonlinearSolve.
Hint: a global variable of this name also exists in OrdinaryDiffEq.
Hint: a global variable of this name also exists in Sundials.
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1
```

This is already quite helpful, but I think it would be better if these were grouped for cases where packages export another package's bindings. For example, I think this could be:

```
Hint: a global variable of this name also exists in SciMLBase.
          - Also re-exported by DiffEqBase
          - Also re-exported by JumpProcesses
          ...
Hint: a global variable of this name also exists in AbstractAlgebra.
```
To make it clear that there are in fact two different solve methods, which package is the canonical source (SciMLBase) and which packages have convenience re-exports if you usually use the method through some other package.

### PR DESCRIPTION
**Pull request by ajwheeler**
This is my attempt to resolve #53000.

```
julia> solve
ERROR: UndefVarError: `solve` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in CommonSolve.
    - Also exported by SciMLBase.
    - Also exported by DiffEqBase.
    - Also exported by JumpProcesses.
    - Also exported by LinearSolve.
    - Also exported by BracketingNonlinearSolve (loaded but not imported in Main).
    - Also exported by SimpleNonlinearSolve.
    - Also exported by NonlinearSolve.
    - Also exported by OrdinaryDiffEqLowStorageRK (loaded but not imported in Main).
    - Also exported by OrdinaryDiffEqSSPRK (loaded but not imported in Main).
    - Also exported by OrdinaryDiffEqVerner (loaded but not imported in Main).
    - Also exported by OrdinaryDiffEqBDF (loaded but not imported in Main).
    - Also exported by OrdinaryDiffEqTsit5 (loaded but not imported in Main).
    - Also exported by OrdinaryDiffEqRosenbrock (loaded but not imported in Main).
    - Also exported by OrdinaryDiffEqDefault (loaded but not imported in Main).
    - Also exported by Sundials.
```

I would have beefed up the test case, but can't follow how it works.

### CODE REVIEW

File: stdlib/REPL/src/REPL.jl [hunk 1]
```diff
@@ -55,37 +55,67 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+        end
+        warned = true
+
+        # handle case where the undefined variable is the name of a loaded module
+        if Symbol(m) == var && !isdefined(active_mod, var)
+            print(io, "\nHint: $m is loaded but not imported in the active module $active_mod.")
+            continue
+        end
+
+        parent_m = parentmodule(getproperty(m, var))
```
Comment (Keno) [inline stdlib/REPL/src/REPL.jl:92]: This is the wrong query. You want `parent_m = binding_module(m, var)`.

**Comment by Keno** [comment]
Seems sensible overall, modulo comment.

**Comment by Keno** [comment]
Does need a test though.

File: stdlib/REPL/src/REPL.jl (hunk 1 above)
Comment (ajwheeler) [reply stdlib/REPL/src/REPL.jl]: Thanks. Fixed.

**Comment by ajwheeler** [comment]
In thinking about how to test this, I've come across what may be a problem.  If I do

```julia
module A
export f
f() = 0.0
end

module B
import ..A: f
export f
end

module C
import ..B: f
public f
end

module D
public f
f() = 1.0
end

append!(Base.loaded_modules_order, [A, B, C, D]) # is there a less gross way?
import .B
```

Then the hints for `julia> f` look like this
```
ERROR: UndefVarError: `f` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in Main.A.
    - Also exported by Main.B (loaded but not imported in Main).
    - Also made available as public by Main.C (loaded but not imported in Main).
Hint: a global variable of this name also exists in Main.D.
```

The problem here is that (unlike `C`), `B` _is_ imported. 

The same thing happens with 1.11.
<details> <summary> hints on 1.11 </summary>

```
julia> f
ERROR: UndefVarError: `f` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name may be made accessible by importing Main.A in the current active module Main
Hint: a global variable of this name may be made accessible by importing Main.B in the current active module Main
Hint: a global variable of this name may be made accessible by importing Main.C in the current active module Main
Hint: a global variable of this name may be made accessible by importing Main.D in the current active module Main
```

</details>

I think the problem arises from calling `Symbol(m)`, where `m` is a `Module`, but I might be confused.

I would welcome input here about whether or not this is out of scope for this PR, and whether there is a better way to test this.

**Comment by ararslan** [comment]
> I think the problem arises from calling `Symbol(m)`, where `m` is a `Module`, but I might be confused.

I haven't looked closely enough to determine whether `Symbol(m)` is the problem but if you suspect it is then you could try `nameof(m)` instead. (However, note that `nameof` here isn't fully equivalent; consider e.g. `Symbol(Base.Broadcast)` vs. `nameof(Base.Broadcast)`. To get the same behavior, you'd need `Symbol(join(fullname(m), '.'))`.)

**Comment by ararslan** [comment]
By the way, GitHub says this is your first contribution to the Julia repo, so welcome, and excellent first PR!

File: stdlib/REPL/test/repl.jl [hunk 2]
```diff
@@ -1833,23 +1833,50 @@ fake_repl() do stdin_write, stdout_read, repl
...
-    # check the requirement to trigger the hint via `UndefVarError_hint`
-    @test !isdefined(Main, :remove_linenums!) && Base.ispublic(Base, :remove_linenums!)
-
     fake_repl() do stdin_write, stdout_read, repl
         backend = REPL.REPLBackend()
         repltask = @async REPL.run_repl(repl; backend)
-        write(stdin_write,
-              "remove_linenums!\n\"ZZZZZ\"\n")
+        write(stdin_write, """
+        module AAAA # can't clash with anything else (module A defined elsewhere)
```
Comment (ararslan) [inline stdlib/REPL/test/repl.jl:1844]: As a general FYI, one common way in Julia's tests to ensure uniqueness of identifiers is to include the associated issue or PR number included as part of the name. For example, since this module is defined for the purpose of testing a change made to address issue #53000, you could name this `A53000`, and similarly for the other modules here.

File: stdlib/REPL/test/repl.jl [hunk 3]
```diff
@@ -1833,23 +1833,50 @@ fake_repl() do stdin_write, stdout_read, repl
...
+            export f
+            f() = 0.0
+        end
+
+        module C_outer
+            import ..AAAA: f
```
Comment (ararslan) [inline stdlib/REPL/test/repl.jl:1850]: An additional important case to test is that of available but unresolved bindings, e.g.
```julia
julia> module AAAA
           export f
           f() = 0.0
       end
Main.AAAA

julia> module B
           using ..AAAA
           export g, f
           g(x) = 69x + 420
       end
Main.B

julia> Base.isbindingresolved(B, :f)
false

julia> isdefined(B, :f)  # note that `isdefined` forces binding resolution
true
```

Comment (ajwheeler) [reply stdlib/REPL/test/repl.jl:1850]: Interesting, thank you.  What is the best place to find docs on this?  Is getting the desired behavior just a matter of changing `Base.isbindingresolved` to `isdefined` in line 81?
```julia
        if !Base.isbindingresolved(m, var) || (!Base.isexported(m, var) && !Base.ispublic(m, var))
```

File: stdlib/REPL/test/repl.jl (hunk 2 above)
Comment (ajwheeler) [reply stdlib/REPL/test/repl.jl]: Thanks, I've done this.

File: stdlib/REPL/src/REPL.jl [hunk 4]
```diff
@@ -55,37 +55,67 @@ function UndefVarError_hint(io::IO, ex::UndefVarError)
...
+            print(io, "\nHint: a global variable of this name also exists in ", binding_m, ".")
+            for m in modules
+                m == binding_m && continue
+                how_available = if Base.isexported(m, var)
+                    "exported by"
+                elseif Base.ispublic(m, var)
+                    "made available as public by"
+                end
+                print(io, "\n    - Also $how_available $m")
+                if !isdefined(active_mod, nameof(m))
```
[the remark this answers is not in the document]
Comment (ajwheeler) [reply stdlib/REPL/src/REPL.jl]: I think I'm now handing this case correctly.

**Comment by ajwheeler** [comment]
Friendly post-holiday bump :)

I _think_ the failures here were also on master and that this is ready modulo additional review.

**Comment by ajwheeler** [comment]
Ping :) 

Are the failing tests here my fault or just flaky?

**Comment by vtjnash** [comment]
there was a merge conflict, so CI needs to re-run anyways, and I fixed an incorrect comment (this PR appears to suppress messages for modules where the binding exists but doesn't currently have a value assigned to them)
