### PR TITLE
fix overflow in `prevfloat` with unsigned stepcount

### LINKED ISSUE #59661: Underflow in `prevfloat` with `Unsigned` iteration count
`prevfloat` is implemented by calling `nextfloat` on the same value but with the iteration count negated:
`prevfloat(x::AbstractFloat, d::Integer) = nextfloat(x, -d)` [julia/base/float.jl#870](https://github.com/JuliaLang/julia/blob/4f1e471d54e93a79aee246bba100032ab3995a8c/base/float.jl#L870)
For `Unsigned` iteration counts, this causes underflow and returns unexpected results.

Examples:
```
prevfloat(1.0, 1)
# 0.9999999999999999        expected result
prevfloat(1.0, 0x01)
# 1.0000000000000566        == nextfloat(1.0, 0xff)
prevfloat(1.0, 0x00000001)
# 1.0000009536743162        == nextfloat(1.0, 0xffffffff)

```

### PR DESCRIPTION
**Pull request by adienes**
fixes https://github.com/JuliaLang/julia/issues/59661

### CODE REVIEW

**Comment by adienes** [comment]
I think the docs could stand an update, as applying a function `-n` times doesn't make much sense (although ofc most people will likely understand what it's intending to say)

instead of

> nextfloat(x::AbstractFloat, n::Integer)
> The result of `n` iterative applications of `nextfloat` to `x` if `n >= 0`, or `-n` applications of `prevfloat` if `n < 0`.

it should probably be something more like

> The result of `n` iterative applications of `nextfloat` to `x` if `n >= 0`, or if `n < 0`, return a value `p` such that `prevfloat(p, n) == x`

but I don't want to change the docs in this PR as that would likely invite stricter scrutiny

File: base/float.jl [hunk 1]
```diff
@@ -851,6 +844,15 @@ function nextfloat(f::IEEEFloat, d::Integer)
...
 end
 
+"""
+    nextfloat(x::AbstractFloat, n::Integer)
+
+The result of `n` iterative applications of `nextfloat` to `x` if `n >= 0`, or `-n`
+applications of [`prevfloat`](@ref) if `n < 0`.
+"""
+nextfloat(f::AbstractFloat, d::Integer) = _nextfloat(f, d < 0, uabs(d))
+nextfloat(f::IEEEFloat, d::Unsigned) = _nextfloat(f, false, d)
```
Comment (nsajko) [inline base/float.jl]: Seems not necessary to have an `Unsigned`-specific method.


```suggestion
```

File: base/float.jl [hunk 2]
```diff
@@ -851,6 +844,15 @@ function nextfloat(f::IEEEFloat, d::Integer)
     reinterpret(F, fu)
 end
 
+"""
+    nextfloat(x::AbstractFloat, n::Integer)
+
+The result of `n` iterative applications of `nextfloat` to `x` if `n >= 0`, or `-n`
+applications of [`prevfloat`](@ref) if `n < 0`.
+"""
+nextfloat(f::AbstractFloat, d::Integer) = _nextfloat(f, d < 0, uabs(d))
```
Comment (nsajko) [inline base/float.jl]: Why define a method for `AbstractFloat` which is just going to throw `MethodError` for non-`IEEEFloat`? Better just define it for `IEEEFloat`.

```suggestion
nextfloat(f::IEEEFloat, d::Integer) = _nextfloat(f, d < 0, uabs(d))
```

File: base/float.jl [hunk 3]
```diff
@@ -859,23 +861,23 @@ If no such `y` exists (e.g. if `x` is `Inf` or `NaN`), then return `x`.
...
+nextfloat(x::AbstractFloat) = nextfloat(x, 1)
 
 """
     prevfloat(x::AbstractFloat, n::Integer)
 
 The result of `n` iterative applications of `prevfloat` to `x` if `n >= 0`, or `-n`
 applications of [`nextfloat`](@ref) if `n < 0`.
 """
-prevfloat(x::AbstractFloat, d::Integer) = nextfloat(x, -d)
+prevfloat(x::AbstractFloat, d::Integer) = _nextfloat(x, d > 0, uabs(d))
```
Comment (nsajko) [inline base/float.jl]:
```suggestion
prevfloat(x::IEEEFloat, d::Integer) = _nextfloat(x, d > 0, uabs(d))
```

**Comment by nsajko** [comment]
This change could break `prevfloat` for a package which implements `nextfloat` and expects `prevfloat` to have a generic fall back implemented using `nextfloat`. So I think this may be a "minor change"?

**Comment by nsajko** [comment]
I guess you may want to use the new `ispositive` and `isnegative`, instead of `<`.

File: base/float.jl (hunk 1 above)
Comment (adienes) [reply base/float.jl]: relies on compiler to know `isnegative` and `uabs` for `Unsigned`, but I guess it should be able to do that

File: base/float.jl (hunk 2 above)
Comment (adienes) [reply base/float.jl]: note that the original PR also defined `function nextfloat(f::IEEEFloat, d::Integer)` and would MethodError on arguments not convertible to `IEEEFloat` so this is NFC in that respect. I actually think it's a little cleaner to separate the IEEEFloat implementation from the generic method.

**Comment by adienes** [comment]
> This change could break prevfloat for a package which implements nextfloat and expects prevfloat to have a generic fall back implemented using nextfloat

those packages were already broken as the existing fallback is incorrect

**Review by vtjnash — COMMENTED** [review]
LGTM

**Review by oscardssmith — APPROVED** [review]

**Comment by KristofferC** [comment]
This caused e.g. the following package to error:

```
Machine precision: Error During Test at /home/pkgeval/.julia/packages/Measurements/pivk0/test/runtests.jl:723
  Test threw exception
  Expression: ≈(prevfloat(y, 3), prevfloat(y.val, 3) ± y.err, rtol = 2.0e-16)
  MethodError: no method matching _nextfloat(::Measurement{Float64}, ::Bool, ::UInt64)
  The function `_nextfloat` exists, but no method is defined for this combination of argument types.
  
  Closest candidates are:
    _nextfloat(!Matched::Union{Float16, Float32, Float64}, ::Bool, ::Integer)
     @ Base float.jl:811
  
  Stacktrace:
   [1] prevfloat(x::Measurement{Float64}, d::Int64)
     @ Base ./float.jl:872
   [2] macro expansion
     @ /opt/julia/share/julia/stdlib/v1.12/Test/src/Test.jl:677 [inlined]
   [3] macro expansion
     @ ~/.julia/packages/Measurements/pivk0/test/runtests.jl:723 [inlined]
   [4] macro expansion
     @ /opt/julia/share/julia/stdlib/v1.12/Test/src/Test.jl:1776 [inlined]
   [5] top-level scope
     @ ~/.julia/packages/Measurements/pivk0/test/runtests.jl:718
Test Summary:     | Pass  Error  Total  Time
Machine precision |   14      1     15  3.2s
RNG of the outermost testset: Random.Xoshiro(0x0e3a33dd23d99956, 0x3f3eee0e33e3eedb, 0xb4c5a981cf374033, 0xb09260fd6f34e3d4, 0x27d3f47ed60be1b2)
ERROR: LoadError: Some tests did not pass: 14 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/pkgeval/.julia/packages/Measurements/pivk0/test/runtests.jl:716
```

Out of an abundance of caution I will drop this from 1.12 backport. It can be put back after analysis or if it gets fixed.

**Comment by adienes** [comment]
that seems to be due to this definition

```
Base.nextfloat(a::Measurement, n::Integer) = result(nextfloat(a.val, n), 1, a)
```

without a corresponding `prevfloat`, which is buggy. the bug was Base's fault, not the author's, but ultimately this is a "good" failure. fair to remove it from the backport though; this was status quo for like 10 years so I suppose another version doesn't really matter

**Comment by adienes** [comment]
https://github.com/JuliaLang/julia/pull/59836

File: base/float.jl [hunk 4]
```diff
@@ -859,23 +860,23 @@ If no such `y` exists (e.g. if `x` is `Inf` or `NaN`), then return `x`.
...
+nextfloat(x::AbstractFloat) = nextfloat(x, 1)
 
 """
     prevfloat(x::AbstractFloat, n::Integer)
 
 The result of `n` iterative applications of `prevfloat` to `x` if `n >= 0`, or `-n`
 applications of [`nextfloat`](@ref) if `n < 0`.
 """
-prevfloat(x::AbstractFloat, d::Integer) = nextfloat(x, -d)
+prevfloat(x::AbstractFloat, d::Integer) = _nextfloat(x, ispositive(d), uabs(d))
```
Comment (giordano) [inline base/float.jl:871]: Now packages defining custom `AbstractFloat` are expected to define a method for `Base._nextfloat`?

Comment (adienes) [reply base/float.jl:871]: no, they should define `prevfloat` separately and explicitly as the old fallback in `Base` was not correct, leading to behavior like
```
julia> prevfloat(Measurement{Float64}(1.0), 0x01)
1.0000000000000566 ± 0.0
```

Comment (adienes) [reply base/float.jl:871]: https://github.com/JuliaPhysics/Measurements.jl/pull/191
