### PR TITLE
cholesky factorization Hermitian non-real in diagonal

### LINKED ISSUE #765: Cholesky factorization fails for Hermitian matrices with imaginary parts in the diagonal of the parent
```julia
julia> B = Hermitian(hcat([one(BigFloat) + im]))
1×1 Hermitian{Complex{BigFloat},Matrix{Complex{BigFloat}}}:
 1.0 + 0.0im

julia> cholesky(B)
ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.
Stacktrace:
 [1] checkpositivedefinite
   @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\factorization.jl:18 [inlined]
 [2] cholesky!(A::Hermitian{Complex{BigFloat},Matrix{Complex{BigFloat}}}, ::Val{false}; check::Bool)
   @ LinearAlgebra D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:219
 [3] cholesky(A::Hermitian{Complex{BigFloat},Matrix{Complex{BigFloat}}}, ::Val{false}; check::Bool)
   @ LinearAlgebra D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:344
 [4] cholesky
   @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:344 [inlined]
 [5] top-level scope
   @ REPL[118]:1
```

### LINKED ISSUE #37356: Cholesky factorization fails for Hermitian matrices with imaginary parts in the diagonal of the parent
```julia
julia> B = Hermitian(hcat([one(BigFloat) + im]))
1×1 Hermitian{Complex{BigFloat},Matrix{Complex{BigFloat}}}:
 1.0 + 0.0im

julia> cholesky(B)
ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.
Stacktrace:
 [1] checkpositivedefinite
   @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\factorization.jl:18 [inlined]
 [2] cholesky!(A::Hermitian{Complex{BigFloat},Matrix{Complex{BigFloat}}}, ::Val{false}; check::Bool)
   @ LinearAlgebra D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:219
 [3] cholesky(A::Hermitian{Complex{BigFloat},Matrix{Complex{BigFloat}}}, ::Val{false}; check::Bool)
   @ LinearAlgebra D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:344
 [4] cholesky
   @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:344 [inlined]
 [5] top-level scope
   @ REPL[118]:1
```

### PR DESCRIPTION
**Pull request by KlausC**
Fixes JuliaLang/LinearAlgebra.jl#765

In case a complex entry is stored in the parent matrix of an Hermitian, consider only the real part when doing Cholesky factorisation.
After change in the generic implementation now in line with LAPACK.

### CODE REVIEW

File: stdlib/LinearAlgebra/src/cholesky.jl [hunk 1]
```diff
@@ -155,10 +155,14 @@ function _chol!(A::AbstractMatrix, ::Type{UpperTriangular})
     n = checksquare(A)
     @inbounds begin
         for k = 1:n
+            Akk = A[k,k]
+            if Akk isa Complex && Akk != Akk'
+                Akk = real(Akk)
+            end
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/cholesky.jl:161]: This is not type-stable (`Akk` can change type).  Better to just write:
```jl
Akk = real(A[k,k])
```
In the case of real elements, the `real` function is the identity and will be optimized out, and just taking the real part will be faster than checking `Akk != Akk'` in the complex case anyway.

File: stdlib/LinearAlgebra/src/cholesky.jl [hunk 2]
```diff
@@ -155,10 +155,14 @@ function _chol!(A::AbstractMatrix, ::Type{UpperTriangular})
...
             for i = 1:k - 1
-                A[k,k] -= A[i,k]'A[i,k]
+                Akk -= A[i,k]'A[i,k]
             end
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/cholesky.jl:164]: To be equivalent to the old code, it should set
```jl
A[k,k] = Akk
```
at the end, so that the final `A` has the same values along the diagonal as in previous Julia versions.

File: stdlib/LinearAlgebra/src/cholesky.jl [hunk 3]
```diff
@@ -179,10 +183,14 @@ function _chol!(A::AbstractMatrix, ::Type{LowerTriangular})
     n = checksquare(A)
     @inbounds begin
         for k = 1:n
+            Akk = A[k,k]
+            if Akk isa Complex && Akk != Akk'
+                Akk = real(Akk)
+            end
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/cholesky.jl:189]: Same comments as above.

File: stdlib/LinearAlgebra/src/cholesky.jl (hunk 1 above)
Comment (KlausC) [reply stdlib/LinearAlgebra/src/cholesky.jl:161]: I agree with respect to `Akk != Akk´` and will remove this check.
The `Akk isa Complex` is necessary, because the element type of `A` is not restricted to `Number`s, but can be for example an `AbstractArray` or some other type, which does not have the `real` method.

File: stdlib/LinearAlgebra/src/cholesky.jl (hunk 2 above)
Comment (KlausC) [reply stdlib/LinearAlgebra/src/cholesky.jl:164]: You are right, that would change the output in case of an error return - will change that.

**Comment by KlausC** [comment]
My naive attempt to rebase on the current master branch added some unexpected commits. If you think it is worth while, I can close this PR and restart a new one, which contains only the changes in (src/test)/cholesky.jl, which I intended.

File: stdlib/LinearAlgebra/src/cholesky.jl (hunk 1 above)
Comment (stevengj) [reply stdlib/LinearAlgebra/src/cholesky.jl]: You can use
```
Akk = eltype(A) <: Number ? real(A[k,k]) : A[k,k]
```
I guess.

File: stdlib/LinearAlgebra/src/cholesky.jl [hunk 4]
```diff
@@ -153,12 +181,15 @@ end
...
     @inbounds begin
         for k = 1:n
+            Akk = realdiag ? real(A[k,k]) : A[k,k]
             for i = 1:k - 1
-                A[k,k] -= A[i,k]'A[i,k]
+                Akk -= realdiag ? abs2(A[i,k]) : A[i,k]'A[i,k]
             end
-            Akk, info = _chol!(A[k,k], UpperTriangular)
+            A[k,k] = Akk
+            Akk, info = _chol!(Akk, UpperTriangular)
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/cholesky.jl:192]: Shouldn't these two lines be swapped to ensure that it is the same as the old code, which mutates `A[k,k]` to the *final* value of `Akk`?

File: src/julia_internal.h [hunk 5]
```diff
@@ -1187,6 +1187,14 @@ struct typemap_intersection_env {
 };
 int jl_typemap_intersection_visitor(jl_typemap_t *a, int offs, struct typemap_intersection_env *closure);
 
+// -- simplevector.c -- //
+
+// For codegen only.
+JL_DLLEXPORT size_t (jl_svec_len)(jl_svec_t *t) JL_NOTSAFEPOINT;
+JL_DLLEXPORT int8_t jl_svec_isassigned(jl_svec_t *t JL_PROPAGATES_ROOT, ssize_t i) JL_NOTSAFEPOINT;
+JL_DLLEXPORT jl_value_t *jl_svec_ref(jl_svec_t *t JL_PROPAGATES_ROOT, ssize_t i);
```
Comment (stevengj) [inline src/julia_internal.h:1195]: Why are these changes in this PR?  Did a rebase/merge go wrong?

**Comment by stevengj** [comment]
Looks like you messed up a rebase/merge and got a whole bunch of unrelated commits into this branch.

You'll probably want to create a new branch on your machine off of `master`, cherry-pick your commits from this branch, and force push.

File: src/julia_internal.h (hunk 5 above)
Comment (KlausC) [reply src/julia_internal.h]: after cleaning up my local repo, `git push --set-upstream origin krc/cholesky` did the job. This PR has now only the final commit.

**Review by stevengj — APPROVED** [review]

**Comment by lkapelevich** [comment]
Is anything else needed to merge this?

**Comment by KlausC** [comment]
Not as far as I can 

> Is anything else needed to merge this?

Not from my side.

**Comment by KlausC** [comment]
> Is anything else needed to merge this?

Not from my side.
