### PR TITLE
gf: support more dispatch on abstract types

### LINKED ISSUE #14919: v0.5 "cannot add methods to an abstract type" when overriding call
I'm updating ApproxFun and this caught me by surprise:

``` julia
abstract Foo
julia> (f::Foo)(x)=x
ERROR: cannot add methods to an abstract type
 in eval(::Module, ::Any) at ./boot.jl:267
```

Is this intentional?  Is there a way to get around this other than define for each subtype:

``` julia
julia> immutable CFoo <: Foo end
julia> (f::CFoo)(x)=x
```

### PR DESCRIPTION
**Pull request by vtjnash**
This removes the restriction on defining dispatch over user-defined abstract types. This fixes #14919 for 99% of cases.
```julia
abstract type A14919; end
struct B14919 <: A14919; end
struct C14919 <: A14919; end
struct D14919 <: Function; end
(::A14919)() = "It's a brand new world"
(::Union{C14919,D14919})() = "Boo."
@test B14919()() == "It's a brand new world"
@test C14919()() == D14919()() == "Boo."
```

The "cannot add methods to an abstract type" error is now only applicable to a couple types (`Any`, `Function`, and functions), and instead now gives a "not implemented yet" message (that's perhaps not entirely right, since in several instances of this, I think they would be ambiguous with calling a Builtin function—and we don't need to ever enable that particular foot-gun).

This PR actually hilariously similar to my branch https://github.com/JuliaLang/julia/issues/14919#issuecomment-221631911 from 3 years ago, but adds a few more error checks so that performance is unaffected.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I think not being able to define methods for `Any` is definitely a feature :)

**Comment by JeffreySarnoff** [comment]
ya' know  the Community will be dancing while this becomes second nature 🌞

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by JeffBezanson** [comment]
This benchmark from #21760 goes from .034 sec to .042 sec on this branch:
```
struct f{t}
end
(::f{t})(x) where {t} = t
@time for i=1:1000; f{i}()(1); end
```

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31916#issuecomment-491335059) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1cd5cd9b758c90d1bbc6b67b86eb904d0cd0ec17/4513236_vs_5486cc2/report.md). cc @ararslan

**Comment by vtjnash** [comment]
@JeffBezanson I ran that code locally, and saw no performance difference. Probably just noise or a different random seed.

File: src/datatype.c [hunk 1]
```diff
@@ -471,23 +469,28 @@ JL_DLLEXPORT jl_datatype_t *jl_new_datatype(
...
-            tn = (jl_typename_t*)name;
+    t->name = NULL;
+    if (jl_is_typename(name)) {
+        // This code-path is used by the Serialization module to by-pass normal expectations
+        tn = (jl_typename_t*)name;
+    }
+    else {
+        tn = jl_new_typename_in((jl_sym_t*)name, module);
+        if (super == jl_function_type || super == jl_builtin_type || jl_symbol_name(name)[0] == '#') {
+            // Callable objects (including compiler-generated closures) get independent method tables
```
Comment (JeffBezanson) [inline src/datatype.c]: This will not catch the case of defining `struct Foo <: Function`, which is probably fine, just want to check that that's the intent.

File: src/dump.c [hunk 2]
```diff
@@ -205,6 +205,14 @@ static void write_float64(ios_t *s, double x) JL_NOTSAFEPOINT
     write_uint64(s, *((uint64_t*)&x));
 }
 
+//#ifdef _P64
+//#define write_ulong(s, x) (write_uint64((s), (x)))
+//#define read_ulong(s, x) (read_uint64((s), (x)))
+//#else
+//#define write_ulong(s, x) (write_uint32((s), (x)))
+//#define read_ulong(s, x) (read_uint32((s), (x)))
+//#endif
```
Comment (JeffBezanson) [inline src/dump.c]: Delete?

File: src/datatype.c (hunk 1 above)
Comment (vtjnash) [reply src/datatype.c]: Correct, that was my intention (it's even part of my examples at the top). Eventually the goal is probably just to merge all of the tables, but for now, I just merge the subset that I expect will be small.

**Comment by vchuravy** [comment]
Running into a segmentation fault that bisect blames on this, https://github.com/JuliaGPU/CUDAnative.jl/issues/407

**Comment by MasonProtter** [comment]
> The "cannot add methods to an abstract type" error is now only applicable to a couple types (Any, Function, and functions), and instead now gives a "not implemented yet" message (that's perhaps not entirely right, since in several instances of this, I think they would be ambiguous with calling a Builtin function—and we don't need to ever enable that particular foot-gun).

What if we were to allow this, but only in cases where a method error would be thrown? Ie. make `(::Function)(x::MyType) = ...` the lowest possible priority such that it always loses priority to standard definitions?

**Comment by caseykneale** [comment]
Awesome I've been waiting for this: https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/RegressionModels.jl

How can developers maintain backward compatibility with previous julia versions with the implementation of this(once its streamlined)? Maybe the correct solution is to tell users to use the latest version of julia.

**Comment by StefanKarpinski** [comment]
This is a language feature that cannot be implemented in a package, so the only option of one needs this is to use a newer Julia version.
