### PR TITLE
ccall: make distinction of pointer vs name a syntactic distinction

### LINKED ISSUE #57931: Clarify ccall evaluation semantics
This aims to summarize a design discussion between @vtjnash, @JeffBezanson, @StefanKarpinski,  @gbaraldi, @topolarity, @xal-0, @mlechu, @oscardssmith and myself around ccall. Except where otherwise annotated, I've tried to capture my understanding the consensus view, but it is of course possible that I have misunderstood or failed to remember in objection. In such cases, error is mine.

## Discussion of the problems and current design

The current evaluation semantics of `ccall` are quite old and predate us having a particular good understanding of what the evaluation semantics of the language should be (and in particular, predate any notion of world ages, partitioned bindings, effects, etc.). For this reason, it is somewhat hard to give a coherent description of the current design.
However, I will try my best.

### Syntax based disambiguation of (non-)library case

There are two basic cases for ccall. The first is call with a plain symbol or ptr:

```
ccall(sym, ...)
```

The second is

```
ccall((sym, lib), ...)
```

These cases are distinguished both syntactically a semantically. In particular,
```
x = sym
ccall(x)
```
is always the same as `ccall(sym)`, but the same is not true for `x = (sym, lib)`.

## Evaluation sematics of the first argument

We first consider the basic case without libraries. Here we are familiar
with the usual ccall syntax:

```
julia> ccall(:sin, Float64, (Float64,), 1.0)
0.8414709848078965
```

What happens if we use an expression instead?

```
julia> f1() = ccall((println("Hello"); :sin), Float64, (Float64,), 1.0)
0.8414709848078965

julia> f1()
Hello
0.8414709848078965

julia> f1()
Hello
0.8414709848078965
```

So far so normal. However, this is where it starts to get weird. I think the
best way I can describe it is that call tries to find a symbol in this order
by:

1. Statically looking at the expression that is syntactically inside `ccall` and
   determining whether or not it can figure out the value of the first argument.

2. Using inference's constant propagation

3. Using codegen's constant propagation (but not LLVM's)

However, for the non-lib case, the first of these is generally a no-op.

This leads to the following observed behavior:

```julia
f2() = ccall((@noinline identity(:sin)), Float64, (Float64,), 1.0)
f3() = ccall(Base.compilerbarrier(:const, :sin), Float64, (Float64,), 1.0)
f4() = ccall(Base.compilerbarrier(:const, (@noinline identity(:sin))), Float64, (Float64,), 1.0)
f5() = ccall((@noinline identity(Base.compilerbarrier(:const, :sin))), Float64, (Float64,), 1.0)
```

```julia-repl
julia> f2()
0.8414709848078965

julia> f3()
0.8414709848078965

julia> f4()
0.8414709848078965

julia> f5()
ERROR: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Symbol
Stacktrace:
 [1] f5()
   @ Main ./REPL[19]:1
 [2] top-level scope
   @ REPL[24]:1
```

To me, this is entirely unintuitive and I had to actually go read the source to figure out which cases I think would work and which didn't.

### Additional complications from lib lowering

The situation becomes more complicated when using the lib syntax:
```
julia> ccall(((println("Hello"); :sin), :openlibm), Float64, (Float64,), 1.0)
Internal error: encountered unexpected error during compilation of top-level scope:
ErrorException("unsupported or misplaced expression \"block\" in function top-level scope")
ijl_errorf at /home/keno/julia/src/rtutils.c:77
emit_expr at /home/keno/julia/src/codegen.cpp:6694

julia> function g1()
               x = (println("Hello"); :sin)
               ccall((x, :openlibm), Float64, (Float64,), 1.0)
       end
ERROR: syntax: ccall function name and library expression cannot reference local variables
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> function g2()
          x = ((println("Hello"); :sin), :libopenlibm)
          ccall(x, Float64, (Float64,), 1.0)
       end
g2 (generic function with 1 method)

julia> g2()
Hello
0.8414709848078965

julia> syms() = (println("Hello"); :sin)
syms (generic function with 1 method)

julia> ccall((syms(), :openlibm), Float64, (Float64,), 1.0)
Hello
ERROR: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Tuple{Symbol, Symbol}
Stacktrace:
 [1] top-level scope
   @ ./REPL[3]:1
```

### Additional complications from bindings partition

Post-bindings partition, there is an additional complication that both cases 1 and 3 depend on inferred world age bounds of the rest of the function, which can lead to completely non-intuitive behavior. This is #57749, although I will mention it here also:

```julia-repl
julia> const sinsym = :sin
:sin

julia> g3() = ccall((sinsym, :libopenlibm), Float64, (Float64,), 1.0)
f6 (generic function with 1 method)

julia> g3()
ERROR: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Tuple{Symbol, Symbol}
Stacktrace:
 [1] f6()
   @ Main ./REPL[15]:1
 [2] top-level scope
   @ REPL[16]:1

julia> const completely_unrelated = 2
2

julia> g4() = (completely_unrelated; ccall((sinsym, :libopenlibm), Float64, (Float64,), 1.0))
g4 (generic function with 1 method)

julia> g4()
0.8414709848078965
```

This is arguably a separate inference bug that should be addressed by properly modeling this in inference, but stems from the same underlying confusion around the evaluation semantics of the first argument of ccall.

### Hidden generic function call inside :foreigncall

This one might be a bit academic, but as of #50074, there is a hidden call to `Libdl.dlopen` inside :foreigncall. This dynamic call edge is not modeled and thus
susceptible to #265-like issues, invisible to trimming, etc. Now, there is already a non-standard caching here, but I wanted to list it for completeness.

### Implicit caching of dlsym

This one isn't so much a problem as it is an aspect of the current design that needs
to be preserved for performance. In particular, the codegen for `:foreigncall` currently looks something like (in pesudo C syntax)

```
static void *cache;
# Expr(:foreigncall, (lib, sym), ...)
{
	if (!_cache) {
		_cache = jl_lazy_load_and_lookup(lib, sym) # Potentially calls Libdl.dlopen internally
	}
	(*_cache)(...)
}
```

Plus some optimizations to fold away the lookup if it can be resolved statically by the JIT or to turn the lookup into a PLT-like structure.

## Additional desirable features

An additional desirable feature that was discussed was that in the context of `--trim`, we would like to have the ability to statically link executables without assuming the presence of a dynamic linker at runtime, ideally while preserving the namespace scoping behavior of the current design. This is a little tricky, because the underlying systme linker generally does not have namespacing. How exactly to do this is outside the scope of this document, but the key consideration is that this constrains us to require a solution that `juliac` might be able to turn the dynamic references into static ones.

## Proposed solutions

The first and most immediate question to answer is what the evaluation scope of the first argument of `ccall` is. I think there are roughly three reasonable answers:

1. It gets evaluated in toplevel scope at definition time, i.e. the following would error:
```
function foo()
	ccall(sym, ...)
end # Error: UndefinedVarError(:sym)
const sym = ...
```

2. It gets evaluated (with usual evaluation semantic) at the same time as the cache logic. I.e. we'd have the following:

```
foo() = ccall((println("Hello"); :sin), ...)

julia> foo()
Hello
0.8414709848078965

julia> foo() # Does not print the second time because the lookup is already cached
0.8414709848078965
```

3. The expression and dlsym lookup get evaluated everytime

4. The expresssion gets evaluated every time, but the `dlsym` lookup is cached the first time it gets evaluated (for a particular native code instance)

5. The expression gets evaluated every time, but the `dlsym` lookup is cached the first time it gets evaluated (for a particular native code instance) plus gets recached when the value of expression changes

### Discussion

Option 3 is the most straightforward behavior in that it is completely dynamic and does not rely on any compiler information. However, because of the lack of caching, it is also prohibitive. However, in general, I think everyone agreed that if it was fast, it would be a good semantic, which is a useful guiding principle for selecting which option to use.

Option 4 is somewhat reminiscent of what we have right now, except that we have extra requirements (i.e. the symbol name needs to be a constant expression). These requirements make the behavior of `ccall` very confusion, though to be fair, they also by default prohibit some problematic cases.

In particular, there's a question about non-constant cases like
```
julia> globalsin = :sin
julia> f() = ccall(globalsin, Float64, (Float64,), 1.0)
julia> f()
julia> globalsin = :cos
julia> f()
```

What should this do? Currently this case is disallowed due to the (semantically strange) constantness detection on the first argument. We do not have constantness detection anywhere else in the language, and in general our semantics are entirely value and type based, so we do need to decide some behavior for this case.

The tradeoff here is essentially one of performance vs surprise. Option 4 has detect performance, but a high surprise level. The answer would change whenever `f` gets re-codegen'ed which is not something that users are traditionally expected to have a mental model of. Option 2 has the same problem (but differs for `ccall((println("Hello"); globalsin)))`). Option 1 goes in the direction of retaining the performance while solving the surprise problem by never-reevaluating (although Revise might do so explicitly). Option 5 goes into the opposite direction of sacrificing some performance (in the - rare, unlikely - fully dynamic case), but reducing surprise by being closer to the native Option 3.

As a general design principle in Julia, we do tend to choose the most dynamic behavior (as long as it is still possible to optimize the common case), which would weigh in favor of option 5.

### Implementation Considerations

Given the above considerations, I think the general consenus was that option 5 is preferred. It is close enough to the current semantics (and identical in the cases
that people actually use) that we should be able to do it without deprecation cycle.

To implement this, I had suggested the following lowering:

```
@assume_effects :consistent_once_per_process :effect_free :consistent_termination dlsym(...)::Ptr{Cvoid} = ... 

function do_call()
	# ccall((bar, lib), ...)
	ptr = inline_cache(dlsym(lib, bar))
	$(Expr(:foreigncall, ptr, ...))
end
```

where `consistent_once_per_process` is a new non-IPO effect annotation that specifies that the result of a call may be assumed `:consistent` within each process (i.e. may be cached for `egal` arguments). And `inline_cache` is a new_builtin that is semantically a no-op, but annotates to the optimizer to perform the caching optimization (using :consistent-cy inference to determine the scope of the region to cache). @vtjnash objected to this scheme on complexity grounds, @jeffbezanson objected on IR size grounds. However, I think people generally agreed that the semantics were reasonable.

Thus, the ultimate proposal is to treat the above as the semantic representation of what :foreigncall should do, but keep both the `dlsym` generic call and the inline_cache inside :foreigncall where they are now. The various places that need to 
analyze this (inference, trimming, etc.) should then model :foreigncall to include the generic call to `dlsym`, including providing edges for it.

### PR DESCRIPTION
**Pull request by vtjnash**
We have long expected users to be explicit about the library name for `ccall`, and the `@ccall` macro has even always enforced that. That means users should have already been using explicit syntax, even though it wasn't strictly enforced. And indeed, the other syntax forms weren't handled reliably anyways (since doing so would require linearizing IR if and only if the runtime values required it, which is not something that is computable, and thus was often done wrong). This now intends to align the runtime and compiler to expect only those syntax forms that we could reliably handle in the past without errors, and adds explicit errors for other cases, most of which we previously knew would be unreliable due to reliance upon inference in making particular decisions for the semantics. The `ccall` function is already very special since it is more like a actual macro (it does not exist as a binding or value), so we can make unusual syntax decisions like this, mirroring `@ccall` also.

This fixes #57931, mostly by restricting the set of things that are allowed to the set of things that have an obvious and pre-existing behavior to be guaranteed to do that behavior. The hope is to PkgEval this to check if any packages are doing something unusual and see if we even need to allow anything else.

This drops support for https://github.com/JuliaLang/julia/pull/37123, since we were going to use that for LazyLibraries, be we decided that approach was quite buggy and that PR would make static compilation quite impossible to support, so we instead actually implemented LazyLibraries with a different approach. It could be re-enabled, but we never had correct lowering or inference support for it, so it is presumably still unused.

The goal is to cause breakage only where the package authors really failed to express intent with syntax, and otherwise to explicitly maintain support by adding cases to normalize the given syntax into one of the supported cases. All existing functionality (and more) can be accessed by explicit management of a pointer or by a LazyLibrary-like type, so this shouldn't cause any reduction in possible functionality, just possibly altered syntax.

In followup work, we may want to apply some similar improvements to the cglobal semantics, though not nearly as urgent, since cglobal on a pointer is permitted as a complicated bitcast right now, which doesn't make sense and probably should be deprecated, so that there is no ambiguity with that function's meaning.

Mostly written by Claude

### CODE REVIEW

**Comment by Keno** [comment]
Can we specify that the variable must be a constant binding (in the evaluation world) and have it participate in the invalidation? I don't know that I like the time traveling binding behavior. Seems like a nice change otherwise though.

**Comment by vtjnash** [comment]
No, far too much code (all JLLs before they are recompiled to be lazy) relies upon the dynamic behavior of allowing a non-constant binding to evaluate at runtime and cache. Basically, I don't consider this to be time traveling anymore either, but rather that it is intended to express equivalent behavior to there existing a separate `const` cache variable, which can be out of date (ahead or behind) the variable that is supposed to compute it, and thus enables explicitly rejecting the notion of time travel here (data never time travels, only bindings and functions):
```
const call_target = Ref(C_NULL)
global lib = "runtime value"
global name = "runtime value"
f() = @atomiconce call_target[] = dlsym(name, dlopen(lib))
```

**Comment by Keno** [comment]
Ok. Perhaps we could still invalidate on binding replacement though? I don't think that'd be much harder to implement, and gets us 90% of the way there (and non-const could be disallowed in the future or in strict mode).

**Comment by vtjnash** [comment]
I'm still not sure I quite follow the request. Are you suggesting we add a semantic dependence on data, or simply best-effort? I think we already will do a best effort attempt which should happen in most cases (particularly after Jeff's PR, and other related corrections to trimming)

**Comment by Keno** [comment]
My request is to make that invalidation a semantic guarantee by making the completely generic fallback path record the world age it was created in and then checking if the latest binding partition covers that world age.

**Comment by topolarity** [comment]
Thanks for taking the initiative!

This feels like a much more pragmatic (and complete) solution to https://github.com/JuliaLang/julia/issues/57931 than anything else we've implemented so far.

I think I prefer this to the more dynamic options proposed in #57931, esp. since those only covered the case of a dynamically-chosen library `ccall`'d with statically-evaluated ABI / types. That seems like a narrow use case (and is anyway already possible with a function pointer and some amount of manual caching, as you mention) so preserving our existing static-by-default semantics, as determined by syntax, feels like a much less radical change to me.

> This drops support for https://github.com/JuliaLang/julia/pull/37123, since we were going to use that for LazyLibraries, be we decided that approach was quite buggy and that PR would make static compilation quite impossible to support

Why does this make static compilation impossible?

It doesn't seem like, e.g., the behavior proposed in solution (5) in https://github.com/JuliaLang/julia/pull/57931 is impossible to statically compile, assuming it is type-stable (but not necessarily value-stable) - but maybe you were referring just to the particular implementation in that PR?

**Comment by vtjnash** [comment]
> Why does this make static compilation impossible?

It seemed mainly that we couldn't quite define whether it was a static name expression or a dynamic pointer so it couldn't be quite linearized so it was sort of an embedded `eval` call in some unknown world

File: base/gmp.jl [hunk 1]
```diff
@@ -151,7 +151,7 @@ using ..GMP: BigInt, Limb, BITS_PER_LIMB, libgmp
 const mpz_t = Ref{BigInt}
 const bitcnt_t = Culong
 
-gmpz(op::Symbol) = (Symbol(:__gmpz_, op), libgmp)
+gmpz(op::Symbol) = Expr(:tuple, QuoteNode(Symbol(:__gmpz_, op)), GlobalRef(MPZ, :libgmp))
```
Comment (JeffBezanson) [inline base/gmp.jl:154]: I wouldn't be surprised if some other packages do this. We might need to allow it.

File: doc/src/manual/calling-c-and-fortran-code.md [hunk 2]
```diff
@@ -990,11 +998,37 @@ The arguments to [`ccall`](@ref) are:
 
 
 !!! note
-    The `(:function, "library")` pair, return type, and input types must be literal constants
-    (i.e., they can't be variables, but see [Non-constant Function Specifications](@ref)).
-
-    The remaining parameters are evaluated at compile-time, when the containing method is defined.
-
+    The `(:function, "library")` pair and the input type list must be syntactic tuples
+    (i.e., they can't be variables or values with a tuple of Tuple.
```
Comment (JeffBezanson) [inline doc/src/manual/calling-c-and-fortran-code.md]:
```suggestion
    (i.e., they can't be variables or values with a type of Tuple.
```

File: src/julia-syntax.scm [hunk 3]
```diff
@@ -4443,6 +4469,14 @@ f(x) = yt(x)
          (list-set e 3 (compile-body (cadddr e)
                                      (append (car (caddr e))
                                              (cadr (caddr e))) e)))
+        ((eq? (car e) 'foreigncall)
```
Comment (JeffBezanson) [inline src/julia-syntax.scm]: This is handled by `compile-body`.

File: src/method.c [hunk 4]
```diff
@@ -175,6 +175,54 @@ static jl_value_t *resolve_definition_effects(jl_value_t *expr, jl_module_t *mod
...
         jl_task_t *ct = jl_current_task;
+        jl_value_t *fptr = jl_exprarg(e, 0);
+        // Handle dot expressions in tuple arguments for ccall by converting to GlobalRef eagerly
+        if (jl_is_expr(fptr) && ((jl_expr_t*)fptr)->head == jl_symbol("tuple")) {
+            jl_expr_t *tuple_expr = (jl_expr_t*)fptr;
+            size_t nargs_tuple = jl_expr_nargs(tuple_expr);
+            if (nargs_tuple == 0)
+                jl_error("ccall function name cannot be empty tuple");
+            if (nargs_tuple > 2)
+                jl_error("ccall function name tuple can have at most 2 elements");
```
Comment (JeffBezanson) [inline src/method.c:194]: I think these kinds of syntax validity checks should be done by lowering.

**Comment by JeffBezanson** [comment]
I'm not sure we should do this. I'm willing to hold out for a version that eliminates `static_eval` completely and has simpler semantics.

**Comment by vtjnash** [comment]
This version does eliminate it semantically, though I didn't quite remove it, it only gets trivial cases now and only as an optimization (to peek at whether the expression is constant before emitting a branch to contain it). It is still used by cglobal, which I left as followup work.

File: src/runtime_ccall.cpp [hunk 5]
```diff
@@ -64,22 +64,35 @@ void *jl_load_and_lookup(const char *f_lib, const char *f_name, _Atomic(void*) *
...
+    if (jl_is_symbol(f_name))
+        fname_str = jl_symbol_name((jl_sym_t*)f_name);
+    else if (jl_is_string(f_name))
+        fname_str = jl_string_data(f_name);
+    else
+        jl_type_error("ccall function name", (jl_value_t*)jl_symbol_type, f_name);
+
+    // If the user didn't supply a library name, try to find it now from the runtime value of f_name
+    if (lib_val == NULL)
+        lib_ptr = jl_get_library(jl_dlfind(fname_str));
```
Comment (topolarity) [inline src/runtime_ccall.cpp:92]:
```suggestion
    void *lib_ptr;
    const char *fname_str;

    if (jl_is_symbol(f_name))
        fname_str = jl_symbol_name((jl_sym_t*)f_name);
    else if (jl_is_string(f_name))
        fname_str = jl_string_data(f_name);
    else
        jl_type_error("ccall function name", (jl_value_t*)jl_symbol_type, f_name);

    if (lib_val) {
        if (jl_is_symbol(lib_val))
            lib_ptr = jl_get_library(jl_symbol_name((jl_sym_t*)lib_val));
        else if (jl_is_string(lib_val))
            lib_ptr = jl_get_library(jl_string_data(lib_val));
        else if (jl_libdl_dlopen_func != NULL) {
            lib_ptr = jl_unbox_voidpointer(jl_apply_generic(jl_libdl_dlopen_func, &lib_val, 1));
        } else
            jl_type_error("ccall", (jl_value_t*)jl_symbol_type, lib_val);
    } else {
        // If the user didn't supply a library name, try to find it now from the runtime value of f_name
        lib_ptr = jl_get_library(jl_dlfind(fname_str));
    }
```

makes the case analysis a bit more direct, to fix:
```julia
[buildroot]/src/runtime_ccall.cpp:95:13: error: 'lib_ptr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
--
  | 95 \|     jl_dlsym(lib_ptr, fname_str, &ptr, 1);
```

File: base/gmp.jl (hunk 1 above)
Comment (vtjnash) [reply base/gmp.jl:154]: Yes, we might, but until PkgEval results finish, we won't know if we need to add yet more cases or are fine with what we already have covering all uses. It is fairly easy to add (it is the same as the syntactic string case), but we won't know if it worth documenting yet another optional form of the same thing until we finish the test run.

File: src/method.c (hunk 4 above)
Comment (vtjnash) [reply src/method.c:194]: These are value checks (it is preparing to call `jl_toplevel_eval`), so they are not straightforward to have duplicated in both of our lowering implementations now

File: src/julia-syntax.scm (hunk 3 above)
Comment (vtjnash) [reply src/julia-syntax.scm]: Good point. I forgot everything ends up wrapped in a lambda, so it is impossible for this pass to end up encountering `foreigncall`.

**Comment by topolarity** [comment]
Unsurprisingly, looks like JuliaInterpreter and friends need some adjusting: https://buildkite.com/julialang/julia-master/builds/49600#01986719-957f-4f8a-9636-9470d50ae64b/836-1055

**Comment by vtjnash** [comment]
Yes, it looks like given the choices among possible buggy reimplementations of the ill-defined `static_eval` previously implemented here, it chose one of the buggiest versions (it just calls `eval` on the first argument and embeds the result into the new IR)

**Comment by vtjnash** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/59165#issuecomment-3146118289) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/cce193b_vs_2eb2bf9/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

5 packages crashed on the previous version too.

## ✖ Packages that failed

**988 packages failed only on the current version.**

 - Package fails to precompile: 908 packages
 - Illegal method overwrites during precompilation: 13 packages
 - Package has test failures: 5 packages
 - Package tests unexpectedly errored: 21 packages
 - Networking-related issues were detected: 9 packages
 - There were unidentified errors: 2 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 28 packages
 - Test log exceeded the size limit: 1 packages

1192 packages failed on the previous version too.

## ✔ Packages that passed tests

**12 packages passed tests only on the current version.**

 - Other: 12 packages

4832 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**3 packages successfully loaded only on the current version.**

 - Other: 3 packages

2857 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

**6 packages were skipped only on the current version.**

 - Package could not be installed: 6 packages

904 packages were skipped on the previous version too.



</details>

**Comment by vtjnash** [comment]
It looks like a majority of those were due to a recent breaking change in FFTW (https://github.com/JuliaMath/FFTW.jl/pull/207) which could just be partly reverted it seems (it had been in preparation for LazyLibraries, but then we went a different way with implementation of those, so now this should be reverted to actually support them)

**Comment by vtjnash** [comment]
@nanosoldier `runtests(["AutoCorrelationResampling", "Fourier", "NumberTheoreticTransforms", "MeanFilters", "GeneralizedRouwenhorst", "SpecAugment", "Checkerboard", "TestEnv", "StableLinearAlgebra", "MutableShiftedArrays", "AppleAccelerate", "NonlinearEquations", "ShortFFTs", "ConvexHulls2d", "EarlyStopping", "JDQMCFramework", "CGcoefficient", "WellKnownGeometry", "Spinnaker", "Skipper", "SmallCombinatorics", "LoweredCodeUtils", "CUDA_Driver", "ImageGeoms", "RunningQuantiles", "AbstractFastHartleyTransforms", "CxxWrap", "PositionalEmbeddings", "Measurements", "AutoSymPTR", "Pardiso", "BallArithmetic", "SHTns", "Opus", "LACosmic", "SMCExamples", "Revise", "LinearOperatorCollection", "StrICU", "CrystallographyBase", "Uncertain", "IntervalArithmetic", "InfiniteArrays", "FourierSeries", "LocalSignalAttributes", "DifferentialPhaseContrast", "Hadamard", "MDCT", "Deconvolution", "FINUFFT", "TrigPolys", "RealFFTs", "ThreadPinning", "ChebyshevTransforms", "FFTW", "OccurrencesInterface", "GenericFFT", "FFTInterpolations", "FFTResampling", "AcousticFeatures", "Walsh", "PDEngine", "FFTViews", "KissSmoothing", "SmoQyKPMCore", "PowerLawNoise", "RandomizedPreconditioners", "ExampleJuggler", "FastHartleyTransform", "NFFTTools", "SkyCoords", "StationaryRandomFields", "PhaseRec", "MuSink", "ArnoldiMethodTransformations", "AbstractImageReconstruction", "SubpixelRegistration", "LoRaPHY", "SpeechFeatures", "FastChebInterp", "PulseArchitect", "ImagePhantoms", "BlockArrays", "PseudostableRecurrences", "LatticeUtilities", "OpticalPropagation", "GeoJSON", "ExtXYZ", "ImplicitPlots", "HChebInterp", "InMemoryDatasets", "LongDatasetSort", "WORLD", "InverseLaplace", "FixedEffects", "InterferometricModels", "LowRankApprox", "CartesianJoin", "UncertainSkyCoords", "FdeSolver", "SymEngine", "DLMReader", "Shapefile", "CastepReader", "ArbNumerics", "AMGCLWrap", "NearestCorrelationMatrix", "TimeseriesFeatures", "Arblib", "DifferentialRiccatiEquations", "JDQMCMeasurements", "GeoInterfaceMakie", "Electrum", "TinyEKFGen", "ArbExtras", "LinearInterpolators", "CharacteristicInvFourier", "Sixel", "RadonKA", "LombScargle", "BarnesDoubleGamma", "LazyAlgebra", "BasisFunctionExpansions", "SpectralEnvelope", "SNMRForward", "GPLinearODEMaker", "BM3DDenoise", "SIAMFANLEquations", "DensityRatioEstimation", "GraphPlot", "NamedTrajectories", "AutoregressiveModels", "QuadratureRules", "FourierSpaces", "Sinograms", "MicroscopyTools", "PolynomialBases", "FastTransformsForwardDiff", "WavesAndEigenvalues", "Polylabel", "TwoFAST", "RandFieldStructFuncs", "SMLMMetrics", "TotalVariation", "AutoVectors", "SavitskyGolayFilters", "EasyFFTs", "EDFPlus", "Autocorrelations", "Dolang", "ElementarySymmetricFunctions", "Wavelets", "AuditoryFilters", "DSP", "FastLocalCorrelationCoefficients", "AcousticMetrics", "FourierAnalysis", "OceanLight", "RFImpairmentsModels", "GastonDSP", "MRIFiles", "FiberNlse", "GeneralizedPhase", "HeartBeats", "KadanoffBaym", "GeostatInversion", "JetPackDSP", "SpectralWaves", "HarmonicPolya", "MRICoilSensitivities", "IntervalWavelets", "FlashAttentionWrapper", "DigitalComm", "Phylopic", "QuadraticFormsMGHyp", "SampledSignals", "BandwidthBenchmark", "PolynomialModelReductionDataset", "IsotopeCorrection", "MeanSquaredDisplacement", "ModelParameters", "SparsityOperators", "GeoIP", "MacOSIOReport", "MultiPrecisionArrays", "GridUtilities", "CMDimCircuits", "TaylorFourierTransform", "GaussianRandomFields", "ClusteredLowRankSolver", "MathJaxRenderer", "TemplateMatching", "LaserFields", "WaterWaves1D", "MultiFractalFields", "NeuralFieldEq", "ImageSmooth", "ConvolutionalOperatorLearning", "GLM", "BPGates", "AutoHist", "ParametricBodies", "OrnsteinZernike", "IncompressibleNavierStokes", "NonuniformFFTs", "SemiLagrangian", "FFTDists", "ImageFiltering", "MultiCDF", "AcceleratorSimUtils", "LittleEphemeris", "PressureSensitiveMats", "FractionalTransforms", "ToeplitzMatrices", "MAiNGO", "IntervalMDP", "OptimalBranchingCore", "KalmanFilters", "LibSndFile", "WaveFD", "Postprocessing", "MutualInformationImageRegistration", "ReinforcementLearningTrajectories", "YaoSym", "Clarabel", "CartesianGrids", "KomaMRIBase", "MCMCDiagnosticTools", "KernelDensity", "Vlasiator", "NonParametricNORTA", "MartaCT", "Coulter", "STFT", "MDEStudy", "BasicTextRender", "Jolab", "GeNIOS", "NumericalDistributions", "ApproxFunBaseTest", "ImageCorners", "MonteCarloMarkovKernels", "PolyChaos", "ProbabilityBoundsAnalysis", "RainFARM", "MicroMagnetic", "ApproxFunBase", "AdaptiveFilters", "SPECTrecon", "SmoQyDQMC", "MFCC", "Tonari", "FastTransforms", "NFFT", "AcceleratorLattice", "KomaMRIFiles", "AbstractOperators", "TrainingPhantoms", "SyntheticEddyMethod", "YaoToEinsum", "FixedEffectModels", "PoissonSolvers", "PhilipsDataList", "FinanceTools", "QPGreen", "FastSphericalHarmonics", "QuasinormalModes", "ElectromagneticFields", "SineFit", "SphericalHaarTransform", "RoomAcoustics", "AngularSpectrumMethod", "GlobalSensitivityAnalysis", "GeoArrayOps", "OnlinePortfolioSelection", "SlidingDistancesBase", "ComplexityMeasures", "AbstractSDRs_rx_ascii_art_dft", "Lasso", "RegressionDynamicCausalModeling", "ImageEdgeDetection", "BytePairEncoding", "ParetoSmooth", "BoundaryLayerDynamics", "MRICompress", "LocalProjections", "BootstrapVirasoro", "PoincareInvariants", "NaiveBayes", "AlgebraicMultigrid", "ImageComponentAnalysis", "ADCME", "AdvancedMH", "TicraUtilities", "Pingouin", "StratiGraphics", "MatrixProfile", "Acquisition", "EHTModels", "ImagePhaseCongruency", "AlphaStableDistributions", "TimeseriesSurrogates", "FractalDimensions", "FrameFun", "VkFFTCUDA", "SeisPlot", "BatchedBLAS", "ChowLiuTrees", "IndexSpaces", "ImageIO", "Augmentor", "ShaneGPUCountMinSketch", "AuditorySignalUtils", "CudaNTTs", "MethodOfMoments", "ChaChaCiphers", "SimulationLogs", "Jello", "FourierTools", "CompactBasisFunctions", "ImageInpainting", "CUSOLVERRF", "PointSpreadFunctions", "AMGX", "LlamaCppOutlines", "CuTropicalGEMM", "GAP", "cuStateVec", "GEMPIC", "TransferFunctions", "AeroAcoustics", "Synaptogen", "HierarchicalTemporalMemory", "NextLA", "cuTensorNet", "LPVSpectral", "SimpleDiffEq", "SliceSampling", "MLJNaiveBayesInterface", "FractionalGaussianFields", "CUDASIMDTypes", "SemiclassicalOrthogonalPolynomials", "ADCMEKit", "LocalPoly", "HarmonicOrthogonalPolynomials", "OptimizationMultistartOptimization", "Earth", "ApproxFunOrthogonalPolynomials", "LuxCUDA", "ApproxFunFourier", "MultivariateSingularIntegrals", "MultivariateOrthogonalPolynomials", "SingularIntegrals", "GraphSignals", "RadiationDetectorDSP", "ApproxFunSingularities", "Multitaper", "GenomicOffsets", "PiecewiseOrthogonalPolynomials", "SimplexGridFactory", "GridVisualize", "SurveyDataWeighting", "KernelDensityEstimatePlotting", "Sainsc", "NeumannKelvin", "TaylorIntegration", "TurbulenceFlux", "CountingChambers", "ContinuousWavelets", "ScalingCollapse", "Gadfly", "Stopping", "ApproxFun", "CoupledElectricMagneticDipoles", "BcdiCore", "MRIOperators", "Zauner", "ClassicalOrthogonalPolynomials", "VLBIImagePriors", "BcdiTrad", "KomaMRICore", "SatelliteAnalysis", "Hamburg", "RadialPiecewisePolynomials", "SmoQySynthAC", "EquilibriumMeasures", "TimeseriesUtilities", "BcdiStrain", "SpmImages", "StatisticalGraphics", "BlochSimulators", "DampRR", "SeisReconstruction", "RecurrenceCoefficients", "SodShockTube", "DynamicAxisWarping", "Gridap", "AlgebraicCurveOrthogonalPolynomials", "OrdinaryDiffEqQPRK", "ChebParticleMesh", "SeisProcessing", "ElectricFields", "MPIFiles", "OrdinaryDiffEqFeagin", "SignalAlignment", "JOLI", "OrthogonalSphericalShellGrids", "SpinWeightedSpheroidalHarmonics", "Isoplot", "MRISimulation", "TokenCompression", "FourierFlows", "RayTracing", "AsapOptim", "ApproximatingMapsBetweenLinearSpaces", "EquivariantOperators", "ImageQualityIndexes", "EquilibratedFlux", "TransitionsInTimeseries", "WhittleLikelihoodInference", "SteadyStateDiffEq", "PositiveIntegrators", "SIMIlluminationPatterns", "OceanWaveSpectralFitting", "SignalDecomposition", "CalciumScoring", "XGBoost", "PowerNetworkMatrices", "MadNLPGPU", "NonlinearSolveQuasiNewton", "ArchGDAL", "SMLMFrameConnection", "Pixell", "ImageGather", "SurrogatesPolyChaos", "VisualRegressionTests", "ConstrainedSystems", "PowerFlows", "BoltzmannMachinesPlots", "TracyWidomBeta", "MRFingerprintingRecon", "SummationByPartsOperators", "SkeelBerzins", "JUDI", "DiffEqPhysics", "PhysicalMeshes", "SphericalFunctions", "RigorousCoupledWaveAnalysis", "ModeCouplingTheory", "SpinGlassTensors", "HighDimMixedModels", "ParticleInCell", "CudaRBMs", "TinyGibbs", "ImageSegmentation", "ClimaCoreSpectra", "SignalAnalysis", "GridapDistributed", "SimpleImplicitDiscreteSolve", "CausalityTools", "Empirikos", "MPIMeasurements", "ReducedComplexityModeling", "MRIReco", "KDEstimation", "QuantumFluidSpectra", "QuantEcon", "BasisMatrices", "TimeseriesTools", "BioLab", "PhysicalFFT", "ElasticFDSG", "GeophysicalFlows", "SpeedyWeather", "PencilFFTs", "QuantumOpticsBase", "OrdinaryDiffEqDifferentiation", "Batsrus", "DiffEqGPU", "OrdinaryDiffEqRosenbrock", "Associations", "MCMCChains", "GrayCoding", "NonlinearSolveFirstOrder", "ClimaSeaIce", "GridapP4est", "DiracBilinears", "NestedSamplers", "GilaElectromagnetics", "SetIntersectionProjection", "DeconvOptim", "FittedItemBanks", "FastSpecSoG", "OrdinaryDiffEqExponentialRK", "MIRT", "JetPack", "MCMCTempering", "OrdinaryDiffEqExtrapolation", "PhysicalFDM", "LatticeModels", "AtmosphericModels", "BayesQR", "KomaMRIPlots", "JetPackTransforms", "ZilanyBruceCarney2014", "ProjectManagement", "BoundaryValueDiffEqCore", "NonlinearSolve", "BoundaryValueDiffEqAscher", "DeepFry", "OperatorFlux", "ProteinEnsembles", "TruncatedMVN", "BoundaryValueDiffEqShooting", "BoundaryValueDiffEqMIRK", "MCMCChainsStorage", "BoundaryValueDiffEqFIRK", "BoundaryValueDiffEqMIRKN", "BcdiSimulate", "FishTank", "DifferentialEvolutionMCMC", "Sunny", "PiecewiseDeterministicMarkovProcesses", "FractionalDiffEq", "SpmGrids", "GumbelSoftmax", "Crispulator", "OrdinaryDiffEqNonlinearSolve", "ManiFactor", "PSSFSS", "OrdinaryDiffEqSDIRK", "OrdinaryDiffEqPDIRK", "OrdinaryDiffEqIMEXMultistep", "OrdinaryDiffEqBDF", "OrdinaryDiffEqStabilizedIRK", "RHEOS", "OrdinaryDiffEqFIRK", "CanopyOptics", "ONSAS", "InstrumentOperator", "HarmonicPowerModels", "SteadyWaves", "SpecialExponentialFamilies", "Bcube", "MriResearchTools", "OpticalFibers", "GeneralisedFilters", "CLEARSWI", "OrdinaryDiffEqDefault", "Tracking", "BcdiMeso", "JetPackWaveFD", "MPISphericalHarmonics", "PowerSpectra", "ITensorGPU", "ROMEO", "CorrelationFunctions", "BoundaryValueDiffEq", "MRIGradients", "DiffEqUncertainty", "UnetUtils", "TinnitusReconstructor", "Walrus", "CirculantAttention", "QuantitativeSusceptibilityMappingTGV", "PeriodicOrbits", "NoiseModels", "PotentialFlow", "VectorSpaceDarkMatter", "ControlSystemIdentification", "DistributedStwdLDA", "BackgroundSubtraction", "TestParticle", "ImgCIFHandler", "BcubeVTK", "StellarSpectraObservationFitting", "NonstationaryProcessesBase", "NonstationaryProcesses", "DoloYAML", "SphericalFourierBesselDecompositions", "UltraDark", "VIDA", "Photometry", "SimSpin", "NetworkDynamics", "BioFindr", "JosephsonCircuits", "ExtremePlots", "DiffEqFinancial", "Swalbe", "BLAKJac", "MendelPlots", "Oscar", "GeometricIntegrators", "Extremes", "Fortuna", "GroebnerWalk", "PawsomeTracker", "ReinforcementLearningFarm", "Jags", "BEASTDataPrep", "NetworkHawkesProcesses", "SymbolicAnalysis", "GridPotentialFlow", "WaveOpticsPropagation", "Dolo", "IDFCurves", "ToricAtiyahBott", "GenericCharacterTables", "OptimizationFlux", "MessyTimeSeriesOptim", "ComputationalHeatTransfer", "Mimi", "BcubeCGNS", "PowerSimulations", "HomotopyContinuation", "FSimZoo", "MimiFAIRv1_6_2", "HydroPowerSimulations", "Mimi_NAS_pH", "StorageSystemsSimulations", "PowerAnalytics", "PowerSimulationsDynamics", "ImmersedLayers", "MimiSNEASY", "FluxMPI", "MimiMooreEtAlAgricultureImpacts", "MGVI", "FerriteMultigrid", "LearnVanishingIdeal", "RandomizedDiagonalEstimation", "MusicProcessing", "EFTfitter", "VortexStepMethod", "PostNewtonian", "OrdinaryDiffEq", "ProbNumDiffEq", "ClimaCalibrate", "ViscousFlow", "AcousticAnalogies", "MimiPAGE2020", "GModelFit", "SourceCodeMcCormick", "UncertainData", "DynamicMovementPrimitives", "MatterPower", "Yao", "FLOYao", "GModelFitViewer", "Attractors", "GridapGmsh", "Rimu", "CodonMolecularEvolution", "MimiSSPs", "ChaosTools", "ImageQuilting", "PulseInputDDM", "SLHQuantumSystems", "VoronoiFVM", "Phonetics", "GeoSimulation", "UVITTools", "SimpleSDMPolygons", "SecondQuantizedAlgebra", "Einstein", "Intan", "SensitivityRankCondition", "YaoExtensions", "ApproxMasterEqs", "FNCFunctions", "SystemBenchmark", "Circuitscape", "StatsKit", "YaoSubspaceArrayReg", "Omniscape", "LogicCircuits", "FastBEAST", "MimiRFFSPs", "NBodySimulator", "RandomFeatures", "BloqadeExpr", "Consensus", "LiquidElectrolytes", "Comrade", "RvSpectML", "Ditherings", "Regions", "GradientRobustMultiPhysics", "BcubeGmsh", "Eikonal", "Images", "PlotPlants", "InvertibleNetworks", "ColorSchemeTools", "HoloProcessing", "GeneralizedSDistributions", "ImageTracking", "MimiCIAM", "ComplexPhasePortrait", "QuadraticOutputSystems", "OperatorApproximation", "GameTheory", "BLASBenchmarksCPU", "ILMPostProcessing", "ObjectDetector", "ScatteringOptics", "GigaScatter", "AbstractPlotting", "SunlightHNC", "EMpht", "OptimalBranchingMIS", "ImageFeatures", "Globtim", "HssMatrices", "MIRTjim", "QuantizedSystemSolver", "SpaSM", "StatisticalRethinking", "NonlinearSolveHomotopyContinuation", "RogueWaveInfiniteNLS", "ImageUtils", "GeoStatsSolvers", "SafetySignalDetection", "Trebuchet", "LongwaveModePropagator", "UnfoldSim", "ClimateTools", "AutocorrelationShell", "AuditoryStimuli", "ChargeTransport", "ElectroPhysiology", "UnderwaterAcoustics", "DynamicalSystems", "SpQEphysTools", "VirtualAcousticOcean", "BloodFlowTrixi", "ParametricOperators", "QSFit", "DirectTrajOpt", "Luna", "TrixiShallowWater", "AIBECS", "Hedgehog", "KomaMRI", "Trixi2Vtk", "QuantumCollocation", "FlightSims", "ClimatePlots", "Tapestree", "OtsuThresholding", "ModelingToolkitStandardLibrary", "StarFormationHistories", "CategoricalTimeSeries", "DecomposingPolynomialSystems", "PixelArt", "Cropbox", "Makie", "BioChemicalTreatment", "PhysiologyPlotting", "MultiScaleArrays", "WebToys", "NeuralLyapunovProblemLibrary", "SmithChart", "ODEProblemLibrary", "Ai4EComponentLib", "ParameterizedFunctions", "EntropyHub", "StochasticDelayDiffEq", "SimpleCrop", "SwarmMakie", "FiniteStateProjection", "BaseModelica", "ReactionNetworkImporters", "GpABC", "LeafGasExchange", "InteractiveViz", "MintsMakieRecipes", "CatmullClark", "SBMLToolkit", "ImageColorThresholderApp", "JumpProblemLibrary", "GeometryPrimitives", "Basins", "StatsPlots", "SeisMakie", "MakieDraw", "PlotShapefiles", "CairoMakie", "TernaryDiagrams", "Garlic", "ItemResponsePlots", "MakieRichText", "Biplots", "DiffusionGarnet", "MakiePublication", "Escher", "LocalAnisotropies", "MomentClosure", "CellMLToolkit", "RPRMakie", "ModelingToolkitNeuralNets", "AbstractGPsMakie", "MaxwellBase", "LowLevelParticleFiltersMTK", "MakiePDF", "Pesto", "FisherPlot", "InPartSMakie", "NestedGraphMakie", "StochasticWeatherGenerators", "PlantViz", "AppBundler", "OptimizationMOI", "ThermovisorImages", "ChemfilesViewer", "PlantGraphs", "MicrobiomeAnalysis", "PairPlots", "GraphMakie", "GeoStats", "OptimizedEinsum", "CollatzConjecture", "Piccolo", "PubChem", "DistributedRelaxationTimes", "QuDiffEq", "GeometricFlux", "Yunir", "FerriteViz", "PlantGeomTurtle", "VlasiatorMakie", "MembraneAnalysis", "SIAN", "BloqadeKrylov", "DynamicModelTestUtils", "PeriodicMatrices", "MakieTeX", "LWFBrook90", "ThreeBodyTB", "GeoMakie", "SpectralStatistics", "AlgebraOfGraphics", "EarthSciMLBase", "MapMakie", "EigenShow", "WGLMakie", "LongMemory", "CitableImage", "TestParticleMakie", "ColorVintner", "AcousticRayTracers", "WGPUgfx", "TightBindingToolkit", "WaveguideQED", "AeroBeams", "RankCompV3", "ThesisArt", "HarmonicPowerFlow", "SymbolicNumericIntegration", "CitablePhysicalText", "DataDrivenDMD", "DataDrivenSparse", "FrequencySweep", "SignedDistanceField", "VisClaw", "Drifters", "InformationGeometry", "SankeyMakie", "SynapseElife", "PhysiologyAnalysis", "VirtualPlantLab", "TuringGLM", "IndividualDisplacements", "KinematicDriver", "AoGExtensions", "SSMPlots", "MethodOfLines", "HetaSimulator", "QEPOptimize", "Chron", "SubsidenceChron", "DataDrivenSR", "MPIReco", "VLBIPlots", "MultiAgentPathFinding", "ActionModels", "MTKHelpers", "TrajectoryGamesBase", "SequentialSamplingModels", "JenaAtomicCalculator", "HierarchicalGaussianFiltering", "CalibrateEmulateSample", "ProtPlot", "TrajectoryGamesExamples", "Repotomata", "StochasticGene", "MeshViz", "SignalTablesInterface_CairoMakie", "ActiveInference", "ModiaPlot_CairoMakie", "MCHammer", "ObservableCortex", "BiGSTARS", "EditorsRepo", "QuantumCumulants", "ClimaCoreMakie", "Spectra", "StateSpaceAnalysis", "RainMaker", "NeuroStats", "Tortuosity", "ModiaPlot_GLMakie", "WaveletsExt", "MCPhylo", "Jchemo", "FKRBDemand", "CollectiveSpins", "PowerGraphics", "CatColabInterop", "MESTI", "MixedModelsMakie", "SGCRNAs", "BoxCox", "GridapMakie", "MaterialPointVisualizer", "MRIgeneralizedBloch", "FourLeafMLE", "Octofitter", "SimulatedNeuralMoments", "PDMPFlux", "MimiBRICK", "MicroTracker", "UnfoldDecode", "HomotopyOpt", "HeartRateVariability", "IMAS", "SphericalClusterMass", "MimiGIVE", "ITensorMakie", "SymplecticMapTools", "StateSpacePartitions", "StatisticalRethinkingPlots", "Tyler", "FusionSyntheticDiagnostics", "CropRootBox", "InferenceReport", "Kraken", "MixedComplementarityProblems", "GalacticPotentials", "QAOA", "TensegrityEquilibria", "Pioran", "MRINavigator", "SimulationBasedCalibration", "QuantumDynamics", "Biofilm", "XPalm", "StratIntervals", "TidierPlots", "SPEDAS", "Graphene", "Turkie", "OctofitterRadialVelocity", "Coalescent", "SpectralDistances", "ElasticNetworks", "IonSim", "SoilWater_ToolBox", "HmtGutenberg", "BloqadeODE", "UnfoldMakie", "BloqadeGates", "CanDecomp", "GasChromatographySimulator", "SBMLToolkitTestSuite", "MiseEnPage", "Tidier", "RigorousInvariantMeasures", "Controlz", "ReducedBasisMethods", "DecisionFocusedLearningBenchmarks", "Test", "MagNav", "NTFk"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/59165#issuecomment-3303349130) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b3f8bb4_vs_067b013/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

1 packages crashed on the previous version too.

## ✖ Packages that failed

**167 packages failed only on the current version.**

 - Package fails to precompile: 126 packages
 - Illegal method overwrites during precompilation: 5 packages
 - Package has test failures: 2 packages
 - Package tests unexpectedly errored: 20 packages
 - There were unidentified errors: 2 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 11 packages

220 packages failed on the previous version too.

## ✔ Packages that passed tests

**1 packages passed tests only on the current version.**

 - Other: 1 packages

362 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**3 packages successfully loaded only on the current version.**

 - Other: 3 packages

229 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

1 packages were skipped on the previous version too.



</details>

**Comment by vtjnash** [comment]
@nanosoldier `runtests(["CUDA_Driver", "SHTns", "CGcoefficient", "StrICU", "Spinnaker", "Walsh", "Pardiso", "LoweredCodeUtils", "ThreadPinning", "CrystallographyBase", "SymEngine", "SmallCombinatorics", "ArnoldiMethodTransformations", "WellKnownGeometry", "TinyEKFGen", "ArbNumerics", "CxxWrap", "BarnesDoubleGamma", "InMemoryDatasets", "Revise", "LongDatasetSort", "ArbExtras", "GPLinearODEMaker", "CartesianJoin", "TwoFAST", "IntervalArithmetic", "Dolang", "DLMReader", "Polylabel", "PolynomialBases", "ClusteredLowRankSolver", "GeoIP", "BandwidthBenchmark", "AMGCLWrap", "GLM", "YaoSym", "ImplicitPlots", "MDEStudy", "RegressionDynamicCausalModeling", "AlgebraicMultigrid", "QuasinormalModes", "Pingouin", "BootstrapVirasoro", "ElectromagneticFields", "BytePairEncoding", "MAiNGO", "GAP", "SemiLagrangian", "CountingChambers", "SurveyDataWeighting", "PositiveIntegrators", "Hamburg", "StatisticalGraphics", "NonlinearSolve", "AsapOptim", "OrdinaryDiffEqExtrapolation", "ModeCouplingTheory", "ParticleInCell", "PowerNetworkMatrices", "DiffEqGPU", "OrdinaryDiffEqExponentialRK", "TruncatedMVN", "PowerFlows", "ArchGDAL", "SkeelBerzins", "SimpleImplicitDiscreteSolve", "SteadyWaves", "BoundaryValueDiffEqAscher", "OrdinaryDiffEqNonlinearSolve", "OrdinaryDiffEqIMEXMultistep", "OrdinaryDiffEqPDIRK", "OrdinaryDiffEqSDIRK", "BoundaryValueDiffEqCore", "OrdinaryDiffEqFIRK", "OrdinaryDiffEqStabilizedIRK", "OrdinaryDiffEqBDF", "OrdinaryDiffEqDefault", "BoundaryValueDiffEqMIRKN", "BoundaryValueDiffEqShooting", "BoundaryValueDiffEqMIRK", "FittedItemBanks", "DiffEqPhysics", "Fortuna", "PeriodicOrbits", "VortexStepMethod", "Bcube", "ONSAS", "BcubeVTK", "SphericalFourierBesselDecompositions", "GModelFit", "DoloYAML", "GModelFitViewer", "DiffEqFinancial", "HomotopyContinuation", "MatterPower", "FerriteMultigrid", "TestParticle", "Dolo", "LearnVanishingIdeal", "MusicProcessing", "PowerSimulationsDynamics", "GroebnerWalk", "Yao", "FLOYao", "BcubeCGNS", "OptimizationFlux", "ProbNumDiffEq", "Einstein", "GenericCharacterTables", "PowerSimulations", "VoronoiFVM", "Consensus", "MGVI", "FNCFunctions", "Omniscape", "DynamicMovementPrimitives", "PowerAnalytics", "HydroPowerSimulations", "StorageSystemsSimulations", "SensitivityRankCondition", "Circuitscape", "YaoSubspaceArrayReg", "NBodySimulator", "QuadraticOutputSystems", "LiquidElectrolytes", "GeneralizedSDistributions", "BloqadeExpr", "BcubeGmsh", "QuantizedSystemSolver", "EMpht", "Trebuchet", "ScatteringOptics", "GameTheory", "QSFit", "Globtim", "ChargeTransport", "DecomposingPolynomialSystems", "Ai4EComponentLib", "Tapestree", "BaseModelica", "Yunir", "BloqadeKrylov", "PeriodicMatrices", "Pesto", "LWFBrook90", "JenaAtomicCalculator", "KinematicDriver", "QuantumCumulants", "Spectra", "SphericalClusterMass", "HomotopyOpt", "Kraken", "GalacticPotentials", "Octofitter", "IMAS", "FourLeafMLE", "TensegrityEquilibria", "MixedComplementarityProblems", "QuantumDynamics", "Biofilm", "StateSpacePartitions", "BloqadeODE", "IonSim", "SimulationBasedCalibration", "BloqadeGates", "SpectralDistances", "OctofitterRadialVelocity"])`

File: base/gmp.jl (hunk 1 above)
Comment (vtjnash) [reply base/gmp.jl:154]: As you guessed, PkgEval confirmed we should add this case too, so I've done that.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/59165#issuecomment-3309033013) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b251dac_vs_067b013/report.html) is available.

<details><summary>Report summary</summary>

## ✖ Packages that failed

**103 packages failed only on the current version.**

 - Package fails to precompile: 77 packages
 - Illegal method overwrites during precompilation: 5 packages
 - Package tests unexpectedly errored: 7 packages
 - Networking-related issues were detected: 4 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 9 packages

20 packages failed on the previous version too.

## ✔ Packages that passed tests

32 packages passed tests on the previous version too.

## ~ Packages that at least loaded

11 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

1 packages were skipped on the previous version too.



</details>

**Comment by vtjnash** [comment]
@nanosoldier `runtests(["CUDA_Driver", "ThreadPinning", "SHTns", "Walsh", "CGcoefficient", "Spinnaker", "Pardiso", "ArnoldiMethodTransformations", "BandwidthBenchmark", "GeoIP", "RegressionDynamicCausalModeling", "SmallCombinatorics", "Hamburg", "InMemoryDatasets", "LongDatasetSort", "PositiveIntegrators", "CxxWrap", "CartesianJoin", "MDEStudy", "Pingouin", "PowerNetworkMatrices", "SurveyDataWeighting", "CountingChambers", "ModeCouplingTheory", "ParticleInCell", "TruncatedMVN", "SkeelBerzins", "DLMReader", "AlgebraicMultigrid", "PowerFlows", "DiffEqGPU", "OrdinaryDiffEqExtrapolation", "AsapOptim", "StatisticalGraphics", "GLM", "BytePairEncoding", "AMGCLWrap", "GAP", "OrdinaryDiffEqExponentialRK", "OrdinaryDiffEqNonlinearSolve", "SteadyWaves", "Bcube", "SimpleImplicitDiscreteSolve", "BoundaryValueDiffEqAscher", "BoundaryValueDiffEqCore", "VortexStepMethod", "MusicProcessing", "OrdinaryDiffEqDefault", "OrdinaryDiffEqPDIRK", "DiffEqPhysics", "BcubeVTK", "OrdinaryDiffEqIMEXMultistep", "OrdinaryDiffEqSDIRK", "OrdinaryDiffEqFIRK", "OrdinaryDiffEqStabilizedIRK", "OrdinaryDiffEqBDF", "Omniscape", "PowerSimulationsDynamics", "BoundaryValueDiffEqMIRKN", "BoundaryValueDiffEqShooting", "FerriteMultigrid", "BcubeCGNS", "BoundaryValueDiffEqMIRK", "MAiNGO", "GModelFit", "DecomposingPolynomialSystems", "ProbNumDiffEq", "VoronoiFVM", "GroebnerWalk", "GModelFitViewer", "BcubeGmsh", "PowerSimulations", "PeriodicOrbits", "Einstein", "Circuitscape", "ONSAS", "Fortuna", "LiquidElectrolytes", "MGVI", "GenericCharacterTables", "MatterPower", "Trebuchet", "DiffEqFinancial", "HydroPowerSimulations", "NBodySimulator", "StorageSystemsSimulations", "PowerAnalytics", "Consensus", "Tapestree", "Globtim", "Yunir", "QSFit", "IonSim", "SphericalClusterMass", "QuantumCumulants", "Biofilm", "QuantumDynamics", "MixedComplementarityProblems", "KinematicDriver", "GalacticPotentials", "Octofitter", "OctofitterRadialVelocity", "SpectralDistances"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/59165#issuecomment-3363963266) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b251dac_vs_067b013/report.html) is available.

<details><summary>Report summary</summary>

## ✖ Packages that failed

**24 packages failed only on the current version.**

 - Package fails to precompile: 15 packages
 - Illegal method overwrites during precompilation: 1 packages
 - Package tests unexpectedly errored: 7 packages
 - Test duration exceeded the time limit: 1 packages

74 packages failed on the previous version too.

## ✔ Packages that passed tests

**1 packages passed tests only on the current version.**

 - Other: 1 packages


## ➖ Packages that were skipped altogether

4 packages were skipped on the previous version too.



</details>

**Comment by oscardssmith** [comment]
Is there a reason this needs backporting?

**Comment by vtjnash** [comment]
@nanosoldier `runtests(["CGcoefficient", "Walsh", "Spinnaker", "Pardiso", "ArnoldiMethodTransformations", "GeoIP", "SmallCombinatorics", "Hamburg", "LongDatasetSort", "CxxWrap", "CartesianJoin", "Pingouin", "DLMReader", "StatisticalGraphics", "BytePairEncoding", "GLM", "AMGCLWrap", "GAP", "SteadyWaves", "DecomposingPolynomialSystems", "MAiNGO", "GenericCharacterTables", "ONSAS", "Globtim"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/59165#issuecomment-3377951858) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/159a24f_vs_e8667fb/report.html) is available.

<details><summary>Report summary</summary>

## ✖ Packages that failed

**15 packages failed only on the current version.**

 - Package tests unexpectedly errored: 14 packages
 - There were unidentified errors: 1 packages

9 packages failed on the previous version too.



</details>

**Comment by vtjnash** [comment]
Good. Now only the desired (ambiguous or unexpected method call) failures. And about half are just from having a dependency on a failing package (e.g. because they pinned to an old version of LinearSolve), so fixing those half will fix the rest.
```
Package tests unexpectedly errored: 14 packages
Package	Version	Primary	Against	History (9-7 to 10-6)
CxxWrap	v0.17.3	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
AMGCLWrap	v2.1.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
Pardiso	v1.1.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
GAP	v0.15.3	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
Spinnaker	v1.2.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
ArnoldiMethodTransformations	v0.1.3	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
CGcoefficient	v0.3.3	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
Walsh	v0.1.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
SmallCombinatorics	v0.1.1	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
DecomposingPolynomialSystems	v1.0.1	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
SteadyWaves	v1.1.1	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
Globtim	v0.1.3	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
MAiNGO	v0.2.2	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
GenericCharacterTables	v0.6.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▅
```

**Comment by lgoettgens** [comment]
@vtjnash Could you give any pointer how to fix the nanosoldier failures? I am currently looking into GAP.jl, which, according to the log, fails around https://github.com/oscar-system/GAP.jl/blob/f50b8d0473cf13f196a9a90507614215692dc772/src/ccalls.jl#L21
However, there is no use of `ccall` in that function. All places use `@ccall` which (if I understand the initial description correctly) shouldn't be affected by this change at all.

cc @fingolfin

**Comment by vtjnash** [comment]
Function calls (JuliaInterface_path()) was an experimental feature we introduced a couple years ago, but it never really worked correctly, and then we replaced it with LazyLibraries (overloads of Libdl.dlopen). So switch to LazyLibraries (or roll your own with dlopen overloads on your own lazy library like type). I can send along a PR if you remind me next week.

**Comment by lgoettgens** [comment]
Since this is marked as a "minor change" and it seems to break some packages in practice (like CxxWrap and a few other ones mentioned in https://github.com/JuliaLang/julia/pull/59165#issuecomment-3383250920), I don't think this should be backported to 1.12.
Backporting this would require the above mentioned packages to be adapted and released before julia 1.12.1 gets released.

cc @KristofferC

**Comment by fingolfin** [comment]
So, wait... are you saying this PR now broke CxxWrap, and the 50+ packages depending on it, without any warning there (e.g. at least an issue that something has to be changed, with some hint as to what)?

That seems... suboptimal?

**Comment by vtjnash** [comment]
PkgEval only identified a bug in the CxxWrap tests (https://github.com/JuliaInterop/CxxWrap.jl/blob/ece5014a34f2c9434ad714ebf7e7fa2238c523ed/test/functions.jl#L246) and not in the package itself (so no dependencies were noted in PkgEval runs)

**Comment by fingolfin** [comment]
> Function calls (JuliaInterface_path()) was an experimental feature we introduced a couple years ago, but it never really worked correctly, and then we replaced it with LazyLibraries (overloads of Libdl.dlopen). So switch to LazyLibraries (or roll your own with dlopen overloads on your own lazy library like type). I can send along a PR if you remind me next week.

Huh, what? So looking at [the Julia manual, it says](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Non-constant-Function-Specifications):

> In some cases, the exact name or path of the needed library is not known in advance and must be computed at run time. To handle such cases, the library component specification can be a function call, e.g. find_blas().dgemm. The call expression will be executed when the ccall itself is executed. However, it is assumed that the library location does not change once it is determined, so the result of the call can be cached and reused. Therefore, the number of times the expression executes is unspecified, and returning different values for multiple calls results in unspecified behavior.

Is this the same feature we are talking about? Because the one I am quoting describes pretty much what we use in GAP.jl as far as I can tell, and I don't see any references about it being "experimental". What am I missing?

**Comment by vtjnash** [comment]
Yes, it wasn't intended to be experimental, but it never worked correctly, and only a couple packages started attempting to use it (GAP being the main one). We replaced it almost immediately after attempting to introduce it with LazyLibraries, but hadn't fixed up any of the old code to error reliably, so it would just crash sometimes instead. This just makes the error path reliable.

**Comment by vtjnash** [comment]
You didn't need this whole PR, and shouldn't have ever really needed it, you just needed to remove the `const` from that line to be both forward and backwards compatible: https://github.com/oscar-system/GAP.jl/pull/743

**Comment by lgoettgens** [comment]
> So switch to LazyLibraries (or roll your own with dlopen overloads on your own lazy library like type).

`Libdl.LazyLibrary` seems to be very sparingly documented, it does have a short docstring, but it is not mentioned anywhere else in the manual. I would have expected it to be mentioned at https://docs.julialang.org/en/v1.13-dev/stdlib/Libdl/



> I can send along a PR if you remind me next week.

For GAP.jl, I already have a draft PR at https://github.com/oscar-system/GAP.jl/pull/1267 where it would be great to hear your feedback. 
But I am certain that @barche would be very happy if you send them a fix for CxxWrap.

**Comment by fingolfin** [comment]
> Yes, it wasn't intended to be experimental, but it never worked correctly, and only a couple packages started attempting to use it (GAP being the main one). We replaced it almost immediately after attempting to introduce it with LazyLibraries, but hadn't fixed up any of the old code to error reliably, so it would just crash sometimes instead. This just makes the error path reliable.

Well, it did work well for GAP, at least. And while you are right, *working* code could have been had easier, this was based on measuring code performance.

Anyway, we'll deal with it somehow.

BTW at the top you wrote 
> `@ccall` macro has even always enforced that

which I don't understand, because we have been and are using `@ccall` and got no warning from that either? Am I misunderstanding this somehow?

---

But what riles me up about this is the way it was handled: a feature was added years ago to Julia, and documented, with no hint of it being experimental. Then apparently issues were found and it now is being yanked. This is a breaking change. While I understand it may be necessary, I also think such a thing should then always be communicated very clearly, in particular:
- a prominent note in the NEWS that the feature was removed due to unresolvable issues (and because hardly anyone uses it)
- a hint what to do instead, and possibly an offer to help people migrate away from it
- if things like `LazyLibraries` are mentioned as a possible solution, some more info as to what that even is / where to learn more about it should be included. As it is, I just searched the Julia docs, grepped the Julia git repo, and did a web search for "julia LazyLibraries"; the only hit I found was to <https://docs.julialang.org/en/v1/NEWS/> which did not mention it, but I then figured out I had to manually switch to the 1.11 version; that then made me realize I need to search for `LazyLibrary`. That then produced a single hit in the Julia documentation, to <https://docs.julialang.org/en/v1.12/devdocs/locks/> (??). But at least it made me realize it is something in `Libdl`, so I went to https://docs.julialang.org/en/v1.12/stdlib/Libdl/ but it is not mentioned there either. So back to looking at the Julia git repo, and ahh, there is a docstring `Libdl.LazyLibrary`. But since it is not in the Julia manual, I have to assume *this* now is an experimental feature...

So, again: I can live with this change, but I really think this kind of communication breakdown is a good example for why Julia sometimes gets a bad rep on HackerNews :-(.

Foremost, I'd suggest to avoid any hints or implications that it is somehow the user's fault for using this supposed "experimental" feature, which was actually documented as a regular feature, or blame for using a barely documented supposed "replacement" feature.

**Comment by vtjnash** [comment]
I hesitated to mention it too much in NEWS, since it was just a couple packages that had started to use it, so it wasn't broadly applicable to all audiences. I apologize for not being more proactive to let you guys know what changes to expect.

I didn't realize LazyLibraries hadn't gotten more than a passing mention in the documentation. Hopefully this should help address that deficiency: https://github.com/JuliaLang/julia/pull/59841
