### PR TITLE
“Fix” #53451 -- allow zero-row QR factorization bypassing LAPACK

### LINKED ISSUE #1054: Allow QR decomposition for zero-row matrices.
This came up in https://github.com/DynareJulia/FastLapackInterface.jl/issues/39

Currently, Julia allows for QR decomposition of zero-column matrices by skipping the call to LAPACK with a simple conditional [in this line].(https://github.com/JuliaLang/julia/blob/923fe2d74d469d73f0285a9cd41c88f90edd04d1/stdlib/LinearAlgebra/src/lapack.jl#L456)

Zero-row matrices are not supported and give an argument error:
```julia
 LA.qr(zeros(0, 10))
```
```
 ** On entry to DGEQRT parameter number  3 had an illegal value
ERROR: ArgumentError: invalid argument JuliaLang/julia#3 to LAPACK call
```

Is there a reason for this?
The data type should support these matrices:
```julia
import LinearAlgebra as LA
A = Matrix{Float64}(undef, 0, 10)
T = Matrix{Float64}(undef, 0, 0)
qr = LA.QRCompactWY(A, T)
```
and `qr` is as I would expect it.

### LINKED ISSUE #53451: Allow QR decomposition for zero-row matrices.
This came up in https://github.com/DynareJulia/FastLapackInterface.jl/issues/39

Currently, Julia allows for QR decomposition of zero-column matrices by skipping the call to LAPACK with a simple conditional [in this line].(https://github.com/JuliaLang/julia/blob/923fe2d74d469d73f0285a9cd41c88f90edd04d1/stdlib/LinearAlgebra/src/lapack.jl#L456)

Zero-row matrices are not supported and give an argument error:
```julia
 LA.qr(zeros(0, 10))
```
```
 ** On entry to DGEQRT parameter number  3 had an illegal value
ERROR: ArgumentError: invalid argument #3 to LAPACK call
```

Is there a reason for this?
The data type should support these matrices:
```julia
import LinearAlgebra as LA
A = Matrix{Float64}(undef, 0, 10)
T = Matrix{Float64}(undef, 0, 0)
qr = LA.QRCompactWY(A, T)
```
and `qr` is as I would expect it.

### PR DESCRIPTION
**Pull request by manuelbb-upb**
This is a very simple fix for JuliaLang/LinearAlgebra.jl#1054, allowing for QR factorizations of zero-row matrices by bypassing LAPACK in case *any* matrix dimension is positive.
A few unit tests check both zero-column and zero-row matrices (including 0x0) for all relevant data types.

Built from source the tests seem to pass alright.

Fixes JuliaLang/LinearAlgebra.jl#1054.

### CODE REVIEW

File: stdlib/LinearAlgebra/test/qr.jl [hunk 1]
```diff
@@ -504,4 +504,28 @@ end
...
 end
 
+@testset "issue #53451" begin
+    # in the issue it was noted that QR factorizations of zero-column matrices
+    # were possible, but zero row-matrices errored, because LAPACK does not
+    # accept these empty matrices. now, the `geqrt!` call should be forwarded only
+    # if both matrix dimensions are positive.
+
+    for dimA in (0, 1, 2, 4)
+        for F in (Float32, Float64, ComplexF32, ComplexF64)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/qr.jl:514]: I believe we also have generic `qr` methods, in which case which you could test for this edge case behavior with `BigFloat`, for instance?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/test/qr.jl:514]: Aha, yes, at least `qr` works for `F = BigFloat`:

```suggestion
        for F in (Float32, Float64, ComplexF32, ComplexF64, BigFloat)
```

**Comment by dkarrasch** [comment]
The newly added tests pass also in the failing windows run, so I'm merging this.
