### PR TITLE
fix less on windows

### LINKED ISSUE #17872: Wrong paths for `less` on windows
```
julia> less(sin,(Int64,))
ERROR: could not spawn `less +139g 'C:\Users\XXX\AppData\Local\Julia-0.4.6\bin\../share\julia\base\math.jl'`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
```
Note the forward slash in `../share`

### PR DESCRIPTION
**Pull request by pfitzseb**
by using `more` as the default and escaping `file`.

More concise implementation would be something like 

``` julia
function less(file::AbstractString, line::Integer)
    default = is_windows() ? "more" : "less"
    pager = get(ENV, "PAGER", default)
    g = is_windows() && pager == "more" ? "" : "g"
    run(Cmd(`$pager +$(line)$g \"$file\"`, windows_verbatim = true)
end
```

but I dunno if escaping `file` with `\"` does something bad on non-windows OSs.

Fixes #17872.

### CODE REVIEW

File: base/interactiveutil.jl [hunk 1]
```diff
@@ -70,9 +70,17 @@ edit(file, line::Integer) = error("could not find source file for function")
...
 # terminal pager
 
-function less(file::AbstractString, line::Integer)
-    pager = get(ENV, "PAGER", "less")
-    run(`$pager +$(line)g $file`)
+if is_windows()
+    function less(file::AbstractString, line::Integer)
+        pager = get(ENV, "PAGER", "more")
+        g = pager == "more" ? "" : "g"
+        run(Cmd(`$pager +$(line)$(g) \"$file\"`, windows_verbatim = true))
```
Comment (tkelman) [inline base/interactiveutil.jl]: is `windows_verbatim` needed for pagers other than `more` ?

**Comment by tkelman** [comment]
> I dunno if escaping `file` with `\"` does something bad on non-windows OSs.

I highly doubt it would? If `Cmd` interpolation didn't already do the right thing with paths-with-spaces, it might even help. It looks like with gnu `less` you can leave off the `g` if you give a line number with `+`, but maybe the BSD version of `less` doesn't do that?

**Comment by pfitzseb** [comment]
Just noticed: The manual escaping in this PR would be unnecessary if [this line](https://github.com/JuliaLang/julia/blob/6b5a05eb1a029aef93f77b60bb1d745c7d6e1d8d/base/shell.jl#L145) were changed so that we escape with `"` on Windows (`'` doesn't do anything).

**Comment by tkelman** [comment]
I've noticed that inconsistency a few times, but I'm not sure whether that function is used for more than just display of `Cmd` objects.

File: base/interactiveutil.jl (hunk 1 above)
Comment (pfitzseb) [inline base/interactiveutil.jl]: The escaping won't work without, I think. See below for a (possibly) nicer fix though.

**Comment by pfitzseb** [comment]
Ah, right, it isn't. Too bad. We can't do the escaping automatically anyways since there may be spaces in paths...

**Comment by pfitzseb** [comment]
> It looks like with GNU less you can leave off the g if you give a line number with +, but maybe the BSD version of less doesn't do that?

Yeah, that'd [work there as well](http://www.freebsd.org/cgi/man.cgi?query=less).

Gotta go now though, I'll update this PR (`\"` escaping and no `g` everywhere) when I'm back if no one beats me to it.

**Comment by tkelman** [comment]
> less is part of the GNU project and is free software.

So FreeBSD uses GNU less? Hm, what about on Macs?

**Comment by vtjnash** [comment]
> I dunno if escaping file with \" does something bad on non-windows OSs.

yes, that would cause it to try to open a filename with quotes in the name. there is no escaping of strings in execv on non-Windows OS's – the argv is passed through directly as an array.
