### PR TITLE
Concatenation with UniformScaling and numbers

### LINKED ISSUE #666: Concatenation with I (UniformScaling) fails with numbers
This works:

```julia
julia> [I     [2,3]
        [4 5] [6]]
3×3 Array{Int64,2}:
 1  0  2
 0  1  3
 4  5  6
```

And this works:

```julia
julia> [[1 0; 0 1] [2,3]
        [4 5]      6]
3×3 Array{Int64,2}:
 1  0  2
 0  1  3
 4  5  6
```

But this fails:
```julia
julia> [I     [2,3]
        [4 5] 6]
ERROR: DimensionMismatch("mismatch in dimension 1 (expected 1 got 2)")
Stacktrace:
 [1] cat_shape(::Tuple{Bool,Bool}, ::Tuple{}, ::Tuple{Int64}, ::Tuple{Int64}) at ./abstractarray.jl:1421
 [2] _cat_t(::Val{2}, ::Type, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1441
 [3] #cat_t#103(::Val{2}, ::typeof(Base.cat_t), ::Type{Any}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1438
 [4] (::Base.var"#kw##cat_t")(::NamedTuple{(:dims,),Tuple{Val{2}}}, ::typeof(Base.cat_t), ::Type{Any}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./none:0
 [5] typed_hcat(::Type, ::UniformScaling{Bool}, ::Array{Int64,1}) at ./abstractarray.jl:1548
 [6] typed_hvcat(::Type{Any}, ::Tuple{Int64,Int64}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1738
 [7] hvcat(::Tuple{Int64,Int64}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1716
 [8] top-level scope at REPL[42]:1
````

### LINKED ISSUE #33343: Concatenation with I (UniformScaling) fails with numbers
This works:

```julia
julia> [I     [2,3]
        [4 5] [6]]
3×3 Array{Int64,2}:
 1  0  2
 0  1  3
 4  5  6
```

And this works:

```julia
julia> [[1 0; 0 1] [2,3]
        [4 5]      6]
3×3 Array{Int64,2}:
 1  0  2
 0  1  3
 4  5  6
```

But this fails:
```julia
julia> [I     [2,3]
        [4 5] 6]
ERROR: DimensionMismatch("mismatch in dimension 1 (expected 1 got 2)")
Stacktrace:
 [1] cat_shape(::Tuple{Bool,Bool}, ::Tuple{}, ::Tuple{Int64}, ::Tuple{Int64}) at ./abstractarray.jl:1421
 [2] _cat_t(::Val{2}, ::Type, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1441
 [3] #cat_t#103(::Val{2}, ::typeof(Base.cat_t), ::Type{Any}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1438
 [4] (::Base.var"#kw##cat_t")(::NamedTuple{(:dims,),Tuple{Val{2}}}, ::typeof(Base.cat_t), ::Type{Any}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./none:0
 [5] typed_hcat(::Type, ::UniformScaling{Bool}, ::Array{Int64,1}) at ./abstractarray.jl:1548
 [6] typed_hvcat(::Type{Any}, ::Tuple{Int64,Int64}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1738
 [7] hvcat(::Tuple{Int64,Int64}, ::UniformScaling{Bool}, ::Vararg{Any,N} where N) at ./abstractarray.jl:1716
 [8] top-level scope at REPL[42]:1
````

### PR DESCRIPTION
**Pull request by dkarrasch**
Rebase of  JuliaLang/julia#33363.

This allows to concatenate matrices, numbers and uniform scalings.

Fixes JuliaLang/LinearAlgebra.jl#666. Closes  JuliaLang/julia#33363.

### CODE REVIEW

File: stdlib/LinearAlgebra/src/uniformscaling.jl [hunk 1]
```diff
@@ -467,16 +468,22 @@ function hvcat(rows::Tuple{Vararg{Int}}, A::Union{AbstractVecOrMat,UniformScalin
...
                     n[j+k] = nci
                 end
             end
             j += rows[i]
         end
     end
-    return hvcat(rows, promote_to_arrays(n,1, promote_to_array_type(A), A...)...)
+    Atyp = promote_to_array_type(A)
+    Amat = promote_to_arrays(n, 1, Atyp, A...)
+    if Atyp == Matrix
```
Comment (stevengj) [inline stdlib/LinearAlgebra/src/uniformscaling.jl:482]: `<: AbstractMatrix`?

File: stdlib/SparseArrays/src/sparsevector.jl [hunk 2]
```diff
@@ -1083,23 +1083,26 @@ const _Triangular_DenseArrays{T,A<:Matrix} = LinearAlgebra.AbstractTriangular{T,
 const _Annotated_DenseArrays = Union{_Triangular_DenseArrays, _Symmetric_DenseArrays, _Hermitian_DenseArrays}
 const _Annotated_Typed_DenseArrays{T} = Union{_Triangular_DenseArrays{T}, _Symmetric_DenseArrays{T}, _Hermitian_DenseArrays{T}}
 
-const _SparseConcatGroup = Union{Vector, Adjoint{<:Any,<:Vector}, Transpose{<:Any,<:Vector}, Matrix, _SparseConcatArrays, _Annotated_SparseConcatArrays, _Annotated_DenseArrays}
-const _DenseConcatGroup = Union{Vector, Adjoint{<:Any,<:Vector}, Transpose{<:Any,<:Vector}, Matrix, _Annotated_DenseArrays}
+const _SparseConcatGroup = Union{Number, Vector, Adjoint{<:Any,<:Vector}, Transpose{<:Any,<:Vector}, Matrix, _SparseConcatArrays, _Annotated_SparseConcatArrays, _Annotated_DenseArrays}
+const _DenseConcatGroup = Union{Number, Vector, Adjoint{<:Any,<:Vector}, Transpose{<:Any,<:Vector}, Matrix, _Annotated_DenseArrays}
```
Comment (stevengj) [inline stdlib/SparseArrays/src/sparsevector.jl:1087]: Should we have a test for the sparse case?

File: stdlib/LinearAlgebra/src/uniformscaling.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/uniformscaling.jl:482]: I don't think so. We have two methods for `promote_to_array_type`, one returning `Matrix` (see the new line 405 above) and another one returning `SparseMatrixCSC` (in SparseArrays.jl). In the dense case, we cannot call `hvcat` for the promoted `UniformScaling`s because this causes a stack overflow. In the sparse case, however, we cannot call `typed_hvcat` because we need a sparse output. Should I add a comment to explain that?

File: stdlib/SparseArrays/src/sparsevector.jl (hunk 2 above)
Comment (dkarrasch) [reply stdlib/SparseArrays/src/sparsevector.jl:1087]: The `*cat` tests are run both for dense and sparse arrays (the `T` in the type assertions). So there are tests for concatenation with (sparse) arrays, uniform scalings and numbers. Is that what you mean?

File: stdlib/LinearAlgebra/src/uniformscaling.jl (hunk 1 above)
Comment (stevengj) [reply stdlib/LinearAlgebra/src/uniformscaling.jl:482]: A comment would be good.

Comment (vtjnash) [reply stdlib/LinearAlgebra/src/uniformscaling.jl:482]:
```suggestion
    # We have two methods for promote_to_array_type, one returning Matrix and
    # another one returning SparseMatrixCSC (in SparseArrays.jl). In the dense
    # case, we cannot call hvcat for the promoted UniformScalings because this
    # causes a stack overflow. In the sparse case, however, we cannot call
    # typed_hvcat because we need a sparse output.
    if Atyp == Matrix
```

**Review by vtjnash — APPROVED** [review]
I made your comment into a suggestion. If you approve/commit that, I think we can immediately merge (i.e. add the merge-me tag)

**Comment by JeffBezanson** [comment]
Interestingly (for the type system), this made the humble call `methods(hvcat, (Tuple{Int,Int},Any,Any,Any,Any,Any,Any,Int,Int))` take >50 seconds, which also affects some compile times.

**Comment by dkarrasch** [comment]
@JeffBezanson So how do we handle this slowdown? #41511 is a small PR on top of this one to avoid method ambiguities. Are we going to keep this one here and try to improve it or revert it and tackle the issue from scratch with latency checks included?
