### PR TITLE
optimize and fix map/broadcast over Adjoint/Transpose vectors, take 2

### LINKED ISSUE #492: eliminate temporary in map/broadcast over Adjoint/Tranpose-wrapped vectors
Leaving this breadcrumb to https://github.com/JuliaLang/julia/pull/25083#discussion_r157332474 so that I do not forget to incorporate `@timholy`'s great optimization suggestion. Best!

### LINKED ISSUE #25134: eliminate temporary in map/broadcast over Adjoint/Tranpose-wrapped vectors
Leaving this breadcrumb to https://github.com/JuliaLang/julia/pull/25083#discussion_r157332474 so that I do not forget to incorporate `@timholy`'s great optimization suggestion. Best!

### PR DESCRIPTION
**Pull request by Sacha0**
Second take on JuliaLang/julia#25219: This pull request implements the optimization @timholy suggested in https://github.com/JuliaLang/julia/pull/25083#discussion_r157302172 (hence closes JuliaLang/LinearAlgebra.jl#492) and fixes the inference issue @martinholters caught in https://github.com/JuliaLang/julia/pull/25083#issuecomment-353031641. This version addresses the linalg/dense test failures discovered in JuliaLang/julia#25219 as well, and adds a couple direct tests for that issue to linalg/adjtrans. Thanks and best!

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by Sacha0** [comment]
Absent objections or requests for time, I plan to merge these changes midday tomorrow PT at the earliest. Thanks all!

File: base/linalg/adjtrans.jl [hunk 1]
```diff
@@ -136,30 +136,15 @@ hcat(tvs::Transpose{T,Vector{T}}...) where {T} = _transpose_hcat(tvs...)
...
-map(f, tvs::TransposeAbsVec...) = Transpose(map(Transpose∘f, vectorfyall(tvs...)...))
-
-# broadcast over collections of Adjoint/Transpose-wrapped vectors and numbers
-# similar explanation for these definitions as for map above
-broadcast(f, avs::Union{Number,AdjointAbsVec}...) = Adjoint(broadcast(Adjoint∘f, vectorfyall(avs...)...))
-broadcast(f, tvs::Union{Number,TransposeAbsVec}...) = Transpose(broadcast(Transpose∘f, vectorfyall(tvs...) ...))
+#
+# note that the caller's operation f operates in the domain of the wrapped vectors' entries.
+# hence the Adjoint->f->Adjoint shenanigans applied to the parent vectors' entries.
+map(f, avs::AdjointAbsVec...) = Adjoint(map((xs...) -> Adjoint(f(Adjoint.(xs)...)), parent.(avs)...))
```
Comment (timholy) [inline base/linalg/adjtrans.jl]: given recent discussions shouldn't this be `adjoint.(xs)...`?

Comment (Sacha0) [reply base/linalg/adjtrans.jl]: Absolutely, given recent discussion these calls should eventually become `adjoint`/`transpose` :). That said, with master as it stands, `Adjoint`/`Transpose` are correct, whereas I am not entirely confident that `adjoint`/`transpose` are correct and will remain correct through the few remaining pull requests in the #5332 series. After those remaining pull requests in the #5332 series, changing these calls to `adjoint`/`transpose` should become correct with certainty. Thoughts? :) Thanks!

**Comment by Sacha0** [comment]
Absent further commentary I plan to merge this change tomorrow morning PT or later. Best!

File: base/linalg/adjtrans.jl (hunk 1 above)
Comment (timholy) [reply base/linalg/adjtrans.jl]: As long as this is an intermediate state, I'm fine with it.

Comment (Sacha0) [reply base/linalg/adjtrans.jl]: With a bit more thought, writing these methods in `Adjoint`/`Transpose` may also be ultimately best: The relevant objects are `<:AbstractVector`, and as such `Adjoint`/`Transpose`-wrapping is correct, precise, and unambiguous  (whereas `adjoint`/`transpose` will be more nebulous). Best!

**Comment by Sacha0** [comment]
Thanks all! :)
