### PR TITLE
Make Memory{T} respect the max alignment of the heap

### LINKED ISSUE #53683: vecelement test fails on Zen4
```
keno@demeter1:~/julia$ make test-vecelement 
Whitespace check found no issues.
    JULIA test/vecelement
Running parallel tests with:
  getpid() = 1386043
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 64
  Sys.total_memory() = 755.645 GiB
  Sys.free_memory() = 745.864 GiB

Test   (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
vecelement  (1) |        started at 2024-03-09T23:02:36.957

[1386043] signal 11 (128): Segmentation fault
in expression starting at /home/keno/julia/test/vecelement.jl:113
f20961 at /home/keno/julia/test/vecelement.jl:0
unknown function (ip: 0x7fdd57964b4f)
jl_apply at /home/keno/julia/src/julia.h:2166 [inlined]
do_call at /home/keno/julia/src/interpreter.c:126
eval_value at /home/keno/julia/src/interpreter.c:223
eval_body at /home/keno/julia/src/interpreter.c:560
jl_interpret_toplevel_thunk at /home/keno/julia/src/interpreter.c:815
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:943
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:886
ijl_toplevel_eval_in at /home/keno/julia/src/toplevel.c:994
eval at ./boot.jl:428 [inlined]
include_string at ./loading.jl:2249
_include at ./loading.jl:2309
include at ./Base.jl:556 [inlined]
```
Since it's not failing on CI, I'm assuming it's microarchitecture specific. My hardware is:
```
processor	: 63
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 17
model name	: AMD EPYC 9354 32-Core Processor
stepping	: 1
microcode	: 0xa10113e
cpu MHz		: 1500.000
cache size	: 1024 KB
```
Bisect says:
```
8db129472ea88a9c5c4a6e94dff7b330723aed28 is the first bad commit
commit 8db129472ea88a9c5c4a6e94dff7b330723aed28
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Sun Feb 4 19:51:02 2024 -0500

    add atomic operators for globals, memory, and setonce (#52868)
```

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes https://github.com/JuliaLang/julia/issues/53683

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
Could you add a test for `code_llvm(optimize=false)` to check for the string align 16 and not align 64?

File: test/vecelement.jl [hunk 1]
```diff
@@ -120,3 +120,9 @@ for T in (Float64, Float32, Int64, Int32)
         @test b == result
     end
 end
+@testset "vecelement overalignment" begin
```
Comment (vchuravy) [inline test/vecelement.jl:123]: I do think those kinds of test are better for llvmpasses, 
since it is easy to match the wrong align here.

Comment (gbaraldi) [reply test/vecelement.jl:123]: Any suggestions?
