### PR TITLE
Probe and dlopen() the correct libstdc++

### LINKED ISSUE #198: Julia loading Julia's libstdc++ instead of system, causes inscrutable errors
Hi,
GLFW.jl is affected by the outdated libstdc++ issue. It's a problem that has been affecting several projects and has been documented in [at least one Discourse thread](https://discourse.julialang.org/t/glibcxx-3-4-26-not-found-in-rcall/29113/11). What happens is that Julia ships with an old version of libstdc++, and something in the linking process fails on systems that expect a newer version of libstdc++. If you run a GLFW.jl function with the `LIBGL_DEBUG=verbose` environment variable set, you get an error message like `libGL: MESA-LOADER: failed to open /usr/lib/dri/radeonsi_dri.so: /home/alex/pkgs/julia-1.3.0/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/libLLVM-9.so)`. The libstdc++ shipped with Julia 1.3 is version 3.4.24. 

[There's an open issue on the main Julia repo](https://github.com/JuliaLang/julia/issues/34276). Other packages like RCall have been adding notices in their docs with workarounds in the meantime. The error message GLFW.jl gives right now is especially lacking. Without the `LIGBL_DEBUG=verbose`, on my machine it is:
```Julia
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
ERROR: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: BadValue
Stacktrace:
 [1] _ErrorCallbackWrapper(::Int32, ::Cstring) at /home/alex/.julia/packages/GLFW/g1nX6/src/callback.jl:43
 [2] CreateWindow(::Int64, ::Int64, ::String, ::GLFW.Monitor, ::GLFW.Window) at /home/alex/.julia/packages/GLFW/g1nX6/src/glfw3.jl:487 (repeats 2 times)
 [3] top-level scope at REPL[3]:1
``` 
The workaround right now is to:
1) Delete `julia-1.3.0/lib/julia/libstdc++.so.6`
2) Find the system libstdc++ with `whereis libstdc++`
3) Link that location to `julia-1.3.0/lib/julia-libstdc++.so.6` using `ln`.

I think it'd be worthwhile to put a notice up on the README that this issue is occurring. I encountered the problem while trying to use Makie, and this repo was one of the first places I went to debug it since the error comes from this library. It's probably worthwhile to put a notice up in Makie too.

### LINKED ISSUE #205: Make libstdc++ loading more reliable
We currently load the libstdc++ we ship from rpath, which is usually fine. It isn't fine when the system's libstdc++ is newer than ours, and a system lib needs the newer symbols, which leads to errors.
To fix that there needs to be some way that checks the systems libstdc++ and ,if it's newer than ours, load it instead. 

Some ideas were put forward in the ci-dev call.

* remove it from the rpath and `dlopen` it. Check for some `GLIBCXX` version symbol and if it's there then load it. Otherwise `dlclose` it and load ours as usual (Probably the best)
* Do the same thing but on an external process if `dlclose` causes issues.

### LINKED ISSUE #34276: libstdc++.so.6 is outdated and breaks RCall and others on recent Linux distros
As discussed on slack with and discourse ( https://discourse.julialang.org/t/glibcxx-3-4-26-not-found-in-rcall/29113/2 ) the problem of an outdated, bundled libstdc++ (e.g. Julia 1.3.1) compared to the libstdc++ provided by the OS (e.g. Ubuntu 19.10) is that it breaks RCall.jl when `Rcpp` is in play due to missing GLIBCXX symbols.

I quote @staticfloat 

> So Ubuntu 19.10 is based on GCC 9, huh.  We don't have a GCC 9 shard yet; we've been using GCC 7.2 on the buildbots (which correspondes to GLIBCXX_3.4.24), but there's no reason why we can't put our own libstdc++.so.6 into a julia binary-dist.  Right now we've been bundling the libstdc++.so.6 that we get from the build environment, but it would be even better for us to just use an appropriate CompilerSupportLibraries_jll release, and craft those releases to be as compatible as possible (e.g. use the absolute newest libstdc++.so.6, the appropriate libgfortran.so.X, etc...)

An intermediate workaround is described here: https://discourse.julialang.org/t/glibcxx-3-4-26-not-found-in-rcall/29113/11?u=laborg

### PR DESCRIPTION
**Pull request by apaz-cli**
Fixes https://github.com/JuliaCI/julia-buildkite/issues/205
Fixes https://github.com/JuliaLang/julia/issues/34276
Fixes https://github.com/JuliaGL/GLFW.jl/issues/198

Initial implementation by @giordano 

To opt-out of the fix, set the `JULIA_PROBELIBSTDCXX` environment variable to `0`; e.g. `export JULIA_PROBELIBSTDCXX=0`.

TODO:
* [x] Move the `libstdcxx.so.6` that we ship off rpath
* [x] Load from the correct location when installed with `make install`
* [x] Is `LIBSTDCXXPROBE` a good name for the `#define` and `JULIA_PROBELIBSTDCXX` a good name for the environment variable?
* [x] Parse `CSL_NEXT_GLIBCXX_VERSION` for the symbol to extract and check for compatibility.

### CODE REVIEW

File: cli/loader_lib.c [hunk 1]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        ret = close(fork_pipe[0]);
+        if (ret == -1) exit(1);
+
+        // Open the first available libstdc++.so
+        handle = dlopen("libstdc++.so", RTLD_LAZY);
+        if (!handle) exit(0);
+
+        // See if the version is compatible
+        dlerr = dlerror(); // clear out dlerror
+        void* sym = dlsym(handle, "GLIBCXX_3.4.29");
```
Comment (giordano) [inline cli/loader_lib.c:188]: It'd nice to have a way to keep this in sync with https://github.com/JuliaLang/julia/blob/9fd408723aab0974f399b8ffc952af4b4d20b6f7/deps/csl.mk#L25 although it's a bit tricky because that refers to the next possible versions of libstdc++

File: cli/loader_lib.c [hunk 2]
```diff
@@ -163,6 +240,32 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+        size_t pathlen = 0;
+        if (!libstdcxxprobe(cxxpath, &pathlen)) {
+            jl_loader_print_stderr("ERROR: Syscalls failed while finding which libstdcxx path to load!\n");
+            exit(1);
+        }
+        handle = dlopen(cxxpath, RTLD_LAZY);
+        if (!handle) perror("dlopen"), exit(1);
+    }
+    else {
+        handle = dlopen("libstdc++.so.6", RTLD_LAZY);
```
Comment (giordano) [inline cli/loader_lib.c:264]: Should use `JL_DEFAULT_STDCXXLIB` here?

**Review by giordano — COMMENTED** [review]
Thanks for taking this over!

File: cli/loader_lib.c [hunk 3]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
     return lib_dir;
 }
 
+#ifdef LIBSTDCXXPROBE
+// Write the path to the libstdcxx to load to "path", which should be a buffer of at least
+// JL_PATH_MAX, and the length of that string (excluding null terminator) to "written"
+// Returns 1 on success or 0 on error, in which case the caller should abort the process.
+#define JL_DEFAULT_STDCXXLIB "libstdc++.so.6"
+static int libstdcxxprobe(char* path, size_t* written) {
```
Comment (vtjnash) [inline cli/loader_lib.c:162]: style nits
```suggestion
static int libstdcxxprobe(char *path, size_t *written)
{
```

File: cli/loader_lib.c [hunk 4]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+    // On Linux, it can happen that the system as a newer libstdc++ than the one we ship,
```
Comment (vtjnash) [inline cli/loader_lib.c:163]:
```suggestion
    // On Linux, it can happen that the system has a newer libstdc++ than the one we ship,
```

File: cli/loader_lib.c [hunk 5]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+
+    // Create the pipe and child process.
+    ret = pipe(fork_pipe);
+    if (ret == -1) return 0;
+    pid = fork();
+    if (pid == -1) return 0;
+
+    if (pid == (pid_t) 0) { // Child process.
+        ret = close(fork_pipe[0]);
+        if (ret == -1) exit(1);
```
Comment (vtjnash) [inline cli/loader_lib.c:180]: The child process must use `_exit(0)`
```suggestion
        if (ret == -1) _exit(1);
```

File: cli/loader_lib.c [hunk 6]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        // No error means the symbol was found, we can use this library/
+        // The symbol we just got is always NULL. Get another one that actually
+        // has an address so we can call dladdr() with it to get the path to the
+        // shared object it was loaded from. The symbol is arbitrary.
+        Dl_info info;
+        sym = dlsym(handle, "__gxx_personality_v0");
+        if (!sym) exit(1);
+        ret = dladdr(sym, &info);
+        if (ret == 0) exit(1);
+        ret = write(fork_pipe[1], info.dli_fname, strlen(info.dli_fname));
```
Comment (vtjnash) [inline cli/loader_lib.c:206]: this should loop until it is all written or the write returns -1 and errno != EAGAIN

File: cli/loader_lib.c [hunk 7]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        if (ret == -1) exit(1);
+        exit(0);
+    }
+    else { // Parent process.
+        close(fork_pipe[1]);
+        // Read the absolute path to the lib from the child process.
+        ssize_t have_read = read(fork_pipe[0], path, JL_PATH_MAX);
```
Comment (vtjnash) [inline cli/loader_lib.c:213]: this should loop until it returns 0, or returns -1 and errno is not EAGAIN

File: cli/loader_lib.c (hunk 1 above)
Comment (staticfloat) [reply cli/loader_lib.c:188]: We can take the first value, split it on periods, subtract one from the patch version and recombine. That’s doable in make

File: cli/loader_lib.c [hunk 8]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        if (have_read == -1) return 0;
+        path[have_read] = '\0';
+        *written = have_read;
+        if (access(path, F_OK) == -1) {
```
Comment (vtjnash) [inline cli/loader_lib.c:217]: If `path` is `JL_DEFAULT_STDCXXLIB`, this will always fail. Do we need this check? The system will eventually repeat the `R_OK | X_OK` check (though I am not sure of the exact flags), and the dlopen call will later just not open it.

File: cli/loader_lib.c [hunk 9]
```diff
@@ -163,6 +240,32 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
     // Introspect to find our own path
     const char * lib_dir = jl_get_libdir();
 
+#ifdef LIBSTDCXXPROBE
+    void* handle;
+    int do_probe = 1;
+    char* probevar = getenv("JLLIBSTDCXXPROBE");
```
Comment (vtjnash) [inline cli/loader_lib.c:246]: I think all of our env variables start with `JULIA_` currently

File: cli/loader_lib.c (hunk 2 above)
Comment (vtjnash) [inline cli/loader_lib.c:264]: @staticfloat is this the correct file that we want to load unconditionally in this case?

DRY nit:
```suggestion
        handle = dlopen(JL_DEFAULT_STDCXXLIB, RTLD_LAZY);
```

File: cli/loader_lib.c [hunk 10]
```diff
@@ -163,6 +240,32 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+            do_probe = 1;
+        else if (strcmp(probevar, "0") == 0 || strcmp(probevar, "no"))
+            do_probe = 0;
+    }
+    if (do_probe) {
+        char cxxpath[JL_PATH_MAX];
+        size_t pathlen = 0;
+        if (!libstdcxxprobe(cxxpath, &pathlen)) {
+            jl_loader_print_stderr("ERROR: Syscalls failed while finding which libstdcxx path to load!\n");
+            exit(1);
```
Comment (vtjnash) [inline cli/loader_lib.c:258]: It might be better to make each error site explicitly fail, or not to fail at all, than to have this cryptic error message

File: cli/Makefile [hunk 11]
```diff
@@ -12,6 +12,8 @@ LOADER_LDFLAGS = $(JLDFLAGS) -ffreestanding -L$(build_shlibdir) -L$(build_libdir
 
 ifeq ($(OS),WINNT)
 LOADER_CFLAGS += -municode -mconsole -nostdlib -fno-stack-check -fno-stack-protector -mno-stack-arg-probe
+else ifeq ($(OS),Linux)
+LOADER_CFLAGS += -DLIBSTDCXXPROBE
```
Comment (vtjnash) [inline cli/Makefile:16]: We typically use the existing `__linux__` define in the file, rather than adding this to the makefile. We can can try to add @ararslan (FreeBSD) to this too by making the detection more accurate also:
```suggestion
#ifndef LIBSTDCXXPROBE
#ifdef defined(__GLIBC__)
#define LIBSTDCXXPROBE 1
#elseif
#define LIBSTDCXXPROBE 0
#endif
#endif
```

File: cli/loader_lib.c (hunk 2 above)
Comment (apaz-cli) [reply cli/loader_lib.c:264]: Yes, definitely.

File: cli/Makefile (hunk 11 above)
Comment (ararslan) [reply cli/Makefile:16]: (I think the empty `#elseif` there should just be an `#else`)

Comment (giordano) [reply cli/Makefile:16]: #34276 is typically a problem only on Linux: there you can expect to have a new libstdc++ which system libraries may have been linked to.  I don't think this is the case on FreeBSD?

Comment (gbaraldi) [reply cli/Makefile:16]: I believe FreeBSD uses libcxx, libsdtc++ is only if a dep needs it.

File: cli/loader_lib.c (hunk 1 above)
Comment (ararslan) [reply cli/loader_lib.c:189]: Naively, I think you can do something like
```makefile
GLIBCXX_MAJOR := $(shell echo $(GLIBCXX_VERSION) | cut -d'.' -f1)
GLIBCXX_MINOR := $(shell echo $(GLIBCXX_VERSION) | cut -d'.' -f2)
GLIBCXX_PATCH := $(shell echo $(GLIBCXX_VERSION) | cut -d'.' -f3)
THING := $(GLIBCXX_MAJOR).$(GLIBCXX_MINOR).$(shell expr $(GLIBCXX_PATCH) - 1)
```

Comment (giordano) [reply cli/loader_lib.c:189]: Actually, I'm wondering if here we should actually search for the next version of GLIBCXX, instead of the current one, so that we can simply grab the first item of `CSL_NEXT_GLIBCXX_VERSION`.

File: cli/Makefile (hunk 11 above)
Comment (vtjnash) [reply cli/Makefile:16]: Ah, true. But checking if you are using glibc should be right in any case for deciding this, I think?

Comment (staticfloat) [reply cli/Makefile:16]: On second thought, yes, I think checking for `__GLIBC__` should work just fine.  I was the one who asked Aaron to make this into a Makefile define, because I figured we might need to do something more complicated than the C preprocessor can handle, and I also thought we might want a Makefile switch to disable this functionality permanently, but I think checking for `__GLIBC__` and also having a runtime environment variable escape hatch is sufficient.

File: cli/loader_lib.c (hunk 7 above)
Comment (apaz-cli) [reply cli/loader_lib.c:214]: Should `JL_PATH_MAX` be changed to actually be the `PATH_MAX` for the system (from `linux/limits.h`)? I brought it up with Mosè and Elliot, but we decided to not to immediately expand the scope of what we were doing.

File: cli/loader_lib.c (hunk 9 above)
Comment (DilumAluthge) [reply cli/loader_lib.c:247]: Yeah, it would be good to preserve that convention.

Also, all environment variables beginning with `JULIA_` will automatically show up in the output of `versioninfo(; verbose = true)`, which is useful,

File: cli/loader_lib.c [hunk 12]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
     return lib_dir;
 }
 
+#ifdef LIBSTDCXXPROBE
+// Write the path to the libstdcxx to load to "path", which should be a buffer of at least
+// JL_PATH_MAX, and the length of that string (excluding null terminator) to "written"
+// Returns 1 on success or 0 on error, in which case the caller should abort the process.
+#define JL_DEFAULT_STDCXXLIB "libstdc++.so.6"
```
Comment (staticfloat) [inline cli/loader_lib.c:161]: We need to calculate the path to the bundled `libstdc++.so` at runtime.  Let's make a function called `get_bundled_libstdcxx()` or something like that, and have it return the equivalent of `joinpath(jl_get_libdir(), "julia", "bundled", "libstdc++.so")`.  We can then alter the `libstdc++.so` installation rules to install to `lib/julia/bundled` instead of just `lib/`.

## `libstdc++` installation rules

There are two stages of `libstdc++` installation: there's where it lives after you've run `make` (and Julia lives in the build tree, in `usr/bin/julia`), and where it lives after `make install` (which is the portable binary installation).  I for one absolutely hate that there is a difference, I would much rather that `make` created a build tree that is identical to what gets shipped when you do `make install`, but, unfortunately, it's a big lift to properly unify things, and there are some good reasons (such as multiarch libdir layouts) for why it exists, so c'est la vie, I suppose).

### `make` time:

When you run `make`, we'll run the steps in [`deps/csl.mk`](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/deps/csl.mk) (which stands for Compiler Support Libraries), which will either [download a binary package](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/deps/csl.mk#L107) of standard libraries (snarfed from [CompilerSupportLibraries_jll](https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl)), or [steal the binaries from your current compilers](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/deps/csl.mk#L66), if you've opted to build everything locally.

To adjust this step, you need to redirect the `libstdc++` installation location.  For the from-source installation this is fairly simple; you need to replace [this invocation](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/deps/csl.mk#L66) with one that installs to that "bundled" directory (something like `$(build_private_shlibdir)/bundled`) instead of the main shared library directory.

For the bb install step, it's a little trickier, we want to basically move the `libstdc++` library after it's been unpacked from the downloaded tarball.  We can make a new makefile target called `$(build_private_shlibdir)/bundled/$(call versioned_libname,libstdc++,6)` that `install-csl` will depend on, and have that makefile target copy the library from where it usually sits to where it should actually sit.  And, of course, we only want to do this on glibc platforms.  ;)

### `make install` time

Since you've gone through the work of getting things set up correctly at `make` time, the `make install` time should be quite easy.  Remove `libstdc++` from [this list](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/Makefile#L213) which will try to copy it along with other libraries, and instead create a custom copy command [here](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/Makefile#L290) that copies the entire `bundled` directory over to `$(DESTDIR)$(private_libdir)`.

Currently, we [add `libstdc++` onto our `JL_PRIVATE_LIBS` list](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/Makefile#L213), but we want to avoid that, because [those all get installed to `lib`](https://github.com/JuliaLang/julia/blob/68632490a2ac52320734acbbbea6e3abc8bb2b3f/Makefile#L291-L297) and [then `lib/julia`]()

File: cli/Makefile (hunk 11 above)
Comment (staticfloat) [reply cli/Makefile:16]: Ah, that's a great point @giordano, I got confused between glibc and libstdc++.  You're right, it's not enough to check `__GLIBC__`, we need to basically check if our compiler is GCC and we're on Linux instead.

The alternative, of course, is to simply do this everywhere, since we do ship our own `libstdc++` everywhere.  That's not the end of the world, we just have to gracefully handle not finding a global `libstdc++`.

File: cli/loader_lib.c (hunk 1 above)
Comment (staticfloat) [reply cli/loader_lib.c:189]: Agreed; since we are not shipping the absolute latest libstdc++, we know that the first element of `CSL_NEXT_GLIBCXX_VERSION` exists, and is a good indication that we should use the system libstdc++.

File: cli/Makefile (hunk 11 above)
Comment (giordano) [reply cli/Makefile:16]: > we need to basically check if our compiler is GCC and we're on Linux instead.

I'd say only Linux, which is what I initially did: https://github.com/JuliaLang/julia/blob/ef1f5dc6751d4c302add4525f56bbdb04063448c/cli/loader_lib.c#L173-L176 :innocent:

We can build with Clang on Linux, but still have libstdc++ in the search path.

Comment (staticfloat) [reply cli/Makefile:16]: I thought there might be Linux distros that use clang/libcxx by default, but it appears there aren't any other than OpenMandriva.  I found these slides which are kind of a fun read: https://llvm.org/devmtg/2019-04/slides/TechTalk-Rosenkranzer-Switching_a_Linux_distro.pdf

That being said, yes, `_OS_LINUX_` should just be enough here for now.  :)

**Comment by staticfloat** [comment]
Also, to bikeshed the names of things a bit, I tend to prefer "verb-object" names where possible, so `PROBE_LIBSTDCXX`, rather than `LIBSTDCXXPROBE`, as the latter is somewhat ambiguous whether there is a library called `libstdcxxprobe.so` or whatnot.  This may be moot if we end up just using `_OS_LINUX_` guards, but it's useful nonetheless.

One thing that I'm not 100% happy about here is that we will be introducing a bit of a behavior change on Linux versus everything else.  In particular, the path of our bundled `libstdc++` is going to be different.  I'm of half a mind to just have this probing occur on _all_ platforms, no matter what, and make things consistent across all platforms.  What do you all think?

**Comment by apaz-cli** [comment]
> One thing that I'm not 100% happy about here is that we will be introducing a bit of a behavior change on Linux versus everything else. In particular, the path of our bundled `libstdc++` is going to be different. I'm of half a mind to just have this probing occur on _all_ platforms, no matter what, and make things consistent across all platforms. What do you all think?

I agree with keeping behavior consistent across all platforms, but I'm also not sure if this is an issue on other platforms. Also obviously if we want to do this on Windows it's going to look completely different.

File: cli/loader_lib.c (hunk 1 above)
Comment (fingolfin) [reply cli/loader_lib.c:189]: Two remarks:
1. Isn't that `CSL_NEXT_GLIBCXX_VERSION` pattern incomplete? It doesn't match e.g. `3.6.0`... or are you really only interested in the literal *next* version? If not, a pattern like `GLIBCXX_3\.[5-9]\.` would be better, but of course it'd also not deal with `3.10.0`, so then you'd also need `GLIBCXX_3\.[1-9][0-9]+\.` or so (untested)
2. how about doing the reverse, and storing the value `3.4.29` (or even the three numbers 3, 4, 29 in the Makefile, and building `CSL_NEXT_GLIBCXX_VERSION` from that? That seems simpler.

File: cli/loader_lib.c (hunk 7 above)
Comment (fingolfin) [reply cli/loader_lib.c:214]: Also `PATH_MAX` is a lie. There is no maximum limit for the length of a path. It's one of these dark shameful corners of POSIX that everyone hopes will go away if we just all pretend it's not there, but sadly it won't...

**Comment by apaz-cli** [comment]
Om my machine, the path that is loaded is: `/home/apaz/git/ejulia/usr/bin/../lib/libstdc++.so`. Should we do path normalization?

File: cli/loader_lib.c [hunk 13]
```diff
@@ -153,6 +154,82 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        if (ret == 0) exit(1);
+        ret = write(fork_pipe[1], info.dli_fname, strlen(info.dli_fname));
+        if (ret == -1) exit(1);
+        exit(0);
+    }
+    else { // Parent process.
+        close(fork_pipe[1]);
+        // Read the absolute path to the lib from the child process.
+        ssize_t have_read = read(fork_pipe[0], path, JL_PATH_MAX);
+        if (have_read == -1) return 0;
```
[the remark this answers is not in the document]
Comment (apaz-cli) [reply cli/loader_lib.c]: Do you mean that the chain of events for the parent process should go:

```md
1. read()
2. waitpid()
3. write()
```

Currently, 2 and 3 are switched.

**Comment by vtjnash** [comment]
path normalization is likely unnecessary, as the loader will probably capture the realpath later (a function which, notoriously, is the only one that does suffer from PATH_MAX issues, and has no posix replacement 👀)

File: cli/loader_lib.c (hunk 13 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply cli/loader_lib.c]: Does the parent process do a write? If you mean `close`, then, I am suggesting it can go right after the last read

File: cli/loader_lib.c (hunk 9 above)
Comment (apaz-cli) [reply cli/loader_lib.c]: Name changed to `JULIA_PROBELIBSTDCXX`.

File: cli/loader_lib.c [hunk 14]
```diff
@@ -195,35 +196,50 @@ static int libstdcxxprobe(char *path, size_t *written)
...
-            fputs("", stderr);
-            exit(1);
+        size_t pathsize = JL_PATH_MAX;
+        *path = (char*)malloc(pathsize + 1);
+        size_t have_read = 0;
+        while (1) {
+            ssize_t n = read(fork_pipe[0], *path + have_read, pathsize - have_read);
+            have_read += n;
+            if (n == 0) break;
+            if (n == -1 && errno != EINTR) return 0;
```
Comment (vtjnash) [inline cli/loader_lib.c:230]: you need to cleanup first

File: cli/loader_lib.c [hunk 15]
```diff
@@ -195,35 +196,50 @@ static int libstdcxxprobe(char *path, size_t *written)
...
+            if (n == -1 && errno == EINTR) continue;
+            if (have_read == pathsize) {
+                *path = (char*)realloc(*path, 1 + (pathsize *= 2));
+                if (!*path) return 0;
```
Comment (vtjnash) [inline cli/loader_lib.c:234]: you need to cleanup first

File: cli/loader_lib.c [hunk 16]
```diff
@@ -244,22 +260,24 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+    char* probevar = getenv("JULIA_PROBELIBSTDCXX");
     if (probevar) {
         if (strcmp(probevar, "1") == 0 || strcmp(probevar, "yes"))
             do_probe = 1;
         else if (strcmp(probevar, "0") == 0 || strcmp(probevar, "no"))
             do_probe = 0;
     }
     if (do_probe) {
-        char cxxpath[JL_PATH_MAX];
+        char* cxxpath = NULL;
```
Comment (vtjnash) [inline cli/loader_lib.c:271]: style nit: star leans right (as a reminder that it "belongs" to the expression on the right, semantically)
```suggestion
        char *cxxpath = NULL;
```

File: cli/loader_lib.c [hunk 17]
```diff
@@ -244,22 +260,24 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
         size_t pathlen = 0;
-        if (!libstdcxxprobe(cxxpath, &pathlen)) {
+        if (!libstdcxxprobe(&cxxpath, &pathlen)) {
             jl_loader_print_stderr("ERROR: Syscalls failed while finding which libstdcxx path to load!\n");
             exit(1);
         }
+        puts(cxxpath);
```
Comment (vtjnash) [inline cli/loader_lib.c:277]: TODO: remove debug code before merging

File: cli/loader_lib.c (hunk 13 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply cli/loader_lib.c]: You are still missing the `close(fork_pipe[0]);` call in the parent

File: cli/loader_lib.c [hunk 18]
```diff
@@ -198,10 +198,10 @@ static int libstdcxxprobe(char **path, size_t *written)
         
         // No error means the symbol was found, we can use this library.
         // Get the path to it.
-        struct link_map* lm;
+        struct link_map * lm;
```
Comment (vtjnash) [inline cli/loader_lib.c:201]: style nit: prefer no space after the `*` (leans right, not leans centered)

File: cli/loader_lib.c [hunk 19]
```diff
@@ -221,7 +221,7 @@ static int libstdcxxprobe(char **path, size_t *written)
 
         // Read the absolute path to the lib from the child process.
         size_t pathsize = JL_PATH_MAX;
-        *path = (char*)malloc(pathsize + 1);
+        *path = (char *)malloc(pathsize + 1);
```
Comment (vtjnash) [inline cli/loader_lib.c:224]: style nit: prefer no spaces inside casts

File: cli/Makefile (hunk 11 above)
Comment (apaz-cli) [reply cli/Makefile]: Reverted the makefile change, back to just checking `_OS_LINUX_`.

File: cli/loader_lib.c (hunk 10 above)
Comment (apaz-cli) [reply cli/loader_lib.c]: Added error handling to every site that could possibly fail (except inside the reporting of other failures before an exit, but if fprintf errors I think we're doomed anyway)

File: cli/loader_lib.c (hunk 13 above)
[the remark this answers is not in the document]
Comment (apaz-cli) [reply cli/loader_lib.c]: Reordered and closed the read end.

**Comment by apaz-cli** [comment]
Currently, buildkite shows that it does fail to `dlopen()` `libstdc++.so.6` on `x86_64-linux-musl`. So, perhaps there should be a check for gnu after all?

**Comment by giordano** [comment]
Do we have an idea of why? I can't easily tell why this should fail to dlopen system libstdc++ (and I'm not even sure this is system libstdc++ at this stage yet as I believe Julia's one still has the priority).

**Comment by apaz-cli** [comment]
> Do we have an idea of why?
https://buildkite.com/julialang/julia-master/builds/16493#01839fe3-7e36-4069-bade-e3b8582c9b6e
`dlopen: Invalid argument`

**Comment by staticfloat** [comment]
@apaz-cli you can debug this with the same environment as on CI by using [the `bughunt` tool](https://github.com/JuliaCI/julia-buildkite/tree/main/debugging/bughunt).  Using a Linux machine, just run `julia --project bughunt.jl https://buildkite.com/julialang/julia-master/builds/16493#01839fe3-7e36-4069-bade-e3b8582c9b6e` and it'll drop you in a shell inside of the same build environment as we use on CI, with the correct Julia checkout.  So you can then look at the [make flags here](https://buildkite.com/julialang/julia-master/builds/16493#01839fe3-7e36-4069-bade-e3b8582c9b6e/566-567) and re-create the same `make` command.  Then you can recreate the error locally, eyeball the command that's failing, then run that command inside of `gdb` or `strace`:

```
$ /build/julia.git/usr/bin/julia -C "generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)" --output-ji /build/julia.git/usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -g0 -O0 compiler/compiler.jl
libstdc++.so.6dlopen: Invalid argument
```

For the record, there is a `libstdc++.so.6` available within the build rootfs as well:
```
$ find / -name libstdc++.so.6 2>/dev/null
/usr/lib/libstdc++.so.6
/build/julia.git/usr/lib/libstdc++.so.6
```

**Comment by staticfloat** [comment]
Alright, definite progress!  Next thing is to do the moving of `libstdc++`'s install locations, as I [outlined in this comment](https://github.com/JuliaLang/julia/pull/46976#discussion_r983785628).

File: Make.inc [hunk 20]
```diff
@@ -1147,6 +1147,9 @@ BB_TRIPLET := $(subst $(SPACE),-,$(filter-out cxx%,$(filter-out libgfortran%,$(s
 
 LIBGFORTRAN_VERSION := $(subst libgfortran,,$(filter libgfortran%,$(subst -,$(SPACE),$(BB_TRIPLET_LIBGFORTRAN))))
 
+CSL_NEXT_GLIBCXX_VERSION=GLIBCXX_3\.4\.30|GLIBCXX_3\.5\.|GLIBCXX_4\.
+GLIBCXX_LEAST_VERSION=$(shell echo "$(CSL_NEXT_GLIBCXX_VERSION)" | cut -d'|' -f1 | sed 's/\\//g')
```
Comment (staticfloat) [inline Make.inc:1151]: Since you're only using this in once place, just inline the `$(shell ...)` invocation into the `LOADER_CFLAGS` line in `cli/Makefile`

File: cli/loader_lib.c [hunk 21]
```diff
@@ -153,6 +153,177 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        perror("fork");
+        fflush(stderr);
+        exit(1);
+    }
+    if (pid == (pid_t) 0) { // Child process.
+        ret = close(fork_pipe[0]);
+        if (ret == -1) {
+            fputs("Error during libstdcxxprobe in child process:", stderr);
+            perror("close");
+            fflush(stderr);
```
Comment (vtjnash) [inline cli/loader_lib.c:196]: Let's avoid getting our output mixed up, reversed, backwards, and duplicated with the parent process by avoiding libc's `FILE *stderr` handle.
```suggestion
            perror("Error during libstdcxxprobe in child process:\nclose");
```

File: cli/loader_lib.c [hunk 22]
```diff
@@ -153,6 +153,177 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+            fprintf(stderr, "dlinfo - %s\n", dlerror());
+            fflush(stderr);
+            _exit(1);
+        }
+        char * libpath = lm->l_name;
+
+        // Write the path over the pipe to the parent process.
+        size_t written_sofar = 0;
+        size_t write_len = strlen(libpath);
+        while(write_len) {
```
Comment (vtjnash) [inline cli/loader_lib.c:244]: style nit: while is not a function call
```suggestion
        while (write_len) {
```

File: cli/loader_lib.c [hunk 23]
```diff
@@ -153,6 +153,177 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+            }
+            else if (WEXITSTATUS(wstatus)) {
+                exit(1); // The child has reported an error and exited, and so should the parent.
+            }
+            break;
+        }
+
+        // Read the absolute path to the lib from the child process.
+        size_t pathsize = JL_PATH_MAX;
+        char* path = (char *)malloc(pathsize + 1);
```
Comment (vtjnash) [inline cli/loader_lib.c:291]:
```suggestion
        char *path = (char*)malloc(pathsize + 1);
```

File: cli/loader_lib.c [hunk 24]
```diff
@@ -153,6 +153,177 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+                if (bytes_written == -1 && errno == EINTR) continue;
+                if (bytes_written == -1 && errno != EINTR) {
+                    fputs("Error during libstdcxxprobe in child process:", stderr);
+                    perror("write");
+                    fflush(stderr);
+                    _exit(1);
+                }
+                write_len -= bytes_written;
+                written_sofar += bytes_written;
+            }
```
Comment (vtjnash) [inline cli/loader_lib.c:225]:
```suggestion
```

File: cli/loader_lib.c [hunk 25]
```diff
@@ -153,6 +153,177 @@ JL_DLLEXPORT const char * jl_get_libdir()
     return lib_dir;
 }
 
+#ifdef _OS_LINUX_
+#define JL_DEFAULT_STDCXXLIB "libstdc++.so.6"
+#ifndef GLIBCXX_LEAST_VERSION /* Should always be defined in the makefile. This appeases the linter. */
+#define GLIBCXX_LEAST_VERSION "GLIBCXX_3.4.29"
```
Comment (vtjnash) [inline cli/loader_lib.c:159]:
```suggestion
#ifndef GLIBCXX_LEAST_VERSION /* This is just to appease the linker */
#warning GLIBCXX_LEAST_VERSION should always be defined in the makefile.
#define GLIBCXX_LEAST_VERSION "GLIBCXX_a.b.c"
```

File: cli/loader_lib.c [hunk 26]
```diff
@@ -153,6 +152,206 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        void *sym = dlsym(handle, GLIBCXX_LEAST_VERSION);
+        dlerr = dlerror();
+        if (dlerr) {
+            // We can't use the library that was found, use the default one instead.
+            char *bundled;
+            size_t len;
+            get_bundled_folder(&bundled, &len);
+            strcat(bundled, "libstdc++.so");
+
+            write_wrapper(fork_pipe[1], bundled, len);
```
Comment (vtjnash) [inline cli/loader_lib.c:291]: since the parent already is required to implement this, I don't think we need to reimplement it here
```suggestion
```

File: cli/loader_lib.c [hunk 27]
```diff
@@ -161,11 +360,52 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+        }
+    }   
+#else
+/* void * load_library(const char * rel_path, const char * src_dir, int err) */
+        char *bundled;
+        size_t len;
+        get_bundled_libstdcxx(&bundled, &len);
+        load_library("libstdc++.so", bundled, 1);
+        free(bundled);
+#endif
```
Comment (vtjnash) [inline cli/loader_lib.c:408]: Please DRY this, so we aren't doing the same thing 3 times slightly differently. (I posted one code suggestion snippet earlier for how to combine them)

File: cli/loader_lib.c [hunk 28]
```diff
@@ -278,7 +518,7 @@ JL_DLLEXPORT int jl_load_repl(int argc, char * argv[]) {
 }
 
 #ifdef _OS_WINDOWS_
-int __stdcall DllMainCRTStartup(void* instance, unsigned reason, void* reserved) {
+int __stdcall DllMainCRTStartup(void * instance, unsigned reason, void * reserved) {
```
Comment (vtjnash) [inline cli/loader_lib.c:521]: style nit
```suggestion
int __stdcall DllMainCRTStartup(void *instance, unsigned reason, void *reserved) {
```

File: cli/loader_lib.c [hunk 29]
```diff
@@ -153,6 +152,206 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+            }
+            else if (WEXITSTATUS(wstatus)) {
+                // The child has printed an error and exited, so the parent should exit too.
+                exit(1);
+            }
+            break;
+        }
+
+        // Read the absolute path to the lib from the child process.
+        char* path;
```
Comment (vtjnash) [inline cli/loader_lib.c:338]:
```suggestion
        char *path;
```

File: cli/loader_lib.c [hunk 30]
```diff
@@ -153,6 +152,206 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+    // Create the pipe and child process.
+    int fork_pipe[2];
+    int ret = pipe(fork_pipe);
+    if (ret == -1) {
+        perror("Error during libstdcxxprobe:\npipe");
+        exit(1);
+    }
+    // Make sure the buffers are clean before forking.
+    fflush(stdout);
+    fflush(stderr);
```
[the remark this answers is not in the document]
Comment (apaz-cli) [reply cli/loader_lib.c:262]: Some of the error handling does use `fprintf()`, and my idea was that:
1. There's only one thread right now, so there's no way to partially flush or confuse the order of writes to the stdio buffers
2. I want the stdio buffers to be empty so that after the `fork()` its contents won't be duplicated

Is the first point not necessarily the case? If it's not, how about calling `flockfile()`?

File: cli/loader_lib.c (hunk 26 above)
Comment (apaz-cli) [reply cli/loader_lib.c:291]: I too have been annoyed at the code duplication. Originally I checked to see if nothing was written over the pipe, and failed out of the function. I was then asked to change it, but I think it works better.

File: cli/loader_lib.c (hunk 30 above)
[the remark this answers is not in the document]
Comment (vtjnash) [reply cli/loader_lib.c:262]: It looked like you were just dumping strings, so write would suffice

[the remark this answers is not in the document]
Comment (apaz-cli) [reply cli/loader_lib.c:262]: Now that all the error handling in the parent process uses `write()`, what should be done with the stuff that's in the meantime to the std streams? Should the parent and child both call `exit()`, or `_exit()`?

[the remark this answers is not in the document]
Comment (vtjnash) [reply cli/loader_lib.c:262]: child always uses `_exit`, parent always uses `exit`

File: deps/csl.mk [hunk 31]
```diff
@@ -22,31 +22,28 @@ endef
...
 ifeq ($(USE_SYSTEM_CSL),1)
 USE_BINARYBUILDER_CSL ?= 0
 else
-# If it's not, see if we should disable it due to `libstdc++` being newer:
 LIBSTDCXX_PATH := $(eval $(call pathsearch,libstdc++,$(STD_LIB_PATH)))
 ifneq (,$(and $(LIBSTDCXX_PATH),$(shell objdump -p $(LIBSTDCXX_PATH) | grep $(CSL_NEXT_GLIBCXX_VERSION))))
-# Found `libstdc++`, grepped it for strings and found a `GLIBCXX` symbol
-# that is newer that whatever we have in CSL.  Default to not using BB.
-USE_BINARYBUILDER_CSL ?= 0
+USE_BINARYBUILDER_CSL ?= 0 # Found a newer symbol, default to not using BB
```
Comment (staticfloat) [inline deps/csl.mk:38]: Do we still need to do this?  @giordano I'm thinking we can actually drop this part (essentially reverting https://github.com/JuliaLang/julia/commit/27c0291f7fbecd811a3f9eb62b1159cff6b61e2a) and just always ship our `libstdc++` (as long as `USE_BINARYBUILDER_CSL=1`), since the decision to use it or not should now be made correctly at runtime.

File: deps/csl.mk [hunk 32]
```diff
@@ -104,5 +100,25 @@ clean-csl:
...
+ifeq ($(USE_BINARYBUILDER_CSL),0)
+$(LIBSTDCXX_INSTALL_PATH): | $(build_shlibdir)
+	-@mkdir -p "$(LIBSTDCXX_INSTALL_FOLDER)"
+	-cp "$(LIBSTDCXX_PATH)" "$(LIBSTDCXX_INSTALL_PATH)"
+else
+$(LIBSTDCXX_INSTALL_PATH): | $(build_shlibdir)
+	-@mkdir -p "$(LIBSTDCXX_INSTALL_FOLDER)"
+	-mv "$(build_shlibdir)/libstdc++"* "$(LIBSTDCXX_INSTALL_FOLDER)/"
+endif
+install-csl: | $(build_shlibdir) $(LIBSTDCXX_INSTALL_PATH)
```
Comment (staticfloat) [inline deps/csl.mk:119]:
```suggestion
install-csl: | $(LIBSTDCXX_INSTALL_PATH)
```

**Review by staticfloat — DISMISSED** [review]

File: deps/csl.mk (hunk 31 above)
Comment (giordano) [reply deps/csl.mk:38]: Uhm, yeah, good point, so we'd have a single place where we do this check (runtime), which would simplify things a bit.

Comment (apaz-cli) [reply deps/csl.mk]: I've made the change because I agree. But, note that this does affect whether other libraries are copied through BB or not in that case. I take it that this is acceptable?

File: cli/loader_lib.c (hunk 25 above)
Comment (vtjnash) [reply cli/loader_lib.c]: still need this warning added

File: cli/loader_lib.c [hunk 33]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+#include <sys/wait.h>
+
+static void write_wrapper(int fd, char *str, size_t len)
+{
+    size_t written_sofar = 0;
+    while (len) {
+        ssize_t bytes_written = write(fd, str + written_sofar, len);
+        if (bytes_written == -1 && errno == EINTR) continue;
+        if (bytes_written == -1 && errno != EINTR) {
+            perror("Error in write wrapper:\nwrite");
```
Comment (vtjnash) [inline cli/loader_lib.c:170]: "write wrapper" is a meaningless phrase to users. While this is unlikely to fail (probably meaning the parent was killed), it is clearer if it specifies that it comes from julia and is part of the libstdcxxprobe helper functionality
```suggestion
            perror("(julia) child libstdcxxprobe write:");
```

File: cli/loader_lib.c [hunk 34]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+// Where the buf passed in was malloced
+static void read_wrapper(int fd, char **ret, size_t *ret_len)
+{
+    // Allocate an initial buffer
+    size_t len = JL_PATH_MAX;
+    char *buf = (char *)malloc(len + 1);
+    if (!buf) {
+        char err_str[] = "Error in read wrapper:\nmalloc() returned NULL.\n";
+        size_t err_strlen = strlen(err_str);
+        write_wrapper(STDERR_FILENO, err_str, err_strlen);
```
Comment (vtjnash) [inline cli/loader_lib.c:187]:
```suggestion
        perror("(julia) malloc");
```

File: cli/loader_lib.c [hunk 35]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+            perror("Error in read wrapper:\nread");
+            exit(1);
+        }
+        if (n == -1 && errno == EINTR) continue;
+        if (have_read == len) {
+            buf = (char *)realloc(buf, 1 + (len *= 2));
+            if (!buf) {
+                char err_str[] = "Error in read wrapper:\nrealloc() returned NULL.\n";
+                size_t err_strlen = strlen(err_str);
+                write_wrapper(STDERR_FILENO, err_str, err_strlen);
```
Comment (vtjnash) [inline cli/loader_lib.c:207]:
```suggestion
                perror("(julia) realloc");
```

File: cli/loader_lib.c [hunk 36]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+    }
+
+    // Read into it, reallocating as necessary
+    size_t have_read = 0;
+    while (1) {
+        ssize_t n = read(fd, buf + have_read, len - have_read);
+        have_read += n;
+        if (n == 0) break;
+        if (n == -1 && errno != EINTR) {
+            perror("Error in read wrapper:\nread");
```
Comment (vtjnash) [inline cli/loader_lib.c:198]:
```suggestion
            perror("(julia) libstdcxxprobe read");
```

File: cli/loader_lib.c [hunk 37]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
 
+#ifdef _OS_LINUX_
+#ifndef GLIBCXX_LEAST_VERSION_SYMBOL /* Should always be defined in the makefile. This appeases the linter. */
+#define GLIBCXX_LEAST_VERSION_SYMBOL "GLIBCXX_a.b.c"
+#endif
+
+#include <link.h>
+#include <sys/wait.h>
+
+static void write_wrapper(int fd, char *str, size_t len)
```
Comment (vtjnash) [inline cli/loader_lib.c:163]: IIUC, these are only used on linux, which means the unused-function warning will occur unless you hide these inside the `#if` block also

File: cli/loader_lib.c [hunk 38]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+// If the path is found, return it.
+// Otherwise, print the error and exit.
+// The path returned must be freed.
+static char *libstdcxxprobe(void)
+{
+    // Create the pipe and child process.
+    int fork_pipe[2];
+    int ret = pipe(fork_pipe);
+    if (ret == -1) {
+        perror("Error during libstdcxxprobe:\npipe");
```
Comment (vtjnash) [inline cli/loader_lib.c:230]:
```suggestion
        perror("(julia) Error during libstdcxxprobe: pipe");
```

File: cli/loader_lib.c [hunk 39]
```diff
@@ -153,6 +152,181 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        }
+
+        // No error means the symbol was found, we can use this library.
+        // Get the path to it, and write it to the parent process.
+        struct link_map *lm;
+        ret = dlinfo(handle, RTLD_DI_LINKMAP, &lm);
+        if (ret == -1) {
+            char errbuf[2048];
+            int err_len = snprintf(errbuf, 2048, "Error during libstdcxxprobe in child process:\ndlinfo() - %s\n", dlerror());
+            write_wrapper(STDOUT_FILENO, errbuf, (size_t)err_len);
```
Comment (vtjnash) [inline cli/loader_lib.c:269]:
```suggestion
            char *errbuf = dlerror();
            const char *errdesc = "Error during libstdcxxprobe in child process:\ndlinfo: ";
            write_wrapper(STDERR_FILENO, errdesc, strlen(errdesc));
            write_wrapper(STDERR_FILENO, errbuf, strlen(errbuf));
            write_wrapper(STDERR_FILENO, "\n", 1);
```

File: cli/loader_lib.c [hunk 40]
```diff
@@ -161,11 +335,46 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+        if (cxxpath) {
+            cxx_handle = dlopen(cxxpath, RTLD_LAZY);
+            char *dlr = dlerror();
+            if (dlr) {
+                size_t buflen = strlen(cxxpath) + 2048;
+                char *errbuf = malloc(buflen);
+                int err_len = snprintf(errbuf, buflen, "Error, cannot load \"%s\"\n"
+                                                       "dlinfo() - %s\n", cxxpath, dlr);
+                write_wrapper(STDOUT_FILENO, errbuf, (size_t)err_len);
+                free(errbuf);
```
Comment (vtjnash) [inline cli/loader_lib.c:355]: There are already wrapper functions supplied for this
```suggestion
                jl_loader_print_stderr("ERROR: Unable to dlopen(cxxpath) in parent!\n");
                jl_loader_print_stderr3("Message: ", dlerr, "\n");
```

n.b. make sure `Message: ` has a space after it

File: cli/loader_lib.c [hunk 41]
```diff
@@ -161,11 +335,46 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+                exit(1);
+            }
+            free(cxxpath);
+            done_probe = 1;
+        }
+    }
+#endif
+    // If not on linux, or the probe does not finish successfully, load the bundled version.
+    if (!done_probe) {
+        load_library("libstdc++.so", jl_get_libdir(), 1);
```
Comment (vtjnash) [inline cli/loader_lib.c:365]:
```suggestion
        load_library("libstdc++.so.6", jl_get_libdir(), 1);
```

File: cli/loader_lib.c [hunk 42]
```diff
@@ -153,6 +152,170 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        perror("(julia) Error during libstdcxxprobe: pipe");
+        exit(1);
+    }
+    pid_t pid = fork();
+    if (pid == -1)  {
+        perror("Error during libstdcxxprobe:\nfork");
+        exit(1);
+    }
+    if (pid == (pid_t) 0) { // Child process.
+        ret = close(fork_pipe[0]);
```
Comment (vtjnash) [inline cli/loader_lib.c:238]:
```suggestion
        close(fork_pipe[0]);
```

File: cli/loader_lib.c [hunk 43]
```diff
@@ -153,6 +152,170 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+            write_wrapper(STDERR_FILENO, errbuf, strlen(errbuf));
+            write_wrapper(STDERR_FILENO, "\n", 1);
+            _exit(1);
+        }
+        char *libpath = lm->l_name;
+        write_wrapper(fork_pipe[1], libpath, strlen(libpath));
+        _exit(0);
+    }
+    else { // Parent process.
+        ret = close(fork_pipe[1]);
```
Comment (vtjnash) [inline cli/loader_lib.c:275]:
```suggestion
        close(fork_pipe[1]);
```

File: cli/loader_lib.c [hunk 44]
```diff
@@ -153,6 +153,177 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        if (ret == -1) {
+            fputs("Error during libstdcxxprobe in parent process:", stderr);
+            perror("close");
+            exit(1);
+        }
+
+        // Wait for the child to complete.
```
[the remark this answers is not in the document]
Comment (vtjnash) [reply cli/loader_lib.c:277]: still a deadlock here, since you don't read the pipe until after the child exits, but the child may not exit until after you read the pipe

File: cli/loader_lib.c [hunk 45]
```diff
@@ -153,6 +152,170 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+            break;
+        }
+
+        // Read the absolute path to the lib from the child process.
+        char *path;
+        size_t pathlen;
+        read_wrapper(fork_pipe[0], &path, &pathlen);
+
+        // Close the read end of the pipe
+        ret = close(fork_pipe[0]);
```
Comment (vtjnash) [inline cli/loader_lib.c:308]:
```suggestion
        close(fork_pipe[0]);
```

File: deps/csl.mk (hunk 31 above)
Comment (staticfloat) [reply deps/csl.mk]: Yes; we're just always going to copy the libraries through now.

File: cli/loader_lib.c [hunk 46]
```diff
@@ -161,11 +324,42 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+                exit(1);
+            }
+            free(cxxpath);
+            done_probe = 1;
+        }
+    }
+#endif
+    // If not on linux, or the probe does not finish successfully, load the bundled version.
+    if (!done_probe) {
+        load_library("libstdc++.so.6", lib_dir, 1);
```
Comment (staticfloat) [inline cli/loader_lib.c:361]: On third thought, I think the best thing to do here is to disambiguate the "not on linux" and "probe did not finish successfully" cases; on e.g. macOS, there's no need to eagerly load `libstdc++`, so let's just not do it.  It will just get loaded on-demand, along with everything else.  On Linux, if our probe failed, we should load the bundled version.

Comment (staticfloat) [reply cli/loader_lib.c:361]: This will also fix Windows CI, since you're trying to load `libstdc++.so.6` on windows, which doesn't use `.so`. ;)

**Review by vtjnash — APPROVED** [review]

File: cli/loader_lib.c [hunk 47]
```diff
@@ -161,11 +324,42 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+                jl_loader_print_stderr("ERROR: Unable to dlopen(cxxpath) in parent!\n");
+                jl_loader_print_stderr3("Message: ", dlr, "\n");
+                exit(1);
+            }
+            free(cxxpath);
+            done_probe = 1;
+        }
+    }
+    if (!done_probe) {
+        load_library("libstdc++.so.6", lib_dir, 1);
```
Comment (vtjnash) [inline cli/loader_lib.c:360]: There is a CI issue because the install path is different from the build path. Currently we call stringreplace to fix that in the `make install` step, as well as make this a static buffer in the file with a special pattern you can use for the find-replace:
```suggestion
        static const char libstdcxx_path[128]= "\0*libstdc++.so.6";
        load_library(&libstdcxx_path[2], lib_dir, 1);
```

then see how LIBJULIAINTERNAL_BUILD_DEPLIB is changed to LIBJULIAINTERNAL_INSTALL_DEPLIB in the Makefile for an example, using `\*libstdc\+\+\.so\.6$$` as the search text and `*$(call rel_path,$(libdir),$(private_libdir))/libstdc++.so.6` as the replacement text

File: cli/loader_lib.c [hunk 48]
```diff
@@ -153,6 +152,170 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
 }
 
+// On Linux, it can happen that the system has a newer libstdc++ than the one we ship,
+// which can break loading of some system libraries: <https://github.com/JuliaLang/julia/issues/34276>.
+// As a fix, on linux we probe the system libstdc++ to see if it is newer, and then load it if it is.
+// Otherwise, we load the packaged one. This improves compatibility with third party dynamic libs that
+// may depend on symbols exported by the system libstdxc++.
+#ifdef _OS_LINUX_
+#ifndef GLIBCXX_LEAST_VERSION_SYMBOL
+#warning GLIBCXX_LEAST_VERSION_SYMBOL should always be defined in the makefile.
```
Comment (giordano) [inline cli/loader_lib.c:162]: I'm surprised this `#warning` is surviving `-Werror`, don't we use it in `cli/`?  We typically use `#pragma message "..."` instead.

Comment (vtjnash) [reply cli/loader_lib.c:162]: this should be unreachable or the build will be corrupted, but it makes linters happy

File: cli/loader_lib.c (hunk 47 above)
Comment (apaz-cli) [reply cli/loader_lib.c:360]: How about just using a define on the command line like with `GLIBCXX_LEAST_VERSION_SYMBOL`?

File: cli/Makefile [hunk 49]
```diff
@@ -13,7 +13,7 @@ LOADER_LDFLAGS = $(JLDFLAGS) -ffreestanding -L$(build_shlibdir) -L$(build_libdir
 ifeq ($(OS),WINNT)
 LOADER_CFLAGS += -municode -mconsole -nostdlib -fno-stack-check -fno-stack-protector -mno-stack-arg-probe
 else ifeq ($(OS),Linux)
-LOADER_CFLAGS += -DGLIBCXX_LEAST_VERSION_SYMBOL=\"$(shell echo "$(CSL_NEXT_GLIBCXX_VERSION)" | cut -d'|' -f1 | sed 's/\\//g')\"
+LOADER_CFLAGS += -DGLIBCXX_LEAST_VERSION_SYMBOL=\"$(shell echo "$(CSL_NEXT_GLIBCXX_VERSION)" | cut -d'|' -f1 | sed 's/\\//g')\" -DGLIBCXX_PATH=\"$($(private_libdir)/libstdc++.so.6)\"
```
Comment (vtjnash) [inline cli/Makefile:16]: We do not use absolute paths. Also, this is a the build, not install, path that goes here.
```suggestion
LOADER_CFLAGS += -DGLIBCXX_LEAST_VERSION_SYMBOL=\"$(shell echo "$(CSL_NEXT_GLIBCXX_VERSION)" | cut -d'|' -f1 | sed 's/\\//g')\" -DGLIBCXX_PATH=\"$($(call relpath,$(build_libdir),$(build_libdir))/libstdc++.so.6)\"
```
But that relpath is obviously meaningless (it is always `.`, so this commit is simply unnecessary and should be dropped

File: deps/csl.mk [hunk 50]
```diff
@@ -22,7 +22,6 @@ endef
 # would get from CSL (by searching for a `GLIBCXX_3.4.X` symbol that does not exist
 # in our CSL, but would in a newer one), and default to `USE_BINARYBUILDER_CSL=0` in
 # this case.
```
Comment (giordano) [inline deps/csl.mk:24]: There is a leftover comment which should probably be moved to Make.inc

**Comment by giordano** [comment]
I see the TODO list is complete, but I think there is something still missing:
```console
% ./julia --startup-file=no -q
julia> using Libdl; filter!(x -> occursin("libstdc++.so", x), dllist())
1-element Vector{String}:
 "/home/mose/repo/julia/46976-mg-dlopen-libstdc++/usr/bin/../lib/libstdc++.so.6"
```
but
```console
% nm usr/lib/libstdc++.so | grep -E ' GLIBCXX_3.4.(2|3)[0-9]' 
0000000000000000 A GLIBCXX_3.4.20
0000000000000000 A GLIBCXX_3.4.21
0000000000000000 A GLIBCXX_3.4.22
0000000000000000 A GLIBCXX_3.4.23
0000000000000000 A GLIBCXX_3.4.24
0000000000000000 A GLIBCXX_3.4.25
0000000000000000 A GLIBCXX_3.4.26
0000000000000000 A GLIBCXX_3.4.27
0000000000000000 A GLIBCXX_3.4.28
0000000000000000 A GLIBCXX_3.4.29
% nm /usr/lib/libstdc++.so | grep -E ' GLIBCXX_3.4.(2|3)[0-9]'
0000000000000000 A GLIBCXX_3.4.20
0000000000000000 A GLIBCXX_3.4.21
0000000000000000 A GLIBCXX_3.4.22
0000000000000000 A GLIBCXX_3.4.23
0000000000000000 A GLIBCXX_3.4.24
0000000000000000 A GLIBCXX_3.4.25
0000000000000000 A GLIBCXX_3.4.26
0000000000000000 A GLIBCXX_3.4.27
0000000000000000 A GLIBCXX_3.4.28
0000000000000000 A GLIBCXX_3.4.29
0000000000000000 A GLIBCXX_3.4.30
```
Note that `/usr/lib/libstdc++.so` has `GLIBCXX_3.4.30`, so the system library should have been loaded.

In terms of startup time, unsurprisingly this PR slightly slows it down (first is https://github.com/JuliaLang/julia/commit/dc3a2e8d27a6527b3ca3583e478710dffce18319, second is https://github.com/JuliaLang/julia/commit/5b622feca59b36732b3afafd241be2703dfe6b6e):
```console
% hyperfine -r 50 "./julia --startup-file=no -e ''" "46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''"
Benchmark 1: ./julia --startup-file=no -e ''
  Time (mean ± σ):     126.0 ms ±   1.0 ms    [User: 93.7 ms, System: 81.3 ms]
  Range (min … max):   124.0 ms … 128.4 ms    50 runs
 
Benchmark 2: 46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''
  Time (mean ± σ):     128.1 ms ±   1.5 ms    [User: 96.8 ms, System: 80.8 ms]
  Range (min … max):   126.0 ms … 132.1 ms    50 runs
 
Summary
  './julia --startup-file=no -e ''' ran
    1.02 ± 0.01 times faster than '46976-mg-dlopen-libstdc++/julia --startup-file=no -e '''
```
This is 2 extra milliseconds, perhaps not too bad.  However, what I do find surprising is that on a cold start this PR seems ~12 ms faster:
```console
% hyperfine --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' -r 50 "./julia --startup-file=no -e ''" "46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''"
Benchmark 1: ./julia --startup-file=no -e ''
  Time (mean ± σ):     274.3 ms ±   9.2 ms    [User: 151.8 ms, System: 191.4 ms]
  Range (min … max):   263.0 ms … 316.8 ms    50 runs
 
Benchmark 2: 46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''
  Time (mean ± σ):     262.0 ms ±   3.5 ms    [User: 144.5 ms, System: 176.1 ms]
  Range (min … max):   254.5 ms … 269.3 ms    50 runs
 
Summary
  '46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''' ran
    1.05 ± 0.04 times faster than './julia --startup-file=no -e '''
```
I don't have an explanation for this.

**Comment by gbaraldi** [comment]
Does the cold start remove everything from the cache? Maybe there is some optimization for system libs, or something of the sort.

**Comment by giordano** [comment]
> Maybe there is some optimization for system libs, or something of the sort.

What do you mean?  That loading `/usr/lib/libstdc++.so` should be faster?  If so, I'm not even loading that library as I pointed in the same message.

**Comment by gbaraldi** [comment]
Just a guess. Are the libs about the same size? Maybe there is a difference?

**Comment by giordano** [comment]
> Are the libs about the same size?

What libs?  I'm always loading the same libstdc++ :joy:

**Comment by gbaraldi** [comment]
I misread it 😄. I saw you mentioning the system libs above and my mind just connected some dots that weren't there 😅

**Comment by apaz-cli** [comment]
@giordano Currently, `GLIBCXX_LEAST_VERSION` should be `GLIBCXX_3.4.30`, so on linux it should (unless disabled by env var) load the system version. On other platforms, libstdc++ is not loaded by the loader at all, and the libraries that require libstdc++ must load it instead. They may choose to load the system one or the bundled one.

On my debian sid machine, your code gives me: `"/lib/x86_64-linux-gnu/libstdc++.so.6"`, the system library, which is correct. Let me know if you think what it's doing on your machine is wrong.

**Comment by staticfloat** [comment]
> It does occur to me though that maybe we should handle checking for CSL_NEXT_GLIBCXX_VERSION a bit better. Suppose the next version of glibcxx was not GLIBCXX_3.4.30, but GLIBCXX_3.5.X or GLIBCXX_4.X.X. We're not handling that correctly at the moment. It's an easy and minor fix though.

We know the next version of `GLIBCXX`; it's `3.4.30`.  We don't need to prepare for the future, any version of `libstdc++` that is newer than the one we ship will contain `GLIBCXX_3.4.30` in addition to `GLIBCXX_3.5.0` or whatever else exists in the future.

File: cli/loader_lib.c [hunk 51]
```diff
@@ -153,6 +152,173 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+    }
+    if (pid == (pid_t) 0) { // Child process.
+        close(fork_pipe[0]);
+
+        // Open the first available libstdc++.so.
+        // If it can't be found, report so by exiting zero.
+        // The star is there to prevent the compiler from merging constants
+        // with "\0*libstdc++.so.6", which we string replace inside the .so during
+        // make install.
+        void *handle = dlopen("libstdc++.so.6\0*", RTLD_LAZY);
```
Comment (staticfloat) [inline cli/loader_lib.c:245]: I don't think we want to alter this path during `make install` time; this should always try to open exactly `libstdc++.so.6`; it's the bundled `libstdc++` path that we need to alter with `stringreplace`.

File: cli/loader_lib.c [hunk 52]
```diff
@@ -153,6 +152,173 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+                                      "The child process did not exit normally.\n";
+                size_t err_strlen = strlen(err_str);
+                write_wrapper(STDERR_FILENO, err_str, err_strlen);
+                exit(1);
+            }
+            else if (WEXITSTATUS(wstatus)) {
+                // The child has printed an error and exited, so the parent should exit too.
+                exit(1);
+            }
+            break;
```
Comment (staticfloat) [inline cli/loader_lib.c:310]: Don't we need to set `path` to the bundled path here?  This would be the point that we'd reach if we found that the system `libstdc++` is unsatisfactory and exited with `exit(0)`, correct?

**Review by staticfloat — CHANGES_REQUESTED** [review]
I tried this out and found that it works when run after `make`, but fails when run after `make install`; I think there's some confusion regarding which paths get overwritten.

**Comment by staticfloat** [comment]
FWIW, my testing setup is:

```Dockerfile
# Save this file as 'Dockerfile'
# Try images such as:
# - centos:7
# - debian:11
# - ubuntu:2022.10
# - archlinux:latest
ARG IMAGE
FROM ${IMAGE}

# If we're on debian/ubuntu, use `apt-get` to get `curl`, `readelf`, etc...
RUN [ -z "$(command -v apt-get)" ] || ( apt-get update && apt-get install -y curl tar binutils )
# If we're on arch, use `pacman` to install `readelf`
RUN [ -z "$(command -v pacman)" ] || ( pacman -Syu --noconfirm binutils )

ARG JULIA_TARBALL="https://buildkite.com/organizations/julialang/pipelines/julia-master/builds/17231/jobs/0183f6cd-92c6-4f18-8505-fc09c60996ee/artifacts/0183f6f9-bf8b-45aa-a263-432467e4eb65"
RUN curl -L "${JULIA_TARBALL}" | tar -C /usr/local --strip-components=1 -xz

COPY test.sh /usr/local/bin/test.sh
CMD ["/bin/bash", "/usr/local/bin/test.sh"]
```

```bash
#!/bin/bash
# save this file as `test.sh`

#!/bin/bash

LIB_PATH=$(ldconfig -p | grep libstdc++.so.6 | awk '{ print $4 }')
echo "DUMPING ALL GLIBCXX_ version symbols in ${LIB_PATH}:"
readelf -V "${LIB_PATH}" | grep "Name: GLIBCXX_3.4" | cut -d' ' -f11-

echo "Julia links against:"
julia -E 'using Libdl; filter(f -> occursin("libstdc++.so", f), Libdl.dllist())'
```

Run this on different images via:
```shell
docker build . -t libstdcxx --build-arg IMAGE=archlinux:latest && docker run -ti libstdcxx
```

File: cli/loader_lib.c (hunk 51 above)
Comment (apaz-cli) [reply cli/loader_lib.c:245]: We don't want it to be altered, hence why we appended `\0*`. The other (bundled) one prepends `*`, and we string replace the prepended symbol.

File: cli/loader_lib.c (hunk 52 above)
Comment (apaz-cli) [reply cli/loader_lib.c:310]: If the system libstdc++ is unsatisfactory, then nothing is read, and `!pathlen` returns `NULL`, `done_probe` is never set to 1, and the bundled lib is loaded.

**Comment by apaz-cli** [comment]
> I tried this out and found that it works when run after `make`, but fails when run after `make install`; I think there's some confusion regarding which paths get overwritten.

It works on my machine. How can I reproduce this?

**Comment by vtjnash** [comment]
There seems to be something vaguely wrong with the build machines, where `ld` is emitting `DT_RPATH` instead of `DT_RUNPATH` into `bin/julia`. This doesn't seem to reproduce on our local dev machines, but it is making our binary release from buildkite a bit broken (and, in particular, is also making this fail).

**Comment by DilumAluthge** [comment]
@apaz-cli Could you mention the escape-hatch environment variable in the NEWS entry?

**Comment by giordano** [comment]
Ok, with one of the changes after my last message (probably https://github.com/JuliaLang/julia/commit/af25dd73880207e66d5328b5507b9930decfa4d6?) I now get:
```console
% ./julia -E 'using Libdl; filter!(x -> occursin("libstdc++.so", x), dllist())'
["/usr/lib/libstdc++.so.6"]
```
:partying_face:

**Comment by vtjnash** [comment]
@staticfloat Is this look good now to you? I would give it a LGTM. Note that without the BB fix, we have been often loading the wrong (aka system) `libquadmath.so` even prior to this PR. However, we will now load the correct one after `make install` (though pre-make install builds may still be slightly broken, such that this PR could break things for anyone that compiles julia locally, but doesn't have a compiler installed (libquadmath0 is a dependency of gcc-*)--hopefully this explanation makes enough sense):
```
julia> Libdl.dllist()
38-element Vector{String}:
 "linux-vdso.so.1"
 "/lib/x86_64-linux-gnu/libdl.so.2"
 "/lib/x86_64-linux-gnu/libpthread.so.0"
 "/lib/x86_64-linux-gnu/libc.so.6"
 "/data/vtjnash/julia1/usr/bin/../lib/libjulia.so.1"
 "/lib64/ld-linux-x86-64.so.2"
 "/data/vtjnash/julia1/usr/bin/../lib/libstdc++.so.6"
 "/lib/x86_64-linux-gnu/libm.so.6"
 "/lib/x86_64-linux-gnu/libgcc_s.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libopenlibm.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libjulia-internal.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libunwind.so.8"
 "/lib/x86_64-linux-gnu/librt.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libatomic.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libz.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libjulia-codegen.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libLLVM-14jl.so"
 "/data/vtjnash/julia1/usr/lib/julia/sys.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libpcre2-8.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libgmp.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libmpfr.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libgfortran.so.5"
 "/usr/lib/x86_64-linux-gnu/libquadmath.so.0" <-------------------------- !
 "/data/vtjnash/julia1/usr/bin/../lib/libgomp.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libopenblas64_.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libblastrampoline.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libcholmod.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libamd.so.2"
 "/data/vtjnash/julia1/usr/bin/../lib/libcolamd.so.2"
 "/data/vtjnash/julia1/usr/bin/../lib/libsuitesparseconfig.so.5"
 "/data/vtjnash/julia1/usr/bin/../lib/libccolamd.so.2"
 "/data/vtjnash/julia1/usr/bin/../lib/libcamd.so.2"
 "/data/vtjnash/julia1/usr/bin/../lib/libnghttp2.so.14"
 "/data/vtjnash/julia1/usr/bin/../lib/libcurl.so"
 "/data/vtjnash/julia1/usr/bin/../lib/libssh2.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libmbedtls.so.14"
 "/data/vtjnash/julia1/usr/bin/../lib/libmbedx509.so.1"
 "/data/vtjnash/julia1/usr/bin/../lib/libmbedcrypto.so.7"
```

File: Makefile [hunk 53]
```diff
@@ -382,6 +382,17 @@ else ifeq ($(JULIA_BUILD_MODE),debug)
 endif
 endif
 
+	# Fix rpaths for dependencies. This should be fixed in BinaryBuilder later.
+ifeq ($(OS), Linux)
+	-$(PATCHELF) --set-rpath '$$ORIGIN' $(DESTDIR)$(private_shlibdir)/libgfortran.$(SHLIB_EXT)
+	-$(PATCHELF) --set-rpath '$$ORIGIN' $(DESTDIR)$(private_shlibdir)/libLLVM.$(SHLIB_EXT)
+endif
```
Comment (vtjnash) [inline Makefile:389]: Note for other reviewers: we also identified that libgit2, lib\*san, and all suitesparse libraries do not have `RUNPATH: $ORIGIN` in them as expected. Of those, however, the lib\*san libraries are not installed, so we don't care about them currently. Secondly, we appear to load all of the dependencies of libgit2 at startup (excluding libgit2 itself), according to `Libdl.dllist()`, so it shouldn't see a change there, even with attempted LD_LIBRARY_PATH overloading:
```
  SONAME               libgit2.so.1.4
  NEEDED               librt.so.1
  NEEDED               libpthread.so.0
  NEEDED               libmbedtls.so.14
  NEEDED               libmbedx509.so.1
  NEEDED               libmbedcrypto.so.7
  NEEDED               libssh2.so.1
  NEEDED               libc.so.6
  RPATH                $ORIGIN
```
And while we do not load all of SuiteSparse at startup, the `_jll` pkg will attempt to sort them correctly, so the presence of `RPATH $ORIGIN` should be of little to no consequence, compared to `RUNPATH $ORIGIN` that we would prefer to see there.

So these seem to be the only 2 libraries that we need to care about for this PR to progress at present.

File: deps/csl.mk (hunk 50 above)
Comment (staticfloat) [reply deps/csl.mk:24]: @apaz-cli can you move this comment please?

**Review by staticfloat — CHANGES_REQUESTED** [review]

File: deps/csl.mk (hunk 50 above)
Comment (staticfloat) [reply deps/csl.mk:24]: Actually, just copy it, since it makes sense in both places.

**Review by staticfloat — APPROVED** [review]

File: Makefile [hunk 54]
```diff
@@ -382,6 +382,17 @@ else ifeq ($(JULIA_BUILD_MODE),debug)
 endif
 endif
 
+	# Fix rpaths for dependencies. This should be fixed in BinaryBuilder later.
+ifeq ($(OS), Linux)
+	-$(PATCHELF) --set-rpath '$$ORIGIN' $(DESTDIR)$(private_shlibdir)/libgfortran.$(SHLIB_EXT)
```
Comment (giordano) [inline Makefile:387]: This one shouldn't be needed anymore after #47381 (now merged)

Comment (apaz-cli) [reply Makefile:387]: Neat. What should we do about LLVM?

Comment (giordano) [reply Makefile:387]: I'd say keep the line below for the time being.  Investigating what the audit does in the build of llvm is way more complicated.

File: Make.inc [hunk 55]
```diff
@@ -1149,6 +1149,28 @@ BB_TRIPLET := $(subst $(SPACE),-,$(filter-out cxx%,$(filter-out libgfortran%,$(s
...
+# relatively old. This is not a problem for code that is built in BB, but when we build Julia
+# with the system compiler, that compiler uses the version of `libstdc++` that it is bundled
+# with, and we can get linker errors when trying to run that `julia` executable with the
+# `libstdc++` that comes from the (now old) BB-built CSL.
+# To fix this, we take note when the system `libstdc++.so` is newer than whatever we
+# would get from CSL (by searching for a `GLIBCXX_X.Y.Z` symbol that does not exist
+# in our CSL, but would in a newer one), and default to `USE_BINARYBUILDER_CSL=0` in
+# this case. This ensures that we link against a version with the symbols required.
+# We also check the system libstdc++ at runtime in the cli loader library, and
+# load it if it contains the version symbol that indicates than it is newer than the one
```
Comment (fingolfin) [inline Make.inc:1168]:
```suggestion
# load it if it contains a version symbol that indicates that it is newer than the one
```

File: NEWS.md [hunk 56]
```diff
@@ -183,7 +183,8 @@ Deprecated or removed
 
 External dependencies
 ---------------------
-
+* On linux, now autodetects the system libstdc++ version, and automatically loads the system library if it is newer. The old behavior of loading the bundled libstdc++ regardless of the system version obtained by setting the environment variable `JULIA_PROBE_LIBSTDCXX=0`.
```
Comment (fingolfin) [inline NEWS.md:186]:
```suggestion
* On Linux, now autodetects the system libstdc++ version, and automatically loads the system library if it is newer. The old behavior of loading the bundled libstdc++ regardless of the system version obtained by setting the environment variable `JULIA_PROBE_LIBSTDCXX=0`.
```

File: cli/loader_lib.c [hunk 57]
```diff
@@ -167,6 +166,173 @@ JL_DLLEXPORT const char * jl_get_libdir()
     return lib_dir;
 }
 
+// On Linux, it can happen that the system has a newer libstdc++ than the one we ship,
+// which can break loading of some system libraries: <https://github.com/JuliaLang/julia/issues/34276>.
+// As a fix, on linux we probe the system libstdc++ to see if it is newer, and then load it if it is.
```
Comment (fingolfin) [inline cli/loader_lib.c:171]:
```suggestion
// As a fix, we probe the system libstdc++ to see if it is newer, and then load it if it is.
```

File: cli/loader_lib.c [hunk 58]
```diff
@@ -167,6 +166,173 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+// Otherwise, we load the packaged one. This improves compatibility with third party dynamic libs that
```
Comment (fingolfin) [inline cli/loader_lib.c:172]:
```suggestion
// Otherwise, we load the bundled one. This improves compatibility with third party dynamic libs that
```

File: cli/loader_lib.c [hunk 59]
```diff
@@ -167,6 +166,173 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+#ifdef _OS_LINUX_
+#ifndef GLIBCXX_LEAST_VERSION_SYMBOL
+#warning GLIBCXX_LEAST_VERSION_SYMBOL should always be defined in the makefile.
+#define GLIBCXX_LEAST_VERSION_SYMBOL "GLIBCXX_a.b.c" /* Appease the linter */
+#endif
+
+#include <link.h>
+#include <sys/wait.h>
+
+static void write_wrapper(int fd, const char *str, size_t len)
```
Comment (fingolfin) [inline cli/loader_lib.c:183]: could this get a comment? Perhaps something like this (if I guessed right at its purpose)
```suggestion
// helper function to make `write` more convenient to use correctly
static void write_wrapper(int fd, const char *str, size_t len)
```

File: cli/loader_lib.c [hunk 60]
```diff
@@ -167,6 +166,173 @@ JL_DLLEXPORT const char * jl_get_libdir()
...
+        if (bytes_written == -1 && errno != EINTR) {
+            perror("(julia) child libstdcxxprobe write");
+            _exit(1);
+        }
+        len -= bytes_written;
+        written_sofar += bytes_written;
+    }
+}
+
+// Where the buf passed in was malloced
```
Comment (fingolfin) [inline cli/loader_lib.c:198]: I am not sure I understand this comment correctly; as far as I can tell, no buffer is passed in. Or if it is, then it is ignored: this function allocates its own buffer, and ultimately returns it via `ret`

File: deps/csl.mk (hunk 50 above)
Comment (fingolfin) [reply deps/csl.mk:24]: Huh, it seems the comment I edited above is derived from the comment here, but has unique typos?! What's going on there?

**Review by fingolfin — COMMENTED** [review]
Thank you very much for working on this! I noticed a few minor typos

File: cli/loader_lib.c (hunk 60 above)
Comment (apaz-cli) [reply cli/loader_lib.c:198]: In a previous revision of the function, `buf` used to be passed in as an argument and then realloced if it was not large enough. The comment is no longer valid.

File: Make.inc (hunk 55 above)
Comment (apaz-cli) [reply Make.inc:1168]: By "the version symbol," it means the first part of `CSL_NEXT_GLIBCXX_VERSION`

**Comment by apaz-cli** [comment]
This PR should be ready to merge, unless there's something else to add. The previous changes were comment typos only.

**Comment by vtjnash** [comment]
There is a conflict now with CSL_NEXT_GLIBCXX_VERSION, since that was recently bumped, but once you resolve that, it seems good to me.

**Review by staticfloat — APPROVED** [review]

**Comment by giordano** [comment]
Final benchmarks, https://github.com/JuliaLang/julia/commit/f7d4edc0f4d66b783a19eb0bfd934c0bb074086e (`master`) vs [`7685f15` (#46976)](https://github.com/JuliaLang/julia/pull/46976/commits/7685f15f40acfbe0bc9369bd0ad019ee45486af4):

hot start:
```console
% hyperfine -r 50 "./julia --startup-file=no -e ''" "46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''"
Benchmark 1: ./julia --startup-file=no -e ''
  Time (mean ± σ):     114.4 ms ±   1.0 ms    [User: 87.2 ms, System: 75.9 ms]
  Range (min … max):   113.1 ms … 117.2 ms    50 runs
 
Benchmark 2: 46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''
  Time (mean ± σ):     114.6 ms ±   1.0 ms    [User: 88.6 ms, System: 74.2 ms]
  Range (min … max):   113.2 ms … 117.3 ms    50 runs
 
Summary
  './julia --startup-file=no -e ''' ran
    1.00 ± 0.01 times faster than '46976-mg-dlopen-libstdc++/julia --startup-file=no -e '''
```

cold start:
```console
% hyperfine --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' -r 50 "./julia --startup-file=no -e ''" "46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''"
Benchmark 1: ./julia --startup-file=no -e ''
  Time (mean ± σ):     253.1 ms ±   3.9 ms    [User: 141.5 ms, System: 175.6 ms]
  Range (min … max):   245.4 ms … 262.2 ms    50 runs
 
Benchmark 2: 46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''
  Time (mean ± σ):     249.6 ms ±   6.7 ms    [User: 134.3 ms, System: 178.0 ms]
  Range (min … max):   238.3 ms … 275.8 ms    50 runs
 
Summary
  '46976-mg-dlopen-libstdc++/julia --startup-file=no -e ''' ran
    1.01 ± 0.03 times faster than './julia --startup-file=no -e '''
```

Timings are compatible within error bars.  Note that in the meantime #45582 has been merged, so the fact timings are consistent is good because now this probe should be no-op.

Thanks a lot @apaz-cli for this work! :rocket:

**Comment by fxcoudert** [comment]
This has broken build on Linux with `USE_SYSTEM_CSL=1` in Homebrew. It passed for Julia 1.8.3 and fails for Julia 1.8.4 and 1.8.5. I believe the issue is this one: https://github.com/JuliaLang/julia/issues/47987
