### PR TITLE
[LibGit2] Teach tests to be resilient to `init.defaultBranch`

### LINKED ISSUE #44547: CI failures due to `main` vs `master` branches in LibGit2 tests on macOS
I see failures like https://build.julialang.org/#/builders/2/builds/3456/steps/5/logs/stdio

```
Error in testset LibGit2/libgit2:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/stdlib/v1.9/LibGit2/test/libgit2.jl:961
  Expression: LibGit2.name(brref) == "refs/heads/master"
   Evaluated: "refs/heads/main" == "refs/heads/master"
```

I don't know if it is macOS-specific but I notice it only on macOS. I'm also not sure if it occurs always.

### PR DESCRIPTION
**Pull request by staticfloat**
If a user runs the tests with a `~/.gitconfig` that provides an
`init.defaultBranch` that is not `master`, our tests fail.  Let's adjust
to the user's configuration as appropriate.

### CODE REVIEW

File: stdlib/LibGit2/test/libgit2.jl [hunk 1]
```diff
@@ -634,7 +634,7 @@ mktempdir() do dir
     commit_oid1 = LibGit2.GitHash()
     commit_oid2 = LibGit2.GitHash()
     commit_oid3 = LibGit2.GitHash()
-    master_branch = "master"
+    master_branch = LibGit2.getconfig("init.defaultBranch", "master")
```
Comment (vchuravy) [inline stdlib/LibGit2/test/libgit2.jl:637]: nitpick can we call this `default_branch` instead?

**Review by Keno — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@staticfloat Does this need backport to 1.6 and 1.7 as well? Or just 1.8?

**Comment by staticfloat** [comment]
Yeah, it wouldn't hurt
