### PR TITLE
Fix JULIA_EXCLUSIVE setting affinity on non-worker threads

### LINKED ISSUE #50702: JULIA_EXCLUSIVE with auto threads errors on 1.10, mac/arm64
Running
```
JULIA_EXCLUSIVE=1 julia --threads=auto 
```
with v1.10 now errors with
> ERROR: Too many threads requested for JULIA_EXCLUSIVE option

on macos, `versioninfo` is
```
Julia Version 1.10.0-beta1
Commit 6616549950e (2023-07-25 17:43 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

### PR DESCRIPTION
**Pull request by xal-0**
With JULIA_EXCLUSIVE=1, we would try to give both worker and interactive threads an exclusive CPU, causing --threads=auto to produce a "Too many threads requested" error.

Fixes #50702.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Review by topolarity — COMMENTED** [review]
This logic is a little odd to me - e.g. if `nthreadsi == 1` and `nmutator_threads == 2` we no longer end up setting affinity for any thread

Is that intentional?

**Comment by xal-0** [comment]
> This logic is a little odd to me - e.g. if `nthreadsi == 1` and `nmutator_threads == 2` we no longer end up setting affinity for any thread
> 
> Is that intentional?

It was not intentional! It should be fixed now:
```
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 1 -e ''
setting affinity of master thread to 0
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 2 -e ''
setting affinity of master thread to 0
setting affinity of thread 1 to 1
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 3 -e ''
setting affinity of master thread to 0
setting affinity of thread 1 to 1
setting affinity of thread 2 to 2
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 1,1 -e ''
setting affinity of thread 1 to 0
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 1,2 -e ''
setting affinity of thread 2 to 0
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 1,3 -e ''
setting affinity of thread 3 to 0
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 2,1 -e ''
setting affinity of thread 1 to 0
setting affinity of thread 2 to 1
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 2,2 -e ''
setting affinity of thread 2 to 0
setting affinity of thread 3 to 1
$ JULIA_EXCLUSIVE=1 ./usr/bin/julia-debug -t 3,3 -e ''
setting affinity of thread 3 to 0
setting affinity of thread 4 to 1
setting affinity of thread 5 to 2
```

File: src/threading.c [hunk 1]
```diff
@@ -794,6 +794,9 @@ void jl_start_threads(void)
 {
     int nthreads = jl_atomic_load_relaxed(&jl_n_threads);
     int ngcthreads = jl_n_gcthreads;
+    int nthreadsi = jl_n_threads_per_pool[0];
```
[the remark this answers is not in the document]
Comment (xal-0) [reply src/threading.c]: I did some renaming, and made #defines for the two hard-coded indices in `jl_n_threads_per_pool`.

File: src/julia.h [hunk 2]
```diff
@@ -2058,6 +2058,9 @@ extern JL_DLLIMPORT _Atomic(int) jl_n_threads;
 extern JL_DLLIMPORT int jl_n_gcthreads;
 extern int jl_n_markthreads;
 extern int jl_n_sweepthreads;
+
+#define JL_THREADPOOL_ID_INTERACTIVE 0
+#define JL_THREADPOOL_ID_DEFAULT 1
```
Comment (Keno) [inline src/julia.h:2063]: Thank you!

Comment (Keno) [reply src/julia.h:2063]: (I am well known for my hatred of magic integer constants).

File: src/threading.c [hunk 3]
```diff
@@ -778,9 +778,9 @@ void jl_init_threading(void)
     }
 
     jl_all_tls_states_size = nthreads + nthreadsi + ngcthreads;
-    jl_n_threads_per_pool = (int*)malloc_s(2 * sizeof(int));
-    jl_n_threads_per_pool[0] = nthreadsi;
-    jl_n_threads_per_pool[1] = nthreads;
+    jl_n_threads_per_pool = (int*)malloc_s(jl_n_threadpools * sizeof(int));
+    jl_n_threads_per_pool[JL_THREADPOOL_ID_INTERACTIVE] = nthreadsi;
+    jl_n_threads_per_pool[JL_THREADPOOL_ID_DEFAULT] = nthreads;
```
Comment (Keno) [inline src/threading.c:783]: Not that we currently have more than two, but if we're making this generic, should we be memset'ing the remaining threadpool counts to 0?

File: src/threading.c [hunk 4]
```diff
@@ -808,36 +811,42 @@ void jl_start_threads(void)
...
         jl_threadarg_t *t = (jl_threadarg_t *)malloc_s(sizeof(jl_threadarg_t)); // ownership will be passed to the thread
         t->tid = i;
         t->barrier = &thread_init_done;
         uv_thread_create(&uvtid, jl_threadfun, t);
-        if (exclusive) {
-            mask[i] = 1;
+
+        // Interactive pool threads get the low IDs, so check if this is a
+        // default pool thread.  The master thread is already on CPU 0.
+        if (exclusive && i >= ninteractive_threads) {
```
Comment (Keno) [inline src/threading.c:846]: This is a bit of a behavior change, but I do like the new behavior better. However, we should probably update the documentation (https://github.com/JuliaLang/julia/blob/master/doc/src/manual/environment-variables.md#julia_exclusiveid-julia_exclusive) to mention that interactive threads remain under OS control.

**Review by Keno — APPROVED** [review]
Nice work

File: src/threading.c [hunk 5]
```diff
@@ -808,36 +811,42 @@ void jl_start_threads(void)
...
+            mask[i - ninteractive_threads] = 1;
```
Comment (topolarity) [inline src/threading.c:847]:
```suggestion
            assert(i - ninteractive_threads < cpumasksize);
            mask[i - ninteractive_threads] = 1;
```

An assert like this is good practice, so that someone changing this logic in the future doesn't accidentally start corrupting memory (if they introduce a bug)

**Review by topolarity — APPROVED** [review]
Nicely done!

File: src/threading.c [hunk 6]
```diff
@@ -778,9 +778,9 @@ void jl_init_threading(void)
     }
 
     jl_all_tls_states_size = nthreads + nthreadsi + ngcthreads;
-    jl_n_threads_per_pool = (int*)malloc_s(2 * sizeof(int));
-    jl_n_threads_per_pool[0] = nthreadsi;
-    jl_n_threads_per_pool[1] = nthreads;
+    jl_n_threads_per_pool = (int*)malloc_s(jl_n_threadpools * sizeof(int));
```
Comment (topolarity) [inline src/threading.c:781]:
```suggestion
    jl_n_threads_per_pool = (int*)calloc_s(jl_n_threadpools * sizeof(int));
```

**Comment by giordano** [comment]
Git history and diff seem to be messed up

**Comment by topolarity** [comment]
Our CI seems to have fallen over, but this has passed tests repeatedly on all platforms so I'll go ahead and merge it.
