### PR TITLE
Check that matrix is symmetric/Hermitian in dense Cholesky

### LINKED ISSUE #189: Dense and sparse cholfact handles deviations from symmetry differently
Right now sparse Cholesky factorization checks for symmetry in contrast to dense Cholesky.

``` julia
julia> A = speye(4);A[1,2] = eps();

julia> cholfact(A)
ERROR: ArgumentError: sparse matrix is not symmetric/Hermitian
 in cholfact at sparse/cholmod.jl:980
 in cholfact at sparse/cholmod.jl:1055

julia> cholfact(full(A))
Base.LinAlg.Cholesky{Float64,Array{Float64,2},:U} with factor:
4x4 Base.LinAlg.UpperTriangular{Float64,Array{Float64,2}}:
 1.0  2.22045e-16  0.0  0.0
 0.0  1.0          0.0  0.0
 0.0  0.0          1.0  0.0
 0.0  0.0          0.0  1.0
```

It is an easy fix to make this consistent, but which solution is preferred. Right now I lean towards the sparse solution where the matrix is checked for symmetry. If the user wants to bypass the check, there should be `cholfact(Symmetric)` method defined which is already the case for `cholfact(Sparse)`.

### PR DESCRIPTION
**Pull request by andreasnoack**
This fixes https://github.com/JuliaLang/LinearAlgebra.jl/issues/189 by checking that the input matrix is symmetric/Hermitian before computing the Cholesky factorization. This was already the behavior for sparse matrices but not for dense matrices where we simply ignored either the lower or upper part of the input. The check for symmetry can be avoided by using the `Hermitian` immutable.

While making this change, I realized how wild the dense Cholesky constructors have grown. Most of this is because of the `Val` dispatch for turning pivoting on and off. It was possible to clean it up a little bit but I think a full cleanup would require removal of the `Val` dispatch one way or another. Eliminating the `Val` here is beyond the scope of this PR but I've added a comment about this.

### CODE REVIEW

File: base/linalg/cholesky.jl [hunk 1]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
...
+Compute the Cholesky factorization of a positive definite matrix `A`
+and return the UpperTriangular matrix `U` such that `A = U'U`.
+"""
+function chol(A::StridedMatrix)
+    ishermitian(A) || throw(ArgumentError("matrix is not symmetric/Hermitian. Consider calling chol(Hermitian(A)) instead."))
+    return chol(Hermitian(A))
+end
+
+## Numbers
 """
```
Comment (kshyatt) [inline base/linalg/cholesky.jl]: Isn't the function signature here wrong?

Comment (andreasnoack) [inline base/linalg/cholesky.jl]: Are you talking about the `args...` part?

Comment (kshyatt) [inline base/linalg/cholesky.jl]: Yeah, does that need to be in the sig?

Comment (andreasnoack) [inline base/linalg/cholesky.jl]: Often the documentation signatures cheat a bit for simplification. I think that having the `args...` part in the docstring would confuse more than help. Maybe you could write that "extra arguments are ignored". However, this is not part of the change in this PR so if we want that, it could be done in a separate PR.

Comment (kshyatt) [inline base/linalg/cholesky.jl]: Sure; I just want to make sure the docs still work! On the other hand I don't think the masses are really clamoring for `chol(Number)` that we need to worry about it :).

File: base/linalg/cholesky.jl [hunk 2]
```diff
@@ -3,6 +3,29 @@
...
+# In the methods below, LAPACK is called when possible, i.e. StridedMatrices with Float32,
+# Float64, Complex{Float32}, and Complex{Float64} element types. For other element or
+# matrix types, the unblocked Julia implementation in _chol! is used. For cholfact
+# and cholfact! pivoting is supported through a Val{Bool} argument. A type argument is
+# necessary for type stability since the output cholfact and cholfact! is either Cholesky or
+# PivotedCholesky. The latter is only
+# supported for the four LAPACK element types. For other types, e.g. BigFloats Val{true} will
+# give an error. It is required that the input is Hermitian (including real symmetric) either
+# through the Hermitian and Symmetric views or exact symmetric or Hermitian elements which
+# is checked then checked and an error is thrown if the check fails. The dispatch
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: checked then checked?

File: base/linalg/cholesky.jl [hunk 3]
```diff
@@ -3,6 +3,29 @@
...
+# is further complicated by a limitation in the formulation of Unions. The relevant union
+# would be Union{Symmetric{T<:Real,S}, Hermitian} but, right now, it doesn't work in Julia
+# so we'll have to define methods for the two elements of the union separately.
+
+# FixMe? The dispatch below seems overly complicated. One simplifacation could be to merge
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: simplification

File: base/linalg/cholesky.jl [hunk 4]
```diff
@@ -3,6 +3,29 @@
...
+# the two Cholesky types into a single. It would remove the need for Val completely but
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: s/a single/one/

File: base/linalg/cholesky.jl [hunk 5]
```diff
@@ -3,6 +3,29 @@
...
+# the cost would be extra unnecessary/ununsed fields for the unpivoted Cholesky and runtime # checks of those fields before calls to LAPACK to check which version of the Cholesky
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: missing line break

File: base/linalg/cholesky.jl [hunk 6]
```diff
@@ -23,24 +46,27 @@ function CholeskyPivoted{T}(A::AbstractMatrix{T}, uplo::Char, piv::Vector{BlasIn
     CholeskyPivoted{T,typeof(A)}(A, uplo, piv, rank, tol, info)
 end
 
-function chol!{T<:BlasFloat}(A::StridedMatrix{T}, ::Type{UpperTriangular})
+
+# _chol!. Internal methods for calling unpivoted Cholesky in LAPACK
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: calling ... on

File: doc/stdlib/linalg.rst [hunk 7]
```diff
@@ -169,17 +169,17 @@ Linear algebra functions in Julia are largely implemented by calling functions f
 
    Compute the square root of a non-negative number ``x``\ .
 
-.. function:: cholfact(A::StridedMatrix, uplo::Symbol, Val{false}) -> Cholesky
+.. function:: cholfact!(A, uplo::Symbol, Val{false}) -> Cholesky
```
Comment (tkelman) [inline doc/stdlib/linalg.rst]: is non-in-place cholfact still documented?

File: base/linalg/cholesky.jl [hunk 8]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
...
+
+## for StridedMatrices, check that matrix is symmetric/Hermitian
+"""
+    chol(A) -> U
+
+Compute the Cholesky factorization of a positive definite matrix `A`
+and return the UpperTriangular matrix `U` such that `A = U'U`.
+"""
+function chol(A::StridedMatrix)
+    ishermitian(A) || throw(ArgumentError("matrix is not symmetric/Hermitian. Consider calling chol(Hermitian(A)) instead."))
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: maybe elaborate that "instead" means one of the triangles of the input will be ignored if you go with the suggestion?

File: base/linalg/cholesky.jl [hunk 9]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
...
     if rx != abs(x)
         throw(ArgumentError("x must be positive semidefinite"))
     end
     rxr = sqrt(rx)
     convert(promote_type(typeof(x), typeof(rxr)), rxr)
 end
+
+
+
+# chol!. Destructive methods for computing Cholesky factor of real symmetric of Hermitian
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: or Hermitian

File: base/linalg/cholesky.jl [hunk 10]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
...
+chol!(A::Hermitian)                                = _chol!(A.data, UpperTriangular)
+chol!{T<:Real,S<:StridedMatrix}(A::Symmetric{T,S}) = _chol!(A.data, UpperTriangular)
+function chol!(A::StridedMatrix)
+    ishermitian(A) || throw(ArgumentError("matrix is not symmetric/Hermitian. Consider calling chol!(Hermitian(A)) instead."))
+    return _chol!(A, UpperTriangular)
+end
+
+
+
+# chol. Non-destructive methods for computing Cholesky factor of real symmetric of
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: real symmetric or

File: base/linalg/cholesky.jl [hunk 11]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
...
+# Hermitian matrix. Promotes elements to type that is stable under sqrt roots.
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: "sqrt" or "square roots"

File: base/linalg/cholesky.jl [hunk 12]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
     return LowerTriangular(A)
 end
 
-"""
-    chol(A::AbstractMatrix) -> U
-
-Compute the Cholesky factorization of a positive definite matrix `A`
-and return the UpperTriangular matrix `U` such that `A = U'U`.
-"""
-function chol{T}(A::AbstractMatrix{T})
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: if I'm reading this right, is there no longer a definition for AbstractMatrix at all?

File: doc/stdlib/linalg.rst [hunk 13]
```diff
@@ -169,17 +169,17 @@ Linear algebra functions in Julia are largely implemented by calling functions f
...
+   The same as ``cholfact``\ , but saves space by overwriting the input ``A``\ , instead of creating a copy. An ``InexactError`` exception is thrown if the factorisation produces a number not representable by the element type of ``A``\ , e.g. for integer types.
 
-.. function:: cholfact(A::StridedMatrix, uplo::Symbol, Val{true}; tol = 0.0) -> CholeskyPivoted
+.. function:: cholfact!(A, uplo::Symbol, Val{true}) -> CholeskyPivoted
 
    .. Docstring generated from Julia source
 
-   Compute the pivoted Cholesky factorization of a dense symmetric positive semi-definite matrix ``A`` and return a ``CholeskyPivoted`` factorization. The ``uplo`` argument may be ``:L`` for using the lower part or ``:U`` for the upper part of ``A``\ . The default is to use ``:U``\ . The triangular Cholesky factor can be obtained from the factorization ``F`` with: ``F[:L]`` and ``F[:U]``\ . The following functions are available for ``PivotedCholesky`` objects: ``size``\ , ``\``\ , ``inv``\ , ``det``\ , and ``rank``\ . The argument ``tol`` determines the tolerance for determining the rank. For negative values, the tolerance is the machine precision.
```
Comment (tkelman) [inline doc/stdlib/linalg.rst]: looks like `tol` still exists so it should still be documented

File: base/linalg/cholesky.jl [hunk 14]
```diff
@@ -78,83 +104,149 @@ function chol!{T}(A::AbstractMatrix{T}, ::Type{LowerTriangular})
...
+## With pivoting
+### BLAS/LAPACK element types
+function cholfact!{T<:BlasReal,S<:StridedMatrix}(A::RealHermSymComplexHerm{T,S},
+        uplo::Symbol, ::Type{Val{true}}; tol = 0.0)
+    uplochar = char_uplo(uplo)
+    AA, piv, rank, info = LAPACK.pstrf!(uplochar, A.data, tol)
+    return CholeskyPivoted{eltype(AA),typeof(AA)}(AA, uplochar, piv, rank, tol, info)
+end
+
+### Non BLAS/LAPACK element types (generic). Since generic fallback for pivoted Cholesky ### is not implemented yet we throw an error
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: missing line break

File: doc/stdlib/linalg.rst (hunk 7 above)
Comment (andreasnoack) [inline doc/stdlib/linalg.rst]: This was a copy/paste error.

File: doc/stdlib/linalg.rst (hunk 13 above)
Comment (andreasnoack) [inline doc/stdlib/linalg.rst]: This is because of the copy/paste error in the `rst` file.

File: base/linalg/cholesky.jl (hunk 12 above)
Comment (andreasnoack) [inline base/linalg/cholesky.jl]: I'd restricted it to `StridedMatrix` to avoid overlap with `Hermitian` but it's not necessary in the version of this I ended up with so I've changed it back to `AbstractMatrix`.

File: base/linalg/cholesky.jl [hunk 15]
```diff
@@ -23,24 +47,27 @@ function CholeskyPivoted{T}(A::AbstractMatrix{T}, uplo::Char, piv::Vector{BlasIn
     CholeskyPivoted{T,typeof(A)}(A, uplo, piv, rank, tol, info)
 end
 
-function chol!{T<:BlasFloat}(A::StridedMatrix{T}, ::Type{UpperTriangular})
```
Comment (tkelman) [inline base/linalg/cholesky.jl]: So this renames the two-argument `chol!` method with the upper/lower type second argument, making it no longer available under the `chol!` name at all, right? I did a quick grep of packages and luckily it looks like no one was calling that in anything that's registered.

**Comment by tkelman** [comment]
I pushed a commit here that factors the almost-exactly-repeated (only the function name changes) error message for the non Hermitian case into a common helper function, and has some minor edits in a few comments. We can iterate on that if you disagree with anything in https://github.com/JuliaLang/julia/pull/16799/commits/905c2f4c114812c8bf5fb268a43b433b64db50b2, otherwise I think we're good.

File: test/linalg/cholesky.jl [hunk 16]
```diff
@@ -136,8 +136,8 @@ begin
     # Cholesky factor of Matrix with non-commutative elements, here 2x2-matrices
```
Comment (tkelman) [inline test/linalg/cholesky.jl]: you took your typo fix out from L120 in the rebase

Comment (andreasnoack) [inline test/linalg/cholesky.jl]: Should be fixed again now
