### PR TITLE
fix zero-dimensional `reverse!`

### LINKED ISSUE #58085: zero-dimensional `reverse` and `reverse!` for `AbstractArray` throw
Not a regression, the bug was here ever since the subfeature was introduced in v1.6 with PR #37367.

```julia-repl
julia> a = fill(7)
0-dimensional Array{Int64, 0}:
7

julia> reverse!(a)
ERROR: ArgumentError: reducing with add_sum over an empty collection of element type Union{} is not allowed.
You may be able to prevent this error by supplying an `init` value to the reducer.
Stacktrace:
  [1] _empty_reduce_error(f::Any, T::Type)
    @ Base ./reduce.jl:320
  [2] reduce_empty(::typeof(Base.add_sum), ::Core.TypeofBottom)
    @ Base ./reduce.jl:351
  [3] reduce_empty(op::Base.BottomRF{typeof(Base.add_sum)}, ::Type{Union{}})
    @ Base ./reduce.jl:360
  [4] reduce_empty_iter
    @ ./reduce.jl:384 [inlined]
  [5] reduce_empty_iter
    @ ./reduce.jl:383 [inlined]
  [6] foldl_impl(op::Base.BottomRF{typeof(Base.add_sum)}, nt::Base._InitialValue, itr::Tuple{})
    @ Base ./reduce.jl:49
  [7] mapfoldl_impl(f::typeof(identity), op::typeof(Base.add_sum), nt::Base._InitialValue, itr::Tuple{})
    @ Base ./reduce.jl:44
  [8] mapfoldl(f::Function, op::Function, itr::Tuple{}; init::Base._InitialValue)
    @ Base ./reduce.jl:175
  [9] mapfoldl
    @ ./reduce.jl:175 [inlined]
 [10] mapreduce
    @ ./reduce.jl:307 [inlined]
 [11] sum(f::Function, a::Tuple{})
    @ Base ./reduce.jl:535
 [12] sum(a::Tuple{}; kw::@Kwargs{})
    @ Base ./reduce.jl:564
 [13] _reverse!(A::Array{Int64, 0}, dims::Tuple{})
    @ Base ./arraymath.jl:77
 [14] _reverse!(A::Array{Int64, 0}, ::Colon)
    @ Base ./arraymath.jl:71
 [15] reverse!(A::Array{Int64, 0}; dims::Function)
    @ Base ./arraymath.jl:70
 [16] top-level scope
    @ REPL[4]:1

julia> reverse(a)
ERROR: ArgumentError: reducing with add_sum over an empty collection of element type Union{} is not allowed.
You may be able to prevent this error by supplying an `init` value to the reducer.
Stacktrace:
  [1] _empty_reduce_error(f::Any, T::Type)
    @ Base ./reduce.jl:320
  [2] reduce_empty(::typeof(Base.add_sum), ::Core.TypeofBottom)
    @ Base ./reduce.jl:351
  [3] reduce_empty(op::Base.BottomRF{typeof(Base.add_sum)}, ::Type{Union{}})
    @ Base ./reduce.jl:360
  [4] reduce_empty_iter
    @ ./reduce.jl:384 [inlined]
  [5] reduce_empty_iter
    @ ./reduce.jl:383 [inlined]
  [6] foldl_impl(op::Base.BottomRF{typeof(Base.add_sum)}, nt::Base._InitialValue, itr::Tuple{})
    @ Base ./reduce.jl:49
  [7] mapfoldl_impl(f::typeof(identity), op::typeof(Base.add_sum), nt::Base._InitialValue, itr::Tuple{})
    @ Base ./reduce.jl:44
  [8] mapfoldl(f::Function, op::Function, itr::Tuple{}; init::Base._InitialValue)
    @ Base ./reduce.jl:175
  [9] mapfoldl
    @ ./reduce.jl:175 [inlined]
 [10] mapreduce
    @ ./reduce.jl:307 [inlined]
 [11] sum(f::Function, a::Tuple{})
    @ Base ./reduce.jl:535
 [12] sum(a::Tuple{}; kw::@Kwargs{})
    @ Base ./reduce.jl:564
 [13] _reverse!(A::Array{Int64, 0}, dims::Tuple{})
    @ Base ./arraymath.jl:77
 [14] _reverse!(A::Array{Int64, 0}, ::Colon)
    @ Base ./arraymath.jl:71
 [15] reverse!(A::Array{Int64, 0}; dims::Function)
    @ Base ./arraymath.jl:70
 [16] _reverse(A::Array{Int64, 0}, dims::Function)
    @ Base ./arraymath.jl:60
 [17] reverse(A::Array{Int64, 0}; dims::Function)
    @ Base ./arraymath.jl:59
 [18] top-level scope
    @ REPL[5]:1
```

### PR DESCRIPTION
**Pull request by nsajko**
Also changed the check to compare against the tuple argument, instead of against the method static parameter for the tuple length. Should be better when the length isn't known at compile time.

Fixes #58085

### CODE REVIEW

File: base/arraymath.jl [hunk 1]
```diff
@@ -72,12 +72,12 @@ _reverse!(A::AbstractArray{<:Any,N}, ::Colon) where {N} = _reverse!(A, ntuple(id
 _reverse!(A, dim::Integer) = _reverse!(A, (Int(dim),))
 _reverse!(A, dims::NTuple{M,Integer}) where {M} = _reverse!(A, Int.(dims))
 function _reverse!(A::AbstractArray{<:Any,N}, dims::NTuple{M,Int}) where {N,M}
+    dims === () && return A # nothing to reverse
     dimrev = ntuple(k -> k in dims, Val{N}()) # boolean tuple indicating reversed dims
 
     if N < M || M != sum(dimrev)
         throw(ArgumentError("invalid dimensions $dims in reverse!"))
     end
-    M == 0 && return A # nothing to reverse
```
Comment (jishnub) [inline base/arraymath.jl:80]: Maybe this line can be moved up? This seems equivalent to `dims === ()`.

Comment (nsajko) [reply base/arraymath.jl:80]: As far as I understand the change you're suggesting is exactly the change in this PR?

Comment (jishnub) [reply base/arraymath.jl:80]: Yes, I meant having the check in terms of the type parameter, but it probably doesn't matter.

**Comment by nsajko** [comment]
As mentioned in the PR description, I believe changing `M == 0` to `dims === ()` is an improvement, because it results in better code when `M` isn't known, which is any time the length of `dims` isn't exactly known. See `code_typed`:

```julia-repl
julia> f(dims::NTuple{M}) where {M} = M == 0
f (generic function with 1 method)

julia> g(dims::NTuple{M}) where {M} = dims === ()
g (generic function with 1 method)

julia> code_typed(f, Tuple{Tuple{Any,Vararg}})
1-element Vector{Any}:
 CodeInfo(
1 ─ %1 = $(Expr(:static_parameter, 1))::Int64
│   %2 =   builtin (%1 === 0)::Bool
└──      return %2
) => Bool

julia> code_typed(g, Tuple{Tuple{Any,Vararg}})
1-element Vector{Any}:
 CodeInfo(
1 ─     return false
) => Bool
```
