### PR TITLE
Explicitly compute stride in unaliascopy for SubArray

### LINKED ISSUE #54100: Bug in `unaliascopy` for a `SubArray` with `AbstractRange` indices
```julia
julia> struct MyStepRange{T} <: OrdinalRange{T,T}
               r::StepRange{T,T}
       end

julia> for f in (:first, :last, :step, :length, :size)
               @eval Base.$f(r::MyStepRange) = $f(r.r)
       end

julia> Base.getindex(r::MyStepRange, i::Int) = r.r[i]

julia> A = rand(6);

julia> V = view(A, 2:2:4)
2-element view(::Vector{Float64}, 2:2:4) with eltype Float64:
 0.02519989368909037
 0.5834755544565842

julia> V2 = view(A, MyStepRange(2:2:4))
2-element view(::Vector{Float64}, 2:2:4) with eltype Float64:
 0.02519989368909037
 0.5834755544565842

julia> V == V2
true

julia> Base.unaliascopy(V2) # incorrect
2-element view(::Vector{Float64}, 2:2:4) with eltype Float64:
 6.9259266686866e-310
 0.02519989368909037

julia> Base.unaliascopy(V) # correct
2-element view(::Vector{Float64}, 1:1:2) with eltype Float64:
 0.02519989368909037
 0.5834755544565842
```
This seems to arise from 
https://github.com/JuliaLang/julia/blob/d8b9810b8908560cc4aaa744c0e587f4dfd11bfb/base/subarray.jl#L113-L119
where the offset and stride are being hard-coded instead of being computed.

Version:
```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.343
Commit 98f47474d83 (2024-04-15 04:40 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  LD_LIBRARY_PATH = :/usr/lib/x86_64-linux-gnu/gtk-3.0/modules
  JULIA_EDITOR = subl
```
This issue exists on v"1.11.0-beta1" as well. The result is correct on v"1.10.2".

### PR DESCRIPTION
**Pull request by jishnub**
Fix https://github.com/JuliaLang/julia/issues/54100 by computing the stride and offset explicitly. This is unlikely to be a performance concern, so we don't need to hard-code this.

### CODE REVIEW

**Review by mbauman — APPROVED** [review]
I see. We normalize some known ranges to `OneTo`s, but custom ranges are preserved, so their offset/stride aren't `0`/`1`.  Makes sense.

File: base/subarray.jl [hunk 1]
```diff
@@ -115,11 +115,14 @@ function unaliascopy(V::SubArray{T,N,A,I,LD}) where {T,N,A<:Array,I<:Tuple{Varar
...
-    SubArray{T,N,A,I,LD}(dest, map(_trimmedindex, V.indices), 0, Int(LD))
+    indices = map(_trimmedindex, V.indices)
+    stride1 = LD ? compute_stride1(dest, indices) : 0
+    offset1 = LD ? compute_offset1(dest, stride1, indices) : 0
+    SubArray{T,N,A,I,LD}(dest, indices, offset1, stride1)
 end
 # Get the proper trimmed shape
 _trimmedshape(::ScalarIndex, rest...) = (1, _trimmedshape(rest...)...)
-_trimmedshape(i::AbstractRange, rest...) = (maximum(i), _trimmedshape(rest...)...)
+_trimmedshape(i::AbstractRange, rest...) = (isempty(i) ? zero(eltype(i)) : maximum(i), _trimmedshape(rest...)...)
```
Comment (mbauman) [inline base/subarray.jl:125]: This predates you (obviously), but this just smells wrong to me here. How is this offset-array-safe?

Comment (N5N3) [reply base/subarray.jl:125]: For `AbstractRange` we do tail trimming here, i.e. `view([1,2,3,4], 2:3) == view([1,2,3], 2:3)`.
So it doesn't matter if `2:3` has offset axes.
