### PR TITLE
Do not raise BoundsError when indexing SubString with empty range

### LINKED ISSUE #15624: `SubString` reports out-of-bounds error for empty ranges
I encounter this error when remaking the documentation (after adding more documentation to Base):
```
# GENSTDLIB

INFO: loading docstrings from modules.
INFO: parsing external documentation.
ERROR: LoadError: BoundsError: attempt to access "          "
  at index [15:14]
 in getindex(::SubString{ASCIIString}, ::UnitRange{Int64}) at ./abstractarray.jl:0
```

I think this is due to an error in `SubString`. This works:
```
julia> "x"[3:2]
""
```

This should have the same result, but doesn't:
```
julia> SubString("x", 1, 1)[3:2]
ERROR: BoundsError: attempt to access "x"
  at index [3:2]
 in getindex(::SubString{ASCIIString}, ::UnitRange{Int64}) at /Users/eschnett/julia05nt/lib/julia/sys-debug.dylib:-1
 in eval(::Module, ::Any) at /Users/eschnett/julia05nt/lib/julia/sys-debug.dylib:-1
```

### PR DESCRIPTION
**Pull request by nalimilan**
Even if the range is out of bounds. Fixes #15624.

### CODE REVIEW

**Comment by vtjnash** [comment]
lgtm

File: base/strings/types.jl [hunk 1]
```diff
@@ -79,9 +79,7 @@ convert{T<:AbstractString}(::Type{SubString{T}}, s::T) = SubString(s, 1, endof(s
 bytestring{T <: ByteString}(p::SubString{T}) = bytestring(p.string.data[1+p.offset:p.offset+nextind(p, p.endof)-1])
 
 function getindex(s::AbstractString, r::UnitRange{Int})
-    if first(r) < 1 || endof(s) < last(r)
-        throw(BoundsError(s, r))
-    end
+    checkbounds(s, r) || throw(BoundsError(s, r))
```
Comment (hayd) [inline base/strings/types.jl]: Should we test some examples where this throws?

Comment (nalimilan) [inline base/strings/types.jl]: There are tests for that in `test/strings/types.jl` already. That's why I only added tests for when this should work.
