### PR TITLE
Fix layout flags for types that have oddly sized primitive type fields

### LINKED ISSUE #49318: Inconsistent claims about padding in structs
This came up while experimenting with `@flaggify` and `@bitfieldify` from [FieldFlags.jl](https://github.com/Seelengrab/FieldFlags.jl) (name pending).

```julia
julia> primitive type Foo_prim 40 end

julia> struct Foo_p
           a::Foo_prim
       end

julia> struct Foo
           a::NTuple{5, UInt8}
       end

julia> sizeof(Foo_prim)
5

julia> sizeof(Foo_p)
8

julia> sizeof(NTuple{5, UInt8})
5

julia> sizeof(Foo)
5

julia> Base.datatype_haspadding(NTuple{5, UInt8})
false

julia> Base.datatype_haspadding(Foo)
false

julia> Base.datatype_haspadding(Foo_prim)
false

julia> Base.datatype_haspadding(Foo_p)
false # ?!
```

How can `Foo_p` grow in size from 5 to 8 bytes, when there isn't supposed to be any padding there?

Additionally, `Base.padding` doesn't seem to take this "magic end-struct padding" into account, not even for structs that do claim to have padding:

```julia
julia> sizeof(Tuple{UInt32, UInt8})
8

julia> Base.datatype_haspadding(Tuple{UInt32, UInt8})
true

julia> Base.padding(Tuple{UInt32, UInt8})
Base.Padding[] # ?!

julia> Base.padding(Foo_p)
Base.Padding[]
```

So either `Foo_p` doesn't have padding, which begs the question why it's 8 bytes in size, or it does, which begs the question why it claims that it doesn't.

### LINKED ISSUE #58434: Inconsistent results from `===` on non-power-of-2 primitives
Here is an MRE we tracked down from our real code:
```julia
julia> primitive type ByteString18 (18 * 8) end

julia> a = reinterpret(ByteString18, ntuple(_->0x0, 18))
ByteString18(0x000000000000000000000000000000000000)

julia> (a,) === (a,)
false

julia> (a,) === (a,)
true

julia> (a,) === (a,)
false

julia> (a,) === (a,)
false

julia> (a,) === (a,)
false

julia> (a,) === (a,)
true
```

This is definitely wrong.
This reproduces for me on ARM Mac, x86 Linux, 1.10, and 1.12.

And it's not unique to `reinterpret`, it shows up with `zext` as well:
```julia
julia> primitive type ByteString18 (18 * 8) end

julia> a = Core.zext_int(ByteString18, 0x0)
ByteString18(0x000000000000000000000000000000000000)

julia> (a,) === (a,)  # should obviously be `true`
false
```

And also, it's not unique to being all 0s,  it works for reinterpreting any values in there.
```
julia> a = reinterpret(ByteString18, ntuple(_->0xaf, 18)); C = 10000; sum(@eval ((a,) === (a,)) for _ in 1:C) / C
0.7306
```

So far, we've only ever seen this during constant-folding, but I'm not sure if that's 100% true or not.

Finally, as you'd expect, this issue doesn't seem to affect primitive types that have standard power-of-2 integer sizes: 1,2,4,8,16,32. But most of the rest are affected:

Image
ratio of times `(a,) === (a,)` returns `true` out of 3,000 iterations, for different primitive type byte-widths.
<details>
<summary>Code to generate the above plot:</summary>

```julia
const MAX_PRIMITIVE_BYTE_STRING = 16 * 8
for BYTES in 1:MAX_PRIMITIVE_BYTE_STRING
    name = Symbol("ByteString$(BYTES)")
    BITS = BYTES * 8
    @eval begin
        primitive type $(name) $(BITS) end
    end
end

out = let iters = 3000, out = Float64[]
    for N in 1:32
        T = eval(Symbol("ByteString$(N)"))
        a = reinterpret(T, ntuple(_->0x0, N))
        push!(out, sum(@eval(($a,) === ($a,)) for _ in 1:iters) / iters)
    end
    out
end

using Plots

plot(out)
vline!([1,2,4,8,16,32])
```
</details>

### PR DESCRIPTION
**Pull request by gbaraldi**
This is caused because for LLVMs sake we have to say that the oddly typed field is smaller than it actually is. (I wonder if we could represent it as an iN field in a struct and have it work but the result would be the same for now)

Fix #58434, fix #49318, close #49362.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
SGTM, though I think this is supposed to be set on the primitive type, so that it gets copied here correctly, rather than computed here?

File: test/core.jl [hunk 1]
```diff
@@ -8534,3 +8534,9 @@ module GlobalBindingMulti
     using .M.C
 end
 @test GlobalBindingMulti.S === GlobalBindingMulti.M.C.S
+
+#58434 bitsegal comparison of oddly sized fields
+primitive type ByteString58434 (18 * 8) end
+
+@test Base.datatype_isbitsegal(Tuple{ByteString58434}) == false
+@test Base.datatype_haspadding(Tuple{ByteString58434}) == true
```
Comment (Seelengrab) [inline test/core.jl:8542]:
```suggestion
@test Base.datatype_haspadding(Tuple{ByteString58434}) == (length(Base.padding(Tuple{ByteString58434})) > 0) 
```

Might be good as a sanity check to ensure that reflection stays consistent with this, since this fluctuated in the past.

**Comment by oscardssmith** [comment]
> (I wonder if we could represent it as an iN field in a struct and have it work but the result would be the same for now)

Theoretically we should be able to do this (but it will need very careful testing)

**Comment by Seelengrab** [comment]
This might also fix #49318, come to think of it :thinking: The symptoms are very closely related, I think.

**Comment by giordano** [comment]
Does this fix #42326 too?

**Comment by Seelengrab** [comment]
I can confirm that this PR fixes the inconsistent padding claims in #49318! The struct still ends up larger than technically necessary, but at least the padding claims are correct now.

> Does this fix https://github.com/JuliaLang/julia/issues/42326 too?

Potentially - on my x86_64 machine, I now also get 

```
julia> primitive type PadAfter64 448 end

julia> mutable struct CheckPadAfter64
           a::UInt64
           pad::PadAfter64
           b::UInt64
       end

julia> fieldoffset(CheckPadAfter64, 3)
0x0000000000000050
```

**Comment by giordano** [comment]
Ah, right, Gabriel mentioned at https://github.com/JuliaLang/julia/issues/42326#issuecomment-2282919660 that LLVM 18 may have fixed that issue, and [I even later confirmed](https://github.com/JuliaLang/julia/issues/42326#issuecomment-2293815968) that `fieldoffset` was consistent on the different architectures.

**Comment by giordano** [comment]
I marked this PR to close #49362 since it'd solve the same issue (and that PR is stuck).  Are there any tests from that PR that are worth incorporating here?

**Comment by Seelengrab** [comment]
#49362 is not quite the same, as that PR (I think) deals with `sizeof(Tuple{UInt136}) == 24`, while this PR keeps this as `32`. That's why I mentioned that this PR fixes the inconsistency https://github.com/JuliaLang/julia/issues/49318 was originally about. The (in my view, unnecessary) additional padding is a seperate topic that shouldn't really hold up this PR.

**Comment by gbaraldi** [comment]
The padding is necessary for ABI reasons, we assume that a type like that is aligned to 16 bytes, so if it uses slightly more than 16 we go to 32. There are compelling reasons for that, like being able to ignore the existing bytes there when doing a store for example

File: test/core.jl [hunk 2]
```diff
@@ -8534,3 +8534,9 @@ module GlobalBindingMulti
     using .M.C
 end
 @test GlobalBindingMulti.S === GlobalBindingMulti.M.C.S
+
+#58434 bitsegal comparison of oddly sized fields
+primitive type ByteString58434 (18 * 8) end
+
+@test Base.datatype_isbitsegal(Tuple{ByteString58434}) == false
+@test Base.datatype_haspadding(Tuple{ByteString58434}) == (length(Base.padding(Tuple{ByteString58434})) > 0)
```
Comment (giordano) [inline test/core.jl:8542]:
```suggestion
@test Base.datatype_haspadding(Tuple{ByteString58434}) == (length(Base.padding(Tuple{ByteString58434})) > 0)
```

**Review by PatrickHaecker — APPROVED** [review]
I do not know the code base, but this change looks good to me both the changed lines itself and also in the context of the code's surrounding.

Additionally, I confirmed, that this fixes the [test case](https://github.com/JuliaLang/julia/issues/58434#issuecomment-2887193897) from #58434.
