### PR TITLE
Fix bug in `invmod` [RFC]

### LINKED ISSUE #29971: `invmod` gives wrong results for moduli close to `typemax`
Julia 1.0.1

```
julia> invmod(1, 127)
1

julia> invmod(Int8(1), Int8(127))
126
```

Similarly for unsigned types:

```
julia> invmod(3, 251)
84

julia> Int(invmod(UInt8(3), UInt8(251)))
79
```

### PR DESCRIPTION
**Pull request by sam0410**
Fixes #29971

### CODE REVIEW

**Comment by sam0410** [comment]
Hi @ararslan, I just came back to check if this could be merged.

**Comment by ararslan** [comment]
I'm not familiar enough with the code myself to review it, but if @eschnett isn't around then I'll request a different person to review.

File: base/intfuncs.jl [hunk 1]
```diff
@@ -161,8 +161,7 @@ function invmod(n::T, m::T) where T<:Integer
     g != 1 && throw(DomainError((n, m), "Greatest common divisor is $g."))
     m == 0 && throw(DomainError(m, "`m` must not be 0."))
     # Note that m might be negative here.
-    # For unsigned T, x might be close to typemax; add m to force a wrap-around.
-    r = mod(x + m, m)
+    r = (T <: Unsigned && x == typemax(x)) ? mod(x + m, m) : mod(x, m)
```
Comment (rfourquet) [inline base/intfuncs.jl]: I can't review now, but it seems this needs a `Base.hastypemax` check, not all unsigned types have `typemax`

**Comment by eschnett** [comment]
A `hastypemax` check seems reasonable. Otherwise, when I looked at that code I was easily able to fool myself, so I tested it for `Int8` / `UInt8` in a loop for all 65536 possible inputs. That kind of test can easily be repeated. (Maybe I even defined a custom `Int4` / `UInt4` type for testing...)

File: base/intfuncs.jl (hunk 1 above)
Comment (sam0410) [reply base/intfuncs.jl]: Thanks for your time @rfourquet . I see that all the Integer types have `typemax` defined. Correct me if I am wrong.

```
julia> intsubtypes = vcat(map(subtypes, subtypes(Integer))...)
11-element Array{Any,1}:
 BigInt 
 Int128 
 Int16  
 Int32  
 Int64  
 Int8   
 UInt128
 UInt16 
 UInt32 
 UInt64 
 UInt8  

julia> map(x -> hasmethod(typemax, Tuple{Type{x}}), intsubtypes)
11-element Array{Bool,1}:
 false
  true
  true
  true
  true
  true
  true
  true
  true
  true
  true
```

Comment (rfourquet) [reply base/intfuncs.jl]: I don't know an unsigned type without `typemax`, but it can exist and a `hastypemax` is free for the known types, so just put it, it may save us from a future bug report :)

Comment (sam0410) [reply base/intfuncs.jl]: Oh! I will do that straightaway. Thanks :)

**Comment by sam0410** [comment]
@eschnett , are you suggesting to add more tests? I added the `hastypemax` check that you and @rfourquet suggested.

Also, I am not sure why this check is failing (because of failure in `profile` tests), I think it is not because of the code I wrote.

**Comment by eschnett** [comment]
I'm not necessarily suggesting to add more tests, since adding 65536 tests might be too expensive to run. But if there is uncertainty about whether the new code is correct, then it's easy to check it very thoroughly.

**Comment by sam0410** [comment]
Thanks @eschnett ! I added a few tests (which were failing on master), just to be sure the code covers everything.

**Comment by KlausC** [comment]
Please look at this harmless-looking test case:
```
@test invmod(Uint8(3), UInt8(124)), UInt8(3)) == invmod(3, 124) # ( == 83)
```
which fails despite of the suggested changes. I found this code change more useful:
```
r = (T <: Unsigned && hastypemax(typeof(x)) && x > typemax(x)>>1) ? mod(x + m, m) : mod(x, m)
```

**Comment by sam0410** [comment]
Thanks for pointing that out @KlausC . I added the change.
I wrote the tests locally ( what @eschnett had suggested) and it passes.
```
julia> @testset "validation of " begin
           for i in  0 : (typemax(UInt8)-1)
               for j in 1 : (typemax(UInt8)-1) 
                   g, x, y = gcdx(i, j)
                   if(g==1)
                     @test invmod(UInt8(i), UInt8(j)) == invmod(i,j)  
                   end
               end
           end
       end
Test Summary: |  Pass  Total
validation    | 39384  39384
Test.DefaultTestSet("validation", Any[], 39384, false)

```

**Comment by KlausC** [comment]
1. Why do you exclude `typemax(UInt8)`from the tests? The code should be correct also then.2. 
2. Why not also the complete test set for `Int8`.
3. The test case I gave (3, 124) (or similar) should be tested with all integer types.

**Comment by sam0410** [comment]
`1.`  My bad. Its working for `typemax(UInt8)`.
`2.`  I have checked for `Int8` locally. But have not added it as it is time consuming.
```
julia> @testset "validation" begin
           for i in typemin(Int8) : typemax(Int8)
               for j in typemin(Int8) : typemax(Int8)
                   if !(j==0 || (i==typemin(Int8) && j==-1)|| (j==typemin(Int8) && i==-1))
                       g, x, y = gcdx(i, j)
                       if(g==1)
                           @test invmod(Int8(i), Int8(j)) == invmod(i,j)
                       end
                   end
               end
           end
       end
Test Summary: |  Pass  Total
validation    | 39916  39916
Test.DefaultTestSet("validation", Any[], 39916, false)

```
`3.` You are right. Made the change.

**Comment by fjarri** [comment]
Just wondering what the status of this PR is, are there any plans of merging it?

Also some questions:

1. I think the test above should have
```
           for i in Int(typemin(Int8)) : Int(typemax(Int8))
               for j in Int(typemin(Int8)) : Int(typemax(Int8))
```
otherwise 
```
invmod(Int8(i), Int8(j)) == invmod(i,j)
```
is always true (because `i` and `j` are already `Int8`). Although, granted, it still passes after this change.

2. Shouldn't there be a check for `m != 1 && m != -1` in addition to `m != 0`? After all, everything modulo `1` is `0`, so there's no inverse.

3. What is the actual contract of `invmod`, that is should the result satisfy `rem(n * res, m) == 1` or `mod(n * res, m) == 1` (assuming no overflow)? This is important when `n` or `m` are negative. From the name it feels like it is supposed to be the latter, but if you try it on the values from the testsuite:

```
julia> n, m = -1, 3; r = invmod(n, m); println((r, mod(n * r, m), rem(n * r, m)))
(2, 1, -2)

julia> n, m = -1, -3; r = invmod(n, m); println((r, mod(n * r, m), rem(n * r, m)))
(-1, -2, 1)
```

That is, in the first case the result of `invmod` gives `1` for `mod`, but in the second case for `rem`. 

2 and 3 may call for a separate issue though, or a clarification in the docstring at least.

**Comment by simonbyrne** [comment]
To follow up on @fjarri's points, I would suggest the following:
```julia
    for x in typemin(Int8) : typemax(Int8)
        for m in typemin(Int8) : typemax(Int8)
            if m != 0 && gcdx(x, m)[1] == 1
                @test mod(invmod(x, m) * x, m) != mod(1,m)
            end
        end
    end
```

In particular with regards to point 3, the emphasis is that we guarantee they will be _congruent_ modulo `m`, not necessarily equal, hence we need the `mod` on both sides.

**Comment by simonbyrne** [comment]
Should we also open an issue for the `gcd` overflow?

**Comment by KlausC** [comment]
Happy birthday!!

**Comment by JeffBezanson** [comment]
@simonbyrne Is this ok to merge? My only question would be whether it's possible to do without `hastypemax` e.g. by checking for some sort of overflow?

**Comment by JeffBezanson** [comment]
Though note that you might want to wait 2 weeks, in order to merge it on the birthday I share with this PR :joy:

**Comment by KlausC** [comment]
We could replace `hastypemax(typeof(x)) && x > typemax(x)>>1` by `2*x < x` in this case.
But why is the use of `hastypemax` bad? It is completely removed from the code at compile time.

**Comment by KlausC** [comment]
Just want to use this to remind of Jeff's birthday.
Happy birthday, and may all your wishes be realistic enough to become true!

 :fireworks:  :bouquet:  :wine_glass:

**Comment by simonbyrne** [comment]
Okay, I've managed to get the exhaustive tests working, and fixed what I think was an error in the docs.

There are some weird branches to work around the strange overflow behaviour of `gcdx` (see https://github.com/JuliaLang/julia/issues/33781#issuecomment-570459336). Once that is fixed, this can be cleaned up.

**Comment by vtjnash** [comment]
Any last words? I don't think we're going to wait for Jeff's birthday to come around again. But I rebased and seems to work still (even after #35507), though I had to alter it.

**Comment by JeffBezanson** [comment]
I was considering making this an annual birthday ritual, but I figure most people would prefer just merging it instead.

**Comment by tkluck** [comment]
A bisect seems to indicate that this breaks the tests in my `GaloisFields.jl`package with the following stack trace:
```
  Test threw exception
  Expression: F[x;] ./ F[y;] == F.(x .* invmod.(y, char(F)))
  MethodError: no method matching typemin(::Type{BigInt})
  Closest candidates are:
    typemin(::Union{Dates.DateTime, Type{Dates.DateTime}}) at /home/tkluck/src/julia/usr/share/julia/stdlib/v1.6/Dates/src/types.jl:427
    typemin(::Union{Dates.Date, Type{Dates.Date}}) at /home/tkluck/src/julia/usr/share/julia/stdlib/v1.6/Dates/src/types.jl:429
    typemin(::Union{Dates.Time, Type{Dates.Time}}) at /home/tkluck/src/julia/usr/share/julia/stdlib/v1.6/Dates/src/types.jl:431
    ...
  Stacktrace:
    [1] invmod(n::BigInt, m::Int64)
      @ Base ./intfuncs.jl:224
    [2] _broadcast_getindex_evalf
      @ ./broadcast.jl:648 [inlined]
    [3] _broadcast_getindex
      @ ./broadcast.jl:621 [inlined]
    [4] _getindex
      @ ./broadcast.jl:645 [inlined]
    [5] _getindex
      @ ./broadcast.jl:644 [inlined]
    [6] _broadcast_getindex
      @ ./broadcast.jl:620 [inlined]
    [7] _getindex
      @ ./broadcast.jl:645 [inlined]
    [8] _broadcast_getindex
      @ ./broadcast.jl:620 [inlined]
    [9] getindex
      @ ./broadcast.jl:575 [inlined]
   [10] copy
      @ ./broadcast.jl:876 [inlined]
   [11] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, Type{𝔽₂₉}, Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(*), Tuple{Vector{BigInt}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(invmod), Tuple{Vector{BigInt}, Int64}}}}}})
      @ Base.Broadcast ./broadcast.jl:837
   [12] top-level scope
      @ ~/src/julia/regress.jl:8
   [13] include(mod::Module, _path::String)
      @ Base ./Base.jl:389
   [14] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:285
   [15] _start()
      @ Base ./client.jl:485
```

**Comment by vtjnash** [comment]
Ah, seems to be missing some `hastypemax` calls in the gcdx work-around code
