### PR TITLE
Make zero on array of arrays etc apply recursively

### LINKED ISSUE #38064: zero is not recursive
An array of arrays is a valid vector space.
Even an array of arrays of different sizes.

This is why we define `transpose`, `adjoint`, `dot` and `+` recursively

However we do not do the same for `zero`, which is a fundermental vector space operation.

```julia
julia> zero([2,2])
2-element Array{Int64,1}:
 0
 0

julia> zero([[2,2], [3,3,3]])
ERROR: MethodError: no method matching zero(::Type{Array{Int64,1}})
```

This is a problem for AD purposes.
Types that are used to represent a tangent/cotangent need to have the basic vector space operations defined on them.
So if we want to say that the cotangent of an array of arrays of numbers is an an array of arrays of numbers then we should really have `zero` on it

### PR DESCRIPTION
**Pull request by oxinabox**
Closes https://github.com/JuliaLang/julia/issues/38064

I wonder if this breaks things, in practice. It shouldn't. Since old code behavior errored for the cases I am aware of.
As discussed in #38064, this definition is needed to be consistent with our other linear algebra operations,
and with us considering a vector of vectors etc as a vector space.

### CODE REVIEW

File: base/abstractarray.jl [hunk 1]
```diff
@@ -1198,7 +1198,8 @@ function copymutable(a::AbstractArray)
 end
 copymutable(itr) = collect(itr)
 
-zero(x::AbstractArray{T}) where {T} = fill!(similar(x, typeof(zero(T))), zero(T))
+zero(x::AbstractArray{T}) where {T<:Number} = fill!(similar(x, typeof(zero(T))), zero(T))
+zero(x::AbstractArray) = map(zero, x)
```
Comment (jishnub) [inline base/abstractarray.jl:1202]: Should this use broadcasting instead, as custom sparse arrays might define their own broadcast styles and don't need to iterate over the entire array?

Comment (oxinabox) [reply base/abstractarray.jl:1202]: maybe? idk

Custom sparse arrays should probably be implementing their own `zero` function outright.
Since they likely have their own opinions about whether or not to store structural zeros etc (the SparseArrays stdlib does this).

Comment (mbauman) [reply base/abstractarray.jl:1202]: It's also a whole lot easier to define a single-argument `map(f, ::CustomArray)` than it is to define your own broadcast style. I think the map is fine; it's straightforward and obvious and even enables the laser-focused `map(::typeof(zero), ::CustomArray)`.

**Comment by oxinabox** [comment]
I do not understand the whitespace failure
https://buildkite.com/julialang/julia-master/builds/28131#018ad586-9fea-401c-b809-8aabe49f59ea/711-714

```


Whitespace check found 2 issues:
base/abstractarray.jl:3544 -- trailing blank lines
test/abstractarray.jl:1873 -- no trailing newline
make: *** [Makefile:129: check-whitespace] Error 1
```
Does it want trailing new lines or not?

D

File: base/abstractarray.jl [hunk 2]
```diff
@@ -3540,3 +3541,4 @@ function circshift!(a::AbstractVector, shift::Integer)
     reverse!(a)
     return a
 end
+
```
Comment (oxinabox) [inline base/abstractarray.jl:3544]:
```suggestion
```

File: test/abstractarray.jl [hunk 3]
```diff
@@ -1860,3 +1860,14 @@ f45952(x) = [x;;]
...
+@testset "zero" begin
+    @test zero([1 2; 3 4]) isa Matrix{Int}
+    @test zero([1 2; 3 4]) == [0 0; 0 0]
+
+    @test zero([1.0]) isa Vector{Float64}
+    @test zero([1.0]) == [0.0]
+
+    @test zero([[2,2], [3,3,3]]) isa Vector{Vector{Int}}
+    @test zero([[2,2], [3,3,3]]) == [[0,0], [0, 0, 0]]
+end
```
Comment (oxinabox) [inline test/abstractarray.jl:1873]:
```suggestion
end

```

**Comment by oxinabox** [comment]
one thing this does not handle is if the original array has `undef` elements.
I am not sure if it should or not.

**Comment by adienes** [comment]
this functionality was asked for on slack

possible for 1.11?

**Comment by vtjnash** [comment]
I don't forsee an issue with this, so let's merge

File: test/abstractarray.jl [hunk 4]
```diff
@@ -1950,3 +1950,14 @@ end
...
```
Comment (inkydragon) [inline test/abstractarray.jl:1963]: fix Whitespace check: `test/abstractarray.jl:1963 -- no trailing newline`
```suggestion
end

```

**Comment by Jutho** [comment]
I think it is great that this is fixed. Nonetheless, I would like to advertise https://github.com/Jutho/VectorInterface.jl which on his README lists some other potential issues (https://github.com/Jutho/VectorInterface.jl?tab=readme-ov-file#current-situation-and-problems-in-julia). My apologies if this is out of place.
