### PR TITLE
codegen: Mark resolved `const` `GlobalRef` as method root

### LINKED ISSUE #60846: Trimming: Elements added to global `const` become garbage collected
MWE:
```julia
mutable struct Foo
    x::Int
end

const storage = Foo[]

Base.@ccallable function add_one(x::Cint)::Cint
    i = length(storage)

    println(Core.stdout, "Creating Foo($i)")

    foo = Foo(i)
    finalizer(foo) do x
        println(Core.stdout, "...Deleting Foo($(x.x))")
    end
    
    push!(storage, foo)

    println(Core.stdout, "Starting GC:")
    GC.gc()
    println(Core.stdout, "...GC done")

    return x + 1
end
```
When built with `trim = "safe"` and repeatedly called, results in
```
julia> run(`python ./build/example.py`)
Creating Foo(0)
Starting GC:
...Deleting Foo(0)
...GC done
Creating Foo(1)
Starting GC:
...Deleting Foo(1)
...GC done
Creating Foo(2)
Starting GC:
...Deleting Foo(2)
...GC done
Creating Foo(3)
Starting GC:
...Deleting Foo(3)
...GC done
Creating Foo(4)
Starting GC:
...Deleting Foo(4)
...GC done
Creating Foo(5)
Starting GC:
...Deleting Foo(5)
...GC done
Creating Foo(6)
Starting GC:
...Deleting Foo(6)
...GC done
Creating Foo(7)
Starting GC:
...Deleting Foo(7)
...GC done
Creating Foo(8)
Starting GC:
...Deleting Foo(8)
...GC done
Creating Foo(9)
fatal: error thrown and no exception handler available.
Core.ArgumentError(msg="jl_genericmemory_copyto requires source and dest to have same type")
...Deleting Foo(9)
ERROR: failed process: Process(`python ./build/example.py`, ProcessExited(1)) [1]
```
So `storage` grows as expected, but its elements are garbage collected. I checked the following:

* This is not the case when using `trim = "no"`. 
* This is not the case when using a non-const i.e `storage::Vector{Foo} = Foo[]`. So this is a work-around, but does not solve the dangers of `const`. 
* Using a `Dict` for the storage instead just leads to other error messages, but the problem seems to be the same. 
* Using a pre-allocated `storage` and `setindex!` makes no difference. 
* Using `Base.OncePerProcess` makes no difference. 

Tested on latest nightly, windows.

### PR DESCRIPTION
**Pull request by topolarity**
This allows `--trim` to safely* prune bindings without dropping the root required for the generated machine code.

Opening this PR with a "simple" solution to get numbers / opinions on the overhead of these extra roots.

The (significantly more complex) alternative will be to examine the bindings (back)edges during `--trim` serialization and reconstruct the relevant binding dependency edges at that time. I'll update this PR in-place with that solution if it seems like the right direction to go instead.

Resolves https://github.com/JuliaLang/julia/issues/60846.

\* As a caveat, uninferred GlobalRefs can lead to missing bindings at runtime, but this is out-of-scope for --trim.

### CODE REVIEW

**Comment by gbaraldi** [comment]
How was the code there not segfaulting? Because I thought in this case we just removed the globalref and got the underlying object but that was rooted by the code

**Comment by johroj** [comment]
> How was the code there not segfaulting? Because I thought in this case we just removed the globalref and got the underlying object but that was rooted by the code

Are you referring to the MWE I posted? I think got some segfaults too while exploring, but usually it would halt before that with some other error message.

**Comment by topolarity** [comment]
Shockingly small impact on the sysimage:
```
Total                   293292043
```
https://buildkite.com/julialang/julia-master/builds/54331#019c30cc-fd0f-4cc6-989c-ef6ae1c5376f/L2692

vs.
```
Total                   293268479
```
https://buildkite.com/julialang/julia-master/builds/54334#019c3107-6984-4458-84a3-e78986f9948f/L2482

23.6 KB difference

**Comment by topolarity** [comment]
@keno or @vtjnash any complaints about this solution?
Seems much simpler than trying to read the edges in `staticdata`

**Review by vtjnash — COMMENTED** [review]
This seems like it should work, since it should shove it into the global dict eventually, which we then prune during sysimage generation

File: src/codegen.cpp [hunk 1]
```diff
@@ -3505,6 +3505,8 @@ static jl_cgval_t emit_globalref(jl_codectx_t &ctx, jl_module_t *mod, jl_sym_t *
             undef_var_error_ifnot(ctx, ConstantInt::get(getInt1Ty(ctx.builder.getContext()), 0), name, (jl_value_t*)mod);
             return jl_cgval_t();
         }
+        // root is required to allow bindings to be pruned, especially by `--trim`
+        jl_temporary_root(ctx, constval);
```
Comment (vtjnash) [inline src/codegen.cpp]:
```suggestion
        if (jl_generating_output())
            jl_temporary_root(ctx, constval);
```
