### PR TITLE
ensure internal_obj_base_ptr checks whether objects past freelist pointer are in freelist

### LINKED ISSUE #50434: gcext test is often failing
The gcext test is failing. A quick fix would be to change the `length(errlines) == 0` check to use `isempty(errlines)` instead, which has special printing in Test and would likely quickly reveal the issue.
example: https://buildkite.com/julialang/julia-master/builds/25595#01892862-243e-4599-b390-cf005b815ea4

### PR DESCRIPTION
**Pull request by d-netto**
Fixes https://github.com/JuliaLang/julia/issues/50434.

### CODE REVIEW

File: src/gc.c [hunk 1]
```diff
@@ -4069,8 +4073,18 @@ JL_DLLEXPORT jl_value_t *jl_gc_internal_obj_base_ptr(void *p)
...
+            && (char *)cell < (char *)pool->freelist) {
             goto valid_object;
+        }
+        else {
+            jl_taggedvalue_t *v = pool->freelist;
+            while (v != NULL) {
+                if (v == cell) {
+                    return NULL;
+                }
+                v = v->next;
```
Comment (fingolfin) [inline src/gc.c:4085]: We are seeing some major regression in GC performance with Julia master and wonder if it may be caused by this fix. Presumably if the freelist is long, and we do a lot of `jl_gc_internal_obj_base_ptr` calls, then this would indeed be slow-ish.

Comment (fingolfin) [reply src/gc.c:4085]: See also https://github.com/oscar-system/Oscar.jl/issues/2543#issuecomment-1641555936

Comment (d-netto) [reply src/gc.c:4085]: There is likely some low-hanging fruit here.

We may possibly restrict this loop for the subset of the free-list which is contained in the page.

Will open a PR with that.

Comment (fingolfin) [reply src/gc.c:4085]: Just for future reference, the PR @d-netto opened was #50599 and has already been merged
