### PR TITLE
Make `jl_cumulative_compile_time_ns` global (and reentrant).

### LINKED ISSUE #41739: Compilation Time reporting is broken on Julia 1.7, due to Task Migration
Consider this small example, which `@time`s within a Task, allows the Task to migrate threads, and then shows that the results are garbage when it switches threads:
```julia
# compilation-task-migration-17-example.jl
@sync begin
    # Start a long task that yields a lot, and is likely to switch tasks
    # Run a `@time` measurement in there, to report the compilation time.
    Threads.@spawn begin
        @time begin
            Core.println("start thread: ",Threads.threadid())
            for _ in 1:5
                sleep(0.2)  # might switch threads
            end
            @eval module M ; f(x,y) = x+y; end
            @eval M.f(1,2)
            Core.println("end thread: ",Threads.threadid())
        end
    end
    # Start some heavy work to occupy the thread that the above task started on.
    @sync for _ in 1:Threads.nthreads()
        Threads.@spawn for _ in 1:10 peakflops() end
    end
end
```
One time it reported 0% compilation time, the next time it reports 4327426979.58% compilation time 😅 
```julia
julia> versioninfo()
Julia Version 1.7.0-beta3
Commit e76c9dad42 (2021-07-07 08:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  
julia> include("compilation-task-migration-17-example.jl")
start thread: 1
WARNING: replacing module M.
end thread: 3
  4.352289 seconds (18.97 k allocations: 2.391 GiB, 6.06% gc time)

julia> include("compilation-task-migration-17-example.jl")
start thread: 2
WARNING: replacing module M.
end thread: 3
  4.262751 seconds (18.97 k allocations: 2.391 GiB, 5.35% gc time, 4327426979.58% compilation time)
```

(For completeness, here's the same test on julia 1.6):
```julia
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

julia> include("compilation-task-migration-17-example.jl")
start thread: 2
end thread: 2
  5.200354 seconds (3.24 M allocations: 2.563 GiB, 6.75% gc time, 0.33% compilation time)

julia> include("compilation-task-migration-17-example.jl")
start thread: 2
WARNING: replacing module M.
end thread: 2
  5.840806 seconds (18.27 k allocations: 2.391 GiB, 8.02% gc time, 0.05% compilation time)
```

### PR DESCRIPTION
**Pull request by NHDaly**
Now, multiple tasks (on the same or different Threads) can start and stop compilation
time measurement, without interrupting each other.

Compilation time measurement originally added in: https://github.com/JuliaLang/julia/pull/38885

Problems addressed:
- This fixes https://github.com/JuliaLang/julia/issues/41739, meaning it fixes compilation time reporting in 1.7 after task migration was enabled.
- ~This allows users to enable global monitoring of compilation time, by enabling it with `Base.cumulative_compile_time_ns_before()`, and then regularly calling `Base.cumulative_compile_time_ns()` to track the metric, and finally optionally disabling it with `Base.cumulative_compile_time_ns_after()` when they're done.~
    - EDIT: This actually _isn't_ supported by this PR, because of the "exception throwing" problem, described in the comments at the end of the PR discussion. See #41762 for a PR that supports this use case.
- It also fixes the race condition that existed previously, even on 1.6, where multiple Tasks on the thread measuring `@time` could break the measurement, as identified in (https://github.com/JuliaLang/julia/issues/41271#issuecomment-876564749).

-----

Here's a very simple example that shows the fixed "reentrant" behavior:
v1.6 - the inner `@time` disables compilation measurement, so the outer `@time` misses it:
```julia
julia> struct X x::Int end

julia> show(io::IO, x::X) = print(io, "hello $(x.x)")
show (generic function with 1 method)

julia> @time begin
           @time 2+2
           @eval show(stdout, X(3))
       end
  0.000003 seconds (6 allocations: 192 bytes)
hello 3  0.010132 seconds (2.75 k allocations: 178.116 KiB)
```
this PR:
```julia
julia> struct X x::Int end

julia> show(io::IO, x::X) = print(io, "hello $(x.x)")
show (generic function with 1 method)

julia> @time begin
           @time 2+2
           @eval show(stdout, X(3))
       end
  0.000008 seconds (6 allocations: 192 bytes)
hello 3  0.008674 seconds (2.73 k allocations: 158.612 KiB, 94.03% compilation time)
```

And here's the fixed examples from https://github.com/JuliaLang/julia/issues/41739:
```julia
julia> include("compilation-task-migration-17-example.jl")
start thread: 1
WARNING: replacing module M.
end thread: 2
  4.664806 seconds (18.22 k allocations: 2.391 GiB, 4.89% gc time, 0.08% compilation time)

julia> include("compilation-task-migration-17-example.jl")
start thread: 2
WARNING: replacing module M.
end thread: 2
  4.374656 seconds (18.22 k allocations: 2.391 GiB, 5.18% gc time, 0.07% compilation time)
```

### CODE REVIEW

**Comment by NHDaly** [comment]
Also:
```julia
julia> function process_cumulative_compile_time_ns()
           out = fill(UInt(0), Threads.nthreads())
           Threads.@threads for i in 1:Threads.nthreads()
               out[i] = Base.cumulative_compile_time_ns()
           end
           return sum(out)
       end
process_cumulative_compile_time_ns (generic function with 1 method)

julia> process_cumulative_compile_time_ns() / 1e9
0.367209021
```
Which is maybe nice? :) I'm not sure if that's worth adding to the stdlib, or users should do that themselves?

I guess I'll add it too - why not!

**Comment by NHDaly** [comment]
Cool, that seems to work too! :) 
```julia
julia> @test Base.process_cumulative_compile_time_ns() >= Base.cumulative_compile_time_ns()
Test Passed
  Expression: Base.process_cumulative_compile_time_ns() >= Base.cumulative_compile_time_ns()
   Evaluated: 0x00000000008d47ed >= 0x00000000008d47ed

julia> Threads.@spawn @eval @time @eval 2+2
Task (runnable) @0x000000010fb907f0
0.004653 seconds (53 allocations: 2.703 KiB, 92.94% compilation time)

julia> @test Base.process_cumulative_compile_time_ns() >= Base.cumulative_compile_time_ns()
Test Passed
  Expression: Base.process_cumulative_compile_time_ns() >= Base.cumulative_compile_time_ns()
   Evaluated: 0x0000000000cf466f >= 0x00000000008d47ed
```

File: src/jitlayers.cpp [hunk 1]
```diff
@@ -79,14 +79,20 @@ extern "C" JL_DLLEXPORT
 uint64_t jl_cumulative_compile_time_ns_before()
 {
     int tid = jl_threadid();
-    jl_measure_compile_time[tid] = 1;
+    jl_measure_compile_time[tid] += 1;
```
Comment (vchuravy) [inline src/jitlayers.cpp:82]: This has me worried in the context of migration. We can no longer assume that the Julia task will finish executing on the same thread that it started on. This would mean increment and decrement no longer matching. 

In https://github.com/JuliaLang/julia/pull/41612 we solved this by having a single atomic counter that keeps track of how many tasks have asked for timings to be enabled.
Similarily for the `jl_cumulative_compile_time` array.

Comment (NHDaly) [reply src/jitlayers.cpp:82]: Interesting. So that's a global metric, not a per-thread metric.

In fact, doesn't task-migrations on 1.7 mean that `@time` is already broken on 1.7? Since you might migrate to a thread that isn't currently measuring compilation? 😬

Comment (NHDaly) [reply src/jitlayers.cpp:82]: Oh, yeah, okay this is definitely just broken on 1.7:
https://github.com/JuliaLang/julia/issues/41739

**Sigh.**

I just wanted to make this small fix, why is everything so complicated!? 😂 

-----------

............ okay i'll think a bit more about doing this the Right Way.

Am I right that this PR as-is looks okay for a backport to 1.6 (for our own buildfarm, even if we don't _actually_ backport this to 1.6?)

Comment (NHDaly) [reply src/jitlayers.cpp:82]: I've branched this into https://github.com/NHDaly/julia/tree/nhd-allow-reentrant-compilation-time-measurement--1.6-backport so that we can look at backporting that, separately.

Comment (NHDaly) [reply src/jitlayers.cpp:82]: 🤔 part of the problem is that this boolean is checked from C code. Is there an equivalent to atomics for our C codebase?

Comment (NHDaly) [reply src/jitlayers.cpp:82]: EDIT: ah, yeah, okay i think i've found stuff after looking through the codebase... i'll try this

Comment (NHDaly) [reply src/jitlayers.cpp]: Okay thanks, Valentin. I've addressed this in the latest push! :)

**Comment by NHDaly** [comment]
Okay this is now ready for review again! :) Thanks Valentin. 🙏

**Review by vchuravy — APPROVED** [review]
Can you squash your commits? 

I would like you have @vtjnash eyes on this once, but it looks good toe.

**Comment by NHDaly** [comment]
Thanks Valentin. Squashed!

> looks good toe.
😁 Classic tell-tale sign of you reviewing code from your phone. pressing `backspace` instead of `m` is a classic mobile phone mistake 😛 Go enjoy your vacation! ❤️ 

Haha thanks for the review :)

**Comment by IanButterworth** [comment]
I just looked at the diff. There's a lot changed here that doesn't seem relevant. Did something go wrong in the squash?

**Comment by NHDaly** [comment]
Oh thanks, it might've. I didn't check. Out to dinner now, will have a look
later :)

**Comment by NHDaly** [comment]
> I just looked at the diff. There's a lot changed here that doesn't seem relevant. Did something go wrong in the squash?

Thanks @IanButterworth - fixed the squash. It looks right now. Thanks for catching that! :)

**Comment by NHDaly** [comment]
@vtjnash - i think this PR is waiting for your review as well, whenever you get the chance. Thanks!

File: src/aotcompile.cpp [hunk 2]
```diff
@@ -415,8 +414,8 @@ void *jl_create_native(jl_array_t *methods, const jl_cgparams_t cgparams, int _p
     }
 
     data->M = std::move(clone);
-    if (jl_measure_compile_time[tid])
-        jl_cumulative_compile_time[tid] += (jl_hrtime() - compiler_start_time);
+    if (jl_atomic_load(&jl_measure_compile_time))
+        jl_atomic_fetch_add(&jl_measure_compile_time, (jl_hrtime() - compiler_start_time));
```
Comment (vtjnash) [inline src/aotcompile.cpp:418]: The `jl_atomic_load` should only appear exactly once in this function, or it is not actually atomic (just data-race free).

Comment (vtjnash) [reply src/aotcompile.cpp:418]: (it could also be `jl_atomic_load_relaxed`, though the performance different shouldn't be measurable)

File: src/gf.c [hunk 3]
```diff
@@ -3164,15 +3164,14 @@ static uint64_t inference_start_time = 0;
...
+    if (jl_atomic_load(&jl_measure_compile_time))
         inference_start_time = jl_hrtime();
 }
 
 JL_DLLEXPORT void jl_typeinf_end(void)
 {
-    int tid = jl_threadid();
-    if (typeinf_lock.count == 1 && jl_measure_compile_time[tid])
-        jl_cumulative_compile_time[tid] += (jl_hrtime() - inference_start_time);
+    if (typeinf_lock.count == 1 && jl_atomic_load(&jl_measure_compile_time))
```
Comment (vtjnash) [inline src/gf.c:3173]: Same here–this read should only happen once (in jl_typeinf_begin). We can use `inference_start_time == 0` here as a flag to test whether it was true on entry.

File: src/aotcompile.cpp (hunk 2 above)
Comment (vtjnash) [reply src/aotcompile.cpp:418]: Though it is actually unclear to me why this function counts against the compile-time. It is only used by the GPU stack, and is therefore not quite JIT time.

File: src/aotcompile.cpp [hunk 4]
```diff
@@ -916,8 +915,7 @@ void *jl_get_llvmf_defn(jl_method_instance_t *mi, size_t world, char getwrapper,
         jl_llvm_functions_t decls;
         JL_LOCK(&codegen_lock);
         uint64_t compiler_start_time = 0;
-        int tid = jl_threadid();
-        if (jl_measure_compile_time[tid])
+        if (jl_atomic_load(&jl_measure_compile_time))
```
Comment (vtjnash) [inline src/aotcompile.cpp:918]: Same here: this is the implementation of `code_llvm`, which is not part of compile time, as that is run at runtime.

File: src/jitlayers.cpp [hunk 5]
```diff
@@ -78,16 +78,21 @@ void jl_jit_globals(std::map<void *, GlobalVariable*> &globals)
 extern "C" JL_DLLEXPORT
 uint64_t jl_cumulative_compile_time_ns_before()
 {
-    int tid = jl_threadid();
-    jl_measure_compile_time[tid] = 1;
-    return jl_cumulative_compile_time[tid];
+    // Increment the flag to allow reentrant callers to `@time`.
+    jl_atomic_fetch_add(&jl_measure_compile_time, 1);
+    return jl_atomic_load(&jl_cumulative_compile_time);
```
Comment (vtjnash) [inline src/jitlayers.cpp:83]:
```suggestion
    return jl_atomic_fetch_add(&jl_measure_compile_time, 1) + 1;
```

(as with my first comment here, the fetch much only happen once, or it is not atomic, merely data-race-free)

Comment (vtjnash) [reply src/jitlayers.cpp:83]: EDIT: oh, I see those are different variables. I suppose I am not sure how this part is intended to work, but I think your change is as close to correct as would currently be possible.

File: src/threading.c [hunk 6]
```diff
@@ -287,8 +287,8 @@ void jl_pgcstack_getkey(jl_get_pgcstack_func **f, jl_pgcstack_key_t *k)
 #endif
 
 jl_ptls_t *jl_all_tls_states JL_GLOBALLY_ROOTED;
-uint8_t *jl_measure_compile_time = NULL;
-uint64_t *jl_cumulative_compile_time = NULL;
+volatile uint8_t jl_measure_compile_time = 0;
+volatile uint64_t jl_cumulative_compile_time = 0;
```
Comment (vtjnash) [inline src/threading.c:291]: volatile makes no useful promise here
```suggestion
uint8_t jl_measure_compile_time = 0;
uint64_t jl_cumulative_compile_time = 0;
```

**Comment by janrous-rai** [comment]
I would also like to draw attention to my PR that tackles somewhat different aspect of this problem: https://github.com/JuliaLang/julia/pull/41762 (ability to turn the compilation tracking permanently which is going to be useful for long-running processes where we are okay with paying the overhead)

File: src/aotcompile.cpp (hunk 2 above)
Comment (NHDaly) [reply src/aotcompile.cpp:418]: > The `jl_atomic_load` should only appear exactly once in this function, or it is not actually atomic (just data-race free).

Ah, thanks @vtjnash! Great catch. Thanks for the careful review 👍 I'll apply this change (and those suggested throughout), and ping you again. 👍 👍

File: src/jitlayers.cpp (hunk 5 above)
Comment (NHDaly) [reply src/jitlayers.cpp:83]: I think the alternative would be having a shared global lock for both of those variables, but i don't think it really adds much to this function, since if compilation is going on elsewhere, it's already a bit arbitrary whether or not you return that compilation time.

I agree, i think this current implementation seems okay, and I'll probably leave this one alone?

Also - i mixed up those two variable names multiple times too. 😑  Maybe I should rename them to indicate that one is a boolean/counter? Something like `jl_measure_compile_time_enabled`?

File: src/task.c [hunk 7]
```diff
@@ -561,7 +561,7 @@ static void JL_NORETURN throw_internal(jl_task_t *ct, jl_value_t *exception JL_M
     ptls->io_wait = 0;
     // @time needs its compile timer disabled on error,
     // and cannot use a try-finally as it would break scope for assignments
-    jl_measure_compile_time[ptls->tid] = 0;
```
[the remark this answers is not in the document]
Comment (NHDaly) [reply src/task.c:564]: Ah, actually, @janrous-rai raises a really great point here.

> Even if this is used "correctly" as an alternative exit point from the `@time` call I am not sure if it is only guaranteed to occur in exactly that context, i.e. whether we can guarantee that we won't get the `jl_measure_compile_time` counter decremented in other scenarios.

Thank you for the careful review! You're totally right. As currently implemented, even if the user hasn't called `@time`, and then we throw an exception, this will decrement the counter, and then we'll _start_ measuring compilation time because `if (-1)` is considered `true` in C! 😂 And then when the user calls `jl_cumulative_compile_time_before`, we'll _stop_ measuring. 😬 
Thanks for catching this!

If our only goal was to support reentrant calls to `@time`, I think we could address this by using an atomic compare-and-decrement that only decrements this **if it's already above 0**. 

However, we _also_ would like to support the use-case identified at RelationalAI, where we just want to turn this on all the time, and _leave it on_, and in that case we obviously don't want to disable it whenever we throw an exception!

🤔 This requires more thinking. 😕
Thanks for identifying it.

[the remark this answers is not in the document]
Comment (janrous-rai) [reply src/task.c:564]: My other PR deals with the other use-case and is somewhat simpler as it doesn't need to deal with re-entrancy (which is conceptually hard) and because it is triggered on demand, I think it's okay if the compilation costs incurred by exception handling is included in the timing (we care more about the rough-estimates and excluding or including the exception handling compilation costs will likely be miniscule in the overall big picture).

[the remark this answers is not in the document]
Comment (NHDaly) [reply src/task.c:564]: Hah, bummer, another reason that this original mechanism is broken is that it must mean that a **handled** try/catch would already disable compilation time measurement! 

And yeah, indeed, seems like it:
```julia
julia> @time begin
           # The following exception disables compilation time measurement
           try throw("ha HAH!") catch end
           @eval module M ; f(x) = 2*x ; end
           @eval M.f(2)
       end
  0.006116 seconds (2.17 k allocations: 156.874 KiB)
4
```
vs
```julia
julia> @time begin
           @eval module M ; f(x) = 2*x ; end
           @eval M.f(2)
       end
WARNING: replacing module M.
  0.008430 seconds (1.20 k allocations: 84.593 KiB, 53.77% compilation time)
4
```

Oops!

[the remark this answers is not in the document]
Comment (NHDaly) [reply src/task.c:564]: Oh, it sounds like this is already reported and understood, so i think we can leave this alone in this PR. :)

**Comment by vchuravy** [comment]
@NHDaly friendly bump

File: src/task.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (NHDaly) [reply src/task.c:564]: Here's the relevant discussions about this existing bug where exceptions disable the compilation measurement:

https://github.com/JuliaLang/julia/pull/38915
https://github.com/JuliaLang/julia/pull/39138
https://github.com/JuliaLang/julia/pull/39217

File: src/aotcompile.cpp (hunk 2 above)
Comment (NHDaly) [reply src/aotcompile.cpp]: > Though it is actually unclear to me why this function counts against the compile-time. It is only used by the GPU stack, and is therefore not quite JIT time.

Regarding this part, I'd like to leave this change out of this PR. This is only supposed to be a bug fix. Can we start a separate discussion, maybe in an issue, about this?

File: src/aotcompile.cpp (hunk 4 above)
Comment (NHDaly) [reply src/aotcompile.cpp]: Same as above - maybe we can move this into a separate thread & separate PR?

This makes sense to me, but i'd like to do the change elsewhere.

File: src/gf.c (hunk 3 above)
Comment (NHDaly) [reply src/gf.c]: Thanks Jameson - fixed in latest push.

File: src/jitlayers.cpp (hunk 5 above)
Comment (NHDaly) [reply src/jitlayers.cpp]: Done - i've renamed it to jl_measure_compile_time_enabled (and fixed another mix-up i caught along the way 😅)

File: src/task.c [hunk 8]
```diff
@@ -561,7 +561,10 @@ static void JL_NORETURN throw_internal(jl_task_t *ct, jl_value_t *exception JL_M
...
+    // We blindly disable compilation time tracking here, for all running Tasks, even though
+    // it may cause some incorrect measurements. This is a known bug, and is being tracked
+    // here: https://github.com/JuliaLang/julia/pull/39138
+    jl_atomic_store_release(&jl_measure_compile_time_enabled, 0);
```
Comment (NHDaly) [inline src/task.c:567]: @vtjnash can you help me with this? What's the difference between `jl_atomic_store` and `jl_atomic_store_release`? The rest of the code here seems to use `_release`, but i'm not sure what i should do here.

Since I'm using `jl_atomic_load()` for this variable everywhere else, should i just use `jl_atomic_store`?

File: src/aotcompile.cpp (hunk 2 above)
Comment (NHDaly) [reply src/aotcompile.cpp]: I've opened https://github.com/JuliaLang/julia/issues/41921 to discuss the remaining question here. I'll now resolve this thread.

File: src/aotcompile.cpp (hunk 4 above)
Comment (NHDaly) [reply src/aotcompile.cpp]: I've opened https://github.com/JuliaLang/julia/issues/41921 to discuss the remaining question here. I'll now resolve this thread.

**Review by Sacha0 — APPROVED** [review]
Looks great! Thanks Nathan! :)

(From an offline conversation: the exception-throwing-disabling-timing conundrum is to be addressed downstream.)

**Comment by NHDaly** [comment]
Thanks for the review @Sacha0! 😊  And yeah, thanks - i was just about to write up a message about the exception handling thing.

Hokay, this PR is ready to go.

It fixes the following problems:
- It fixes `@time` compilation measurement, which was broken due to task migration, by making it a global metric.
- It fixes reentrant `@time` by making the `enable` flag a _counter,_ instead of a boolean.
- It fixes `@time` called from multiple threads by making that flag thread-safe (via atomics).

It **does not** the following problem:
- An exception thrown _anywhere in the system, by any task on any thread_ currently entirely disables compilation time measurement.
    - This bug already existed, and was introduced in https://github.com/JuliaLang/julia/pull/39133. I will try to follow up with a separate PR to fix the issue, but it will require more discussion.

File: src/task.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (NHDaly) [reply src/task.c:564]: As mentioned in another comment (https://github.com/JuliaLang/julia/pull/41733/#issuecomment-901368198), we're going to have to tackle this exception throwing issue in a separate PR.

This PR is an improvement, and we don't want to hang it up.

Thanks for pointing this out!

File: src/task.c (hunk 8 above)
Comment (vtjnash) [reply src/task.c:567]: It specifies restrictions on what must happen to other memory:

relaxed -> no other constraints
release (store) -> all stores before this must occur before this is visible to any processor
acquire (load) -> all loads after this must occur after this is visible to this processor
seq_cst -> (store) all stores and loads must happen in program order before/after this OR (load) all loads must happen in program order before/after this

We are probably okay with `relaxed` on this everywhere, since I don't think we are attempting to synchronize any other operations

Comment (NHDaly) [reply src/task.c:567]: okay thanks, i'll change everything to relaxed everywhere. 🏖️

**Comment by NHDaly** [comment]
I think the remaining build failures are all unrelated:
- `llvmpasses` and `embedding` both say: 
    ```
    ERROR: "/cache/julia-buildkite-plugin/depots/53de1ea5-6dd3-4008-b976-161c9f34b0ad/registries/General/J/JLLWrappers/Package.toml": No such file
    ```
- The `tester_win64` build failed with:
    ```
    Error in testset Downloads:
    Error During Test at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\stdlib\v1.8\Downloads\test\runtests.jl:392
      Got exception outside of a @test
      HTTP/1.1 200 OK (Operation too slow. Less than 1 bytes/sec transferred the last 20 seconds) while requesting https://httpbingo.org/drip
    ```
    and I don't have the permissions to restart the build (`Cannot rebuild: you need to have role 'JuliaLang'`) - is that something I should get fixed?
- I'm not sure what happened to `package_linuxppc64le`, but it failed like this:
    ```
    Precompilation complete. Summary:
    Total ��������������������� 259.195869 seconds
    Generation ������ 194.241971 seconds 74.9402%
    Execution ���������  64.953898 seconds 25.0598%
    /bin/sh: line 1: 881134 Killed                  JULIA_BINDIR=/buildworker/worker/package_linuxppc64le/build/usr/bin WINEPATH="/buildworker/worker/package_linuxppc64le/build/usr/bin;$WINEPATH" /buildworker/worker/package_linuxppc64le/build/usr/bin/julia -O3 -C "pwr8" --output-o /buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys-o.a.tmp --startup-file=no --warn-overwrite=yes --sysimage /buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys.ji /buildworker/worker/package_linuxppc64le/build/contrib/generate_precompile.jl 1
    make[1]: *** [/buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys-o.a] Error 1
    make: *** [julia-sysimg-release] Error 2
    *** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
    make[1]: Leaving directory `/buildworker/worker/package_linuxppc64le/build'
    program finished with exit code 2
    elapsedTime=1126.065277
    ```

Seem reasonable to merge now?
