### PR TITLE
fix Dict completion when using non-ASCII (fix #23004)

### LINKED ISSUE #23004: ℂ[\ + Tab -> ERROR (in the keymap): UnicodeError: invalid character index
In the REPL,  after having the combination `ℂ[` ( \BbbC+TAB followed by a square opening bracket), any following tab completion that you try gives an error:
```
ℂ[\ERROR (in the keymap): UnicodeError: invalid character index
Stacktrace:
 [1] slow_utf8_next(::Ptr{UInt8}, ::UInt8, ::Int64, ::Int64) at ./strings/string.jl:174
 [2] next at ./strings/string.jl:206 [inlined]
 [3] getindex at ./strings/basic.jl:32 [inlined]
 [4] findnext(::Base.REPLCompletions.##15#16, ::String, ::Int64) at ./array.jl:1352
 [5] dict_identifier_key(::String, ::Symbol) at ./repl/REPLCompletions.jl:421
 [6] completions(::String, ::Int64) at ./repl/REPLCompletions.jl:446
 [7] complete_line(::Base.REPL.REPLCompletionProvider, ::Base.LineEdit.PromptState) at ./repl/REPL.jl:291
 [8] complete_line(::Base.LineEdit.PromptState, ::Int64) at ./repl/LineEdit.jl:142
 [9] complete_line(::Base.LineEdit.MIState) at ./repl/LineEdit.jl:140
 [10] (::Base.LineEdit.##91#121)(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL, ::Vararg{Any,N} where N) at ./repl/LineEdit.jl:1353
 [11] (::Base.LineEdit.##13#14{Base.LineEdit.##91#121,String})(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL) at ./repl/LineEdit.jl:742
 [12] prompt!(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface, ::Base.LineEdit.MIState) at ./repl/LineEdit.jl:1624
 [13] run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./repl/LineEdit.jl:1584
 [14] run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./repl/REPL.jl:962
 [15] run_repl(::Base.REPL.LineEditREPL, ::Base.##530#531) at ./repl/REPL.jl:183
 [16] _start() at ./client.jl:425
```

Works fine in Atom.

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

File: base/repl/REPLCompletions.jl [hunk 1]
```diff
@@ -407,18 +407,18 @@ function dict_identifier_key(str,tag)
...
+    for name in split(str[frange[1]:end_of_identifier], '.')
         Base.isidentifier(name) || return (nothing, nothing, nothing)
         sym = Symbol(name)
         isdefined(obj, sym) || return (nothing, nothing, nothing)
         obj = getfield(obj, sym)
         # Avoid `isdefined(::Array, ::Symbol)`
         isa(obj, Array) && return (nothing, nothing, nothing)
     end
-    begin_of_key = findnext(x->!in(x,whitespace_chars), str, end_of_indentifier+2)
+    begin_of_key = first(search(str, r"\S", nextind(str, end_of_identifier) + 1)) # 1 for [
```
Comment (stevengj) [inline base/repl/REPLCompletions.jl]: Seems like we should have a fallback
```
searchindex(s, p, start) = first(search(s, p, start))
```
so that `searchindex` works for regex.

**Comment by StefanKarpinski** [comment]
Bump. While @stevengj's comment would be a good change, it doesn't need to happen in this PR. Are there any other issues with this? I restarted the failed macOS build, the Win32 failure was a timeout, so I don't think it need restarting.

**Review by stevengj — APPROVED** [review]

**Comment by Jutho** [comment]
Thanks for that!
