### PR TITLE
remove special-casing of Tuple in REPL completion

### LINKED ISSUE #36872: Tab-completion for integer propertynames
Objects which have integer `propertyname`s currently cause an error (other than `Tuple`s, which [are handled specifically](https://github.com/JuliaLang/julia/blob/004cb25d66199aa0a2b7a985ecb86e773118ef82/stdlib/REPL/src/REPLCompletions.jl#L126)):

```
julia> struct Foo
       end

julia> Base.propertynames(::Foo) = (1,2)

julia> f = Foo()
Foo()

julia> f.┌ Error: Error in the keymap
│   exception =
│    MethodError: Cannot `convert` an object of type Int64 to an object of type Symbol
│    Closest candidates are:
│      convert(::Type{T}, ::T) where T at essentials.jl:171
│      Symbol(::Any...) at strings/basic.jl:207
|     [1] REPL.REPLCompletions.PropertyCompletion(::Foo, ::Int64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:30
│     [2] complete_symbol(::String, ::REPL.REPLCompletions.var"#21#25", ::Module) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:150
│     [3] completions(::String, ::Int64, ::Module) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:703
...
```

Interestingly, you can use `:` to access fields of `Tuple`s:
```
julia> t = (5,7)
(5, 7)

julia> t.:2
7
```
so it would be nice if tab-completion worked this way. I did start trying to fix this, but got lost in the logic around this part:
https://github.com/JuliaLang/julia/blob/004cb25d66199aa0a2b7a985ecb86e773118ef82/stdlib/REPL/src/REPLCompletions.jl#L104

### PR DESCRIPTION
**Pull request by simonbyrne**
Partially fix #36872

### CODE REVIEW

**Review by zonito — APPROVED** [review]

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -123,7 +123,6 @@ function complete_symbol(sym, ffunc, context_module=Main)::Vector{Completion}
         end
         found || return Completion[]
         # Ensure REPLCompletion do not crash when asked to complete a tuple, #15329
```
Comment (JeffBezanson) [inline stdlib/REPL/src/REPLCompletions.jl:125]: Also remove this comment?

Comment (simonbyrne) [reply stdlib/REPL/src/REPLCompletions.jl]: Done.
