### PR TITLE
Limit the `src` style in structured broadcast.

### LINKED ISSUE #940: Broadcast with structured matrix types may yield non-intuitive results
```julia
julia> using LinearAlgebra

julia> A = rand(2,2)
2×2 Matrix{Float64}:
 0.697319  0.499919
 0.790291  0.619497

julia> SA = LowerTriangular(A)
2×2 LowerTriangular{Float64, Matrix{Float64}}:
 0.697319   ⋅ 
 0.790291  0.619497

julia> transpose(SA)
2×2 UpperTriangular{Float64, Transpose{Float64, Matrix{Float64}}}:
 0.697319  0.790291
  ⋅        0.619497

julia> B = zeros(2,2);

julia> SB = LowerTriangular(B);

julia> SB .= transpose(SA)
2×2 LowerTriangular{Float64, Matrix{Float64}}:
 0.697319   ⋅ 
 0.0       0.619497
```
The broadcast `setindex!` should fail, as the RHS can't be stored in the LHS. This is what happens in `transpose!`
```julia
julia> transpose!(SB, SA)
ERROR: ArgumentError: cannot set index in the upper triangular part (1, 2) of a LowerTriangular matrix to a nonzero value (0.7902909099826494)
Stacktrace:
 [1] setindex!
   @ ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/LinearAlgebra/src/triangular.jl:256 [inlined]
 [2] transpose_f!(f::typeof(transpose), B::LowerTriangular{Float64, Matrix{Float64}}, A::LowerTriangular{Float64, Matrix{Float64}})
   @ LinearAlgebra ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/LinearAlgebra/src/transpose.jl:104
 [3] transpose!(B::LowerTriangular{Float64, Matrix{Float64}}, A::LowerTriangular{Float64, Matrix{Float64}})
   @ LinearAlgebra ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/LinearAlgebra/src/transpose.jl:41
 [4] top-level scope
   @ REPL[11]:1
```

### LINKED ISSUE #46165: Broadcast with structured matrix types may yield non-intuitive results
```julia
julia> using LinearAlgebra

julia> A = rand(2,2)
2×2 Matrix{Float64}:
 0.697319  0.499919
 0.790291  0.619497

julia> SA = LowerTriangular(A)
2×2 LowerTriangular{Float64, Matrix{Float64}}:
 0.697319   ⋅ 
 0.790291  0.619497

julia> transpose(SA)
2×2 UpperTriangular{Float64, Transpose{Float64, Matrix{Float64}}}:
 0.697319  0.790291
  ⋅        0.619497

julia> B = zeros(2,2);

julia> SB = LowerTriangular(B);

julia> SB .= transpose(SA)
2×2 LowerTriangular{Float64, Matrix{Float64}}:
 0.697319   ⋅ 
 0.0       0.619497
```
The broadcast `setindex!` should fail, as the RHS can't be stored in the LHS. This is what happens in `transpose!`
```julia
julia> transpose!(SB, SA)
ERROR: ArgumentError: cannot set index in the upper triangular part (1, 2) of a LowerTriangular matrix to a nonzero value (0.7902909099826494)
Stacktrace:
 [1] setindex!
   @ ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/LinearAlgebra/src/triangular.jl:256 [inlined]
 [2] transpose_f!(f::typeof(transpose), B::LowerTriangular{Float64, Matrix{Float64}}, A::LowerTriangular{Float64, Matrix{Float64}})
   @ LinearAlgebra ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/LinearAlgebra/src/transpose.jl:104
 [3] transpose!(B::LowerTriangular{Float64, Matrix{Float64}}, A::LowerTriangular{Float64, Matrix{Float64}})
   @ LinearAlgebra ~/packages/julias/julia-latest/share/julia/stdlib/v1.9/LinearAlgebra/src/transpose.jl:41
 [4] top-level scope
   @ REPL[11]:1
```

### PR DESCRIPTION
**Pull request by N5N3**
close JuliaLang/LinearAlgebra.jl#940.

### CODE REVIEW

File: stdlib/LinearAlgebra/src/structuredbroadcast.jl [hunk 1]
```diff
@@ -9,53 +9,60 @@ StructuredMatrixStyle{T}(::Val{2}) where {T} = StructuredMatrixStyle{T}()
 StructuredMatrixStyle{T}(::Val{N}) where {T,N} = Broadcast.DefaultArrayStyle{N}()
 
 const StructuredMatrix = Union{Diagonal,Bidiagonal,SymTridiagonal,Tridiagonal,LowerTriangular,UnitLowerTriangular,UpperTriangular,UnitUpperTriangular}
-Broadcast.BroadcastStyle(::Type{T}) where {T<:StructuredMatrix} = StructuredMatrixStyle{T}()
+for ST in Base.uniontypes(StructuredMatrix)
+    @eval Broadcast.BroadcastStyle(::Type{<:$ST}) = StructuredMatrixStyle{$ST}()
```
Comment (vtjnash) [inline stdlib/LinearAlgebra/src/structuredbroadcast.jl:13]:
```suggestion
    @eval Broadcast.BroadcastStyle(::Type{<:$ST}) = $(StructuredMatrixStyle{ST}())
```
If we are going to use `eval` on this we might as well splice in the exact result for it

File: stdlib/LinearAlgebra/src/structuredbroadcast.jl [hunk 2]
```diff
@@ -9,53 +9,60 @@ StructuredMatrixStyle{T}(::Val{2}) where {T} = StructuredMatrixStyle{T}()
...
+Broadcast.BroadcastStyle(::StructuredMatrixStyle{UpperTriangular}, ::StructuredMatrixStyle{<:Union{Diagonal,UpperTriangular,UnitUpperTriangular}}) =
     StructuredMatrixStyle{UpperTriangular}()
-Broadcast.BroadcastStyle(::StructuredMatrixStyle{<:UnitLowerTriangular}, ::StructuredMatrixStyle{<:Union{Diagonal,LowerTriangular,UnitLowerTriangular}}) =
+Broadcast.BroadcastStyle(::StructuredMatrixStyle{UnitLowerTriangular}, ::StructuredMatrixStyle{<:Union{Diagonal,LowerTriangular,UnitLowerTriangular}}) =
     StructuredMatrixStyle{LowerTriangular}()
-Broadcast.BroadcastStyle(::StructuredMatrixStyle{<:UnitUpperTriangular}, ::StructuredMatrixStyle{<:Union{Diagonal,UpperTriangular,UnitUpperTriangular}}) =
+Broadcast.BroadcastStyle(::StructuredMatrixStyle{UnitUpperTriangular}, ::StructuredMatrixStyle{<:Union{Diagonal,UpperTriangular,UnitUpperTriangular}}) =
     StructuredMatrixStyle{UpperTriangular}()
 
+# TODO: drop StructuredMatrixStyle{Matrix}
```
Comment (N5N3) [inline stdlib/LinearAlgebra/src/structuredbroadcast.jl:49]:
```suggestion
```
