### PR TITLE
fix missing layout allocation

### LINKED ISSUE #41503: Julia nightly throwing at `jl_datatype_isinlinealloc`
A recent version of Julia nightly started throwing errors on tests in Manifolds.jl, see for example these CI runs: https://github.com/JuliaManifolds/Manifolds.jl/pull/381/checks?check_run_id=3010181089 . On Windows, for example, a part of the error reads:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1f9b127 -- jl_datatype_isinlinealloc at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:253 [inlined]
jl_datatype_isinlinealloc at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:250 [inlined]
union_isinlinable at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:277 [inlined]
union_isinlinable at /cygdrive/c/buildbot/worker/package_win64/build/src\datatype.c:266
in expression starting at D:\a\Manifolds.jl\Manifolds.jl\test\centered_matrices.jl:3
```
and on Ubuntu:
```
signal (11): Segmentation fault
in expression starting at /home/runner/work/Manifolds.jl/Manifolds.jl/test/centered_matrices.jl:3
jl_datatype_isinlinealloc at /buildworker/worker/package_linux64/build/src/datatype.c:253 [inlined]
union_isinlinable at /buildworker/worker/package_linux64/build/src/datatype.c:277 [inlined]
jl_islayout_inline at /buildworker/worker/package_linux64/build/src/datatype.c:300
jl_compute_field_offsets at /buildworker/worker/package_linux64/build/src/datatype.c:446
inst_datatype_inner at /buildworker/worker/package_linux64/build/src/jltypes.c:1520
```

I'll try making an MWE.

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #41503

mea culpa.

### CODE REVIEW

File: test/compiler/codegen.jl [hunk 1]
```diff
@@ -594,6 +594,14 @@ f41438(y) = y[].x
 @test f41438(Ref{A41438}(A41438(C_NULL))) === C_NULL
 @test f41438(Ref{B41438}(B41438(C_NULL))) === C_NULL
 
+const S41438 = Pair{Any, Ptr{T}} where T
+g41438() = Array{S41438,1}(undef,1)[1].first
+get_llvm(g41438, ()); # cause allocation of layout
+@test S41438.body.layout != C_NULL
+@test !Base.datatype_pointerfree(S41438.body)
+@test S41438{Int}.layout != C_NULL
+@test !Base.datatype_pointerfree(S41438.body)
```
Comment (jpsamaroo) [inline test/compiler/codegen.jl:603]: Duplicate test of line 601?

Comment (vtjnash) [reply test/compiler/codegen.jl:603]:
```suggestion
@test !Base.datatype_pointerfree(S41438{Int}.body)
```

File: test/compiler/codegen.jl [hunk 2]
```diff
@@ -594,6 +594,14 @@ f41438(y) = y[].x
 @test f41438(Ref{A41438}(A41438(C_NULL))) === C_NULL
 @test f41438(Ref{B41438}(B41438(C_NULL))) === C_NULL
 
+const S41438 = Pair{Any, Ptr{T}} where T
+g41438() = Array{S41438,1}(undef,1)[1].first
+get_llvm(g41438, ()); # cause allocation of layout
+@test S41438.body.layout != C_NULL
+@test !Base.datatype_pointerfree(S41438.body)
+@test S41438{Int}.layout != C_NULL
+@test !Base.datatype_pointerfree(S41438{Int}.body)
```
Comment (vtjnash) [inline test/compiler/codegen.jl:603]:
```suggestion
@test !Base.datatype_pointerfree(S41438{Int})
```
