### PR TITLE
Fix potential overflow in nextfloat

### LINKED ISSUE #16206: nextfloat behaviour near Inf
I find this behaviour surprising:
```julia
>> nextfloat(Inf)
Inf
>> nextfloat(Inf, 2)
Inf
>> nextfloat(prevfloat(Inf))
Inf
>> nextfloat(prevfloat(Inf), 2)
NaN
```
I would expect the last call to return `Inf` as well.

The following code seems to do what I expected:
```julia
function nextfloat(x::Float64, i::Integer)
    if i == 0 || (isinf(x) && sign(x) == sign(i))
        return x
    end
    xint = float_lex_order(reinterpret(Int64,x), i)
    intmax = reinterpret(Int64, Inf64)
    int0 = reinterpret(Int64, -0.0)
    intmin = reinterpret(Int64, -Inf64)
    return (0 <= xint <= intmax || int0 <= xint <= intmin) ?
        reinterpret(Float64, xint) : flipsign(Inf, x)
end
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #16206

### CODE REVIEW

File: base/float.jl [hunk 1]
```diff
@@ -421,6 +452,8 @@ bswap(x::Float64) = box(Float64,bswap_int(unbox(Float64,x)))
 # bit patterns
 reinterpret(::Type{Unsigned}, x::Float64) = reinterpret(UInt64,x)
 reinterpret(::Type{Unsigned}, x::Float32) = reinterpret(UInt32,x)
+reinterpret(::Type{Signed}, x::Float64) = reinterpret(Int64,x)
+reinterpret(::Type{Signed}, x::Float32) = reinterpret(Int32,x)
```
Comment (tkelman) [inline base/float.jl]: probably worth testing these added `reinterpret` methods directly too

Comment (simonbyrne) [inline base/float.jl]: done.

**Comment by omus** [comment]
Changes to docstring signatures need to be replicated in the manual for `make julia-genstdlib` to work:
```
WARNING: missing docs for signature:

    nextfloat(f)

WARNING: missing docs for signature:

    prevfloat(f) -> AbstractFloat
```
