### PR TITLE
[GC Lowering] Improve calculation of rooting location

### LINKED ISSUE #22770: Crash due to use-after-free (?)
After #22210, tests of ACME.jl end in a crash (ref. https://github.com/JuliaLang/julia/pull/22210#issuecomment-314416531), reproducible with
```julia
Pkg.add("ACME", v"0.4.1", v"0.4.1+")
Pkg.test("ACME")
```
As `Pkg.test("ACME")` takes quite long, the much quicker repro is
```julia
using ACME
for i in 1:10000
    @show i
    mats = ACME.model_matrices(Circuit(), 1)
end
```
The iteration in which the crash occurs and the exact error and backtrace vary, but a value whose type is not a type at all seems to be a recurring theme. However, adding a `gc()` to `model_matrices(...)` with
```diff
diff --git a/src/ACME.jl b/src/ACME.jl
index 466a26d..ab7fd74 100644
--- a/src/ACME.jl
+++ b/src/ACME.jl
@@ -509,6 +509,7 @@ function model_matrices(circ::Circuit, t::Rational{BigInt})
         res[v] = squeeze(res[v], 2)
     end
 
+    gc()
     p = [pv(circ) pi(circ) px(circ)//2+pxd(circ)//t pq(circ)]
     if normsquared(p * indeterminates) > 1e-20
         warn("Model output depends on indeterminate quantity")
```
consistently leads to a crash in iteration 1. The crash here actually occurs when trying to show a `MethodError`, this is an excerpt from a GDB session:
```
#12 0x00007ffff757b6af in jl_apply_generic (args=0x7fffffffa620, nargs=2) at ./src/gf.c:1928
1928	    jl_value_t *res = jl_call_method_internal(mfunc, args, nargs);
(gdb) call jl_(args[0])
getfield(Base, Symbol("##494#495")){Base.MethodError}(ex=Base.MethodError(f=typeof(Base.:(*))(), args=<?#0x7fffe8f76990::Array{UInt64, 1}[0xffffffffffffffff]>, world=0x0000000000005675))
```
Note the garbled inner `args`, where the type is an array _instance_ (and trying do to something with that then hits an assertion further down the backtrace), hence my guess that this is a use-after-free.

My very wild guess is that the new inlining heuristics due to #22210 lead to code that somehow confuses the GC. But I'm way over my head here. If there is anything I can do to obtain/provide more information, I'm all ears.

### PR DESCRIPTION
**Pull request by Keno**
The old way to do it interacted badly with load refinements, causing
roots to get clobbered, because the compiler would attemt to root values
while their slot was still in use by a different value. Instead,
look at live sets and insert a rooting, whenever there's a non-live->live
transition.

Fixes #22770

### CODE REVIEW

File: src/llvm-late-gc-lowering.cpp [hunk 1]
```diff
@@ -1186,6 +1178,74 @@ static Value *GetPtrForNumber(State &S, unsigned Num, Instruction *InsertionPoin
...
+                    First = false;
+                } else {
+                    LiveIn &= S.LiveSets[LastSP];
+                }
+            }
+        }
+    }
+}
+
+void LateLowerGCFrame::PlaceGCFrameStore(State &S, unsigned R, unsigned MinColorRoot, const std::vector<int> &Colors, Value *GCFrame, Instruction *InsertionPoint) {
```
Comment (tkelman) [inline src/llvm-late-gc-lowering.cpp]: line length

**Comment by martinholters** [comment]
I'm in no position to review this, but I can confirm that it solves the original issue of #22770 for me locally.

The travis failure is a bit funny: 10 minutes without output, but the last output before that was
```
make: Leaving directory `/home/travis/build/JuliaLang/julia/doc'

Done. Your build exited with 0.
```
So it actually had finished successfully. Maybe something went wrong when checking whether the dependency cache needs updating? Anyway, looks more like a Travis problem than a Julia one, definitely unrelated to this PR, I'd say.

**Comment by quinnj** [comment]
FWIW, I saw the same travis failure within the last week.

**Comment by KristofferC** [comment]
Perhaps Nanosoldier would have been appropriate here?

**Comment by Keno** [comment]
Shouldn't really change anything. This only changes where things are rooted for correctness. Shouldn't have any performance impact. If there's something interesting the nightly run will find it.

File: src/llvm-late-gc-lowering.cpp (hunk 1 above)
Comment (tkelman) [inline src/llvm-late-gc-lowering.cpp]: was not addressed

**Comment by tkelman** [comment]
This did make CI runtimes consistently about 10-15 minutes longer though (in the PR runs and everything since merging), so it looks like it hurt noticeably in compile time.

**Comment by Keno** [comment]
Hmm, only on 32 bit though?

**Comment by tkelman** [comment]
worse on 32 bit than 64, slowdown on 64 bit looks like maybe 5-10 minutes on average (but pretty noisy)

**Comment by Keno** [comment]
Which numbers are you looking at? Travis 64 bit numbers look pretty unchanged.

**Comment by tkelman** [comment]
more on 64 bit appveyor, e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.16710 1hr13min vs https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.16709 1hr4min

**Comment by vtjnash** [comment]
I concur. We're also somewhere around 40% slower at total CI time than release-0.6 (e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.15674). Would be helpful for someone to bisect that too.

File: src/llvm-late-gc-lowering.cpp [hunk 2]
```diff
@@ -1186,6 +1178,74 @@ static Value *GetPtrForNumber(State &S, unsigned Num, Instruction *InsertionPoin
...
+}
+
+void LateLowerGCFrame::PlaceGCFrameStores(Function &F, State &S, unsigned MinColorRoot, const std::vector<int> &Colors, Value *GCFrame)
+{
+    for (auto &BB : F) {
+        if (!S.BBStates[&BB].HasSafepoint) {
+            continue;
+        }
+        BitVector LiveIn;
+        AddInPredLiveOuts(&BB, LiveIn, S);
```
Comment (vtjnash) [inline src/llvm-late-gc-lowering.cpp]: This appears to be O(N^2) in the number of BB. Could this be converged once when creating the LiveSet instead of recomputing for each BB?

File: src/llvm-late-gc-lowering.cpp [hunk 3]
```diff
@@ -1186,6 +1178,74 @@ static Value *GetPtrForNumber(State &S, unsigned Num, Instruction *InsertionPoin
...
+        for(auto rit = S.BBStates[&BB].Safepoints.rbegin();
+              rit != S.BBStates[&BB].Safepoints.rend(); ++rit ) {
```
Comment (vtjnash) [inline src/llvm-late-gc-lowering.cpp]: `S.BBStates[&BB]` is `O(log(n))` and doesn't need to be recomputed on each loop

**Comment by tkelman** [comment]
The `sparse/cholmod` test in particular is taking over 4x longer on 32 bit than 64 bit. Will look into how big the difference was before this merged.

**Comment by tkelman** [comment]
Ping, @Keno have you looked into this regression at all? That one test taking over half an hour when it should take under a minute is pretty extreme.

**Comment by Keno** [comment]
Not yet, I'll look at it in the morning.
