### PR TITLE
Make cor work again for complex input

### LINKED ISSUE #21093: cor broken for complex numbers
```julia
julia> cor(randn(50)+im*randn(50), randn(50)+im*randn(50))
ERROR: MethodError: no method matching isless(::Complex{Float64}, ::Complex{Float64})
 in corm(::Array{Complex{Float64},1}, ::Complex{Float64}, ::Array{Complex{Float64},1}, ::Complex{Float64}) at ./statistics.jl:452
 in cor(::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}) at ./statistics.jl:480
```

Works on 0.4, but throws an error on 0.5 and 0.6.

### PR DESCRIPTION
**Pull request by simonster**
Also fix an inconsistency in complex `cov`. Fixes #21093.

It appears there is some ambiguity regarding whether the first or second argument should be conjugated when computing these quantities. MATLAB conjugates the first argument, while NumPy conjugates the second. [Wikipedia](https://en.wikipedia.org/wiki/Covariance_matrix#Complex_random_vectors) defines the complex covariance matrix as E((Z - μ)(Z - μ)ᴴ), which seems to imply that the second argument should be conjugated, so that is the convention I followed here. Previously, we were not consistent about this: We conjugated the first argument when computing the covariance between vectors, but the second when computing the covariance between matrices.

### CODE REVIEW

File: base/statistics.jl [hunk 1]
```diff
@@ -388,18 +389,26 @@ cov(X::AbstractMatrix, Y::AbstractMatrix) = cov(X, Y, 1, true)
 
 ##### correlation #####
 
+"""
+    clampcor(x)
+
+Clamp a real correlation to between -1 and 1, leaving complex correlations unchanged
+"""
+clampcor(x::Real) = clamp(x, -1, 1)
+clampcor(x) = x
```
Comment (andreasnoack) [inline base/statistics.jl]: Isn't there any bounds for the complex version?

**Review by andreasnoack — APPROVED** [review]
What about the *relation* component. Do people just ignore it? Should we consider returning a tuple for complex input or should it be a separate function?

File: base/statistics.jl (hunk 1 above)
Comment (simonster) [inline base/statistics.jl]: With infinite precision, `abs(x) <= 1`, but if this isn't the case due to floating point rounding, I don't think there's a principled way to adjust `x`.

**Comment by simonster** [comment]
For circularly symmetric complex random variables, both the relation matrix and mean are zero. Since complex variables are often assumed to be circularly symmetric, I don't think it makes sense to compute the relation matrix by default (although in this case, `corzm` makes more sense than `cor`). Having never dealt with non-circularly-symmetric complex data myself, I don't know whether it's worth having a separate function to compute the relation matrix or not.

File: base/statistics.jl (hunk 1 above)
Comment (StefanKarpinski) [inline base/statistics.jl]: Closest representable value to `x` such that `abs(x) ≤ 1`? Not sure how find that though.

Comment (simonster) [inline base/statistics.jl]: It is possible that adjusting the number so that `abs(x) <= 1` decreases the accuracy of the real or imaginary components or the accuracy of `angle(x)`, and the `abs` operation itself may not even be correctly rounded; openlibm guarantees 1 ulp, not 0.5 ulp. So I think the appropriate adjustment would depend on what is relevant to the user (real component imaginary component, phase, and/or magnitude).

If one of the components is `>1` or `<-1` and the other is 0, then clamping that component would improve accuracy, but in any other case it's probably possible to find a counterexample. So we could do:

```julia
function clampcor(x::Complex)
    if imag(x) == 0 && abs(real(x)) > 1
        complex(copysign(one(real(x)), real(x)), zero(imag(x)))
    elseif real(x) == 0 && abs(imag(x)) > 1
        complex(zero(real(x)), copysign(one(imag(x)), imag(x)))
    else
        x
    end
end
```

This might make sense, since it would improve consistency between `cor(X)` and `cor(complex(X))`. But it might not be worth the computational cost, since these cases are probably relatively rare.
