### PR TITLE
Fix: Complex SubArray times real Matrix  

### LINKED ISSUE #566: SubArray x Matrix fails for different types
Multiplying a subarray and a matrix different eltype (complex and float)  fails on julia 1.0.0:
```
julia> A0=rand(5,5)+1im*randn(5,5); 
julia> A=view(A0,1:2,1:2); 
julia> B=randn(2,2); 
julia> A*B
ERROR: MethodError: no method matching gemm_wrapper!(::Base.ReinterpretArray{Float64,2,Complex{Float64},Array{Complex{Float64},2}}, ::Char, ::Char, ::Base.ReinterpretArray{Float64,2,Complex{Float64},SubArray{Complex{Float64},2,Array{Complex{Float64},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}, ::Array{Float64,2})                                                  
```
The other multiplication works:
```
julia> B*A
2×2 Array{Complex{Float64},2}:
 0.00905465-0.746745im  0.125384-1.28383im
   0.640798-1.25818im   0.416431-2.5558im 
```
The calls lead to different multiplication functions:
```
julia> TS=ComplexF64; C=similar(A,TS,size(A,1),size(B,1)); 
julia> @which mul!(C,B,A)  # leads to generic_matmatmul!
mul!(C::AbstractArray{T,2} where T, A::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T, B::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/matmul.jl:172
julia> @which mul!(C,A,B) # leads to gemm_wrapper!
mul!(C::Union{DenseArray{Complex{Float64},2}, ReinterpretArray.... where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/matmul.jl:147
```

It seems to me that the functions defined by the following in `matmul.jl` should not be activated in this case, since the are selected even for matrices for which `gemm_wrapper!` is not defined:
```
for elty in (Float32,Float64)
    @eval begin
        function mul!(C::StridedMatrix{Complex{$elty}}, A::StridedVecOrMat{Complex{$elty}}, B::StridedVecOrMat{$elty})
            Afl = reinterpret($elty, A)
            Cfl = reinterpret($elty, C)
            gemm_wrapper!(Cfl, 'N', 'N', Afl, B)
            return C
        end
    end
end
```
Or there is a problem that the reinterpretation of a `SubArray` is not a `StridedVecOrMat`:
```
julia> Afl=reinterpret(Float64,A);
julia> isa(Afl,StridedVecOrMat)
false
julia> isa(A,StridedVecOrMat)
true
```

### LINKED ISSUE #29224: SubArray x Matrix fails for different types
Multiplying a subarray and a matrix different eltype (complex and float)  fails on julia 1.0.0:
```
julia> A0=rand(5,5)+1im*randn(5,5); 
julia> A=view(A0,1:2,1:2); 
julia> B=randn(2,2); 
julia> A*B
ERROR: MethodError: no method matching gemm_wrapper!(::Base.ReinterpretArray{Float64,2,Complex{Float64},Array{Complex{Float64},2}}, ::Char, ::Char, ::Base.ReinterpretArray{Float64,2,Complex{Float64},SubArray{Complex{Float64},2,Array{Complex{Float64},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}, ::Array{Float64,2})                                                  
```
The other multiplication works:
```
julia> B*A
2×2 Array{Complex{Float64},2}:
 0.00905465-0.746745im  0.125384-1.28383im
   0.640798-1.25818im   0.416431-2.5558im 
```
The calls lead to different multiplication functions:
```
julia> TS=ComplexF64; C=similar(A,TS,size(A,1),size(B,1)); 
julia> @which mul!(C,B,A)  # leads to generic_matmatmul!
mul!(C::AbstractArray{T,2} where T, A::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T, B::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/matmul.jl:172
julia> @which mul!(C,A,B) # leads to gemm_wrapper!
mul!(C::Union{DenseArray{Complex{Float64},2}, ReinterpretArray.... where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/matmul.jl:147
```

It seems to me that the functions defined by the following in `matmul.jl` should not be activated in this case, since the are selected even for matrices for which `gemm_wrapper!` is not defined:
```
for elty in (Float32,Float64)
    @eval begin
        function mul!(C::StridedMatrix{Complex{$elty}}, A::StridedVecOrMat{Complex{$elty}}, B::StridedVecOrMat{$elty})
            Afl = reinterpret($elty, A)
            Cfl = reinterpret($elty, C)
            gemm_wrapper!(Cfl, 'N', 'N', Afl, B)
            return C
        end
    end
end
```
Or there is a problem that the reinterpretation of a `SubArray` is not a `StridedVecOrMat`:
```
julia> Afl=reinterpret(Float64,A);
julia> isa(Afl,StridedVecOrMat)
false
julia> isa(A,StridedVecOrMat)
true
```

### PR DESCRIPTION
**Pull request by jarlebring**
This fixes JuliaLang/LinearAlgebra.jl#566 concerning multiplication of a complex SubArray with a real matrix. The only substantial change is  
```
gemm_wrapper!(Cfl, 'N', 'N', Afl, B)
```
to
```
mul!(Cfl, Afl, B)
```
This allows dispatch to determine if we can use `gemm` for the reinterpreted matrix, or just do it through the fallback `generic_matmatmul!`.

### CODE REVIEW

File: stdlib/LinearAlgebra/test/matmul.jl [hunk 1]
```diff
@@ -161,6 +161,35 @@ end
     @test *(Asub, adjoint(Asub)) == *(Aref, adjoint(Aref))
 end
 
+@testset "Complex matrix x real MatOrVec etc (issue #29224)" for T1 in (Float32,Float64)
+    for T2 in (Float32,Float64)
+        for arg1_real in (true,false)
+            @testset "Combination $T1 $T2 $arg1_real $arg2_real" for arg2_real in (true,false)
+                A0 = reshape(Vector{T1}(1:25),5,5) .+
+                   (arg1_real ? 0 : 1im*reshape(Vector{T1}(-3:21),5,5))
+                A = view(A0,1:2,1:2)
```
Comment (andreasnoack) [inline stdlib/LinearAlgebra/test/matmul.jl]: Maybe also add a test with `view(A0,:,1:2)` to tests the code path that dispatches to BLAS.

Comment (jarlebring) [reply stdlib/LinearAlgebra/test/matmul.jl]: Done

**Review by andreasnoack — APPROVED** [review]

**Review by andreasnoack — COMMENTED** [review]
Actually, would you mind making the same change in the two other places where we use the `reinterpret` trick?

**Comment by jarlebring** [comment]
Sure. For the record: This is places the trick is used and it also does not work:
```
julia> A=view(complex.(randn(2,2),randn(2,2)),1:2,1:2);
julia> B=transpose(randn(2,2))
julia> A*B
```

**Comment by jarlebring** [comment]
Done. All three reinterpret tricks are now changed.
