### PR TITLE
Fix thread safety in `atexit(f)`: Lock access to atexit_hooks

### LINKED ISSUE #49746: Reproducible Memory Corruption in `atexit_hooks` (on MacOS) leading to GC corruption and/or segfault
Quite possibly related to https://github.com/JuliaLang/julia/issues/43567.

Here is a small reproducer https://github.com/NHDaly/ThreadingUtils.jl
Uploaded here:
[ThreadingUtils.zip](https://github.com/JuliaLang/julia/files/11446675/ThreadingUtils.zip)

When running the tests for this small repro, on macOS, I can reliably get a crash around 1/20 times. (this repro was distilled down from our real codebase, where the crash happens more like 1/5 times.)

We would love to get an `rr` trace, but we sadly haven't been able to repro on linux yet 😢 

We've seen crashes on both our internal build of 1.8.2, as well as on the latest master, built as of yesterday,  e204e200df8f57e516920c056b6ec2eb37d34079.

To repro:
```bash
~/src/julia/julia --project=. -E 'using Pkg; for _ in 1:100; Pkg.test("ThreadingUtils", julia_args=["-t4,1", "--gcthreads=1"]); end'
```

I eventually see crashes, such as:
```julia
13:29:46 | maxrss  0.9% | mem 98.9% | DONE  ( 3/11) test item "spawn_sticky_periodic_task on correct threadpool" 2.1 secs (60.2% compile, 0.3% GC), 2.07 M allocs (149.759 MB)
GC error (probable corruption) :
Allocations: 8942391 (Pool: 8933067; Big: 9324); GC: 13

!!! ERROR in jl_ -- ABORTING !!!

[98691] signal (6): Abort trap: 6
in expression starting at /Users/nathandaly/work/Delve/packages/ThreadingUtils/test/Future_tests.jl:1
Allocations: 8942391 (Pool: 8933067; Big: 9324); GC: 13
ERROR: Package ThreadingUtils errored during testing (received signal: 6)
```
or
```julia
signal (11): Segmentation fault: 11
in expression starting at /Users/nathandaly/work/raicode2/packages/ThreadingUtils/test/runtests.jl:2
gc_mark_loop at /nix/store/w6hgdihnsbgl5sk14rybgm7ffyh0mgq9-julia-1.8.2-patched/lib/julia/libjulia-internal.1.8.dylib (unknown line)
_jl_gc_collect at /nix/store/w6hgdihnsbgl5sk14rybgm7ffyh0mgq9-julia-1.8.2-patched/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_gc_collect at /nix/store/w6hgdihnsbgl5sk14rybgm7ffyh0mgq9-julia-1.8.2-patched/lib/julia/libjulia-internal.1.8.dylib (unknown line)
gc at ./gcutils.jl:93 [inlined]
#runtestitem#75 at /Users/nathandaly/.julia/packages/ReTestItems/Go9Yr/src/ReTestItems.jl:711
runtestitem##kw at /Users/nathandaly/.julia/packages/ReTestItems/Go9Yr/src/ReTestItems.jl:630 [inlined]
```
or
```julia
[61257] signal (11.2): Segmentation fault: 11
in expression starting at /Users/nathandaly/work/Delve/packages/ThreadingUtils/test/runtests.jl:5
gc_mark_outrefs at /Users/nathandaly/src/julia/src/gc.c:2573 [inlined]
gc_mark_loop_serial_ at /Users/nathandaly/src/julia/src/gc.c:2759
gc_mark_loop_serial at /Users/nathandaly/src/julia/src/gc.c:2782
gc_mark_loop at /Users/nathandaly/src/julia/src/gc.c:2908 [inlined]
_jl_gc_collect at /Users/nathandaly/src/julia/src/gc.c:3227
ijl_gc_collect at /Users/nathandaly/src/julia/src/gc.c:3540
gc at ./gcutils.jl:129 [inlined]
#runtestitem#79 at /Users/nathandaly/.julia/packages/ReTestItems/NIjKJ/src/ReTestItems.jl:727
```
(Sorry, the line numbers will be wrong, because i've been adding printlns for debugging. This is the line on that gc_mark_outrefs):
https://github.com/JuliaLang/julia/blob/552121236bdd63876912bab72e8b20d3abc8870b/src/gc.c#L2569

------

We added some println debugging (in #49741), and we got some more information, which is what led us to the fact that the corruption is happening in the `atexit_hooks` object:
```julia
# added this to the top of runtests.jl
@info "Pointer of atexit_hooks: $(Base.pointer_from_objref(Base.atexit_hooks))"
```
and it matches up here:
```julia
[ Info: Pointer of atexit_hooks: Ptr{Nothing} @0x000000011f632d40

...

GC error (probable corruption) while enqueing:
Allocations: 8893120 (Pool: 8883835; Big: 9285); GC: 13
While marking parent 0x11f632d40, of type:
Array{Union{Function, Type}, 1}
invalid object encountered when enqueuing object at 0x1633ac358, of type:
Base.var"#939#940"()
Attempting to dump parent object:
Array{Union{Function, Type}, (4,)}[
...
```
Note: `0x000000011f632d40` and `parent 0x11f632d40`.

So, somehow, one of the functions in the `atexit_hooks` vector is getting trashed. Here are some of the times it's managed to dump the vector via `jl_`:
```
GC error (probable corruption) while enqueing:
Allocations: 9075187 (Pool: 9065758; Big: 9429); GC: 16
While marking parent 0x11eae2d40, of type:
Array{Union{Function, Type}, 1}
invalid object encountered when enqueuing object at 0x10e4eafd8, of type:
Union{}
Attempting to dump parent object:
Array{Union{Function, Type}, (6,)}[
  ##spawn named periodic task#229.var"#2#4"(),
  ##periodic task with exceptions#228.var"#2#4"(),
  ##spawn_sticky_periodic_task on correct threadpool#227.var"#3#10"{WeakRef}(#189#wkr=WeakRef(value=nothing)),
  ##spawn_sticky_periodic_task on correct threadpool#227.var"#3#10"{WeakRef}(#189#wkr=WeakRef(value=nothing)),
  ##spawn_sticky_periodic_task on correct threadpool#227.var"#3#10"{WeakRef}(#189#wkr=WeakRef(value=nothing)),

!!! ERROR in jl_ -- ABORTING !!!

[93789] signal (6): Abort trap: 6
```
or also:
```
Attempting to dump parent object:
Array{Union{Function, Type}, (3,)}[
  ##spawn_sticky_periodic_task on correct threadpool#227.var"#3#10"{WeakRef}(#166#wkr=WeakRef(value=ThreadingUtils.PeriodicTask([...]))  # elided
  ##spawn_sticky_periodic_task on correct threadpool#227.var"#3#10"{WeakRef}(#166#wkr=WeakRef(value=ThreadingUtils.PeriodicTask([...]))  # elided
  <?#0x281ef42b8::
!!! ERROR in jl_ -- ABORTING !!!
```

In the original code, the `atexit() do` hooks were using a `WeakRef` to ensure that the hook itself isn't unnecessarily keeping the object alive. We've removed that from the version of the reproducer provided above, since it reproduces without the WeakRefs, so the WeakRefs themselves are probably a red herring.

That said, it seemed to reproduce slightly more frequently when WeakRefs were involved as well. The diff to put them back is here:
```diff
diff --git a/src/ThreadingUtils.jl b/src/ThreadingUtils.jl
index 26be26d..4a3aa66 100644
--- a/src/ThreadingUtils.jl
+++ b/src/ThreadingUtils.jl
@@ -54,8 +54,11 @@ macro spawn_interactive_periodic_task(name, period, expr)
             end
         end
         _pt = PeriodicTask(n, p, timer, should_terminate, task)
+        wkr = WeakRef(_pt)
         atexit() do
-            stop_periodic_task!(_pt)
+            if wkr.value !== nothing
+                stop_periodic_task!(wkr.value)
+            end
         end
         _pt
     end
```

--------

Phew! I'm not sure how actionable this is, but it's a pretty surprisingly small reproducer and it can surface a crash, so this should be looked into! I'm not sure who would be best positioned to investigate further. I'm happy to help if anyone wants to pair.

Thanks!

### PR DESCRIPTION
**Pull request by NHDaly**
- atexit(f) mutates global shared state.
- atexit(f) can be called anytime by any thread.
- Accesses & mutations to global shared state must be locked if they can be accessed from multiple threads.

Fixes #49746

### CODE REVIEW

File: base/initdefs.jl [hunk 1]
```diff
@@ -374,7 +375,7 @@ calls `exit(n)`, then Julia will exit with the exit code corresponding to the
 last called exit hook that calls `exit(n)`. (Because exit hooks are called in
 LIFO order, "last called" is equivalent to "first registered".)
 """
-atexit(f::Function) = (pushfirst!(atexit_hooks, f); nothing)
+atexit(f::Function) = Base.@lock _atexit_lock (pushfirst!(atexit_hooks, f); nothing)
```
Comment (NHDaly) [inline base/initdefs.jl:378]: Does anyone have a **style preference** between this oneliner and this multiliner?:
```suggestion
function atexit(f::Function)
    Base.@lock _atexit_lock begin
        pushfirst!(atexit_hooks, f)
        return nothing
    end
end
```
I think I prefer the nested multiliner, but it's maybe less julian, so I want to leave it up to reviewers. Thanks!

File: base/initdefs.jl [hunk 2]
```diff
@@ -353,6 +353,7 @@ end
 const atexit_hooks = Callable[
     () -> Filesystem.temp_cleanup_purge(force=true)
 ]
+const _atexit_lock = ReentrantLock()
```
Comment (kpamnany) [inline base/initdefs.jl:356]:
```suggestion
const _atexit_hooks_lock = ReentrantLock()
```

File: base/initdefs.jl (hunk 1 above)
Comment (kpamnany) [inline base/initdefs.jl:378]:
```suggestion
atexit(f::Function) = Base.@lock _atexit_hooks_lock (pushfirst!(atexit_hooks, f); nothing)
```

**Review by kpamnany — APPROVED** [review]
Good find!

I'm fine with the one-liner.

Guessing you checked whether the test fails on current `master`?

File: base/initdefs.jl (hunk 2 above)
Comment (NHDaly) [reply base/initdefs.jl:356]: Thanks, yeah that seems like a nice change 👍

**Comment by NHDaly** [comment]
> Guessing you checked whether the test fails on current `master`?

@kpamnany: Yes, and boy do they fail!...
```julia
julia> using Test

julia> @testset "atexit thread safety" begin
           f = () -> nothing
           before_len = length(Base.atexit_hooks)
           @sync begin
               for _ in 1:1_000_000
                   Threads.@spawn begin
                       atexit(f)
                   end
               end
           end
           @test length(Base.atexit_hooks) == before_len + 1_000_000
           @test all(hook -> hook === f, Base.atexit_hooks[1 : 1_000_000])

           # cleanup
          # Base.@lock Base._atexit_lock begin
          #     deleteat!(Base.atexit_hooks, 1:1_000_000)
          # end
       end

[57702] signal (11.2): Segmentation fault: 11
in expression starting at REPL[2]:1
sweep_big_list at /Users/nathandaly/src/julia/src/gc.c:1094 [inlined]
sweep_big at /Users/nathandaly/src/julia/src/gc.c:1116 [inlined]
gc_sweep_other at /Users/nathandaly/src/julia/src/gc.c:1608 [inlined]
_jl_gc_collect at /Users/nathandaly/src/julia/src/gc.c:3315
ijl_gc_collect at /Users/nathandaly/src/julia/src/gc.c:3486
maybe_collect at /Users/nathandaly/src/julia/src/gc.c:954 [inlined]
jl_gc_pool_alloc_inner at /Users/nathandaly/src/julia/src/gc.c:1317
ijl_gc_pool_alloc at /Users/nathandaly/src/julia/src/gc.c:1368
jfptr_iterate_34613 at /Users/nathandaly/src/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/nathandaly/src/julia/src/gf.c:0 [inlined]
```
... here's how it failed on 1.8.2 😂:
```julia
signal (11): Segmentation fault: 11

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1
_ZNK5dyld311MachOLoaded17findClosestSymbolEyPPKcPy at /usr/lib/dyld (unknown line)
Allocations: 2961458 (Pool: 2959697; Big: 1761); GC: 3

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1
write at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2961458 (Pool: 2959697; Big: 1761); GC: 3

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1
_platform_strlen at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 2961458 (Pool: 2959697; Big: 1761); GC: 3

...

```
lol there were like 30 segfaults reported 😂

File: base/initdefs.jl (hunk 1 above)
Comment (NHDaly) [reply base/initdefs.jl:378]: done

File: base/initdefs.jl [hunk 3]
```diff
@@ -374,7 +375,7 @@ calls `exit(n)`, then Julia will exit with the exit code corresponding to the
 last called exit hook that calls `exit(n)`. (Because exit hooks are called in
 LIFO order, "last called" is equivalent to "first registered".)
 """
-atexit(f::Function) = (pushfirst!(atexit_hooks, f); nothing)
+atexit(f::Function) = Base.@lock _atexit_hooks_lock (pushfirst!(atexit_hooks, f); nothing)
 
 function _atexit(exitcode::Cint)
     while !isempty(atexit_hooks)
```
Comment (NHDaly) [inline base/initdefs.jl:381]: Actually, maybe we should lock here too... Is there any chance that other Julia Threads can still be running during `_atexit()`? I guess it can't hurt to grab the lock here... Lemme push that up too.

Is it still safe to call into the runtime for things like locks inside `_atexit()`? For this we might need help from @vtjnash or someone similarly familiar?

Comment (kpamnany) [reply base/initdefs.jl:381]: It [seems](https://stackoverflow.com/questions/39655868/what-does-the-posix-standard-say-about-thread-stacks-in-atexit-handlers-what) threads may or may not have stopped running.

Don't think it's safe/possible to lock in exit handler context either. It's an improbable race too, maybe?

I'd leave it, but maybe @vtjnash has thoughts on this?

Comment (NHDaly) [reply base/initdefs.jl:381]: We can always open a follow-up issue to cover this question.

Comment (NHDaly) [reply base/initdefs.jl:381]: K, filed: https://github.com/JuliaLang/julia/issues/49841 as followup.
