### PR TITLE
Correct lyap definition for complex scalar arguments

### LINKED ISSUE #814: lyap is incorrect for complex scalar arguments
The current implementation of `lyap` for complex scalar arguments is incorrect. We can see this by comparing the result obtained using 1x1 matrices vs scalars:

```julia
julia> A = (1.0+2.0im)*ones(1,1);

julia> C = (3.0+4.0im)*ones(1,1);

julia> lyap(A, C)  # expected
1×1 Matrix{ComplexF64}:
 -1.5 - 2.0im

julia> lyap(A[1], C[1])  # wrong! 
-1.1 + 0.2im

julia> -C[1] / 2real(A[1])  # correct implementation
-1.5 - 2.0im
```

The current implementation is:
```julia
lyap(a::T, c::T) where {T<:Number} = -c/(2a)
```
However, it should be:
```julia
lyap(a::T, c::T) where {T<:Number} = -c/(2real(a))
```

### LINKED ISSUE #39857: lyap is incorrect for complex scalar arguments
The current implementation of `lyap` for complex scalar arguments is incorrect. We can see this by comparing the result obtained using 1x1 matrices vs scalars:

```julia
julia> A = (1.0+2.0im)*ones(1,1);

julia> C = (3.0+4.0im)*ones(1,1);

julia> lyap(A, C)  # expected
1×1 Matrix{ComplexF64}:
 -1.5 - 2.0im

julia> lyap(A[1], C[1])  # wrong! 
-1.1 + 0.2im

julia> -C[1] / 2real(A[1])  # correct implementation
-1.5 - 2.0im
```

The current implementation is:
```julia
lyap(a::T, c::T) where {T<:Number} = -c/(2a)
```
However, it should be:
```julia
lyap(a::T, c::T) where {T<:Number} = -c/(2real(a))
```

### PR DESCRIPTION
**Pull request by Regan-Koopmans**
This PR resolves JuliaLang/LinearAlgebra.jl#814 

As per @sethaxen 's demonstration, the definition of `lyap` is incorrect for complex scalar arguments. The definition has. been updated in accordance with his recommendation.

### CODE REVIEW

**Comment by Keno** [comment]
Welcome. This could additionally use a test to make sure that this doesn't regress.

File: stdlib/LinearAlgebra/src/dense.jl [hunk 1]
```diff
@@ -1568,4 +1568,4 @@ function lyap(A::StridedMatrix{T}, C::StridedMatrix{T}) where {T<:BlasFloat}
     rmul!(Q*(Y * adjoint(Q)), inv(scale))
 end
 lyap(A::StridedMatrix{T}, C::StridedMatrix{T}) where {T<:Integer} = lyap(float(A), float(C))
-lyap(a::T, c::T) where {T<:Number} = -c/(2a)
+lyap(a::T, c::T) where {T<:Number} = -c/(2real(a))
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/dense.jl:1571]:
```suggestion
lyap(a::Union{Real,Complex}, c::Union{Real,Complex}) = -c/(2real(a))
```

**Review by dkarrasch — COMMENTED** [review]
IIUC, this seems to require commutativity, and may fail for `Quaternion`s. As a slight generalization, I don't see why we need to require equal types for `a` and `c`.

File: stdlib/LinearAlgebra/src/dense.jl (hunk 1 above)
Comment (Regan-Koopmans) [reply stdlib/LinearAlgebra/src/dense.jl]: @dkarrasch I have committed the suggestion above. Should I add a separate definition for handling `Quaternion`s? Should I create a separate issue for this?

**Review by sethaxen — APPROVED** [review]
LGTM. Thanks for the fix!

File: stdlib/LinearAlgebra/src/dense.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/dense.jl]: No, I don't think we need an issue. Let's wait until somebody hits the missing method error. This has been wrong even in the complex case, not to mention the quaternion case (if that has ever been used).
