### PR TITLE
clarify documentation for randcycle

### LINKED ISSUE #50479: Random.randcycle(1) should throw?
Currently, we define:
```jl
julia> Random.randcycle(1)
1-element Vector{Int64}:
 1
```
which seems wrong to me — as I understand it, the [identity permutation is not cyclic](https://math.stackexchange.com/questions/1151548/is-identity-permutation-cyclic).  Indeed, for `n > 1` we never generate the identity permuation:
```jl
julia> [Random.randcycle(2) for i = 1:10]
10-element Vector{Vector{Int64}}:
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
```
Note that this behavior was introduced in a *very* early version of Julia, way back in 2010 when files still ended in `.j`, by @ViralBShah (https://github.com/JuliaLang/julia/commit/18b72d1c565dca19696ef5ad0d07060cf7b7620a), and appears to have been copied down through the versions ever since.

### PR DESCRIPTION
**Pull request by stevengj**
Closes #50479 by precisely stating the definition of "cyclic permutation" that we are using (which follows Knuth 2b), and the fact that we sample them uniformly.

### CODE REVIEW

**Review by rfourquet — APPROVED** [review]
The same text could be added to the docstring of `randcycle!` (or a reference to it: `"cf. `[randcycle](@ref)`" for what is meant by "cyclic"`.

File: stdlib/Random/src/misc.jl [hunk 1]
```diff
@@ -343,6 +343,10 @@ Construct a random cyclic permutation of length `n`. The optional `rng`
 argument specifies a random number generator, see [Random Numbers](@ref).
 The element type of the result is the same as the type of `n`.
 
+(Here, a "cyclic permutation" means that all of the elements lie within
```
Comment (rfourquet) [inline stdlib/Random/src/misc.jl:346]: Maybe omit the parens? Given the ambiguity highlighted in the issue, this info seems important enough to be placed in the foreground.

Comment (stevengj) [reply stdlib/Random/src/misc.jl:346]: Okay.

**Comment by stevengj** [comment]
I've updated the `randcycle!` docs.

File: stdlib/Random/src/misc.jl [hunk 2]
```diff
@@ -343,6 +343,12 @@ Construct a random cyclic permutation of length `n`. The optional `rng`
 argument specifies a random number generator, see [Random Numbers](@ref).
 The element type of the result is the same as the type of `n`.
 
+Here, a "cyclic permutation" means that all of the elements lie within
+a single cycle of length `n`.  There are ``(n-1)!`` possible cyclic permutations,
```
Comment (stevengj) [inline stdlib/Random/src/misc.jl:347]:
```suggestion
a single cycle.  If `n > 0`, there are ``(n-1)!`` possible cyclic permutations,
```

**Review by rfourquet — APPROVED** [review]

File: stdlib/Random/src/misc.jl [hunk 3]
```diff
@@ -343,6 +343,12 @@ Construct a random cyclic permutation of length `n`. The optional `rng`
 argument specifies a random number generator, see [Random Numbers](@ref).
 The element type of the result is the same as the type of `n`.
 
+Here, a "cyclic permutation" means that all of the elements lie within
+a single cycle.  If `n > 0`, there are ``(n-1)!`` possible cyclic permutations,
+which are sampled uniformly.  If `n == 0`, `randcycle` returns an empty array.
```
Comment (LilithHafner) [inline stdlib/Random/src/misc.jl:348]:
```suggestion
which are sampled uniformly.  If `n == 0`, `randcycle` returns an empty vector.
```
better to be more precise when possible

File: stdlib/Random/src/misc.jl [hunk 4]
```diff
@@ -365,10 +371,16 @@ randcycle(n::Integer) = randcycle(default_rng(), n)
...
-Construct in `A` a random cyclic permutation of length `length(A)`.
+Construct in `A` a random cyclic permutation of length `n = length(A)`.
 The optional `rng` argument specifies a random number generator, see
 [Random Numbers](@ref).
 
+Here, a "cyclic permutation" means that all of the elements lie within a single cycle.
+If `A` is nonempty (`n > 0`), there are ``(n-1)!`` possible cyclic permutations,
+which are sampled uniformly.  If `A` is empty, `randcycle!` leaves it unchanged.
+
+[`randcycle`](@ref) is a variant of this function that allocates a new array.
```
Comment (LilithHafner) [inline stdlib/Random/src/misc.jl:382]:
```suggestion
[`randcycle`](@ref) is a variant of this function that allocates a new vector.
```

**Review by LilithHafner — APPROVED** [review]
