### PR TITLE
runtime versions of Intrinsics.reinterpret

### LINKED ISSUE #12832: `reinterpret(Float64,Complex(1))` kills Julia
````
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6880 (2015-08-21 18:32 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 482aa20 (6 days old master)
|__/                   |  x86_64-apple-darwin14.4.0

julia> reinterpret(Float64,Complex(1))
LLVM ERROR: Cannot select: 0x7fc0518a5a10: f64 = truncate 0x7fc05198c210 [ORD=8705] [ID=4] dbg:essentials.jl:116:1
  0x7fc05198c210: i64 = FrameIndex<0> [ORD=8705] [ID=1]
In function: julia_reinterpret_21170
````

### PR DESCRIPTION
**Pull request by vtjnash**
this implements runtime versions of all of the julia intrinsics (so that functions that use them don't need to be compiled to be run). it additionally includes a `Core.Intrinsics.intrinsic_call` invoke point for calling any of these runtime intrinsics. and it adds the name of the intrinsic to `jl_` printing.

additionally, It implements full error checking for the reinterpret/box/unbox intrinsic (fixes #12832), falling back to the the runtime version when necessary.

finally, it re-organizes some of the julia codegen architecture so that it is possible to link a version of libjulia that does not include a copy of LLVM (although I don't recommend trying, since the runtime currently can't get very far without the JIT).

~~(marked as wip simply because I'm still working on this branch, not because it couldn't be merged)~~

### CODE REVIEW

File: src/APInt-C.cpp [hunk 1]
```diff
@@ -0,0 +1,486 @@
+#include "llvm-version.h"
```
Comment (vtjnash) [inline src/APInt-C.cpp]: need license

File: src/APInt-C.cpp [hunk 2]
```diff
@@ -0,0 +1,486 @@
...
+#include <llvm/ADT/APInt.h>
+#include <llvm/ADT/APFloat.h>
+#include <llvm/Support/MathExtras.h>
+
+#define DLLEXPORT
```
Comment (vtjnash) [inline src/APInt-C.cpp]: ???

File: src/APInt-C.h [hunk 3]
```diff
@@ -0,0 +1,78 @@
+
```
Comment (vtjnash) [inline src/APInt-C.h]: add license

File: src/intrinsics.cpp [hunk 4]
```diff
@@ -413,10 +495,7 @@ static jl_cgval_t generic_box(jl_value_t *targ, jl_value_t *x, jl_codectx_t *ctx
         }
         else {
             if (!jl_is_leaf_type(v.typ) && !jl_is_bitstype(v.typ)) {
-                // TODO: currently doesn't handle the case where the type of neither argument is understood at compile time
-                // since codegen has no idea what size it might have
-                jl_error("codegen: failed during evaluation of a call to reinterpret");
-                return jl_cgval_t();
+                return jl_cgval_t(); // TODO: XXX
```
Comment (vtjnash) [inline src/intrinsics.cpp]: revert this blob

File: src/runtime_intrinsics.c [hunk 5]
```diff
@@ -0,0 +1,930 @@
...
+        if (jl_typeof(x) != ety)
+            jl_error("pointerset: type mismatch in assign");
+        jl_assign_bits(pp, x);
+    }
+    return p;
+}
+
+
+static inline unsigned int next_power_of_two(unsigned int val) {
+  /* this function taken from libuv src/unix/core.c */
```
Comment (tkelman) [inline src/runtime_intrinsics.c]: license here too

Comment (vtjnash) [inline src/runtime_intrinsics.c]: I wouldn't consider this a "substantial portion" of libuv, so i don't think it needs one (https://github.com/libuv/libuv/blob/26917ddf7a5279c5d913c12121fe955ba4de91c0/LICENSE#L14-L15)

File: src/intrinsics.cpp [hunk 6]
```diff
@@ -819,43 +901,87 @@ static Value *emit_smod(Value *x, Value *den, jl_codectx_t *ctx)
...
+        jl_errorf("intrinsic #%d %s: wrong number of arguments", f, jl_intrinsic_name((int)f));
+    }
+
     switch (f) {
     case ccall: return emit_ccall(args, nargs, ctx);
     case cglobal: return emit_cglobal(args, nargs, ctx);
     case llvmcall: return emit_llvmcall(args, nargs, ctx);
-
-    HANDLE(pointerref,2)
+#if 0
```
Comment (tkelman) [inline src/intrinsics.cpp]: what's this about?

File: src/runtime_intrinsics.c [hunk 7]
```diff
@@ -0,0 +1,930 @@
...
+  val |= val >> 4;
+  val |= val >> 8;
+  val |= val >> 16;
+  val += 1;
+  return val;
+}
+
+static inline char signbitbyte(void *a, unsigned bytes) {
+    // sign bit of an signed number of n bytes, as a byte
+    return signbit(((signed char*)a)[bytes-1]) ? ~0 : 0;
```
Comment (tkelman) [inline src/runtime_intrinsics.c]: msvc errors on this
```
d:/code/msys64/home/Tony/julia/src/runtime_intrinsics.c(89) : error C2668: 'sign
bit' : ambiguous call to overloaded function
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(32
9): could be 'bool signbit(long double)'
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(32
4): or       'bool signbit(double)'
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(31
9): or       'bool signbit(float)'
        while trying to match the argument list '(signed char)'
```

File: src/runtime_intrinsics.c [hunk 8]
```diff
@@ -0,0 +1,930 @@
...
+    case  8: return 4;
+    case 16: return 5;
+    }
+}
+
+#define SELECTOR_FUNC(intrinsic) \
+    typedef intrinsic##_t select_##intrinsic##_t[6]; \
+    static inline intrinsic##_t select_##intrinsic(unsigned sz, select_##intrinsic##_t list) \
+    { \
+        return list[select_by_size(sz)] ?: list[0]; \
```
Comment (tkelman) [inline src/runtime_intrinsics.c]: gnu extension

File: src/runtime_intrinsics.c [hunk 9]
```diff
@@ -0,0 +1,930 @@
...
+    if (isize2 > osize2)
+        osize2 = isize2;
+    if (osize2 > isize || isize2 > isize) {
+        /* if needed, round type up to a real c-type and set/clear the unused bits */
+        void *pa2;
+        pa2 = alloca(osize2);
+        /* TODO: this memcpy assumes little-endian,
+         * for big-endian, need to align the copy to the other end */ \
+        memcpy(pa2, pa, isize);
+        memset(pa2 + isize, getsign(pa, isize), osize2 - isize);
```
Comment (tkelman) [inline src/runtime_intrinsics.c]: `d:/code/msys64/home/Tony/julia/src/runtime_intrinsics.c(292) : error C2036: 'void *' : unknown size`

File: src/runtime_intrinsics.c [hunk 10]
```diff
@@ -0,0 +1,930 @@
...
+        jl_error("check_top_bit: value is not a bitstype");
+    if (signbitbyte(jl_data_ptr(a), jl_datatype_size(ty)))
+        jl_throw(jl_inexact_exception);
+    return a;
+}
+
+// checked arithmetic
+#define check_sadd(a,b) \
+        /* this test is a reduction of (b > 0) ? (a + b >= typemin(a)) : (a + b < typemin(a)) ==> overflow */ \
+        (b > 0) == (a >= (((typeof(a))1) << (8 * sizeof(a) - 1)) - b)
```
Comment (tkelman) [inline src/runtime_intrinsics.c]:
```
d:/code/msys64/home/Tony/julia/src/runtime_intrinsics.c(842) : error C2143: synt
ax error : missing ')' before 'constant'
d:/code/msys64/home/Tony/julia/src/runtime_intrinsics.c(842) : error C2059: synt
ax error : ')'
d:/code/msys64/home/Tony/julia/src/runtime_intrinsics.c(842) : error C3861: 'typ
eof': identifier not found
```

File: src/intrinsics.cpp (hunk 6 above)
Comment (vtjnash) [inline src/intrinsics.cpp]: you can flip this switch and codegen will only use runtime intrinsics, never inline / optimized :O

it's a useful mode for showing that the runtime versions pass all of the julia tests, but its rather slow (it ends up doing too much re-boxing due to the current codegen design).

Comment (tkelman) [inline src/intrinsics.cpp]: I see, that makes sense. Is this worthy of a named option define? and/or an explanatory comment...

**Comment by tkelman** [comment]
okay if I commit https://gist.github.com/6c318f37be5a77b42ca7 ? MSVC is strange.

File: src/anticodegen.c [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+    *filename = NULL;
+    *inlinedat_file = NULL;
+    *inlinedat_line = -1;
+    *fromC = 0;
+}
+
+jl_value_t *jl_static_eval(jl_value_t *ex, void *ctx_, jl_module_t *mod,
+                           jl_value_t *sp, jl_expr_t *ast, int sparams, int allow_alloc)
+{
+    return NULL;
```
Comment (JeffBezanson) [inline src/anticodegen.c]: Seems like it should be possible to always include a useful version of this function.

File: src/intrinsics.h [hunk 12]
```diff
@@ -0,0 +1,207 @@
...
+typedef jl_value_t *(*intrinsic_call_2_arg)(jl_value_t*, jl_value_t*);
+typedef jl_value_t *(*intrinsic_call_3_arg)(jl_value_t*, jl_value_t*, jl_value_t*);
+#define jl_is_intrinsic(v)       jl_typeis(v,jl_intrinsic_type)
+
+#ifdef __cplusplus
+extern "C"
+#endif
+JL_CALLABLE(jl_f_intrinsic_call)
+{
+    JL_NARGSV(intrinsic_call, 1);
```
Comment (JeffBezanson) [inline src/intrinsics.h]: I'd rather have this function in a .c file.

**Comment by JeffBezanson** [comment]
Cool!

It looks like `intrinsic_call` is not used yet? Is the idea to use this at all intrinsic call sites eventually?

**Comment by vtjnash** [comment]
Long term, yes. Or make them all Function with this as the fptr and the id in the env (no linfo). It's all a bit dependent on what happens in the jb/functions branch
