### PR TITLE
Insert bitcast after any additional phi nodes

### LINKED ISSUE #46852: PHI nodes not grouped at top of basic block!
When running the test suite of [CrystalNets.jl](https://github.com/coudertlab/CrystalNets.jl/actions/runs/3097871177/jobs/5015064801) on julia master I hit the following error (with the julia-debug build):
```
PHI nodes not grouped at top of basic block!
  %ptr_phi20.ph = phi {} addrspace(10)* [ %gclift582, %L176.L208.thread_crit_edge ], [ %165, %L200.L208_crit_edge ], [ %171, %L205 ]
label %L208.thread
julia-debug: /home/liozou/julia-debug/src/llvm-muladd.cpp:87: bool combineMulAdd(llvm::Function&): Assertion `!verifyFunction(F, &errs())' failed.
```

<details>
<summary>Full stacktrace with debug build.</summary>

```
PHI nodes not grouped at top of basic block!
  %ptr_phi20.ph = phi {} addrspace(10)* [ %gclift582, %L176.L208.thread_crit_edge ], [ %165, %L200.L208_crit_edge ], [ %171, %L205 ]
label %L208.thread
julia-debug: /home/liozou/julia-debug/src/llvm-muladd.cpp:87: bool combineMulAdd(llvm::Function&): Assertion `!verifyFunction(F, &errs())' failed.

[526728] signal (6): Aborted
in expression starting at /home/liozou/.julia/dev/CrystalNets/test/runtests.jl:75
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f5423e72728)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
combineMulAdd at /home/liozou/julia-debug/src/llvm-muladd.cpp:87
runOnFunction at /home/liozou/julia-debug/src/llvm-muladd.cpp:107
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
operator() at /home/liozou/julia-debug/src/jitlayers.cpp:1062
withModuleDo<(anonymous namespace)::OptimizerT::operator()(llvm::orc::ThreadSafeModule, llvm::orc::MaterializationResponsibility&)::<lambda(llvm::Module&)> > at /home/liozou/julia-debug/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136
operator() at /home/liozou/julia-debug/src/jitlayers.cpp:1034
CallImpl<(anonymous namespace)::OptimizerT> at /home/liozou/julia-debug/usr/include/llvm/ADT/FunctionExtras.h:222
_ZN4llvm3orc16IRTransformLayer4emitESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EENS0_16ThreadSafeModuleE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
emit at /home/liozou/julia-debug/src/jitlayers.cpp:592
_ZN4llvm3orc31BasicIRLayerMaterializationUnit11materializeESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc19MaterializationTask3runEv at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm6detail18UniqueFunctionBaseIvJSt10unique_ptrINS_3orc4TaskESt14default_deleteIS4_EEEE8CallImplIPFvS7_EEEvPvRS7_ at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession22dispatchOutstandingMUsEv at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23AsynchronousSymbolQueryEESt8functionIFvRKNS_8DenseMapIPNS0_8JITDylibENS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISF_vEEEENSG_ISD_vEENS_6detail12DenseMapPairISD_SI_EEEEEE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc25InProgressFullLookupState8completeESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession19OL_applyQueryPhase1ESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EENS_5ErrorE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS0_10LookupKindERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS8_EENS0_15SymbolLookupSetENS0_11SymbolStateENS_15unique_functionIFvNS_8ExpectedINS_8DenseMapINS0_15SymbolStringPtrENS_18JITEvaluatedSymbolENS_12DenseMapInfoISI_vEENS_6detail12DenseMapPairISI_SJ_EEEEEEEEESt8functionIFvRKNSH_IS6_NS_8DenseSetISI_SL_EENSK_IS6_vEENSN_IS6_SV_EEEEEE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS7_EERKNS0_15SymbolLookupSetENS0_10LookupKindENS0_11SymbolStateESt8functionIFvRKNS_8DenseMapIS5_NS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISK_vEEEENSL_IS5_vEENS_6detail12DenseMapPairIS5_SN_EEEEEE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS7_EENS0_15SymbolStringPtrENS0_11SymbolStateE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS_8ArrayRefIPNS0_8JITDylibEEENS0_15SymbolStringPtrENS0_11SymbolStateE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS_8ArrayRefIPNS0_8JITDylibEEENS_9StringRefENS0_11SymbolStateE at /home/liozou/julia-debug/usr/bin/../lib/libLLVM-14jl.so (unknown line)
addModule at /home/liozou/julia-debug/src/jitlayers.cpp:1316
jl_add_to_ee at /home/liozou/julia-debug/src/jitlayers.cpp:1693
operator() at /home/liozou/julia-debug/src/jitlayers.cpp:1677
withModuleDo<jl_add_to_ee(llvm::orc::ThreadSafeModule&, llvm::StringMap<llvm::orc::ThreadSafeModule*>&, llvm::DenseMap<llvm::orc::ThreadSafeModule*, int>&, std::vector<std::vector<llvm::orc::ThreadSafeModule*> >&, int)::<lambda(llvm::Module&)> > at /home/liozou/julia-debug/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136
jl_add_to_ee at /home/liozou/julia-debug/src/jitlayers.cpp:1671
operator() at /home/liozou/julia-debug/src/jitlayers.cpp:1677
withModuleDo<jl_add_to_ee(llvm::orc::ThreadSafeModule&, llvm::StringMap<llvm::orc::ThreadSafeModule*>&, llvm::DenseMap<llvm::orc::ThreadSafeModule*, int>&, std::vector<std::vector<llvm::orc::ThreadSafeModule*> >&, int)::<lambda(llvm::Module&)> > at /home/liozou/julia-debug/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136
jl_add_to_ee at /home/liozou/julia-debug/src/jitlayers.cpp:1671
jl_add_to_ee at /home/liozou/julia-debug/src/jitlayers.cpp:1715
_jl_compile_codeinst at /home/liozou/julia-debug/src/jitlayers.cpp:230
jl_generate_fptr_impl at /home/liozou/julia-debug/src/jitlayers.cpp:429
jl_compile_method_internal at /home/liozou/julia-debug/src/gf.c:2156
_jl_invoke at /home/liozou/julia-debug/src/gf.c:2439
ijl_apply_generic at /home/liozou/julia-debug/src/gf.c:2629
jl_apply at /home/liozou/julia-debug/src/julia.h:1866
start_task at /home/liozou/julia-debug/src/task.c:1085
Allocations: 14940269 (Pool: 14926251; Big: 14018); GC: 10
```
</details>

When running without the debug build, this results in `LLVM ERROR: visitCatchSwitch not yet implemented!`.
<details>
<summary>Full stacktrace without debug build</summary>

```
LLVM ERROR: visitCatchSwitch not yet implemented!

[522480] signal (6): Aborted
in expression starting at /home/liozou/.julia/dev/CrystalNets/test/runtests.jl:75
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN4llvm18report_fatal_errorERKNS_5TwineEb at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm18report_fatal_errorEPKcb at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm19SelectionDAGBuilder5visitEjRKNS_4UserE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm19SelectionDAGBuilder5visitERKNS_11InstructionE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm16SelectionDAGISel16SelectBasicBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb1EEES6_Rb at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE.part.902 at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN12_GLOBAL__N_115X86DAGToDAGISel20runOnMachineFunctionERN4llvm15MachineFunctionE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc14SimpleCompilerclERNS_6ModuleE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
operator() at /home/liozou/julia/src/jitlayers.cpp:1114
_ZN4llvm3orc14IRCompileLayer4emitESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EENS0_16ThreadSafeModuleE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16IRTransformLayer4emitESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EENS0_16ThreadSafeModuleE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
emit at /home/liozou/julia/src/jitlayers.cpp:592
_ZN4llvm3orc31BasicIRLayerMaterializationUnit11materializeESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc19MaterializationTask3runEv at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm6detail18UniqueFunctionBaseIvJSt10unique_ptrINS_3orc4TaskESt14default_deleteIS4_EEEE8CallImplIPFvS7_EEEvPvRS7_ at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession22dispatchOutstandingMUsEv at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23AsynchronousSymbolQueryEESt8functionIFvRKNS_8DenseMapIPNS0_8JITDylibENS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISF_vEEEENSG_ISD_vEENS_6detail12DenseMapPairISD_SI_EEEEEE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc25InProgressFullLookupState8completeESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession19OL_applyQueryPhase1ESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EENS_5ErrorE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS0_10LookupKindERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS8_EENS0_15SymbolLookupSetENS0_11SymbolStateENS_15unique_functionIFvNS_8ExpectedINS_8DenseMapINS0_15SymbolStringPtrENS_18JITEvaluatedSymbolENS_12DenseMapInfoISI_vEENS_6detail12DenseMapPairISI_SJ_EEEEEEEEESt8functionIFvRKNSH_IS6_NS_8DenseSetISI_SL_EENSK_IS6_vEENSN_IS6_SV_EEEEEE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS7_EERKNS0_15SymbolLookupSetENS0_10LookupKindENS0_11SymbolStateESt8functionIFvRKNS_8DenseMapIS5_NS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISK_vEEEENSL_IS5_vEENS_6detail12DenseMapPairIS5_SN_EEEEEE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS7_EENS0_15SymbolStringPtrENS0_11SymbolStateE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS_8ArrayRefIPNS0_8JITDylibEEENS0_15SymbolStringPtrENS0_11SymbolStateE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS_8ArrayRefIPNS0_8JITDylibEEENS_9StringRefENS0_11SymbolStateE at /home/liozou/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)
addModule at /home/liozou/julia/src/jitlayers.cpp:1316
jl_add_to_ee at /home/liozou/julia/src/jitlayers.cpp:1693
operator() at /home/liozou/julia/src/jitlayers.cpp:1677 [inlined]
withModuleDo<jl_add_to_ee(llvm::orc::ThreadSafeModule&, llvm::StringMap<llvm::orc::ThreadSafeModule*>&, llvm::DenseMap<llvm::orc::ThreadSafeModule*, int>&, std::vector<std::vector<llvm::orc::ThreadSafeModule*> >&, int)::<lambda(llvm::Module&)> > at /home/liozou/julia/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136 [inlined]
jl_add_to_ee at /home/liozou/julia/src/jitlayers.cpp:1671
operator() at /home/liozou/julia/src/jitlayers.cpp:1677 [inlined]
withModuleDo<jl_add_to_ee(llvm::orc::ThreadSafeModule&, llvm::StringMap<llvm::orc::ThreadSafeModule*>&, llvm::DenseMap<llvm::orc::ThreadSafeModule*, int>&, std::vector<std::vector<llvm::orc::ThreadSafeModule*> >&, int)::<lambda(llvm::Module&)> > at /home/liozou/julia/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136 [inlined]
jl_add_to_ee at /home/liozou/julia/src/jitlayers.cpp:1671
operator() at /home/liozou/julia/src/jitlayers.cpp:1677 [inlined]
withModuleDo<jl_add_to_ee(llvm::orc::ThreadSafeModule&, llvm::StringMap<llvm::orc::ThreadSafeModule*>&, llvm::DenseMap<llvm::orc::ThreadSafeModule*, int>&, std::vector<std::vector<llvm::orc::ThreadSafeModule*> >&, int)::<lambda(llvm::Module&)> > at /home/liozou/julia/usr/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h:136 [inlined]
jl_add_to_ee at /home/liozou/julia/src/jitlayers.cpp:1671
jl_add_to_ee at /home/liozou/julia/src/jitlayers.cpp:1715 [inlined]
_jl_compile_codeinst at /home/liozou/julia/src/jitlayers.cpp:230
jl_generate_fptr_impl at /home/liozou/julia/src/jitlayers.cpp:429
jl_compile_method_internal at /home/liozou/julia/src/gf.c:2156 [inlined]
jl_compile_method_internal at /home/liozou/julia/src/gf.c:2097
_jl_invoke at /home/liozou/julia/src/gf.c:2439 [inlined]
ijl_apply_generic at /home/liozou/julia/src/gf.c:2629
jl_apply at /home/liozou/julia/src/julia.h:1866 [inlined]
start_task at /home/liozou/julia/src/task.c:1085
Allocations: 11649971 (Pool: 11635914; Big: 14057); GC: 9
```
</details>

Both errors only appear when running the test from Pkg mode (or from `Pkg.test("CrystalNets")`, not with `include("runtests.jl")`.

My `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.9.0-DEV.1417
Commit ed01ee036b (2022-09-21 11:27 UTC)
DEBUG build
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 40 × Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, cascadelake)
  Threads: 8 on 40 virtual cores
Environment:
  JULIA_NUM_THREADS = 8
```

Git bisection points to caf544b9a8a3d11ea01a82221c970ac886aa2566 @pchintalapudi.

### PR DESCRIPTION
**Pull request by pchintalapudi**
Fixes #46852, adjusts the relevant test to catch this type of error.

### CODE REVIEW

**Review by Keno — APPROVED** [review]

File: src/llvm-late-gc-lowering.cpp [hunk 1]
```diff
@@ -781,6 +781,9 @@ void LateLowerGCFrame::LiftPhi(State &S, PHINode *Phi) {
                             assert(isa<Instruction>(BaseElem) && "Unknown value type detected!");
                             InsertBefore = cast<Instruction>(BaseElem)->getNextNonDebugInstruction();
```
Comment (vtjnash) [inline src/llvm-late-gc-lowering.cpp:782]: LLVM will soon have `getInsertionPointAfterDef`, which would be an even more correct implementation for this PR to use here
