### PR TITLE
fix tab completion of invalid identifiers

### LINKED ISSUE #47593: REPL tab completions broken for invalid identifier names
```
struct A
    var"()"::Int
end
a = A(1)
a.<TAB>
```
autocompletes with `a.()` instead of `a.var"()"`

### PR DESCRIPTION
**Pull request by oscardssmith**
fixes https://github.com/JuliaLang/julia/issues/47593.

### CODE REVIEW

File: stdlib/REPL/src/REPLCompletions.jl [hunk 1]
```diff
@@ -95,13 +95,19 @@ function Base.getproperty(c::Completion, name::Symbol)
     return getfield(c, name)
 end
 
+function representable_string(s::Symbol)
+    io = IOBuffer()
```
Comment (KristofferC) [inline stdlib/REPL/src/REPLCompletions.jl:99]: This is function is just `sprint(Base.show_sym, s)`

File: stdlib/REPL/src/REPLCompletions.jl [hunk 2]
```diff
@@ -95,13 +95,15 @@ function Base.getproperty(c::Completion, name::Symbol)
     return getfield(c, name)
 end
 
+representable_string(s::Symbol) = sprint(Base.show_sym, s)
```
Comment (KristofferC) [inline stdlib/REPL/src/REPLCompletions.jl:98]: Feels like this can just be manually inlined? The current function name is a bit strange and inlining it avoids having to come up with a better one, heh.

Comment (vtjnash) [reply stdlib/REPL/src/REPLCompletions.jl:98]: A better name: `Base.sym_to_string`? lol

**Comment by aviatesk** [comment]
@oscardssmith Can you add a test please?
