### PR TITLE
Fix issue 19534

### LINKED ISSUE #19534: WeakKeyDict has not the usual Associative constructors
WeakKeyDicts can only be created empty and then filled:
```julia
julia> WeakKeyDict()[BigFloat(1)]=1 # works
1

julia> WeakKeyDict(BigFloat(1)=>1)
ERROR: MethodError: Cannot `convert` an object of type Pair{BigFloat,Int64} to an object of type WeakKeyDict{K,V}
This may have arisen from a call to the constructor WeakKeyDict{K,V}(...),
since type constructors fall back to convert methods.
 in WeakKeyDict{K,V}(::Pair{BigFloat,Int64}) at ./sysimg.jl:66

julia> WeakKeyDict(i=>BigFloat(i) for i=1:2)
ERROR: MethodError: Cannot `convert` an object of type Base.Generator{UnitRange{Int64},##5#6} to an object of type WeakKeyDict{K,V}
This may have arisen from a call to the constructor WeakKeyDict{K,V}(...),
since type constructors fall back to convert methods.
 in WeakKeyDict{K,V}(::Base.Generator{UnitRange{Int64},##5#6}) at ./sysimg.jl:66
```
Those constructors should probably be added.

### PR DESCRIPTION
**Pull request by mauro3**
This fixes #19534.

### CODE REVIEW

File: base/weakkeydict.jl [hunk 1]
```diff
@@ -1,22 +1,78 @@
 # weak key dictionaries
 
 type WeakKeyDict{K,V} <: Associative{K,V}
-    ht::Dict{Any,V}
+    ht::Dict{WeakRef,V}
```
Comment (mauro3) [inline base/weakkeydict.jl]: This change is unrelated.  I can revert it but it seems to me that the stricter type is a bit saver.

File: base/weakkeydict.jl [hunk 2]
```diff
@@ -1,22 +1,78 @@
...
+        sizehint!(h, length(ps))
+        for p in ps
+            h[p.first] = p.second
+        end
+        return h
+    end
 end
 WeakKeyDict() = WeakKeyDict{Any,Any}()
 
+WeakKeyDict(kv::Tuple{}) = WeakKeyDict()
```
Comment (mauro3) [inline base/weakkeydict.jl]: These outer constructors are copies of the Dict ones.  It could be DRYed up using something along the lines of
```
type A1{T}
    a::T
    A1(x) = new(x)
end
type A2{T}
    a::T
    A2(x) = new(x)
end
typealias A Union{A1,A2}
(::Type{TA}){TA<:A,T}(x::T) = TA{T}(x)
```
However, I suspect that there will be boot-strap isssues as WeakKeyDict comes later, thus these constructors would need to be added to weakkeydict.jl.  Alternatively, I could put a comment into dict.jl to state to keep the constructors synchronized.

**Comment by StefanKarpinski** [comment]
Could you make the commit message a bit more informative?

**Comment by mauro3** [comment]
@StefanKarpinski, yes will do. I'll also squash into one.  (I'll wait for a bit for other comments)

**Comment by mauro3** [comment]
Fixed up commit message.  Fixed `Int64` issue in tests.

File: base/weakkeydict.jl (hunk 2 above)
Comment (mauro3) [inline base/weakkeydict.jl]: I went with the comment in dict.jl

**Comment by mauro3** [comment]
The Appveyor [build](https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.8543/job/0hmoj97m76hmgwj7) got to `Build success` but seems to be stuck there for almost an hour. Any idea what that is?

**Comment by mauro3** [comment]
That appveyor build is stuck for sure.

File: test/dict.jl [hunk 3]
```diff
@@ -628,7 +639,10 @@ Dict(1 => rand(2,3), 'c' => "asdf") # just make sure this does not trigger a dep
     @test !isempty(wkd)
 
     wkd = empty!(wkd)
+    @test wkd==similar(wkd)
+    @test typeof(wkd)==typeof(similar(wkd))
```
Comment (tkelman) [inline test/dict.jl]: unaddressed

Comment (mauro3) [inline test/dict.jl]: Sorry to have wasted your time, I forgot to push...

**Comment by mauro3** [comment]
Updated formatting of tests according to @tkelman's comment.

**Review by tkelman — APPROVED** [review]
lgtm

**Comment by tkelman** [comment]
If no other opinions here I'll merge this and #19515 later today.
