### PR TITLE
Fix `mapreduce` on `AdjOrTrans`

### LINKED ISSUE #951: `extrema([3,7,4]')` throws
In Julia 1.8 and master:
```julia
ulia> extrema([3,7,4]')
ERROR: MethodError: no method matching adjoint(::Tuple{Int64, Int64})
  ...
```
whereas in 1.7 as expected:
```
julia> extrema([3,7,4]')
(3, 7)
```

I guess in the new `extrema` implementation the transpose somehow is propagated through the computation and then applied to the result-tuple.

### LINKED ISSUE #46714: `extrema([3,7,4]')` throws
In Julia 1.8 and master:
```julia
ulia> extrema([3,7,4]')
ERROR: MethodError: no method matching adjoint(::Tuple{Int64, Int64})
  ...
```
whereas in 1.7 as expected:
```
julia> extrema([3,7,4]')
(3, 7)
```

I guess in the new `extrema` implementation the transpose somehow is propagated through the computation and then applied to the result-tuple.

### PR DESCRIPTION
**Pull request by SobhanMP**
see https://github.com/JuliaSparse/SparseArrays.jl/pull/244. Lots of operations are defined in term of _mapreduce i.e. sum. We think it makes sense that transpose "forwards" the map reduce to the parent as to not use the abstractarray implementation if the parent has a better implementation. While this is not as important for dense arrays, for special arrays like sparse matrices, this has grave consequences. We think that it makes sense that this should be added to LinearAlgebra.

(didn't run tests, waiting for CI)
@dkarrasch

Fixes JuliaLang/LinearAlgebra.jl#951.

### CODE REVIEW

**Comment by dkarrasch** [comment]
@tkf I'm not familiar with the transducer stuff. I was expecting `sum(A')` to be much slower than `sum(A)` for big matrices due to an unfortunate memory reading pattern (as I'm seeing in a simple hand-written for-loop case, iterating over `eachindex(A)`). But I'm seeing essentially identical runtimes for both cases, even though they take different code paths: `sum(A)` takes some `mapreduce(..., ::IndexLinear, A)` route, whereas `sum(A')` enters the `mapfoldl` mechanism. To me surprisingly, the approach taken in this PR then doesn't give any benefit on dense matrices.

As stated in the OP, it certainly helps in the sparse case, or just as much, in cases of matrices  that have "non-symmetric" reduction methods implemented, whose transposes/adjoints then would go inefficient `mapreduce(..., ::IndexCartesian, A)` routes.

**Comment by martinholters** [comment]
I was about to complain that this would change the order in which the reduction happens (while `op` has to be associative, we don't necessarily expect it to be commutative in general, I think). But apparently, that's already the case:
```julia
julia> mapreduce(identity, (x, y) -> 10x+y, copy([1 2; 3 4]'))
1234

julia> mapreduce(identity, (x, y) -> 10x+y, [1 2; 3 4]')
1324
```
This looks like a bug to me, but code out there might be relying on this behaviour.

Another thing I've noticed:
```julia
julia> mapreduce(string, *, copy([1 2; 3 4]'))
"1234"

julia> mapreduce(string, *, [1 2; 3 4]')
ERROR: MethodError: no method matching adjoint(::String)
```
Why are we applying adjoint to the result of applying `string` here? OTOH, this works:
```julia
julia> reduce(*, map(string, [1 2; 3 4]'))
"1234"
```
I won't hold up this PR for not fixing things it wasn't meant to fix, but while you're at it, maybe you could?

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 1]
```diff
@@ -452,3 +452,15 @@ pinv(v::TransposeAbsVec, tol::Real = 0) = pinv(conj(v.parent)).parent
 ## complex conjugate
 conj(A::Transpose) = adjoint(A.parent)
 conj(A::Adjoint) = transpose(A.parent)
+
+## reductions
+for (ttype, transform) in ((:Adjoint, adjoint), (:Transpose, transpose))
+    @eval _mapreduce(f, op, ::IndexStyle, A::$ttype) =
+        _mapreduce(f∘$transform, op, IndexStyle(parent(A)), parent(A))
```
Comment (SobhanMP) [inline stdlib/LinearAlgebra/src/adjtrans.jl:459]: i think this should not overwrite the IndexStyle. instead the default index style function should return the default index style of the parent

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:459]: I think this method definition should be removed anyway, as the above cited ones should do the job already.

**Comment by dkarrasch** [comment]
@martinholters Can you please take another look when you find the time. I'm not sure we can fix your mapreduce-string example, because that fails in a broader context, see:

```julia
julia> ["a" "b"; "c" "d"]'
2×2 adjoint(::Matrix{String}) with eltype Union{}:
Error showing value of type LinearAlgebra.Adjoint{Union{}, Matrix{String}}:
ERROR: MethodError: no method matching adjoint(::String)
```

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 2]
```diff
@@ -378,15 +378,31 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
 
 
 ### reductions
-# faster to sum the Array than to work through the wrapper
-Base._mapreduce_dim(f, op, init::Base._InitialValue, A::Transpose, dims::Colon) =
+# faster to sum the Array than to work through the wrapper (but only in commutative reduction ops)
+const CommutativeOps = Union{typeof(+),typeof(Base.add_sum),typeof(-),typeof(min),typeof(max),typeof(|),typeof(&)}
```
Comment (martinholters) [inline stdlib/LinearAlgebra/src/adjtrans.jl:382]: I haven't looked any closer at the code where this is used, but having `-` in a list with this name sounds wrong.

```suggestion
const CommutativeOps = Union{typeof(+),typeof(Base.add_sum),typeof(min),typeof(max),typeof(|),typeof(&)}
```
But as `-` is also not associative, it should not be used with `reduce` anyway I guess.

**Comment by martinholters** [comment]
Regarding the original intention of this PR and the current implementation, I cannot offer any helpful feedback. But I'm glad to see the bug I've discovered is fixed.

Regarding the `string` case, I'd like to point out that this works:
```julia
julia> reduce(*, map(string, [1 2; 3 4]'))
"1234"
```
But as I've said before, I don't want to force this PR into fixing things it wasn't meant to fix. So feel free to ignore this case.

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 2 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:382]: The name is bad, I agree, but in the case of reduction, we have

```julia
init - f(a_1) - f(a_2) - ... - f(a_n) = init - (f(a_1) + f(a_2) + ... + f(a_n))
```

where the terms in the last bracket commute. So, by "`CommutativeOps` we don't mean `op(x, y) = op(y, x)`, but rather `op(op(x, y), z) = op(op(x, z), y)`. I'll add a comment to the very least, and will keep thinking about a better name for the union. Perhaps `CommutativeReductionOps`... 😅

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:382]: From what I understand, yes:

https://github.com/JuliaLang/julia/blob/81eb6ef068fe2999340b4403a3855f38e361b74f/base/reducedim.jl#L362-L363

Comment (martinholters) [reply stdlib/LinearAlgebra/src/adjtrans.jl:382]: But that's an implementation detail, not something that is guaranteed, or?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:382]: Which example do you have in mind that would be critical in connection with `-`? I'm not insisting on including `-` in the list, I'd just like to understand which possible issues can arise... out of curiosity. To me, `-` is like `+`, which we include in the list, with a prepended `-`, so I don't see the issue, but may be missing something.

Comment (martinholters) [reply stdlib/LinearAlgebra/src/adjtrans.jl:382]:
```julia
julia> foldl(-, 1:4)
-8

julia> foldr(-, 1:4)
-2

julia> reduce(-, 1:4)
-8 # could also be -2 or (1-2)-(3-4)=0 or 1-((2-3)-4)=6
```
Adding commutations in there would probably not make things much worse, but feels strange to explicitly allow it.

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:382]: I see. I think that in Base, both the generator-based and the array specific implementation operate in the `foldl` way, currently. But I see the point that it is not specified/guaranteed. Thanks for taking the time to explain!

**Comment by dkarrasch** [comment]
> Regarding the `string` case, I'd like to point out that this works:

I'm not sure we can do much about that. Taking adjoints of strings is apparently not intended to work, and the above combination is one that works "by chance", whereas moving the adjoint by one bracket fails for the same reason: `reduce(*, map(string, [1 2; 3 4])')`. I assume this could be made to work by defining a generic fallback:

```julia
adjoint(x) = x
tranpose(x) = x
```

which I'm not going to propose. A similar generalization of basic operators got reverted a few months ago after causing lots of hassle 😅 .

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 3]
```diff
@@ -378,15 +378,31 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
...
 ### reductions
-# faster to sum the Array than to work through the wrapper
-Base._mapreduce_dim(f, op, init::Base._InitialValue, A::Transpose, dims::Colon) =
+# faster to sum the Array than to work through the wrapper (but only in commutative reduction ops)
+const CommutativeOps = Union{typeof(+),typeof(Base.add_sum),typeof(min),typeof(max),typeof(|),typeof(&)}
+Base._mapreduce_dim(f, op::CommutativeOps, init::Base._InitialValue, A::Transpose, dims::Colon) =
     transpose(Base._mapreduce_dim(_sandwich(transpose, f), _sandwich(transpose, op), init, parent(A), dims))
-Base._mapreduce_dim(f, op, init::Base._InitialValue, A::Adjoint, dims::Colon) =
+Base._mapreduce_dim(f, op::CommutativeOps, init::Base._InitialValue, A::Adjoint, dims::Colon) =
     adjoint(Base._mapreduce_dim(_sandwich(adjoint, f), _sandwich(adjoint, op), init, parent(A), dims))
```
Comment (N5N3) [inline stdlib/LinearAlgebra/src/adjtrans.jl:386]: It seems more intuitive to make these `CommutativeOps` call
```julia
Base._mapreduce_dim(f, op::CommutativeOps, init::Base._InitialValue, A::Transpose, dims::Colon) =
    Base._mapreduce_dim(f∘transpose, op, init, parent(A), dims)
```
Then we can add `Base._extrema_rf` to this list to fix #46714

Comment (N5N3) [reply stdlib/LinearAlgebra/src/adjtrans.jl:386]: And L399 could be replaced with
```julia
Base.mapreducedim!(f, op::CommutativeOps, B::AbstractArray, A::TransposeAbsMat) =
    (Base.mapreducedim!(f∘transpose, op, B, parent(A)); B)
Base.mapreducedim!(f, op::CommutativeOps, B::AbstractArray, A::AdjointAbsMat) =
    (Base.mapreducedim!(f∘transpose, op, B, parent(A)); B)
switch_dim12(B::AbstractVector) = permutedims(B)
switch_dim12(B::AbstractArray{<:Any,0}) = B
switch_dim12(B::AbstractArray) = PermutedDimsArray(B, (2, 1, ntuple(Base.Fix1(+,2), ndims(B) - 2)...))
```

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:386]: > ```julia
> Base._mapreduce_dim(f, op::CommutativeOps, init::Base._InitialValue, A::Transpose, dims::Colon) =
>     Base._mapreduce_dim(f∘transpose, op, init, parent(A), dims)
> Base._mapreduce_dim(f, op::CommutativeOps, init::Base._InitialValue, A::Adjoint, dims::Colon) =
>     Base._mapreduce_dim(f∘adjoint, op, init, parent(A), dims)
> ```

The sandwiching mechanism was introduced by @mcabbott in #39513, and I believe it is for the following reason: summing a transpose matrix of (recursively transposed) matrices should perhaps result in a `Transpose`, which is what the current design yields. Otherwise redirecting to `f∘transpose` - perhaps in more restricted (`Number`?) cases - should be good enough.

Comment (mcabbott) [reply stdlib/LinearAlgebra/src/adjtrans.jl:386]: Oh that's embarrassing, sorry, I thought we thought this all through carefully. But `prod` is clearly broken.

Comment (mcabbott) [reply stdlib/LinearAlgebra/src/adjtrans.jl:386]: OK, now I think the sandwich story is just wrong, even for arrays of numbers:
```julia
julia> mapreduce(imag, +, [1 2im 3])
2

julia> mapreduce(imag, +, [1, 2im, 3]')
-2

julia> mapreduce(x -> [x;;;], +, [1 2 3])
1×1×1 Array{Int64, 3}:
[:, :, 1] =
 6

julia> mapreduce(x -> [x;;;], +, [1, 2, 3]')
ERROR: adjoint not defined for Array{Int64, 3}. 
```

The suggestion by N5N3 to do `f∘transpose` seems like a good one to me. 

Is the restriction to `CommutativeOps` necessary? `reduce` makes no claims about the order of operations, so arguably `prod(::Matrix{Matrix})` is ill-defined, you should call `foldl`. The case of  `prod(::Adjoint{Float64, ...})` is one that it would be nice to send the fast path.

Comment (N5N3) [reply stdlib/LinearAlgebra/src/adjtrans.jl:386]: Since these dispatches are for performance reason, I think we'd better keep the same result as the general fallback.
As for `prod(::Adjoint{Float64, ...})`, `*` should be commutative for `Number`, maybe we can use `Core.Compiler,return_type` to turn the optimization on.
It should be ok as even the inference fails, the result should be similar (with negligible numerical difference).

**Comment by dkarrasch** [comment]
With the next commit, the following now "works":

```julia
julia> mapreduce(string, *, [1 2; 3 4]')
"1324"

julia> mapreduce(string, *, copy([1 2; 3 4]'))
"1234"
```

Apparently, we don't necessarily need that the eltype of the matrix is such that `*` commutes, but that `*` commutes for the return types of `f`. I guess we should be conservative and restrict to `f::Identity` for `*`? Then the fast path would apply to `prod(A')`, which is perhaps our main concern.

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 4]
```diff
@@ -378,22 +378,37 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
...
-Base.mapreducedim!(f, op, B::AbstractArray, A::AdjointAbsMat) =
-    adjoint(Base.mapreducedim!(_sandwich(adjoint, f), _sandwich(adjoint, op), adjoint(B), parent(A)))
-
-_sandwich(adj::Function, fun) = (xs...,) -> adj(fun(map(adj, xs)...))
-for fun in [:identity, :add_sum, :mul_prod] #, :max, :min]
-    @eval _sandwich(::Function, ::typeof(Base.$fun)) = Base.$fun
-end
-
+Base.mapreducedim!(f, op::CommutativeOps, B::AbstractArray, A::TransposeAbsMat) =
+    (Base.mapreducedim!(f∘transpose, op, switch_dim12(B), parent(A)); B)
```
Comment (N5N3) [inline stdlib/LinearAlgebra/src/adjtrans.jl:401]: missing `f::typeof(identity)`?

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 3 above)
Comment (martinholters) [reply stdlib/LinearAlgebra/src/adjtrans.jl]: > Is the restriction to `CommutativeOps` necessary? `reduce` makes no claims about the order of operations, 

For, say, `reduce(*, ["a", "b", "c", "d"])` all of the following would be valid ways to compute the result:
* `"a" * ("b" * ("c" * "d"))`
* `(("a" * "b") * "c") * "d"`
* `("a" * "b") * ("c" * "d")`
* `("a" * ("b" * "c")) * "d"`
* `"a" * (("b" * "c") * "d")`

They all yield `"abcd"`. But `reduce` is not allow to do, say `"a" * (("c" * "b") * "d")`. But if the operation is commutative, the result is the same, so `reduce` would be ok to do this reordering then.

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 4 above)
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:401]: You're right. What I said above applies to all `op`s, right? They need to be commutative on the image of `f`.

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:401]: Wait, whatever `f` does and whatever type it returns, the operations are assumed to be commutative, aren't they?

Comment (N5N3) [reply stdlib/LinearAlgebra/src/adjtrans.jl:401]: sorry, I mark on the wrong line. should be L404 and L406

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:401]: Good catch!

**Comment by dkarrasch** [comment]
Alright, tests are passing. Thanks everyone for suggestions, more test cases and comments!
