### PR TITLE
define dot between AbstractMatrix and UniformScaling

### LINKED ISSUE #831: Define dot between UniformScaling and Matrix
```jl
julia> using LinearAlgebra; U = UniformScaling(2); A = ones(2,2); dot(U, A)
ERROR: MethodError: no method matching iterate(::UniformScaling{Int64})
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:737
  iterate(::Union{LinRange, StepRangeLen}, ::Int64) at range.jl:737
  iterate(::T) where T<:Union{Base.KeySet{var"#s78", var"#s77"} where {var"#s78", var"#s77"<:Dict}, Base.ValueIterator{var"#s76"} where var"#s76"<:Dict} at dict.jl:693
  ...
Stacktrace:
 [1] dot(x::UniformScaling{Int64}, y::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:876
 [2] top-level scope
   @ REPL[13]:1
```
I guess it would make sense for this use `U.λ * tr(A)`

### LINKED ISSUE #40248: Define dot between UniformScaling and Matrix
```jl
julia> using LinearAlgebra; U = UniformScaling(2); A = ones(2,2); dot(U, A)
ERROR: MethodError: no method matching iterate(::UniformScaling{Int64})
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:737
  iterate(::Union{LinRange, StepRangeLen}, ::Int64) at range.jl:737
  iterate(::T) where T<:Union{Base.KeySet{var"#s78", var"#s77"} where {var"#s78", var"#s77"<:Dict}, Base.ValueIterator{var"#s76"} where var"#s76"<:Dict} at dict.jl:693
  ...
Stacktrace:
 [1] dot(x::UniformScaling{Int64}, y::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:876
 [2] top-level scope
   @ REPL[13]:1
```
I guess it would make sense for this use `U.λ * tr(A)`

### PR DESCRIPTION
**Pull request by lkapelevich**
closes JuliaLang/LinearAlgebra.jl#831

### CODE REVIEW

File: stdlib/LinearAlgebra/src/uniformscaling.jl [hunk 1]
```diff
@@ -480,6 +480,9 @@ Array(s::UniformScaling, dims::Dims{2}) = Matrix(s, dims)
 Diagonal{T}(s::UniformScaling, m::Integer) where {T} = Diagonal{T}(fill(T(s.λ), m))
 Diagonal(s::UniformScaling, m::Integer) = Diagonal{eltype(s)}(s, m)
 
+dot(A::AbstractMatrix, J::UniformScaling) = tr(A)*J.λ
+dot(J::UniformScaling, A::AbstractMatrix) = J.λ*tr(A)
```
Comment (sethaxen) [inline stdlib/LinearAlgebra/src/uniformscaling.jl:484]: This seems safer, since the generic implementation of `dot` calls `dot` on the individual elements of the matrices. Also this makes sure that the first argument is conjugated correctly.
```suggestion
dot(A::AbstractMatrix, J::UniformScaling) = dot(tr(A), J.λ)
dot(J::UniformScaling, A::AbstractMatrix) = dot(J.λ, tr(A))
```

File: stdlib/LinearAlgebra/test/uniformscaling.jl [hunk 2]
```diff
@@ -460,6 +460,14 @@ end
     @test I(3) == [1 0 0; 0 1 0; 0 0 1]
 end
 
+@testset "dot" begin
+    A = rand(-10:10, 3, 3)
+    λ = rand(-10:10)
```
Comment (sethaxen) [inline stdlib/LinearAlgebra/test/uniformscaling.jl:465]: Can you add a check for complex numbers as well?

**Review by sethaxen — CHANGES_REQUESTED** [review]

File: stdlib/LinearAlgebra/test/uniformscaling.jl (hunk 2 above)
Comment (lkapelevich) [reply stdlib/LinearAlgebra/test/uniformscaling.jl]: Thanks for catching, definitely got that case wrong

**Review by sethaxen — APPROVED** [review]

**Comment by chriscoey** [comment]
bump!

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
LGTM; it's consistent with treating `I` as a square matrix of appropriate size in `+` and `*`

**Comment by stevengj** [comment]
Needs a NEWS entry, though.

**Comment by kshyatt** [comment]
Anything holding this up?

**Comment by lkapelevich** [comment]
i don't see anything on my end
