### PR TITLE
inference: always bail out const-prop' with non-const result limited

### LINKED ISSUE #52763: REPL becomes unresponsive during completion inference
On master, typing the following makes the REPL completely unresponsive with 100% CPU usage for more than an hour:
```julia
julia> import Clapeyron

julia> Clapeyron.isstable(Clapeyron.GERG2008(["carbon dioxide"]),
```

(the last comma must be typed, not copy-pasted, or you have to type something after the comma in order to kick completion into action)

It does not respond to Ctrl+C either, but does print a stacktrace when sending a SIGUSR1:

<details>

<summary> SIGUSR1 stacktrace from julia-debug (first example) </summary>

```julia
signal (10): User defined signal 1
- at ./int.jl:86 [inlined]
iterate at ./array.jl:884 [inlined]
cache_lookup at ./compiler/inferenceresult.jl:235
const_prop_call at ./compiler/abstractinterpretation.jl:1229
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:852
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:818
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:111
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_unknown at ./compiler/abstractinterpretation.jl:2237
abstract_call at ./compiler/abstractinterpretation.jl:2247
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
const_prop_call at ./compiler/abstractinterpretation.jl:1244
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:852
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:818
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:111
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
jfptr_typeinf_12881 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
jl_apply at /LionelSSDext4/liozou/julia/src/julia.h:2152
jl_f__call_in_world at /LionelSSDext4/liozou/julia/src/builtins.c:894
#invoke_in_world#3 at ./essentials.jl:989 [inlined]
invoke_in_world at ./essentials.jl:986 [inlined]
#repl_eval_ex#28 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:681
repl_eval_ex at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:650 [inlined]
detect_args_kwargs at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:807
complete_methods_args at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:827 [inlined]
_complete_methods at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:707
complete_methods at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:712 [inlined]
completions at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:1259
complete_line at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:560
unknown function (ip: 0x7f3cf2927118)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2921
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
check_for_hint at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:384
#139 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2501
jl_fptr_args at /LionelSSDext4/liozou/julia/src/gf.c:2563
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
jl_apply at /LionelSSDext4/liozou/julia/src/julia.h:2152
jl_f__call_latest at /LionelSSDext4/liozou/julia/src/builtins.c:875
#invokelatest#2 at ./essentials.jl:955 [inlined]
invokelatest at ./essentials.jl:952 [inlined]
#27 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:1685
jfptr_YY.27_10394 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
prompt! at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2822
run_interface at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2724
jfptr_run_interface_10910 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
run_frontend at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1352
#64 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:401
jfptr_YY.64_12224 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
jl_apply at /LionelSSDext4/liozou/julia/src/julia.h:2152
start_task at /LionelSSDext4/liozou/julia/src/task.c:1306
```

</details>

<details>

<summary> SIGUSR1 stacktrace from julia-debug (example 2) </summary>

```julia
signal (10): User defined signal 1
jl_exprn at /LionelSSDext4/liozou/julia/src/builtins.c:1477
jl_decode_value_expr at /LionelSSDext4/liozou/julia/src/ircode.c:579
jl_decode_value at /LionelSSDext4/liozou/julia/src/ircode.c:711
jl_decode_value_memory at /LionelSSDext4/liozou/julia/src/ircode.c:500
jl_decode_value_array at /LionelSSDext4/liozou/julia/src/ircode.c:550
jl_decode_value at /LionelSSDext4/liozou/julia/src/ircode.c:704
ijl_uncompress_ir at /LionelSSDext4/liozou/julia/src/ircode.c:944
_uncompressed_ir at ./reflection.jl:1311 [inlined]
retrieve_code_info at ./compiler/utilities.jl:143 [inlined]
InferenceState at ./compiler/inferencestate.jl:480
typeinf_edge at ./compiler/typeinfer.jl:860
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_unknown at ./compiler/abstractinterpretation.jl:2237
abstract_call at ./compiler/abstractinterpretation.jl:2247
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3011
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:219
jfptr_typeinf_12881 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
jl_apply at /LionelSSDext4/liozou/julia/src/julia.h:2152
jl_f__call_in_world at /LionelSSDext4/liozou/julia/src/builtins.c:894
#invoke_in_world#3 at ./essentials.jl:989 [inlined]
invoke_in_world at ./essentials.jl:986 [inlined]
#repl_eval_ex#28 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:681
repl_eval_ex at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:650 [inlined]
detect_args_kwargs at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:807
complete_methods_args at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:827 [inlined]
_complete_methods at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:707
complete_methods at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:712 [inlined]
completions at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:1259
complete_line at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:560
unknown function (ip: 0x7f3cf2927118)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2921
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
check_for_hint at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:384
#139 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2501
jl_fptr_args at /LionelSSDext4/liozou/julia/src/gf.c:2563
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
jl_apply at /LionelSSDext4/liozou/julia/src/julia.h:2152
jl_f__call_latest at /LionelSSDext4/liozou/julia/src/builtins.c:875
#invokelatest#2 at ./essentials.jl:955 [inlined]
invokelatest at ./essentials.jl:952 [inlined]
#27 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:1685
jfptr_YY.27_10394 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
prompt! at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2822
run_interface at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2724
jfptr_run_interface_10910 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
run_frontend at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1352
#64 at /LionelSSDext4/liozou/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:401
jfptr_YY.64_12224 at /LionelSSDext4/liozou/julia/usr/share/julia/compiled/v1.11/REPL/u0gqU_e5kOS.so (unknown line)
_jl_invoke at /LionelSSDext4/liozou/julia/src/gf.c:2902
ijl_apply_generic at /LionelSSDext4/liozou/julia/src/gf.c:3098
jl_apply at /LionelSSDext4/liozou/julia/src/julia.h:2152
start_task at /LionelSSDext4/liozou/julia/src/task.c:1306
unknown function (ip: (nil))
```

</details>

Two comparison points:
- on 1.10.0, this freezes for a few seconds only (after hitting TAB to force completion inference).
- precomputing the `Clapeyron.GERG2008(["carbon dioxide"])` object first removes the issue:
   ```julia
   julia> import Clapeyron

   julia> model = Clapeyron.GERG2008(["carbon dioxide"]);

   julia> Clapeyron.isstable(model, # REPL is still responsive
   ```

___________

To avoid REPL freezes due to inference in general, a speculative solution could be to launch REPL completion inference from a separate (non-`interactive`) dedicated thread, and make it easily interruptible from a signal without killing the REPL? At least we'll need a way to interrupt inference without crashing the session if it's stuck.

For this particular issue though, I would assume there is an inference heuristic incorrectly set for REPL completion because actually executing the following code (by copy-pasting it into the REPL, or from a file) takes less than a minute to compile and execute:

```julia
julia> Clapeyron.isstable(Clapeyron.GERG2008(["carbon dioxide"]), 1e3, 300, 1)
true
```

<details>

<summary> versioninfo and Clapeyron version </summary>

```julia
julia> versioninfo()
Julia Version 1.11.0-DEV.1203
Commit 2816a3f0f7 (2024-01-05 14:14 UTC)
Build Info:
  DEBUG build
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)

(v1.11) pkg> status Clapeyron
Status `/LionelSSDext4/liozou/.julia/environments/v1.11/Project.toml`
  [7c7805af] Clapeyron v0.5.9
```

</details>

### PR DESCRIPTION
**Pull request by aviatesk**
Investigating into #52763, I've found that `AbstractInterpreters` which enables the `aggressive_constprop` option, such as `REPLInterpreter`, might perform const-prop' even if the result of a non-const call is `LimitedAccuracy`. This can lead to an unintended infinite loop with a custom aggressive const-prop' implementation.

This commit restricts const-prop' for such cases where the non-const call result is limited to avoid the issue. This fix is conservative, but given that accurate inference is mostly impossible when there are unresolvable cycles (which is indicated by limited result), aggressive const-prop' isn't necessary for such cases, and I don't anticipate this leading to any obvious regression.

fix #52763

### CODE REVIEW

**Comment by vtjnash** [comment]
LGTM

File: test/compiler/inference.jl [hunk 1]
```diff
@@ -4937,10 +4937,19 @@ g() = empty_nt_values(Base.inferencebarrier(Tuple{}))
...
+        return false # allow constprop to recurse into unresolved cycles
+    end
+    return @invoke CC.bail_out_const_call(interp::CC.AbstractInterpreter, result::CC.MethodCallResult,
+                                          si::CC.StmtInfo, sv::CC.AbsIntState)
+end
 Base.@constprop :aggressive type_level_recurse1(x...) = x[1] == 2 ? 1 : (length(x) > 100 ? x : type_level_recurse2(x[1] + 1, x..., x...))
 Base.@constprop :aggressive type_level_recurse2(x...) = type_level_recurse1(x...)
 type_level_recurse_entry() = Val{type_level_recurse1(1)}()
-@test Base.return_types(type_level_recurse_entry, ()) |> only == Val{1}
+@test Base.infer_return_type(type_level_recurse_entry, (); interp=RecurseInterpreter()) == Val{1}
```
Comment (aviatesk) [inline test/compiler/inference.jl:4952]: @Keno This PR prevents const-prop' in the presence of unresolvable cycles, regardless of whether const-prop' is enforced. Consequently, it causes the test cases from #48045 to fail. For interpreters requiring optimization against heavy recursions, like Diffractor, do you think it would fine to make them add explicit overloads to permit const-prop' for cycles as like `RecurseInterpreter` here?

Comment (Keno) [reply test/compiler/inference.jl:4952]: I don't fully know. I'm now entirely happy with the recursion story with respect to Diffractor anyway, so I think that needs a larger solution. As long as this doesn't end up causing us immediate problems, I think it's fine.

Comment (aviatesk) [reply test/compiler/inference.jl:4952]: In that case, I'll move forward with this plan. I'll implement the necessary adjustments in Diffractor that would be similar to what `RecurseInterpreter` does here.

**Comment by aviatesk** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by aviatesk** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52836#issuecomment-1890384990) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/7901b6b_vs_e3a64e8/report.html) is available.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52836#issuecomment-1890886988) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/a9d2126_vs_a034aa1/report.html) is available.
