### PR TITLE
fix: trigger error hints on exception supertypes too

### LINKED ISSUE #58367: Define error hints for abstract exception types
Would a PR be welcome that changes this line

https://github.com/JuliaLang/julia/blob/24d2f4af851e6911fe2ea242a82cf2338d46afc1/base/experimental.jl#L318

to get exception handlers for every supertype of `typeof(exc)`? That way, [error hints](https://docs.julialang.org/en/v1/base/base/#Base.Experimental.register_error_hint) wouldn't have to be defined for every concrete type.

### PR DESCRIPTION
**Pull request by gdalle**
Fixes #58367

### CODE REVIEW

**Comment by tecosaur** [comment]
I'm afraid I can't offer a full review, but I do want to say that I love `module Hinterland` in the tests :laughing:

**Comment by DilumAluthge** [comment]
@vtjnash Could you review this?

**Comment by DilumAluthge** [comment]
And maybe also @timholy?

**Comment by gdalle** [comment]
Crap, I struggled with the master build on my Mac so I didn't test locally but judging by CI it seems that

```
UndefVarError: `supertypes` not defined in `Base.Experimental`
```

which makes sense since `supertypes` comes from the `InteractiveUtils` stdlib. Is this approach doomed to fail?

**Comment by tecosaur** [comment]
> which makes sense since supertypes comes from the InteractiveUtils stdlib. Is this approach doomed to fail?

Not at all, you can still use `supertype` in a while loop.

File: base/experimental.jl [hunk 1]
```diff
@@ -295,18 +295,18 @@ Closest candidates are:
     `if isdefined(Base.Experimental, :register_error_hint) ... end` block.
 """
 function register_error_hint(@nospecialize(handler), @nospecialize(exct::Type))
-    list = get!(Vector{Any}, _hint_handlers, exct)
+    list = get!(Vector{Any}, _hint_handlers, nameof(exct))
```
Comment (vtjnash) [inline base/experimental.jl]:
```suggestion
    list = get!(Vector{Any}, _hint_handlers, typename(exct))
```

File: base/experimental.jl [hunk 2]
```diff
@@ -295,18 +295,18 @@ Closest candidates are:
...
     push!(list, handler)
     return nothing
 end
 
-const _hint_handlers = IdDict{Type,Vector{Any}}()
+const _hint_handlers = IdDict{Symbol,Vector{Any}}()
```
Comment (vtjnash) [inline base/experimental.jl]:
```suggestion
const _hint_handlers = IdDict{Typename,Vector{Any}}()
```

File: base/experimental.jl [hunk 3]
```diff
@@ -316,15 +316,20 @@ the handler for that type.
...
-    isnothing(hinters) && return
-    for handler in hinters
-        try
-            @invokelatest handler(io, ex, args...)
-        catch
-            tn = typeof(handler).name
-            @error "Hint-handler $handler for $(typeof(ex)) in $(tn.module) caused an error" exception=current_exceptions()
+    ex_supertype = typeof(ex)
+    while ex_supertype != Any
+        hinters = get(_hint_handlers, ex_supertype, nothing)
```
Comment (vtjnash) [inline base/experimental.jl]:
```suggestion
        hinters = get(_hint_handlers, typename(ex_supertype), nothing)
```

File: base/experimental.jl [hunk 4]
```diff
@@ -295,18 +295,18 @@ Closest candidates are:
     `if isdefined(Base.Experimental, :register_error_hint) ... end` block.
 """
 function register_error_hint(@nospecialize(handler), @nospecialize(exct::Type))
-    list = get!(Vector{Any}, _hint_handlers, exct)
+    list = get!(Vector{Any}, _hint_handlers, nameof(exct))
     push!(list, handler)
```
Comment (vtjnash) [inline base/experimental.jl]:
```suggestion
    push!(list, exct, handler)
```

File: base/experimental.jl [hunk 5]
```diff
@@ -316,15 +316,20 @@ the handler for that type.
...
-        try
-            @invokelatest handler(io, ex, args...)
-        catch
-            tn = typeof(handler).name
-            @error "Hint-handler $handler for $(typeof(ex)) in $(tn.module) caused an error" exception=current_exceptions()
+    ex_supertype = typeof(ex)
+    while ex_supertype != Any
+        hinters = get(_hint_handlers, ex_supertype, nothing)
+        isnothing(hinters) && continue
+        for handler in hinters
```
Comment (vtjnash) [inline base/experimental.jl]:
```suggestion
        for handler in 1:2:length(hinters)
            ex isa hinters[handler] || continue
            handler = hinters[handler + 1]
```

Comment (gdalle) [reply base/experimental.jl]: I don't understand the point of this one, can you enlighten me?

Comment (vtjnash) [reply base/experimental.jl]: This avoids calling hinters that did not apply to the given ex

Comment (gdalle) [reply base/experimental.jl]: Oh right, I was thrown off by your double use of the `handler` variable. Maybe it would be clearer like this? Or using two zipped lists even?
```suggestion
        for k in 1:2:length(hinters)
            ex isa hinters[k] || continue
            handler = hinters[k + 1]
```

**Comment by DilumAluthge** [comment]
@vtjnash Can you do another review?

**Comment by DilumAluthge** [comment]
@gdalle I think the CI failures are related to this PR. Are you able to build this PR branch locally?

```
rror during bootstrap:
LoadError("sysimg.jl", 3, LoadError("Base.jl", 251, LoadError("experimental.jl", 303, UndefVarError(:TypeName, 0x0000000000006487, Base.Experimental))))
ijl_undefined_var_error at [buildroot]/src/rtutils.c:167
```

**Comment by gdalle** [comment]
Last time I tried the Julia build showed errors on my Mac M3, which is why I didn't test locally. Not sure if this is expected or not with the current master

**Comment by DilumAluthge** [comment]
> Last time I tried the Julia build showed errors on my Mac M3, which is why I didn't test locally. Not sure if this is expected or not with the current master

Hmmm, we generally expect that you can build master locally. What's the error you get? We may need to open a new issue.

**Comment by DilumAluthge** [comment]
The Build jobs are hanging on CI, reproducible after a retry. Master is green, so this seems related to the PR.

**Comment by DilumAluthge** [comment]
> > Last time I tried the Julia build showed errors on my Mac M3, which is why I didn't test locally. Not sure if this is expected or not with the current master
> 
> Hmmm, we generally expect that you can build master locally. What's the error you get? We may need to open a new issue.

@gdalle Try building master first, before you try building this PR.

I just confirmed that I can successfully build master (c1353acc1008548cecd5ed51ef605df1d7003a43) locally on an M2 MacBook.

**Comment by DilumAluthge** [comment]
@vtjnash Any idea why this PR would cause a hang when building Julia?

**Comment by gdalle** [comment]
I'll try building tomorrow and report back. Hope we can sneak this into 1.13

**Comment by gdalle** [comment]
I tried to build locally, `master` works but this PR fails. It runs for really long and then crashes my console. I don't know how to see the error on the buildkite logs, where should I look?

**Comment by tecosaur** [comment]
I just took a look at the builtkite logs

image

Seems like the builds are failing because they're timing out.

**Comment by gdalle** [comment]
Could it be an infinite `while` loop here?

```julia
while ex_supertype != Any
```

That seems unlikely but it is the only reason I can think of for a timeout

**Comment by abraemer** [comment]
Seems unlikely but also easy to check: You could keep track of types you have already seen and then abort the loop once `supertype` gives you a type you saw already. That would cover any sorts of strange loops. 

Perhaps simpler for debugging: Keep track of the number of iterations and if it exceeds e.g. 20 or so then you log the type and abort the loop.

**Comment by gdalle** [comment]
I figured it out: the shortcut `isnothing(hinters) && continue` did not replace `ex_supertype` with its supertype, so it did not make any progress towards `Any`. That's what was triggering the infinite loop

**Comment by DilumAluthge** [comment]
```
Error in testset errorshow:
Error During Test at /cache/build/tester-amdci4-8/julialang/julia-master/julia-8cb1702aa9/share/julia/test/testdefs.jl:25
```

**Comment by gdalle** [comment]
Oh right, the test suite is doing some weird popping so that the length doesn't stay even. I'll fix it tomorrow

**Comment by gdalle** [comment]
Now my new test is passing but some older tests are failing, partly because the error prints _more_ than it used to 🤔

**Comment by gdalle** [comment]
Why was this merged despite breaking CI?

**Comment by vtjnash** [comment]
CI said it passed

**Comment by gdalle** [comment]
Okay, it seems that the buildkite failure is unrelated then
