### PR TITLE
Don't report only-inferred methods as recompiles

### LINKED ISSUE #56155: `--trace-compile` incorrectly reports only-inferred methods as being re-compiled
There are times (such as when inlining) when Julia will create a `CodeInstance` that has no code associated with it.

For example:
```julia
using Base.Filesystem: contractuser
mi = methods(contractuser, (String,))[1].specializations::Base.MethodInstance

println("world range: ", (mi.cache.min_world, mi.cache.max_world))
println("invoke, specptr: ", (mi.cache.invoke, mi.cache.specptr))
println("next?: ", (isdefined(mi.cache, :next)))

println(contractuser("")) # trigger compilation

println("world range: ", (mi.cache.min_world, mi.cache.max_world))
println("invoke, specptr: ", (mi.cache.invoke, mi.cache.specptr))
println("next?: ", (isdefined(mi.cache, :next)))
```

This outputs:
```julia
world range: (0x0000000000003f84, 0xffffffffffffffff)
invoke, specptr: (Ptr{Nothing}(0x0000000000000000), Ptr{Nothing}(0x0000000000000000))
next?: false

world range: (0x0000000000003f84, 0xffffffffffffffff)
invoke, specptr: (Ptr{Nothing}(0x00007f6f10b09680), Ptr{Nothing}(0x00007f6f10b09590))
next?: false
```
which shows that `contractuser(::String)` was never invalidated (and in fact only has one CodeInstance). It just never had any code associated with it because it was only inferred and then inlined.

However if you run with `--trace-compile=compile.log` you'll see:
```julia
...
precompile(Tuple{typeof(Base.Filesystem.contractuser), String}) # recompile
...
```

You can see we reported `precompile(Tuple{typeof(Base.Filesystem.contractuser), String}) # recompile`

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/56155

If I run the test in https://github.com/JuliaLang/julia/issues/56155#issue-2585792789 the `--trace-compile` output contains no `# recompile` at all, but specifically not for `contractuser`.

And the test added here ensures that it is actually catching a true recompilation.

### CODE REVIEW

File: src/gf.c [hunk 1]
```diff
@@ -2863,7 +2863,13 @@ jl_code_instance_t *jl_compile_method_internal(jl_method_instance_t *mi, size_t
...
     // Everything from here on is considered (user facing) compile time
     uint64_t start = jl_typeinf_timing_begin();
-    int is_recompile = jl_atomic_load_relaxed(&mi->cache) != NULL;
+
+    // Is a recompile if there is cached code, and it was compiled (not only inferred) before
+    int is_recompile = 0;
+    jl_code_instance_t *codeinst_old = jl_atomic_load_relaxed(&mi->cache);
+    if ((codeinst_old != NULL) && (jl_atomic_load_relaxed(&codeinst_old->invoke) != NULL)) {
+        is_recompile = 1;
+    }
```
Comment (vtjnash) [inline src/gf.c:2872]:
```suggestion
    while (codeinst_old != NULL) {
        if (jl_atomic_load_relaxed(&codeinst_old->invoke) != NULL) {
            is_recompile = 1;
            break;
        }
        codeinst_old = jl_atomic_load_relaxed(&codeinst_old->next);
    }
```

**Comment by KristofferC** [comment]
Needsa a manual backport
