### PR TITLE
Fix integer overflow in `skip(s::IOBuffer, typemax(Int64))`

### LINKED ISSUE #53908: Integer overflow in `skip(s::IOBuffer, typemax(Int64))` can cause seg fault
Here is a MWE:
```julia
julia> s = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> skip(s, typemax(Int64))
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=-9223372036854775808, mark=-1)

julia> position(s)
9223372036854775807

julia> read(s, UInt8)

[807576] signal 11 (128): Segmentation fault
in expression starting at REPL[10]:1
getindex at ./essentials.jl:375 [inlined]
read at ./iobuffer.jl:240
unknown function (ip: 0x775177259d32)
...
```

This happens on nightly as well as 1.10.2, both installed using juliaup.

```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.274
Commit a3f710e2a35 (2024-03-31 01:56 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
```

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #53908  by clamping before doing addition.

This also fixes an issue with negative skips if `io.offset` isn't zero.

I am assuming that `io.size+1` cannot overflow.

### CODE REVIEW

File: base/iobuffer.jl [hunk 1]
```diff
@@ -260,22 +260,27 @@ bytesavailable(io::GenericIOBuffer) = io.size - io.ptr + 1
 position(io::GenericIOBuffer) = io.ptr - io.offset - 1
 
 function skip(io::GenericIOBuffer, n::Integer)
-    seekto = io.ptr + n
```
Comment (Seelengrab) [inline base/iobuffer.jl:263]: I think it'd be better to replace this with `Base.Checked.add_with_overflow` and check the returned flag, rather than widen by default. That makes the intent of the code clearer. Then, if an overflow occurred, we can just return `io.size+1` (assuming it too doesn't overflow) and don't have to do any more wider arithmetic. If there is no overflow, the existing `min` call is still valid.

File: base/iobuffer.jl [hunk 2]
```diff
@@ -260,22 +260,29 @@ bytesavailable(io::GenericIOBuffer) = io.size - io.ptr + 1
...
-    io.ptr = min(seekto, io.size+1)
-    return io
+    skip(io, clamp(n, Int))
+end
+function skip(io::GenericIOBuffer, n::Int)
+    if signbit(n)
+        seekto = clamp(widen(position(io)) + widen(n), Int)
+        seek(io, seekto) # Does error checking
+    else
+        @assert io.ptr ≤ io.size + 1
```
Comment (Seelengrab) [inline base/iobuffer.jl:270]: Don't use `@assert` for hard requirements of correctness, as it's valid to be removed.

**Comment by Seelengrab** [comment]
Why not use `Base.Checked.add_with_overflow`?

**Comment by nhz2** [comment]
No real reason, I just find `widen` and `clamp` easier to understand.

File: base/iobuffer.jl (hunk 2 above)
Comment (nhz2) [reply base/iobuffer.jl:270]: It's ok for this assert to be removed. I can't see a case where it does anything.

Comment (nhz2) [inline base/iobuffer.jl:270]:
```suggestion
```

File: base/iobuffer.jl [hunk 3]
```diff
@@ -260,22 +260,28 @@ bytesavailable(io::GenericIOBuffer) = io.size - io.ptr + 1
...
+    seek(io, clamp(n, Int))
+end
+function seek(io::GenericIOBuffer, n::Int)
     if !io.seekable
         ismarked(io) || throw(ArgumentError("seek failed, IOBuffer is not seekable and is not marked"))
         n == io.mark || throw(ArgumentError("seek failed, IOBuffer is not seekable and n != mark"))
     end
-    # TODO: REPL.jl relies on the fact that this does not throw (by seeking past the beginning or end
-    #       of an GenericIOBuffer), so that would need to be fixed in order to throw an error here
-    #(n < 0 || n > io.size) && throw(ArgumentError("Attempted to seek outside IOBuffer boundaries."))
```
Comment (Seelengrab) [inline base/iobuffer.jl:276]: Why delete the TODO as well?

Comment (nhz2) [reply base/iobuffer.jl:276]: This TODO is very old, from https://github.com/JuliaLang/julia/pull/8238

At this point, I think it is too late to change this. 

Also, I think a new file or buffer interface shouldn't include a `seek` function. Ref: https://github.com/joyent/libuv/pull/664

Comment (Seelengrab) [reply base/iobuffer.jl:276]: Then the comment can be kept around for consideration in an eventual rework. If the REPL changes (or perhaps it already has and this was just forgotten), this too can be changed.

**Review by vtjnash — APPROVED** [review]

**Review by vtjnash — COMMENTED** [review]
IIUC, the main problem with `widen` is that it is less likely to be defined on arbitrary types and is more likely to fall back to slow BigInt math unnecessarily in other cases. But in this case, it is just `widen(::Int)::2Int`, so that is always fine.
