### PR TITLE
rational powers (fixes #18114)

### LINKED ISSUE #18114: Rational powers and coversion
There is something wrong with `Rational` powers:
```
julia> BigFloat(2)^(BigFloat(1)/BigFloat(3))-BigFloat(2)^(1//3)
1.615949454734010502584703185359054123712092705937300412204179527347802183365638e-17
```
where there shouldn't be any difference (`1//3` is of infinite precision).  The issue comes from the [definition](https://github.com/JuliaLang/julia/blob/master/base/rational.jl#L378-L379) of `^` for rationals, where convert is applied to the result of a division of two integers, which is basically a `Float64`, the result is then converted back to `BigFloat`
```julia
^{T<:AbstractFloat}(x::T, y::Rational) = x^(convert(T, y.num / y.den))
^{T<:AbstractFloat}(x::Complex{T}, y::Rational) = x^(convert(T, y.num / y.den))
```

Redefining `^` like this
```julia
^{T<:AbstractFloat}(x::T, y::Rational) = x^(convert(T, y.num) / convert(T, y.den))
^{T<:AbstractFloat}(x::Complex{T}, y::Rational) = x^(convert(T, y.num) / convert(T, y.den))
```
fixes the problem:
```
julia> BigFloat(2)^(BigFloat(1)/BigFloat(3))-BigFloat(2)^(1//3)
0.000000000000000000000000000000000000000000000000000000000000000000000000000000
```

In summary, `convert` doesn't commute with division (nor with other similar operations) and `convert` should be applied as early as possible (directly to the integers in this case) to avoid precision loss.  There might be more cases like this that I am not aware of.

EDIT: This bug is new in 0.5 and it was introduced in #17530.

### PR DESCRIPTION
**Pull request by pwl**
Fixes #18114

### CODE REVIEW

File: test/numbers.jl [hunk 1]
```diff
@@ -2137,7 +2137,8 @@ rationalize(nextfloat(0.0)) == 0//1
 # rational-exponent promotion rules (issue #3155):
 @test 2.0f0^(1//3) == 2.0f0^(1.0f0/3)
 @test 2^(1//3) == 2^(1/3)
-
+# no loss of precision for rational powers (issue #18114)
+@test_approx_eq_eps BigFloat(2)^(BigFloat(1)/BigFloat(3)) BigFloat(2)^(1//3) 1e-20
```
Comment (stevengj) [inline test/numbers.jl]: Cleaner to do `@test BigFloat(2)^(BigFloat(1)/BigFloat(3)) ≈ BigFloat(2)^(1//3)` ... this will test to sqrt(eps) precision by default, about 4e-39.

Comment (pwl) [inline test/numbers.jl]: I think even `==` should work in this case.

File: base/rational.jl [hunk 2]
```diff
@@ -375,8 +375,8 @@ function ^(x::Rational, n::Integer)
 end
 
 ^(x::Number, y::Rational) = x^(y.num/y.den)
-^{T<:AbstractFloat}(x::T, y::Rational) = x^(convert(T, y.num / y.den))
-^{T<:AbstractFloat}(x::Complex{T}, y::Rational) = x^(convert(T, y.num / y.den))
+^{T<:AbstractFloat}(x::T, y::Rational) = x^(convert(T,y.num)/convert(T,y.den))
+^{T<:AbstractFloat}(x::Complex{T}, y::Rational) = x^(convert(T,y.num)/convert(T,y.den))
```
Comment (simonbyrne) [inline base/rational.jl]: You could probably simplify these to `x^convert(T,y)`

File: test/numbers.jl [hunk 3]
```diff
@@ -2137,7 +2137,8 @@ rationalize(nextfloat(0.0)) == 0//1
 # rational-exponent promotion rules (issue #3155):
 @test 2.0f0^(1//3) == 2.0f0^(1.0f0/3)
 @test 2^(1//3) == 2^(1/3)
-
+# no loss of precision for rational powers (issue #18114)
+@test BigFloat(2)^(BigFloat(1)/BigFloat(3)) == BigFloat(2)^(1//3)
```
Comment (simonbyrne) [inline test/numbers.jl]: Not a big deal, but you can use `cbrt(BigFloat(2))` on the left-hand side

Comment (stevengj) [inline test/numbers.jl]: Not if we want to guarantee exact equality.

File: base/rational.jl (hunk 2 above)
Comment (pwl) [inline base/rational.jl]: My thinking here was that there is a higher chance to have a conversion from `Int` then from `Rational`.  But if you think it's ok to have `x^convert(T,y)` I can change it.

Comment (stevengj) [inline base/rational.jl]: `convert(T,y)` is safe, because there is a [generic conversion from Rational to AbstractFloat](https://github.com/JuliaLang/julia/blob/adecd7323455f09462588667e225b6467099e6a1/base/rational.jl#L71-L74).

Comment (simonbyrne) [inline base/rational.jl]: It will dispatch to this method:
https://github.com/JuliaLang/julia/blob/b50604121db9cc6a7b1294ca040fc9a715c00359/base/rational.jl#L71-L74
which actually will be better, as it will handle, e.g. `^(x::Float64, y::Rational{BigInt})` by promoting to `BigFloat`.

File: test/numbers.jl (hunk 3 above)
Comment (simonbyrne) [inline test/numbers.jl]: It already does for BigFloat, which calls `mpfr_cbrt`.

File: base/rational.jl (hunk 2 above)
Comment (pwl) [inline base/rational.jl]: Maybe I don't see the whole picture, but why is there even a specialization for `AbstractFloat` at all?  Can't this case be treated by `^(x::Number, y::Number) = ^(promote(x,y)...)`?

Comment (stevengj) [inline base/rational.jl]: No, because then it will call `^(x::Number, y::Rational)` instead.  (Remember, Julia always calls the most specific method.)

**Comment by simonbyrne** [comment]
Thanks!
