### PR TITLE
fix rawbigints

### LINKED ISSUE #51111: Segmentation fault during native BigFloat to Float32 conversion
MWE:

`Foo.jl`
```julia
module Foo
bar() = convert(Float32, big"1.582533518939116418785258993332844897062")
end
```

```
$ JULIA_LOAD_PATH=. julia -e 'using Foo; Foo.bar()'
[1054346] signal (11.1): Segmentation fault
in expression starting at none:1
unsafe_load at ./pointer.jl:119 [inlined]
get_elem at ./rawbigints.jl:30 [inlined]
get_elem at ./rawbigints.jl:35 [inlined]
truncated at ./rawbigints.jl:115
to_ieee754 at ./mpfr.jl:441
Float32 at ./mpfr.jl:468 [inlined]
Float32 at ./mpfr.jl:468 [inlined]
convert at ./number.jl:7 [inlined]
bar at /home/tim/Julia/tools/creduce/Foo.jl:2
unknown function (ip: 0x7fd567700102)
_jl_invoke at /home/tim/Julia/src/julia/src/gf.c:2873 [inlined]
ijl_apply_generic at /home/tim/Julia/src/julia/src/gf.c:3074
jl_apply at /home/tim/Julia/src/julia/src/julia.h:1970 [inlined]
do_call at /home/tim/Julia/src/julia/src/interpreter.c:125
eval_value at /home/tim/Julia/src/julia/src/interpreter.c:222
eval_stmt_value at /home/tim/Julia/src/julia/src/interpreter.c:173 [inlined]
eval_body at /home/tim/Julia/src/julia/src/interpreter.c:634
jl_interpret_toplevel_thunk at /home/tim/Julia/src/julia/src/interpreter.c:774
jl_toplevel_eval_flex at /home/tim/Julia/src/julia/src/toplevel.c:934
jl_toplevel_eval_flex at /home/tim/Julia/src/julia/src/toplevel.c:877
jl_toplevel_eval_flex at /home/tim/Julia/src/julia/src/toplevel.c:877
ijl_toplevel_eval_in at /home/tim/Julia/src/julia/src/toplevel.c:985
eval at ./boot.jl:383 [inlined]
exec_options at ./client.jl:290
_start at ./client.jl:552
jfptr__start_83124 at /home/tim/Julia/src/julia/build/dev/usr/lib/julia/sys.so (unknown line)
_jl_invoke at /home/tim/Julia/src/julia/src/gf.c:2873 [inlined]
ijl_apply_generic at /home/tim/Julia/src/julia/src/gf.c:3074
jl_apply at /home/tim/Julia/src/julia/src/julia.h:1970 [inlined]
true_main at /home/tim/Julia/src/julia/src/jlapi.c:582
jl_repl_entrypoint at /home/tim/Julia/src/julia/src/jlapi.c:731
main at /home/tim/Julia/src/julia/cli/loader_exe.c:58
unknown function (ip: 0x7fd568027ccf)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
_start at /home/tim/Julia/src/julia/build/dev/julia (unknown line)
Allocations: 2927 (Pool: 2918; Big: 9); GC: 0
```

Bisected to #50691, cc @nsajko.

This affects a couple of packages on PkgEval, e.g., https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-08/29/Modia.primary.log, https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-08/29/StochasticRounding.primary.log, https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-08/29/PostNewtonian.primary.log, https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-08/29/SummationByPartsOperators.primary.log

### PR DESCRIPTION
**Pull request by nsajko**
Using `Ptr` like that was incorrect. Among other issues, a `Ptr` doesn't own the data it points to, so hold a `String` instead.

Fixes #51111

### CODE REVIEW

**Comment by nsajko** [comment]
There's significant performance degradation for `Float64` in particular, so I'll add some `@inbounds`.

**Comment by nsajko** [comment]
Ended up removing the boundschecking altogether. It seemed simpler than sprinkling `@inbounds` all over, and the lack of bounds checking for rawbigints didn't seem to cause any bugs anyway.

File: base/rawbigints.jl [hunk 1]
```diff
@@ -26,8 +25,9 @@ split_bit_index(x::RawBigInt, i::Int) = divrem(i, word_length(x), RoundToZero)
 `i` is the zero-based index of the wanted word in `x`, starting from
 the less significant words.
 """
-function get_elem(x::RawBigInt, i::Int, ::Val{:words}, ::Val{:ascending})
-    unsafe_load(x.d, i + 1)
+function get_elem(x::RawBigInt{T}, i::Int, ::Val{:words}, ::Val{:ascending}) where {T}
+    # `i` must be nonnegative and less than `x.word_count`
+    unsafe_load(Ptr{T}(pointer(x.d)), i + 1)::T
```
Comment (KristofferC) [inline base/rawbigints.jl:30]: Need a `GC.@preserve` on `x.d` here?

**Comment by nsajko** [comment]
Regarding the `needs tests` label, my current minimal reproducer for #51111 is:
```julia
using StochasticRounding, OrdinaryDiffEq
const SR = Float32sr
OrdinaryDiffEq.Tsit5ConstantCacheActual(SR, SR)
```

To make it amenable for inclusion into Julia's test suite, it would be necessary to get rid of the two package dependencies. This seems like it would be quite time consuming, while risking ending up with a huge reproducer in the end.

I tried to remove the dependency on `OrdinaryDiffEq`, with minimal changes, and ended up with a non-reproducer in the process. So what I'm trying to say is, this is (I guess so, at least) a difficult-to-reproduce heisenbug caused by undefined behavior, is it really worth it trying to add a test here?

File: base/rawbigints.jl (hunk 1 above)
Comment (nsajko) [reply base/rawbigints.jl:30]: Ah, OK, thank you. I guess I assumed it's not necessary in such a short one-liner.

**Comment by maleadt** [comment]
> Regarding the `needs tests` label, my current minimal reproducer for #51111 is:
> 
> ```julia
> using StochasticRounding, OrdinaryDiffEq
> const SR = Float32sr
> OrdinaryDiffEq.Tsit5ConstantCacheActual(SR, SR)
> ```

Why not the MWE I reduced it to? There's a couple of tests that require separate packages already, so you could mimic what they do.

**Review by vtjnash — COMMENTED** [review]
LGTM. There should be similar tests in precompile. There is already a `abigfloat_x` value, it looks like you just need to add some code to exercise this path (whereas currently it only tests addition).

**Comment by nsajko** [comment]
Added the test based on the MWE by @maleadt to the location suggested by @vtjnash. Thanks.

> Why not the MWE I reduced it to?

I misunderstood your MWE back then and thought I couldn't reproduce the issue using it.
