### PR TITLE
Fix fptrunc Float64 -> Float16 rounding through Float32

### LINKED ISSUE #57805: Float16 runtime and compiler intrinsics models do not match
```
julia> f() = Base.fptrunc(Base.Float16, -2.980232238769532e-8)
f (generic function with 1 method)

julia> f()
Float16(-0.0)

julia> f(x) = Base.fptrunc(Base.Float16, x)
f (generic function with 2 methods)

julia> f(-2.980232238769532e-8)
Float16(-6.0e-8)
```

### PR DESCRIPTION
**Pull request by xal-0**
Widening from Float32 to Float64 and then rounding to Float16 will not introduce any error, but going from Float64 -> Float32 -> Float16 will round incorrectly if the intermediate Float32 is halfway between two Float16s.

Fixes #57805.

Thanks to @vtjnash for suggesting the fix.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

File: src/runtime_intrinsics.c [hunk 1]
```diff
@@ -1629,8 +1629,8 @@ cvt_iintrinsic(LLVMFPtoUI, fptoui)
 #define fintrinsic_read_float32(p)   *(float *)p
 #define fintrinsic_read_float64(p)   *(double *)p
 
-#define fintrinsic_write_float16(p, x)  *(uint16_t *)p = float_to_half(x)
-#define fintrinsic_write_bfloat16(p, x) *(uint16_t *)p = float_to_bfloat(x)
+#define fintrinsic_write_float16(p, x)  *(uint16_t *)p = double_to_half(x)
+#define fintrinsic_write_bfloat16(p, x) *(uint16_t *)p = double_to_bfloat(x)
```
Comment (Keno) [inline src/runtime_intrinsics.c:1633]: I don't think the same logic applies to bfloat16. Since bfloat16 is just a truncated float32, shouldn't it always be legal to go through Float32? If not, it'd be good to have a test.

Comment (vtjnash) [reply src/runtime_intrinsics.c:1633]: According to the double_to_bfloat code, the same correction to the rounding direction is required whenever the float32 (after truncation from float64) is exactly halfway between 2 bfloat16 values, but wasn't required for the subnormal case (as was demonstrated in the original issue for float16)
