### PR TITLE
Fix multiversioning issues caused by the parallel llvm work

### LINKED ISSUE #52079: `Base.two_mul` is constant folding incorrectly on 1.10 (but not 1.9 or 1.11)
It's useful for something: https://cds.cern.ch/record/2866130/files/ANA-EXOT-2022-18-PAPER.pdf#page=9

(this is a fitting, so you want this exponential to be very fast)

```julia
julia> @benchmark x^y setup=begin x=rand(); y=rand()end
BenchmarkTools.Trial: 10000 samples with 988 evaluations.
 Range (min … max):  47.248 ns … 440.931 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     47.567 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   49.616 ns ±   4.787 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▅█▇▁     ▂▁       ▁▁▁                ▆▇▄       ▁             ▂
  ████▁▃▄▁▇██▇▇▆▆▆▆▇███▇▇▆▆▆▆▆▅▇▆▆▆▆▆▆█████▇▇▇▇▇███▆▆▆▅▅▆▅▇▇█▇ █
  47.2 ns       Histogram: log(frequency) by time      55.5 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark x^y setup=begin x=rand(); y=rand(3:9)end
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  2.408 ns … 20.031 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     9.003 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   8.631 ns ±  2.849 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▇                           ▇       █     █   ▂
  █▃▂▂▂▂▂▁▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▂█▂▂▁▃▂▇▄█▇▂▂▂▃█▆▂▂█▃▃▇▂▇▆▂▂▂▂▂ ▃
  2.41 ns        Histogram: frequency by time        12.7 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

## Maybe we're hitting the physical limit of how fast this can go?
```python
In [2]: a=np.random.rand(100);

In [3]: b=np.random.rand(100);

In [5]: %timeit np.power(a,b)
514 ns ± 3.64 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

### PR DESCRIPTION
**Pull request by gbaraldi**
So after struggling with this for a long while it seems there were two different issues. The first one we lacked coverage over, but the other was a very subtle issue when we sorted the fptrs.

~I still need to add test that does multiversioning where we call between multiversioned functions~

Fixes https://github.com/JuliaLang/julia/issues/52079

### CODE REVIEW

File: test/compiler/codegen.jl [hunk 1]
```diff
@@ -860,3 +860,16 @@ foo50964(1) # Shouldn't assert!
 # https://github.com/JuliaLang/julia/issues/51233
 obj51233 = (1,)
 @test_throws ErrorException obj51233.x
+
+# Very specific test for multiversioning
+if Sys.ARCH === :x86_64
+    foo52079() = Core.Intrinsics.have_fma(Float64)
+    if foo52079() == true
```
Comment (oscardssmith) [inline test/compiler/codegen.jl:867]: would this test have caught the issue? I thought we were miscompiling `have_fma` also.

Comment (gbaraldi) [reply test/compiler/codegen.jl:867]: Yes (this test fails in 1.10/master), `code_native` tends to lie. but `code_native(...dump_module=false)` doesn't lie too much since it just gets whateve the JIT has.

Comment (gbaraldi) [reply test/compiler/codegen.jl:867]: We weren't miscompiling. We were just not multiversioning as we should.

Comment (vtjnash) [reply test/compiler/codegen.jl:867]: IIRC, it is considered a miscompilation in this case, since we defined that `have_fma` is not permitted to disagree with itself within any given run of the program (e.g. what happened in #52079).

Comment (gbaraldi) [reply test/compiler/codegen.jl:867]: Doesn't it always do that? (if we are interpreting it returns false) i.e
```julia
julia> Core.Intrinsics.have_fma(Float64)
false

julia> foo() = Core.Intrinsics.have_fma(Float64)
foo (generic function with 2 methods)

julia> foo()
true
```

Comment (vtjnash) [reply test/compiler/codegen.jl:867]: Uh oh. That seems very bad

Comment (oscardssmith) [reply test/compiler/codegen.jl:867]: I believe we intentionally made it return false from the global scope (but I forget why)

Comment (vtjnash) [reply test/compiler/codegen.jl:867]: Hm, seems like it was a known bug in the initial PR that was not fixed before merging https://github.com/JuliaLang/julia/pull/43085#discussion_r758714415

Comment (Keno) [reply test/compiler/codegen.jl:867]: I don't think there's anything semantically wrong with have_fma returning different values, but it is certainly undesirable.

Comment (gbaraldi) [reply test/compiler/codegen.jl:867]: In any case I opened https://github.com/JuliaLang/julia/pull/52206

**Comment by oscardssmith** [comment]
Is this ready to merge?
