### PR TITLE
Make the memory GEP an inbounds GEP since the bounds check has happened somewhere else

### LINKED ISSUE #55090: 2x regression in indexing benchmarks due to 'Remove references to non opaque pointers in codegen and LLVM passes (#54853)'
Through bisection I identified 5e1bcdf9ff42ca17a995ce7bc7ef7fc30ce81d78 as causing the regressions below. This change also led to some improvements but caused many more regressions. I believe these two commits were my more minimal version of the identified commit, so would be good to test if they also cause the regression, https://github.com/JuliaLang/julia/commit/4eef1be617fb6b89a79ea516212a9d27af4e82a5 https://github.com/JuliaLang/julia/commit/756e72ff93aee37e915877ac3e7122a854e2c327.

A subset of the results is below, for full results see https://tealquaternion.camdvr.org/compare.html?start=a14cc38512b6daab6b8417ebb8a64fc794ff89cc&end=323e725c1e4848414b5642b8f54c24916b9ddd9e&stat=min-wall-time or https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_date/2024-07/05/report.md.

# Summary
| | Range | Mean | Count |
|:---:|:---:|:---:|:---:|
| Regressions | 0.52%, 207.23% | 27.72% | 129 |
| Improvements | -47.24%, -0.17% | -14.31% | 22 |
| All | -47.24%, 207.23% | 21.60% | 151 |

# Benchmarks
| Benchmark | % Change | Significance Factor |
|:---:|:---:|:---:|
| array.index.(sumrange_view, SubArray{Int32, 2, Base.ReshapedArray{Int32, 2, SubArray{Int32, 3, Array{Int32, 3}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}) | 207.23% | 54.86x
| array.index.(sumcolon_view, SubArray{Int32, 2, Base.ReshapedArray{Int32, 2, SubArray{Int32, 3, Array{Int32, 3}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}) | 205.96% | 54.63x
| array.index.(sumeach_view, SubArray{Int32, 2, Array{Int32, 3}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, true}) | 159.39% | 203.84x
| array.index.(sumlinear, SubArray{Int32, 2, Array{Int32, 3}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, true}) | 159.14% | 244.42x
| array.index.(sumeach, SubArray{Int32, 2, Array{Int32, 3}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, true}) | 159.02% | 451.23x

### PR DESCRIPTION
**Pull request by gbaraldi**
This makes the code in https://github.com/JuliaLang/julia/issues/55090 look almost the same as it did before the change. Locally I wasn't able to reproduce the regression, but given it's vectorized code I suspect it is backend sensitive.
@Zentrik 

Fixes https://github.com/JuliaLang/julia/issues/55090

### CODE REVIEW

**Comment by Zentrik** [comment]
@nanosoldier `runbenchmarks("sparse" || "array", vs=":master")`

File: src/cgutils.cpp [hunk 1]
```diff
@@ -4262,9 +4262,8 @@ static jl_cgval_t emit_memoryref(jl_codectx_t &ctx, const jl_cgval_t &ref, jl_cg
             ovflw = ctx.builder.CreateICmpUGE(ctx.builder.CreateAdd(offset, mlen), ctx.builder.CreateNUWAdd(mlen, mlen));
         }
 #endif
-        //Is this change fine
         boffset = ctx.builder.CreateMul(offset, elsz);
-        newdata = ctx.builder.CreateGEP(getInt8Ty(ctx.builder.getContext()), data, boffset);
+        newdata = ctx.builder.CreateInboundsGEP(getInt8Ty(ctx.builder.getContext()), data, boffset);
```
Comment (Zentrik) [inline src/cgutils.cpp:4266]:
```suggestion
        newdata = ctx.builder.CreateInBoundsGEP(getInt8Ty(ctx.builder.getContext()), data, boffset);
```

**Comment by Zentrik** [comment]
Could someone trigger nanosoldier on this, I don't seem to have perms. Thanks

**Comment by vtjnash** [comment]
You have permission unless you haven't made your membership in JuliaLang public

**Comment by Zentrik** [comment]
@nanosoldier `runbenchmarks("sparse" || "array", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55107#issuecomment-2226849234) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/38f0bd9_vs_0fd1f04/report.md).

**Comment by Zentrik** [comment]
The regression still exists on nanosoldier and locally and this doesn't seem to have made much difference to performance. The optimized ir is essentially unchanged compared to master apart from some inbounds sprinkled on some geps. The only difference in the unoptimized ir with the fast version is `i8`s are used instead of `i32`s.
