### PR TITLE
Make `Matrix` cntr work for structured matrices for `zero(T) !isa T`

### LINKED ISSUE #2930: Tests are broken on nightly
Here's the problem: https://github.com/JuliaLang/julia/pull/44615#issuecomment-1075811641

### PR DESCRIPTION
**Pull request by dkarrasch**
This fixes https://github.com/JuliaLang/julia/pull/44615#issuecomment-1075811641. At the same time, it extends the `Matrix` constructors to other structured matrices whose eltype `T` has the property `!isa(zero(T), T)`. Before https://github.com/JuliaLang/julia/pull/44615, `Matrix(::Diagonal)` was defined in terms of `diagm`, which handled the eltype promotion correctly. `Matrix(::BiTriSym)`, however, was defined manually without correctly handling type promotion.

Fixes https://github.com/jump-dev/JuMP.jl/issues/2930.

### CODE REVIEW

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["JuMP"], vs = ":master")`

File: stdlib/LinearAlgebra/src/dense.jl [hunk 1]
```diff
@@ -257,6 +257,8 @@ Vector `kv.second` will be placed on the `kv.first` diagonal.
 By default the matrix is square and its size is inferred
 from `kv`, but a non-square size `m`×`n` (padded with zeros as needed)
 can be specified by passing `m,n` as the first arguments.
+For repeated diagonal indices `kv.first` the values in the corresponding
```
Comment (jishnub) [inline stdlib/LinearAlgebra/src/dense.jl:260]: Just out of curiousity, why this behavior?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/dense.jl:260]: I guess to be consistent with how the `sparse(I, J, V)` works by default. Otherwise the order in which you supply the diagonal values starts to matter.

**Comment by blegat** [comment]
Thanks! You can find here a list of assumptions commonly made and types for which it doesn't hold: https://github.com/jump-dev/MutableArithmetics.jl/issues/47

**Comment by dkarrasch** [comment]
Aha, I realize you made a more complete proposal in #36256. Currently, none of the `Matrix` methods touched here works for eltypes `T` that don't have `zero(T)` defined. So this PR here fixes the issue, and puts `BiTriSym` to the same level as `Diagonal`. So shall we take this one and continue the discussion in #36256? Or should I cut down a bit and make the fix only for `Diagonal`?

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44707#issuecomment-1076138333) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/eb9a80e_vs_d655402/report.html).

**Comment by blegat** [comment]
> shall we take this one and continue the discussion in #36256? Or should I cut down a bit and make the fix only for `Diagonal`?

Please leave this one as it is. I'll happily rebase #36256 once this one is merged.

File: stdlib/LinearAlgebra/test/special.jl [hunk 2]
```diff
@@ -104,6 +104,29 @@ Random.seed!(1)
...
+        d  = fill(TypeWithoutZero(), 3)
+        du = fill(TypeWithoutZero(), 2)
+        dl = fill(TypeWithoutZero(), 2)
+        D  = Diagonal(d)
+        Bu = Bidiagonal(d, du, :U)
+        Bl = Bidiagonal(d, dl, :L)
+        Tri = Tridiagonal(dl, d, du)
+        Sym = SymTridiagonal(d, dl)
+        for M in (D, Bu, Bl, Tri, Sym)
+            @show typeof(M)
```
Comment (odow) [inline stdlib/LinearAlgebra/test/special.jl:126]:
```suggestion
```

**Review by odow — APPROVED** [review]
