### PR TITLE
RFC: bring back v0.6 scope rules in the REPL

### LINKED ISSUE #28789: Global variable scope rules lead to unintuitive behavior at the REPL/notebook
### Example 1

This came up with a student who upgraded from 0.6 to 1.0 directly, so never even got a chance to see a deprecation warning, let alone find an explanation for new behavior:

```julia
julia> beforefor = true
true

julia> for i in 1:2
         beforefor = false
       end

julia> beforefor  # this is surprising bit
true

julia> beforeif = true
true

julia> if 1 == 1
         beforeif = false
       end
false

julia> beforeif  # Another surprise!
false

julia> function foo()
         infunc = true
         for i in 1:10
           infunc = false
         end
         @show infunc
       end
foo (generic function with 1 method)

julia> foo()  # "I don't get this"
infunc = false 
```

### Example 2

```julia
julia> total_lines = 0
0

julia> list_of_files = ["a", "b", "c"]
3-element Array{String,1}:
 "a"
 "b"
 "c"

julia> for file in list_of_files
         # fake read file
         lines_in_file = 5
         total_lines += lines_in_file
       end
ERROR: UndefVarError: total_lines not defined
Stacktrace:
 [1] top-level scope at ./REPL[3]:4 [inlined]
 [2] top-level scope at ./none:0

julia> total_lines  # This crushs the students willingness to learn
0
```

I "get" why this happens in the sense that I think I can explain, with sufficient reference to the arcana in the manual about what introduces scopes and what doesn't, but I think that this is problematic for interactive use.

In example one, you get a silent failure. In example two, you get an error message that is very there-is-no-spoon. Thats roughly comparable to some Python code I wrote in a notebook at work today.

I'm not sure what the rules are in Python, but I do know that generally you can't assign to things at the global scope without invoking global. But at the REPL it does work, presumably because at the REPL the rules are different or the same logic as if they were all are in the scope of function is applied.

I can't language-lawyer the rules enough to propose the concrete change I would like, and based on Slack this isn't even necessarily perceived as an issue by some people, so I don't know where to go with this except to flag it.

Cross-refs:
#19324
https://discourse.julialang.org/t/repl-and-for-loops-scope-behavior-change/13514
https://stackoverflow.com/questions/51930537/scope-of-variables-in-julia

### PR DESCRIPTION
**Pull request by JeffBezanson**
After thinking about it off and on for quite a while, @StefanKarpinski and I more-or-less decided that the best way to change the REPL scope situation (if at all) is just to bring back what v0.6 did. That's what SoftGlobalScope and IJulia already do (albeit somewhat approximately; implementing it internally it's much easier to get it 100%), and seems less disruptive than introducing a *third* behavior.

This needs to be finished up but is ready to try. Please give it a whirl.

I'm not sure what the best interface to it is; it seemed easiest just to drop a special expression in the AST itself.

fixes #28789

### CODE REVIEW

**Comment by andyferris** [comment]
I couldn’t tell from the OP - does this affect the top level scoping rules in general, or just code typed into the REPL?

**Comment by ronisbr** [comment]
Wouldn't it break code that was assuming that a variable on the global scope was not being modified in local scope when running in REPL?

Like, today we have:

```julia
julia> aux = 1
1

julia> for i = 1:10
       aux = i
       end

julia> aux
1
```

The behavior in v0.6 would lead to `aux = 10` right? Is it possible to at least print a warning? Anyway, this should be minor since AFAICT this PR does not change the behavior inside functions.

Just to make it clear, I always preferred the solution in v0.6.

**Comment by JeffBezanson** [comment]
> does this affect the top level scoping rules in general, or just code typed into the REPL

Just the repl. Any top-level expression can opt-in to it by including a `:softscope` expr, but this change only does that for the repl.


> Wouldn't it break code that was assuming that a variable on the global scope was not being modified in local scope when running in REPL?

I'm not sure how code could assume that. It's always been possible to modify globals from the REPL; I don't see how code could be OK with modifying a global in the REPL, *but not* if that modification happens inside a for loop. It does break possible workflows though, which is maybe what you mean; e.g. if you're used to pasting loops into the repl and them not having global effects.

**Comment by andyferris** [comment]
> and seems less disruptive than introducing a *third* behavior.

> Just the repl. Any top-level expression can opt-in to it by including a :softscope expr, but this change only does that for the repl.

So... is what you're saying is there will be three behaviours in Julia 1.x? One for scripts, one for the REPL and one for inside functions? (And how will people learn to write scripts if they are not exposed to the same rules at the REPL?)

(On the other hand, changing scoping rules at toplevel in general could potentially break what I'd call "production scripts" and the breakage wouldn't be detectable from open-source packages, so I'm not sure what else you could do in Julia 1.x?)

**Comment by StefanKarpinski** [comment]
Inside functions and in scripts aren’t different, so that’s two.

**Comment by jlperla** [comment]
Spectacular!  Any hope for a top-level script solution that is easy for beginners?  To be honest, I think the majority of issues occur when beginners move from jupyter to `.jl` with Juno, or people copy code from the inside of a function to a top-level script in the process of testing.  I haven't seen writing `for` loops in a REPL.

The other worry is that I thought a lot of the UIs (both Juno or vscode)? work by shift-entering code from the `.jl` file and executes within the REPL.  Which would mean that executing a script line-by-line would have a different behavior than running it all at once?

> (On the other hand, changing scoping rules at toplevel in general could potentially break what I'd call "production scripts" and the breakage wouldn't be detectable from open-source packages, so I'm not sure what else you could do in Julia 1.x?)

I suspect this is true... But if there was a function we could call a function toplevel to `:softscope` at the top of the script?  Or perhaps a command-line option?  Later you could decide if it made sense to make it the default in a 2.0?

**Comment by JeffBezanson** [comment]
> I haven't seen writing `for` loops in a REPL.

What?? I thought that's what this was largely about, and for example why IJulia started using SoftGlobalScope.jl.

**Comment by JeffBezanson** [comment]
It should be easy to add an option (with whatever default) to Juno to use this for shift-enter. It would also be possible to add `@softscope` in a script to change the behavior for that file. But that starts to worry me. I find this scope behavior convenient for running excerpts/snippets of code, which is what a REPL and shift-enter are for. But as soon as you have a whole program, you should really use functions. Juno also has an actual debugger now.

**Comment by JeffBezanson** [comment]
Also I know @stevengj and @aviks at least have often mentioned wanting this in the REPL.

**Comment by jlperla** [comment]
@JeffBezanson  First of all, thanks again for considering this.  I know what a pain this (and me!) has been.  To me at least, it has always been about "scripts" rather than the REPL.  But considering the connection between the two in the tooling, it might be hard to separate them and have different behavior.

To explain why the soft-scoping of scripts is intuitive, take a look at https://discourse.julialang.org/t/tips-to-cope-with-scoping-rules-of-top-level-for-loops-etc/24902/4  and https://discourse.julialang.org/t/tips-to-cope-with-scoping-rules-of-top-level-for-loops-etc/24902/12

But the basic issue is the intuition of people writing scripts don't think of the "global variables" as being globals unless they intended to be accessed from somewhere outside the top level script.  Since that isn't possible in Julia (and I am not sure it should be), soft-scope makes things comparable to matlab/R/python and all other scripting languages that seem to have that behavior.  (Note that in matlab, a "true" global (i.e. not just local to the script) needs to be declared, https://www.mathworks.com/help/matlab/ref/global.html ).

> What?? I thought that's what this was largely about, and for example why IJulia started using SoftGlobalScope.jl.

@stevengj can correct me, but my guess is that the goal was to make scripting (i.e. top level code where the intuitive scoping level is the "script") intuitive moreso than making jupyter match the old REPL.

> It would also be possible to add @softscope in a script to change the behavior for that file. But that starts to worry me. I find this scope behavior convenient for running excerpts/snippets of code, which is what a REPL and shift-enter are for. But as soon as you have a whole program, you should really use functions. Juno also has an actual debugger now.

Given your use of the word "program" rather than "script", I would agree with you.

I think that a lot of serious developers think of them as synonymous, but for many beginning (often permanently) programmers and scientists, a script patching together other people's serious packages is where they would stop.  There is enough evidence that people like scripts (e.g. Jupyter is effectively a literate environment for scripting) that I don't think it should be discouraged through language features.  We could educate them on the downsides separately, but scripts have their place.

With all of that said, I realize that "script" has no direct meaning in Julia and a `.jl` file is just an approximation.. but it is the best we have outside of jupyter.

**Comment by JeffBezanson** [comment]
> my guess is that the goal was to make scripting (i.e. top level code where the intuitive scoping level is the "script") intuitive moreso than making jupyter match the old REPL.
> 

Why does IJulia use it then? I see IJulia as primarily interactive.

But to be clear, the main problem here is that changing how scope works in e.g. `./julia x.jl` (or `include`, or loading packages) would be breaking and we can't do it.

One thing that comes to mind is that we have  "stream REPL" that gets used when you redirect a file to julia (as opposed to passing it on the command line like `julia x.jl`). Soft scope is not yet hooked up to that in this PR, but it could be. Then you'd at least get soft scope for `julia < x.jl`. We might be able to get away with that since it's an unusual way to run code.

**Comment by jlperla** [comment]
> Why does IJulia use it then? I see IJulia as primarily interactive.

Because Juno and vscode are awesome, and jupyter is frequently infuriating!

I think that of scripting as being a superset of interactive.  Many people (e.g. me!) would love to use Juno, Weave, etc. more for scripts where we can actually track git changes and use a proper IDE.  It is how people write R, python, matlab, etc. scripts largely.

You may not have intended for the `.jl` without a module to be a top-level script, but people have come to that conclusion (and in the absence of any alternative "script" outside of jupyter, the conclusion is understandable).

> But to be clear, the main problem here is that changing how scope works in e.g. ./julia x.jl (or include, or loading packages) would be breaking and we can't do it.

Yeah...  Would it be breaking if there was a global setting users can tweak as an environment variable?  Then in a v2.0 you could decide whether having that behavior the default (or only) scoping makes sense?

I think that it would be easy to teach intro users to setup an environment variable before using Juno and then serious programmers wouldn't need to worry about it.

> One thing that comes to mind is that we have a "stream REPL"

I fear that would end up more confusing for beginners.  My feeling is that the changes in global scope should be either (optionally) consistent across all "top level" scripting/interactive environments, or that we are better off waiting for a v2.0 to give the opportunity to break things.

**Comment by JeffBezanson** [comment]
> You may not have intended for the `.jl` without a module to be a top-level script, but people have come to that conclusion

During development and debugging, many of us (me included!) find soft scope more convenient. I agree it's what you want for ad-hoc loops in the REPL (which I certainly use), and for pasting code from functions (which is still useful sometimes in spite of a better debugger existing).

But my view is that as soon as you have any sort of coherent program that you might want to run repeatedly e.g. on new data, you should put code in functions. If all your code is loops at the top level, it will be slow anyway and there is much less reason to use julia at all. I just don't think you can design how scope works in a language based on what people seem to want in the first week. I also fail to understand the extreme resistance to writing functions. Not only is it not onerous, everybody agrees it is how you should do things anyway, so why not tell people about it? Setting environment variables and whatnot (giving disparate behavior in different people's environments) is preferable to just writing a function?

I don't like environment variables for this, since it makes it difficult to share code. Though it may be ugly, putting an annotation in the file is far better since it makes the code self-contained.

**Comment by jlperla** [comment]
> I don't like environment variables for this, since it makes it difficult to share code. Though it may be ugly, putting an annotation in the file is far better since it makes the code self-contained.

I agree with both.  Then if they shift-enter in Juno it uses the REPL scoping (even if they forget to shift-enter the ugly annotation)- while if they run the whole script in CI/etc. then it always runs the ugly thing at the the top.  Reproducible, and in v2 you could decide if you want the annotation call the default.

> But my view is that as soon as you have any sort of coherent program that you might want to run repeatedly e.g. on new data, you should put code in functions. If all your code is loops at the top level, it will be slow anyway and there is much less reason to use julia at all.

It depends when things move between a simple script and a program.  But with a rich package ecosystem, you can get a lot done in Julia with shockingly little code.  Regardless, my feeling is that the top-level should be as convenient as possible and that teaching people to organize as functions is worthwhile but orthogonal.

Also, I am not sure that  speed is always a worry since many useful top-level scripts are calling very elaborate calculations in real packages with function barriers.  Depends on the circumstances, I guess.

**Comment by antoine-levitt** [comment]
> I fear that would end up more confusing for beginners. My feeling is that the changes in global scope should be either (optionally) consistent across all "top level" scripting/interactive environments, or that we are better off waiting for a v2.0 to give the opportunity to break things.

I second that. Whatever the decision is regarding scope at toplevel, having code typed up at the REPL and code `include`d behave differently would be massively confusing to me. That is true in general, and is even more true for scoping issues, which routinely confuse semi-experienced programmers like me, let alone beginners. As far as I can see this PR would be the only instance where `include` and REPL behave differently, it would be a shame to break that.

> I also fail to understand the extreme resistance to writing functions. Not only is it not onerous, everybody agrees it is how you should do things anyway, so why not tell people about it?

That might be going a bit off-topic, but I just want to point out that this is a huge cultural divide. There is a lot of things you can do without having to write a single function, and I would imagine much of data science happens in scripts. It's not necessarily bad performance if all you're doing is arrays. The usual workflow for a lot of people is: edit script.jl, alt tab to terminal, press up key and enter to run `include("script.jl")`, maybe print a few variables, alt tab back, repeat. The transition from this style to functions is annoying because it makes it much harder to examine the things you want to examine. This is somewhat helped by the debugger and the awesome `Infiltrator.jl`, but it's still not as convenient as just having everything in a script. This goes way beyond first week, and the lack of support in julia for this workflow (eg slow global variables, with `const` as the only workaround) is actually one of the things I (and several people I know) find most annoying with julia. I don't see any reason why Julia couldn't support this, while gently nudging users towards proper functions, modules and packages.

**Comment by JeffBezanson** [comment]
> There is a lot of things you can do without having to write a single function, and I would imagine much of data science happens in scripts. It's not necessarily bad performance if all you're doing is arrays.

I agree with that, but these things aren't mutually exclusive. Nobody is saying you should never write scripts. Rather, my position is that a mixture of (1) maybe put *some* code in functions, (2) avoid top-level loops since we're mostly calling library functions anyway, and (3) maybe write `global` a couple times if you insist on having a top-level loop, provides an acceptable trade-off. IMO it's not worth upending the language just to delete a couple occurrences of `global` inside loops in scripts --- in fact I thought the nagging presence of those `global` keywords was not a bad way to gently nudge people to functions, as you say. I guess it was not gentle enough.

> eg slow global variables

Let me drill down on this a bit. Would you want global variables exactly as they are today, just faster? Or would "script-local" variables do; e.g. implicitly wrapping the script in `function main()`? If using global variables for debugging purposes, the issue is that it's not generally possible to have full performance and a good debugging experience. Even in C++ etc. you have to disable optimizations to get really good debugging.

**Comment by antoine-levitt** [comment]
> I agree with that, but these things aren't mutually exclusive. Nobody is saying you should never write scripts. Rather, my position is that a mixture of (1) maybe put some code in functions, (2) avoid top-level loops since we're mostly calling library functions anyway, and (3) maybe write global a couple times if you insist on having a top-level loop, provides an acceptable trade-off. IMO it's not worth upending the language just to delete a couple occurrences of global inside loops in scripts --- in fact I thought the nagging presence of those global keywords was not a bad way to gently nudge people to functions, as you say. I guess it was not gentle enough.

I'm completely fine with having `global`s. I think what people object to most is the surprise element, and to me a very acceptable way to close this issue could be just adding an explicit warning (something like `Warning: the binding for x in this loop shadows the global binding for x; use global to access the global variable`). That feels like the right balance between nudging and helpful (but it's a personal opinion of course and I'm sure many feel differently)

> Let me drill down on this a bit. Would you want global variables exactly as they are today, just faster? Or would "script-local" variables do

What I really want is to be able to define ten numerical parameters at the beginning of my file and refer to them in functions without a prohibitive speed penalty. Right now I do `const` on all of them, which 1) is ugly 2) gives me a warning each time I replace eg `const x = [1.0; 2.0]` by `const x = [2.0; 3.0]` 3) makes me restart my session because I've written `const T = 10` and then want to look at what happens at time 10.5 4) makes me restart my session because I have one script where I do `const t = 3.4` because `t` is a hopping parameter and then I switch to another project where I do `const t = range(0, 1, length=N)` because `t` is time. I know the "proper" way to do that is pass the parameters around to functions, but it's just too annoying when you have a lot of them. Eg the code on which I've been working for a paper, and which is typical of this type of work for me, is one file with 250 lines, 15 parameters and 15 functions, some of which have tight loops, and every function uses a random subset of the parameters. For this kind of task, I just don't see any alternative that would be as convenient. Wrapping things in a `function main()` means I can't leisurely look at the outputs of my simulation in the REPL, which is bad. If it's really not possible for globals to be fast and debuggable, that's just life and it definitely won't stop me from using julia, but I was under the impression from https://github.com/JuliaLang/julia/issues/8870#issuecomment-320101744 that it could be possible with some wizardry.

**Comment by JeffBezanson** [comment]
> If it's really not possible for globals to be fast and debuggable, that's just life and it definitely won't stop me from using julia, but I was under the impression from [#8870 (comment)](https://github.com/JuliaLang/julia/issues/8870#issuecomment-320101744) that it could be possible with some wizardry.

They can definitely be faster, just not 100%. In the interim, by far the best thing to do is to annotate the type of the global at the point of use when it occurs in performance-critical code. That will give you nearly full performance, and you can still reassign the variable with no warning (you just might get a type error when running that particular function).

I can also imagine a utility here that runs a script by wrapping it in `function main()`, *but also* exports its variables to global at the end , so you can see all the values in the REPL after it runs.


> something like `Warning: the binding for x in this loop shadows the global binding for x; use global to access the global variable`

This is a possible transition strategy that I think has been discussed. It could work either way --- e.g. we could switch to global-by-default, and warn people to add `local` declarations before then.

**Comment by antoine-levitt** [comment]
> They can definitely be faster, just not 100%. In the interim, by far the best thing to do is to annotate the type of the global at the point of use when it occurs in performance-critical code. That will give you nearly full performance, and you can still reassign the variable with no warning (you just might get a type error when running that particular function).

It's still pretty annoying for complicated mathematical expressions, but yeah that's another workaround that at least doesn't abuse the `const` mechanism (it's mentioned in the performance tips, looks like I skipped that one...)

> I can also imagine a utility here that runs a script by wrapping it in function main(), but also exports its variables to global at the end , so you can see all the values in the REPL after it runs.

That could maybe work but it'd have to be pretty careful to be robust against ctrl-c (interrupting computations that run too long and looking at intermediate results is a common pattern) and not to hit the closure performance gotcha.

**Comment by jlperla** [comment]
> Nobody is saying you should never write scripts. Rather, my position is that a mixture of (1) maybe put some code in functions, (2) avoid top-level loops since we're mostly calling library functions anyway, and (3) maybe write global a couple times if you insist on having a top-level loop, provides an acceptable trade-off. IMO it's not worth upending the language just to delete a couple occurrences of global inside loops in scripts

It isn't the typing, it is the confusion for non-programmers - especially when it doesn't fit their intuition of what constitutes a script, and previous experiences with languages.

My feeling is that a language doesn't really support scripting if you have to annotate something as a global and it isn't "really" a global (i.e. it is "script-local" and is never accessed outside of the script, or from within a non-closure function).  This is the reason people find it so confusing, and matlab or IJulia scoping so intuitive.  Users don't think of these as global variables, and soft-scoping was letting them pretend they weren't.

>  Or would "script-local" variables do; e.g. implicitly wrapping the script in function main()

I think that is *exactly* the right mental model  (and the exact scoping rule in some scripting languages such as matlab and python, as far as I can tell). The code is wrapped in a big `let` before it is run.  Then, if someone declares something as `global` they really mean it, and it should smell.

In fact, a benefit of having softscope which is equivalent to "wrapping a script in a `main()`" is that you can manually exactly that.  Get your code working as a script, and then literally just put a function around the whole block of code and call it, without any modifications, when you need more performance.

> They can definitely be faster, just not 100%.

I think the speed of using global variables in Julia is a separate issue.  Slow global variables are not a big issue since you easily tell people that they need to put code in functions when they need it to be fast.  It is a teachable heuristic, even to the many scientists/economsists/etc. who would be scared if you started talking about "scope" (which someone coming from matlab would probably never even thought about, since using global variables (as opposed to script level) variables is heavily discouraged in matlab).

In a hypothetical world of "script-local" variables and true globals (which is my dream!) then people would start expecting the script-local to be faster in certain circumstances, but that could wait.

**Comment by JeffBezanson** [comment]
> then people would start expecting the script-local to be faster in certain circumstances, but that could wait.

Perhaps stating the obvious, if we did something like wrapping the script in `let` or `function main()`, it would be much faster immediately.

Maybe we should pursue this file-local scope thing seriously.

**Comment by jlperla** [comment]
> Maybe we should pursue this file-local scope thing seriously.

If it is feasible, then I think that is the ideal solution.  It fits the mental model people have.  Then the ugly annotation in v1.x could be something basically declaring a `.jl` as a script with a file-local scope... and decisions could be made later of whether that should be default in some circumstances.

I think you could even have the annotation around the whole code, i.e. `myscript.jl` becomes
```
@scriptlocal begin

#... CODE

end
```
where the tooling could be taught to ignore the macro with shift-enter?

My guess is that the REPL should have the current scoping fudge as well to make integration with Juno/vscode intuitive. (intuitively, tell people that they should think of the REPL is having something equivalent to a file-local scope, even if the performance is sometimes different).

After that, anything which is annotated as a  `global` REALLY means a global.

**Comment by MasonProtter** [comment]
Having different behavior between scripts and the REPL seems highly undesirable to me. If people are insistent that this be done, then I think it should be a non-default option that users can turn on in their startup.jl.

Personally, I mostly like the current scoping rules though.

**Comment by swissr** [comment]
> Personally, I mostly like the current scoping rules though.

Are you teaching? I think opinions are split (++) if you are teaching or using ~explorative scripts like antoine-levitt mentioned above or have relatively simple, e.g. 'normal biological scripts' vs. (--) more mathematically/computationally involved work where people are more strict and have more background knowledge. My gut feeling is that simpler is better and a softscope in the REPL would be nice (but I have switched my opinion several times)

**Comment by MasonProtter** [comment]
> My gut feeling is that simpler is better and a softscope in the REPL would be nice (but I have switched my opinion several times)

Having different scoping rules in scripts and packages versus functions is not simple and is only punting on the problem, making it an even more subtle issue and harder to debug. 

I'm not a teacher, but I have had numerous conversations explaining the scoping to new users both in person, and online and every one of those conversations have ended with something along the lines of 'huh, that's a little strange but okay, it's easy enough to remember' and then they move on and it's no longer an issue.

**Comment by jlperla** [comment]
> I'm not a teacher, but I have had numerous conversations explaining the scoping to new users both in person, and online 

There is a selection bias problem.  Essentially, anyone who asks on discourse or slack is very likely to be someone able to deal with the issue (i.e. they probably already understand how scoping works in 2-3 languages).  The people this issue impacts the most are not, and will never be, programmers.

Many "script" writers do not know about slack, discourse, etc. and there are cultural factors specific to their fields where they wouldn't ask these things online even if they did know.  Furthermore, you are missing out on the data of people who try Julia from matlab or python, don't understand why the simple loop doesn't work, and decide to try it again a few years later to see if it is more intuitive.

**Comment by JeffBezanson** [comment]
> something along the lines of 'huh, that's a little strange but okay, it's easy enough to remember'

What's your sense of what would be considered non-strange? I'm not really content to leave things in a state of "bad, but hey you can get used to it".

**Comment by MasonProtter** [comment]
> What's your sense of what would be considered non-strange? I'm not really content to leave things in a state of "bad, but hey you can get used to it".

I'm not actually sure. There were unintuitive and weird corner cases to the old soft-scope as well, though they were encountered less often by beginners. In a vacuum, I probably wouldn't be opposed to a re-introduction of soft-scope, but given that we can't break compatibility with scripts, I don't really see how this is  preferable at all. 

Having the REPL use different scoping rules than scripts seems way worse to my eye than some slightly unintuitive scoping rules with global for loops. I think that though it's not ideal for a new user, if this causes them to give up on julia, then they probably weren't going to stick with it very long anyway. 

I'm all for trying out new scope solutions for 2.0, but this just feels like a cure that's worse than the disease.

**Comment by jlperla** [comment]
> I think that though it's not ideal for a new user, if this causes them to give up on julia, then they probably weren't going to stick with it very long anyway.

I wouldn't be so sure. If non-programmers feel they can start writing scripts, or directly try porting a matlab script, you probably have them hooked. Luckily most of those users are on jupyter, where they don't run into this issue, but those who don't may run into the issue in the first 10 minutes of playing with the language.

> Having the REPL use different scoping rules than scripts seems way worse 

I definitely agree, if scripts remain in their current form.  But does Julia really have "scripts"?... it isn't too far off from literal includes into a REPL (as far as I can tell).

But what about the idea of having a "script local" scope  First introduced with an annotation and later in 2.0 introduced as a more formal default?  That way, the REPL is fully consistent with the script local scope, the tooling is consistent anytime the annotation is added, etc?  

> I'm all for trying out new scope solutions for 2.0

Maybe this is just all too much for a v1.5... This, and a few other breaking changes (eg I heard talk of moving more packages out of the standard library) could be queued to have a v2.0 sooner than previously intended. 

Basically, the feature would be an introduction of first-class scripts, which provide a new scope.  Beyond just the scoping issue, I believe it would also address most of the current performance issues with globals (because variables in scripts not annotated `global` would become script-local, which the compiler could treat as effectively the same as a big `let`?).

**Comment by StefanKarpinski** [comment]
Personally I don’t have any issues with the current behavior in files: loops introduce scope and assignment in a scope introduces a new local unless there’s already a local by that name. However, this is a royal pain in the hind quarters when going back and forth between a function body and the REPL. To me that is the only thing this is meant to fix—because the other thing doesn’t seem like it needs fixing.

On the other hand, I have in the past proposed the concept of file-local scope but didn’t do a great job of explaining or developing the idea so it never went anywhere. In particular, I like the idea that in order for a variable to be accessible outside of a file, it must be declared with `global`. This would be roughly like each file being wrapped in a let block.

**Comment by StefanKarpinski** [comment]
Sorry, button slip.

**Comment by antoine-levitt** [comment]
> On the other hand, I have in the past proposed the concept of file-local scope but didn’t do a great job of explaining or developing the idea so it never went anywhere. In particular, I like the idea that in order for a variable to be accessible outside of a file, it must be declared with global. This would be roughly like each file being wrapped in a let block. Maybe functions would be an exception, being implicitly global when at the top level like this.

That would prevent people from accessing their script variables in the REPL, which kind of removes the point of scripts. If you thought the villagers were pitchforky before...

**Comment by jlperla** [comment]
> On the other hand, I have in the past proposed the concept of file-local scope 

I think that a file-local scope would be very confusing for everyone.  the literal `include("test.jl")` is very useful, for example.  Matlab connects the script-level scoping to a file, and it makes things clunky.

> Maybe functions would be an exception, being implicitly global when at the top level like this.

Functions in a `.jl` file or a REPL session accessing a variable not purposefully declared as a global should be a closure, don't you think? Then it is entirely consistent with functions inside of functions or funcitons inside of let blocks (which have an implicit scope).

> That would prevent people from accessing their script variables in the REPL, which kind of removes the point of scripts. If you thought the villagers were pitchforky before...

Agreed.

I think that of what constitutes a script, independent of the connection to a particular file, is the key here and it doesn't make sense to think about scoping solutions until that is figured out.  It is becoming more and more clear that the issue here is that people scripting don't think of top-level variables as true globals.

Here is an idea.  The definition of a script is defined is whenever a "script-local" scope is defined.  That is a proper and normal scope in every sense (e.g. functions in it referencing unannotated variables are closures as I say above).  Right now that concept doesn't exist, so global variables are providing a solution for "script-local" and for true globals - which is the source of almost all confusion.  It "works" in jupyter right now and with the old v0.6 simply because people don't/can't make a distinction between the two.

Instead of "scriptlocal" scope, perhaps it is more general to describe it as a "top-level " scope.

In a hypothetical v2.0 redesign of scoping, when would it make sense to introduce a new top-level  scope?  My answer is that: a new "top-level" scope is introduced with any new top-level session.  Hence the following would have a top-level scope introduced:
- `julia script-name.jl`  in v2.0 introduces a toplevel scope and then executes the file.  i.e. not file level, session level.  That encompasses `] test` as well, so the `runtests.jl` would be running in a toplevel scope.
- A new REPL session
- A new session in Juno/Vscode (which is nicely connected to the REPL session)
- A new jupyter kernel for a notebook

We could describe the intuition as: "imagine a top-level script as putting all of the code in a big `function main()` or a big `let`.  You might need some slightly special cases for functions (e.g. if a function is defined in a top-level scope which accesses toplevel scope variables it becomes a closure rather than a method, etc.) but I think they would be intuitive.

What doesn't create a new scope?  The most important one is that a literal include does not (e.g. `include("myfile.jl")`).  This is a session-level rather than a file-level scope.

Note that there is a symmetry here:  If you are editing a file intended to be called with `julia script-name.jl` in Juno then the scoping of using the REPL session matches the scoping of actually running the file.

The scoping rules in a toplevel scope are identical to the scoping rules in any other scope.  Global variables would become very rare, would have a smell to them, and any sort of inconvenience in using them (e.g. annotating `global` to access the variables in a for loop) make plenty of sense.

... now, lets say that mental model of scoping makes sense, then should it wait for a v2.0?  It is possible that the following would work:
 - Merge this current REPL PR, which gives a good emulating of the behavior for both the REPL, Juno/vscode, etc. along with IJulia.
- Add in a `toplevelscope = {true|false}` to the `julia` command-line for executing a `.jl` file.  The default would be `false`.  If set to true then a big `let` is put around the code or it just uses the exact PR here before it is executed.
  - If you use Juno/etc. on a file (which sends commands to a REPL session) it would then be pretty much equivalent to running a file with `toplevelscope = true` - which you can do.
  - This is non-breaking.
- In v2.0, the `toplevelscope` could become more of a default, or even the only choice...

**Comment by MasonProtter** [comment]
Having the meaning of code depend on what command line arguments you used when starting up julia is even worse than having different scoping rules for scripts vs the repl.

**Comment by jlperla** [comment]
> Having the meaning of code depend on what command line arguments you used when starting up julia is even worse than having different scoping rules for scripts vs the repl.

I hear you.  Then what about a hypothetical v2.0 where calling `julia myfile.jl` *always* introduces a new toplevel scope (i.e. a toggle is only useful as a stopgap to avoid breaking code).  Maybe this is all simply impossible to do right in v1.x without either breaking existing scripts or making things even more confusing?

**Comment by MasonProtter** [comment]
> Maybe this is all simply impossible to do right in v1.x without either breaking existing scripts or making things even more confusing?

That's my strong feeling. Soft-scope is semantically different from our current scoping rules and any changes to the scoping will either be a breaking change or increase the complexity of the language. 

Currently if someone shows me a piece of code that says
```julia
x = 1
for i in 1:10
    x += 1
end
x
```
and asks me what it returns, I need to ask is a julia language question: "Is this code being run out in the global scope, or is it in a local scope?". I don't need to ask about file structure, modules, scripts, repls, etc. Technically, I might need to ask them if they're using IJulia or not, but that's outside our control here.

Assuming we don't make breaking changes, these proposals will change that from questions about language constructs (global / local scope) to fiddly satellite issues like "Okay, so did you run this in a repl? Did you run it through `include`ing a file into the repl? Did you run it like `julia myscript.jl`? Is it in a module?"

I see that as a regression.

**Comment by jlperla** [comment]
> Did you run it through includeing a file into the repl? Did you run it like julia myscript.jl? Is it in a module? I see that as a regression.

My proposal is that this has a simple answer:  a new scope is included in a top level session.  We would tell people that  `include` is *not* running a "script"... it is for a literal include.  Otherwise, I am not sure if there is any confusion?  Your hypothetical
```
x = 1
for i in 1:10
    x += 1
end
x
```
always has the same answer, even in a top level scope?  No thinking required at all, and almost no global variables to be seen.

**Comment by MasonProtter** [comment]
I was referring to *non-breaking* changes. 

I don't feel like I have enough insight to predict what sort of unintended consequences (if any) your top-level scope proposal would have if we could do it in a comprehensive, language wide, breaking way. I suspect there would be weird corner cases abound, but it'd require thought.

**Comment by jlperla** [comment]
> I was referring to _non-breaking_ changes.

Gotcha.  Then I think we probably agree.  It remains to be seen... but if the optimal solution is to introduce a new scoping level then it is better to do it right, and make sure it tackles other issues (e.g. performance of top-level scripts) as well.

> I don't feel like I have enough insight to predict what sort of unintended consequences (if any) your top-level scope proposal would have if we could do it in a comprehensive, language wide, breaking way. I suspect there would be weird corner cases abound, but it'd require thought.

Yes.  This will take thought from people smarter than me (a low bar!) who have a solid intuition of scripting.  One thing that helps is considering what other "scripting" languages do. 
- What I have described is a variation on matlab (i.e. matlab has a scope whenever you use a new script or start a REPL, so that if you see a `global` in matlab, it is a "real" global.  But the connection to a `.m` file is very clunky in matlab and shouldn't be emulated.)
- Someone who understands python better could probably explain why this same scoping issue isn't an issue there either.  But I do know that in python, it is very rare to see a `global` annotation on a variable.  I believe that in python, a top level script is running in something like a hidden module so there is a very natural scope level.  Also, I also believe that loops in python have ugly leakage of scope (in my opinion), so maybe that is the main reason?
- Similarly, I don't know R well.  My guess is that in R everything outside of a function is basically global, that loops don't introduce a new scope at all, and that the pervasive functional-style means it doesn't matter to them in practice.

**Comment by StefanKarpinski** [comment]
> Functions in a .jl file or a REPL session accessing a variable not purposefully declared as a global should be a closure, don't you think?

Clearly. The question is whether you would need to declare a function as global to be able to access it outside of the file in which it is defined. That would be rather annoying. The premise is that a function is often intended to be called elsewhere whereas other locals tend to be used locally rather than exposed as part of an API.

You idea of a “session” already exists: it’s called a module. That notion of scope is not syntactically limited and therefore doesn’t actually address any of the problems with current global scope. In fact it’s the same. You need the ability to say “I’m sure that these are all the accesses to this variable” or you’ve just reinvented modules.

**Comment by StefanKarpinski** [comment]
> Someone who understands python better could probably explain why this same scoping issue isn't an issue there either.

Because in Python loops don’t introduce scope. This becomes very awkward when it comes to comprehensions, however: they can either match for loops and not introduce scope and leak iteration variables into the enclosing scope (old behavior) or they can introduce scope and not match for loops (new behavior). Neither is great. Julia instead chooses to have more scope-introducing constructs, including loops, which behave the same way as comprehensions: both introduce scope.

**Comment by jlperla** [comment]
> You idea of a “session” already exists: it’s called a module. 

OK, sounds like I have failed.  But maybe there is a way to reorganize/recast an "anonymous module" introduced when starting the REPL or a jupyter notebook with its own scope (distinct from globals) to represent a session in an intuitive sane way.  Hopefully the perspective I have given for how top-level scopes should be equivalent to a big `let` is useful.

**Comment by StefanKarpinski** [comment]
> Hopefully the perspective I have given for how top-level scopes should be equivalent to a big `let` is useful.

The issue is that a let block is syntactically bounded whereas what you’re describing is unbounded and open-ended. When you parse and evaluate a let block, you can definitively answer questions like “is the variable `x` ever assigned in the scope of this let block?” With an open-ended construct like a module or the “session” concept you’re describing, you cannot answer that question, because even there are no  assignments in what you’ve seen so far, there might be one at any point in the future. It’s that inability to predict the future and see all possible assignments that causes _all_ of the problems with globals. (Declaring something `const` is just a promise that there will not be any assignments.) A “local scope” that is unbounded is just a global scope. The best you can do with an unbounded construct is ask “has the variable `x` been assigned yet?” which is what the soft scope heuristic does: if `x` is assigned already, treat it as a global, if it’s not assigned yet, make it local. This doesn’t match local scope perfectly because in local scope even if the assignment to `x` happens after a usage, `x` is local for the entire duration of the scope. With the soft scope heuristic, that won’t work because by the time the later assignment is seen, it’s too late because you already evaluated code with the other decision. But it’s close enough to usually work similarly since most of the time one assigns something before using it.

Ok, so what is wrong with using the soft scope assignment in top level global scope all the time? That’s what we didn’t in 0.6 and before. Aside from the many complaints we got that this was confusing and various misguided attempts to document it which were not actually correct, it has the issue that it means that it’s not statically decidable whether a variable in a top-level loop is local or global: it depends on whether the variable has been assigned or not, and it’s easy to write code where that depends on a random bit or an external input. For example:
```jl
# top level, x not defined
if rand(Bool)
    x = 1
end
for i = 1:1
    x = 2 # local or global?
end
# x here is either 2 or undefined
```
With the 0.6 soft scope heuristic, whether the second assignment assigns to a local `x` and leaves the global `x` alone or reassigns the global `x` depends on a random bit. If the random bit is true, then then `x` has a value going into the for loop so the assignment reassigned the global with 2; of the random bit is false, then `x` has no value going into the loop and the assignment creates and assigns a new local variable, leaving the global `x` undefined.

So that’s bad. Another solution would be to base it not on whether the variable has been assigned but whether code that could have assigned it has been evaluated. So in the above example, it wouldn’t matter whether the if branch is true or not: the fact that `x` could have been assigned means that that later loop treats it as an existing global. I’ll leave it to you to judge whether that’s more or less confusing. In the discussion of fixing the 0.6 behavior, I proposed this and it was deemed to subtle and confusing, although in retrospect maybe it was better that what we did. 

However, note that both of these options are much more subtle and hard to explain than what Julia currently does.

**Comment by jekbradbury** [comment]
> they can either match for loops and not introduce scope and leak iteration variables into the enclosing scope (old behavior) or they can introduce scope and not match for loops (new behavior).

The way I've learned to justify this behavior in Python is to think of for loops as being primarily for imperative programming (where you frequently set variables and expect them to persist) and comprehensions as being primarily about functional programming (where you can use side effects but very rarely want to persist things across loop iterations).

(There's also another option for loop scoping that would be consistent with comprehensions: you can put the iteration variable/s into a new nested scope but keep variables defined in the loop body in the outer scope. I'm not sure if any languages do that, although it feels like a fairly intuitive compromise...)

**Comment by StefanKarpinski** [comment]
@jekbradbury, that makes sense. It also works better in Python because Python doesn’t have real closures, so the difference between having a new local per loop iteration and assigning to the same outer variable is hard to observe. Julia does have closures which makes this very much observable:
```jl
v = [(x = i^2; ()->x) for i = 1:5]
```
It’s hard to argue that you don’t want `map(f->(), v)` to produce 1, 4, 9, 16 and 25.  If comprehensions didn’t have scope or the assignment to `x` leaked out of that scope then you would get 25 five times instead. That’s pretty clear for comprehensions, but is it really different for loops? Shouldn’t this do the same thing?
```jl
v = Funtion[]
for i = 1:5
     x = i^2
     push!(v, ()->x)
end
```
If `x` was local to the comprehension but not the for loop then the comprehension would produce the desired vector of thunks returning a sequence of squares while the loop version would produce five thinks all returning 25. And if someone happened to assign to `x` after the loop then that value is what this would all return. Of comprehensions and loops were different like this, it would make refactoring code between comprehensions fraught with danger. Sure, this is a somewhat advanced situation, but isn’t that when you need the language to have your back the most?

Python, on the other hand, doesn’t allow lambdas to capture local variables, so you would get an error that `x` is not defined. It avoids the distinction but it makes functional programming quite annoying.

**Comment by jlperla** [comment]
> The issue is that a let block is syntactically bounded whereas what you’re describing is unbounded and open-ended. When you parse and evaluate a let block, you can definitively answer questions like “is the variable x ever assigned in the scope of this let block?” 

I think I see now.  In my mind, I always think of scripts as compiling and executing where it is all visible to the compiler so this isn't an issue.  I can understand performance differences with executing those out of order (i.e. in an interactive scope/module it may not infer in the same way) but I didn't appreciate the role of syntactic bounding on deterministic behavior.

> However, note that both of these options are much more subtle and hard to explain than what Julia currently does

If you have a second, it may be helpful to discuss the difference with what you wrote above from
```julia
function f()
    if rand(Bool)
        x = 1
    end
    for i = 1:1
        x = 2
    end
    @show x
end
f()
end
```
or even
```julia
function g()
    for i = 1:1
        x = 2
    end
    @show x
end
g()
```
I know that you think the current behavior is easy to explain, but I think understanding it is a lot more subtle than you realize for people who don't live and breath julia's scoping rules.

> So that’s bad. Another solution would be to base it not on whether the variable has been assigned but whether code that could have assigned it has been evaluated. So in the above example, it wouldn’t matter whether the if branch is true or not: the fact that x could have been assigned means that that later loop treats it as an existing global. 

I suspect you guys have completely exhausted the design space of global vs. local here - it isn't like this is the first time you have tried!   Given the current scopes, it is a question of tradeoffs between things being confusing to beginners vs. advanced users.

But I still am not sure that there isn't room for a new scope level.    My suggestion for a standardized interactive/toplevel scope doesn't work, but maybe something along the lines of a `@script` annotation for "file-local" variables is valuable.  In effect, it would be a statement of promises in the same sense as the current `const` does.  Of course, if you can't have an interactive REPL/Jupyter almost entirely consistent with it in scoping rules (though not performance), then it is pointless (i.e. otherwise they could just wrap things in a function).

**Comment by swissr** [comment]
If the design space is exhausted, would two scope variants really be that subtle and confusing?
- the real scope would be the current 'global scope'. An explicit error message says that `global` is needed (and that for convenience it could be left out in the REPL etc.). This version is slightly more annoying but afaiu the only sound possibility
- In order to "avoid royal pain" and help with "little strange but okay" and with teaching, there would be an official but optional @softscope support in IJulia, the REPL and (not recommended but possible) in .jl scripts. It could be configured in startup.jl but there would be no commandline startup option to keep it simple/restricted. It's purely meant for convenience in interactive work.

This would mean that there will be Julia-for-loop-code in the internet which (depending on options) doesn't run because of a missing `global`. The error message (and doc) would explain that it is technically not otherwise possible but had been supported in certain situations for convenience.

**Comment by JeffBezanson** [comment]
> Another solution would be to base it not on whether the variable has been assigned but whether code that could have assigned it has been evaluated. So in the above example, it wouldn’t matter whether the if branch is true or not: the fact that `x` could have been assigned means that that later loop treats it as an existing global.

I did briefly look into that during the 0.7 era. The problem is that adding a global binding has various externally-visible consequences (e.g. what `names` returns, or whether there is a conflict with a name imported from a package). People use `if` statements at the top level specifically to avoid those effects (often e.g. version checks). Making the binding effects unconditional breaks everything quite spectacularly.

In local scope the concerns are totally different. If locals copied this behavior of globals, then the scope of variables in a function could be different on different calls to the function with different values. That would just be a disaster. Whereas at the top level, getting different scope on different runs with different values (e.g. different configurations or julia versions) is the whole point. The difference between global and local is just much larger than anybody intuitively expects. The C preprocessor, goofy as it is, has a point!

**Comment by JeffBezanson** [comment]
> I know that you think the current behavior is easy to explain, but I think understanding it is a lot more subtle than you realize for people who don't live and breath julia's scoping rules.

The key is that you have to look at a top-level expression in isolation, because that is how the system sees them. Most, or all, of the problem here is due to the illusion that something like
```
x = 0
for i = 1:n
    x += i
end
```
is a "piece of code". It is not! It's two pieces of code. Look, I'm not a robot. I understand it looks like a piece of code. It does to me too. But at a certain point you have to accept that you're talking to a machine. The suggestion of adding `@script` at the top works because it transforms this into something that *is* a piece of code; it says to wrap everything in the file in some kind of block.

Putting it all in a function also changes things because then the `function...end` delimits it. You're allowed to look at the whole function body together (one piece of code), which lets you see that the `x` variable is shared between the two statements. But when you're only allowed to look at
```
    for i = 1:1
        x = 2
    end
```
`x` only exists inside the loop. It can't exist outside the loop because there's no mention of it outside the loop. If there's a mention of it in a different top-level expression, that changes nothing because there's nothing tying the two top-level expressions together. I hope this helps somewhat.

**Comment by jlperla** [comment]
> It is not! It's two pieces of code.

Very helpful.  And I fear that this is lost on a lot of people (luckily most of them use Jupyter and then the heuristic of "put everything with a for loop into a function outside of jupyter).  A lot of script people don't even really understand the distinction between a compiler and interpreter.

> The suggestion of adding @script at the top works because it transforms this into something that is a piece of code; it says to wrap everything in the file in some kind of block.

Given my assumption that you guys have exhausted the design space of tricks on the current scoping levels, is there a place for a new `@script`?  In essence, it takes the `.jl` file, wraps it in a `let` and then compiles the whole thing - enabling whatever optimizations it can and dealing with the issues you mention?

Of course, on its own, that sort of feature is completely unnecessary... it is just as easy to just always wrap things in a function, but it becomes useful if it is (mostly) in sync with the tooling/REPL.

> If there's a mention of it in a different top-level expression, that changes nothing because there's nothing tying the two top-level expressions together

Lets assume two things: (1) the REPL and Juno shift-enter supports the proposed v0.6 scoping/soft-scoping; and (2) users execute the same lines of code, *in the same order*, as a `@script` file.

Would the calculations (but not the performance) be identical in almost all circumstances?  The `if rand(Bool)` clearly would have trouble, but are those the only bizarre ones?

**Comment by HenriLaurie** [comment]
I'm trying to teach Jula at both ends of experienced vs beginner spectrum. My solution is: teach functions before loops (actually, also comprehensions before loops). Then local vs global scope is an intuitive concept which I explicitly introduce, and one can then simply say that in Julia, loops also introduce local scope.

Perhaps the learning issue is simply that loops have "always" been one of the earliest things taught/experimented with? In that case, a system of warnings (perhaps specialised in the sense that this set can be turned off without affecting any other warnings) would be enough for experienced programmers, and for teachers it would be a handy reinforcement tool?

So I'm on the side of minimal change. A few warnings, the need for an occasional annotation, customised variations to live in packages.

PS -- as a further tweak to a special warning system for possibly ambiguous variables (i.e. locally declared but the same name as in the global namespace), why not the first time in a session the warning is displayed also give a link to a special page i.e. something like a small blog post or a tutorial, not the main docs, but leave it out later?

**Comment by HenriLaurie** [comment]
Oh, and add in the help that comes up with ? that loops create a local namespace, perhaps with an illustrative example such as 
```
x = 5; for n in 1:2 println(x) end
```
versus
```
x = 5; for n in 1:2 x=2; println(x) end
```
and noting that although the global x is visible inside the loop it can't be bound to a new value without annotating it with "global"

**Comment by stevengj** [comment]
Thanks @JeffBezanson, this is basically what I advocated for in #28789.   I really don't want to have to rehash all the arguments there, e.g. [why "just teach students about scoping" or "just use functions" were not acceptable solutions](https://github.com/JuliaLang/julia/issues/28789#issuecomment-414851094), and would rather focus on this PR.

There is no perfect non-breaking solution here.  Changing everything in `Main` (i.e. including "scripts") to softscope [has a definite appeal](https://github.com/JuliaLang/julia/issues/28789#issuecomment-423336959), but is arguably a breaking change disallowed in 1.x.   We could have a new `--softscope=yes` command-line option to opt-in for scripts, however.

FWIW, using softscope in IJulia for interactive notebooks has proven consistently popular.  Occasionally you get questions on discourse of "why does this loop work in IJulia but not in the REPL," but it's with users pretty consistently preferring the IJulia behavior.

File: stdlib/REPL/src/REPL.jl [hunk 1]
```diff
@@ -83,7 +99,7 @@ function eval_user_input(@nospecialize(ast), backend::REPLBackend)
                 put!(backend.response_channel, (lasterr,true))
             else
                 backend.in_eval = true
-                value = Core.eval(Main, ast)
+                value = Core.eval(Main, softscope!(ast))
```
Comment (stevengj) [inline stdlib/REPL/src/REPL.jl]: Maybe it would be better to have an array of transformation functions that are applied to the `ast`, as was discussed in https://github.com/stevengj/SoftGlobalScope.jl/issues/2, where `softscope!` is in the list by default.

This would make future customizations of the REPL easier and more composable, e.g. Revise.jl [hacks the REPL input](https://github.com/timholy/Revise.jl/blob/672dc74b99f2dbd9183abeeed73ff0e65af7781a/src/Revise.jl#L1044-L1054) as well.   It would also allow people to `pop!` the `softscope!` transformation if they don't like it.

File: stdlib/REPL/src/REPL.jl [hunk 2]
```diff
@@ -73,6 +73,22 @@ mutable struct REPLBackend
...
+    if ex isa Expr
+        h = ex.head
+        if h === :toplevel
+            for i = 1:length(ex.args)
+                ex.args[i] = softscope!(ex.args[i])
+            end
+        elseif h in (:meta, :import, :using, :export, :module, :error, :thunk)
+            return ex
+        else
+            return Expr(:block, Expr(:softscope), ex)
```
Comment (stevengj) [inline stdlib/REPL/src/REPL.jl]: Should this be something like `Expr(:softscope, true)`, with a corresponding `Expr(:softscope, false)` that turns it off?

I'm wondering whether there might ever be circumstances, e.g. in a macro, where you want to turn off softscope for a nested block even if the surrounding code is softscoped.

**Comment by StefanKarpinski** [comment]
> > @JeffBezanson: The suggestion of adding `@script` at the top works because it transforms this into something that is a piece of code; it says to wrap everything in the file in some kind of block.
> 
> @jlperla: Given my assumption that you guys have exhausted the design space of tricks on the current scoping levels, is there a place for a new `@script`? In essence, it takes the `.jl` file, wraps it in a `let` and then compiles the whole thing - enabling whatever optimizations it can and dealing with the issues you mention?

Let me make sure that one of the consequences of this is 100% clear: if you put `@script` on something and it has the effect of wrapping that code in a `let` then you cannot access the top-level variables in that script form elsewhere. That's what I had mentioned earlier:

> @StefanKarpinski: On the other hand, I have in the past proposed the concept of file-local scope but didn’t do a great job of explaining or developing the idea so it never went anywhere. In particular, I like the idea that in order for a variable to be accessible outside of a file, it must be declared with global. This would be roughly like each file being wrapped in a let block. Maybe functions would be an exception, being implicitly global when at the top level like this.

Which was met with:

> @antoine-levitt: That would prevent people from accessing their script variables in the REPL, which kind of removes the point of scripts. If you thought the villagers were pitchforky before...

I kind of get the feeling from comments like

> @jlperla: But I still am not sure that there isn't room for a new scope level.

> @swissr: would two scope variants really be that subtle and confusing?

that people have the impression that there's some kind of in-between goldilocks kind of scope that behaves like a local scope when that's what you want but a global scope when that's what you want, but it's not like this exists and we're just unwilling to do it... as far as I can tell, this isn't a coherent design, at least not from what I've been able to determine.

**Comment by StefanKarpinski** [comment]
To clarify: we're very willing to think out of the box here and do something sneaky and/or clever.

**Comment by jlperla** [comment]
> then you cannot access the top-level variables in that script form elsewhere.

Yup, I understand and thanks for confirming.  The question I have is whether a REPL (or shift-enter) session with solution like v0.6 soft-scope would have the same behavior in almost all cases if you execute the lines in order.  i.e. run it in a "let" in production, but during development if you execute it in a softscope it would give the same results...   Certainly there would be variables that are softscope'd global in one context and local in another.  This is generally how I do a lot of coding:  write it all in jupyter where the scope never confuses me, and then copy/paste into a big function in a `.jl` file for production.

If true, this is the only sort of sneakyness that I can think of...  nobody should expect that if they execute a script in a big `let` function out of order that it would deliver the same results, so those sorts of things wouldn't be a surprise to them...  And people could be taught that performance increases when you run it all at once, since the compiler is able to use more information.

> goldilocks kind of scope that behaves like a local scope when that's what you want but a global scope when that's what you want, but it's not like this exists and we're just unwilling to do it... a
>To clarify: we're very willing to think out of the box here and do something sneaky and/or clever.

I understand completely, and your patience and openmindedness on this is very appreciated.

There is also an increasingly high chance that (in the opinion of many, but certainly not all) your v0.6 rules were the best possible solution given the usability tradeoffs.  That may be why the current IJulia implementation has caused no user confusion that I am aware of.

**Comment by antoine-levitt** [comment]
I think a very important principle is that `include` is functionally equivalent to copy/pasting in the REPL. Breaking that is massively more confusing than any weird scoping rule. Accepting that, and accepting that `x = 2; println(x)` is valid at the REPL, means there is a global scope shared by the REPL and scripts, and when I write `x = 2` I declare a variable at the global scope. From there, as far as I can see, there are essentially two designs: special-case toplevel code (0.6) or not (1.0). 1.0 is more consistent, 0.6 was more convenient. I personally liked 0.6 better (toplevel code is different from function code, it's fine to special-case it).

The only reasonable options I can think of are: bring back 0.6, keep the current behavior unchanged, or keep the current behavior but print a warning if a binding shadows a global variable.

**Comment by stevengj** [comment]
@antoine-levitt, a fourth option is to bring back the 0.6 behavior only for interactive code, which is basically the idea here.

This was discussed ad nauseam in #28789, but the TLDR is that there is no perfect solution, but given that we want to be non-breaking in 1.x, changing this just for interactive code is pretty much the only option to improve this issue.

Whether "interactive code" also means `include` statements run from the REPL is open to question, but I would be inclined to say no (by default).

**Comment by mauro3** [comment]
Could this break doc-tests?  Presumably that would be considered ok for a 1.x release?

**Comment by StefanKarpinski** [comment]
Only if the doc tests use the softscope!, which, unless someone makes them do that, they won't. The only case where this chance could cause a working doc test to fail is if the doc test uses a local variable name that is already a global variable name. Even then, it's unlikely to cause an issue unless there's a closure that captures the variable and it's modified later on. Given that doc examples aren't generally guaranteed to work unless you run them in a clean REPL, I think that's ok.

**Comment by vtjnash** [comment]
> if the doc test uses a local variable name that is already a global variable name. Even then, it's unlikely to cause an issue unless there's a closure that captures the variable and it's modified later on.

I think it's helpful to remember that this isn't just hypothetical. This _was_ a known reliability issue with CI before we changed the scoping rules. Prior to the change, our test suite would occasionally fail because some fairly trivial expressions could radically change meaning depending on whether some other tests happened to have run on the same worker (not something complex like a closure, since those weren't really affected by the scope change anyways, but something simple like the variables in a for-loop were getting mixed up). The problem with depending on implicit global scope is that it's sometimes really big, so that you can't see most of it and you can end up with some unexpected, and thus almost inexplicable, action-at-a-distance when trying to paste things together.

**Comment by JeffBezanson** [comment]
> The only case where this chance could cause a working doc test to fail is if the doc test uses a local variable name that is already a global variable name.

Just to be clear, that will not actually happen when running doc tests, right? IIUC, it's only an issue if somebody tries the doctest examples in the REPL.

**Comment by StefanKarpinski** [comment]
Right. The doc tests themselves are fine. My point was that even in the REPL, it could only behave differently if it uses a global and local variable with the same name. While that is plausible in real code where the global scope spans many files (and did actually happen and cause bugs pre-1.0), it's pretty implausible in doctests, which have fairly limited scope (pun sort of intended?) and are written specifically to be exemplary.

**Comment by stevengj** [comment]
Is there an easy way to apply the new softscope to `include` or `include_string`?   Currently [SoftScope.jl needs to jump through hoops](https://github.com/stevengj/SoftGlobalScope.jl/blob/master/src/SoftGlobalScope.jl#L202-L223) to do a transformed `include_string` while preserving line-number information.

**Comment by StefanKarpinski** [comment]
Removing needs docs tag since I've opened a [dedicated issue](https://github.com/JuliaLang/julia/issues/34104) for the docs.

**Comment by antoine-levitt** [comment]
So the decision has been taken to do this ? :(

In that case, to hopefully reduce confusion, can we get a warning in `include`d code? Something like "warning: the binding x overwrites the global variable of the same name"?

**Comment by vtjnash** [comment]
> The doc tests themselves are fine. 

They shouldn't be though, right? The documentation says they are supposed to act as if it was typed at the REPL: https://github.com/JuliaDocs/Documenter.jl/blob/1d0a3837d72179a49f9e3923b27251cc6c7dd8d5/docs/src/man/doctests.md#repl-examples

One reason not to do this particular PR is that it'll become a bit of a mystery what scope something may be using (without consulting the code).

> have exhausted the design space of tricks

Jeff and I talked offline about several other designs, so we haven't exhausted the options. We're currently just at a local minimum for the easiest design to describe, so any modification (including this PR) adds special cases that become more longer and nuanced to explain in the documentation.

**Comment by jlperla** [comment]
> is that it'll become a bit of a mystery what scope something may be using (without consulting the code).

My fear is that Julia beginners start coding in jupyter, where they find the scoping intuitive, then move to using Juno or vscode and (since shift enter sends things to the repl) also find it consistent and intuitive.... But...if they were ever to actually run their script on its own, the behavior could be completely different.

That seems even harder to explain than the current situation (where the heuristic advice to "scripters" is to tell them to wrap any loops in a function outside of jupyter)

**Comment by tkf** [comment]
If you were to do this, why not do this just _after_ the feature freeze, so that you can maximize the time for feedbacks? It'd be also nice to release (say) 1.5-alpha with 1.4 like it was done for threading.

**Comment by JeffBezanson** [comment]
I would be fine with merging this after 1.4 feature freeze.

**Comment by tpapp** [comment]
Does this imply that code included with `include` and typed directly into the REPL would have different scoping behavior? I am asking for two reasons:

1. For some complicated data analysis, I develop code interactively and then organize them into files which `include` previous files I am finished with for the time being (eg to read data, set up plotting, etc). Technically this would break that kind of code (except that personally for me it won't because I just use assignments in scripts).

2. The julia-repl Emacs mode chooses to [evaluate code directly or via `include`](https://github.com/tpapp/julia-repl/blob/b11a5729709c5ca541db2b6472b6579166723060/julia-repl.el#L565) depending on context and user settings. So far this has been innocuous because the two are interchangeable, but if they are not then I would have to devise a workaround. Is it possible to prepend a `:softscope` before an `include`?

Finally, as much as I like seeing the *existential crisis* and *minor change* labels together, I am not sure the latter is justified. I think this is a breaking change.

**Comment by StefanKarpinski** [comment]
The only code that this would break is interactive code and even then only in cases where someone has defined a global variable, then use a local variable by the same name, then used the global variable again. If the interactive code is an example in documentation, then it seems unlikely that someone has done this since that's a very confusing way to write an example. What interactive scenario are you imagining where someone might have this issue?

**Comment by jlperla** [comment]
> The only code that this would break is interactive code and even then only in cases where someone has defined a global variable, then use a local variable by the same name, then used the global variable again.

I think that one of the issues he brings up is the same concern I have with Atom.  Create a `.jl` file and start editing it in emas/atom/vscode.  It sends the code to the REPL to execute (and hence has the "softscope behavior".  However, you ever do a `include` on that file yourself (or if the tooling does, as he says emacs does), then the behavior of the code is different than that of editing (since softscope no longer applies when running in through an `include`).

**Comment by tpapp** [comment]
> The only code that this would break is interactive code and even then only in cases where someone has defined a global variable, then use a local variable by the same name, then used the global variable again.

So something like
```julia
x = ...some value...

function f(x)
    # do something and return a result
end

y = f.(x)
```
?

> What interactive scenario are you imagining where someone might have this issue?

My concern was code that behaves differently when

1. "typed into the REPL" (could happen, eg, when sent by some IDE like julia-emacs) 

2. `include`d

My understanding is that this PR breaks this equivalence, is this correct? Sorry if I misunderstood something.

**Comment by StefanKarpinski** [comment]
> @tpapp: So something like

No, that would work the same since the softscope bit doesn't change functions, only top-level for loops. It would have to be code that does this:

```jl
some_name = 123

for x in itr
    some_name = "hi there"
    # use it locally
end

x = some_name + 456
```

**Comment by StefanKarpinski** [comment]
> @jlperla: I think that one of the issues he brings up is the same concern I have with Atom. Create a `.jl` file and start editing it in emas/atom/vscode. It sends the code to the REPL to execute (and hence has the "softscope behavior". However, you ever do a `include` on that file yourself (or if the tooling does, as he says emacs does), then the behavior of the code is different than that of editing (since softscope no longer applies when running in through an `include`).

If the code is in a function body, then it will work the same. If it's top-level and it's intentionally modifying a global variable, then you should use `global` and it will work the same in the REPL or a script. The only situation where you should be relying on soft scope REPL behavior IMO is when cutting and pasting code from the body of a function into the REPL. That's the case where the difference in behavior is annoying; otherwise, just use `global` to modify a global.

**Comment by StefanKarpinski** [comment]
The one modification to this PR's behavior that I would support is to make it a warning in non-REPL mode to use the same name for a global and an implicitly local variable in a loop. E.g. I would want to make the example code I gave [here](https://github.com/JuliaLang/julia/pull/33864#issuecomment-573789153) warn that `x` in the loop should either be explicitly marked as `local` or renamed to a name that isn't used for a global. That warning would mean that if anyone does take REPL code that worked but relies on soft scope to work, and runs it in a script, they would get this warning, telling them they should fix it.

**Comment by tpapp** [comment]
> That's the case where the difference in behavior is annoying; otherwise, just use global to modify a global.

Thanks for the clarification. This is a good style recommendation; my concern is that it possible for some otherwise quite ordinary code (not something I would write as I avoid top-level loops, but still valid code) to behave differently in the REPL and when `include`d.

I explicitly relied on these two being the same in julia-repl, so I would have to devise a workaround if this is merged.

**Comment by jlperla** [comment]
> If the code is in a function body, then it will work the same. If it's top-level and it's intentionally modifying a global variable, then you should use global and it will work the same in the REPL or a script. 

Sure, but what if they don't?  Then they get the code working in Atom and are confused why it ceases to work when they try to run it directly without `shift-enter`?

The main people this effects are those who are especially confused with the scoping rules (and matlab is completely different, which makes it harder.  There, you declare a variable to be global, and nothing is global at the top level by default). If I recall, there are plenty of pieces of code which are valid (and compile) within both scoping rules but have different behaviors?  People then need to realize that code would have different values returned if they execute with `shift-enter` vs. run the top level script on its own.

**Comment by StefanKarpinski** [comment]
I'm not sure if this is the intention, but the way this discussion is going, this is not going to get merged and we will just live with the status quo for the rest of the Julia 1.x timeframe.

**Comment by stevengj** [comment]
> My concern was code that behaves differently when [ REPL vs `include` ]

Yes, but currently code behaves differently in the REPL vs in a function body, in a way that makes interactive code much harder to write, especially in non-computer-science contexts, as has been discussed extensively.

There is **no non-breaking solution here that will be completely consistent.** There is no perfect solution, only different tradeoffs.  But I think making the REPL more usable, and interactive code more like code in a function body, is a better tradeoff here.

**Comment by jlperla** [comment]
> There is **no non-breaking solution here that will be completely consistent.**
> I'm not sure if this is the intention, but the way this discussion is going, this is not going to get merged and we will just live with the status quo for the rest of the Julia 1.x timeframe.

Why not accelerate the Julia 2.x timeframe as the next release, where this can be done right and consistent across all setups, and other minor breaking changes that have queued up can be implemented?  Julia 2.x doesn't have to be a massive release...  If there is no way to fix something with a non-breaking change, then make it a breaking change.

**Comment by stevengj** [comment]
> Why not accelerate the Julia 2.x timeframe as the next release,

That opens up a huge can of worms of instabilities that everyone was hoping was behind them.  I don't think it's worth it just to erase a minor difference between interactive and file scopes.

**Comment by StefanKarpinski** [comment]
> Why not accelerate the Julia 2.x timeframe as the next release, where this can be done right and consistent across all setups

You're assuming that this isn't the best option. Personally, I think this with the warning I mentioned above is pretty much an ideal solution: the REPL is convenient and works closely enough to a function body to make cut-and-paste debugging work; if anyone takes code from a function body or the REPL and puts it in a file that doesn't do the soft scope thing, they get a warning that tells them how to fix it. The same warning tells someone that writes `t = 0; for i = 1:n; t += i; end` in a script that they need to either declare `t` to be local or global depending on what they want.

**Comment by MasonProtter** [comment]
Can the warning be resolved at macroexpansion time? Would it be likely to have a negligible overhead? 

As long as it doesn't cost us anything to do and it's robust across many inputs, such a warning would mostly cancel my concerns about the change.

**Comment by jlperla** [comment]
Here is the scenario:  a new (non-programmer) user writes code in Jupyter, it works great and scoping is completely intuitive.  They copy and past the code to a `.jl` file and start editing it with Atom/VScode/emacs/etc., which all use the REPL to execute code.  Works great and is completely intuitive and consistent with Jupyter and code inside of functions.

Then, suddenly when they try to `include` the code, execute it from command-line, or execute it with `] test`, it puts up a warning - which they might not even notice... and has different behavior.

> You're assuming that this isn't the best option.

Yes, that is my assumption.  It just doesn't smell right to have Jupyter + REPL + Atom + VScode having different behavior than `include` (and the inconsitency didn't exist in v0.6).

But maybe it is just me.  Right now Jupyter is inconsistent with REPL and the IDEs use the repl, so perhaps a half-step to get it consistent with the REPL and `shift-enter` in the IDEs is less confusing than I think.

**Comment by JeffBezanson** [comment]
The warning could be done at lowering time and would not affect execution. Of course, it's possible somebody might *want* the warning at run time instead (e.g. if the offending block of code is disabled with `if false` or something), but we don't have to do it that way.

**Comment by MasonProtter** [comment]
> The warning could be done at lowering time and would not affect execution.

Excuse my ignorance, but does that mean that if there was offending code in a package, the warning would be emitted during pre-compilation? 

I'm just trying to figure out if this can be done in such a way that it doesn't add meaningful overhead to macroexpansion / compile times, but also gets emitted at a useful phase.

**Comment by JeffBezanson** [comment]
Yes it would be during precompilation. The overhead would be negligible; just the time to print the warning itself basically.

**Comment by StefanKarpinski** [comment]
@jlperla: your requirements seem to only be satisfied by the 0.6 behavior; there were good reasons for changing that which have been explained repeatedly, and which are no less valid now than when we changed it. Moreover scope behavior in scripts is simply not eligible for changing until Julia 2.0. The immediate options are:

1. Make this change;
2. Leave everything as is.

I get that you want something else entirely, but that is not an option. Arguing against this PR is implicitly a vote for leaving things as they currently are.

**Comment by JeffBezanson** [comment]
I gather this might be more agreeable if we immediately also provide a way to opt-in to this behavior inside files. Then if you just add that annotation, you have the full 0.6 behavior back. (The warning could also be added instead of, or in addition to, that.)

**Comment by jlperla** [comment]
>  Moreover scope behavior in scripts is simply not eligible for changing until Julia 2.0. 

Yes, I fully understand that.  In my mind, we are better off not making another source of confusion for people (i.e. the difference between executing a script with shift-enter vs. executing all at once).  Right now, we have one fully intuitive interactive environment (jupyter) which is isolated and consistent with how code in functions work, and other (the world of scripts through Atom with shift-enter) which is different but at least consistent regardless of how you execute the script.  What you are proposing would make scripts executed in all of the IDEs inconsistent with running them outside of the IDE.

Others, such as @stevengj, can disagree with me and say that a 1/2 step towards consistency is worthwhile.  And they might be right.

That said: my mind completely changes if there is a way to put in a macro (`@softscope`) or whatever so that scripts operate consistently with shift-enter as well as `include`.  It is OK if tagging consistency is a manual step.

Alternatively, instead of a macro, there could be a softscope include (which could be used inside of `] test` scripts or when using `julia -e `include(myscript.jl, softscope=true)` etc. and we could tell people to use that for constency.  This sort of option seems to be what @tpapp was hinting at for `include` as well, so emacs wouldn't break.

**Comment by jlperla** [comment]
> I gather this might be more agreeable if we immediately also provide a way to opt-in to this behavior inside files. Then if you just add that annotation, you have the full 0.6 behavior back. (The warning could also be added instead of, or in addition to, that.)

Yes.  100%.

**Comment by tpapp** [comment]
> provide a way to opt-in to this behavior inside files

My biggest concern about solutions like that and this PR in general is that the very same Julia code could suddenly have different semantics, depending on whether it was typed into the REPL, `include`d, and (with this suggestion) potentially depending on annotation inside files.

I agree with @stevengj about there being [different trade-offs](https://github.com/JuliaLang/julia/pull/33864#issuecomment-573859527) here. I do not have the expectation that code at toplevel and inside functions should behave the same, because I can usually recognize each context easily; but I write "script" code in files which may be directly sent to the REPL piecewise or `include`d, and being able to treat the two as interchangeable is valuable to me. Having to pay attention to annotation at the beginning of the file would complicate this further.

**Comment by WenjieZ** [comment]
@jlperla From deep in your heart, you want [this](https://discourse.julialang.org/t/remove-the-soft-scope-altogether-and-make-it-global/33333).

**Comment by antoine-levitt** [comment]
I want to emphasize @tpapp 's point above. I don't expect code to behave similarly at the REPL/toplevel and in functions, but I do expect it to behave similarly in the REPL and in include files. Of course that's just my own biased set of expectations, but I would imagine these are shared by a lot of users.

I think there's a consensus that a warning would be a good thing, so this should be done regardless of what the decision here is.

**Comment by StefanKarpinski** [comment]
I want to point out that with my proposed warning, there's no change to semantics unless there's also a warning when running the code not in the REPL. The warning would occur in precisely the case where the soft scope rule would make a variable assigned in a loop global rather than local. In fact, the same detection logic would apply and just do something different: in the REPL, it would make the assigned variable global rather than local; elsewhere, it leave the variable local but emit a warning. So if you don't get warning, there's guaranteed to be no difference in behavior.

Then the question is: _is this warning acceptable?_ My position is: _yes, because this only occurs if the programmer is doing something very confusing that they should not do._ Specifically, they are using the same name for a global variable and top-level local loop variable (without explicitly declaring it with `local`). How does one avoid this warning? One solution is to use the `local` keyword to explicitly declare the local as such, but even better is to rename the local variable to something that doesn't shadow the global. Here, again, is code that would warn outside of the REPL:
```jl
x = 123

for i in itr
    x = "hi there" # oops: local or global?
    # use it locally
end

y = x + 456
```
This is bad code. You should not write this ever. The warning forces you to fix it in one of two ways.
One possible way to write this to avoid the warning:
```jl
x = 123

for i in itr
    a = "hi there" # different local variable name, not `x`
    # use it locally
end

y = x + 456
```
See? That was easy and much clearer. Another way to fix it would be:
```jl
x = 123

for i in itr
    local x = "hi there" # explicitly local not global
    # use it locally
end

y = x + 456
```
That's also much clearer—now it's completely obvious to anyone writing this code that the `x` that is assigned in the loop is local to that loop. No ambiguity.

Adding this warning amounts to enforcing what would be good style anyway: _don't use the same name for a global and a top-level local._ Just follow this simple rule and you'll never have code that emits this warning and you'll always be able to cut-and-paste your code into the REPL and have it work the exact same way. Forget the rule? No problem, you'll get a warning to remind you.

**Comment by tpapp** [comment]
@StefanKarpinski: I wonder if we could just get the warning *without any change in the semantics* first, as an experiment? Eg in 1.4 or 1.5.

It would be absolutely non-breaking, help new users adapting to Julia, clear up a lot of the confusion, and prepare for the ground for the (minor) semantic change if this PR is merged in another release. In case it isn't, the warning provides guidance on good style.

**Comment by jlperla** [comment]
> @jlperla From deep in your heart, you want this.

@WenjieZ  I think they considered this before.  Python's scoping (with leaky scopes in loops and comprehensions) is strictly worse than either v0.6 or v0.7 julia and would be massively breaking.

My guess is that, given the amount of time Stefan and Jeff have spent on exhausting the design space, they may have found the only local optima:  v0.6 and v0.7 scoping rules.  Reasonable people can apply different weights on the tradeoffs to argue which is the global optima, but neither is perfect.  My own preferences are to significantly upweight tradeoffs which effect new users vs. seasoned users (and hence v0.6 rules win for me, as I have never seen any new users complain about IJulia scoping).  The proposed repl change, if it had a `include(myscript.jl, softscope = true)` or whatever opt-in for scripts) seems an attempt to have a  non-breaking way of bringing v0.6 back optionally... for better or (potentially) worse.

While I doubt that we will get anything better than the two local optima, I think there is a chance that by adding a new dimension (e.g. an additional scoping level distinct from global, such as one for first-class scripts like Matlab) a new global optima could be found.  I tried to suggest one above in this issue as a strawman, but it was ultimately a failure.  Regardless, it is a v2.0 discussion.

**Comment by vtjnash** [comment]
> I wonder if we could just get the warning without any change in the semantics first, as an experiment?

We've had that situation before. It was called v0.7, and was pretty much the worst possible combination of options. It combined all the worst aspects of implicitly globals and additionally required explicit locals. It was rather painful to make our test suite run with these restrictions (since in every case we wanted new the 1.0 behavior, but had to explicitly opt out of the warning anyways).

> this only occurs if the programmer is doing something very confusing that they should not do. Specifically, they are using the same name for a global variable and top-level local loop variable (without explicitly declaring it with local)

This makes it sound like we've never tried the v0.6 scoping rules before and got experience with how they work out when used for files. But in fact, this was a significant contributor to CI failures several versions ago. I tried (and failed) several times to make the tests reliable with the old scope rules, but the state dependence of them made that a herculean task. We eventually put in a number of mitigations by v0.6 such that it was, by then, only a minor cause of failures. The eventual change to the current scoping rules were a direct result of wanting to eliminate that problem.

> I think they considered this before. Python's scoping (with leaky scopes in loops and comprehensions) is strictly worse

It was considered, but I don't think anyone claimed it was any worse. I think the conclusion was just, relative to the status quo, it would be more complicated to explain (though perhaps less complex than this PR).

**Comment by WenjieZ** [comment]
I support this PR.

@JeffBezanson Please also add this feature to Juno's shift+enter and ctrl+enter.

**Comment by StefanKarpinski** [comment]
@WenjieZ, that's up to the Juno developers, but it should be easy after this PR.

**Comment by JeffBezanson** [comment]
Some updates:
- added a warning plus command line option to control it
- made `let` always a hard scope, and added it to testsets

File: src/jloptions.c [hunk 3]
```diff
@@ -109,7 +110,8 @@ static const char opts[]  =
 
     // error and warning options
     " --depwarn={yes|no|error}  Enable or disable syntax and method deprecation warnings (\"error\" turns warnings into errors)\n"
-    " --warn-overwrite={yes|no} Enable or disable method overwrite warnings\n\n"
+    " --warn-overwrite={yes|no} Enable or disable method overwrite warnings\n"
+    " --warn-scope={yes|no}     Enable or disable warning for ambiguous top-level scope\n\n"
```
Comment (StefanKarpinski) [inline src/jloptions.c]: Maybe `yes|no|error` so people can opt into making this fatal?

**Comment by StefanKarpinski** [comment]
Seems like there's a mismatch between shortopts and longopts. Man, that's really an awkward interface to keep in sync. Tried looking at it to see if I could fix but didn't figure it out.

File: src/jloptions.c (hunk 3 above)
Comment (StefanKarpinski) [reply src/jloptions.c]: Can also be added later.

**Comment by StefanKarpinski** [comment]
Yeah, I do not understand the option parsing code anymore. Somehow this change is causing the first branch of this code to get called instead of the second branch when the `--inline` option is passed without an argument:
```jl
if (strchr(shortopts, o->val)) {
    jl_errorf("option `-%c/--%s` is missing an argument", o->val, o->name);
}
else {
    jl_errorf("option `--%s` is missing an argument", o->name);
}
```
But `o->val` ought to be `opt_inline` as far as I can tell, but what's being printed is `:`. Strange.

**Comment by StefanKarpinski** [comment]
Ok, turns out it's a bug (a long standing one): I would assume since `strchr` takes its needle argument as `int c` that it would just return `null` when the needle is not a valid byte value, but that's not the case: it searches for `(char) c` instead. In this case `o->val` is 314 which just happens to have the property that `':' == (char) o->val`. I pushed a commit that checks if `o->val` is a valid `char` value first, which fixes this issue.

**Comment by StefanKarpinski** [comment]
Win32 failure is the usual temp file non-uniqueness.

**Comment by StefanKarpinski** [comment]
Rebased onto current master to fix the Windows tempfile collision issue and to move the option parsing fix earlier so that we don't have a broken commit in when bisecting.

**Comment by Keno** [comment]
> I pushed a commit that checks if `o->val` is a valid `char` value first, which fixes this issue.

Cherry-pick this onto master so we don't forget it even if this branch gets munged around?

**Comment by StefanKarpinski** [comment]
Made a separate PR: https://github.com/JuliaLang/julia/pull/34432.

**Comment by StefanKarpinski** [comment]
Any idea why the tests aren't running?

File: src/ast.c [hunk 4]
```diff
@@ -131,13 +131,34 @@ static jl_value_t *scm_to_julia(fl_context_t *fl_ctx, value_t e, jl_module_t *mo
...
 static jl_value_t *jl_expand_macros(jl_value_t *expr, jl_module_t *inmodule, struct macroctx_stack *macroctx, int onelevel);
 
+value_t fl_defined_julia_global(fl_context_t *fl_ctx, value_t *args, uint32_t nargs)
+{
+    // tells whether a var is defined in and *by* the current module
+    argcount(fl_ctx, "defined-julia-global", nargs, 1);
+    (void)tosymbol(fl_ctx, args[0], "defined-julia-global");
+    jl_ast_context_t *ctx = jl_ast_ctx(fl_ctx);
+    jl_sym_t *var = jl_symbol(symbol_name(fl_ctx, args[0]));
+    jl_binding_t *b = jl_get_module_binding(ctx->module, var);
```
Comment (vtjnash) [inline src/ast.c]: needs thread safety

File: src/julia-syntax.scm [hunk 5]
```diff
@@ -2591,27 +2645,53 @@
...
         (else
+         (if (and (eq? (car e) '=) (symbol? (cadr e))
+                  scope (null? (lam:vars (scope:lam scope)))
+                  (warn-var?! (cadr e) scope)
+                  (= *scopewarn-opt* 1))
+             (let* ((v    (cadr e))
+                    (loc  (extract-line-file loc))
+                    (line (if (= (car loc) 0) (julia-current-line) (car loc)))
+                    (file (if (eq? (cadr loc) 'none) (julia-current-file) (cadr loc))))
+               (julia-logmsg
```
Comment (vtjnash) [inline src/julia-syntax.scm]: This file should not be doing IO

**Review by vtjnash — COMMENTED** [review]
transferring review comments from #34383

+1 to seeing `let` remain unaffected by this change

Should we re-run the PkgEval test with this less breaking version now?

File: src/ast.c (hunk 4 above)
Comment (JeffBezanson) [reply src/ast.c]: `jl_get_module_binding` is locked. This seems ok to me now.

File: src/julia-syntax.scm (hunk 5 above)
Comment (JeffBezanson) [reply src/julia-syntax.scm]: Well, this is how we did deprecation warnings. I'm sympathetic to not wanting side effects during lowering, but the alternative seems pretty complex. We can't just move it to run time since we don't want the warning more than once. So `eval` would have to search for this within an expression first, plus the rest of the compiler would have to be able to handle the new form. Is that really worth it?

**Comment by StefanKarpinski** [comment]
So merge this or try PkgEval run on a branch where the warning is an error?

File: src/julia-syntax.scm (hunk 5 above)
Comment (vtjnash) [reply src/julia-syntax.scm]: Yeah, we said it was a bad idea then, but was only going to be used in v0.7 and future code wouldn't have any warnings so we didn't bother trying to implement it any better. The thinking was that if someone wanted to be adding warnings again, it should be kinda hard 😝. But since the compiler already does that pre-processing step, it shouldn't be that hard (though ideally perhaps, lowering would just put it in a top-most first-statement position—but if that's awkward to implement right now, I don't think it has any actual benefits).

**Comment by JeffBezanson** [comment]
OK I implemented a scheme wherein all existing lowering entry points are effect free, and warnings are only printed when loading files or calling `eval` (where we know we're going to eval right after anyway).

File: src/jloptions.c [hunk 6]
```diff
@@ -556,6 +560,14 @@ JL_DLLEXPORT void jl_parse_opts(int *argcp, char ***argvp)
             else
                 jl_errorf("julia: invalid argument to --warn-overwrite={yes|no|} (%s)", optarg);
             break;
+        case opt_warn_scope:
+            if (!strcmp(optarg,"yes"))
+                jl_options.warn_scope = JL_OPTIONS_WARN_SCOPE_ON;
+            else if (!strcmp(optarg,"no"))
+                jl_options.warn_scope = JL_OPTIONS_WARN_SCOPE_OFF;
+            else
+                jl_errorf("julia: invalid argument to --warn-scope={yes|no|} (%s)", optarg);
```
Comment (StefanKarpinski) [inline src/jloptions.c]:
```suggestion
                jl_errorf("julia: invalid argument to --warn-scope={yes|no} (%s)", optarg);
```

File: stdlib/REPL/src/REPL.jl [hunk 7]
```diff
@@ -73,6 +73,24 @@ mutable struct REPLBackend
...
+        elseif h in (:meta, :import, :using, :export, :module, :error, :incomplete, :thunk)
+            return ex
+        else
+            return Expr(:block, Expr(:softscope, true), ex)
+        end
+    end
+    return ex
+end
+
+const repl_ast_transforms = Any[softscope!]
```
Comment (stevengj) [inline stdlib/REPL/src/REPL.jl]: Hopefully, this will allow OhMyREPL.jl and Revise.jl and other packages that require REPL hooks to play nicely, since they can just push new transforms to `REPL.repl_ast_transforms`.   But I'm not sure if it should be a global variable or should be a property specific to a REPL instance?

See also the discussion in stevengj/SoftGlobalScope.jl#2; cc @dawbarton, @KristofferC, @timholy.

Comment (StefanKarpinski) [reply stdlib/REPL/src/REPL.jl]: Does seem like it should be per-REPL-instance.

**Comment by StefanKarpinski** [comment]
Windows failures are the known and unrelated temp directory capitalization issue.

File: doc/src/manual/variables-and-scoping.md [hunk 8]
```diff
@@ -1,33 +1,36 @@
...
-interactive prompt (REPL)                         | global | global
-(mutable) [`struct`](@ref), [`macro`](@ref)       | local  | global
-[`for`](@ref), [`while`](@ref), [`try-catch-finally`](@ref try), [`let`](@ref) |local | global or local
-functions (either syntax, anonymous & do-blocks) | local | global or local
-comprehensions, broadcast-fusing                 | local | global or local
+The constructs introducing scope blocks are:
+
+Construct | Scope type | Allowed within
+--------- | ---------  |---------------
+files, REPL (i.e. `Main` module), [`module`](@ref), [`baremodule`](@ref) | global | global
```
Comment (JeffBezanson) [inline doc/src/manual/variables-and-scoping.md]: I would not mention files or the REPL here, since neither delimit scope blocks. A file doesn't get its own scope.

Comment (StefanKarpinski) [reply doc/src/manual/variables-and-scoping.md]: Fair point, it was in there before so I left it, but happy to delete.

File: doc/src/manual/variables-and-scoping.md [hunk 9]
```diff
@@ -52,15 +55,21 @@ julia> Bar.foo()
...
 
-Each module introduces a new global scope, separate from the global scope of all other modules;
-there is no all-encompassing global scope. Modules can introduce variables of other modules into
-their scope through the [using or import](@ref modules) statements or through qualified access using the
-dot-notation, i.e. each module is a so-called *namespace*. Note that variable bindings can only
-be changed within their global scope and not from an outside module.
+Each module introduces a new global scope, separate from the global scope of all other modules—there
+is no all-encompassing global scope. Modules can introduce variables of other modules into their
+scope through the [using or import](@ref modules) statements or through qualified access using the
+dot-notation, i.e. each module is a so-called *namespace* which means it is a first-class data
```
Comment (JeffBezanson) [inline doc/src/manual/variables-and-scoping.md]: I don't think "namespace" implies first-class-ness; for example C++ namespaces are not first class.

File: doc/src/manual/variables-and-scoping.md [hunk 10]
```diff
@@ -93,244 +102,356 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
+    for i = 1:n
+        s = s + i # assigns existing local
+    end
+    return s # same local
+end
 ```
 
-The location of both the `local` and `global` keywords within the scope block is irrelevant.
-The following is equivalent to the last example (although stylistically worse):
+As in the previous example, the first assignment to `t` at the top of `sum_to` causes `s` to be a
```
Comment (JeffBezanson) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
As in the previous example, the first assignment to `s` at the top of `sum_to` causes `s` to be a
```

File: doc/src/manual/variables-and-scoping.md [hunk 11]
```diff
@@ -93,244 +102,356 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
-           function bar()
-               x = 10       # modifies the parent's x
-               return x + y # y is global
-           end
-           return bar() + x # 12 + 10 (x is modified in call of bar())
-       end;
-
-julia> baz()
-22
+Since there global `x` is not defined when the for loop is evaluated, the first clause of the soft
```
Comment (JeffBezanson) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
Since the global `x` is not defined when the for loop is evaluated, the first clause of the soft
```

File: doc/src/manual/variables-and-scoping.md [hunk 12]
```diff
@@ -93,244 +102,356 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
 ```jldoctest
-julia> x, y = 1, 2;
+julia> code = """
+       s = 0 # global
+       for i = 1:10
+           t = s + i # new local `t`
+           s = t # new local `s` with warning
+       end
+       s # global
+       @isdefined(t) # global
```
Comment (JeffBezanson) [inline doc/src/manual/variables-and-scoping.md]: Maybe this should be `s, @isdefined(t)`, since otherwise only the second result would ever be visible.

File: doc/src/manual/variables-and-scoping.md [hunk 13]
```diff
@@ -93,244 +102,356 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
+worked just fine, but then when someone adds a new global far away, possibly in a different file,
+the code suddenly changes meaning and either breaks noisily as in this case, or worse still, might
+break silently and just do the wrong thing. This kind of "spooky action at a distance" is the kind
+of thing good programming language designs should prevent.
+
+So in Julia 1.0, we simplified the rules for scope: in any local scope, assignment to a name that
+wasn't already a local variable created a new local variable. This eliminated the notion of soft
+scope entirely and eliminated the spooky action potential that having a global by a certain name
+previously had. We uncovered and fixed a log of bugs in the process. And there was much rejoicing!
+Well, no, not really. Because the people were angry that they now had to write:
```
Comment (JeffBezanson) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
Well, no, not really. Because some people were angry that they now had to write:
```

File: doc/src/manual/variables-and-scoping.md (hunk 9 above)
Comment (StefanKarpinski) [reply doc/src/manual/variables-and-scoping.md]: Aight, I was just trying to make more sense of what was here previously.

File: doc/src/manual/variables-and-scoping.md [hunk 14]
```diff
@@ -93,244 +102,356 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
 
 ```jldoctest
-julia> x, y = 1, 2;
+julia> code = """
+       s = 0 # global
+       for i = 1:10
+           t = s + i # new local `t`
+           s = t # new local `s` with warning
+       end
+       s # global
```
Comment (StefanKarpinski) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
       s, # global
```

File: doc/src/manual/variables-and-scoping.md (hunk 13 above)
Comment (StefanKarpinski) [reply doc/src/manual/variables-and-scoping.md]: This choice of words was very intentional 😂

File: doc/src/manual/variables-and-scoping.md [hunk 15]
```diff
@@ -93,244 +102,356 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
+
+In Julia ≤ 0.6, all global scopes did work like the current REPL: when `x = <value>` occurred in a
+loop (or try/catch, or struct body) but outside of a function body (or let block or comprehension),
+it was decided based on whether a global named `x` was defined or not whether `x` should be local to
+the loop. This behavior has the advantage of being intuitive and convenient since it approximates
+the behavior inside of a function body as closely as possible. In particular, it makes it easy to
+move code back and forth between a function body and the REPL when trying to debug the behavior of a
+function. However, it has some down sides. First, it's quite a complex behavior: many people over
+the years were confused about this behavior and complained that it was complicated and hard to
+understand and to explain. Fair point. Second, and arguably worse, is that it's bad for programming
```
Comment (StefanKarpinski) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
both explain and understand. Fair point. Second, and arguably worse, is that it's bad for programming
```

File: doc/src/manual/variables-and-scoping.md [hunk 16]
```diff
@@ -93,244 +102,355 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
 
-!!! sidebar "Avoiding globals"
-    Avoiding changing the value of global variables is considered by many
-    to be a programming best-practice.
-    Changing the value of a global variable can cause "action at a distance",
-    making the behavior of a program harder to reason about.
-    This is why the scope blocks that introduce local scope require the `global`
-    keyword to declare the intent to modify a global variable.
+Let's move onto some more ambiguous cases covered by the soft scope rule. We'll explore this by
+extracting the bodies of the `greet`  and `sum_to` into soft scope contexts. First, let's put the
```
Comment (StefanKarpinski) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
extracting the bodies of the `greet`  and `sum_to′` into soft scope contexts. First, let's put the
```

File: doc/src/manual/variables-and-scoping.md [hunk 17]
```diff
@@ -93,244 +102,355 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
+false
 ```
 
-See also the closures in the examples in the next two sections. A variable,
-such as `x` in the first example and `state` in the second, that is inherited
-from the enclosing scope by the inner function is sometimes called a
-*captured* variable. Captured variables can present [performance challenges
-discussed in performance tips](@ref man-performance-captured).
+The REPL approximates being in the body of a function by deciding whether assignment inside the loop
+assigns to a global  or creates new local based on whether a global variable by that name is defined
```
Comment (StefanKarpinski) [inline doc/src/manual/variables-and-scoping.md]:
```suggestion
assigns to a global or creates new local based on whether a global variable by that name is defined
```

File: stdlib/REPL/src/REPL.jl (hunk 7 above)
Comment (JeffBezanson) [reply stdlib/REPL/src/REPL.jl]: I agree it should be per-REPL, but I'm not sure how to implement it. E.g. `LineEditREPL` does not directly contain a `REPLBackend`, so passing around which transforms to use is nontrivial. Hopefully somebody can help with that later.

**Comment by JeffBezanson** [comment]
Ready to merge I think.

**Comment by rapus95** [comment]
Nothing to add about the decision, just asking:
Might you write a blogpost about the new behaviour and how it is implemented internally?
 1. Is it still implemented by some :softscope AST-nodes?
 2. Is it possible/intended to be able to hook into the decision of the scoping system (for example by transforming the AST manually)?
 3. Is it in a shape that current tooling (especially juno & vscode) can help exploring which scoping is used in which position? -> Something like code blocks being highlighted if they are evaluated in softglobalscope etc.?

File: doc/src/manual/variables-and-scoping.md [hunk 18]
```diff
@@ -93,244 +102,359 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
 ```
 
-This behavior may seem slightly odd for a normal variable, but allows for named functions -- which
-are just normal variables holding function objects -- to be used before they are defined. This
-allows functions to be defined in whatever order is intuitive and convenient, rather than forcing
-bottom up ordering or requiring forward declarations, as long as they are defined by the time
-they are actually called. As an example, here is an inefficient, mutually recursive way to test
-if positive integers are even or odd:
+Do you see that `global` annotation in there? Hideous. Obviously this situation could not be
+tolerated. But seriously, there are two main issues with requiring `global` for this kind of
```
[the remark this answers is not in the document]
Comment (StefanKarpinski) [reply doc/src/manual/variables-and-scoping.md]: A mild saltiness about this process seems earned at this point. Someone else can water it down later.

File: doc/src/manual/variables-and-scoping.md [hunk 19]
```diff
@@ -93,244 +102,359 @@ Note that the interactive prompt (aka REPL) is in the global scope of the module
...
+        s = s + i # assign existing local
+    end
+    return s # same local
+end
 ```
 
-The location of both the `local` and `global` keywords within the scope block is irrelevant.
-The following is equivalent to the last example (although stylistically worse):
+As in the previous example, the first assignment to `s` at the top of `sum_to` causes `s` to be a
+new local variable in the body of the function. The for loop has its own inner local scope within
```
[the remark this answers is not in the document]
Comment (StefanKarpinski) [reply doc/src/manual/variables-and-scoping.md]: I've been not putting the `for` or `while` descriptor of a loop in backticks here pretty consistently.

File: doc/src/manual/variables-and-scoping.md (hunk 18 above)
[the remark this answers is not in the document]
Comment (rfourquet) [reply doc/src/manual/variables-and-scoping.md]: Fair enough :)

**Comment by JeffBezanson** [comment]
@rapus95 
1. Yes
2. Yes; the function `softscope!` in the REPL transforms a top-level expression so that it will be evaluated with soft scope. If you don't call it, you get the normal 1.x behavior.
3. Nothing in the code itself indicates whether it will be evaluated with soft scope; it's an external decision. It seems like the most useful thing would be to highlight ambiguous assignments that will trigger a warning.

**Comment by rapus95** [comment]
@JeffBezanson So if I understand it correctly, there are some signs in the AST (according to 1.) but the only way to use them for 3. would be to create a hook which the AST will be passed to when it already holds the corresponding nodes. Is that possible/Is there a step in the compilation pipeline in which those will always be visible if set?

**Comment by vtjnash** [comment]
> Is it in a shape that current tooling (especially juno & vscode) can help exploring which scoping is used in which position?

This seems like it'd be the main reason to further alter this code and lift the warning outside of flisp entirely. It's already nearly there now, there's just not an API to separately access the list of warnings (either they get immediately printed or they get discarded). Probably doesn't really affect this PR right now, since that's largely just an internal question. But some REPLs in Base currently do explicitly separate the calls to `Core.eval(Meta.lower(Meta.parse(code)))`, I'm guessing as a way to separate the source of warnings and errors between stages (parse / macros / lowering / eval / show)—though it doesn't end up reporting them any differently right now.

**Comment by JeffBezanson** [comment]
> Is that possible/Is there a step in the compilation pipeline in which those will always be visible if set?

I don't think this is the right question --- the interactive front-end is what decides whether to add the `:softscope` annotation, so it already knows whether it has been added.

**Comment by StefanKarpinski** [comment]
OMG, finally.

**Comment by AzamatB** [comment]
This messed up the sections of the documentation that it modified. E.g.:
Screen Shot 2020-01-29 at 4 00 33 AM

**Comment by StefanKarpinski** [comment]
There's a space in front of one of the closing triple backticks which most markdown implementations seem to be fine with but Julia's built-in markdown parser doesn't like. I've added a fix to https://github.com/JuliaLang/julia/pull/34558.

**Comment by rapus95** [comment]
> I don't think this is the right question --- the interactive front-end is what decides whether to add the `:softscope` annotation, so it already knows whether it has been added.

Well sure, if the frontend is what does the analysis that works well. But what I was referring to is that then, there is no passive way to observe the scoping without actually influencing it. Feels like quantum behaviour. 😁 But as it is escalating into nonsense now, I might rather wait for solutions/ideas to come up in the tooling of Julia before asking such questions. Thanks!

**Comment by JeffBezanson** [comment]
What analysis? Given an expression, you either add `softscope` to it or you don't, before handing it to the compiler. If you don't add it, you get the default 1.0 behavior, so if you don't touch anything it's safe to assume that.

**Comment by StefanKarpinski** [comment]
I think the analysis he means is which assignments may be ambiguous.

**Comment by KristofferC** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by WenjieZ** [comment]
That was definitely not a question. It was an opinion. 

Not everyone subscribing this issue is on discourse, so I feel fine to get notified and learn that this issue is not forgotten, yet.

**Comment by KristofferC** [comment]
This is not the correct place for this discussion. Again, please continue on https://discourse.julialang.org/.

**Comment by vtjnash** [comment]
> Since when did for loops start to have separate scopes?

They always did. Though this was a common misunderstanding prior to this change, because of some special toplevel rules that sometimes could make it appear as if they did not.

**Comment by StefanKarpinski** [comment]
If anyone wants to discuss this further, they can do so on [discourse](httsp://discourse.julialang.org/).
