### PR TITLE
fix return value of `typeinf_code` for `code == nothing`

### LINKED ISSUE #20067: code_typed bounds error
I'm on Julia Version `0.6.0-dev.2005`.
Seems like sometimes `Core.Inference.typeinf_code` returns a tuple with 2 elements, instead of 3, generating a bounds error with code_typed!
https://github.com/JuliaLang/julia/blob/master/base/reflection.jl#L644
```Julia
# DataType seems to be too unspecific, with Type{Vec{2, Int}} it works
code_typed(some_generated_function, (DataType, Int,))
```
If you actually need the correct function call, I can try to make a minimal example.
@vtjnash, I figure you might be involved in this ;)

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #20067

@SimonDanisch what was the example that triggered this? Would be good as a test case.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
that seems to do it:
```Julia
@generated function construct_similar{FSA <: Tuple}(::Type{FSA}, elements::Tuple)
           :(FSA)
end
code_typed(construct_similar, (DataType, Tuple{Int, Int}))
```

**Comment by SimonDanisch** [comment]
thanks! :)

**Comment by vtjnash** [comment]
Is it possible to trigger this without `DataType`? That's a different error.

**Comment by vchuravy** [comment]
I seem to be only able to trigger that code-path with `DataType`.

**Comment by vchuravy** [comment]
@vtjnash ok to merge?

File: test/inference.jl [hunk 1]
```diff
@@ -494,3 +494,9 @@ immutable MyType18457{T,F,G}<:AbstractMyType18457{T,F,G} end
 tpara18457{I}(::Type{AbstractMyType18457{I}}) = I
 tpara18457{A<:AbstractMyType18457}(::Type{A}) = tpara18457(supertype(A))
 @test tpara18457(MyType18457{true}) === true
+
+# Issue 20067
+@generated function foo20067{T <: Tuple}(::Type{T}, elements::Tuple)
+           :(T)
+end
+code_typed(DevNull, foo20067, (DataType, Tuple{Int, Int}))
```
Comment (JeffBezanson) [inline test/inference.jl]: There is no 3-argument `code_typed`. Unfortunately this test failure was masked by #20027.
It would also be better if there were a `@test` in here.

Comment (JeffBezanson) [inline test/inference.jl]: Inference also fails here, I believe because it doesn't want to call the generated function on an abstract type (`Type{T} where T<:Tuple`).

Comment (vchuravy) [inline test/inference.jl]: Sorry about, that, I noticed that and then promptly forgot to fix it...
It might be best to remove the test for now. #20146
