### PR TITLE
compiler type fixes

### LINKED ISSUE #34834: Unknown hang-up in v1.3.1
Julia v1.3.1 hangs when running the following call of `pickvarnames(:(a + b))`:
```
pickvarnames(ex::Symbol) = ex

function pickvarnames(ex::Expr)
    varnames = ()
    if ex.head == :call
        for arg in ex.args[2:end]
            varnames = (varnames..., pickvarnames(arg) )
        end
    end
    return varnames
end

julia> pickvarnames(:a)
:a

julia> pickvarnames(:(a + b) )  # Hangs!
Killed: 9
```
this issue was original discussed in [discourse](https://discourse.julialang.org/t/unknown-hang-up-in-v1-3-1/34912.
so far, the actual cause of hanging is mysterious. knowledge collected so far are:
1. it hangs in v1.3, v1.2, v0.7 and v1.4 master. But v0.6 has no problem.
2. using `Vector{Symbol}` instead of `Tuple` avoids hanging. (i.e. `varnames = []` and `varnames = [varnames..., pickvarnames(arg) ]`.

### PR DESCRIPTION
**Pull request by vtjnash**
`tmerge` was ignoring the limits on type-size if the early-return tests completed. add that check in and fix other isseus encountered along the way.

fixes #34834

### CODE REVIEW

**Comment by Keno** [comment]
codegen changes look good to me. I'll leave the inference lattice considerations to @JeffBezanson

File: base/compiler/typelimits.jl [hunk 1]
```diff
@@ -266,13 +268,21 @@ function type_more_complex(@nospecialize(t), @nospecialize(c), sources::SimpleVe
     return true
 end
 
+function isnarrowenoughtype(@nospecialize t)
```
Comment (JeffBezanson) [inline base/compiler/typelimits.jl]:
```suggestion
function issimpleenoughtype(@nospecialize t)
```

**Comment by vtjnash** [comment]
@nanosoldier `runtests(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34876#issuecomment-592034730) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/b685d5a385dd08fdad6d64eca14388c08d84485d/pkgeval/by_hash/5d3cd1a_vs_f0636b2/report.md). cc @maleadt

**Comment by vtjnash** [comment]
We should probably start filing bug reports for the 19 packages here with bad tests. But these two are probably interesting / related:
```
Test duration exceeded the time limit:
KrylovKit v0.4.1 vs. KrylovKit v0.4.1 (successful)
OhMyREPL v0.5.4 vs. OhMyREPL v0.5.4 (successful)
```

**Comment by vtjnash** [comment]
@nanosoldier runtests("KrylovKit" || "OhMyREPL", vs=":master")

**Comment by maleadt** [comment]
That doesn't look like valid submission syntax; copying from the report:

@nanosoldier `runtests(["KrylovKit", "OhMyREPL"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34876#issuecomment-594433605) has completed - no new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/ea58e86cb67ae80c507c468cfed1178b68e47489/pkgeval/by_hash/dc8d885_vs_0e8143e/report.md). cc @maleadt
