### PR TITLE
fix bug in allunique(::StepRangeLen)

### LINKED ISSUE #34997: allunique(('a':1:'c')[1:2]) errors
I didn't find a bug report for this elsewhere. I'm on 1.3.1 with Mac OS Catalina

```julia
julia> allunique(('a':1:'c')[1:2])
ERROR: MethodError: no method matching zero(::Type{Char})
Closest candidates are:
  zero(::Type{Missing}) at missing.jl:103
  zero(::Type{LibGit2.GitHash}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeights.VersionWeight}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/resolve/VersionWeights.jl:19
  ...
```

### PR DESCRIPTION
**Pull request by ShriprajwalK**
Fixed #34997

### CODE REVIEW

File: test/sets.jl [hunk 1]
```diff
@@ -452,6 +452,7 @@ end
     @test allunique(7:-1:1)       # negative step
     @test allunique(Date(2018, 8, 7):Day(1):Date(2018, 8, 11))  # JuliaCon 2018
     @test allunique(DateTime(2018, 8, 7):Hour(1):DateTime(2018, 8, 11))
+    @test allunique(('a':1:'c')[1:2]) == true
```
Comment (rfourquet) [inline test/sets.jl]: I would use `'a':'\x01':'b'` instead of (or in addition to) `('a':1:'c')[1:2]`, to be sure what the test is actually testing, and doesn't depend on possible future changes of the result type of `('a':1:'c')[1:2]`.

Comment (StefanKarpinski) [reply test/sets.jl]: Wouldn't that still error even after this change? Since the step type is `Char` which correctly does not have a zero element and also is not a valid step type. Perhaps I'm misunderstanding the suggestion.

Comment (rfourquet) [reply test/sets.jl]: Oh I got it wrong. I don't fully understand what happens here, but I just did:
```
julia> ('a':1:'c')[1:2]
'a':'\x01':'b'
```
And assumed `allunique('a':'\x01':'b')` was the problem, but `'a':'\x01':'b'` is actually not valid input:
```julia
julia> 'a':'\x01':'b'
ERROR: MethodError: no method matching zero(::Char)
```
Forget my comment above and carry on, though there might be a problem with the printing of `('a':1:'c')[1:2]`.

**Comment by ShriprajwalK** [comment]
What changes do I do to make this PR better?

**Comment by rfourquet** [comment]
Thanks!

File: test/sets.jl (hunk 1 above)
Comment (rfourquet) [reply test/sets.jl]: Ok, I found the source of the confusion: until very recently, `step(::StepRangeLen)` was returning a `Char`, hence the output above `'a':'\x01':'b'`, now `step` properly doesn't convert the step to `Char` (cf. #34412), and keeps it as an `Int`, so we now have:
```julia
julia>  ('a':1:'c')[1:2]
'a':1:'b'
```
So at least now `('a':1:'c')[1:2] == 'a':1:'b'` even though the types don't match.
