### PR TITLE
break some dependency backedges

### LINKED ISSUE #20780: Compilation time regression when extending a Base method.
One of my packages (https://github.com/KristofferC/Crayons.jl) went from 0.02 seconds load time after precompilation to ~ 1 seconds from 0.5 to 0.6. I was able to reduce it to the following:

```julia
type Crayon end

begin
tic()
Base.print_with_color(crayon::Crayon, io::IO, msg::AbstractString...) =
    Base.with_output_color(print, crayon, io, msg...)
toc()
end
```

On 0.5:
```
elapsed time: 0.015108936 seconds
```

On 0.6:
```
elapsed time: 1.109898606 seconds
```

Removing that method, load time of package goes from 0.02s to 0.04s from 0.5 to 0.6.

### PR DESCRIPTION
**Pull request by vtjnash**
This might be nicer if we had function types (so that we could declared that `function == end::Bool` for example), but this tries to at least hit a couple of the high points.

fix #20780

The main issue here was that BitArray deprecated bitwise operations, so `|` and `!` ended with a lot of  edges between anything with bitwise operations or for loops and anything required for printing warnings.

### CODE REVIEW

File: base/promotion.jl [hunk 1]
```diff
@@ -352,6 +352,6 @@ min(x::Real) = x
 max(x::Real) = x
 minmax(x::Real) = (x, x)
 
-max{T<:Real}(x::T, y::T) = ifelse(y < x, x, y)
-min{T<:Real}(x::T, y::T) = ifelse(y < x, y, x)
+max{T<:Real}(x::T, y::T) = select_value(y < x, x, y)
+min{T<:Real}(x::T, y::T) = select_value(y < x, y, x)
```
Comment (JeffBezanson) [inline base/promotion.jl]: Now that the other methods of `ifelse` are deprecated, I suppose we could replace `ifelse` and `select_value` with a single `ifelse` builtin.

**Comment by KristofferC** [comment]
With this PR, loading Crayons.jl take 0.2s instead of 1.0s as on master. Compared to 0.02s on 0.5.

File: base/deprecated.jl [hunk 2]
```diff
@@ -826,6 +826,7 @@ end
 # Deprecate vectorized !
 @deprecate(!(A::AbstractArray{Bool}), .!A) # parens for #20541
 @deprecate(!(B::BitArray), .!B) # parens for #20541
+!(::typeof(!)) = identity # make sure ! has at least 4 methods so that for-loops don't end up getting a back-edge to depwarn
```
Comment (JeffBezanson) [inline base/deprecated.jl]: I think it's a bit of a gotcha if `!!` accepts arguments that `!` doesn't. Also, not too long from now the two deprecated methods of `!` will be removed, which also removes the need for this method (IIUC), but in the meantime code could have become dependent on this behavior. So I think it would be helpful to type-restrict this.

**Review by JeffBezanson — CHANGES_REQUESTED** [review]

File: base/promotion.jl (hunk 1 above)
Comment (vtjnash) [inline base/promotion.jl]: once the deprecations get removed, that does seem to be true

File: base/deprecated.jl (hunk 2 above)
Comment (vtjnash) [inline base/deprecated.jl]: OK. I went with just creating an unused Function for this purpose

**Comment by tkelman** [comment]
it's not exactly recommended, but there are packages that defined comparison operators that return non Bool, that might get caught by these type annotations

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
If a package wants to do that, it should be able to work around this by adding methods for e.g. `!=` as well.

**Comment by tkelman** [comment]
wouldn't it have to do that for all possible subtypes of Real and Number that promotion might send through this method?

**Comment by JeffBezanson** [comment]
I see what you mean now; yes the ones on the methods that call `promote` seem too strict.

**Comment by vtjnash** [comment]
Maybe I should assert that `promote(x, y)` returns `Tuple{T, T} where T <: Real`?

**Comment by tkelman** [comment]
Is it possible to achieve the goals of this PR in another way that doesn't force promotion constraints for arbitrary user types in these fallbacks?

**Comment by vtjnash** [comment]
No. This PR is all about making sure type information can be better preserved.

**Comment by tkelman** [comment]
By imposing type-assertion constraints that we previously have not been forcing on user code, which makes this a potentially breaking change post-feature-freeze.

**Comment by vtjnash** [comment]
Ah well, it looks like that was insufficient to break that edge anyways – it's too prevalent from other code too.

**Comment by tkelman** [comment]
The version in 7be90097b2868b56280e16d3095561011db0d536 looks safer, the `!=` method could be overridden if needed as Jeff said.

I'd run nanosoldier here if I weren't currently hogging the workers elsewhere. Can keep an eye on the nightly runs.

**Comment by tkelman** [comment]
This caused a sizable regression in dates performance https://github.com/JuliaCI/BaseBenchmarkReports/blob/fe41d40a910c29c0489bd50a21458cb68701e9b8/daily_2017_3_4/report.md

**Comment by vtjnash** [comment]
Looks like that should be fixed by https://github.com/JuliaLang/julia/pull/20853. This commit had a bunch of coupled side-effects (type-assert not being effect-free meant that we were now able to generate line-number information for `!=`, but also pushed `mod` over the inlining threshold)
