### PR TITLE
[GCLowering] Fix type condition to include vector of pointers

### LINKED ISSUE #28445: Missing GC root in DecisionTrees
Reported in https://discourse.julialang.org/t/fatal-error-in-type-inference-type-bound-in-0-7-rc2

It looks like what's happening is that the root for `numPerScore` in the `bagged_tree` function is getting dropped and that array is then freed during the `createTrnValStatsForThisIteration` function, but used later.

### PR DESCRIPTION
**Pull request by Keno**
Fixes #28445

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -6675,3 +6675,23 @@ c28399 = 42
...
 @test_throws UndefVarError(:__undef_28399__) f28399()
+
+# issue #28445
+mutable struct foo28445
+    x::Int
+end
+
+@noinline make_foo28445() = (foo28445(1), foo28445(rand(1:10)), foo28445(rand(1:10)))
+@noinline function use_tuple28445(c)
+	@test isa(c[2], foo28445)
```
Comment (KristofferC) [inline test/core.jl]: tab
