### PR TITLE
Fix type_more_complex

### LINKED ISSUE #49287: type_more_complex broken for Vararg{Tuple{}} compared to another Tuple
seen at https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/5235bfb_vs_5235bfb/SPHtoGrid.primary.log
```
│  [39mInternal error: encountered unexpected error in runtime:[33m
│  [39mBoundsError(a=svec(), i=0)[33m
│  [39mijl_bounds_error_int at /source/src/rtutils.c:180[33m
│  [39mjl_f__svec_ref at /source/src/builtins.c:1633[33m
│  [39mgetindex at ./essentials.jl:741 [inlined][33m
│  [39mtype_more_complex at ./compiler/typelimits.jl:264[33m
│  [39mtype_more_complex at ./compiler/typelimits.jl:288[33m
│  [39mtype_more_complex at ./compiler/typelimits.jl:288[33m
│  [39mtype_more_complex at ./compiler/typelimits.jl:288[33m
│  [39mlimit_type_size at ./compiler/typelimits.jl:20[33m
│  [39mabstract_call_method at ./compiler/abstractinterpretation.jl:603[33m
│  [39mabstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:131[33m
```
MWE:
```
julia> Core.Compiler.type_more_complex(Tuple{Vararg{Tuple{}}}, Tuple{Vararg{Tuple}}, Core.svec(), 0, 0, 0)
ERROR: BoundsError: attempt to access Core.SimpleVector at index [0]
Stacktrace:
 [1] getindex
   @ ./essentials.jl:741 [inlined]
 [2] type_more_complex(t::Any, c::Any, sources::Core.SimpleVector, depth::Int64, tupledepth::Int64, allowed_tuplelen::Int64)
   @ Core.Compiler ./compiler/typelimits.jl:264
 [3] type_more_complex(t::Any, c::Any, sources::Core.SimpleVector, depth::Int64, tupledepth::Int64, allowed_tuplelen::Int64)
   @ Core.Compiler ./compiler/typelimits.jl:288
 [4] top-level scope
   @ REPL[11]:1
```

### PR DESCRIPTION
**Pull request by p1scescom**
Fixes #49287.
My understanding is that `type_more_complex` is a function to check that `t`(which is a Type given first arg) is more complex than `c`(which is a Type given second arg).
In my chaning,  when `t` and `c` are `DataType` and they have same name but `c`'s parameters length is longer than `t`'s it , I don't know its details and think there are some situations on it.
Also in this situation, if `c`'s end paramer is a varargtype, `c` is more complex than `t`. 

I guess this thinkig from this simple Result 
```
julia> Core.Compiler.type_more_complex(Tuple{}, Tuple, Core.svec(), 0, 0, 0)
false
```
It works on stable version julia.

I don't understand the meaning of the original code happened error.
Thus I didn't change it.

### CODE REVIEW

File: base/compiler/typelimits.jl [hunk 1]
```diff
@@ -261,7 +261,8 @@ function type_more_complex(@nospecialize(t), @nospecialize(c), sources::SimpleVe
         elseif isa(c, DataType) && t.name === c.name
             cP = c.parameters
             length(cP) < length(tP) && return true
-            length(cP) > length(tP) && !isvarargtype(tP[end]) && depth == 1 && return false
+            length(cP) > length(tP) && isvarargtype(cP[end]) && return false
```
Comment (vtjnash) [inline base/compiler/typelimits.jl:264]: I might have over-complicated the example on you, since the error will occur even if cP does not have a Vararg:
```
julia> Core.Compiler.type_more_complex(Tuple{Vararg{Tuple{}}}, Tuple{Tuple{Int,Int}}, Core.svec(), 0, 0, 0)
ERROR: BoundsError: attempt to access Core.SimpleVector at index [0]
```

I think what we need is to check again (after the unwrapva call earlier) that there are some parameters here to check:
```suggestion
             isempty(tP) && return false
```

Comment (p1scescom) [reply base/compiler/typelimits.jl:264]: You are right. And Vararg is more complex Int,Int. I rethink this function's purpose. thank you.

Comment (p1scescom) [reply base/compiler/typelimits.jl:264]: I have an question in this situation,
```
julia> Core.Compiler.type_more_complex(Tuple{Int,Int}, Tuple{Vararg{Int}}, Core.svec(), 1, 1, 1)
true
``
is it expected a result? I think `Tuple{Int, Int}` is not more complex than `Tuple{Vararg{Int}}` because It is not .

Comment (p1scescom) [reply base/compiler/typelimits.jl]: I survey this code blame and rethink it and agree your suggestion.

**Comment by p1scescom** [comment]
I have an question in this situation,
```
julia> Core.Compiler.type_more_complex(Tuple{Int,Int}, Tuple{Vararg{Int}}, Core.svec(), 1, 1, 1)
true
```
is it expected a result? I think Tuple{Int, Int} is not more complex than Tuple{Vararg{Int}} because Tuple{Vararg{Int}} is an abstract type(Maybe that's not the right word) of Tuple{Int,Int}.

**Comment by vtjnash** [comment]
That is expected (`true` is always a safe answer always). It is a longer tuple, and we already have this statement also about Vararg and tuple lengths:
```
julia> Core.Compiler.type_more_complex(Tuple{Vararg{Int}}, Tuple{Int}, Core.svec(), 1, 1, 1)
false
```
therefore changing the predicate for Vararg for Tuple{Int,Int} would result in a circularity in the results here. Note that type_more_complex and subtyping tend to run in opposite directions to each other, as widening must move towards the abstract type, so the abstract type must also be able to be simpler.

**Comment by p1scescom** [comment]
I understand an difference between type_more_complex and subtyping. Thank you for answering.
