### PR TITLE
ensure reflection returns all names in a module

### LINKED ISSUE #17140: names(all=true) fails to return all names
As I discovered while trying to investigate https://github.com/JuliaLang/julia/issues/16091, `names` has started lying when called with `all = true` and doesn't return all names, but instead filters out names that it doesn't like. This makes debugging hard as `names` no longer does accurate introspection.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #17140

### CODE REVIEW

**Comment by tkelman** [comment]
Where are the ASCIIString errors coming from here?

**Comment by vtjnash** [comment]
we're running with `--depwarn=error`, and this changes reflection to also return deprecated bindings

**Comment by tkelman** [comment]
Hm. So do we temporarily swallow warnings any time we use `all=true` in the tests then?

**Comment by vtjnash** [comment]
no, I'm working on a more complete fix. But so far, fixing this has uncovered 3 bugs in our testing :/ and caused me to fix examples/typetree.jl to be prettier :). Also it should save a small amount of memory.

File: test/show.jl [hunk 1]
```diff
@@ -278,20 +278,19 @@ end
 let oldout = STDOUT, olderr = STDERR
     local rdout, wrout, rderr, wrerr, out, err, rd, wr
     try
-        rd, wr = redirect_stdout()
-        @test dump(STDERR) == nothing
```
Comment (tkelman) [inline test/show.jl]: why are you deleting this?

Comment (vtjnash) [inline test/show.jl]: it wasn't checking it's output so it's just artificially inflating the coverage. I added more than enough tests below of the same to make up for it.

**Comment by vtjnash** [comment]
Test failure seems to have been the libopenspecfun mod2pi issue, so ready to merge now

**Comment by StefanKarpinski** [comment]
This failure appears to be something else: https://travis-ci.org/JuliaLang/julia/jobs/145942953. If you're sure that it's unrelated, go ahead and merge – I can't really tell.

**Comment by vtjnash** [comment]
@yuyichao is it possible that the size of the `.eh_frame` section is not exactly equal to the end of the last symbol in it?

**Comment by yuyichao** [comment]
I don't know. @Keno 

In any case, I think we should stop processing after we hit a terminator? So maybe

```diff
diff --git a/src/debuginfo.cpp b/src/debuginfo.cpp
index 4901eab..5a6c531 100644
--- a/src/debuginfo.cpp
+++ b/src/debuginfo.cpp
@@ -1357,7 +1357,7 @@ extern "C" void __register_frame(void*);
 extern "C" void __deregister_frame(void*);
 
 template <typename callback>
-static const char *processFDE(const char *Entry, callback f)
+static uint32_t processFDE(const char *Entry, callback f)
 {
     const char *P = Entry;
     uint32_t Length = *((const uint32_t *)P);
@@ -1368,7 +1368,7 @@ static const char *processFDE(const char *Entry, callback f)
     if (Offset != 0 && Length != 0) {
         f(Entry);
     }
-    return P + Length;
+    return Length;
 }
 
 template <typename callback>
@@ -1376,9 +1376,12 @@ static void processFDEs(const char *EHFrameAddr, size_t EHFrameSize, callback f)
 {
     const char *P = (const char*)EHFrameAddr;
     const char *End = P + EHFrameSize;
-    do  {
-        P = processFDE(P, f);
-    } while(P != End);
+    do {
+        uint32_t Length = processFDE(P, f);
+        if (Length == 0)
+            break;
+        P += Length + 4;
+    } while (P != End);
 }
 #endif
 ```

File: base/interactiveutil.jl [hunk 2]
```diff
@@ -670,7 +670,7 @@ function summarysize(obj::Module, seen, excl)
     haskey(seen, obj) ? (return 0) : (seen[obj] = true)
     size::Int = Core.sizeof(obj)
     for binding in names(obj, true)
-        if isdefined(obj, binding)
+        if isdefined(obj, binding) && !isdeprecated(obj, binding)
```
Comment (JeffBezanson) [inline base/interactiveutil.jl]: This seems like a strange place to exclude deprecated items.

Comment (vtjnash) [inline base/interactiveutil.jl]: agreed. but we need some non-warning form of `getfield` so that we can reflect on them without causing warnings to be printed (and with `--depwarn=error` to fail). However, I'm not sure what that API should look

**Comment by maleadt** [comment]
This makes `testall` fail on my system because of the new tests for `dumptypes` introduced in 1b470f5a0a833903b7c724c618f9e2b92ccd5caa, more specifically the `@test startswith(repr, "Any\n  Base.")`.

When running in isolation, `sprint(dump, Any)` starts with:
```
Any
  Base.=> = Pair{A,B}
  Base.AbstractCartesianIndex{N}
    Base.CartesianIndex = CartesianIndex{N}
    CartesianIndex{N}
  AbstractChannel
    Channel{T}
...
```

However, when running `make testall`, it starts with:
```
Any
  Main.#1181#rettype = Tuple{Int64,Int64}
  Main.#1185#rettype = Tuple{Int64,Int64,Int64}
  Base.=> = Pair{A,B}
  Base.AbstractCartesianIndex{N}
    Base.CartesianIndex = CartesianIndex{N}
    CartesianIndex{N}
  AbstractChannel
    Channel{T}
...
```

**Comment by vtjnash** [comment]
alright, I added that as an option for that test too: https://github.com/JuliaLang/julia/commit/8a9fd10b0a317b952575e9dd230b901342636f05
