### PR TITLE
Fix BLAS.syr/her! by checking stride of x

### LINKED ISSUE #373: BLAS.syr! incorrect when argument is SubArray
`BLAS.syr!` is incorrect when the vector argument is a view.  The first element is correct, but the others are off.  Here is a minimal example:

``` julia
a1 = zeros(2, 2); a2 = zeros(2, 2); x = randn(5, 2);

x[1, :] * x[1,:]'
JuliaLang/julia#2×2 Array{Float64,2}:
JuliaLang/julia#1.80996   0.192666
#0.192666  0.0205089

BLAS.syr!('U', 1.0, x[1, :], a1)
JuliaLang/julia#2×2 Array{Float64,2}:
JuliaLang/julia#1.80996  0.192666
#0.0      0.0205089

BLAS.syr!('U', 1.0, view(x,1,:), a2)
JuliaLang/julia#2×2 Array{Float64,2}:
JuliaLang/julia#1.80996  -0.0177593
#0.0       0.000174254
```

And my version info:

```
julia> versioninfo()
Julia Version 0.5.1-pre+2
Commit f0d40ec (2016-09-20 03:34 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, has well)
```

### LINKED ISSUE #18908: BLAS.syr! incorrect when argument is SubArray
`BLAS.syr!` is incorrect when the vector argument is a view.  The first element is correct, but the others are off.  Here is a minimal example:

```julia
a1 = zeros(2, 2); a2 = zeros(2, 2); x = randn(5, 2);

x[1, :] * x[1,:]'
#2×2 Array{Float64,2}:
# 1.80996   0.192666
# 0.192666  0.0205089

BLAS.syr!('U', 1.0, x[1, :], a1)
#2×2 Array{Float64,2}:
# 1.80996  0.192666
# 0.0      0.0205089

BLAS.syr!('U', 1.0, view(x,1,:), a2)
#2×2 Array{Float64,2}:
# 1.80996  -0.0177593
# 0.0       0.000174254
```

And my version info:
```
julia> versioninfo()
Julia Version 0.5.1-pre+2
Commit f0d40ec (2016-09-20 03:34 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, has well)
```

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes JuliaLang/LinearAlgebra.jl#373

### CODE REVIEW

File: test/choosetests.jl [hunk 1]
```diff
@@ -118,7 +118,7 @@ function choosetests(choices = [])
                    "linalg/diagonal", "linalg/pinv", "linalg/givens",
                    "linalg/cholesky", "linalg/lu", "linalg/symmetric",
                    "linalg/generic", "linalg/uniformscaling", "linalg/lq",
-                   "linalg/hessenberg"]
+                   "linalg/hessenberg", "linalg/blas"]
```
Comment (tkelman) [inline test/choosetests.jl]: what's the difference between `linalg/blas` and just `blas` then?

Comment (andreasnoack) [inline test/choosetests.jl]: I've moved the tests to the existing `blas.jl` test file. I'll probably move that file to the linalg tests when this is merged.

**Comment by kshyatt** [comment]
Good to go?
