### PR TITLE
REPLCompletions: allow completions for explicitly `using`-ed names

### LINKED ISSUE #29275: Tab completion of symbols fails when doing using Package: Foo
For example:

```jl
julia> using LibGit2: GitRepo

julia> GitR<TAB> # doesn't complete

julia> using LibGit2

julia> GitR<TAB> # completes to GitRepo
```

This also fails on 0.6 but according to @ararslan it works on 0.5 so marking as regression.

### LINKED ISSUE #40356: REPL tab completion: some completions are missing
After `using Flux`,
```
julia> Flux.CU<tab>
```
completes to `Flux.CUDAint`, skipping `Flux.CUDA`.
Also, `Flux.CUDA.all<tab>` completes to `Flux.CUDA.alloc`, skipping `Flux.CUDA.allowscalar`. An additional tab shows
```
julia> Flux.CUDA.alloc
alloc          alloc_stats     alloc_timings   alloc_to        allocated       allocated_lock
```

```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
```
`Flux` version is 0.12.1

### LINKED ISSUE #49109: REPL shell completion fail to detect imported symbol
to reproduce

```julia
julia> using Random: AbstractRNG, Xoshiro
```

both `AbstractRNG, Xoshiro` failed to complete but they are in the namespace, however if we

```julia
julia> using Random
```

REPL seems to be able to complete them.

### LINKED ISSUE #53524: Autocompletion after selective `using`
```julia
using Package: something
somet<TAB> # doesn't work :(
```

Especially disappointing when `something == Package`:
```julia
using Package: Package
Packa<TAB> # doesn't work :(
```

Note that this works (of course):
```julia
import Package # or using
Packa<TAB> # works :)
```

### LINKED ISSUE #53999: [REPL] Autocompletion of `using` multiple submodules is broken
Julia v1.10.2, in a REPL session:
```
using Base.Threads, Base.Thre<TAB>
```
results in
```
julia> using Base.Threads, Base.Thre┌ Error: Error in the keymap
│   exception =
│    UndefVarError: `out` not defined
│    Stacktrace:
│      [1] complete_identifiers!(suggestions::Vector{REPL.REPLCompletions.Completion}, ffunc::Any, context_module::Module, string::String, name::String, pos::Int64, dotpos::Int64, startpos::Int64; comp_keywords::Bool)
│        @ REPL.REPLCompletions ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPLCompletions.jl:1055
│      [2] complete_identifiers!
│        @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPLCompletions.jl:983 [inlined]
│      [3] completions(string::String, pos::Int64, context_module::Module, shift::Bool)
│        @ REPL.REPLCompletions ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPLCompletions.jl:1299
│      [4] complete_line(c::REPL.REPLCompletionProvider, s::REPL.LineEdit.PromptState, mod::Module)
│        @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:545
│      [5] complete_line(s::REPL.LineEdit.PromptState, repeats::Int64, mod::Module)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:376
│      [6] complete_line(s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:367
│      [7] edit_tab(s::REPL.LineEdit.MIState, jump_spaces::Bool, delete_trailing::Bool)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2320
│      [8] edit_tab
│        @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2320 [inlined]
│      [9] (::REPL.LineEdit.var"#114#170")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2366
│     [10] #invokelatest#2
│        @ ./essentials.jl:892 [inlined]
│     [11] invokelatest
│        @ ./essentials.jl:889 [inlined]
│     [12] (::REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#114#170", String})(s::Any, p::Any)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:1612
│     [13] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2749
│     [14] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2651
│     [15] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1312
│     [16] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:386
└ @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2751
julia> 
julia> 
```
In Julia `master` this doesn't crash, but it also doesn't complete the second `Base.Thre`.  This works as expected in Julia v1.9.

### PR DESCRIPTION
**Pull request by aviatesk**
The new feature `usings=true` added to `names` enhances REPL completions by allowing explicitly `using`-ed names to be found.
```julia
julia> using Base: @assume_effects

julia> @assu| # completes to `@assume_effects`
```

As a result, the implementation of REPL completions has been simplified. Additionally, it allows completion for names that are implicitly or explicitly `using`-ed in code specifying a module explicitly, such as:
```julia
julia> module A end

julia> A.signi| # completes to `A.significand`
```

- fixes #29275
- fixes #40356
- fixes #49109
- fixes #53524
- ~~fixes #53999~~

### CODE REVIEW

File: stdlib/REPL/test/replcompletions.jl [hunk 1]
```diff
@@ -2260,3 +2264,30 @@ let s = "Issue53126()."
...
+let s = "@assu"
+    c, r, res = test_complete_context(s, TestExplicitUsing)
+    @test res
+    @test "@assume_effects" in c
+end
+let s = "TestExplicitUsing.@assu"
+    c, r, res = test_complete_context(s)
+    @test res
+    @test "@assume_effects" in c
+end
```
Comment (aviatesk) [inline stdlib/REPL/test/replcompletions.jl:2281]:
```suggestion
baremodule TestExplicitUsing
using Base: @assume_effects
end # baremodule TestExplicitUsing
let s = "@assu"
    c, r, res = test_complete_context(s, TestExplicitUsing)
    @test res
    @test "@assume_effects" in c
end
let s = "TestExplicitUsing.@assu"
    c, r, res = test_complete_context(s)
    @test res
    @test "@assume_effects" in c
end
baremodule TestExplicitUsingNegative end
let s = "@assu"
    c, r, res = test_complete_context(s, TestExplicitUsingNegative)
    @test res
    @test "@assume_effects" ∉ c
end
let s = "TestExplicitUsingNegative.@assu"
    c, r, res = test_complete_context(s)
    @test res
    @test "@assume_effects" ∉ c
end
```

**Comment by giordano** [comment]
This doesn't fix #53999, the second submodule is still not completed.
