### PR TITLE
Move `libstdc++` path into `LOADER_*_DEP_LIBS`

### LINKED ISSUE #47987: Build fails with USE_SYSTEM_CSL=1
Since commit 96592e21e2b186bfba2044dac84a15d0c31ee662 julia build fails with USE_SYSTEM_CSL=1 with error
```
ERROR: Unable to load dependent library /build/julia/src/julia-1.8.4/usr/bin/../lib/libstdc++.so.6
Message:/build/julia/src/julia-1.8.4/usr/bin/../lib/libstdc++.so.6: cannot open shared object file: No such file or directory
```
The `libstdc++.so.6` symlink is in `usr/lib/julia`, but the build system expects to find it in `usr/lib`

### PR DESCRIPTION
**Pull request by staticfloat**
After adding `libstdc++` probing into the Julia loader [0], we originally made the assumption that the `libstdc++` that is shipped with `julia` would always be co-located with `libjulia.so` [1].  This is not the case when building with `USE_SYSTEM_CSL=1`, however, where we sequester system libraries in `usr/lib/julia`, even at build-time.

The path to `libstdc++.so` has already been getting altered when moving from build-time to install time via `stringreplace` [2], but after further thought, I decided that it would be better to just use the pre-existing `LOADER_*_DEP_LIBS` mechanism to communicate to the loader what the correct relative path to `libstdc++.so` is.  This also allows the single `stringreplace` to update all of our "special" library paths.

[0] https://github.com/JuliaLang/julia/pull/46976
[1] https://github.com/JuliaLang/julia/pull/46976/files#diff-8c5c98f26f3f7aac8905a1074c5bec11a57e9b9c7c556791deac5a3b27cc096fR379 [2] https://github.com/JuliaLang/julia/blob/master/Makefile#L430

Fix #47987.

### CODE REVIEW

**Comment by staticfloat** [comment]
This should fix #47987

**Comment by fxcoudert** [comment]
Fixes the build on Linux for Homebrew. Thanks!

File: cli/loader_lib.c [hunk 1]
```diff
@@ -366,6 +366,50 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
+    // Assert that we have exactly the right number of special library names
+    if (special_idx != sizeof(special_library_names)/sizeof(char *)) {
+        jl_loader_print_stderr("ERROR: Too few special library names specified, check LOADER_BUILD_DEP_LIBS and friends!\n");
+        exit(1);
+    }
+
+    // Unpack our special library names.  This is why ordering of library names matters.
+    char * bundled_libstdcxx_path = special_library_names[0];
+    libjulia_internal = load_library(special_library_names[1], lib_dir, 1);
+    void *libjulia_codegen = load_library(special_library_names[2], lib_dir, 0);
```
Comment (vtjnash) [inline cli/loader_lib.c:411]: Why are we loading this early now?

**Review by vtjnash — APPROVED** [review]

File: cli/loader_lib.c (hunk 1 above)
Comment (staticfloat) [reply cli/loader_lib.c:411]: Ahh, that was unintentional.  Thank you, good catch.

**Comment by staticfloat** [comment]
I've now pushed a commit that causes the library loading (including special libraries) to obey the order as specified in `DEP_LIBS`.  The current ordering is now:

* `libgcc_s`
* `libm` (usually OpenLibm, but can be system libm if `USE_SYSTEM_LIBM=1`)
* `libstdc++`
* `libjulia-internal`
* `libjulia-codegen`

This ordering is important because `libstdc++` depends on `libgcc_s` and `libm`, so if we are using `USE_SYSTEM_LIBM=1`, we technically should load `libm` first.  Previously, we would probe and load `libstdc++` first, which would bring in `libgcc_s` and `libm` from the system.

File: Make.inc [hunk 2]
```diff
@@ -1465,7 +1465,7 @@ JULIA_SYSIMG_release := $(build_private_libdir)/sys.$(SHLIB_EXT)
 JULIA_SYSIMG := $(JULIA_SYSIMG_$(JULIA_BUILD_MODE))
 
 define dep_lib_path
-$$($(PYTHON) $(call python_cygpath,$(JULIAHOME)/contrib/relative_path.py) $(1) $(2))
+$(shell $(PYTHON) $(call python_cygpath,$(JULIAHOME)/contrib/relative_path.py) $(1) $(2))
```
Comment (vtjnash) [inline Make.inc:1468]: :heart:

Comment (staticfloat) [reply Make.inc:1468]: This slows things down a bit (adds ~60ms to every `make` invocation on my linux desktop) but I think it's worth it for the extra clarity.
