### PR TITLE
Backports 1.5.4

### LINKED ISSUE #37872: Internal error with StackOverflowError while compiling a function
MWE:
```
julia> function swapliterals!(@nospecialize(swaps::AbstractDict))
           swaps === Base.ImmutableDict(Int128 => :big)
       end
swapliterals! (generic function with 1 method)

julia> swapliterals!(Dict(Int=>Int))
Internal error: encountered unexpected error during compilation of swapliterals!:
StackOverflowError()
jl_type_intersection_env_s at /local/src/julia/src/subtype.c:3305
emit_f_is at /local/src/julia/src/codegen.cpp:2553
emit_bits_compare at /local/src/julia/src/codegen.cpp:2503
operator() at /local/src/julia/src/codegen.cpp:2573
emit_guarded_test<emit_f_is(jl_codectx_t&, const jl_cgval_t&, const jl_cgval_t&, llvm::Value*, llvm::Value*)::<lambda()>&> at /local/src/julia/src/codegen.cpp:
2322
operator() at /local/src/julia/src/codegen.cpp:2354 [inlined]
[...]
```

### LINKED ISSUE #37880: Codegen bug with Base.lshr_int intrinsic
Ref: https://discourse.julialang.org/t/failure-with-lshr-int-intrinsic-for-on-uint256-type/47738/4
@simeonschaub suggested this repro which "looks like it’s an LLVM bug":
```
julia> primitive type UInt256 256 end

julia> x = reinterpret(UInt256, rand(UInt128, 2))[]
UInt256(0x48805fdfb72d71fadaf8daa563cf816383f755d9d9e70d703fa348f556c717ad)

julia> f(x) = Base.lshr_int(x, 0x8)
f (generic function with 1 method)

julia> @code_llvm optimize=false f(x)
;  @ REPL[22]:1 within `f'
define void @julia_f_392(i256* noalias nocapture sret %0, i256 %1) {
top:
  %2 = call {}*** @julia.ptls_states()
  %3 = bitcast {}*** %2 to {}**
  %4 = getelementptr inbounds {}*, {}** %3, i64 4
  %5 = bitcast {}** %4 to i64**
  %6 = load i64*, i64** %5
  %7 = lshr i256 %1, 8
  %8 = select i1 true, i256 0, i256 %7
  store i256 %8, i256* %0, align 8
  ret void
}

julia> @code_llvm optimize=true f(x)
;  @ REPL[22]:1 within `f'
define void @julia_f_394(i256* noalias nocapture sret %0, i256 %1) {
top:
  store i256 0, i256* %0, align 8
  ret void
}
```

### LINKED ISSUE #38386: defining empty function with escaped name in macro does not work
When I try to define an empty generic function from within a macro using an escaped name I get a 'malformed expression' error. Doing exactly the same thing but with a function with an empty argument list works.

```Julia
julia> macro Bla()
       fname = :myfun
       :(function $(esc(fname)) end)
       end
@Bla (macro with 1 method)

julia> @Bla
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope at REPL[8]:1

julia> macro Bla()
       fname = :myfun
       :(function $(esc(fname))() end)
       end
@Bla (macro with 1 method)

julia> @Bla
myfun (generic function with 1 method)
```

### PR DESCRIPTION
**Pull request by vchuravy**
Backported PRs:
- [x] ~#36396 - fix showing methods with unicode gensymed variable names~ (in 1.5.3)
- [x] ~#37236 - Add INNO_ARGS makefile var for signtool~ (in 1.5.3)
- [x] ~#37407 - Bump libuv to latest commit~ (in 1.5.3)
- [x] ~#37562 - Revert "Improve typesubtract for tuples (#35600)"~ (in 1.5.3)
- [x] ~#37769 - Fix `getfield_tfunc` for `PartialStruct` with `Vararg`~ (in 1.5.3)
- [x] #38002 - Fix tall qr multiplication
- [x] #38399 - Fix segfault in static_show, by using correct `vt` instead of `typeof(v)`
- [x] #38551 - update to utf8proc 2.6
- [x] #38900 - update to utf8proc 2.6.1
- [x] #38270 - added automatic keyword assignment support to test macro
- [x] #39265 - aotcompile: avoid cache lookup when disallowed
- [x] #38487 - threads: avoid deadlock from recursive lock acquire (https://github.com/JuliaLang/julia/pull/38753)
- [x] ~#37594 - dump: ensure Array eltype layout is initialized early~ (in 1.5.3)
- [x] #38679 - Report the top of the exception stack when there's no handler.
- [x] #37645 - fix fields description of Module type
- [x] #38402 - fix #38386, macro defining empty function with escaped name
- [x] ~#36821 - Fix function call to rec_backtrace_ctx when using USE_SYSTEM_LIBUNWIND=1~ (alt in 1.5.3)
- [x] ~#37101 - make Profile more thread/signal-safe~ (in 1.5.3)
- [x] #37557 - Fix === and objectid of object with potentially undef inline immutable field
- [x] #37891 - fix #37880, overflow in shift amount range check in codegen
- [x] #37896 - fix #37872, avoid cycles in codegen for `===`
- [x] #37243 - code coverage fixes
- [x] #39038 - [libuv] Bump to include `DELETE` win ACL patch'
- [x] #39153 - improve performance of disabling finalizers in locks
- [x] #39336 - fix failing `enable_finalizers` test

TODO:
- [x] FreeBSD build failure
- [x] Turn https://github.com/JuliaCI/julia-buildbot/blob/master/commands/rr_capture.jl into a Noop
- [ ]

### CODE REVIEW

**Comment by NHDaly** [comment]
Note: Backport of https://github.com/JuliaLang/julia/pull/37896 depends on first backporting https://github.com/JuliaLang/julia/pull/37557.

**Comment by giordano** [comment]
#38753 is already on this branch, isn't it?

**Comment by Sacha0** [comment]
> #38753 is already on this branch, isn't it?

Yes, it's already on `release-1.5`. Backporter probably attempted to sweep it in due to the `backport-1.5` label on #38753. (I just removed the label and will update the OP.)

**Comment by Sacha0** [comment]
Similarly https://github.com/JuliaLang/julia/pull/37613 made it into 1.5.3, so I've dropped it from the OP and removed the `backport-1.5` label from https://github.com/JuliaLang/julia/pull/37613.

**Comment by Sacha0** [comment]
A backport of https://github.com/JuliaLang/julia/pull/37594 made it into https://github.com/JuliaLang/julia/pull/37594; updating the OP accordingly :).

**Comment by Sacha0** [comment]
Added a commit for https://github.com/JuliaLang/julia/pull/37645 and dropped the `backport-1.5` tag.

**Comment by Sacha0** [comment]
Added a commit for #38402 and dropped the `backport-1.5` tag.

**Comment by Sacha0** [comment]
Cleaned up a few more items in the OP that made it into 1.5.3. Not too many commits left :).

File: base/compiler/tfuncs.jl [hunk 1]
```diff
@@ -925,11 +925,11 @@ function fieldtype_tfunc(@nospecialize(s0), @nospecialize(name))
...
         return Type
     end
-    # fieldtype only accepts Types, errors on `Module`
-    if isa(s0, Const) && (!(isa(s0.val, DataType) || isa(s0.val, UnionAll) || isa(s0.val, Union)) || s0.val === Module)
+    # fieldtype only accepts Types
+    if isa(s0, Const) && !(isa(s0.val, DataType) || isa(s0.val, UnionAll) || isa(s0.val, Union))
         return Bottom
     end
-    if s0 == Type{Module} || s0 == Type{Union{}} || isa(s0, Conditional)
+    if (s0 isa Type && s0 == Type{Union{}}) || isa(s0, Conditional)
```
Comment (NHDaly) [inline base/compiler/tfuncs.jl:932]: @Sacha0 - i also did this backport, here (oops, we collided. I'm happy to drop that now that you've done it 😊):
https://github.com/JuliaLang/julia/compare/backports-release-1.5...NHDaly:nhd-backports-release-1.5-manual

And i wasn't sure whether to pull over the `isa Type` change as well. Technically that was added in https://github.com/JuliaLang/julia/commit/dcc0696971a100dbc63f90b8789632631dd1bfef, as part of (#36596), so i wasn't sure whether to backport it as well. Supposedly it's just a code cleanup, but i'm not sure if it holds in isolation from the rest of the commit.

I think the closest transformation keeping in spirit of the change we're backporting from (#37645) would be just to drop the `Module` part, since that's all they did in the original PR? Like this, perhaps?:
```suggestion
    if s0 == Type{Union{}} || isa(s0, Conditional)
```

PROBABLY fine either way, but since i see you made a different decision than I made when attempting the manual bisect, I wanted to just bring this up! :)

Comment (NHDaly) [reply base/compiler/tfuncs.jl:932]: To see the diff standalone, it's the change i made:
https://github.com/JuliaLang/julia/compare/backports-release-1.5...NHDaly:nhd-backports-release-1.5-manual#diff-94ffb7fc1a419bb8439ae0ecbb4a3b5460d193e53c96bb97b50e283fdbc16a85L932-R932

Comment (NHDaly) [reply base/compiler/tfuncs.jl:932]: EDIT: https://github.com/JuliaLang/julia/commit/cc099114749a53490d7903dc122dd813609ea569#diff-94ffb7fc1a419bb8439ae0ecbb4a3b5460d193e53c96bb97b50e283fdbc16a85L932-R932

Comment (Sacha0) [reply base/compiler/tfuncs.jl:932]: I wondered the same, but err'd to adding the `isa Type` guard as `== Type{Union{}}` cannot be true unless the guard is true, and if the latter is true then the former must be true as well, so this transformation should be functionally identical modulo some additional safety with the guard (against `== Type{Union{}}` throwing something for non-`Type` `s0`s)? Either way is fine by me though :).

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/39351#issuecomment-765101238):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`/home/nanosoldier/workdir/jl_g4mXAp/julia -e 'VERSION >= v"0.7.0-DEV.3656" && using Pkg; Pkg.update()'`, ProcessExited(1)) [1]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/b8bc0275ecbdbd856d393b7d8abe26bf5209d062/benchmark/by_hash/dfaeca9_vs_ebcc603/report.md)
cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39351#issuecomment-765101188) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/7b05f42_vs_ebcc603/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Needs this change:
```diff
--- a/base/lock.jl
+++ b/base/lock.jl
@@ -87,7 +87,7 @@ function lock(rl::ReentrantLock)
         if rl.reentrancy_cnt == 0
             rl.locked_by = t
             rl.reentrancy_cnt = 1
-            GC.enable_finalizers()
+            GC.disable_finalizers()
             break
         elseif t === notnothing(rl.locked_by)
```

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39351#issuecomment-766510566) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/cb75d49_vs_ebcc603/report.md). cc @maleadt

**Comment by Sacha0** [comment]
Thanks folks! ❤️
