### PR TITLE
[Fix #32070] SparseMatrixCSC{Bool} x [Sparse]Vector{Bool} too narrow result eltype

### LINKED ISSUE #32070: SparseMatrixCSC{Bool} x SparseVector{Bool} can't store result type
# Bug
Multiplying a bool sparse matrix with a bool sparse vector should widen the result type to Int, like BitArray{2} x BitArray{1} does.

## MWE

BitArrays (dense):
```
jl> G= bitrand(100,200); h= bitrand(200)
jl> G*h|> typeof
Array{Int64,1}
```

Sparse:
```
jl> S= sprand(Bool,100,200,0.02); v= sprand(Bool,200,0.1)
jl> S*v|> typeof
ERROR: InexactError: Bool(2)
Stacktrace:
 [1] Type at ./float.jl:73 [inlined]
 [2] convert at ./number.jl:7 [inlined]
 [3] setindex! at ./array.jl:767 [inlined]
 [4] mul!(::Array{Bool,1}, ::SparseMatrixCSC{Bool,Int64}, ::SparseVector{Bool,Int64}, ::Bool, ::Bool) at /home/oblivion/ws/var/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:1618
 [5] mul! at /home/oblivion/ws/var/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:1593 [inlined]
 [6] #densemv#57(::Char, ::Function, ::SparseMatrixCSC{Bool,Int64}, ::SparseVector{Bool,Int64}) at /home/oblivion/ws/var/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:1580
 [7] densemv at /home/oblivion/ws/var/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:1566 [inlined]
 [8] *(::SparseMatrixCSC{Bool,Int64}, ::SparseVector{Bool,Int64}) at /home/oblivion/ws/var/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:1672
 [9] top-level scope at none:0
```

The problem seems to be with the result vector eltype `T = promote_type(eltype(A), eltype(x))` at
```
[6] #densemv#57(::Char, ::Function, ::SparseMatrixCSC{Bool,Int64}, ::SparseVector{Bool,Int64}) at /home/oblivion/ws/var/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:1577
```

## versioninfo

```
jl> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
```

### PR DESCRIPTION
**Pull request by Oblynx**
This issue was caused by an improper result type calculation in some sparse matrix ops.

Fixing according to the example in the docs https://docs.julialang.org/en/v1/manual/methods/#Output-type-computation-1

closes #32070

### CODE REVIEW

**Comment by Oblynx** [comment]
closes #32070

File: stdlib/SparseArrays/src/linalg.jl [hunk 1]
```diff
@@ -50,9 +50,9 @@ function mul!(C::StridedVecOrMat, A::SparseMatrixCSC, B::StridedVecOrMat, α::Nu
     C
 end
 *(A::SparseMatrixCSC{TA,S}, x::StridedVector{Tx}) where {TA,S,Tx} =
-    (T = promote_type(TA, Tx); mul!(similar(x, T, A.m), A, x, one(T), zero(T)))
+    (T = promote_op((a,b)->a*b+a*b, TA, Tx); mul!(similar(x, T, A.m), A, x, one(T), zero(T)))
```
Comment (stevengj) [inline stdlib/SparseArrays/src/linalg.jl]: Cleaner to do `typeof(zero(TA)*zero(Tx)+zero(TA)*zero(Tx))`

Comment (stevengj) [reply stdlib/SparseArrays/src/linalg.jl]: Actually, we already have a function for this in LinearAlgebra.  Do `promote_op(matprod, TA, tx)`, where you do `using LinearAlgebra: matprod` somewhere.

Comment (Oblynx) [reply stdlib/SparseArrays/src/linalg.jl]: Done, thanks!

**Comment by Oblynx** [comment]
@stevengj In the Julia PR workflow, how should I squash my commits? Should I squash them locally and force-push?
This is my first PR. Thank you!

**Comment by stevengj** [comment]
@Oblynx, no need to squash or rebase (unless there is a merge conflict) — github allows us to squash/rebase when we merge.

**Review by stevengj — APPROVED** [review]

**Comment by Oblynx** [comment]
@stevengj can we backport to 1.2? If yes, how?

**Comment by stevengj** [comment]
Whether this can be backported depends on whether @StefanKarpinski and the other core devs feel that this is a bugfix or a new feature.  You could argue both ways on this PR.

My instinct here is that this is more "featurey," because it takes a case that threw an exception before and makes it work, rather than fixing something that silently gave the wrong answer.

**Comment by Oblynx** [comment]
Hmm I see your point. Just for argument's sake, there is of course the "buggey" view as well: this functionality is implicitly promised, as a special case of matrix-vector multiplication, and before this it loudly failed to give the correct answer.

**Comment by Oblynx** [comment]
@stevengj should someone be assigned to this? Is there anything more I should do?

**Comment by ViralBShah** [comment]
Thanks @Oblynx.  I am marking this for triage to decide if it can be backported to 1.2.
