### PR TITLE
Improve work-around for LLVM SIMD bug

### LINKED ISSUE #16287: `VecElement` doesn't work with 1-tuples
@ArchRobison I find that the `VecElement` mechanism doesn't work with length-1 tuples; these are still represented as LLVM arrays in function arguments. Is this intended? If not, do you know where I could change this?

This is inconvenient because it requires many special cases in <https://github.com/eschnett/SIMD.jl>.

### PR DESCRIPTION
**Pull request by eschnett**
Disable exactly those SIMD vectors sizes that cause problems in LLVM 3.7 and 3.8.

Closes #16287.

### CODE REVIEW

**Comment by eschnett** [comment]
@ArchRobison I've implemented the patch we discussed in #16287. Could you have a look?

**Comment by eschnett** [comment]
@ArchRobison ping?

File: src/alloc.c [hunk 1]
```diff
@@ -832,9 +832,22 @@ JL_DLLEXPORT jl_datatype_t *jl_new_uninitialized_datatype(size_t nfields, int8_t
 unsigned jl_special_vector_alignment(size_t nfields, jl_value_t *t) {
     if (!is_vecelement_type(t))
         return 0;
-    if (nfields>16 || (1<<nfields & 0x1157C) == 0)
-        // Number of fields is not 2, 3, 4, 5, 6, 8, 10, 12, or 16.
+    // LLVM 3.7 and 3.8 either crash or generate wrong code for many
+    // SIMD vector sizes N. It seems the rule is that N can have at
+    // most 2 non-zero bits. (This is true at least for N<=100.) See
+    // also <https://llvm.org/bugs/show_bug.cgi?id=27708>.
+    if (nfields <= 32 && (1U << (unsigned)(nfields-1) & 0x808b8bbfU) == 0)
```
Comment (ArchRobison) [inline src/alloc.c]: I'd prefer to not treat `nfields <= 32` as a special case since that introduces another boundary case/path for testing.  The following sequence efficiently detects if `nfields` has two or fewer bits:
```
size_t mask = nfields;
mask &= mask-1;    // Clear least-significant 1 if present
mask &= mask-1;    // Clear another 1
if (mask)
    return 0;      // nfields has more than two 1s. 
```
The clear-least-significant-1 hack is a good one to know in general.  Here's a [ref](https://graphics.stanford.edu/~seander/bithacks.html)  that has it (dates back to [1960](https://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetKernighan)!) and other bit hacks.

**Comment by ArchRobison** [comment]
Looks good to me.
