### PR TITLE
Fix sparse matrix row slices

### LINKED ISSUE #14013: problem of conversion from sparse matrix slice to sparse vector
hello,

the conversion between sparse matrix line and sparse vecteor is not correct

julia> aa = sparse([10. 0 30.])
1x3 sparse matrix with 2 Float64 entries:
    [1, 1]  =  10.0
    [1, 3]  =  30.0

julia> full(aa[1,:])
3-element Array{Float64,1}:
 10.0
 30.0
  0.0

the zeros coefficient has been misplaced in the sparse vector.

this happens in the development branch
Version 0.5.0-dev+1265 (2015-11-13 08:40 UTC)
Commit f045831 (0 days old master)
x86_64-linux-gnu

...and just a comment about
https://github.com/JuliaLang/julia/pull/13440

the direction taken by sparse arrays (matrix or vector) library is questionable in my opinion. if a line or column slice of a sparse matrix is transformed into a sparse vector, with a different internal implementation, then you will prevent people from passing slices like a[k,:] to libraries. in my opinion, more generally, the implicit conversion of matrix slices like a[k,:] or a[:,k] into vectors will reduce drastically the main quality of Julia : "it's very easy to plug algorithms between them". we will have to write special case for slices every time.

bests,
M.

### PR DESCRIPTION
**Pull request by mbauman**
Fix #14013

### CODE REVIEW

File: base/sparse/sparsevector.jl [hunk 1]
```diff
@@ -392,7 +392,7 @@ function Base.getindex{Tv,Ti}(A::SparseMatrixCSC{Tv,Ti}, i::Integer, J::Abstract
             if rowvalA[ptrA] <= rowI
                 ptrA = searchsortedfirst(rowvalA, rowI, ptrA, stopA, Base.Order.Forward)
                 if ptrA <= stopA && rowvalA[ptrA] == rowI
-                    push!(nzinds, ptrI)
+                    push!(nzinds, j)
```
Comment (tkelman) [inline base/sparse/sparsevector.jl]: should this be `col`?

Comment (mbauman) [inline base/sparse/sparsevector.jl]: No, it should be `j`.  We want the n-th index to be the result of indexing with to the n-th value in `J`… that just happens to be the same as `col` in the case of `1:end`.
