### PR TITLE
Fix symdiff/symdiff! for vector inputs with duplicates, closes #34686

### LINKED ISSUE #34686: should symdiff care about item multiplicity?
See https://github.com/JuliaLang/julia/pull/34675. It came up that `symdiff([1, 2, 3, 2]) == [1, 3]` which struck me as... unexpected. I'm opening an issue to discuss whether this is a behavior we actually want.

### PR DESCRIPTION
**Pull request by pcjentsch**
This PR is a simple change to address the bug that `symdiff!` returns incorrect results if called on non-Sets with duplicate entries. 

The behaviour is now equivalent to `symdiff(a::AbstractVector, b::AbstractVector) = collect(symdiff(Set(a), Set(b)))`, as suggested in #34686.

Example from #34686 before PR:
```
julia> symdiff([1, 2, 2], [2, 3, 3, 4])
3-element Vector{Int64}:
 1
 2
```

After PR
```
julia> symdiff([1, 2, 2], [2, 3, 3, 4])
3-element Vector{Int64}:
 1
 3
 4
```

I had to add an additional method `symdiff!(s::BitSet, ns::AbstractSet)` to resolve a method ambiguity that arose when I defined `symdiff!(s::AbstractSet, itr::AbstractSet)`. Let me know if there's a better way to address that!

This change also contradicts [this odd comment](https://github.com/JuliaLang/julia/blob/2d6e3b95a674e99eb8827c341424b2880e515c8f/test/sets.jl#L396).

I am working on another PR that implements more performant methods for set operations on vectors, but I thought that would be out of scope of this one.

### CODE REVIEW

**Comment by pcjentsch** [comment]
Oops I missed the tests in `arrayops.jl`, and the docs, will fix.

**Comment by pcjentsch** [comment]
@oscardssmith if you have time, could you take a look at this PR? I'd like to get this fixed.

File: base/abstractset.jl [hunk 1]
```diff
@@ -287,6 +281,13 @@ function symdiff!(s::AbstractSet, itrs...)
 end
 
 function symdiff!(s::AbstractSet, itr)
+    for x in unique(itr)
```
Comment (oscardssmith) [inline base/abstractset.jl:284]: won't this allocate a bunch and be slow?

File: test/tmp/logs/manifest_usage.toml [hunk 2]
```diff
@@ -0,0 +1,95 @@
+[["/tmp/jl_0yvG9Y/Manifest.toml"]]
```
Comment (oscardssmith) [inline test/tmp/logs/manifest_usage.toml:1]: what is this file?

File: test/tmp/registries/General.toml [hunk 3]
```diff
@@ -0,0 +1,3 @@
+git-tree-sha1 = "e43e89818f33d2c3758603b099941fe944f43676"
```
Comment (oscardssmith) [inline test/tmp/registries/General.toml:1]: also this one

File: base/abstractset.jl (hunk 1 above)
Comment (pcjentsch) [reply base/abstractset.jl:284]: Yeah, but for the general case, hashmap-based solutions always other methods in my tests, and we need to put the hashmap somewhere.

We can also do 

```
symdiff!(s::AbstractSet, itr) = symdiff!(s::AbstractSet, Set(itr))
```

I think that's the same though, since `unique` just makes a `Set` under the hood. I guess `unique` would allocate an additional vector though, you're right. 

For types that can be radix-sorted, I have the following method:

```
function symdiff!(A, _B)
    issorted(A) || sort!(A)
    B = issorted(_B) ? _B : sort(_B)
    N = length(A)
    M = length(B)
    i = 1
    j = 1
    A_out_ind = 1
    B_out_ind = 1
    @inbounds while i <= N && j <= M
        if A[i] < B[j]
            A[A_out_ind] = A[i]
            A_out_ind += 1
            i = _lookahead(A[i], A, i)
        elseif B[j] < A[i]
            B[B_out_ind] = B[j]
            B_out_ind += 1
            j = _lookahead(B[j], B, j)
        else
            i = _lookahead(A[i], A, i)
            j = _lookahead(B[j], B, j)
        end
    end
    @inbounds while i <= N
        A[A_out_ind] = A[i]
        A_out_ind += 1
        i = _lookahead(A[i], A, i)
    end
    @inbounds while j <= M
        B[B_out_ind] = B[j]
        B_out_ind += 1
        j = _lookahead(B[j], B, j)
    end
    resize!(A, A_out_ind + B_out_ind - 2)
    copyto!(A, A_out_ind, B, 1, B_out_ind - 1)
end

function _lookahead(cur, l, ind)
    @inbounds while ind <= length(l)
        if l[ind] > cur
            return ind
        else
            ind += 1
        end
    end
    return ind
end
```

but this idea can be applied to *all* the Set operations that take `Vector`, which is the subject of another issue.

Given that `symdiff` is currently broken, I think that it's best to get correct behauviour first, and then

File: test/tmp/logs/manifest_usage.toml (hunk 2 above)
Comment (pcjentsch) [reply test/tmp/logs/manifest_usage.toml]: sorry, accidentally committed these

**Review by oscardssmith — APPROVED** [review]

**Comment by pcjentsch** [comment]
I think the test failures are unrelated?

**Comment by pcjentsch** [comment]
all passed!

**Comment by oscardssmith** [comment]
Thanks for getting this done!
