### PR TITLE
fix bug in sparse is_hermsym

### LINKED ISSUE #16521: bounds error in issym or issymmetric on 2x2 sparse matrix with 1 lower-triangle non-zero
Seems like this should be a simple fix. Will try and take a look at some point.

~~~~
julia> VERSION
v"0.5.0-dev+4248"

julia> issymmetric(sparse([0 0; 1 0]))
ERROR: BoundsError: attempt to access 1-element Array{Int64,1} at index [2]
 in is_hermsym(::SparseMatrixCSC{Int64,Int64}, ::Base.#identity) at ./sparse/sparsematrix.jl:3000
 in issymmetric(::SparseMatrixCSC{Int64,Int64}) at ./sparse/sparsematrix.jl:2961
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
~~~~

Curiously, if you use the transpose, it works

~~~~
julia> issymmetric(sparse([0 1; 0 0]))
false
~~~~

Here's versioninfo()
~~~~
julia> versioninfo()
Julia Version 0.5.0-dev+4248
Commit e2f59bc (2016-05-21 05:43 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
~~~~

This also arises on v0.4.5 with bounds checking turned on

~~~~
$ julia --check-bounds=yes

julia> issym(sparse([0 1; 0 0]))
false

julia> issym(sparse([0 0; 1 0]))
ERROR: BoundsError: attempt to access 1-element Array{Int64,1}:
 2
  at index [2]
 in is_hermsym at sparse/sparsematrix.jl:2590
 in issym at sparse/sparsematrix.jl:2567

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

~~~~

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #16521

### CODE REVIEW

File: test/sparsedir/sparse.jl [hunk 1]
```diff
@@ -1154,6 +1155,14 @@ let
...
     A.nzval[end - 3]  = 2.0
     @test issymmetric(A) == false
+
+    # 16521
+    @test issymmetric(sparse([0 0; 1 0])) == false
+    @test issymmetric(sparse([0 1; 0 0])) == false
+    @test issymmetric(sparse([0 0; 1 1])) == false
+    @test issymmetric(sparse([1 0; 1 0])) == false
+    @test issymmetric(sparse([0 1; 1 0])) == true
+    @test issymmetric(sparse([1 1; 1 0])) == true
```
Comment (tkelman) [inline test/sparsedir/sparse.jl]: really?

**Comment by KristofferC** [comment]
Backport? @tkelman
