### PR TITLE
fix #57749, model ccall binding access in inference

### LINKED ISSUE #57749: `ccall` sometimes fails to statically evaluate arguments due to binding ages
```julia
using Zstd_jll
const prefix = "Zstd version: "
const sym = :ZSTD_versionString
get_zstd_version() = prefix * unsafe_string(ccall((sym, libzstd), Cstring, ()))
```
On `nightly`:
```julia
julia> get_zstd_version()
ERROR: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Tuple{Symbol, String}
```

It works if you swap the constant definition order:
```julia
using Zstd_jll
const sym = :ZSTD_versionString
const prefix = "Zstd version: "
get_zstd_version() = prefix * unsafe_string(ccall((sym, libzstd), Cstring, ()))
```

```julia
julia> get_zstd_version()
"Zstd version: 1.5.7"
```

This happens because the usage of `prefix` restricted the valid world range more tightly

### PR DESCRIPTION
**Pull request by JeffBezanson**
I've played around with ccall semantics a bunch (#57931) but concluded that a bandaid like this is far better for 1.12.

fixes #57749

### CODE REVIEW

**Comment by JeffBezanson** [comment]
So we basically need a custom interpreter here to handle the non-standard IR in ccall names, which I have tried to do but am flailing a bit :smile: It doesn't really need to be "correct" and its value is not used. It just needs to be enough for inference to tell which bindings are accessed.

So far I only have special support for nests of calls, which handles many cases like `A.B.C` but I wonder if there are any other syntaxes used out there?

File: Compiler/src/abstractinterpretation.jl [hunk 1]
```diff
@@ -3485,7 +3485,39 @@ function refine_partial_type(@nospecialize t)
...
+        for i = 1:n
+            argtypes[i] = abstract_eval_nonlinearized_foreigncall_name(interp, e.args[i], sstate, sv)
+        end
+        result = abstract_call(interp, ArgInfo(e.args, argtypes), sstate, sv)
+    else
+        result = abstract_eval_basic_statement(interp, e, sstate, sv)
+    end
+    if result isa Future
+        if !isready(result)
+            result
```
Comment (JeffBezanson) [inline Compiler/src/abstractinterpretation.jl]: I think things can break if we hit this case, so possibly we should bail out if this happens. Need some advice on this.

Comment (Keno) [reply Compiler/src/abstractinterpretation.jl]: `abstract_eval_statement_expr` which calls `abstract_eval_foreigncall` returns a future, so you can just wrap the continuation in abstract_eval_foreigncall even if you're only using the future for its effects.

**Comment by Keno** [comment]
One inline comment and I think we need to pkgeval this to see if there's any corner cases, but I think as a workaround, this seems reasonable.

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests()`

**Comment by Keno** [comment]
@KristofferC already pkgeval'd this in https://github.com/JuliaLang/julia/pull/58987

**Comment by JeffBezanson** [comment]
This PR wasn't linked nor the tag removed. In any case that run was not too useful since there were assertion failures from the other PR.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/58872#issuecomment-3080854304) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3e868b2_vs_d7bdd21/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

**3 packages crashed only on the current version.**

 - The process was aborted: 1 packages
 - Invalid LLVM IR was generated: 1 packages
 - GC corruption was detected: 1 packages

3 packages crashed on the previous version too.

## ✖ Packages that failed

**42 packages failed only on the current version.**

 - Illegal method overwrites during precompilation: 1 packages
 - Package has test failures: 2 packages
 - Package tests unexpectedly errored: 2 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 21 packages
 - Test log exceeded the size limit: 15 packages

1156 packages failed on the previous version too.

## ✔ Packages that passed tests

**15 packages passed tests only on the current version.**

 - Other: 15 packages

5369 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**16 packages successfully loaded only on the current version.**

 - Other: 16 packages

3224 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

**2 packages were skipped only on the current version.**

 - Package could not be installed: 2 packages

903 packages were skipped on the previous version too.



</details>

**Comment by vtjnash** [comment]
Looks like up to 15 failures caused by this PR (CustomGaussQuadrature was in the last report as failing from this PR too)
```
Test log exceeded the size limit: 15 packages
Package	Version	Primary	Against	History (6-16 to 7-15)
Quadmath	v0.5.13	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
HyperDualNumbers	v4.0.10	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
JSOSolvers	v0.14.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
Lehmann	v0.2.7	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
GreenFunc	v0.2.6	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
ElectronGas	v0.2.6	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
TensorTrains	v0.12.1	fail	test	▇▇▅▅▇▅▇▅▅▇▅▅▇
IterativeRefinement	v0.2.1	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
HAdaptiveIntegration	v0.2.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
JacobiEigen	v1.0.1	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
RationalFunctionApproximation	v0.2.4	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
CaNNOLeS	v0.8.0	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇▇
NEFTInterface	v0.1.0	fail	load	▅▅▅▅▅▅▅▅▅▅▅▅▅
CaratheodoryFejerApprox	v0.1.0	fail	test	▇▇▇▅▅▅▅▅▇▇▇▇▇
CustomGaussQuadrature	v1.0.6	fail	test	▇▇▇▇▇▇▇▇▇▇▇▇
```

File: Compiler/src/abstractinterpretation.jl [hunk 2]
```diff
@@ -3485,7 +3485,57 @@ function refine_partial_type(@nospecialize t)
...
+                ai = abstract_eval_nonlinearized_foreigncall_name(interp, e.args[i], sstate, sv)
+                if !isready(ai)
+                    nextstate = 0x1
+                    return false
+                    @label state1
+                end
+                argtypes[i] = ai[].rt
+                i += 1
+            end
+            res = abstract_call(interp, ArgInfo(e.args, argtypes), sstate, sv)
```
Comment (vtjnash) [inline Compiler/src/abstractinterpretation.jl:3514]: IIRC, this call will occasionally corrupt the InferenceState structure for the current statement, since this is not actually the current statement (there might be some support code in return_type_tfunc for working around it though)

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/58872#issuecomment-3133231615) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/d2bbd0a_vs_90e3c1a/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

8 packages crashed on the previous version too.

## ✖ Packages that failed

**13 packages failed only on the current version.**

 - Package has test failures: 2 packages
 - Package tests unexpectedly errored: 1 packages
 - Networking-related issues were detected: 1 packages
 - Test duration exceeded the time limit: 9 packages

1187 packages failed on the previous version too.

## ✔ Packages that passed tests

**27 packages passed tests only on the current version.**

 - Other: 27 packages

5419 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**17 packages successfully loaded only on the current version.**

 - Other: 17 packages

3216 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

905 packages were skipped on the previous version too.



</details>

**Comment by JeffBezanson** [comment]
Failures look unrelated?

File: Compiler/src/abstractinterpretation.jl (hunk 2 above)
Comment (Keno) [reply Compiler/src/abstractinterpretation.jl:3514]: return_type_tfunc twiddles `restrict_abstract_call_sites`, but that's just a correctness issue for return_type. The world age side effect that we care about here will still be conservatively correct (though conservatively correct might still mess with out codegen, so not perfect, but better than before). I don't see it doing anything else that would be required here.

**Review by Keno — APPROVED** [review]
