### PR TITLE
fixes for the runtime (interpreted intrinsics)

### LINKED ISSUE #29379: tests known to fail in the interpreter
- [x] core.jl (setfield on an immutable throws a different error message)
- [x] checked.jl (runtime-intrinsic implementation problems?)
- [x] ~errorshow.jl (dispatch or type-system mistake? shows up as recursive StackOverflow)~~ moving to separate issue #29695
- [x] ~~math.jl (incorrect answers in sinh/cosh)~~ duplicate of #29400 / fixed by #29401.

### PR DESCRIPTION
**Pull request by vtjnash**
closes #29379

### CODE REVIEW

File: src/builtins.c [hunk 1]
```diff
@@ -677,10 +677,10 @@ JL_CALLABLE(jl_f_setfield)
         jl_type_error("setfield!", (jl_value_t*)jl_datatype_type, v);
     jl_datatype_t *st = (jl_datatype_t*)vt;
     if (!st->mutabl)
-        jl_errorf("type %s is immutable", jl_symbol_name(st->name->name));
+        jl_error("setfield! cannot change immutable struct");
```
Comment (ararslan) [inline src/builtins.c]: This seems strictly less informative than the previous text.

Comment (vtjnash) [reply src/builtins.c]: Yes, but it's an error message—how much do we want to care?

Comment (ararslan) [reply src/builtins.c]: If we don't care then why change it at all?

Comment (vtjnash) [reply src/builtins.c]: This isn't the text that you would usually see. That's text was emitted at https://github.com/JuliaLang/julia/pull/29721/files#diff-7a4c9160e84426f92c6790c4e8b14efaL2432

Comment (StefanKarpinski) [reply src/builtins.c]: > but it's an error message—how much do we want to care?

This is a terrible attitude. The quality of error messages is one of the primary things that makes people feel that a programming language is "helpful". For example, Elm gets rave reviews for the quality of the error messages. Similarly, in the past few years there's been a huge push to improve Rust's error messages with the very visible effect that what is still a fairly hard-to-learn language is considered to be much more usable than it once was.

If the other place where this message can be emitted from has a worse version of this message, then can we please change them both to be the better message instead of to the worse one?

**Comment by StefanKarpinski** [comment]
Does that mean that all tests pass in the interpreter now?

**Comment by KristofferC** [comment]
Does not backport cleanly. Please push backport to "backport-1.0.3" or make a rebased branch on top of that and I will backport the commits.

**Comment by KristofferC** [comment]
Doesn't seem the backport will happen.
