### PR TITLE
Stop exporting dot from LinearAlgebra.BLAS

### LINKED ISSUE #626: Both LinearAlgebra and LinearAlgebra.BLAS export dot
This is quite annoying:
```
julia> using LinearAlgebra

julia> using LinearAlgebra.BLAS

julia> dot
WARNING: both BLAS and LinearAlgebra export "dot"; uses of it in module Main must be qualified
ERROR: UndefVarError: dot not defined
```
It seems like BLAS should either extend `dot` from LinearAlgebra or not export its own `dot`.

### LINKED ISSUE #31838: Both LinearAlgebra and LinearAlgebra.BLAS export dot
This is quite annoying:
```
julia> using LinearAlgebra

julia> using LinearAlgebra.BLAS

julia> dot
WARNING: both BLAS and LinearAlgebra export "dot"; uses of it in module Main must be qualified
ERROR: UndefVarError: dot not defined
```
It seems like BLAS should either extend `dot` from LinearAlgebra or not export its own `dot`.

### PR DESCRIPTION
**Pull request by ararslan**
LinearAlgebra exports the familiar `dot` function. The BLAS submodule has its own `dot` function, which it also exports, leading to problems if a user tries to access `dot` after `using` both LinearAlgebra and BLAS.

Because this conflict currently exists, this change should be non-breaking, as it's difficult to resolve `dot` unqualified from BLAS before it's resolved from LinearAlgebra, so pretty much any consumer must already calling `BLAS.dot` as such.

Fixes JuliaLang/LinearAlgebra.jl#626.

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
@staticfloat: any idea what's up with these failures?

**Comment by staticfloat** [comment]
* `win32` tester failure: FileWatching test took 0.51 seconds when it needed to take < 0.5 seconds.  I restarted it.  (The windows buildbots occasionally see huge latency spikes due to running on OpenStack)
* `mac64` tester failure: Misconfiguration of buildbot due to me moving it to a new physical location; fixed and restarted.
* `freebsd64` build failure: Unknown; it got killed halfway through; I'm restarting it to see if it happens again.

File: stdlib/LinearAlgebra/src/blas.jl [hunk 1]
```diff
@@ -15,7 +15,6 @@ export
     axpy!,
     axpby!,
     blascopy!,
-    dot,
```
Comment (musm) [inline stdlib/LinearAlgebra/src/blas.jl]: maybe just comment it out, so it's clear that it's no longer exported ? 
`#dot` ?

**Comment by mbauman** [comment]
> as it's difficult to resolve `dot` unqualified from BLAS before it's resolved from LinearAlgebra

Not so difficult, but I agree that most everyone who is using this is probably just calling `BLAS.dot`.

```julia
julia> using LinearAlgebra.BLAS

julia> dot(3, [1.,2,3], 1, [1.,2,3], 1)
14.0 
```

**Review by StefanKarpinski — APPROVED** [review]
