### PR TITLE
Fix #37756: Correct formatting of hexadecimal imaginary parts

### LINKED ISSUE #37756: bad print format for Complex{Unsigned}
Complex number printing assumes that simple concatenation will produce something meaningful:
```
julia> 0x1e*im
0x00 + 0x1eim

julia> 0x1eim
ERROR: syntax: invalid numeric constant "0x1ei"
```

### PR DESCRIPTION
**Pull request by tsbranquinho**
The 'show' method for 'Complex' was not properly handling cases where the imaginary part was represented in hexadecimal ('0x'). This could lead to missing multiplication symbols '*' in the output, making the formatting inconsistent.

To fix this, a check using 'occursin("0x", repr(i))' was added to detect these cases and ensure proper formatting.

This improves the consistency of complex number representations and prevents ambiguities in the printed output.

### CODE REVIEW

File: base/complex.jl [hunk 1]
```diff
@@ -206,7 +206,7 @@ function show(io::IO, z::Complex)
         print(io, compact ? "+" : " + ")
         show(io, i)
     end
-    if !(isa(i,Integer) && !isa(i,Bool) || isa(i,AbstractFloat) && isfinite(i))
+    if !(isa(i,Integer) && !isa(i,Bool) || isa(i,AbstractFloat) && isfinite(i)) || occursin("0x",repr(i))
```
Comment (LilithHafner) [inline base/complex.jl:209]: This is a good rule but it is better to implement it with a type check.
```suggestion
    if !(isa(i,Signed) || isa(i,AbstractFloat) && isfinite(i))
```

**Review by LilithHafner — COMMENTED** [review]
Thanks for working on this! You have a good solution and should also add tests to make sure it works as expected.

File: test/complex.jl [hunk 2]
```diff
@@ -1,6 +1,7 @@
 # This file is a part of Julia. License is MIT: https://julialang.org/license
 
 using LinearAlgebra
+using Test
```
Comment (LilithHafner) [inline test/complex.jl:4]:
```suggestion
```
We don't actually need a `using Test` here. Because of the way these files are included we can assume that `Test` is loaded beforehand.

**Review by LilithHafner — COMMENTED** [review]
Lovely tests, thanks!

**Comment by tsbranquinho** [comment]
Hey @LilithHafner, I have applied the suggested changes.  
Let me know if there's anything else I should update.  
Thanks for the review, I appreciate the feedback!

**Review by LilithHafner — APPROVED** [review]
Thanks! This looks good to me (LGTM). We'll wait to make sure that CI passes (or at least all the checks that pass on master also pass here) and then merge. Thank you for you contribution!

**Review by JeffBezanson — APPROVED** [review]
