### PR TITLE
Run FD stress test in separate process

### LINKED ISSUE #23143: FreeBSD CI workers got ENOMEM randomly
```julia
ERROR (unhandled task failure): write: not enough memory (ENOMEM)
Stacktrace:
 [1] try_yieldto at ./event.jl:189 [inlined]
 [2] wait() at ./event.jl:248
 [3] uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:811
 [4] unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:832
 [5] write(::Pipe, ::String) at ./strings/string.jl:71
 [6] write_cookie(::Base.Process) at ./distributed/cluster.jl:1120
 [7] launch(::Base.Distributed.LocalManager, ::Dict{Any,Any}, ::Array{WorkerConfig,1}, ::Condition) at ./distributed/managers.jl:328
 [8] (::Base.Distributed.##39#42{Base.Distributed.LocalManager,Dict{Any,Any}})() at ./event.jl:73
```

But the available memory observed from `top` on each work is enough.

Not sure it's bsd only issue or not. 

Ref builds:
1. https://julia.iblis.cnmc.tw/#/builders/1/builds/903
2. https://julia.iblis.cnmc.tw/#/builders/1/builds/887
3. https://julia.iblis.cnmc.tw/#/builders/1/builds/891
4. https://julia.iblis.cnmc.tw/#/builders/1/builds/772
...

### LINKED ISSUE #35011: `test/stress.jl` should be run with special `ulimit` applied
The [pipe fd exhaustion test](https://github.com/JuliaLang/julia/blob/master/test/stress.jl#L3-L26) should be run in its own process with a low `ulimit` applied such that we don't need to allocate potentially hundreds of thousands of pipes; this can result in nasty errors such as on FreeBSD where the kernel returns `ENOMEM` on `write()` in certain rare cases.

### PR DESCRIPTION
**Pull request by Keno**
As noted in #35011, the `stress` test is likely causing ENOMEM
errors in unrelated processes on FreeBSD as it's causing kernel
resource exhaustion. This fixes that by running that test with
a low FD ulimit (100). Should fix #23143. Closes #35011.

### CODE REVIEW

File: test/stress.jl [hunk 1]
```diff
@@ -2,27 +2,9 @@
...
-        catch ex
-            isa(ex, Base.IOError) || rethrow()
-            @test ex.code in (Base.UV_EMFILE, Base.UV_ENFILE)
-        finally
-            foreach(close, ps)
-        end
-    end
+    # Run this test with a really small ulimit. If the ulimit is too high,
+    # we might saturate kernel resources (See #23143)
+    run(`sh -c "ulimit -n 100; $(Base.shell_escape(Base.julia_cmd())) --startup-file=no $(joinpath(@__DIR__, "stress_fd_exec.jl"))"`)
```
Comment (vtjnash) [inline test/stress.jl]: Shouldn’t the whole command (especially the user path) have been inside the shell_escape call?
