### PR TITLE
process and pipe cleanup

### LINKED ISSUE #9659: use of open() results or filehandles
[novice warning]

per the discussion in https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!searchin/julia-users/reading$20compressed$20csv/julia-users/1C97f24SmKo/2K5c2OdAV94J and https://github.com/JuliaLang/julia/pull/6948 

I would suggest that all functions that work with a part of the tuple returned by open() also work with the full tuple.  in particular, I would like to see familiar language constructs like the following to "just work":

```
close(open(...))
fs=open(`cat file.csv`); readcsv(fs); close(fs);
```

having to index fs is neither intuitive nor necessary.

regards,

/iaw

### LINKED ISSUE #11824: Add STDERR pipe to `readandwrite`
Sometimes it is necessary to have access to a process' STDIN, STDOUT and STDERR. In my case, I need to open pipes to an external command (specifically, `gnuplot`) that outputs text to both STDOUT and STDERR. With current command `readandwrite()`, I can't read STDERR. This is on both 0.3 and master.

I can redirect the process' STDERR to a file with `pipe()`, but that is not good enough in my case. The reason is that the process is long-lived; I want to issue a command to it by writing to its STDIN, and then read both STDOUT and STDERR to see if the command was successful. This may be repeated any number of times.

I have tried redirecting STDERR to a `PipeBuffer`, but it doesn't work:

    julia> S=PipeBuffer(1024)
    IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=false, append=true, size=0, maxsize=1024, ptr=1, mark=-1)
    julia> readandwrite(pipe(`gnuplot`, stderr=S))
    ERROR: MethodError: `redir_err` has no method matching redir_err(::Cmd, ::Base.AbstractIOBuffer{Array{UInt8,1}})

### LINKED ISSUE #12176: InexactError on failed spawn
backtrace:
```
ERROR: InexactError()
 in uv_return_spawn at process.jl:242
```

### PR DESCRIPTION
**Pull request by vtjnash**
this is a grab-bag of various fixes to the Process and Pipe handling. I'm sticking all of these together to try to minimize the incremental API churn and breakage:
- this includes and thus replaces #11919 (which also fixes #11824)
- ~~fixes #9659 by changing `open(Cmd)` to only return a Process, defining IO operations on Process, and defining `close(Process)` to mean `close(Process.in) && close(Process.out)`. this is a breaking change, since i know of no way to sanely provide a deprecation for this (I would prefer not to define iteration over a Process object as returning the old tuple of `(io, process)`)~~ [this item is moving to a new PR]
- makes Cmd objects immutable and other general API cleanup utilizing various new features in Julia like keyword arguments, immutable types
- this deletes all usages of `Intrinsics.Box(Ptr{Void},Intrinsics.jl_alloca(size))` from Base (preferring the possibility of a small memory leak in exceptional cases instead of segfaults), in preparation for deprecating this intrinsic function
- does stdio setup in generic functional style rather than hard coded case statements and macros
- adds a few more methods to DevNull (ref #12050), although its still short of the list implemented for `Pipe`
- also fixes #12176 (inexact error on spawn on windows)

### CODE REVIEW

File: base/process.jl [hunk 1]
```diff
@@ -81,7 +88,15 @@ end
 
 immutable DevNullStream <: AsyncStream end
 const DevNull = DevNullStream()
+isreadable(::DevNullStream) = false
+iswritable(::DevNullStream) = true
+isopen(::DevNullStream) = true
+read{T<:DevNullStream}(::T, args...) = throw(EOFErorr())
+write{T<:DevNullStream}(::T, args...) = 0
```
Comment (JeffBezanson) [inline base/process.jl]: This might be ok for now but I'm not sure it's right. Semantically, I believe all bytes are successfully written to DevNull.

Comment (vtjnash) [inline base/process.jl]: i think you're right, i just don't know if there is a good way to generically compute the number of bytes that got "written"

**Comment by JeffBezanson** [comment]
Awesome!! Looks really good.

Very happy to see jl_alloca go away. Do any packages use it? Would be best to remove it entirely.

It looks like the fix for #12176 can be split out? Maybe the DevNull changes too?

**Comment by JeffBezanson** [comment]
Also, I'm pretty sure you meant this replaces #11919, not #12113?

**Comment by vtjnash** [comment]
> Also, I'm pretty sure you meant this replaces #11919, not # 12113?

fixed. i have no idea how that got into my paste buffer

> It looks like the fix for #12176 can be split out? Maybe the DevNull changes too?

yes they could. i put them all together here mostly to see if there would be any overlapping API decisions. i generally try to structure many of my commits so that they are relatively independent and could be reordered or dropped as needed.

> Very happy to see jl_alloca go away. Do any packages use it? Would be best to remove it entirely.

I'm not sure, so the deprecation should happen in a separate PR.

**Comment by JeffBezanson** [comment]
Looks like a small memory leak can only happen if `link_pipe` fails? In that case, would it make sense to put link_pipe inside the try-finally block in `spawn`?

**Comment by vtjnash** [comment]
to do it right, you would need to figure out how far into setting up stdio it got and then unwind those steps (starting at https://github.com/JuliaLang/julia/pull/12739/files#diff-ab46297895850308343e9cbd5ebeb6cdR392). it would be a good improvement (the old code didn't do it either)

File: base/process.jl (hunk 1 above)
Comment (Keno) [inline base/process.jl]: That's what `sizeof` is for.

**Comment by sbromberger** [comment]
Thank you for including #12050.

**Comment by IainNZ** [comment]
> Very happy to see jl_alloca go away. Do any packages use it? Would be best to remove it entirely. 
https://github.com/search?l=julia&q=jl_alloca&type=Code&utf8=%E2%9C%93

Looks like no, except for various forks of Julia

**Comment by ViralBShah** [comment]
Is this good to merge now? Looks like the last major thing in the way for 0.4 RCs.

**Comment by vtjnash** [comment]
yes. however, since this is breaking for the definition of `open(cmd)`, i was thinking of merging this as close to the branch point as possible, so that writing the deprecation in packages is a simpler test `>v"0.4.0-dev"`

**Comment by StefanKarpinski** [comment]
That is literally the worst reason to delay merging something I've ever heard.

**Comment by ivarne** [comment]
> That is literally the worst reason to delay merging something I've ever heard.

+1

**Comment by vtjnash** [comment]
That's my deadline for hitting the merge button. I won't hinder anyone else from merging it sooner.

**Comment by ViralBShah** [comment]
Please merge. We are pretty close to the branch point.

**Comment by StefanKarpinski** [comment]
@JeffBezanson, please merge if you're happy with this.

**Comment by JeffBezanson** [comment]
My main concern is that the change to `open` has not really been discussed at all. All we wanted was to make it easier to read stderr, and I don't think changing `open` is necessary to do that. (There are also bug fixes applicable to master bundled in here, which annoys me extremely, but that's a much smaller issue right now.)

**Comment by vtjnash** [comment]
agreed, i've taken out the change to `open` in a separate revert commit so that this PR is no longer breaking and can be be merged once CI passes. Later, I'll open a second PR to revert that last commit, with more focused discussion. Including it here was initially helpful since it helped me test out these changes and account for the overlapping functionality, but the actual change doesn't need to happen in this PR merge.

**Comment by JeffBezanson** [comment]
That's great; then we can merge this ASAP.

**Comment by vtjnash** [comment]
> That's great; then we can merge this ASAP.

yep, that was exactly the point. and as promised, the new PR is https://github.com/JuliaLang/julia/pull/12807

**Comment by JeffBezanson** [comment]
Note: needs `NEWS` update for the rename of pipe, and to mention `Pipe()`.
