### PR TITLE
 fix compile=all, move code related to static compilation to precompile.c

### LINKED ISSUE #21141: World age failure when running GtkReactive demo
When running the `examples/drawing.jl` demo under
```julia
julia> versioninfo()
Julia Version 0.6.0-pre.alpha.229
Commit cc917b5 (2017-03-22 21:53 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
and **if** GtkReactive needs to be rebuilt, I get the following error when I click on the canvas:
```julia
julia> include("drawing.jl")
INFO: Recompiling stale cache file /home/tim/.julia/lib/v0.6/GtkReactive.ji for module GtkReactive.
Gtk.GtkWindowLeaf(name="", parent, width-request=-1, height-request=-1, visible=TRUE, sensitive=TRUE, app-paintable=FALSE, can-focus=FALSE, has-focus=FALSE, is-focus=FALSE, can-default=FALSE, has-default=FALSE, receives-default=FALSE, composite-child=FALSE, style, events=0, no-show-all=FALSE, has-tooltip=FALSE, tooltip-markup=NULL, tooltip-text=NULL, window, opacity=1.000000, double-buffered, halign=GTK_ALIGN_FILL, valign=GTK_ALIGN_FILL, margin-left, margin-right, margin-start=0, margin-end=0, margin-top=0, margin-bottom=0, margin=0, hexpand=FALSE, vexpand=FALSE, hexpand-set=FALSE, vexpand-set=FALSE, expand=FALSE, scale-factor=1, border-width=0, resize-mode, child, type=GTK_WINDOW_TOPLEVEL, title="Drawing", role=NULL, resizable=TRUE, modal=FALSE, window-position=GTK_WIN_POS_NONE, default-width=-1, default-height=-1, destroy-with-parent=FALSE, hide-titlebar-when-maximized=FALSE, icon, icon-name=NULL, screen, type-hint=GDK_WINDOW_TYPE_HINT_NORMAL, skip-taskbar-hint=FALSE, skip-pager-hint=FALSE, urgency-hint=FALSE, accept-focus=TRUE, focus-on-map=TRUE, decorated=TRUE, deletable=TRUE, gravity=GDK_GRAVITY_NORTH_WEST, transient-for, attached-to, has-resize-grip, resize-grip-visible, application, is-active=TRUE, has-toplevel-focus=TRUE, startup-id, mnemonics-visible=FALSE, focus-visible=FALSE, is-maximized=FALSE)

julia> Failed to push!
    GtkReactive.MouseButton{GtkReactive.UserUnit}(GtkReactive.XY{GtkReactive.UserUnit}(GtkReactive.UserUnit(0.208377685546875), GtkReactive.UserUnit(0.3292300415039063)), 0x00000001, 4, 0)
to node
    Signal{GtkReactive.MouseButton{GtkReactive.UserUnit}}(GtkReactive.MouseButton{GtkReactive.UserUnit}(GtkReactive.XY{GtkReactive.UserUnit}(GtkReactive.UserUnit(0.208377685546875), GtkReactive.UserUnit(0.3292300415039063)), 0x00000001, 4, 0), nactions=1)
MethodError: no method matching (::##3#4)(::GtkReactive.MouseButton{GtkReactive.UserUnit})
The applicable method may be too new: running in world age 21622, while current world is 21627.
Closest candidates are:
  #3(::Any) at /home/tim/.julia/v0.6/GtkReactive/examples/drawing.jl:13 (method too new to be called from this world context.)
(::Reactive.##10#11{##3#4,Tuple{Reactive.Signal{GtkReactive.MouseButton{GtkReactive.UserUnit}}}})(::Reactive.Signal{Void}, ::Int64) at /home/tim/.julia/v0.6/Reactive/src/operators.jl:39
do_action(::Reactive.Action, ::Int64) at /home/tim/.julia/v0.6/Reactive/src/core.jl:141
run(::Int64) at /home/tim/.julia/v0.6/Reactive/src/core.jl:218
macro expansion at /home/tim/.julia/v0.6/Reactive/src/core.jl:258 [inlined]
(::Reactive.##7#8)() at ./task.jl:335
Failed to push!
    GtkReactive.MouseButton{GtkReactive.UserUnit}(GtkReactive.XY{GtkReactive.UserUnit}(GtkReactive.UserUnit(0.1935784912109375), GtkReactive.UserUnit(0.7561200714111328)), 0x00000001, 7, 256)
to node
    Signal{GtkReactive.MouseButton{GtkReactive.UserUnit}}(GtkReactive.MouseButton{GtkReactive.UserUnit}(GtkReactive.XY{GtkReactive.UserUnit}(GtkReactive.UserUnit(0.1935784912109375), GtkReactive.UserUnit(0.7561200714111328)), 0x00000001, 7, 256), nactions=1)
MethodError: no method matching (::##7#8)(::GtkReactive.MouseButton{GtkReactive.UserUnit})
The applicable method may be too new: running in world age 21622, while current world is 21627.
Closest candidates are:
  #7(::Any) at /home/tim/.julia/v0.6/GtkReactive/examples/drawing.jl:25 (method too new to be called from this world context.)
(::Reactive.##10#11{##7#8,Tuple{Reactive.Signal{GtkReactive.MouseButton{GtkReactive.UserUnit}}}})(::Reactive.Signal{Void}, ::Int64) at /home/tim/.julia/v0.6/Reactive/src/operators.jl:39
do_action(::Reactive.Action, ::Int64) at /home/tim/.julia/v0.6/Reactive/src/core.jl:141
run(::Int64) at /home/tim/.julia/v0.6/Reactive/src/core.jl:218
macro expansion at /home/tim/.julia/v0.6/Reactive/src/core.jl:258 [inlined]
(::Reactive.##7#8)() at ./task.jl:335
```

However, it seems to work fine if GtkReactive didn't need to be recompiled.

For you convenience I did a `egrep "pure|generated|eval" *` in every package that gets loaded for that demo, looking for language constructs that might be suspicious; results are in [this gist](https://gist.github.com/timholy/beaf63ec8f97dd30ba50f82ba644339a).

### PR DESCRIPTION
**Pull request by JeffBezanson**
More moving stuff around. I think it will be useful to have a dedicated file for static-compilation-related stuff.

fix https://github.com/JuliaLang/julia/issues/21141

### CODE REVIEW

File: src/compileout.c [hunk 1]
```diff
@@ -0,0 +1,442 @@
...
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+JL_DLLEXPORT int jl_generating_output(void)
+{
+    return jl_options.outputo || jl_options.outputbc || jl_options.outputji;
+}
+
+void jl_precompile(int all);
```
Comment (vtjnash) [inline src/compileout.c]: should be in a header file

File: src/compileout.c [hunk 2]
```diff
@@ -0,0 +1,442 @@
...
+
+        if (jl_options.outputo || jl_options.outputbc)
+            jl_dump_native(jl_options.outputbc,
+                           jl_options.outputo,
+                           (const char*)s->buf, (size_t)s->size);
+    }
+    JL_GC_POP();
+}
+
+int jl_is_rettype_inferred(jl_method_instance_t *li);
```
Comment (vtjnash) [inline src/compileout.c]: should be in a header also

File: src/compileout.c [hunk 3]
```diff
@@ -0,0 +1,442 @@
...
+        return 0;
+    jl_code_info_t *src = NULL;
+    if (!jl_is_rettype_inferred(li))
+        src = jl_type_infer(&li, world, 0);
+    if (li->jlcall_api != 2)
+        jl_compile_linfo(&li, src, world, &jl_default_cgparams);
+    return 1;
+}
+
+#if 0  // TODO restore this for jb/subtype
```
Comment (vtjnash) [inline src/compileout.c]: probably should be restored, in order to make sure this code movement isn't breaking anything here

**Review by vtjnash — COMMENTED** [review]
compileout doesn't seem like the best name choice

**Comment by JeffBezanson** [comment]
Suggest a name?

File: src/compileout.c (hunk 3 above)
Comment (JeffBezanson) [inline src/compileout.c]: Ok, I'll do that as part of this PR.

**Comment by vtjnash** [comment]
This seems pretty tightly coupled to the rest of `gf.c` to me. I'm not sure this code movement is worthwhile.

**Comment by JeffBezanson** [comment]
This code does something pretty specific: traversing modules to find everything that needs to be compiled for compile=all. In theory, if you were never going to use compile=all you could exclude this code from the build. Sure it uses Method and MethodInstance a fair amount, but so do several other files. `gf.c` is also coupled to `typemap.c`, but they can quite sensibly be separate files since typemap.c implements a data structure and gf.c mostly implements caching algorithms on top of it.

**Comment by vtjnash** [comment]
TypeMap is a fairly general concept though, and can get reused elsewhere. The compile-all code is pretty tightly coupled with the precompile and caching logic. Sure, doesn't mean this can't move, it just means I don't have a clear idea of what categorization this should have. Maybe `precompile.c` would be a better name?

**Comment by JeffBezanson** [comment]
`precompile.c` is fine with me. It would be nice if we could move some of the module precompile code there eventually, to make a single integrated binary-artifact-generator, but that code really is quite coupled with dump.c.

I would say this code is anti-reusable: it's not used by anything else in the system, and is actually an application of various reusable mechanisms that exist elsewhere, such as looking up specializations and traversing typemaps. I'm looking toward the idea of a `juliac` program separable from the julia runtime, where we want the runtime to consist of the minimal stuff needed to run any julia code.

**Comment by JeffBezanson** [comment]
Ok, I think I have compile=all working.

**Comment by tkelman** [comment]
CI will be broken until the S3 outage is resolved.

File: src/jltypes.c [hunk 4]
```diff
@@ -307,6 +307,32 @@ static int count_union_components(jl_value_t **types, size_t n)
...
 }
 
+int jl_count_union_components(jl_value_t *v)
+{
+    if (!jl_is_uniontype(v)) return 1;
+    jl_uniontype_t *u = (jl_uniontype_t*)v;
+    return jl_count_union_components(u->a) + jl_count_union_components(u->b);
+}
+
+static jl_value_t *nth_union_component(jl_value_t *v, int *pi)
```
Comment (vtjnash) [inline src/jltypes.c]: needs comments

File: src/precompile.c [hunk 5]
```diff
@@ -0,0 +1,385 @@
...
+        }
+
+        //// infer this function now, if necessary
+        if (linfo->jlcall_api == 2)
+            continue;
+        src = jl_type_infer(&linfo, jl_world_counter, 1);
+        m->unspecialized = linfo;
+        jl_gc_wb(m, linfo);
+        if (linfo->jlcall_api == 2)
+            continue;
```
Comment (vtjnash) [inline src/precompile.c]: don't uncomment this - this is completely invalid right now.

File: src/precompile.c [hunk 6]
```diff
@@ -0,0 +1,385 @@
...
+
+        // keep track of whether all possible signatures have been cached (and thus whether it can skip trying to compile the template function)
+        // this is necessary because many intrinsics try to call static_eval and thus are not compilable unspecialized
+        int complete = _compile_all_union((jl_value_t*)ml->sig);
+        if (complete) {
```
Comment (vtjnash) [inline src/precompile.c]: can delete this branch test now (the comment about intrinsics calling static_eval is incorrect)

File: src/precompile.c [hunk 7]
```diff
@@ -0,0 +1,385 @@
...
+            if (linfo->fptr == NULL && linfo->functionObjectsDecls.functionObject == NULL)
+                // indicate that this method doesn't need to be compiled, because it was fully covered above
+                // TODO: do this some other way
+                linfo->fptr = (jl_fptr_t)(uintptr_t)-1;
+        }
+        else {
+            jl_compile_linfo(&linfo, src, jl_world_counter, &jl_default_cgparams);
+            assert(linfo->functionObjectsDecls.functionObject != NULL);
+            m->unspecialized = linfo;
```
Comment (vtjnash) [inline src/precompile.c]: this'll corrupt the system. don't store an inferred object here.

File: src/precompile.c [hunk 8]
```diff
@@ -0,0 +1,385 @@
...
+            jl_gc_wb(m, linfo);
+        }
+    }
+    JL_GC_POP();
+    jl_printf(JL_STDERR, "\n");
+}
+
+static void foreach_def_in_module(jl_module_t *m, int (*visit)(jl_typemap_entry_t *, void*), jl_array_t *out)
```
Comment (vtjnash) [inline src/precompile.c]: `visit` should be a `jl_typemap_visitor_fptr` type

File: src/precompile.c (hunk 6 above)
Comment (JeffBezanson) [inline src/precompile.c]: Yes you're right about static_eval, but isn't it still true that we don't need to compile an `unspecialized` method if the signature is a leaf type or union of leaf types?

File: src/precompile.c (hunk 5 above)
Comment (JeffBezanson) [inline src/precompile.c]: Why is that?

Should I set `src = m->source` instead?

File: src/precompile.c (hunk 6 above)
Comment (vtjnash) [inline src/precompile.c]: That's going to depend on how we want to define the behavior of the compile=all output. Branching on isleaftype is also valid. I guess the main point is just that this is now just an optimization (while before it was a crutch that was needed for handling intrinsics).

File: src/precompile.c (hunk 5 above)
Comment (vtjnash) [inline src/precompile.c]: the `unspecialized` field is not world-aware, so it can't store world-specialized data. Yes, use `src = m->source`.

**Comment by JeffBezanson** [comment]
Comments addressed. However, this doesn't seem to quite do what we want. If I try building a system image with this, I still get lots of `code missing` warnings with `compile=no`. What am I doing wrong?

**Comment by JeffBezanson** [comment]
Adding to milestone since we need to fix compile=all for the release.

**Comment by vtjnash** [comment]
this gets it much closer for me:
```diff
diff --cc src/gf.c
index 5651e279d1,e07378ca58..0000000000
--- a/src/gf.c
+++ b/src/gf.c
diff --git a/base/interactiveutil.jl b/base/interactiveutil.jl
index 1d569265a3..12663bb923 100644
--- a/base/interactiveutil.jl
+++ b/base/interactiveutil.jl
@@ -61,9 +61,10 @@ function edit(path::AbstractString, line::Integer=0)
     end
 
     if is_windows() && name == "open"
-        systemerror(:edit, ccall((:ShellExecuteW,"shell32"), stdcall, Int,
-                                 (Ptr{Void}, Cwstring, Cwstring, Ptr{Void}, Ptr{Void}, Cint),
-                                 C_NULL, "open", path, C_NULL, C_NULL, 10) ≤ 32)
+        @static is_windows() && # don't emit this ccall on other platforms
+            systemerror(:edit, ccall((:ShellExecuteW, "shell32"), stdcall, Int,
+                                     (Ptr{Void}, Cwstring, Cwstring, Ptr{Void}, Ptr{Void}, Cint),
+                                     C_NULL, "open", path, C_NULL, C_NULL, 10) ≤ 32)
     elseif background
         spawn(pipeline(cmd, stderr=STDERR))
     else
```
```diff
diff --git a/src/dump.c b/src/dump.c
index dc9a97ed79..5d6bc80aa3 100644
--- a/src/dump.c
+++ b/src/dump.c
@@ -422,7 +422,15 @@ static void jl_update_all_fptrs(void)
 {
     //jl_printf(JL_STDOUT, "delayed_fptrs_n: %d\n", delayed_fptrs_n);
     void **fvars = sysimg_fvars;
-    if (fvars == 0) return;
+    if (fvars == NULL) {
+        size_t i;
+        for (i = 0; i < delayed_fptrs_n; i++) {
+            jl_method_instance_t *li = delayed_fptrs[i].li;
+            assert(li->jlcall_api && li->jlcall_api != 2);
+            li->jlcall_api = 0;
+        }
+        return;
+    }
     // jl_fptr_to_llvm needs to decompress some ASTs, therefore this needs to be NULL
     // to skip trying to restore GlobalVariable pointers in jl_deserialize_gv
     sysimg_gvars = NULL;
@@ -431,7 +439,7 @@ static void jl_update_all_fptrs(void)
     jl_method_instance_t **linfos = (jl_method_instance_t**)malloc(sizeof(jl_method_instance_t*) * sysimg_fvars_max);
     for (i = 0; i < delayed_fptrs_n; i++) {
         jl_method_instance_t *li = delayed_fptrs[i].li;
-        assert(li->def);
+        assert(li->def && li->jlcall_api && li->jlcall_api != 2);
         int32_t cfunc = delayed_fptrs[i].cfunc - 1;
         if (cfunc >= 0) {
             jl_fptr_to_llvm((jl_fptr_t)fvars[cfunc], li, 1);
```
```diff
diff --git a/src/precompile.c b/src/precompile.c
index 909e180b5d..e34ff9a81b 100644
--- a/src/precompile.c
+++ b/src/precompile.c
@@ -266,14 +266,14 @@ static void _compile_all_deq(jl_array_t *found)
         int complete = _compile_all_union((jl_value_t*)ml->sig);
         // if _compile_all_union returns 1, all possible signatures have been covered, so we don't
         // need to compile an unspecialized version.
-        if (complete) {
+        if (0) {
             if (linfo->fptr == NULL && linfo->functionObjectsDecls.functionObject == NULL)
                 // indicate that this method doesn't need to be compiled, because it was fully covered above
                 // TODO: do this some other way
                 linfo->fptr = (jl_fptr_t)(uintptr_t)-1;
         }
         else {
-            jl_compile_linfo(&linfo, src, jl_world_counter, &jl_default_cgparams);
+            jl_compile_linfo(&linfo, src, linfo->min_world, &jl_default_cgparams);
             assert(linfo->functionObjectsDecls.functionObject != NULL);
         }
     }
```

**Comment by vtjnash** [comment]
Should be entirely fixed now.

File: src/precompile.c [hunk 9]
```diff
@@ -0,0 +1,363 @@
...
+        // TODO: the `unspecialized` field is not yet world-aware, so we can't store
+        // an inference result there.
+        //src = jl_type_infer(&linfo, jl_world_counter, 1);
+        //m->unspecialized = linfo;
+        //jl_gc_wb(m, linfo);
+        //if (linfo->jlcall_api == 2)
+        //    continue;
+
+        _compile_all_union((jl_value_t*)ml->sig);
+        // if _compile_all_union returns 1, all possible signatures have been covered, so we don't
```
Comment (JeffBezanson) [inline src/precompile.c]: Is this comment not true any more?

File: src/precompile.c [hunk 10]
```diff
@@ -0,0 +1,363 @@
...
+    return 1;
+}
+
+
+static void compile_all_enq_(jl_methtable_t *mt, void *env)
+{
+    jl_typemap_visitor(mt->defs, compile_all_enq__, env);
+}
+
+void jl_foreach_mtable_in_module(
```
Comment (JeffBezanson) [inline src/precompile.c]: Where is this defined?

Comment (vtjnash) [inline src/precompile.c]: gf.c

File: src/precompile.c (hunk 9 above)
Comment (vtjnash) [inline src/precompile.c]: Not really, no. The main culprit is inference, which runs in its own world. But it was also only ever intended as a work-around hack for the duct tape, so it's simpler to just remove this now that intrinsics no longer require this.

Comment (JeffBezanson) [inline src/precompile.c]: I don't quite get it. I thought the idea of the return value of `_compile_all_union` was that we didn't need to infer or compile an unspecialized version, since the signature is equivalent to a set of concrete signatures.

**Comment by timholy** [comment]
Thanks folks! (Ref #21141)
