### PR TITLE
heap snapshot: add gc roots and gc finalist roots to fix unrooted nodes

### LINKED ISSUE #52432: Heapsnapshot has some unrooted objects
The heapsnapshots seem to be missing either some edges or maybe some roots, or maybe both, but somehow many objects end up not retained by any roots, which is of course nonsense, since they couldn't have been exported if they're not reachable from a root (since unrooted things are garbage).

You can see that in this simple repro:
```julia
julia> using Profile

julia> Profile.take_heap_snapshot("1.11.0-DEV.638.heapsnapshot")
"1.11.0-DEV.638.heapsnapshot"
```
[1.11.0-DEV.638.heapsnapshot.zip](https://github.com/JuliaLang/julia/files/13592248/1.11.0-DEV.638.heapsnapshot.zip)

You can see in the screenshot that the roots are only retaining 87% of the heap snapshot. (in another attempt, i got only 5,000 bytes out of 120 MB!)
Screenshot 2023-12-06 at 3 25 50 PM

And you can see here that one random object has retainers that don't terminate in a root:

Screenshot 2023-12-06 at 3 27 57 PM

From randomly clicking around so far, it seems to often be Arrays that aren't parented, and so i wonder if we're missing some edge somewhere for arrays?

### PR DESCRIPTION
**Pull request by JianFangAtRai**
This PR is to fix the issue: https://github.com/JuliaLang/julia/issues/52432

1. Added logic to check unrooted nodes by looking at nodes without any incoming edges when serializing the heap snapshot
2. Fixed unrooted nodes from gc_mark_roots and added a GC root to them
3. Fixed unrooted nodes from gc_mark_finlist and added a finlist root to them
4. Fixed gc_mark_module_binding and put back gc_heap_snapshot_record_module_to_binding
5. Added assertion for zero unrooted nodes when serialize heap snapshot so that we could catch any regression

Before the fix, we have hundreds of unrooted nodes while taking a heapsnapshot of the julia process.

```
julia> using Profile
julia> Profile.take_heap_snapshot("jf-julia.heapsnapshot")
node count: 1041177
edge count: 3453348
orphan node count: 184
orphan nodes: ["5147","5149","5553","5555","7678","7680","8176","8178","9220","9222","11772","11774","12747","12749","13899","13901","14704","14706","15121","15123","18432","18434","19168","19170","21244","21246","23269","23271","24093","24095","26844","26846","27663","27665","28370","28372","28475","28477","34062","34064","34256","34258","36015","36017","36467","36469","37120","37122","37528","37530","39239","39241","39362","39364","52876","52878","55525","55527","60283","60285","63028","63030","72342","72344","101263","101265","103270","103272","103605","103607","105531","105533","120615","120617","123648","123650","132677","132679","135160","135162","144572","144574","150328","150330","173130","173132","209504","209506","236797","236799","316892","316894","456927","456929","537338","537340","554866","554868","578863","578865","582952","582954","585451","585453","586423","586425","634063","634065","702923","702925","703422","703424","712207","712209","712634","712636","725533","725535","729698","729700","732614","732616","732667","732669","732744","732746","737171","737173","754904","754906","765460","765462","860312","860314","862032","862034","862619","862621","862695","862697","866102","866104","873182","873184","874234","874236","874556","874558","895852","895854","918476","918478","919418","919420","922516","922518","927599","927601","928244","928246","929233","929235","929956","929958","940564","940566","940921","940923","943767","943769","947934","947936","948984","948986","950690","950692","1013089","1013091","1014901","1014903","1016206","1016208","1040145","1040147"]
orphan node: {type:(4,object), name:(17,GenericMemory{:not_atomic, UInt16, Core.AddrSpace{Core}(0x00)}), id:(0xffffaa557750,5147), self_size:24, edge_count:1, trace_node_id:0, detachedness:0}
orphan node: {type:(8,jl_svec_t), name:(1045,SimpleVector), id:(0xffffaa557770,5149), self_size:3648, edge_count:454, trace_node_id:0, detachedness:0}
orphan node: {type:(4,object), name:(3830,GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}), id:(0xffffa7e2f820,5553), self_size:24, edge_count:1, trace_node_id:0, detachedness:0}
orphan node: {type:(8,jl_svec_t), name:(1045,SimpleVector), id:(0xffffa7e2f840,5555), self_size:1096, edge_count:135, trace_node_id:0, detachedness:0}
...
```

After the fix, the number of unrooted nodes is zero.

```
julia> using Profile
julia> Profile.take_heap_snapshot("jf-julia.heapsnapshot")
node count: 1041228
edge count: 3452686
orphan node count: 0
orphan nodes: []
"jf-julia.heapsnapshot"
```

The containment view on chrome DevTools:

julia-heapsnapshot-jf-test

Fixes #52432.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: src/gc-heap-snapshot.cpp [hunk 1]
```diff
@@ -170,6 +178,44 @@ void _add_internal_root(HeapSnapshot *snapshot)
...
+        snapshot->names.find_or_create_string_id("GC roots"), // edge label
+        snapshot->_gc_root_idx // to
+    });
+    snapshot->num_edges += 1;
+
+    // add a node for the gc finalizer list roots
+    snapshot->_gc_finlist_root_idx = snapshot->nodes.size();
+    Node gc_finlist_roots{
+        snapshot->node_types.find_or_create_string_id("synthetic"),
+        snapshot->names.find_or_create_string_id("GC finlist roots"), // name
```
Comment (vchuravy) [inline src/gc-heap-snapshot.cpp:205]:
```suggestion
        snapshot->names.find_or_create_string_id("GC finalizer list roots"), // name
```

**Comment by NHDaly** [comment]
Thanks for the reviews and the merge, @vchuravy, @vtjnash, @IanButterworth! Sorry I wasn't able to get to it because of the holidays, thanks for taking care of it. 😎
