### PR TITLE
Fix #38491: fix an abspath() edge case on Windows

### LINKED ISSUE #38491: abspath bug for relative directories
A bit of an edge case, but noticed this when looking at https://github.com/JuliaLang/julia/issues/23646 

Assume the current directory is `C:\Users\Mus\x`
```
julia> abspath("C:x")
"C:\\Users\\Mus\\x"  # correct


julia> abspath("X:x")
"X:x"  # should be "X:\x"
```

### PR DESCRIPTION
**Pull request by belamenso**
Fixes #38491.

### CODE REVIEW

**Comment by musm** [comment]
LGTM thanks!

**Review by musm — APPROVED** [review]

**Comment by musm** [comment]
I'll give it a day or two to let others also look and comment if they have something to say. Otherwise, ping me if I forget to merge.

File: base/path.jl [hunk 1]
```diff
@@ -390,7 +390,19 @@ normpath(a::AbstractString, b::AbstractString...) = normpath(joinpath(a,b...))
...
+        return normpath(isabspath(a) ? a : joinpath(pwd(),a))
+    else
+        pwd_drive, _ = splitdrive(pwd())
+        a_drive, a_nodrive = splitdrive(a)
+        if a_drive != "" && lowercase(pwd_drive) != lowercase(a_drive) && !isabspath(a)
+            return a_drive * normpath(joinpath(path_separator, a_nodrive))
+        else
+            return normpath(isabspath(a) ? a : joinpath(pwd(),a))
+        end
+    end
```
Comment (vtjnash) [inline base/path.jl:404]: I think there's some opportunity to minimize code duplication, as follows. This also handles looking at ENV when necessary, matching my observations of how `realpath` would handle these paths.
```suggestion
    if !isabspath(a)
        cwd = pwd()
        a_drive, a_nodrive = splitdrive(a)
        if a_drive != "" && lowercase(splitdrive(cwd)[1]) != lowercase(a_drive)
            cwd = get(ENV, "=" * a_drive, nothing) # check DOS directory
            if cwd === nothing || !endswith(cwd, '\\') || !isabspath(cwd)
                cwd = a_drive * path_separator
            end
            a = joinpath(cwd, a_nodrive)
        else
            a = joinpath(cwd, a)
        end
    end
    return normpath(a)
```

File: test/path.jl [hunk 2]
```diff
@@ -9,6 +9,23 @@
         @test isabspath(S(homedir()))
         @test !isabspath(S("foo"))
     end
+    if Sys.iswindows()
+        @testset "issue #38491" begin
```
Comment (vtjnash) [inline test/path.jl:13]:
```suggestion
        @testset "issue #38491" begin withenv("=X:" => nothing, "=Y:" => nothing) do
```

File: test/path.jl [hunk 3]
```diff
@@ -9,6 +9,23 @@
...
+            @test abspath("$(lowercase(drive))a") == "$(lowercase(drive))\\a"
+            @test abspath("$(uppercase(drive))a") == "$(uppercase(drive))\\a"
+            @test abspath(lowercase(drive)) == "$(lowercase(drive))\\"
+            @test abspath(uppercase(drive)) == "$(uppercase(drive))\\"
+
+            @test lowercase(abspath("$(pwd_drive)a\\b\\c")) == lowercase(joinpath(pwd(), "a\\b\\c"))
+            @test lowercase(abspath("$(pwd_drive)a")) == lowercase(joinpath(pwd(), "a"))
+            @test lowercase(abspath(lowercase(pwd_drive))) == lowercase("$(pwd())\\")
+            @test lowercase(abspath(uppercase(pwd_drive))) == lowercase("$(pwd())\\")
+        end
```
Comment (vtjnash) [inline test/path.jl:27]:
```suggestion
        end; end
```

File: test/path.jl [hunk 4]
```diff
@@ -9,6 +9,23 @@
         @test isabspath(S(homedir()))
         @test !isabspath(S("foo"))
     end
+    if Sys.iswindows()
+        @testset "issue #38491" begin
+            pwd_drive = uppercase(splitdrive(pwd())[1])
+            drive = if (pwd_drive != "X:") "X:" else "Y:" end
```
Comment (vtjnash) [inline test/path.jl:15]:
```suggestion
            drive = (pwd_drive == "X:") ? "Y:" : "X:"
```
optional style nit: this is a somewhat more canonical form

**Review by vtjnash — APPROVED** [review]
Thanks! I tested this and added some thoughts. PTAL and let me know what you think.

File: base/path.jl (hunk 1 above)
Comment (musm) [reply base/path.jl:404]: Why do we have to bother with DOS directories?

Comment (musm) [reply base/path.jl:404]: It would also be good to avoid   accessing environment variables, unless necessary.

Comment (musm) [reply base/path.jl:404]: @vtjnash  I just rereviewed your suggested changes.  I like the proposed updates, as they consolidate the code and is more readable. 

My only concern, do we really need to bother with the DOS checks (at a quick search I couldn't find a reference on them)? If they are not necessary, I think it would be good to remove them as it would avoid any issues checking environment variables with, e.g., race conditions etc. 
```
            cwd = get(ENV, "=" * a_drive, nothing) # check DOS directory
	            if cwd === nothing || !endswith(cwd, '\\') || !isabspath(cwd)
	                cwd = a_drive * path_separator
	            end
```

Comment (vtjnash) [reply base/path.jl:404]: We could assume `cwd = nothing` there (nothing in ENV). It won't match the Win32 system behavior, but it wouldn't necessarily be wrong either, since we don't claim that this function does.

File: base/path.jl [hunk 5]
```diff
@@ -390,7 +390,22 @@ normpath(a::AbstractString, b::AbstractString...) = normpath(joinpath(a,b...))
...
-abspath(a::String) = normpath(isabspath(a) ? a : joinpath(pwd(),a))
+function abspath(a::String)::String
+    if !isabspath(a)
+        cwd = pwd()
+        a_drive, a_nodrive = splitdrive(a)
+        if a_drive != "" && lowercase(splitdrive(cwd)[1]) != lowercase(a_drive)
+            cwd = get(ENV, "=" * a_drive, nothing) # check DOS directory
+            if cwd === nothing || !endswith(cwd, '\\') || !isabspath(cwd)
+                cwd = a_drive * path_separator
+            end
```
Comment (musm) [inline base/path.jl:401]:
```suggestion

```

File: base/path.jl [hunk 6]
```diff
@@ -390,7 +390,22 @@ normpath(a::AbstractString, b::AbstractString...) = normpath(joinpath(a,b...))
...
+            a = joinpath(cwd, a_nodrive)
```
Comment (musm) [inline base/path.jl:402]:
```suggestion
            cwd = a_drive * path_separator
            a = joinpath(cwd, a_nodrive)
```

**Review by musm — APPROVED** [review]

**Comment by musm** [comment]
unrelated test failures on linux
