### PR TITLE
effects: relax recursion detection for effects analysis

### LINKED ISSUE #45781: Intermittent test failure in math-effect test
Failure is test order dependent and reproducible with
```
JULIA_CPU_THREADS=1 ../julia runtests.jl LinearAlgebra/svd LinearAlgebra/pinv LinearAlgebra/givens LinearAlgebra/structuredbroadcast numbers copy math
Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 1
  Sys.total_memory() = 1007.822 GiB
  Sys.free_memory() = 992.748 GiB

Test                          (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LinearAlgebra/svd                  (1) |        started at 2022-06-22T03:20:39.381
LinearAlgebra/svd                  (1) |    50.03 |   2.66 |  5.3 |    7520.24 |   665.83
LinearAlgebra/pinv                 (1) |        started at 2022-06-22T03:21:29.526
LinearAlgebra/pinv                 (1) |     9.04 |   0.66 |  7.3 |    1456.71 |   839.06
LinearAlgebra/givens               (1) |        started at 2022-06-22T03:21:38.564
LinearAlgebra/givens               (1) |     4.25 |   0.21 |  5.0 |     441.16 |   848.18
LinearAlgebra/structuredbroadcast  (1) |        started at 2022-06-22T03:21:42.814
LinearAlgebra/structuredbroadcast  (1) |    33.33 |   2.27 |  6.8 |    4345.93 |   909.84
numbers                            (1) |        started at 2022-06-22T03:22:16.142
numbers                            (1) |    48.12 |   1.14 |  2.4 |    4384.62 |  1356.91
copy                               (1) |        started at 2022-06-22T03:23:04.259
copy                               (1) |     2.52 |   0.09 |  3.4 |     277.91 |  1356.91
math                               (1) |        started at 2022-06-22T03:23:06.782
┌ Warning: bad effects found for sin(::Float32)
│   eff = (+c,+e,?n,?t,+s)
└ @ Main.Test6Main_math ~/julia/test/math.jl:1467
┌ Warning: bad effects found for cos(::Float32)
│   eff = (+c,+e,?n,?t,+s)
└ @ Main.Test6Main_math ~/julia/test/math.jl:1467
┌ Warning: bad effects found for tan(::Float32)
│   eff = (+c,+e,?n,?t,+s)
└ @ Main.Test6Main_math ~/julia/test/math.jl:1467
math                               (1) |    36.14 |   1.31 |  3.6 |    4391.28 |  1625.89

Test Summary: |    Pass  Broken    Total     Time
  Overall     | 3493226       3  3493229  3m04.5s
    SUCCESS
```

_Originally posted by @Keno in https://github.com/JuliaLang/julia/issues/45670#issuecomment-1162593633_

### PR DESCRIPTION
**Pull request by aviatesk**
In a similar spirit to #40561, we can relax the recursion detection to
guarantee `:terminates` effect and allow the effects analysis to not
taint `:terminates` effect when there are no cycles in `MethodInstance`s
in a call graph.

fix #45781

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/45993#issuecomment-1180306748) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4455529_vs_afe3838/report.md).

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -963,8 +988,8 @@ function is_const_prop_profitable_arg(@nospecialize(arg))
     isa(arg, PartialOpaque) && return true
     isa(arg, Const) || return true
     val = arg.val
-    # don't consider mutable values or Strings useful constants
-    return isa(val, Symbol) || isa(val, Type) || (!isa(val, String) && !ismutable(val))
+    # don't consider mutable values useful constants
+    return isa(val, Symbol) || isa(val, Type) || !ismutable(val)
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:992]: This is a significant change, so it should land separately (with nanosoldier run)

File: base/compiler/abstractinterpretation.jl [hunk 2]
```diff
@@ -617,9 +617,13 @@ function abstract_call_method(interp::AbstractInterpreter, method::Method, @nosp
         # this edge is known to terminate
         effects = Effects(effects; terminates=ALWAYS_TRUE)
     elseif edgecycle
-        # Some sort of recursion was detected. Even if we did not limit types,
-        # we cannot guarantee that the call will terminate
-        effects = Effects(effects; terminates=ALWAYS_FALSE)
+        # Some sort of recursion was detected.
+        if edge !== nothing && !edgelimited && !is_edge_recursed(edge, sv)
+            # no `MethodInstance` cycles -- don't taint :terminate
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:622]: This seems like it may only consider whether there was a cycle that will impact the computation of the result type. If we note that the result is discarded, there won't be an `edge` or `edgecycle `here at all (note line 512 above).

IIUC, the correct fix for that may be to poison the effects at line 512 however?

**Review by vtjnash — COMMENTED** [review]
sgtm

File: base/compiler/abstractinterpretation.jl (hunk 1 above)
Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:992]: Because `!ismutable(val::String) === false`, doesn't this change any meaning of the condition but just simplify it?

File: base/compiler/abstractinterpretation.jl (hunk 2 above)
Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:622]: If we discard the result, we propagated the unknown effects `Effects()`, whose `:terminate` effect is also tainted, and it will eventually poison the rest of the call graph.

File: base/compiler/abstractinterpretation.jl (hunk 1 above)
Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:992]: Ah, okay, yep

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:992]: Perhaps at some point when this was written String had been immutable?

Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:992]: A long, long time ago... (`String` has always been mutable since I started to use this language)
