### PR TITLE
Fix string interpolation into Markdown.Table and Markdown.List

### LINKED ISSUE #16194: Markdown strings and interpolation
How to do interpolation in markdown strings? Is the intended way to do it using dollars like in ordinary strings?
If so it seems that interpolation dollars and latex dollars are sometimes confused in markdown strings. For example the following snipped works:

```
x = "3"
md"""This works $(x) 

* a
* b
"""
```

This works 3 
- a
- b

While

```
md"""This works not 

* a $(x)
* b
"""
```

Throws an error:

```
MethodError: `latexinline` has no method matching latexinline(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Symbol)
Closest candidates are:
  latexinline(::IO, !Matched::Base.Markdown.LaTeX)
  latexinline(::IO, !Matched::Base.Markdown.Code)
  latexinline(::IO, !Matched::Array{T,1})
  ...
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix string interpolation into `Markdown.Table` and `Markdown.List` in `md"..."` strings, fixes #16194.

### CODE REVIEW

File: stdlib/Markdown/src/Julia/interp.jl [hunk 1]
```diff
@@ -11,7 +11,7 @@ function interpinner(stream::IO, greedy = false)
     startswith(stream, '$') || return
     (eof(stream) || peek(stream, Char) in whitespace) && return
     try
-        return _parse(stream::IOBuffer, greedy = greedy)
```
Comment (KristofferC) [inline stdlib/Markdown/src/Julia/interp.jl:14]: 😭 

Can we also check the exception type?

File: stdlib/Markdown/src/Julia/interp.jl [hunk 2]
```diff
@@ -11,7 +11,7 @@ function interpinner(stream::IO, greedy = false)
...
+        return _parse(stream, greedy = greedy)
```
Comment (fredrikekre) [inline stdlib/Markdown/src/Julia/interp.jl:14]: This type-assert in `try-catch` threw sometimes since in some cases this function is passed a `GenericIOBuffer` instead of an `IOBuffer`....

File: stdlib/Markdown/src/Julia/interp.jl (hunk 1 above)
Comment (fredrikekre) [reply stdlib/Markdown/src/Julia/interp.jl:14]: I don't quite know what exception type to look for, tests pass even if I comment out the try-catch so perhaps we can just do that?

**Comment by thofma** [comment]
Does this by accident also fix https://github.com/JuliaLang/julia/issues/36946?

**Comment by fredrikekre** [comment]
No.

File: stdlib/Markdown/src/Julia/interp.jl (hunk 2 above)
Comment (fredrikekre) [reply stdlib/Markdown/src/Julia/interp.jl:14]:
````
julia> using Markdown, MethodAnalysis

julia> methodinstances(Markdown.interpinner)
2-element Vector{Core.MethodInstance}:
 MethodInstance for interpinner(::IOBuffer)
 MethodInstance for interpinner(::IOBuffer, ::Bool)

julia> begin
           x = "X"
           contains_X(md) = occursin(x, sprint(show, MIME("text/plain"), md))
           @assert contains_X(md"# $x") # H1
           @assert contains_X(md"## $x") # H2
           @assert contains_X(md"### $x") # H3
           @assert contains_X(md"x = $x") # Paragraph
           @assert contains_X(md"- $x") # List
           @assert contains_X(md"[$x](..)") # Link
           @assert contains_X(md"**$x**") # Bold
           @assert contains_X(md"*$x*") # Italic
           @assert contains_X( # Table
               md"""
               | name |
               |------|
               |  $x  |
               """)
       end

julia> methodinstances(Markdown.interpinner)
4-element Vector{Core.MethodInstance}:
 MethodInstance for interpinner(::IOBuffer)
 MethodInstance for interpinner(::Base.GenericIOBuffer{SubArray{UInt8,1,Vector{UInt8},Tuple{UnitRange{Int64}},true}})
 MethodInstance for interpinner(::IOBuffer, ::Bool)
 MethodInstance for interpinner(::Base.GenericIOBuffer{SubArray{UInt8,1,Vector{UInt8},Tuple{UnitRange{Int64}},true}}, ::Bool)
````

**Review by timholy — APPROVED** [review]
