### PR TITLE
Make Compiler use separate sorting algorithm.

### LINKED ISSUE #47065: Core.Compiler.sort! is broken
```
ERROR: UndefVarError: sizeof not defined
Stacktrace:
  [1] sort!(v::Vector{Int64}, lo::Int64, hi::Int64, a::Core.Compiler.Sort.AdaptiveSort{Core.Compiler.Sort.QuickSortAlg}, o::Core.Compiler.Order.ForwardOrdering, t::Nothing)
    @ Core.Compiler.Sort ./sort.jl:804
  [2] sort!
    @ ./sort.jl:895 [inlined]
  [3] #sort!#8
    @ ./sort.jl:950 [inlined]
  [4] sort!
    @ ./sort.jl:943 [inlined]
  [5] compute_live_ins(cfg::Core.Compiler.CFG, du::Core.Compiler.SSADefUse)
    @ Core.Compiler base/compiler/ssair/passes.jl:46
  [6] sroa_mutables!(ir::Core.Compiler.IRCode, defuses::Core.Compiler.IdDict{Int64, Tuple{Core.Compiler.IdSet{Int64}, Core.Compiler.SSADefUse}}, used_ssas::Vector{Int64}, lazydomtree::Core.Compiler.LazyGenericDomtree{false}, inlining::Core.Compiler.InliningState{Core.Compiler.EdgeTracker, Core.Compiler.WorldView{DAECompiler.DAEGlobalCache}, DAECompiler.DAEInterpreter})
    @ Core.Compiler base/compiler/ssair/passes.jl:1314
  [7] sroa_pass!(ir::Core.Compiler.IRCode, inlining::Core.Compiler.InliningState{Core.Compiler.EdgeTracker, Core.Compiler.WorldView{DAECompiler.DAEGlobalCache}, DAECompiler.DAEInterpreter})
    @ Core.Compiler base/compiler/ssair/passes.jl:1041
  [8] run_passes(ci::Core.CodeInfo, sv::Core.Compiler.OptimizationState, caller::Core.Compiler.InferenceResult, optimize_until::Nothing)
```
This is the first issue, but fixing this shows a bunch more. Here's a start at fixing it, but there's more issues:
```
diff --git a/base/sort.jl b/base/sort.jl
index f6f737ac20..12ce7c79fc 100644
--- a/base/sort.jl
+++ b/base/sort.jl
@@ -12,7 +12,7 @@ using .Base: copymutable, LinearIndices, length, (:), iterate, OneTo,
     extrema, sub_with_overflow, add_with_overflow, oneunit, div, getindex, setindex!,
     length, resize!, fill, Missing, require_one_based_indexing, keytype, UnitRange,
     min, max, reinterpret, signed, unsigned, Signed, Unsigned, typemin, xor, Type, BitSigned, Val,
-    midpoint, @boundscheck, checkbounds
+    midpoint, @boundscheck, checkbounds, sizeof, leading_zeros

 using .Base: >>>, !==, !=

@@ -881,6 +881,8 @@ function sort!(v::AbstractVector{T}, lo::Integer, hi::Integer, a::AdaptiveSort,
         u2 = radix_sort!(u, lo, hi, bits, similar(u))
         uint_unmap!(v, u2, lo, hi, o, u_min)
     end
+
+    return nothing
 end

 ## generic sorting methods ##
@@ -1412,7 +1414,7 @@ uint_map(x::Unsigned, ::ForwardOrdering) = x
 uint_unmap(::Type{T}, u::T, ::ForwardOrdering) where T <: Unsigned = u

 uint_map(x::Signed, ::ForwardOrdering) =
-    unsigned(xor(x, typemin(x)))
+    unsigned(xor(x, typemin(typeof(x))))
 uint_unmap(::Type{T}, u::Unsigned, ::ForwardOrdering) where T <: Signed =
     xor(signed(u), typemin(T))
```

### PR DESCRIPTION
**Pull request by oscardssmith**
Separated from https://github.com/JuliaLang/julia/pull/46679 as the easiest way to fix  https://github.com/JuliaLang/julia/issues/47065. Needs tests.

closes #46586
closes #46587

### CODE REVIEW

File: base/compiler/ssair/passes.jl [hunk 1]
```diff
@@ -1317,7 +1317,7 @@ function sroa_mutables!(ir::IRCode, defuses::IdDict{Int, Tuple{SPCSet, SSADefUse
             else
                 phiblocks = iterated_dominance_frontier(ir.cfg, ldu, get!(lazydomtree))
             end
-            allblocks = sort!(vcat(phiblocks, ldu.def_bbs); alg=QuickSort)
+        allblocks = union!(BitSet(phiblocks), ldu.def_bbs)
```
Comment (vchuravy) [inline base/compiler/ssair/passes.jl:1320]:
```suggestion
            allblocks = union!(BitSet(phiblocks), ldu.def_bbs)
```

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47066#issuecomment-1270696627) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/a696034_vs_950ce91/report.md).

File: test/compiler/datastructures.jl [hunk 2]
```diff
@@ -53,3 +53,15 @@ end
...
+
+# Make sure that the compiler can sort things.
+# https://github.com/JuliaLang/julia/issues/47065
+@testset "Compiler Sorting" begin
+    for len in (0, 1, 10, 100, 10000)
+        v = Core.Compiler.sort!(rand(Int8,len))
+        @test length(v) == len
+        @test issorted(v)
+        Core.Compiler.sort!(v, by=abs)
+        issorted(v, by=abs)
```
Comment (ranocha) [inline test/compiler/datastructures.jl:65]:
```suggestion
        @test issorted(v, by=abs)
```

File: test/compiler/interpreter_exec.jl [hunk 3]
```diff
@@ -106,3 +106,19 @@ let m = Meta.@lower 1 + 1
...
+            $(ex) end)
+    end
+    @eval begin
+        function f_1000()
+            $ex
+            return 0
+         end
+    end
+    @test f_1000()===0
+end
```
Comment (aviatesk) [inline test/compiler/interpreter_exec.jl:124]: I'm confused at this test case. What's being tested here?

Comment (oscardssmith) [reply test/compiler/interpreter_exec.jl:124]: I believe that this is testing compilation of a function with a bunch of basic blocks. Is there a better version of this test?

Comment (aviatesk) [reply test/compiler/interpreter_exec.jl:124]: Is the compilation performance being tested, or is there any correctness issue? And why `f_1000` always returns `0`?

Comment (oscardssmith) [reply test/compiler/interpreter_exec.jl:124]: There was a correctness issue (https://github.com/JuliaLang/julia/issues/47065) where the compiler would try to sort a big list and fail. `f_1000` doesn't technically always return 0, but it returns 1 1 time in 10^1000 which is close enough to 0 that it will never fail.

File: test/compiler/datastructures.jl [hunk 4]
```diff
@@ -53,3 +53,15 @@ end
         end
     end
 end
+
+# Make sure that the compiler can sort things.
+# https://github.com/JuliaLang/julia/issues/47065
+@testset "Compiler Sorting" begin
```
Comment (LilithHafner) [inline test/compiler/datastructures.jl:59]: I think this is redundant with (or at least should be in the same place as) test/compiler/sort.jl

File: test/compiler/interpreter_exec.jl (hunk 3 above)
Comment (aviatesk) [reply test/compiler/interpreter_exec.jl:124]: Okay, I understand. I'd prefer not having `@testset` there though.
