### PR TITLE
fix #8925, `global const (a,b) = (1,2)` should work

### LINKED ISSUE #7314: syntax of `const` with multiple variables
While `global const a=1, b=2` works as expected,

`const a=1, b=2`
`syntax: invalid assignment location "1"`

obviously doesn't.  Instead one has to use `const a, b = 1, 2`.
This looks quite inconsistent to me.

### LINKED ISSUE #8925: global const vs. const tuple assignment inconsistency
`const (c,d) = (3,4)` works but `global const (a,b) = (3,4)` does not.  Seems wrong to me.

Probably related to #7314, but I thought using parens was suppose to work here.

It is desirable to have a syntax for assignment of a tuple to `global const` values, if you want to initialize several constants from a function returning a tuple.

### PR DESCRIPTION
**Pull request by JeffBezanson**
The ultimate goal is to fix #7314, but this is a non-breaking piece of the puzzle. It simply allows tuple assignment syntax `(a, b) = ...` to work with local, global, and const declarations equally.

The next step is to deprecate `const a, b = 1, 2`, requiring it to be written as `const (a,b) = (1,2)`. Then all declaration keywords can use the exact same syntax, where `const a=1, b=2` assigns two variables just like `global a=1, b=2`. `const a, b = 1, 2` would be an error, because `2` is not a variable name, and `const a` is not allowed, since you have to do an assignment.

### CODE REVIEW

File: test/parse.jl [hunk 1]
```diff
@@ -878,3 +878,8 @@ let f = function (x; kw...)
     @test f(1) == (1, Any[])
     @test g(1) == (1, 2)
 end
+
+# issue #8925
+global const (c8925, d8925) = (3, 4)
```
Comment (ararslan) [inline test/parse.jl]: Perhaps not necessary, but you could simultaneously test the `global`ness by wrapping the definition in a `let` block and leaving the `@test`s outside.
