### PR TITLE
Test `return` as expression

### LINKED ISSUE #11169: return is not an expression
Simple (and useless) examples:

```jl
julia> function f()
           identity(return)
       end
ERROR: syntax: misplaced return statement

julia> function f()
           x = return
       end
ERROR: syntax: misplaced return statement
```

So far, entirely pointless usages – just don't do that. But I just came across a situation where it would actually be useful to allow `return` in r-value position:

```jl
julia> function f()
           x = try something_that_might_fail()
           catch err
               warn(err)
               return
           end
           do_something_with(x)
           return
       end
ERROR: syntax: misplaced return statement
```

At first I thought this was a try-catch bug, but it's actually because `return` isn't a valid expression.

### PR DESCRIPTION
**Pull request by eschnett**
Closes #11169.

### CODE REVIEW

**Comment by tkelman** [comment]
needs end-of-file rebase but lgtm

File: test/parse.jl [hunk 1]
```diff
@@ -366,8 +366,14 @@ let a⊂b = reduce(&, x ∈ b for x in a) && length(b)>length(a)
...
+
 # issue #9503
 @test parse("x<:y") == Expr(:(<:), :x, :y)
 @test parse("x>:y") == Expr(:(>:), :x, :y)
 @test parse("x<:y<:z").head === :comparison
 @test parse("x>:y<:z").head === :comparison
+
+# issue #11169
+@test_throws UndefVarError undefvar
+let undefvar = return end
```
Comment (JeffBezanson) [inline test/parse.jl]: This is a bit sketchy --- it's not clear we should even allow `return` without any obvious enclosing function. Also since this is a `let`, it wouldn't lead to `undefvar` being defined globally anyway. Maybe we should test `f(return)` and confirm that `f` wasn't called (via a side effect)?

Comment (eschnett) [inline test/parse.jl]: I think this should succeed:
```Julia
uncalled(x) = @test false
fret() = uncalled(return true; @test false)
@test fret()
```
Alas it doesn't; the `@test false` after the `return true` is executed. This looks like a bug to me.

Comment (JeffBezanson) [inline test/parse.jl]: Yes I think you're right. I believe this is #9535.

**Comment by eschnett** [comment]
@JeffBezanson I simplified the test -- nothing about argument order any more. LGTY?
