### PR TITLE
make union(::Set, itr...), intersect(::Set, itr...), and setdiff(::Set, itr) return a Set (fix #23137)

### LINKED ISSUE #23137: union(::Set, itr...), intersect(::Set, itr...), and setdiff(::Set, itr) should return Set and not Array{Int,1}
This issue refers to
https://discourse.julialang.org/t/union-and-intersect-with-unexpected-return-types/5222
```
julia> union(Set(Int16[1,2,3]), IntSet([1,42]))
4-element Array{Int64,1}:
  2
  3
  1
 42
julia> intersect(Set(Int16[1,2,3]), IntSet([1,42]))
1-element Array{Int64,1}:
 1
julia> setdiff(Set(Int16[1,2,3]), IntSet(2:4))
1-element Array{Int64,1}:
 1
```
The method dispatches to the array-version for the example, but schould use the set-version:
```
julia> @which union(Set([1]), IntSet())
union(vs...) in Base at array.jl:1870
julia> @which union(Set([1]), Set{Int}())
union(s::Set, sets::Set...) in Base at set.jl:55
```
propose to change `set.jl`:
`function union(s::Set, sets...)`
`function intersect(s::Set, sets...)`
`function setdiff(s::Set, xs)`

### PR DESCRIPTION
**Pull request by KlausC**
Fix #23137.

### CODE REVIEW

**Comment by rfourquet** [comment]
LGTM, thanks! I just wonder if performance could be improved if the iterators have O(n) `in`, by using a temporary `Set`? Also, try to give a more descriptive commit message.

File: test/sets.jl [hunk 1]
```diff
@@ -147,6 +147,10 @@ s = union(Set([5,6,7,8]), Set([7,8,9]))
 s = Set([1,3,5,7])
 union!(s,(2,3,4,5))
 @test isequal(s,Set([1,2,3,4,5,7]))
+@test ===(typeof(union(Set([1]), IntSet())), Set{Int})
```
Comment (nalimilan) [inline test/sets.jl]: You can just write `intersect(Set([1]), IntSet()) isa Set{Int}`. Same below.

**Comment by nalimilan** [comment]
@KlausC Thanks for making a PR! It looks good in general, I just have one stylistic comment.

@rfourquet Performance improvements should go to another PR. This is true in general, but even more so for first-time contributors.

**Comment by rfourquet** [comment]
@nalimilan Yes I agree, I was not requesting a change here, just opening a possible follow-up! (also motivated by the fact that the current `setdiff` for arrays converts the second argument to a `Set`, ensuring that the `in` test is fast, so there could be a regression on this front).

File: test/sets.jl (hunk 1 above)
Comment (KlausC) [inline test/sets.jl]: Will do next time. I just copied this style from the beginning of `test/sets.jl`. I think I should I do such stylistic changes to otherwise unrelated lines of code? That would complicate review and merging...

Comment (nalimilan) [inline test/sets.jl]: Don't worry with existing code. You can change it too if you like (in a separate commit), but that's really not a requirement.

**Comment by KlausC** [comment]
two of the travis-jobs failed. I cannot see any relation with the changes I made. How do I proceed?

**Comment by JeffBezanson** [comment]
Those failures seem to be happening regularly; not related.

**Comment by nalimilan** [comment]
Thanks @KlausC!

@rfourquet I just had a look at how to implement your suggestion, and it looks like it will require a bit more work. Ideally we would call `convert(AbstractSet, t)` so that no conversion/copy is done for arguments which are already sets. But currently that fails for `Array`. And calling `Set(t)` will reconstruct a `Set` even when the input is already a `Set` (which really sounds like a bug to me). Probably worth filing an issue if you don't want to work on it right now.
