### PR TITLE
Fix issue with mod(::BigInt, ::Unsigned)

### LINKED ISSUE #24298: Issue with BigInt <: Signed
Changing [`BigInt` to be a subtypes of `Signed`](https://github.com/JuliaLang/julia/pull/23473) can cause issues when promotion is skipped. For example:

Julia 0.6.0
```julia
julia> mod(BigInt(6), UInt128(5))  # Calls `mod(::Real, ::Real)`
1
```

Julia 0.7.0-DEV.2280 (d3afdfd5ff)
```julia
julia> mod(BigInt(6), UInt128(5))  # Calls `mod(::Signed, ::Unsigned)`
ERROR: MethodError: Cannot `convert` an object of type BigInt to an object of type Unsigned
This may have arisen from a call to the constructor Unsigned(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] unsigned(::BigInt) at ./int.jl:148
 [2] mod(::BigInt, ::UInt128) at ./int.jl:210
```

### PR DESCRIPTION
**Pull request by omus**
Fixes #24298

### CODE REVIEW

File: base/int.jl [hunk 1]
```diff
@@ -207,7 +207,7 @@ function mod(x::T, y::T) where T<:Integer
     y == -1 && return T(0)   # avoid potential overflow in fld
     return x - fld(x, y) * y
 end
-mod(x::Signed, y::Unsigned) = rem(y + unsigned(rem(x, y)), y)
+mod(x::BitSigned, y::Unsigned) = rem(y + unsigned(rem(x, y)), y)
```
Comment (stevengj) [inline base/int.jl]: Rather than remove the general `mod(x::Signed, y::Unsigned) ` method, wouldn't it be better to add a specific method for `mod(x::BigInt, y::Unsigned)`?

Comment (omus) [reply base/int.jl]: I'm not sure what would be better. If special casing just `BigInt` is preferred to switching `Signed` to `BitSigned` we probably want to revert some changes in #23473 such as: https://github.com/JuliaLang/julia/pull/23473/files#diff-a59f124e9ddd1942d5324499c0cd3fceR601

Comment (rfourquet) [reply base/int.jl]: IMHO using `BitSigned` is better, as we don't know what is a good implementation for the general case. The only example of a `Signed` type in base which is not `BitSigned` is `BigInt` I think, and this general definition fails for it, which should be a good indication I believe to only define those functions for the specific types we know it works with.

**Review by rfourquet — APPROVED** [review]
