### PR TITLE
Also update phi counts in adce pass

### LINKED ISSUE #47180: `CmdRedirect` constructor throwing `TypeError`
[`BinaryBuilderBase.jl`](https://github.com/JuliaPackaging/BinaryBuilderBase.jl) tests are failing on https://github.com/JuliaLang/julia/commit/532125d51d23f22c3fd117fe8a37c158fe16ac62.  A smaller reproducer cooked up with the help of https://github.com/maleadt/creduce_julia is:
```julia
function a(b; stdout )
    c = setenv(b, b.env)
    if true
        c = pipeline(c, stdout)
    end
    c
end
a(``; stdout)
```
The output is
```
ERROR: LoadError: TypeError: in new, expected Base.AbstractCmd, got a value of type Nothing
Stacktrace:
 [1] CmdRedirect
   @ ./cmd.jl:186 [inlined]
 [2] CmdRedirect
   @ ./cmd.jl:191 [inlined]
 [3] redir_out
   @ ./cmd.jl:355 [inlined]
 [4] #pipeline#761
   @ ./cmd.jl:389 [inlined]
 [5] pipeline
   @ ./cmd.jl:397 [inlined]
 [6] #a#3
   @ /tmp/foo.jl:4 [inlined]
 [7] top-level scope
   @ /tmp/foo.jl:8
in expression starting at /tmp/foo.jl:8
```
I don't see how you can enter https://github.com/JuliaLang/julia/blob/d89b96b3fc7ac13ed29ac1508ba302dc4f758d33/base/cmd.jl#L355 where `src::AbstractCmd` and then the `CmdRedirect` constructor complains `src` isn't `AbstractCmd`.

Last time tests passed was on https://github.com/JuliaLang/julia/commit/7f507e64aa14dbbd7e0c9b51a0ee72e7ea97bb19.

### PR DESCRIPTION
**Pull request by Keno**
The whole point of this pass is to compute and compare the counts of all SSA value uses vs those of only-phi uses to find SSA values that have no real uses. In #47080, I updated the code to properly account for removal of phi edges in the SSA count, but neglected to do the same in the phi-only count, leading to #47180. Fix that.

Fixes #47180

### CODE REVIEW

File: test/compiler/irpasses.jl [hunk 1]
```diff
@@ -1092,3 +1092,13 @@ let src = code_typed1(foo_defined_last_iter, Tuple{Int})
...
+
+# Issue #47180, incorrect phi counts in CmdRedirect
+function a47180(b; stdout )
+    c = setenv(b, b.env)
+    if true
+        c = pipeline(c, stdout)
+    end
+    c
+end
+@test isa(a47180(``; stdout), Base.AbstractCmd)
```
Comment (giordano) [inline test/compiler/irpasses.jl:1104]: For what is worth, by playing a bit more with creduce (more specifically, searching for `"TypeError: in new"` instead of the full message `"TypeError: in new, expected Base.AbstractCmd, got a value of type Nothing"`, to give it more freedom) I've got a marginally simpler reproducer:
```julia
julia> function a(b)
           cmd = setenv(``, b.env)
           if true
               cmd = (cmd, )
           end
           cmd
       end
a (generic function with 1 method)

julia> a(``)
ERROR: TypeError: in new, expected Cmd, got a value of type Nothing
Stacktrace:
 [1] a(b::Cmd)
   @ Main ./REPL[1]:4
 [2] top-level scope
   @ REPL[2]:1
```
```suggestion
# Issue #47180, incorrect phi counts in CmdRedirect
function a47180(b)
    cmd = setenv(``, b.env)
    if true
        cmd = (cmd, )
    end
    cmd
end
@test isa(a47180(``), Tuple{Cmd})
```
