### PR TITLE
Some promotion and error reporting fixes for eigs

### LINKED ISSUE #269: ARPACKException with eigs
On v0.4 I see the following:

```
julia> for i = 1:100
           A = randn(256,256)
           λ,v = eigs(A,nev=1,which=:LM)
           println(λ)
       end
Complex{Float64}[-5.403315222231397 + 16.446255603922936im]
Complex{Float64}[-16.83827451218431 + 0.0im]
Complex{Float64}[-2.395397568451567 + 16.123526196663914im]
Complex{Float64}[-12.39397801177645 + 11.304084721268927im]
Complex{Float64}[-12.27303495097507 + 11.832055786740451im]
Complex{Float64}[-7.908468037577425 + 14.731418350155243im]
Complex{Float64}[-16.470027322364675 + 0.0im]
Complex{Float64}[-16.99591969718958 + 0.0im]
Complex{Float64}[-8.513801628913438 + 14.190942988032592im]
Complex{Float64}[-14.123131553900631 + 9.55200192151935im]
Complex{Float64}[15.2472765341005 + 7.023088970503387im]
ERROR: Base.LinAlg.ARPACKException(-14)
 in eupd_wrapper at ./linalg/arpack.jl:165
```

I discovered this while investigating a bug where my code hangs while calling `eigs` in this way, so I'm hoping this is related.

### LINKED ISSUE #13709: ARPACKException with eigs
On v0.4 I see the following:
```
julia> for i = 1:100
           A = randn(256,256)
           λ,v = eigs(A,nev=1,which=:LM)
           println(λ)
       end
Complex{Float64}[-5.403315222231397 + 16.446255603922936im]
Complex{Float64}[-16.83827451218431 + 0.0im]
Complex{Float64}[-2.395397568451567 + 16.123526196663914im]
Complex{Float64}[-12.39397801177645 + 11.304084721268927im]
Complex{Float64}[-12.27303495097507 + 11.832055786740451im]
Complex{Float64}[-7.908468037577425 + 14.731418350155243im]
Complex{Float64}[-16.470027322364675 + 0.0im]
Complex{Float64}[-16.99591969718958 + 0.0im]
Complex{Float64}[-8.513801628913438 + 14.190942988032592im]
Complex{Float64}[-14.123131553900631 + 9.55200192151935im]
Complex{Float64}[15.2472765341005 + 7.023088970503387im]
ERROR: Base.LinAlg.ARPACKException(-14)
 in eupd_wrapper at ./linalg/arpack.jl:165
```
I discovered this while investigating a bug where my code hangs while calling `eigs` in this way, so I'm hoping this is related.

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes JuliaLang/LinearAlgebra.jl#269 and JuliaLang/LinearAlgebra.jl#274

### CODE REVIEW

File: base/linalg/exceptions.jl [hunk 1]
```diff
@@ -11,7 +11,18 @@ type LAPACKException <: Exception
 end
 
 type ARPACKException <: Exception
-    info::BlasInt
+    info::ByteString
```
Comment (tkelman) [inline base/linalg/exceptions.jl]: this is technically breaking and iffy to backport

Comment (andreasnoack) [inline base/linalg/exceptions.jl]: Yes. That's true. We could backport the promotion commit only, or assume that nobody relies on the internals of `ARPACKException` which is probably a safe assumption. They are thrown very rarely because we capture most of the errors with checks before calling ARPACK.

**Comment by ViralBShah** [comment]
I don't think anyone relies on the internals of ARPACKException. Let's backport it - since it is a significantly better experience.

File: base/linalg/arnoldi.jl [hunk 2]
```diff
@@ -47,9 +47,21 @@ The following keyword arguments are supported:
...
-
-
+eigs(A; kwargs...) = eigs(A, I; kwargs...)
+eigs{T<:BlasFloat}(A::AbstractMatrix{T}, ::UniformScaling; kwargs...) = _eigs(A, I; kwargs...)
+
+eigs{T<:BlasFloat}(A::AbstractMatrix{T}, B::AbstractMatrix{T}; kwargs...) = _eigs(A, B; kwargs...)
+eigs(A::AbstractMatrix{BigFloat}, B::AbstractMatrix...; kwargs...) = throw(MethodError(eigs, Any[A,B,kwargs...]))
+eigs(A::AbstractMatrix{BigFloat}, B::UniformScaling; kwargs...) = throw(MethodError(eigs, Any[A,B,kwargs...]))
+function eigs{T}(A::AbstractMatrix{T}, ::UniformScaling; kwargs...)
+    Tnew = typeof(zero(T)/sqrt(one(T)))
```
Comment (stevengj) [inline base/linalg/arnoldi.jl]: we should just define `float(T)`.  I hate this kind of `typeof` construction.
