### PR TITLE
Broadcast to a host-only network, fixes #14040.

### LINKED ISSUE #14040: UDP socket test failure with egress firewall
The following UDP broadcast test in `test/socket.jl` fails on a firewalled system:

```julia
function create_socket()
    s = UDPSocket()
    bind(s, ip"0.0.0.0", 2000, reuseaddr = true, enable_broadcast = true)
    s
end
a, b, c = [create_socket() for i = 1:3]
@sync begin
    recvs = [@async @test bytestring(recv(s)) == "hello" for s in (a, b)]
    send(c, ip"255.255.255.255", 2000, "hello")
    map(wait, recvs)
end
[close(s) for s in [a, b, c]]
```

The `send` from `0.0.0.0` to `255.255.255.255` triggers an `EPERM` due to an egress firewall. Disabling the firewall works, but the packet does really escape to the local network, which might be unwanted in some situations.

I realize this is a minor detail, but due to the test failing it might be better to protect the test against this situation. I did consider wrapping in a `try` and catching `LoadError`, but due to the inner `errno` not being available that would mean string-matching against `EPERM` which isn't terribly neat. Any ideas?

### PR DESCRIPTION
**Pull request by maleadt**
Restrict the UDP broadcast test to `127.255.255.255` instead of `255.255.255.255`, which should prevent the test packets from escaping the host network and possibly triggering a firewall.

### CODE REVIEW

File: test/socket.jl [hunk 1]
```diff
@@ -239,19 +239,21 @@ begin
...
-        s
-    end
-    a, b, c = [create_socket() for i = 1:3]
-    @sync begin
-        recvs = [@async @test bytestring(recv(s)) == "hello" for s in (a, b)]
-        send(c, ip"255.255.255.255", 2000, "hello")
-        map(wait, recvs)
+# Local-machine broadcast
+# (Mac OS X's loopback interface doesn't support broadcasts)
+if @osx ? false : true
```
Comment (tkelman) [inline test/socket.jl]: were you hitting the firewall problem on osx? if not, could the test stay using the existing ip on osx?

Comment (maleadt) [inline test/socket.jl]: No I wasn't, but echoing @sbromberger comment on #14040 it doesn't seem like a good idea to generate active network traffic as part of a test, which is the case when using `255.255.255.255`. Also, if somebody were to run a somewhat restricted firewall on Mac, this test would fail.

Comment (tkelman) [inline test/socket.jl]: we could move the test to one of the other files that do rely on network access. I'm mostly concerned about the test coverage of ensuring this functionality doesn't regress on osx

Comment (maleadt) [inline test/socket.jl]: Yeah definitely, test coverage is of utmost importance. Will re-enable, conditionally.

**Comment by maleadt** [comment]
Okay, new approach: re-enable the 255.255.255.255 broadcast on Mac OS X, but catch any EPERM and skip the test. Only disadvantage, the `isa(e, Base.UVError) && Base.uverrorname(e) == "EPERM"` might bitrot (almost never triggered).

File: test/socket.jl [hunk 2]
```diff
@@ -239,19 +239,29 @@ begin
...
+        @sync begin
+            send(c, bcastdst, 2000, "hello")
+            recvs = [@async @test bytestring(recv(s)) == "hello" for s in (a, b)]
+            map(wait, recvs)
+        end
+    catch e
+        if isa(e, Base.UVError) && Base.uverrorname(e) == "EPERM"
+            warn("UDP broadcast test skipped (permission denied upon send, restrictive firewall?)")
+        else
+            throw(e)
```
Comment (tkelman) [inline test/socket.jl]: `rethrow` ?

Comment (maleadt) [inline test/socket.jl]: Did not know about `rethrow`. Fixed, and squashed the commits into one.
