### PR TITLE
fix some inference and method lookup issues

### LINKED ISSUE #20096: Printing issue with `Tuple{Vararg{Int}}` first time
This is a reproducible full REPL session

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.2143 (2017-01-17 18:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a6cde76* (0 days old master)
|__/                   |  x86_64-pc-linux-gnu

julia> Tuple{Vararg{Int}}
Any where Core<:Tuple<:svec()

julia> Tuple{Vararg{Int}}
Tuple{Vararg{Int64,N} where N}

julia> Tuple{Vararg{Int}}
Tuple{Vararg{Int64,N} where N}
```

The type is printed oddly the first time. Subsequent printings are correct.

### LINKED ISSUE #20305: Type inference error
`PyCall` test is causing a `SIGILL` due to what seems to be a type inference/type computation error. Reduced case:

```julia
data = Ptr{Float16}(Libc.malloc(1000))
dims = (6, 1)
function copy2(data)
    B = unsafe_wrap(Array, data, dims::Tuple)
    return transpose(B)
end
@code_warntype copy2(data)
copy2(data)
```

The inferred code is
```julia
Variables:
  #self#::#copy2
  data::Ptr{Float16}
  B::Union{Array{Float16,N},Array{Float16,N}}
  #temp#::Core.MethodInstance

Body:
  begin 
      B::Union{Array{Float16,N},Array{Float16,N}} = (Main.unsafe_wrap)(Main.Array,data::Ptr{Float16},(Core.typeassert)(Main.dims,Main.Tuple)::Tuple)::Union{Array{Float16,N},Array{Float16,N}} # line 7:
      return (Main.transpose)(B::Union{Array{Float16,N},Array{Float16,N}})::Union{}
  end::Union{}
```

The inferred type of `B` looks weird and the inferred type of `transpose` is wrong.

Maybe it's related to failing to normalize these types?

```julia
julia> Union{Array{Float16,N},Array{Float16,N}} where N
Union{Array{Float16,N},Array{Float16,N}} where N

julia> Union{Array{Float16,N1},Array{Float16,N2}} where N1 where N2
Union{Array{Float16,N1},Array{Float16,N2}} where N1 where N2
```

@JeffBezanson

### PR DESCRIPTION
**Pull request by JeffBezanson**
1. Given something like `Array{Any[Int][1]}`, we can now infer `Type{Array{_,N} where N} where _` instead of `Type{_} where _<:Array`.

2. Given `Tuple{x::Any}` we didn't take into account the possibility that `x` could be `Vararg` at run time. This is fixed.

3. *All* versions of julia seem to have this bug:

```
julia> f{T}(x::T...) = 0

julia> f(x...) = ""

julia> f()
""

julia> @code_typed f()
LambdaInfo for f()
:(begin 
        return 0
    end::Int64)
```

Another manifestation:

```
julia> g{T}() = 0
WARNING: static parameter T does not occur in signature for g at none:1.
The method will not be callable.
g (generic function with 1 method)

julia> g()
ERROR: MethodError: `g` has no method matching g()

julia> @which g()
g{T}() at none:1
```

We were actually testing for this behavior! Test fixed.

4. In `ml_matches_visitor`, after computing a type intersection, we also computed subtype. I added a flag to intersection to avoid this redundant call, which will hopefully save a little compile time.

5. Deleted some code that's not needed with the new subtyping algorithm.

6. Inference of `ccall` was returning types with free variables. Fixes #20305

7. Improve/fix t-func for `fieldtype`.

Fixes #20096

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Fixes #20096

**Comment by yuyichao** [comment]
I think the auto close only works in commit message or top post of a PR.

**Comment by tkelman** [comment]
Which part fixes the first-time-only misprinting? Testable?

**Comment by JeffBezanson** [comment]
The tests added to test/subtype cover the underlying cause. That symptom is difficult to reproduce reliably since it depends on what gets into the method cache first.

File: base/essentials.jl [hunk 1]
```diff
@@ -83,6 +83,21 @@ function rewrap_unionall(t::ANY, u::ANY)
     return UnionAll(u.var, rewrap_unionall(t, u.body))
 end
 
+function rename_unionall(u::ANY)
```
Comment (Keno) [inline base/essentials.jl]: Comment explaining what this does?

File: base/inference.jl [hunk 2]
```diff
@@ -2081,7 +2081,7 @@ end
 function typeinf_code(method::Method, atypes::ANY, sparams::SimpleVector,
                       optimize::Bool, cached::Bool, params::InferenceParams)
     code = code_for_method(method, atypes, sparams, params.world)
-    code === nothing && return (nothing, nothing, Any)
+    code === nothing && return (nothing, Any)
```
Comment (tkelman) [inline base/inference.jl]: is this part still needed though?

Comment (JeffBezanson) [inline base/inference.jl]: This is just a temporary revert for purposes of testing this branch.

File: base/inference.jl [hunk 3]
```diff
@@ -862,27 +880,45 @@ function apply_type_tfunc(headtypetype::ANY, args::ANY...)
...
             push!(tparams, ai.val)
         else
             # TODO: return `Bottom` for trying to apply a non-UnionAll
-            #if !istuple && i-1 > length(headtype.parameters)
-            #    # too many parameters for type
-            #    return Bottom
-            #end
             uncertain = true
+            # These blocks improve type info but make compilation a bit slower.
+            # XXX
```
Comment (tkelman) [inline base/inference.jl]: You and Jameson use this fairly often in comments. What's this for, any distinction from a usual todo?

Comment (vtjnash) [inline base/inference.jl]: yes. TODO is just a note for a future reader of something interesting that could be done, but isn't. But that nothing is seriously broken. XXX means something is broken or wrong. (usually very wrong, and FIXME would indicate slightly wrong, but that's pretty flexible.) Either form should also have a clarifying comment after it before ending up on master, but it's not uncommon to write one during WIP just to tag places that need revisiting before finishing the commit.

File: base/inference.jl [hunk 4]
```diff
@@ -791,23 +791,36 @@ function getfield_tfunc(s00::ANY, name)
...
+            ft = nothing
+            try
+                ft = fieldtype(s, fld)
+            catch
+            end
+            if ft !== nothing
+                if isleaftype(ft) || ft === Bottom
+                    return Const(ft)
+                else
+                    return Type{ft}
```
Comment (vtjnash) [inline base/inference.jl]: This seems like it might not be quite monotonic, since I think the `getfield_tfunc` is actually pretty smart about inferring `Const` for various cases. For example, the return_type of `HasAbstractlyTypedField` should be `Const(ft)` (although we widen it before letting the user see that, so it's a bit annoying to test for). It should be possible to see the difference by using a UnionAll type for the field, and checking that you can parameterize the result of fieldtype to form a leaftype.

Also, would be nice not to catch errors silently in that try/catch.

Comment (JeffBezanson) [inline base/inference.jl]: I might have to rewrite this not to call `getfield_tfunc` at all. In general we don't want to have to guess the relationship between getfield_tfunc's result and the exact declared type.

Comment (vtjnash) [inline base/inference.jl]: `getfield_tfunc` used to return an exact / inexact bit to allow it to implement both with the same code. should we bring that back?

**Comment by StefanKarpinski** [comment]
I resolved conflicts but @JeffBezanson, you should probably review:

- kept the more alarming comments in `base/inference.jl`
- kept both sets of tests in `test/inference.jl`

**Comment by vtjnash** [comment]
From looking at historical data from travis-ci, it looks like this commit may have added 1-1.5 MB to sysimg. Was that intentional?

**Comment by yuyichao** [comment]
Measured with

```
perf stat -e task-clock -e cycles -e instructions -e branches -e branch-misses -e cache-references -e cache-misses ./julia -e 'for i in 1:300; gc(true); end'
```

This also makes the full GC after startup a tiny bit (`5%`) slower, probably due to the change in the object tree structure.

**Comment by JeffBezanson** [comment]
This gets better type info, so it's not surprising that there is more compiler data around. I don't know if I'd expect 1mb worth, but we'll be able to make it up elsewhere. My pending ir cleanup pr helps.
