### PR TITLE
use a non-stack-based algorithm to compute summarysize

### LINKED ISSUE #19707: StackOverflowError in summarysize during misc test
I see new failures when building Fedora/RHEL RPM nightlies. These have bee, introduced since d47f24b638e8b0dfc1ec73d1406d7a66ae4b4a50 (from Dec. 22).

```julia
Error in testset misc:
Error During Test
  Test threw an exception of type StackOverflowError
  Expression: $(Expr(:escape, :(summarysize(Core)))) $(Expr(:escape, :>)) $(Expr(:escape, :(summarysize(Core.Inference)))) $(Expr(:escape, :>)) $(Expr(:escape, :(Core.sizeof(Core))))
  StackOverflowError:
Error in testset misc:
Error During Test
  Test threw an exception of type StackOverflowError
  Expression: summarysize(Base) > 10000 * sizeof(Int)
  StackOverflowError:
Error in testset ambiguous:
Error During Test
  Expression evaluated to non-Boolean
  Expression: ((x->begin 
        isempty(x) || println(x)
    end))(detect_ambiguities(Core,Base; imported=true))
       Value: nothing
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-25-x86_64/00492486-julia/build.log.gz

### PR DESCRIPTION
**Pull request by vtjnash**
nothing too fancy here, just swapping the existing stack-based DFS algorithm for a heap-based one. this'll prevent this method from ever causing stack overflow, which will fix #19707.

### CODE REVIEW

File: base/summarysize.jl [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+    chargeall::Any
+end
+
+
+"""
+    Base.summarysize(obj; exclude=Union{...}, chargeall=Union{...}) -> Int
+
+Compute the amount of memory used by all unique objects reachable from the argument.
+Keyword argument `exclude` specifies the types of objects to exclude from the traversal.
+Keyword argument `chargeall` specifies the types of objects to always charge the size of all of their fields, even if those fields would normally be excluded.
```
Comment (ararslan) [inline base/summarysize.jl]: Might be nice to provide keyword arguments as a bulleted list. Makes it a little easier to read. It would also be good to add line breaks to maintain the line length guidelines.

File: base/summarysize.jl [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+"""
+function summarysize(obj::ANY; exclude::ANY = Union{DataType, TypeName}, chargeall::ANY = Union{TypeMapEntry, Method, Core.MethodInstance})
```
Comment (ararslan) [inline base/summarysize.jl]: Same comment regarding line lengths. You could just align `exclude` and `chargeall` beneath `obj`; that style is used elsewhere.

**Comment by ararslan** [comment]
Is there a way to test that #19707 is fixed so that we can track it going forward?

File: base/summarysize.jl [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+@noinline function _summarysize(ss::SummarySize, obj::ANY)
+    key = pointer_from_objref(obj)
+    haskey(ss.seen, key) ? (return 0) : (ss.seen[key] = true)
+    if nfields(obj) > 0
+        push!(ss.frontier_x, obj)
+        push!(ss.frontier_i, 1)
+    end
+    if isa(obj, UnionAll)
+        # black-list of items that don't have a Core.sizeof
+        return 2 * sizeof(Int)
```
Comment (tkelman) [inline base/summarysize.jl]: the old computation for UnionAll also added `summarysize(obj.body, seen, excl) + summarysize(obj.var, seen, excl)`, is this new version undercounting?

Comment (vtjnash) [inline base/summarysize.jl]: the fields are handle elsewhere now. (unrelated, but the old version was also over-counting the `Core.sizeof`)

File: base/summarysize.jl (hunk 1 above)
Comment (nalimilan) [inline base/summarysize.jl]: Cf. reference example [in the manual](http://docs.julialang.org/en/latest/manual/documentation.html) (bullet 4).

File: base/summarysize.jl [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+                val = x[i]
+            end
+        else
+            nf = nfields(x)
+            ft = typeof(x).types
+            if !isbits(ft[i]) && isdefined(x, i)
+                val = getfield(x, i)
+            end
+        end
+        if nfields(x) > i
```
Comment (JeffBezanson) [inline base/summarysize.jl]: Should this be `nf > i`?
