### PR TITLE
fix pkgdir on the package and dependencies when it is precompiling

### LINKED ISSUE #37620: pathof(Module) not working inside Module
There is a popular method to query for the location of `Module` inside `Module` itself (see https://juliahub.com/ui/CodeSearch?q=pathof&u=all&t=all) by calling `dirname(pathof(Module))`. This was working until yesterday, but now it is broken:

```julia
module Bla 

const blabla = dirname(pathof(Bla))

end # module
```
This yields:
```julia
julia> using Bla
[ Info: Precompiling Bla [67033f7b-c123-4da7-a97e-40e01a5d0b32]
ERROR: LoadError: MethodError: no method matching dirname(::Nothing)
Closest candidates are:
  dirname(::AbstractString) at path.jl:161
Stacktrace:
 [1] top-level scope
   @ ~/Bla/src/Bla.jl:3
 [2] include
   @ ./Base.jl:379 [inlined]
 [3] include_package_for_output(input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, uuid_tuple::Tuple{UInt64, UInt64}, source::Nothing)
   @ Base ./loading.jl:1135
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:345 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at /home/blabla/Bla/src/Bla.jl:1
ERROR: Failed to precompile Bla [67033f7b-c123-4da7-a97e-40e01a5d0b32] to /home/blabla/.julia/compiled/v1.6/Bla/70hQi_AUMiz.ji.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1266
 [3] _require(pkg::Base.PkgId, cache::Base.TOMLCache)
   @ Base ./loading.jl:946
 [4] require(uuidkey::Base.PkgId, cache::Base.TOMLCache)
   @ Base ./loading.jl:839
 [5] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:826
```
I have not bisected it, but I guess it is related to https://github.com/JuliaLang/julia/pull/37586, since the error started a few hours ago (@KristofferC).

I am afraid this will give lots of errors when running PkgEval for the upcoming 1.6 release.

Edit:
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.945
Commit 01ebd93771 (2020-09-17 07:05 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/37620

I think this is a decent way of doing it.

### CODE REVIEW

File: base/loading.jl [hunk 1]
```diff
@@ -1140,10 +1141,10 @@ function include_package_for_output(input::String, depot_path::Vector{String}, d
     end
 end
 
-@assert precompile(include_package_for_output, (String,Vector{String},Vector{String},Vector{String},typeof(_concrete_dependencies),NTuple{2,UInt64},Nothing))
-@assert precompile(include_package_for_output, (String,Vector{String},Vector{String},Vector{String},typeof(_concrete_dependencies),NTuple{2,UInt64},String))
+@assert precompile(include_package_for_output, (PkgId,String,Vector{String},Vector{String},Vector{String},typeof(_concrete_dependencies),NTuple{2,UInt64},Nothing))
+@assert precompile(include_package_for_output, (PkgId,String,Vector{String},Vector{String},Vector{String},typeof(_concrete_dependencies),NTuple{2,UInt64},String))
 
-function create_expr_cache(input::String, output::String, concrete_deps::typeof(_concrete_dependencies), uuid::Union{Nothing,UUID})
+function create_expr_cache(pkg::PkgId, input::String, output::String, concrete_deps::typeof(_concrete_dependencies), uuid::Union{Nothing,UUID})
```
Comment (vtjnash) [inline base/loading.jl:1147]:
```suggestion
function create_expr_cache(pkg::PkgId, input::String, output::String, concrete_deps::typeof(_concrete_dependencies))
    uuid = pkg.uuid
```

Comment (KristofferC) [reply base/loading.jl:1147]: Ah, nice.
