### PR TITLE
narrow array conversions

### LINKED ISSUE #26178: Converting a vector to `Diagonal` shouldn't work
This new behaviour seems wrong:
```julia
julia> convert(Diagonal, rand(5))
5×5 Diagonal{Float64,Array{Float64,1}}:
 0.731736   ⋅         ⋅         ⋅         ⋅      
  ⋅        0.501643   ⋅         ⋅         ⋅      
  ⋅         ⋅        0.520562   ⋅         ⋅      
  ⋅         ⋅         ⋅        0.390789   ⋅      
  ⋅         ⋅         ⋅         ⋅        0.237735
```

I think the old behaviour of only supporting `Diagonal(rand(5))` was correct.

### LINKED ISSUE #26294: Unexpected transposition when combining convert() and copy() for adjoints
I just noticed this while trying to fix WoodburyMatrices.jl for v0.7. Here's a reduced example of the behavior:

```julia
julia> struct Woodbury{Vt} <: AbstractMatrix{Float64}
         V::Vt
       end

julia> Woodbury(V::AbstractMatrix) = Woodbury{typeof(V)}(copy(V))
```

Previously, this worked fine. However, something interesting happens if `V` happens to be an Adjoint:

```julia
julia> V = zeros(3, 2)
3×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

julia> Vprime = V'
2×3 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> Woodbury(Vprime).V
3×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
```

Note that even though we constructed `Woodbury` with the `2x3` Vprime, we got a `3x2` matrix in the `V` field. What's happening is:

1. We call `Woodbury(Vprime::Adjoint)`
2. `typeof(Vprime)` is `Adjoint`
3. `copy(Vprime)` returns a plain `Matrix`
4. we call `Woodbury{Adjoint{...}}(vprime_copy::Matrix)`
5. that implicitly calls `convert(Adjoint, vprime_copy::Matrix)`...
6. ...which in turn transposes `vprime_copy`, yielding a matrix which is transposed from the original `Vprime`

In essence, this is a case where `convert(typeof(V), copy(V))` returns the *adjoint* of V, not something of the same shape as V. 

This is all perfectly correct given the currently defined behaviors, but it seems like an edge case that might be worth fixing. For example, if `copy(Vprime)` returned another `Adjoint`, then I believe this particular problem would go away (but I imagine it's not as easy as that). 

Of course, the answer may just be "don't do that". It's easy to fix this particular case now that I understand what's going on, but it may be a trap that others fall into.

### PR DESCRIPTION
**Pull request by JeffBezanson**
Not all array types can convert from any AbstractArray via a 1-argument constructor call. Structured array types like `Diagonal` have different constructor behaviors, and some types like `ReshapedArray` don't have any such constructors.

fixes #26294, fixes #26178

### CODE REVIEW

**Comment by mbauman** [comment]
Wow, that was easier than I expected.  I assume that this then hits the convert deprecation for `::Any` for all custom arrays you've not explicitly allowed here?

File: base/array.jl [hunk 1]
```diff
@@ -413,8 +413,11 @@ oneunit(x::AbstractMatrix{T}) where {T} = _one(oneunit(T), x)
 
 ## Conversions ##
 
-# arises in similar(dest, Pair{Union{},Union{}}) where dest::Dict:
-convert(::Type{Vector{Union{}}}, a::Vector{Union{}}) = a
+convert(::Type{T}, a::T) where {T<:Array} = a
+convert(::Type{T}, a::AbstractArray) where {T<:Array} = T(a)
+
+convert(::Type{AbstractArray{T}}, a::AbstractArray) where {T} = AbstractArray{T}(a)
```
Comment (mbauman) [inline base/array.jl]: Did you try removing this one, too?

Comment (mbauman) [reply base/array.jl]: Ah, nevermind.  I was getting confused by `Type{<:AbstractArray}` and `Type{AbstractArray}`.  This looks great.  For anyone else getting into the same confusion, this dispatches to the `AbstractArray{T}(…)` constructor, which definitely exists and just `copyto!`s into a `similar` array.

**Comment by JeffBezanson** [comment]
From this I've discovered that it's possible to `convert` between sparse matrices and vectors (in the case of matrices, it checks that there's only one column). Other array types don't support that. Do we want to keep it?

**Comment by JeffBezanson** [comment]
Holy cow, this seems to have a huge effect on sysimg build time and size --- basecompiler.ji goes from ~19MB to ~80MB.

**Comment by JeffBezanson** [comment]
Ok, I thought this caused it but now I've seen the same behavior on master. Appears to be non-deterministic?

**Comment by StefanKarpinski** [comment]
Non-deterministic compiled code size has been reported a few times before.

**Comment by mbauman** [comment]
(#25900)

**Comment by mbauman** [comment]
I'm tentatively in support of having `convert` support moving between arrays of supported dimensionalities.  See #23821.

**Comment by JeffBezanson** [comment]
OK, I agree that might be fine. I'll keep these methods for now then.

**Comment by nalimilan** [comment]
Probably worth marking #23821 for triage? It doesn't make much sense to keep these `convert` methods if we do not add more generic ones.

**Comment by JeffBezanson** [comment]
I'm finding the structured matrix constructors a bit hard to navigate. It's not clear when they (should?) check to see if their argument is representable. For example

```
julia> s = Symmetric(rand(3,3));
# allowed; virtually copies upper triangle to lower

julia> SymTridiagonal(s)
# allowed; ignores off-band elements

julia> tr = Tridiagonal(rand(3,3))
# allowed; ignores off-band elements

julia> SymTridiagonal(tr)
ERROR: ArgumentError: matrix cannot be represented as SymTridiagonal
```

This might be partly my fault from the constructor-to-convert fallback removal. But I'm guessing the intent is to have all such operations accessible as `T(x)`, with the safe subset of those also callable via `convert`? That still doesn't seem totally optimal though. For example maybe the constructors should try harder to avoid throwing errors. Or maybe there's a pattern I'm missing of which operations are allowable?

**Comment by JeffBezanson** [comment]
#23821 should be non-breaking.

**Comment by nalimilan** [comment]
> #23821 should be non-breaking.

Yes, it's non-breaking, but if we eventually decide not to do it, we won't be able to remove `convert` methods between sparse matrices and vectors, which will be an unjustified exception. So I'd rather remove these methods now.
