### PR TITLE
Do not swallow UndefVarError in alloc_elim_pass!

### LINKED ISSUE #18385: A statement like `sometuple[index]` executed without error in a code branch when `sometuple` should **not** have a value at all
Very strange behaviour -- looks like having executed code that should **not** have been executed at all:

```
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> function f()
           if g
               x = (0, 42)
           else
               y = (1, 43)
           end
           println(g)
           println(x[2])
           println(y[1])
       end
f (generic function with 1 method)

julia> g = true
true

julia> f()
true
42
1

julia> g = false
false

julia> f()
false
42
1
```

What is interesting, the code starts to crash (**as expected**, with `UndefVarError`) when we either *use arrays instead of tuples* or try *referring to the variables themselves* without using the getindex syntax:

```
julia> function f2()
           if g
               x = (0, 42)
           else
               y = (1, 43)
           end
           println(g)
           println(x)
           println(y)
       end
f2 (generic function with 1 method)

julia> f2()
false
ERROR: UndefVarError: x not defined
 in f2() at ./REPL[5]:8

julia> g = true
true

julia> f2()
true
(0,42)
ERROR: UndefVarError: y not defined
 in f2() at ./REPL[5]:9

julia> function f3()
           if g
               x = [0, 42]
           else
               y = [1, 43]
           end
           println(g)
           println(x[2])
           println(y[1])
       end
f3 (generic function with 1 method)

julia> f3()
true
42
ERROR: UndefVarError: y not defined
 in f3() at ./REPL[9]:9

julia> g = false
false

julia> f3()
false
ERROR: UndefVarError: x not defined
 in f3() at ./REPL[9]:8
```

Checked with julia v0.5.0-rc3 and rc2.

(The problem was reported by the user huckl3b3rry87 at the julia IRC chat -- see: https://gitter.im/JuliaLang/julia?at=57cf5209f5a156f56489b57a).

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #18385

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -4519,6 +4519,35 @@ ptr18236_2 = cfunction(identity, VecElement{NTuple{2,Int8}},
...
+    if g
+        a = (1, 2)
+    end
+    return a[1]
+end
+@test f18385(true) === 1
+# variable name in the error is tested above in `TestSSA16244`
+@test_throws UndefVarError f18385(false)
+
+# Another similar issue, make sure newvar nodes are create for the fields
```
Comment (tkelman) [inline test/core.jl]: are created
