### PR TITLE
stop using `rand(lo:hi)` for QuickerSort pivot selection

### LINKED ISSUE #48230: Default sort algorithm affects global RNG
In #45222, the default sort algorithm was changed to an algorithm which uses randomness (at least, when `Random` is loaded), and therefore can modify the global RNG state.

This can lead to surprising bugs in cases where `sort!` is used with the expectation that it will not modify the global RNG state. For example: https://github.com/FluxML/Zygote.jl/issues/1351, where Zygote's metaprogramming (`IRTools`) calls `sort` when running the program for the first time. This means that a primal program gives a different output when a function is differentiated for the first time, as compared to subsequent runs, even when the global RNG is initialized to the same thing in both cases. This is incorrect behaviour because Zygote should not affect the primal's random draws.

Arguably, this is a bug in `IRTools`: `IRTools` should either switch to a `sort!` algorithm that has a semantic guarantee of determinism, or somehow perform the default `sort` but with a different RNG that doesn't affect the global one (note that the latter is difficult to do because Julia does not have native splittable RNGs, and extra global RNGs hidden in packages sounds like a bad idea, because a computation's result would ideally be deterministic given a) the global RNG's initial state, and b) any user-provided RNGs). 

Also, to clarify, for a sorting algorithm that needs randomness to make calls to `rand` certainly seems like the right thing to do, so the discussion in https://github.com/JuliaLang/julia/pull/45222#discussion_r896901381 makes sense to me. (Although, perhaps there should be a facility for user-provided RNGs.). 

However, in practice, the question is whether breaking the implicit assumption that the _default_ `sort` is deterministic could lead to bugs. For example, the `REPL` calls `sort!` (logging mine, this is on `1.9.0-beta2`):
image

If `sort!` does not have a semantic guarantee of not affecting the global RNG, would it be correct to say that `Random.seed!(123); rand();` could have different outputs in the REPL v.s.  a script? 

This does not actually happen in the above example,, because the polyalg uses `InsertionSort` for small inputs, which does not make any calls to `rand`. (This is why the `Zygote` bug linked above was a bit difficult to discover; presumably the AST had to be big enough). However, relying on this fact seems dangerous: the question is really about getting the semantic guarantees right, and whether modifying any existing (implicit) guarantees on a function such as `sort!` that is used in internals could have unforeseen effects.

Please let me know if I'm missing anything big in the story here, it's very possible:) But since this change is slated for Julia 1.9, I thought it would be good to raise this concern asap in case there's something to it.

Edit: see discussion in https://github.com/JuliaLang/julia/pull/45222#discussion_r896901381 which is highly relevant

### PR DESCRIPTION
**Pull request by LilithHafner**
see discussion here: https://github.com/JuliaLang/julia/pull/45222#discussion_r896901381
fixes https://github.com/JuliaLang/julia/issues/48230
takes sorting out of the discussion in #48069
This is a regression in how easy it is to construct a pathological input with respect to master and julia-1.9.0-beta2, but not w.r.t. 1.8.5.

Also fix a comment that I noticed had gone stale.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

File: base/sort.jl [hunk 1]
```diff
@@ -983,21 +983,15 @@ QuickerSort(lo::Union{Integer, Missing}, hi::Union{Integer, Missing}) = QuickerS
...
 # to the pivot, and store the result in t[lo:hi].
 #
-# returns (pivot, pivot_index) where pivot_index is the location the pivot
-# should end up, but does not set t[pivot_index] = pivot
+# sets `pivot_dest[pivot_index+pivot_index_offset] = pivot` and returns that index.
 function partition!(t::AbstractVector, lo::Integer, hi::Integer, offset::Integer, o::Ordering,
         v::AbstractVector, rev::Bool, pivot_dest::AbstractVector, pivot_index_offset::Integer)
-    pivot_index = select_pivot(lo, hi)
+    # Ideally we would use `pivot_index = rand(lo:hi)`, but a dependency on Random.jl
+    # complicates things and some folks object to mutating the global RNG in sorting.
```
Comment (fredrikekre) [inline base/sort.jl:993]:
```suggestion
    # Ideally we would use `pivot_index = rand(lo:hi)`, but that requires Random.jl
    # and would mutate the global RNG in sorting.
```

Comment (LilithHafner) [reply base/sort.jl:993]: Nice wording. Thanks!
