### PR TITLE
Bugfix: Use Base.aligned_sizeof instead of sizeof in Mmap.mmap

### LINKED ISSUE #58982: Silently wrong Mmap of primitive types
Mmapping for custom primitives with non-standard byte numbers does not error but silently gives wrong results.
(Tested for e.g. 3, 5, 9, 12 byte primitives)

When mmapping directly, the pointer stride  is rounded up to the next multiple of 8, even though the real element size is smaller.

```julia
julia> using Mmap

julia> primitive type MyPrim9 9*8 end

julia> write("datafile", UInt8.(0:63))
64

julia> reinterpret(MyPrim9, mmap("datafile", Vector{UInt8}, (63,)))
7-element reinterpret(MyPrim9, ::Vector{UInt8}):
 MyPrim9(0x080706050403020100)
 MyPrim9(0x11100f0e0d0c0b0a09)
 MyPrim9(0x1a1918171615141312)
 MyPrim9(0x232221201f1e1d1c1b)
 MyPrim9(0x2c2b2a292827262524)
 MyPrim9(0x3534333231302f2e2d)
 MyPrim9(0x3e3d3c3b3a39383736)

julia> mmap("datafile", Vector{MyPrim9}, (7,))
7-element Vector{MyPrim9}:
 MyPrim9(0x080706050403020100)
 MyPrim9(0x181716151413121110)
 MyPrim9(0x282726252423222120)
 MyPrim9(0x383736353433323130)
 MyPrim9(0x000000000000000000)
 MyPrim9(0x000000000000000000)
 MyPrim9(0x000000000000000000)
```

this is on julia `v1.11.5`

### PR DESCRIPTION
**Pull request by JonasIsensee**
The purpose of this PR is to fix #58982 .

The current (bugged) behaviour is:
```
julia> primitive type MyPrim9 9*8 end

julia> sizeof(MyPrim9)
9

julia> Base.aligned_sizeof(MyPrim9)
16


julia> arr = Vector{MyPrim9}(undef, 2)
2-element Vector{MyPrim9}:
 MyPrim9(0x700000000000000002)
 MyPrim9(0xd000007fb7705a2c30)

julia> write("file", arr)
32

julia> using Mmap

julia> mmap("file", Vector{MyPrim9})
3-element Vector{MyPrim9}:
 MyPrim9(0x700000000000000002)
 MyPrim9(0xd000007fb7705a2c30)
 MyPrim9(0x000000000000000000)
```

This is because `Mmap` erroneously uses `sizeof` instead of `Base.aligned_sizeof` to compute the number of elements (` 32 ÷ 9 == 3 `).
This has gone undetected for a long time because `sizeof(T) == Base.aligned_sizeof(T)` is true for most types including structs. (Padding is to a multiple of 8 bytes is  included in `sizeof(T)`) 

closes #58982

edit:
Previously, `sizeof` would throw an error exception when presented with a non-mappable type such as `Ref`.
This occurred within the default argument generation. `Base.aligned_sizeof` does not error here, and this is instead caught in the dedicated `isbits` check.
This seems desirable and I changed the test to require an `ArgumentError`.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Very nice, thank you for finding and fixing this.

File: stdlib/Mmap/test/runtests.jl [hunk 1]
```diff
@@ -343,6 +343,18 @@ end
 GC.gc()
 rm(file)
 
+# test for #58982
```
Comment (Seelengrab) [inline stdlib/Mmap/test/runtests.jl]: Should this be put into a `@testset` to make failures here more localized?

Comment (JonasIsensee) [reply stdlib/Mmap/test/runtests.jl]: We can wrap it into a testset.
I just tried to match the (oldish) style of the test file as closely as possible.

**Comment by KristofferC** [comment]
I think this broke Windows CI (#59053)

**Comment by JonasIsensee** [comment]
> I think this broke Windows CI (#59053)

The only difference from the other tests is that it is wrapped into an `@testset`.
Are these known to cause trouble with file removal on windows?

**Comment by KristofferC** [comment]
CI at least passed on the Windows worker that ran (https://buildkite.com/julialang/julia-master/builds/49176#01980ab7-c042-4ddb-a06e-6020753851d3) before the testset was introduced.

**Comment by JonasIsensee** [comment]
If this persists, then we should remove the `@testset` and place the new test at toplevel, like all the others in the file.

The CI  logs seem to suggest this(?). The `@testset` was only added in the very last commit of this PR.

Is file removal on windows ci known to be buggy?

**Comment by Seelengrab** [comment]
I think it's already been removed https://github.com/JuliaLang/julia/pull/59062, but the root cause is probably indeed something else: https://github.com/JuliaLang/julia/issues/58736

**Comment by DilumAluthge** [comment]
~~Just taking some notes for myself:~~

~~It looks like the flakyness of this test (on Windows) was fixed by Ian in https://github.com/JuliaLang/julia/pull/57686/commits/7c81745ff78511135db5e980b5522560c708818e (which is part of #57686).~~

**Comment by DilumAluthge** [comment]
> ~~Just taking some notes for myself:~~
> 
> ~~It looks like the flakyness of this test (on Windows) was fixed by Ian in [7c81745](https://github.com/JuliaLang/julia/commit/7c81745ff78511135db5e980b5522560c708818e) (which is part of #57686).~~

On further reflection, I don't think 7c81745 was sufficient. I think the flakyness was actually fixed by #59062.
