### PR TITLE
check lengths in covector-vector products

### LINKED ISSUE #746: Dimension checking for vector' * vector is broken
As noted by @marius311 [here](https://github.com/JuliaLang/julia/pull/35257#issuecomment-657901503), the merged PR JuliaLang/julia#35257 seems to cause the following unintended behavior
```
julia> [1,2]' * [1,2,3.]
5.0
julia> [1,2]' * [1,2,3]
ERROR: DimensionMismatch("first array has length 2 which does not match the length of the second, 3.")
```

Both should error, but if the eltype is different between the two vectors, it does not. The culprit seems to be https://github.com/JuliaLang/julia/blob/eb4784a8fb7f572b12d9e4c966975bc8d4c8157f/stdlib/LinearAlgebra/src/adjtrans.jl#L247 where `zip` is used as a fallback

### PR DESCRIPTION
**Pull request by MasonProtter**
closes https://github.com/JuliaLang/LinearAlgebra.jl/issues/746

### CODE REVIEW

**Comment by MasonProtter** [comment]
Paraphrased from a Slack discussion @pablosanjose on this, in case anyone wants to chime in while we're fixing things with indexing:

Currently we have
```julia
julia> o = OffsetArray(collect(1:10), 11:20); v = collect(1:10); o' * v
385
```
but
```julia
julia> o = OffsetArray(rand(3,3), 2:4, 1:3); v = rand(3); o * v
ERROR: ArgumentError: offset arrays are not supported but got an array with index other than 1
```
Should we be checking to see if the two objects have different index styles as well as whether they have different lengths?

I say

> I'm not really sure if that's desirable or not. I'd be tempted to say yes, the out of the box behaviour is the most sensible one and if OffsetArrays wants to disallow it, they can do so within the package

> I suspect Base does that for mat-vec products because it makes the implementation simpler, not because it'd be nonsense to do so. In this case, handling an offset array doesn't really add any extra complication imo.

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 1]
```diff
@@ -267,10 +267,24 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
 
 ## multiplication *
 
+function dot_nonrecursive(u::AbstractVector, v::AbstractVector)
```
Comment (tkf) [inline stdlib/LinearAlgebra/src/adjtrans.jl:270]: I think you need to `permutedims` on the call site or just accept any `AbstractVecOrMat` here?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:270]: Why?

Comment (tkf) [reply stdlib/LinearAlgebra/src/adjtrans.jl:270]: These `u`s and `v`s are not vectors

https://github.com/JuliaLang/julia/blob/8639f6ba5f0c065b662c44e103ee27036fab1ca6/stdlib/LinearAlgebra/src/adjtrans.jl#L298-L301

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:270]: I was thinking whether we should make this function "more internal" by prepending a `_` and leave the arguments unrestricted.

Comment (tkf) [reply stdlib/LinearAlgebra/src/adjtrans.jl:270]: Sounds good to me.

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 2]
```diff
@@ -267,10 +267,24 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
...
+    lu = length(u)
+    if length(u) != length(v)
+        throw(DimensionMismatch("first array has length $(lu) which does not match the length of the second, $(length(v))."))
+    end
+    if lu == 0
+        zero(eltype(u)) * zero(eltype(v))
+    else
+        sum(uu*vv for (uu, vv) in zip(u, v))
+    end
```
[the remark this answers is not in the document]
Comment (MasonProtter) [reply stdlib/LinearAlgebra/src/adjtrans.jl]: Good catch.

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 1 above)
Comment (MasonProtter) [reply stdlib/LinearAlgebra/src/adjtrans.jl]: Yep, makes sense.

**Comment by dkarrasch** [comment]
@MasonProtter You'll need to rename the nonrecursive functions also at their call sites. 😜

**Comment by marius311** [comment]
Thanks for looking at this so quickly! One super minor thing, but you might consider using something other than `nonrecursive` in that function name, b/c while I know what you mean in terms of the function not recursing into `dot` immedaitely, the mathematical operation is still "recursive", i.e. `[[1.,2]]' * [[3,4]]` still gives `11`. Seeing the word "non-recursive" there (and in the title of the original PR fwiw) really threw me off intially on if something fundamental about how Julia handles dot products had changed (which it hasnt). 

I also wonder whether you might throw in to this PR my other suggestion about using instead:
```julia
*(u::AdjointAbsVec{<:Number}, v::AbstractVector{<:Number})
```

**Comment by dkarrasch** [comment]
> the mathematical operation is still "recursive", i.e. `[[1.,2]]' * [[3,4]]` still gives `11`

It isn't:
```julia
julia> v = [rand(2,2) for _ in 1:2]
2-element Array{Array{Float64,2},1}:
 [0.4274917728716121 0.8685061037888708; 0.8947672491011569 0.4527571728561508]
 [0.20207963479107605 0.8146694999967596; 0.07323308037672915 0.5415494652667667]

julia> v'*v
2×2 Array{Float64,2}:
 1.02956   0.980679
 0.980679  1.91625

julia> dot(v,v)
2.9458110362426355
```
And that is a fundamental change, because we do change from recursive reduction to a non-recursive one, since the recursive one was agreed to be inconsistent behavior. We have `dot` for the recursive reduction.

**Comment by marius311** [comment]
Right, good point, thanks. I took a stab at writing a News.md item that would have helped me understand all of this more quickly at the beginning (I have not been following any of this discussion). Feel free to use it if its right:

* `x'*y` where `x` and `y` are `AbstractVector`s is now semantically equivalent to `sum(vx'*vy for (vx,vy) in zip(x,y))`. `dot(x,y)` remains semantically equivalent to `sum(dot(vx,vy) for (vx,vy) in zip(x,y))` (previously, both cases `dot` to recurse, so only the behavior of `x'*y` is changed to be more consistent).

Note the "is semantically equivalent" is taken straight out of the docstring for `dot`. It might not hurt to mention this there too.

**Comment by MasonProtter** [comment]
> @MasonProtter You'll need to rename the nonrecursive functions also at their call sites. :stuck_out_tongue_winking_eye:

:facepalm: I should stop trying to quickly commit things right before bed, sorry about that. 


> Right, good point, thanks. I took a stab at writing a News.md item that would have helped me understand all of this more quickly at the beginning (I have not been following any of this discussion).

Honestly, I think this is more of a bug-fix than a change in intended semantics. Note that this makes `u' * v` behave like `transpose(conj(u)) * v`. From that perspective, I'm not sure it really needs a news item, but I don't know.

**Comment by marius311** [comment]
The main motivation for me for a News item is that as it stands, anyone that has defined a custom vector type and implemented a custom `dot(x::MyVector, y::MyVector)` with the expectation that for scalar eltype's this would also make `x' * y` work, will now need to explicitly implement `x' * y`, since the default `x' * y` even for scalar eltypes no longer always uses `dot`. I just wanted to highlight this for others so they don't have to dig through the code these PRs like I did to understand why.

An alternative to a news item might be just to make scalar eltype's always use `dot`, which you could do I think with the thing I was suggesting, `*(u::AdjointAbsVec{<:Number}, v::AbstractVector{<:Number})`.

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (MasonProtter) [reply stdlib/LinearAlgebra/src/adjtrans.jl]: Okay, so this is actually problematic becuase it makes `u' * v` not work for any `u` or `v` for which `zero(eltype(_))` isn't defined (i.e. things like arrays of arrays.

[the remark this answers is not in the document]
Comment (MasonProtter) [reply stdlib/LinearAlgebra/src/adjtrans.jl]: I'm going to undo the suggested change.

**Comment by MasonProtter** [comment]
CI failures appear to be unrelated. @dkarrasch @tkf could you re-review? This is important to get in for 1.5.

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 3]
```diff
@@ -267,10 +267,23 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
...
+end
+
 # Adjoint/Transpose-vector * vector
 *(u::AdjointAbsVec{T}, v::AbstractVector{T}) where {T<:Number} = dot(u.parent, v)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/adjtrans.jl:283]:
```suggestion
*(u::AdjointAbsVec{<:Number}, v::AbstractVector{<:Number}) = dot(u.parent, v)
```
IIUC, that's @marius311's suggestion, which I think is fine.

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:279]: Now, this reads basically exactly (up to the `*` vs `dot`) as:
https://github.com/JuliaLang/julia/blob/971e769479a2947a55cc253dc9750fd2a361367a/stdlib/LinearAlgebra/src/generic.jl#L886-L899
which I think is good.

**Review by dkarrasch — APPROVED** [review]

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 4]
```diff
@@ -267,10 +267,23 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
...
+        zero(eltype(u)) * zero(eltype(v))
+    else
+        sum(uu*vv for (uu, vv) in zip(u, v))
+    end
+end
+
 # Adjoint/Transpose-vector * vector
-*(u::AdjointAbsVec{T}, v::AbstractVector{T}) where {T<:Number} = dot(u.parent, v)
+*(u::AdjointAbsVec{<:Number}, v::AbstractVector{<:Number}) = dot(u.parent, v)
 *(u::TransposeAbsVec{T}, v::AbstractVector{T}) where {T<:Real} = dot(u.parent, v)
```
Comment (marius311) [inline stdlib/LinearAlgebra/src/adjtrans.jl:284]: Thanks for adding that change in. Any reason not to do the equivalent thing in 284 as well?

Comment (dkarrasch) [reply stdlib/LinearAlgebra/src/adjtrans.jl:284]: It's causing method ambiguities that I'm not in the mood now of resolving. I've reverted that. I think the `*(::TransVector,::AbstractVector)` is handled somewhere in `matmul.jl`.

File: stdlib/LinearAlgebra/src/adjtrans.jl [hunk 5]
```diff
@@ -267,10 +267,23 @@ Broadcast.broadcast_preserving_zero_d(f, tvs::Union{Number,TransposeAbsVec}...)
 
 ## multiplication *
 
+function _dot_nonrecursive(u, v)
+    lu = length(u)
+    if lu != length(v)
+        throw(DimensionMismatch("first array has length $(lu) which does not match the length of the second, $(length(v))."))
+    end
+    if lu == 0
```
Comment (tkf) [inline stdlib/LinearAlgebra/src/adjtrans.jl:275]: Re OffsetArrays support, I think it's enough to check `axes` like this?

```suggestion
function _dot_nonrecursive(u::AbstractVecOrMat, v::AbstractVecOrMat)
    if !(axes(u, 1) == axes(v, 2) && axes(u, 2) == axes(v, 1))
        throw(DimensionMismatch("dimensions of the first array $(axes(u)) and the second array $(axes(v)) are incompatible for a dot product."))
    end
    if isempty(u)
```

I think this is a kind of error that would have thrown if we use here `promote_shape(u', v)` (with a better error message).  Since something like `eachindex(a, b)` already throws an error with something like `eachindex(1:3, OffsetArray(1:3, -2:0))` simply based on `axes`, maybe it makes sense to check `axes` here?

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (tkf) [reply stdlib/LinearAlgebra/src/adjtrans.jl:279]: > `zero(eltype(_))` isn't defined (i.e. things like arrays of arrays.

Actually I feel like I did a similar suggestion before here that was ended up useless exactly due to this... I should have learned from a mistake.

File: stdlib/LinearAlgebra/src/adjtrans.jl (hunk 5 above)
Comment (MasonProtter) [reply stdlib/LinearAlgebra/src/adjtrans.jl:275]: Alternatively, we could just do 
```julia
@inbounds sum(u[i]*v[i] for i in eachindex(u, v))
```
However, I'm still not actually convinced it's even desirable to throw an error here. I'm also not convinced we *shouldn't* throw an error, but I will point out that that in the current state of affairs `transpose(u::OffsetVector) * v::Vector` currently has the same behaviour as the implementation in this PR (i.e. no error). I feel like it'd be good at least for 1.5 since it's so near, to just follow the lead of `transpose(u) * v` rather than being over eager about throwing errors. 

```julia
julia> using OffsetArrays

julia> let u = OffsetArray([1,2,3], -1:1), v = [1,2,3]
           transpose(u) * v
       end
14
```

Comment (pablosanjose) [reply stdlib/LinearAlgebra/src/adjtrans.jl:275]: I'm rather inclined towards throwing an error, as in the matrix-vector case. If the user really wants to contract an `o::OffsetArray` with a `v::Vector`, it is not complicated to do `OffsetArrays.no_offset_view(o)' * v`. Perhaps `no_offset_view` should be exported.

**Comment by JeffBezanson** [comment]
What's the status here? Would be good to get this resolved very soon.

**Comment by dkarrasch** [comment]
> What's the status here?

The remaining question is whether we should require that the two vectors have equal axes. Most functionality in `LinearAlgebra` does require one-based indexing and equal lengths, which seems to imply equal axes, but currently there is no such check here. So, adding that requirement (as suggested by consistency) means making something throw that currently doesn't.

**Comment by MasonProtter** [comment]
Im pretty wary of the idea of throwing an error here since this change will have so little time for someone to try it out and complain if it causes a problem. I think being as conservative as possible, just fixing the bug caused from unequal length vectors is the right way to go.

**Comment by timholy** [comment]
To me it seems clear this should be an error; the only other alternative I can see would be that
```julia
julia> a = [1, 3]
2-element Array{Int64,1}:
 1
 3

julia> b = OffsetArray([3, 7], 2:3)
2-element OffsetArray(::Array{Int64,1}, 2:3) with eltype Int64 with indices 2:3:
 3
 7
```
should yield `a'*b == 9`. I do not favor this solution, however.

Right before releasing Juila 1 I tried to go through the entire code base and at least make stuff fragile (meaning, throw an error eagerly) with respect to non-1 indices if no one had yet gotten around to generalizing the operation. Looks like this is a case that got missed?

**Comment by JeffBezanson** [comment]
Right now, the most important thing is to get something backportable, so I agree with Mason we should just fix the thing that changed in 1.5 and add further checks separately.

**Comment by timholy** [comment]
Agreed, what we do immediately does not have to be where we are heading.

**Comment by MasonProtter** [comment]
Then I think this PR is ready to merge.
