### PR TITLE
timedwait, sleep now validate arguments

### LINKED ISSUE #10855: sleep does not validate arguments
- [ ] `sleep`
```jl
julia> sleep(-0.5)
ERROR: InexactError()
 in start_timer at ./stream.jl:507
 in sleep at ./stream.jl:527
```

- [ ] `timedwait`

```jl
julia> timedwait(()->false, 1.0, pollint=-0.2) #Nonsensical polling interval
ERROR: InexactError()
 in start_timer at stream.jl:508
 in timedwait at multi.jl:1544
```

At the very least, these calls should throw `ArgumentError`s instead.

### PR DESCRIPTION
**Pull request by jiahao**
sleep now throws an error if called with a negative argument

timedwait errors if the optional pollint kwarg is set to a negative
number.

Closes #10855, #10847

### CODE REVIEW

File: base/stream.jl [hunk 1]
```diff
@@ -520,6 +520,7 @@ function stop_timer(timer::Timer)
 end
 
 function sleep(sec::Real)
+    sec ≥ 0 || throw(ArgumentError("cannot sleep for $sec seconds"))
```
Comment (tkelman) [inline base/stream.jl]: is there anything wrong with `sleep(0)` ?

Comment (tkelman) [inline base/stream.jl]: nevermind sorry
