### PR TITLE
Fix signature of git_libgit2_opts

### LINKED ISSUE #27007: Segmentation fault while buiilding sysimage
From my investigations this is a null-pointer dereference, but not a usercode one.
I also observed other weird compilations that all included a `ccall`.

```
signal (11): Segmentation fault
in expression starting at no file:0
set_ssl_cert_locations at /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v0.7/LibGit2/src/error.jl:0
__init__ at /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v0.7/LibGit2/src/LibGit2.jl:990
jfptr___init___18949 at /buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /buildworker/worker/package_linuxppc64le/build/src/gf.c:2167
jl_apply at /buildworker/worker/package_linuxppc64le/build/src/julia.h:1540 [inlined]
jl_module_run_initializer at /buildworker/worker/package_linuxppc64le/build/src/toplevel.c:90
_julia_init at /buildworker/worker/package_linuxppc64le/build/src/init.c:810
julia_init__threading at /buildworker/worker/package_linuxppc64le/build/src/task.c:302
main at /buildworker/worker/package_linuxppc64le/build/ui/repl.c:234
generic_start_main.isra.0 at /lib64/libc.so.6 (unknown line)
__libc_start_main at /lib64/libc.so.6 (unknown line)
Allocations: 5387 (Pool: 5378; Big: 9); GC: 0
make: *** [julia-base-cache] Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by Keno**
On most platforms this doesn't make a difference,
but the PowerPC ABI uses the signature to decide
whether or not to allocate a parameter save area.
Without this, the caller does not, but the callee
assumes it's there causing the callee to overwrite
critical parts of the caller stack.

Fixes #27007

### CODE REVIEW

File: stdlib/LibGit2/src/LibGit2.jl [hunk 1]
```diff
@@ -1003,7 +1003,7 @@ function set_ssl_cert_locations(cert_loc)
     cert_dir  = isdir(cert_loc) ? cert_loc : Cstring(C_NULL)
     cert_file == C_NULL && cert_dir == C_NULL && return
     @check ccall((:git_libgit2_opts, :libgit2), Cint,
-          (Cint, Cstring, Cstring),
+          (Cint, Cstring, Cstring...),
```
Comment (vtjnash) [inline stdlib/LibGit2/src/LibGit2.jl]: the `...` is on the wrong argument here. it should be `(Cint, Cstring...)`

Comment (Keno) [reply stdlib/LibGit2/src/LibGit2.jl]: Does it make a difference? The prototype at the llvm level doesn't match either way. This syntax is a bit odd in any case. C doesn't restrict the remaining args to be `Cstring` and for our own conversions we do kind of need to know for each argument what it was intended to be at the C level. I think we may have to redesign that part, but that's a separate discussion of course.

Comment (vtjnash) [reply stdlib/LibGit2/src/LibGit2.jl]: The llvm prototype will be exactly correct if you declare it correctly (modulo any implementation bugs). It might not make much difference, but why make it almost correct when you could make it entirely correct.
