### PR TITLE
use Iterators.reverse for foldr etc.

### LINKED ISSUE #24823: use reverse iteration protocol in foldr and mapfoldr
The `foldr` and `mapfoldr` operations require that one traverse an iterator in reverse order.  However, the [current implementation](https://github.com/JuliaLang/julia/blob/2316bb58cf5a180622ffe178df19df2322590d66/base/reduce.jl#L99-L113) assumes that the iterator supports `getindex` and `endof`.   Now that we have a reverse-iteration protocol, it would be good to use it here instead of `getindex`.

### LINKED ISSUE #31780: foldr fails for unicode strings
As reported [on discourse](https://discourse.julialang.org/t/allow-foldr-operation-for-strings/23343):
```jl
julia> foldr((x, y) -> (x * '|' * y), "λ x.x")
ERROR: StringIndexError("λ x.x", 2)
Stacktrace:
 [1] string_index_err(::String, ::Int64) at ./strings/string.jl:12
 [2] getindex_continued(::String, ::Int64, ::UInt32) at ./strings/string.jl:218
 [3] getindex at ./strings/string.jl:211 [inlined]
 [4] mapfoldr_impl(::typeof(identity), ::getfield(Main, Symbol("##5#6")), ::NamedTuple{(:init,),Tuple{Char}}, ::String, ::Int64) at ./reduce.jl:104
 [5] mapfoldr_impl(::Function, ::Function, ::NamedTuple{(),Tuple{}}, ::String, ::Int64) at ./reduce.jl:115
 [6] #mapfoldr#189 at ./reduce.jl:125 [inlined]
 [7] mapfoldr at ./reduce.jl:125 [inlined]
 [8] #foldr#190 at ./reduce.jl:144 [inlined]
 [9] foldr(::Function, ::String) at ./reduce.jl:144
 [10] top-level scope at none:0
```
I would consider this a bug, not just a limitation of `foldr`, because it silently works fine for ASCII strings.

### PR DESCRIPTION
**Pull request by stevengj**
This is an alternate version of #25520 (and #24833) that avoids wrapping `op` in a `Switch` type.    Rationale: avoids potential complications of overloading `mapreduce_empty_iter` and `mapreduce_first` discussed in https://github.com/JuliaLang/julia/pull/25520/files#r277144296, at a slight cost in code size.

Fixes #31780.  Closes #25520.  Fixes #24823.

Performance-wise it seems roughly identical to `master` in a simple benchmarks as I mentioned in #25520, ~~though for some reason `@btime` is now reporting `(1 allocation: 16 bytes)` whereas there were zero allocations before~~ (*update*: now fixed, see below).

### CODE REVIEW

**Comment by stevengj** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by stevengj** [comment]
In particular, it looks like *any* reversed-order array iteration, e.g. `foo(x) = foldl(-, Iterators.reverse(x))` or `bar(x) = sum(Iterators.reverse(x))`, gives `1 allocation: 16 bytes` from `@btime` on `master`.  Not sure why.

**Comment by KristofferC** [comment]
It is probably allocating the `Reverse` wrapper itself to pass it to the non-inlined `mapfoldl_impl`:

```
julia> @code_warntype bar(x)
Body::Float64
1 ── %1  = %new(Base.Iterators.Reverse{Array{Float64,1}}, x)::Base.Iterators.Reverse{Array{Float64,1}}
...
│    %35 = invoke Base.mapfoldl_impl(%2::typeof(identity), %3::typeof(Base.add_sum), %34::NamedTuple{(:init,),Tuple{Float64}}, %1::Base.Iterators.Reverse{Array{Float64,1}}, %30::Tuple{StepRange{Int64,Int64},Int64})::Float64
└───       goto #11

```

**Comment by KristofferC** [comment]
The explicit `@noinline` was added at https://github.com/JuliaLang/julia/pull/22210/commits/705a187e6812a6176a3738311757215236f758fc but I am not sure what the exact reason was.

**Comment by stevengj** [comment]
I can confirm that removing the `@noinline` removes the allocation.  I'll add that to this PR.

**Comment by KristofferC** [comment]
In `foo(x) = foldl(-, Iterators.reverse(x))` the reverse wrapper gets allocated because it is used in `mapreduce_empty_iter` which will en up throwing an error in the empty iterator case:

```
julia> @code_warntype foo(rand(5))
Body::Float64
1 ── %1  = %new(Base.Iterators.Reverse{Array{Float64,1}}, x)::Base.Iterators.Reverse{Array{Float64,1}}
9 ── %35 = Base.mapreduce_empty_iter::typeof(Base.mapreduce_empty_iter)
│          invoke %35(%3::Function, %2::Function, %1::Base.Iterators.Reverse{Array{Float64,1}}, $(QuoteNode(Base.HasEltype()))::Base.HasEltype)
└───       $(Expr(:unreachable))
```

```jl
julia> foo(Float64[])
ERROR: ArgumentError: reducing over an empty collection is not allowed
Stacktrace:
```

**Comment by stevengj** [comment]
Thanks for the tip; that's now fixed for `foldr`.

File: test/reduce.jl [hunk 1]
```diff
@@ -31,6 +31,8 @@ using .Main.OffsetArrays
 @test Base.mapfoldr(abs2, -, 2:5) == -14
 @test Base.mapfoldr(abs2, -, 2:5; init=10) == -4
 
+@test foldr((x, y) -> ('⟨' * x * '|' * y * '⟩'), "λ 🐨.α") == "⟨λ|⟨ |⟨🐨|⟨.|α⟩⟩⟩⟩" # issue #31780
+
```
Comment (KristofferC) [inline test/reduce.jl]: Perhaps it is worth adding `@allocated` test for the `foo` and `bar` functions (in https://github.com/JuliaLang/julia/pull/31781#issuecomment-485164510) since getting those to not allocate was a bit finicky?

**Comment by stevengj** [comment]
Added an allocation test.

**Comment by stevengj** [comment]
cc @timholy, not sure if you have any further thoughts about removing the `@noinline` annotation here.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31781#issuecomment-485158814) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1db17e7f0cbf405e3b306a397556f4ccd4245ae1/7aa7cf4_vs_4955696/report.md). cc @ararslan

File: base/reduce.jl [hunk 2]
```diff
@@ -91,28 +91,20 @@ foldl(op, itr; kw...) = mapfoldl(identity, op, itr; kw...)
...
+# we can't just call mapfoldl_impl with (x,y) -> op(y,x), because
+# we need to use the type of op for mapreduce_empty_iter and mapreduce_first.
+function mapfoldr_impl(f, op, nt::NamedTuple{()}, itr)
+    ritr = Iterators.reverse(itr)
+    y = iterate(ritr)
+    if y === nothing
         return Base.mapreduce_empty_iter(f, op, itr, IteratorEltype(itr))
     end
-    return mapfoldr_impl(f, op, (init=mapreduce_first(f, op, itr[i]),), itr, i-1)
+    (x, i) = y
```
Comment (KristofferC) [inline base/reduce.jl]:
```suggestion
    x, i = y
```

maybe?

Comment (stevengj) [reply base/reduce.jl]: Sure.  (I just copied it from `mapfoldl_impl`.)

Comment (stevengj) [reply base/reduce.jl]: Fixed.

**Comment by stevengj** [comment]
nanosoldier regressions look like unrelated noise.  (BaseBenchmarks.jl also doesn't call `foldr` directly.)

**Comment by stevengj** [comment]
Okay to merge? @StefanKarpinsky?
