### PR TITLE
make `ccallable` work with system images and precompilation

### LINKED ISSUE #35014: Outputting a @ccallable function to an object file broken on master
MWE from test failure in PackageCompiler.jl

```jl
# callable.jlj
Base.@ccallable function f()::Cint
    return 0
end
```

```jl
run(`$(Base.julia_cmd()) --startup=no --output-o=sys.o ccallable.jl`)
```

prints:

```
Assertion failed: (Val && "isa<> used on a null pointer"), function doit, file /Users/kristoffercarlsson/julia/usr/include/llvm/Support/Casting.h, line 105.

signal (6): Abort trap: 6
in expression starting at /Users/kristoffercarlsson/julia/ccallable.jl:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #35014

The approach I took is to add a field to `Method` storing the needed return type and signature if a C entry point is requested for that method. `jl_compile_extern_c` is called to inform the JIT during loading, or after loading a .ji or system image. The signatures are also added to the data passed to `jl_create_native` to tell it to include aliases in the system image.

A possible simplification is to require the argument types to be specific enough to be specialized. Currently, we allow `@ccallable f(x::Any) = ...`, in which case we need to generate a wrapper accepting any value and doing dynamic dispatch. If we required specific types, e.g. `f(x::Cint)`, then every ccallable would be associated with a single MethodInstance, and we'd just generate the alias whenever the instance is compiled.

It's not clear whether this feature is needed in the JIT, or just system images (i.e. only when you want to link a C program with direct calls against sys.so). The JIT case takes a bunch of the code here.

A separate problem to fix in the near future is that I believe ccallable and possibly also cfunction are always using jl_apply_generic when compiled into a system image, since `gen_cfun_wrapper` doesn't use the new mechanism for looking up call targets (there is already a TODO comment about the recursive compilation done there).

### CODE REVIEW

File: src/aotcompile.cpp [hunk 1]
```diff
@@ -271,7 +271,14 @@ void *jl_create_native(jl_array_t *methods, const jl_cgparams_t cgparams)
             continue;
         size_t i, l;
         for (i = 0, l = jl_array_len(methods); i < l; i++) {
-            mi = (jl_method_instance_t*)jl_array_ptr_ref(methods, i);
+            // each item in this list is either a MethodInstance indicating something
+            // to compile, or an svec(rettype, sig) describing a C-callable alias to create.
+            jl_value_t *item = jl_array_ptr_ref(methods, i);
+            if (jl_is_simplevector(item)) {
```
Comment (vtjnash) [inline src/aotcompile.cpp:277]:
```suggestion
            if (jl_is_simplevector(item) && worlds == 1) {
```

File: src/jitlayers.cpp [hunk 2]
```diff
@@ -197,47 +197,84 @@ static jl_callptr_t _jl_compile_codeinst(
...
+    for (i = 1; i < nargs; i++) {
+        jl_value_t *ati = jl_tparam(sigt, i);
+        if (jl_is_abstract_ref_type(ati)) {
+            ati = jl_tparam0(ati);
+            if (jl_is_typevar(ati))
+                jl_error("@ccallable: argument type Ref should have an element type, not Ref{<:T}");
+        }
+        if (jl_is_pointer(ati) && jl_is_typevar(jl_tparam0(ati)))
+            jl_error("@ccallable: argument type Ptr should have an element type, Ptr{<:T}");
+    }
```
Comment (vtjnash) [inline src/jitlayers.cpp:265]: Ah, I see this design is just handling all of the `Ref` declared signatures incorrectly. It seems part also of why they can't appropriately be attached to a single Method.

File: src/jitlayers.cpp [hunk 3]
```diff
@@ -197,47 +197,84 @@ static jl_callptr_t _jl_compile_codeinst(
...
+
+// declare a C-callable entry point; called during code loading from the toplevel
 extern "C" JL_DLLEXPORT
-void jl_extern_c(jl_function_t *f, jl_value_t *rt, jl_value_t *argt, char *name)
-{
+void jl_extern_c(jl_value_t *declrt, jl_tupletype_t *sigt)
+{
+    // validate arguments. try to do as many checks as possible here to avoid
+    // throwing errors later during codegen.
+    JL_TYPECHK(@ccallable, type, declrt);
```
Comment (vtjnash) [inline src/jitlayers.cpp:231]: Since this function is named `ccallable`, I don't think the `@` is really a part of the name.

File: src/jitlayers.cpp (hunk 2 above)
Comment (JeffBezanson) [reply src/jitlayers.cpp:265]: Yeah, I would be fine with not supporting `Ref` at all here --- no julia values, no by-reference, only simple types you'd write directly in C code. That would make a lot of this easier.

File: src/jitlayers.cpp (hunk 3 above)
Comment (JeffBezanson) [reply src/jitlayers.cpp:231]: The user-facing API is `@ccallable`. I'll add an underscore to `ccallable` to make that clear.

**Comment by JeffBezanson** [comment]
Review comments hopefully addressed now. For now I'm just going to be strict about what types are allowed, and later we can see if that can be leveraged to simplify the compilation flow.

**Comment by KristofferC** [comment]
Also fixes https://github.com/JuliaLang/julia/issues/34076 I guess?
