### PR TITLE
Fixed the algorithm for powers of a matrix.

### LINKED ISSUE #414: incorrect code for Matrix^Number
There are several issues with the [`^(A::AbstractMatrix, p::Number)`](https://github.com/JuliaLang/julia/blob/2a5b3d8fd717d2276ecae7ea832ab62b2758fb6e/base/linalg/dense.jl#L314-L323) method, illustrated by this example:

```julia
julia> B = [ 3  2
            -5 -3 ]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> B^2.0
2×2 Array{Int64,2}:
 -1   0
  0  -1

julia> B^2.01
ERROR: MethodError: no method matching isless(::Complex{Float64}, ::Int64)
Closest candidates are:
  isless(::AbstractFloat, ::Real) at operators.jl:98
  isless(::Real, ::Real) at operators.jl:266
Stacktrace:
 [1] (::Base.LinAlg.##17#18)(::Complex{Float64}) at ./<missing>:0
 [2] broadcast_t(::Function, ::Type{Any}, ::Tuple{Base.OneTo{Int64}}, ::CartesianRange{CartesianIndex{1}}, ::Array{Complex{Float64},1}) at ./broadcast.jl:255
 [3] broadcast_c at ./broadcast.jl:298 [inlined]
 [4] broadcast(::Function, ::Array{Complex{Float64},1}) at ./broadcast.jl:415
 [5] ^(::Array{Int64,2}, ::Float64) at ./linalg/dense.jl:320
```

* The promotion is wrong for `Matrix{Int}^Float64`, since it doesn't promote the matrix if the power is integer-valued.  The result is type-unstable and, more importantly, potentially wrong (since integers might overflow for large powers).

* It computes the eigenvalues `v` and checks whether they are negative via `any(v.<0)`, but this check is nonsensical if the eigenvalues are complex.

* Because it relies on the eigenvalue decomposition, it is potentially very inaccurate if the matrix is close to defective (and can fail entirely if it is defective, of course).  It would be better to use something like our `expm` algorithm here.

This is a pretty basic routine, so I was a little surprised to find it to be so buggy.

cc @jiahao and @andreasnoack (who have both touched this code).

### LINKED ISSUE #21143: incorrect code for Matrix^Number
There are several issues with the [`^(A::AbstractMatrix, p::Number)`](https://github.com/JuliaLang/julia/blob/2a5b3d8fd717d2276ecae7ea832ab62b2758fb6e/base/linalg/dense.jl#L314-L323) method, illustrated by this example:

```julia
julia> B = [ 3  2
            -5 -3 ]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> B^2.0
2×2 Array{Int64,2}:
 -1   0
  0  -1

julia> B^2.01
ERROR: MethodError: no method matching isless(::Complex{Float64}, ::Int64)
Closest candidates are:
  isless(::AbstractFloat, ::Real) at operators.jl:98
  isless(::Real, ::Real) at operators.jl:266
Stacktrace:
 [1] (::Base.LinAlg.##17#18)(::Complex{Float64}) at ./<missing>:0
 [2] broadcast_t(::Function, ::Type{Any}, ::Tuple{Base.OneTo{Int64}}, ::CartesianRange{CartesianIndex{1}}, ::Array{Complex{Float64},1}) at ./broadcast.jl:255
 [3] broadcast_c at ./broadcast.jl:298 [inlined]
 [4] broadcast(::Function, ::Array{Complex{Float64},1}) at ./broadcast.jl:415
 [5] ^(::Array{Int64,2}, ::Float64) at ./linalg/dense.jl:320
```

* The promotion is wrong for `Matrix{Int}^Float64`, since it doesn't promote the matrix if the power is integer-valued.  The result is type-unstable and, more importantly, potentially wrong (since integers might overflow for large powers).

* It computes the eigenvalues `v` and checks whether they are negative via `any(v.<0)`, but this check is nonsensical if the eigenvalues are complex.

* Because it relies on the eigenvalue decomposition, it is potentially very inaccurate if the matrix is close to defective (and can fail entirely if it is defective, of course).  It would be better to use something like our `expm` algorithm here.

This is a pretty basic routine, so I was a little surprised to find it to be so buggy.

cc @jiahao and @andreasnoack (who have both touched this code).

### PR DESCRIPTION
**Pull request by iamnapo**
Fixed JuliaLang/LinearAlgebra.jl#414 

I did a few small bug-fixes and also changed the [^(A::AbstractMatrix, p::Integer)](https://github.com/iamnapo/julia/blob/anj/powm/base/linalg/dense.jl#L314) algorithm a bit to make use of [powm(A0::UpperTriangular{T}, p::Real)](https://github.com/iamnapo/julia/blob/anj/powm/base/linalg/triangular.jl#L1671).

### CODE REVIEW

File: base/linalg/linalg.jl [hunk 1]
```diff
@@ -113,6 +113,7 @@ export
     ordschur,
     peakflops,
     pinv,
+    powm,
```
Comment (tkelman) [inline base/linalg/linalg.jl]: this is an internal helper function, it shouldn't be exported

**Comment by iamnapo** [comment]
fixed it.

**Comment by iamnapo** [comment]
I changed some and added a few more tests based on:
**Deadman & Higham [March 2014]** , **Higham & Lin [September 2013]**

**Comment by kshyatt** [comment]
Is this good to go?

**Comment by andreasnoack** [comment]
I don't know yet. I haven't looked carefully. What is the easiest way to resume? Should I open a PR from my branch or should this PR be against master?

**Comment by tkelman** [comment]
let's change this branch to be against master, so we can get a more complete view of the diff including the few commits from your branch

**Comment by tkelman** [comment]
and close/reopen to trigger CI, apparently changing the target branch doesn't do that

File: base/linalg/dense.jl [hunk 2]
```diff
@@ -309,17 +309,53 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
 kron(a::AbstractMatrix, b::AbstractVector)=kron(a,reshape(b,length(b),1))
 kron(a::AbstractVector, b::AbstractMatrix)=kron(reshape(a,length(a),1),b)
 
-^(A::AbstractMatrix, p::Integer) = p < 0 ? inv(A^-p) : Base.power_by_squaring(A,p)
-
-function ^(A::AbstractMatrix, p::Number)
+# Matrix power
+^(A::AbstractMatrix, p::Integer) = p < 0 ? Base.power_by_squaring(inv(A),-p) : Base.power_by_squaring(A,p)
+function ^{T}(A::AbstractMatrix{T}, p::Real)
```
Comment (tkelman) [inline base/linalg/dense.jl]: what's the right approach for complex `p` ? is there a different method for that?

Comment (andreasnoack) [inline base/linalg/dense.jl]: Not sure. Maybe we can ask @higham what the right approach is.

Comment (iamnapo) [inline base/linalg/dense.jl]: Only approach I found is by definition: `expm(p * logm(A))`. But @stevengj pointed out correctly that it's very expensive, so I didn't add it.

Comment (higham) [inline base/linalg/dense.jl]: I think that's all there is for complex p. If you do an initial Schur decomp of A then expm and logm are applied to triangular matrices, which reduces the cost.

File: base/intfuncs.jl [hunk 3]
```diff
@@ -193,7 +193,6 @@ end
 
 ^{T<:Integer}(x::T, p::T) = power_by_squaring(x,p)
 ^(x::Number, p::Integer)  = power_by_squaring(x,p)
-^(x, p::Integer)          = power_by_squaring(x,p)
```
Comment (iamnapo) [inline base/intfuncs.jl]: not sure if this should be here.

Comment (iamnapo) [inline base/intfuncs.jl]: not sure if this should be here.

File: base/linalg/dense.jl [hunk 4]
```diff
@@ -309,17 +309,60 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+    # non-inversible matrix to negative power is undefined.
+    if (p < 0) && (det(A) == 0)
+        throw(ArgumentError("Negative powers of singular matrix are not defined"))
+    end
 
-function ^(A::AbstractMatrix, p::Number)
+    # For integer powers, use repeated squaring
     if isinteger(p)
-        return A^Integer(real(p))
+        return p < 0 ? Base.power_by_squaring(inv(A),-Integer(p)) : Base.power_by_squaring(A,Integer(p))
```
Comment (stevengj) [inline base/linalg/dense.jl]: The promotion here is still wrong if `p` is not an integer, as explained in #21143.  `A^2.0` should produce a floating-point matrix even if `A` is integer.

The return type should be something like `Matrix{promote_op(^, eltype(A), typeof(p))}`.

Comment (stevengj) [inline base/linalg/dense.jl]: Also, note that `power_by_squaring` is pretty inefficient for matrices because it generates a lot of temporary matrices.  We should really have a specialized `_power_by_squaring!(Aᵖ::Matrix, A::Matrix, p::Integer)` function that minimizes the number of temporary arrays and uses a pre-allocated output array.  But that can be a separate PR, since it is just a performance optimization.

Comment (iamnapo) [inline base/linalg/dense.jl]: if `A` is integer, what should `A^2` produce?
On your second comment, you think we should always use diagonalization, even `p` is integer?

Comment (stevengj) [inline base/linalg/dense.jl]: If `A` is an integer matrix, `A^2` should be an integer matrix, but `A^2.0` should be a floating-point matrix.

We definitely should *not* use diagonalization for integer `p`, because it will be way slower even than what we are doing now, despite the temporary matrices.  e.g.
```jl
julia> A = randn(1000,1000); A = A'*A;

julia> @time A^4;
  0.428707 seconds (114.28 k allocations: 20.806 MiB, 20.50% gc time)

julia> @time A^4.5;
  3.669913 seconds (2.70 M allocations: 172.916 MiB, 2.36% gc time)
```

File: base/linalg/dense.jl [hunk 5]
```diff
@@ -310,15 +310,23 @@ kron(a::AbstractMatrix, b::AbstractVector)=kron(a,reshape(b,length(b),1))
 kron(a::AbstractVector, b::AbstractMatrix)=kron(reshape(a,length(a),1),b)
 
 # Matrix power
+function ^{T}(A::AbstractMatrix{T}, p::Integer)
+    # non-inversible matrix to negative power is undefined.
+    if (p < 0) && (det(A) == 0)
```
Comment (stevengj) [inline base/linalg/dense.jl]: This check does not seem like a good idea.  First, `inv(A)` will already throw an error if `A` is singular, and just as quickly as `det` will.  Second, computing `det(A)` means that you compute the LU factorization of `A` twice.   Third, you could get false positives because of underflow (`det([1e-300 0; 0 1e-300]) == 0` even though the matrix is not singular.

(Basically, you should forget everything you learned in high school about the determinant as a computational tool.)

File: base/linalg/dense.jl [hunk 6]
```diff
@@ -310,15 +310,23 @@ kron(a::AbstractMatrix, b::AbstractVector)=kron(a,reshape(b,length(b),1))
...
     # non-inversible matrix to negative power is undefined.
     if (p < 0) && (det(A) == 0)
         throw(ArgumentError("Negative powers of singular matrix are not defined"))
     end
 
     # For integer powers, use repeated squaring
-    if isinteger(p)
-        return p < 0 ? Base.power_by_squaring(inv(A),-Integer(p)) : Base.power_by_squaring(A,Integer(p))
+    if isinteger(p) && !(typeof(p) <: Int64)
+        return float.(A^Integer(p))
```
Comment (stevengj) [inline base/linalg/dense.jl]: This is not right.  First, `Matrix{Integer}^Integer` should be an integer matrix.   Second, for `Matrix{Int}^Float64` we need to convert to floating point and *then* exponentiate in order to avoid overflow problems.  Third, calling `float.(X)` will make an extra copy even if the matrix is already floating point.

We want something like:
```jl
convert(Matrix{promote_op(^, eltype(A), typeof(p)}, A)^Integer(p)
```
although that isn't quite right either: if `A` is not a `Matrix`, but is some other `AbstractMatrix` type, then we probably want the same type.  Maybe
```jl
T = Base.promote_op(^, eltype(A), typeof(p))
return T == eltype(A) ? A^Integer(p) : copy!(similar(A, T), A)^Integer(p)
```

File: base/intfuncs.jl (hunk 3 above)
Comment (stevengj) [inline base/intfuncs.jl]: This fallback method shouldn't be removed by this PR.

**Comment by iamnapo** [comment]
One thing I'm not sure is what should happen is `A` is singular and `p` is negative real

File: base/linalg/diagonal.jl [hunk 7]
```diff
@@ -285,7 +285,6 @@ logm(D::Diagonal) = Diagonal(log.(D.diag))
 logm(D::Diagonal{<:AbstractMatrix}) = Diagonal(logm.(D.diag))
 sqrtm(D::Diagonal) = Diagonal(sqrt.(D.diag))
 sqrtm(D::Diagonal{<:AbstractMatrix}) = Diagonal(sqrtm.(D.diag))
-^(D::Diagonal, p::Real) = Diagonal((D.diag).^p)
```
Comment (stevengj) [inline base/linalg/diagonal.jl]: Why was this method removed?

File: base/linalg/dense.jl [hunk 8]
```diff
@@ -309,17 +309,57 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+    # Check whether the matrix has nonpositive real eigs
+    np_real_eigs = false
+    for i = 1:n
+        if imag(d[i]) < eps() && real(d[i]) <= 0
+            np_real_eigs = true
+            break
+        end
+    end
+    if np_real_eigs
+        warn("Matrix with nonpositive real eigenvalues, a nonprincipal matrix power will be returned.")
```
Comment (stevengj) [inline base/linalg/dense.jl]: Maybe pass `once=true` here so that people don't see repeated warnings?

File: base/linalg/dense.jl [hunk 9]
```diff
@@ -309,17 +309,57 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+    end
+
+    if isreal(A) && ~np_real_eigs
```
Comment (stevengj) [inline base/linalg/dense.jl]: `!np_real_eigs`

File: base/linalg/triangular.jl [hunk 10]
```diff
@@ -1662,35 +1662,195 @@ At_ldiv_B(::Union{UnitUpperTriangular,UnitLowerTriangular}, ::RowVector) = throw
...
+
+    n = checksquare(A0)
+
+    A, m, s = invsquaring(A0,theta)
+
+    # Compute accurate diagonal of A - I
+    sqrt_diag!(A0, A, s)
+
+    # Compute the Gauss-Legendre quadrature formula
+    x, w = Base.QuadGK.gauss(Float64, m)
```
Comment (stevengj) [inline base/linalg/triangular.jl]: This won't work now that QuadGK was removed from Base, no?

Comment (stevengj) [inline base/linalg/triangular.jl]: Since it looks like `m ≤ length(theta)`, we can just precompute these and store them in a `const` array.

File: base/linalg/dense.jl (hunk 8 above)
Comment (iamnapo) [inline base/linalg/dense.jl]: you mean in something like `(A^0.5) * (A^0.5)`? If so, I'm not sure how to come up with a right key for the warning.

Comment (stevengj) [inline base/linalg/dense.jl]: The default key is the warning message, which seems fine here.

**Comment by iamnapo** [comment]
@stevengj 
If I put `once=true` then the warning will only show once, even if later I have a different matrix.
I removed `^(D::Diagonal, p::Real)` because it created ambigiuties with `^(x, p::Integer)`, for some reason.
Regarding  logm: #21179

File: test/linalg/dense.jl [hunk 11]
```diff
@@ -512,6 +512,49 @@ end
     @test_throws ArgumentError diag(zeros(0,1),2)
 end
 
+@testset "New matrix ^ implementation" for elty in (Float64, Complex{Float64})
+    A11 = convert(Matrix{elty}, rand(10, 10))
```
Comment (jebej) [inline test/linalg/dense.jl]: You might want to just have `rand(elty,10,10)` here so that you actually make complex matrices.

**Comment by iamnapo** [comment]
I think it's got to go now.

File: base/linalg/dense.jl [hunk 12]
```diff
@@ -309,17 +309,64 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+        R = full(S) ^ floor(p)
+        #Real part
+        R = R * full(powm(UpperTriangular(float.(S)), real(p - floor(p))))
+        retmat = Q * R * Q'
+    end
+
+    # Check whether the matrix has nonpositive real eigs
+    np_real_eigs = false
+    for i = 1:n
+        if imag(d[i]) < eps() && real(d[i]) <= 0
```
Comment (tkelman) [inline base/linalg/dense.jl]: should this be the eps of the element type? not sure how likely it would be to matter

**Comment by tkelman** [comment]
It evidently isn't tested, but tightening `^(A::AbstractMatrix, p::Number)` to `^(A::AbstractMatrix, p::Real)` and not having a method for other subtypes of Number could be breaking

File: base/linalg/symmetric.jl [hunk 13]
```diff
@@ -403,8 +403,55 @@ function svdvals!{T<:Real,S}(A::Union{Hermitian{T,S}, Symmetric{T,S}, Hermitian{
...
+end
+function ^(A::Hermitian, p::Integer)
+    n = checksquare(A)
+    if p < 0
+        retmat = Base.power_by_squaring(inv(A), -p)
+    else
+        retmat = Base.power_by_squaring(A, p)
+    end
+    for i = 1:n
+        retmat[i,i] = real(retmat[i,i])
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: I know there are separate issues where this has been discussed, but just checking - any imaginary components here should only ever be round-off, right? Does blas hemm touch the diagonal imaginary components or wouldn't it leave them alone? Is the issue round-off for julia-generic or non-blas element types?

File: base/linalg/symmetric.jl [hunk 14]
```diff
@@ -403,8 +403,55 @@ function svdvals!{T<:Real,S}(A::Union{Hermitian{T,S}, Symmetric{T,S}, Hermitian{
...
+            end
+            return Hermitian(retmat)
+        end
+    else
+        retmat = (F.vectors * Diagonal((complex(F.values).^p))) * F.vectors'
+        return retmat
+    end
+end
+
+function expm{T<:Real}(A::Symmetric{T})
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: would this, logm, and sqrtm for Symmetric of non-Real element types become no-method errors here?

File: base/linalg/triangular.jl [hunk 15]
```diff
@@ -1662,13 +1662,79 @@ At_ldiv_B(::Union{UnitUpperTriangular,UnitLowerTriangular}, ::RowVector) = throw
...
+
+    blockpower!(A0,S,p/(2^s))
+    for m = 1:s
+        A_mul_B!(Stmp.data,S,S)
+        copy!(S,Stmp)
+        blockpower!(A0,S,p/(2^(s-m)))
+    end
+    return S
+end
+^(A::LowerTriangular, p::Integer) = ^(A.', p::Integer).'
```
Comment (tkelman) [inline base/linalg/triangular.jl]: where is `^(::UpperTriangular, ::Integer)` implemented then? (needs-tests?)

File: base/linalg/triangular.jl [hunk 16]
```diff
@@ -1854,6 +1920,168 @@ function logm{T<:Union{Float64,Complex{Float64}}}(A0::UpperTriangular{T})
...
+            end
+            A[i,i] = z0 / r
+        end
+    end
+end
+
+# Repeatedly compute the square roots of A so that in the end its
+# eigenvalues are close enough to the positive real line
+function invsquaring(A0::UpperTriangular, theta)
+    maxsqrt = 100
```
Comment (tkelman) [inline base/linalg/triangular.jl]: would you ever need to change this?

File: base/linalg/triangular.jl [hunk 17]
```diff
@@ -1854,6 +1920,168 @@ function logm{T<:Union{Float64,Complex{Float64}}}(A0::UpperTriangular{T})
...
+    A = complex(copy(A0))
+    p = 0
+    m = 0
+
+    # Compute repeated roots
+    d = complex(diag(A))
+    dm1 = similar(d, n)
+    s = 0
+    for i = 1:n
+        dm1[i] = d[i] - 1.
```
Comment (tkelman) [inline base/linalg/triangular.jl]: looks like at the moment this function only gets called for BlasFloat element types, but still might be good to use `d[i] - 1` just for consistency, let element type promotion happen as usual (on single-precision this might result in unnecessary conversions otherwise)

File: base/linalg/triangular.jl [hunk 18]
```diff
@@ -1854,6 +1920,168 @@ function logm{T<:Union{Float64,Complex{Float64}}}(A0::UpperTriangular{T})
...
+    end
+    while norm(dm1, Inf) > theta[tmax]
+        for i = 1:n
+            d[i] = sqrt(d[i])
+        end
+        for i = 1:n
```
Comment (tkelman) [inline base/linalg/triangular.jl]: could be combined in the same loop? might be better for `d[i]` locality

File: base/linalg/triangular.jl [hunk 19]
```diff
@@ -1854,6 +1920,168 @@ function logm{T<:Union{Float64,Complex{Float64}}}(A0::UpperTriangular{T})
...
+        A = sqrtm(A)
+    end
+
+    AmI = A - I
+    d2 = sqrt(norm(AmI^2, 1))
+    d3 = cbrt(norm(AmI^3, 1))
+    alpha2 = max(d2, d3)
+    foundm = false
+    if alpha2 <= theta[2]
+        m = alpha2<=theta[1]?1:2
```
Comment (tkelman) [inline base/linalg/triangular.jl]: `m = (alpha2 <= theta[1]) ? 1 : 2` would be more readable

File: base/linalg/dense.jl (hunk 12 above)
Comment (iamnapo) [inline base/linalg/dense.jl]: There's also `typemin()` for example, but I thought default `eps()` is generally a safe condition to produce a warning. You think I should change it nevertheless?

File: base/linalg/dense.jl [hunk 20]
```diff
@@ -309,17 +309,64 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
-
-function ^(A::AbstractMatrix, p::Number)
+# Matrix power
+^{T}(A::AbstractMatrix{T}, p::Integer) = p < 0 ? Base.power_by_squaring(inv(A),-Integer(p)) : Base.power_by_squaring(A,Integer(p))
+function ^{T}(A::AbstractMatrix{T}, p::Real)
+    n = checksquare(A)
+    # Quick return if A is diagonal
+    if isdiag(A)
+        for i in 1:n
+            A[i, i] = A[i, i] ^ p
```
Comment (fredrikekre) [inline base/linalg/dense.jl]: This shouldn't update `A` inplace. Currently:
```julia
julia> a = 2*eye(2);

julia> b = a^2.
2×2 Array{Float64,2}:
 4.0  0.0
 0.0  4.0

julia> a
2×2 Array{Float64,2}:
 4.0  0.0
 0.0  4.0
```

File: base/linalg/triangular.jl (hunk 16 above)
Comment (iamnapo) [inline base/linalg/triangular.jl]: I don't think so

File: base/linalg/symmetric.jl (hunk 14 above)
Comment (iamnapo) [inline base/linalg/symmetric.jl]: No, these are covered by Hermitian methods

Comment (tkelman) [inline base/linalg/symmetric.jl]: what about complex symmetric, non hermitian?

Comment (iamnapo) [inline base/linalg/symmetric.jl]: oooh I'm sorry, for some reason I thought symmetric matrices are always hermitian

Comment (tkelman) [inline base/linalg/symmetric.jl]: it's a bit of a niche type, a fair number of routines even in blas or lapack aren't always implemented for c/z symmetric

File: base/linalg/dense.jl [hunk 21]
```diff
@@ -315,10 +315,11 @@ function ^{T}(A::AbstractMatrix{T}, p::Real)
     n = checksquare(A)
     # Quick return if A is diagonal
     if isdiag(A)
+        retmat = A
```
Comment (tkelman) [inline base/linalg/dense.jl]: you need to call `copy(A)` here

File: base/linalg/dense.jl [hunk 22]
```diff
@@ -309,17 +309,65 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+    end
+    # For integer powers, use repeated squaring
     if isinteger(p)
-        return A^Integer(real(p))
+        TT = Base.promote_op(^, eltype(A), typeof(p))
+        return (TT == eltype(A) ? A : copy!(similar(A, TT), A))^Integer(p)
+    end
+
+    # If possible, use diagonalization
+    if issymmetric(A) && T <: Real
```
Comment (stevengj) [inline base/linalg/dense.jl]: maybe `T <: Real && issymmetric(A)` to make sure that the type is checked first.

File: base/linalg/dense.jl (hunk 12 above)
Comment (stevengj) [inline base/linalg/dense.jl]: This is not a good way to do the test because it depends on overall scaling of the matrix (if you multiply the whole matrix by `1e±100` the result will change).

Also, shouldn't you be checking `abs(imag)`, not `imag`?  And shouldn't the warning be for `real < 0`, not real ≤ 0`?

I'm not sure what a robust test would be here.  Maybe `abs(imag(d[i])) ≤ ɛ`, where `ɛ = eps(maxabs(d))`?

File: base/linalg/symmetric.jl [hunk 23]
```diff
@@ -403,8 +403,55 @@ function svdvals!{T<:Real,S}(A::Union{Hermitian{T,S}, Symmetric{T,S}, Hermitian{
...
+function ^{T<:Real}(A::Symmetric{T}, p::Integer)
+    if p < 0
+        return Symmetric(Base.power_by_squaring(inv(A), -p))
+    else
+        return Symmetric(Base.power_by_squaring(A, p))
+    end
+end
+function ^{T<:Real}(A::Symmetric{T}, p::Real)
+    F = eigfact(full(A))
+    if isposdef(F)
```
Comment (stevengj) [inline base/linalg/symmetric.jl]: We should allow positive semidefinite here, not just positive definite

Comment (stevengj) [inline base/linalg/symmetric.jl]: (similarly below)

File: base/linalg/triangular.jl [hunk 24]
```diff
@@ -1854,6 +1919,166 @@ function logm{T<:Union{Float64,Complex{Float64}}}(A0::UpperTriangular{T})
...
+            A[i,i] = z0 / r
+        end
+    end
+end
+
+# Repeatedly compute the square roots of A so that in the end its
+# eigenvalues are close enough to the positive real line
+function invsquaring(A0::UpperTriangular, theta)
+    maxsqrt = 100
+    tmax = size(theta, 1)
```
Comment (stevengj) [inline base/linalg/triangular.jl]: the `theta` array is assumed to be sorted in ascending, I think?  This is fine, but it should be documented by a comment at the top

File: base/linalg/triangular.jl [hunk 25]
```diff
@@ -1854,6 +1919,166 @@ function logm{T<:Union{Float64,Complex{Float64}}}(A0::UpperTriangular{T})
...
+    A = complex(copy(A0))
+    p = 0
+    m = 0
+
+    # Compute repeated roots
+    d = complex(diag(A))
+    dm1 = similar(d, n)
+    s = 0
+    for i = 1:n
+        dm1[i] = d[i] - 1
```
Comment (stevengj) [inline base/linalg/triangular.jl]: this seems weird to me, because it doesn't seem dimensionally correct: `d` is potentially dimensionful but `1` is dimensionless.

The comparisons of `dm1` to the dimensionless `theta` are also weird for the same reason.

Another way of saying it is why isn't this algorithm scale-invariant?  i.e. why should we be treating `A` and `1000A` differently?   I wonder if the algorithm should be dividing `A` by its norm somewhere to make it dimensionless?

File: base/linalg/triangular.jl (hunk 16 above)
Comment (stevengj) [inline base/linalg/triangular.jl]: It looks like it should depend on `theta[tmax]` at least, which could change in e.g. bigfloat precision.

File: base/linalg/symmetric.jl (hunk 23 above)
Comment (iamnapo) [inline base/linalg/symmetric.jl]: Is there a method in julia for that?

File: base/linalg/dense.jl [hunk 26]
```diff
@@ -309,17 +309,65 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+
+    # Check whether the matrix has nonpositive real eigs
+    np_real_eigs = false
+    for i = 1:n
+        if imag(d[i]) < eps() && real(d[i]) <= 0
+            np_real_eigs = true
+            break
+        end
+    end
+    if np_real_eigs
```
Comment (KristofferC) [inline base/linalg/dense.jl]: Unconditional warnings like this are typically annoying because they end up being thrown in loops and spams the terminal. Isn't it enough to document what happens and then do that thing silently?

File: base/linalg/symmetric.jl (hunk 23 above)
Comment (stevengj) [inline base/linalg/symmetric.jl]: I don't think so.  Just check `if all(λ -> λ ≥ 0, eigvals(F))`?

Or maybe check `λ ≥ -ε` for some appropriate `ε`, similar to above?

File: base/linalg/dense.jl (hunk 26 above)
Comment (stevengj) [inline base/linalg/dense.jl]: That's why I suggested using `warn_once`

Comment (KristofferC) [inline base/linalg/dense.jl]: I did not see that. I still think documenting it is enough.

**Comment by iamnapo** [comment]
Should I remove the nonpositive real eigs warning althogether and just update the documentation?

File: base/linalg/dense.jl (hunk 26 above)
Comment (iamnapo) [inline base/linalg/dense.jl]: Should I remove the  warning altogether and just update the documentation?

File: base/linalg/triangular.jl (hunk 25 above)
Comment (iamnapo) [inline base/linalg/triangular.jl]: `invsquaring` is only used by [`powm`](https://github.com/JuliaLang/julia/pull/21184/files#diff-a73c39358f896eb4f7ef800a8bf481ceR1671) at the moment. Should I try to make it more generic now? ( Also regarding comments about `maxsqrt` above)

File: base/linalg/dense.jl [hunk 27]
```diff
@@ -343,31 +345,16 @@ function ^{T}(A::AbstractMatrix{T}, p::Real)
         retmat = retmat * full(powm(UpperTriangular(float.(A)), real(p - floor(p))))
         d = diag(A)
     else
-        S,Q,d = schur(complex(A))
+        S,Q,d = schur(complex(full(A)))
```
Comment (tkelman) [inline base/linalg/dense.jl]: why shouldn't this let a specialized method of `schur` be called when there is one?

File: base/linalg/triangular.jl (hunk 25 above)
Comment (stevengj) [inline base/linalg/triangular.jl]: Even for use by powm, it seems odd that the algorithm is not scale invariant. Are you sure this is correct?

File: base/linalg/dense.jl (hunk 27 above)
Comment (iamnapo) [inline base/linalg/dense.jl]: For something like `A = Symmetric([2 3+4im; 3+4im 8])`

Comment (iamnapo) [inline base/linalg/dense.jl]: For something like `A = Symmetric([2 3+4im; 3+4im 8])`

Comment (stevengj) [inline base/linalg/dense.jl]: Shouldn't the `schur` function have a method that calls `full` if necessary?

Why wouldn't you just do `schur(A)`?

File: base/linalg/triangular.jl (hunk 25 above)
Comment (iamnapo) [inline base/linalg/triangular.jl]: The algorithm is explained [here](http://eprints.ma.man.ac.uk/2021/01/hili13.pdf) and this seems to be in line with the [code provided by the author](https://www.mathworks.com/matlabcentral/fileexchange/41621-fractional-matrix-powers-with-frechet-derivatives-and-condition-number-estimate). Also, it produced correct results with every example I used.

Comment (stevengj) [inline base/linalg/triangular.jl]: I looked at the paper, and it is also not dimensionally correct.  I have no doubt that it produces the right answer, but it is still unsatisfying to have an algorithm where the number of iterations depends on an overall scaling (and it will cause trouble with arrays of dimensionful quantities).

My instict would be to compute `A^p = α^p (A/α)^p`, where `α = norm(A,1)` is a scale factor that makes  `A/α` dimensionless and scale-invariant.  That is, apply the Higham algorithm to `A/α`.  (The cost of the additional scaling step should be negligible.)

Comment (stevengj) [inline base/linalg/triangular.jl]: (From the looks of it, if anything, scaling by the norm will improve the performance of the algorithm, particulary if you apply it to `1e±100*A` for an `A` of order unity: it will decrease the number of matrix square roots required.)

File: base/linalg/dense.jl [hunk 28]
```diff
@@ -354,7 +354,11 @@ function ^{T}(A::AbstractMatrix{T}, p::Real)
     end
 
     # if A has nonpositive real eigenvalues, retmat is a nonprincipal matrix power.
-    return retmat
+    if isreal(retmat)
+        return real.(retmat)
```
Comment (stevengj) [inline base/linalg/dense.jl]: `real(retmat)` works and is faster if `retmat` is already a real type.

File: base/linalg/dense.jl (hunk 27 above)
Comment (iamnapo) [inline base/linalg/dense.jl]: It should, I guess.

Because I need the complex schur form which is different for e.g. `A = [0 1; -1 0]`

File: base/linalg/triangular.jl (hunk 25 above)
Comment (iamnapo) [inline base/linalg/triangular.jl]: I'm not sure I understood you correctly:
```julia
julia> A = rand(1000, 1000);

julia> p = 1/2;

julia> @time (B = A^p);
 29.278370 seconds (3.45 M allocations: 966.345 MiB, 1.79% gc time)

julia> @time (n = norm(A,1); C = (n^p) * ((A/n)^p);)
 27.698599 seconds (102.70 k allocations: 1.086 GiB, 1.35% gc time)

julia> norm(B - sqrtm(A))
2.38568013239948e-11

julia> norm(C - sqrtm(A))
1183.3092335613323
```

Comment (stevengj) [inline base/linalg/triangular.jl]: @iamnapo, it looks like that's a consequence of taking a non-principal root.  If you look at `norm(C^2 - A)` it should be small.

This is another reason to rescale the matrix, in my mind: which non-principal root we take should not depend on the units (overall scaling).

Comment (stevengj) [inline base/linalg/triangular.jl]: (That being said, for `p=integer + 0.5` we should probably call `sqrtm`.)

File: base/linalg/dense.jl [hunk 29]
```diff
@@ -309,17 +309,65 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+        end
+        return retmat
+    end
+
+    # Otherwise, use Schur decomposition
+    if istriu(A)
+        #Integer part
+        retmat = full(A) ^ floor(p)
+        #Real part
+        if floor(p) == 0.5
```
Comment (simonbyrne) [inline base/linalg/dense.jl]: how can `floor(p) == 0.5`?

Comment (simonbyrne) [inline base/linalg/dense.jl]: Ah, is it supposed to be `p - floor(p) == 0.5`?

File: base/linalg/triangular.jl [hunk 30]
```diff
@@ -1662,13 +1662,81 @@ At_ldiv_B(::Union{UnitUpperTriangular,UnitLowerTriangular}, ::RowVector) = throw
...
+#     a matrix and their Fréchet derivatives", SIAM. J. Matrix Anal. & Appl.,
+#     34(3), (2013) 1341–1360.
+function powm(A0::UpperTriangular{T}, p::Real) where T<:BlasFloat
+
+    if abs(p) >= 1
+        ArgumentError("p must be a real number in (-1,1), got $p")
+    end
+
+    normA0 = norm(A0, 1)
+    normalizedA0 = A0 / normA0
```
Comment (stevengj) [inline base/linalg/triangular.jl]: can we scale A0 in-place (renaming to `powm!`), since it seems like this routine is always called on a copy?

File: base/linalg/triangular.jl [hunk 31]
```diff
@@ -1662,13 +1662,81 @@ At_ldiv_B(::Union{UnitUpperTriangular,UnitLowerTriangular}, ::RowVector) = throw
...
+        @inbounds S[i,i] = S[i,i] + 1
+    end
+
+    blockpower!(A0,S,p/(2^s))
+    for m = 1:s
+        A_mul_B!(Stmp.data,S,S)
+        copy!(S,Stmp)
+        blockpower!(A0,S,p/(2^(s-m)))
+    end
+    return (normA0^p) * S
```
Comment (stevengj) [inline base/linalg/triangular.jl]: use `scale!` to scale in-place.

File: base/linalg/triangular.jl [hunk 32]
```diff
@@ -1662,13 +1662,81 @@ At_ldiv_B(::Union{UnitUpperTriangular,UnitLowerTriangular}, ::RowVector) = throw
 Ac_ldiv_B(::Union{UpperTriangular,LowerTriangular}, ::RowVector) = throw(DimensionMismatch("Cannot left-divide matrix by transposed vector"))
 Ac_ldiv_B(::Union{UnitUpperTriangular,UnitLowerTriangular}, ::RowVector) = throw(DimensionMismatch("Cannot left-divide matrix by transposed vector"))
 
+# Complex matrix power for upper triangular factor, see:
+#   Higham and Lin, "A Schur-Padé algorithm for fractional powers of a Matrix",
+#     SIAM J. Matrix Anal. & Appl., 32 (3), (2011) 1056–1078.
+#   Higham and Lin, "An improved Schur-Padé algorithm for fractional powers of
+#     a matrix and their Fréchet derivatives", SIAM. J. Matrix Anal. & Appl.,
+#     34(3), (2013) 1341–1360.
+function powm(A0::UpperTriangular{T}, p::Real) where T<:BlasFloat
```
Comment (stevengj) [inline base/linalg/triangular.jl]: since it looks like you don't use `T`, you can just do `A0::UpperTriangular{<:BlasFloat}`

File: test/linalg/dense.jl [hunk 33]
```diff
@@ -512,6 +512,20 @@ end
     @test_throws ArgumentError diag(zeros(0,1),2)
 end
 
+@testset "Matrix to real power" for elty in (Float64, Complex{Float64})
+# Tests proposed at Higham, Deadman: Testing Matrix Function Algorithms Using Identities, March 2014
+    A11 = rand(elty, 10, 10)
```
Comment (stevengj) [inline test/linalg/dense.jl]: I would rather do a fixed `A11 = [....]` matrix here, though, than a random one.  We don't want the tests to fail just because `rand` was unlucky.  Also, we should probably test a matrix that is close to defective, which is unlikely with `rand`.

Comment (stevengj) [inline test/linalg/dense.jl]: And we should test real matrices that have (a) all positive real eigenvalues, (b) a mix of positive and negative real eigenvalues and (c) complex eigenvalues.

File: base/linalg/symmetric.jl (hunk 13 above)
Comment (stevengj) [inline base/linalg/symmetric.jl]: Yes, the imaginary part is guaranteed to be zero, so any nonzero imaginary part is purely due to roundoff errors.

The errors arise for any values, including blas floats, because multiplying by the matrix of eigenvectors uses the general matmul routine.  I don't think there is a specialized BLAS routine for `matrix * real diagonal * matrix'`, which is the operation here.

Comment (stevengj) [inline base/linalg/symmetric.jl]: Sorry, for Hermitian^p the operation is `hermitian * hermitian`, but again there is no specialized method for this because in general the result would not be Hermitian.  (The result is Hermitian here because the matrices being multiplied are A^p and A^q, i.e. different powers of the same Hermitian matrix.)

Comment (stevengj) [inline base/linalg/symmetric.jl]: For example, note the nonzero imaginary parts on the diagonal of:
```jl
julia> A = rand(Complex128,10,10); A = Hermitian(A + A')
10×10 Hermitian{Complex{Float64},Array{Complex{Float64},2}}:
 0.0861346-0.0im        0.837547-0.743436im   …     1.09493-0.163298im 
  0.837547+0.743436im    1.96064-0.0im             0.491744-0.792954im 
  0.869364-0.131544im    1.06965-0.252339im        0.370136+0.0155668im
   0.83727+0.303993im    1.18724+0.108695im         1.38671+0.191601im 
   1.50475+0.357721im    1.00663-0.421604im         1.02963-0.13435im  
    1.1999+0.0748608im  0.370293+0.503285im   …     1.13011-0.0552782im
   1.56458+0.546159im   0.512528-0.0406777im       0.721986+0.445042im 
  0.394002+0.645965im   0.935305-0.473984im        0.971132+0.493203im 
  0.741598-0.175156im    1.91631+0.111909im        0.868631+0.834707im 
   1.09493+0.163298im   0.491744+0.792954im      0.00985939-0.0im      

julia> imag(diag(A^2 * A^3))
10-element Array{Float64,1}:
 0.0        
 5.68434e-14
 0.0        
 0.0        
 0.0        
 4.54747e-13
 0.0        
 5.68434e-14
 0.0        
 0.0        
```

Comment (andreasnoack) [inline base/linalg/symmetric.jl]: https://github.com/JuliaLang/julia/pull/17367

File: base/linalg/dense.jl (hunk 27 above)
Comment (stevengj) [inline base/linalg/dense.jl]: It should be possible to compute the complex Schur form from the real Schur form, but I guess that can be left for another PR.

**Comment by iamnapo** [comment]
I'm not sure why the spawn test failed. It runs fine on my Mac.

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
LGTM.  The Travis failure seems unrelated.

File: base/linalg/symmetric.jl [hunk 34]
```diff
@@ -403,7 +403,54 @@ function svdvals!{T<:Real,S}(A::Union{Hermitian{T,S}, Symmetric{T,S}, Hermitian{
...
+#Matrix functions
+function ^{T<:Real}(A::Symmetric{T}, p::Integer)
+    if p < 0
+        return Symmetric(Base.power_by_squaring(inv(A), -p))
+    else
+        return Symmetric(Base.power_by_squaring(A, p))
+    end
+end
+function ^{T<:Real}(A::Symmetric{T}, p::Real)
+    F = eigfact(full(A))
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: why is it we need the full call here?

Comment (stevengj) [inline base/linalg/symmetric.jl]: (In general, a lot of the `full` calls seem odd to me; we seem better off adding additional methods elsewhere, but I thought that could be left for another PR.  This particular one is especially egregious though because `eigfact` should be especially efficient for real-symmetric matrices.   What happens if you just delete all of the `full` calls?)

**Comment by jebej** [comment]
Thanks for pushing with this. It would be really great to have it for 0.6.0

File: base/linalg/dense.jl [hunk 35]
```diff
@@ -309,17 +309,65 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
 kron(a::AbstractMatrix, b::AbstractVector)=kron(a,reshape(b,length(b),1))
 kron(a::AbstractVector, b::AbstractMatrix)=kron(reshape(a,length(a),1),b)
 
-^(A::AbstractMatrix, p::Integer) = p < 0 ? inv(A^-p) : Base.power_by_squaring(A,p)
-
-function ^(A::AbstractMatrix, p::Number)
+# Matrix power
+^{T}(A::AbstractMatrix{T}, p::Integer) = p < 0 ? Base.power_by_squaring(inv(A),-Integer(p)) : Base.power_by_squaring(A,Integer(p))
```
Comment (jebej) [inline base/linalg/dense.jl]: Is `Integer(p)` needed here?

**Comment by tkelman** [comment]
The tightening of the allowed power type here from Number to Real would currently break `[1 2; 3 4]^im`

**Comment by iamnapo** [comment]
@tkelman I'm not sure where are you referring to

**Comment by tkelman** [comment]
it's collapsed right now, but the line at https://github.com/JuliaLang/julia/pull/21184#discussion_r108523279

**Comment by iamnapo** [comment]
Currently `[1 2; 3 4]^im` produces a `MethodError`. What do you think should happen?

(I plan on working at `function ^{T}(A::AbstractMatrix{T}, p::Complex)` at another PR)

**Comment by tkelman** [comment]
On master it gives a consistent answer with http://www.wolframalpha.com/input/?i=N%5B%7B%7B1,+2%7D,+%7B3,+4%7D%7D%5EI%5D. I don't know of a use case for this off the top of my head, but that doesn't seem like a good reason to change it from consistent with Wolfram to an error.

File: base/linalg/dense.jl (hunk 2 above)
Comment (stevengj) [inline base/linalg/dense.jl]: It would be reasonable to have `^(A::AbstractMatrix, p::Number) = expm(p * logm(A))` as a fallback.  We can optimize it later if needed.

**Comment by stevengj** [comment]
@iamnapo, we should just add the `^(A::AbstractMatrix, p::Number) = expm(p*logm(A))` fallback routine and a test.

File: base/linalg/dense.jl [hunk 36]
```diff
@@ -309,18 +309,67 @@ kron(a::AbstractVector, b::AbstractVector)=vec(kron(reshape(a,length(a),1),resha
...
+        retmat = A ^ floor(p)
+        #Real part
+        if p - floor(p) == 0.5
+            # special case: A^0.5 === sqrtm(A)
+            retmat = retmat * sqrtm(A)
+        else
+            retmat = retmat * powm!(UpperTriangular(float.(A)), real(p - floor(p)))
+        end
+    else
+        S,Q,d = schur(complex(full(A)))
```
Comment (tkelman) [inline base/linalg/dense.jl]: another full that may have been missed, or was this one needed?

File: base/linalg/symmetric.jl [hunk 37]
```diff
@@ -423,10 +470,8 @@ function expm{T}(A::Hermitian{T})
 end
 
 for (funm, func) in ([:logm,:log], [:sqrtm,:sqrt])
-
     @eval begin
-
-        function ($funm)(A::Symmetric)
+        function ($funm){T<:Real}(A::Symmetric{T})
```
Comment (tkelman) [inline base/linalg/symmetric.jl]: is the problem for `Symmetric{<:Complex}` that `isposdef` doesn't work?

Comment (stevengj) [inline base/linalg/symmetric.jl]: No, the issue is that `Symmetric{<:Complex}` may have ill-conditioned eigenvectors `F.vectors`.  Whereas for real-symmetric matrices the eigenvectors are unitary.  The complex analogue is a Hermitian matrix, not complex-symmetric.

Comment (tkelman) [inline base/linalg/symmetric.jl]: Cool. Useful to write that down somewhere, I wouldn't have remembered that detail from a linear algebra textbook.

File: base/linalg/dense.jl (hunk 36 above)
Comment (iamnapo) [inline base/linalg/dense.jl]: This one is needed

Comment (tkelman) [inline base/linalg/dense.jl]: good to know - what was happening without it?

Comment (iamnapo) [inline base/linalg/dense.jl]: if `A` is symmetric with complex values, but not hermitian

Comment (stevengj) [inline base/linalg/dense.jl]: @iamnapo, do you mean that there was a methoderror for `schur(::Symmetric{<:Complex}}`?  It would be better to solve that by adding a method to `shur` or `shurfact` that calls `full`.

Comment (stevengj) [inline base/linalg/dense.jl]: Looks like we just need:
```
schur(A::Symmetric{<:Complex}) = schur(full(A))
```

Comment (iamnapo) [inline base/linalg/dense.jl]: Yes. I'll add it.

File: base/linalg/schur.jl [hunk 38]
```diff
@@ -107,6 +107,7 @@ function schur(A::StridedMatrix)
     SchurF = schurfact(A)
     SchurF[:T], SchurF[:Z], SchurF[:values]
 end
+schur(A::AbstractMatrix) = schur(full(A))
```
Comment (stevengj) [inline base/linalg/schur.jl]: The problem with this definition is that it will produce an infinite loop for any `AbstractMatrix` type where `full(A) === A` and there is no more-specific `schur` method.

I would just add `schur(A::Triangular{<:Complex}) = schur(full(A))` (and anything else as needed).

Comment (iamnapo) [inline base/linalg/schur.jl]: Isn't `full(A)` always of type `StridedMatrix`? If not, I'll lot into it because just adding a  command like that (`Symmetric, Hermitian, Triangular` etc) in shur.jl, produces UndefVarError.

File: base/linalg/schur.jl [hunk 39]
```diff
@@ -111,8 +111,7 @@ schur(A::Symmetric) = schur(full(A))
 schur(A::Hermitian) = schur(full(A))
 schur(A::UpperTriangular) = schur(full(A))
 schur(A::LowerTriangular) = schur(full(A))
-
-
+schur(A::Tridiagonal) = schur(full(A))
```
Comment (stevengj) [inline base/linalg/schur.jl]: These methods can obviously be made vastly more efficient.  For example, an upper-triangular matrix is *already* in Schur form.  But that can be left for another PR.

**Comment by tkelman** [comment]
Do the original 2 commits by a different author pass on their own? Any failing commits should be squashed here, but git is bad at attribution if you squash together commits by different authors. Otherwise this lgtm now, thanks for the epic persistence @iamnapo !

File: base/linalg/schur.jl (hunk 39 above)
Comment (iamnapo) [inline base/linalg/schur.jl]: Of course. I just added these definitions to make it work for now. I plan to work on `schur()` after this PR is closed.

**Comment by iamnapo** [comment]
I don't think there will be a problem, but in the case there is, you can use command line to `--amend` authorship, if that's what you mean.

**Comment by Sacha0** [comment]
> thanks for the epic persistence @iamnapo !

Epic persistence indeed! Thanks @iamnapo! :)

**Comment by iamnapo** [comment]
is this good to go?
