### PR TITLE
Fix behaviour of scale! for triangular matrices (fixes #12903)

### LINKED ISSUE #244: scale!(A,b) for triangular matrices is actually scale(A,b)
For reference, the code I blame is

``` javascript
for (t1, t2) in ([:UnitLowerTriangular, :LowerTriangular],
                 [:UnitUpperTriangular, :UpperTriangular])
    @eval begin
        function scale!{T,S<:Number}(A::$(t1){T}, c::S)
            D = $(t2)(Array(promote_type(T,S), size(A)...));
            scale!(D,A,c);
            return D
        end
        function scale!{T,S<:Number}(A::$(t2){T}, c::S)
            D = $(t2)(Array(promote_type(T,S), size(A)...));
            scale!(D,A,c);
            return D
        end
    end
end
```

The code does not modify the input matrix `A`, but instantiates and returns a new matrix. I think this can be solved easily for `UpperTriangular` and `LowerTriangular`, as rewriting the method to modify `A` in place and return it should be enough, but I am not sure what I should do with the `Unit` versions.
These methods cannot be removed as they are used by `scale(A,c)`, but `A` cannot be modified in place without changing type (from `UnitUpperTriangular` to `UpperTriangular` and from `UnitLowerTriangular` to `LowerTriangular`).

### LINKED ISSUE #12903: scale!(A,b) for triangular matrices is actually scale(A,b)
For reference, the code I blame is
```javascript
for (t1, t2) in ([:UnitLowerTriangular, :LowerTriangular],
                 [:UnitUpperTriangular, :UpperTriangular])
    @eval begin
        function scale!{T,S<:Number}(A::$(t1){T}, c::S)
            D = $(t2)(Array(promote_type(T,S), size(A)...));
            scale!(D,A,c);
            return D
        end
        function scale!{T,S<:Number}(A::$(t2){T}, c::S)
            D = $(t2)(Array(promote_type(T,S), size(A)...));
            scale!(D,A,c);
            return D
        end
    end
end
```
The code does not modify the input matrix `A`, but instantiates and returns a new matrix. I think this can be solved easily for `UpperTriangular` and `LowerTriangular`, as rewriting the method to modify `A` in place and return it should be enough, but I am not sure what I should do with the `Unit` versions.
These methods cannot be removed as they are used by `scale(A,c)`, but `A` cannot be modified in place without changing type (from `UnitUpperTriangular` to `UpperTriangular` and from `UnitLowerTriangular` to `LowerTriangular`).

### PR DESCRIPTION
**Pull request by mfasi**
Make `scale!` modify input matrix for `UpperTriangular` and `LowerTriangular`, remove `scale!` method for `UnitUpperTriangular` and `UnitLowerTriangular`. 

[would close JuliaLang/LinearAlgebra.jl#244]

### CODE REVIEW

File: base/linalg/triangular.jl [hunk 1]
```diff
@@ -324,20 +325,21 @@ function scale!{T<:Union{LowerTriangular, UnitLowerTriangular}}(A::LowerTriangul
...
-        function scale!{T,S<:Number}(A::$(t1){T}, c::S)
-            D = $(t2)(Array(promote_type(T,S), size(A)...));
-            scale!(D,A,c);
-            return D
-        end
-        function scale!{T,S<:Number}(A::$(t2){T}, c::S)
-            D = $(t2)(Array(promote_type(T,S), size(A)...));
-            scale!(D,A,c);
-            return D
+    for (type1, type2) in ([:Real, :Complex], [:Any, :Number])
```
Comment (andreasnoack) [inline base/linalg/triangular.jl]: Why are these different element types necessary?

File: base/linalg/triangular.jl [hunk 2]
```diff
@@ -324,20 +325,21 @@ function scale!{T<:Union{LowerTriangular, UnitLowerTriangular}}(A::LowerTriangul
...
+        @eval begin
+            function scale{T<:$(type1),S<:$(type2)}(A::$(t1){T}, c::S)
```
Comment (andreasnoack) [inline base/linalg/triangular.jl]: I guess this could simply be defined as `scale(A::AbstractTriangular, x::Number)=A*x`. Actually, we should consider if the scale function without exclamation mark makes sense at all. Why not just use `*`? However, that is a discussion for another issue.

File: base/linalg/triangular.jl (hunk 1 above)
Comment (mfasi) [inline base/linalg/triangular.jl]: Because if I don't put the `Real`/`Complex` version I get a few warnings at compile time, pointing out that my methods are ambiguous with the `scale(A,c)` in `generic.jl`
```javascript
WARNING: New definition 
    scale(Base.LinAlg.UnitLowerTriangular{#T<:Any, S<:AbstractArray{T<:Any, 2}}, #S<:Number) at linalg/triangular.jl:337
is ambiguous with: 
    scale(AbstractArray{#R<:Real, N<:Any}, #S<:Base.Complex) at linalg/generic.jl:9.
To fix, define 
    scale(Base.LinAlg.UnitLowerTriangular{_<:Real, S<:AbstractArray{T<:Any, 2}}, #S<:Base.Complex)
before the new definition.
WARNING: New definition 
    scale(#S<:Number, Base.LinAlg.UnitLowerTriangular) at linalg/triangular.jl:341
is ambiguous with: 
    scale(Base.Complex, AbstractArray{#R<:Real, N<:Any}) at linalg/generic.jl:14.
To fix, define 
    scale(_<:Base.Complex, Base.LinAlg.UnitLowerTriangular{#R<:Real, _<:S<:AbstractArray{T<:Any, 2}})
before the new definition.
WARNING: New definition 
    scale(Base.LinAlg.UnitUpperTriangular{#T<:Any, S<:AbstractArray{T<:Any, 2}}, #S<:Number) at linalg/triangular.jl:337
is ambiguous with: 
    scale(AbstractArray{#R<:Real, N<:Any}, #S<:Base.Complex) at linalg/generic.jl:9.
To fix, define 
    scale(Base.LinAlg.UnitUpperTriangular{_<:Real, S<:AbstractArray{T<:Any, 2}}, #S<:Base.Complex)
before the new definition.
WARNING: New definition 
    scale(#S<:Number, Base.LinAlg.UnitUpperTriangular) at linalg/triangular.jl:341
is ambiguous with: 
    scale(Base.Complex, AbstractArray{#R<:Real, N<:Any}) at linalg/generic.jl:14.
To fix, define 
    scale(_<:Base.Complex, Base.LinAlg.UnitUpperTriangular{#R<:Real, _<:S<:AbstractArray{T<:Any, 2}})
before the new definition.
```

File: base/linalg/triangular.jl (hunk 2 above)
Comment (mfasi) [inline base/linalg/triangular.jl]: Yes, I agree, there's no need to define them in such an involved way.  In fact, removing these four methods would break `scale` for two non-exported data types only. This should be safe, since these methods were not implemented at all two days ago.

Comment (andreasnoack) [inline base/linalg/triangular.jl]: Let's just remove them. It is most likely that users will use `*` for non-mutating scaling anyway. Then I think we are ready for merge.

**Comment by mfasi** [comment]
@andreasnoack Thank you, I removed the `scale` method as per your suggestion and updated the test file accordingly.
