### PR TITLE
Faster pow32 and pow16 without the negative number bug

### LINKED ISSUE #40609: Exponentiation of negative single and half precision fails on nightly
```julia

julia> versioninfo()
Julia Version 1.7.0-DEV.1011
Commit 4e176ac965* (2021-04-26 08:26 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8

julia> Float64(-2)^5
-32.0

julia> Float32(-2)^5
ERROR: DomainError with -2.0:
log2 will only return a complex result if called with a complex argument. Try log2(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] _log(x::Float64, base::Val{2}, func::Symbol)
   @ Base.Math ./special/log.jl:304
 [3] log2
   @ ./special/log.jl:268 [inlined]
 [4] ^
   @ ./math.jl:914 [inlined]
 [5] ^
   @ ./math.jl:942 [inlined]
 [6] literal_pow(#unused#::typeof(^), x::Float32, #unused#::Val{5})
   @ Base ./intfuncs.jl:315
 [7] top-level scope
   @ REPL[34]:1

julia> Float16(-2)^5
ERROR: DomainError with -2.0:
log2 will only return a complex result if called with a complex argument. Try log2(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] _log(x::Float64, base::Val{2}, func::Symbol)
   @ Base.Math ./special/log.jl:304
 [3] log2
   @ ./special/log.jl:268 [inlined]
 [4] ^
   @ ./math.jl:914 [inlined]
 [5] ^
   @ ./math.jl:942 [inlined]
 [6] ^
   @ ./math.jl:944 [inlined]
 [7] literal_pow(#unused#::typeof(^), x::Float16, #unused#::Val{5})
   @ Base ./intfuncs.jl:315
 [8] top-level scope
   @ REPL[40]:1
```

### PR DESCRIPTION
**Pull request by oscardssmith**
updated version of https://github.com/JuliaLang/julia/pull/40236 that actually works for negative x. I haven't done performance tests yet to ensure that this doesn't negate the performance benefits. That said, I don't expect it to perform much worse, and the numerical results will be identical.

closes #40609

### CODE REVIEW

**Comment by oscardssmith** [comment]
Also added tests for https://github.com/JuliaLang/julia/issues/40609#issuecomment-827109848

File: base/math.jl [hunk 1]
```diff
@@ -911,13 +911,19 @@ end
...
-        throw_exp_domainerror(x)
-    end
-    z
+    x = Float64(x)
+    x<0 && !isinteger(y) && throw_exp_domainerror(x)
+    ans = Float32(exp2(log2(abs(x))*y))
+    x<0 && isodd(y) && return -ans
+    return ans
+end
+@inline function ^(x::Float32, y::Float32)
```
Comment (dkarrasch) [inline base/math.jl:920]:
```suggestion
@inline function ^(x::Float16, y::Float16)
```
?

**Comment by simeonschaub** [comment]
I think this will still fail for `x = 0`

File: test/math.jl [hunk 2]
```diff
@@ -149,6 +149,8 @@ end
             @test x^y ≈ big(x)^big(y)
             @test x^1 === x
             @test x^yi ≈ big(x)^yi
+            @test (-x)^yi == x^yi
```
Comment (fredrikekre) [inline test/math.jl:152]: `Float16` is not tested in this code path.

**Review by fredrikekre — COMMENTED** [review]
The method bodies are the same? Can define
```
function ^(x::T, y::T) where T <: Uniont{Float16, Float32}
    x = widen(x) # convert Float16/Float32 to Float32/Float64
    # ...
end
```
instead then.

File: base/math.jl [hunk 3]
```diff
@@ -911,13 +911,19 @@ end
...
 @inline function ^(x::Float32, y::Float32)
-    z = ccall("llvm.pow.f32", llvmcall, Float32, (Float32, Float32), x, y)
-    if isnan(z) & !isnan(x+y)
-        throw_exp_domainerror(x)
-    end
-    z
+    x = Float64(x)
+    x<0 && !isinteger(y) && throw_exp_domainerror(x)
+    ans = Float32(exp2(log2(abs(x))*y))
+    x<0 && isodd(y) && return -ans
```
Comment (KristofferC) [inline base/math.jl:917]: Feels like just either

```
if x<0 && isodd(y)
    return -ans
else
    return ans
end
```

or

`return (x<0 && isodd(y)) ? -ans : ans`

is clearer.

**Comment by oscardssmith** [comment]
We definitely need tests for `x==0`. On master, `0.0^(-3.0)==Inf` which is very wrong (acceptable behavior would be domain error or `0.0`).

File: base/math.jl [hunk 4]
```diff
@@ -910,14 +910,13 @@ end
...
     z
 end
-@inline function ^(x::Float32, y::Float32)
-    z = ccall("llvm.pow.f32", llvmcall, Float32, (Float32, Float32), x, y)
-    if isnan(z) & !isnan(x+y)
-        throw_exp_domainerror(x)
-    end
-    z
+@inline function ^(x::T, y::T) where T <: Union{Float16, Float32}
+    x==0 && return T(y==0)
```
Comment (oscardssmith) [inline base/math.jl:914]: What do we want for the following cases?

- 0.0^0.0
- 0.0^-1.0
- 0.0^NaN
I've gone with 1 for 0^0, and otherwise 0., which I think is reasonable.

Comment (simeonschaub) [reply base/math.jl:914]: Looks like this is what we do for `Float64`. As long as it's consistent, this seems fine to me.

Comment (simeonschaub) [reply base/math.jl:914]: Ah, wait. We do have:
```julia
julia> 0.0 ^ NaN
NaN
```
so this should probably be matched.

Comment (oscardssmith) [reply base/math.jl:914]: I'm somewhat unclear about if this is intended given that `0.0^negative` is clearly wrong. It's reasonable behavior, but not the only reasonable behavior.

Comment (oscardssmith) [reply base/math.jl:914]: Also worth noting is that `1.0^NaN` currently gives `1.0`, and `NaN^0.0` gives `1.0`. Having similar behavior for `0.0` seems reasonable.

File: base/math.jl [hunk 5]
```diff
@@ -904,36 +904,36 @@ function modf(x::Float64)
 end
 
 @inline function ^(x::Float64, y::Float64)
+    x==0 && return Float64(y==0)
```
Comment (fredrikekre) [inline base/math.jl:907]:
```suggestion
    x == 0 && return Float64(y == 0)
```

File: base/math.jl [hunk 6]
```diff
@@ -904,36 +904,36 @@ function modf(x::Float64)
...
-    if isnan(z) & !isnan(x+y)
-        throw_exp_domainerror(x)
-    end
-    z
+@inline function ^(x::T, y::T) where T <: Union{Float16, Float32}
+    x==0 && return T(y==0)
+    x = widen(x) # convert Float16/Float32 to Float32/Float64
+    x<0 && !isinteger(y) && throw_exp_domainerror(x)
+    ans = T(exp2(log2(abs(x))*y))
+    return (x<0 && isodd(y)) ? -ans : ans
```
Comment (fredrikekre) [inline base/math.jl:919]:
```suggestion
    x == 0 && return T(y == 0)
    x = widen(x) # convert Float16/Float32 to Float32/Float64
    x < 0 && !isinteger(y) && throw_exp_domainerror(x)
    ans = T(exp2(log2(abs(x)) * y))
    return (x < 0 && isodd(y)) ? -ans : ans
```

File: base/math.jl (hunk 4 above)
Comment (JeffreySarnoff) [reply base/math.jl]: IEEE Std 754-2019 

6.2 Operations with NaNs
Under default exception handling, any operation signaling an invalid operation exception and for which a floating-point result is to be delivered, except as stated otherwise, shall deliver a quiet NaN.

6.2.3 NaN propagation
An operation that propagates a NaN operand to its result and has a single NaN as an input should produce a NaN with the payload of the input NaN if representable in the destination format.

seems to me that `float^NaN should == NaN^float == NaN`

**Comment by JeffreySarnoff** [comment]
the line `if isnan(z) & !isnan(x+y)` should be `if isnan(z) && !isnan(x+y)`

**Comment by oscardssmith** [comment]
That's a line I removed.

**Comment by oscardssmith** [comment]
Assuming my attempt to merge with master worked, I'm planning on merging this soon sans objection.

**Comment by KristofferC** [comment]
FWIW, it is probably a good idea to run PkgEval on PRs like this that changes very low level functions.
