### PR TITLE
Fix GC corruption during NamedTuple instantiation

### LINKED ISSUE #36649: Missing GC root somewhere
We have a missing GC root somewhere, as seen on CI https://build.julialang.org/#/builders/77/builds/1618/steps/8/logs/stdio

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x70532ab4 -- gc_try_setmark at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:1643 [inlined]
gc_mark_scan_obj8 at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:1837 [inlined]
gc_mark_loop at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:2118
in expression starting at loading.jl:1267
gc_try_setmark at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:1643 [inlined]
gc_mark_scan_obj8 at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:1837 [inlined]
gc_mark_loop at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:2118
_jl_gc_collect at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:2903
jl_gc_collect at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:3109
maybe_collect at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:828 [inlined]
jl_gc_pool_alloc at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:1143 [inlined]
jl_gc_alloc_ at /cygdrive/d/buildbot/worker/package_win32/build/src\julia_internal.h:277 [inlined]
jl_gc_alloc at /cygdrive/d/buildbot/worker/package_win32/build/src\gc.c:3151
jl_alloc_svec_uninit at /cygdrive/d/buildbot/worker/package_win32/build/src\simplevector.c:60
inst_datatype_inner at /cygdrive/d/buildbot/worker/package_win32/build/src\jltypes.c:1396
inst_datatype_env at /cygdrive/d/buildbot/worker/package_win32/build/src\jltypes.c:895 [inlined]
inst_datatype_env at /cygdrive/d/buildbot/worker/package_win32/build/src\jltypes.c:899 [inlined]
inst_datatype_env at /cygdrive/d/buildbot/worker/package_win32/build/src\jltypes.c:899 [inlined]
inst_datatype_env at /cygdrive/d/buildbot/worker/package_win32/build/src\jltypes.c:899 [inlined]
```

### PR DESCRIPTION
**Pull request by Keno**
Plus a bonus missing GC root in dead code. Fixes #36649.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: src/jltypes.c [hunk 1]
```diff
@@ -1255,12 +1255,9 @@ static jl_value_t *inst_datatype_inner(jl_datatype_t *dt, jl_svec_t *p, jl_value
...
                     jl_types_equal(pi, tw)) {
-                if (jl_is_vararg_type(iparams[i])) {
-                    tw = jl_wrap_vararg(tw, jl_tparam1(jl_unwrap_unionall(iparams[i])));
-                    JL_GC_PUSH1(&tw);
-                    tw = jl_rewrap_unionall(tw, iparams[i]);
-                    JL_GC_POP();
-                }
+                // This would require some special handling, but is never used at
+                // the moment.
+                assert(!jl_is_vararg_type(pi));
```
Comment (vtjnash) [inline src/jltypes.c:1260]:
```suggestion
                assert(!jl_is_vararg_type(iparams[i]));
```

I think this was even more false than you intended. Though, I expect `cacheable` and non-concrete `Vararg` should be mutually exclusive anyways, so this handling will never be needed.

Comment (Keno) [reply src/jltypes.c:1260]: thanks

**Review by JeffBezanson — APPROVED** [review]
