### PR TITLE
Fix performance of merging Dicts by sizehint!

### LINKED ISSUE #40412: inserting into a large `Dict` becomes extremely slow for certain sizes
I have noticed that inserting into large `Dict`s becomes extremely slow at certain sizes. Consider the following example where I merge two dictionaries with disjoint keys:
```
for n in 4_000_000:10_000:9_000_000
    a = Dict(k => true for k in 1:n)
    b = Dict(-k => true for k in 1:n)
    print("n = $n: ")
    @time mergewith!(*, a, b)
end
```
The output contains:
```
n = 4000000:   0.320012 seconds (12 allocations: 160.001 MiB, 0.74% gc time)
n = 4010000:   0.318491 seconds (12 allocations: 160.001 MiB, 1.20% gc time)
[some lines skipped]
n = 4170000:   0.657388 seconds (12 allocations: 160.001 MiB, 1.36% gc time)
n = 4180000:   0.821303 seconds (12 allocations: 160.001 MiB, 1.03% gc time)
n = 4190000:   1.371666 seconds (12 allocations: 160.001 MiB, 0.65% gc time)
n = 4200000:   7.115236 seconds (12 allocations: 160.001 MiB, 0.12% gc time)
n = 4210000:  22.755990 seconds (12 allocations: 160.001 MiB, 0.04% gc time)
n = 4220000:  41.291562 seconds (12 allocations: 160.001 MiB, 0.02% gc time)
n = 4230000:  59.546199 seconds (12 allocations: 160.001 MiB, 0.02% gc time)
n = 4240000:  86.307720 seconds (12 allocations: 160.001 MiB, 0.01% gc time)
n = 4250000: 108.880615 seconds (12 allocations: 160.001 MiB, 0.01% gc time)
```
The time continues to increase linearly. I didn't wait for the loop to complete, but the situation gets better again when you get close to 5_600_000 elements. A loop counting down gives:
```
n = 5600000:   0.429293 seconds (12 allocations: 320.001 MiB)
n = 5590000:   0.316916 seconds (12 allocations: 160.001 MiB, 2.45% gc time)
n = 5580000:   0.568302 seconds (12 allocations: 160.001 MiB, 1.93% gc time)
n = 5570000:   1.185528 seconds (12 allocations: 160.001 MiB, 5.08% gc time)
n = 5560000:   2.075435 seconds (12 allocations: 160.001 MiB, 2.11% gc time)
n = 5550000:   3.318913 seconds (12 allocations: 160.001 MiB, 0.27% gc time)
n = 5540000:   4.909952 seconds (12 allocations: 160.001 MiB, 0.17% gc time)
n = 5530000:   6.897621 seconds (12 allocations: 160.001 MiB, 0.15% gc time)
n = 5520000:   9.098108 seconds (12 allocations: 160.001 MiB, 0.10% gc time)
n = 5510000:  11.437910 seconds (12 allocations: 160.001 MiB, 0.08% gc time)
n = 5500000:  14.194875 seconds (12 allocations: 160.001 MiB, 0.06% gc time)
```
At twice the previous problematic size, the run time goes up again:
```
n = 8350000:   1.690423 seconds (12 allocations: 320.001 MiB, 1.10% gc time)
n = 8360000:   2.069064 seconds (12 allocations: 320.001 MiB, 0.87% gc time)
n = 8370000:   2.728515 seconds (12 allocations: 320.001 MiB, 0.69% gc time)
n = 8380000:   4.684132 seconds (12 allocations: 320.001 MiB, 0.41% gc time)
n = 8390000:   9.868301 seconds (12 allocations: 320.001 MiB, 0.19% gc time)
n = 8400000:  41.515405 seconds (12 allocations: 320.001 MiB, 0.05% gc time)
n = 8410000:  80.647027 seconds (12 allocations: 320.001 MiB, 0.02% gc time)
n = 8420000: 120.061138 seconds (12 allocations: 320.001 MiB, 0.02% gc time)
```
The problem does not occur if the two dictionaries have identical keys.
The output of `versioninfo()` on my machine is:
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```
With Julia 1.5.3 the same problem occurs. I've also reproduced it on a Linux machine with a different processor (Intel(R) Xeon(R) CPU E5-2430 0 @ 2.20GHz, libLLVM-11.0.1 (ORCJIT, sandybridge)).

### PR DESCRIPTION
**Pull request by petvana**
Fixes #40412. The problem was that the elements were sorted based on the hash. Thus, there are many collisions and long sequences are generated by linear probing, before the automatic resize is triggered. Maybe it would be nice to be more restrictive to the maximum probe length.
https://github.com/JuliaLang/julia/blob/b9b2a3cc01404e019682e75e3c5241f105031511/base/dict.jl#L48-L50

Old

``` julia
julia> for n in 4_100_000:50_000:4_250_000
           a = Dict(k => true for k in 1:n)
           b = Dict(-k => true for k in 1:n)
           print("n = $n: ")
           @time mergewith!(*, a, b)
       end
n = 4100000:   0.285087 seconds (12 allocations: 160.000 MiB, 8.77% gc time)
n = 4150000:   0.311986 seconds (12 allocations: 160.000 MiB, 5.29% gc time)
n = 4200000:   2.375610 seconds (12 allocations: 160.000 MiB)
n = 4250000:  32.344895 seconds (12 allocations: 160.000 MiB)

julia> for n in 4_100_000:50_000:4_250_000
           a = Dict(k => true for k in 1:n)
           b = Dict(-k => true for k in 1:n)
           print("n = $n: ")
           @time merge(a, b)
       end
n = 4100000:   0.313683 seconds (39.77 k allocations: 242.227 MiB, 8.03% compilation time)
n = 4150000:   0.313875 seconds (19 allocations: 240.001 MiB)
n = 4200000:   2.397114 seconds (19 allocations: 240.001 MiB, 0.21% gc time)
n = 4250000:  30.312298 seconds (19 allocations: 240.001 MiB, 0.05% gc time)
```

PR

``` julia
julia> for n in 4_100_000:50_000:4_250_000
           a = Dict(k => true for k in 1:n)
           b = Dict(-k => true for k in 1:n)
           print("n = $n: ")
           @time mergewith!(*, a, b)
       end
n = 4100000:   0.244038 seconds (42.62 k allocations: 162.201 MiB, 4.46% gc time, 10.62% compilation time)
n = 4150000:   0.257953 seconds (12 allocations: 160.000 MiB, 21.66% gc time)
n = 4200000:   0.207655 seconds (12 allocations: 160.000 MiB, 2.12% gc time)
n = 4250000:   0.208645 seconds (12 allocations: 160.000 MiB, 3.58% gc time)

julia> for n in 4_100_000:50_000:4_250_000
           a = Dict(k => true for k in 1:n)
           b = Dict(-k => true for k in 1:n)
           print("n = $n: ")
           @time merge(a, b)
       end
n = 4100000:   0.282340 seconds (102.46 k allocations: 245.687 MiB, 6.91% gc time, 11.79% compilation time)
n = 4150000:   0.232964 seconds (19 allocations: 240.001 MiB)
n = 4200000:   0.229429 seconds (19 allocations: 240.001 MiB)
n = 4250000:   0.224806 seconds (19 allocations: 240.001 MiB)
```

### CODE REVIEW

File: base/abstractdict.jl [hunk 1]
```diff
@@ -217,6 +217,7 @@ Dict{Int64, Int64} with 3 entries:
 """
 function merge!(d::AbstractDict, others::AbstractDict...)
     for other in others
+        sizehint!(d, length(d) + length(other))
```
Comment (simeonschaub) [inline base/abstractdict.jl:220]: Could we just do `sizehint!(d, sum(length, other; init=0))` once upfront? Also, do we generally assume that `AbstractDict`s define `length`? Otherwise we'd need to check `Base.IteratorSize` frst.

Comment (petvana) [reply base/abstractdict.jl]: My first idea was also to use `sum`. However, merging N Dicts would allocate (N-1)-times more memory than necessary in the worst case when keys are not unique. (This PR only 1-times more).

Not sure, if `AbstractDict` has `length`. Didn't find anything in docs. So, I've added a check inspired by:
https://github.com/JuliaLang/julia/blob/a761cc0b82f88838eb31b29e7387cea35a0cab30/base/abstractset.jl#L102

Comment (simeonschaub) [reply base/abstractdict.jl]: Ah, that makes sense!

**Comment by petvana** [comment]
Not sure if news is needed here. I'd think this is a kind of bugfix with no new functionality. The only change is that it more likely triggers resizing.

File: base/abstractdict.jl [hunk 2]
```diff
@@ -217,6 +217,7 @@ Dict{Int64, Int64} with 3 entries:
 """
 function merge!(d::AbstractDict, others::AbstractDict...)
     for other in others
+        haslength(other) && sizehint!(d, length(d) + length(other))
```
Comment (vtjnash) [inline base/abstractdict.jl:220]: Why does d be assumed to haslength, but not other, despite being the same type? Is it because it is mutable?

Comment (petvana) [reply base/abstractdict.jl:220]: No, just embarrassing. I've added the check in #44687.
