### PR TITLE
inference: handle `Vararg` in `abstract_call_unionall` for `argtypes` computed by `abstract_apply`

### LINKED ISSUE #51310: Method error during ⊑(::ConstsLattice)
Reduced example:

```julia
(a(() = b{c} = d...) = 0)()
```

```
Internal error: encountered unexpected error in runtime:
MethodError(f=Core.Compiler.:(⊑), args=(Core.Compiler.JLTypeLattice(), Vararg{Any}, Type), world=0x00000000000015a5)
jl_method_error_bare at /cache/build/default-amdci5-3/julialang/julia-release-1-dot-10/src/gf.c:2203
jl_method_error at /cache/build/default-amdci5-3/julialang/julia-release-1-dot-10/src/gf.c:2221
jl_lookup_generic_ at /cache/build/default-amdci5-3/julialang/julia-release-1-dot-10/src/gf.c:3052 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-3/julialang/julia-release-1-dot-10/src/gf.c:3067
⊑ at ./compiler/typelattice.jl:530
⊑ at ./compiler/typelattice.jl:508
⊑ at ./compiler/typelattice.jl:432 [inlined]
⊑ at ./compiler/typelattice.jl:397
#347 at ./compiler/abstractlattice.jl:288 [inlined]
abstract_call_unionall at ./compiler/abstractinterpretation.jl:1877
abstract_call_known at ./compiler/abstractinterpretation.jl:2031
abstract_call at ./compiler/abstractinterpretation.jl:2154
abstract_apply at ./compiler/abstractinterpretation.jl:1608
abstract_call_known at ./compiler/abstractinterpretation.jl:1989
abstract_call at ./compiler/abstractinterpretation.jl:2154
abstract_call at ./compiler/abstractinterpretation.jl:2147
abstract_call at ./compiler/abstractinterpretation.jl:2331
abstract_eval_call at ./compiler/abstractinterpretation.jl:2347
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2357
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2601
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2890
typeinf_local at ./compiler/abstractinterpretation.jl:3075
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3163
_typeinf at ./compiler/typeinfer.jl:247
typeinf at ./compiler/typeinfer.jl:216
```

Bisected to #48063 (cc @Keno @aviatesk), so technically 1.10-only, but doesn't seem worth putting on the milestone.

### PR DESCRIPTION
**Pull request by aviatesk**
This commit adds special handling for `Vararg` types that may appear at the end of `argtypes`, as computed by `abstract_apply`. Even though PR #42583 has ensured that `Vararg` and `TypeVar` should never appear within the abstract state, they can still be part of `argtypes`. As a result, this kind of special handling is still necessary. It remains an open question whether we can refactor `abstract_apply` to prevent `Vararg`s from appearing in `argtypes` in the first place.

### CODE REVIEW

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -1858,7 +1858,7 @@ function abstract_call_unionall(interp::AbstractInterpreter, argtypes::Vector{An
         a2 = argtypes[2]
         a3 = argtypes[3]
         ⊑ᵢ = ⊑(typeinf_lattice(interp))
-        nothrow = a2 ⊑ᵢ TypeVar && (a3 ⊑ᵢ Type || a3 ⊑ᵢ TypeVar)
+        nothrow = (!isvarargtype(a2) && a2 ⊑ᵢ TypeVar) && (!isvarargtype(a3) && (a3 ⊑ᵢ Type || a3 ⊑ᵢ TypeVar))
```
Comment (Keno) [inline base/compiler/abstractinterpretation.jl:1861]: `a2` can't be vararg, since it's not the last argtype. If it's vararg, we can never prove nothrow, but maybe still unwrap `a3` afterwards in case we can say something about the type?

Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:1861]: Ah right, `abstract_apply` truncates the first `Vararg` to ensure that `Vararg` only appears at the last argument: https://github.com/JuliaLang/julia/blob/7f37e709d36891b0ef263051c3df3b3529569f93/base/compiler/abstractinterpretation.jl#L1580-L1592

**Comment by aviatesk** [comment]
fix #51310

**Review by Keno — APPROVED** [review]

File: base/compiler/abstractinterpretation.jl [hunk 2]
```diff
@@ -1858,7 +1858,12 @@ function abstract_call_unionall(interp::AbstractInterpreter, argtypes::Vector{An
         a2 = argtypes[2]
         a3 = argtypes[3]
         ⊑ᵢ = ⊑(typeinf_lattice(interp))
-        nothrow = a2 ⊑ᵢ TypeVar && (a3 ⊑ᵢ Type || a3 ⊑ᵢ TypeVar)
+        if isvarargtype(a3)
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl:1861]: The `length(argtypes)` check is not correct either if you have varargs

Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:1861]: Yeah, but what we are trying to model here is call to the `UnionAll(tv, t)` method, which just throws `MethodError` when `length(argtypes) ≠ 3` at runtime. So this is fine as far as we model `nothrow` correctly.

Comment (vtjnash) [reply base/compiler/abstractinterpretation.jl:1861]: When you have Vararg, you don’t know if length!=3, so you don’t know that if it throws an error or not

Comment (Keno) [reply base/compiler/abstractinterpretation.jl:1861]: Yes, we can't concluded that the rt is `Bottom` if either of the first two argtypes is `Vararg`, we should fix that.

Comment (aviatesk) [reply base/compiler/abstractinterpretation.jl:1861]: Ah, right... I will work on it.
