### PR TITLE
introduce IOContext and ImmutableDict to fix some of show, print, & friends

### LINKED ISSUE #10327: Can we have print_color and println_color?
Title says it all really. We currently have just `print_with_color` which is verbose and almost every time I've used it I've wanted to have a new line. Hence my "request". I will even invest the 10 hours required myself to make the PR ;)

### LINKED ISSUE #11364: Should code_warntype integrate with the writemime system?
Right now the output of code_warntype won't have red highlighting in IJulia (https://github.com/JuliaLang/IJulia.jl/issues/310), rendering it fairly pointless. Maybe we could change it so it outputs HTML/markdown.

### PR DESCRIPTION
**Pull request by vtjnash**
This is a small PR is intended to provide a general framework to address quite a few of the broader issues with show, print, & friends.

The specific implementation details is that this is an immutable dictionary that is a subclass of IO (so it can be used anywhere an IO object can be used), where the dictionary allows a display function to pass along arbitrary metadata to arbitrary other parts of the printing infrastructure.

As proof-of-concept examples, the PR replaces the existing global or TLS shown_set, limit_output, type-emphasis, with a simple IO-local mechanism, plus it provides a way to add a lock to any IO object.

Just a quick search nets the following list of existing issues for reference:

solves #5709 "Show, showcompact, showall, showlimited, print, repr, summary, and friends"
addresses #7959 "proposed cleanup of output functions"
mostly implements #10794 "Show of parameterized methods" (replacing PR #10861)
provides a mechanism for addressing #6117 "array display is a mess"
alternative/complement to PR #8987 "WIP: cleanup of output functions"
addresses #10009 Overload `print` for Markdown Strings
fixes #11364 integrate code_warntype with the output system
fixes #10327 print_color and println_color

additionally, cross-ref with:
PR #12929 showcompact(::RefValue) prints the contained object compactly
#6921 Pager support in the repl

PR #13256 Wrapper to annotate the MIME type of some data

Inspired by https://groups.google.com/forum/#!topic/julia-dev/uKPxXCQCU_A

TODO:
- [x] docs
- [x] remove special case for limit_output (upon review, there's no real value in it)
- [x] allow constructing `IOContext(::IO, ::IOContext)`
- [x] finish #10794 by hiding typevars that aren't in tvar_env if tvar_env is present
-  ~~integrate MIME printing (e.g. #8987)~~
- [x] integrate tty_rows / tty_cols into IOContext (#4117, also #5709)
- ~~make `:formatting => :ansi` another valid option~~
- [x] integrate array printing options (deal with #6117)
- [x] squash commit history
- [x] split immutable dict implementation out of IOContext into it's own type

### CODE REVIEW

**Comment by vtjnash** [comment]
for a usage example take a look at the implementation of tvar_env https://github.com/JuliaLang/julia/commit/11a5c37c52b58bde7321cad8002946d74496a634#diff-b4267643a238b5a375b3e055817ee6caR833 or typeemphasize. once the IOContext implementation is in place, the addition of each of these is accomplished in a small amount of code.

**Comment by StefanKarpinski** [comment]
Did I miss you explaining the high-level idea of IOContext somewhere?

**Comment by vtjnash** [comment]
there's not really much to explain, so I wasn't sure what to write. the problem in all of the IO issues above is that the show methods want to customize the output based on some property known only to the caller, but there was no way to pass that information into the callee -- other than TLS variables. IOContext is unlike any other IO object (well, except maybe Process), in that it is does not actually reflect a type of IO stream, but instead can be used to convey context about how the IO stream should be used (or ignored as used as a generic stream).

**Comment by StefanKarpinski** [comment]
Start with "what is an IO context?". Move on to "why do we need them?" Probably want to include "what problems do they solve?"

**Comment by vtjnash** [comment]
> what is an IO context?

an immutable Dictionary that is a subclass of IO. or alternatively, keyword arguments for all IO functions

> why do we need them?

the existing problems in the show/print hierarchy (ref #5709) are generally of the form that the caller only can provide two arguments: what to print and where to print. but the caller often wants to include a third consideration: how to print (limited, recursive, types-emphasized, typevars ignored, mime formatting).

> what problems do they solve?

this PR provides a mechanism to essentially add keyword arguments to every function ever written for IO, without changing a single line of existing code (by transparently reusing the existing IO argument)

File: base/show.jl [hunk 1]
```diff
@@ -1,9 +1,60 @@
...
+show(io::IO, ctx::IOContext) = (print(io, "IOContext("); show(io, ctx.io); print(io, ")"))
+
+pipe_reader(io::IOContext) = io.io
+pipe_writer(io::IOContext) = io.io
+lock(io::IOContext) = (lock(io.io); lock(io.lock)) # double lock, because IO itself might not be lockable
+unlock(io::IOContext) = (unlock(io.io); unlock(io.lock))
+
+limit_output(::ANY) = false
+limit_output(io::IOContext) = io.limit_output
+function in{I<:IOContext}(value, io_key::Pair{I})
```
Comment (JeffBezanson) [inline base/show.jl]: I find this notation really confusing. Normally we'd have `(key=>val) in dict`, and this rearranges it to `val in (dict=>key)`. There can be no good reason for that.

File: base/show.jl [hunk 2]
```diff
@@ -1,9 +1,60 @@
...
+        new(io.io, io.lock, io.limit_output, true, first(KV), last(KV), io)
+end
+IOContext(io::IO, arg=false) = IOContext{typeof(io)}(io, arg)
+IOContext(io::IOContext, arg=io.limit_output) = typeof(io)(io, arg)
+IOContext(io::IOContext, key, value) = typeof(io)(io, Pair{Any, Any}(key, value))
+show(io::IO, ctx::IOContext) = (print(io, "IOContext("); show(io, ctx.io); print(io, ")"))
+
+pipe_reader(io::IOContext) = io.io
+pipe_writer(io::IOContext) = io.io
+lock(io::IOContext) = (lock(io.io); lock(io.lock)) # double lock, because IO itself might not be lockable
```
Comment (JeffBezanson) [inline base/show.jl]: I don't understand the need for the extra layer of locking.

Comment (vtjnash) [inline base/show.jl]: there isn't an extra layer. it is unknown if the IO object that the IOContext is wrapping has a lock, so IOContext brings it own to ensure that there is at least one lock

File: base/show.jl (hunk 1 above)
Comment (vtjnash) [inline base/show.jl]: good point. this was holdover from an earlier, more convoluted design iteration. this can be switched now in a future rev of the PR.

File: base/show.jl (hunk 2 above)
Comment (JeffBezanson) [inline base/show.jl]: I guess my question then is, why does IOContext need to ensure that there is at least one lock?

Comment (vtjnash) [inline base/show.jl]: ah, that's a different question: it was part of the RFC / proof-of-concept

Comment (vtjnash) [inline base/show.jl]: what are the pros and cons of providing this lock?

**Comment by vtjnash** [comment]
bump. i completed the implementation of this proposal over the weekend and would appreciate review.

**Comment by IainNZ** [comment]
I haven't reviewed the first few commits, but I've looked at some the rest, and it definitely looks like a good idea. Elimination of those `showcompact`s is very nice

**Comment by vtjnash** [comment]
this now has tests and the actions items i had are closed. (this does not yet implement any of the changes discussed in #14052 as those were largely independent)

**Comment by tkelman** [comment]
ImmutableDict should be a separate PR.

**Comment by vtjnash** [comment]
counterpoint: it has near zero value without this PR (e.g. i wouldn't want to add it to base unless this PR also simultaneously got merged -- hence one PR)

**Comment by tkelman** [comment]
Then how much value does it have within this PR? Is it really necessary?

**Comment by vtjnash** [comment]
it is an implementation detail for IOContext

**Comment by timholy** [comment]
This is very nice, thanks for doing this.

Looks like [these](https://github.com/JuliaLang/julia/blob/6d7a50b880fe2189b1efa34eb47d4dfeb181b674/base/show.jl#L1020) [`with_output_lim`](https://github.com/JuliaLang/julia/blob/6d7a50b880fe2189b1efa34eb47d4dfeb181b674/base/show.jl#L1032) got missed, though. (We could use some more `dump` tests, obviously.)

**Comment by timholy** [comment]
See also #14533.

**Comment by JeffBezanson** [comment]
I would rename `iosize`. That name sounds like it might involve a size in bytes. It should clarify that it refers to the size of a terminal window, maybe `terminalsize`.

We also need to figure out a better way to deal with properties like `limit_output`. After all, we wanted to *reduce* the number of printing-related exports. We don't want a new export for every io property, nor do we want only *some* properties to have their own top-level functions. Though if I have to pick, the second one is worse since it makes the API less predictable.

**Comment by vtjnash** [comment]
maybe `displaysize`, since it is expected to be primarily used with `display`?

if we don't want more exports, it's hard to get more concise than just using the definition everywhere:
`limit_output(io::IO) = (get(io, :limit_output, false) === true)`

i'm not opposed to that. the named function version was a bit of an experiment in transitioning, but i didn't find it to be any more usable

**Comment by tkelman** [comment]
+1 for not exporting display-properly-checker functions

**Comment by JeffBezanson** [comment]
`displaysize` sounds good.

File: base/dict.jl [hunk 3]
```diff
@@ -258,12 +267,13 @@ function isequal(l::Associative, r::Associative)
...
 function ==(l::Associative, r::Associative)
+    l === r && return true
     if isa(l,ObjectIdDict) != isa(r,ObjectIdDict)
         return false
     end
     if length(l) != length(r) return false end
-    for (key, value) in l
-        if value != get(r, key, secret_table_token)
+    for pair in l
+        if !in(pair, r, ==)
```
Comment (yuyichao) [inline base/dict.jl]: Hmm, this change (together with the type constraint in the `in` above) makes custom `Associative`s that doesn't define their own `==` and return tuples in their iterator to raise method error in comparison. Is this intended? @vtjnash 

This causes a test failure in PyCall. c.c. @stevengj

Comment (vtjnash) [inline base/dict.jl]: the type constraint is due to the expectation that an Associative only contains Pairs (e.g. see the error message you get if you look for something else: https://github.com/JuliaLang/julia/pull/13825/files#diff-d4736682004c1996e5d9b1c5c33c8c8eR28)

**Comment by nalimilan** [comment]
@vtjnash The `displaysize()` method without any arguments is undocumented. Since it's based on `ENV` and doesn't seem react to changes in the terminal window size, what's it's purpose? How could we describe it in the docs?

**Comment by nalimilan** [comment]
@vtjnash Bump? Could you explain the purpose of `displaysize` in a few words? I can't fix the docs myself without this information.

**Comment by vtjnash** [comment]
i generally considered it internal in that you shouldn't need to call it unless you are implementing a new display. it returns a generic size suitable for use by IO streams that couldn't compute the actual size

**Comment by nalimilan** [comment]
Either it should be documented, or it should be another (unexported) function. The risk here is that people porting from the deprecated `tty_size()` will use `displaysize()` without any argument because it's similar. Which of the two solutions would you prefer?

**Comment by hayd** [comment]
Should ImmutableDict be exported/documented? It feels like it could be useful for defining a FrozenSet/FrozenDict in DataStructures.
