### PR TITLE
Make `StepRangeLen` in operations which may produce zero step

### LINKED ISSUE #10391: Subtracting a range from another range with the same step
I'm not sure if there's anything we can do about this, but this throws an error:

``` julia
julia> (1:2) - (1:2)
ERROR: ArgumentError: step cannot be zero
 in steprange_last at ./range.jl:47
 in - at operators.jl:331
```

This can break code that expects that any two `AbstractVector{T<:Number}`s of the same length can be subtracted from each other.

### LINKED ISSUE #40317: Broadcasting and zero-step ranges
```julia
julia> 0 .* collect(1:3) .+ (1:4)'
3×4 Matrix{Int64}:
 1  2  3  4
 1  2  3  4
 1  2  3  4

julia> 0 .* (1:3) .+ (1:4)'
ERROR: ArgumentError: step cannot be zero
```
This fails because it eagerly evaluates `0 .* (1:3)` without waiting to see the rest of the broadcast:

https://github.com/JuliaLang/julia/blob/b7b0a634d8fab9e94dec7177b3853c3c46e3e7dd/base/broadcast.jl#L1141

However, it works fine for floating point ranges:
```julia
julia> 0 .* (1:1.0:3) .+ (1:4)'
3×4 Matrix{Float64}:
 1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0

julia> 0 .* (1:1.0:3)  # not great printing, BTW!
0.0:0.0:0.0

julia> typeof(ans)
StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}
```
To fix this, if `broadcasted` is still going to return a range, then perhaps `2 .* (1:3)` needs to return `StepRangeLen(2,2,3)`. 

Xref #15218 about zero step, pre-1.0.

### PR DESCRIPTION
**Pull request by mcabbott**
This allows calculations with integer ranges leading to zero step to work:
```julia
julia> 0 * (1:3)
StepRangeLen(0, 0, 3)

julia> (1:3) - (1:3)
StepRangeLen(0, 0, 3)

julia> exp.(ans)
3-element Vector{Float64}:
 1.0
 1.0
 1.0
```
Will this have awful side effects elsewhere?

Note that it does not change how `range` behaves, nor allow you to enter `1:0:1`. Many floating point ranges already use `StepRangeLen` and hence already allow zero step, it does change their printing to something which parses:
```julia 
julia> range(1, 5, step=2) |> typeof
StepRange{Int64, Int64}

 julia> 0 * (1:2.0:10)
StepRangeLen(0.0, 0.0, 5)
```
Closes #40317. Closes #10391.

### CODE REVIEW

File: base/range.jl [hunk 1]
```diff
@@ -1258,7 +1264,8 @@ function _define_range_op(@nospecialize f)
             r1l = length(r1)
             (r1l == length(r2) ||
              throw(DimensionMismatch("argument dimensions must match: length of r1 is $r1l, length of r2 is $(length(r2))")))
-            range($f(first(r1), first(r2)), step=$f(step(r1), step(r2)), length=r1l)
+            # range($f(first(r1), first(r2)), step=$f(step(r1), step(r2)), length=r1l)
```
Comment (vtjnash) [inline base/range.jl:1267]:
```suggestion
```

**Review by vtjnash — APPROVED** [review]

**Comment by simeonschaub** [comment]
Would it be good to run PkgEval here? I could imagine that some people are implicitly relying on these returning a `StepRange`.

**Comment by simeonschaub** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/40320#issuecomment-812895924):
```
NanosoldierError: failed to run tests: TaskFailedException:
failed process: Process(`docker stop ExportAll-WED15I1v`, ProcessExited(1)) [1]

pipeline_error at ./process.jl:525 [inlined]
#run#596 at ./process.jl:440
run at ./process.jl:438 [inlined]
kill_container at /storage/pkgeval/dev/PkgEval/src/run.jl:364 [inlined]
stop at /storage/pkgeval/dev/PkgEval/src/run.jl:167 [inlined]
#36 at /storage/pkgeval/dev/PkgEval/src/run.jl:234 [inlined]
lock at ./lock.jl:161
macro expansion at /storage/pkgeval/dev/PkgEval/src/run.jl:231 [inlined]
#35 at ./task.jl:356
wait at ./task.jl:267 [inlined]
fetch at ./task.jl:282 [inlined]
#run_sandboxed_test#30 at /storage/pkgeval/dev/PkgEval/src/run.jl:258
macro expansion at /storage/pkgeval/dev/PkgEval/src/run.jl:584 [inlined]
#50 at ./task.jl:356
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/529beb2_vs_ad513ca/report.md)
cc @maleadt

**Comment by maleadt** [comment]
Docker hiccup. Let's try again:

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40320#issuecomment-813003388) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/529beb2_vs_0596d51/report.md). cc @maleadt

**Comment by simeonschaub** [comment]
The failures look mostly real.

The AbstractFFT failures are interesting, since it looks like this change introduced some numerical instabilities with operations involving floating points with integer ranges. Could we perhaps promote to `TwicePrecision` if a `StepRange` is multiplied by a float? 

InfiniteArrays would be good to look into as well, but I am guessing it wouldn't be too hard to fix the breakage on their side.

The others mostly look like their tests are just a little to strict and explicitly test the type of a range, so I don't think we need to worry too much about those.

**Comment by mcabbott** [comment]
I think I fixed the AbstractFFTs test, which was producing this:
```
julia> using AbstractFFTs

julia> x = fftfreq(5);

julia> fftshift(fftfreq(5)) |> collect
5-element Vector{Float64}:
 -0.4
 -0.2
  0.0
  0.20000000000000007
  0.4

julia> (x.n_nonnegative-x.n:x.n_nonnegative-1)
-2:2

julia> (x.n_nonnegative-x.n:x.n_nonnegative-1)*x.multiplier
-0.4:0.2:0.4

julia> typeof(ans)
StepRangeLen{Float64, Float64, Float64}

# My fix
julia> @eval Base.Broadcast broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::AbstractRange, x::AbstractFloat) = Base.range_start_step_length(first(r)*x, step(r)*x, length(r))

julia> (x.n_nonnegative-x.n:x.n_nonnegative-1)*x.multiplier |> typeof
StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}
```
But now there are other problems... hope nobody is in a rush.

**Comment by simeonschaub** [comment]
Any news on this? Not in a rush, but it would be nice to get this into 1.7, since it could be argued that this is really a bugfix. Let me know if there's anything I can help with.

File: base/broadcast.jl [hunk 2]
```diff
@@ -1153,15 +1153,15 @@ broadcasted(::DefaultArrayStyle{1}, ::typeof(-), r::LinRange, x::Number) = LinRa
...
-# separate in case of noncommutative multiplication
-broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::AbstractRange, x::Number) = range(first(r)*x, step=step(r)*x, length=length(r))
-broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::StepRangeLen{T}, x::Number) where {T} =
-    StepRangeLen{typeof(T(r.ref)*x)}(r.ref*x, r.step*x, length(r), r.offset)
+broadcasted(::DefaultArrayStyle{1}, ::typeof(*), x::AbstractFloat, r::OrdinalRange{<:Integer}) = Base.range_start_step_length(x*first(r), x, length(r))
+# separate in case of noncommutative multiplication:
+broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::AbstractRange, x::Number) = StepRangeLen(first(r)*x, step(r)*x, length(r))
+broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::StepRangeLen{T}, x::Number) where {T} = StepRangeLen{typeof(T(r.ref)*x)}(r.ref*x, r.step*x, length(r), r.offset)
 broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::LinRange, x::Number) = LinRange(r.start * x, r.stop * x, r.len)
+broadcasted(::DefaultArrayStyle{1}, ::typeof(*), r::OrdinalRange{<:Integer}, x::AbstractFloat) = Base.range_start_step_length(first(r)*x, x, length(r))
```
Comment (mcabbott) [inline base/broadcast.jl:1164]: The last method here handles the case needed for AbstractFFTs tests, above, of float * UnitRange -> range with twiceprecision. 

And `(-2:2) * 0.0` works because for floats `range_start_step_length` does sometimes allow zero step:
```
julia> Base.range_start_step_length(1.0, 0, 5)
StepRangeLen(1.0, 0.0, 5)

julia> Base.range_start_step_length(1, 0, 5)  # goes to 1st method not 4th
ERROR: ArgumentError: step cannot be zero
```
But probably it could just be `OrdinalRange`. Are there other weird cases we should think about?

Comment (simeonschaub) [reply base/broadcast.jl:1164]: I wonder whether `Base.range_start_step_length(1, 0, 5)` should just return a `StepRangeLen`. Do you expect that to be too breaking?

Comment (mcabbott) [reply base/broadcast.jl:1164]: I haven't thought about it. Was hoping to change as little as possible, focused on calculations that may produce zero step, rather than constructors. 

This one is called by `range(1, step=0, length=10)` which would otherwise make an integer StepRange. Whereas `range(1, 1, length=10)` works, and makes a floating point range. It is a bit weird that some constructors work and some don't, but this isn't changed here.

Comment (simeonschaub) [reply base/broadcast.jl]: Agree, it's probably better not to change this behavior in this PR. Could you just add a short comment here explaining why we can't use `range_start_step_length`?

Comment (mcabbott) [reply base/broadcast.jl]: Sure, see what you think of https://github.com/JuliaLang/julia/pull/40320/commits/56d9c27b617c5c9bb4b2fa720ffa3d9b0434e5a9

Comment (simeonschaub) [reply base/broadcast.jl]: Looks good! Let's run PkgEval one more time once tests pass, but otherwise this should be good to go.

File: base/range.jl [hunk 3]
```diff
@@ -924,9 +924,15 @@ function getindex(r::LinRange{T}, s::OrdinalRange{S}) where {T, S<:Integer}
...
-show(io::IO, r::AbstractRange) = print(io, repr(first(r)), ':', repr(step(r)), ':', repr(last(r)))
 show(io::IO, r::UnitRange) = print(io, repr(first(r)), ':', repr(last(r)))
 show(io::IO, r::OneTo) = print(io, "Base.OneTo(", r.stop, ")")
+function show(io::IO, r::AbstractRange)
+    if step(r) != 0
+        print(io, repr(first(r)), ':', repr(step(r)), ':', repr(last(r)))
+    else
+        print(io, "StepRangeLen(", repr(first(r)), ", ", repr(step(r)), ", ", repr(length(r)), ")")
+    end
+end
```
[the remark this answers is not in the document]
Comment (mcabbott) [reply base/range.jl:935]: It's ugly to print what seems like an internal detail, but it feels wrong to leave it printing `0:0:0` if we support the use of such ranges, more than by accident. Perhaps it can become something prettier like `range(1, step=0, length=3)` in another PR?

[the remark this answers is not in the document]
Comment (simeonschaub) [reply base/range.jl:935]: > Perhaps it can become something prettier like range(1, step=0, length=3) in another PR?

Yeah, that was my thinking. Since it is not directly related to this PR, I would prefer not to change this here.

[the remark this answers is not in the document]
Comment (mcabbott) [reply base/range.jl:935]: But what harm in printing something for now? It's only the zero step case. Maybe someone's doctests want that `range(1.0, step=0, length=4)` prints `1.0:0.0:1.0` and you'd rather not break them twice?

[the remark this answers is not in the document]
Comment (simeonschaub) [reply base/range.jl:935]: It seems confusing to have this as a fallback for all `AbstractRange`s, since people may define their own ranges with zero step. Perhaps it would be ok to just print `StepRangeLen` this way?

[the remark this answers is not in the document]
Comment (mcabbott) [reply base/range.jl]: OK, that will work, I've restricted it to StepRangeLen.

**Comment by simeonschaub** [comment]
@nanosoldier `runtests(["AbstractFFTs", "ArrayLayouts", "BlockArrays", "CUTEst", "Cambrian", "CustomUnitRanges", "DimensionalData", "Hecke", "IdentityRanges", "ImageDistances", "InfiniteArrays", "InverseLaplace", "LoopThrottle", "ProximalAlgorithms"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40320#issuecomment-830363986) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/15d226b_vs_d7c6a9b/report.md). cc @maleadt

**Comment by simeonschaub** [comment]
> IdentityRanges:
> 
> ```
> Test Failed at /home/pkgeval/.julia/packages/IdentityRanges/liKDH/test/runtests.jl:3
>   Expression: isempty(detect_ambiguities(IdentityRanges, Base, Core))
>    Evaluated: isempty(Tuple{Method, Method}[(broadcasted(::Base.Broadcast.DefaultArrayStyle{1}, ::typeof(*), x::Number, r::IdentityRange) in IdentityRanges at /home/pkgeval/.julia/packages/IdentityRanges/liKDH/src/IdentityRanges.jl:139, broadcasted(::Base.Broadcast.DefaultArrayStyle{1}, ::typeof(*), x::AbstractFloat, r::OrdinalRange) in Base.Broadcast at broadcast.jl:1161), (broadcasted(::Base.Broadcast.DefaultArrayStyle{1}, ::typeof(*), r::IdentityRange, x::Number) in IdentityRanges at /home/pkgeval/.julia/packages/IdentityRanges/liKDH/src/IdentityRanges.jl:138, broadcasted(::Base.Broadcast.DefaultArrayStyle{1}, ::typeof(*), r::OrdinalRange, x::AbstractFloat) in Base.Broadcast at broadcast.jl:1168)])
> ```
> 
> That ambiguity might be avoided if you modified `range_start_step_length` instead.

That should be easily fixable on IdentityRanges' side, so I am not too worried about that.

> BlockArrays:
> 
> ```
> Special broadcast: Test Failed at /home/pkgeval/.julia/packages/BlockArrays/aLe8n/test/test_blockbroadcast.jl:114
>   Expression: broadcast(*, 2, v) isa BlockVector{Int, Vector{StepRange{Int, Int}}}
>    Evaluated: [2, 4, 6, 8, 10, 12, 14] isa BlockVector{Int64, Vector{StepRange{Int64, Int64}}}
> ```
> 
> Maybe that's roughly like `===`, something isn't giving a StepRange anymore.

Yeah, it's just explicitly testing the type, so that should be fine as well.

**Review by simeonschaub — APPROVED** [review]

**Comment by mcabbott** [comment]
Pre-1.7 bump?

**Comment by simeonschaub** [comment]
Just realized that it might also be good to have a news entry for this, would you mind adding one? Otherwise will merge later if there are no objections.

**Comment by mcabbott** [comment]
Sure. I added something, perhaps too verbose?

**Comment by simeonschaub** [comment]
No, looks good.
