### PR TITLE
Some fixes in Distributed 

### LINKED ISSUE #21630: addprocs fails when port is specified
```
julia> addprocs(["host:22"])
exception launching on machine host:22 : MethodError(isinteger, ("22",), 0x00000000000054ee)
0-element Array{Int64,1}

julia> versioninfo()
Julia Version 0.6.0-pre.beta.383
Commit 471c4cda48 (2017-04-27 16:49 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libgfortblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

The reason seems to be a function call `isinteger(portstr)`, where `isinteger` does not have a method for strings. The author probably meant to call `isdigit(portstr)`.

https://github.com/JuliaLang/julia/blob/master/base/distributed/managers.jl#L170

### PR DESCRIPTION
**Pull request by amitmurthy**
- Fix bug in parsing port number from host spec. Closes #21630
- Fix wrong error message with ssh addprocs tunnel option (Discovered on Discourse - https://discourse.julialang.org/t/addprocs-remote-does-not-work-but-ssh-remote-julia-version-does-why/3400/10)
- SSHManager now supports keyword arg exename as a Cmd type. Discovered issue while working on https://github.com/JuliaLang/julia/pull/21652#discussion_r114075816

### CODE REVIEW

File: test/distributed_exec.jl [hunk 1]
```diff
@@ -950,7 +949,10 @@ if is_unix() # aka have ssh
     end
 
     print("\n\nTesting SSHManager. A minimum of 4GB of RAM is recommended.\n")
-    print("Please ensure sshd is running locally with passwordless login enabled.\n")
+    print("Please ensure: \n")
+    print("1) sshd is running locally with passwordless login enabled.\n")
+    print("2) Env variable USER is defined and is the ssh user.\n")
```
Comment (ararslan) [inline test/distributed_exec.jl]: I'd either spell out "environment" here or use all caps to make it clear that it corresponds to the Julia `ENV` variable. (Also these can all be `println` rather than `print(..., "\n")`.)

File: base/distributed/managers.jl [hunk 2]
```diff
@@ -167,7 +167,7 @@ function launch_on_machine(manager::SSHManager, machine, cnt, params, launched,
     portopt = ``
     if length(machine_def) == 2
         portstr = machine_def[2]
-        if !isinteger(portstr) || (p = parse(Int,portstr); p < 1 || p > 65535)
+        if !all(isdigit, portstr) || (p = parse(Int,portstr); p < 1 || p > 65535)
```
Comment (JeffBezanson) [inline base/distributed/managers.jl]: This should use `tryparse(Int, portstr)`.

Comment (JeffBezanson) [inline base/distributed/managers.jl]: I guess any valid port number would be all digits though.

Comment (yuyichao) [inline base/distributed/managers.jl]: If this is to avoid confusing errors it can still happen on overflow?
