### PR TITLE
Fix numeric instability in signif

### LINKED ISSUE #3497: Bugs on signif()
Default ```signif``` return ```NaN``` for the value 0.0 instead of 0.0
```
julia> signif(0.000,1,10) # default
NaN

julia> signif(0.000,1,1)
0.0
```
There is problems with some float values. I expect for ```signif(0.6,1)``` return 0.6 like with 0.1:
```
julia> signif(0.6,1)
0.6000000000000001

julia> signif(0.1,1)
0.1
```

### PR DESCRIPTION
**Pull request by pfitzseb**
This issue came up in the [mailing list](https://groups.google.com/forum/?fromgroups=#!searchin/julia-users/signif/julia-users/AzIcaDUf3zc/pkdG0I8CWhYJ) and I thought I'd have a stab at it.

Also fixes #3497.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Thanks. @simonbyrne – I feel like you may be the expert here.

**Comment by simonbyrne** [comment]
This seems like a good solution. Since we're splitting out the cases `2` and `10` here anyway, we might as well use `exp2` and `exp10` instead of calling `^`.

At some point it might make sense to share this sort of machinery with decimal string input and printing routines, but I don't think that is a huge priority.

**Comment by Varanas** [comment]
Fixed.

I don't quite see how this would be useful for input, but compact printing of floats in arrays could/should probably use this.

**Comment by simonbyrne** [comment]
@Varanas I was simply referring to the binary <-> decimal conversion routines that underly all these things.

**Comment by simonbyrne** [comment]
Great: would you mind adding some tests for `Float32` as well? Then we can probably merge this.

**Comment by Varanas** [comment]
Yeah, will do.

One question though: Should we really *not* throw an `DomainError()` if `digits == 0`? It doesn't really make sense to round a number to zero digits of precision, does it?

**Comment by Varanas** [comment]
Oh, and another thing: When wanting more digits of precision than the type actually stores, we get `Inf`s and `NaN`s, e.g. `isnan(signif(1., 1000)) == true`.

Should we special case this and just return the maximum number of digits supported by the given type, throw a `DomainError`, or just add a note to the docs?

**Comment by simonbyrne** [comment]
> One question though: Should we really not throw an DomainError() if digits == 0? It doesn't really make sense to round a number to zero digits of precision, does it?
I think `DomainError` makes the most sense,

> Oh, and another thing: When wanting more digits of precision than the type actually stores, we get Infs and NaNs, e.g. isnan(signif(1., 1000)) == true.

I think returning the current value would make the most sense.

It also just occurred to me that we could handle the base 2 using `exponent` and `ldexp`, which might be quicker.

**Comment by Varanas** [comment]
Okay, I fixed that.

I didn't include the change for base 2 since that would require a special case in `signif` and it only gives a ~8% speedup. Not sure if that's worth the added code complexity...

**Comment by simonbyrne** [comment]
Fair enough: I think the main boost would come from using `exponent`. This looks good to me, thanks for doing this.

File: base/floatfuncs.jl [hunk 1]
```diff
@@ -105,24 +105,30 @@ end
 
 function _signif_og(x, digits, base)
     if base == 10
-        oftype(x, 10. ^ floor(log10(abs(x)) - digits + 1.))
+        e = floor(log10(abs(x)) - digits + 1.)
+        og = oftype(x, exp10(abs(e)))
     elseif base == 2
-        oftype(x, 2. ^ floor(log2(abs(x)) - digits + 1.))
+        e = exponent(abs(x)) - digits + 1.
+        og = oftype(x, exp2(abs(e)))
```
Comment (simonbyrne) [inline base/floatfuncs.jl]: You could use `ldexp(1.0,e)` should be quicker than `exp2`.

File: base/floatfuncs.jl [hunk 2]
```diff
@@ -105,24 +105,30 @@ end
 
 function _signif_og(x, digits, base)
     if base == 10
-        oftype(x, 10. ^ floor(log10(abs(x)) - digits + 1.))
+        e = floor(log10(abs(x)) - digits + 1.)
+        og = oftype(x, exp10(abs(e)))
     elseif base == 2
-        oftype(x, 2. ^ floor(log2(abs(x)) - digits + 1.))
+        e = exponent(abs(x)) - digits + 1.
```
Comment (simonbyrne) [inline base/floatfuncs.jl]: `exponent` will return an `Int`, so the function won't be type-stable: after you do the `ldexp`, you could convert it back to the relevant type.

Comment (Varanas) [inline base/floatfuncs.jl]: Shouldn't the addition of the Float literal promote this to `Float64`/`Float32` anyways so that `e` always has the same type?
Sure, I'm adding two integers and a float, but that shouldn't harm performance any more than doing the conversion manually, right?

Comment (simonbyrne) [inline base/floatfuncs.jl]: Ah true, I missed the `.`

File: base/floatfuncs.jl (hunk 1 above)
Comment (simonbyrne) [inline base/floatfuncs.jl]: that should be `ldexp(1.0,abs(e))`: however I think this currently requires `e` to be an integer.

Comment (Varanas) [inline base/floatfuncs.jl]: Should there be any difference in performance in generic exponentation whether the exponent is an integer or a float? I thought having an integer exponent might be faster, but my small test shows no significant difference.
If it makes no difference, we could have `e` always be an Int and use `ldexp`. So the only change would be the deletion of the `.` and then we'd have a type stable `e`?

Comment (simonbyrne) [inline base/floatfuncs.jl]: No, `exp2` converts integer arguments to floats, and all float arguments (even if integer valued) should be roughly the same speed.

Let's go with what we have now: there is always room for more speed hacks later on, it's probably more important to have it correct for the time being.

**Comment by simonbyrne** [comment]
Thanks, it's great to get some of these old bugs fixed!

**Comment by vtjnash** [comment]
warning: this fix appears to be thwarted by the llvm constant propagation pass in llvm-svn (not sure about other llvm versions)

**Comment by simonbyrne** [comment]
@vtjnash I'm not sure I understand the problem. Can you expand on it further, or provide an example?

**Comment by vtjnash** [comment]
llvm35 observes that since you branched on a comparison to 0.0, the value of `%0` in the branch is 0.0, so it can constant fold to pre-compute the return value:
```
julia> signif(-0.0,1)
0.0

julia> @code_llvm signif(-0.0,1,10)

define double @julia_signif_43028(double, i64, i64) {
top:
  %3 = icmp sgt i64 %1, 0, !dbg !8
  br i1 %3, label %L, label %if, !dbg !8

if:                                               ; preds = %top
  call void @jl_throw_with_superfluous_argument(%jl_value_t* inttoptr (i64 4360765456 to %jl_value_t*), i32 121), !dbg !8
  br label %L, !dbg !8

L:                                                ; preds = %if, %top
  %4 = fcmp une double %0, 0.000000e+00, !dbg !10
  br i1 %4, label %L2, label %if1, !dbg !10

if1:                                              ; preds = %L
  ret double 0.000000e+00, !dbg !10

L2:                                               ; preds = %L
  %5 = call <2 x double> @julia__signif_og_43029(double %0, i64 %1, i64 %2), !dbg !11, !julia_type !12
  %6 = extractelement <2 x double> %5, i32 0, !dbg !11
  %7 = extractelement <2 x double> %5, i32 1, !dbg !11
  %8 = fcmp ult double %7, 0.000000e+00, !dbg !13
  br i1 %8, label %L5, label %if3, !dbg !13

if3:                                              ; preds = %L2
  %9 = fdiv double %0, %6, !dbg !14
  %10 = call double @llvm.rint.f64(double %9), !dbg !14
  %11 = fmul double %6, %10, !dbg !14
  br label %L6, !dbg !14

L5:                                               ; preds = %L2
  %12 = fmul double %6, %0, !dbg !15
  %13 = call double @llvm.rint.f64(double %12), !dbg !15
  %14 = fdiv double %13, %6, !dbg !15
  br label %L6, !dbg !15

L6:                                               ; preds = %L5, %if3
  %r.0 = phi double [ %14, %L5 ], [ %11, %if3 ]
  %15 = fsub double %r.0, %r.0, !dbg !16
  %16 = fcmp oeq double %15, 0.000000e+00, !dbg !16
  br i1 %16, label %L9, label %if7, !dbg !16

if7:                                              ; preds = %L6
  ret double %0, !dbg !16

L9:                                               ; preds = %L6
  ret double %r.0, !dbg !16
}
```

**Comment by simonbyrne** [comment]
Sorry, I'm still a bit confused: isn't that we want to happen?

**Comment by vtjnash** [comment]
It fails the tests

**Comment by Varanas** [comment]
if that is that is aproblem, rhen something like
```
x === 0.0 && return oftype(x, 0.0)
x === -0.0 && return oftype(x, -0.0)
```
should do the trick, no?
Alternatively we could always returN `+0.0` and change the test accordingly, but that would probably be a bad idea.

**Comment by simonbyrne** [comment]
Ah, I see now. My initial reaction is that this is a bug in LLVM, as it isn't a valid transformation.

I just compiled with LLVM 3.5 and couldn't reproduce this, I'll try 3.6.

**Comment by vtjnash** [comment]
@Varanas you don't want strict equality, since that would only be correct for the Float64 case

i agree that llvm seems to be doing an invalid optimization there. would the following statement be valid there instead?

`(x==0 || !isfinite(x)) && return x`

**Comment by Varanas** [comment]
Ah, I see.
And yes, `(x==0 || !isfinite(x)) && return x` would be valid. I just moved the `!isfinite` check to the end - mistakenly, as returning before trying to calculate anything for `NaN`s and `Inf`s should improve performance.
