### PR TITLE
Fix reuse of client port on FreeBSD

### LINKED ISSUE #22302: Distributed tests fail on FreeBSD
On FreeBSD 11, the following segment of the tests in distributed_exec.jl fail:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.506 (2017-06-08 21:51 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit dde6ff61c3* (0 days old master)
|__/                   |  x86_64-unknown-freebsd11.0

julia> using Base.Test

julia> function reuseport_tests()
           # Run the test on all processes.
           results = asyncmap(procs()) do p
               remotecall_fetch(p) do
                   ports_lower = []        # ports of pids lower than myid()
                   ports_higher = []       # ports of pids higher than myid()
                   for w in Base.Distributed.PGRP.workers
                       w.id == myid() && continue
                       port = Base._sockname(w.r_stream, true)[2]
                       if (w.id == 1)
                           # master connects to workers
                           push!(ports_higher, port)
                       elseif w.id < myid()
                           push!(ports_lower, port)
                       elseif w.id > myid()
                           push!(ports_higher, port)
                       end
                   end
                   @assert (length(ports_lower) + length(ports_higher)) == nworkers()
                   for portset in [ports_lower, ports_higher]
                       if (length(portset) > 0) && (length(unique(portset)) != 1)
                           warn("SO_REUSEPORT TESTS FAILED. UNSUPPORTED/OLDER UNIX VERSION?")
                           return 0
                       end
                   end
                   return myid()
               end
           end

           # Ensure that the code has indeed been successfully executed everywhere
           @test all(p -> p in results, procs())
       end
reuseport_tests (generic function with 1 method)

julia> addprocs(4)
4-element Array{Int64,1}:
 2
 3
 4
 5

julia> reuseport_tests()
WARNING: SO_REUSEPORT TESTS FAILED. UNSUPPORTED/OLDER UNIX VERSION?
WARNING: WARNING: SO_REUSEPORT TESTS FAILED. UNSUPPORTED/OLDER UNIX VERSION?
SO_REUSEPORT TESTS FAILED. UNSUPPORTED/OLDER UNIX VERSION?
Test Failed
  Expression: all((p->begin
            p in results
        end), procs())
ERROR: There was an error during testing
```
The tests were passing as recently as about a month or so ago (I hadn't run them in a while).

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #22302 

I think DragonFly BSD might do the same thing as Linux here but I can't confirm because I've yet to get Julia to build on DragonFly. This at least gets the distributed tests passing on FreeBSD.

### CODE REVIEW

**Comment by amitmurthy** [comment]
Thinking a bit more, I realize we should replace the OS checks by checking if `SO_REUSEPORT ` is defined. Can have a C function that checks for it and use that both here and in the test script.

**Comment by ararslan** [comment]
@amitmurthy Were you thinking something like this?

File: base/distributed/managers.jl [hunk 1]
```diff
@@ -455,10 +455,10 @@ end
 const client_port = Ref{Cushort}(0)
 
 function socket_reuse_port()
-    @static if is_linux() || is_apple()
+    if Bool(ccall(:jl_has_so_reuseport, Int32, ()))
```
Comment (ararslan) [inline base/distributed/managers.jl]: Realized that this can be `ccall(:jl_has_so_reuseport, Bool, ())`. I'll make that change if this approach is acceptable.

Comment (vtjnash) [inline base/distributed/managers.jl]: `Bool` is a `Int8` (really `Int1`) type, so those wouldn't be equivalent. Although, I thought we deprecated this Bool constructor some years ago and required `!= 0` now?

Comment (ararslan) [inline base/distributed/managers.jl]: I guess if this PR is good then I'll make it `!= 0`.

Comment (amitmurthy) [inline base/distributed/managers.jl]: Also https://github.com/JuliaLang/julia/pull/22303/files#diff-5b6252dbf4f6ba35c7ee92dde3cb6451L836 can return `-1` now as Julia code is expected to check with `jl_has_so_reuseport`  before calling `jl_tcp_reuseport`

File: base/distributed/managers.jl [hunk 2]
```diff
@@ -455,10 +455,10 @@ end
...
         s = TCPSocket(delay = false)
 
-        # Linux requires the port to be bound before setting REUSEPORT, OSX after.
+        # Linux requires the port to be bound before setting REUSEPORT, BSD after.
         is_linux() && bind_client_port(s)
         rc = ccall(:jl_tcp_reuseport, Int32, (Ptr{Void},), s.handle)
         if rc > 0  # SO_REUSEPORT is unsupported, just return the ephemerally bound socket
```
Comment (amitmurthy) [inline base/distributed/managers.jl]: This check can now be removed.

File: base/distributed/managers.jl [hunk 3]
```diff
@@ -470,7 +470,7 @@ function socket_reuse_port()
             # provide a clean new socket
             return TCPSocket()
         end
-        is_apple() && bind_client_port(s)
+        is_bsd() && bind_client_port(s)
```
Comment (amitmurthy) [inline base/distributed/managers.jl]: Should change this to `!is_linux() && bind_client_port(s)`. 

Or ideally, few lines above to `bind_port = is_linux() ? true : false ; bind_port && bind_client_port(s)` and this line to `!bind_port && bind_client_port(s)`.

File: base/distributed/managers.jl (hunk 1 above)
Comment (ararslan) [inline base/distributed/managers.jl]: Right, I was talking more specifically about the return type of `jl_has_so_reuseport`, which will only ever be 0 or 1, so I figured that one was safe to convert to `Bool`.

File: base/distributed/managers.jl (hunk 3 above)
Comment (amitmurthy) [inline base/distributed/managers.jl]: Just to ensure that if in the future,  Windows starts supporting reuseport, and requires early binding, we then have to change only the first line.

File: base/distributed/managers.jl (hunk 2 above)
Comment (ararslan) [inline base/distributed/managers.jl]: Do you mean the entire conditional on `rc` or just the `rc > 0` section?

File: test/distributed_exec.jl [hunk 4]
```diff
@@ -48,7 +48,7 @@ end
 
 # Test that the client port is reused. SO_REUSEPORT may not be supported on
 # all UNIX platforms, Linux kernels prior to 3.9 and older versions of OSX
-if is_unix()
+if ccall(:jl_has_so_reuseport, Int32, ()) == 1
```
Comment (amitmurthy) [inline test/distributed_exec.jl]: The lines below were checking if reuseport is supported. Can be simplified now to directly call `reuseport_tests()` if supported else print an informational string.

File: src/jl_uv.c [hunk 5]
```diff
@@ -823,6 +823,15 @@ JL_DLLEXPORT int jl_tcp_quickack(uv_tcp_t *handle, int on)
...
+#if defined(SO_REUSEPORT)
+    return 1;
+#else
+    return 0;
+#endif
+}
+
 JL_DLLEXPORT int jl_tcp_reuseport(uv_tcp_t *handle)
 {
 #if defined(SO_REUSEPORT)
```
Comment (amitmurthy) [inline src/jl_uv.c]: Can return `-1` in the `#else` condition now.

File: base/distributed/managers.jl (hunk 2 above)
Comment (amitmurthy) [inline base/distributed/managers.jl]: `rc > 0` section.

File: src/jl_uv.c (hunk 5 above)
Comment (ararslan) [inline src/jl_uv.c]: I'm confused—this function could always return -1.

Comment (amitmurthy) [inline src/jl_uv.c]: I meant
```
#if defined(SO_REUSEPORT)
......
#else
   return -1;
#endif
```

Comment (ararslan) [inline src/jl_uv.c]:
```diff
 JL_DLLEXPORT int jl_tcp_reuseport(uv_tcp_t *handle)
 {
 #if defined(SO_REUSEPORT)
     int fd = (handle)->io_watcher.fd;
     int yes = 1;
     if (setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &yes, sizeof(yes))) {
         return -1;
     }
     return 0;
 #else
-    return 1;
+    return -1;
 #endif
 }
```
?

Comment (amitmurthy) [inline src/jl_uv.c]: Yes.

Comment (ararslan) [inline src/jl_uv.c]: Okay, will do. Thanks!

**Comment by amitmurthy** [comment]
LGTM.

**Comment by ararslan** [comment]
Thanks for all your help and guidance, @amitmurthy!
