### PR TITLE
base: make diff() use views and broadcasting

### LINKED ISSUE #15414: Extend diff() to arbitrary dimensions
I recently saw a [post by Tim](http://julialang.org/blog/2016/02/iteration) discussing the new `CartesianIndex` type. Does it help to write a more general `diff()` that works with N-dimensional arrays? Currently it only supports matrices (i.e. 2D arrays).

### LINKED ISSUE #27957: diff(Vector,dims=1)
in 0.7.0-beta.108,
```diff(ones(6),dims=1)```  gives

> ERROR: MethodError: no method matching diff(::Array{Float64,1}; dims=1)

In contrast, ```sum(ones(6),dims=1)``` works.

### PR DESCRIPTION
**Pull request by stev47**
fixes #27957
fixes #15414 (didn't see this at the time of coding)

This uses array views and broadcasting to implement diff() in arbitrary dimension.
Added benefit is a significant performance increase for arrays with more than about 10 elements (at least in my tests).

```
x = rand(1000)
y = rand(1000,1000)
z = rand(10)
@btime diff($x);
@btime diff($y, dims=2);
@btime diff($z);
```
before:
```
919.474 ns (3 allocations: 7.98 KiB)
1.612 ms (4 allocations: 7.62 MiB)
41.718 ns (3 allocations: 208 bytes)
```
after:
```
504.201 ns (3 allocations: 8.03 KiB)
864.279 μs (4 allocations: 7.62 MiB)
41.598 ns (3 allocations: 256 bytes)
```

### CODE REVIEW

File: base/multidimensional.jl [hunk 1]
```diff
@@ -690,14 +687,15 @@ julia> diff(vec(a))
...
-function diff(A::AbstractMatrix; dims::Integer)
-    if dims == 1
-        [A[i+1,j] - A[i,j] for i=1:size(A,1)-1, j=1:size(A,2)]
-    elseif dims == 2
-        [A[i,j+1] - A[i,j] for i=1:size(A,1), j=1:size(A,2)-1]
-    else
-        throw(ArgumentError("dimension must be 1 or 2, got $dims"))
-    end
+function diff(a::AbstractArray; dims::Integer)
+  @assert !has_offset_axes(a)
```
Comment (ararslan) [inline base/multidimensional.jl]: This should use the Julia standard of 4 spaces for indentation, in keeping with the rest of the repo. Also, instead of `@assert`ing conditions about arguments, you should use something like
```julia
has_offset_axes(a) && throw(ArgumentError("..."))
```

File: base/multidimensional.jl [hunk 2]
```diff
@@ -690,14 +687,15 @@ julia> diff(vec(a))
...
+  1 <= dims <= ndims(a) || throw(ArgumentError("dimension out of range"))
```
Comment (ararslan) [inline base/multidimensional.jl]: Since you're using `ndims(a)` multiple times, it might be a little nicer to do
```julia
function diff(a::AbstractArray{T,N}; dims::Integer) where {T,N}
    ...
    1 <= dims <= N || ...
    ...
end
```

File: base/multidimensional.jl [hunk 3]
```diff
@@ -690,14 +687,15 @@ julia> diff(vec(a))
...
+
+  r = axes(a)
+  r0 = ntuple(i -> i == dims ? Base.OneTo(last(r[i]) - 1) : r[i], ndims(a))
```
Comment (ararslan) [inline base/multidimensional.jl]: No need for `Base.` qualifications inside of Base.

File: base/multidimensional.jl (hunk 2 above)
Comment (nalimilan) [reply base/multidimensional.jl]: BTW, printing the dimension which was actually passed (as the existing code does) is also nice for users.

File: base/multidimensional.jl (hunk 3 above)
Comment (nalimilan) [reply base/multidimensional.jl]: And `OneTo` won't be correct for all `AbstractArrays`, so better use a more general range starting at `first(r[i])`. Also, below `UnitRange` could be built using the standard `a:b` syntax, starting at `r[i][2]`.

File: base/multidimensional.jl (hunk 1 above)
Comment (stev47) [reply base/multidimensional.jl]: thanks, fixed

File: base/multidimensional.jl (hunk 2 above)
Comment (stev47) [reply base/multidimensional.jl]: good call, fixed

File: base/multidimensional.jl (hunk 3 above)
Comment (ararslan) [reply base/multidimensional.jl]: Currently the code ensures that the input does not have offset axes, so `OneTo` should technically work, though it should be fairly straightforward to tweak things to allow offset axes.

**Review by timholy — COMMENTED** [review]
Very nice @stev47, just one tiny thing to fix and then I think this can be merged. There's some chance we'd need #28941 to solve this elegantly for arrays with offset axes, so I think it's fine to restrict this to 1-indexed arrays for now.

(@juliohm, this is the implementation I was hinting at with my comment about "in one go.")

File: base/multidimensional.jl [hunk 4]
```diff
@@ -690,14 +687,15 @@ julia> diff(vec(a))
...
-        [A[i,j+1] - A[i,j] for i=1:size(A,1), j=1:size(A,2)-1]
-    else
-        throw(ArgumentError("dimension must be 1 or 2, got $dims"))
-    end
+function diff(a::AbstractArray{T,N}; dims::Integer) where {T,N}
+    has_offset_axes(a) && throw(ArgumentError("offset axes unsupported"))
+    1 <= dims <= N || throw(ArgumentError("dimension out of range"))
+
+    r = axes(a)
+    r0 = ntuple(i -> i == dims ? OneTo(last(r[i]) - 1) : r[i], N)
```
[the remark this answers is not in the document]
Comment (timholy) [reply base/multidimensional.jl]: (Note that an array can have non-OneTo axes and still pass the test above---it's a test for values, not types.)

[the remark this answers is not in the document]
Comment (stev47) [reply base/multidimensional.jl]: thanks, fixed. I opted for the `UnitRange` variant.

**Comment by juliohm** [comment]
Thanks @stev47 for the addition, and thanks @timholy for pinging. :+1:

**Comment by timholy** [comment]
Sorry for one more request, but I think the docstring needs updating too. Does this need a NEWS item?

**Comment by stev47** [comment]
updated the docstring

**Review by mbauman — APPROVED** [review]
