### PR TITLE
fix `power_by_squaring`: use `promote` instead of type inference

### LINKED ISSUE #53504: More correct inference for the return type of exponentiation
The function `Base.to_power_type(x)` is found [here](https://github.com/JuliaLang/julia/blob/c379db77135e55b71707704f58d901e78924804d/base/intfuncs.jl#L298) and defined below:
```julia
to_power_type(x) = convert(Base._return_type(*, Tuple{typeof(x), typeof(x)}), x)
```
This function is used in `Base.power_by_squaring` to determine what type the result should be. I think the definition above is flawed, and we should be using this:
```julia
power_type(::Type{T}) where T = promote_type(Base._return_type(*, Tuple{T, T}), T, Base._return_type(one, Tuple{T}))

to_power_type(x::T) where T = convert(power_type(T), x)
```
# But why, you ask?

In the general case, to maintain type stability, the output of `Base.power_by_squaring(x, n)` needs to be a type that can store `x^0`, `x`, and `x^2`. However, `one(x)`, which is used to calculate `x^0`,  may be a different type from `x` or `x*x`:

> If possible, `one(x)` returns a value of the same type as `x`, and `one(T)` returns a value of type `T`. However, this may not be the case for types representing dimensionful quantities (e.g. time in days), since the multiplicative identity must be dimensionless. In that case, `one(x)` should return an identity value of the same precision (and shape, for matrices) as `x`.

I am currently writing a package, CliffordNumbers.jl, which has some data types `T` (such as `KVector{K}` when `K` is odd) for which neither `typeof(one(T))` nor `Base._return_type(*, Tuple{T, T})` are `T`. This causes exponentiation to fail without some workarounds because the input is not always convertable to the result of `Base._return_type(*, Tuple{T, T})`.

The problem I faced might be a really niche edge case, but I think the way integer powers of types are handled in cases where they are not equivalent to the type itself is worth discussing and refining. The solution I present would completely solve my issues (though I have already solved them within the package), but I'm not sure if it's too much of a breaking change.

### LINKED ISSUE #55633: `power_by_squaring` (thus `^`, too) broken for "type domain number" types
`power_by_squaring` starts like this:

https://github.com/JuliaLang/julia/blob/da3468c1208b087161af5b69a26a92a91967a367/base/intfuncs.jl#L315-L317

The intention is to help with type stability by converting the input to the type of the square of the input. This is the definition of the only method of the helper function `to_power_type`:

https://github.com/JuliaLang/julia/blob/da3468c1208b087161af5b69a26a92a91967a367/base/intfuncs.jl#L300-L301

There are multiple issues here:
* the use of type inference
* the assumption that `x` may be converted to `typeof(x*x)` (doesn't hold for "type domain number" types, as in my package TypeDomainNaturalNumbers, so I get a `MethodError`)

These would all be fixed by replacing `x = to_power_type(x_)` with something like:

```julia
(x0, x, x2) = promote(one(x_), x_, mul(x_, x_))
```

Testing this right now.

NB: this fix will cause unnecessary allocation for some matrix inputs, because of the unconditional `one(_x)` and `mul(_x, _x)`.

xref #11383 #24151 #53504

### PR DESCRIPTION
**Pull request by nsajko**
Fixes #53504

Fixes #55633

### CODE REVIEW

**Comment by nsajko** [comment]
NB: initially I was going to put `one(x_)` into the `promote`, too. This would help with #53504. However, some packages don't implement `one` for their types, and apparently expect `x^0` not to be called. PolynomialRings is such an example. So I decided to leave that out of this PR. It can always be tackled in a future PR.

File: base/intfuncs.jl [hunk 1]
```diff
@@ -314,13 +315,13 @@ to_power_type(x) = convert(Base._return_type(*, Tuple{typeof(x), typeof(x)}), x)
     "or write float(x)^", p, " or Rational.(x)^", p, ".")))
 # The * keyword supports `*=checked_mul` for `checked_pow`
 @assume_effects :terminates_locally function power_by_squaring(x_, p::Integer; mul=*)
-    x = to_power_type(x_)
+    (x, x2) = promote(x_, mul(x_, x_))
```
Comment (mbauman) [inline base/intfuncs.jl:318]: This is close to how it used to be, but de7f5ae changed it to avoid the unnecessary allocation for matrices.

File: test/math.jl [hunk 2]
```diff
@@ -1498,6 +1498,15 @@ end
...
+
+    # #55633
+    struct Issue55633 <: Number end
+    struct Issue55633Squared <: Number end
+    Base.:(*)(::Issue55633, ::Issue55633) = Issue55633Squared()
+    Base.promote_rule(::Type{Issue55633}, ::Type{Issue55633Squared}) = Int
+    Base.convert(::Type{Int}, ::Issue55633) = 3
+    Base.convert(::Type{Int}, ::Issue55633Squared) = 9
+    @test 9 === Issue55633()^2
 end
```
Comment (mbauman) [inline test/math.jl:1510]: I suspect some of these tests will fail:

```suggestion
    for (x,x0,x1,x2) in ((im, 1+0im, 0+1im, -1+0im),
                         ('x', "", "x", "xx"),
                         (pi, 1.0, Float64(pi), pi*pi))
        @test x^0 === x0
        @test x^1 === x1
        @test x^2 === x2
    end
end
```

File: base/intfuncs.jl (hunk 1 above)
Comment (nsajko) [reply base/intfuncs.jl:318]: I don't think that having the behavior vary depending on input type is such a good idea. Especially because the code is quite inefficient allocation-wise for matrix input anyway.

File: test/math.jl (hunk 2 above)
Comment (nsajko) [reply test/math.jl:1510]: I don't think strings are supposed to be supported? The code relies on `copy`, but there's no `copy(::String)`.

Comment (mbauman) [reply test/math.jl:1510]: Ah, sure enough, there's a different `^` for those — `power_by_squaring('x', 0)` doesn't even get that far because it tries to convert the char to a string first.  Maybe use Furlongs instead?  Just trying to think of all the odd types here.

Comment (nsajko) [reply test/math.jl:1515]: `^` is broken for Furlongs both before and after this change. And a furlong squared isn't promotable together with the original furlong. This is really issue #24151. I don't think there's a good way of fixing that issue.

I propose we just keep `^` broken for furlongs.

File: base/intfuncs.jl (hunk 1 above)
Comment (nsajko) [reply base/intfuncs.jl:318]: Looks like it's necessary to avoid the promotion for matrices in any case, looking at the failing tests.

**Comment by nsajko** [comment]
the failing test is because of #55642

**Comment by simeonschaub** [comment]
This still seems potentially too narrow for number types such as those in https://github.com/SciML/Static.jl for example though

**Comment by nsajko** [comment]
> too narrow

What do you mean? Are you saying the change would cause an incorrect throw, or are you saying this doesn't help with type instability?

FTR the Static.jl testsuite passes with this PR.

**Comment by simeonschaub** [comment]
I'm saying that `promote_type(typeof(x), typeof(one(x)), typeof(x*x))` might not always contain `typeof(x*x*x)` for example. This still seems like an overall improvement over the current situation though so these concerns can probably be addressed at a later time

**Comment by nsajko** [comment]
I'd rather not add `x*x*x` to the `promote_type`. In the case of, e.g., `BigInt` that computation AFAIK could never be optimized out (unless `BigInt` gets reimplemented in pure Julia).

**Comment by nsajko** [comment]
Interestingly, Static.jl doesn't implement promotion correctly: https://github.com/SciML/Static.jl/issues/98

**Comment by nsajko** [comment]
bump

**Comment by nsajko** [comment]
ping

**Review by oscardssmith — APPROVED** [review]

File: base/intfuncs.jl [hunk 3]
```diff
@@ -298,7 +298,11 @@ function invmod(n::T) where {T<:BitInteger}
 end
 
 # ^ for any x supporting *
-to_power_type(x) = convert(Base._return_type(*, Tuple{typeof(x), typeof(x)}), x)
+function to_power_type(x::Number)
+    T = promote_type(typeof(x), typeof(one(x)), typeof(x*x))
```
Comment (nsajko) [inline base/intfuncs.jl:302]:
```suggestion
    T = promote_type(typeof(x), typeof(x*x))
```

It just occured to me that a multiplicative identity doesn't necessarily exist:

https://en.wikipedia.org/wiki/Rng_(algebra)

Are such structures supported?

Comment (nsajko) [reply base/intfuncs.jl:302]: I guess it'd be OK to require a type without a multiplicative identity to implement `^` themselves?

Comment (KristofferC) [reply base/intfuncs.jl:302]: This is breaking.

```
julia> using FixedPointNumbers

julia> (0.0Q0f15)^2
ERROR: ArgumentError: Q0f15 is a 16-bit type representing 65536 values from -1.0 to 0.99997; cannot represent 1
Stacktrace:
  [1] throw_converterror(::Type{Q0f15}, x::Int64)
    @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:326
  [2] rawone(::Type{Q0f15})
    @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/fixed.jl:41
  [3] oneunit(::Type{Q0f15})
    @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:108
  [4] one(::Type{Q0f15})
    @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:109
  [5] one(x::Q0f15)
    @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:222
  [6] to_power_type(x::Q0f15)
    @ Base ./intfuncs.jl:336
```

Comment (KristofferC) [reply base/intfuncs.jl:302]: https://github.com/JuliaLang/julia/issues/57390
