### PR TITLE
fix #35708, GC seeing uninitialized struct in `jl_new_struct*`

### LINKED ISSUE #35708: Segfault in Julia runtime
Following the instructions in [Segfaults when running a script](https://docs.julialang.org/en/v1/devdocs/backtraces/#Segfaults-when-running-a-script-1):

Here is a [Gist](https://gist.github.com/bzinberg/9f065885929564d53947f07a484a845f) containing versioninfo, backtrace and valgrind output.

This crash occurs in Julia 1.4.1 and 1.4.0, but not 1.3.1.

I'm not experienced in this kind of debugging, so not sure what further information would be useful.  Happy to dialogue about it.

Thanks!

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #35708

### CODE REVIEW

File: src/datatype.c [hunk 1]
```diff
@@ -943,14 +939,17 @@ JL_DLLEXPORT jl_value_t *jl_new_structt(jl_datatype_t *type, jl_value_t *tup)
...
     JL_GC_PUSH2(&jv, &fi);
     for (size_t i = 0; i < nargs; i++) {
         jl_value_t *ft = jl_field_type(type, i);
         fi = jl_get_nth_field(tup, i);
         if (!jl_isa(fi, ft))
             jl_type_error("new", ft, fi);
+    }
+    jv = jl_gc_alloc(ptls, jl_datatype_size(type), type);
+    for (size_t i = 0; i < nargs; i++) {
+        fi = jl_get_nth_field(tup, i);
```
Comment (vtjnash) [inline src/datatype.c:952]: This allocates too
