### PR TITLE
fix cumsum ignoring first element returned in call to promote_op

### LINKED ISSUE #53438: `cumsum` gives bad error message when collection elements can't be added
```julia
julia> sum(sincos.(1:10)) # Good error
ERROR: MethodError: no method matching +(::Tuple{Float64, Float64}, ::Tuple{Float64, Float64})

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:587

Stacktrace:
 [1] add_sum(x::Tuple{Float64, Float64}, y::Tuple{Float64, Float64})
   @ Base ./reduce.jl:24
 [2] _mapreduce
   @ ./reduce.jl:440 [inlined]
 [3] _mapreduce_dim
   @ ./reducedim.jl:365 [inlined]
 [4] mapreduce
   @ ./reducedim.jl:357 [inlined]
 [5] _sum
   @ ./reducedim.jl:1015 [inlined]
 [6] _sum
   @ ./reducedim.jl:1014 [inlined]
 [7] sum(a::Vector{Tuple{Float64, Float64}})
   @ Base ./reducedim.jl:1010
 [8] top-level scope
   @ REPL[24]:1

julia> cumsum(sincos.(1:10)) # Bad error
ERROR: ArgumentError: cannot convert a value to Union{} for assignment
Stacktrace:
  [1] convert(T::Core.TypeofBottom, x::Tuple{Float64, Float64})
    @ Base ./essentials.jl:315
  [2] setindex!(A::Vector{Union{}}, x::Tuple{Float64, Float64}, i1::Int64)
    @ Base ./array.jl:1021
  [3] accumulate_pairwise!
    @ ./accumulate.jl:29 [inlined]
  [4] _cumsum!(out::Vector{Union{}}, v::Vector{Tuple{Float64, Float64}}, dim::Int64, ::Base.ArithmeticRounds)
    @ Base ./accumulate.jl:57
  [5] _cumsum!
    @ ./accumulate.jl:60 [inlined]
  [6] #cumsum!#889
    @ ./accumulate.jl:53 [inlined]
  [7] cumsum!
    @ ./accumulate.jl:51 [inlined]
  [8] #cumsum#890
    @ ./accumulate.jl:115 [inlined]
  [9] cumsum
    @ ./accumulate.jl:113 [inlined]
 [10] cumsum(x::Vector{Tuple{Float64, Float64}})
    @ Base ./accumulate.jl:146
 [11] top-level scope
    @ REPL[25]:1
```

In 1.9 the error was
```julia
julia> cumsum(sincos.(1:10))
ERROR: MethodError: Base.ArithmeticStyle(::Type{Union{}}) is ambiguous.
```

### PR DESCRIPTION
**Pull request by rofinn**
Include an option to have `promote_op` throw an error rather than return `Union{}`. We're not changing the default behaviour, but in some cases returning `Union{}` will result in less clear error messages.

Closes #53438

@LilithHafner may have comments

### CODE REVIEW

File: base/promotion.jl [hunk 1]
```diff
@@ -502,10 +502,12 @@ function TupleOrBottom(tt...)
 end
 
 """
-    promote_op(f, argtypes...)
+    promote_op(f, argtypes...; throw_error=false)
 
 Guess what an appropriate container eltype would be for storing results of
 `f(::argtypes...)`. The guess is in part based on type inference, so can change any time.
+If `f(::argtypes...)` does not return (e.g., a method does not exist) then `Union{}` will be returned.
```
Comment (rofinn) [inline base/promotion.jl:509]: I could move this into the `Extended help` section if folks prefer.

File: base/accumulate.jl [hunk 2]
```diff
@@ -33,7 +33,7 @@ function accumulate_pairwise!(op::Op, result::AbstractVector, v::AbstractVector)
 end
 
 function accumulate_pairwise(op, v::AbstractVector{T}) where T
-    out = similar(v, promote_op(op, T, T))
+    out = similar(v, promote_op(op, T, T; throw_error=true))
```
Comment (rofinn) [inline base/accumulate.jl:36]: I'm only using `throw_error=true` in this file since that was the source of the original issue. There may be other cases where this would be useful.

File: base/promotion.jl [hunk 3]
```diff
@@ -608,7 +610,13 @@ loosen the API guarantee:
 
 However, it is discouraged to define such unconventional API guarantees.
 """
-function promote_op(f, S::Type...)
+function promote_op(f, S::Type...; throw_error=false)
```
Comment (rofinn) [inline base/promotion.jl:613]: Default behaviour is unchanged.

File: test/arrayops.jl [hunk 4]
```diff
@@ -2851,6 +2851,12 @@ end
     @inferred accumulate(*, String[])
     @test accumulate(*, ['a' 'b'; 'c' 'd'], dims=1) == ["a" "b"; "ac" "bd"]
     @test accumulate(*, ['a' 'b'; 'c' 'd'], dims=2) == ["a" "ab"; "c" "cd"]
+
+    # #53438
+    v = [(1, 2), (3, 4)]
+    @test_throws "does not return" accumulate(+, v)
```
Comment (rofinn) [inline test/arrayops.jl:2857]: First commit includes the original error message for this case. I can squash that if folks prefer.

**Comment by jishnub** [comment]
The name 'throw_error` is a bit generic and doesn't indicate the purpose of the argument. I wonder if a name like 'allow_bottom` might be better?

File: base/promotion.jl (hunk 1 above)
Comment (LilithHafner) [reply base/promotion.jl:509]: I think this is worth mentioning in the main text, it's brief.

```suggestion
If `f(::argtypes...)` does never return (e.g., a method does not exist) then `Union{}` may be returned.
```

`promote_op` may not be clever enough to determine that f does not return. In this case it would be valid for `promote_op` to return literally any type. Consequently will => may

**Comment by LilithHafner** [comment]
Lovely! The implementation looks good. I agree that `allow_bottom` would be a better name. I'm also realizing that this encourages folks to introduce bugs like https://github.com/JuliaLang/julia/issues/53458, but I don't think that's blocking.

**Comment by KristofferC** [comment]
For `parse` and `tryparse` there are two different functions controlling whether to throw or not. I think that makes sense here too.

**Comment by rofinn** [comment]
Yeah, my initial thought was introducing try_promote_op, but that’s what the current behaviour does, so renaming it would be breaking? I’m open to other naming conventions. I just went with throw_error since has precedent elsewhere in the codebase.

**Comment by KristofferC** [comment]
I'm wondering if adding a keyword argument to such a "basic" function could have some unexpected effects. This is just a worry without any supported evidence though.

**Comment by vtjnash** [comment]
I updated the example in https://github.com/JuliaLang/julia/issues/53438 to show that this will not close that issue. I am mildly against this PR, as this is a usage bug in `accumulate` incorrectly resulting in an error here, and which seems would be even more wrong if it was using this proposed flag.

**Comment by rofinn** [comment]
I have no strong preference here. The flag approach seemed like a relatively small change to address the `accumulate` code not handling the `Union{}` case. If we can rewrite the logic to avoid `promote_op` completely then that seems better, though more involved.

**Comment by rofinn** [comment]
As per @vtjnash's suggestions on issue #53438, I've reverted the `promote_op` change in favour of:

1. Consolidating the various `promote_op` calls to a single internal function in `accumulate.jl` (I have no opinion about the name)
2. Falling back to `Iterators.accumulate` if possible

NOTE: I couldn't find a way to drop the `promote_op` calls without breaking existing behaviour, so we're still using.
```
promote_type(
    isnothing(init) ? promote_op(reduce_first, typeof(op), T) : promote_op(op, typeof(init), T),
    promote_op(op, T, T)
)
```
This was also recommended in the issue thread and my understanding is that `promote_type` should fallback to a `typejoin` if no rule exists.

File: base/accumulate.jl [hunk 5]
```diff
@@ -280,14 +286,25 @@ function accumulate(op, A; dims::Union{Nothing,Integer}=nothing, kw...)
...
         throw(ArgumentError("accumulate does not support the keyword arguments $(setdiff(keys(nt), (:init,)))"))
     end
+
+    if dims === out === nothing
+        # If we failed to guess the container eltype then try to fallback to the iterators method
+        return collect(Iterators.accumulate(op, A; kw...))
+    elseif out === nothing
+        # If we can't fallback then error
+        T = eltype(A)
+        throw(ArgumentError("accumulate could not determine an appropriate container eltype for `$op($T, $T)"))
```
Comment (rofinn) [inline base/accumulate.jl:305]: As far as I can tell, there isn't a way around this case?

File: base/accumulate.jl [hunk 6]
```diff
@@ -442,3 +459,22 @@ function _accumulate1!(op, B, v1, A::AbstractVector, dim::Integer)
...
 end
+
+# Internal function used to identify the correct result array for a given op.
+# If that fails by returning `Union{}` then `nothing` will be returned, and the
+# calling function should fallback to an iterative solution.
+_try_result(args...; kwargs...) = nothing
+function _try_result(op, v::AbstractArray{T}; init=nothing) where T
+    # Try to identify the return type for the first element using `init` or `reduce_first`
+    F = isnothing(init) ? promote_op(reduce_first, typeof(op), T) : promote_op(op, typeof(init), T)
+    # Try to identify the return type fo the rest of the elements given op and eltype T
```
Comment (vtjnash) [inline base/accumulate.jl:470]:
```suggestion
    # Try to identify the return type of the rest of the elements given op and eltype T
```

File: base/accumulate.jl [hunk 7]
```diff
@@ -442,3 +459,22 @@ function _accumulate1!(op, B, v1, A::AbstractVector, dim::Integer)
...
+    R = promote_op(op, T, T)
```
Comment (vtjnash) [inline base/accumulate.jl:471]:
```suggestion
    R = promote_op(op, F, T)
```
technically this still is wrong, since it only models the first and second arguments. The Stateful type has a similar problem in `_approx_iter_type` and you can see the approximate solution it employs there. The only place I know that handles this pattern fully complete is `@default_eltype`. I think the pattern you need here looks like this (untested):

```julia
function _accumulate_upper_bound(v, i, op, init)
    val = v[i]
    r = isnothing(init) ? reduce_first(op, val) : op(init, val)
    while inferencebarrier(nothing)
        val = v[i]
        r = op(r, val)
    end
    return r
end

function _try_result(op, v::AbstractArray{T}, init) where T
    return promote_op(_accumulate_upper_bound, typeof(v), Int, typeof(op), typeof(init))
end
```

No failure handling should be necessary (or desirable), since the only reason this returns `Union{}` is that the code will fail with the real error message before it reaches that assignment.

Comment (rofinn) [reply base/accumulate.jl:471]: > No failure handling should be necessary (or desirable), since the only reason this returns `Union{}` is that the code will fail with the real error message before it reaches that assignment.

Right, thanks! Since the original issue was that `reduce_first` would work and try to assign into the array of type `Union{}` when it should have been `Tuple{Int, Int}`. If `Union{}` is returned then it should mean that all operations prior to insertion should fail.

Hmm, so the edge case your snippet is trying to address is when the return type for each call to the `op` results in us calling a different method? My understanding is that we want a "mock" function which updates a result value with the `op` over all elements of the array. We don't call it at runtime, but pass it to `promote_op` so we can ensure the widest possible type? A couple things I don't understand are:

1. What does `inferencebarrier(nothing)` do here? I thought that was used to tell the compiler to infer a value as `Any`?
2. Would this slow down inference?

In any case, yes, your example does seem to address that edge case. Here's a gist showing the difference for that edge case.

https://gist.github.com/rofinn/6aae6f559f2d9e6d1539f063ceabe2fc

Comment (vtjnash) [reply base/accumulate.jl:471]: Yes, it simply tells the compile to ignore that and treat the loop condition as unknown. Alternatively, this could perhaps use eachindex there to be a bit more accurate to the iteration protocol. There shouldn't be any discernible latency cost to this, since it is just one extra method to infer behavior on

I am also also not sure that typejoin result is needed on the uniontypes of the result. It looks like can be used directly in this example.

Comment (rofinn) [reply base/accumulate.jl:471]: Yeah, both work, but I was hoping to avoid overly complicated `Union` types.

Comment (rofinn) [reply base/accumulate.jl]: Okay, two other things I changed were.

1. Switched to using `Iterators.peel` in the inference function because tests failed for arrays that didn't support linear indexing.
2. I made it a nested function to make it clear that it is only intended to be used with `promote_op`.

File: test/arrayops.jl [hunk 8]
```diff
@@ -2589,7 +2589,7 @@ end
     @test accumulate(+, 0x00:0xff)[end] === 0x80         # overflow
     @test_throws InexactError cumsum!(similar(0x00:0xff), 0x00:0xff) # overflow
 
-    @test cumsum([[true], [true], [false]])::Vector{Vector{Int}} == [[1], [2], [2]]
+    @test cumsum([[true], [true], [false]])::Vector{Union{Vector{Bool}, Vector{Int}}} == [[1], [2], [2]]
```
Comment (rofinn) [inline test/arrayops.jl:2592]: This is why I was calling `promote_type(uniontypes(...))` initially.

File: base/accumulate.jl [hunk 9]
```diff
@@ -442,3 +441,21 @@ function _accumulate1!(op, B, v1, A::AbstractVector, dim::Integer)
...
 end
+
+# Internal function used to identify the widest possible eltype required for accumulate results
+function _accumulate_promote_op(op, v; init=nothing)
+    # Nested mock function that applies the `op` to each element of `v` which is necessary
+    # to find the widest return eltype.
+    # NOTE: We are just passing this to promote_op for inference and should never be run.
+    function f(op, v, init)
+        val, iter = Iterators.peel(v)
+        r = isnothing(init) ? reduce_first(op, val) : op(init, val)
```
[the remark this answers is not in the document]
Comment (rofinn) [reply base/accumulate.jl:452]: Yeah, the first option seems to give up and returns the wrong answer, but the second doesn't work because `k` needs to be defined... which is what the point of `r` is.

I really think the `promote_type(uniontypes(...)...)` has the most intuitive behaviour. It also handles the main edge case I was worried which was accidentally converting `Union{T, Missing/Nothing}` -> `Any`. Is there a particular performance issue or edge case you're concerned about?

[the remark this answers is not in the document]
Comment (vtjnash) [reply base/accumulate.jl:452]: We don't actually run this code, so it doesn't matter if k actually gets defined

[the remark this answers is not in the document]
Comment (rofinn) [reply base/accumulate.jl]: Hmm, then I'm not sure why it always return `Any`... even in simple cases like `op=+` and `v=[1, 2, 3]` 😕

[the remark this answers is not in the document]
Comment (rofinn) [reply base/accumulate.jl]: Thanks, that does seem to work. So `k` does need to be defined even though the code isn't run? Is the preference for that solution simply the fact that it produces the narrowest possible answer, where `promote_union` will return `Any` when a `Union` would suffice?

[the remark this answers is not in the document]
Comment (vtjnash) [reply base/accumulate.jl]: Yeah, my thought is that inference alone will generally pick a better type than `promote_union`, and that this seemed the most accurate model of what type we want it to compute

[the remark this answers is not in the document]
Comment (vtjnash) [reply base/accumulate.jl]: yes, `k` needed to be defined in the right scope. I had defined it before too, but it had the wrong scope then

[the remark this answers is not in the document]
Comment (rofinn) [reply base/accumulate.jl]: Sorry, I was away from my workstation for a couple weeks. The two remaining issues with the approach you suggested is that:

1. It currently doesn't address the original `Union{}` case when `op(...)` would throw an error. This happens when `k` is undefined during the `convert(promote_type(...), r)` because the `op` errors in the loop. I'm fine with adding an early exit when `k` is undefined.

2. Inference seems to give up more easily in simple cases and causes other tests to fail.
```
Expression: cumsum(Any[1, 2.3]) == [1, 3.3] == cumsum(Real[1, 2.3])::Vector{Real}
  TypeError: in typeassert, expected Vector{Real}, got a value of type Vector{Any}
```
It's less clear to me how to fix this, or whether this is an acceptable compromise.

[the remark this answers is not in the document]
Comment (vtjnash) [reply base/accumulate.jl]: yes, there could be an `isdefined` check there, but you have to be careful of how to write that because when written statically that check would always be true and result in skipping computing the desired promotion.

My other thought was that it might be possible to split `f` into 2 parts (before and after computing `k`) with the first one computing `typeof(k)`, then calling this `promote_type` directly (instead of inferring it)
```
        # next try to change `r` to that type
        r = convert(promote_type(typeof(r), typeof(k)), r)
```

My main concern with using `Base.promote_union` is that it can discard a lot of information and be quite terrible at computing the output if you have any unions in the input array. Whereas `promote_op` originally should be able to give a precise answer in those cases, which `promote_union` then discards.

[the remark this answers is not in the document]
Comment (rofinn) [reply base/accumulate.jl]: Hmm, it's not pretty, but it looks like breaking up `f` works.

1. Avoids the `isdefined` check
2. Fixes the test where inference was giving up and returning `Any`.

I'll push a commit, so you can take a look. Maybe there's a cleaner way to right it...?

**Review by vtjnash — APPROVED** [review]
I think this looks great
