### PR TITLE
fix oc lowering with return type annotations

### LINKED ISSUE #44723: `invalid syntax (gotoifnot (true) 0)` from return type conversion of an opaque closure
```julia
julia> demo(thunk)::Any = Base.Experimental.@opaque () -> true ? 1 : 2
ERROR: syntax: invalid syntax (gotoifnot (true) 0)
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> VERSION
v"1.9.0-DEV.241"
```

`Meta.@lower` throws, so I guess it happens in the frontend?

```julia
julia> Meta.@lower demo(thunk)::Any = Base.Experimental.@opaque () -> true ? 1 : 2
:($(Expr(:error, "invalid syntax (gotoifnot (true) 0)")))
```

But `fe` throws something else?

```lisp
> (fe "demo(thunk)::Any = Base.Experimental.@opaque () -> true ? 1 : 2")
error: invalid syntax (call (top getproperty) (call (top getproperty) (outerref Base) (inert Experiment
al)) (inert @opaque)) # none, line 1 begin
    nothing
    begin
        nothing
        #1 = (new #1#2)
        (unnecessary #1)
    end
end
#0 (error ("invalid syntax (call (top getproperty) (call (top getproperty) (outerref Base) (inert Exper
imental)) (inert @opaque)) # none, line 1 begin\n    nothing\n    begin\n        nothing\n        #1 =
(new #1#2)\n        (unnecessary #1)\n    end\nend"))
#1 (compile-body/compile
...
```

### PR DESCRIPTION
**Pull request by simeonschaub**
fixes #44723

### CODE REVIEW

File: test/syntax.jl [hunk 1]
```diff
@@ -3276,3 +3276,7 @@ end
     @test m.Foo.bar === 1
     @test Core.get_binding_type(m.Foo, :bar) == Any
 end
+
+# issue 44723
+demo44723(thunk)::Any = Base.Experimental.@opaque () -> true ? 1 : 2
+@test demo44723(7)() == 1
```
Comment (tkf) [inline test/syntax.jl:3282]: The argument `thunk` was not required. It was from the code before I minimize it.

```suggestion
demo44723()::Any = Base.Experimental.@opaque () -> true ? 1 : 2
@test demo44723(7)() == 1
```
