### PR TITLE
Fix left division for Hermitian sparse array and transpose/adjoint rhs

### LINKED ISSUE #27860: Left division operator fails between sparse matrices and transposed arrays
The left division operations involving a sparse matrix and a transposed/conjugated matrix produce the error
`MethodError: no method matching lu!`

```julia
using SparseArrays
sparse([2. 0.1; 0.1 2.]) \ (ones(2,2)')
sparse([2. 0.1; 0.1 2.]) \ transpose(ones(2,2))
```
I am using 0.7.0-beta.0 on Linux.
The full stack trace is copied below.

```
julia> sparse([2. 0.1; 0.1 2.]) \ (ones(2,2)')
ERROR: MethodError: no method matching lu!(::SparseMatrixCSC{Float64,Int64}, ::Val{true}; check=true)
Closest candidates are:
  lu!(::Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, Base.ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}, ::Union{Val{false}, Val{true}}; check) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:26
  lu!(::Union{LinearAlgebra.Hermitian{T,S}, LinearAlgebra.Symmetric{T,S}} where S where T, ::Union{Val{false}, Val{true}}; check) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:34
  lu!(::Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T, ::Union{Val{false}, Val{true}}; check) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:75
  ...
Stacktrace:
 [1] #lu!#92(::Bool, ::Function, ::LinearAlgebra.Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}, ::Val{true}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:35
 [2] #lu#95 at ./none:0 [inlined]
 [3] lu at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:131 [inlined] (repeats 2 times)
 [4] \(::LinearAlgebra.Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}, ::LinearAlgebra.Adjoint{Float64,Array{Float64,2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/generic.jl:887
 [5] \(::SparseMatrixCSC{Float64,Int64}, ::LinearAlgebra.Adjoint{Float64,Array{Float64,2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/SparseArrays/src/linalg.jl:935
 [6] top-level scope at none:0

julia> sparse([2. 0.1; 0.1 2.]) \ transpose(ones(2,2))
ERROR: MethodError: no method matching lu!(::SparseMatrixCSC{Float64,Int64}, ::Val{true}; check=true)
Closest candidates are:
  lu!(::Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, Base.ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}, ::Union{Val{false}, Val{true}}; check) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:26
  lu!(::Union{LinearAlgebra.Hermitian{T,S}, LinearAlgebra.Symmetric{T,S}} where S where T, ::Union{Val{false}, Val{true}}; check) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:34
  lu!(::Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T, ::Union{Val{false}, Val{true}}; check) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:75
  ...
Stacktrace:
 [1] #lu!#92(::Bool, ::Function, ::LinearAlgebra.Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}, ::Val{true}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:35
 [2] #lu#95 at ./none:0 [inlined]
 [3] lu at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:131 [inlined] (repeats 2 times)
 [4] \(::LinearAlgebra.Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}, ::LinearAlgebra.Transpose{Float64,Array{Float64,2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/generic.jl:887
 [5] \(::SparseMatrixCSC{Float64,Int64}, ::LinearAlgebra.Transpose{Float64,Array{Float64,2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/SparseArrays/src/linalg.jl:935
 [6] top-level scope at none:0

julia> versioninfo()

Julia Version 0.7.0-beta.0
Commit f41b1ecaec (2018-06-24 01:32 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by goggle**
This partly addresses JuliaLang/LinearAlgebra.jl#538.
The other mentioned issues in this thread are still unsolved, so JuliaLang/LinearAlgebra.jl#538 should either remain open or the other mentioned issues should get their own tickets, even if this gets merged.

### CODE REVIEW

**Review by dkarrasch — CHANGES_REQUESTED** [review]
This is a good start, but the tests are probably tricky and require some more work, to really test the added methods.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 1]
```diff
@@ -804,7 +804,15 @@ function Dense{T}(A::StridedVecOrMat) where T<:VTypes
     end
     d
 end
-function Dense(A::StridedVecOrMat)
+function Dense{T}(A::Union{Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}) where T<:VTypes
+    d = allocate_dense(size(A, 1), size(A, 2), size(A, 1), T)
+    s = unsafe_load(pointer(d))
+    for i in 1:length(A)
+        unsafe_store!(s.x, A[i], i)
```
[the remark this answers is not in the document]
Comment (goggle) [reply stdlib/SuiteSparse/src/cholmod.jl]: I have modified this code, so that it uses `eachindex` now. As far as I understand this, it should not depend on being one-indexed anymore.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 2]
```diff
@@ -1716,7 +1737,7 @@ function \(A::RealHermSymComplexHermF64SSL, B::StridedVecOrMat)
         end
     end
 end
-function \(adjA::Adjoint{<:Any,<:RealHermSymComplexHermF64SSL}, B::StridedVecOrMat)
+function \(adjA::Adjoint{<:Any, <:RealHermSymComplexHermF64SSL}, B::StridedVecOrMatInclAdjAndTrans)
```
[the remark this answers is not in the document]
Comment (goggle) [reply stdlib/SuiteSparse/src/cholmod.jl]: I have reverted this space; didn't intended to modify it in the first place :smile: .

File: stdlib/SuiteSparse/test/cholmod.jl [hunk 3]
```diff
@@ -855,3 +855,18 @@ end
         @test !issuccess(ldlt!(F, M; check = false))
     end
 end
+
+@testset "Issue #27860" begin
+    A = sparse(Float64[2.0 0.1; 0.1 2.0])
```
[the remark this answers is not in the document]
Comment (goggle) [reply stdlib/SuiteSparse/test/cholmod.jl]: I have modified the tests according to your sketch above. But I didn't understand, what you wanted to show with `m`, so I left it out for now. In your example, `m` is `1 x 1` but the RHS is `2 x 1` or `2 x 2`, so the dimensions do not match...

**Comment by goggle** [comment]
Thanks for the review @dkarrasch. I have made some changes, feel free to have a look at it again.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (dkarrasch) [reply stdlib/SuiteSparse/src/cholmod.jl]: I was actually thinking that it does, via `unsafe_store!`, and that the same applies to the method above that you haven’t touched. In that sense, I thought your approach was „more correct“ than what we have above. But I’m not familiar with `unsafe_store!` and `unsafe_load`.

File: stdlib/SuiteSparse/test/cholmod.jl (hunk 3 above)
[the remark this answers is not in the document]
Comment (dkarrasch) [reply stdlib/SuiteSparse/test/cholmod.jl]: The rhs’s for `m` (or `a`) are transposes of vectors, so they are row vectors (1x2). I don’t see any other way of testing the `Adjoint{<:Any,<:Vector}` methods, of which I’m not so sure if we really need them anyway.

File: stdlib/SuiteSparse/test/cholmod.jl [hunk 4]
```diff
@@ -855,3 +855,13 @@ end
         @test !issuccess(ldlt!(F, M; check = false))
     end
 end
+
+@testset "Issue #27860" begin
+    for typeA in (Float64, ComplexF64), typeB in (Float64, ComplexF64), transform in (adjoint, transpose)
+        A = sparse(typeA[2.0 0.1; 0.1 2.0])
+        B = randn(typeB, 2, 2)
+        b = randn(typeB, 1, 2)
```
Comment (dkarrasch) [inline stdlib/SuiteSparse/test/cholmod.jl]: This is a `Matrix`, and `transform(b)` is an `Adjoint/Transpose{<:Any,<:AbstractMatrix}`, not `Adjoint/Transpose{<:Any,<:AbstractVector}`.

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (goggle) [reply stdlib/SuiteSparse/src/cholmod.jl]: In the initial version
```julia
for i in 1:length(A)
    unsafe_store!(s.x, A[i], i)
end
```
I have assumed that the array `A` is 1-indexed, because I have accessed `A` (inside the loop) at `1`, `2`, ..., `length(A)`.

In the current version
```julia
for (i, c) in enumerate(eachindex(A))
    unsafe_store!(s.x, A[c], i)
end
```
I access `A` at indices given by the `eachindex` function, so they should be valid, even if `A` is not 1-indexed.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 5]
```diff
@@ -804,7 +804,15 @@ function Dense{T}(A::StridedVecOrMat) where T<:VTypes
     end
     d
 end
-function Dense(A::StridedVecOrMat)
+function Dense{T}(A::Union{Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}) where T<:VTypes
+    d = allocate_dense(size(A, 1), size(A, 2), size(A, 1), T)
+    s = unsafe_load(pointer(d))
```
Comment (yuyichao) [inline stdlib/SuiteSparse/src/cholmod.jl]: `GC.@preserve d` until the function returns.

**Review by yuyichao — CHANGES_REQUESTED** [review]

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (dkarrasch) [reply stdlib/SuiteSparse/src/cholmod.jl]: I understand all that. But assume that the first index is `-100`. Then I’m not sure that `unsafe_store!` will work correctly, at least judging by its docstring.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 6]
```diff
@@ -806,7 +806,7 @@ function Dense{T}(A::StridedVecOrMat) where T<:VTypes
 end
 function Dense{T}(A::Union{Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}) where T<:VTypes
     d = allocate_dense(size(A, 1), size(A, 2), size(A, 1), T)
-    s = unsafe_load(pointer(d))
+    GC.@preserve d s = unsafe_load(pointer(d))
```
Comment (yuyichao) [inline stdlib/SuiteSparse/src/cholmod.jl]: You need to preserve d "until the function returns." since you are still using the pointer associated with `d`.
The function above also seems to be missing it.

**Review by yuyichao — CHANGES_REQUESTED** [review]

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (goggle) [reply stdlib/SuiteSparse/src/cholmod.jl]: It seems to work fine for such cases:
```julia
julia> using OffsetArrays

julia> import SuiteSparse.CHOLMOD: allocate_dense

julia> A = OffsetArray{Float64}(undef, -100:-95, -100:-95)
       for (i,c) in enumerate(eachindex(A))
            A[c] = i
       end

julia> A
6×6 OffsetArray(::Array{Float64,2}, -100:-95, -100:-95) with eltype Float64 with indices -100:-95×-100:-95:
 1.0   7.0  13.0  19.0  25.0  31.0
 2.0   8.0  14.0  20.0  26.0  32.0
 3.0   9.0  15.0  21.0  27.0  33.0
 4.0  10.0  16.0  22.0  28.0  34.0
 5.0  11.0  17.0  23.0  29.0  35.0
 6.0  12.0  18.0  24.0  30.0  36.0

julia> B = A'
6×6 LinearAlgebra.Adjoint{Float64,OffsetArray{Float64,2,Array{Float64,2}}} with indices -100:-95×-100:-95:
  1.0   2.0   3.0   4.0   5.0   6.0
  7.0   8.0   9.0  10.0  11.0  12.0
 13.0  14.0  15.0  16.0  17.0  18.0
 19.0  20.0  21.0  22.0  23.0  24.0
 25.0  26.0  27.0  28.0  29.0  30.0
 31.0  32.0  33.0  34.0  35.0  36.0

julia> d = allocate_dense(6, 6, 6, Float64)
       GC.@preserve d begin
           s = unsafe_load(pointer(d))
           for (i,c) in enumerate(eachindex(B))
               unsafe_store!(s.x, B[c], i)
           end
       end

julia> d
6×6 SuiteSparse.CHOLMOD.Dense{Float64}:
  1.0   2.0   3.0   4.0   5.0   6.0
  7.0   8.0   9.0  10.0  11.0  12.0
 13.0  14.0  15.0  16.0  17.0  18.0
 19.0  20.0  21.0  22.0  23.0  24.0
 25.0  26.0  27.0  28.0  29.0  30.0
 31.0  32.0  33.0  34.0  35.0  36.0
```
@dkarrasch Do you think further changes are needed here?

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 7]
```diff
@@ -798,13 +798,25 @@ get_perm(FC::FactorComponent) = get_perm(Factor(FC))
...
     end
     d
 end
-function Dense(A::StridedVecOrMat)
+function Dense{T}(A::Union{Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}) where T<:VTypes
+    d = allocate_dense(size(A, 1), size(A, 2), size(A, 1), T)
+    GC.@preserve d begin
+        s = unsafe_load(pointer(d))
+        for (i, c) in enumerate(eachindex(A))
+            unsafe_store!(s.x, A[c], i)
```
Comment (dkarrasch) [inline stdlib/SuiteSparse/src/cholmod.jl]: Ok, I misread that earlier. It works, because the `i`s run from 1 to `length(A)`, and not through the indices of `A` (like `c`). I wonder if we should take the same approach in other method above, I mean with `enumerate(eachindex(A))` etc.

File: stdlib/SuiteSparse/test/cholmod.jl (hunk 4 above)
Comment (dkarrasch) [reply stdlib/SuiteSparse/test/cholmod.jl]: With the `Vector` methods deleted, I’m no longer sure the `b` tests add anything. At least, we don’t seem to test previously untested methods.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 8]
```diff
@@ -798,13 +798,25 @@ get_perm(FC::FactorComponent) = get_perm(Factor(FC))
...
+        end
+    end
+    d
+end
```
Comment (dkarrasch) [inline stdlib/SuiteSparse/src/cholmod.jl]: It seems to me that these two methods are exactly the same. So you could introduce
```julia
const StridedVecOrMatInclAdjAndTrans = Union{StridedVecOrMat, Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}
```
around here, and have the method as
```julia
function Dense{T}(A::StridedVecOrMatInclAdjAndTrans) where T<:VTypes
```

**Review by dkarrasch — CHANGES_REQUESTED** [review]
Sorry for being nitpicking, but I just realized one more thing. Everything else looks great.

**Comment by goggle** [comment]
@dkarrasch No need to apologize, I appreciate to have a careful review! Maintaining good code quality is important IMO.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 9]
```diff
@@ -796,15 +796,18 @@ get_perm(FC::FactorComponent) = get_perm(Factor(FC))
...
 
 # Conversion/construction
-function Dense{T}(A::StridedVecOrMat) where T<:VTypes
-    d = allocate_dense(size(A, 1), size(A, 2), stride(A, 2), T)
-    s = unsafe_load(pointer(d))
-    for i in eachindex(A)
-        unsafe_store!(s.x, A[i], i)
+const StridedVecOrMatInclAdjAndTrans = Union{StridedVecOrMat, Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}
+function Dense{T}(A::StridedVecOrMatInclAdjAndTrans) where T<:VTypes
+    d = allocate_dense(size(A, 1), size(A, 2), size(A, 1), T)
```
Comment (dkarrasch) [inline stdlib/SuiteSparse/src/cholmod.jl]: This is outside of my area of expertise, but I would rather not change the `stride(A, 2)` we had before to `size(A, 1)`. I guess it was written for a reason.

File: stdlib/SuiteSparse/src/cholmod.jl [hunk 10]
```diff
@@ -1703,7 +1712,8 @@ const RealHermSymComplexHermF64SSL = Union{
     Symmetric{Float64,SparseMatrixCSC{Float64,SuiteSparse_long}},
     Hermitian{Float64,SparseMatrixCSC{Float64,SuiteSparse_long}},
     Hermitian{Complex{Float64},SparseMatrixCSC{Complex{Float64},SuiteSparse_long}}}
-function \(A::RealHermSymComplexHermF64SSL, B::StridedVecOrMat)
+const StridedVecOrMatInclAdjAndTrans = Union{StridedVecOrMat, Adjoint{<:Any, <:StridedVecOrMat}, Transpose{<:Any, <:StridedVecOrMat}}
```
Comment (dkarrasch) [inline stdlib/SuiteSparse/src/cholmod.jl]: With the above definition, this one is obsolete now, isn't it?

**Review by dkarrasch — CHANGES_REQUESTED** [review]

File: stdlib/SuiteSparse/src/cholmod.jl (hunk 9 above)
Comment (goggle) [reply stdlib/SuiteSparse/src/cholmod.jl]: Yeah, that was that small difference between the two `Dense{T}` methods, that still existed. I cannot use `stride(A, 2)` here, because `stride` is not defined for `Adjoint` or `Transpose`... So I see 2 possibilities:

1. Revert the last change and use two `Dense{T}` methods again.
2. Keep it as it is.

What should I do?

Comment (dkarrasch) [reply stdlib/SuiteSparse/src/cholmod.jl]: I thought I tested it because I wasn't sure myself, but I must have messed it up. I now see that there is no `stride` function for `Adjoint`s and `Transpose`s. Sorry for that. Then I'd suggest to have two methods again, just to make sure we don't change behavior of existing methods unnecessarily (beyond the `GC.@preserve` stuff).

**Comment by goggle** [comment]
@dkarrasch You seem to have pushed something onto my branch. Was this an accident?
Also, is this ready to be merged?

**Comment by dkarrasch** [comment]
Oh yes, I resolved the merge conflict, with the intention to merge right afterwards... and forgot! 🤣 To make matters worse, I have introduced an issue by missing an `end` somewhere in the `cholmod` test files. 😇 I'm sorry, I didn't want to bother you with the "trivial" merge conflict. I quickly fixed it now, and will merge after tests pass.

**Review by dkarrasch — APPROVED** [review]
