### PR TITLE
Deepcopy Fix

### LINKED ISSUE #56775: deepcopy with non-trivial circular references fails in 1.11.2
Not sure if this is just a symptom of deepcopy not having much in terms of guaranteed behaviour, but it is no longer consistent with serialize => deserialize.

I tried to recreate it with a simpler structure (e.g. just Arrays which contain themselves) but couldn't. This is the most stripped down version I could create:

```julia
struct ProblemStruct{T}
    label::String # Just helps a bit when debugging
    inputs::T
end

using Serialization

let 
    problem = ProblemStruct("problem", ProblemStruct[])

    next = ProblemStruct("next", [problem])
    push!(problem.inputs, next) # Make a circular reference

    println("Original:")
    @show problem === next.inputs[1]
    @show problem.inputs[1] === next

    problemc, nextc = deepcopy((problem, next))
    println("\ndeepcopy:")
    @show problemc === nextc.inputs[1]
    @show problemc.inputs[1] === nextc

    println("\nserde:")
    problemds, nextds = let 
        io = PipeBuffer()
        serialize(io, (problem, next))
        deserialize(io)
    end
    @show problemds === nextds.inputs[1]
    @show problemds.inputs[1] === nextds

end;
```

Prints the following in Julia 1.11.2:
```
Original:
problem === next.inputs[1] = true    
problem.inputs[1] === next = true    

deepcopy:
problemc === nextc.inputs[1] = false 
problemc.inputs[1] === nextc = true  

serde:
problemds === nextds.inputs[1] = true
problemds.inputs[1] === nextds = true
```

And this in Julia 1.10.7:
```
Original:
problem === next.inputs[1] = true
problem.inputs[1] === next = true

deepcopy:
problemc === nextc.inputs[1] = true
problemc.inputs[1] === nextc = true

serde:
problemds === nextds.inputs[1] = true
problemds.inputs[1] === nextds = true
```

Fwiw: I can work around the problem on my side with the following:
```julia
function Base.deepcopy_internal(v::Vector{ProblemStruct}, stackdict::IdDict)
    v in keys(stackdict) && return stackdict[v]
    newv = similar(v)
    stackdict[v] = newv
    for (i, vi) in zip(eachindex(newv), v)
        newv[i] = Base.deepcopy_internal(vi, stackdict)
    end
    return newv
end
```

Versioninfo 1.11.2:
```
Julia Version 1.11.2
Commit 5e9a32e7af (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, haswell)
Threads: 12 default, 0 interactive, 6 GC (on 12 virtual cores)
Environment:
  JULIA_DEPOT_PATH = E:/Programs/julia/.julia
  JULIA_PKG_DEVDIR = E:/Programs/julia/.julia/dev
  JULIA_EDITOR = code
```

Versioninfo 1.10.7:
```
Julia Version 1.10.7
Commit 4976d05258 (2024-11-26 15:57 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, haswell)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_DEPOT_PATH = E:/Programs/julia/.julia
  JULIA_PKG_DEVDIR = E:/Programs/julia/.julia/dev
```

### PR DESCRIPTION
**Pull request by willtebbutt**
Resolves #56775 . Credit for this fix rests entirely with @bbrehm .

I have a regression test -- see https://github.com/JuliaLang/julia/issues/56775#issuecomment-2531482733 -- but I'm unsure where to put it. If someone could point me towards an appropriate location for the test, that would be very helpful!

edit: CC @nsajko

### CODE REVIEW

File: base/deepcopy.jl [hunk 1]
```diff
@@ -124,7 +124,8 @@ end
     if haskey(stackdict, x)
         return stackdict[x]::typeof(x)
     end
-    stackdict[x] = $(Expr(:new, :(Array{T, N}), :(deepcopy_internal(x.ref, stackdict)), :(x.size)))
+    copied = $(Expr(:new, :(Array{T, N}), :(deepcopy_internal(x.ref, stackdict)), :(x.size)))
+    get!(stackdict, x, copied)::typeof(x)
```
Comment (bbrehm) [inline base/deepcopy.jl:128]: I think I'd put in some short comment here -- sure there's always git blame, but the double lookup may otherwise seem wrong to the naive reader.

**Comment by oscardssmith** [comment]
Calling `setfield!` on an array is fine (so long as you don't violate the invariant)

**Comment by willtebbutt** [comment]
Cool. I'll change the fix.

**Comment by willtebbutt** [comment]
Fix modified to following @LilithHafner 's suggestion, which I agree is probably cleaner. Test also fixed to actually be a test, rather than just evaluating a `Bool`.

**Comment by vtjnash** [comment]
Is this triggering a Revise.jl internal bug?

**Comment by willtebbutt** [comment]
It looks like the `@eval` statement I had (accidentally) left in the code was causing some kind of problem. The latest commit appears to resolve.

File: test/copy.jl [hunk 2]
```diff
@@ -253,8 +253,19 @@ end
...
+end
+
 @testset "deepcopy_internal arrays" begin
     @test (@inferred Base.deepcopy_internal(zeros(), IdDict())) == zeros()
+
+    # issue 56775
+    p = make_circular_reference_array_56775()
+    p2 = deepcopy(p)
+    @test p2 === p2[1]
 end
```
Comment (LilithHafner) [inline test/copy.jl:269]: I'd put this in a separate testset because it is an end to end test, not a deepcopy_internal test:
```suggestion
@testset "circular reference arrays" begin
    # issue 56775
    p = Any[nothing]
    p[1] = p
    p2 = deepcopy(p)
    @test p2 === p2[1]
end

@testset "deepcopy_internal arrays" begin
    @test (@inferred Base.deepcopy_internal(zeros(), IdDict())) == zeros()
end
```

Comment (willtebbutt) [reply test/copy.jl:269]: Good point!

**Comment by willtebbutt** [comment]
It _looks_ to me like the current test failures are unrelated to this PR, but someone who knows more about Julia's CI should probably take a look.

File: test/copy.jl [hunk 3]
```diff
@@ -253,6 +253,14 @@ end
     @test copyto!(s, String[]) == [1, 2] # No error
 end
 
+@testset "circular reference arrays" begin
+    # issue 56775
+    p = Any[nothing]
+    p[1] = p
+    p2 = deepcopy(p)
+    @test p2 === p2[1]
```
Comment (nsajko) [inline test/copy.jl:261]: Wouldn't hurt, I guess:

```suggestion
    @test p2 === p2[1]
    @test p2 !== p
```

**Review by nsajko — APPROVED** [review]
