### PR TITLE
Pkg3: workaround windows not deleting folder with open files

### LINKED ISSUE #26407: intermittent permissions error in Pkg3 test on AV
E.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.25328/job/aqs54cg5beawsak0

```
3343 Error in testset Pkg3/pkg:
3344 Error During Test at C:\projects\julia\julia-2de83a3277\share\julia\test\testdefs.jl:19
3345  Got exception LoadError("C:\\projects\\julia\\julia-2de83a3277\\share\\julia\\site\\v0.7\\Pkg3\\test\\pkg.jl", 152, LoadError("C:\\projects\\julia\\julia-2de83a3277\\share\\julia\\site\\v0.7\\Pkg3\\test\\repl.jl", 23, unlink: operation not permitted (EPERM))) outside of a @test
3346  LoadError: LoadError: unlink: operation not permitted (EPERM)
3347  Stacktrace:
3348   [1] uv_error at .\libuv.jl:68 [inlined]
3349   [2] unlink(::String) at .\file.jl:549
3350   [3] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:151
3351   [4] #rm at .\<missing>:0 [inlined]
3352   [5] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:161
3353   [6] #rm at .\<missing>:0 [inlined]
3354   [7] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:161
3355   [8] #rm at .\<missing>:0 [inlined]
3356   [9] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:161
3357   [10] #rm at .\<missing>:0 [inlined]
3358   [11] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:161
3359   [12] #rm at .\<missing>:0 [inlined]
3360   [13] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:161
3361   [14] #rm at .\<missing>:0 [inlined]
3362   [15] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:161
3363   [16] #rm at .\<missing>:0 [inlined]
3364   [17] mktempdir(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##9#14")){String}, ::String) at .\file.jl:443
3365   [18] mktempdir at .\file.jl:439 [inlined]
3366   [19] (::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##8#13")){String,String,String})() at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\repl.jl:77
3367   [20] cd(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##8#13")){String,String,String}, ::String) at .\file.jl:61
3368   [21] (::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##7#12")){String})() at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\repl.jl:71
3369   [22] withenv(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##7#12")){String}, ::Pair{String,String}, ::Vararg{Pair{String,String},N} where N) at .\env.jl:156
3370   [23] (::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##6#11")))() at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\repl.jl:64
3371   [24] cd(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##6#11")), ::String) at .\file.jl:61
3372   [25] #5 at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\repl.jl:23 [inlined]
3373   [26] (::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##2#4")){String,getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##5#10"))})(::String) at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\utils.jl:18
3374   [27] mktempdir(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##2#4")){String,getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##5#10"))}, ::String) at .\file.jl:441
3375   [28] mktempdir at .\file.jl:439 [inlined]
3376   [29] #1 at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\utils.jl:11 [inlined]
3377   [30] mktempdir(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##1#3")){getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##5#10"))}, ::String) at .\file.jl:441
3378   [31] mktempdir at .\file.jl:439 [inlined]
3379   [32] temp_pkg_dir(::getfield(Main.Test57Main_Pkg3_pkg.OperationsTest.REPLTests, Symbol("##5#10"))) at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\utils.jl:10
3380   [33] top-level scope
3381   [34] include(::Module, ::String) at .\boot.jl:306
3382   [35] include_relative(::Module, ::String) at .\loading.jl:1072
3383   [36] include at .\sysimg.jl:29 [inlined]
3384   [37] include(::String) at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\pkg.jl:1
3385   [38] top-level scope
3386   [39] include(::Module, ::String) at .\boot.jl:306
3387   [40] include_relative(::Module, ::String) at .\loading.jl:1072
3388   [41] include at .\sysimg.jl:29 [inlined]
3389   [42] include(::String) at C:\projects\julia\julia-2de83a3277\share\julia\test\testdefs.jl:13
3390   [43] macro expansion at C:\projects\julia\julia-2de83a3277\share\julia\test\testdefs.jl:22 [inlined]
3391   [44] macro expansion at C:\projects\julia\usr\share\julia\site\v0.7\Test\src\Test.jl:1022 [inlined]
3392   [45] macro expansion at C:\projects\julia\julia-2de83a3277\share\julia\test\testdefs.jl:21 [inlined]
3393   [46] macro expansion at .\util.jl:289 [inlined]
3394   [47] top-level scope at .\<missing>:19
3395   [48] eval(::Module, ::Any) at .\boot.jl:309
3396   [49] #runtests#5(::UInt128, ::Function, ::String, ::String, ::Bool) at C:\projects\julia\julia-2de83a3277\share\julia\test\testdefs.jl:25
3397   [50] #runtests at .\<missing>:0 [inlined] (repeats 2 times)
3398   [51] (::getfield(Distributed, Symbol("##120#122")){Distributed.CallMsg{:call_fetch}})() at C:\projects\julia\usr\share\julia\site\v0.7\Distributed\src\process_messages.jl:269
3399   [52] run_work_thunk(::getfield(Distributed, Symbol("##120#122")){Distributed.CallMsg{:call_fetch}}, ::Bool) at C:\projects\julia\usr\share\julia\site\v0.7\Distributed\src\process_messages.jl:56
3400   [53] macro expansion at C:\projects\julia\usr\share\julia\site\v0.7\Distributed\src\process_messages.jl:269 [inlined]
3401   [54] (::getfield(Distributed, Symbol("##119#121")){Distributed.CallMsg{:call_fetch},Distributed.MsgHeader,Sockets.TCPSocket})() at .\event.jl:92
3402  in expression starting at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\repl.jl:23
3403  in expression starting at C:\projects\julia\julia-2de83a3277\share\julia\site\v0.7\Pkg3\test\pkg.jl:152
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/26407.

Should be fixed better but for now, should be ok.

### CODE REVIEW

File: stdlib/Pkg3/test/repl.jl [hunk 1]
```diff
@@ -74,11 +74,11 @@ temp_pkg_dir() do project_path; cd(project_path) do
...
-                mktempdir() do depot_dir
-                    pushfirst!(DEPOT_PATH, depot_dir)
-                    pkg"up --fixed"
-                    @test Pkg3.installed()[pkg2] == v"0.2.0"
-                end
+                depot_dir = mktempdir()
+                pushfirst!(DEPOT_PATH, depot_dir)
+                pkg"up --fixed"
+                @test Pkg3.installed()[pkg2] == v"0.2.0"
+                try rm(depot_dir; recurisve=true) end
```
Comment (vchuravy) [inline stdlib/Pkg3/test/repl.jl]: Typo in recursive?

Comment (KristofferC) [reply stdlib/Pkg3/test/repl.jl]: That's the problem with `try`...

Comment (KristofferC) [reply stdlib/Pkg3/test/repl.jl]: https://github.com/JuliaLang/julia/commit/40f64e590ffd3f03836a7a2b13c53b86be4a7856
