### PR TITLE
wcsftime instead of strftime for different locales (#27239)

### LINKED ISSUE #27239: PCRE.exec error during REPL startup error with non-Unicode locales
With 32bit version on Windows 10:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.5161 (2018-05-22 16:48 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit c9583e76d5* (1 day old master)
|__/                   |  i686-w64-mingw32

ERROR: PCRE.exec error: UTF-8 error: isolated byte with 0x80 bit set
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] exec at .\pcre.jl:137 [inlined]
 [3] match(::Regex, ::String, ::Int32, ::UInt32) at .\regex.jl:197
 [4] match at .\regex.jl:195 [inlined]
 [5] match at .\regex.jl:210 [inlined]
 [6] hist_from_file(::REPL.REPLHistoryProvider, ::IOStream, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:407
 [7] setup_interface(::REPL.LineEditREPL, ::Bool, ::Array{Dict{Any,Any},1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:845
 [8] #setup_interface#49(::Bool, ::Array{Dict{Any,Any},1}, ::Function, ::REPL.LineEditREPL) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:756
 [9] setup_interface(::REPL.LineEditREPL) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:756
 [10] (::getfield(Pkg3, Symbol("##1#2")))(::REPL.LineEditREPL) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg3\src\Pkg3.jl:58
 [11] __atreplinit(::REPL.LineEditREPL) at .\client.jl:309
 [12] (::getfield(Base, Symbol("#inner#2")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},typeof(Base.__atreplinit),Tuple{REPL.LineEditREPL}})() at .\essentials.jl:667
 [13] #invokelatest#1 at .\essentials.jl:668 [inlined]
 [14] invokelatest at .\essentials.jl:667 [inlined]
 [15] _atreplinit at .\client.jl:316 [inlined]
 [16] (::getfield(Base, Symbol("##875#877")){Bool,Bool,Bool,Bool})(::Module) at .\client.jl:352
 [17] (::getfield(Base, Symbol("#inner#2")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},getfield(Base, Symbol("##875#877")){Bool,Bool,Bool,Bool},Tuple{Module}})() at .\essentials.jl:667
 [18] #invokelatest#1 at .\essentials.jl:668 [inlined]
 [19] invokelatest at .\essentials.jl:667 [inlined]
 [20] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:337
 [21] exec_options(::Base.JLOptions) at .\client.jl:275
 [22] _start() at .\client.jl:424

[ Info: Disabling history file for this session
julia> versioninfo()
Julia Version 0.7.0-DEV.5161
Commit c9583e76d5* (2018-05-22 16:48 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)

julia>
```

With 64bit version on Windows 10:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.5170 (2018-05-22 22:52 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6945f24d53* (0 days old master)
|__/                   |  x86_64-w64-mingw32

ERROR: PCRE.exec error: UTF-8 error: isolated byte with 0x80 bit set
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] exec at .\pcre.jl:137 [inlined]
 [3] match(::Regex, ::String, ::Int64, ::UInt32) at .\regex.jl:197
 [4] match at .\regex.jl:195 [inlined]
 [5] match at .\regex.jl:210 [inlined]
 [6] hist_from_file(::REPL.REPLHistoryProvider, ::IOStream, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:407
 [7] setup_interface(::REPL.LineEditREPL, ::Bool, ::Array{Dict{Any,Any},1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:845
 [8] #setup_interface#49(::Bool, ::Array{Dict{Any,Any},1}, ::Function, ::REPL.LineEditREPL) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:756
 [9] setup_interface(::REPL.LineEditREPL) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:756
 [10] (::getfield(Pkg3, Symbol("##1#2")))(::REPL.LineEditREPL) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg3\src\Pkg3.jl:58
 [11] __atreplinit(::REPL.LineEditREPL) at .\client.jl:309
 [12] (::getfield(Base, Symbol("#inner#2")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},typeof(Base.__atreplinit),Tuple{REPL.LineEditREPL}})() at .\essentials.jl:667
 [13] #invokelatest#1 at .\essentials.jl:668 [inlined]
 [14] invokelatest at .\essentials.jl:667 [inlined]
 [15] _atreplinit at .\client.jl:316 [inlined]
 [16] (::getfield(Base, Symbol("##878#880")){Bool,Bool,Bool,Bool})(::Module) at .\client.jl:352
 [17] (::getfield(Base, Symbol("#inner#2")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},getfield(Base, Symbol("##878#880")){Bool,Bool,Bool,Bool},Tuple{Module}})() at .\essentials.jl:667
 [18] #invokelatest#1 at .\essentials.jl:668 [inlined]
 [19] invokelatest at .\essentials.jl:667 [inlined]
 [20] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:337
 [21] exec_options(::Base.JLOptions) at .\client.jl:275
 [22] _start() at .\client.jl:424

[ Info: Disabling history file for this session
julia> versioninfo()
Julia Version 0.7.0-DEV.5170
Commit 6945f24d53* (2018-05-22 22:52 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)

julia>
```
I deleted `%USERPROFILE%\.julia_history` yet same error occurs.

### PR DESCRIPTION
**Pull request by yeonsookimdev**
Fix #27239

The problem was invalid UTF-8 characters from `strftime()`  depending on Windows system locales.
Solution is using `wcsftime()` to get UTF-16 and `transcode()` it into UTF-8 on Windows.

### CODE REVIEW

**Review by Keno — APPROVED** [review]

**Comment by Keno** [comment]
Add a test?

File: base/libc.jl [hunk 1]
```diff
@@ -170,12 +170,24 @@ library.
...
+# On Windows use wcsftime instead of strftime to support different locales
+if Sys.iswindows()
+    function wcsftime(fmt::AbstractString, tm::TmStruct)
+        wctimestr = Vector{Cwchar_t}(undef, 128)
+        n = ccall(:wcsftime, Csize_t, (Ptr{Cwchar_t}, Csize_t, Cwstring, Ref{Libc.TmStruct}),
+           wctimestr, length(wctimestr), fmt, tm)
+        n == 0 && return ""
+        return transcode(String, wctimestr[1:n])
+    end
+    strftime(fmt::AbstractString, tm::TmStruct) = wcsftime(fmt, tm)
```
Comment (ararslan) [inline base/libc.jl]: Rather than defining both `strftime` and `wcsftime`, you could just call the function `strftime`. Currently you're effectively defining two identical functions on Windows.

**Comment by ararslan** [comment]
Yep, I think test/misc.jl would be a fine place for it. 🙂

**Comment by StefanKarpinski** [comment]
Commentary: https://discourse.julialang.org/t/strftime-strptime-bug-27239-is-present-on-all-platforms-not-just-windows/11191.

**Comment by alkorang** [comment]
> Commentary: https://discourse.julialang.org/t/strftime-strptime-bug-27239-is-present-on-all-platforms-not-just-windows/11191.

The comment from @ScottPJones is that this can happen in any system with different locales other than `UTF-8`, For example on the Mac,
```
julia> setlocale(lc) = unsafe_string(ccall((:setlocale,"libc"), Cstring,(Cint,Cstring),0,lc))
setlocale (generic function with 1 method)
julia> setlocale("ko_KR.UTF-8")
"ko_KR.UTF-8"

julia> Libc.strftime("%Y-%m-%d %A %H:%M:%S %Z", time())
"2018-05-28 월요일 02:46:27 EDT"

julia> setlocale("ko_KR.CP949")
"ko_KR.CP949"

julia> Libc.strftime("%Y-%m-%d %A %H:%M:%S %Z", time())
"2018-05-28 \xbf\xf9\xbf\xe4\xc0\xcf 02:46:36 EDT"
```

So I changed the title.

**Comment by alkorang** [comment]
> Yep, I think test/misc.jl would be a fine place for it. 🙂

I added tests in `test/misc.jl`.

**Comment by alkorang** [comment]
@ararslan 
Nothing wrong. I pressed the close button by mistake....

**Comment by ararslan** [comment]
Happens to the best of us!

**Comment by alkorang** [comment]
It finally passed all checks after more rebasing!
@Keno @ararslan 
Could you review the tests and merge this pr?

**Comment by m-j-w** [comment]
Any chance this gets merged soon?  Currently 0.7 is not really usable on Win 10 with non-english locale. Thanks!

**Comment by KristofferC** [comment]
Let's rerun tests and merge when CI is green.
