### PR TITLE
RFC: remove repl prompt prefix before parsing

### LINKED ISSUE #16383: Accidentally pasting a "julia>" command leaves julia in a broken state
I realize this is not strictly a bug due to being able to define new comparison operators with infix notation but it is a bit unfortunate:

```jl
julia> julia> A = 2 # Accidentally included the `julia>` from pasting code, REPL is now hosed
WARNING: module Main should explicitly import > from Base
WARNING: Method definition >(Any, Any) in module Base at operators.jl:40 overwritten in module Main at REPL[1]:1.
> (generic function with 2 methods)

julia> "foo" > 3 # Wut?
2

# Let's try to exit this demon REPL
julia> {Ctrl + D} WARNING: Caught an exception in the keymap:
ERROR: TypeError: non-boolean (Int64) used in boolean context
# Nope!

julia> >1,2
ERROR: syntax: ">" is not a unary operatorSYSTEM: show(lasterr) caused an error
```

Feel free to close if this is considered a non issue.

### PR DESCRIPTION
**Pull request by KristofferC**
It is common to encounter example code that is posted with the REPL prefix included (typically `julia>`). This occurs in manual, doc tests and in forum posts etc. Usually one wants to quickly run this code in the REPL but then has to manually remove all the prompt prefixes first which can be a bit annoying.

This PR simply checks if the statement being evaluated in the REPL starts with the REPL prefix and in that case removes it.

As an example pasting this code block:

``` jl
julia> const x = 1;

julia> function foo(x)
           return x + 1
       end;

julia> type X
       x::Int
       end;
```

will be equivalent to pasting it without the `julia>` prefixes.

This is also implemented for the other REPL modes.

fixes https://github.com/JuliaLang/julia/issues/16383

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @StefanKarpinski because of https://github.com/JuliaLang/julia/issues/16383#issuecomment-219443555

>I've considered in the past automatically detecting leading julia> and then stripping the indent from the following lines so so that you can just paste REPL transcripts back into the REPL and have them work. Not sure that's a good idea though and of course it doesn't help other REPL modes unless we handle them too (and switch to the named REPL mode automatically?).

**Comment by Keno** [comment]
Maybe activate this only in the bracketed paste mode parser?

**Comment by KristofferC** [comment]
That seems like a good idea. I will wait a bit with updates to the PR until there is more feedback regarding doing this at all but will change it later if people are positive to the idea in general.

**Comment by omus** [comment]
Is the `julia>` prompt saved in the command history?

**Comment by StefanKarpinski** [comment]
> Is the `julia>` prompt saved in the command history?

It's not, but the mode is, from which you can figure out what the prompt was.

**Comment by KristofferC** [comment]
Okay, I updated this to work in the bracket-paste-mode instead. This also has the effect that the `julia> ` part is completely removed from the input before the REPL prints it or it is saved in history. So it should be equivalent to pasting the code without the prompts there at all.

Was it something like this you had in mind @keno?

**Comment by StefanKarpinski** [comment]
Very nice. I think this is a pretty handy addition :)

**Comment by mbauman** [comment]
This is awesome.  I've thought of doing this myself a few times but never got to it.

A potential addition (for a future PR) — treat any non-prompt-prefixed data within the same bracketed paste operation as doc-test style assertions.

File: test/repl.jl [hunk 1]
```diff
@@ -397,6 +397,64 @@ begin
...
+    @test T17599(3).a == 3
+    @test !foo(2)
+
+    # Test only works in bracket mode
+    sendrepl2("julia = 4\n julia> 3 && (A = 1)\n")
+    wait(c)
+    @test A == 1
+
+    # Test shell> mode
+    tmpdir = mktempdir()
```
Comment (tkelman) [inline test/repl.jl]: clean this up when finished, do block would be good

Comment (KristofferC) [inline test/repl.jl]: cleaning up now in the same way as done in the other tests in this file

File: base/REPL.jl [hunk 2]
```diff
@@ -838,11 +838,11 @@ function setup_interface(repl::LineEditREPL; hascolor = repl.hascolor, extra_rep
                 while c <= sizeof(input) && (input[c] == '\n' || input[c] == ' ' || input[c] == '\t')
                     c = nextind(input, c)
                 end
-                n_newlines = c - oldpos
+                n_whistespace_chars = c - oldpos
```
Comment (tkelman) [inline base/REPL.jl]: whitespace

File: test/repl.jl [hunk 3]
```diff
@@ -450,6 +450,7 @@ begin
     wait(c)
     @test tmpdirnow == tmpdir
     cd(curr_dir)
+    rm(tmpdir)
```
Comment (tkelman) [inline test/repl.jl]: `mktempdir() do` would be more robust about cleaning up even if the test fails

File: test/repl.jl (hunk 1 above)
Comment (tkelman) [inline test/repl.jl]: I don't see many other tests in this file creating or deleting things? If there were and they weren't using do blocks yet I'd go fix them (in a separate PR if needed).

**Comment by KristofferC** [comment]
On Apple i get `Evaluated: "/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpq563HH" == "/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpq563HH"`

Does anyone know why the `private` part is dropped from the return value of `mktempdir()`?

**Comment by tkelman** [comment]
I've seen that before. I think it's a symlink resolution thing.

**Comment by KristofferC** [comment]
Looks like the other repl test uses `pwd() == realpath(tmpdir)`. Do you think that would help?

**Comment by KristofferC** [comment]
Tests added, tests passing, bikeshed away.

To get started.

- If the first statement in a paste block contains `julia> ` should all of them require it? In my opinion, no, because then pasting something which contains parsable output can be annoying ex:
```jl
julia> 1+1
1

julia> "hej alla goa gubbar"
"hej alla goa gubbar"
```

This ties in with what @mbauman said that the unprefixed output could potentially be turned into tests but that whole discussion can be had later.

- Similarly, if the first statement does **not** contain a `julia> ` prompt, should then the rest of the statements be parsed as normally? In my view, again, no, ex:

```jl
# Random comment
julia> 1+1
```

Anything else?

**Comment by KristofferC** [comment]
Actually,

pasting
```jl
julia> "hej alla goa gubbar"
"hej alla goa gubbar"
```

turns into

```jl
"hej alla goa gubbar"
"hej alla goa gubbar"
```

which gives the error

```jl
ERROR: cannot document the following expression:

"hej alla goa gubbar"

 in error(::String, ::String, ::Vararg{String,N}) at ./error.jl:22
```

**Comment by vtjnash** [comment]
We may want to use `Base.samefile` more for those sorts of tests, since it avoids questions of alternative normalizations and such.

**Comment by StefanKarpinski** [comment]
I think it's fine for this not to work well if you paste the result too since that's easy to avoid.

**Comment by KristofferC** [comment]
After playing around with this for a bit I would say that if you are in "prompt paste mode", simply ignoring everything that does not have a prompt is the nicest user experience because then you can paste arbitrary sections of the REPL / forum posts without having to scrub the output:



Available for play at: https://github.com/KristofferC/PimpMyREPL.jl ;)

**Comment by StefanKarpinski** [comment]
Love the package name :)

**Comment by johnmyleswhite** [comment]
I'm a little concerned that the package name subtly undermines our effort to be an inclusive community for all genders.

**Comment by tkelman** [comment]
XzibitHeardYouLikeREPLs.jl

**Comment by KristofferC** [comment]
If people feel strongly about it I guess it can be called REPLEnhancements or something. There is also the point to make that too much bike shedding and "no fun allowed" policy might have negative effects when it comes to people doing actual work now as opposed to people who potentially might do work later. Might be a discussion better had somewhere else though.

**Comment by kshyatt** [comment]
My bikeshed contribution: "PutAREPLInYourREPL.jl"

**Comment by mbauman** [comment]
photo.jl

**Comment by StefanKarpinski** [comment]
My view is that the phrase "pimp my ride" / "pimp my X" has entered the common vernacular so thoroughly that it's literal meaning is extremely watered down and not much of a primary association. I'm much more concerned about the usage of "slave" terminology and have been trying to consistently get people to use "worker" instead.

**Comment by KristofferC** [comment]
http://dev.solita.fi/2014/03/18/pimp-my-repl.html

**Comment by Evizero** [comment]
> I'm a little concerned that the package name subtly undermines our effort to be an inclusive community for all genders.

I don't all see the issue in this instance. is it not a common phrase? meme even. 

In contrast to this, I do understand how the typically used "lena" test-image is undermining the effort in computer science to some extend.

> I'm much more concerned about the usage of "slave" terminology and have been trying to consistently get people to use "worker" instead.

These all seem like artificial issues. I do get avoiding offensive things, but some people just want to be upset it seems. That said, I do see that there is no downside to calling something worker instead; may even be more intuitive. But that would at least be an actual legit reason.

> There is also the point to make that too much bike shedding and "no fun allowed" policy might discourage people doing actual work now as opposed to people who potentially might do work later

I agree there. I would even go a step further and say that _exaggerated_ social justice, which seems to be the latest craze, should have no place among engineers. I for one am someone who actively tries to avoid all outlets where people are offended on behalf of someone else just for the sake of being outraged and whatnot. I'd much rather be among people who just enjoy creating cool things and are being light-hearted about it. The name `PimpMyRepl` made me smirk even. I find that a good thing.

**Comment by KristofferC** [comment]
Let's move the discussion about naming of packages to the repo I posted above and then we can focus on the feature being implemented here in this PR.

**Comment by KristofferC** [comment]
Some updates.

* Removed prompt paste support for the shell and help prompt. This seems exceedingly rare to want to do.
* Implemented what I described in  https://github.com/JuliaLang/julia/pull/17599#issuecomment-237087652
* Added a NEWS entry. Never done that before so not sure if I did it right.

**Comment by KristofferC** [comment]
@tkelman could I get a windows build for this commit? I want to test it live in window as well.

**Comment by tkelman** [comment]
we should probably actually split news to an 0.6 section if this isn't a backport candidate.

I'll trigger a win32 and win64 build from your latest commit. do you know the pattern to get it from julianightlies when it's done?

**Comment by Evizero** [comment]
the (cool!) syntax-highlighting might make this issue be related to #7604

**Comment by KristofferC** [comment]
This PR in itself has nothing to do with syntax highlighting imo.

**Comment by tkelman** [comment]
look for the first 10 characters of the sha under julianightlies.s3.amazonaws.com:

https://julianightlies.s3.amazonaws.com/bin/winnt/x86/0.5/julia-0.5.0-e1b1055f75-win32.exe
https://julianightlies.s3.amazonaws.com/bin/winnt/x64/0.5/julia-0.5.0-e1b1055f75-win64.exe

**Comment by KristofferC** [comment]
So yeah, does not work in the Windows REPL for me but passes the AppVeyor tests. I can only imagine that the bracket paste characters are not getting inserted in the paste then.

**Comment by tkelman** [comment]
what version of windows? the windows console doesn't really handle ansi control codes - mintty might do better

**Comment by KristofferC** [comment]
Win10. Mintty works fine so I guess that bracket pasting just doesnt work wil the standard windows cmd then.

File: base/REPL.jl [hunk 4]
```diff
@@ -831,7 +831,27 @@ function setup_interface(repl::LineEditREPL; hascolor = repl.hascolor, extra_rep
...
             while !done(input, oldpos) # loop until all lines have been executed
+                # Check if the next statement starts with "julia> ", in that case
+                # skip it. But first skip whitespace
+                while input[oldpos] in ('\n', ' ', '\t')
+                    oldpos = nextind(input, oldpos)
+                    oldpos >= sizeof(input) && return
+                end
+                # Check if input line starts with "julia> ", remove it if we are in prompt paste mode
+                jl_prompt_len = 7
+                 if (firstline || isprompt_paste) && (oldpos + jl_prompt_len <= sizeof(input) && input[oldpos:oldpos+jl_prompt_len-1] == "julia> ")
```
Comment (omus) [inline base/REPL.jl]: Should the Julia prompt string be turned into a constant?

Comment (KristofferC) [inline base/REPL.jl]: You expect it to change soon? :P

Comment (omus) [inline base/REPL.jl]: lol, no. Just looking over REPL.jl I noticed it was being copy pasted a couple of times.

**Comment by KristofferC** [comment]
So the reason why windows cmd goes crazy when you paste something in it (https://media.giphy.com/media/26BRNHPneDuYFWoi4/giphy.gif) is because the bracket paste good is not run and then the whole screen is basically redrawn for every character?

**Comment by Keno** [comment]
Correct, no bracketed paste, redraw for every character and windows console APIs are very slow.

**Comment by KristofferC** [comment]
Rebased, added a bit to the interactive use manual and made an option to disable it. If tests pass this is good to go from my pov.

Would a backport PR of this that defaults to not enabling the feature be considered? Virtually all code added is completely enclosed in the if statement so it should be safe. After dog fooding this a bit I feel it is extremely convenient...

File: base/REPL.jl (hunk 4 above)
Comment (musm) [inline base/REPL.jl]: Perhaps this feature would also be useful for other repl modes.

Comment (KristofferC) [inline base/REPL.jl]: Perhaps. What is possible to do is to remove an initial prompt if it exists in a pasted text but multiple statements and scrubbing away output is only possible because the julia parser tells us when an expression ends.

File: NEWS.md [hunk 5]
```diff
@@ -4,6 +4,8 @@ Julia v0.6.0 Release Notes
 New language features
 ---------------------
 
+* The REPL now supports something called *prompt pasting*. This activates when pasting text that starts with `julia> ` into the REPL. In that case, only expressions starting with `julia> ` are parsed, the rest are removed. This makes it is possible to paste a chunk of code that have been copied from a REPL session without having to scrub away prompts and outputs. This can be disabled or enabled at will with `Base.REPL.enable_promptpaste(::Bool)`.
```
Comment (tkelman) [inline NEWS.md]: most of the rest of this file wraps long lines

Comment (tkelman) [inline NEWS.md]: "makes it possible"
"code that has been copied"

File: doc/manual/interacting-with-julia.rst [hunk 6]
```diff
@@ -42,6 +42,13 @@ There are a number useful features unique to interactive work. In addition to sh
     julia> ans
     "12"
 
+In Julian mode, the REPL supports something called *prompt pasting*. This activates when pasting text that starts with ``julia> `` into the REPL.
```
Comment (tkelman) [inline doc/manual/interacting-with-julia.rst]: Julia mode

**Comment by KristofferC** [comment]
Updated from comments by @tkelman

**Comment by PallHaraldsson** [comment]
I saw this under: "New language features" not "Breaking changes"

Can this be backported? It just seems very handy (for beginners, and we want then to use 0.5 (or 0.4) and not 0.6?)

I'm not too concerned, but:

julia> julia=1
1

julia> julia>1
false

so strictly breaking (but only for the REPL).. In case people are worried, it could be off by default in older versions.. then not really helping beginners.. [I do not have commit privileges, let alone backport, could I help in some way in such matters, not sure how automated it is (if not default changed).]

I know theres a feature freeze, seems this could be an exception for 0.5.0 or 0.5.1?

**Comment by KristofferC** [comment]
Note that this is only active when you paste something, not when you type it. You even have to paste `julia> 1` with the space for it to be active, both `julia>1` and `julia > 1` will work fine but yes, in those cases it will be "breaking". 

About backporting, I don't think it should be backported with default on but as I said in https://github.com/JuliaLang/julia/pull/17599#issuecomment-238101361 defaulting it to off should be safe. I could easy make a backport PR where I disable it by default and fixup the documentation but not sure if it will be accepted.

**Comment by KristofferC** [comment]
It is annoying that Githubs markdown renderer don't respect trailing whitespaces inside a quoted code block.

**Comment by tkelman** [comment]
I'm generally against backporting features right now. Let people try this out for a while on master, keep track of any bugs with it that might need to be fixed, and we can reconsider later. Not worth introducing more changes to 0.5.0 for this IMO.

Since this is a REPL extension couldn't it even be enabled as a package?

**Comment by KristofferC** [comment]
It could and it is.

**Comment by StefanKarpinski** [comment]
This is a wonderful addition to the REPL behavior, btw.

**Comment by KristofferC** [comment]
Thanks, I like it too.

**Comment by PallHaraldsson** [comment]
"against backporting features right now", you mean backport for 0.5.1 (and maybe 0.4.x) would be ok (even with strictly breaking)? I'm ok with that, since the "break" is hardly real and only for the REPL.

This seems just that good, that we wouldn't want to wait for a year for 0.6 (or use a package).

**Comment by tkelman** [comment]
x-ref #17939 if we do decide to backport this later

**Comment by StefanKarpinski** [comment]
This feature is so nice and since it's purely interactive, I'd be in favor of backporting to 0.5.x.

**Comment by tkelman** [comment]
or it could be enabled as a package already, can't it? would that even work for users on 0.4?

this missed feature freeze - if we backport absolutely everything, what was the point of feature freeze then?

**Comment by KristofferC** [comment]
It is already enabled in a package that (should) work on 0.4. I'm fine with not back porting this and as @tkelman it did miss the feature freeze.

**Comment by tkelman** [comment]
for one of the later point releases, probably disabled by default there as suggested above, should be fine. I don't think we've had new nightlies with this in it yet.

**Comment by musm** [comment]
Just to confirm this isn't working for me on windows either

**Comment by KristofferC** [comment]
Yes,  and the docs so says so.  But there are many terminals it works on in Windows,  the standard one just lacks certain features needed.

**Comment by StefanKarpinski** [comment]
This change is so nice that I *really* want to backport it to 0.5. How do people feel about that? I can't imagine backporting this breaking anyone's programs...

**Comment by tkelman** [comment]
Disabled by default but with an option to turn it on I could see doing.

**Comment by StefanKarpinski** [comment]
How can this possibly break someone's code?

**Comment by tkelman** [comment]
It's a feature and a behavior change, neither of which we generally backport. It would make 0.5.0 behave diifferently than 0.5.1 which is not good. And it's implemented in a package that works already on 0.5.0.

**Comment by StefanKarpinski** [comment]
There's a *massive* difference between changes that only affect the REPL and other changes.

**Comment by tkelman** [comment]
0.5.x releases should be completely interchangeable with one another if you aren't hitting a bug that was fixed. This isn't a bug fix. What's the problem with installing the package to get this behavior on 0.5?

**Comment by StefanKarpinski** [comment]
That's not an a priori principle. Describe to me the scenario where having this feature in a 0.5.1 REPL but not in a 0.5.0 REPL causes any serious problem for someone.

**Comment by tkelman** [comment]
Well sure, it's a stricter interpretation of semver without the 0.x.y anything-goes exception.

Say you're teaching a course or working on a project with multiple other people, if people are on a range of different 0.5.x releases you shouldn't rely on features ("copy-paste this snippet of code") that work for only a subset of students or collaborators. Backporting features is what the minor version will be for after we hit 1.0, before then I'd rather say "if you want this feature to work on 0.5.x, use the package."

**Comment by StefanKarpinski** [comment]
That's an incredibly thin reason not to backport this. In that scenario, a few students may not be able to paste into the REPL including the `julia>` prompt, in which case they can do what we've all been doing previously – pasting only the input part. In that same scenario, if we don't backport this, then no one can paste including the `julia>` prompt. How is that better? I get the compatibility principle here, but being pointlessly dogmatic about it seems misguided.

**Comment by tkelman** [comment]
This is a feature, and it missed the 0.5 feature freeze. 0.5.0 working the same way as 0.5.1 is better than having an inconsistent feature set. No one can paste including the prompt on 0.5 unless they install the package, which works consistently no matter which point release of Julia you have installed.

**Comment by nalimilan** [comment]
I agree with @tkelman. Let's release 0.6 soon if we want to give users access the new features quickly. 0.5.x releases should be as boring as possible.
