### PR TITLE
[Statistics] fix type determination in corm

### LINKED ISSUE #32264: Statistics.cor throws domain error with specific data
This code causes `Statistics.cor` to throw a DomainError:
https://gist.github.com/manuelVo/dce2a962bbe6f5cb6181c8f55f3e1dbf

The data itself should be fine since the Error doesn't occur if `y` is a `Vector{Int16}`.

The thrown exception is the following:
```
ERROR: DomainError with -112.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] sqrt at ./math.jl:492 [inlined]
 [2] sqrt at ./math.jl:518 [inlined]
 [3] corm(::Array{UInt8,1}, ::Float64, ::Array{Int8,1}, ::Float64) at /build/julia/src/julia-1.1.1/usr/share/julia/stdlib/v1.1/Statistics/src/Statistics.jl:592
 [4] cor at /build/julia/src/julia-1.1.1/usr/share/julia/stdlib/v1.1/Statistics/src/Statistics.jl:629 [inlined]
 [5] a() at ./REPL[13]:4
 [6] top-level scope at none:0
```

The output of `versioninfo()` is
```
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes #32264. This avoids overflow (and subsequently a method error "sqrt of negative number") for smaller integer types at the initialization step. I guess this is a bugfix...?

### CODE REVIEW

File: stdlib/Statistics/src/Statistics.jl [hunk 1]
```diff
@@ -645,9 +645,9 @@ function corm(x::AbstractVector, mx, y::AbstractVector, my)
 
     @inbounds begin
         # Initialize the accumulators
-        xx = zero(sqrt(abs2(x[1])))
-        yy = zero(sqrt(abs2(y[1])))
-        xy = zero(x[1] * y[1]')
+        xx = zero(typeof(sqrt(abs2(one(eltype(x))))))
```
Comment (nalimilan) [inline stdlib/Statistics/src/Statistics.jl]: `typeof` isn't needed, right?

Comment (dkarrasch) [reply stdlib/Statistics/src/Statistics.jl]: No, it's not. Thanks for pointing out. I'll leave it out.

Comment (nalimilan) [reply stdlib/Statistics/src/Statistics.jl]: Oh, and I wonder whether this might break things like `cor(Any[1, 2], Any[1, 2])`. Probably better do `one(x[1])` and so on so that the type of the first element is used when the element type is abstract. A test for that would be nice BTW.

**Comment by nalimilan** [comment]
Thanks! Could you add a test for the fix?

File: stdlib/Statistics/src/Statistics.jl (hunk 1 above)
Comment (dkarrasch) [reply stdlib/Statistics/src/Statistics.jl]: Yes, I was wondering if there is an issue with (in)homogeneity.

**Review by nalimilan — APPROVED** [review]
