### PR TITLE
Fixed diagonal matrix eigen decomposition to return eigenvectors as diagonal matrix

### LINKED ISSUE #1049: Eigen decomposition of Diagonal matrix returns Dense eigenvectors
Hello. I noticed today that if you have a matrix of `Diagonal` type, then the eigenvector matrix (from `eigvecs` or `eigen`) is not of type `Diagonal`. Wouldn't it make more sense for the eigenvectors to match the type of the input matrix, when possible?

For example, if I have `A = Diagonal(rand(10))`, then `eigvecs(A;kwarg...)` should return a `Diagonal` (e.g. `one(A)`), but `eigvecs(Matrix(A);kwarg...)` should return a `Matrix` (e.g. `one(Matrix(A))`), and so on. The same changes would be needed for `eigen(...)`.

### LINKED ISSUE #53007: Eigen decomposition of Diagonal matrix returns Dense eigenvectors
Hello. I noticed today that if you have a matrix of `Diagonal` type, then the eigenvector matrix (from `eigvecs` or `eigen`) is not of type `Diagonal`. Wouldn't it make more sense for the eigenvectors to match the type of the input matrix, when possible?

For example, if I have `A = Diagonal(rand(10))`, then `eigvecs(A;kwarg...)` should return a `Diagonal` (e.g. `one(A)`), but `eigvecs(Matrix(A);kwarg...)` should return a `Matrix` (e.g. `one(Matrix(A))`), and so on. The same changes would be needed for `eigen(...)`.

### PR DESCRIPTION
**Pull request by OzgurMertEmir**
Solution to issue [Eigen decomposition of Diagonal matrix returns Dense eigenvectors JuliaLang/LinearAlgebra.jl#1049](https://github.com/JuliaLang/LinearAlgebra.jl/issues/1049). Modified the eigen function for diagonal matrices to return eigenvectors as diagonal matrices.

Closes JuliaLang/LinearAlgebra.jl#1049.

### CODE REVIEW

**Comment by jishnub** [comment]
You might need to update some tests that are explicitly checking for a dense matrix.

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 1]
```diff
@@ -812,15 +812,10 @@ function eigen(D::Diagonal; permute::Bool=true, scale::Bool=true, sortby::Union{
     end
     Td = Base.promote_op(/, eltype(D), eltype(D))
     λ = eigvals(D)
+    evecs = Diagonal{eltype(λ)}(ones(length(λ)))
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/diagonal.jl:815]: I suspect this needs to replace the old line 823, because when you want to sort by eigenvalues, then this will fail with a Diagonal matrix.

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 2]
```diff
@@ -820,7 +820,7 @@ function eigen(D::Diagonal; permute::Bool=true, scale::Bool=true, sortby::Union{
             evecs[p[i],i] = one(Td)
         end
     else
-        evecs = Matrix{Td}(I, size(D))
+        evecs = Diagonal{eltype(λ)}(ones(length(λ)))
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/diagonal.jl:823]: By moving the type statement, you make sure that you only allocate one vector and don't need to convert the Float64 `one` to something else, to which it may not be convertible to (like in the failing tests):

```suggestion
        evecs = Diagonal(ones(eltype(λ), length(λ)))
```

File: stdlib/LinearAlgebra/src/diagonal.jl [hunk 3]
```diff
@@ -820,7 +820,7 @@ function eigen(D::Diagonal; permute::Bool=true, scale::Bool=true, sortby::Union{
             evecs[p[i],i] = one(Td)
         end
     else
-        evecs = Matrix{Td}(I, size(D))
+        evecs = Diagonal(ones(eltype(λ), length(λ)))
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/diagonal.jl:823]:
```suggestion
        evecs = Diagonal(ones(Td, length(λ)))
```

**Comment by dkarrasch** [comment]
This infers just fine:

```julia
julia> using LinearAlgebra

julia> using Test

julia> @inferred eigen(Diagonal(ones(3)))
Eigen{Float64, Float64, Diagonal{Float64, Vector{Float64}}, Vector{Float64}}
values:
3-element Vector{Float64}:
 1.0
 1.0
 1.0
vectors:
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

julia> @inferred eigvecs(Diagonal(ones(3)))
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
```

**Comment by dkarrasch** [comment]
The failing tests are unrelated. Thanks @OzgurMertEmir for picking this up, and welcome to the Julia community.
