### PR TITLE
RFC: fix rmprocs/addprocs locking issue. Change timeout behavior.

### LINKED ISSUE #38: rmprocs / addprocs racy
node termination during node provisioning is not well handled, resulting in `connect: connection refused (ECONNREFUSED) in connect_to_worker from the new worker to the terminating worker.

for an example, see: https://travis-ci.org/JuliaLang/julia/jobs/186141590

```julia
julia> p = addprocs(2)

julia> begin # try this a couple times
         @spawnat p[1] sleep(5)
         @show rmprocs(p[1]; waitfor=0)
         @show workers()
         @show p = addprocs(1)
       end
rmprocs(p[1]; waitfor=0) = :ok
workers() = [3,4,5]
ERROR: connect: connection refused (ECONNREFUSED)
 in yieldto(::Task, ::ANY) at ./event.jl:153
 in wait() at ./event.jl:186
 in wait(::Condition) at ./event.jl:27
 in stream_wait(::TCPSocket, ::Condition, ::Vararg{Condition,N}) at ./stream.jl:42
 in wait_connected(::TCPSocket) at ./stream.jl:258
 in connect at ./stream.jl:957 [inlined]
 in connect_to_worker(::String, ::Int16) at ./managers.jl:490
 in connect_w2w(::Int64, ::WorkerConfig) at ./managers.jl:453
 in connect(::Base.DefaultClusterManager, ::Int64, ::WorkerConfig) at ./managers.jl:387
 in connect_to_peer(::Base.DefaultClusterManager, ::Int64, ::WorkerConfig) at ./multi.jl:1516
 in (::Base.##598#600{WorkerConfig,Int64})() at ./task.jl:404
Error [connect: connection refused (ECONNREFUSED)] on 6 while connecting to peer 4. Exiting.
Worker 6 terminated.
ERROR (unhandled task failure): Version read failed. Connection closed by peer.
```

### LINKED ISSUE #19687: rmprocs / addprocs racy
node termination during node provisioning is not well handled, resulting in `connect: connection refused (ECONNREFUSED) in connect_to_worker from the new worker to the terminating worker.

for an example, see: https://travis-ci.org/JuliaLang/julia/jobs/186141590

```julia
julia> p = addprocs(2)

julia> begin # try this a couple times
         @spawnat p[1] sleep(5)
         @show rmprocs(p[1]; waitfor=0)
         @show workers()
         @show p = addprocs(1)
       end
rmprocs(p[1]; waitfor=0) = :ok
workers() = [3,4,5]
ERROR: connect: connection refused (ECONNREFUSED)
 in yieldto(::Task, ::ANY) at ./event.jl:153
 in wait() at ./event.jl:186
 in wait(::Condition) at ./event.jl:27
 in stream_wait(::TCPSocket, ::Condition, ::Vararg{Condition,N}) at ./stream.jl:42
 in wait_connected(::TCPSocket) at ./stream.jl:258
 in connect at ./stream.jl:957 [inlined]
 in connect_to_worker(::String, ::Int16) at ./managers.jl:490
 in connect_w2w(::Int64, ::WorkerConfig) at ./managers.jl:453
 in connect(::Base.DefaultClusterManager, ::Int64, ::WorkerConfig) at ./managers.jl:387
 in connect_to_peer(::Base.DefaultClusterManager, ::Int64, ::WorkerConfig) at ./multi.jl:1516
 in (::Base.##598#600{WorkerConfig,Int64})() at ./task.jl:404
Error [connect: connection refused (ECONNREFUSED)] on 6 while connecting to peer 4. Exiting.
Worker 6 terminated.
ERROR (unhandled task failure): Version read failed. Connection closed by peer.
```

### PR DESCRIPTION
**Pull request by amitmurthy**
Closes JuliaLang/Distributed.jl#38

This changes the behavior of `rmprocs`, specifically how arg `waitfor` is handled.

The previous behavior was to return a symbol (`:timed_out` or `:ok`) depending on if the workers were removed in the stipulated time. Default value of `waitfor` was 0 with no wait for worker removal. 

Now:
    - If unspecified, `rmprocs` will wait until all requested `pids` are removed.
    - An `ErrorException` is raised if all workers cannot be terminated before
      the requested `waitfor` seconds.
    - With a `waitfor` value of 0, the call returns immediately with the workers scheduled
       for removal in a different task. The scheduled `Task` object is returned.
       The user should call `wait` on the task before invoking any other parallel calls.

### CODE REVIEW

File: base/multi.jl [hunk 1]
```diff
@@ -505,52 +505,72 @@ function workers()
...
-                sleep(0.1)
-            end
+            all(w -> w.state == W_TERMINATED, rmprocset) && break
+            sleep(min(0.1, waitfor - (time() - start)))
         end
 
-        ((waitfor > 0) && any(w -> w.state != W_TERMINATED, rmprocset)) ? :timed_out : :ok
+        unremoved = [wrkr.id for wrkr in filter(w -> w.state != W_TERMINATED, rmprocset)]
+        if length(unremoved) > 0
+            estr = string("rmprocs: pids ", unremoved, " not terminated after", waitfor, " seconds.")
```
Comment (tkelman) [inline base/multi.jl]: space between after and the time

**Comment by vtjnash** [comment]
It looks like this should help, but I don't think this fixes #19687 completely. Note that we still still have a plausible racy execution of:
@async rmprocs()
@async addprocs()
Since in runtests, each worker is being managed by an independent task without synchronization.

**Comment by amitmurthy** [comment]
`addprocs` and `rmprocs` internally synchronize access via `worker_lock`.

runtests should be fine since the code there is adding/removing specific process ids.  Since newer pids connect to lower pids, as long as `addprocs` and `rmprocs` are dealing with correctly updated data structures, newer processes will not be sent pids of workers who are in the process of exiting from process 1. 

With this PR rmprocs returns only after the process removal is complete (by default). 

And the example mentioned
```
@async rmprocs(workers())
@async addprocs(N)
```

will also not fail due to an invalid state. It may however not have desired effect since we do not guarantee the order in which tasks are executed.

**Comment by amitmurthy** [comment]
Travis error is unrelated.

**Comment by vtjnash** [comment]
Ah, ok, thanks. Lgtm.

**Comment by amitmurthy** [comment]
Will merge this in a couple of days after addressing Tony's comment.
