### PR TITLE
optimizer: fix #43254, avoid infinite CFG traversal in SROA's domination analysis

### LINKED ISSUE #43254: Internal error: encountered unexpected error in runtime: StackOverflowError() in has_safe_def
One of our packages started to produce the following error:
```julia
Internal error: encountered unexpected error in runtime:
StackOverflowError()
has_safe_def at ./compiler/ssair/passes.jl:98
has_safe_def at ./compiler/ssair/passes.jl:113
[...]
has_safe_def at ./compiler/ssair/passes.jl:101 [inlined]
sroa_mutables! at ./compiler/ssair/passes.jl:873
[...]
```
see https://github.com/oscar-system/Oscar.jl/runs/4352506233?check_suite_focus=true#step:5:426.

This is with master I built a few minutes ago:
```julia
julia> versioninfo()
Julia Version 1.8.0-DEV.1081
Commit 43bc48b1f8 (2021-11-29 13:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```
I have not done a bisect yet, but there are some obvious commits to look at.

### PR DESCRIPTION
**Pull request by aviatesk**
Since CFG can be cyclic, the previous implementation of `has_safe_def`
that simply walks predecessors recursively was just wrong.

This commit fixes it by making `has_safe_def` maintain a single set that
keeps the identities of basic blocks that have been examined already.

~~This commit doesn't come with any sort of fancy tags that indicates a
basic block is "being examined" or such, as opposed to inference,
and thus this approach doesn't handle cycles very nicely.
But still I don't see much motivation to make `has_safe_def` more accurate
while keeping it correct, since it's called only in rare cases.~~ 
EDIT: now I don't think we even want such tagging mechanism here,
rather this commit just gives up SROA if it encounters a cycle.

---

I confirmed this commit passes Oscar.jl's test suite w/o the problem reported at #43254 .
I couldn't make up a MRE that hits the barrier added by this commit though.

### CODE REVIEW

File: base/compiler/ssair/passes.jl [hunk 1]
```diff
@@ -97,20 +97,39 @@ end
...
+        idx = last(ir.cfg.blocks[pred].stmts)
+        # NOTE `idx` isn't a load, thus we can use inclusive coondition within the `find_def_for_use`
+        def, _, _ = find_def_for_use(ir, domtree, allblocks, du, idx, true)
+        # will throw since we already checked this `:new` site doesn't define this field
+        def == newidx && return false
+        # found a "safe" definition for this predecessor
+        def ≠ 0 && continue
+        # check for the predecessors of this predecessor
+        push!(seen, pred)
+        has_safe_def(ir, domtree, allblocks, du, newidx, pred, seen) || return false
```
Comment (vchuravy) [inline base/compiler/ssair/passes.jl:132]: Side Note: In a compiler it's generally best to avoid recursion and use worklists instead. 

Recursion can always blow-up the stack on a sufficiently complex input program

Comment (aviatesk) [reply base/compiler/ssair/passes.jl:132]: Good to know, I don't read much compiler books yet, but now I see why passes.jl is full of worklists :)
Well, does this imply that in Julia at least, it's generally better to switch to iteration if we don't spend much attention to readability or such, but only care about performance?

File: base/compiler/ssair/passes.jl [hunk 2]
```diff
@@ -97,20 +97,39 @@ end
...
-    def ≠ 0 && return true # found a "safe" definition
-
-    # we may be able to replace this load with `PhiNode` if all the predecessors have "safe" definitions
-    idxblock = block_for_inst(ir, idx)
-    for pred in ir.cfg.blocks[idxblock].preds
-        lastidx = last(ir.cfg.blocks[pred].stmts)
-        # NOTE `lastidx` isn't a load, thus we can use inclusive coondition within the `find_def_for_use`
-        has_safe_def(ir, domtree, allblocks, du, newidx, lastidx, true) || return false
+# recursively examine if all predecessors of `block` have any "safe" definition
+# XXX this implementation avoids infinite cycles by maintaining a sigle set of seen basic blocks,
```
Comment (fingolfin) [inline base/compiler/ssair/passes.jl:113]:
```suggestion
# XXX this implementation avoids infinite cycles by maintaining a single set of seen basic blocks,
```
