### PR TITLE
Use exact algorithm for `cond(A,1)`, and fix for singular matrices

### LINKED ISSUE #664: cond(A,1) fails to produce Inf for A exactly singular
The following error occurs with Julia V1.1:

A = [1. 1.; 0. 0.]
cond(A,1)
ERROR: SingularException(2)
Stacktrace:
 [1] checknonsingular at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\factorization.jl:12 [inlined]
 [2] #lu!#103(::Bool, ::Function, ::Array{Float64,2}, ::Val{true}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\lu.jl:41
 [3] #lu#107 at .\none:0 [inlined]
 [4] lu at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\lu.jl:142 [inlined] (repeats 2 times)
 [5] _cond1Inf(::Array{Float64,2}, ::Int64) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\dense.jl:1390
 [6] cond(::Array{Float64,2}, ::Int64) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\dense.jl:1386
 [7] top-level scope at none:0

The result should be Inf, as correctly computed by cond(A,2).

### LINKED ISSUE #674: Condition number is computed wrong in some cases
I have discovered this issue while working on another one:

```julia
julia> M = [1.0 -2.0; -2.0 -1.5]
2×2 Array{Float64,2}:
  1.0  -2.0
 -2.0  -1.5

julia> S = Symmetric(M)
2×2 Symmetric{Float64,Array{Float64,2}}:
  1.0  -2.0
 -2.0  -1.5

julia> cond(M, 1)
1.909090909090909

julia> cond(S, 1)
2.227272727272727
```

These two condition numbers should be the same, but they are clearly not.

### PR DESCRIPTION
**Pull request by antoine-levitt**
Fix https://github.com/JuliaLang/LinearAlgebra.jl/issues/664
Fix https://github.com/JuliaLang/LinearAlgebra.jl/issues/674

### CODE REVIEW

File: stdlib/LinearAlgebra/src/dense.jl [hunk 1]
```diff
@@ -1421,12 +1421,19 @@ function cond(A::AbstractMatrix, p::Real=2)
         return maxv == 0.0 ? oftype(real(A[1,1]),Inf) : maxv / minimum(v)
```
Comment (goggle) [inline stdlib/LinearAlgebra/src/dense.jl]: For `A = zeros(Int, 2, 2)`, `cond(A, 2)` fails with an `InexactError`. I have changed this line to
```julia
return iszero(maxv) ? oftype(real(maxv), Inf) : maxv / minimum(v)
```

File: stdlib/LinearAlgebra/src/dense.jl [hunk 2]
```diff
@@ -1421,12 +1421,19 @@ function cond(A::AbstractMatrix, p::Real=2)
...
     elseif p == 1 || p == Inf
         checksquare(A)
-        return _cond1Inf(A, p)
+        try
+            Ainv = inv(A)
+            return opnorm(A, p)*opnorm(Ainv, p)
+        catch e
+            if isa(e, LAPACKException) || isa(e, SingularException)
+                return convert(real(eltype(A)), Inf)
```
Comment (goggle) [inline stdlib/LinearAlgebra/src/dense.jl]: Also this will fail if `A = zeros(Int, 2, 2)`.

File: stdlib/LinearAlgebra/test/lu.jl [hunk 3]
```diff
@@ -341,4 +337,13 @@ end
...
 
+@testset "Issue #33547, condition number of 2x2 matrix" begin
+    M = [1.0 -2.0; -2.0 -1.5]
+    @test cond(M, 1) ≈ 2.227272727272727
+end
+@testset "Issue #33297, condition number of singular matrix" begin
+    M = [1. 1.; 0. 0.]
+    @test cond(M, 1) == Inf
+end
+
```
Comment (goggle) [inline stdlib/LinearAlgebra/test/lu.jl]: I have added my tests to the test set "Matrix condition number" in `stdlib/LinearAlgebra/test/dense.jl`. In my opinion this is a better place for these tests, because then they're bundled.

Maybe we could add this:
```julia
for p in (1, 2, Inf)
        @test cond(zeros(Int, 2, 2), p) == Inf
        @test cond(zeros(2, 2), p) == Inf
        @test cond([0 0; 1 1], p) == Inf
        @test cond([0. 0.; 1. 1.], p) == Inf
end

**Review by goggle — CHANGES_REQUESTED** [review]

**Comment by antoine-levitt** [comment]
Thanks @goggle, I changed according to your input. I used the same (convoluted) logic as in `inv` for computing the output type.

File: stdlib/LinearAlgebra/src/dense.jl [hunk 4]
```diff
@@ -1418,15 +1418,24 @@ function cond(A::AbstractMatrix, p::Real=2)
...
         checksquare(A)
-        return _cond1Inf(A, p)
+        try
+            Ainv = inv(A)
+            return opnorm(A, p)*opnorm(Ainv, p)
+        catch e
+            if isa(e, LAPACKException) || isa(e, SingularException)
+                TA = real(eltype(A))
+                Tout = typeof((one(TA)*zero(TA) + one(TA)*zero(TA))/one(TA))
+                return convert(Tout, Inf)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/src/dense.jl]: The issue seems to be that `Inf` is not in `Int`, right? We could simplify this a bit to
```julia
TA = float(real(eltype(A)))
return convert(TA, Inf)
```
?

Comment (antoine-levitt) [reply stdlib/LinearAlgebra/src/dense.jl]: Great idea, thanks!

**Comment by dkarrasch** [comment]
Looks good to me, let's try to have another pair of eyes on it. BTW, do we need to announce somewhere that we're no longer (silently) returning condition number _estimates_ in some cases? This certainly changes behavior, now the question is if that's simply a "bugfix" or a "breaking change"?

File: stdlib/LinearAlgebra/test/lu.jl (hunk 3 above)
Comment (goggle) [inline stdlib/LinearAlgebra/test/lu.jl]: Maybe we could move these tests to `dense.jl`? The current implementation of `cond` has nothing in common with `lu` anymore and resides in `dense.jl`. So doesn't it make more sense to have these tests also in `dense.jl`?

File: stdlib/LinearAlgebra/test/lu.jl [hunk 5]
```diff
@@ -341,4 +337,13 @@ end
...
 end
 
+@testset "Issue #33547, condition number of 2x2 matrix" begin
+    M = [1.0 -2.0; -2.0 -1.5]
+    @test cond(M, 1) ≈ 2.227272727272727
+end
+@testset "Issue #33297, condition number of singular matrix" begin
+    M = [1. 1.; 0. 0.]
+    @test cond(M, 1) == Inf
+end
```
Comment (goggle) [inline stdlib/LinearAlgebra/test/lu.jl]: Maybe we could move these tests to `dense.jl`? The current implementation of `cond` has nothing in common with `lu` anymore and resides in `dense.jl`. So doesn't it make more sense to have these tests also in `dense.jl`?

Comment (antoine-levitt) [reply stdlib/LinearAlgebra/test/lu.jl]: Done, thanks!

File: stdlib/LinearAlgebra/test/dense.jl [hunk 6]
```diff
@@ -29,6 +29,17 @@ Random.seed!(1234321)
             @test_throws ArgumentError cond(a,3)
         end
     end
+    @testset "Singular matrices" for p in (1, 2, Inf)
+        @test cond(zeros(Int, 2, 2), p) == Inf
+        @test cond(zeros(2, 2), p) == Inf
+        @test cond([0 0; 1 1], p) == Inf
+        @test cond([0. 0.; 1. 1.], p) == Inf
+    end
+
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/dense.jl]: There seems to be some trailing whitespace issue in this line...

**Review by goggle — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Changing behavior is technically breaking, so I'm putting the "minor change" label on this, but going from an estimate to an exact error is certainly an improvement, so permissible in a minor version. Should have a NEWS entry, however.

**Comment by antoine-levitt** [comment]
Done

**Review by dkarrasch — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
This seems to be good to go as soon as CI passes.
