### PR TITLE
Fix Pkg require check

### LINKED ISSUE #20419: jl_deserialize_value crash during Pkg.add("MatlabCompat")
Bisect points to c99e12c9338 as introducing this, cc @simonbyrne
```
~/Julia/julia-0.6$ ./julia -e 'versioninfo()'
Julia Version 0.6.0-dev.2540
Commit ad5cd7b* (2017-02-02 21:32 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
~/Julia/julia-0.6$ rm -rf jlpkgtmp
~/Julia/julia-0.6$ JULIA_PKGDIR=$PWD/jlpkgtmp ./julia -e 'Pkg.init(); Pkg.add("MatlabCompat")'
INFO: Initializing package repository /home/tkelman/Julia/julia-0.6/jlpkgtmp/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of AxisArrays from https://github.com/JuliaArrays/AxisArrays.jl.git
<etc>
INFO: Cloning cache of Zlib from https://github.com/dcjones/Zlib.jl.git
INFO: Installing AxisArrays v0.0.3
<etc>
INFO: Installing Zlib v0.1.12

signal (15): Terminated
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f2ecc81aeed)
memcpy at /usr/include/x86_64-linux-gnu/bits/string3.h:51 [inlined]
_ios_read at /home/tkelman/Julia/julia-0.6/src/support/ios.c:275 [inlined]
ios_read at /home/tkelman/Julia/julia-0.6/src/support/ios.c:331
jl_deserialize_value_ at /home/tkelman/Julia/julia-0.6/src/dump.c:2057
jl_deserialize_value_svec at /home/tkelman/Julia/julia-0.6/src/dump.c:1534 [inlined]
jl_deserialize_value_ at /home/tkelman/Julia/julia-0.6/src/dump.c:1979
jl_deserialize_struct at /home/tkelman/Julia/julia-0.6/src/dump.c:1880
jl_deserialize_value_any at /home/tkelman/Julia/julia-0.6/src/dump.c:1969 [inlined]
jl_deserialize_value_ at /home/tkelman/Julia/julia-0.6/src/dump.c:2065
jl_deserialize_value at /home/tkelman/Julia/julia-0.6/src/dump.c:1517 [inlined]
jl_deserialize_value_array at /home/tkelman/Julia/julia-0.6/src/dump.c:1595
<etc>
```
full output: https://gist.github.com/5ea4ace3667e6043e9c8ec87fbe021de

### PR DESCRIPTION
**Pull request by simonbyrne**
Pkg previously used `iszero` as a check on the return value of `revparseid`. `revparseid` no longer returns a zero hash if the result does not exist.

Fixes #20419.

### CODE REVIEW

**Comment by tkelman** [comment]
is there any way to check for existence without needing a try catch?

**Comment by simonbyrne** [comment]
I don't so. We could add one, though not sure the best way to do it.

**Comment by tkelman** [comment]
we shouldn't be throwing in the API if this is commonly called on things that it won't find then. return a nullable for not found?

File: base/pkg/read.jl [hunk 1]
```diff
@@ -64,7 +64,11 @@ function isfixed(pkg::AbstractString, prepo::LibGit2.GitRepo, avail::Dict=availa
     LibGit2.isdirty(prepo) && return true
     LibGit2.isattached(prepo) && return true
     LibGit2.need_update(prepo)
-    LibGit2.iszero(LibGit2.revparseid(prepo, "HEAD:REQUIRE")) && isfile(pkg,"REQUIRE") && return true
+    try
+        LibGit2.revparseid(prepo, "HEAD:REQUIRE")
+    catch e
```
Comment (tkelman) [inline base/pkg/read.jl]: if it's going to be a try catch (which it shouldn't) then it needs to be specific about what it's expecting

**Comment by simonbyrne** [comment]
Calling `find` on the index already provides the functionality, so that seems like the best option here.

File: base/libgit2/index.jl [hunk 2]
```diff
@@ -113,12 +113,12 @@ function Base.find(path::String, idx::GitIndex)
...
-    ret == Error.ENOTFOUND && return Nullable{Csize_t}()
+    ret == Cint(Error.ENOTFOUND) && return Nullable{Csize_t}()
     return Nullable(pos_ref[]+1)
 end
 
 stage(ie::IndexEntry) = ccall((:git_index_entry_stage, :libgit2), Cint, (Ptr{IndexEntry},), Ref(ie))
 
 function Base.show(io::IO, idx::GitIndex)
-    println(io, "GitIndex:\nRepository: ", repository(idk), "\nNumber of elements: ", count(idx))
+    println(io, "GitIndex:\nRepository: ", repository(idx), "\nNumber of elements: ", count(idx))
```
Comment (tkelman) [inline base/libgit2/index.jl]: was this not tested?

File: base/pkg/read.jl [hunk 3]
```diff
@@ -64,8 +64,9 @@ function isfixed(pkg::AbstractString, prepo::LibGit2.GitRepo, avail::Dict=availa
     LibGit2.isdirty(prepo) && return true
     LibGit2.isattached(prepo) && return true
     LibGit2.need_update(prepo)
-    LibGit2.iszero(LibGit2.revparseid(prepo, "HEAD:REQUIRE")) && isfile(pkg,"REQUIRE") && return true
-
+    if isnull(find("REQUIRE", LibGit2.GitIndex(repo)))
```
Comment (tkelman) [inline base/pkg/read.jl]: does `find` not handle the `HEAD:` part then?

Comment (simonbyrne) [inline base/pkg/read.jl]: No, it's not necessary, since the index will be for `HEAD`.

File: base/libgit2/repository.jl [hunk 4]
```diff
@@ -100,6 +100,11 @@ function (::Type{T}){T<:GitObject}(repo::GitRepo, spec::AbstractString)
     obj_ptr_ptr = Ref{Ptr{Void}}(C_NULL)
     @check ccall((:git_revparse_single, :libgit2), Cint,
                  (Ptr{Ptr{Void}}, Ptr{Void}, Cstring), obj_ptr_ptr, repo.ptr, spec)
+    # check object is of correct type
+    if T != GitObject && T != GitUnknownObject
+        t = Consts.OBJECT(obj_ptr_ptr[])
+        t == Consts.OBJECT(T) || throw(GitError(Error.Object, Error.ERROR, "Expected object of type $T, received object of type $(objtype(t))"))
```
Comment (tkelman) [inline base/libgit2/repository.jl]: is there a test for this branch?

Comment (simonbyrne) [inline base/libgit2/repository.jl]: Ah, good idea.

File: base/pkg/read.jl (hunk 3 above)
Comment (tkelman) [inline base/pkg/read.jl]: should be `prepo`
