### PR TITLE
fix #42409, stack overflow in type intersection

### LINKED ISSUE #42409: Internal Error/StackOverflowError: reachable_var at subtype.c after ca0331f
MWE:
```julia

using Pkg
Pkg.activate(; temp=true)

Pkg.Registry.add("General")
Pkg.Registry.add(RegistrySpec(url = "https://gitlab.kuleuven.be/ppw-okpiv/research/okpregistry.git"))

Pkg.add("GradientDiffusion")

using GradientDiffusion
GradientDiffusion.random_free_energy_parameters(GradientDiffusion.BoundedOrnsteinUhlenbeckModel, Float32, Int64(2))

```
I tried this on the configurations below:
```julia
julia> versioninfo()
Julia Version 1.7.0-rc1
Commit 9eade6195e (2021-09-12 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```
and:
```julia
Julia Version 1.7.0-beta4
Commit d0c90f37ba (2021-08-24 12:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
```

The error below occurs on Windows 10 (AMD64) and Linux (AMD64) since https://github.com/JuliaLang/julia/commit/ca0331f75182eb221a8a80000edb7a758fcbb87b. So version 1.6 and 1.7-beta3 are not affected, 1.7-beta4 and 1.7-rc1 are affected.

If I build version 1.7-rc1 on the Windows 10 (AMD64) machine, after rolling back the changes made in https://github.com/JuliaLang/julia/commit/ca0331f75182eb221a8a80000edb7a758fcbb87b in subtype.c, the error message is gone.

```julia
Internal error: encountered unexpected error in runtime:
StackOverflowError()
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2248
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2258 [inlined]
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2257
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2257
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2258 [inlined]
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2257
reachable_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2257
... repeats a lot of times...
intersect_var at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2280
intersect at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3045
intersect_all at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3170
intersect_aside at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2126
var_lt at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:623
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1226
forall_exists_equal at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1378
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1301
subtype_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:769
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1255
subtype_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:803
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1252
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1226
exists_subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1390 [inlined]
forall_exists_subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1418
subtype_ccheck at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:555
var_gt at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:657
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1229
forall_exists_equal at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1366
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1301
subtype_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:769
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1255
subtype_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:803
subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1252
exists_subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1390 [inlined]
forall_exists_subtype at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1418
subtype_in_env_ at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1894
subtype_bounds_in_env at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:1904 [inlined]
subtype_in_env_existential at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2236
intersect_invariant at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2884
intersect at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3125
intersect_unionall_ at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2569
intersect_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2618
intersect at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3104
intersect_tuple at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2765 [inlined]
intersect at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3119
intersect_unionall_ at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2573
intersect_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:2618
intersect at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3101
intersect_all at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3170
jl_type_intersection_env_s at /cygdrive/c/buildbot/worker/package_win64/build/src\subtype.c:3412
jl_type_intersection2 at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1597
ml_matches at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2957
jl_matching_methods at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1893
_methods_by_ftype at .\reflection.jl:908 [inlined]
#findall#246 at .\compiler\methodtable.jl:68 [inlined]
findall##kw at .\compiler\methodtable.jl:65
jfptr_findallYY.YY.kw_15965.clone_1 at C:\Users\User1\AppData\Local\Programs\Julia-1.7.0-rc1\lib\julia\sys.dll (unknown line)
#249 at .\compiler\methodtable.jl:97
get! at .\iddict.jl:178 [inlined]
#findall#248 at .\compiler\methodtable.jl:96 [inlined]
findall##kw at .\compiler\methodtable.jl:95
jfptr_findallYY.YY.kw_15960.clone_1 at C:\Users\User1\AppData\Local\Programs\Julia-1.7.0-rc1\lib\julia\sys.dll (unknown line)
find_matching_methods at .\compiler\abstractinterpretation.jl:308
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:39
abstract_call_known at .\compiler\abstractinterpretation.jl:1319
abstract_call at .\compiler\abstractinterpretation.jl:1374
abstract_call at .\compiler\abstractinterpretation.jl:1359
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1514
typeinf_local at .\compiler\abstractinterpretation.jl:1897
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1993
_typeinf at .\compiler\typeinfer.jl:226
typeinf at .\compiler\typeinfer.jl:209
typeinf_ext at .\compiler\typeinfer.jl:909
typeinf_ext_toplevel at .\compiler\typeinfer.jl:942
typeinf_ext_toplevel at .\compiler\typeinfer.jl:938
jfptr_typeinf_ext_toplevel_9672.clone_1 at C:\Users\User1\AppData\Local\Programs\Julia-1.7.0-rc1\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2245 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2427 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1790 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:295
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:338
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1978
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1932 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2237 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2427
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1790 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:713
#quadratic#143 at C:\Users\User1\.julia\packages\GradientDiffusion\pnaF4\src\BOU\Parameters.jl:16
quadratic##kw at C:\Users\User1\.julia\packages\GradientDiffusion\pnaF4\src\BOU\Parameters.jl:10 [inlined]
#random_free_energy_parameters#144 at C:\Users\User1\.julia\packages\GradientDiffusion\pnaF4\src\BOU\Parameters.jl:39
random_free_energy_parameters at C:\Users\User1\.julia\packages\GradientDiffusion\pnaF4\src\BOU\Parameters.jl:39
unknown function (ip: 000000005e677134)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1790 [inlined]
do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:126
eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:215
eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:166 [inlined]
eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:583
jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:731
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:885
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:830
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:830
jl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:894 [inlined]
jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:944
eval at .\boot.jl:373 [inlined]
eval_user_input at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\REPL\src\REPL.jl:150
repl_backend_loop at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\REPL\src\REPL.jl:244
start_repl_backend at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\REPL\src\REPL.jl:229
#run_repl#47 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\REPL\src\REPL.jl:362
run_repl at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\REPL\src\REPL.jl:349
#929 at .\client.jl:394
jfptr_YY.929_20898.clone_1 at C:\Users\User1\AppData\Local\Programs\Julia-1.7.0-rc1\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1790 [inlined]
jl_f__call_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:757
#invokelatest#2 at .\essentials.jl:716 [inlined]
invokelatest at .\essentials.jl:714 [inlined]
run_main_repl at .\client.jl:379
exec_options at .\client.jl:309
_start at .\client.jl:495
jfptr__start_47598.clone_1 at C:\Users\User1\AppData\Local\Programs\Julia-1.7.0-rc1\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1790 [inlined]
true_main at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:559
jl_repl_entrypoint at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:701
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win64/build/cli\loader_exe.c:42
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
(Float32[12.177841 4.3019295; 4.3019295 13.54631], Float32[0.0038441217, -0.030088827])

julia>

```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #42409

### CODE REVIEW

File: src/subtype.c [hunk 1]
```diff
@@ -656,7 +658,9 @@ static int var_gt(jl_tvar_t *b, jl_value_t *a, jl_stenv_t *e, int param)
     }
     if (!((bb->ub == (jl_value_t*)jl_any_type && !jl_is_type(a) && !jl_is_typevar(a)) || subtype_ccheck(a, bb->ub, e)))
         return 0;
-    bb->lb = simple_join(bb->lb, a);
+    jl_value_t *lb = simple_join(bb->lb, a);
+    if (!e->intersection || !subtype_by_bounds(lb, b, e))
```
Comment (vtjnash) [inline src/subtype.c:662]: You've angered analyzegc here:
```
/cache/build/amdci5-2/julialang/julia-master/src/subtype.c:662:30: error: Passing non-rooted value as argument to function that may GC [julia.GCChecker]
    if (!e->intersection || !subtype_by_bounds(lb, b, e))
```

since `subtype_by_bounds` is not marked JL_NOTSAFEPOINT, nor is `simple_join` marked `JL_PROPAGATES_ROOT`

File: src/subtype.c [hunk 2]
```diff
@@ -656,7 +658,9 @@ static int var_gt(jl_tvar_t *b, jl_value_t *a, jl_stenv_t *e, int param)
...
+        bb->lb = lb;
     assert(bb->lb != (jl_value_t*)b);
```
Comment (vtjnash) [inline src/subtype.c:664]:
```suggestion
    assert(lb != (jl_value_t*)b && "why is this wrong?");
```
?
