### PR TITLE
Fix a small number of invalid unsafe code

### LINKED ISSUE #23520: Invalid `write(io::IO, s::String)` method
The method definition

```julia
write(io::IO, s::String) = unsafe_write(io, pointer(s), reinterpret(UInt, sizeof(s)))
```

is invalid since it is not guaranteed that the `s` will be kept alive when this function is inlined.

In particular, this cases `@code_llvm show(IOBuffer(), 4)` to be invalid
```llvm
; Function show
; Location: show.jl
define void @jlsys_show_37268(%jl_value_t addrspace(10)* dereferenceable(48), i64) #0 {
top:
; Location: show.jl:353
  %2 = ashr i64 %1, 63
  %3 = add i64 %2, %1
  %4 = xor i64 %3, %2
  %.lobit = lshr i64 %1, 63
  %5 = trunc i64 %.lobit to i8
  %6 = call %jl_value_t addrspace(10)* @jlsys_dec_38356(i64 %4, i64 1, i8 %5)
  %7 = addrspacecast %jl_value_t addrspace(10)* %6 to %jl_value_t*
  %8 = ptrtoint %jl_value_t* %7 to i64
  %9 = add i64 %8, 8
  %10 = inttoptr i64 %9 to i8*
  %11 = bitcast %jl_value_t addrspace(10)* %6 to i64 addrspace(10)*
  %12 = load i64, i64 addrspace(10)* %11, align 8
  %13 = call i64 @jlsys_unsafe_write_37226(%jl_value_t addrspace(10)* %0, i8* %10, i64 %12)
  ret void
}
```
(Note that the return value of `dec` is passed to `unsafe_write` without being rooted).

This may show up as intermittent test failure with `UndefVarError(t_...)` since it can cause the `"t_$i"` to return the wrong value and messes up lowering. (Not sure if this shows up on CI but I've hit it multiple times in ~1 day of GC stress testing)

We can workaround this for now by adding `@noinline` although it'll be nice if we can fix this with some kind of GC preserve scope for a certain object.

### PR DESCRIPTION
**Pull request by yuyichao**
Started as trying to fix #23520 but as the title said, this end up fixing only a small number of them -- basically all use of `pointer` were wrong. Also marked a few even more invalid places where managed pointer is passed to `unsafe_wrap` (the fix for those will be much more involved).

The only unrelated change is https://github.com/JuliaLang/julia/compare/yyc/gc/safe_unsafe_write?expand=1#diff-b103e3ad474d354f14374e435955adcbL516 which is what I happened to notice when fixing the function.

Should in principle have no effect on performance but inlining may still be sensitive in some cases so 

@nanosoldier `runbenchmarks(ALL, vs=":master")`

### CODE REVIEW

**Comment by quinnj** [comment]
Could we get a little documentation/explanation on `gc_preserve` for those of us who haven't been following this development very closely? This seems like a pretty significant change, i.e. any time I use `pointer` in my code is probably wrong, correct? Are there cases where I use `pointer` that I _don't_ need `gc_preserve`?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23914) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ecb9e554fb41df04b038e88df7b98fd1695dc2a9/2036451_vs_b72af50/report.md). cc @ararslan

**Comment by mschauer** [comment]
The infrastructure was introduced in #23610, related devdoc entry: https://docs.julialang.org/en/latest/devdocs/llvm/#Keeping-values-alive-in-the-absence-of-uses-1

**Comment by yuyichao** [comment]
> Could we get a little documentation/explanation on gc_preserve for those of us who haven't been following this development very closely?

The macro has doc.

> This seems like a pretty significant change, i.e. any time I use pointer in my code is probably wrong, correct? Are there cases where I use pointer that I don't need gc_preserve?

There has been no change in the semantic, those code has always been wrong. It's just that the compiler wasn't smart enough to use them in a lot of the cases. The main issue is that local variables do not create GC roots, only their use does. This is consistent with the property that extra local variable assignments has absolutely no semantic significance, including the arguments for inlined functions.

There are cases where `@gc_preserve` is not necessary, basic when there are other defined way an object is rooted. Other defined way includes,

1. Globals.

    Note that simply stroing the object to a global is not good enough. Ref https://github.com/JuliaPy/PyCall.jl/pull/425/commits/0e3bf0ec187980653030dda10ff61492fd78a6d7

2. `ccall`

    If the pointer value is only used in ccall and the same object is being preserved by another ccall argument then you don't have to preserve that object explicitly, i.e. `ccall(...., pointer(array) + 1, array)` is fine, though could be a little confusing/misleading for the reader.

3. If the caller is supposed to do so for you

   When you define `unsafe_convert` and `pointer` methods, it's obviously fine to call these without preserving the arguments since the caller must do that for you, if the result needs to be used. If you are using the pointer yourself in those methods (not just pointer arithmetic, but loading/storing on the pointer) though, those use must be preserved since the caller only need to preserve the argument if the result will be used.

File: base/random/RNGs.jl [hunk 1]
```diff
@@ -137,7 +137,7 @@ hash(r::MersenneTwister, h::UInt) = foldr(hash, h, (r.seed, r.state, r.vals, r.i
 @inline mt_pop!(r::MersenneTwister) = @inbounds return r.vals[r.idx+=1]
 
 function gen_rand(r::MersenneTwister)
-    dsfmt_fill_array_close1_open2!(r.state, pointer(r.vals), length(r.vals))
+    Base.@gc_preserve r dsfmt_fill_array_close1_open2!(r.state, pointer(r.vals), length(r.vals))
```
Comment (rfourquet) [inline base/random/RNGs.jl]: Here (also in other places), the "preserved" object is again used on the line after, isn't it enough to preserve it? (I guess not as you updated the code) Is it that the compiler can reorder instructions?

File: base/random/RNGs.jl [hunk 2]
```diff
@@ -328,8 +328,9 @@ function rand!(r::MersenneTwister, A::Union{Array{Float16},Array{Float32}},
     T = eltype(A)
     n = length(A)
     n128 = n * sizeof(T) ÷ 16
-    rand!(r, unsafe_wrap(Array, convert(Ptr{Float64}, pointer(A)), 2*n128),
-          2*n128, Close1Open2())
+    Base.@gc_preserve A rand!(r, unsafe_wrap(Array, convert(Ptr{Float64}, pointer(A)), 2*n128),
+                              2*n128, Close1Open2())
+    # FIXME: This code is completely invalid!!!
     A128 = unsafe_wrap(Array, convert(Ptr{UInt128}, pointer(A)), n128)
```
Comment (rfourquet) [inline base/random/RNGs.jl]: I had plans to change this to avoid using `unsafe_wrap` for performance reasons (cf. #9174), but maybe I need to understand what is invalid here? Preserving `A` wouldn't be enough?

Comment (yuyichao) [reply base/random/RNGs.jl]: You can't pass a managed pointer to `unsafe_wrap`.

File: base/random/RNGs.jl (hunk 1 above)
Comment (yuyichao) [reply base/random/RNGs.jl]: No it's not.

**Comment by yuyichao** [comment]
There are of course cases where the code will practically be fine, for now. But I don't want to go into detail to document the limitation of the compiler/optimizer especially since people don't have to rely on these anymore with the introduction of `@gc_preserve`. We have a few guaranteed rooting as mentioned above (`ccall` roots (of `cconvert` return value), `@gc_preserve` and globals) their rooting behavior is documented in their own docstrings (not for global I guess so we can add that). In general, if it is not explicitly documented that something will guarantee the lifetime of an object then there's no such guarantee.

File: base/random/RNGs.jl (hunk 2 above)
Comment (rfourquet) [reply base/random/RNGs.jl]: Ok thanks for the precision (this limitation is not documented in the docstring). I will work on fixing those cases.

File: base/random/RNGs.jl (hunk 1 above)
Comment (Keno) [reply base/random/RNGs.jl]: To clarify, after inlining any uses after may be dead code and eliminated.

Comment (yuyichao) [reply base/random/RNGs.jl]: This is the detail I don't want to go into since I don't want people to rely on it but another way this can be invalid is that the compiler can see you are using only some fields and then discards all other fields.

File: base/iostream.jl [hunk 3]
```diff
@@ -264,7 +264,7 @@ end
 function readbytes_all!(s::IOStream, b::Array{UInt8}, nb)
     olb = lb = length(b)
     nr = 0
-    while nr < nb
+    @gc_preserve b while nr < nb
```
Comment (vtjnash) [inline base/iostream.jl]: should we just use `Ref(b, nr + 1)` instead?

File: src/cgutils.cpp [hunk 4]
```diff
@@ -2108,6 +2108,9 @@ static Value *boxed(jl_codectx_t &ctx, const jl_cgval_t &vinfo)
         return UndefValue::get(T_prjlvalue);
     if (vinfo.constant)
         return maybe_decay_untracked(literal_pointer_val(ctx, vinfo.constant));
+    // This can happen in early bootstrap for `gc_preserve_begin` return value.
+    if (jt == (jl_value_t*)jl_void_type)
+        return maybe_decay_untracked(literal_pointer_val(ctx, jl_nothing));
```
Comment (vtjnash) [inline src/cgutils.cpp]: If `vinfo.typ == jl_void_type` then `vinfo.constant == jl_nothing` and we shouldn't get here. What's violating that?

**Review by vtjnash — APPROVED** [review]

File: base/iostream.jl (hunk 3 above)
Comment (yuyichao) [reply base/iostream.jl]: There's a few different places that uses `pointer(ary, i)` that can be changed, yes.

File: src/cgutils.cpp (hunk 4 above)
Comment (yuyichao) [reply src/cgutils.cpp]: https://github.com/JuliaLang/julia/blob/056b374919e11977d5a8d57b446ad1c72f3e6b1d/src/codegen.cpp#L3926 It's not just a `nothing` but also an LLVM `token` though so I'm avoiding touching that.

**Review by Keno — APPROVED** [review]

File: src/cgutils.cpp (hunk 4 above)
Comment (vtjnash) [reply src/cgutils.cpp]: Ah, ok. Right, this was an intentionally malformed value.

**Comment by StefanKarpinski** [comment]
There's a bunch of cases here where you use `@gc_preserve_begin` and `@gc_preserve_end` pairs instead of the `@gc_preserve` macro even though the latter seems applicable. Was there some reason for that? Too early in bootstrap? Macro lowering having some undesirable effect?

**Comment by yuyichao** [comment]
They are exactly the same. The `@_gc_preserve_begin` and `@_gc_preserve_end` are used just for bootstrap, which is why it's defined right after the inline/noinline macros that serves the same purpose..................

**Comment by StefanKarpinski** [comment]
I figured it was bootstrap-related.
