### PR TITLE
Fix some redefinition warnings in tests, add a missing distclean makefile rule

### LINKED ISSUE #16324: Testall fails in ambiguous
On

```
Julia Version 0.5.0-dev+4047
Commit 8f4e33f* (2016-05-12 08:42 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

testall fails with (showing end of output only, rest available)
```

	From worker 2:	     * checked               in   8.12 seconds, maxrss 1046.56 MB
	From worker 2:	     * inline                in   0.18 seconds, maxrss 1046.68 MB
	From worker 2:	     * boundscheck           in   0.06 seconds, maxrss 1046.77 MB
	From worker 3:	     * misc                  in  12.97 seconds, maxrss 1117.50 MB
WARNING: Method definition ambig(Any, Integer) in module Main at /home/colin/Downloads/julia/test/ambiguous.jl:4 overwritten at /home/colin/Downloads/julia/test/ambiguous.jl:58.
	From worker 3:	     * ambiguous            Skipping Base.<|
	From worker 3:	Skipping Base.>:
	From worker 3:	Skipping Base.active_repl
	From worker 3:	Test Failed
	From worker 2:	     * error                 in   1.83 seconds, maxrss 1047.00 MB
	From worker 3:	  Expression: isempty(detect_ambiguities(Core,Base; imported=true))
	From worker 6:	     * dsp                   in  11.69 seconds, maxrss  230.16 MB
	From worker 2:	     * fft                   in  18.92 seconds, maxrss 1083.67 MB
	From worker 6:	     * examples              in  13.56 seconds, maxrss  275.24 MB
	From worker 5:	     * parallel              in  41.54 seconds, maxrss 1284.36 MB
	From worker 4:	     * cmdlineargs           in  99.29 seconds, maxrss 1039.40 MB
Exception running test ambiguous :
On worker 3:
LoadError: There was an error during testing
 in record at ./test.jl:321
 in do_test at ./test.jl:219
 [inlined code] from ./int.jl:33
 in include_string at ./loading.jl:380
 in include_from_node1 at ./loading.jl:429
 [inlined code] from ./util.jl:179
 in runtests at /home/colin/Downloads/julia/test/testdefs.jl:7
 in #16 at /home/colin/Downloads/julia/test/runtests.jl:36
 [inlined code] from ./promotion.jl:248
 in #308 at ./multi.jl:1030
 in run_work_thunk at ./multi.jl:754
 [inlined code] from ./multi.jl:1030
 in #307 at ./event.jl:46
while loading /home/colin/Downloads/julia/test/ambiguous.jl, in expression starting on line 110
ERROR: LoadError: Some tests exited with errors.
 in (::##11#19)() at /home/colin/Downloads/julia/test/runtests.jl:64
 in cd(::##11#19, ::String) at ./file.jl:48
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:263
 in _start() at ./client.jl:319
while loading /home/colin/Downloads/julia/test/runtests.jl, in expression starting on line 13
Makefile:12: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:568: recipe for target 'testall' failed
make: *** [testall] Error 2
```

### PR DESCRIPTION
**Pull request by tkelman**
and fix #16324

### CODE REVIEW

File: test/ambiguous.jl [hunk 1]
```diff
@@ -107,7 +107,7 @@ ambs = detect_ambiguities(Ambig5)
 @test length(ambs) == 2
 
 # Test that Core and Base are free of ambiguities
-@test isempty(detect_ambiguities(Core, Base; imported=true))
+@test (x->(isempty(x) || println(x)))(detect_ambiguities(Core, Base; imported=true))
```
Comment (vtjnash) [inline test/ambiguous.jl]: println doesn't return a boolean

Comment (tkelman) [inline test/ambiguous.jl]: that's intentional. the test macro doesn't show the contents of the result if isempty returns false, it just shows false. this still triggers an error but prints the contents

Comment (tkelman) [inline test/ambiguous.jl]: though this could probably stand to be refactored for clarity's sake
