### PR TITLE
Replace isfinite check in ranges with lo ≤ x ≤ hi

### LINKED ISSUE #45747: ∈ throws for Float64 with large value with small range
```julia
1e40 ∈ 0:1.0
```
This errors instead of returning false
```
ERROR: InexactError: trunc(Int64, 1.0e40)
Stacktrace:
 [1] trunc
   @ ./float.jl:781 [inlined]
 [2] trunc
   @ ./float.jl:354 [inlined]
 [3] round
   @ ./float.jl:359 [inlined]
 [4] _in_range(x::Float64, r::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64})
   @ Base ./range.jl:1396
 [5] in(x::Float64, r::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64})
   @ Base ./range.jl:1400
 [6] top-level scope
   @ REPL[21]:1
```

### PR DESCRIPTION
**Pull request by LilithHafner**
This `isfinite` check is a problem in at least two cases:
- Working with infinite ranges. If I'm working in nonstandard arithmetic with nonstandard element `a`, `a ∈ 1:a^2` should hold
- Working with ranges over non-numbers The docstring of `AbstractRange` states "Supertype for ranges with elements of type T. UnitRange and other types are subtypes of this." (T need not be a number) whereas `isfinite`'s docstring states "Test whether a number is finite." This check breaks range membership checks for non-numeric elements.

~The check does not make `n = round(Integer, (x - first(r)) / step(r)) + 1` much safer because it is possible to have a number that is too large to round to an Integer and still finite.~

The new check makes `n = round(Integer, (x - first(r)) / step(r)) + 1` much safer, but it could still throw for ranges with length greater than `typemax(Int)`. Fixes #45747.

### CODE REVIEW

**Comment by giordano** [comment]
Needs a test probably?

**Comment by ViralBShah** [comment]
@oscardssmith Review?

**Review by oscardssmith — APPROVED** [review]

**Comment by oscardssmith** [comment]
This looks good, but ranges are very finicky, so this probably should get a pkgeval.

File: base/range.jl [hunk 1]
```diff
@@ -1388,9 +1388,7 @@ function sum(r::AbstractRange{<:Real})
 end
 
 function _in_range(x, r::AbstractRange)
-    if !isfinite(x)
-        return false
-    elseif iszero(step(r))
+    if iszero(step(r))
```
Comment (vyu) [inline base/range.jl:1391]:
```suggestion
    isnan(x) && return false
    if iszero(step(r))
```
The `isfinite` check implicitly covered NaNs. I think an explicit check for NaN is necessary if it's removed? Otherwise `NaN in 1.0:2.0` would throw instead of returning `false`.

Comment (LilithHafner) [reply base/range.jl:1391]: Good catch! Unfortunately, that fix will not work because we don't have `isnan` for non-numeric ranges.

**Comment by LilithHafner** [comment]
Here's a related issue inspired by @vyu's comment: `1e40 ∈ 0:1.0` throws on conversion to Integer.

File: base/range.jl (hunk 1 above)
Comment (LilithHafner) [reply base/range.jl]: I used `first(r) <= x <= last(r)` instead.

**Comment by LilithHafner** [comment]
This should now also support empty ranges with undefined `first`.

File: base/range.jl [hunk 2]
```diff
@@ -1388,14 +1388,12 @@ function sum(r::AbstractRange{<:Real})
...
-    elseif iszero(step(r))
-        return !isempty(r) && first(r) == x
-    else
-        n = round(Integer, (x - first(r)) / step(r)) + 1
-        return n >= 1 && n <= length(r) && r[n] == x
-    end
+    isempty(r) && return false
+    f, l = first(r), last(r)
+    # check for NaN, Inf, and large x that may overflow in the next calculation
+    f <= x <= l || l <= x <= f || return false
```
Comment (N5N3) [inline base/range.jl:1394]: The current change will break `0. in (0. .* (1:10))`
We need to keep the `iszero(step(r))` branch or add `f == x && return true`

Comment (LilithHafner) [reply base/range.jl:1394]: Thanks! I'm starting to understand what "ranges are very finicky" means. CI tests passed despite that bug so we should add a test for `0. in (0. .* (1:10))`.

**Comment by LilithHafner** [comment]
Is the set of assumptions we can make about an `AbstractRange` documented somewhere?
For example, can we assume `first(r) + (length(r)-1) * step(r) ≈ last(r)`?

File: base/range.jl (hunk 2 above)
Comment (LilithHafner) [reply base/range.jl:1402]: `iszero(step(r)) && return true` changes behavior when `first(r) < x <= last(r)` or `last(r) <= x < first(r)` and `iszero(step(r))` to say that `x in r`. I think this is okay because 1) ranges have lengths and a range with `first(r) ≠ last(r)` and `iszero(setp(r))` has no length and 2) a range with step 0, if it did exist, would be continuous, so any number between `first(x)` and `last(x)` should be in it.

**Comment by LilithHafner** [comment]
> This looks good, but ranges are very finicky, so this probably should get a pkgeval.

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45646#issuecomment-1264541397) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/1b5fdf6_vs_95a5ad8/report.html).

**Comment by LilithHafner** [comment]
@nanosoldier `runtests(["BasisFunctions", "HorseML", "OutlierDetectionData", "SimpleChains", "StableTrees", "TensorBoardLogger"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45646#issuecomment-1264618417) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/e91b5c3_vs_51d1a56/report.html).

**Comment by LilithHafner** [comment]
PkgEval game back positive and I think this is ready to go if someone is willing to give it a final look over.

**Comment by oscardssmith** [comment]
looks good to me.

File: base/range.jl (hunk 2 above)
Comment (N5N3) [reply base/range.jl:1402]: I‘m not sure I get it. if `first(r) != last(r) && iszero(step(r))` i'm assuming that `r` must be empty and would be catched with L1391?
