### PR TITLE
Fix compilation with MCJIT

### LINKED ISSUE #15079: New segfault in build during inference
I see a new segfault 100% of the time when building RPM nightlies using LLVM 3.7.1 (including the three Julia patches). It has been introduced over the last two days.

I can do some debugging if you tell me what you need to know.

```
cd /builddir/build/BUILD/julia/base && /builddir/build/BUILD/julia/build/usr/bin/julia -C x86-64 --output-ji /builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji -f coreimg.jl
/bin/sh: line 1: 14588 Segmentation fault      (core dumped) /builddir/build/BUILD/julia/build/usr/bin/julia -C x86-64 --output-ji /builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji -f coreimg.jl
Makefile:214: recipe for target '/builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji' failed
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-23-x86_64/00159825-julia/build.log.gz

### PR DESCRIPTION
**Pull request by vtjnash**
Run `finalize_gc_frame` on functions with MCJIT
and make sure the function hasn't already been emitted
before copying it for native code generation

Fix #15079. Alternative to #15084

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -1075,22 +1075,26 @@ extern "C" void jl_generate_fptr(jl_lambda_info_t *li)
...
-            mover.CloneFunction((Function*)li->functionObjects.functionObject);
-            if (li->functionObjects.specFunctionObject != NULL)
-                mover.CloneFunction((Function*)li->functionObjects.specFunctionObject);
-            if (li->functionObjects.cFunctionList != NULL) {
-                size_t i;
-                cFunctionList_t *list = (cFunctionList_t*)li->functionObjects.cFunctionList;
-                for (i = 0; i < list->len; i++) {
-                    list->data()[i].f = mover.CloneFunction(list->data()[i].f);
+            // see if it has been emitted already (as part of compiling something else)
+            li->fptr = (jl_fptr_t)jl_ExecutionEngine->getFunctionAddress(((Function*)li->functionObjects.functionObject)->getName());
```
Comment (yuyichao) [inline src/codegen.cpp]: Does the fact that this wasn't a problem with ORCJIT means that we were emitting functions mutiple times with ORCJIT?

Comment (Keno) [inline src/codegen.cpp]: ORCJIT checks somewhere else: https://github.com/JuliaLang/julia/blob/4eedd2e045a76de5778e5388d3d1f586d9ad55b0/src/codegen.cpp#L1024
