### PR TITLE
macOS: Don't inspect dead threadtls during exception handling.

### LINKED ISSUE #225: Crash during MTLDispatchListApply
For example, https://buildkite.com/julialang/metal-dot-jl/builds/630#0189615c-46ea-4cb7-8b2c-32d5c4ecea1f. This happens on 1.9.2. Maybe related to https://github.com/JuliaGPU/Metal.jl/issues/138?

### PR DESCRIPTION
**Pull request by maleadt**
Otherwise we may end up with the state of a dead thread, as the system IDs can alias. This can lead to an early return from the exception handler, resulting in e.g. safepoint exceptions being actually delivered to user code.

Alternative to https://github.com/JuliaLang/julia/pull/50747, closes https://github.com/JuliaGPU/Metal.jl/issues/225.

### CODE REVIEW

**Review by topolarity — APPROVED** [review]
LGTM

The bug that you found def makes me suspicious of broader TLS tearing in this code, but I think this is a good low-risk fix for back-porting until we can do a more complete review.

File: src/signals-mach.c [hunk 1]
```diff
@@ -279,12 +279,16 @@ kern_return_t catch_mach_exception_raise(
     int nthreads = jl_atomic_load_acquire(&jl_n_threads);
     for (tid = 0; tid < nthreads; tid++) {
         jl_ptls_t _ptls2 = jl_atomic_load_relaxed(&jl_all_tls_states)[tid];
+        if (_ptls2->current_task == NULL) {
```
Comment (vtjnash) [inline src/signals-mach.c:282]:
```suggestion
        if (jl_atomic_load_relaxed(&_ptls2->current_task) == NULL) {
```

The `current_task` field is _Atomic, so we have a verifier rule that you must specify the intended ordering for it. For this field, the only defined ordering for a load is usually `relaxed`, since we don't have any other ordering defined when we release stored it. (And relaxed is what `jl_thread_suspend_and_get_state2` uses for the same check).

Comment (maleadt) [reply src/signals-mach.c:282]: Thanks

Comment (topolarity) [reply src/signals-mach.c]: Why didn't the verifier catch the unspecified load that was previously below?

Comment (vtjnash) [reply src/signals-mach.c]: I think we skip this file in the verifier, since we only run it on linux for CI.

**Comment by maleadt** [comment]
macOS tests have been hanging on master as well, so seem unrelated. Which is too bad, as it's one of the 2 relevant runs for this PR; but at least macOS-aarch64 passed.
