### PR TITLE
symlink: don't warn on Windows symlink failure (fix #37845)

### LINKED ISSUE #37845: don't warn for failed symlink on Windows (just error)
See https://github.com/JuliaLang/Pkg.jl/issues/2061: in `symlink` on Windows if the symlink operation fails, we print a warning and the throw an error. This means that even if we catch the warning (when, say, we're just testing to see if we _can_ symlink), we end up printing a warning too. PlatformEngines and Tar were disabling logging to suppress this, but this can cause problems with Julia's CI (this is the root cause of the very annoying https://github.com/JuliaLang/julia/issues/37731 CI failures). There are already PRs to stop disabling logging in both of these places: https://github.com/JuliaLang/Pkg.jl/pull/2062, https://github.com/JuliaIO/Tar.jl/pull/76. However, we should also stop printing that warning and instead include the warning test, if at all, in the error message.

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

File: base/file.jl [hunk 1]
```diff
@@ -977,12 +977,13 @@ function symlink(p::AbstractString, np::AbstractString)
...
     err = ccall(:jl_fs_symlink, Int32, (Cstring, Cstring, Cint), p, np, flags)
+    prefix = ""
     @static if Sys.iswindows()
         if err < 0 && !isdir(p)
-            @warn "On Windows, creating file symlinks requires Administrator privileges" maxlog=1 _group=:file
+            prefix = "On Windows, creating symlinks requires Administrator privileges.\n"
         end
     end
-    uv_error("symlink",err)
+    uv_error(prefix * "symlink", err)
```
Comment (vtjnash) [inline base/file.jl:986]: Perhaps preferable to pre-render the strings, and not copy it here each time?

**Comment by StefanKarpinski** [comment]
Decided to combine the Pkg bump that includes not changing the logger with this change since the former was ready and doing them separately seems like a waste of CI.
