### PR TITLE
restore fallback 3-arg `setprecision` method

### LINKED ISSUE #55899: `setprecision(::Function, ::Type, ::Int)` regression
Passes on v1.11, throws `MethodError` on v1.12:

```julia
using Test

struct Issue55899 end

const issue_55899_precision = Ref{Any}(123)

@testset "`setprecision` regression, issue #55899" begin
    function Base.precision(::Type{Issue55899})
        issue_55899_precision[]
    end

    function Base.setprecision(::Type{Issue55899}, p::Int)
        issue_55899_precision[] = p
    end

    function issue_55899_get_set_precision(p::Int)
        f = () -> precision(Issue55899)
        setprecision(f, Issue55899, p)
    end

    for p ∈ (1, 10, 100)
        @test p === issue_55899_get_set_precision(p)
    end
end
```

xref #51362

xref kalmarek/Arblib.jl#187

### PR DESCRIPTION
**Pull request by JeffBezanson**
There should possibly be some other deprecation plan here, but I don't know, I'm just a robot that fixes regressions.

fixes #55899

### CODE REVIEW

**Comment by JeffBezanson** [comment]
OK, I added a news entry and depwarn. What do we think?

File: base/mpfr.jl [hunk 1]
```diff
@@ -1183,9 +1183,29 @@ Often used as `setprecision(T, precision) do ... end`
...
+    and `setprecision`, but it should no longer be relied on. Instead, you
+    should define the 3-argument form directly in a way that uses `ScopedValue`,
+    or recommend that callers use `ScopedValue` and `@with` themselves.
+
 !!! compat "Julia 1.8"
     The `base` keyword requires at least Julia 1.8.
 """
+function setprecision(f::Function, ::Type{T}, prec::Integer; kws...) where T
+    depwarn("""
+            The fallback `setprecision(::Function, ...)` method is deprecated. Types should
```
Comment (Seelengrab) [inline base/mpfr.jl]:
```suggestion
            The fallback `setprecision(::Function, ...)` method is deprecated. Packages overloading this method should
```

Might be a bit clearer for users of those packages, that it's not something they have to implement themselves. Looks good otherwise!

**Review by Seelengrab — APPROVED** [review]

**Comment by topolarity** [comment]
Backported in https://github.com/JuliaLang/julia/pull/58699
