### PR TITLE
Backports for 1.9.0-rc1

### LINKED ISSUE #47658: statestack_set assertion in subtype resolution
I'm getting a segfault in the subtype resolution. I'm not sure how to track this down to its source, but you can reproduce if you clone [this commit](https://github.com/AlgebraicJulia/Catlab.jl/commit/287cd55ba4e6206dc0611b8d573b1f4591a6911a) of Catlab.jl, and then run `julia --project=test test/wiring_diagrams/WiringDiagrams.jl`. What I get when I run this is:

```txt
signal (11): Segmentation fault
in expression starting at /home/o/g/topos/Catlab.jl/test/wiring_diagrams/Directed.jl:177
subtype_unionall at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:793
subtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1257
subtype_unionall at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:805
subtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1254
subtype_unionall at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:805
subtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1254
subtype_unionall at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:805
subtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1254
exists_subtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1391 [inlined]
forall_exists_subtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1419
ijl_subtype_env at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/subtype.c:1881
jl_f_issubtype at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/builtins.c:509
⊑ at ./compiler/typelattice.jl:234
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:157
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2360
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_ext at ./compiler/typeinfer.jl:967
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1000
typeinf_ext_toplevel at ./compiler/typeinfer.jl:996
jfptr_typeinf_ext_toplevel_17736.clone_1 at /nix/store/xrjyvk8mkfxka8c72h52md040wwbz5mn-julia-1.8.3/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2365 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
jl_apply at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
jl_type_infer at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:317
jl_generate_fptr_impl at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/jitlayers.cpp:319
jl_compile_method_internal at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2079 [inlined]
jl_compile_method_internal at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2023
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2357 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
jl_apply at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
do_call at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_stmt_value at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:166 [inlined]
eval_body at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:612
jl_interpret_toplevel_thunk at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_eval_module_expr at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:203 [inlined]
jl_toplevel_eval_flex at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:709
jl_toplevel_eval_flex at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:850
ijl_toplevel_eval_in at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
include_string at ./loading.jl:1428
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2365 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
_include at ./loading.jl:1488
include at ./client.jl:476
unknown function (ip: 0x7f4e0c700dc2)
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2365 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
jl_apply at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
do_call at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_stmt_value at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:166 [inlined]
eval_body at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:612
eval_body at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:522
eval_body at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:522
jl_interpret_toplevel_thunk at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_toplevel_eval_flex at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:850
ijl_toplevel_eval_in at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
include_string at ./loading.jl:1428
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2365 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
_include at ./loading.jl:1488
include at ./Base.jl:419
jfptr_include_57158.clone_1 at /nix/store/xrjyvk8mkfxka8c72h52md040wwbz5mn-julia-1.8.3/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2365 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
exec_options at ./client.jl:303
_start at ./client.jl:522
jfptr__start_27977.clone_1 at /nix/store/xrjyvk8mkfxka8c72h52md040wwbz5mn-julia-1.8.3/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2365 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/gf.c:2547
jl_apply at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
true_main at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/jlapi.c:575
jl_repl_entrypoint at /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/src/jlapi.c:719
main at julia (unknown line)
__libc_start_call_main at /usr/lib/libc.so.6 (unknown line)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 37948610 (Pool: 37937867; Big: 10743); GC: 45
```

My feeling is that perhaps if the underlying logical error of #47654 is sorted out, this might be fixed as a side-effect, but then again it could be completely unrelated.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #48567 
- [x] #48544 
- [x] #48659 
- [x] #46153 
- [x] #48660 
- [x] #45127 
- [x] #48221 
- [x] #48672 
- [x] #48583 
- [x] #48677 
- [x] #48586 
- [x] #48392 
- [x] #48614 
- [x] #46791 
- [x] #48592 
- [x] #48703 
- [x] #48628 
- [x] #48620 
- [x] #48689 
- [x] #48671 
- [x] #48673 
- [x] #48826 
- [x] #48838 
- [x] #48854 
- [x] #48526 
- [x] #48746 
- [x] #48788 
- [x] #48796 
- [x] #48810 
- [x] #48712 
- [x] #48806 
- [x] #48835 
- [x] #48869 
- [x] #48620 
- [x] #47832 
- [x] #48723 
- [x] #48833 
- [x] #48854 
- [x] #48747 

Non-merged PRs with backport label:
- [ ] #48809 
- [ ] #48749 
- [ ] #48726 
- [ ] #48702 
- [ ] #48674 
- [ ] #48642 
- [ ] #48215 
- [ ] #48183 
- [ ] #48050 
- [ ] #47636 
- [ ] #47615

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = "@7b395153e80672f8cdb18f51dd653a85e28b2070", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48733#issuecomment-1441730391) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
Seems like the build failed?

```
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ make[4]: Leaving directory '/source/src/support'
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ make[4]: Entering directory '/source/src/flisp'
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ rm: cannot remove '/source/usr/manifest/SHA': No such file or directory
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ make[4]: Leaving directory '/source/stdlib'
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ make[3]: Leaving directory '/source/stdlib'
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ make[2]: *** [Makefile:64: julia-stdlib] Error 2
Feb 23 14:57:03 amdci8.julia.csail.mit.edu julia-1.8[2811677]:       From worker 2:        │ make[2]: *** Waiting for unfinished jobs....
```

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = "@7b395153e80672f8cdb18f51dd653a85e28b2070", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48733#issuecomment-1442393340) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
Now it failed with:

```
===============================================================================
  ERROR: sha512 checksum failure on Statistics-61a021bcb330e6c52f2435f2abaffc77875ab6f2.tar.gz, should be:
      27e6f153f119638c4ed8e29127db10c1aff4fe5c14217a86a65d2bcb7ffbd3ed
      8e22613ed26fe0b9ffbb525ba00fc673be989d9da50e10fa12fd9a460ceeddcf
  But `sha512sum /source/stdlib/srccache/Statistics-61a021bcb330e6c52f2435f2abaffc77875ab6f2.tar.gz | awk '{ print $1; }'` results in:
      c22dc7c5aa41886a4abc683b5d2be04538ff043cc81e3f5ca482fed0dd160cdf
      ebe7c3d3366b324dc92678d69ce069a92a8ce38d396a7be6fc6bf10c1abfa67e
  This can happen due to bad downloads or network proxies, please check your
  network proxy/firewall settings and delete
  /source/stdlib/srccache/Statistics-61a021bcb330e6c52f2435f2abaffc77875ab6f2.tar.gz
  to force a redownload when you are ready
===============================================================================
make[3]: *** [Makefile:49: Statistics-61a021bcb330e6c52f2435f2abaffc77875ab6f2/source-extracted] Error 2
make[3]: *** Waiting for unfinished jobs....
```

I cannot reproduce locally...

Third time's a charm? 

@nanosoldier `runtests(ALL, vs = "@7b395153e80672f8cdb18f51dd653a85e28b2070", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48733#issuecomment-1445055966) failed. Consult the server logs for more details (cc @maleadt).

**Comment by KristofferC** [comment]
That looks like https://github.com/JuliaLang/julia/issues/48698

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = "@7b395153e80672f8cdb18f51dd653a85e28b2070", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48733#issuecomment-1445436829) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
Still the same build error. I can try wiping the cache of downloaded files, but we don't cache stdlibs as part of `make -C deps getall` (which is the only thing PkgEval caches), so I don't think that would help.

**Comment by KristofferC** [comment]
I thought https://github.com/JuliaLang/julia/issues/48698#issuecomment-1445220844 would have fixed that.

**Comment by KristofferC** [comment]
Maybe now... (https://github.com/JuliaLang/julia/issues/48698#issuecomment-1451666322).

@nanosoldier `runtests(ALL, vs = "@7b395153e80672f8cdb18f51dd653a85e28b2070", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

File: test/compiler/AbstractInterpreter.jl [hunk 1]
```diff
@@ -45,6 +45,14 @@ import Base.Experimental: @MethodTable, @overlay
 @MethodTable(OverlayedMT)
 CC.method_table(interp::MTOverlayInterp) = CC.OverlayMethodTable(CC.get_world_counter(interp), OverlayedMT)
 
+function CC.add_remark!(interp::MTOverlayInterp, ::CC.InferenceState, remark)
+    if interp.meta !== nothing
```
Comment (vchuravy) [inline test/compiler/AbstractInterpreter.jl:49]: In 1.9 the meta field is missing

Comment (vchuravy) [reply test/compiler/AbstractInterpreter.jl:49]: The meta field was introduced in 1d8f7e0723d e.g. #41199 which we didn't backport to 1.9

Comment (vchuravy) [reply test/compiler/AbstractInterpreter.jl:49]: fix incoming.

**Comment by vchuravy** [comment]
```
vchuravy@odin ~/b/julia-1.9> make -C test misc
make: Entering directory '/home/vchuravy/builds/julia-1.9/test'
    JULIA /home/vchuravy/builds/julia-1.9/test/misc
Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 16
  Sys.total_memory() = 125.703 GiB
  Sys.free_memory() = 103.313 GiB

Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
misc       (1) |        started at 2023-03-05T13:45:36.168
┌ Warning: `old_return_args` is deprecated, use `new_return_args` instead.
│   caller = macro expansion at Test.jl:478 [inlined]
└ @ Core ~/builds/julia-1.9/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:478
┌ Warning: `old_return_args` is deprecated, use `new_return_args` instead.
│   caller = macro expansion at Test.jl:478 [inlined]
└ @ Core ~/builds/julia-1.9/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:478
┌ Warning: skipping stftime tests: no locale found for testing
└ @ Main.Test13Main_misc ~/src/julia/test/misc.jl:1099
misc       (1) |         failed at 2023-03-05T16:54:28.430
Test Failed at /home/vchuravy/src/julia/test/misc.jl:496
  Expression: summarysize(Core) > summarysize(Core.Compiler) + Base.summarysize(Core.Intrinsics) > Core.sizeof(Core)
   Evaluated: 42790095 > 60977967 > 0

Test Summary: |    Pass  Fail    Total       Time
  Overall     | 1282259     1  1282260  188m53.6s
    misc      | 1282259     1  1282260  188m52.7s
    FAILURE

The global RNG seed was 0xbd82c5bcade1a3be3610e82bec31468a.

Error in testset misc:
Test Failed at /home/vchuravy/src/julia/test/misc.jl:496
  Expression: summarysize(Core) > summarysize(Core.Compiler) + Base.summarysize(Core.Intrinsics) > Core.sizeof(Core)
   Evaluated: 42790095 > 60977967 > 0
```

188m for this testset is exceeding our timeout on master this takes `52.53s`...

File: src/method.c [hunk 2]
```diff
@@ -447,6 +447,7 @@ JL_DLLEXPORT jl_method_instance_t *jl_new_method_instance_uninit(void)
     li->callbacks = NULL;
     jl_atomic_store_relaxed(&li->cache, NULL);
     li->inInference = 0;
+    li->inInference = 0;
```
Comment (vchuravy) [inline src/method.c:450]: This looks like a mistake in backporting?

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/48733#issuecomment-1455668602) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9ced070_vs_7b39515/report.html).

**Comment by vchuravy** [comment]
@maleadt  https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9ced070_vs_7b39515/GPUCompiler.primary.log
