### PR TITLE
Disallow ranges with Integer eltype but non-integer step

### LINKED ISSUE #32419: StepRange{<:Integer} with non-integer step
It is possible to create a `StepRange{<:Integer}` with non-integer step:
```julia
julia> r = StepRange(1, 1//3, 2)
1:1//3:2

julia> r[2]
ERROR: InexactError: Int64(4//3)
```
Should the creation of such ranges throw an error?

There are methods which expect a `StepRange{<:Integer}` to have an integer step (quite reasonable IMO), and which return wrong results if this is not the case:
```julia
julia> intersect(StepRange(1, 1//3, 2), 1:5)
1//1:1//3:2//1
```

I would prefer the following behavior:
* `StepRange{T,S}(start, step, stop)` throws an error if `T<:Integer` and `!isinteger(step)`
* ~~`StepRange(start, step, stop)` (constructor without type parameters) converts `start` and `stop` to `promote_type(typeof(start), typeof(step), typeof(stop))`, so that `StepRange(1, 1//3, 2)` yields a `StepRange{Rational{Int},Rational{Int}}`, but `StepRange(1//2, 1, 5//2)` still yields a `StepRange{Rational{Int},Int}`~~

### PR DESCRIPTION
**Pull request by sostock**
Fixes #32419.

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by sostock** [comment]
I now added the same check for `StepRangeLen`, since it showed the same behavior.

Before:
```julia
julia> StepRangeLen{Int}(1, 1//2, 5);

julia> collect(ans)
ERROR: InexactError: Int64(3//2)
```
After:
```julia
julia> StepRangeLen{Int}(1, 1//2, 5);
ERROR: ArgumentError: StepRangeLen{<:Integer} cannot have non-integer step
```

**Comment by sostock** [comment]
I added the same check for `LinRange{<:Integer}`.

**Comment by sostock** [comment]
Can this be in 1.5?

File: test/ranges.jl [hunk 1]
```diff
@@ -1324,6 +1333,7 @@ Base.:+(x, y::NotReal) = x + y.val
 Base.zero(y::NotReal) = zero(y.val)
 Base.rem(x, y::NotReal) = rem(x, y.val)
 Base.isless(x, y::NotReal) = isless(x, y.val)
+Base.isinteger(y::NotReal) = isinteger(y.val)
```
Comment (timholy) [inline test/ranges.jl:1336]: Is this still necessary or a leftover? Without it, what happens?

**Review by timholy — APPROVED** [review]
Check one item and then merge. Nice & thorough, thanks!

File: test/ranges.jl (hunk 1 above)
Comment (sostock) [reply test/ranges.jl:1336]: Without this, the test at the following line fails, since `steprange_last` checks whether `NotReal(1)` is an integer.
https://github.com/JuliaLang/julia/blob/e959dde5bbdc2a6a83b2524a9ebd8599c21c34c1/test/ranges.jl#L1337

Comment (timholy) [reply test/ranges.jl:1336]: I worry about adding an API requirement we didn't have before. What about checking `isinteger(start+step)`?

Comment (sostock) [reply test/ranges.jl:1336]: Sounds good to me.

**Comment by timholy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32439#issuecomment-622004898) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ab4c133b8ddd5f1f2a258870be58118c7714f336/e3cfde3_vs_3637c9e/report.md). cc @ararslan

**Comment by sostock** [comment]
Can this be in 1.6?

**Comment by StefanKarpinski** [comment]
@timholy this good to go from your POV?
