### PR TITLE
fix #32699, more accurate apply_type_tfunc for NamedTuple

### LINKED ISSUE #32699: better upper bounds in apply_type_tfunc for NamedTuple
Here's an example where the resulting `NamedTuple{names, _A) where _A` type is not ideal since it completely discards valid information up to that point.
```julia
8 ── %21 = Base.getfield(%14, :id)::Array{Int64,1}
│    %22 = Base.arrayref(true, %21, %15)::Int64
│    %23 = Base.getfield(%16, :salary)::Array{Union{Missing, Float64},1}
│    %24 = Base.arrayref(true, %23, %17)::Union{Missing, Float64}
│    %25 = (isa)(%24, Missing)::Bool
└───       goto #10 if not %25
9 ──       goto #13
10 ─ %28 = (isa)(%24, Float64)::Bool
└───       goto #12 if not %28
11 ─ %30 = π (%24, Float64)
│    %31 = Base.sitofp(Float64, 2)::Float64
│    %32 = Base.mul_float(%30, %31)::Float64
└───       goto #13
12 ─       Core.throw(ErrorException("fatal error in type inference (type bound)"))::Union{}
└───       $(Expr(:unreachable))::Union{}
13 ┄ %36 = φ (#9 => $(QuoteNode(missing)), #11 => %32)::Union{Missing, Float64}
│    %37 = Core.tuple(%22, %36)::Tuple{Int64,Union{Missing, Float64}}
│    %38 = (NamedTuple{(:id, :y),T} where T<:Tuple)(%37)::NamedTuple{(:id, :y),_A} where _A
```
@JeffBezanson thought it should be valid/fine to include an upper bound here, so that we end up with `NamedTuple{(:id, :y), _A} where _A <: Tuple{Int64, Union{Missing, Float64}`

### PR DESCRIPTION
**Pull request by JeffBezanson**
This can make inference a bit slower, so I tried limiting it to NamedTuple types with known names, to mitigate the effects a bit.

@quinnj @timholy See how this works for you.

fixes #32699

### CODE REVIEW

**Comment by quinnj** [comment]
image

**Comment by timholy** [comment]
The inference looks great! In #36322 I failed to record which package's invalidations I was looking at. I think it was FilePathsBase, and I haven't seen `load_direct_deps` pop up, so I think it's likely this fixes it. Thanks!

**Comment by quinnj** [comment]
Yep, the inference is looking super spiffy, though it seems the last part of my work-flow is failing to inline (`Tables.eachcolumns`):
```julia
│    %33 = Core.tuple(%20, %32)::Tuple{Int64,Union{Missing, Float64}}
│    %34 = (NamedTuple{(:x, :y),T} where T<:Tuple)(%33)::NamedTuple{(:x, :y),_A} where _A<:Tuple{Int64,Union{Missing, Float64}}
└───       goto #14
14 ─       goto #15
15 ┄ %37 = φ (#7 => true, #14 => false)::Bool
│    %38 = φ (#14 => %34)::NamedTuple{(:x, :y),_A} where _A<:Tuple{Int64,Union{Missing, Float64}}
│    %39 = φ (#14 => %16)::Int64
└───       goto #17 if not %37
16 ─       goto #20
17 ─ %42 = Base.add_int(%3, 1)::Int64
│          Tables.eachcolumns(Tables.add_or_widen!, sch, %38, columns, %42, updated, $(QuoteNode(Base.HasLength())))::Any
```
Is that failure to inline related? Like, the inline-cost is calculated too expensive because we have `NamedTuple{(:x, :y),_A} where _A<:Tuple{Int64,Union{Missing, Float64}}`?

(I've double checked that my definitions of `eachcolumns` and related calls all have `@inline` appropriately).

File: base/compiler/tfuncs.jl [hunk 1]
```diff
@@ -1122,13 +1128,34 @@ function apply_type_tfunc(@nospecialize(headtypetype), @nospecialize args...)
...
+                # Is this the second parameter to a NamedTuple?
+                if isnamedtuple && isa(ua, UnionAll) && uw.parameters[2] === ua.var
+                    # If the names are known, keep the upper bound (which we know is
+                    # at most Tuple), but otherwise widen to Tuple.
+                    # This is a widening heuristic to avoid keeping type information
+                    # that's unlikely to be useful.
+                    if uw.parameters[1] isa Tuple || (i == 2 && tparams[1] isa Tuple)
+                        if ub >: Tuple
+                            ub = Tuple
+                        end
```
Comment (vtjnash) [inline base/compiler/tfuncs.jl:1140]: `ub = typeintersect(ub, Tuple)`?

File: base/compiler/tfuncs.jl [hunk 2]
```diff
@@ -1122,13 +1128,34 @@ function apply_type_tfunc(@nospecialize(headtypetype), @nospecialize args...)
             #        ai = ai.body
             #    end
             else
+                # Is this the second parameter to a NamedTuple?
+                if isnamedtuple && isa(ua, UnionAll) && uw.parameters[2] === ua.var
+                    # If the names are known, keep the upper bound (which we know is
+                    # at most Tuple), but otherwise widen to Tuple.
+                    # This is a widening heuristic to avoid keeping type information
+                    # that's unlikely to be useful.
+                    if uw.parameters[1] isa Tuple || (i == 2 && tparams[1] isa Tuple)
```
Comment (vtjnash) [inline base/compiler/tfuncs.jl:1137]: This feels like it assumes NamedTuple can only be used in very specific ways. But I don't see a particular reason to believe that `i == 2` implies anything about it being the bound for the second parameter. As a trivial counter example, we can just flip the order of them:

```
julia> NamedTuple{T, S} where {S, T}
NamedTuple{T,S} where T where S

julia> ans{Tuple{Int}, (:a,)}
NamedTuple{(:a,),Tuple{Int64}}
```

File: base/compiler/tfuncs.jl [hunk 3]
```diff
@@ -1105,8 +1108,11 @@ function apply_type_tfunc(@nospecialize(headtypetype), @nospecialize args...)
             #    ai = rename_unionall(ai)
             #    unw = unwrap_unionall(ai)
             #end
+            ub = ai <: Type ? instanceof_tfunc(ai)[1] : Any
```
Comment (vtjnash) [inline base/compiler/tfuncs.jl:1111]:
```suggestion
            ub = widenconst(ai) <: Type ? instanceof_tfunc(ai)[1] : Any
```

File: base/compiler/tfuncs.jl (hunk 2 above)
Comment (JeffBezanson) [reply base/compiler/tfuncs.jl:1137]: That's what `uw.parameters[2] === ua.var` above is trying to check for --- that the var we're substituting for corresponds to the second parameter.

File: base/compiler/tfuncs.jl [hunk 4]
```diff
@@ -1122,13 +1129,32 @@ function apply_type_tfunc(@nospecialize(headtypetype), @nospecialize args...)
...
+                    # This is a widening heuristic to avoid keeping type information
+                    # that's unlikely to be useful.
+                    if uw.parameters[1] isa Tuple || (i == 2 && tparams[1] isa Tuple)
+                        ub = typeintersect(ub, Tuple)
+                    else
+                        ub = Tuple
+                    end
+                else
+                    ub = Any
+                end
```
Comment (vtjnash) [inline base/compiler/tfuncs.jl:1145]:
```suggestion
                    if !(uw.parameters[1] isa Tuple || (i == 2 && tparams[1] isa Tuple))
                        ub = Any
                    end
                else
                    ub = Any
                end
```

**Review by vtjnash — COMMENTED** [review]
Very late night thought: didn't we attempt part of this 6 months ago, before we realized this bound would be wrong, and did https://github.com/JuliaLang/julia/pull/33472 instead?

Counter-example:
```julia
julia> NamedTuple{<:Any, <:Any}
NamedTuple{var"#s1",var"#s2"} where var"#s2" where var"#s1"
```

File: base/compiler/tfuncs.jl (hunk 2 above)
Comment (vtjnash) [reply base/compiler/tfuncs.jl:1138]: Ah. I guess it's just the `i == 2 && tparams[1] isa Tuple` that seemed strange, but I suppose that variable can be assumed that it must appear as the names for the NamedTuple in this case. And it's hopefully not important to deal with the case where the variables are swapped.

File: base/compiler/tfuncs.jl (hunk 4 above)
Comment (JeffBezanson) [reply base/compiler/tfuncs.jl:1145]: Ah, yes. The `Tuple` bound should be valid only if `ai_w <: Type` above holds, i.e. if whatever we're putting in there is not a typevar.

Comment (vtjnash) [reply base/compiler/tfuncs.jl:1145]: I think not even then?
```
julia> NamedTuple{<:Any, Val{T}} where T
NamedTuple{var"#s1",Val{T}} where var"#s1" where T
```

Comment (JeffBezanson) [reply base/compiler/tfuncs.jl:1145]: Ouch.

**Review by vtjnash — APPROVED** [review]

**Comment by quinnj** [comment]
Exciting! @JeffBezanson , do you have any thoughts on my inlining question from above? Just wondered if you were aware of something obvious. I'm planning on looking into it a little deeper as well.

**Comment by JeffBezanson** [comment]
Since we infer `eachcolumns` as `Any`, I imagine there might be dynamic dispatches in it, which make the inlining cost very high.
