### PR TITLE
replace current_module() with @__MODULE__

### LINKED ISSUE #20487: isdefined() gives unexpected result inside of __init__()
When trying to test if a particular value had been set within `deps.jl`, I discovered that `__init__()` is run inside the `Main` module (e.g. `current_module()` returns `Main`) which causes fun strangeness like the following:

```julia
# module_test.jl
module Foo

const bar = 1
function __init__()
    if isdefined(:bar)
        println("bar is defined!")
    else
        println("bar is undefined!")
    end

    println("Value of bar: $bar")
end
end # module Foo

using Foo
```
```
$ julia module_test.jl
bar is undefined!
Value of bar: 1
```

This can be easily remedied by using `isdefined(Foo, :bar)`, but it seems to me that having a situation where `isdefined()` fails to resolve scope the same way as the actual compiler is a bug.

### PR DESCRIPTION
**Pull request by vtjnash**
Passes macros a `__module__` argument (like the new `__source__` argument from #21746), allowing them to inspect and configure themselves based on their evaluation context.

This removes current_module dependence from `include`:
Instead, we use the same trick as for `eval` (they are basically the same function after all) to create a module-relative function in each non-bare module.

fixes #20487

### CODE REVIEW

File: base/reflection.jl [hunk 1]
```diff
@@ -159,17 +160,23 @@ Determine the module containing the definition of a `DataType`.
...
-argument is [`current_module()`](@ref).
+Determine whether a global is declared `const` in a given `Module`.
 """
 isconst(m::Module, s::Symbol) =
     ccall(:jl_is_const, Cint, (Any, Any), m, s) != 0
 
+"""
+    @isdefined s -> Bool
+
+Get whether symbol `s` is defined in the current scope.
```
Comment (tkelman) [inline base/reflection.jl]: "Get whether" sounds a bit strange, that wording isn't used in any other docstrings

File: src/builtins.c [hunk 2]
```diff
@@ -524,6 +523,11 @@ JL_CALLABLE(jl_f_isdefined)
     }
     if (nargs != 2) {
         JL_NARGS(isdefined, 1, 1);
+        jl_depwarn("`isdefined(:symbol)` is deprecated, "
```
Comment (tkelman) [inline src/builtins.c]: add a note in deprecated.jl reminding to delete this when the other deprecations from this PR are removed

**Comment by StefanKarpinski** [comment]
Can this info be stuffed into the `__source__` type? It seems better to have one magic argument than >1 magic argument.

**Comment by vtjnash** [comment]
Of course it's possible to make a new type that encapsulates both, but I'm not certain that's entirely desirable. I don't currently anticipate this growing beyond these 2 arguments. Although we might eventually decide to introduce other names for accessing other contextual information for debugging such as `__function__::Symbol`.

**Comment by StefanKarpinski** [comment]
> I don't currently anticipate this growing beyond these 2 arguments.

Famous last words. Is it time to officially reserve names that start and end with double underscores yet? Or are just going to continue to hope that security-through-sufficient-number-of-underscores works in the future?

**Comment by vtjnash** [comment]
Only in macro arguments :P Are you going to reopen https://github.com/JuliaLang/julia/issues/18249?

**Comment by StefanKarpinski** [comment]
Wasn't well received last time, so 🤷‍♂️ .

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22064#issuecomment-304433860) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/677ec71e2bdfae8b56088bcbe22c7296a0ff2b53/5d27526_vs_3e3f966/report.md). cc @jrevels

**Comment by tkelman** [comment]
Is the reason this can't be `__source__.module` that `__source__` is about the definition site whereas `__module__` is about the call site?

File: base/deprecated.jl [hunk 3]
```diff
@@ -1348,6 +1347,44 @@ end
...
 @deprecate MersenneTwister(filename::AbstractString)  srand(MersenneTwister(0), read!(filename, Array{UInt32}(Int(4))))
 
+# also remove all support machinery in src for current_module when removing this deprecation
+_current_module() = ccall(:jl_get_current_module, Ref{Module}, ())
+@noinline function binding_module(s::Symbol)
+    depwarn("binding_module(symbol) is deprecated, use `binding_module(__module__, symbol)` instead.", :binding_module)
+    return binding_module(_current_module(), s)
+end
+@noinline function expand(x::ANY)
+    depwarn("expand(x) is deprecated, use `expand(__module__, x)` instead.", :expand)
```
Comment (tkelman) [inline base/deprecated.jl]: using `__module__` is only relevant syntax when this is used inside a macro definition, right? for interactive repl usage wouldn't `@__MODULE__` be the more useful way to call it? or write this as `expand(module, x)` and let the user determine where they want to get the module argument from

File: base/interactiveutil.jl [hunk 4]
```diff
@@ -676,13 +679,13 @@ end
...
 """
-    whos(io::IO=STDOUT, m::Module=current_module(), pattern::Regex=r"")
+    whos(io::IO=STDOUT, m::Module=Main, pattern::Regex=r"")
 
 Print information about exported global variables in a module, optionally restricted to those matching `pattern`.
 
 The memory consumption estimate is an approximate lower bound on the size of the internal structure of the object.
 """
-function whos(io::IO=STDOUT, m::Module=current_module(), pattern::Regex=r"")
+function whos(io::IO=STDOUT, m::Module=Main, pattern::Regex=r"")
```
Comment (tkelman) [inline base/interactiveutil.jl]: the behavior change here is worth noting more visibly for anyone who may be calling this programmatically inside non-main modules

File: base/deprecated.jl [hunk 5]
```diff
@@ -1348,6 +1347,44 @@ end
...
+@noinline function macroexpand(x::ANY)
+    depwarn("macroexpand(x) is deprecated, use `macroexpand(__module__, x)` instead.", :macroexpand)
+    return macroexpand(_current_module(), x)
+end
+@noinline function isconst(s::Symbol)
+    depwarn("isconst(symbol) is deprecated, use `isconst(__module__, symbol)` instead.", :isconst)
+    return isconst(_current_module(), s)
+end
+@noinline function include_string(txt::AbstractString, fname::AbstractString)
+    depwarn("include_string(string, fname) is deprecated, use `include_string(__module__, string, fname)` instead.", :include_string)
```
Comment (tkelman) [inline base/deprecated.jl]: what about 1-arg `include_string(::AbstractString)` ?

File: base/markdown/Markdown.jl [hunk 6]
```diff
@@ -37,25 +37,24 @@ function mdexpr(s, flavor = :julia)
...
 
 macro md_str(s, t...)
     mdexpr(s, t...)
 end
 
-doc_str(md, file, mod) = (md.meta[:path] = file; md.meta[:module] = mod; md)
-doc_str(md::AbstractString, file, mod) = doc_str(parse(md), file, mod)
+function doc_str(md, source::LineNumberNode, mod::Module)
+    md.meta[:path] = source.file
+    md.meta[:path] = isa(source.file, Symbol) ? String(source.file) : ""
```
Comment (tkelman) [inline base/markdown/Markdown.jl]: is the first assignment to `md.meta[:path]` redundant?

File: base/reflection.jl [hunk 7]
```diff
@@ -842,9 +849,9 @@ end
 """
     which(symbol)
 
-Return the module in which the binding for the variable referenced by `symbol` was created.
+Return the module in which the binding for the variable referenced by Main.`symbol` was created.
```
Comment (tkelman) [inline base/reflection.jl]: also a behavior change for calls to this from non-main modules that should be noted more prominently somewhere

and this should maybe be formatted with Main inside the code highlighting - not sure if `Main.$symbol` is quite the right way to show it?

File: base/sysimg.jl [hunk 8]
```diff
@@ -3,18 +3,43 @@
...
+    result
+end
+function include(path::AbstractString)
+    local result
+    if INCLUDE_STATE === 1
+        result = Core.include(Base, path)
+    elseif INCLUDE_STATE === 2
+        result = _include(Base, path)
+    else
+        # to help users avoid error (accidentally evaluating into Base), this is deprecated
```
Comment (tkelman) [inline base/sysimg.jl]: if it should become an error eventually, then add a reminder note in deprecated.jl

File: doc/src/manual/metaprogramming.md [hunk 9]
```diff
@@ -530,6 +530,12 @@ LineNumberNode
   file: Symbol REPL[2]
 ```
 
+The argument `__module__` provides information (in the form of a `Module` object)
+about the expansion context of the macro invocation.
+This allows macros to lookup contextual information, such as existing bindings,
```
Comment (tkelman) [inline doc/src/manual/metaprogramming.md]: "lookup" is a noun, "look up" is a verb

File: doc/src/manual/metaprogramming.md [hunk 10]
```diff
@@ -530,6 +530,12 @@ LineNumberNode
...
+or to insert as an extra argument to a runtime function call doing self-reflection.
```
Comment (tkelman) [inline doc/src/manual/metaprogramming.md]: insert what as an extra argument?

File: test/choosetests.jl [hunk 11]
```diff
@@ -32,7 +32,7 @@ function choosetests(choices = [])
         "replutil", "sets", "test", "goto", "llvmcall", "llvmcall2", "grisu",
         "nullable", "meta", "stacktraces", "profile", "libgit2", "docs",
         "markdown", "base64", "serialize", "misc", "threads",
-        "enums", "cmdlineargs", "i18n", "workspace", "libdl", "int",
+        "enums", "cmdlineargs", "i18n", "libdl", "int",
```
Comment (tkelman) [inline test/choosetests.jl]: put back?

File: test/parse.jl [hunk 12]
```diff
@@ -747,20 +747,23 @@ for (str, tag) in Dict("" => :none, "\"" => :string, "#=" => :comment, "'" => :c
...
-    quote
+    return quote
         @inline function foo(sub)
             it = 1
         end
     end
 end
 end
-let ex = expand(:(@M16096.iter))
-    @test !(isa(ex,Expr) && ex.head === :error)
```
Comment (tkelman) [inline test/parse.jl]: why the change in what's being tested here?

File: test/reflection.jl [hunk 13]
```diff
@@ -254,11 +254,14 @@ export this_is_not_defined
...
-@test isexported(current_module(), :this_is_not_defined)
-@test !isexported(current_module(), :this_is_not_exported)
+@test isexported(@__MODULE__, :this_is_not_defined)
+@test !isexported(@__MODULE__, :this_is_not_exported)
 const a_value = 1
-@test which(:a_value) == current_module()
-@test !isexported(current_module(), :a_value)
+@test Base.which_module(@__MODULE__, :a_value) === @__MODULE__
+@test @which(a_value) === @__MODULE__
+@test_throws ErrorException which(:a_value)
```
Comment (tkelman) [inline test/reflection.jl]: would this break if tests were run in no-isolation mode?

**Comment by vtjnash** [comment]
> Is the reason this can't be `__source__.module` that `__source__` is about the definition site [parser] whereas `__module__` is about the call site [eval]?

Yeah, that's basically why I don't think they should be packed into the same argument

File: base/deprecated.jl (hunk 3 above)
Comment (vtjnash) [inline base/deprecated.jl]: For the REPL, you can just type `Main`. There's nothing particularly special about the name `__module__` that makes it any different from `module`. I thought it was nicely reminiscent of the macro argument name (allowing easier search), and also provided underlining of the change (highlighting word diff).

File: base/interactiveutil.jl (hunk 4 above)
Comment (vtjnash) [inline base/interactiveutil.jl]: It's not actually a behavioral change in that case (both the old and new function would have gotten the argument value `Main` in either case). So this is basically just a bugfix that's being forced by the deprecation of this function. This confusion is basically why moving to `@__MODULE__` is a much simpler, more understandable API. (It is a behavioral change if you were calling this while defining a new module, even if called from the Main module, but we didn't have the `STDOUT` variable available then, so you wouldn't have been able to call this method anyways).

File: base/reflection.jl (hunk 7 above)
Comment (vtjnash) [inline base/reflection.jl]: As I wrote above, `current_module` returned `Main`, regardless of where it was called from. Yes, this was highly confusing.

File: test/parse.jl (hunk 12 above)
Comment (vtjnash) [inline test/parse.jl]: I switched from testing that it doesn't fail, to testing that it does succeed (e.g. from a weaker test to a stronger)

File: base/deprecated.jl (hunk 3 above)
Comment (tkelman) [inline base/deprecated.jl]: we normally only put underscores around something when it's special, the deprecation replacement messages are more in line with names we would use for a docstring

File: base/interactiveutil.jl (hunk 4 above)
Comment (tkelman) [inline base/interactiveutil.jl]: you couldn't call `whos` to a buffer from within a package?

Comment (vtjnash) [inline base/interactiveutil.jl]: There's an infinite set of things that someone "could have done" that this PR breaks. I just don't generally care to theorize about them unless someone first shows that it's plausible and meaningful.

Comment (tkelman) [inline base/interactiveutil.jl]: that's an insulting and unhelpful response to a request to document the breaking behavior changes more clearly.

Comment (vtjnash) [inline base/interactiveutil.jl]: also added documentation of change: https://github.com/JuliaLang/julia/pull/22064/files#diff-8312ad0561ef661716b48d09478362f3R68

**Comment by tkelman** [comment]
is it really necessary to deprecate 1-argument `include_string` ? why can't that be made to behave like 1-argument `eval` ?

**Comment by vtjnash** [comment]
I want to deprecate that function too (in favor of `@eval`), I just haven't gotten that PR ready yet. But more importantly, looking though Github search for `include_string`, the method they usually actually wanted was the one I just added.

**Comment by tkelman** [comment]
then should there be an `@include_string` ? or even `@include_str` custom literals?

**Comment by vtjnash** [comment]
Most of them actually wanted the 2-arg form that I just added (and were using ugly hacks to simulate it). The rest didn't want this at all, but are using it for syntax deprecation purposes (so they would probably use `@include_str` instead if that had been available, but I'm disinclined to add a feature that's only needed by deprecations)

**Comment by tkelman** [comment]
> I'm disinclined to add a feature that's only needed by deprecations

Given we didn't implement conditional parsing, it's pretty widely used and more idiomatic than the obvious alternative of `eval(parse("..."))`.

File: base/deprecated.jl [hunk 14]
```diff
@@ -1348,6 +1347,45 @@ end
...
+@noinline function macroexpand(x::ANY)
+    depwarn("macroexpand(x) is deprecated, use `macroexpand(module, x)` instead.", :macroexpand)
+    return macroexpand(_current_module(), x)
+end
+@noinline function isconst(s::Symbol)
+    depwarn("isconst(symbol) is deprecated, use `isconst(module, symbol)` instead.", :isconst)
+    return isconst(_current_module(), s)
+end
+@noinline function include_string(txt::AbstractString, fname::AbstractString="string")
+    depwarn("include_string(string, fname) is deprecated, use `include_string(module, string, fname)` instead.", :include_string)
```
Comment (tkelman) [inline base/deprecated.jl]: since `fname` is pretty rarely used, would be less confusing to give separate depwarns for 1-arg vs 2-arg forms

Comment (vtjnash) [inline base/deprecated.jl]: packages likely should be using it, so we can give correct backtraces

**Comment by vtjnash** [comment]
> Given we didn't implement conditional parsing, it's pretty widely used and more idiomatic than the obvious alternative of eval(parse("...")).

What's your point? It's not very widely used: Github search indicates ~20 packages will need to be updated. But this in no way contradicts my statement that I'm not going to add a feature to base that might strictly have been useful to define in Compat.jl.

The downside of `parse` is that it doesn't accept a filename and only returns a single Expr. The `Base.parse_input_line` function is more useful in that regard. However, IMO, a more useful definition would be:
```julia
module Compat
macro compat_parse(version, new, old)
    return quote
        let s = (VERSION >= $(esc(version)) ? $(QuoteNode(new)) : $(QuoteNode(old)))
            include_string($__module__, s, $("$(__source__.file):$(__source__.line)"))
        end
    end
end
end
```
```julia
@compat_parse(
    v"0.6.0",
    """new syntax""",
    """old syntax""")
```

File: base/deprecated.jl (hunk 14 above)
Comment (tkelman) [inline base/deprecated.jl]: doesn't change the "would be less confusing" point at all, otherwise the deprecation warning doesn't match the code that triggered it

File: doc/src/manual/metaprogramming.md [hunk 15]
```diff
@@ -534,6 +534,13 @@ LineNumberNode
   file: Symbol none
 ```
 
+The argument `__module__` provides information (in the form of a `Module` object)
+about the expansion context of the macro invocation.
+This allows macros to look up contextual information, such as existing bindings,
+or to insert it as an extra argument to a runtime function call doing self-reflection
```
Comment (tkelman) [inline doc/src/manual/metaprogramming.md]: to insert what?

File: src/builtins.c (hunk 2 above)
Comment (tkelman) [inline src/builtins.c]: "support machinery in src for current_module" is not very clear what it's referring to

File: doc/src/manual/metaprogramming.md (hunk 15 above)
Comment (vtjnash) [inline doc/src/manual/metaprogramming.md]: the subject of both sentences in the paragraph: `the argument __module__`

File: src/builtins.c (hunk 2 above)
Comment (vtjnash) [inline src/builtins.c]: There's a lot of it scattered everywhere. Do you really need me to write you a sed script

File: doc/src/manual/metaprogramming.md (hunk 15 above)
Comment (tkelman) [inline doc/src/manual/metaprogramming.md]: does not read clearly

**Review by tkelman — DISMISSED** [review]
deprecation warning for a call to `include_string("foo")` should not suggest the user called it with more arguments than they did

**Comment by JeffBezanson** [comment]
> > Is the reason this can't be `__source__.module` that `__source__` is about the definition site [parser] whereas `__module__` is about the call site [eval]?

> Yeah, that's basically why I don't think they should be packed into the same argument

I'm fine with having them as separate arguments, but I'm a bit confused --- aren't both about the location of the call site?

**Comment by vtjnash** [comment]
> I'm fine with having them as separate arguments, but I'm a bit confused --- aren't both about the location of the call site?

Both come from the call site (obviously - that's the definition of being an argument). But one comes syntatically from the parser and one comes dynamically from the scope.

**Comment by JeffBezanson** [comment]
Got it.

> obviously - that's the definition of being an argument

Obviously, that's not what I meant, which is why I said "about the location of the call site" and not "from the call site".

**Comment by vtjnash** [comment]
> Obviously, that's not what I meant

right. that was supposed to be read in jest, but I forget the :)

File: src/builtins.c (hunk 2 above)
Comment (tkelman) [inline src/builtins.c]: again, not a helpful attitude. enough information so that it can be cleaned up completely would be relevant.

**Comment by JeffBezanson** [comment]
Good change. Nice to be rid of that piece of global state.

The NEWS and deprecation for `current_module` should more clearly state that `@__MODULE__` doesn't do the same thing; it's not a drop-in replacement. Should say that it gives the lexically-enclosing module, and that `__module__` should be used for calls from macros.

File: src/builtins.c (hunk 2 above)
Comment (vtjnash) [inline src/builtins.c]: delete every line containing the deprecated method:
```
grep -RI current_module . | wc -l
62
```
and then refactor the `eval` methods to reflect the fact that this information no longer needs to be maintained

File: src/ast.c [hunk 16]
```diff
@@ -109,14 +110,19 @@ static jl_ast_context_t jl_ast_main_ctx;
...
-#define JL_AST_PRESERVE_PUSH(ctx, _roots, old_roots)    \
-    jl_array_t *_roots = NULL;                          \
-    jl_array_t **old_roots = ctx->roots;                \
-    ctx->roots = &_roots;                               \
-    JL_GC_PUSH1(&_roots)
-#define JL_AST_PRESERVE_POP(ctx, old_roots)     \
+#define JL_AST_PRESERVE_PUSH(ctx, _roots, old, inmodule)  \
+    jl_array_t *(_roots) = NULL;                \
+    struct { jl_array_t **roots;                \
+             jl_module_t *module; } (old);      \
```
Comment (tkelman) [inline src/ast.c]: I don't think msvc likes this initializer style
```
ast.c
c:/projects/julia/src/ast.c(443) : error C2143: syntax error : missing ';' before '<L_TYPE_raw>'
c:/projects/julia/src/ast.c(443) : error C2059: syntax error : '('
c:/projects/julia/src/ast.c(443) : error C2065: 'old_roots' : undeclared identifier
c:/projects/julia/src/ast.c(443) : error C2228: left of '.roots' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(443) : error C2228: left of '.module' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(446) : error C2065: 'old_roots' : undeclared identifier
c:/projects/julia/src/ast.c(446) : error C2228: left of '.roots' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(446) : error C2228: left of '.module' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(967) : error C2143: syntax error : missing ';' before '<L_TYPE_raw>'
c:/projects/julia/src/ast.c(967) : error C2059: syntax error : '('
c:/projects/julia/src/ast.c(967) : error C2065: 'old_roots' : undeclared identifier
c:/projects/julia/src/ast.c(967) : error C2228: left of '.roots' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(967) : error C2228: left of '.module' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(971) : error C2065: 'old_roots' : undeclared identifier
c:/projects/julia/src/ast.c(971) : error C2228: left of '.roots' must have class/struct/union
        type is 'unknown-type'
c:/projects/julia/src/ast.c(971) : error C2228: left of '.module' must have class/struct/union
        type is 'unknown-type'
make[2]: *** [ast.o] Error 2
```

Comment (vtjnash) [inline src/ast.c]: Is it complaining about the parenthesis? Those aren't necessary, I just used them to make the macro arguments more visible. Or is it complaining that the struct doesn't have a name (https://msdn.microsoft.com/en-us/library/c89bw853(v=vs.100).aspx)?

Comment (tkelman) [inline src/ast.c]: I suspect the later errors are nonsense after the first syntax error. What would it look like if given a name?

**Comment by stevengj** [comment]
I have to say I don't understand why the 1-argument `include_string` was deprecated here.   Vague plans to replace it later don't seem like a good justification.

(That being said, in my ChangePrecision package I found `include_string` insufficiently flexible and ended up [using the undocumented `Base.parse_input_line` instead](https://github.com/stevengj/ChangePrecision.jl/blob/4f48a3ccbb8ac723564a1ff65a0c03e729d822a9/src/ChangePrecision.jl#L106-L112).)
