### PR TITLE
Fix-ups for sorting workspace/buffer (#45330)

### LINKED ISSUE #45568: Bug in sorting offset vectors
This bug was introduced by https://github.com/JuliaLang/julia/pull/45330 which tries to reduce the size of an allocated workspace to only what is needed. If sorting a `v::AbstractVector` on indices `lo:hi`, it allocates `similar(v, hi)` which has indices `1:hi`, which may be insufficient if `lo < 1`. The right answer is to allocate `similar(v, lo:hi)`, but that depends on loading OffsetArrays which does not happen in Base. Instead, we can use the simpler `similar(v)` to get a workspace that contains all of `lo:hi` (provided they are in bounds in the original vector).

```
julia> sort!(OffsetArray(rand(200), -10))
ERROR: InexactError: check_top_bit(UInt64, -9)
Stacktrace:
  [1] throw_inexacterror(f::Symbol, #unused#::Type{UInt64}, val::Int64)
    @ Core ./boot.jl:616
  [2] check_top_bit
    @ ./boot.jl:630 [inlined]
  [3] toUInt64
    @ ./boot.jl:741 [inlined]
  [4] UInt64
    @ ./boot.jl:771 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] setindex!
    @ ./array.jl:959 [inlined]
  [7] radix_sort!(v::Base.ReinterpretArray{UInt64, 1, Float64, OffsetVector{Float64, Vector{Float64}}, false}, lo::Int64, hi::Int64, bits::UInt64, t::Base.ReinterpretArray{UInt64, 1, Float64, Vector{Float64}, false}, chunk_size::UInt8)
    @ Base.Sort ~/.julia/dev/julia_dm/base/sort.jl:699
  [8] radix_sort!
    @ ./sort.jl:685 [inlined]
  [9] sort!(v::OffsetVector{Float64, Vector{Float64}}, lo::Int64, hi::Int64, a::Base.Sort.AdaptiveSort{Base.Sort.QuickSortAlg}, o::Base.Sort.Float.Right, t::Nothing)
    @ Base.Sort ~/.julia/dev/julia_dm/base/sort.jl:859
 [10] fpsort!(v::OffsetVector{Float64, Vector{Float64}}, a::Base.Sort.AdaptiveSort{Base.Sort.QuickSortAlg}, o::Base.Order.ForwardOrdering, t::Nothing)
    @ Base.Sort.Float ~/.julia/dev/julia_dm/base/sort.jl:1541
 [11] sort!
    @ ./sort.jl:1551 [inlined]
 [12] #sort!#8
    @ ./sort.jl:927 [inlined]
 [13] sort!(v::OffsetVector{Float64, Vector{Float64}})
    @ Base.Sort ~/.julia/dev/julia_dm/base/sort.jl:920
 [14] top-level scope
    @ REPL[72]:1
```

### PR DESCRIPTION
**Pull request by LilithHafner**
- Fix radix_sort! for negative firstindex (Fixes #45568)
- Actually use a workspace vector for `sort!(A::AbstractArray; dims)`
- Preallocate generously right away for `sort[!](A::AbstractArray; dims)`. Eliminating `t = similar(A::AbstractArray; 0); ... resize!(t, len)` is motivated by correctness concerns: `similar` returns an `AbstractVector` and `resize!` is defined for `Vector`s. I'd rather allocate a wee bit more than have this broken edge case. If radix sort is eventually used, this is the perfect size. If merge sort, it is twice as large as required, but half as many allocations, and it doesn't matter much because it is only a single slice of the array. If quicksort pre #45222 or insertion sort is used the allocation could be empty, but I have not observed a substantive performance cost associated with a slightly too large allocation in this case.
- handle workspaces in an unconventional indexing aware manner
- minor comments and style changes

### CODE REVIEW

File: base/sort.jl [hunk 1]
```diff
@@ -683,7 +683,7 @@ function radix_sort!(v::AbstractVector{U}, lo::Integer, hi::Integer, bits::Unsig
                      t::AbstractVector{U}, chunk_size=radix_chunk_size_heuristic(lo, hi, bits)) where U <: Unsigned
     # bits is unsigned for performance reasons.
     mask = UInt(1) << chunk_size - 1
-    counts = Vector{UInt}(undef, mask+2)
+    counts = Vector{Int}(undef, mask+2)
```
Comment (LilithHafner) [inline base/sort.jl:686]: `lo` may be negative and counts is also used to store offsets.

**Comment by LilithHafner** [comment]
To do workspace management right requires access to OffsetArrays. Hold pending that.

**Comment by LilithHafner** [comment]
We can have only one-based indexed workspaces so long as we convert inputs to one-based indexing to match. Thanks, @N5N3 for encouraging me to pursue this approach. Unfortunately, there is a runtime penalty for this conversion, so we only do it where necessary. This results in a somewhat inelegant solution but does work reasonably well and avoids runtime penalties most of the time.

It would still be nice to be able to construct OffsetVectors when handling offset vectors as input, but they are not necessary.

**Comment by LilithHafner** [comment]
All tests passed!!! That's better than master (and totally unrelated to this PR)

File: base/sort.jl [hunk 2]
```diff
@@ -856,8 +856,18 @@ function sort!(v::AbstractVector{T}, lo::Integer, hi::Integer, a::AdaptiveSort,
         u[i] -= u_min
     end
 
-    u2 = radix_sort!(u, lo, hi, bits, reinterpret(U, workspace(v, t, hi)))
-    uint_unmap!(v, u2, lo, hi, o, u_min)
+    if t !== nothing && checkbounds(Bool, t, lo:hi) # Fully preallocated and aligned workspace
+        u2 = radix_sort!(u, lo, hi, bits, reinterpret(U, t))
+        uint_unmap!(v, u2, lo, hi, o, u_min)
+    elseif t !== nothing && (applicable(resize!, t) || length(t) >= hi-lo+1) # Viable workspace
```
Comment (LilithHafner) [inline base/sort.jl:862]: This branch is triggered in the case of `sort(::OffsetMatrix; dims)`

File: test/sorting.jl [hunk 3]
```diff
@@ -842,5 +841,6 @@ end
         end
     end
 end
+# The "searchsorted" testset is at the end of the file because it is slow.
```
Comment (LilithHafner) [inline test/sorting.jl:844]: I added these comments because by default I put new tests at the end of the file and these comments remind me not to. (see #45233, #45234)

**Comment by oscardssmith** [comment]
overall, this looks good to me.

**Comment by LilithHafner** [comment]
Thanks! Any next steps you'd like to see from me?

**Comment by oscardssmith** [comment]
I don't see any necessary changes (but you know this part of the code better than I do)

**Comment by LilithHafner** [comment]
It looks good to me too.

**Comment by DilumAluthge** [comment]
```


Whitespace check found 2 issues:
--
  | base/sort.jl:608 -- trailing whitespace
  | base/sort.jl:1563 -- trailing whitespace
  | make: *** [Makefile:104: check-whitespace] Error 1


```

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/45713

**Comment by LilithHafner** [comment]
Sorry about that! Thanks for fixing it. I didn't check because I've been desensitized to one or two failed CI runs, but I'll make sure to check in the future.

Is Win32 the only top-level check that's allowed to fail now?

**Comment by DilumAluthge** [comment]
Win32 shouldn't be failing.

**Comment by LilithHafner** [comment]
Thanks!

**Comment by LilithHafner** [comment]
Sorry to bother you again, but how do I rerun a failing job that I suspect is unrelated?

**Comment by LilithHafner** [comment]
Nevermind, I figured it out.
