### PR TITLE
Fix overflow in complex //

### LINKED ISSUE #53435: `Int8(8) // Int8(100)im == -50im` due to overflow
The current method for `//` on `Integer` and `Complex{<:Integer}` can overflow, silently giving an incorrect answer. For example:

```julia
julia> Int8(8) // Int8(100)im
0//1 - 50//1*im
```
The expected answer is `0//1 - 2//25*im`

The issue is caused by `abs2` and `conj` on `Complex{Int8}` silently overflowing in:
https://github.com/JuliaLang/julia/blob/ccba6c91e24ebc0940acc2f8c390e6391ce0e292/base/rational.jl#L101

One solution could be to specialize this method on the many different combinations of `Complex{<:Rational}`, `Complex{<:Integer}`, `Rational`, `Integer`, and `Number` for the inputs, and check for overflow when doing any `Integer` math. Maybe there is a nicer way to fix this issue.

### LINKED ISSUE #56245: the `//(::Number, ::Complex)` method is not correct when the second argument is zero or infinite
This is the method:

https://github.com/JuliaLang/julia/blob/877de9839809e769d4f9707a61df3400d087d8d3/base/rational.jl#L101-L101

The math behind the transformation incorrectly assumes `y` is finite and nonzero.

xref #53435, which concerns overflow caused by the same oneliner.

Test:

```julia
using Test

@testset "exact division by an infinite complex number" begin
    for y ∈ (1 // 0, -1 // 0)
        @test (7 // complex(y)) == (7 // y)
    end
end
```

Resulting in:

```none
Test Summary:                                       | Error  Total  Time
exact division by a zero or infinite complex number |     3      3  1.6s
ERROR: Some tests did not pass: 0 passed, 0 failed, 3 errored, 0 broken.
```

### LINKED ISSUE #60137: Should `3.0 // (1 + 0im)` or other `//(::AbstractFloat, ::Complex{Int})` error?
The following behavior seems inconsistent with the note in the docstring for `//` that:

>   Note that floating-point (AbstractFloat) arguments are not permitted by //
  (even if the values are rational). The arguments must be subtypes of
  Integer, Rational, or composites thereof.

```julia-repl
julia> 3.0 // complex(1)
3.0 + 0.0im

julia> 3.0 // 1
ERROR: MethodError: no method matching //(::Float64, ::Int64)
The function `//` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  //(::Complex, ::Real)
   @ Base rational.jl:107
  //(::Integer, ::Integer)
   @ Base rational.jl:91
  //(::AbstractArray, ::Number)
   @ Base rational.jl:111
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

XRef: #56245 #16282 #17206 #55661 #60130

The issue is the method:

```julia
//(x::Number, y::Complex) = x*conj(y)//abs2(y)
```

The order of operations here is `x * (conj(y) // abs2(y))`

Should this generic method be removed or changed to make: `3.0 // complex(1)` error?

Alternatively, should `3.0 // 1` not error?

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #53435

With this change, internal calculations may still throw an `OverflowError` even if the true result would not overflow, but I think this is better than the current behavior of returning the wrong result:

```julia-repl
julia> (Int8(-128) + Int8(-81)im) // (Int8(-42) + Int8(63)im)
ERROR: OverflowError: 63 * 3 overflowed for type Int8
Stacktrace:
 [1] throw_overflowerr_binaryop(op::Symbol, x::Int8, y::Int8)
   @ Base.Checked ./checked.jl:164
 [2] checked_mul
   @ ./checked.jl:298 [inlined]
 [3] //(x::Complex{Int8}, y::Complex{Int8})
   @ Base ./rational.jl:124
 [4] top-level scope
   @ REPL[23]:1

julia> (-128 + -81im) // (-42 + 63im)
1//21 + 2//1*im
```

Simple benchmarks:

```julia
using Chairmarks
@b (rand(1:1000), complex(rand(1:1000), rand(1:1000))) x->//(x...) seconds=1
@b (complex(rand(1:1000), rand(1:1000)), complex(rand(1:1000), rand(1:1000))) x->//(x...) seconds=1
```

master: 16.122 ns, 59.158 ns
PR: 12.720 ns, 15.447 ns

Edit: I added a suggestion from #60137 so now this PR also fixes #60137 and fixes #56245

### CODE REVIEW

File: base/rational.jl [hunk 1]
```diff
@@ -105,8 +105,28 @@ function //(x::Rational, y::Rational)
 end
 
 //(x::Complex, y::Real) = complex(real(x)//y, imag(x)//y)
+
+# TODO Unclear if this method should be defined. It seems to conflict with the docstring that states that "The arguments must be subtypes of Integer, Rational, or composites thereof."
```
Comment (adienes) [inline base/rational.jl]: rather than adding a comment I would either deprecate this in a separate PR or track the TODO in a separate issue

Comment (mikmoore) [reply base/rational.jl]: I can't imagine an alternative definition (that isn't a pun) that someone would want. Which is to say I think this broad method is fine as-is. Anything invalid will hit a MethodError anyway, just inside this method instead of outside:
```julia-repl
julia> (3+4im) // 5.0
ERROR: MethodError: no method matching //(::Int64, ::Float64)
```

Comment (nhz2) [reply base/rational.jl]: I created #60137 for this.

File: base/rational.jl [hunk 2]
```diff
@@ -105,8 +105,35 @@ function //(x::Rational, y::Rational)
...
+        x * conj(y)
+    end//abs2(y)
+end
+function //(x::Number, y::Complex{<:Integer})
+    c, d = reim(y)
+    c_r, d_r = divgcd(c, d)
+    abs2y_r = checked_add(checked_mul(c, c_r), checked_mul(d, d_r))
+    (x * complex(c_r, checked_neg(d_r)))//abs2y_r
+end
+function //(x::Integer, y::Complex{<:Integer})
```
Comment (adienes) [inline base/rational.jl:132]: is there any meaningful performance difference to spelling this method all out vs forwarding?
```
//(x::Integer, y::Complex{<:Integer}) = complex(x) // y
```

**Comment by adienes** [comment]
>  internal calculations may still throw an OverflowError even if the true result would not overflow,

some `@test_broken`s for those would be good too probably

File: base/rational.jl (hunk 2 above)
Comment (nhz2) [reply base/rational.jl:132]: Seems not to make any difference

**Comment by nhz2** [comment]
It would be easy to solve all of these overflows by converting to `BigInt`, but is this worth the performance cost? Overflow errors seem to be an inherent part of doing math with many intermediate steps with `Rational{Int}`.

File: base/rational.jl [hunk 3]
```diff
@@ -105,8 +105,32 @@ function //(x::Rational, y::Rational)
...
 //(x::Complex, y::Real) = complex(real(x)//y, imag(x)//y)
-//(x::Number, y::Complex) = x*conj(y)//abs2(y)
-
+function //(x::Number, y::Complex{<:Rational})
+    c, d = reim(y)
+    if (isinf(c) | isinf(d))
+        x * conj(zero(y))
+    else
+        x * conj(y)
+    end//abs2(y)
```
Comment (adienes) [inline base/rational.jl]:
```suggestion

```

don't intend to be style police but something about this looks so unsettling haha

**Comment by adienes** [comment]
I wouldn't say promoting to `BigInt` is necessary, no.

the fact that something like `3.0 // (1 + 1im)` now `MethodErrors` is in my opinion the correct outcome, but maybe it is worth running PkgEval to check that nobody is accidentally relying on that, and we can give them a polite warning?

**Comment by nhz2** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/60130#issuecomment-3536041088) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8bcaa34_vs_f5f4c01/report.html) is available.

<details><summary>Report summary</summary>

## ❗ Packages that crashed

10 packages crashed on the previous version too.

## ✖ Packages that failed

**17 packages failed only on the current version.**

 - Package fails to precompile: 1 packages
 - Illegal method overwrites during precompilation: 1 packages
 - Package has test failures: 5 packages
 - Package tests unexpectedly errored: 4 packages
 - Tests became inactive: 1 packages
 - Test duration exceeded the time limit: 5 packages

1503 packages failed on the previous version too.

## ✔ Packages that passed tests

**5 packages passed tests only on the current version.**

 - Other: 5 packages

5415 packages passed tests on the previous version too.

## ~ Packages that at least loaded

**1 packages successfully loaded only on the current version.**

 - Other: 1 packages

3281 packages successfully loaded on the previous version too.

## ➖ Packages that were skipped altogether

902 packages were skipped on the previous version too.



</details>

**Comment by adienes** [comment]
looks like main problem is new ambiguities with methods of `//(<:Number, ::Complex)`

File: base/rational.jl (hunk 3 above)
Comment (nhz2) [reply base/rational.jl]: It looks a bit like `#endif // _COMPILER_GCC_` from C :laughing:

**Comment by adienes** [comment]
@nanosoldier `runtests(["Unitful", "CliffordNumbers", "MultiplesOfPi"])`

**Comment by nhz2** [comment]
There is one remaining test failure in [MultiplesOfPi.jl](https://github.com/jishnub/MultiplesOfPi.jl/blob/44d53025b69fa00e304e6d0d6d57deb3fa79336b/test/runtests.jl#L498)
 CC @jishnub 
I think the `Pi^-1` needs to be switched to `Pi^Int(-1)` or `1//Pi` to prevent promoting to `Float64`

```julia
julia> (Pi^-1) |> typeof
PiExpTimes{Float64, Int64}

julia> (Pi^Int(-1)) |> typeof
PiExpTimes{Int64, Int64}
```

```julia
Complex{Int}: Error During Test at /home/nathan/.julia/packages/MultiplesOfPi/QLHYm/test/runtests.jl:498
  Test threw exception
  Expression: Pi ^ -1 // (2im) === (0 // 1 - 1 // 2 * im) * Pi ^ -1
  MethodError: no method matching //(::Float64, ::Int64)
  The function `//` exists, but no method is defined for this combination of argument types.
  Closest candidates are:
    //(::Number, ::Complex)
     @ Base rational.jl:128
    //(::Complex, ::Real)
     @ Base rational.jl:107
    //(::LinearAlgebra.UniformScaling, ::Number)
     @ LinearAlgebra ~/github/julia/usr/share/julia/stdlib/v1.14/LinearAlgebra/src/uniformscaling.jl:290
    ...
  Stacktrace:
    [1] //(p::PiExpTimes{Float64, Int64}, y::Int64)
      @ MultiplesOfPi ~/.julia/packages/MultiplesOfPi/QLHYm/src/MultiplesOfPi.jl:255
    [2] //(x::Complex{PiExpTimes{Float64, Int64}}, y::Int64)
      @ Base ./rational.jl:107
    [3] //(x::PiExpTimes{Float64, Int64}, y::Complex{Int64})
      @ Base ./rational.jl:130
```

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/60130#issuecomment-3539335937) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/aff40d0_vs_f5f4c01/report.html) is available.

<details><summary>Report summary</summary>

## ✖ Packages that failed

**1 packages failed only on the current version.**

 - Package tests unexpectedly errored: 1 packages


## ✔ Packages that passed tests

2 packages passed tests on the previous version too.



</details>

**Comment by adienes** [comment]
lgtm then, I think just that test should be fixed. I'll leave this up for a few days in case anybody else has thoughts (maybe @nsajko , as the author of https://github.com/JuliaLang/julia/issues/56245 ?) and merge closer to the end of the week
