### PR TITLE
Couple ispointer fixes

### LINKED ISSUE #13305: Unnecessary copying of structs passed by reference
```julia
julia> @noinline f(x) = x;

julia> g(x) = f(x);

julia> Base.code_llvm_raw(g, Tuple{Complex64})

define %Complex.12 @julia_g_21408(%Complex.12*) {
top:
  %x = alloca %Complex.12, align 8, !dbg !1, !julia_type !10
  %1 = load %Complex.12* %0, align 4, !dbg !1
  store %Complex.12 %1, %Complex.12* %x, align 8, !dbg !1
  %2 = call %Complex.12 @julia_f_21409(%Complex.12* %x), !dbg !11
  ret %Complex.12 %2, !dbg !11
}
```

It doesn't seem like it should be necessary to copy the input argument to the stack. It could be passed directly to `f`.

### LINKED ISSUE #15274: Accessing an index in a tuple wrapped by an immutable generates worse code than accessing the naked tuple.
I have an immutable type which is wrapping a `NTuple` and noticed that indexing into the wrapped tuple is much slower than indexing into the naked tuple.

Here is some code that that defines an indexing into a tuple and a wrapped tuple:
```jl
function get_idx_tuple(n::NTuple, i::Int)
    @inbounds v = n[i]
    return v
end

immutable TupleWrap{N, T}
    data::NTuple{N, T}
end

function get_idx_tuplewrap(n::TupleWrap, i::Int)
    @inbounds v = n.data[i]
    return v
end

tuple = (rand(15)...)
tuple_wrap = TupleWrap((rand(15)...))
```

Indexing into the tuple:

```jl
julia> @code_native get_idx_tuple(tuple, 5)
    .text
Filename: none
Source line: 0
    pushq   %rbp
    movq    %rsp, %rbp
Source line: 2
    vmovsd  -8(%rdi,%rsi,8), %xmm0  # xmm0 = mem[0],zero
Source line: 3
    popq    %rbp
    retq
```

Indexing into the wrapper

```jl
julia> @code_native get_idx_tuplewrap(tuple_wrap, 5)
    .text
Filename: none
Source line: 0
    pushq   %rbp
    movq    %rsp, %rbp
Source line: 2
    vmovsd  112(%rdi), %xmm8        # xmm8 = mem[0],zero
    vmovsd  104(%rdi), %xmm9        # xmm9 = mem[0],zero
    vmovsd  96(%rdi), %xmm10        # xmm10 = mem[0],zero
    vmovsd  88(%rdi), %xmm11        # xmm11 = mem[0],zero
    vmovsd  80(%rdi), %xmm12        # xmm12 = mem[0],zero
    vmovsd  72(%rdi), %xmm13        # xmm13 = mem[0],zero
    vmovsd  64(%rdi), %xmm14        # xmm14 = mem[0],zero
    vmovsd  56(%rdi), %xmm7         # xmm7 = mem[0],zero
    vmovsd  48(%rdi), %xmm0         # xmm0 = mem[0],zero
    vmovsd  40(%rdi), %xmm1         # xmm1 = mem[0],zero
    vmovsd  32(%rdi), %xmm2         # xmm2 = mem[0],zero
    vmovsd  24(%rdi), %xmm3         # xmm3 = mem[0],zero
    vmovsd  16(%rdi), %xmm4         # xmm4 = mem[0],zero
    vmovsd  (%rdi), %xmm5           # xmm5 = mem[0],zero
    vmovsd  8(%rdi), %xmm6          # xmm6 = mem[0],zero
    vmovsd  %xmm5, -120(%rbp)
    vmovsd  %xmm6, -112(%rbp)
    vmovsd  %xmm4, -104(%rbp)
    vmovsd  %xmm3, -96(%rbp)
    vmovsd  %xmm2, -88(%rbp)
    vmovsd  %xmm1, -80(%rbp)
    vmovsd  %xmm0, -72(%rbp)
    vmovsd  %xmm7, -64(%rbp)
    vmovsd  %xmm14, -56(%rbp)
    vmovsd  %xmm13, -48(%rbp)
    vmovsd  %xmm12, -40(%rbp)
    vmovsd  %xmm11, -32(%rbp)
    vmovsd  %xmm10, -24(%rbp)
    vmovsd  %xmm9, -16(%rbp)
    vmovsd  %xmm8, -8(%rbp)
    vmovsd  -128(%rbp,%rsi,8), %xmm0 # xmm0 = mem[0],zero
Source line: 3
    popq    %rbp
    retq
```

I am not good at assembler but it looks like the wrapped indexing is accessing all the elements of the tuple instead of just directly returning from the offset into the data. For longer tuples this starts to generate extremely long code when (in my layman guess) the registers run out.

### LINKED ISSUE #15277: Performance regression in tuples getting copied to functions that only read from them.
There is a performance regression in what I ~~believe is tuple indexing~~ ~~(now I believe it is function call overhead)~~ now I believe it is tuples sometimes getting copied into functions that previously got passed by reference, from the giant codegen rewrite PR.

Test script (note the `@noinline`):

```jl
@noinline function get_idx_tuple(n::NTuple, i::Int)
    @inbounds v = n[i]
    return v
end


function bench{N, T}(tuple::NTuple{N, T})
    s = 0.0
    t_tup = @elapsed for n in 1:10^5
        for i in 1:N
            s += get_idx_tuple(tuple, i)
        end
    end
    return t_tup
end


tuple = (rand(75)...)

bench(tuple)
```

This typically looks like this for different sizes of the tuple:

tuple

Full bisect log: https://gist.github.com/KristofferC/1ba13fe374897e4f7f98

Relevant:
```
# possible first bad commit: [5c5d48369a1a8f9a5959699ec44cab393255d0c5] [wip codegen rewrite] fix another type information mismatch error in assignment
# possible first bad commit: [548075efe73083f6a58b97814ea558bdbc0db41d] [wip codegen rewrite] fix mixed-type intrinsic usage (such as `bswap(Float64)`)
# possible first bad commit: [322878d93879f81cdf3d6a783376ad149b10d65b] [wip codegen rewrite] fix select_value validation and missing value copy in variable assignment
# possible first bad commit: [e4dcff39221571b8fc59d25873de092edaf46768] [wip codegen rewrite] fix isVolatile marking and closure memloc allocation marking
# possible first bad commit: [8b98aa0fe4056915b69176c0eca23391a77f2f58] [wip codegen rewrite] fix marking of varinfo.value when type_is_ghost and recursive constant struct creation
# possible first bad commit: [ffc200620862e04d6e4d5b9363ea03130276deca] [wip codegen rewrite] cleanup closure env handling to occur early
# possible first bad commit: [ae1a623634aed1912b8fb12a624529f3108fe418] [wip codegen rewrite] use correct macro test for jl_is_immutable
# possible first bad commit: [fec6aa9048d2e54f3c178b379db96074f1d867be] [wip] codegen rewrite + rewrite intrinsics to accomodate
```

cc @vtjnash

### PR DESCRIPTION
**Pull request by carnaval**
- Do not copy a getfield argument if it is already a pointer.
- Mark struct-as-pointer arguments immutable

Should: fix #15274, fix #13305, fix #15277 

@KristofferC @simonster can you please check that it is all better ?

Also thanks to @vtjnash for the much nicer codegen.cpp now

### CODE REVIEW

**Comment by KristofferC** [comment]
#15274 looks fixed, #15277 looks fixed.

#13305 no longer has the `alloc, load, store` triplet.

Really nice, thanks for fixing this so quick.

**Comment by JeffBezanson** [comment]
:100:

**Comment by KristofferC** [comment]
The FixedSizeArrays code example from #15274 is also fixed.

**Comment by tkelman** [comment]
Nice. Is this testable in any more direct way than doing regular perf tracking?

**Comment by carnaval** [comment]
I'm not sure there is a reasonable way since we don't have first class llvm IR in the language and trying to parse it (or look at the size of the text ...) feels quite brittle

**Comment by KristofferC** [comment]
I added a benchmark for this in https://github.com/JuliaCI/BaseBenchmarks.jl/pull/7. If I did it correctly this PR should show a good performance gain for this.

Should be something like `runbenchmarks("tuple", vs = "JuliaLang/julia:master")`. Since there are only my benchmark with the `tuple` tag it should go fast.

**Comment by KristofferC** [comment]
If someone could run that for me :)

**Comment by mbauman** [comment]
`runbenchmarks("tuple", vs = "JuliaLang/julia:master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/15312#issuecomment-190934162) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/master/5e15cc3/5e15cc3_vs_0b6cab6.md). cc @jrevels

**Comment by jrevels** [comment]
> I added a benchmark for this in JuliaCI/BaseBenchmarks.jl#7. If I did it correctly this PR should show a good performance gain for this.

Sorry, changes to that repo don't automatically deploy to @nanosoldier - I normally tag a version and do it manually, so that I can do a full test sweep of the CI cycle first. I didn't have time to do it yesterday, but I can deploy the change tomorrow.

**Comment by KristofferC** [comment]
Okay, no worries.

File: src/cgutils.cpp [hunk 1]
```diff
@@ -1567,6 +1567,15 @@ static bool emit_getfield_unknownidx(jl_cgval_t *ret, const jl_cgval_t &strct, V
             jl_value_t *jt = jl_field_type(stt, 0);
             idx = emit_bounds_check(strct, (jl_value_t*)stt, idx, ConstantInt::get(T_size, nfields), ctx);
             Value *ptr = data_pointer(strct, ctx);
+            if (!stt->mutabl) {
+                // just compute the pointer and let user load it when necessary
+                Type *fty = julia_type_to_llvm(jt);
+                Value *addr = builder.CreateGEP(builder.CreatePointerCast(ptr, PointerType::get(fty,0)), idx);
+                jl_cgval_t fieldval = mark_julia_slot(addr, jt);
```
Comment (vtjnash) [inline src/cgutils.cpp]: `fieldval.isimmutable = true`?
