### PR TITLE
Fix bug in `pinv`

### LINKED ISSUE #911: pinv bug: matrix misdiagnosed as diagonal
The code
```
A = [1.0 0.0;0.0 1.0;0.0 0.0]
A1 = pinv(A):
```
produces
```
[1.0 0.0 1.0;0.0 0.0 0.0]
```
An incorrect answer, which is due to the identification of `A` as diagonal on line
https://github.com/JuliaLang/julia/blob/bf534986350a991e4a1b29126de0342ffd76205e/stdlib/LinearAlgebra/src/dense.jl#L1433

I think the solution could be to check that the matrix is square and `isdiag` returns true.

Or, perhaps `isdiag` does not work correctly, and the solution is to fix that function to identify matrix as diagonal only if it is square? 

The `svd` code below the if block would have worked correctly.
https://discourse.julialang.org/t/bug-in-linearalgebra-pinv/76663/2

### LINKED ISSUE #44234: pinv bug: matrix misdiagnosed as diagonal
The code
```
A = [1.0 0.0;0.0 1.0;0.0 0.0]
A1 = pinv(A):
```
produces
```
[1.0 0.0 1.0;0.0 0.0 0.0]
```
An incorrect answer, which is due to the identification of `A` as diagonal on line
https://github.com/JuliaLang/julia/blob/bf534986350a991e4a1b29126de0342ffd76205e/stdlib/LinearAlgebra/src/dense.jl#L1433

I think the solution could be to check that the matrix is square and `isdiag` returns true.

Or, perhaps `isdiag` does not work correctly, and the solution is to fix that function to identify matrix as diagonal only if it is square? 

The `svd` code below the if block would have worked correctly.
https://discourse.julialang.org/t/bug-in-linearalgebra-pinv/76663/2

### PR DESCRIPTION
**Pull request by hyrodium**
This PR fixes JuliaLang/LinearAlgebra.jl#911.

### CODE REVIEW

File: stdlib/LinearAlgebra/test/pinv.jl [hunk 1]
```diff
@@ -63,69 +63,54 @@ function tridiag(T::Type, m::Integer, n::Integer)
...
     @test norm(a*apinv*a-a)/norm(a) ≈ 0 atol=tol1
-    x0 = randn(n); b = a*x0; x = apinv*b
-    @test norm(a*x-b)/norm(b) ≈ 0 atol=tol1
-    apinv = pinv(a,sqrt(eps(real(one(eltype(a))))))
+    @test norm(apinv*a*apinv-apinv)/norm(apinv) ≈ 0 atol=tol1
+    for _ in 1:100
+        b = a*randn(n)
+        x = apinv*b
+        @test norm(a*x-b)/norm(b) ≈ 0 atol=tol1
+    end
```
Comment (thchr) [inline stdlib/LinearAlgebra/test/pinv.jl:77]: Why the loop here? Is this intended or something left over from editing? Same below in lines 83-87.

Comment (hyrodium) [reply stdlib/LinearAlgebra/test/pinv.jl:77]: Since `randn(n)` is included, I thought it would be better to verify multiple times rather than just one test.

Comment (ViralBShah) [reply stdlib/LinearAlgebra/test/pinv.jl:77]: I think just one test should suffice. If we do this everywhere, the tests will take way too long.

Comment (hyrodium) [reply stdlib/LinearAlgebra/test/pinv.jl]: Okay, I have removed `for _ in 1:100`.

**Comment by hyrodium** [comment]
I hope this PR will be backported to 1.6 and 1.7.

**Comment by ViralBShah** [comment]
Added the backport labels. Not sure if another 1.7 release will happen before 1.8 comes out.

**Review by stevengj — APPROVED** [review]
