### PR TITLE
alignment: subtly change meaning of datatype_align

### LINKED ISSUE #32414: Wrong GEP emission for tuple containing VecElement
```julia
julia> @noinline function foo(a)
           v = ntuple(Val(8)) do w Core.VecElement(Float64(10w)) end
           a, (v, (a,(1e6,1e9)))
       end
foo (generic function with 1 method)

julia> foo(-35.0)
(10.0, ((VecElement{Float64}(30.0), VecElement{Float64}(40.0), VecElement{Float64}(50.0), VecElement{Float64}(60.0), VecElement{Float64}(70.0), VecElement{Float64}(80.0), VecElement{Float64}(-35.0), VecElement{Float64}(1.0e6)), (1.0e9, (1.2353556789225747e-307, 6.9513596813479e-310))))

julia> versioninfo()
Julia Version 1.3.0-DEV.428
Commit 863e03fbb1* (2019-06-19 15:07 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.0 (ORCJIT, skylake)
```
The answer should be:
```julia
(-35.0, ((VecElement{Float64}(10.0), VecElement{Float64}(20.0), VecElement{Float64}(30.0), VecElement{Float64}(40.0), VecElement{Float64}(50.0), VecElement{Float64}(60.0), VecElement{Float64}(70.0), VecElement{Float64}(80.0), VecElement{Float64}(-35.0), VecElement{Float64}(1.0e6)), (-35.0, (1.0e6, 1.0e9))))
```
That is, the incorrect answer we received is shifted to the left by 16 bytes, and there appears to be an 8-byte gap between the first float and the following vector.

If we replace the tuple of `VecElement`s with a standard tuple, that is what we get:
```julia
julia> @noinline function bar(a)
           v = ntuple(Val(8)) do w Float64(10w) end
           a, (v, (a,(1e6,1e9)))
       end
bar (generic function with 1 method)

julia> bar(-35.0)
(-35.0, ((10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0), (-35.0, (1.0e6, 1.0e9))))
```

This silently corrupts data -- not the easiest problem to track down!

I referenced the issue [here](https://github.com/JuliaLang/julia/issues/30426#issuecomment-505603418), where vtjnash said:
> Seems like a new issue: it looks like we're specifying the wrong sort of vector to LLVM for our desired alignment for Julia.

### PR DESCRIPTION
**Pull request by vtjnash**
Rather than meaning the actual alignment of the object, this now means
the preferred alignment of the object. The actual alignment of any
object is the minimum of this preferred alignment and the alignment
supported by the runtime allocator. This aligns us with how LLVM treats
alignment, and is probably reasonably sensible anyways.

Also tries to audit our existing uses of CreateLoad/CreateStore for
correctness, and upgrade some to include pointer-types.

fixes #32414

### CODE REVIEW

**Review by vchuravy — COMMENTED** [review]
Looks good to me.

**Comment by JeffBezanson** [comment]
Let's rebase this and try to get a better CI run.

File: test/vecelement.jl [hunk 1]
```diff
@@ -73,6 +73,13 @@ end
 
 @test isa(VecElement((1,2)), VecElement{Tuple{Int,Int}})
 
+# test for alignment agreement (#32414)
+@noinline function bar32414(a)
+    v = ntuple(w -> Float64(10w), Val(8))
+    return a, (v, (a, (1e6, 1e9)))
+end
+@test bar32414(-35.0) === (-35.0, ((10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0), (-35.0, (1.0e6, 1.0e9))))
```
Comment (JeffBezanson) [inline test/vecelement.jl]: Unlike the example in #32414 this test passes for me on master. Should we add a version that includes `VecElement`?

Comment (vtjnash) [reply test/vecelement.jl]: oh, I just pasted the wrong one here

**Comment by KristofferC** [comment]
Doesn't backport cleanly. Can push a backport to https://github.com/JuliaLang/julia/pull/34517.

**Comment by KristofferC** [comment]
Bump for backport.
