### PR TITLE
fix #22624, crash in certain circular type definitions

### LINKED ISSUE #22624: crash on this circular type definition
The following segfaults on 0.6:

```
julia> struct T{A,B,C}; v::Vector{T{Int,A}}; end

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
inst_type_w_ at /home/jeff/src/julia/src/jltypes.c:1338
inst_all at /home/jeff/src/julia/src/jltypes.c:1272
inst_datatype at /home/jeff/src/julia/src/jltypes.c:1204
inst_type_w_ at /home/jeff/src/julia/src/jltypes.c:1429
```

I'm working on it and will hopefully have a fix pretty soon.

### PR DESCRIPTION
**Pull request by JeffBezanson**
This was caused by expanding a type's field types in the wrong environment.

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -177,6 +177,16 @@ struct C21923{T,N}; v::C21923{T,M} where M; end
 struct D21923{T,N}; v::D21923{T}; end
 @test fieldtype(D21923, 1) == D21923
 
+# issue #22624, more circular definitions
+struct T22624{A,B,C}; v::Vector{T22624{Int,A}}; end
+let elT = T22624.body.body.body.types[1].parameters[1]
+    @test elT == T22624{Int64, T22624.var, C} where C
```
Comment (tkelman) [inline test/core.jl]: Int vs Int64 nickel?
