### PR TITLE
read(io, Char): fix read with too many leading ones

### LINKED ISSUE #50532: read(io, Char) doesn't match collect(string) for malformed UTF-8
The following mismatch seems undesirable to me: the same data `"\xfc\xa8"` is treated as 2 (malformed) characters for `collect` but as only 1 character for `read`:
```jl
julia> s = "\xfc\xa8"
"\xfc\xa8"

julia> io = IOBuffer(s);

julia> read(io, Char)
'\xfc\xa8': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> collect(s)
2-element Vector{Char}:
 '\xfc': Malformed UTF-8 (category Ma: Malformed, bad data)
 '\xa8': Malformed UTF-8 (category Ma: Malformed, bad data)
```
cc @StefanKarpinski, the guru of malformed `Char`, who wrote this `read` code and the string iteration in #24999 — is this intentional?

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Fixes #50532. The `read(io, Char)` method didn't correctly handle the case where the lead byte starts with too many leading ones; this fix makes it handle that case correctly, which makes `read(io, Char)` match `collect(s)` in its interpretation of what a character is in all invalid cases.

### CODE REVIEW

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
Thanks!  Now passes my tests from JuliaIO/BufferedStreams.jl#77 where I first noticed this issue.

File: base/io.jl [hunk 1]
```diff
@@ -884,9 +884,9 @@ end
 
 function read(io::IO, ::Type{Char})
     b0 = read(io, UInt8)::UInt8
-    l = 8(4-leading_ones(b0))
+    l = 0x08 * (0x04 - UInt8(leading_ones(b0)))
```
Comment (stevengj) [inline base/io.jl:887]:
```suggestion
    l = 0x08 * (0x04 -(leading_ones(b0) % UInt8))
```
though maybe LLVM is smart enough to elide the overflow check?

File: base/io.jl [hunk 2]
```diff
@@ -884,9 +884,9 @@ end
...
     c = UInt32(b0) << 24
-    if l < 24
+    if l ≤ 0x10
```
Comment (stevengj) [inline base/io.jl:889]:
```suggestion
    if l < 0x18
```
if we want to make it the same as before.  (LLVM seems to generate essentially the same code, though?)

**Comment by StefanKarpinski** [comment]
I was kind of hoping the optimizer would figure that out for me, but might as well do it explicitly. This might be what I had intended the code to do originally but got foiled by promotion with Int.

**Comment by stevengj** [comment]
Maybe backport to 1.10 at least?

File: base/io.jl (hunk 2 above)
Comment (StefanKarpinski) [reply base/io.jl:889]: Eh, 🤷🏻‍♂️

File: base/io.jl (hunk 1 above)
Comment (StefanKarpinski) [reply base/io.jl:887]:
```jl
julia> leading_ones_u8(b::UInt8) = UInt8(leading_ones(b))
leading_ones_u8 (generic function with 1 method)

julia> @code_native debuginfo=:none leading_ones_u8(0xff)
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 13, 0
	.globl	_julia_leading_ones_u8_198      ## -- Begin function julia_leading_ones_u8_198
	.p2align	4, 0x90
_julia_leading_ones_u8_198:             ## @julia_leading_ones_u8_198
	.cfi_startproc
## %bb.0:                               ## %top
	cmpb	$-1, %dil
	je	LBB0_1
## %bb.2:                               ## %cond.false
	notb	%dil
	movzbl	%dil, %eax
	bsrl	%eax, %eax
	xorl	$7, %eax
                                        ## kill: def $al killed $al killed $eax
	retq
LBB0_1:
	movb	$8, %al
                                        ## kill: def $al killed $al killed $eax
	retq
	.cfi_endproc
                                        ## -- End function
.subsections_via_symbols
```
Not as concise as I would have imagined, but no error branch and identical to using `% UInt8`.
