### PR TITLE
Fix some overly optimistic fastpaths in subtyping

### LINKED ISSUE #25430: Unreachable reached at 0000000015349AF1
I was running the following code, when Julia crashed and I got the following error:
```julia
julia> struct FunctorArgTrait{T<:Tuple} end

julia> struct FunctorRetTrait{S} end

julia> f(x, y) =  x+y
f (generic function with 1 method)

julia> get_ret_trait(::Type{typeof(f)}, input_types::Type{<:Tuple}) = FunctorRetTrait{promote_type(input_types.parameters...)}()
get_ret_trait (generic function with 1 method)

julia> get_arg_trait(::Type{typeof(f)}) = FunctorArgTrait{Tuple{Any,Any}}()
get_arg_trait (generic function with 1 method)

julia> g(f::F, x, y) where {F<:Function, T1, T2} = g(f, x, y, get_arg_trait(F), get_ret_trait(F, Tuple{Int,Int}))
g (generic function with 1 method)

julia> g(f::F, x, y, ::FunctorArgTrait{Tuple{>:Int, >:Int}}, ::FunctorRetTrait{S}) where {F<:Function, S<:Int} = f(x,y)::S
g (generic function with 2 methods)

julia> g(f, 1, 2)

Unreachable reached at 0000000015349AF1

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x15349af1 -- g at .\REPL[8]:1
in expression starting at no file:0
g at .\REPL[8]:1
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:384 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:399 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2082
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:395
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:509
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:720
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000001161720F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:798
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:626
eval at .\boot.jl:298 [inlined]
eval at .\repl\REPL.jl:3
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:380 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:399 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2082
eval_user_input at .\repl\REPL.jl:70
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:380 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:399 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2082
macro expansion at .\repl\REPL.jl:101 [inlined]
#1 at .\event.jl:92
jl_call_fptr_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:380 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src\julia_internal.h:399 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2082
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1473 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 2506350 (Pool: 2505097; Big: 1253); GC: 5
```

### PR DESCRIPTION
**Pull request by martinholters**
Fixes #25430, see discussion therein.

WIP because it leads to this regression (hence the disabled core test):
```julia
julia> struct T22624{A,B,C}; v::Vector{T22624{Int64,A}}; end
ERROR: StackOverflowError:
```
Hints welcome about where I should look to fix this!

### CODE REVIEW

**Comment by martinholters** [comment]
Ok, the recursive type definition requires `obviously_unequal(Int64, A)` to be true to not result in a stack overflow, so I've added another fast path to `obviously_unequal` for the (concrete type, typevar) case.  However, from the function name, I would expect `Int64` and `A` _not_ to be obviously unequal without knowing the environment; after all, `A` could be bound to `Int64`. But I guess that's just the problematic semantics of lone type variables...

Anyway, this now passes tests (locally, hoping CI agrees), and fixes a bug, so getting a review would be appreciated.

File: src/jltypes.c [hunk 1]
```diff
@@ -810,6 +815,27 @@ jl_value_t *jl_cache_type_(jl_datatype_t *type)
...
+        if (!(is_cacheable(dt2) || jl_svec_len(dt2->parameters) == 0))
+            return 0;
+        else
+            return 1;
+    }
+    if (!(is_cacheable(dt2) || jl_svec_len(dt2->parameters) == 0))
+        return 1;
+
+    return is_typekey_ordered(jl_svec_data(dt1->parameters), jl_svec_len(dt1->parameters)) ==
+        is_typekey_ordered(jl_svec_data(dt2->parameters), jl_svec_len(dt2->parameters));
```
Comment (JeffBezanson) [inline src/jltypes.c]: This predicate seems pretty expensive. If we're going to use this, we should probably cache this property like we do for has-free-typevars.

**Comment by JeffBezanson** [comment]
> Ok, the recursive type definition requires obviously_unequal(Int64, A) to be true to not result in a stack overflow

Where was this call coming from? Was it the call to `jl_types_equal` in `inst_datatype_inner`?

File: src/jltypes.c [hunk 2]
```diff
@@ -583,6 +583,11 @@ static int is_typekey_ordered(jl_value_t **key, size_t n)
             !(jl_is_datatype(k) && (((jl_datatype_t*)k)->uid ||
                                     (!jl_has_free_typevars(k) && !contains_unions(k)))))
             return 0;
+        if (jl_is_datatype(k)) {
```
[the remark this answers is not in the document]
Comment (martinholters) [reply src/jltypes.c]: Ah, right, recursing down the structure once should be enough. Will push a simplified version once checks pass locally.

File: src/jltypes.c (hunk 1 above)
Comment (martinholters) [reply src/jltypes.c]: Sure. Performance-wise, I'm more worried about taking the fast-paths in subtype.c much less often, though. BTW, does nanosoldier have any benchmarks that exercise the type system?

> If we're going to use this

Before I set into motion working on the caching: What are the chances of that becoming true? (And what are the alternatives?)

**Comment by martinholters** [comment]
> Where was this call coming from?

I admit I got nowhere when I tried to walk through the code in the debugger and figure why it was ending in a stack overflow. So I added debug output showing all type pairs where the result of `obviously_unequal` had changed. The (`Int64`, `A`) looked promising and, yes, fixed it.

So looking at the stack traces of all calls to `obviously_unequal(Int64, A)` (occurring 8 times), I can verify your suspicion, they all look like:

`inst_datatype_inner` -> `jl_types_equal` -> `obviously_unequal` -> `obviously_unequal(Int64, A)`

BTW, there are also calls to `obviously_unequal(A, Int64)`, but they may safely return false without breaking anything.

**Comment by martinholters** [comment]
Bump. Should I work on caching the result of `is_typekey_ordered`? Or do we need to work out what to do with `obviously_unequal(Int64, A)`? Or...?

**Comment by martinholters** [comment]
Bumpity.

**Comment by martinholters** [comment]
Looking at #31696, it still fails in this branch, but only because `jl_obviously_unequal(Int8, T)` returns `true`. If I revert b5cb181, this actually fixes #31696 :tada:, but of course, breaks #22624 again (ref. https://github.com/JuliaLang/julia/pull/25796#issuecomment-380775853). So I think a type should not be "obviously unequal" to a typevar and we need to find some other fix to make #22624 work again, but I have no clue about that (and little time to look into it at the moment).

**Comment by martinholters** [comment]
I've removed
https://github.com/JuliaLang/julia/blob/9d9257d4c05552a7f83eeda5a6b47f1280228701/src/subtype.c#L223-L225
and spent some time in the debugger to figure out why that makes
```julia
struct T22624{A,B,C}; v::Vector{T22624{Int64,A}}; end
```
overflow the stack. The call to `jl_types_equal` in
https://github.com/JuliaLang/julia/blob/9d9257d4c05552a7f83eeda5a6b47f1280228701/src/jltypes.c#L1103-L1104
is invoked for `pi == Main.T22624{Int64, Int64, C} where C`, `tw == Main.T22624{A, B, C} where C where B where A`. That subtype test invokes `rename_unionall`, which wants to construct another `T22624`, resulting in the infinite recursion. I think guarding the call to `jl_types_equal` with a suitable predicate allows to keep #22624 fixed and at the same time fix #31696. I'll poke at it a bit more...

**Comment by martinholters** [comment]
Yep, this can be fixed by adding a suitable guard, see last commit. However, I have no idea how to justify this. My guess is it's just a more or less accidental fix. Hence, the name `guard_against_22624` because that's what is. I would have thought the `stack` plays a role here, too, but couldn't put it to use fruitfully. @JeffBezanson can you take a look at this?

**Comment by JeffBezanson** [comment]
Nice, thanks for figuring that out. I'll take a look.

File: src/jltypes.c [hunk 3]
```diff
@@ -797,6 +788,26 @@ jl_value_t *jl_cache_type_(jl_datatype_t *type)
...
 
+int jl_type_equality_is_identity(jl_value_t *t1, jl_value_t *t2)
+{
+    if (t1 == t2)
+        return 1;
+    if (!jl_is_datatype(t1) || !jl_is_datatype(t2))
+        return 0;
+    jl_datatype_t *dt1 = (jl_datatype_t *) t1;
+    jl_datatype_t *dt2 = (jl_datatype_t *) t2;
+    if (!(is_cacheable(dt1) || jl_svec_len(dt1->parameters) == 0)) {
```
Comment (vtjnash) [inline src/jltypes.c]: could be nice to have some comments here about what the reasoning here is, what the parameters are, etc.

**Comment by JeffBezanson** [comment]
This is trying to normalize types that might equal `dt.name.wrapper` for some `dt::DataType`. So in effect `guard_against_22624` is another variant of `types_obviously_unequal`. So we could call it `type_obviously_not_wrapper` and make sure it implements that rigorously.

File: src/jltypes.c [hunk 4]
```diff
@@ -566,10 +554,13 @@ static int is_typekey_ordered(jl_value_t **key, size_t n)
...
         if (jl_is_typevar(k))
             return 0;
-        if (jl_is_type(k) && k != jl_bottom_type && !wrapper_id(k) &&
-            !(jl_is_datatype(k) && (((jl_datatype_t*)k)->uid ||
-                                    (!jl_has_free_typevars(k) && !contains_unions(k)))))
-            return 0;
+        if (jl_is_datatype(k)) {
+            if (!((jl_datatype_t *) k)->typekeyordered)
+                return 0;
+        } else {
```
Comment (JeffBezanson) [inline src/jltypes.c]:
```suggestion
        }
        else {
```

**Comment by martinholters** [comment]
I guess calling `jl_types_equal` here is generally risky, so ideally, we should fuse the `!type_obviously_not_wrapper` and `jl_types_equal` into an `type_is_wrapper` which does not lead to calls to `rename_unionall`. I don't know whether that is feasible. So what do we loose if we instead make this a `type_obviously_wrapper`, i.e. maybe miss opportunities to normalize to the wrapper? What's the utility of normalizing to wrappers here? As an experiment, I've disabled the whole loop trying to normalize the parameters and nothing bad seems to be happening...

**Comment by martinholters** [comment]
See #31828 for a possible remedy concerning the normalization to wrapper/infinite recursion issue.

**Comment by vtjnash** [comment]
> I guess calling jl_types_equal here is generally risky,

FWIW, the lines of code immediately subsequent (`lookup_type` and `lookup_type_stack`) are also a call to `jl_types_equal`*, this particular stacktrace is the result of hoisting this particular common case out of the inner loop (thereby allowing us to replace the linear scan with a faster and simpler binary search).

* for instance, at https://github.com/JuliaLang/julia/blob/5919a38d07df7fe2b5d38993a17f0bfca17d1c39/src/jltypes.c#L651

**Comment by martinholters** [comment]
Right. But it's the comparison to the potential wrapper that is most likely to require a `rename_unionall`.

**Comment by vtjnash** [comment]
This test is simply extracted from that loop, it would be doing the comparison against the wrapper more frequently if we didn't do it already here.

**Comment by martinholters** [comment]
Huh? Then why does #31838 work? Are we talking past each other?

**Comment by martinholters** [comment]
Ah, if `pi` is a `UnionAll`, it will only be compared to the entries in the linear scan cache, but the entry with the wrapper is in the ordered cache. Hence the issue is worked around.

But one can probably still construct cases that fail. Any idea how to get out of this dilemma? Or is failing in fewer cases the best we can do here?

**Comment by vtjnash** [comment]
From discussions in #31877, I think I found what a proper solution may be. The code path is reached when we are trying to make a copy of a bound object, but that should be a simple copy, since those cannot (by definition) be present in a cache. I think that's pretty much just needing a change to `inst_datatype_inner` here: https://github.com/JuliaLang/julia/commit/397d22f023bc0a0f4089d146dfab37a2b1817ff3#diff-471be6c4456a1e81a1af5962a4fcee0eR1508 (although I think we need a couple other changes to make sure `bound` is computed fully).

**Comment by martinholters** [comment]
I've started dusting this off, but I'm not 100% sure I completely understand the caching logic which has changed a bit since I did this stuff a year ago. That is, the code has changed quite a bit, but I believe the basic concept is still same (which I'd like to be confirmed by someone knowledgeable—@vtjnash?): There is a cache where a hash of the type structure is used for lookup and a linear cache which uses linear search. In both caches individually, entries should be unique based on type equality. (But there may be two type-equal types spread among the two caches.) The hash-based cache is only used for types where type-equality is equivalent to structural equality (hence equal hashes), which are "suffiiciently simple" types for some suitable definition of "suffiiciently simple".

However, I'm seeing this:
```julia
julia> T1 = Vector{Vector{<:Int}}
Array{Array{var"#s1",1} where var"#s1"<:Int64,1}

julia> T2 = Vector{Vector{Vector{<:Int}}}
Array{Array{Array{var"#s1",1} where var"#s1"<:Int64,1},1}

julia> Array_name = Base.unwrap_unionall(Array).name
Array

julia> T1 in Array_name.linearcache
true

julia> T2 in [Array_name.cache[i] for i in eachindex(Array_name.cache) if isassigned(Array_name.cache, i)]
true
```

Now, I would have believed that not only `T1` but also  `T2` should be in the linear cache. Bug on Julia's side or misunderstanding on my side?

I've also observed the following, which I consider misbehavior:
```julia
julia> T1 = Vector{Vector{Tuple{>:Int}}}
Array{Array{Tuple{var"#s1"} where var"#s1">:Int64,1},1}

julia> T2 = Vector{Vector{Tuple{Any}}}
Array{Array{Tuple{Any},1},1}

julia> T1 === T2
false

julia> T1 === Array_name.cache[94]
true

julia> T2 === Array_name.cache[95]
true
```
Yet `T1` and `T2` are type-equal:
```julia
julia> T1 <: T2
true

julia> T2 <: T1
true
```
(`T1 === T2 == false`—but that's a bug of the kind I've tried to address in this PR.)

I think the same issue was present also a year ago and I tried to address it with 1326fe50839691caf26dc4e75dfb7dfe5989603b. If so, I guess I should try to work out how to port the fix to the new `typekey_hash` function. Comments appreciated @vtjnash or possibly @JeffBezanson.

**Comment by vtjnash** [comment]
That subtyping/cache issue is https://github.com/JuliaLang/julia/issues/35130 and results from this identity:
```
julia> Tuple{Any} == Tuple{T} where {T>:Union{}}
true
```

**Comment by martinholters** [comment]
Alright, rebased and updated. I haven't addressed the issue noted in https://github.com/JuliaLang/julia/pull/25796#issuecomment-634164315 which I think is related but has a different root cause. If at all, I'd prefer to tackle it separately to keep this PR from stalling again. The good news is that the changes that happened in the meantime simplified this PR and breaking #22624 was not an issue anymore.

**Comment by martinholters** [comment]
Any ideas anyone about the failed `precompile` test on win32? I wouldn't expect that to be flaky, but I also don't see how this PR could affect only a single platform. And the output is not too helpful.

**Comment by martinholters** [comment]
Ok, rebasing made the CI error go away. And yay, all green!

**Comment by martinholters** [comment]
Fixed another fastpath found in `typekey_eq`, now the case from https://github.com/JuliaLang/julia/pull/25796#issuecomment-634164315 passes, too.

Note that this PR does not improve the normalization, but aims at avoiding bugs due to incomplete normalization. E.g. the types from #35130 are still not normalized any better, but they now compare equal as they should. While better normalization would certainly be good, I doubt it can ever be perfect, except for an uncoditional linear cache search which is probably too expensive. So I think we should apply the fixes from this PR _and_ try to improve normalization.

RA new round of review from @vtjnash / @JeffBezanson would be appreciated.

**Comment by martinholters** [comment]
Bump. As this fixes a bug and resolves an [existential crisis](https://github.com/JuliaLang/julia/issues/31696), it would be nice to make some progress here. The main point I'm unsure about is the caching of `cashed_by_hash`. Is it worth it and if so, does the current implementation make sense? But another round of general review would also be appreciated.

**Comment by StefanKarpinski** [comment]
Since this passes tests and has gotten no responses despite multiple pings over a long period, I will merge this if there's no replies in the next day or so.

**Comment by vtjnash** [comment]
This seems slightly expensive, and still will be wrong in many other places in the system, so I'm inclined to try to go the normalization route to get the majority of cases, and see what it breaks with these rules:
 - For instantiation of Tuple, replace any TypeVar parameter with a concrete upper bound with the upper bound itself (ignores lower bound).
 - For instantiation of any other object, replace any TypeVar with `ub === lb` with just upper bound itself.

**Comment by martinholters** [comment]
Ref. #36211 for an experiment going the normalization route (where I'd also appreciate feedback). In general, I think to thoroughly fix the situation, an approach like in this PR will be needed. Even if there are more places around which need fixing to call `jl_type_equality_is_identity`, that's a finite number, so eventually, we should be able to fix them all. OTOH, I'm skeptical whether normalization can ever be perfect. Of course, we might decide that it's acceptable to be wrong in some corner cases if the price for fixing them is too high:

> This seems slightly expensive

Expensive in terms of what? Do you have an idea for a benchmark to evaluate the cost of this approach?

**Comment by martinholters** [comment]
> Do you have an idea for a benchmark to evaluate the cost of this approach?

As it seems to be quite fashionable at the moment, I measured the TTFP:
```julia
julia> @time using Plots
 15.696126 seconds (22.13 M allocations: 1.186 GiB, 3.09% gc time) # before
 10.652585 seconds (10.04 M allocations: 630.085 MiB, 2.28% gc time) # after

julia> @time plot(rand(10))
  3.294725 seconds (3.64 M allocations: 188.339 MiB, 2.04% gc time) # before
  3.257043 seconds (3.64 M allocations: 188.792 MiB, 1.37% gc time) # after
```
Before is 8c65f8d987669678d2e6b5d19c84c82b40fdd684, not current master, as I didn't rebase. Given the latest latency improvements, I probably should repeat this after a rebase, but from this benchmark, it doesn't look expensive at all. Quite on the contrary, actually. (Without precomputation of `cashed_by_hash`, the times are 10.98s and 3.49s, so it's probably worth it.)

**Comment by martinholters** [comment]
After rebasing (to 6185d24ac3), `@time plot(rand(10))` is pretty much unaffected by this PR, while `@time using Plots` still shows an improvement, albeit a smaller one: from 11.6s to 9.5s.

**Comment by martinholters** [comment]
Sill trying to get a feel for the cost of this, I can first report that `touch base/compiler/compiler.jl ; time make` is pretty much unaffected (within measurement noise).

I'm a bit puzzled by
```julia
julia> @btime ==(Vector{Tuple{Integer}}, Vector{Tuple{>:Int}})
  11.548 μs (6 allocations: 320 bytes) # master
  5.343 μs (6 allocations: 320 bytes) # PR
false
```
Why is this getting faster? Does it involve an `obviously_disjoint` (where I could enable the fastpath) somewhere?

@vtjnash, you claimed that this "seems slightly expensive". Any idea for a benchmark where might actually show?

**Comment by JeffBezanson** [comment]
I think it's ok to merge this. It fixes some things, and there doesn't seem to be a cost. I do agree we should do more in the future to help ensure that equality_is_identity is true for types used as type tags (`===typeof(x)` for some x). But this seems like a reasonable stopgap.
