### PR TITLE
Resolve instability from `reducedim_init`

### LINKED ISSUE #43461: Inference failure in `maximum` / `minimum`
Should this be able to infer the type?
```julia
julia> @inferred maximum([1 2; 3 4]; dims=1)
ERROR: return type Matrix{Int64} does not match inferred return type Union{Matrix{Float64}, Matrix{Int64}}
```
The instability is in `Base.reducedim_init(identity, max, [1 2; 3 4], 1)`

### PR DESCRIPTION
**Pull request by N5N3**
This PR fix the instability found by #43461.
Since some of them were introduced by #35316. I'm not sure do we need to backport this.

Test added.
Close #43461.

### CODE REVIEW

File: base/reducedim.jl [hunk 1]
```diff
@@ -148,9 +148,9 @@ for (f1, f2, initval, typeextreme) in ((:min, :max, :Inf, :typemax), (:max, :min
             Tr = v0 isa T ? T : typeof(v0)
 
             # but NaNs and missing need to be avoided as initial values
-            if (v0 == v0) === false
+            if isnan(v0)
```
Comment (KristofferC) [inline base/reducedim.jl:151]: How about `missing` (like the comment above discusses)?

Comment (N5N3) [reply base/reducedim.jl:151]: missing is handled below. (L153)

Comment (KristofferC) [reply base/reducedim.jl:151]: Ah, ok.
