### PR TITLE
Use `__repl_entry` prefix to shorten `shell_parse` stack traces

### LINKED ISSUE #54277: Too long stack traces at the REPL shell mode
I recently typed `;git push'` and got the following result:

Screenshot from 2024-04-26 15-26-28

Once I scrolled up, I saw this:

```julia
shell> git push'
ERROR: unterminated single quote
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] shell_parse(str::String, interpolate::Bool; special::String, filename::String)
    @ Base ./shell.jl:139
  [3] shell_parse (repeats 2 times)
    @ ./shell.jl:31 [inlined]
  [4] (::REPL.var"#104#116"{REPL.LineEditREPL})(line::Any)
    @ REPL ~/.julia/juliaup/julia-1.11.0-beta1+0.aarch64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1113
  [5] #invokelatest#2
    @ ./essentials.jl:1030 [inlined]
  [6] invokelatest
    @ ./essentials.jl:1027 [inlined]
  [7] (::REPL.var"#do_respond#93"{…})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL ~/.julia/juliaup/julia-1.11.0-beta1+0.aarch64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:976
  [8] #invokelatest#2
    @ ./essentials.jl:1030 [inlined]
  [9] invokelatest
    @ ./essentials.jl:1027 [inlined]
 [10] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.0-beta1+0.aarch64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2748
 [11] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/.julia/juliaup/julia-1.11.0-beta1+0.aarch64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1407
 [12] (::REPL.var"#75#81"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ~/.julia/juliaup/julia-1.11.0-beta1+0.aarch64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:457
Some type information was truncated. Use `show(err)` to see complete types.
```

That's a huge amount of noise. The bottom 8 stack frames (at least) should be removed IMO.

### PR DESCRIPTION
**Pull request by BioTurboNick**
Fixes #54277

Doesn't completely remove them, but vast improvement. I'll let someone else go the next step if desired.

Current:
```
shell> '
ERROR: unterminated single quote
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:44

shell>
```

Before:
```
shell> '
ERROR: unterminated single quote
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:44
 [2] shell_parse(str::String, interpolate::Bool; special::String, filename::String)
   @ Base .\shell.jl:139
 [3] shell_parse (repeats 2 times)
   @ .\shell.jl:31 [inlined]
 [4] (::REPL.var"#setup_interface##2#setup_interface##3"{REPL.LineEditREPL})(line::Any)
   @ REPL D:\.julia\juliaup\julia-1.12.3+0.x64.w64.mingw32\share\julia\stdlib\v1.12\REPL\src\REPL.jl:1324
 [5] (::REPL.var"#do_respond#73"{…})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
   @ REPL D:\.julia\juliaup\julia-1.12.3+0.x64.w64.mingw32\share\julia\stdlib\v1.12\REPL\src\REPL.jl:1186
 [6] run_interface(terminal::Base.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
   @ REPL.LineEdit D:\.julia\juliaup\julia-1.12.3+0.x64.w64.mingw32\share\julia\stdlib\v1.12\REPL\src\LineEdit.jl:2854
 [7] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
   @ REPL D:\.julia\juliaup\julia-1.12.3+0.x64.w64.mingw32\share\julia\stdlib\v1.12\REPL\src\REPL.jl:1663
 [8] (::REPL.var"#61#62"{REPL.LineEditREPL, REPL.REPLBackendRef})()
   @ REPL D:\.julia\juliaup\julia-1.12.3+0.x64.w64.mingw32\share\julia\stdlib\v1.12\REPL\src\REPL.jl:650
Some type information was truncated. Use `show(err)` to see complete types.

shell>
```

### CODE REVIEW

File: base/shell.jl [hunk 1]
```diff
@@ -28,8 +28,11 @@ function rstrip_shell(s::AbstractString)
     SubString(s, 1, 0)
 end)
 
-function shell_parse(str::AbstractString, interpolate::Bool=true;
-                     special::AbstractString="", filename="none")
+shell_parse(str::AbstractString, interpolate::Bool=true;
+            special::AbstractString="", filename="none") =
+    __repl_entry_shell_parse(str, interpolate, special, filename)
+
+function __repl_entry_shell_parse(str::AbstractString, interpolate::Bool, special::AbstractString, filename)
```
Comment (LilithHafner) [inline base/shell.jl:36]:
```suggestion
# N.B.: Any functions starting with __repl_entry cut off backtraces when printing in the REPL.
function __repl_entry_shell_parse(str::AbstractString, interpolate::Bool, special::AbstractString, filename)
```
Elsewhere we have this comment, which is very helpful as function names are typically not semantically meaningful.

**Review by LilithHafner — APPROVED** [review]
Thanks! I didn't know about the `__repl_entry` special handling and how easily extensible it is :)

**Comment by IanButterworth** [comment]
Related failure
```
REPL                                                        (8) \|         failed at 2025-12-26T08:09:13.297
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-master/julia-f3b5e7a35b/share/julia/stdlib/v1.14/REPL/test/repl.jl:247
Expression: startswith(s, "\e[0mERROR: unterminated single quote\nStacktrace:\n  [1] ") \|\| startswith(s, "\e[0m\e[1m\e[91mERROR: \e[39m\e[22m\e[91munterminated single quote\e[39m\nStacktrace:\n  [1] ")
```

**Comment by BioTurboNick** [comment]
I think I'm seeing #60239 here, so maybe that issue wasn't fully fixed? Otherwise all green.

**Comment by IanButterworth** [comment]
I think it's specifically that precompile statement https://github.com/JuliaLang/julia/issues/60643
So should be  fixed by https://github.com/JuliaLang/julia/pull/60775
