### PR TITLE
fix #34080, regression in printing qualified macro calls

### LINKED ISSUE #34080: Behavior change in v1.3.0 regarding Symbol in a QuoteNode
I have just upgraded to v1.3.0 and I noticed a behavior change regarding `QuoteNode()`. Here is a MWE:

```julia
julia> Expr(:(.), 
           Expr(:(.), :Base, QuoteNode(Symbol("Enums"))),
           QuoteNode(Symbol("@enum")))
:(Base.Enums.var"@enum")
```

And here is what I used to get in v1.2.0:

```julia
julia> Expr(:(.), 
           Expr(:(.), :Base, QuoteNode(Symbol("Enums"))),
           QuoteNode(Symbol("@enum")))
:(Base.Enums.@enum)
```

which is the expected behavior.

My code heavily relies on this to automatically generate custom enum types. Please help. Thanks.

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #34080

### CODE REVIEW

File: base/show.jl [hunk 1]
```diff
@@ -1483,15 +1485,18 @@ function show_unquoted(io::IO, ex::Expr, indent::Int, prec::Int, quote_level::In
...
             show_sym(io, arg1, allow_macroname=true)
+        elseif arg1 isa GlobalRef
+            show_globalref(io, arg1, allow_macroname=true)
         elseif is_expr(arg1, :(.)) && length(arg1.args) == 2
-            if arg1.args[1] isa Module
-                print(io, '(')
-                print(io, arg1.args[1])
-                print(io, ").")
+            m = arg1.args[1]
+            if m isa Symbol || m isa GlobalRef || is_expr(m, :(.), 2)
```
Comment (c42f) [inline base/show.jl]: Very minor: should we also allow `m isa Module` here in case people interpolate a module into the AST?

**Review by c42f — APPROVED** [review]
Looks great to me.

File: base/show.jl (hunk 1 above)
Comment (JeffBezanson) [reply base/show.jl]: The previous version of the code parenthesized Modules, but I'm not sure why. I guess we'd need `$` to be super accurate about it.

Comment (c42f) [reply base/show.jl]: Good point, it would be nice to generally show the difference between purely symbolic ASTs vs ASTs which have "unusual" objects interpolated into them. Especially for things like modules which `show` the same way as symbols.

**Comment by KristofferC** [comment]
Doesn't backport cleanly.

**Comment by c42f** [comment]
@KristofferC what's the procedure to do a complex backport? PR against the backports branch?

**Comment by JeffBezanson** [comment]
Yes, a PR against the backports branch should be fine. Thanks for handling this!! :heart:

**Comment by KristofferC** [comment]
Can also just push directly to the backports branch.
