### PR TITLE
Make UCP option the default for regex matching

### LINKED ISSUE #27084: Option to use PCRE2_UCP in regular expressions ("u regex flag)
Per the [PCRE2 documentation](http://www.pcre.org/current/doc/html/pcre2pattern.html#extraprops): 

> 
> If the PCRE2_UCP option is set, the behaviour is changed so that Unicode properties are used to determine character types, as follows:
> 
>   \d  any character that matches \p{Nd} (decimal digit)
>   \s  any character that matches \p{Z} or \h or \v
>   \w  any character that matches \p{L} or \p{N}, plus underscore
>     
(This is only a subset of the changes, other parts of the documentation mention changes to POSIX character class interpretations among other things.)

There's a `const UCP = UInt32(0x00020000)` defined in `base/pcre_h.jl`, but it doesn't seem to be used for anything. It would be very useful to have a regex flag that allowed us to specify to the regex library when we wanted UCP set. 

Perl seems to automatically set its `/u` flag (http://perldoc.perl.org/perlre.html under "Character set modifiers") when in 'unicode_strings' mode, which is the default mode in recent Perl versions. Julia could do the same (since Julia is also in 'unicode strings' mode by default) and make PCRE2_UCP the default mode, but the PCRE2 documentation says "Matching these sequences is noticeably slower when PCRE2_UCP is set" - if that's still the case in practice and there's performance impact, then UCP can be left just as a non-default flag that the user can enable by saying, for eg., `match(r"\w+"u, "~~கசடதபற_2!! ")`. Currently this returns: 

```
ERROR: LoadError: ArgumentError: unknown regex flag: u
Stacktrace:
 [1] Regex(::String, ::String) at .\regex.jl:43
 [2] @r_str(::LineNumberNode, ::Module, ::Any, ::Vararg{Any,N} where N) at .\regex.jl:83
in expression starting at REPL[76]:1
```

### PR DESCRIPTION
**Pull request by Keno**
Fixes #27084. Regexes now match based on unicode character properties,
rather than just ASCII character properties, e.g. `match(r"\w+", "café")`
will now match the entire word (and not just `caf`). This behavior can
be disabled with the `a` flag to the regex string macro (e.g. `r"\w+"a`).

### CODE REVIEW

File: base/regex.jl [hunk 1]
```diff
@@ -72,8 +76,12 @@ after the ending quote, to change its behaviour:
 - `s` allows the `.` modifier to match newlines.
 - `x` enables "comment mode": whitespace is enabled except when escaped with `\\`, and `#`
   is treated as starting a comment.
+- `a` disables `UCP` mode (enables ASCII mode). By default `\\B`, `\\b`, `\\D`, `\\d`, `\\S`,
+  `\\s`, `\\W`, `\\w`, etc match based on unicode character properties. With this option,
```
Comment (nalimilan) [inline base/regex.jl]: "etc." and "Unicode". "are recognized" -> "these sequences only match"
