### PR TITLE
Revert "better type inference for several functions taking `NTuple` args"

### LINKED ISSUE #55374: Large regression in union array benchmarks due to 'better type inference for several functions taking NTuple args (#55124)'
Latest Nanosoldier report shows large regression in the union array benchmarks, here are the top ones
# Benchmarks
| Benchmark | % Change | Significance Factor |
|:---:|:---:|:---:|
| union.array.(map, *, Float32, (false, false)) | 30305.68% | 18458.45x
| union.array.(map, *, Float64, (false, false)) | 29682.96% | 5624.19x
| union.array.(map, *, Int64, (false, false)) | 24487.60% | 18929.41x
| union.array.(map, *, Int8, (false, false)) | 24076.75% | 227276.64x
| union.array.(map, *, Bool, (false, false)) | 23804.87% | 53681.88x
| union.array.(map, *, Float32, (false, true)) | 17389.56% | 842.80x
| union.array.(map, *, Float32, (true, true)) | 17318.22% | 1046.03x
| union.array.(map, *, Int8, (true, true)) | 16607.94% | 8268.41x

More data available at https://tealquaternion.camdvr.org/compare.html?start=5a904ac97a89506456f5e890b8dabea57bd7a0fa&end=f2f188d57346a0163b82740ac0a758311c41004f&stat=min-wall-time or https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_date/2024-08/04/report.md?rgh-link-date=2024-08-04T17%3A48%3A31Z.

Bisected to 2179f146945039dca4093ea511c8fe6ea51276c9

### PR DESCRIPTION
**Pull request by vtjnash**
Reverts JuliaLang/julia#55124 as this turns out to hurt performance quite a bit

Closes #55374

### CODE REVIEW

File: base/ntuple.jl [hunk 1]
```diff
@@ -95,5 +95,5 @@ end
 function reverse(t::NTuple{N}) where N
     ntuple(Val{N}()) do i
         t[end+1-i]
-    end::NTuple
+    end
```
Comment (nsajko) [inline base/ntuple.jl:98]: Could you leave this part in? It's just an unconditional type assert, so it shouldn't cause any harm.

Comment (KristofferC) [reply base/ntuple.jl:98]: Let's get back to a known good state and we can readd this if it is shown with the benchmarks the regressed to be ok.
