### PR TITLE
RFC: clean up method reflection

### LINKED ISSUE #16042: REPL: Tab completion for a type throws a MethodError
On current master, the tab-completion for types does this:

```
julia> type T; x; end

julia> T(WARNING: Caught an exception in the keymap:
ERROR: MethodError: no method matching visit(::Base.REPLCompletions.##9#10, ::Array{Any,1})
Closest candidates are:
  visit(::Any, ::MethodTable)
  visit(::Any, ::TypeMapLevel)
  visit(::Any, ::TypeMapEntry)
ERROR: syntax: incomplete: premature end of input
 in eval at .\boot.jl:236
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
This does a few things to improve the results from `methods`, and clean up some internals:
- Adds back the `sig` and `tvars` fields to `Method`. Although technically redundant, this makes `Method` more intuitive for describing a method definition.
- Removes most uses of `TypeMapEntry` in reflection, de-coupling the method cache representation from anything user-facing.
- Fixes #16042 in passing.

Finally, we had a problem where `methods(f)` returned a full MethodTable (except sometimes!), but `methods(f, t)` returned an array of `Method`s. Those types are printed differently, plus we are only able to show keyword arguments if we have access to the `MethodTable`, due to how kwargs are implemented. We could always use `MethodTable`, but it's not iterable and building one is a very non-trivial process just for showing a list of methods.

To address this I added a `MethodSet` type, so we can return any subset of methods with a consistent interface and printing. This solves all of the problems, but I don't quite love it, so suggestions are welcome.

This could be used in `methodswith` as well, except that it can return methods from multiple functions so it doesn't quite fit.

Another option would be to return matches from a function's keyword arg sorter as well, so you'd get 2 entries in a returned array for each method with keyword args. The downside is that these are not really methods of the same function, and have non-obvious argument lists.

### CODE REVIEW

**Comment by iamed2** [comment]
For use of method reflection in the wild you can look at https://github.com/invenia/Mocking.jl. We needed `first` so I implemented iteration for MethodTable. There's also some signature-parsing shenanigans that were using TypeMapEntry here: https://github.com/invenia/Mocking.jl/blob/master/src/signature.jl#L33

**Comment by JeffBezanson** [comment]
I'm not sure that definition of iteration for MethodTable is correct any more.

Thanks for pointing me to this --- it's truly scary how an internal change leaked to a package within a matter of days. This is exactly why this PR is needed. You should not need to use `TypeMapEntry`; the representation of a cache is as subject to change as anything I can think of.

**Comment by JeffBezanson** [comment]
To expand a bit, I think it makes sense to have a `Method` type that (surprise) describes a single method, for the foreseeable future. Even if it is no longer used internally, we can continue to return `Method` objects for reflection. Some other types, like TypeMapEntry and MethodTable, are more ephemeral.

File: base/inference.jl [hunk 1]
```diff
@@ -3409,13 +3408,13 @@ end
 # make sure that typeinf is executed before turning on typeinf_ext
 # this ensures that typeinf_ext doesn't recurse before it can add the item to the workq
 
-precompile(methods(typeinf_edge).defs.sig)
+precompile(typeof(typeinf_edge).name.mt.defs.sig)
```
Comment (vtjnash) [inline base/inference.jl]: doesn't matter now, but eventually we should delete this line (it's been a no-op ever since inference0.ji was eliminated)

**Comment by vtjnash** [comment]
lgtm

File: base/reflection.jl [hunk 2]
```diff
@@ -224,15 +219,40 @@ function _methods(t::Array,i,lim::Integer,matching::Array{Any,1})
...
-    if ft <: Type || !isempty(ft.parameters)
-        # for these types of `f`, not every method in the table will necessarily
-        # match, so we need to filter based on its type.
-        return methods(f, Tuple{Vararg{Any}})
-    else
-        return ft.name.mt
+# high-level, more convenient method lookup functions
+
+# type for reflecting and pretty-printing a subset of methods
+type MethodSet
```
Comment (stevengj) [inline base/reflection.jl]: `<: AbstractSet{Method}`?

File: base/reflection.jl [hunk 3]
```diff
@@ -224,15 +219,40 @@ function _methods(t::Array,i,lim::Integer,matching::Array{Any,1})
...
+    ms::Array{Method,1}
+    mt::MethodTable
+end
+
+length(m::MethodSet) = length(m.ms)
+isempty(m::MethodSet) = isempty(m.ms)
+start(m::MethodSet) = start(m.ms)
+done(m::MethodSet, s) = done(m.ms, s)
+next(m::MethodSet, s) = next(m.ms, s)
+getindex(m::MethodSet, i::Int) = m.ms[i]
```
Comment (stevengj) [inline base/reflection.jl]: If we define `getindex`, shouldn't it be `MethodVector <: AbstractVector{Method}`? rather than `MethodSet`?   Or maybe don't define `getindex`?

Comment (stevengj) [inline base/reflection.jl]: The only use of `getindex` below seems to be for `methods[1]`, which could be replaced with `first(methods)`.

Comment (stevengj) [inline base/reflection.jl]: But maybe the ordering is useful to expose for some reason?

Comment (stevengj) [inline base/reflection.jl]: Or maybe it is useful to make it an `AbstractVector` subtype if only as a hint that `in` is O(n).

File: src/dump.c [hunk 4]
```diff
@@ -1440,6 +1440,8 @@ static jl_value_t *jl_deserialize_value_(ios_t *s, jl_value_t *vtag, jl_value_t
         m->isstaged = read_int8(s);
         m->file = (jl_sym_t*)jl_deserialize_value(s, NULL);
         m->line = read_int32(s);
+        m->sig = (jl_tupletype_t*)jl_deserialize_value(s, (jl_value_t**)&m->sig);
+        m->tvars = (jl_svec_t*)jl_deserialize_value(s, (jl_value_t**)&m->tvars);
```
Comment (yuyichao) [inline src/dump.c]: `wb`s?

File: base/reflection.jl (hunk 3 above)
Comment (JeffBezanson) [inline base/reflection.jl]: I'll remove `getindex`, which will give us more flexibility in the future. How about `MethodList`, since it is list-like in supporting forward iteration but not getindex?
