### PR TITLE
Remove backtrace entirely in shell mode

### LINKED ISSUE #40958: Scrub shell prompt backtrace up through `_spawn_primitive` frame
The REPL scrubs all stack frames prior to and including `eval` to avoid showing REPL-specific frames. I suggest doing the same for the shell prompt, the top meaningful frame of which seems to be `_spawn_primitive`. Maybe there are other places for errors to emerge from that would be scrub targets, I just haven't seen them yet.

```
shell> test
ERROR: IOError: could not spawn `test`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
   @ Base .\process.jl:99
 [2] #637
   @ .\process.jl:112 [inlined]
 [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
   @ Base .\process.jl:196
 [4] _spawn
   @ .\process.jl:111 [inlined]
 [5] run(::Cmd; wait::Bool)
   @ Base .\process.jl:439
 [6] run
   @ .\process.jl:438 [inlined]
 [7] repl_cmd(cmd::Cmd, out::Base.TTY)
   @ Base .\client.jl:69
 [8] top-level scope
   @ none:1
```

### PR DESCRIPTION
**Pull request by BioTurboNick**
Resolves #40958

With this PR, as suggested by @simeonschaub, the REPL scrubs all stack frames when the shell mode produces an error, and just displays the error itself.

### CODE REVIEW

**Comment by KristofferC** [comment]
Maybe this should be done for the shell repl mode evaluation function to just not show any backtrace, instead of putting it in the general backtrace filter?

**Comment by BioTurboNick** [comment]
Hmm... looks like it is just a Windows problem. Nightly Windows has the stack traces, master on WSL does not.

File: base/client.jl [hunk 1]
```diff
@@ -66,7 +66,15 @@ function repl_cmd(cmd, out)
             end
             cmd = `$shell -c $shell_escape_cmd`
         end
-        run(ignorestatus(cmd))
+        try
+            run(ignorestatus(cmd))
+        catch
+            # strip backtrace and display error
+            # mainly for Windows
```
Comment (KristofferC) [inline base/client.jl:73]: It's a bit unclear to me what "mainly for windows" here refers to.

Comment (BioTurboNick) [reply base/client.jl:73]: When it isn't on Windows, commands go to a shell that prints an error but doesn't produce a Julia exception. On Windows, there is a Julia exception. But I don't know if there are other cases where this might not hold true.

Comment (KristofferC) [reply base/client.jl:73]: Aha, I didn't know that was the case.

**Comment by BioTurboNick** [comment]
Actually, looks like the root issue is that on Windows, Shell mode tries to directly execute the processes, rather than using `cmd.exe` or `powershell.exe` to do it.

**Comment by BioTurboNick** [comment]
"don't shell out on Windows where there are no real shells." is a comment from 8 years ago on a commit in this code. Which is fair. But if you're someone who uses Windows, probably could use powershell.

**Comment by BioTurboNick** [comment]
Okay I see there are several other issues, so fixing one of those would really be best. I'll make note of that in the comment.

#16565 
#31490

and more.

At least this PR will make it a bit nicer to use in current form.

File: base/client.jl [hunk 2]
```diff
@@ -66,7 +66,15 @@ function repl_cmd(cmd, out)
...
             cmd = `$shell -c $shell_escape_cmd`
         end
-        run(ignorestatus(cmd))
+        try
+            run(ignorestatus(cmd))
+        catch
+            # Windows doesn't shell out right now (complex issue), so Julia tries to run the program itself
+            # Julia throws an exception if it can't find the program, but the stack trace isn't useful
+            lasterr = current_exceptions()
+            lasterr = ExceptionStack([(exception = e[1], backtrace = [] ) for e in lasterr])
```
Comment (vtjnash) [inline base/client.jl:75]: This probably should have been an `Any[]` to avoid the copy inside the constructor
