### PR TITLE
Fix for #25847 (leaking Futures) 

### LINKED ISSUE #25847: Bug in distributed garbage collection of Futures
Hi,
      Please see the [discussion of this issue on discourse](https://discourse.julialang.org/t/understanding-distributed-memory-garbage-collection/8726) for a more detailed explanation. I'm grateful to @amitmurthy for his quick response to my original Discourse post. Here's a shorter description of the bug, including the same MWE as on Discourse:

We have a master function that manages a parallel computation in which subproblem computations are performed on remote worker processes and the results are collected on the master process. There can be more than one subproblem per worker. There is some input data on the master process needed by all subproblems. The master process communicates this data once to each worker. When this is implemented as in the MWE below the input arrays passed to the workers seem to never be garbage collected and the memory used by the program increases until the system runs out of memory and the program crashes. This "memory leak" occurs only when there are multiple Julia worker processes and there is more than one subproblem per worker. The code needed to reproduce this is:
```
function workerFunction( sigmaRef::Future )

   sigma = fetch(sigmaRef)
   println(sum(sigma))

   return true
end

function leakingMasterFunction( n1::Int, n2::Int )

   sigma      = ones(n1)
   nw         = nworkers()
   workerList = workers()
   sigmaRef   = Array{Future}(nw)
   
   @sync begin
       for i in 1:nw
           p = workerList[i]
           @async begin

              sigmaRef[i] = remotecall_wait(identity,p,sigma)
              
              for idx = 1:n2
                 b = remotecall_fetch(workerFunction,p,sigmaRef[i])
              end  # idx

           end  # @async begin
       end  # p
   end  # @sync begin

end  # func
```
Assuming we've launched Julia with two or more workers and loaded the above functions, executing the following from the REPL with two or more subproblems per workers (`nPerWorker >= 2`) causes the memory used by Julia to increase until the system runs out of memory and the code crashes with an out of memory error
```
> nPerWorker = 2
> while true; masterFunction( 5000000 , nPerWorker); end
```
With `nPerWorker = 1` The infinite loop continues to run forever with relatively constant memory usage. This behaviour has been confirmed by my colleagues on OS X and Linux with Julia versions 0.6.1 and 0.6.2. as well as by @amitmurthy on 0.6.2. I've also confirmed that it exists on Linux on master:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.3677
Commit ecb8b56075 (2018-02-01 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
@amitmurthy suggested a workaround on Discourse, which he tested on 0.6.2. I've confirmed that his workaround also works on master at the commit in the above versioninfo dump.

### PR DESCRIPTION
**Pull request by amitmurthy**
This fixes a leak of Futures when unfetched Futures are repeatedly serialized to the node with the reference store.

Closes https://github.com/JuliaLang/julia/issues/25847

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

File: stdlib/Distributed/src/remotecall.jl [hunk 1]
```diff
@@ -292,24 +292,29 @@ function serialize(s::ClusterSerializer, rr::AbstractRemoteRef, addclient)
...
-    Future(f.where, RRID(f.whence, f.id), f.v) # ctor adds to client_refs table
+    f = invoke(deserialize, Tuple{ClusterSerializer, DataType}, s, t)
+    f2 = Future(f.where, RRID(f.whence, f.id), f.v) # ctor adds to client_refs table
+
+    # 1) send_add_client() is not executed when the ref is being serialized
+    #    to where it exists, hence do it here.
+    # 2) If we have recieved a 'fetch'ed Future or if the Future ctor found an
+    #    already 'fetch'ed instance in client_refs (Issue #25847), we should not
+    #    track it in the backing RemoteValue store.
+    if f2.where == myid() && f2.v === nothing
```
Comment (JeffBezanson) [inline stdlib/Distributed/src/remotecall.jl]: Could you explain a bit more how this works? It seems like a data race to me --- we `add_client` for the current process only if the future is not done computing yet, and we don't know when that will happen.

Comment (amitmurthy) [reply stdlib/Distributed/src/remotecall.jl]: Given a Future created on node 1 but pointing to data on node 2 (i.e., where=2, whence=1) :

If it is unfetched and sent to node 3, `add_client` is invoked here - https://github.com/JuliaLang/julia/blob/4115c9cb88a9e81faacff4ba41a5d420b3f6cf44/stdlib/Distributed/src/remotecall.jl#L287-L290
(Note that the `if addclient` is checking if the Future is unfetched, i.e. same as `if f.v === nothing) 

If it has been fetched and is being sent to 3, no `add_client` is performed since it is assumed that the fetch call would have removed the reference to the backing store and it may been collected on the remote node.
The del_client here - https://github.com/JuliaLang/julia/blob/4115c9cb88a9e81faacff4ba41a5d420b3f6cf44/stdlib/Distributed/src/remotecall.jl#L494

Now, add_client as a message is not sent if the Future is being sent to the "where" node, 2 in this case, as the add_client will be performed during the deserialization process.

The bug in this case manifested during the second time the Future was serialized to its "where" node. The first time it was sent, the `Future` constructor did not find an entry in `client_refs`, created one and setup a finalizer - https://github.com/JuliaLang/julia/blob/4115c9cb88a9e81faacff4ba41a5d420b3f6cf44/stdlib/Distributed/src/remotecall.jl#L64-L79 . In the bug report posted, the remote function invoked with this Future did a `fetch`. This resulted in a) the "whence" id, i.e. 1  in this case, being removed from PGRP.refs[rrid].clientset (as `fetch` invokes a del_client the first time it is invoked on a Future), and b) Future.v being populated with the computation value.
Now the second time this same Future was sent to 2, the deserialization/Future constructor code immediately returned a cached instance (from `client_refs`) and an add_client was done. The remote function invoked `fetch`, which again directly returned `Future.v` (did not execute a `del_client` as was done for the first time `fetch` was called). This extra `add_client` was the source of the leak as the finalizer code does NOT execute a `del_client` on fetched Futures. See here - 
https://github.com/JuliaLang/julia/blob/4115c9cb88a9e81faacff4ba41a5d420b3f6cf44/stdlib/Distributed/src/remotecall.jl#L93

The fix avoids doing an add_client if a Future has been fetched in both cases (i.e., destination node same as "where" node and when it is different).

Comment (JeffBezanson) [reply stdlib/Distributed/src/remotecall.jl]: Great explanation, thank you!

**Comment by amitmurthy** [comment]
CI errors appear to be unrelated. CircleCI-i686 went through but failed at the last step. The other failed at build time. AV appears to have failed very early on in the build step.

Merging in a few hours if there are no objections.
