### PR TITLE
Fix no-arg `ScopedValues.@with` within a scope

### LINKED ISSUE #56017: No-arg `ScopedValues.@with` doesn't like being in a scope
```julia
julia> x = Base.ScopedValues.ScopedValue(1)
Base.ScopedValues.ScopedValue{Int64}(1)

julia> Base.ScopedValues.@with x => 2 begin
           Base.ScopedValues.@with begin
               @show x
           end
       end
ERROR: MethodError: Cannot `convert` an object of type Base.ScopedValues.Scope to an object of type Base.PersistentDict{Base.ScopedValues.ScopedValue, Any}
The function `convert` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  convert(::Type{T}, ::T) where T<:AbstractDict
   @ Base abstractdict.jl:571
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:129
  convert(::Type{T}, ::AbstractDict) where T<:AbstractDict
   @ Base abstractdict.jl:573

Stacktrace:
 [1] Base.ScopedValues.Scope(values::Base.ScopedValues.Scope)
   @ Base.ScopedValues ./scopedvalues.jl:85
 [2] top-level scope
   @ REPL[3]:2
```

```
julia> versioninfo()
Julia Version 1.12.0-DEV.1315
Commit bb5aa5bd16* (2024-10-06 02:17 UTC)
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/56017

### CODE REVIEW

File: base/scopedvalues.jl [hunk 1]
```diff
@@ -85,6 +85,10 @@ struct Scope
     values::ScopeStorage
 end
 
+function Scope(parent::Scope)
+    return Scope(parent.values)
+end
```
Comment (IanButterworth) [inline base/scopedvalues.jl:90]: Or should this just forward?
```suggestion
Scope(parent::Scope) = parent
```

Comment (IanButterworth) [reply base/scopedvalues.jl:90]: That's what https://github.com/JuliaLang/julia/pull/53462 does so I'll do that it here.

**Review by simonbyrne — APPROVED** [review]
