### PR TITLE
Fix bug in schur for zero dimension matrices

### LINKED ISSUE #752: `schur` fails for zero dimension matrices
The function `schur` fails for zero dimension matrices:

```
julia> schur(zeros(0,0),ones(0,0))
 ** On entry to DGGES PMGTL parameter number 15 had an illegal value
ERROR: ArgumentError: invalid argument JuliaLang/julia#15 to LAPACK call
Stacktrace:
 [1] gges!(::Char, ::Char, ::Array{Float64,2}, ::Array{Float64,2}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\lapack.jl:36
 [2] schur! at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\schur.jl:252 [inlined]
 [3] schur(::Array{Float64,2}, ::Array{Float64,2}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\schur.jl:268   
 [4] top-level scope at REPL[4]:1
```

The fix is easy: in the function `LAPACK.gges!` the parameters `ldvsl` and  `ldvsr` must be set to `max(1,n)`.

### LINKED ISSUE #36957: `schur` fails for zero dimension matrices
The function `schur` fails for zero dimension matrices:

```
julia> schur(zeros(0,0),ones(0,0))
 ** On entry to DGGES PMGTL parameter number 15 had an illegal value
ERROR: ArgumentError: invalid argument #15 to LAPACK call
Stacktrace:
 [1] gges!(::Char, ::Char, ::Array{Float64,2}, ::Array{Float64,2}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\lapack.jl:36
 [2] schur! at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\schur.jl:252 [inlined]
 [3] schur(::Array{Float64,2}, ::Array{Float64,2}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\schur.jl:268   
 [4] top-level scope at REPL[4]:1
```

The fix is easy: in the function `LAPACK.gges!` the parameters `ldvsl` and  `ldvsr` must be set to `max(1,n)`.

### PR DESCRIPTION
**Pull request by cfauchereau**
Fix JuliaLang/LinearAlgebra.jl#752
As described in the associated issue, the `ldvsl` and `ldvsr` parameters for the lapack `gges` function must be set to `max(1, n)` to account for zero dimension matrices.

### CODE REVIEW

File: stdlib/LinearAlgebra/test/schur.jl [hunk 1]
```diff
@@ -132,6 +132,16 @@ aimg  = randn(n,n)/2
...
+    @testset "0x0 $eltya matrices" begin
+        A = zeros(eltya, 0, 0)
+        B = zeros(eltya, 0, 0)
+        S = LinearAlgebra.schur(A, B)
+        @test S.S == A
+        @test S.T == A
+        @test S.Q == A
+        @test S.Z == A
+        @test S.alpha == zeros(0)
+        @test S.beta == zeros(0)
```
Comment (dkarrasch) [inline stdlib/LinearAlgebra/test/schur.jl:144]:
```suggestion
        @test S.beta == zeros(0)
    end
```
?

Comment (clement-f) [reply stdlib/LinearAlgebra/test/schur.jl:144]: Yes, of course, I messed up with git, the version I tested and intended to send had the end statement.

**Comment by dkarrasch** [comment]
This requires a rebase onto current master, I guess. Some checksums of SuiteSparse appear to be out-of-sync or something?

**Review by dkarrasch — APPROVED** [review]
