### PR TITLE
invoke should raise MethodError for ambiguous cases

### LINKED ISSUE #18095: invoke should raise MethodError for ambiguous cases
Currently we have this:

``` jl
julia> f(::Int, ::Number) = 1
f (generic function with 1 method)

julia> f(::Number, ::Int) = 2
f (generic function with 2 methods)

julia> f(1,2)
ERROR: MethodError: f(::Int64, ::Int64) is ambiguous. Candidates:
  f(::Number, ::Int64) at REPL[1]:1
  f(::Int64, ::Number) at REPL[0]:1

julia> invoke(f, (Int,Int), 1, 2)
1
```

When `invoke` is called with an ambiguous tuple of types, it should raise the same error as when the function is simply called with arguments of those types. Discovered while playing with the `@invoke` macro I cooked up [here](https://github.com/JuliaLang/julia/pull/13123#issuecomment-240552541).

### LINKED ISSUE #22988: which() reports "no method found" when there is an ambiguity
I believe the following behavior of `which()` is not intended:

```
julia> f(a::Int, b) = a+b
f (generic function with 1 method)

julia> f(a, b::Int) = a-b
f (generic function with 2 methods)

julia> f(2,2) # to highlight that there is an ambiguity
ERROR: MethodError: f(::Int64, ::Int64) is ambiguous. Candidates:
  f(a, b::Int64) in Main at REPL[2]:1
  f(a::Int64, b) in Main at REPL[1]:1
Possible fix, define
  f(::Int64, ::Int64)

julia> which(f, Tuple{Int,Int})
ERROR: no method found for the specified argument types
Stacktrace:
 [1] which(::Any, ::Any) at ./reflection.jl:823
```

Instead of saying that there is "no method found", `which()` should give an error indicating that there is an ambiguity. Looking at the source https://github.com/JuliaLang/julia/blob/2b983d41f064c39c0b73f6c7695cc13e0de45c03/base/reflection.jl#L878, it looks like an ambiguity error was intended. Blame shows that none of this code has changed for a while.

I think it's worth fixing or changing the error to say that it might be an ambiguity because it was quite confusing to me when debugging.

Sorry if this is a duplicate issue - it's not too easy to search for issues involving "which".

Also, my `versioninfo()`:
```
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
```

### PR DESCRIPTION
**Pull request by vtjnash**
fix #18095
fix #22988 (by improving error message)

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

File: src/gf.c [hunk 1]
```diff
@@ -1552,7 +1552,7 @@ jl_method_instance_t *jl_method_lookup_by_type(jl_methtable_t *mt, jl_tupletype_
         JL_UNLOCK(&mt->writelock);
         return linfo;
     }
-    if (jl_is_leaf_type((jl_value_t*)types))
+    if (jl_is_leaf_type((jl_value_t*)types)) // FIXME: this is the wrong predicate
```
Comment (StefanKarpinski) [inline src/gf.c]: Concerning... could you elaborate on why it's the wrong predicate, why you can't use the right predicate and in what direction this would need to change in order to be correct?

Comment (vtjnash) [reply src/gf.c]: #23606
