### PR TITLE
rough fix to allow at-pure optimization for generated thunks that have the pure field set

### LINKED ISSUE #108: `@pure` seems to cause issues!
```
Base.@pure datatype_align(::Type{T}) where T = T.layout

function broken(::Type{T}) where {T}
     align = datatype_align(T)
     Val(align)
end

using Cassette
Cassette.@context CUDACtx
const cudactx = Cassette.disablehooks(CUDACtx())

# Comment this out 
function Cassette.overdub(::CUDACtx, ::typeof(datatype_align), ::Type{T}) where T
    datatype_align(T)
end
```

### PR DESCRIPTION
**Pull request by jrevels**
I'm sure this is a broken implementation, but it fixes https://github.com/jrevels/Cassette.jl/issues/108.

Before this PR:

```julia
julia> Base.@pure datatype_align(::Type{T}) where T = T.layout
datatype_align (generic function with 1 method)

julia> function broken(::Type{T}) where {T}
            align = datatype_align(T)
            Val(align)
       end
broken (generic function with 1 method)

julia> using Cassette

julia> Cassette.@context CUDACtx;

julia> const cudactx = Cassette.disablehooks(CUDACtx());

julia> @code_typed Cassette.overdub(cudactx, broken, Float64)
CodeInfo(
1 ─ %1 = Base.getfield($(QuoteNode(Float64)), :layout)::Ptr{Nothing}
│   %2 = invoke Cassette.overdub(_2::Cassette.Context{nametype(CUDACtx),Nothing,Nothing,getfield(Cassette, Symbol("##PassType#365")),Nothing,Cassette.DisableHooks}, Main.Val::Type{Val}, %1::Ptr{Nothing})::Any
└──      return %2
) => Any
```

After this PR:

```julia
julia> @code_typed Cassette.overdub(cudactx, broken, Float64)
CodeInfo(
1 ─ %1 = Base.getfield($(QuoteNode(Float64)), :layout)::Ptr{Nothing}
│   %2 = invoke Cassette.overdub(_2::Cassette.Context{nametype(CUDACtx),Nothing,Nothing,getfield(Cassette, Symbol("##PassType#365")),Nothing,Cassette.DisableHooks}, Main.Val::Type{Val}, %1::Ptr{Nothing})::Const(Val{Ptr{Nothing} @0x000000011495c010}(), true)
└──      return %2
) => Val{Ptr{Nothing} @0x000000011495c010}
```

### CODE REVIEW

File: base/compiler/abstractinterpretation.jl [hunk 1]
```diff
@@ -560,9 +560,16 @@ function pure_eval_call(@nospecialize(f), argtypes::Vector{Any}, @nospecialize(a
...
     meth = meth[1]::SimpleVector
+    sig = meth[1]::DataType
+    sparams = meth[2]::SimpleVector
     method = meth[3]::Method
-    # TODO: check pure on the inferred thunk
-    if isdefined(method, :generator) || !method.pure
+
+    if isdefined(method, :generator)
+        method.generator.expand_early || return false
+        mi = code_for_method(method, sig, sparams, sv.params.world, false)
```
Comment (jrevels) [inline base/compiler/abstractinterpretation.jl]: should `sig` here be derived from `atypes` rather than pulled from the method lookup?

**Comment by jrevels** [comment]
Bump?

**Comment by vchuravy** [comment]
Would be good to get some eyes on this since this leads to a Cassette performance cliff, since it can circumvent `@pure` annotations for functions like `isbitstype`

**Comment by ararslan** [comment]
Bump. Anybody?

**Comment by jrevels** [comment]
bumpety bump

File: base/compiler/abstractinterpretation.jl [hunk 2]
```diff
@@ -560,9 +560,16 @@ function pure_eval_call(@nospecialize(f), argtypes::Vector{Any}, @nospecialize(a
...
+        isa(mi, MethodInstance) || return false
+        get_staged(mi).pure || return false
```
Comment (vtjnash) [inline base/compiler/abstractinterpretation.jl]: `get_staged(mi) isa CodeInfo && .pure || return false`

**Comment by vchuravy** [comment]
Rebased, added a test and addressed Jameson's comment.
