### PR TITLE
Use correct predicate to test for bitstype

### LINKED ISSUE #28102: getfield for incompletely initialized "plain data" throws an UndefRefError
The example defining "HasPlain" under [Incomplete Initialization in Constructor](https://docs.julialang.org/en/latest/manual/constructors/#Incomplete-Initialization-1)  states

> While you are allowed to create objects with uninitialized fields, any access to an uninitialized reference is an immediate error... This avoids the need to continually check for null values. However, not all object fields are references. Julia considers some types to be "plain data", meaning all of their data is self-contained and does not reference other objects. The plain data types consist of primitive types (e.g. Int) and immutable structs of other plain data types. The initial contents of a plain data type is undefined... Arrays of plain data types exhibit the same behavior.

This suggested to me that Julian plain data has LLVM undefined value semantics, so that it can be lazily defined or optimized down to its effects by the compiler. Instead, I've found that calling getfield on an incompletely initialized plain data instance varies in its behavior over recent betas, with beta 45 yielding a runtime error the first time but otherwise behaving as expected, and beta 272 throwing an UndefRefError:

```julia
struct HasPlain                  # modified example from "Constructors"
   plain::Int
   HasPlain() = new()
end
function bam()
  x = HasPlain()                     
  print(isdefined(x,:plain),"\n") # always prints true
  if isdefined(x,:plain)
    x.plain
  end
end
bam()                             # UndefRefError: access to undefined reference
```

```
julia> bam()
true
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty at ./sysimg.jl:18 [inlined]
 [2] bam() at ./REPL[2]:5
 [3] top-level scope at none:0

julia> 

julia> versioninfo()
Julia Version 0.7.0-beta.272
Commit 0f4b15a59c* (2018-07-12 07:27 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

This can evidently be "fixed" by storing the incompletely initialized plain data instance to a mutable location first, i.e. replacing the assignment in the function above with `x = Ref(HasPlain()).x`, but (a) given the importance of immutability to the compiler I was thinking that that might miss optimization opportunities, and (b) if instead that or some other step is necessary for incomplete initialization of plain data, perhaps it needs to be documented.

### PR DESCRIPTION
**Pull request by Keno**
Fixes #28102

### CODE REVIEW

File: test/core.jl [hunk 1]
```diff
@@ -6279,3 +6279,17 @@ f27910() = ((),)[2]
...
 @test_throws TypeError g9765()
+
+# Issue 28102
+struct HasPlain28102
+   plain::Int
+   HasPlain28102() = new()
+end
+@noinline function bam28102()
+  x = HasPlain28102()
+  print(isdefined(x,:plain),"\n") # always prints true
```
Comment (vtjnash) [inline test/core.jl]: Delete this and fix indent and spacing
