### PR TITLE
Fix #13223, linear indexing of sparse matrices

### LINKED ISSUE #13223: Linear indexing of sparse matrices is slow
Case 1: this is quite slow for what is just a resize.

```
julia> r=[1;10000]
2-element Array{Int64,1}:
     1
 10000

julia> A=sparse(r,r,r)
10000x10000 sparse matrix with 2 Int64 entries:
	[1    ,     1]  =  1
	[10000, 10000]  =  10000

julia> B=A[:]
100000000x1 sparse matrix with 2 Int64 entries:
	[1        ,         1]  =  1
	[100000000,         1]  =  10000
```

Case 2: This one crashes even tho the 64 bit intsize should be enough to accomodate an index of 1e10.

```
julia> r=[1;100000]
2-element Array{Int64,1}:
      1
 100000

julia> A=sparse(r,r,r)
100000x100000 sparse matrix with 2 Int64 entries:
	[1     ,      1]  =  1
	[100000, 100000]  =  100000

julia> B=A[:]
ERROR: OutOfMemoryError()
 in getindex at sparse/sparsematrix.jl:1709
 in getindex at sparse/sparsematrix.jl:1295
```

### PR DESCRIPTION
**Pull request by tkelman**
make `getindex(A::SparseMatrixCSC, I::AbstractArray)` faster by allocating
at most the number of nonzeros in `A`, and add a specialized implementation
for `getindex(A::SparseMatrixCSC, I::UnitRange)`

before:

```
 _/ |\__'_|_|_|\__'_|  |  Commit 7a4d817* (0 days old master)
|__/                   |  x86_64-linux-gnu
julia> r=[1;10000]
2-element Array{Int64,1}:
     1
 10000
julia> A=sparse(r,r,r)
10000x10000 sparse matrix with 2 Int64 entries:
        [1    ,     1]  =  1
        [10000, 10000]  =  10000
julia> @time A[:]
  1.839530 seconds (40.10 k allocations: 1.492 GB, 0.16% gc time)
Sparse vector of length 100000000, with 2 Int64 nonzero entries:
  [1        ]  =  1
  [100000000]  =  10000
```

after:

```
 _/ |\__'_|_|_|\__'_|  |  tk/fix13223/f0f5938* (fork: 1 commits, 0 days)
|__/                   |  x86_64-linux-gnu
julia> r=[1;10000]
2-element Array{Int64,1}:
     1
 10000
julia> A=sparse(r,r,r)
10000x10000 sparse matrix with 2 Int64 entries:
        [1    ,     1]  =  1
        [10000, 10000]  =  10000
julia> @time A[:]
  0.028696 seconds (58.86 k allocations: 2.627 MB)
Sparse vector of length 100000000, with 2 Int64 nonzero entries:
  [1        ]  =  1
  [100000000]  =  10000
julia> @time A[:]
  0.000020 seconds (7 allocations: 352 bytes)
Sparse vector of length 100000000, with 2 Int64 nonzero entries:
  [1        ]  =  1
  [100000000]  =  10000
```

### CODE REVIEW

File: base/sparse/sparsevector.jl [hunk 1]
```diff
@@ -421,12 +423,46 @@ function getindex{Tv}(A::SparseMatrixCSC{Tv}, I::AbstractVector)
...
+
+function getindex{Tv}(A::SparseMatrixCSC{Tv}, I::AbstractVector)
+    szA = size(A)
+    nA = szA[1]*szA[2]
+    colptrA = A.colptr
+    rowvalA = A.rowval
+    nzvalA = A.nzval
 
+    n = length(I)
+    nnzB = min(n, nnz(A))
```
Comment (tkelman) [inline base/sparse/sparsevector.jl]: Ah, wait, I need to check this against index vectors with repeats, don't I. Maybe keep this as a reasonable initial guess but have a fallback that does `push!(rowvalB, i); push!(nzvalB, nzvalA[r])` if `idxB > nnzB` below. Thoughts?

**Comment by ViralBShah** [comment]
@tanmaykm  Could you please take a look at this one too?

**Comment by ViralBShah** [comment]
Looks good to me.

File: base/sparse/sparsevector.jl (hunk 1 above)
Comment (ViralBShah) [inline base/sparse/sparsevector.jl]: The repeated index case is quite common, and you have to do `push!`, or have a separate phase where you count the result size first, and then do the full operation again.

Comment (tkelman) [inline base/sparse/sparsevector.jl]: Need a better repository of real test code to benchmark sanely. I'd rather underallocate and grow an amortized number of times than overallocate for the case where many of the selected elements are zeros, but there will be corner cases for both.

**Comment by tkelman** [comment]
I wonder whether the AbstractVector indexing case should first calculate a sortperm of the indices so the sparse matrix can be traversed efficiently (as opposed to having to search an entire column at each index) to get the nonzero results first, then put them in the right order for the output. Does the matrix indexing do anything like this right now? Future work for a later PR, maybe.

**Comment by ViralBShah** [comment]
That is the right thing to do. Another PR perhaps? `sortperm` is used in a number of places in the indexing code, like in `getindex_general`.

**Comment by ViralBShah** [comment]
Anything holding the merge?

**Comment by tkelman** [comment]
Was waiting for Tanmay to review, but if no one has any comments I think we can merge this for now and keep working on things gradually with future PR's.
