### PR TITLE
RFC: Move Colon translation out of the parser

### LINKED ISSUE #9419: allow `getindex(::MyType, ::Colon)` to be customized
And similarly for `setindex!`.
For example:
```
type A end
Base.getindex(a::A, ::Range) = 0
Base.getindex(a::A, ::Colon) = 1

julia> A()[:]
ERROR: `endof` has no method matching endof(::A)
```
This is worse if `endof(::A)` is defined, as then `A()[:]` chooses silently the unintended `getindex` method.

If allowing customization of `Base.getindex(a::A, ::Colon)` does not happen, I would request that `a[:]` is translated to `a[beginof(a):endof(a)]`, as some indexable collections have an indice starting at something else than 1.

At the very least, the doc for `getindex/setindex!` should mention this special case, where "The syntax `a[i,j,...]` is converted by the compiler to `getindex(a, i, j, ...)`" does not seem true.

Also, in "base/subarray.jl", this method is defined: `getindex{T}(v::AbstractArray{T,1}, ::Colon) = v`, should it be removed or is it used?

### PR DESCRIPTION
**Pull request by mbauman**
This is a work ~~in progress~~ to move the translation of `[:]` out of the parser.  I've squashed-and-split @andreasnoack's ambitious work from #9150 to exclude the bigger change (returning views from indexing with UnitRanges) and just focus on indexing with `Colon`.  While this previously included the code that adapted base array types to accept `Colon()` as an index, that portion was broken out and subsumed by #10525.  This is now _only_ the parser change.

~~This is still a work-in-progress as it hasn't made it through the test suite yet.  Right now the blocker is in `getindex(::SubArray, ::Colon)`, which is a pretty gnarly piece of metaprogramming.  But I think it's pretty close.  Would you have a chance to look into it, @timholy?~~

~~This takes a cue from SubArray and doesn't even create a range for indexing into Array types, which is really cool.  In general, this approach will require all custom `AbstractArray` types to allow indexing with `Colon`.  We could define a fallback `getindex(::AbstractArray, ::Union(Real, AbstractArray, Colon)…)` to do the lowering step, but it's then a little tricky for custom types to define their indexing methods without ambiguities.~~
### Todo:
- [x] ~~SubArray getindex~~ (subsumed by #10525)
- [x] ~~SharedArray get/setindex!~~ (subsumed by #10525)
- [x] ~~Improve inference (#10341) and revert a733b1f~~ (subsumed by #10525)
- [x] ~~Decide if we need a deprecation/warning strategy for indexing custom AbstractArray types with `:`. _I don't think this is possible in a sensible manner._~~ Became non-breaking with #10525.

Fixes #9419.

### CODE REVIEW

File: base/range.jl [hunk 1]
```diff
@@ -67,6 +67,8 @@ immutable UnitRange{T<:Real} <: OrdinalRange{T,Int}
 end
 UnitRange{T<:Real}(start::T, stop::T) = UnitRange{T}(start, stop)
 
+colon() = Colon()
```
Comment (JeffBezanson) [inline base/range.jl]: I don't think we need this. `colon` is never called with 0 arguments as far as I know. The front end can just produce `(top :)` or `(call (top Colon))` instead.

File: base/operators.jl [hunk 2]
```diff
@@ -224,16 +224,44 @@ function promote_shape(a::Dims, b::Dims)
...
+        end
+    end
+    ex
+end
+
 # shape of array to create for getindex() with indexes I
 # drop dimensions indexed with trailing scalars
-index_shape(I::Real...) = ()
-index_shape(i, I...) = tuple(length(i), index_shape(I...)...)
+stagedfunction index_shape(A::AbstractArray, I...)
```
Comment (JeffBezanson) [inline base/operators.jl]: I'd prefer to try to do this without a staged function. It should be possible by following the pattern of the old `index_shape` function.

**Comment by JeffBezanson** [comment]
Nice! This is something I've wanted for a while.

**Comment by JeffBezanson** [comment]
ref #9419

File: base/operators.jl (hunk 2 above)
Comment (mbauman) [inline base/operators.jl]: Hm, I'll have to think about that.  It's not as easy to recursively pick off the elements with `:` in the mix because the colon needs to know its position in the argument list.

Comment (andreasnoack) [inline base/operators.jl]: I gave up on this one for exactly that reason. I simply couldn't figure out how extract the right dimension of `A` in this recursive definition.

Comment (timholy) [inline base/operators.jl]: While I haven't thought it through in detail, it seems like it should be possible if you follow a pattern similar to `next`, e.g.,
```
index_shape_dim(A, dim, i::Colon, I...) = tuple(size(A, dim), index_shape_dim(A, dim+1, I...)...)
index_shape_dim(A, dim, i, I...) = tuple(length(i), index_shape_dim(A, dim+1, I...)...)
```

**Comment by timholy** [comment]
Sorry, can you give a little more detail about what you want me to look at? Currently I don't think there is a `getindex(::SubArray, ::Colon)`---are you saying that implementing it will be a gnarly bit of metaprogramming or something else?

My current proposal is that this shouldn't involve any metaprogramming at all: it should be
```
getindex(S::SubArray, ::Colon) = reshape(S, Colon())
```
and let a [new reshape](https://github.com/JuliaLang/julia/issues/9874#issuecomment-75979041) handle it. I suspect it will be cleaner and more efficient. (There is at least one nasty SubArray method I'm looking forward to deleting, if that proposal passes muster.)

**Comment by mbauman** [comment]
Sure.  I'm slowly grokking Cartesian more and more as I work my way through this, myself, too.  Right now, indexing a SubArray with a Colon() bails in the middle of the complicated [`merge_indexes_div`](https://github.com/JuliaLang/julia/blob/28419b452e481b8c00fcb2f4f0c71601b31de2ab/base/multidimensional.jl#L406).  But you're probably right that there'd be a better place to handle Colons for SubArrays.  I can keep toying with it, myself, but I just felt *so close* that I figured I'd post it and see if folks had any pointers.

Thanks for taking a look. :)

**Comment by timholy** [comment]
`merge_indexes` and `merge_indexes_div` are indeed the methods I'm so, so looking forward to deleting.

**Comment by timholy** [comment]
Any comments you have on the reshape proposal would certainly be helpful, though. I'm worried about the nesting, but since it allows us to avoid calling `div` or allocating big `Vector{Int}` indexes, I suspect it will be a win overall.

**Comment by mbauman** [comment]
By using recursive multiple dispatch for the index_shape, we seem to be running up against an inference boundary one dimension sooner than on master here:

```julia
julia> Base.return_types(getindex, (Array{Int,4}, UnitRange{Int}, Int))
1-element Array{Any,1}:
 Array{Int64,1}

julia> # This is well-typed and returns a Matrix on master, but not on this branch
       Base.return_types(getindex, (Array{Int,4}, UnitRange{Int}, UnitRange{Int}, Int))
1-element Array{Any,1}:
 Array{T,N}

julia> # Inference isn't precise on either my branch or master
       Base.return_types(getindex, (Array{Int,4}, UnitRange{Int}, UnitRange{Int}, UnitRange{Int}, Int))
1-element Array{Any,1}:
 Array{T,N}
```

**Comment by Jutho** [comment]
> Any comments you have on the reshape proposal would certainly be helpful, though. I'm worried about the nesting, but since it allows us to avoid calling div or allocating big Vector{Int} indexes, I suspect it will be a win overall.

I like the reshape proposal, but I don't understand the comment that this avoids calling `div`. The `ind2sub` call is filled with `div` and `rem` no? I guess it's probably also time to replace `ind2sub` with a `stagedfunction` that generates specialized code for every `N` in `dims::NTuple{N,Int}`?

**Comment by timholy** [comment]
Thanks for looking!

Regarding `div`, the current state does not reflect the final state. When more fully fleshed out, it will avoid calling `div` via https://github.com/JuliaLang/julia/issues/8188#issuecomment-56763806. Those magic numbers will be computed at the time of construction, and once computed they can be used for faster indexing. That's by far the most important optimization to make, but I'm sure you recognize many others, too.

**Comment by Jutho** [comment]
Great, looking forward to that. But probably it's still a good idea to reimplement `ind2sub` as well, as probably many people are using this. E.g., with the following:
```julia
stagedfunction myind2sub{N}(dims::NTuple{N,Integer}, ind::Int)
    subsyms = [symbol("i$k") for k=1:N]
    subex = Expr(:block,[:($(subsyms[k])=rem(ind,dims[$k])+1;ind=div(ind,dims[$k])) for k=1:N]...)
    quote
        ind-=1
        $(subex)
        $(Expr(:tuple,subsyms...))
    end
end
function test(N)
       @time for i=1:N;s=ind2sub((5,8,9,3),103);end
       @time for i=1:N;s2=myind2sub((5,8,9,3),103);end
end
```
I already obtain
```
julia> test(10000)
elapsed time: 0.004069134 seconds (2 MB allocated)
elapsed time: 0.000924436 seconds (0 bytes allocated)
```
I'll submit a PR later today.

**Comment by timholy** [comment]
:+1:

**Comment by Jutho** [comment]
On a related note, although I apologize for hijacking the original discussion, should we also have a `PermutedArray` to have a lazy/data-sharing version of `permutedims`? This could have efficient indexing if we are willing to encode the permutation as type parameter. The type parameter can not be determined at compile time, but I guess that's the same with `ReshapedArray`.

**Comment by timholy** [comment]
There seemed to be some enthusiasm for this general idea in #6837.

Not exactly sure what you mean by "type parameter cannot be determined at compile time," can you elaborate? I presume you're thinking of putting the actual permutation as a tuple into the parameters. If you can't get julia to dispatch on the tuple, you can use a 2-stage process:
```
getindex{T,N,P}(A::PermutedArray{T,N,P}, indexes...) = getindexP(A, P, indexes...)
stagedfunction getindexP{TT}(A, P::TT, indexes...)
    ...
end
```
The `TT` ("tuple-type") forces specialization on the type of `P`, even if `P` is a tuple. If `P` is encoded as a tuple of `Val`s (or you use a `val(P)` to convert it into one), then I think you can discover the permutation at compile time.

**Comment by Jutho** [comment]
I did indeed not explain myself properly, I meant, at the time where the `PermutedArray` is created; e.g. creating a `B::PermutedArray{T,N,A<:AbstractArray,P}` from `B=permutedims(parent::AbstractArray,P::(Int...,))` will require to transfer `P` from the value domain to the type domain, which I guess needs to happen dynamically. But then, once `B` is created, calling `getindex` on it has the information of `P` in the type domain and can thus generate efficient code that just permutes the indices as required.

**Comment by timholy** [comment]
Got it. I agree that it's not necessary to infer the permutation at compile time. Any computationally-heavy work should be in a separate function anyway.

**Comment by JeffBezanson** [comment]
> we seem to be running up against an inference boundary

I'm on the case! I may have a fix for this soon. I've been limiting argument lists too aggressively. I'm trying to switch this to only limit argument lists that are growing due to recursion.

**Comment by mbauman** [comment]
Updated! Now the only blocker is #10341.  I temporarily lowered the number of tested dimensions in the test-suite to see if AppVeyor or Travis will catch any other failures (all other tests pass on my machine).

The other thing I think needs a conscious decision here is if or how we want to handle a deprecation.  Custom array types in packages probably aren't prepared to with indexing methods for `::Colon`.

**Comment by mbauman** [comment]
Does Travis use 32-bit BLAS binaries?  That was handy for catching a missing method error that wasn't covered in the test suite.  (It's tested now).

**Comment by tkelman** [comment]
32-bit-ints, yeah. Generally distributions don't ship ILP64 BLAS, if they do they better be really careful about marking them as conflicting with every other BLAS package.

**Comment by mbauman** [comment]
Hm, now there's a strange OS X error that I'm not seeing locally:

```
	From worker 3:	     * arrayops            Worker 3 terminated.
Assertion failed: (rval->getType() == jl_pvalue_llvmt || rval->getType() == NoopType), function emit_assignment, file codegen.cpp, line 2920.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
```

All other platforms seem to be fine.

**Comment by JeffBezanson** [comment]
Ok #10341 is merged.

**Comment by mbauman** [comment]
Awesome!  Thanks Jeff.  The inferred types are now precise for up to 4 dimensions in [that test](https://github.com/JuliaLang/julia/blob/e190f8cb4f94e47e5edfa16f538d7814be89a8b2/test/arrayops.jl#L838-L850).

We'll see if this magically fixed the travis OS X segfault.

**Comment by mbauman** [comment]
Updated! We're set to go.  The only thing that remains on my list is a decision regarding backwards-compatibility for user AbstractArray types.

**Comment by mlubin** [comment]
This change will likely affect JuMP. I won't complain if this breaks things, since the old behavior has been holding us back for quite some time.
CC @IainNZ @joehuchette

**Comment by joehuchette** [comment]
Yeah, a big +1 to this.

**Comment by mbauman** [comment]
The 32-bit linux failure is sporadic (only happened in one of the six builds this morning), but I don't see any similar failures since we started testing 32-bit linux on Travis. The backtrace does go through a method I touched:

```
julia-debug: ast.c:714: jl_lam_gensyms: Assertion `(((jl_value_t*)((uptrint_t)((jl_value_t*)(l))->type & ((uintptr_t)~3)))==(jl_value_t*)(jl_expr_type))' failed.
signal (6): Aborted
__kernel_vsyscall at  (unknown line)
gsignal at /lib/i386-linux-gnu/libc.so.6 (unknown line)
abort at /lib/i386-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: -1233294155)
unknown function (ip: -1233293977)
jl_lam_gensyms at /home/travis/build/JuliaLang/julia/src/ast.c:715
emit_function at /home/travis/build/JuliaLang/julia/src/codegen.cpp:3714
to_function at /home/travis/build/JuliaLang/julia/src/codegen.cpp:603
jl_compile at /home/travis/build/JuliaLang/julia/src/codegen.cpp:732
jl_trampoline_compile_function at /home/travis/build/JuliaLang/julia/src/builtins.c:920
jl_trampoline at /home/travis/build/JuliaLang/julia/src/builtins.c:932
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1072
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:1686
_getindex at multidimensional.jl:237
⋮
```

@tkelman have you seen this before?

File: src/julia-syntax.scm [hunk 3]
```diff
@@ -332,7 +332,7 @@
 
 ; translate index x from colons to ranges
 (define (expand-index-colon x)
```
Comment (JeffBezanson) [inline src/julia-syntax.scm]: Looks like this whole function can be removed. We don't allow the `a[i:]` cases anymore, and `:` can just be left as an identifier (it's bound to `Colon()` in Base).

Comment (JeffBezanson) [inline src/julia-syntax.scm]: Also the comment for `process-indexes` should be updated.

**Comment by JeffBezanson** [comment]
This should get a NEWS item.

Also I wonder if, in light of how indexing works now, we can stop making numbers iterable. Indexing is now based on `index_lengths` and `unsafe_getindex` instead of the iteration protocol.

**Comment by toivoh** [comment]
+ a lot to making numbers non-iterable.

**Comment by StefanKarpinski** [comment]
I have wanted to try making numbers non-iterable for quite a long time, so +1 to at least giving it a shot.

**Comment by johnmyleswhite** [comment]
Not getting tricked by writing:

```
for i in 10
 do()
end
```

would be awesome.

**Comment by tkelman** [comment]
I think I've seen assertion failures from ast.c before, but I haven't been watching CI results super closely for the last few weeks.

**Comment by tkelman** [comment]
Though I do have a pretty strong feeling that something related to gensyms is behind #10045, which may also be an issue on 32-bit Linux rather than a strictly-Windows problem.

**Comment by mbauman** [comment]
> if … we can stop making numbers iterable

Interesting! Just gave it [a shot](https://gist.github.com/mbauman/b5cae54a7e0541cc44a5).  There are a few intentional cases of `for i=1, j=...` in comprehensions for transposition, but those are easy fixes.  It looks like I can remove iteration if I replace it with a specialized `collect(x::Number) = [x]` to make `cat` happy.  The next big blocker is [`append_any` in base.jl](https://github.com/JuliaLang/julia/blob/753390bb7eb535c6b235e14914ccacf012b3a44f/base/base.jl#L180-L181), which I'm not sure how to resolve.  But this seems like another issue for another breaking PR.

**Comment by JeffBezanson** [comment]
It's a bit annoying to need to make a container to do `for i=1, j=...` in a comprehension.

**Comment by mbauman** [comment]
I played around a bit with fallbacks on `AbstractArray`, and as far as I can see, there's really no sensible way to do this without causing all sorts of ambiguity problems (both in Base and in packages).  So I'm marking this as breaking.

Of course the next step (returning views) will be even *more* breaking (and in more subtle ways).  Now that this is working, perhaps we could move towards bundling the two changes together again.  I could rebase this to eliminate the parser change, allowing packages to start using `Colon`-indexing, and then we can work on rebasing #9150 on top of this.

**Comment by timholy** [comment]
I don't think we can really return views until we figure out how bounds checking is supposed to work for user-defined types.

**Comment by tkelman** [comment]
> Now that this is working, perhaps we could move towards bundling the two changes together again.

What exactly would be the advantage of that?

**Comment by mlubin** [comment]
Yeah, no reason here to hold up on breaking things.

**Comment by mbauman** [comment]
Great! Then full speed ahead!

I've rebased into two commits to make sure that this is bisect-friendly.  It's good to go as far as I'm concerned.

**Comment by mbauman** [comment]
I've started playing around with AbstractArray fallbacks along the lines of the discussion in #10458.  If we can get something to work along those lines, this would no longer be a breaking change.  We may want to hold off on breaking things if we don't have to.

**Comment by timholy** [comment]
I'm thrilled to hear that. I am nearing completion (I hope) on two separate Array-related projects, one of which is ReshapedArrays. If we can centralize indexing with fewer or more dimensions in one place, it would [simplify some pretty unpleasant code](https://github.com/JuliaLang/julia/blob/5195cc82f5a0256f64900367578a75e1d76d93a5/base/subarray2.jl#L118-L144) that would otherwise have to be generated for each AbstractArray type.

So, godspeed!

**Comment by tkelman** [comment]
This was apparently passing. Would the tuple change influence anything here, or should it be rebased and merged soon. I believe this (and #10525) is on the critical path of array changes needed to move from 0.4-dev to 0.4-pre, right?

**Comment by mbauman** [comment]
It's just on hold (in my mind) since #10525 would make it non-breaking. That PR incorporates the first of these two commits -- that is, it allows indexing with Colon(), but does not include the parser changes.

I'd really like to see them both merged, so we may as well avoid the intermediate breakage. #10525 is getting close, but is still

**Comment by tkelman** [comment]
okay thanks for the clarification, and we all hate that button placement

**Comment by JeffBezanson** [comment]
@mbauman I'm guessing this is next on your list?

**Comment by mbauman** [comment]
Yup! Just sat down this evening to update this PR.  Was really easy to rebase once I removed the commit that became part of #10525.  This should be good to go now, too.

**Comment by tkelman** [comment]
```
error during bootstrap:
UndefVarError(var=:string)
```

wha?

**Comment by mbauman** [comment]
Hah, I suppose I should have tried building this first.  It's just that part of the indexing machinery isn't available by the time inference wants to use it.  Should be a simple fix.

**Comment by mbauman** [comment]
5/6 tests passed (one OOMkill). I'll rip the space-time continuum and reorder the commits so we don't have an intermediate breakage.  I'd prefer to keep them separate since they're discrete operations.

Then this will actually be good to go.

**Comment by tkelman** [comment]
> reorder the commits

Good call, thanks. I think I restarted a few other OOM failures here so the actual numbers were worse, but +1 for merging.

**Comment by StefanKarpinski** [comment]
@mbauman is having a hell of a week

**Comment by mbauman** [comment]
Phew!  Some week indeed.  :)

Now that the dust is starting to settle from #10525, I'd like to merge this soon.  This shouldn't be nearly as troublesome (but it will test #10525 more thoroughly).

**Comment by StefanKarpinski** [comment]
I'm all for it.

**Comment by mlubin** [comment]
Yes please

**Comment by mbauman** [comment]
Done!

**Comment by joehuchette** [comment]
:100: awesome!

**Comment by yuyichao** [comment]
Cool!

**Comment by tkelman** [comment]
We should really start re-running appveyor on some of these more complicated PR's right before merging. This is freezing during second-stage inference builds on win64 https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.5619/job/xln3xt63xsxs4m1i, 100% of the time. If no one has a fix right away I think we'll need to revert.

**Comment by yuyichao** [comment]
@tkelman I was going to re-enable the bad commit in my gc codgen PR to test this. Do you have a backtrace to see where it gets stuck?

**Comment by tkelman** [comment]
I don't think there's any way of getting a backtrace while frozen in compiling inference. Maybe I could try attaching gdb, but the backtraces aren't always great on Windows. I might have a much better fix, taking Colon `setindex!` out of core inference and moving it to something later, like arraymath.jl (for lack of a better home). I'll replace and rename my "Revert" PR if that works locally.

**Comment by yuyichao** [comment]
> but the backtraces aren't always great on Windows.

I don't have any experience with backtrace on windows but that might be useful enough...

**Comment by tkelman** [comment]
`julia-debug.exe` does not exhibit the freeze, but I'll see if I can get anything meaningful out of the non-debug exe in gdb. Meanwhile, waiting on CI but I think #11678 will work and be a much better fix than reverting (sorry for being so revert-happy, but the way our CI is set up does not always satisfy the [Not Rocket Science Rule](http://graydon.livejournal.com/186550.html)).
