### PR TITLE
delete_method: remove method from any pre-existing ambiguities

### LINKED ISSUE #28899: Method deletion ambiguity recomputation fails for Union
#25050 recomputed ambiguities but clearly missed a case:

```julia
julia> struct A end

julia> struct B end

julia> foo(a::Union{Nothing, A}) = 1
foo (generic function with 1 method)

julia> foo(a::Union{Nothing, B}) = 2
foo (generic function with 2 methods)

julia> mths = methods(foo)
# 2 methods for generic function "foo":
[1] foo(a::Union{Nothing, A}) in Main at REPL[3]:1
[2] foo(a::Union{Nothing, B}) in Main at REPL[4]:1

julia> Base.delete_method(first(mths))

julia> methods(foo)
# 1 method for generic function "foo":
[1] foo(a::Union{Nothing, B}) in Main at REPL[4]:1

julia> foo(nothing)
ERROR: MethodError: foo(::Nothing) is ambiguous. Candidates:
  foo(a::Union{Nothing, A}) in Main at REPL[3]:1
  foo(a::Union{Nothing, B}) in Main at REPL[4]:1
Possible fix, define
  foo(::Nothing)
Stacktrace:
 [1] top-level scope at none:0
```

(It works fine if you delete first and then define the `B` method.)

### PR DESCRIPTION
**Pull request by timholy**
Fixes #28899. Kinda amazing we never noticed this til now.

### CODE REVIEW

**Review by vtjnash — CHANGES_REQUESTED** [review]
The ambiguity doesn't disappear, it should simply be no longer applicable during lookup

**Comment by timholy** [comment]
So you mean the fix should be here? 
https://github.com/JuliaLang/julia/blob/3ab56f19a81a1d658a02750b48abbd63950ef248/src/gf.c#L2006-L2016
Since we don't store the `max_world` in the method itself, wouldn't you have to walk the method table's `typemapentry` and find instances of `mambig`? Doesn't that introduce an `O(MN)` step, where `M` is the number of methods previously determined to be possibly-ambiguous (i.e., `length(m.ambig)`) and `N` is the number of methods in the `typemapentry`? Or perhaps we should just get rid of the `ambig` field altogether and recompute everything by type intersection every time?

What's the downside of just removing it from `m.ambig`? (Maybe someone will reset the `max_world` and "undelete" the method?) Stated differently, what's the purpose of caching this in `m.ambig` at all?

**Comment by timholy** [comment]
Bump @vtjnash. I'm willing to implement it but I need to know more about why this isn't the right solution. AFAIK the `ambig` field is just a list of methods that should be checked by future dispatch events, and if the method has been deleted I am failing to understand why it would need to be checked.

**Comment by vtjnash** [comment]
> Since we don't store the max_world in the method itself, wouldn't you have to walk the method table's typemapentry and find instances of mambig?

We can just store it there—we already have copies of many of the other fields (sig, min-world, name). Currently, it seems like the purpose of Method is essentially just to contain the information about how to find it in the method table.

> checked by future dispatch events

It's only supposed to check them for dispatch events in the applicable world (e.g. if someone is using a generated function, any later change in method definitions shouldn't be visible to them)

**Comment by timholy** [comment]
OK, but redesigning `Method` seems a bit beyond the scope of this PR since it affects the whole compiler chain.

So, is reasonable to fix this by implementing the `O(NM)` algorithm?

**Comment by vtjnash** [comment]
Redesign, hm? Just add the field. That won't change anything about `Method`.

**Comment by timholy** [comment]
I'm just envisioning changes sprinkled throughout `src/` (e.g., `dump.c`) but perhaps I'm being overly pessimistic. I'll give it a whirl.

**Comment by vtjnash** [comment]
Mostly just need to revert https://github.com/JuliaLang/julia/commit/a52919962d527029ebed75b713ef9fa40815ed6e#diff-ab8c4a99930a43168794a7bd3b8bfa91

File: base/compiler/utilities.jl [hunk 1]
```diff
@@ -112,6 +112,11 @@ function retrieve_code_info(linfo::MethodInstance)
         return get_staged(linfo)
     else
         # TODO: post-inference see if we can swap back to the original arrays?
+        println(linfo)
+        println(linfo.def)
+        println(typeof(linfo.def))
+        println(typeof(m.source))
+        println(m.source)
```
Comment (timholy) [inline base/compiler/utilities.jl]: With a `make debug`, this debugging output produces lots of lines like (nb I've manually shortened the arrays)
```julia
print(Core.CoreSTDOUT, Type{Core.MethodInstance})
Core.print(...)
Method
Array{UInt8, 1}
Array{UInt8, (66,)}[0x00, 0x03, 0x00, 0x00, 0x00, ...]
show(Core.CoreSTDOUT, Type{Core.MethodInstance})
Core.show(...)
Method
Array{UInt8, 1}
Array{UInt8, (119,)}[0x00, 0x03, 0x00, 0x00, ...]
```
which all seem fine.

Then we get to the fatal error
```julia
validate_code_in_debug_mode(Core.MethodInstance, Core.CodeInfo, String)
Core.Compiler.validate_code_in_debug_mode(...)
Method
Core.MethodInstance
Array{UInt8, (452,)}[0x00, 0x07, 0x00, 0x00, ...]
error during bootstrap:
LoadError(at "compiler/compiler.jl" line 3: LoadError(at "compiler/bootstrap.jl" line 8: MethodError(f=typeof(Core.Compiler.copy_code_info)(), args=(Array{UInt8, (452,)}[0x00, 0x07, 0x00, 0x00, ...],), world=0x0000000000000e5d)))
```
Notice that `m.source` is a `MethodInstance`, [which shouldn't happen](https://github.com/JuliaLang/julia/blob/39e5742557cf56f26e1eccd28ab52d258ae19863/src/julia.h#L277) and is inconsistent with the actual value that is printed. Interestingly, you can explain this if this is an off-by-one bug in the field offset and you're picking up `unspecialized` instead. Since I added a field to `method_t`, this seems plausible. Know of any places where field offsets are likely to be hard-coded?

Comment (timholy) [reply base/compiler/utilities.jl]: Got it: https://github.com/JuliaLang/julia/blob/2346be896129f594ce2e6104f612828468e63bfc/src/jltypes.c#L2218
Just happened to stumble across it while searching.

**Comment by timholy** [comment]
OK, ready for another round of review.

**Comment by timholy** [comment]
...and now with bonus features (aka, passing tests even with `FORCE_ASSERTIONS=1` :wink:)

Is it possible to run this against the package ecosystem and see whether adding that field to `Method` breaks anything? Or does that happen only when someone tries to do the backport?

**Comment by quinnj** [comment]
I think w/ @Keno 's new PkgEval it should be possible, though I'm not sure how much we worry about the number packages that actually pass tests currently. I think we have a critical mass that a PkgEval run would given decent signal.

**Comment by ararslan** [comment]
FWIW NewPkgEval takes less time to run than any of our current CI builds.

**Comment by timholy** [comment]
How does one run it? If there's a bot it's one of the many discussions I've missed.

**Comment by ararslan** [comment]
> How does one run it?

The "one" must be @Keno and he must be brought a sacrificial offering.

**Comment by timholy** [comment]
> he must be brought a sacrificial offering

OK, that's easy: I'll find a rare but serious bug that is triggered by a combination of LLVM, our inlining engine, and 32bit that nevertheless can't be fixed without rewriting both Julia's compiler and all of LLVM. That should keep him happy for at least 3 days.

**Comment by timholy** [comment]
@vtjnash, any chance you can take a second look at this? Revise has started working around this bug whenever it can, but we should still fix the core problem. I *think* this is ready to merge, but I won't do so without your approval.

**Review by vtjnash — APPROVED** [review]
