### PR TITLE
[internals] add time metrics for every CodeInstance

### LINKED ISSUE #56115: snoop_inference is broken on latest after stackless inference change
We should be able to restore basically the old behavior with the new stack.

> I wasn't certain how to maintain the old code, since it was working with incomplete and inaccurate information available. Now all required information is available in `function typeinf(interp::AbstractInterpreter, frame::InferenceState)`, so this could be reimplemented there in some form.

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/pull/55575#discussion_r1795702974_

### PR DESCRIPTION
**Pull request by vtjnash**
Adds 4 new Float16 fields to CodeInstance to replace Compiler.Timings with continually collected and available measurements.

Sample results on a novel method signature:

    julia> @time code_native(devnull, ÷, dump_module=false, (Int32, UInt16));
      0.006262 seconds (3.62 k allocations: 186.641 KiB, 75.53% compilation time)

    julia> b = which(÷, (Int32, UInt16)).specializations[6].cache
    CodeInstance for MethodInstance for div(::Int32, ::UInt16)

    julia> reinterpret(Float16, b.time_infer_self)
    Float16(0.0002766)

    julia> reinterpret(Float16, b.time_infer_total)
    Float16(0.00049)

    julia> reinterpret(Float16, b.time_infer_cache_saved)
    Float16(0.02774)

    julia> reinterpret(Float16, b.time_compile)
    Float16(0.003773)

Closes https://github.com/JuliaLang/julia/issues/56115

### CODE REVIEW

**Comment by gbaraldi** [comment]
Are float32s too awful to use here? I really would like to avoid depending on Float16 to work in C correctly (The ABI horrors it caused have scarred me). Also UInt16 has a larger range than Float16 ;)

**Comment by vtjnash** [comment]
Fixed point won't work (insufficient range), though exponential would (at a significant loss of accuracy compared to Float16). I avoided using any of the Float16 in C, just calling our emulation functions directly using the uint16_t ABI to avoid any issues. All math is explicitly done using Float64 or double, so here we are just using it as a storage format (as IEEE intended).

File: base/hashing.jl [hunk 1]
```diff
@@ -98,6 +98,87 @@ function hash_integer(n::Integer, h::UInt)
...
+        return hx_NaN ⊻ h # NaN does not have a stable bit pattern
+    end
+    return hash_uint64(bitcast(UInt64, x)) - 3h
+end
+
+hash(x::Float32, h::UInt) = hash(Float64(x), h)
+
+function hash(x::Float16, h::UInt)
+    # see comments on trunc and hash(Real, UInt)
+    if isfinite(x) # all finite Float16 fit in Int64
```
Comment (gbaraldi) [inline base/hashing.jl:126]: I think it even fits in Int32, though not sure if there is much to be gained here

Comment (vtjnash) [reply base/hashing.jl:126]: I am not going to change the hash code in this PR

**Comment by topolarity** [comment]
This is awesome. I've wanted something like this for a long time.

**Comment by IanButterworth** [comment]
This is already on the 1.12 milestone but just to highlight that without it, if I understand correctly, `PrecompileTools.@compile_workload` is broken, and TTFX on 1.12 back to the olden times.
