### PR TITLE
fix reinterpret(Char, ::UInt32) for "unnatural" values (fix #29181)

### LINKED ISSUE #29181: Char reinterpret is (kind of) broken
```jl
julia> reinterpret(UInt32, reinterpret(Char, 0x00ff0000))
0x00000000

julia> u2c(u::UInt32) = reinterpret(Char, u)
u2c (generic function with 1 method)

julia> c2u(c::Char) = reinterpret(UInt32, c)
c2u (generic function with 1 method)

julia> u2c(0x00ff0000)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> c2u(u2c(0x00ff0000))
0x00000000

julia> u2u(u) = c2u(u2c(u))
u2u (generic function with 1 method)

julia> u2u(0x00ff0000)
0x00ff0000

julia> c2u(u2c(0x00ff0000))
0x00000000
```
The fortunate thing is that it doesn't seem to be broken in a way that affects any `Char` values that can be produced naturally—you can only produce the values for which this is broken through reinterpret of `UInt32` values.

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

File: src/datatype.c [hunk 1]
```diff
@@ -689,8 +689,9 @@ static jl_value_t *boxed_char_cache[128];
 JL_DLLEXPORT jl_value_t *jl_box_char(uint32_t x)
 {
     jl_ptls_t ptls = jl_get_ptls_states();
-    if (0 < (int32_t)x)
-        return boxed_char_cache[x >> 24];
+    uint32_t u = __builtin_bswap32(x);
```
Comment (JeffBezanson) [inline src/datatype.c]: We have `bswap_32` defined for this for a few platforms.

Comment (StefanKarpinski) [reply src/datatype.c]: "for a few platforms" sounds unlikely to work everywhere. @yuyichao, @Keno, @vtjnash, do any of you have advice on how to spell this operation correctly and portably?

Comment (vchuravy) [reply src/datatype.c]: `bswap_32` is the correct version since it takes care of the difference between clang, ICC, MSVC, or not having the builtin available at all.

see https://github.com/JuliaLang/julia/blob/75075114d407eb5d4bf1604880e3423052d96887/src/support/utils.h#L32-L57

**Comment by StefanKarpinski** [comment]
We're seeing a lot of httpbin flakiness again. Time to switch, @staticfloat?

**Comment by staticfloat** [comment]
@StefanKarpinski your wish is my command: https://github.com/JuliaLang/julia/pull/29228
