### PR TITLE
[JuliaLowering] Refactor function desugaring

### LINKED ISSUE #155: Unnamed arguments not marked hidden / unnamed
flisp avoids printing unused argument names in Methods:
```julia
julia> myzeros(::Type{T}, ::Type{S}, ::Type{R}, dims::Tuple{Vararg{Integer, N}}, dims2::Tuple{Vararg{Integer, M}}) where {T, R, S, M, N} = (x = 1)
julia> methods(myzeros, Tuple{Type{<:Integer}, Type{>:String}, Type{T} where Signed<:T<:Real, Tuple{Vararg{Int}}, NTuple{4,Int}})
# 1 method for generic function "myzeros" from Main:
 [1] myzeros(::Type{T}, ::Type{S}, ::Type{R}, dims::NTuple{N, Integer}, dims2::NTuple{M, Integer}) where {T, R, S, M, N}
     @ REPL[1]:1
```
JL fills these with auto-generated names:
```julia
julia> myzeros(::Type{T}, ::Type{S}, ::Type{R}, dims::Tuple{Vararg{Integer, N}}, dims2::Tuple{Vararg{Integer, M}}) where {T, R, S, M, N} = (x = 1)
julia> methods(myzeros, Tuple{Type{<:Integer}, Type{>:String}, Type{T} where Signed<:T<:Real, Tuple{Vararg{Int}}, NTuple{4,Int}})
# 1 method for generic function "myzeros" from Main:
 [1] myzeros(var"#arg1#"::Type{T}, var"#arg2#"::Type{S}, var"#arg3#"::Type{R}, dims::NTuple{N, Integer}, dims2::NTuple{M, Integer}) where {T, R, S, M, N}
     @ REPL[1]:1
```

Not sure if this has other downstream consequences, but it would be nice to recover the "good" printing.

This also causes the InteractiveUtils tests to fail, since they scan for the unnamed argtype: https://github.com/JuliaLang/julia/blob/5308f13b01ee989f552c31c3ab38ab5c97b534cb/stdlib/InteractiveUtils/test/highlighting.jl#L12

### LINKED ISSUE #156: Destructuring in callable type name fails
```
julia> struct X
       x
       y
       end

julia> JuliaLowering.include_string(Main, "function ((;x,y)::X)(arg); x + y + arg; end")
ERROR: internal lowering bug:
function ((;x,y)::X)(arg); x + y + arg; end
#         └────┘ ── `jl_assert(kind(c) in KSet"Identifier BindingId Placeholder", _)`: c
Expression:
  (call (call core.apply_type core.NamedTuple (call core.tuple :x :y)) (call core.tuple x y))
```

### LINKED ISSUE #157: Default kwargs in anonymous functions don't work
```
julia> JuliaLowering.include_string(Main, "((; keyword_arguments_my_unbeloved=2) -> nothing)()")
ERROR: UndefVarError: `#->#1` not defined in `Main`
```

### LINKED ISSUE #158: `TypeVar` not correctly expanded for `function` w/ multiple positional defaults
```julia
julia> JuliaLowering.include_string(Main, """
       function foo(::Type{T}=Vector{UInt8}, sz=Base.aligned_sizeof(eltype(T))) where T
           return sz
       end
       """)
foo (generic function with 3 methods)

julia> foo()
8
```

This should return 1, of course.

It looks like JuliaLowering tries to fill in multiple defaults at once:
```julia
julia> @code_typed optimize=false foo()
CodeInfo(
1 ─ %1  = Main.Vector::Core.Const(Vector)
│   %2  = Main.UInt8::Core.Const(UInt8)
│   %3  =   builtin Core.apply_type(%1, %2)::Core.Const(Vector{UInt8})
│   %4  = Main.Base::Core.Const(Base)
│   %5  =   dynamic Base.getproperty(%4, :aligned_sizeof)::Core.Const(Base.aligned_sizeof)
│   %6  = Main.eltype::Core.Const(eltype)
│   %7  = T::Core.Const(T)
│   %8  =   dynamic (%6)(%7)::Core.Const(Any)
│   %9  =   dynamic (%5)(%8)::Core.Const(8)
│   %10 =   dynamic (#self#)(%3, %9)::Core.Const(8)
└──       return %10
) => Int64
```

compared to the chaining done in flisp:
```julia
julia> @code_typed optimize=false foo()
CodeInfo(
1 ─ %1 = Main.Vector::Core.Const(Vector)
│   %2 = Main.UInt8::Core.Const(UInt8)
│   %3 =   builtin Core.apply_type(%1, %2)::Core.Const(Vector{UInt8})
│   %4 =   dynamic (#self#)(%3)::Core.Const(1)
└──      return %4
) => Int64
```

but I am not sure this "optimization" can emulate static parameters that depend on expanding defaults.

Encountered in the `Mmap` stdlib (https://github.com/JuliaLang/julia/blob/331421e83770b4492e3fda65686d8b8459053786/stdlib/Mmap/src/Mmap.jl#L267-L271)

### PR DESCRIPTION
**Pull request by mlechu**
A number of fixes that hopefully make up for the large diff.  Currently atop https://github.com/JuliaLang/julia/pull/61213

Changes:
1. Handle destructuring (tuple) params first, like flisp does, since it's
   simpler to assume every param is a single identifier later.
2. Structure "expand function", "method-def-expr", "keyword-method-def-expr",
   and "optional positional wrappers" to call each other like flisp does.  I
   think it's simpler this way, and it also affects the order of the methods
   (closure boxes unfortunately depend on this right now; see discussion in
   #61051).
3. Don't rewrite constructors with callbacks passed to expand_function_def.  I
   think this was originally since matching the function name was too messy, but
   validation.jl and pattern-matching make this doable (even flisp uses its own
   pattern-lambda language here)
4. Keep args bundled with their types for longer
5. Keep typevars bundled with their bounds for longer with new `K"_typevar"`
   (flisp does this with 3-long lists).
6. Set the first argument to `:method` expressions to `nothing` if the function
   is local.  I think flisp does this to remove unnecessary data dependencies.
7. Add `valid_st2` (just for internal use).
8. Push the generated function wrapper (previously `generated_function`, now
   `_generated_body`) down to wrap the body of the function instead, and 
   introduce it in `est_to_dst` instead of macro expansion.  That information
   needs to travel with the function body anyway to get to the right 
   `method_def_expr` calls.

Fixes:
- fix https://github.com/JuliaLang/JuliaLowering.jl/issues/158, failure to
  detect inter-arg static param dependencies.  As discussed with @topolarity,
  we're trying out something slightly different from flisp commented on in
  `optional_positional_defs`
- fix https://github.com/JuliaLang/JuliaLowering.jl/issues/157.
- fix https://github.com/JuliaLang/JuliaLowering.jl/issues/156.  Destructuring
  args are now treated the same in function-name position.
- fix https://github.com/JuliaLang/JuliaLowering.jl/issues/155, unused args not
  marked unused.  This is part of function desugaring in flisp and I've tried to
  match that logic within the JL framework.  This means `Symbol("#unused#")`
  becomes `K"Placeholder"` in `est_to_dst`, the reverse happens in
  `to_lowered_expr`, and generated functions do their own detection for the
  quoted arglist.
- Initial support for method table overlays
- fix and test anonymous generated functions

https://github.com/JuliaLang/JuliaLowering.jl/issues/152 is also worth checking

TODO (later):
- Support globalref properly (validator and existing lowering recognize it, but
  it isn't generally expected as an lvalue in desugaring)
- Overlays need more work
- Destructured args in generated functions may need to be special-cased, since
  desugaring pushes statements into the body
- Fix `where` expression in function name
  (https://github.com/JuliaLang/julia/pull/35861).  This PR fixes the desugaring
  part, but scope resolution appears to fail.

### CODE REVIEW

**Comment by topolarity** [comment]
Nice!

Any significant divergences from flisp worth calling out? Any chance the constructor changes are separable from the args / generator desugaring? They seem like their own bugbear.

File: JuliaLowering/src/desugaring.jl [hunk 1]
```diff
@@ -3611,155 +3246,70 @@ function _new_call_convert_arg(ctx, full_struct_type, field_type, field_index, v
     ]
 end
 
-function default_inner_constructors(ctx, srcref, global_struct_name,
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl:3615]: Was this just unused before? Ah this was https://github.com/JuliaLang/julia/pull/60782

**Comment by mlechu** [comment]
> Any significant divergences from flisp worth calling out?

No new significant ones.  There are still the existing divergences with generated functions, `K"method_defs"`/`K"function_decl"` into closure conversion, and typevar resolution in signatures.

> Any chance the constructor changes are separable from the args / generator desugaring

Would be nice, but both are somewhat tied to function desugaring.  The constructor changes aren't too huge.

File: JuliaLowering/src/closure_conversion.jl [hunk 2]
```diff
@@ -486,12 +498,14 @@ function _convert_closures(ctx::ClosureConversionCtx, ex)
...
-        elseif is_closure
-            body
+        if is_closure
+            if ctx.is_toplevel_seq_point
+                body
+            else
+                # Move methods out to a top-level sequence point.
+                push!(ctx.toplevel_stmts, body)
+                @ast ctx ex (::K"TOMBSTONE")
+            end
```
Comment (mlechu) [inline JuliaLowering/src/closure_conversion.jl:508]: Undid (2) from https://github.com/JuliaLang/julia/pull/61001: lifting stuff makes it harder to reason about data flow

File: JuliaLowering/src/validation.jl [hunk 3]
```diff
@@ -1135,3 +1147,142 @@ function _assert_syntaxtree(st::SyntaxTree, parents::Vector{NodeId}, vr)
...
+         vst2(vcx, cconv) &
+         all(vst2, vcx, roots_args)
+    [K"cfunction" [K"Value"] fptr [K"static_eval" rt] [K"static_eval" at] [K"Symbol"]] ->
+         vst2(vcx, fptr) & vst2(vcx, rt) & vst2(vcx, at)
+
+    [K"isdefined" x] -> vst1_ident(vcx, x)
+    [K"isglobal" [K"Placeholder"]] -> pass()
+    [K"islocal" [K"Placeholder"]] -> pass()
+    [K"isglobal" x] -> vst1_ident(vcx, x)
+    [K"islocal" x] -> vst1_ident(vcx, x)
```
Comment (topolarity) [inline JuliaLowering/src/validation.jl]: Should this be calling `vst1` functions?

Seems like a potential issue since the contexts don't match up

File: JuliaLowering/src/desugaring.jl [hunk 4]
```diff
@@ -2405,902 +2307,636 @@ end
...
-        # `function A.f(x,y) ...`
-        name = ex[2].name_val
-    else
-        return true
+# The Julia runtime associates the code generator with the non-generated method
+# by adding (meta generated ...) to the non-generated body
+function generated_method_defs(ctx, src, mtable, sparams, argl, body, rett)
+    @jl_assert kind(body) === K"_generated_body" && numchildren(body) == 2 body
+    gen_name = let mangled = reserve_module_binding_i(
+        ctx.mod, "#$(isnothing(mtable) ? "_" : mtable)@generator#")
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl]: Is there a reason this is different than the logic at https://github.com/JuliaLang/julia/pull/61342/changes#diff-9f30e34c994aa9aae04f0e2bf7b1d6718bde7c3c3da647cfc8068921b4431927R2637?

File: JuliaLowering/src/desugaring.jl [hunk 5]
```diff
@@ -2405,902 +2307,636 @@ end
...
-            for j = i+1:n_typevars
-                if typevar_used[j] && contains_identifier(typevar_stmts[j], tn)
-                    found_used = true
-                    typevar_used[i] = true
-                    break
-                end
+function select_used_typevars(uses::SyntaxList, typevars::SyntaxList)
+    used = BitVector(undef, length(typevars))
+    for (i, tv) in enumerate(typevars)
+        @jl_assert kind(tv) === K"_typevar" v
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl]:
```suggestion
        @jl_assert kind(tv) === K"_typevar" tv
```

File: JuliaLowering/src/desugaring.jl [hunk 6]
```diff
@@ -2405,902 +2307,636 @@ end
...
+            _ -> false
+        end
+        keywords_method_def_expr(ctx, src, mtable, sparams, argl, body, rett, pos_va)
     else
-        @ast ctx arglist [K"call"
-            arrowname::K"Placeholder"
-            children(expand_arrow_args(ctx, arglist))...
-        ]
+        @ast ctx src [K"block"
+            is_core_nothing(mtable) ? nothing : [K"function_decl" mtable]
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl]: Can we rely on this being core nothing from flisp and / or expanded `macro`s as well?

File: JuliaLowering/src/desugaring.jl [hunk 7]
```diff
@@ -2405,902 +2307,636 @@ end
...
+# method with all args filled.  As an optimization, a wrapper can fill all
+# remaining default values as long as we can rule out any of the additional
+# default values depending on the values of non-`passed` arguments.
+#
+# flisp checks dependencies by searching each additional default for every
+# subexpression of `arg::type` for every non-`passed` `arg` before it.  We only
+# check that static params in `::type` are not referenced in later defaults, and
+# use `(= arg default)` to handle references to `arg`. (possible TODO: it's
+# unclear why flisp doesn't do this; too many slots?)
+function optional_positional_defs(ctx, src, mtable, sparams, argl, body, rett)
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl:2528]: Does this interact well with destructuring? e.g. `foo((x,y) = (1,x), (z,w) = (y, (x, y))) = (x,y,z,w)`

Hmm no, it does not but neither does `flisp` handle this well.

**Review by topolarity — APPROVED** [review]
Thanks @mlechu 

Might be nice to add some `@overlay` tests if the basic support is enough for some examples to work (`@test_broken` is good too)

Otherwise coverage (and changes!) look pretty good to me. Only a few minor issues to flag.

File: JuliaLowering/src/desugaring.jl [hunk 8]
```diff
@@ -2405,902 +2307,636 @@ end
...
+        ctx.mod, "#$(isnothing(mtable) ? "_" : mtable)@generator#")
+        new_global_binding(ctx, src, mangled, ctx.mod)
+    end
+
+    gen_mdef = let arg1_name = newsym(ctx, argl[1], "#self#"),
+         gen_argl = SyntaxList(
+            @ast(ctx, src, [K"::" arg1_name [K"function_type" gen_name]]),
+            @ast(ctx, src, [K"::"
+                # TODO: correct scope layer?
+                "__context__"::K"Identifier"(scope_layer=get(mtable, :scope_layer, 1))
```
Comment (topolarity) [inline JuliaLowering/src/desugaring.jl:2480]: TODO indeed:
```julia
julia> JuliaLowering.include_string(Main, """
       @generated function f((a,b)::T) where T
           T
       end
       """)
f(f (generic function with 1 method)

julia> f((1,2))
ERROR: BoundsError: attempt to access 1-element Vector{JuliaLowering.ScopeLayer} at index [3]
```

The bug may not be here, that's just a guess. Either way something to add to the tests I guess

File: JuliaLowering/src/desugaring.jl (hunk 6 above)
Comment (mlechu) [reply JuliaLowering/src/desugaring.jl]: `mtable` here is the processed output of `expand_function_arg1`, which I believe produces the `K"core"` nothing in the right cases (other than `K"Value"`, which I'll fix this week with proper globalref support)  Added a comment to `expand_function_arg1`.

File: JuliaLowering/src/desugaring.jl (hunk 8 above)
Comment (mlechu) [reply JuliaLowering/src/desugaring.jl:2480]: (from meeting) This is the TODO in `prepend_function_body`
